### ISSUE TITLE
Open Source VS Code

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#1]

**Comment by jbondc** [comment]
:+1: :sunglasses:

**Comment by jrieken** [comment]
:dancers:

**Comment by joaomoreno** [comment]
This seems fixed now! :ok_hand:

**Comment by chrisdias** [comment]
Done!

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

Error: Not supported<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#L110:9](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/common/viewModel/splitLinesCollection.ts#L110:9)<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#L682:42 (getInputColumnOfOutputPosition)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/common/viewModel/splitLinesCollection.ts#L682:42 (getInputColumnOfOutputPosition))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#L478:20 (convertOutputPositionToInputPosition)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/common/viewModel/viewModelImpl.ts#L478:20 (convertOutputPositionToInputPosition))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#L482:19 (convertViewPositionToModelPosition)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/common/viewModel/viewModelImpl.ts#L482:19 (convertViewPositionToModelPosition))<br />[/vs/editor/browser/view/viewController.ts#L251:24 (convertViewRangeToModelRange)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/view/viewController.ts#L251:24 (convertViewRangeToModelRange))<br />[/vs/editor/browser/view/viewController.ts#L260:26 (convertViewToModelRange)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/view/viewController.ts#L260:26 (convertViewToModelRange))<br />[/vs/editor/browser/view/viewController.ts#L279:7 (convertViewToModelMouseEvent)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/view/viewController.ts#L279:7 (convertViewToModelMouseEvent))<br />[/vs/editor/browser/controller/mouseHandler.ts#L254:22 (emitMouseMove)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/controller/mouseHandler.ts#L254:22 (emitMouseMove))<br />[/vs/editor/browser/controller/mouseHandler.ts#L168:82 (_onMouseMove)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/controller/mouseHandler.ts#L168:82 (_onMouseMove))<br />[/vs/editor/browser/controller/mouseHandler.ts#L68:8 (_destination)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/controller/mouseHandler.ts#L68:8 (_destination))<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

Error: Not supported<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#L110:9](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/common/viewModel/splitLinesCollection.ts#L110:9)<br />[/vs/editor/common/viewModel/splitLinesCollection.ts#L682:42 (getInputColumnOfOutputPosition)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/common/viewModel/splitLinesCollection.ts#L682:42 (getInputColumnOfOutputPosition))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#L478:20 (convertOutputPositionToInputPosition)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/common/viewModel/viewModelImpl.ts#L478:20 (convertOutputPositionToInputPosition))<br />[/vs/editor/common/viewModel/viewModelImpl.ts#L482:19 (convertViewPositionToModelPosition)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/common/viewModel/viewModelImpl.ts#L482:19 (convertViewPositionToModelPosition))<br />[/vs/editor/browser/view/viewController.ts#L251:24 (convertViewRangeToModelRange)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/view/viewController.ts#L251:24 (convertViewRangeToModelRange))<br />[/vs/editor/browser/view/viewController.ts#L260:26 (convertViewToModelRange)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/view/viewController.ts#L260:26 (convertViewToModelRange))<br />[/vs/editor/browser/view/viewController.ts#L279:7 (convertViewToModelMouseEvent)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/view/viewController.ts#L279:7 (convertViewToModelMouseEvent))<br />[/vs/editor/browser/controller/mouseHandler.ts#L254:22 (emitMouseMove)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/controller/mouseHandler.ts#L254:22 (emitMouseMove))<br />[/vs/editor/browser/controller/mouseHandler.ts#L168:82 (_onMouseMove)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/controller/mouseHandler.ts#L168:82 (_onMouseMove))<br />[/vs/editor/browser/controller/mouseHandler.ts#L68:8 (_destination)](https://github.com/microsoft/vscode/blob/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/src/vs/editor/browser/controller/mouseHandler.ts#L68:8 (_destination))<br />
