### ISSUE TITLE
Search does not search all files.

### ISSUE THREAD

**Issue by jake-jester-nih** [microsoft/vscode#100002]
Issue Type: <b>Bug</b>

I am using WSL 1. I have a fairly large project. In a settings.php file there is a URL at the end of it. When I search for a sub string of that URL, it does not appear in the full search results. If I open the file, it will then appear in the full search results. Switching exclude on and off does nothing.

Is there a limit to the depth or number of files search will include? I have no include or exclude settings. 

With the file open in an editor:

![image](https://user-images.githubusercontent.com/64654554/84512447-03614680-ac96-11ea-8c48-0b357be8abf8.png)

Without the file open in an editor:

![image](https://user-images.githubusercontent.com/64654554/84512158-8d5cdf80-ac95-11ea-97f6-a946ab19b4ad.png)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-17134-Microsoft
Remote OS version: Linux x64 4.4.0-17134-Microsoft
Remote OS version: Linux x64 4.4.0-17134-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 4100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (52.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|31%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17134-Microsoft|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 4100)|
|Memory (System)|63.95GB (52.22GB free)|
|VM|31%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17134-Microsoft|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 4100)|
|Memory (System)|63.95GB (52.22GB free)|
|VM|31%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17134-Microsoft|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 4100)|
|Memory (System)|63.95GB (52.22GB free)|
|VM|31%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
bracket-pair-colorizer|Coe|1.0.61
vue|jcb|0.1.5
dotenv|mik|1.0.1
vscode-docker|ms-|1.2.1
remote-wsl|ms-|0.44.2
fast-arrow|vin|1.0.7
JavaScriptSnippets|xab|1.8.0
yaml2json|ahe|0.0.3
vscode-intelephense-client|bme|1.4.1
jshint|dba|0.10.21
vscode-eslint|dba|2.1.5
vscode-html2pug|dba|4.0.0
gitlens|eam|10.2.2
prettier-vscode|esb|5.0.0
vscode-jest-runner|fir|0.4.22
vscode-pull-request-github|Git|0.16.1
beautify|Hoo|1.5.0
regionfolder|map|1.0.10
VS-code-drupal|mar|0.0.12
vscode-language-babel|mgm|0.0.27
python|ms-|2020.5.86806
powershell|ms-|2020.6.0
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0
explorer-exclude-vscode-extension|Red|1.2.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
>Switching exclude on and off does nothing.

Maybe this is what you are referring to, but if you toggle that button in the "files to exclude" box off, does that make a difference?
