### ISSUE TITLE
UI problem,white splash in Dark theme

### ISSUE THREAD

**Issue by superiums** [microsoft/vscode#100071]
Issue Type: <b>Bug</b>

1.install vscode in arch.
2.start vscode.
3.click any menu. 

you will see white splash before the dark menu appears.

VS Code version: Code - OSS 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-11T14:57:41.218Z)
OS version: Linux x64 5.7.2-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800U with Radeon Graphics (16 x 1713)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.07GB (12.88GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by IllusionMH** [comment]
Looks like duplicate of #80798 could you check that one and close this if it's duplicate.

You can also check exploration build from https://github.com/microsoft/vscode/issues/97270#issuecomment-626248706 to see if it helps (problem looks similar)

**Comment by superiums** [comment]
yes, it's same as #90798 .
very sorry that i missed it.
