### ISSUE TITLE
Reuse a single Search Editor tab per window

### ISSUE THREAD

**Issue by swrobel** [microsoft/vscode#100048]
I thought I'd flag to @JacksonKearl that I'm interested in this feature as well (since I know @kolpav is), as [discussed here](https://github.com/microsoft/vscode/issues/23931#issuecomment-597786597).

I love the search editor, but due to having bound it to cmd+shift+F to replace the existing search functionality, I end up with a ton of open Search Editor tabs, when what I really want is a max of 1 that is reused for each new search. When this setting is enabled, I would imagine that it would focus that tab on invocation of `search.action.OpenNewEditor` (or perhaps this would just be a separate command?), and highlight all of the currently-entered text in the search box.

**Comment by JacksonKearl** [comment]
I agree, I could see this as a new command.

**Comment by JacksonKearl** [comment]
`search.action.openEditor`, also available in command pallet as "Open Search Editor" (as opposed to "New Search Editor" né "Open new Search Editor")

**Comment by pstrum** [comment]
With "New Search Editor," if I have a selection it is put into the input of the new search editor. However, with "Open Search Editor" the selection does not replace what was already in the input of the existing search editor. Is this the correct behavior? Is there a setting to enable selection to auto-fill the existing search editor when I run the new `search.action.openEditor` command?

**Comment by JacksonKearl** [comment]
@pstrum no setting for that, though it would make sense for a feature request.

**Comment by hesting15** [comment]
When several search editors are open, by triggering `search.action.openEditor` we always go to the latest window. It would be nice to cycle through search editors if we are already inside search editor.

**Comment by JacksonKearl** [comment]
@hesting15 again no setting for that, though it would make sense for a feature request.
