### ISSUE TITLE
Can I sell any program I made on Visual Studio Code?

### ISSUE THREAD

**Issue by Specs10** [microsoft/vscode#100064]
**I have a very _major_ and important question. Punctuality is appreciated:** 
## Can I use anything that I developed on Visual Studio Code with commercial purposes, i.e., selling any app/game/whatever thing I developed on that software? There's absolutely NOTHING about this in VS Code License Terms.

Please respond as quickly as possible.

**Comment by gjsjohnmurray** [comment]
/question

https://code.visualstudio.com/License/
