### ISSUE TITLE
IPC "File Watcher (chokidar)" crashed with exit code null and signal SIGABRT

### ISSUE THREAD

**Issue by ghuba** [microsoft/vscode#100091]
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

Steps to Reproduce:

Launch vscode by clicking on the icon

Error message:

![image](https://user-images.githubusercontent.com/4511360/84577414-b9995e80-ad70-11ea-90da-6f083bc7ea0f.png)

![image](https://user-images.githubusercontent.com/4511360/84577434-d170e280-ad70-11ea-9a8c-d2bb5aff7432.png)

Does this issue occur when all extensions are disabled?
Yes

I removed all the extensions but the error is still here. I also reinstalled vscode.

The error does **not** show up if I run

`$ /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code`

from the terminal. The error also does not show up if I run `code --disable-extensions`. 

The error does show up if I click on the vscode icon in the Applications folder (that's on macOS Catalina).

Similar but not identical errors seem to have been reported.

**Comment by ghuba** [comment]
I found the problem. It was caused by
`export DYLD_LIBRARY_PATH="/usr/local/lib"`
in my `.zshrc`. So some of the libraries being loaded were wrong.

**Comment by joeybaba** [comment]
how to fix it?

**Comment by joeybaba** [comment]
oh...thanks, i del :`export DYLD_LIBRARY_PATH="/usr/local/lib"`, done for me
