### ISSUE TITLE
Cannot commit or refresh from icons at the top of the SCM menu with keyboard-only navigation

### ISSUE THREAD

**Issue by kylemh** [microsoft/vscode#100045]
- VSCode Version: 1.46.0
- OS Version: MacOS 10.15.5

I didn't use insiders build, but I didn't see this issue covered in the [minor version release candidate issues list](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22May+2020+Recovery%22
).

Steps to Reproduce:

1. Make changes to a file
2. Go to source control menu
3. Stage changes to be committed
4. SHIFT + TAB should focus on the commit message input ✅ 
5. SHIFT + TAB again should see the focus ring on the "more options" / triple dot button ✅ 
6. Hitting ENTER will open the full menu of options ✅ 
7. SHIFT + TAB one more time and you should see the focus ring on the "Refresh" option ✅ 
8. Hitting ENTER will trigger a loading state as you get a refreshed look from your remote 🔴 
9. SHIFT + TAB once more and you should see the focus ring on the "Commit" option ✅ 
10. Hitting ENTER will trigger a commit or a prompt to add a commit message (if none is entered already) 🔴 

Instead, step 10 is opening the same menu that opens from the triple dot button.

All of the other focus options are miffed too.

Does this issue occur when all extensions are disabled?: Yes

Obviously, it's a bit difficult to convey via gif without signifying which key on the keyboard I'm hitting, but basically I'm using SHIFT+TAB and then ENTER on each option.
![demo](https://user-images.githubusercontent.com/9523719/84555875-201c6f00-acd4-11ea-982e-6e2b5ae1424b.gif)

**Comment by gjsjohnmurray** [comment]
For future GIFs like this you may like to use screencast mode.

https://code.visualstudio.com/updates/v1_31#_screencast-mode

**Comment by joaomoreno** [comment]
Same as https://github.com/microsoft/vscode/issues/100273
