### ISSUE TITLE
font-size

### ISSUE THREAD

**Issue by jim4067** [microsoft/vscode#100085]
Issue Type: <b>Bug</b>

Hey guys. The latest upgrade (May) changed the application's font family to use my system font but whenever the font size is wrong. It does increase or reduce when i make the changes on my system

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 5.3.0-3-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-6310 APU with AMD Radeon R4 Graphics (4 x 2028)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|4.77GB (0.15GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|deepin|
|XDG_CURRENT_DESKTOP|Deepin|
|XDG_SESSION_DESKTOP|deepin|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
code-runner|for|0.10.0
rest-client|hum|0.24.1
cpptools|ms-|0.28.3
debugger-for-chrome|msj|4.12.8
vscode-react-native|msj|0.16.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.8
vscode-icons|vsc|10.1.1

</details>

**Comment by bpasero** [comment]
/duplicate https://github.com/microsoft/vscode/issues/10144

cc @kdrag0n

**Comment by perlun** [comment]
@bpasero If possible, please unlock the conversation in #10144. I noted it has gone read-only now.

**Comment by perlun** [comment]
Continuing here since #10144 is read only. I still consider this a problem. We have changed now to a behavior that is much harder to override. It might be a great change for 90% of the users, but it's quite annoying for the other 10% of us. I am still on the old version of VS Code until this can be properly resolved.

I _think_ it could also be resolved by a custom fontconfig config file. Might look into it some day. Of course, #519 would be the long-term fix.
