### ISSUE TITLE
Feature Request: Use Windows-style custom titlebar, but with GTK icons instead

### ISSUE THREAD

**Issue by chaitunya** [microsoft/vscode#100040]
It would be a lot nicer to have a custom titlebar (like Windows), but instead of having the Windows titlebar buttons, you could use the titlebar buttons in the user's GTK theme. Here is a simple mockup of what I am talking about, with Ubuntu's default Yaru theme:
![vscode_mockup](https://user-images.githubusercontent.com/13303232/84551068-513f7400-acc1-11ea-8e75-ab14f4d87ef1.png)
It would look a lot cleaner, IMO.

**Comment by sbatten** [comment]
Windows 10 has a consistent built-in style for the title bar and that's something we can easily mimic. That's not the case for gtk themes as a user can do whatever they want. For this reason, we recommend the native experience on Linux.
