### ISSUE TITLE
icon in explorer not show when change file icon theme

### ISSUE THREAD

**Issue by Sedsakol** [microsoft/vscode#100065]
Issue Type: <b>Bug</b>

In seti the display is correct. But once changed to minimal, the icon disappeared

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.5.86806
material-theme|zhu|3.7.3

</details>

**Comment by aeschli** [comment]
Can you add a screenshot?

**Comment by Sedsakol** [comment]
Minimal icon Visual Studio Code
![image](https://user-images.githubusercontent.com/31177224/84863091-976c4d00-b09e-11ea-8072-64ad49040395.png)

Seti icon Visual Studio Code
![image](https://user-images.githubusercontent.com/31177224/84863260-e0bc9c80-b09e-11ea-85a3-a9012525eb61.png)

Material icon Theme
![image](https://user-images.githubusercontent.com/31177224/84863337-fd58d480-b09e-11ea-8adf-8867bc0fdcb5.png)

**Comment by aeschli** [comment]
Likely a duplicate of https://github.com/microsoft/vscode/issues/97564
Can you follow the steps described in https://github.com/microsoft/vscode/issues/97564#issuecomment-627351149 ?

**Comment by Sedsakol** [comment]
Thank you so much.
