### ISSUE TITLE
Command to Create Empty README.md in project root directory

### ISSUE THREAD

**Issue by LittleboyHarry** [microsoft/vscode#100046]
Creating a `README.md` file manually is cumbersome for each new empty project directory.

Would you add a command to create automatically a `README.md` file in project root directory, which is keymap shortcut bindable.

**Comment by ArturoDent** [comment]
You could create one pretty easily yourself with this **task** (tasks.json):

```
   {
      "label": "newFile",
      "command": "touch '${workspaceFolder}'/README.md";      
      "type": "shell",
      "problemMatcher": [],
    },
```

`touch` or whatever your shell uses to create a new file.

keybinding:

 ```
  {
    "key": "alt+r",     // whatever keybinding you like
    "command": "workbench.action.tasks.runTask",
    "args": "newFile"        // match the label name from the task
  },
```

**Comment by LittleboyHarry** [comment]
If I can add `task.json` and add task for each new empty project directory easily, why not create a new README.md directly?
It's getting more trouble. @ArturoDent

**Comment by gjsjohnmurray** [comment]
@LittleboyHarry maybe implement @ArturoDent's idea as a [user level task](https://code.visualstudio.com/updates/v1_42#_user-level-tasks)

**Comment by ArturoDent** [comment]
See https://code.visualstudio.com/updates/v1_42#_user-level-tasks.   Thanks @gjsjohnmurray
