### ISSUE TITLE
Breakpoints not applied if Node.js project contains inaccessible subdirectory

### ISSUE THREAD

**Issue by wooque** [microsoft/vscode#100018]
- VSCode Version: 1.46.0
- OS Version: Arch Linux

Steps to Reproduce:

1. Create dir inside Node.js project with `sudo mkdir data && sudo chmod 700 data`
2. Try to add breakpoint to any js file 

Does this issue occur when all extensions are disabled?: Yes

**Comment by wooque** [comment]
It will silently break with launch configuration of type `node`, `pwa-node` will fail with

**Comment by wooque** [comment]
Bug present in this insider build also
```
Version: 1.47.0-insider
Commit: 7e4cc2c435927e5a2845897961a2af10ee7f784d
Date: 2020-06-12T05:53:29.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.2-arch1-1
```

**Comment by connor4312** [comment]
Thanks for the issue! Fixed in the latest [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension).
