### ISSUE TITLE
editor.find.seedSearchStringFromSelection no longer honored after 1.45 update

### ISSUE THREAD

**Issue by reporter123** [microsoft/vscode#100001]
Issue Type: <b>Bug</b>

Setting editor.find.seedSearchStringFromSelection=true no longer has any effect.

Steps to Reproduce:

1. Set editor.find.seedSearchStringFromSelection = true
2. Select text
3. Open "Search" side ber

Search field is no long filled out with the selection.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 5.4.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz (4 x 1829)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|5.68GB (0.21GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by JacksonKearl** [comment]
This is by design, focusing the viewlet (which is what clicking on it does) shouldn't affect its contents. Discussion here: https://github.com/microsoft/vscode/issues/91901

You can use the `Search: Find in Files` command (Ctrl/Cmd + Shift + F) to seed&focus, or set `"search.seedOnFocus": true`.
