### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Daneto123** [microsoft/vscode#100041]
Issue Type: <b>Bug</b>

my project run on one device ,but doesn't run to another why is it.

thanks

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.94GB (4.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
prettier-vscode|esb|5.0.0
code-runner|for|0.10.0
language-haskell|jus|3.2.1
cpptools|ms-|0.28.3
pdf|tom|0.6.0

</details>

**Comment by Daneto123** [comment]
https://github.com/Daneto123/storage/tree/master/storage this is a project and the problem is in main.cpp and file.cpp(split function) if you could help I will be grateful to you.

Thank you for your attention.

**Comment by sandy081** [comment]
Please file issue against the c++ extension.
