### ISSUE TITLE
marketplace

### ISSUE THREAD

**Issue by feelipecl** [microsoft/vscode#100035]
Issue Type: <b>Feature Request</b>

hello , I get this error when I see the market

I get this error when I see the market
we cannot connect to the extensions marketplace at this time please try again later

![image](https://user-images.githubusercontent.com/66842018/84547648-ffebb080-acd1-11ea-9e7f-2869041bb18f.png)

**Comment by anuj-apdev** [comment]
Got similar issue. On Console log says -> 

{timestamp: "2020-06-13T00:53:21.571+0000", status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
message: "sortOrder parameter must be either 'asc' or 'desc'."
path: "/vscode/gallery/extensionquery"
status: 500
timestamp: "2020-06-13T00:53:21.571+0000"

**Comment by juanmi108** [comment]
> Got similar issue. On Console log says ->
> 
> {timestamp: "2020-06-13T00:53:21.571+0000", status: 500, error: "Internal Server Error",…}
> error: "Internal Server Error"
> message: "sortOrder parameter must be either 'asc' or 'desc'."
> path: "/vscode/gallery/extensionquery"
> status: 500
> timestamp: "2020-06-13T00:53:21.571+0000"

I have the same Issue this is the request payload 
`{"filters":[{"criteria":[{"filterType":8,"value":"Microsoft.VisualStudio.Code"},{"filterType":12,"value":"4096"}],"pageNumber":1,"pageSize":50,"sortBy":4,"sortOrder":0}],"assetTypes":[],"flags":946}`

**Comment by feelipecl** [comment]
any solution?

**Comment by Daniyal-Javani** [comment]
Nevermind! it's related to vscodium https://github.com/VSCodium/vscodium/issues/418

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by feelipecl** [comment]
I made the test of the page the photo appeared to me, when entering the console all these problems appear

![image](https://user-images.githubusercontent.com/66842018/84679442-4bcf6d00-aeff-11ea-99a2-5c795ea98a63.png)
![image](https://user-images.githubusercontent.com/66842018/84679459-51c54e00-aeff-11ea-919d-125df83dccab.png)

**Comment by sandy081** [comment]
Seems proxy issues

**Comment by chrmarti** [comment]
@feelipecl Please start VSCode with `--log-net-log=netlog.json`, try searching the marketplace and then upload the resulting `netlog.json` here.

**Comment by feelipecl** [comment]
![image](https://user-images.githubusercontent.com/66842018/84785174-2d2dac80-afb9-11ea-8579-7a5f0ba7610e.png)
![image](https://user-images.githubusercontent.com/66842018/84785236-4171a980-afb9-11ea-8c49-72b7e45d764f.png)

**Comment by chrmarti** [comment]
@feelipecl When you start with `--log-net-log=netlog.json` there should be a `netlog.json` created. Could you upload that? (Maybe you have the `http.proxy` setting in VS Code set or one of the HTTP_PROXY or HTTPS_PROXY environment variables.)
