### ISSUE TITLE
minimize context menu

### ISSUE THREAD

**Issue by SailorMax** [microsoft/vscode#100084]
Issue Type: <b>Feature Request</b>

Can you try to minimize context menu in long cases? In notebooks they can take all height of screen already! Sometimes with scroll!

You can group not often use items.

For example:
SCM / "..." menu:
 - you can group in submenu "Commit ..." all commit-like items
 - also can group "Apply", "Pop", "Stash" items

context menu of selected text:
 - you can group in submenu "Format ..." all format-like items
 - also scm-copy items, like "Copy Commit ID", "Copy Remote Url",..
 - "Go to ..." items

Extensions like "Bookmarks" also add additional items. If they has not API to make groups, add it please.

thank you.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

**Comment by sbatten** [comment]
merging with #100172
