### ISSUE TITLE
Incorrect syntax coloring for backslashes in JavaScript raw strings

### ISSUE THREAD

**Issue by kshetline** [microsoft/vscode#100082]
- VSCode Version: 1.46.0
- OS Version: MacOS 10.15.5

Steps to Reproduce:

1. Type in a JavaScript (or TypeScript) raw string containing backslashes (other than `` \` ``).
2. Observe the syntax coloring of the backslashes, meant to indicate that a backslash is a character escape, when it actually isn't an escape but a literal character.
3. Also note that the `.` in `String.raw` is colored as if it were text, and not as punctuation.

Does this issue occur when all extensions are disabled?: Yes

Here's a sample of what this looks like using the Dark+ theme:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/24473229/84569568-b5ac1300-ad55-11ea-9257-27805234ec75.png">

Notice that the backslashes are yellow, not orange like the rest of the text, when these backslashes are not escape characters in this context, and should not be highlighted as such.

Also notice the orange dot in `String.raw`, which is the color for text, instead of the near-white color typically used for punctuation.

**Comment by alexr00** [comment]
Moved to the repository where we get our syntax highlighting grammar from.
