### ISSUE TITLE
i cannot install any extensions

### ISSUE THREAD

**Issue by arifikhsan** [microsoft/vscode#100075]
- VSCode Version: 1.46.0
- OS Version: Windows 10

Steps to Reproduce:

1. click install on any extension
2. error

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/32485694/84567424-ce8ee580-ada2-11ea-8001-efcd787a0d53.png)

![image](https://user-images.githubusercontent.com/32485694/84567475-157cdb00-ada3-11ea-88ad-f67cee67dfc9.png)

**Comment by codingonHP** [comment]
@arifikhsan I tried it just now and it is working for me.

**Comment by gjsjohnmurray** [comment]
I suggest you look at https://github.com/microsoft/vscode/issues/99668#issuecomment-641807657

**Comment by arifikhsan** [comment]
> I suggest you look at [#99668 (comment)](https://github.com/microsoft/vscode/issues/99668#issuecomment-641807657)

configuring dns to 1.1.1.1 not solving the issue

**Comment by arifikhsan** [comment]
vscjava.gallerycdn.vsassets.io/extensions/vscjava/vscode-maven/0.22.0/1591942965576/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://vscjava.gallerycdn.vsassets.io/extensions/vscjava/vscode-maven/0.22.0/1591942965576/Microsoft.VisualStudio.Services.Icons.Default net::ERR_CONNECTION_TIMED_OUT
Image (async)
(anonymous) @ extensionsList.ts:172
(anonymous) @ event.ts:40
fire @ event.ts:587
o @ event.ts:16
error (async)
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:516
(anonymous) @ event.ts:31
renderElement @ extensionsList.ts:172
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
ms-azuretools.gallerycdn.vsassets.io/extensions/ms-azuretools/vscode-docker/1.2.1/1590518461276/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://ms-azuretools.gallerycdn.vsassets.io/extensions/ms-azuretools/vscode-docker/1.2.1/1590518461276/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TIMED_OUT
Image (async)
renderElement @ extensionsList.ts:173
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
ms-vscode-remote.gallerycdn.vsassets.io/extensions/ms-vscode-remote/remote-wsl/0.44.2/1584956688534/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://ms-vscode-remote.gallerycdn.vsassets.io/extensions/ms-vscode-remote/remote-wsl/0.44.2/1584956688534/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TIMED_OUT
Image (async)
(anonymous) @ extensionEditor.ts:338
(anonymous) @ event.ts:40
fire @ event.ts:587
o @ event.ts:16
error (async)
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:516
(anonymous) @ event.ts:31
updateTemplate @ extensionEditor.ts:338
async function (async)
updateTemplate @ extensionEditor.ts:324
setInput @ extensionEditor.ts:319
async function (async)
setInput @ extensionEditor.ts:317
doSetInput @ editorControl.ts:179
openEditor @ editorControl.ts:68
(anonymous) @ editorGroupView.ts:973
doShowEditor @ editorGroupView.ts:971
doOpenEditor @ editorGroupView.ts:954
openEditor @ editorGroupView.ts:882
openEditor @ editorService.ts:530
open @ extensionsWorkbenchService.ts:635
run @ extensionsActions.ts:230
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/1.5.0/1556863124877/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/1.5.0/1556863124877/Microsoft.VisualStudio.Services.Icons.Default net::ERR_CONNECTION_TIMED_OUT
Image (async)
renderElement @ extensionsList.ts:173
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
notificationsAlerts.ts:40 Unable to open 'Extension: Auto Close Tag': An unknown error occurred. Please consult the log for more details..
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
doHandleOpenEditorError @ editorGroupView.ts:1056
(anonymous) @ editorGroupView.ts:984
async function (async)
(anonymous) @ editorGroupView.ts:973
doShowEditor @ editorGroupView.ts:971
doOpenEditor @ editorGroupView.ts:954
openEditor @ editorGroupView.ts:882
openEditor @ editorService.ts:530
open @ extensionsWorkbenchService.ts:635
run @ extensionsActions.ts:230
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
request.ts:40 GET https://formulahendry.gallerycdn.vsassets.io/extensions/formulahendry/auto-close-tag/0.5.7/1587467276579/Microsoft.VisualStudio.Code.Manifest net::ERR_CONNECTION_TIMED_OUT
(anonymous) @ request.ts:40
t.request @ request.ts:18
request @ requestService.ts:34
(anonymous) @ extensionGalleryService.ts:669
Promise.then (async)
(anonymous) @ extensionGalleryService.ts:652
Promise.then (async)
getAsset @ extensionGalleryService.ts:634
getManifest @ extensionGalleryService.ts:580
getManifest @ extensionsWorkbenchService.ts:213
(anonymous) @ extensionEditor.ts:334
a @ async.ts:23
(anonymous) @ extensionEditor.ts:334
get @ cache.ts:24
updateTemplate @ extensionEditor.ts:440
async function (async)
updateTemplate @ extensionEditor.ts:324
setInput @ extensionEditor.ts:319
async function (async)
setInput @ extensionEditor.ts:317
doSetInput @ editorControl.ts:179
openEditor @ editorControl.ts:68
(anonymous) @ editorGroupView.ts:973
doShowEditor @ editorGroupView.ts:971
doOpenEditor @ editorGroupView.ts:954
openEditor @ editorGroupView.ts:882
openEditor @ editorService.ts:530
open @ extensionsWorkbenchService.ts:635
run @ extensionsActions.ts:230
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
extensionsActions.ts:263 Error
(anonymous) @ extensionsActions.ts:263
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
install @ extensionsActions.ts:258
run @ extensionsActions.ts:234
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
notificationsAlerts.ts:40 Failed to install 'formulahendry.auto-close-tag'.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
prompt @ notificationService.ts:171
(anonymous) @ extensionsActions.ts:86
invokeFunction @ instantiationService.ts:61
se @ extensionsActions.ts:76
(anonymous) @ extensionsActions.ts:265
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
install @ extensionsActions.ts:258
run @ extensionsActions.ts:234
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
log.ts:197   ERR An unknown error occurred. Please consult the log for more details.: downloading
    at file:///C:/Users/Arif Ikhsanudin/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:561:471
eg2.gallerycdn.vsassets.io/extensions/eg2/vscode-npm-script/0.3.12/1590483955634/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://eg2.gallerycdn.vsassets.io/extensions/eg2/vscode-npm-script/0.3.12/1590483955634/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TIMED_OUT
Image (async)
renderElement @ extensionsList.ts:173
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
notificationsAlerts.ts:40 Unable to open 'Extension: Remote - WSL': An unknown error occurred. Please consult the log for more details..
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
doHandleOpenEditorError @ editorGroupView.ts:1056
(anonymous) @ editorGroupView.ts:984
async function (async)
(anonymous) @ editorGroupView.ts:973
doShowEditor @ editorGroupView.ts:971
doOpenEditor @ editorGroupView.ts:954
openEditor @ editorGroupView.ts:882
openEditor @ editorService.ts:530
open @ extensionsWorkbenchService.ts:635
run @ extensionsActions.ts:230
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
request.ts:40 GET https://ms-vscode-remote.gallerycdn.vsassets.io/extensions/ms-vscode-remote/remote-wsl/0.44.2/1584956688534/Microsoft.VisualStudio.Code.Manifest net::ERR_CONNECTION_TIMED_OUT
(anonymous) @ request.ts:40
t.request @ request.ts:18
request @ requestService.ts:34
(anonymous) @ extensionGalleryService.ts:669
Promise.then (async)
(anonymous) @ extensionGalleryService.ts:652
Promise.then (async)
getAsset @ extensionGalleryService.ts:634
getManifest @ extensionGalleryService.ts:580
getManifest @ extensionsWorkbenchService.ts:213
(anonymous) @ extensionEditor.ts:334
a @ async.ts:23
(anonymous) @ extensionEditor.ts:334
get @ cache.ts:24
updateTemplate @ extensionEditor.ts:440
async function (async)
updateTemplate @ extensionEditor.ts:324
setInput @ extensionEditor.ts:319
async function (async)
setInput @ extensionEditor.ts:317
doSetInput @ editorControl.ts:179
openEditor @ editorControl.ts:68
(anonymous) @ editorGroupView.ts:973
doShowEditor @ editorGroupView.ts:971
doOpenEditor @ editorGroupView.ts:954
openEditor @ editorGroupView.ts:882
openEditor @ editorService.ts:530
open @ extensionsWorkbenchService.ts:635
run @ extensionsActions.ts:230
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
extensionsActions.ts:263 Error
(anonymous) @ extensionsActions.ts:263
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
install @ extensionsActions.ts:258
run @ extensionsActions.ts:234
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
notificationsAlerts.ts:40 Failed to install 'ms-vscode-remote.remote-wsl'.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
prompt @ notificationService.ts:171
(anonymous) @ extensionsActions.ts:86
invokeFunction @ instantiationService.ts:61
se @ extensionsActions.ts:76
(anonymous) @ extensionsActions.ts:265
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
install @ extensionsActions.ts:258
run @ extensionsActions.ts:234
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
log.ts:197   ERR An unknown error occurred. Please consult the log for more details.: downloading
    at file:///C:/Users/Arif Ikhsanudin/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:561:471
ms-vscode-remote.gallerycdn.vsassets.io/extensions/ms-vscode-remote/remote-wsl/0.44.2/1584956688534/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://ms-vscode-remote.gallerycdn.vsassets.io/extensions/ms-vscode-remote/remote-wsl/0.44.2/1584956688534/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TIMED_OUT
Image (async)
renderElement @ extensionsList.ts:173
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
eg2.gallerycdn.vsassets.io/extensions/eg2/tslint/1.0.44/1562333373210/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://eg2.gallerycdn.vsassets.io/extensions/eg2/tslint/1.0.44/1562333373210/Microsoft.VisualStudio.Services.Icons.Default net::ERR_CONNECTION_TIMED_OUT
Image (async)
renderElement @ extensionsList.ts:173
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
eg2.gallerycdn.vsassets.io/extensions/eg2/vscode-npm-script/0.3.12/1590483955634/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://eg2.gallerycdn.vsassets.io/extensions/eg2/vscode-npm-script/0.3.12/1590483955634/Microsoft.VisualStudio.Services.Icons.Default net::ERR_CONNECTION_TIMED_OUT
Image (async)
(anonymous) @ extensionsList.ts:172
(anonymous) @ event.ts:40
fire @ event.ts:587
o @ event.ts:16
error (async)
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:516
(anonymous) @ event.ts:31
renderElement @ extensionsList.ts:172
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
zhuangtongfa.gallerycdn.vsassets.io/extensions/zhuangtongfa/material-theme/3.8.0/1592033977382/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://zhuangtongfa.gallerycdn.vsassets.io/extensions/zhuangtongfa/material-theme/3.8.0/1592033977382/Microsoft.VisualStudio.Services.Icons.Default net::ERR_CONNECTION_TIMED_OUT
Image (async)
renderElement @ extensionsList.ts:173
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
request.ts:40 GET https://zhuangtongfa.gallerycdn.vsassets.io/extensions/zhuangtongfa/material-theme/3.8.0/1592033977382/Microsoft.VisualStudio.Code.Manifest net::ERR_CONNECTION_TIMED_OUT
(anonymous) @ request.ts:40
t.request @ request.ts:18
request @ requestService.ts:34
(anonymous) @ extensionGalleryService.ts:643
Promise.then (async)
getAsset @ extensionGalleryService.ts:634
getManifest @ extensionGalleryService.ts:580
getManifest @ extensionsWorkbenchService.ts:213
(anonymous) @ extensionEditor.ts:334
a @ async.ts:23
(anonymous) @ extensionEditor.ts:334
get @ cache.ts:24
updateTemplate @ extensionEditor.ts:440
async function (async)
updateTemplate @ extensionEditor.ts:324
setInput @ extensionEditor.ts:319
async function (async)
setInput @ extensionEditor.ts:317
doSetInput @ editorControl.ts:179
openEditor @ editorControl.ts:68
(anonymous) @ editorGroupView.ts:973
doShowEditor @ editorGroupView.ts:971
doOpenEditor @ editorGroupView.ts:954
openEditor @ editorGroupView.ts:882
openEditor @ editorService.ts:530
open @ extensionsWorkbenchService.ts:635
run @ extensionsActions.ts:230
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
request.ts:40 GET https://donjayamanne.gallerycdn.vsassets.io/extensions/donjayamanne/githistory/0.6.5/1587993326663/Microsoft.VisualStudio.Code.Manifest net::ERR_CONNECTION_TIMED_OUT
(anonymous) @ request.ts:40
t.request @ request.ts:18
request @ requestService.ts:34
(anonymous) @ extensionGalleryService.ts:643
Promise.then (async)
getAsset @ extensionGalleryService.ts:634
getManifest @ extensionGalleryService.ts:580
getManifest @ extensionsWorkbenchService.ts:213
(anonymous) @ extensionEditor.ts:334
a @ async.ts:23
(anonymous) @ extensionEditor.ts:334
get @ cache.ts:24
updateTemplate @ extensionEditor.ts:440
async function (async)
updateTemplate @ extensionEditor.ts:324
setInput @ extensionEditor.ts:319
async function (async)
setInput @ extensionEditor.ts:317
doSetInput @ editorControl.ts:179
openEditor @ editorControl.ts:68
(anonymous) @ editorGroupView.ts:973
doShowEditor @ editorGroupView.ts:971
doOpenEditor @ editorGroupView.ts:954
openEditor @ editorGroupView.ts:882
openEditor @ editorService.ts:530
open @ extensionsWorkbenchService.ts:635
run @ extensionsActions.ts:230
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
request.ts:40 GET https://eg2.gallerycdn.vsassets.io/extensions/eg2/tslint/1.0.44/1562333373210/Microsoft.VisualStudio.Code.Manifest net::ERR_CONNECTION_TIMED_OUT
(anonymous) @ request.ts:40
t.request @ request.ts:18
request @ requestService.ts:34
(anonymous) @ extensionGalleryService.ts:643
Promise.then (async)
getAsset @ extensionGalleryService.ts:634
getManifest @ extensionGalleryService.ts:580
getManifest @ extensionsWorkbenchService.ts:213
(anonymous) @ extensionEditor.ts:334
a @ async.ts:23
(anonymous) @ extensionEditor.ts:334
get @ cache.ts:24
updateTemplate @ extensionEditor.ts:440
async function (async)
updateTemplate @ extensionEditor.ts:324
setInput @ extensionEditor.ts:319
async function (async)
setInput @ extensionEditor.ts:317
doSetInput @ editorControl.ts:179
openEditor @ editorControl.ts:68
(anonymous) @ editorGroupView.ts:973
doShowEditor @ editorGroupView.ts:971
doOpenEditor @ editorGroupView.ts:954
openEditor @ editorGroupView.ts:882
openEditor @ editorService.ts:530
open @ extensionsWorkbenchService.ts:635
run @ extensionsActions.ts:230
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
ms-vscode-remote.gallerycdn.vsassets.io/extensions/ms-vscode-remote/remote-wsl/0.44.2/1584956688534/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://ms-vscode-remote.gallerycdn.vsassets.io/extensions/ms-vscode-remote/remote-wsl/0.44.2/1584956688534/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TIMED_OUT
Image (async)
(anonymous) @ extensionsList.ts:172
(anonymous) @ event.ts:40
fire @ event.ts:587
o @ event.ts:16
error (async)
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:516
(anonymous) @ event.ts:31
renderElement @ extensionsList.ts:172
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
ms-vscode.gallerycdn.vsassets.io/extensions/ms-vscode/powershell/2020.6.0/1591920190840/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://ms-vscode.gallerycdn.vsassets.io/extensions/ms-vscode/powershell/2020.6.0/1591920190840/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TIMED_OUT
Image (async)
renderElement @ extensionsList.ts:173
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
ms-vscode.gallerycdn.vsassets.io/extensions/ms-vscode/powershell/2020.6.0/1591920190840/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://ms-vscode.gallerycdn.vsassets.io/extensions/ms-vscode/powershell/2020.6.0/1591920190840/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TIMED_OUT
Image (async)
(anonymous) @ extensionsList.ts:172
(anonymous) @ event.ts:40
fire @ event.ts:587
o @ event.ts:16
error (async)
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:516
(anonymous) @ event.ts:31
renderElement @ extensionsList.ts:172
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
ms-vsliveshare.gallerycdn.vsassets.io/extensions/ms-vsliveshare/vsliveshare/1.0.2302/1591821369867/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://ms-vsliveshare.gallerycdn.vsassets.io/extensions/ms-vsliveshare/vsliveshare/1.0.2302/1591821369867/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TIMED_OUT
Image (async)
renderElement @ extensionsList.ts:173
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
eg2.gallerycdn.vsassets.io/extensions/eg2/tslint/1.0.44/1562333373210/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://eg2.gallerycdn.vsassets.io/extensions/eg2/tslint/1.0.44/1562333373210/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TIMED_OUT
Image (async)
(anonymous) @ extensionEditor.ts:338
(anonymous) @ event.ts:40
fire @ event.ts:587
o @ event.ts:16
error (async)
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:516
(anonymous) @ event.ts:31
updateTemplate @ extensionEditor.ts:338
async function (async)
updateTemplate @ extensionEditor.ts:324
setInput @ extensionEditor.ts:319
async function (async)
setInput @ extensionEditor.ts:317
doSetInput @ editorControl.ts:179
openEditor @ editorControl.ts:68
(anonymous) @ editorGroupView.ts:973
doShowEditor @ editorGroupView.ts:971
doOpenEditor @ editorGroupView.ts:954
openEditor @ editorGroupView.ts:882
openEditor @ editorService.ts:530
open @ extensionsWorkbenchService.ts:635
run @ extensionsActions.ts:230
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
notificationsAlerts.ts:40 Unable to open 'Extension: TSLint (deprecated)': An unknown error occurred. Please consult the log for more details..
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
doHandleOpenEditorError @ editorGroupView.ts:1056
(anonymous) @ editorGroupView.ts:984
async function (async)
(anonymous) @ editorGroupView.ts:973
doShowEditor @ editorGroupView.ts:971
doOpenEditor @ editorGroupView.ts:954
openEditor @ editorGroupView.ts:882
openEditor @ editorService.ts:530
open @ extensionsWorkbenchService.ts:635
run @ extensionsActions.ts:230
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
request.ts:40 GET https://eg2.gallerycdn.vsassets.io/extensions/eg2/tslint/1.0.44/1562333373210/Microsoft.VisualStudio.Code.Manifest net::ERR_CONNECTION_TIMED_OUT
(anonymous) @ request.ts:40
t.request @ request.ts:18
request @ requestService.ts:34
(anonymous) @ extensionGalleryService.ts:669
Promise.then (async)
(anonymous) @ extensionGalleryService.ts:652
Promise.then (async)
getAsset @ extensionGalleryService.ts:634
getManifest @ extensionGalleryService.ts:580
getManifest @ extensionsWorkbenchService.ts:213
(anonymous) @ extensionEditor.ts:334
a @ async.ts:23
(anonymous) @ extensionEditor.ts:334
get @ cache.ts:24
updateTemplate @ extensionEditor.ts:440
async function (async)
updateTemplate @ extensionEditor.ts:324
setInput @ extensionEditor.ts:319
async function (async)
setInput @ extensionEditor.ts:317
doSetInput @ editorControl.ts:179
openEditor @ editorControl.ts:68
(anonymous) @ editorGroupView.ts:973
doShowEditor @ editorGroupView.ts:971
doOpenEditor @ editorGroupView.ts:954
openEditor @ editorGroupView.ts:882
openEditor @ editorService.ts:530
open @ extensionsWorkbenchService.ts:635
run @ extensionsActions.ts:230
runAction @ actions.ts:198
run @ actions.ts:190
onClick @ actionbar.ts:183
(anonymous) @ actionbar.ts:163
processImmediate @ internal/timers.js:439
zhuangtongfa.gallerycdn.vsassets.io/extensions/zhuangtongfa/material-theme/3.8.0/1592033977382/Microsoft.VisualStudio.Services.Icons.Default:1 GET https://zhuangtongfa.gallerycdn.vsassets.io/extensions/zhuangtongfa/material-theme/3.8.0/1592033977382/Microsoft.VisualStudio.Services.Icons.Default net::ERR_TIMED_OUT
Image (async)
(anonymous) @ extensionsList.ts:172
(anonymous) @ event.ts:40
fire @ event.ts:587
o @ event.ts:16
error (async)
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:516
(anonymous) @ event.ts:31
renderElement @ extensionsList.ts:172
renderElement @ listPaging.ts:51
renderElement @ listWidget.ts:1009
insertItemInDOM @ listView.ts:690
render @ listView.ts:634
onScroll @ listView.ts:853
fire @ event.ts:589
(anonymous) @ scrollableElement.ts:181
fire @ event.ts:587
_setState @ scrollable.ts:358
setScrollPositionNow @ scrollable.ts:282
setScrollPositionSmooth @ scrollable.ts:288
_onMouseWheel @ scrollableElement.ts:405
e @ scrollableElement.ts:335
notificationsAlerts.ts:40 Unable to open 'Extension: One Dark Pro': An unknown error occurred. Please consult the log for more details..

**Comment by arifikhsan** [comment]
![image](https://user-images.githubusercontent.com/32485694/84572325-67cdf400-adc3-11ea-97ae-c9a7988f7e3b.png)

![image](https://user-images.githubusercontent.com/32485694/84572333-71575c00-adc3-11ea-8a24-fb833a2e8a57.png)

**Comment by arifikhsan** [comment]
![image](https://user-images.githubusercontent.com/32485694/84572521-ba5be000-adc4-11ea-8861-ae9d6432fa30.png)

why i can install dart, flutter, and vetur?

**Comment by arifikhsan** [comment]
but others can't

**Comment by arifikhsan** [comment]
cannot visit this link

[](https://nash.gallerycdn.vsassets.io/extensions/nash/awesome-flutter-snippets/2.0.3/1571590746875/Microsoft.VisualStudio.Code.Manifest)

or 

https://hirantha.gallerycdn.vsassets.io/extensions/hirantha/json-to-dart/2.2.0/1590606637423/Microsoft.VisualStudio.Services.Icons.Default

no logs

![image](https://user-images.githubusercontent.com/32485694/84572857-20496700-adc7-11ea-87a6-b8b2d5a29a69.png)

**Comment by codingonHP** [comment]
@arifikhsan Do you have any proxy setup on your machine by any chance?

**Comment by arifikhsan** [comment]
> @arifikhsan Do you have any proxy setup on your machine by any chance?

no, everything is default

**Comment by arifikhsan** [comment]
i solved this by using vpn
