### ISSUE TITLE
On Project Open Do X

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/vscode#100008]
I haven't found any existing notes on this. 

Essentially when I open folders, the first thing I want to do is a git pull. Right now I have to do this manually. Ideally I would like to automate this. I do some extra steps for other projects, but I would think a per project thing will have to be an extension, though that said, I haven't found specific extension events for that either.

**Comment by misolori** [comment]
You can actually set this up with tasks using the `"runOn": "folderOpen"` flag ([docs](https://code.visualstudio.com/Docs/editor/tasks#_run-behavior) and [example](https://code.visualstudio.com/updates/v1_30#_run-on-folder-open)):

```jsonc
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Sync Git (Automated)",
            "type": "shell",
            "command": "git pull && git push",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true
            },
            "runOptions": {
                "runOn": "folderOpen"
            }
        }
    ]
}
```

Then once you have this configured, when you run the task manually it will ask whether you want to allow automatic tasks for this folder (or you can directly enable this via the `Tasks: Manage Automatic Tasks in Folder` command in the command palette). The `presentation` options allow you to customize things like whether you want the panel to be open when it runs, etc.

**Comment by mjmatthiesen** [comment]
Thanks! I was definitely not using the right search terms.
