### ISSUE TITLE
cursorword[right|left] don't work as expected

### ISSUE THREAD

**Issue by ZooDoo4U** [microsoft/vscode#100089]
I've disable all extensions, removed any conflicting keymapping for cursor movement.  Closed and restarted VS Code.  Not able to get "CTRL+LEFT or RIGHT" arrow to navigate cursorWordStart[Right|Left] as expected.  Given the code below I'll use $$ for the intial cursor loction and $1, $2 for each time i press "CTRL-RIGHT Arrow"..

Sample/originating source:
const productData = ProductData.map...

(actual)
$$con$1st $2pro$3duc$4tDa$5ta $6= $7Pro$8du$8c$9tDat$10a.map

Expected:
$$const $1productData $2= $3ProductData.$4map

Given the expcected word sperators are defatult but at the least these are in the default word seperator list...

**Comment by alexdima** [comment]
@ZooDoo4U I cannot reproduce what you are describing. Could you please try the following:
* add to the end of your `keybindings.json`:
```
{ "key": "ctrl+t", "command": "cursorWordEndRight", "when": "textInputFocus" }
```
* in a new window, open a new untitled file
* paste `const productData = ProductData.map`
* press `ctrl+t` repeatedly.

Here is where the cursor lands for me:
`|const| productData| =| ProductData|.map|`

**Comment by ZooDoo4U** [comment]
Thanks for following up,  looking at the settings currently set, searching for any [left|right]Arrow I notice many had ctrl-right or ctrl-left bound in some manor, such as :
cursorWordAccessibility[left|right]  when editorfocus 

Below the one really off is the $3 in the actual, still making an inter-word match,


Cleaning this up helped abit but still not moving as expected
raw css:

.parent {
  height: 100vh;
  border: 3px solid #000000;
}

Expected using $$ initial cursor pos $1 each moveWord...: 
$$
$1.parent $2{
  $3height: $4100vh;
  $4border: $53px $6solid $6#000000;
$7}

Actual:
$$
$1.$2pare$3nt $4{
  $5height$6: $7100vh$8;
  $9border$10: $113px $12solid $13#$14000000$15;
}

C# -- this was much worse...

Starting:
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

Expected:
$$
$1using $2System;
$3using $4System.$5Collections.$6Generic;

Actual: 
$$
$1using $2Sys$3t$4em$5;
$6using $7Sys$8t$9em$10.$11Colle$12c$13tions.Generic;

**Comment by alexdima** [comment]
@ZooDoo4U 
* Can you please check your definition for `"editor.wordSeparators"`? Comment it out if you have customized it.
* It is still not 100% clear to me that this is not caused by an extension. Can you please disable all extensions, comment all of your `settings.json` and comment all of your `keybindings.json` and try to repro?

**Comment by ZooDoo4U** [comment]
I think i see what is happening now.  In the word separators there was \t for a tab character, i'm think i put the in there,  given i see some characters  escaped to get past the JSON encoding, I probably put it it for save measure...   While there is still one place where the word left/right seems odd,  going right/forward it will hit the end of line, going left/back it hits the beginning of line.  Would assert shouldn't the the begin/end of line, they aren't any part of a word...

Given: 
$$ -- initial point
$1, $2- each move...
                items.map((i,index) =>  
                    <React.Fragment key={index}>

Actual (ctrl-right): 
                items.map((i,in$$dex$1) $2=>     $3
                    <React.Fragment key={index}>
Expected: 
                items.map((i,in$$dex$1) $2=>  
                    $3<React.Fragment key={index}>

<AND ctrl-left> 
Actual: 
                items.map((i,index) $3=>  
$2                    $1<$$React.Fragment key={index}>

Expected: 
                items.map((i,index) $2=>  
                    $1<$$React.Fragment key={index}>

**Comment by alexdima** [comment]
Ok, I'm happy we found the root cause.
