### ISSUE TITLE
Can not load extensions market and extension can not install

### ISSUE THREAD

**Issue by MohamedAladdin** [microsoft/vscode#100028]
Issue Type: <b>Bug</b>

Can not load extensions market and extension can not install,
Every time I tried to install or open the page of any Extension.. this error showed to me
`Unable to open 'Extension: ExtensionName': An unknown error occurred. Please consult the log for more details..`

and the log telling me that..
"net::ERR_NAME_NOT_RESOLVED"

I do not know what to do

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.2
indent4to2|Com|0.1.2
vscode-markdownlint|Dav|0.36.0
jshint|dba|0.10.21
vscode-eslint|dba|2.1.5
php-intellisense|fel|2.3.14
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
vue|jcb|0.1.5
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
mssql|ms-|1.9.0
python|ms-|2020.5.86806
laravel-blade|one|1.21.0
laravel5-snippets|one|1.8.0
vscode-totaljs|pnm|0.3.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
wordpress-snippet|tun|1.1.5

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Did you try searching issues here for the string ERR_NAME_NOT_RESOLVED?

**Comment by MohamedAladdin** [comment]
> Did you try searching issues here for the string ERR_NAME_NOT_RESOLVED?

Yes @gjsjohnmurray  I tried searching here, and no solution

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/99480#issuecomment-640810182

**Comment by MohamedAladdin** [comment]
@gjsjohnmurray , Oh.. ok I fixed it thank you

**Comment by gjsjohnmurray** [comment]
@MohamedAladdin that's good to hear. Please close this issue.
