### ISSUE TITLE
🎉🎊🎈 Congrats on issue #100000! 🎉🎊🎈

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#100000]
VSCode is awesome, the team is awesome, the community is awesome, and you are awesome, kudos 👏👏👏

_P.S. sorry for this issue spam :)_

**Comment by arifikhsan** [comment]
Does more issue mean better?

**Comment by iigmir** [comment]
> Does more issue mean better?

Well, more issues don't mean the software is more buggy; because the software more people used, more issues people may be reported.

**Comment by chrisdias** [comment]
:) thanks! closing issue as a part of housekeeping.
