### ISSUE TITLE
I can't see the snippets 'preview' next to the suggestion anymore.

### ISSUE THREAD

**Issue by Dannymx** [microsoft/vscode#100056]
Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z (2 days ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Try to get suggestions for snippets. I'm using this extension [ES7 React Snippets](https://marketplace.visualstudio.com/items?itemName=dsznajder.es7-react-js-snippets) but I also checked other snippets for example `html:5` and I can't see the preview of the snippet.
2. I used to get a preview of the snippet to the right of the suggestion

Does this issue occur when all extensions are disabled?: Yes

This is what I'm getting with the extension:
![image](https://user-images.githubusercontent.com/364003/84561114-59be9b80-ad0f-11ea-9fa5-250ac886820a.png)

With `html:` suggestions:
![image](https://user-images.githubusercontent.com/364003/84561233-5972d000-ad10-11ea-989d-00ed66dc2769.png)

This is what I used to get before (I screenshotted someone else's video):
![image](https://user-images.githubusercontent.com/364003/84561209-1ca6d900-ad10-11ea-8060-9eb7021963cf.png)

**Comment by gjsjohnmurray** [comment]
When you mouse over an item in the list do you get a chevron near the right-hand end, with a hint appearing when you hover over it?

![image](https://user-images.githubusercontent.com/6726799/84563500-e8eda280-ad53-11ea-8cbc-6d278bc8f3dd.png)

As well as the keyboard shortcut (mine is on Windows) you can click on the chevron to get this:

![image](https://user-images.githubusercontent.com/6726799/84563534-2baf7a80-ad54-11ea-9fd3-f1ccef87af68.png)

The upper-right X will hide the extra info.

**Comment by Dannymx** [comment]
@gjsjohnmurray Thanks that fixed my issue! Although I don't remember ever closing it, maybe I hit ctrl+space accidentally.
