### ISSUE TITLE
Bash(as Linux Subsystem) does not works within VSCode. Error: 0x80070057

### ISSUE THREAD

**Issue by aleksey-pastuhov** [Microsoft/vscode#10000]
- VSCode Version: 1.3.1
- OS Version: Windows 10 
- OS Build: 14393.5

Steps to Reproduce:

1. Enable bash(as Linux Subsystem) in Windows 10
2. Open User Settings
3. Add next lines
```json
{
    "terminal.external.windowsExec": "C:\\Windows\\System32\\bash.exe",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe"
}
```
4. If you will try to open bash via `Ctrl+Shift+C` you will get next error:
![image](https://cloud.githubusercontent.com/assets/11784219/17279844/55d8893a-5788-11e6-9c86-f9dbdf5ce5e7.png)
5. If you will try to open bash as internal terminal, it will close and open immediately.
**terminalInstance.ts:55 Integrated terminal exited with code 1**

*Note*
Open windows cmd and write `bash` - it works as expected and open bash in current directory. If create simple Node-app which run command via child-process.exec - it fails with:
```
{ 
  message: [Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "bash"],
  killed: false,
  code: 4294967295,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "bash"' 
}
```

Error: 0x80070057

It looks like it is the problem with Node itself. [https://github.com/Microsoft/BashOnWindows/issues/2](https://github.com/Microsoft/BashOnWindows/issues/2)

**Comment by mrmlnc** [comment]
Try this: `"terminal.integrated.shell.windows": "\\WINDOWS\\sysnative\\bash.exe"`

**Comment by aleksey-pastuhov** [comment]
Yep.. it worked. Sorry, I didn't noticed that it is already described in docs.
