### ISSUE TITLE
Provide error message when clicking on "clone repository" and git isn't found 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#100015]
I got a new laptop and forgot to install git as part of the setup 🤦🏾‍♀️ so when I clicked on "clone repository" in VS Code, nothing happened. 

![image](https://user-images.githubusercontent.com/45497113/84523731-b24d5480-ac8d-11ea-9aad-f80a71a1f3a1.png)
 
When I looked at the developer console, I saw that it was because git wasn't installed.

![image](https://user-images.githubusercontent.com/45497113/84523805-ce50f600-ac8d-11ea-9e60-128ef0690dca.png)

Perhaps the "clone repo" button could be grayed out if git isn't found, or an error banner could be shown with an error message?

**Comment by joaomoreno** [comment]
Olá Luciana! Great catch! 😉
