### ISSUE TITLE
Support Grid View in View Containers

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode#100094]
Currently, tabs can be split vertically and horizontally, but with version 1.46, view can only be split vertically. 

VS Code should allow views to be split horizontally as well. 

![image](https://user-images.githubusercontent.com/2473545/84579315-1281ea80-ada3-11ea-8d41-d78f5b785f41.png)

**Comment by phgmacedo** [comment]
Other tools, like like [JetBrains' WebStorm](https://www.jetbrains.com/webstorm/) provide much more flexible layout options:

![image](https://user-images.githubusercontent.com/2473545/84579375-a9e73d80-ada3-11ea-845b-c8bb90bdc18c.png)

**Comment by sbatten** [comment]
Currently, we optimized based on location. As you can see side bar stacks vertically and panel stacks horizontally by default but if it is moved to the left or right it stacks vertically as well. The terminal in VS Code splits on its own and follows similar logic. 

cc @sandy081 @joaomoreno @Tyriar

**Comment by Tyriar** [comment]
The rationale for the terminal only allowing splitting in a single direction was that it complicates both in the implementation and UX. I always said to myself when we allow tearing the terminal out of the window we should allow splitting in both directions for advanced users while trying to keep the one-way split UX for the average user.

**Comment by joaomoreno** [comment]
Remember to stay lightweight. ☝️

**Comment by sbatten** [comment]
I was on the fence here. I agree we should stay lightweight. And to be honest, since most views are primarily tree views, there isn't a lot of benefit to supporting this generally at the moment. I like the idea of saying this is a feature tear out when we get there.
