### ISSUE TITLE
Able to Create Unnamed Folder And it Deletes Everything When Trying to Delete Unnamed Folder

### ISSUE THREAD

**Issue by d35k** [microsoft/vscode#100031]
Hello, I found a strange bug. I was accidentally clicked to Create a new folder from sidebar (Screen Shot 1), after that, quickly clicked to collapse button next to the refresh button. (Screen Shot 2) I realized that when I clicked collapse button, it saves unnamed folder and when I want to delete that folder it deletes all files shown in sidebar. (Screen Shot 3 and 4)

- VSCode Version: 
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (4 wks ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

- OS Version: MacOs Catalina 10.15.3

Steps to Reproduce:

1. Click create button placed in sidebar
2. Click collapse button before typing or clicking anywhere in the screen

1 - https://pasteboard.co/JcMUXa2.png - After Clicking Create button
2- https://pasteboard.co/JcMV8LB.png - After Clicking Collapse button
3- https://pasteboard.co/JcMVfBO.png - Deleting Unnamed Folder
4- https://pasteboard.co/JcMVkLT.png - Trying to re-delete or rename folder
5- https://pasteboard.co/JcMVpAT.png - After deleting folder and refreshing from sidebar

Does this issue occur when all extensions are disabled?: Yes

**Comment by antlionguard** [comment]
I tried at Windows 10 2004 and I couldn't get this problem. New folder automatically removed when i clicked new folder button and after clicking collapse button.

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by subscribe-lark** [comment]
Test

**Comment by subscribe-lark** [comment]
Test

From: Liang Dai <admin@larkms.com>
Date: Tuesday, June 16, 2020 at 12:23
To: microsoft/vscode <reply@reply.github.com>, microsoft/vscode <vscode@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [microsoft/vscode] Able to Create Unnamed Folder And it Deletes Everything When Trying to Delete Unnamed Folder (#100031)

Test

**Comment by d35k** [comment]
> Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

I'll try as soon as possible, thank you for reply!
