### ISSUE TITLE
Commenting in HTML + JS mixed mode

### ISSUE THREAD

**Issue by vbbalaji** [microsoft/vscode#100099]
- VSCode Version: Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:
1. Open a HTML file that also has Javascript in it
2. (a). Select a block of HTML which also has a single line commented. Now VS Code will try to comment just the start and bottom, thus not commenting at all.
2 (b). Select a block of JS code and press Ctrl+Y. VS Code will try to do `<!--  var days = Math.floor(distance / (1000 * 60 * 60 * 24));  -->` instead of  `\\var days = Math.floor(distance / (1000 * 60 * 60 * 24));`

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
The comment feature is not smart. It just adds block comments around the selected area.
It's up to the user to decide if that makes sense and adjust the selection accordingly.
