### ISSUE TITLE
Hidden Panel Re-appears after re-start

### ISSUE THREAD

**Issue by andyj513** [microsoft/vscode#100009]
- VSCode Version: 1.46.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Move Source Control view to the top position on the Side Bar
2. Right-click on the Explorer view icon and choose Hide
3. Close Code
4. Restart Code

Results:
The Explorer view is visible (and selected).  It seems to hide again when I select a different view.

Expected Results:
I expected the Source Control view to be selected (since it is now the top item), and the Explorer view to remain hidden.

I think what is going on is that the Explorer is being selected when Code starts, even when that view was hidden, and even when it is not the top item in the Side Bar (which causes it to show temporarily, just as it does after being hidden and then doing Ctrl-Shift-E).  And I was expecting the top item in the Side Bar to be the default selection when Code starts.

**Comment by sbatten** [comment]
@sandy081 this behavior is expected with our current model of always restoring explorer on re-open. even though it is not pinned, it is the default view. @eamodio brought this up a bit back with regards to restoring the last view on restore.

**Comment by sandy081** [comment]
True. Explorer is default viewlet and we restore it on re-open. So IMO it is expected and as designed.

**Comment by andyj513** [comment]
Okay, so perhaps not a bug.  And certainly not a huge issue and I can live with it as-is.  But it seems like there is room for improvement in the design (a feature request?) to A) Not select by default a view that the user chose to hide, and B) It might be nice to let the user select a different default view, and using the first (visible) one on the Side Bar seems like an intuitive way to let the user select this.

**Comment by sandy081** [comment]
Can be considered as a feature request though I do not think this meet our priority requirements.
