### ISSUE TITLE
A small problem about js hints

### ISSUE THREAD

**Issue by keyiis** [Microsoft/vscode#10006]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.when i type "console." in vscode,it will hints "log".
2.when i select "log" in hints list ,it will be generate "console.console.log() ".
This is a small problem and if  can resolve all the better!

**Comment by jrieken** [comment]
@keyiis Can you paste a screen shot of the completions and the one you selected? I wonder if this is a snippet completion (see icon below) and if you have an extension that added this? For the July release we have added a new option to control how snippet suggestions should be treated

<img width="189" alt="screen shot 2016-08-03 at 12 43 49" src="https://cloud.githubusercontent.com/assets/1794099/17362957/fbe5b6fe-5977-11e6-8eb1-e161c5246b73.png">

**Comment by keyiis** [comment]
1.when i type "console.l" in vscode,it will hints "log"
![1](https://cloud.githubusercontent.com/assets/7766085/17394512/288e8b60-5a5c-11e6-95cd-3c6fc2d350aa.jpg)

2.i press 'enter' key.it will be generate "console.console.log() ".

![2](https://cloud.githubusercontent.com/assets/7766085/17394561/718af9fc-5a5c-11e6-801b-60d06c21e8a6.JPG)

**Comment by jrieken** [comment]
Yep - that's snippet. Closing as dup of #9286 which will give you new options to control this.
