### ISSUE TITLE
Problem with "Problem" tab - input field and filter

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#100073]
- VSCode Version: 1.45.1
- OS Version:

Steps to Reproduce:

1. Change tabs with Output, Problem, Terminal
2. The input field change size, and change tabs to dots "..." what made disonanse on GUi

 
![VSC_input](https://user-images.githubusercontent.com/25403861/84566421-30365c00-ad71-11ea-9836-a049d99995c3.png)
![VSC_input 2](https://user-images.githubusercontent.com/25403861/84566430-53f9a200-ad71-11ea-9f12-3f0cc3af9b19.png)

**Comment by ArturoDent** [comment]
Yes, I agree that Problems filter input box seems larger than typically necessary, resulting in the loss of panel headers.
