### ISSUE TITLE
workbench.editor.showtabs setting not working

### ISSUE THREAD

**Issue by maristhek** [microsoft/vscode#100055]
Issue Type: <b>Bug</b>

Can open only one file at a time

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz (8 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (18.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
composer|ika|0.7.1
vscode-rust|kal|0.4.2
vscode-docker|ms-|1.2.1
csharp|ms-|1.22.0
python|ms-|2020.5.86806
debugger-for-chrome|msj|4.12.8
vscode-unitymeta|PTD|0.0.7

</details>

**Comment by gjsjohnmurray** [comment]
Maybe you don't yet know about preview mode

https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by maristhek** [comment]
Setting the preview mode settings to true has no effect.

I don't understand why this has become a problem.  The multiple tabs for open editors was working fine for 99% of vs code users prior to the update.  It appears to be a solution to a non-problem.

**Comment by gjsjohnmurray** [comment]
So please clarify your problem. Screenshots may help.

**Comment by maristhek** [comment]
Attached is the screenshot of the project I'm working on, cloned from https://github.com/fantasticdonkey/rIoT.  VS Code is running on Win SRV 2016. The editor window shows my user settings.  It's been saved and vs code has been restarted.  Note that the tab has an open file : haversine.py.  When I click on another file in the Explorer panel the selected file replaces the haversine.py.  It happens to any file I open : it replaces the currently opened tab.

It is the same behavior in JS projects other than Python code.

I am going to test running thes projects on Linux, ubuntu 18.04 and ubuntu 19.04 where at this point VS code has not been updated to the latest v.

Please advise.

**Comment by gjsjohnmurray** [comment]
I'm not seeing a screenshot here in GitHub. If you copy it to your clipboard, then visit this issue from your web browser, you should be able to paste the clipboard contents directly into the comment box. Then use the Preview tab to check it's there before submitting it with the 'Comment' button.

But earlier you wrote:
> Setting the preview mode settings to true has no effect.

True is the default setting:
![image](https://user-images.githubusercontent.com/6726799/84576194-bd49d700-adaa-11ea-9b65-0dfabb596686.png)

Single-clicking a file in Explorer opens it in preview mode (italic label on the tab). Next file you open will replace this.

**Comment by maristhek** [comment]
OK How do I open multiple files on separate tabs.

I attached the png to email reply.

**Comment by gjsjohnmurray** [comment]
Looks like attaching a PNG to an emailed reply to a GH issue notification doesn't feed the attachment into the system.

Per the Preview Mode doc I originally pointed you to:
![image](https://user-images.githubusercontent.com/6726799/84577004-b32ad700-adb0-11ea-9a60-1107464be353.png)

Two ways to turn a preview tab (italic) into a regular one:

- Double-click the tab; or
- Right-click it and choose 'Keep Open'

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by maristhek** [comment]
Tnx.  Got an answer from John Murray : double-click the tab or right-click it and choose 'Keep Open'.  Undocumented feature ?  I could not find  a reference to it.

**Comment by bpasero** [comment]
Follow our docs to resolve this: https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by maristhek** [comment]
Tnx.

Following the docs :  It is not indicated that preview mode enabled is the default.  It is not indicated that preview mode enabled tabs can be controlled by mouse clicks.
