### ISSUE TITLE
Faulty smart select in YAML files

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#100081]
Faulty `editor.action.smartSelect.expand` behavior in YAML files.

![vsc2](https://user-images.githubusercontent.com/9438102/84569208-10a92e80-ad85-11ea-97fe-7d94db2e0fb6.gif)

Steps to Reproduce:
- `editor.action.smartSelect.expand` within parenthesis, backticks, single/double quotes containing a space, an hyphen, etc. (It is ok with brackets or curly brackets).

Expected:
- A step as selecting everything inside quotes.
- A step as selecting everything outside quotes.

Result:
 - Jumping outside quotes.

```
Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by aeschli** [comment]
What you see is text based smart selection as out of the box, VSCode only has basic yaml support. To get more, you need a YAML extension that is able to parse YAML code and can provide language aware smart selection

https://github.com/redhat-developer/vscode-yaml/ would be such extension, but from what I see it doesn't provide smart selection ranges. I suggest to file an issue there: https://github.com/redhat-developer/vscode-yaml/issues

**Comment by inwardmovement** [comment]
https://github.com/microsoft/vscode/issues/100081

**Comment by aeschli** [comment]
Thanks a lot!

**Comment by codingonHP** [comment]
@aeschli Are there any resources/links which you can point me to help me understand how VS handles different languages (for ex: typescript). I explored the VS codebase and saw by default it uses Word and Bracket selection providers.

**Comment by aeschli** [comment]
Extensions can contribute a [SelectionRangeProvider](https://code.visualstudio.com/api/references/vscode-api#SelectionRangeProvider) and that what our the TypeScript/CSS/... extensions do.
FOr languages where there is no usch provider contributed, we fall back to a generic, non-language ware one:
https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/smartSelect/bracketSelections.ts#L12
