### ISSUE TITLE
Webview API - Cant see Iframe rendered content or change console context

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#100039]
My app is rendering right but I cant expand the Iframe to see the details. 

![image](https://user-images.githubusercontent.com/55927613/84549867-7fcc4780-acdf-11ea-8d07-4d9d34743e3e.png)

I also can't focus the console in the Iframe to see the logs. 
![image](https://user-images.githubusercontent.com/55927613/84550017-ca4dc400-acdf-11ea-810d-c97743c6e1d6.png)

- VSCode Version:
1.46.0
a5d1cc28bb5da32ec67e86cc50f84c67cc690321
x64
- OS Version:
Windows 10

**Comment by mjbvz** [comment]
Please provide steps to reproduce (including extension code)

**Comment by mjbvz** [comment]
Actually, you are using the wrong in web inspector. See: https://code.visualstudio.com/api/extension-guides/webview#inspecting-and-debugging-webviews which documents how to inspect webviews
