### ISSUE TITLE
Starting inspector on 127.0.0.1:9229 failed: address already in use

### ISSUE THREAD

**Issue by j-quelly** [microsoft/vscode#100093]
Running next.js locally and was able to debug last night, now all of a sudden it's stopped working.

```
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z (3 days ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

Steps to Reproduce:

1. Create launch.json file
2. Add the following recipe:

```
    {
      "type": "node",
      "request": "launch",
      "name": "Next: Node",
      "runtimeExecutable": "${workspaceFolder}/node_modules/next/dist/bin/next",
      "env": {
        "NODE_OPTIONS": "--inspect-brk"
      },
      "port": 9229,
      "console": "integratedTerminal"
    },
```

3. Click play

See the following error:

>Starting inspector on 127.0.0.1:9229 failed: address already in use

4. `lsof -i :9229`
5. See no results, no processes running on this port.
6. Kill vscode
7. Open activity monitor, kill all node processes
8. Restart computer
9. Issue persists
10. Try several other permutations of launch recipe per hundreds of comments found throughout this repo and stackoverflow, for example, alternative ports.
11. Issue persists on all ports
12. Reinstall vscode 4 times
11. Issue persists

Does this issue occur when all extensions are disabled?: Yes

**Comment by gabrielew** [comment]
`sudo kill 'sudo lsof -t -i:9229'` fixed for me, but at once a day i have to execute this.

**Comment by iandev096** [comment]
Another process is probably using that port. In my case it was another instance of VS CODE. So I changed the debug script from

`"dev": "NODE_OPTIONS='--inspect' next dev"`

to

` "dev": "NODE_OPTIONS='--inspect=localhost:4444' next dev -p 4000"`. 

And it works for me. The trick is to use a port that is not being used by any other process. In my case I chose port 4444

**Comment by connor4312** [comment]
@j-quelly please try removing the "env" and "port" from your launch.json. These are no longer needed. Let us know if the issue still happens with that fixed.
