### ISSUE TITLE
git commit (amend) reformats multi-line commit message

### ISSUE THREAD

**Issue by rhaschke** [microsoft/vscode#100080]
When triggering a git commit (amend) command, the previous commit message is displayed for editing. If this previous commit was a multi-line message, vscode squeezes everything into a single line like this:
![image](https://user-images.githubusercontent.com/5376030/84568783-15201800-ad82-11ea-9168-feff0e609794.png)

This renders the amend commit feature unusable in many cases.

**Comment by joaomoreno** [comment]
#40295
