### ISSUE TITLE
Commented code fragment isn't displayed as such

### ISSUE THREAD

**Issue by roman02** [microsoft/vscode#100092]
![vscode - poorly displayed commented php code](https://user-images.githubusercontent.com/1476055/84577617-91672b00-ad83-11ea-903a-9dea31c6de70.jpg)
Issue Type: <b>Bug</b>

You will need to see a screenshot

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexr00** [comment]
@roman02 what language is this file? Can you provide a copy/paste-able snippet that I can reproduce the issue with?

**Comment by roman02** [comment]
It's a PHP file mixed with HTML code.

**Comment by roman02** [comment]
I wonder if I have made a mistake interpreting what happened. It seems that using those comment characters in a mixed PHP/HTML file only comments out HTML code that may be inside the block, but the PHP code in the block continues to be executed.

I think I need to file a different ticket with a request to change how commenting such blocks is done.
