### ISSUE TITLE
Search.Location settings is missing

### ISSUE THREAD

**Issue by LostLaplace** [microsoft/vscode#100017]
Search.Location setting is missing, this prevents me from moving the search window to the bottom of the screen on my vertical monitor and basically makes VS code unusable vertically.

- VSCode Version: 1.47.0-insider as well as 1.46.0
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Open settings UI
2. Search.Location is missing

Does this issue occur when all extensions are disabled?: Yes

**Comment by jmrf** [comment]
Exact same issue on:

```
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:04.923Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-53-generic snap
```

**Comment by jmrf** [comment]
Ok - apparently views can now be moved between the sidebar and the pannel: https://code.visualstudio.com/updates/v1_46

**Comment by LostLaplace** [comment]
Good find.
