### ISSUE TITLE
Nodejs debugger cannot attach child (linux)

### ISSUE THREAD

**Issue by Ierezell** [microsoft/vscode#100019]
- VSCode Version: `code --version`  => `1.46.0 x64`
- OS Version: `uname -a` => `Linux 5.7.2-arch1-1 x86_64 GNU/Linux` (Archlinux)

I know this problem as been aborded in other issues and should have been fixed with new versions but the problem is still here.

Steps to Reproduce:

In a totally new project 
1. Copy the code of the docs in test.js: 
[Code from the docs](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_automatically-attach-debugger-to-nodejs-subprocesses)
``` 
const cluster = require("cluster");
const http = require("http");
const numCPUs = require("os").cpus().length / 2;

if (cluster.isMaster) {
  console.log(`Master ${process.pid} is running`);
  for (let i = 0; i < numCPUs; i++) {
    cluster.fork();
  }
  cluster.on("exit", (worker, code, signal) => {
    console.log(`worker ${worker.process.pid} died`);
  });
} else {
  http
    .createServer((req, res) => {
      res.writeHead(200);
      res.end("hello world\n");
    })
    .listen(8000);
  console.log(`worker ${process.pid} started`);
}
```
2. Create a debug file as given in the docs 
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceFolder}/test.js",
      "autoAttachChildProcesses": true
    }
  ]
}

```

3. launch the debugger (with a breakpoint at `res.end("Hello World")` or elsewhere) and look at it being stuck :
```
cd /mnt/Documents/Projets/test ; /usr/bin/node --inspect-brk=15200 test.js
Debugger listening on ws://127.0.0.1:15200/5f2a7319-438f-45e2-9b34-54dade2d5bcc
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Master 18237 is running
Debugger listening on ws://127.0.0.1:15201/65008efc-1b46-4a7c-930d-e0e07caeb6b0
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:15202/3df330ed-7dac-493a-b66c-0292dfdb287b
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:15203/a24ef418-b736-4568-b7b6-6d66e5b6cfba
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:15204/fa348a09-97b2-4b21-ab48-cabe2469adbc
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:15205/95d05851-35cc-40e0-bd40-b95c8ec538bb
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:15206/ca3db31d-e023-4479-afb9-8eeec64e5a2b
For help, see: https://nodejs.org/en/docs/inspector
``` 

Note from other issues : VSCODE_PID is not set, trying to get it with echo $VSCODE_PID retruns nothing

No child can attach, nothing in the call stack, no breakpoint hitten...

Does this issue occur when all extensions are disabled?: Yes/No
Same problem with no extensions

**Comment by roblourens** [comment]
Are you sure nothing is attached? I see this at first in the call stack

![image](https://user-images.githubusercontent.com/323878/85295298-53de5e00-b465-11ea-843c-fa287c161e15.png)

and you will not hit that breakpoint unless you navigate to `localhost:8000` in a browser.

`VSCODE_PID` where is this coming from, what do you expect that to be?

**Comment by Ierezell** [comment]
Hi, sorry for the late reply....

I don't see anything in the call stack.

Furthermore, by adding a `console.log('Hello worker ${process.pid}')` just after the else (l.14) and putting a breakpoint on this line, it's never hit.

The only way to hit it is to manually attach the process (only with the preview fonction the classic one doesn't list processes) => `Ctrl+shift+P >> Debug : Attach to Node process (preview)`. Then it appears in the call stack and I can hit breakpoints. 

I got the same problem with a big project, the only way to make it work is to manually attach the subprocess.

**Comment by roblourens** [comment]
Can you try with VS Code Insiders, where we have our new debugger implementation? It solves some issues in this area. 

https://code.visualstudio.com/insiders

**Comment by Ierezell** [comment]
With the insider version (1.47.0-insider) I can have the toy exemple working ! 
I copied it in a typescript file just to compile and check sourcesmaps etc.. and everything is good

Furthermore the big code base can start in debug mode (which was impossible before)  and breakpoints are working in javascript ! 

However, they are unbound in typescript and it's painful to put breakpoints in javascript files... (it's still much better than before)

**Comment by roblourens** [comment]
Could you set `"trace": true`, try again with bps in TS, and share the log from the path in the debug console?

**Comment by connor4312** [comment]
Also @lerezell I notice you have outFiles `"${workspaceFolder}/out",`. These are [glob patterns](https://globster.xyz/), having that alone doesn't recurse. Maybe you mean `"${workspaceFolder}/out/**/*"?

**Comment by Ierezell** [comment]
Thanks all for your help ! 

@roblourens  

With trace I got  : 
```
Verbose logs are written to:
/tmp/vscode-debugadapter-1.json.gz
Could not read source map for file:///opt/visual-studio-code-insiders/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js: ENOENT: no such file or directory, open '/opt/visual-studio-code-insiders/resources/app/extensions/ms-vscode.js-debug/src/unhandledErrorReporter.js.map'
Could not read source map for file:///opt/visual-studio-code-insiders/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js: ENOENT: no such file or directory, open '/opt/visual-studio-code-insiders/resources/app/extensions/ms-vscode.js-debug/src/unhandledErrorReporter.js.map'
Could not read source map for file:///mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/index.js: ENOENT: no such file or directory, open '/mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/index.js.map'
Could not read source map for file:///mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/inference-session.js: ENOENT: no such file or directory, open '/mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/inference-session.js.map'
Could not read source map for file:///mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/inference-session-impl.js: ENOENT: no such file or directory, open '/mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/inference-session-impl.js.map'
Could not read source map for file:///mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/binding.js: ENOENT: no such file or directory, open '/mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/binding.js.map'
Could not read source map for file:///mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/tensor.js: ENOENT: no such file or directory, open '/mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/tensor.js.map'
Could not read source map for file:///mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/tensor-impl.js: ENOENT: no such file or directory, open '/mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/tensor-impl.js.map'
Could not read source map for file:///mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/onnx-value.js: ENOENT: no such file or directory, open '/mnt/Documents/Projets/BotPress/botpress/modules/new_qna/node_modules/onnxruntime/lib/onnx-value.js.map'

.... then console blabla for the program which is running normally 
07/02/2020 11:22:41.911 Launcher
 ========================================
                              Botpress Server            
                              Version 12.9.3             
                              OS linux arch
========================================
etc..
```

Source map of onnx and tensorflow are not that important and I guess it's really deep internals fonctions so it's okay because for now I just use them and I don't plan to debug their source code.

 From the log it doesn't seems I miss my code sourcemaps (which I can see in the file explorer)


@connor4312  I tried adding more globbing patterns but the problem still persists. (furthermore, like I said before all my collegues use this config and everything is working perfeclty for them, I guess it's more an OS problem because they are on ubuntu and I'm on Archlinux)

**Comment by connor4312** [comment]
Okay, thanks for giving that a show. Sharing the trace log as Rob mention would be helpful as well.

On further step you could take is to insert a `debugger;` statement in some of your source code. If that opens a 'read-only' TypeScript file in the wrong location, that means there's some path mapping that needs to be fixed. If it opens a compiled file, it means the sourcemaps weren't detected. Or you can share the log file and we can find out for you 🙂 

> ⚠️ The log file contains file paths from your local machine. If you have concerns about sharing it, you can email the log file to me at connor@xbox.com.

**Comment by Ierezell** [comment]
@connor4312  Thanks for the fast reply ! 

I added the `debugger;` statement, launch the debugger and it openned the good file at the debugger line. It's the good typescript file at the good place (juste with a js icon ironically).

From there I can see variables and do step by step stuff as expected ! 
My other "normal" breakpoint is still `Unbound breakpoint`

It's a good improvement, I can't debug without the "red dot gutter" breakpoint but at least I can add the `debugger;` statement

**Comment by connor4312** [comment]
Ah, sorry, the log I'm looking for is that file it prints out at the top of your debug console, e.g. `/tmp/vscode-debugadapter-1.json.gz` in what you gave above 🙂

**Comment by Ierezell** [comment]
[vscode-debugadapter-6.json.gz](https://github.com/microsoft/vscode/files/4865531/vscode-debugadapter-6.json.gz)

Here is the log.

I tried to change permission on the disk (777) but still the same. 

I also hit the `debugger;` statement, the other breakpoint is still unbound but if I add a new one (from the red gutter dot) after hitting the statement and click 'play' I hit the second one.

**Comment by connor4312** [comment]
I think your glob is just slightly off :) the source map is at `/mnt/Documents/Projets/BotPress/botpress/modules/new_qna/dist/backend/svmProbas.js.map` but the glob only has one star at the end, `/mnt/Documents/Projets/BotPress/botpress/modules/*/dist/*`. If you add another star it will match and should discover that file

https://globster.xyz/?q=%2Fmnt%2FDocuments%2FProjets%2FBotPress%2Fbotpress%2Fmodules%2F*%2Fdist%2F**&f=%2Fmnt%2FDocuments%2FProjets%2FBotPress%2Fbotpress%2Fmodules%2Fnew_qna%2Fdist%2Fbackend%2FsvmProbas.js.map

**Comment by Ierezell** [comment]
I tried with the globstar (**) : 

```
"${workspaceFolder}/modules/*/dist**",
even
"${workspaceFolder}/modules/**"
```

both works perfectly on my collegue laptops but not on mine .... 

When parsing the logs I can get the one for the breakpoint and I see  : 
```
{
  "tag": "dap.receive",
  "timestamp": 1593712634767,
  "metadata": {
    "connectionId": 2,
    "message": {
      "command": "setBreakpoints",
      "arguments": {
        "source": {
          "name": "src/bp/core/module-loader.ts",
          "path": "/mnt/Documents/Projets/BotPress/botpress/src/bp/core/module-loader.ts",
          "sourceReference": 0
        },
        "lines": [],
        "breakpoints": [],
        "sourceModified": false
      },
      "type": "request",
      "seq": 43
    }
  },
  "level": 0
}
```

```
{
  "tag": "dap.receive",
  "timestamp": 1593712234763,
  "metadata": {
    "connectionId": 2,
    "message": {
      "command": "setBreakpoints",
      "arguments": {
        "source": {
          "name": "retriever.ts",
          "path": "/mnt/Documents/Projets/BotPress/botpress/modules/new_qna/src/backend/retriever.ts"
        },
        "lines": [],
        "breakpoints": [],
        "sourceModified": false
      },
      "type": "request",
      "seq": 124
    }
  },
  "level": 0
}
```

Depending of the file and the folder I don't have the full path....

I will investigate on that and on the company project config to be sure it's not on my side and that every path is correct.

**Comment by connor4312** [comment]
Hm, okay, sounds good. If you're looking into it -- https://microsoft.github.io/vscode-pwa-analyzer/index.html is the tool I use to look at logs (you can open the .json.gz file directly). I'll take a shot at getting a setup with a linux vm on this next week.
