### ISSUE TITLE
Extension: low priority keybindings support

### ISSUE THREAD

**Issue by aioutecism** [Microsoft/vscode#10004]
- VSCode Version: 1.3.1
- OS Version: OSX 10.11.5

In my Vim extension, `escape` is overridden in order to mimic Vim's behavior:

```
{
    // ...

    "contributes": {
        "keybindings": [
            // ...
            { "command": "amVim.escape", "key": "escape", "when": "editorTextFocus" }
        ]
    }
}
```

This overrides `escape`'s default behaviors since VSCode appends extension keybindings to the end of default keybindings.
However, we need only to handle `escape` when none of the default behaviors got invoked. (So user can dismiss messages, cancel suggestions, etc.)

A low priority keybindings which are prepended to the VSCode's default keybindings should solve my problem.

**Comment by sandy081** [comment]
@aioutecism You can always make your key binding more restrictive by adding more when clauses. For eg, in this case, you can let `amVim.escape` command is executed on key press `escape` when editor text is in focus and editor is in insert mode. For this you need to create the respective context key for vim mode (insert or normal) and implement your key binding and vim extension accordingly.

For more information refer to our sample vim extension code here - https://github.com/Microsoft/vscode-extension-samples/blob/master/vim-sample/package.json#L21

**Comment by aioutecism** [comment]
Keybinding context won't solve the problem.

For example, when suggest widget is shown in Vim's insert mode, escape should close the widget instead of exiting to normal mode. I cloud add `suggestWidgetVisible` to specify the context but then I have to add all the conditions when VSCode corresponding to  `escape`.
This is all the default behaviors I have to deal with:

```
{ "key": "escape", "command": "closeReferenceSearchEditor",     "when": "inReferenceSearchEditor && !config.editor.stablePeek" },
{ "key": "escape", "command": "closeFindWidget",                "when": "editorFocus && findWidgetVisible" },
{ "key": "escape", "command": "closeBreakpointWidget",          "when": "breakpointWidgetVisible && editorFocus" },
{ "key": "escape", "command": "leaveSnippet",                   "when": "editorTextFocus && inSnippetMode" },
{ "key": "escape", "command": "closeMarkersNavigation",         "when": "editorFocus && markersNavigationVisible" },
{ "key": "escape", "command": "closeReferenceSearch",           "when": "referenceSearchVisible && !config.editor.stablePeek" },
{ "key": "escape", "command": "closeParameterHints",            "when": "editorTextFocus && parameterHintsVisible" },
{ "key": "escape", "command": "closeQuickFixWidget",            "when": "editorFocus && quickFixWidgetVisible" },
{ "key": "escape", "command": "hideSuggestWidget",              "when": "editorTextFocus && suggestWidgetVisible" },
{ "key": "escape", "command": "cancelRenameInput",              "when": "editorFocus && renameInputVisible" },
{ "key": "escape", "command": "closeAccessibilityHelp",         "when": "accessibilityHelpWidgetVisible && editorFocus" },
{ "key": "escape", "command": "workbench.action.closeMessages", "when": "globalMessageVisible" }
```

Besides, `escape`'s behavior may increase/change with VSCode update. It's not a good idea to keep tracking all changes about `escape`.

**Comment by sandy081** [comment]
@aioutecism Your argument makes sense to me.

@alexandrudima @jrieken Is there a way to provide priorities for key bindings?

**Comment by jrieken** [comment]
Internally yes but externally no. I believe extension and user config gets the highest prio since that are something more explicit. I believe this must be tackled with a long and complex `when` clause

**Comment by sandy081** [comment]
@aioutecism In this case, having a complex `when` clause is the only way for extension writers.

**Comment by aioutecism** [comment]
Appending all the default `escape` keybindings to the end of extension's keybinding section in `package.json` results in what I need. Guess I have to live with that 😞
