### ISSUE TITLE
make workspace in tree view more visually separated

### ISSUE THREAD

**Issue by benman64** [microsoft/vscode#100036]
because it looks like a folder icon visually it's hard to see when I pass workspaces as I scroll, this is a problem with lots of files and long directories. Having workspaces more distinct like maybe a hard line, or and empty row, could go with a hard line too. This would be good so I can better see it as I scroll.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
