### ISSUE TITLE
Error reporter cannot send data directly to GitHub

### ISSUE THREAD

**Issue by peterkos** [microsoft/vscode#100054]
- VSCode Version: 1.46.0
- OS Version: macOS 10.15.4

Attempting to send any somewhat-detailed bug report gives this error:
> There is too much data to send to GitHub directly. The data will be copied to the clipboard, please paste it into the GitHub issue page that is opened.

I tried to send the following message:
> 1. Search for an extension (e.g., "Custom CSS and JS Loader")
> 2. Attempt to copy the config information to put in settings.json via Cmd+C
> 3. Notice that it doesn't work (Cmd+V does not yield those contents)
> 4. Select that text and use Edit>Copy (in menu bar) to copy
> 5. Notice that your clipboard now has those contents

<hr />
Two main concerns here.

First, this is around 319 bytes of UTF-8 for "Steps to Reproduce". Is this a GitHub API limitation of some sort? This is very strange and I've never seen an application do this. 

Second, I think this is really bad UX: 
- The "Steps to Reproduce" area takes up a _large_ portion of the screen, of which I've filled not even half.
    <img width="914" alt="Screen Shot 2020-06-13 at 12 55 56 AM" src="https://user-images.githubusercontent.com/2782749/84560304-a48ce300-ad10-11ea-8169-ced01d99b2b4.png">
- The "include system information" and "include my enabled extensions" both still remain checked, which is **not** indicative of the current state (clipboard only contains "steps to reproduce")
- The "opened for you" GitHub issue does not include any _issue template information_ in the clipboard (VSCode version, OS version).
- The user, after filling out two select fields, two text fields, and two check boxes, must redo that work on GitHub.

**Comment by peterkos** [comment]
I see in this issue (https://github.com/microsoft/vscode/issues/73921) that it is performance-related, however I don't think this adresses the UX issues that are present (issue template info, system info, etc.)

Apologies if this is too close to that issue!

**Comment by peterkos** [comment]
And also, here is the list of extensions I have:

<img width="304" alt="Screen Shot 2020-06-13 at 1 08 00 AM" src="https://user-images.githubusercontent.com/2782749/84560460-642e6480-ad12-11ea-8480-e960b67931b0.png">

**Comment by RMacfarlane** [comment]
Hey @peterkos, here's an explanation of why dialog appears: https://github.com/microsoft/vscode/issues/97171#issuecomment-625439349 The limit is based on number of characters, not bytes, and is unfortunately pretty easy to hit with just system info/extensions.

I'm not seeing what you describe with that information not being copied when you click "OK" in the dialog - all of the diagnostic information should be copied to the clipboard at that time. What version of VS Code are you using?

**Comment by peterkos** [comment]
Thanks for the info! That makes a bit more sense. I'm using VSCode version 1.46.0; also updated my original post.

Also I think that was my fault; I tried again (a few times to make sure) and it does indeed copy all info. I must have copied the steps to reproduce myself, overwriting the clipboard 😅

**Comment by RMacfarlane** [comment]
I'm going to go ahead and close this, since the copy to clipboard functionality is working

**Comment by peterkos** [comment]
This still seems like a usability issue to force the user to copy&paste, even though I understand the technical limitation there. 

(For anyone browsing, to save some digging, see https://github.com/microsoft/vscode/issues/95165 for discussion on bypassing the limitation.)
