### ISSUE TITLE
File extensions dialog keeps previous selected file type 

### ISSUE THREAD

**Issue by gsilvers** [microsoft/vscode#100012]
- VSCode Version: 1.45.1
- OS Version: Windows 10 Pro Version 1809

Steps to Reproduce:

1. Open a new tab/file and type some text
2. Hit control+S or file save to save the file for the first time
3. In the file type drop down select a file type that has an extension built in like .html
4. Go back to the file type drop down and select a file type with no default extension like all files or text
5. Save the file and it will default to the prior extension you selected
6. I would expect going back to all files would produce a no extension file

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I do not understand this and would like to ask for a screen recording.
