### ISSUE TITLE
fails to install golang extension

### ISSUE THREAD

**Issue by scottstensland** [microsoft/vscode#100088]
Issue Type: <b>Bug</b>

brand new vs code install

I enter  ctrl + p

then paste

ext install golang.Go

to install golang extension as per your page
https://marketplace.visualstudio.com/items?itemName=golang.go

vs code fails with error

connect ENOENT /run/user/1000/vscode-b9b3c598-1.46.0-shared.sock

which is a totally useless error  ... get same error after uninstall then reinstall

installed on ubuntu 20.04 using

sudo dpkg -i code_1.46.0-1591780013_amd64.deb

please fix

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 5.4.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3422)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|11.59GB (1.17GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by joaomoreno** [comment]
Does the `/run/user/1000/vscode-b9b3c598-1.46.0-shared.sock` file exist? Does the `/run/user/1000` folder exist?

**Comment by scottstensland** [comment]
file

    /run/user/1000/vscode-b9b3c598-1.46.0-shared.sock

does not exist however dir `/run/user/1000/` does exist

**Comment by joaomoreno** [comment]
Is there any `/run/user/1000/*.sock` file _while Code is running_?

**Comment by scottstensland** [comment]
yes see my above comment where I list directory  `/run/user/1000/`

**Comment by joaomoreno** [comment]
Oh sorry about that. I know this sounds dumb... but have you tried restarting? Also, are you sure you don't have two versions of Code installed?
