### ISSUE TITLE
Changing cell between markdown & codes does not trigger NotebookCellLanguageChangeEvent

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#100042]
Found a slight inconsistentcy.
* Create an nb with support for multiple langauges
* Change cell language from markdown to some language or some language to markdown, at this point VSC triggers a `NotebookCellsChangeEvent`
* Now change a cell language from python to javascript, VSC triggers a `NotebookCellLanguageChangeEvent`

I.e. changing languages to/from Markdown is treated as a special change and not a change in language.

Any reason for this inconsistentcy.
I'd expect it to be treated as a change in language as opposed to change in cells.

@rebornix /cc

**Comment by rebornix** [comment]
Markdown and code cells are different in both renderer side and API side, even though we share the same language picker. FYI @roblourens
