### ISSUE TITLE
Synced Scrolling

### ISSUE THREAD

**Issue by Aamir2000** [microsoft/vscode#100004]
>This is not a duplicate issue its created on request of a team member here : #99742

Synced scrolling is also a thing which could be life changing for some developers. This feature focuses on syncing scrolling in Vscode and browser as new elements are being added and new changes have been made in css or preprocessors. It can help many developers like myself focus on working instead of focusing on scrolling browser everytime the page refreshes.

**Comment by sandy081** [comment]
> This feature focuses on syncing scrolling in Vscode and browser as new elements are being added and new changes have been made in css or preprocessors. 

Can you please elaborate more here.. what does the browser contain? Are you using some extension here?

**Comment by Aamir2000** [comment]
# Explanation

what I mean here is that when we write html to let say for making a website or making a web component. Vscode should at least sync scrolling with the browser we're previewing our html inside and update the browser content as we type in real time. Make it so when we scroll our file in Vscode browser also scroll to the same point so we can see what we're changing or doing in real time without having to leave our editor just to scroll back to where we were before as sometimes when we're using "live server for vscode" extension it sometimes refreshes and put us back on top of the page then we've to switch back to browser scroll down again and then switch back to our editor. Seems like a lot of work when we're in hurry we don't wanna waste time doing this constant back and forth with editor and browser. It'll be better if Vscode or the extension some how can be improved so that it scrolls automatically in sync with our code editor and also updates in real time as we type without having to save the file and then it updates. If you still need more explanation please do let me know I'm willing to give everything to get this functionality It can save me a lot of headaches and also I'm sure people will appreciate it a lot if you guys can make this happen its like a dream feature we want in our beloved code editor "Vscode".....Please 🥺

**Comment by sandy081** [comment]
Are you using any extension to preview your html with the browser?

**Comment by Aamir2000** [comment]
Yes "Live Server For Vscode" for previewing in browser

**Comment by sandy081** [comment]
Ok, then I would recommend to file the issue against that extension.

**Comment by Aamir2000** [comment]
uhhh why do you guys have a request feature section I don't understand sometimes like if we have to do everything through a extension why not make vscode editor as a extension itself so we can maybe install it on Sublime Text or maybe web storm at least they might wanna give better support than this com'on guys all that for that anyways still thanks for looking at these issues though

**Comment by sandy081** [comment]
Please understand that this request has to be implemented by the extension providing this feature (preview) and we do not own or host that. 

Filing the feature request against the corresponding extension helps them to go through it and validate the requirement and implement it.

**Comment by lockwoodnd** [comment]
Afdsjki-09qw4iu3 09-q4trui90-q4rjl;kq3rejkfm;lasdk’f;lj4590-3=2u=

**Comment by lockwoodnd** [comment]
Jfdsap0iju0892quy890
