### ISSUE TITLE
iPython console for Jupyter Notebook kernel: like Python Interactive for .py files

### ISSUE THREAD

**Issue by wodecki** [microsoft/vscode#100061]
That would be great to have Python interactive for Jupyter Notebook. 

Reason: at the moment I use Python interactive mostly for additional computations, different checks, etc. - and that's app. 80% of my time. When sth works > I move it to the main code.

It is only partially available for Jupyter Notebooks: jupyter console for the existing kernel (see eg. https://stackoverflow.com/questions/58926229/new-console-for-notebook-for-jupyter-notebook-in-visual-studio-code#) is very limited: won't display pandas dataframes like Python Interactive does (try eg. df.head()), etc.

At the moment I code in python <> Python interactive, and then move to Jupyter. This feature would greatly simplify this workflow :)

Many thanks in advance, 

Andy

**Comment by rebornix** [comment]
Please file this issue to the Python extension, which currently provide the Jupyter notebook support.
