### ISSUE TITLE
Autocompletion not working for React Native

### ISSUE THREAD

**Issue by Miraj98** [microsoft/vscode#100026]
Issue Type: <b>Bug</b>

Try to use VS Code for an existing React Native project. Autocompletion not working which is so frustrating because autompletion on VS Code was too good! And randomly it has stopped working for me. I even uninstalled and reinstalled VS Code (also the necessary extensions - ESLint, React Native Tools, etc) and still its not working 

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.94GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
prettier-vscode|esb|5.0.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-react-native|msj|0.16.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled), such as the react native extension?

Also, can you provide an example project? I just tested this in a new react-native project but can't reproduce this

**Comment by Miraj98** [comment]
I tried with all extension disabled and the problem persisted. Meaning I was able to reproduce the problem with all extensions disabled.
I also initialised a new React Native project and the problem persists. It is able to show me suggestions based on variables/functions already declared in the file but no code completion based on the functions and fields made available by the class. So for example if I have 
```
import {StyleSheet} from 'react-native'
```
Then writing `StyleSheet.` should show me suggestions like `create` or `absoluteFill` , etc. But it does not. And this is very weird because it was working absolutely fine the day before yesterday.

But yeah, since you were not able to reproduce to problem on your machine I think there should be some issue with my local setup. What might be the best way to investigate the issue further? VS Code's code completion feature is too good and it is now suddenly not working which is so frustrating. Any help is appreciated, thank you.

**Comment by syedhaider03** [comment]
Experiencing the same issue, was working fine before but now react native StyleSheet intellisense is not working and not showing suggestions for StyleSheet object which causes code navigation issues and is frustrating me.

**Comment by peteroid** [comment]
### issue
I experienced the same issue. I noticed that VSCode can automatically acquire the types for `react-native` but the warning [1] showed from v1.46 [2]

I have to install the types explicitly on the project to enable the autocomplete on v1.46.
```
yarn add -D @types/react-native
```

However, installing types explicitly seems not ideal as this issue also affects other libs like `react-redux`. The similar warning message was observed.

Another observation here is that the types packages are automatically loaded from `~/Library/Caches/typescript/3.8/node_modules/@types/react-native/index.d.ts` on v1.45 and the default typescript version changes to 3.9 on v1.46. 

### workaround works for me
1. Use 1.45.1 at the moment
2. Install all the missing types packages

### ref
[1]
```
Could not find a declaration file for module 'react-native'. '____/node_modules/react-native/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native';`ts(7016)
```

[2]
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z (3 days ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by mjbvz** [comment]
Can someone please provide an example broken project? I can't reproduce in a new react native project:

<img width="975" alt="Screen Shot 2020-06-23 at 3 10 34 PM" src="https://user-images.githubusercontent.com/12821956/85470326-b453c500-b563-11ea-8b24-2a25ff8394cc.png">

Also for someone who is seeing this issue, what file is opened when you run `F12` (go to definition) on the react-native import? Mine goes to:

<img width="1049" alt="Screen Shot 2020-06-23 at 3 11 39 PM" src="https://user-images.githubusercontent.com/12821956/85470429-dd745580-b563-11ea-8c45-26ee9d98a9b7.png">
