### ISSUE TITLE
Quick-Fix dialog UX Improvement

### ISSUE THREAD

**Issue by erfanium** [microsoft/vscode#100025]
![Screenshot-from-2020-06-12-22-56-53](https://user-images.githubusercontent.com/47688578/84535506-29700080-ad01-11ea-90ed-7209084e214d.jpg)
Sometimes I try to click on `Quick fix` button (via `1` path) but the dialogue disappears immediately, so I need move my mouse over path `2` to avoid this!!

Better to add a tiny delay after `mouse out` or something to fix this UX issue.

**Comment by erfanium** [comment]
@sandy081 Duplicate of what issue? I didn't find anything.
Thanks.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/97328
