### ISSUE TITLE
problem with changes

### ISSUE THREAD

**Issue by fuerstbro** [microsoft/vscode#100049]
Issue Type: <b>Bug</b>

The visual studio code will not recognize any changes made to my program.
 I changed somthing, hit save, went to my website, and pressed refresh,  and nothing changed. So I went to my inspection tool and looked where I had put my line of code, and it wasn't there.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.90GB (6.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
emmet-live|yse|1.0.0

</details>

**Comment by codingonHP** [comment]
@fuerstbro Are you saying VS Code is not saving your file? If this is the case then just open the file in another editor (notepad) and verify your changes.
If your changes are saved but they are not showing up in browser then it means they are being cached. Try to do hard reload or just open the page in incognito and check.

**Comment by sandy081** [comment]
I suspect this is nothing to do with VS Code as you said `hit save`. Please file the issue against the extension using which you are debugging/running the program.
