### ISSUE TITLE
Global Configuration for "launch.json" such that attributes are shared between configurations

### ISSUE THREAD

**Issue by Harsha-Yalagach** [microsoft/vscode#100188]
I have a project/workspace with multiple launch configurations. There are got of configuration values that are common for all the launch configuration, like environment variables, Current Working Directory.

I would want a way to consolidate all these common settings/configuration into a common area, probably a new section/dictionary called "global".

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. I have renamed it to make it a bit clearer. Thus assigning to backlog and we might add this in the future. Thanks
