### ISSUE TITLE
There is no IntelliSense, quick fix, yellow bulb

### ISSUE THREAD

**Issue by islamyoussef** [microsoft/vscode#100194]
First of all thanks for every help you supply us with,
after updating Flutter & Dart something went wrong, first the colorfull code disappeared every thing became white -I use dark theme- second there is no yellow bulb or IntelliSense.

Note: 
1. I'm using VS Code version 1.46.0
2. when i try to install any Extension error appers on the right side says
[Unable to open 'Extension: Todo Tree': An unknown error occurred. Please consult the log for more details..]
then follow with [Failed to install 'gruntfuggly.todo-tree'.]
3. I fixed the color of code, but I couldn't fix the rest.

4. I can complete what I'm started but without those feature.
![Capture](https://user-images.githubusercontent.com/25922224/84661140-3287ea00-af1a-11ea-83fb-78da35d4d8f7.PNG)
.....flutter doctor result
![Capture1](https://user-images.githubusercontent.com/25922224/84661203-4af80480-af1a-11ea-9cfb-81d97e5f5b39.PNG)

thanks again

**Comment by sandy081** [comment]
For the issue related to Dart & Flutter please file issue against those extensions.
