### ISSUE TITLE
Getting "Extension host terminated unexpectedly." eveytime i start visual studio code

### ISSUE THREAD

**Issue by clashbrizz** [microsoft/vscode#100130]
```
Extension host terminated unexpectedly. Code:  0  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:155
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidChangeNotification @ notificationsAlerts.ts:40
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.diff.
Old grammar file: file:///c%3A/Users/SONY/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/git/syntaxes/diff.tmLanguage.json.
New grammar file: file:///c%3A/Users/SONY/.vscode/extensions/rafaelmaiolla.diff-0.0.1/syntaxes/diff.tmLanguage
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.html.basic.
Old grammar file: file:///c%3A/Users/SONY/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/html/syntaxes/html.tmLanguage.json.
New grammar file: file:///c%3A/Users/SONY/.vscode/extensions/salesforce.salesforcedx-vscode-lightning-48.20.0/syntaxes/html.tmLanguage.json
register @ TMScopeRegistry.ts:45
extensionHostProcessManager.ts:73 Error received from starting extension host
(anonymous) @ extensionHostProcessManager.ts:73
extensionHostProcessManager.ts:74 timeout
(anonymous) @ extensionHostProcessManager.ts:74
lifecycle.ts:134 Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at e.add (lifecycle.ts:134)
    at e._register (lifecycle.ts:164)
    at extensionHostProcessManager.ts:80
add @ lifecycle.ts:134
```

**Comment by clashbrizz** [comment]
can someone help to resolve this issue?

**Comment by gregid** [comment]
@clashbrizz Try identifying the most likely extension that could be the culprit - in my case it was `vscode-jest` then disable the extension, restart vscode then enable the extension after restart. If you can't identify one try disabling all of them and then enable one by one after restart.

**Comment by bvrygud** [comment]
Have the same problem mentioned in # #100124

**Comment by alexdima** [comment]
@clashbrizz Can you please try running `code --crash-reporter-directory <path>` and attach the generated dump file? More steps are described here -- https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

Also, does this reproduce when disabling all extensions?

**Comment by joeybaba** [comment]
i am new user of vscode, when i first install and open vscode, software tell me this error. i didn't know what worry with it.

**Comment by bvrygud** [comment]
Added the details for console crash logs w.r.t macos
[Console Logs](https://github.com/microsoft/vscode/issues/100124#issuecomment-647856183)

**Comment by joeybaba** [comment]
del `export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/` from .zshrc or .bash_profile. it work to me.

**Comment by clashbrizz** [comment]
Hi Alexdima,

I tried by disabling all extension, still i get same issue.
please find the crash report in attachment

[Code__PID__696__Date__06_28_2020__Time_05_27_28PM__634__Log.txt](https://github.com/microsoft/vscode/files/4842193/Code__PID__696__Date__06_28_2020__Time_05_27_28PM__634__Log.txt)
[Code__PID__3924__Date__06_28_2020__Time_05_27_06PM__780__Log.txt](https://github.com/microsoft/vscode/files/4842194/Code__PID__3924__Date__06_28_2020__Time_05_27_06PM__780__Log.txt)
[Code__PID__5748__Date__06_28_2020__Time_05_27_31PM__783__Log.txt](https://github.com/microsoft/vscode/files/4842195/Code__PID__5748__Date__06_28_2020__Time_05_27_31PM__783__Log.txt)
[Code__PID__7456__Date__06_28_2020__Time_05_27_29PM__693__Log.txt](https://github.com/microsoft/vscode/files/4842196/Code__PID__7456__Date__06_28_2020__Time_05_27_29PM__693__Log.txt)
[Code__PID__7556__Date__06_28_2020__Time_05_27_37PM__803__Log.txt](https://github.com/microsoft/vscode/files/4842197/Code__PID__7556__Date__06_28_2020__Time_05_27_37PM__803__Log.txt)
[Code__PID__7900__Date__06_28_2020__Time_05_27_07PM__52__Log.txt](https://github.com/microsoft/vscode/files/4842198/Code__PID__7900__Date__06_28_2020__Time_05_27_07PM__52__Log.txt)
[Code__PID__8368__Date__06_28_2020__Time_05_27_07PM__196__Log.txt](https://github.com/microsoft/vscode/files/4842199/Code__PID__8368__Date__06_28_2020__Time_05_27_07PM__196__Log.txt)
[Code__PID__8532__Date__06_28_2020__Time_05_27_31PM__658__Log.txt](https://github.com/microsoft/vscode/files/4842200/Code__PID__8532__Date__06_28_2020__Time_05_27_31PM__658__Log.txt)
[Code__PID__8704__Date__06_28_2020__Time_05_27_07PM__328__Log.txt](https://github.com/microsoft/vscode/files/4842201/Code__PID__8704__Date__06_28_2020__Time_05_27_07PM__328__Log.txt)
[Code__PID__9148__Date__06_28_2020__Time_05_27_34PM__672__Log.txt](https://github.com/microsoft/vscode/files/4842202/Code__PID__9148__Date__06_28_2020__Time_05_27_34PM__672__Log.txt)
[Code__PID__9912__Date__06_28_2020__Time_05_29_28PM__747__Log.txt](https://github.com/microsoft/vscode/files/4842203/Code__PID__9912__Date__06_28_2020__Time_05_29_28PM__747__Log.txt)
[Code__PID__10528__Date__06_28_2020__Time_05_27_07PM__512__Log.txt](https://github.com/microsoft/vscode/files/4842204/Code__PID__10528__Date__06_28_2020__Time_05_27_07PM__512__Log.txt)
[Code__PID__11608__Date__06_28_2020__Time_05_27_07PM__688__Log.txt](https://github.com/microsoft/vscode/files/4842205/Code__PID__11608__Date__06_28_2020__Time_05_27_07PM__688__Log.txt)

**Comment by deepak1556** [comment]
@clashbrizz they are not crash minidumps.

Can you attach the files generated in the `<path>` directory `code --crash-reporter-directory <path>`, please make sure the path is absolute.

**Comment by clashbrizz** [comment]
Hi Deepak
Please find the compressed file of crash report: 
[VSCode Crashes.zip](https://github.com/microsoft/vscode/files/4849550/VSCode.Crashes.zip)

**Comment by nguyenxndaidev** [comment]
Please vote this related issue: [Prevent global crash when extension crashes](https://github.com/microsoft/vscode/issues/100283)!

**Comment by deepak1556** [comment]
@clashbrizz do you still experience the crash with latest stable ?

**Comment by joeybaba** [comment]
> @clashbrizz do you still experience the crash with latest stable ?
already fixed
