### ISSUE TITLE
Starting with vscode 1.43 non-ascii characters with braces and parentheses are not rendered correctly

### ISSUE THREAD

**Issue by Abdullah-AlAttar** [microsoft/vscode#100112]
Issue Type: <b>Bug</b>
I tried it with extensions disabled.
put the following line in a .lua file
note: also happens with other languages, it just happens that I was using lua.
```lua 
what = (["على"] . ("محموله"))
```
this is how it looks in version 1.42.1
![Image of Correct behavior](https://i.imgur.com/RRqtMV8.png)
and this is in  the versions after 
![Image of incorrect behavior](https://i.imgur.com/wfLMVpf.png)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 5.4.0-7634-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.01GB (20.07GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by MustafaAbdalwahab** [comment]
I have the same Issue I am running vscode version 1.45 on windows.
<img width="777" alt="Screenshot 2020-06-14 at 1 34 54 PM" src="https://user-images.githubusercontent.com/26796057/84590133-f171d600-ae44-11ea-92d5-93d379ff1bb3.png">

**Comment by Abdullah-AlAttar** [comment]
Thanks, but I don't think the solution cover all the cases, this is in version 1.65.2
![Screenshot from 2022-04-03 02-23-31](https://user-images.githubusercontent.com/18447305/161403252-c0c78cbb-9837-4579-aab3-f8e1a77ebfd2.png)
Which should look like this if rendered correctly
![Screenshot from 2022-04-03 02-24-59](https://user-images.githubusercontent.com/18447305/161403272-1829018c-9eb3-4c10-ae5a-8e87419ad550.png)
