### ISSUE TITLE
Add UI list of all registered action participants (save, file rename, etc.)

### ISSUE THREAD

**Issue by narfanar** [microsoft/vscode#100102]
It's currently incredibly frustrating trying to debug slow action participants by turning off extensions one-by-one. Considering how terrible an effect a misbehaving extension can have on the entire experience, and how participants sort of constitute an "interface" for the user (not too different from a permission list), it seems reasonable to have an easy way in the main UI to view all registered participants.

Context: https://stackoverflow.com/questions/60229040/viewing-debugging-slow-save-participants

**Comment by jrieken** [comment]
> it seems reasonable to have an easy way in the main UI to view all registered participants.

It's actually not super trivial because providers are very dynamic and them being applicable or not can different from file to file
