### ISSUE TITLE
White flash when reloading covered part of window

### ISSUE THREAD

**Issue by saleyn** [microsoft/vscode#100101]
- VSCode Version:  1.46.0
- OS Version: Arch Linux 5.6.15

Steps to Reproduce:

1. Open VSCode and some other window.
2. Switch back and forth between windows and observe white flicker of the portion of the VSCode window that was covered by another window, before it gets properly repainted.

Does this issue occur when all extensions are disabled?: Yes

This issue doesn't happen with other applications running on the same desktop, only with VSCode.

![ezgif-4-d061f8572668](https://user-images.githubusercontent.com/272543/84581591-d5bcf000-adb0-11ea-8e04-d67011fc73d7.gif)

**Comment by deepak1556** [comment]
Can you check if the issue happens with the insiders release https://code.visualstudio.com/insiders/

**Comment by saleyn** [comment]
The issue is not observed in the insiders release.  Thank you, this bug has been very annoying!

**Comment by deepak1556** [comment]
Thanks for confirming!

**Comment by saleyn** [comment]
What version will this fix be included in?

**Comment by saleyn** [comment]
Never mind - I see this is fixed again in insiders build 1.48.

**Comment by deepak1556** [comment]
Electron 9 will be included in upcoming stable release, closing this.
