### ISSUE TITLE
the system can not find the specified at...

### ISSUE THREAD

**Issue by yashwantmadane** [microsoft/vscode#100165]
Wi am trying to print the value of i using %u but systm giving me error as following.
Program 'check.exe' failed to run: The system cannot     
find the file specifiedAt line:1 char:70                   
+ ... de\.vscode\" ; if ($?) { gcc check.c -o check } ;  
if ($?) { .\check }
+
          ~~~~~~~.
At line:1 char:70                                          
+ ... de\.vscode\" ; if ($?) { gcc check.c -o check } ;  
if ($?) { .\check }
+
          ~~~~~~~                                          
    + CategoryInfo          : ResourceUnavailable: (:)   
   [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed      

this error is given in red color,dont know why.

**Comment by sandy081** [comment]
Please file the issue agains the extension that is causing this.
