### ISSUE TITLE
HMR port can't be exported in codespaces/online

### ISSUE THREAD

**Issue by janat08** [microsoft/vscode#100128]
HMR- hot module reloading- doesn't work in workspaces, and the bundle sizes are big so reloading the whole page takes quite a bit of time (hot reload doesn't work either).

**Comment by sandy081** [comment]
I do not think this is a feature that VS Code supports out of the box and I assume you are having an extension for your described feature. Please file issue against that extension.

**Comment by janat08** [comment]
Basically you can't expose ports in web version of visual studio online, renamed codespaces. It links here for feature requests, I hate Microsoft.

**Comment by janat08** [comment]
You must know what hmr/live reload is.

**Comment by sandy081** [comment]
> Basically you can't expose ports in web version of visual studio online, renamed codespaces.

This description would have been helpful.

**Comment by janat08** [comment]
Lol ye, I used the wrong term too, workspaces.

**Comment by alexr00** [comment]
@fara-nak this sounds like a feature request for a forwarded ports view in the web version of codespaces. Can I give this to you?

**Comment by janat08** [comment]
It's no visible until you run npm or there're ports to forward, reproducible steps.

**Comment by fara-nak** [comment]
@janat08 you should be able to see the "Codespace details" by default even if you haven't forwarded any port yet. that's why i'm wondering if you can share repro steps with us? i'm wondering if it's a regression.
![image](https://user-images.githubusercontent.com/48534922/85173179-75ea9d00-b227-11ea-8d8d-7d025f01f9f0.png)

**Comment by janat08** [comment]
I didn't find it when there were connection issues. Otherwise it just loaded fine on refresh.
Failed to connect to the remote extension host server (Error: Time limit reached)

**Comment by janat08** [comment]
Im using firefox.
