### ISSUE TITLE
Add API support for submenus

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#100172]
Add support for submenus to simplify the menu structure of the Git extensions '...' menu.

**Comment by gjsjohnmurray** [comment]
See #9827

I'd particularly like https://github.com/microsoft/vscode/issues/9827#issuecomment-619989638 to be catered for in the new API, so an extension can contribute a submenu whose contents are computed at display-time.

**Comment by joaomoreno** [comment]
Syntax proposal:

```json
{
	"contributes": {
		"menus": {
			"scm/title": [
				{
					"command": "git.commit",
					"group": "navigation"
				},
				{
					"submenu": "git.stage",
					"group": "navigation"
				}
			],
			"git.stage": [
				{
					"command": "git.stageAll",
					"group": "navigation"
				},
				{
					"command": "git.stageUntracked",
					"group": "navigation"
				}
			]
		},
		"submenus": [
			{
				"id": "git.stage",
				"label": "Stage"
			}
		]
	}
}
```

**Comment by gjsjohnmurray** [comment]
> Syntax proposal:

@joaomoreno Maybe extend the syntax of `submenus` contribution to support submenus that call the extension at display-time to obtain their contents.

**Comment by joaomoreno** [comment]
That will definitely not be in there for the first iteration. That should even be generalized for regular menus.

**Comment by joaomoreno** [comment]
@jrieken Added the `icon` property in the `submenus` contribution, in order to make submenus work in toolbars. 👍

**Comment by jrieken** [comment]
Re-opening for the finalisation process...

**Comment by joaomoreno** [comment]
@jrieken I had this one created: https://github.com/microsoft/vscode/issues/103946

I leave it up to you to decide which one to keep. I won't be able to work in finalizing it since I'm out in August so after choosing the issue, pick one option:

1. Keep it in August and assign someone else;
2. Move it to September and assign myself.

**Comment by jrieken** [comment]
> I leave it up to you to decide which one to keep.

The newish flow is to have a single item that can followed through out the phases of idea, proposal, and finalization. September is good for me

**Comment by yubaoquan** [comment]
When will submenu apis be stable?

**Comment by joaomoreno** [comment]
With the next upcoming stable release: September 2020.

**Comment by joaomoreno** [comment]
**Verification**

This new API should be usable without the proposed flag!

**Comment by erythana** [comment]
Is it possible to change the Submenu via Code? (= alter the Package.json?)
