### ISSUE TITLE
Wrong GPU used for hardware acceleration on macOS

### ISSUE THREAD

**Issue by raiskila** [microsoft/vscode#100154]
- VSCode Version: Version: 1.47.0-insider 
- OS Version: macOS Catalina 10.15.5 (19F96)

### Steps to Reproduce:

Depending on how VS Code is launched (clicking on app icon vs. using the `code` shortcut in terminal), it may use a different GPU for rendering.

The 13 inch MacBook Pro only comes with integrated Intel Iris graphics. This combined with a high-resolution external monitor results in poor scrolling performance in VS Code (#26398). Thus I'm using an external GPU with the monitor.

In macOS, it seems apps that don't actively choose to take advantage of the external GPU must be "forced" to do so by pressing Cmd-I on the app's icon in "/Applications" in Finder and selecting "Prefer External GPU". VS Code won't render on the external GPU unless this is selected.

However, when launched via the terminal using the `code` command, it seems this setting is ignored and VS Code will always use the internal, slow GPU. This can be seen by poor scrolling performance and by observing which of the "Code - Insiders Helper (GPU)" processes on the GPU tab of Activity Monitor is using GPU (there seems to be one process per GPU) while scrolling a long file in VS Code.

### Does this issue occur when all extensions are disabled?
Yes

**Comment by raiskila** [comment]
Update on GPU selection behavior in Big Sur - now the GPU used by the "Code - Insiders Helper (GPU)" process is determined by whether my laptop clamshell is open or closed _while starting VS Code_ (from the Dock icon).

This is with an external monitor connected to an external GPU. Even though the external monitor is set as the primary display, just having the laptop's built in screen available seems to be enough to cause the "Code - Insiders Helper (GPU)" process to prefer the slower integrated GPU.

So to get VS Code to use the fast GPU, I close my laptop lid, then start VS Code, then open the lid again.

**Comment by raiskila** [comment]
This behavior may have changed again (?) but I may have found better workaround.

- Open /Applications in Finder, hit ⌘I ("Get Info") on Visual Studio Code.app, and check "Prefer External GPU"
- Open /Applications/Visual Studio Code.app/Contents/Frameworks in Finder and do the same for all three "Code Helper" ".app"s here

All in all, this is a pretty uncommon setup, but there are probably a bunch of people unknowingly dealing with poor graphics performance in VS Code who've bought into a setup like this in response to Apple's marketing push of eGPUs circa 2018. Hopefully these workarounds reach some of those people. Looking forward to replacing this mess with an ARM MBP.

**Comment by deepak1556** [comment]
Closing as GPU selection is performed by the runtime.
