### ISSUE TITLE
Missing title borders

### ISSUE THREAD

**Issue by leandrowilliam** [microsoft/vscode#100138]
Issue Type: <b>Bug</b>

The right and botton border of the title box is missing....

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.30GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/leandrow/dev/wenlogic/ehr-app --remote=wsl+Ubuntu-20.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2495)|
|Memory (System)|12.43GB (11.42GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-close-tag|for|0.5.7
dotenv|mik|1.0.1
remote-wsl|ms-|0.44.2
vscode-icons|vsc|10.1.1
JavaScriptSnippets|xab|1.8.0
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
prettier-vscode|esb|5.0.0
vscode-pull-request-github|Git|0.16.1
magit|kah|0.2.2
git-graph|mhu|1.23.0
vscode-scss|mrm|0.9.0
vscodeintellicode|Vis|1.2.8

(3 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/9604296/84602638-ec1d8700-ae56-11ea-9127-a730670e4a13.png)

**Comment by bpasero** [comment]
This is the native hover we get from Electron.

**Comment by deepak1556** [comment]
Can you confirm if this issue is present with latest stable ?
