### ISSUE TITLE
XML Node Collapsing Effected by Tab Indentations

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/vscode#100176]
Issue Type: <b>Bug</b>

1) Open `generic.xaml` from `c:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\<Version>\Generic\generic.xaml` where version could be 10.0.18362.

2) Collapse a `<VisualStateManager.VisualStateGroups>` node using arrow on left margin. E.g. Line 6972

3) Note that the whole XML tag is not collapsed, it only goes to line `7042` however this tag ends on line `7309`.

![image](https://user-images.githubusercontent.com/24302614/84635956-d0db6780-aea8-11ea-9105-731411238c2a.png)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.90GB (44.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by michael-hawker** [comment]
It looks like if indentation levels of tabs may be effecting this, for instance if you have this:

```xml
<Grid>
    <Button/>
    <Button/>
</Grid>
```

It works fine, but if you have this:

```xml
    <Grid>
<Button/>
<Button/>
    </Grid>
```

Then the collapse option only appears for the 3rd line:

![image](https://user-images.githubusercontent.com/24302614/84636377-60811600-aea9-11ea-807a-f9673029d27b.png)

The indentation of elements/properties shouldn't effect the ability to collapse them properly as long as they're on separate lines.

**Comment by gjsjohnmurray** [comment]
From https://code.visualstudio.com/docs/editor/codebasics#_folding

> Folding regions are by default evaluated based on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.
> 
> Since the 1.22 release, folding regions can also be computed based on syntax tokens of the editor's configured language. The following languages already provide syntax aware folding: Markdown, HTML, CSS, LESS, SCSS, and JSON.

Maybe you can find an extension that implements what's necessary for smarter folding of XML.

**Comment by aeschli** [comment]
Yes, to XML aware folding has to come from an extension. https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml is an XML extension that does that.
