### ISSUE TITLE
regex sub match cannot work using replace in files

### ISSUE THREAD

**Issue by timeregained** [Microsoft/vscode#10019]
- VSCode Version: 1.3.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1.  Create test1.txt and test2.txt with the same content as following:
Test 300
Test 301
Test 302

2. I can use regex find all lines in both files through:
`Test (3[0-9]*)`
When I try replace in files with following regex:
`Test $1-100`

both files become as following:
Test $1-100
Test $1-100
Test $1-100

Not as expected:
Test 300-100
Test 301-100
Test 302-100

However, the sub math replace works well in replace in single file.

**Comment by sandy081** [comment]
Duplicates https://github.com/Microsoft/vscode/issues/9010

**Comment by sandy081** [comment]
Duplicates https://github.com/Microsoft/vscode/issues/9010
