### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by varunsharda** [microsoft/vscode#100124]
Issue Type: <b>Bug</b>

Extension host terminated unexpectedly. getting this always

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
github-repository-manager|hen|0.3.6
azure-pipelines|ms-|1.170.0
vscode-azureappservice|ms-|0.17.0
vscode-azurefunctions|ms-|0.22.1
vscode-azureresourcegroups|ms-|0.1.0
vscode-azurestorage|ms-|0.9.0
vscode-azurevirtualmachines|ms-|0.1.0
vscode-cosmosdb|ms-|0.13.0
vscode-docker|ms-|1.2.1
vscode-dotnet-runtime|ms-|0.1.2
azure-account|ms-|0.8.11
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.0.11
azurerm-vscode-tools|msa|0.10.0

</details>

**Comment by gregid** [comment]
I had the same problem #100118 
In my case `disabling` -> `restarting` -> `enabling` the extension helped to fix it

**Comment by bvrygud** [comment]
Even I am having the same issue. 

VsCode Version: Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z (4 days ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

I am trying in mac. 

I uninstall all everything related to VS Code using instructions provided in https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2019

I did a fresh install without installing any extensions. But got the same issue as 

Extension Host terminated unexpectedly. 

Developer tools had the below problem: 

`dyld: Symbol not found: __ZN20wireless_diagnostics6google8protobuf2io16CodedInputStream24default_recursion_limit_E  Referenced from: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib  Expected in: /usr/local/lib/libprotobuf-lite.dylib in /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib`


It is further blocking me to do a git clone as well. I have been already using git in my mac. Location of git is /usr/bin/git. 
But when I use command pallette to do a git clone , I get the following issue 

Command 'Git: Clone' resulted in an error (command 'git.clone' not found)

Even my Source Control tab in left panel, shows "No Source Control providers registered" 

I tried to set my `"git.path": "/usr/bin/git"`. Still had the same issue. 

I tried to disable git using `"git.enabled": false`. Still had the same issue related to Extension host when i restarted vscode.

**Comment by alexdima** [comment]
@varunsharda Could you please try to execute `code --crash-reporter-directory <path>` from the command line? There are more steps here -- https://github.com/microsoft/vscode/wiki/Native-Crash-Issues -- about how to collect a dump file and attach it here.

**Comment by bvrygud** [comment]
@alexdima Tried from my mac. Crash report from Mac console logs


[Code Helper (Renderer)_2020-06-22-182808_.crash.zip](https://github.com/microsoft/vscode/files/4816493/Code.Helper.Renderer._2020-06-22-182808_.crash.zip)

**Comment by deepak1556** [comment]
@bvrygud the issue is specifically from the mysql library that started shipping its own version of protobuf library which collides with the standalone one https://github.com/microsoft/vscode/issues/100118#issuecomment-647888790 . I don't know the right solution here wrt the package, but you should be fine just excluding `mysql` library from the `DYLD_LIBRARY_PATH`
