### ISSUE TITLE
VSCode hitting CPU

### ISSUE THREAD

**Issue by caub** [microsoft/vscode#100136]
- VSCode Version: 1.46.0
- OS Version: Linux x64 4.15.0-106-generic
- Hardware: CPU i5 8th gen, 16G RAM, SSD

Steps to Reproduce:

1. Run just one instance of VSCode, on a react-scripts app, moderately large, with a few opened tabs, vscode will start hitting CPU when you edit code or save, it's gets really intense if you save invalid code

This problems happens gradually, maybe not just from latest version

I've made sure that node_modules/ and build/ directories are in my files.exclude, files.watcherExclude and search.exclude as I know this has been a problem in the past

Does this issue occur when all extensions are disabled?: Yes

**Comment by mpx2m** [comment]
I have the same problem

**Comment by sandy081** [comment]
Do you also see this when you disable all extensions?

To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks.

When Code is consuming lots of CPU, please run "code --status" from the command line (or "code-insiders --status" if you are using VS Code Insiders edition).

Please attach the output of this command to this issue. Thanks!

**Comment by caub** [comment]
Is there a way for me to monitor vscode subprocesses, to have an idea what's the issue?

I really confirm I'm running vscode with `code --disable-extensions .` (anyway, my only extension was code runner, not something that would use CPU constantly), shortly after my laptop fan will activate. If I close vscode, and run sublimetext on the same project, the fan goes silent again

the only other thing that can trigger the fans is google meet, I'd really like vscode to get back to something lighter, less intensive for the CPU

**Comment by sandy081** [comment]
Please provide the information I requested in my previous comment:

To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks.

When Code is consuming lots of CPU, please run "code --status" from the command line (or "code-insiders --status" if you are using VS Code Insiders edition).

Please attach the output of this command to this issue. Thanks!

**Comment by caub** [comment]
@sandy081 Sorry I missed that `code --status` part

Here's what I get currently, the fan is running not too loud, it looks fine, but maybe there are things I could improve/disable for performance?
```
[25064:0618/143811.912441:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS Version:       Linux x64 4.15.0-106-generic
CPUs:             Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1000)
Memory (System):  15.56GB (8.58GB free)
Load (avg):       2, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox --disable-extensions
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 disabled_software
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  unavailable_off
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	   112	 11037	code main
    0	    32	 11039	   zygote
    0	    80	 11061	   gpu-process
    0	    48	 11074	   utility
    0	   112	 11290	   shared-process
    0	     0	 25087	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 25088	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   319	 23422	   window (index.js - admin - Visual Studio Code)
    0	   112	 23451	     extensionHost
    0	    96	 23539	       electron_node tsserver.js 
    0	  1291	 23540	       electron_node tsserver.js 
    0	   127	 23574	         electron_node typingsInstaller.js typesMap.js 
    0	    48	 23646	       /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=23451
    0	     0	 23452	     /bin/bash
    0	    32	 23614	       npm
    0	     0	 23625	         sh -c PORT=7300 react-scripts start
    0	    32	 23626	           node /home/caub/dev/Storeganise/admin/node_modules/.bin/react-scripts start
    0	   478	 23633	             node /home/caub/dev/Storeganise/admin/node_modules/react-scripts/scripts/start.js
    0	    80	 23521	     watcherService
    0	    48	 23726	     searchService

Workspace Stats: 
|  Window (index.js - admin - Visual Studio Code)
|    Folder (admin): 890 files
|      File types: js(560) less(39) scss(32) css(31) png(22) map(19) eot(8)
|                  svg(8) ttf(8) woff(8)
|      Conf files: settings.json(1) jsconfig.json(1) package.json(1)

```

**Comment by bpasero** [comment]
@caub in your output I am not seeing any of VSCode processes take any CPU?

**Comment by caub** [comment]
@bpasero correct, so I don't really know, could be the room temperature, but it's not really hot

I still observe that CPU fan starts running hard if I save invalid code, I guess tsserver isn't happy when this happens

**Comment by bpasero** [comment]
@caub are you able to pin point it to the TS server or do you speculate on that?

**Comment by caub** [comment]
it's just pure speculation sorry

**Comment by bpasero** [comment]
Ok, please update when you found out which process exactly is spending CPU cycles.
