### ISSUE TITLE
Extension API: Sense theme change

### ISSUE THREAD

**Issue by jaime-olivares** [Microsoft/vscode#10010]
It should be possible to detect when the user changes the theme, as well as what is the new theme palette (dark, light, high-contrast).

**Comment by rozzzly** [comment]
That sounds reasonable, but makes me curious as to your usecase?

**Comment by jaime-olivares** [comment]
@rozzzly, I have created an extension (see https://github.com/jaime-olivares/vscode-yuml)  where the preview image is rendered before creating the output html, so I cannot rely on CSS variables like those added in v1.3. I need to know the theme style at JS/node code level, at the beginning and after a theme change.

**Comment by jaime-olivares** [comment]
A side note: the current extension API allows us to know every editor and workspace preference/setting but not the theme details.

**Comment by jaime-olivares** [comment]
Not sure how I closed this issue. Reopening...

**Comment by bpasero** [comment]
Isn't this possible ever since we moved the selected them into settings by using the normal settings API and events?
