### ISSUE TITLE
ModelService: Cannot add model because it already exists

### ISSUE THREAD

**Issue by Jaroslaw-Brzezinski** [microsoft/vscode#100181]
Issue Type: <b>Bug</b>

Hello,

An error occurs when a new terminal is attempted to start up (as shown below). At the same time the entire contents of the extension panel disappears and an empty side panel opens. 

The virtual machine has been checked and the problem looks local. Reinstalling Visual Studio Code with deleting launch.json and settings.json configuration files did not help.

Version: 1.46.0 (system setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

notificationsAlerts.ts:38 Error: ModelService: Cannot add model because it already exists!
    at e._createModelData (modelServiceImpl.ts:402)
    at e.createModel (modelServiceImpl.ts:493)
    at new e (suggestEnabledInput.ts:148)
    at d._createInstance (instantiationService.ts:111)
    at d.createInstance (instantiationService.ts:76)
    at e.create (extensionsViewlet.ts:411)
    at i.create (panecomposite.ts:45)
    at e.showComposite (compositePart.ts:215)
    at e.doOpenComposite (compositePart.ts:146)
    at e.openComposite (compositePart.ts:110)
    at e.doOpenViewlet (sidebarPart.ts:275)
    at e.openViewlet (sidebarPart.ts:230)
    at e.openComposite (viewsService.ts:235)
    at e.openView (viewsService.ts:337)
    at e.showPanel (terminalService.ts:483)
    at e.run (terminalActions.ts:219)
    at Object.triggerAndDisposeAction (actions.ts:120)
    at /C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/async file:/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2936

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-java-debug|vsc|0.26.0

</details>

**Comment by roblourens** [comment]
Do you understand this callstack @sbatten? I don't understand why creating the terminal leads to creating the extension viewlet. I thought maybe views were moved around strangely but it looks like you can't really move the extension viewlet. If two extension viewlets were being created that would explain this issue. If there's a valid case for that, it would be easy to work around.

**Comment by Jaroslaw-Brzezinski** [comment]
The terminal remains inaccessible every time and the side panel jumps to extensions as well when trying to start the main class. Both side panels "Extensions" and "Run" stay permanently empty.

**Comment by sbatten** [comment]
I "understand" the call stack but I do not understand how it is possible lol. You could try resetting all view locations in case  there is some bad state, but I don't how that state would exist.

**Comment by roblourens** [comment]
@Jaroslaw-Brzezinski could you run the command "Reset View Locations", reload the window, and see whether that's any better?

**Comment by Jaroslaw-Brzezinski** [comment]
Yeah, that solves the problem. Terminal and extensions are back. Thank you! It made things a lot easier.

**Comment by roblourens** [comment]
Sorry, I'm not sure how this happened, but please let me know if it happens again.
