### ISSUE TITLE
text selected in the output window doesn't populate the search textbox on searching

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#10015]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:
1. Search something make sure that the search textbox has a value
2. Get some text in the output window
3. Select a piece of the text in the output window
4. Press `Ctrl + F` to display the search pane

Expected: the selected text from the output window to populate the search textbox
Actual: a previously search value is in the search textbox

**Comment by Tyriar** [comment]
This is as designed, no plans to change currently.

**Comment by aleksey-bykov** [comment]
why not?

**Comment by Tyriar** [comment]
I actually misread your issue. However, looking at this again, I think it behaves like this now?

**Comment by aleksey-bykov** [comment]
just checked in 

![image](https://cloud.githubusercontent.com/assets/937933/25289024/f8126702-2695-11e7-8738-fdec66e90dae.png)


still doesn't work

**Comment by Tyriar** [comment]
When I tried it worked fine on Windows 10, ctrl+f with a selection always overrode the output find widget? I'll reopen and pass over to @rebornix who should know more about how the find widget works.
