### ISSUE TITLE
Multiple Git status indicators

### ISSUE THREAD

**Issue by mhanuszh** [microsoft/vscode#100117]
Issue Type: <b>Bug</b>

I have multiple git status indicators (Modified, Added, Untracked) in the "Source Control" tab:
![Annotation 2020-06-14 150349](https://user-images.githubusercontent.com/5262962/84594189-dd33d600-ae50-11ea-98a4-55f68c9057a0.png)

Is this normal? If yes, what does these mean?
If not, i'm sorry but I couldn't reproduce it. After reloading it seems to be fixed.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-5600K APU with Radeon(tm) HD Graphics    (4 x 3618)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (1.35GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.1.4
dart-code|Dar|3.11.0
flutter|Dar|3.11.0
gitlens|eam|10.2.2
ev3dev-browser|ev3|1.1.0
php-intellisense|fel|2.3.14
godot-tools|gee|1.1.0
vscode-pull-request-github|Git|0.17.0
todo-tree|Gru|0.0.176
debug-visualizer|hed|1.1.0
vscode-drawio|hed|0.7.0
beautify|Hoo|1.5.0
vscode-peacock|joh|3.7.2
chat|kar|0.35.0
google-fonts|lio|0.0.1
git-graph|mhu|1.24.0
csharp|ms-|1.22.1
python|ms-|2020.5.86806
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
azure-account|ms-|0.8.11
cpptools|ms-|0.28.3
hexeditor|ms-|1.0.1
mono-debug|ms-|0.15.8
typescript-javascript-grammar|ms-|0.0.53
vsliveshare|ms-|1.0.2302
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
vsonline|ms-|1.0.2361
debugger-for-chrome|msj|4.12.8
vetur|oct|0.24.0
vscode-versionlens|pfl|1.0.8
pwabuilder-extension|PWA|0.0.3
quicktype|qui|12.0.46
java|red|0.62.0
rust|rus|0.7.8
html-preview-vscode|tht|0.2.5
pdf|tom|0.6.0
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
quokka-vscode|Wal|1.0.295
vscode-nginx|wil|0.7.2
file-size|zh9|0.1.3
</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
