### ISSUE TITLE
Running 'PowerShell' Formatter runs endlessly

### ISSUE THREAD

**Issue by reuvygroovy** [microsoft/vscode#100153]
![image](https://user-images.githubusercontent.com/1325158/84620715-61359e80-aee1-11ea-9554-732473e62f76.png)

We get this when trying to save PowerShell code. It can run endlessly for minutes or hours. Sometimes after a few minutes it stops, other times is keeps going like the Energizer Bunny . . .

- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:
The behaviour is inconsistent. Many times this works without problems, but again I have seem it resurface many times as well. Sometimes I can just change a line or two (or even a few words) in my code for this to occur. I haven't been able to pinpoint what causes it.

Does this issue occur when all extensions are disabled?: Yes/No
I haven't tried honestly, but it seems that I need the PowerShell extension enabled in order for the formatter to recognize PowerShell code.

**Comment by reuvygroovy** [comment]
??

**Comment by jrieken** [comment]
This is me trying to talk to our triage bot. When powershell formatting hangs than you should have files this issue against them. To double check, when this happens can you format a typescript file?

**Comment by reuvygroovy** [comment]
what do you mean by a typescript file?

**Comment by jrieken** [comment]
a file that contains typescript source code

**Comment by reuvygroovy** [comment]
I didn't try and also don't have one. I mainly got into this issue with PowerShell. Even with the same file/code, the problem sometimes crops up and sometimes dissapears.
