### ISSUE TITLE
Auto indent when typing `{}` in .jsx file

### ISSUE THREAD

**Issue by stephen-hank** [microsoft/vscode#100162]
- VSCode Version:1.46.0
- OS Version: macOS 10.15.4

Steps to Reproduce:

1.In reactjs when i typing '}' in jsx, the row will auto indent. like this

![image](https://user-images.githubusercontent.com/33717252/84624838-b5a64180-af14-11ea-8dd1-a9a1f8250bcc.png)

![image](https://user-images.githubusercontent.com/33717252/84624776-9d362700-af14-11ea-8326-20bf6cbb3f20.png)

I expect no indent.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
May I know if this is causing by any extension you installed?

**Comment by simon-woo** [comment]
> May I know if this is causing by any extension you installed?

I'm sure it's not cause of the extension. because I has uninstall my vscode completely. and reinstall, it still recurrence this bug.

then I tested this bug using several colleague's editors, They have the same problem.

**Comment by simon-woo** [comment]
![image](https://user-images.githubusercontent.com/33717252/84729389-25283980-afc6-11ea-8971-5d8f361ca197.png)

this is a example gif.

**Comment by simon-woo** [comment]
like this.

![image](https://ibb.co/NgRPvRj)

**Comment by stephen-hank** [comment]
need any infos? please help my obsession, thx~

**Comment by alexdima** [comment]
This is caused by the auto indent.

@stephen-hank You can use `"editor.autoIndent": "advanced"` instead of the default `"full"`.

**Comment by stephen-hank** [comment]
> This is caused by the auto indent.
> 
> @stephen-hank You can use `"editor.autoIndent": "advanced"` instead of the default `"full"`.

**Comment by stephen-hank** [comment]
> This is caused by the auto indent.
> 
> @stephen-hank You can use `"editor.autoIndent": "advanced"` instead of the default `"full"`.

thanks! it's works!
