### ISSUE TITLE
Multiline select doesn't start where mousedown occurs

### ISSUE THREAD

**Issue by Montago** [microsoft/vscode#100198]
Issue Type: <b>Bug</b>

When starting a column / multiline select, the selection doesn't start where the mousedown event occurs (like in Visual Studio 2019) 

This makes it really annoying to do multiline selects. 

eg, when editing 5 lines of HTML elements and you want to add a 'class=""' to all of them. In order to do this, you first need to set the carret on the first line and THEN you can select downwards. 

in VS2019 you don't need to set the carret first, you simply start the selection where it should start. 

it should be very easy to fix this, simply set the carret on mousedown.. 

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Does this occur after you run the Command Palette command to reload with all extensions disabled?

**Comment by Montago** [comment]
> Does this occur after you run the Command Palette command to reload with all extensions disabled?

yes, this issue is a flaw in VScode.. not the extensions.

**Comment by alexdima** [comment]
@Montago Column selection can be triggered by a multitude of steps. What precise steps are you doing?

For example, the following steps work for me:
* pressing middle mouse button and dragging
* configuring `editor.multiCursorModifier": "ctrlCmd"` to free up `alt` and then doing alt+click and dragging.

**Comment by Montago** [comment]
> @Montago Column selection can be triggered by a multitude of steps. What precise steps are you doing?
> 
> For example, the following steps work for me:
> 
> * pressing middle mouse button and dragging
> * configuring `editor.multiCursorModifier": "ctrlCmd"` to free up `alt` and then doing alt+click and dragging.

Hi .. I'm using CTRL + ALT + Mouse left 
But it seems that middle-mouse does exactly what i want. 

strange that there's a difference between the two.

**Comment by Montago** [comment]
so you closed this issue because i'm able to solve my problem by using my mouse - but the shift + alt behavior still sucks ??
