### ISSUE TITLE
Explorer: each click results in 2 open editor calls

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#100175]
I tried to debug this for 1h and could not get to the bottom of it. I suspect that the same listener is created twice, but could not verify that.

Anyhow, steps:
* add a `console.log('onDidOpenResource', new Error().stack);` to https://github.com/microsoft/vscode/blob/18cb88ee6d58d2ea6db2b632b66acc65337bd34f/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L428
* click on a file

=> 🐛 the listener is called twice and as such we try to open editors 2 times

**Comment by joaomoreno** [comment]
Let me see what I find out.

**Comment by bpasero** [comment]
i hope this is not some weird debug issue, I would not trust the devtools on this one, listeners are weird...

**Comment by joaomoreno** [comment]
Comes from these two:

https://github.com/microsoft/vscode/blob/da8f44cf08d658ef6f44efb995bc089a0e1998a8/src/vs/base/browser/ui/list/listWidget.ts#L634-L637

We gotta kill that open controller.

**Comment by joaomoreno** [comment]
Make sure this doesn't break: https://github.com/microsoft/vscode/issues/58124

**Comment by isidorn** [comment]
@joaomoreno I see you area already on this. Let me know how I can help. Otherwise once the PR is ready I can make sure all the views are still working as expected: open editors, explorer, debug views.
