### ISSUE TITLE
Keyboard malfunctioning

### ISSUE THREAD

**Issue by SanyaOdare** [microsoft/vscode#100103]
Issue Type: <b>Performance Issue</b>

The enter key of my keyboard works find for any other program but malfunctions and doeasn't work at all whenever I'm using Visual Studio Code.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (10.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    82	 12196	code main
    0	   144	  8624	   window (Welcome - Visual Studio Code)
    0	    81	   652	     extensionHost
    0	    28	 11796	       electron_node serverMain.js 
    0	    37	 13588	       electron_node server.js 
    0	    80	  9572	   shared-process
    0	    14	 11692	   electron-crash-reporter
    0	    69	 12760	   window (Issue Reporter)
    0	    26	 12900	   utility
    0	   155	 13784	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|1.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-rename-tag|for|0.1.3
rest-client|hum|0.24.1
JavaScriptSnippetsStandard|jms|1.7.2
vscode-docker|ms-|1.2.1
python|ms-|2020.5.86806
atom-keybindings|ms-|3.0.8
sublime-keybindings|ms-|4.0.7
debugger-for-chrome|msj|4.12.8
indent-rainbow|ode|7.4.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.9.0
vim|vsc|1.14.5
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by gjsjohnmurray** [comment]
Please use Command Palette to reload with all extensions disabled, then retest.

**Comment by alexdima** [comment]
@SanyaOdare Does this reproduce when disabling all extensions?

**Comment by SanyaOdare** [comment]
I did uninstall and re-install VS Code.
Meanwhile the frustrating experience is still the same.


Yours truly,

Sanya Oluwadare

+234 802 339 4978
13, Emina Crescent,
Off Toyin Street,
Ikeja, Lagos.

**Comment by gjsjohnmurray** [comment]
> I did uninstall and re-install VS Code.

We didn't ask you to do that. We asked you to use the Command Palette (F1) to run the command that reloads your current running instance of VS Code but with all of your 22 extensions disabled.

![image](https://user-images.githubusercontent.com/6726799/85313677-49958180-b4b0-11ea-9dea-2980a6047154.png)

After doing that you should see a notification in the lower right:

![image](https://user-images.githubusercontent.com/6726799/85313737-616d0580-b4b0-11ea-9b7c-23ab0730f41a.png)

DON'T press the Reload button there yet. Instead, try to replicate the issue.

If it still occurs, open your Keyboard Shortcuts (from the gearwheel menu) and enter this into the filter field:

```@source:user```

Are any entries listed? If yes, paste a screenshot here.

**Comment by SanyaOdare** [comment]
Thank you John, I've followed all the instructions listed below.
However, nothing shows up when I opened my Keyboard Shortcuts
(from the gearwheel menu) and entered *@source:user* into the filter field:

The attached screenshot is for your attention.


Yours truly,

Sanya Oluwadare

+234 802 339 4978
13, Emina Crescent,
Off Toyin Street,
Ikeja, Lagos.

**Comment by alexdima** [comment]
@SanyaOdare Screenshots do not appear on github if they are attached to emails. Screenshots only show up if you upload them directly at https://github.com/microsoft/vscode/issues/100103

Can you please confirm that you have disabled all extensions? Can you please confirm that your `keybindings.json` file is empty?

**Comment by SanyaOdare** [comment]
![vscode-keyboard-shortcuts](https://user-images.githubusercontent.com/50111615/85931827-062b8080-b8bf-11ea-891b-1ac903284de3.jpg)

**Comment by SanyaOdare** [comment]
Attention @alexdima alexdima
Please see the screenshot as you requested.

**Comment by alexdima** [comment]
@SanyaOdare Can you please also confirm that you have disabled all extensions?

**Comment by SanyaOdare** [comment]
Yes  @alexdima, I have disabled all extensions.

**Comment by alexdima** [comment]
@SanyaOdare So to recap:
* you have no installed extensions
* you have no user keybindings
* but still, you cannot press Enter

Can you please answer these two follow up questions:

1. Does typing any other letter work for you? 

2. Can you please create the following keybinding in your user `keybindings.json`:
```
{
	"key": "ctrl+e",
	"command": "type",
	"args": {
		"text": "\n"
	},
	"when": "editorTextFocus"
}
```
Does pressing `ctrl+e` insert a new line for you?
