### ISSUE TITLE
vscode-triage-bot response to /extGo needs updating 

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#100143]
- VSCode Version: n/a
- OS Version: n/a

Steps to Reproduce:

1. Be someone the bot respects. 
2. Add '/extGo' to your reply to an issue. 
3. Observe that the comment added by the bot links to https://github.com/microsoft/vscode-go
4. Follow that link and find that the repo has moved. 

Does this issue occur when all extensions are disabled?: Yes/No n/a

**Comment by gjsjohnmurray** [comment]
Example: https://github.com/microsoft/vscode/issues/100139#issuecomment-643827825

**Comment by JacksonKearl** [comment]
Thanks!
