### ISSUE TITLE
Auto Update to latest version sometimes uninstalls the existing version, but it wont install the latest version. It keeps on showing the error somthing like this "some vscode instance is running please close and retry "

### ISSUE THREAD

**Issue by vinodsai-a** [microsoft/vscode#100170]
- VSCode Version:
- OS Version:

Steps to Reproduce:

Auto-updates from vscode will uninstall the current version and it keeps on showing the error something like this "some vscode instance is running please close and retry "

I have to download the latest version every time and install after it is uninstalled

At least user should be given the path of the updater to install after it is uninstalled. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
