### ISSUE TITLE
git fatal error: file is outside directory

### ISSUE THREAD

**Issue by NickLiu635** [microsoft/vscode#100146]
- VSCode Version:1.46.0 (a5d1cc28bb5d)

版本: 1.46.0 (user setup)
提交: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
日期: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

- OS Version: win10 1909 18363.900 
- Language: Chinese

log:
git.stage 1
git.stage.scmResources 1
**>** git add -A -- c:\Users\lyj\Desktop\CODE\xxxxx\activity.html
fatal: c:\Users\lyj\Desktop\CODE\xxxxx\activity.html: 'c:\Users\lyj\Desktop\CODE\xxxxx\activity.html' is outside repository

git config
[core]
repositoryformatversion = 0
filemode = false
bare = false
logallrefupdates = true
symlinks = false
ignorecase = true

commands
`
C:\Users\lyj\Desktop\CODE\xxxxx>git add -A -- c:\Users\lyj\Desktop\CODE\xxxxx\activity.html
fatal: c:\Users\lyj\Desktop\CODE\xxxxx\activity.html: 'c:\Users\lyj\Desktop\CODE\xxxxx\activity.html' is outside repository

C:\Users\lyj\Desktop\CODE\xxxxx>git add -A -- **C**:\Users\lyj\Desktop\CODE\xxxxx\activity.html

C:\Users\lyj\Desktop\CODE\xxxxx>
`

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/duplicate

Other people who have reported this resolved it by updating their Git version.
