### ISSUE TITLE
Add setting to disable debug from showing up in package.json

### ISSUE THREAD

**Issue by serenedu** [microsoft/vscode#100104]
After upgrading to V1.46.0, this showed up, I asked "how to disable debug in package.json" in this [stackoverflow question](https://stackoverflow.com/questions/62358131/how-to-disable-debug-from-showing-in-package-json), the setting seems to be non-existent.
![image](https://user-images.githubusercontent.com/28700378/84584309-3ee64700-ae35-11ea-8c4d-af0f7ae09436.png)

**Comment by gjsjohnmurray** [comment]
Just a guess - does `npm.scriptCodeLens.enable` affect this?

**Comment by ArturoDent** [comment]
Please see your SO question, I answered it there: https://stackoverflow.com/a/62368407/836330

**Comment by gjsjohnmurray** [comment]
@ArturoDent thanks for the correction. I found reference to that setting in https://github.com/microsoft/vscode/issues/51613#issuecomment-406217286 but I guess it got moved.

**Comment by serenedu** [comment]
`"debug.javascript.codelens.npmScripts": "never"` did the trick ,thank you all! @ArturoDent @gjsjohnmurray
