### ISSUE TITLE
Provide a light high contrast theme

### ISSUE THREAD

**Issue by saltukkos** [microsoft/vscode#100119]
- VSCode Version:  1.45.1
- OS Version: Windows 10.0.18363

Steps to Reproduce:

1. Enable High Contrast mode in Windows settings
2. Choose a "High Contrast White" theme 
3. Visual studio code shows High contrast black theme, ignoring this setting
![image](https://user-images.githubusercontent.com/13440397/84595362-b04be700-ae81-11ea-92c0-817eef01e1a9.png)

**Comment by aeschli** [comment]
We only have a dark high contrast theme/
