### ISSUE TITLE
Terminal window confusing 1:cmd.exe 2:cmd.exe

### ISSUE THREAD

**Issue by vidhya03** [Microsoft/vscode#10018]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

I am running angular2 projects. 
I am in need to run two command ,  npm start, and npm run tsc:w

Steps to Reproduce:
 a. I used code in built terminal ctrl+`

![vscode-terminal](https://cloud.githubusercontent.com/assets/534679/17295004/b0475d62-5817-11e6-834e-558674ebeec8.png)

b. It is confusing if i open more than one cmd

![vscode-terminal-multiple](https://cloud.githubusercontent.com/assets/534679/17295089/0b89cade-5818-11e6-9e4e-487970f2388e.png)

Please show as tab with title of running command. instead of 1:cmd, 2:cmd

**Comment by Tyriar** [comment]
As far as I'm aware, on Windows there is no way of pulling the command being run from cmd, at least using the lib we're using. Tabs were planned originally but scrapped as they make the UI feel a lot heavier and could be confusing (panel tabs, editor tabs, terminal tabs?).

Going to close this in favor of https://github.com/Microsoft/vscode/issues/10023

**Comment by vidhya03** [comment]
Ok. I am looking forward to this feature  #10023 at least
