### ISSUE TITLE
Cursor length in vscode terminal is not normal (cursor is too long)

### ISSUE THREAD

**Issue by mfaridzia** [microsoft/vscode#100185]
- VSCode Version: 1.46
- OS Version: Linux Mint 19 Tara
Steps to Reproduce:

1. Open vscode
2. Settings
3. Change the type of cursor in the terminal

This is the settings.json file

Settings.json

{
    "workbench.colorTheme": "Plastic",
    "workbench.iconTheme": "vscode-icons",
    "explorer.confirmDelete": false,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "editor.tabSize": 2,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.lineHeight": 30,
    "window.zoomLevel": 0,
    "editor.formatOnPaste": false,
    "editor.formatOnType": false,
    "editor.fontFamily": "Fira Code, 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
    "editor.formatOnSave": false,
    "editor.fontLigatures": true,
    "prettier.requireConfig": true,
    "terminal.integrated.lineHeight": 30,
    "terminal.integrated.shell.linux": "/bin/bash",
    "terminal.integrated.rendererType": "dom",
    "terminal.integrated.cursorStyle": "underline"
}

After setting the cursor, the cursor is still long

[This is the cursor image on the vscode terminal](https://imgur.com/a/4MjoPJK)

**Comment by Tyriar** [comment]
Can you share your settings.json file? Also try switching to the DOM renderer:

```
"terminal.integrated.rendererType": "dom"
```

**Comment by mfaridzia** [comment]
I tried to switch to dom mode before, but it's still the same.

Settings.json

{
    "workbench.colorTheme": "Plastic",
    "workbench.iconTheme": "vscode-icons",
    "explorer.confirmDelete": false,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "editor.tabSize": 2,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.lineHeight": 30,
    "window.zoomLevel": 0,
    "editor.formatOnPaste": false,
    "editor.formatOnType": false,
    "editor.fontFamily": "Fira Code, 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
    "editor.formatOnSave": false,
    "editor.fontLigatures": true,
    "prettier.requireConfig": true,
    "terminal.integrated.lineHeight": 30,
    "terminal.integrated.shell.linux": "/bin/bash",
    "terminal.integrated.rendererType": "dom",
    "terminal.integrated.cursorStyle": "underline"
}

**Comment by Tyriar** [comment]
Remove this: `"terminal.integrated.lineHeight": 30`

![image](https://user-images.githubusercontent.com/2193314/84664442-6986dd00-aed3-11ea-999a-86806dc93aba.png)

**Comment by mfaridzia** [comment]
Yay, it worked, thank you very much.
