### ISSUE TITLE
 Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#100157]
Issue Id: <b>c2d9874a-f39e-c4d7-7961-ecfd4ef17e86</b><br /><br />*Versions* <br />- 1.46.0<br />-  b1ef2bf05f90dd0e6438782411ab84756f97d8f1<br />-  9f89da69154ac6c99dfa7c82986e2df95b7bbe0b<br />-  24ebced0aba496bd7bdacd432aa9e877181bcf63<br />*Stack* <br />TypeError: Cannot read property 'indexOf' of null<br />[/vs/workbench/api/browser/mainThreadStatusBar.ts#35:20 (apply)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/workbench/api/browser/mainThreadStatusBar.ts#L35:20 (apply))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#402:16 (_doInvokeHandler)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L402:16 (_doInvokeHandler))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#387:31 (_invokeHandler)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L387:31 (_invokeHandler))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#303:18 (_receiveRequest)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L303:18 (_receiveRequest))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#239:9 (_receiveOneMessage)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L239:9 (_receiveOneMessage))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#105:41 (call)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L105:41 (call))<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/base/parts/ipc/common/ipc.net.ts#453:18 (fire)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/parts/ipc/common/ipc.net.ts#L453:18 (fire))<br />[/vs/base/parts/ipc/common/ipc.net.ts#733:20 (_receiveMessage)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/parts/ipc/common/ipc.net.ts#L733:20 (_receiveMessage))<br />[/vs/base/parts/ipc/common/ipc.net.ts#592:72 (call)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/parts/ipc/common/ipc.net.ts#L592:72 (call))<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/base/parts/ipc/common/ipc.net.ts#239:20 (acceptChunk)](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/parts/ipc/common/ipc.net.ts#L239:20 (acceptChunk))<br />[/vs/base/parts/ipc/common/ipc.net.ts#200:50](https://github.com/microsoft/vscode/blob/a5d1cc28bb5da32ec67e86cc50f84c67cc690321/src/vs/base/parts/ipc/common/ipc.net.ts#L200:50)<br />    at Socket.t (out/vs/workbench/workbe<br />

**Comment by bpasero** [comment]
While this probably fixes the issue, isn't there a typing issue that `text` can be `null`? Feel free to move back to me if you have not touched that part recently.

**Comment by isidorn** [comment]
@bpasero yeah there is a typing issue, and yes I did not touch the typgins there. Assigning also to you. The issue is that probably some extension is not respecting the contract and we are not validating input

**Comment by bpasero** [comment]
Actually the type is proper for extensions, someone must have really disabled types to sneak in `null`.
