### ISSUE TITLE
Terminal not showing text

### ISSUE THREAD

**Issue by ersuman** [microsoft/vscode#100178]
Issue Type: <b>Bug</b>

VS Code integrated terminal showing blank. Also some formatting style changed => angular modules: imports and declarations used to show at different color but now showing in the same color as keywords like NgModule

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|15.67GB (3.01GB free)|
|Process Argv|--folder-uri file:///d%3A/Dev/merchantrademoney/MerchantradeMoney.Admin/src|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.11
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.12
auto-close-tag|for|0.5.7
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.3
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.2
debugger-for-chrome|msj|4.12.8
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
angular-console|nrw|12.0.0
material-icon-theme|PKi|4.1.0
typescript-hero|rbb|3.0.0
code-settings-sync|Sha|3.4.3
autoimport|ste|1.5.3
move-ts|str|1.12.0
highlight-matching-tag|vin|0.9.9

(5 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot of [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal

**Comment by ersuman** [comment]
![vscode formatting issue](https://user-images.githubusercontent.com/23517648/84925375-839a0880-b0e9-11ea-8dcb-854c29d87242.gif)

I don't know how but Terminal is showing text now, I couldn't replicate that issue now, but you can see the formatting issue in the attached gif. VS Code shows accurate formatting (green text) at loading time but after few seconds it changes to color same as keywords like NgModule (blue). NOTE: I'm using dracula theme.

**Comment by Tyriar** [comment]
That text color looks like semantic tokens, it's probably as designed but you can create a new issue if you want.
