### ISSUE TITLE
Regexp freezes VS Code when code has emoji

### ISSUE THREAD

**Issue by 0x00000ED** [microsoft/vscode#100134]
- VSCode Version: 1.46.0 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open editor.
2. Create new file.
3. Press win+; select any emoji.
4. Open search panel and select regexp mode.
5. Type /* in search line.
6. RIP.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
It's interesting. Freeze looks like result of #30874
`.*` will match every string (because still in "non-multiline" search mode)
`/` will match `/` characters only (even in RegEx mode)

Not sure why, but `/*` starts to match every character and even `\/*` doesn't help

**Comment by IllusionMH** [comment]
Problem here that `/*` or even `a*` will match empty string after each character.
As workaround `/+` can be used to avoid ton of zero-length matches.

_(Initial response removed because it had wrong conclusions.)_
