### ISSUE TITLE
"Stage Changes" button in Source Control window uses wrong casing for drive letter

### ISSUE THREAD

**Issue by cynicaloptimist** [microsoft/vscode#100161]
- VSCode Version: 1.47.0-insider
- OS Version: Windows 10 Pro 1909

Steps to Reproduce:

1. Use the Source Control sidebar to initialize a git repository in an empty folder
2. Create a file (like "test.txt")
3. Click the inline "Stage Changes" button on the sidebar by the new file
4. See this error:
```
[Window Title]
Visual Studio Code - Insiders

[Content]
Git: fatal: c:\Users\cynic\Documents\src\vs-code-drive-letter-repro\test.txt: 'c:\Users\cynic\Documents\src\vs-code-drive-letter-repro\test.txt' is outside repository

[Open Git Log] [Cancel]
```

Git Log contents:
```
> git ls-tree -l HEAD -- C:\Users\cynic\Documents\src\vs-code-drive-letter-repro\test.txt
fatal: Not a valid object name HEAD
> git ls-tree -l HEAD -- C:\Users\cynic\Documents\src\vs-code-drive-letter-repro\test.txt
git.stage 1
git.stage.scmResources 1
> git add -A -- c:\Users\cynic\Documents\src\vs-code-drive-letter-repro\test.txt
fatal: Not a valid object name HEAD
fatal: c:\Users\cynic\Documents\src\vs-code-drive-letter-repro\test.txt: 'c:\Users\cynic\Documents\src\vs-code-drive-letter-repro\test.txt' is outside repository
> git ls-tree -l HEAD -- C:\Users\cynic\Documents\src\vs-code-drive-letter-repro\test.txt
fatal: Not a valid object name HEAD
```

The command `git add -A -- c:\Users\cynic\Documents\src\vs-code-drive-letter-repro\test.txt` fails if rerun on the command line. It succeeds if I correct the casing of `c:\` to uppercase.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
What Git version are you using? Several other recent issues have reported the "outside repository" problem being resolved by updating their local Git.

**Comment by cynicaloptimist** [comment]
Updating my local git installation fixed this, thanks very much for the advice!

**Comment by joaomoreno** [comment]
Thanks @gjsjohnmurray for being so on top of this.
