### ISSUE TITLE
files.exclude .js.map

### ISSUE THREAD

**Issue by tonyeung** [microsoft/vscode#100137]
- VSCode Version: VSO
- OS Version: VSO

Steps to Reproduce:
```
{
    "files.exclude": {
        "**/*.js": { "when": "$(basename).ts" },
        "**/*.map": { "when": "$(basename).ts" }
    }
}
```
When compiling index.ts the .js.map file doesn't get hidden unless you remove the .ts from `$(basename)`. See https://stackoverflow.com/questions/31587949/hide-js-map-files-in-visual-studio-code for more examples of people recommending the workaround. 

Does this issue occur when all extensions are disabled?: Yes/No
VSO

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
