### ISSUE TITLE
Custom registerDocumentLinkProvider disables built in ones

### ISSUE THREAD

**Issue by matepek** [microsoft/vscode#100106]
Hello, 
My extension registers a [link provider](https://github.com/matepek/vscode-catch2-test-adapter/blob/5eac807f03caeb656a8c0369cb0c33118967ae7e/src/ExecutableConfig.ts#L59).
In [this](https://github.com/matepek/vscode-catch2-test-adapter/issues/207) issue a user of mine complains about that with my extension the link recognition doesn't work. 

Is that normal or is it a vscode bug and both the built in and my DocumentLinkProvider should be active at the same time?

- VSCode Version: 1.45.1
- OS Version: Windows

Steps to Reproduce:

1. Install [cmake-tools](https://github.com/microsoft/vscode-cmake-tools)
2. Install [TestMate C++](https://marketplace.visualstudio.com/items?itemName=matepek.vscode-catch2-test-adapter) v3.2.6
3. Clone [this repo](https://github.com/matepek/vscode-catch2-test-adapter)
4. `cd <new_repo>/test/cpp`
5. `code .`
6. cmake-tools will ask: "Would you like to configure project?" Answer: Yes
7. Open `catch2v3_test1.cpp` and make a compilation error
8. Using activity bar select cmake-tools.
9. Click on the icon next to "catch2v3_test1[catch2v3_test1.exe]"

At the output I can see:
```
[build] FAILED: CMakeFiles/catch2v3_test1.dir/catch2v3_test1.cpp.o 
[build] /usr/bin/clang++  -DCATCH_CONFIG_ENABLE_BENCHMARKING -I_deps/catch2v3test-src/src/catch2/.. -w -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=gnu++14 -MD -MT CMakeFiles/catch2v3_test1.dir/catch2v3_test1.cpp.o -MF CMakeFiles/catch2v3_test1.dir/catch2v3_test1.cpp.o.d -o CMakeFiles/catch2v3_test1.dir/catch2v3_test1.cpp.o -c ../catch2v3_test1.cpp
[build] ../catch2v3_test1.cpp:7:3: error: use of undeclared identifier 'x'
[build]   x;
[build]   ^
[build] 1 error generated.
```
But the file is not a link.

Does this issue occur when all extensions are disabled?: Not applicable

**Comment by jrieken** [comment]
Custom link provider do not disable the build in once. However, when the built in and a custom provider report a link at the same location than the custom provider takes precedence (that one link)

So, please craft a repo that shows what you are seeing

**Comment by matepek** [comment]
Repro:

1. Install [cmake-tools](https://github.com/microsoft/vscode-cmake-tools)
2. Install [TestMate C++](https://marketplace.visualstudio.com/items?itemName=matepek.vscode-catch2-test-adapter)
3. Clone [this repo](https://github.com/matepek/vscode-catch2-test-adapter)
4. `cd <new_repo>/test/cpp`
5. `code .`
6. cmake-tools will ask: "Would you like to configure project?" Answer: Yes
7. Open `catch2v3_test1.cpp` and make a compilation error
8. Using activity bar select cmake-tools.
9. Click on the icon next to "catch2v3_test1[catch2v3_test1.exe]"

At the output I can see:
```
[build] FAILED: CMakeFiles/catch2v3_test1.dir/catch2v3_test1.cpp.o 
[build] /usr/bin/clang++  -DCATCH_CONFIG_ENABLE_BENCHMARKING -I_deps/catch2v3test-src/src/catch2/.. -w -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=gnu++14 -MD -MT CMakeFiles/catch2v3_test1.dir/catch2v3_test1.cpp.o -MF CMakeFiles/catch2v3_test1.dir/catch2v3_test1.cpp.o.d -o CMakeFiles/catch2v3_test1.dir/catch2v3_test1.cpp.o -c ../catch2v3_test1.cpp
[build] ../catch2v3_test1.cpp:7:3: error: use of undeclared identifier 'x'
[build]   x;
[build]   ^
[build] 1 error generated.
```
But the file is not a link.

Actually this is the situation on macos without TestMate extension. But I believe on windows it should be recognised as a link and that is the issue about.

Let me know if something is not clear.

**Comment by jrieken** [comment]
minimal repro please

**Comment by matepek** [comment]
This is almost minimal. 😅
Number 7 is the extra step.

**Comment by jrieken** [comment]
Really? So it really requires for instance cmake-tools and won't reproduce without?

**Comment by matepek** [comment]
I don't know in what other cases it does not work. Maybe if I learned and understood what's happening in vscode codebase I could give a simpler one. You don't expect me to do that, right?

**Comment by jrieken** [comment]
I know that it works because we ship with multiple links providers. So, I expect you to provide a simple extension sample that shows where it doesn't work. Simple cannot mean install tool X and Y because vscode doesn't launch external tools during link detection.

**Comment by matepek** [comment]
I'm sorry but I'm a but busy right now.

If you are right, I just close the issue at my extension's github repo because I checked that I don't override the link, so it cannot be me.

**Comment by jrieken** [comment]
not actionable

**Comment by matepek** [comment]
disagree
