### ISSUE TITLE
"Activating extension 'vscode.github' failed: Git model not found." when Git is disabled

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#100183]
I have `"git.enabled": false` in my VS Code user settings, and this causes the built-in GitHub extension to fail to activate:

> Activating extension 'vscode.github' failed: Git model not found.

For the main VS Code window this is generally silent (other than writing into the dev console), however in the extension host this triggers a `showErrorMessage` so it's quite annoying when working on extensions.

If this extension doesn't function with Git disabled, it should probably fail silently rather than triggering errors.

**Comment by joaomoreno** [comment]
Funny, just pushed a commit which fixes this: https://github.com/microsoft/vscode/commit/208d556b1df23e5602b6539d7df0da5246d363c0

**Comment by DanTup** [comment]
@joaomoreno I don't see the notification in the extension host anymore, but I do get this in the debug console for the main VS Code extension (the one editing the extension code, not running it):

<img width="1308" alt="Screenshot 2020-06-22 at 11 07 40" src="https://user-images.githubusercontent.com/1078012/85275768-bab94280-b478-11ea-82c1-d39462f76130.png">

This is still very annoying - it makes it hard for me to see my own errors/warnings being printed. I don't need a big message on every debug session to tell me I've disabled Git :-)
