### ISSUE TITLE
menu key applied to the wrong item in explorer

### ISSUE THREAD

**Issue by glacjay** [microsoft/vscode#100151]
Issue Type: <b>Bug</b>

- ctrl-shift-e to switch input focus to the explorer panel
- select a file
- press menu key
- another item's context menu is shown

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (17.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
theme-verdandi|be5|2.0.1
vscode-custom-css|be5|3.0.9
markdown-mermaid|bie|1.5.1
better-toml|bun|0.3.2
thief-book|C-T|0.0.9
vscode-autohotkey-plus|cwe|2.4.1
autoit|Dam|1.0.5
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
xml|Dot|2.5.0
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.0.0
shell-format|fox|7.0.1
toml-formatter|ice|0.0.3
sublime-babel-vscode|jos|0.2.10
vscode-language-pack-zh-hans|MS-|1.46.3
node-debug2|ms-|1.42.4
snippet-creator|nik|0.0.5
java|red|0.62.0
rust|rus|0.7.8
trailing-spaces|sha|0.3.1
language-stylus|sys|1.11.0
stylus-supremacy|thi|2.14.5
html-preview-vscode|tht|0.2.5
ghosttext|tok|1.1.0
vim|vsc|1.14.5
markdown-auto-toc|wib|0.3.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.0.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. This works fine fine for me. 
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by glacjay** [comment]
@isidorn just tried the insiders (freshly downloaded one) and the same happened :-(

**Comment by isidorn** [comment]
@glacjay can you please post a picture, or a short gif? What is the menu key?

**Comment by glacjay** [comment]
![output](https://user-images.githubusercontent.com/292719/84666058-32581080-af53-11ea-931b-747d0c5bd6d4.gif)

**Comment by glacjay** [comment]
![图片](https://user-images.githubusercontent.com/292719/84666491-b90ced80-af53-11ea-8119-d4b9c4b9164f.png)

This is the menu key, and it's usually being used to call out the context menu, just like the right mouse button, but without a mouse.

**Comment by isidorn** [comment]
Thanks for providing more details. However this works just fine for me on Mac and Win.
However I do not have the menu key so I triggered the context menu via Ctrl+Shift+F10.

For know let's keep this issue opened and we see if more people hit it.

**Comment by glacjay** [comment]
shift-f10 works fine for me, so I think I must use this instead for now.

Thank you anyway. Waiting for your good news.

**Comment by gjsjohnmurray** [comment]
/confirm

Screen recording from stable after reloading with all extensions disabled and enabling screencast mode:
![junk](https://user-images.githubusercontent.com/6726799/84784393-26675f80-afe2-11ea-9f3d-568b46c2a494.gif)

Compare the first menu that appears (right-click on filename) with the second one (after pressing ContextMenu key).

Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
@gjsjohnmurray thanks for confirming.
@joaomoreno why would the tree handle the context menu differently based on the trigger key? I once case trigger is shift + F10, in another trigger is the `menu` key.

**Comment by joaomoreno** [comment]
It really shouldn't since both come from: https://github.com/microsoft/vscode/blob/86e6f8121ffec29243881374cc71352042c39231/src/vs/base/browser/ui/list/listWidget.ts#L1131-L1131

You can start debugging there.

**Comment by thomazmoura** [comment]
I'm having the same issue and it was driving me crazy (I'm a VIM user and this completely breaking my work flow - since I could not create a simple folder any longer without needing the mouse). Thanks for shift+F10 suggestion, it really saved me (I've managed to map "ctrl+contextmenu" to "editor.action.showContextMenu" as a workaround).

I've noticed two interesting things with this, though:

1. Trying to bind to "contextmenu" is pointless - it continues having the same behaviour. Mapping to "ctrl+contextmenu" worked as intended, though. __So I believe there is something on the "contextmenu" by itself that is overriding any custom mapping__.

2. The "contextmenu" key seems to get fixed on the last selected item (the one that was selected when you hit "ctrl+shift+e" or the last you clicked). __It's like when you move with the arrow keys the selected item is not updated correctly__.

So, my wild guess is: the arrow keys are not updating the selected items properly, and hitting the "contextmenu" key does not use the "editor.action.showContextMenu" but another similar function that considers only the "properly selected" item.

**Comment by guitexa** [comment]
I had to change my `keybindings.json` and add this shortcut to use `contextmenu` with `ctrl`

```json
{
    "key": "ctrl + contextmenu",
    "command": "editor.action.showContextMenu",
    "when": "textInputFocus"
 }
```

**Comment by glacjay** [comment]
@isidorn this is not vscode's problem?

**Comment by dmondev** [comment]
This is happening for me as well in:

VS Code 1.50.1
Windows 10.0.18363

Shift + F10 works fine.

**Comment by isidorn** [comment]
Adding verified since I just verified a potential duplicate https://github.com/microsoft/vscode/issues/116083

Users please let me know if you still see this.
