### ISSUE TITLE
vs code slowness

### ISSUE THREAD

**Issue by kesavamuthu** [microsoft/vscode#100189]
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-6f02.extHost.cpuprofile.txt`
-`prof-6f02.main.cpuprofile.txt`
-`prof-6f02.renderer.cpuprofile.txt`
[prof-6f02.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/4780158/prof-6f02.extHost.cpuprofile.txt)
[prof-6f02.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/4780159/prof-6f02.main.cpuprofile.txt)
[prof-6f02.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/4780161/prof-6f02.renderer.cpuprofile.txt)
[cod.txt](https://github.com/microsoft/vscode/files/4780228/cod.txt)

**Comment by kesavamuthu** [comment]
Sorry, this issue already reported in #100120 it's breaking the chain I think. I am new to report issues.

**Comment by eamodio** [comment]
Can you provide  more details as to when/how you are seeing slowness?

**Comment by kesavamuthu** [comment]
Actually It got closed. I duplicated the issue  #22087 sorry I am a newbie. Also, #22087 denoted slowness because of AV software that's ok. Can I have any solution so that I can do my work on vs code?
