### ISSUE TITLE
github authentication / microsoft authentication erro

### ISSUE THREAD

**Issue by QingFengpoor** [microsoft/vscode#100122]
- VSCode Version: 1.46.0
- OS Version: Linux x64 5.4.0-37-generic
Steps to Reproduce:

1. Have no idea about how the bug come up. In OUTPUT, the github authentication and microsoft authentication output the same error:   
[Error  - 14:01:49.709] Getting token failed: Error: The name org.freedesktop.secrets was not provided by any .service files  
[Error  - 14:02:19.727] Getting token failed: Error: The name org.freedesktop.secrets was not provided by any .service files  
[Error  - 14:02:49.744] Getting token failed: Error: The name org.freedesktop.secrets was not provided by any .service files  
[Error  - 14:03:19.762] Getting token failed: Error: The name org.freedesktop.secrets was not provided by any .service files  
[Error  - 14:03:49.778] Getting token failed: Error: The name org.freedesktop.secrets was not provided by any .service files  
[Error  - 14:04:19.792] Getting token failed: Error: The name org.freedesktop.secrets was not provided by any .service files  
[Error  - 14:04:49.808] Getting token failed: Error: The name org.freedesktop.secrets was not provided by any .service files  
[Error  - 14:05:19.826] Getting token failed: Error: The name org.freedesktop.secrets was not provided by any .service files  

and I don’t know if it’s because I turned on Sync.

Does this issue occur when all extensions are disabled?: Yes

expecting a reply， thanks.
![Screenshot_20200614_220540](https://user-images.githubusercontent.com/24737114/84595684-d70f1b00-ae8b-11ea-8ec7-443477d654f9.png)

**Comment by RMacfarlane** [comment]
@QingFengpoor Can you try installing `gnome-keyring`? `sudo apt-get install gnome-keyring`
