### ISSUE TITLE
Make `resources/linux/bin/code.sh` POSIX-compliant to remove `bash` dependency

### ISSUE THREAD

**Issue by VoidNoire** [microsoft/vscode#100144]
I'd like `resources/linux/bin/code.sh` to be POSIX-compliant to remove the dependency on `bash`.

**Comment by joaomoreno** [comment]
Why? Does this actually cause a problem?

**Comment by VoidNoire** [comment]
I'm unable to start VS Code on my system which doesn't have `bash`. The linked PR allows me to start it because I have `dash` instead.

**Comment by JacksonKearl** [comment]
Verified by review.
