### ISSUE TITLE
Restarting a dynamic debug session with the same name as a regular configuration reads settings from launch.json

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#100115]
I've had reports that clicking the "Restart" button in the debug toolbar (when restart is handled by VS Code, and not the DA) starts the new session using values from `launch.json` even if the session was a dynamically created session.

I was able to repro this with a copy of MockDebug:

https://github.com/DanTup/vscode-repro-debug-restart
https://github.com/DanTup/vscode-repro-debug-restart/commit/7ec8353495c62455e500142a722cf3e7236f38a4

This adds a command called "MockDebug: Run without args" that starts a debug session dynamically:

```ts
vscode.debug.startDebugging(
	vscode.workspace.workspaceFolders![0],
	{
		name: "Mock",
		request: "launch",
		type: "mock",
		program: '${file}',
	},
);
```

There are no `args` in this launch config.

Opening the `sample_project` folder and putting a breakpoint in the `.md` file, then invoking the command causes the DA prints the `args` during `launchRequest`:

```
DA got args: undefined
```

If you hit the Restart button, it'll then print:

```
DA got args: from-launch.json
```

This is because it's started a new session using the launch config from `launch.json`, even though the `launch.json` was never involved in the session that was running.

This is undesirable - the launch.config should not be re-read. It seems like there is code to do this deliberately, but it's not clear why:

https://github.com/microsoft/vscode/blob/af9d0d5df2679d6dd0c2fd9f99d69e4c79376f8b/src/vs/workbench/contrib/debug/browser/debugService.ts#L657

I guess this didn't consider dynamically-launched sessions and assumed they were always from launch.json (however honestly, I wouldn't expect it to re-read on a restart of a session from launch.config either.. I would expect a restart to be exactly as it was, since that's the only behaviour you could get from a DA-provided restart anyway).

@weinand @isidorn this may be slightly related to https://github.com/microsoft/vscode/issues/21316.

**Comment by isidorn** [comment]
I agree that this is an issue. Let me just verify something: this only happens if the dynamic configuration and a written configuration in `launch.json` have the same `name`?

**Comment by DanTup** [comment]
> this only happens if the dynamic configuration and a written configuration in launch.json have the same name?

In my real extension I don't have a name on the dynamic config (though it's possible if it goes through resolve, that it might be added on).

As a workaround I was considering making up a random name, but since that may show up in the UI (eg. the debug toolbar when the are multiple sessions), having a random name wouldn't be ideal.

TBH, even if I launched from launch.json and then modified it - I'm not sure I'd expect Restart to pick up the changes even in that case (especially as this would be inconsistent if the DA handles restart itself, as it definitely won't be reading new values from launch.json - it doesn't even know that's where they came from).

**Comment by isidorn** [comment]
@dantup if you do not set a `name` on your dynamic configuration then the call to `getConfiguration` [here](https://github.com/microsoft/vscode/blob/9bebaefc7bfca937721e7ce3d5fcfde8745e7727/src/vs/workbench/contrib/debug/browser/debugService.ts#L662) should return `undefined` and thus nothing should be read. Unleass you also have a configuration in `launch.json` which does not have a name.
Can you put a breakpoint at a pointer i provided and investigate more? Thanks

**Comment by DanTup** [comment]
I checked, and it was as a I suggested above:

> though it's possible if it goes through resolve, that it might be added on

When I launch the dynamic debug session, it goes through my `resolve` method, which populates some default values if they're not sent, including the name:

```
if (!debugConfig.name) {
	if (isFlutter && debugConfig.deviceId) {
		debugConfig.name = `Flutter (${debugConfig.deviceId})`;
	} else if (isFlutter && device) {
		debugConfig.name = `Flutter (${deviceManager ? deviceManager.labelForDevice(device) : device.name})`;
	} else if (isFlutter) {
		debugConfig.name = "Flutter";
	} else {
		debugConfig.name = "Dart";
	}
}
```

So this will pick up the name "Dart" here, which would then match what's in `launch.json`. We add the default name so if you run multiple sessions (for ex. a Dart backend, and a Flutter frontend) you can tell them apart easily in the debug UIs.

**Comment by DanTup** [comment]
> As for re-reading the config on restart - this was already discussed at lenght in a closed issue, you can search for it if you are interested in more details why we do this.

There are 294 results for "restart launch.json" - do you happen to remember anything that would help narrow it down? 😄

**Comment by DanTup** [comment]
The only note I could find was this:

https://github.com/microsoft/vscode/issues/47021#issuecomment-381129386

> The use case that triggered this was that a user edited a launch config and then aways restarted the debug session to pick up those changes.

However I still think this is questionable, because if a DA handles restart itself, it would not reload this config - so the behaviour will be inconsistent between DAs that do/don't handle their own restart.

That aside, could dynamic sessions have some flag so they are excluded from the reload? I think forcing dynamic sessions to have some random name to avoid overlapping with `launch.json` is not ideal.

**Comment by isidorn** [comment]
Ok, so the gist is: when there is a config with the same name in the launch.json it gets read. As a workaround I suggest you simply give a different name to the dynamic launch configuration. For example "Dart " with a space at the end.
We can look into fixing this issue on our end in the future when we introduce a distinction between dynamic configuraitons and regular ones - the distinciton which we currently do not have.

As for older discussions yeah that issue captures it quite well. Feel free to comment there.

**Comment by DanTup** [comment]
> As a workaround I suggest you simply give a different name to the dynamic launch configuration. For example "Dart " with a space at the end.

Yeah, that sounds better than being random, I'll do that in the meantime. Thanks!

**Comment by isidorn** [comment]
Since there is a workaround for this I wil lclose this as out of scope.
