### ISSUE TITLE
macOS Touchbar support choice between Editing vs Debug Session Touchbars

### ISSUE THREAD

**Issue by sageata** [microsoft/vscode#100164]
I am working on a macOS with Dart and Flutter on a Mac Book with touch bar.

The annoying part is that whenever I enter a debug session the Touch Bar enters the debug session mode and replaces all my editing shortcuts that are found on my touch bar with the debug tools.

Is it possible to customize which Touch Bar to show, either Debug Session or the Editing one?

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by sageata** [comment]
Thanks for the prompt reply!

**Comment by isidorn** [comment]
Good point, I was unaware of that setting. Thus closing since there is a workaround
