### ISSUE TITLE
Built-in CSS/SCSS formatting

### ISSUE THREAD

**Issue by mariusa** [microsoft/vscode#100105]
vscode has built-in formatting for web development (HTML, JS...), but no CSS & SCSS

Please add built-in CSS/SCSS formatting support, so we don't have to install a 3rd party extension just for this.

Similar old issue, which was closed: #28836

Thanks

**Comment by aeschli** [comment]
We have still no plans to bundle or provide a css/scss formatter.
See https://github.com/microsoft/vscode/issues/19166#issuecomment-409928738

**Comment by yw662** [comment]
Actually why not just use the same formatter for formatting <style> inside HTML to format standalone CSS files ?

It is as simple as, add <style> at the first line, let HTML formatter format it, remove <style> and remove the indent.

It is indeed rediculous that you already have a CSS formatter in HTML formatter and saying you have no CSS formatter.
