### ISSUE TITLE
TypeScript syntax hightlighting color Bug: new instance without parenthesis

### ISSUE THREAD

**Issue by Zorgatone** [Microsoft/vscode#10017]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. TypeScript Code:
```TypeScript
// Note: `new Date` without parenthesis (`new Date()`)
ctrl.filter("dateFilter", () => (input: mycivis.IAll[], date: Date = new Date) => input.filter((value, index, array) => {
    let date2 = value.date || (value.day) ? moment(`${value.day} ${value.time}`, "YYYY-MM-DD HH:mm").toDate() : next_wday(value.wday);

    return moment(date).format("DD/MMM/YYYY") === moment(date2).format("DD/MMM/YYYY");
}));
```

This is what I see (syntax hightlight with wrong colors):

![schermata 2016-08-01 alle 14 44 48](https://cloud.githubusercontent.com/assets/2664036/17294283/24a677b4-57f6-11e6-977e-14305875015c.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#230
