### ISSUE TITLE
the spinning bar (progress indicator) doesn't appear anymore after a running task gets terminated

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#10016]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. Start an task
2. Observe a spinning progress indicator in the status bar
3. Terminate the task before it finishes
4. Start the task again

Expected: so see the spinning progress indicator again
Actual: the indicator is not displayed anymore

**Comment by dbaeumer** [comment]
@aleksey-bykov how do you stop the task. Using the terminate task command.

**Comment by aleksey-bykov** [comment]
Yes, by clicking Terminate in the Terminate task toaster popup

**Comment by aleksey-bykov** [comment]
Yes
