### ISSUE TITLE
Follow link for files no longer working

### ISSUE THREAD

**Issue by deepzeafish** [microsoft/vscode#100195]
- VSCode Version: 1.46
- OS Version: Catalina

Issue Type: <b>Bug</b>

Until recently I could Cmd+left click on a file path and VS Code would open the related file:

```
file://Users/myuser/somefolder/somefile.txt
```

But now I'm getting this error:

> Unable to read file '//Users/Users/Users/myuser/somefolder/somefile.txt' (Error: Unable to resolve non-existing file //Users/Users/Users/myuser/somefolder/somefile.txt')

I disabled all installed extensions, but the problem persists. 

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.2.0
Bookmarks|ale|11.2.0
project-manager|ale|11.0.1
swagger-viewer|Arj|3.0.1
All-Autocomplete|Ati|0.0.23
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.36.0
gitlens|eam|10.2.2
url-encode|fle|1.1.0
seito-openfile|Fr4|1.8.7
rest-client|hum|0.24.1
copy-current-file-path|ion|0.0.3
path-autocomplete|ion|1.13.6
asciidoctor-vscode|joa|2.7.15
vscode-cfn-lint|kdd|0.12.1
rainbow-csv|mec|1.7.0
metago|met|4.2.0
MetaJump|met|1.0.2
MetaWord|met|1.2.1
prettify-json|moh|0.0.3
python|ms-|2020.5.86806
vscode-json-editor|nic|0.2.3
text-power-tools|qcz|1.11.1
java|red|0.62.0
vscode-yaml|red|0.8.0
partial-diff|ryu|1.4.1
open-in-browser|tec|2.0.0
json|Zai|1.0.4

</details>

**Comment by sandy081** [comment]
May I know where are you clicking such links?

**Comment by deepzeafish** [comment]
In a text file. Language mode doesn't seem to matter.

**Comment by alexdima** [comment]
@deepzeafish I think you're missing a `/`:

```
file:///Users/alex/src/working_dir/test.css
```
