### ISSUE TITLE
Integration test: VS Code API - openTextDocument failed

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#100159]
Failed on Windows:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=78487&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=c9c1d16f-6a21-57a3-556a-d7a168909c84&l=321

**Comment by jrieken** [comment]
This test still relies on the FS and should be moved to a virtual file system for more stability
