### ISSUE TITLE
vscode run to show  configuration.jsonValidation.url  error

### ISSUE THREAD

**Issue by MrSunml** [microsoft/vscode#100125]
This error is reported every time it is started, no solution is found. 
The error message is as follows：

[tht13.python]: "configuration.jsonValidation.url" 必须是绝对 URL 或者以 "./" 开头，以引用扩展中的架构。
------------------------------------------------------------------------------------------------------------
[tht13.python]: " configuration.jsonValidation.url 'must be an absolute URL or start with'. / 'to refer to the schema in the extension.

**Comment by aeschli** [comment]
Can you file this against the `tht13.python` extension? Thanks!
