### ISSUE TITLE
WebviewInput and LazilyResolvedWebviewEditorInput have same type ID?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#100184]
Not clear to me how the one relates to the other, but typically editors should have different type IDs per kind. And if the one is only used as parent type, it could remain `abstract`

**Comment by mjbvz** [comment]
This is by-design. `LazilyResolvedWebviewEditorInput ` is just a specialized implementation of `WebviewEditorInput`. From the workbench's point of view, the two use the same editor and are functionally the same

We only need to differentiate `LazilyResolvedWebviewEditorInput` for the implementation of webview editors themselves, such as: https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/workbench/contrib/webview/browser/webviewWorkbenchService.ts#L272
