### ISSUE TITLE
 Auto-indent on tab press to match indentation of previous line

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode#100135]
**Issue Type - Indentation**
- VSCode Version: 1.46.0 (May 2020 _Release)_
- OS Version:Windows 10 x64

_Steps to Reproduce:_

- For Comparision to other editors:
  In Sublime (and also Atom), if I press tab under a line of code that already has 4 tab spaces, 
  Sublime will automatically jump to the same tab spacing of the previous line (4 tab spaces).

- **But in VS CODE when trying to accomplish the same thing – tabs will fail to 'jump' to the previous line's spacing, and force me to manually press tab multiple times, instead of once.**

_**ScreenShots:**_

**1. Sublime Text:**
![sublime-gif](https://user-images.githubusercontent.com/54276661/84601712-f617a800-ae9f-11ea-8f56-476de1e0ce86.gif)

**2. VS CODE**
![vscode-gif](https://user-images.githubusercontent.com/54276661/84601706-ea2be600-ae9f-11ea-8303-506fdc53e687.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/confirmationPending

Doesn't reproduce for me:
![junk](https://user-images.githubusercontent.com/6726799/84642368-4587c380-aef4-11ea-9033-54a78e0f038a.gif)

(screencast mode used for clarity)

Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Ah, I think I see the difference in what you're doing. Looks like you Press Home after the end-if-line-1 Enter, then expect one Tab to give you the same indent on line 2 as line 1 has, right?

**Comment by lakshits11** [comment]
Yes!! @gjsjohnmurray
