### ISSUE TITLE
Can't use debugger anymore (cannot find any required module or local js file)

### ISSUE THREAD

**Issue by accessdev** [Microsoft/vscode#10012]
- VSCode Version: 1.3.1
- OS Version: windows 7
- node version : 0.12.9

Steps to Reproduce:
1. Launch my node.js project
2.  notice the error, the app can't be launched due to crash at first require (same error for local js file, local module or global module)
   
   var filename = Module._findPath(request, paths);

can't find  "./c:UAFCODEUbiArtFrameworkexternOnlineServer\nodejsconfig" 

I don't know why the / are missing from this path

in the node.js code I do:

var config = require("./config")

I am able to launch the project using node app.js from command line

Only visual studio code debugger fail to launch the project.

It starts to fails suddenly after no specific changes

My launch.json file 

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Lancer",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/app.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "local"
            },
            "externalConsole": false,
            "sourceMaps": false,
            "outDir": null
        },
        {
            "name": "Attacher",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outDir": null,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        },
        {
            "name": "Attach to Process",
            "type": "node",
            "request": "attach",
            "processId": "${command.PickProcess}",
            "port": 5858,
            "sourceMaps": false,
            "outDir": null
        }
    ]
}

Reinstalling visual studio code or node.js don't fix the issue.

**Comment by weinand** [comment]
@accessdev and the problem persists after a reboot?

**Comment by accessdev** [comment]
yes. I reinstall node.js and visual studio code several times. still the same issue.

**Comment by weinand** [comment]
@accessdev did you try to use a more recent version of node, e.g. v5.12.0?
Can you try with the upcoming 1.4.0 release: https://code.visualstudio.com/insiders ?

**Comment by accessdev** [comment]
@weinand thanks ! it works with 1.4.0  :)
I can't update to node 5.X because we use some custom c++ modules and we still need to port it to 5.X.

**Comment by weinand** [comment]
@accessdev I've just created a Win 7 VM with node 0.12.9 and VS Code 1.3.1 and I cannot reproduce your problem with an "express" app that requires several modules (including one that uses a '../app.js' path, but no './config' path).

**Comment by weinand** [comment]
@accessdev are you relying on some specific environment variables (e.g. PATH)?
In 1.4.0 we've fixed something in that area (but IIRC only for linux or OS X). Strange.

**Comment by accessdev** [comment]
Indeed, that s weird. I use VS code on a daily basis since month on the same machine, same project, the problem starts in the middle of a debug session last week without any chances in the project, or envs vars, software installs. between, I started a fresh express project to reproduce the issue in a minimal setup , but the issue was not present.

**Comment by weinand** [comment]
Hmmm, this sounds like something got corrupted. But I don't understand how VS Code 1.4.0 was able to "fix" that.

**Comment by adamwlarson** [comment]
I think this is related to #13005 as I have the exact same issue, right down to the detail of crashing anytime a require occurs.

**Comment by MartinMuzatko** [comment]
Still have the problem

**Comment by weinand** [comment]
@MartinMuzatko so you are using VS Code 1.3.1 and node.js 0.12.9 on Windows 7?

**Comment by MartinMuzatko** [comment]
No. I'm on Windows 10 with latest vscode @weinand .
However, i found the cause that makes Debugging with vscode impossible for me. I use WSL (Bash on Ubuntu on Windows) which I use to install dependencies. The problem is that for a package, only the linux bindings are installed. Is there a way to set an environment for vs code?

**Comment by weinand** [comment]
@MartinMuzatko please create a new issue for this since it is unrelated to this.
