### ISSUE TITLE
Still get padding after exiting Zen Mode

### ISSUE THREAD

**Issue by RalfG** [microsoft/vscode#100113]
- VSCode Version: 1.46.0 (user setup)
- OS Version: Windows_NT x64 10.0.19035

Steps to Reproduce:
1. Turn on Zen Mode
2. Close VSCode
3. Reopen VSCode

Does this issue occur when all extensions are disabled?: Yes

Duplicate of #91805, but the problem does not get fixed when removing the `.vscode` directory and reopening VSCode.

My workspace was opened in Remote - WSL. The padding is not present when I reopen the project folder in VSCode "non-WSL", or when I open another project folder (either in in normal VSCode or in Remote - WSL). 

When reopening with all extensions disabled, the padding is still present (although the Remote - WSL extension is disabled and shows "Disconnected from wsl+Ubuntu" in the bottom left-hand corner.

I also tried to toggle both Zen Mode and Full Screen mode several times, but this does not seem to fix the issue.

**Comment by isidorn** [comment]
F1 > toggle centered mode
Does this help?
Also you can experiment with 
	"zenMode.centerLayout": false
if you do not want this

**Comment by RalfG** [comment]
Yes, that indeed worked! I did not know centered mode was a separate feature... 🤦‍♂️
Thanks!
