### ISSUE TITLE
Inconsistent paste behavior with multiple cursors

### ISSUE THREAD

**Issue by jonsa** [Microsoft/vscode#10024]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1: With the following text

```
abcd
1234
abcd
1234

```

2: Select all occurrences of `1234` with two cursors
3: Cut and paste the content and the original text will be restored.
4: Extend the selection to include the trailing new line.
5: The output will now be

```
abcd
1234

1234
abcd
1234

1234

```

Expected result would be to have the original text restored.

![multicursor_copy_paste](https://cloud.githubusercontent.com/assets/807381/17299405/828b1fd4-580e-11e6-8434-0a89fb3621b9.gif)

**Comment by atombender** [comment]
I believe this is the same issue as #4996.

**Comment by Leeds-eBooks** [comment]
Is there any movement on this? I am trying to move from Atom to VSCode but this is a huge deal-breaker, I use multiple copy and paste all the time.

**Comment by winuxue** [comment]
any update?

**Comment by alexandrudima** [comment]
Fixed with the fix for #4996 (e07bba8de99e116d63eb18e142a711ed92b04445)
