### ISSUE TITLE
"You cannot save this document with extension..." Is this new?

### ISSUE THREAD

**Issue by ConduciveMammal** [microsoft/vscode#100241]
Issue Type: <b>Bug</b>

In my `settings.json`, I have this setting enabled: `"files.defaultLanguage": "liquid"`, and have done for a long time.

But since the last update, when attempting to save other file types, such as SCSS or JS, I've been getting the following dialog:
![image](https://user-images.githubusercontent.com/18140157/84713658-6e936d00-af63-11ea-824a-1054297962b5.png)

Now simply changing the Format option to All Files allows it to save but it's immensely annoying.

Is this a new feature or could it be an extension?

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|-psn_0_3433286|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
polaris-snippets|And|0.1.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.1.4
vscode-eslint|dba|2.1.5
vscode-dash|dee|2.4.0
githistory|don|0.6.5
jquerysnippets|don|0.0.1
EditorConfig|Edi|0.15.1
auto-complete-tag|for|0.1.0
vscode-drawio|hed|0.7.0
beautify|Hoo|1.5.0
vscode-fast-folder-structure|Huu|1.0.1
vscode-cdnjs|Jak|0.18.0
vscode-liquid-snippets|kil|1.3.0
vscode-autoprefixer|mrm|3.0.1
vscode-scss|mrm|0.9.0
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.3
vscode-remote-extensionpack|ms-|0.20.0
language-liquid|nei|0.1.1
material-icon-theme|PKi|4.1.0
vscode-yaml|red|0.8.0
bash-beautify|sha|0.1.1
stylelint|shi|0.51.0
json-template|sto|0.3.1
vscode-status-bar-format-toggle|tom|2.0.0
vscode-sort-package-json|uni|1.2.2
vscodeintellicode|Vis|1.2.8
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@ConduciveMammal I am trying to reproduce this, but I need exact steps from zero to issue. What I did so far:
* installed the extension `language-liquid`
* configured `"files.defaultLanguage": "liquid"`
* created a new file and saved as *.scss

**Comment by bpasero** [comment]
The fix for https://github.com/microsoft/vscode/issues/96283 should not be done on any OS but Windows.

**Comment by bpasero** [comment]
Turns out this needed a different fix: https://github.com/microsoft/vscode/issues/102713
