### ISSUE TITLE
Creating an untitled paw draw file will not open the paw draw editor

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#100238]
- VSCode Version: Version: 1.47.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:
1. Modify the custom-editor-sample to have a 'create new pawdraw' file.
1. Change extension.ts to have code like so:
```
import * as vscode from 'vscode';
import * as path from 'path';
import * as os from 'os';
import { CatScratchEditorProvider } from './catScratchEditor';
import { PawDrawEditorProvider } from './pawDrawEditor';

export function activate(context: vscode.ExtensionContext) {
	// Register our custom editor providers
	context.subscriptions.push(CatScratchEditorProvider.register(context));

	if (+vscode.version.match(/1\.(\d+)/)![1] >= 45) {
		context.subscriptions.push(PawDrawEditorProvider.register(context));
	}

	vscode.commands.registerCommand('catCustoms.createnew', newPawDraw);
}

function newPawDraw() {
	const file = path.join(os.tmpdir(), 'test-1.pawdraw');
	const uri = vscode.Uri.file(file);
	const untitled = uri.with({ scheme: 'untitled', path: uri.fsPath });
	vscode.commands.executeCommand('vscode.openWith', untitled, 'catCustoms.pawDraw' );
}
```
3. Modify the package.json to support the new 'catCustoms.pawDraw' command:
```
"commands": [
            {
                "command": "catCustoms.createnew",
				"title": "Create new Paw Draw",
				"category": "Paw Draw"
            }
		],
```
4. Run the extension
4. Attempt to run the command 
4. This comes up instead of the paw draw editor:

![image](https://user-images.githubusercontent.com/19672699/84712427-67497080-af1d-11ea-93f0-b3fb3ef96351.png)

Does this issue occur when all extensions are disabled?: N/A

Note this might be related to:
https://github.com/microsoft/vscode/issues/93441

**Comment by rebornix** [comment]
I am seeing exceptions after running this command 

```
Unable to open 'test-1.pawdraw': No file system provider found for resource 'untitled:/var/folders/j7/py1_06vs0y3bbcdpsn0pd66h0000gn/T/test-1.pawdraw'.
```

I'm wondering if we should always recommend creating untitled file by https://github.com/microsoft/vscode/issues/98992#issuecomment-644388948

**Comment by connor4312** [comment]
reopening due to `-found` tag

**Comment by mjbvz** [comment]
Should be fixed by cf0094f9ebbb4c0a8df6991da9a7b154b0475c1e

**Comment by mjbvz** [comment]
Actually never mind, that was for a different issue.

I think the bug here is that the example extension does not handle untitled files properly. The root problem is that we try using the `vscode.fs` with an `untitled:` uri, which is not supported. That limitation probably makes sense considering how `fs` works, but makes handling untitled custom editors more difficult

**Comment by rchiodo** [comment]
Creating a new file works, but you can't close it.

When I attempt to close the file this happens:

![image](https://user-images.githubusercontent.com/19672699/89672747-0a719300-d89a-11ea-9396-7d2cdffa8be3.png)

**Comment by rchiodo** [comment]
@mjbvz is this a known limitation or should I open a separate bug? You kinda made it sound like untitled files just aren't supported.

**Comment by mjbvz** [comment]
A separate issue would be best. We haven't focused on support for untitled files, in part be because we're still seeing how people use custom editors. We also need proper apis for creating untitled files in the first place
