### ISSUE TITLE
File Explorer: Add shortcut to go up to the parent directory 

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#100208]
Let's say In the file explorer i'm hovered over a folder in `node_modules`.
We know node_modules can be very big, and after inspecting a vendored file I want to close the directory (using the keyboard).

I'm usually 100 folders deep and i want to get back out, like this screenshot:
<img src="https://user-images.githubusercontent.com/936006/84671806-b55f7380-af1f-11ea-9e55-c9dc4150385a.png" width=300 />

Right now the only (quick) way to back to the top is to search again for `node_modules` then press up on the cursor key, and then you can close the directory.
This is a bit cumbersome, it would be nice if we can have a "go to parent directory" shortcut to speed up explorer navigation

As an aside
it would be nice if the `Back` shortcut also worked in the File Explorer context, so you could go back to files you highlighted over

**Comment by isidorn** [comment]
Press the left key please.

**Comment by jasonwilliams** [comment]
@isidorn Thanks I wasn't aware that worked

**Comment by isidorn** [comment]
You're welcome.
