### ISSUE TITLE
VS Code runs stale persisted launch configs

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#100265]
VS Code 1.46

- start VS Code Stable
- use this launch config:
  ```
  {
     "type": "node",
     "request": "launch",
     "name": "echo args",
     "runtimeExecutable": "echo",
     "args": [ "hello", "world" ]
  },
  ```
- close "launch.json" editor
- run it
- Observe: (everything is good)
  <img width="749" alt="2020-06-16_09-34-37" src="https://user-images.githubusercontent.com/1898161/84745991-a1665100-afb5-11ea-9d65-5055f5e20f0b.png">
- shutdown VS Code
- open same project with VS Code Insiders (or any other editor)
- modify "launch.json" and include argument "1234" between "hello" and "world"
- shutdown VS Code Insiders
- launch VS Code Stable again
- go to debug view and run "echo args" launch config
- open launch.json
- Observe:
  <img width="1080" alt="2020-06-16_09-39-11" src="https://user-images.githubusercontent.com/1898161/84746241-fa35e980-afb5-11ea-90f2-119b00c3caca.png">

VS Code runs old launch config which lacks the "1234".

Workaround: an edit change of launch.json is needed before VS Code will run the correct launch config.

**Comment by isidorn** [comment]
We no longer store the configuration in storage. The only downside is that now when you select a dynamic configuration, reload, we do not preserve the dynamic configuratoin and you have to select it again. For that we would have to store the "origin" as you suggested, but that I will tackle as a seperate issue, thus reopening https://github.com/microsoft/vscode/issues/96293

**Comment by weinand** [comment]
I've verified that no stale launch configs are run.
