### ISSUE TITLE
Disable certain keyboard shortcuts when the terminal has focus

### ISSUE THREAD

**Issue by seandjones92** [microsoft/vscode#100292]
When using the terminal I want to be able to use default bash/zsh keybindings for the readline to scroll through the history. When in a normal standalone terminal emulator I can use `ctrl+p` to scroll up through history and `ctrl+n` to scroll down. 

These have some obvious conflicts with other keybindings in VSCode. I'd like to have the built in terminal catch these bindings before they go to the rest of the editor. 

For example, if a file has focus and I hit `ctrl+p` it should launch the quick open UI as it normally would. Then I can use `ctrl+~` to launch a terminal and then hit `ctrl+p` again to start scrolling up through the command history

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/docs/editor/integrated-terminal#_forcing-key-bindings-to-pass-through-the-terminal

For your specific example (ctrl+p) I think you need:

```
  "terminal.integrated.commandsToSkipShell": [
    "-workbench.action.quickOpen"
  ]
```

**Comment by seandjones92** [comment]
That did the trick, thank you
