### ISSUE TITLE
Moving a file should load the model directly with the contents it had before

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#100255]
Version: 1.47.0-insider
Commit: 0288447572790f983c350905bd1fc5b754970a0a
Date: 2020-06-15T05:32:43.514Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

Currently when you move an unsaved file to a new location, VS Code will load the model with the disk content first, then do an extra update to append the unsaved changes to the model. See a typical workflow as below:
- Open file A.java in VS Code.
- Modify file A.java and add some contents, and leave it unsaved.
- Drag and drop A.java to a new folder f1.
- I observed the following notifications happening:
-> didClose { uri: A.java }
-> didOpen { uri: f1/A.java, version: 1, text: \<the contents in the disk file\> }
-> didChange { uri: f1/A.java, version: 2, contentsChanges: \<the unsaved changes before move\> }

When there are extensions listening on renameFiles event for rename refactoring, the silent didChange behavior from VS Code client probably conflicts with the refactoring job. It makes more sense to load the model directly with the contents it had before. 

_Originally posted by @testforstephen in https://github.com/microsoft/vscode/issues/98653#issuecomment-644167079_

**Comment by testforstephen** [comment]
@bpasero Any update about this issue?

**Comment by bpasero** [comment]
Yeah I think I have a possible fix.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/108115

@testforstephen would be great if you can verify this once we have a `1.51.x` insiders build out at the end of this week.

**Comment by testforstephen** [comment]
@bpasero The fix works well in the insider at 2020-10-09, the unsaved contents are carried to the moved file directly. thanks.
