### ISSUE TITLE
Notebook editor layout glitch while resizing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#100224]
![Jun-15-2020 13-44-16](https://user-images.githubusercontent.com/323878/84694149-56ddc980-af0e-11ea-9f1c-fcbfeede2018.gif)

Seems like the basic issue is that here, we are using the old scrollWidth to compute the new height, with the new total width, so when sizing the editor to be smaller, `scrollWidth` is always `> width`. I see the same wrong computation in a basic text editor, but I guess it's not a problem when the height is wrong there.

https://github.com/microsoft/vscode/blob/b95c7252d1b4fcc649ace208d49503211f6b8fca/src/vs/editor/common/viewLayout/viewLayout.ts#L218

This fixes it

![image](https://user-images.githubusercontent.com/323878/84695001-c30cfd00-af0f-11ea-9dfe-c1603d0e0cfb.png)

but I really have no clue if that's the right thing to do, also `scrollWidth` is used in `_updateHeight`. I think that's ok because that's not called when these numbers are changing so `scrollWidth` will just be equal to `contentWidth` or `width`.

**Comment by roblourens** [comment]
@rebornix I think I've done all the debugging I can do on this. The change in my screenshot might be enough or it might break stuff. Do you have any idea or should we loop in Alex?

**Comment by rebornix** [comment]
thanks for the investigation, @alexdima can you confirm if it's safe?

**Comment by alexdima** [comment]
:+1: The analysis is very good and that change makes good sense.
