### ISSUE TITLE
The workspace could not save the added directory.

### ISSUE THREAD

**Issue by sguot** [microsoft/vscode#100210]
Hello, I have a problem adding to the directory in the workspace. After restarting the editor, it will be cleared and need to be added again.

---

* VS Code version: 1.46.0
* OS version : MacOs Catalina 10.15.4 (19E287)
* extensions : empty(Empty the installation)
* steps
   1. start the vscode.
   2. `explorer` -> `Open Folder` => Select a directory to open.
   3. `File` => `Close Window`.
   4. start the vscode again ，**The exploer is empty**

**Comment by isidorn** [comment]
I can not reproduce this. Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by sguot** [comment]
> I can not reproduce this. Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

Thanks，It should be the system

**Comment by isidorn** [comment]
Then I am closing this issue, if more users mention this we can reopen and investigate further. Thanks
