### ISSUE TITLE
"Go to file" truncates paths and is non-resizable

### ISSUE THREAD

**Issue by Bu11etmagnet** [microsoft/vscode#100214]
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a deep directory hierarchy
2. Create several files with the same name in different directories
3. Press Ctrl+P and type in the name of the file

![image](https://user-images.githubusercontent.com/7579651/84680194-974f3e80-af32-11ea-908d-079aa289493f.png)

There is no way to uniquely identify the files if they differ in the deepest directory level.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.

**Comment by Bu11etmagnet** [comment]
To save others the eyeball-grep: https://github.com/microsoft/vscode/issues/85374
