### ISSUE TITLE
Folder settings don't work

### ISSUE THREAD

**Issue by dreamflasher** [microsoft/vscode#100203]
- VSCode Version: 1.46.0
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

1. Create workspace with two folders A and B
2. Change folder setting A: `"python.formatting.provider": "black"` 
3. Change folder setting B: `"python.formatting.provider": "yapf"`

# Expected Result
Formatting in folder A will be done by black, and formatting in B by yapf.

# Actual Result
Formatting in both folders is done by autopep8, the default.

**Comment by IllusionMH** [comment]
/extPython

This setting comes is from Python extension and it's support/behavior should be reported there.
