### ISSUE TITLE
debugging on python error: Ctrl+click gives "Search Workspace" instead of "jump to line"

### ISSUE THREAD

**Issue by Dr-Nuke** [microsoft/vscode#100213]
- VSCode Version:
Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
- OS Version:
Win 10

Steps to Reproduce:

1. produce an error in a python script
![image](https://user-images.githubusercontent.com/56429408/84679298-70dcd380-af31-11ea-9375-550dd3be682b.png)

2. ctrl-click the code line number
![image](https://user-images.githubusercontent.com/56429408/84679515-aed9f780-af31-11ea-8586-920a3b4a0ce2.png)

Intended behavior:
jump to the correspoding line in the code

Does this issue occur when all extensions are disabled?: Yes/No

no, it would disable my WSL extension, which is the basis of my environment

**Comment by sandy081** [comment]
Please file the issue agains the extension that is providing this feature. In this case I think the python extension.

**Comment by Dr-Nuke** [comment]
no, actually same behavior for a shell script

**Comment by IllusionMH** [comment]
VS Code supports go to line for something line `test.py:1`, but `File "test.py", line 1` is custom format and far from something guessable/parsable.
Also see https://github.com/microsoft/vscode/issues/98277#issuecomment-640658189 which mentions that spaces in links are not supported.
