### ISSUE TITLE
Explorer no longer opens file on click when selected before

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#100279]
Steps to Reproduce:

1. open a file by clicking on explorer
2. close file via `Cmd+W`
3. reload window
4. click on same file

=> 🐛 nothing happens

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/100207

**Comment by joaomoreno** [comment]
@isidorn You *did* say users would be enraged.

**Comment by isidorn** [comment]
🔥 ⚔️ ⚒️ 🔥
