### ISSUE TITLE
Code won't update on macOS 10.15.5

### ISSUE THREAD

**Issue by PenelopeFudd** [microsoft/vscode#100216]
- VSCode Version: 1.46.0
- OS Version: MacOS 10.15.5 Catalina

Steps to Reproduce:

1. Start VSCode
2. Click 'Code > Check for updates'

"Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See this link for more information."

* The error message is incorrect: the application is not on a read-only volume, it is in "/Applications/Visual Studio Code.app", but the files are marked as "quarantined".

* This is the same error as https://github.com/microsoft/vscode/issues/57664 and https://github.com/Microsoft/vscode/issues/7426 . 

* The fix suggested by #7426 was incomplete.

Solution:
```
xattr -dr com.apple.quarantine ~/Library/Caches/com.microsoft.VSCode.ShipIt* /Applications/Visual\ Studio\ Code.app/
```

* If you could improve the error message, that'd be good.
* If the code could do the xattr deletion itself, even better.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
The error message comes from the Squirrel framework, unfortunately. And it is correct, since when apps are in quarantine, they get executed from a read-only volume.

Code can't do the xattr deletion itself, that would be a pretty awful security flaw in macOS.
