### ISSUE TITLE
@路径提示问题(@Path question)

### ISSUE THREAD

**Issue by osorso** [microsoft/vscode#100262]
Path IntelliSense in version 1.46 cannot call up automatic path prompt after configuring alias, additional configuration is required jsconfig.json ; version 1.45.1 does not require additional configuration jsconfig.json File, can be called up normally

**Comment by yume-chan** [comment]
Are you using the Path Intellisense extension?

Did you see ChristianKohler/PathIntellisense#162 ?

**Comment by osorso** [comment]
yes, thanks

**Comment by eamodio** [comment]
@osorso Can this be closed then?

**Comment by osorso** [comment]
@eamodio sure
