### ISSUE TITLE
Allow right-click paste inside the debug console

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode#100235]
![image](https://user-images.githubusercontent.com/2473545/84702177-97e4d680-af2c-11ea-9383-4fde85171870.png)

- VSCode Version: 1.46

Steps to Reproduce:

1. Open the debug debug console
2. Right-click inside the console view

There should be an option to paste text. Currently, pasting is only allowed when right-clicking the very narrow text input area. 

The debug console should be more similar to the terminal, which allows for right-click pasting anywhere. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
I like this idea and makes perfect sense.
We are open for a PR that fixes this
Code pointer https://github.com/microsoft/vscode/blob/6d5bed6ac92012004c9d264340a341f924f260da/src/vs/workbench/contrib/debug/browser/repl.ts#L597

You would simply need to create a new action that uses a clipboardService to read what is in the clipboard and write it in the `replEditor`

**Comment by daniel-j-davis** [comment]
I'd like to take this on, @isidorn. Is that OK?

**Comment by isidorn** [comment]
Yes it is ok. Thanks

**Comment by daniel-j-davis** [comment]
Just to confirm, is this the expected behaviour, or is the idea that it would overwrite the input field, instead of appending the pasted text to what's already there? 

https://i.gyazo.com/f1cfe66ae6ad3ec7718c308c1c702d11.gif

@phgmacedo @isidorn

**Comment by phgmacedo** [comment]
> Just to confirm, is this the expected behaviour, or is the idea that it would overwrite the input field, instead of appending the pasted text to what's already there?
> 
> https://i.gyazo.com/f1cfe66ae6ad3ec7718c308c1c702d11.gif
> 
> @phgmacedo @isidorn

That's what I had in mind.

**Comment by isidorn** [comment]
Correct, this is also what I had in mind. Thanks!

**Comment by weinand** [comment]
Verifying...
After a right-click "Paste" from the upper part of the "Debug Console" (which cannot receive keyboard input), the focus stays on that part (which is pretty useless). The focus should be transferred to the bottom text box so that I can just press return to execute the pasted command. The "Clear Console" command transfers the focus correctly.

**Comment by isidorn** [comment]
@weinand good catch. Pushed a fix.

**Comment by isidorn** [comment]
Yeah let's also disable the action when debug session is not running.
