### ISSUE TITLE
Spamming DEL on Keyboard Shortcuts view duplicates entries

### ISSUE THREAD

**Issue by theAkito** [microsoft/vscode#100200]
- VSCode Version: 1.46.0
- OS Version:
```
10.0.19041
19041
```

Steps to Reproduce:

1. Open Preferences -> Keyboard Shortcuts
2. Spam DEL key
3. See duplicate entries created in `keybindings.json`, if you spam DEL key too quickly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Not sure what you meant by Spam DEL key. Can you please provide a video or gif to know what it is about.

**Comment by theAkito** [comment]
@sandy081 

Thanks for your response.

1. Open Preferences -> Keyboard Shortcuts
2. `for i in shortcuts; do press DEL; sleep 0.01s; done`
3. See duplicate entries created in keybindings.json, if you spam DEL key too quickly.

**Comment by sandy081** [comment]
> while true; do press DEL; sleep 0.01s; done

Where are you writing this? Can you please provide a video ?

**Comment by theAkito** [comment]
@sandy081 

Forgive me, if my explanations are confusing.

I am trying to say the following:
1. One should open _Keyboard Shortcuts_ in the _Preferences_ section in _File_, in the VS Code window.
2. You select 1 single shortcut in the list of Keyboard Shortcuts GUI.
3. You press the DEL key on your keyboard really quickly.
4. The DEL key deletes a shortcut.
5. If you press the DEL key on your keyboard really quickly, then some shortcuts are deleted twice, etc.
6. This results in duplicate rules within the `keybindings.json`.

I hope this is explicit enough.

P.S.: Holding the DEL key instead does not work.
