### ISSUE TITLE
Launch config: Input variables do not work inside input defaults

### ISSUE THREAD

**Issue by Spenhouet** [microsoft/vscode#100268]
- VSCode Version: 1.46.0
- OS Version: Windows 10

Steps to Reproduce:

1. Use input variables in the defaults for input fields in the launch configuration (e.g. `"default": "${workspaceFolder}"`).
2. Start the execution
=> The input field will show "${workspaceFolder}" instead of the actual path.

Example launch config:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run: Test",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/test.py",
            "args": [
                "--test",
                "${input:test}",
            ],
            "console": "integratedTerminal",
        },
    ],
    "inputs": [
        {
            "id": "test",
            "type": "promptString",
            "default": "${workspaceFolder}"
        },
    ]
}
```

Does this issue occur when all extensions are disabled?: I did not test that.

**Comment by Spenhouet** [comment]
@weinand Sure I disagree. How can this be expected behavior or are you trying to say you were unable to make it work?

What about this is supposed to be expected? Can you please elaborate?

**Comment by weinand** [comment]
Variable substitution was designed as a simple macro mechanism not supporting nesting.
Input variables are one type of variables.
Supporting variable substitution in input variables would result in nesting.
