### ISSUE TITLE
Extension Development Host doesn't prompt to save dirty files on close

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10027]
- VSCode Version: 1.3.1
- OS Version: Windows 10

I noticed that if I make changes to files inside the extension development copy of Code then close those files (middle click on the tab, or click the X) then I do not get prompted to save; the changes are just discarded.

I've commented out all code in my `activate` method along with things like `grammar`s in `package.json` but it still happens. My main Code window *does* prompt to save performing the same action.

I cloned one of your [sample repos](https://github.com/microsoft/vscode-wordcount) and I see the same behaviour running that.

**Comment by kieferrm** [comment]
This is still the case in 1.4.0 insiders. Not sure whose area that is. Starting with @bpasero.

**Comment by bpasero** [comment]
As designed, e.g. to enable tests to make buffers dirty and shutdown after tests are done.

**Comment by bpasero** [comment]
**Verification:** Run an extension development window with `--extension-development-confirm-save` and close a dirty file. It should prompt you to save.
