### ISSUE TITLE
In-application rating for extensions

### ISSUE THREAD

**Issue by jaime-olivares** [Microsoft/vscode#10025]
- VSCode Version: 1.3

Something is not working well regarding to the rating of extensions. I estimate only 1 out of 10,000 downloaders provide a rating.

I think it may be useful to provide a mechanism for rating/commenting inside the application rather than the Marketplace website. It can be also suggested to the user from time to time.

**Comment by joaomoreno** [comment]
Fair feature request, but very likely not going to happen. Ratings require authentication, which we already get for free in the Marketplace.

**Comment by jaime-olivares** [comment]
Avoiding authentication doesn't sound reasonable. It may be complex but it does work in Visual Studio and offers many benefits, specially for valuable per-user analytics and reducing sign-ins in multiple Microsoft services. I think that should be explicitly in your roadmap.

**Comment by joaomoreno** [comment]
True, but is also adds to Code's weight.

Visual Studio is an IDE, while Code is a _lightweight but powerful source code editor_.

**Comment by jaime-olivares** [comment]
Well, an editor with a built-in and or attached compiler, debugger and linter, cannot be considered a lightweight editor, IMHO, I would rather think of a lightweight IDE.

I have been tempted to suggest to add this functionality as an extension, but the fact is that you guys have turned the extension manager into a first-class citizen (something that I celebrate), so it makes sense to me to add authentication in the same way.

**Comment by waderyan** [comment]
Thank you for your feedback @jaime-olivares. Your viewpoint is valuable to us. 

However, @joaomoreno is correct. We explored this option before in our usability studies and, although further data will be gathered and we may change our mind in the future, adding authentication to VS Code is not on the roadmap.

**Comment by jaime-olivares** [comment]
@waderyan & @joaomoreno,  let me go back to my primary comment: something is not working well with ratings, as only 0.01% of downloaders are providing scores. In case it is not possible to have authentication (and hence in-app scoring) right now, there should be another mechanism for encouraging people to provide scores.

**Comment by joaomoreno** [comment]
Closing as likely won't happen any time soon. Sorry, man.
