### ISSUE TITLE
Relative paths not working

### ISSUE THREAD

**Issue by HyunMook** [microsoft/vscode#100251]
- VSCode Version: 1.46.0
- OS Version: Windows 10 Pro 1909

Steps to Reproduce:

1.  `Ctrl + Click` the import path have to jump to the file/definition. But the relative paths are not working.

2.
`/webpack.config.js`
resolve: {
      extensions: ['.js', '.json', '.jsx', '.css', 'scss'],
      alias: {
        '@assets': path.resolve(__dirname, 'assets/'),
        '@component': path.resolve(__dirname, 'src/component/'),
        '@reducer': path.resolve(__dirname, 'src/reducer/'),
        '@modules': path.resolve(__dirname, 'src/modules/'),
        '@': path.resolve(__dirname, 'src/'),
      },
    },

`/jsconfig.js`
"compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "baseUrl": ".",
    "paths": {
      "*": ["*"],
      "@assets/*": ["./assets/*"],
      "@reducer/*": ["./src/reducer/*"],
      "@modules/*": ["./src/modules/*"],
      "@component/*": ["./src/component/*"]
    }
  }

`In my React component`
import React, { useRef, useState } from 'react'; // Ctrl + Click ---> It works.
import { useDispatch } from 'react-redux'; // Ctrl + Click ---> It works.
import { closeModal } from '@reducer/modal/actions'; // Ctrl + Click ---> It works.
import OptionSelectBox from './snippets/OptionSelectBox'; // Ctrl + Click ---> **NOT WORKING**

Also, if I do auto-import, the auto generated path is not what I expected.

expect>
import { closeModal } from '@reducer/modal/actions';

auto-generated>
import { closeModal } from 'src/reducer/modal/actions';
OR
import { closeModal } from '../../reducer/modal/actions';

**Comment by mjbvz** [comment]
Can you please share a complete, self contained example project that demonstrates the issue

**Comment by HyunMook** [comment]
https://github.com/HyunMook/R01

Please refer to the comments.

**Comment by mjbvz** [comment]
Thanks.

If you are using the `.jsx` file extension, you need to add:

```
    "jsx": "react",
```

to your `jsconfig.json`. Otherwise our IntelliSense will not load `.jsx` files. Once I added this setting, I see the imports being properly resolved 

You can easily debug problems like this by [enabling type checking in your js files](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript).

**Comment by HyunMook** [comment]
@mjbvz Thanks, It works.

But can you check one more thing in the sample repo?
How can I use the alias path to import path auto-completion?

When I use my function/file, I expect to import not the original path(1*) but the alias path(2*).
```
{
  ...
  "@modules/*"(2*): ["src/modules/*"](1*)
  ...
}
```

Because it occurred an Error like the below.
```
ERROR in ./src/component/App.jsx
Module not found: Error: Can't resolve 'src/modules/mTest' in '/Users/hmroh/Dev/ReactJS/R01/src/component'
 @ ./src/component/App.jsx 21:0-45 26:2-10
 @ ./src/index.js
```

**Comment by mjbvz** [comment]
Do you see that error in the editor, when you run webpack, or when you try running the packed javascript?

**Comment by HyunMook** [comment]
After trying to build

**Comment by mjbvz** [comment]
That is an issue with your webpack configuration then. Try looking over how you have configured the aliases to make sure they are correct

**Comment by HyunMook** [comment]
If I manually type the alias path such as `@modules/mTest`, It will not appear the Error.
Auto-completion is a function of VSCode.
Do I miss something?
