### ISSUE TITLE
Can't open preview of markdown

### ISSUE THREAD

**Issue by ericoshina** [microsoft/vscode#100254]
Issue Type: <b>Bug</b>

I can't find command “Markdown: Open Preview to the Side” on the Command Palette， thus can not open preview of a markdown file when I opened it on the editors. Also, there is no open preview icon on the upper right quarter.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (9.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.5.1
vscode-wordcount-cjk|hol|1.3.1
vscode-icons|vsc|10.1.1
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.0.0

</details>

**Comment by ericoshina** [comment]
Besides, OUTLINE can not show the outline information for markdown files.
![image](https://user-images.githubusercontent.com/54708017/84731602-eb5a3180-afcb-11ea-8378-1c44ba6cd6bf.png)

**Comment by gjsjohnmurray** [comment]
Please run the command to reload with all extensions disabled. If the MD preview now works, reload normally then disable each of your 6 extensions in turn until the preview works again.

**Comment by ericoshina** [comment]
> Please run the command to reload with all extensions disabled. If the MD preview now works, reload normally then disable each of your 6 extensions in turn until the preview works again.

Thanks for your help. I disabled all the extensions but the issue still exist. So maybe it's not about the extensions.

**Comment by ericoshina** [comment]
I installed a new extension “Markdown Preview Enhanced”, although I the command still cannot be found, but this extension will add a icon"markdown preview enhanced: open preview to the side" on the upper right corner and I can open the preview by tapping this icon. 
Besides. I also tried to reinstall vscode to fix this issue but it didn't work, and reinstall changed nothing of my settings. @mjbvz maybe those are the information that you need.

**Comment by mjbvz** [comment]
Did you also disable the built-in markdown extension? In the extensions view, search `@builtin markdown` to check this.


Also make sure you restart VS Code after disabling `Markdown Preview Enhanced`

**Comment by ericoshina** [comment]
@mjbvz I couldn't find the builtin markdown extension… and after disabling all the extensions including "Markdown Preview Enhanced", the issue still exists.

**Comment by mjbvz** [comment]
@ericoshina Here's an example of how to find the builtin extension:

<img width="715" alt="Screen Shot 2020-06-23 at 3 05 09 PM" src="https://user-images.githubusercontent.com/12821956/85469767-f03a5a80-b562-11ea-96c8-23839fbbe8ee.png">

Both of these should be enabled
