### ISSUE TITLE
merge-conflict Options Not Available in Settings

### ISSUE THREAD

**Issue by SapekshGupta** [microsoft/vscode#100227]
Issue Type: <b>Bug</b>

Cannot find Merge coflict options such as merge-conflict.codelens in VSC settings because of which I am not able to see the code difference options and the inline conflict resolution options when there is conflict during git merge.

Steps: Run below command in git-bash terminal:
`git merge bugfix`
Then observe the file main.html which is under conflict. Ideally, the file should highlight the conflicting lines of code and should provide the code lens options to resolve the conflict.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (1.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.5
gitlens|eam|10.2.2
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
code-runner|for|0.10.0
start-git-bash|McC|1.2.1
python|ms-|2020.5.86806
cpptools|ms-|0.28.3
material-icon-theme|PKi|4.1.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.8

</details>

**Comment by SapekshGupta** [comment]
I uninstalled everything (VSCode and all the extensions) and re-installed just the Code, the issue still persists. Still cannot find **merge-conflict.CodeLense** options in settings.

**Comment by chrmarti** [comment]
@SapekshGupta Not sure I understand. What do you get when searching for "merge conflict" in settings?
![image](https://user-images.githubusercontent.com/9205389/84989335-cd174180-b143-11ea-8f2b-6d27b2c69b2b.png)

What is the content of main.html when it has the conflict?

**Comment by SapekshGupta** [comment]
@chrmarti I get nothing when searching for "merge conflict" in Settings. - **No Settings Found**

![image](https://user-images.githubusercontent.com/52113122/84998451-7b83ac80-b16d-11ea-943d-862bd5e8f708.png)

If searching with only "merge", then I can see only this option:

![image](https://user-images.githubusercontent.com/52113122/84998412-6d359080-b16d-11ea-96d2-cb927760849e.png)

Content of main.html was something like this (it might have got changed a bit here and there):
![image](https://user-images.githubusercontent.com/52113122/84999054-46c42500-b16e-11ea-92f8-54c11f655c2b.png)
But, would like to understand whether the content really matters while searching or maintaining a given setting? I can't see this option even for a text file.

**Comment by chrmarti** [comment]
That extension works on textual markers in the file itself, e.g.:
```
<<<<<<< HEAD
bbb
=======
eee
>>>>>>> incoming
```
If you don't have any of these, there will be no code lens from the extension.

Did you by chance turn off the built-in extension? You can check in the Extensions viewlet's `Disabled` section:
![image](https://user-images.githubusercontent.com/9205389/85033659-7e889800-b181-11ea-8adb-8c9f9785e868.png)

**Comment by chrmarti** [comment]
Reinstallation does not reset the user data folder, so the extension stays turned off.

**Comment by AncientSwordRage** [comment]
I had this issue, and resolved it by disabling Git Lens.
