### ISSUE TITLE
Allow for instantly opening live share links that are sent in chat.

### ISSUE THREAD

**Issue by LucasBollen** [microsoft/vscode#100277]
In my experience, collaboration invites in VS code do not always appear when the user just launched vscode and we have to resort to sharing a link. Perhaps it would be possible to make it clickable in the live chat such that it instantly starts the session. (or let it generate a new invite?)

**Comment by eamodio** [comment]
Please open live share issues/feature requests here: https://github.com/MicrosoftDocs/live-share/issues
