### ISSUE TITLE
Support pinned tabs when tabs are disabled

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#100211]
I really want to use the pinned tabs feature, but I don't use the tab row - it's unnecessary when I can just use the list of open editors. Could the pinned tab functionality be applied to open editors too?

**Comment by bpasero** [comment]
Yeah I like that, there is nothing preventing us from supporting it, though we currently have no way of indicating that a tab is pinned when tabs are disabled. Maybe we simply do not decorate it at all and you have to know that you pinned it?

**Comment by Gruntfuggly** [comment]
Yes, I guess there's no real necessity to indicate that an editor is pinned. It could be shown in the hover (like it shows modified). If I was being really demanding, then a small pin icon where the close (x) icon appears would work too. You already have a "pinned" codicon.

**Comment by bpasero** [comment]
Maybe @misolori has ideas.

**Comment by Gruntfuggly** [comment]
Something like 
![image](https://user-images.githubusercontent.com/376658/84678334-cad89b80-af27-11ea-9c03-b8eb0d49dffa.png)

**Comment by bpasero** [comment]
Somehow this pin icon never feels right to me, but what you are suggesting somewhat makes sense to me.

However, I can see people wanting to both have a pin icon and a close icon and then it gets very heavy imho.

**Comment by Gruntfuggly** [comment]
I know what you mean - although it is the 'pinned' icon - it is still unpinned.

The close icon only appears on hover (apart from the current editor) so I would be happy if the close icon took priority over the pinned icon.

**Comment by misolori** [comment]
Not sure if using text as an alternate option would work any better (it's less noisy but takes up more space). We could also use it in the editor if we want to. We'd also need to make sure this works when the filename is truncated.

![image](https://user-images.githubusercontent.com/35271042/84679196-d86d3180-aee5-11ea-8527-e894319c8fb7.png)

**Comment by bpasero** [comment]
@misolori yeah so a decoration such as you show would also help for https://github.com/microsoft/vscode/issues/98161 if the tab was actually shown in full. Maybe something to play around with, it could even literally be the pin icon at that position.

**Comment by misolori** [comment]
Adding a pin icon instead might throw off the balance, but we can definitely play around with this:

![image](https://user-images.githubusercontent.com/35271042/84680010-e66f8200-aee6-11ea-8ef1-e3f875b78b38.png)

**Comment by bpasero** [comment]
Oh yeah, does not look very elegant...

**Comment by vicmarcal** [comment]
Also looks as "unpinned" as stated by @Gruntfuggly  
Attached one idea, slightly cleaner imho. It resembles a bullseye or the same pin looked from top down.
![pin](https://user-images.githubusercontent.com/6674048/85045590-70da0f00-b18f-11ea-9f94-69bff14eb044.png)

**Comment by bpasero** [comment]
@vicmarcal interesting idea, so you would put that when a tab is pinned instead of the close button? Similar to our dirty indication today?

**Comment by vicmarcal** [comment]
> @vicmarcal interesting idea, so you would put that when a tab is pinned instead of the close button? Similar to our dirty indication today?

Yes!

**Comment by bpasero** [comment]
This landed via https://github.com/microsoft/vscode/pull/106385
