### ISSUE TITLE
Terminal内容无法正常显示

### ISSUE THREAD

**Issue by leaf1992** [microsoft/vscode#100259]
Issue Type: <b>Bug</b>

Terminal输入了文字，但是显示不出来。

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3260 @ 3.30GHz (2 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
vetur|oct|0.24.0
LiveServer|rit|5.6.1
vscode-scss-formatter|sib|2.0.1
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4

</details>

**Comment by leaf1992** [comment]
![image](https://user-images.githubusercontent.com/13012378/84737086-c53b8e00-afd9-11ea-9d65-e2befd21f60b.png)

**Comment by leaf1992** [comment]
![image](https://user-images.githubusercontent.com/13012378/84737137-dab0b800-afd9-11ea-9a7a-f6b1e83ebabe.png)

**Comment by leaf1992** [comment]
Terminal cannot display the entered text and error log normally

**Comment by leaf1992** [comment]
![1592287481(1)](https://user-images.githubusercontent.com/13012378/84737350-527ee280-afda-11ea-8a74-8c74497e8445.jpg)

**Comment by leaf1992** [comment]
The uploaded image can't be displayed when GitHub comments

**Comment by yume-chan** [comment]
We can see your screenshot. 

Sometimes GitHub images can't be loaded from China due to some network issue.

**Comment by leaf1992** [comment]
Turn off the terminal and then turn it on again. The content can be displayed normally again.




| |
叶菲
|
|
邮箱：17606524212@163.com
|

签名由 网易邮箱大师 定制

在2020年06月16日 14:20，Simon Chan 写道：

We can see your screenshot.

Sometimes GitHub images can't be loaded from China due to some network issue.

**Comment by Tyriar** [comment]
This may be https://github.com/Microsoft/vscode/issues/69665, this setting should work around the problem: `"terminal.integrated.rendererType": "dom"`
