### ISSUE TITLE
CAN't connect to my account

### ISSUE THREAD

**Issue by pav88** [microsoft/vscode#100272]
Issue Type: <b>Feature Request</b>

I want to connect my visual studio code to my azure account but its not working.pls help

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
> I want to connect my visual studio code to my azure account

What are you trying to achieve?

In 1.46 the new Accounts icon only comes to life with a few extensions. See https://code.visualstudio.com/updates/v1_46#_accounts-management

It does more in the Insiders release.
