### ISSUE TITLE
[Request] Add command to Restart With Extensions Disabled

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#10028]
- VSCode Version: Code - Insiders 1.4.0-insider (e3758d2cdaae78082a08a45ae28ea1bed5f47e8c, 2016-07-29T18:41:58.915Z)
- OS Version: Windows_NT ia32 10.0.14393

As a matter of convenience, it would be nice to have an in-app ability to restart without extensions (instead of going to the command line and invoking `code --disable-extensions`).

**Comment by kieferrm** [comment]
You should't be required to start without extensions on a regular basis. It's intended for tracking down issues, i.e. debugging. For extension management, the extension viewlet is the place to go. However, I could see an extension picking this up and providing a command in the command palette.
