### ISSUE TITLE
Allow me to give a description to previewHtml command

### ISSUE THREAD

**Issue by ryu1kn** [Microsoft/vscode#10022]
It's great that we can now set a label for previewHtml command, but can we also set a description so that we can provide additional information while we keep the label short and focused?

I've come to want this feature while I'm developing my extension. Here's the issue I've created on my repository: https://github.com/ryu1kn/vscode-annotator/issues/5

Thank you!

cf. https://github.com/Microsoft/vscode/issues/2351

**Comment by mjbvz** [comment]
Closing as this feature request is over a year old and has not seen any further interest
