### ISSUE TITLE
Problem with VsCode icon in Arch Linux

### ISSUE THREAD

**Issue by arian999** [microsoft/vscode#100284]
- VSCode Version:  **1.46.0**
- OS Version:  **ArchLinux 5.7.2-arch1-1 KDE**

The main icon will not be displayed after I have downloaded and installed Visual Studio Code From the Arch Linux official repositories.
 
![Screenshot_20200616_164935](https://user-images.githubusercontent.com/51256681/84773266-67b33b80-aff1-11ea-814e-1c64e554cb04.png)

![Screenshot_20200616_153931](https://user-images.githubusercontent.com/51256681/84769803-b2ca5000-afeb-11ea-8be2-7b5653d2c114.png)

**Comment by gjsjohnmurray** [comment]
That looks like the 'Code - OSS' icon. What does Help\About report?

**Comment by arian-ir** [comment]
> That looks like the 'Code - OSS' icon. What does Help\About report?

I had this problem in xfce called 'Code-OSS'

**Comment by gjsjohnmurray** [comment]
Based on [this info](https://wiki.archlinux.org/index.php/Visual_Studio_Code#Installation) maybe install `visual-studio-code-bin` instead of `code`.

**Comment by arian-ir** [comment]
Why is this icon considered as the main VsCode icon in the GNU/linux?

**Comment by gjsjohnmurray** [comment]
Which distribution did you install?

**Comment by arian999** [comment]
ArchLinux and use code

**Comment by gjsjohnmurray** [comment]
As stated at https://wiki.archlinux.org/index.php/Visual_Studio_Code#Installation (linked to in a previous comment from me) the 'code' one contains the 'Code - OSS' version of VS Code. More info is at https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code

**Comment by lockwoodnd** [comment]
What do I have to do to get off of this list? Jperhaps I will just spam the list until I am blocked and unsubscribed. I already sent an unsubscribe email and it did nothing. I clicked at the buttomend of the email and it did nothing

**Comment by lockwoodnd** [comment]
L;fadjksflkajlsdkfjaslkdfjaoijhoikcnlk ajnsdeclkahjoiw4jhofiauwh0894rfiqu089=34fuhj09[ahwlkjhnbvalk’;sdejnflkashjekl’fdjhakl;’esdjflkasd
