### ISSUE TITLE
Add a tabular variables view for debugging

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#100205]
Today the VS Code debugger UI shows data (aka "variables") only in a tree viewer.
However, trees are not ideal for tabular data, e.g. arrays of records where each record has multiple properties.

To improve this, we will add a tabular view mode to the VARIABLES view.

**Comment by weinand** [comment]
The required work on a table widget is covered by https://github.com/microsoft/vscode/issues/99997

**Comment by isidorn** [comment]
Same as https://github.com/microsoft/vscode/issues/99997
Thus moving to August

**Comment by isidorn** [comment]
Due to the change of plans closing this as out of scope
