### ISSUE TITLE
Can you add In-editor shell command runner to vscode like in pycharm? -: Aryan

### ISSUE THREAD

**Issue by CodeWithAryann** [microsoft/vscode#100201]

**Comment by sandy081** [comment]
Can you please be clear about what is this In-editor shell command runner? Is it something specific to Python?

**Comment by CodeWithAryann** [comment]
In Visual Studio Code 2019  not Visual Studio Code the normal one . The program runs or the output comes in shell . That means that the output is in another window not the vs code or project windows . For eg - IN pycharm like this- The output window is attached to project window[
![Capture](https://user-images.githubusercontent.com/64773763/84758697-6b3fc600-afe3-11ea-992c-ae108c931d86.JPG)
](url)

**Comment by CodeWithAryann** [comment]
And pls add the option of viewing the whole folder  the project is in like in this, the left column is the folder in which our project is located .I am not able to see this option in vs code . If there is an option pls let me know.

**Comment by sandy081** [comment]
I see.. I would recommend to file the issue against Python extension so that they can go through it and see if they already support it or they can implement using the existing API or they can file issues against us.
