### ISSUE TITLE
panel.dropBackground and activityBar.dropBackground property is not allowed

### ISSUE THREAD

**Issue by shungo27** [microsoft/vscode#100239]
panel.dropBackground and activityBar.dropBackground property is not allowed. but there is a description on the Theme Color | Visual Studio Code Extension API(https://code.visualstudio.com/api/references/theme-color). Which one is correct?

- VSCode Version: 1.46.0
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. open name-color-theme.json
2. panel.dropBackground and activityBar.dropBackground is property is not allowed.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by eamodio** [comment]
They have been replaced by `panel.dropBorder` and `activityBar.dropBorder`. Hope that helps!
