### ISSUE TITLE
Add a Setting to Hide/Gray-Out Disabled Extensions' Actions

### ISSUE THREAD

**Issue by MBetters** [microsoft/vscode#100294]
Add a setting for `.vscode/settings.json` (or the user's global `settings.json`) that hides or grays out all the actions associated to disabled extensions. I think the UI / UX rules for this are worth discussing, but a couple rules that make sense to me would be:

- If a disabled extension has actions listed in any of the various right-click menus (Editor, Explorer, etc.), then hide those. This would declutter the right-click menus in workspaces that only require a few extensions to be enabled.
- If a disabled extension has actions listed in the Ctrl + Shift + P menu, keep those and gray them out to indicate they're "disabled." Maybe also add a little annotation on the right that says "disabled." I don't see any reason to fully hide disabled extensions' Ctrl + Shift + P actions because users usually just do a global search of the Ctrl + Shift + P menu anyway. However, it might also make sense to not show disabled extensions' Ctrl + Shift + P actions in the "recent list" that gets shown when you pull up the Ctrl + Shift + P menu, just to declutter it.

Thanks for the great IDE.

**Comment by sandy081** [comment]
We do not show actions of an extension that is disabled. Why do you want to have them shown ?

**Comment by MBetters** [comment]
I'd like to hide right-click actions, and possibly gray out or hide Ctrl+Shift+P actions for disabled extensions. For example, if I disable the PlatformIO extension, I still see both its right-click actions and its Ctrl+Shift+P actions, which clutters my VSCode UI.

**Comment by sandy081** [comment]
> For example, if I disable the PlatformIO extension, I still see both its right-click actions and its Ctrl+Shift+P actions, which clutters my VSCode UI.

This should not happen, can you please provide steps to repro?

**Comment by MBetters** [comment]
- Install the latest VSCode as well as the PlatformIO extension.
- Disable the PlatformIO extension.
- Right-click in the editor pane. The `PlatformIO: ...` extensions are still there.
- Ctrl + Shift + P then search `PlatformIO`. The `PlatformIO: ...` actions are still there.

**Comment by sandy081** [comment]
Did you get reload action that reloads the window after disabling the extension and did you reload the window?

**Comment by MBetters** [comment]
I did not get a reload action. However, I just did a Ctrl+Shift+P-->Reload Window and still PlatformIO actions are shown.

**Comment by sandy081** [comment]
Strange, I am not able to reproduce it. 

Can you please record a video or gif and share it?
