### ISSUE TITLE
Font Ligatures stopped working.

### ISSUE THREAD

**Issue by YashKarthik** [microsoft/vscode#100264]
- VSCode Version:1.46.0
- OS Version:Darwin x64 18.6.0

Steps to Reproduce:

1. Download and setup FiraCode-Retina

Does this issue occur when all extensions are disabled?: Yes

The font ligatures are woking perfectly in the **Jupyter notebooks**, but when I try to use them in the editor they don't work.

Ligatures and font settings:
```
 "editor.fontFamily": "FiraCode-Retina",
 "editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'zero', 'onum'",

```

**Comment by ArturoDent** [comment]
Just checking: is `FiraCode-Retina` the form of the font name given by your OS?  It is just `Fira Code Retina` on WinOS but I can't check on macOS

**Comment by YashKarthik** [comment]
yes on macOS its like that, 
I checked the official FiraCode repo too

**Comment by alexdima** [comment]
@YashKarthik Can you please try with  `"'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'zero', 'onum', 'calt', 'liga'"`?

**Comment by YashKarthik** [comment]
@alexdima perfect...thanks a lot
im closing this issue
