### ISSUE TITLE
Feature Request: Add Pin Tab

### ISSUE THREAD

**Issue by awatansa** [microsoft/vscode#100261]
Requesting to a Tab Pin Feature just like Edge Browser.

**Comment by kanlukasz** [comment]
It is already implemented. Have you checked the latest version?
https://code.visualstudio.com/updates/v1_46#_pin-tabs

**Comment by awatansa** [comment]
Got the feature by just updating 😄. Wow, Updated a product in just 7 mins!!! (⊙x⊙;)
