### ISSUE TITLE
gdb freezed

### ISSUE THREAD

**Issue by huanhexiao** [microsoft/vscode#100282]
Issue Type: <b>Bug</b>

I debug C++ with code, it freezes when jumping into some certian functions or snippets, which are traverses of a std::list. 
ifi switch such std::list to std::vector, it occurs the same problems.
If i set breakpoints outside such functions, everything is OK.
i also tried qt creator, everything is OK.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 4.15.0-106-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.67GB (0.11GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
mdmath|goe|2.5.1
latex-workshop|Jam|8.10.0
vscode-language-pack-zh-hans|MS-|1.46.3
python|ms-|2020.5.86806
cmake-tools|ms-|1.4.0
cpptools|ms-|0.28.3
cmake|twx|0.0.17
vscode-icons|vsc|10.1.1
markdown-all-in-one|yzh|3.0.0

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
Please file this issue against C++ extension.

**Comment by huanhexiao** [comment]
thx


发自我的iPhone

------------------ Original ------------------
