### ISSUE TITLE
Emmet expansion problem

### ISSUE THREAD

**Issue by EdFenner** [Microsoft/vscode#10029]
- VSCode Version:1.3.1
- OS Version:1011.6

Steps to Reproduce:

1. script:src
2. Tab to expand
3. Result is `script:<source src="" type="">`  instead of `<script src=""></script>`

**Comment by mrmlnc** [comment]
First, cool red panda :panda_face: 
Secondly, I can't reproduce your problem. Try running the editor without extensions (launch vscode with the `--disable-extensions` command line argument).

**Comment by EdFenner** [comment]
Good call - it is working. Guess something else is jumping in there and having it's way with things. Now to track it down. Thanks!

**Comment by mrmlnc** [comment]
@EdFenner, Any extensions that work with HTML.

**Comment by EdFenner** [comment]
In case anyone else has the problem. The extension that will cause this is:
HTML Snippets - Mohamed Abusaid - Full HTML tags including HTML5 Snippets
Works well, but messes up Emmet in this case.
