### ISSUE TITLE
VSCode opens twice when starting Workspace

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#100276]
#### Environment:
```
Version: 1.46.0 (system setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

#### Steps to Reproduce:

1. Run clear/empty VSCode instance
2. Run Menu → `File` → `Save Workspace As` and save it as `test.code-workspace`
3. Run Menu → `File` → `Add folder to Workspace` and add any folder
4. Run Menu → `File` → `Exit` to close VSCode
5. Start Workspace by directly clicking on the file `test.code-workspace`
6. Now VSCode has opened two instances

#### Video GIF for better understanding
![double](https://user-images.githubusercontent.com/30685349/84763143-0a58c380-afcc-11ea-865d-3624d418f288.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Wow, weird. Probably not a recent regression but maybe. Somehow we never deleted the untitled workspace. 

All in all weird that we first create an untitled workspace only to save it later, could maybe try to avoid that.

//cc @sandy081

**Comment by sandy081** [comment]
Not exactly.
