### ISSUE TITLE
Integrated Terminal : Allow Renaming sessions

### ISSUE THREAD

**Issue by geevi** [Microsoft/vscode#10023]
Please add a feature to rename sessions in the integrated terminal.
Usually one opens multiple terminal sessions using the same command like ssh. Then all these sessions are called ssh in the dropdown. Please allow to rename the session, so that its easy to choose.

**Comment by Tyriar** [comment]
@stevencl @bgashler1 thoughts on this from UX side? I was thinking something like this would be quite cumbersome as you would have to do it whenever you launch a new terminal instance.

**Comment by stevencl** [comment]
I would expect it would be optional. Just a quick thought but could you right click on the dropdown and choose a rename command?

**Comment by JostCrow** [comment]
I would like to see a new button near the dropdown. Something like my screenshot. Also a command when you are in the terminal like ctrl+shift+r or f2 would be nice. 

button example:
![screenshot from 2016-08-04 10 22 23](https://cloud.githubusercontent.com/assets/390575/17395351/4ecd96a0-5a2e-11e6-92a9-5aea920e1c5c.png)

**Comment by stevencl** [comment]
If the goal is to distinguish between different terminals, how about just automatically showing the last command run in each terminal? That way the user wouldn't even have to bother renaming if they just want to be bale to distinguish between multiple terminals (assuming that they aren't running the same command in every terminal).

If we have to expose an action, right click probably isn't the best approach as it is a little unusual to right click on a drop down. Thinking of this like a regular combobox though, perhaps just single clicking inside the drop down could highlight the text which the user could then replace.

I'm reluctant to add more buttons as that just adds weight and takes up space. I'd definitely expect that we should have some keyboard bindings for it.

**Comment by JostCrow** [comment]
For me it is mainly to distinguish the different terminals. So for me personally showing the last ran command is also fine.

**Comment by Tyriar** [comment]
Right clicking the terminal could also be an option, there's already a context menu there.

Also another piece of information I feel is missing is the current number of terminals, integrating everything into the dropdown could get messy, eg. "2/3: /bin/bash (gulp watch)"

**Comment by evandigby** [comment]
For UX I would like:

- If you hover over session name in dropdown (or new edit box beside the dropdown or beside "TERMINAL") the mouse pointer turns to text cursor. You can select and rename the session easily 
- Key binding for a command to rename which automatically moves focus / cursor to a fully selected name so you can immediately type a new one (or modify the selection to augment the existing name). 
- In either case enter or some other key binding "saves" and returns focus and cursor to the terminal prompt

**Comment by evandigby** [comment]
With the "last run command" option would you display the full command line or just the command? 

Particularly when using Go, there are good reasons to have multiple terminals using the same "command" since many Go tools start with "go" ("go build", "go test", "go tool pprof", etc...). I'll often have an active profiling session open in one terminal while running builds / tests in another session. Unfortunately they're both the same "command" ("go").

I would say displaying the last run command is useful, but doesn't satisfy the same requirements as explicitly allowing renaming sessions. I would treat it as separate feature request to this one.

**Comment by rjoshi31** [comment]
Going by the suggestions made, I believe there are two points this RFE should consider.

1. [Default Mode] The dropdown should always display last command run (truncated). Hovering over the dropdown can display the full text.

2. [Custom Mode] In case the user wants a custom name, they can right click the dropdown to make inline edits. Thereafter, the new input will be set as the default for that terminal.

Much needed!

**Comment by stevencl** [comment]
In addition to the context menu (which I still think is a bit unusual) I was thinking of a design similar to this experience

![dropdown](https://cloud.githubusercontent.com/assets/1704059/17482903/afea0522-5d7b-11e6-9c09-8b2c9ee11c26.gif)

With the addition that I wouldn't make the text area editable by default. Perhaps guard against undesired edits by making the user click inside the area once to position a cursor at the end.

Another alternative design is that there is an <Rename...> entry at the bottom of the dropdown. If the user chooses this, they see a dialog box that displays the list of terminals. The user can select one, press a rename button, then type in the new name. It's quite cumbersome compared to the others but it puts the functionality out of the way meaning that people will be much less likely to rename a terminal.

**Comment by Tyriar** [comment]
@stevencl I was speaking with @bgashler1 the other day about custom dropdowns for the panel `x` icon discussion. I don't think we do custom dropdowns currently which would be necessary for something like this, custom dropdowns are a decent chunk of effort to get right (fitting in with each OS, ensuring accessibility, etc.).

This also may not work if we want to put buttons inside the dropdown? Something to consider.

**Comment by stevencl** [comment]
OK, how about we just start by automatically showing the last command run in each terminal? That seems to be the least we can do to help distinguish between the different terminals without requiring us to create custom controls to rename terminals.

**Comment by Tyriar** [comment]
Not sure if it's clear, but right now on platforms other than Windows it will show the currently running program, not just the shell name, So originally it's `/bin/bash`, but when I run `gulp watch` the label is changed to `gulp` as that's the active program. Once `gulp watch` exits it will go back to `/bin/bash` since that is now the active program.

There are some issues with trying to amend this string with the "last command run" as I don't think it's even possible to extract that information in a reasonable way given the array of shells that could be getting used and their syntax. Also commands are not composed and then sent to the shell, each *keystroke* is converted into an ANSI key sequence and sent to the terminal at that time, depending on the key stroke the output on the actual terminal could be the key, it could be ignored, it could output garbage. There isn't a reliable way as far as I'm aware to get the command that is run from the terminal, only the last *program* run.

Due to technical constraints on Windows it is always `cmd.exe` or whatever the shell name is, this discussion likely wouldn't be able to affect the Windows situation.

**Comment by evandigby** [comment]
@stevencl @Tyriar I still think it's worth splitting "last run command" and "renaming the window" into two separate requests, even if the latter gets shelved due to the UX complexity. 

I think there is value in both, but I don't believe last run command would meet requirements set out by the OP (@geevi correct me if I'm wrong!). It definitely wouldn't meet the requirements of the feature request that I was going to fill out before my duplicate search lead me to this one.

**Comment by stevencl** [comment]
OK, in that case lets go with the other suggestion I made:

Another alternative design is that there is an entry at the bottom of the dropdown. If the user chooses this, they see a dialog box that displays the list of terminals. The user can select one, press a rename button, then type in the new name. It's quite cumbersome compared to the others but it puts the functionality out of the way meaning that people will be much less likely to rename a terminal

**Comment by evandigby** [comment]
Another option could be to have a button and key binding that brings up a dialog similar to the find/replace dialog (and hopefully reuse the code) in the top right with the current window name, allowing you to rename.

**Comment by chevex** [comment]
Adding support for this feature. Googled to see if there was an option after I opened five terminal sessions (Windows 10) and couldn't remember what was running in each session. They all say "cmd.exe" which doesn't help at all.

**Comment by vivekvenkatesh** [comment]
+1 for this feature request. Also,  if we are working over SSH, just showing the last command run is not helpful. Hence it would be good to have a custom renaming.

**Comment by kiliwalk** [comment]
+1 custom renaming 
and custom order

**Comment by zephrxx** [comment]
+1

**Comment by Tyriar** [comment]
Update on this:

- Currently it's possible to name sessions when they are created through the API, so an extension could be made to largely solve this.
- Another area I'm looking into here is to make the dynamic name smarter through potential features like https://github.com/Microsoft/vscode/issues/20676 or https://github.com/sourcelair/xterm.js/issues/576

**Comment by Tyriar** [comment]
Opening this up to PRs, here's what we need:

- A new command registered `workbench.action.terminal.rename` (see https://github.com/Microsoft/vscode/blob/ed91b067e075457791e5e523d25e110c57650a4b/src/vs/workbench/parts/terminal/electron-browser/terminal.contribution.ts#L209)
- The command will rename the currently active terminal instance, regardless if it is currently visible or not. You will need to get the active instance from `TerminalService`, add support for changing the terminal's name on `TerminalInstance` and ensure the `_onTitleChanged` event emitter gets triggered so the change is picked up by the panel and the dropdown is changed.
- When the name is changed it should behave like when the title is set by the extension API and not change afterwards even if the terminal process tells it to change. So unregistering this will be required: https://github.com/Microsoft/vscode/blob/ed91b067e075457791e5e523d25e110c57650a4b/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L470

**Comment by jammerware** [comment]
Hey @Tyriar, I'm taking a look at this one. I've modified the `TerminalInstance` to support renaming, defined a new `Action` in `terminalActions` to expose it, and (I think) done the de-registration of the terminal process message handler for title changes. Do I also need to figure out how to present the UI for the user to enter the name of the terminal, or is the intent that I just PR this stuff and you guys work that out?

Thanks much!

**Comment by Tyriar** [comment]
@jammerware the command `workbench.action.terminal.rename` should present a quick open that lets the user enter the new name. To do that I think you want to use this https://github.com/Microsoft/vscode/blob/f1a8632778e4574cf07b3cb162aa998e4a51aebc/src/vs/platform/quickOpen/common/quickOpen.ts#L136

**Comment by Tyriar** [comment]
Should land in Insiders tomorrow thanks to @jammerware :+1:

**Comment by winuxue** [comment]
waiting for this feature in the stable version

**Comment by zephrxx** [comment]
Can it use the console caption as the default session name?

**Comment by Tyriar** [comment]
@zephrxx what's the console saption?

**Comment by zephrxx** [comment]
By caption I mean the highlighted part in the screen shot below.
![capture](https://user-images.githubusercontent.com/5190347/28133860-18d448ca-66f6-11e7-8987-04ad87b7696b.PNG)

**Comment by Tyriar** [comment]
Ah, well I don't think we have access to that and also it would be too long for the dropdown. In https://github.com/Microsoft/vscode/issues/30152 we're looking into getting Windows closer to the Linux/macOS experience which shows the active program/shell:

- If you launch powershell it will say "powershell"
- If you launch cmd *inside* powershell, it will say "cmd"
- If you launch npm install *inside* powershell, it will say "node"

**Comment by thiagoufg** [comment]
Just press CTRL+SHIFT+P, then type TERMINAL RENAME, enter a name and press ENTER. :-D
