### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by guillermoroblesjr** [microsoft/vscode#100221]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Alert message showing at bottom of VS Code

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 12, 8|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.1.0
codesnap|adp|1.0.27
vscode-coverage-highlighter|bra|1.0.3
vscode-jq|dan|1.2.0
vscode-eslint|dba|2.1.5
javascript-ejs-support|Dig|1.3.1
gitlens|eam|10.2.2
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.0.0
gc-excelviewer|Gra|2.1.35
asciidecorator|hel|0.2.0
vscode-styled-components|jpo|0.0.29
rainbow-csv|mec|1.7.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.2.1
vscode-typescript-tslint-plugin|ms-|1.2.3
sqltools|mtx|0.22.7
code-settings-sync|Sha|3.4.3

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also when this happens, the error notification should include 'report issue' button. Click that to get the  error stack

/needsMoreInfo
