### ISSUE TITLE
1.46 brings back "git fatal error: file is outside directory"

### ISSUE THREAD

**Issue by strowk** [microsoft/vscode#100226]
- VSCode Version: 1.46.0
- OS Version: Windows 10

Steps to Reproduce:

Same as in https://github.com/microsoft/vscode/issues/89373, except the version is latest

Does this issue occur when all extensions are disabled?: Yes

I see that fix https://github.com/microsoft/vscode/commit/830992d818cbf1a09e744f0ee475c542763bdfff
does not work, because "Output" shows
```
git add -A -- c:\vms\deb0\git-compose-eyodf\git-compose\internal\cmd\gico.go
```
"C:" here is lower case. The problem appeared recently after the update.

**Comment by gjsjohnmurray** [comment]
Others have reported that updating their local Git version resolves this. What version are you using? Are you able to update?

**Comment by strowk** [comment]
Git is of "git version 2.12.0.windows.1", but I'm not sure if that's the git problem. 
It seems like git does not like lowercase drive names (I checked that specifically) and I think the mentioned fix was lost between versions. 

That method `add` has changed between
https://github.com/microsoft/vscode/blame/1.42.0/extensions/git/src/git.ts#L1159
and 
https://github.com/microsoft/vscode/blame/1.46.0/extensions/git/src/git.ts#L1217

This block changed
from
``` ts
		if (paths && paths.length) {
			args.push.apply(args, paths.map(sanitizePath));
		} else {
			args.push('.');
		}
```

to
``` ts
		if (paths && paths.length) {
			for (const chunk of splitInChunks(paths, MAX_CLI_LENGTH)) {
				await this.run([...args, '--', ...chunk]);
			}
		} else {
			await this.run([...args, '--', '.']);
		}
```

The first one passes arguments through `sanitizePath`, second one does not look so. 
This commit looks like the one, that removed call to `sanitizePath`
https://github.com/microsoft/vscode/commit/93b50c021106ed6a4712eb1c93a0baed98f64353

**Comment by merandall** [comment]
It is working in 1.43.0 for me, but started happening after that 1.44,2 - 1.46.0. I am using Windows 10, git version 2.25.0.windows.1. I will update git to the latest version and try again and let you know if that worked.

**Comment by merandall** [comment]
Upgrading git to 2.27.0.windows.1 did seem to resolve the issue for me. I updated. added and deleted files and all three scenarios worked.

**Comment by joaomoreno** [comment]
@strowk Please update Git to 2.27 and let us know how that goes.

**Comment by Robominister** [comment]
After upgrading to git 2.27, I can confirm that for me, the issue was resolved.
