### ISSUE TITLE
Environment variable does not work on launch file

### ISSUE THREAD

**Issue by danielhue** [microsoft/vscode#100258]
- VSCode Version: 1.46.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. set environment variable on settings.json
"terminal.integrated.env.linux": {
        "TARGET_IP": "11.0.1.1"
 },
2. The environment variable does not work at launch.json like below
"miDebuggerServerAddress": "${env:TARGET_IP}:3000"          
The value is empty when running launch.json. How can I set environment variable for launch file?   

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
Environment variables like `${env:TARGET_IP}` are read from VS Code's environment (the environment that existed when VS Code was launched).

Environment variables that are configured for the integrated terminal with the `terminal.integrated.env.linux` setting are set for integrated terminals launched from VS Code.
These variables are not available via the `${env:XXX}`.
