### ISSUE TITLE
Find in Files reports ENOENT issue with rg.exe

### ISSUE THREAD

**Issue by dmayo77** [microsoft/vscode#100337]
- VSCode Version: 1.46.0    commit: a5d1cc28bb
- OS Version: Windows 10

Steps to Reproduce:

1. Search for something using the Find in Files (CTRL+SHIFT+F)
2. Type in something to search
3. Enter a file path rather than a file directory 

Click search

Would be better if an error was reported "cannot find in files in a specific file. Try a folder path instead of a file path" rather than a cryptic error 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
>     3\. Enter a file path rather than a file directory

Where do you enter this?

Where is the ENOENT error reported?

Maybe paste screenshot(s).

**Comment by roblourens** [comment]
I think I understand it, this is basically https://github.com/microsoft/vscode/issues/20530
