### ISSUE TITLE
Buttons trigger while window is unfocused

### ISSUE THREAD

**Issue by declanrg** [microsoft/vscode#100363]
- vscode Version: 1.46.0
- OS Version: macOS 10.15.5

Steps to Reproduce:

1. Unfocus vscode window
2. Click on any button or action in the vscode sidebar

Expected behaviour:
Refocusing to vscode application should not trigger any buttons or actions

The vscode application window will perform a selected action after clicking to refocus to its window. This can be frustrating at times as I'd expect to just bring the window to front and not unintentionally open a new file or scroll halfway down the page in the sidebar. Most applications with sidebars such as Spotify and Finder simply return to the window without interacting with its interface.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Configurable via `window.clickThroughInactive`
