### ISSUE TITLE
Use the same "sync" terminology across the product and docs

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100315]
Docs still say `Settings Sync`:
![image](https://user-images.githubusercontent.com/35271042/84810628-75040200-afc0-11ea-8ac5-aca2473f139c.png)

Everywhere else in the app it's referenced as `Preference Sync`:
![image](https://user-images.githubusercontent.com/35271042/84810664-84834b00-afc0-11ea-9a95-15320ad40d5f.png)

![image](https://user-images.githubusercontent.com/35271042/84810720-949b2a80-afc0-11ea-9657-c2a9085564d2.png)

![image](https://user-images.githubusercontent.com/35271042/84810725-95cc5780-afc0-11ea-8587-2b74fd90b90d.png)

**Comment by gregvanl** [comment]
There have been discussions around the feature name and we're continuing to use "Settings Sync" since it has taken hold with the community.
We may revisit this later.

**Comment by misolori** [comment]
@gregvanl if the plan is to use "Settings Sync" then we need an issue to track updating that in the product because right now it is inconsistent.

**Comment by misolori** [comment]
It sounds like there is an ongoing discussion on what terms to use. Whichever one we go with, we should make it consistent in the product and docs. Will update this issue to reflect that.

**Comment by Tyriar** [comment]
I've never been a fan of preferences sync as it doesn't really roll off the tongue, I prefer "Settings Sync" over that.

I think I like even more calling the feature "Sync" and then using the word preferences or settings just in the entry context item, for example "Sync your settings", and then everywhere else it's called simply "Sync".

**Comment by sandy081** [comment]
Agreed **Preferences Sync** is not a good name but it represents the functionality well. We are representing Settings, Keybindings, Extensions and Snippets. 

**Settings Sync** is catchy term but not sure if represents the complete functionality.

We started with **Sync** but this got feedback that it is missing the context that what is it syncing.

**Comment by sandy081** [comment]
@microsoft/vscode Please provide your opinion about naming this in the product. Here are the options

1. **Settings Sync**
2. **Sync**
3. **Preferences Sync**

It would be great if you have better suggestions.

**Comment by bpasero** [comment]
I like `Sync` because we also sync extensions and UI state, not just settings.

**Comment by gregvanl** [comment]
I prefer `Settings Sync` for context even if it isn't completely accurate. Windows settings uses similar phrasing for the various preferences (theme, language, settings):

![image](https://user-images.githubusercontent.com/12818376/85599653-8f159400-b601-11ea-9024-191ae1840b6c.png)

**Comment by Chuxel** [comment]
Yeah the danger with just "sync" is that this can imply code sync'ing particularly in the context of the Remote - * extensions.  We have feature requests to sync code from local to remote, so I think we need to be specific on exactly what is being sync'd.  "Settings Sync" seems like the closest to me as well.

Conceptually, the list of installed extensions and your UI "preferences" are variations of the idea of a VS Code setting. To us they are separate and distinct, but I'm not sure a user would really say that.  

Preferences doesn't feel right either IMHO, the only other one we could potentially use is "Configuration Sync" which is beyond just "preferences" and doesn't directly evoke the `settings.json` in one's mind.  Not sure if that's already been considered.

**Comment by Tyriar** [comment]
> I prefer Settings Sync for context even if it isn't completely accurate.

> Yeah the danger with just "sync" is that this can imply code sync'ing particularly in the context of the Remote - * extensions.

This is the reason I suggested that the _entry points_ elaborate a little on what's synced, eg. "Sync your settings", "Sync your preferences", and everything else just refers to it as "Sync" as it's already been established via the entry label plus this dialog:

![image](https://user-images.githubusercontent.com/2193314/85608520-ff281800-b609-11ea-91aa-91891562b348.png)

**Comment by chrisdias** [comment]
as others have said, my feeling is that "settings sync" is what everyone can identify with, even if it's not accurate.

**Comment by eamodio** [comment]
My first choice is still _Sync_ since its clear and simple, but I also don't mind _Settings Sync_ even as @chrisdias says it isn't completely accurate.

**Comment by ItalyPaleAle** [comment]
From a marketing perspective, I agree that *Settings sync* (or *Preferences sync*) is the most descriptive and clearer to communicate. It also provides an answer to the requested ability to synchronize settings and preferences.

*Sync* could also cause some confusion with the "synchronize" button at the bottom which is about checking for changes in the Git remote.

Alternatively, may I propose *Profile sync*?

**Comment by sandy081** [comment]
I too agree with @chrisdias that we have been calling and representing this as **Settings Sync** everywhere like in discussions or whenever we have to call out the feature.

So, I would change it to **Settings Sync** instead of **Preferences Sync**
