### ISSUE TITLE
Show Synced Data shows no synced machine

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100317]
When turning sync on where I previously used a synced machines, you are prompted with this dialog:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/84810999-04111a00-afc1-11ea-917b-d29220517e94.png">

However, when I navigate to the synced machines list, there are no additional synced machines:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/84811102-3753a900-afc1-11ea-8e03-de0a5e0adc59.png">

Which is confusing when it shows there are no synced machines.

**Comment by sandy081** [comment]
Looks like you have very old data where we do not support syncing machines and showing machine information along with the request. Since no info is available. synced machines are not shown.
