### ISSUE TITLE
Suggestion Widget appears to eagerly

### ISSUE THREAD

**Issue by jseanxu** [Microsoft/vscode#1003]
I have custom key bindings like these
```
{ "key": ";",  "command": "^acceptSelectedSuggestion", "when": "editorTextFocus && suggestWidgetVisible" },
{ "key": "space",  "command": "^acceptSelectedSuggestion", "when": "editorTextFocus && suggestWidgetVisible" },
...
```
to mimic how autocomplete works in the full VS, however, this makes typing something like
```
var foo = 1;
```
difficult in JavaScript/TypeScript because when typing `1`, the suggestion widget eagerly appears with `Int16Array` and hitting `;` autcompletes to it and you end up with
```
var foo = Int16Array;
```

**Comment by joaomoreno** [comment]
Numbers seem to be words...

**Comment by egamma** [comment]
@jrieken for this scenario it would make sense when 7x24 intellisense only pops-up when there is a prefix match.

**Comment by jrieken** [comment]
Yes, if would be even more strict and say the current word never matching anything if its just numbers

**Comment by jseanxu** [comment]
Can we get a config hook to make it only prefix match?

**Comment by dbaeumer** [comment]
There is not to much I can do in TS land since the tsserver gets ask for code completion and provides the proper items. @joaomoreno I assign to you since it is more a code complete request issue.

**Comment by joaomoreno** [comment]
@jrieken this is the one we were just talking about

**Comment by jrieken** [comment]
yeah, related to #752

**Comment by jrieken** [comment]
Until we improve the API we don't automatically show suggestion when the current work is just a number.
