### ISSUE TITLE
Window size spreads out of monitor

### ISSUE THREAD

**Issue by KosukeMizuno** [microsoft/vscode#100377]
![screenshot](https://user-images.githubusercontent.com/43668684/84889693-3d867a00-b0d4-11ea-9b89-a7375827df82.png)

When I maximize vscode's window on the secondary display, the window spreads out of the secondary display a little.
The status bar of vscode is hidden below the taskbar.
The left edge of the vscode window spreads on the primary display, but clicking the edge makes another window in the primary display get focused.

This doesn't occur if I maximize on the primary display.

Steps to Reproduce:

1. Maximize vscode's window on the secondary display

Environment:

- VSCode Version: 1.46.0
- OS Version: Windows 10 Pro 2004

- Monitors:
	- primary display: Dell XPS 15 7590 (3840x2160)
	- secondary display: iiyama ProLite XB2472HD (1980x1080)

![image](https://user-images.githubusercontent.com/43668684/84888848-e2a05300-b0d2-11ea-8dcb-809800488612.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
#100370 looks similar

**Comment by IllusionMH** [comment]
Looks like more drastic version of #85310

**Comment by KosukeMizuno** [comment]
Window size looks appropriately with native title bar.
Thank you.

I noticed that the title bar doesn't obey my color theme.
I have set it dark (See attached image).
![image](https://user-images.githubusercontent.com/43668684/84904224-0622c800-b0ea-11ea-902b-38867146768b.png)
In the screenshot, title bars of explorer look dark, but that of vscode looks white when vscode window doesn't have focus.
When vscode has focus, it has a dark title bar.
![image](https://user-images.githubusercontent.com/43668684/84904444-44b88280-b0ea-11ea-88ff-c3945531a486.png)
 
Is there a way to make it dark ?

**Comment by IllusionMH** [comment]
> Is there a way to make it dark ?

This is Windows behavior and I doubt that it can be controlled from app

**Comment by jofultz** [comment]
> Looks like more drastic version of #85310
> 
> Do you see this problem if you set `"window.titleBarStyle": "native"`?

I have the same issue.  When I changed to "native" it fixed the status bar and it now renders above the windows taskbar.  So, it seems the current options are native title bar or half-hidden status bar :)

Any chance this is something that can be correct so that we may have custom title bar and fully visible taskbar?

Also, FWIW, this only happens on my external monitors.  It renders properly on my laptop's built-in screen.

**Comment by KosukeMizuno** [comment]
It may be from electron, so I write their versions.

> vscode: 1.46.0 (user setup)
> commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
> date: 2020-06-10T09:03:20.462Z
> Electron: 7.3.1
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.19041

**Comment by deepak1556** [comment]
Yes the issue stems from electron implementation of custom titlebar, I will merge this issue to #85310 . You can follow that for updates, thanks!
