### ISSUE TITLE
Electron crash caused by integration test on Windows

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#100321]
Crash reported from https://dev.azure.com/vscode/a4cdce18-a05c-4bb8-9476-5d07e63bfd76/_build/results?buildId=46280 and I followed https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports to generate the stack

[1_symbolicated_stack.txt](https://github.com/microsoft/vscode/files/4788517/ce_symbolicated_stack.txt)
[2_symbolicated_stack.txt](https://github.com/microsoft/vscode/files/4788518/fc_symbolicated_stack.txt)

**Comment by deepak1556** [comment]
The second trace is the same as https://github.com/microsoft/vscode/issues/99408

The first one is new, out-of-bounds exception from `std::vector`. I think its a one time issue, lets see if that happens again.

**Comment by bpasero** [comment]
@deepak1556 in https://dev.azure.com/vscode/VSCode/_build/results?buildId=46492&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=d494b5db-eef8-5766-984e-01186010c86f I see another crash, not sure you are aware. It is on Windows and has a dump attached.

Doing the symbolification:

[crash1.txt](https://github.com/microsoft/vscode/files/4792292/crash1.txt)
[crash2.txt](https://github.com/microsoft/vscode/files/4792293/crash2.txt)

Seems to be webview related:

```
 0  Code - OSS.exe!content::WebContentsImpl::AttachInnerWebContents(std::unique_ptr<content::WebContents,std::default_delete<content::WebContents> >,content::RenderFrameHost *) [web_contents_impl.cc : 1883 + 0x0]
```

**Comment by bpasero** [comment]
And on macOS too it seems:

[crash-macos.txt](https://github.com/microsoft/vscode/files/4793594/crash-macos.txt)

**Comment by deepak1556** [comment]
@bpasero yup they are both https://github.com/microsoft/vscode/issues/99408 , crash always seems to happen under notebook API tests, would be great to narrow down the problematic test.

**Comment by rebornix** [comment]
After stress testing the notebook by opening/closing notebook 200 times, I found that he webview crashed in two reasons.

The first one is we try to update the content of the webview when the webview is being disposed. This usually happens when we close a dirty file and then two async tasks run in unpredictable sequence: reverting the document (which triggers rerendering of the webview) and closing the editor (which disposes all event listeners and webview). The root cause is we can't dispose/stop a promise chain. Tried my best to fix this set of problems by eagerly checking if a notebook/webview is being closed while handling all kinds of promises/events. It avoided quite a ton of crashes. ✅ 

The second one is, well, I can't explain. It happens often when removing a webview element from the DOM tree. A typical code path before the process crashes is

* Notebook Editor close
* `NotebookEditorWidget#dispose`
* `BackLayerWebView#dispose`
* `BaseWebview#dispose`
  * remove electron webview element from DOM tree 

https://github.com/microsoft/vscode/blob/cd3a3ea6faa9d83dae1b706cfe1aaa2dbcaf3411/src/vs/workbench/contrib/webview/browser/baseWebviewElement.ts#L167

I kind of have a stable reproduce which 

* open notebook A
* save, close it
* open notebook B
* save, close it
* repeat 200 times

and it then will crash after waiting for a while. Users usually don't notice this as they don't open/close notebooks like this but we have 25 integration tests which open/close notebooks around 50 times within a short time, thus it often crashes the process and abort the integration tests. @deepak1556 let's meet next week and look into this together.

**Comment by deepak1556** [comment]
We are no longer affected by this due to iframe transition on desktop.
