### ISSUE TITLE
The terminal process terminated with exit code: 4294901760

### ISSUE THREAD

**Issue by antonioborondo** [microsoft/vscode#100366]
- VSCode Version: 1.46.0 (user setup)
- OS Version: Microsoft Windows 10 Enterprise 10.0.17763

Steps to Reproduce:

1. Open Visual Studio Code
2. Click on View > Terminal
3. Get notification error "The terminal process terminated with exit code: 4294901760"

Does this issue occur when all extensions are disabled?: Yes

Launch Visual Studio Code with the following command:
```
code --log trace
```
Shows the following message when the notification error appears:
```
(node:18408) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
```

**Comment by antonioborondo** [comment]
https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

> If you're on Windows 10 1809 (build 17763) or below, the issue is related to the legacy "winpty" backend. Upgrading to Windows 1903 (build 18362) will move you onto the new "conpty" backend that is built by Microsoft and could fix your problem.

It might be related.

**Comment by Tyriar** [comment]
@antonioborondo yep you would be on the old backend that had a bunch of issues that we couldn't fix, it could also be anti-virus software blocking it so you could try excluding the paths called out in https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch#_error-connectnamedpipe-failed-windows-error-232

Also, I'm really glad you found the troubleshooting page I just created 😄

**Comment by Shoeb456** [comment]
I have a issu terminated with exit code 4294901760 ,while run the program ...pless help me to solve the problem!

**Comment by kodmanyagha** [comment]
I think I found the problem. When you push `CTRL+D` shortcut sometimes I get same error notification. In normal terminal this shortcut means "quit", but same shortcut exist in vscode too. The solution: remove this shortcut from vscode. Search this in shortcut list: `kill terminal` and remove unnecessary shortcut from there. My current status is like that:

![image](https://user-images.githubusercontent.com/3948692/224152668-26e0d92b-2129-4b32-9a31-7da93bd16518.png)
