### ISSUE TITLE
Allow support for SQL code in Jupyter notebooks like in Azure Data Studio

### ISSUE THREAD

**Issue by pacorreia** [microsoft/vscode#100390]
As multi platform developer and also presenter, I will find  useful to have the jupyter notebook support in VS Code as it exists in Azure Data Studio for running SQL code against a database.

This can be acomplished by adding a SQL kernel to existing Jupyter notebook built in VS Code.

Example:
![image](https://user-images.githubusercontent.com/54323159/84907043-9e995800-b0aa-11ea-8297-e51ab5a25701.png)

Without this I'm always jumping between VS Code and Azure Data Studio, in the future you could merge both, big benefit to be honest.

**Comment by rebornix** [comment]
Right now the Jupyter notebook feature is provided by the Python extension, please file issue against them and I think they have plans for supporting multi languages in their notebook.
