### ISSUE TITLE
Rename View & Sort 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#100394]
Currently there is a `View & Sort` menu entry in the SCM viewlet.
Since we plan to introduce a Views submenu (more details https://github.com/microsoft/vscode/issues/98614) I suggest that we rename this entry to avoid confusion since they both start similar.

Here are some suggestions:
* Presentation
* Layout
* Sort and View

fyi @joaomoreno

![Screenshot 2020-06-17 at 16 23 44](https://user-images.githubusercontent.com/1926584/84910317-06ee3680-b0b7-11ea-828e-0bc172e9e3e8.png)

**Comment by joaomoreno** [comment]
@lszomoru My suggestion is simply `View`.

**Comment by isidorn** [comment]
@joaomoreno that would not work imho, since we will add a menu called `Views`.

**Comment by lszomoru** [comment]
@isidorn, have we actually heard feedback from customers that the `Views` and `View & Sort` menus are causing confusion? Please correct me if I am wrong but these two menus appear at different levels - `Views` appears in the viewlet toolbar, while the `View and Sort` appears in the SCM view's toolbar. I would suggest that we keep things as is, and make changes only if we hear customer feedback that this is causing confusion.

**Comment by isidorn** [comment]
@lszomoru no we did not hear feedback because the `Views` thing is only in insiders for 2 days and because by default you do not see it in the SCM. It is only shown when there is more than 1 view.

I am fine with leaving the current naming since by default users will not see Views in the SCM viewlet.
So feel free to do what you think is best.

**Comment by lszomoru** [comment]
Closing this for now. Will reopen if needed based on customer feedback.
