### ISSUE TITLE
Unknown URL scheme when using vscode-resource scheme in extension webview

### ISSUE THREAD

**Issue by tetchel** [microsoft/vscode#100325]
- VSCode Version: 1.46.0 `a5d1cc28`
- OS Version: MacOS Catalina 10.15.5

Steps to Reproduce:

Intermittently, my Webviews fail to load any resources (css, images) using the `vscode-resource` scheme.
![image](https://user-images.githubusercontent.com/8888438/84817311-b9a09500-afe2-11ea-9e54-7e45488b7baa.png)

An example URL is 
```
vscode-resource://file///Users/tim/programs/codewind-vscode/dev/res/css/common.css
```

The testing team has seen this outside of Extension Development Host mode too, so it's not caused by that.

Closing the webview and re-opening it fixes it. The URL is the same when the webview works.

Does this issue occur when all extensions are disabled?: 
Couldn't reproduce, but the issue is intermittent

**Comment by mjbvz** [comment]
Seems like a duplicate of #89038

Can you please test the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) to see if this has been fixed for you

**Comment by tetchel** [comment]
It is a dupicate
