### ISSUE TITLE
Mac Very slow Sometimes

### ISSUE THREAD

**Issue by crazed-developer** [microsoft/vscode#100357]
Issue Type: <b>Bug</b>

Often my VS Code is very slow, however I'm able to often "fix" it by doing this procedure:

Open: Help -> Process Explorer

Right click: gpu-process -> Select Force Kill Process

I do this a few times (Often there are Two of these processes) and sometimes i have to kill 3-4 times.. 

Then everything works very swiftly.

My Mac: 
MacBook Pro (15-inch, 2018)
2,9 GHz 6-Core Intel Core i9, 32 GB 2400 MHz DDR4
Radeon Pro 560X 4 GB
Intel UHD Graphics 630 1536 MB
OS: Catalina / 10.15.5 (19F101)

I've searched this issue a few times, and often do not find anything usefull. I hope this can maybe help find this bug.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|32.00GB (16.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
alpine-js-intellisense|adr|1.2.0
vscode-tailwindcss|bra|0.3.1
vscode-docker|ms-|1.3.0
mssql|ms-|1.9.0
payara-vscode|Pay|0.0.3
java|red|0.62.0
vscode-quarkus|red|1.5.0
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0

</details>

**Comment by westmark** [comment]
Since the latest update, I have also experienced VS Code becoming significantly slower. The intellisense import popup would take ages to appear, and fixed linting errors took a good 3-4 seconds to be cleared. 

But, after killing the process like @crazed-developer described above these issues went away immediately. My setup is almost exactly the same as the above.

**Comment by rebornix** [comment]
@crazed-developer  @westmark can you follow our wiki https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu to provide some more information to help troubleshoot? 

Also, if you are seeing slowness from extensions, please follow https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions to provide more details as well.
