### ISSUE TITLE
Saving new PHP files with extension ".inc" results in file with extension ".inc.ctp"

### ISSUE THREAD

**Issue by jimbonator** [microsoft/vscode#100332]
Issue Type: <b>Bug</b>

When saving a new PHP file with the extension ".inc" (as in `Foo.inc`), the final file name has a ".ctp" extension added (resulting in `Foo.inc.ctp`).

The Save As... dialog shows the name to be saved as `Foo.inc` and the Format dropdown shows PHP.

I've tried saving these files with the ".php" extension, and the problem does not occur.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.24GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by bpasero** [comment]
I think this is just standard native macOS behaviour if a file type is selected. I for example always have to use the terminal to properly name a file, the save dialog never works.

I suggest to report this to Apple.

**Comment by jimbonator** [comment]
Perhaps, but I can say with confidence this wasn't the behavior before the update before today's (June 22).  And I don't see this behavior with other file extensions.

I'll keep investigating.

**Comment by bpasero** [comment]
I wonder if this is related to https://github.com/microsoft/vscode/issues/100241 where I pushed a fix. To proof that theory you can check if you can still reproduce from the insider build we release today.

**Comment by jimbonator** [comment]
Alas, this doesn't appear to fix it.

I'm using VS Code Insiders 1.47.0 out-of-the-box, no config changes, no extensions installed:
```
Version: 1.47.0-insider
Commit: 0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69
Date: 2020-06-23T09:38:28.751Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 18.7.0
```
The steps for this unconfigured build:

1. Open a new file
2. Set file type (bottom-right pop-up) to PHP
3. File -> Save
4. Enter `Foo.inc` for name

File is saved as `Foo.inc.ctp`.  `Foo.php` saves as typed, as do other less-common PHP extensions (`Foo.php5`, `Foo.phtml`).

However (and this might relate to #100241), when I try to save a PHP file as `Foo.txt`, I receive a similar dialog as that ticket describes:
> You cannot save this document with extension “.txt” at the end of the name. The required extension is “.ctp”.
>
> You can choose to use both, so that your file name ends in “.txt.ctp”.

Apparently Cake PHP uses `.ctp` for its [template library](https://book.cakephp.org/2/en/views.html#view-templates), so perhaps that's where the extension comes from.  I don't know why it would be the required extension for PHP files, though.

**Comment by bpasero** [comment]
@jimbonator again I think this is just how macOS file dialogs behave. I see two workarounds:
* you can configure `"files.simpleDialog.enable": true` to get our own custom dialog that gives you full control over the path
* you can select "All Files" from the "Format" dropdown in the dialog and then you have control

macOS seems to add the file extension to the file automatically unless you select "All Files". I do not think there is much VSCode can do actually.

**Comment by jimbonator** [comment]
I'll use the simple dialog then.
