### ISSUE TITLE
Is there anyway to get which completion item is chosen by the user?

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#100345]
Hello, I am developing an auto-completion extension. I want to get some statistics for my completion extension. For example, when the user chooses a completion item, an event is fired with recording the index of chosen completion item. Does vscode's api provide anyway to record this? 

Thank you!

**Comment by HaoboGu** [comment]
@jrieken Can you take a look of this?

**Comment by jrieken** [comment]
Yes - check out [`CompletionItem#command`](https://github.com/microsoft/vscode/blob/cf7b620598e7e48a0c532af90bc7d9517c59edfa/src/vs/vscode.d.ts#L3846) which is executed whenever a completion is inserted
