### ISSUE TITLE
Pinned tabs do not preserve when joining editor groups

### ISSUE THREAD

**Issue by adamrushuk** [microsoft/vscode#100303]
- VSCode Version: `1.46.0`
- OS Version: `Windows 10 Pro 2004 Build 19041`

Steps to Reproduce:

1. Right-click one or more tabs and select `Pin`.
2. Split or move other tabs to another Editor Group.
3. Press `F1` and select `View: Join All Editor Groups`
4. Note there are no longer any pinned tabs.

Does this issue occur when all extensions are disabled?: `Yes`

**Comment by bpasero** [comment]
@adamrushuk can you give a bit more precise steps, in your summary you talk about "Join All Editor Groups" but in your "Steps to reproduce" I see no mention.

**Comment by adamrushuk** [comment]
Thanks @bpasero good catch. 
I've added the missing step.

**Comment by bpasero** [comment]
Yeah I can reproduce. Probably a regression from when we decided that pinned tabs should not survive pinned state when splitting, but in this case it would make sense to keep it.

Up for grab if someone has cycles.

**Comment by adamrushuk** [comment]
Wow, that fix was rapid!
