### ISSUE TITLE
VS Code dosn't start 

### ISSUE THREAD

**Issue by zenyogi28** [microsoft/vscode#100350]
Issue Type: <b>Performance Issue</b>

Everytime I try to start VSCode it crashed and shows message "We are sorry ..."

This stated happening after I installed Git plugin and configured my Github reporsitory

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3391)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.15GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    77	 18368	code main
    0	    18	 11068	   electron-crash-reporter
    2	   155	 12860	   gpu-process
    0	    76	 20484	   shared-process
    0	   134	 22444	   window (Welcome - Visual Studio Code)
    0	    58	 20448	     extensionHost
    2	    72	 24296	   window (Issue Reporter)
    0	    25	 27020	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
python|ms-|2020.6.88468
django-intellisense|sha|0.0.2

</details>

**Comment by zenyogi28** [comment]
![image](https://user-images.githubusercontent.com/30011956/84856420-ff746080-b0a9-11ea-9227-91aa0e280d9e.png)

**Comment by deepak1556** [comment]
@zenyogi28 can you follow the instructions to create a crash dump https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach it here. Thanks!

Also does this crash happen when you run with `--disable-extensions` ?
