### ISSUE TITLE
vscode with javascript not always showing folding comment block option 

### ISSUE THREAD

**Issue by noblejack** [microsoft/vscode#100367]
Issue Type: <b>Bug</b>

using javascript with vscode.
vscode does not show option to fold/unfold a comment block some place in my code.
in other lines I can fold/unfold comment block.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo Please supply some JS that reproduces the problem.

**Comment by noblejack** [comment]
> /needsMoreInfo Please supply some JS that reproduces the problem.

the problem occurs when typing in any new .js file
fold/unfold option for comment block isn't showing in some places
![vscodeIssue](https://user-images.githubusercontent.com/16888911/84885676-0ac08f80-b09c-11ea-9e7c-ba83a010eed5.JPG)

**Comment by gjsjohnmurray** [comment]
/confirm

```javascript
// Before const
// doesn't fold

const circle = {
    // TODO
}

// before function
// does fold

function cc() {
    // TODO
}
```
![image](https://user-images.githubusercontent.com/6726799/84892774-1610bc80-b096-11ea-8bf9-dce9c197dffb.png)

**Comment by noblejack** [comment]
confirmed
I disabled all my extensions, but the problem is still persisting
what is causing this ?

**Comment by mjbvz** [comment]
Works for me in VS Code 1.49 with TypeScript 4.0.2:

<img width="414" alt="Screen Shot 2020-09-10 at 2 16 46 PM" src="https://user-images.githubusercontent.com/12821956/92808107-4eabf380-f370-11ea-96be-9841689efd0a.png">

Let me know if there's a case that still doesn't work
