### ISSUE TITLE
about pinned tab feature

### ISSUE THREAD

**Issue by sachisent** [microsoft/vscode#100355]
Issue Type: <b>Feature Request</b>

pin tabs introduced in the latest update was good..but if i pin two tabs at the same time,i am not able to diffrentiate between pined tabs(pinned tabs looks same))

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.
