### ISSUE TITLE
Creating a new notebook cell copies time metadata over.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#100339]
- VSCode Version: 1.47.0-insider (user setup) commit 0288447572790f983c350905bd1fc5b754970a0a
- OS Version: Windows 10

Steps to Reproduce:

1. Install the [.NET Interactive Notebook extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode).
2. Execute a cell with `Console.WriteLine(1234);`
3. Notice the cell execution time is displayed.
4. Add new cell.
5. The new cell has a time pre-populated.

![dotnet/interactive#546](https://user-images.githubusercontent.com/547415/84837974-2a997a00-afee-11ea-9d30-665ab1175e8f.gif)

Does this issue occur when all extensions are disabled?: N/A

**Comment by rebornix** [comment]
@roblourens as we discussed this morning, execution related metadata has its own meaning, compared to other metadata. Maybe we want to extract them out from metadata and then copy/paste cells won't copy them over.

**Comment by roblourens** [comment]
There was no copy/paste here though, is metadata cloned from somewhere when you create a new cell?

**Comment by brettfo** [comment]
Doesn't seem to repro anymore.
