### ISSUE TITLE
Customize scrollbar widths

### ISSUE THREAD

**Issue by jez9999** [microsoft/vscode#100305]
Both horizontal and vertical scrollbars in the code editor, as well as the vertical scrollbar in the Explorer, should have settings allowing the user to specify how thick they should be.  Setting should be a number, not values like "small" and "large".

**Comment by gjsjohnmurray** [comment]
/duplicate of #30191

Please add your comments there.

**Comment by jez9999** [comment]
@gjsjohnmurray This is not a dupe - that bug only tackles VERTICAL widths.
