### ISSUE TITLE
Source control 无法commit代码

### ISSUE THREAD

**Issue by yqbboy** [microsoft/vscode#100360]
- VSCode Version:
- OS Version:
-----------------------------
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0
--------------------------------------
Steps to Reproduce:
1.修改代码后，使用Source Control commit代码，CHANGES 可以看到代码改动列表，但是填完commit Message后，点击✔️ 没有任何反应
2.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by joaomoreno** [comment]
Can you provide a screen recording?

**Comment by yqbboy** [comment]
Yes I can ,how can i give you ?

**Comment by yqbboy** [comment]
Sure，I can . But how can I record it to you?

**Comment by yqbboy** [comment]
> [](url)

> Can you provide a screen recording?
Sure，I can . But how can I record it to you?
