### ISSUE TITLE
Equal text highlighting over multiple rows

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode#100384]
Issue Type: <b>Bug</b>

I am having the exact same issue as described in #6663 (which was closed 4 years ago)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.9.0-0.bpo.6-amd64
Remote OS version: Linux x64 4.9.0-0.bpo.6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.95GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bmews7748/homes/baruchb/work/eq5-latest/ME.Develop|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mews7748|
|OS|Linux x64 4.9.0-0.bpo.6-amd64|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4052)|
|Memory (System)|15.54GB (0.25GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mews7748|
|OS|Linux x64 4.9.0-0.bpo.6-amd64|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4052)|
|Memory (System)|15.54GB (0.25GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.1.4
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
material-icon-theme|PKi|4.1.0
gitlens|eam|10.2.2
me-vscode|ME-|0.0.5
git-graph|mhu|1.24.0
cpptools|ms-|0.28.3

</details>

**Comment by alexdima** [comment]
@BMBurstein That issue was fixed some time ago. Can you please include fresh steps that do not work for you?

**Comment by BMBurstein** [comment]
The exact same steps as in that bug report. I opened the same file as used in the report, highlighted the same part of a line and the identical text a few lines down was highlighted. When I highlighted the same multi-line section, it was not highlighted a few lines down. If I press Ctrl+D it does find the other place.

**Comment by alexdima** [comment]
In case of multi-line selection there multiple occurences are not highlighted for performance reasons, but Ctrl+D/Cmd+D will find them.

**Comment by eamodio** [comment]
Nice to know about ctrl+d still finding them, but it would be nice to have on selection

**Comment by BMBurstein** [comment]
> In case of multi-line selection there multiple occurences are not highlighted for performance reasons, but Ctrl+D/Cmd+D will find them.

I am pretty sure this used to work, no?
