### ISSUE TITLE
Test failure: Tasks Execution from onDidEndTaskProcess is equal to original

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#100361]
https://dev.azure.com/vscode/VSCode/_build/results?buildId=46453&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=855ed636-0983-5316-9b28-7efa8f10a65b

**Comment by alexr00** [comment]
Looks like the terminal is so fast now without the 500 ms timeout that the task `executeTask` hasn't returned by the time the events fire.
