### ISSUE TITLE
UX: Improve first time sync user experience

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100346]
## Problem
When turning on sync on secondary machine, it asks to either replace or merge the synced data. There is also an option to "Show Synced Data" which leads to a confusing flow:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/84850338-588db700-b00c-11ea-8196-18b5e4bbb158.png">

<img width="50%" src="https://user-images.githubusercontent.com/35271042/84850383-778c4900-b00c-11ea-818f-22cae6410d23.png">

From this point, there is nothing guiding the user back through the flow to continue to turn on sync and is quite confusing. I would expect a better guided experience to:

1. View the difference of the local and synced data
2. Choose to either replace or merge
3. Complete the sync process

## Proposal
Create a specific view for this scenario where a user can view the diff between the local and synced data and then allow them to either replace/merge all or do it one by one:

![image](https://user-images.githubusercontent.com/35271042/84851154-604e5b00-b00e-11ea-9854-575330331a69.png)

**Comment by sandy081** [comment]
Created specific view `Synced Data` for this scenario. Will think about adding upload and download buttons.

**Comment by misolori** [comment]
Here's an updated proposal with some feedback from the Redmond team's standup and [a prototype flow](https://www.figma.com/proto/pq9IdpLjHYuuLzaWnavkNc/Settings-Sync-Manual-Sync?node-id=16%3A136&viewport=-2473%2C-94%2C0.43500059843063354&scaling=min-zoom):
- Update terminology from "Show Synced Data" => "Manual Sync"
- Show a filtered view where we only show the items that need to be resolved
- Flatten the list to simplify the mental mode for the user
- User `Info` and `Pass` icons to signify that an item has been resolved
- Have a button that lights up when all items have been resolved (this is a stretch item, we can try a check button in the header)
- Once the user clicks the button, Sync is turned on and changes are pushed to the server

![Kapture 2020-06-23 at 13 55 34](https://user-images.githubusercontent.com/35271042/85461745-95503580-b559-11ea-82a9-09dea0c40fb1.gif)

**Comment by sandy081** [comment]
I like it. My feedback:

- How about having single Replace All (Local) and Remote All (Remote) buttons on the view?
- How to represent a deleted or added snippet? 
- It seems not obvious to me how a user can merge data (say settings) from this view and confirm? 

How about reusing some SCM concepts here? For eg:

  - Using SCM badges and decorations to represent Added, Delete, Modified files ?
  - Instead of cloud download and upload icons, show `+ with cloud badge` and `+` icon to accept cloud and local respectively? 
  - Having `Accepted` section/root  and move accepted entries under it.

Being more like SCM will make it easier for user to understand to do changes manually and accept them (helps merge scenario).

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/issues/100791#issuecomment-648569454

> @Tyriar had an interesting idea where the button options could be:
>
> - Replace Local (most common on secondary machines)
> - Manual Sync (this would show the proposed ui)
> - Cancel
>
> Thoughts? This way in the manual sync flow you can still choose the primary to replace the remote.

My thought was actually rolling Replace Local into Manual Sync so the options are:

- Merge
- Manual Sync (which shows proposed UI plus maybe a more prominent way in the sidebar to replace local)
- Cancel

4 buttons in a dialog is _a lot_.

**Comment by sandy081** [comment]
I like it to show only Merge and move Replace actions to Manual Sync.

**Comment by misolori** [comment]
I like the simplicity of the two options now, though it does make it a bit harder to replace local on secondary machines (which might be a more common scenario). But this now makes both the "replace local" and "replace remote" a consistent experience.

> How about having single Replace All (Local) and Remote All (Remote) buttons on the view?

I think we can show the same icons on the single file entries at the very top as global actions for replace all

> How to represent a deleted or added snippet?

I assume that in the diff the one where it's deleted would be empty/red. If the entire contents of the file is empty I would assume that file is deleted.

> It seems not obvious to me how a user can merge data (say settings) from this view and confirm?

That is true, we could introduce a third icon in the list or add a context menu item for it

**Comment by sandy081** [comment]
Here is the updated manual sync flow:

1. Accepting changes manually and turning on sync 

![Kapture 2020-07-16 at 19 22 40](https://user-images.githubusercontent.com/10746682/87768113-f4812d00-c81b-11ea-8462-ed4cc69e8757.gif)

2. More actions - resolving conflicts, discarding changes

![Kapture 2020-07-16 at 19 58 33](https://user-images.githubusercontent.com/10746682/87768090-ec28f200-c81b-11ea-83cb-abdcc9d49df2.gif)

**Comment by sandy081** [comment]
Closing this and feedback will be tracked here #102581
