### ISSUE TITLE
VS code crashes if trying to type open and close parenthesis in search with match case and regular expression turned on

### ISSUE THREAD

**Issue by arindamdawn** [microsoft/vscode#100376]
- VSCode Version: 1.46.0
- OS Version: Win10.0.18362

Steps to Reproduce:

1. Open Search.
2. Turn on match cases (Alt + C) and regex (Alt + R)
3. Type open parenthesis "("
4. Type close parenthesis ")"

VS code will freeze and stop responding.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Do you have emoji in your document or other UTF characters combined from several codepoints?

Doesn't happen for me in files without them, but problem reproduced with zero-width matches and emojis as in #100134

**Comment by arindamdawn** [comment]
I was able to reproduce with ascii characters itself.

**Comment by IllusionMH** [comment]
Strange. Do you have anything except `()` in search field?

In my case it has 1s lag, but VS Code highlights matches in 2MB file (`tsserver.log`) with `()`

**Comment by IllusionMH** [comment]
Do you have an example string that causes  this behavior?
I think I have a fix for #100134 and would like to see if your test can be fixed too.

**Comment by arindamdawn** [comment]
> 
> 
> Do you have an example string that causes this behavior?
> I think I have a fix for #100134 and would like to see if your test can be fixed too.

You were right #100134 is related to this. I am closing this issue.
