### ISSUE TITLE
set the "window.reopenFolders": "all" not work

### ISSUE THREAD

**Issue by sunyuu** [Microsoft/vscode#10032]
- VSCode Version: 1.3.1
- OS Version: windows 7

Steps to Reproduce:

1.  set the "window.reopenFolders": "all" in the setting file
2. open one or two or more windows with folders opened
3. close  all the windows
4. click the vscode icon to reopen it
5. it just show the last window that i closed
 
so,I need to go the file->new window->open recent folders,that's disturbing me , it's the problem that i do not set correctly or something others, need some help.

**Comment by kieferrm** [comment]
I couldn't reproduce the problem with 1.4.0 insiders on Windows 10 or on MacOS.

**Comment by wolfsilver** [comment]
@sunyuu 
use `File > Quit`
not 

> close all the windows
