### ISSUE TITLE
closePanel does not work with when clause

### ISSUE THREAD

**Issue by Christilut** [microsoft/vscode#100358]
Issue Type: <b>Bug</b>

1. Add this keybinding:
```json
  {
    "key": "escape",
    "command": "workbench.action.closePanel",
    "when": "activePanel == 'workbench.panel.repl' || activePanel == 'workbench.panel.output' || activePanel == 'workbench.panel.terminal'"
  }
```
2. Focus the editor pane
3. Press Escape. The panel does not close.
4. Remove the "when" line from the keybinding.
5. Focus the editor pane.
6. Press Escape. The panel does close.

This worked in an earlier version of VSCode, but I'm not sure when this changed.

I've also tried adding this to my settings:
```json
  "terminal.integrated.commandsToSkipShell": [
    "workbench.action.closePanel"
  ]
```
This has no effect. And since I'm not focusing the terminal, I don't think this setting should matter.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard

**Comment by jschweighofer** [comment]
Same here

**Comment by ArturoDent** [comment]
Your keybinding works for me as is (without the `skipShell` addition).  Any other keybindings using `escape`?  If you put it at the very end of your keybindings.json, any difference?

**Comment by Christilut** [comment]
I've moved it to the end of the json and it makes no difference, same problem. No other bindings use `escape` in any way.

**Comment by sbatten** [comment]
@Christilut If you have moved views around (terminal, output debug) it is possible that the activePanel key no longer matches properly because we use random guids for the panel container. To see if this is the issue, try running the `Reset View Locations` command.

**Comment by Christilut** [comment]
That worked! The escape keyboard shortcut now works properly again
