### ISSUE TITLE
MarlinLCD12864 is not displayed on TFT3.5 when uploading firmware.

### ISSUE THREAD

**Issue by auger1234** [microsoft/vscode#100349]
MarlinLCD12864 is not displayed on TFT3.5 when uploading firmware.
This is a link to download the firmware file.
https://drive.google.com/file/d/1rlBbMdjzhrDeOQ9JEc7tuGK5K0eWDBh9/view?usp=sharing

**Comment by gjsjohnmurray** [comment]
@auger1234 how is this related to Visual Studio Code? Maybe you posted to the wrong repo.
