### ISSUE TITLE
Add support for new extension categories

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode#100399]
New extension categories have been added in the marketplace and need to be added in various places for VS Code.

- Data Science
- Machine Learning
- Visualization
- Testing
- Notebooks

Areas that need updated
- [x] ~~[Adopt in vsce](https://github.com/microsoft/vscode-vsce/issues/459) @joaomoreno~~
- [x] Update completions for package.json @sandy081
- [x] Update completions for extensions view @sandy081
- [x] Update completions for cli @sandy081
- [x] Update documentation @fiveisprime

**Comment by joaomoreno** [comment]
@fiveisprime There is no adoption in VSCE. The Marketplace does the category validation.

**Comment by sandy081** [comment]
@fiveisprime Only pending here is updating documentation. Guess you are taking care of this?

**Comment by sandy081** [comment]
To verify:

- Make sure new categories are shown in the suggestions in the Extensions Viewlet input box and while editing `categories` in package.json
- Make sure new categories are shown while running following command `code-insiders --list-extensions --category`

**Comment by fiveisprime** [comment]
Yeah, I'll take care of the documentation today. Also, the marketplace team let me know that they weren't able to get "testing" in as a category after all. This has to do with how the categories are structured for VS where there is already a "testing" top level category.

**Comment by fiveisprime** [comment]
...and the doc change has been merged.
