### ISSUE TITLE
Skip sync configure dialog when re-enabling sync

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100336]
![image](https://user-images.githubusercontent.com/35271042/84832407-10f23580-afe2-11ea-918e-f5e37f5f15e1.png)

1. Turn off sync
2. Make changes in the settings
3. Turn on sync
4. 🐛 Dialog appears asking what you want to configure

If I've already enabled sync and am re-enabling, this step feels repetitive and this this could be skipped as we already have several steps in this process.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/95352

**Comment by misolori** [comment]
Sorry, this issue is different than #95352. I am proposing that when you re-enable sync to skip the dialog. #95352 is proposing to skip the dialog all together. Will re-open this one.

**Comment by sandy081** [comment]
@misolori If I remember in the earlier sync discussions that we want to have consistent experience for this turn on action. And how often a user turn off and turn on sync?  If it is not too often is not worth to have consistency? Also interested to know what is the use case to turn on and turn off sync immediately?

**Comment by sandy081** [comment]
Closing this in favour of consistent experience and not sure what is the use case to turn on / off sync frequently.
