### ISSUE TITLE
Closing browser when Settings Sync starts leaves app in broken state

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100314]
1. Turn on sync
2. Sign in
3. Close browser
4. Go back to app
5. :bug: no way to re-trigger sign in

![image](https://user-images.githubusercontent.com/35271042/84810059-a6300280-afbf-11ea-8467-391c08ef40e9.png)

**Comment by sandy081** [comment]
> Close browser

Which App are you referring to Code Insiders or Web?

**Comment by RMacfarlane** [comment]
@sandy081 I can repro this in Insiders, I imagine the same thing applies to web if you just close the tab that was opened to do auth.

I think the easiest fix is to not have a disabled "Turning on Preferences Sync..." menu item. There's a 5 minute timeout on MS auth after which it will reject, but that's a long time to wait for the UI to be enabled again.

**Comment by sandy081** [comment]
Hmm good that you are able to repro, but I wonder how `Turning on Preferences Sync...` state is persisted across refreshes because this state is in memory and shall be cleared on refresh.

Can you provide me exact steps to repro on insiders?

**Comment by RMacfarlane** [comment]
1. Use "Turn on Preferences Sync" from the accounts menu
2. Choose a sign in option that's not for an existing account so that the browser opens
3. Close the browser window that opens (not vs code)

In VS Code, account menu is now stuck in disabled state and it's not possible to finish auth

**Comment by sandy081** [comment]
Ah ok I understood now. Its closing the browser window that asks for login.

> I think the easiest fix is to not have a disabled "Turning on Preferences Sync..." menu item. 

I do not know if it is the right fix because it will allow user to turn on sync while sync is being turned on from the given window. Is it possible for the auth extension to return after closing the browser? 

@misolori What do you suggest from UX point of view to show or not to show `Turning on Preferences Sync...` menu item?

**Comment by sandy081** [comment]
Ok, it seems @misolori has a suggestion here - https://github.com/microsoft/vscode/issues/100411

I would go with toast notification for turning on sync progress and remove this menu item. Hence closing this as duplicate.

**Comment by sandy081** [comment]
Actually I do not want to remove this `Turning on Preferences Sync..` menu item under gear or accounts drop down. Instead I will add this item only after sign in successful. It means in this case (when you close browser window without signing in), you will see `Turn on Preferences Sync` item and you can turn on sync.
