### ISSUE TITLE
File find/replace dialog is pixelated

### ISSUE THREAD

**Issue by mattklein123** [microsoft/vscode#100302]
I searched other issues to see if I can find something similar but I did not come up with anything. Apologize if this is a duplicate. On my machine, the file find/replace dialog becomes pixelated when I use it. I haven't found any specific set of repro instructions, but it happens every time I start typing into the dialog (it typically does not start pixelated). Attached is an image of what it looks like. Please let me know if there is additional information that I can provide.

![Screenshot_2020-06-15_13-44-24](https://user-images.githubusercontent.com/6305260/84792038-437f3c80-afa8-11ea-8061-a50dee511897.png)

Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:04.923Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-59-generic

Steps to Reproduce:

1. Use file find/replace dialog
2. Notice that is becomes pixelated

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@rebornix from the screenshot, it look like greyscale AA on the find widget.

**Comment by rebornix** [comment]
@sbatten may I ask what's the suggested fix for it?

**Comment by rebornix** [comment]
@mattklein123 I tested on Ubuntu 18 but didn't reproduce this issue with latest Stable, can you please help check if the issue is still there?

**Comment by mattklein123** [comment]
I have not seen this recently (on Ubuntu 20.04) so perhaps it has been fixed? I can reopen if it happens again.
