### ISSUE TITLE
Link detection stops at ＆(double-byte)

### ISSUE THREAD

**Issue by Yamasix** [microsoft/vscode#100353]
Issue Type: <b>Bug</b>

When I Ctrl+click "http://tree-mark.chips.jp/レーズン＆ベリーミックス", vscode ignore "＆ベリーミックス".

I expect open following url:  
http://tree-mark.chips.jp/レーズン＆ベリーミックス

Actually, it opens the following URL:  
http://tree-mark.chips.jp/レーズン  

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

**Comment by jrieken** [comment]
@yamachu Do you mean the partial underline?

<img width="422" alt="Screenshot 2020-06-19 at 13 50 37" src="https://user-images.githubusercontent.com/1794099/85129710-e13a6c00-b233-11ea-99ff-6548263c8938.png">

**Comment by Yamasix** [comment]
@jrieken Yes.
