### ISSUE TITLE
Improve cell metadata API so that executions can be represented easier

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#100388]
Issue Type: <b>Bug</b>

Steps to reproduce
1. Execute a large query
2. Before it's done join with an empty cell
3. rinse and repeat 3-4 times
4. 🐛 You'll hit the API limit because the previously joined searches aren't aborted

Extension version: 0.0.28
VS Code version: Code - Insiders 1.46.0-insider (b1ef2bf05f90dd0e6438782411ab84756f97d8f1, 2020-06-05T12:30:13.870Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (5.85GB free)|
|Process Argv|C:\Users\t-lora\Documents\notebook test|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
> I don't see what it has to do with hitting the API limit.

I guess that's just bad luck. The API is ready to "self cancel", right?

**Comment by jrieken** [comment]
My plan is this: inside execute cell check if the cell gets deleted and then self-cancel (tho this should be done by the UI imo). Maybe, also check if the cells get modified and also self-cancel. 

I have started to look into this but I think the metadata/runState API needs more tweaks. Today there is a bunch of metadata properties that need careful updating. E.g update `runState` and `runStartTime` or `duration` and/or status message and obviously updating the outputs. This is super powerful but also lacks encapsulation, transactionality, and is error prone. E.g run  `executeCell` and then `executeNotebook` but for some reason the latter finishes before the former. In that case metadata isn't reflecting the reality but you see a mix of both runs. 

I think we should come up with an API that helps extension authors more, e.g when execute cell happens an object that represents a single execution should be created. That object should have all properties like state, duration, message, output that are relevant for that execution and it should be independent of other executions. The UI would only need to know what the most recent execution is and render that.

fyi @roblourens

**Comment by jrieken** [comment]
I have pushed changes to fix the underlying issue (abort execute on cell change) but I think the API challenge remains. Tho, I have sketched what I described before (https://github.com/microsoft/vscode/issues/100388#issuecomment-648719193) in the `NotebookCellExecution`-object: https://github.com/microsoft/vscode-github-issue-notebooks/blob/82ba27476f925d1dd5c3ad05bf538542c47c78ce/src/notebookProvider.ts#L33-L89

**Comment by roblourens** [comment]
Closing since this discussion is basically happening in https://github.com/microsoft/vscode/issues/103713
