### ISSUE TITLE
Allow to configure word definition for word based suggestions

### ISSUE THREAD

**Issue by seltzer1717** [microsoft/vscode#100397]
Many languages support language tokens that include hyphens. Although there is an editor setting to add hyphens in tokens for search and selection, autocomplete breaks the tokens at the hyphen making it unusable in languages with hyphens:

![image](https://user-images.githubusercontent.com/1911117/84916459-f7e59500-b072-11ea-8521-14c99a1a3f9f.png)

**Comment by IllusionMH** [comment]
According to icon this is simple Text suggestion, not language specific one.
You can try to remove `-` from `"editor.wordSeparators"` setting and reload window to see it that helps.

However for language tailored experience you would need to install extension that will provide language specific completions. E.g. [Clojure](https://marketplace.visualstudio.com/items?itemName=avli.clojure)

**Comment by seltzer1717** [comment]
I already have that setting, it does not change autocomplete

**Comment by seltzer1717** [comment]
... And by autocomplete I mean text suggestion. Removing the hyphen does
expand selection but has no impact on text suggestion. I assume it's
different regex.

**Comment by jrieken** [comment]
Every language comes with an individual word definition. So, first I need to know what language that is.

**Comment by seltzer1717** [comment]
Interesting, I did not know that. The language is Clojure.

**Comment by seltzer1717** [comment]
- Looks like this is the language file in question: clojure.tmLanguage.json?
- Taken from here: https://github.com/atom/language-clojure/blob/master/grammars/clojure.cson
- Regex definitions look correct
- e.g. "symbol":{"patterns":[{"match":"([\\p{L}\\.\\-\\_\\+\\=\\>\\<\\!\\?\\*][\\w\\.\\-\\_\\:\\+\\=\\>\\<\\!\\?\\*\\d]*)"
- Speculating two possibilities: 1) Word suggestions does not use this file to parse words or 2) The Clojure definition file is missing the definition expected by Word suggestions. The named definitions in this file are Clojure specific: symbol, namespace, etc. Perhaps this file lacks a named regex definition that VS Code word suggestions parser is looking for and thus falls back to some default.

Not sure but thought this was interesting.

**Comment by seltzer1717** [comment]
- Found this in the VSCode docs: https://code.visualstudio.com/api/language-extensions/language-configuration-guide
- Says to use the json key "wordPattern" to add regex for word suggestion
- Clojure's language-configuration.json does NOT have this key
- Tried to add the key using the same regex for symbol in the clojure.tmLanguage.json file
- Seems to have broken my VS Code install
- However believe this to be the problem
- Again use the symbol regex above, that should be the "wordPattern" regex.
- Will fork and patch to confirm

**Comment by seltzer1717** [comment]
Very odd behavior setting "wordPattern". Is there an existing bug? It seems the suggested words are all missing the first character and other odd behavior.

**Comment by jrieken** [comment]
Closing as this is in the hand of languages
