### ISSUE TITLE
Display abnormality on dual screens(both 4K)

### ISSUE THREAD

**Issue by yanxijian** [microsoft/vscode#100370]
Issue Type: <b>Bug</b>

When Visual Code shows on the secondary screen, the right border is drawed on the main screen.
This may happens when Visual Code shows directly on the secondary screen.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (18.67GB free)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-JS-CSS-HTML-formatter|lon|0.2.3
cpptools|ms-|0.28.3

</details>

**Comment by yanxijian** [comment]
![image](https://user-images.githubusercontent.com/9412262/84886957-b16e5580-b0c7-11ea-9a45-8acf487aa493.png)

Hi, this happens when opening a file with VS Code on display 2.

**Comment by bpasero** [comment]
Ok this sounds more like an electron issue to me.

**Comment by IllusionMH** [comment]
Looks like #85310 but that one has 1ps that matches theme etc, not a white line

**Comment by deepak1556** [comment]
Merging this to #85310 , please follow that issue for updates. Thanks!
