### ISSUE TITLE
Revert Notebook Document

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#100331]
Reverting notebooks would require the use of Notebook Editor API.

@rebornix suggested that this API might have to be reviewed.
Filing this issue to track the discussions

**Comment by rebornix** [comment]
The `revertNotebook` API is somewhat similar to our initial implementation of `openNotebook` API, which gives extensions a `NotebookEditor` and extensions use the `edit()` API to fill in the data. It can be painful as opening a notebook and reverting a notebook requires different API usage.

Thus we drop `revertNotebook` API. Instead we will always call `openNotebook` for opening a notebook and reverting a notebook. Extensions only need to return the `NotebookData` which represents the file on disk (or remote).
