### ISSUE TITLE
After copying the current line, it cannot be pasted at the cursor

### ISSUE THREAD

**Issue by 0x018** [microsoft/vscode#100356]
- VSCode Version:1.46.0
- OS Version:win10

Steps to Reproduce:
(The character '|' indicates the cursor position)

```
abfg
cde|
```
1. ctrl+c
2. move the cursor behind the character 'b'
```
ab|fg
cde
```
3. ctrl+v
4. result:
```
cde
ab|fg
cde
```
---

What i want
```
abcde|fg
cde
```

If the current result is what others want, is there any configuration item that can be cancelled?

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
I suggest you press Shift+Home before you press Ctrl+C

**Comment by 0x018** [comment]
> I suggest you press Shift+Home before you press Ctrl+C

1.cde|
2.cd|e
3.c|de

Using 'Shift+Home' will only work in the first case.

Now that I want to copy a line, why should I consider how to select it?

**Comment by gjsjohnmurray** [comment]
> Using 'Shift+Home' will only work in the first case.

For 2 and 3, 'End' followed by 'Shift+Home' ?

> Now that I want to copy a line, why should I consider how to select it?

Do you differentiate between 'copy a line' and 'copy the contents of a line'?

It seems that VS Code assumes Ctrl+C when nothing is selected means 'copy a line', in the sense that when you then paste you get a complete new line.

**Comment by 0x018** [comment]
> > Using 'Shift+Home' will only work in the first case.
> 
> For 2 and 3, 'End' followed by 'Shift+Home' ?
> 
> > Now that I want to copy a line, why should I consider how to select it?
> 
> Do you differentiate between 'copy a line' and 'copy the contents of a line'?
> 
> It seems that VS Code assumes Ctrl+C when nothing is selected means 'copy a line', in the sense that when you then paste you get a complete new line.

I know the difference between the two, but I don't think they are used at all.
'copy the contents of a line' can do everything that'copy a line' can do.

So I hope I can cancel the practice of'copy a line' or provide the configuration to cancel the item

**Comment by alexdima** [comment]
This is by design. Ctrl+C without a selection will place the line in the clipboard and will always paste its contents on a separate line. This is consistent with other editors. This can be turned off via `editor.emptySelectionClipboard`.
