### ISSUE TITLE
Powershell Terminal not rendering colors correctly

### ISSUE THREAD

**Issue by ToastyMallows** [microsoft/vscode#100300]
I installed posh-git (https://github.com/dahlbyk/posh-git) for my Powershell terminal, and everything works but the colors are not rendering in VSCode's Powershell terminal.  They ARE rendering in a normal Powershell terminal, that's why I'm writing it up here.

VSCode:

![vscode terminal](https://user-images.githubusercontent.com/4356159/84790065-ef338700-afbe-11ea-91e6-fd84fdd6b46a.PNG)

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

C:\GIT\test-repo ←[93m[←[39m←[96mmaster←[39m←[93m]←[39m>
```

Windows Powershell:

![powershell terminal](https://user-images.githubusercontent.com/4356159/84790226-1f7b2580-afbf-11ea-8d5c-c42acda731cd.png)

- VSCode Version: 1.46.0 (user setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Install posh-git for Powershell
1. Change directory into a git backed folder
1. Open VSCode, open a terminal
1. Notice that the colors are not rendered

Does this issue occur when all extensions are disabled?: Yes

Issue also still occurs with all of my settings disabled.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
