### ISSUE TITLE
Bad string causes weird behaviours in VS Code

### ISSUE THREAD

**Issue by JeffreyCA** [microsoft/vscode#100343]
- VSCode Version: 1.47.0
- OS Version: macOS 10.15.6

### The string

```
'test⁠test‫'
```

### Steps to Reproduce

1. Copy the above string and try setting it as a string variable in any code or paste in an empty document. Semicolons will appear inside the quotes, but the code is still syntactically valid.

2. Text selection skips around.

3. Use arrow keys to move cursor between characters. The cursor may jump around unpredictably.

4. Click the end of the string and press backspace to delete. Characters in the middle of the line will get deleted.

5. Creating a new unsaved document with the string results in a badly formatted document title.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/9157833/84846084-02c10b00-b01c-11ea-8830-bc5ebed4bbb6.gif)

6. Using the TreeView API, if a tree item's **label** is set to that string, and the tree item's **description** is something like `(text)`, then the description actually gets rendered as `text))`.

![unnamed](https://user-images.githubusercontent.com/9157833/84846749-731c5c00-b01d-11ea-8d84-c70874e09308.png)

There's probably other issues I haven't covered above.

**Comment by yume-chan** [comment]
I can reproduce this issue when I have `"typescript.format.semicolons": "insert"` and `"editor.formatOnPaste": true`

Without the two settings, I can observe after pasting, the cursor is at 'testtest$', not the end, and left/right arrow key won't move cursor correctly.

The root cause is that there is a `\u202b (Right-to-Left Embedding)` after the last "t", I don't think it's a supported scenario.

See how Chrome DevTools handle this:

![image](https://user-images.githubusercontent.com/1330321/84849147-443ad000-b087-11ea-8b4e-d3856a4673d5.png)

**Comment by alexdima** [comment]
That is a valid character -- `'RIGHT-TO-LEFT EMBEDDING' (U+202B)` and the font layouting is correct. After that character, the text renders right to left until a `'LEFT-TO-RIGHT EMBEDDING' (U+202A)` which will switch the layouting back to LTR. This is a case of bidi, and everything runs OK.

**Comment by JeffreyCA** [comment]
Thanks, is the treeview issue also expected? IMO the label and description should be independent and should not affect the other.

**Comment by alexdima** [comment]
fyi @sandy081 @alexr00

**Comment by alexr00** [comment]
The html that's generated from using that string as the label and `(test)` as the tree item description is correct:
```html
<div class="monaco-icon-label-container">
	<span class="monaco-icon-name-container">
		<a class="label-name">
			<span class="monaco-highlighted-label" title="Tooltip for a">
				<span>test⁠test&#8235;</span>
			</span>
		</a>
	</span>
	<span class="monaco-icon-description-container">
		<span class="label-description">(test)</span>
	</span>
</div>
```
This is also as designed for the tree.
