### ISSUE TITLE
unfold region doesn't work

### ISSUE THREAD

**Issue by JohanMeline** [microsoft/vscode#100389]
Issue Type: <b>Bug</b>

Hi,
The Unfold region function doesn't work but folding do.
It's not a keyboard mapping problem because even clicking the function by CTRL SHIFT P don't do anything.

VS Code version: Code - Insiders 1.47.0-insider (84f52fe1c0124307046ac0f5443493cda946e60f, 2020-06-17T06:43:38.511Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
powershell|ms-|2020.6.0
powershell-preview|ms-|2020.6.1
vsliveshare|ms-|1.0.2302
nativescript|Tel|0.11.0

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo Short code example please, as plaintext to be copied and pasted. Also, what language mode?
