### ISSUE TITLE
Equals character (=) is incorrectly escaped in plugin READMEs

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#10033]
Begin installing the Ionide F# extension (Ionide-fsharp).

If you check out [the current README.md](https://github.com/ionide/ionide-vscode-fsharp/blob/4a2fbf0dc92bc6282144af74cd5d294a6935e9af/README.md#windows) on GitHub, you'll see that both Windows download links work.

Specifically, one of the links is to

```text
https://www.microsoft.com/en-us/download/details.aspx?id=44011
```

However, when viewing the extension's README on Visual Studio Code, clicking on the first Windows download link brings you to

```text
http://www.microsoft.com/en-us/download/details.aspx?id%3D44011
```

Notice the `=` has been escaped and replaced with `%3D`.

**Comment by joaomoreno** [comment]
@jrieken Gimme a quick review here. Maybe the `toString` method needs a bit more details. Something in the lines of:

```typescript
	/**
	 * Returns the string representation of this URL. By default, the result
	 * will be _URI component encoded_.
	 * 
	 * @param skipEncoding Do not URI component encode the result. Defaults to `false`.
	 */
```

**Comment by jrieken** [comment]
@joaomoreno We encode all [reserved characters](https://tools.ietf.org/html/rfc3986#section-2.2) which is roughy what you should do. The catch is that each scheme encodes slightly different like `=` in the `query`-part of `http(s)`-uris. We don't implement scheme-specific encoding rules 

 You might wanna use the [OpenerService](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/opener/common/opener.ts#L14) for this.

**Comment by joaomoreno** [comment]
But the URL actually contains the `=` character and wants to preserve it, as part of its query string...

**Comment by rebornix** [comment]
@joaomoreno per your merged PR, seems we no longer encode URL when opening it but I'm still seeing `%3d` while open the downlink @DanielRosenwasser mentioned.
