### ISSUE TITLE
sub folder not shownig

### ISSUE THREAD

**Issue by sarojsekhar17** [microsoft/vscode#100398]
I create a  new folder in src, then a subfolder but the sub folder is not showing

**Comment by ArturoDent** [comment]
If you disable the 

`Compact Folders` setting are the subFolders shown?  And are you sure that they are not already shown to the right of the parent folder.

See https://code.visualstudio.com/updates/v1_41#_compact-folders-in-explorer

**Comment by isidorn** [comment]
@ArturoDent thanks for answering
