### ISSUE TITLE
TYPESCRIPT无法正常启动

### ISSUE THREAD

**Issue by sakuraZY** [microsoft/vscode#100385]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

**Comment by smallg0at** [comment]
**Translation:** 
Title: TypeScript could not start properly
Details: We could not send due to the massive size of information required. We wrote it in your clipboard, so please paste it here.
(This is probably useless information)

**Comment by yume-chan** [comment]
@JacksonKearl Looks like the ["you forgot to paste" bot](https://github.com/microsoft/vscode/issues/94731) doesn't understand Chinese 😞

**Comment by JacksonKearl** [comment]
@yume-chan Thanks for pointing this out! I've opened a new issue to track this.
