### ISSUE TITLE
Disable unfold when hover

### ISSUE THREAD

**Issue by romainmartinez** [microsoft/vscode#100324]
When working on a large file, I sometimes like to fold everything and focus only on one section/function/class.
I use the vim extension and when my cursor passes over a part of a folded section, vscode unfolds it.

![Peek 2020-06-16 14-59](https://user-images.githubusercontent.com/17710617/84816154-10599f00-afe2-11ea-914d-0182c4000365.gif)

Is there any way to disable this feature?

**Comment by yume-chan** [comment]
See VSCodeVim/Vim#1004 and https://github.com/VSCodeVim/Vim/issues/4517#issuecomment-592535396

**Comment by romainmartinez** [comment]
Thanks, `"vim.foldfix": true` solved my problem. Sorry for the issue not directly related to vscode.
