### ISSUE TITLE
Screen refreshing

### ISSUE THREAD

**Issue by AshwinSarath** [microsoft/vscode#100351]
Whenever I resize the vs code editor, my whole computer screen flashes on and off .
Upon closing the editor the problem doesn't exist.
Vs code version:1.46
Windows version: may 2004 (updated)

**Comment by deepak1556** [comment]
Can you provide a demo of the issue or some steps to repro, I don't see the issue when resizing with the 2004 update.

Also can you try https://code.visualstudio.com/insiders/

**Comment by AshwinSarath** [comment]
Since I found windows 2004 is too buggy I uninstalled and I am running Ubuntu.
VS CODE works perfectly there. May be windows is harming VSCODE.

**Comment by deepak1556** [comment]
Thanks for the update, I am on 2004 and haven't see this issue specifically. Lets loop back if you face the issue again, closing for now.
