### ISSUE TITLE
Editor / Context menu (more actions...) items are displayed center, not left-aligned

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#100316]
- VSCode Version: 1.46 Stable and 1.47 Insiders
- OS Version:Windows 10

Steps to Reproduce:

1. Open any file
2. Click on the Editor / Context items (ellipsis button at top right corner)
3. See how the items (core and extension provided) are center, instead of left-aligned

![image](https://user-images.githubusercontent.com/3781424/84810515-d2f51180-afe1-11ea-8ecb-a5b90e44e49b.png)

I checked on MacOS, and it appears to be working just fine. Didn't test on Linux.

Thank you

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Do you have editor tabs switched of on Windows?

Looks like duplicate of #99895

**Comment by alefragnani** [comment]
Yep, turned off.

It's indeed a duplicate. I search for duplicate issues, but didn't find. Maybe because the searched for _centered/center_ instead of _centred_.

Thank you
