### ISSUE TITLE
notification for incoming commits

### ISSUE THREAD

**Issue by ohermosa** [microsoft/vscode#100372]
It would be very useful any kind of notification when there were incomming commits in git repositories.

![image](https://user-images.githubusercontent.com/8667345/84885215-03e14f00-b093-11ea-8d90-5ebaf3163437.png)

Automatically, VSCode shows when there are incoming commits but an outstanding notification would be great

**Comment by joaomoreno** [comment]
The git extension exposes API so it would be trivial for you to implement an extension which could provide that.
