### ISSUE TITLE
Bug with terminal

### ISSUE THREAD

**Issue by nintend01337** [microsoft/vscode#100313]
Issue Type: <b>Bug</b>

Terminal not responding and opens after long time.
Its happens any workspace, even without extensions, idk what the hell..

What i had tried to do 

runs with parameters  --disable-gpu,
sets terminal to render with DOM.
changes all terminals   cmd,powershell,bash

VS Code version: VSCodium 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-12T10:32:02.515Z)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-4100 Quad-Core Processor             (4 x 3617)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.97GB (2.92GB free)|
|Process Argv|--disable-gpu|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
php-debug|fel|0.0.0-development
php-intellisense|fel|1.5.4
code-runner|for|0.10.0
references-view|ms-|0.0.47
vscode-xml|red|0.12.0

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
