### ISSUE TITLE
Custom width for every sidebar view

### ISSUE THREAD

**Issue by chrisands** [microsoft/vscode#100318]
I think it would be better if every view (explorer, search, SCM) should have a separate width when switching between them. For different tasks it better different view width.
For example, the explorer view is a good view when it is narrow, because I can see what is it with folder structure and don't hide when coding, and for search is better when a view is pretty wide because I can see much more information when searching.

What do you think about this feature? And how hard it would be to implement?
I didn't dig into VSCode code, but I would like to make PR if you were interested and that would be not very complicated.

**Comment by sbatten** [comment]
We had this request quite some time ago and it was closed as out of scope. We may have another duplicate open right now but I could not find it. I understand this request, but it has some considerations technically with regards to our layout and I'm not sure the UX is so great that when you switch views, the editor shrinks/grows. I will leave this open for discussion for now, but I am not certain about wanting this just yet.

**Comment by chrisands** [comment]
@sbatten it could be the opt-in feature and enabled individually to each view instead of the whole feature on/off.

For example `settings.json`
```json
{
  "workbench.sideBar.viewsWidth": {
    "search": "400px"
  }
}
```
In this example, the only search view would have custom width and others should be working as is. Of course, when resizing search view width configuration should be updated automatically.

Personally think that it would result in better UX since some of the views are better when they are wide, but I suggest it won't be easy to implement such a feature.
