### ISSUE TITLE
Issue in RTL languages after update to latest version

### ISSUE THREAD

**Issue by YassineXM** [microsoft/vscode#100386]
Issue Type: <b>Bug</b>

hi
the previous version was working perfectly with RTL (Arabic)
Example in HTML :
<option value="العربية<"العربية</option>
but latest version:
<option value="العربية">العربية</option>
thank you very much

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2

</details>

**Comment by rebornix** [comment]
I'm no longer seeing this in Insiders.
