### ISSUE TITLE
Error: Cannot find module 

### ISSUE THREAD

**Issue by smancang** [Microsoft/vscode#10036]
- VSCode Version:1.3.1
- OS Version:windows 10

Steps to Reproduce:

1.compile my code,there's no error. 
2. press F5 to run it, the console output the error.it says it "Error: Cannot find module 'express'",but I have the express in my typings folder

my tsconfig.json is like the follows:
```json
{
	"compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "bin",
        "rootDir": "src",
        "sourceMap": true
	},
    "filesGlob": [
        "./src/**/*.ts",
        "./src/**/*.tsx",
        "!./node_modules/**/*.ts",
        "!./node_modules/**/*.tsx"
	],
    "exclude": [
       "node_modules"
     ]
}
```

**Comment by wallverb** [comment]
But do you have express in your `node_modules` folder ?

**Comment by smancang** [comment]
Oh,you're right.I forgot to run "npm install".Thanks.
