### ISSUE TITLE
[Feature Request] - Support Ctrl + L for clearing console to match Chrome and Edge consoles

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#100330]
In all modern browsers I can Ctrl + l to clear the console when debugging but not in VSCode.

I can override this by setting:
| Command              | Shortcut | When                                    |
|----------------------|----------|-----------------------------------------|
| Debug: Clear Console | ^ + L    | activeViewlet == 'workbench.view.debug' |

But it would be good if this was available out the box.

**Comment by isidorn** [comment]
Actually this is user configurable, and our terminal actually binds Cmd + K on mac.
So will not change the default, and closing this as wont fix.
