### ISSUE TITLE
Synced data view is overwhelming

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100347]
I'm assuming that this view is modeled after how we store the data in the backend, but from a user's perspective this view is extremely overwhelming:

- Everything is grouped by data type (settings, keybindings, etc.) and then by date
- Every entry includes a non-actionable row for the machine
- There is no way to rollback to a certain place in time, you have to do it file-by-file
- The UI state file (globalstate.json) is a weird format that users don't need to see
- The context item "Show raw JSON data" is another item that users don't need to see

![image](https://user-images.githubusercontent.com/35271042/84852562-0c457580-b012-11ea-873f-97afed6c72f4.png)

## Proposal

- Sort the view based on time
- Remove the machine item and append to the filename
- Update actions so that you can rollback to either a single file or to a date in time
- Move context menu actions into a global ellipsis (logs, reset, etc.)

![image](https://user-images.githubusercontent.com/35271042/84852498-df915e00-b011-11ea-9a32-a02c3dd682c8.png)

**Comment by sandy081** [comment]
Thanks for the feedback and the proposal. 

> Sort the view based on time

I have to say that we cannot group all requests by time as the requests are independent. We can follow this pattern in the timeline view for each resource (Settings etc., ). I liked your idea, in other issues you filed, of showing a simpler view that shows last synced data. So I can think of showing a simple view with latest data and have a filter or something to load all data.

> Remove the machine item and append to the filename

👍 

> Update actions so that you can rollback to either a single file or to a date in time

Falls into category of grouping by time

> Move context menu actions into a global ellipsis (logs, reset, etc.)

👍

**Comment by sandy081** [comment]
It is more helpful to know the latest state on the server (for eg., while turning on syncing). Hence added `Synced Data` view to show the latest state.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/10746682/85388864-ec98da80-b546-11ea-9e23-927ab9983a52.png">

Renamed previous synced data view to be called `Sync Activity (Remote)` as it is indeed showing the sync activity. Made these views hidden by default as they are only used for troubleshooting.

Did not append machine name to the file name because it is redundant and causing more noise in the views.

**Comment by misolori** [comment]
> It is more helpful to know the latest state on the server (for eg., while turning on syncing)

I'm not sure I fully understand what the scenario is here. If this view is intended to be an "advanced" view for users to debug what's happening, it makes more sense to see the activity rather than the current state. I think having the additional views (Sync Activity Remote/Local) may just add confusion/noise.

I think this view should just show a list of changes where users can revert back to if needed, and that we should keep it as simple as possible (flat list). 

cc @Tyriar @RMacfarlane for additional thoughts

**Comment by sandy081** [comment]
I would be removing **Synced Data** view in favour of **Manual Sync** view that you recommended in #100346. **Manual Sync** view is only shown while turning on sync to help users to resolve changes manually while turning on sync.

So this will leave only following views in Sync viewlet

- Synced Machines
- Sync Activity (Remote)
- Sync Activity (Local)

> I think this view should just show a list of changes where users can revert back to if needed, and that we should keep it as simple as possible (flat list).

Are you suggesting to merge the activity views?

**Comment by misolori** [comment]
> Are you suggesting to merge the activity views?

Instead of having lots of nodes like this:

![image](https://user-images.githubusercontent.com/35271042/85610383-cf7a0f80-b60b-11ea-9ad8-df75d1fe659d.png)

I propose we simplify the list like this:

![image](https://user-images.githubusercontent.com/35271042/85610415-d7d24a80-b60b-11ea-8571-5ed9c8dc787e.png)

**Comment by sandy081** [comment]
We also need to show the Machine. How about showing machine as description and pushing the time to right aligned?

**Comment by sandy081** [comment]
BTW Flat list requires resolving data which can cause request rate limit. Given that this view is an advanced view, I think the following is good enough. 

In order to achieve flat list we need to filter these requests from rate limit @Tyriar FYI

**Comment by Tyriar** [comment]
Why would rate limiting be a concern? You just need to fetch the latest for 5 or so resources, more snippets maybe but there aren't that many snippets. Rate limiting only happens when the client does 100 requests in 5 minutes

**Comment by sandy081** [comment]
Because this is not just fetching latest versions but the view also show all versions. Hence per each resource there will be as number of requests as that of versions. So it hits the rate limit.

**Comment by Tyriar** [comment]
I have no idea what this view does now:

![image](https://user-images.githubusercontent.com/2193314/86923501-fc85f200-c0e2-11ea-8aed-e2b0939cb5c3.png)

Both left and right clicking "settings.json (Current)" does nothing, same for Settings "(16 hrs ago)". The "undo" button looks scary and I'm too scared to click it.

When I'm in a Remote WSL workspace I see these exceptions, but it doesn't do anything in a regular Windows workspace either:

![image](https://user-images.githubusercontent.com/2193314/86923356-c7799f80-c0e2-11ea-9464-534edbc51fd9.png)

**Comment by sandy081** [comment]
This view will be removed in favour of manual sync view. There is a bug that clicking does nothing and it is fixed in master - https://github.com/microsoft/vscode/issues/101912

**Comment by Tyriar** [comment]
@sandy081 does the manual sync view allow viewing history?

**Comment by sandy081** [comment]
There is a view already to show history which is called `Sync Activity` view

<img width="345" alt="image" src="https://user-images.githubusercontent.com/10746682/86937028-08070680-c13f-11ea-924c-219519a81548.png">

Currently this is hidden by default, but I changed it to be shown by default (in master).

**Comment by Tyriar** [comment]
@sandy081 oh ok, that's what I was looking for. Will check that out at some point.

**Comment by sandy081** [comment]
As mentioned in this comment - https://github.com/microsoft/vscode/issues/100347#issuecomment-649263929 , flat list is expensive in terms of number of server requests. Hence closing this with the current solution.
