### ISSUE TITLE
Extend language API to allow sourceRange in Go to Definition

### ISSUE THREAD

**Issue by vidhya03** [Microsoft/vscode#10037]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1. Create a typescript project for eg angular2
2. create a component with name having dot character
3. import the module in to another component. 

ctrl + hover - highlighting upto dot character
in the below issue the ctl + hover should highlight **gateway.destination.component** but it is highlighting only the _component_ alone. 
![vscode-ctrl-hover](https://cloud.githubusercontent.com/assets/534679/17328223/0b2fc7f6-58da-11e6-8937-326b2c18c084.png)

**Comment by dbaeumer** [comment]
This is the link detector / renderer in the editor. The tsserver returns the right result for the definition request. @alexandrudima assuming this is you. Please move back if I am mistaken.

**Comment by alexandrudima** [comment]
I think it is a limitation of `DefinitionProvider` that does not return the source range, it only returns the definition ranges.

**Comment by alexandrudima** [comment]
fyi @bpasero @jrieken

**Comment by bpasero** [comment]
Yes, I am getting the target location and so the link is being created around the word you hover over. We have the same issue in selfhost when hovering over imports too.

See https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.ts#L276

**Comment by jrieken** [comment]
@bpasero You could maybe not use the word but the token? Then it would be the whole string token instead of the string in there?

**Comment by bpasero** [comment]
@jrieken is there API for me to get this info? I can give it a try 👍

**Comment by jrieken** [comment]
Yeah - I believe you use [`getLineToken`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/editorCommon.ts#L1770)-method and continue from there

**Comment by bpasero** [comment]
I cannot use tokens because some languages return a lot more in a single token compared to what you can click on. For example for a TS thing like `QUnit.equal(entry, entry.next);` the token includes QUnit, equal and even the whitespace to the left.

I think the lack of token info here was the original reason why we went with words.

**Comment by alexandrudima** [comment]
I think this would go well only if the GoToDefinition result would include a `sourceRange` or something that could be used for highlighting. Relying on the tokens has the exact same kind of issues as relying on the word.

**Comment by dbaeumer** [comment]
@jrieken @ben: who should own this. To my knowledge the API doesn't allow to return the information and the tsserver doesn't provide it.

**Comment by jrieken** [comment]
No language service I know off provides that information. I still believe that tokens are the way to go but 'yes' it does depend on how good/bad those are. If we extend the API to allow for a source range we still need to handle the missing case.

**Comment by bpasero** [comment]
As of today using tokens is worse than using words :)

**Comment by mjbvz** [comment]
Upstream change from TS to support this: https://github.com/Microsoft/TypeScript/pull/19175

**Comment by mjbvz** [comment]
Moving out of November as the upstream TypeScript change is scheduled for TS 2.7, which will pick up in VS Code 1.20

**Comment by joshunger** [comment]
@mjbvz Does this issue cover clicking on a directory in an import or is there a separate issue tracking this improvement?
