### ISSUE TITLE
Potential Optimization: Keep extra VSCode window hidden, ready to open?

### ISSUE THREAD

**Issue by coreh** [Microsoft/vscode#10030]
Just noticed that if I set VSCode as my default editor in the command line, via `EDITOR=code -w`, and then run a command that opens the default editor, like `git commit`, it takes quite a while for a new VSCode window to open and be ready for editing. I assume this is related to the overhead of starting a new Electron window, loading, parsing and initializing all the JavaScript for VSCode's interface and plugins.

Not sure if this has been considered or proposed before, but perhaps VSCode could pre-initialize an extra editor window in the background and keep it hidden. That way whenever `code -w` is invoked the window can appear to open instantaneously.

I figure some people might not appreciate the tradeoff of extra RAM consumption for startup performance, so maybe this could be disabled by a flag?
- VSCode Version:  1.3.1
- OS Version: OS X 10.11.6

**Comment by mjbvz** [comment]
Closing as it has been a over a year since this issue was opened and there has not been interested expressed in it
