### ISSUE TITLE
Debug screen cheese

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#100387]
* use `"debug.toolBarLocation": "docked",`
* start debuging
* 🧀 unless you config are very, very short you screen cheese

<img width="402" alt="image" src="https://user-images.githubusercontent.com/1794099/84905811-752ffa80-b0b1-11ea-8c03-3e97794705a0.png">

**Comment by isidorn** [comment]
Good catch, thanks for filling this.
I have changed the select box css rules to be applied across the workench (previously they were only applied in the panel - which does not make a lot of sense).
I checked that I did not break the remote explorer dropdown but it seems good. fyi @alexr00

**Comment by jrieken** [comment]
well, verified but it's not a great solution. there is no ellipsis and it seems wider

**Comment by isidorn** [comment]
Yeah I just changed the style to be like the other select boxes in the workbench.
So the elipses and the width is a general select box issue.
