### ISSUE TITLE
Everything kaput after update.

### ISSUE THREAD

**Issue by pupp3tPr0j3ct** [microsoft/vscode#100424]
If any system data is needed lmk.

**Comment by pupp3tPr0j3ct** [comment]
Sorry for the late reply...

After the May update I cannot open copied code in a browser. Whenever I copy path through vscode the path is a different one to the local path. Always starting with `/mnt/c/Users` instead of `C:/Users`.

Any help will be greatly appreciated.

**Comment by gjsjohnmurray** [comment]
@pupp3tPr0j3ct you have given clues but not yet clarified your dev setup (VS Code on Windows, developing in a Linux environment?), nor given steps to reproduce (copy path exactly how?). If someone was reporting an issue with the software you are developing, what would you like their report to contain?

**Comment by pupp3tPr0j3ct** [comment]
Thank you for being patient with me!

- VS Code v 1.46.1 on Windows 10

As I said before, I can open html files with a browser but I am unable to do so by copying the path through vscode. The method I use to do so is to right click on the file and click on copy path.

**Comment by eamodio** [comment]
@bpasero could this be related the the Uri changes?

> Always starting with /mnt/c/Users instead of C:/Users.

**Comment by bpasero** [comment]
@pupp3tPr0j3ct do you open folders inside WSL?

**Comment by pupp3tPr0j3ct** [comment]
I have yes.

Sorry for the late reply again, I'll try to be more prompt.

**Comment by aeschli** [comment]
@pupp3tPr0j3ct Sorry, you have to explain the problem. I have no clue what this is about.
- what's your dev setup (VS Code on Windows, developing in a Linux environment?),
- steps to reproduce (copy path exactly how?). 
- screenshot

**Comment by pupp3tPr0j3ct** [comment]
> @pupp3tPr0j3ct Sorry, you have to explain the problem. I have no clue what this is about.
> 
> * what's your dev setup (VS Code on Windows, developing in a Linux environment?),
> * steps to reproduce (copy path exactly how?).
> * screenshot

Hi the issue is resolved, not by my doing of course but I don't know what to say. The path copied is now the correct one, I wish I could say that I know what fixed it to avoid it. Thanks for the assistance.
