### ISSUE TITLE
Azure Pipelines YAML returning "problems" since today

### ISSUE THREAD

**Issue by nubgamerz** [microsoft/vscode#100476]
Hello

Been working on building some pipeline in YAML. Everything was fine up until today when I opened VSCode and it's now showing numerous "problems" which don't make sense.

![image](https://user-images.githubusercontent.com/26341882/85007290-9b11d980-b15b-11ea-9732-c9c43d2ba7a6.png)

-task: AzurePowershell@4

Problem: Value is not accepted. Valid values: "AzurePowerShell@4"

I changed the capitalization of "shell" to "Shell" and the error changed to:
"String does not match the pattern of "^PowerShell@2$".

Is this a vscode related issue? Or extension related? I checked the extensions and the ones for YAML haven't been updated recently.

**Comment by Tyriar** [comment]
Related to https://github.com/microsoft/vscode/issues/100471? cc @TylerLeonhardt

**Comment by nubgamerz** [comment]
Not sure how it would be powershell extension related, since the codebase is YAML.

**Comment by Tyriar** [comment]
@nubgamerz do you know what extension contributes those tasks?

**Comment by Oceanswave** [comment]
Same issue - VSCode 1.47.1
![2020-07-16 00_53_58-azure-pipelines yml - Espresso-v8 - Visual Studio Code](https://user-images.githubusercontent.com/760674/87628424-e5588d00-c6fe-11ea-8649-7b4d55e6a236.png)

**Comment by alexr00** [comment]
@nubgamerz can you try disabling all your installed extensions and see if the issue still happens?

**Comment by olaeld** [comment]
I have the same issue. The problem disappears when I disable the extension "YAML Language Support by Red Hat".
But I would rather have that one installed. For example, the "Jira and Bitbucket" extension depends on it.

**Comment by alexr00** [comment]
In that case, the issue is coming from "YAML Language Support by Red Hat", and you should file an issue with that extension.
