### ISSUE TITLE
Intellisense (auto-complete) not working in for-of

### ISSUE THREAD

**Issue by leduardobc** [microsoft/vscode#100478]
Issue Type: <b>Bug</b>

steps to reproduce:
```ts
//create an array of any type:
let my_arr:MyType[] = [];

// bring a for-of snipet
// forof (enter)  becomes:

for (const iterator of object) {
}
```

// the cursor will be positioned in "iterator" variable. Intellisense can't help there (OK)

// hit tab one time and the cursor will go to the "object" variable. (OK)

// start to write "my_" and Intellisense is completelly silent in this section 

// the expected behavior is the auto-complete box appears with "my_arr" as an option. (or any variable in the scope)

// is not a too problematic bug because I can hit ctrl+space to force Intellisense to come out, but is a little anoying since the rest of the code works without ctrl+space  (like on IFs)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 5.3.0-59-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2372)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.59GB (7.76GB free)|
|Process Argv|--no-sandbox --unity-launch /home/luis/devenv/i3track/apis/maxtrack/workunit|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
vscode-docker|ms-|1.3.0

</details>

**Comment by mjbvz** [comment]
Try setting `"editor.suggest.snippetsPreventQuickSuggestions": false`

**Comment by leduardobc** [comment]
Thanks for the sugestion but it isn't a good solution.

Now when I start typing in the iterator part (I am naming a fresh new variable there) snippets suggestions pops and if I hit tab to go to the object part the snippet suggestion is accepted breaking the code.
The IF statement now suffers for the same problem.

All I wanted was that the "for-of" worked like the "if" statement in regard to code-suggestions.

But thanks for the try.
I can continue hitting ctrl+space in the object sesction. No problem.
