### ISSUE TITLE
Changing character casing in file name doesn't take effect in editor

### ISSUE THREAD

**Issue by elanhamburger** [microsoft/vscode#100436]
Changing the capitalization of any character(s) in the name of a file in the explorer does not get reflected into the editor, even after closing and re-opening the file. For example:

1. Create a new file in file explorer, e.g. newfile.js (Optionally close the editor that automatically opens.)
2. Change capitalization of any part of new file name, e.g. rename to NewFile.js
3. Open the renamed file in the editor
Expected: The editor tab will show new name "NewFile.js"
Actual: The editor tab shows old name "newfile.js"

Even the tooltip over the editor tab shows the old file name.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by elanhamburger** [comment]
@bpasero Slight modification for version 1.47.0-insider

Renaming the file causes the name of the file in the editor tab to change, but it does not change the name of the file in the breadcrumb underneath the tab. When you save the file, the file name reverts itself to the previous casing, even across multiple renames of the file.

**Comment by bpasero** [comment]
Yeah, my change was not complete. Adding @jrieken for breadcrumb, but I am actually not sure how to fix it there because breadcrumbs are probably just picking on the resource of the input. We might have to expose the `label` thing I introduced to the file inputs to others for consumption?

**Comment by jrieken** [comment]
Yeah, good question. Breadcrumbs use the resource from the file input and actually not just the name but every path segment of it. So, changing the casing of a parent folder would have the same problem...

**Comment by bpasero** [comment]
I wonder if the generic `EditorInput` should not only have `resource` but also `label: URI` so that everyone can adopt this.

**Comment by bpasero** [comment]
I extracted the breadcrumbs issue into https://github.com/microsoft/vscode/issues/100633
