### ISSUE TITLE
Extensions list doesn't auto-update when sync is installing extensions

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100415]
This came up a lot in our previous user studies and thought we filed this issue.

1. Open extensions list before turning on sync
2. Turn on sync
3. 🐛 Extensions list never gets updated

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/35271042/84932886-d217ba80-b089-11ea-885d-3e46017ecd4f.png">

But when I update the query it shows the right info:

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/35271042/84932921-de037c80-b089-11ea-970f-62dea506caa9.png">

We should auto-refresh the list once sync starts installing extensions so users can see the update in real-time

**Comment by sandy081** [comment]
It seems user did not have any extensions before and when user opens extensions, Marketplace extensions are shown by default. 

I agree that in this case the default view shall be updated to installed extensions.

**Comment by sandy081** [comment]
@misolori I thought about this a bit and it might not be really clear when to auto refresh or not, because user might be browsing Marketplace extensions in the view at this point and auto refreshing might not be intended?

Is there any other passive approach like a hint or something in extensions view to represent extensions are installed/auto updated in the background?

**Comment by misolori** [comment]
I think that if the user has the default view (no query) or any of the installed queries (installed, enabled, etc.) we should update the list. If they are searching through the marketplace then that makes sense to not update the list. However, in my experience when sync is installing extensions and I've searched through the marketplace the default view never gets updated long after extensions are installed (like when you clear your results). So we should make sure that is accounted for as well.

This is one of the things that came up a lot in the user study and most people were confused/thought it didn't work.

**Comment by sandy081** [comment]
Installed Extensions view is always shown now 

<img width="482" alt="image" src="https://user-images.githubusercontent.com/10746682/99515697-93b25e80-298d-11eb-9c47-a908f2e96ee6.png">

When extensions are installed either manually or through setting sync, installed list gets auto updated

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/10746682/99515791-b5134a80-298d-11eb-9a9e-324e0d94a77d.png">
