### ISSUE TITLE
Javascript HTML DOM - Autocomplete does not pick up classes and IDs

### ISSUE THREAD

**Issue by gabriel-cloud** [microsoft/vscode#100403]
- VSCode Version: 1.46.0
- OS Version: Darwin x64 19.5.0 / macOS Catalina 10.15.5 (19F101)

Steps to Reproduce:

* Open the attached zip
* Load the files in vscode
* Go to script.js
* Put the cursor inside the " " of getElementById and press CTRL + Space to bring up the suggestions
** (x) Observe you don't get a suggestion for "door1"
** <img width="1905" alt="image" src="https://user-images.githubusercontent.com/54978752/84920961-c2b16500-b0bb-11ea-86b2-4c8bfd70afde.png">
* Go to style.css
* Type #d
** (/) Observe you get the correct "door1" autosuggestion
** 
<img width="993" alt="image" src="https://user-images.githubusercontent.com/54978752/84921191-115eff00-b0bc-11ea-92f6-d8a1e4f5b42f.png">

Does this issue occur when all extensions are disabled?: Yes

[Archive.zip](https://github.com/microsoft/vscode/files/4793764/Archive.zip)

**Comment by ArturoDent** [comment]
I don't think that functionality is built-in.  It works for me with this extension:

[HTML CSS Support](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css)

**Comment by usernamehw** [comment]
also duplicate of #47331
