### ISSUE TITLE
Code Helper (Renderer) Constantly at above 100% CPU usage and causing machine to overheat

### ISSUE THREAD

**Issue by delta97** [microsoft/vscode#100401]
Issue Type: <b>Performance Issue</b>

Within the last 2 weeks, a runaway process has appeared in which during even a few minute of having VS Code open, my fans start spooling up to a ridiculous RPM and at least one Code Helper (Renderer) process is using more than 100% of CPU. It's forcing me to have to use a different IDE. 

Reproduce:
- open vscode 
- open any file, but specifically json and html files for some reason
- look at task manager/activity monitor and observe runaway process that only stops once the app has been ended.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (1.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	    98	  1641	code main
    0	    49	  1642	   gpu-process
    0	    16	  1644	   utility
    0	    82	  1653	   shared-process
    0	     0	  1775	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   590	  1687	   window (index.html — data_dashboard)
    0	   262	  1688	     extensionHost
    0	   115	  1692	       /private/var/folders/wg/rt2wy89x7cg8004dgmbxl5yr0000gn/T/AppTranslocation/595A30C6-7797-4C99-8FBC-DC8B506E1369/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /private/var/folders/wg/rt2wy89x7cg8004dgmbxl5yr0000gn/T/AppTranslocation/595A30C6-7797-4C99-8FBC-DC8B506E1369/d/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain --node-ipc --clientProcessId=1688
    0	    82	  1697	       /private/var/folders/wg/rt2wy89x7cg8004dgmbxl5yr0000gn/T/AppTranslocation/595A30C6-7797-4C99-8FBC-DC8B506E1369/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /private/var/folders/wg/rt2wy89x7cg8004dgmbxl5yr0000gn/T/AppTranslocation/595A30C6-7797-4C99-8FBC-DC8B506E1369/d/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=1688
    0	    33	  1690	     watcherService
    0	    82	  1772	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html — data_dashboard)
|    Folder (data_dashboard): 399 files
|      File types: js(179) css(135) json(10) png(10) html(4) DS_Store(3)
|                  map(3) csv(2) scss(2) swf(1)
|      Conf files: package.json(3);
```

</details>
Extensions: none

**Comment by vittau** [comment]
My Code Helper has been crashing a lot lately as well, on Mac. Windows appears to be unaffected, but I'm not 100% sure. I have to force quit it (or reopen VSCode) for the auto-completion to work again.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
