### ISSUE TITLE
Too many find and replace results breaks the feature until manual service restart

### ISSUE THREAD

**Issue by Jherrild** [microsoft/vscode#100435]
Issue Type: <b>Bug</b>

If my find and replace results are too large, the process completes partway, and then crashes. VS Code stays open, but if I don't close and rerun the find/replace, it'll never complete.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.92GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
csharp|ms-|1.22.1

</details>

**Comment by rebornix** [comment]
@Jherrild can you provide some samples which can break to help me troubleshoot?

**Comment by Jherrild** [comment]
I'm on vacation this week, but anything with 1000 results over 150 files
was pretty consistently failing to finish the find and replace operation.

**Comment by rebornix** [comment]
@Jherrild thanks, it would be great if you can provide concrete sample when it's convenient.

**Comment by Jherrild** [comment]
Of course, I'm sure I'll run into it again next week- do you have a page
somewhere indicating what I should collect for you? It's a proprietary code
base, so I'm afraid I probably can't share the actual files I was
performing the find and replace on.

Best,
Jesten

**Comment by rebornix** [comment]
If sharing the file is not option, can you please try https://github.com/microsoft/vscode/wiki/Native-Crash-Issues to provide us more information to help troubleshoot since you mentioned that it crashed VS Code?
