### ISSUE TITLE
Inconsistent name casing after renaming file

### ISSUE THREAD

**Issue by plankp** [microsoft/vscode#100481]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Create a file in the explorer sidebar (let's say `file.txt`)
2. Open the file in the editor and save it (do not close it)
3. Rename the file in the explorer sidebar, new name has a different case from the original (let's say `FILE.txt`)
4. Observe the names change (which is expected)
5. Edit the same file (that was already opened) and save it
6. Observe the name of the opened file change back to its original name (while the explorer sidebar still shows the changed name).

VS Code version: Code - Insiders 1.47.0-insider (84f52fe1c0124307046ac0f5443493cda946e60f, 2020-06-17T06:56:23.406Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.22GB free)|
|Process Argv|-psn_0_69649|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.15.1
reasonml|fre|1.0.38
vscode-antlr4|mik|2.2.4
csharp|ms-|1.22.1
scala|sca|0.3.9

</details>

**Comment by isidorn** [comment]
Feels like dup of https://github.com/microsoft/vscode/issues/100436
Though first assigning to @bpasero
