### ISSUE TITLE
[Request]Inject Snipet for selection

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#100440]
unlike `vs`, vscode injecting snipet will delete seletion.
please provide inject code as `Outside code`,thanks
![csj](https://user-images.githubusercontent.com/1876302/84968871-0baffa80-b14a-11ea-83eb-2d6a31c8f987.png)

**Comment by usernamehw** [comment]
```js
"ifdef": {
	"prefix": "ifdef",
	"body": "#ifdef ${TM_SELECTED_TEXT}",
},
```
