### ISSUE TITLE
scriptcs extension not finding mono command

### ISSUE THREAD

**Issue by riddhiac** [microsoft/vscode#100452]
I'm running a mac with Catalina. I've installed scriptcs via brew and Mono from the publisher's site.

When I click the 'play' button for a .cs file I get the following error:
/usr/local/bin/scriptcs: line 2: mono: command not found

Mono is located here:
/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono

scriptcs is located here:
/usr/local/bin/scriptcs

Mono version: 6.4.0.198
scriptcs version: 0.17.1

**Comment by yume-chan** [comment]
Does scriptcs work outside Code, e.g., in terminal app?

**Comment by riddhiac** [comment]
yes

**Comment by riddhiac** [comment]
plz help

**Comment by Tyriar** [comment]
This is likely an environment issue on your end. Things to explore:

- Is `mono` on your `$PATH`? If not, where is it set up?
- Try setting `terminal.integrated.shellArgs.osx` to `["-l"]` and `[]`
