### ISSUE TITLE
Can't modify C++ string type variable in local window

### ISSUE THREAD

**Issue by Lili28** [microsoft/vscode#100483]
- VSCode Version: 1.46.0.0
- OS Version: Ubuntu Server 18.04 LTS
- Cpptools: v0.28.3

Steps to Reproduce:
 1.Open tests folder in attachments directly.
 [a.zip](https://github.com/microsoft/vscode/files/4798079/a.zip)
 2.Set a breakpoint on line 20 in a.cpp file.
 3.Press F5 to start debugging.
 4.When hitting the breakpoint, modify the value of the String type variable in the Local window and press Enter.

Excepted:
 It can modify normally.

Actual:
 It pop up a error message:
![Capture](https://user-images.githubusercontent.com/46367699/85012680-f660bd80-b195-11ea-9dc0-34af9ff59367.PNG)

Investigation:
You can successfully modify int type variables in the local window.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
Please file against C++ extension.

**Comment by Lili28** [comment]
Link this issue to another:https://github.com/microsoft/vscode-cpptools/issues/5662
