### ISSUE TITLE
Notebook: turns dirty when being opened

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#100459]
Steps to Reproduce:

1. in the explorer create a new "foo.github-issues"
2. the notebook opens

=> 🐛 the editor is immediately dirty

![image](https://user-images.githubusercontent.com/900690/84987435-68a6b300-b140-11ea-9169-c169ac7e5ec6.png)

**Comment by jrieken** [comment]
It's a new file, shouldn't it be dirty?

**Comment by bpasero** [comment]
No, the file just empty. When you open an empty file it should not show dirty. Even untitled files are not dirty until you start typing.

**Comment by rebornix** [comment]
> Even untitled files are not dirty until you start typing.

I did this on purpose as I thought untitled file should always be dirty but now I don't know how did I have this wrong assumption :(

**Comment by rebornix** [comment]
Verifier:

* Install GitHub Issue Notebook extension
* Add keybindings
```
	{
		"key": "cmd+i",
		"command": "workbench.action.files.newUntitledFile",
		"args": { "viewType": "github-issues" }
	}
```
* Run `cmd+i`
* The untitled notebook should be non-dirty and become dirty once you make changes to the cell
