### ISSUE TITLE
Ctrl + V is actully copying ^V on terminal

### ISSUE THREAD

**Issue by shantanutheone** [microsoft/vscode#100410]
Issue Type: <b>Bug</b>

when i copy some code for pasting in terminal and press Ctrl+V then it type ^V on terminal rather that my code.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (2.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
competitive-programming-helper|Div|4.0.3
python|ms-|2020.6.88468
azure-account|ms-|0.8.11
LiveServer|rit|5.6.1

</details>

**Comment by Tyriar** [comment]
Can you share a screenshot of a new terminal (I'm interested in powershell's intro message) and also your settings.json file?

**Comment by shantanutheone** [comment]
![Here comes the ^V part](https://user-images.githubusercontent.com/40365125/84994050-c13d7680-b167-11ea-8941-b9102ad51687.png)
![Settings.json](https://user-images.githubusercontent.com/40365125/84994060-c39fd080-b167-11ea-987a-8b1aec77c86d.png)
