### ISSUE TITLE
Debugger evaluation status indicator

### ISSUE THREAD

**Issue by syagev** [microsoft/vscode#100430]
When the debugger is busy in evaluation - e.g. after entering a long-running command in the debug window, or when hovering above a variable that has a long-running string representation method - there is no visible indication of this work. This contributes to a programmer's confusion/frustration trying to understand why the debugger is non-responsive.

A good counter example is the "Locals" window which **does** show an indicator when evaluating variables.

Related https://github.com/microsoft/debugpy/issues/294#issue-639028616

**Comment by isidorn** [comment]
This is a fair feature request to show progress while evaluating.

**Comment by pauljurczak** [comment]
It is a must-have feature for me - it takes over 5 minutes of execution in my case to get to the problem spot and CPU frequency monitor is the only indication I have that VSCode is probably still alive.

**Comment by isidorn** [comment]
@pauljurczak please also file an issue against the debug extension you are using
Since we have progress api and each extension can use the debug progress api for reporting progress.
