### ISSUE TITLE
Ability to change cursor height

### ISSUE THREAD

**Issue by roboslone** [microsoft/vscode#100492]
In some apps (Sublime Text, IDEA and iTerm2) cursor height matches font size is not affected by line height.

For example, Sublime Text 3:
<img width="221" alt="st3" src="https://gitlab.com/gnachman/iterm2/uploads/cab06416c10a47cc99ba31d7bb29d24b/Screen_Shot_2016-07-14_at_14.00.14.png">

VS Code's cursor height is affected by line height, which doesn't look as good:
<img width="221" alt="Screenshot 2020-06-18 at 15 03 20" src="https://user-images.githubusercontent.com/1941275/85017860-de2c7680-b174-11ea-9db9-09c0f11fb90e.png">

Could you please make this configurable?

**Comment by usernamehw** [comment]
Old ticket with the same issue: #27931

**Comment by roboslone** [comment]
And there's event a [PR](https://github.com/microsoft/vscode/pull/28109/files)!

**Comment by berknam** [comment]
Will this allow to set the height of the block cursor or the underline cursor as well? So that we can have an half block cursor?
