### ISSUE TITLE
Opening notebook from SCM view opens text editor

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#100468]
Issue Type: <b>Bug</b>

- Have a `.github-issues` notebook with changes.
- Clicking on the 'Open File` inline action in the SCM View open the text editor on the file.

I'd expect to get the notebook editor, just like when opening the file from the Explorer viewlet.

VS Code version: Code - Insiders 1.47.0-insider (84f52fe1c0124307046ac0f5443493cda946e60f, 2020-06-17T06:56:23.406Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.25GB free)|
|Process Argv|-psn_0_12422104|
|Screen Reader|no|
|VM|18%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
regex|chr|0.2.0
vscode-eslint|dba|2.1.5
ghlink|dt|1.2.0
remotehub|eam|0.5.0
tsl-problem-matcher|eam|0.2.0
EditorConfig|Edi|0.15.1
vscode-pull-request-github-insiders|Git|2020.6.23941
rest-client|hum|0.24.1
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|1.3.0
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.6.88468
remote-containers|ms-|0.122.99
remote-ssh-edit-nightly|ms-|2020.6.3953
remote-ssh-nightly|ms-|2020.6.3953
remote-wsl|ms-|0.44.3
azure-account|ms-|0.8.11
azurecli|ms-|0.5.0
js-debug-nightly|ms-|2020.6.1717
vscode-github-issue-notebooks|ms-|0.0.31
debugger-for-chrome|msj|4.12.8
vscode-versionlens|pfl|1.0.8
vscode-yaml|red|0.8.0
vscode-open-in-github|sys|1.14.0
vscodeintellicode|Vis|1.2.8

</details>

**Comment by joaomoreno** [comment]
@bpasero I'm calling `window.showTextDocument`, as suggested before. Is this not recommended now that documents can be opened in editors other than text?

https://github.com/microsoft/vscode/blob/65fa899fbecb5d52ce65df2d1e88df335791a6f9/extensions/git/src/commands.ts#L861-L861

**Comment by bpasero** [comment]
@jrieken should answer, I think he changed `showTextDocument` to enforce opening as text.

**Comment by jrieken** [comment]
Yes - use `vscode.open`. The `showTextDocument` will show a *text* document and its contract is that it returns a text editor which naturally cannot be a notebook

**Comment by joaomoreno** [comment]
Alrighty!
