### ISSUE TITLE
Excessive use of explicit any

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#100454]
![image](https://user-images.githubusercontent.com/900690/84983749-b53ac000-b139-11ea-8b01-56a652a90d70.png)

I stumbled upon this specifically here:

https://github.com/microsoft/vscode/blob/4d91d96e5e121b38d33508cdef17868bab255eae/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L192

If you cast to something, use `as unknown as INotebookEditor` but please do not use explicit `any`.

**Comment by rebornix** [comment]
Thanks for the feedback! most of them have concrete types and `any` is not needed.
