### ISSUE TITLE
[themes] Add command to switch to a specific theme.

### ISSUE THREAD

**Issue by ArjunNair** [microsoft/vscode#100460]
My eyesight is not what it used to be, and I often find myself constantly switching between a dark and light theme as I code through the day depending on the light situation or my mood (...). It would be nice if I can configure a default 'light' and 'dark' theme and then be able to switch between them via a toggle button on the GUI (hey, themes are an important part of the coding sub-culture and warrant a button for instant gratification IMHO) and/or a shortcut (Cmd + Shift + K + T, for example). 

Perhaps this can also be tackled via an extension (I dunno how), but I feel this is important enough (see sub-text on sub-culture above) that it's an integral part of the IDE experience.

**Comment by yume-chan** [comment]
I found the [Theme Switch](https://marketplace.visualstudio.com/items?itemName=Fooxly.themeswitch) extension, which adds two commands `Day Theme` and `Night Theme`, allows you to set two preferred themes and quickly switch between with command palette or key bindings.

**Comment by yume-chan** [comment]
I also tried to add `args` support for `workbench.action.selectTheme` command, but the args get intercepted here:

https://github.com/microsoft/vscode/blob/ec90e96bba9bceaaaedf5033a310893d0156976c/src/vs/workbench/common/actions.ts#L119-L120

I searched for all actions' `run` method but I could find where the `from` field is used.

**Comment by aeschli** [comment]
To change themes programmatically, you update `workbench.colorTheme` in the settings.

(vscode.workspace.getConfiguration(...).update(..)`

**Comment by yume-chan** [comment]
@aeschli I don't want to change theme *programmatically*. What I want to do is allowing `workbench.action.selectTheme` command to take an optional argument, so I can configure a keybinding like:

```json
{
  "key": "cmd+t cmd+l",
  "command": "workbench.action.selectTheme",
  "args": {
    "name": "Monokai"
  }
}
```

**Comment by aeschli** [comment]
Currently 'workbench.action.selectTheme' is for opening the theme selection dialog.
But allowing a parameter sounds like a good idea. PRs welcome!

**Comment by ArjunNair** [comment]
> I found the [Theme Switch](https://marketplace.visualstudio.com/items?itemName=Fooxly.themeswitch) extension, which adds two commands `Day Theme` and `Night Theme`, allows you to set two preferred themes and quickly switch between with command palette or key bindings.

Very nice! I must admit I thought my suggestion would be dismissed as yet another whimsical feature request from a random coder. :) 

I like the idea of having a command to switch to a particular theme, which is a much more generic and powerful implementation than what I had suggested. I look forward to seeing this in action!

**Comment by priytosh-tripathi** [comment]
Hey all,
Is the branch still under active development of the Feature requested here? If not, can someone assign this to me ?

**Comment by RadhiRasho** [comment]
VS Code already has a feature similar to this where you can set your preferred dark and light themes and also the high contrast settings as well: 

![image](https://github.com/microsoft/vscode/assets/54078496/8da449bf-3913-4d30-b616-ab1cd7e421b6)

you can toggle between them using this  command pallet option: 

![image](https://github.com/microsoft/vscode/assets/54078496/0e28be3a-e4a0-4681-b0eb-c56ad5654941)


Not sure if this was discussed, but hopefully this is of help.

**Comment by RadhiRasho** [comment]
you can also set a keybinding to it which should make the switching between them a lot easier: 

![image](https://github.com/microsoft/vscode/assets/54078496/648277a6-0924-48ae-9b9b-5c531b7596c9)

**Comment by Christian1984** [comment]
> VS Code already has a feature similar to this where you can set your preferred dark and light themes and also the high contrast settings as well:
> [...]
> Not sure if this was discussed, but hopefully this is of help.

that's gold. i have bound this to <leader>t in my neovim config and i love it. thanks for sharing!

**Comment by RadhiRasho** [comment]
Glad to be of help

**Comment by ProvaTeams** [comment]
I found an extension similar to Theme Switch that in addition to being able to change the theme manually also allows you to follow the system theme. The extension is called [Toggle Light/Dark Theme](https://marketplace.visualstudio.com/items?itemName=danielgjackson.auto-dark-mode-windows)

**Comment by ArjunNair** [comment]
> VS Code already has a feature similar to this where you can set your preferred dark and light themes and also the high contrast settings as well:
> 
> ![image](https://private-user-images.githubusercontent.com/54078496/266636676-8da449bf-3913-4d30-b616-ab1cd7e421b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTAyMzYsIm5iZiI6MTcwNjUwOTkzNiwicGF0aCI6Ii81NDA3ODQ5Ni8yNjY2MzY2NzYtOGRhNDQ5YmYtMzkxMy00ZDMwLWI2MTYtYWIxY2Q3ZTQyMWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA2MzIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNmFhNTRlMGRkOTIyZjE5Y2Y4MjZjMWQ4MmYyZmQ5MjBiNTU4NjhiN2ZmOThmZTgzM2NiOGVkMDg1NjE3YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K3UxQmyvWBdcH3RBuVg4aExI_-g4GjPDQB5uskKeSdA)
> 
> you can toggle between them using this command pallet option:
> 
> ![image](https://private-user-images.githubusercontent.com/54078496/266636891-0e28be3a-e4a0-4681-b0eb-c56ad5654941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTAyMzYsIm5iZiI6MTcwNjUwOTkzNiwicGF0aCI6Ii81NDA3ODQ5Ni8yNjY2MzY4OTEtMGUyOGJlM2EtZTRhMC00NjgxLWIwZWItYzU2YWQ1NjU0OTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA2MzIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MmU3ZGIyZDM0ZjAzMDNiZWRhNTZlZmYzMWM0OGFiOGZmNjI0MjIzMTE4ZDM3MzU5ZGQyZWFjNWM1ZDA1NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.36B4g-T9_2sn6LL7SClAmk_Y87gNRq_rSsZ65oZtCdI)
> 
> Not sure if this was discussed, but hopefully this is of help.

Brilliant. It's been nearly 4 years since I started this thread! The above along with the next comment about binding keyboard shortcuts (I've setup mine to ⌘T ⌘T, which is easy to remember (mnemonic for Toggle Theme) and execute) pretty much does the job IMO. Thanks to everyone who chipped in with helpful suggestions and @SmallMistake for the useful PR which I hope makes it to the main code base soon. You guys rock!

I will lay this thread to rest now. ☮️
