### ISSUE TITLE
cmd + T it always have "#"

### ISSUE THREAD

**Issue by Paxa** [microsoft/vscode#100462]
Issue Type: <b>Bug</b>

why when press cmd + T it always have "#", it's annoying to search for file

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 7, 5|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
ace|eva|0.0.1
Go|gol|0.14.4
theme-macos-classic|hua|1.2.1
java|red|0.62.0
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
vscode-proto3|zxh|0.4.2

</details>

**Comment by Paxa** [comment]
<img width="1136" alt="Screen Shot 2020-06-18 at 15 11 44" src="https://user-images.githubusercontent.com/26019/84989365-239d7380-b176-11ea-9601-a5242748e5ed.png">

**Comment by yume-chan** [comment]
Cmd+T is searching symbol.

Use Cmd+P to search file, or you can define your own keybindings.
