### ISSUE TITLE
Make the Open Folder and Clone Repository buttons  less in your face

### ISSUE THREAD

**Issue by musm** [microsoft/vscode#100431]
![image](https://user-images.githubusercontent.com/4319522/84955483-5d627180-b0c5-11ea-92fd-1ce4c1efa966.png)

I find these massive buttons extremely in 'your face', when I have the sidebar open.  It's distracting from the main text editor to have these massive buttons on the side, even when you don't' care to 'open a folder' nor 'clone repository'

**Comment by gjsjohnmurray** [comment]
Maybe click the chevron by the NO FOLDER OPENED title?

**Comment by isidorn** [comment]
And you click click the chevron as @gjsjohnmurray suggests

**Comment by isidorn** [comment]
Also @gjsjohnmurray would you consider opening your GitHub account for sponsoring?
Since you help us a lot with inbox triaging some of us would like to give back somehow. We are also open to other ideas.

fyi @joaomoreno
