### ISSUE TITLE
Synced data shows entries with no changes

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100416]
There are several entries in the synced data view where there are no changes:

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/35271042/84935737-fd040d80-b08d-11ea-9e15-f0c0fb4a365f.png">

This further adds to the confusion of this view, not sure why we need to show these entries.

**Comment by sandy081** [comment]
Do you mean `settings.json` with no changes? If so, do you think is it a good to hide entries (requests/transactions). 

Just wanted to be clear that the purpose of this view is to show the log of synced requests and hiding any of them might not be intended.

**Comment by misolori** [comment]
I think we should hide entries where there are no changes, since in this view users are trying to navigate back to a certain point in time it feels like there is no added benefit in seeing requests/transactions (I would argue that's what the output logs are for).

**Comment by sandy081** [comment]
> I would argue that's what the output logs are for

Yeah and this view is the same that is showing activity on the server. In addition it also allows user to restore from a certain point. I also renamed this view to be called `Sync Activity` to make it clear.

Moreover to check if there are changes are not we need to resolve the data upfront which is expensive and will hit server request rate limit. 

Hence I would prefer not to hide the entries.

**Comment by misolori** [comment]
This is going to lead to a lot of confusion/frustration, the users have no way of knowing or understanding why there are entries with no changes. If there is any way for us to filter this list that would be best (IMO).

**Comment by sandy081** [comment]
Yeah I understand but since it cannot be done technically closing this as no action.
