### ISSUE TITLE
Any way to run command on VS Code Start up

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#10044]
- VSCode Version: 1.3.1
- OS Version: Win 10

Is there any way to build any command on the VS Code Start up , when the VS Code Loads completely that command or function runs ? in extension.

I need it for Vs Sync Settings so it will auto check on start up if settings update , it will save on cloud.

**Comment by kieferrm** [comment]
@shanalikhan  There is not an explicit mechanism. But [activationEvents.*](https://code.visualstudio.com/docs/extensionAPI/activation-events#_activationevents) could be used for what you are looking for.
