### ISSUE TITLE
Show useful information when hovering over breakpoints

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#100475]
Today when I hover over a breakpoint in the Breakpoints view the hover shows "breakpoint" which is not helpful.

I suggest show at least the source path for SourceBreakpoints.
Ideally you could show all information that is persisted.

**Comment by isidorn** [comment]
@weinand check it out and let me know how it works for you.
Idealy we would use the labelService to compute the label to be shown however that would drag down the labelService dependency in a lot of places, so to reduce complexity I am simplying using the `path`. This should work just fine in most of the cases, however if it does not work well for notebooks let me know and I will drag down the `labelService` dependency.

**Comment by isidorn** [comment]
After some though pushed a better fix.
To verify: hovering over a breakpoint in the breakpoint view shows the path which makes sense depending on the lpatform.
Hovering over a breakpoint in the editor still shows "Breakpoint" - which I like for clarity.
