### ISSUE TITLE
Sync: provide better progress information when sync is turning on

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100411]
I'm setting up sync on another machine (empty data) and when I turn Sync on, there is nothing telling me what is happening. There are indicators on the extension and gear icons but the menus don't show any information so it's confusing to the user what is happening. If you have a lot of data, this could take more than a minute. Questions I asked myself: Is sync turning on? Is it stuck? What's being installed? How much longer will this take?

<img width="994" alt="image" src="https://user-images.githubusercontent.com/35271042/84931353-895f0200-b087-11ea-9cd8-16be24e29fab.png">

I would expect to see a toast notification, similar to our remote connections, where it would say "Turning on sync..." and a link to the details which would open the logs. Or an item in the status bar that links to the logs. Once sync is turned on, you would never see this again. This is just for the first time you turn on sync.

**Comment by sandy081** [comment]
I liked it.

**Comment by sandy081** [comment]
I went with showing the toast notification as it is consistent with our other progress notifications. Progress also shows which resource is being synced and at the end shows turned on confirmation notification.

![Kapture 2020-06-20 at 1 03 58](https://user-images.githubusercontent.com/10746682/85185071-b03d5400-b292-11ea-9e9d-f5efcf815fbc.gif)

**Comment by sandy081** [comment]
To verify make sure progress toast is shown while turning on sync as above.
