### ISSUE TITLE
vscode unusually slow

### ISSUE THREAD

**Issue by danvixent** [microsoft/vscode#100473]
Issue Type: <b>Performance Issue</b>

From the previous update, vscode became very slow, won't keep up with fast typing, and switching lines is slow, amognst other thing.

i siliently hoped the next update fix this and it did (to an extent), its stillslow while perfoming certain actions.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 5.6.6-300.fc32.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2391)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (10.75GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   111	  5734	code main
    0	    32	  5737	   zygote
    0	   111	  5765	   gpu-process
    0	    64	  5784	   utility
    0	   254	  5792	   window (supplier_protobuf.go - Untitled (Workspace) - Visual Studio Code)
    0	   175	  5860	     extensionHost
    0	   365	  6051	       /home/dan_vixent.go/go/bin/gopls -mode=stdio
    0	    48	  6090	       /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=5860
    0	    48	  6091	       /usr/share/code/code /usr/share/code/resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=5860
    0	    64	  5875	     watcherService
    0	    64	  5934	     searchService
    0	   111	  5898	   shared-process
    0	     0	  7913	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    95	  7888	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (supplier_protobuf.go - Untitled (Workspace) - Visual Studio Code)
|    Folder (BBW): 14 files
|      File types: sql(11) md(1)
|      Conf files:
|    Folder (BBW-app): 92 files
|      File types: go(43) proto(8) json(7) gitignore(1) md(1) mod(1) sum(1)
|      Conf files: launch.json(1) makefile(1)
|      Launch Configs: go
|    Folder (examples): 148 files
|      File types: go(50) md(21) proto(3) sh(1) json(1)
|      Conf files:;
```

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
