### ISSUE TITLE
Cloning from DevOps with remote WSL active

### ISSUE THREAD

**Issue by stressfulPanda** [microsoft/vscode#100488]
Issue:

On Win10 (Build 1904) using WSL2 and an active remote WSL session for my distro (Ubuntu 18.04), if I select 'clone in VS Code' from an Azure Devops repo and then when VS Code pops up I select a local windows folder (so I'm not just cloing into a WSL linux directory) to clone into (by using the 'Show Local' button and then selecting my local windows code folder using the file explorer windows that pops up as a result of using the 'Show Local' folder), then vs code shows the repo being cloned (progress bar, bottom right) but once finished the folder doesn't show up in the target windows folder. If I clone using VS Code without an active remote WSL session then everything clones into my windows folder without issue.

A search of my hard drive shows that cloning using an active remote WSL session results in the repo being cloned to:

 C:\Users\username\.vscode\extensions\ms-vscode-remote.remote-wsl-0.44.2\c\Users\username\source\repos\c\Users\username\source\repos

It should have gone to (i.e. this is the target path and directory for the clone):

C:\Users\username\source\repos

It's not a huge issue - I now clone and then activate my remote WSL session, but it looks like vs code tries to support cloning whilst a remote session is active so thought I'd mention it.

**Comment by joaomoreno** [comment]
> select a local windows folder

If you are in a WSL session, please select a WSL folder

If you'd like it to go to a local Windows folder, please use a normal Windows session.
