### ISSUE TITLE
Editor: Format On Save is not respecting Editor: Tab Size setting.

### ISSUE THREAD

**Issue by RyanJEC** [microsoft/vscode#100434]
Issue Type: <b>Bug</b>

Editor: Format On Save = True
Editor: Tab Size = 4

Save typescript file.

All indents change from 4 spaces to 2 spaces on save.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mattgaspar** [comment]
I had this exact same issue which I thought was related to the update to 1.47 but turns out it was actually related to the **Deno** extension that I installed yesterday.

This issue might be related (at least in my case)
https://github.com/denoland/vscode_deno/issues/101
