### ISSUE TITLE
Multiple breakages when host home directory renamed

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#100441]
- VSCode Version: Latest
- OS Version: Windows 10 x86_64 Professional

Steps to Reproduce:

1. Install VSCode.
2. Rename the Windows user's home directory.
3. Launch, or try to uninstall VSCode.

What's galling is that even the *uninstaller* crashes.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This is not supported. Unfortunately you're going to have to find a way to completely remove VS Code and reinstall it again.
