### ISSUE TITLE
Make notification transparent when focus is in panel

### ISSUE THREAD

**Issue by RookTKO** [microsoft/vscode#100412]
Issue Type: <b>Feature Request</b>

Guys can we have it so when I am typing and I get a popup, the popup has its opacity changed so I can see what I am typing in the terminal instead of having to close out the pop up?

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
What popup are you talking about? Screenshot would be handy.

**Comment by RookTKO** [comment]
@Tyriar  any pop up that pops up in the bottom right corner.

**Comment by RookTKO** [comment]
![image](https://user-images.githubusercontent.com/16005493/84955809-c5588e00-b0ac-11ea-8c9b-60c238c663ae.png)
Something along these lines. I didn't have any pops up atm but when you have an alert in the bottom right corner and you're in the middle of typing commands it would be nice for it to change the opacity so you can see what your typing instead of having to close it out first. I know this seems like a very VERY lazy request but I feel like it would be a great improvement to user experience.
