### ISSUE TITLE
config.get does not return expected value if passing type argument

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10048]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Added a configuration option that's a boolean to my `packages.json`:

    "configuration": {
        "type": "object",
        "title": "Dart Configuration",
        "properties": {
            "dart.setIndentSettings": {
                "type": "boolean",
                "default": true,
                "description": "Forces indenting with two spaces when Dart files are opened. This is on by default because VS Code doesn't support per-language settings and most people use tabs/4 spaces for other languages."
            }
        }
    }

When I come to read it with `config.get<boolean>("setIndentSettings")` it comes back as undefined, yet `config.get("setIndentSettings")` returns false!

From my debug console:

    $ config.get<boolean>("setIndentSettings")
      not available
    $ config.get("setIndentSettings")
      false
    $ typeof config.get("setIndentSettings")
      "boolean"

**Comment by bpasero** [comment]
config.get<boolean>("setIndentSettings") is invalid JavaScript, so what you see is a crash in the VM evaluating what you are typing.
