### ISSUE TITLE
Editor cannot function after using traditional chinese input

### ISSUE THREAD

**Issue by raychunghk** [microsoft/vscode#100491]
- VSCode Version:
1.46
- OS Version:
windows 10 v 1903
Steps to Reproduce:

Chiangjie Chinese input method takes several alphabet characters to compose a chinese characters by pressing space at the end of the combination. e.g  key in [m]+[k]+space to produce the word 天(sky)

1.Press [ctrl+shift] to chinese input method
2.key in some characters
3. the text editor fails to allow to input anything further in the editor

Does this issue occur when all extensions are disabled?: Yes/No

Chinese input method takes several alphabet characters to compose a chinese characters by pressing space at the end of the combination.

1.Press [ctrl+shift] to chinese input method
2.key in some characters

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
@raychunghk can you verify if you are still seeing the issue in latest Insiders https://code.visualstudio.com/insiders/ ?
