### ISSUE TITLE
PowerShell Support since last Update not really there

### ISSUE THREAD

**Issue by vkuehn** [microsoft/vscode#100471]
Issue Type: <b>Bug</b>

Difficult to describe as since the last update Intellisence for almost everything in PowerShell does not show up.  Many errors does not go away  even when fixed in Code only restarting VC does fix that 

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-edifact|DAX|0.6.0
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
prettier-vscode|esb|5.0.1
rainbow-csv|mec|1.7.0
sqlops-debug|ms-|1.3.0
python|ms-|2020.6.88468
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
powershell|ms-|2020.6.0
eof-mark|msf|0.1.0
debugger-for-chrome|msj|4.12.8
resourcemonitor|mut|1.0.7
partial-diff|ryu|1.4.1
vscode-hexdump|sle|1.7.2
vscode-yseopml|Yse|1.9.1

</details>

**Comment by Tyriar** [comment]
cc @TylerLeonhardt
