### ISSUE TITLE
After upgrading to WSL2 and vscode 1.46.0, vscode terminal hangs

### ISSUE THREAD

**Issue by SenorAgosto** [microsoft/vscode#100422]
- VSCode Version: 1.46.0
- Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
- Electron: 7.3.1
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. open vscode 
2. click the green box in the lower left corner
3. select "Remote-WSL: New Window Using Distro"
4. select Centos-7 WSL2 image
5. open folder (open a project)
6. edit files for awhile
7. change application focus to chrome for awhile
8. change application focus back to VS Code
9. attempt to type in the terminal window

For some reason, more often than not, when I do this I can no longer type in the vscode terminal. It is completely unresponsive. I have to close vscode and open a new instance to get around the problem. 

UPDATE: while I appear to be able to change between the "TERMINAL" and "DEBUG CONSOLE" tabs, once frozen, I cannot type in the debug console window either. 

Expected behavior:
I can continue typing in the WSL terminal window after focus comes back from chrome.

Does this issue occur when all extensions are disabled?: Uncertain. 

I do not know how to open Remote-WSL instance of vscode with extensions disabled.

**Comment by franTarkenton** [comment]
I'm experiencing this issue with a slightly different configuration.  Differences are:
* WSL 1
* using Ubuntu 18.04
* I'm using firefox not chrome

Sometimes the terminal becomes unresponsive as described above.  Other times it goes blank, and I can longer communicate with it.  Only solution in this case is restart or reload windows.

**Comment by Tyriar** [comment]
@deepak1556 any ideas? I use a remote WSL2 workspace every day and haven't seen anything like this.

**Comment by SenorAgosto** [comment]
I noticed yesterday, it doesn't have to be a chrome window, just switching focus to another window and coming back causes the terminal/debug-console to hang. 

I upgraded Chrome to 83.0.4103.106, and I'm still experiencing the issue.

**Comment by SenorAgosto** [comment]
@Tyriar I noticed you tagged this "needs more info" but you didn't list what additional information you would like me to provide.

**Comment by SenorAgosto** [comment]
Ran vscode for several hours this morning without an issue, then suddenly the terminal hung again. Interesting bit of information, I did not have my DISPLAY environment variable set in the terminal when it was working. As soon as I set my DISPLAY environment variable and did a `git difftool` on some code, it exhibited the terminal freeze behavior again. 

Other information about my setup, I'm on a VPN for work, so I prepend nameservers to /etc/resolv.conf.

**Comment by ashishmgofficial** [comment]
Same issue is happening to me also in Viscose with WSL Remote. Suddenly in between work, everything goes stuck. Then popup comes us telling , attempting to reconnect Remote. After this I even cannot do anything on windows. I have to restart the system to get back to normal. One thing I noticed is the Python Language Server in task manager using the largest ram space during this time.

**Comment by ealanisg** [comment]
In my case it happens with multiple instances of wsl2 open (in vscode terminal), I ran my tests and start to hanging, if I start to close other instances of vscode, the tests and vscode work again normally... If I only have one instance of vscode, it works well...

**Comment by Tyriar** [comment]
Ping @deepak1556

**Comment by ealanisg** [comment]
What it helped more was to increase the amount of memory that WSL2 could use on the .wslconfig file, I increased it from 4GB to 8GB and it is freezing less often...

https://medium.com/@lewwybogus/how-to-stop-wsl2-from-hogging-all-your-ram-with-docker-d7846b9c5b37

**Comment by SenorAgosto** [comment]
> Hey @Tyriar, this issue might need further attention.
> 
> @SenorAgosto, you can help us out by closing this issue if the problem no longer exists, or adding more information.

I've upgraded VS Code to the latest version, I'll try testing to see if I can replicate the problem or not.

**Comment by SenorAgosto** [comment]
VS Code: 1.50.1
Commit: d2e414d9
Date: 2020-10-13
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
On Windows 10

With this version of VS Code, I was not able to reproduce the issue.
