### ISSUE TITLE
Function breakpoint icon disappear for C++ project

### ISSUE THREAD

**Issue by Tina2018** [microsoft/vscode#100485]
- VSCode Version: 1.46.0.0
- OS Version: Ubuntu Server 18.04 LTS
- Cpptools: v0.28.3

Steps to Reproduce:

1. Create an empty folder called projects and create a .cpp file.
2. Open projects folder using VSCode
3. Add following code in .cpp file, you can refer to attchment file
[projects.zip](https://github.com/microsoft/vscode/files/4798149/projects.zip)
4. Set a function bp as sum(int,int)
5. Click F5 to start debugging

[Expected]
Function icon should display.

[Actual]
It can hit function bp and function bp icon is display.
![Untitled](https://user-images.githubusercontent.com/35017348/85012986-76872300-b196-11ea-8878-9be2ebe1a53c.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
Please file this against the C++ extension. They should first investigate and if the issue is on the vscode side they can file it in this repository. Thanks
https://github.com/microsoft/vscode-cpptools

**Comment by Tina2018** [comment]
link this issue to another: https://github.com/microsoft/vscode-cpptools/issues/5661
