### ISSUE TITLE
Find all implementations cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by bmewburn** [microsoft/vscode#100487]
Issue Type: <b>Bug</b>

I'm seeing an error notification appear in the lower right corner when trying to use right click -> find all implementations.

The language is php and textDocument/implementation is provided by the intelephense extension. Intelephense server appears to return a result and no errors can be observed in the intelephense log.

![Screenshot from 2020-06-18 21-31-44](https://user-images.githubusercontent.com/5885195/85015331-249cc800-b1ab-11ea-906f-b4a344234e26.png)

<details>
<summary>server trace</summary>

```
[Trace - 9:20:17 pm] Sending request 'textDocument/implementation - (25)'.
Params: {
    "textDocument": {
        "uri": "file:///xxxxxxxx.php"
    },
    "position": {
        "line": 16,
        "character": 58
    }
}

[Trace - 9:20:17 pm] Received response 'textDocument/implementation - (25)' in 6ms.
Result: [
    {
        "targetUri": "file:///xxxxxxx.php",
        "targetRange": {
            "start": {
                "line": 16,
                "character": 0
            },
            "end": {
                "line": 1261,
                "character": 1
            }
        },
        "targetSelectionRange": {
            "start": {
                "line": 16,
                "character": 6
            },
            "end": {
                "line": 16,
                "character": 35
            }
        },
        "originSelectionRange": {
            "start": {
                "line": 16,
                "character": 44
            },
            "end": {
                "line": 16,
                "character": 64
            }
        }
    },
    {
        "targetUri": "file:///xxxxxxxxxxxx.php",
        "targetRange": {
            "start": {
                "line": 18,
                "character": 0
            },
            "end": {
                "line": 3558,
                "character": 1
            }
        },
        "targetSelectionRange": {
            "start": {
                "line": 18,
                "character": 6
            },
            "end": {
                "line": 18,
                "character": 26
            }
        },
        "originSelectionRange": {
            "start": {
                "line": 16,
                "character": 44
            },
            "end": {
                "line": 16,
                "character": 64
            }
        }
    }
]
```

</details>

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 4.19.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 1|
|Memory (System)|7.68GB (0.34GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.4.1
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.3.0
csharp|ms-|1.22.1
sqltools|mtx|0.22.7
vetur|oct|0.24.0
ayu|tea|0.20.1

</details>

**Comment by bmewburn** [comment]
In 1.46.1 I see `Cannot read property 'with' of undefined` and an empty Reference Results UI open up. Once again server doesn't appear to error and returns a result as above.

![Screenshot from 2020-06-19 09-25-58](https://user-images.githubusercontent.com/5885195/85081300-f18c2000-b20e-11ea-8e2d-fdeece013519.png)
![Screenshot from 2020-06-19 09-26-05](https://user-images.githubusercontent.com/5885195/85081310-f7820100-b20e-11ea-949e-47ffa876b9d3.png)

**Comment by bmewburn** [comment]
Output from debug console:

```
(node:27238) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:27238) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
rejected promise not handled within 1 second: TypeError: Cannot read property 'toString' of undefined
stack trace: TypeError: Cannot read property 'toString' of undefined
	at _compareLocations (/usr/share/code/resources/app/extensions/ms-vscode.references-view/dist/extension.js:1:4871)
	at Array.sort (<anonymous>)
	at /usr/share/code/resources/app/extensions/ms-vscode.references-view/dist/extension.js:1:2543
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
rejected promise not handled within 1 second: TypeError: Cannot read property 'toString' of undefined
stack trace: TypeError: Cannot read property 'toString' of undefined
	at _compareLocations (/usr/share/code/resources/app/extensions/ms-vscode.references-view/dist/extension.js:1:4871)
	at Array.sort (<anonymous>)
	at /usr/share/code/resources/app/extensions/ms-vscode.references-view/dist/extension.js:1:2543
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
rejected promise not handled within 1 second: TypeError: Cannot read property 'toString' of undefined
stack trace: TypeError: Cannot read property 'toString' of undefined
	at _compareLocations (/usr/share/code/resources/app/extensions/ms-vscode.references-view/dist/extension.js:1:4871)
	at Array.sort (<anonymous>)
	at /usr/share/code/resources/app/extensions/ms-vscode.references-view/dist/extension.js:1:2543
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by bmewburn** [comment]
Seems like it doesn't like `LocationLink[]` being returned from the provider.

Client capabilities says this is supported though

```
"implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
```

**Comment by jrieken** [comment]
\closedWith 2a8e5298ebb02302ba340ff7312ba92bf7b3d08c
