### ISSUE TITLE
NODE_MODULE_VERSION Error

### ISSUE THREAD

**Issue by vsjha18** [microsoft/vscode#100428]
- VSCode Version: 1.46.0
- OS Version: Mac OS Catalina

More Details of VSCode 
```
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```
Steps to Reproduce:

1. Create a setup for extension development
2. Use `node-pty` as one of the dependency for your extension.

Once you build the extension and launch `Extension Development Host`. You will see the following pop-up error. 
```
Activating extension 'sco-vscode.xdev' failed: The module '/Users/vjha/projects/ide/extensions/xdev/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)..
```

I can anticipate that this error may be because my `nodejs` version on my laptop may be different that what is "rolled" and shipped with `vscode` or may be it has some relation to the `electron` environment in which this vscode was actually built.

My questions are as follows:
1. How to avoid such situations in general - a cleaner solution.
2. If above is not possible then how will I know which exact version of `node` should I be using on my system.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
Let's track in #658
