### ISSUE TITLE
Filter `Keyboard Shortcuts` by particular column

### ISSUE THREAD

**Issue by deadcoder0904** [microsoft/vscode#100498]
Issue Type: <b>Feature Request</b>

I want to focus on Explorer when my cursor is in the main panel without using mouse.

So I started searching for `focus` in `Keyboard Shortcuts`

Now it filters `focus` everywhere including other columns like `Keybinding` & `When`.

But I only want it to show on `Command` column.

I tried doing `filter:Command focus` but it doesn't work.

I want it to work like either Github or Twitter. As in if you want to search for a particular users tweets with a keyword, you can type `from:username javascript` & it'll give you those results.

Does this exist in VSCode? If not, would be a great feature :)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

**Comment by ArturoDent** [comment]
Related: https://github.com/microsoft/vscode/issues/22748 looks like someone had started this in 2017.

**Comment by sandy081** [comment]
You can now filter by command id column - `@command:${commandId}`. Other supported columns are 

- `@source`
- @keybinding`
