### ISSUE TITLE
Settings editor only gives a partial list of the defaults for 'terminal.integrated.commandsToSkipShell'

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#100437]
Issue Type: <b>Feature Request</b>

An easily-overlooked ellipsis is the only clue that the list is only a partial one.

![image](https://user-images.githubusercontent.com/6726799/84964538-48f19980-b104-11ea-87c4-a4420e3f7183.png)

The actual list of defaults can be viewed after running `Preferences: Open Default Settings (JSON)` and searching there for the string `SkipShell":`

There are currently 118 default items. It is impractical to list them all in the settings editor, but the description text for the setting should be improved to guide the user to find the full list. For example, #100304 means it is now possible to offer a clickable link that will run the command mentioned above. The user could also be advised what string to search for.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
Any thoughts @Tyriar, like would it make sense to click to expand these things inline?
