### ISSUE TITLE
Publisher query is a bit off

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#100495]
I accidentally clicked on publisher name:

![Screenshot (257)](https://user-images.githubusercontent.com/9638156/85021747-f4d5cc00-b17a-11ea-8f92-e253cfafe8f3.png)

It opened extension search prefilled with text:

```
publisher:"Alexander"
```

Problems:

1. Usually query starts with `@` and has autocomplete like `@category:themes`
1. This query returns multiple extension authors (I think it should be search by author id, but `publisher:"usernamehw"` doesn't work)

**Comment by sandy081** [comment]
@prashantvc May I know what is the Marketplace API to get extensions given a publisher?

**Comment by prashantvc** [comment]
I don't think we have search API to get extension for a given publisher.
@SaiKanth007 Do you know anything?

**Comment by isidorn** [comment]
Opened upstream issue https://github.com/microsoft/vsmarketplace/issues/153

**Comment by isidorn** [comment]
@sandy081 as Sai mentioned I think we have this now. Let me assign to this Milestone so we explore this?

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/151192 - this issue has more info
