### ISSUE TITLE
New Solidity extension work.

### ISSUE THREAD

**Issue by Hyperion101010** [microsoft/vscode#100429]
- VSCode Version:
- OS Version:

I am working on a Solidity extension for vscode and during that have faced many problems.
One such is the interfacing of Solidity server implemented in rust with vscode client.
What i am trying to do is sending messages from client and then recieve at the lsp server which is implemented in rust. But while i do this the server is not always crashing with promise failed error.
Also there is no documentation to refer while someone is building a LSP in some other language like rust and want's to interface it with vscode client. Please let me know if you know some resource to refer.

LSP servevr: https://github.com/rust-analyzer/lsp-server/blob/master/examples/goto_def.rs
My client/extension.ts file: https://github.com/Hyperion101010/sls/blob/p1_work/src/client/extension.ts#L74
  
Screenshot:
![Screenshot from 2020-06-18 02-28-58](https://user-images.githubusercontent.com/32175777/84953022-73495400-b110-11ea-8f5e-865e47e0cf48.png)

Steps to Reproduce:

1.Install the extension
2.Call any command or launch the client.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dbaeumer** [comment]
@Hyperion101010 I think a better team to answer this question is the rust analyzer team. They will know how to start their server.

A specification on how client and servers communicate is here:  https://microsoft.github.io/language-server-protocol/specifications/specification-current/#baseProtocol
