### ISSUE TITLE
Sync commands are undiscoverable

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100425]
These are the commands that we show when clicking on sync:

![image](https://user-images.githubusercontent.com/35271042/84950653-1748e600-b0a4-11ea-872b-a7387b5127d7.png)

And these are the commands that are in the command palette:

![image](https://user-images.githubusercontent.com/35271042/84950753-3a739580-b0a4-11ea-95ea-32c5ea56ed31.png)

I think it would be worthwhile to add a command in the sync menu that's labeled "Advanced" where we surface the synced data, local backups, logs, etc. otherwise they become hard to discover. I was specifically looking for the Synced Data view and couldn't find it until I remembered it's not in this list.

**Comment by sandy081** [comment]
Added following entries to the sync menu

- Preferences Sync: Show Settings
- Preferences Sync: Show Synced Data

An action to show logs is available in Synced Data view. Other commands related to local backup are way too advanced and showing them might not be worth.
