### ISSUE TITLE
pin时希望Tab标签可以显示文件名

### ISSUE THREAD

**Issue by colinsusie** [microsoft/vscode#100439]
Issue Type: <b>Feature Request</b>

现在固定标签页之后，标签页只显示一个图标，如果固定的标签比较多，就没有办法一眼看出是哪个文件名。
希望固定时可以保留文件名，用另一个图标或颜色来表示固定标签。

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

**Comment by KiruyaMomochi** [comment]
#98161

**Comment by KiruyaMomochi** [comment]
谢谢你创建这个 Issue！我们认为它与我们已有的另一个 Issue 的内容相同。因此，我们将这个 Issue 作为重复 Issue 关闭。您可以在 <https://aka.ms/vscodeissuesearch> 搜索现有的问题。也请看我们的[问题报告](https://aka.ms/vscodeissuereporting)指南。

祝您编程愉快！
