### ISSUE TITLE
Run menu does not remember launch configuration from settings.json

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#100451]
- VSCode Version: 1.46.0
- OS Version: Win 10 2004

Steps to Reproduce:
1. Have "Python: Current File" launch config in your user `settings.json`
2. Have `project/.vscode/launch.json` with additional launch configs.
3. Use a multi-root workspace (not sure this is required)
4. Select "Python: Current File (user settings)"
5. Reload
6. Note that the first workspace launch config is selected.

This reads similar to #96293, but I don't even know what a dynamic launch configuration is, so I doubt I am using one. My user-settings one is almost certainly non-dynamic:

```
    "launch": {
        "configurations": [
            {
                "presentation": {
                    "group": "00 Python",
                    "order": 0,
                },
                "name": "Python: Current File",
                "type": "python",
                "request": "launch",
                "program": "${file}",
                "justMyCode": false,
                "subProcess": true,
                "internalConsoleOptions": "openOnSessionStart",
                "console": "internalConsole",
            },
        ],
    },
```

Does this issue occur when all extensions are disabled?: No (need SSH remote)

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by bersbersbers** [comment]
> Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

Yes, just tested commit id b9d7ec9ff367a8e59fe4cc2abee605a55be180e8.

**Comment by isidorn** [comment]
Thanks for trying vscode insiders.
Looks like an issue with how we preserve configuration names from user settings.
Code pointer if someone would like to investigate more https://github.com/microsoft/vscode/blob/de1f4a6cbf942096567408e0ac82381b499445c3/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L86

**Comment by bersbersbers** [comment]
If some starts working in this, I guess that problem 2 of #90216 is related - maybe both can be fixed together.

**Comment by bersbersbers** [comment]
Sad to see that - it is beyond me why this issue has been closed. It has the exact same description and user impact as #96293 (just replace "dynamic" by "user"), which has recently been fixed. This includes the same repeated annoyance every time one presses F5 to start debugging after starting VS Code.
