### ISSUE TITLE
markdown preview do not work on linux

### ISSUE THREAD

**Issue by fringesoft** [Microsoft/vscode#10043]
- VSCode Version: 1.3.1
- OS Version: Fedora 24

Steps to Reproduce:
1. open .md file
2. press ctrl + shift + v
3. show error message: "No handler found for the command: 'markdown.showPreview'. An extension might be missing an activation event."

**Comment by kieferrm** [comment]
Works as expected on Ubuntu, MacOS, and Windows. Need to check our `.rpm` installs.

**Comment by eladcandroid** [comment]
Works for me on Fedora 24... (VSCode 1.3.1)

**Comment by cg-cnu** [comment]
working fine on centos 7 with vscode 1.3.1

**Comment by sdminonne** [comment]
Works fine on F24 (VSCode 1.6.1). To be closed?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/15184
