### ISSUE TITLE
Support manual Git sign-in for multiple account mode

### ISSUE THREAD

**Issue by phathuynh5519** [microsoft/vscode#100404]
Issue Type: <b>Feature Request</b>

Support manual Git sign-in & log-out option for multiple account mode and user can switch between git accounts 
Thanks

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
Do you mean GitHub? Or Git? Can you show me a screenshot of the current login mechanism you're using?
