### ISSUE TITLE
move up in autocomplete box using ctrl+k

### ISSUE THREAD

**Issue by itaysk** [microsoft/vscode#100587]
currently we support moving down in an autocomplete box using ctrl+j instead of using the down arrow. can we please add ctrl+k to move up?

**Comment by ArturoDent** [comment]
Hmmm, I don't have a default `ctrl+j` keybinding relating to suggestions or intellisense (if that is what you mean by the `autocomplete box`?).  Did you previously add your own keybinding for that?

In any case, you can add your own to move to the previous suggestion like this:

```
{
    "key": "ctrl+k",
    "command": "selectPrevSuggestion",
    "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
 },
```

**Comment by itaysk** [comment]
sorry you're right I didn't notice but it came through one of the extensions I use.
