### ISSUE TITLE
setting "terminal.integrated.shell.windows" reopens default integrated terminal

### ISSUE THREAD

**Issue by wojcraftinio** [microsoft/vscode#100520]
- VSCode Version: 1.46
- OS Version: Windows 10 Home 2004 19041.329

Hi. I'm using _vercel/hyper_ as external terminal in **_vscode_** with setting **"terminal.integrated.shell.windows"**. After pressing **"Ctrl + `"**, besides opening _vercel/hyper_ app, it also reopens default terminal additionaly. Can you please fix it?  This should increase comfort of using. For example I add this video. [This video](https://streamable.com/m5nb88) only shows vscode window, however Hyper opens correctly on the other screen, which is not recorded. Thanks for reading and I think You can fix it.

**Comment by Tyriar** [comment]
`terminal.integrated.shell.windows` is for the _integrated_ terminal, `terminal.external.windowsExec` is the right setting.
