### ISSUE TITLE
Keyboard responds incorrectly upon CTRL+A+BACKSPACE

### ISSUE THREAD

**Issue by Petronian** [Microsoft/vscode#10059]
- VSCode Version: 1.3.1
- OS Version: Windows 10 ver. 1607

Steps to Reproduce:

1.  Open Visual Studio Code (Make sure to install to PATHS, not sure if this affects it though, I'm sure it doesn't)
2. Opens in Insert mode sometimes for me, you have to spam keys to get out of it.
3. If it works at first, hit CTRL+A and then try to delete the suggestion. This triggers the glitch.

Please note that I did install quite a bit of extensions, although I'm sure none of them would insert these ridiculous key bindings... If they even are bindings.

**Comment by aeschli** [comment]
To find out if an extension causes the problem, run VSCode with `--disable-extensions`

What does ctrl+a do for you? Normally is selects the full text.

**Comment by Petronian** [comment]
I will try that, thanks. Ctrl+ A it's normal purpose, but when you try to delete the resulting selection, that is when the keyboard input problems start to occur.

**Comment by Petronian** [comment]
Found it! Vim's keybindings are wonky and will not allow typing in VSCode to work for me. There was no way for you guys to know that this was the issue as I did not specify. Uninstalled it and now everything is working just fine.
