### ISSUE TITLE
Launch inputs ignored in user settings

### ISSUE THREAD

**Issue by solaris765** [microsoft/vscode#100509]
Issue Type: <b>Bug</b>

Upon launch vscode will report `Variable 'port' must be defined in an 'input' section of the debug or task configuration.`
If the same inputs and configuration as below are used in the workspace's launch.json, input works as expected.

After testing, it looks like the inputs are still read from the workspaces launch.json instead of user settings

1. Add the following to your user settings.
  ```
"launch": {
    "version": "0.2.0",
    "inputs": [
      {
        "id": "port",
        "type": "promptString",
        "description": "Attach to specified port.",
        "default": "9229"
      }
    ],
    "configurations": [
      {
        "type": "node",
        "request": "attach",
        "name": "Debug Port: ${input:port}",
        "address": "0.0.0.0",
        "port": "${input:port}",
        "localRoot": "${workspaceFolder}",
        "remoteRoot": "${workspaceFolder}"
      }
    ]
  }
  ```
2. hit F5 / launch the config

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 5.3.0-59-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 1900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.17GB (17.91GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
smali|cra|1.0.1
c-cpp-compile-run|dan|1.0.11
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.36.0
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
prettier-vscode|esb|5.0.1
dotenv|mik|1.0.1
mongodb-vscode|mon|0.0.4
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.3.0
csharp|ms-|1.22.1
python|ms-|2020.6.88468
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.3
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.4.0
cpptools|ms-|0.28.3
vsliveshare|ms-|1.0.2354
debugger-for-chrome|msj|4.12.8
vetur|oct|0.24.0
vscode-jest|Ort|3.2.0
material-icon-theme|PKi|4.2.0
multi-command|ryu|1.4.0
code-settings-sync|Sha|3.4.3
swdc-vscode|sof|2.2.13
vscode-stylelint|sty|0.84.0
cmake|twx|0.0.17
vscode-proto3|zxh|0.4.2

</details>

**Comment by randy5235** [comment]
Seeing a similar behavior. 

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by weinand** [comment]
related issue: #96522

**Comment by weinand** [comment]
Thanks to @bzarco his PR https://github.com/microsoft/vscode/pull/97440 has fixed this issue too.
