### ISSUE TITLE
Hope to support the PHP Annotations

### ISSUE THREAD

**Issue by iimeepo** [microsoft/vscode#100554]
Hope to support the PHP Annotations
eg:
![image](https://user-images.githubusercontent.com/20764007/85101823-e0a2d500-b235-11ea-8c42-8bf7cd9031e4.png)
![image](https://user-images.githubusercontent.com/20764007/85101844-ed272d80-b235-11ea-99b0-4e6aa0998a41.png)

**Comment by roblourens** [comment]
I don't know what you are asking for, but this request probably belongs on a PHP extension
