### ISSUE TITLE
Can't turn off tag highlight after update.

### ISSUE THREAD

**Issue by TicTak21** [microsoft/vscode#100565]
- VSCode Version: 1.47.0-insider
-- Commit: 8cd3fe080bee38d28ba01d0d71713d6ec22b254e
- OS Version: Darwin x64 19.5.0

Steps to Reproduce:

1. Open VSCode
2. Open *.html
3. Put the cursor over the tag
![1A491BBD-4C57-4B72-9E57-3F7E589DB114_4_5005_c](https://user-images.githubusercontent.com/44474697/85121760-0fb54880-b22e-11ea-8494-251522ce8a87.jpeg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Red highlight comes from Rename on type feature `"editor.renameOnType"`
Light highlight comes from `"editor.occurrencesHighlight"`

You can set them both to `false` to remove highlights for all files or nest in `[html]` and disable for HTML only

```json
"[html]": {
    "editor.renameOnType": false,
    "editor.occurrencesHighlight": false,
}
```

**Comment by TicTak21** [comment]
> Red highlight comes from Rename on type feature `"editor.renameOnType"`
> Light highlight comes from `"editor.occurrencesHighlight"`
> 
> You can set them both to `false` to remove highlights for all files or nest in `[html]` and disable for HTML only
> 
> ```json
> "[html]": {
>     "editor.renameOnType": false,
>     "editor.occurrencesHighlight": false,
> }
> ```

Thank you. `"editor.renameOnType": false` helped.
