### ISSUE TITLE
Proper support for renaming files

### ISSUE THREAD

**Issue by timolehto** [microsoft/vscode#100591]
Currently it is very cumbersome to rename files in VSCode. There is only one(?) special place in the UI where that can be done, and it can not be done via shortcut nor via action command. This can to a degree be remedied by installing special plugins, but it of course makes using VSCode a bit difficult if even this basic funtcionality requires searching for, picking "the right one" and learning to use special plugins. You should not need to do that, unless you want something very special, like maybe rename multiple files using a pattern.

Also while we are at it one might consider adding similar level of support for the "sister" features: moving and deleting, perhaps even duplicating files

_Original sarcastic title and description for context:_

> **Deprecate creating new files, extensions can handle that**
> 
> As per https://github.com/microsoft/vscode/issues/1886 and https://github.com/microsoft/vscode/issues/30400 managing files is not considered a core functionality of an editor. And that makes total sense. We're talking about an editor here. What do you use an editor for? That's right, to edit files. How can you edit a file that doesn't exists, makes zero sense. If you want to do that sort of crazy things then an extension can be used to create these new files for you to edit, but c'mon this is not a creator it's an editor.

**Comment by timolehto** [comment]
Srsly, I think we should seriously consider https://github.com/microsoft/vscode/issues/96162 and I'm not just talking about hacking a command/shortcut for that, but also how crazy it is that right click on filename in the open editors view or the file tab does not allow renaming the file?! Like if I'm not gonna install those extensions, then my only option is to open some other utility, terminal or file browser and rename that file, but then vscode is of course completely oblivious to the fact that I renamed that file and it thinks I've deleted it. How infuriating is that? But if you still think that's not core then I 100% stand behind what I just said. Saving/creating new files is not a core functionality of an editor either.

P.S.
I just figured out that if you actually right click on the filename under the file explorer, under "the project tree", or what do you call that, then there is an option to rename the file (there would even be a shortuct if you just mangede to move the focus on the file there). So in fact renaming is supported to a degree, it's just following the POMA (Principle of Maximal Astonishment). E.g. personally I never use the explorer to navigate to files or anything, I use the jump to file feature and the feature is not available when right clicking on the file tab, menus in at the top, open editors under explorer nor under the searchable actions, all of which are imho far more likely places to look for the feature than the obscure explorer file tree.

**Comment by gjsjohnmurray** [comment]
Try using `Reveal in Side Bar` off the context menu of the tab. Then use the context menu of the item that the focus jumped to. Yes, not as convenient as having the option in the tab's context menu, but that context menu is already quite long.

**Comment by timolehto** [comment]
Yeah, I can even configure a shortcut for that and then hit F2 and it's almost like I had a shortcut for renaming files.. but that's pretty hard to discover and annoying..

Let's compare with Android Studio

I can rename from tab menu
![studio1](https://user-images.githubusercontent.com/491473/85196719-d4c21c00-b2e4-11ea-87a5-c058ae0a6477.png)

I can rename from Open Files menu
![studio2](https://user-images.githubusercontent.com/491473/85196727-e1467480-b2e4-11ea-8d68-ea3327183d0a.png)

I can rename from searchable actions
![studio3](https://user-images.githubusercontent.com/491473/85196729-e4d9fb80-b2e4-11ea-9540-ee076882709d.png)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by timolehto** [comment]
@isidorn :+1: I rephrased the title and description without sarcasm to make it clearer.

**Comment by wellu** [comment]
+1 to this feature request, file renaming is something that happens at some point in every real world project. Currently the feature is there but hidden inside the file explorer which experienced users rarely use as one can open and close files with shortcuts.

File renaming could also be implemented so that once user double clicks the tab, where the filename is shown, it turns in to an editable label where new name could be typed.

**Comment by fingoldo** [comment]
It's simply unbelievable how you Microsoft folks are ignoring a totally valid and well-grounded feature request from the users that keeps appearing as many as (at least) 5 times already after being closed by you, and keeps making so many people (including me today) stumble. Is it among your core company values, to ignore your users? If I were your manager, staff involved in closing these issues would be working at some other place already, for 4 reasons: 1) it questions your professional abilities if you don't understand that file renaming happens quite a lot in programming 2) you don't worry about what your users are requesting 3) you deny requests without giving clear explanation of why not fulfilling the request is better than fulfilling it 4) you don't understand that competing code editors all have requested functionality already, and you don't want to make your own product to at least fare. It's a miracle to me that a company treating its customers like that, with such weak customers satisfaction control, is in world top-3 by capitalization.
