### ISSUE TITLE
Code.exe corrupt and not deleting. 

### ISSUE THREAD

**Issue by lisaraj2009** [microsoft/vscode#100548]
Ok, I was such an idiot because I ranted in my previous report. Sorry about that. 
My VSCode update somehow went corrupt. I tried deleting the files from C:\Users\<<myusername>>\AppData\Local\Programs\Microsoft VS Code\, but Code.exe did not delete. I tried installing from the System Installer, but my OCD is driving me crazy about the corrupt Code.exe. How do I delete the obtrusive exe file?

**Comment by lisaraj2009** [comment]
Hello? Any ideas on how i can get rid of the old, obtrusive 'Code.exe'?

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo Where is it still appearing? If it's hard to explain, maybe paste a screenshot into your reply (direct from clipboard usually works).
