### ISSUE TITLE
[CommandLine] code command remain attached

### ISSUE THREAD

**Issue by buster95** [microsoft/vscode#100516]
executing `code .` the process remains attached in the process of my console, if I close my console vscode also closes

![image](https://user-images.githubusercontent.com/15637669/85055279-884ad500-b15a-11ea-97c2-2439ba6f3155.png)

**Comment by Tyriar** [comment]
What OS/shell is this?

**Comment by buster95** [comment]
I'm using
![image](https://user-images.githubusercontent.com/15637669/86965592-09c3d080-c125-11ea-827b-e0351f3d63e8.png)
Shell
![image](https://user-images.githubusercontent.com/15637669/86965784-44c60400-c125-11ea-992d-dae979b95605.png)
And this is my $PROFILE file
![image](https://user-images.githubusercontent.com/15637669/86965890-7212b200-c125-11ea-9663-c560e472e9a8.png)

**Comment by buster95** [comment]
When remains attached shown this on console
![image](https://user-images.githubusercontent.com/15637669/86966082-bd2cc500-c125-11ea-873b-8c40f14d6e42.png)

**Comment by deepak1556** [comment]
Can you check if the happens when using `code.cmd` ?
