### ISSUE TITLE
visual studio code for mac 1.46 crash at startup 

### ISSUE THREAD

**Issue by mbaldasshcl** [microsoft/vscode#100532]
Cannot start Visual studio code any more, it crash when I try to open it, I've tryed to uninstall and reinstall but the problem remain, even restarting the system. Visual studio code version is 1.46.1  was created 3 Jun 2020. and  OS is Catalina 10.15.5, I've also deleted .vscode and Code folder before reinstalling the product.
maria.baldassarri@hcl.com

**Comment by namaggarwal** [comment]
Did you try disabling all the extensions and then running VSCode. Also https://github.com/microsoft/vscode/blob/master/CONTRIBUTING.md

**Comment by mbaldasshcl** [comment]
I cannot disable the extensions because i cannot open visual studio code. When I open the application from the icon nothing happen. Only one time I've seen the screen that show the message "Code quit unexpectely" Process Electron [1056] Path: /Applications/Vsula Studio Code.app/Contents/MacOS/Electron Identifier: com.microsoft.VSCode Version: 1.46.0 Code Type: X86.0 (Native) Parent Process: ??? [1] Responsible: Electron [1056] User ID: 501

**Comment by mbaldasshcl** [comment]
<img width="934" alt="Screenshot 2020-06-19 at 09 39 12" src="https://user-images.githubusercontent.com/50319336/85109615-e1c20b00-b211-11ea-8d51-9b2ca4c3e44e.png">

**Comment by mbaldasshcl** [comment]
this is the site where I've downloaded the code: https://code.visualstudio.com/download

**Comment by mbaldasshcl** [comment]
old version of visual studio code (1.45) works

**Comment by namaggarwal** [comment]
From the terminal run the following to start without extension
```
code --disable-extensions
```

**Comment by mbaldasshcl** [comment]
same result, nothing happen:
Marias-MBP-2:Contents mbaldass$ ./Resources/app/bin/code --disable-extensions
Marias-MBP-2:Contents mbaldass$ pwd
/Applications/Visual Studio Code.app/Contents

**Comment by deepak1556** [comment]
@mbaldasshcl can you provide the full console report from https://github.com/microsoft/vscode/issues/100532#issuecomment-646493067, you can follow the instructions from here https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#macos

**Comment by mbaldasshcl** [comment]
Process:               Code Helper (GPU) [9285]
Path:                  /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (GPU).app/Contents/MacOS/Code Helper (GPU)
Identifier:            Code Helper (GPU)
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        Electron [9284]
Responsible:           Electron [9284]
User ID:               501

Date/Time:             2020-06-23 10:56:29.514 +0200
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Anonymous UUID:        16805AFC-9A8E-9F62-78CF-F7DE20C22C3F


Time Awake Since Boot: 4700 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libwep
  Referenced from: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (GPU).app/Contents/MacOS/Code Helper (GPU)
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libwep: code signature in (/usr/local/lib/libwep) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/lib/libwep: stat() failed with errno=1

Binary Images:
       0x10fd1a000 -        0x10fd53fe7 +com.github.Electron.helper (0) <034AE9CC-344B-350D-A291-FD6F2F600FAD> /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (GPU).app/Contents/MacOS/Code Helper (GPU)
       0x116296000 -        0x116327eff  dyld (750.5) <E4698FBD-806A-3396-B279-E685BA37430B> /usr/lib/dyld
       0x11639b000 -        0x11c934fbf +com.github.Electron.framework (7.3.1) <4B5879C5-F2C3-3635-8074-283BFE0F6BC7> /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
    0x7fff31222000 -     0x7fff316a1ffb  com.apple.CoreFoundation (6.9 - 1676.105) <6AF8B3CC-BC3F-3869-B9FB-1D881422364E> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff35f90000 -     0x7fff36047ff7  com.apple.MediaPlayer (1.0 - 1.0) <0CE26562-5D87-31D2-A558-641E0822BC6F> /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer
    0x7fff68286000 -     0x7fff68287fff  libSystem.B.dylib (1281.100.1) <B6FDA8A9-3D2B-3BD5-B5B0-57D311C0FF3D> /usr/lib/libSystem.B.dylib
    0x7fff6a207000 -     0x7fff6a24bff7  libsandbox.1.dylib (1217.120.7) <728BC15F-9A6C-3634-9427-60C01CB5A5D6> /usr/lib/libsandbox.1.dylib

**Comment by deepak1556** [comment]
Thanks that makes the issue clearer, we have restricted certain entitlements for the different helper executables and in this case for GPU helper it cannot load non-validated libraries. Not sure why webp library is trying to be loaded into the gpu process

* Does this issue happen when opening any workspace ?
* Can you try our insiders version https://code.visualstudio.com/insiders/
* What does `otool -L /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (GPU).app/Contents/MacOS/Code Helper (GPU)` report ?

**Comment by mbaldasshcl** [comment]
Marias-MBP-2:~ mbaldass$  otool -L /Applications/Visual Studio Code.app/Contents/Frameworks/Code
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Marias-MBP-2:~ mbaldass$  otool -L /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Marias-MBP-2:~ mbaldass$

**Comment by mbaldasshcl** [comment]
now I will try with your insiders version

**Comment by mbaldasshcl** [comment]
also insider version crash:

Process:               Code - Insiders Helper (GPU) [1576]
Path:                  /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (GPU).app/Contents/MacOS/Code - Insiders Helper (GPU)
Identifier:            Code - Insiders Helper (GPU)
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        Electron [1573]
Responsible:           Electron [1573]
User ID:               501

Date/Time:             2020-06-24 09:14:25.986 +0200
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Anonymous UUID:        16805AFC-9A8E-9F62-78CF-F7DE20C22C3F


Time Awake Since Boot: 700 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libwep
  Referenced from: /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (GPU).app/Contents/MacOS/Code - Insiders Helper (GPU)
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libwep: code signature in (/usr/local/lib/libwep) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/lib/libwep: stat() failed with errno=1

Binary Images:
       0x10d0fb000 -        0x10d134fef +com.github.Electron.helper (0) <59C3FC83-C3DF-365B-AF17-2F522B2ADFC7> /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (GPU).app/Contents/MacOS/Code - Insiders Helper (GPU)
       0x10d14c000 -        0x113643f77 +com.github.Electron.framework (8.3.3) <99C86A44-DC48-3233-B8C2-3C5A2676B510> /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x11bb57000 -        0x11bbe8eff  dyld (750.5) <E4698FBD-806A-3396-B279-E685BA37430B> /usr/lib/dyld
    0x7fff321ea000 -     0x7fff32669ffb  com.apple.CoreFoundation (6.9 - 1676.105) <6AF8B3CC-BC3F-3869-B9FB-1D881422364E> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff36f58000 -     0x7fff3700fff7  com.apple.MediaPlayer (1.0 - 1.0) <0CE26562-5D87-31D2-A558-641E0822BC6F> /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer
    0x7fff6924e000 -     0x7fff6924ffff  libSystem.B.dylib (1281.100.1) <B6FDA8A9-3D2B-3BD5-B5B0-57D311C0FF3D> /usr/lib/libSystem.B.dylib
    0x7fff6b1cf000 -     0x7fff6b213ff7  libsandbox.1.dylib (1217.120.7) <728BC15F-9A6C-3634-9427-60C01CB5A5D6> /usr/lib/libsandbox.1.dylib

**Comment by mbaldasshcl** [comment]
and again I get:
Marias-MBP-2:~ mbaldass$  otool -L /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Marias-MBP-2:~ mbaldass$  otool -L /Applications/Visual Studio Code.app/Contents/Frameworks/Code
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by deepak1556** [comment]
Thanks! 

For running otool, the path to the helper executable is incorrect, the spaces must be escaped.

`otool -L /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(GPU\).app/Contents/MacOS/Code\ Helper\ \(GPU\)`

**Comment by mbaldasshcl** [comment]
If I install april version 1.45 it works well, but every morning when I start the computer after shutdown, I find version 1.46 has covered version 1.45 and it crash of course. Is there a way to avoid automatic update so that until you have found a fix for this problem I can use 1.45 without reinstalling it every day ?

**Comment by mbaldasshcl** [comment]
otool -L /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(GPU\).app/Contents/MacOS/Code\ Helper\ \(GPU\)
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by deepak1556** [comment]
You can set `"update.mode": "none"` in your settings.json to disable updates.

The path is still incorrect, missing escape on `\(`

`otool -L /Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Frameworks/Code\ -\ Insiders\ Helper\ \(GPU\).app/Contents/MacOS/Code\ -\ Insiders\ Helper\ \(GPU\)`

**Comment by mbaldasshcl** [comment]
otool -L /Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Frameworks/Code\ -\ Insiders\ Helper\ \(GPU\).app/Contents/MacOS/Code\ -\ Insiders\ Helper\ \(GPU\)
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by mbaldasshcl** [comment]
otool -L /Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Frameworks/Code\ -\ Insiders\ Helper\ \(GPU\).app/Contents/MacOS/Code\ -\ Insiders\ Helper\ \(GPU\)
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by mbaldasshcl** [comment]
the escape on the command line is correct, it get lost when I past it here

**Comment by deepak1556** [comment]
Do you have xcode installed ?

**Comment by mbaldasshcl** [comment]
no

**Comment by deepak1556** [comment]
Okay that explains the error, you need to install the xcode command line tools for it to work `xcode-select --install` . Try the otool command after installing it. Thanks!

**Comment by mbaldasshcl** [comment]
I get message " Can't install software because it is not currently available from Software Update server"

**Comment by mbaldasshcl** [comment]
but you are no able to reproduce this issue on your mac ?

**Comment by deepak1556** [comment]
Nope I can't, `/usr/local/lib/libwep` is not something that should be loaded by the GPU helper executable.

**Comment by mbaldasshcl** [comment]
/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (GPU).app/Contents/MacOS/Code - Insiders Helper (GPU):
	/System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer (compatibility version 1.0.0, current version 1.0.0, weak)
	@rpath/Electron Framework.framework/Electron Framework (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libsandbox.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1575.17.0)

**Comment by mbaldasshcl** [comment]
I've installed xcode. above the output of the command you asked

**Comment by deepak1556** [comment]
thanks for the details!

TIL that libwep is a library injected by websense in all running processes. Do you have Websense or Triton AP-Endpoint ? You will have to exclude vscode from being scanned by them otherwise this crash will happen. VSCode doesn't allow injecting arbitrary into certain processes as a part of macOS hardened runtime.

**Comment by deepak1556** [comment]
Closing as out of scope.

**Comment by ghasemikasra39** [comment]
I have the same issue. When I open Vscode and connect to my remote windows 10 machine, after a few random minutes, my whole macOS crashes ad my system restarts. The vscode make the whole system to restart!!
<img width="267" alt="Screenshot 2020-11-26 at 15 05 55" src="https://user-images.githubusercontent.com/24314029/100360190-e678bf80-2ff8-11eb-9781-729ef4d28db8.png">

VScode version: `October 2020 (version 1.51)`

**Comment by bitops** [comment]
This is still a real issue even for later versions of VSCode.

**Comment by realnatuki** [comment]
Any of you guys using mongoose. I had this one time, today got the same both times I've used mongoose, first it slowed my computer intellisense stopped working and then it crashed.
