### ISSUE TITLE
Attach to process does not list node process

### ISSUE THREAD

**Issue by avissn** [Microsoft/vscode#10050]
- VSCode Version: 1.3.1
- OS Version: win 7

I have default config

``` json
{
      "name": "Attach to Process",
      "type": "node",
      "request": "attach",
      "processId": "${command.PickProcess}",
      "port": 5858,
      "sourceMaps": false,
      "outDir": null
}
```

When I F5 it shows "There are no entries to pick from". 
I have started node in non-debug mode. It is in a VM.
![1](https://cloud.githubusercontent.com/assets/13973713/17342469/77459a78-58c7-11e6-8ddb-a1f5c3f4a7ea.png)

**Comment by weinand** [comment]
@avissn the process picker can only list local node processes. It cannot "see" node processes running in a VM because a VM appears like a remote system.

**Comment by avissn** [comment]
I meant to say I remote desktop to vm for my dev work. 
I understand if I run vsc in my local system and node process in VM it wont show up but I have vsc, code and node processes all running in VM.

**Comment by weinand** [comment]
@avissn can you see the "node" process in your win 7 task manager?

**Comment by avissn** [comment]
yes I in task manager

**Comment by avissn** [comment]
One more thing I noticed related to this issue in VSC 1.4 version. When I run node app in windows cmd it shows up list of process but doesn't show when I run node app in power shell.

**Comment by safinahmed** [comment]
I have the same issue
However if I remove this line from launch.json
` "processId": "${command:PickProcess}",`
The debugger is automatically attached to my process running in 5858

**Comment by weinand** [comment]
@safinahmed do you really want to attach the debugger to a node process that was **not** started in debug mode? If not, then please do not use the "processId" attribute.
