### ISSUE TITLE
the Chinese show problem

### ISSUE THREAD

**Issue by bobo4629** [Microsoft/vscode#10058]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.when i printf some Chinese char it will show as unencoded char 
2.![20160803114325.png](https://ooo.0o0.ooo/2016/08/02/57a1688492792.png)

**Comment by crperlin** [comment]
乱码。。。。这是代码没写好吧。。。若是调用code runner这种插件的。。一般内置编码都是国外的。而不是UTF-8。。

**Comment by aeschli** [comment]
Can you explain where the error is and what is expected?
Is the error in the Windows console window?

**Comment by bobo4629** [comment]
the settings and codes listed as followed   

![_20160805110642.png](https://ooo.0o0.ooo/2016/08/04/57a4032ae9aa4.png)
![_20160805110650.png](https://ooo.0o0.ooo/2016/08/04/57a4032b2a92f.png)
![_20160805110622.png](https://ooo.0o0.ooo/2016/08/04/57a4032b36aaa.png)
![_20160805110712.png](https://ooo.0o0.ooo/2016/08/04/57a4032b65041.png)


the erro is in the Windows console windows

Are my settings' wrong?

**Comment by rebornix** [comment]
@bobo4629 I don't see any relationship between the error and Code. Can you run this C code from command line and see the output? If it's still the same error, then it's not a Code issue.

**Comment by aeschli** [comment]
From how I see it, this is not related to VSCode.
