### ISSUE TITLE
mouse leaving scroll thumb in explorer pane causes selection loss

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#100526]
Issue Type: <b>Bug</b>

when scrolling in the exporer pane (also in SCM), if the mouse leaves the the scroll thumb then when it is released the selection is lost. this makes shift-selecting many items in the list extremely fiddly.

to repro:
- open a folder with many files (more than will fit on screen in the window, so the scrollbar appears in the explorer view
- scroll to the top of the window
- select the first file
- drag the scroll thumb to the bottom, while scrolling (and holding the mouse button down) move the mouse cursor to the left of the thumb. release the mouse button.
- shift-select the last item in the explorer view.

notice that the selection is not extended, this is because, when releasing the mouse button, the original selection was lost.

the selection should not be lost after dragging the thumb.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (3.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1:2222|
|OS|Linux x64 3.10.0-1127.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|3.70GB (1.59GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1:2222|
|OS|Linux x64 3.10.0-1127.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|3.70GB (1.59GB free)|
|VM|100%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.4.1
vscode-markdownlint|Dav|0.36.0
gitlens|eam|10.2.2
php-debug|fel|1.13.0
cmake|twx|0.0.17
plsql-language|xyz|1.8.2
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.3

</details>

**Comment by eamodio** [comment]
I can reproduce

**Comment by Spongman** [comment]
simpler repro:

- open directory with many files
- select a file in explorer
- mouse-down in explorer scrollbar thumbnail
- mouse-over explorer tree
- mouse-up

selection is lost.

**Comment by joaomoreno** [comment]
@alexdima I need your wizardry 🧙‍♂️ 

The click event fires on the list view element for the following sequence of events:

- `mousedown` on the scrollbar handle
- `mouseup` on the the list view element, which contains the scrollbar handle

This matches the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event):

> If the button is pressed on one element and the pointer is moved outside the element before the button is released, the event is fired on the most specific ancestor element that contained both elements.

I tried playing around with cancellation of events at the scrollbar layer but failed. I have a feeling we should simply cancel out any `click` event in [here](https://github.com/microsoft/vscode/blob/7e4c8c983d181cbb56c969662ead5f9a59bfd786/src/vs/base/browser/globalMouseMoveMonitor.ts#L77-L77), if a scrollbar is being scrolled. What do you think?

**Comment by alexdima** [comment]
@joaomoreno :+1: The `GlobalMouseMoveMonitor` is used a lot for click & drag kind of operations, like selection in the editor, or dragging the scrollbar slider, or the minimap slider. We could try to always cancel `click` events and then add a special option for the scrollbar slider case only if necessary.

**Comment by Spongman** [comment]
it maybe worth noting that the main text editor doesn't exhibit this behavior, nor do the output/log windows (the teminal window clear selection on thumb-mouse-down for some reason).

**Comment by joaomoreno** [comment]
@alexdima That strategy didn't work, since the click event comes after the monitoring stops... Can you maybe give it a try, see if you can come up with some better solution?

**Comment by alexdima** [comment]
@joaomoreno So when you receive a `click` event, it is not possible to determine if the original `mousedown` occurred in the same element? What about `e.relatedTarget`? Maybe that one shows the element that received the initial `mousedown`? What other options do we have? Should we call `e.preventDefault` of the `mouseup` event? Would that prevent the `click` event from firing?

**Comment by Spongman** [comment]
Really, this is expected behavior?

**Comment by joaomoreno** [comment]
Not expected, just not fixing it. Sorry about that. You can read more about it here: https://github.com/microsoft/vscode/wiki/Issue-Grooming#wont-fix-bugs
