### ISSUE TITLE
Workbench navigation commands do not work inside extension WebView panels.

### ISSUE THREAD

**Issue by MasonAsh** [microsoft/vscode#100536]
- VSCode Version: Up to date master branch
- OS Version: Windows 10

When a `WebViewPanel` in an extension is focused the workbench navigation commands do not work.  

Steps to Reproduce:

1. Have `workbench.action.navigateDown`, `workbench.action.navigateUp`, `workbench.action.navigateLeft`, and `workbench.action.navigateRight` bound to keys.
2. Use an extension that creates a `WebViewPanel`. For example the REST Client extension creates a webview after sending a request.
3. Focus the webview created and try to use any of the navigation keys to created in step 1. 

I debugged vscode and found that the culprit comes from `Layout.hasFocus` method, which is unable to find any of the `Parts` containers as an ancestor of a webview.

I think this is because webviews are mounted at a different part of the DOM with absolute positioning, so the `Parts` containers aren't found when crawling up the DOM from the focused element.

**Comment by infokiller** [comment]
I'm also hitting this bug and I'm able to consistently reproduce it in VSCode 1.49.1 with all extensions disabled, no settings, and only one keybinding defined. 

## Steps to reproduce

- Set the following keybindings:

  ```json
  [
    {
      "key": "f1",
      "command": "workbench.action.navigateLeft"
    }
  ]
  ```

- Open any file you want
- Use `workbench.action.splitEditorRight` to split the editor to the right
- Use `update.showCurrentReleaseNotes` to open the Release Notes WebView
- Type <kbd>F1</kbd> from the WebView to navigate to the left editor


VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 5.8.10

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 3455)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|31.03GB (1.45GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 39f0e56d-047c-4994-990f-e6e79755483c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|custom|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|custom|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by infokiller** [comment]
My current (limited) workaround is to use editor group focus commands like this:

```json
  {
    "key": "alt+j",
    "command": "workbench.action.focusLeftGroup",
    "when": "!editorFocus && !panelFocus && activeEditor == 'WebviewEditor'"
  },
```

**Comment by infokiller** [comment]
It looks like workbench navigation also doesn't work between split terminals.
