### ISSUE TITLE
Add option to duplicate file from the explorer

### ISSUE THREAD

**Issue by Rozz7niner** [microsoft/vscode#100567]
Many times i find myself needing a new file with the same content as an exsiting file. Would be nice to be able to right click a file a select duplicate. The duplacted file will then be created with a _1 suffix or something similar. Of course you can copy a file then paste it to the same folder, but this would be much quicker.

**Comment by gjsjohnmurray** [comment]
Did you try any extensions? For example https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils looks relevant.

**Comment by ArturoDent** [comment]
As a simple workaround - if you don't want an extension - you could make a keybinding to do this.  It isn't as nice as the `context menu/duplicate` option though.

```
  {
    "key": "alt+d alt+1",     whatever keybinding you wish
    "command": "workbench.action.terminal.sendSequence",
      "args": {
        "text": "touch '${relativeFileDirname}/${fileBasenameNoExtension}_1${fileExtname}' && cat '${file}' > '${relativeFileDirname}/${fileBasenameNoExtension}_1${fileExtname}'\u000D"
      },
    "when": "explorerViewletFocus || editorTextFocus"
  },
```

Uses bash commands `touch and cat`, replace with your shell's equivalent.  I added `_1` to the fileBasename for the duplicate, you could make that anything you wish.  Obviously, you would just be re-writing the same duplicate file every time if you used it more than once on the same "original" file.  Unless you make another keybinding for duplicate `_2` like this:

 ```
 {
    "key": "alt+d alt+2",
    "command": "workbench.action.terminal.sendSequence",
      "args": {
        "text": "touch '${relativeFileDirname}/${fileBasenameNoExtension}_2${fileExtname}' && cat '${file}' > '${relativeFileDirname}/${fileBasenameNoExtension}_2${fileExtname}'\u000D"
      },
    "when": "explorerViewletFocus || editorTextFocus"
  },
```
Again, you could change that `_2` to something else.


But the file's editor has to be "active" - either by clicking it in the explorer (not right-clicking) or when that editor has focus (you could change the `when` context of course).
