### ISSUE TITLE
Binary Custom Editor support on Live Share

### ISSUE THREAD

**Issue by ederign** [microsoft/vscode#100506]
We are really happy that Binary Custom Editor also works on visual studio core online. Congrats to everyone involved. ([gif](https://share.getcloudapp.com/2Nu5j2LD)).

I wonder what if the roadmap to also provide Binary Custom Editor on Live Share. Currently, they don't appear on the 'editing list' of a live share session. [gif](https://share.getcloudapp.com/8Lu7rwxg)

Is there anything related to this on the roadmap? 

I'm more than open to collaborating with this if necessary. Thanks and keep you the awesome work

Eder

**Comment by porcelli** [comment]
hi @mjbvz - is this considered for the binary custom editors?

**Comment by mjbvz** [comment]
Please start by filing this issue against live share. They can follow up with us if any changes are needed to support this on the VS Code side
