### ISSUE TITLE
you forgot to paste doesn't understand Chinese 😞

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#100588]
@JacksonKearl Looks like the ["you forgot to paste" bot](https://github.com/microsoft/vscode/issues/94731) doesn't understand Chinese 😞 

See also #100249 #98544 #95181 #91865 etc

_Originally posted by @yume-chan in https://github.com/microsoft/vscode/issues/100385#issuecomment-646687137_

**Comment by JacksonKearl** [comment]
@yume-chan could you possibly translate the text:

It looks like you're using the VS Code Issue Reporter but did not paste the text generated into the created issue. We've closed this issue, please open a new one containing the text we placed in your clipboard.

Happy Coding!

?

**Comment by yume-chan** [comment]
Sure. 

> 看起来您正在使用 VS Code 问题报告程序，但是没有把生成的文本粘贴到创建的问题中。我们将关闭这个问题，请使用剪贴板中的内容创建一个新的问题。
>
> 祝您使用愉快！

I don't think anyone would say "Happy Coding" in Chinese. It literally translates to "编程快乐！" or "祝您编程快乐！" (hope you happy coding), but that's wired.

So I'm using "祝您使用愉快！" that is "hope you have a great experience" (not specific to coding). Hard to make a decision.

**Comment by JacksonKearl** [comment]
Sounds good, thanks!

**Comment by JacksonKearl** [comment]
See #100597
