### ISSUE TITLE
Press and hold cmd/alt to show hotkey highlight

### ISSUE THREAD

**Issue by Alex-Mann** [microsoft/vscode#100521]
Much like excel has the alt+<SHORTCUT_KEY> command to do certain actions, it could be a really awesome feature to hold down cmd/alt and see shortcuts for navigation in vscode or button clicks.

The most obvious thing to me is navigating open windows/panes/consoles, but I'm sure there are other use cases too with respect to other useful shortcuts. VSCode is becoming more and more of a full-fledged editor/IDE which is great, but it is also becoming more difficult to be aware of all the useful shortcuts unless you spend considerable time looking at the pre-existing shortcuts in detail/keybindings/others settings/ etc.

Example screenshot attached below of how it works in excel:
![image](https://user-images.githubusercontent.com/4520864/85060486-55f9a180-b173-11ea-8f83-cf4ea356b3e1.png)

**Comment by isidorn** [comment]
looks like a feature request for the menu thus forwarding to @sbatten 
also fyi @sandy081 for keyboard shortucts

**Comment by sbatten** [comment]
I find that this is not really menu-specific but is trying to address the same issue that our command palette tries to solve. The menu already outlines the shortcuts for commands that it presents, but I think @Alex-Mann is look for a way to "see some piece of UI and learn how to interact with it via the keyboard"

**Comment by Alex-Mann** [comment]
Yes, that's correct, small visual cues indicating a button to press to jump to that part of the editor would be very useful. iTerm already does something like this and its a very useful feature for those not wanting to lift their hands from they keyboard during their workflow:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/4520864/85418529-e141b100-b53e-11ea-9817-cc995f4c8d02.png">

**Comment by sbatten** [comment]
@Alex-Mann This would be a pretty large shift for us in how we present keybindings. Today, our discoverability mechanisms go through menus and the command palette. For the command palette, it is keyboard driven and is searchable making it easier to find keyboard shortcuts on the fly. Can you speak to your experience with the command palette or ways we might improve that to address the issue?
