### ISSUE TITLE
Remote-SSH broken after update to 1.46.1

### ISSUE THREAD

**Issue by bitscuit** [microsoft/vscode#100586]
- VSCode Version: 1.46.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363

```
Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Steps to Reproduce:

1. Update VSCode from v1.46.0 to v.146.1
2. Remote-SSH: Connect to Host...
3. Choose host from list of hosts

After this, VSCode will continuously retry connecting (~30 times) to the host and eventually fail. The output has a lot of:
```
[11:41:50.199] > c775c92b5a1e: running
> 
[11:41:50.232] > Acquiring lock on /root/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05
> f5d/vscode-remote-lock.root.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
> 
[11:41:50.240] > \ln /root/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/vscode-rem
> ote-lock.root.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d.target /root/.vscode-serv
> er/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/vscode-remote-lock.root.cd9ea648
> 8829f560dc949a8b2fb789f3cdc05f5d
> ln: failed to create hard link '/root/.vscode-server/bin/cd9ea6488829f560dc949a8
> b2fb789f3cdc05f5d/vscode-remote-lock.root.cd9ea6488829f560dc949a8b2fb789f3cdc05f
> 5d': File exists
> Installation already in progress...
> c775c92b5a1e##24##
> 
[11:41:50.240] Received install output: c775c92b5a1e##24##
[11:41:50.240] Server installation process already in progress - waiting and retrying
[11:41:50.520] "install" terminal command done
[11:41:50.521] Install terminal quit with output: 
[11:41:51.243] Running script with connection command: ssh -T -D 56960 <host ip here> bash
[11:41:51.245] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:41:51.296] > 
```
* I replaced the IP with `<host ip here>`.

If I revert back to v1.46.0, I can Remote-SSH again to my host.

Does this issue occur when all extensions are disabled?: Yes (with only the `Remote - SSH` and `Remote - SSH: Editing Configuration Files` extensions enabled)

**Comment by SummerYY16** [comment]
I met the same problem

**Comment by lidanqing123** [comment]
i met the same problem，too！ [100734](https://github.com/microsoft/vscode/issues/100734)

but no one responsible for solving this problem!

**Comment by bitscuit** [comment]
Is there a bug label or some way to add labels? I don't know why the `new release` label was removed, nor how to attract attention to this issue for someone to pick up

**Comment by stuarteberg** [comment]
FWIW, I ran into this issue, and running `rm -rf ~/.vscode-server` on the remote machine resolved it.

**Comment by roblourens** [comment]
Sorry, this is https://github.com/microsoft/vscode-remote-release/issues/2518, and running the command "Kill VS Code Server on Host" is the suggested workaround
