### ISSUE TITLE
Control+K twice can't kill the \n

### ISSUE THREAD

**Issue by learning** [Microsoft/vscode#10056]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:
1. `Control+a` jump to the beginning of line
2. `Control+k` kill the line
3. `Control+k` again to kill the new line character `\n`, **IT DOES NOT WORK**

`Control+k` it's the common behaviour in macOS just like emacs & shell, it works in most macOS applications.

**Comment by alexandrudima** [comment]
I have just double checked that this now works correctly. It was a fix from @joaomoreno
