### ISSUE TITLE
Git Fatal error: File outside repository

### ISSUE THREAD

**Issue by Lewiscowles1986** [microsoft/vscode#100553]
- VSCode Version: 1.46.1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Setup git with `core.ignorecase = false`
2. try to add a file where the full-path has mixed case
3. See error

Does this issue occur when all extensions are disabled?: Yes/No

Yes (technically it is a git issue)

Suggested remediation:

1. You could let people know, in more human terms that this is a git config issue, and that `core.ignorecase = true` in a `.gitattributes` or global config will overcome the error surfaced via vscode.
2. You could use the relative path to the file from the workspace. In my case my repository only contains lower-case files, so using relative path, git has no issues.

This IS a resolution rather than closing of locked #88890
this IS NOT a duplicate of #41246 or #85666 which are entirely separate

**Comment by Lewiscowles1986** [comment]
![screenshot of vscode about](https://user-images.githubusercontent.com/2605791/85099755-2b046180-b1f6-11ea-85ba-0b70bc98ffb3.png)

![Screenshot of the alert where whitespace is edited to remove repository name](https://user-images.githubusercontent.com/2605791/85099833-66069500-b1f6-11ea-99d4-661bfe5aa289.png)

**Comment by gjsjohnmurray** [comment]
@Lewiscowles1986 what is the version number of your local Git? There have been several similar issues opened lately that got resolved by a Git update.

**Comment by Lewiscowles1986** [comment]
```
$ git --version
git version 2.9.0.windows.1
```

I'll try with 2.27.0 64-bit (I'm on 64-bit Windows 10 when experiencing. No issues on Linux or Mac)

**Comment by Lewiscowles1986** [comment]
can confirm that newer Git does not have the issue... My bad. Closing

```
$ git --version
git version 2.27.0.windows.1
```

**Comment by stilllife00** [comment]
On a side not I had vscode git path configured to point to a different version of git that the one used globally (e.g. in the terminal).
In that case, make sure the user setting `"git.path": "...` is pointing to the proper git version
