### ISSUE TITLE
Wavy yellow ligne under " float: left; " in a css file

### ISSUE THREAD

**Issue by aminkala** [microsoft/vscode#100596]
We have written the needed data into your clipboard because it was too large to send. Please paste.

header nav
{
    float: right;
    margin-top: 50px;
}
header nav ul li
{
    float: left;
    display: inline-block;
}

This happens only when I put   "display: inline-block;"   along with the   " float: left; "   instruction.

CPUs | Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 3.92GB (0.57GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
alignment | ann | 0.3.0
vscode-eslint | dba | 2.1.5
php-debug | fel | 1.13.0
php-intellisense | fel | 2.3.14
php-pack | fel | 1.0.2
vscode-firefox-debug | fir | 2.9.0
debugger-for-chrome | msj | 4.12.8
LiveServer | rit | 5.6.1
open-in-browser | tec | 2.0.0
![image](https://user-images.githubusercontent.com/66949235/85162761-28d7ec80-b262-11ea-9fcb-35e7f8cbb7a6.png)

**Comment by ArturoDent** [comment]
If you hover over the squiggled property, you get this explanation:

> inline-block is ignored due to the float. If 'float' has a value other than 'none', the box is floated and 'display' is treated as 'block'css(propertyIgnoredDueToDisplay)

So it is saying that `inline-block`  and `float` are incompatible - the `inline-float` setting will be ignored.

  If you nevertheless wish to disable that warning, change the following setting to `ignore`.  There are similar settings for `scss.lint` and `less.lint`.

 

>  // Property is ignored due to the display. E.g. with `display: inline`, the `width`, `height`, `margin-top`, `margin-bottom`, and `float` properties have no effect.

>  ` "css.lint.propertyIgnoredDueToDisplay": "warning",`

**Comment by aeschli** [comment]
Thanks @ArturoDent!
