### ISSUE TITLE
deploy source to org 

### ISSUE THREAD

**Issue by kapreddy** [microsoft/vscode#100566]
Performance Issue on Visual Studio

after updating or creating a code i am **unable to deploy source to org** on visual Studio after the latest update 1.45.1

VS Code version: Code 1.45.1 
 i am able to delete , create but unable to deploy
 
Please resolve issue ASAP 
Thanking Advancily

**Comment by gjsjohnmurray** [comment]
Are you working with Salesforce using the SFDX extension?

**Comment by kapreddy** [comment]
> Are you working with Salesforce using the SFDX extension?

yes

**Comment by gjsjohnmurray** [comment]
/causedByExtension Please report it to the extension developers.

**Comment by kapreddy** [comment]
> /causedByExtension Please report it to the extension developers.

how to report it

**Comment by kapreddy** [comment]
> This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the [marketplace](https://aka.ms/vscodemarketplace) for VS Code. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

ok
