### ISSUE TITLE
"your 131072x1 screen size is bogus, expect trouble"

### ISSUE THREAD

**Issue by nukoyluoglu** [microsoft/vscode#100563]
Issue Type: <b>Bug</b>

ctrl-shift-p, "Debug: Start Debugging" leads to this error. I saw that this error was previously mentioned and fixed in a recent update, but the error persists. 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.95GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/v-naugur --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2593)|
|Memory (System)|6.10GB (4.98GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
regex|chr|0.2.0
gitlens|eam|10.2.2
vscode-pull-request-github|Git|0.17.0
vscode-codemetrics|kis|1.24.0
cpptools|ms-|0.28.3
vscode-versionlens|pfl|1.0.8
java|red|0.63.0
vscodeintellicode|Vis|1.2.8
application-insights|Vis|0.4.2
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
code-lens-roundup|wad|1.0.0
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.3
vscode-remote-extensionpack|ms-|0.20.0

</details>

**Comment by Alirezanet** [comment]
Same problem vscode v1.47.3. any update on this issue?

**Comment by nukoyluoglu** [comment]
> Same problem vscode v1.47.3. any update on this issue?

@Alirezanet The issue was fixed in this insiders release: https://github.com/microsoft/vscode-cpptools/releases/tag/0.29.0-insiders2

**Comment by weinand** [comment]
@Alirezanet what debugger are you using?

**Comment by Alirezanet** [comment]
@weinand Dotnet Core.
```json
      "name": ".NET Core Attach",
         "type": "coreclr",
         "request": "attach",
         "processId": "${command:pickProcess}",
```

**Comment by weinand** [comment]
@Alirezanet thanks. That debugger is a separate extension (C#). Please file an issue against that.

We have fixed a similar problem with the Node.js debugger (which is built into VS Code). But that fix does not cover the C# debugger.
