### ISSUE TITLE
Ship ffmpeg with VS Code

### ISSUE THREAD

**Issue by allefeld** [microsoft/vscode#100599]
The [Python extension for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ms-python.python) has made VS Code one of the best Python editors out there. This is especially facilitated by its support for __Jupyter notebooks__. Notebooks are tools that allow interactive data analysis and visualization, and are popular among engineers, scientists, and people working on corporate data analysis, probably among others. One important feature of notebooks is that it allows to show data directly in the notebook interface, in the form of plots (vector graphics), bitmap images, __video and audio__. The latter two are obviously important for people who work in video / audio processing and generation, e.g. computer vision and language recognition.

However, audio/video display does not work in notebooks in VS Code. This was filed as an issue https://github.com/microsoft/vscode/issues/80196 on VS Code itself, where it was classified as `caused-by-extension`, i.e. the Python extension.

It was also filed as issues https://github.com/microsoft/vscode-python/issues/3456 and https://github.com/microsoft/vscode-python/issues/3405 on the Python extension, where however it was determined that it is not caused by the extension, but is due to the fact that audio and video are not supported by webviews in VS Code.

Well, there is an issue https://github.com/microsoft/vscode/issues/54097 regarding that on VS Code, which was closed with the lakonic statement

> We don't ship ffmpeg in our electron build. Many audio and video formats are therefore not supported inside webviews. No plans to change this

I feel that __wires have been crossed__ here due to the issues being spread over VS Code vs the Python extension. Regarding VS Code, it is understandable that audio/video support does not appear to be relevant for a code editor. It is however relevant for the Python extension, because it sets the notebook provided by the extension back relative to "native" Jupyter notebooks.

__Long story short__: I think it is in the best interest of VS Code as a  multi-language editor to enable feature complete development environments for all languages, and to enable that for Python would mean to support audio/video, which means VS Code needs to be shipped with ffmpeg.

Please reconsider the decision on https://github.com/microsoft/vscode/issues/54097. (I would have commented on that issue, but it is locked.)

**Comment by andycloke** [comment]
Has anyone found a way around this in the mean time? e.g. by including ffmpeg + binaries with an extension

**Comment by allefeld** [comment]
I wouldn't even mind if I had to manually copy the necessary libraries into some directory.

**Comment by YXL76** [comment]
[nondanee/vsc-netease-music](https://github.com/nondanee/vsc-netease-music#requirement) is a music player extension. It has a tutorial about how to replace ffmpeg.

**Comment by mjbvz** [comment]
Closing as we don't have near term plans to include ffmpeg due to licensing and security concerns
