### ISSUE TITLE
Provide unified intelligent completion services for mainstream programming languages

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/vscode#100564]
Vscode performs well in all aspects, the only drawback is that his code completion and smart tips are not very good. For example, Python's language server will take up a lot of CPU and memory, causing the computer to freeze. Java's intelligent completion is a mess. I hope you can provide unified intelligent completion services for mainstream programming languages, rather than using different services for different programming languages. When can I get an intelligent completion experience like pycharm and idea.

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/82024
