### ISSUE TITLE
Quick outline: Preserve symbol choice (@ vs @:)

### ISSUE THREAD

**Issue by Menelion** [microsoft/vscode#100573]
In Outline view, I'd like to have my chosen symbols preserved when I reopen the view (see below.

**Steps to Reproduce**:

1. Open a project, folder or file in VS Code Insiders.
2. Press **Ctrl**+**Shift**+**O** to open the Outline view.
3. Note that there is an `@` character already in the edit box. Add a `:`, i.e., make it `@:` to skim through the symbols in the code.
4. Close the view by pressing the **Escape** key.
5. Press **Ctrl**+**Shift**+**O** again.

**Actual Result**: There is a lonely `@` character again.  
**Expected Result**: `@:` should be preserved from the last input.

**Comment by bpasero** [comment]
As a workaround, you can configure a keybinding to bring `@:` up:

```json
{
	"key": "cmd+7",
	"command": "workbench.action.quickOpen",
	"args": "@:"
}
```

There is a bug currently where the `:` gets selected, but I pushed a fix in https://github.com/microsoft/vscode/issues/100584

**Comment by Menelion** [comment]
@bpasero Thanks. May I also ask a (somewhat) relevant question: are there any more special characters there like `@` or `@:`? If not, are they planned? Thanks!

**Comment by bpasero** [comment]
If you type `?` into the input field you can see the list of available symbols.
