### ISSUE TITLE
docked debug tool bar not able to start multiple sessions any more

### ISSUE THREAD

**Issue by holdfenytolvaj** [microsoft/vscode#100583]
Issue Type: <b>Bug</b>

In settings change the 'Debug: Tool Bar Location' to 'docked'.
- start one debug session
- press '...' then 'start additional session' and choosew as you wish.

afterwards nothing happens (previously you could see the secondary session in 'call stack')
Everything works as normal with 'floating' tool bar location so two sessions are still possible (and also shows both if changed back to 'docked' afterwards).

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux

**Comment by blumanfry** [comment]
My team found running a session with the same name will not run. We had to rename one of the config's to a different name and it would run a 2nd debugger session: https://github.com/microsoft/vscode/issues/100589

**Comment by sirlancelot** [comment]
Confirmed on Mac as well

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/99786

Sorry about this. Please use vscode insiders which has this fixed.
