### ISSUE TITLE
few of the code is not runnig after compilation

### ISSUE THREAD

**Issue by tanvir1098** [microsoft/vscode#100598]
Issue Type: <b>Performance Issue</b>

I have written a code in C language,after the compilation few of the code does not runs.
This is my code :#include <stdio.h>
#include <conio.h>
int main()
{
    int ref_year = 1901, year, day = 0, leap = 0, total_days, diff;
    printf("Enter the year.\n");
    scanf("%d", &year);

    diff = year - ref_year;
    while (ref_year < year)
    {
        if (ref_year % 100 == 0)
        {
            if (ref_year % 400 == 0)
            {
                leap++;
            }
        }
        else
        {
            if (ref_year % 4 == 0)
            {
                leap++;
            }
        }
        ref_year++;
    }
    total_days = (diff - leap) * 365 + leap * 366;
    day = total_days % 7;
    printf("The day on the January of %d was/will be :\n ", year);

    switch (day)
    {
    case '1':
        printf("Monday");

        break;
    case '2':
        printf("Tuesday");
        break;
    case '3':
        printf("Wednesday");
        break;
    case '4':
        printf("Thrusday");
        break;
    case '5':
        printf("Friday");
        break;
    case '6':
        printf("Saturday");
        break;
    case '7':
        printf("Sunday");

    default:
        break;
    }

    return 0;
}
switch case does not Executes .
Please help. 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	    85	  3972	code main
    0	    14	  4624	   electron-crash-reporter
    0	    25	  9580	   utility
    0	    64	  9584	   shared-process
    7	    71	 10024	   window (Issue Reporter)
    0	   216	 10348	   window (practice12.c - C Programs - Visual Studio Code)
    0	    14	  1808	     watcherService 
    0	    11	  7388	       console-window-host (Windows internal process)
    0	    92	 11620	     extensionHost
    0	    23	  9244	       c:\Users\hp\.vscode\extensions\ms-vscode.cpptools-0.28.3\bin\cpptools.exe
    0	    14	  1672	         "c:\Users\hp\.vscode\extensions\ms-vscode.cpptools-0.28.3/bin/cpptools-srv.exe" 9244 0
    0	     8	  2752	         console-window-host (Windows internal process)
    0	     6	 12204	     console-window-host (Windows internal process)
    0	    69	 13300	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    3	   289	 11364	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (practice12.c - C Programs - Visual Studio Code)
|    Folder (C Programs): 17 files
|      File types: c(16) exe(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
code-runner|for|0.10.0
cpptools|ms-|0.28.3
commandlist|yam|1.0.3

</details>

**Comment by gjsjohnmurray** [comment]
> switch case does not Executes .
> Please help.

Maybe time to try using VS Code's [debugging capabilities](https://code.visualstudio.com/docs/editor/debugging).

**Comment by eamodio** [comment]
If you are having C/C++ issues I would recommend open an issue with the C++ extension
