### ISSUE TITLE
History: Fuzzy-filter: prioritize word-boundry matches

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#100590]
Suggestion: fuzzy filtering can prioritize matches at word starts, as IMO it's more likely for someone to be typing from a wordstart than a random substring.

For instance, here I'm typing the first part of `actions`, but other things come first.
in this case I'd expect either `apply-changes` or `actions` to be at the top, followed by the other.
![image](https://user-images.githubusercontent.com/8586769/85157175-fa312600-b20f-11ea-8079-a77f69a8eef3.png)

This is what I do in the triage extension, https://github.com/microsoft/vscode-github-triage-extension/blob/eb3bd12d537a152aba60783aeee3e527fd8bfabf/src/common/fuzzyMatch.ts#L17-L29

**Comment by jrieken** [comment]
Yeah, [`fuzzyScore`](https://github.com/microsoft/vscode/blob/696dca786ac73ca0779a65e18f4bdb613d66b26f/src/vs/base/common/filters.ts#L541) does that. It boosts matches after separators and makes sequences of contiguous matches score higher. So, in theory it should work... However, I believe this part of quick pick doesn't use fuzzyScore.

**Comment by bpasero** [comment]
I think you are seeing history matches where we use a slightly different matcher strategy, in general history matches always come first using a less fuzzy scorer and then use a fuzzy scorer that does what you ask, see:

https://github.com/microsoft/vscode/blob/68bf05a59c10985cfbfc8aa8dbd34235085ddb2f/src/vs/base/common/fuzzyScorer.ts#L193-L195

I will add this to https://github.com/Microsoft/vscode/issues/27317

**Comment by JacksonKearl** [comment]
Ah okay, so in this case I'm viewing the recently opened folders, filtered by those that have any match with the query, then sorted alphabetically? 

Would it be possible to optionally remove last alphabetic sort step, so that I view the results in fuzzyScore order always? That or recency of access, in the above case I'm working in vscode-github-triage-actions pretty much every day, and the others quite rarely, but traige-actions is still always at the bottom.

**Comment by bpasero** [comment]
@JacksonKearl I think what you are suggesting is a setting to always sort both history and file results fuzzy? This would mean that history results no longer get a boost over other results? Basically you can do this today already via `"search.quickOpen.includeHistory": false`

**Comment by JacksonKearl** [comment]
This is with regards to `recent workspaces` (workbench.action.openRecent), which seems unaffected by that history setting (they're all history). 

It initially looks like:
![image](https://user-images.githubusercontent.com/8586769/85766948-60182480-b6cc-11ea-9e6d-8f63d55f30d3.png)
 
Which seems to be sorted by recent use (good)

I then type `ac` and I get this:
![image](https://user-images.githubusercontent.com/8586769/85767047-7920d580-b6cc-11ea-9de0-a0d981812fc3.png)

Which is sorted alphabetically (bad). I would expect the filtered list to be sorted either by fuzzy match score or by recency of use, alphabetics doesn't seem very useful.

**Comment by bpasero** [comment]
@JacksonKearl that is just a normal picker, it does not use fuzzy scoring.

/duplicate https://github.com/microsoft/vscode/issues/34088

**Comment by JacksonKearl** [comment]
Sad.
