### ISSUE TITLE
Extension is sometimes corrupted when upgrading/installing

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#100537]
Version: 1.47.0-insider (user setup)
Commit: 84f52fe1c0124307046ac0f5443493cda946e60f
Date: 2020-06-17T06:43:38.511Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

I do not have a reliable repro for this, but we have had numerous bug reports from users of the C/C++ Extension of failures that appear to be due to files missing from the extension's directory.  Re-installation of the extension addresses the issue.  Reports of this issue have recently become common.  I have now repro'ed a similar issue myself.  It appears that VS Code Insiders failed to fully extract all files from a vsix while applying an update of our extension from the marketplace.  After repro'ing failures trying to use the extension, I moved the installation directory, reinstalled the extension, and compared the directories.  All files were present in the newly installed directory, but various files (that are present in the vsix) were missing from the prior directory.

I was not monitoring the progress of updating the extension, so I do not know for sure, but I suspect the issue may be due to having terminated VS Code Insiders while it was still in the process of apply the update.

**Comment by sandy081** [comment]
Is there a way to repro this? If you are using our latest insiders and you are reproducing this please check if the downloaded VSIX is complete or not? You can get the downloaded VSIX in the parent directory of your user settings

`{parent of settings}/CachedExtensionVSIXs`

**Comment by Colengms** [comment]
@sandy081 You may want to re-open this.  I think your questions are answered in my original message.  As I indicated, I do not have a repro.  We have had many reports, but I have only repro'ed once myself.  As mentioned, after my repro and deleting the installed extension directory, a subsequent install was successful.  I did not delete the downloaded VSIX.  Unless VS Code deleted and re-downloaded it, perhaps that implies that the VSIX was intact?  I'm afraid I don't have further information to offer.  However, as users continue to report the issue, I would be glad to refer them to this issue to allow you to follow up.  Could someone knowledgeable of the extension installation process review the implementation to ensure terminating the application while that is in progress would not lead incomplete extraction?

**Comment by sandy081** [comment]
Reopened.

It seems I did not get answer for following question

> if you are using our latest insiders and you are reproducing this please check if the downloaded VSIX is complete or not? You can get the downloaded VSIX in the parent directory of your user settings
`{parent of settings}/CachedExtensionVSIXs`
