### ISSUE TITLE
Need solve problem with breakpoints and bookmarks - TAGS

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#100579]
Regarding this:
https://github.com/alefragnani/vscode-bookmarks/issues/313
Expeting this type solution like on image:

1. Bookmark must be shadow layer under breakpoint
2. Bookmarks must should have own counters
https://marketplace.visualstudio.com/items?itemName=alefragnani.numbered-bookmarks
3. Breakpoints need to have labels like bookmarks
4. Both Breakpoints and Bookmarks need searching by part of code in line or label
5. I often need sorting the "labels" by importancy for curent work
6. Sometimes I'm looking grouping some labels due to parts related in whole project and many files, eg. specialy views in MVC and realted files in any of part by M V C as related module/component of project
7. In relation of this is Outline - there is some poor support for searching/contex (like on breadcrumbs - like often stay with some contex search due curent work of some classes or functions realted with similar headnames to easy find/work), searching by types or grouping by types, coolapsing all, and colapsing levels/types
https://github.com/microsoft/vscode/issues/83127
8. It's can by nice to show the NOC (number of code) in breadcrumbs similar for outline, and bookmarks with TODO list
- I'm trying experiment with `#TODO: 'timestamp'` like `TODO: 2020-06-06 12:12` and `TODO: 'count'` as `#TODO: 1 = the text to be more effective and looking way to optimize this and by filtering with data`, finaly this is simillar like roadmap for PO (product owner) and RFR (role-feature-reason) or `RFRR` (role-feature-reason-request), by this is fine to do something like `RFRR: 2020-06-06 12:12 =  As a user , want bether manage my code in VSC , so that need consolidation for TODO: 1 and TODO: 2020-06-06 12:12` 
- so there is problem to easy put timestamp and current count from sumarized TODO in whole project or files that can support coders
- I'm often doing something like `#TODO: [x]` due that someone doing for me `#TODO: [ ]` ; ) after made days targets for some FIXes or updateds i know how made was done and reporting, when winished then `#TODO: [x]` i replacing for empty and going commit this (as reflection how we playing sometimes in remote work)
- coz bookmarks are local in git we using `#NOTE:` that emulate bookmarks by VSC not suporting this `TAG` soo.. I thing we should add this type solution to organize and set some tags for projects
- sometimes is  `#TODO: user = when you broken this code CTO said repair this` thats mind can be some Regex for `TAGS` not simple `TODO`
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree
9. What this all minds, that `TAGS` can have own colours in relations first points and image bellow as lablel/markers and the commented code line text can be in dedicated colour (it's experiemntal vision)
10. The shortcuts for whole tags and option to put on code quickly by this
![VSC_Bookmark](https://user-images.githubusercontent.com/25403861/85130863-fe703a00-b235-11ea-8923-520835ed2adf.png)
![VSC_TAGS](https://user-images.githubusercontent.com/25403861/85133951-f9ae8480-b23b-11ea-8d19-5c6e7c6cfdd6.png)
![VSC_git improvements around tags](https://user-images.githubusercontent.com/25403861/85134331-9b35d600-b23c-11ea-8d75-1fcca0dfe2d3.png)

**Comment by alefragnani** [comment]
@ManPython,

As I [commented here](https://github.com/alefragnani/vscode-bookmarks/issues/313#issuecomment-646674370), the _automatic bookmarking_ feature is more related to the [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) extension, so I suggest you to mention the developer. I’m not sure the features it has, so I can’t say which one could or could not be implemented.

Some of the _gutter features_ and _tree view filtering_ you pointed out has already been requested to have available APIs, but some has closed after some time. I’m not sure which one are still open, but I guess the VS Code team could point you to the right ones.

About the _bookmarks should have numbering_, in fact, you should use that other extension :smile:

Hope this helps

**Comment by weinand** [comment]
It is difficult to act on an issue that combines an existing VS Code (breakpoints) with a feature that is implemented outside of VS Code. We have no plans to support TODO items based on existing breakpoints. Breakpoints are a fundamental part of the VS Code debugger and we don't want to dilute them by adding non-breakpoint features.

If you need more extension API to implement TODO items, then file feature requests but please don't stipulate that they these features must be breakpoint features.
