### ISSUE TITLE
Markdown Live Preview does not render pictures

### ISSUE THREAD

**Issue by t-jaxian** [microsoft/vscode#100531]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Use a relative link to reference a picture that is several subfolders up in your tree structure using Markdown
2. Open Markdown Live Preview, image does not load

![VSCode Bug](https://user-images.githubusercontent.com/66283214/85074002-ad4a4280-b170-11ea-86db-06654af8e06d.PNG)
![VSCode Bug 2](https://user-images.githubusercontent.com/66283214/85074004-ae7b6f80-b170-11ea-9163-df1b89aeb465.PNG)

The picture renders fine on Github but not on VSCode. This issue persists for both Markdown `.md` and Jupyter notebooks `.ipynb`

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Is the file you are linking to within your workspace? The markdown preview only supports loading resources from the current workspace

**Comment by t-jaxian** [comment]
Ah that makes a lot of sense, thanks.

**Comment by mjbvz** [comment]
Was that the issue?

**Comment by t-jaxian** [comment]
Yup, thanks!
