### ISSUE TITLE
ES6 code highlighting broken after "for of" with Map and destructuring

### ISSUE THREAD

**Issue by joseroux** [Microsoft/vscode#10053]
- VSCode Version: Code - Insiders 1.4.0-insider (e3758d2cdaae78082a08a45ae28ea1bed5f47e8c, 2016-07-29T18:41:58.915Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1. type the following code
```
for( let [k, component] of this.components){
    let bounds = component.view.getBounds(); /// <= not highlighted, nor anything after this
}
```
![code-bug-example](https://cloud.githubusercontent.com/assets/5633182/17349310/9de3c952-58ea-11e6-9007-ec3753ab04f4.png)
:  
Everything that follows is not highlighted...

The square brackets seem to be the problem; adding a semi-colon after fixes the highlighting (but of course is not valid code).

**Comment by joseroux** [comment]
Hum, sometimes highlighting works, sometime not, and when it's not working, putting the opening curly bracket on next line corrects the problem partially... but it's still broken in next method!

Will try to see why, but basically the context is the same - a for loop in a class method.
![code-bug-example2](https://cloud.githubusercontent.com/assets/5633182/17349753/65f0bf88-58ee-11e6-936e-dfe2048a9100.png)

**Comment by joseroux** [comment]
Wow. Perfect storm, or something. The problem is only happening in a very precise way: if I remove any of these loops, it works!!! Here's the minimal complete example that breaks the highlighting:
![code-bug-example3](https://cloud.githubusercontent.com/assets/5633182/17352008/4dba2112-5901-11e6-8acc-9790d7f87e94.png)

Here's the code, if ever someone is crazy enough to try and fix this !

```
class Test0 {
	method(){
		function func(){
			for( let [key, val] of tests)
				val.id = 0;
			for( let [key, val] of tests)
				val.id = 0;
			for( let [key, val] of tests)
				val.id = 0;
		}
	}
	method2(){ /// <- FROM NOW ON, METHODS' NAME OTHER THAN 1ST AREN'T HIGHLIGHTED' 
		for( let [key, val] of tests){
			// 
		}
	}
}
class Test1 extends Container {
	method(){
		for( let [ key, val] of tests){
			//
		}
	}
	method2(){
		//
	}
}
class Test2 extends Container {
	method(){
		for( let [ key, val] of tests){
			//
		}
	}
}
class Test3 {
	method(){
		for( let [key, val] of tests){
			//
		}
	}
}
class Test4 { 
	constructor(){
		// messed up
	}
	method(){
		// messed up
	}
}
class Test5 {
	// no hope
}
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#232
