### ISSUE TITLE
Unable to open a fresh install of VS code on windows 10

### ISSUE THREAD

**Issue by shrinivas96** [microsoft/vscode#100512]
- VSCode Version: x64, 1.46.0
- OS Version: Windows 10 Home Version 1909

Steps to Reproduce:

1. Download [VS Code](https://code.visualstudio.com/download) system installer
2. Open VS Code from windows start menu or anywhere
3. `code --verbose` in a folder displays:

Unable to read argv.json configuration file in C:\Users\shrin\.vscode\argv.json, falling back to defaults (Error: EPERM: operation not permitted, open 'C:\Users\shrin\.vscode\argv.json')
[main 2020-06-18T17:05:17.308Z] Error: EPERM: operation not permitted, mkdir
[main 2020-06-18T17:05:17.309Z] Lifecycle#kill()

Does this issue occur when all extensions are disabled?: Yes

**Comment by PeterWone** [comment]
The error _tells_ you it's a permission problem.  The remaining question is why.

- Have you looked at the permissions on that folder? 
  - What are they?
  - Does manually editing permissions resolve the problem?
- Did you do a system install or a user install?

**Comment by bpasero** [comment]
Sorry, I cannot find anything VSCode is doing wrong. If VSCode cannot read files from user home on startup due to permissions, then this is a configuration problem the user needs to solve.
