### ISSUE TITLE
File modified on disk not noticed or loaded in VS Code IDE

### ISSUE THREAD

**Issue by ChrisWestermann** [microsoft/vscode#100504]
Issue Type: <b>Bug</b>

If I am already viewing a file in VS Code and the file is modified on disk there is no real indication that the file has changed, except that the "x" button on the tab subtly changes to a solid circle to indicate that the current viewing content is modified from the disk content.  The problem is that you can easily save over the modified file content unexpectedly because you are not aware that the file content changed since you last opened the file.

One common workflow I use with VS Code is to view an output file and then test/develop code that modifies the output file; it is VERY frustrating at first to see apparently none of the expected modifications to the file content after executing code, which leads to assuming the code did not produce the correct changes and wastes time troubleshooting code that worked perfectly well.  Also, the only way to get the actual changes is to close the file, knowingly refuse to save the "modified" content, and then reload the file.  This is an unacceptable workflow.

I would expect the same behavior like ALL basic text editors that if the file is modified on disk a dialog or notification is shown that content has changed and the user has the option to load or ignore changes so that a developer can safely notice and deal with this situation.  I want to see a yellow bar on the top of the file that the content has been modified externally since it was last opened and option to reload or ignore the changes.

If this feature already exists then the option should be turned on by default as I have not modified the out of box experience of VS Code and this is unexpected behavior.  Also I should not have to hunt for a setting or find and install or write an extension to VS Code for it to work properly as a basic text file viewer.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (16.22GB free)|
|Process Argv|D:\Development\Work\Bedrock\deploy\Bedrock.Azure.Deploy\bin\Debug\staging\Bedrock.Azure.Deploy\appsettings.Development.json|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
prettify-json|moh|0.0.3
vscode-docker|ms-|1.3.0
csharp|ms-|1.22.1
powershell|ms-|2020.6.0

</details>

**Comment by isidorn** [comment]
This works fine for me.
Can you reproduce with vscode insiders? https://code.visualstudio.com/insiders/

If yes, please file a new issue with exact concise steps, not a novel. Thanks!
