### ISSUE TITLE
iosevka font not working

### ISSUE THREAD

**Issue by Airbus5717** [microsoft/vscode#100515]
Issue Type: <b>Bug</b>

i've tried this font many times and its not working in vscode 
i tried other custom fonts and it worked
font link : https://typeof.net/Iosevka/

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aasutossh** [comment]
Yes, I am trying Iosevka NF for an hour and turns out it's vscode's issue. I can use FiraCode NF but not Iosevka. Something wrong with this definitely.
