### ISSUE TITLE
rejected promise not handled with latest insiders

### ISSUE THREAD

**Issue by badsyntax** [microsoft/vscode#100577]
- VSCode Version: 1.47.0-insiders (Commit: 8cd3fe080bee38d28ba01d0d71713d6ec22b254e Date: 2020-06-19T05:44:44.062Z)
- OS Version: macos catalina

Steps to Reproduce:

I cannot reproduce with a simple case. It seems like a race condition again, similar to https://github.com/microsoft/vscode/issues/98080

I get this error in my [CI tests](https://github.com/badsyntax/vscode-gradle/runs/787933868?check_suite_focus=true) (and local) when running `vscode.tasks.executeTask(task)`:

```
rejected promise not handled within 1 second: Error: [object Object]

stack trace: Error: [object Object]
	at /home/runner/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:889:991
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Although that error message is not very helpful, I was able to debug `extensionHostProcess.js` to see the actual error, which is:

```
code:5
message:'Task to execute is undefined'
severity:1
```

I believe it's a bug in vscode, as I cannot catch this error. I was not getting this error with the previous insiders version.

Does this issue occur when all extensions are disabled?: Yes

cc @alexr00

**Comment by badsyntax** [comment]
Hi @alexr00 After a bit of tinckering I have figured out how to reproduce this bug. 

1. Clone/download this repo: https://github.com/badsyntax/vscode-executetask-test-example
2. `npm i`
3. `npm run compile`
4. `code .`
5. Run the `Run Extension` launch configuration
6. Note a custom terminal is not created

In your debug console, you should see:

```
rejected promise not handled within 1 second: Error: [object Object]
extensionHostProcess.js:3842
stack trace:  Error: [object Object]
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:3459:39
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

I've added some comments to [extension.ts](https://github.com/badsyntax/vscode-executetask-test-example/blob/1fa7957767129e438d2c4fa26e04389fde016dbe/src/extension.ts). It looks like the bug occurs when the task has a `vscode.CustomExecution` and when you retrieve the task via `vsode.tasks.fetchTasks` to execute it.

**Comment by alexr00** [comment]
@badsyntax thanks for the repro! I tracked it down to two separate problems, and I've added a test for this.

**Comment by badsyntax** [comment]
Awesome thanks! Will verify with the next insiders build.

**Comment by badsyntax** [comment]
I have verified this fix is working with the latest insiders.

**Comment by alexr00** [comment]
Thanks for verifying!
