### ISSUE TITLE
Integrated terminal doesn't show up when vscode is lauched from terminal

### ISSUE THREAD

**Issue by slashformotion** [microsoft/vscode#100502]
- VSCode Version: 1.46.0
- OS Version: Linux Mint 19.3 Tricia x86_64

Steps to Reproduce:

1. Launch VS Code from terminal  `code .` , `code --disable-extensions . `, `code`  or `code --disable-extensions `
![image](https://user-images.githubusercontent.com/45801817/85031373-e25d9180-b17e-11ea-9ec7-f7a552aa72df.png)

2. When vs code is launched, the integrated terminal is not there.
![image](https://user-images.githubusercontent.com/45801817/85031511-0f11a900-b17f-11ea-8ce9-a9207d83ff9a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaopedroaats** [comment]
I had the same problem with manjaro, just remove `terminal.integrated.inheritEnv` or set it to true in settings.json; if it doesn't work, try cleaning the settings.json as the issue #83100 recommends
