### ISSUE TITLE
Better localisation support for error (original English button)

### ISSUE THREAD

**Issue by jonlepage** [microsoft/vscode#100514]
Hey guys, it very nice to read and understand eroor in our native language, but is it possible to add a original localisation icon support ?
Because sometime if we need copy past error on the web for search or talk about a error, it not useful to translate the message, and sometime the translate dont give the real original English message.

![image](https://user-images.githubusercontent.com/24865815/85054621-56416f00-b16a-11ea-8909-8a16f4bfb4cb.png)
Just need a very fast buton to get original message in English will be user full.
Example for the case upper, i really dont know what append, and the translate give me nothing.

**Comment by dbaeumer** [comment]
These need several improvements. First to load both language packs and second UI support in the problems hover.

**Comment by djmisterjon** [comment]
for now it fine, i see we can set type in English
![image](https://user-images.githubusercontent.com/24865815/85305663-62d00b00-b47b-11ea-89bc-5a3ab5970832.png)
So it no very urgent, just a little enhancement. :)
