### ISSUE TITLE
autocompletion doesn't work and the dropdown menu item icon is wrong 

### ISSUE THREAD

**Issue by whinc** [microsoft/vscode#100543]
Issue Type: <b>Bug</b>

autocompletion doesn't work in `*.jsx` file  and the dropdown menu item icon is wrong 

![image](https://user-images.githubusercontent.com/5096493/85089828-349dc180-b216-11ea-8892-bc3d0fdcc89b.png)

![image](https://user-images.githubusercontent.com/5096493/85089849-3f585680-b216-11ea-987e-06f0de0bafad.png)

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (1.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
mermaid-markdown-syntax-highlighting|bpr|1.0.2
jison-syntax-highlight|cru|0.1.1
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.0.1
lex-flex-yacc-bison|fau|0.0.3
todo-tree|Gru|0.0.177
vscode-drawio|hed|0.7.0
rest-client|hum|0.24.1
vscode-styled-components|jpo|0.0.29
python|ms-|2020.6.88468
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
debugger-for-chrome|msj|4.12.8
vscode-jest|Ort|3.2.0
code-settings-sync|Sha|3.4.3
vscode-mindmap|Sou|0.0.5
code-spell-checker|str|1.9.0
shellcheck|tim|0.9.0
vscode-bnf|Val|0.0.1
vscodeintellicode|Vis|1.2.8
vscode-icons|vsc|10.1.1
vim|vsc|1.14.5
quokka-vscode|Wal|1.0.300

</details>

**Comment by gjsjohnmurray** [comment]
When the autocompletion list is only showing 'abc' type items it may be indicative of a problem with one of your extensions crashing the shared Extension Host (EH) process. Maybe try disabling half of your extensions at a time until you locate the problem one. Creating a workspace just for this task, then disabling extensions only for that workspace means you don't have to re-enable extensions afterwards. Just discard the temporary workspace.

**Comment by whinc** [comment]
> When the autocompletion list is only showing 'abc' type items it may be indicative of a problem with one of your extensions crashing the shared Extension Host (EH) process. Maybe try disabling half of your extensions at a time until you locate the problem one. Creating a workspace just for this task, then disabling extensions only for that workspace means you don't have to re-enable extensions afterwards. Just discard the temporary workspace.

Thanks, i will try again later.

**Comment by whinc** [comment]
> When the autocompletion list is only showing 'abc' type items it may be indicative of a problem with one of your extensions crashing the shared Extension Host (EH) process. Maybe try disabling half of your extensions at a time until you locate the problem one. Creating a workspace just for this task, then disabling extensions only for that workspace means you don't have to re-enable extensions afterwards. Just discard the temporary workspace.

After disable all extensionos, i still encounter the same problem, top level variable has no autocompletions, but it's properties has autocompletions.

![image](https://user-images.githubusercontent.com/5096493/85222801-96198800-b3f0-11ea-9b78-b4ecfc017326.png)

![image](https://user-images.githubusercontent.com/5096493/85222830-c5c89000-b3f0-11ea-8531-b021d2d472a5.png)


VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.27GB free)|
|Process Argv|-psn_0_413797|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
@whinc Can you please share a small project where IntelIiSense does not work?
