### ISSUE TITLE
SCM Decorations missing

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#100524]
OK I was able to find 100% repro steps out of sources on `master`. I can't repro on Insiders tho... 🙈 

There's a bit of setup:

```
git init foo
git init bar
echo hello > foo/file.json
```

1. Then, open both folders in a single workspace window
2. Go to the SCM viewlet, `file.json` should appear as untracked with the letter `U`
3. Click `file.json` and it will open a diff editor, now in the SCM view it appears as `1,U` due to the JSON syntax error
4. Reload

🐛 It only shows `1` instead of `U`. As soon as you hit `Refresh` on the repository, the `U` appears!

This could also very well be an issue in Git and not decorations. @jrieken Can you check whether the decorations are reaching your model at least?

**Comment by jrieken** [comment]
Does this repo consistently? Otherwise you can enable `trace` logging. Whenever I [retrieve](https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/workbench/services/decorations/browser/decorationsService.ts#L372) data it's being logged as trace-message

**Comment by jrieken** [comment]
> Go to the SCM viewlet, file.json should appear as untracked with the letter U

This is just in one window, right? The `bar` windows doesn't show anything. I have followed your steps but wasn't able to reproduce....

**Comment by joaomoreno** [comment]
OK it seems I can't get 100% repro but I'm more on 50% now. It's also irrelevant to the error decoration, as I am able to repro without that decoration.

After enabling trace logging, that message doesn't show up for those decorations. Will dig deeper.

**Comment by joaomoreno** [comment]
Oh man, it's related to the [ignore decorator](https://github.com/microsoft/vscode/blob/1b0f70606a81edbba6f260d507aaf2828cf8bc03/extensions/git/src/decorationProvider.ts#L16-L16). When I comment that one out, not only git decorations come *much faster* but also the bug does not reproduce.

**Comment by joaomoreno** [comment]
Caught it:

https://github.com/microsoft/vscode/blob/1b0f70606a81edbba6f260d507aaf2828cf8bc03/extensions/git/src/decorationProvider.ts#L47

If two `provideDecoration` calls for the same `uri` overlap, the second one's `resolve` and `reject` will overwrite the first one's, so that first one will never complete! This points to a potential issue in decorations in which if some providers do not complete, this affects other provider's decorations as well. This might also be a pretty ugly memory leak of pending `provideDecoration` calls, since we might listen on them forever and ever. @jrieken Leaving this investigation to you.

I've fixed it in https://github.com/microsoft/vscode/commit/fad4d8d254f9959bb64b9ebb9f6a0742ec4cc005 and now I can't repro no more! 💪

**Comment by jrieken** [comment]
> Caught it:

Hmmm... You saw this in source or actually for real? The refetch while pending fetch shouldn't happen and it would be pretty horrible if it does.

**Comment by jrieken** [comment]
I think what's more likely is that this is happening because the we don't honour the [cancellation token](https://github.com/microsoft/vscode/blob/fb36c0ddc3a16f9570c65d2915e7a5af1d21bb34/src/vs/vscode.proposed.d.ts#L845) that is passed to the provide call. Internally we [cancel requests](https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/workbench/services/decorations/browser/decorationsService.ts#L270) re-fetching them while they are in flight

**Comment by joaomoreno** [comment]
> You saw this in source or actually for real?

Saw it running out of sources, but I have some users reporting similar issues: https://github.com/microsoft/vscode/issues/98241, https://github.com/microsoft/vscode/issues/53260, https://github.com/microsoft/vscode/issues/93701

> I think what's more likely is that this is happening because the we don't honour the [cancellation token](https://github.com/microsoft/vscode/blob/fb36c0ddc3a16f9570c65d2915e7a5af1d21bb34/src/vs/vscode.proposed.d.ts#L845) that is passed to the provide call. Internally we [cancel requests](https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/workbench/services/decorations/browser/decorationsService.ts#L270) re-fetching them while they are in flight

Makes sense! Should we still do some work in the core in case people don't respect the token? (Remember you implemented the original ignore decoration provider 😆)

**Comment by jrieken** [comment]
>  Should we still do some work in the core in case people don't respect the token

We [do]( https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/workbench/services/decorations/browser/decorationsService.ts#L285) which makes me wonder how this reproduced... I'll need to step through this to get a repo and an understanding
