### ISSUE TITLE
Hover popups always seem to go up, even for first line of file (going offscreen)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10051]
- VSCode Version: 1.3.1
- OS Version: Windows 10

For some reason, the hover information provided by my extension always goes up and gets chopped off; even though the built-in TypeScript one does not!

TypeScript (left) has the hover popup appear below the mouse, whereas mine (right) shows it above.

![hovers](https://cloud.githubusercontent.com/assets/1078012/17343347/13b5b3b6-58f5-11e6-908a-7e804da9c492.png)

My code looks like this (I've checked but can't see anything on the related classes that might let me control this):

```
export class DartHoverProvider implements HoverProvider {
    private analyzer: Analyzer;
    constructor(analyzer: Analyzer) {
        this.analyzer = analyzer;
    }

    provideHover(document: TextDocument, position: Position, token: CancellationToken): Thenable<Hover> {
        return new Promise<Hover>((resolve, reject) => {
            this.analyzer.analysisGetHover({
                file: document.fileName,
                offset: document.offsetAt(position)
            }).then(resp => {
                if (resp.hovers.length == 0)
                    resolve(null);
                else
                    // TODO: Add Range
                    resolve(new Hover(resp.hovers.map(this.getHoverData)));
            });
        });
    }

    private getHoverData(hover: as.HoverInformation): string {
        return (
            (hover.dartdoc != null ? hover.dartdoc + "\r\n" : "")
            + hover.elementDescription
        ).trim();
    }
}
```

**Comment by alexandrudima** [comment]
@DanTup The UI code that renders the hovers doesn't care about where the hover comes from, but cares about the height of the hover. Is it possible to share here the values you provide to a hover? (I'm thinking it is a very large text blob?)

**Comment by alexandrudima** [comment]
@joaomoreno I think we've added scrolling in the hover since this issue was created, right ?

**Comment by joaomoreno** [comment]
@alexandrudima Talk about digging. 👴
