### ISSUE TITLE
Using vscode.Pseudoterminal for executing commands

### ISSUE THREAD

**Issue by vsjha18** [microsoft/vscode#100535]
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0```
```
Pseudoterminal doesn't provide any mechanism to issue commands to the underlying shell like `vscode.terminal` does with `sendText`. For example.
```typescript
class CustomBuildTaskTerminal implements vscode.Pseudoterminal {
	private writeEmitter = new vscode.EventEmitter<string>();
        open() {
             // I need API's to execute commands on this Pseudoterminal
             // make some user interacitions
            // again run commands

        }
```

I do not have the liberty to use this
```typescript
const pty = new CustomBuildTaskTerminal()
const term = vscode.window.createTerminal("Some Name", pty)
```
Because in the `CustomExecution` in the `TaskProvider`, you can only provide `vscode.Pseudoterminal` instance. 

With the following code I can send text to the pseudo terminal
```
this.writeEmitter.fire("any text")
```
But I want to send to the shell instead of just displaying it on the terminal.
Hope you get my problem, else please ask for more clarification.

**Comment by Tyriar** [comment]
You can just call into your `Pseudoterminal.handleInput`. The extension is "the shell" so you can send text to it whenever you want.
