### ISSUE TITLE
Support syntax aware folding for XML

### ISSUE THREAD

**Issue by eldano** [microsoft/vscode#100513]
According to the documents (https://code.visualstudio.com/docs/editor/codebasics#_folding) code folding works based on indentation and for a set of specific languages it works based on syntax. These languages include HTML but not XML.
Could XML be added to this list?
Currently if I open an XML file and set the language mode to HTML it folds fine (syntax aware) but it would be nice to be able to do that without setting the wrong mode and without any extensions.

**Comment by aeschli** [comment]
Yes, to XML aware folding has to come from an extension. https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml is an XML extension that does that.
