### ISSUE TITLE
Fix this issue PLEASE

### ISSUE THREAD

**Issue by lisaraj2009** [microsoft/vscode#100542]
So, I was going to close VSCode to concentrate on some OTHER WORK, then your STUPID PROGRAM suddenly decided to do a FRICKING UPDATE!! 

First of all, STOP FOOLING ABOUT WITH YOUR CUSTOMERS AND LET THEM UPDATE THE PROGRAM WHEN THEY WANT TO! Suprisingly, the update ran into an error. I re-ran the executable installer and it ran into an error when installing the program. I'm right now trying to delete YOUR STUPID PROGRAM AND REINSTALL IT! I AM TRYING TO DELETE Code.exe, BUT YOUR PIECE OF CRAP KEEPS RESPAWNING! CAN YOU AT LEAST IN THE NEXT UPDATE STOP THROWING UPDATES AT USERS LIKE THEY EVER WANTED IT!? ALSO, REMOVE YOUR STUPID RESTRICTIONS FROM CODE.EXE! EVEN THE INSTALLER ISN'T WORKING!

**Comment by lisaraj2009** [comment]
Imagine if M$ even actually CARED about their customers - yeah right, EMBRACE, EXTEND AND EXTINGUISH ARE YOUR FILTHY POLICIES OUT THERE!

**Comment by lisaraj2009** [comment]
Ah yes, triggered microsoft people nicely closing this issue as they don't want to admit how useless they are...

**Comment by lisaraj2009** [comment]
Wow, like you even ever CARED about customers!

**Comment by mjbvz** [comment]
If you have an issue then please file a proper issue report. We do not put up with tantrums or insults
