### ISSUE TITLE
html inside php doesn't autoindent anymore

### ISSUE THREAD

**Issue by fgschafer** [microsoft/vscode#100578]
Issue Type: <b>Bug</b>

Since any of the last updates, the html parts of php file don't autoindent with proper linebreaks as before.  This happens in all my VS code instalations with 1.46.1 on W7, with or without any extension installed.
I mean, when I hit enter in: 
```
<div>|</div>
```
I get only a regular linebreak and not the extraline and indentation I get in a html file.  I noticed that if I open an html file and come back to the php file, the autoindentation temporarily wors again until you close and reopen de php file.  So annoying.  I hope thi can be fixed asap.  Thank you very much.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU N3450 @ 1.10GHz (4 x 1094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.84GB (0.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
ayu|tea|0.20.1

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This has been the case for awhile, tracking in https://github.com/microsoft/vscode/issues/98621
