### ISSUE TITLE
Unable to suppress error about `Non-null assertions can only be used in TypeScript files.javascript` in a Blade template file in Laravel/Vue application

### ISSUE THREAD

**Issue by agm1984** [microsoft/vscode#100613]
- VSCode Version:
``` bash
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z (1 wk ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```
- OS Version:
``` bash
MacOS Mojave
Version 10.14.6 (18G103)
```
Steps to Reproduce:

1. Put the following code into a Blade template, such as `callback.blade.php`:
``` blade
<html>
    <head>
        <meta charset="utf-8">
        <title>{{ config('app.name') }}</title>
        <script>
            window.opener.postMessage(
                {
                    user: {!! $user !!},
                },
                "{{ url('/') }}"
            );

            window.close();
        </script>
    </head>

    <body>
    </body>

</html>
```

2. attempt to suppress the error

I am unable to get rid of this error:
![image](https://user-images.githubusercontent.com/17655219/85184952-c6bdbe00-b246-11ea-8c00-96e183089d39.png)

I suspect there is a minor issue here because of the language mixing in this Blade template. I'm not using TypeScript, and I am using PHP to inject the object into the JavaScript function inside what might be an HTML file. I do see it is set to HTML:
![image](https://user-images.githubusercontent.com/17655219/85185068-3fbd1580-b247-11ea-9ce6-25bee781d23c.png)

I tried all techniques to suppress the error, but I wasn't able to achieve success. Notably, this doesn't work:

``` json
"javascript.validate.enable": false,
```

I also tried things such as `// @ts-nocheck` and `<!-- @ts-nocheck -->` in the file, but that didn't work either.

I have another known error, and this feels very related to it:
![image](https://user-images.githubusercontent.com/17655219/85185170-bb1ec700-b247-11ea-9c9f-24686c87d4b7.png)

It feels to me like similar dynamics are coming into play for both issues.

Also thanks for your time, and your contributions to mankind (plus gender inclusion). VS Code consistently sparks joy to use.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by aeschli** [comment]
Yes, the HTML language server is intended for pure HTML, not for templated HTML.

Ideally there would be an extension that has knowledge of the tempting syntax and can offer proper support for all language features. Did you check on the marketplace for anything better?

To disable javascript / css validations in HTML, use settings
`html.validate.scripts` and `html.validate.styles`

**Comment by agm1984** [comment]
Thanks for your time and advice. 

Addition of this in `settings.json` suppressed the warning:

``` json
"html.validate.scripts": false,
```
