### ISSUE TITLE
VSCode, Python, Docker-debug does not work

### ISSUE THREAD

**Issue by EduardBlinov** [microsoft/vscode#100634]
- VSCode Version: 1.46.1 (latest)
- OS Version: Win 10 Pro, ver.1909, os build 18363.900 (latest)
- Python 3.7.3 64-bit

 **Docker-debug does not work (but it worked before).**

Steps to Reproduce:

1.Add 2 extensions: Docker and Python
2.Create docker environment:
command palette: Docker: Add Docker Files to Workspace
Select App Platform: Python: General
Include optional Docker Compose files: No
Enter the relative path: app.py
3.Create app.py in root. with print(111)
4.F5
**Result:**
Error text in terminal:
Executing task: docker-run: debug 
Unable to find the debugger in the Python extension.
The terminal process failed to launch (exit code: 1)
and see attach.
![error](https://user-images.githubusercontent.com/29820109/85197148-f34bf700-b293-11ea-9eaa-a03d04644988.jpg)
But a week ago it worked. I tested the latest vscode insiders build - the same issue.
If I build image and run it by commands in terminal - it works fine.
Please help.

**Comment by Mikecom32** [comment]
Also having this problem debugging through an SSH connection to a linux host.

**Local Host**
Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Remote host** 
Ubuntu 20.04 LTS
Python 3.8.2 64-bit
Docker 19.03.11, build 42e35e61f3

**Extensions**
Remote Development 0.20.0
Docker 1.3.1
Python 2020.6.89148
