### ISSUE TITLE
Git does not work when VS code is open

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode#100653]
Issue Type: <b>Bug</b>

Recent updates to VS Code have caused git to fail most of the time.  
Most of the time I cannot:
1.  add files to staging with `git add filename`, 
1. commit staged files with `git commit`,   
1.  push to remote with `git push` .  

It does not matter whether I execute these commands from the integrated terminal (gitbash, PowerShell, or cmd) , a stand alone terminal (gitbash, PowerShell, or cmd), or from the git tools integrated in VS Code.  All attempts results in the same errors.

The most common error occurs when running `git add` or `git commit`, which is: 
```
fatal: fsync error on 'loose object file': Bad file descriptor
```
When running `git gc` I get:
```
fatal: fsync error on '.git/objects/pack/tmp_pack_sztM1a': Bad file descriptor
fatal: failed to run repack
```

There are other errors, I will post here when I get them again.  

This has happened occasionally before, but now it is nearly constant.

The only way to get git to work is to close **all** open instances of VS Code and run the git commands from a separate terminal.  This is a irritating impediment.

If there is no way around this, is there a way to completely block all VS Code git integration?

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
macros|ged|1.2.1
sftp|lix|1.12.9
python|ms-|2020.6.89148
rust|rus|0.7.8

</details>

**Comment by joaomoreno** [comment]
This is specific to a single repository, I guess? Can you reproduce in other repositories? Can you clone that repository to another folder and see if you still have the issue?

Also: https://stackoverflow.com/questions/4254389/git-corrupt-loose-object

**Comment by clayms** [comment]
Not specific to single repo.  Happens with every repo I currently use (~6 actively). 
Same problem when cloning the same repo into another folder.

The issue only arises with any project when that project is open in VS Code.  As soon as I close VS Code, I can `add`, `commit`, `gc` and `push` with no issue.

**Comment by clayms** [comment]
closed accidentally

**Comment by clayms** [comment]
Could the problem be when using Git Bash as the default integrated terminal? 
The problem *seems* to occur more often when Git Bash is open in the integrated terminal and less when PowerShell is the only shell open in the integrated terminal, but I have not fully tested.

**Comment by joaomoreno** [comment]
Is this Git for Windows?

**Comment by joaomoreno** [comment]
> There are other errors, I will post here when I get them again.

What are the other errors?

**Comment by clayms** [comment]
The only other error I have seen is when I run `git push`.  It is nearly the same as other errors above and contains some combination of  `fsync error`,  `'loose object file'`,  and `Bad file descriptor`.

**Comment by clayms** [comment]
I changed my default integrated terminal shell from git-bash to PowerShell and the issue has mostly gone away.  I am a bit reluctant to switch back to git-bash just for testing.  

Could git-bash be causing the issue?  
What hooks does git-bash put into the git repos in the folders it is opened from?  
When I open git-bash outside of VS Code, I don't have the issue, as long as my default shell in VS Code is not git-bash.

**Comment by joaomoreno** [comment]
@Tyriar any thoughts?

**Comment by Tyriar** [comment]
https://stackoverflow.com/q/47929881/1156119 looks similar which says it could be low disk space, permissions or not using mapped drives? The only thing I can think of is this is a limitation of winpty and you need to update to the new terminal backend which is maintained by Microsoft so weird permissions-related things like this don't happen, you need to be on Windows 1903+ to use the new system.

**Comment by clayms** [comment]
Windows system info:

```
PS > (Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion") | Select ProductName, ReleaseId, CurrentBuild, CurrentVersion

ProductName           ReleaseId CurrentBuild CurrentVersion
-----------           --------- ------------ --------------
Windows 10 Enterprise 1909      18363        6.3
```

**Comment by Tyriar** [comment]
@clayms does this also happen in Windows Terminal? Also can you share your settings.json file?

**Comment by clayms** [comment]
I have not attempted to use the new Windows Terminal with the Git Bash profile at the same time Git Bash is set as the default shell in the VS Code integrated terminal.

Below is my Windows Terminal Git Bash profile.  

```
{
                "name" : "Git Bash",
                "guid": "{5888f0dc-45e9-4a51-ba72-00a2d5d04072}",
                "commandline" : "\"%PROGRAMFILES%\\git\\usr\\bin\\bash.exe\" -i -l",
                "closeOnExit" : true,
                "colorScheme" : "Campbell",
                "cursorColor" : "#FFFFFF",
                "cursorShape" : "bar",
                "fontFace" : "Consolas",
                "fontSize" : 10,
                "historySize" : 9001,
                "icon" : "%PROGRAMFILES%\\git\\mingw64\\share\\git\\git-for-windows.ico",
                "padding" : "0, 0, 0, 0",
                "snapOnInput" : true,
                "startingDirectory" : null,
                "useAcrylic" : true,
                "acrylicOpacity" : 0.8
            },
```

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
