### ISSUE TITLE
Jupyter Notebook fails to save [Notebook Editor]

### ISSUE THREAD

**Issue by zatkins2** [microsoft/vscode#100670]
Issue Type: <b>Bug</b>

Unfortunately this Issue appears in ~50% of sessions, but of course this is frequent enough to prevent use of any Notebook development in VS Code (with the Notebook Editor) on my machine.

1. Open a pre-existing Jupyter Notebook (any .ipynb file; as indicated open within WSL. I am running Ubuntu-18.04).
2. Make arbitrary changes to your file.  After a short period (immediately to a few minutes), the Notebook Editor will not be able to save -- both ctrl + S and the save button do not clear the "dirty editor" asterisk next to filename.
3. Does not depend on whether cells have been executed since changes made in file (unlike in other issues which noted that executing a cell recovers ability to save the file).

Interestingly, the problem does seem to correlate with the Notebook Editor mistakenly opening multiple windows of the same file in step 1, if opening directly from the VS Code explorer. In ~50% of VS Code sessions, I observe this behavior (multiple Notebook Editor windows even though I opened the file "once"). If this happens, my inability to save occurs ~100% of the time...

In this case:
1. Open a pre-existing Jupyter Notebook (any .ipynb file; as indicated open within WSL. I am running Ubuntu-18.04).
2. Close any redundant Editor windows opened by VS Code.
3. Make arbitrary changes to your file.  **_Immediately_**, the Notebook Editor will not be able to save -- both ctrl + S and the save button do not clear the "dirty editor" asterisk next to filename.
4. Does not depend on whether cells have been executed since changes made in file (unlike in other issues which noted that executing a cell recovers ability to save the file).

Example:
* Mulitple Editors opened from one file in Explorer
![image](https://user-images.githubusercontent.com/46325652/85213338-1e355a00-b32b-11ea-9955-48847f7c5191.png)
* Changes made to file, "dirty editor" asterisk does not respond to save attempts. Changes **_not_** written to disk
![image](https://user-images.githubusercontent.com/46325652/85213380-94d25780-b32b-11ea-83f5-f734ab1c2dac.png)

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (8.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|Memory (System)|15.79GB (8.22GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
gitlens|eam|10.2.2
python|ms-|2020.6.89148

</details>

**Comment by rebornix** [comment]
Please file issue agains the Python extension, which currently provides the notebook feature.
