### ISSUE TITLE
The scrolls are not visible enought in default

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#100602]
Can be scroll highlighted when focused are for click/move? Like on image?
I tied many themes but in any of this I have problem to quick find scroll and wate time for this with some confusion.
1 Left is as now, 2 the right proposition, 3 sugested, 4 experiment. 
The highlith can be related with statusbar color - eg. in black is blue, so hihgl. is blue.
![VSC_scroll](https://user-images.githubusercontent.com/25403861/85168277-6b052c00-b26a-11ea-89d8-135e72eb18b0.png)

**Comment by ManPython** [comment]
BTW I think that the "elements" on the right sides should be related with the level of the outline colours and positions, eg. clases, functions, some vars. This can build some view of file based on colours that is more cognitive that this what is now on my img.

**Comment by ManPython** [comment]
> 2. Need scroll btn use for tabs card to switch betwen left/right.

Need reapir this in current VSC, cos when exist many tabs then sroll is actvie but blocking click tab. Soo.. the scroll should be uper tabs not under tabs, or sroll for tabs can have option to turn off (scrolling by mouse scroll is enough - not need widget maybe).

**Comment by alexdima** [comment]
@ManPython All the colors applied to the slider are customizable, e.g.:

```
"workbench.colorCustomizations": {
	"scrollbarSlider.background": "#ff0000"
},
```

**Comment by ManPython** [comment]
@alexdima thats is some solution but..
1. Scroll covering tabs
![VSC_scroll_colored](https://user-images.githubusercontent.com/25403861/85959243-5546e380-b99b-11ea-9a77-27969234c1ea.png)
- the scroll vertical should be upper tabs or turned off as option

2. On tabs is highlighted for blue when mouse is focused, on vertical is blue when moving, and focued gray. Thats disonanse little.
![VSC_scroll_colored_2](https://user-images.githubusercontent.com/25403861/85959300-dbfbc080-b99b-11ea-87a7-ff5f84ce827f.png)

3. There is next disonanse with high upper level of scroll as I discover due that breadcrumbs hide layer when is IDE doc in down
![VSC_scroll_colored_3](https://user-images.githubusercontent.com/25403861/85959329-106f7c80-b99c-11ea-971b-c55dd4f279d8.png)
- when line is # 4 not # 1 we see "layer" under breadcrumbs (IMHO should be constant visible)

**Comment by alexdima** [comment]
@ManPython 

There are multiple colors for the slider. Please use ctrl+space to discover them in `settings.json` or read about them in our documentation page at https://code.visualstudio.com/api/references/theme-color#scrollbar-control

e.g.
```
	"workbench.colorCustomizations": {
		"scrollbarSlider.background": "#ff000088",
		"scrollbarSlider.activeBackground": "#00ff0088",
		"scrollbarSlider.hoverBackground": "#0000ff88",
	},
```

Please edit these colors as you desire. If you don't like the blue, then please choose another color. If you find it is too transparent, then please increase its alpha channel.
