### ISSUE TITLE
???

### ISSUE THREAD

**Issue by chany-hub** [microsoft/vscode#100623]
Issue Type: <b>Bug</b>

What's the matter?

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.23GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.3
react-native-react-redux|EQu|2.0.4
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.1.0
code-runner|for|0.10.0
graphql-for-vscode|kum|1.15.3
vscode-react-native|msj|0.16.0
material-icon-theme|PKi|4.2.0
open-in-browser|tec|2.0.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo or else please close this issue.
