### ISSUE TITLE
Semantic code parsing is much slower than before May 2020

### ISSUE THREAD

**Issue by cynicmusic** [microsoft/vscode#100698]
Issue Type: <b>Bug</b>

The latest VS update makes HTML files including javascript especially long single liners hang the application. There are frequent hangs for for 250ms-1000ms range (looks like UI thread locks). The hangs happen when you are editing near or on that line of code. It works fine for "well formatted code" but please consider monolithic HTML files containing several minified libraries on a single line. We're not talking about huge libraries here, a few 1KB lines is enough to reproduce this issue, which I have seen daily on Mac/PC. thanks guys since May update or so.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

**Comment by aeschli** [comment]
Wondering if there has been any updates to the HTML or JavaScript grammar lately...

**Comment by alexr00** [comment]
Last HTML grammar change was 6 months ago 18bab626b9d54e836412b7a6aae620645da0422c
Last Javascript grammar update was also in 1.45.0 https://github.com/microsoft/vscode/commit/a1d80c4a70a507fba7c939a4e57642dc6b4d5f5e

**Comment by alexr00** [comment]
@cynicmusic can you provide a copy/pastable example we can reproduce the issue with.
