### ISSUE TITLE
"Problems" not removed for closed file when file is closed while file is being linted

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#100646]
- VSCode Version: 
- OS Version: Win 10, 2004

Steps to Reproduce:

I think I observed that "Problems" are removed/hidden when a file is closed. However, when I close a file while linting is running (in this case, lintr for the R language, which can take a long time), the problems appear after the file is closed and are _not_ removed.

Does this issue occur when all extensions are disabled?: No (needs R extension, but I suspect the problem is more general)

**Comment by sandy081** [comment]
Do you have a filter in Problems to show problems for active file only?

<img width="782" alt="image" src="https://user-images.githubusercontent.com/10746682/85306655-143c6400-b4af-11ea-89ea-bb31371f787b.png">

**Comment by bersbersbers** [comment]
@sandy081 no. But I have still noticed that when you close a file, this file's problems are removed (do let me know if this is not intended) such that problems are shown only for open files - and that closing a file during linting seems to prevent that.

**Comment by sandy081** [comment]
It seems it is nothing to do with above feature. Hence, I would suggest to file an issue first with the linter.

**Comment by bersbersbers** [comment]
I can trigger the same problem with the [R extension](https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r) (using `lintr`, original report) and now also with the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) (using `pylint`) using the same steps.

Do you still think this is an extension/linter issue? If so, can you maybe move this issue to https://github.com/microsoft/vscode-python? Otherwise, I'll open my there myself.

**Comment by sandy081** [comment]
I would think so because the linter extension should be listening to file close events and remove the diagnostics.

**Comment by bersbersbers** [comment]
Alright, thanks. I had expected this part ("listening to file close events and remove the diagnostics") to be code that is assumed to be identical across all extensions, and thus part of "core" VS Code. Will report with the respective extensions then.

**Comment by kimadeline** [comment]
Hi @sandy081, 

This doesn't seem to be an extension-specific problem, there's a similar behaviour in TypeScript:

![problems_002](https://user-images.githubusercontent.com/51720070/86398363-56596880-bc5a-11ea-8d2e-c27d38f1f91b.gif)

It is flaky though, I couldn't get it to reproduce 100% of the time.

**Comment by sandy081** [comment]
VS Code core does not add/remove any diagnostics by itself except applying some UI filters. If no filters are applied it shows all diagnostics extensions created. Hence I would recommend to reach out to extensions if you are seeing diagnostics which you are not supposed to.

**Comment by kimadeline** [comment]
We certainly should fix it in the Python extension, but I could reproduce it using the built-in TypeScript support, which isn't caused by an extension. The behaviour (diagnostics not being hidden) doesn't happen all the time though, why are the diagnostics sometimes hidden and sometimes not when closing the file?

**Comment by sandy081** [comment]
In built typescript is also an extension except that it is bundled with VS Code. I would ask @mjbvz about this behaviour.

**Comment by mjbvz** [comment]
Currently TypeScript only shows error for opened files (unless you use a watch task)

**Comment by kimadeline** [comment]
I don't use a watch task, does it mean that the behaviour in the gif above is unexpected? Should I open a separate issue for it?

**Comment by mjbvz** [comment]
Sure
