### ISSUE TITLE
The shorcut is not working 

### ISSUE THREAD

**Issue by RIshonRJ** [microsoft/vscode#100687]
Issue Type: <b>Bug</b>

when i type an exclamation mark and press tab, it doesn't type the basic html what i need.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.76GB (0.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.20.0
code-runner|for|0.10.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
python|ms-|2020.6.89148
LiveServer|rit|5.6.1
pygame-snippets|tus|0.0.1

</details>

**Comment by eamodio** [comment]
Did this change, is this new? What are you expecting to happen?

**Comment by sharmandhruvpl** [comment]
I had the same issue, this is when you set your emmet abbreviations to Django. You probably installed Django recently and that makes the difference.
Solution
1. Press Ctrl + Shift + P to open the command palette.
2. Type 'Change Language Mode' in the searcher.
3. Select 'Change Language Mode'.
4. Type 'HTML' in the searcher.
5. And select 'HTML' (it was probably set to 'django-html)

**Comment by eamodio** [comment]
@RIshonRJ does the above resolve the issue for you?

**Comment by RIshonRJ** [comment]
nope!
that was when i was writing my base for my javascript code which is html
language which i don't know so what i was expecting is typing  a
exclamation mark and press tab and type out the things for me. but to my
surprise i didn't. so i reported it.

**Comment by RIshonRJ** [comment]
added to that i didnt still work

**Comment by RIshonRJ** [comment]
Yes please close this issue.it is fixed now.
