### ISSUE TITLE
Modifier keys for preferences sync

### ISSUE THREAD

**Issue by Keno** [microsoft/vscode#100615]
I frequently use either a Macbook or a Linux desktop and would like to sync my VS Code settings between them. This becomes problematic because the modifier keys differ between linux and OS X.
At the moment it looks like the settings I configured to use the command key on OS X end up getting mapped to Ctrl on Linux. However, I would prefer to map command to super, which would match what happens when I switch my external keyboard between the two machines. Is there, or could there be a setting to specify how keys get mapped between the different operating systems?

**Comment by sandy081** [comment]
Are you asking to configure this setting with different values per OS?

**Comment by Keno** [comment]
I use the same keyboard when I switch between devices, so I want it to be the same physical key ideally, but of course the OSes themselves treat the modifier keys differently, so I'm not entirely sure how to represent that in the keymap.

**Comment by sandy081** [comment]
@alexdima Any suggestions?

**Comment by alexdima** [comment]
@Keno Two suggestions:
1. You can write os specific keybindings using os specific context keys. The following are available: `isWindows`, `isMac`, `isLinux`. You can add `&& isMac` to the `when` clause.
2. You can try using `meta`. I think this maps to the super key on Linux and to the cmd key on macOS, but I haven't tested this.

**Comment by sandy081** [comment]
Please reopen if above suggestions do not work.
