### ISSUE TITLE
feature request: detect node inspect in the terminal

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/vscode#100674]
When the terminal appears text like:

```
$ node --inspect-brk ../TypeScript/built/local/tsc.js -p ./
Debugger listening on ws://127.0.0.1:9229/535c1ac2-1499-44a8-8432-117dc73ebb46
For help, see: https://nodejs.org/en/docs/inspector
```

Allow click the `ws://...` link to connect to the debugger

**Comment by weinand** [comment]
This case is covered by our new JavaScript debugger.

**Comment by Jack-Works** [comment]
Does it shipped yet?

**Comment by weinand** [comment]
yes, please see: https://code.visualstudio.com/updates/v1_46#_new-javascript-debugger

**Comment by Jack-Works** [comment]
Cool! Thanks
