### ISSUE TITLE
VS-code could not open default browser

### ISSUE THREAD

**Issue by 64bitBunny** [microsoft/vscode#100697]
Issue Type: <b>Bug</b>

First 'live server extension' could not open the browser,  it was working fine before, I thought it was extension problem, but then 'Open In Browser extension ' also started giving error 'Open browser failed!! Please check if you have installed the browser correctly!', I tried reinstalling extension, browser, vscode but nothing worked.
I think the problem might have started after installing node.js, I've found similar issues on the net saying the same.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (3.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
javascript-ejs-support|Dig|1.3.1
jquerysnippets|don|0.0.1
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.1.0
auto-rename-tag|for|0.1.3
code-runner|for|0.10.0
csharp|ms-|1.22.1
python|ms-|2020.6.89148
cpptools|ms-|0.28.3
color-highlight|nau|2.3.0
java|red|0.63.0
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
vscode-icons|vsc|10.1.1
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by dbaeumer** [comment]
Anything in the log files?

**Comment by dbaeumer** [comment]
Closing issue since needed information was not provided. Please ping when available.
