### ISSUE TITLE
Flip EditorTabs(groups) on split view: LEFT<->RIGHT  with Hotkey

### ISSUE THREAD

**Issue by patarok** [microsoft/vscode#100608]
If I have two editor tabs open and split to left and right(so two editor groups),
i think it would be nice to be able to just flips/swap sides via some HotKey...
Up til now, there only seems to be the possibility to flip layout from "left/right" to "top/bottom",
via 'Shift+Alt+0'....
One could think that 'Shift+Alt+X' is not reserved and should be used to flip editor-group sides.

**Comment by ArturoDent** [comment]
There are commands to move editor groups, like `Move Editor Group Left` (Ctrl+K leftArrow) and more so if you have focus in the right split it would flip to the left.

Does that do what you want?

**Comment by patarok** [comment]
> 
> 
> There are commands to move editor groups, like `Move Editor Group Left` (Ctrl+K leftArrow) and more so if you have focus in the right split it would flip to the left.
> 
> Does that do what you want?

Actually, yes! But somehow, no.

Though I find a general Flip of Sides no matter what, without touching twice much nicer
and still think that Shift-Alt-X would not feel as impractical as:
-) hitting the combo first 
-) then the arrow
-) then also maybe click some tab again (because for some reason and this combo to work something may not be in focus as it should...) 
* I am pretty sure it works most of the time, 
but itdoesnt work for instance:
 --> when you have some image file open and in focus on one side...
what will force you to:
-)touch your mouse again 
-)click a text-file tab,
-)click into that tabs text area, and than 
-)again hit the (split up) combo


... ... I gotta admit, it will do the job for me - for now
 and I really have to send a big merci to you. :)
So again, thank you for the info I really appreciate and will use it, 
but still:

I would prefer Shift-Alt-X flipping the splits NO MATTER WHAT.
(I hope caps arent considered screamin on github like on some forums, otherwise I'll have to say sorry.)

So pls guysngals, take a heart and vote for a very practical shortcut. thx.
