### ISSUE TITLE
Support TS import module ending option .ts

### ISSUE THREAD

**Issue by deepkolos** [microsoft/vscode#100679]
deno's import require full path, so hope vscode support add an option for auto import add .ts ending

![图片](https://user-images.githubusercontent.com/12824616/85218618-78d3c200-b3ce-11ea-802f-d845641f1193.png)

![图片](https://user-images.githubusercontent.com/12824616/85218694-33fc5b00-b3cf-11ea-9d33-3e9adae29b82.png)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
