### ISSUE TITLE
Documentation of a CompletionItem does not resize dynamically

### ISSUE THREAD

**Issue by Zezombye** [microsoft/vscode#100676]
- VSCode Version: 1.46.1 (also tested on Insiders)
- OS Version: 10.0.14393

In my language, I wish to display previews of the built-in icons to users. However, as the images are fetched from the web (and I could not find any way of storing images locally), there is a very slight delay which makes the size of the preview not take into account the size of the image.

To do that, I put a `MarkdownString` in my `CompletionItem`:

```js
var compItem = new vscode.CompletionItem();
compItem.documentation = new vscode.MarkdownString("![](https://i.imgur.com/hych4AE.jpg)");
```
The first time I fetch the image, the preview is this size:

![](https://i.imgur.com/QLpe6dF.png)

I had to insert newlines and spaces as a workaround to make the image visible. If I only display the image, the preview's height would be the length of a single line.

If I go to the next item then go back, the image is already fetched, making the preview the right size:

![](https://i.imgur.com/8ldlogX.png)

The preview should resize dynamically when it has finished fetching images, instead of staying the same original size.

Steps to Reproduce:

1. Install the "overpy" extension
2. Create a new file, switch the language to "overpy"
3. Type `Icon.`, you will have a list of icons
4. Notice how the size of the preview changes depending of whether the image is cached

Does this issue occur when all extensions are disabled?: N/A

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest+label%3Aux
