### ISSUE TITLE
Custom editor for TextDocumentContentProvider content

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#100612]
I'm trying to integrate the awesome new custom editor (or rather viewer) for profile results that ships with the new JS debugger with the Julia extension.

Here is how I generally imagine that: we have a Julia REPL process where users can run some code in the profiler. We then provide a function that sends the profile results to the extension itself, and the extension displays the profile results using the fancy new profile results viewer. I _don't_ want to write a `.cpuprofile` file, though. So what I'm trying right now is to add a custom `TextDocumentContentProvider` provider to our extension that exposes the profiler results as a virtual document. That part works well, but I can't get the custom editor that displays `.cpuprofile` files to also display the virtual documents I'm providing.

The uri I'm creating for a profile result is `const uri = vscode.Uri.parse('juliavsodeprofilerresults:' + new_uuid.toString() + '.cpuprofile')`. I would have thought that the `.cpuprofile` would then automatically trigger the custom editor `jsProfileVisualizer.cpuprofile.table` that is defined in [here](https://github.com/microsoft/vscode-js-profile-visualizer/blob/master/packages/vscode-js-profile-table/package.json), but that doesn't seem to be the case.

Is this scenario generally not supported? Or is this just a bug and it should in theory work? It would make for a _very_ nice and smooth integration for the Julia extension!

CC @connor4312

**Comment by connor4312** [comment]
Related: https://github.com/microsoft/vscode/issues/93441 I wanted to do the same thing for js-debug and ran into the same issue 😛

**Comment by mjbvz** [comment]
@davidanthoff Can you share the  extension code for what you've tried so far?

**Comment by davidanthoff** [comment]
@mjbvz, sure, the PR is https://github.com/julia-vscode/julia-vscode/pull/1378. Just ignore the Julia side of things :)

**Comment by mjbvz** [comment]
I'm going to close this as by-design. Our `fs` apis do not work with virtual text documents created by `TextDocumentContentProvider`, which really limits what you can do.

The `TextDocumentContentProvider` api was designed for showing text content to the user in an editor. If you want to show virtual documents using custom editors, try using a custom file system provider instead. These can be used with custom editors
