### ISSUE TITLE
文本中会出现特殊字符

### ISSUE THREAD

**Issue by zhangjindong** [microsoft/vscode#100690]
Issue Type: <b>Bug</b>

拷贝的字符串总是有未知的特殊字符，
比如：/fina/basecontract/business/delete
实际粘贴为：/fina/basecontract%E2%80%8B/business%E2%80%8B/delete

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (4.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|12.40GB (5.63GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|12.40GB (5.63GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|12.40GB (5.63GB free)|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.2
vscode-markdownlint|Dav|0.36.0
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
tslint|eg2|1.0.44
prettier-vscode|esb|5.1.0
todo-tree|Gru|0.0.177
comment-translate|int|1.4.2
docthis|joe|0.7.1
px-to-vw|lee|1.0.2
vscode-todo-parser|min|1.9.1
vscode-docker|ms-|1.3.1
vscode-language-pack-zh-hans|MS-|1.46.3
vscode-typescript-tslint-plugin|ms-|1.2.3
codelf|unb|11.7.0
ionic4-snippets-vscode|4tr|1.4.0
flutter-snippets|ale|2.0.0
color-info|bie|0.5.1
bracket-pair-colorizer-2|Coe|0.1.4
FreeMarker|dco|0.0.9
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
vscode-ionic-snippets|fiv|2.2.1
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
AngularMaterial|har|7.0.1
smarty|imp|0.3.0
vue|jcb|0.1.5
Angular2|joh|9.1.2
Angular-BeastCode|Mik|8.1.2
vscode-language-pack-zh-hans|MS-|1.46.3
remote-wsl|ms-|0.44.4
debugger-for-chrome|msj|4.12.8
nestjs|rub|1.5.0
hosts|tom|1.1.1
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.8.1

(2 theme extensions excluded)

</details>

**Comment by alexyu0610** [comment]
Translation:

Issue Type: Bug

String copied includes unknown special characters:
For example：/fina/basecontract/business/delete
Pasted results：/fina/basecontract%E2%80%8B/business%E2%80%8B/delete

VS Code version: Code 1.46.1 (cd9ea64, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.19.84-microsoft-standard

**Comment by dbaeumer** [comment]
Assuming this is copy Path in the explorer.
