### ISSUE TITLE
Jupyter cell inactive after switching to it via keyboard shortcuts when using split view.

### ISSUE THREAD

**Issue by Databoy555** [microsoft/vscode#100607]
- VSCode Version: 1.46.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Create some .py files and an ipynb (jupyter notebook) file. 
2. Split them so you have one file on the left hand pane and a couple of .py files on the right hand side along with the jupyter notebook (ipynb file) on the right hand side.
3) Now make the file on the left hand side active i.e. type some code in to it
4) Navigate to the right hand pane via keyboard shortcut i.e. ctrl-2
5) Toggle between the files on the right hand pane via shift+tab until the jupyter notebook is the active file
6) Now you the ipynb file should be active, with a cell highlighted in blue. Try and navigate up or down with keyboard only i.e without using a mouse. 

I frequently cannot perform step 6 i.e. the ipynb file appears active with a blue highlight around the active cell but I cannot navigate around until I use the mouse to click on the cell then it seems to work from there onward.

Does this issue occur when all extensions are disabled?: No

**Comment by rebornix** [comment]
Please file issue against the Python extension which currently provides the jupyter notebook feature.
