### ISSUE TITLE
Manage title bar text length

### ISSUE THREAD

**Issue by cr3ux53c** [microsoft/vscode#100642]
If ${remoteName} is too long, the title bar text is collapsed to 3 dots.
I can't read the container name via the title bar text.
I want the option to adjust the threshold for the title bar text collapse.

![image](https://user-images.githubusercontent.com/28856527/85201600-b4717c00-b33b-11ea-8e28-e2c19c0b8bdf.png)

**Comment by sbatten** [comment]
@chrmarti  is it that the remote name formatter is controlled by the extension?

**Comment by chrmarti** [comment]
Yes, I think there should be a feature request for the remote indicator to automatically shorten overlong labels and set the title attribute for the tooltip with the full text. @aeschli Not sure if we have that.

**Comment by aeschli** [comment]
>there should be a feature request for the remote indicator to automatically shorten overlong labels and set the title attribute for the tooltip with the full text

@chrmarti  That's already there.
![image](https://user-images.githubusercontent.com/6461412/85864096-5bcf3280-b7c4-11ea-85b2-dfffd8a4c68a.png)

I think the request is for the title bar
