### ISSUE TITLE
 The sharpness of the interface is lost.

### ISSUE THREAD

**Issue by Goldfor** [microsoft/vscode#100661]
When I use VS Code, after some time (less than 30 minutes) the sharpness of the interface is lost. After a reboot, sharpness grows for less than 30 minutes.
Windows 10 2004
Latest VS Code
![image](https://user-images.githubusercontent.com/44811908/85210419-572ff780-b348-11ea-8e49-96b18f5f6ba4.png)

**Comment by gjsjohnmurray** [comment]
Please try running with [GPU disabled](https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration).

**Comment by deepak1556** [comment]
@Goldfor have you tried running with hw acceleration disabled per https://github.com/microsoft/vscode/issues/100661#issuecomment-647073976 ? If so, can you check the issue still happens with latest insiders https://code.visualstudio.com/insiders
