### ISSUE TITLE
The VS Code freezes completely

### ISSUE THREAD

**Issue by rikdev** [microsoft/vscode#100656]
Issue Type: <b>Bug</b>

The VS Code periodically freezes completely at random times. When it happens the last line in the log always is 'Server response: {"status":"Success","validDiagnostic'. And one of the Code processes has defunct mark:
```
ps -ejH | grep code
   6911    6910    6910 ?        00:00:05   code
   6913    6910    6910 ?        00:00:00     code
   6934    6910    6910 ?        00:00:00     code
   6953    6910    6910 ?        00:00:00     code
   7296    7296    7296 ?        00:00:07   code
   7298    7296    7296 ?        00:00:00     code
   7318    7296    7296 ?        00:00:00     code
   7325    7296    7296 ?        00:00:00     code
   7344    7296    7296 ?        00:00:04     code <defunct>
   7390    7296    7296 ?        00:00:00     code
   7361    7296    7296 ?        00:00:01   code
```

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 5.7.3-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz (2 x 3007)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|3.84GB (2.08GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details>Extensions: none

**Comment by deepak1556** [comment]
Can you launch code with `--crash-reporter-directory <some-path>`, check for dumps in that directory when the freeze happens and attach them here. Thanks!
