### ISSUE TITLE
[debt] improve the internals of the suggestion contribution

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1006]
Over the years we have accumulated debt in the internals of the suggest feature. Let's collect what we have already cleaned up and what left to do. 

- [x] move `overwiteBefore` and `overwriteAfter` from `ISuggestResult` to `ISuggestion` - @aeschli 
- [x] remove `Suggestion.highlights` and move it correctly in  to the view model
- [x] improv perf when filtering down a list of suggestion by using the tree properly - @joaomoreno

**Comment by jrieken** [comment]
@aeschli I'd be nice if you can update the html and JSON intellisense to use the textEdit

**Comment by joaomoreno** [comment]
:+1:

**Comment by jrieken** [comment]
@joaomoreno i have fixed the problem of disappearing highlights when focusing a suggestion

**Comment by joaomoreno** [comment]
@aeschli Only `overwriteBefore` and `overwriteAfter` left...!

**Comment by aeschli** [comment]
I'll work on it ASAP

**Comment by jrieken** [comment]
:dancer:

**Comment by aeschli** [comment]
I moved overwiteBefore and overwriteAfter from ISuggestResult to ISuggestion.
Removed the textEdit on ISuggestion again.
As a last step we can look into removing currentWord and replace it with overwiteBefore
