### ISSUE TITLE
Maintain horizontal position on vertical movement

### ISSUE THREAD

**Issue by mjkalba** [microsoft/vscode#100666]
Issue Type: <b>Feature Request</b>

I am in the process of moving to Visual Studio Code from TextPad, and while I have found that Code supports most of the TextPad capabilities, there is one small additional feature I would like to see.

In TextPad, when you move between lines, the cursor maintains the vertical position that it had when it moved to the previous line, if possible.

Thus if the cursor is ac character position 10  when you moved to the current line, if you move up or down, it will remain at position 10 regardless of where it moved to while you were editing the current line. This is very helpful in many cirumstances, particularly as it treats end and beginning of line as special cases,for instance allowing you to mve through a file with the cursor going automatically to the end of each line.

If there is already an option to support this behaviour, I have not yet managed to find it. If not, I would commend it for inclusion as an option in a future release.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/96809#issuecomment-638852638 seems slightly related, detailing how to get a way of making the cursor stick with the end of the line. But not a duplicate.

**Comment by gjsjohnmurray** [comment]
Thread [here](https://forum.sublimetext.com/t/smart-horizontal-cursor-positioning/2050/29) about wanting this feature in another editor pointed to an extension for that editor which implemented the feature. Maybe a VS Code extension would be feasible.

**Comment by alexdima** [comment]
@mjkalba Would binding the following keybindings for `end` and `shift+end` work for you?

```
    { "key": "end",       "command": "cursorEnd",       "when": "textInputFocus", "args": {"sticky":true} },
    { "key": "shift+end", "command": "cursorEndSelect", "when": "textInputFocus", "args": {"sticky":true} },
```

**Comment by mjkalba** [comment]
I’m a Code newbie, so I would have to try it to know, but I doubt it meets the full requirement, which is for the cursor position to be sticky at any position in a line, with end of line being a special case irrespective of line length.

It needs to be able to provide the following functionality.

You position the cursor at character 15 on a line. You then type 5 characters so that the cursor is now at character 20. You move down (or up) to the next line. The cursor automatically positions to character 15.

The special case for end of line is that if you explicitly position the cursor to the end of a line, moving up or down will position the cursor at the end of the line moved to, regardless of its length.

**Comment by alexdima** [comment]
> You position the cursor at character 15 on a line. You then type 5 characters so that the cursor is now at character 20. You move down (or up) to the next line. The cursor automatically positions to character 15.

@mjkalba  This is honestly the first time I hear of this request for a code editor. Let's track this as a feature request.

**Comment by mjkalba** [comment]
It is a standard feature of Textpad, which is a fine editor, but only works on Windows, hence my interest in moving to Code.
