### ISSUE TITLE
the  extenstion don`t work on visual

### ISSUE THREAD

**Issue by shams42** [microsoft/vscode#100665]
Issue Type: <b>Bug</b>

the  extenstion don`t work on visual , i can`t install any thing 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
env-vscode|Ber|0.1.1
javascript-ejs-support|Dig|1.3.1
node-module-intellisense|lei|1.5.0
dotenv|mik|1.0.1
laravel-blade|one|1.21.0
LiveServer|rit|5.6.1
ejs-snippets|Tao|0.1.0

</details>

**Comment by gjsjohnmurray** [comment]
Please follow the steps at https://github.com/microsoft/vscode/issues/99668#issuecomment-641807657

**Comment by joaomoreno** [comment]
Can you provide more information? What is the issue? Is there an error? Can you show me a screenshot?
