### ISSUE TITLE
synchronized threads in java 

### ISSUE THREAD

**Issue by viveksunder77** [microsoft/vscode#100601]
//this is my source code its not working the way it should i checked this outside vscode its working perfectly  
class thre extends Thread{
    public void run(){
        display();
    }
     synchronized void display(){
        for(int i=0;i<5;i++){
            System.out.println("counter --->"+i+"from thread "+Thread.currentThread().getName());
        }
    }
}
class thread{
    public static void main(String[] args) {
        Thread t0=new thre();
        Thread t1=new thre();
        Thread t2=new thre();
        t0.start();   
        t1.start();
        t2.start();
    }
}

**Comment by weinand** [comment]
VS Code knows nothing about Java. Please file issue against Java extension.
