### ISSUE TITLE
"revealProblems": "onProblem" doesn't work for CustomExecution

### ISSUE THREAD

**Issue by csk-ableton** [microsoft/vscode#100645]
- VSCode Version: 1.46.1 and 1.47.0-insider
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Download the minimal example [presentation-bug.zip](https://github.com/microsoft/vscode/files/4807943/presentation-bug.zip) - The example creates a `CustomExecution` with a `Pseudoterminal` and generates some errors in the Problems pane.
2. Run the extension
3. Create a `tasks.json`:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Custom Exec",
            "type": "customexec",
            "presentation": {
                "revealProblems": "onProblem"
            }
        },
    ]
}
```
4. Run the task

Expected: The Problems panel is shown
Actual: Nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Same root cause as https://github.com/microsoft/vscode/issues/92868
@Tyriar, the terminal `onExit` is firing before the `onLineData`.
