### ISSUE TITLE
TS completes single quote in comments

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#10068]
* open a ts file
* type a comment like `// it's`
* 🐛 notice that when typing `'` it inserts another `'` which I believe for comments it shouldn't

**Comment by aeschli** [comment]
Sorry for that, the settings for `' `and `"` got switched up when migrating the autoClosingPair moved to `langage-configuration.json`.
Regression but IMO not a biggie, I'd suggest to fix for August.

**Comment by jrieken** [comment]
It's quite annoying and fixes are still easy (being pre stable)

**Comment by ffxsam** [comment]
I have v1.4.0 and this is still an issue. Is there a way to track when certain commits will be pushed into production?

**Comment by aeschli** [comment]
You can try this in the [insider](https://code.visualstudio.com/insiders) build.

**Comment by rebornix** [comment]
Verified in latest Insider build.

**Comment by ffxsam** [comment]
Is it possible to run the Insider build alongside the stable release? (in the same way Chrome & Canary can co-exist)

**Comment by aeschli** [comment]
Yes, they are two different application with separated settings.
