### ISSUE TITLE
Extension API - How to log errors in extensions

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode#10063]
- VSCode Version: 1.3.1
- OS Version: OSx 10.11.6

Steps to Reproduce:

1. Code an extension :-)

I'm currently testing my extension locally before I want to publish it. Problem is, I can't possibly find all errors by myself. So I installed it on my friends computer as it would be installed through the marketplace.

Is there any possibility to `console.error` or anything similar from the extension? It seems there are no chances to log any errors other than the `showError` over the whole app.

I'm guessing this should be the Extensions tab in the output window?

Or is the only way to write down the errors in files?

Cheers
Chris

**Comment by jrieken** [comment]
Apart from full-blown telemetry solutions your extension could create a separate [channel](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3340) and use that to logic additional information. Other extensions like vscode-omnisharp and vscode-typescript have taken that approach.

**Comment by buehler** [comment]
Well, I'll look into it! Thanks for the fast answer!

**Comment by lextm** [comment]
In case anyone comes here later to find a relatively small sample, you can check this commit of my extension, https://github.com/vscode-restructuredtext/vscode-restructuredtext/commit/460f9f37cdf048e4c30d2705ff9b89ebd03f535b
