### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by humbertoatondo** [microsoft/vscode#100673]
Issue Type: <b>Bug</b>

Every time I open vs code a pop up message appears saying that extension host terminated unexpectedly. This means that none of my extensions work and I haven't been able to know why. I have been force to use atom as an alternative but I don't know if there is something I can do to fix it or if it is a product bug. 

I get this message in my console. 
dyld: Symbol not found: __ZN20wireless_diagnostics6google8protobuf2io16CodedInputStream24default_recursion_limit_E  Referenced from: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib  Expected in: /usr/local/mysql/lib//libprotobuf-lite.dylib in /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib

I see there is an issue on Github regarding this same problem but I didn't found a solution in that issue.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|8.00GB (0.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.1.4
gitlens|eam|10.2.2
cpptools|ms-|0.28.3
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.2.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Disable each of your extensions in turn until the problem is resolved. Then report the issue to that extension's repo.
