### ISSUE TITLE
Enter/Return key not creating a new line within .md files

### ISSUE THREAD

**Issue by martyav** [microsoft/vscode#100605]
Issue Type: **Bug**

**Steps to reproduce:**
1. Open a .md file.
1. Press Enter/Return key.
1. VSCode will pop up a little notification saying, "command 'automaticList' not found".
1. The cursor will not move and a new line will NOT be created within the document.

Pressing ctrl+Enter/Return will, however, create a new line.

Changing the file's language mode to plain text  will allow you to press just Enter/Return and create a new line.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (9.50GB free)|
|Process Argv|windows/security/threat-protection/windows-defender-antivirus/deployment-vdi-windows-defender-antivirus.md|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.36.0
docs-article-templates|doc|0.2.9
docs-authoring-pack|doc|0.1.8
docs-images|doc|0.0.9
docs-linting|doc|0.0.4
docs-markdown|doc|0.2.74
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.51
docs-yaml|doc|0.2.5
python|ms-|2020.6.89148
vscode-yaml|red|0.8.0
code-spell-checker|str|1.9.0

</details>

**Comment by usernamehw** [comment]
Most likely an extension issue. You can try running with extensions disabled `code --disable-extensions` or disable some of them one by one.

**Comment by martyav** [comment]
@usernamehw That fixed it.

**Comment by martyav** [comment]
Looks like the extension has a list of shortcuts and automaticList is now bound to the Enter key by default. 

You can edit or remove the binding by hitting CTRL+K, then CTRL+S, to open the Keyboard Shortcuts list.
