### ISSUE TITLE
程序“helloworld.exe”无法运行: 指定的可执行文件不是此操作系统平台的有效应用程序。 

### ISSUE THREAD

**Issue by Heath-Wang** [microsoft/vscode#100619]
Issue Type: <b>Bug</b>

所在位置 行:1 字符: 1
+ .\helloworld.exe
+ ~~~~~~~~~~~~~~~~。
所在位置 行:1 字符: 1
+ .\helloworld.exe
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedExcep  
   tion
    + FullyQualifiedErrorId : NativeCommandFailed

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.87GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|60%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.46.3
python|ms-|2020.6.89148
cpptools|ms-|0.28.3

</details>

**Comment by dbaeumer** [comment]
Closing issue since the needed information was not provided.
