### ISSUE TITLE
Typescript extension

### ISSUE THREAD

**Issue by TheoOliveira** [microsoft/vscode#100622]
Issue Type: <b>Bug</b>

Keeps saying every 5 times in the last 5 minutes Typescript and Javascript Language Feature died. For no reason. I am using Jest, express, nodemon and yarn with some basic tests on.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 4.9.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 1999)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|5, 7, 4|
|Memory (System)|3.85GB (0.35GB free)|
|Process Argv|desafio-conceitos-node --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
prettier-vscode|esb|5.1.0
debugger-for-chrome|msj|4.12.8
vscode-jest|Ort|3.2.0
material-icon-theme|PKi|4.2.0
vscode-xml|red|0.12.0
LiveServer|rit|5.6.1
vscode-stylelint|sty|0.84.0
sass-indented|syl|1.8.6
vscode-wakatime|Wak|4.0.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo are you able to update to the current release, 1.46.1 and retest? If the problem remains please use Command Palette to reload with all extensions disabled and see if the problem still occurs.

**Comment by TheoOliveira** [comment]
> /needsMoreInfo are you able to update to the current release, 1.46.1 and retest? If the problem remains please use Command Palette to reload with all extensions disabled and see if the problem still occurs.

Hello, thanks for the reply. Ok. What other info do you need? 2) Seems the issue is gone after I've disable all extensions and enable all after it.
