### ISSUE TITLE
Clear the Undo stack

### ISSUE THREAD

**Issue by alexbunardzic** [microsoft/vscode#100600]
I'd like to be able to clear the Undo stack on each save.

**Comment by yume-chan** [comment]
Maybe can be merge into #96601

Looks like #96601 still needs 11 upvotes and the deadline is today.

**Comment by boltex** [comment]
My extension (https://github.com/boltex/leointeg) uses file system api to implement custom 'editors' for my needs as indicated in the docunmentation here https://code.visualstudio.com/api/extension-guides/virtual-documents#file-system-api .

I need to  be able to 'block' or 'clear' undos when closing or switching from one of them to another. 

It used to be that doing vscode.WorkspaceEdit "rename" operation would 'clear'/'block' all undos for the newly named document to traverse across the point where the document was renamed, but lately the newer versions of vscode tries to open a document with the old name when pressing ctrl+Z on a newly renamed document (in a custom filesystem)... Is there a way to disable that? Or a way to clear the undo stack for a given document URL? or for a filesystem scheme only in particular? 

Thanks!
