### ISSUE TITLE
Warning when invoking explorer.newFile

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#100604]
Issue Type: <b>Bug</b>

Executing `explorer.newFile` without having a folder open produces the following warning
> Cannot read property 'isReadOnly' of undefined

![image](https://user-images.githubusercontent.com/484784/85159738-bbe93600-b212-11ea-9d06-80b8d5e490a4.png)

Steps to repro:
* Open vscode without any folder or workspace
* Bind `explorer.newFile` to a keyboard shortcut
* Invoke `explorer.newFile`
* Notice the warning

Expected result:
Either
* The OS file dialog is displayed to choose the file location, or
* No new file is created and a clearer warning is displayed

VS Code version: Code - Insiders 1.47.0-insider (8cd3fe080bee38d28ba01d0d71713d6ec22b254e, 2020-06-19T06:35:49.048Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
I suggest you add a When Expression that replicates how VS Code [hides this command from the Command Palette](https://github.com/microsoft/vscode/blob/98b5bec6bc39c04a19da4923ce219974ee6033fe/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L224) until the workspace consists of at least one folder.

![image](https://user-images.githubusercontent.com/6726799/85177842-e075fa00-b274-11ea-8f3f-98d492779ef0.png)

**Comment by isidorn** [comment]
I acknolwedge this issue.
We accept PRs that fix this.
Code pointer https://github.com/microsoft/vscode/blob/4f76209b7c60bd736d9d9afcd7ad1fce3e0215e8/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L224

Probably the command should not even be executed in the purple no folder workspace

**Comment by bpasero** [comment]
@isidorn I felt like working on this, idea: https://github.com/microsoft/vscode/pull/109905

**Comment by isidorn** [comment]
@bpasero thanks a lot, I have commented on the PR
