### ISSUE TITLE
The condition for a breakpoint failed to execute if expression is a string - Still failing

### ISSUE THREAD

**Issue by carrigiljavia** [microsoft/vscode#100672]
Setup a valid conditional breakpoint and got an exception or debugger stops every time in the breakpoint setted. The expected result is to stop just once. Condition is valid, evaluated in debug console.

```
#include <iostream>
#include <vector>
#include <string>

using namespace std;

int main()
{
    vector<string> msg {"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};
    string text ;
    for (const string& word : msg)
    {
        cout << word << " ";
        text = word; //breakpoint here expression: text=="from"
        if (word=="from")
        {
            cout << " -> ";
        }
    }
    cout << endl;
}
```

Version: 1.46.1 (system setup)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by weinand** [comment]
Please file against C++ extension
