### ISSUE TITLE
Git not loading on vscode terminal

### ISSUE THREAD

**Issue by ChamuMutezva** [microsoft/vscode#100606]
Issue Type: <b>Bug</b>

After the latest update of vs code on my windows 10, the git terminal is no longer showing as was the usual case. Just a blank screen with to signal of where to enter the commands. The option that i have for now is to open the file explorer and execute the commands in the folders

VS Code version: Code - Insiders 1.47.0-insider (8cd3fe080bee38d28ba01d0d71713d6ec22b254e, 2020-06-19T06:35:49.048Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-9120 RADEON R3, 4 COMPUTE CORES 2C+2G    (2 x 2196)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.3.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
jsrefactor|cms|2.20.6
vscode-eslint|dba|2.1.5
es7-react-js-snippets|dsz|2.8.0
vscode-npm-script|eg2|0.3.12
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
vscode-styled-components|jpo|0.0.29
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo First please use the command to reload with all extensions disabled, in case your problem is caused by one of your 14 extensions. If that doesn't help, paste screenshot(s) to help us understand what you're seeing.

**Comment by gjsjohnmurray** [comment]
Please also give this issue a better title.

**Comment by ChamuMutezva** [comment]
Issue Type: <b>Bug</b>

further details 
I have disabled all extensions and the results are still the same. Used to work fine until the recent vscode update.

![vsgit](https://user-images.githubusercontent.com/40114498/85179522-73b52c80-b281-11ea-9a5c-bbc72472e6c8.PNG)

VS Code version: Code - Insiders 1.47.0-insider (8cd3fe080bee38d28ba01d0d71713d6ec22b254e, 2020-06-19T06:35:49.048Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-9120 RADEON R3, 4 COMPUTE CORES 2C+2G    (2 x 2196)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
Looks like a duplicate of #100047

Your Windows version is Version 1809 (October 2018 Update). 

Does the problem only happen with a git bash shell?

Use the `Select Default Shell` option at the end of the dropdown,

![image](https://user-images.githubusercontent.com/6726799/85182608-18833a00-b281-11ea-9a10-56976c0f8b0b.png)

then pick a different shell (below is the list I get)

![image](https://user-images.githubusercontent.com/6726799/85182527-dbb74300-b280-11ea-9015-818703c208df.png)

then the '+' button

![image](https://user-images.githubusercontent.com/6726799/85182659-3f417080-b281-11ea-885b-d38745ca3ad4.png)

**Comment by ChamuMutezva** [comment]
Thanks @gjsjohnmurray . The above suggestion solved the issue
