### ISSUE TITLE
couldnot  connect to marketplace

### ISSUE THREAD

**Issue by Amitupadhyay368** [microsoft/vscode#100689]
Issue Type: <b>Feature Request</b>

error occurs  on connection.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
What is the error? Do you mind sharing a screenshot of the error?
