### ISSUE TITLE
Integrated Terminal - Windows Bash - Arrow keys not responding

### ISSUE THREAD

**Issue by brianblakely** [Microsoft/vscode#10060]
* VSCode Version: 1.3.1
* OS Version: Windows 10.0.14393

Steps to Reproduce:

1. Enable user setting `"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe"`
2. Open integrated terminal
3. Try to use arrow keys

**Comment by mzvast** [comment]
@brianblakely Have you installed some packeges on VScode?I don't know why I get error once several packages installed.

**Comment by brianblakely** [comment]
The only extension I have installed is ESLint.

**Comment by Tyriar** [comment]
I could reproduce this, not sure if it ever worked though?

**Comment by mzvast** [comment]
I could reproduce this.
No history could be fetched with arrow key broken down.Especially use VIM, arrow key can't move.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10163
