### ISSUE TITLE
Visual Studi Code Takes To long to open

### ISSUE THREAD

**Issue by RamosAndreas** [microsoft/vscode#100636]
Issue Type: <b>Performance Issue</b>

Every time I logged in into my computer and I boot it up, when i try to open the app, it has slow start up and some times it keeps asking do i ha ve to keep waiting or reopen the app.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    79	   892	code main
    0	   175	   564	   gpu-process
    0	    25	  2392	   utility
    2	    64	  4336	   window (Issue Reporter)
    0	    73	  5052	   shared-process
    0	   183	 10460	   window (main.js - DicodingBooks - Visual Studio Code)
    0	     5	  2836	     console-window-host (Windows internal process)
    0	     4	  4856	     C:\WINDOWS\System32\cmd.exe
    0	    11	  7972	     watcherService 
    0	    11	  1800	       console-window-host (Windows internal process)
    0	    38	  8808	     searchService
    0	    86	 10656	     extensionHost
    0	    36	   856	       electron_node tsserver.js 
    0	    36	  3824	       electron_node tsserver.js 
    0	    14	 10800	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (main.js - DicodingBooks - Visual Studio Code)
|    Folder (DicodingBooks): 16 files
|      File types: js(6) html(2) json(2) css(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
vscode-eslint|dba|2.1.5
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.3.12
code-runner|for|0.10.0
search-node-modules|jas|1.3.0
java|red|0.63.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
vscode-icons|vsc|10.1.1
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
If you start code.exe with the CLI flag --disable-extensions is it fast enough? If so I suggest you create a scratch XYZ.code-workspace file, relaunch normally, then disable half of your extensions for this workspace only. Now restart VS Code. If still slow, disable half of the remaining extensions (only for this workspace) and restart. If the half you disabled last time included the one previously making startup slow, re-enable half of the half. Repeat this bisect until you pinpoint the culprit.

Using the XYZ.code-workspace means you don't have to remember which extensions are globally disabled.

**Comment by RamosAndreas** [comment]
So are you saying that I should create a new workspace? and in that new workspace I should disable all the extentions so that when I close the app and I  want to use VS Code again it should open the xyz.code workspace and theoretically have a better start up.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
