### ISSUE TITLE
Changing file case is not reflected in breadcrumbs

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#100633]
Steps to Reproduce:

1. open a file
2. ensure breadcrumbs show up with outline
3. rename case of file to lowercase

=> 🐛 breadcrumb label shows with the previous casing

**Comment by bpasero** [comment]
I pushed a change to have `IFileEditorInput.label` property and here is some code I tried it with for `breadcrumbsControl` for its `update` method:

```ts
// honor diff editors and such
let input = this._editorGroup.activeEditor;
if (input instanceof SideBySideEditorInput) {
	input = input.primary;
}

const fileEditorInputFactory = Registry.as<IEditorInputFactoryRegistry>(EditorExtensions.EditorInputFactories).getFileEditorInputFactory();
let uri: URI | undefined;
if (fileEditorInputFactory.isFileEditorInput(input)) {
	uri = input.label;
} else {
	uri = input?.resource;
}
```

This makes the label appear correctly, however I noticed that all the outline information does not show anymore so there must be more issues. I guess the URI still needs to be the original one, but the label needs to be wired in somehow to the place where it is displayed.

**Comment by jrieken** [comment]
@bpasero Took your changes but in addition to the canonical uri.

**Comment by bpasero** [comment]
@JacksonKearl maybe the bot should check if the issue is already verified
