### ISSUE TITLE
visual studio uninstalled itself

### ISSUE THREAD

**Issue by juannieblas** [microsoft/vscode#100630]
today afternoon I installed the ms-python.python extension after this I continued working normally, a few seconds later code closes, and an error appears on my pc that says code.exe refers to an object that does not exist. .. since it was time to leave my work I decided to leave it there, at the moment I am resuming my work and I see that the code is uninstalled, I had to go to the web and download it again

**Comment by juannieblas** [comment]
CPUs | Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.94GB (10.99GB free)
Process Argv |  
Screen Reader | no
VM | 0%

**Comment by juannieblas** [comment]
remote-wsl | ms- | 0.44.3
-- | -- | --
python | ms- | 2020.6.89148

**Comment by juannieblas** [comment]
as additional data I was working on WSL/Scrapy framework

**Comment by awarmfastbear** [comment]
I just had the exact same issue...I had been doing some ReactJS coding last night. I didn't install any new extensions. I think I remember closing everything down with ALT+F4. Then I shutdown my Windows 10 PC and started it up this morning only to find VS Code Insiders uninstalled with a broken shortcut in the task bar. 

I don't remember what version of VS Code Insiders was installed.

OS info:
OS Name: Microsoft Windows 10 Home
Version	10.0.19041 Build 19041

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
