### ISSUE TITLE
VSCODE -- freeze, or fail to start on chromebook. 

### ISSUE THREAD

**Issue by mikewguo** [microsoft/vscode#100620]
- VSCode Version: 1.46 - 1. The latest/latest version 1.46, just downloaded today 6/192020
- OS Version: ChromeOS Version 84.0.4147.51 (Official Build) beta (64-bit)

Steps to Reproduce:
1. VSCODE only loads immediately after a Chromebook reboot.  If I use chrome for half an hour, opening just 3-4 tabs, vscode can no longer load.
2. Immediately after reboot, start vscode, and then even with 3-4 tabs on chrome browser, it still works, until it freezes -- usually after a little inactivity.  If I put Chromebook to sleep and back, it definitely freezes.

So many version ago, it used to not have this hang/free/non-start problem.  WIth each release, it got worst.  Does anyone care for startup performance in the team?  Please keep startup path simple and easy.  If I am doing complex work and hang, I can understand, and I can stop some of my own behavior.  But this is deal breaker. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes, there is zero extension installed.  And I disabled everything I can find, such as no checking update, no open last project, no git hub integration, etc, etc.  Desperately want to love vscode.

**Comment by mikewguo** [comment]
one advice: please keep the startup code path clean, clean, and clean, and NEVER NEVER NEVER add anything to it. Make this your architecture/design principle.  If you add anything at all, have it disabled by default, and let people enable them as they wish.  People are smart -- don't worry -- they will figure it out.   If they run into trouble, they can disable, and life will go on.  But failure at startup, it kills your product completely.

**Comment by bpasero** [comment]
ChromeOS is not a supported OS for VSCode. Please see https://code.visualstudio.com/docs/supporting/requirements

**Comment by zardoz01** [comment]
This seems like a massive copout. Of course Chrome OS is not supported. Chromebooks run Linux and VSCode s run in a Linux VM so not directly in Chrome OS. My observation is that VSCode now freezes whenever I return to use it from the Lock Screen. This wasn't the case previously but my understanding is that Chrome OS now runs Linux in a VM (same as Windows WSL2) whereas previously Linux ran in a container. The freezing issue may well be related to the changes to Chrome OS Linux handling but to close this issue without further discussion is not helpful.
