### ISSUE TITLE
Webextension Intellisense

### ISSUE THREAD

**Issue by shhlkien** [microsoft/vscode#100650]
Visual Code has a great intellisense for Javascript. Since I am a browser extension developer, I want it to support for webextension api such as `chrome` or `browser` namespace as `window` namespace in web. Could you consider this idea?

**Comment by yume-chan** [comment]
```shell
npm i -D @types/chrome
```

https://www.npmjs.com/package/@types/chrome

**Comment by shhlkien** [comment]
> ```shell
> npm i -D @types/chrome
> ```
> 
> https://www.npmjs.com/package/@types/chrome

Thank you, but it's not has `browser` namespace and I don't want an extra package in my bundled extension, which has browser supports

**Comment by yume-chan** [comment]
> and I don't want an extra package in my bundled extension

No, `@types/chrome` contains zero bits of JavaScript code and won't appear in your bundled file. Its only purpose is telling editors the existence of Chrome extension APIs.
