### ISSUE TITLE
Save causing unexpected behavior

### ISSUE THREAD

**Issue by deveshsjain** [microsoft/vscode#100664]
Issue Type: <b>Bug</b>

Write a functioning java code.
Save causes characters to disappear. need to undo and redo changes for expected save.

//code used

```
/*
import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;

public class Solution {

    public static void main(String[] args) {
        /*
         * Enter your code here. Read input from STDIN. Print output to STDOUT. Your
         * class should be named Solution.
         */

        Scanner sc = new Scanner(System.in);
        int sum = 0, y = 0, x = sc.nextInt();
        List<Integer> list = new ArrayList<Integer>();
        for (int i = 0; i < x; i++)
            list.add(sc.nextInt());

        // int[] arr = list.toArray();
        // System.out.println(list);
        for (int i = 0; i < x; ++i) {
            if (list.get(i) < 0)
                sum += 1;
            for (int j = i; j < x; ++j) {
                y += list.get(j);
            }
            if (y < 0 && i != x - 1)
                sum += 1;
            y = 0;
        }
        System.out.println(sum);
    }
}
*/

```
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
<summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.36.0
vscode-eslint|dba|2.1.5
auto-rename-tag|for|0.1.3
code-runner|for|0.10.0
terminal|for|0.0.10
vscode-docker|ms-|1.3.1
python|ms-|2020.6.89148
vsliveshare|ms-|1.0.2354
vetur|oct|0.24.0
java|red|0.63.0
vscode-xml|red|0.12.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you reload with all extensions disabled?

**Comment by deveshsjain** [comment]
@gjsjohnmurray it doesn't. Looks like a problem with my document formatter extension. Thanks for the same though!
