### ISSUE TITLE
New file name suggestion includes extension which can't be changed

### ISSUE THREAD

**Issue by martineno** [microsoft/vscode#100614]
Issue Type: <b>Bug</b>

When the default file name suggestion includes a period, the default macOS save dialog makes it impossible to save the file with a desired extension.

**Steps**
1. Open a new window
2. Enter the following text in the first line `const arg = process.argv`
3. Change the "Save as" name to `hello.js` from `const arg = process.argv`

**Expected**
Should be able to save the file name and proceed with saving the file

**Actual**
Can't save the file with the desired extension. The dialog box comes up and says "You cannot save this document with extension .js at the end of the name. The required extension is .argv".

**Workaround**
In the save dialog change the "Format" dropdown to "All Files".

Alternativelly add a blank line to the begining of the file to force a default "Unittled" file name and then remove the blank line after saving

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 5|
|Memory (System)|16.00GB (2.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dash|dee|2.4.0
vscode-deno|den|1.25.0
vscode-docker|ms-|1.3.1
cpptools|ms-|0.28.3

</details>

<img width="343" alt="Screen Shot 2020-06-19 at 16 20 23" src="https://user-images.githubusercontent.com/461012/85185536-2c12ae80-b249-11ea-832a-e84a90f35d7d.png">
<img width="568" alt="Screen Shot 2020-06-19 at 16 15 51" src="https://user-images.githubusercontent.com/461012/85185537-2e750880-b249-11ea-9485-1e6a41b58f5a.png">

**Comment by bpasero** [comment]
Turns out this needed a different fix: #102713
