### ISSUE TITLE
unable to debug

### ISSUE THREAD

**Issue by desito07** [microsoft/vscode#100768]
Hi, I am unable to perform debugging. After an update a few weeks ago I cannot use F5 and then F10 to debug. I tried deleting vscode folder, and change the config fine - no joy.  Then I tried to uninstall and install back - the same thing. Now I can`t even get the vscode folder back. Please help!!!!!

**Comment by tekdj7** [comment]
have same issue too

**Comment by desito07** [comment]
It is getting worse every day! Pressing F5, just jump on and off the page, as flickering and nothing happens. My only option is to run the debugger manually, however, in the last few days, I have to close and re-open the app for it to work with the workaround at least. Can you help, please??

**Comment by weinand** [comment]
Please provide information what language/debugger you are using.

**Comment by desito07** [comment]
JavaScript, launch.json

**Comment by weinand** [comment]
In order to learn how to write good bug reports please read https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
