### ISSUE TITLE
Sync should allow you to replace synced data

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100791]
<img src="https://user-images.githubusercontent.com/35271042/84850338-588db700-b00c-11ea-8196-18b5e4bbb158.png">

Sometimes I find myself needing to turn on sync (server issue?) and when I do, the dialog above doesn't give me the option to choose my local machine to be the "master". The only way to do this is to merge and then undo the changes from the other machines. Since I only ever use one machine as the primary one and the others are secondary, I would like to have an option to "replace synced data with local" option.

**Comment by sandy081** [comment]
> The only way to do this is to merge and then undo the changes from the other machines.

This option is not shown here as it is a bit risky.
You can always reset data on the server by choosing `Show Synced Data` view and resetting from there.

Let me know if this makes sense or still an option here is needed.

**Comment by misolori** [comment]
@Tyriar had an interesting idea where the button options could be:
- Replace Local (most common on secondary machines)
- Manual Sync (this would show [the proposed ui](https://github.com/microsoft/vscode/issues/100346#issuecomment-648416726))
- Cancel

Thoughts? This way in the manual sync flow you can still choose the primary to replace the remote.

**Comment by sandy081** [comment]
I would like to have Merge option because I trust what Sync does and allows it to merge. In fact I use it quite often.

I am making this a duplicate of #100346 as I am calling that `Improve first time sync UX` and this is also part for first time sync.
