### ISSUE TITLE
Javascript debugger should show more of text values in the debug console or be configurable

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#100786]
Issue Type: <b>Bug</b>

This appears to be a fairly recent change.  I frequently work with JSON file contents inside strings, and sometimes wish to display the string (which I might copy to an external editor to view).  But recently the debug console started limiting the length of strings it would display, replacing a large chunk with "..." in the middle.  Since the debugger hover also won't display the full value of a string, there's now no way for me to get that full value.  I could understand limiting it to some value, but the current value is way too low, and should be configurable.

![image](https://user-images.githubusercontent.com/6913354/85333130-e85cb680-b48d-11ea-903e-0cdb45fade40.png)

VS Code version: Code - Insiders 1.47.0-insider (b9d7ec9ff367a8e59fe4cc2abee605a55be180e8, 2020-06-19T22:43:58.425Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurestorage|ms-|0.9.0
vscode-azurevirtualmachines|ms-|0.1.1
vscode-cosmosdb|ms-|0.13.0
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
vscode-dotnet-runtime|ms-|0.1.2
azure-account|ms-|0.8.11
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-yaml|red|0.8.0
tmcolor|sle|0.0.1
vscode-todo-highlight|way|1.0.4

</details>

**Comment by isidorn** [comment]
Looking at your screenshoot I believe this is coming from the js-debug. Thus assigning first to @connor4312 

Also we do not shorten the strings in any way in the debug console on the vscode side.

**Comment by connor4312** [comment]
Thanks, I'll look at this. Fyi you can also use `copy(someExpression)` to copy the full value to your clipboard

**Comment by StephenWeatherford** [comment]
I'm sure 100k will be plenty for my purposes, and the copy() suggestion will be helpful, too, thanks!

**Comment by jrieken** [comment]
verified in source
