### ISSUE TITLE
When amending commit, commit message is squished into single line

### ISSUE THREAD

**Issue by ezk84** [microsoft/vscode#100788]
Issue Type: <b>Bug</b>

In a project that has a git repository:

1. Change a file
2. Use Source Control tab to stage changes
3. Add a mutliline commit message (using shift+enter) and commit
4. Change a file again
5. Use Source Control tab to stage changes
6. Click diaeresis (...) button next to repository name and click `Commit Staged (Amend)`
7. Commit message input box has a the whole commit message in a single line, trying to press shift+enter to add newlines will finish the commit.

To get around it one would have to do the `git commit --amend` from the command line instead.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (3.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.3.0
ng-template|Ang|0.901.11
better-toml|bun|0.3.2
gotemplate|cas|0.4.0
vscode-markdownlint|Dav|0.36.0
vscode-eslint|dba|2.1.5
make-hidden|dev|3.0.3
prettier-vscode|esb|5.1.0
auto-close-tag|for|0.5.7
Go|gol|0.14.4
Angular2|joh|9.1.2
AWK|lug|0.0.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.3.1
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.6.89148
remote-containers|ms-|0.122.1
remote-wsl|ms-|0.44.4
debugger-for-chrome|msj|4.12.8
bracketeer|pus|1.2.7
vscode-yaml|red|0.8.0
awk-language-client|TGV|0.1.0
JasmineSnippets|xab|1.0.1

</details>

**Comment by joaomoreno** [comment]
#40295
