### ISSUE TITLE
scroll bar too small

### ISSUE THREAD

**Issue by viponedream** [microsoft/vscode#100766]
too many files in a project,
we always have to drag up and down to find some file. 
now the  scrollbar is too samll hard to drag up or down

![scroll bar too small](https://user-images.githubusercontent.com/16624529/85307043-fa684480-b4e1-11ea-9977-52414b799d71.png)

**Comment by gjsjohnmurray** [comment]
Tip: When focus is on the tree, start typing characters to find your file. The widget that appears also lets you make this act as a filter.

**Comment by gjsjohnmurray** [comment]
/duplicate of #30191

Please add your comments there.
