### ISSUE TITLE
Preferences: Open Settings (JSON) command opens folder settings after using Preferences: Open Folder Settings (JSON) command

### ISSUE THREAD

**Issue by AnthonyWeston** [microsoft/vscode#100752]
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

0. Open a multi-root workspace
1. Ctrl + Shift + P -> Open Settings (JSON) - This opens the user settings.json normally
2. Close settings.json -> Ctrl + Shift + P -> Open Folder Settings (JSON) -> select a folder in the workspace - This opens the folder settings.json normally
3. Close folder settings.json (Or don't, either way gives the same result) -> Ctrl + Shift + P -> Open Settings (JSON) - This opens the folder settings.json that was opened in Step 2.
Open Settings (JSON) doesn't work normally until VSCode is restarted, and only if the folder settings.json isn't reopened when VSCode starts.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/confirmationPending

I wasn't able to reproduce this.

I assume step 0 is to open a multi-root workspace, otherwise the `Preferences: Open Folder Settings (JSON)` command won't be available.

You don't specify if the settings.json file that opens on each step should be closed before proceeding to the next step. I tried both ways but it made no difference, In the third step (you gave two labelled 2) it always correctly opened the user settings file.

**Comment by AnthonyWeston** [comment]
> I assume step 0 is to open a multi-root workspace, otherwise the Preferences: Open Folder Settings (JSON) command won't be available.
Correct, I updated the steps to reflect this

> You don't specify if the settings.json file that opens on each step should be closed before proceeding to the next step.
In the steps I described, I was closing each settings.json file before the next step. I get the same result either way. I updated the steps to clarify.

>  (you gave two labelled 2)
Fixed. I missed adding a space after Step 2, so it skipped numbering that step. 

Thanks!

**Comment by roblourens** [comment]
Are you using the "split" json editor? If so, I can repro, and I think it is by design.

**Comment by AnthonyWeston** [comment]
Yes. I didn't realize that was a customizable option. If I set it to `false`, it behaves as I would expect.

Why would this behavior be by design? I can't imagine any good use case for it.

**Comment by roblourens** [comment]
That command was just designed to open the settings editor to the same state it was previously in, you can switch the target from there. The split editor is sort of deprecated, I don't plan on working on it any more.
