### ISSUE TITLE
setting `editor.semanticTokenColorCustomizations` bolding name of variable instead of keyword name like const, class etc.

### ISSUE THREAD

**Issue by wojcraftinio** [microsoft/vscode#100777]
- VSCode Version: 1.46
- OS Version: Windows 10 Home 2004 19041.329

Hello. I have problem with `editor.semanticTokenColorCustomizations` using `SynthWave '84` theme.
Screenshots are presenting my situation (incorrect), expected score (expected) and my settings screenshot. I get piece of expected image from vscode docs website (April 2020). I think, so that's enough to repair this bug. Thanks for reading and good luck!

screenshot of my settings:
![settings](https://user-images.githubusercontent.com/46259497/85310869-d6423e80-b4b4-11ea-9cbe-564b243aa1e3.png)

incorrect:
![image](https://user-images.githubusercontent.com/46259497/85310281-089f6c00-b4b4-11ea-9400-87b36178743b.png)

expected:
![expected](https://user-images.githubusercontent.com/46259497/85308620-b2c9c480-b4b1-11ea-9ff1-635118551996.png)

**Comment by aeschli** [comment]
`hello` is a variable declaration and is now bold, as specified in your settings.

You can use the `Developer: Inspect Editor token scopes` to see the computed tokens:
![image](https://user-images.githubusercontent.com/6461412/85334332-5da2a880-b4db-11ea-89e2-5f53b9470511.png)

Can you describe what is he expected result for the content `const hello = 'hello'`?

**Comment by wojcraftinio** [comment]
Sure!

word `const` should be bolded instead of `hello`.

For example:
`const`(bolded) `hello = <string>`(not bolded)

**Comment by aeschli** [comment]
But when removing the setting you described above, `const` is not not bold. 
![image](https://user-images.githubusercontent.com/6461412/85515778-cb46f580-b5fd-11ea-93b2-ce27174087a2.png)

And looking at SynthWave '84 theme ffile there is no rule to make `storare.type` bold
https://github.com/robb0wen/synthwave-vscode/blob/master/themes/synthwave-color-theme.json

Maybe the expected screenshot is with a different theme? The colors look very different.

**Comment by wojcraftinio** [comment]
I have tried this with Default Dark theme and still not working. [This](https://code.visualstudio.com/updates/v1_45#_semantic-token-styling) link should you help understand me and presents my expected results. Yes, expected result is with Default Dark theme.

**Comment by aeschli** [comment]
The default Dark theme does not use bold for keywords (or any other symbol). That screenshot is strange. Not sure why it looks like that, maybe a bug that we fixed since.

Semantic highlighting is not about keywords, only bout about identifiers. So you can not make keywords bold with it.

If you want bold keywords: use
```
	"editor.tokenColorCustomizations": {
		"keywords": { "fontStyle": "bold"}
	}
```
