### ISSUE TITLE
Allow custom tree hovers to be markdown

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#100741]
Currently, the tooltip for custom tree items can only be a string. We should also allow markdown.

**Comment by mattacosta** [comment]
So I was only able to get my tooltips containing markdown to work by implementing a do-nothing `resolveTreeItem()` method. Is that supposed to happen? My tree does not need to resolve any data.

**Comment by alexr00** [comment]
Not supposed to happen. I will take a look.

**Comment by alexr00** [comment]
However, if you tree is going to have many items it is better to set the markdown tooltip in `resolveTreeItem` so that you aren't creating all that markdown in advance.

**Comment by alexr00** [comment]
@mattacosta I pushed a fix that should be available in insiders tomorrow.

**Comment by mattacosta** [comment]
More feedback: Not sure if anything can even be done about this, but I'm now noticing that it is significantly easier for the cursor to get into the new hovers compared to the native tooltips, thereby preventing them from going away. This makes it more difficult and/or frustrating to select the tree items that it covers.

**Comment by alexr00** [comment]
I think this is mostly because they are larger, but it would help if the hovers had one of their corners at your mouse, instead of starting where the tree html element starts. 

@Tyriar would it be possible to do this?

**Comment by Tyriar** [comment]
@alexr00 use `IHoverOptions.hideOnHover`, this is ignored if you provide actions though.

**Comment by alexr00** [comment]
@Tyriar would it be possible to have the corner of the hover at the mouse instead of in line with the html element it's attached to?

**Comment by Tyriar** [comment]
@alexr00 `hideOnHover` isn't a good enough solution? Is the hiding of tree items too disruptive? Can you show a gif of the issue as I'm not sure how to show it on the tree atm.

**Comment by alexr00** [comment]
@Tyriar There are things to click and select in the hover, so `hideOnHover` doesn't sound like something I want to use. 
![recording (10)](https://user-images.githubusercontent.com/38270282/89308368-78d40c80-d672-11ea-8248-6ed0d0cb0b2f.gif)

**Comment by Tyriar** [comment]
If it's at the mouse position though you would need to move the mouse to the right in order to hover it. Is this what you mean?

![image](https://user-images.githubusercontent.com/2193314/89311840-5cf94800-d62b-11ea-96ba-29f13d642e5a.png)

cc @misolori

**Comment by alexr00** [comment]
Yep, that's exactly what I mean! That way the behavior is more consistent with the default tooltip and it doesn't obscure all of the tree above it.

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/issues/104058

**Comment by usernamehw** [comment]
Anything blocking this from moving to Stable?

**Comment by alexr00** [comment]
Yes, I need to get the hover working properly on resources (files and the like) when they are in the tree. Once that's good, we can move it to stable shortly after.

**Comment by jrieken** [comment]
* swap argument order
* use `ProviderResult`
