### ISSUE TITLE
Search in Files only searches currently edited file

### ISSUE THREAD

**Issue by mbaas2** [microsoft/vscode#100732]
- VSCode Version: 1.46.1
- OS Version: Windows 10 [Version 10.0.18363.900]

Steps to Reproduce:

1. Open code passing the names of 3 files on the commandline (make sure to have a string which appears in all 3 files)
2. Edit>"Find in Files">Enter search expression matching that string (using regex or not does not make a difference)
3. Only results of active file are shown!
4. Click on tab of 2nd file
5. while search results are shown, call Edit>"Find in Files" again - triggering the option add matches from 2nd file.
6. Click tab of last file and repeat step 5.
--> This is no longer a "Search in file**s**"!

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/confirm

The key to the issue seems to be that the files were opened via command line. Their tabs appear, and they are listed on the OPEN EDITORS view, but somehow they only qualify to be checked by 'Find in Files' (aka Search) after they have actually been displayed.

**Comment by ArturoDent** [comment]
See https://github.com/microsoft/vscode/issues/20530#issuecomment-629398063

> Going back to the original post and the few that followed, which were focused on how to search "only open files", I'll share something I just discovered.
> 
> If you have only opened files in vscode directly, by way of using File>Open, or Open Recent, or by opening a file from the OS into vscode, etc., THEN a search/find in files WILL indeed search ONLY (and all of) those opened files.
> 
> But it's if you use File>Open Folder, that's when things change about search (and of course many other ways about the UI). It THEN presumes to search first all files/folders in THAT folder, and you can't tell it to ONLY search open files. To be clear, it DOES ALSO search open files--and it shows the results of that as "other files", below the search of the "opened folder".
> 
> I suspect it's those folks (who use that valuable "open folder" feature) who are calling for an option to be able to limit the search to ONLY open files. I didn't see it mentioned in any comments above, so I wanted to offer this distinction.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/62488
