### ISSUE TITLE
Error while turning off sync: No Auth Token Available

### ISSUE THREAD

**Issue by wayou** [microsoft/vscode#100714]
Issue Type: <b>Bug</b>

Steps to reproduce:
- <kbd>command</kbd> + <kbd>shift</kbd> + <kbd>P</kdb> open command palette
- Search for `sync off` and select `Preference Sync: Trun off`
- Shows the error `Error while turning off sync: No Auth Token Available`

VS Code version: Code - Insiders 1.47.0-insider (b9d7ec9ff367a8e59fe4cc2abee605a55be180e8, 2020-06-19T22:43:58.425Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 8|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_479349|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
markdown-toc|Ala|1.5.6
vscode-bazel|Baz|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
npm-intellisense|chr|1.3.0
codealignment-vscode|cpm|2.0.19
dart-code|Dar|3.11.0
flutter|Dar|3.11.0
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
vscode-wasm|dts|1.3.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.1.0
php-intellisense|fel|2.3.14
file-icons|fil|1.0.24
auto-close-tag|for|0.5.7
shell-format|fox|7.0.1
Go|gol|0.14.4
vscode-power-mode|hoo|2.2.0
theme-macos-classic|hua|1.2.1
search-node-modules|jas|1.3.0
svg|joc|1.3.4
markdown-toc|jof|1.4.0
vscode-styled-components|jpo|0.0.29
auto-comment-blocks|kev|1.0.1
vscode-fileheader|mik|0.0.2
vscode-csscomb|mrm|5.3.1
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.3.1
remote-containers|ms-|0.123.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.28.3
debugger-for-chrome|msj|4.12.8
indent-rainbow|ode|7.4.0
emoji|Per|0.0.3
material-icon-theme|PKi|4.2.0
seti-icons|qin|0.1.3
nginx-formatter|ray|0.0.8
gi|rub|0.2.11
vscode-nginx|sha|0.6.0
html5-boilerplate|sid|1.0.3
type-doc-vscode|Tre|0.0.35
vscode-qcfe|way|0.1.0
file-icons-mac|way|1.0.1
vscode-icons-mac|way|7.25.3
vscode-qcfe|way|0.1.0
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2
vscode-proto3|zxh|0.4.2

(13 theme extensions excluded)

</details>

![Screen Recording 2020-06-22 at 10 05 32 mov](https://user-images.githubusercontent.com/3783096/85242038-76c23f80-b470-11ea-9077-2e208be95b49.gif)

**Comment by sandy081** [comment]
Can you please provide following logs:

- View -> Open View… -> Log (Preferences Sync)
- View -> Open View… -> Output -> Account (Microsoft / GitHub)

**Comment by wayou** [comment]
Hi @sandy081 ,as you can see from the gif above, there's nothing in the view `Log (Preferences Sync)`.
And there's no such view `Output -> Account (Microsoft / GitHub)` on my side neither :(

**Comment by sandy081** [comment]
Can you please check if Sync is turned on from the Settings Gear icon in the bottom left?

**Comment by wayou** [comment]
<img width="349" alt="You are not signed in to any accounts" src="https://user-images.githubusercontent.com/3783096/85488119-5aeda380-b600-11ea-877a-5e3cb1a9a23c.png">

**Comment by wayou** [comment]
Signing in solved the problem.

**Comment by sandy081** [comment]
Looks like turning off from command palette when you are signed out is not working.
