### ISSUE TITLE
VSCode prevents auto-hide Windows taskbar from being visible

### ISSUE THREAD

**Issue by evakili** [microsoft/vscode#100746]
Issue Type: <b>Bug</b>

In Windows settings enabale "Autmatically hide the taskbar in desktop mode". Now if VSCode is maximized (or in full-screen or Zen-mode), moving mouse cursor to the side does not show the hidden taskbar.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

**Comment by bpasero** [comment]
Not sure if this is an Electron issue or not, might also be Windows standard behaviour.

**Comment by evakili** [comment]
At least not showing taskbar if a window is maximized, is not a standard behavior of Windows. (I've now the Chrome browser maximized and taskbar is shown as expected on mouse move to the side).

**Comment by deepak1556** [comment]
@evakili what is the position of your taskbar, the only position I can repro the issue is for `top`, all other positions work fine when window is maximized.

**Comment by evakili** [comment]
@deepak1556 Yes! that is at top!

**Comment by deepak1556** [comment]
Thanks for confirming

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/86260
