### ISSUE TITLE
Checkout branch, corresponding to opening different files

### ISSUE THREAD

**Issue by frei-x** [microsoft/vscode#100713]
Checkout 'A' branch, opened A.js, xxx.js ,

Now checkout 'B' branch. Do not keep opening A.js, xxx.js .

When I check out 'a' branch, open A.js, xxx.js .

**Comment by joaomoreno** [comment]
Is this a feature request to open certain files when certain branches are checked out?

**Comment by frei-x** [comment]
> Is this a feature request to open certain files when certain branches are checked out?

@joaomoreno  Yes, different branches need to open corresponding opened files

This is very useful for large projects when checkout branches frequently,

Because different branches solve different issues, the files that need to be opened are different when checkout branches.

Thank you for your reply. I'm sorry. I'm from China. This is machine translation. It may not be accurate

**Comment by frei-x** [comment]
Hopefully this should be an optional option,

Whether the file in the current window remains open when chcekout,

When other branches of chcekout, close the current window file and automatically open the new branch corresponding to the opened file
