### ISSUE TITLE
Ability to Debug RUST code that uses STDIN inputs on vscode on Windows 10

### ISSUE THREAD

**Issue by dejannenov** [microsoft/vscode#100703]
Presently, there appears to be no way to debug a RUST program in vscode on windows, if the program requires stdin input.

Considering that the second example in the rust book tutorial: 
https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html,
 is in fact such a program, a newcomer to RUST that is looking for fully functional IDE on windows would not be able to use vscode.

This feature request is to enhance the msvc debugging integration for RUST, so that the example code above can be debugged interactively.

**Comment by weinand** [comment]
Please file this feature request against the Rust extension. VS Code provides API to run the debuggee in the integrated terminal or a regular external terminal. Both support that the debuggee can read from stdin. I do not know whether the Rust extension already supports this...
