### ISSUE TITLE
Terminal is open, and just shut down.

### ISSUE THREAD

**Issue by LeeHyungGeun** [Microsoft/vscode#10071]
- VSCode Version: 1.3.1
- OS Version: Windows 7

Steps to Reproduce:
1. Open Ctrl+'
2. CMD Window is open, and just shutdown

**Comment by mzvast** [comment]
@LeeHyungGeun 
I think maybe it something to do with Electron.
Same crash on windows 10x64pro 1607

Fresh Install is fine.After install some pakages,restart and failed!

**Comment by Tyriar** [comment]
You're likely seeing this issue https://github.com/Microsoft/vscode/issues/7727
