### ISSUE TITLE
Single-key shortcuts don't work in file explorer

### ISSUE THREAD

**Issue by Haberkamp** [microsoft/vscode#100773]
It is not possible to use shortcuts with a single letter inside the file explorer.

- VSCode Version: 1.46.1
- OS Version: Darwin x64 19.5.0

Steps to Reproduce:

1. Bind keys <kbd>cmd</kbd>+<kbd>e</kbd> <kbd>n</kbd> to command `explorer.newFile` as shortcut
2. Set 'when'-clause to `explorerViewletFocus && explorerViewletVisible`
3. Press shortcut to create new file

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
Set this to `false` and try it:

`"workbench.list.automaticKeyboardNavigation": false,`

See similar https://github.com/microsoft/vscode/issues/99683#issuecomment-641473196 for more info.

**Comment by isidorn** [comment]
@ArturoDent thanks for jumping in.
Closing as designed
