### ISSUE TITLE
The active item on sidebar has a different border on right position

### ISSUE THREAD

**Issue by coderdiaz** [microsoft/vscode#100784]
- VSCode Version: 1.46.1
- OS Version: 10.15.5

Steps to Reproduce:

1. Go to user settings and change the `sidebar` position from `left` to `right`.
2. Check the active item and the border has `1px` size.

### Sidebar on Left:
![image](https://user-images.githubusercontent.com/1901273/85330139-6ecac580-b499-11ea-8347-e33e34aba1eb.png)

### SIdebar on Right:
![image](https://user-images.githubusercontent.com/1901273/85330192-80ac6880-b499-11ea-89d8-a87c6be8947a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Looks similar to #100309 but doesn't looks like macOS uses chromeless windows

**Comment by coderdiaz** [comment]
@IllusionMH I think will be related 🤔 but on `left` position looks correctly.

**Comment by IllusionMH** [comment]
Can be in case when window is positioned correctly, bit inner dimensions are somehow calculated incorrectly (e.g. https://github.com/microsoft/vscode/issues/90466#issuecomment-584927230) left will be correctly aligned to the edge because coordinates start there, but right will be cropped by 1px. However this is guess without any proofs :(

**Comment by IllusionMH** [comment]
@sbatten not sure about Mac but now it's consistently bad on Windows - for both left and right positions:


Maximized with `"window.titleBarStyle": "custom"`
![image](https://user-images.githubusercontent.com/1312662/86017449-b5d23100-ba2c-11ea-95cb-13c32fcc1e2d.png)

Maximized with `"window.titleBarStyle": "native"`
![image](https://user-images.githubusercontent.com/1312662/86017469-ba96e500-ba2c-11ea-9d4d-f8de8383e0a4.png)

Regular window with `"window.titleBarStyle": "custom"`
![image](https://user-images.githubusercontent.com/1312662/86017914-5163a180-ba2d-11ea-9e26-ac8ed4569be2.png)

**Comment by sbatten** [comment]
@IllusionMH can you show me a comparison with stable in those configurations?

**Comment by IllusionMH** [comment]
@sbatten sorry, looks like I was incorrect about case when left position get worse - it was already bad
![image](https://user-images.githubusercontent.com/1312662/86020001-04cd9580-ba30-11ea-8789-57182bd9f110.png)
screenshot is for 1.46.1, but found 1.43 and it has same problem

Not sure how I have it sometimes correct size on the left and consistently incorrect on the right.

Probably Windows case should be tracked in #100309

**Comment by sbatten** [comment]
Don't use a maximized window as there seems to be a separate issue for that.

To Verify:
1. Toggle side bar position
2. Ensure the active icon border is the same size on both sides in the activity bar
