### ISSUE TITLE
References: clicking on result moves focus into editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#100726]
Steps to Reproduce:

1. run a reference search
2. click on a result

=> 🐛  focus moves into the editor

**Comment by joaomoreno** [comment]
I can't reproduce. 🤔 Can you repro with a fresh setting base?

**Comment by bpasero** [comment]
Very likely already fixed, cannot reproduce running from `master`

**Comment by bpasero** [comment]
Ah, it is the references view that has this behaviour, not the search.

**Comment by jrieken** [comment]
Likely caused by https://github.com/microsoft/vscode-references-view/pull/62
