### ISSUE TITLE
VSCode Terminal Always Grabs Keyboard

### ISSUE THREAD

**Issue by jayded** [microsoft/vscode#100799]
Issue Type: <b>Feature Request</b>

The VSCode terminal always grabs the keyboard on reconnect/any restart of the terminal (e.g. when using the remote server connection), while the editor itself is ready to receive input. This means one can start editing, and have the mouse grabbed by the terminal. Multiple times. This makes for a very bad editing experience. Perhaps the terminal shouldn't grab focus at all?

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.5.0
Remote OS version: Linux x64 4.4.0-139-generic

**Comment by Tyriar** [comment]
It shouldn't unless you open the terminal. Do you have an extension that could be doing this? A list of extensions and a [gif](https://gifcap.dev/) would help.
