### ISSUE TITLE
Quick pick should fuzzy search on the folder names in multi-root workspaces

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#100723]
VSCode supports [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces).

In the example you give in the docs, the `.code-workspace` file looks like this:

```json5
{
  "folders": [
    {
      // Source code
      "name": "Product",
      "path": "vscode"
    },
    {
      // Docs and release notes
      "name": "Documentation",
      "path": "vscode-docs"
    },
    {
      // Yeoman extension generator
      "name": "Extension generator",
      "path": "vscode-generator-code"
    }
  ]
}
```

Now let's say I want to open `README.md` from the vscode-docs folder.

I press <kbd>Ctrl</kbd>+<kbd>P</kbd> and then type `doc README.md`, and I get no results, even though the folder path is `vscode-docs`, and the folder name is `Documentation`.

Please make fuzzy search also search the folder path & name.

**Comment by gjsjohnmurray** [comment]
Seems related to #32444 but that one had a fix merged a few months back. So perhaps this one is an unhandled variant.

**Comment by bpasero** [comment]
I cannot reproduce:

![image](https://user-images.githubusercontent.com/900690/85371359-61ace580-b530-11ea-9ff8-5300a84f7c7c.png)

**Comment by NotWearingPants** [comment]
The problem was that my VSCode was not updated recently and I didn't know this was added, sorry 🙄
