### ISSUE TITLE
autopep8 not working in VSCode

### ISSUE THREAD

**Issue by ThamuMnyulwa** [microsoft/vscode#100708]
I am new to using VS Code and trying to use autopep8 in order to format my python notebooks. I have come across this page [Editing Python in Visual Studio Code](https://code.visualstudio.com/docs/python/editing) but am unable to implement it. Please can you show me how to do this.

My latest attempt led me to this error message

<code>Command 'autopep8' resulted in an error (Running the contributed command: 'extension.sayHello' failed.) </code>

Please can you help me get autopep8 working for python notebooks.

**Comment by NotWearingPants** [comment]
What operating system are you using?

**Comment by ThamuMnyulwa** [comment]
Hi @NotWearingPants  I am using Ubuntu 18.04 as my operating system.

**Comment by NotWearingPants** [comment]
Try running `sudo pip install autopep8`, and then checking if the command `autopip8` exists

**Comment by rebornix** [comment]
Please file this issue against the Python extension.
