### ISSUE TITLE
Jupyter Notebook - Option to Disable Wordwrap in Cell Results

### ISSUE THREAD

**Issue by diveyseek** [microsoft/vscode#100710]
Hi, 

**Feature / Issue**
It would be great to be able to disable word wrapping in Jupyter Notebook Cell Results

Currently if you have a dataframe with a large number of columns or a dataframe with long fields or field names the results end up wrapping and the results are unreadable.

My current work around is to copy and paste the results into Notepad++ to view them there which is a pretty poor experience.

Searching and posting questions via Stackoverflow hasn't resulted in a way around this :(

**System details**
VS Code 1.46
Windows 10 20.04

**Sample Result**
![Wrap](https://user-images.githubusercontent.com/25731279/85237383-bdf90200-b469-11ea-91d7-b323e54a7ecb.jpg)

**Sample Code**
Sample code to generate a wide Pyspark dataframe that will wrap .... 
`spark.sql("select 'field1field1field1' as field1, 'field2field2field2' as field2, 'field3field3field3' as field3, 'field4field4field4' as field4, 'field5field5field5' as field5, 'field6field6field6' as field6, 'field7field7field7' as field7, 'field8field8field8' as field8, 'field9field9field9' as field9, 'field10field10field10' as field1, 'field11field11field11' as field11, 'field12field12field12' as field12, 'field13field13field13' as field13, 'field14field14field14' as field14, 'field15field15field15' as field15, 'field16field16field16' as field16, 'field17field17field17' as field17, 'field18field18field18' as field18, 'field19field19field19' as field19, 'field1field1field1' as field1, 'field2field2field2' as field2, 'field3field3field3' as field3, 'field4field4field4' as field4, 'field5field5field5' as field5, 'field6field6field6' as field6, 'field7field7field7' as field7, 'field8field8field8' as field8, 'field9field9field9' as field9, 'field10field10field10' as field1, 'field11field11field11' as field11, 'field12field12field12' as field12, 'field13field13field13' as field13, 'field14field14field14' as field14, 'field15field15field15' as field15, 'field16field16field16' as field16, 'field17field17field17' as field17, 'field18field18field18' as field18, 'field19field19field19' as field19").show(10, False)`

**Comment by rebornix** [comment]
Please file this issue against the Python extension.
