### ISSUE TITLE
XDebug Through Vagrant Ubuntu Not Working

### ISSUE THREAD

**Issue by rmb32** [microsoft/vscode#100707]
When trying to run PHP debugging, I always get the following without any debugging output, no matter what:
```
<- launchResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 2,
  command: 'launch',
  success: true
}
```

My "launch.json" settings are:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "pathMappings": {
                "/projects/websites": "d:/dev/websites",
            },
            "port": 9000,
            "log": true
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
```

I run Windows and have a Vagrant environment using VirtualBox, running Ubuntu Xenial64.
I have Apache and PHP 7.3 set up on the Vagrant environment along with XDebug.
I have the "Xdebug helper" extension for Chrome enabled with the IDE key for "other" set to "vscode".

XDebug works as it responds to specific "xdebug_" functions in PHP and re-formats var_dump calls.

Strangely, I get the same 'success' message in the debug console regardless of whether Vagrant is running or not.

When I set a breakpoint and reload a page that is definitely using that line of code, the page loads fully without stopping at the breakpoint.

In my `/etc/php/7.3/mods-available/xdebug.ini` file, I have:
```
zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_connect_back=0
debug.remote_port=9000
xdebug.max_nesting_level=1000
xdebug.remote_autostart=1
xdebug.remote_host=10.0.2.2
xdebug.remote_log=/var/log/xdebug.log
xdebug.idekey="vscode"
```

I've tried a lot of other things including putting the above settings at the end of my `php.ini` file following the "[XDebug]" heading, all without luck.

**Comment by weinand** [comment]
please file issue against php extension you are using
