### ISSUE TITLE
Broken unit test: WorkspaceConfigurationService - Remote Folder update remote settings

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#100700]
Failed on macOS:

```
  1) WorkspaceConfigurationService - Remote Folder update remote settings:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
```

https://dev.azure.com/vscode/VSCode/_build/results?buildId=46792&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=b16e48eb-d187-5f92-5721-e17908fef4e2

**Comment by joaomoreno** [comment]
Another one: https://dev.azure.com/vscode/VSCode/_build/results?buildId=46960&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=b16e48eb-d187-5f92-5721-e17908fef4e2

**Comment by sandy081** [comment]
Skipping this test as I do not have any clue why it is failing.

**Comment by bpasero** [comment]
@sandy081 can you remove the test then? I think leaving skipped tests is not very helpful.
