### ISSUE TITLE
no paste item when select a file

### ISSUE THREAD

**Issue by viponedream** [microsoft/vscode#100767]
when we change a file , we ofter need to make a copy first.
but now before paste a file  we have to select a folder,  if too many files in a folder, it's easy to select to wrong folder.

if we select any file and paste, it's certain in the same folder. 

![no paste](https://user-images.githubusercontent.com/16624529/85307351-65198000-b4e2-11ea-888e-70c0e037b627.png)

**Comment by gjsjohnmurray** [comment]
Did you try any extensions? For example https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils looks relevant.
