### ISSUE TITLE
Preview selected file in Explorer when using arrow keys

### ISSUE THREAD

**Issue by imAliAzhar** [microsoft/vscode#100744]
Right now, if I click on a file in Explorer, the file opens up in a preview window. But if I navigate the directory tree with arrow keys, the selected file doesn't open up in a preview tab unless I press Cmd+Down (on mac) for the selected file.
It would be really helpful for quickly glancing files if the selected file would automatically open up in a preview window.

This can also work in the SCM tab when navigating changed files.

**Comment by isidorn** [comment]
Press `space` key for preview.

**Comment by imAliAzhar** [comment]
@isidorn Yes but the feature I am requesting is for me to not have to press `space` for previewing. Selected file should be previewed automatically without needing me to press `space`.

**Comment by isidorn** [comment]
Ok. I can reopen this and keep it open as a feature request but I think we will not do this.
