### ISSUE TITLE
renaming by /only/ changing capitalisation of a file with an ending (letters stay the same) has no effect on the file name capitalisation in Windows Explorer

### ISSUE THREAD

**Issue by lorenzznerol** [microsoft/vscode#100763]
- VSCode Version: 1.46.1
- OS Version: Windows 10 Home Version 1909

Steps to Reproduce:

01. create an empty file in Windows, e.g. called test.xyz - the file ending is unimportant, it can also be .txt, .java, .py or whatever.
02. change the file to Test.xyz
03. After pressing enter, the file is still named text.xyz.

This has the following same effect in the rename function of vscode. You can repeat the steps 1 to 3 and see that you have the same issue in vscode.

This has the bad side effect that class and class files should be named the same, and this is a case-sensitive requirement, e.g. in Java.

Going through this issue with respect to a Java programmer who has mistakenly called his class and his class file "test.java" and `public class test {}` repectively and now renamed the class in her code to `public class Test {}`.
1. She wants the real file name in Windows to change to Test.java as well, renames the file the left panel of vscode and saves
2. The file in vscode's file panel shows up with the new name Test.java. 
3. She runs the Java file. error: `The public type Test must be defined in its own file.`
4. She sees that the header of the file edit is still test.java and closes the file. 
5. She opens Test.java again but the file edit header is still test.java, and same error when running.
6. She closes vscode and looks up the Windows Explorer and has the same issue as shown in the 01,02,03 points above.

99. The only way to change it is to rename it by taking away the file type ending (.java) and press enter. Then, you can change the capitalisation as you like. And afterwards, add .java ending again.
This works both vscode or in Windows Explorer. Thus it is a Windows issue. 

Suggestion / idea:
When you have the case of a change in capitalisation only, while the letters stay the same: It could be automatically programmed in vscode to use an invalid and completely unused ending first (in order not to overwrite any other files) first, and after renaming changing back to the right ending, or to copy the file into a vscode temp folder and delete it physically and then save it back with the right capitalisation.

Does this issue occur when all extensions are disabled?: Yes/No
This is not relevant as it is a Windows issue that is only carried to vscode.

**Comment by dbaeumer** [comment]
Since this is Java specific please file the issue against the extension that provides you with the Java support.

**Comment by lorenzznerol** [comment]
This is not a Java specific Problem, you can do this with any file that has an ending, I have tested this with .py and with an imaginary xyz. It is a Windows issue that vscode might be able to solve, see my suggestion above. Now it is necessary to manually remove the ending temporarily, then change the capitalisation, and then add the ending again in Windows Explorer. That is why I ask you to re-open this issue here.

**Comment by bpasero** [comment]
@lorenzznerol does this still reproduce with latest? you said there are steps to reproduce without having to use Java, can you elaborate?

**Comment by lorenzznerol** [comment]
That is ok of course. I just wanted to let vscode know about it, even though it is just a very tiny and unimportant thing. Since it is not a vscode issue, but a Windows issue, it might be too unimportant to address at all, I guess closing this issue is just right.
