### ISSUE TITLE
Fail to update git branches - needs IDE restart in order to do so

### ISSUE THREAD

**Issue by selfrefactor** [microsoft/vscode#100754]
I am opening this as I cannot reopen https://github.com/microsoft/vscode/issues/93314

I am on Manjaro and I definitely sure it is not OS related problem. Still, this issue is frustrating as it keeps happening for a long time.

At that point I restart VSCode as I prefer it to the false hope that it might work.

Maybe your tests for this feature are incomplete or missing as I cannot explain myself the lack of progress for this issue. The other explanation is that the whole VSCode team works on Mac and this is issue related to Linux.

**Comment by joaomoreno** [comment]
Reopened the original issue.

**Comment by selfrefactor** [comment]
@joaomoreno 
I cannot comment on the original issue as I am not a collaborator 
![vscode-bug](https://user-images.githubusercontent.com/2149294/85568857-b9377800-b63a-11ea-9ae2-b285230673c1.gif)

In this recording not only I had to restart VSCode, but also to click the icon to update the branches. Usually only restart of VSCode is enough and click of icon is not necessary.

**Comment by joaomoreno** [comment]
Sorry about that, I've unlocked that issue.

Cool, thanks for using gifcap! 🙏
