### ISSUE TITLE
Stop "This extension is recommended based on the files you recently opened." and similar behavior

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#100750]
Issue Type: <b>Bug</b>

I'd prefer extension recommendations based on more valuable factors, like those placed specifically in workspace settings. The recommendations based on factors like "files I have recently opened" are mostly useless and annoying.

I do not need a myriad of SQL-related extensions in my installation, just because I've openend a `.sql` file recently or because I have a specific application installed. Installing excessive amounts of extensions should be discouraged, due to the instability they cause. I don't understand this excessive force to drive users to installing them. There is a reason disabling extensions is the first thing you request users to do when they experience issues with VS Code. Please at least give me the option to disable this behavior.

The entire feature **could** be so useful, in that it provides a quick overview of which extensions make sense to use in the current project or which are actually _required_ for a proper experience. Instead you devalue it by littering it with the most useless information possible. Do you really think I need some "npm command Intellisense" for the entire project just because it has a single `package.json` file? I strongly disagree with that. And these suggestions are valued on the same level as something the workspace author specifically picked out to be a valuable asset for the project. I find that to be a very frustrating experience that continously bothers me when adjusting to new projects.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (41.17GB free)|
|Process Argv|core-web2/core-web2.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
code-beautifier|mic|2.3.3
vscode-puglint|mrm|2.3.0
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.8
vscode-paste-image|mus|1.0.4
vscode-yaml|red|0.8.0
vscode-icons|vsc|10.1.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
> Please at least give me the option to disable this behavior.

Did you try these?

![image](https://user-images.githubusercontent.com/6726799/85284636-708b8d80-b487-11ea-8b71-8f13f48733cb.png)

**Comment by oliversalzburg** [comment]
I actually have **Ignore Recommendations** already enabled, which is somewhat confusing, given that I'm seeing recommendations.

So, to confirm, when I _enable_ **Ignore Recommendations** and reload the window (just to be sure), I'm seeing 9 recommended extensions, based on several factors, none of which is an explicit recommendation from the workspace.

When I _disable_ **Ignore Recommendations** and reload the window, I'm seeing 2 recommended extensions, because "I have Kubernetes installed".

To be clear, I'm not opposed to having extensions recommended to me. I feel the workspace maintainer has a pretty good understanding of which extensions make sense in the current context. I claim that whatever logic is implemented in VS Code to make these recommendations _automatic_, is broken by design and a way to disable _only those_ would be beneficial.

I should have probably labeled this as a feature request and not a bug, but given the observed behavior I described above, maybe it is actually a bug.

**Comment by sandy081** [comment]
Can you please let us know which extensions are being recommended when you enable / disable this setting. And these recommendations are shown as notifications or where are you seeing these?

Can you also please let us know what do you see in extensions view > show recommendations in both cases?

**Comment by oliversalzburg** [comment]
I can't reproduce the behavior I saw when toggling the **Ignore recommendations** setting on my current workstation. Might have been specific to the other workstation or a different root cause.

The behavior I'm observing is specific to the **Recommended** section of the extensions pane:
![image](https://user-images.githubusercontent.com/1658949/86232065-c05b0a80-bb93-11ea-877f-d876f74b48fd.png)

When searching for "@recommended" or using the command you provided, I get a new section specific to workspace recommendations (thanks for the heads-up). 

I still get conflicting recommendations that would cause issues in our environment in the **Other recommendations** section though. Installing these would be counter-productive to our workflow. It seems counter-intuitive that these destructive suggestions are placed on the same level as the carefully authored ones from our workspace. Like, I regularly get recommendation to install the JSHint extension, even though we use ESLint throughout our entire ecosystem. Or I get a suggestion to install Beautify, even though we use a different code formatter.

This is a view one of our new users might see when they open the extensions pane for one of our workspace. 

![image](https://user-images.githubusercontent.com/1658949/86232937-fcdb3600-bb94-11ea-9b18-36e665cb59f4.png)

This user is missing an important extension (puglint) that is recommended in the workspace. If they don't specifically search for that, they will not realize it or possibly install _all_ recommended extensions, which would cause more problems.

Maybe I'm missing something, but an option to _fully_ ignore (as in invisible) automatically generated recommendations would be greatly appreciated. I also really like that workspace recommendations are a distinct section when searching for recommendations. I don't quite understand why this distinction isn't made by default. It seems like that'd be beneficial.

**Comment by gjsjohnmurray** [comment]
@oliversalzburg does this setting meet your need?

`"extensions.showRecommendationsOnlyOnDemand": true`

**Comment by sandy081** [comment]
@oliversalzburg Default recommendations do show workspace recommendations. It is union of workspace recommendations + a random subset of other recommendations. Workspace recommendations are shown in the top of the list. If you do not want a recommendation in other recommendations to be shown you can configure to ignore it in `extensions.json` file in the workspace

<img width="697" alt="image" src="https://user-images.githubusercontent.com/10746682/86243829-4c2a6200-bba7-11ea-81b8-992454736055.png">

Let me know if there is anything missing after this?

**Comment by oliversalzburg** [comment]
@gjsjohnmurray Not really, because I'm not concerned for myself, but for people I work with. My opinion is that the current default is counter-productive and requires additional instructions to be useful (by using the setting you recommended or searching manually).

Suggesting a myriad of random extensions to new users doesn't seem beneficial either, as extensions seem to be the primary cause of issues in VS Code. So driving new users towards known problems, just so they can experience extensions, doesn't seem compelling to me.

@sandy081 That's actually not bad. Is there a full list available of the extensions that VS Code will pick for suggestion, so that I can exclude the entire list in every workspace?

**Comment by sandy081** [comment]
> Is there a full list available of the extensions that VS Code will pick for suggestion, so that I can exclude the entire list in every workspace?

This list is dynamic and adding full list might not be a good idea and also this includes some user specific extensions like WSL and it is helpful for user to know that. If user wants to see only workspace recommendations and not others by default, we can make this configurable at user level.

CC @sana-ajani - for any other better advice or if we are missing any.

**Comment by gjsjohnmurray** [comment]
@oliversalzburg does it help that the `"extensions.showRecommendationsOnlyOnDemand": true` can be set at the workspace level?

**Comment by gjsjohnmurray** [comment]
> This list is dynamic and adding full list might not be a good idea and also this includes some user specific extensions like WSL and it is helpful for user to know that.

@sandy081 in #74137 it was suggested to extend `unwantedRecommendations` syntax so it can indicate "all". You closed it as a dup, but it's not clear to me how the one you pointed to will meet @oliversalzburg's need. It's also a bigger issue and likely to take longer to arrive (if it ever does).

**Comment by oliversalzburg** [comment]
> @oliversalzburg does it help that the `"extensions.showRecommendationsOnlyOnDemand": true` can be set at the workspace level?

I'm an idiot for not realizing that. 😅 Thank you, that does help.

**Comment by oliversalzburg** [comment]
If there was a way so I could achieve that the workspace recommendations would still be visible, that'd be nice to have though.

**Comment by sandy081** [comment]
@gjsjohnmurray That was an impeccable finding. 

And #74137 is not a dup of #57548. That was my mistake doing it. I might have mis read the description. I will reopen that and supporting that will also solve @oliversalzburg 's requirement. 

> If there was a way so I could achieve that the workspace recommendations would still be visible, that'd be nice to have though.
