### ISSUE TITLE
Powershell MFA popup is behind the VSCode window

### ISSUE THREAD

**Issue by jolauMSFT** [microsoft/vscode#100798]
Issue Type: <b>Bug</b>

With the powershell module installed and on an AAD account with MFA enforced (e.g. microsoft.com)
Execute: 
Connect-AzAccount
Either by itself or as part of a script.

Consistently the window for you to enter MFA pops up behind the VSCode window and is not visible unless you minimize VSCode in order to log in.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
remote-wsl|ms-|0.44.4
azurecli|ms-|0.5.0
powershell|ms-|2020.6.0

</details>

**Comment by dbaeumer** [comment]
@jolauMSFT how do you execute `Connect-AzAccount`

**Comment by jolauMSFT** [comment]
@dbaeumer . I open a .ps1 script that was created in Powershell ISE and then "Run without debugging".
It then executes in the Terminal > Powershell Integrated Console v2020.6.0

> =====> PowerShell Integrated Console v2020.6.0 <=====
> 
> PS > connect-azaccount

And the MFA prompt pops up behind the main VSCode window, so only visible if I minimize VSCode

**Comment by dbaeumer** [comment]
@Tyriar  Not sure if this is something that is under the control of the powershell extension or us.
