### ISSUE TITLE
Some message text is not easily readable

### ISSUE THREAD

**Issue by StingyJack** [microsoft/vscode#100711]
Issue Type: <b>Bug</b>

i published a powershell module to github, and a message showed up at the bottom of my screen saying "Would you like Code to " <had to screencap and zoom 200% to read this next part> " periodically run git fetch?". 

It says its coming from a builtin extension so I'm using the default issue reporter, but that doesnt let me choose Git as an extension. LMK if this needs to be reported elsewhere.

This is it as it displays
![image](https://user-images.githubusercontent.com/15381181/85237426-d24ee780-b3f4-11ea-8e6d-5de0764ea43b.png)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.55GB (4.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
vscode-solution-explorer|fer|0.3.10
beautify|Hoo|1.5.0
vscode-azureappservice|ms-|0.17.0
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
mssql|ms-|1.9.0
python|ms-|2020.6.89148
remote-wsl|ms-|0.44.4
azure-account|ms-|0.8.11
azurecli|ms-|0.5.0
powershell|ms-|2020.6.0
vs-keybindings|ms-|0.2.0
team|ms-|1.161.0
vscode-fileutils|sle|3.0.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
That hard-to-read text is a hyperlink. Which theme are you using?

**Comment by StingyJack** [comment]
@bpasero - it says it's a built in extension. Where to report built in extensions other than here?
![20200622_064907](https://user-images.githubusercontent.com/15381181/85279569-a4998b00-b454-11ea-8e56-efefa4dbbc94.jpg)

Also its rather rude and useless issue handling to slap a label on it and sick a bot on me without a single word of assistance. Microsoft could go a long way toward repairing broken community relationships by teaching engineers to respond electronically like they should if they were verbalizing with another human being standing in front of them asking for help. 

@gjsjohnmurray - I didnt realize I had one installed. It's "winter is coming". I'll try disabling it and see if I can get that prompt to pop up again. Thanks!

**Comment by bpasero** [comment]
@StingyJack can you let me know what theme you have enabled in VSCode? Looking at the screenshot I assumed it is not one of our built in ones, but sorry if that was the wrong assumption.

**Comment by StingyJack** [comment]
@bpasero  - the original screenshot says "Source: Git (Extension)" and that extension says its Built In. 
Git is not selectable in the "Report an issue" dialog in vscode.

See above for theme.

**Comment by bpasero** [comment]
@StingyJack the notification originates from the Git extension but is not the reason the link is not readable. The link color must be coming from a theme you have selected, it does not look like our standard theme.
