### ISSUE TITLE
Optout: editor.semanticTokenColorCustomizations

### ISSUE THREAD

**Issue by User7711** [microsoft/vscode#100737]
When registering a DocumentSemanticTokensProvider it does not work. It only works if you explicitly enable this feature (it defaults to false: "opt-in") in the settings.

    "editor.semanticTokenColorCustomizations": {
        "enabled": true,
    }

Is there a specific reason for configuring it like this? Isn't optout (default set to true) a better approach for a setting like this.!? Because now if you provide this feature in an extension, it seems that every user must enable it first before it starts to work.

From Example: https://github.com/Microsoft/vscode-extension-samples/tree/master/semantic-tokens-sample

**Comment by aeschli** [comment]
When we enabled semantic highlighting for all in 1.43, we got string pushback from users and theme authors. So 1.43.1 only the built-in themes and custom themes that opt-in get semantic highlighting.

We've been working with the theme authors of the top themes to adopt semantic highlighting.

Can you describe your use case? Are you implementing semantic highlighting for a language that depends on semantic highlighting?

**Comment by User7711** [comment]
Thanks for the reply,

I'm creating a language extension that can do most common language tasks. Like IntelliSense & goto definition. Because I've already got all the Tokens of the source code - and with that all the definitions of the identifiers - it would be nice to also add Semantic Highlighting for defined classes, function parameters and other things.

Perhaps there are other ways of doing this? Can I alter the tmLanguage data on runtime perhaps? This will not give me local things like function parameters, but it will possibly give me global things like classes and function, etc.

Or perhaps any other workaround/solution.!?

**Comment by aeschli** [comment]
No, tmLanguage are static regex rules. Semantic highlighting is the right thing.
We are thinking about a way for languages to defined what the default for semantic highlighting is

**Comment by User7711** [comment]
Well, you can make a "generic" tokenizer and use json + regex to specify what everything. Or even better, use [BNF](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form) to figure out what everything is. Than you can just add the BNF grammar of any language and use it for Semantic features and even syntax/bug checking.

That would be an intrestring feature and fun programming work. However, it will take some time to complete. And debugging might be a pain.

So please let me know when you guys finish it! :D

For now I wil just add the Semantic Highlighting as optional feature.

Thanks for helping me out!
