### ISSUE TITLE
Extension API - How to determine debug state

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode#10077]
Dear vscode-team

I've got another question for you guys.
Is there any possibility to determine if VSCode is actually debugging?

My idea is to do something like this:

If a file changes, AND vscode is in debug mode (with `f5`), I want to run a certain command.

As I'm aware of, one can define a `when` on a key binding but is this possible from the extension API?

Cheers
Chris

**Comment by isidorn** [comment]
Yes there is a `"when": "inDebugMode"`, however not sure if we surface `when` in our api or if we want to add that.
Thus forwarding to @jrieken

**Comment by buehler** [comment]
It would be a nice feature actually (if it's not already possible)
So one could add special behavior for certain actions.

Like, if my file changes and vscode is actually in debugging mode (or in a debugging session) I'd run the command `workspace.debug.restart` (just as an example, I know the actual command does have another name)

**Comment by jrieken** [comment]
The `when` clause is not the right vehicle for this because it's just a condition under which commands are constraint by default. However, a user can always change things like a keybinding and skip/change the `when` clause as she/he likes.

What you want is debugging API like a `vscode.debugger`-namespace which have we not yet planned to do.

**Comment by buehler** [comment]
Yeah such a namespace would be nice to determine the state of vscode.

Something like `vscode.debugger.isDebugging()` maybe?

I would like to suggest this feature then 😄
IMO it could be very beneficial for some extensions to add features and / or behaviors based on the state of VSCode.

For now, I just can execute the command for restarting the debugger and see if there's an error.

**Comment by jrieken** [comment]
There is now debug api that allows you to do this. Please try it out and provide in detail feedback. Thanks
