### ISSUE TITLE
IDE crashes

### ISSUE THREAD

**Issue by coRz** [microsoft/vscode#100747]
Uppon running regular yarn build command ide crashes after getting freeze while building the project.
Reloads the ide after crash, same issue over again happened after todays update.
Thanks

**Comment by alexr00** [comment]
@coRz  can you provide a repository we can clone to reproduce the issue with?
How are you running the build command?

**Comment by coRz** [comment]
Hey sorry I cannot reproduce it, after reboot the issue was gone.
If I will experience it again will report.
Thank you.
