### ISSUE TITLE
Shouldn't the 1.46.1 “May 2019 Recovery” release be named “May 2020 Recovery”?

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [microsoft/vscode#100743]
- VSCode Version: N/A
- OS Version: N/A

Steps to Reproduce:

1. Check out <https://github.com/microsoft/vscode/releases>

![](https://user-images.githubusercontent.com/13408130/85269598-b017a100-b4aa-11ea-89d2-d3bd84f4ddb7.png)

![](https://user-images.githubusercontent.com/13408130/85269610-b443be80-b4aa-11ea-91bc-a9f5f713b581.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Pinging @connor4312
