### ISSUE TITLE
The touchpad cannot drag the page down

### ISSUE THREAD

**Issue by Hilf20181024** [microsoft/vscode#100705]
Issue Type: <b>Feature Request</b>

English is not good, but the title says it all

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

**Comment by eamodio** [comment]
You can't scroll with the touchpad? Is this new?

**Comment by Hilf20181024** [comment]
> You can't scroll with the touchpad? Is this new?

No, but can do it in other software, to be precise can't scroll with two fingers, to be exact.

**Comment by Hilf20181024** [comment]
> 您无法使用触摸板滚动吗？这是新的吗？
I've found the problem.
If I run VSCode as an administrator, then scrolling does not work.
Scrolling does work If I run VSCode just as it is.
