### ISSUE TITLE
Prompt Windows users to update to Git 2.27 from 2.25-2.26

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#100701]
We've seen lots of issues with 2.25-2.26, eg https://github.com/microsoft/vscode/issues/98967

**Comment by dbaeumer** [comment]
Saw it today :-)

**Comment by JasonGore** [comment]
Is there any way to disable this notification? I've been getting it for days now on every window I open. There are also [issues preventing us from using git 2.27](https://github.com/git-for-windows/git/issues/2732). Linking to actual issues on a forced notification like this would also help balance the notification out when there are issues preventing users from upgrading.

**Comment by joaomoreno** [comment]
We will push a _Do not show again_ button to it.
