### ISSUE TITLE
Copying page files

### ISSUE THREAD

**Issue by protegesolutions** [microsoft/vscode#100775]
Issue Type: <b>Feature Request</b>

I select a page file, right-click and click Copy.

Then what??

I deselect the copied page and right-click and click paste and nothing happens.

Fundamental, intuitive contextual functionality missing.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:44.937Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by isidorn** [comment]
I do not know what are page files?
Explorer supportes copy and paste of all files.

**Comment by protegesolutions** [comment]
A "page file" as I put it is any file that appears in the left-hand Explorer pane. My issue is that you cannot perform a copy/paste in one of the usual manners using a mouse. Please read the description of the issue.

**Comment by isidorn** [comment]
Yeah that works. Please use the context menu as the screen shot shows
You can also use Cmd + C

<img width="500" alt="Screenshot 2020-06-23 at 17 39 51" src="https://user-images.githubusercontent.com/1926584/85424736-947acc00-b578-11ea-8b3f-7469efbdff4d.png">

**Comment by protegesolutions** [comment]
I don't think you're taking the time to actually read what I've posted: where is the **Paste** option in your image?
