### ISSUE TITLE
Renaming page files

### ISSUE THREAD

**Issue by protegesolutions** [microsoft/vscode#100776]
Issue Type: <b>Feature Request</b>

I select a page file, then click again which I expect to enter text edit mode to rename the file but that's not what happens.

Fundamental, intuitive contextual functionality missing.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:44.937Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by dbaeumer** [comment]
Assuming you are talking about file rename in the explorer

**Comment by protegesolutions** [comment]
Yes.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/100775

**Comment by protegesolutions** [comment]
It's not a dupe; this is about **renaming**, the other **copying**.
