### ISSUE TITLE
Quickopen not finding all files

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1007]
quickopen, vscode repo, search for some files in quick open does not always give results even though they exist.
Searching for pluginHostMain.ts produces no results for me. Once I open that file manually it starts appearing in quick open.

I see this on OS X el capitan with latest code. Started happening 3 days ago - about the time you messed with that complex promise chain

**Comment by bpasero** [comment]
@isidorn whats your commit id you are on?

**Comment by isidorn** [comment]
Ok updated to latest and I no longer see it, it seems. I will reopen if I see it again

**Comment by bpasero** [comment]
@isidorn nice, there was a bugfix for this yesterday, but now it should all be ok!
