### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by Goutampatidar** [microsoft/vscode#100772]
We have written the needed data into yo
Issue Type: <b>Performance Issue</b>

vs code notworking properly. 
first of all extenstention bar or extenstion view bar is not working,it show empty .
secondly, compiler is also not working (i.e code runner) .No any program is being compliled yet.
this issue is from the first day when i had install  it and i had also complained about it before on twitter.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (1.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    53	 12944	code main
    0	   194	  4644	   gpu-process
    0	   143	  8196	   window (height of tree.cpp - couresera - Visual Studio Code)
    0	     3	  1048	     console-window-host (Windows internal process)
    0	    66	  1944	     extensionHost
    0	    20	  2884	       c:\Users\hp\.vscode\extensions\ms-vscode.cpptools-0.28.3\bin\cpptools.exe
    0	    27	  8724	         "c:\Users\hp\.vscode\extensions\ms-vscode.cpptools-0.28.3/bin/cpptools-srv.exe" 2884 0
    0	     5	 11988	         console-window-host (Windows internal process)
    0	    10	  5896	     watcherService 
    0	     5	 13496	       console-window-host (Windows internal process)
    0	     2	  6796	     C:\Windows\System32\cmd.exe
    0	     6	 13744	     console-window-host (Windows internal process)
    0	     4	 15556	     C:\Windows\System32\cmd.exe
    0	    16	 13708	   utility
    1	    68	 13864	   window (Issue Reporter)
    0	    39	 15980	   shared-process
    0	     8	 16728	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (height of tree.cpp - couresera - Visual Studio Code)
|    Folder (couresera): 5 files
|      File types: cpp(3) json(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
c-cpp-compile-run|dan|1.0.11
code-runner|for|0.10.0
cpptools|ms-|0.28.3

</details>
ur clipboard because it was too large to send. Please paste.

**Comment by dbaeumer** [comment]
@Goutampatidar since the issue seems to be related to CPP development please start the problem tracking with the owner of the CPP extension you are using.
