### ISSUE TITLE
No insiders updates

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10073]
- VSCode Version: 1.4.0-insiders (e3758d2cdaae78082a08a45ae28ea1bed5f47e8c)
- OS Version: OSX 10.11.6

Hi awesome VSCode team,

Best part of starting new day was to have a fresh coffee and fresh update of insiders.
For some reason updates of my insiders stopped - is there some problem with auto builds or is it the problem on my side. My version is e3758d2cdaae78082a08a45ae28ea1bed5f47e8c and that commit was from Jul 29.
When I check for updates I get:
![image](https://cloud.githubusercontent.com/assets/1723815/17363748/53f229dc-594a-11e6-9dda-e13aee46f058.png)

**Comment by aeschli** [comment]
During the [end game](https://github.com/Microsoft/vscode/wiki/Development-Process#end-game), and until the new build is declared, the insider build represents the release candidate. As we stabelize, there will be only few fixes, and the insider build might not change for a few days. Once the final build is declared, the insider build will return to be a daily build representing the latest development.
