### ISSUE TITLE
The bracket coloriser extension can cause VS Code to become unresponsive

### ISSUE THREAD

**Issue by Wintaru** [microsoft/vscode#100779]
- VSCode Version: 1.46.0
- OS Version: Linux x64 4.9.0-12-amd64

Steps to Reproduce:

1. Use VS Code for a while
2. Eventually becomes unresponsive, must close the window and reopen.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Wintaru** [comment]
By unresponsive I mean that scrolling and clicking on editors no longer works, or takes many seconds before they complete and it immediately hangs again. I have to kill the window every few hours now. No spike on CPU or RAM usage either, it's really bizarre.

I have disabled all extensions and it still happens. I ran code --verbose and this is the last bit of the log before I had to kill it. I can reproduce this regularly. This didn't happen in the previous release I was running. I will see if our sysadmin will install the insiders build and confirm it still happens there.

[unresponsive.log](https://github.com/microsoft/vscode/files/4814660/unresponsive.log)

**Comment by borisovg** [comment]
I am also seeing something similar (Debian Sid, codium 1.46.1) The editor window locks up frequently for several seconds after some time using the app, but in my case it will recover.

Looking at the process explorer the only thing that is using CPU at the time is "window" - at 25% which suggests Node.js garbage collector? (I'm on an 8-core system so it could be just pegging one proc).

The window process is using suspiciously a lot of memory for a single tab - memory leak? This never happened before I upgraded to 1.46.

![ss](https://user-images.githubusercontent.com/3171327/85560296-6e116b00-b622-11ea-977a-1e2d14b6896b.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by deepak1556** [comment]
@Wintaru can you attach the full verbose log, the attached log only contains the app exit state. Also try to take a performance profile of the editor https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by Wintaru** [comment]
> @Wintaru can you attach the full verbose log, the attached log only contains the app exit state. Also try to take a performance profile of the editor https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

I'm not sure I can, there is a lot of personal information about my machine including source tree file paths/names/etc of our source code. 

That being said, I have been using 1.46.1 for a while now without seeing the issue so maybe it's resolved? I'm going to use it the rest of the day today and see if I get the freeze, if not I'll close the bug.

**Comment by Wintaru** [comment]
Spoke too soon, it just froze again. I will have to spend time to get my setup going with the insiders build, I'm not sure why none of my settings port over to it...

**Comment by Wintaru** [comment]
> @Wintaru can you attach the full verbose log, the attached log only contains the app exit state. Also try to take a performance profile of the editor https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

There were two processes:
![image](https://user-images.githubusercontent.com/1441142/86004825-775f5680-b9d9-11ea-8ca4-2a39680896de.png)

The file that ends with Profile1 is the first one, the file that ends with Profile2 is the second one.

Once it started freezing again I recorded both for about 30 seconds. I've noticed that it seems to only happen when scrolling (I tried editing the smooth scrolling settings that are new in 1.46 for both on and off but it happens either way)

**Comment by deepak1556** [comment]
Thanks for the profile, the first profile shows a lot of time spent in `deltaDecorations` looping in @jrieken for core related perf.

**Comment by jrieken** [comment]
<img width="1098" alt="Screenshot 2020-07-06 at 08 45 16" src="https://user-images.githubusercontent.com/1794099/86563654-0aae0400-bf65-11ea-9f4b-923f3c443adb.png">

This the `setDecorations`-api. You must be using some kind of extension that adds a really large amount of editor decorations, like bracket colorizer or semantic tokens that don't use the new API. Please share your list of extensions. 

Adding @alexdima to safe-guard this API

**Comment by alexdima** [comment]
@Wintaru What extensions do you have installed? One of your extension is flooding our vscode API with text editor decorations.

**Comment by Wintaru** [comment]
I swear I tried this with extensions disabled and still got it, but I didn't run the profile thing with them off. I do have a bracket colorizer, I will try this all again with extensions disabled tomorrow when I'm back in the office to make sure. If it's just that extension that would be a relief (and I'd be embarrassed about wasting people's time).

**Comment by alexdima** [comment]
Yeah, no worries. I'm pretty sure it is the bracket coloriser extension, it has well known performance issues that cause stutters and freezes.

**Comment by Wintaru** [comment]
Ok, I have C/C++, Doxygen Documentation Generator, Git History, GitLens, JSON Pretty Printer, Rainbow Brackets, and Tcl installed. I will run today with Rainbow Brackets disabled and report back at the end of the day, that would be enough to prove it because it was happening several times a day.

**Comment by Wintaru** [comment]
No freezes at all today, this is the extension I disabled.

https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets

Thanks for the help, do you need me to close it?

**Comment by borisovg** [comment]
I was able to catch a hang of several seconds that shows up as "Recalculate Style" - let me know if I should open a separate issue.

[Profile-20200711T131157.json.gz](https://github.com/microsoft/vscode/files/4906728/Profile-20200711T131157.json.gz)

![Profile-20200711T131157-fs8](https://user-images.githubusercontent.com/3171327/87223911-bb0e7480-c378-11ea-88e4-7d1dc6875103.png)

**Comment by alexdima** [comment]
VS Code supports in the meantime bracket coloring out of the box --> https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization
