### ISSUE TITLE
Add setting to control font weight in debug output

### ISSUE THREAD

**Issue by cnshenj** [microsoft/vscode#100778]
#1957 is fixed by adding `debug.console.fontFamily` and `debug.console.fontSize`. Compared to editor and terminal font settings, `debug.console.fontWeight` is missing. Please add this setting so we can make the font rendering consistent across editor, terminal, and debug output.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
