### ISSUE TITLE
markdown preview ignores custom css on start

### ISSUE THREAD

**Issue by gmccullo** [microsoft/vscode#100727]
- VSCode Version: 1.46.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a custom CSS for a workspace. 
2. Create a markdown document. 
3. Open preview to the side. 
4. Close VS Code. 
5. Start VS Code on the same workspace.

Expected: Markdown preview is shown with custom CSS styling.

Actual: Preview is shown with default styling own. Custom styling is ignored.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
>     1. Create a custom CSS for a workspace.

Are you using an extension to do this?

**Comment by gmccullo** [comment]
> 
> 
> > ```
> > 1. Create a custom CSS for a workspace.
> > ```
> 
> Are you using an extension to do this?

Not to create the file. It's just a text file in the root of the workspace called "my.css". And then the workspace settings.json file looks like this:
```
{
    "markdown.styles": [
        "my.css"
	],
	"editor.renderWhitespace": "all",
}
```
As far as I can tell extensions don't make any difference. For example, if I reload with extensions disabled, I still don't see my custom styles in effect _on load_. But if I then close the preview window and reopen it ("markdown: open preview to the side"), then the custom styles _are_ in effect.

**Comment by mjbvz** [comment]
I can't reproduce this in current VS Code builds. Here's the preview after a reload for example:

<img width="1226" alt="Screen Shot 2020-09-28 at 4 02 29 PM" src="https://user-images.githubusercontent.com/12821956/94494431-0bd98080-01a4-11eb-9fd1-e90dd4aa1f72.png">


If it does, please share exact steps to reproduce the problem
