### ISSUE TITLE
Random warning "Cannot Rename this element" 

### ISSUE THREAD

**Issue by srk1195** [microsoft/vscode#100769]
Issue Type: <b>Bug</b>

1. Open VScode for any JS files.
2. Start the webserver
3. Try to write a piece of code.

Expected: No random warnings of "Cannot rename this element"
Actual: Random warnings of "cannot rename this element".

Note: Idk wether it is a bug or not. But, it is so annoying as it is not allowing me to code peacefully. I also use codesandbox.io also, and issue also seen over there.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.87GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
snapshot-tools|asv|0.4.0
vscode-opennewinstance|chr|0.0.7
bracket-pair-colorizer-2|Coe|0.1.4
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
prettier-vscode|esb|5.1.0
auto-rename-tag|for|0.1.3
Python-autopep8|him|1.0.2
rest-client|hum|0.24.1
vscode-language-babel|mgm|0.0.27
python|ms-|2020.6.89148
env-cmd-file-syntax|Nix|0.1.2
material-icon-theme|PKi|4.2.0
LiveServer|rit|5.6.1
snipsnap-vscode|sni|1.0.3
jest-snapshot-language-support|tle|1.1.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Random behaviour is hard to implement in software.

Please re-test with all you extensions disabled (look for the `Reload With All Extensions Disabled` command in the palette).

If your problem still occurs please provide the simplest reproducible steps you can devise. Screenshots and/or animated GIFs get bonus points.

**Comment by srk1195** [comment]
The issue is reproducing very frequently even after all the extensions are disabled.

![random_rename](https://user-images.githubusercontent.com/18619508/85360188-0978e200-b536-11ea-8fc5-b9f1f65603b8.gif)

**Comment by mjbvz** [comment]
Please provide steps to reproduce this issue along with example code (as text)

**Comment by srk1195** [comment]
it is an OS issue. Thanks for support
