### ISSUE TITLE
The terminal process terminated with exit code: 3221225477

### ISSUE THREAD

**Issue by xlambda** [microsoft/vscode#100715]
- VSCode Version: 1.46.1 (user setup)
- OS Version: Windows_NT x64 10.0.17763
- Electron: 7.3.1
- Chrome: 78.0.3904.130
- Node.js: 12.8.1

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
See https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch for steps on how to investigate what's going on.
