### ISSUE TITLE
"Go to Symbol": inconsistent escape behavior

### ISSUE THREAD

**Issue by zoharl3** [microsoft/vscode#100795]
- VSCode Version: 1.43.2
- OS Version: win10

Steps to Reproduce:

1. "Go to Symbol in File"
2. Type a name of a function.
3. When it finds the function, press escape.
4. Instead of staying on the function, it jumps back: inconsistent behavior with any other find in the world.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
> 1. "Go to Symbol in File"

I am using the latest release (1.46.1) and this command is called `Go to Symbol in Editor..." (Ctrl+Shift+O is the shortcut on Windows)
> 
> 2. Type a name of a function.
> 
> 3. When it finds the function, press escape.

Why `Escape`? Why not `Enter`?
> 
> 4. Instead of staying on the function, it jumps back: inconsistent behavior with any other find in the world.

By pressing `Escape` you are indicating you changed your mind about wanting to go to the symbol.

**Comment by zoharl3** [comment]
It's a type of a find/search. The convention is that 'enter' gets you to the next occurrence (usually, you have a dialog, whether it's an incremental search or otherwise).

Moreover, in general, when you only browse the code, it's good practice to use keys that can't make changes, such as arrows and esc.

I'm working with a lot of editors, this is my habit, and I think it's a good practice.
