### ISSUE TITLE
Status bar entries should use border for focus

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#100735]
* see attached gif
* move to the lower right corner of status bar
* click
* :bug: status bar gets a focus border

![Jun-22-2020 10-01-33](https://user-images.githubusercontent.com/1794099/85263400-68bfef00-b46f-11ea-8f7f-35a450fa4201.gif)

**Comment by isidorn** [comment]
@jrieken yes we now always render a status bar border when the status bar gets focus via keyboard or on click.
Reason being: status bar is now accessible and navigable so we want the focus to be visible.

What I do not like is that the focus is not fully around it and is missing in the top border.

However your issue might be different: when resizing the whole window you do not want the click to be interpreteed as a status bar click. Did I understand this correctly?
@bpasero is there way for us to prevent the "resize" click going through to the status bar

**Comment by jrieken** [comment]
> when resizing the whole window you do not want the click to be interpreteed as a status bar click. Did I understand this correctly?

Well, that's how I discovered this issue. However the issue is that get a focus border for the status bar but pressing tab/shift+tab or arrow-left/right doesn't focus status bar elements. So what's the focus for?

**Comment by isidorn** [comment]
@jrieken arrow -left/right focuses the status bar elements correctly for me. And that is what the focus is rendered for.
Please note that for focus we are using a hover background color - which might be the reason why you missed this?

**Comment by isidorn** [comment]
Also if you switch to High Contrast theme you will see the border for all entries.
We can change it that we render the border in all themes.

**Comment by jrieken** [comment]
Yeah, my theme has no hover background color

**Comment by isidorn** [comment]
Ok, so renaming this issue to "Use borders for status bar items focus"
We had a similar discussion here https://github.com/microsoft/vscode/issues/99350
