### ISSUE TITLE
"Find in Folder" \ add safety to Replace All (in a file)

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#100702]
The Replace All (in a file) buttons are insanely located right next to the Dismiss ones, the changes can't be reverted if the file wasn't open, and it doesn't have confirmation dialog, i got relatively low damage, but that wasn't more than luck .

Add at least the confirmation dialog, and better implement this https://github.com/Microsoft/vscode/issues/47783 .

**Comment by irvnriir** [comment]
Its so simple to add, but you prefer everyone to risk their work ..

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
