### ISSUE TITLE
Make right-click Find In Folder work for "root" / workspace folder - why is this treated differently?

### ISSUE THREAD

**Issue by therobyouknow** [microsoft/vscode#100719]
Please make right-click Find In Folder work for "root" / workspace folder - why is this treated differently?

I asked for this ages ago I think and it's still not there!

Keep up the fantastic work otherwise.

**Comment by gjsjohnmurray** [comment]
> Please make right-click Find In Folder work for "root" / workspace folder - why is this treated differently?

Please clarify what you mean. Maybe paste screenshot(s).

**Comment by eamodio** [comment]
Please provide more details -- Find In Folder from a root in a multi-root workspace works for me.

**Comment by therobyouknow** [comment]
right click on a folder - find in folders option available

![image](https://user-images.githubusercontent.com/1080646/85755099-8c9c6280-b705-11ea-8b21-74c121e97024.png)

right click on a top-level-folder (workspace folder) - no find in folders option available

![image](https://user-images.githubusercontent.com/1080646/85755194-a178f600-b705-11ea-8a66-9d0f81babb0f.png)

**Comment by gjsjohnmurray** [comment]
> right click on a top-level-folder (workspace folder) - no find in folders option available

Any reason not to just left-click here?

![image](https://user-images.githubusercontent.com/6726799/85767673-2701a380-b710-11ea-85f2-90121b2b386f.png)

**Comment by therobyouknow** [comment]
@gjsjohnmurray actually, yes - consistency: my expectation is to get the same menu on that top level folder. After all, it is actually a file system folder in my source tree just like the other folders.

But yes, thank you for advising on the search symbol in plain sight. I can use that. I'd have to type in the name of the top level folder of course which leads me back to the first point - why not make that top level have the search option.

But I can live with it, now the obvious alternative option has been pointed out to me. Thank you!

**Comment by roblourens** [comment]
You are clicking on the name of the folder that is open, and that folder will be searched by default without typing anything in "files to include". The inconsistency just comes from the fact that we only add that option to folders in the file explorer, and the view you are looking at is not part of the file explorer.

I think @gjsjohnmurray 's answer is the correct one, thank you for jumping in!

**Comment by therobyouknow** [comment]
thank you @roblourens
