### ISSUE TITLE
Add line numbers to search results

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode#10085]
- VSCode Version: 1.3.1
- OS Version: 10.11.5

Steps to Reproduce:
1. Do a search
2. Results are shown

Would be nice to see the line numbers. For example if you search for Bob you get the line where Bob exists shown but it would be nice if the line number was shown as a prefix.

**Comment by mat-m** [comment]
@bpasero : I second this , but on the search panel. Should I open another issue ?

**Comment by prufrock123** [comment]
@sandy081 & @bpasero -  I also think this would be great to have.

**Comment by gianlucaborello** [comment]
I probably spend 30% of my vscode time navigating through search results like a maniac, so having line numbers would be a terrific productivity improvement, especially now that we have `"search.location": "panel"`. Thanks!

**Comment by onqtam** [comment]
just found this:

https://github.com/Microsoft/vscode/commit/cc5e2b41c3add18a31e87f84b5d6162566a38d6e

trying to test it out now...

**Comment by usernamehw** [comment]
`"search.showLineNumbers": true,`

@roblourens Should this be closed?

**Comment by roblourens** [comment]
Yes! I didn't know this dupe existed.
