### ISSUE TITLE
${workspaceFolder} drive letter normalization does not work well with yarn workspaces

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#100875]
- VSCode Version: latest
- OS Version: Windows 10

I have this launch config:
```
{
    "name": "Backend",
    "type": "pwa-node",
    "request": "launch",
    "program": "${workspaceFolder}/backend/index",
    "sourceMaps": false
}
```

Attaching works fine.

However, nodejs will require `c:/.../backend/index` instead of `C:/.../backend/index`.
This is very problematic in yarn workspaces that uses symlinks to create references between packages.

Their symlinks are not normalized to lowercase. E.g. `require("shared")` will resolve to `C:/.../shared/index`, regardless of whether required from `c:/.../index` or `C:/.../index`.

If `shared` requires a hoisted (non symlinked) package `foo`, it will load `C:/.../foo`, whereas `backend` would load `c:/.../foo`.

This would result in `foo` being load twice, since the module cache in NodeJS is case-sensitive.
This is observable behaviour and will lead to failing `instanceof` checks.

When running with `nodejs backend/index`, this problem does not occur, since it does not normalize the drive letter and uses the same casing as the symlink.

It was very time consuming to find this bug (it was a secondary bug and the reason for the failure of instanceof was not obvious). Also, when using typescript and sourcemaps, the casing problem is not apparent (because VS Code treats `C:/.../index.ts` and `c:/.../index.ts` the same).
Please do something that other users don't run into this.

Also, I'm unsure how to fix this even after figuring out every detail.

**Comment by isidorn** [comment]
@hediet yes, by design we are normalizing drive letters. More about why we do this can be found in this and the related issues https://github.com/microsoft/vscode/issues/43959

I am sorry to hear that in this case it does not really work. 
We can leave this one open for now so users see this. And a potential solution would be to introduce new variables that do not do normalization. Though that is not on the immediate plan.

**Comment by hediet** [comment]
Thanks for your reply and the link ;)
Seems like case-insensitive file names on Windows are the real fun :D

This is my quick fix for now inside my index file:
```
const Module = require("module");
const req = Module._resolveFilename;
Module._resolveFilename = function(...args: any[]) {
	const result = req.apply(this, args);
	return result.toLowerCase();
};
```
I don't now what this could break again though.
