### ISSUE TITLE
Cannot 'Reopen With..' settings editor with text editor

### ISSUE THREAD

**Issue by croddin** [microsoft/vscode#100885]
Issue Type: <b>Bug</b>

With Hex editor (or probably any other editor extension) installed. Otherwise 'Reopen With...' won't appear.

1. Click on File > Preferences > Settings
2. Click on ... > Show modified settings
3. Click on ... > Reopen With... then select Text Editor
Expected: The User/settings.json is opened in the text editor
Actual: The error message: 
    Unable to open 'settingseditor': Unable to resolve filesystem provider with relative file path 'vscode-settings:settingseditor'.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
I guess it shows up because it is registered for `"filenamePattern": "*"`, do you think that can be scoped to `file://` or does it not match URIs @lramos15 @mjbvz?

**Comment by croddin** [comment]
The "Reopen With... " menu does not show up now in the latest release.
