### ISSUE TITLE
Breakpoints not remembered on git branch change

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#100864]
Issue Type: <b>Bug</b>

When switching from one git branch and back, breakpoints and their line numbers are not remembered. Sometimes breakpoints disappear entirely and other times they are found to have moved magically from their original line to some other completely different line some hundred or so lines down the file. This makes it tedious to debug files in multiple branches when you're trying to control breakpoints all the time.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by weinand** [comment]
VS Code persists breakpoints in private workspace storage (not in the repo) and knows nothing about branches and SCM in general.

**Comment by ariffjeff** [comment]
Do you know if there is an easy workaround if no fix/change is possible?

**Comment by isidorn** [comment]
@ariffjeff there is no easy workaround sorry.
Currently VS Code removes breakpoint when it detects a file has been deleted.
For now we can leave this open as a feature request and we can think about it in the future to potentialy add this.

**Comment by ariffjeff** [comment]
Thanks. I'll reference this issue since it's similar: #100860
