### ISSUE TITLE
Paste works but copy doesn't, on a VirtualBox Ubuntu guest

### ISSUE THREAD

**Issue by pralhadsapre** [microsoft/vscode#100801]
I am running VS Code inside a VirtualBox VM on a host macOS machine. My clipboard is set to be bi-directional so that I can copy paste code to slack or from it, which runs on my host macOS.

What I have observed, is that I can't copy from VS Code to my host machine. So what I often end up doing is copy from VS Code to another editor in the Ubuntu VM, and then copying it out from there to my host macOS. This is very weird and inefficient.

- VSCode Version: 1.46.1
- OS Version: 16.04.1-Ubuntu
- VirtualBox Version: 6.0.20

On the flip side, I can perfectly paste into VS Code any text I copied from my host or guest OS.

I tried to install the latest version of VirtualBox, it's guest additions and also VS Code. What is funny is that the VSCode version number pops up in a new window, and I could perfectly copy from there!

Steps to Reproduce:

1. Copy text from VS Code editor
2. Try to paste it in the host macOS on any editor

I have a feeling that either:

- VS Code editor page isn't able to copy stuff to the shared clipboard, but rather just the guest OS clipboard or
- There is some keybinding which is interfering with Ctrl + C. But I am not strongly inclined to believe that this wouldn't be the case.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Can you try turn off `editor.copyWithSyntaxHighlighting` and see if you can still reproduce?

**Comment by pralhadsapre** [comment]
Ohh, that actually solves it! Thanks, but I am curious if this is a problem shouldn't the default be off?

**Comment by rebornix** [comment]
It looks like a bug with how virtual machines' copy/paste works as what we do when it's turned on is we put both text and html into the clipboard, maybe it fails in this scenario.

It's a really good catch and we might want to document it better, thanks @pralhadsapre !
