### ISSUE TITLE
Show message when trying to assign an existing key chord as keybinding

### ISSUE THREAD

**Issue by NewtMa** [microsoft/vscode#100899]
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-59-generic

Steps to Reproduce:

1.set "ctrl + k" for "column selection mode";
2.close keyboard shortcuts window;
3.cannot using "ctrl + k ctrl + s" to invoke keyboard shortcuts window and there was no warning to inform possible shortcuts mask;

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/80181
