### ISSUE TITLE
Tab key in text editor does not indent text but cycles focus through bottom panel

### ISSUE THREAD

**Issue by globules-io** [microsoft/vscode#100886]
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:
1- Work
2- It just happens
Cannot tell exact path/worflow. Gone after restarting VSCODE. Happens randomly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Do you have "Tab moves focus" in status bar when it happens?

Ctrl+M to switch between modes for Tab behavior

**Comment by globules-io** [comment]
Thanks, my bad, I must have hit CTRL+m by mistake, closing
