### ISSUE TITLE
Insider version of vscode shows blank window

### ISSUE THREAD

**Issue by sweettyler** [microsoft/vscode#100889]
I reported the same issue in https://github.com/microsoft/vscode/issues/98354. The issue cured by itself for unknown reasons. Now it happens again.

Because vscode does not launch normally. So I can't copy/paste the information in "About". However, the issue is quite simple and you don't need more information:

1) if I use "https://az764295.vo.msecnd.net/insider/8cd3fe080bee38d28ba01d0d71713d6ec22b254e/code-insider-1592545553.tar.gz" (released last Friday), then everything works normally.

2) if I use "https://az764295.vo.msecnd.net/insider/0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69/code-insider-1592906035.tar.gz" (released today) then vscode only shows a blank window.

3) I don't know if the version released yesterday works or not as I didn't download it.

4) The following is from the version mentioned in 1):
=======================================================
Version: 1.47.0-insider
Commit: 8cd3fe080bee38d28ba01d0d71713d6ec22b254e
Date: 2020-06-19T05:31:16.748Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 3.10.0-693.17.1.el7.x86_64
=======================================================

5) Does this issue occur when all extensions are disabled?: Yes

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sweettyler** [comment]
Please see the snapshots of what I have after launching vscode.
![code_2](https://user-images.githubusercontent.com/49961658/85493737-0d8c1a80-b59d-11ea-9204-afff509f6811.png)
![code_1](https://user-images.githubusercontent.com/49961658/85493740-0e24b100-b59d-11ea-9cc1-b11517f6d6bb.png)

**Comment by deepak1556** [comment]
Thanks for creating the issue, merging this to https://github.com/microsoft/vscode/issues/100846. Please follow that issue for updates.
