### ISSUE TITLE
Create a file/folder from fuzzy search if it does not exist

### ISSUE THREAD

**Issue by ahkohd** [microsoft/vscode#100854]
Hi, great work going on here!

I want to make a feature request:
When I search for a file with `ctrl+p` and it does not exist,  VSCode should give me the option to create the file.

**Current behaviour:**
1. `Ctrl+p` opens a fuzzy search of the command palette.
2. I type `components/Hello.js`. (let's assume this file does not exist)
3. VSCode tells me "no matching result".
![image](https://user-images.githubusercontent.com/13041443/85417991-2dedb200-b568-11ea-84bf-307bc9556564.png)

**Requested feature:**
1. `Ctrl+p` opens a fuzzy search of the command palette.
2. I type `components/Hello.js`. (let's assume this file does not exist)
3. VSCode tells me "no matching result", but also give me a second option that says "create file".
4. Once I click the create file option, the file should be created `(at ${jsconfig.baseUrl}/components/Hello.js)`, then open the file.

Thanks!

**Comment by roblourens** [comment]
Interesting idea, thanks, but I think it's unlikely that people would use this in anything but a really shallow file structure.

**Comment by altosaar** [comment]
I actually second this - think it would be useful!

**Comment by moseslucas** [comment]
I'm actually looking for this kind of feature. Too bad it doesn't exist
