### ISSUE TITLE
Add an option to show output panel only if there is

### ISSUE THREAD

**Issue by sylveon** [Microsoft/vscode#10089]
- VSCode Version: 1.4.0-insider
- OS Version: Windows 10 build 14393

When building with tools unsupported by VS, such as `csc.exe`, I'd like to have the output panel to show only if there is.

Because `csc.exe` with the `/nologo` option makes no output if there is no error or warnings.

So if everything goes okay, this is what I see:
![capture](https://cloud.githubusercontent.com/assets/6440374/17376460/a2e55ecc-5983-11e6-9d83-86de5b960fb8.PNG)

I'd like to not see the output panel at all if everything is okay, and see it only if there is warning or errors, without having to create complex problem matchers.

So setting `showOutput` to `output`, for example, should produce that behavior.

**Comment by alexr00** [comment]
If you use tasks version 2.0.0, there is a property you can set on tasks to only show the task output (which actually occurs in the terminal) if there is an error running the task or if the task outputs errors.

    "presentation": {
				"reveal": "silent"
			},
