### ISSUE TITLE
Source Control has wrong casing

### ISSUE THREAD

**Issue by MasAngeles** [microsoft/vscode#100855]
Issue Type: <b>Bug</b>

1) Somehow have VSCode think your repository lives in c: drive instead of C: drive.
2) Attempt to stage something in the source control tab.
3) That's it. It throws an error then.

I've found that by using the same line manually, it still happens. But when I set the c: to C:, it works fine. No idea what happened. It hasn't always been like this. Only happened within the last couple of weeks.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (8.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
What version is your local Git installation? There have been several reports similar to yours that were solved by upgrading Git.

**Comment by joaomoreno** [comment]
Yes, check your Git version and make sure you update to 2.27.
