### ISSUE TITLE
Can I somehow start a new node process running a script in a createTerminal created terminal?

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#100891]
I'd like to open a new terminal with `vscode.window.createTerminal` that runs a custom javascript file that I ship with my extension. Ideally I would not depend on the user having installed node, but instead just use the node that is included with any VS Code installation to run this script. Can that somehow be done?

I think essentially I'm trying to do something like `child_process.fork`, but have that child process run inside a VS Code terminal.

I tried various things, but am stuck. `code.exe` seems the only binary that ships with VS Code, so I guess if I wanted to start a new node process I would somehow have to start `code.exe`, but pass some command line args instructing it to not show the UI but instead just run a javascript file?

**Comment by davidanthoff** [comment]
Or is the (kind of) simple answer to just use `child_process.fork`, and then somehow wire that process up with a terminal via `ExtensionTerminalOptions`?

**Comment by Tyriar** [comment]
> but instead just use the node that is included with any VS Code installation to run this script.

This is certainly possible but I wouldn't recommend it as how running node inside code could change. 

> Or is the (kind of) simple answer to just use child_process.fork, and then somehow wire that process up with a terminal via ExtensionTerminalOptions?

This seems like the simple option, it won't be interactive but you'll have control over all I/O (unlike if you run a regular process in the terminal).
