### ISSUE TITLE
vscode API - workspace openTextDocument is flaky

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#100842]
```
Failing
  1) vscode API - workspace openTextDocument:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: 45 == 46
      + expected - actual

      -45
      +46
      
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/workspace.test.ts:68:10)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=79566&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=f58c00c4-bf13-5e9c-4e42-b9695c0a283b

I have seen this failure twice already today

**Comment by jrieken** [comment]
Fishy... I have already pushed changes that this is a random file. So unless there is a conflict with random names there is something wrong with opening files.

**Comment by bpasero** [comment]
@jrieken how can there be 45 documents open when the tests run, are we not always ensuring that all documents are closed before a test runs?

**Comment by jrieken** [comment]
no, we only close editors but documents that extension have opened are kept for a while (3min or max combined size).

**Comment by jrieken** [comment]
Optimistically closing after https://github.com/microsoft/vscode/commit/ef9a24f0219ddb7676a5d47ff3d9a0a931464097
