### ISSUE TITLE
Search dialog should keep a history of searches

### ISSUE THREAD

**Issue by darkguy2008** [Microsoft/vscode#10088]
- VSCode Version: 1.3.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Go to the search dialog
2. Type something and search
3. Type something else and search
4. Try to type the first letters of the first thing you searched for

What is expected to happen?:

The text box should be a dropdown instead just like in VS2015's search box, or at least do some autocompletion according to your previous searches.

**Comment by glen-84** [comment]
Related to #5508.

**Comment by sandy081** [comment]
duplicates #5508
