### ISSUE TITLE
Submenu at wrong position when sider bar is at right side

### ISSUE THREAD

**Issue by yume-chan** [microsoft/vscode#100851]
Issue Type: <b>Bug</b>

Testing #100848

If the side bar is at right side, the `Extensions -> View` submenu appears at wrong position.

![image](https://user-images.githubusercontent.com/1330321/85414352-9061a500-b59e-11ea-949c-acc2fdbfb03e.png)

VS Code version: Code - Insiders 1.47.0-insider (0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69, 2020-06-23T09:03:35.861Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (5.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
flow-for-vscode|flo|1.5.0
rest-client|hum|0.24.1
search-node-modules|jas|1.3.0
tabsanity|jed|0.0.11
vscode-language-pack-zh-hans|MS-|1.46.3
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
hexeditor|ms-|1.0.1
powershell-preview|ms-|2020.6.1
typescript-javascript-grammar|ms-|0.0.53
vscode-js-profile-table|ms-|0.0.5
vscode-typescript-next|ms-|4.0.20200622
vsonline|ms-|1.0.2390
vscode-jest|Ort|3.2.0
vscode-autohide|sir|1.0.5
code-spell-checker|str|1.9.0
vscode-icons|vsc|10.1.1
material-theme|zhu|3.8.2

</details>

**Comment by sbatten** [comment]
The menu is using the menubar logic and is unaware that it should flow left. Need to either adopt a flow direction in the toggle more button or make the menu logic more advanced.

**Comment by yume-chan** [comment]
@sbatten I don't think that's true. If I set `"window.menuBarVisibility": "compact"`, and with my side bar on the right side, submenus will correctly flow to the left. I don't know if it's hard coded or it's smart enough to know there is no room at right side.

![image](https://user-images.githubusercontent.com/1330321/85650889-1b46ba80-b6d9-11ea-83d3-13634e6480ef.png)

**Comment by sbatten** [comment]
Compact menubar has the logic that this needs to adopt

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/88499805-8c8bcd00-cff9-11ea-85b0-cbda0bdfec4d.png)

Now the missing of background makes it totally unusable.

```text
Version: 1.48.0-insider (user setup)
Commit: 731f9c25632dbbf01ee3a7892ad9d2791fe0260c
Date: 2020-07-24T05:57:10.466Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by qcz** [comment]
The problem is much worse when trying to use the new proposed submenus API in a right side sidebar editor context menu:

![2020-07-31_18-18-34](https://user-images.githubusercontent.com/304384/89055288-6bf5a700-d35a-11ea-83dd-0aaf3d5efd76.gif)
