### ISSUE TITLE
Reduce the panel minimum width (or make it configurable)

### ISSUE THREAD

**Issue by javawizard** [microsoft/vscode#100836]
It looks like [the current minimum width for the panel is 300px](https://github.com/microsoft/vscode/blob/35266f90b6d4befd00bd5db18f1c0eaff0e7829f/src/vs/workbench/browser/parts/panel/panelPart.ts#L70). Lately I've been pinning the Outline view to the right side of the screen by dragging it into the panel and then moving the panel to the right, which has worked well for me as I rarely use the panel for anything else. However, I wish I could make it narrower.

Any chance of reducing the minimum width further, say to 170px to [match the sidebar](https://github.com/microsoft/vscode/blob/35266f90b6d4befd00bd5db18f1c0eaff0e7829f/src/vs/workbench/browser/parts/sidebar/sidebarPart.ts#L47), or alternatively making it configurable?

Note that at its narrowest the panel currently [cuts off several icons](https://github.com/microsoft/vscode/issues/87347) when the Terminal view is active:

(at 300px)
<img width="402" alt="Screen Shot 2020-06-23 at 3 02 06 AM" src="https://user-images.githubusercontent.com/874635/85384030-f34f2f80-b4fd-11ea-8a50-f53fbd2c85a9.png">

(wider)
<img width="623" alt="Screen Shot 2020-06-23 at 3 01 55 AM" src="https://user-images.githubusercontent.com/874635/85384062-fcd89780-b4fd-11ea-822a-bb05c36adb61.png">

So this wouldn't introduce any problems that aren't already present.

---

I'm also open to suggestions on a quick way to hack up my local install to do this, if it's otherwise not generally wanted. Note that I'd like to avoid losing access to the extension marketplace, so permanently running a home-built VSCode is not ideal unless there's a way to re-enable it.

---

Version info, if it's helpful:

Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by sbatten** [comment]
folding this into #87347
