### ISSUE TITLE
My VS Code OSS built from today's master is broken

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#100873]
Issue Type: <b>Bug</b>

Create a new file.

Unable to open 'Untitled-1': Cannot read property 'minimapWidth' of undefined.

Version: 1.47.0
Commit: Unknown
Date: Unknown
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-3420M APU with Radeon(tm) HD Graphics (4 x 1497)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.47GB (1.55GB free)|
|Process Argv|. --disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

A relevant fragment from the shell I launched `.\scripts\code.bat --disable-extensions` from.

```
[1020512:0623/175601.675:INFO:CONSOLE(144)] "%c  ERR color: #f33 Cannot read property 'minimapWidth' of undefined: TypeE
rror: Cannot read property 'minimapWidth' of undefined
    at EditorScrollbar._setLayout (file:///C:/Users/johnm/Documents/GitHub/gjsjohnmurray/vscode/out/vs/editor/browser/vi
ewParts/editorScrollbar/editorScrollbar.js:79:93)
    at new EditorScrollbar (file:///C:/Users/johnm/Documents/GitHub/gjsjohnmurray/vscode/out/vs/editor/browser/viewParts
/editorScrollbar/editorScrollbar.js:41:18)
    at new View (file:///C:/Users/johnm/Documents/GitHub/gjsjohnmurray/vscode/out/vs/editor/browser/view/viewImpl.js:39:
31)
    at CodeEditorWidget._createView (file:///C:/Users/johnm/Documents/GitHub/gjsjohnmurray/vscode/out/vs/editor/browser/
widget/codeEditorWidget.js:1177:30)
    at CodeEditorWidget._attachModel (file:///C:/Users/johnm/Documents/GitHub/gjsjohnmurray/vscode/out/vs/editor/browser
/widget/codeEditorWidget.js:1099:50)
    at CodeEditorWidget.setModel (file:///C:/Users/johnm/Documents/GitHub/gjsjohnmurray/vscode/out/vs/editor/browser/wid
get/codeEditorWidget.js:247:22)
    at OutputEditor.setInput (file:///C:/Users/johnm/Documents/GitHub/gjsjohnmurray/vscode/out/vs/workbench/browser/part
s/editor/textResourceEditor.js:50:28)
    at async OutputEditor.setInput (file:///C:/Users/johnm/Documents/GitHub/gjsjohnmurray/vscode/out/vs/workbench/contri
b/output/browser/outputView.js:184:17)", source: file:///C:/Users/johnm/Documents/GitHub/gjsjohnmurray/vscode/out/vs/pla
tform/log/common/log.js (144)
```

[Source pointer of error](https://github.com/microsoft/vscode/blob/a6d014fc57d2a0b84bb5cc574636c5e4be211f82/src/vs/editor/browser/viewParts/editorScrollbar/editorScrollbar.ts#L114)

[This line](https://github.com/microsoft/vscode/blob/a6d014fc57d2a0b84bb5cc574636c5e4be211f82/src/vs/editor/browser/viewParts/editorScrollbar/editorScrollbar.ts#L107) returns bad value for layoutInfo.

Perhaps caused by #97742 which was merged earlier today by @mjbvz and added an entry to the EditorOption enum:

```
showDeprecated = 112
```

causing layoutInfo to move from 115 to 116

Also occurs if launching with `--user-data-dir` specifying a fresh directory.

Could this be causing either of today's unit test failures, #100828 and #100842 ?

**Comment by mjbvz** [comment]
Try doing a full rebuild (delete the existing output and then restart `yarn run watch`). Whenever we update editor settings, you need to rebuild the entire core codebase. 

Let me know if you still see this problem after doing a fresh build

**Comment by gjsjohnmurray** [comment]
> delete the existing output

@mjbvz thanks for the pointer. Is there a command or script to do that? Or should I wipe my entire local directory and clone again from my fork of master?

Also, it'd be good to get the wiki at https://github.com/microsoft/vscode/wiki/How-to-Contribute improved with this kind of info.

**Comment by gjsjohnmurray** [comment]
I deleted my `.build` and `out` subdirectories (had to reboot first because something was locking a file), then ran `yarn` and when that finished `.\scripts\code.bat` was able to launch a working OSS.

**Comment by mjbvz** [comment]
Yes typically a full rebuild should fix this, but it does not deleting `out` should make sure the JavaScript is recompiled
