### ISSUE TITLE
php ext  can't support.

### ISSUE THREAD

**Issue by zhuzhuhawk** [microsoft/vscode#100811]
Issue Type: <b>Bug</b>

I use vscode to edit .php,
but,  .php file have no color.

![image](https://user-images.githubusercontent.com/11750448/85353695-70e56080-b53b-11ea-8247-8a29f48b60d1.png)
![image](https://user-images.githubusercontent.com/11750448/85353735-8bb7d500-b53b-11ea-9d4b-7db51cd75d9e.png)

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-intelephense-client|bme|1.4.1
vscode-html-css|ecm|0.2.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
code-runner|for|0.10.0
vscode-language-pack-zh-hans|MS-|1.46.3
python|ms-|2020.6.89148
remote-wsl|ms-|0.44.4
php-docblocker|nei|2.1.0
format-html-in-php|rif|1.6.2
code-settings-sync|Sha|3.4.3
php-formatter|Sop|0.2.4
vscode-icons|vsc|10.1.1

</details>

**Comment by roblourens** [comment]
I'm not sure where the php language is coming from, but it's probably coming from an extension - the language in the status bar would be "PHP" in caps if it's the language provided by VS Code.
