### ISSUE TITLE
Don't show the "mssql" extension for SQL files & add more granular SQL language options

### ISSUE THREAD

**Issue by Zamiell** [microsoft/vscode#100883]
Related to issue #41368.

Consider the following user story:

1. The user opens a PostgreSQL file with an extension of ".sql". (e.g. "postgresql_database_schema.sql")
2. A popup appears in the bottom-right-hand-corner that states: "The 'mssql' extension is recommended for this file type."
3. This popup message is spurious because the file is for a PostgreSQL database, so the user frowns and promptly closes it.
4. If the file is closed and opened again, the popup message will not return.
5. However, if the entire editor is closed and reopened, and the file is opened again, the popup message will return again (because it is a brand new session and VSCode does not remember that the user has already ignored the popup message).
6. In an attempt to get the spurious popup to go away, the user clicks on the "Install" button on the popup in order to install the "mssql" extension to try and prevent it from ever showing up ever again.
7. After the "mssql" extension is installed, it immediately throws up a zillion errors in the file, presumably because VSCode thinks that it is an MSSQL file and it is in fact a PostgreSQL file.
8. The user realizes that the new situation is much more terrible than the previous one, so they immediately uninstall the "mssql" extension.
9. Finally, after some more trial and error, the user eventually finds out that he can click on the gear inside the popup and select "Don't Show Again" in order to permanently suppress the popup. This correctly works, even between VSCode restarts.
10. The "postgresql_database_schema.sql" file is part of a repository that the user owns. So, the user looks into some way to specify in the ".vscode/settings.json" file of repository that no popups should occur when opening the "postgresql_database_schema.sql" file. After searching for a while, the user is not able to find anything. The user knows that this same disastrous sequence of events will happen for anyone who happens to clone his repository, in a never-ending cycle of frustration.

Overall, a bad experience for the user.

Essentially, this user story is predicated on VSCode not being smart enough to derive the dialect of SQL for any arbitrary SQL file that a user opens. Thus, VSCode defaults to assuming that it is a MSSQL file and prompts the user to install the MSSQL extension.

According to [some quick research on Google](https://scalegrid.io/blog/2019-database-trends-sql-vs-nosql-top-databases-single-vs-multiple-database-use/#:~:text=Most%20Popular%20Databases,-So%2C%20which%20databases&text=MySQL%20dominated%20this%20report%20with,%2C%20and%20Cassandra%20at%203.0%25.&text=DB%2DEngines%20Ranking%20%E2%80%93%20Trend%20Popularity,SQL%20Server%20at%20number%203.), MySQL appears to be the most popular SQL database in the world, followed by PostgreSQL. MSSQL doesn't even show up on the chart. Thus, it seems strange that VSCode has taken the opinionated stance of assuming that an unknown SQL file is MSSQL instead of the other two.

First and foremost, I propose that if MySQL is the highest market share, and VSCode does not have the intelligence to parse the different dialects, then it should simply assume that it is a MySQL file. The current behavior of guessing that the file is MSSQL will be wrong in almost all cases, statistically speaking.

Furthermore, VSCode classifies the "language" of a ".sql" file as "SQL". But as we have seen, this is not specific enough. VSCode should have additional languages added: "MySQL", "MSSQL", and "PostgreSQL". Then, the user can specify exactly what language it is in their "settings.json" file:

```
"files.associations": {
  "postgresql_database_schema.sql": "postgres", // This is "sql" by default, so we must specify it here
}
```

And subsequently, VSCode would then be able to offer a better extension recommendation to the end-user, e.g. the [MySQL VSCode extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.vscode-mysql) or the [PostgreSQL VSCode extension](https://marketplace.visualstudio.com/items?itemName=ms-ossdata.vscode-postgresql).

Thanks for your consideration.

**Comment by chrisdias** [comment]
this was fixed a couple of releases back. let me know if it is still an issue.

**Comment by Zamiell** [comment]
What exactly was fixed? I outlined several different flaws with VSCode in my post and several different suggestions. For example, on the latest version of VSCode, the editor is still not smart enough to recognize PostgreSQL syntax, and indeed the editor does not even have this as a language option.

**Comment by chrisdias** [comment]
sorry, we don't have an "important" recommendation for the sql extension for .sql files anymore.  in other words, when you open a .sql file we don't prompt to install the mssql extension.

**Comment by Zamiell** [comment]
Sounds good. Do you want me to open a new issue for the other things, or should we leave this open?

**Comment by chrisdias** [comment]
please open a separate issue, thanks.
