### ISSUE TITLE
Disable and re-enable only my Enabled extensions 

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#100834]
I have about 50 active extensions and about 15 disabled extensions (5 of those are normal extensions, 10 of those are disabled built-in themes). When troubleshooting an issue with extensions, I'd like to be able to do this:

1. Disable all extensions (there's a **Disable All Installed Extensions** command for this)
2. Experiment with plain VSCode
3. Re-enable all extensions _that were disabled by step 1_.

I want to end up with exactly the same set of both Enabled (50) and Disabled (15) extensions after the steps above. When I tried the **Enable All Extensions** command, it enabled everything – logical but I then needed to manually find and disable the previously disabled extensions and themes again.

I wouldn't mind if this was CLI only, e.g.:

1. `code --disable-extensions`
2. Experiment
3. `code --reenable-extensions`

But the main problem, I guess, is that probably VSCode doesn't differentiate between user-disabled extensions and those disabled technically, by a CLI flag or a command...

**Comment by gjsjohnmurray** [comment]
It's possible to create a temporary workspace (e.g. DisableExtensions.code-workspace), then disable **for this workspace only** each currently-enabled extension. Then by hovering over the main icon of any extension in the Disabled view you can tell if it was globally disabled or only disabled for this workspace. Progressively re-enable for this workspace just the ones that were only disabled for the workspace, until you find which one is causing your problem.

I'd like to propose a couple of enhancements to make this technique easier to use.

1. Add a variant of the `Extensions: Disable All Installed Extensions for this Workspace` command [(code pointer)](https://github.com/microsoft/vscode/blob/2dec57c7f2a63ac9ede0ae3cc55a4bfd9fc7dd71/src/vs/workbench/contrib/extensions/browser/extensionsActions.ts#L2873-L2897) that only marks as "disabled-for-this-workspace" the extensions that are currently enabled for it. The existing commands marks as "disabled-for-this-workspace" all installed extensions, including those currently disabled globally.
2. Add a filter `@disabled:workspace` [(code pointer)](https://github.com/microsoft/vscode/blob/2dec57c7f2a63ac9ede0ae3cc55a4bfd9fc7dd71/src/vs/workbench/contrib/extensions/browser/extensionsViews.ts#L416-L429) to quickly locate extensions explicitly disabled for the current workspace.

The first of these will help with the first phase of the approach I describe above, and the second will help with the second phase.

@sandy081 are you open to a PR from me implementing these?

**Comment by yume-chan** [comment]
> When troubleshooting an issue with extensions

I believe the troubleshooting guide suggests using the `Developer: Reload with extensions disabled`. This command, after another reloading, will restore to previous state (so disabled extensions are still disabled).

**Comment by borekb** [comment]
@yume-chan That indeed worked, thanks! I missed that command as I was only looking visually in the Extensions panel's  drop down menu.

BTW is the troubleshooting guide published somewhere? Tried to find it but no luck so far.

**Comment by gjsjohnmurray** [comment]
> BTW is the troubleshooting guide published somewhere? Tried to find it but no luck so far.

The wiki page at https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions has some good advice, including a link to a page about disabling extensions.

**Comment by yume-chan** [comment]
> BTW is the troubleshooting guide published somewhere?

I can't remember exactly. I thought it used to be in this repository's Wiki pages or Code's official website but neither can I find it now.

Or maybe I just leant this from some Code developer team member's comments.

---

> I wouldn't mind if this was CLI only, e.g.:
>
> `code --disable-extensions`

It also works, and has the same effect as the above command, see https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions

This usage is also in this repository's issue template.

**Comment by borekb** [comment]
Thanks, it covers my use case, I'll close this issue.
