### ISSUE TITLE
'Tweet Feedback' window does not save its state properly on reopen

### ISSUE THREAD

**Issue by nlchar** [microsoft/vscode#100897]
Issue Type: <b>Bug</b>

1. Click 'Tweet Feedback' button at the right bottom corner of the Visual Studio Code window. 
2. Type some text in the text box in the appeared floating window. 
3. **Current state:** character counter is less than 270, 'Tweet' button is active and clickable. 
4. Close the floating window either using ESC key or by tapping the 'Close' button at the top of the window.
5. Click 'Tweet Feedback' button again to reopen the window. 
The state is incorrectly restored: 

-  The text is restored, it is in the text box as it should be.
-  The character counter is not restored and is equal to 270 characters.
-  The 'Tweet' button is not active and is not clickable. 
Any change in the text box or selection of any of the smiles will result in state update to the expected values. 
![standard](https://user-images.githubusercontent.com/64870515/85484914-6a54f880-b5d0-11ea-8e0e-60da5fa223bc.gif)

Also, if you choose 'Happy Feedback Sentiment' at any point, the default value of the character counter on the window reopen would be 257, not 270 (because the 'Happy Feedback Sentiment' mode adds the '#HappyCoding' hashtag to the resulting tweet status), so the Feedback Sentiment selection state persists properly on the window reopen. 
![happy](https://user-images.githubusercontent.com/64870515/85485334-30d0bd00-b5d1-11ea-8088-09d00c063d52.gif)
**Possible solution**
The code responsible for the feature is located in [the file](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/feedback/browser/feedback.ts). The `updateCharCountText` function does the job of updating the counter & the 'Tweet' button state, so its call in the window reopen function may be sufficient to resolve the issue. I think the `show` function is called on window reopen, so it may be used for that purpose. 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by nlchar** [comment]
If the possible solution I suppose is correct I would like to try to correct the issue.

**Comment by dbaeumer** [comment]
Not sure who owns this.

**Comment by bpasero** [comment]
If someone wants to investigate, no plans from my end.

**Comment by nlchar** [comment]
I set up the development environment as described in the repository wiki to try to fix this issue and contribute the code as a PR. However, after a long path of trying to run the Code - OSS I ended up with a version of VS Code with no 'Tweet Feedback' feature at all (no icon in the status bar, no entry in the command palette).

```
Version: 1.47.0
Commit: Unknown
Date: Unknown
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Linux x64 5.4.0-26-generic
```
@bpasero @sandy081 do you know why the 'Tweet Feedback' feature is out of the Code - OSS build and can I fix this somehow to work on the issue?

**Comment by bpasero** [comment]
@nlchar yeah you will make changes to `product.json` as follows:

```json
"sendASmile": {
	"reportIssueUrl": "https://go.microsoft.com/fwlink/?LinkId=534872",
	"requestFeatureUrl": "https://go.microsoft.com/fwlink/?LinkID=533482"
}
```

Then you should get it.
