### ISSUE TITLE
vscode.workspace.openTunnel() does not resolve

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#100822]
Still works in stable, must be a regression in insiders. We use the following to establish a tunnel, the promise no longer resolves:
```ts
	await vscode.workspace.openTunnel({
		remoteAddress: {
			host: '127.0.0.1',
			port
		}
	});
```

**Comment by alexr00** [comment]
@chrmarti, hijacked a command with this:
```
	context.subscriptions.push(vscode.commands.registerCommand('remote-containers.settings', async () => {
		const temp = await vscode.workspace.openTunnel({ remoteAddress: { host: '127.0.0.1', port: 3000 } });
		console.log(temp);
	}));
```
I'm not seeing any problems with it. Do you have any other ideas on how to repro?

**Comment by chrmarti** [comment]
I'm calling this from the resolver, maybe the implementation waits for something to finish that only finishes after the resolver returned?
