### ISSUE TITLE
Depending on how you start VSCode, it could trigger 2 completely different behaviours.

### ISSUE THREAD

**Issue by ogrotten** [microsoft/vscode#100806]
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/8119012/85349507-41474180-b4c4-11ea-9bf0-b90d5c600a3a.png)

</details>

Issue Type: <b>Bug</b>

In the screenshot, there are 2 different windows of VSCode that are results of different start methods. 

* The left most was started in a Windows Explorer directory > right click > Open with Code Insiders.
* The inner window was started via a VSCode icon pinned to the task bar.

The desired behaviour would be a consistent offering of git startup options regardless of how the program gets started. As it stands, if I navigate to a directory and then right-click start, it's a non-trivial path to start from a cloned repo.

I would suggest that all 4 options be available. It's not too much, and there's no overlap.

VS Code version: Code - Insiders 1.47.0-insider (84f52fe1c0124307046ac0f5443493cda946e60f, 2020-06-17T06:43:38.511Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.37GB free)|
|Process Argv|S:\Projects\WORKING\Primitive Quiz\Code|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-browser-preview|auc|0.6.7
bracket-pair-colorizer-2|Coe|0.1.4
auto-rename-tag|for|0.1.3
vscode-peacock|joh|3.7.2
git-graph|mhu|1.24.0
debugger-for-chrome|msj|4.12.8
indent-rainbow|ode|7.4.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|sib|2.0.1
quokka-vscode|Wal|1.0.301

</details>

**Comment by gjsjohnmurray** [comment]
Left one was launched for a specific folder, so the Git suggestions are appropriate for that folder.

Right one has no folder context. 

To switch laft one to be like right one, Close Folder from File menu.
