### ISSUE TITLE
Printable keyboard cheatsheet with real bindings

### ISSUE THREAD

**Issue by tomhanax** [microsoft/vscode#100825]
Greetings, 
printable keyboard cheetsheet is great idea. However, IMHO it will be much better, if it reflects real keybinings. For example, I use Eclipse Keymap, so the current cheatsheet is not entirely relevant and practically unusable, because you do not know if that keybinding was remapped or it is a feature you did not know about. Surely that document can be generated as HTML at runtime from within VS Code using real keybindings.

**Comment by dbaeumer** [comment]
@gregvanl not sure who owns this.

**Comment by gregvanl** [comment]
@tomhanax To keep people in the product, we could add filters to the Keyboard Shortcuts editors, similar to the Settings editor's `@modified`. What if there was a @cheatsheet filter that would limit the Keyboard Shortcuts display to only those keybindings in the current US-English cheatsheet? Users could browse the editor to learn the command keybindings based on their platform and keyboard layout.

**Comment by gregvanl** [comment]
@sandy081 How feasible would it be to add a new filter @cheatsheet to the Keyboard Shortcuts editor to show just the keyboard shortcuts listed in the Keyboard Shortcuts cheat sheet. It would be a hard-coded list of about 140 command IDs.

**Comment by sandy081** [comment]
Sounds do-able, but what is Keyboard Shortcuts cheat sheet in the product and where and how it is defined?

**Comment by gregvanl** [comment]
@sandy081 The list used for the keyboard shortcut cheat sheet is at https://github.com/microsoft/vscode-docs/blob/master/docs/customization/keyboard-shortcuts.md. I can provide this list in the vscode repo in any format that is convenient.

**Comment by sandy081** [comment]
Thanks, let's wait for more users asking for this before supporting.

**Comment by Hikaruxy** [comment]
Perhaps this can be tied in with #107423.
