### ISSUE TITLE
Command palette should not show keybinding with args

### ISSUE THREAD

**Issue by yume-chan** [microsoft/vscode#100830]
Issue Type: <b>Bug</b>

I'm trying to implement #100460 which add `args` support for `workbench.action.selectTheme` command, allowing users to define keybindings to directly switch to a specified theme.

However I found that after defining such a keybinding, it will show up in the command palette.

![image](https://user-images.githubusercontent.com/1330321/85378957-c175b180-b56d-11ea-90ef-6c58a203b46c.png)

![image](https://user-images.githubusercontent.com/1330321/85378654-69d74600-b56d-11ea-97cb-76242aaa0f87.png)

Obviously a keybinding with `args`, at least most of time, will work differently from invoked by command palette. So IMO these keybindings are misleading and should not be included in command palette.

VS Code version: Code - OSS Dev 1.47.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (5.06GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by dbaeumer** [comment]
@bpasero  not sure if you still own the command palette
