### ISSUE TITLE
Introduce compact flag to DebugSessionOptions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#100852]
Refs: https://github.com/microsoft/vscode/issues/99736

We are now compressing debug sessions in the call stack view when there is only one child session.
Since this behavior might not be ideal for all debug extension out of safety we would like to introduce a new flag `noCompact` to the DebugSessionOptions.

If the option is not specified would be the same as `false` and thus we would compact the sessions.

fyi @jrieken

**Comment by isidorn** [comment]
Feedback from api call: it is fine to introduce the option as proposed and then next milestone we will see if debug extensions actually use it, and if nobody wants it we remove it. 
Also the name should be compact not compress since that is how we call it in explorer settings.

**Comment by isidorn** [comment]
I have introduced a `noCompact` flag to the `DebugSessionOptions`.
@weinand and @connor4312 feedback on name is welcome. I went with the `compact` since that is the user facing name of the `explorer.compactFolders` setting.

We wanted to make it negative, since the default that it is not specified should be the same as `false`.
Also aligns with `noDebug`.

**Comment by isidorn** [comment]
Since we have added this api as proposed and created a test plan item, I am moving this out to on-deck for finalisation.
Name changes we can of course still do.

**Comment by isidorn** [comment]
We have renamed this flag to be called `compact`, and to be opt-in. Thus by default we will not compact the session with it's parent.

**Comment by isidorn** [comment]
We plan to finalize this API this August milestone. Just in case there is more feedback before we finalize it.

fyi @connor4312

**Comment by connor4312** [comment]
I've adopted this in js-debug, no real complaints. I had to change some behavior since certain interactions now always target the child, but these were my problems.

**Comment by isidorn** [comment]
The current JS Doc comment on the `compact` flag is 
```
Controls if the debug session's parent session is shown in the CALL STACK view even if it has only a single child.
		 * By default, the debug session will never hide its parent.
		 * If compact is true, debug sessions with a single child are hidden in the CALL STACK view to make the tree more compact.
```

Feedback from API sync: 

"We should make it more clear in the comment that the parent and the child session are actually rendered together since some actions (like stop) might be executed on the parent."


For now I will not change the comment. But @connor4312 and @weinand let me know what you think and if you would like me to change the comment.

**Comment by isidorn** [comment]
I have finalized this API and have created this test plan item to cover the finalisation https://github.com/microsoft/vscode/issues/104986
