### ISSUE TITLE
Visual Studio Code not opening/freezing in background

### ISSUE THREAD

**Issue by mrkybe** [microsoft/vscode#100862]
- VSCode Version: Latest
- OS Version: Windows 1909

So the issue is that after a while, VS Code will not open.  I'm trying to open it via Admin level PowerShell `code --disable-extensions` and I tried `code --disable-extensions --max-memory=12288mb` (which apparently helps if its crashing from a large file? I didn't have any large file open though.)  When I run the command, it shows Windows doing something, the cursor changes to the loading one, but VSCode doesn't open.  The issue goes away for a while if I reboot.  I also notice that there were VSCode.exe's running in the background.  I end'd process on them, but VSCode still doesn't open until there's a full reboot (or possibly logging in and out?).

Steps to Reproduce:

Not sure exactly, this only happens on my work machine which I don't really have full control over.  I think this might be an Electron issue?  I've ran into the same issue once on MS Teams, but it hasn't happened since then (but I also don't ever close MS Teams).

Does this issue occur when all extensions are disabled?: **Yes**

Is there some sort of log file I can attach?

**Comment by deepak1556** [comment]
Can you run with `--verbose` and attach the logs printed to the console. 

When it freezes can you take a process dump with https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer , right click on the process > create dump > create minidump

Also check if the issue happens with our insiders build https://code.visualstudio.com/insiders/ . Thanks!
