### ISSUE TITLE
'get' and 'set' accessors cannot declare 'this' parameters.

### ISSUE THREAD

**Issue by rgbui** [microsoft/vscode#100810]
为什么编译出现这种错误，之前是没有的，因此还特意的将VSCODE版本从1.46.1降到1.45.1。但是仍然出现这种错误，应该是类型引擎有问题。

There was no such error in compilation before, so we deliberately lowered the VSCODE version from 1.46.1 to 1.45.1.However, this error still occurs, which should be due to the type engine.

**Comment by rgbui** [comment]
The compilation error occurred, error: 'get' and 'set' accessors cannot declare 'this' parameters. so the VSCODE version was deliberately lowered from 1.46.1 to 1.45.1.However, this error still occurs, which should be due to the type engine.How do I solve this problem? This problem happens every time I compile. It happened recently after I updated vscode.

**Comment by rgbui** [comment]
give you an example problem

```
export class View$Model {
    get closestModelView(this: View): View {
        return this.closest(x => x.isModel == true || x.isTemplate);
    }
    get closestModel(this: View): Model {
        var view = this.closestModelView;
        if (view) {
            return view.model;
        }
        return null;
    }
```
```
export interface View extends View$Model { }

Util.inherit(View, View$Model)
```
the "this: View"  Will report an error, prompt:  'get' and 'set' accessors cannot declare 'this' parameters.
It was ok before
Updating the VsCode happens

**Comment by mjbvz** [comment]
The error message explains what is wrong: you cannot use `this` parameters in getter or setters. 

Please file an issue against TypeScript if you want this to be supported
