### ISSUE TITLE
Git won't work after Windows updates 2004

### ISSUE THREAD

**Issue by shiZendg** [microsoft/vscode#100833]
Issue Type: <b>Bug</b>

Git won't work after Windows updates 2004,Displays initialization of Git,But clicking the initialize button doesn't do anything.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-beautifier|mic|2.3.3
vscode-language-pack-zh-hans|MS-|1.46.3
vetur|oct|0.24.0
language-stylus|sys|1.11.0

</details>

**Comment by gjsjohnmurray** [comment]
What Git version do you have on your PC?
