### ISSUE TITLE
screen reader focus does not switch to errors view when user clicks show errors button.

### ISSUE THREAD

**Issue by venkateshpotluri** [microsoft/vscode#100871]
Issue Type: <b>Bug</b>

1. open a project with build errors. (I am working on a VSCode extention)
2. press F5. You should see a dialog box that says errors exist after running prelaunch task 'npm: watch'.
3. click the show errors button. The screen reader focus remains on the editor containing the code.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (4.28GB free)|
|Process Argv|.|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.50
vscode-eslint|dba|2.1.5
vscode-pull-request-github|Git|0.17.0
latex-workshop|Jam|8.10.0
python|ms-|2020.6.89148
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
vsliveshare|ms-|1.0.2354
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0

</details>

**Comment by isidorn** [comment]
@venkateshpotluri we pushed a fix, you can try it out with vscode insiders from tomorrow if it works well for you. I tried it out and seems good know. 
Thanks for filling this issue and let us know if you hit more issues.
