### ISSUE TITLE
Markdown preview fails to load required CSS and JS on VSCode startup

### ISSUE THREAD

**Issue by JoernBerkefeld** [microsoft/vscode#100879]
- VSCode Version: 1.46.0
- OS Version: Windows 10 / Windows_NT x64 10.0.18363

**Steps to Reproduce:**

1. Open any .md / markdown file
2. Open the preview to the side
3. close the VSCode window
4. re-open VSCode 
    - this should automatically re-open the same previously open workspace/folder
    - the Markdown file and its preview tab should re-open automatically

**Expected outcome:**
Markdown preview is rendered according to current theme - or to what's setup in markdown.style / markdown.previewStyle.

**Actual outcome:**
Only inline styles and default browser styles are rendered, leaving the preview looking distorted.
looking at the webview console, I can see 7 errors prefixed with `Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME` for:
- pre.js
- markdown.css
- highlight.css
- checkbox.css
- katex.min.css
- index.js

![image](https://user-images.githubusercontent.com/1917227/85442643-aff1d100-b590-11ea-89c0-3502ee2a4e06.png)

and this is how my preview then looks like:
![image](https://user-images.githubusercontent.com/1917227/85442971-095a0000-b591-11ea-9611-03eb9b224eae.png)

**Workaround:**
1. Close preview
2. re-open preview

![image](https://user-images.githubusercontent.com/1917227/85443037-1545c200-b591-11ea-91b7-e427e3ea4725.png)

Does this issue occur when all extensions are disabled?: Could not test.

**Comment by gjsjohnmurray** [comment]
Maybe related to #100727

**Comment by JoernBerkefeld** [comment]
hi @gjsjohnmurray - yes, i can confirm that i saw the same behavior with `markdown.previewStyles` and `markdown.styles`

**Comment by sweettyler** [comment]
@mjbvz I saw this happened with the insider version as early as May 21 and mysteriously back to normal May 25. I don't think the commit 61f796e is the real cause, though the problem may disappear after you revert it back.

**Comment by mhutchie** [comment]
@mjbvz I've had reports that this was fixed in the Insiders release 9b620b2, however it is broken again for every user I've checked with in:

Version: 1.47.0-insider (user setup)
Commit: 6c235c723cb2d8defb840f732eac620f54aa8b9d
Date: 2020-06-26T06:20:06.931Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

How could this occur?
