### ISSUE TITLE
app.use() throwing error

### ISSUE THREAD

**Issue by connect-dhruvi** [microsoft/vscode#100814]
Issue Type: <b>Bug</b>

There is no mistake in the code.
Simply when i try to route , it tells expected a function.
I start VS code and it works fine

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (5.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-icontheme-nomo-dark|be5|1.3.6
bracket-pair-colorizer|Coe|1.0.61
auto-close-tag|for|0.5.7
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.3
LiveServer|rit|5.6.1
git-merger|sha|0.4.1

</details>

**Comment by dbaeumer** [comment]
@connect-dhruvi this sounds like a problem with your application code. 

If you still think this is related to VS Code itself please provide detailed steps how to reproduce.
