### ISSUE TITLE
vscode jupyter lose most progress when script run and freeze

### ISSUE THREAD

**Issue by zhangx306** [microsoft/vscode#100820]
Issue Type: <b>Bug</b>

i selected auto-save on vscode. however, when the .ipynb script ran and froze, i lost most progress once i shut it down. it happened more than 5 times in the past 7 days so it is a persistent issue.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.66GB (25.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|3.0.36
latex-workshop|Jam|8.10.0
python|ms-|2020.6.89148

</details>

**Comment by dbaeumer** [comment]
The Jupyter notebooks come from the Python extension. Please file the issue there.
