### ISSUE TITLE
Open file from call stack during debug session broken when currently opened folder is on a network share

### ISSUE THREAD

**Issue by callumdmay** [microsoft/vscode#100894]
Opening a VSCode session in a network share on another machine works great and debugging works as expected, however when pausing at a breakpoint, the current file that the breakpoint belongs to does not get resolved correctly and uses the local path (C:\src\.. etc.) to the file and not the network share path (\\remote-machine\src...).  The same occurs when you click on any frame in the callstack, an error pops up "Unable to resolve non-existing file...". I can repro this for C++.

Repro steps:

1. Create a VM or use another machine on the same network and install VS Code on it. 
2. On your current machine, share a src folder onto the network.
3. On the VM, open VS Code on the network share src folder
4. Start a debug session, set a breakpoint
5. Trigger the breakpoint, observer that the file that the breakpoint broke on is not opened when the breakpoint is hit and an error pops up  "Unable to resolve non-existing file..." 
6. Click on different frames in the call stack and observe the same behaviour

**Comment by callumdmay** [comment]
Closing out, will add with machine and VSCode version context

**Comment by callumdmay** [comment]
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by isidorn** [comment]
Seems like the C++ can not handle fetching those files, please file the issue against the C++ extension
https://github.com/microsoft/vscode-cpptools

**Comment by callumdmay** [comment]
Will do thanks
