### ISSUE TITLE
Support file watching outside of the workspace

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode#100870]
This is a follow-up from https://github.com/microsoft/vscode-languageserver-node/issues/641.

I work on the Go language server, and we noticed that the file watching API only allows us to watch for file changes in the current workspace. This poses an issue for us because:

> In Go, users typically work in [modules](https://blog.golang.org/using-go-modules), but they may open subdirectories of those modules in VS Code. An on-disk change to any file in the module may affect the subdirectory opened by the user. Furthermore, dependencies of modules can be [replaced](https://thewebivore.com/using-replace-in-go-mod-to-point-to-your-local-module/) with files on-disk. I would like the [Go language server](golang.org/s/gopls) to watch all files in the module and replace directives, not just the files in the workspace.

Is there any possibility of extending the VS Code file watching API to support watching arbitrary locations on disk? LSP recommends that [servers rely on the client's file watching](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workspace_didChangeWatchedFiles), but that will not be possible for us with the current behavior.

**Comment by dbaeumer** [comment]
@bpasero this is not a general problem of language servers. If the Go extension would not use a language server (e.g. only using the VS Code extension API) the extension couldn't watch these files either.

**Comment by jakebailey** [comment]
This'd be useful for Python where we have to set up file watchers for search paths to detect package installs, which are often not within a workspace (pipenv, conda, global installs).

**Comment by karrtikr** [comment]
Is https://github.com/microsoft/vscode/issues/3025 dup of this?
