### ISSUE TITLE
Themes and icons won't work:

### ISSUE THREAD

**Issue by Ritwik880** [microsoft/vscode#100824]
Whenever we download any themes for vs code and apply them to the editor it will only remain till the editor is open and when it restarts our  vs code all things are set to default. And we have to again apply the themes and icons.

The setting.json file is not working properly.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide info required by template (VSCode version, OS etc.)

**Comment by Ritwik880** [comment]
Having a theme/currentTheme key that could be set in settings.json would be useful in automatically setting the theme in an automated setup in my windows.

**Comment by aeschli** [comment]
I'm not able to reproduce:
- install a new theme in the extensions viewlet. A dropdown will show and lets you select the theme
- check the user settings (e.g command `Preferences: Open Settings (JSON)`). The new theme is configured
e.g. `"workbench.colorTheme": "Atom One Dark",`
- close and restart VSCode
- theme is still set.

Do you have settings sync enabled? Any other extensions or settings that could ipmact the theme setting?

**Comment by Ritwik880** [comment]
No, and same thing is happening for vs code icons also.

**Comment by aeschli** [comment]
Can you follow the steps and see if the theme is set in the settings after step 1?
