### ISSUE TITLE
Markdown - Codeblock within lists lacks highlighting in editor

### ISSUE THREAD

**Issue by erichiller** [Microsoft/vscode#10082]
## Basic Information
- VSCode Version: 1.3.1
- OS Version: OSX (if required I can try to reproduce on Windows)
## Steps to Reproduce:
1. Open markdown file
2. Create list doesn't matter whether it is 1 or more levels.
3. Add a code block inline

_**Two Examples Follow**_
## Example 1:

from this [gist](https://gist.githubusercontent.com/clintel/1155906/raw/6b2a78696ff6b0b7222691c52fd0f3c6b98e3172/gistfile1.md)

`````` typescript
1. This is a numbered list.
2. I'm going to include a fenced code block as part of this bullet:

    ```
    Code
    More Code
    ```

3. We can put fenced code blocks inside nested bullets, too.
   1. Like this:

        ```c
        printf("Hello, World!");
        ```

   2. The key is to indent your fenced block by **(4 * bullet_indent_level)** spaces.
   3. Also need to put a separating newline above and below the fenced block.
``````
## Example 2

Best Practices
- Start from the Project's Documentation, not their Source if possible
- Use _Namespaces_ for;
      - variable types
      - parameters
- Callbacks - (_functions as parameters_) - When writing the function signatures for these types, do not mark those parameters as optional. The right way to think of this is “What parameters will be provided?”, not “What parameters will be consumed?”.
- Extensible Declarations - using namespaces you can have a variable named the same in the current namespace, but with additional parameters...
  - [Declarations Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) for more details
    
    ``` typescript
    interface SomePoint { x: number; y: number; }
    declare var MyPoint: SomePoint;
    
    interface SomePoint { z: number; }
    MyPoint.z = 4; // OK
    ```
- xxx
## Output (attached):

![screen shot 2016-08-03 at 8 51 25 am](https://cloud.githubusercontent.com/assets/5379325/17372176/874800d8-5957-11e6-99ec-7955f47c5f23.png)

_As you can see the output is colorized perfectly fine, it is the editor side that is lacking_

However, it is only present within lists, as soon as I remove the indentations, the colorization within the editor returns.... see:
## Output (attached):

![screen shot 2016-08-03 at 8 52 41 am](https://cloud.githubusercontent.com/assets/5379325/17372207/abd0e064-5957-11e6-9f64-6778150b3a8a.png)
## Further information
- This does not seem to be the same issue as #9457 - as multiline blocks work when non-indented, and single blocks never work when indented.
- This issue occurs whether I am using tabs or spaces.

**Comment by Thraka** [comment]
From my quick tests it seems the editor is hard coded to color code markdown with 2 spaces to indicate indentation, no matter what. The preview properly determines indentation by whatever the first indentation is. I use 4 spaces for all indentation, therefor, the editor never colors anything under a list because it always thinks this is an automatic code block section. The preview always figures it out correctly.

**Comment by mjbvz** [comment]
@Thraka Both the editor and the preview target the commonmark spec: http://spec.commonmark.org/0.27/ which specifies what indentation is valid here. The preview conforms much more closely to the standard than the editor's syntax highlighter does

**Comment by colinfang** [comment]
Same as https://github.com/Microsoft/vscode/issues/22185

**Comment by i-give-up** [comment]
Did some testing on my own and found something surprising: If a blockquote or fenced code block follows a list item and it is indented by exactly 4 spaces, it is highlighted as if it is a paragraph.

Let's say this is our input

````` text
## For reference

paragraph, **indent**: `0`

>>> blockquote, **indent**: `0`

## Actual test

1. list item 1

   ``` js
   return "fenced code block, **indent**: `3`";
   ```

1. list item 2

    ``` js
    return "fenced code block, **indent**: `4`";
    ```

1. list item 3

     ``` js
     return "fenced code block, **indent**: `5`";
     ```

1. list item 4

    >>> blockquote, **indent**: `4`
`````

This is how it gets highlighted in VSCode

![paragraph-if-indent-4](https://user-images.githubusercontent.com/14156307/30363320-48d21f20-9892-11e7-8ec5-1f93b7af0f3b.png)


In list item 3, the fenced code block is indented by 4 spaces. Notice how it gets highlighted as if it is a paragraph (compare the highlighting to that paragraph's under "For reference"). In comparison, when indented by 3 or 5 spaces (in list items 1 and 3), the fenced code blocks do get highlighted correctly.

Same oddity with blockquote in list item 4. If you look closely at the blockquote under "For reference", the arrow(s) in properly highlighted blockquotes will have a light green color. And if you look at the blockquote in list item 4, the arrows have white color, implying that the blockquote is highlighted as if it is a paragraph too. Just like in the case of fenced code blocks, indentation by 3 or 5 spaces works fine.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#6
