### ISSUE TITLE
[folding] Improve recovering folded regions when file has changed

### ISSUE THREAD

**Issue by OneLookSigns** [microsoft/vscode#100860]
Issue Type: <b>Bug</b>

When switching between git branches, any folded blocks of code created by commands such as "Fold Level 1" won't get remembered and therefore all blocks of code are unfolded when a branch is switched to. 

This can be quite frustrating when you fold all the blocks of code you want in order to keep your code tidy and then you switch branches and back again to see everything has been unfolded.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aeschli** [comment]
Has the location of the folded blocks changed? We remember the line number of the folded ranges when the editor closes (or is hidden) and expect the file to be unchanged when opening again.

**Comment by ariffjeff** [comment]
No. Locations of folded blocks remain on their correct line numbers. The problem is only VS Code forgetting whether blocks of code were folded when switching branches and back again.

**Comment by aeschli** [comment]
We also check the line count. When we reopen a file and the line count has changed, we do not try to restore the folded regions.

**Comment by ariffjeff** [comment]
Makes sense. I've only been editing files in vs code though. So that wouldn't apply to me in this case.
