### ISSUE TITLE
gutter not showing git changes on wsl

### ISSUE THREAD

**Issue by victron** [microsoft/vscode#100843]
Issue Type: <b>Bug</b>

## Environment 
- win10 with active wsl
- on wsl I have such link to my windows filesystem
```
vic@AN:~/windir/Documents/_privat/GO/Projects/docerExp ->
15:29:38$ ls -ld ~/windir
lrwxrwxrwx 1 vic vic 19 Jun 22 15:21 /home/vic/windir -> /mnt/c/Users/viktor
vic@AN:~/windir/Documents/_privat/GO/Projects/docerExp ->
15:31:02$  ls -ld ./
drwxr-xr-x 1 vic vic 4096 Jun 23 15:21 ./
```

## open vs code in wsl 
```
vic@AN:~/windir/Documents/_privat/GO/Projects/docerExp ->
15:04:56$ code .
```
- doing some changes in file, even saving it
- after pusshing `update button` on sc panel it showes changes
- git also
```
vic@AN:~/windir/Documents/_privat/GO/Projects/docerExp ->
15:10:33$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Dockerfile

no changes added to commit (use "git add" and/or "git commit -a")
vic@AN:~/windir/Documents/_privat/GO/Projects/docerExp ->
15:11:09$
```
- but no any visualization on gutter

## on Native windows
- opening `C:\Users\viktor\Documents\_privat\GO\Projects\docerExp`
folder
- doing any changes in file without saving. Gutter fieds shows changed lines.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (17.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|Memory (System)|24.97GB (23.80GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
cisco|jam|1.8.1
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
jinjahtml|sam|0.13.0
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4
vscode-docker|ms-|1.3.1

(4 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
It's not recommended to use WSL tooling to work with Windows files.

If the repository is on Windows, do not use a Remote WSL window, but instead use a regular window with Git for Windows.

If the repository is on WSL, use the Remote WSL window.

**Comment by victron** [comment]
Based on this post [Do not change Linux files using Windows apps and tools](https://devblogs.microsoft.com/commandline/do-not-change-linux-files-using-windows-apps-and-tools/) and some others, I were sure that this is normal.
I suspect that I need to use some setting, can you share them?
