### ISSUE TITLE
External Terminal broken when connected to remote WSL

### ISSUE THREAD

**Issue by jerivas** [microsoft/vscode#100815]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Open VS Code from a WSL terminal: `$ code`
2. Use the command palette or Ctrl + Shift + C to open an external terminal
3. A terminal window should open, but nothing happens

Launching from cmd.exe or PowerShell produces the expected results.

Does this issue occur when all extensions are disabled?: Yes/No

This can't be tested properly without extensions since the Remote WSL extension is required to open WSL projects

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.34GB free)|
|Process Argv|--remote=wsl+Ubuntu-20.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz (8 x 2711)|
|Memory (System)|5.80GB (0.92GB free)|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-rename-tag|for|0.1.3
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
language-liquid|nei|0.1.1
jinjahtml|sam|0.13.0
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
open-in-browser|tec|2.0.0
calculate|aca|2.1.0
vscode-django|bat|0.20.0
git-easy|bib|1.11.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.0
gc-excelviewer|Gra|3.0.36
docthis|joe|0.7.1
php-cs-fixer|jun|0.1.154
vscode-liquid-snippets|kil|1.3.0
vscode-autoprefixer|mrm|3.0.1
python|ms-|2020.6.89148
language-liquid|nei|0.1.1
incrementor|nms|0.1.0
csv-to-table|php|1.2.3
vscode-sort-json|ric|1.18.0
stylelint|shi|0.51.0
vscode-fileutils|sle|3.0.1
code-spell-checker|str|1.9.0
rst-vscode|tht|3.0.1
sort-lines|Tyr|1.9.0
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.1.0

(1 theme extensions excluded)

</details>

**Comment by Gameghostify** [comment]
Can confirm, running the command does nothing for me as well

**Comment by Tyriar** [comment]
I see this in only some windows:

```
ERR spawn C:\WINDOWS\system32\cmd.exe ENOENT: Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by Tyriar** [comment]
Looked into this, no idea why this is happening, it's running on the Windows side so cmd.exe is there 🤷

**Comment by lionseal** [comment]
Yesterdays update broke it again, executing the external terminal hotkey (Ctrl + Shift + C) while in a WSL session does nothing. 
Aslo, I always use [cmder](https://cmder.net/) as my external terminal with the following settings on vscode 
`"terminal.external.windowsExec": "C:\\cmder\\Cmder.exe"`
It almost works but something strange is happening
![image](https://user-images.githubusercontent.com/2295236/107048988-57321a00-67a8-11eb-98b4-1287e9c358d3.png)

**Comment by denchii** [comment]
Same when trying to open any external terminal from vscode connected to WSL.

![image](https://user-images.githubusercontent.com/7037552/107241539-1eaa6e80-6a3c-11eb-9ff3-68f1c8d6e15d.png)

<details>
<summary>System info</summary>
<br>

CPUs | Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz (4 x 3193)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 31.87GB (20.70GB free)
Process Argv | --crash-reporter-id 7d0f3433-f366-4405-acf0-4b5af60a41e8
Screen Reader | no
VM | 0%

Remote | WSL: Ubuntu-18.04
-- | --
OS | Linux x64 4.19.104-microsoft-standard
CPUs | Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz (4 x 3192)
Memory (System) | 24.96GB (22.05GB free)
VM | 0%

</details>
<details>
<summary>Extensions</summary>

Extension | Author (truncated) | Version
-- | -- | --
output-colorizer | IBM | 0.1.2
dotenv | mik | 1.0.1
remote-containers | ms- | 0.158.0
remote-ssh | ms- | 0.63.0
remote-ssh-edit | ms- | 0.63.0
remote-wsl | ms- | 0.53.2
vscode-remote-extensionpack | ms- | 0.20.0
vscode-icons | vsc | 11.1.0
material-theme | zhu | 3.9.13
Bookmarks | ale | 12.1.4
toml | be5 | 0.5.1
cmake-format | che | 0.6.11
markdown-table-prettify | dar | 3.2.0
vscode-markdownlint | Dav | 0.38.0
githistory | don | 0.6.14
gitlens | eam | 11.2.1
prettier-vscode | esb | 5.9.1
auto-comment-blocks | kev | 1.0.1
cortex-debug | mar | 0.3.11
goto-next-previous-member | mis | 0.0.5
python | ms- | 2021.1.502429796
vscode-pylance | ms- | 2021.2.0
jupyter | ms- | 2020.12.414227025
cmake-tools | ms- | 1.5.3
cpptools | ms- | 1.2.0
autodocstring | njp | 0.5.4
markdown-preview-enhanced | shd | 0.5.16
cmake | twx | 0.0.17
debug | web | 0.25.0
change-case | wma | 1.0.0
clang-format | xav | 1.9.0
markdown-all-in-one | yzh | 3.4.0

</details>

**Comment by Tyriar** [comment]
Figured it out thanks to this comment https://github.com/Microsoft/vscode/issues/28271#issuecomment-308592929, we're passing the active file as the CWD but it's a remote wsl path not a native path.

**Comment by Tyriar** [comment]
Couldn't test this easily not in product build. Need to verify on Windows:

- Empty local workspace
  - Open a new window with no folder
  - Open external terminal should open the home directory
  - Open a file
  - Open external terminal should open the file's directory
- Local workspace
  - Open a new window with a folder
  - Open external terminal should open the workspace directory
  - Open a file
  - Open external terminal should open the workspace directory
- Empty remote workspace
  - Open a new WSL workspace with no folder that's never had a _local_ file opened
  - Open external terminal should open the home directory
  - Open a remote file
  - Open external terminal should open the local version of the remote file (ie. something like `/mnt/d/GitHub/microsoft/vscode`)
  - Open a local file
  - Open external terminal should open the local file's directory
- Remote workspace
  - Open a new WSL workspace with a folder that's never had a _local_ file opened
  - Open external terminal should open the local version of the remote workspace folder
  - Open a remote file
  - Open external terminal should open the local version of the remote workspace folder
  - Open a local file
  - Open external terminal should open the local version of the remote workspace folder
