### ISSUE TITLE
This is really important to me

### ISSUE THREAD

**Issue by sakilahmmad71** [microsoft/vscode#100876]
Actually I use visual studio code for a long time, sometimes I need to open multiple instances at a time and I got lost which instance I need to work with. If every instance has a different color on the menu bar that could be easier for me and us.
Thank you

**Comment by roblourens** [comment]
You might find this extension useful, it lets you pick custom theme colors per workspace window: https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock
