### ISSUE TITLE
Is it possible debug one language when other Language Server is installing.

### ISSUE THREAD

**Issue by jerryzhoujw** [microsoft/vscode#100898]
>  [![enter image description here][1]][1]

> How can I know how long will this finished: 

> 'Installing Kotlin Language Server'

> I `can't debug` on device now, because of this installing didn't finished.

> Can I stop it ?  

>  Because my project didn't include Kotlin part, it's just java for android part.

So, is it possible debug with flutter even when other Language Server is installing ?

  [1]: https://i.stack.imgur.com/viiFB.png

**Comment by jerryzhoujw** [comment]
Restart computer not solve this. it still become  `Installing`.

Is it possible to show progress (like percent:  20%) ?    I waiting for a while now, but I don't know when it can be finished.

**Comment by jerryzhoujw** [comment]
By some one's help,  I disabled the extensions:  Kotlin & Kotlin Language.   Then this downloading stopped.   Temp solve my proglem.

**Comment by dbaeumer** [comment]
@jerryzhoujw please report installing issue against the Kotlin extension you are using.
