### ISSUE TITLE
Launch remote development (SSH/WSL) by default when starting VSCode

### ISSUE THREAD

**Issue by tigerinus** [microsoft/vscode#100813]
After starting VSCode, it launches remote development connected to SSH/WSL by default.

Yes, I know I could pin a remote project and achieve what I want by opening that project from Recent Projects in Start menu. But that's different.

I have tons of projects in a remote SSH server. Sometime I want to get connected remotely first and navigate around in the integrated terminal before knowing which project to open.

Yes, I know I could first SSH to my server using a terminal and open the project in VSCode once I know which project I want to open. But that's different.

It requires a second app (the 'terminal' app) and I would still need to open VSCode with a local environment by default and connected to SSH remote environment. Simply a lot of steps.

Plus I love that in VSCode integrated terminal that I can MOUSE L on path with CTRL held and open it immediately. None of the terminal app supports that so far.

**Comment by weinand** [comment]
You can configure VS Code to reopen your last open project. If this project was a remote (WSL/SSH) project, then you are in remote development when starting VS Code.

**Comment by tigerinus** [comment]
@weinand - you missed my comment. :)

"I have tons of projects in a remote SSH server. Sometime I want to get connected remotely first and navigate around in the integrated terminal before knowing which project to open."

I could do what you suggested - appreciated - but not every project is a small project.
