### ISSUE TITLE
Unable to dynamically set pod name in pipeTransport

### ISSUE THREAD

**Issue by napalm684** [microsoft/vscode#100831]
I am trying to debug kubernetes dotnet core pods (running vscode in wsl2) and it works if I hard code the pod name in, but using an acceptable Linux command to retrieve it does not (see below):

```
        {
            "name": "Attach in k8s",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickRemoteProcess}",
            "justMyCode": false,
            "requireExactSource": false,
            "pipeTransport": {
                "pipeProgram": "kubectl",
                "pipeArgs": [
                    "exec -i -n my-service $(kubectl get pods -n my-service -o name | grep -Po '\\\/\\K.+') --"
                ],
                "quoteArgs": false,
                "debuggerPath": "/vsdbg/vsdbg"
            },
            "sourceFileMap": {
                // For debugging you must copy source code into the app folder and point at the local folder with those
                // source items
                "/app": "${workspaceFolder}/MyService.Web"
            }
        }
```

It randomly tells me valid kubectl flags don't exist. I have tried to use ```pipeTransport.pipeEnvs``` with no luck as it is not documented.  I have tried to use input variables also with no luck here. Also environment variables have not been able to resolve this. Lastly, creating a prelaunch task did not set an environment variable for me to use here.

**Comment by weinand** [comment]
<speculation on>
Since this issue was filed against "microsoft/vscode-remote-release" I assume that you are using VS Code's "Remote Development" and "Remote Container" extensions. But if this is true, I'm not sure that configuring a "pipeTransport" is the correct approach. With VS Code's "Remote Development" it should be possible to use a setup that works locally without changes in a remote setup.
<speculation off>

Please file this issue against the C# extension because "pipeTransport" is not a VS Code concept but a feature of the C# debugger.

**Comment by chrmarti** [comment]
@weinand I wasn't sure if this is related to Remote Development.

@napalm684 Is this while connected via Remote-WSL? (Since you mention "running vscode in wsl2".)

**Comment by napalm684** [comment]
@chrmarti Yes it is while running vscode in wsl2 with the remote-wsl plugin.  However, running on windows does have the same issue.

**Comment by napalm684** [comment]
If I need to open this elsewhere please let me know. I don't want this item to fall in a "black hole".

**Comment by weinand** [comment]
As already said above:

> Please file this issue against the C# extension because "pipeTransport" is not a VS Code concept but a feature of the C# debugger.

This item is closed.
