### ISSUE TITLE
Go to Definition Does Not Work

### ISSUE THREAD

**Issue by jcrawford** [microsoft/vscode#100881]
Issue Type: <b>Bug</b>

1. Open PHP File
2. Cmd-Click a class name
3. Notice nothing happens

1. Put your mouse cursor on a class name
2. Hit F12 of Go -> Go to Definition
3. Again notice nothing happens

Does this issue occur when all extensions are disabled?: Yes
I launched code with --disable-extensions and encountered the same issue.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|50, 58, 58|
|Memory (System)|16.00GB (1.11GB free)|
|Process Argv|-psn_0_4641901|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
svelte-intellisense|ard|0.7.1
markdown-mermaid|bie|1.5.1
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.1.4
vscode-eslint|dba|2.1.5
es7-react-js-snippets|dsz|2.8.0
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.0
vscode-svelte-snippets|fiv|0.4.0
phpcs|ika|1.0.5
svelte-vscode|Jam|0.9.3
vscode-peacock|joh|3.7.2
vscode-styled-components|jpo|0.0.29
php-cs-fixer|jun|0.1.154
chat|kar|0.35.0
laravel-intellisense|moh|0.1.5
vscode-docker|ms-|1.3.1
python|ms-|2020.6.89148
vsliveshare|ms-|1.0.2354
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.8
indent-rainbow|ode|7.4.0
LiveServer|rit|5.6.1
mdx|sil|0.1.0
sass-indented|syl|1.8.6
vscode-open-in-github|sys|1.14.0
tabnine-vscode|Tab|2.8.6
lorem-ipsum|Tyr|1.2.0
highlight-matching-tag|vin|0.9.9
quokka-vscode|Wal|1.0.301
vscode-preview-server|yui|1.3.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.1.0

</details>

**Comment by mjbvz** [comment]
Please file this against your php extension

**Comment by jcrawford** [comment]
It's VSCode without any extensions enabled so why would I file against a PHP extension that is not in use?
