### ISSUE TITLE
Mac Pro 5,1 - Heavily Upgraded Crashes - Kernel CPU 11 Caller (Panic Report)

### ISSUE THREAD

**Issue by dawoodbush** [microsoft/vscode#100888]
Hi all,

Was hoping you could help me - I recently purchased this Mac Pro 5,1 and it has crashed twice in 4 days for no apparent reason. Please find attached System Specs and Problem report that I got. 

Please note, I also have a 1 TB SSD installed. 

Thanks,

![Screenshot 2020-06-23 at 22 55 54](https://user-images.githubusercontent.com/67345863/85471025-c3f4fd00-b5a7-11ea-893b-4d75e3ca3ee4.png)
![Screenshot 2020-06-23 at 23 18 11](https://user-images.githubusercontent.com/67345863/85471057-d2431900-b5a7-11ea-952b-b316947fbf39.png)

**Comment by deepak1556** [comment]
which version of vscode are you running ?

Can you try the insiders version https://code.visualstudio.com/insiders/

**Comment by dawoodbush** [comment]
> which version of vscode are you running ?
> 
> Can you try the insiders version https://code.visualstudio.com/insiders/

Hey - what is this? I've not downloaded any type of vscode

**Comment by deepak1556** [comment]
Oh i was under the impression the issue was caused by vscode. There is nothing we can do here if its not vscode. Thanks!

**Comment by dawoodbush** [comment]
Oh sorry! Is this thread/page just relating to vs code?

**Comment by deepak1556** [comment]
Yup this issue tracker is for the https://code.visualstudio.com/ project.

**Comment by dawoodbush** [comment]
Thanks - do you know where best I can get my query resolved?
