### ISSUE TITLE
"Bad progress location: workbench.view.debug"

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#100847]
I moved my debug adapter over to using the new progress support. I'm sure it was working when I did it, but now it's giving this error:

![Screenshot 2020-06-23 at 14 32 13](https://user-images.githubusercontent.com/1078012/85409923-5a043580-b55e-11ea-8a86-332ed12361ce.png)

I'm sending the first `ProgressStartEvent` during the `launchRequest`.

**Comment by isidorn** [comment]
@DanTup thanks for filling this. Is it possible that you create a fork of Mock Debug that reproduces this so we can investigate further on our side?
Alternativly you can put a breakopint [here](https://github.com/microsoft/vscode/blob/59bb4e1f5061ebbfbcfac46ac3878bb82d91a0ee/src/vs/workbench/contrib/debug/browser/debugProgress.ts#L37) and investigate more what is going on.

Also do you have the debug view open when this happens?

**Comment by DanTup** [comment]
Looks like it might be intermittent - I was just going to try and debug (or revert my change for now), but it's not happening (even with the debug view not visible).

Any thoughts on what else could effect it?

**Comment by isidorn** [comment]
@DanTup not sure what would cause it.
@bpasero might you have ideas why the progressService would not find the workbench.view.debug location?

**Comment by bpasero** [comment]
@isidorn if any of these conditions holds true:

https://github.com/microsoft/vscode/blob/2b766557a7f0c0a9f29c854e5b4494f4915575ee/src/vs/workbench/services/progress/browser/progressService.ts#L52-L64

**Comment by eamodio** [comment]
My fix was making a change to ensure I wouldn't try doing work (and showing progress) when the view itself was hidden.

**Comment by isidorn** [comment]
Ok, maybe I should do the same.

**Comment by DanTup** [comment]
FWIW - I saw this again - I think it's only happening on the very first debug session. After I've launched one, the next one doesn't report the error (even if the debug side bar is not visible). If I Reload Window and then run again, I see the error again.

**Comment by isidorn** [comment]
I pushed the same fix that @eamodio did. I only report progress if the viewlet is visible.
Though it would be nicer if the `progressService` was handling this so that every client would not need to check visibility @bpasero

**Comment by DanTup** [comment]
Thanks! Are Insiders builds paused right now? I just updated (to test something else, merged yesterday) but the latest build is from 23rd.

**Comment by isidorn** [comment]
@DanTup I believe we have some errors which my collegues are looking into and we shuold have insiders builds back up and running.

**Comment by bpasero** [comment]
I did not add this error, I think originally @jrieken did. Should we simply put progress globally if someone (including an extension) shows progress on a view that does not exist?

**Comment by isidorn** [comment]
@bpasero for my use case it should simply be not shown and silently fail.
Because I put the progress in the view and globally already on my own.

**Comment by DanTup** [comment]
I presume in this case the progress text will still appear on the status bar, just not the blue animation on the debug sidebar?

**Comment by isidorn** [comment]
@DanTup correct.

**Comment by bpasero** [comment]
There does not seem to be a way to know if a progress location exists as view/panel/container or not, so I am not sure how to fix this currently. Code pointer if someone wants to pick this up:

https://github.com/microsoft/vscode/blob/0bbc57993bf2dc639d5bb415f5bceff2bc942ce4/src/vs/workbench/services/progress/browser/progressService.ts#L51-L65

**Comment by sandy081** [comment]
Seems ok to me.

**Comment by DanTup** [comment]
Seems to be working correctly in Insiders now, thanks!
