### ISSUE TITLE
Preview Image Markdown

### ISSUE THREAD

**Issue by gabpmcp** [microsoft/vscode#100874]
The system throws the following error when loading image in markdown file:

An error occurred while loading the image.

Open file using VS Code's standard text/binary editor?

The link for open the image with VS Code's standard doesn't work.

![image](https://user-images.githubusercontent.com/48138794/85435238-c5450c00-b54c-11ea-8357-7e8b482948de.png)

In VS Code release version it works:

![image](https://user-images.githubusercontent.com/48138794/85435285-d857dc00-b54c-11ea-9e86-13e966e9de07.png)

Thanks for your help.

**Comment by mjbvz** [comment]
Duplicate of #100879
