### ISSUE TITLE
Open Intergrated Terminal  Crash on None-English Folder

### ISSUE THREAD

**Issue by mzvast** [Microsoft/vscode#10086]
- VSCode Version:1.3.1
- OS Version:Windows 10Pro x64 14393 and Windows 10Ent x64 10240

Steps to Reproduce:

1. Create a folder with a None-English Name,for instance, "你好世界helloWorld"
2. Right click on this folder and open in vscode.
3. Press `Ctrl + `` and Terminal Crash with exit code 1.
Same error in Atom which is also Electron-based.
The Error Code in vscode is useless,while in Atom,the error code shows as following:

`C:\Users\mzvast\AppData\Local\atom\app-1.9.1\resources\app.asar\src\task.js:52 Unable to start terminal process. Win32 error code: 267 Error: Unable to start terminal process. Win32 error code: 267
at Error (native)
at Server. (C:\Users\mzvast.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty_win.js:67:9)
at emitOne (events.js:90:13)
at Server.emit (events.js:182:7)
at Pipe.onconnection (net.js:1439:8)
(anonymous function) @C:\Users\mzvast\AppData\Local\atom\app-1.9.1\resources\app.asar\src\task.js:52
(anonymous function) @C:\Users\mzvast\AppData\Local\atom\app-1.9.1\resources\app.asar\src\task.js:126
module.exports.Emitter.simpleDispatch @ C:\Users\mzvast\AppData\Local\atom\app-1.9.1\resources\app.asar\node_modules\event-kit\lib\emitter.…:25
module.exports.Emitter.emit @ C:\Users\mzvast\AppData\Local\atom\app-1.9.1\resources\app.asar\node_modules\event-kit\lib\emitter.…:125
(anonymous function) @ C:\Users\mzvast\AppData\Local\atom\app-1.9.1\resources\app.asar\src\task.js:78emitTwo @ events.js:100
emit @ events.js:185
handleMessage @ internal/child_process.js:718
channel.onread @ internal/child_process.js:444`

The win32 error code 267 seem to be,according to [microsoft:](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx)
```
ERROR_DIRECTORY
267 (0x10B)
The directory name is invalid.
```

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7727
