### ISSUE TITLE
Remote Container Visual Studio Code Not Starting

### ISSUE THREAD

**Issue by kevinstevanus** [microsoft/vscode#100808]
- VSCode Version: 1.47.0-insider build
- OS Version:
Windows 10 Ver 2004

Steps to Reproduce:

1. Open Visual Studio Insider
2. Install "Remote - Container" extension
3. Docker already running
4. cloning this project https://github.com/microsoft/vscode-remote-try-go
5. open the project in remote mode like in this [gif](https://i.imgur.com/MDjH5Ki.gifv)
6. the remote server will stuck as shown as in the gif

sidenote:
opening the remote container in regular vscode have no problem at all[gif](https://i.imgur.com/kgpYmGd.gifv)
 and..
this is what would pop up when im using regular vscode, but it didnt popup when using insider build

![image](https://user-images.githubusercontent.com/37767069/85352515-5e195e80-b530-11ea-8048-8fe63021181e.png)
this image trigger happen when i start the remote server for the first time.

Does this issue occur when all extensions are disabled?: Yes/No
i dont know, the problem is requiring the extension itself

**Comment by chrmarti** [comment]
Issue in VS Code Insiders. VS Code 1.46.x should work.

Tracking with https://github.com/microsoft/vscode/issues/100822.
