### ISSUE TITLE
Intellisense for javascript function results

### ISSUE THREAD

**Issue by JulianKingman** [microsoft/vscode#100896]
Given these objects:
```javascript
const obj1 = { a: 1 };
const obj2 = () => ({ b: 2 })();
```
I would like IntelliSense to detect the contents of obj2. Is this possible? Currently it doesn't work.
To give an idea of why this would be useful, I generate various permutations of padding and margins, by combining an array of sizes with an array of keys (e.g. `marginTop`), so that I can type `margin.top.md` and get { marginTop: 30 }, or `padding.vertical.sm` etc... less duplication, less potential for errors, but for now it seems I have to use a plain object.

**Comment by yume-chan** [comment]
Because your code is invalid.

`() => ({ b: 2 })();` equals to `() => { return ({ b: 2 })(); }`

Should be `(() => ({ b: 2 }))();`

**Comment by JulianKingman** [comment]
Sorry, the example was contrived, but in my codebase I don't have this typo, and intellisense till doesn't get the result of functions. Can this be opened?

**Comment by mjbvz** [comment]
Seems to work for me?

<img width="771" alt="Screen Shot 2020-07-15 at 4 39 23 PM" src="https://user-images.githubusercontent.com/12821956/87610256-bff56000-c6b9-11ea-8bd6-cc117c54c95e.png">
