### ISSUE TITLE
Unable to find Project.Jsong or CSPROJC

### ISSUE THREAD

**Issue by budspogi** [microsoft/vscode#100845]
I think after the installation of new update  I got this error. I could not create an interface or class in my angular project.

- VSCode Version: 1.46.1
- OS Version: Windows 10

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No
![image](https://user-images.githubusercontent.com/35502387/85408107-27196c00-b575-11ea-8a7b-23b1995102ad.png)

**Comment by dbaeumer** [comment]
Do you have the C# extension installed?

**Comment by budspogi** [comment]
yes.. the C# extension is installed.. I uninstall and install again but still the same problem.

**Comment by dbaeumer** [comment]
Please report the problem to the owner of the C# extension.
