### ISSUE TITLE
Insert Snippet Shortcut not Working

### ISSUE THREAD

**Issue by KyleMit** [microsoft/vscode#100884]
Issue Type: <b>Bug</b>

## Steps to Reproduce

1. Map `editor.action.insertSnippet` to any keybinding (ex. <kbd>Ctrl</kbd> + <kbd>;</kbd>)
2. Invoke via Keybinding - nothing happens
3. Invoke via Command Palette - relevant snippets are shown

## Demo

[![Insert Snippet Demo][1]][1]

## Further Info

This issue on [Insert Snippet Shortcut not Working #92909](https://github.com/microsoft/vscode/issues/92909) does seem to run into the same issue and resolves by using `editor.action.showSnippets`.  However, this issue [showSnippets renamed to insertSnippet #18314](https://github.com/Microsoft/vscode/issues/18314) suggests they should be the same command, with `insertSnippet` being newer.

Indeed, when I map the command to use `showSnippets` instead, the keyboard shortcut *does* work, but I'm curious if that's the correct approach I should be taking

## System Info

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

Thanks! 

[1]: https://user-images.githubusercontent.com/4307307/85461144-056ab580-b572-11ea-90a7-499bf2326fc9.gif

**Comment by jrieken** [comment]
Works for me. Please open the keybindings editor source (the JSON file via the title bar action) and share the exact config. This works

```
    {
        "key": "cmd+;",
        "command": "editor.action.insertSnippet",
    },
```
