### ISSUE TITLE
document.createElement shows as deprecated

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#100878]
All instances of it are crossed out and marked as deprecated, but I think the d.ts is trying to say that only one of the multiple function signatures is deprecated

![image](https://user-images.githubusercontent.com/323878/85442757-21f8f480-b556-11ea-9323-da3bfac5a3e9.png)

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/39212 to track this upstream. We still have a few iterations before we ship TS 4.0 so hopefully this can be addressed
