### ISSUE TITLE
Symbolic Function, Cant Map Object Instance function:

### ISSUE THREAD

**Issue by arcanisgk** [microsoft/vscode#100902]
- VSCode Version: Lastest
- OS Version: Windows 10 Pro 2004

Steps to Reproduce:

1. Install Intellisense or intelephense Extention
1. download this repository: https://github.com/arcanisgk/test-code-style/
2. open VSCode, open the directory and create a workpace.

Does this issue occur when all extensions are disabled?: verified both ways (Yes / No)

I am new to programming in php; But I love the tools that editors have and I can't believe that something so usable is not yet or cannot get the best out of it as I like.

I have been told that in VSCode I can search for functions with symbolic links Like this:

`Core_App::$obj_class['GEN']['VARSMANAGER']->VarExport(Core_App::$obj_class);`

or that was what little I understood; but it is not what I expected; when I use the `F12`; It does not send me to the definition of the function and I am forced to use:

`CTRL+SHIFT+F`
or
`CTRL+T`

I have tested the extensions mentioned above and they do not have this functionality either.
I did tests with Sublime Text 3 and the sublimePHPIntel plugin and guess what ... if you have it ...

I leave you the examples:
(note: in sublime 3 definitions were found because I have 3 projects that use similar libraries and are all under the same workspace)

VSCode:

![image](https://user-images.githubusercontent.com/1207306/85494828-1120a100-b59f-11ea-9677-0c619407119a.png)

Sublime + plugin

![image](https://user-images.githubusercontent.com/1207306/85494868-1f6ebd00-b59f-11ea-99a9-601d24343dda.png)

**Comment by dbaeumer** [comment]
Since this needs to come from a PHP please file the issue against the PHP plugins you tested.

**Comment by arcanisgk** [comment]
> Since this needs to come from a PHP please file the issue against the PHP plugins you tested.

why they close the issues clearly explains what happens with and without extensions.
`Go to Definition`
and
`Go to Reference`

not Work with Symbolic object. can check the repository example.
