### ISSUE TITLE
Git Bash exits with error

### ISSUE THREAD

**Issue by yiannis-had** [microsoft/vscode#100917]
Issue Type: <b>Bug</b>

- Open Terminal ( Ctrl + ` ) . Mine defaults to git bash.
- Type something and either press Enter or Ctrl + C.
- Press Ctrl + D to exit the terminal

Image of bug: https://i.imgur.com/xeTjvDS.png

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (24.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.6.89148
vscodeintellicode|Vis|1.2.8

</details>

**Comment by Tyriar** [comment]
ctrl+d exits with a non-zero code so it's working as designed. You can suppress these notifications if you want via `"terminal.integrated.showExitAlert": false`
