### ISSUE TITLE
Code – Helper (Renderer)

### ISSUE THREAD

**Issue by gordinmitya** [microsoft/vscode#100945]
Issue Type: <b>Performance Issue</b>

1. Install the latest stable or insiders' version from the official site on MacOS. (I use Macbook Pro Early 2015)
2. No additional extension, configurations, nothing. Just blank installation.
3. Open any project (I experience the issue with https://github.com/google/mediapipe repo).
4. Open several files BUILD, *.java, …
5. Listen to your fans spins like crazy.
6. Open Activity Monitor and find Code – Helper (Renderer) consumes an enormous amount of CPU.

<img width="437" alt="Screenshot 2020-06-24 at 2 19 19 PM" src="https://user-images.githubusercontent.com/9286092/85546921-107f1d80-b626-11ea-8f3b-cb02ddccde2c.png">

I don't understand why similar issues were closed #87509 – a lot of people report facing the same issue, there's no any solution. This makes VSCode just useless.

Hope you investigate that. Thank you in advance! 
I'll be happy to provide you any additional information necessary to find the cause of this issue.  

VS Code version: Code - Insiders 1.47.0-insider (0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69, 2020-06-23T09:38:28.751Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 5|
|Memory (System)|8.00GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	    90	 31029	code-insiders main
    9	    57	 31030	   gpu-process
    0	    25	 31032	   utility
    0	   238	 31033	   window (MainActivity.java — mediapipe)
    0	    57	 31060	     extensionHost
  155	   524	 31061	     watcherService
   18	    90	 31062	   shared-process
    0	     0	 31087	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    7	    74	 31085	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (MainActivity.java — mediapipe)
|    Folder (mediapipe): 1959 files
|      File types: cc(507) h(327) proto(172) png(111) pbtxt(87) md(65)
|                  java(47) gif(40) mm(26) m(23)
|      Conf files: makefile(1);
```

</details>
Extensions: none

**Comment by gordinmitya** [comment]
Followed [the guide](https://github.com/Microsoft/vscode/wiki/Performance-Issues) mentioned by @jrieken in #100401 

All extensions manually disabled as described in the guide.
Here is the output:
```
Version:          Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS Version:       Darwin x64 19.4.0
CPUs:             Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)
Memory (System):  8.00GB (0.09GB free)
Load (avg):       5, 5, 5
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	    90	 31355	code main
    0	    57	 31356	   gpu-process
    0	    25	 31359	   utility
    0	   262	 31360	   window (MainActivity.java — mediapipe)
    0	    57	 31396	     extensionHost
   78	   745	 31397	     watcherService
    0	    98	 31398	   shared-process
    0	     0	 31486	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (MainActivity.java — mediapipe)
|    Folder (mediapipe): 1959 files
|      File types: cc(507) h(327) proto(172) png(111) pbtxt(87) md(65)
|                  java(47) gif(40) mm(26) m(23)
|      Conf files: makefile(1)
```

**Comment by gordinmitya** [comment]
From developer tools performance monitor (sorry, I'm not sure what should I provide here)

<img width="346" alt="Screenshot 2020-06-24 at 2 39 31 PM" src="https://user-images.githubusercontent.com/9286092/85549305-85ebed80-b628-11ea-80cb-5ce2eb0c4587.png">

<img width="1235" alt="Screenshot 2020-06-24 at 2 43 13 PM" src="https://user-images.githubusercontent.com/9286092/85549846-0e6a8e00-b629-11ea-84d0-46f1f6364055.png">

**Comment by gordinmitya** [comment]
<img width="1063" alt="Screenshot 2020-06-24 at 2 45 55 PM" src="https://user-images.githubusercontent.com/9286092/85550245-70c38e80-b629-11ea-9039-400c653b6bdf.png">

Performance monitor don't show anything

**Comment by gordinmitya** [comment]
Please guide me how can I help you fixing this!

**Comment by jrieken** [comment]
Looks like file watching issue

<img width="681" alt="image" src="https://user-images.githubusercontent.com/1794099/85553088-eb89ab00-b623-11ea-9fa7-21383bb37724.png">
