### ISSUE TITLE
BigInt literals are not available when targeting lower than ES2020

### ISSUE THREAD

**Issue by paulmillr** [microsoft/vscode#100987]
- VSCode Version: 1.46
- OS Version: macos-latest

Steps to Reproduce:

1. Create js file with bigints like `12345n`
2. Check out "problems" tab. It would highlight the number and throw the error: "BigInt literals are not available when targeting lower than ES2020"

Creating jsconfig.json with target: es2020 doesn't help. 

The issue doesn't happen if you use same target with typescript code / tsconfig. Happens only with JS files

**Comment by mjbvz** [comment]
Are you sure your js file part of your `jsconfig`. Run `JavaScript: Go to project configuration` in the js file to check
