### ISSUE TITLE
Mark all occurrences of alias named property depends on which token I click first

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#100996]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.0.0-dev.20200624

**Search Terms**
- documentHighlights

---

```ts
interface Foo {
	prop: number;
}

function bar(arg: Foo) {}

const prop = 123;
bar({ prop });
```

![recording (5)](https://user-images.githubusercontent.com/22350/85024519-7a0ab200-b176-11ea-8c10-ec8e4d0f5b6c.gif)

I think that when I select `prop` on line 8, all occurrences of `prop` should be highlighted, independently of having clicked `prop` elsewhere right before.

**Comment by mjbvz** [comment]
@alexdima I believe this code is why the requests are not fired again: 

https://github.com/microsoft/vscode/blob/2f367a51c364c1cb95865960de29bfd82cb94776/src/vs/editor/contrib/wordHighlighter/wordHighlighter.ts#L88

I'm assigning to you since you've touched these files recently but please reassign if there is a better owner

**Comment by alexdima** [comment]
PR welcome. That code was written at a time when document highlights were transitive in TS :).

**Comment by CyrusNajmabadi** [comment]
> and @CyrusNajmabadi if this is something that you're considering changing in VS Code.

Currently, Roslyn's take is that these are transitive (i believe).  So we are fine with teh current behavior and aren't asking for it to change.  I do see TS/Js's perspective here.   My major concern is that one could be navigating through the highlights, and then get to an item that causes there to be *less* highlights.  That would then break the ability to cycle through the original set, which seems unfortunate.

**Comment by joaomoreno** [comment]
> PR welcome. That code was written at a time when document highlights were transitive in TS :).

@alexdima I've added `help-wanted`.

**Comment by CyrusNajmabadi** [comment]
As I mentioned above, I would be very wary of making such a change here. If you requery for highlights then you break the ability to cycle through all the highlights. The current behavior seems fine to me. The set of highlights is picked b based on the initial user selection, then navigation through them used that list.

**Comment by alexdima** [comment]
I agree with @CyrusNajmabadi that cycling through references with F7 is a core experience which we shouldn't break.

I've removed the help wanted. Let's avoid asking for PRs which we might not take.
