### ISSUE TITLE
Extensions: Install from VSIX... fails with "Cannot read property 'identifier' of undefined" with WSL on Insiders

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#100983]
- VSCode Version: Does not repro with non-Insiders 1.46.1
Version: 1.47.0-insider (user setup)
Commit: 0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69
Date: 2020-06-23T09:03:35.861Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041
- OS Version: Windows host, remoting to WSL2 (Ubuntu 20) -- does not repro locally on Windows.

Steps to Reproduce:

1. Run Extensions: Install from VSIX... with some vsix, such as https://github.com/microsoft/vscode-cpptools/releases/download/0.28.3/cpptools-linux.vsix .

Bug: It fails

notificationsAlerts.ts:38 TypeError: Cannot read property 'identifier' of undefined
    at extensionsWorkbenchService.ts:937
    at Array.find (<anonymous>)
    at e.installFromVSIX (extensionsWorkbenchService.ts:937)
onDidChangeNotification @ notificationsAlerts.ts:38
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
error @ notificationService.ts:59
(anonymous) @ actions.ts:97
async function (async)
(anonymous) @ actions.ts:95
invokeFunction @ instantiationService.ts:61
_tryExecuteCommand @ commandService.ts:84
(anonymous) @ commandService.ts:73
Promise.then (async)
executeCommand @ commandService.ts:73
accept @ commandsQuickAccess.ts:159
(anonymous) @ pickerQuickAccess.ts:263
fire @ event.ts:587
(anonymous) @ quickInput.ts:768
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
(anonymous) @ event.ts:56
(anonymous) @ event.ts:810
fire @ event.ts:587
_set @ listWidget.ts:167
set @ listWidget.ts:154
setSelection @ listWidget.ts:1375
onViewPointer @ listWidget.ts:617
(anonymous) @ event.ts:91
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
o @ event.ts:16
log.ts:197   ERR Cannot read property 'identifier' of undefined: TypeError: Cannot read property 'identifier' of undefined
    at file:///.../Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4326:794
    at Array.find (<anonymous>)
    at e.installFromVSIX (file:///.../Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4326:764)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sean-mcmanus** [comment]
The "Install in WSL: Ubuntu" button also fails (seems like the same root cause as the vsix install), giving...

Unable to open 'Extension: C/C++': Cannot read property 'identifier' of undefined.

After a few seconds, I find that the Windows version (with Windows binaries) have gotten copied to ~/.vscode-server-insiders/extensions/ms-vscode.cpptools-0.28.3/bin -- the extension fails on Reload Window due to the presence of the Windows binaries (instead of the Linux binaries).

It's supposed to install the vsix from the marketplace (without binaries), and then we download the Linux binaries.

**Comment by sean-mcmanus** [comment]
Now I'm getting 
![image](https://user-images.githubusercontent.com/19859882/85810622-924b7580-b710-11ea-831a-092dac836ca5.png)

**Comment by sandy081** [comment]
/duplicate

#101165 Seems related.

Please try tomorrow's insiders that will have this fix and try again
