### ISSUE TITLE
Test notebook editor input refactoring

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#100965]
Refs: https://github.com/microsoft/vscode/pull/100266

- [x] anyOS @bpasero 
- [x] anyOS @isidorn

Complexity: 2

Authors: @jrieken @rebornix 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23100965%0A%0A)

---

We have reworked how notebook editors and its inputs are managed. Test everything related to opening notebooks like open, split, pin, unpin, move, close, reopen, and (window) reload. Make sure to have rendered output when splitting or moving and ensure that you never loose the output and that you never see two outputs (webviews)

**Comment by isidorn** [comment]
Output is not preserved on reload, but I believe that is expected.
Running a query autoamticaly pins the Notebook editor but I also believe that is by design?

**Comment by jrieken** [comment]
> Have same notebook side by side, running a query in one also runs it in another. If we do this it sort of makes me feel like all state should be synced.

It depends on model state or view state, e.g when you split a text editor, typing is sync'd but find widget or selection isn't

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/101378 is pretty bad, otherwise seems to work fine 👍
