### ISSUE TITLE
Panel sizes not remembered when window border colors are set

### ISSUE THREAD

**Issue by icokk** [microsoft/vscode#100916]
- VSCode Version: 1.46.1
- OS Version: Windows 10 Pro 1903

Steps to Reproduce:

1. Set window.activeBorder and window.inactiveBorder, either in theme or in workbench.colorCustomizations
2. Maximize the main window
3. In explorer, open Outline panel and change its size
4. Restart

The Outline panel size will be reset.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@icokk cannot reproduce. are you opening the same workspace when you restart?

**Comment by icokk** [comment]
Yes, I'm restarting with the same workspace. All extensions are disabled with --disable-extensions and the settings.json is just
```
{

   "workbench.colorCustomizations": {
       "window.activeBorder": "#808080",
       "window.inactiveBorder": "#404040"
    }
}
```

However, I have tried the same setup in my Linux VM and the issue is not reproduced. I haven't had a chance to try it on another Windows box yret.

**Comment by sbatten** [comment]
@eamodio any ideas on how that setting would have some effect?

**Comment by eamodio** [comment]
@sbatten I can't see how this setting could affect the panel sizing -- and I can't reproduce any issue.
