### ISSUE TITLE
Lose correct comment out syntax with previous shortcut

### ISSUE THREAD

**Issue by dickkirkland** [microsoft/vscode#100961]
When using the shortcut, " Command + / " within .erb/ruby files, the shortcut gives mixed results. 
Example: using the shortcut within .erb files sometimes produces a ruby comment, "<%#=", when only trying to generate a basic HTML comment like,  or doesn't work at all.

Another comment type appears is the "#" that doesn't comment out code. This may be VS Code's attempt at trying to perform a type of ruby comment.

I may be mistaken, but thought that previously, the shortcut produced the correct type of comment based on the context of the type of code commented.

Any help would be appreciated.

**Comment by aeschli** [comment]
The built-in ruby extension (also registered for ".erb") only uses `#` to comment single lines, and "=begin", "=end" for blocks.

Maybe you have additional extensions installed?

Also if you can add small code sample with information on what you see and what you expect, that would be great.

**Comment by dickkirkland** [comment]
@aeschli Thanks for the explanation of the built-in ruby extension. 

After talking with my coworkers, they report that the commenting for .erb(s) has always been this way, most of the time using the ruby comments.
```<%# <div class="form-row"> %>```. It is working in this way today and does the job of commenting.

I have a minor amount of extensions installed. The single `#` I witnessed may have been a glitch or an attempt by Code to comment out a snippet that was not a valid context.  Forgive my ignorance with this issue. I'll continue to monitor. 

Have a great day.
