### ISSUE TITLE
Test: noDebug debugSessionOptions API

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#100963]
Refs: https://github.com/microsoft/vscode/issues/99743

- [x] anyOS @connor4312 
- [x] anyOS @jrieken

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23100963%0A%0A)

---

We have introduced a new `noDebug` flag to the `debugSessionOptions` API. So get a VS Code starter extension, call the [`startDebugging`](https://github.com/microsoft/vscode/blob/7c5ed41e731c65532ee8da326c9f124fe1ba838c/src/vs/vscode.d.ts#L11112) api and pass the `DebugSessionOptions` such that you can verify the `noDebug` flag works as expected:
* if `noDebug` is present and set to `true`, no breakpoints should be hit when running the program
* if `noDebug` is set to `false`, breakpoints should be respected and hit
* if `noDebug` is not set the sessions should respect whatever was set to its parent session (if it exists).

Note: a simple way to use the `startDebugging` api is to simply pass the workspace folder and the name of an already existing launch configuration in your `launch.json`.

**Comment by jrieken** [comment]
I have the snippet below but when I open a workspace with a launch config names "Run Extension" nothing happens. How do i test this?

```ts
vscode.commands.registerCommand('extension.helloWorld', async (args) => {
	try {
		const session = await vscode.debug.startDebugging(undefined, 'Run Extension', { noDebug: true })
		console.log('DEBUG', session)
	} catch (err) {
		console.error(err);
	}
});
```

**Comment by isidorn** [comment]
@jrieken this snippet works fine for me if I pass the `workspaceFolder` like this
`const session = await vscode.debug.startDebugging(vscode.workspace.workspaceFolders![0], 'Hello There', { noDebug: true })`

We should handle the `undefined` case better when the name is passed. Can you file an issue for that please?

**Comment by jrieken** [comment]
Thanks for clarifying. Now it proceeded but it still debugs: https://github.com/microsoft/vscode/issues/101413
