### ISSUE TITLE
renameOnType conflicts with emmet on undo after expansion

### ISSUE THREAD

**Issue by jjspace** [microsoft/vscode#100974]
- VSCode Version: 1.46.1
- OS Version: Fedora 30

When working with emmet completions in HTML the `renameOnType` causes issues when you undo a completion. I've only tested this with basic `div` elements with class names but I suspect it causes issues elsewhere. When you do an emmet completion of a class name then undo it any further changes to the class name are duplicated and using `Backspace` is impossible as it tries to duplicate the first half of the class name. Interestingly this only seems to effect class names up to 3 characters in length. I am using the implied `div` element feature of emmet and specifying only the class name before completion and I suspect that when the undo action is triggered the first 3 character locations are still considered to be the location of the opening `div` tag when this is no longer the case causing this error. 

Steps to Reproduce:

1. open an html file (new or old)
2. type an emmet class expansion less than 3 letters (eg. `.abc`)
3. Press `Tab` (or whatever your bind is) to complete/expand using emmet
    * This should work as expected and create a div with that class name (eg. `<div class="abc"></div>`)
4. Undo that (press `Ctrl + Z`)
5. Try and modify the class name at all, especially using `Backspace`
    * See that it's considering the class name as a tag and preventing Backspace from working
    * Also notice that if you complete this again using emmet the div tag name is messed up and looks something like `<didiv class="abcd"></div>`

Does this issue occur when all extensions are disabled?: Yes

Demo: <https://imgur.com/143SaLS> (sorry for size/quality, this computer isn't set up to record)

**Comment by rzhao271** [comment]
Cannot reproduce on my setup (pasted below for reference).

Version: 1.50.0-insider (user setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T01:00:44.765Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Does this issue still persist for you after updating VS Code?
