### ISSUE TITLE
[ts] Syntax highlighting breaks when type of function returning generic type placed on newline

### ISSUE THREAD

**Issue by Sammons** [Microsoft/vscode#10092]
- VSCode Version: 1.3.1 
- OS Version: OS X El Capitan

Steps to Reproduce:

1. Enter the following code

```
export class TestGeneric<T> { }
export class TestClass {
  someFunction():
    TestGeneric<string> {
    let a = 2;// syntax highlighting broken here
    return new TestGeneric<string>();
  }
}
```

2. Or the following code:

```
export class TestGeneric<T> { }
export class TestClass {
  someFunction
    ():TestGeneric<string> {
    let a = 2;// syntax highlighting broken here
    return new TestGeneric<string>();
  }
}
```

Also note that other syntax highlighting bugs have been noticed following that first bit of wierdness, but I have a hard time reproducing those with simple code. I think once the initial bug occurs text below that can randomly have issues.

**Comment by aeschli** [comment]
Seems to be fixed with the latest grammar update

**Comment by Sammons** [comment]
@aeschli how do I get that? Will it be in a future update or something?

**Comment by aeschli** [comment]
You'll have to wait until the July build is out (beginning of next week or so). Then you can try it in the [Insider build] (https://code.visualstudio.com/insiders)
