### ISSUE TITLE
Feature request: move cursor up/down between paragraphs

### ISSUE THREAD

**Issue by danvk** [Microsoft/vscode#10093]
This would be the same as the `{` and `}` commands in vi(m):

- `}`: move to next blank line
- `{`: move to previous blank line

I find this a helpful way to move up/down in a file faster than line-by-line but slower than page-by-page.

**Comment by sandy081** [comment]
@danvk This is a good request. But this can be always achieved by writing an extension. Extension API provides all required information to come up with commands to do this and assign keyboard short cuts. This is the same approach followed by the [Vim Extension](https://github.com/VSCodeVim/Vim).

Thanks

**Comment by pgrz** [comment]
In case someone wandered here in search of this feature just like me: https://github.com/sashaweiss/vscode_block_travel

**Comment by danvk** [comment]
There's also this: https://marketplace.visualstudio.com/items?itemName=jmfirth.vsc-space-block-jumper
