### ISSUE TITLE
[loc][Query][VSCODE] Localizability of strings in vs_workbench

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#100938]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description
-- | -- | -- | -- | --
50449 | vscode-workbench\vs_workbench.xlf | 0;   "src/vs/workbench/browser/actions/layoutActions.moveFocusedView.newContainerInPanel" | New Panel Entry | Please provide more context for   this string: is it a new entry or a new panel?
50450 | vscode-workbench\vs_workbench.xlf | 0;   "src/vs/workbench/browser/parts/views/viewsService.focus view" | Focus on {0} View | Please confirm what the   placeholder replaces in order to translate it properly. Is it a number?
50455 | vscode-workbench\vs_workbench.xlf | 0;   "src/vs/workbench/browser/parts/notifications/notificationsStatus.notifications_Duplicated34" | {0} New Notifications | what will placeholder be   replaced by?
50457 | vscode-workbench\vs_workbench.xlf | 0;   "src/vs/workbench/api/browser/mainThreadAuthentication.accountLastUsedDate" | Last used this account {0} | Could you provide more info for   the placeholders?
50532 | vscode-workbench\vs_workbench.xlf | 0;   "src/vs/workbench/api/browser/mainThreadAuthentication.selectAccount" | The extension '{0}' wants to   access a {1} account | Does placeholder {1} refer to a   type or a name? We assumed a type (of the account) for now, please confirm or   advise.
50534 | vscode-workbench\vs_workbench.xlf | 0;   "src/vs/workbench/api/browser/viewsExtensionPoint.vscode.extension.contributes.view.contextualTitle" | Human-readable context for when   the view is moved out of its original location. By default, the view's   container name will be used. Will be shown | What does "Will be   shown" mean here exactly? Translated literally for now.
50554 | vscode-workbench\vs_workbench.xlf | 0;   "src/vs/workbench/electron-browser/actions/developerActions.developer_Duplicated1" | Developer | Is this string localizable? Is   developer referred to a generic developer?
50768 | vscode-workbench\vs_workbench.xlf | 0;   "src/vs/workbench/browser/parts/notifications/notificationsStatus.notifications_Duplicated34" | {0} New Notifications | Please let us know the   placeholder will be replaced with the number or not.

**Comment by dbaeumer** [comment]
@sbatten starting with you as the owner of layoutActions.ts

**Comment by sbatten** [comment]
@PDostalek added comments in the above commit.

As for 50534, "Will be shown" indicates that this value when provided by an extension author will be visible to the end user. Other properties like name have this "Will be shown" at the end as well. The translation should be the same.

For the rest I will assign owners.

**Comment by RMacfarlane** [comment]
Also added comments explaining the placeholders.

**Comment by PDostalek** [comment]
Thank you
