### ISSUE TITLE
[loc][Query][VSCODE] Localizability of strings in vs_workbench_services

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#100942]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description
-- | -- | -- | -- | --
50540 | vscode-workbench\vs_workbench_services_authentication.xlf | 0; "signInRequest" | Sign in to use {0} (1) | What do the placeholders stand   for? Please explain.
50747 | vscode-workbench\vs_workbench_services_extensions.xlf | 0;   "src/vs/workbench/services/extensions/common/extensionsRegistry.vscode.extension.activationEvents.onStartupFinished" | An activation event emitted   after the start-up finished (after all eager activated extensions have   finished activating). | Please clarify eager. Is it   localizable?

**Comment by dbaeumer** [comment]
@RMacfarlane starting with you as the owner of authentification.

**Comment by RMacfarlane** [comment]
The {0} will be replaced with an extension name. This menu item will appear under an icon that has a badge with a number, the (1) is meant to indicate that this menu entry adds to the total badge count:
![accounts_badge](https://user-images.githubusercontent.com/3672607/85755279-a6688600-b6c2-11ea-94b2-2b2cf508a56d.gif)

I've added a comment in code as well.
