### ISSUE TITLE
Cannot open files from search result editor in multi-root workspace

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/vscode#100929]
Issue Type: <b>Bug</b>

I have a multi-root workspace with this config:

```json
	"folders": [
		{
			"path": "src",
			"name": "Indico",
		},
		{
			"path": "plugins/foo",
			"name": "Plugins :: Foo"
		},
		{
			"path": "plugins/bar",
			"name": "Plugins :: Far"
		}
	],
```

When I open search results in an editor, the `src` part is incorrectly shown as part of the path:

```
Indico • src/indico/core/db/sqlalchemy/principals.py:
  95      is_event_role = False
  96:     is_category_role = False
  97      is_registration_form = False
```

And while this looks like just a cosmetic issue , it also breaks opening the file via F12/doubleclick, since the `src` now gets duplicated in the actual path is tries to open.

---

VS Code version: Code - Insiders 1.47.0-insider (0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69, 2020-06-23T09:03:35.861Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.14.83-gentoo
Remote OS version: Linux x64 4.14.83-gentoo
Remote OS version: Linux x64 5.4.28-gentoo
Remote OS version: Linux x64 4.14.83-gentoo

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: blackhole|
|OS|Linux x64 4.14.83-gentoo|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 969)|
|Memory (System)|15.53GB (0.58GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: blackhole|
|OS|Linux x64 4.14.83-gentoo|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 969)|
|Memory (System)|15.53GB (0.58GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: claptrap|
|OS|Linux x64 5.4.28-gentoo|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 3781)|
|Memory (System)|15.51GB (9.08GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: blackhole|
|OS|Linux x64 4.14.83-gentoo|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 969)|
|Memory (System)|15.53GB (0.58GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
udev-rules|dpk|1.0.0
viml|dun|0.1.7
tmux|mal|0.1.0
remote-containers|ms-|0.123.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
jinjahtml|sam|0.13.0
gitconfig|sid|2.0.1
mako|tom|0.2.0
vscode-icons|vsc|10.1.1
overtype|ada|0.2.0
vscode-module-templates|asb|1.3.0
vscode-postgres|cko|1.1.11
quick-open-prefill-selection|col|0.0.1
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.0
Go|gol|0.14.4
search-editor-apply-changes|jak|0.1.1
vsc-python-indent|Kev|1.10.1
restructuredtext|lex|128.0.0
MagicPython|mag|1.1.0
vscode-github-actions|me-|3.0.0
vscode-docker|ms-|1.3.1
python|ms-|2020.7.86945-dev
puppet-vscode|pup|0.27.3
vscode-yaml|red|0.8.0
vscode-stylelint|sty|0.84.0

(1 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Thanks for submitting this! Should be fixed in the next insiders.
