### ISSUE TITLE
Editor hover does not use reference file encoding until it is opened at least once

### ISSUE THREAD

**Issue by gyzerok** [microsoft/vscode#100994]
- VSCode Version: 1.46.1
- OS Version: macOS 10.15.5

Steps to Reproduce:

**Update:** Following is reproduction with TypeScript for the sake of minimal setup. But I can confirm that it is at least also reproducible with PHP and [Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client&ssr=false#review-details). My assumption is - it is reproducible regardless of the language.

1. Create empty directory
2. Open it in VSCode and configure your workspace settings like so (this will ensure that VSCode has to be certain about the encoding of the files):

```json
{
  "files.encoding": "windows1251",
  "files.autoGuessEncoding": false
}
```

3. Create 2 files with `windows-1251` encoding (you can do it through VSCode, doesn't matter)

```ts
// foo.ts

/**
 * Возвращает фуу
 */
export function foo(): string {
  return "foo";
}
```
```ts
// test.ts

import { foo } from "./foo";

foo();
```

4. Close both files/editors (this is important!)
5. Close VSCode
6. Open VSCode
7. Open `test.ts`
8. Hover over `foo()`
9. Observe encoding issues
10. Open `foo.ts` (I assume at this step it actually checks encoding of the file and that's why it starts working)
11. Go back to `test.ts`
12. Hover over `foo()`
13. Observe correctly rendered text

Does this issue occur when all extensions are disabled?: Yes

<img width="343" alt="Screenshot 2020-06-25 at 10 05 09" src="https://user-images.githubusercontent.com/1706020/85639241-6e197580-b6cb-11ea-8ffe-2a19368db1d7.png">

**Comment by gyzerok** [comment]
@bpasero if you don't mind I would like to look into this issue after we are done with the web encoding.

**Comment by bpasero** [comment]
Very likely TS trying to resolve the file to show it in hover and not having a clue about encodings.

**Comment by gyzerok** [comment]
Originally I've experienced this issue with PHP and [Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client&ssr=false#review-details). So it is definitely not exclusive to TypeScript.

**Comment by mjbvz** [comment]
Yes you start seeing the correct result as soon as VS Code sends `foo.ts` to TypeScript (this happens when you open the file). When TypeScript reads it from disk on its own, it cannot can cannot figure out this encoding

Also not sure what the best approach to this.

/cc @amcasey @DanielRosenwasser Have you dealt with this problem for VS?

**Comment by amcasey** [comment]
@mjbvz AFAIK, this is TS's encoding detection logic: https://github.com/microsoft/TypeScript/blob/6b4d0bff409f07ef7e4acd2cde6f7ca0dc4d28fb/src/compiler/sys.ts#L1562

I'm not aware of a way to specify an encoding (e.g. in tsconfig).  @DanielRosenwasser?

I'm not aware of a corresponding report on the VS side, though it seems like it would also be affected.  @minestarks?

**Comment by gyzerok** [comment]
Hm, it can be solved somehow on the VSCode side, so it doesn't have to be reimplemented per language? Or maybe on LSP side? So client can suggest encoding to the server on creation?

**Comment by amcasey** [comment]
I can't speak for other languages, but TypeScript does its own file reading, so it would have to be supplied with a map describing encodings (globs, perhaps?).  With that model, every language would need to be updated to understand the encoding map.  That is, it's not clear to me how you could make a single, central implementation.

**Comment by gyzerok** [comment]
@amcasey yeah I see what you mean. Thank you for clarifying how TypeScript works 👍 

I didn't mean single place as a single implementation, but central place which knows about the files encoding. So to me encoding map you described sounds like an interesting option.

>  With that model, every language would need to be updated to understand the encoding map.

In any case every language will need to be updated be it adding their own config option for encoding (as the one with `tsconfig`) or understanding additional LSP feature. However it being a part of the protocol will give a signal to language server authors to consider it from the get go.

Of course it might not be the best solution. I am just suggesting to consider it if possible.

**Comment by DanielRosenwasser** [comment]
TypeScript has a `charset` flag to control encoding of the file, but I think it died with the old WScript host. Unfortunately [Node.js only supports 8 types of encodings](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings). How does VS Code handle this toda?

**Comment by mjbvz** [comment]
Let's wait for more feedback on this issue. It's not a regression and this is the first time I remember seeing it, so I'm not sure how many users are effected by this sort of problem.

**Comment by gyzerok** [comment]
Personally I would consider it a bug report, not a feature request.

The features of supporting multiple encodings and editor hover tooltips are already there. The question is: would you expect them to work together? My answer is yes.

**Comment by mjbvz** [comment]
When deciding to implement features / fix bugs, we consider:

* What is the impact?

* How many people are impacted?

    Unknown but likely not very many since we have not see prior issues?
   
* How difficult would it be to fix?

    It seems very difficult to fix.

* How difficult is the current workaround? 

    Switch to  unicode. Some workflows may require different encodings, but again we have not seen a large number of people reporting this problem so I'm not sure how many workflows have this issue
