### ISSUE TITLE
Opening File Style

### ISSUE THREAD

**Issue by chinhphan099** [microsoft/vscode#100900]
Is there any theme or how to set the color for tab file?
Look like screen shot below.
Orange: unsave file
Turquoise: saved file.

![tab-style](https://user-images.githubusercontent.com/7882362/85493054-66d96580-b600-11ea-95e6-621a9f4fc6aa.png)

**Comment by ArturoDent** [comment]
> `tab.activeModifiedBorder`: Border on the top of modified (dirty) active tabs in an active group.
> 
> `tab.inactiveModifiedBorder`: Border on the top of modified (dirty) inactive tabs in an active group.
> 
> `tab.unfocusedActiveModifiedBorder`: Border on the top of modified (dirty) active tabs in an unfocused group.
> 
> `tab.unfocusedInactiveModifiedBorder`: Border on the top of modified (dirty) inactive tabs in an unfocused group.

> `tab.activeBorderTop`: Top border for the active tab.
> 
> `tab.unfocusedActiveBorderTop`: Top border for the active tab in an inactive editor group

and more at https://code.visualstudio.com/api/references/theme-color#editor-groups-tabs
