### ISSUE TITLE
Jupyter notebook - code can't indent automatically when I created a new line

### ISSUE THREAD

**Issue by gemini-mouse** [microsoft/vscode#100946]
using Jupyter notebook, the code can't indent automatically when I created a new line.
the error like this.

for i in range(3):
print(i)

shall be like this
for i in range(3):
    print(i)

**Comment by lafe** [comment]
@gemini-mouse: One quick suggesstion: maybe you can format the code using the Markdown feature for code. This would make the code example clearer as both code snippets are currently the same (I assume that whitespace has not been preserved). A short description of this Markdown feature can be found at <https://guides.github.com/features/mastering-markdown/#examples> ("Code" tab).

**Comment by dbaeumer** [comment]
@gemini-mouse please file the issue against the Python extension that provides you with the Jupyter notebook.
