### ISSUE TITLE
Allow setting labelFormat independently for pinned and non-pinned tabs

### ISSUE THREAD

**Issue by AlexTelon** [microsoft/vscode#100944]
This suggestion started from a comment to another issue:
_"... It should be clear what pinned tab means. In my opinion it does not mean shrink-ed tab. It means that it stays there and is always visible. ... Why do you mix pining tab with shrinking tabs. If you want to shrink tabs, add another feature and call it shrink tab, or whatever ..."_ - https://github.com/microsoft/vscode/issues/98161#issuecomment-643229239

I agree with this sentiment and think it warrants a separate discussion. Hence this issue.

The labelFormat setting seems to change how the normal tabs are presented.
![image](https://user-images.githubusercontent.com/5202914/85542563-7f09ae80-b619-11ea-9025-c545505a82a3.png)
in json:
`"workbench.editor.labelFormat": "short"`

I suggest the following:

1. Make it possible to change "Label Format" for pinned and normal tabs independently.
2. Add the option 'icon-only' (which is how pinned tabs are shown now).
3. Suggestions like [this](https://github.com/microsoft/vscode/issues/98161#issuecomment-642420859) and [this](https://github.com/microsoft/vscode/issues/98161#issuecomment-631139945) can then be introduced as separate labelFormats. 

This way the current default behavior would be something like this:
`"workbench.editor.pinnedTab.labelFormat": "icon-only"` (optional override for pinned tabs)
`"workbench.editor.normalTab.labelFormat": "default"` (optional override for normal tabs)
`"workbench.editor.labelFormat": "default"` (applies to all, is backwards compatible)

I like the idea of going further and making all tab-related settings configurable **independently** for both. Im not sure how many there are and if it is worth it. This would be a big change and messy due to backwards compability so there would be many ways to set the same option. But there are now two types of tabs. Pinned and normal. And I think it makes sense for the configuration options to mirror this change. Lets pretend we can change the colors of normal tabs, why would we not want to be able to change the colors of pinned tabs also? Most tab-settings would probably go hand-in-hand like that except those that explicitly deal with what it means to be "pinned" like [99091](https://github.com/microsoft/vscode/issues/99091). 

But as a first step I think just making it possible to edit "Label Format" for both is a good first step.

**Comment by Coops9** [comment]
Where do we upvote the issue... leave a thumbs up on this Issue on GitHub?

**Comment by Coops9** [comment]
> This feature request is now a candidate for our backlog. The community has 60 days to upvote the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).
> 
> Happy Coding!

Where do we upvote the issue... leave a thumbs up on this Issue on GitHub?
