### ISSUE TITLE
Multiple notebook tests failing

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#100911]
Multiple notebook tests failing

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=79670&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=8e2e103d-8d5d-54da-dc73-3c44bf1dc402

**Comment by rebornix** [comment]
Thanks for the quick turnaround, I missed the build message.
