### ISSUE TITLE
How to add icons at the top of the sidebar?

### ISSUE THREAD

**Issue by luhc228** [microsoft/vscode#100959]
I want to add some icons at the top of the sidebar. Though I read the related docs, I have no ideas. Could you give me a hand? Thanks. 
![image](https://user-images.githubusercontent.com/44047106/85572572-aedfa300-b667-11ea-8928-0e59808d7f6d.png)

**Comment by AllanOricil** [comment]
Using Webview API I can add Icon to my Webview panel using:

```javascript
const onDiskPath = vscode.Uri.file( path.join(context.extensionPath, ".images", "webview_icon.png"));
this.panel.iconPath = onDiskPath;
```

How are you opening this tab?

**Comment by jrieken** [comment]
Check this out: https://code.visualstudio.com/api/references/contribution-points#contributes.menus

**Comment by AllanOricil** [comment]
@luhc228 
I made it work like this. You have to have the command and if you want it to be displayed as a button you add an entry to "menus" as "editor/title". Just make sure the "group" is "navigation"

```
"contributes": {
    "commands": [
      {
        "command": "YOUR_COMMAND",
        "title": "COMMAND TITLE",
        "icon": {
          "light": "/.images/icon2.png",
          "dark": "/.images/icon2.png"
        }
      }
    ],
    "menus": {
      "editor/title": [
        {
          "command": "YOUR_COMMAND",
          "alt": "markdown.showPreviewToSide",
          "group": "navigation"
        }
      ]
    }
}
```

Result

![image](https://user-images.githubusercontent.com/55927613/85585958-dd815d80-b616-11ea-8a0d-15697634d28f.png)
