### ISSUE TITLE
Rename/delete git branches?

### ISSUE THREAD

**Issue by JordanLongstaff** [microsoft/vscode#100981]
I cannot find any way of renaming or deleting local git branches. Having these options as features would be very helpful.

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/85651526-da4fa580-b6da-11ea-85df-e87e4bbb6a9f.png)

There are `Git: Rename Branch...` and `Git: Delete Branch...` commands.

**Comment by JordanLongstaff** [comment]
Let me clarify, then: having these options in the Source Control view would be helpful. I can checkout branches, create new branches, publish branches and view history, but I don't see renaming or deleting branches.
