### ISSUE TITLE
VSC not refreshing Disabled extensions as Enabled

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#100956]
- VSCode Version:
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601
- OS Version:

Steps to Reproduce:

1. Enable/Disable extension and check that disaper or not in "Disabled" dock
![VSC_ext-disabled](https://user-images.githubusercontent.com/25403861/85566522-6a84e080-b630-11ea-8eb4-53310328a9c8.png)

2. This same when unistaled
![VSC_ext-uninstaled](https://user-images.githubusercontent.com/25403861/85567003-cc454a80-b630-11ea-9177-01d1afe00971.png)

Does this issue occur when all extensions are disabled?: No

**Comment by sandy081** [comment]
/duplicate

Yeah we do not auto update the views. This is a known issue.
