### ISSUE TITLE
System color theme

### ISSUE THREAD

**Issue by KvanTTT** [microsoft/vscode#100939]
It's only possible to choose the predefined color theme (Light+, Dark+, etc.). But it also would be great if the theme was bond to system settings (Light+ for Light, Dark+ for Dark or other settings that can be configured).

**Comment by yume-chan** [comment]
> or other settings

What settings?

> that can be configured

Configured for what?

---

You can set `workbench.preferredDarkColorTheme`,`workbench.preferredLightColorTheme` and `window.autoDetectColorScheme` to let Code use same theme with your OS, not sure if it's what you want.

**Comment by KvanTTT** [comment]
> You can set workbench.preferredDarkColorTheme,workbench.preferredLightColorTheme and window.autoDetectColorScheme to let Code use same theme with your OS, not sure if it's what you want.

Thanks, this is exactly what I wished for.
