### ISSUE TITLE
vscod经常崩溃 因为一个 exe cpu占用经常100%

### ISSUE THREAD

**Issue by skyplaying** [microsoft/vscode#100909]
Issue Type: <b>Performance Issue</b>

打开 vscode时 会因为一个 叫 rg.exe的服务导致 cpu占用100% 每次更新都没解决这个问题

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (3.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ShawnMerry** [comment]
Open vscode because of a rg.exe 100% CPU usage caused by the service of            VS Code version: Code 1.46.1 (cd9ea64, 2020-06-17T21:13:20.174Z)            OS version: Windows_ NT x64 10.0.17763

**Comment by ShawnMerry** [comment]
我没这情况

**Comment by shaodahong** [comment]
@skyplaying Can you try
```json
{
  "search.followSymlinks": false
}
```

**Comment by roblourens** [comment]
Please let me know whether any tips here help https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
