### ISSUE TITLE
Documentation for consuming authentication providers

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#100995]
Provide documentation, perhaps in the form of a sample extension, explaining how to use the built in GitHub and Microsoft authentication providers. How to use the API, and what the available scopes for these two providers are.

**Comment by warrenbuckley** [comment]
I always love a good example and saves me trying to go through the GitHub Pull Request source code to figure out what is going on.

Can i suggest an example is also put into the repo for consuming the GitHub Auth provider & using that to do some API calls/GraphQL against the auth'd user please :)
https://github.com/microsoft/vscode/issues/88309

**Comment by jamarw** [comment]
> I always love a good example and saves me trying to go through the GitHub Pull Request source code to figure out what is going on.
> 
> Can i suggest an example is also put into the repo for consuming the GitHub Auth provider & using that to do some API calls/GraphQL against the auth'd user please :)
> #88309

Hi @RMacfarlane , I noticed that the milestones have been updated.  Do you have a rough estimate as to when this documentation and/or sample may be available?

Thanks!

**Comment by RMacfarlane** [comment]
Hi @jamarw, I'm aiming to have this finished in the next two weeks! I want to get a portion of the auth provider API moved to stable (https://github.com/microsoft/vscode/issues/100993) and may incorporate a few changes to the API as part of that. I've already written part of a sample and will finish it when that is done.

**Comment by warrenbuckley** [comment]
Hi @RMacfarlane 
With you closing/merging in #100993 shortly are you able to consider writing an example or documentation for us extension authors please 😄

**Comment by RMacfarlane** [comment]
I've created a simple extension sample that uses the new API: https://github.com/microsoft/vscode-extension-samples/tree/master/github-authentication-sample

**Comment by jamarw** [comment]
Thanks @RMacfarlane !!!
