### ISSUE TITLE
"No renderer could be found" wording

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#100992]
![image](https://user-images.githubusercontent.com/8586769/85638135-f7806780-b639-11ea-9d96-504bda9ee869.png)

We should say that no renderer could be found for the specific mimetype selected, not the output as a whole (unless we cant render any of the mimes I guess)

**Comment by rebornix** [comment]
Just validated that when you see the error, it means we can't render any mimetype.

**Comment by JacksonKearl** [comment]
That not what I saw.. in the above screenshot I have text/html and application/json that core is able to render, but I still saw the error.
