### ISSUE TITLE
Notebook output cells overflow 

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#100913]
Notice the cell goes beyond the right margin. Seems to happen for all cells

**Comment by rebornix** [comment]
@roblourens is it related to the indentation change?

**Comment by roblourens** [comment]
I don't think there's an issue here anymore? I did push a change to ensure that a line of text with no whitespace will break and not overflow. But I don't see any other issues with overflowing horizontally.

I do see plain text outputs overflowing if I resize the editor to be narrower...
