### ISSUE TITLE
cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by hupo376787** [microsoft/vscode#100906]
```
版本: 1.46.1 (user setup)
提交: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
日期: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

I'm debuging flutter, when I click restart button, va code shows Waiting for Pixel 3 API 28 to connect, and I acutally running a emulator.
After 60s, vs code hint Failes to launch Pixel 3 API 28

![image](https://user-images.githubusercontent.com/14960168/85497701-f8e96a00-b610-11ea-865d-3087ee039099.png)

Related issue [https://github.com/flutter/flutter/issues/60162](https://github.com/flutter/flutter/issues/60162)

**Comment by weinand** [comment]
Please file this against the Flutter extension

**Comment by hupo376787** [comment]
OK, Thanks, guys.
