### ISSUE TITLE
Unexpected completion item when returning null for provideCompletionItems

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10099]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

- Create a completion provide that always returns null (the docs say this is valid to signal no matching results)
```
provideCompletionItems(document: TextDocument, position: Position, token: CancellationToken): Thenable<CompletionList> {
    return new Promise<CompletionList>((resolve, reject) => {
        resolve(null);
    });
}
```

- Open a document that contains `import "` and invoke completion at the end of the line

The completion popup will show "import" which doesn't seem to make much sense. Selecting this will leave you with `import "import` which is obviously not useful. I would expect when there are no results the popup would not show, or would indicate that there are no suggestions.

Note: My example was "import", but the same thing happens with anything - you get the first previous text appearing in the popup.

![completion](https://cloud.githubusercontent.com/assets/1078012/17381546/5b9b6c8c-59c4-11e6-8809-8789a6d90aa9.png)

**Comment by aeschli** [comment]
What you see are the word based proposals which are by default shown when there are no other proposals.
You can configure wether you want to see text base proposals with 
`"editor.wordBasedSuggestions": true,` setting

**Comment by DanTup** [comment]
@aeschli Gotcha; thanks. Is it possible (and reasonable) for me to disable it at load of my Dart file? I don't think it'll ever provide useful results here and I think it's somewhat confusing.

**Comment by aeschli** [comment]
I agree with you, IMO it would make sense that word proposals could be disabled/enabled per language. Right now it's just a single setting.
Note however, that once your language extension returns proposals, the word proposals will not show anymore (they are just a fall back)

**Comment by DanTup** [comment]
> (@aeschli) Note however, that once your language extension returns proposals, the word proposals will not show anymore (they are just a fall back)

Does this mean if I return an empty list it won't happen? Or is there no way to avoid the behaviour when there are 0 valid completions?

**Comment by aeschli** [comment]
@DanTup No, returning an empty array will not block the word proposals. You need to provide at least one proposal.

**Comment by DanTup** [comment]
Gotcha, thanks!
