### ISSUE TITLE
Cannot select / highlight text in the editor...

### ISSUE THREAD

**Issue by usc-rdh006** [microsoft/vscode#100999]
Issue Type: <b>Bug</b>

All of a sudden (not after updates, not after anything)
I cannot highlight text in the editor anymore. FRUSTRATING

literally in the middle of a session, i cannot highlight text anymore. 

I can highlight with <shift> and the up and down arrows - but using the mouse is far quicker.

What has happened?

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3506)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (11.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by alexdima** [comment]
@usc-rdh006 Do you have any steps to reproduce? I cannot reproduce, selecting with the mouse always works well for me.
