### ISSUE TITLE
Git commit with two separate messages

### ISSUE THREAD

**Issue by fakhamatia** [microsoft/vscode#100931]
How can I commit with two separate messages?
According to [this post](https://stackoverflow.com/a/44838968/10695748) I must use two `-m` to commit message and close issue on GitLab.
Or how can I commit on VSCode and close issue on GitLab?

![Screenshot from 2020-06-24 14-47-13](https://user-images.githubusercontent.com/20030910/85537985-b41dfd00-b629-11ea-915a-bdae0ca2370e.png)

**Comment by joaomoreno** [comment]
Just type the message. Then press <kbd>Enter</kbd> twice. Then type the description. Then press <kbd>Ctrl+Enter</kbd>.
