### ISSUE TITLE
What changed in Insiders 1.47.0 that prevents extensions from rendering images?

### ISSUE THREAD

**Issue by cmendible** [microsoft/vscode#100926]
Issue Type: <b>Bug</b>

Latest code insiders version is preventing extensions such as GitGraph or Device Simultor express from rendering correctly.

VS Code version: Code - Insiders 1.47.0-insider (0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69, 2020-06-23T09:03:35.861Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (5.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
azds|azu|2.0.220200611
githistory|don|0.6.5
gitlens|eam|10.2.2
Go|gol|0.14.4
terraform|has|2.0.2
vscode-peacock|joh|3.7.2
docomment|k--|0.1.12
git-graph|mhu|1.24.0
vscode-azureappservice|ms-|0.17.0
vscode-azurefunctions|ms-|0.22.1
vscode-dapr|ms-|0.2.1
csharp|ms-|1.22.1
vscode-dotnet-runtime|ms-|0.1.2
vscode-aks-tools|ms-|0.0.6
vscode-kubernetes-tools|ms-|1.2.1
remote-containers|ms-|0.123.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
vsliveshare|ms-|1.0.2377
vsonline|ms-|1.0.2390
azurerm-vscode-tools|msa|0.11.0
vscode-yaml|red|0.8.0

</details>

**Comment by mhutchie** [comment]
This is the same bug as the one I've already raised in #100918, that is affecting all Git Graph users that use Visual Studio Code Insiders, as well as every other extension I'm aware of that loads resources (e.g. CSS, JS) in Webview's _(more specifically, resources loaded by `Webview.asWebviewUri`)_.

**Comment by cmendible** [comment]
@mhutchie I´m closing this one as it's a dup.

Kudos for Git Graph!
