### ISSUE TITLE
Dowload link very slow in Kenya

### ISSUE THREAD

**Issue by ALWISHARIFF** [microsoft/vscode#100969]
- VSCode Version: 6.14
- OS Version: Windows 10

Steps to Reproduce:

1.I am trying to download VScode but the link is super slow below is the slow link around 14kb/s is highest please look into this issue.
https://az764295.vo.msecnd.net/stable/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/VSCodeUserSetup-x64-1.46.1.exe

**Comment by joaomoreno** [comment]
That's terrible... Unfortunately we already use a global CDN and really can't do much but escalate the issue to Azure. Have you tried downloading from a different internet connection? Do your colleagues/friends suffer from the same?

**Comment by ALWISHARIFF** [comment]
I tried using proxy download was fast enough pushed the speed to around 80kb/s it downloaded pretty first,
I think you should a better CDN to provide fast reliable file transfers because everything from microsoft visual code were downloading slow even the extensions were very slowly downloading

**Comment by joaomoreno** [comment]
Can you try a really separate internet connection instead of a proxy?

**Comment by ALWISHARIFF** [comment]
Hello,
I used a different connection and it was fast enough below i have attached the ISP providers i used,Wananchi Group Kenya is the slow network.The Download works well in this broadband network Safaricom isp.If you can solve it from your end it will be a great thing thank you.
![safaricom isp](https://user-images.githubusercontent.com/50083809/86044308-c966a300-b9fe-11ea-8d4b-a7486d88655b.PNG)
![zukuisp](https://user-images.githubusercontent.com/50083809/86044333-d388a180-b9fe-11ea-94a9-2c42b4b89958.PNG)

**Comment by joaomoreno** [comment]
That's great to know. Unfortunately you're going to have to contact Wananchi Group Kenya and see if they can figure out why it is so slow. Let me know how it goes!
