### ISSUE TITLE
remoteRoot and sourceMaps do not work properly with TypeScript and Docker while debugging

### ISSUE THREAD

**Issue by Sir-hennihau** [microsoft/vscode#100973]
- VSCode Version: 1.46.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. $ git clone git@github.com:Sir-hennihau/node-mongo-typescript-docker-setup.git
2. $ git checkout df02470621e5599746477f1614bdb140e14e11aa
3. $ cd node-mongo-typescript-docker-setup
4. $ docker-compose up
5. Attach debugger (config is included)
6. Check "Loaded Scripts" section

Does this issue occur when all extensions are disabled?: Yes
![Screenshot from 2020-06-24 20-51-30](https://user-images.githubusercontent.com/23266886/85615872-3247c700-b65d-11ea-9dc4-25c54c3ae901.png)

I'm trying to develop with this stack: NodeJS, Docker ( + Docker-Compose), TypeScript and VSCode. But the debugger will not work properly.

There seems still to be a problem with using the remoteRoot configuration within launch.json (I need it in another project, the linked one is just an example repo) and TypeScript source maps. As you can see in the screenshot, the loaded script in the debugger looks way different from the original one. This gets even messier in bigger files.

According to [this](https://github.com/microsoft/vscode/issues/2472#issuecomment-228131872) statement, there should have been a fix to this behaviour in 2016 already, if I'm correct? So I'm curious what my issue could be here or if it just wasn't fixed yet?

```javascript
// launch.json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "attach",
      "port": 9229,
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/app"
    }
  ]
}
// I also tried setting "sourceMaps": true, but it didn't change anything
```

```Dockerfile
# Dockerfile
FROM node:14-alpine

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . .

EXPOSE 3000
EXPOSE 9229

CMD ["npm", "run", "dev"]
```

```
# docker-compose.yml
version: "3"

services:
  node-app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
```

```javascript
// index.ts
import express from "express";

const app = express();

const PORT = 3000;

app.get("/", (req, res) => {
  res.send("hello world <333.");
});

app.listen(PORT, () => {
  console.log(`App listening on ${PORT}`);
});
```

```javascript
// tsconfig.json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "inlineSourceMap": true, // <--- Also tried using the "sourceMap: true" property instead or without any sourcemap config, but no success here
    "module": "commonjs",
    "outDir": "build",
    "skipLibCheck": true,
    "strict": true,
    "target": "ESNext"
  }
}
```

```javascript
// package.json
  "scripts": {
    "dev": "nodemon --exec 'node --inspect=0.0.0.0:9229 --require ts-node/register source/index.ts'"
  }
```

fyi: when you don't pass a remoteRoot value, the problem does not occur (but certain folder structures will not be debuggable then).

**Comment by weinand** [comment]
I recommend to use the VS Code "Remote Development" and "Remote Container" extensions. 
With this approach there is no need to deal with localRoots and remoteRoots.

Please see https://code.visualstudio.com/docs/remote/remote-overview

**Comment by Sir-hennihau** [comment]
Thanks, I didn't know about that possibility within VSCode. For now, it works!
