### ISSUE TITLE
Expose Peek view API

### ISSUE THREAD

**Issue by skdeng** [microsoft/vscode#100904]
Is it possible to expose the underlying API for Peek views (such as Peek definition, or Peek diff), so that we can create custom pop-up windows with similar style in extensions.
![image](https://user-images.githubusercontent.com/3770270/85476635-9db26b80-b56d-11ea-99d8-6b55f5fd720c.png)

**Comment by jrieken** [comment]
You can use these commands: [`editor.action.peekLocations`](https://github.com/microsoft/vscode/blob/8434c86e5665341c753b00c10425a01db4fb8580/src/vs/editor/contrib/gotoSymbol/goToCommands.ts#L760) and [`editor.action.goToLocations`](https://github.com/microsoft/vscode/blob/8434c86e5665341c753b00c10425a01db4fb8580/src/vs/editor/contrib/gotoSymbol/goToCommands.ts#L760)

**Comment by skdeng** [comment]
Sorry I wasn't clear. I meant to have a fully customizable view (e.g. virtual document or webview) but with the dropdown window style similar to Peek

**Comment by jrieken** [comment]
then see this: https://github.com/microsoft/vscode/issues/3220
