### ISSUE TITLE
Need option to download old versions of VSC portable

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#100964]
There is no option do download older versions of VSC portable just .exe to install.
https://code.visualstudio.com/updates/v1_45
I need this due that VSC is hudge, new changes made that many extension not runing own changes on the time and mode complications.
The best is to offer some release versions on github maybe.

**Comment by joaomoreno** [comment]
Simply take the following URL and replace with the desired version:

```
https://update.code.visualstudio.com/1.37.1/win32-x64-archive/stable
```

**Comment by ManPython** [comment]
@joaomoreno thx
HVR in case when I working on v 1.44.2 and exist version betwen this as 1.45, 1.46 we see in portable option to Download new version, but not sure what as 1.45, 1.46 in case I'm waiting maybe 1.47 or 1.48. I know that I can check on website, etc. but it's good to know maybe to check on VSC what we can update.
