### ISSUE TITLE
extension bar not working .

### ISSUE THREAD

**Issue by Goutampatidar** [microsoft/vscode#100933]
We have written t
Issue Type: <b>Performance Issue</b>

from the first day of installation i facing this problem .
the problem is of extenstion bar . it is not working it always show emptyor blank . 
if i had to install any extenstion i should use vscode official site and then it redirect me to the only extenstion .

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (1.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    74	  5892	code main
    0	    69	  1712	   shared-process
    0	    13	  2200	   electron-crash-reporter
    0	   227	  2372	   gpu-process
    1	    65	  4628	   window (Issue Reporter)
    0	   186	  5876	   window (beatifull polygon .cpp - couresera - Visual Studio Code)
    0	     6	  4900	     console-window-host (Windows internal process)
    0	     5	  8808	     console-window-host (Windows internal process)
    0	     4	  9752	     C:\Windows\System32\cmd.exe
    0	     3	 12464	     C:\Windows\System32\cmd.exe
    0	    12	 12696	     watcherService 
    0	    11	  6360	       console-window-host (Windows internal process)
    0	   100	 12856	     extensionHost
    0	    38	  9780	       c:\Users\hp\.vscode\extensions\ms-vscode.cpptools-0.28.3\bin\cpptools.exe
    0	    24	  3184	         "c:\Users\hp\.vscode\extensions\ms-vscode.cpptools-0.28.3/bin/cpptools-srv.exe" 9780 0
    0	    11	  8180	         console-window-host (Windows internal process)
    0	    24	 12716	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (beatifull polygon .cpp - couresera - Visual Studio Code)
|    Folder (couresera): 20 files
|      File types: cpp(5) o(3) exe(2) json(1) cbp(1) depend(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
c-cpp-compile-run|dan|1.0.11
code-runner|for|0.10.0
cpptools|ms-|0.28.3

</details>
he needed data into your clipboard because it was too large to send. Please paste.

**Comment by yume-chan** [comment]
> the problem is of extenstion bar .

What's the "extension bar"? Can you attach a screenshot showing your problem?

**Comment by Goutampatidar** [comment]
Here are some images .

If you are unable to understand till now I will help you more ..
Here no extension are showing..

**Comment by Goutampatidar** [comment]
![Scre
![IMG_20200624_213645](https://user-images.githubusercontent.com/55948914/85594919-011fc480-b666-11ea-8dc3-91a132c838b4.jpg)
enshot (1)](https://user-images.githubusercontent.com/55948914/85593949-1fd18b80-b665-11ea-8766-813f8556914a.png)

**Comment by Goutampatidar** [comment]
![IMG_20200624_213645](https://user-images.githubusercontent.com/55948914/85595050-1e549300-b666-11ea-8b27-1fcd4d7ea303.jpg)


This is extension bar . here it show empty same as in screenshot I had given.

**Comment by Goutampatidar** [comment]
Are you working in my issue?

**Comment by sandy081** [comment]
Can you please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by Goutampatidar** [comment]
Yes, ofcourse sir
But due to some issue its may be delay .
I regret for delay but due to climate condition there is internet
connection issue in my area.
I hope you will understand my problem and give me some time to manage all
thing..

**Comment by sandy081** [comment]
Yeah sure. Please provide the information when possible.

**Comment by Goutampatidar** [comment]
![consol](https://user-images.githubusercontent.com/55948914/86482818-4fbd1500-bd70-11ea-9698-7e3a24ef1230.png)

- Help -> Toggle Developer Tools -> Console 
screenshot 


![command palte console](https://user-images.githubusercontent.com/55948914/86482930-8b57df00-bd70-11ea-9598-dba42770f8fe.png)

- View -> Command Pallette... -> Toggle Shared Process -> Console
screenshot


![log shared](https://user-images.githubusercontent.com/55948914/86483018-c78b3f80-bd70-11ea-8fe3-70781502000c.png)

- View -> Open View… -> Log (Shared)
screenshot

![log window](https://user-images.githubusercontent.com/55948914/86483081-e7226800-bd70-11ea-8597-25579a4f78d3.png)

- View -> Open View… -> Log (Window)
screnshot



sir, this are the information you have asked me for . i have no enough knowledge  of computer but i had try my best to provide you all data .

**Comment by sandy081** [comment]
Thanks for sharing info. Unfortunately this is not helping. But it is suspicious why Log (window) is not being shown. 

Can you please try launching VS Code with fresh user data directory and extensions directory? You can do this by opening the Command line tool (say Powershell) and run following command (provide proper folder inputs for user data and extensions dir)

`code --user-data-dir <path-to-user-data-dir> --extensions-dir <path-to-extensions-dir>`

**Comment by Goutampatidar** [comment]
Are you saying for fresh start .

**Comment by vishusandy** [comment]
I have [a similar issue in Linux](https://github.com/microsoft/vscode/issues/98765) affecting multiple computers all running Ubuntu.  Does VS Code start slowly for you as well?  Does VS Code work correctly for you if you execute vs code from a terminal (type into the command line and press enter):
`code`

I found a workaround for my issue but it is specific to Linux, and I still am not sure what caused it - I really would like to find the cause as it is very annoying and with every update to VS Code I have to re-apply the fix.  No one will respond or reopen the issue (I didn't respond with more information quick enough and it was closed).  In my case it seems like it may have something to do with setting environment variables, but it could still be helpful with this issue, or at least provide some information and hopefully inspiration.


Side note: **BTW, can someone [reopen my issue](https://github.com/microsoft/vscode/issues/98765)??**  Or maybe have someone else assigned the issue as @egamma seems to either be busy or unavailable, which is fine - no hard feelings, but I really would like a solution.

**Comment by Goutampatidar** [comment]
Yes, VS Code start slowly in my laptop and also VS Code does not  work correctly when  execute vs code from a terminal. 
And I am using windows 10 and I had removed it completely and then again install but problem is not solved. Please help in this unknown issue.

**Comment by vishusandy** [comment]
I'm not sure if this is the same issue as I had, but when I deleted the extensions folder and reinstalled VS Code the issue still persisted (in Windows I believe extensions are located at `%USERPROFILE%\.vscode\extensions` where `%USERPROFILE%` should expand to something like `C:\Users\YourUsernameHere`), have you tried removing the extensions folder?  I believe it persists between installations (I'm not 100% sure on this however).

**Comment by sandy081** [comment]
@Goutampatidar Did you try the step I requested for? 

`code --user-data-dir <path-to-user-data-dir> --extensions-dir <path-to-extensions-dir>`

**Comment by Goutampatidar** [comment]
@sandy081 
I didn't get what are you telling.
sorry, but can you please provide more info about it because  i am  new  user and i  have no much idea about the system and its commands.
are you saying me for chaning path of directory?

**Comment by sandy081** [comment]
From the command line tool run the following command

`code --user-data-dir <path-to-user-data-dir> --extensions-dir <path-to-extensions-dir>`

Please provide new temporary folder paths for user data and extensions dir.

**Comment by Goutampatidar** [comment]
sir, i had done the step,but problem is not solved.
