### ISSUE TITLE
[loc][Query][VSCODE] Localizability of strings

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#100943]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description
-- | -- | -- | -- | --
50456 | vscode-extensions\git.xlf | 0;   "extensions/git/dist/commands.confirm discard all" | Are you sure you want to discard   ALL changes in {0} files?\r\nThis is IRREVERSIBLE!\r\nYour current working   set will be FOREVER LOST. | what will placeholder be   replaced by?
50531 | vscode-extensions\git.xlf | 0;   "extensions/git/package.command.addRemote" | Add Remote... | Does "remote" refer to   "remote repository" here? Please confirm or advise.          Similar strings:     Add remote from URL     Add remote from {0}     Add Remote     0; "extensions/git/dist/commands.addFrom_Duplicated15"     0; "extensions/git/dist/commands.addfrom_Duplicated14"     0; "extensions/git/dist/commands.addremote"
50546 | vscode-editor\vs_platform.xlf | 0;   "src/vs/platform/undoRedo/common/undoRedoService.cannotWorkspaceRedoDueToInProgressUndoRedo" | Could not redo '{0}' across all   files because there is already an undo or redo operation running on {1} | What does the last placeholder   stand for? Please explain.                    Similar string:          Could not undo '{0}' across all files because there is already an undo or   redo operation running on {1}          0; "src/vs/platform/undoRedo/common/undoRedoService.cannotWorkspaceUndoDueToInProgressUndoRedo"
50744 | vscode-extensions\ms-vscode.js-debug-nightly.xlf | 0;   "browser.revealPage" | Focus Tab | is Focus a verb here meaning to   move active state?
50771 | vscode-extensions\ms-vscode.js-debug-nightly.xlf | 0;   "configuration.pickAndAttachOptions" | Default options used when   debugging a process through the `Debug: Attach to Node.js Process` command | Please confirm command is not to   be translated. Thanks!

**Comment by dbaeumer** [comment]
@joaomoreno starting with you as the owner of Git. Please pass on when done.

**Comment by joaomoreno** [comment]
>  what will placeholder be replaced by?

It will be replaced by a number greater than 1.

> Does "remote" refer to "remote repository" here? Please confirm or advise. Similar strings: Add remote from URL Add remote from {0} Add Remote 0; "extensions/git/dist/commands.addFrom_Duplicated15" 0; "extensions/git/dist/commands.addfrom_Duplicated14" 0; "extensions/git/dist/commands.addremote"

A _remote_ is a noun in git terminology; yes, it loosely means a _remote repository_.

---

Moving to @alexdima

**Comment by PDostalek** [comment]
@alexdima  still not answered

**Comment by alexdima** [comment]
Sorry about that!
