### ISSUE TITLE
Right Mouse Click is broken

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#100982]
Issue Type: <b>Bug</b>

Right click anywhere in a document and the context menu does not appear. An error is reported in the developer tools console.

![image](https://user-images.githubusercontent.com/13488/85621064-b20c6c00-b632-11ea-8cce-15773d076ffb.png)

VS Code version: Code - Exploration 1.47.0-exploration (23d15c61b95620c587e1fbea8bf8cc675a18e7e4, 2020-06-24T17:10:42.684Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (5.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|13%|
</details>Extensions: none

**Comment by jtsom** [comment]
Also, once the error is triggered, hover tool tips don't show anymore.

**Comment by deepak1556** [comment]
Thanks for trying out the exploration build

@bpasero this another one of the breaking change from Electron 9 https://github.com/electron/electron/blob/master/docs/breaking-changes.md#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception , ipc serialization will behave like postmessage and it throws if there is an error.

I am yet to make a tracking issue to cover this change.

**Comment by bpasero** [comment]
@deepak1556 ping

**Comment by bpasero** [comment]
Oh I see it now, there is a function sneaking in via options...
