### ISSUE TITLE
Unresponsive directory tree when contents changing rapidly

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode#100908]
- VSCode Version: 1.46.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Run a process which writes files rapidly to a folder
2. Cannot expand / contract folders easily

![image](https://user-images.githubusercontent.com/5028974/85504083-91daae00-b62e-11ea-9305-82d162307e15.png)

In the image above the .chpk file is being replaced in a very fast loop (new file added, old file removed). It's next to impossible to close the folder / switch to another.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
