### ISSUE TITLE
Support hot-exit in extension development

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#100901]
- VSCode Version: 1.47 Insiders
- OS Version: macOS

Steps to Reproduce:

1. Open an extension folder, debug
2. There is no `environmentService.configuration.backupWorkspaceResource`, so backup file service falls back to in mem impl.
3. Then we can not test any backup/hotexit related features

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
I am not planning of adding this anytime soon, but would accept a PR on this. We have to be careful that e.g. extension tests do not fall over any previous state, so I never wanted hot-exit in extension development windows to restore previous dirty state.
