### ISSUE TITLE
Duet Display monitor unplug causes VS Code ''crash''

### ISSUE THREAD

**Issue by ron1234565** [microsoft/vscode#100972]
''crash'' = VS Code window becomes totally black, doesn't respond, use 30 % processor (like endless loops in MATLAB). I didn't wait a lot of time, but I believe VS Code will endlessly stay like this. Then I kill VS Code process in Task Manager. I restart VS Code, and everything works fine.

**Steps needed to reproduce the problem :**

1. Launch Duet Display (app to use an iOS Device as secondary monitor for Windows or MacOS computers).

2. Launch two different VS Code windows. 

3. Edit a .m code (MATLAB extension)

4. unplug IOS device without exit Duet Display

5. VS Code window becomes completely dark

**_System infos :_**

CPUs | Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2197)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 11.87GB (7.57GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
matlab | Gim | 2.0.0
python | ms- | 2020.6.89148
remote-wsl | ms- | 0.44.4
cpptools | ms- | 0.28.3
powershell | ms- | 2020.6.0

**Comment by deepak1556** [comment]
Does the issue happen with latest stable ?

**Comment by ron1234565** [comment]
Hello ! The issue does not happen with latest stable anymore :) !
