### ISSUE TITLE
Change default split editor to be vertical 

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#100970]
From this: https://twitter.com/frontendben/status/1275761130414256129

Currently, there's many ways to split editor vertically (split icon, view > editor layout, keybinding for split editor down)  but can we make that the default way to split?

**Comment by benfurfie** [comment]
Thanks for raising this @sana-ajani. It would be a huge time saver for those of us that use a vertical monitor for coding on.

**Comment by usernamehw** [comment]
Setting https://github.com/microsoft/vscode/issues/33102#issuecomment-394071390:
```js
"workbench.editor.openSideBySideDirection": "down",
```
Or you can click on split icon while holding <kbd>Alt</kbd> key (Not sure about Mac).

Or reassign split keybinding to `workbench.action.splitEditorDown`.

**Comment by sana-ajani** [comment]
Oh awesome, I didn't know about "workbench.editor.openSideBySideDirection". @benfurfie this should work for changing the icon and default keyboard shortcut.
