### ISSUE TITLE
Chinese font display abnormally

### ISSUE THREAD

**Issue by xiyusullos** [microsoft/vscode#100919]
- VSCode Version:
  - Version: 1.43.2
  - Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
  - Date: 2020-03-24T07:34:57.037Z
  - Electron: 7.1.11
  - Chrome: 78.0.3904.130
  - Node.js: 12.8.1
  - V8: 7.8.279.23-electron.0
  - OS: Darwin x64 19.5.0

- OS Version:
  - macOS: 10.15.5
Steps to Reproduce:

1. open "Extensions" and search "chinese"
2. click the "Chinese (Simplified) Language Pack for Visual Studio Code"
3. the result is shown as below where the Chinese fonts display abnormally.
![image](https://user-images.githubusercontent.com/9032435/85528736-e128da80-b63e-11ea-8804-b88d8a7efa71.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by xiyusullos** [comment]
Yes, I have tried the [ latest VS Code insiders build](https://code.visualstudio.com/insiders/) where the same problem occurred, as shown below screenshot.
![image](https://user-images.githubusercontent.com/9032435/86527486-ad1ca780-bed1-11ea-8f80-181a90b22d11.png)

**Comment by xiyusullos** [comment]
And, what kind of more info do your need?

**Comment by mjbvz** [comment]
@xiyusullos Can you help explain the issue with how the text is displayed and what the text should like? (sorry I do not know Chinese so the problem is not clear to me)

**Comment by yume-chan** [comment]
@mjbvz In the screenshot, many characters are displayed as blocks (□, also called tofu).

It means these characters are missing from all the currently used font list.

Usually it's caused by using a Traditional Chinese or Japanese font for Simplified Chinese text. Although these three languages share a lot of characters, each of them still has many unique characters, that will be missing when making fonts for one specific language.

@xiyusullos What's your OS's language?

**Comment by xiyusullos** [comment]
> @mjbvz In the screenshot, many characters are displayed as blocks (□, also called tofu).
> 
> It means these characters are missing from all the currently used font list.
> 
> Usually it's caused by using a Traditional Chinese or Japanese font for Simplified Chinese text. Although these three languages share a lot of characters, each of them still has many unique characters, that will be missing when making fonts for one specific language.
> 
> @xiyusullos What's your OS's language?

English

**Comment by xiyusullos** [comment]
By the way, it suddenly shows correctly. I can not figure out why it suddenly behaves well. It is weird.
