### ISSUE TITLE
Not Able to create project. VS code is stuck in Activating Extensions

### ISSUE THREAD

**Issue by KhusbooHhicglobalsolutions** [microsoft/vscode#100975]
Issue Type: <b>Bug</b>

I installed the latest version of Salesforce CLI and after that installed the latest version of VS code (1.46). When I tried to create project or create project with Manifest, it shows Activating Extensions.
Sometimes I have also seen the notification- 
The extension 'Salesforce CLI Integration' took a very long time to complete its last operation and it has prevented other extensions from running.  OR
The extension 'Apex' took a very long time to complete its last operation and it has prevented other extensions from running. 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
salesforcedx-vscode|sal|48.21.0
salesforcedx-vscode-apex|sal|48.21.0
salesforcedx-vscode-apex-debugger|sal|48.21.0
salesforcedx-vscode-apex-replay-debugger|sal|48.21.0
salesforcedx-vscode-core|sal|48.21.0
salesforcedx-vscode-lightning|sal|48.21.0
salesforcedx-vscode-lwc|sal|48.21.0
salesforcedx-vscode-visualforce|sal|48.21.0

</details>

**Comment by alexdima** [comment]
Please create an issue directly the problematic extensions.
