### ISSUE TITLE
EXTREMELY SLOW and buggy code navigation after March update 

### ISSUE THREAD

**Issue by chesovnik** [microsoft/vscode#100978]
- VSCode Version: 1.46.1
- OS Version: MacBook Pro (15-inch, 2018), macOS Catalina 10.15.5

Steps to Reproduce:

1. Press cmd and click any method name 

Expected behavior: 
Navigation to the method declaration
Actual behavior:
Infinite loading indicator

Does this issue occur when all extensions are disabled?: Yes

I don't remember when exactly it began, but before March or April update it was working fine.

**Comment by mjbvz** [comment]
Which language is this for?

**Comment by chesovnik** [comment]
> Which language is this for?

JavaScript (React + React Native)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
