### ISSUE TITLE
vscode became no response when matching some word in some file

### ISSUE THREAD

**Issue by LambdaAlpha** [microsoft/vscode#100998]
Issue Type: <b>Bug</b>

1. open file in [basic proof theory-笔记.zip](https://github.com/microsoft/vscode/files/4828926/basic.proof.theory-.zip)
2. start "search in file", enable regex
3. input "∀|" in the search box

then vscode became no response

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-texty|dat|1.1.1
vscode-markdownlint|Dav|0.36.0
translation|dus|0.0.4
gitlens|eam|10.2.2
vscode-highlight|fab|1.4.1
code-runner|for|0.10.0
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.13.6
language-haskell|jus|3.2.1
intellij-idea-keybindings|k--|0.2.41
git-graph|mhu|1.24.0
vscode-language-pack-zh-hans|MS-|1.46.3
python|ms-|2020.6.89148
unicode-latex|oij|1.1.2
java|red|0.63.0
vscode-xml|red|0.12.0
dumb-copy-paste|she|1.0.1
vscode-fileutils|sle|3.0.1
markdown-all-in-one|yzh|3.1.0

</details>

**Comment by roblourens** [comment]
Works fine for me, it just matches every character. 
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by LambdaAlpha** [comment]
I tried in insider version (without any extension), the bug wan't reproduced, and I tried in stable version with all extension disabled, the bug was reproduced.
