### ISSUE TITLE
Opening VS Code from WSL fully saturates CPU, system unusable

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#100950]
Issue Type: <b>Bug</b>

When I open VS Code from a workspace directory in WSL, several `node` processes are started, which fully saturate my CPU for several minutes, until I force them to exit by killing them.

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   8896   176 ?        Ssl  12:36   0:00 /init
oliver     620  0.0  0.0  14080   404 ?        Ss   13:04   0:00 ssh-agent
root       741  0.0  0.0   8908   224 tty2     Ss   13:49   0:00 /init
oliver     742  0.0  0.0  10656   688 tty2     S    13:49   0:00 sh -c "$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" cd9ea6488829f560dc949a8b2fb789f3cdc05f5d stable .vscode-server 0  --disable-telemetry
oliver     743  0.0  0.0  10656   752 tty2     S    13:49   0:00 sh /mnt/c/Users/OliverSalzburg/.vscode/extensions/ms-vscode-remote.remote-wsl-0.44.4/scripts/wslServer.sh cd9ea6488829f560dc949a8b2fb789f3cdc05f5d stable .vscode-server 0 --disable-telemetry
oliver     748  0.0  0.0  10656   720 tty2     S    13:49   0:00 sh /home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/server.sh  --port=0 --use-host-proxy --fileWatcherPolling=0 --disable-telemetry
oliver     750  0.1  0.0 958980 44876 tty2     Sl   13:49   0:02 /home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/main.js  --port=0 --use-host-proxy --fileWatcherPolling=0 --disable-telemetry
oliver     781 85.7  0.0 884076 48068 tty2     Sl   13:49  21:18 /home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/uriTransformer.js --useHostProxy=
root       800  0.0  0.0   8904   220 tty1     Ss   13:51   0:00 /init
oliver     801  0.0  0.0  18208  3824 tty1     S    13:51   0:00 -bash
oliver    1845  324  0.1 2609892 110336 tty2   Z    14:06  26:02 /home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/bootstrap-fork --type=watcherService
oliver    1947 45.8  0.0 1084788 55664 tty2    Sl   14:11   1:23 /home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/uriTransformer.js --useHostProxy=
oliver    1958 1047  0.0 2576288 31204 tty2    Rl   14:11  31:25 /home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/node /home/oliver/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/bootstrap-fork --type=watcherService
oliver    3096  0.0  0.0  18648  1896 tty1     R    14:14   0:00 ps aux
oliver    3097  0.0  0.0  15644  1328 tty1     S    14:14   0:00 less
```

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (48.47GB free)|
|Process Argv|C:/Users/OliverSalzburg/.profile|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3601)|
|Memory (System)|63.91GB (48.49GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3601)|
|Memory (System)|63.91GB (48.46GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
eslint-disable-snippets|drK|1.2.0
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.8
vscode-icons|vsc|10.1.1

(1 theme extensions excluded)

</details>

**Comment by oliversalzburg** [comment]
When I reported this originally, I was still using WSL1. I have now installed Windows 10 2004 and WSL2, in the hope to resolve this performance problem.

It actually got _much_ worse as a result of the upgrade. When I now open the workspace my system actually fully freezes and needs to be hard-reset. Without interaction it takes about 10 minutes before it becomes responsible enough for me to kill VS Code.

**Comment by oliversalzburg** [comment]
Okay, I merely _installed_ WSL2 and hadn't switched my distribution over yet (`wsl --set-version Ubuntu-20.04 2`). After switching the distribution over to WSL2, the system no longer freezes.

**Comment by aeschli** [comment]
There's a known issue for WSL1 with Ubuntu 20.04 caused by https://github.com/microsoft/WSL/issues/4898. We track this in https://github.com/microsoft/vscode-remote-release/issues/3244

The solution at this time is to switch to Ubuntu 18.04 on WSL1 or switch to WSL2
