### ISSUE TITLE
[loc][Query][VSCODE] Localizability of strings in vs_workbench_contrib

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode#100941]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description
-- | -- | -- | -- | --
50454 | vscode-workbench\vs_workbench_contrib_userDataSync.xlf | 0;   "src/vs/workbench/contrib/userDataSync/browser/userDataSyncViews.current" | Current | Does this DevComment mean that   "machine" will follow this segment? Or should this segment itself   be translated as "current machine"?
50458 | vscode-workbench\vs_workbench_contrib_tasks.xlf | 0;   "src/vs/workbench/contrib/tasks/browser/abstractTaskService.TaskSystem.invalidTaskJsonOther" | Error: The content of the tasks   json in {0} has syntax errors. Please correct them before executing a   task.\r\n | Could you kindly check if   "tasks json " is possibly a typo of "tasks.json "?
50505 | vscode-workbench\vs_workbench_contrib_userDataSync.xlf | 0;   "src/vs/workbench/contrib/userDataSync/browser/userDataSyncViews.confirm   replace" | Would you like to replace your   current {0} with selected? | What will {0} be replaced with?
50506 | vscode-workbench\vs_workbench_contrib_terminal.xlf | 0;   "src/vs/workbench/contrib/terminal/common/terminalConfiguration.terminal.integrated.commandsToSkipShell" | A set of command IDs whose   keybindings will not be sent to the shell and instead always be handled by   Code. This allows the use of keybindings that would normally be consumed by   the shell to act the same as when the terminal is not focused, for example ctrl+p   to launch Quick Open. Use the command prefixed with `-` to remove default   commands from the list.\r\nDefault Skipped Commands:\r\n\r\n{0} | Is "Code" capitalized   intentionally? Does it stand for "VS Code"?
50508 | vscode-workbench\vs_workbench_contrib_userDataSync.xlf | 0;   "src/vs/workbench/contrib/userDataSync/electron-browser/userDataSync.contribution.too   many requests_Duplicated1" | Turned off syncing preferences   on this device because it is making too many requests. Please report an issue   by providing the sync logs. | Does this mean "preferences   of syncing" or "syncing the preferences"?          0;   "src/vs/workbench/contrib/userDataSync/browser/userDataSync.contribution.too   many requests_Duplicated2"     0; "src/vs/workbench/contrib/userDataSync/electron-browser/userDataSync.contribution.too   many requests_Duplicated1"
50509 | vscode-workbench\vs_workbench_contrib_search.xlf | 0;   "src/vs/workbench/contrib/search/browser/search.contribution.search.searchEditor.reusePriorSearchConfiguration" | When enabled, new Search Editors   will reuse the includes, excludes, and flags of the previously opened Search   Editor | Are these words localizable?
50536 | vscode-workbench\vs_workbench_contrib_debug.xlf | 0;   "src/vs/workbench/contrib/debug/browser/debugActions.selectWorkspaceFolder" | Select a workspace folder to   create a launch.json file in or add it to the workspace config file | We understood as "add the   workspace folder to the file with the workspace configuration". Please   confirm or advise.
50537 | vscode-workbench\vs_workbench_contrib_debug.xlf | 0;   "src/vs/workbench/contrib/debug/browser/debugEditorActions.stepIntoTargets" | Step Into Targets... | What exactly does "Step   into Targets" mean? Please explain.
50538 | vscode-workbench\vs_workbench_contrib_sash.xlf | 0; "sashSize" | Controls the size of the sash. | What exactly is a   "sash" here? We understood as "side bar which can be   dragged" for now. Please advise.
50539 | vscode-workbench\vs_workbench_contrib_userDataSync.xlf | 0;   "src/vs/workbench/contrib/userDataSync/browser/userDataSyncViews.workbench.actions.sync.commpareWithLocal" | Open Changes | We understood "open"   in sense "pending" here, please confirm or advise.
50547 | vscode-workbench\vs_workbench_contrib_userDataSync.xlf | 0;   "src/vs/workbench/contrib/userDataSync/browser/userDataSync.error   upgrade required" | Turned off sync because the   current version ({0}, {1}) of {2} is not compatible with the Preferences Sync   Service. Please update and turn on sync to continue syncing. | What does placeholder {2} stand   for? Please explain.
50555 | vscode-workbench\vs_workbench_contrib_debug.xlf | 0;   "src/vs/workbench/contrib/debug/browser/replViewer.replRawObjectAriaLabel" | Repl variable {0}, value {1} | Is repl = replacement?
50556 | vscode-workbench\vs_workbench_contrib_tasks.xlf | 0;   "src/vs/workbench/contrib/tasks/common/taskConfiguration.TaskParse.noOsSpecificGlobalTasks" | Task version 2.0.0 doesn't   support global OS specific tasks. Convert them to a task with a OS specific   command. Affected tasks are:\r\n{0} | Is Task in "Task version   2.0.0" localizable?
50745 | vscode-workbench\vs_workbench_contrib_extensions.xlf | 0;   "src/vs/workbench/contrib/extensions/browser/extensionsActions.malicious_Duplicated27" | Malicious | Please clarify context. Is it   referred to an extension?
50746 | vscode-workbench\vs_workbench_contrib_extensions.xlf | 0;   "src/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.startupFinishedActivation" | Activated by {0} after start-up   finished | Please clarify context. Is it   referred to an editor?
50767 | vscode-workbench\vs_workbench_contrib_files.xlf | 0;   "src/vs/workbench/contrib/files/browser/fileCommands.genericSaveError_Duplicated21" | Failed to save '{0}': {1} | If you don't mind, could you let   us know the correlation of "Failed to save '{0}'" and   "{1}"?

**Comment by dbaeumer** [comment]
@sandy081 starting with you as the owner of userDataSync

**Comment by sandy081** [comment]
Done with mine -> assigned to @alexr00 for tasks.

**Comment by alexr00** [comment]
Done with mine, on to @Tyriar for terminal

**Comment by Tyriar** [comment]
@bpasero for file save ones, @isidorn for debug/sash.

**Comment by isidorn** [comment]
Sash one is no longer applicable, we changed the text to "Controls the feedback area size in pixels of the dragging area in between views/editors. Set it to a larger value if you feel it's hard to resize views using the mouse."
The debug ones I will clarify in code via `nls.comments`.

**Comment by PDostalek** [comment]
@isidorn  can not find replies for 50509, 50547, 50746

**Comment by isidorn** [comment]
@PDostalek sorry, we missed those, reopening for those and assigning to @roblourens and @sandy081 since they are related to search and extensions

**Comment by sandy081** [comment]
I have already taken care of mine (it started from me 😉 ).

**Comment by roblourens** [comment]
Sorry I guess I missed the search editor one. But I don't fully understand the question, "Are these words localizable?", I am not sure what we do for those words in other strings, but they should be localized in the same way when describing "search editor", "include/exclude" etc elsewhere.

**Comment by PDostalek** [comment]
I think that the translator asks if "Search Editors", "includes", "excludes", "flags" are localizable words. Why is "Search Editor" capitalized? @roblourens

**Comment by PDostalek** [comment]
Can I see your commit @sandy081 for 50547, 50746 ? 

Under code of 50547 I can see that:
Cannot find 100% match string....Is this changed? 

Under code of 50746  I can see that:
In "Activated by {0} after start-up finished" is placeholder activationID of what?

**Comment by sandy081** [comment]
assigning @alexdima for 50746 

Re 50547 - I changed and reused the existing string.

**Comment by alexdima** [comment]
I've added a comment for 50746 in the code.

**Comment by roblourens** [comment]
Added a comment for 50509

**Comment by PDostalek** [comment]
In relation to your reply @gjsjohnmurray  are those "includes, excludes, and flags " localizable for end user?

**Comment by gjsjohnmurray** [comment]
> In relation to your reply @gjsjohnmurray are those "includes, excludes, and flags " localizable for end user?

@PDostalek the original commit to this repo was by @roblourens. I only got mentioned here as a result of how I synced my fork.

**Comment by roblourens** [comment]
Sorry for the slow response. Pushed another change with a better comment on that string. I think that's all that is to be done here, closing this.
