### ISSUE TITLE
[folding] Add Selection + Folding bug

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#10090]
- VSCode Version: 1.3.1
- OS Version: Windows 2012 R2

Steps to Reproduce:

```ts
function foo () {
  let a = 0;
}

function boo() {
  let b = 0;
  let c = 0;
}
```

- Fold `boo()`
- Select `let` on `foo()`
- Ctrl-D, Ctrl-D
- Type 'const` (i.e. replace `let` with `const`
- Unfold `boo()`

You will see the code becomes:

```ts

function foo () {
  const a = 0;
}

function boo() {
  const c = 0;
}
```

instead of 
```ts
function foo () {
  const a = 0;
}

function boo() {
  const b = 0;
  const c = 0;
}
```

**Comment by aeschli** [comment]
This has to do with cursorCollection._mergeCursorsIfNecessary whih merges the two secondary cursors in the folded range to a single cursor (and to a single selection).
@alexandrudima What's the rationale here?

**Comment by alexandrudima** [comment]
@aeschli When two cursors' ranges touch, the two cursors get merged into one.

**Comment by jrieken** [comment]
Verified that it unfolds
