### ISSUE TITLE
Strange scrollbars in GH issues notebook

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#101021]
On Windows.

They even disappear on hover. Strange! 🤔 

![recording](https://user-images.githubusercontent.com/22350/85717375-bf3a6100-b6ed-11ea-8309-888681522bab.gif)

**Comment by rebornix** [comment]
@roblourens I think it was introduced by recent layout/indentation change.

**Comment by rebornix** [comment]
aha, they are scrollbars in the webview.

**Comment by rebornix** [comment]
Verified that the issue is gone in master.
