### ISSUE TITLE
Peek References tree not expanding/collapsing nodes on mouse click anymore

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#101099]
Version: 1.47.0-insider
Commit: 6c235c723cb2d8defb840f732eac620f54aa8b9d
Date: 2020-06-26T05:33:20.679Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.4.0

The tree used to expand/collapse nodes on mouse click:
![image](https://user-images.githubusercontent.com/9205389/85841978-311eb300-b79f-11ea-9e9d-2d862bcab7ba.png)

**Comment by chrmarti** [comment]
Same in debug hover. Moving to @joaomoreno.

**Comment by joaomoreno** [comment]
Fixed in `master` already.
