### ISSUE TITLE
Popup API for extension development?

### ISSUE THREAD

**Issue by tylerl0706** [Microsoft/vscode#10106]
Excuse me in advance for probably putting this issue in the wrong place... 

I was wondering if VSCode has a Popup API of some sorts for extension development.

If you're not entirely sure what I mean, here's an example in Sublime: ![](https://camo.githubusercontent.com/2c9fceeb7237735751fa2e7a37c6af7e107de24b/687474703a2f2f696d6775722e636f6d2f664d374f5468672e706e67)

And in atom they give you the ability to use html I believe so an example of a popup (or "Marker Decoration") in Atom looks like this: ![](https://raw.githubusercontent.com/tylerl0706/Doge-Atom-Package/master/assets/screen_shot.png)

Does VSCode have something similar to this that extension developers can use? If not, where can I request something like it?

Again, sorry if this is in the wrong location! Feel free to move this elsewhere!

Cheers!

**Comment by aeschli** [comment]
Please create a feature request for what you need. Please write what's the purpose of it, maybe add some use cases.
We have API to show text messages, hover, editors with readonly html (e.g. for previews).

**Comment by tylerl0706** [comment]
@aeachli: I think those APIs are perfect for what I'm trying to do. 

Are there any working examples somewhere of them? 

I scoured the internet all last night looking for examples on how to use the HoverProvider, Hover, and the other APIs you mentioned but I had a lot of difficulty getting it to work.

To be fair, I'm fairly new to Typescript, so it might just be me but any examples that use these APIs would help.

**Comment by rchanou** [comment]
@tylerl0706 I've played with the Hover/HoverProvider API and it looks like they only work in the context of [`languages`, via languages.registerHoverProvider`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_languages). No official method lets you insert HTML like Atom does. In issue #1833 @siegebell describes some hackery which I don't understand but is the closest we can get now.

One great use for this would be a color-picker extension [like Atom has](https://atom.io/packages/color-picker):

![Color Picker](https://i.github-camo.com/467c72e686f00893c3d36bf46499e76c10f31787/68747470733a2f2f6769746875622e636f6d2f74686f6d61736c696e647374726f6d2f636f6c6f722d7069636b65722f7261772f6d61737465722f707265766965772e676966)

**Comment by rchanou** [comment]
Funny, I just thought to look up VSCode color pickers after this and found one that looks like it spins up its own Electron app, which is overkill but might let you achieve what you want. If you still care.

**Comment by tylerl0706** [comment]
Neat ideas :) I'll take a look!
