### ISSUE TITLE
Typescript compile errors go away after VSC restart

### ISSUE THREAD

**Issue by kbrung** [microsoft/vscode#101010]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I have a complex API in TypeScript. Some error persist acros compilations. When I restart , they are gone.

I don't know how to reproduce them.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.22GB free)|
|Process Argv|..|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
path-intellisense|chr|2.2.1
vscode-markdownlint|Dav|0.36.0
xml|Dot|2.5.0
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.0
asciidoctor-vscode|joa|2.7.17
graphql-for-vscode|kum|1.15.3
cpptools|ms-|0.28.3
powershell|ms-|2020.6.0
vs-keybindings|ms-|0.2.0
vscode-typescript-tslint-plugin|ms-|1.2.3
material-icon-theme|PKi|4.2.0
platformio-ide|pla|1.10.0
beautify-json|ran|1.0.2
vscode-yaml|red|0.8.0
comment-ts|sal|0.9.11
vscode-multiclip|sle|0.1.5
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.8
markdown-all-in-one|yzh|3.1.0

</details>

**Comment by mjbvz** [comment]
Please provide example code and steps to reproduce the issue
