### ISSUE TITLE
Remove specific entry from "Recently Opened"

### ISSUE THREAD

**Issue by FStefanni** [microsoft/vscode#101090]
Hi,

I searched for the following feature, but i did not found it, so I belive it is missing (if it is not, please forgive me).
In the initial "welcome" page, there is the list of "recent" opened projects/workspaces/folteds/etc..
It could be nice to be able to remove just the entries no more useful.
For example, remove an old workspace, or remove a folder that we opened just to inspect a project one-time, etc..
I have seen the command "Clear Recentrly Opened", but it deletes *all* the entries, whilst I would like to remove just few of them.

I am using VS code 1.46.1 under Linux and Windows.

Regards.

**Comment by chrmarti** [comment]
`F1`  > `File: Open Recent...` gives you a list of recent entries and each entry has a `x` to its right (when the mouse is there) to delete it.

**Comment by FStefanni** [comment]
Thank you, I did not notice the "x".
