### ISSUE TITLE
Support additional directories in module search path

### ISSUE THREAD

**Issue by kaelig** [Microsoft/vscode#10103]
I am using the [app-module-path package](https://www.npmjs.com/package/app-module-path) in my app, and there is something I'd love to be able to configure in jsconfig.json so I can navigate between files more easily.

Consider this structure:

```js
// a/foo.js
require('app-module-path').addPath(process.cwd());

var bar = require('b/bar')

bar()

// b/bar.js
module.exports = function () { console.log('bar') }
```

```bash
$ node a/foo.js
"bar"
```

Unfortunately hovering `require('b/bar')` or CMD+Click on `b/bar` doesn't open b/bar.js.

Is there a way we could enter these kinds of re-mapped paths in jsconfig.json (or other)?

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript#10127
