### ISSUE TITLE
Changes view: staging last file from a bucket collapses entire tree

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101094]
When having more than one repo listed.

**Comment by joaomoreno** [comment]
Where's my gifcap recording 😆

**Comment by bpasero** [comment]
![recording](https://user-images.githubusercontent.com/900690/85872061-8c689980-b7cf-11ea-98f8-09cae3c27c17.gif)

I think the key is that the lower nodes are collapased?

**Comment by joaomoreno** [comment]
@bpasero I actually don't collapse/expand anything... I also can't repro this... can you still repro? 🤔

**Comment by joaomoreno** [comment]
Oh just repro'd!
