### ISSUE TITLE
Auto closing tag on save still work after disable it

### ISSUE THREAD

**Issue by Cadu007007** [microsoft/vscode#101048]
- VSCode Version:1.46.1
- OS Version:ubuntu 20.04

Steps to Reproduce:

1.i disabled html closing tag , but  when i save the file auto close still work 

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
What is your `editor.formatOnSave` setting?

**Comment by Cadu007007** [comment]
> What is your `editor.formatOnSave` setting?

it's true ,when i disable it , the issue is gone , but i need auto format , what should i do ?

**Comment by aeschli** [comment]
The built-in formatter does not auto closing tags. What formatter are you using?

**Comment by Cadu007007** [comment]
> The built-in formatter does not auto closing tags. What formatter are you using?
after set formatOnSave to false , the formatter is null

**Comment by aeschli** [comment]
>  formatOnSave to false , the formatter is null

Not sure what you mean by 'null'?

When you run `Format` from the context menu, does it also close tags?
Do you have any formatter extensions installed?
