### ISSUE TITLE
renaming files persists old name when file is open

### ISSUE THREAD

**Issue by arminhus** [microsoft/vscode#101040]
Issue Type: <b>Bug</b>

1.) Create a new file all lower cased (ex: example.js)
2.) Navigate where your file was created
3.) right click on example.js and change it to Example.js
4.) opening the file again you'll notice in the tab that it still persisted the example.js name instead of Example.js

Reloading VS Code will fix the naming

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
I believe there is a duplicate issue, but @bpasero would know better.
