### ISSUE TITLE
So, in git terms, what is a changelist?

### ISSUE THREAD

**Issue by slim1979** [microsoft/vscode#101019]
So, in git terms, what is a changelist?

_Originally posted by @joaomoreno in https://github.com/microsoft/vscode/issues/36472#issuecomment-339975948_

Сhangelists is a very comfortable thing to work with GIT, for example. This is a kind of precommit. I create such a precommit, give it a name that will then be the commit header, make it active, and all the files I change fall into this list. Then I commit, and the header is ready. I can switch between such lists, making them active or not. This is a tool for sorting changes. Now all the changes are in one big list, which is not very convenient.

**Comment by joaomoreno** [comment]
> Сhangelists is a very comfortable thing to work with GIT, for example. This is a kind of precommit. I create such a precommit, give it a name that will then be the commit header, make it active, and all the files I change fall into this list. Then I commit, and the header is ready. I can switch between such lists, making them active or not. This is a tool for sorting changes. Now all the changes are in one big list, which is not very convenient.

Can you show me what this means in terms of the git command line?

**Comment by slim1979** [comment]
Guess, it's means nothing in terms of the git command line? You can think about it, like about GUI commit wrapper. It's like stashed changes. When I create changelist and set it as active, I can d&d file into and it became _stashed_. When I work in such active changelist and make changes in file, file automatically added to this active list. Lately, when I click on this list by right mouse button and choose to commit, from this moment this can means in terms of the git command line, that I want to commit changes.... You can see how this works for JetBrains. That's what they do.

**Comment by faulknermano** [comment]
I've also been looking at Changelists (i.e. PyCharm) for VS Code, and I found Git Stash (https://marketplace.visualstudio.com/items?itemName=vii.GitStashExtension) which seems to be, at the least, closer to Changelists in terms of useability.

I like PyCharm's Changelist feature in that you can add your commit message there, too, keeping my changes compartamentalised. It's a much faster to work with, and less-error prone.
