### ISSUE TITLE
Using files to exclude after searching should filter results

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#101038]
<img width="500" src="https://user-images.githubusercontent.com/35271042/85749337-9e5a1780-b6bd-11ea-8eed-5b28dc54b7c1.gif">

Steps to Reproduce:
1. Search for an item
2. Remove a few entries from the results
3. Add a file type in the "files to exclude"
4. :bug: search is re-triggered which causes previous files that were removed to re-appear

Proposal: in the case of excluding files **after** a search, filter out the results which persist previously removed items

**Comment by roblourens** [comment]
That's a good suggestion. I would prefer to retrigger the search, for consistency with "files to include", and it's especially useful if you hit the max results limit. A couple other directions to get the same thing

- We can support the "type to find/filter" that we support in other trees. I would like to have this but there are some limitations in the model for that thing, there is another issue for this
- There is another issue to support multiple searches, like in tabs. I think that if we had this, I would feel better having different experiences for narrowing down a search vs kicking off a new search
