### ISSUE TITLE
Yaml syntax highlight break for comma in quoted string

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#10107]
- VSCode Version: 1.3.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Create a yaml file and add following code 
```yaml
     fields: publisher_id.`split(., 1, 1)`
```
2. The highlight breaks at comma in vscode

And I also created a PR which is abandoned by me [here](https://github.com/Microsoft/vscode/pull/10105), and it breaks some cases about comma, I am not quite sure if it's right, so could you please fix the issue. And in other editors like sublime and atom the colorizer result are all correct

**Comment by aeschli** [comment]
This issue was moved to textmate/yaml.tmbundle#16
