### ISSUE TITLE
Consider adding a short delay before debug toolbar appears

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#101018]
Using the latest `vscode-mock-debug` in a VS Code - OSS that I just built from master, the Run button makes the debug toolbar appear, then change, then disappear when the run has ended.

![junk](https://user-images.githubusercontent.com/6726799/85632282-f4539e80-b66e-11ea-8f6b-0a15049c1a63.gif)

Can anything be done to prevent this unnecessary activity>

_Originally posted by @gjsjohnmurray in https://github.com/microsoft/vscode/issues/92269#issuecomment-649097480_

**Comment by isidorn** [comment]
Thanks for creating this issue! I think what you are saying and it makes sense. We should show the toolbar with a slight delay, now the open question is when to show it with a delay and when to immediatly show it.

**Comment by weinand** [comment]
The toolbar must become visible on first change. E.g. the debugger breaks and the "pause" button turns into a "continue" button. If nothing is happening, it is OK to show the toolbar after a delay, e.g. 300 ms.

**Comment by isidorn** [comment]
We can do that. But what is the right number, because 300ms for example would still show the debug toolbar in the examlpe above, it would just be shorter and look more like a UX glitch.

**Comment by weinand** [comment]
The question is: what delay are users willing to accept when they start a debug session and are not immediately hitting a breakpoint.

**Comment by isidorn** [comment]
Let's close as dup of https://github.com/microsoft/vscode/issues/84228
