### ISSUE TITLE
Do not close tabs when releasing middle-mouse while not pressed over tab

### ISSUE THREAD

**Issue by alanhett** [microsoft/vscode#101028]
- VSCode Version: 1.46.1
- OS Version: Windows 10

Steps to Reproduce:

<img width="224" alt="Screenshot" src="https://user-images.githubusercontent.com/20879700/85735172-7ec9eb80-b6cb-11ea-818f-9e60945b5a19.png">

1. Use middle-click to column select some text, 
2. Release the middle-click over the tab bar

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Up for grab if someone has a minimal fix that does not cause regressions.
