### ISSUE TITLE
Property autoAttachChildProcesses is not allowed

### ISSUE THREAD

**Issue by nadiiach** [microsoft/vscode#101039]
VScode does not stop on breakpoints for the code that was called by child process created within main process.
I googled and found the following property that is supposed to resolve my issue: "autoAttachChildProcesses": true, but for some reason it is underscored with warning that this property is not allowed. I would like to know how to resolve this issue. 

- VSCode Version: 
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

- OS Version:
VERSION="18.04.4 LTS (Bionic Beaver)"

Steps to Reproduce:

1. Create launch.json 
{
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "autoAttachChildProcesses": true,
        }
    ]
}

Warning: Property autoAttachChildProcesses is not allowed.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
launch configuration properties like "autoAttachChildProcesses" are not VS Code features but are private to specific debuggers.   So only the Node.js debugger understands "autoAttachChildProcesses". If you would like to see this feature in another debug extension, please file a feature request against that extension.
