### ISSUE TITLE
Can't move folder/file to root

### ISSUE THREAD

**Issue by AndreVanKammen** [microsoft/vscode#101020]
- VSCode Version: 1.46.1
- OS Version: Windows 10

Steps to Reproduce:

1. Drag folder
2. Drop it on the root folder
3. Nothing happens

Why did you close the original question?

Now i had to open a new one and that doesn't help. Don't close of tickets like that with saying drop it in the empty space that is not an user-friendly solution because that is hardly reachable. The most obvious thing i tried was dropping it on the header, because that contains the root folder name.

It looks to me like these kind of bugs are never fixed, just like not being able to rename a file properly (same problem for create file). I just did a create file typed a name with a space in it and my file just disappeared, how is that for user experience. These are basic functions that everyone uses, they shouldn't be this buggy.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
> Why did you close the original question?

Please reference that original question.

> 
> It looks to me like these kind of bugs are never fixed, just like not being able to rename a file properly (same problem for create file). I just did a create file typed a name with a space in it and my file just disappeared, how is that for user experience. These are basic functions that everyone uses, they shouldn't be this buggy.

[One problem per issue please](https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions). If you can't find open duplicates for your additional issues, go ahead and open new ones.
