### ISSUE TITLE
Provide a web minify gulp task or web npm package

### ISSUE THREAD

**Issue by Felx-B** [microsoft/vscode#101087]
Hello team ! 

I'm trying to build a vscode full web environment to provide a solid file system editor.
For dev I'm using the `yarn web` command, which works very well, but for a later production I'll need a bundled/minified verision of the static files.  

I found in the history of this file https://github.com/microsoft/vscode/blob/master/build/gulpfile.vscode.web.js 
those tasks seem to have been moved elsewhere.

Why do not expose this anymore ?

It could be great to support these commands or even more, provide npm package with a full web vscode out of the box

Thank you !

**Comment by orta** [comment]
To provide an example of why I +1'd this, I'd like to explore whether vscode can be used as a framework for replacing the [new TypeScript Playground](https://www.staging-typescript.org/play) in a statically built website in relation to https://github.com/microsoft/TypeScript/issues/39707

**Comment by larshp** [comment]
And I'd like to replace https://playground.abaplint.org with the vscode web version to get support for multiple files and upload download zip

**Comment by Felx-B** [comment]
I found a way to bundle/minify web version with few modifications : 
in file [`/build/gulpfile.vscode.js`](https://github.com/microsoft/vscode/blob/master/build/gulpfile.vscode.js)
replace 
```typescript
const vscodeEntryPoints = _.flatten([
	buildfile.entrypoint('vs/workbench/workbench.desktop.main'),
	buildfile.base,
	buildfile.workerExtensionHost,
	buildfile.workerNotebook,
	buildfile.workbenchDesktop,
	buildfile.code
]);
```
by 
```typescript
const vscodeEntryPoints = _.flatten([
	buildfile.entrypoint('vs/workbench/workbench.web.api'),
	buildfile.base,
	buildfile.workerExtensionHost,
        buildfile.workerNotebook,
	buildfile.workbenchWeb,
        buildfile.keyboardMaps,
	buildfile.code
]);
```

then run `gulp compile-build` and `gulp minify-vscode`

To host it you should then use [`workbench.html`](https://github.com/microsoft/vscode/blob/master/src/vs/code/browser/workbench/workbench.html) instead of dev version

**Comment by darrinm** [comment]
Awesome @Felx-B! Now I have a minimized build. However when I serve it and load workbench.html it fails with "Uncaught TypeError: Cannot read property 'context' of undefined" in bootstrap-window.js. No network request failures though. What are you doing to host/serve it?

Also found the build can be reduced to 1/4 of the size by removing all the .map files.

**Comment by egamma** [comment]
>I'm trying to build a vscode full web environment to provide a solid file system editor.

We are sorry, but we currently have no plans to support such scenarios.

**Comment by Felx-B** [comment]
For those who are still interessed by this kind of feature, I made a repo & npm packages :
https://github.com/Felx-B/vscode-web
https://www.npmjs.com/package/vscode-web

**Comment by GregBrimble** [comment]
Amazing, thanks @Felx-B!
