### ISSUE TITLE
Toggle View Visibility Missing in Panel at Container Level

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101016]
1. Move variables view to problems panel
2. Right click on variables view -> hide
3. No way to get the variables view back 🐛 

I am still puzled how to get the variables view back since there is no affordance in the panel to see hidden views.
Or I might be missing something.

fyi @sandy081

**Comment by sbatten** [comment]
@isidorn you are right, this is missing.

Workaround: 
1. Drag another view into problems view.
2. Right click a view header and check variables view
3. Reset other view

**Comment by isidorn** [comment]
@sbatten yeah, I found the workaround, however I think it is very ugly and would be great if we could somehow fix this.

**Comment by sbatten** [comment]
This will be resolved by https://github.com/microsoft/vscode/issues/101382
