### ISSUE TITLE
Remote explorer select box has weird border

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101029]
1. Open remote explorer
2. Notice the select box has a weird gray border. No other dropdown has this border and our dropdowns should look consistent in general

I see this on macOS

![Screenshot 2020-06-25 at 16 20 26](https://user-images.githubusercontent.com/1926584/85737690-e437cf80-b6ff-11ea-966e-2ae041af3962.png)

**Comment by alexr00** [comment]
@misolori might you be able to help here? This doesn't occur on Windows and I can't test on macOS.

**Comment by isidorn** [comment]
I see that the border is added from Javascript
So it might be some weird styling?

![Screenshot 2020-06-25 at 16 47 18](https://user-images.githubusercontent.com/1926584/85742475-8efdbd00-b703-11ea-8528-33aeb7c61c88.png)

Weirdly in the light theme it does not look that bad

![Screenshot 2020-06-25 at 16 48 20](https://user-images.githubusercontent.com/1926584/85742653-b6548a00-b703-11ea-958b-5e43b9b48965.png)


All our select boxes should look the same, and they should not have a custom styling. We are totaly failing here because nobody owns the select box.

**Comment by alexr00** [comment]
Looks like its coming from https://github.com/microsoft/vscode/blob/cfd345c3b58ddb46b8231f3c9fc43e5ce8f18568/src/vs/workbench/contrib/remote/browser/explorerViewItems.ts#L79-L79

**Comment by misolori** [comment]
Ah, I noticed this the other day but couldn't remember where I saw this. I can take a look.

**Comment by alexr00** [comment]
I think I can safely just remove it since @isidorn has updated the select box styles.

**Comment by alexr00** [comment]
I deleted the offending line, let me know if that fixes it!

**Comment by isidorn** [comment]
Good job, fixed it
