### ISSUE TITLE
Change debug.toolbarLocation to be docked by default

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101031]
Users general dislike the floating debug toolbar since it gets in the way. I say this with a certainty because I have recieved numerous issues over the years.

My proposal:
1. Change the `debug.toolbarLocation` to be `docked` by default
2. Add an action `Move Out Toolbar` in the `...` to make it discoverable how to go back to the old behavior

fyi @weinand @connor4312 and @jrieken since I know he uses it like this
@misolori a potential discussion for one future ux meeting

![Screenshot 2020-06-25 at 16 25 50](https://user-images.githubusercontent.com/1926584/85739458-1a298380-b701-11ea-9fee-689155ac4699.png)

**Comment by connor4312** [comment]
I prefer docked as well. The floating bar always seems to get in the way no matter where I put it.

**Comment by alexr000** [comment]
I suspect I'm in the minority here, but I prefer it floating. If I've switched to another view while debugging, then it's two steps to get back to the docked toolbar instead of only one to get to the floating toolbar. It also gives me a nice reminder of whether execution is paused or not (play icon vs. pause icon). If the toolbar is docked, it would be nice to show that play/pause somewhere else so I know if execution is paused at a glance.

**Comment by isidorn** [comment]
@alexr000 good points. We could play with the status bar a bit, so the status bar would give the indication if paused or not.
Also isn't your account @alexr00 ?

**Comment by misolori** [comment]
I personally have it docked, except for when I run multiple debug sessions. And that's mostly because the docked view is harder to use:

![image](https://user-images.githubusercontent.com/35271042/85742495-23423280-b6b8-11ea-87b1-314d0d427692.png)

Maybe as part of this we improve this view as well?

**Comment by weinand** [comment]
I prefer the toolbar floating because then it is available everywhere. 
Since I'm running debug sessions from the explorer (via F5), and do not automatically switch to the debug viewlet, I would not see a docked toolbar.

**Comment by isidorn** [comment]
@weinand we open the debug viewlet once the debug session is started
@misolori sure we can have that action, not only in the `...` but in the command palette as well

**Comment by rebornix** [comment]
IMHO it will lead to confusion for a while for users like me: I use the floating toolbar as an indicator for execution status as @alexr00 said above, and then use Hover and Debug Console for accessing variables. It means I pay very little attention to the Debug viewlet while debugging and my major focus is the editor pane. I tried docking it and play with it a few times and got mixed feelings of

* where is my toolbar, is it half broken?
  * then how to move it back to where it was? I tried dragging it out but it didn't work (I'm pretending I'm unaware of the setting)
* as a mouse user, I need to move mouse more to click those buttons or switch processes

Having a command or secondary action doesn't improve the experience a lot as the dropdown menu in non-debug mode is for turning on/off views, I doubt if users will try it before searching online how to disable/modify it online.

**Comment by sbatten** [comment]
I am a docked user, I never liked the floating UX but I do sometimes have the pain of having to switch back to the debug viewlet if I've done anything else during the debug session. If were were to make this change, I imagine it would be best for new users only.

**Comment by weinand** [comment]
@isidorn you said:
> we open the debug viewlet once the debug session is started

not for me, I'm using the `"debug.openDebug": "openOnDebugBreak"` setting.

**Comment by isidorn** [comment]
@rebornix good points.

@weinand sure, but those are advanced users who have those settings, since it is not the default. For them I am not worried that they will not figure out to put debug.toolbarLocation: floating.

@sbatten agree, safest is to only do this for new users

**Comment by kieferrm** [comment]
I'm in the same boat as @weinand (see comments above) and prefer floating.

**Comment by gjsjohnmurray** [comment]
>     2\. Add an action `Move Out Toolbar` in the `...` to make it discoverable how to go back to the old behavior

IMO it would be better phrased as `Float Toolbar` or `Undock Toolbar`. I prefer the first of these.

How about resolving the "it gets in the way" complaints by removing the Y-constraint [here](https://github.com/microsoft/vscode/blob/41f32e0bd66c709095e9d9c9d07e5f0a238735db/src/vs/workbench/contrib/debug/browser/debugToolBar.ts#L222-L227) which prevents people moving it any lower than the breadcrumb region?

Or are there good reasons for keeping it up there?

**Comment by Spongman** [comment]
there needs to be more places to put the 'floating' toolbar. all of the places you can put it now are obscuring some other UI elements.

**Comment by isidorn** [comment]
Thanks for the feedback. However I have decided not to change the default value of the debug toolbar location. Thus closing.
