### ISSUE TITLE
Breakpoints are hit or miss when debugging the spell check extension

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#10102]
- VSCode Version: latest 1.4.0 insiders
- OS Version: MacOS, Windows

Steps to Reproduce:
1.  `git clone git@github.com:Microsoft/vscode-spell-check.git`
2. `cd vscode-spell-check`
3. `code-insiders .`
4. launch extension
5. set breakpoint https://github.com/Microsoft/vscode-spell-check/blob/master/src/Features/spellProvider.ts#L151
6. open a `.md` file
   **-> breakpoint should be hit**
7. insert `Thhhis` to the `.md`file
   **-> breakpoint should be hit**

Observation:
Out of a dozen attempts of steps 3 - 7 I hit the breakpoints only a couple of times. This on Mac and in a Windows VM using node 4.4.7, 6.2, and 6.3.1. It seems completely random when the breakpoint is hit and when not.

@seanmcbreen reported similar observations.

**Comment by kieferrm** [comment]
I believe the problem is an upper/lower case letter difference if folder names in that particular extension:

<img width="193" alt="screen shot 2016-08-03 at 5 16 41 pm" src="https://cloud.githubusercontent.com/assets/4674940/17386301/2dc1e460-599e-11e6-9043-cb90081fd96a.png">

The `src\Features` folder gets transpiled into `out\features`.  There are a couple of issues here:
1. On a case insensitive file system such a difference shouldn't matter to the debugger.
1. On a case sensitive file system the build result should be `out\Features`. (Still need to check if this isn't the case and possibly file a separate issue.)

However, it's unclear why sometimes the breakpoint was hit at all.

**Comment by seanmcbreen** [comment]
Thanks for digging in.  I will try first thing tomorrow on my Mac.  My only caution is that I also failed to bebug on Windows which should be case insensitive.

**Comment by weinand** [comment]
Thanks for looking into this while I'm on vacation. Just one additional comment: the node loader is case-sensitive on all platforms. So the path used to register a breakpoint must match the character-case of the path that node uses to load the file. If it doesn't node won't hit breakpoints.

Could you disable sourceMaps and set the breakpoint in the generated source instead of TS and see whether this makes a difference.

**Comment by seanmcbreen** [comment]
I'm hitting the breakpoints now with the case changed.  It does take ~20 seconds to get there but it's working for sure!

Is there an issue we should post to typescript?

**Comment by seanmcbreen** [comment]
Ok I tried a few more times and I still don't hit breakpoints predictably - most of the time not at all.  

So as suggested by @weinand I turned off source maps and set directly in the transpiled `.js` files.  Here I had 100% success.

**Comment by weinand** [comment]
I'm no longer aware of any issues in this area. Closing.
