### ISSUE TITLE
Cannot disable Git repository detection.

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#101060]
Issue Type: <b>Bug</b>

**I cannot disable submodule/repository detection.** This is **infuriating**. Whenever VSCode feels like it (which is frequent during a rebase), an extra 7 repositories that *I do not care about* pop up under "Source control providers". I have tried disabling `git.detectSubmodules`. I have tried disabling `git.autoRepositoryDetection`. I have done both. I have done all of these things at the user level and the workspace level. NOTHING WORKS.

I am working on `github.com/tinygo-org/tinygo`, using my fork `github.com/firelizzard18/tinygo`, on my branch `teensy-3.6`.

The host operating system is Windows 10, version 2004. I am developing within an Ubuntu WSL 2 environment using the VSCode remote WSL extension.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Fetching remote diagnostics for 'wsl+ubuntu2' timed out.
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.90GB (31.71GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu2/usr/src/go/src/gitlab.com/firelizzard/go-iter|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'wsl+ubuntu2' timed out.

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu2|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3299)|
|Memory (System)|50.14GB (29.69GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu2|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3299)|
|Memory (System)|50.14GB (29.69GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
better-toml|bun|0.3.2
gitlens|eam|10.2.2
permute-lines|ear|1.1.0
EditorConfig|Edi|0.15.1
gitlab-workflow|Git|3.0.2
Go|gol|0.14.4
vscode-test-explorer|hbe|2.19.1
vetur|oct|0.24.0
vscode-graphql|Pri|0.2.14
ruby|reb|0.27.0
rewrap|stk|1.12.0
code-spell-checker|str|1.9.0
vscode-ruby|win|0.27.0
vscode-proto3|zxh|0.4.2
gotemplate|cas|0.4.0
vscode-firefox-debug|fir|2.9.0
remote-wsl|ms-|0.44.4
debugger-for-chrome|msj|4.12.8
idl|myt|0.3.1
material-icon-theme|PKi|4.2.0
tcl|sle|0.2.0
haml|vay|1.0.1
vscode-ruby|win|0.27.0

</details>

**Comment by joaomoreno** [comment]
Where do those 7 repositories live? Any idea what's the reason behind VS Code detecting them? Do you open files which reside inside them? Are they submodules?

**Comment by firelizzard18** [comment]
They are submodules within the repository I care about. I do not open files within those submodules. I have no idea why VSCode detects them when I have explicitly disabled submodule detection.

**Comment by joaomoreno** [comment]
> Whenever VSCode feels like it (which is frequent during a rebase), an extra 7 repositories that I do not care about pop up under "Source control providers".

Could you maybe get me exact steps for a situation that causes this?

Once I open your repo, having `git.detectSubmodules` to `false`, I don't see the submodules. So I'm interested in the exact steps that make them appear.

**Comment by firelizzard18** [comment]
Did you clone with `--recursive`? That's the only thing that comes to mind. Currently I'm seeing the problem when using Remote WSL, but I've had the same issue with the same repo in macOS.

**Comment by firelizzard18** [comment]
I'm having trouble reproducing the issue. Maybe a restart fixed it... I was definitely seeing issues while rebasing. I'll comment again if I can reproduce the issue.

**Comment by joaomoreno** [comment]
Cool, let me know!

**Comment by cdoublev** [comment]
Hey, same issue there. If I restart VSCode, it's not detecting submodules. But after some time away from keyboard and opening a file (not from this repository that contains submodules), it happens again.
