### ISSUE TITLE
Go to File... - Misleading placeholder text 

### ISSUE THREAD

**Issue by smdonoghue** [microsoft/vscode#101036]
The use of **append** in placeholder text within the _**Go to File...**_ control can be a little misleading as this implies the go to line/symbol prefix should be added at the end of the search text - if you take the terminology literally.

![image](https://user-images.githubusercontent.com/2563987/85748815-3d076800-b700-11ea-84d7-8a43068c2027.png)

Perhaps prepend, prefix or something similar would be more appropriate?

- VSCode Version: 1.47.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open Go to File... `Ctrl + P`

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
@smdonoghue it **does** mean _append_. For example if you enter `extension.ts:20` it will open that file and position the cursor on line 20. And `extension.ts@deactivate` puts the cursor at the line defining that symbol.

**Comment by smdonoghue** [comment]
@gjsjohnmurray Ah fair enough! I used it mainly for the current file where it's the a prefix.

Good to close if that's the primary use in that case.

**Comment by gjsjohnmurray** [comment]
@smdonoghue yes, working as designed. Please close the issue.
