### ISSUE TITLE
Incorrect indentation on newline

### ISSUE THREAD

**Issue by rmclaughlin-nelnet** [microsoft/vscode#101032]
Issue Type: <b>Bug</b>

Using the following code hit enter after the last line. The new line will be indented to match the closing bracket, which is incorrect. It should be matched up with the indentation of the C in const

```
const res = await fetch(`${URL}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        createCdJson,
      }),
    });
```
![Screen Shot 2020-06-25 at 8 40 10 AM](https://user-images.githubusercontent.com/59625617/85741288-86839300-b6bf-11ea-9610-33669a75c0ac.png)

I also ran the same steps with code --disable-extensions and the same thing happened.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|3.0.1
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
terraform|has|2.0.2
vscode-xml|red|0.12.0
vscode-yaml|red|0.8.0
local-history|xyz|1.8.1

</details>

**Comment by rebornix** [comment]
Our auto indentation support is currently based on brackets and doesn't cover this scenario.
