### ISSUE TITLE
Highlight code line when hovering over Search results, and append line number on result list

### ISSUE THREAD

**Issue by andresargos** [microsoft/vscode#101043]
When using the Search panel, if you hover on the results and the document where that result exists is open, the editor should highlight the code line of the result, to make it easier to find the result.

Furthermore, it would be easier to navigate through the results on the code if the line number is also displayed on the Search panel, next to the result.

**Comment by roblourens** [comment]
There is a setting for your second request - you can enable `search.showLineNumbers`

**Comment by andresargos** [comment]
> There is a setting for your second request - you can enable `search.showLineNumbers`

Thanks for the info, @roblourens!
