### ISSUE TITLE
Open editors

### ISSUE THREAD

**Issue by molisoft** [Microsoft/vscode#10109]
- VSCode Version: 1.3.1
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. 
<img width="257" alt="2016-08-04 11 41 04" src="https://cloud.githubusercontent.com/assets/3153675/17389621/8face2a2-5a38-11e6-9482-99678e221d76.png">

2.

**Comment by aeschli** [comment]
Is this about an untranslated string?

**Comment by jrieken** [comment]
@molisoft please answer the question above
