### ISSUE TITLE
Debug viewlet tittle truncated too early when docked

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#101034]
![image](https://user-images.githubusercontent.com/35271042/85743534-f5112280-b6b8-11ea-805e-2856ccf984fa.png)

Seems there is plenty of space to the left that it shouldn't be truncated yet.

**Comment by isidorn** [comment]
I can not repro this.
Are you doing something special?

![Screenshot 2020-06-25 at 17 03 55](https://user-images.githubusercontent.com/1926584/85745288-e00eb080-b705-11ea-8eb5-bccbe68cf5bf.png)

**Comment by misolori** [comment]
Oops, this was totally my fault (I was testing something out in dev tools). Sorry about that, false alarm.

**Comment by isidorn** [comment]
No worries.
