### ISSUE TITLE
inactiveSelectionForeground not working when there is source control

### ISSUE THREAD

**Issue by hosseinse1919** [microsoft/vscode#101072]
Issue Type: <b>Bug</b>

setting.json
"workbench.colorCustomizations": {
    "list.inactiveSelectionBackground": "#d99741",
    "list.activeSelectionBackground": "#d99741",
    "list.inactiveSelectionForeground": "#000000",
    "list.activeSelectionForeground": "#000000",
 }

inactiveSelectionForegroundnot working when there is source control

**Comment by joaomoreno** [comment]
In which VS Code version is this issue?

**Comment by hosseinse1919** [comment]
version 1.46.1 
![https://www.dropbox.com/s/tlr6zyg4mqwd2rm/55.jpg?dl=0](https://ucff7e2318b0ab90045e559c2416.previews.dropboxusercontent.com/p/thumb/AA2OXdkURgjD6YNa1EK2NelhjAha1-MTfyfPs7JpYFBLWlpuz7nZt_uH7hdhPI8ultOFjFz0p-rAoWstbnE2drRcYKEGlcLoNToG-DvXosSFgyySp79Eu4LHpD_XabR0mWvUSn_vYvFBtS6wSP3wlgKhWR5UI7-3_gd6RFtlbS3JQPpFG3TMhzKqcE0EJnWXTS2LR5rqYyamXkyBQr4c2WNNDa-od7LbnkC58EBdpXJA2Fm4IXcqLHwGpTaY-Y9F3iz7qc3_XtO_aCPDmObugqTaChuziDsBXNL0u2eEd5wCNAIqwVbdIfpNGJvBSKu7nMXPf6JBDwS6wgYpPyYnqWkHeDmzpV7Nu1rLsWeYPnSRvgpbEDXsTec69F6soZuTRBQNYqR8-YnVlRB4kvVt1LQx/p.jpeg?fv_content=true&size_mode=5)

**Comment by hosseinse1919** [comment]
it is work fine with active selection foreground (show color black)

**Comment by joaomoreno** [comment]
Your screenshot doesn't show.

Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by hosseinse1919** [comment]
it does not matter i just report it

**Comment by hosseinse1919** [comment]
screen shop link 

https://www.dropbox.com/s/tlr6zyg4mqwd2rm/55.jpg?dl=0

**Comment by joaomoreno** [comment]
Oh I see, this is as designed. You can use the `explorer.decorations.colors` setting to disable this behavior.
