### ISSUE TITLE
Use native select box instead of custom solution on Windows and Linux

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101045]
Currently we use a native select box on mac, and a custom solution that uses the list on Windows and Linux.
It would be great if we used the native select box on all platforms.

As @bpasero points out the reason why we have a custom solution

"I think theming for one (which maybe by now we can resolve differently) and then often we saw bugs from Electron where the dropdown was located at a wrong location the first time you expanded it. Would probably also need a bit of tweaking the native one to support all the styling. "

**Comment by isidorn** [comment]
I believe the Settings UX usage of the custom dropdown would be the biggest blocker for us to get rid of the custom drop down.
With the native one we could not have such nice separators or the bottom element having a larger height.
So getting rid of the custom dropdown might not be so trivial.

@roblourens let me know what you think

![Screenshot 2020-08-11 at 10 35 23](https://user-images.githubusercontent.com/1926584/89876040-613edb80-dbbe-11ea-8a38-449f984aec08.png)

**Comment by roblourens** [comment]
I don't know the history behind the platform differences. Maybe @sbatten does. But yeah, I think showing the enum descriptions in the custom box is very nice.

**Comment by sbatten** [comment]
I have no additional intel sorry, I made tweaks but the initial version was created before my involvement.

**Comment by isidorn** [comment]
@roblourens I somewhat know the platform differences, I was only interested in your take on settings UX.
Bottom line: the biggest loss would be losing the enum descriptions. I think this is a good enough reason to keep the custom select box around -> moving this to backlog. I am open for ideas for alternatives on how to show enum descriptions.

**Comment by bpasero** [comment]
@isidorn why not keep custom dropdowns exclusive to the settings editor but use native everywhere else? In fact, even on macOS we force enable custom dropdowns for this particular reason.

**Comment by isidorn** [comment]
@bpasero yes, I was thinking of that but then we would still have to keep the custom dropdown implementation which sort of defeats the purpose.

**Comment by bpasero** [comment]
Yeah understood. This probably needs more investigation if we can somehow get a similar behaviour using native dropdown and maybe custom rich hover (Daniel recently added this).

**Comment by isidorn** [comment]
@Tyriar does the custom rich hover need an editor, or might it in theory work with a native select box?

**Comment by bpasero** [comment]
@isidorn there is `IHoverService` to open a hover anywhere in the workbench. I think the challenge is to see if we get hover events for select box items. Probably not on macOS at least...

**Comment by isidorn** [comment]
@bpasero yeah, I think we do not on all platforms. There is only the event when the value is chosen and select box gets closed - I just tryed it out
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement

**Comment by Tyriar** [comment]
Yeah I don't think we enough events for the hover service unfortunately.
