### ISSUE TITLE
Backups disappeared

### ISSUE THREAD

**Issue by fearandtrembling** [microsoft/vscode#101037]
- VSCode Version: 1.46.1
- OS Version: elementary OS 5.1.5 Hera x86_64, kernel: 5.4.21

I had a lot of untitled files opened with writings in it that just disappeared. The tabs are still there, but there is no content. I can close them and not be warned.

I checked the ~./config/Code/Backups/  and there are only 2 files in the 'untitled' folder.

I'm thinking it has to do with snap updating it without warning, I didn't realized I had installed vscode through snap.

Very sad. I like using vscode to write.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
The way the "hot exit" feature works is by saving backups to that Backups folder you checked in shortly after editing a file, this way it is resilient to crashes or if the snap system forcefully shuts down the app. I can't explain what happened and doubt it's related to the snap package, unfortunately I don't think there is anything we can do further here if you've already checked the backups.
