### ISSUE TITLE
There can optional color indication that user can make his own color selection to denote for what each VS instance is intended for

### ISSUE THREAD

**Issue by sntpcvan** [microsoft/vscode#101006]
1. VS code often opened at multiple folders. So, at same time, multiple windows sessions are active which creates confusion where i am working and what each window refers to. 
2. To give user a hint to right window, we can have a feature like outlining or having some indication on each window with some color.

![image](https://user-images.githubusercontent.com/12716881/85670325-6911f180-b6de-11ea-8e6f-181ca8831012.png)

**In attached picture ( i have added color using paint ),** it very easy for to go right window by recognizing the color, It would be Awesome if there is way to do with VS code itself. and allows user can choose his/her own color ( completely optional ).

**Also, this will be an unique one, Not every editor has it right now.**

**Comment by dbaeumer** [comment]
There is an extension doing this: https://marketplace.visualstudio.com/items?itemName=stuart.unique-window-colors
