### ISSUE TITLE
Autocomplete for Angular v10

### ISSUE THREAD

**Issue by jcpalma** [microsoft/vscode#101065]
- VSCode Version: 1.46.1
- OS Version: macOS Catalina 10.15.5

Steps to Reproduce:

1. Update to Angular v10.
2. Create an Application
3. Autocomplete doesn't work when you add directives, attributes define in components or another stuff. 

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Since this only happens when extensions are enabled, it sounds like one of them is causing this (likely your angular extension)

Please try tracking down which extension is to blame and file an issue against them

**Comment by jcpalma** [comment]
Hi @mjbvz, thanks for your answer, I'll check what you have to say.
