### ISSUE TITLE
Terminal cursor does not invert text color

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#10100]
Bug present in July but it's low impact so pushing fix to August.

![image](https://cloud.githubusercontent.com/assets/2193314/17382218/92c275f6-5984-11e6-86d8-05b9c06f3826.png)

**Comment by mirao** [comment]
Just noticed it in 1.4.0 on Ubuntu 16.04.
Workaround for me: `"terminal.integrated.cursorBlinking": true` (it's actually default setting in gnome-terminal that I use in Ubuntu)

**Comment by Tyriar** [comment]
@mirao it was the default setting previously but some team members thought it should be disabled by default since that's the default on Mac & Windows.

**Comment by mirao** [comment]
@Tyriar : Thanks for info, no problem for me. I can live with both settings :smile:
