### ISSUE TITLE
Search  in a file that is not part of the open folder does not work

### ISSUE THREAD

**Issue by leorana** [microsoft/vscode#101049]
Issue Type: <b>Bug</b>

I have VS code open to a specific folder sets. If I use VS code to open a file that is not in the current open editor vide and try to search in that file the search will not find antying even if that file contrains the search parameters. 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (15.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
badgerdevtools|Dan|0.0.8
color-manager|roy|0.5.7
perforce|sle|3.2.0

</details>

**Comment by roblourens** [comment]
Please see these tips and let me know whether they help https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results

**Comment by leorana** [comment]
I have "search.useIgnoreFiles": false in the settings. I am searching JSON files. I did not have this issue until the latest update. 
[https://imgur.com/a/b1dHW2t](https://imgur.com/a/b1dHW2t)

**Comment by roblourens** [comment]
You have the "whole word" option selected, so it will only match "tex" as a complete word
