### ISSUE TITLE
Support for using .git/SQUASH_MSG in Git commit message box

### ISSUE THREAD

**Issue by philipstarkey** [microsoft/vscode#101078]
Currently the VS Code Git commit message box automatically synchronises with the contents of .git/MERGE_MSG (provided you have not entered your own commit message yet into VS Code).

I would like to request support for VS Code to do the same with .git/SQUASH_MSG (produced when running `git merge <branch> --squash`). This would provide better integration between VS code git related VS Code extensions which often have the ability to perform a squash merge via the extension GUI but do not typically replicate any of the existing VS Code git interface (commit message box and changed file list).

**Comment by daniel-j-davis** [comment]
@joaomoreno I wouldn't mind taking this on, and I've looked through the code so I have a pretty good idea of what's required to implement this. Just one question, though — is there any situation where `.git/MERGE_MSG` and `.git/SQUASH_MSG` are both present? If so: which one do we think should take precedence as the 'default' commit message?

**Comment by philipstarkey** [comment]
@daniel-j-davis my suggestion would be to follow what git-gui does since it's bundled with git. Looks like it preferences MERGE_MSG over SQUASH_MSG (see [here](https://github.com/git/git/blob/ae92ac8ae3838e72840f5d019195bb9c0c9e7b0e/git-gui/git-gui.sh#L1480))

**Comment by daniel-j-davis** [comment]
That makes sense, and that's what I was thinking too. I'll put a PR in shortly!

**Comment by isidorn** [comment]
I got this to partially work by:
1. Having a `SQUASH_MSG` file with some content like "HELLO"
2. Creaing a local branch `git co -b isidorn/deleteme`
3. `git merge master --squash`
4. The `SQUASH_MSG` file sometimes gets filled with content, like the following
5. SO it seems like the content of the `SQUASH_MSG` file is not constant for me, and changes once I do a squash

Reopening this for discussion. I also might be doing something wrong.
Bonus bug: when chaning the content of the SQUASH_MSG the scm input does not reg resized and ends up looking broken (picture attached).
So I would recommend that we revert this PR and polish it a bit more.

```
Squashed commit of the following:

commit 639a21b145ba38007a2b5ee9d4233ac6a6067e89
Author: Daniel Imms <tyriar@tyriar.com>
Date:   Tue Jun 30 06:39:30 2020 -0700

    Add ending period to terminal launch notification messages
    
    Fixes #101344

commit 01d0314308fdf83801c3d7abf43b7a2702ea9263
Author: Daniel Imms <tyriar@tyriar.com>
Date:   Tue Jun 30 05:22:31 2020 -0700

    Change troubleshoot button to 'Open Help'
    
    Fixes #101345
```

![Screenshot 2020-06-30 at 16 02 54](https://user-images.githubusercontent.com/1926584/86135544-42dbbf80-baeb-11ea-9a47-4f9a17790955.png)

**Comment by daniel-j-davis** [comment]
It worked fine (and always displayed the intended squash msg), but maybe it's because I was only squashing another branch that only had one commit? I concur that it seems like the contents of SQUASH_MSG aren't always consistent though, now that I've tried with a branch with more than one commit. I guess the question is, if SQUASH_MSG actually does contain the messages for all of the squashed commits, which one do you expect to see? Would other applications just show you the contents of that file as the message?

As for the bonus bug, is that issue exclusive to SQUASH_MSG or does it also happen if you change the contents of MERGE_MSG? @isidorn

**Comment by joaomoreno** [comment]
@isidorn You're not supposed to manually create or edit the `SQUASH_MSG` file. This is a file created by git. during the `git merge <branch> --squash` command. 🤔 

Thanks for the input box issue.

**Comment by philipstarkey** [comment]
> **EDIT**: It seems like it displays all of the squashed commits in one message, prefaced by
> 
> ```
> Squashed commit of the following:
> <some commits>
> ...

This was the intended behaviour behind this feature request. I'm not expecting VS Code to do anything magical here with SQUASH_MSG. It should just be taking the entire contents of the file as other graphical git tools do (and as a command line call to `git commit` does if SQUASH_MSG exists).

I do not think the PR needs reverting.

**Comment by joaomoreno** [comment]
Added another commit, since the `MERGE_MSG` can exist but just have no content. In that case we should take `SQUASH_MSG`. 

@isidorn Please verify once again, now the feature is clearer.

**Comment by isidorn** [comment]
Sorry for the confusion, just was not very clear to me. 
I will verify this later today.

**Comment by isidorn** [comment]
Adding verified label since the git commit gets nicely preopulated with the squash message.
