### ISSUE TITLE
cammand not working

### ISSUE THREAD

**Issue by Goutampatidar** [microsoft/vscode#101044]
We have written the needed data into your cli
Issue Type: <b>Performance Issue</b>

I am facing this problem from the first day of installation'

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (1.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    76	 10412	code main
    0	   272	  4464	   gpu-process
    0	    81	  5492	   shared-process
    0	    55	  6424	   electron-crash-reporter
    0	    38	  7516	   utility
    0	    84	  9116	   window (Issue Reporter)
    0	   199	 10920	   window (beatifull polygon .cpp - couresera - Visual Studio Code)
    0	     6	   840	     console-window-host (Windows internal process)
    0	   119	  1952	     extensionHost
    0	    58	  6452	       c:\Users\hp\.vscode\extensions\ms-vscode.cpptools-0.29.0-insiders\bin\cpptools.exe
    0	    10	  3564	         console-window-host (Windows internal process)
    0	    18	  9712	         "c:\Users\hp\.vscode\extensions\ms-vscode.cpptools-0.29.0-insiders/bin/cpptools-srv.exe" 6452 0
    0	    16	 10716	         "c:\Users\hp\.vscode\extensions\ms-vscode.cpptools-0.29.0-insiders/bin/cpptools-srv.exe" 6452 1
    0	    21	 10968	         "c:\Users\hp\.vscode\extensions\ms-vscode.cpptools-0.29.0-insiders/bin/cpptools-srv.exe" 6452 2
    0	     4	  2168	     C:\Windows\System32\cmd.exe
    0	     4	  3408	     C:\Windows\System32\cmd.exe
    0	    14	  3608	     watcherService 
    0	    11	  2944	       console-window-host (Windows internal process)
    0	     6	  3952	     console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (beatifull polygon .cpp - couresera - Visual Studio Code)
|    Folder (couresera): 25 files
|      File types: cpp(7) o(4) exe(3) json(1) cbp(1) depend(1) layout(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
c-cpp-compile-run|dan|1.0.11
code-runner|for|0.10.0
cpptools|ms-|0.29.0-insiders

</details>
pboard because it was too large to send. Please paste.

**Comment by Goutampatidar** [comment]
![Untitled](https://user-images.githubusercontent.com/55948914/85761764-b61eb380-b730-11ea-87ec-e5d8d72378b4.png)

here is the screenshot of the issue.

**Comment by dbaeumer** [comment]
@Goutampatidar can you please provide the information from the clipboard when you are seeing this.

**Comment by Goutampatidar** [comment]
Are you asking information about output terminal where out is show.
There is no any information other than in screen shot.
 If other than it please make me understand.

**Comment by gjsjohnmurray** [comment]
@Goutampatidar either rename your source file `beautiful polygon .cpp` so the name doesn't include spaces, or put quotes round the filename when using it as an argument to your g++ command.

**Comment by joaomoreno** [comment]
As @gjsjohnmurray, you need to wrap the filename in quotes, if it has any spaces, otherwise `g++` won't be able to figure it out.
