### ISSUE TITLE
Confusing JSON string warning

### ISSUE THREAD

**Issue by astrostl** [microsoft/vscode#101084]
The small Azure ARM template inside [arm.json.zip](https://github.com/microsoft/vscode/files/4834983/arm.json.zip) is returning the warning `String does not match the pattern of "^[-\w\._\(\)]+$".`. The string is copied and pasted from the section above it, which does not return a warning. Any ideas on what the trigger is here?

**Comment by aeschli** [comment]
This regex is from a rule defined in the schema of the ARM template: https://schema.management.azure.com/schemas/2018-05-01/Microsoft.Resources.json#/subscription_resourceDefinitions/resourceGroups

resourceGroup can only consist of letters, minus, dot and `(` `)`

If you feel that rule is wrong, file an issue against https://github.com/Azure/azure-resource-manager-schemas
