### ISSUE TITLE
Preferences Sync: Theme fails to apply

### ISSUE THREAD

**Issue by developit** [microsoft/vscode#101027]
- VSCode Version: 1.47.0-insider (b9d7ec9ff367a8e59fe4cc2abee605a55be180e8) 2020-06-19T22:25:04.581Z (5 days ago)
- OS Version: Intel Mac OS X 10_14_6
- Browser: Chrome 84 (stable, 84.0.4147.56)

### Steps to Reproduce:

1. Create a codespace (codespace 1) and set the theme to "GitHub Dark"
2. Enable preferences sync using the GitHub provider
3. Create a second codespace (codespace 2)
4. Enable preferences sync, select all groups, choose "replace local"
5. The "GitHub Dark" theme is not applied.

### Workaround:

I have discovered that the following can be used to fix the issue:

1. load the codespace (codespace 2)
2. open Chrome DevTools once loaded. Ensure caching is _not_ disabled and "bypass SW" is _not_ enabled.
3. Force a ServiceWorker update using the "update" link in DevTools' Applications tab
4. In the VSCode UI, change the theme to "GitHub Dark"

If it doesn't work the first time, toggle "Disable cache" in DevTools' Network panel to clear the cache and try again.

Does this issue occur when all extensions are disabled?: N/A (preferences sync gets disabled)

**Comment by sandy081** [comment]
Can you please provide preference sync logs when you enable preferences sync on second codespace?
