### ISSUE TITLE
Markdown preview -  does not scroll correctly with cursor pointing when scrolling with images in downward direction

### ISSUE THREAD

**Issue by surpavan** [microsoft/vscode#101023]
- VSCode Version:1.46.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. With having lot of images
2. Scrolling down does not move the preview along with it, i guess it is going by line space/height and not taking image height into account to scroll down.
3. But scrolling up works fine.

Does this issue occur when all extensions are disabled?: Yes/No   Yes- error continues even when all extensions are disabled.

**Comment by mjbvz** [comment]
Can you provide a screen recording of the problem and example markdown code I can use to reproduce it?
