### ISSUE TITLE
Need option to copy lines from parts of code in previous version (git) and reach olders versions of code

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#101091]
Red highlited line can't be selectable with text - need this
![VSC_git 2](https://user-images.githubusercontent.com/25403861/85832854-1b09f600-b791-11ea-8d4f-c592a5649bdd.png)
Want meet older version of his code part
![VSC_git 1](https://user-images.githubusercontent.com/25403861/85833016-599fb080-b791-11ea-8677-415130c4c961.png)

**Comment by joaomoreno** [comment]
Click on the light bulb icon: 
![image](https://user-images.githubusercontent.com/22350/86016306-e745ff00-ba22-11ea-8d59-5dd63cfad754.png)

**Comment by ManPython** [comment]
@joaomoreno thx, but I need to select some part. Don't see sense to turn of copy and selection
