### ISSUE TITLE
Remote SSH adds the ability to show hidden files

### ISSUE THREAD

**Issue by littleShy** [microsoft/vscode#101001]
How can i open hide files on remote host? I did not find any function like this.

**Comment by roblourens** [comment]
Can you explain what you mean by "hidden files"?

**Comment by roblourens** [comment]
You might not be seeing files that are hidden by the patters in the `files.exclude` setting.

**Comment by littleShy** [comment]
For example .conan/ and .bash_rc in my home directory

**Comment by roblourens** [comment]
Still need more details about exactly what you are trying to do.
