### ISSUE TITLE
Allow customizing whitespace characters

### ISSUE THREAD

**Issue by darsain** [microsoft/vscode#101013]
A way to customize how vscode renders whitespace characters. I don't mind the dots for spaces, but I really hate the arrows with empty space for tabs:

![arrows][1]

It's such a poor visualization of tab characters. I'd much rather have lines with gaps like sublime text does it:

![lines][2]

To my knowledge, there is currently no way how to achieve this.

  [1]: https://i.stack.imgur.com/6Du1N.png
  [2]: https://i.stack.imgur.com/iP5Fe.png

**Comment by gjsjohnmurray** [comment]
@ darsain interesting idea. It appears you have set `"editor.renderIndentGuides": false`

I experimented with some simple source changes [here](https://github.com/microsoft/vscode/blob/5de3aa7eace377f095000787129534a11b54734f/src/vs/editor/common/viewLayout/viewLineRenderer.ts#L867-L877) 

Current with `"editor.renderIndentGuides": false`

![image](https://user-images.githubusercontent.com/6726799/85703160-fe10ec80-b6d6-11ea-8062-1293e15ecd6a.png)

and with `"editor.renderIndentGuides": true` (the default)

![image](https://user-images.githubusercontent.com/6726799/85702942-cc982100-b6d6-11ea-93af-91fe4d3e326a.png)

Experimental change, variant 1:

![image](https://user-images.githubusercontent.com/6726799/85703302-213b9c00-b6d7-11ea-9809-d32c20f4ae22.png)

and

![image](https://user-images.githubusercontent.com/6726799/85703392-387a8980-b6d7-11ea-8f6f-6df2831aee04.png)

My changes for variant 1:
![image](https://user-images.githubusercontent.com/6726799/85703652-78da0780-b6d7-11ea-88c7-df356e10aeca.png)

Variant 2, using character 0x250C (Box Drawings Light Down And Right) instead:

![image](https://user-images.githubusercontent.com/6726799/85704315-17666880-b6d8-11ea-8a03-e6ce3d2da4cd.png)

and

![image](https://user-images.githubusercontent.com/6726799/85704502-411f8f80-b6d8-11ea-8e16-3490d261f394.png)
 

Obviously any alternative appearance would need to be placed behind a setting and default to the current behaviour.

**Comment by darsain** [comment]
Yes, I have the intend guides off. For me, they just add visual clutter for no benefit.

And I don't want to be rude, but none of the examples you posted look nice :worried:

Does vscode's text rendering not allow to just render a simple line across a tab width? It can render boxes (text selection) so can't it just render a box with 1px height?

**Comment by gjsjohnmurray** [comment]
@darsain thanks for your feedback. For a quick prototype (I'm not part of the VS Code core team) I needed to use a character.

I'm guessing you won't like this variant either because it doesn't show gaps in the horizontal line to denote the individual tabs as you showed in your ST example:

![image](https://user-images.githubusercontent.com/6726799/85712593-63b5a680-b6e0-11ea-842f-9351444c8660.png)

**Comment by darsain** [comment]
Yes, the gaps to denote separate indentation levels are of course important. But this is just a couple pixels away from perfection :)

**Comment by darsain** [comment]
This is one of those things that people appreciate when it's in but not many will go out of their way and try to research/request unless they are pedantic like me.

It's a valuable feature that would improve whitespace visualization for everyone using tabs, and bring vscode in line with other editors that do it by default, but the only way how it'll get 20 up-votes is if I go and brigade it, which I don't want to do.

This system sux :(
