### ISSUE TITLE
输出窗口编码格式

### ISSUE THREAD

**Issue by qingfeng346** [Microsoft/vscode#10108]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. 输出窗口 能调 输出 编码格式吗

**Comment by zouyx** [comment]
这里开发的有人会中文吗........

**Comment by rebornix** [comment]
He wants to change the encoding in output pane.

@qingfeng346 any reason for this kind of request?

**Comment by ZCShou** [comment]
@zouyx 当然有，不全是老外！

**Comment by aeschli** [comment]
Which output pane? Git, tasks, debug console.
Please give an example where you see wrong encoding. The problem is maybe at the place the output is created.

**Comment by leafli7** [comment]
Usually we save the source code in UTF-8, but the panel of cmd(ctrl+` to call) will print in GBK(Chinese), so I want to know how to change it to UTF-8?

**Comment by Tyriar** [comment]
You should file this against https://github.com/sourcelair/xterm.js

**Comment by xlsfs** [comment]
![20170328145628](https://cloud.githubusercontent.com/assets/7886342/24392523/d7f1472c-13c6-11e7-87d6-cd7ef5037bf7.png)
请问，怎么改变输出面板的编码格式。
How change output panel encoding.I need GBK,please tell me,thanks.

**Comment by dyh333** [comment]
@xlsfs 兄弟 你解决了吗？

**Comment by overing** [comment]
HKEY_CURRENT_USER\Console\%SystemRoot%_system32_cmd.exe\CodePage=65001(DEC)

**Comment by navono** [comment]
@overing CodePage 是什么类型？

**Comment by kookpua** [comment]
@xlsfs 
@dyh333 
1.解决vccode调试控制台官方内容乱码
点击菜单栏的任务  配置任务 点击 打开task.json文件
修改task.json
为以下内容就好了
`{
    "version": "0.1.0",
    "tasks": [
        {
            "taskName": "build",
            "command": "cmd",
            "suppressTaskName": true,
            "args": [
                "/c chcp 65001 >nul && dotnet build ${workspaceRoot}/projectName.csproj"
            ],
            "isBuildCommand": true,
            "problemMatcher": "$msCompile"
        }
    ]
}`



2.解决控制台自己输出的乱码

` static void Main(string[] args)
        {
            //解决输出中文乱码的问题
            Console.OutputEncoding = Encoding.UTF8;
            // Console.WriteLine("Message :{0} ", "請求成功1");
        }
`

**Comment by dyh333** [comment]
@kookpua  哥们 我按你说的方法试了 输出控制台还是乱码 麻烦帮忙看一下
![image](https://user-images.githubusercontent.com/1221313/31800060-a79a7bb0-b570-11e7-868d-bc89cd98c758.png)
