### ISSUE TITLE
Path to tasks.json 'process' is incorrectly resolved in Windows Visual Studio Codespaces

### ISSUE THREAD

**Issue by gregg-miskelly** [microsoft/vscode#101073]
- VSCode Version: 1.45.1
- OS Version: Windows 10.0.19041

This issue is from a bug opened by @kendrahavens (https://github.com/OmniSharp/omnisharp-vscode/issues/3878)

### Steps to Reproduce:
1. Create a VSCode [Codespaces](http://online.visualstudio.com/) instance with default .NET Core console app template in **Windows** Codespaces (doesn't repro with Linux)
2. Open with "Connect" option to open with VSCode in the web browser
3. Accept pop-up to load debug assets
4. Run the `build` task.

### Result:
tasks.json tries to run dotnet.exe from `C:\workspace\dotnet` instead of from where it is installed, and so it fails.

### Terminal output
```console
> Executing task: C:\workspace\dotnet build C:\workspace/TestCodespacesWindowsAndVSCode/TestCodespacesWindowsAndVSCode/TestCodespacesWindowsAndVSCode.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

The terminal shell path "C:\workspace\dotnet" does not exist

Terminal will be reused by tasks, press any key to close it.
```

### tasks.json
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/TestCodespacesWindowsAndVSCode/TestCodespacesWindowsAndVSCode/TestCodespacesWindowsAndVSCode.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/TestCodespacesWindowsAndVSCode/TestCodespacesWindowsAndVSCode/TestCodespacesWindowsAndVSCode.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "${workspaceFolder}/TestCodespacesWindowsAndVSCode/TestCodespacesWindowsAndVSCode/TestCodespacesWindowsAndVSCode.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}
```

**Comment by alexr00** [comment]
For this step:

> Create a VSCode Codespaces instance with default .NET Core console app template in Windows Codespaces (doesn't repro with Linux)

How do I get the default .NET Core console app template?

**Comment by kendrahavens** [comment]
@alexr00 If dotnet is installed, you can run `dotnet new console` from the terminal. [docs](https://docs.microsoft.com/en-us/dotnet/core/get-started?tabs=windows)

**Comment by alexr00** [comment]
Looks like `findExecutable` needs to be moved to the extension host. This wasn't needed before because it's only required for Windows, and we didn't have Windows remotes.

**Comment by allan-mobley-jr** [comment]
# Visual Studio Codespaces Insiders

Encountering the same issue with `dotnet new webapp`.

* Running codespace from Chrome browser with Insiders switch turned on under settings.
* Self-hosted Windows machine

**Comment by alexr00** [comment]
I tested with an SSH Windows remote, and I see the executable path being correctly found now. Please let me know if you try it out in the next insiders build!

**Comment by roblourens** [comment]
I'm using a windows codespace, with the build from 7/23, and I think I still see this issue

![image](https://user-images.githubusercontent.com/323878/89568263-e64d7d80-d7d7-11ea-9f5f-3359d8b281d9.png)

**Comment by alexr00** [comment]
Interesting. I tried it with a windows codespace and got:

```
C:\Program Files\dotnet\dotnet.exe build C:\workspace/TestCodespacesWindowsAndVSCode/TestCodespacesWindowsAndVSCode/TestCodespacesWindowsAndVSCode.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <
```

This is with the build from 8/3. Not sure what could be going on here. I'm going to close and see if someone else can verify.
