### ISSUE TITLE
vscode-server's node process consume 100% cpu

### ISSUE THREAD

**Issue by VmFree** [microsoft/vscode#101080]
Hi, here the top & ps information:
===================================
top - 09:19:48 up 12:14,  0 users,  load average: 0.52, 0.58, 0.59
Tasks:  13 total,   1 running,  12 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5.1 us, 20.4 sy,  0.0 ni, 74.4 id,  0.0 wa,  0.1 hi,  0.0 si,  0.0 st
MiB Mem :   8114.4 total,   4732.0 free,   3158.4 used,    224.0 buff/cache
MiB Swap:  19200.0 total,  19198.5 free,      1.5 used.   4825.4 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 1352 mical     20   0 1028500  56680  46024 S 100.0   0.7   6:10.91 node
    1 root      20   0    8324    156    132 S   0.0   0.0   0:00.07 init
  123 root      20   0    8328    156    120 S   0.0   0.0   0:00.00 init
  124 mical     20   0   18348   4020   3916 S   0.0   0.0   0:00.41 bash
 1299 root      20   0    8328    156    120 S   0.0   0.0   0:00.00 init
 1300 mical     20   0   10656    688    652 S   0.0   0.0   0:00.00 sh
 1301 mical     20   0   10656    748    716 S   0.0   0.0   0:00.04 sh
 1306 mical     20   0   10656    720    684 S   0.0   0.0   0:00.01 sh
 1308 mical     20   0  952504  37876  21984 S   0.0   0.5   0:01.41 node
 1326 mical     20   0  861116  21644  13068 S   0.0   0.3   0:00.33 node
 1371 mical     20   0   18048   3500   2092 S   0.0   0.0   0:00.03 bash
 1398 mical     20   0  561656  18520  11188 S   0.0   0.2   0:00.15 node
 1405 mical     20   0   18904   2144   1520 R   0.0   0.0   0:00.00 top
------------------------------------------------------------------------------
mical     1308  1306  0 09:13 tty1     00:00:02 /home/mical/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
node /home/mical/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/main.js  --port=0 --use-host-proxy --fileWatcherPolling=0
mical     1326  1308  0 09:13 tty1     00:00:00 /home/mical/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
node /home/mical/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/bootstrap-fork --type=watcherService
mical     1352  1308 98 09:13 tty1     00:19:42 /home/mical/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
node /home/mical/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/mical/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/uriTransformer.js --useHostProxy=
mical     1398  1352  0 09:18 tty1     00:00:01 /home/mical/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
node /home/mical/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=1352

as you can see pid 1352 **ALWAYS** consume 100% CPU

I use win10 and WSL ：
--------------------------
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

Regards

**Comment by VmFree** [comment]
since the --type=extensionHost, I try to disable extension one by one, finally, the problem is caused by "Remote - WSL" v.0.44.4......... if it is closed, WSL won't work at all

**Comment by VmFree** [comment]
done by : https://github.com/microsoft/vscode-remote-release/issues/2921

**Comment by WuHeartGod** [comment]
I have the same problem after I upgraded Ubuntu18 to Ubuntu20.
