### ISSUE TITLE
Internal Compiler Error

### ISSUE THREAD

**Issue by ydasc815** [microsoft/vscode#101088]
Issue Type: <b>Bug</b>

Following error occured while declaring a boolean array bool a[2][n+1] = {0};

during RTL pass: expand
c:\Users\Aditya\Documents\cpp\cp_prac.cpp: In function 'int main()':
c:\Users\Aditya\Documents\cpp\cp_prac.cpp:9271:10: internal compiler error: in make_decl_rtl, at varasm.c:1340
 9271 |     bool a[2][n+1] = {0};
      |          ^

c:\Users\Aditya\Documents\cpp\cp_prac.cpp:9271:10: internal compiler error: Aborted
g++.exe: internal compiler error: Aborted signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
The terminal process terminated with exit code: 1

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
python|ms-|2020.6.90262
cpptools|ms-|0.29.0-insiders
java|red|0.63.0
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by dbaeumer** [comment]
@ydasc815 please report the issue against the CPP extension.
