### ISSUE TITLE
No git executable found

### ISSUE THREAD

**Issue by Brezels-Empire** [microsoft/vscode#101148]
Issue Type: <b>Bug</b>

No git executable found. Please install git and if required set it in your path. You may also set 'git Command'.

How does one go about intalling git, which extension is it ???

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  J2900  @ 2.41GHz (4 x 2417)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (162)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
better-comments|aar|2.0.5
project-manager|ale|11.1.0
angular1-code-snippets|ale|0.0.3
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.1000.0
angulardoc-vscode|Ang|6.1.3
git-tools|ank|1.0.0
git-urgent|ara|1.0.0
gitstash|art|3.2.0
scanner-js-twain-wia-javascript-browser-scan|asp|2.0.2
git-bundle|baq|0.0.1
git-temporal-vscode|bee|1.0.0
vscode-node-readme|ben|3.0.2
node-json-autocomplete|bhs|0.1.3
git-easy|bib|1.11.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
jsrefactor|cms|2.20.6
vscode-devtools-for-chrome|cod|0.0.7
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.1.4
angular-schematics|cyr|4.3.0
split-html-attributes|dan|1.0.10
angular2-snippets|dan|1.0.21
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|2.1.5
angular-productivity-pack|dev|2.5.0
angular-extension-pack|dog|8.0.1
git-extension-pack|don|0.1.3
githistory|don|0.6.5
javadebugger|don|0.1.5
vscode-git-pack|dse|1.4.0
git-cheatsheet|dzh|1.1.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.12
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.1.0
rightclick-git|Eve|1.0.0
git-commits|Exe|3.6.0
vscode-git-history|fab|2.0.5
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.9.0
git-extensions-for-vs-code|for|1.1.2
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
vscode-git-log-line|gar|0.0.1
html-slim-scss-css-class-completion|gen|1.7.5
ultimate-angular-extension-pack|geo|1.0.0
vscode-angular-html|gha|1.7.0
vscode-pull-request-github|Git|0.17.0
json2ts|Gre|0.0.6
todo-tree|Gru|0.0.177
angular-bootstrap|her|4.0.9
npm-dependency-links|her|1.1.0
GitHubIssues|Hoo|0.1.2
vscode-git-tags|how|1.4.4
openchrome|hua|0.0.3
githd|hui|2.2.4
codewind-node-profiler|IBM|0.9.0
output-colorizer|IBM|0.1.2
angular2-switcher|inf|0.3.3
vscode-git-add-and-commit|iva|2.1.1
vscode-angular2-emmet|jak|2.0.3
search-node-modules|jas|1.3.0
NodeAssertionSnippets|jay|0.1.0
node-module-intellisense|jhe|1.6.0
docthis|joe|0.7.1
angular-file-changer|joh|0.0.4
angular-essentials|joh|9.0.1
Angular1|joh|0.2.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.2
chrome-app-devtools|jon|1.1.1
auto-comment-blocks|kev|1.0.1
vscode-codemetrics|kis|1.24.0
vscode-commitizen|Kni|0.8.4
vscode-github|Kni|0.30.3
refactorix|kri|0.3.6
git-indicators|lam|2.1.2
node-module-intellisense|lei|1.5.0
git-tree-compare|let|1.9.1
lirongfei-open-chrome|lir|0.0.2
angular-extension-pack|loi|0.7.1
nodejs-repl|los|0.5.15
git-graphy|mar|1.0.14
Angular2Tests|Mar|0.7.3
json-to-ts|Mar|1.7.5
start-git-bash|McC|1.2.1
git-graph|mhu|1.24.0
gitignore|mic|1.0.1
Angular-BeastCode|Mik|8.1.2
vscode-exec-node|mir|0.5.1
vscode-scss|mrm|0.9.0
vscode-azurefunctions|ms-|0.22.1
azure-account|ms-|0.8.11
github-issues-prs|ms-|0.9.2
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2377
vsliveshare-audio|ms-|0.1.85
chrome-tools|msh|0.0.3
debugger-for-chrome|msj|4.12.8
debugger-for-chrome-nightly|msj|2020.2.15300
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
git|NAV|1.6.12
ng-fortytwo-vscode-extension|NG-|0.0.9
gremlins|nho|0.23.0
vscode-for-node-js-development-pack|nod|2.0.1
angular-console|nrw|12.0.0
vscode-html-scss|P-d|0.0.42
gitpatch|par|0.2.1
open-html-in-browser|pea|2.1.3
vscode-versionlens|pfl|1.0.8
material-icon-theme|PKi|4.2.0
angular-extension-pack|pli|0.0.5
start-git|pol|0.0.6
git-file-history|pom|1.0.1
vscode-css-peek|pra|3.0.2
vscode-git-flow|Psy|0.4.2
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
project-snippets|reb|0.5.0
format-html-in-php|rif|1.6.2
vscode-coverage-gutters|rya|2.4.4
awesome-angular-pack|sal|3.0.0
comment-ts|sal|0.9.11
copy-text|sal|0.4.3
git-merger|sha|0.4.1
code-settings-sync|Sha|3.4.3
git-autoconfig|shy|0.0.1
simontest|Sim|1.8.8
kx-vscode-angular-context-creator|sju|0.1.3
vscode-smoothtype|spi|1.2.0
git-prefix|srm|1.2.0
autoimport|ste|1.5.3
code-spell-checker|str|1.9.0
angular-template-formatter|str|0.1.2
move-ts|str|1.12.0
angulargenerator|Tal|0.0.1
git-commit-format|tkw|1.1.0
Angular2|UVB|0.4.1
web-extension|Vai|0.1.0
vscode-angular-support|vis|0.1.4
gitblame|wad|4.0.1
nodejs-extension-pack|wad|0.1.9
NodeJS-extension-pack|wal|0.0.2
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
github-detial-comment|wk-|0.0.9
nativescript-ng2-snippets|www|2.0.1
JavaScriptSnippets|xab|1.8.0
vscode-angularlens|xin|1.0.1
yannis2707s-nodejs-extension-pack|yan|0.1.0
auto-git|zei|1.0.3
html-css-class-completion|Zig|1.19.0
vscode-open-in-github|ziy|1.3.6

(8 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
The section at https://code.visualstudio.com/docs/editor/versioncontrol#_git-support includes the link you need.
