### ISSUE TITLE
can't log in to git via extension

### ISSUE THREAD

**Issue by buchananwp** [microsoft/vscode#101190]
Issue Type: <b>Bug</b>

try to clone a repo
send to authentication page via MSFT
log in via 2FA
successful auth
notification to re-open VSCode
failure auth notification with no idea what went wrong

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.6.89148
vscode-yaml|red|0.8.0
vscode-icons|vsc|10.1.1

</details>

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the auth window?

**Comment by buchananwp** [comment]
it seems to be working now. Not sure how to replicate, sorry. I'll start
another bug if i have more issues.

Best,
Will
