### ISSUE TITLE
Semantic highlighting not working with a custom theme.

### ISSUE THREAD

**Issue by rchoudhary** [microsoft/vscode#101168]
- VSCode Version:  1.46.1
- OS Version: Mac OS 10.14.6 (Mojave)

Semantic highlighting doesn't seem to work with the [OneHalf Light Theme](https://github.com/sonph/onehalf).

First I added the following to my VS Code settings:

```
    "C_Cpp.enhancedColorization": "Enabled",
    "editor.semanticTokenColorCustomizations": {
        "enabled": true
    },
    "editor.tokenColorCustomizations": {
        "[onehalf-light]": {
            "textMateRules": [
                {
                    "scope": "entity.name.type.struct",
                    "settings": {
                        "foreground": "#FF0000",
                        "fontStyle": "italic bold underline"
                    }
                }
            ]
        }
    },
```

That last `tokenColorCustomazation` bit is just because struct names aren't colored by the OneHalf Light theme due to a small bug.

I created a small C++ file on my local machine and opened it with VS Code.

Here is what the code looks like when colored with OneHalf Light in VS Code:

<img width="245" alt="Screen Shot 2020-06-26 at 5 52 24 PM" src="https://user-images.githubusercontent.com/4595638/85908178-adce8300-b7d9-11ea-8a7d-c1132d820618.png">

The types of `b` and `c` are not colored. If I view the same snippet of code with the default Light+ theme, semantic coloring works perfectly:

<img width="248" alt="Screen Shot 2020-06-26 at 5 51 18 PM" src="https://user-images.githubusercontent.com/4595638/85908200-c5a60700-b7d9-11ea-979c-6ff909e38f42.png">

I have both the [C/C++](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) extension by Microsoft and the [Better C++ Syntax](https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-cpp-syntax) extension by Jeff Hykin installed and enabled.

**Comment by aeschli** [comment]
I believe the c/c++ has not yet switched to the new semantic tokens API (they still use their own infrastructure).

You can verify this by using the `Developer: Inspect Editor Tokens and Scopes` command on the symbol.

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/85990073-bd281900-b9f1-11ea-9286-ef8c43212c59.png)

-> no section 'semantic tokens' yet.

Closing the issue. Please track the C++ issue to know when the switch happens

**Comment by rchoudhary** [comment]
Hi @aeschli, I'm confused by the statement "I believe the c/c++ has not yet switched to the new semantic tokens API (they still use their own infrastructure)"

Why does the in-built Light+ theme work but not a custom theme?

In any case, switching to Atom One Light theme instead has fixed the issue; it seems to highlight correctly:

<img width="235" alt="Screen Shot 2020-06-29 at 3 34 15 PM" src="https://user-images.githubusercontent.com/4595638/86053364-00987c80-ba1e-11ea-909c-5b51c3ab8fcb.png">

**Comment by aeschli** [comment]
All I meant to say is that the issue needs to be filed against the C++ extension...
https://github.com/microsoft/vscode-cpptools
