### ISSUE TITLE
vscode python debugging expand the content wrapped by the curly bracket in args automatically 

### ISSUE THREAD

**Issue by Lukeeeeee** [microsoft/vscode#101177]
When I am debugging the python script with passed in arguments defined by `args` section in the `launch.json` which contains curly brackets, VS code seems automatically expand the content wrapped by the bracket splitted by comma, e.g., `{1,2,3}->[1, 2,3]`

- VSCode Version: 1.46.1
- OS Version: macos 10.15.5 

Steps to Reproduce:

1. set an arg in python launch {1,2,3}
![image](https://user-images.githubusercontent.com/9161548/85915460-4583ae00-b87a-11ea-94a1-4fd99945fa59.png)

2. monitor the sys.argv, the {1,2,3} is expanded to 1,2,3
![image](https://user-images.githubusercontent.com/9161548/85915480-61874f80-b87a-11ea-8631-fe0ac3200d1b.png)

How to disable it?

Does this issue occur when all extensions are disabled?: only python extension is enabled for debugging

**Comment by weinand** [comment]
@Lukeeeeee In your second screenshot I cannot see the `[1, 2, 3]` that you mention in your description.
All I see is the same string `{1, 2, 3}` that you pass via the launch config.
Please clarify.

**Comment by Lukeeeeee** [comment]
> @Lukeeeeee In your second screenshot I cannot see the `[1, 2, 3]` that you mention in your description.
> All I see is the same string `{1, 2, 3}` that you pass via the launch config.
> Please clarify.

Sorry, it seems that I have attached the wrong pic. Pls see the one blew. Many thanks.

![image](https://user-images.githubusercontent.com/9161548/86023900-e16e0f00-ba5e-11ea-8d39-5643ba8637e2.png)

**Comment by attilah** [comment]
I think the following issue is related so not opening a new issue, but adding +1 failing case here. It is happening in a node project the issues is not extension related as this issue shows  as well.

When I am trying to pass escaped JSON in `args` it is being passed to the process as multiple args.

launch.json
``` 
args: ["--option", "{\"envName\":\"dev\",\"appId\":\"foo\"}"]
```

argv:
![image](https://user-images.githubusercontent.com/230432/95941186-0465ca00-0d95-11eb-8e77-fc05dc05d1f5.png)

if I add a whitespace after the first property's comma, then it is being passed correctly:

`launch.json`
```
"args": ["--option", "{\"envName\":\"dev\", \"appId\":\"foo\"}"],
```

argv:
![image](https://user-images.githubusercontent.com/230432/95941260-32e3a500-0d95-11eb-9051-e5a74e0c6639.png)

**Comment by weinand** [comment]
@Lukeeeeee yes, VS Code fails to quote the string `{1,2,3}` property.
Adding a space character fixes that: `{1, 2,3}`

**Comment by lewisconklin** [comment]
Has this issue been resolved? I cannot seem to reproduce it on the current version (1.51.1)
