### ISSUE TITLE
"The window is no longer responding" after webpack build

### ISSUE THREAD

**Issue by githubaccount624** [Microsoft/vscode#10115]
- VSCode Version: 1.3.1
- OS Version: Windows 7

I can run "webpack index.js" in the command prompt and it works fine.

Recently, if I build in VS Code, after the build completes it crashes and says the window is no longer responding. Any idea what could be causing this?

I just downloaded the VS Code insiders build and the problem isn't on there so I guess I'll just use that. I suppose this is fixed already but not included in the stable 1.3.1 release?

**Comment by aeschli** [comment]
@githubaccount624 How do you build it in VS Code? Using the integrated terminal, or how?

**Comment by jrieken** [comment]
@githubaccount624 Can you please provide the information asked for above? Also can you run top/htop/process explorer to see what process is running high?
