### ISSUE TITLE
Latest Insiders incorrectly renders the "More Action..." popup menu in the Source Control view

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#101163]
- VSCode Version: Does not repro with 1.46.0
Version: 1.47.0-insider (user setup)
Commit: 6c235c723cb2d8defb840f732eac620f54aa8b9d
Date: 2020-06-26T06:20:06.931Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041
- OS Version:

Steps to Reproduce:

1. Open some Git repo. Click the More Actions... dropdown (from the ... in the Source Control view). See the screenshot (the width and height is incorrect -- the UI is accessible via using the keyboard). Let me know if you can't repro it. My Source Control view has 2 "roots" in the tree view (i.e. a repo and a submodule), not sure if that's required for the repro or not.

Bug: The popup menu renders incorrectly (clipped, i.e. the "pull" text in the screenshot).

![image](https://user-images.githubusercontent.com/19859882/85899914-bd3ad580-b7b3-11ea-8e7d-c2cf8d96ca83.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sean-mcmanus** [comment]
@joaomoreno It looks like you've been making changes in this area?

**Comment by joaomoreno** [comment]
@sean-mcmanus I can't repro this no more, I believe it has been fixed meanwhile. Do you confirm?

**Comment by sean-mcmanus** [comment]
Yeah, it's fixed now, thanks.
