### ISSUE TITLE
Allow to configure workbench.editor.restoreViewState per language

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#101110]
When we close a file and then re-open it, VS Code will restore the cursor position.

In many cases this is desired. However, in some cases it is not, therefore it would be useful to provide a setting for this and allow it to be configured differently depending on the language being used.

For example: when I run `git commit` in terminal, the `COMMIT_EDITMSG` file will open in VS Code. Ideally my cursor would be positioned at the top so I can start writing my commit message right away. However, many times my cursor is positioned elsewhere, presumably because VS Code is trying to restore it to the position when I closed this file the last time I wrote a commit message.

This also happens when I run `git rebase --interactive` and the rebase todo list is opened in VS Code.

**Comment by joaomoreno** [comment]
@bpasero Not sure if this feature is from you.

**Comment by bpasero** [comment]
We have `"workbench.editor.restoreViewState": true` but you cannot set it as resource setting currently.

**Comment by OliverJAsh** [comment]
> We have `"workbench.editor.restoreViewState": true` but you cannot set it as resource setting currently.

Ah I didn't find that when I was searching for keywords "cursor, position, reset, restore". Maybe we could add those as keywords so the setting is more easily found.

**Comment by bpasero** [comment]
**Verification:**
* configure `workbench.editor.restoreViewState` for a language, e.g. `markdown`
* open a couple of files including `markdown` and scroll + set a selection you can memorize
* switch between tabs and verify view state is restored
* reload window and do the same and verify view state is restored
* close a non-markdown file and open it again and verify view state is restored
* close the markdown file and open it again and verify view state is NOT restored

**Comment by isidorn** [comment]
I have verified this works as expected, with the following correction to the last two bullet points

* close a non-markdown file and open it again and verify view state is **NOT** restored
* close the markdown file and open it again and verify view state **IS** restored

Since I have configured for markdown to restore view state this is expected behavior imho.

**Comment by bpasero** [comment]
I think what I meant to say is to configure `workbench.editor.restoreViewState: false` for `[markdown]` because the default is to restore view state always.

**Comment by isidorn** [comment]
Ok, let me verify it again...

**Comment by isidorn** [comment]
Works fine! Thanks for clarifying.
