### ISSUE TITLE
Provide a way to specify controlling debug session in multi-session scenarios

### ISSUE THREAD

**Issue by int19h** [microsoft/vscode#101140]
When there are multiple physical debug sessions in a rooted tree representing a single logical debug session, it would be nice to have a way to specify which of the physical sessions is the one that controls the overall lifetime of that logical session from the user perspective - i.e. which session should be represented in the debug toolbar wrt Stop/Disconnect behavior. 

This is particularly important in light of https://github.com/microsoft/vscode/issues/99736, because when processes get compressed in the Call Stack pane, only the child session - and its associated controls - is visible in the UI anywhere. Thus, when the child session is "attach", but the (lifetime-controlling) parent session is "launch", the UX only shows Disconnect, not Stop - and there's no way for the user to work around that.

(Note that this does *not* apply to Pause.)

**Comment by isidorn** [comment]
Agree we should provide a way for extensions to control this behavior.
However we can also put it the other way around: all the actions are always done on the child session except the `Stop / Disconnect`. There should be a way for extensions to specify on which session `Stop` and `Disconnect` are executed.

fyi @connor4312

**Comment by int19h** [comment]
This is basically what my intent was. Pause etc on child session makes perfect sense for us, because the child session is normally where user code runs, so that's what they want to see paused. Stop/Disconnect needs to be on the parent only because it's a lifetime management thing - that's what I was trying to convey with "lifetime-controlling session". Hence why the issue is specifically scoped to Stop/Disconnect.

I suppose there might also be scenarios where the innermost session is also not the one running user code, and so being able to explicitly designate a session for *that* would also be handy. It just didn't come up for us yet, so I'd rather treat it as a separate thing.

**Comment by int19h** [comment]
It might help to establish some clear terminology here, and then frame UX in those terms. The way I see it, in a generic multiproc scenario, you have three broad kinds of processes:

1. One that manages the overall lifetime of the logical process group.
1. One or more that run code that's interesting to the user (where the code in which they're setting line breakpoints runs).
1. One or more that run code that is usually not interesting to the user, but they might still want to e.g. get reports of exceptions occurring there (utility processes spawned by libraries or frameworks).

(The first kind can overlap with the other two for some processes.)

**Comment by isidorn** [comment]
@int19h thanks for feedback. And yes looking and the kind of processes makes sense.

For now I would suggest that we see how @connor4312 and @weinand feel like and then we can look intro introducing some API. Probably a `debugSessionOptions` field in the `startDebugging` api.
Simpliest thing I have in mind is a boolean field `sendStopAndDisconnectToParentSession`

**Comment by connor4312** [comment]
Something that's led to difficultly in quite a few places is the fact that the debug toolbar is displayed independently of the debug sessions. If there's a session with any children, then seeing the toolbar alone is not enough to determine what any of its buttons will do -- I have to also open the debug view to see what session is selected to determine this.

I think that the controls of the debug toolbar should always go to the top-level session, since that's the level at which context is given. In the case that the control should be given a child session, maybe the debug extension reroutes that appropriately.

**Comment by firelizzard18** [comment]
Fun fact - disconnecting from the parent session does not disconnect from the child session, but it does remove both sessions from the Call Stack view, unless the child is paused, and the toolbar remains up and associated with the child session: #108351
