### ISSUE TITLE
Visual Studio Codespaces will not allow me to clone any repos

### ISSUE THREAD

**Issue by Olb** [microsoft/vscode#101147]
I have just set up my first VisualStudio CodeSpace. I am not able to clone any repos. I am the owner of those repos. I am not being prompted to sign in. I have given VisualStudio CodeSpaces access to my repos.

The command:
git clone https://github.com/flx-systems/name.git

Gives this:
Cloning into 'name'...
remote: Repository not found.
fatal: repository 'https://github.com/flx-systems/name.git/' not found

**Comment by joaomoreno** [comment]
Is that repository private?
