### ISSUE TITLE
large icon in task switcher(alt+tab) on centos-KDE.

### ISSUE THREAD

**Issue by cg-cnu** [Microsoft/vscode#10110]
- VSCode Version: 1.3.1
- OS Version: CentOS Linux release 7.1.1503 (Core)
- Desktop Environment: KDE Version 4.10.5

Icon size in the task switcher( alt + tab ) is extremely large! 
Its working fine for the git popup window! But not for the main vscode window.
(All other apps working fine!)
Could be a vscode linux-KDE specific issue.

![media-20160804](https://cloud.githubusercontent.com/assets/2767425/17390276/48fe4a76-5a29-11e6-9cd8-ec2a258965ec.jpg)

**Comment by Tyriar** [comment]
Firefox seems to be large as well, are you sure this isn't a KDE issue?

**Comment by calumblair** [comment]
The icon file at /usr/share/code/resources/app/resources/linux/code.png is 1024x1024. It's being used in the task switcher without being scaled. If you resize it to 256x256 or smaller, it behaves the same as the other task icons and doesn't overwrite the icons next to it in the switcher.

**Comment by cg-cnu** [comment]
Sorry, lost track of this one. I don't think its the issue with KDE.
All apps are working fine except firefox and code. While firefox is manageable code is too big. 
@calumblair's comments make sense.

**Comment by Tyriar** [comment]
@cg-cnu I find it curious that KDE would not scale the image itself though, of course we could resize it, but then other distros may get a worse quality icon for example. Do you have any documentation on the recommended size of the icon in the desktop entry? I see nothing about a recommended size in https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

**Comment by Tyriar** [comment]
Closing this off until more details surface on how to properly do this without degrading the experience on other distros.

**Comment by Tyriar** [comment]
Reopening and adding help wanted to hopefully get some feedback on the fix.

**Comment by bpasero** [comment]
@cg-cnu still happening?

**Comment by cg-cnu** [comment]
Hey @bpasero thanks for getting back to this one... Yes, I still have the issue.

![vscode](https://user-images.githubusercontent.com/2767425/32699657-66854174-c7df-11e7-9ac7-645bf43ef192.png)

I tried out changing the image size of `/usr/share/code/resources/app/resources/linux/code.png` from `1024` to `128` and that solved it. 

![vscode 1](https://user-images.githubusercontent.com/2767425/32700089-00d270ca-c7e6-11e7-862a-f340be3388d1.png)


Let me know if you need any more info 😄
