### ISSUE TITLE
Broken outline rendering in git commit box for warning

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101131]
Have a long message in the commit box. Notice how the outline is not rendered well.
Also the warning message is not shown.

![Screenshot 2020-06-26 at 15 39 48](https://user-images.githubusercontent.com/1926584/85863353-545b5980-b7c3-11ea-95ce-10d5b96e9f41.png)

**Comment by joaomoreno** [comment]
dupe

**Comment by gjsjohnmurray** [comment]
#101053
