### ISSUE TITLE
Unable to interact with extension menu on remote SSH

### ISSUE THREAD

**Issue by arpanlaha** [microsoft/vscode#101169]
- VSCode Version: 1.47.0-insider: commit 6c235c723cb2d8defb840f732eac620f54aa8b9d
- OS Version: Windows_NT x64 10.0.19041

Searching for extensions on VSCode remote (SSH) fails, and I am unable to manage my extensions through the interface.

Upon loading, I run into one of two scenarios

1. The search bar is squished (for lack of a better term). In this case, I'm unable to interact with the search bar at all.
![image](https://user-images.githubusercontent.com/32147742/85899618-f1b68d80-b7c3-11ea-8e44-2497d6c7ebe8.png)
2. Images are not loaded alongside the extensions. 
![image](https://user-images.githubusercontent.com/32147742/85899819-51149d80-b7c4-11ea-860a-a972e228cd59.png)

Both of the above result in the following:

- Opening the extension menu results in the following logs in the developer console (plus more of the same errors that don't fit in the screenshot): 
![image](https://user-images.githubusercontent.com/32147742/85908073-3c8ed000-b7d9-11ea-91b6-a9a6501f4003.png)
- Searching for an extension results in the message "We cannot connect to the Extensions Marketplace at this time, please try again later." 
![image](https://user-images.githubusercontent.com/32147742/85899971-9507a280-b7c4-11ea-9cd5-a25393144b07.png)
However, this is not a network issue, as the developer tools shows that the responses return 200s with the expected results.
![image](https://user-images.githubusercontent.com/32147742/85900107-d8621100-b7c4-11ea-9a90-ba0e5a124f74.png)
![image](https://user-images.githubusercontent.com/32147742/85900120-df891f00-b7c4-11ea-8be8-6b695aab788e.png)
The developer console shows that this is a client-side error
![image](https://user-images.githubusercontent.com/32147742/85900643-c6cd3900-b7c5-11ea-9fd0-6a2214d7e1ba.png)
- Clicking on an installed extension in the menu pane does not bring up the page in the editor panel. This brings up the following logs in the developer console: 
![image](https://user-images.githubusercontent.com/32147742/85900774-faa85e80-b7c5-11ea-977e-10caca2ad18b.png)
- Interacting with the extension through the settings wheel (Enable/Disable) causes an error to pop up, with associated logs in the console 
![image](https://user-images.githubusercontent.com/32147742/85908196-c2128000-b7d9-11ea-8df0-9048db025a98.png)
![image](https://user-images.githubusercontent.com/32147742/85908202-c76fca80-b7d9-11ea-9ba7-92adf186f156.png)
Uninstalling through this interface works; however, more of the same errors from above (cannot read property ____...) are logged in the console.

The errors messages seem to indicate that the source of this error is the same as #100983 and #100880 (unsure if this is a duplicate, but I wanted to provide more information/screenshots). Additionally, in the time since I've started writing this up #101165 seems to be similar if not the same, so apologies if this is another duplicate.

As for my attempts to resolve this, I've both uninstalled VSCode on the remote server, uninstalled VSCode on my client machine, and done a full clean installation (uninstall + delete associated folders), and have not seen the error go away.

Steps to Reproduce:

1. Open VSCode insiders with a Remote SSH (Linux, Azure Standard B2ms server) workspace
2. Open extension menu and interact with elements as described above

Does this issue occur when all extensions are disabled?: Yes/No
Unable to test, as disabling all extensions prevents remote access and the bug prevents me from manually disabling/enabling any extensions.

**Comment by sandy081** [comment]
/duplicate

#101165
