### ISSUE TITLE
ctrl-click in terminal doesn't handle trailing ':' in file:line:col: links

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#101155]
Issue Type: <b>Bug</b>

gcc generates errors in the terminal window that look like this:
```
File.cpp:52:32: error: blah blah blah
```

if you ctrl-click on the `File.cpp` bit in the terminal window, it populates the vscode file search popup with the text `File.cpp:52:32:`, but this yields **no** search results.

however, if you delete the trailing `:` from that text (resulting in `File.cpp:52:32` then the file search popup shows the correct file and hitting &lt;enter&gt; takes you to the correct file/line/column.

Either:
- the terminal window location parsing code should omit the trailing `:`, or
- the file search popup parser should handle the trailing `:`

left-hand meet right-hand.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (2.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1:2222|
|OS|Linux x64 3.10.0-1127.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2903)|
|Memory (System)|3.70GB (1.62GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1:2222|
|OS|Linux x64 3.10.0-1127.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2903)|
|Memory (System)|3.70GB (1.62GB free)|
|VM|100%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.4.1
vscode-markdownlint|Dav|0.36.0
gitlens|eam|10.2.2
php-debug|fel|1.13.0
cmake|twx|0.0.17
change-case|wma|1.0.0
plsql-language|xyz|1.8.2
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4

</details>

**Comment by Tyriar** [comment]
Code pointer: https://github.com/microsoft/vscode/blob/e0d4a2fe2d57019a5b3709ff16e2331e46a612df/src/vs/workbench/contrib/terminal/browser/links/terminalValidatedLocalLinkProvider.ts#L42

**Comment by tabaddor** [comment]
Can look into this! Though I may not be super responsive at the moment.

**Comment by kosuruvarunkumar** [comment]
Hi @Spongman, asking for my clarification.
In my case, nothing is happening on ctrl + mouseclick. But the system is asking for alt+click which is navigating me to the source of the error. I am adding the screen recording of what I did. I am new to this environment, can you help me with any configurations needed using which I can reproduce this?
Thanks

![ctrlclick](https://user-images.githubusercontent.com/24850168/85942992-b1cde280-b94a-11ea-9d2a-ac71ea1546fe.gif)

**Comment by Tyriar** [comment]
@tabaddor 👍 

@kosuruvarunkumar it will be alt or ctrl depending on `editor.multiCursorModifier`

**Comment by NotWearingPants** [comment]
I think this only reproduces on Linux, OP was using a remote Linux host

**Comment by NotWearingPants** [comment]
I figured it out, this is because the file is at the root and so it has no slashes at all.

The example OP gave was with "File.cpp:52:32:".
The Ctrl+click and popup he's talking about isn't the suggestion of "open file in editor", it's the "search workspace" one.

**Comment by Spongman** [comment]
part the issue is that when the string in the terminal is
```
/file:line:col:
```

the underline does **NOT** include the trailing ':'

and when the string in the terminal is
```
file:line:col:
```
the underline **DOES** include the trailing ':'

regardless of this difference, the search popup should handle the trailing ':' whether or not it is there.
