### ISSUE TITLE
Regex not working on ungreedy captures

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode#10116]
- VSCode Version: 1.3.1
- OS Version: 10.11.5

Steps to Reproduce:

1. Imagine you have a line such as `if (ConfigurationManager.AppSettings["Bar"] != null && bool.Parse(ConfigurationManager.AppSettings["Foo"]))`
2. You want to find and replace the ConfigurationManager with a object and property
3. We can search like so `(ConfigurationManager\.AppSettings\[")(.+?)("\])`, this searches finds and sets capture groups.
4. Notice the `?` in the bit where we are searching inside the square brackets. This says search for anything inside square brackets but be ungreedy and then find a closing bracket. Without this `?` it would find the last occurrence of the square bracket on the line.
5. VSCode seems to use the `?` to only find the first occurrence of a match on one line and ignores the second existence of `ConfigurationManager.AppSettings["Foo"]` 
6. When we replace with `this.myobject.$2` obviously only the first occurrence is replaced
6. Sublime Text works with this regex to find and replace

**Comment by jchannon** [comment]
**UPDATE** This only seems to exist in Find in Files, seems fine in Find in open file

**Comment by jchannon** [comment]
**UPDATE 2** Actually I think the functionality does exist, its just the preview in the Find in Files which is incorrect. When it shows what its found and highlights it and highlights what will change it doesn't show the second occurrence on the line

**Comment by sandy081** [comment]
@jchannon I could see the highlights and replace preview as expected. Please see the screenshot

<img width="874" alt="screen shot 2016-08-04 at 11 28 52 am" src="https://cloud.githubusercontent.com/assets/10746682/17397109/ca2ea05c-5a36-11e6-9518-0aeab617faaf.png">

I have this text `if (ConfigurationManager.AppSettings["Bar"] != null && bool.Parse(ConfigurationManager.AppSettings["Foo"]))` on a single line. 

Any additional info would be really helpful.

Thanks

**Comment by jchannon** [comment]
Ah I think I can see what it's doing, it's putting each search result on a new line in the preview which is confusing, it looks like its missed the 2nd occurrence.  I also just found out if you click on a search result it will show you a split pane diff of before/after which helps.

Looks like it's just a confusing/unexpected UX feature.
