### ISSUE TITLE
UX: Source control expands all repos for all folders in workspace

### ISSUE THREAD

**Issue by trdyer** [microsoft/vscode#101160]
Version: 1.47.0-insider
Commit: 6c235c723cb2d8defb840f732eac620f54aa8b9d
Date: 2020-06-26T05:33:20.679Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.5.0

Steps to Reproduce:

1. Have multiple folders open in a workspace
2. view Source control tab

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Preciously there was a ux element to select the folder you wished to view changes for, now it shows all changes across all folders plus UI to commit changes for every folder. this becomes incredibly noisy and hard to comprehend.

**Comment by joaomoreno** [comment]
#101146
