### ISSUE TITLE
Test: Install VSIX through drag'n'drop to extension viewlet

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#101117]
Refs: #12090

- [x] macOS @weinand
- [x] linux @deepak1556
- [x] windows @mjbvz

Authors: @lszomoru, @joaomoreno 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23101117%0A%0A)

---

We have added support to install a VSIX file by dragging and dropping it onto the Extensions viewlet.

Verification:
* Download one or more VSIX files from the marketplace - https://marketplace.visualstudio.com/vscode
  * Drag'n'drop one or more VSIX files onto the Extensions viewlet and confirm that the extensions are installed
* Drag'n'drop any files that do not have a VSIX extension. While the file can be dropped onto the viewlet, nothing should happen.
* Rename an image file to have the `.vsix` extension. Drag'n'drop the file onto the viewlet. This should result in an error that the ZIP is corrupt.

**Comment by weinand** [comment]
@lszomoru FYI, on macOS it is possible to remove the ".vsix" from the extension file and still D&D it successfully onto the Extensions viewlet. The reason for this is that macOS detects the removal of the ".vsix" from the name as a request to hide the file's extension. This can be seen with "Get Info":

<img width="631" alt="2020-07-01_09-41-06" src="https://user-images.githubusercontent.com/1898161/86216945-0e194800-bb7f-11ea-9f8e-117d19d21a02.png">
