### ISSUE TITLE
SCM: can not open some repositories view

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#101157]
Issue Type: <b>Bug</b>

In a multi workspace, I can't open some of the repository view

![image](https://user-images.githubusercontent.com/876920/85892442-c6bd4100-b7a5-11ea-85c2-14eec9ecbd5c.png)

As in above image, some of the repositories views are expanded but no changes view shows at all.

VS Code version: Code - Insiders 1.47.0-insider (6c235c723cb2d8defb840f732eac620f54aa8b9d, 2020-06-26T05:33:20.679Z)
OS version: Darwin x64 19.4.0

**Comment by gjsjohnmurray** [comment]
Isn't that because according to their badges there are 0 changes?

**Comment by rebornix** [comment]
Right, I didn't see that they have no changes. Previously in SCM, no matter if it has changes or not, I can always see the SCM box but now I can't, which made me unclear which one is focused and working.

**Comment by gjsjohnmurray** [comment]
On another issue someone has suggested not displaying a badge if its value is zero.

**Comment by joaomoreno** [comment]
Yeah this was a design decision: in multi-scm let's hide the inputbox and empty groups, to reduce visual noise. I think another good alternative might be to simply automatically collapse groups when in this state.

**Comment by rebornix** [comment]
Speaking of visual noise, I found that lacking of padding between views is making it hard to differentiate change entries and view titles

![image](https://user-images.githubusercontent.com/876920/86064660-8ae2df80-ba22-11ea-8b5b-500bc1f39aec.png)

**Comment by joaomoreno** [comment]
Merged with https://github.com/microsoft/vscode/issues/101103
