### ISSUE TITLE
Setting to Disable npm scripts Debug Button in package.json

### ISSUE THREAD

**Issue by karlhorky** [microsoft/vscode#101107]
Currently, in VS Code May 2020 (1.46), there is a **Debug** button that appears above the npm scripts in my `package.json`:

<img width="293" alt="Screen Shot 2020-06-26 at 11 57 01" src="https://user-images.githubusercontent.com/1935696/85845424-83ae9e00-b7a4-11ea-8e62-aafe6dba83c2.png">

I would like to configure a setting to disable this.

**Comment by gjsjohnmurray** [comment]
These things are called CodeLenses. Take a look at `debug.javascript.codelens.npmScripts`

**Comment by karlhorky** [comment]
Funny enough, trawling around the history, it seems like there was a feature that was removed in 2018, which was configurable with `npm.scriptCodeLens.enable` setting 🤔 hm...

https://github.com/microsoft/vscode/commit/73b72464b3f71db7ac3b763f37e84769bd411a7b

**Comment by karlhorky** [comment]
@gjsjohnmurray nice, thanks! Possible options are `"all"`, `"top"` and `"never"`.

I guess to turn it off it's:

```json
"debug.javascript.codelens.npmScripts": "never"
```

**Comment by ArturoDent** [comment]
Also answered here: https://stackoverflow.com/questions/62358131/how-to-disable-debug-from-showing-in-package-json/62368407#62368407
