### ISSUE TITLE
Editor: Allow overflowing widgets to be rooted at an external DOM node

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#101128]
Editor overflowing widgets are `position: fixed` so they escape `overflow: hidden` rules which might be set in editor ancestor DOM elements, making them effectively overflowing.

On `position: fixed`, [MDN says](https://developer.mozilla.org/en-US/docs/Web/CSS/position):

> The element is removed from the normal document flow, and no space is created for the element in the page layout. It is positioned relative to the initial containing block established by the viewport, except when one of its ancestors has a transform, perspective, or filter property set to something other than none (see the CSS Transforms Spec), in which case that ancestor behaves as the containing block.

For Notebooks, the list `transformOptimization` setting was added to address this limitation, since the list uses `transform` to implement performant scroll. This setting allows to simply disable that performance optimization, which makes it not ideal. cc @rebornix 

The same issue is now happening in SCM https://github.com/microsoft/vscode/issues/101054 and the same `transformOptimization` setting will be used temporarily.

---

After a brief discussion with @alexdima, we think a better solution would be to have a new editor option which allows passing a DOM node under which all overflowing widgets shall be placed. This way, we can keep having the `transform` optimization as well as true overflowing widgets.

We can potentially even avoid having `position: fixed` and simply use `position: absolute`, leveraging the `fixedOverflowWidgets` editor setting, which can make layout easier in views which scroll such as the list. And fix some issues:

![recording (3)](https://user-images.githubusercontent.com/22350/85871694-0f3d2480-b7cf-11ea-8436-8ef637c80674.gif)

**Comment by rebornix** [comment]
+1 for introducing an external DOM node for overflow widgets. cc @sbatten we had the same discussion previously when fixing the notebook list cut off issue.

**Comment by connor4312** [comment]
Verified looking at through the code... it doesn't look like we've adopted this for notebooks yet, though (at least, I still see the fixed-position suggest widget)

**Comment by joaomoreno** [comment]
@rebornix can you check if adopting this works, in debt week?

**Comment by rebornix** [comment]
@joaomoreno yes sir, I'll adopt this in Notebook next week. Thanks for the new option, it will make the notebook scroll faster.
