### ISSUE TITLE
Terminal preferences being ignored

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/vscode#101150]
Issue Type: <b>Bug</b>

It was working until this latest update -- I have both

`"terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",`

and 

`"terminal.external.windowsExec": "C:\\Program Files\\PowerShell\\7\\pwsh.exe"` 

specified, but new terminals are spawning in Powershell 1.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aga|0.5.0
pgformatter|bra|1.14.0
sqlformatter|bre|0.0.7
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
excel-to-markdown-table|csh|1.2.2
vscode-svgviewer|css|2.0.0
vbscript|Dar|1.0.4
empty-indent|Dmi|0.2.0
githistory|don|0.6.5
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
LogFileHighlighter|emi|2.8.0
indent-switcher|eph|1.2.1
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
terraform-autocomplete|erd|0.0.8
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-mysql|for|0.4.0
mdmath|goe|2.5.1
gc-excelviewer|Gra|3.0.37
terraform|has|2.0.2
live-html-previewer|hdg|0.3.0
r|Iku|1.4.2
mysql-syntax|jak|1.3.1
cypher-query-language|jak|1.0.2
latex-workshop|Jam|8.11.0
nbpreviewer|jit|1.2.2
language-julia|jul|0.16.8
php-cs-fixer|jun|0.1.155
indentation-level-movement|kai|1.2.1
stata-enhanced|kyl|1.6.1
vscode-emacs-friendly|lfs|0.9.0
rainbow-csv|mec|1.7.0
code-beautifier|mic|2.3.3
vscode-apache|mrm|1.2.0
vscode-less|mrm|0.6.3
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
mssql|ms-|1.9.0
vscode-postgresql|ms-|0.3.0
python|ms-|2020.6.90262
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
cpptools|ms-|0.28.3
hexeditor|ms-|1.0.1
powershell|ms-|2020.6.0
team|ms-|1.161.0
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
vscode-yaml|red|0.8.0
r-lsp|REd|0.1.6
terraform-doc-snippets|run|0.4.0
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|3.4.3
stylelint|shi|0.51.0
vscode-coffeelint|slb|0.0.2
vscode-autohotkey|sle|0.2.2
vba-snippets|spe|1.0.1
code-spell-checker|str|1.9.0
tabnine-vscode|Tab|2.8.6
open-in-browser|tec|2.0.0
html-preview-vscode|tht|0.2.5
latex-support|tor|3.2.0
vscodeintellicode|Vis|1.2.8
vscode-arduino|vsc|0.3.1
markdown-pdf|yza|1.4.4

(4 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Please provide [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
