### ISSUE TITLE
Webviews have native scrollbars

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#101143]
- Open a markdown preview webview, or a notebook

![image](https://user-images.githubusercontent.com/323878/85874233-ee0d1180-b797-11ea-8029-845c358ab38d.png)

Doesn't repro in master, but that was also the case a couple days ago, so I was wondering whether there was a build issue or something that would cause it to use the wrong index.html file

**Comment by roblourens** [comment]
And the problem is from the webview not using the index.html that has the styles including `margin: 0` on the body

![image](https://user-images.githubusercontent.com/323878/85875091-501a4680-b799-11ea-86bd-e087447031c2.png)

**Comment by mjbvz** [comment]
Should be fixed by 33142d0202d018e0e5bc11304504c84c33c3e8d5
