### ISSUE TITLE
A Bug?

### ISSUE THREAD

**Issue by StelianMihai** [microsoft/vscode#101115]
Hi i have a question why my scripts like: import, def , etc are just white?
i mean is just a black fond and my words are just white i can change the color for this commends like import?
same with words from "( )" 
i don't think is a bug i think i don't see a setting for this and all tutorials are from 2015 :( all i found is how to change the FONT the BACKGROUND of python but i don't want that i want to see the words colored.
Can you help me?.

**Comment by aeschli** [comment]
If you think youi have found a bug, please add a small sample code and describe what you se and what you expect. Also clarify what language this is for (C, JavaScipt, Python, ...) and what color theme you are using.

If this is a question,  please use https://stackoverflow.com/questions/tagged/vscode
