### ISSUE TITLE
Lots of extension errors when opening a WSL folder

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#101165]
I'm trying to open a folder in WSL and at startup I see lots of errors in the console, and the scrolling in the extensions view is broken.

I have disabled the built-in version of js debug, and have the nightly version installed an enabled.

I've tracked it down to this following code returning `undefined` for the `ms-vscode.js-debug` extension:
https://github.com/microsoft/vscode/blob/d04df068bdaf096b8bca742ef60065d2ef36e24e/src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts#L664-L674

Specifically, it looks like this line: https://github.com/microsoft/vscode/blob/d04df068bdaf096b8bca742ef60065d2ef36e24e/src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts#L668-L669 

Returns an empty array, so that causes an `undefined` later -- which then causes the cascade of issues.

If I re-enable the built-in js debug, the issue goes away.

**Comment by sandy081** [comment]
Sorry for breaking this.

To verify:

- Disable a builtin extension for eg: `js debug`
- Open a remote window (SSH / Dev Container / WSL)
- Make sure there are no error in the console while browsing extensions.
