### ISSUE TITLE
Inline tsdoc comment support

### ISSUE THREAD

**Issue by probablyup** [microsoft/vscode#101142]
When writing a type, sometimes you want to add more information to a field that will be surfaced in IDE autocomplete. Currently you must define them like this:

```ts
export type BoxSizeDefinition = {
  /** this is null for non-custom box sizes */
  itemCount: number | null
  size: BoxSize
  /** A description for the range of pounds included in box. */
  poundage: string
  /** price in cents of the box size */
  price: number
}
```

Note that the comment is _above_ the field. This is problematic because auto-sorting linters and such will mangle the comments.

I propose also supporting _inline_ tsdoc comments:

```ts
export type BoxSizeDefinition = {
  itemCount: number | null /** this is null for non-custom box sizes */
  size: BoxSize
  poundage: string /** A description for the range of pounds included in box. */
  price: number /** price in cents of the box size */
}
```

This effectively fixes the sorting problem.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by probablyup** [comment]
Done https://github.com/microsoft/TypeScript/issues/39290, thanks
