### ISSUE TITLE
[testing] New TS Error report template

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#101171]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.0.0-dev.20200626

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Please review and upload this log file to help us diagnose this crash:

`/Users/matb/Library/Application Support/code-oss-dev/logs/20200626T163321/exthost1/vscode.typescript-language-features/tsserver-log-5CfVo6/tsserver.log`

The log file may contain personal data, including full paths and source code from your workspace. You can scrub the log file to remove paths or other personal information.

**TS Server Error Stack**

```
Error: xxx
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:153579:23)
    at IOSession.Session.executeCommand (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:153591:33)
    at IOSession.Session.onMessage (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:153615:35)
    at Interface.<anonymous> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:155830:27)
    at Interface.emit (events.js:210:5)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
```

VS Code version: Code - OSS Dev 1.47.0 (Commit unknown, Date unknown)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|32.00GB (2.29GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|17%|
</details>

**Comment by mjbvz** [comment]
@sheetalkamat @RyanCavanaugh @DanielRosenwasser @amcasey

We get a lot of non-actionable TS crashes , so I've updated VS Code to prompt users to upload the log from the crashed TSServer instance. The issue report above shows what users would see (if they do not have logging enabled, we also prompt them to enable logging).

Let me know if you have any concerns about this or suggestion on how we could help users provide more information about their crashes

**Comment by amcasey** [comment]
I might specifically call out `updateOpen` as a request that might need to be scrubbed.

There should probably be a Microsoft Privacy link somewhere.

Do we get the syntax server log too?

**Comment by mjbvz** [comment]
@amcasey The report flow is pretty much a fancy way of directing users to report issues through GitHub. Do you think we need a privacy link for this and this link actually be helpful? 

We do enable logging on the syntax server but to my knowledge have not ever used this log while investigating an issue. The errors always seem to happen in the full server

**Comment by amcasey** [comment]
@mjbvz You're right, I think it's sufficient for the repro to have a clear privacy policy.

If we start using the syntax server for semantic operations, crashes are more likely to occur there.
