### ISSUE TITLE
Auto import path is invisible

### ISSUE THREAD

**Issue by dsdenes** [microsoft/vscode#101119]
My problem is that I cannot see that what I'm importing:

![Screenshot 2020-06-26 at 14 26 50](https://user-images.githubusercontent.com/123850/85856944-2ffa7f80-b7b9-11ea-8e2b-42a90170cece.png)

It would be good if path would be visible.

**Comment by mjbvz** [comment]
To see the full path you can expand the intellisense details by pressing ctrl+space again:


<img width="1286" alt="Screen Shot 2020-06-26 at 2 18 35 PM" src="https://user-images.githubusercontent.com/12821956/85902046-ed847300-b7b7-11ea-868a-5af82b477683.png">
