### ISSUE TITLE
Ctrl + click on quick open does not work

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#1011]
* Open quick open with ctrl + tab
* Click on file you want to open while holding down ctrl - **nothing happens**
* I would expect the file gets opened

I see this on mac el capitan. I think it was working before your promise chain work since I this is part of my workflow.

**Comment by bpasero** [comment]
@isidorn Don't think this ever worked, please try with 0.10.3. I dont think the tree gives me a mouse down with Ctrl clicked.

**Comment by isidorn** [comment]
You are right, just checked - also not working with 0.10.3
I confused it with my workflow with regular quick open + click. Though this would still be nice to have if possible.

**Comment by bpasero** [comment]
The issue is that Ctrl+click on Mac seems to trigger the context menu. I am overriding this now in quick open so that you can Ctrl+click to pick an entry from the editor history. I was missing this feature a lot too, so I am happy this seems to work now!

**Comment by isidorn** [comment]
awesome :fist:
