### ISSUE TITLE
Stop extension watch task when stopping extension run

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#10118]
Version 1.4.0-insider
- start vscode fresh
- open a extension sample code, e.g. https://github.com/DanTup/Dart-Code/
- in the settings unfilter the out folder, so it can be seen in the exlorer
- delete the out/src folder, create a empty src folder again
- press F5.
- Extension Development Host starts, open a dart file, all works fine, files are compiled
- shutdown the Extension Development Host
- delete the out/src folder, create a empty src folder again
- press F5.
- Extension Development Host starts, open a dart file, error, out/src stays empty.
- Run 'terminate running task'
- press F5.
- Extension Development Host starts, open a dart file, all works fine, files are compiled

Wouldn't it be better to kill the task when the Extension Development Host is closed? It is not obvious to the user that there's still a task running and how to terminate it. Also I don't need to have my files compiled until I start the the Extension Development Host again.

**Comment by dbaeumer** [comment]
Instead of killing I would then not start a watching task.

**Comment by aeschli** [comment]
While the Extension Development Host is up, watching makes sense (reload is faster than restart)
