### ISSUE TITLE
"Duplicate Workspace in New Window" does not duplicate launch configurations

### ISSUE THREAD

**Issue by SAbboushi** [microsoft/vscode#101156]
Issue Type: <b>Bug</b>

1) Add launch configuration to workspace file e.g.
AHKv2.code-workspace:
```
{
	"folders": [
		{
			"name": "MasterAHK scripts",
			"path": "..\\..\\..\\..\\..\\..\\..\\Documents\\Application Data\\AutoHotkey"
		},
		{
			"name": "AHK LibV2",
			"path": "D:\\Documents\\AutoHotkey\\LibV2"
		},
		{
			"name": "AHK V2 Examples",
			"path": "D:\\Documents\\Application Data\\AutoHotkey\\AHK SA Examples\\AHKv2"
		},
		{
			"name": "vscode Workspaces",
			"path": "J:\\SyMenu\\ProgramFiles\\SPSSuite\\SyMenuSuite\\Visual_Studio_Code_(x64)_sps\\Data\\workspaces"
		}
	],
	"settings": {
		"files.exclude": {
			"**/*.bak": true,
			"**/*.ico": true,
			"**/*.png": true,
			"**/*.PNG": true
        },
        "code-runner.executorMap": {
            "ah2": "\"J:\\StandaloneApps\\AutoHotkeyV2\\AutoHotkeyU64.exe\" /r /errorStdOut"
        }
    },
    "launch": {
        "configurations": [
            {
                "name": "AutoHotkey V2 Debug",
                "request": "launch",
                "type": "autohotkey",  // identifies the debugger
                "runtime": "J:/StandaloneApps/AutoHotkeyV2/AutoHotkeyU64.exe",
                "program": "${file}",
                "args": [],
                "stopOnEntry": false,
                "useAdvancedBreakpoint": true,
                "useAdvancedOutput": true,
                "maxChildren": 10000,
                "port": "9000-9010"
                // "internalConsoleOptions": "openOnSessionStart"
            }
        ]
    }
}
```

2) "F1">Duplicate Workspace in New Window

3) In new window>"F1">Preferences: Open Workspace Settings (JSON).
Launch configuration was not duplicated:
```
{
	"folders": [
		{
			"name": "MasterAHK scripts",
			"path": "J:\\Documents\\Application Data\\AutoHotkey"
		},
		{
			"name": "AHK LibV2",
			"path": "D:\\Documents\\AutoHotkey\\LibV2"
		},
		{
			"name": "AHK V2 Examples",
			"path": "D:\\Documents\\Application Data\\AutoHotkey\\AHK SA Examples\\AHKv2"
		},
		{
			"name": "vscode Workspaces",
			"path": "J:\\SyMenu\\ProgramFiles\\SPSSuite\\SyMenuSuite\\Visual_Studio_Code_(x64)_sps\\Data\\workspaces"
		}
    ],
    "settings": {
        "files.exclude": {
            "**/*.bak": true,
            "**/*.ico": true,
            "**/*.png": true,
            "**/*.PNG": true
        },
        "code-runner.executorMap": {
            "ah2": "\"J:\\StandaloneApps\\AutoHotkeyV2\\AutoHotkeyU64.exe\" /r /errorStdOut"
        }
    }
}
```

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (9.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
insertnumbers|Asu|0.9.1
auto-align|bla|0.0.13
findallinfile|bna|0.9.1
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.1.4
vscode-autohotkey2|dud|0.2.0
code-runner|for|0.10.0
vscode-ts-whitespace-converter|joh|1.2.1
wordcounter|kir|2.3.0
gremlins|nho|0.23.0
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.7.2
sort-lines|Tyr|1.9.0
cursor-align|yo1|1.0.4
cursor-trim|yo1|1.0.0
cursorCharCode|zei|0.1.1
vscode-autohotkey-debug|zer|1.4.2

</details>

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
