### ISSUE TITLE
crash, prompt reopen, then files unsaved or opened before crash lost

### ISSUE THREAD

**Issue by suiwenfeng** [Microsoft/vscode#10113]
- VSCode Version:1.3.1
- OS Version:Windows Server 2008 R2 Enterprise
![image](https://cloud.githubusercontent.com/assets/2735407/17391323/b46635d0-5a47-11e6-9946-45e8b5ee4115.png)
Steps to Reproduce:

1. Open a folder with too much files, open some files.
2. leave and back in 2 hours, prompt as screenshot shows up
3. choose reload the folder, and any opened or unsaved files lost.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/101
