### ISSUE TITLE
Automatic github auth doesn't work with gist repositories

### ISSUE THREAD

**Issue by ab763** [microsoft/vscode#101174]
- VSCode Version: 1.47.0-insider
- OS Version: MacOS 10.15.5

Steps to Reproduce:

1. Clone a gist from your own GitHub account (https://help.github.com/en/github/writing-on-github/forking-and-cloning-gists)

2. In VSCode, attempt to push a new commit to it. VSCode will complete its authentication via its GitHub integration, but then displays a message "Git: remote: Repository not found."

Expected result: Commit is pushed, as is done in GitHub Desktop, etc.

I'm guessing the error is because VSCode is hardcoded to a fixed repository URL format, instead of just attempting to do a normal push using the actual repository URL that it already sees.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by jsejcksn** [comment]
> VSCode will complete its authentication via its GitHub integration

Are you sure about this?

Manually setting credentials for `https://gist.github.com` in the [credential helper](https://docs.github.com/en/github/using-git/caching-your-github-credentials-in-git) resolves this. I think the error message is misleading, and VS Code doesn't actually attempt to authenticate.

Gists are different from repos because they are public read, but restricted write (amongst other quirks like no directories, etc.). You didn't get the same error when cloning for that reason.

**Comment by ab763** [comment]
> > VSCode will complete its authentication via its GitHub integration
> 
> Are you sure about this?

I believe that VSCode prompted me to login, yes.

I am able to push to the gist otherwise, yes.. I've used gists a lot otherwise, yes, thank you.

**Comment by eallenOP** [comment]
I can't push to a gist no matter what I do! VS Code won't do it, gh cli won't do it, credential helper won't do it. So, how would we go about manually setting credentials for gist.github.com in the credential helper? @jsejcksn

**Comment by eonist** [comment]
@eallenOP Same here. I think some people have success with PAT tokens. But yet to figure out how.

**Comment by lszomoru** [comment]
I have tested this with the latest version of VS Code and I am able to clone, update my own gist.
In case you are still running into any issues, please feel free to create a separate issue so that I can investigate it.

**Comment by eonist** [comment]
Thanks @lszomoru I got it working too. Wrote a tutorial here: https://gist.github.com/eonist/3f3dd1902dd23bfeeaba3d83e9f0e9da
