### ISSUE TITLE
vscode got performance issue

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode#101139]
Issue Type: <b>Performance Issue</b>

I found that vscode performs poorly on low-frequency CPUs

In high-end CPUs, the difference is not obvious ( intel 7+)

Even though, It is still very slow compared to IDE (idea)

Mainly reflected in these aspects:

1. UI displays delayed
2. Operation delayed (cursor / mouse)
3. Intelligent slowly
4. Large expansion leads to slowness (Go/Rust/Vim) It's strange, these processes should be separated from the rendering process, should not affect

There are still many issues in vscode that indicate that its performance is not good, even bad

Does the vscode team have a plan to improve performance(not just startup)？

VS Code version: Code - Insiders 1.47.0-insider (6c235c723cb2d8defb840f732eac620f54aa8b9d, 2020-06-26T05:33:20.679Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|72, 70, 49|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|-psn_0_5588308|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    8	    90	 63049	code-insiders main
    7	    41	 63053	   gpu-process
    1	    16	 63055	   utility
   12	    74	 63236	   shared-process
    0	     0	 70095	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    16	 63769	   utility
    6	   254	 64386	   window (common.go — 无标题 (工作区))
    0	    41	 64390	     extensionHost
    0	    16	 64431	       electron_node server.js 
    0	    16	 64447	       /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=64390
    0	    16	 64448	       electron_node serverMain.js 
    0	    16	 64515	       electron_node vueServerMain.js 
    0	    16	 64549	       /Users/axetroy/go/bin/gopls -mode=stdio
    0	     8	 64787	       /Users/axetroy/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rls
    0	    16	 66759	       electron_node tomlServerMain.js 
    0	    16	 64391	     watcherService
   34	   197	 70033	   window (undefined)
   29	    66	 70093	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (common.go — 无标题 (工作区))
|    Folder (JuFengShiYe): 307 files
|      File types: js(146) vue(49) md(16) png(8) html(7) json(5) yml(3) log(3)
|                  gitignore(2) map(2)
|      Conf files: package.json(2) webpack.config.js(1) jsconfig.json(1)
|    Folder (rust-kp): 2632 files
|      File types: json(314) timestamp(251) d(213) rmeta(157) rlib(102) o(100)
|                  plist(55) bin(36) dylib(28) lock(13)
|      Conf files:
|    Folder (go-server): 4863 files
|      File types: go(1947) md(159) yml(69) s(61) mod(47) gitignore(43)
|                  log(31) sum(27) sh(21) gz(18)
|      Conf files: makefile(13) github-actions(1);
```

</details>
<details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
s4|axe|0.1.1
vscode-auto-schema|axe|0.1.0
vscode-changelog-generator|axe|1.0.0
vscode-comment-autocomplete|axe|0.4.2
vscode-gpm|axe|2.3.6
vscode-http-proxy|axe|0.1.3
vscode-movie|axe|0.5.0
vscode-open-in-browser|axe|1.0.0
vscode-static-server|axe|0.3.1
github-markdown-preview|bie|0.0.2
markdown-preview-github-styles|bie|0.1.6
better-toml|bun|0.3.2
dart-code|Dar|3.12.0
flutter|Dar|3.12.0
vscode-eslint|dba|2.1.5
vscode-deepscan|Dee|1.9.8
docs-yaml|doc|0.2.5
xml|Dot|2.5.0
gitlens|eam|10.2.2
vscode-pull-request-github|Git|0.17.0
Go|gol|0.14.4
vscode-placeholder-images|Jak|0.1.0
statusbarerror|Joe|0.4.0
vscode-colorize|kam|0.8.17
git-graph|mhu|1.24.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.3.1
vscode-language-pack-zh-hans|MS-|1.47.0
python|ms-|2020.6.90262
remote-containers|ms-|0.123.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsonline|ms-|1.0.2390
vetur|oct|0.24.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.8.0
vscode-sort-json|ric|1.18.0
rust|rus|0.7.8
extension-update-reporter|ryu|1.0.3
rainbow-fart|sae|1.2.4
px-to-rem|sai|1.3.1
bash-beautify|sha|0.1.1
vscode-nginx|sha|0.6.0
trailing-spaces|sha|0.3.1
prettier-vscode|Sim|2.0.7
svg-preview|Sim|2.8.3
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.8
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2
markdown-all-in-one|yzh|3.1.0
vscode-caddyfile-syntax|zam|1.0.4

(1 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
Do you this behavior with latest insiders https://code.visualstudio.com/insiders and [exploration versions](https://az764295.vo.msecnd.net/exploration/3c1b4bacbef4ab788f72059f56ef53e9aa7923bc/VSCode-darwin.zip)
