### ISSUE TITLE
Opening chrome as vs code tab

### ISSUE THREAD

**Issue by iamaks93** [microsoft/vscode#101179]
Issue Type: <b>Bug</b>

Hi there

Recently I found a weird issue in my ubuntu 18 system. When I open the chrome browser it opens up vscode tab. I also tried to reinstalling vscode it works fine a few days then again it behaves the same. 

https://www.loom.com/share/50d2963e56e64fc288372fcf9bbe0f0a

Please find the above link.

Thanks

VS Code version: Code - Insiders 1.47.0-insider (6c235c723cb2d8defb840f732eac620f54aa8b9d, 2020-06-26T05:33:52.214Z)
OS version: Linux x64 5.3.0-59-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 2, 1|
|Memory (System)|7.72GB (0.98GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-react-native|msj|0.16.0

</details>

**Comment by deepak1556** [comment]
Can you check if the issue happens with latest insiders https://code.visualstudio.com/insiders ?
