### ISSUE TITLE
Problem with Powershell-Syntax - after legal statement all lines seems to be interpret as string

### ISSUE THREAD

**Issue by dhcgn** [Microsoft/vscode#10117]
- VSCode Version:  
Version 1.3.1  
Commit e6b4afa53e9c0f54edef1673de9001e9f0f547ae  
Datum 2016-07-12T13:35:06.227Z  
Shell 0.37.6  
Renderer 49.0.2623.75  
Node 5.10.0  
- OS Version: Windows 7

Steps to Reproduce:

1. Copy this Code in VSCode  
```
DoSomething | ft Sucess, @{Label="X-Powered-By"; Expression={$_.Headers.'X-Powered-By'}} -AutoSize
Write-Host "Hello World"
```
2. The line `Write-Host "Hello World"` is interpret as string
![vscode-problem](https://cloud.githubusercontent.com/assets/6566207/17397503/99890940-5a38-11e6-843c-eb9eae227c71.png)

**Comment by daviwil** [comment]
This is a known issue which we've addressed by reverting the PowerShell syntax highlighter to an older version which does not have this problem.  You should see this resolved once VS Code 1.4 releases.  Closing this issue for now, please comment back here if you still have issues after the 1.4 update.  Thanks!
