### ISSUE TITLE
Jupyter syntax highlighting : some symbols not supported?

### ISSUE THREAD

**Issue by lostdatum** [microsoft/vscode#101154]
Issue Type: <b>Bug</b>

Minor issue. FYI, I'm new with Python, Jupyter and VS Code.

I noticed that the syntax highlighting in Jupyter does not quite work like in the text editor. Not only the colors are different (not so bad), but also some symbols are not highlighted as they should : 'def', '=', function names, exceptions types...

Here is a screenshot of sample code in Jupyter (left) and its export as a Python module (right).
![image](https://user-images.githubusercontent.com/67317293/85888846-a2378800-b7ea-11ea-9e8a-cb0453ca862b.png)

Is it just a matter of theme configuration or something? 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.86GB (2.79GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.6.90262
remote-wsl|ms-|0.44.4

</details>

**Comment by dbaeumer** [comment]
Please file the issue against the Python extension that provides the Jupyter  support.
