### ISSUE TITLE
Javascript Debugger fails to hit breakpoints if launch.json exists

### ISSUE THREAD

**Issue by LJSamuelson** [microsoft/vscode#101162]
Issue Type: <b>Bug</b>

Test.js file:
    console.log("Starting");
    console.log('Ending');
Set breakpoint on line 2.
    Click Run /Start Debugging/Node.js.  Break point is hit.
    Click Run/Run Without Debugging/Node.js..  Break point is not hit.
    Click Run /Start Debugging/Node.js..  Break point is hit.
Now create a launch.json file.
   Click Run/Add Configuration/Node.js
   Click Run /Start Debugging.  Break point is hit.
   Click Run/Run Without Debugging.  Break point is not hit.
   Click Run /Start Debugging.  Break point is NOT hit.
Delete the launch.json file and breakpoint are hit again.

This is launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\test.js"
        }
    ]
}
```

**Comment by isidorn** [comment]
What you are seeing is fixed in vscode insiders.
However in insiders there is another issue that  the js-debug is not supporting Run Without Debugging tracked here https://github.com/microsoft/vscode-js-debug/issues/523

Thus closing as duplicate
fyi @connor4312
