### ISSUE TITLE
c/c++ ext error

### ISSUE THREAD

**Issue by amither** [Microsoft/vscode#10111]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.install c/c++ ext
2. in my c++ project , error info : The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscppsamples#128
