### ISSUE TITLE
scroll problem

### ISSUE THREAD

**Issue by realing29** [microsoft/vscode#101137]
Issue Type: <b>Bug</b>

When scrolling, there is a delay. If you hold down the "ctrl", then there is no delay. In the settings, scroll animation is disabled. How to remove the delay?

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (4.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
project-manager|ale|11.1.0
bemhelper|Box|0.8.1
turbo-console-log|Cha|1.4.0
bracket-pair-colorizer|Coe|1.0.61
ecsstractor-port|diz|0.0.3
githistory|don|0.6.5
auto-close-tag|for|0.5.7
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.3
vscode-google-translate|fun|1.4.5
vscode-gutter-preview|kis|0.26.2
vs-color-picker|lih|1.0.0
vscode-scss|mrm|0.9.0
vscode-language-pack-ru|MS-|1.46.3
debugger-for-chrome|msj|4.12.8
vetur|oct|0.24.0
indent-rainbow|ode|7.4.0
vscode-css-navigation|puc|1.9.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
sass-indented|syl|1.8.6
language-stylus|sys|1.11.0

</details>

**Comment by alexdima** [comment]
@realing29 You can try: `"editor.smoothScrolling": false` and `"workbench.list.smoothScrolling": false`.

**Comment by realing29** [comment]
> @realing29 You can try: `"editor.smoothScrolling": false` and `"workbench.list.smoothScrolling": false`.
Did not help.

**Comment by realing29** [comment]
Decision:
![image](https://user-images.githubusercontent.com/36142237/86145982-0f139080-bb11-11ea-985a-a8ff8bfec7fe.png)
