### ISSUE TITLE
Selected but not focused sessions inline actions have wrong color

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101111]
1. Start debugging two sessions
2. Have one selected and one focused in the tree
3. Hover over the selected one -> notice debug inline actions do not have contrast. They should have that special css rules applied so they are white.

How it is

![Screenshot 2020-06-26 at 12 39 30](https://user-images.githubusercontent.com/1926584/85849037-82806f80-b7aa-11ea-8a0a-d2d39f7ffe09.png)

How it should be

![Screenshot 2020-06-26 at 12 42 53](https://user-images.githubusercontent.com/1926584/85849071-91672200-b7aa-11ea-81a0-973d357cade7.png)

@misolori feel free to asign back to me

**Comment by isidorn** [comment]
I could change the rule here to be on selected but not selected and focused
https://github.com/microsoft/vscode/blob/277627c09011f4075dfac47dd9793b1f015be306/src/vs/workbench/contrib/debug/browser/media/debugViewlet.css#L81

However that fix would not fix the RUNNING color and background
Also note that this milestone I have introduced compact debug sessions, so this might have changed some css we were relying on

![Screenshot 2020-06-26 at 12 48 01](https://user-images.githubusercontent.com/1926584/85849473-4dc0e800-b7ab-11ea-9c08-f09b4e67336f.png)

**Comment by misolori** [comment]
Fixed now:

![image](https://user-images.githubusercontent.com/35271042/86035878-dd57d800-b9f1-11ea-8e41-74e5c87baf2d.png)

**Comment by isidorn** [comment]
I tried your fix and it does not work for me. I have your commit and was triying out of source.
Let's reopen for now. Maybe I was doing something wrong
I am using the default Light+ theme

![Screenshot 2020-06-30 at 09 09 06](https://user-images.githubusercontent.com/1926584/86094875-6255f680-bab1-11ea-9b1d-0f6393a065a1.png)

**Comment by misolori** [comment]
Oh, I now see what you mean. I was selected + hovering another item, not selecting. Will look into this.

**Comment by misolori** [comment]
Now it should be fixed:

![image](https://user-images.githubusercontent.com/35271042/86153179-1a859e00-bab6-11ea-88e0-730a3380390b.png)

**Comment by isidorn** [comment]
Yes, now it is great, thanks!
