### ISSUE TITLE
Smart select randomly selects first parenthesis in call expression

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#101199]
- VSCode Version: latest
- OS Version: latest

Steps to Reproduce:

```ts
a(
  1
)
```

1. Place your cursor on `a` (before/after the function name)
2. Run "expand selection" twice

Expected: the whole call expression should be selected, including the arguments.

![image](https://user-images.githubusercontent.com/921609/85932056-c82f5c00-b8c0-11ea-8c59-c51e26e202fc.png)

Actual: only `a(` is selected. This is not at all helpful. The user has to run "expand selection" again to get what they want.

![image](https://user-images.githubusercontent.com/921609/85932045-b64db900-b8c0-11ea-8506-344896494cb0.png)

Note this works in a variable declaration, so I don't see why we would want different behaviour outside of a variable? E.g.

```ts
const x = a(
  1
)
```

![image](https://user-images.githubusercontent.com/921609/85932059-d2515a80-b8c0-11ea-88ed-3588b2219c19.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
What language? AFAIK this is the responsibility of the `SelectionRangeProvider`

**Comment by OliverJAsh** [comment]
`ts`/`tsx`/`js`/`jsx`

**Comment by jrieken** [comment]
This is on purpose and needs feature work to add a setting or so. The idea is that the current line always is a selection stop

**Comment by OliverJAsh** [comment]
How come it doesn't do that when using a variable declaration e.g. my second example?

**Comment by OliverJAsh** [comment]
> This is on purpose and needs feature work to add a setting or so. The idea is that the current line always is a selection stop

Alternatively, could VS Code expose commands that are _strictly_ for expanding/shrinking the selection according to the AST and nothing else?
