### ISSUE TITLE
scm.alwaysShowProviders has disappeared from 1.47 Insider

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#101112]
Issue Type: <b>Bug</b>

The `scm.alwaysShowProviders` setting arrived in January 2018 in response to #38785, but seems to have been removed during recent work. Has this already been discussed somewhere?

VS Code version: Code - Insiders 1.47.0-insider (6c235c723cb2d8defb840f732eac620f54aa8b9d, 2020-06-26T06:20:06.931Z)
OS version: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
This was a purposeful decision since no information is dropped:

- When 1 repository is open, the status commands always appear on the status bar. Also, something new since that feature request: the commit box placeholder now indicates the current branch as well.
- When 2 or more repositories are open, all information is still rendered in the new tree.

So I believe this might just be a small friction of change, rather than an actual drop in usability. Of course, if it's still in high demand, the view can always come back, but I'd love if we ran with this a bit more before committing to that again. What do you think @gjsjohnmurray?

**Comment by gjsjohnmurray** [comment]
@joaomoreno it's probably going to be okay, at least for me. Here's a side-by-side of a single-Git-repo workspace, 1.46 on the left, with `"scm.alwaysShowProviders": true` and 1.47 on the right.

![image](https://user-images.githubusercontent.com/6726799/85860557-e4df6d00-b7b6-11ea-8696-0b29d66c8c3d.png)

And for a two-repo workspace, using Git for one and our own SCM product (Deltanji) for the other:

![image](https://user-images.githubusercontent.com/6726799/85860788-3687f780-b7b7-11ea-875c-7cbfc9747138.png)

I like how the new UX no longer uppercases the SourceControl and SourceControlResourceGroup labels, (e.g. `Trial2` and `WebTerminal`, `Changes` and `#4: Fourth`) but perhaps they could be bolded or get some other visual differentiation from  the SourceControlResourceState entries (e.g. `README2.txt` and `WebTerminal.Updater.CLS [WEBTERMINAL.0]`). This might help with #101103, raised by @bpasero.

I don't like that the new UX no longer displays the `label` parameter passed on the `vscode.scm.createSourceControl(...)` call (e.g. `Git` and `Deltanji`). Perhaps they can be added as hovers on the `Trial2` and `WebTerminal` headers.

**Comment by joaomoreno** [comment]
Yeah let's keep the UX discussion in #101103. 

> I don't like that the new UX no longer displays the `label` parameter passed on the `vscode.scm.createSourceControl(...)` call (e.g. `Git` and `Deltanji`). Perhaps they can be added as hovers on the `Trial2` and `WebTerminal` headers.

I was just thinking about the same. I'll bring it back, I think it actually looks better with it.

Closing then, thanks for the feedback!

**Comment by gjsjohnmurray** [comment]
@joaomoreno it's probably going to be okay, at least for me. Here's a side-by-side of a single-Git-repo workspace, 1.46 on the left, with `"scm.alwaysShowProviders": true` and 1.47 on the right.

![image](https://user-images.githubusercontent.com/6726799/85860557-e4df6d00-b7b6-11ea-8696-0b29d66c8c3d.png)

And for a two-repo workspace, using Git for one and our own SCM product (Deltanji) for the other:

![image](https://user-images.githubusercontent.com/6726799/85860788-3687f780-b7b7-11ea-875c-7cbfc9747138.png)

I like how the new UX no longer uppercases the SourceControl and SourceControlResourceGroup labels, (e.g. `Trial2` and `WebTerminal`, `Changes` and `#4: Fourth`) but perhaps they could be bolded or get some other visual differentiation from  the SourceControlResourceState entries (e.g. `README2.txt` and `WebTerminal.Updater.CLS [WEBTERMINAL.0]`). This might help with #101103, raised by @bpasero.

I don't like that the new UX no longer displays the `label` parameter passed on the `vscode.scm.createSourceControl(...)` call (e.g. `Git` and `Deltanji`). Perhaps they can be added as hovers on the `Trial2` and `WebTerminal` headers.
