### ISSUE TITLE
Test: SCM sort changes

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#101116]
Refs: #40712

- [x] anyOS @alexdima
- [x] anyOS @sana-ajani

Authors: @lszomoru , @joaomoreno 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23101116%0A%0A)

---

The SCM viewlet now supports changes by path (default), name, and status

* Open/Create a Git repository which contains multiple files
* Make changes (add, edit, delete, etc.) to multiple files in the repository
* Switch to the SCM viewlet:
  * In the toolbar choose `...` -> `View & Sort` -> `Sort by Name`.
    * Confirm that the changes are sorted by name.
    * Reopen the menu and confirm that `Sort by Name` is checked.
  * In the toolbar choose `...` -> `View & Sort` -> `Sort by Path`.
    * Confirm that the changes are sorted by path.
    * Reopen the menu and confirm that `Sort by Path` is checked.
  * In the toolbar choose `...` -> `View & Sort` -> `Sort by Status`.
    * Confirm that the changes are sorted by status.
    * Reopen the menu and confirm that `Sort by Status` is checked.
  * In the toolbar choose `...` -> `View & Sort` -> `View as Tree`.
    * Confirm that all sorting options under `...` -> `View & Sort` are disabled.
  * In the toolbar choose `...` -> `View & Sort` -> `View as List`.
    * Confirm that all sorting options under `...` -> `View & Sort` are reenabled.

**Comment by sana-ajani** [comment]
I'm not sure what "status" means in this context?

**Comment by alexdima** [comment]
@sana-ajani It is about Deleted, Untracked or Modified files (`D`, `U` or `M`)
