### ISSUE TITLE
Repos in SCM view expand after closing/opening the sidebar

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#101146]
- Collapse a repo in the SCM view
![image](https://user-images.githubusercontent.com/323878/85878157-e5b7d500-b79d-11ea-963b-35180323ab69.png)

- Toggle the sidebar, now it's expanded
![image](https://user-images.githubusercontent.com/323878/85878176-ed777980-b79d-11ea-88c4-f8726aa7151b.png)

**Comment by joaomoreno** [comment]
Similar https://github.com/microsoft/vscode/issues/101094
