### ISSUE TITLE
Tabs get unpinned if VSC is closed and I open a file

### ISSUE THREAD

**Issue by teejay-87** [microsoft/vscode#101109]
Issue Type: <b>Bug</b>

I have a dozen pinned tabs, all of never-saved files.
VSC is closed.
I right-click, "Open with Code" a file.
VS Code opens up, loads my file, and then all other tabs open but unpinned.

In this specific case, the file being open is a .vb file.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
vscode-postgres|cko|1.1.11
xml|Dot|2.5.0
prettier-vscode|esb|5.1.0
Untabify|ili|0.0.2
csharp|ms-|1.22.1
text-power-tools|qcz|1.11.1

</details>

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.

**Comment by teejay-87** [comment]
Ok. I thought it was correct to insert new one because no of the existing speak of pinned tabs.
