### ISSUE TITLE
provide workspace folder alias

### ISSUE THREAD

**Issue by zxffan** [microsoft/vscode#101207]
i got two same name folder in one workspace. like this.
![image](https://user-images.githubusercontent.com/48522331/85935417-2b51da80-b923-11ea-99e0-6fce3dc66a6b.png)

can i tag the folder named web with a alias name?

**Comment by gjsjohnmurray** [comment]
/question

https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file-schema
