### ISSUE TITLE
Command Line --install-extention help lacks detail indicating support for extension version

### ISSUE THREAD

**Issue by WhisperingChaos** [microsoft/vscode#101248]
- VSCode Version: 1.43.2
- OS Version: MS Windows 7 Ultimate - [Version 6.1.7601]

Steps to Reproduce:
1.  Open terminal.
2.  At CLI prompt enter: ```> code --help``` Generates following help test for extension option:
```
 --install-extension <extension-id | path-to-vsix> Installs or updates the
                                                   extension. Use `--force`
                                                   argument to avoid
                                                   prompts.
```

Does this issue occur when all extensions are disabled?: Yes/No
Not Applicable 

Expected:
```
 --install-extension <extension-id>[@<extension-version>] | <path-to-vsix>     Installs or updates the
                                                   extension. Use `--force` argument to avoid prompts.  <extension-id>
                                                   reflects combination of "publisher.name" while <extension-version>
                                                   specifies the desired implementation.
```
Note:
 -  According to  [Extension Manifest](https://code.visualstudio.com/api/references/extension-manifest), ```<extension-id>``` it is defined as ```${publisher}.${name}```.  Extension Manifest defines ```version``` separately from ```name```.  Therefore, ```extension-id``` should not involve notion of ```version```. 
 - Adding the ```version``` specifier to CLI occurred ~2yrs ago: #12764.
 - Lack of updated CLI documentation generates needless discussion and potential [reimplementation](https://github.com/microsoft/vscode-remote-release/issues/3253).

**Comment by sandy081** [comment]
Good catch. Thanks for pointing this out.

Fixed.
