### ISSUE TITLE
Terminate Running Task and Retry

### ISSUE THREAD

**Issue by grovina** [Microsoft/vscode#10124]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04

When I try to run a task and there's already one running, I get the warning 

> There is an active running task right now. Terminate it first before executing another task.

with the button `Terminate Running Task`.

I suggest that this button could not only terminate the running task but also launch the one I asked for.
Something like `Terminate Running Task and Retry`.

**Comment by dbaeumer** [comment]
Got implemented. Task > Restart Running Task.
