### ISSUE TITLE
Markdown code block with type and extra space breaks rest of document

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10125]
- VSCode Version: 1.4.0-insiders
- OS Version: OSX

Steps to Reproduce:

Create markdown file with content:

(Notice extra space after closing ``` in first and last case)

![image](https://cloud.githubusercontent.com/assets/1723815/17402710/90dc619a-5a22-11e6-8e5f-7cbb6541662f.png)

Github handles it fine:

```
let test = 0
``` 

Coloring ok here (closing code block has space)

```ts
let test = 0
```

Coloring ok here (closing code block has NO space)

```ts
let test = 0
``` 

Coloring ok here (closing code block has space)

**Comment by mjbvz** [comment]
I believe this was fixed by #12342.

We now correctly support any number of spaces after the end of a fenced code block. The fix is in the latest insiders builds.
