### ISSUE TITLE
Debug crashes when there is error in python in built modules.Instead it should show error 

### ISSUE THREAD

**Issue by PradeepNooney** [microsoft/vscode#101264]
Issue Type: <b>Bug</b>

This is  very unusual case.
os is one of the python in built modules. I have made changes(made errors) in that by mistake and saved it. When i debug , it  just crashes, it doesnt inform like there is some error in the file or something.
if i make the same error in the any of the user created python files. and when i start debug session, it shows the error  properly highlighting in red color and debug session is paused.
Sorry for my bad english.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

**Comment by weinand** [comment]
Please file against Python extension.
