### ISSUE TITLE
Backspace dedents instead of deleting character

### ISSUE THREAD

**Issue by masaeedu** [Microsoft/vscode#10123]
- VSCode Version: 1.3.1
- OS Version: Win 8.1

Steps to Reproduce:

1. Enable indentation using spaces
2. Press tab to insert indentation
3. Hit backspace

Actual result:
An number of spaces equivalent to your indentation size gets deleted

Expected result:
One space gets deleted

We already have shortcuts for deleting entire lines and dedenting by a single unit of indentation. Magic behavior that hijacks the backspace key is one of the reasons I switched over from Atom. Currently there is no key for simply deleting one space, and I believe backspace is a sensible default for this (this is also how Visual Studio behaves by default).

**Comment by alexandrudima** [comment]
@masaeedu Would changing this setting work for you:

```
// Inserting and deleting whitespace follows tab stops
"editor.useTabStops": true,
```

**Comment by masaeedu** [comment]
@alexandrudima Yup, that works. Thanks!
