### ISSUE TITLE
Hide properties starting with '#' if they are not in the declaration class (ES2019)

### ISSUE THREAD

**Issue by HerryYT** [microsoft/vscode#101252]
I would like VSCode to hide properties that begin with '#' outside the declaration class, this is a convention introduced with ES2019 and approved by Chrome: https://developers.google.com/web/updates/2019/04/nic74

**Comment by IllusionMH** [comment]
Where they should be hidden?

**Comment by HerryYT** [comment]
> Where they should be hidden?
> Howers, suggestions, code etc.

From autocompletion while accessing another class properties, if the other class property has a '#' in front of it, the property should be hidden or at least marked as private

**Comment by IllusionMH** [comment]
I don't see incorrect suggestions
![image](https://user-images.githubusercontent.com/1312662/86015990-ee710b00-ba2a-11ea-9c57-794d13de19f8.png)

VS Code Version: 1.47.0-insider (user setup) (Commit: 0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69)
TS Versions: 4.0.0-dev.20200625

Could you provide examples where it's suggested inappropriately?
You can check latest TS build using https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

**Comment by HerryYT** [comment]
The problem occurs when you use them in a different module, so you export the class Example with module.exports = Example; then in another file you create another class and you require the Example one... now instantiate the Example and when you try accessing the properties you will notice properties with #

**Comment by HerryYT** [comment]
Example on my actual project 
![Screenshot (58)](https://user-images.githubusercontent.com/34418030/86021057-f5971980-ba28-11ea-9209-d8a3a16cc86e.png)
In this exported class module there are private properties
![Screenshot (57)](https://user-images.githubusercontent.com/34418030/86021206-2414f480-ba29-11ea-9882-227a7c2971e7.png)
And there form another class module i can access them by istantiating the imported class

**Comment by IllusionMH** [comment]
Have you tried extension that I linked above?
Looks like it's already fixed in Nightly builds of TS and will be available without extension when VS Code will bundle TS 4.0 (probably August 2020 update in early September).

**Comment by HerryYT** [comment]
Installed it now and works, thank you so much for the assistence!
