### ISSUE TITLE
vs code fails to open file and folders

### ISSUE THREAD

**Issue by gurrrung** [microsoft/vscode#101280]
- VSCode Version: 1.44.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open a folder in VSCode using terminal. `code .` after moving to that folder.
2. Delete that folder using the terminal. I did `rm -r folder_name`
3. Now, try opening any other folder using VSCode through the terminal. It will not be able to open any folder from the PC. (Make sure you keep that old VSCode window open).

Additional:
This gets fixed when I close the old VSCode window but it is still a bug, I guess.

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment]
We have received your issue #101274, please do not file the same issue again.

**Comment by gurrrung** [comment]
I'm sorry, Github is behaving weirdly today. I was getting 404 from Github so I re-submitted.
