### ISSUE TITLE
Absolute path added to worktree property when cloning github repository

### ISSUE THREAD

**Issue by glopesdev** [microsoft/vscode#101244]
Issue Type: <b>Bug</b>

In two different machines I am seeing different behaviors when cloning a git repository from GitHub using VS Code Explorer > Clone Repository.

Specifically, an extra `worktree` property is added to the `.git` config file in the newly configured machine. VS Code versions are exactly the same and the difference is only in Git for Windows (2.19.1.windows.1 for the old machine and 2.27.0.windows.1 for the new).

This seems related to the recent GfW issue: https://github.com/git-for-windows/git/issues/2569

As reported in the above issue, the `worktree` entry is added only when the target directory does not *exactly* match the disk path (including drive letter), so it seems there is something in the way VS Code passes the path to `git clone` that is triggering this.

Is it possible to fix this? The absolute windows-style path is breaking calling git commands from WSL on all our newly configured machines.

To Reproduce:
1. Install the latest git for windows
2. Install the latest VS Code
3. Clone a repository from GitHub (using VS Code Explorer > Clone Repository interface)
4. Observe that the `config` file in the `.git` folder has a `worktree` property with a windows-style absolute path pointing to the target folder

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.23GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
Unfortunately this is exactly the upstream issue https://github.com/git-for-windows/git/issues/2569

I highly recommend not running git from WSL with files from Windows: it underperforms **badly**.

**Comment by glopesdev** [comment]
> Unfortunately this is exactly the upstream issue git-for-windows/git#2569

I agree. Can you confirm whether vscode passes the correct path to git for windows, including upper-case drive letter? Is there a way to see what exact git command vscode uses?

> I highly recommend not running git from WSL with files from Windows: it underperforms badly.

We don't. However, we do run Jekyll through WSL to build and host github-pages sites locally, which uses git commands underneath to fill in metadata. It's actually that workflow that is broken for us.

**Comment by joaomoreno** [comment]
> I agree. Can you confirm whether vscode passes the correct path to git for windows, including upper-case drive letter? Is there a way to see what exact git command vscode uses?

Run `Git: Show Git Output` and you'll see the log int he output pane.
