### ISSUE TITLE
Why are codicon styles loaded with a timeout of 0?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101265]
Looking at this code:

https://github.com/microsoft/vscode/blob/b58df64fd23e9639972d4b669d37365a76955d07/src/vs/base/browser/ui/codicons/codiconStyles.ts#L26

We seem to be computing a stylesheet and setting it with a timeout of 0. On Windows this shows up as perf hit:

![image](https://user-images.githubusercontent.com/900690/85987461-f2326c80-b9ed-11ea-8403-555d831326ae.png)

This will trigger the "Recalculate Style" in the browser.

What is the rationale here? Can we compute this and inline it?

[Profile-20200629T095103.zip](https://github.com/microsoft/vscode/files/4844465/Profile-20200629T095103.zip)

//cc @misolori @jrieken

**Comment by aeschli** [comment]
Cod-icon css is now dynamically generated based on (statc) icon registrations across our code base. The purpose of the timeout is to wait generating the css until all the registrations are in.
Is there a better way to achieve this?

**Comment by aeschli** [comment]
Yes, an alias. Like for colors, icons are referenced by ids. The ids are view specific, e.g. `dialog-error`. The purpose is that product icon themes can customize icons.

**Comment by bpasero** [comment]
@aeschli isn't this very similar to the `registerThemingParticipant` and could maybe work the same way? Afaik that one does not have a timeout. I would assume that all `registerIcon` calls are being made at code loading time, e.g. not within methods or classes. As such, at the time when the workbench starts up, all registrations should be there and you could create the stylesheet in one go. The fact that a timeout is used is imho triggering the recalculate style.

**Comment by aeschli** [comment]
The following work is needed:
- remove direct codicon usages from base
- move the image registry to platform and the codicon css generation to a service.

**Comment by aeschli** [comment]
Actually @alexdima fixed this through microsoft/monaco-editor#2140. The codicon css is now managed by the theme service.
