### ISSUE TITLE
'code' cli to open remote workspaces 

### ISSUE THREAD

**Issue by lemiesz** [microsoft/vscode#101200]
So one feature that I really like when developing locally with vscode, is the ability to use the 'code' CLI command. 
Using this to open a workspace based on my current terminal path. 

Recently I have started using Remote-SSH to develop on my remote box. Would be awesome if there was a way to implement a feature that detected my current terminal SSH session, then opened a VSCode window rooted at the current remote.

**Comment by roblourens** [comment]
Thanks for the request. It's not practical for us to do this. You can use the `code` CLI from an integrated terminal in a remote window, once you have a connection from the client to server already established. But there is no way for us to bootstrap this from your SSH session in another terminal, there is no way for it to tell VS Code on your local computer to launch.

**Comment by lemiesz** [comment]
`You can use the code CLI from an integrated terminal in a remote window, once you have a connection from the client to server already established.`

Not really clear what this means. 

Is there a way for me to map code so that it opens a remote workspace? 

For example, something like: 

`code --w {remote-workspace-name}`

Where {remote-workspace-name} is a predefine variable. 

The problem im trying to solve is that I am frequently switching workspaces throughout the day. Since I work on multiple projects, each consisting of server/client/infrastructure packages.

**Comment by roblourens** [comment]
Two options:

- From a _local_ terminal, `code --remote ssh-remote+myremotename /some/remote/folder`
- From a terminal in a remote vscode window, `code /some/remote/folder`

But there is no way to do this from an ssh session in an external terminal
