### ISSUE TITLE
Extension development - Syntax highlight only works on debug mode

### ISSUE THREAD

**Issue by BrunoQuaresma** [microsoft/vscode#101298]
**Issue**
I'm developing an extension and when I use the "Run Extension" the syntax highlight works as expected for `.fql` files however, when I published the extension to marketplace and installed locally it is not working.

**Steps to reproduce**
1. Install the extension FaunaDB
2. Execute CMD + P > Create Query
3. The code is not highlighted

Although, if you clone the extension repo https://github.com/fauna/vscode and try to debug the extension you will see the same steps will reproduce a diff behaviour in the new VSCode window. The code will have the correct syntax highlight.

On debug mode:
<img width="1366" alt="Screen Shot 2020-06-29 at 14 35 24" src="https://user-images.githubusercontent.com/3165839/86037458-caef9580-ba15-11ea-9b28-0b3a75bdf0b1.png">

Installing from marketplace
<img width="1363" alt="Screen Shot 2020-06-29 at 14 34 35" src="https://user-images.githubusercontent.com/3165839/86037486-d3e06700-ba15-11ea-959d-625d037e431e.png">

**Comment by alefragnani** [comment]
Hi @BrunoQuaresma ,

Do you see any error message in console, (opened via  `Toggle Developer Tools`)? Also, you could try to install the extension locally (`.vsix` File), created using `vsce package`.

I have experienced similar issues myself before, for two different reasons: general failure running the command and wrong use of dependencies described in `package.json`

Hope this helps

**Comment by BrunoQuaresma** [comment]
Thanks @alefragnani.

I found the issue. It was because my syntaxes folder was inside of `./src` which is ignored on `.vscodeignore`. Although I think the debug mode + packaged version should behaves in the same way.

**Comment by alefragnani** [comment]
That’s great you’ve found the issue! 

I’ve looked your repo and noted `./src` in `.vscodeignore` but your `syntaxes` folder was already on the root folder so, I eliminated that from the alternatives 😄
