### ISSUE TITLE
Unrecognized Git

### ISSUE THREAD

**Issue by WiseDoge** [Microsoft/vscode#10128]
- VSCode Version: 1.3.1.0
- OS Version:Windows 10 redstone

Yesterday, I update my OS from Windows 10 th2 to Windows 10 redstone, and when I open vscode again,I found that the git in vscode  can`t be recognized, How can I do?

**Comment by joaomoreno** [comment]
Which version of git do you have installed? You can use the `git.path` setting to point to `git.exe`.

**Comment by WiseDoge** [comment]
Thank you, I added `Git\bin` to the environment variables, and then git can be recingnized
