### ISSUE TITLE
After working for some time (perhaps dragging tabs?) I cannot use Escape to hide find widget

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#10122]
I will keep an eye out for clear repro steps, but it just happened to me the second time.

**Comment by jrieken** [comment]
One issue is that we might have multiple instances of a code editor inside one keybinding context (since different input types map to different editors and we don't dispose). That might cause such issues.

**Comment by bpasero** [comment]
If that is the issue here, then it would be a duplicate of https://github.com/Microsoft/vscode/issues/9705

The issue remains that we have potentially hidden diff editor per editor slot and if that one is still eating keys, we might need a method to put the hidden editor into a sleeping state.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/10358
