### ISSUE TITLE
Make Notebook rendering a per Notebook toggle rather than global.

### ISSUE THREAD

**Issue by petebryan** [microsoft/vscode#101293]
I sometime want to see the raw JSON of a notebook file rather than the rendered notebook. For example I recently updated the kernelspec in a number of our template notebooks to match our default environment which required me to edit the JSON. Whilst I can toggle notebook rendering off on a global level via settings it would be nice if I could toggle this on a per notebook basis via the command palette.

**Comment by rebornix** [comment]
For now the notebook feature is provided by the Python extension, please file issue against them.
