### ISSUE TITLE
Python: Line with Error Code is wrong

### ISSUE THREAD

**Issue by jmoraispk** [microsoft/vscode#101216]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I have blocks of code collapsed. When I run a cell with errors, the line number reported as having an error is in relation to the beginning of the cell, instead of the beginning of the file. Since these line numbers are not clickable, and the numbering of lines in the editor starts at the beginning of the file, it takes much longer to find a typo. Also, if the code is collapsed, it's quite hard to track down the line with the error since the linting doesn't go to the top of the function.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.14GB free)|
|Process Argv|C:\Users\janeiroja\Documents\SXR-sim\sim1.py|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.50
latex-workshop|Jam|8.11.0
python|ms-|2020.6.90262
remote-wsl|ms-|0.44.4
local-history|xyz|1.8.1

</details>

**Comment by rebornix** [comment]
Please file issue against the Python extension.
