### ISSUE TITLE
macOS: support case sensitive file system

### ISSUE THREAD

**Issue by yoyo930021** [microsoft/vscode#101267]
- VSCode Version: 1.46.1
- OS Version: macOS 10.15.5 in case sensitive volume

Steps to Reproduce:

1. Open any file.
2. Change file name case
3. Close file.
4. Open again and get error.
![Screen Shot 2020-06-29 at 3 52 42 PM](https://user-images.githubusercontent.com/9126398/85988229-51f63b00-ba21-11ea-9a46-ae354a2fd754.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by bpasero** [comment]
We currently do not support case-sensitive file systems on macOS or Windows. It may have worked by chance in the past but we never officially did anything to enable this scenario.

//cc @jrieken

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/94307
