### ISSUE TITLE
Terminal blank on windows 10

### ISSUE THREAD

**Issue by Gowthami11** [microsoft/vscode#101237]
Issue Type: <b>Bug</b>

on my acer nitro 5, vs code terminal is showing blank(folder path is not visible), i have tried uninstalling and installing also. but it hasn't worked.

Can i know why is it happening?

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (3.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by yume-chan** [comment]
See https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch#_additional-troubleshooting-steps

> If you're on Windows 10 1809 (build 17763) or below, the issue is related to the legacy "winpty" backend. Upgrading to Windows 1903 (build 18362) will move you onto the new "conpty" backend that is built by Microsoft and could fix your problem.

Terminal implementation on Windows 1803 is known to be buggy and Code team doesn't want to fix those issues anymore.

**Comment by cmeyertons** [comment]
Is there an alternative option for people in a large corporate environment that have zero say in when Windows gets upgraded?

We recently started seeing this issue -- terminal is rendered completely useless.  Also, task output is invisible (tasks still run though)

Currently on Windows 10 1809

**Comment by Tyriar** [comment]
Does changing the `terminal.integrated.rendererType` setting help?

**Comment by cmeyertons** [comment]
No - it’s definitely permission related as running as admin fixes the issue on Windows 10 build 1809. 

What permissions does VSC need to render the terminal properly?

**Comment by Tyriar** [comment]
@cmeyertons whatever [winpty](https://github.com/rprichard/winpty) needs. If permissions are indeed the reason you will have to wait until the Windows update gets rolled out.
