### ISSUE TITLE
Create ExtHostNotebookController service for node & web

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#101282]
Follow up issue for https://github.com/microsoft/vscode/commit/6bdb7e921e05be0747d1ff0188dec41283b82d7f

**Comment by rebornix** [comment]
@sandy081 may I ask what I should do here? I'm not 100% sure about what `ExtHostNotebookController service` means here.

**Comment by sandy081** [comment]
It seems `ExtHostNotebookController` has different behaviour for web worker ext host and node ext host as extHostStoragePaths does not exist in former and exist in latter. 

Ideally in such cases we register different services for [former](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/extensions/worker/extHost.services.ts)  and [latter](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.services.ts).

I think the fix I did [here](https://github.com/microsoft/vscode/commit/6bdb7e921e05be0747d1ff0188dec41283b82d7f) might not be correct as I am checking for the `UIKind`. I do not think we shall have two different ways of instantiating services.

**Comment by jrieken** [comment]
>  as extHostStoragePaths does not exist in former and exist in latter.

This isn't true anymore. There is now a single storage paths service that's used in both worlds.
