### ISSUE TITLE
Can't open folders in Explorer view

### ISSUE THREAD

**Issue by PEZ** [microsoft/vscode#101225]
Issue Type: <b>Bug</b>

All of a sudden most of the folders I try to open in VS Code simply won't open.

## Reproduction:

1. Create a new, empty, repo in Gitlab
2. Frrom a terminal:  Clone the repo 
3. `cd new-repo`
4. `code .`

### Expected results

The folder is opened in the Exporer view

### Actual results

The Explorer view says, ”You have not yet opened a folder”. Using the **Open Folder** button doesn't help, neither **Open** from the **File** menu.

Similar symptoms as with #91002, afaict.

Some folders do work.

It works in Insiders June: `1.47.0-insider`. However I am not sure that means it is fixed. Rather it could be that some state I have in my regular Code install is not there for my Insiders install. At least I can't find any PR addressing this.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.97GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
calva|bet|2.0.106
emojisense|bie|0.7.0
clj-kondo|bor|2020.6.21
better-toml|bun|0.3.2
gitlens|eam|10.2.2
terraform|has|2.0.2
vscode-mocha-test-adapter|hbe|2.6.0
vscode-test-explorer|hbe|2.19.1
chat|kar|0.35.0
restructuredtext|lex|128.0.0
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.3.1
vsliveshare|ms-|1.0.2377
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.8
vscode-react-native|msj|0.16.0
typescript-hero|rbb|3.0.0
vscode-xml|red|0.12.0
vscode-yaml|red|0.8.0
terraform-doc-snippets|run|0.4.0
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|sib|2.0.1
code-spell-checker|str|1.9.0
shellcheck|tim|0.9.0
org-mode|too|0.5.0

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by sailikhithk** [comment]
Hi PEZ, this issue is because of the problem of the extensions for the VS code which is present suffering everyone. So, I would suggest either to reset the settings or re-install the file related extensions or GIT related extensions.

**Comment by PEZ** [comment]
Also. After having done an extension-less launch seems to have fixed whatever caused the problem. Now I can run with extensions enabled and folders open as they should.

**Comment by isidorn** [comment]
So it seems to be caused by an extension. Please find which extension caused it and file an issue against that extension. Thanks
