### ISSUE TITLE
Plots viewer is very slow

### ISSUE THREAD

**Issue by sws144** [microsoft/vscode#101238]
Issue Type: <b>Bug</b>

Plotting a large plot (e.g seaborn pairplot) with many columns via jupyter interactive mode and then viewing in plots viewer is very slow to view/zoom/pan

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (0.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
vscode-markdownlint|Dav|0.36.1
python-extension-pack|don|1.6.0
gc-excelviewer|Gra|2.1.35
r|Iku|1.4.2
vsc-python-indent|Kev|1.10.1
MagicPython|mag|1.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.6.90262
vscode-yaml|red|0.8.0
vscodeintellicode|Vis|1.2.8

</details>

**Comment by dbaeumer** [comment]
This sounds like a problem caused by the extension providing the Jupyter Notebooks. Please file the issue there.

**Comment by rdlagos** [comment]
Hi same problem here, are there any workarounds in place for this?

**Comment by sws144** [comment]
I've moved to https://github.com/microsoft/vscode-python/issues/12658
