### ISSUE TITLE
Support Linux for Windows

### ISSUE THREAD

**Issue by techbykyle** [Microsoft/vscode#10129]
- VSCode Version: 1.3.1
- OS Version: Windows 10 anny update.

Steps to Reproduce:
1. Install Ubuntu for windows.
2. Install Git in Ubuntu.
3. Try to point VSC to the git binary.
   I tried doing this by setting:
   "git.path": "C:\Users\Username\AppData\Local\lxss\rootfs\usr\bin\git"
   ...but that did not work.

I just started using the Ubuntu/Bash for Windows and am very close to having my entire dev environment ready but this is one thing that prevents that.

**Comment by techbykyle** [comment]
Though i guess the point is moot since now that i tried editing files using VSC that are located on the Ubuntu file sys (e.g. C:\Users\Username\AppData\Local\lxss\rootfs\var\repos\...), said edited files are corrupted and cannot be accessed. They just show i/o errors when trying from the Ubuntu side and eventually just disapear from the Ubuntu side all together?

**Comment by joaomoreno** [comment]
I guess this is not specific to git but to pretty much every tool...

**Comment by kinglew** [comment]
i have the same problem, but i use cygwin (babun.io) on windows 10.

When i configure vscode to use the following git path:
"git.path":"C:\\Users\\<user>\\.babun\\cygwin\\bin\\git.exe"
ENOENT: no such file or directory, lstat 'C:\cygdrive'

Same problem if i simply add the above path to system environment variable PATH.

Note that this works well in webstorm/intellij based IDEs. This also works for atom editor (with gitplus).

This is most likely an issue with vscode-git integration, my guess is how the paths are being handled ('c:\cygdrive' definitely does not exist)!

**Comment by Tyriar** [comment]
@joaomoreno should we close this in favor of https://github.com/Microsoft/vscode/issues/13138?
