### ISSUE TITLE
Can't type letter C

### ISSUE THREAD

**Issue by munano96** [microsoft/vscode#101270]
Issue Type: <b>Bug</b>

I get the following error whenever i type letter C "command 'C_Cpp.ConfigurationProviderSelect' not found"

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3360M CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.44.4

</details>

**Comment by gjsjohnmurray** [comment]
Sounds like you might have a [keyboard shortcut](https://code.visualstudio.com/docs/getstarted/keybindings) defined.

**Comment by munano96** [comment]
Thankyou for your help, I've successfully dealt with the issue.

> Sounds like you might have a [keyboard shortcut](https://code.visualstudio.com/docs/getstarted/keybindings) defined.

**Comment by gjsjohnmurray** [comment]
@munano96 that's good. Now please close the issue.
