### ISSUE TITLE
ThemeService registers configuration late triggering change event

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101226]
![image](https://user-images.githubusercontent.com/900690/85944746-8e4e6c00-b939-11ea-9ba7-81bac8ff2575.png)

Is there a reason that this call is made from the constructor and not statically outside:

https://github.com/microsoft/vscode/blob/b03f792383ed259bb884cc85568374b4e347ff43/src/vs/workbench/services/themes/common/themeConfiguration.ts#L246

This triggers a `onDefaultConfigurationChange` event that clocks at `16ms` on startup.

//cc @jrieken @sandy081

**Comment by aeschli** [comment]
The default value of the configuration is defined in the constructor (it uses the environment service). Modifying the default value of an existing configuration are problematic/not allowed.

@sandy081 Any advice?

Can the configuration service wait with sending out the event until all services have been created?

**Comment by jrieken** [comment]
> Can the configuration service wait with sending out the event until all services have been created?

💯 for that. Maybe risky but I am also for not sending change event while starting up and then send one combined event once things are initialised

**Comment by sandy081** [comment]
Configuration service is created in the very beginning with no dependencies on other services. So it is tricky deferring firing events until some lifecycle phase. 

@bpasero Is it possible to have lifecycle service along with initial services?

**Comment by bpasero** [comment]
> Is it possible to have lifecycle service along with initial services?

You mean to depend on lifecycle service? Yes, why not?

**Comment by sandy081** [comment]
yeah, configuration service depending on lifecycle service.

**Comment by bpasero** [comment]
Yeah I think that might work, in the end not a lot of dependencies:

https://github.com/microsoft/vscode/blob/04203498480e48be84d86f5763e126c7c5bf22e0/src/vs/workbench/services/lifecycle/electron-sandbox/lifecycleService.ts#L27-L32

This would mean we need to move lifecycle creation into the list of services we create eagerly. And probably need to move notification service as well.

In general I am not a big fan of adding more services to the list of services we create manually and not via `registerSingleton`.

**Comment by sandy081** [comment]
I can think of two options

1. Move necessary lifecycle services to create manually during start up as initial services and add dependency (Ideal)
2. Expose an API on configuration service to start triggering events which workbench can call when all services are created.

Let me know which is the better option.

**Comment by bpasero** [comment]
Actually, 1. is not straight forward as the storage service is used inside notification service but both init in parallel with the config service...

**Comment by bpasero** [comment]
However, maybe we could simply introduce a new `ILifecyclePhaseService` which does not have any dependencies, should be no problem to extract this and adopt it.
