### ISSUE TITLE
Stage changes ends in Git fatal, saying file is outisde repository, because c:\ is used instead of C:\

### ISSUE THREAD

**Issue by StefanBa** [microsoft/vscode#101294]
- Extension version: v0.17.0
- VSCode Version: 1.46.1
- OS: win10

Steps to Reproduce:

1. change a file
2. go to Source control and right-click to the modified file
3. select "Stage changes"
4. I get this in the change log:
> git add -A -- c:\Users\bla\Documents\GitHub\bla\__init__.py
fatal: c:\Users\bla\Documents\GitHub\bla\__init__.py: 'c:\Users\bla\Documents\GitHub\bla\__init__.py' is outside repository
> git ls-tree -l HEAD -- C:\Users\bla\Documents\GitHub\bla\__init__.py

running that command in the cmd gives me also such an error:
git add -A -- c:\Users\bla\Documents\GitHub\bla\__init__.py

running it with a capital letter "C" like so, it doesnt run in an error, so I assume that the small "c" is the problem
git add -A -- C:\Users\bla\Documents\GitHub\bla\__init__.py

**Comment by gjsjohnmurray** [comment]
@StefanBa others have resolved this kind of issue by upgrading their local Git version to 2.27.

**Comment by StefanBa** [comment]
I run git --version and get the following on my PC:
git version 2.10.2.windows.1

**Comment by joaomoreno** [comment]
Can you update to Git 2.27?
