### ISSUE TITLE
Notebook cell drag area should be larger

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101284]
Open my-work.github-issues

Try to drag some cells around, notice how the Drag area is only a bit around the Expando. I think the drag area should be everything right of the title as well.
This would make it more consistent and make the feature more discoverable.
I suggest to try to behave like Split View views regardgin the drag area.

**Comment by roblourens** [comment]
There was a bug in the sizing of the drag handle. Fixed now. I want to keep it just that area on the left so it can be consistent between markdown and code cells and not take too much space

**Comment by isidorn** [comment]
@roblourens should we add bug label and milestone so I get this verified or it is good?
