### ISSUE TITLE
Shortcut to open the activity menu of specific extensions.

### ISSUE THREAD

**Issue by antoniogamiz** [microsoft/vscode#101232]
Hi, I really like to open the activity menus using my keyboard. At this moment, I can only open the default ones (explorer, scm, debugger, etc). I also would like to be able to do this with all extensions which add an activity menu, but I do not know what command should I use in the shortcut (if there's any). 

I asked [this question in Stackoverflow](https://stackoverflow.com/questions/62540503/how-to-see-the-activity-menu-of-a-specific-extension) but nobody has answered, so maybe it's not possible yet (for that reason I'm opening this issue).

**Comment by dbaeumer** [comment]
@sandy081 not sure if this is you.

**Comment by alefragnani** [comment]
Hi @antoniogamiz ,

If I remember correctly, there is no _pattern_ that you could use. I mean, the name/id of the extension is not its view name, and VS Code itself doesn’t create a name for it. 

Instead, you should look at extension’s repo and look inside the `package.json` file, searching for `contributes/viewContainers/activitybar/id`. 

In your case, I guess it should be `todo-tree-container`, based on https://github.com/Gruntfuggly/todo-tree/blob/master/package.json

```json
    "contributes": {
        "viewsContainers": {
            "activitybar": [
                {
                    "id": "todo-tree-container",
```

Hope this helps

**Comment by sandy081** [comment]
There are commands to open activity bar containers but they are not associated with keybindings 

<img width="794" alt="image" src="https://user-images.githubusercontent.com/10746682/86218856-ab757b80-bb81-11ea-84ce-982f15263ffe.png">

You can assign one from Keyboard Shortcuts Editor. You can also access these using `Open View` command

**Comment by antoniogamiz** [comment]
Thanks a lot :).

**Comment by alefragnani** [comment]
Right, @sandy081 had an easier way 😆
