### ISSUE TITLE
Bug: GitHub Sync GET request failed

### ISSUE THREAD

**Issue by ofrades** [microsoft/vscode#101273]
The sync extension works well when logged to the Microsoft account but not when logged with the GitHub account.

I receive the following error:

Error while starting Sync: GET request 'https://vscode-sync.trafficmanager.net/v1/resource/keybindings/latest' failed because of too many requests (429).

VS Code version: Code - Insiders 1.47.0-insider (7923112cdd20575406ec547b55a99c289dd7d7e2, 2020-06-29T05:53:43.438Z)
OS version: Windows_NT x64 10.0.19631

**Comment by sandy081** [comment]
Are you able to repro it ? If so can you please provide the logs available at `View -> Open View… -> Log (Preferences Sync)` ?
