### ISSUE TITLE
Ctrl+a closes the window instead of select all

### ISSUE THREAD

**Issue by withmask** [microsoft/vscode#101291]
- VSCode: Version:1.46.1
cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
x64

- OS Version: Ubuntu 20.04 LTS x86_64 

Steps to Reproduce:

1.Start visual studio code and open a file
2.Hit ctrl+a

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
What keybindings show when you search for `ctrl+a` ?

**Comment by withmask** [comment]
Select all. Tought, i have found something. I had multiple layouts in my configuration and the list had english first then french. I used the french keyboard. But for keybidings when i hit ctrl+a it runs ctrl+q but only for keybinding even tho i was using the french keyboard. This happens only in visual studio code and not other applications

**Comment by gjsjohnmurray** [comment]
Sounds like the case described in the second bullet at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

**Comment by JacksonKearl** [comment]
Closing based on @gjsjohnmurray's suggestion. Let me now if that doesn't help.
