### ISSUE TITLE
markdown footnote display error

### ISSUE THREAD

**Issue by cheapw** [microsoft/vscode#101221]
Issue Type: <b>Bug</b>

1.The built-in markdown previewer can't display Chinese in footnote content.

for example:
demo text with footnote [^1]

[^1]: if the text here is Chinese，the footnote will display some % , some numbers and Uppercase letter.

2.when the footnote content contain whitespace, such as spaces between words,  regardless of the language,  the previewer will not identify it is a footnote.

for example:
demo text with footnote [^1]

[^1]: hello world!

the previewer will display demo text with footnote [^1] 
[^1]: hello world! directly, it will not treat the text as footnote.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.20152

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|29%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|2.0.0
npm-intellisense|chr|1.3.0
dart-code|Dar|3.12.0
flutter|Dar|3.12.0
vscode-markdownlint|Dav|0.36.1
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
xml|Dot|2.5.0
vscode-npm-script|eg2|0.3.12
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
beautify|Hoo|1.5.0
csharp|ms-|1.22.1
python|ms-|2020.6.90262
debugger-for-chrome|msj|4.12.8
awesome-flutter-snippets|Nas|2.0.3
vetur|oct|0.24.0
material-icon-theme|PKi|4.2.0
java|red|0.63.0
markdown-preview-enhanced|shd|0.5.12
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.8
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
vscode-icons|vsc|10.1.1
markdown-pdf|yza|1.4.4
material-theme|zhu|3.8.2

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
The built-in markdown support does not support footnotes. 

Please file this against the markdown preview enhanced extension
