### ISSUE TITLE
VS Code problems language

### ISSUE THREAD

**Issue by matousvolf** [microsoft/vscode#101212]
I have Win 10 language set to Czech (I live there) and VS Code to English. But the errors (Problems panel) still show in Czech. How do I change it to English?
![01](https://user-images.githubusercontent.com/66163112/85940612-b29c4f80-b91d-11ea-828e-13fe4bff394b.png)

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Problems come from extensions. VS Code simply displays what it receives.
