### ISSUE TITLE
Integrated terminal highly unstable and crashes VSCode

### ISSUE THREAD

**Issue by samdoeswork** [microsoft/vscode#101246]
I *frequently* have issues where the integrated terminal causes a total crash of VSCode. This will happen a %age of all times run task is used, and quite reliably when stopping and starting a terminal task a couple of times.

This happens in Insider, and with --disable-extensions (the code --status dump below was with --disable-extensions).

- VSCode Version: 1.46.1
- OS Version: 

Steps to Reproduce:
1. Start a terminal via. run task (in this case a NPM script to webpack)
2. Restart this job (will also frequently fail when you stop, wait, start)

Does this issue occur when all extensions are disabled?: Yes

Version:          Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS Version:       Windows_NT x64 10.0.18362
CPUs:             Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)
Memory (System):  15.94GB (3.66GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --disable-extensions
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0       78   34768  code main
    0      116    1424     gpu-process
    0       25    6216     utility
    0      205    6524     window (exchangeReply.ts - JustAddFeatures-Workspace (Workspace) - Visual Studio Code)
    0        6    6456       console-window-host (Windows internal process)
    0        4    8160       C:\WINDOWS\System32\cmd.exe /d /c npm run debug_exchangeReply
    0       27   23272         "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" run debug_exchangeReply
    0        4   38784           C:\WINDOWS\system32\cmd.exe /d /s /c npx webpack && node --inspect node_modules/@google-cloud/functions-framework --target=exchangeReply --port=13023
    0       20    7128             "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npx-cli.js" webpack
    0        4   30372               C:\WINDOWS\system32\cmd.exe /d /s /c "webpack"
    0      256    4992                 electron_node webpack.js
    0       15   10424       watcherService
    0       11   10664         console-window-host (Windows internal process)
    0        4   11856       C:\WINDOWS\System32\cmd.exe
    0        6   14432       console-window-host (Windows internal process)
    0        6   22780       console-window-host (Windows internal process)
    0       69   26328       extensionHost
    0       32    2712         "C:\Users\Sam\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Sam\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=26328
    0       52    7176         electron_node tsserver.js
    0      186   35092         electron_node tsserver.js
    0       58   26776           electron_node typingsInstaller.js typesMap.js
    0       74   20452     shared-process
    0       14   34136     electron-crash-reporter

Workspace Stats:
|  Window (exchangeReply.ts - JustAddFeatures-Workspace (Workspace) - Visual Studio Code)
|    Folder (jaf): 2581 files
|      File types: ts(613) js(570) map(371) json(163) html(139) css(117)
|                  yaml(78) gcloudignore(25) png(22) hbs(22)
|      Conf files: package.json(37) webpack.config.js(26) tsconfig.json(21)
|                  tslint.json(3) launch.json(1) settings.json(1)
|                  tasks.json(1)
|      Launch Configs: node(10) cloudcode.kubernetes chrome

**Comment by samdoeswork** [comment]
Hi @Tyriar I see you've been assigned. Please let me know if there's anything I can do to help. In particular, would you like additional "code --status dump" output as I encounter more crashes?

**Comment by MkLHX** [comment]
same issue here many crashes per day everytime i used terminal in VScode 1.46.1

**Comment by MkLHX** [comment]
#99456

**Comment by samdoeswork** [comment]
Hi @dbaeumer  @Tyriar  - has anyone had any opportunity to look at this? Thank you in advance!
