### ISSUE TITLE
SCM: Provide setting to hide the repository actions, so the branch name and ahead/behind indicator are more visible

### ISSUE THREAD

**Issue by sstoychev** [microsoft/vscode#101251]
I'd like to have an option to hide the actions available for every repository as now they are hiding the name of the branch unless you make it too wide.
Old:
![image](https://user-images.githubusercontent.com/11898259/85960510-a90df880-b9ac-11ea-8600-d2fb7d637ab2.png)
New:
![image](https://user-images.githubusercontent.com/11898259/85960546-f4280b80-b9ac-11ea-968d-de693d59239f.png)

Another option would be if they are moved on the line of "Changes".
Also it would be nice to hide the badge when there are 0 changed files.

**Comment by yume-chan** [comment]
Compare to other views:

1. Their header actions are hidden when view collapsed.
2. Their header actions' visibility are controlled by `workbench.view.alwaysShowHeaderActions` setting.

And they are not aligned properly.

**Comment by sstoychev** [comment]
1. - Obviously no.
2. No:
![image](https://user-images.githubusercontent.com/11898259/85981480-eeeab100-b9ec-11ea-8341-566603f0ae3b.png)

**Comment by joaomoreno** [comment]
I think we just need to do a better job on the layout of these actions and give different priorities to resizing.

**Comment by Tyriar** [comment]
@joaomoreno I suggest only showing the actions when the section is hovered or expanded as that's when they seem to be useful. When you're not actively working on a repo the change count and branch are probably the most important, the latter of which gets truncated currently.

**Comment by joaomoreno** [comment]
@Tyriar It's not that trivial, as I've been through all iterations of this. If you hide the actions until hover, but still leave the status showing you will get the status actions to shift left when you hover, annoying people that want to click them. If you place the actions to the left of the status actions, they will be misaligned with the groups' and you will get a `...` right between normal actions.

I can definitely improve the current layout while keeping them all in there, will give that a try and see how that goes.

**Comment by joaomoreno** [comment]
Improved the layout, but did not address the original feedback: how to show the actions when the user prioritizes the branch name?

**Comment by sstoychev** [comment]
The issue is not only with the branch name. The buttons are also hiding the commits behind/ahead.
I'll wait for the new build

**Comment by sstoychev** [comment]
Just to better illustrate the issue:
![image](https://user-images.githubusercontent.com/11898259/86333733-f57b6180-bc54-11ea-9c34-042266579475.png)
In "changes" the actions available for each file are shown only on hover. 
In the previous setup the buttons for synchronize, refresh and commit were on a separate line and thus were shown only once. This was giving enough space on the line with the repository for the labels with information. Currently you are always seeing these buttons which give you no information.

The idea with hiding the chevron for the repos without changes is great! I wish the counters with 0 changes to be hidden also, but I realize this would mess the alignment of the action buttons. Probably this should be left for the next time when the look is reviewed.
Let's us vote! :)

**Comment by yume-chan** [comment]
> Obviously no.

I mean other views do.

> In "changes" the actions available for each file are shown only on hover. 

This can be toggle with `scm.alwaysShowActions` setting (see #101257) (and I prefer always showing them).
