### ISSUE TITLE
Tab title shows dirty long file path after relaunching workspace on WSL

### ISSUE THREAD

**Issue by ahmad-taha** [microsoft/vscode#101241]
Issue Type: <b>Bug</b>

1. Open 2 files with same name from different folders. Something like views.py from multiple Django apps. It will look like this:
![image](https://user-images.githubusercontent.com/30227751/85954355-7c4de700-b994-11ea-9e50-54a9966a679c.png)

2. Relaunch VS Code. Both tabs will show dirty file paths instead of just folder names, like in following picture. Note - The tab which was active while you closed VS Code won't be affected.
![image](https://user-images.githubusercontent.com/30227751/85954631-896bd580-b996-11ea-8499-dc513157cf25.png)

This bug extends the tab width and takes more space, also makes it difficult to see and switch between lot multiple files with the same name. 
For example, I have a Django workspace with about 6-7 different apps and all contain views.py, models.py, etc. So need to switch between them a lot frequently, and this bug makes it difficult to read the app name quickly.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|Memory (System)|15.95GB (7.84GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-postgres|cko|1.1.11
gitlens|eam|10.2.2
python|ms-|2020.6.90262
vscode-edge-devtools|ms-|1.0.7
remote-wsl|ms-|0.44.4

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Looks like a label formatter issue to me, maybe an event missing when the remote connection is resolved?

**Comment by isidorn** [comment]
There were similar issues filles filled.
I ackonlewdge this bug, however I will not have time to look into it in the near future.
In case somebody from the community wants to investigate, code pointer
https://github.com/microsoft/vscode/blob/b58df64fd23e9639972d4b669d37365a76955d07/src/vs/workbench/services/label/common/labelService.ts#L136

**Comment by ahmad-taha** [comment]
This issue seems to be fixed now.
