### ISSUE TITLE
unsupported in tittle

### ISSUE THREAD

**Issue by SamyakUkey** [microsoft/vscode#101235]
Issue Type: <b>Bug</b>

i updated vs code after that it is showing corrupt code and to reinstall it

VS Code version: Code - Insiders 1.47.0-insider (9bf6af04dcb5c2e531cedca83cd188939ca1b0db, 2020-06-26T18:55:07.038Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by joaomoreno** [comment]
Please reinstall VS Code.

**Comment by SamyakUkey** [comment]
> Please reinstall VS Code.

sir i did it 5-6 times but repeatedly i got the same message.

**Comment by gjsjohnmurray** [comment]
Do you have any antivirus running? Did you check in case it quarantined or deleted anything when you installed VS Code?
