### ISSUE TITLE
Project not loading on remote server in vscode insiders (working in other remote workspaces/ regular vs code)

### ISSUE THREAD

**Issue by dvirginz** [microsoft/vscode#101222]
- VSCode Version: 1.47 insiders
- OS Version: Ubuntu 18.04

I probably caused it somehow(..), but I cannot undo it, the window hangs indefinitely. I saw previous posts regarding hanging workspaces, all pointing to large files in the workspace, but there are none (and the settings of both the insiders and the regular are the same)
Other workspaces in the same remote server still open, and this workspace opens in regular (not insiders) vscode
![image](https://user-images.githubusercontent.com/31047807/85943611-d1a8da80-b939-11ea-9537-2834bc20106e.png)

**Comment by dbaeumer** [comment]
@dvirginz how do youy connect to the remote. Using SSH?
