### ISSUE TITLE
Not Able to create project and Authorize an org. VS code is stuck in Activating Extensions

### ISSUE THREAD

**Issue by KhusbooHhicglobalsolutions** [microsoft/vscode#101229]
-VS Code version: Code 1.46.1 (cd9ea64, 2020-06-17T21:13:20.174Z)
-OS version: Windows_NT x64 10.0.18362

Steps to Reproduce:

Issue Type: Bug

I installed the latest version of Salesforce CLI and after that installed the latest version of VS code (1.46). When I tried to create project or create project with Manifest, it shows Activating Extensions.
Sometimes I have also seen the notification-
The extension 'Salesforce CLI Integration' took a very long time to complete its last operation and it has prevented other extensions from running. OR
The extension 'Apex' took a very long time to complete its last operation and it has prevented other extensions from running.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexdima** [comment]
Please create an issue directly against the problematic extensions.
