### ISSUE TITLE
Characters lost from random lines.

### ISSUE THREAD

**Issue by sherinsugathan** [microsoft/vscode#101228]
Issue Type: <b>Bug</b>

Ctrl+Shift+Alt helps to make the cursor span over multiple lines. I used it to remove indentation space from multiple lines. After this action I noticed that I got one character removed from "random lines"!!! I did not tested this again and again as I am busy. I am not even 100% sure that the multiline cursor spanning is the issue. That was the only step I remember I did before I noticed hundreds of compiler errors. I am leaving it to you for investigation. I am 100% sure that there is a problem. Don't stick to Ctrl+Shift+Alt as I am not sure about it. I just wanted to report that I encountered this painful problem. Yesterday I added back the missing characters. Today I noticed that I have missing characters from the comments as well. So I thought of reporting.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
code-runner|for|0.10.0
d3-js-snippets|Hri|1.0.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.6.90262
cpptools|ms-|0.28.3
powershell|ms-|2020.6.0
vscode-yaml|red|0.8.0
vscode-qt-for-python|sea|0.4.2
shader|sle|1.1.4

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
I am sorry, but I cannot reproduce with the provided steps. Please provide clear reproducible steps.
