### ISSUE TITLE
the terminal shows the same

### ISSUE THREAD

**Issue by zunoa** [microsoft/vscode#101206]
(VS code) the terminal is showing me the same thing.... i mean, niether if i change something on my code. the terminal shows the same thing.

my code:

#include <iostream>

int main()
{
     std::cout << "you are a lil boy runing from dead..."; 
     std::cout << std::endl;
     std::cout << "enter the correct code to continue..."; 
     
     int a = 3;
     int b = 6;
     int c = 9;

     std::cout << std::endl;
     std::cout << a;

    return 0;
 
 } 

and what the terminal show me:

you are a lil boy runing from dead
enter the correct code to continue4

**Comment by Tyriar** [comment]
What's the issue?
