### ISSUE TITLE
Support to contribute a custom view so that it is only visible in the Views menu of view's container

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#101283]
Currently it is not possible to contribute a custom view so that it is visible in the 'Views' menu only but not also in the View Container. This will help to improve the 1st run experience and to reduce the clutter of the Explorer view, e.g., the NPM Script Explorer would no longer be visible by default (when there is a package.json)

**Comment by alexr00** [comment]
Current contribution point:
```json
    "views": {
      "explorer": [
        {
          "id": "npm",
          "name": "%view.name%",
          "when": "npm:showScriptExplorer || config.npm.enableScriptExplorer",
          "icon": "images/code.svg"
        }
      ]
    }
```

Proposal is to add a `initialState` or `defaultState` which can be set to `visible`, `collapsed`, or `hidden`. The default value would `visible`. Example:
```json
    "views": {
      "explorer": [
        {
          "id": "npm",
          "name": "%view.name%",
          "when": "npm:showScriptExplorer || config.npm.enableScriptExplorer",
          "icon": "images/code.svg",
          "initialState": "hidden"
        }
      ]
    }
```

**Comment by alexr00** [comment]
This has been finalized.
