### ISSUE TITLE
Exact match in completion overrides CompletionItem.sortText

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#101254]
- VSCode Version: 1.46.1
- OS Version: macOS 10.15.5

The completion items provider of a language server could specify `CompletionItem.sortText` (as defined in https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion) to adjust the order of completion items. However, exact match in the completion list overrides the ordering specified by `CompletionItem.sortText`.

For example, the completion items are 

```
label (sortText)
---------------
test (0-test)
tes  (1-tes)
```

If user types `tes`, both completion items appear but `tes`, as an exact match of current input, ranks higher than `test` even though `test` should rank higher in terms of its `sortText`.

Related:

* https://github.com/REditorSupport/languageserver/issues/285
* https://github.com/REditorSupport/languageserver/issues/288

**Comment by jrieken** [comment]
That's the design. What a user types (the prefix) always counts more than what the extension wants

**Comment by renkun-ken** [comment]
In the example at https://github.com/REditorSupport/languageserver/issues/288, the user is inputing the following function call:

```r
sample(1, 1, rep|
```

where `|` stands for the cursor. While there's a function named `rep`, we actually want `sample`'s argument `replace` to always rank higher than other symbols in this case. 

In fact, we want to implement a principle to give different priorities to different category of completion items: from local to global. Is there a way we could ensure that some completion items always rank higher than others even if the current token under cursor has an exact match (which is in most cases not desired)?

**Comment by HaoboGu** [comment]
> That's the design. What a user types (the prefix) always counts more than what the extension wants

I don't think this is a good design, look at the following example:
![image](https://user-images.githubusercontent.com/8640918/87114600-94cad500-c2a3-11ea-84a3-fd9868b73ab1.png)

I have already typed `Test`, the suggestion of `Test` is meaningless: nothing will happen if I choose `Test`.

So I think the prefix matching, at least the exact matching(the suggestion is exact same as the prefix) should not override the sortText.
