### ISSUE TITLE
[VS Code Insider] WebView Bug - Cut, Copy and Paste does not work anymore in <input> fields

### ISSUE THREAD

**Issue by L13** [microsoft/vscode#101201]
Issue Type: <b>Bug</b>

Hi,

my extension L13 Diff https://marketplace.visualstudio.com/items?itemName=L13RARY.l13-diff uses webviews. In the webview are native HTML input elements. In the current version of VS Code Insider it's possible with the keyboard shortcut meta+a to select the value in an input field, but it is not possible anymore to cut (meta+x), copy (meta+c) or paste (meta+v) a value.

This bug is not in VS Code <= 1.46.1

Steps to Reproduce:

1. Download/Install the extensions [L13 Diff](https://marketplace.visualstudio.com/items?itemName=L13RARY.l13-diff).
2. Open the command palette (Ctrl/Meta+Shift+P) and search for "L13 Diff" or press "Ctrl+L Ctrl+L" on Windows/Linux or "Meta+L Meta+L" on macOS.
3. Now try to paste a value into the input fields -> Does not work

VS Code version: Code - Insiders 1.47.0-insider (9bf6af04dcb5c2e531cedca83cd188939ca1b0db, 2020-06-26T21:11:02.609Z)
OS version: Darwin x64 19.5.0

**Comment by L13** [comment]
Additional Info:

I found a funny side effect.

1. Download/Install the extensions L13 Diff.
2. Open the command palette (Ctrl/Meta+Shift+P) and search for "L13 Diff" or press "Ctrl+L Ctrl+L" on Windows/Linux or "Meta+L Meta+L" on macOS.
3. Open the Extension View.
4. Type `@builtin`
5. Now click in an input field in the webview.
6. Press "Ctrl/Meta+A" to select all.
7. Press "Ctrl/Meta+C" to copy the value.
8. Press "Ctrl/Meta+V" to paste the value multiple times.
9. Look at the input field in the extension view -> `@builtin @builtin @builtin ...`

This should not happen.

**Comment by mjbvz** [comment]
Thanks for catching this. 

This Should be fixed by 7f138d56a0c8ccd44d1835260d8e989ca1649866 which is the current insiders build. Let me know if you still see issues

**Comment by jrieken** [comment]
\closedWith 7f138d5
