### ISSUE TITLE
VSC debugger error: XDLError: packagerPort must be an integer

### ISSUE THREAD

**Issue by mjstelly** [microsoft/vscode#101236]
- VSCode Version: 1.46.1
- OS Version: macOS 10.15.5
- Platform: React Native 0.61.x, Expo: 37.0.3

The `expo-cli` authors requested I open an issue here. They believe it's a problem with how the VSC debugger connects to Expo. Please reference this issue, [XDLError: packagerPort must be an integer
](https://github.com/expo/expo-cli/issues/2295) for details.

Does this issue occur when all extensions are disabled?: Yes (sort of). The expo debugger won't run at all if extensions are disabled because it depends on the `React Native Tools` extension. Of course, the `reactnative` issue goes away when extensions are re-enabled. That leaves me with 3 dependencies: VSC, React Native Tools, Expo. I hope someone can help. Javascript debugging is enough of a chore already without having to wrestle with the tools. 

Please advise.

![Screen Shot 2020-06-28 at 10 12 24 AM](https://user-images.githubusercontent.com/313819/85951300-e7150900-b927-11ea-9bb7-5e49b9f81929.png)

```
        {
            "name": "Debug in Exponent",
            "cwd": "${workspaceFolder}",
            "type": "reactnative",
            "request": "launch",
            "platform": "exponent"
        }
```

**Comment by weinand** [comment]
Please file this issue against the extension that implements the "reactnative" debugger.
