### ISSUE TITLE
[css] allow to supress linting warning with ignore comment

### ISSUE THREAD

**Issue by KyleMit** [microsoft/vscode#101249]
Some linting libraries like [CSSLint](https://github.com/CSSLint/csslint) allow you to [Ignoring parts of CSS during linting](https://github.com/CSSLint/csslint/wiki/Ignoring-parts-of-CSS-during-linting)

Like this:

```css
/* csslint ignore:start */
@import('normalize.css');
/* csslint ignore:end */
```

Or like this:

```css
.foo.bar { /* csslint allow: adjoining-classes */
    margin: 0;
}
```

I believe this was also implemented for [microsoft  / vscode-eslint](https://github.com/microsoft/vscode-eslint/issues/245)

Can this be added for the default linting features in VS Code?

Possible workarounds are to turn off CSS linting altogether:

```json
{
    "css.validate": false,
}
```

Or disable just the rule everywhere:

```json
{
    "css.lint.vendorPrefix": "ignore"
}
```
But sometimes the rule fits 95% of cases and it's nice to be able to toggle it off individually when neccessary

**Comment by willmtemple** [comment]
This would be very helpful until https://github.com/microsoft/vscode/issues/85828 can be addressed. I've got this warning about an unknown property staring at me even though I know it's a legit SVG 2 setting, and I can't figure out if there's a way to just disable it on that one line short of setting the entire warning category to be ignored.

![image](https://user-images.githubusercontent.com/666532/115967086-773ec300-a4e5-11eb-844e-2f14a7c29ce2.png)

**Comment by aeschli** [comment]
I recommend to use the settings `css.lint.validProperties` you can give a list of properties which are not validated against.

**Comment by s-gbz** [comment]
I agree, this feature would be awesome considering that [Jekyll requires front matter](https://jekyllrb.com/docs/assets/) to identify .scss that will be parsed into css.

```
---
---
```

It has to start like this & leads to a nasty, permanent warning in the file explorer.

**Comment by underr-ua** [comment]
> I agree, this feature would be awesome considering that [Jekyll requires front matter](https://jekyllrb.com/docs/assets/) to identify .scss that will be parsed into css.
> 
> ```
> ---
> ---
> ```
> 
> It has to start like this & leads to a nasty, permanent warning in the file explorer.

Just leaving it here as a temporary solution from [Fixing vscode scss linting “errors” on front matter](https://talk.jekyllrb.com/t/fixing-vscode-scss-linting-errors-on-front-matter/1710)

create a workspace (`*.code-workspace`) file with the following content:
```
{
    "settings": {
        "scss.validate": false
    }
}
```

**Comment by linusjf** [comment]
Any updates about this? Should users abandon csslint?

**Comment by aeschli** [comment]
We have no plans of introducing a new syntax for ignore.

Closing as out-of-scope

**Comment by marcospgp** [comment]
Landed here from google as well, dealing with the same issue where having to include empty front matter in Jekyll causes the first SCSS line to report an error that currently cannot be ignored.

**Comment by Chrysaloid** [comment]
@aeschli:
> We have no plans of introducing a new syntax for ignore.
> 
> Closing as out-of-scope

Why? What is your solution to this **still existing** issue?

**Comment by douira** [comment]
VScode doesn't appear to support the [`string-set` property](https://www.w3.org/TR/css-gcpm-3/#setting-named-strings-the-string-set-pro) so it would be nice if one were able to disable the warning that it's unknown, because it might not be but the linter doesn't know. This feature is relevant and necessary.

**Comment by aeschli** [comment]
I recommend to use the settings css.lint.validProperties you can give a list of properties which are not validated against. Or turn of validation and replace by running `styleint` as part of your build process. There's also an extension for that: https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint
