### ISSUE TITLE
TS: implementing interface uses double quotes and not single quotes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101219]
If you implement an interface via TS that uses string literals, the generated methods use double quotes and not single quotes which results in warnings in our code. Similar to imports, they should use single quotes if the file is using single quotes.

Example:

```ts
interface Foo {
   sendInputEvent(event: { type: 'mouseDown' | 'mouseUp'; x: number; y: number; clickCount: number; }): Promise<void>;
}
```

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/39332 to track upstream
