### ISSUE TITLE
High cpu usage  Code Helper (Renderer)

### ISSUE THREAD

**Issue by droplab** [microsoft/vscode#101247]
Issue Type: <b>Bug</b>

This process is constantly >= 100% usage even when a single window is open. It's constantly spinning up fans on my imac and is driving me nuts. This has been an ongoing issue for months now.

I'm running Mojave 10.14.6

Please advise!

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 6|
|Memory (System)|64.00GB (31.37GB free)|
|Process Argv|-psn_0_6452775|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.5
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
docker-explorer|for|0.1.7
prettify-json|moh|0.0.3
vscode-docker|ms-|1.3.1
material-icon-theme|PKi|4.2.0
sass-indented|rob|1.5.1
python|tht|0.2.3

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Can you collect a snapshot of the process as described [here](https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu)

**Comment by deviun** [comment]
Same. Macos Catalina. electron_node tsserver.js
<img width="1232" alt="Screenshot 2020-07-01 at 12 44 03 PM" src="https://user-images.githubusercontent.com/16022500/86229907-0c5c7e00-bb99-11ea-80a9-205bf18501f1.png">

**Comment by jrieken** [comment]
@deviun How do you know that @droplab is using TypeScript?

**Comment by deviun** [comment]
> @deviun How do you know that @droplab is using TypeScript?

I am not use TS in project with this issue. Despite tsserver.js is running.

**Comment by jrieken** [comment]
No TS and also no JS? what files do you have open? what project are you working on?

**Comment by deviun** [comment]
JS, React/NextJS. Observed also with NodeJS project. Often happens after npm install command.

**Comment by jrieken** [comment]
As far as we are concerned that's TypeScript, or to be precise TypeScript is used form JavaScript language features. Still, doesn't explain why you think that @droplab has an issue with tsserver

**Comment by deviun** [comment]
Sorry, I am not reply instead of @droplab. I notice about same issue with high cpu usage from Code Helper (Renderer). And sent my process explorer screen and explain when it happened. Is ok high cpu after npm install?(

**Comment by jrieken** [comment]
> Is ok high cpu after npm install?

Try installing latest TypeScript 4.x which has fixed that issue.
