### ISSUE TITLE
Force auto-complete imports to use rewritten paths

### ISSUE THREAD

**Issue by yorrd** [microsoft/vscode#101214]
I have the following tsconfig.json:

```
{
  "compilerOptions": 
    ...
    "paths": {
      "@adornis/*": ["./imports/git_modules/*"]
    },
    ...
  }
}
```

When I import something from `@adornis/...`, it automatically suggests a relative path, for example `../../base/file` instead of `@adornis/base/file`.

Can we add the possibility to force VSCode to automatically suggest rewritten paths on auto complete if available?

Motivation: We use this path rewrite to be able to switch between different branches of these submodules or potentially even switch to already compiled npm modules (also called `@adornis/...`) to reduce project size and therefore compile time and bundle size. It's working like a charm except for us having to rewrite almost half of our imports by hand.

**Comment by mjbvz** [comment]
Have you tried setting: `"typescript.preferences.importModuleSpecifier": "non-relative"`?

**Comment by yorrd** [comment]
@mjbvz yes, in fact that's part of our standard config, so it's been in there forever :)

**Comment by mjbvz** [comment]
Thanks. Can you please share a minimal project that triggers this bug?

**Comment by yorrd** [comment]
@mjbvz have a look here: https://github.com/yorrd/vscode-import-repro . There's a file `lookhere.ts` which contains what I'm getting and what I'd like.

Thanks in advance!

**Comment by yorrd** [comment]
actually. Never mind. Here's the solution:

For people from google: the order of the paths in my `tsconfig` was reversed. It's using them by priority. 

Sorry @mjbvz for the hassle and thanks for the ideas!
