### ISSUE TITLE
VSCode switches to different tab when I save the file (even via the File menu)

### ISSUE THREAD

**Issue by Ark-kun** [microsoft/vscode#101260]
- VSCode Version: 1.44.2
- OS Version: Windows 10 Pro 1903

Steps to Reproduce:

1. Open multiple files in VSCode and work for days or weeks
2. Save an open file (no need to change it). You can save using Ctrl+S and weirdly even via the File menu.

Actual behavior:
The file is saved, but VSCode switches to the tab to the left of the active tab. Usually it's the adjacent left tab, but right now it goes left 3 tabs.

I thought that this might be some issue with the Ctrl+S shortcut, but now i see that this happens when when you use the mouse and the File/Save.

This issue fixes itself when restarting VSCode.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Ark-kun** [comment]
> I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

The problem is that this bug does not survive VSCode restarts. I had this issue ~3 times. Each time is was 100% reproducible until reopening the VSCode.

**Comment by bpasero** [comment]
Can you maybe record a screen cast that demos the problem?

**Comment by Ark-kun** [comment]
> Can you maybe record a screen cast that demos the problem

I'll try to do that when it happens again.

But it's pretty mundane really: Click "File/Save" or press Ctrl+S and the active editor window tab switches to another opened file.
