### ISSUE TITLE
Undo/Redo not working in search bar.

### ISSUE THREAD

**Issue by m-garg** [Microsoft/vscode#10126]
- VSCode Version: 1.3.1 (1.3.1)
- OS Version: OS X El Capitan (10.11.4)

Steps to Reproduce:

- In any opened file, press Cmd + f.
- Type something.
- Cmd + z to undo what you typed last in the search bar.
- "Undo" action applied on the opened file instead of search input field.

When in focus, undo-redo should work in search bar, as copy-paste do.

**Comment by aeschli** [comment]
That works on Linux/Ubuntu, but not on OSX.

**Comment by alexandrudima** [comment]
Most likely it is the menu stealing the keybinding

**Comment by FabianLauer** [comment]
Isn't this a dupe of #151?

**Comment by alexandrudima** [comment]
Yes, let's track in #151
