### ISSUE TITLE
Notebook cells: as I am moving mouse around there is constant hover feedback

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101285]
1. Open `my-work.github-issues`
2. Move your mouse up / down slowly
3. Notice how there is constant hover feedback which I personly dislike and find noisy

I am not sure what is the benefit of showing hover feedback on the cell when the mouse is over the editor.
In VS Code we do not show hover feedback when a user hover over an editor group.
The hover feedback is also too nervous. If we decide to keep it, it should use a lighter color to make it more calming.

![notebookHover](https://user-images.githubusercontent.com/1926584/86014000-14dd7900-ba20-11ea-8e0b-4c1fc011aa17.gif)

**Comment by roblourens** [comment]
There is a nice blue color as the background in the next build, lmk if that helps

**Comment by isidorn** [comment]
@roblourens just updated to the latest insiders da73d2d11540232a5c75788ac0c9b41c3d432b2d  and I see the same as before.

**Comment by isidorn** [comment]
Ok, I see the blue color with the default theme. While I think it is better, it is still pretty nervous and I personally do not like it.

Also it does not work in high contrast theme

![Screenshot 2020-06-30 at 11 37 43](https://user-images.githubusercontent.com/1926584/86110737-38f39580-bac6-11ea-93a8-e62398919adf.png)

**Comment by roblourens** [comment]
Should we just not have the hover feedback at all in HC?

**Comment by misolori** [comment]
@isidorn are you also suggesting that the hover state should be removed?

**Comment by isidorn** [comment]
Yeah I think the hover state should just be removed. That would be fantastic.

**Comment by misolori** [comment]
Not sure how I feel about removing the hover, it does remove a bit of the visual noise but then it's also hard to see/notice that you can still perform actions on the cells on hover.

![Kapture 2020-07-01 at 8 45 17](https://user-images.githubusercontent.com/35271042/86264417-5896c680-bb77-11ea-9533-f5c4b62c0a37.gif)


@rebornix @jrieken thoughts?

**Comment by jrieken** [comment]
I really like hover feedback, it gives me a better understanding about whats happening. Tho, in comparison to the list or tree the color is quite strong. Maybe weaking that a little would help

**Comment by misolori** [comment]
We've come along way now and only show hover feedback for the run action + in between cells:

https://user-images.githubusercontent.com/35271042/135935905-49ed3837-abf1-4012-9285-d6373b8f30f2.mp4
