### ISSUE TITLE
[semantic] Allow to enable semantic highlighting for a language

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#101292]
Currently it is up to themes to decide whether semantic highlighting is enabled. The built-in theme enable it by default, while custom theme control it with the `semanticHighlighting` in the theme. Additionally, user can override that setting with 
```
	"editor.semanticTokenColorCustomizations": {
		"[Atom One Dark]": {
			"enabled": true
		}
	}
```

The problem is some languages very much depend on semantic highlighting as their TextMate grammar are limited due to the language's syntax.
C++ is an example: https://github.com/microsoft/vscode/issues/99499

**Comment by pgfearo** [comment]
XSLT 3.0 is another language example. The language extension only uses Semantic Highlighting, there is no TextMate grammar for XSLT 3.0, so no highlighting at all with most themes until the setting is changed.

**Comment by aeschli** [comment]
"editor.semanticHighlighting.enabled" now has 3 possible values: `true`, `false` and `configuredByTheme`.
`configuredByTheme` is the new default.

Language that want to enforce semanticHighlighting can define in the package.json:
```
      "[html]": {
        "editor.semanticHighlighting.enabled": true
      }
```
