### ISSUE TITLE
Ctrl+left arrow behaves incorrectly when there is no character immediately to the right of the cursor

### ISSUE THREAD

**Issue by RheingoldRiver** [microsoft/vscode#101243]
- VSCode Version: 1.46.1
- OS Version: Windows 10
 
Steps to Reproduce:
 
1. Type the following code `Hello `
2. Press Ctrl+left arrow
3. Your cursor SHOULD end up to the left of the `H` but instead will end up to the right of the `o`
4. This is in contrast to typing `Hello w` then left arrow then ctrl+left
 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
@RheingoldRiver I cannot reproduce with your steps. Can you please try to disable all extensions?

**Comment by RheingoldRiver** [comment]
Hi, are you typing a space after Hello? sorry I realized only now that it's not obvious from the code block that there's one there.

**Comment by RheingoldRiver** [comment]
Thanks!!
