### ISSUE TITLE
Terminal can't delete character

### ISSUE THREAD

**Issue by BayuZangetsu** [microsoft/vscode#101231]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

while using terminal inside vscode, when I write some words it work fine but when I want to delete or backspaces, text not deleted
example :
i wrote i love you
then i want to delete 1 word and become i love yo
but what happens is not delete but give spaces

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 5.4.0-7634-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7410 APU with AMD Radeon R5 Graphics (4 x 2183)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|6.75GB (0.93GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
entitas-unused-components-finder|Ari|1.2.0
unity-code-snippets|cem|0.1.0
dart-code|Dar|3.12.0
flutter|Dar|3.12.0
gitlens|eam|10.2.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
beautify|Hoo|1.5.0
unity-snippets-modified|lio|0.4.0
csharp|ms-|1.22.1
python|ms-|2020.6.90262
cpptools|ms-|0.28.3
111-unity-csharp-extensionpack|pen|2.2.0
platformio-ide|pla|1.10.0
project-snippets|reb|0.5.0
ayu|tea|0.20.1
unity-tools|Tob|1.2.3
vscode-input-sequence|tom|0.2.0
sort-lines|Tyr|1.9.0
unity-debug|Uni|2.7.5
change-case|wma|1.0.0
unity-snippets|Ycl|0.1.2

</details>

**Comment by antoniogamiz** [comment]
Maybe a duplicated: https://github.com/microsoft/vscode/issues/18985

**Comment by Tyriar** [comment]
Please provide a screenshot of [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
