### ISSUE TITLE
Wrong formatting node js file

### ISSUE THREAD

**Issue by tarunzoot** [Microsoft/vscode#10120]
- VSCode Version: 1.3.1
- OS Version: OSX El Capitan 10.11.6

Steps to Reproduce:
tab size = 4 spaces
write the following code in vscode and press alt+shift+f, next statement after `try` i.e `var connection = mysql.createConnection({` should have 4 spaces 

> var fs = require('fs');
> var mysql = require('mysql');

> try {
  var connection = mysql.createConnection({
    host: '127.0.0.1',
    user: 'root',
    password: 'root',
    database: 'test'
  });

>   connection.connect(function(err) {
    if (err) {
      throw err;
    }

   > connection.query(
        'SELECT 1', function(err, nRows) {
          if (err) {
            throw err;
          }
          console.log(nRows);
        })
   > connection.end(function(err) {
      if (err) throw err;
    })

 > })
} catch (error) {
  console.log(error);
}

**Comment by dbaeumer** [comment]
@tarunzoot what does VS Code think the file is formatted with. There should be something in the right corner of the status bar saying either Tab or Spaces: x.

**Comment by tarunzoot** [comment]
Fresh launch:
<img width="1433" alt="screenshot" src="https://cloud.githubusercontent.com/assets/18568258/17409694/f5cc0554-5a8d-11e6-9720-b201031ae3ce.png">

After changing indentation to 4 spaces,
<img width="1430" alt="screenshot" src="https://cloud.githubusercontent.com/assets/18568258/17409613/a4c4f51c-5a8d-11e6-903e-1ebdc1a2aebd.png">

I deleted and created a new file also, but every time it launches, the indentation level becomes 2 spaces

my settings.json:
>`// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "Source Code Pro, Menlo, Monaco, 'Courier New', monospace", "editor.fontSize": 16, "editor.formatOnType": true, "editor.glyphMargin": true, "editor.renderWhitespace": true, "editor.renderControlCharacters": true, "editor.renderIndentGuides": true, "editor.wrappingColumn": 0,  "explorer.openEditors.visible": 0, "window.openFilesInNewWindow": false,
    "window.reopenFolders": "all",
    "window.restoreFullscreen": true,
    "workbench.editor.showTabs": false,
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 1000,
    "files.trimTrailingWhitespace": true,
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true,
    "php.validate.executablePath": "/usr/local/bin/php",
    "html.format.indentHandlebars": true,
    "html.format.wrapLineLength": 0,
    "html.format.unformatted": "abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, label, map, object, q, samp, script, select, small, span, strong, sub, sup, textarea, tt var",
    "editor.scrollBeyondLastLine": false
}`

**Comment by dbaeumer** [comment]
I am not able to reproduce this in a simple toy example. @tarunzoot could you share your project. And how did you change from 2 -> 4 spaces.

What is very wired as well is that new files are formatted with 2 spaces since the settings clearly indicate 4 spaces. CCing @alexandrudima

**Comment by tarunzoot** [comment]
I clicked on Spaces at the bottom status bar strip of editor, and in the popup panel I clicked `Indent Using Spaces` and clicked on 4 (Configured Tab Size).
Link to my project https://github.com/tarunzoot/temp.git

**Comment by dbaeumer** [comment]
@tarunzoot I cloned the project had did the following:

- formatted script.js. This results in a correct format. When a document gets formatted its inferred settings are used (in this case 2 spaces) and not the once under editor.tabSize. This is for new files.
- changed spaces to 4. Formatted. Which results for me in correct behavior as well.

![cast](https://cloud.githubusercontent.com/assets/1931590/17477391/55f378a2-5d65-11e6-931e-dfdc4396b52f.gif)


Am I missing something?

**Comment by dbaeumer** [comment]
We look for a user settings file as well. However workspace settings always have preference over user settings. Do you have an extension install that might cause that. You can start vscode with `--disable-extensions` to ensure this is not a side effect of an extension (e.g. like editor config, ....)

**Comment by alexandrudima** [comment]
@tarunzoot Please review the settings you have configured around indentation guessing:

![image](https://cloud.githubusercontent.com/assets/5047891/17510955/61b47350-5e21-11e6-9cfe-2b0dcdf639ed.png)

By default, the indentation will be guessed from the file you open.

**Comment by tarunzoot** [comment]
thanks @dbaeumer and @alexandrudima for your suggestions, --disable-extensions works, an extension is causing this behaviour, thanks again

**Comment by tarunzoot** [comment]
`clang-format` plugin was causing this problem
