### ISSUE TITLE
TypeScript breakpoints not hit when workspace/folder path is a directory junction

### ISSUE THREAD

**Issue by spinard65** [microsoft/vscode#101287]
Issue Type: <b>Bug</b>

If the file system path to the open workspace/folder is a directory **junction**, then breakpoints will not work.  Breakpoint tooltips show either "Breakpoint set but not bound" or "Breakpoint ignored because generated code not found (source map problem?)".  If the path is a directory symlink, then breakpoints work.

Steps to repro:
1.  Create a new folder somewhere a few directories deep, e.g. `mkdir C:\Users\user-name\source\testproject`
2.  Create a helloworld.ts file with a simple one-liner:
    `console.log('Hello World');`
3.  Set a breakpoint on the line, and verify that the debugger halts at the breakpoint when you press `F5`
4.  Now create a directory junction to the path in step #1, e.g.
     `mklink /J C:\testproject C:\Users\user-name\source\testproject`
5.  Re-open the workspace/folder using the junction path:  `C:\testproject`
6.  Set the breakpoint as in step #3 and press `F5`
OBSERVE:  Debugger does not halt at breakpoint.

If instead of a junction you create a directory symlink, then breakpoints work:
    `mklink /D C:\testproject C:\Users\user-name\source\testproject`

FYI - Issue #97109 is another junction-related bug.  Unsure if they are related.

---
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1270 v5 @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (22.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details>Extensions: none

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? We have a new debugger implementation in Insiders that might fix this https://code.visualstudio.com/insiders

**Comment by spinard65** [comment]
No difference with insider build 1.47.0-insider.  Still does not stop at breakpoints with junction in file path.Thanks.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Rob Lourens <notifications@github.com> Date: 6/30/20  12:27 AM  (GMT-05:00) To: microsoft/vscode <vscode@noreply.github.com> Cc: spinard65 <spinard65@gmail.com>, Author <author@noreply.github.com> Subject: Re: [microsoft/vscode] TypeScript breakpoints not hit when workspace/folder path is a directory junction (#101287) 
Can you try downloading the Insiders' build and tell me whether it happens there? We have a new debugger implementation in Insiders that might fix this https://code.visualstudio.com/insiders

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/microsoft/vscode/issues/101287#issuecomment-651524417",
"url": "https://github.com/microsoft/vscode/issues/101287#issuecomment-651524417",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by connor4312** [comment]
This can be fixed by telling Node to `--preserve-symlinks`. This is the same behavior needed when dealing with npm link'd modules, for example. https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks
