### ISSUE TITLE
Missing translations for older features in 1.4.0

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#10139]
- VSCode Version: 1.4.0
- OS Version: All

Steps to Reproduce:

1.  The Explorer Viewlet:
`Explorer`, `Left`, `Right`, `Center` should be localized.
![image](https://cloud.githubusercontent.com/assets/16890566/17414681/3c339f5a-5a3b-11e6-90d8-a9c272fb5894.png)

2. Tooltip for Debug Console has the Keyboard Shortcut that shouldn't get localized
![image](https://cloud.githubusercontent.com/assets/16890566/17414854/100d13b0-5a3c-11e6-891e-8d4c3289efb4.png)

3. Tooltip for gear in the debug viewlet is not localized
![image](https://cloud.githubusercontent.com/assets/16890566/17414938/649c8492-5a3c-11e6-96b7-52151bd99ca9.png)

4. `Show Recommended Extensions` in the drop down in Extensions viewlet is not localized
![image](https://cloud.githubusercontent.com/assets/16890566/17416516/56fd289e-5a43-11e6-9a24-356d936b2397.png)

**Comment by dbaeumer** [comment]
Translation process is back to normal again. Will close. For 1.5 we need to do a final translation verification anyways since we want to ship fully localized.

**Comment by Tyriar** [comment]
All these seem fine, I'll mark as verified. @dbaeumer please reopen if "Strg" and "Umschalttaste" are not supposed to be translated from "Ctrl" and "Shift" as they seem to be globally translated.

**Comment by dbaeumer** [comment]
Strg and Umschalttaste are correct. In German Windows they are translated as well.
