### ISSUE TITLE
Notebook UX - Disable code cell during execution

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#101393]
Testing #101325

I think that we should consider disabling the code cell while it is being executed so that it cannot be edited.

**Comment by claudiaregio** [comment]
@jrieken Could this be resolved by the issue opened here? Seems closely related. https://github.com/microsoft/vscode-python/issues/13634 

The python extension would appreciate if this functionality was left up to the extensions, not default behavior. 

1. Jupyter users are currently used to being able to edit during run (this is a strong learned behavior of theirs) so if there is no visual indicator to show editing has been disabled, they may think something has broken for longer running cells. 

2. Assuming there is a visual indicator, if a user runs all cells/all cells above/all cells below it could lead to a lot of noise in the notebook. You would need a disabled indicator/state + enabled indicator/state so you would have two indicators/states per cell for these cases.

**Comment by greazer** [comment]
To Claudia's point, it's common in jupyter to start a cell running, realize you made a mistake or want to add something, edit the code, then either wait shortly for the cell to finish, or stop the kernel and run again with the new code.

**Comment by roblourens** [comment]
I am for closing this issue and leaving this up to extensions. That's also just what you are suggesting right?

There is a visual indicator that an editor is readonly but it only shows up when you try to type in an editor. An extension could set a cell to readonly during execution if it wanted to do that, and I think it would work out ok. But I don't want to do anything like that by default.
