### ISSUE TITLE
Source- github 

### ISSUE THREAD

**Issue by RaidoNek** [microsoft/vscode#101306]
Issue Type: <b>Bug</b>

Please someone help me i tried to send all files to github , but nothing was sent and all my data is lost, please help

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (6.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
add-reference|adr|1.0.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-solution-explorer|fer|0.3.10
discord-vscode|icr|3.14.0
amxxpawn-language|Kli|0.7.5
csharp|ms-|1.22.1
cpptools|ms-|0.28.3
format-html-in-php|rif|1.6.2
sourcepawn|sel|0.0.4
html-preview-vscode|tht|0.2.5

</details>

**Comment by RaidoNek** [comment]
I really need that files

**Comment by joaomoreno** [comment]
Can you explain exactly where you clicked and what happened? Can you reproduce the issue?

**Comment by RaidoNek** [comment]
Thanks for response, i connected VS code with my github and send my folder to github repository and since this, folder is lost

**Comment by RaidoNek** [comment]
I think my data  is forever lost :(

**Comment by RaidoNek** [comment]
I clicked on Source Control and Publish Branch

**Comment by RaidoNek** [comment]
and all data lost , i hate github from this time

**Comment by joaomoreno** [comment]
Can you find your files somewhere in https://github.com/RaidoNek?

Did you have any backup of your files?

Did the files simply disappear after you published them to GitHub? How exactly did you publish them? Which button did you press?

**Comment by RaidoNek** [comment]
Nothing at my discord, i have backup of some files, but actually 5 months ago... I just logged VS code with github and it idk how just put my folder into this source control and i have clicked to publish branch..  and files disappeared.. folder is still here, but files not.

**Comment by joaomoreno** [comment]
Can you show me a [screen recording](https://gifcap.dev/), by doing the same on another, sample folder?

**Comment by RaidoNek** [comment]
Now i cant even login to github from VS code, thanks for your time i have to pay for data recovery and blocking every interaction with gits. thanks.

**Comment by joaomoreno** [comment]
Sorry but I really can't help if you can't provide additional information. Please let me know if you find out more.
