### ISSUE TITLE
Adopt Typescript 2.0

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#10136]
- [x] adopt TS 2.0 in the VS Code code base
- [x] bundle TS 2.0 with VS Code
- [x] Enable the use of TS 2.0 for extension development. 
- [x] Check that the vscode yeoman generator is up to date with TS 2.0

**Comment by dbaeumer** [comment]
I changed to extension code to make VS Code better work with 2.0 however we still ship with 1.8.10. 2.0.0 is still not RTM.

**Comment by dbaeumer** [comment]
Rest of the work will happen in September.

**Comment by dbaeumer** [comment]
Closing. All work is done.
