### ISSUE TITLE
Use context menu to display actions that do not fit

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#101353]
Testing #100850

Consider using a context menu (`...`) at the end of the line, to surface the actions that do not fit in the view. 

![image](https://user-images.githubusercontent.com/3372902/86106072-69383580-bac0-11ea-8d80-8daab9334685.png)

**Comment by isidorn** [comment]
We rarely do this for our inline actions. However I think this is a fair feature request against our inline actions across the workbench
