### ISSUE TITLE
Notebooks UX - execute cell button style

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#101377]
Testing #101325

Have we considered adding a border, and background color on hover to the `Execute cell` button? 
Right now it seems to be floating around, and I think that having the action buttons with consistent style would help.

**Comment by misolori** [comment]
We wanted the actions on the left side to be distinctly different than the other actions as these are primary actions. Here's what it would look like if they were the same style:

![image](https://user-images.githubusercontent.com/35271042/86156211-73efcc00-baba-11ea-9965-8341f4ab32ee.png)

**Comment by roblourens** [comment]
I don't think those actions should look like they are a toolbar of 1. I think the current styling is better.

**Comment by lszomoru** [comment]
I personally like the style in the screenshot, as the play button is clearly associated with the cell, and nicely aligned with it.
Having said that, I am not a designer and I am still learning about our design system so please feel free to discard :)
