### ISSUE TITLE
Extension recommendations should start earliest in LifecyclePhase.Restored

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101348]
It looks like some recommendations in `ExtensionRecommendationsService` are activated right from the constructor of the service. I am not sure why we would need any recommendation to do work before the workbench has finished loading and suggest to move them all into `LifecyclePhase.Restored` or `LifecyclePhase.Eventually`.

**Comment by bpasero** [comment]
Actually I just checked and today the extension recommendations service seems to be instantiated already after editors restore, so this is probably fine.

**Comment by sandy081** [comment]
Ok, Closing this for now. We will get back to this if it is really an issue.
