### ISSUE TITLE
Cannot copy exception messages (event short text) into clipboard

### ISSUE THREAD

**Issue by CarlosTorrecillas** [Microsoft/vscode#10130]
- VSCode Version: 1.3.1
- OS Version: OS El Capitan

Steps to Reproduce:

1. Create a .NET console app
2. Add the code to throw an exception
3. In the debugging section try to copy the exception message / stacktrace (Copy Value)
4. You get the message "error CS1012: Too many characters in character literal"

**Comment by isidorn** [comment]
This error looks like it is coming from the C# extension, can you please file this bug agains the C# repository here https://github.com/OmniSharp/omnisharp-vscode

Thanks

**Comment by CarlosTorrecillas** [comment]
Thanks, will do!
