### ISSUE TITLE
Integration test failed: renderer process crashed

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#101341]
Not sure if we have logs to help find out why the process crashed.

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=80319&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=8d770de7-1c45-559d-f821-c35376a078ad&l=576

**Comment by deepak1556** [comment]
Yup we have artifacts published that contain crash dumps. The related build log has expired, hence closing.
