### ISSUE TITLE
[Dev question] completionItemProvider triggerChars

### ISSUE THREAD

**Issue by yzhang-gh** [microsoft/vscode#101333]
@jrieken Sorry if it is not a good place for this question but I'm having almost the same question as in #52411.

I registered a `completionItemProvider` for the JS/Python/… file type (only provides completions in string/comment parts).
But the problem is then completions from the JS language server will no longer show up *if I have registered the corresponding `triggerChars`*.

See the comparison below (line 4 demonstrates `myCompletionItemProvider` and line 6 is for the JS language server).

<img src="https://user-images.githubusercontent.com/7588612/86080963-bb7c5500-bac6-11ea-98e6-78e2879fa65b.gif" alt="triggerChars-b" width="451px">

<img src="https://user-images.githubusercontent.com/7588612/86080996-c9ca7100-bac6-11ea-9a13-7a9f68868609.gif" alt="triggerChars-ab" width="451px">

So the questions are:
- Why the completions no longer show up automatically if there is another completion provider claiming the `triggerChars`?
- Can I get rid of `triggerChars` but still be able to get suggestion in the string/comment scope?
  It (no `triggerChars`) works well for Markdown, LaTeX etc. But quick suggestion seems not to be triggered inside string/comment scope of JS/Python etc.

Many thanks.

(https://github.com/yzhang-gh/vscode-dic-completion/blob/b316c6598040edb36277e3c5122939b79b0e09b1/src/completion.ts#L57-L71)

**Comment by jrieken** [comment]
> Why the completions no longer show up automatically if there is another completion provider claiming the triggerChars?

Is your provider actually being invoking and returning results?

Generally, using `abc...` as trigger character does not make sense. This fights the quick-suggest-setting which already triggers completions as you type "normal" word characters. Trigger characters should be characters that typically don't appear in words, like `.`

**Comment by yzhang-gh** [comment]
Thanks for the reply.

> Is your provider actually being invoking and returning results?

Yes. The extension provides common English word completions (e.g. `abandon`, `ability`, `baby`, `background` as in the GIF, line 4) *only in the string/comments scope* (this is done with some naive RegExps).

> Generally, using `abc...` as trigger character does not make sense. **This fights the quick-suggest-setting which already triggers completions as you type "normal" word characters.** Trigger characters should be characters that typically don't appear in words, like `.`

I set the `triggerChars` because I couldn't get quick suggestions in the string/comment scope (i.e. my provider would not be invoked). You remind me that there is a setting `editor.quickSuggestions` which can be set to
```js
{
    "other": true,
    "comments": true,
    "strings": true
}
```

I just tried and now my provider can be invoked without using `abc` as trigger chars 🤩. So my second question (no `triggerChars`) is solved and the first question is not important now. Please feel free to close this.

Just out of curious, how do you check whether the "quick suggestions" is invoked inside strings or comments? based on syntax highlight tokens?

**Comment by jrieken** [comment]
Great this worked for you

> Just out of curious, how do you check whether the "quick suggestions" is invoked inside strings or comments? based on syntax highlight tokens?

There is no good answer. On the UX side we know this based on grammar information but we don't share that info with extensions...
