### ISSUE TITLE
Highlight arrow function parameters

### ISSUE THREAD

**Issue by Bigous** [Microsoft/vscode#1013]
When you are writing in TypeScript, arrow function does not get the parameter names colored. Using anonymous functions you get it colored.

**Comment by alexandrudima** [comment]
@Bigous can you provide the code snippet please.
@dbaeumer this might be an upstream issue in the TypeScript TM grammar

**Comment by Bigous** [comment]
Sure...
This is not colored
```typescript
app.get('/test/', (req, res) => {
});
```
This is colored correctly
```typescript
app.get('/test/', function (req, res) {
});
```
Just like here in github :D

[]s

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#22
