### ISSUE TITLE
Voice Over: 'row 1 collapsed' when expanding

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#10135]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:
1. Enable Voice Over
2. Select a folder in the explorer
3. Collapse/expand the folder node with left/right arrow keys
   -> Voice Over says 'row 1 collapsed' when it is expanded

**Comment by bpasero** [comment]
I verified that we set the correct ARIA roles so this must be an issue with the screen reader not detecting that the row got expanded or collapsed. 

Once I select another element and go back, the expansion state is correctly spoken.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
