### ISSUE TITLE
Failed to run smoke test in dev container

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101361]
Testing #101334

I don't have a linux dev setup so I figured running smoke tests on linux is a good scenario for our own dev container. However, I failed a few times and eventually gave up

1. not enough resources. the readme explains this but not clear enough, e.g you cannot run `yarn run gulp vscode-linux-x64` without tweak the docker settings
1. permission issues, e.g I have seen this 👇 after compiling and bundling for 20minutes
<img width="711" alt="Screenshot 2020-06-30 at 11 06 32" src="https://user-images.githubusercontent.com/1794099/86108681-c2559880-bac3-11ea-906e-6d569287a5e2.png">
1. Unclear failure to run the smoke test (see below)

```
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
node@c79a7052e0e9:/workspaces/vscode$ sudo yarn smoketest --build /workspaces/VSCode-linux-x64/
yarn run v1.22.4
$ cd test/smoke && node test/index.js --build /workspaces/VSCode-linux-x64/
Running desktop smoke tests against /workspaces/VSCode-linux-x64/code-oss


*** Test data: /tmp/t3854OCiwroH4a5kv
*** Preparing smoketest setup...
*** Cloning test project repository...
*** Running yarn...
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
*** Smoketest setup done!

  VSCode Smoke Tests (Electron)
    VSCode Smoke Tests (Electron)
      1) "before all" hook in "VSCode Smoke Tests (Electron)"
      2) "after all" hook in "VSCode Smoke Tests (Electron)"


  0 passing (15s)
  2 failing

  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         "before all" hook in "VSCode Smoke Tests (Electron)":
     Error: connect ENOENT /tmp/tmp-3854Fo4Ftgpn5PwY
      at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

  2) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         "after all" hook in "VSCode Smoke Tests (Electron)":
     TypeError: Cannot read property 'stop' of undefined
      at Context.<anonymous> (out/main.js:267:28)



error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
node@c79a7052e0e9:/workspaces/vscode$ 
```

**Comment by egamma** [comment]
@jrieken did you Open the VS Code repository into Volume?

**Comment by Chuxel** [comment]
Yeah breaking this down:

1. It looks like `sudo` was getting used with some of the commands. This can cause folders that were created to be locked to root rather than the current user in the container. That could cause the permission issue.

2. As Erich mentioned, using the open reop in container option will dramatically speed things up on macOS and Windows (with the Hyper-V engine) and RAM and CPU need to be increased - I can make the guidance there even stronger.

    FWIW - I saw 6 mins for `yarn install` and 8 mins for `yarn run gulp vscode-linux-x64` w/4 cores and 8GB of RAM allocated on a 2015 MBP w/16 GB RAM and Sophos AV running.  Note that compiling native modules during `yarn install` and `yarn gulp` max out CPU at certain points and `yarn gulp` hit ~7.12GB of RAM, so it's undoubtedly getting resource constrained at times.

3. The tests did fail - but it looks to me like some sort of bug in the test code.  I don't know the test code - but I wonder look at the logs if the wrong folder is getting created.  In the log:

    ```
    *** Test data: /tmp/t3854OCiwroH4a5kv
    ```

    And then later...

    ```
    Error: connect ENOENT /tmp/tmp-3854Fo4Ftgpn5PwY
    ```

    Should test data have been added to `/tmp/tmp-3854Fo4Ftgpn5PwY` instead of `/tmp/t3854OCiwroH4a5kv`

**Comment by jrieken** [comment]
> @jrieken did you Open the VS Code repository into Volume?

Nope. Tho, to my understanding that helps with IO. That's a nice boost but the blocker is that 2GB of RAM aren't enough to compile vscode, the compiler will simply crash at one point. 

> It looks like sudo was getting used with some of the commands.

Yeah, I ended up running the build (gulp vscode-linux-x64) with sudo because it failed with permission trouble before. Then I ran the tests as sudo because I was worries about exactly the issues that a normal user cannot access sudo-folders. 

> I don't know the test code - but I wonder looking at the logs if the wrong folder is getting created. In the log:

I don't know the code either but I assume that it works ;-)

**Comment by Chuxel** [comment]
> Nope. Tho, to my understanding that helps with IO. That's a nice boost but the blocker is that 2GB of RAM aren't enough to compile vscode, the compiler will simply crash at one point.

Yeah, totally agree there. Making sure the long build times weren't something else. Can make that much more visible in the READMEs.

> Yeah, I ended up running the build (gulp vscode-linux-x64) with sudo because it failed with permission trouble before. 

Strange, yeah I haven't been able to repro that.

> I don't know the code either but I assume that it works ;-)

Debugging a bit it seems like this other path is the handle for the driver. It seems to get past spawning Code and then fails connecting and gives up after 50 tries. Not sure yet why it's failing when `scripts/code.sh` does not.

**Comment by jrieken** [comment]
> Can make that much more visible in the READMEs.

On top of that, I was thinking to add a message to the build script (independent of dev containers) that checks that there is enough RAM to proceed.

**Comment by Chuxel** [comment]
@jrieken Good idea.  I also found the problem.  Chrome sandboxing doesn't work in containers.  So, the test needs to have `--no-sandbox` passed in. After that it works though there's 4 failed tests (unknown if this is something container related).

```text
  24 passing (3m)
  4 failing
```

Here's the update.  In `test/automation/src/code.ts`:
```
	const args = [
		options.workspacePath,
		'--skip-release-notes',
		'--disable-telemetry',
		'--no-cached-data',
		'--disable-updates',
		'--disable-crash-reporter',
		`--extensions-dir=${options.extensionsPath}`,
		`--user-data-dir=${options.userDataDir}`,
		`--disable-restore-windows`,
		'--driver', handle,
                '--no-sandbox'
	];
```

**Comment by Chuxel** [comment]
Even better, it looks like the problem is the default `seccomp` settings.  This appears to resolve it in `devcontainer.json`:

```json
	"runArgs": [
		"--init",
		"--security-opt", "seccomp=unconfined"
	],
```

I think you do have to chown `/workspaces/VSCode-linux-x64/chrome-sandbox` to root and set permissions like you would normally in Linux.

I'll play a bit more, but it took a while to figure out since the error was hidden. Now it's just a question of what the best solution is.
