### ISSUE TITLE
Test: yeoman generator for notebook

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#101319]
Refs: #101056

- [x] anyOS @weinand 
- [x] anyOS @alexdima

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23101319%0A%0A)

---

_Note: the starter was tested last endgame, this is sanity checking the generator code_

1. Grab the latest `npm install -g yo generator-code`
2. Run `INCLUDE_PROPOSED=1 yo code` and select the notebook starter
3. Fill out options. Check that it generates sane, runnable code for you.

If you use the test provider, you'll be able to see a sample notebook by creating an empty file with your chosen file extension (e.g. `foo.my-cool-notebook`).

**Comment by lszomoru** [comment]
@connor4312 is this supposed to work on Windows? I don't see the `notebook starter`.

**Comment by connor4312** [comment]
@aeschli can you publish generator-code?

For running the test in the interim you can `npm link` the repo locally.

**Comment by aeschli** [comment]
Published generator-code@1.2.17

**Comment by weinand** [comment]
The correct name of the generator is "Notebook Renderer" not "notebook starter".
