### ISSUE TITLE
Notebook UX - Black horizontal line at the bottom

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#101392]
Testing #101325

I have put some dummy text in a code cell, executed it and noticed that there is a small black border at the bottom of the cell.

![image](https://user-images.githubusercontent.com/3372902/86123328-904f3100-bad9-11ea-95a8-53c470b1a487.png)

**Comment by rebornix** [comment]
/duplicate 

not seeing this issue for a while so close it but we can reopen whenever you see it again.
