### ISSUE TITLE
"Go" > "Switch Group" > "Side Group" should be labelled "Center Group"

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#10131]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:49:32.489Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

![image](https://cloud.githubusercontent.com/assets/2193314/17411942/0dd0399a-5a2f-11e6-953f-e65d82a1eb27.png)

**Comment by bpasero** [comment]
If you have 2 groups open, there is no center group. Hence we call it side group.

**Comment by Tyriar** [comment]
But it's called side group even when there are 3 groups open. When this is the case only the left and right are "side groups".

**Comment by bpasero** [comment]
Good catch 👍
