### ISSUE TITLE
Windows no longer respond

### ISSUE THREAD

**Issue by lsh499742959** [microsoft/vscode#101327]
Recently, vsCode has been running projects for a while with the prompt, "Windows are no longer responding, you can reopen or close, or wait."The operation continues to wait or reopens.Most of the time you just restart the computer and it works.But rebooting the computer every once in a while still doesn't work

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
