### ISSUE TITLE
Notebook editor: collapsed state of sections not preserved

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101356]
Testing #100965

1. Open my-work.github-issues
2. Collapse section `Bugs, Debt, Features...`
3. Split editor to right
4. The collapse state of sections is not preserved

Even though some other UI state is preserved, like an output mime type

**Comment by rebornix** [comment]
We didn't share the view states of Folding between editors now but I found that text editors do share that.

**Comment by jrieken** [comment]
The editor "inherits" the collapse/expand state of an existing editor but they aren't sync'ed, e.g when you collapse in one editor it doesn't reflect in another existing editor. It's only the initial state and I will look into doing the same
