### ISSUE TITLE
Notebook: clicking into breadcrumb does not work

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101369]
Testing #100965

Steps to Reproduce:

1. click into a notebook
2. click into breadcrumb

=> 🐛 dropdown opens and closes immediately

![recording (6)](https://user-images.githubusercontent.com/900690/86110398-cd112d00-bac5-11ea-8c1d-06418c4bde33.gif)

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/101181

must be a recent regression...
