### ISSUE TITLE
Reopen Editor With... shows empty editor

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#101360]
Testing #101295

- Create Untitled notebook.
- Add some content.
- Use `Reopen Editor With...` from the editor's overflow menu.
- Pick Text Editor
- Shows empty Text Editor

![image](https://user-images.githubusercontent.com/9205389/86108515-89b5bf00-bac3-11ea-9c1f-ad73fa1df402.png)

Switching back to the notebook editor again shows the content entered.

**Comment by rebornix** [comment]
Good point and it's an interesting issue. The reason I put it `as-designed` for now is that's how the design works now: when an untitled notebook is opened, we ask the extension to provide the template data (`vscode.NotebookData`) and the extension will be responsible for saving the data to disk later on (so it handles the serialization). When we switch to text editor directly from the untitled notebook, we don't know how to serialize it, thus we show an empty untitled text file.

**Comment by chrmarti** [comment]
Maybe ask to user to save first?

**Comment by rebornix** [comment]
@chrmarti good point, thanks!

**Comment by bpasero** [comment]
Adding Logan, I think there are similar issues for custom editors (Hex) too, maybe needs a unified solution. As discussed, maybe a pragmatic fix is to tell the user to save first via a dialog.

**Comment by lramos15** [comment]
Closing this with the same fix as #124356. We disallow this action.
