### ISSUE TITLE
Weird Menu Bar Flasing on MATE.

### ISSUE THREAD

**Issue by alexacallmebaka** [microsoft/vscode#101314]
I am having a weird bug specifically with MATE and VS Code. Whenever I use the menu bar in VS code, each "sub menu" flashes bright white before returning to my dark theme. This is only happening with VS code. [Here](https://www.reddit.com/r/mate/comments/hht1zo/super_weird_bug_in_mate_with_vs_code/?utm_source=share&utm_medium=web2x) is a link to my Reddit post with a video that showcases the bug. This issue is not specific to the theme I am using. I am running i3WM on top of MATE. 

- VSCode Version: 1.46.1
- OS Version:  Debian GNU/Linux 10 (buster)

Steps to Reproduce:

1. Download VS code onto a system which mimics this one. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexacallmebaka** [comment]
This error also occurs on Fedora 32, but the error is not present on Manjaro Linux (Both running i3wm on top of Mate using Compton). There is also a report of this occurring on GNOME.

**Comment by deepak1556** [comment]
Does it continue to happen when you have `"window.titleBarStyle": "custom"` ?

**Comment by alexacallmebaka** [comment]
It does not! Thank you for the information!

**Comment by deepak1556** [comment]
merging this to https://github.com/microsoft/vscode/issues/80798
