### ISSUE TITLE
VS Codespaces & GitHub Codespaces - No code colourisation for .cs files. 

### ISSUE THREAD

**Issue by dingjimmy** [microsoft/vscode#101317]
Writing c# code in vs codspaces using Microsoft Edge browser on iPadOS 13.5.1. 

1. Create a new code space (Linux 4 core) 
2. Install C# extension
3. From terminal type `dotnet new console`
4. Observe new console project being created and omnisharp server starting.
5. Once project is created, open `program.cs`
6. Expect to see boilerplate hello world console code with colourisation. However all text is shown in default grey. 

![FE82BB9A-4491-44E8-A907-E9B0ED6042C2](https://user-images.githubusercontent.com/1486412/86058203-6a357c80-ba58-11ea-95ec-f0f8675cdcb0.jpeg)

Also occurs on Firefox for iPad.

Does not occur when using Edge (chromium) or Firefox on windows 10.

**Comment by alexr00** [comment]
@dingjimmy was there any case you found where this occurred on either Windows or linux (I don't have an ipad to test on, but can figure something out if needed) ?

**Comment by dingjimmy** [comment]
No, no other cases. Tried it using: 

- Firefox 77 on Windows 10 (1909) 
- Edge 83 on Windows 10 (1909) 
- Firefox 73 on Ubuntu 18.04.4 LTS

**Comment by alexr00** [comment]
@dingjimmy thanks for the additional information!

**Comment by bpasero** [comment]
@dingjimmy can you still reproduce? I tried and cannot.

**Comment by dingjimmy** [comment]
Ok, so good news is it seems to be fixed in visual studio codespaces 😀, But is broken still in GitHub codespaces 😟 .

**Comment by dingjimmy** [comment]
Those screenshots were taken using latest Firefox for iPad 28.2, on iPad OS 14.1

**Comment by bpasero** [comment]
@dingjimmy I tried Edge on iPadOS with Codespaces, does it make a difference?

**Comment by dingjimmy** [comment]
Ok, this is weird. Just gone into GitHub codespaces in Edge, and all looks good. 

Then went back to Firefox to compare and it now looks good.

**Comment by dingjimmy** [comment]
Do you think the c# extension wasn’t loading correctly?

**Comment by bpasero** [comment]
@dingjimmy maybe browser cache issue?

**Comment by dingjimmy** [comment]
I’ve never used GitHub codespaces before today, so would assume everything was downloaded fresh from server.

**Comment by dingjimmy** [comment]
Am interested in what fixed this. Checked in about a few months ago and could still replicate the issue in VS Codespaces.

**Comment by bpasero** [comment]
Ok I suggest we close this for now until we see it again.
