### ISSUE TITLE
No view menu for panels

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101382]
Testing #100848

* move a view into a panel, e.g timeline into terminal container
* 😕 there is no view menu only the context menu...

**Comment by sbatten** [comment]
@isidorn did you have plans to port the view menu to the panel as well?

**Comment by isidorn** [comment]
Yeah we plan to do it in the future. So let's assign to me and we can tackle it in the future - for now assignig to August, since in July i am out.
