### ISSUE TITLE
Editor drop feedback for notebooks does not work when hovering over cells

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101379]
Refs: #100965

1. Drag an editor group
2. Drop feedback is not there when dragging over notebook cell 🐛 

The issue here is that notebooks can contain a lot of cells and then this makes it really hard to drag and drop editors around to set up your layout.

**Comment by roblourens** [comment]
Works fine for me. Has been fixed in the past. Can you explain some more or include a gif?

**Comment by isidorn** [comment]
Works now. I have no clue why it was not working yesterday. If I see it again I will try to get steps.
For now closing.
