### ISSUE TITLE
Notebooks UX - action buttons hover background

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#101374]
Testing #101325

Notebook cells have a background color on hover, the language selector button has a background color on hover but the action buttons do not have a background color on hover. I think we should be consistent and provide a background color on hover for the action buttons.

**Comment by misolori** [comment]
See https://github.com/microsoft/vscode/issues/101371#issuecomment-651919422, since we follow the status bar model we didn't intend on providing a bg color for the button. We could add one for the status bar.

**Comment by roblourens** [comment]
The status bar has one, I agree that the toolbar shouldn't, matching other toolbars.
