### ISSUE TITLE
Show process id in the callstack view

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#101355]
Testing #100850

Looking at the before and after screenshots I see that in the compressed callstack view we are not showing the process id any more. Did we explicitly remove this information? I think that it would still be valuable to show the process id in the compressed callstack view.

**Comment by isidorn** [comment]
Yeah we explicitly remove this information. Also assigning @connor4312 as he should decide what is best here.
Also the js-debug extension could update the session name if it wanted to.

I personally think the process id should not be part of the name as it is too prominent.
What we could do on the vscode side: make sure the name of child sessions are shown on hover. So the hover over the session would provide all the older information, including the process id.

Let me know what you think

**Comment by lszomoru** [comment]
Given that you are debugging a process I do not feel that the id is too prominent in the name.  

By showing the information when you hover over, do you mean in a tooltip? Would I be able to copy/paste the process id?

**Comment by isidorn** [comment]
@lszomoru yeah I mean in the tooltip. You can always click in the tooltip to select stuff, so yeah you could copy/paste it.

**Comment by connor4312** [comment]
Showing it in the tooltip makes sense. Last I checked the tooltip for all debug sessions is just "Session", I think we should instead show session name (incl in compressed sessions)

**Comment by isidorn** [comment]
I think this makes sense, and I can look into it today.

**Comment by isidorn** [comment]
Fixed via changes to https://github.com/microsoft/vscode/issues/101429#issuecomment-652908112
So by default we show the child session which has the process id
