### ISSUE TITLE
希望vscode可以兼容import导入的方法使用ctrl+鼠标左键的方式来进行查看

### ISSUE THREAD

**Issue by DeanNode** [microsoft/vscode#101347]
在vue当中经常会出现 export function barChart 这样导出的方法，然后在使用的vue模版当中，使用import { barChart } from "@/utils/bill.js"; 引入对应的方法，然而这样的方法没法直接通过ctrl+鼠标左键的方式进行跳转到定义实现的地方去。

**Comment by iigmir** [comment]
---
Translate:

Feature request: Improve the compatibility of import that can check the file with Ctrl+Left mouse.

In VueJS, it's common to use the export syntax in a module: `export function barChart`. When using the very same module in a Vue's component file, we will import syntax something like this: `import { barChart } from "@/utils/bill.js";`. In VSCode, however, can not navigate to the module file.

---

Well, as a VueJS developer, I can say that VSCode _supports_ this feature, but only when using **relative** file syntax. That said, you'll need to use the syntax like this:

```vue
import { barChart } from "../../utils/bill.js";

export default {
    computed: { barChart }
};
```

**Comment by iigmir** [comment]
See also:  #100262 and [the issue on PathIntellisense](https://github.com/ChristianKohler/PathIntellisense/issues/162).

**Comment by JacksonKearl** [comment]
I believe this issue should be filed against the vue extension, https://github.com/vuejs/vetur. Let me know if I've missed something. Closing for now.
