### ISSUE TITLE
editor.semanticHighlighting.enabled not offered in package.json code completion

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101385]
Refs: #101316

1. Use the semantic coloring extension, open package.json
2. Have the following entry
```
"[semanticLanguage]": {
		
	}
```
3. `editor.semanticHighlighting.enabled` is not suggested by code completion

**Comment by aeschli** [comment]
The entry needs to be
```
		"configurationDefaults": {
			"[semanticLanguage]": {
				"editor.semanticHighlighting.enabled": 
			}
		}
```

Works for me:
![image](https://user-images.githubusercontent.com/6461412/86231070-3fe7da00-bb92-11ea-9797-656c3b440f47.png)

**Comment by isidorn** [comment]
Ok, works when under `configuartionDefaults`. That was not clear to me. Will re-test the item now due to this confusion on my end.
