### ISSUE TITLE
Test: webview debugging

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#101320]
Refs: #96626

- [x] anyOS @eamodio 
- [x] anyOS @alexdima

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23101320%0A%0A)

---

We can now debug webviews native in VS Code, such as those created in custom editors and notebook renderers. Test this!

If you have a notebook renderer or webview editor already, you can use that. Otherwise, you can use a sample project / [the yeoman generator for notebooks](https://github.com/microsoft/vscode/issues/101319).

1. Make sure you're on the latest Insiders build
2. Make sure you're using js-debug nightly https://github.com/microsoft/vscode-js-debug#nightly-extension
3. Add `"webview.experimental.useIframes": true`, to your user configuration. (Workspace configuration only will not work!)
4. Add debugWebviews: true to your `extensionHost` launch config.
    - By default this will attach to all webviews, to narrow this you can instead specify an object like `{ "urlFilter": "*yourExtensionId*" }` for custom editors or `{ "urlFilter": "*notebookRenderer*" }` for notebook renderers
    - This object is a subset of the normal chrome launch config. If you need to set up webroots, source map overrides, etc. you can do that in here.
5. F5 and it should 'just work' :sparkles:

Note: iframe webviews are experimental (https://github.com/microsoft/vscode/issues/83188). If you have issues with the webview itself/when not in debug mode, please report those to Matt. Also, with iframes, "open webview developer tools" will no-op, instead you can open the normal developer tools and look at iframes there.

**Comment by connor4312** [comment]
Please ensure electron is bumped to 7.3.2 prior to testing

**Comment by alexdima** [comment]
Very cool!! This just works  ✨ ✨ ✨

**Comment by eamodio** [comment]
This is so awesome! Works great! This will make debugging webview so much less painful.
