### ISSUE TITLE
Test: Allow to enable semantic highlighting for a language

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#101316]
Refs: #101292

- [x] anyOS @isidorn 

Complexity: 2

---
Verify:
- check out the semantic highlight sample: https://github.com/microsoft/vscode-extension-samples/blob/master/semantic-tokens-sample
- add the following to the package.json
```
     "[semanticLanguage]": {
        "editor.semanticHighlighting.enabled": true
      }
```
- run the extension, open the `sample/sample.semanticLanguage` from the sample repo
- verify with the `Developer: Inspect Editor Tokens and Scopes` that semantic highlighting is available for all themes, built-in and custom
- set 
```
"editor.semanticTokenColorCustomizations": {
	"enabled": false; // disable for all themes
}
```
- verify that semantic highlighting is still available

**Comment by isidorn** [comment]
Works well.
