### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by sachinsharma10** [microsoft/vscode#101343]
Issue Type: <b>Performance Issue</b>

on each restart of VS Code i am facing  this issue "Extension host terminated unexpectedly". do you have any solution?

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    77	 21768	code main
    0	   120	  3308	   gpu-process
    0	    25	 11040	   utility
    0	    72	 12160	   shared-process
    2	    65	 13024	   window (Issue Reporter)
    0	   154	 23100	   window (index.component.html - src - Visual Studio Code [Unsupported])
    0	     5	  8420	     console-window-host (Windows internal process)
    0	    67	  9996	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    11	 24904	     watcherService 
    0	    11	 11432	       console-window-host (Windows internal process)
    0	    14	 26428	   electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.component.html - src - Visual Studio Code [Unsupported])
|    Folder (src): 222 files
|      File types: ts(68) scss(32) html(29) jpg(16) css(9) png(9) svg(3)
|                  ico(2) gitkeep(1) eot(1)
|      Conf files: tsconfig.json(1);
```

</details>
Extensions: none

**Comment by alexdima** [comment]
@sachinsharma10
The title of VS Code is: `Window (index.component.html - src - Visual Studio Code [Unsupported])`. Please note the `[Unsupported]` part in the title.

This indicates that the files of VS Code have been altered on disk. i.e. your VS Code installation is corrupt. Can you please try to reinstall VS Code? You can try the zip version or the Insiders variant.
