### ISSUE TITLE
Notebooks: have a lot of unneeded margins/paddings?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101366]
Testing #100965

![image](https://user-images.githubusercontent.com/900690/86110058-5ffd9780-bac5-11ea-825e-81c0db9508f0.png)

I find this could be more condense.

**Comment by misolori** [comment]
This was intentional, previously code cells and markdown cells were on the same vertical plane and it was hard to tell which cells were code vs markdown (especially when edited a markdown cell). So we decided to indent code cells to give better hierarchy.

We could tighten the left margin by a few pixels (~8px) but we'd still need to keep the code cells indented.

**Comment by roblourens** [comment]
@bpasero are you thinking about horizontal padding or vertical padding or both?

**Comment by bpasero** [comment]
Both horizontal and vertical padding! Maybe have a setting where I can decide if I want the condense view or not. 

Now that I look at my screenshot from https://github.com/microsoft/vscode/issues/101366#issue-648023018 again, it really feels like there is a bug in notebook that prevents some data to be shown.

**Comment by misolori** [comment]
I've updated the overall padding/margin around the cells, between the cells, and inside the editors:

![Frame 6](https://user-images.githubusercontent.com/35271042/86410637-fc639d80-bc6f-11ea-9705-e9e9551429f4.png)

I also created https://github.com/microsoft/vscode/issues/101635 to propose to hide the status bar until needed, and https://github.com/microsoft/vscode/issues/101633 to explore a more compact bottom toolbar which will reduce more space. 

Let me know if this looks good for you and we can close out this issue.

**Comment by bpasero** [comment]
It is better, thanks for reducing it. I still think there is lots of whitespace, e.g. here:

![image](https://user-images.githubusercontent.com/900690/86434151-fa93eb80-bcfc-11ea-922a-f3a313e592da.png)

The line around `Config: defines the inbox query` being in small font having almost 5x the line height as surrounding whitespace.

**Comment by bpasero** [comment]
@rebornix @misolori is there any way I can see how this used to look in 1.46? How can I run an older notebook UX currently, if possible?

**Comment by roblourens** [comment]
You can see it in stable, starting with `--enable-proposed-api` for whichever extension

**Comment by bpasero** [comment]
@roblourens this results in: 

```
Unable to open 'inbox.github-issues': Cannot read property 'backupId' of undefined.
```

**Comment by roblourens** [comment]
Oh, I guess you would have to use an older build of the extension. It works for the markdown notebook.

**Comment by bpasero** [comment]
Thanks that works 👍

**Comment by rebornix** [comment]
The editor inner left padding issue is extracted to https://github.com/microsoft/vscode/issues/101808 .

**Comment by misolori** [comment]
I think we've addressed a lot of these issues, below is a comparison from June => July:

![image](https://user-images.githubusercontent.com/35271042/88339195-770f5e00-ccee-11ea-8629-bab47ae8ca9b.png)

Let us know if you think it's better.

**Comment by isidorn** [comment]
I see there are improvments, adding verified and Ben can open more issues once he is back if this did not capture everything he pointed out.
