### ISSUE TITLE
React TypeScript minor color issue

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10138]
- VSCode Version: 1.4.0-insiders
- OS Version: OSX

Steps to Reproduce:

![image](https://cloud.githubusercontent.com/assets/1723815/17415965/1779a884-5a5a-11e6-818e-2655983faf15.png)

Notice how text `test` has different color in first `div`

**Comment by jasonwilliams200OK** [comment]
For minimal steps to repro., paste:

```tsx
var a = (
    <a>
        <b c=''>test1</b>
        <b c=''>test2</b>
        <b c=''>test3</b>
    </a>
);
```

in a new document and save as `color-test.tsx`.

* `test2` and `test3` have wrong foreground color. `test1` has the correct one.
* Removing attribute part `c=''` from line 4 and 5 corrects the color.

**Comment by wallverb** [comment]
Gets even more interesting in this case:
![image](https://cloud.githubusercontent.com/assets/1723815/17420401/65433eac-5a70-11e6-8eda-654a28b73932.png)

3 different colors

**Comment by aeschli** [comment]
#3008 is the cause of this bug.
