### ISSUE TITLE
Error after DND cells

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#101326]
- Drag a cell, drop it somewhere
- Error in console:  `ListError [NotebookCellList] Invalid index -1`

@rebornix we now create a new cell VM when dropping a cell, and this fails when I try to focus the previous cell VM. I think it didn't do that before. Is that expected?

**Comment by rebornix** [comment]
@roblourens did you still see this issue after the commit you pushed (which is a good fix btw)?

**Comment by roblourens** [comment]
No, but I still have a `focusNotebookCell` call after I move the cell, which isn't doing anything since the previous cell VM does not exist anymore. And I am not sure whether the moved cell is guaranteed to still be focused, or whether I need to do something else to find the new cell and focus it.

**Comment by rebornix** [comment]
> And I am not sure whether the moved cell is guaranteed to still be focused

if you are using the `MoveCell` API it should as we are focusing cells based on handle, which won't change as the new view model is using the same text model.

We may want to polish the API as right now it's not clear how `MoveCell` handles the selections change, especially with Undo/Redo. Recommend to look into this in debt week.

**Comment by roblourens** [comment]
Yeah I am using moveCell. It looks like we do create a new cell vm with the same text model. I'll just delete the line that tries to focus with the old vm

https://github.com/microsoft/vscode/blob/43a10264cd81af821c81589b044e2b8146f6465b/src/vs/workbench/contrib/notebook/common/model/notebookTextModel.ts#L548-L551

**Comment by roblourens** [comment]
Also it loses the edit state when dragging now, which isn't a big deal, not sure how I would fix that.

**Comment by mjbvz** [comment]
To verify, I tried dragging and dropping a bunch of cells around. Did not see any errors but let me know if there are more specific verification steps
