### ISSUE TITLE
this extension is enabled globally 

### ISSUE THREAD

**Issue by salaredward11** [microsoft/vscode#101389]
Issue Type: <b>Feature Request</b>

im trying to install dart but i cant plz send me steps how to fix this keep showing this extension is enabled globally  

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

**Comment by teguhablazed** [comment]
im trying to install python but its keep showing "this extension is enabled globally" please send me steps how to fix ??
