### ISSUE TITLE
Settings object editor: Ok button feels unecessary

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#101358]
Testing #101329

- Follow the setup ('Test with the dummy extension') from https://github.com/microsoft/vscode/issues/101329
- open the `static object` setting, press the edit control and make a change
- go to the settings JSON representation and realize there's no change, I forgot to press the OK button

As the settings UI typically applies changes right when modifying, it feels to me there should be no OK button, but the changes should be applied on edit.

Also the modify button could maybe be unnecessary. When selecting an entry, why not go into edit mode right away?

**Comment by 9at8** [comment]
@aeschli I'm leaving this open for now to discuss in next week's UX call

**Comment by roblourens** [comment]
It's slightly inconsistent but I think it makes more sense for this complex control type.
