### ISSUE TITLE
Notebooks UX - language selector button

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#101371]
Testing #101325

I always felt that the language selector button is out of place in the lower right corner. All action buttons are in a border while the language selector is just floating in the cell. Have we considered putting it in a border in the lower right hand corner? Have we considered putting the language selector in the upper right hand corner with the other buttons? Maybe separate them with a bar?

**Comment by misolori** [comment]
We actually followed the status bar model here where each item has a hover bg and is an action. Since we don't believe users will interact with this button too often we didn't want to place it with the other actions as that tends to get too busy. So we thought of having it in the bottom right, just like a regular language selector, was more appropriate and consistent.

**Comment by roblourens** [comment]
Do you think a subtle border between the status bar and the cell editor would help with the "floating" feeling @lszomoru?

**Comment by lszomoru** [comment]
Yes, if the idea is that each cell has a "status bar" and that button is part of it, we should visually separate the cell from the status bar. I also think that it might be a waste of space to have each cell have a status bar, especially if we only have this one button in it, and we expect people not to interact with it too often. Might be better than to move it up with the other actions.

**Comment by roblourens** [comment]
It also has the cell execution status (checkmark, error indicator, progress indicator, and duration)

**Comment by misolori** [comment]
We use to have a border but there were too many lines that made it feel busy:

![image](https://user-images.githubusercontent.com/35271042/86169821-13b75500-bacf-11ea-88b0-29992e45adcb.png)

**Comment by lszomoru** [comment]
That does seem busy indeed but it is an edge case where the cell only has one line of code/text.

**Comment by misolori** [comment]
I don't think a single line cell is an edge case, at least in all of the VS Code notebooks most cells are this way. I'm still not convinced of a better alternate though.

**Comment by misolori** [comment]
Given that this issue is a bit older and we haven't seen similar feedback, I'm going to close this one out.
