### ISSUE TITLE
Notebook UX - Add Code/Markdown buttons overlap with cell

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#101380]
Testing #101325

* Add a markdown cell to a GitHub issues notebook
* Click outside the newly added markdown cell (clicked on the next markdown cell)
* Moving the mouse in between the two cells reveals the Add Code, Add Markdown buttons
  * Buttons overlap the the cell
  * Tooltip seems to be wrong

![image](https://user-images.githubusercontent.com/3372902/86112001-b966c600-bac7-11ea-87ed-6289fe0084f6.png)

**Comment by rebornix** [comment]
The cell height is not updated correctly the very first time when it goes into edit mode.
