### ISSUE TITLE
Function getTreeItem (interface TreeDataProvider) -> return value 'undefined' is also valid

### ISSUE THREAD

**Issue by rwnkl** [microsoft/vscode#101387]
- VSCode Version: 1.46.1
- OS Version:

Does this issue occur when all extensions are disabled?: Yes

If the getTreeItem (interface TreeDataProvider) function returns 'undefined', the window.createTreeView function generates a correct TreeView. That makes sense. Please complete the file vscode.d.ts and the documentation.

**Comment by rwnkl** [comment]
For the element: T for which get TreeItem returns 'undefined', the getChildren function must return an empty array T [] or maybe 'undefined'.

**Comment by alexr00** [comment]
The contract of the API is such that you can simply not include the element you with to return undefined for in `getChildren`. No need to return `undefined` from `getTreeItem`, instead, just make sure you don't include that element when you return children.
