### ISSUE TITLE
Test: Azure Account extension SDK upgrade

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#101315]
Refs: https://github.com/microsoft/vscode-azure-account/issues/140

- [ ] macOS @btholt
- [x] linux @lramos15
- [x] windows @fiveisprime

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23101315%0A%0A)

---

**Setup**

The changes for the extension have not yet been published. To test, download this file and change the extension from ".zip" to ".vsix" and run the `Extensions: Install from VSIX` command to install the extension.
[azure-account-0.8.12.zip](https://github.com/microsoft/vscode/files/4847681/azure-account-0.8.12.zip)

**Test**

There are two sets of Azure SDK packages for javascript: https://github.com/Azure/azure-sdk-for-node and https://github.com/azure/azure-sdk-for-js. The first one of these is being deprecated soon, so the Azure Account extension has been updated to use the new packages internally. First, please test that existing functionality continues to work, i.e. you can run the `Sign In` command, `Select Subscriptions`, `Cloud Console`, and Azure extensions that depend on the account extension (such as Docker or Azure Functions) behave as normal.

The account extension exposes a credentials object in its API for other extensions to use. It should now expose two different objects, `credentials`, which is the old object that works for `azure-sdk-for-node`, and `credentials2`, which works with `azure-sdk-for-js`. Please test that you are able to use `credentials2` with the new SDK in an extension.

Example of getting the creds:
```ts
export async function activate(context: vscode.ExtensionContext) {
	context.subscriptions.push(vscode.commands.registerCommand('extension.helloworld', async () => {
		const accountAPI = vscode.extensions.getExtension('ms-vscode.azure-account')!.exports;
		if (accountAPI) {
			const session = accountAPI.sessions[0];
			if (session) {
				const creds = session.credentials2;
				console.log(creds);
			}
		}
	}));
}

```

**Comment by fiveisprime** [comment]
Works great! 🙌 🎉
