### ISSUE TITLE
Semantic highlighiting disabled for a language does not work

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101381]
Refs: #101316

in my test semantic extension `package.json` I set
```
"[semanticLanguage]": {
		"editor.semanticHighlighting.enabled": false
	}
```

I see semantic highlighting still enabled, when I inspect elements:

I think the "semanticLanguage" setting should have the final say in this.

![Screenshot 2020-06-30 at 11 45 11](https://user-images.githubusercontent.com/1926584/86112537-62adbc00-bac8-11ea-9ba7-11a1af36e8fc.png)

**Comment by isidorn** [comment]
This works fine. I was wrongly putting the [sematnicLangauge] not inside the configarationDefaults.

**Comment by aeschli** [comment]
Thanks, my fault, the test item didn't show that.
I also tested it and it all looks fine.
