### ISSUE TITLE
TerminalLink endIndex should be inclusive (and it should say that in the documentation)

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#101394]
Testing #101300

The end position of a range used for a `DocumentLink` appears to be inclusive. I would expect the `endIndex` of a `TerminalLink` to behave the same way. Same code to calculate end position results in different range being used:

![image](https://user-images.githubusercontent.com/38270282/86124196-030cdc00-badb-11ea-8686-c5e6c0fc3ac0.png)

**Comment by Tyriar** [comment]
`InputBoxOptions.valueSelection` uses exclusive end index, so does `String.prototype.substring`. Opinions @jrieken?

**Comment by jrieken** [comment]
Yeah, given these are two indexes into a "flat" string I'd stick with substring and valueSelection logic. I see the inconsistency, we can argue that one is ranges with position objects and the other is offsets...

**Comment by alexr00** [comment]
How often do you expect people to want to share code between a document link provider and a terminal link provider? The inconsistency is annoying in that case because you have to have an extra +1 or -1 somewhere, and that feels broken.

**Comment by Tyriar** [comment]
Decided not to do this https://github.com/microsoft/vscode/issues/91290#issuecomment-658271823
