### ISSUE TITLE
Notebook UX - Code cell behavior during drag'n'drop

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#101397]
Testing #101325

* Open the `my-work.github-issues` notebook and scroll down to the bottom
* Collapse/Expand the `Not Actionable` Markdown cell. When doing so the Code cell is hidden/shown which makes me believe that this Code cell is a child of the Markdown cell. 
* While the `Not Actionable` Markdown cell is expanded, grab it and drag'n'drop it just above the `Feature Requests` Markdown cell.
  * The document is scrolled back to the top
  * The `Not Actionable` Markdown cell is placed above the `Feature Requests` Markdown cell
  * The Code cell does not move together with the `Not Actionable` Markdown cell even though they seem to be related.

**Comment by roblourens** [comment]
This has been changed
