### ISSUE TITLE
Editing object settings: Only limit entries when `additionalProperties: false` is defined

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#101354]
Testing #101329

- Follow the setup ('Test with the dummy extension') from https://github.com/microsoft/vscode/issues/101329
- open the `static object` setting. Note that you can only add `aString`, `anEnum` and aBoolean`.

But looking ate the [configuration schema](https://github.com/9at8/vscode-99635-test/blob/master/package.json#L25), it does not forbid additional properties.

So maybe there should be an extra `additionalProperties: false` in the schema and the schema editor should check for it.

**Comment by roblourens** [comment]
I can only add additional items after adding all the known items. But I think that is a known limitation
