### ISSUE TITLE
Pause on breakpoint badge should use text ellipsis

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#101352]
Testing #100850

Badge should use text ellipsis `...` when there is not enough room to display the full message:

![image](https://user-images.githubusercontent.com/3372902/86105413-959f8200-babf-11ea-8f94-57d22898de7f.png)

**Comment by isidorn** [comment]
Good catch. Yes, we should improve this.

**Comment by isidorn** [comment]
Not for endgame since we always behaved like this. Moving out of milestone and opening up for PRs.
