### ISSUE TITLE
API access to clipboard

### ISSUE THREAD

**Issue by vegerot** [microsoft/vscode#101309]
Extends #4972

It's been a few years, and I'm wondering if any progress has been made on this.  VSCode already offers the ability to copy to the clipboard by highlighting text and pressing `Command + C`.  Are there any plans to open this up to developers?

Reading through the comments on #4972 there seemed to be tons of support for such an idea

**Comment by usernamehw** [comment]
https://code.visualstudio.com/api/references/vscode-api#Clipboard
