### ISSUE TITLE
Terminal Orientation

### ISSUE THREAD

**Issue by bnkalya1502** [microsoft/vscode#101390]
Issue Type: <b>Feature Request</b>

It would be great if the terminal's orientation can be changed to vertical instead of horizontal . This is because it is quite time consuming to review all of the code when the terminal is also open .

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
Maybe try the `View: Move Panel Right` command. If you don't like the result, use `View: Move Panel to Bottom`

**Comment by Tyriar** [comment]
Along the same lines, we are investing in a more flexible workbench which will eventually likely allow you to split the terminal in both directions regardless of where it is.
