### ISSUE TITLE
Test: Smoke Test

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#101334]
- [x] Windows @stevencl
- [x] macOS @Tyriar 
- [x] Linux @jrieken
- [x] Web (Chromium, anyOS) @9at8

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23101334%0A%0A)

---

**NOTE:** Desktop & Web tests MUST run with `--build` argument

**NOTE:** Desktop tests MUST run with `--stable-build` argument additionally

Documentation: https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md#run.

If the automated tests fail, create and issue for that and run the tests manually: https://github.com/microsoft/vscode/wiki/Smoke-Test

**Comment by jrieken** [comment]
done. no linux dev setup so I ran them manually
