### ISSUE TITLE
Webview sometimes hitting invalid token error on focus

### ISSUE THREAD

**Issue by jimcottrell** [microsoft/vscode#101321]
Version: 1.47.0-insider
Commit: 7923112cdd20575406ec547b55a99c289dd7d7e2
Date: 2020-06-29T05:43:37.799Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.5.0

I originally brought this up in #98746 as seeming related. I've only seen it happen through the Git Graph extension, but the author had investigated in https://github.com/mhutchie/vscode-git-graph/issues/301 and felt that this was a bug in VS Code. I should note that as of a month or two ago, I can trigger this every time from a certain repo, but others do not expose this behavior. So it's possible that's it's something about the extension itself, but mhutchie's investigation seemed thorough. Wherever the issue resides, it seems likely to be a rare confluence of events that I'm just lucky enough to experience.

Steps to Reproduce:

1. Open a Git Graph tab, which I understand to be a Webview
2. Change focus to another tab
3. Come back to Git Graph. Contents are now gone.

As seen in the log, the first error is `Invalid or unexpected token` though the view contents are seemingly fine before getting back the focus.

Does this issue occur when all extensions are disabled?: I've not yet come across any way to trigger this apart from Git Graph, so no.

![Screen Recording](https://user-images.githubusercontent.com/1483197/86060597-48b99e00-ba22-11ea-9f33-addf1e43240b.gif)

Developer Tools log:

```
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): init
log.ts:179 DEBUG WebviewResourceRequestManager(d744cc61-f95a-4326-9d46-e02a52634442): init
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): will set html
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): will update content
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): webview ready
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): will post message on 'styles'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): will post message on 'content'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): will post message on 'focus'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): dom-ready
log.ts:179 DEBUG WebviewResourceRequestManager(d744cc61-f95a-4326-9d46-e02a52634442): did-start-loading
log.ts:179 DEBUG WebviewResourceRequestManager(d744cc61-f95a-4326-9d46-e02a52634442): did register
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): did post message on 'styles'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): did post message on 'content'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): did post message on 'focus'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): will post message on 'focus'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): did post message on 'focus'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): did-set-content
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): will post message on 'message'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): did post message on 'message'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): will post message on 'message'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): did post message on 'message'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): will set html
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): will update content
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): will post message on 'content'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): did post message on 'content'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): will post message on 'focus'
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): did post message on 'focus'
webviewElement.ts:149 [Embedded Page] Uncaught SyntaxError: Invalid or unexpected token
webviewElement.ts:149 [Embedded Page] The Content Security Policy 'default-src 'none'; style-src vscode-webview-resource: 'unsafe-inline'; script-src 'nonce-ZQqKrJxFs0rCyI4HiJlKH9To4iGH4oho'; img-src data:;' was delivered via a <meta> element outside the document's <head>, which is disallowed. The policy has been ignored.
webviewElement.ts:149 [Embedded Page] Uncaught ReferenceError: acquireVsCodeApi is not defined
log.ts:179 DEBUG Webview(d744cc61-f95a-4326-9d46-e02a52634442): did-set-content
```

**Comment by mjbvz** [comment]
When this happens again, can you run: `Developer: Open webview developer tools`. In these dev tools, look for where the `Uncaught SyntaxError: Invalid or unexpected token` error is happening. This should help us track down what is going wrong

**Comment by jimcottrell** [comment]
Ah, that's helpful. Thanks for letting me know about those separate Webview developer tools. So, I was able to pin down specifically what's triggering it and create a dummy repo with a single commit message `Test commit with </script> tag`. The error triggers as follows (JSON string truncated as indicated):

```js
const acquireVsCodeApi = (function() {
				const originalPostMessage = window.parent.postMessage.bind(window.parent);
				const targetOrigin = '*';
				let acquired = false;

				let state = JSON.parse("{\"currentRepo\":\"/Users/jim/temp\", ...TRUNCATED... ,\"date\":1593476449,\"message\":\"Test commit with 
```

Clearly the presence of `</script>` in that string is cutting off the script parsing prematurely.

**Comment by mjbvz** [comment]
Thanks for the investigation. The `</script>` tag definitely explains the issue
