### ISSUE TITLE
Synchronize user formatting settings to workspace formatting settings page

### ISSUE THREAD

**Issue by greygraphics** [microsoft/vscode#101383]
When `editor.formatOnPaste` is set in the user settings and you want to turn it off for a certain workspace, you cannot do that from the UI but have to create the setting and set it to false in the settings.json of the workspace.
It would be great, if the workspace setting reflected the current user setting instead of the default setting (off).

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/58038
