### ISSUE TITLE
The file could not be saved to disk

### ISSUE THREAD

**Issue by Aliador** [microsoft/vscode#101330]
Problem Description:
The file is modified and saved in vscode. If you open the file with other tools, you can't see the modified content.

Figure 1 shows the modified content in vscode:
![image](https://user-images.githubusercontent.com/16972108/86077370-6d635380-babe-11ea-8d3f-116784e15a52.png)

Figure 2 shows the content opened with vim
![image](https://user-images.githubusercontent.com/16972108/86077594-cb903680-babe-11ea-9472-063dd12b8785.png)

**Comment by yume-chan** [comment]
I see your file path in Code is `target/classes/mybatis/mapper/OutpatientInfoMapper.xml`, but your terminal's title is `src/main/resources/mybatis/mapper/OutpatientInfoMapper.xml`. Can you confirm you are looking at the correct file?

**Comment by JacksonKearl** [comment]
Closing based on @yume-chan's observation that the files are in fact not the same. Please let me know if the problem persists.
