### ISSUE TITLE
VS Code closes immediately after launch with Centos 7

### ISSUE THREAD

**Issue by denisrheault** [microsoft/vscode#101310]
- VSCode Version:
1.46.1
cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
x64

- OS Version:
Centos 7: Linux 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

Install VS Code as per 
https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions

Start VS Code on command line.  Expecting window to open and stays open with the Welcome window.  Isntead a white window opens and closes right away.

Tried to disable gpu and extensions but nothing solves it.

However if I open it with '--log critical' it opens like expected, except that there's a message 'Extension host terminated unexpectedly' and I'm not able to open a folder (the window hangs and the then there's a message asking if it should be closed).  Also tried other levels of --log but only 'critical' has an effect.  Also the logs contains folders and files but all files are empty.

If I open it from the Applications> Vedelopment > MS VS Code then it opens properly and no complaints saying that the 'Extension host terminated unexpectedly.'  I can open a file, but not a folder.

Does this issue occur when all extensions are disabled?: Yes/No
Yes
Also occurs when gpu is diabled

**Comment by denisrheault** [comment]
How can we debug this?  I'd really like to use code on Centos 7.
Let me know what further info I can provide.
Thanks!

**Comment by deepak1556** [comment]
can you paste the output of `code --verbose`

**Comment by denisrheault** [comment]
Hi,

Thanks for the response.
Somehow the issue partially went away last week.  By that I mean that Code
wasn't closing right away, although it hangs so often that it is
barely usable.  One thing I did last week was to wipe out ~/.vscode.  Not
sure if that is the reason.
I was a little surprised to see this morning that the issue was back; code
closes right away.  Which is good because you can see an error with
'--verbose'

[drheault@hwd-58-172 scripts]$* code --verbose*
ATTENTION: default value of option force_s3tc_enable overridden by
environment.
[main 2020-07-23T10:46:49.103Z] Starting VS Code
[main 2020-07-23T10:46:49.105Z] from: /usr/share/code/resources/app
[main 2020-07-23T10:46:49.105Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false
}
[main 2020-07-23T10:46:49.108Z] Resolving machine identifier...
[main 2020-07-23T10:46:49.108Z] Resolved machine identifier:
87b08f238429699c4ac03bec95d8b4593b00a0212895fb9018e4dbf0947512fb
[49645:0723/064649.141277:ERROR:sandbox_linux.cc(369)] InitializeSandbox()
called with multiple threads in process gpu-process.



So I did the same but disabling the gpu:
[drheault@hwd-58-172 scripts]$ *code --verbose --disable-gpu*
[main 2020-07-23T10:48:39.422Z] Starting VS Code
[main 2020-07-23T10:48:39.424Z] from: /usr/share/code/resources/app
[main 2020-07-23T10:48:39.424Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': true,
  telemetry: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false
}
[main 2020-07-23T10:48:39.426Z] Resolving machine identifier...
[main 2020-07-23T10:48:39.426Z] Resolved machine identifier:
87b08f238429699c4ac03bec95d8b4593b00a0212895fb9018e4dbf0947512fb

So  --disable-gpu seems to help.  But right now I don't see the window
opening and no errors.  I grep 'ps -ef' for code and there's no process.
I wiped out ~/.vscode and it doesn't help.
I reinstalled it together and same thing.  I don't know why it doesn't
start anymore.

So then I try the '--log critical' and it works; the window opens.  But
there's a message saying that the extension host terminated unexpectedly
and crashes within minutes.  The messages are strange though with
--verbose...
[drheault@hwd-58-172 scripts]$ code --log critical --disable-gpu --verbose
[main 2020-07-23T11:20:16.306Z] Sending env to running instance...
[main 2020-07-23T11:20:16.531Z] Sent env to running instance.*
Terminating...*
[main 2020-07-23T11:20:16.532Z]* Lifecycle#kill()*

I looked at the content of the logs and the files are all empty.
I tried --disable-extensions and there's no apparent changes.

Regards,
Denis

**Comment by denisrheault** [comment]
Closing as I don't have access to the host which had the issue and therefore can't debug or verify anything.
