### ISSUE TITLE
Markdown Notebooks - GitHub actions leak in with GitHub Issue Notebooks installed

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#101419]
Testing #101325

If you have both notebook extension installed and open a markdown file as a markdown notebook you will see options to clear cell outputs and to lock GitHub document.

![image](https://user-images.githubusercontent.com/4544166/86144444-ace06e80-bac3-11ea-9285-92dc77c5db62.png)

**Comment by roblourens** [comment]
Clearing cells is not from the lock/unlock is, @jrieken those can be registered just for your notebook type with the `notebookViewType` key
