### ISSUE TITLE
When in High Contrast theme, menus that open via the "..." do not follow high contrast color scheme

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#10141]
- VSCode Version: 1.4.0
- OS Version: Windows

Steps to Reproduce:

1. Choose High Contrast theme from File -> Preferences -> Color Theme
2. Open any of the below menus

- In the Git viewlet, click the "..." which will open a menu for all the git actions
- In the Extensions viewlet, click the "..." which will open menu for options for showing extensions
- In any of the ediots, click the "..." on the top right corner

Each of these menus have the light gray background with black text that does not follow the high contrast color scheme.

![image](https://cloud.githubusercontent.com/assets/16890566/17417744/c6d2a4c2-5a49-11e6-834a-509007bb6a3f.png)

**Comment by aeschli** [comment]
Context menus (and the application menu) are rendered by the OS. You would have to use the OS configuration settings to enable high contrast for menues.
