### ISSUE TITLE
Support Search profiles to search predetermined file extensions

### ISSUE THREAD

**Issue by yonifra** [microsoft/vscode#101481]
I use the Search mechanism quite a lot in VSC during my work. While searching in the code, I often find myself filtering out test files and including code files (or the other way around) in the filter "files to include"/"files to exclude" filter.

**For example:**
![image](https://user-images.githubusercontent.com/726718/86214315-afa29880-bb83-11ea-8502-fcda8409c29c.png)

I would love it if I could save _"Search Presets"_ that would automatically filter out files I don't wish to search in, and including files I would like to search in, thus saving me the time to manually include / exclude file types all the time.

For me, I would have started with two presets, called "Search Code Files" and "Search Test Files". But of course this feature could be beneficial for many developers in my opinion.

**Comment by JacksonKearl** [comment]
\duplicate #20530
