### ISSUE TITLE
SCM context menu vertical alignment is off

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#101410]
Testing #101302

![image](https://user-images.githubusercontent.com/2193314/86134201-31b89180-ba9e-11ea-8f7d-f4b8efce4dfa.png)

**Comment by joaomoreno** [comment]
cc @sbatten we should probably think about shadow DOM for inline context views, such that CSS doesn't affect it

**Comment by sbatten** [comment]
@joaomoreno https://github.com/microsoft/vscode/issues/98673
