### ISSUE TITLE
Allow number values for editor.fontWeight

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#101467]
Currently `editor.fontWeight` only accepts values from `enum` which is convenient to pick from dropdown, however causes problems with fonts when there is noticeable difference between e.g. `300`, `350`, and `400` because `"350"` is not valid value.
Recently [new version of Cascadia Code](https://github.com/microsoft/cascadia-code/releases/tag/v2007.01) was released which provide nicer look for `"350"` value but marked as invalid.

I propose to allow numeric values in addition to current enum values (for backward compatibility) accordind to [CSS Fonts Module Level 4 > font-weight](https://drafts.csswg.org/css-fonts-4/#font-weight-prop)

Draft PR: #101468
If this request will be approved - I'll add same support to `terminal.integrated.fontWeight` and `terminal.integrated.fontWeightBold` options.

Only drawback that I see at this point - it's no longer possible to pick value from dropdown in Settings editor, however text values are still suggested in JSON.

UPD. As alternative it would be nice to have at least `*50` values at the end of the list of `*00` values

**Comment by IllusionMH** [comment]
@alexdima any chance to get feedback on this issue?
Looks like I'm not the only one with similar request - #103565

**Comment by alexdima** [comment]
I will try to set some time aside in August. I didn't look at it because the PR is marked as a draft. I thought that a "draft PR" represents work-in-progress and is not ready for review.

**Comment by IllusionMH** [comment]
@alexdima it was marked as draft for 2 reasons:

1) There was no approve on this issue yet, if proposed solution will be considered and mentioned cons aren't blocker for this feature.

2) If approved - I was going to do same for terminal `terminal.integrated.fontWeight`.

Since it's not rejected at this point I can finish changes for terminal and move PR out of draft status.

**Comment by jrieken** [comment]
It seems to accept 350 (as number) or any other number but I think it is very bogous that "300" (as string) is accepted but not "350". There is also no hit in the hover info that a string-enum and any number is OK.

**Comment by IllusionMH** [comment]
Previously allowed string values `"300"` etc. are left as is so users won't have problems with their existing settings (ideally there would be great to have something as migration scripts and replace it with `300` as number and don't allow ).
`"350"` (as string) was never allowed before (worked but was a warning) therefore I don't see it as problem.
I can check if it's `"normal"` or `"bold"` and treat it as number otherwise if necessary, however not sure how pattern validation will work in this case.

Agree with hint. I guess that text like `Controls the font weight. Accepts "normal" and "bold" keywords or numbers between 1 and 1000.` should do the trick

**Comment by IllusionMH** [comment]
OK, I guess combination of `enum`, `number`, and `string` + `pattern` + `patternErrorMessage` will provide good experience - suggests values from existing enum, allows `"350"`, and has adequate error message for strings like `"qwe"` and `"7000"`.
Will submit PR later today.

Any suggestions on how to improve `Controls the font weight. Accepts "normal" and "bold" keywords or numbers between 1 and 1000.` are welcome.

**Comment by jrieken** [comment]
I like that. Thanks
