### ISSUE TITLE
Settings object editor - editor interface missing for several Settings

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#101479]
Testing [#101329](https://github.com/microsoft/vscode/issues/101329)

Windows, Insiders

Problem:
Missing Add Item interface for all but one of the object-settings Settings, as well as some of the others you call out (typescript.tsserver.watchOptions, go.addTags, go.removeTags).

Repro:
1. Launch dummy extension, navigate to object-settings Settings.
2. All except "Empty Objects Don't Work" have the old "Edit in settings.json" interface.

![image](https://user-images.githubusercontent.com/1389808/86212341-b6ea8780-bb2c-11ea-9172-ed49b7aed877.png)

![image](https://user-images.githubusercontent.com/1389808/86212404-d2559280-bb2c-11ea-9cc5-d8b64b1169ed.png)

**Comment by 9at8** [comment]
@devinvalenciano this looks like an old prototype. You're probably not on the latest insiders 😉

**Comment by devinvalenciano** [comment]
@9at8 thanks Adi! I'll close this one out and retest.
