### ISSUE TITLE
Search within files doesn't work until file tab has been clicked

### ISSUE THREAD

**Issue by gitgitwhat** [microsoft/vscode#101416]
I don't know if this is a bug or by design but when you re-open VSCode and it auto loads a lot of files, when you use the search feature only files that have had their tab clicked will be searched in.  So, if you want to search in all open files, you will first have to click each tab before results are returned from them.

- VSCode Version:  Latest
- OS Version:  Windows 10

Steps to Reproduce:

1.  Open multiple files with common terms.
2.  Close Code
3.  Re-open Code but don't click any file tabs.
4.  Search for a word that is in one or more files.
5.  The results will only return matches in the active tab.
6.  Click each file tab and then rerun search.  All results will now appear.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Yeah, this is a known issue, there is another bug for it, sorry for the trouble.
