### ISSUE TITLE
marketplace is unavailable

### ISSUE THREAD

**Issue by pleabargain** [microsoft/vscode#101497]
videos
https://www.youtube.com/watch?v=ov1_9ygc2qE
https://www.youtube.com/watch?v=njbbeECNbi8

Issue Type: <b>Bug</b>

ex: 
show popular extensions
blue bar just crawls no results

ex:
ext install MS-vsliveshare.vsliveshare-pack
no results
timeout icon on extension
https://i.imgur.com/alh8Lpe.png

I cannot connect to marketplace.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 5.4.0-39-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3721)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|5, 5, 5|
|Memory (System)|15.33GB (2.26GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
kite|kit|0.117.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.0.3
python|tht|0.2.3
pdf|tom|0.6.0

</details>

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by pleabargain** [comment]
No movement at all when searching recommended or popular
https://i.imgur.com/oDTyceX.png
python image works
https://i.imgur.com/GXDO4BL.png

console log is full of red
[console-1593668408332.log](https://github.com/microsoft/vscode/files/4862195/console-1593668408332.log)
shared process console is empty even after requesting popular extensions
https://i.imgur.com/r3GXoPK.png

View -> Open View… -> Log (Shared)
https://i.imgur.com/4ioXO9L.png

re: View -> Open View… -> Log (Window)
I don't see that option.
![no window op in veiw Peek 2020-07-02 08-50](https://user-images.githubusercontent.com/640846/86321183-23ef4180-bc41-11ea-9858-bf44519ae951.gif)

**Comment by pleabargain** [comment]
![image](https://user-images.githubusercontent.com/640846/86321281-5b5dee00-bc41-11ea-8dbb-08edec1622a9.png)

**Comment by pleabargain** [comment]
turned off all ext
restarted
still no connection to marketplace
![turned off all ext and restarted still no joy Peek 2020-07-02 08-58](https://user-images.githubusercontent.com/640846/86321844-72e9a680-bc42-11ea-9a6e-63d95e99c318.gif)

**Comment by sandy081** [comment]
Can you please disable all extensions and try?

**Comment by pleabargain** [comment]
As I already mentioned here
https://github.com/microsoft/vscode/issues/101497#issuecomment-652801382
I turned off all extensions.
Restarted.
Then tried again.
NO JOY.

here is a gif showing that I am trying other marketplace tools and NONE work
![ext market place does not work Peek 2020-07-02 17-57](https://user-images.githubusercontent.com/640846/86374765-9a199580-bc8d-11ea-9b46-5d0d9beb734c.gif)

**Comment by pleabargain** [comment]
VS Code Market place is not working.
No extensions are enabled. 
NO JOY!

![marketplace not working Peek 2020-07-03 08-46](https://user-images.githubusercontent.com/640846/86435903-bfe48000-bd09-11ea-99ba-20b674821cc4.gif)

**Comment by sandy081** [comment]
I think you have to reload window after disabling all extensions. Please follow the steps below

- Open VS Code
- Reload VS Code with extensions disabled using the command `Developer: Reload with Extensions Disabled`
- Open developer tools using the command `Developer: Toggle Developer Tools`
- Open Extensions View
- Show Popular Extensions from `...` entry
- Check in the developer tools network tab if the request to Marketplace is succeeded.

**Comment by pleabargain** [comment]
no joy | does not work.

I have followed your instructions.
Here is the video:
https://youtu.be/RMEWsRyzfOw

**Comment by pleabargain** [comment]
How do I get marketplace to work?

**Comment by sandy081** [comment]
Running out of ideas here. 

Can you please try launching VS Code with fresh user data directory and extensions directory? You can do this by opening the Command line tool (say Powershell) and run following command (provide proper folder inputs for user data and extensions dir)

`code --user-data-dir <path-to-user-data-dir> --extensions-dir <path-to-extensions-dir>`

**Comment by pleabargain** [comment]
No joy
https://youtu.be/vSOYz0Gt9v8

I did as you instructed. Marketplace is NOT connecting.

I'm thinking NUCLEAR and just blow out VSCode from snap repo and start over... and HOPE.

**Comment by pleabargain** [comment]
still no joy!
https://youtu.be/wTkzzTPlAa4

**Comment by pleabargain** [comment]
I don't think this label applies anymore. Please escalate.

![image](https://user-images.githubusercontent.com/640846/87218893-aec9ed80-c35f-11ea-9df8-1d8dab7578fe.png)

**Comment by pleabargain** [comment]
I have a number of marketplace extensions I would like to install. What is the fix?

**Comment by pleabargain** [comment]
Still no joy with v. 1.47.1
![image](https://user-images.githubusercontent.com/640846/87532733-413dfa00-c69c-11ea-9767-099149943449.png)

**Comment by pleabargain** [comment]
https://youtu.be/opTgFKrw2mQ

**Comment by pleabargain** [comment]
dgd@dgd-System-Product-Name:~/Desktop/English Class Support$ code --list-extensions
abusaidm.html-snippets
batisteo.vscode-django
bibhasdn.django-html
bibhasdn.django-snippets
kiteco.kite
ms-python.python
ritwickdey.LiveServer
sidthesloth.html5-boilerplate
tht13.python
tomoki1207.pdf

**Comment by pleabargain** [comment]
<pre>code --user-data-dir vs1user/ --extensions-dir vs1ext/
</pre>

marketplace does not work!

https://youtu.be/bKxpHMuults

**Comment by pleabargain** [comment]
Help -> Toggle Developer Tools -> Console -> empty
View -> Command Pallette... -> Toggle Shared Process -> Console -> empty
View -> Open View… -> Log (Shared)
[2020-07-16 10:13:04.599] [sharedprocess] [info] main {"machineId":"486c4331ed3f5605a899a8366cd2dbecd76ad2e233d1830ed91b7f65a1917c41","windowId":2}
[2020-07-16 10:13:04.671] [sharedprocess] [error] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/dgd/vs1user/User/snippets'
[2020-07-16 10:13:44.623] [sharedprocess] [info] Starting to clean up unused language packs.

View -> Open View… -> Log (Window)

[2020-07-16 10:13:03.847] [exthost] [info] extension host started
[2020-07-16 10:13:03.951] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-07-16 10:13:03.952] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/37/usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2020-07-16 10:13:03.960] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-07-16 10:13:03.960] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/37/usr/share/code/resources/app/extensions/emmet/dist/extension
[2020-07-16 10:13:03.975] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-07-16 10:13:03.975] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/37/usr/share/code/resources/app/extensions/git/dist/main
[2020-07-16 10:13:04.014] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":true,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"*"}
[2020-07-16 10:13:04.015] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/37/usr/share/code/resources/app/extensions/github-authentication/dist/extension.js
[2020-07-16 10:13:04.029] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-07-16 10:13:04.029] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/37/usr/share/code/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2020-07-16 10:13:04.035] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":true,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"*"}
[2020-07-16 10:13:04.035] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/37/usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2020-07-16 10:13:04.039] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-07-16 10:13:04.045] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/37/usr/share/code/resources/app/extensions/search-result/dist/extension.js
[2020-07-16 10:13:04.311] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-07-16 10:13:04.311] [exthost] [info] ExtensionService#loadCommonJSModule file:///snap/code/37/usr/share/code/resources/app/extensions/github/dist/extension.js
[2020-07-16 10:13:04.389] [exthost] [info] eager extensions activated

preferences are empty
![image](https://user-images.githubusercontent.com/640846/87639573-1b712d80-c74e-11ea-9272-4f6e67404319.png)

**Comment by pleabargain** [comment]
codeverbose 1.txt
I started code 1.47.1 in verbose mode
There are a few errors at the beginning.

after running ext.txt
I am not seeing any OBVIOUS errors but I'm not the expert here.

PLEASE HELP!

[code verbose 1.txt](https://github.com/microsoft/vscode/files/4929988/code.verbose.1.txt)
[after running extension manager.txt](https://github.com/microsoft/vscode/files/4929989/after.running.extension.manager.txt)

**Comment by sandy081** [comment]
Sorry for not getting back on to this soon, I was stuck with other stuff.

I do not understand what is wrong with your installation, but we have to try out different steps

- Start VS Code with clean user data dir and extensions dir in verbose mode
- Open Network tab in developer tools (`Developer: Toggle Developer Tools`)
- Go to extensions view and search for 'flutter'
- Do you see any requests in network tab?

Also

- Try to install extension from command line like ` code --install-extension Dart-Code.flutter` and see what happens?

**Comment by pleabargain** [comment]
Do you see any requests in network tab? = no
![no network connection Peek 2020-07-19 11-19](https://user-images.githubusercontent.com/640846/87870545-b9186700-c9b1-11ea-903f-a062b06e8441.gif)
New weirdness
I installed via CL
![image](https://user-images.githubusercontent.com/640846/87870584-1e6c5800-c9b2-11ea-8a9f-93110d71d36c.png)
but after 'successful' install, ext is NOT in the list
![install from command line Peek 2020-07-19 11-21](https://user-images.githubusercontent.com/640846/87870591-30e69180-c9b2-11ea-83c3-0d6617ba6b20.gif)

**Comment by sandy081** [comment]
- Can you please run this command `Extensions: Open Extensions Folder` and let me know if you see the extensions you installed from CLI?
- Can you also check if the installed extension is running? For eg, you can see the features that this extension supports. Do not forget to reload window after installing from CLI.

**Comment by pleabargain** [comment]
I have updated
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic snap

and the problem STILL exists. I have been messaged via Youtube. Someone else is having the same problem, apparently.

re: Can you please run this command Extensions: Open Extensions Folder and let me know if you see the extensions you installed from CLI?
YES. I can see them.

dart works
I don't have any way of easily testing LIveshare. :/

What is interesting though is that I just tried installing a .vsix file and both failed with a .json missing error. I checked the zip. There is a json in the .vsix directory!
https://i.imgur.com/NxFniKu.png

**Comment by pleabargain** [comment]
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic snap

Still no joy in search
![no joy Peek 2020-08-03 12-46](https://user-images.githubusercontent.com/640846/89170000-b740cd00-d587-11ea-8aa8-df87bda9c487.gif)

**Comment by sandy081** [comment]
@deepak1556 Last thing I suspect here is underlying chromium. Can you please help user in debugging the requests and see if they are going through?

**Comment by pleabargain** [comment]
Possible fix I have not tested: https://github.com/microsoft/vscode/issues/104236

**Comment by pleabargain** [comment]
Latest version same problems!

Version: 1.48.1
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:11:59.963Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic snap

**Comment by sandy081** [comment]
Sorry that it got closed by our BOT and I did not realise it.

Seems similar to #104236. 

@pleabargain Did you try what other users tried here https://github.com/microsoft/vscode/issues/104236#issuecomment-679420305 ?

**Comment by debby12345** [comment]
Latest version same problems!  still encountering this problem please help

**Comment by davidalmarinho** [comment]
Same here, my vscode cannot connect to the Extensions Marketplace.

**Comment by deepak1556** [comment]
@debby12345 @davidalmarinho please open separate issues to track down the problem.

**Comment by davidalmarinho** [comment]
> @debby12345 @davidalmarinho please open separate issues to track down the problem.
Here it is
https://github.com/microsoft/vscode/issues/106369
