### ISSUE TITLE
VS Code not recognizing changes to files in Git branch

### ISSUE THREAD

**Issue by patrickdamery** [microsoft/vscode#101493]
Issue Type: <b>Bug</b>

On Ubuntu, working on a project with a working Git branch. If I make a change to any file in the project I would expect this change to show up in the Source Control in the left sidebar. However no changes show up, I need to close VS code and open it again for it to recognize that there are changes to the file system compared to the Git branch.

This is a recent problem, I've updated to the latest version and that didn't help. Git is setup to use an ssh key which has a passphrase, normally VS code would prompt me for this password when I start it up but it hasn't done so since the problem started so I'm guessing it's relevant.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 4.15.0-1090-oem

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 3204)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.36GB (6.69GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.4.1
bracket-pair-colorizer|Coe|1.0.61
vue-snippets|hol|0.1.11
vscode-peacock|joh|3.7.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
dotenv|mik|1.0.1
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
vetur|oct|0.24.0
gitblame|wad|4.0.1
twig|wha|1.0.2

</details>

**Comment by nepetadosmil** [comment]
Can reproduce on Windows 10 Pro 1909, same VSCode version (1.46.1) too.

Changed files no longer get highlighted in the Explorer, and changes don't get detected on the Source Control tab unless I manually click on "sync". Autorefresh is enabled in my VS Code settings.

**Comment by joaomoreno** [comment]
@patrickdamery  
You seem to be missing file events. Please go through the following steps:

1. Run `Git: Set Log Level...` and choose `Trace`
2. Run `Git: Show Git Output`
3. Reproduce the issue and wait 10-20 seconds
4. Paste the whole output here

---

@nepetadosmil Please file a separate issue, since it's very likely a different one.
