### ISSUE TITLE
drag and drop not working properly

### ISSUE THREAD

**Issue by gurrrung** [microsoft/vscode#101470]
- VSCode Version: 1.46.1
- OS Version: Ubuntu 18

Steps to Reproduce:

I tried dragging my file from VSCode into a folder and found that instead of moving/copying the file, it creates a txt file which contains the path of the file. Is something wrong with VSCode or this is just how it works?

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/101368
