### ISSUE TITLE
undo stack restore not working

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#101440]
- VSCode Version:

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-17T22:31:53.325Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.44-1-MANJARO
```

- OS Version: Manjaro Linux

Steps to Reproduce:

1. Make an undo stack (make changes)
2. Close VS Code.
3. Open VS Code and return to the project
4. Notice there is no restored undo stack

Does this issue occur when all extensions are disabled?: Didn't test this yet.

**Comment by alexdima** [comment]
Let's track in #7536
