### ISSUE TITLE
Odd failures when dropping multiple copies of the same vsix into extension view

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#101456]
Refs #101117

**Repro**
1. Download a vsix
1. Duplicate the vsix
1. Drag both copies of the vsix to the extension view

**Bug**
See odd failures related to disk operations. These errors vary. Here's one example:
<img width="548" alt="Screen Shot 2020-06-30 at 2 38 53 PM" src="https://user-images.githubusercontent.com/12821956/86179660-90522f80-badf-11ea-8ea1-b263b953c189.png">

Probably an issue someone will only hit during testing :)

**Comment by sandy081** [comment]
Eventually these duplicated vsixs gets extracted into same folder and hence you are seeing this error for one of the VSIXs and other one succeeds. Since it is not a realistic scenario I would close this as won't fix.
