### ISSUE TITLE
compacted debug sessions should show name of child and not of parent

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#101429]
Testing #101009

When hierarchical debug sessions are compacted, the resulting tree node uses the name of the parent session, not the name of the child session.

So this uncompressed tree:
<img width="346" alt="2020-06-30_18-40-53" src="https://user-images.githubusercontent.com/1898161/86153046-56922080-bb01-11ea-8feb-dc392d504558.png">

becomes this:
<img width="339" alt="2020-06-30_18-42-40" src="https://user-images.githubusercontent.com/1898161/86153152-7e818400-bb01-11ea-828a-f7b63cf1d389.png">

IMO this does not make sense because the compact feature **eliminates the parent** when there is only one child.
It does not eliminate the child.

**Comment by isidorn** [comment]
@weinand what you are saying makes sense, however for js-debug this would not really work that well scine the child sessions have "weird names".

What I suggest: we change this on the vscode side as you suggest - to use the parent name
And @connor4312 improves on the JS-debug side the names of child sessions: for example to be NAME_OF_CONFIG + process ID
So something like "Launch Program 1452"

**Comment by weinand** [comment]
@isidorn  yes, I agree with your proposal.

Another argument for that approach: with the current behavior the "weird name" child gets the "nice name" from the parent. But if another child arrives, two "weird names" shows up...

**Comment by int19h** [comment]
It's not just JS. Python also has "weird" child session names - they're basically "Subprocess ...", where ... is the process ID. Concatenating them would also not work well.

I'm not sure why it's a weird scheme, though. This naming scheme works just fine when the tree is fully expanded - it tells users exactly what they need to know, without overburdening them with redundant information that's already available (e.g. repeating parent process name). It feels weird having to change that just to play well with a subset of scenarios that involve compacting.

**Comment by isidorn** [comment]
After discussions with @weinand we decided to do the following changes:
* Change the `noCompact` flag to be `compact` flag and thus the default value is to not compact sessions. So this is opt-in
* Changed call stack to display the name of the Child Session. I actually think by default it does not looks so "weird"

@connor4312 As a follow up for js-debug I have created this item https://github.com/microsoft/vscode-js-debug/issues/551
@int19h as a follow up for pythong I have created https://github.com/microsoft/vscode-python/issues/12716


![Screenshot 2020-07-02 at 11 45 13](https://user-images.githubusercontent.com/1926584/86344143-32962280-bc5a-11ea-8e38-fb1dc5c4472c.png)
