### ISSUE TITLE
Notebooks: consolidate output actions

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#101448]
This is more of a generic notebook request. Would love it if we could consolidate the output actions so they're in the same place. We could try to add them to the toolbar with a separator. This would allows us to have additional output actions (like expand/collapse output):

![image](https://user-images.githubusercontent.com/35271042/86173759-52e8a480-bad5-11ea-8616-967aaeb6f278.png)

![Kapture 2020-06-30 at 13 30 22](https://user-images.githubusercontent.com/35271042/86174620-d951b600-bad6-11ea-95c7-6384a6ab88dc.gif)

And we could also put less used actions in the ellipsis (locked, etc.)

cc @roblourens @jrieken

**Comment by misolori** [comment]
I think my only concern with my proposal is for the toolbar to get unnecessarily long like so:

![image](https://user-images.githubusercontent.com/35271042/86258431-ad364380-bb6f-11ea-9a7e-30ad4e8ef163.png)

**Comment by rebornix** [comment]
Fixed via bae379e986aa72d026d0904fe22d05221a139156
