### ISSUE TITLE
[themes] Support separate Dark, Light, HighContrast color theme customizations (i.e. specific to ColorThemeKind)

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#101418]
Issue Type: <b>Feature Request</b>

Users can already set `workbench.colorCustomizations` and `editor.tokenColorCustomizations` and `editor.semanticTokenColorCustomizations` at two levels, either globally or for named themes.

I would also like to be able to set customizations based on the kind of color theme.

Possible syntax, using double square-brackets in place of the singles that denote a named theme:

```
"workbench.colorCustomizations": {
	"[[Dark]]": {
		"activityBar.activeBackground": "#222222"
	},
	"[[Light]]": {
		"activityBar.activeBackground": "#dddddd"
	},
	"[[HighContrast]]": {
		"activityBar.activeBackground": "#ffff00"
	}
}
```

One specific use case is for a semantic highlight provider extension that defines custom token types and would like to provide sensible default styling for these tokens in dark, light and high contrast themes.

VS Code version: Code - Insiders 1.47.0-insider (04203498480e48be84d86f5763e126c7c5bf22e0, 2020-06-30T09:00:22.588Z)
OS version: Windows_NT x64 10.0.18363

**Comment by aeschli** [comment]
The suggested feature make sense, but I don't think the suggested use case is the right motivation.

It's ok for a user to define new theme colors, and override themes, but we don't want extensions to do it. I understand why semantic token provider would want that. But such colors will interfere with the work of theme authors.
Colors have to come from themes and the decision if/what to color also has to come from themes.
It's not possible to find a good default color that works with all themes. There are many things that have to work together, background color, various selection colors. If it doesn't look good, the theme will be blamed.

**Comment by gjsjohnmurray** [comment]
@aeschli I take your points re themes and theme authors, but if a language doesn't map well to the standard tokens and consequently the provider's `SemanticTokensLegend` contains mostly (or even exclusively) custom tokens, then either the language provider also has to provide one or more full themes (and convince users to use it/them), or else there will be little or no semantic coloring, right?

I wrote "full theme" because as far as I know it's not possible to subclass an existing theme and only provide additional color information.

**Comment by aeschli** [comment]
I understand the dilemma. But actually it's no different with TextMate grammars/TextMate themes. A grammar can be as sophisticated as it wants, if themes don't assign colors to the scopes, there's no benefit to that.
- have your custom tokens inherit from the standard tokens, as these are more likely covered by themes or have TextMate scope mapping
- have your own theme to showcase the capabilities, and work with theme authors and we can improve the default themes
- tell user how they can take advantage of semantic tokens through defining rules in `editor.semanticTokenColorCustomizations`

**Comment by gjsjohnmurray** [comment]
It turns out that `editor.semanticTokenColorCustomizations` and its friends aren't language-overridable, so an extension can't influence them through its `configurationDefaults` contribution. Probably the best (worst?) it can do is give the user a block of settings to add to their settings.json or XYZ.code-workspace file. Maybe even implement a command that adds this block. Then leave it to the user to tweak the colors if they don't play nice with the theme.

Being able to supply [[Dark]], [[Light]] and [[HighContrast]] variants would be nice. Otherwise I might use the ColorThemeKind of the active theme to pick the right variant, then either add it in a theme-specific section or add it where it applies to all themes. In the latter case if the user changed to a theme of a different ColorThemeKind they might want to rerun the command.

**Comment by zEdS15B3GCwq** [comment]
I'd like to add my +1 vote for this feature. My use case would be purely from a user's side, who sometimes switches to a different theme based on my mood, light conditions etc. I'd like my customisations to work with dark and light themes in general, as it's difficult to define them for each theme I might be using in the future.

**Comment by zEdS15B3GCwq** [comment]
Thanks, I've submitted my thumbs up. I feel, however, that the title may be too developer-specific and may not be clear to the average user. Something like "theme colour customisation for dark/light/high contrast theme kind in general" sounds clearer to me, though I'm sure that can be improved further.
