### ISSUE TITLE
View menu hover shows 'and more actions' when there are no more actions

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#101491]
Testing #100848 

A nit, but the hover over the '...' in the SCM container or the Debugger shows

![image](https://user-images.githubusercontent.com/172399/86224708-8422ac80-bb89-11ea-97ca-f19c9158b5d9.png)

'More Actions...' but in this case there are no more actions. Having the hover just showing 'Views'  would be more accurate.

**Comment by isidorn** [comment]
Actually in the SCM view the correct would be to just say `More Actions...` as before. Since we do not show the Views submenut for SCM by default.
