### ISSUE TITLE
noDebug: true debugs

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101413]
Testing #100963

* have an extension sample, set a breakpoint on first line in activate-function
* debug from the viewlet, breakpoint hit, stop debugging
* have the snippet below
* debug via the command
* :bug: breakpoint hit 

```

	vscode.commands.registerCommand('extension.helloWorld', async (args) => {
		try {
			const session = await vscode.debug.startDebugging(vscode.workspace.workspaceFolders![0], 'Run Extension', { noDebug: true })
			console.log('DEBUG', session)
		} catch (err) {
			console.error(err);
		}
	});
```

**Comment by isidorn** [comment]
This is probably becauase js-debug currently does not support `noDebug`. So first assigning to @connor4312 
@jrieken as a workaround you can set `"debug.extensionHost.useV3": false,` and that should make you use the old node debugger

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/523. I'm probably going to fix this in my run of the test plan.

**Comment by connor4312** [comment]
Fixed in the next nightly
