### ISSUE TITLE
Copy/paste cell issues

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#101462]
- Execute a github issue cell
- Copy the cell, paste it below
- The output picker shows up, but the output doesn't
- Scroll around, sometimes the second output is visible when the first cell is not visible
- Delete the first cell
- Scroll the second cell in and out, now the output is visible

My guess is that there are outputs with the same outputId

**Comment by rebornix** [comment]
cc @connor4312

**Comment by roblourens** [comment]
Also it looks like we end up with a cell with the same handle, which leads to other issues, like 'selection' is not updated in the EH if I select that cell

**Comment by roblourens** [comment]
It looks like this is fixed
