### ISSUE TITLE
Feature Request: Copy path and goto from top file path at top of page

### ISSUE THREAD

**Issue by gitgitwhat** [microsoft/vscode#101415]
You can right click a file from the Explorer frame and copy the file path or jump to it in Windows Explorer but you can not do the same from the file path that is at the top of each page.

**Comment by gjsjohnmurray** [comment]
> from the file path that is at the top of each page

Related to #56494

**Comment by isidorn** [comment]
Forwarding to @jrieken since this seems like a feature request for breadcrumbs

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Abreadcrumbs
