### ISSUE TITLE
Windowed Zen+ Mode

### ISSUE THREAD

**Issue by narfanar** [microsoft/vscode#101450]
Zen mode, but windowed.

Basically what _seems like_ an easy alternative to a way to focus on specific editor groups.

I want a toggle that turns a window with multiple editor groups into a window with only the current editor group visible and filling the width/height of the window.

The current `Maximize Editor Group*` commands are insufficient as the "minimized" editor groups still take a lot of space.

**Alternatively**: Provide a way to toggle visibility of editor groups (from the `Open Editors` pane) and then we can get an extension that toggles "hide all but this editor group".

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by adriancuadrado** [comment]
For now you can go to the Menu Bar --> View --> Appearance and uncheck everything but "Show Editor Area".
It would, still, be useful to have a keyboard shortcut to do this directly. I can recommend you this one: https://github.com/ryuta46/vscode-multi-command. You can then add the commands from the command palette that toggles each thing to execute all of them at once and get the equivalent of Ctrl+K, Z for Zen mode, but windowed.
