### ISSUE TITLE
startDebugging handle better when undefined passed for workspaceFolder and name set

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#101400]
Have the following code snippet in your extension

```
		const session = await vscode.debug.startDebugging(undefined, 'Run Extension', { noDebug: true })
```

1. This should either just work and we should automatically pick the first workspace folder if there is only one
2. Or there should be an appropriate error message

**Comment by connor4312** [comment]
I think the error message should be `Cannot find "Run Extension" in the workspace folder's launch.json` if the launch.json exists
