### ISSUE TITLE
How to set Heap size

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#10149]
By default the memory limit in Node js is 512 mb. This will cause FATAL ERROR- JS Allocation failed – process out of memory when processing large data files. How do i fixed it in Visual studio code 

ported from https://github.com/Microsoft/vscode-docs/issues/489

**Comment by bpasero** [comment]
As far as I know you cannot set the heap size.

**Comment by Astr-o** [comment]
I found that you can use the `--max-old-space-size=<max-heap>` node argument. You can add it to the `runtimeArgs` property of your config in `launch.json`. 

See example below. 

```JSON
{
    "version": "0.2.0",
    "configurations": [{
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\server.js"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Training Script",
            "program": "${workspaceRoot}\\training-script.js",
            "runtimeArgs": [
                "--max-old-space-size=4096"
            ]
        }
    ]
}
```

**Comment by naveedahmed1** [comment]
Can anyone please guide how to increase max-old-space-size when using Visual Studio 2017? I am using Angular template in VS 2017 and having memory errors when publishing.

**Comment by matthewwren** [comment]
@naveedahmed1 If you open the .csproj file in a text editor you will find the following section, there you can add the `--max-old-space-size` as I have done:

    <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    
    <Exec Command="npm install" />
    <Exec Command="node --max-old-space-size=4096 node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod" />
    <Exec Command="node --max-old-space-size=4096 node_modules/webpack/bin/webpack.js --env.prod" />

    
    <ItemGroup>
      <DistFiles Include="wwwroot\dist\**; ClientApp\dist\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>

**Comment by naveedahmed1** [comment]
Thanks for sharing this @matthewwren  , just found it recently :)
