### ISSUE TITLE
Improve ProblemMatcher error message when a problem matcher is not available

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#101475]
In the setup shown in the screenshot I had the TS extension disabled:

![image](https://user-images.githubusercontent.com/172399/86208520-05217a00-bb71-11ea-8501-391f16f328df.png)

The error message should hint at that this could be caused by a missing extension. Instead of:
'Value not accepted' -> 'Problem matcher not recognised (could be caused by a missing extension), recognized matchers:...'

**Comment by alexr00** [comment]
New message:
![image](https://user-images.githubusercontent.com/38270282/86915793-dd0eb980-c122-11ea-81a7-b0d660c034ac.png)
