### ISSUE TITLE
Reload notification appears when extensions are already installed

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#101441]
Testing #101117

* Download extensions from marketplace ex: ESLint, C/C++
* DnD into the extension viewlet
* Both extensions are successfully installed and requests reload
* Confirm reload window
* Again DnD the extensions into the viewlet
* nothing should happen instead notification pops up with `Please reload Visual Studio Code to complete installing the extension ....`

**Comment by lszomoru** [comment]
This also happens when you are installing an extension using the `Install from VSIX...` action in the context menu of the Extensions viewlet. I believe that there was a conversation around improving this behavior but I am not sure whether that worked is being tracked. @sandy081 do you remember?

**Comment by sandy081** [comment]
Yes it was discussed but do not remember if it is being tracked. Let's use this issue.

**Comment by sandy081** [comment]
Sometimes VSIXs with same version can have different changes crafted in the VSIX, hence we show the reload notification even when same version is installed from VSIX. 

So, I would still show the reload prompt with a different message..

<img width="562" alt="image" src="https://user-images.githubusercontent.com/10746682/98565453-edd86300-22ad-11eb-8bb2-e838f7c493f2.png">
