### ISSUE TITLE
Consider adding a `command` object to TerminalLink rather than the `handleTerminalLink` method

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#101457]
Testing #101300

Again, this is mostly API ergonomics, but this would keep consistency with other APIs (CodeLens, StatusBarItems, TreeItems, etc). It also helps guide the usage of a command being required to return a link, and somewhat avoids calls to `handleTerminalLink` that take no action.

Additionally since the command object has a `title` property, that could be used in place of the `tooltip` property as well.

re: https://github.com/microsoft/vscode/issues/101391#issuecomment-652046491

/cc @jrieken

**Comment by Tyriar** [comment]
Decided not to do this https://github.com/microsoft/vscode/issues/91290#issuecomment-658271823
