### ISSUE TITLE
Regex support for ++ (Possessive Quantifier)

### ISSUE THREAD

**Issue by nesovera** [microsoft/vscode#101403]
Issue Type: <b>Feature Request</b>

Search does not support regex Possessive Quantifier.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

**Comment by roblourens** [comment]
We can only support regex patterns that are supported by JS
