### ISSUE TITLE
Mac upgrade failed: The application “Visual Studio Code.app” can’t be opened.

### ISSUE THREAD

**Issue by raminf** [Microsoft/vscode#10142]
- VSCode Version: Visual Studio Code Mac v 1.3.1
- OS Version: OSX El Capitan 10.11.6 (15G31)

Steps to Reproduce:

1. Tried to do an in-app update. It asked to restart to apply update. Clicked OK.
2. It said update could not be applied and to download full version from link.
3. Followed link and downloaded latest stable release zip file.
4. Unzipped and copied to Applications folder.
5. Tried running and got: 'The application “Visual Studio Code.app” can’t be opened.' 
![screenshot_303](https://cloud.githubusercontent.com/assets/66789/17417930/b3e6f524-5a4a-11e6-86c9-0813f16c6633.png)

6. Tried to download directly from website. Same result.

**Comment by oshalygin** [comment]
Might want to try remove it from applications, re-download and move over to Applications again.  I had the same issue  a few months ago.

**Comment by joaomoreno** [comment]
Yes, completely remove it from the Applications folder. Then copy a fresh copy there.

**Comment by raminf** [comment]
Removed it and re-downloaded it. Still got the same issue. 

Tried removing it then rebooting system, re-downloading then reinstalling. This time it worked. 

Something wasn't cleaning up properly after itself...
