### ISSUE TITLE
Markdown Notebooks - Code and Markdown buttons intersect cells in edit mode

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#101420]
Testing #101325

1. Create two markdown cells both in edit mode 
2. The buttons to create a new code cell or markdown cell will intersect with the bottom cell in edit mode

![image](https://user-images.githubusercontent.com/4544166/86145393-dfd73200-bac4-11ea-8dd1-5bcf195e3886.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/101380
