### ISSUE TITLE
Empty cell not visible when notebook is split

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#101445]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/101305

1. Create a new `.github-issues` file and add another markdown cell to it, so that it has two empty cells both in edit mode
2. Split the editor

Originally I thought the second cell wasn't being rendered at all in the split view, but it's just not in edit mode. Since focus goes to the first cell this makes it hard to see.
<img width="1359" alt="Screen Shot 2020-06-30 at 12 29 33 PM" src="https://user-images.githubusercontent.com/3672607/86168687-698afd80-bacd-11ea-864e-8a381fe57551.png">

VS Code version: Code - Insiders 1.47.0-insider (04203498480e48be84d86f5763e126c7c5bf22e0, 2020-06-30T09:00:22.588Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bamurtaugh** [comment]
I'm able to repro this. It also appears that just the markdown cells are not in edit mode- subsequent code cells are more visible:

![image](https://user-images.githubusercontent.com/25310137/86169473-896ef100-bace-11ea-9075-d99f38172fdb.png)

VS Code version: Code - Insiders 1.47.0-insider
Date: 2020-06-26T06:20:06.931Z
OS: Windows_NT x64 10.0.19041

**Comment by rebornix** [comment]
Thanks for the feedback! We should show some placeholders for empty markdown cell preview.
