### ISSUE TITLE
Show editor reopen with in title context menu

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#101463]
For mouse users, the title context menu might be a better place for the reopen action

![image](https://user-images.githubusercontent.com/876920/86186122-19bc2e80-baed-11ea-81d0-ef4c27faffb8.png)

cc @mjbvz

**Comment by bpasero** [comment]
@rebornix @mjbvz if we decide to have this in the tab context menu, why do we still have it in the "..." menu? We now essentially show this command twice:

![image](https://user-images.githubusercontent.com/900690/86207411-c8ed1a00-bb6e-11ea-97d3-e0d4b62d5aa2.png)

![image](https://user-images.githubusercontent.com/900690/86207419-ce4a6480-bb6e-11ea-8864-2af23c49bd32.png)

**Comment by rebornix** [comment]
@mjbvz the reason I added this to the title bar is I saw the "Show Preview" in the title bar context menu, so it makes sense to have Open With action there too. But I agree that having redundant actions doesn't make sense, what are your thoughts on it?

**Comment by bpasero** [comment]
If I had to choose I would try to keep the tabs menu small and actually liked the action inside the "...", though arguably less discoverable.

**Comment by rebornix** [comment]
It comes relatively late so I reverted the change and let's discuss in next iteration.

**Comment by mjbvz** [comment]
This is probably worth quickly bringing up at the UX sync. I agree the context menu is makes this feature more discoverable

**Comment by jrieken** [comment]
related: did we discuss using a sub menu for this?

**Comment by rebornix** [comment]
@jrieken where would the sub menu show?

**Comment by jrieken** [comment]
Where we show (or will show) the current menu
