### ISSUE TITLE
Support outline for custom editors

### ISSUE THREAD

**Issue by perspectivus1** [microsoft/vscode#101476]
As a developer, I would like to see the outline tree for non-text editors. Currently, I get this message for my custom editor:

> The active editor cannot provide outline information

![image](https://user-images.githubusercontent.com/9444504/86210140-c396cc00-bb7c-11ea-930b-a922190a6e62.png)

Note that I get this message even though my custom editor is registered using a [CustomTextEditorProvider](https://code.visualstudio.com/api/references/vscode-api#CustomTextEditorProvider). This provider is based on TextDocument, and so is [DocumentSymbolProvider](https://code.visualstudio.com/api/references/vscode-api#DocumentSymbolProvider), so enabling the outline should be straightforward.

I believe showing the outline would be very useful, even if clicking on a symbol in the outline does not navigate to a location in the custom editor.

**Comment by gjsjohnmurray** [comment]
@perspectivus1 I suggest you upvote #97095
