### ISSUE TITLE
C# 6.0 string interpolation does not recognize the end of string

### ISSUE THREAD

**Issue by RaulOnk** [Microsoft/vscode#10146]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

When doing string interpolation everything greys out. For example            
public void GreetName() => Console.WriteLine($"Hello {this.Name}");
will grey out everything under that method. It does not recognize where the string ended.

**Comment by Tyriar** [comment]
@RaulOnk do you have the C# extension installed?

**Comment by RaulOnk** [comment]
Yes and it compiled just fine. It is just visually not working and anything under that does not have auto complete.

**Comment by RaulOnk** [comment]
![image](https://cloud.githubusercontent.com/assets/13458372/17420626/d1c2ccb8-5a58-11e6-8da3-87db4ac1916b.png)

**Comment by Tyriar** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#638
