### ISSUE TITLE
Notebook reopen with: can not open text editor

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#101465]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install GitHub Issue Notebook
2. Create/Open a `*.github-issues` notebook
3. Double click the title to pin it
4. Run "Reopen editor with...` and open in text editor
5. The document is opened in a new tab, and rendered in text editor, which is good
6. Click the first tab, it switches to notebook editor
7. Click the second tab, it no longer switches to text editor

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
Introduced by https://github.com/microsoft/vscode/commit/412e3fb8ec07b648563c9b6fb47e6646ca636610

**Comment by rebornix** [comment]
I think we only want to open the same notebook editor if the passed in original input is `ResourceEditorInput`. @jrieken you can correct me if it was wrong assumption.

**Comment by jrieken** [comment]
Yeah, sounds reasonable
