### ISSUE TITLE
cannot copy using command+c neither from extension details nor notebook output

### ISSUE THREAD

**Issue by anya2go** [microsoft/vscode#101439]
- VSCode Version: 1.45.1
- OS Version: MacOS Catalina 10.15.5

Unable to use the keyboard shortcut to copy text from within extensions and output of dataframes in Jupiter notebook. (could be other outputs as well, this is the one I failed to copy)
Steps to Reproduce:

1. command+c from any extension details
2. command+c output of pandas dataframe in Jupiter notebook

Does this issue occur when all extensions are disabled?: n/a

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? We've fixed a few bugs related to this in more recent VS Code builds
