### ISSUE TITLE
Show error messages in contributed commands somewhere discoverable

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#101460]
Extension:

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	context.subscriptions.push(vscode.commands.registerCommand('sd.helloWorld', () => {
		throw Error('Super helpful debugging information');
	}));
}
```

Run command, note that the super helpful debugging info gets discarded: 
![image](https://user-images.githubusercontent.com/8586769/86183449-d959b200-bae6-11ea-8062-3984f42ab9a5.png)

If you dig a bit you can find the error logged in the Extension Host output channel, but that is pretty undiscoverable.

This came up a couple times at the VS Code extension hackathon and students did not know how to see what was actually failing. I think we could go a few ways on this:
- Include the error message in the notification
- Include in notification a directive to enable "stop on caught exceptions". (This isn't ideal because running an extension with this enabled will trigger a bunch of unrelated stops)
- log the error to console and put a button in the notification that opens developer tools.
- put a button in the notification to open the extension host output channel

**Comment by jrieken** [comment]
I assume this is happening when a command is triggered via the command palette...

Generally, we don't have special error handling for commands from extensions vs commands from the core and I that's a good choice. Instead, each caller of a command should handle errors in the best fitting ways

**Comment by JacksonKearl** [comment]
@bpasero would you accept PR for this? Speaking with first-time extension authors at the hackathon this was a large point of confusion.
