### ISSUE TITLE
Extension Authors Call for June 2020

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#101459]
Here is the rough plan for our extension authors call for **June** 2020. The call will be held on **July 10th** @ **8am PT (UTC-7)**.

The call will be focused on gathering feedback on how we can improve an extension's first-run experience (e.g. notifications, welcome pages), update experience (notifications, release notes, etc), and settings experience for end-users — so if you are interested in participating in those topics please join us!

### Agenda
- [_~10 mins_] Introductions — please introduce yourselves and your extension(s)
- [_~50 mins_] Open discussion on learning about extension's requirements, wants, etc around first-run, update, and settings
experience and how that impacts end-users and what we can do to improve that experience

### Participants
Since we want a small set of participants to facilitate richer and more effective communication, we are asking everyone who is interested in participating to fill out the sign up link below:

~~[Sign up to participate](https://www.surveymonkey.com/r/J5JLNHM)~~ *Sign-ups are over for this month's call*

Sign-ups will end on **July 8th**. After which, we will reach out and confirm the set of authors who will be participating in the call, and will update this post with the final list.

### Logistics
On **July 10th** @ **8am PT (UTC-7)**, via a MS Teams call. After the call ends, we will post a link to the recorded video.

**Comment by Brandy003** [comment]
Asking anyone if they could better explain

**Comment by eamodio** [comment]
Unfortunately we've had to move the call to Friday, July 10th. Please sign up above before the 8th!

**Comment by eamodio** [comment]
@Brandy003 I'm not sure what details you are looking for, but here is a link to the issue explaining the reasoning/goals of the authors' calls: https://github.com/microsoft/vscode/issues/91714

**Comment by eamodio** [comment]
The call will be tomorrow **July 10th @ 8am PT (UTC-7)**

**Comment by pikadun** [comment]
Hope to solve this problem: https://github.com/microsoft/vscode/issues/54111

**Comment by eamodio** [comment]
Thank you to everyone who participated in this call!

### Video
[![](https://img.youtube.com/vi/r6Jd0BgYBrM/maxresdefault.jpg)](https://youtu.be/r6Jd0BgYBrM)

### Participants
- Georgekutty Antony ([Docker Run](https://marketplace.visualstudio.com/items?itemName=george3447.docker-run))
- Gustavo Cassel ([Google Drive](https://marketplace.visualstudio.com/items?itemName=GustavoASC.google-drive-vscode))
- Dan Čermák ([Open Build Service Connector](https://marketplace.visualstudio.com/items?itemName=SUSE.open-build-service-connector))
- Alessandro Fragnani ([Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager), [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks), and [more](https://marketplace.visualstudio.com/publishers/alefragnani))
- Ekansh Gupta ([ImageToText](https://marketplace.visualstudio.com/items?itemName=SimranMakhija.imagetotext))
- Hana Kim ([Go](https://marketplace.visualstudio.com/items?itemName=golang.Go))
- Lex Li ([reStructuredText](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext))
- Nandini Sharma

### Issues
Here are the issues tracking the features, bugs, etc that came up during the call.
- What's new icon/UI for extensions (and future API) — https://github.com/microsoft/vscode/issues/102139
- Issue Reporter: Support configuring data sent to extensions — https://github.com/microsoft/vscode/issues/46726

Looking forward to next month!

P.S. Extension authors — join our community run [VS Code Developer Community Slack](https://aka.ms/vscode-dev-community) 😄
