### ISSUE TITLE
Bash Integrated Terminal No Cursor/Can't Type

### ISSUE THREAD

**Issue by gavinuhran** [microsoft/vscode#101423]
- VSCode Version: Most Recent Version
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCode and the bash terminal does not allow me to type.

Image 1: My bash terminal does not give me the option to type anything
![frozen terminal](https://user-images.githubusercontent.com/29406498/86146421-cda5c580-babd-11ea-9563-3c11d60e2acf.JPG)

Image 2: My CMD terminal works fine
![working terminal](https://user-images.githubusercontent.com/29406498/86146431-d4343d00-babd-11ea-838b-1f1f6e046295.JPG)

Image 3: My settings.json
![settings](https://user-images.githubusercontent.com/29406498/86146442-d7c7c400-babd-11ea-89b1-fc7d7a2417c3.JPG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Can you run `ver` in cmd to get your windows build number?

/label "needs more info" integrated-terminal
