### ISSUE TITLE
Extension Host Terminated Unexpectedly

### ISSUE THREAD

**Issue by nick-adair** [microsoft/vscode#101406]
Issue Type: <b>Bug</b>

I'm running virtual environments and writing code in python 3.8, I enabled flake8 and was in the process of enabling radon.  To recreate all I have to do I start VSCODE and wait about 10 seconds.

VS Code version: Code - Insiders 1.47.0-insider (04203498480e48be84d86f5763e126c7c5bf22e0, 2020-06-30T09:00:22.588Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (3.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.5
aws-toolkit-vscode|ama|1.10.0
vscode-django|bat|0.20.0
bracket-pair-colorizer-2|Coe|0.1.4
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
docker-explorer|for|0.1.7
shell-format|fox|7.0.1
todo-tree|Gru|0.0.177
vscode-docker-ipython|har|0.1.2
docker-linter|hen|0.5.0
live-share-for-aws-cloud9|ian|0.11.4
vscode-aws-cloudformation-auto-template-generator|joh|1.1.1
cornflakes-linter|kev|0.5.1
vsc-python-indent|Kev|1.10.1
kite|kit|0.119.0
azureloginaws|Lum|0.1.0
MagicPython|mag|1.1.0
aws-cli-configure|mar|0.3.0
vscode-remote-workspace|mkl|0.44.0
vscode-docker|ms-|1.3.1
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.7.91116-dev
remote-containers|ms-|0.124.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
powershell|ms-|2020.6.0
autodocstring|njp|0.5.3
vscode-ipython|pan|0.5.0
aws-step-functions-constructor|pau|0.6.3
vscode-yaml|red|0.8.0
preview-vscode|sea|2.1.0
markdown-preview-enhanced|shd|0.5.12
regexworkbench|ste|2.0.4
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.9
jinja|who|0.0.8

</details>

**Comment by JacksonKearl** [comment]
\extPython
