### ISSUE TITLE
NPM extension provides 'Go to Definition'?

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#101474]
The built-in npm extension provides a Go to Definition command.

Open a package.json:

![image](https://user-images.githubusercontent.com/172399/86207586-25e8d000-bb6f-11ea-987a-b2735b903814.png)

I couldn't find a location where this command is successful?

**Comment by NotWearingPants** [comment]
It works in `require('express')`

**Comment by egamma** [comment]
@NotWearingPants inside the `package.json` file?

**Comment by aeschli** [comment]
Find definition works only on JSON files that are schemas and only when the selection is `$ref` value
It was a PR: https://github.com/microsoft/vscode-json-languageservice/pull/50

**Comment by aeschli** [comment]
The JSON language service now uses links for the $ref in schemas. Goto definition is no longer used.
