### ISSUE TITLE
Improve explanation of "compacted with the parent"

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#101434]
Testing #101009

The comment for the new "noCompact" option says:
> Controls if the debug session created will be compacted with the parent in the CALL STACK view. Compact with the parent is only done if the session is the only child of its parent session. Default is to compact.

IMO "compacted with the parent" is not very clear to me. I think this can be improved to something like:

> Controls if the debug session's parent session is shown even if it has only a single child. Default is to hide the parent session in this case in order to make the tree more compact.

@connor4312 any other suggestions from a native speaker?

**Comment by connor4312** [comment]
I like the rewording. Something I was initially confused about was where `noCompact` applied -- to the subtree, children, parents? Maybe something like this:

> By default, debug sessions with a single child are hidden in the CALL STACK view to make the tree more compact. If noCompact is `true`, then the new debug session will never hide its parent.

**Comment by isidorn** [comment]
Thanks for feedback!
Landed on 
```
Controls if the debug session's parent session is shown in the CALL STACK view even if it has only a single child.
By default, debug sessions with a single child are hidden in the CALL STACK view to make the tree more compact.
If noCompact is true, then the debug session will never hide its parent.
```
