### ISSUE TITLE
Markdown cells go into edit mode when focused

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#101402]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.47.0-insider (04203498480e48be84d86f5763e126c7c5bf22e0, 2020-06-30T09:00:22.588Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (1.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
mock-debug|and|0.42.1
vscode-eslint|dba|2.1.5
EditorConfig|Edi|0.15.1
vscode-github-releases-updater|joa|0.18.0
vscode-peacock|joh|3.7.2
chat|kar|0.35.0
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
python|ms-|2020.6.90262
remote-containers|ms-|0.124.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
js-debug-companion|ms-|1.0.2
vscode-github-issue-notebooks|ms-|0.0.31
cloudenv-extensions|ms-|1.0.1369
vsliveshare|ms-|1.0.2377
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
vsonline|ms-|1.0.2390
debugger-for-chrome|msj|4.12.8
test-search-rg|rob|0.0.3
code-spell-checker|str|1.9.0

</details>

Found while testing https://github.com/microsoft/vscode/issues/101334

Open a notebook
Set focus in a code cell
Use the arrow keys to move to a markdown cell
Note that the markdown cell goes into edit mode
Use arrow keys to move to another cell
Note that the markdown cell remains in edit mode. This means it is not possible to use the arrow keys to navigate to different cells without changing the appearance of markdown cells.
![recording (1)](https://user-images.githubusercontent.com/1704059/86127157-5d0ba280-bad7-11ea-9b42-b0a2ab78c4a1.gif)

**Comment by roblourens** [comment]
Have discussed improving this with @kieferrm, some options are

- Don't put markdown cells in edit mode when the cursor goes out of a sibling cell editor, just focus the container instead. Code cells can keep the behavior of getting editor focus in this case. And maybe, "remember" that an editor focus context exists so that if I go past a markdown cell to another code cell, that cell gets editor focus
- Don't keep markdown cells in edit mode when cursoring through them, unless I edited the markdown cell while the cursor was in it

**Comment by stevencl** [comment]
I think I prefer the second option of the two. With this option, I arrow into a markdown cell, press Enter to edit it, make some edits, then arrow out of the cell to another markdown cell. That second markdown cell would not be in edit mode, correct?

Another option might be to more closely match what Jupyter notebooks do:

- Pressing enter while a container has focus puts the notebook into edit mode. Arrowing through other cells puts those cells into edit mode.
- Pressing shift-enter while in edit mode in a cell puts the notebook into non-edit mode. Arrowing through other cells focuses the container and does not put the cell into edit mode.
- Clicking in a cell puts the notebook into edit mode

The second option above is optimised for reading notebooks and making small edits. The Jupyter style interaction is perhaps better when doing a lot of edits throughout the notebook as it avoids the need to press enter on each cell to edit it.

**Comment by roblourens** [comment]
No, in that case the second one would be in edit mode, but if you don't make any edits to the second cell, it will go back to preview mode when you arrow out of it.

I don't understand how the Jupyter scenario is different from what we do currently. We modeled the current design off Jupyter.

**Comment by stevencl** [comment]
Here's an example:

VS Code: When in a markdown cell in edit mode, press shift-enter. That cell is now not in edit mode and shows the rendered markdown. Focus shifts to the cell underneath which is now in edit mode.

Jupyter: When in a markdown cell in edit mode, press shift-enter. That cell is now not in edit mode and shows the rendered markdown. Selection moves to the cell underneath which is not in edit mode.

In VS Code, if I want to get out of edit mode I need to press Esc.

In Jupyter pressing Shift-Enter brings me out of edit mode for the notebook.

**Comment by roblourens** [comment]
I see the difference with shift+enter, it gives the next cell container focus instead of editor focus. vscode should match that.
