### ISSUE TITLE
Hanging due to a lot of spaces in markdown header

### ISSUE THREAD

**Issue by cherouvim** [microsoft/vscode#101485]
- VSCode Version: 1.46.1 (2020-06-17T21:13:20.174Z)
- OS Version: Windows 7 (Windows_NT x64 6.1.7601)

Steps to Reproduce:

1. Open up an `.md` file with this content:
```
# foo        [2000 spaces here]    bar
```
Such a file is provided within this zip (couldn't directly upload `.md`): [__repro.zip](https://github.com/microsoft/vscode/files/4856458/__repro.zip)

2. Watch CPU go crazy, and vscode become unresponsive.

Does this issue occur when all extensions are disabled?: Yes. To overcome the problem I had to open using `--disable-extensions --new-window`

Maybe there is some hanging regex in the markdown specific code? Opening the file as `.txt` solves the issue.

**Comment by cherouvim** [comment]
Oh, and if you want to know how I discovered this, I accidentally left a bag of things on top of my keyboard for some time.

**Comment by IllusionMH** [comment]
Hangs on looks like hangs due to syntax highlighting
![image](https://user-images.githubusercontent.com/1312662/86278464-1d30e200-bbe1-11ea-9f73-a763521dcc81.png)
