### ISSUE TITLE
Align error message with task configuration terminology

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#101482]
Testing https://github.com/microsoft/vscode/issues/101299

In the task.json the shell is configured with the property `executable`

<img width="435" alt="image" src="https://user-images.githubusercontent.com/172399/86214298-46b72280-bb7b-11ea-93aa-0b52e5d629c7.png">

The error message uses the term path

<img width="744" alt="image" src="https://user-images.githubusercontent.com/172399/86214327-53d41180-bb7b-11ea-8966-85b473ef7f6b.png">

For example:  ... Shell execrable "foo" does not exist.

**Comment by alexr00** [comment]
Currently this comes from the terminal. @Tyriar, would you be amenable to this string change? 
```
Path to shell executable \"{0}\" does not exist
```
in https://github.com/microsoft/vscode/blob/7f132c907bce4e4d8331d647a4a7c94b7f5eb063/src/vs/workbench/contrib/terminal/node/terminalProcess.ts#L123-L123
