### ISSUE TITLE
regex replace case changing in search

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#101454]
Case changing for a replace with regex in the find widget was implemented in https://github.com/microsoft/vscode/issues/12185. Search has a different implementation and needs a different approach. 

@irridia are you planning on looking into this? Either way is fine, but let me know

https://github.com/microsoft/vscode/pull/96128#issuecomment-642187968

**Comment by irridia** [comment]
I can probably manage a very simplified regex replace that's on the search side. But looking into a full refactor/join of the two implementations, I don't think I have the TS expertise to do that within the time I'd have. I totally get it if you'd rather have a merged implementation, but if feature parity (if not code parity) is okay for now, I can take a look at the parallel take.

**Comment by roblourens** [comment]
That would be fine with me!

**Comment by irridia** [comment]
@roblourens see #105101

**Comment by Aypahyo** [comment]
+1 for this feature
