### ISSUE TITLE
Controle de Código Fonte

### ISSUE THREAD

**Issue by maeverson** [microsoft/vscode#101447]
Issue Type: <b>Bug</b>

O atalho do teclado (windows) Ctrl + Enter, na área de Controle de Código Fonte, para commitar uma alteração parou de funcionar.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.1
vue|jcb|0.1.5
dotenv|mik|1.0.1
vscode-language-pack-pt-BR|MS-|1.46.3
color-highlight|nau|2.3.0
vetur|oct|0.24.0
material-icon-theme|PKi|4.2.0
markdown-all-in-one|yzh|3.1.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
@maeverson Can you reproduce if you disable all extensions? `code --disable-extensions`.
