### ISSUE TITLE
Markdown Notebooks - Markdown notebook structure should be reproducible

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#101421]
Testing #101325

1. Create two cells first cell containing `***italics**` second cell containing `**bold**`.
2. The outputted markdown just gets concatenated. I would expect with two different cells it would have a line break in between
3. Reopen this markdown in a markdown notebook, the markdown notebook has issues parsing it. I would expect that since I edited this markdown file in a markdown notebook when I reopen it in the notebook it should be the same structure as how I left it.

**Comment by roblourens** [comment]
Fixing, need to wait a day for https://github.com/microsoft/vscode/issues/101461
