### ISSUE TITLE
Touch Screen Click vs Mouse Click

### ISSUE THREAD

**Issue by jacksonbrumbaugh** [microsoft/vscode#101471]
Issue Type: <b>Performance Issue</b>

I have a touch screen laptop and notice that some clicks behave differenly whether I click on screen or click with my touchpad mouse.  For instance, in the Explorer tab, with an opened folder, when I click with my touchpad mouse in an open space beneath all sub items (folders and files), a blue outline appears around the open folder drop down and any selected items are de-selected.  However, this behavior does not occur if I click the open space on my touch screen; a selected item is still selected and the blue outline does not appear

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/wiki/Performance-Issues
