### ISSUE TITLE
Windows HD colors problem with Dell XPS13(9300) 2020

### ISSUE THREAD

**Issue by LiNINJA** [microsoft/vscode#101449]
I use Dell XPS13(9300), 2020 model, with a 4K display.
The problem is, **this application, vscode, seems to be detected as an HDR app(?)**
When I open this program with Win10's "Use HDR" option on, this app launch with apparently darker than other apps.

--Here's the detail--

Model:Dell XPS13(9300) 2020

OS: Win10 Pro build 19042.330 (Stable build, 1904, has the same issue too, I tested it.)

Graphics:
Operating System: NA
Language: en-US
Physical Memory: NA
Current Resolution: 3840x2400
Processor: NA
Processor Speed: 1498 MHz MHz
GFX Driver Name: Intel(R) Iris(R) Plus Graphics
Shader Version: 5.1
OpenCL* Version: 2.1
* Microsoft DirectX* *
Runtime Version: 12
Hardware-Supported Version: 12
Vulkan* Version: 1.2.135
Vendor ID: 8086
Device ID: 8A52
Device Revision: 07
GFX Driver Version: 26.20.100.8141
GFX Vulcan: 1.2.135
GFX GOP: 14.0.1036
Display Name: Built-In Display
Display Type: Digital
Serial Number: -
DDC2 Protocol: Supported
Gamma: 2.2
Connector Type: Built-In Display
Maximum Image Size
Horizontal - 11.42 inches
Vertical - 7.09 inches
Supported Modes
3840 x 2400 (48p Hz)
3840 x 2400 (60p Hz)

--
I don't know the bug came from OS or Graphic driver or vs code or Dell.
I hopefully fix this near future.

**Comment by gjsjohnmurray** [comment]
Does the information at https://code.visualstudio.com/updates/v1_43#_electron-70-update help?

**Comment by JacksonKearl** [comment]
@LiNINJA were you able to resolve this using the linked troubleshooting guide?
