### ISSUE TITLE
TS and JS Language Features crashing

### ISSUE THREAD

**Issue by NigelThorne** [microsoft/vscode#101477]
Issue Type: <b>Bug</b>

I don't have steps. It's just in a crashing loop.  Reporting it's crashed every 5 mins.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-storybook|cst|0.0.5
vscode-eslint|dba|2.1.5
es7-react-js-snippets|dsz|2.8.0
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.1
vscode-highlight|fab|1.4.1
code-runner|for|0.10.0
vscode-mysql|for|0.4.0
cover|hin|0.0.2
dotenv|mik|1.0.1
mssql|ms-|1.9.0
cpptools|ms-|0.28.3
vscode-typescript-tslint-plugin|ms-|1.2.3
sqltools|mtx|0.22.10
sqltools-driver-mysql|mtx|0.1.0
sqltools-driver-pg|mtx|0.1.0
proto|pet|0.0.2
material-icon-theme|PKi|4.2.0
vscode-qt-for-python|sea|0.4.2
slim|sia|0.1.2
rewrap|stk|1.12.0
org-mode|too|0.5.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also, when the crash happens click the report issue button in the crash notification. This should help you report an issue that includes the error stack

**Comment by mjbvz** [comment]
Closing as not-actionable without more information
