### ISSUE TITLE
Markdown Notebooks - Small black line with creating multiple new markdown cells

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#101428]
Testing #101325

1. Create a few markdown cells
2. At least one of them will have a black line that juts into the cell

![image](https://user-images.githubusercontent.com/4544166/86148695-f54e5b00-bac8-11ea-859d-16f7778ba461.png)

This goes away upon changing themes, editing, etc.

**Comment by rebornix** [comment]
I haven't seen this issue for a while, closing it for now and reopen if you are seeing it again.
