### ISSUE TITLE
Keyboard shortcuts for new notebook UI

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#101436]
Is there going to be a uniform keyboard shortcut story for the new notebook UI, or is the idea that every extension configures its own keyboard shortcuts?

If there is something uniform, has the choice of keyboard shortcuts been settled? If yes, is there a place where we can look at the current choices?

We are currently redesigning the keyboard shortcut choices generally inside the Julia extension, and we would like to make sure that the code execution shortcuts we use outside of the notebook UI are aligned with whatever will come via notebook support once it lands.

**Comment by rebornix** [comment]
@davidanthoff we are going to introduce builtin keyboard shortcuts, which will be similar to the keybindings for text editor, e.g., Copy/Move Line, Delete Line, Insert Line Above/Below.

**Comment by davidanthoff** [comment]
Cool! And I take it that the final set of keyboard shortcuts has not been set yet, right? We're particularly interested in the set of shortcuts that will execute cells.

**Comment by rebornix** [comment]
Currently we have following *execute* related commands/keybindings for macOS

```json
{ "key": "ctrl+enter",            "command": "notebook.cell.execute",
                                     "when": "notebookEditorFocused" },
{ "key": "alt+enter",             "command": "notebook.cell.executeAndInsertBelow",
                                     "when": "notebookEditorFocused" },
{ "key": "shift+enter",           "command": "notebook.cell.executeAndSelectBelow",
                                     "when": "notebookEditorFocused" },
{ "command: "notebook.execute" }
```

**Comment by davidanthoff** [comment]
How final do you think they are? Should we better wait with our keyboard redesign until this is all settled? I think if there is a non-negligible probability that this is not yet final, we would probably be better off waiting with our general redesign until the notebook stuff has shipped.

**Comment by rebornix** [comment]
@davidanthoff I'll suggest you wait for us to finalize (shipping to Stable) before you redesign the keybindings. Next month we will roll in more keybindings and you can start looking into that and see how much gap between the builtin ones and the ones you have in mind for Julia.

**Comment by davidanthoff** [comment]
Ok, perfect, that was exactly the kind of info I was looking for!

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode/commit/404eb11bde49955819079ecc76b7cfd329654b02 updated commonly used keybindings for notebooks @davidanthoff you can open Keybindings Editor and search for Notebook.
