### ISSUE TITLE
Markdown Notebooks - Clicking between tabs is flipped

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#101417]
Testing #101325

1. Open  markdown file as markdown notebook
2. Click the tab with the notebook open, it will bring you to the regular file
3. Click the tab with the regular file, it will bring you to the notebook 
![recording (3)](https://user-images.githubusercontent.com/4544166/86143778-dd73d880-bac2-11ea-8298-7e4484ae636e.gif)

**Comment by roblourens** [comment]
I think this is some EditorInput issue @rebornix. 

- Open a .md file, it opens in the notebook which is my configured default
- "Reopen with" Text Editor - I have one tab open, as expected
- "Reopen with" Notebook - now I have two tabs open with this weird bug

**Comment by rebornix** [comment]
This is already fixed in Insiders.
