### ISSUE TITLE
SCM Open and Open in New Window do the same thing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#101404]
Testing #101302

![image](https://user-images.githubusercontent.com/2193314/86129827-282c2b00-ba98-11ea-95fd-c56df7a021eb.png)

These do the same thing when `"window.openFoldersInNewWindow": "on"` is set. Open recent respects this only when not using modifiers:

![image](https://user-images.githubusercontent.com/2193314/86129951-4db93480-ba98-11ea-9591-40cbc59009dd.png)

**Comment by joaomoreno** [comment]
@bpasero Is there any way to force `vscode.openFolder` to use the same window?

https://github.com/microsoft/vscode/blob/master/extensions/git/src/commands.ts#L766-L770

**Comment by bpasero** [comment]
@joaomoreno should work if you pass `{ forceReuseWindow: true }`

**Comment by Tyriar** [comment]
Also consider swapping the "Open" action based on the setting as well, eg the buttons could be either "Open" and "Open in New Window", or "Open" and "Open in This Window".
