### ISSUE TITLE
there seems to be no obvious way to "unsplit" a splitted terminal

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#101587]
I got into a situation where my terminal is splitted:

![2020-07-02_12-31-45](https://user-images.githubusercontent.com/1898161/86348530-14cbbc00-bc60-11ea-941b-622efa1047b0.png)

How do I get rid of this?
There seems to be no obvious way to unsplit.

**Comment by annalifatou** [comment]
You can click the trashcan to 'unsplit'. It will kill terminals one at a time. I agree it's not immediately obvious though.

**Comment by Tyriar** [comment]
I guess you're asking to be able to unsplit terminals so they becomes tabs instead?

**Comment by weinand** [comment]
@Tyriar no, I just wanted to remove individual terminals in the splitted case. The "trashcan" wasn't obvious to me...
