### ISSUE TITLE
Cannot manually stage specific range with only whitespace changes.

### ISSUE THREAD

**Issue by snctfd** [microsoft/vscode#101503]
It seems to be impossible to forcibly stage ranges (Working Tree -> select changed areas -> ... in top right -> Stage Selected Ranges) where the only change is in the whitespace. This is janky when working with Python if you only want to stage some of the changes you've made to a given file. See https://gist.github.com/snctfd/b4eff5323fefb7b6b9f616e36e0b9243 for a MWE. Staging the entire file (by clicking the little +) will lead to the correct behavior.

- VSCode Version: 1.46.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create an empty git repository.
2. Open the repository folder in Code.
3. Create a file with the contents of `test1.py` (see gist linked above) and commit it.
4. Change the file such that it looks like `test2.py`.
5. Open the test file's working tree in the source control sidebar (i.e. click the file's name under "changes")
6. Select the entire `foo()` method *without* selecting the newly created `qux()`, and try to stage the selected changes. 

Because of the bug, only the first two lines of foo() (the ones with non-whitespace changes) will be changed, meaning bar() will remain on the first level of indentation, breaking the code. It looks as such:

![image](https://user-images.githubusercontent.com/24232947/86246293-0c657980-bbab-11ea-9b90-90b1187facfd.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/) of what happens during the staging?
