### ISSUE TITLE
"Duplicate Workspace in New Window" command creates a different workspace

### ISSUE THREAD

**Issue by Milunnn** [microsoft/vscode#101557]
Issue Type: <b>Bug</b>

![bugImage1](https://iulcrg.bn.files.1drv.com/y4m0WiFLvWk7oZtKctxaol-iFv7LLRUHAV1OqkGZN9YuvfvphoyB2qLhVrRYPuI0gK5wdE3RbRH_8GgzhgJl_bslR1IKHuf2h2Mvz69JGscSetSO4D9bzCYY6x0SOuQX5diQ83DlVHKhIodvSWBqz-whYqWYwOSWz9nJpiaTL8hwqoB2sqREoNgxTajE3PgEzXK0el8omzZmBwIAraSCVrd4A)

![bugImage2](https://hpkprg.bn.files.1drv.com/y4m5FSu3ZVdHCvzzRv9A3C9kfdiAEJ_M_C8aiyxufHqw0mplx99bu3TDqeR6ysfduQjFMIhE-HkAl_Dx-UY9dXOzjHVYtd2EZ8DzwZ71DtW8G3lA6tRICJvJPqnubNHmZRpPJjWZ5GL6UCihak4auXS-aXdvcks_EonclZi6odrmmyjJ64E1j_IMRRFwqcihiRVznpV3TYI_pUJgEcMZeTMeA)

As you see, after I execute the "Duplicate Workspace in New Window" command, it creates a new window in which the workspace is different than the original one. The root folder (of the original workspace) in the duplicate window is included as a part of the workspace, instead of being recognized as a root workspace folder.

But when I tried to create a folder on the same level as the root folder and then execute this command to test if it detected all folders on the same level as the root folder, only the original workspace root folder was shown in the workspace.

This bug kinda bugs me (heh), because if you look at the second image, the root folder shouldn't really be there, if it is meant to be the workspace root folder. This happens even if the workspace is saved on the hard drive.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor          (16 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
prettier-vscode|esb|5.1.2
go|gol|0.15.0
beautify|Hoo|1.5.0
vscode-styled-components|jpo|0.0.29
code-beautifier|mic|2.3.3
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.24.0
cwtools-vscode|tbo|0.8.41
paradox-syntax|tbo|0.1.15
vscodeintellicode|Vis|1.2.9
markdown-all-in-one|yzh|3.1.0

</details>

**Comment by bpasero** [comment]
This is currently the only way we can support it: by creating an "Untitled Workspace". See our docs for more info on that topic.
