### ISSUE TITLE
UX meeting agenda 10 August, 2016

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#10155]
Agenda:

- (Next time, not this week) Allow users to chose squiggly lines or boxes for errors and warnings. #9209

**Comment by stevencl** [comment]
Refactor the view menu: https://github.com/Microsoft/vscode/issues/9924

Showing errors in the editor: https://github.com/Microsoft/vscode/issues/9062

Distinguishing two files with the same name: https://github.com/Microsoft/vscode/issues/8499

**Comment by stevencl** [comment]
More discussion on the horizontal panel: https://github.com/Microsoft/vscode/issues/9659

**Comment by bpasero** [comment]
Sorry to hijack the order of priority but I think horizontal editor layout should be # 1 because it is planned as item in the August iteration plan (https://github.com/Microsoft/vscode/issues/1749)

**Comment by stevencl** [comment]
OK, lets spend some time discussing how we will know when we are done and how we will proceed with that item during August.

**Comment by bpasero** [comment]
Also on the plan with UX impact: Extensible Icon support in the explorer (https://github.com/Microsoft/vscode/issues/10294)
