### ISSUE TITLE
Behavior of detecting the file language

### ISSUE THREAD

**Issue by simpleapples** [microsoft/vscode#101573]
- VSCode Version: 1.46.1
- OS Version: macOS 10.15.5

Steps to Reproduce:
1. create a file named `dockerfile.go`, `dockerfile.py` or other extensions.
2. you can see the file is detected as a `Dockerfile`, but it should be a go file or python file.
<img width="852" alt="Screen Shot 2020-07-02 at 3 59 43 PM" src="https://user-images.githubusercontent.com/1655036/86332490-2d969a80-bc7d-11ea-8d72-2c9488250f9c.png">

Related logic:
I found the file detecting logic is here: 
https://github.com/microsoft/vscode/blob/697b702e47d05fa71f480a2620ab5849f52f55c3/src/vs/base/common/mime.ts#L195-L208
 *Filename Match* has the higher priority than *Extension Match*, I think it should be reconsidered. *Extension Match* should have the highest priority.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bpasero** [comment]
I can reproduce in Code stable, but not Insiders, but have no clue what has changed. 

@simpleapples can you try to reproduce with our insiders?

**Comment by simpleapples** [comment]
Hi, @bpasero, thank you for your response.

I can't reproduce the same result on the latest insider build. There is no essential change between insider build and stable build on the file `mime.ts`. 

So I have the same confusion about the different behaviors.

**Comment by bpasero** [comment]
Ok, looks like this got fixed somehow I cannot explain why. We can reopen if this comes back next month after we have released.

**Comment by simpleapples** [comment]
I got reasons about this issue.

1. Why a `dockerfile.go` is recognized as a `Dockerfile`?
Recently, developers of `vscode-docker` added a `Dockerfile.*` file association (https://github.com/microsoft/vscode-docker/pull/1908), If a file is called `dockerfile.go`, it will match this pattern and will be recognized as a `Dockerfile`.

2. Why detection behaviors are different between insider and stable?
The `extension/docker/package.json` of `vscode` is different from `extension/docker/package.json` of `vscode-docker` after https://github.com/microsoft/vscode-docker/pull/1908. So, it will function properly with docker extension installed, whether in insider or in stable.

Next step:
I'm trying to argue with developers of `vscode-docker` to remove the `Dockerfile.*` file association, because it will disrupt normal operation of file associaitons of other languages.

Just to explain.

**Comment by simpleapples** [comment]
Hi, @bpasero , I'm confused about the mechanism of file type detecting.

As you know, there is a `filenameMatch` and a `extensionMatch`. `extensionMatch` is responsible for checking the extension of files. `filenameMatch` for the filename.

But, if we add a pattern `filename.*` on `filenameMatch`, it can match any extensions. For my perspective, `filenameMatch` should just match filenames without extension. 

What do you think about it ?
