### ISSUE TITLE
debugger does not show line

### ISSUE THREAD

**Issue by FelixBenning** [microsoft/vscode#101531]
Issue Type: <b>Bug</b>

When starting the (python) debugger:
orange line at the bottom, variables and call stack show up, but the current line is not highlighted

![image](https://user-images.githubusercontent.com/29106652/86277022-4730d700-bbd6-11ea-98cc-387491f03142.png)

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.36.1
githistory|don|0.6.5
gitlens|eam|10.2.2
prettify-json|moh|0.0.3
python|ms-|2020.6.91350
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
markdown-all-in-one|yzh|3.1.0

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/100805
If you have repro steps that would be great
