### ISSUE TITLE
VS Code Freezes sometimes after killing the in-built terminal of it

### ISSUE THREAD

**Issue by soumya-99** [microsoft/vscode#101528]
### VS Code Freezes Sometime
**Sometimes, when I click on the kill button of in-built terminal, it freezes for no reason. Please fix the bug.**

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide all necessary data requested by by issue template (OS, VS Code version etc).
What terminal are you using?

Also check if this is duplicate of #76548 or #71966

**Comment by soumya-99** [comment]
**OS is Windows 10 pro and VS Code has the latest version**
_Please Check it._
