### ISSUE TITLE
VS Code Insider Force Close

### ISSUE THREAD

**Issue by randynetworks** [microsoft/vscode#101565]
Issue Type: <b>Feature Request</b>

hi!, i found some bug, when i delete a file or paste file from file explorer, it's stuck and force close. i hope it's will be fix

VS Code version: Code - Insiders 1.47.0-insider (b16b467d3e03e1a1ae05b5836e4e5a5af504e86d, 2020-07-01T05:31:43.470Z)
OS version: Linux x64 5.6.19-300.fc32.x86_64 snap

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by isidorn** [comment]
Oh, you are using insiders, so it is actually a duplicate https://github.com/microsoft/vscode/issues/85332
