### ISSUE TITLE
editor screen is divvied when a .dart file is opened

### ISSUE THREAD

**Issue by xwpdev** [microsoft/vscode#101566]
Issue Type: <b>Bug</b>

When I open a .dart file, editor screen is has a divider and text is wrapped around it. cannot see an option / config to disable it

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.77GB (10.44GB free)|
|Process Argv|--folder-uri file:///c%3A/Work/HeyDoor/heydoor_app|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
ng-template|Ang|0.1000.2
dart-code|Dar|3.12.1
flutter|Dar|3.12.1
es7-react-js-snippets|dsz|2.8.0
gitlens|eam|10.2.2
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.2
remote-wsl|ms-|0.44.4
awesome-flutter-snippets|Nas|2.0.3
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-wakatime|Wak|4.0.0

</details>

![image](https://user-images.githubusercontent.com/10055067/86321630-01682300-bc57-11ea-85fe-e0bbfd0a0649.png)

**Comment by gjsjohnmurray** [comment]
That looks like a [ruler](https://stackoverflow.com/questions/29968499/vertical-rulers-in-visual-studio-code) contributed by your Dart extension.

**Comment by xwpdev** [comment]
@gjsjohnmurray I guess it is. updated workoplace settings
