### ISSUE TITLE
Double paste when using Jupyter Notebook in VS Code Insider

### ISSUE THREAD

**Issue by Spalar** [microsoft/vscode#101574]
Issue Type: <b>Bug</b>

Whenever i copy some text on my clipboard and paste it in jupyter notebook file it pastes it twice.
There is no problem with my keyboard and the copy and paste works fine in other file types.

VS Code version: Code - Insiders 1.47.0-insider (b16b467d3e03e1a1ae05b5836e4e5a5af504e86d, 2020-07-01T05:32:07.483Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
django|big|1.0.2
php-debug|fel|1.13.0
uikit-3-snippets|Ken|1.4.3
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
cpptools|ms-|0.28.3
java|red|0.63.0
LiveServer|rit|5.6.1
django-intellisense|sha|0.0.2
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
vscode-icons|vsc|10.1.1

</details>

**Comment by mswiatlo** [comment]
I see this as well very often (though not 100% of the time, but definitely a majority of the time).

**Comment by sylvainlapeyrade** [comment]
Same here. I have updated the last version of VS Code Insiders today and I have still the same issue.
However, I have noticed that pressing CTRL+SHIFT+V instead of just CTRL+V prevents this bug.
