### ISSUE TITLE
Top and bottom border cut off on status bar item border

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#101525]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/99350

Using the high contrast theme on mac, the top and bottom border of these boxes appear cut off:
![Screen Shot 2020-07-01 at 9 25 48 AM](https://user-images.githubusercontent.com/3672607/86268439-0c4e8500-bb7d-11ea-87a2-3d47acd582b7.png)

VS Code version: Code - Insiders 1.47.0-insider (04203498480e48be84d86f5763e126c7c5bf22e0, 2020-06-30T09:01:06.154Z)
OS version: Darwin x64 18.7.0

**Comment by RMacfarlane** [comment]
Ah, this was on hover, not focus, if that makes any difference

**Comment by isidorn** [comment]
Hmm yeah on hover I get the dotted lines, but I still get the botom border...

**Comment by jeanp413** [comment]
Not sure if you tried this, but you need to have the window not maximized, in that case the bottom window border covers the status bar item hover or focus border. I'll make a PR to try to fix this.
