### ISSUE TITLE
Activity bar: menu could offer an action to move it right

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101578]
Talking about this menu:

![image](https://user-images.githubusercontent.com/900690/86337295-32ddf000-bc51-11ea-9333-5681b38d2d6f.png)

To be consistent with panel:

![image](https://user-images.githubusercontent.com/900690/86337315-396c6780-bc51-11ea-95fe-66cfed5c3f94.png)

**Comment by bpasero** [comment]
Oh just found this:

![image](https://user-images.githubusercontent.com/900690/86337364-4be6a100-bc51-11ea-824e-96d3fed33242.png)

Maybe we should have it also in the activity bar menu.

**Comment by rzhao271** [comment]
Notes for tester(s):

When right-clicking on an activity bar that is on the left, the second-last option should be "Move Side Bar Right". Upon clicking this option, the activity bar should move with the sidebar to the right.
When right-clicking on an activity bar that is on the right, the second-last option should be "Move Side Bar Left". Upon clicking this option, the activity bar should move with the sidebar to the left.
The side bar should be hidden immediately after the move if and only if it was hidden immediately before the move.

Notes for documentation:

- This issue adds to the activity bar context menu the option to move the entire side bar left or right
