### ISSUE TITLE
Terminal Broken on v1.4

### ISSUE THREAD

**Issue by jboothe** [Microsoft/vscode#10153]
Terminal window is visible but typing any command at the prompt, then pressing enter results in no results other than the same prompt. It's as if the prompt is reset each time enter is pressed.  Also the prompt is vertically aligned in the window. 

- VSCode Version: 1.4
- OS Version: OS X v10.11.6
- zsh

Steps to Reproduce:

1. Open prompt window
2. Type any command and press enter

**Comment by Tyriar** [comment]
@jboothe sorry to hear that, I have some questions to get to the bottom of this:

- Can you add a screenshot?- Any errors in the console? (Help > Toggle Developer Tools)
- Are you using oh-my-zsh?
- Did you experience this on v1.3.1? If so did you have any configuration changes recently?
- What does your settings.json file look like?

**Comment by jboothe** [comment]
![terminal-issue2](https://cloud.githubusercontent.com/assets/3723481/17423205/2199521a-5a87-11e6-9c1e-1de4b0610000.gif)

- Yes, I'm using oh-my-zsh.
- Only problems I had with 1.3.1 was scrolling back up. Seemed to be tied to node server crash would freeze the ability to scroll back up the window to review error console logging. 
- Settings is pretty thin:

```
{
    "editor.fontFamily": "Roboto Mono Light for Powerline",
    "editor.fontSize": 14,
    "editor.lineHeight": 20,
    "editor.tabSize": 2,
    "terminal.integrated.fontFamily": "Roboto Mono Light for Powerline",
    "terminal.integrated.fontSize": 14,
    "terminal.integrated.lineHeight": 16,
    
    "files.exclude": {
      "**/.git": true,
      "**/.svn": true,
      "**/.DS_Store": true,
      "**/*.js.map": true,
      "**/*.js": {"when": "$(basename).ts"}
    },

    "search.exclude": {
      "**/node_modules": false,
      "**/bower_components": true
    }
}

```

**Comment by Tyriar** [comment]
Could you open dev tools, inspect the terminal and get a screenshot of the elements? I'm mainly interested in the dimensions of `.xterm-rows` as well as the number of children it has and their contents.

**Comment by jboothe** [comment]
Here ya' go. 

![screen shot 2016-08-04 at 10 08 20 pm](https://cloud.githubusercontent.com/assets/3723481/17424250/17ac77e2-5a90-11e6-82eb-a9b819deb7f4.png)

**Comment by Tyriar** [comment]
Thanks. This setting is the issue:

```
"terminal.integrated.lineHeight": 16,
```

It's now a multiplier of fontSize, try `1` or `1.2` for example.

**Comment by jboothe** [comment]
That did the trick! Nicely done! 🚀

**Comment by Tyriar** [comment]
@jboothe same :wink: if you're interested that change was made to ensure selection was treated as a single block. It was difficult to ensure this across platforms without using a multiplier.

**Comment by jboothe** [comment]
Works for me and perhaps a better solution since it mirrors css line-height.

**Comment by jboothe** [comment]
@Tyriar you may want to look at this one too since you're familiar with my setup. 
[Issue 10221](https://github.com/Microsoft/vscode/issues/10221)
