### ISSUE TITLE
Extensions: Install Another Version... fails with golang.go

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#101509]
`Extensions: Install Another Version...` menu fails with an "Server returned 404" error. 

I think this is related to our recent extension transition. `ms-vscode.Go` -> `golang.Go` (`golang.go`) 
We've been publishing two versions since the transition.

**Comment by sandy081** [comment]
Can you please try with our latest insiders and see if it works?

**Comment by hyangah** [comment]
Thanks! It works in the latest insiders.

**Comment by sandy081** [comment]
Cool. Fix will be available in next stable.
