### ISSUE TITLE
Authentication through work proxy

### ISSUE THREAD

**Issue by peters225** [microsoft/vscode#101545]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Hi

At work, the infrastructure team have implemented a new network security solution and all apps go through the proxy solution.

Before this new solution I was able to connect to my Salesforce Orgs, however I now get ERROR running force:org:open:  read ECONNRESET errors when trying to connect to the various Salesforce orgs.

I have tried various solution by setting http.proxy variable, updating the windows variables and working directly with the networking team.

Can someone please help 

Thanks
Pete

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
xml|Dot|2.5.0
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.0
git-project-manager|fel|1.7.1
shell-format|fox|7.0.1
bash-extension-pack|liz|0.0.4
bash-ide-vscode|mad|1.10.2
powershell|ms-|2020.6.0
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.8
vscode-yaml|red|0.8.0
shellman|Rem|4.5.0
bash-debug|rog|0.3.9
shebang-snippets|rpi|0.1.4
salesforcedx-vscode|sal|48.21.0
salesforcedx-vscode-apex|sal|48.21.0
salesforcedx-vscode-apex-debugger|sal|48.21.0
salesforcedx-vscode-apex-replay-debugger|sal|48.21.0
salesforcedx-vscode-core|sal|48.21.0
salesforcedx-vscode-lightning|sal|48.21.0
salesforcedx-vscode-lwc|sal|48.21.0
salesforcedx-vscode-visualforce|sal|48.21.0
shellcheck|tim|0.9.0
vscode-icons|vsc|10.1.1

</details>

**Comment by chrmarti** [comment]
You only mention this in the title: Does you proxy require authentication? What type of authentication?
