### ISSUE TITLE
$end$ in snippets

### ISSUE THREAD

**Issue by exprosic** [microsoft/vscode#101521]
It would be nice to have `$end$` for snippets as in [Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets-schema-reference?view=vs-2019) behaving like `$1` but without a gray background after being inserted.

**Comment by jrieken** [comment]
We support the textmate snippet syntax and in there `$end$` would be the value of the variable called`$end` and the `$` character.
