### ISSUE TITLE
Custom Editor overrides default text editor reopen

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#101541]
- VSCode Version: 1.47 Insiders
- OS Version: macOS

Steps to Reproduce:

1. Vanilla VS Code without Custom Editor extensions
2. Install GitHub Issue Notebook
3. Create a `*.github-issues` notebook, double click the tab (or modify it) to pin it
4. Run command `Reopen Editor With ...`, and open in text editor. The text editor will be opened in a new tab ✅ 
5. Install Hex Editor, repeat above 1-4. Custom Editor overrides the default text editor open handler, and it replaces the notebook editor tab with the text editor tab.

cc @kieferrm you might see different "Reopen Editor with..." behaviors depending on if you have custom editors installed.

Does this issue occur when all extensions are disabled?: No

**Comment by rebornix** [comment]
We already had https://github.com/microsoft/vscode/blob/bbaabb52ff3e5f2ad67aa272607a3d07d04b1e2f/src/vs/workbench/services/editor/common/editorOpenWith.ts#L139-L154 so I suggest we remove the `text editor` handler in Custom Editor.

**Comment by mjbvz** [comment]
@rebornix I'm concerned about making this change late in the iteration. Would it be ok fix it in July instead?

**Comment by rebornix** [comment]
Agree that it might be too late, let's move it to July. IIRC the default behavior of reopening file in text editor in Custom Editor is always Replace Tab.

**Comment by mjbvz** [comment]
I have a local fix for this. However it looks like there is now a bug for notebooks (and custom editors). After steps 1-4, I have two tabs open but I cannot switch to the second one tab

<img width="633" alt="Screen Shot 2020-09-18 at 12 28 17 PM" src="https://user-images.githubusercontent.com/12821956/93637419-702d6080-f9aa-11ea-9cab-588309b26139.png">
