### ISSUE TITLE
Need option to minimize Exception (including shortcut)

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#101532]
After Exception we have something like this:
![VSC_debuger_](https://user-images.githubusercontent.com/25403861/86278911-6ed56e80-bbd9-11ea-8339-a8537f364456.png)

But when we trying repair code, modify, then this layer doing problems if some part of code is upper, and other in down. 
My idea is to made "indention" for exception and offer some icon to control layer to minimize/maximize (eq. yellowe arror)
![VSC_debuger_1](https://user-images.githubusercontent.com/25403861/86278974-890f4c80-bbd9-11ea-9e6b-d48ea4f50e6b.png)
This same by some shortcut (on/off layer) and the result what I'm expecting
![VSC_debuger_2](https://user-images.githubusercontent.com/25403861/86279020-a3492a80-bbd9-11ea-95e4-886c7786b989.png)

Other ideas
![VSC_debuger_2a](https://user-images.githubusercontent.com/25403861/86279791-ddff9280-bbda-11ea-9977-f5dc7681317d.png)
![VSC_debuger_2b](https://user-images.githubusercontent.com/25403861/86279795-e061ec80-bbda-11ea-8837-20ad969a40ce.png)
![VSC_debuger_2c](https://user-images.githubusercontent.com/25403861/86279802-e2c44680-bbda-11ea-9663-3e5a876250b1.png)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by ManPython** [comment]
@isdorn I hope that is possible to made here more improvements
https://github.com/microsoft/debugpy/issues/321
Debuging is still hell here

**Comment by ManPython** [comment]
The Pylance have something like this for `Problems`
![VSC_debuger_3](https://user-images.githubusercontent.com/25403861/86914085-fe21db00-c11f-11ea-8b0d-cb2bc54fc086.png)

This aditional btn as minimize next to close can be ok with shortcuts as up,down, minimize, close
![VSC_debuger_3a](https://user-images.githubusercontent.com/25403861/86914153-172a8c00-c120-11ea-87aa-ea1269844500.png)

**Comment by ManPython** [comment]
@isidorn  Take look nowe as upper
@alexr00 want corupt MS to realise this in this way : )
Need more Kansei.

**Comment by ManPython** [comment]
This must be re-open and resolved. Current solution is really stupid and no kansei, etc.
