### ISSUE TITLE
debug not work after "run without debugging"

### ISSUE THREAD

**Issue by atreeyang** [microsoft/vscode#101597]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

create a simple python file, 
and set a breakpoint

1.click run->run without debugging
2.click run->start debugging

the breakpoint not  work.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|32.00GB (6.25GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.5.1
vscode-markdownlint|Dav|0.36.1
beautify|Hoo|1.5.0
vscode-docker|ms-|1.3.1
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.6.91350
cpptools|ms-|0.28.3
debugger-for-chrome|msj|4.12.8
vscode-spring-boot|Piv|1.19.0
java|red|0.63.0
vscode-yaml|red|0.8.0
markdown-preview-enhanced|shd|0.5.12
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
vim|vsc|1.14.5
markdown-all-in-one|yzh|3.1.0
material-theme|zhu|3.8.2

</details>

**Comment by isidorn** [comment]
I just tried this with python and I can not reproduce with vscode insiders
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by atreeyang** [comment]
it is worked with vscode insiders

**Comment by weinand** [comment]
@atreeyang thanks for verifying that this problem is fixed in Insiders (which will become Stable next week).
