### ISSUE TITLE
Internet issues with VS App on Ipad

### ISSUE THREAD

**Issue by TheKingsNQueensProject** [microsoft/vscode#101518]
Hi I been using the vs app for a couple months now, and since I don’t have a pc. I code on my iPad Pro 2020. Now the app usually works fine it’s a bit buggy, but for the pass few days I been having a internet connection problem and my internet is fine. The app just keeps telling me to reload the window. I’ve falling behind on a lot of work because this is my only coding editor. Is it possible to fix this problem?

**Comment by rebornix** [comment]
@sbatten the reconnection window is too aggressive

**Comment by sbatten** [comment]
@alexdima as he handles the eventing for reconnect

**Comment by alexdima** [comment]
@TheKingsNQueensProject Can you please describe what exact steps you are doing?
