### ISSUE TITLE
Switching between tabs takes 2 o 3 seconds

### ISSUE THREAD

**Issue by oscarlvp** [microsoft/vscode#101544]
Issue Type: <b>Performance Issue</b>

Switching between tabs takes 2 or 3 seconds. Happens anytime under any conditions, with or without disabling extensions, for large or even very small files and any workspace.
I ran the profiling tools for nearly 30 seconds and switched tabs several times. The full recorded profile is here: [Profile-20200701T231959.json.zip](https://github.com/microsoft/vscode/files/4860642/Profile-20200701T231959.json.zip)

This issue seems to be related to #59094.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 4.19.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2883)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.69GB (3.38GB free)|
|Process Argv|--disable-extensions --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   126	 13694	code main
    0	    31	 13696	   zygote
    0	    87	 13721	   gpu-process
    0	    47	 13734	   utility
    0	   236	 13742	   window (b.txt - Visual Studio Code)
    0	    94	 13779	     extensionHost
    0	   165	 13828	   window (Code)
    0	     0	 14307	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 14308	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	   110	 14230	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions disabled

**Comment by bpasero** [comment]
Thanks for the profile, but I am not seeing information there that could help understand the issue. 

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by oscarlvp** [comment]
The problem can be reproduced with the insider version.

Here is the profile:

[Profile-20200707T103307-insider.json.zip](https://github.com/microsoft/vscode/files/4883600/Profile-20200707T103307-insider.json.zip)
As before I switched tabs several times using a folder with a few files and only two small text files open.

On a side note the issue does not happen with the same VSCode version on the same machine in Windows.

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by oscarlvp** [comment]
No, still the same with or without the option.

**Comment by bpasero** [comment]
@oscarlvp how about using your normal web browser and try on https://vscode-web-test-playground.azurewebsites.net/?enter=true

**Comment by oscarlvp** [comment]
@bpasero same behavior there.

**Comment by bpasero** [comment]
Ok so this seems at least VSCode Electron unrelated. I cannot explain this and cannot provide further help, sorry.

**Comment by oscarlvp** [comment]
@bpasero thanks a lot for the support.
