### ISSUE TITLE
References list shows focus and selection

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101517]
Steps to Reproduce:

1. find references
2. click on a result

=> 🐛  somehow even though an item is selected, the entire list shows blue outline

![image](https://user-images.githubusercontent.com/900690/86266460-8b67ab80-bbc5-11ea-8fe7-c47d8f4fe239.png)

**Comment by bpasero** [comment]
Hm, this no longer reproduces for me anymore after a window reload, not sure what was going on. I had a notebook open as well...

**Comment by joaomoreno** [comment]
> Hm, this no longer reproduces for me anymore after a window reload, not sure what was going on. I had a notebook open as well...

Let me know if you can!
