### ISSUE TITLE
Code Helper (Renderer) uses 100% of CPU in background but nothing is open

### ISSUE THREAD

**Issue by esprehn** [microsoft/vscode#101555]
- VSCode Version: May 2020 (version 1.46)
- OS Version: OS X 10.15.5 (19F101)

Steps to Reproduce:

1. Use VSCode for a while
2. 100% CPU usage even though no tabs are open.

Strangely the process explorer for VSCode doesn't show the process, but Activity Monitor shows it owned by the extensionHost. It seems like VSCode doesn't know about this process anymore even though it belongs to it and is using 100% of the CPU.

![Screen Shot 2020-07-01 at 5 46 34 PM](https://user-images.githubusercontent.com/415779/86304350-74c05500-bbc3-11ea-9640-dbe76f31b017.jpg)

[CPU-20200702T005008.014Z.cpuprofile.txt.zip](https://github.com/microsoft/vscode/files/4861389/CPU-20200702T005008.014Z.cpuprofile.txt.zip)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by esprehn** [comment]
Note in the above attached screenshot that the process using 100% of the CPU is not in the VSCode Process Explorer, but has the pid of the extensionHost as the parent.

Here's a sample from Activity Monitor that shows it's running a lot of JS in that process.

[Sample of Code Helper (Renderer).zip](https://github.com/microsoft/vscode/files/4861392/Sample.of.Code.Helper.Renderer.zip)

**Comment by JacksonKearl** [comment]
/needsMoreInfo

Could you use this guide to help narrow down the cause? https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by esprehn** [comment]
@JacksonKearl per my bug report whatever extension this is doesn't show up in any of the tools because it's not connected anymore. I did attach a profile, and but the Process Explorer and other tools don't show the runaway process.

**Comment by fortinmike** [comment]
I also see this bug. Same repro steps. I did not notice this being an issue until recently.

macOS Catalina 10.15.6 (19G73)
VS Code 1.47.3

I can add that the processes stay alive and at 100% CPU **even after VS Code is quit completely**:

![Screen Shot 2020-07-30 at 11 34 10 AM](https://user-images.githubusercontent.com/118257/88955984-b0a21500-d26a-11ea-81b4-91706d822bf4.png)

In the above screenshot, I have only one stray process running, but just this morning I had the exact same issue, but with two processes taking 100% CPU each.

**Comment by JacksonKearl** [comment]
@deepak1556 maybe you can make some sense of these cpu profiles?

**Comment by deepak1556** [comment]
@esprehn thanks for the process sample, I have not been successful analyzing the sample trace. Here is the dsym download link https://electron.blob.core.windows.net/builds/7.3.1/vscode/4994287/electron-v7.3.1-darwin-x64-dsym.zip incase you would like to try.

If the issue still continues to happen with latest insiders https://code.visualstudio.com/insiders/, can you re-record the trace using `Instruments.app > Time Profiler`, choose the offending process to trace 

<img width="697" alt="Screen Shot 2020-07-30 at 5 34 29 PM" src="https://user-images.githubusercontent.com/964386/88987559-2ddd8200-d28b-11ea-9268-be5ded4a25ef.png">

Load the symbols from `File menu > Symbols`, here are the download links

For insiders with `9.1.0` electron runtime https://electron.blob.core.windows.net/builds/9.1.0/vscode/5372887/electron-v9.1.0-darwin-x64-dsym.zip

For insiders with `7.3.2` electron runtime https://electron.blob.core.windows.net/builds/7.3.2/vscode/5445046/electron-v7.3.2-darwin-x64-dsym.zip

With symbols loaded, save and attach the trace.

@fortinmike please do the same, thanks!

**Comment by webOS101** [comment]
I also see a lot of these proesses.  Here's a sample of some interesting ones:
```
15960 ??         0:00.17 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) -e var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}}); 
15961 ??         0:00.16 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) -e var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}}); 
15962 ??         0:00.18 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) -e var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}}); 
15963 ??         0:00.16 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) -e var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}}); 
15964 ??         0:00.17 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) -e var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}}); 
15965 ??         0:00.16 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) -e var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}}); 
15966 ??         0:00.16 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) -e var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}}); 
15967 ??         0:00.15 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) -e var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}}); 
15968 ??         0:00.15 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) -e var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}}); 
15969 ??         0:00.00 (Code Helper (Ren)
83061 ??       261:56.81 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Users/RoySutton/.vscode/extensions/dbaeumer.vscode-eslint-2.1.8/server/out/eslintServer.js --node-ipc --clientProcessId=83050
```

VS Code is not running.  I often see the Code Helper process taking up 100% or more of CPUs and shutting down VS Code usually cleans that up.  It's not really helpful that have to do it, but I discovered today that there are a lot of lingering processes even after shutting down VS Code

**Comment by deepak1556** [comment]
@webOS101 those processes are not from the core, some extension is spawning child process to do a node script evaluation `node -e var p = process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else if(m.c==='rs'){try{var r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});` using the helper executable. Does you see the process when you run with `--disable-extensions` ? can you try narrowing down the faulty extension ?

**Comment by fortinmike** [comment]
Maybe figuring out which extensions we have in common might be a good start to find out which one causes this? Here are mine, minus themes (as listed in `~/.vscode/extensions`):

```
IBM.output-colorizer-0.1.2
Tyriar.lorem-ipsum-1.2.0
albymor.increment-selection-0.2.0
alekseychaikovsky.line-jumper-0.1.0
andrewvallette.zeonica-1.2.0
ankitcode.firefly-3.0.1
ariaminaei.vscode-jump-to-counterpart-0.0.1
bierner.markdown-preview-github-styles-0.1.6
cesium.gltf-vscode-2.2.12
codezombiech.gitignore-0.6.0
coenraads.bracket-pair-colorizer-2-0.2.0
dbaeumer.vscode-eslint-2.1.8
deerawan.vscode-dash-2.4.0
drknoxy.eslint-disable-snippets-1.2.0
eamodio.gitlens-10.2.2
editorconfig.editorconfig-0.15.1
eg2.vscode-npm-script-0.3.13
enkia.tokyo-night-0.6.1
esbenp.prettier-vscode-5.1.3
eserozvataf.one-dark-pro-monokai-darker-1.1.0
fabiospampinato.vscode-statusbar-debugger-2.0.6
felipe.nasc-touchbar-1.12.0
formulahendry.auto-close-tag-0.5.8
formulahendry.auto-rename-tag-0.1.4
geobomatic.dark-plus-one-monokai-0.2.0
github.vscode-pull-request-github-0.18.0
gruntfuggly.shifter-0.0.6
heaths.vscode-guid-1.4.20
hediet.vscode-drawio-0.7.2
humao.rest-client-0.24.1
ionutvmi.path-autocomplete-1.15.0
jakob101.relativepath-1.4.0
jock.svg-1.3.8
jpoissonnier.vscode-styled-components-0.0.29
kelvienhidayat.vscode-hue-1.3.1
maptz.template-string-expander-0.0.6
mariusschulz.yarn-lock-syntax-0.1.3
marqu3s.aurora-x-2.0.0
mechatroner.rainbow-csv-1.7.1
mhutchie.git-graph-1.25.0
ms-dotnettools.csharp-1.22.1
ms-mssql.mssql-1.9.0
ms-vscode.hexeditor-1.2.1
ms-vscode.wordcount-0.1.0
msjsdiag.cordova-tools-1.9.5
msjsdiag.debugger-for-chrome-4.12.9
nmsmith89.incrementor-0.1.0
ow.vscode-subword-navigation-1.2.0
rebornix.ruby-0.27.0
redhat.vscode-xml-0.13.0
sandcastle.vscode-open-0.1.0
sburg.vscode-javascript-booster-14.0.1
sidneys1.gitconfig-2.0.1
stkb.rewrap-1.13.0
unity.unity-debug-2.7.5
visualstudioexptteam.vscodeintellicode-1.2.9
wayou.vscode-todo-highlight-1.0.4
wingrunr21.vscode-ruby-0.27.0
xabikos.javascriptsnippets-1.8.0
yzhang.markdown-all-in-one-3.2.0
```

**Comment by webOS101** [comment]
I missed the response earlier!  My list is quite a bit smaller:
```
artdiniz.quitcontrol-vscode-3.1.3
auchenberg.vscode-browser-preview-0.6.7
coenraads.bracket-pair-colorizer-2-0.2.0
dbaeumer.vscode-eslint-2.1.8
eamodio.gitlens-10.2.2
eg2.vscode-npm-script-0.3.13
fabiospampinato.vscode-todo-plus-4.17.1
github.vscode-pull-request-github-0.18.0
mrmlnc.vscode-duplicate-1.2.1
ms-vsliveshare.vsliveshare-1.0.2478
msjsdiag.debugger-for-chrome-4.12.9
pkief.material-icon-theme-4.2.0
shardulm94.trailing-spaces-0.3.1
stkb.rewrap-1.13.0
streetsidesoftware.code-spell-checker-1.9.0
ziyasal.vscode-open-in-github-1.3.6
```

Common plugins:
```
coenraads.bracket-pair-colorizer-2-0.2.0
dbaeumer.vscode-eslint-2.1.8
eamodio.gitlens-10.2.2
eg2.vscode-npm-script-0.3.13
github.vscode-pull-request-github-0.18.0
msjsdiag.debugger-for-chrome-4.12.9
```

**Comment by webOS101** [comment]
I did a `grep` for the offending string and, per my expectation, found it in the `eslint` plugin:
```
./dbaeumer.vscode-eslint-2.1.8/server/out/eslintServer.js
```

cc: @dbaeumer

**Comment by dbaeumer** [comment]
That process should only have a very short life. It is used to resolve the eslint node module. @webOS101 can you reproduce this?

**Comment by webOS101** [comment]
I can't reproduce the lost processes at will.  I'm not sure what triggers it.  The pegged CPU while VS Code is open is easy to reproduce.  I suspect, maybe, after the process gets pegged, it might be possible to trigger the other somehow but I haven't figured out reproduction steps.

**Comment by Sixthdim** [comment]
I too am having this issue several times per day. Here is my bug report paste:


Issue Type: <b>Bug</b>

Hi! I have been running into this issue several times a day on my Mac where the "Code Helper (Renderer)" process gets stuck using 100% CPU and my fans go into jet engine mode. This usually happens when I switch between Git branches. When this does happen, I lose the ability to "Go to Definition" or "Peek" within my code. To fix the issue, I need to quit VS Code and force quit the helper process from Inspector. The code I'm working in is mostly TypeScript. Thanks!

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 10, 10|
|Memory (System)|16.00GB (2.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-rename-files|alf|2.0.0
ng-template|Ang|0.1000.8
json-tools|eri|1.0.2
seito-openfile|Fr4|1.8.7
duplicate-module|Leo|0.0.3
code-spell-checker|str|1.9.0
gitblame|wad|4.2.0
vscode-open-in-github|ziy|1.3.6


</details>

**Comment by MrBokeh** [comment]
Yup, the **Code Helper (Renderer)** process is causing my quad-core 15-inch MacBookPro running 100% with 95-99 degrees Celcius which I have to use the insider's edition for now. I thought my trusty old mac gets hacked by crypto miners...

**Comment by eickler** [comment]
Thanks for the hint regarding eslint. I had the same issue and disabling the eslint extension solved it for me.

**Comment by RHammond2** [comment]
I am having this same issue, and have had it across multiple versions of both macOS and VSCode, but my current versions are: macOS 10.14.6 and VSCode version 1.49.2. I typically work with Python.

Shutting off extensions doesn't seem to do anything, but restarting the whole app seems to work most of the time, but it starts up again once I start writing any code.

**Comment by mkaaaf** [comment]
Hello, I just had this problem with VS Code.
Happy (or horrified) to see that it's a known issue for one year now.

For your information, I just had this cpu eater process which have used like 30% of battery life in like 10 min, on a brand new MacBook 16', with a fresh install of VS Code, with absolutely 0 extensions installed.

VS Code version: 1.51.1
OS: Darwin x64 19.6.0

I need VS Code to work as it's the only code editor I like out there (like many people I think)

**Comment by esprehn** [comment]
We see this happen almost always after an `npm install` (or `yarn install`) and have mitigated it by killing the VSCode process in the postinstall script in package.json:

```bash
  # Kill VSCode's TypeScript server on post-install to avoid high CPU usage from changing many files at once.
  # VSCode will auto-restart the TypeScript server.
  ps -eo user,pid,command | grep "$(pwd)/node_modules/typescript" | grep vscode | tr -s ' ' | cut -d' ' -f2 | xargs -I{} kill {} || true
```

Recently it seems like the TS Language Server itself is what gets pegged at 100% forever, but if we kill it then it comes back immediately and doesn't use 100% of the CPU forever.

@deepak1556 what would be the best thing to share when the VSCode processes are in a runaway state?

**Comment by deepak1556** [comment]
@mjbvz can you have to look at the memory consumption of TS language server reported in above comment.

 > what would be the best thing to share when the VSCode processes are in a runaway state?

@esprehn if you can capture the system trace of the process using the following command and send it to Deepak.Mohan@microsoft.com, it would be a good place to start.

```
xcrun xctrace record --template 'System Trace' --output <some-path>/code_system.trace --attach <pid>
```

**Comment by mjbvz** [comment]
If you are seeing an problem related to TS server, please open a new issue
