### ISSUE TITLE
Unresolved placeholder in message text after install of an extension

### ISSUE THREAD

**Issue by kthoms** [Microsoft/vscode#10151]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.5 El Capitan

Steps to Reproduce:

1. Locale German
2. Manually install a .vsix extension with File / Open 
3. Message "{0} wurde erfolgreich installiert. Führen Sie zur Aktivierung einen Neustart aus." is displayed.

It is expected that {0} is replaced by the extension name.

![screenshot 24](https://cloud.githubusercontent.com/assets/265597/17421392/bccb4aa0-5aa9-11e6-99fa-f920b6120c8a.png)

**Comment by dbaeumer** [comment]
Looks like the extension name is not fill in / passed.

**Comment by joaomoreno** [comment]
Already fixed:

https://github.com/Microsoft/vscode/blob/master/i18n/deu/src/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchExtension.i18n.json#L11
