### ISSUE TITLE
codespace multiple client connection at once was failed

### ISSUE THREAD

**Issue by ilatree** [microsoft/vscode#101548]
Issue Type: <b>Bug</b>

i have been using visual studio codespaces in development
most of experience was very satisfied but,
if i opened multiple codespaces windows at once, 
only single connection was suceed, and others was failed
so i had to do one connection at the time after previous connection finished

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 5.3.0-1028-azure
Remote OS version: Linux x64 5.3.0-1028-azure
Remote OS version: Linux x64 5.3.0-1028-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.92GB (8.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: playauto|
|OS|Linux x64 5.3.0-1028-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (4 x 2693)|
|Memory (System)|7.75GB (0.64GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: playauto|
|OS|Linux x64 5.3.0-1028-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (4 x 2693)|
|Memory (System)|7.75GB (0.64GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: playauto|
|OS|Linux x64 5.3.0-1028-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (4 x 2693)|
|Memory (System)|7.75GB (0.64GB free)|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
project-manager|ale|11.1.0
angular1-code-snippets|ale|0.0.3
vscode-babel-coloring|dza|0.0.4
vscode-firefox-debug|fir|2.9.0
vscode-peacock|joh|3.7.2
angular1-code-snippets-johnpapastyle|lpe|0.1.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.3.1
network-edge-devtools|ms-|1.0.0
vscode-edge-devtools|ms-|1.0.7
remote-containers|ms-|0.122.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
vsonline|ms-|1.0.2427
debugger-for-chrome|msj|4.12.8
debugger-for-edge|msj|1.0.15
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|10.1.1
Bookmarks|ale|11.3.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.2
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.17.0
beautify|Hoo|1.5.0
chat|kar|0.35.0
vscode-kubernetes-tools|ms-|1.2.1
mssql|ms-|1.9.0
azure-account|ms-|0.8.11
cpptools|ms-|0.28.3
vsliveshare|ms-|1.0.2427
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
vsonline|ms-|1.0.2427
reload|nat|0.0.6
java|red|0.63.0
vscode-xml|red|0.12.0
vscode-yaml|red|0.8.0
vscodeintellicode|Vis|1.2.9

</details>

**Comment by dbaeumer** [comment]
@chrisdias do you know to whom to forward?

**Comment by chrisdias** [comment]
https://github.com/MicrosoftDocs/vsonline/issues

**Comment by chrisdias** [comment]
however i don't have permissions to transfer there...

**Comment by chrisdias** [comment]
@dbaeumer what's the process to transfer an issue?

**Comment by dbaeumer** [comment]
If we can't transfer it we ask the creator to create a new one in the target repository.

**Comment by chrisdias** [comment]
@ilatree can you please open an issue at https://github.com/microsoftdocs/vsonline/issues?
