### ISSUE TITLE
VS Code stops debugging after running "run without debug for the first time"

### ISSUE THREAD

**Issue by nirothehero1983** [microsoft/vscode#101534]
1.Debug you're code (.net Core project)
2.After debugging run the code using "Run without debugging".
3.Select debug again -> debug will not work.

As a workaround if I select a diffrent "Run" in the top left screen of vs code, and then select my code (.net core application) debug will work again.

This is a basic feature bug which needs to be fixed ASAP.

**Comment by weinand** [comment]
What version of VS Code are you using?

Please read our guidelines for how to create a good bug report here: https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by nirothehero1983** [comment]
> What version of VS Code are you using?
> 
> Please read our guidelines for how to create a good bug report: https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
> If you file a bug report from within VS Code (see menu: Help > Report Issue), it will provide most of the required information automatically.

 1.46.1
Mac.

Iv'e actually used the tool and this is the copy paste option it gave me.

**Comment by nirothehero1983** [comment]
CPUs | Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 32.00GB (12.38GB free)
Process Argv |  
Screen Reader | no
VM | 0%




Extension	Author (truncated)	Version
csharp	ms-	1.22.1
code-spell-checker	str	1.9.0

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by nirothehero1983** [comment]
> Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

I can confirm that this seems resolved in the VS code insiders.

**Comment by isidorn** [comment]
Thanks, thus closing this
