### ISSUE TITLE
Cannot search and view symbols in outline that are inside export default object in 1.47.0

### ISSUE THREAD

**Issue by kliput** [microsoft/vscode#101570]
**IMPORTANT NOTE:**

This is not a duplicate of [#94630](https://github.com/microsoft/vscode/issues/94630) - this issue was not fixed in TypeScript [#37877](https://github.com/microsoft/TypeScript/issues/37877) although it was marked as fixed.

It was not working in any stable release since first bug report ([#94630](https://github.com/microsoft/vscode/issues/94630)).

See this comment for details: https://github.com/microsoft/TypeScript/issues/37877#issuecomment-644516684

- VSCode Version: Version: 1.47.0-insider
- OS Version: Darwin x64 18.5.0

Steps to Reproduce:

1. Create JS file with content:

```javascript
export default {
  foo: 1,
};
export const hello = {
  world: 2,
};
```

2. The code outline and symbol search (Ctrl+Alt+O) will show: default, hello, world (nested), while it should (as in previous VSCode versions): default, foo (nested), hello, world (nested) - foo is missing, as well as other symbols if they were put inside default symbol.

![obraz](https://user-images.githubusercontent.com/1345438/86329708-d70e6980-bc46-11ea-9e7d-2787a395ed7b.png)

Screenshot from newest Insiders VSCode:

![obraz](https://user-images.githubusercontent.com/1345438/86329534-944c9180-bc46-11ea-8507-c4f20373d691.png)

**Comment by mjbvz** [comment]
This is fixed in TypeScript 4.0 which is not included in VS code 1.46. Try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Comment by kliput** [comment]
It is not working with TypeScript 4.0

![obraz](https://user-images.githubusercontent.com/1345438/86445948-887ad100-bd13-11ea-8a9a-f47aad73bbae.png)

![obraz](https://user-images.githubusercontent.com/1345438/86446072-b95b0600-bd13-11ea-973c-fd7585f20c55.png)

As you can see on screenshot, there should be `store`, `onedataGraph`, etc. in outline.

Please reopen the issue.

**Comment by mjbvz** [comment]
Your example of it not working is significantly different than  #94630 and the example you first provided (it exports the result of a function call instead of an object literal or class)

If you want to see that supported, please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) against TypeScript
