### ISSUE TITLE
Visual Studio Code for mac same key bindings a VS on windows

### ISSUE THREAD

**Issue by ekrogh** [microsoft/vscode#101515]
Issue Type: <b>Feature Request</b>

You can set Visual Studio on mac to use same key bindings as Visual Studio on windows.

It would be nice if you could configure Visual Studio Code on mac + windows  to use the same key bindings as Visual Studio on Windows.

Best,
 Eigil

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

**Comment by JacksonKearl** [comment]
Does this help? https://marketplace.visualstudio.com/items?itemName=ms-vscode.vs-keybindings
