### ISSUE TITLE
When debugging vscode, a couple of console windows open for a short time

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#101543]
I remember this happening in the past, but I haven't seen this in a long time, but it started today.

Debugging the current vscode `master` branch in today's insiders build, each time I hit F5 (using the `VS Code` launch config), I see a couple of console windows open up for a short time then disappear.

**Comment by deepak1556** [comment]
Do you see this issue with latest master ?

**Comment by eamodio** [comment]
Not anymore, it seemed to only happen with the old debugger.
