### ISSUE TITLE
Pixiedust produces no images/graphs

### ISSUE THREAD

**Issue by MuSamiNaf** [microsoft/vscode#101547]
- VSCode Version: 1.46.1
- OS Version: Windows 10 x64 18362

Steps to Reproduce:

1. Running Pixiedust does not produce any images/graphs in Python Notebooks.
2. Pixiedust  works with  browser-based Jupyter Notebooks.

Does this issue occur when all extensions are disabled?: Yes/No **Yes**

**Comment by rebornix** [comment]
Please file issue against the Python extension you are using.
