### ISSUE TITLE
"Code ." opens a Cli.js and hooks my terminal to electron's session

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#101506]
- VSCode Version:
I can't even get the VSCOde version from the cli anymore...
![image](https://user-images.githubusercontent.com/55927613/86248127-5c414200-bba5-11ea-9797-75d50d5ac240.png)

- OS Version: Windows  10

Steps to Reproduce:

I just run code . and it opened a cli.js file and did that to my terminal.
![image](https://user-images.githubusercontent.com/55927613/86247938-197f6a00-bba5-11ea-8ef1-5fe36c55b3eb.png)

![image](https://user-images.githubusercontent.com/55927613/86248032-374ccf00-bba5-11ea-9f29-453c70b0a217.png)

**Comment by deepak1556** [comment]
Use `code.cmd` instead.

**Comment by AllanOricil** [comment]
I have two computers and this behavior only happens in one of them. Both run windows 10.

**Comment by AllanOricil** [comment]
Could somebody reopen this issue, please.

I tried with both code and code.cmd and the result was the same in one of my pcs

![image](https://user-images.githubusercontent.com/55927613/98245672-32d85e80-1f69-11eb-8fd9-51de47a1c62f.png)

**Comment by deepak1556** [comment]
Can you set `ELECTRON_NO_ATTACH_CONSOLE` environment variable and see if the issue is present ?

**Comment by AllanOricil** [comment]
@deepak1556 it did not work. The logs are now surpressed, but the behavior is still there.

![image](https://user-images.githubusercontent.com/55927613/98379038-badc6800-203e-11eb-9a2b-e68ea12e02d9.png)

**Comment by AllanOricil** [comment]
@deepak1556 another thing it can help you to find a solution. Some folders seems to not hook with an electron session. But when I open the project it displays that "cli.js" file. Could it be some kind of permission ? All these weird behaviors only happen on the company's laptop.

![image](https://user-images.githubusercontent.com/55927613/98932525-5a827600-24d7-11eb-851b-5346c7343849.png)

**Comment by AllanOricil** [comment]
@deepak1556 is there anything I can do to help you to better understand what is happening? Maybe there are some debug logs that are being saved by vscode that I can share with you? if so, help me to help you. Thanks

**Comment by AllanOricil** [comment]
@deepak1556 could you tell me when this is planned to be fixed?

**Comment by deepak1556** [comment]
Can you provide the output `get-command -All code`

Do you see this issue with insiders https://code.visualstudio.com/insiders ?

**Comment by AllanOricil** [comment]
> Can you provide the output `get-command -All code`
> 
> Do you see this issue with insiders https://code.visualstudio.com/insiders ?

![image](https://user-images.githubusercontent.com/55927613/101166119-abe1d900-362f-11eb-9a20-36fdfb8a6a2a.png)

@deepak1556 How do I a folder/file using the VSCOde Insiders version in the terminal? With the standard vscode I use `code`. What about the insiders version?

**Comment by deepak1556** [comment]
Thanks for confirming, can you uninstall the stable and retry installing again ?

**Comment by AllanOricil** [comment]
@deepak1556 I uninstalled vscode and installed again and the error is gone partially. Now when I open any repository I still see the file called cli.js but code no longer binds the session to that terminal. But the weird thing is that Im still on v1.51.1.  I will wait until v1.52 to see what happens.

![image](https://user-images.githubusercontent.com/55927613/101347059-6288c800-3881-11eb-96c5-5b30251db7d8.png)

![image](https://user-images.githubusercontent.com/55927613/101347132-821ff080-3881-11eb-871f-e12a202a6bb7.png)

On the insider version this behavior is not happening.

**Comment by reecebradley** [comment]
I have this installed:
```
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
```

I execute "code ." in my dev folder and I get cli.js opened and my prompt is tied up with debug info
![image](https://user-images.githubusercontent.com/1536861/104023728-ad9b4100-5187-11eb-9601-d7890eb88d87.png)

**Comment by AllanOricil** [comment]
> I have this installed:
> 
> ```
> Version: 1.52.1 (system setup)
> Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
> Date: 2020-12-16T16:34:46.910Z
> Electron: 9.3.5
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT x64 10.0.18363
> ```
> 
> I execute "code ." in my dev folder and I get cli.js opened and my prompt is tied up with debug info
> ![image](https://user-images.githubusercontent.com/1536861/104023728-ad9b4100-5187-11eb-9601-d7890eb88d87.png)

this issue is kind random. I use vscode on two Windows 10 PCs and only in one the problem happens.

**Comment by AllanOricil** [comment]
It is still happening with the latest vscode version 

![image](https://user-images.githubusercontent.com/55927613/113144714-763bae00-9225-11eb-8dbe-0731493d3955.png)

**Comment by AllanOricil** [comment]
@deepak1556 I will close because I no longer have access to the computer the issue was happening. But I can't confirm it is fixed.

**Comment by deepak1556** [comment]
No worries, thanks for following up.
