### ISSUE TITLE
Nested snippets (or include snippet inside another snippet)

### ISSUE THREAD

**Issue by GlenNicholls** [microsoft/vscode#101526]
I would like the ability to have nested language snippets [like this question](https://stackoverflow.com/questions/58566363/vscode-nested-snippets-or-include-a-snippet-inside-another-snippet) or https://github.com/microsoft/vscode/issues/83690. For example, let's say I have the following language snippets:

```
{
    "VUnit Library": {
        "prefix": ["libraryvunit"],
        "body": [
            "library vunit_lib;",
            "context ${1|vunit_lib.vunit_context;,vunit_lib.com_context;|}"
        ],
        "description": "VUnit library and contexts"
    }, 
    "Testbench Instantiation": {
        "prefix": ["vunit_tb"],
        "body": [
            "library ieee;",
            "context ieee.ieee_std_context;",
            "use ieee.math_real.all;",
            "",
            "$libraryvunit"
        ],
        "description": "Instantiate a libraries"
    }
}
```

Now, when I would start typing `vunit_tb` and insert that snippet, it would insert the `libraryvunit` snippet. In this case, it would produce the following if I selected the first `libraryvunit` snippet option:

```
library ieee;
context ieee.ieee_std_context;
use ieee.math_real.all;

library vunit_lib
context vunit_lib.vunit_context;
```

In the link I shared above, it is annoying to deal with using a macro since you have to use a key binding. I feel that it makes more sense to have built-in capability for nested snippets so all you have to do is insert the snippet and if there are nested snippets, it will insert those snippets for the user. This way, they can be more powerful and reduce the typing and thought process for the user.

**Comment by GlenNicholls** [comment]
The other aspect of this issue that I would like is the ability to select multiple snippets in a list of options:

```
${1|opt1,opt2,opt3...|}
```

It would be nice if there was some way to add multiple items from this list. E.g., If I start this snippet, I might like it to insert those parts of the snippet like so:

```
opt1
opt3
```

**Comment by ArturoDent** [comment]
If you use this line: `"libraryvunit"` instead of `"$libraryvunit"` and then hit <kbd>Ctrl</kbd>+<kbd>space</kbd> you'll get the option to insert the other snippet  - because that is the prefix of the included snippet.  So you wouldn't need the macro.  

Just a workaround until nested snippets can be implemented.

**Comment by GlenNicholls** [comment]
Moved this issue to https://github.com/microsoft/vscode/issues/106132

**Comment by GlenNicholls** [comment]
@all this has moved to https://github.com/microsoft/vscode/issues/106132
