### ISSUE TITLE
vscode.workspace.getWorkspaceFolder does not check if file exists (or API documentation is not clear)

### ISSUE THREAD

**Issue by pkruk2** [microsoft/vscode#101569]
Issue Type: <b>Bug</b>

Hi,

it looks like `vscode.workspace.getWorkspaceFolder` only checks if the uri matches any of the workspace folders uri. It does not check if the file actually exists in the folder.
For example if I have workspace folder which path `C:\ps\build\engine` then `getWorkspaceFolder('C:\ps\build\engine\doesNotExist.txt')` returns this workspace folder.
In other words, following always returns the folder: `vscode.workspace.getWorkspaceFolder(vscode.Uri.file(path.join(vscode.workspace.workspaceFolders[0].uri.fsPath, "does not exists.txt")))`

It might be that current behaviour is correct. But then, the API documentation is not clear in my opinion. Currently it says:

> Returns the workspace folder that contains a given uri.
> - returns undefined when the given uri doesn't match any workspace folder
> - returns the input when the given uri is a workspace folder itself

### Actual results:

`vscode.workspace.getWorkspaceFolder`  does not check if file exists.

### Expected results:

Either:
* `vscode.workspace.getWorkspaceFolder` checks if file exists - returns only if folder actually contains the specified uri, or
* make API documentation more clear about how the function works

### System details

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
jenkinsfile-support|ivo|1.1.0
vscode-typescript-tslint-plugin|ms-|1.2.3

</details>

**Comment by bpasero** [comment]
I suggest we tweak the API docs to not break. Up for grab.
