### ISSUE TITLE
Global search and replace is inefficient and can freeze the editor

### ISSUE THREAD

**Issue by jvilk-stripe** [microsoft/vscode#101523]
- VSCode Version: 1.46.1
- OS Version: Mac OS 10.15.4

Steps to Reproduce:

1. Open VS Code in a large project with `--disable-extensions` (in this case, it's a Ruby monorepo).
2. Perform a global search-and-replace that targets >1000 files.
3. The VS Code UI freezes during this process. The renderer process pegs a CPU core. VS Code has to be force quitted.
4. Reopening VS Code with --disable-extensions freezes for minutes (long enough for VS Code to prompt you to reopen it). If you wait long enough, it unfreezes and displays hundreds of opened editors with dirty, unsaved buffers. After it is unfrozen, the editor is responsive as-normal. 

If you have linters enabled, VS Code triggers them run on each of these files. The linters I have configured only care about files open in the editor, so I'm guessing that VS Code really is opening an editor for each of these files. imo, it would be better if VS Code treated these edits as external file system changes (unless the file is already open), since the linters I have configured would ignore those changes and wouldn't further contribute to system load -- although I understand if some other constraint in the system prevents you from doing that.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Discussing this in https://github.com/microsoft/vscode/issues/89300

**Comment by jvilk-stripe** [comment]
Thanks! I did a few searches and didn't see that one.
