### ISSUE TITLE
Occasionally when resizing a panel, mouseup will resize the terminal to ~100px high

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#10156]
- VSCode Version: latest
- OS Version: Ubuntu 16.04

**Comment by Tyriar** [comment]
Repros on the problems panel so it's a generic panel issue. To reproduce just move the panel up, release mouse, then move down and repeat. Seems to happen ~5-10% of the time.

**Comment by isidorn** [comment]
I can not repro this. Do you still see this with the latest? Are you doing something different to what I am doing? I tried both OS X and Ubuntu
If you still see it on your machine 

![panel](https://cloud.githubusercontent.com/assets/1926584/18280932/3ec86b44-745b-11e6-80bb-db0637d718f6.gif)

**Comment by Tyriar** [comment]
I can't repro this anymore either so I guess it got fixed somehow :+1:
