### ISSUE TITLE
Electron 8 freezes while debugging

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#101535]
Forking from https://github.com/microsoft/vscode/issues/100368; it seems that even with the webview fix there are issues with Electron 8 freezing while debugging.

**Comment by deepak1556** [comment]
Do you think this is same as https://github.com/microsoft/vscode/issues/103124 ? Does it happen with latest insiders which is on electron 9 ?

**Comment by connor4312** [comment]
Yea, it's the same one

/duplicate
