### ISSUE TITLE
Git stash doesn't work

### ISSUE THREAD

**Issue by tegola** [microsoft/vscode#101584]
Issue Type: <b>Bug</b>

On an active repository with uncommitted changes, open the source control pane's popup menu and select "Stash", input a message and press Enter.

The app tries to run "git stash push -m <message>", but it actually needs to run "git stash save <message>".

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0
Remote OS version: Linux x64 3.10.0-327.22.2.el7.x86_64

**Comment by KyleFromKitware** [comment]
+1, I just ran into this as well

**Comment by joaomoreno** [comment]
`git stash save` is deprecated:

https://www.git-scm.com/docs/git-stash#Documentation/git-stash.txt-save-p--patch-k--no-keep-index-u--include-untracked-a--all-q--quietltmessagegt

Can you update your git version? What version do you have installed?

**Comment by KyleFromKitware** [comment]
> What version do you have installed?

2.7.4, the version that ships with Ubuntu 16.04 LTS

**Comment by joaomoreno** [comment]
Oh, that's pretty old! Can you update with `sudo apt update && sudo apt upgrade git`?

**Comment by KyleFromKitware** [comment]
Tried that, it tells me Git is already at the newest version.

Ubuntu freezes the package versions with each release (with a few exceptions, like Firefox). Ubuntu 16.04 LTS is going to continue to be supported until next year.

**Comment by joaomoreno** [comment]
Can you use Git's PPA? https://launchpad.net/~git-core/+archive/ubuntu/ppa

**Comment by tegola** [comment]
> `git stash save` is deprecated:
> 
> https://www.git-scm.com/docs/git-stash#Documentation/git-stash.txt-save-p--patch-k--no-keep-index-u--include-untracked-a--all-q--quietltmessagegt
> 
> Can you update your git version? What version do you have installed?

I was so accustomed with working with VS Code on a SMB share + local git executable that I forgot I had switched to Remote-SSH + local server's git executable, which is at version 2.9.1.

So this is fixed for me, sorry!

**Comment by KyleFromKitware** [comment]
> Can you use Git's PPA? https://launchpad.net/~git-core/+archive/ubuntu/ppa

This worked for me
