### ISSUE TITLE
Renaming case of file closes the file in editor

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10150]
- VSCode Version: 1.4.0-insiders
- OS Version: OSX

Steps to Reproduce:

1. Create file `test.tsx` (opens tab for it)
2. Rename file to `Test.tsx` 
3. Problem: VSCode closes the file (removes tab from editor)

Expected:
Tab should stay open similar if you rename `test.tsx` to `somethingelse.tsx`

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/10360
