### ISSUE TITLE
No symbols found in .c document

### ISSUE THREAD

**Issue by mingyangSunshine** [microsoft/vscode#101558]
- VSCode Version: 1.46.1
- OS Version: windows
- SSH remote OS: Ubuntu 16.04
- C/C++ extension 0.28.3

I am using remote SSH in VScode. There is always a message in the "OUTLINE" box: No symbols found in xxx.c document.
For py files, it shows the outline correctly.
If opening a local C project, it shows the outline correctly for C files.

**Comment by JacksonKearl** [comment]
\extC
