### ISSUE TITLE
*contributes* should respect *activationEvents* definition

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#10154]
When I define an extension to only activate if some file is present in the root folder (`workspaceContains`) or for certain language (`onLanguage`), I would expect that the `contributes/commands` and `contributes/menus` to respect that, and only be available if _is true_. 

But today, all `commands` defined in `package.json` are available in **Command Palette** and when I call one of them, an error appears (_Command 'myExtesion.myCommand' not found._)

Should I use another approach in this case, or is it really an issue?

Thanks for your help.

**Comment by jrieken** [comment]
That's the idea behind the declarative approach of declaring commands and menu items. The UI knows how to display a command before the extension has already been loaded. You must use the `onCommand:xyz` activation event for that case.

**Comment by alefragnani** [comment]
Related https://github.com/microsoft/vscode/issues/10401
