### ISSUE TITLE
StatusBarItem does not allow setting of AccessibilityInformation after ctor

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#101554]
refs #100936

Repro:
1. Create StatusBarItem without accessibilityInformation
2. Attempt to set accessibility information afterward e.g. `myItem.accessibilityInformation = { label: 'label' };`

:bug: => No error is thrown but the item will not be displayed properly.

**Comment by isidorn** [comment]
Assigning to June to investigate further
