### ISSUE TITLE
VScode installed from snap : command “code” not working as expected

### ISSUE THREAD

**Issue by yossefaz** [microsoft/vscode#101577]
- VSCode Version: 1.46
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1.install from :  sudo snap install code --classic
2. open from command line : code .

Does this issue occur when all extensions are disabled?: Yes

Expected behavior : the code command will open the VScode programm

What occurs instead : nothing, it just returns to a new command line without opening the program.

**Comment by joaomoreno** [comment]
What about `code --verbose`?

**Comment by yossefaz** [comment]
After reboot it runs....do you still need the verbose output ? otherwise we can close the issue
