### ISSUE TITLE
Filename in Tab does not Match Filename

### ISSUE THREAD

**Issue by jcrawford** [microsoft/vscode#101505]
We have written the needed data into your clipboard because it was too large to send. Please paste.  See my attached screenshots. Notice the screenshot that shows the name in the tree view shows `SendPoolNotification` and the classname in the file is `SendPoolNotification` and then notice in the tab it is `sendPoolNotification` .

![Screen Shot 2020-07-01 at 8 54 10 AM](https://user-images.githubusercontent.com/875341/86246275-bd065580-bb78-11ea-846b-ab30dcf1e362.png)
![Screen Shot 2020-07-01 at 8 54 27 AM](https://user-images.githubusercontent.com/875341/86246277-bd9eec00-bb78-11ea-95e2-5e5dc09253fb.png)

**Comment by gjsjohnmurray** [comment]
Maybe dup of #101040, which itself is closed as a dup.

Did you rename your file to change its case?
