### ISSUE TITLE
Panel: hiding all panels not possible and/or weird

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101592]
Steps to Reproduce:

1. right-click hide on each panel
2. the last one never hides
3. however the label seems to disappear?

![recording](https://user-images.githubusercontent.com/900690/86356195-20bd7b00-bc6c-11ea-83c4-c704150422b1.gif)

**Comment by sbatten** [comment]
seemed to be a pretty simple issue, at some point I guess visibleComposites was not updated until after the operation completed. @sandy081 to review

**Comment by sbatten** [comment]
To Verify:
follow ben's steps

**Comment by bpasero** [comment]
@sbatten one thing I wonder: given we have a UI for when the panel is truly empty, why do we not show the panel empty when you clicked "Hide" on the last panel? We now seem to always show at least one entry, but I think we could also show it completely empty?

**Comment by sbatten** [comment]
It's kind of a corner case to have nothing. Yes we could show an empty panel but it's probably not the intent of the user. The empty panel message is truly for the case where we cannot show anything but the panel is being summoned. My opinion.
