### ISSUE TITLE
Network folders don't work correctly with git integration

### ISSUE THREAD

**Issue by TeroPihlaja** [microsoft/vscode#101585]
Issue Type: <b>Bug</b>

I believe the steps to reproduce would be:

1. Mount a network drive to drive letter
2. Create a folder and git repository on the network drive
3. Modify some file contents within the repo
4.  View the "source control" section in the activity bar
5. Try to add the modified file to the repository

Expected result: File is staged correctly
Actual result: Depending on which "+" button is pressed, either nothing happens or the following error is shown:

```
fatal: x:elasticapmserver.tf: 'x:elasticapmserver.tf' is outside repository at '//tmiettin-linuxdev/tmiettin/terraform'
```

Note: ```\\tmiettin-linuxdev\tmiettin\``` has been mounted as drive ```X:\```

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
rails|bun|0.16.7
vscode-gemfile|bun|0.4.0
solargraph|cas|0.21.1
chef|che|1.7.0
bracket-pair-colorizer-2|Coe|0.1.4
gauge|get|0.0.13
gitlab-workflow|Git|3.0.3
go|gol|0.15.0
beautify|Hoo|1.5.0
vscode-github|Kni|0.30.3
prettify-json|moh|0.0.3
vscode-docker|ms-|1.3.1
mssql|ms-|1.9.0
azure-account|ms-|0.8.11
cpptools|ms-|0.28.3
powershell|ms-|2020.6.0
vetur|oct|0.24.0
ruby|reb|0.27.0
java|red|0.63.0
vscode-yaml|red|0.8.0
slim|sia|0.1.2
shellcheck|tim|0.9.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
vscode-ruby|win|0.27.0

</details>

![image](https://user-images.githubusercontent.com/8665642/86347464-ff0dc500-bc66-11ea-8609-1594f5c04dcf.png)
![image](https://user-images.githubusercontent.com/8665642/86347499-0b921d80-bc67-11ea-936d-bc7eb7d0870e.png)

**Comment by joaomoreno** [comment]
What git version do you have installed? Can you update to 2.27?
