### ISSUE TITLE
[VS Code Insider] InputBox Bug - Active webview prevents cut, copy and paste into input box

### ISSUE THREAD

**Issue by L13** [microsoft/vscode#101599]
Issue Type: <b>Bug</b>

Hi @mjbvz and @jrieken ,

I found another input focus bug.

1. Download/Install an extension with a webview like L13 Diff https://marketplace.visualstudio.com/items?itemName=L13RARY.l13-diff.
2. Open the command palette (Ctrl/Meta+Shift+P) and search for "L13 Diff" or press "Ctrl+L Ctrl+L" on Windows/Linux or "Meta+L Meta+L" on macOS.
3. If the webview is the active editor, open for example the command palette (Ctrl/Meta+Shift+P) again and try to cut, copy or paste a value into the input box -> Does not work.

If you close the active webview or the webview is not the active editor cut, copy or paste in the input box works.

This bug is not in VS Code <= 1.46.1

PS: Thank you for the previous fix #101201 

VS Code version: Code - Insiders 1.47.0-insider (b16b467d3e03e1a1ae05b5836e4e5a5af504e86d, 2020-07-01T05:30:11.898Z)
OS version: Darwin x64 19.5.0

and

VS Code version: Code - Insiders 1.47.0-insider (04545fa88043fd10d1f3edefd26be1b8245b516f, 2020-07-02T05:41:12.081Z)
OS version: Darwin x64 19.5.0

**Comment by mjbvz** [comment]
Good find!

**Comment by aeschli** [comment]
Still doesn't work for me.
Version: 1.47.0-insider
Commit: 376d9d9d785ccca128fdbb16f001446d0ad64d32
Date: 2020-07-03T10:15:57.898Z
OS: Linux x64 5.3.0-59-generic

- Install an extension https://marketplace.visualstudio.com/items?itemName=L13RARY.l13-diff.
- Ctrl+L Ctrl+L
- Select a word in one of the input boxes
![image](https://user-images.githubusercontent.com/6461412/86590143-46f65a00-bf8f-11ea-82af-2caa1b696403.png)

- Ctrl +X works, but not when running command `Cut` via command palette.

**Comment by mjbvz** [comment]
Thanks for testing @aeschli. That is a known separate issue: #101553

For this issue, please just verify that the keyboard shortcuts work when you have a webview open and then open the command palette
