### ISSUE TITLE
Debugging breaks on first line of code

### ISSUE THREAD

**Issue by vainamov** [microsoft/vscode#101581]
When debugging an application using the new js debugger preview, the debugger stops immediately on the first line on every run.

- Version: 1.47.0-insider (system setup)
- Commit: 04545fa88043fd10d1f3edefd26be1b8245b516f
- Date: 2020-07-02T05:48:37.715Z
- Electron: 7.3.2
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Create a new node application with typescript installed
2. Create a `/src/index.ts` file with any valid code
3. Use the configurations from below
4. Start the debugging

![grafik](https://user-images.githubusercontent.com/11841072/86341742-ff05c900-bc56-11ea-86af-6be069dbebd2.png)
![grafik](https://user-images.githubusercontent.com/11841072/86341783-0cbb4e80-bc57-11ea-9ff1-582c152c92de.png)

**tsconfig.json**
```json
{
    "compilerOptions": {
        "incremental": true,
        "target": "ESNEXT",
        "module": "commonjs",
        "sourceMap": true,
        "outDir": "dist",
        "tsBuildInfoFile": "./.tsc/buildInfo.json",
        "removeComments": true,
        "strict": true,
        "noImplicitAny": true,
        "moduleResolution": "node",
        "baseUrl": ".",
        "paths": {
            "*": [
                "node_modules/*"
            ]
        },
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true
    },
    "include": [
        "src/**/*"
    ]
}
```

**tasks.json**
```json
{
	"version": "2.0.0",
	"tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json",
            "option": "watch",
            "problemMatcher": [
                "$tsc-watch"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "label": "tsc: Überwachen – tsconfig.json"
        }
    ]
}
```

**launch.json**
```json
{
    // Verwendet IntelliSense zum Ermitteln möglicher Attribute.
    // Zeigen Sie auf vorhandene Attribute, um die zugehörigen Beschreibungen anzuzeigen.
    // Weitere Informationen finden Sie unter https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Programm starten",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\dist\\index.js",
            "runtimeArgs": [
                "--inspect-brk"
            ],
            "stopOnEntry": false,
            "preLaunchTask": "${defaultBuildTask}"
        }
    ]
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@vainamov you are specifying the runtimeArg  `--inspect-brk` which makes the debugger "break" on the first line.
Just remove the "runtimeArgs" array since it is not necessary.

**Comment by vainamov** [comment]
@weinand Thanks for the heads up! I'm not really sure why I added it in the first place but it works fine. Curiously though, even with only `--inspect` the debugger stops on entry.

**Comment by weinand** [comment]
Please don't specify a "--inspect" argument - the debug extension does that automatically.

**Comment by connor4312** [comment]
@vainamov thanks for the issue! Stopping on entry when only --inspect is given is unexpected. Can you enable `trace: true` in your launch config and share the logs for that?

**Comment by vainamov** [comment]
@connor4312 Sure thing! https://gist.github.com/vainamov/fac246796a0f525186a3afca23847be6

**Comment by connor4312** [comment]
In the log you sent it doesn't looks like the debugger stopped anywhere. Do you still have that issue?
