### ISSUE TITLE
javascript font color

### ISSUE THREAD

**Issue by k9282000** [Microsoft/vscode#10158]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.
![_080516_093058_am](https://cloud.githubusercontent.com/assets/3058883/17423687/52c04322-5aef-11e6-96bb-7a7c564e2c27.jpg)

MY COLOR DISAPPEAR

2.

**Comment by aeschli** [comment]
@k9282000 Can you attach the (minimal) code sample to reproduce? (so I don't need to type it off the screenshot)

**Comment by valkanov** [comment]
It is reproducible to my machine as well. 

Version 1.4.0
Commit 6276dcb0ae497766056b4c09ea75be1d76a8b679
Shell 0.37.6

Here is a sample code, that is not colored.

[sample.txt](https://github.com/Microsoft/vscode/files/403373/sample.txt)

and a screenshot of what I see

![capture](https://cloud.githubusercontent.com/assets/5782506/17430530/5748bda8-5afd-11e6-87d9-4055269e45be.PNG)

Note that  I am using Javascript Atom Grammar, but it is reproducible without it too.

**Comment by aeschli** [comment]
@valkanov What you describe is different. Please file a separate issue.

**Comment by iMasoud** [comment]
Hi,

I think I have the same problem here. After Updating to version 1.4, VSCode highlights my code only until specific line:
![screenshot from 2016-08-06 13-48-56](https://cloud.githubusercontent.com/assets/9999208/17455942/cb51606c-5bdc-11e6-9c3e-6824e0fdf9ba.png)

[app.txt](https://github.com/Microsoft/vscode/files/404948/app.txt)

**Comment by aeschli** [comment]
@iMasoud Always file a separate issue, we will mark it as duplicate if it is really the same issue.

**Comment by WangJi** [comment]
+1

**Comment by k9282000** [comment]
this is my code sample,thx
[code.txt](https://github.com/Microsoft/vscode/files/412405/code.txt)

**Comment by aeschli** [comment]
@k9282000 Thanks a lot for the code sample. I tried it the latest [insider build](https://code.visualstudio.com/insiders) and it works again. There was a grammar update that must have fixed it.

@iMasoud @valkanov Both of your issues are related to #9937
