### ISSUE TITLE
[feature request] on startup to restore the opened files (incl. unsaved files and unsaved untitled documents) of last session

### ISSUE THREAD

**Issue by darkred** [Microsoft/vscode#10152]
- VSCode Version: 1.4.0
- OS Version: win 10 x64
 
Steps to Reproduce:

1. Currently there is only this pref in User Settings related to this :

        // Controls how folders are being reopened after a restart. 
        // Select: 
        // 'none' to never reopen a folder, 
        // 'one' to reopen the last folder you worked on, or
        // 'all' to reopen all folders of your last session.
        "window.reopenFolders": "one",
i.e. VSCode can only reopen **folders** that they were open during the last session.
Also, as you quit VSCode, you get a prompt about whether you want to save unsaved files: 
in any case, in the next program launch it will open with just a new empty file (instead of your files from your last session).

2. My feature request is to add a new pref to **restore all files of your last session**: 
VSCode to periodically backup the current session, 
user won't be asked to save unsaved file as he quits VSCode, 
and on next startup VSCode to restore all files (incl. unsaved file and unsaved untitled documents) of last session. 
This feature will protect your data/work. 

Duplicate of this #8101  (most probably)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/101
