### ISSUE TITLE
Allow to enable extensions if launched "with extensions disabled" or change to "with extension host disabled"

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#101580]
At first I wanted to report a bug, but I realised it might have been intended, though it doesn't really make sense as I don't see a real usage for the current behaviour. It would intuitively make more sense if it was renamed to `Reload With Extension Host Disabled`.

![image](https://user-images.githubusercontent.com/2313018/86338884-28bcf100-bc53-11ea-8838-5e52629cb63e.png)
Unexpectedly, can't enable extensions
![image](https://user-images.githubusercontent.com/2313018/86338914-35d9e000-bc53-11ea-8186-801b02862efa.png)

I expected that `Reload with extensions disabled` is just a shortcut for
- temporarily disable all extensions (and don't actually store that in settings)
- and reload vscode so that it takes effect

but instead it reloads with extension feature disabled alltogether, which is of no use for me in fact. Being able to start enabling extensions one by one seems like the only logical action in this state as otherwise the vscode instance is useless for any specific work. **I wonder what the use case for this feature is.**

The reason I wanted to use it like this is to be able to enable extensions one by one and see which extensions interfere.

Because this didn't work as expected, I had to do this instead:
- create new workspace
- `Disable All Installed Extgensions For This Workspace`
- `Reload Window`
- start enabling extensions for this workspace

That being said, I expected that this use case will be more straight forward, supported natively and not requiring these extra steps.
If there is a workflow for this, could you please direct me? I spent an hour searching on google and wasn't able to find a definitive guide how to solve interfering extensions.

---

So please, can you give me more explanation for this feature?
Then I suggest to either
- allow enabling extensions when launched via `Reload With Extensions Disabled`
- rename `Reload With Extensions Disabled` to `Reload With Extension Host Disabled`

**Comment by sandy081** [comment]
> So please, can you give me more explanation for this feature?

This feature is to quickly check if a certain issue is caused by an extension or not.

> The reason I wanted to use it like this is to be able to enable extensions one by one and see which extensions interfere.

We already have an open feature request for your use case - https://github.com/microsoft/vscode/issues/99552

Hence marking this as duplicate.

**Comment by ackvf** [comment]
@sandy081 Thank you. Anyway, would you still consider renaming the option as per my suggestion? It is quite unexpected and confusing why it is not possible to enable extension when reloaded this way.

**Comment by sandy081** [comment]
I will probably leave it to @RMacfarlane

**Comment by ackvf** [comment]
To further extend a bit, upon reading a third time.

I get this

>This feature is to quickly check if a certain issue is caused by an extension or not.

However, when one wants to properly assess which extension causes an issue, or which set of extensions cause an issue, it is necessary to be able to enable/disable the various extensions to reproduce the issue. By not allowing to enable any extension, you effectively cut this flow away, which then makes it more or less internal only for VSCode.

This basically tells anyone "Is it VSCode issue" or "Is it caused by an extension"?
It doesn't allow us to find "Which extension causes this"


Thank you for reopening.

**Comment by RMacfarlane** [comment]
I'm going to close this issue again, because I think the current name is accurate. The extension host is still available and built-in extensions are run, only user-installed extensions are disabled.
