### ISSUE TITLE
MD preview previews markdown notebook cells

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101514]
* open a markdown file
* open the markdown preview to its side
* replace the markdown file with a notebook
* in the notebook edit a markdown cell
* :bug: the markdown preview previews the cell

<img width="811" alt="Screenshot 2020-07-01 at 17 17 44" src="https://user-images.githubusercontent.com/1794099/86261385-c87c6f80-bbbe-11ea-8eea-0ddf5cc91373.png">

@kieferrm had demoed this issue before and I am unsure if a duplicate exists or not...

**Comment by jrieken** [comment]
I believe what's happening is that the cell editor is becoming the active editor (in API term) and the the markdown preview panel reacts on that. I think that generally makes sense but only for editors that have a view column. @mjbvz is there a reason why the preview work on any editor?

**Comment by roblourens** [comment]
If I change the 'when' clause of the command to open the markdown preview to remove `!notebookEditorFocused`, I can still open a preview of a markdown cell. Is that a problem? Seems ok, I specifically asked for it.

**Comment by mjbvz** [comment]
Yes, I think that's fine. I gated the automatic previewing of files to always be disabled in notebooks. I didn't do the same for the command since the `when` clause seemed like a better approach
