### ISSUE TITLE
Hey all! Rulers not work that espected

### ISSUE THREAD

**Issue by arcanisgk** [microsoft/vscode#101536]
Hey all!

This looks to be merged into the Insiders release of VS Code. Here is an example snippet with the updated scheme:

```
"editor.rulers": [
    {
        "column": 80,
        "color": "#ff00FF"
    },
    100,
    {
        "column": 120,
        "color": "#ff0000"
    },
],
```

i expected a second line:

![image](https://user-images.githubusercontent.com/1207306/86287639-23599b00-bbae-11ea-8d84-95d74a8f4acb.png)

_Originally posted by @mallardduck in https://github.com/microsoft/vscode/issues/54312#issuecomment-583654497_

**Comment by mallardduck** [comment]
@arcanisgk As I mentioned in my original comment, it was included in Insiders release of VS Code and it does still work there for me. Potentially the issue is that you're using the release version of VS Code and not Insiders builds?

**Comment by mallardduck** [comment]
TBH I'm not sure if this has been included in a full release of VS code yet.

**Comment by mallardduck** [comment]
Yeah - it seems you may be having an isolated issue. I've tested my settings.json file from insiders release and all 3 rulers show up.

Here's my `settings.json` file if you want to try pasting the entire file in?
```
{
    "editor.rulers": [
        80,
        {
            "column": 100,
            "color": "#ff7b00b0"
        },
        {
            "column": 120,
            "color": "#ff0000dc"
        },
    ],
    "editor.fontFamily": "Fira Code Retina, Fira Code, Menlo, Monaco, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",
}
```

**Comment by arcanisgk** [comment]
this is my version: 

![image](https://user-images.githubusercontent.com/1207306/86289715-c8c23e00-bbb1-11ea-99d1-d76e7fc03229.png)

**Comment by mallardduck** [comment]
Very odd - I wonder if it's a platform specific bug. Are you sure your `settings.json` has valid formatting?

**Comment by IllusionMH** [comment]
It works as expected for me at least on 3 VSCode version for me 1.45.1, 1.46.1, 1.47 (insiders) on Windows
![image](https://user-images.githubusercontent.com/1312662/86290993-09907600-bbf7-11ea-8cee-b8b913eae932.png)

Do you have anything set to `"window.zoomLevel"` or do rulers become visible if you change this value?

**Comment by arcanisgk** [comment]
for me only show if any line of the file break the limit...

**Comment by IllusionMH** [comment]
Do you have `"editor.rulers"` anywhere in Workspace/Folder configurations?
![image](https://user-images.githubusercontent.com/1312662/86298437-68a9b700-bc06-11ea-86e6-869ae80b6919.png)


Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by arcanisgk** [comment]
i have it in JSON Genereral configuration.
