### ISSUE TITLE
multiple folder entries

### ISSUE THREAD

**Issue by wenhongjie** [microsoft/vscode#101653]
Sometimes a project can have a lot of folders and files, and the folders associated with it can be very far apart. If you can split the folders like the editor, you can make it much more efficient.
![image](https://user-images.githubusercontent.com/30290407/86437531-4bc0d100-bd37-11ea-887c-04734694a697.png)

**Comment by isidorn** [comment]
I believe you can write na extension that contributes a view that represents this as you wish
