### ISSUE TITLE
[Debug] Debug console completions don't work the way they are descripbed in DAP specification.

### ISSUE THREAD

**Issue by vadimcn** [microsoft/vscode#101623]
- VSCode Version: 1.46.1
- OS Version: Ubuntu 20.04

(This is in the context of implementing "completions" request in a debugger extension) 

Steps to Reproduce:
1. Debug session starts.
2. User types "se" in the debug console.   VSCode sends a completion request to the debug adapter: `"arguments":{"frameId":1001,"text":"se","column":3,"line":1}` (I'm copying only the relevant parts of the messages here).
3. The adapter responds with `body":{"targets":[{"label":"ttings","length":0,"start":3}]}` (I also tried just `"body":{"targets":[{"label":"ttings"}]}`)
4. Nothing happens.   If I force suggestions with Ctrl+Space, VSCode says "No suggestions."

According to my reading of  [DAP spec]( https://microsoft.github.io/debug-adapter-protocol/specification#Types_CompletionItem), this response should have caused "ttings" to be inserted at the current cursor position.  In reality, it seems that in order for completions to appear, the completion text must start with the current word under the cursor, i.e. `"body":{"targets":[{"label":"settings"}]}`.  As far as I can tell, the "start" and the "length" attributes are completely ignored.

**Comment by isidorn** [comment]
I acknolwedge this limitation.
I believe that the underlying vscode comlpetion item infrastructure filters out the completions which do not match.
Code pointer in case there are interests in experimenting with changing this
https://github.com/microsoft/vscode/blob/320fbada86c113835aef4fb9d7c4bc5b74678166/src/vs/workbench/contrib/debug/browser/repl.ts#L150
