### ISSUE TITLE
Notebooks: Broken subpixel AA

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#101607]
Open a Notebook on Light+ theme.

![image](https://user-images.githubusercontent.com/22350/86370324-dcd47100-bc7f-11ea-98a7-fb61ca7d72cc.png)

**Comment by roblourens** [comment]
Hm, I fixed this but subpixel AA is still broken in markdown content. It works in the monaco editor in either case. If I get rid of the webview, it works for markdown. 

It seems like `contain: strict` is responsible for making this work in monaco. I'm trying to apply the same fix to markdown cells in the notebook and it's not working (but I don't really think that's the right fix anyway). @rebornix wondering whether you know anything about this?

**Comment by DonJayamanne** [comment]
No longer an issue.
