### ISSUE TITLE
Notebook editor actions dont appear until explorer double click 

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#101624]
![Kapture 2020-07-02 at 11 30 25](https://user-images.githubusercontent.com/8586769/86396811-805d5b80-bc57-11ea-894d-a86cfe594577.gif)

**Comment by JacksonKearl** [comment]
Still seeing this happen
![Uploading recording (1).gif…]()

**Comment by roblourens** [comment]
Now it's actually by design with the way the github issues notebook registers it

**Comment by JacksonKearl** [comment]
Even with latest issue notebooks still seeing weirdness, but verified that actions can be visible in general.
![recording (3)](https://user-images.githubusercontent.com/8586769/89479834-b4410a80-d748-11ea-9add-c48d0766b434.gif)
