### ISSUE TITLE
vc code does not show data received in functions while debugging

### ISSUE THREAD

**Issue by alishagupta20** [Microsoft/vscode#10168]
- VSCode Version: 1.4.0
- OS Version:windows

Steps to Reproduce:

1. add debugger on some function that receive parameter
2. it does not show value received by function but when explore it in console print all values.
![error](https://cloud.githubusercontent.com/assets/20121463/17426938/4eea41ac-5afa-11e6-8f8a-7c3023d9f385.png)

**Comment by isidorn** [comment]
Can you please expand the `req` in the variables view? So we see what is the value there?
Also is it possible to share the repository so we can reporduce this issue on our side?

**Comment by alishagupta20** [comment]
I cann't share my repository. All I want to say is that, when I hover on variable to check its value, it shows none.but when I print it in console by Debug:Evaluate option on right click , it shows all data. but on hover that variable, it shows blank.

**Comment by alishagupta20** [comment]
As you can see that in screenshot res variables have so many values like _body, _consuming,_dumped like. but on hovering re variable, it shows only one value _body.

**Comment by isidorn** [comment]
I understand that but can you please expand the 'req' in the variables view on the left (it is above the watch expressions and the callstack)

**Comment by isidorn** [comment]
This is the current limitation of the debug hover. Closing as designed.
Will be improved in the future once we incorporate more language knowledge into the debug hvoer
