### ISSUE TITLE
Don't enable stop profiling when not profiling

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101686]
* start vscode
* f1 > perf
* 😕 there an entry for stop perf profile...

<img width="817" alt="Screenshot 2020-07-03 at 17 08 43" src="https://user-images.githubusercontent.com/1794099/86482213-c8f93f80-bd51-11ea-9c7d-a84e339c7139.png">

**Comment by connor4312** [comment]
Fixed this, forgot to close it.
