### ISSUE TITLE
Perl代码提示活动编辑器无法提供大纲信息

### ISSUE THREAD

**Issue by 825906328** [microsoft/vscode#101655]
Issue Type: <b>Bug</b>

Perl代码提示活动编辑器无法提供大纲信息

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (3.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.10.0
vscode-language-pack-zh-hans|MS-|1.46.3
vscode-icons|vsc|10.1.1
material-theme|zhu|3.8.2

</details>

**Comment by 825906328** [comment]
Perl code hints that the active editor cannot provide outline information

**Comment by JacksonKearl** [comment]
Outline information is implemented on a per-language basis by extensions. You can open a feature request against the perl extension for this.
