### ISSUE TITLE
Quick outline doesn't focus editor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101657]
* select a file in the explorer, e.g `src/vs/base/common/async.ts`
* without clicking into the editor, open quick outline and select an element from the file
* :bug: focus is not in the editor

---

![Jul-03-2020 09-40-11](https://user-images.githubusercontent.com/1794099/86444603-418bdc00-bd11-11ea-8825-d44b50a0930f.gif)

**Comment by bpasero** [comment]
This is very likely from https://github.com/microsoft/vscode/issues/93055

**Comment by bpasero** [comment]
The quick outline is setting focus to the editor, but it seems that https://github.com/microsoft/vscode/commit/da99f1fe1fc9def6cbe5cbe122de49b3716e2cee is still restoring focus to the previous element.

Imho quick input should check if the focused element is different from where it was before.
