### ISSUE TITLE
Hope to add function of 'Find All'

### ISSUE THREAD

**Issue by leafli7** [Microsoft/vscode#10161]
### Thanks to all of you for making such perfect product.
- I make the issue to request a new function 'Find All', which means I can enter the multiple-cursor mode when I have done the find operation.
### The step is as below:
1. Find something, usually a regular expression.
2. I hope that i can click a button such as 'Find All', the vs code will insert cursor at every end of finding result. It is very useful when I want to do batch insert operation.
### This is the function all i want. The gif is as below.

![muti-cursor](https://cloud.githubusercontent.com/assets/10811577/17425092/42b07742-5afc-11e6-8b40-c2cd072895b0.gif)

**Comment by alexandrudima** [comment]
We have a PR for this (#7559), but we need to figure out some UX first -- in the meantime you can use alt+enter in the find input.

**Comment by leafli7** [comment]
@alexandrudima thank you for reply! I will wait for it~

**Comment by siegebell** [comment]
@leafli7 you could also try the [incremental-search extension](https://marketplace.visualstudio.com/items?itemName=siegebell.incremental-search). 

For your example, either:
a) create a new cursor for each line (`ctrl+alt+down`), type `ctrl+i`, type `9`, and then press `enter`; or
b) with just one cursor, type `ctrl+i`, type `9`, type `shift+alt+i` 8 times (to add to the selection), and then press `enter`.

**Comment by mjbvz** [comment]
Closing this issue as out of date.

You can use the `Select all occurrences of find match` command to do something similar to what was originally requested
