### ISSUE TITLE
Web Speech API support

### ISSUE THREAD

**Issue by vdeantoni** [microsoft/vscode#101621]
Hello,

I've been trying to use the [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) in my extension. However, it does not seem to be enabled as both `SpeechRecognition` and `webkitSpeechRecognition` are not defined.

I'm not sure if this is an electron limitation or if it is something that was excluded from the vscode build.

It would be great if we could leverage the native Web Speech API to create custom voice commands.

Thank you for you hard work.

**Comment by yume-chan** [comment]
Your extension runs in a Node.js-like process without all the Web stuff.

You need to find a solution for Node.js (for example https://github.com/googleapis/nodejs-speech)

**Comment by dbaeumer** [comment]
@yume-chan thanks, that is correct.
