### ISSUE TITLE
Find in File: filter unmatched lines

### ISSUE THREAD

**Issue by ChuckJonas** [microsoft/vscode#101649]
When looking a large text files (AKA logs), it can be very helpful filter out the unmatched lines.  This allows you to view all the matched lines side by side.

<img width="789" alt="debug_log_—_apex-log-stream-files" src="https://user-images.githubusercontent.com/5217568/86432005-8aad4300-bcb3-11ea-8308-4793ab710d67.png">

_In the above example only the two matches would be shown_

There are [extensions that allow something similar](https://marketplace.visualstudio.com/items?itemName=everettjf.filter-line), but the number of clicks/keystrokes required is too high when needing to run quick, subsequent searches.  

The ideal experience would be filtering as you type and without creating a "temporary" file.  When the `Find in file` dialog is closed or the "filter" button unchecked, the lines would return.

**Comment by ralphcallaway** [comment]
in terms of an implementation example, `less` has this feature with the `&<regex>` operator.
