### ISSUE TITLE
LAGS

### ISSUE THREAD

**Issue by 336ccf** [microsoft/vscode#101646]
I am newbie and lags emberassing, please make sure that not every letter or mouse moving catched by screen. If it would not chage I would work in standart Text editor by MS. I am really appreciate your team about interest and of course a lot of features, but it is disgusting. This makes me turtle in some really usual things. Guys, please &3

**Comment by Gitter499** [comment]
The source of your issue might be your computer. Please specify what version and what OS you are running so people can respond.

**Comment by 336ccf** [comment]
Accidently, I think it is problems with my PC. It is Windows 7 Home x 64 x SP1, Intel Pentium CPU G2020 @ 2.9 GHz (no boost). 6 Gb RAM . Usually I use it with Google Chrome(15-20 tabs) and 2-3 light programms. Thanks for answers, obvously it is more my own problem, but VSCode goode team able to adopt some kind of feature, where you can test it with own list of plugins and addons, for example: you start test option, VSCode or other services run Back-endly 100 heavy files and simulate their work. When computer start slowing down feed-back, rate the limits and show them to the user as compitability. I am not pro, but it might able to work

**Comment by JacksonKearl** [comment]
Hey sorry this issue slipped through the cracks, if you are still experiencing slowness you can try looking through this document https://github.com/microsoft/vscode/wiki/Performance-Issues to collect data to help us diagnose the issue.
