### ISSUE TITLE
Menus: Can't run menu action on a single click

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#101658]
Using custom title bars:

1. Press mouse left button down on `Help`
2. Move mouse to `About` and release mouse button

🐛 Nothing happens

I thought we had this working before 🤔

**Comment by gjsjohnmurray** [comment]
Sounds similar to #101537 but @drventure doesn't mention if using custom title bars.

**Comment by joaomoreno** [comment]
Yeah definitely a dupe.
