### ISSUE TITLE
Notebook output misaligned

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101663]
* todays insiders
* run `.vscode/notebooks/verification.github-issues`
* 🧀 on the right hand side

<img width="446" alt="Screenshot 2020-07-03 at 10 28 15" src="https://user-images.githubusercontent.com/1794099/86449224-2cff1200-bd18-11ea-9bfb-644c4246515a.png">

**Comment by misolori** [comment]
Forgot to update the output width when I increased the right side margin. Will create a candidate release PR.
