### ISSUE TITLE
SCM input box line length warning can get detached on scroll

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#101643]
Issue Type: <b>Bug</b>

**repro**
1. In the scm view
1. Have enough changes the the changes section can be scrolled
1. Enter a long line in the scm input so that the line length warning shows up
1. With the warning visible, scroll the commit list

**Bug**

The line length warning become detached from the input box:

<img width="618" alt="Screen Shot 2020-07-02 at 5 41 21 PM" src="https://user-images.githubusercontent.com/12821956/86420453-9c7af000-bc8b-11ea-8cb6-664b5f526a99.png">

VS Code version: Code - Insiders 1.47.0-insider (04545fa88043fd10d1f3edefd26be1b8245b516f, 2020-07-02T05:41:12.081Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.68GB free)|
|Process Argv|-psn_0_13069430|
|Screen Reader|no|
|VM|14%|
</details>

**Comment by joaomoreno** [comment]
Decided to hide the validation when the view scrolls, for now.
