### ISSUE TITLE
Delete Big Folders

### ISSUE THREAD

**Issue by ProMikeCoder2020** [microsoft/vscode#101617]
I would like that in the editor we could delete big folders like node-modules.

**Comment by IllusionMH** [comment]
/needsMoreInfo

What exactly you want, how it should looks and behave?

At this point there is no problems with removing `node_modules` in explorer view, and it's much faster than `rm -rf node_modules` in Git Bash on Windows.

**Comment by Nimplex** [comment]
![image](https://user-images.githubusercontent.com/39964594/86388970-ecf74b00-bc95-11ea-8fcf-c3c60a722c58.png)

**Comment by IllusionMH** [comment]
![image](https://user-images.githubusercontent.com/1312662/86389404-eb7e5080-bc9e-11ea-89dd-e6e122031260.png)

It's in context menu for `node_modules` also removed on <kbd>Del</kbd>.
It will be changes to Delete Permanently if modifier key is pressed (on Windows it's <kbd>Shift</kbd> or <kbd>Alt</kbd>)

It's not clear what exactly problem do you have.

If this context menu item is missing for you - update your post with details required by bug template.
If you don't see `node_modules` in Explorer - check if it's not in `files.exclude` setting.

**Comment by ProMikeCoder2020** [comment]
> /needsMoreInfo
> 
> What exactly you want, how it should looks and behave?
> 
> At this point there is no problems with removing `node_modules` in explorer view, and it's much faster than `rm -rf node_modules` in Git Bash on Windows.

When i try to delete node_modules in the explorer view that editor crashes. And it doesn't even delete the folder!

**Comment by IllusionMH** [comment]
> When i try to delete node_modules in the explorer view that editor crashes. And it doesn't even delete the folder!

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

That's a bug. Please update description according to issue template(VSCode version, OS Version, Reproducible without extension etc.). You can see template here https://github.com/microsoft/vscode/issues/new?template=bug_report.md

**Comment by isidorn** [comment]
Can not reproduce

**Comment by ProMikeCoder2020** [comment]
> > When i try to delete node_modules in the explorer view that editor crashes. And it doesn't even delete the folder!
> 
> Is it reproducible with all extensions disabled?
> You can try this with F1 and `>Developer: Reload Window With Extensions Disabled`
> 
> That's a bug. Please update description according to issue template(VSCode version, OS Version, Reproducible without extension etc.). You can see template here https://github.com/microsoft/vscode/issues/new?template=bug_report.md
I have already created a new issue with the template
