### ISSUE TITLE
The terminal process terminated with exit code: 4294901760

### ISSUE THREAD

**Issue by Hasib-z** [microsoft/vscode#101697]
We have written the needed data into your clipboard because it was too large to send. Please paste.

My terminal stopped

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    71	  5600	code main
    0	   233	  3384	   gpu-process
    0	   171	  3724	   window (Settings - myfst - Visual Studio Code)
    0	    53	  2868	     extensionHost
    0	    22	   232	       "C:\Users\hasib\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\hasib\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=2868
    0	    28	  5088	       "C:\Users\hasib\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\hasib\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=2868
    0	     9	  4340	     watcherService 
    0	     4	  9060	       console-window-host (Windows internal process)
    0	    34	 12304	     searchService
    5	    72	  6928	   window (Issue Reporter)
    0	     9	 11384	   electron-crash-reporter
    0	    50	 11712	   shared-process
    0	    21	 12280	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - myfst - Visual Studio Code)
|    Folder (myfst): 2 files
|      File types: htm(1) html(1)
|      Conf files:;
```

</details>
Extensions: none

OS: Windows_NT x64 10.0.18362

**Comment by Tyriar** [comment]
Please see https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch to help diagnose.
