### ISSUE TITLE
Correctly parse jinja templates 

### ISSUE THREAD

**Issue by leonbrag** [microsoft/vscode#101645]
VS code is not able to correctly parse HTML Jinja templates. 

When HTML file with  {% %} is opened, I get nice HTML color coding, but lots of parsing errors are reported, since {% %}  correctly identified as non-valid HTML tags

When I change type Jinja manually, then parsing errors are no longer shows, but all color coding are lost

The suggestion is to merge ability to recognize {% %} with HTML parsing

**Comment by aeschli** [comment]
VSCode only support standard HTML.
Jinja support has to come from extension. Please check the marketplace.
