### ISSUE TITLE
Suggestion hints automatically being complete from alphatyping () select first entry or partial match, and injects it.

### ISSUE THREAD

**Issue by wesleyolis** [microsoft/vscode#101669]
Hi,

Well this is rather anoying that one is not allowed to type somthing that doesn't below to the auto complete list, if partially matches, when added () to the end, it automatically selects the 1 suggested partially matching.
Did I hit enter or tab, no, so why is it while typing take that entry.
This happens so often and is so anoying. Have they write escape, write escape to get what one wants that is not productive. Espeically when one can type and not look at the screen or care about auto suggestions, because you is notusing them they much. They should be there for assit and not to inject crap the whole time that is unwanted, this been going on now for 2 years, its extermly anoying. If write a call to a function that doesn't exist yet, then well I should be allowed to do that.

If there is spelling mistake, then basically rather highlight the token, showing a suggestative correction, if like 1 charater off, or statistically acourding to the key qweerty layout or devorak layour. Cell and android auto correct makes many mistakes there.. change the means of sentance to wrong things.

when goes above the mistake auto popup the suggestion box.

Please please fix, productivity is so harm by auto completing random stuff.

**Comment by gjsjohnmurray** [comment]
Maybe try `"editor.acceptSuggestionOnCommitCharacter": false`

Whether this will help or not may depend on what language you're coding in (you didn't say).

In  #85768 I previously suggested an option to turn off automatic selection a suggestion, but it didn't get enough votes to reach the Backlog.

I also recommend you tell us what VS Code version you are using, and on what platform. These get added automatically if you open your issue using 'Report Issue' from VS Code's Help menu.
