### ISSUE TITLE
Unicode characters U+2591, 2592, 2593 are not properly displayed with Consolas

### ISSUE THREAD

**Issue by Zezombye** [microsoft/vscode#101651]
- VSCode Version: 1.46.1
- OS Version: 10.0.14393

Steps to Reproduce:

1. Copy paste the following text in VS Code, using Consolas (the default font):

```
light shade: ░
medium shade: ▒
dark shade: ▓
```

These characters overflow into the previous line:

![](https://i.imgur.com/n8evqvd.png)

Using Consolas on notepad++ doesn't have this problem. On Firefox, it overlaps by one pixel, but this is still manageable.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@Zezombye Can you reproduce when opening the following sample in Chrome? https://jsfiddle.net/g2kw1uyq/

**Comment by Zezombye** [comment]
Indeed, I'll file a bug with Chromium then. Thanks!
