### ISSUE TITLE
inconsistent naming of QuickPickOptions and QuickPick

### ISSUE THREAD

**Issue by dcermak** [microsoft/vscode#101666]
- VSCode Version: 1.46.1
- OS Version: irrelevant

The interface [`QuickPickOptions`](https://code.visualstudio.com/api/references/vscode-api#QuickPickOptions) has the entry `canPickMany`, however this field appears as `canSelectMany` in the actual [`QuickPick`](https://code.visualstudio.com/api/references/vscode-api#QuickPick%3CT%3E).

How about making the naming consistent here?

**Comment by chrmarti** [comment]
Not sure how we got there, but since this is stable API, we'll just keep it that way. Thanks.
