### ISSUE TITLE
Gtihub issues notebooks never open

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#101625]
```
Version: 1.47.0-insider (user setup)
Commit: 04545fa88043fd10d1f3edefd26be1b8245b516f
Date: 2020-07-02T05:48:37.715Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Github issues notebook v0.0.33

Recently I've noticed that a most of the time issue notebooks never load. I'm not sure if this is an issue with vscode or the notebook, no errors in the debug console. If I reload the window with a notebook open it will print an error that "Workbench did not finish loading in 10 seconds". I notice that if I do this it seems that other things don't activate, e.g. there's no problems action in the status bar.

![](https://memes.peet.io/img/20-07-d3c18515-3fb4-4e69-bd49-67f49c6d15ee.png)

Steps to Reproduce:

1. Try to open a .github-issues notebook

Does this issue occur when all extensions are disabled?: N/A

Peng requested a --prof-startup: 
[prof-a314.txt](https://github.com/microsoft/vscode/files/4866052/prof-a314.txt)

**Comment by jrieken** [comment]
> "Workbench did not finish loading in 10 seconds"

That usually means that the extension host didn't come up at all, e.g before loading extensions. Was there anything on the console? How did you start VS Code?

**Comment by connor4312** [comment]
It seems to work today, so I'm unable to reproduce it to get more information. Maybe there was a bad build. I will reopen if I run into it again.
