### ISSUE TITLE
renaming services type script adding at the end of path in components '.js'

### ISSUE THREAD

**Issue by alinastorm** [microsoft/vscode#101608]
- VSCode Version:
- OS Version: 1.46.1

Steps to Reproduce:

1.Rename any ServiceName.service.ts ( for example ServiceName2.service.ts)
2. VSC auto rename import path in components whith adding at the end of path '.js'
3. After that subscribe in angular components where path ends without '.js' not working. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
I don't understand your steps to reproduce. Can you please provide a code example that walks through the issue?

**Comment by alinastorm** [comment]
I'm confused. Error is not reproduced today. 
Yesterday when you rename a service added to the end of 'js'.
![photo_2020-07-03_21-29-09](https://user-images.githubusercontent.com/47041836/86491756-46ce4280-bd74-11ea-9bcc-473ca37e77e7.jpg)

**Comment by alinastorm** [comment]
I create repo for tests https://github.com/alinastorm/issueVsc101608.git
