### ISSUE TITLE
Arrow keys don't work in Ubuntu Bash on Windows

### ISSUE THREAD

**Issue by u84six** [Microsoft/vscode#10163]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:
1. Bind bash.exe path to integrated shell ("terminal.integrated.shell.windows": "C:\Windows\sysnative\bash.exe")
2. Open terminal by Ctrl-Shift-~
3. Type a command: echo hello world
4. Use up arrow to find the command in history (doesn't work)

This works in the new stand-alone bash terminal. This also works on a mac. Just not vsc.

**Comment by phfsantos** [comment]
I am also having the same issue. It does not work on version 1.4 neither. 
Arrows left and right also not working.

**Comment by vrabcak** [comment]
It is related to https://github.com/Microsoft/BashOnWindows/issues/111

**Comment by Tyriar** [comment]
@vrabcak thanks a bunch for pointing this issue out!

**Comment by u84six** [comment]
Why did this one get closed? The Bash terminal on Windows 10 works. It's just the vscode integrated terminal that doesn't.

**Comment by cybrown** [comment]
For those using bash for windows in vscode and cannot wait to use the history, here are some usefull commands involving the bang character when arrow keys are not available: http://ss64.com/bash/bang.html

**Comment by u84six** [comment]
I can't believe that this one is still not working. I submitted this back and August. How long does it take to support a simple history buffer? The native shell (Win10 bash) works, why not vsc?

**Comment by Tyriar** [comment]
@u84six as mentioned above, this is an upstream issue https://github.com/Microsoft/BashOnWindows/issues/111

**Comment by longtomjr** [comment]
just want to chime in ;). The Developer of [ConEmu](https://github.com/Maximus5/ConEmu), @Maximus5, has come up with a workaround for this issue. It might be worth it to look at what he did. :)

**Comment by Tyriar** [comment]
@longtomjr thanks for the tip, info here:

- https://conemu.github.io/en/BashOnWindows.html
- https://github.com/Maximus5/ConEmu/issues/629
- https://github.com/Maximus5/ConEmu/commit/2daa2df332b653de6de8a266cc096ec011287b83
- https://github.com/Maximus5/ConEmu/wiki/Bash-For-Windows-and-VIM-Arrow-Keys

**Comment by Tyriar** [comment]
Not 100% sure but the fix may just be to have xterm.js set application mode?

**Comment by longtomjr** [comment]
More info here: [Build 6041](http://conemu.github.io/en/Whats_New.html#Build_160411)

**Comment by pre63** [comment]
https://github.com/Microsoft/vscode/issues/7266#issuecomment-224520618

```
{
  "terminal.integrated.shell.linux": "bash",
  "terminal.integrated.shellArgs.linux": [ "-l" ]
}
```

**Comment by Tyriar** [comment]
`-cur_console:p1` was not recognized as an option when I tried it. Also regarding windows shell args, this is working find in the Insiders's build.

**Comment by Maximus5** [comment]
@Tyriar `-cur_console:p1` is [ConEmu switch](https://conemu.github.io/en/NewConsole.html)!

**Comment by longtomjr** [comment]
@Tyriar  sorry for misleading, I did not really know what the arg was for just grabbing around. @Maximus5 do you think it will be possible for us to recreate what you did to work around this issue using the method you used, also if you have any other info that you think might help the efforts please share. :).  

From what I understood you have two workarounds, the initial one and the later one. I am finding it hard to see what you did for the later one, if it is possible can you please point to a commit or something ;). Thanks for the great work on ConEmu btw, it is a dream to use!

**Comment by Maximus5** [comment]
ConEmu provides the one workaround: automatic translation of *native* keypresses into *Xterm* compatible keypresses. In later (current) ConEmu versions this translation is turned on automatically when flag 0x200 is turned on for input console handle.

Actually, this is due to a bug (AFAIK the internal MS bug is filled for conhost).

Unfortunately, arrow keypresses may be encoded in two ways, and without wslbridge it's absolutely impossible to handle them automatically.

**Comment by Tyriar** [comment]
@Maximus5 thanks for the clarification :smiley:

**Comment by stereokai** [comment]
@Tyriar @longtomjr and update on this? Anything I can do to help?

**Comment by Tyriar** [comment]
I'm in the process of an uplevel to winpty@0.4.0 which should fix the issue, see https://github.com/Tyriar/pty.js/issues/10

**Comment by whitecolor** [comment]
The same problem here when working with docker container's bash session: `docker-compose exec container-name bash`

**Comment by CherryDT** [comment]
There is a simple workaround for using the history: Use the bash commands which use the Ctrl key! Yes, bash has those, but most people forgot their existence, it seems.

Ctrl+P: Previous command (like up arrow)
Ctrl+N: Next command (like down arrow)
Ctrl+B: One character backwards (like left arrow)
Ctrl+F: One character forwards (like right arrow)
Ctrl+A: Start of line (like home key)
Ctrl+E: End of line (like end key)
Ctrl+D: Delete character (like delete key)

For details, see http://www.gnu.org/software/bash/manual/html_node/Bindable-Readline-Commands.html#Bindable-Readline-Commands

There is just one small issue: Ctrl+P (arguably one of the most important commands) is usually executed by VSCode to show "Quick Open". There are three ways to solve this: You could reassign the "previous-history" command in bash, reassign the "workbench.action.quickOpen" command in VSCode, or - arguably the easiest solution - change your "terminal.integrated.commandsToSkipShell" setting in VSCode to exclude "workbench.action.quickOpen" (you would then have to move focus away from the terminal to have VSCode respond to Ctrl+P).

**Comment by horihiro** [comment]
I tried [wslbridge](https://github.com/mintty/wsltty/) to use arrow keys on terminal, and I successed.

1. Download and execute [wslbridge installer](https://github.com/mintty/wsltty/releases)
1. Add following code to User Settings of Visual Studio Code.
```
{
  "terminal.integrated.shell.windows": "C:\\Users\\%USERNAME%\\AppData\\Local\\wsltty\\bin\\wslbridge.exe"
}
```
NOTICE: you can NOT use an environment variable (i.e. %USERNAME%) in User Settings, you have to replace to your username.

**Comment by Tyriar** [comment]
@horihiro good to know you got this working that way at a temporary work around :+1:

**Comment by u84six** [comment]
Does closing this mean that it's fixed? What do I have to update to fix this problem because it's still not working.

**Comment by Tyriar** [comment]
@u84six it's fixed in the Insiders build which you can test [here](https://code.visualstudio.com/insiders), it should included in v1.9.0 in ~2 weeks time.

**Comment by SMEmp** [comment]
Fantastic news, your efforts here are greatly appreciated!

I've been using Ubuntu in a Windows shop, (and dealing with some pretty poor graphics drivers because of it) it'll be nice to remove that bit of friction when this lands by switching to Windows 10.

**Comment by khards** [comment]
Good to hear that it's fixed in the insiders build. Perhaps I can encourage some Apple fanboys to develop on windows not we have all the Unix CLI tools built in.

**Comment by saopang** [comment]
when type 'blank' or 'tab' ,there is a wrong blank space,use 'cat sth.txt',repeat this bug
