### ISSUE TITLE
Scroll controls incorrect

### ISSUE THREAD

**Issue by m-brooks** [microsoft/vscode#101698]
Issue Type: <b>Bug</b>

FIRST PART
Steps to reproduce:
1) Open a file of a fair length (at least several screens in length) in edit mode with the cursor at the beginning of the file.
2) Move the pointer over the vertical scrollbar near the bottom.
3) Perform a single click on the mouse.
  
Symptom observed:
The scrollbar's slider immediately jumps to the position of the pointer.
  
What should happen:
The screen should scroll down one page with each successive click of the mouse (and the scrollbar's slider should jump the appropriate distance down the scrollbar at the same time). Once the slider has reached the pointer, successive clicks on the same location have no effect. This at least should be the behaviour on a Windows platform - I cannot speak for other operating systems.

SECOND PART
Steps to reproduce:
1) Open the settings at User->Commonly Used, sitting at the top of the available settings ("Files: Auto Save" on my installation).
2) Point at the area left of the vertical scrollbar and click once to ensure that focus is on this panel.
3) Press the "Page down" key.
  
Symptom observed:
Nothing happens.
  
What should happen:
The page of settings should scroll down one screenfull.

  
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharpfixformatfixed|aww|0.0.85
vscode-nuget-package-manager|jmr|1.1.6
csharp|ms-|1.22.1

</details>

**Comment by gjsjohnmurray** [comment]
Second is a duplicate of #66237
