### ISSUE TITLE
SCM tree expands whenever a provider removes a SourceControlResourceGroup

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#101688]
Issue Type: <b>Bug</b>

My source control extension creates and deletes its resource groups dynamically, based on the state of the repo it relates to. It implements a Refresh command button to trigger a manual refresh, and also uses a timer for a periodic refresh.

When used in a multiroot workspace in which other SourceControl instances (e.g. Git ones) appear in the SCM panel, I observe that if I have collapsed those instances prior to mine refreshing (i.e. deleting and creating its resource groups), this refresh causes all the other SourceControl instances to expand.

Deletion of a resource group leads to a splice [here](https://github.com/microsoft/vscode/blob/c6dde2b1ceb2eeebda3c2dec9c3cbf20e6d005f4/src/vs/workbench/api/browser/mainThreadSCM.ts#L238).

That causes [this refresh](https://github.com/microsoft/vscode/blob/c6dde2b1ceb2eeebda3c2dec9c3cbf20e6d005f4/src/vs/workbench/contrib/scm/browser/scmViewPane.ts#L999).

The subsequent render has [code](https://github.com/microsoft/vscode/blob/c6dde2b1ceb2eeebda3c2dec9c3cbf20e6d005f4/src/vs/workbench/contrib/scm/browser/scmViewPane.ts#L1024) that uses its repositoryCollapseStates map to determine the state of each tree root. But that map only seems to get populated when the SCM view is hidden (e.g. when switching to Explorer view. This means the correct collapse state is restored when returning to the SCM view, but it doesn't preserve state across the refresh described above.

VS Code version: Code - Insiders 1.47.0-insider (376d9d9d785ccca128fdbb16f001446d0ad64d32, 2020-07-03T10:27:06.804Z)
OS version: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
> But that map only seems to get populated when the SCM view is hidden (e.g. when switching to Explorer view. This means the correct collapse state is restored when returning to the SCM view, but it doesn't preserve state across the refresh described above.

We only need this state when the view is hidden, because the tree widget should take care of preserving collapse states otherwise.

Could you give me exact steps so I can repro with your extension?

**Comment by gjsjohnmurray** [comment]
> But yeah... this might be better be `undefined`:

@joaomoreno I confirmed this fixes the issue. Please apply it to 1.47

**Comment by joaomoreno** [comment]
Steps:

1. Open a workspace with two folders under git
2. Make a change on a file of one of them
3. Collapse the repository in the SCM view
4. <kbd>F1</kbd>, `Git: Stage All Changes`

:bug: The repository gets expanded in the SCM view, it shouldn't.
