### ISSUE TITLE
"no debug adapter"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#101626]
![image](https://user-images.githubusercontent.com/323878/86397933-9ff58380-bc59-11ea-8c4a-b03d0f5d3582.png)

I see this from time to time with js-debug, I don't remember seeing it before. In this case what I did was fairly simple, 

- Follow setup steps in https://github.com/microsoft/vscode-js-debug/issues/470
- Run "launch server", then "launch chrome"
- Press stop on "launch server"
- Get that error

Once it happens I am stuck and can't stop debugging and have to reload the window

**Comment by roblourens** [comment]
The second time I tried to repro I got this after clicking stop 

![image](https://user-images.githubusercontent.com/323878/86398130-fa8edf80-bc59-11ea-82a7-3c6bef444ee5.png)

**Comment by connor4312** [comment]
Merging with https://github.com/microsoft/vscode/issues/102037

/duplicate
