### ISSUE TITLE
Notebooks steal focus on explorer select

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#101622]
1. create a new .github-issues notebook. It should have a single, empty github-issues cell by default.
2. close the editor, then click on it again from explorer. 
1. 🐛 Focus goes to editor

**Comment by JacksonKearl** [comment]
Still seeing this...  whenever the file is empty, clicking on it will steal focus.
![recording](https://user-images.githubusercontent.com/8586769/89475072-1f381480-d73c-11ea-8720-880faec3828a.gif)

**Comment by roblourens** [comment]
For some reason, the empty cell we insert by default steals focus. But @rebornix do we want to get rid of that default cell now that the toolbar exists for an empty editor?

**Comment by roblourens** [comment]
I see https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L654, I think ideally it would only do that if the notebook is focused, but the notebook doesn't know whether it's going to be focused when it's opening, and when it gets focused, it doesn't know if it just got opened. I'm going to delete this for now.
