### ISSUE TITLE
VSCode does not launch on Apple Silicon

### ISSUE THREAD

**Issue by 0xTim** [microsoft/vscode#101662]
- VSCode Version: Latest
- OS Version: macOS 11.0

Steps to Reproduce:

1. Download VS Code
2. Open

Does this issue occur when all extensions are disabled?: Yes

<img width="1136" alt="Screenshot 2020-07-03 at 09 27 49" src="https://user-images.githubusercontent.com/9938337/86449026-7b5be300-bd0f-11ea-882d-7c8e20852248.png">

I can't find any logs or crash reports, but may be looking in the wrong place! Let me know if I can provide anything else

**Comment by 12101111** [comment]
Maybe you should try Electron or Chrome first.

**Comment by 0xTim** [comment]
Yeah I suspect this is waiting on fixes to Electron first. Apple did say they were working on it, but I'm assuming the fixes will need to be brought into VSCode

**Comment by deepak1556** [comment]
Thanks for opening the issue, this will be blocked until https://github.com/electron/electron/issues/24319 is resolved.

**Comment by gaodeng** [comment]
related [ Issue 1102194: Intel Chrome crashes under Rosetta 2 on arm macs](https://bugs.chromium.org/p/chromium/issues/detail?id=1102194&q=apple%20silicon&can=2)
electron patch https://github.com/Unity-Technologies/electron/commit/79a9fa9f4619393b78a44a69f92b32070f473e83

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/104780
