### ISSUE TITLE
VSCode can't read linked files

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [microsoft/vscode#101695]
Issue Type: <b>Bug</b>

I use pnpm instead of npm.
pnpm links to existing npms packages/files on the dev's computer, so it doesn't download new files everytime, like npm does!
But  vscode is showing a sea of errors like: "cannot find module 'react' or its corresponding type declarations."!

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.79GB free)|
|Process Argv|C:\Users\gabri\Documents\VS Code\React\file-explorer|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
git-easy|bib|1.11.0
vscode-styled-jsx|bla|1.5.0
better-toml|bun|0.3.2
cmake-format|che|0.6.10
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.1.4
selectword|cra|1.0.1
vscode-eslint|dba|2.1.5
vscode-deno|den|1.25.0
prettier-java|dot|0.1.1
vscode-wasm|dts|1.3.1
gitlens|eam|10.2.2
vscode-diff|fab|1.4.0
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
backticks|fra|1.6.0
rust-test-lens|hde|1.0.0
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
ispc|int|1.0.0
Ionide-fsharp|Ion|4.14.0
blender-development|Jac|0.0.12
latex-workshop|Jam|8.11.1
rust-doc-viewer|JSc|1.0.15
vscode-rust|kal|0.4.2
vscode-format-context-menu|lac|1.0.4
vscode-js-annotations|lan|0.11.0
pretty-formatter|mbl|0.2.1
vscode-language-babel|mgm|0.0.29
dotenv|mik|1.0.1
HTMLHint|mka|0.8.0
vscode-filesize|mkx|2.1.4
prettify-json|moh|0.0.3
csharp|ms-|1.22.1
cpptools|ms-|0.28.3
powershell|ms-|2020.6.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.8
vscode-react-native|msj|0.16.1
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.2.0
tsimporter|pmn|2.0.1
vscode-css-peek|pra|3.0.2
webgl-glsl-editor|rac|1.1.0
java|red|0.63.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
rocketseatreactjs|roc|3.0.2
rocketseatreactnative|roc|3.0.1
mongo-snippets-for-node-js|roe|1.3.4
color-manager|roy|0.5.7
rust|rus|0.7.8
vscode-javascript-booster|sbu|14.0.1
crates|ser|0.5.1
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.12
vscode-scss-formatter|sib|2.0.1
html5-boilerplate|sid|1.0.3
vsc-quokka-statusbar|ske|1.3.5
vscode-3dviewer|sle|0.2.0
snipsnap-vscode|sni|1.0.5
vscode-status-bar-format-toggle|tom|2.0.0
java-imports-snippets|tus|0.0.1
cmake|twx|0.0.17
errorlens|use|3.1.1
highlight-matching-tag|vin|0.9.9
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
quokka-vscode|Wal|1.0.305
map-replace-js|Yuk|0.2.2

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Maybe #98305 is relevant. 1.47 is in endgame at the moment, and you can try it by using Insiders.

**Comment by mjbvz** [comment]
@Gabriel-Alves-Cunha Can you please share some steps and potentially a small example project to reproduce this issue?
