### ISSUE TITLE
vscode not adhering to my syntax highlighting in settings.json unless I open the file and edit one of the colors (still)

### ISSUE THREAD

**Issue by cjolivier01** [microsoft/vscode#101627]
Same as https://github.com/microsoft/vscode/issues/101422

insiders build does not fix

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by cjolivier01** [comment]
also, it doesnt fix itself when I edit the color now.

**Comment by aeschli** [comment]
dup of #101422
