### ISSUE TITLE
Notebooks: Find widget is broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#101604]
Verifying https://github.com/microsoft/vscode/issues/99371

1. Open our `verification.github-issues`.
2. <kbd>Ctrl F</kbd>, type `config`, press <kbd>Enter</kbd>
3. <kbd>Ctrl Backspace</kbd> to delete, type `label, press <kbd>Enter</kbd>

🐛 Only one `label` is found
🐛 `config` is still highlighted as a match

---

I was also able to get into a terrible state in which NPEs appeared in dev tools and I was even able to surface one of the text editor's find widget, by focusing it and pressing <kbd>Ctrl F</kbd>. I can't repro this so I'll have to keep an eye on it.

**Comment by rebornix** [comment]
Already fixed in https://github.com/microsoft/vscode/commit/dab68ed88523db7e7161f69da791b8c7e87c99c8.
