### ISSUE TITLE
Debug doesn't wait until the process ends

### ISSUE THREAD

**Issue by JonaVDM** [microsoft/vscode#101675]
Issue Type: <b>Bug</b>

When debugging a file in Javscript that ends in a loop, the debugger ends before the program itself. Which results in this case in some items not being logged in the console.

Expected
![image](https://user-images.githubusercontent.com/32264711/86472876-2b494480-bd40-11ea-924c-4bd037f53654.png)

Reality 
![image](https://user-images.githubusercontent.com/32264711/86472547-9b0aff80-bd3f-11ea-808e-04e4a7544220.png)

1. Create a new js file named for example test.js with this content
```js
let array = new Array(10).fill('hello world')

for (let i in array) {
    let item = `${array[i]} - ${i}`;

    console.log(item);
    console.log({ item });
}

console.log('Set debug on this line'); // or uncomment the next line
// setTimeout(() => {console.log('end')}, 1000);
```
2. Go to the run tab and hit the run and debug button, select Node.JS
3. Go to the dubug console

A quick fix I found was by either putting a breakpoint in the loop or just behind it. Or by adding a timeout.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz (8 x 1700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by weinand** [comment]
@JonaVDM Could you please try to use the integrated terminal and see whether this makes a difference.
Just add `"console": "integratedTerminal"` to your launch config.

**Comment by JonaVDM** [comment]
It does work as I expect when I add in the `"console": "integratedTerminal"`. That is that it logs the objects.

![image](https://user-images.githubusercontent.com/32264711/86494431-64e87280-bd75-11ea-8e70-e24e38e007ac.png)

**Comment by connor4312** [comment]
Thanks for the issue, this duplicates https://github.com/microsoft/vscode-js-debug/issues/161
