### ISSUE TITLE
Notebooks: only show the status bar after executing a cell

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#101635]
From #101600

Proposal would be to hide the status bar in notebook cells unless the cell has been executed. This means that the language picker would be hidden, which I personally think should be hidden unless there is more than 1 language (you can still perform this action via the command palette).

## Default state
![image](https://user-images.githubusercontent.com/35271042/86409376-9e35bb00-bc6d-11ea-9054-2f1526b601d3.png)

## With execution
![image](https://user-images.githubusercontent.com/35271042/86409423-b7d70280-bc6d-11ea-96cc-3f918dc4d56a.png)

cc @kieferrm @roblourens @jrieken

**Comment by rebornix** [comment]
I like this a bit more than having it always displayed there. Usually you get a result after executing a cell, so there will be some cell positions shifting (we discussed before that we don't want to see too much UI shifting) and status bar height change is part of it, which is fine IMHO. 

If we make the visibility conditional, the language picker should probably go into the cell toolbar *again*.

**Comment by roblourens** [comment]
Yeah, so there will be a double shift. The status bar will show up with the progress/timer, then the output will show up. I'd be slightly worried about that but it's worth experimenting with.

**Comment by misolori** [comment]
I'm wondering if now is a good time to add a `...` toolbar action for overflow actions like the language selector and others. My hypothesis is switching languages on a cell will be less common. But when you have multiple languages, it's important to visibly tell the difference so I'd expect it to contextually appear.

**Comment by rebornix** [comment]
@misolori .NET notebook might be an exception as you can use any .NET languages in it, then it's hard to

* guess what should be the default language for a code cell (C#, F#, PS all make sense)
* users might mix use those languages 

@jonsequitur @brettfo may I ask if my assumption is correct?

**Comment by roblourens** [comment]
For any notebook with multiple languages, I think that seeing the language for the code cell is important. I can't remember whether we have talked about this but how about having the language be an item in the cell toolbar, in other words, you can always see it without clicking in to `...`, and it basically works like a button with text, but it doesn't take up extra space on the bottom?

**Comment by rebornix** [comment]
> how about having the language be an item in the cell toolbar

@roblourens I like it more. It's similar to Debug Toolbar with multi processes. I remember @misolori shared once about adding vertical separator in the toolbar, we might want to have a mock of that together to see how it looks.

**Comment by misolori** [comment]
![image](https://user-images.githubusercontent.com/35271042/86954496-ebe97200-c10a-11ea-9642-d6fb8a922b8c.png)

@roblourens is this what you mean? Would this only show up when you have multiple languages or all the time?

**Comment by jonsequitur** [comment]
.NET Interactive has multiple languages as well as the ability to add more at runtime. Making the cell language visible is pretty important to the workflow.

**Comment by roblourens** [comment]
Yeah that's what I am imagining. And it could go either way. I can imagine that it might still be useful to see it even when you are dealing with multiple languages. Like when switching between two notebooks each with a single different language.

**Comment by misolori** [comment]
We discussed this during standup and we're going to leave this under discussion as there is still a valid reason for seeing the current cell language (even more for multiple language notebooks like .NET)

**Comment by roblourens** [comment]
Is this something we still want to consider @misolori? I think this encompasses

- Moving the language to the toolbar area
- Only showing the statusbar after executing

but I don't think this has come up in a bit. Please reopen if you think it's still relevant
