### ISSUE TITLE
JavaScript Syntax Highlighting: Ternary object declaration

### ISSUE THREAD

**Issue by JosephGarrone** [Microsoft/vscode#10166]
- VSCode Version: 1.4
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new file and set language to JavaScript
2. Paste the following in:
```
class Test {
    let style = type ? {
        color: '#FFF',
        padding: '15px'
    } : {
        overflow: 'hidden',
        height: '0px'
    };
}
```

The resultant highlighting will render as such: 

![image](https://cloud.githubusercontent.com/assets/4310797/17426447/19d1a12e-5b1b-11e6-9b88-58ef584a72a8.png)

IE: No highlighting on second object and also breaks code formatting (Alt + Shift + F).

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#234
