### ISSUE TITLE
Reactivate window after Continue when debugging extensions

### ISSUE THREAD

**Issue by jaime-olivares** [Microsoft/vscode#10160]
- VSCode Version: 1.3 and 1.4
- OS Version: macOS

When debugging an extension and a breakpoint is set, and after reviewing, the Continue (F5) button is pressed, the debugged window remains in the background.

Steps to reproduce:
1. Open a folder containing a VSCode extension project
2. Set a breakpoint anywhere in the source code
3. Start debugging the extension (a new VSCode window is shown)
4. Run until the breakpoint is reached (the source code is shown, the debugged window goes to the background)
5. Press the Continue button or F5

Expected result:
The debugged window is shown and the execution continues

Observed result:
The execution continues but the debugged window doesn't bring to front

**Comment by DonJayamanne** [comment]
I too have experienced similar issues, but worse, the breakpoints seem to be getting hit, but the editor isn't getting updated, and debugger window is empty, the debug breakpoints are disabled.
I have to hit the continue button a couple of times before the debugger kicks in. Looks like there's

**Comment by Huachao** [comment]
I also met the same issue in VS Code 1.4, while I can work in version 1.3

**Comment by weinand** [comment]
@DonJayamanne @Huachao the original issue by @jaime-olivares is clearly the feature request to bring the debuggee window to front on 'continue' whereas your issue sounds like a bug.
Could you please create a new issue for this so that we don't mix-up unrelated issues. Thanks.

**Comment by weinand** [comment]
we are not planning to implement the feature to bring the debuggee window to front.
