### ISSUE TITLE
python showing "SyntaxError: invalid character in identifier" after creating a new python file from vscode

### ISSUE THREAD

**Issue by dbsxdbsx** [microsoft/vscode#101665]
- VSCode Version: 1.47.0 inside
- OS Version: win10 or win8

Steps to Reproduce:
1.creating a python file BY VSCODE, 
2.just run the python file ,even there is no code.

I wonder this is due to some extension conflict, but after disabling all extensions, it still occurs. By the way, this bug does not occur when using vscode 1.46.1 normal version.

**Comment by Tek-God** [comment]
[ai-essentials-understanding-2019-12-06-A.zip](https://github.com/microsoft/vscode/files/4869022/ai-essentials-understanding-2019-12-06-A.zip)

**Comment by JacksonKearl** [comment]
\extPython
