### ISSUE TITLE
Toggle header/source file

### ISSUE THREAD

**Issue by zrno** [microsoft/vscode#101644]
Issue Type: <b>Feature Request</b>

Currently an extension needs to be used to toggle between header and source files written in C, C++ and Objective-C. 

https://marketplace.visualstudio.com/items?itemName=bbenoist.togglehs

Could this feature be implemented as part of VS Code?

One the issues with the extension is that it doesn't work when using VS Codes Live Share extension.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

**Comment by dbaeumer** [comment]
Having this done in an extension is the right thing to do since VS Code itself has no knowledge about header and source files. Which extension are you using for this?

**Comment by zrno** [comment]
extension link is in the first post

**Comment by dbaeumer** [comment]
The best I can recommend is to request that feature from the CPP extension directly.

**Comment by zrno** [comment]
That is a good advice. Will ask the cpp extension people. Thanks
