### ISSUE TITLE
Interrupted search freezes Mac

### ISSUE THREAD

**Issue by chrisgordon** [microsoft/vscode#101634]
Issue Type: <b>Bug</b>

Using a Macbook Air 11" (High Sierra) with 24" external monitor, VS Code 1.46.1

I have a folder open that has many subfolders & files.
I type into the global Search to begin searching in the files.
While it's still in process of searching and showing results, I alter the search string.
Shortly after, mouse arrow changes to the "beachball" (not spinning) and everything is frozen
I have to restart with Ctrl+Cmd+Power

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 51, 32|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|-psn_0_77843|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
svn-scm|joh|2.11.4
easy-less|mrc|1.6.3
csharp|ms-|1.22.1
debugger-for-chrome|msj|4.12.8
vshaxe|nad|2.21.1

</details>

**Comment by roblourens** [comment]
Do you have any search settings set?

**Comment by chrisgordon** [comment]
No, I don’t have any particular search settings configured. Also, within the search box, case sensitive, whole word, and regex are NOT selected
-Chris

**Comment by roblourens** [comment]
Sorry, I don't have a clue what is going on. Tracking this in https://github.com/microsoft/vscode/issues/87254. Disabling searchOnType may help.
