### ISSUE TITLE
Favorite Commands

### ISSUE THREAD

**Issue by atok2amnh** [microsoft/vscode#101616]
I apologize in advance if a feature or a feature request exists for this already, I couldn't find anything similar in the backlog.

I find myself searching for a same commands several times in the command palette. 
What would improve my user experience and be really cool is:
1. Mark a command in the Command Palette as favorite 
2. Allow the assignment of keyboard shortcuts to a favorite command
3. Allow to group the favorite commands under a new menu item.
 e.g. **Favorite Commands** 
        Command 1    -keyboard-shortcut-
        Command 2   -keyboard-shortcut-

**Comment by IllusionMH** [comment]
> Allow the assignment of keyboard shortcuts to a favorite command

You can change or assign (additional) shortcuts to most of the commands with  `>Preferences: Open Keyboard Shortcuts` in Command Palette already.
