### ISSUE TITLE
"Join With Previous Cell" screen cheese

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#101620]
Cells like:
![image](https://user-images.githubusercontent.com/8586769/86393957-9d436000-bc52-11ea-9de6-e500ebd3679d.png)

Run join:
![image](https://user-images.githubusercontent.com/8586769/86393914-8c92ea00-bc52-11ea-8d68-64c8f33bf22e.png)

**Comment by rebornix** [comment]
Thanks, I can easily reproduce this issue.

**Comment by rebornix** [comment]
I think it's already fixed by @roblourens
