### ISSUE TITLE
Handlebars formatting will break inside styles

### ISSUE THREAD

**Issue by Razican** [microsoft/vscode#101603]
- VSCode Version: 1.46.1
- OS Version: Fedora Linux

Steps to Reproduce:

1. Create a Handlebars (.hbs) file with the following content:
```handlebars
<style>{{ onload_style }}</style>
```
2. Format the document.

Note how the formatted document will look like this:
```handlebars
<style>
    {
            {
            onload_style
        }
    }
</style>
```

Does this issue occur when all extensions are disabled?: Yes

Might be related to #67871.

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
