### ISSUE TITLE
vscode.window.activeTextEditor still set after focusing on webview

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#101682]
- VSCode Version:
![image](https://user-images.githubusercontent.com/55927613/86479139-7ca70300-bd43-11ea-8be6-d7f7b2739089.png)

- OS Version: Windows 10

Steps to Reproduce:

How to get  vscode.window.activeTextEditor  Undefined:
 - Open a TextEditor (just click any file that can be edited)
 - Open a Webview Panel
 - Focus on the TextEditor
 - Click anywhere in the Webview panel, but not in its tab (DON'T CLICK ON THE TAB)
 - Check that the vscode.window.activeTextEditor is Undefined

How to get  vscode.window.activeTextEditor  defined: THIS WORKS
 - Open a TextEditor (just click any file that can be edited)
 - Open a Webview Panel
 - Focus on the TextEditor
 - Click exactly in the --> TAB <--- of the Webview.
 - Check that the vscode.window.activeTextEditor is now defined

<b>Workaround:</b>
I added an event handler to my Webview to update a local activeTextEditor every time the Webview panel state changes.
````
didChangeViewState = ()=>{
    this.activeTextEditor = vscode.window.activeTextEditor;
}; 
````

<b>Expected Behavior:</b>
vscode.window.activeTextEditor should always get the latest TextEditor that was in focus before switching to any other tab

<b>Actual Behavior:</b>
vscode.window.activeTextEditor works only if clicked on the Panel Tab, when switching to a Webview.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by mjbvz** [comment]
This is by design. `activeTextEditor` always tracks the currently focused text editor. When you focus the webview, there is no longer a focused text editor

**Comment by AllanOricil** [comment]
No, you did not understand.
When I click inside the "TAB" of the Webview, it works. When I click in the Webview, it does not. Why?

**Comment by mjbvz** [comment]
The bug then is that it is defined. Whenever the webview is focused, `activeTextEditor `should never be defined

**Comment by AllanOricil** [comment]
> The bug then is that it is defined. Whenever the webview is focused, `activeTextEditor `should not be defined

Could we create a variable called `lastActiveTextEditor`?
I have a button in this extension https://marketplace.visualstudio.com/items?itemName=allanoricil.salesforce-soql-editor&ssr=false that appends text in the last active text editor. I had to implement that workaround to make it possible. But if I had this variable I would not need to rely on the change state event.
