### ISSUE TITLE
Deactivating the Github mastery repos from viscose after usage.

### ISSUE THREAD

**Issue by CS150-Alam** [microsoft/vscode#101673]
After pushing the files to the GitHub repository, I think that people should be able to have the feature of deactivating the GitHub auto mastery repos so that when people create a new file script, they do not need to face the issue of going into .gitignore to set the repository system to not detect the newly made files. Later when wanting to use it, we can later activate it.

**Comment by joaomoreno** [comment]
> GitHub auto mastery repos

What do you mean? What feature is this?
