### ISSUE TITLE
Can't delete big folders like the node-modules generated by Create React App

### ISSUE THREAD

**Issue by ProMikeCoder2020** [microsoft/vscode#101672]
- VSCode Version: 1.46.1(the latest version)
- OS Version:  10.0.18363 N/A Build 18363 (Microsoft Windows 10 Home)

Steps to Reproduce:

1. Run create-react-app since it generates a big node-modules
2. Now try to delete it
3. Then the editor will crash and the node-modules will remain there

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
How are you deleting the folder?

**Comment by ProMikeCoder2020** [comment]
I am using the del key

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
