### ISSUE TITLE
Unable to save notebook 

### ISSUE THREAD

**Issue by PaulHoefnagels** [microsoft/vscode#101691]
Issue Type: <b>Bug</b>

Im unable to save Jupyter Notebook (.ipynb). I tried multiple ways, but none of them works:
1. Ctrl + S (nothing happens)
2. Via File > Save (is permanent greyed out)
3. Via File > Save As... (nothing happends, no pop-up of the window explorer)
4. Pressing the save-button in the notebook (nothing happens)

My ipynb-file has changes (it's marked with a star).

See also: https://stackoverflow.com/questions/62718613/unable-to-save-jupyter-notebook-in-vsc

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.36.1
python|ms-|2020.6.91350
cpptools|ms-|0.28.3
autodocstring|njp|0.5.3

</details>

**Comment by evan-anderson-ts** [comment]
This is also happening to me on mac:

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (2 wks ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

OS Version: 
![image](https://user-images.githubusercontent.com/60150801/86517034-a61f6780-bdf3-11ea-99a2-5edf5095ccb0.png)

**Comment by dalidavila** [comment]
Same for me, after work a while in a notebook for some reason I don't know, the autosave function doesn't save any change that I make to the file, and the option "save as" (to try to save the changes as another file and not to lose my work :( ) doesn't work at all either!! 

literally I have to open a text editor, and copy all the work I have written, close vscode (It actually ask if I want to save changes but it doesn't save anything!), then open vscode again and take the code from the text editor to vscode again, what a waste of time. 

The files are in a git repository.

This happened to me several times now.

**Comment by rebornix** [comment]
Please file this issue against Python extension, which is currently providing this feature.

**Comment by dalidavila** [comment]
sorry wich extension is that?

**Comment by rebornix** [comment]
@dalidavila https://marketplace.visualstudio.com/items?itemName=ms-python.python I think this is the one you are using
