### ISSUE TITLE
Switching workspace shortcut (Ctlr+W) doesn't work when Terminal is active

### ISSUE THREAD

**Issue by jelnur** [microsoft/vscode#101661]
Issue Type: <b>Bug</b>

Open more than one project
Make sure pressing Ctrl+W activates workspace selector
Open Terminal windows and place cursor in it
Press Ctrl+W. Now workspace switch is not activated

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 4|
|Memory (System)|16.00GB (4.08GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
EditorConfig|Edi|0.15.1
vscode-docker|ms-|1.3.1
debugger-for-chrome|msj|4.12.8
vscode-extension-auto-import|Nuc|1.4.3
autoimport|ste|1.5.3
vscode-js-import|wan|0.15.5

</details>

**Comment by gjsjohnmurray** [comment]
Take a look at the `terminal.integrated.commandsToSkipShell` setting. More info [here](https://code.visualstudio.com/docs/editor/integrated-terminal#_forcing-key-bindings-to-pass-through-the-terminal).
