### ISSUE TITLE
Remote Containers gets you throttled with Marketplace 

### ISSUE THREAD

**Issue by EricHripko** [microsoft/vscode#101654]
- VSCode Version: 1.40.2
- Local OS Version: MacOS 10.14.5
- Remote OS Version: RHEL 7.7
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Work with a lot of projects using Remote Containers extension
2. Remote Containers downloads all extensions you specify
3. VSC Marketplace throttles you:
   ```
   Installing extensions...
   Installing extension 'ms-python.python' v2019.11.50794...
   Corrupt ZIP: end of central directory record signature not found
   ```

Does this issue occur when you try this locally?:
Yes, I can reproduce it by reaching out to the URL that (I believe) VSC uses to download the extensions.
```
$ curl https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2019.11.50794/vspackage
{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}
```

Does this issue occur when you try this locally and all extensions are disabled?:
No, since VSC doesn't download the extensions then.

VSC silently fails when an extension couldn't be downloaded - so I only find out it's broken when my IntelliSense or pylint is broken.
- Are there any solutions for this?
- Could Remote Containers pull extensions from the local installation?
- Could Remote Containers be configured to pull extensions from a custom URL (to vsix archive)?

**Comment by sandy081** [comment]
As said, there is not any throttling - https://github.com/microsoft/vscode/issues/101654#issuecomment-567388314.
