### ISSUE TITLE
Python 2.7 virtualenv Python Language Server error

### ISSUE THREAD

**Issue by xkotj** [microsoft/vscode#101699]
Issue Type: <b>Bug</b>

After creating virtualenv in WSL2:
virtualenv -p /usr/bin/python2.7 .venv

opening folder in WSL2:
code .

Virtual environment is activated, but no import works even standard imports like theese
import socket
import re
import json
import argparse

In Output tab in Python Language Server there is this error:
[Info  - 9:24:36 PM] Analysis cache path: /home/user/.cache/Microsoft/Python Language Server
[Info  - 9:24:36 PM] Microsoft Python Language Server version 0.5.51.0
[Info  - 9:24:36 PM] Workspace root: /home/user/Projects/helpdesk-ticket
[Info  - 9:24:37 PM] GetCurrentSearchPaths /home/user/Projects/helpdesk-ticket/.venv/bin/python2.7 
Traceback (most recent call last):
  File "/home/user/.vscode-server/extensions/ms-python.python-2020.6.91350/languageServer.0.5.51/get_search_paths.py", line 31, in <module>
    import site
  File "/home/user/Projects/helpdesk-ticket/.venv/lib/python2.7/site.py", line 165, in <module>
    main()
  File "/home/user/Projects/helpdesk-ticket/.venv/lib/python2.7/site.py", line 19, in main
    load_host_site()
  File "/home/user/Projects/helpdesk-ticket/.venv/lib/python2.7/site.py", line 54, in load_host_site
    full_path = os.path.abspath(os.path.join(here, path.encode("utf-8")))
LookupError: no codec search functions registered: can't find encoding

How can I troubleshoot this issue?
JK

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4

</details>

**Comment by rbtsolis** [comment]
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

**Comment by xkotj** [comment]
Hello,
it did not help setting those variables in schell and start **code .**
I have fixed it with editing file:
**/home/user/Projects/helpdesk-ticket/.venv/lib/python2.7/site.py**

changing this line
full_path = os.path.abspath(os.path.join(here, **path.encode("utf-8")**))

to this line
full_path = os.path.abspath(os.path.join(here, **path**))

I have second windows with same installation and WSL1 and there seems not to be this problem.

I have even configured same LANG and LC_ALL variables as it is on functional system and it did not work.

JK

**Comment by aeschli** [comment]
Is this related to VSCode ?

**Comment by xkotj** [comment]
Hello, 
I do not know yet. Maybe its combination of virtualenv, python server extension and vscode and wsl2.
I will close this issue and try to ask in python extension github.
JK
