### ISSUE TITLE
Notebooks: Find widget UX

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#101602]
Verifying https://github.com/microsoft/vscode/issues/99371

Related to the find widget:

- It doesn't highlight changes as I type
- When it opens, the entire text inside the find widget should be selected
- The input background color fails to update as the user switches themes (eg switch from light to black)

**Comment by rebornix** [comment]
> It doesn't highlight changes as I type

Fixed via https://github.com/microsoft/vscode/commit/dab68ed88523db7e7161f69da791b8c7e87c99c8

> The input background color fails to update as the user switches themes (eg switch from light to black)

Fixed via https://github.com/microsoft/vscode/commit/dab68ed88523db7e7161f69da791b8c7e87c99c8
