### ISSUE TITLE
Can't respond to keyboard inputs

### ISSUE THREAD

**Issue by brainvader** [microsoft/vscode#101742]
- VSCode Version: 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d x64)
- OS Version: 5.4.0-40-generic/Ubuntu 20.04

Steps to Reproduce:

1. Writing Rust code
2. Keyboard was suddenly not working
3. Restart/reload temporarily resolves this issue, but it raises again after moving back from other applications like browser.

* I didn't any updates or change to VSCode or OS before this happened
* I tried to reboot OS and re-install VSCode
* CPU is not busy and memory has enough space

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@brainvader I'm sorry, but I never observed this behaviour. Are there some specific steps to it?

**Comment by brainvader** [comment]
Thank you for sparing time and replying quickly. I can solve the issue by doing clean install ubuntu 20.04. I'm new to ubuntu, so It clear that I don't make a lot of changes to it. I'm not sure what actually make VSCode disable keyboard input, but one thing I remember is that I installed [intel ax200 firmware](https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi) since bluetooth was kept turning off.

**Comment by alexdima** [comment]
@brainvader when this problem occurs, is it just VS Code that stops receiving input? How about if you go to `Help > Toggle Developer Tools`, can you type in the developer tools console?

**Comment by brainvader** [comment]
We had to open developer console, but I didn't. For my environment, everything was working fine except for VSCode. I could raise this issue without any glitches while typing. Some keyboards, say j or p, are still able to type in.

**Comment by alexdima** [comment]
> We had to open developer console, but I didn't. 

I'm not sure I understand. When the problem occurs, are you able to use `Help > Toggle Developer Tools` and type in the developer tools console?

**Comment by brainvader** [comment]
Sorry for the late reply. I can't type in  the developer tools console too.

![Screenshot from 2020-07-24 22-42-33](https://user-images.githubusercontent.com/40913024/88397830-79ada880-cdff-11ea-84e4-e805dc7f666f.png)

**Comment by Leko** [comment]
@alexdima I'm facing the same problem. How can I get you an information for debugging? I cannot use devtools too because keyboard is not working. But I can copy text from another software and past it to VSCode.

VSCode Version: 1.47.3 91899dcef7b8110878ea59626991a18c8a6a1b3e x64
OS Version: Ubuntu 20.04.1 LTS

**Comment by Leko** [comment]
#103587 seems to be related.

**Comment by alexdima** [comment]
Thank you for the extra information. @deepak1556 from the following comments, this appears to me to be an Electron issue, not an issue specific to VS Code:

https://github.com/microsoft/vscode/issues/101742#issuecomment-663547194
> Additionally, the same thing happened in GitKraken that also uses Electron.

https://github.com/microsoft/vscode/issues/101742#issuecomment-667809241
> I cannot use devtools too because keyboard is not working.

**Comment by deepak1556** [comment]
Thanks @alexdima 

@brainvader @Leko how did you install code, Is it via snap ? If so, what does `snap version` return ?

**Comment by Leko** [comment]
@alexdima Thank you for the reply!

> this appears to me to be an Electron issue

I think so too. I tried to add logs to the vscode and run it locally, but the keydown event didn't fire in the first place.
It's Electron's problem I guess.

```diff
diff --git a/src/vs/base/browser/dom.ts b/src/vs/base/browser/dom.ts
index f203119f8f..26227695e9 100644
--- a/src/vs/base/browser/dom.ts
+++ b/src/vs/base/browser/dom.ts
@@ -144,6 +144,7 @@ function _wrapAsStandardMouseEvent(handler: (e: IMouseEvent) => void): (e: Mouse
 }
 function _wrapAsStandardKeyboardEvent(handler: (e: IKeyboardEvent) => void): (e: KeyboardEvent) => void {
 	return function (e: KeyboardEvent) {
+		console.log('_wrapAsStandardKeyboardEvent', e)
 		return handler(new StandardKeyboardEvent(e));
 	};
 }
```

**Comment by Leko** [comment]
@deepak1556 I installed code via apt rather than snap.

**Comment by Leko** [comment]
I found a workaround for this problem. But I have no idea why it works.

1. Switch window between vscode and another app quickly
2. Then type any characters promptly
3. (Repeat 1-2 several times)

In the screen capture, it looks like I'm not typing any keys, but I'm typing keys such as 123123123... to the vscode while my screen is recording.

![Peek 2020-08-04 01-15](https://user-images.githubusercontent.com/1424963/89204721-87c6aa80-d5f1-11ea-9660-620e8f61f668.gif)

**Comment by ckerr** [comment]
Maybe this was mentioned and I missed it, but if I wanted to reproduce this on my own system, is there a way to consistently trigger the issue?

**Comment by brainvader** [comment]
@deepak1556 I downloaded .deb from the official download site and installed code.
