### ISSUE TITLE
Search sidebar: Disable search while typing.

### ISSUE THREAD

**Issue by jbnv** [microsoft/vscode#101726]
Is there a way to disable automatic search while typing criteria in the Search sidebar? The automatic search is virtually useless, especially when using regular expressions which i do all the time. And it's an *incredible* drag on performance. 

I apologize if this is answered elsewhere; I tried multiple searches both in this repository and in the Internet in general and didn't find an answer.

**Comment by ArturoDent** [comment]
Disable the setting;

`Search: Search On Type`  it is on by default.

**Comment by jbnv** [comment]
Thanks.
