### ISSUE TITLE
Under German QWERTZ keyboard layout, the Edit menu shows incorrect keybinding for Toggle Line Comment

### ISSUE THREAD

**Issue by lusitania** [microsoft/vscode#101754]
Issue Type: <b>Bug</b>

Open a page, write something, press the key combination ctrl-shift-7 (shift-7 is the / character) as hinted in the menu. nothing happens.

In File -> Preferences -> Keyboard Shortcuts I found the binding set to ctrl-#. This shortcut works. Either way the menu hints are out of sync with the actual binding.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.44GB free)|
|Process Argv|--remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Dockerfile|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz (2 x 1607)|
|Memory (System)|1.94GB (0.46GB free)|
|VM|0%|
</details>

**Comment by alexdima** [comment]
> File -> Preferences -> Keyboard Shortcuts I found the binding set to ctrl-#

This is the "real" keybinding.

I believe the menus could be misbehaving. Can you please include a screenshot of the `Edit` menu?

**Comment by lusitania** [comment]
![image](https://user-images.githubusercontent.com/4135918/86567058-071d7b80-bf6b-11ea-859f-51c565c8fb58.png)
after I `Reset Keybinding` for `Toggle Line Comment` in `Keyboard Shortcuts` to `Ctrl + #` 

![image](https://user-images.githubusercontent.com/4135918/86567316-76936b00-bf6b-11ea-9d3a-b432385ff9e2.png)

**Comment by alexdima** [comment]
@lusitania What keyboard layout have you configured in Windows?

**Comment by lusitania** [comment]
Keyboard: QWERTZ (German)
Locale: en-IE

**Comment by gomker** [comment]
I have the same problem however, it seems to be affecting only certain file types. 
For me anything "terraform" associated is not working right now. Via the menu and keyboard shortcut.

I have checked to see if I had any duplicate keybindings for Control + /

**Comment by i-jk13** [comment]
i am having a similar problem i tried using the ctrl+/ to comment but it does not work.

**Comment by olafgeibig** [comment]
> I have the same problem however, it seems to be affecting only certain file types.
> For me anything "terraform" associated is not working right now. Via the menu and keyboard shortcut.
> 
> I have checked to see if I had any duplicate keybindings for Control + /

For me the same: doesn't work on terraform files

**Comment by awkwrd** [comment]
> > I have the same problem however, it seems to be affecting only certain file types.
> > For me anything "terraform" associated is not working right now. Via the menu and keyboard shortcut.
> > I have checked to see if I had any duplicate keybindings for Control + /
> 
> For me the same: doesn't work on terraform files

Confirmed
doesn't work on terraform `.tf` files

**Comment by alexdima** [comment]
@olafgeibig @awkwrd This issue is about the menu displaying the shortcut incorrectly when using the German Keyboard layout on Windows (`QWERTZ (German)`). It looks like your problem might be unrelated if it is only a problem in terraform files.

**Comment by alexdima** [comment]
It looks like this got broken way back in January 2019 (1.31), and I think it happened when we upgraded to Electron 3.0

To reproduce, simply configure to use the German QWERTZ keyboard layout in Windows and launch VS Code 1.30 and look at the Edit menu:

| VS Code 1.30 | VS Code 1.31 |
|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101495419-d81b9380-3968-11eb-9543-464c4060a7be.png) | ![image](https://user-images.githubusercontent.com/5047891/101495593-0305e780-3969-11eb-9275-00dc204ccfb1.png) |

**Comment by alexdima** [comment]
This appears to be an upstream issue, first introduced via Electron 3.0. I have created https://github.com/electron/electron/issues/26888

cc @deepak1556 @bpasero

**Comment by alexdima** [comment]
I've pushed a workaround and are now falling back to rendering these keybindings similar to how we render other keybindings that Electron cannot parse (like chords):

![image](https://user-images.githubusercontent.com/5047891/101516996-7830e700-3980-11eb-94fc-4f5484b298b2.png)

**Comment by deepak1556** [comment]
@alexdima the upstream issue has been fixed, should we revert https://github.com/microsoft/vscode/commit/838b3949ec8da1cdc0375d85209b7f3bd67fb9b0 ?

**Comment by alexdima** [comment]
@deepak1556 :+1: I've created https://github.com/microsoft/vscode/issues/126347 to investigate removing various Electron workarounds from this area that we added over the years.
