### ISSUE TITLE
Can not find namespace

### ISSUE THREAD

**Issue by ctien** [microsoft/vscode#101784]
index.d.ts
```sh
export = CTCart;
export as namespace CTCart;
declare namespace CTCart {
  interface Test{
    str: string;
  }
}
```
When i use it in other file
```sh
const initialState: CTCart.Test = {
  str: "string",
};
export default initialState;
```
Its often appears error: "Cannot find namespace 'CTCart'. ts(2503)". Sometimes received, sometimes not. This error only appears on vscode. Its okay on other editors. My code is still good to run. But its hard to focus on my work. Hope you fix it. Thank you!

**Comment by ctien** [comment]
[use file](https://raw.githubusercontent.com/ctien/bugs/master/Screenshot%20from%202020-07-06%2005-13-47.png)
[declare file](https://raw.githubusercontent.com/ctien/bugs/master/Screenshot%20from%202020-07-06%2005-13-55.png)

**Comment by mjbvz** [comment]
Do you have a [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) file? This tells VS Code that the two files are part of the same project

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate

Sounds like a configuration question from the symptoms
