### ISSUE TITLE
Codespaces - saving ports for future use

### ISSUE THREAD

**Issue by taniotanio7** [microsoft/vscode#101766]
I'm developing new front-end project with firebase emulators. This requires to forward **many ports** to my local device.
It would be great to have those ports saved between sessions, so I don't have to set them up every time I open the project and restore the remote machine.

![Project with many ports forwarded](https://user-images.githubusercontent.com/4144459/86542105-ca259a80-bf12-11ea-93a7-a998bca63bee.png)

**Comment by alexr00** [comment]
Thanks for the issue! The folks working on Codespaces are moving the port forwarding UI from your screen shot to the same unified port forwarding solution that SSH and Containers use. The new port forwarding solution already has setting for restoring ports (`remote.restoreForwardedPorts`). Once they're done moving to the new port UI, that setting will do what you're looking for.

@fara-nak FYI
