### ISSUE TITLE
Custom grouping for plugins

### ISSUE THREAD

**Issue by lancerXXXX** [microsoft/vscode#101781]
![image](https://user-images.githubusercontent.com/42160297/86574596-a6ad2f00-bfa8-11ea-9939-f4ec7b0eb687.png)

Custom grouping, easy to manage a large number of  extensions

**Comment by mohamedGamalAbuGalala** [comment]
Related to: [#40239, #20599, #49826, #35891, #40239] and they all pass the 20 votes.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/20599
