### ISSUE TITLE
Shift key cancels accented IME input with fcitx 

### ISSUE THREAD

**Issue by tduyduc** [microsoft/vscode#101751]
Issue Type: <b>Feature Request</b>

Actually a feature counter-request.
Starting from Chromium version 79, an IME feature (?) might cause issues and nuisances for user input in Linux.
There are bug reports about this matter [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1086946), [here](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1861882), and [here](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1859294), and all of them haven't been resolved yet.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 4.15.0-106-generic

**Comment by NotWearingPants** [comment]
The next Electron version (8) includes an update to Chrome 80

Comment on the update issue if you know of problems -#100731

**Comment by tduyduc** [comment]
> The next Electron version (8) includes an update to Chrome 80
> 
> Comment on the update issue if you know of problems - #100731

Thanks! I'll write a comment there to let more people know about the potential issues.

**Comment by deepak1556** [comment]
Thanks for the heads up, since chromium team doesn't consider this a high priority bug I don't think this deems to block from updating to chromium 80 and higher. We will continue to track the upstream bug and incase a fix is available, it can be backported.

**Comment by faea726** [comment]
I'm facing the same issue here. Not only chrome, discord also.

**Comment by tduyduc** [comment]
> I'm facing the same issue here. Not only chrome, discord also.

It seems that Discord also uses Electron for its app. Any app that uses Electron with Chrome 79+ would introduce this issue.

**Comment by deepak1556** [comment]
Closing as issue has been resolved in upstream.
