### ISSUE TITLE
IntelliSense vscode.Uri missing

### ISSUE THREAD

**Issue by rwnkl** [microsoft/vscode#101792]
- VSCode Version: 1.46.1
- OS Version: Windows 10 Prof

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rwnkl** [comment]
IntelliSense: class vscode.Uri - static method  joinPath() is missing

**Comment by JacksonKearl** [comment]
Is this a new problem? Does it appear in the `.d.ts` you're using for `vscode`?

**Comment by rwnkl** [comment]
Problem isn't new.
File: Microsoft VS Code\resources\app\out\vs\vscode.d.ts          (v. 1.46.1)
Notepad++ Line 1301:  static joinPath(base: Uri, ...pathSegments: string[]): Uri;

**Comment by JacksonKearl** [comment]
This is in extension development, correct? Does the `node_modules/@types/vscode/index.d.ts` exist and contain `Uri.joinPath`?

**Comment by rwnkl** [comment]
Yes is in extension dev. The  node_modules/@types/vscode/index.d.ts exist and Uri.joinPath is missing!

**Comment by JacksonKearl** [comment]
Can you upgrade the types install? `npm install --upgrade @types/vscode`

**Comment by rwnkl** [comment]
I ran   npm install. 
Now file node_modules/@types/vscode/index.d.ts is up to date again.
Thank you for your help.
