### ISSUE TITLE
Can not use extension.

### ISSUE THREAD

**Issue by gone2808** [microsoft/vscode#101721]
Extension host terminated unexpextedly

**Comment by gone2808** [comment]
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

+List of extensions that you have installed
![image](https://user-images.githubusercontent.com/54107885/86527450-02a08680-bec9-11ea-957d-b3ff37383ea8.png)
![image](https://user-images.githubusercontent.com/54107885/86527451-07fdd100-bec9-11ea-80a5-84b2e9d00726.png)
![image](https://user-images.githubusercontent.com/54107885/86527454-0df3b200-bec9-11ea-9849-5877512df7a1.png)
![image](https://user-images.githubusercontent.com/54107885/86527457-12b86600-bec9-11ea-9697-53c6fabf1eb7.png)
![image](https://user-images.githubusercontent.com/54107885/86527461-164bed00-bec9-11ea-87c7-ff12e4961fc5.png)
![image](https://user-images.githubusercontent.com/54107885/86527463-18ae4700-bec9-11ea-8d09-6f51bd3f6234.png)


+Steps that cause the issue: 
̀5/5/2020, When opened Vscode, I Have taken this bug
// It said 
"Extension host terminated unexpextedly" => I cant use any extensions.
![image](https://user-images.githubusercontent.com/54107885/86527499-75a9fd00-bec9-11ea-8bdf-9a7f13a26b21.png)
and also Can't Restart Extension Host

**Comment by gone2808** [comment]
![image](https://user-images.githubusercontent.com/54107885/86527808-93c52c80-becc-11ea-818b-b5fab4a53e9e.png)
I dont know how to show the detail about errors

**Comment by alexdima** [comment]
Does the extension host crash when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)
