### ISSUE TITLE
IntelliSense breaks on files using `import` or `export`

### ISSUE THREAD

**Issue by ekr3peeK** [microsoft/vscode#101780]
- VSCode Version: 1.46.1
- OS Version: Microsoft Windows 10

I do not know if this is a bug, or an inteded feature, but when I am trying to rely on autosuggestion from the Javascript IntelliSense, Visual Studio Code does not parse files using `import` or `export` statements for types.

Steps to Reproduce:

1. Create a new empty workspace
2. Create file `myclass.js`

```
class MyClass {
    ... class methods here
}
```

3. Create file `index.js`

```
/** @type {MyClass} */
let instanceOfMyClass;
```

4. Now I get suggestions on methods available in `MyClass` in `index.js` file.

5. Add an import statement to `myclass.js`, ie: `import jQuery from 'jQuery'`;

6. Now I do not see any autosuggestion on methods available in `MyClass` in `index.js` file.

The same applies when running VSCode without extensions.

**Comment by mjbvz** [comment]
By adding the `import` to `myclass.js` you have made the file into a module. Modules are isolated so their variables are not globally accessible. Instead you must import `MyClass` to use it

**Comment by ekr3peeK** [comment]
Okay, so basically, if I have an ES6 class definition inside a module, I instantiate that class in some file, and then start passing it over to different modules as a parameter (the instantiated variable, not the definition itself), it means that I have to also manually import my module with the definition in each and every file? Because this seems a bit like an overkill to me...

**Comment by mjbvz** [comment]
You can use import types for this case: https://github.com/Microsoft/TypeScript/issues/23692#issuecomment-384599074
