### ISSUE TITLE
Option -g from command line with multiple files doesn't work well

### ISSUE THREAD

**Issue by tokoharu** [microsoft/vscode#101714]
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCode from command line : `code -g A.txt:10 B.txt:10`
2. If I executed from Windows Power Shell, VS Code didn't open.
3. If I executed from WSL, VS Code opened and cursor is at A.txt:10.
   But, cursor of tab B.txt is at 1st line (not 10th line). 

[Documentation of VSCode](https://code.visualstudio.com/docs/editor/command-line#_opening-files-and-folders) says following.

> Used with the -g argument. Name of a file to open at the specified line and optional character position. You can specify multiple files in this manner,...

Does this issue occur when all extensions are disabled?: Yes

**Comment by MarekLew** [comment]
First. This command must have form:
code -g a.txt:10 -g b.txt:10
But this form don't work too.Vsc Comand line  parser is not secfencional. Not different:
code -g a.txt
Or:
code a.txt -g
Not multii Comand in one line suported.

**Comment by kyuridenamida** [comment]
@MarekLew  Hi! Can I know why `code -g a.txt:10 -g b.txt:10` is a valid form, while `code -g A.txt:10 B.txt:10` is not?

The documentation explicitly says:

> You can specify multiple files in this manner, but you must use the -g argument (once) before using the file:line[:character] specifier.

According to this explanation, `code -g A.txt:10 B.txt:10` is still one of the expected forms. Otherwise, the documentation is a little bit outdated or misleading.  'm still not sure what behavior is reasonable though.

**Comment by MarekLew** [comment]
@kyuridenamida Comand line parser used in VSC not recognize position parameters "a.txt" and swich "-g". It's frustrating and useless when you want to do more than open a file. You must use "-g" not because it works later, but because the second one will not be recognized :)

**Comment by tokoharu** [comment]
@bpasero Hello, thank you for checking my issue. Then, you added the duplicate label, but I couldn't find precedent issue relevant to this issue.

I want to follow discussions about this problem, so could you tell me which issue is the precedent one?

Regards.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/58023

**Comment by tokoharu** [comment]
Thank you!
