### ISSUE TITLE
Literally "Select all" 

### ISSUE THREAD

**Issue by Phisherman** [Microsoft/vscode#10172]
- VSCode Version: 1.4.0
- OS Version: Windows 10 Enterprise 2015 LTSB

Steps to Reproduce: Sorry, I can't really reproduce it.

If I select all text in a tab sometimes VS Code also selects the text from other tabs and from the terminal too. If I switch to another tab, switch back, deselect the text and select it again it just works fine.

**Comment by aeschli** [comment]
How do you select all? Ctrl + A?

**Comment by Phisherman** [comment]
Yes.

**Comment by alexandrudima** [comment]
@Phisherman Is the mouse involved somehow when you hit this problem? i.e. is the selection you see looking like a "browser" selection:

![image](https://cloud.githubusercontent.com/assets/5047891/17429810/0fa877f6-5af1-11e6-8378-0fcd49b4afd4.png)

**Comment by Phisherman** [comment]
In my humble opinion it looked like the regular VS Code selection.

For the sake of completeness: The dev console didn't show an error.

**Comment by alexandrudima** [comment]
This is the handler for `selectAll` - https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/config.ts#L489 -

```
function selectAll(accessor: ServicesAccessor, args: any): void {
	let HANDLER = editorCommon.Handler.SelectAll;

	let focusedEditor = findFocusedEditor(HANDLER, accessor, false);
	// Only if editor text focus (i.e. not if editor has widget focus).
	if (focusedEditor && focusedEditor.isFocused()) {
		focusedEditor.trigger('keyboard', HANDLER, args);
		return;
	}

	// Ignore this action when user is focussed on an element that allows for entering text
	let activeElement = <HTMLElement>document.activeElement;
	if (activeElement && ['input', 'textarea'].indexOf(activeElement.tagName.toLowerCase()) >= 0) {
		(<any>activeElement).select();
		return;
	}

	// Redirecting to last active editor
	let activeEditor = getActiveEditor(accessor);
	if (activeEditor) {
		activeEditor.focus();
		activeEditor.trigger('keyboard', HANDLER, args);
		return;
	}
}
```

**Comment by jrieken** [comment]
Closing since we have removed the `when` clause

**Comment by alexandrudima** [comment]
Issue with steps: #10222
