### ISSUE TITLE
sql mode error comment colors

### ISSUE THREAD

**Issue by andreescastano** [microsoft/vscode#101701]
Issue Type: <b>Bug</b>

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

In the SQL language the line comments are made with (--) and Vscode is coloring the lines that contain (##)

![2020-07-03 14_58_45-Clipboard](https://user-images.githubusercontent.com/47229833/86495191-ea503080-bd3d-11ea-9e51-8f3be6da79d9.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.91GB (10.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

**Comment by alexr00** [comment]
What theme are you using? I'm seeing the `--` comment line colored as a comment. Does this issue reproduce if you disable all extensions?
![image](https://user-images.githubusercontent.com/38270282/86596363-60e96a00-bf9a-11ea-95a6-4decb0985232.png)

**Comment by andreescastano** [comment]
> What theme are you using? I'm seeing the `--` comment line colored as a comment. Does this issue reproduce if you disable all extensions?
> ![image](https://user-images.githubusercontent.com/38270282/86596363-60e96a00-bf9a-11ea-95a6-4decb0985232.png)
> 
> ```sql
> -- comment 
> 	SELECT *
> 	FROM ##SOMETHING
> 	WHERE 1=1
> ```

**Comment by andreescastano** [comment]
> > What theme are you using? I'm seeing the `--` comment line colored as a comment. Does this issue reproduce if you disable all extensions?
> > ![image](https://user-images.githubusercontent.com/38270282/86596363-60e96a00-bf9a-11ea-95a6-4decb0985232.png)
> > ```sql
> > -- comment 
> > 	SELECT *
> > 	FROM ##SOMETHING
> > 	WHERE 1=1
> > ```

You are right, I had the Azure Data Lake Tools extension enabled, disabling it fixes the problem. Thank you very much
