### ISSUE TITLE
Notebooks: cell background makes it look heavier

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101710]
I just looked at how notebooks used to be in stable and prefer it actually over our current designs with regards to the background color on cell. Compare the initial look of a notebook.

**Stable**
![image](https://user-images.githubusercontent.com/900690/86507270-3ef3ba00-bdd7-11ea-93ed-ba04706ec9a8.png)

**Insiders**
![image](https://user-images.githubusercontent.com/900690/86507278-50d55d00-bdd7-11ea-8d40-982f4a65cef5.png)

Maybe the cell selection background could be optional for people that want it?

**Comment by bpasero** [comment]
One particular issue seems to be that we automatically put focus into the first cell each time you open a notebook.

**Comment by misolori** [comment]
+1 for not having the first cell auto-focused

**Comment by rebornix** [comment]
If we don't focus the first cell by default, we should make sure arrow keys can focus the cells to make it keyboard accessible.

**Comment by roblourens** [comment]
I can focus the list but not the cell

**Comment by roblourens** [comment]
I was implementing this but it will only have an affect once per notebook. After that, some cell will probably be focused and then persisted as the focused cell. So I can put it in but does it really make a difference?

**Comment by roblourens** [comment]
Unless you were all talking about not focusing any cell by default when opening a notebook, which I think we should definitely do, same as restoring your cursor position in an editor.

**Comment by roblourens** [comment]
Hopefully it's better without the shadow at least. I don't want to do anything to get rid of cell focus.
