### ISSUE TITLE
Semantic token provider does not react properly to batched edits

### ISSUE THREAD

**Issue by mrakgr** [microsoft/vscode#101744]
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Description:

Rapid pressing `qwe` into the first line of [this file](https://github.com/mrakgr/The-Spiral-Language/blob/31b6b7ef61e5101f1546b31cb79da6a29ec67570/VS%20Code%20Plugin/spiral/src/b.spi) does not result in correct highting. As the messages sent between the editor and the server are correct, and the error does not occur when I slowly press `q`, `w` and `e`, I suspect this is a bug in the semantic token provider.

For the error to manifest, a token needs to be added so just selecting something on the first line and rapid replacing it will not trigger the issue. Two tokens, `e` and `a` in this case, also have to be present after the first line for the issue to trigger.

My suspicion is that when the server returns multiple edits in a batch, the provider does something wrong.

Steps to Reproduce:

1. Run the extension. It is important that the extension be run before the server otherwise the messages might go out of order.
2. Run the server.
3. Type `qwe` rapidly on the first line.

I am printing the messages the server receives on the command prompt and see this.

```
Server bound to: tcp://*:13805
0, FileOpen
  { spiPath =
             "c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\spiral\src\b.spi"
    spiText = " qwe qwe qwe qwea qwe w ee
e
a" }
1, FileTokenAll
  { spiPath =
             "c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\spiral\src\b.spi" }
2, FileChanged
  { spiEdits = [||]
    spiPath =
             "c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\spiral\src\b.spi" }
3, FileChanged
  { spiEdits = [|{ from = 0
                   lines = [|"q qwe qwe qwe qwea qwe w ee"|]
                   nearTo = 1 }|]
    spiPath =
             "c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\spiral\src\b.spi" }
4, FileChanged
  { spiEdits = [|{ from = 0
                   lines = [|"qw qwe qwe qwe qwea qwe w ee"|]
                   nearTo = 1 }|]
    spiPath =
             "c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\spiral\src\b.spi" }
5, FileChanged
  { spiEdits = [|{ from = 0
                   lines = [|"qwe qwe qwe qwe qwea qwe w ee"|]
                   nearTo = 1 }|]
    spiPath =
             "c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\spiral\src\b.spi" }
6, FileTokenChanges
  { spiPath =
             "c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\spiral\src\b.spi" }
[|(0, 40,
   [|0; 0; 1; 0; 0; 0; 2; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 4; 0; 0;
     0; 5; 3; 0; 0; 0; 4; 1; 0; 0; 0; 2; 2; 0; 0; 1; 0; 1; 0; 0|]);
  (0, 45,
   [|0; 0; 2; 0; 0; 0; 3; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 4; 0; 0;
     0; 5; 3; 0; 0; 0; 4; 1; 0; 0; 0; 2; 2; 0; 0; 1; 0; 1; 0; 0|]);
  (0, 45,
   [|0; 0; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 4; 0; 0;
     0; 5; 3; 0; 0; 0; 4; 1; 0; 0; 0; 2; 2; 0; 0; 1; 0; 1; 0; 0|])|]
```

Messages 0 and 1 happen when the file opens and that does the initial highlight. That is fine.

Messages 2,3,4 are for `q`,`w`,`e`. key presses. Since they are fast, the changes get batched and released in one go when the semantic token provider makes a request for them. Had I pressed `q`, `w`, `e` slowly, there would have been 3 separate `FileTokenChanges` requests, one for each edit and the bug would not occur in that case.

This last thing...

```
[|(0, 40,
   [|0; 0; 1; 0; 0; 0; 2; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 4; 0; 0;
     0; 5; 3; 0; 0; 0; 4; 1; 0; 0; 0; 2; 2; 0; 0; 1; 0; 1; 0; 0|]);
  (0, 45,
   [|0; 0; 2; 0; 0; 0; 3; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 4; 0; 0;
     0; 5; 3; 0; 0; 0; 4; 1; 0; 0; 0; 2; 2; 0; 0; 1; 0; 1; 0; 0|]);
  (0, 45,
   [|0; 0; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 4; 0; 0;
     0; 5; 3; 0; 0; 0; 4; 1; 0; 0; 0; 2; 2; 0; 0; 1; 0; 1; 0; 0|])|]
```

...are the edits sent to the semantic token provider. I compared them with the ones when the keys are pressed slowly and they are identical.

Link: https://github.com/mrakgr/The-Spiral-Language/tree/31b6b7ef61e5101f1546b31cb79da6a29ec67570

As an aside, since I want to get this running I'd be willing to look into the semantic provider itself, but when I tried building VS Code several months ago I had no luck. Back then I was completely fresh to Javascript, so I'll give this a try again now that I have some more experience, but if I get stuck again (which I suspect will be the case) I hope I can get some guidance for how to build the massive thing.

Also, a short term solution for this might be to use the ranged version of the semantic token provider. Even though right now I am just trying to save code here by not having to reimplement tokenization for my language in TS, later I might have multiple passes and the range provider does not have a trigger. I am not pleased with the current design of the provider, it would have made more sense to treat semantic tokens similarly to diagnostics and decorations. That would have made it easier to associate the triggers to file changes. Right now it has a layer of indirection where the semantic token provider itself has to make a separate request.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mrakgr** [comment]
Here is the screen before pressing `qwe`. Note how the token on the first line are all blue indicating they are variables.

![Highlighting initial](https://user-images.githubusercontent.com/6266635/86530540-cb76a900-beb9-11ea-9ac6-b19a8055d40c.png)

After pressing `qwe` in rapid succession. Now they are gray.

![Highlighting error after rapid-pressing qwe](https://user-images.githubusercontent.com/6266635/86530538-ca457c00-beb9-11ea-89b5-056e7b606c48.png)

**Comment by mrakgr** [comment]
Much like last time, I am running into issues trying to build VS Code on Window. Until I get some advice on the `vscode-dev` slack channel on how to do that, I won't touch this issue myself.

**Comment by alexdima** [comment]
@mrakgr 
It is incorrect for the language server to reply with the same data both when 3 requests are made and when 1 request is made.


Can you please explain what is the format of this:

```
[|(0, 40,
   [|0; 0; 1; 0; 0; 0; 2; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 4; 0; 0;
     0; 5; 3; 0; 0; 0; 4; 1; 0; 0; 0; 2; 2; 0; 0; 1; 0; 1; 0; 0|]);
  (0, 45,
   [|0; 0; 2; 0; 0; 0; 3; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 4; 0; 0;
     0; 5; 3; 0; 0; 0; 4; 1; 0; 0; 0; 2; 2; 0; 0; 1; 0; 1; 0; 0|]);
  (0, 45,
   [|0; 0; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 3; 0; 0; 0; 4; 4; 0; 0;
     0; 5; 3; 0; 0; 0; 4; 1; 0; 0; 0; 2; 2; 0; 0; 1; 0; 1; 0; 0|])|]
```

**Comment by mrakgr** [comment]
The type of the above format is `(int * int * int []) []`. So it is an array of edits. Whenever I do a change on a line, it retokenizes the whole line. This is suboptimal, but it is easier for me to do. The tuples are passed as arguments to the `SemanticTokensEdit` constructor. [See here.](https://github.com/mrakgr/The-Spiral-Language/blob/31b6b7ef61e5101f1546b31cb79da6a29ec67570/VS%20Code%20Plugin/src/index.ts#L85)

In the edit, the first int is the offset - since I've been working on the first line, the offset is 0 in the first edit.

The second int is the delete count. This is the number of tokens on that line + 1 token past that line (as line delta for it needs to be adjust) times 5. You see it is 40 on the first edit, meaning it is replacing 8 tokens, but once I write `q` it adds that token on the line and it is 45 on the subsequent ones.

The third field of the tuple is the data array. You can see the data for the first and the second token being affected as I write `qwe`.

**Comment by mrakgr** [comment]
My recommendation, you should do a test for the semantic token provider that tests whether a batch of edits passed all at once is the same as them being applied sequentially. Right now, it would probably fail.

**Comment by alexdima** [comment]
@mrakgr Thank you for clarifying. Those are illegal edits. An array of edits do not transform the result sequentially. All the edits must have coordinates that refer to indices in the original.

So for example, editing the following:
`a b c d e f` into `b c x e f` can be represented with the following two edits:
`[0, 1, []], [3, 1, [x]]`. These edits mean: delete index 0 in the original and replace index 3 in the original with `x`. Notice how the index of `d` is `3` because that is the index in the original array. The edits are not applied sequentially.

So having three overlapping edits like in your example is illegal.

**Comment by mrakgr** [comment]
Uf, that kind of design will make things complicated. What is the right choice here?

1) I try really hard to figure out how to optimize those overlapping edits into something that is legal. I don't suppose you know a way to do that efficiently for an arbitrary batch of edits? This kind of things feels like an interesting programming puzzle.

2) You make those edits not illegal and I go back to the change-based semantic token provider in that commit.

3) I stick with the range provider that I am using currently.

I guess I'll take some time to try the first one, but otherwise I'll stick with the range provider even though there is some flickering associated with it.

One thing that would make things a lot easier, is to make a provider that merges the capabilities of the range and the changes provider - instead of assuming a flat array of tokens, why not use an array of an array of tokens? Meaning, you arrange them per line. That would make it easy for the editor to index into them.

Some languages have multiline tokens for things like multiline strings and comments, but you can take care of that case by splitting them into multiple tokens, one for each line.

**Comment by mrakgr** [comment]
Ok, I gave the first one some thought. It is not impossible, but optimizing (arbitrary) overlapping edits into non-overlapping form is definitely very hard. Considering the worst case scenario in terms of batched edits is the one I showed above, where the user types several keys rapidly, it is not worth it for me to mess with this. It is not going to kill the computer to change the array a few times in a sequence.

Either way, I will consider these sequential edits being illegal a bug and shift the onus on you to fix this. It would definitely be much easier for you to make batched edits sequential in VS Code than for me to make them non-overlapping on my own side.

**Comment by mrakgr** [comment]
By the way...

> An array of edits do not transform the result sequentially. All the edits must have coordinates that refer to indices in the original.

> So for example, editing the following: `a b c d e f` into ` b c x e f` can be represented with the following two edits: `[0, 1, []], [3, 1, [x]]`.

The offsets for this make no sense to me. Shouldn't this be `[0, 1, []], [6, 1, [x]]`? Because `d` is at 6 in the original array. Even without that `a` it would be at 5.

**Comment by alexdima** [comment]
One way to implement this on the server side is:
* when getting a semantic tokens request, save the reply in memory (`R0`)
* when text edits come in, don't do anything
* when the next semantic tokens request comes in, compute all the semantic tokens for the entire file (`R1`)
* if the request has the previous result id set to the id of `R0`, then compute the `diff(R0,R1)` and send that as a reply. Store `R1` in memory, as it might be useful in the future. A very simple diff (prefix and suffix) which works quite well in practice can be found [here](https://github.com/microsoft/vscode/blob/9e17e6de341c3d8614f3059c43af1431713e1e52/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L765-L791). If you have sufficient time, you can implement other (better) diff algorithms, like Myers, etc. The output of such algorithms is always in terms of initial coordinates (like the edits are) 
* when a text document close event comes in, clear the saved reply from memory

---

I'm sorry that my example was problematic. I did not mean for whitespace to be considered elements in my example. So the arrays I was referring to are:

R0:

| a | b | c | d | e | f |
|---|---|---|---|---|---|
| 0 | 1 | 2 | 3 | 4 | 5 |

R1:

| b | c | x | e | f |
|---|---|---|---|---|
| 0 | 1 | 2 | 3 | 4 |

**Comment by mrakgr** [comment]
> A very simple diff (prefix and suffix) which works quite well in practice can be found here.

That link you gave me did give me inspiration. Rather than saving the old results and computing the diff by looking at the difference between the old and the new document which would be a significant expense, I could keep track of the suffix and prefix lengths iteratively in a more compact way. Although I knew that I could get the minimum bound for the diff range just by taking the min over the array indexes, it never occurred to me to get the maximum bound the same way by thinking of the file as starting from the opposite side.

So I am sure I could make the changes provider work now.

That having said is that the course of action I should take? Consider that internally it is maintaining that uint32 array. Every time I insert a token, it has to shift the rest forward, right? No doubt that is expensive. I'd want to avoid such a situation if I can. My rough guess is that the token array is around the size of the original text document so I want to avoid doing that kind of mirroring and operation of it in different places.

As a matter of principle, I want to maximize both performance and simplicity of my code.

If you think about it more in depth, the range provider should be superior in all cases to the changes one, as it only needs to maintain a small range of tokens in the viewport and has no need to shift and resize that document sized token array. Furthermore, going to the range provider did simplify the implementation significantly. With the changes provider I am also exposing myself to the synchronization issues of having to send deltas between two async apps. The range provider should be a more robust solution.

Right now though with the range provider, when I write code there is a small, but definitely visible lag before the highlighting kicks in. It does not really make sense.

Yes, there is overhead from doing app to app communication over the network card, and there is more traffic involved in the range provider (though that too could be optimized) but even so those overheads are microsecond on their scale. From the user perspective, given how swift tokenization is, the highlighting should be instantaneous. Since I am doing small scale testing it should not even matter even if hypothetically the range provider is poorly implemented - it should still be sub-millisecond latency. I think the real issue with the range provider is that it is not triggering fast enough.

---

So instead of me implementing diffing and putting yet even more complicated functionality that I do not want just to please VS Code, would it be fine if I just requested that you make the range provider faster? 

Maybe you could add that event trigger the changes ones already has. Calling `fire` after doing the file changes worked wonders for the highlighting lag with the changes provider. I'd need that kind of thing anyway since I want to have multiple semantic passes in the future.

**Comment by kjeremy** [comment]
> One way to implement this on the server side is:
> 
> * when getting a semantic tokens request, save the reply in memory (`R0`)
> * when text edits come in, don't do anything
> * when the next semantic tokens request comes in, compute all the semantic tokens for the entire file (`R1`)
> * if the request has the previous result id set to the id of `R0`, then compute the `diff(R0,R1)` and send that as a reply. Store `R1` in memory, as it might be useful in the future. A very simple diff (prefix and suffix) which works quite well in practice can be found [here](https://github.com/microsoft/vscode/blob/9e17e6de341c3d8614f3059c43af1431713e1e52/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L765-L791). If you have sufficient time, you can implement other (better) diff algorithms, like Myers, etc. The output of such algorithms is always in terms of initial coordinates (like the edits are)
> * when a text document close event comes in, clear the saved reply from memory
> 

Is this for the semantic tokens delta request? If so how does this save any work (since you are recomputing semantic tokens on every request) or is it just network traffic being saved?

**Comment by alexdima** [comment]
> Is this for the semantic tokens delta request? If so how does this save any work (since you are recomputing semantic tokens on every request) or is it just network traffic being saved?

What I have outlined saves on network traffic. But you can implement this in any way you want on the server side. If you have a language server where you can compute a diff after each document change event, then by all means, do so! So if the initial result is `R0` and a document change event comes in, and you can very quickly compute `diff(R0,R1)`, then compute it and store it. Then, when another document change event comes in, and you have stored `R1` and `diff(R0,R1)`, if you can very quickly compute `diff(R1,R2)`, then I believe you can straight-forward compute `diff(R0,R2)` and store it... So, when VS Code decides to make the semantic tokens edit request, you can return `diff(R0,R2)` which you have already computed.
