### ISSUE TITLE
Code fails to launch (non-elevated) if there is already an existing (elevated) process

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10178]
There's a similar case #3180 that was closed as a dupe of #929, however I can reproduce this much worse than #929.

- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. Run VS Code as Admin
2. Try to launch code as non-Admin (from taskbar, shell, explorer context menu)

Nothing happens. No new Code window, and nothing opens in the Admin instance either.

**Comment by joaomoreno** [comment]
#1614

**Comment by DanTup** [comment]
@joaomoreno that case defined very different behaviour - where new code windows open but are not elevated. The bug here is that clicking Code does *absolutely nothing*. No Code window, no reused existing instance, no error message, nothing.

While the two may be related, surely it should not be considered a new feature for clicking the icon on the taskbar to actually do anything at all? :/

Even a nasty pop-up saying "There is another instance of coding running" would be better than the (really confusing) behaviour of silently doing nothing.

**Comment by joaomoreno** [comment]
The issue relates to supporting all use cases of _running as Administrator_, and this is one of them.

I totally agree with you on the current behaviour though.

Since we're trying to decide whether we should allow people to open as Administrator at all, let me ask you: why do you need to open it as an Administrator? Just to save write-protected files?

**Comment by DanTup** [comment]
I actually don't, it was just a side-effect of launching it from an elevated PoSh shell. If it had launched a non-elevated Code that would probably suit me fine :)

**Comment by joaomoreno** [comment]
Thanks!
