### ISSUE TITLE
Suggestion: Add the ability to autocomplete files that exist in explorer

### ISSUE THREAD

**Issue by eyalsk** [Microsoft/vscode#10175]
At times you need to write the name of the resource that appears in explorer like when you're doing web development and you need to reference whatever file, so this can be pretty nice feature to have.

**Comment by alefragnani** [comment]
Maybe this extension already do that 
https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense ?

**Comment by eyalsk** [comment]
@alefragnani Yeah but I feel like this is something that needs to be in the base product, nonetheless, this is useful, thank you. :)

**Comment by arthurbdiniz** [comment]
Can i take this feature?

**Comment by eyalsk** [comment]
@arthurbdiniz Well, they did label it as "help-wanted" so you can prob just send them a PR. ;)

**Comment by mjbvz** [comment]
Closing this as path completions have been implemented for html, css, js, and ts out of the box. Extensions can add more advanced path completions and support for additional languages
