### ISSUE TITLE
IntelliSense vscode.ExtensionContext missing

### ISSUE THREAD

**Issue by rwnkl** [microsoft/vscode#101794]
- VSCode Version: 1.46.1
- OS Version: Windows 10 Prof

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rwnkl** [comment]
IntelliSense: interface vscode.ExtensionContext property extensionUri is missing

**Comment by JacksonKearl** [comment]
Will track this with #101792
