### ISSUE TITLE
Intellisense is messing up since last update

### ISSUE THREAD

**Issue by Maryannah** [microsoft/vscode#101757]
VSCode About page : 

![image](https://user-images.githubusercontent.com/46892394/86534390-6a120280-bed8-11ea-97a0-c47fe5fc3e75.png)

Steps to Reproduce:

1. Run the intellisense on anything

This is the intellisense result : 

![image](https://user-images.githubusercontent.com/46892394/86534378-5bc3e680-bed8-11ea-9781-2b88b1d23651.png)

In case it might help, here are my settings

```json
{
    "terminal.integrated.shellArgs.linux": ["-l"],
    "window.zoomLevel": -1,
    "editor.detectIndentation": false,
    "emojisense.languages": {
      "markdown": true,
      "html": true,
      "typescript": true,
      "javascript": true,
      "plaintext": true,
      "css": true
    },
    "editor.tabSize": 2,
    "workbench.tree.indent": 16,
    "extensions.ignoreRecommendations": false,
    "[json]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "workbench.iconTheme": "material-icon-theme",
    "[html]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.suggestSelection": "first",
    "files.exclude": {
      "**/.classpath": true,
      "**/.project": true,
      "**/.settings": true,
      "**/.factorypath": true
    },
    "[jsonc]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "explorer.confirmDragAndDrop": false,
    "remote.WSL.fileWatcher.polling": true,
    "remote.WSL.fileWatcher.pollingInterval": 3000,
    "files.watcherExclude": {
      "**/node_modules": true
    }
  }
```

And here are my extensions : 

![image](https://user-images.githubusercontent.com/46892394/86534435-be1ce700-bed8-11ea-9f88-a8ce600922c3.png)

**Comment by mjbvz** [comment]
It looks like you have enabled IntelliSense explain mode. Run the `toggleExplainMode` command (ctrl+\ I believe) with intellisense open to exit this 

/cc @jrieken

**Comment by Maryannah** [comment]
@mjbvz thank you a lot for that information ! It's resolved now. 

(And for future reference, the shortcut was `ctrl + :` on my azerty keyboard). 

I'll edit the title to help people find this answer in the future. Thank you again !
