### ISSUE TITLE
Language support: autocomplete does not decrease indent

### ISSUE THREAD

**Issue by tobega** [microsoft/vscode#101711]
Issue Type: <b>Bug</b>

Create support for a new language
In language-configuration.json add:
    "indentationRules": {
        "increaseIndentPattern": "begin",
        "decreaseIndentPattern": "end"
    }

When typing "end", indent is decreased fine, but when an auto-suggestion of "end" is accepted, the indent is not decreased.

I would expect accepting auto-suggestion to behave the same as if I typed the full word

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

**Comment by jrieken** [comment]
Indentation rules are only applied to user gesture, e.g typing text, and not to computed modifications. Those should be already computed with the right indentation.

**Comment by tobega** [comment]
Except they are not

**Comment by jrieken** [comment]
Are you developing or using the language extension?

**Comment by tobega** [comment]
I'm developing it with the aim to use it.

It is when it is used that the reported action happens. I suppose the
auto-suggestion is some vscode magic because I certainly haven't gotten
much beyond the simple language-configuration.json.

**Comment by jrieken** [comment]
This is likely simple, word-based completions. Once you have a "real" completion provider this will go away
