### ISSUE TITLE
Links involving a file path with white space are broken

### ISSUE THREAD

**Issue by jeswr** [microsoft/vscode#101707]
- VSCode Version: May 2020 (version 1.46)
- OS Version:
Edition: Windows 10 Pro
Version: 1903
OS build: 18362.900

Steps to Reproduce:

--- The following applies in any shell opened using the terminal built into Visual Studio Code ---

1. Make and `cd` into a folder with white space in the name. I used `C:\Users\jmwri\white space`.

In a directory of the form `C:\Users\jmwri\no_white_space`, `crtl + click` can be used to open the folder. Files within the folder, for instance `C:\Users\jmwri\no_white_space\index.js` can be opened using `crtl + click`. This is not possible with `C:\Users\jmwri\white space` as it is broken into 2 invalid links `C:\Users\jmwri\white` and `space`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This needs a label, otherwise it goes back to inbox.
