### ISSUE TITLE
Changes view: sync action very close incoming/outgoing numbers

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101777]
I feel this could benefit from some spacing:

![image](https://user-images.githubusercontent.com/900690/86560281-35e12500-bf5e-11ea-8ad9-f3c819ec81c4.png)

**Comment by joaomoreno** [comment]
This has changed since: 
![image](https://user-images.githubusercontent.com/22350/89397151-c3f02d00-d70f-11ea-9b0a-2148f6e249e0.png)
