### ISSUE TITLE
Screen cheese with SCM input message and suggest widget

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101786]
* type a long commit message so that warning appears
* trigger intelli sense
* 🧀 the message is atop the suggest widget

<img width="505" alt="Screenshot 2020-07-06 at 12 31 55" src="https://user-images.githubusercontent.com/1794099/86584205-d8140380-bf84-11ea-9e26-cc4b38ca7e32.png">

**Comment by joaomoreno** [comment]
Fixed by https://github.com/microsoft/vscode/commit/149f31ed01fa46841d27dca9318e28066af26335
