### ISSUE TITLE
The git clone should take the url as well

### ISSUE THREAD

**Issue by anirugu** [microsoft/vscode#101752]
Suppose I work on VS CODE and  I type > Git clone which I used for clone the repository.

Now if I enter the url of repo for example https://github.com/DeborahK/AngularF2BWebAPI it must be able to clone it. What I need to do is I need to remove 'https://github.com/DeborahK/' from url to clone it.

when I remove it then it fetch the repos , then I can clone it, I think it would be better if it's just take the url of repos to clone the repository.

Actual behaviour

![image](https://user-images.githubusercontent.com/35772421/86533728-c5e88580-bef0-11ea-8ce0-504b8b5c2862.png)

Expected behaviour 

![image](https://user-images.githubusercontent.com/35772421/86533736-d862bf00-bef0-11ea-9092-60e6ad7f708d.png)

**Comment by yume-chan** [comment]
![1](https://user-images.githubusercontent.com/1330321/86552062-7ac68500-bf79-11ea-8dd4-03b90d13f8f0.gif)

I can't reproduce. What's your Code's version?

**Comment by joaomoreno** [comment]
@anirugu Instead of selecting `Clone from Github`, simply paste the URL at that time. Does that work?

**Comment by anirugu** [comment]
I was on windows machine when I found this trouble, @joaomoreno  Yes It's work as you say on linux, will check on windows too.
