### ISSUE TITLE
git commit no response

### ISSUE THREAD

**Issue by zouzg** [microsoft/vscode#101743]
I can't commit my changes, ether by cmd+enter or by click the right icon. I tried reinstall the vscode but not works.
Here is my machine info: 

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (2 wks ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by joaomoreno** [comment]
Can you show me the full output of `Git: Show Git Output`, especially what's the output when you click the action? Can you reproduce the issue with `code --disable-extensions`?
