### ISSUE TITLE
rg process eat 100% cpu and +8GB memory

### ISSUE THREAD

**Issue by dmahmouali** [microsoft/vscode#101753]
- VSCode Version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
- OS Version: Linux x64 5.3.0-61-generic

Does this issue occur when all extensions are disabled?: 
-No

**Comment by roblourens** [comment]
Can you take a look at this doc and let me know whether any of the tips help?

https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
