### ISSUE TITLE
Ability to set an option to always center the cursor on the editor.

### ISSUE THREAD

**Issue by Parkar99** [microsoft/vscode#101765]
Similar to setting a huge number in scrolloffset in VIM, the feature would allow the cursor to be always centered on the editor. This allows the cursor to be in 1) a predictable location and 2) always in front of you so you don't have to crane your neck on large screens.

Hope you consider this request :)

**Comment by usernamehw** [comment]
```js
"editor.cursorSurroundingLines": 100,
```

**Comment by ArturoDent** [comment]
And, if using the `cursorSurroundingLines` you will also have to set 

    "editor.cursorSurroundingLinesStyle": "all",

**Comment by Parkar99** [comment]
I can't believe I missed that. Thanks @usernamehw and @ArturoDent
