### ISSUE TITLE
Markdown preview - does not scroll correctly with cursor pointing when scrolling with images in downward direction

### ISSUE THREAD

**Issue by surpavan** [microsoft/vscode#101713]
- VSCode Version: 1.46.1
- OS Version: Windows 10

Steps to Reproduce:

1. With having lot of images
2. Scrolling down does not move the preview along with it, i guess it is going by line space/height and not taking image height into account to scroll down.
3. But scrolling up works fine.

Does this issue occur when all extensions are disabled?: Yes/No Yes- error continues even when all extensions are disabled.

**Comment by surpavan** [comment]
Sample files
![ta](https://user-images.githubusercontent.com/37795549/86510750-1dfb8b00-be10-11ea-9a52-853ddc88bd5c.png)

MD Code:
A Sample file

![some sample image](ta.png)
A Sample file

![some sample image](ta.png)
A Sample file

![some sample image](ta.png)
A Sample file

![some sample image](ta.png)
A Sample file

![some sample image](ta.png)
A Sample file

![some sample image](ta.png)
A Sample file

![some sample image](ta.png)
A Sample file

![some sample image](ta.png)

**Comment by mjbvz** [comment]
I can't reproduce this issue in the current VS Code insiders build.

Can you please test again in the latest builds and let me know if you still see the problem. If so, can you describe the problem in more detail so I know what to look for?
