### ISSUE TITLE
VS code keeps asking for password

### ISSUE THREAD

**Issue by Allmedialab** [microsoft/vscode#101712]
Hi,
My work flow get's disturbed by this message on my iMac after every save I do in a Bootstrap gulp/pug project: "localhost Enter your password (Press 'Enter' to confirm or 'Escape' to cancel".
I have no clue if it's a bug or how to stop it, it's my first time I use VS code.
Regards & Thanks,
David

**Comment by JacksonKearl** [comment]
Have you installed any additional extensions?
