### ISSUE TITLE
Triple click selection seems to render a single line's selection twice

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#1017]
Best seen on dark themes.

In the following screenshots, I triple-clicked line 381. Then I dragged down to the next line. Notice that when only line 381 is selected, the selection is brighter and misses rounded corners. As soon as I drag the selection down, the selection is OK.

![image](https://cloud.githubusercontent.com/assets/22350/11592132/0173655c-9a9d-11e5-8740-05b1578db0ea.png)

![image](https://cloud.githubusercontent.com/assets/22350/11592139/07f2f3c0-9a9d-11e5-8cd9-8a9afa7de08f.png)

**Comment by alexandrudima** [comment]
selectionHighlighter

**Comment by joaomoreno** [comment]
Oh no, let me take this.

**Comment by alexandrudima** [comment]
Possible dup of #64
