### ISSUE TITLE
Question: Is there a preferred way for an extension to store data/state across sessions?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10176]
My extension searches for the Dart SDK at startup (it scans the PATH environment variable). I could make this faster if I cached the last place I found it and always inserted that at the top of the list at startup (PATHs can be long, especially on Windows!).

Is there a good way for me to do this? Stashing it in a text file is good enough for me (assuming there's no relevant API), but I want to make sure I put it in a good place across all platforms.

Asking the user to provide add the SDK path to config is not a good experience; they have the ability to override it but it will be a really bad first-launch experience to ask the user to provide this (especially if they installed it with `apt-get` and might have no idea where it is).

**Comment by aeschli** [comment]
There's currently no internal settings API. All the extension API currently gives you is the user settings.

**Comment by DanTup** [comment]
@aeschli Is there a folder path or something I can get via the API that would be an appropriate place to store this, or do I just need to do totally my own thing?

**Comment by aeschli** [comment]
Oh, sorry, I didn't realize that we have what you want: There is `ExtensionContext.workspaceState `and `ExtensionContext.globalState` and `ExtensionContext.storagePath`. You get the ExtensionContext when the extension is activated.

**Comment by DanTup** [comment]
Excellent, thanks! :)
