### ISSUE TITLE
source maps for webpack bundles stop working after a hot rebuild

### ISSUE THREAD

**Issue by hedgepigdaniel** [microsoft/vscode#101762]
## Prerequisites
Getting the sourcemaps to work at all with a webpack build required setting `output.devtoolModuleFilenameTemplate: '[absolute-resource-path]'` in the webpack config

## Reproduce
1. Set up a webpack build that exports an express/koa handler/middleware
2. Use https://github.com/60frames/webpack-hot-server-middleware to serve it, and to switch incoming requests to use new builds as webpack creates them
3. Set a breakpoint in the source code, and also add a debugger statement.
4. Start the server and trigger the code with the breakpoint and debugger statement. Notice that both the breakpoint and the debugger statement work correctly, and the IDE opens the original source code.
5. Make a change to the source file the the debugger and break point to trigger a webpack recompile (but not a restart of the debugged process), and perform a second request
6. Notice that the breakpoint does not work, and the debugger statement causes the IDE to open the compiled file rather than the original source.

**Comment by connor4312** [comment]
Okay, thanks for the steps! Before I dive into this more, can you see if this works if you set `debug.javascript.usePreview: true`? That will use our new debugger, which has different sourcemap handling and will become the default debugger in the upcoming release.

**Comment by hedgepigdaniel** [comment]
I tried with the new debugger (released version, and nightly version). The symptoms are the same for the breakpoint inside the webpack build - it works the first time, but not after a recompile.

Some more detail for the issue in the babel compiled code (`serveDev.js`)
- the debugger causes the IDE to open a source file with the correct content, but it is not correctly mapped to the editable source file on the filesystem
- the breakpoint causes the IDE to open compiled code which does not look like the source code.

**Comment by rushvora** [comment]
I have the same issue, easily reproducible, with both the preview debugger and the non-preview debugger. Let me know if I can provide information or logs. VS Code 1.47.3.

**Comment by captainkout** [comment]
This problem remains a massive productivity cost for our project. We are still experiencing errors in 1.48.

**Comment by connor4312** [comment]
Depending on your case (have not verified this scenario yet), https://github.com/microsoft/vscode-js-debug/commit/7d8f598a61728a2f0c00ec756d7b565c9bbab030 may solve your issue. Fixes several use cases with things like types of nodemon builds and Nest.js dev mode.

**Comment by captainkout** [comment]
@connor4312 As of this morning, we are still experiencing this issue in our Angular Project.

**Comment by connor4312** [comment]
Yes, Angular is an entirely different scenario from what's in that commit.

**Comment by captainkout** [comment]
@connor4312 Thanks. I expected it might be different. Do i need to create a new issue for Angular specifically?

**Comment by connor4312** [comment]
Yep, that would be good to make sure your scenario is tracked. Link for a bug: https://github.com/microsoft/vscode-js-debug/issues/new/choose A repro is sufficient, I probably will not need the trace logs that the template asks for.

**Comment by hedgepigdaniel** [comment]
great thanks :)
