### ISSUE TITLE
Support "go back" and "go forward" in notebooks

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101779]
The workbench commands for going back and forward don't seem to work for notebook but they should. Simple steps: 

* open a notebook
* edit cell 1, edit cell 2
* trigger "Go Back"
* nothing happens...

**Comment by jrieken** [comment]
@bpasero What does it take to make this happen?

**Comment by bpasero** [comment]
Well, the code is probably not ready for non-text-editor controls. Starting from here:

https://github.com/Microsoft/vscode/blob/2e8b1458ad9fc6df9783cb1d20d888d25e73b119/src/vs/workbench/services/history/browser/history.ts#L194-L211

It listens to active editor changes and installs cursor listeners to the active editor if being a text editor. Maybe the history service could be tricked into believing that the notebook is a text editor.

**Comment by jrieken** [comment]
It actually gets there. When switching editors I see that the selection change listener is installed and fired but those events are associated with the outer editor, not the inner editor. It also seems that in-editor-editor changes (changes between cells) don't work, e.g are conceptually missing. I see the same with the diff-editor where selections in the LHS are also ignored from history. 

Not sure how to tackle this best. WOuld it make sense to turn this around and let editors push stop points onto the history stack?

**Comment by bpasero** [comment]
Needs thinking... how would that work, history service having methods to push history events? And then each event has a way to be triggered to e.g. go back? This would probably require adoption somewhere in the monaco editor and then as well in notebooks. But I think it is a good model, especially given that custom editors for example currently cannot participate in history either (@mjbvz right?)

**Comment by jrieken** [comment]
Removing milestone but adding back @bpasero since this is a new requirement to this history service for which we need your help

**Comment by bpasero** [comment]
This landed via https://github.com/microsoft/vscode/pull/142152 and is limited to supporting navigation between cells. It currently does not support navigation within a cell.

**Comment by bpasero** [comment]
Oh btw, it also does not support notebook diff editors yet because they seemed to behave much different from normal notebooks, i.e. did not provide me with the same set of events from the underlying widget.

**Comment by bpasero** [comment]
**Verification:**
* open notebooks and click through cells
* open other text files as well
* use multiple editor groups
* verify that using "Go Back" and "Go Forward" navigation stops include cells of notebooks as well now
