### ISSUE TITLE
Add an option to prompt for confirmation before moving files

### ISSUE THREAD

**Issue by eyalsk** [Microsoft/vscode#10174]
Even though most of us working with source control and it's not a problem it still nice to have this lilttle feature.

**Comment by aeschli** [comment]
There is already a prompt before deleting files...

**Comment by eyalsk** [comment]
@aeschli Yeah, you're right, I'm just blind... I'll update it. :)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1414
