### ISSUE TITLE
High Contrast color theme comes out as "stealth" low-viz

### ISSUE THREAD

**Issue by rbtyod** [microsoft/vscode#101731]
Issue Type: <b>Bug</b>

When using the vs code high contrast color scheme with "Show Variables in Jupyter Kernel", 
alternate lines (with orange background) are effectively invisible.  See attached .png

![Annotation 2020-07-04 180510](https://user-images.githubusercontent.com/3954001/86523427-11336300-be21-11ea-90c7-a02035f38867.png)

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (17.48GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.15.0
conda-cheatsheet|joj|1.2.7
kite|kit|0.119.0
rainbow-csv|mec|1.7.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.6.91350
vscode-pylance|ms-|2020.6.1
remote-wsl|ms-|0.44.4
vscode-yaml|red|0.8.0
pdf|tom|1.0.0

</details>

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/Microsoft/vscode-python/issues
Would you mind filing the issue there? (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)
