### ISSUE TITLE
Have jsconfig.json AND have each file treated separately

### ISSUE THREAD

**Issue by phudson** [microsoft/vscode#101783]
According to https://code.visualstudio.com/docs/languages/jsconfig

> Visual Studio Code's JavaScript support can run in two different modes:
> 
> File Scope - no jsconfig.json: In this mode, JavaScript files opened in Visual Studio Code are treated as independent units. As long as a file a.js doesn't reference a file b.ts explicitly (either using import or CommonJS modules), there is no common project context between the two files.
> 
> Explicit Project - with jsconfig.json: A JavaScript project is defined via a jsconfig.json file. The presence of such a file in a directory indicates that the directory is the root of a JavaScript project. The file itself can optionally list the files belonging to the project, the files to be excluded from the project, as well as compiler options (see below).
> 

In my context, I have a number of Javascript files. Each can use the same APIs, will be run with the same Javascript version etc. However each file is independent, and I want Visual Studio code to treat them that way

Which it does, if I have no jsconfig.json. But I want one of those to control the options used (e.g. strict checking). But then the files are considered together, and I get errors about conflicting definitions etc between the files

So is there some way I can have both a jsconfig.json, and have Visual Studio Code treat the files as independent units?

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

Potentially also related to https://github.com/microsoft/TypeScript/issues/14279

**Comment by phudson** [comment]
Thanks. Wasn't obvious to me I should have requested it elsewere. The linked existing feature request covers what I want.
