### ISSUE TITLE
the console does not show multiple unicode characters correctly

### ISSUE THREAD

**Issue by lugeke** [microsoft/vscode#101741]
Issue Type: <b>Bug</b>

when display multiple same unicode characters(like ⬆️), they stack together , doesn't have proper space between them, can't distinguish them apart 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 20.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 8, 9|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|-psn_0_446573|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-m3u|af4|1.0.0
python|ms-|2020.6.91350

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot of [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal

**Comment by lugeke** [comment]
![屏幕录制2020-07-11 上午11 21 31](https://user-images.githubusercontent.com/8017813/87215492-8e9f2c00-c369-11ea-820a-17cfb3081b3d.gif)

**Comment by Tyriar** [comment]
This is an ambiguous width character unfortunately that may be right or wrong depending on the font, here's what I see:

![image](https://user-images.githubusercontent.com/2193314/87308090-8eb93c00-c4cf-11ea-91eb-966ba915ef2a.png)

Currently the terminal uses widths based on Unicode v11.
