### ISSUE TITLE
Problems window does not clear

### ISSUE THREAD

**Issue by julian-hansen** [microsoft/vscode#101748]
Issue Type: <b>Bug</b>

I have been able to reproduce this with PHP - have not tried any other environments

Relevant Extensions loaded
PHP Debug 1.13.0
PHP Extension Pack 1.0.2
PHP IntelliSense 2.3.14

1. Create a new file (Ctrl + N)
2. Change language module to PHP (click footer toolbar -> Plain Text and Select PHP Language Module)
3. Add the following code
<?php

echo rubbish

4. Errors should show in the Problems window
5. Close untitled window without saving
6. Problems window does not clear
7. Click on issue in Problems window - a new untitled (blank) window is opened.

Problem seems to be if errors are present on an unsaved file that is closed - VS Code does not "forget" the errors.

Work around to fix
1. Click on Problem in Problems window - this should open a blank untitled file
2. Change language module to PHP
3. Type in valid PHP script
4. Errors should be removed
5. Close file

Would be nice if Code would "forget" errors on closed files.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:16:50.293Z)
OS version: Windows_NT ia32 10.0.18362

**Comment by JacksonKearl** [comment]
Please file this on the relevant extension. You can try disabling extensions until it doesn't reproduce to find the extension causing the problem.
