### ISSUE TITLE
show full path of files in find/replace panel and title bar

### ISSUE THREAD

**Issue by warmhug** [Microsoft/vscode#10170]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

In find/replace panel, it can't display the full path of searched file, it's inconvenient. like this: 

![snip20160805_1](https://cloud.githubusercontent.com/assets/2011119/17427599/6b69a0ce-5b14-11e6-99eb-038f5edf507c.png)

Also, should enable to show the full path of file in title bar, but it isn't also now, like this:

![snip20160805_2](https://cloud.githubusercontent.com/assets/2011119/17427666/e3e70532-5b14-11e6-86b6-b7014a45b617.png)

**Comment by aeschli** [comment]
The second request is https://github.com/Microsoft/vscode/issues/3119 (please only one request per issue)

**Comment by bpasero** [comment]
@aeschli please assign search related issues to Sandeep

**Comment by sandy081** [comment]
We are showing the full path of the file in search results view. When the width is not sufficient, path details are trimmed. Hovering on the label always show the full path. 

@warmhug May I know what more you are looking for?

**Comment by warmhug** [comment]
Okay, so be it, thanks.
