### ISSUE TITLE
VS Code interpreter / REPL

### ISSUE THREAD

**Issue by weitzhandler** [microsoft/vscode#101737]
Hi,

As opposed to Visual Studio, VS code is lightweight and loads in seconds. I thought why not make it even faster, by enabling it to act as an interactive code interpreter.

In my vision, ideally, after launching vs code, clicking <kbd>Ctrl</kbd>+<kbd>N</kbd> for creating a new temp file at an undisclosed location, should allow me rename the file to indicate its type (let's say `*.cpp` or `*.cs`).

Once file type is known to the editor I can benefit from intellisense, which would already be a lot to me without even being able to run. This would allow me to include headers and ctrl+click types or definitions etc. to look them up in the header files (cpp), to see how they were defined, or clicking on types to see their structure, much like C# interactive window in Visual Studio does, but with current renamable code file as source.

Anyway, last step would be being able to run a single command that launches the appropriate interpreter/compiler and runs the code printing the output with a single click according to the file type.

I just spent 40 minutes installing and uninstalling extension after extension that claims to do what I'd like, no one which worked as desired, each one with its quirks and imperfections.
Wouldn't it be time for this basic editor functionality to fast-interpret code to finally become a recognized part of VS Code already?

Thank you!

**Comment by NotWearingPants** [comment]
Use <kbd>Ctrl</kbd>+<kbd>K</kbd>,<kbd>M</kbd> to change the untitled file's language, and then install [the code runner extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner), and press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>N</kbd> to run the code

**Comment by weitzhandler** [comment]
That worked great.
The <kbd>Ctrl</kbd>+<kbd>K</kbd>,<kbd>M</kbd> is what I was looking for!
Anyway I wonder if I should close this issue or keep it open for the sake of the second part.

**Comment by weitzhandler** [comment]
The <kbd>Ctrl</kbd>+<kbd>K</kbd>,<kbd>M</kbd> only sets the file-type, but seems it doesn't do the job thoroughly as renaming. When <kbd>Ctrl</kbd>+<kbd>Click</kbd>ing types or headers doesn't open them as with a file named *.cpp.

**Comment by Tyriar** [comment]
> In my vision, ideally, after launching vs code, clicking Ctrl+N for creating a new temp file at an undisclosed location, should allow me rename the file to indicate its type (let's say *.cpp or *.cs).

You can write an extension to do this.
