### ISSUE TITLE
Let user add custom button in status bar that executes vscode command

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/vscode#101758]
There might be cases in which you have to execute a VSCommand from the command palette many times. I think it could be a good idea to add a gear icon next to the command in the command palette with a contextual menu with an option to add (or remove if already added) a button in the status bar to execute this command easily. Then vscode ask you to write a title for this button and voila! Now you don't have to go through the command palette to execute this command anymore, just click the new button at the bottom.

All new buttons are recorded in settings.json so that you can add buttons from there too. This way you can specify values to some arguments if the command ask you for them. For instance, you might want to add 3 buttons to the status bar to run 3 different build tasks. In this case, just add the buttons in settings.json, each button with the task to run argument set to the correct task.

**Comment by rei-vilo** [comment]
There is thread about customisable tool bar at https://github.com/microsoft/vscode/issues/41309

**Comment by ArturoDent** [comment]
I use the [Command](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands) extension for this.  Not as easy as your suggestion but still pretty easy.  I'm using the `sendSequence` here but it could be any command.  Part of my setup:

    {
      "command": "workbench.action.terminal.sendSequence",
      "arguments": [{"text": "gulp deploy_E\u000d"}],
      "text": "Deploy to Experimental",
      "tooltip": "Deploy to experimental folder",
      "alignment": "left",
      "priority": 4,
      "color": "#fff"
    },
    {
      "command": "workbench.action.terminal.sendSequence",
      "arguments": [{"text": "gulp sync\u000d"}],
      "text": "Gulp Sync",
      "tooltip": "Start the gulp server",
      "alignment": "left",
      "priority": 3,
      "color": "#fff"
    },
    {
      "command": "workbench.action.terminal.sendSequence",
      "arguments": [{"text": "gulp build\u000d"}],
      "text": "Build All",
      "tooltip": "Build and process all files",
      "alignment": "left",
      "priority": 2,
      "color": "#fff"
    },

![status bar commands](https://user-images.githubusercontent.com/31813701/86547639-d4d23680-bef6-11ea-9716-f8042416fb0e.gif)

**Comment by JacksonKearl** [comment]
\duplicate #41309
