### ISSUE TITLE
Publish to GitHub: Do not add empty .gitignore

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#101795]
Issue Type: <b>Bug</b>

I checked in everything and unexpectedly got an empty .gitignore added.

VS Code version: Code - Insiders 1.47.0-insider (376d9d9d785ccca128fdbb16f001446d0ad64d32, 2020-07-03T10:26:01.724Z)
OS version: Darwin x64 19.4.0

**Comment by JacksonKearl** [comment]
Blocked on #104248.
