### ISSUE TITLE
all my code disappeared

### ISSUE THREAD

**Issue by Reyn52** [microsoft/vscode#101720]
Issue Type: <b>Bug</b>

all my code just disappeared, the window crashed then i have to re open and when that happend all my code was gone. What to do? 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz (2 x 2167)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|1.89GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.4.1
htmltagwrap|bra|0.0.7
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|5.1.3
php-debug|fel|1.13.0
auto-rename-tag|for|0.1.4
code-runner|for|0.10.0
material-icon-theme|PKi|4.2.0
LiveServer|rit|5.6.1
px-to-rem|sai|1.3.1
bunker|sld|1.1.6

</details>

**Comment by Reyn52** [comment]
> 
> 
> /needsMoreInfo

its just like that, was working on the js code at that moment then the window crashed and stop working and says i need to re open so i did and then all my js code was gone. The file now in 0 kb and all the code is gone. Dont know what to do. Is not like I didnt save or something, I have several time working on it but now is all gone. Really dont know what to do, cant find any solution dont know where to post

**Comment by mjbvz** [comment]
@Reyn52 Sorry about the data loss. @bpasero @Tyriar may have suggestions on recovering the file from VS Code's backups  

Also, this could have been caused by one of your extensions. To help us investigate, can you tell us how the window crashed? Was there an error message? Did VS Code just suddenly quit? Has this happened before?

**Comment by Reyn52** [comment]
I tried but found nothing in backups, That's why I posted it here. Search in every single folder and there wasnt any thing to backup just found workspaces or something like that .json files I think.
I post the extensions I have if you can see.
And yes, is not the first time that the window crashed, but it was the first time I lost everything. You see, this computer doesnt have too many ram and when I'm doing something I have to just open the page that I'm working on and the vs code program, if I open to many tabs on firefox or any other programs they suddenly crash and have to be closed. So that is why I'm kind of use to crashes, even the vs code as I say, has crashed before and I just click on re open and close programs to save ram and normalize things. But this time, I dont know why it erase all my code, not just the code I writte at that time or that day, but all the code suddenly go to 0. 
And btw the vs code never show any error message, or not something meaningful, just the window that says it crashed and if I want to re open or close and thats all I think.
I need to know if that is normal or if is a one time thing and if there is any solution in case it happends again to me or anyone (I hope no, I really wanted to cry). I found the way to keep things backup now with git, I'm new on this and learning along the way.
And if there's no solution at least have record of this problem.

PS: Luckily I had sent a copy with my code several days ago and at least I didnt have to start over again from 0 but for now I'm stuck with this computer and is all that I have and I know that it will keep crashing, already happend once today but with no code lost. So any advices or solution for the problem will be great.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
