### ISSUE TITLE
File names in view pane flicker with Jupyter

### ISSUE THREAD

**Issue by caallinson** [microsoft/vscode#101727]
Issue Type: <b>Bug</b>

When two Jupyter notebooks are open (or an Interactive Python Window), dragging one to another pane (Split Right, for example) causes the file names in the top file tab to flicker and the UI becomes unresponsive. 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3999)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (21.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
r|Iku|1.4.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.6.91350
vscode-yaml|red|0.8.0

</details>

**Comment by rebornix** [comment]
Please file issue against Python extension.
