### ISSUE TITLE
Minimize Terminal Button

### ISSUE THREAD

**Issue by yaddly** [microsoft/vscode#101760]
Kindly add minimize terminal button, we only have maximize option

**Comment by yume-chan** [comment]
The <kbd>X</kbd> (Close Panel) button will hide (minimize) the terminal panel, does that work for you?

Or can you clarify what "minimized" state you want?

**Comment by AdamTeodoro** [comment]
Use ctrl + ' Para abrir e fechar o terminal

**Comment by yaddly** [comment]
> The X (Close Panel) button will hide (minimize) the terminal panel, does that work for you?
> 
> Or can you clarify what "minimized" state you want?

Good day, thank you for the response, well I admit that X (close panel) button works but using close button to achieve minimizing function is a violation of user-friendliness. Again when I close the panel, there is no clearly labeled restore panel function...

**Comment by yaddly** [comment]
> Use ctrl + ' Para abrir e fechar o terminal

Good day, using ctrl + zooms the IDE not minimize the terminal panel

**Comment by IllusionMH** [comment]
No, not <kbd>Ctrl</kbd>+<kbd>=</kbd>(<kbd>+</kbd>)  which is **View: Zoom in** , but <kbd>Ctrl</kbd>+<kbd>`</kbd> - which is **View: Toggle Integrated Terminal**.

When you say there should be minimize button for Terminal - what behavior should be?
By default Terminal is part of the panel and whole panel is hidden when clicked on Close Panel. If there is minimize button only for terminal - that what should happed for other tabs in panel?

If there is not difference with Close Panel - no need to eat more space for another button which does same. If there is difference - there will be inconsistency between different views in Panel.

**Comment by Tyriar** [comment]
@misolori FYI feedback on x to minimize panel
