### ISSUE TITLE
[Feature] Tasks available directly from command palette

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode#101761]
## Is it possible to allow showing tasks directly in the command palette?

I.e. Change from workflow:
1. Launch command palette
1. `Tasks: Run Task`
1. `my awesome task`

To workflow:
1. Launch command palette
1. `Tasks: my awesome task`

## Reason

This is to streamline task execution.

The search and ordering functionality of command palette is fantastic 👍 . It would be really helpful to just search and execute a task directly from command palette.

**Comment by rrmistry** [comment]
As MVP solution it would be OK to just make user defined tasks from `.vscode/tasks.json` available in the command palette instead of automatically inferred tasks

**Comment by alexr00** [comment]
If you open the command palette then type `task ` (task + a space), then the task picker opens.

**Comment by rrmistry** [comment]
Thanks @alexr00 ! This is much appreciated

__________

FYI to those who, like me, couldn't find this short cut:

The task picker short cut (`task ` = task + space) is not under traditional command palette (`ctrl` + `shift` + `p` on Windows), but rather under quick navigation (`ctrl` + `p` on Windows)

**Comment by alexr00** [comment]
@rrmistry thanks for the correction
