### ISSUE TITLE
Auto-recommended extension cannot be found

### ISSUE THREAD

**Issue by lusitania** [microsoft/vscode#101756]
Issue Type: <b>Bug</b>

A popup tells me

> The 'Remote - WSL' extension is recommended as you have Windows Linux Subsystem (WSL) installed on your system.

I click `Install` but get
> (x) Error while loading extension. Error

The search field says
> @id:ms-vscode-remote.remote-wsl

Funny thing: I already have the Remote WSL extension installed.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363
Fetching remote diagnostics for 'Dev Container: Existing Dockerfile' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.49GB free)|
|Process Argv|--remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'Dev Container: Existing Dockerfile' failed.
</details>Extensions: none

**Comment by sandy081** [comment]
Can you please provide error logs when you install the extension?

Please follow these steps

- please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
