### ISSUE TITLE
VS Code Insider 1.46.1 crashes at startup - MacOS 11.0,  "Big Sur”, ARM (A12Z)

### ISSUE THREAD

**Issue by pearcy** [microsoft/vscode#101724]
- VSCode Version: 1.46.1
- OS Version: macOS Big Sur Version 11.0 Beta (20A5299w)
- Chip: ARM (A12Z) 

Steps to Reproduce:

1. Downloaded VSCode Insider on 7.4.20
2. When I try to open VS Code I receive a pop-up window with the following message:
The window has crashed
We are sorry for the inconvenience! You can reopen the window to continue where you left off. 

![The window has crashed](https://user-images.githubusercontent.com/4790266/86520579-e33b2800-bdfa-11ea-9879-06f79834ba0e.png)

-- It takes a few times to close out of the application (close, close, quit)

Does this issue occur when all extensions are disabled?: Yes

It’s a fresh install but I disabled all extensions just in case
./code --disable-extensions

If I run  `./code --verbose` at the following directory I get the same result.  
/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin

Crash report from console (partial):

`Process:               Code - Insiders Helper (Renderer) [2878]
Path:                  /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer)
Identifier:            Code - Insiders Helper (Renderer)
Version:               0
Code Type:             X86-64 (Translated)
Parent Process:        Electron [2872]
Responsible:           Terminal [1912]
User ID:               502

Date/Time:             2020-07-04 13:45:29.377 -0700
OS Version:            Mac OS X 10.16 (20A5299w)
Report Version:        12
Anonymous UUID:        046B23A9-EBF5-1015-D3CD-5146E2CA0F1E

Sleep/Wake UUID:       5BEA3457-47E6-41AC-A732-18FC14701851

Time Awake Since Boot: 15000 seconds
Time Since Wake:       3100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrRendererMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [2878]

Thread 0 Crashed:: CrRendererMain  Dispatch queue: com.apple.main-thread
0   com.github.Electron.framework 	0x000000010cf9c3a1 0x10afe5000 + 33256353
1   libsystem_kernel.dylib        	0x00007fff714fd21a __mprotect + 10
2   com.github.Electron.framework 	0x000000010cf9d160 0x10afe5000 + 33259872
3   com.github.Electron.framework 	0x000000010cf9cf56 0x10afe5000 + 33259350
4   com.github.Electron.framework 	0x000000010cfafb1d 0x10afe5000 + 33336093
5   com.github.Electron.framework 	0x000000010cfadd07 0x10afe5000 + 33328391
6   com.github.Electron.framework 	0x000000010ef150b9 0x10afe5000 + 66257081
7   com.github.Electron.framework 	0x000000010ef14fd2 0x10afe5000 + 66256850
8   com.github.Electron.framework 	0x000000010ec186b1 0x10afe5000 + 63125169
9   com.github.Electron.framework 	0x0000000110560b57 0x10afe5000 + 89635671
10  com.github.Electron.framework 	0x000000011055eda3 0x10afe5000 + 89628067
11  com.github.Electron.framework 	0x00000001105609ae 0x10afe5000 + 89635246
12  com.github.Electron.framework 	0x0000000110584732 0x10afe5000 + 89782066
13  com.github.Electron.framework 	0x000000010bb1b4ec 0x10afe5000 + 11756780
14  com.github.Electron.framework 	0x000000010e9ef339 0x10afe5000 + 60859193
15  com.github.Electron.framework 	0x000000010bb1ab94 0x10afe5000 + 11754388
16  com.github.Electron.framework 	0x000000010afe7fd4 AtomMain + 84
17  com.github.Electron.helper    	0x0000000102c473a5 0x102c46000 + 5029
18  libdyld.dylib                 	0x00007fff7138b651 start + 1`

**Comment by robsussman** [comment]
This looks the same as the Chromium bug here: 
https://bugs.chromium.org/p/chromium/issues/detail?id=1102194&q=label%3AMac-BigSur%20OR%20label%3AMac-Arm64&can=2

**Comment by coderDem** [comment]
I have also the same error, after I updated the OS Version to: macOS Big Sur 11.0 Beta (20A4300b)

**Comment by kamil-ignac-ih21** [comment]
I see the same error on 11.0 Beta (20A5364e) on DTK

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/104780, please try the builds posted there for the DTK
