### ISSUE TITLE
The TypeScript language service died 5 times right after it got started.

### ISSUE THREAD

**Issue by davo1984** [microsoft/vscode#101768]
Issue Type: <b>Bug</b>

Upon starting I receive the message:
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

Additionally I am not able to Open a Folder, not when I start nor by clicking the "Open Folder" button and selecting a folder. 

I am running on a MacBook Pro and the error started suddenly this morning. I have started both normally "code ." and "code . --disable-extensions"

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.15GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
When this happens, there should be a button in the popup that helps you report an issue that includes the error stack from the TypeScript service. Please try using that

/needsMoreInfo

**Comment by davo1984** [comment]
Sorry, I didn's see that button. A reboot seems to have fixed the problem.
