### ISSUE TITLE
'timeline' should be in 'Source Control' sidebar panel

### ISSUE THREAD

**Issue by allefeld** [microsoft/vscode#101772]
The list of git commits ('timeline') is shown in the 'Explorer' sidebar panel,but not in the 'Source Control' sidebar panel:

Explorer:
![image](https://user-images.githubusercontent.com/1738353/86546642-e08d1f80-bf2d-11ea-97b0-a8e78c01c681.png)

Source Control:
![image](https://user-images.githubusercontent.com/1738353/86546659-ee42a500-bf2d-11ea-9378-fa517a36aa01.png)

While having it in the Explorer can be useful, it is logically expected in Source Control.

I suggest that you either move the timeline from Explorer to Source Control, or add an additional timeline to Source Control.

**Comment by ArturoDent** [comment]
You can move it there yourself.  It is two steps (there may be a more direct method).  Move it to the Side Bar, open SCM, drag the Timeline icon to the lower/upper half of the SCM view.

![timeline move](https://user-images.githubusercontent.com/31813701/86547102-021de500-bef5-11ea-9625-2f1dd8b2baeb.gif)

**Comment by allefeld** [comment]
@ArturoDent Interesting, I didn't know something like that was possible. Thanks!
