### ISSUE TITLE
shared integrated terminal 11 characters wide on guest side

### ISSUE THREAD

**Issue by dgh1000** [microsoft/vscode#101775]
Issue Type: <b>Bug</b>

I was not able to find related issues open.

I frequently use Live Share on my MacBook with my students who are on Windows machines, including sharing an integrated terminal in read-only mode. I have lots of trouble with the terminal looking garbled, but I wanted to stick to a specific issue that I can reproduce.

My student was running Live Share on VS Code v1.46 on Windows 10. I connected via the join option in the sidebar with the link he sent to me. He destroyed his terminal by clicking the trash can, then created a new one. One his side, the terminal behaved normally. On my side, it looked like it was wrapping all the characters into a column 11 characters wide.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 6, 4|
|Memory (System)|16.00GB (2.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|2.1.5
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.12
html-snippets|gey|0.2.3
vscode-picture|Jak|1.0.0
hoogle-vscode|jca|0.0.7
language-haskell|jus|3.3.0
chat|kar|0.35.0
csound-vscode-plugin|kun|0.2.3
tag-inserter|l7s|1.4.0
quickstart|lol|0.1.0
eclipse-new-java-project|mel|1.0.1
hindent-format|mon|0.0.11
python|ms-|2020.6.91350
azure-account|ms-|0.8.11
cpptools|ms-|0.28.3
vsliveshare|ms-|1.0.2427
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.8
vscode-purty|mva|0.4.1
printcode|nob|3.0.0
ide-purescript|nwo|0.21.1
language-purescript|nwo|0.2.4
ghci-helper|rco|0.0.9
java|red|0.63.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.0.3
rewrap|stk|1.12.0
ejs-snippets|Tao|0.1.0
java-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
HTML5-extension-pack|wal|0.0.3
html-snippets|wge|0.1.5

</details>

**Comment by Tyriar** [comment]
Might be https://github.com/microsoft/vscode/issues/55718

**Comment by Tyriar** [comment]
Please report to the live share ext https://github.com/MicrosoftDocs/live-share
