### ISSUE TITLE
Freezing of desktop while using VS Code for even 5 minute

### ISSUE THREAD

**Issue by Gulshan2002** [microsoft/vscode#101717]
- VSCode Version:1.46
- OS Version: Pop!_OS 20.04 LTS x86_64 

Steps to Reproduce:

1.Force Shutdown

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
