### ISSUE TITLE
Not able to assign keyboard shortcut to "Source Action"

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#101738]
Issue Type: <b>Bug</b>

Recently I came across "Source Action" and it changed the way I used to code, however, I could not associate a keyboard shortcut to the "Souce Action" (my allegiance lie with keyboard).
It would really help if source action can be associated with a keyboard shortcut.

VS Code version: Code - Insiders 1.47.0-insider (376d9d9d785ccca128fdbb16f001446d0ad64d32, 2020-07-03T10:27:06.804Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.2
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
output-colorizer|IBM|0.1.2
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
vscode-pylance|ms-|2020.6.1
remote-containers|ms-|0.126.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
cordova-tools|msj|1.9.4
debugger-for-chrome|msj|4.12.9
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.19.0
vscode-manifest-yaml|Piv|1.19.0
vscode-spring-boot|Piv|1.19.0
fabric8-analytics|red|0.0.13
java|red|0.63.0
vscode-xml|red|0.12.0
vscode-yaml|red|0.8.0
sonarlint-vscode|Son|1.16.0
code-spell-checker|str|1.9.0
vscode-stylelint|sty|0.84.0
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
vscode-spring-boot-dashboard|vsc|0.1.10
vscode-spring-initializr|vsc|0.4.8
quokka-vscode|Wal|1.0.306

</details>

**Comment by mjbvz** [comment]
What have you tried so far?

The release notes show an example of creating a keybinding for a source action: https://code.visualstudio.com/updates/v1_46#_add-all-missing-imports-source-action

**Comment by sanket-bhalerao** [comment]
@mjbvz I am able to add the keybinding using keybindings.json. Thank you.

However, by default, the Source Action keybinding is not visible in the keyboard shortcuts UI.
![image](https://user-images.githubusercontent.com/9264813/86710773-f0455a80-c038-11ea-9ff6-f7262a0fca4f.png)

once its added  to the keybinding.json file 
![image](https://user-images.githubusercontent.com/9264813/86710920-123edd00-c039-11ea-83e1-534dc0f245e4.png)

it becomes visible in the UI
![image](https://user-images.githubusercontent.com/9264813/86711002-24b91680-c039-11ea-8a7a-b6642f41a5af.png)

is the Keyboard Shortcuts search option not showing all the options that can be set/bound? Is making all option available/searchable a possibility?

**Comment by pwsq** [comment]
Hi I want to give it a try

**Comment by susiwen8** [comment]
Related to #70230

**Comment by susiwen8** [comment]
I'm working on this issue

**Comment by sandy081** [comment]
Feel free to close this as dup of https://github.com/microsoft/vscode/issues/84072 if it is asking for same.

**Comment by sandy081** [comment]
Related - https://github.com/microsoft/vscode/issues/113732

Underlying rule - all commands those shown in command pallette should be able to configurable from keybindings editor.

Fixed.
