### ISSUE TITLE
extensionKind: ["ui"] can't depend on extensionKind: ["workspace"]

### ISSUE THREAD

**Issue by bestander** [microsoft/vscode#101873]
`extensionDependencies` field is checked during extension activation and is used to schedule activation of them in the right order.

There are cases when a feature is split between UI and workspace into multiple extensions, e.g. mobile development workflows where simulators are managed by UI extension and source code is compiled by a workspace extension.

When using [Remote Development](https://code.visualstudio.com/api/advanced-topics/remote-extensions) a UI extension can't have a dependency on a workspace extension, the UI extension fails to activate.
Can we add a more loose version of `extensionDependencies` field that would trigger a workspace extension installation after vscode is connected to a remote workspace?

**Comment by alexdima** [comment]
@bestander here is what we did in this situation in the past:
1. on the ui extension, in its `package.json`, use `"api": "none"`. This is enforced at runtime and no other extension will be able to consume any API exposed by this extension, even when everything executes locally. This is the marker that helps the second bullet point work.
2. on the workspace extension, in its `package.json`, add an extension dependency to the ui extension. This will work correctly, i.e. if your workspace extension is activated via an activation event, the ui extension will first be activated, and only after the ui extension is activated on the ui machine, will the workspace extension activate.

You can then proceed to register one or more commands from the ui extension that you can invoke from the workspace extension. I like to think of the problem as exposing the mobile simulator API via one or more commands from the UI extension to the workspace extension.
