### ISSUE TITLE
Ask your GitHub colleagues to enable Discussions on the repo

### ISSUE THREAD

**Issue by warrenbuckley** [microsoft/vscode#101818]
As GitHub is owned by the lovely people at Microsoft, it would be nice if this repo got some of the newer GitHub features such as the community/discussions feature.

Where questions and other things that are not issues or feature requests can be put in a more central place.

**Comment by warrenbuckley** [comment]
@vscode-triage-bot oh mighty robot 🤖 can you assign someone to this please?

**Comment by warrenbuckley** [comment]
@egamma or @kieferrm any update on this issue at all, is it likely that the VSCode repository will get the GitHub beta feature turned of for discussions?

**Comment by egamma** [comment]
@warrenbuckley we already have several feedback channels see https://github.com/microsoft/vscode/wiki/Feedback-Channels. These channels work fine and have established communities. We therefore have to be sensitive to channel changes. Also, before enabling Discussions on the VS Code project we want to first get experience with this new feature on one of our smaller satellite projects.

**Comment by warrenbuckley** [comment]
Valid concerns - just thought it made sense for you to use it. To keep discussions as close to the code as possible without looking through other places.
