### ISSUE TITLE
Hiding derived files does not work for *.js.map

### ISSUE THREAD

**Issue by db6edr** [Microsoft/vscode#10189]
- VSCode Version: 1.4.0
- OS Version: Windows 7 Enterprise x64

Steps to Reproduce:

1. Setup a TypeScript project with sourceMap: true and no outputDir.
2. Run TypeScript compilation
3. Configure [Hiding derived JavaScript files](http://code.visualstudio.com/docs/languages/typescript#_hiding-derived-javascript-files) following the documentation
4. Add another line `"**/*.js.map": { "when": "$(basename).ts"`} to also hide the derived mapping files

Expected Behavior:

The derived mapping files, ending in *.js.map, no longer show up in the explorer

Actual Behavior:

The derived mapping files, ending in *.js.map, still show up in the explorer

**Comment by bpasero** [comment]
http://stackoverflow.com/questions/34045749/excluding-js-map-files-from-project-when-ts-file-is-present
