### ISSUE TITLE
Not recognizing extensions correctly

### ISSUE THREAD

**Issue by seMikel** [microsoft/vscode#101851]
Issue Type: <b>Bug</b>

My VSCode stopped recognizing extensions correctly. It now treats .ts files as if they were .js files and .html file as if they were something else I cannot recongnize. Reinstalling did not work.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (18.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.1000.2
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.6
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
auto-rename-tag|for|0.1.4
hclappscancodesweep|HCL|1.1.0
beautify|Hoo|1.5.0
vscode-language-babel|mgm|0.0.29
vscode-docker|ms-|1.3.1
remote-wsl|ms-|0.44.4
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.8
angular2-inline|nat|0.0.17
typescript-hero|rbb|3.0.0
code-spell-checker|str|1.9.0
shell-launcher|Tyr|0.4.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

>It now treats .ts files as if they were .js files

Could you specify what exactly you mean when you say this? 

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Do you have any mappings in User or Workspace settings that mention these extensions e.g. `files.associations` ?

**Comment by seMikel** [comment]
Thanks for the suggestion, it does seem like one of my extensions updated and is causing the issue. I'll figure out which one myself.
