### ISSUE TITLE
two main menu items

### ISSUE THREAD

**Issue by yousefvand** [microsoft/vscode#101866]
- VSCode Version: 1.46.1
- OS Version: Linux x64 4.4.0-184-generic

Steps to Reproduce:

1. Random

Does this issue occur when all extensions are disabled?: Yes

It happens to any menu item like `Run` or `Help`

![2help](https://user-images.githubusercontent.com/18329462/86819890-8612d100-c09d-11ea-8f9b-6673c2e33936.png)

**Comment by sbatten** [comment]
When the items are duplicated, do the entries inside both menus work as expected? Under what conditions do they return to normal?

**Comment by yousefvand** [comment]
Yes menu entries work as expected. A vscode restart fixes the issue but it turns back very quickly. Last time I was copying version from help/about to attach it to issue it happened but on subsequent tries it didn't.

**Comment by sbatten** [comment]
can you try with 1.47, just released yesterday

**Comment by yousefvand** [comment]
The same with 1.47.0

I forgot to mention sometimes it fixes without restating vscode, for example closing a tab may fix it.

![menu](https://user-images.githubusercontent.com/18329462/87220734-b8614e80-c37b-11ea-9180-c86f16e10383.png)

**Comment by sbatten** [comment]
@yousefvand thanks for trying it out, will try to get a repro

**Comment by sbatten** [comment]
please post if this issue is still reproducing
