### ISSUE TITLE
Support the new search options in vscode.workspace.findFiles

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#101889]
Working on merging in https://github.com/microsoft/vscode-js-debug/pull/377. Since that PR was submitted, we added Vue handling which involves enumerating all .vue files in the workspace.

`vscode.workspace.findTextInFiles` has lots of nice new options for configuring what files are excluded. It doesn't look like these have been ported back to `vscode.workspace.findFiles`.

**Comment by roblourens** [comment]
Also https://github.com/microsoft/vscode/issues/48674#issuecomment-423285008

**Comment by roblourens** [comment]
Closing for https://github.com/microsoft/vscode/issues/48674
