### ISSUE TITLE
Encoding euckr does not exist anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101847]
@gyzerok this seems to be a regression in the webpack version of `iconv-lite`, I am pushing a test now to review...

**Comment by bpasero** [comment]
Uncomment this line to see the failure:

https://github.com/microsoft/vscode/blob/c212eface27d69060847aa9cca0226052be7f3a1/src/vs/workbench/services/textfile/test/node/encoding/encoding.test.ts#L410-L412

When I debug this I see the following exception for `encodingExists`:

`TypeError: Cannot read property '63' of undefined`

```
a (/Users/bpasero/Development/Microsoft/monaco/node_modules/iconv-lite-umd/lib/iconv-lite-umd.js:10)
a.getCodec (/Users/bpasero/Development/Microsoft/monaco/node_modules/iconv-lite-umd/lib/iconv-lite-umd.js:8)
a.encodingExists (/Users/bpasero/Development/Microsoft/monaco/node_modules/iconv-lite-umd/lib/iconv-lite-umd.js:8)
encodingExists (encoding.js:136)
await in encodingExists (async)
getEncodingForResource (textFileService.js:478)
getReadEncoding (textFileService.js:464)
overwriteEncoding (textFileService.js:80)
createDecoder (encoding.js:40)
await in createDecoder (async)
(anonymous) (encoding.js:74)
(anonymous) (stream.js:170)
flowData (stream.js:170)
resume (stream.js:56)
on (stream.js:122)
(anonymous) (encoding.js:61)
toDecodeStream (encoding.js:27)
doRead (textFileService.js:78)
await in doRead (async)
read (textFileService.js:54)
read (nativeTextFileService.js:28)
run (editorStatus.js:1116)
await in run (async)
triggerAndDisposeAction (actions.js:85)
await in triggerAndDisposeAction (async)
(anonymous) (actions.js:64)
invokeFunction (instantiationService.js:43)
_tryExecuteCommand (commandService.js:74)
(anonymous) (commandService.js:64)
Promise.then (async)
executeCommand (commandService.js:64)
executeCommand (statusbarPart.js:639)
(anonymous) (statusbarPart.js:594)
```

@gyzerok @ashtuchkin any clues?

**Comment by gyzerok** [comment]
@bpasero I can take a look tomorrow. Quick idea - this because of

https://github.com/microsoft/iconv-lite-umd/blob/6cc48fdd57904dfe84f33e72a1f294b8a7327a7a/webpack.config.js#L3-L14

**Comment by bpasero** [comment]
@gyzerok ok thanks. one thought I had: it would maybe be good if `iconv-lite-umd` would run the test suite of `iconv-lite` somehow to validate things are working fine. Maybe reduced depending on what VSCode is using.

**Comment by bpasero** [comment]
@gyzerok I ended up simply doing this change which makes the test succeed: 

https://github.com/microsoft/iconv-lite-umd/commit/f4180d8044930d3e2c65d73123f030511f1f3f0d

**Comment by dbaeumer** [comment]
Verified using the following steps:

- open this file: build/win32/i18n/Default.ko.isl
- in the status bar switch to encoding EUC-KR

Verify that encoding is picked
