### ISSUE TITLE
settings.json intellisense suggests incorrect items

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#101822]
- VSCode Version: 1.47.0-insider
Commit: 376d9d9d785ccca128fdbb16f001446d0ad64d32
Date: 2020-07-03T10:26:01.724Z (3 days ago)

- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

1. Install golang.go extension
2. Open "Settings", and find "Go: Language Server Experimental Features".  Click "Edit in settings.json"
3. See incorrect items suggested

This is a new problem in 1.47.0-insiders. Not observed in 1.46.1

Does this issue occur when all extensions are disabled?: N/A 

In 1.46.1

<img width="779" alt="Screen Shot 2020-07-06 at 6 22 41 PM" src="https://user-images.githubusercontent.com/4999471/86656792-baab5d80-bfb5-11ea-943c-e0c5befaaf3e.png">

Note that clicking "Edit in settings.json" inserts 
```
"go.languageServerExperimentalFeatures": {
    
 },
```

In 1.47.0-insiders

<img width="756" alt="Screen Shot 2020-07-06 at 6 23 52 PM" src="https://user-images.githubusercontent.com/4999471/86657046-ec242900-bfb5-11ea-88c7-8a2209116575.png">

Note that clicking "Edit in settings.json" inserts
```
    "go.languageServerExperimentalFeatures": {
    
        "diagnostics": true,
        "documentLink": true
    },
```

**Comment by gjsjohnmurray** [comment]
@sandy081 probably https://github.com/microsoft/vscode/issues/99854#issuecomment-652891096

**Comment by gjsjohnmurray** [comment]
> @sandy081 probably [#99854 (comment)](https://github.com/microsoft/vscode/issues/99854#issuecomment-652891096)

New 1.47 behaviour of 'Edit in settings.json' reported by @hyangah is from #99854 and is correct I think. Completion no longer offers the two defined values because default entries got added. I guess it lists 'abc' type completions because Go extension maybe doesn't specify `"additionalProperties": false`

**Comment by sandy081** [comment]
Yeah it is because of #99854. As suggested in the issue it is better not to trigger the suggestion.

**Comment by hyangah** [comment]
> I guess it lists 'abc' type completions because Go extension maybe doesn't specify `"additionalProperties": false`

I think I observed this issue first while testing https://github.com/golang/vscode-go/pull/284 that adds `additionalProperties`. I didn't see any differences UX wise with and without the field, so I wondered what difference the PR would make.

**Comment by sandy081** [comment]
Meanwhile settings editor has been improved and is able to support modifying some of the object types like the one reported here. I would ask to please recheck if the bug still happens to you and let us know.

Thanks.
