### ISSUE TITLE
Find in files operation extremely slow after upgrade to 1.46

### ISSUE THREAD

**Issue by marcmorente** [microsoft/vscode#101842]
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.0-9-amd64

**Comment by roblourens** [comment]
Can you check whether any of the tips here are relevant? https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by marcmorente** [comment]
Well, after upgrade to version 1.46, find in files worked properly and relatively fast without doing any configuration as you mentioned.

When I put a word to search, the first occurrences appear relatively fast, but then, the finder take half-second more or less doing a background process to finally put the last occurrence(s).

But I put `"search.followSymlinks": false` into `settings.json` and seems to be that is working better than before.

**Comment by roblourens** [comment]
Nothing really changed here in 1.46, so I'm not sure what the issue is, sorry. `"search.followSymlinks": false` this is a common configuration, sounds like it helps

**Comment by ochristensen** [comment]
Seeing the same in 1.46.1 on MacOS 10.15.5
I have searched for something which I know occurs 3 times across ~2,600,00 lines without symlinks (though I've set `"search.followSymlinks: false"` just to be sure)
in 1.45.1 that search takes less than 10 seconds; in 1.46.1 it takes 60+ seconds

not sure if it's related but we do have a mix of file encodings (utf16 and utf8)

**Comment by roblourens** [comment]
The new Insiders build actually has a new rg version, and I'm curious whether that's any better for you @ochristensen
