### ISSUE TITLE
Changes not showing up to commit or push to github

### ISSUE THREAD

**Issue by darlajford** [microsoft/vscode#101881]
Issue Type: <b>Performance Issue</b>

Yesterday while working on coding in VS, the screen went blank and everything quit working. Then VS closed by itself. It took a few minutes to get it started again and then it asked for the github password. Since that time, I have been able to work in VS but the changes are not showing up to be committed nor can I push to github. I have tried several pushes today, but the last push showing in github is 24 hours ago.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.83GB (6.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    81	 10144	code main
    1	    66	  1864	   shared-process
    0	    13	  2648	   electron-crash-reporter
    1	    72	  5000	   window (Issue Reporter)
    0	    25	  6132	   utility
    1	   154	  8736	   gpu-process
    0	   205	 12384	   window (scootsIndex.html - darlajford.github.io - Visual Studio Code)
    0	    14	  1800	     watcherService 
    0	     5	  2308	       console-window-host (Windows internal process)
    0	    78	  8480	     extensionHost
    0	     5	  1400	       "C:\Program Files\Git\cmd\git.exe" push origin master:master
    0	     4	  2984	         git.exe push origin master:master
    0	     4	  4796	           git remote-https origin https://github.com/darlajford/darlajford.github.io
    0	     9	  6504	             git-remote-https origin https://github.com/darlajford/darlajford.github.io
    0	     6	 12620	               sh -c "git credential-manager get" "git credential-manager get"
    0	     4	  9048	                 "C:\Program Files\Git\mingw64\libexec\git-core\git.exe" credential-manager get
    0	    55	 12516	                   git-credential-manager get
    0	     5	  9056	         console-window-host (Windows internal process)
    0	    40	  7368	       "C:\Users\dejae\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\dejae\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=8480
    0	    49	 13736	       "C:\Users\dejae\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\dejae\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=8480
    0	    29	 18240	       "C:\Users\dejae\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\dejae\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=8480
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (scootsIndex.html - darlajford.github.io - Visual Studio Code)
|    Folder (darlajford.github.io): 379 files
|      File types: html(101) jpg(76) css(56) png(39) js(21) ico(9) scss(6)
|                  json(3) DS_Store(3) map(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
LiveServer|rit|5.6.1

</details>

**Comment by joaomoreno** [comment]
> changes are not showing up to be committed nor can I push to github

These sound like two very different problems.

Can you please provide a [screen recording](https://gifcap.dev/) of the issue you're seeing?

**Comment by darlajford** [comment]
It seems for some reason my VS was disconnected from Github, probably happened when VS stopped working for a bit. I am not sure what happened but I got a prompt in VS to sign back in to Github. I entered my password and now everything is working again. I am not sure what the issue was, but am happy to be back in business. Thanks for reaching out.
