### ISSUE TITLE
Syntax highlight don't support JS' ?: optional chaining operator?

### ISSUE THREAD

**Issue by glacjay** [microsoft/vscode#101894]
Issue Type: <b>Bug</b>

Tried many color theme, and the colors all break after the `?:` operator.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (18.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
theme-verdandi|be5|2.0.1
vscode-custom-css|be5|3.0.10
markdown-mermaid|bie|1.5.1
better-toml|bun|0.3.2
thief-book|C-T|0.0.9
vscode-autohotkey-plus|cwe|2.4.7
autoit|Dam|1.0.5
vscode-eslint|dba|2.1.6
githistory|don|0.6.5
xml|Dot|2.5.0
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
shell-format|fox|7.0.1
toml-formatter|ice|0.0.3
sublime-babel-vscode|jos|0.2.10
vscode-language-pack-zh-hans|MS-|1.46.3
node-debug2|ms-|1.42.4
snippet-creator|nik|0.0.5
java|red|0.64.0
rust|rus|0.7.8
trailing-spaces|sha|0.3.1
language-stylus|sys|1.11.0
stylus-supremacy|thi|2.14.5
html-preview-vscode|tht|0.2.5
ghosttext|tok|1.1.0
vscode-jsx-style|upp|1.0.1
vim|vsc|1.14.5
markdown-auto-toc|wib|0.3.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.1.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
This is most likely caused by one of your extensions, specifically sublime-babel-plus-vscode which was last updated 3 years ago

**Comment by glacjay** [comment]
Yeah it works! Thank you.
