### ISSUE TITLE
Showing error

### ISSUE THREAD

**Issue by adityavermaa** [microsoft/vscode#101814]
Issue Type: <b>Bug</b>

Its showing Error on Absolutely write and woorking code!
please resolve it

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (3.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-html-css|ecm|0.2.3
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
code-runner|for|0.10.0
python|ms-|2020.6.91350
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by adityavermaa** [comment]
Thanks for your response!

**Comment by bpasero** [comment]
.
