### ISSUE TITLE
Unable to debug unit tests

### ISSUE THREAD

**Issue by mrj001** [microsoft/vscode#101877]
Issue Type: <b>Bug</b>

Create a new solution:
$ dotnet new console -n MyConsole
$ dotnet new xunit -n test
$ dotnet add test/test.csproj reference MyConsole/MyConsole.csproj
$ dotnet sln program.sln add MyConsole/MyConsole.csproj
$ dotnet sln program.sln add test/test.csproj

Add this to Program.cs in MyConsole folder:
        public static bool DoSomething()
        {
           return false;
        }

Change Test1 to:
        [Fact]
        public void Test1()
        {
           Assert.True(Program.DoSomething());
        }

$ dotnet build 
- succeeds

Launch vscode
Open the folder
Generate assets for build & debug
Select program to launch
Open the UnitTest1.cs file.  Click “debug test”
get
Error Processing Launch options at field: Program

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
docomment|k--|0.1.13
csharp|ms-|1.22.1

</details>

This is the output of dotnet --info:

> .NET SDK (reflecting any global.json):
>  Version:   5.0.100-preview.6.20310.4
>  Commit:    16d29b9349
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.15
>  OS Platform: Darwin
>  RID:         osx.10.15-x64
>  Base Path:   /Users/mj/Documents/develop/runtime/.dotnet/sdk/5.0.100-preview.6.20310.4/
> 
> Host (useful for support):
>   Version: 5.0.0-preview.6.20305.6
>   Commit:  4ba9ecaabd
> 
> .NET SDKs installed:
>   5.0.100-preview.6.20310.4 [/Users/mj/Documents/develop/runtime/.dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 5.0.0-preview.6.20309.8 [/Users/mj/Documents/develop/runtime/.dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [/Users/mj/Documents/develop/runtime/.dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET runtimes or SDKs:
>   https://aka.ms/dotnet-download
>

**Comment by weinand** [comment]
Please file against C# extension
