### ISSUE TITLE
command + <number> key behaviers

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#10188]
We can use **`command+\`** and **`command+<number>key`** to split editor.
Why not use **`command+<number>key`** to switch tabbar file list.

Just we have three file `a`,`b`,`c`opened. So use **`command+1`** open `a`,**`command+2`** open `b`,**`command+3`** open `c`.

**Comment by djyde** [comment]
+1

**Comment by bpasero** [comment]
We decided against this because it badly breaks existing behaviour. Closing as wont fix.

**Comment by djyde** [comment]
It's not possible to allow user set on keymap settings?

**Comment by bpasero** [comment]
@djyde did you even try?
