### ISSUE TITLE
Integrated Terminal not allows to scroll up 

### ISSUE THREAD

**Issue by morwin10** [Microsoft/vscode#10185]
- VSCode Version: 1.4.0
- OS Version: Windwos 7 Ultimate 64bit

I tried to scroll with CTRL+ Arrow keys  or  SHIFT + Arrow keys 
But it doesn't work

![capture](https://cloud.githubusercontent.com/assets/3899222/17435170/a42eaa82-5b17-11e6-9dc0-b4dec3b2bc9b.PNG)

![ver](https://cloud.githubusercontent.com/assets/3899222/17435172/a8c846a2-5b17-11e6-8bf6-85ba1f69c9f7.PNG)

**Comment by Tyriar** [comment]
This is coming in v1.5.0 and will be available for testing in the [Insiders build](https://code.visualstudio.com/insiders) tomorrow (#10302).
