### ISSUE TITLE
 Structure keyword highlighting behavior needs improvement

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/vscode#101846]
![image](https://user-images.githubusercontent.com/5162926/86764944-17248080-c07b-11ea-97f7-2ba9ca1ff737.png)
the color is the same as variable， I think the _TestStruct_ need be else color

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version and which extensions you are using.

**Comment by xspeed1989** [comment]
> /needsMoreInfo including version and which extensions you are using.

ext on remote(ssh):
C/C++ 0.28.3
CMake 0.0.17
CMake Tools 1.4.1

ext on global:
Syntax Highlight Theme  publisher:"peaceshi" 0.0.12

Visual Code 1.46.1

**Comment by alexr00** [comment]
@xspeed1989 this can't really be done with the built in grammar we use for syntax highlighting. I recommend that you install the [C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools), which improves upon the built in colorization:
![image](https://user-images.githubusercontent.com/38270282/87306035-b7fdba80-c517-11ea-9d6b-e08bd5870061.png)
