### ISSUE TITLE
leading TAB by snippets won't replace by spaces

### ISSUE THREAD

**Issue by yousefvand** [microsoft/vscode#101870]
- VSCode Version: 1.46.1
- OS Version: Linux x64 4.4.0-184-generic

Steps to Reproduce:

1. Create a simple snippet with leading `\t`
2. Use snippet while vscode is in `Indent using spaces` mode.
3. All `'\t`s would be replaced by spaces except the leading one.

Does this issue occur when all extensions are disabled?: Yes

Sample user snippet (shellscript.json):

```
{
  "test": {
    "prefix": "test",
    "body": "\tHello World\n\tNew Line",
    "description": "Test snippet"
  }
}
```

I'm using  2 spaces at `\t` and here is the result:

```
🡒Hello.World
 ..New.Line
```

The `TAB` before Hello is not replaced with spaces.

![tab](https://user-images.githubusercontent.com/18329462/86822241-9c6e5c00-c0a0-11ea-8d47-710df8d466c5.png)

**Comment by jrieken** [comment]
Looks like we do that on [purpose](https://github.com/microsoft/vscode/blob/28cb90be8c65ed4fc54622297e2508e75684f138/src/vs/editor/contrib/snippet/snippetSession.ts#L344) but the question is why...

**Comment by yousefvand** [comment]
To make a good example of double standard?

**Comment by jrieken** [comment]
I think it's more a case of "why would one author a script like that?". Fix should be easy and I don't see an obvious negative impact

**Comment by yousefvand** [comment]
Thanks. The actual snippet where I faced this issue is [here](https://github.com/yousefvand/shellman/blob/master/nsroot/fn-fx/fn-animate.json).

**Comment by jrieken** [comment]
Confused? That snippet doesn't start with `\t` on its first line

**Comment by yousefvand** [comment]
In that snippet it happens at the first line after comment. Line 11 start's with `\t`.

```
..# comment out next...
🡒trap 'tput...
..trap 'exit...
```
![tab](https://user-images.githubusercontent.com/18329462/87027420-62ad6a80-c1f2-11ea-9885-c84bac64346b.png)

**Comment by jrieken** [comment]
Thanks for clarifying. I have pushed a failing/omitted test for this but fixing this is actually harder then I thought. Not sure anymore if this will happen in July
