### ISSUE TITLE
Preferences sync dies on latest VSCode Insiders version.

### ISSUE THREAD

**Issue by skamansam** [microsoft/vscode#101861]
# Issue Type: <b>Bug</b>
#### To Reproduce:
1. Start VSCode Insiders
##### Expectation:
  * Expect the preferences to sync, with no errors
##### Actual Results:
  * The preferences menu says "Turn on Preferences sync"

#### Extra Steps:
1. Click on the preferences icon
1. Select "Turn on Preferences Sync..."
1. Choose all settings to sync from the resultant window
1. Click the button labelled, "Turn On" in the same window
1. Select the account with which you wish to sync

##### Expectation:
  * Preferences should sync with no errors
##### Actual Results:
  * A notification is displayed that reads, "Error while starting Sync: GET request 'https://vscode-sync.trafficmanager.net/v1/resource/globalState/latest' failed because of too many requests (429)."

Here is a screenshot of the `Log (Preferences Sync)` with the error notification:
![Screenshot from 2020-07-07 12 27 51](https://user-images.githubusercontent.com/102971/86812940-969b5b00-c04d-11ea-89e5-4d59246f2e86.png)

VS Code version: Code - Insiders 1.47.0-insider (376d9d9d785ccca128fdbb16f001446d0ad64d32, 2020-07-03T10:15:57.898Z)
OS version: Linux x64 5.6.19-300.fc32.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3749)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|15.49GB (0.19GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (72)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.3.0
generator-vue-components|Nic|0.1.5
better-comments|aar|2.0.5
Bookmarks|ale|11.3.1
vscode-sqlite|ale|0.8.2
i18n-ally|ant|2.2.7
statusbar-commands|anw|0.1.0
sourcetrail|ast|0.0.2
atlascode|atl|2.6.6
vscode-django|bat|0.20.0
django-snippets|bib|1.1.1
vscode-exports-autocomplete|cap|0.5.4
vscode-postgres|cko|1.1.11
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
vue-peek|dar|1.0.2
ini-for-vscode|Dav|0.0.4
vscode-eslint|dba|2.1.6
vscode-quick-select|dba|0.2.8
vscode-dash|dee|2.4.0
wpy-beautify|doi|2.0.10
git-extension-pack|don|0.1.3
githistory|don|0.6.5
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
vscode-diff|fab|1.4.0
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.9.0
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
docker-explorer|for|0.1.7
vscode-pull-request-github|Git|0.17.0
sass-lint|gle|1.0.6
vscode-ungit|Hir|2.2.3
rest-client|hum|0.24.1
vue|jcb|0.1.5
firebase-explorer|jsa|0.3.3
vscode-gutter-preview|kis|0.26.2
marp-vscode|mar|0.14.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.3.1
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.6.91350
remote-containers|ms-|0.126.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.9
sqltools|mtx|0.22.10
sqltools-driver-pg|mtx|0.1.0
autodocstring|njp|0.5.3
vetur|oct|0.24.0
indent-rainbow|ode|7.4.0
vscode-code-outline|pat|0.2.1
material-icon-theme|PKi|4.2.0
ruby|reb|0.27.0
vscode-yaml|red|0.8.0
elastic|ria|0.13.3
partial-diff|ryu|1.4.1
language-stylus|sys|1.11.0
vscode-json-stable-stringify|Tra|1.2.0
vscodeintellicode|Vis|1.2.9
gitblame|wad|4.0.1
quokka-vscode|Wal|1.0.306
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2
vscode-ruby|win|0.27.0
markdown-all-in-one|yzh|3.1.0
html-css-class-completion|Zig|1.19.0
vsc-docker|Zim|0.34.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/101504
