### ISSUE TITLE
open integrated terminal run node debugger

### ISSUE THREAD

**Issue by fablec** [microsoft/vscode#101864]
- VSCode Version: 1.47.0-insider
- OS Version: OSX Catalina 10.15.5 & Linux Mint 19.3
default shell : zsh

Opening integrated terminal run a node debugger

<img width="1085" alt="Screenshot 2020-07-07 at 19 28 58" src="https://user-images.githubusercontent.com/195961/86819622-3675da80-c088-11ea-8974-eb2b40def653.png">

Does this issue occur when all extensions are disabled?: Yes

Debug node auto attach is on in the settings, changing to off seems to fix the problem

**Comment by weinand** [comment]
If "auto attach" is on, the debugger will attach to any node.js program.
Are you running a node.js program from your .zshrc file?

**Comment by fablec** [comment]
no, there is no node program executed by my .zshrc
and in the previous versions I have not encountered this problem, it suddenly appears just after upgrade and restarting code-insider

**Comment by connor4312** [comment]
Are you using nvm? If so, that does execute an npm script during startup.

**Comment by stepli1010** [comment]
> If "auto attach" is on, the debugger will attach to any node.js program.
> Are you running a node.js program from your .zshrc file?

integrated oh-my-zsh terminal, .zshrc does not execute

**Comment by connor4312** [comment]
Are you sure? Without executing the ,zshrc you would not get those fancy command line decorations with the time/branch/node version, for example.

**Comment by stepli1010** [comment]
> Are you sure? Without executing the ,zshrc you would not get those fancy command line decorations with the time/branch/node version, for example.

sorry, i solve my own problems,  my settings is:"terminal.integrated.shell.linux": "/bin/zsh", but new zsh version is somewhere, add the new zsh to PATH  then  change  the settings:"terminal.integrated.shell.linux": "zsh",  it's ok.

**Comment by fablec** [comment]
I solve my problem by disabling "debug javascript Use Preview" in the settings

**Comment by connor4312** [comment]
There is also now a feature in the newest build that allows you to choose to inspect only if `--inspect` is given on the command line, similar to the old auto attach behavior, see: https://github.com/microsoft/vscode-js-debug/issues/566#issuecomment-656916160
