### ISSUE TITLE
Missing ESLint command implementation

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#10187]
- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/8189808/17436279/3fcd5ff8-5b16-11e6-8c8c-2754f2deda29.png)

- OS Version: Win 10 x64

@dbaeumer Sorry but since there is no repo for the extension I thought I drop it here.

Steps to Reproduce:

1. Install ESLint extension
2. Hit Ctrl+Shift+Alt+F fix all eslint errors
3. 
![image](https://cloud.githubusercontent.com/assets/8189808/17436249/1d974f34-5b16-11e6-8d7f-618719c75e37.png)

**Comment by kumarharsh** [comment]
@con-ssc  there is a repo: https://github.com/Microsoft/vscode-eslint

**Comment by con-ssc** [comment]
Oh, sorry I wasn't able to find it looking at @dbaeumer github profile

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-eslint#109

**Comment by dbaeumer** [comment]
Moved.
