### ISSUE TITLE
"Open with Code" in Context of Desktop causes Error

### ISSUE THREAD

**Issue by NikoMix** [Microsoft/vscode#1018]
Hello,
if you right-click on the desktop (Win 10) "Open with Code" is available, but if you click it an error message appears.

<img width="155" alt="menu item" src="https://cloud.githubusercontent.com/assets/809210/11592169/26961bb8-9a9d-11e5-92de-e5e61c0a6281.PNG">
<img width="418" alt="error" src="https://cloud.githubusercontent.com/assets/809210/11592168/2692c5c6-9a9d-11e5-898c-108586d919bb.PNG">

**Comment by joaomoreno** [comment]
This is more likely the old shortcut from before `0.8.0`, that an update failed to remove. You can remove it by opening the Registry (`regedit.exe`) and deleting the following keys:

```
HKEY_CURRENT_USER\Software\Classes\*\shell\Ticino
HKEY_CURRENT_USER\Software\Classes\directory\shell\Ticino
HKEY_CURRENT_USER\Software\Classes\directory\background\shell\Ticino
```
