### ISSUE TITLE
Using vscode.workspace.findTextInFiles with an empty non-regex pattern times out

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#101890]
I was trying to hijack findTextInFiles as a general file matcher since `vscode.workspace.findFiles` doesn't support all the exclusion options yet (https://github.com/microsoft/vscode/issues/101889)

```
this.vscode.workspace.findTextInFiles({ pattern: '', isRegExp: true }, ...
```

Works ✔️ 

```
this.vscode.workspace.findTextInFiles({ pattern: '', isRegExp: false }...
```

Never calls the callback or resolves ❌

**Comment by connor4312** [comment]
Actually, this approach does not work since it matches every character in every file, which is...not efficient. I'll fall back to the glob-stream based approach for this scenario.

**Comment by roblourens** [comment]
You can probably construct a clever search that produces one multiline match per file. Like if you set the multiline flag and search for `.*`. Should the first and second error? Or complete with no matches? I think matching every character is wrong.
