### ISSUE TITLE
Debugger highlights the wrong line when stopping if word wrap is present higher up in file

### ISSUE THREAD

**Issue by LightCC** [microsoft/vscode#101891]
Issue Type: <b>Bug</b>

This was found in Python files, and it may be specific to Python, I have not tried to reproduce in another language.

When debugging, I've seen this before, but finally zero'd in on the issue. It happens if you have word-wrap set to on and have lines higher up in the file that are wrapping.

#### Wrap Wrap Related Settings (in case it matters):
* Editor: Word Wrap: On (not wordWrapColumn or bounded)
* Editor: Wrapping Indent: deepIndent
* Editor: Wrapping Strategy: simple
* Debug > Console: Word Wrap: enabled

All the breakpoint line numbers and the placement of the breakpoints appear to be correct. For example, if you look in the "breakpoints" window, the line number indicated matches with the line number which was clicked and where the breakpoint visually showed up:

* Here, the first two breakpoints show as line 71 and 79 on the right:
   * ![image](https://user-images.githubusercontent.com/19731713/86856849-375c3b80-c08b-11ea-84c1-9fe7fe9bd9b7.png)
* And in the code, the breakpoints show up at the same lines:
   * ![image](https://user-images.githubusercontent.com/19731713/86856908-5a86eb00-c08b-11ea-8846-1413e6b396d2.png)

And, the debugger appears to stop at the correct line - i.e. where the breakpoint is located, but something is wrong with which line it is on, if any line higher up in the file has been wrapped by the "word wrap" function. For example, you have a current width that is 40 characters, and have a line that wraps because it is 60 characters, then there is a continuation line that doesn't have a line number on it:
   * Here on line 37, it is wrapped twice, so two lines with no line number shown:
      * ![image](https://user-images.githubusercontent.com/19731713/86857055-a5086780-c08b-11ea-8b1d-c8f4808741de.png)

It's tough to figure out exactly what is going on, but if you add a few **for loops** and then some **if/else** statements, you'll notice that the highlighted lines do not match up with the code as you step through it in debugging mode. They are shifted down a few lines. I finally realized that the number of the lines they are shifted appears to correspond to how many lines are wrapped higher up in the file.

In other words, it seems that the breakpoint highlighting (and possibly the location of the breakpoints as well are not taking into account the extra lines in the editor window that are word wrapped. I'm not sure if it is just lines wrapped in the current view - it appears to be any line wrapped anywhere higher in the file at all.

i.e. if line 1 has 100 characters, and the width of the window is 40 characters, the line numbers on the left will start at 1, 2 lines will be blank where the line wraps, and then the 4th physical line of the file will start with "2" for the 2nd line in the actual file. It appears the debugger gets off by some amount based on how many lines are wrapping and/or how many times they wrap.

Example of wrapping in editor:
![image](https://user-images.githubusercontent.com/19731713/86856666-c9b00f80-c08a-11ea-9dc9-dd7a0108646b.png)

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (13.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

<details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.6
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.36.1
ini-for-vscode|Dav|0.0.4
xml|Dot|2.5.0
json-tools|eri|1.0.2
vscode-open-in-github|fab|1.2.3
matlab|Gim|2.0.0
gc-excelviewer|Gra|3.0.37
todo-tree|Gru|0.0.177
vscode-test-explorer|hbe|2.19.1
beautify|Hoo|1.5.0
reg|ion|1.0.1
vscode-edit-csv|jan|0.2.11
vsc-python-indent|Kev|1.10.1
restructuredtext|lex|128.0.0
rainbow-csv|mec|1.7.0
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
python|ms-|2020.6.91350
cpptools|ms-|0.28.3
idl|myt|0.3.1
autodocstring|njp|0.5.3
vscode-coverage-gutters|rya|2.5.1
code-settings-sync|Sha|3.4.3
matlab-snippets|sky|1.11.0
better-search|tra|0.0.6
python-extended-snippets|tus|0.0.1
highlight-matching-tag|vin|0.9.9
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.1.1
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|3.1.0
json|Zai|1.0.4

</details>

**Comment by weinand** [comment]
I don't think that word-wrap (which is a view only feature) and Python (where the syntax relies on correct indentation) goes together well. Please file the issue against the Python extension first.

**Comment by LightCC** [comment]
I'm surprised by the comment - Python works perfectly fine with long lines and word-wrap. Indentation only matters when a new underlying line is required.

I was thinking the Python specific behavior might be in the debugger implementation area. I can log against Python, of course.

**Comment by weinand** [comment]
No, VS Code knows nothing about Python (or any other language). All language specific functionality is provided by extensions.

**Comment by LightCC** [comment]
I didn't word that very well. I'm seeing this issue in Python, yes, but I don't think it's due to anything specific to Python, given the behavior.

All that said, I've logged an issue with the Python extension and they can refer it back here if needed.

**Comment by int19h** [comment]
Line-wrapping has no effect on Python extension, since, as you've mentioned, it's strictly a presentation feature. The debugger sees the source code as it actually is, and reports line numbers accordingly.

@LightCC, can you please check the line numbers that you see in the Call Stack pane when breakpoints are hit? If those line numbers are correct, that would indicate that the debug adapter is doing everything right, and the bug with highlighting is due to VSCode itself not applying those numbers correctly.

This may be related to #100805. Even if it's not the same root cause, my hypothesis in https://github.com/microsoft/vscode/issues/100805#issuecomment-649207096 wrt `column`, `endLine`, and `endColumn` not being set by the Python debug adapter when reporting line numbers may be applicable here.

**Comment by LightCC** [comment]
Update: Can't get this to happen on my home PC. It is likely only happening on my work PC, which, with remote working at the moment, is remoting into a workstation from a laptop (windows 7 laptop to windows 10 workstation with normal windows remote session through a VPN). This messes with the screen scaling (removes it) and that's my top guess at the root cause at the moment.

I'll run the checks requested on the problem setup and report back...

**Comment by lbaiao** [comment]
I'm having the same problem. Was it solved? Where is the solution? I'm running VSCode 1.47.3, on Windows 10.

**Comment by weinand** [comment]
@lbaiao since we cannot reproduce the problem we do not know where it comes from and how it can be fixed.

Can you please check the line numbers that you see in the Call Stack pane when breakpoints are hit? If those line numbers are correct, that would indicate that the debug adapter is doing everything right, and the bug with highlighting is due to VSCode itself not applying those numbers correctly.

**Comment by weinand** [comment]
@LightCC you are talking about "Debugger highlights the wrong line" but none of your screenshots are showing any highlight.
Please provide one screeshot that shows the "full picture" and not only fragments, that is the breakpoint view, the call stackview and the highlighted line in the editor.
