### ISSUE TITLE
After entering "Tab" key, unable to undo that operation in special cases

### ISSUE THREAD

**Issue by sanals** [microsoft/vscode#101898]
We have written the needed data into your clipboard because it was too large to send. Please paste.I am facing this issue with react web app. Have not tried it anywhere else.

Step 1 - create javascript file and enter below code

Step 2 - 

`<TableCell align="right">`
`    <Link style={{ textDecoration: 'none', color: "black" }} to="/examreport">`
`        <EqualizerRoundedIcon fontSize="small" />`
`    </Link>`
`</TableCell>`

Step 3 - Place cursor on  line 1 as specified:  Tab(CURSOR)leCell  
Step 4 - Press tab key in keyboard
step 5 - Try to undo this! You will get the issue

**Comment by gjsjohnmurray** [comment]
/confirmationPending

![junk](https://user-images.githubusercontent.com/6726799/86914276-ee9e9400-c117-11ea-9182-12f0f5343ff6.gif)

> step 5 - Try to undo this! You will get the issue

Please explain "the issue"

**Comment by sanals** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16471631/87123212-f2f7b800-c2a3-11ea-8977-24bb9ff2030d.gif)

> You can see that on pressing 'tab', the whole tag opening and closing changes from TableCell to Tab .

> To recover from it, I have to keep the ctrl+z pressed and it exits the cycle, but uncontrolled.

**Comment by gjsjohnmurray** [comment]
Is https://github.com/microsoft/vscode/issues/88424#issuecomment-600840619 relevant? Is your `editor.renameOnType` perhaps set to true?

**Comment by sanals** [comment]
Will check that. But still. ctrl+z must not do that right?
