### ISSUE TITLE
Cannot Install extensions inside WSL:Ubuntu-20.04

### ISSUE THREAD

**Issue by mhshakouri** [microsoft/vscode#101892]
I was trying to do some Svelte, and headed out to install the extension https://github.com/UnwrittenFun/svelte-vscode.git and found out I can only install it on windows side of VS Code, not the WSL side, and this extension is not globally active, so I headed out and checked out a few other extensions, and the problem persist. 

VS code Version : 1.46.1
WSL2 - Ubuntu-20.04

**Comment by aeschli** [comment]
I tried to reproce, but installing the svelte-vscode extension in a Remote - WSL window on Ubuntu 20.04 worked for me.

Can you give more information that you see and what doesn't work?
Do you see the button `Install on WLS: Ubuntu`? What happens when you press it?

**Comment by mhshakouri** [comment]
Hi aeschli, such a fast response !
yes I can see the button "Install in WSL: Ubuntu-20.04" and when pressing it nothing ever happens. I can confirm I tried to install a few other packages and that didnt work.

**Comment by mhshakouri** [comment]
I think the issue is of my non-standard wsl installation, since I managed to get a full pledge GUI of different DEs, till when I check if the issue is reproducible on a normal wsl installation I'll close this issue. Thanks for your attention anyways, cheers.
