### ISSUE TITLE
When IME enabled, some key bindings not work.

### ISSUE THREAD

**Issue by tomoki1207** [Microsoft/vscode#10183]
- VSCode Version: 1.4.0
- OS Version: Windows 8.1 Pro
- Language: JP

Steps to Reproduce:
1. IME on
2. Input keys like `Ctrl+k, v`
3. `v` detected as 'unknown' and key binding not work.(May be detected full-width `ｖ`, not `v`)

**Comment by rebornix** [comment]
We already changed the implementation under the hood and I can not reproduce this on Windows any more. @tomoki1207 can you help verify?

**Comment by tomoki1207** [comment]
I rechecked its behavior. 
+ Ver. 1.11.2
+ OS Win 8.1 Pro

Surely a full-width character is not treat as undefined. But even not detected as a part of command.
This char is inputted in editor, the VSCode still waiting for next command char.
![capture](https://cloud.githubusercontent.com/assets/3643499/25214265/35b56192-25d1-11e7-8885-e34481dd61ef.gif)

I think it is not fixed completely. Is this behavior as expected?

**Comment by rebornix** [comment]
@tomoki1207 this is as-design, since IME is in composition state, we don't allow any command to avoid conflict with IME.
