### ISSUE TITLE
Client side sync rate limiting

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#101815]
Verifying https://github.com/microsoft/vscode/issues/99102

A couple things, first when I trigger this by executing "Sync Now" a lot of times, I get two notifications

![image](https://user-images.githubusercontent.com/323878/86632454-460bfb00-bf84-11ea-8713-42955c8b7ba9.png)

The second is good but the first has no context and seems redundant.

Also I'm just wondering in what scenarios would the user see this? Clearly if I run that command 100 times in a row something weird is going on, but is it also possible that I could see it just from editing my settings.json many times quickly? In that case, what am I supposed to do about that and how do I reenable Sync? This has probably been discussed a bunch already but did you consider doing something quieter like debouncing sync with a larger timeout? Or, if this would probably only happen as the result of some weird bug, it's probably fine to get in the user's face like this.

**Comment by sandy081** [comment]
First message is an error notification for the operation (`Sync Now`) user performed manually has failed.

I do not think it is practical that a user performs this operation continuously. This can also happen if someone tries to initiate sync every 5s with a setting change. In this case user will see only second notification. Again this is not practical.

If user hits a client side rate limit without doing any non-realistic scenarios, then the client has some issue which has to be reported. So I do not think user shall be seeing this unless in an extreme unrealistic scenarios.

**Comment by roblourens** [comment]
Ok, the 2 notifications makes sense. One realistic case for making lots of settings.json edits that I can imagine is someone continuously tweaking colors (eg `workbench.colorCustomizations`) for a couple minutes. But they would have to be doing it very frantically and I guess we should wait and see whether it actually happens.
