### ISSUE TITLE
I can't push code from VS code but can do it from the CLI

### ISSUE THREAD

**Issue by gunslingerOP** [microsoft/vscode#101813]
- Extension version: v0.17.0
- VSCode Version:May 2020 (version 1.46)
- OS:[Kubuntu OS] 

My ssh key is functional as i can push, pull and merge with the remote repo from my CLI but when i try to do it in VS code using the  "Synchronize changes" button at the bottom left corner near the branch name, it outputs this error:

> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.

i have signed into VS code using my github account and checked using several methods if the issue is with my ssh key, it isn't.

**Comment by joaomoreno** [comment]
Which CLI? The VS Code integrated terminal? Or something else?

The Github authentication in VS Code only works with HTTPS repositories, so switching to that will address your issue.
