### ISSUE TITLE
Moving files doesn't rename the paths as per jsconfig

### ISSUE THREAD

**Issue by sendy34** [microsoft/vscode#101882]
Issue Type: <b>Feature Request</b>

In react, when I move my files, it auto renames the imported paths everywhere which is sooo cool :)

But when I have JSCONFIG added, then it doesn't rename based on Alias names defined.

Thanks!

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.0.0

**Comment by mjbvz** [comment]
Please provide steps (or better, a small example project) to reproduce  this issue

/needsMoreInfo

**Comment by mjbvz** [comment]
Closing as not-actionable without steps to reproduce this
