### ISSUE TITLE
Incorrect highlighting of active editor tab - OSX, dark mode

### ISSUE THREAD

**Issue by mrj001** [microsoft/vscode#101879]
- VSCode Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
- OS Version: macOS 10.15.5

Steps to Reproduce:

1. Have OS set to dark mode
2. Open multiple editor tabs

Does this issue occur when all extensions are disabled?: yes

The active editor tab has a black background, and the inactive ones are dark gray.  However, in Safari (and terminal), the inactive tabs have black background and the active one has a dark gray background.

VS Code;
![Screen Shot 2020-07-07 at 2 38 13 PM](https://user-images.githubusercontent.com/62225294/86840100-8ee4b200-c05f-11ea-8490-a941c8d639e5.png)

Safari:
![Screen Shot 2020-07-07 at 2 39 10 PM](https://user-images.githubusercontent.com/62225294/86840163-a6239f80-c05f-11ea-85d1-3ebdd13721d0.png)

**Comment by bpasero** [comment]
This can be changed via themes and settings. We do not detect macOS dark mode to update the colors.
