### ISSUE TITLE
Marketplace entry for Angular/Karma Test Explorer redirects to EditorConfig extension

### ISSUE THREAD

**Issue by dschuessler** [microsoft/vscode#101841]
- VSCode Version: 1.46
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Navigate to https://marketplace.visualstudio.com/items?itemName=raagh.angular-karma-test-explorer
2. Click on "Install"

Expected behavior: VSCode enables me to install Angular/Karma Test Explorer

Actual behavior: VSCode offers me to install the editorconfig extension.

![Bildschirmfoto 2020-07-07 um 10 38 18](https://user-images.githubusercontent.com/5774545/86750924-99428400-c03e-11ea-85e9-20e5e904f1fd.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
I cannot reproduce it. Clicking on install button opens VS Code and opens the correct extension. Are there any steps I am missing?

**Comment by dschuessler** [comment]
Here is a screen grab for comparison.

![Ohne Titel2 2020-07-07 14_48_42](https://user-images.githubusercontent.com/5774545/86783761-0535e400-c061-11ea-9a63-f64d1786af7f.gif)

**Comment by sandy081** [comment]
It seems you are opening with VSCodium and not VS Code. Please file issue against VSCodium.
