### ISSUE TITLE
Tasks: Duplicate problems go away when one contributor deletes them

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#101843]
In our selfhosting setup, run <kbd>Ctrl Shift B</kbd> to start compiling. Once done, open a TS file and make a compilation error. Notice now you have >0 problems. Close the file, now you have 0 problems 🐛. Open the task terminal, the compilation task should still be reporting the error.

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/58210
