### ISSUE TITLE
Broken C++ syntax highlighting

### ISSUE THREAD

**Issue by marzojr** [microsoft/vscode#101840]
- VSCode Version: Latest release
- OS Version: Observed on Windows and Linux (CentOS), likely all

Steps to Reproduce:

1. Open a new tab in VSCode and set language to C++
2. Paste the following code:

```C++
Test::Test() : Base ("{}") {
    Broken syntax highlight
}
```

The combination of the space between `Base` and `(`, and the curly braces in the string, combine to break the syntax highlighting. Removing the space fixes the issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by marzojr** [comment]
Actually, it seems that the curly braces aren't even needed: the following also displays broken highlighting:

```C++
Test::Test() : Base ("Broken syntax highlight") {
}
```

In this case, the string is not highlighted. But adding the braces breaks the highlighting afterwards, possibly throughout the whole file.

**Comment by alexr00** [comment]
I can get the broken highlighting with 
```c++
Test::Test() : Base ("{}") {
   // Broken syntax highlight
}
```

It looks like things start to go wrong on the first curly brace, which ends up with these scopes:
```
punctuation.section.block.begin.bracket.curly.function.definition.special.constructor.cpp
meta.head.function.definition.special.constructor.cpp
meta.function.definition.special.constructor.cpp
source.cpp
```

**Comment by alexr00** [comment]
Moved to the repo where we get our C++ grammar from

**Comment by marzojr** [comment]
Thanks!
