### ISSUE TITLE
hard lags

### ISSUE THREAD

**Issue by artem-rekunov** [microsoft/vscode#101860]
Issue Type: <b>Bug</b>

1) hard lags when deleting files (in the previous version this was not):
file deletion
2) hard lags with large text in the console (in the previous version this was not):
number of characters in the console more than 10k (response from the server)

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 4.19.0-9-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core  CPU      E6300  @ 2.80GHz (2 x 3354)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|5.82GB (0.88GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.0.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
material-icon-theme|PKi|4.2.0
trailing-spaces|sha|0.3.1
guides|spy|0.9.3
vs-code-node-require|tgr|1.4.7
vscodeintellicode|Vis|1.2.9
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.8.3

</details>

**Comment by artem-rekunov** [comment]
Sorry, I didn’t understand what additional information is needed?

The report was compiled using VScode itself and I added all the additional information.

if we are talking about what lags are ... then this is the program’s freeze\impossibility to perform actions at the time of executing file deletion or scrolling (
not print to the console, namely viewing\scrolling) the console with a large number of characters

**Comment by Tyriar** [comment]
Please provide a screenshot of [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com).

/label "needs more info"

**Comment by artem-rekunov** [comment]
Start-Date: 2020-07-09  11:22:06
Commandline: apt upgrade
Requested-By: argus (1000)
Upgrade: libavformat58:amd64 (7:4.1.4-1~deb10u1, 7:4.1.6-1~deb10u1), ruby2.5:amd64 (2.5.5-3+deb10u1, 2.5.5-3+deb10u2), libswresample3:amd64 (7:4.1.4-1~deb10u1, 7:4.1.6-1~deb10u1), libswresample3:i386 (7:4.1.4-1~deb10u1, 7:4.1.6-1~deb10u1), libpostproc55:amd64 (7:4.1.4-1~deb10u1, 7:4.1.6-1~deb10u1), libruby2.5:amd64 (2.5.5-3+deb10u1, 2.5.5-3+deb10u2), libavcodec58:amd64 (7:4.1.4-1~deb10u1, 7:4.1.6-1~deb10u1), libavcodec58:i386 (7:4.1.4-1~deb10u1, 7:4.1.6-1~deb10u1), libavutil56:amd64 (7:4.1.4-1~deb10u1, 7:4.1.6-1~deb10u1), libavutil56:i386 (7:4.1.4-1~deb10u1, 7:4.1.6-1~deb10u1), libswscale5:amd64 (7:4.1.4-1~deb10u1, 7:4.1.6-1~deb10u1), libavresample4:amd64 (7:4.1.4-1~deb10u1, 7:4.1.6-1~deb10u1), libavresample4:i386 (7:4.1.4-1~deb10u1, 7:4.1.6-1~deb10u1)
End-Date: 2020-07-09  11:22:15


The problems were resolved by updating (released today \ yesterday), thanks for your time. Have a good day
