### ISSUE TITLE
Issue reporter: remove node.js/electron dependencies

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#101833]
The issue reporter depends on a lot of Electron/node.js and should move into `electron-sandbox` compatible layer. The dependencies can be broken up by e.g. depending on the `IElectronService` instead. More methods can be added to this service as needed.

**Comment by RMacfarlane** [comment]
It looks like you've already moved over the Electron calls to use `IElectronService`, the only things still in `electron-browser` are the code for the issue reporter itself and the `ISharedProcessService`. In the sandbox architecture, what happens to the shared process? Is it also in `electron-sandbox`?

**Comment by bpasero** [comment]
The shared process will likely remain a background window with node.js access.

**Comment by bpasero** [comment]
@RMacfarlane I wonder if it is worth the trouble requiring the telemetry service from the issue reporter? If we do not use the events, maybe we can simplify the code and remove the shared process dependency for now.

**Comment by bpasero** [comment]
Alternatively, maybe easier to add more methods to `IElectronService` for now to access the telemetry service. This has the disadvantage of needing 2 hops to reach the telemetry code in shared process, but since it is low volume it should be fine.

**Comment by bpasero** [comment]
@RMacfarlane I went ahead and worked on this, would like to hand it over since I soon leave on vac and 2 things are unclear to me (log needs, telemetry needs). Please check https://github.com/microsoft/vscode/pull/102949
