### ISSUE TITLE
Saving custom editors marks file as non-edited before `CustomDocument#save` promise returns

### ISSUE THREAD

**Issue by tiagobento** [microsoft/vscode#101872]
- VSCode Version: 1.46.1
- OS Version: macOS Catalina 10.15.3
##
Steps to Reproduce:

1. Install the BPMN Editor https://marketplace.visualstudio.com/items?itemName=redhat.vscode-extension-bpmn-editor
2. Create a new BPMN file (e.g. `example.bpmn`)
3. Insert a Start node (Green circle)
4. Leave a dangling arrow (attached on the rear end on the green node, dangling on the pointy end)
5. Notice how the file is marked as edited
6. Save the file
7. Notice how the file is now not marked as edited
8. Close the file and open it
9. Notice how it is does not contain the edits you've made

##

Does this issue occur when all extensions are disabled?: No

##

Detailed explanation:

When a dangling arrow is present on a diagram, it's not possible to save it, because it is considered a validation error. We currently don't have a good error-treatment tool, but even if we did, the file would be marked as non-edited by VS Code and if someone accidentally closed the editor before fixing the validation problems, their work would be lost.

My understanding is that VS Code should wait for the return of `CustomDocument#save` to decide if the file should be marked as non-edited. If the promise resolves normally, the file should be marked as non-edited, if the promise rejects, no change should be made.

This would prevent users from accidentally closing the editor and losing their work. If they really want to quit, VS Code's native confirmation popup should appear and provide the customary choices to the user.

**Comment by tiagobento** [comment]
@mjbvz FYI

**Comment by alexr00** [comment]
The unsaved/saved marking works nicely now, but if I close VS Code while the save promise is still happening I don't get the "Do you want to save this" dialog.

**Comment by mjbvz** [comment]
@alexr00 Were you testing in extension development mode? Many of the prompts on on close are disabled when you are developing an extension. Here's what I see after installing a packaged extension that takes 10 seconds to save:

<img width="781" alt="Screen Shot 2020-10-29 at 2 17 22 PM" src="https://user-images.githubusercontent.com/12821956/97633565-8985eb80-19f1-11eb-9c86-9b00c9e45c4b.png">

(note that there's a separate issue where if you click `save`, we trigger a second save which cancels the first)

**Comment by alexr00** [comment]
agh. yes I was testing in extension development mode.
