### ISSUE TITLE
Turn on sync command is not available

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#101868]
Issue Type: <b>Bug</b>

Click accounts icon 

VS Code version: Code - Insiders 1.47.0-insider (e95f9e63380a139cb1cbe54bacfc6703b96e30b9, 2020-07-07T07:46:21.608Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
mock-debug|and|0.42.1
vscode-eslint|dba|2.1.6
EditorConfig|Edi|0.15.1
vscode-github-releases-updater|joa|0.18.0
vscode-peacock|joh|3.7.2
chat|kar|0.35.0
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
python|ms-|2020.6.91350
remote-containers|ms-|0.126.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
js-debug-companion|ms-|1.0.2
vscode-github-issue-notebooks|ms-|0.0.33
cloudenv-extensions|ms-|1.0.1369
vsliveshare|ms-|1.0.2427
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
vsonline|ms-|1.0.2427
debugger-for-chrome|msj|4.12.9
test-search-rg|rob|0.0.3
code-spell-checker|str|1.9.0

</details>

When I click on the Accounts icon I see this:
![image](https://user-images.githubusercontent.com/1704059/86821806-c3b63080-c082-11ea-8a73-023d63335a15.png)

The gear menu looks like:
![image](https://user-images.githubusercontent.com/1704059/86821854-d03a8900-c082-11ea-9661-533afea9df5e.png)

Command palette:
![image](https://user-images.githubusercontent.com/1704059/86821906-dc264b00-c082-11ea-9f76-c94622fee4ea.png)

Nothing showing in Output window:
![image](https://user-images.githubusercontent.com/1704059/86822107-198ad880-c083-11ea-9e31-e88d849f50a2.png)

Any ideas?

**Comment by RMacfarlane** [comment]
Do you have any `sync` related settings configured? Can you double check that there is a "Microsoft Authentication" log in the output panel?

**Comment by stevencl** [comment]
I did have some old sync settings there but deleted those. I see a Microsoft Authentication log in the output panel although it is empty.

**Comment by stevencl** [comment]
Got today's update and now the commands are showing up.

**Comment by sandy081** [comment]
I think this is the same bug that @misolori mentioned. If you have old sync config setting it requires restart of VS Code after you deleted them. I assume with new update you restarted VS Code and hence sync is shown.

**Comment by misolori** [comment]
@stevencl I think what we didn't do is a full restart of VS Code, we just reloaded the window.
