### ISSUE TITLE
When I put a new folder within a new folder it hides the subfolder.

### ISSUE THREAD

**Issue by knbrlo** [microsoft/vscode#101888]
Issue Type: <b>Bug</b>

Create a new folder.
Create a subfolder within that new folder.
Now the subfolder is hidden within the explorer on the left side of the editor. 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (2.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|11.1.0
vscode-django|bat|0.20.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
compulim-vscode-dictionary|Com|0.0.5
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.6
githistory|don|0.6.5
python-extension-pack|don|1.6.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.12
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.1.3
auto-close-tag|for|0.5.8
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.4
code-runner|for|0.11.0
go|gol|0.15.0
json2ts|Gre|0.0.6
todo-tree|Gru|0.0.177
live-html-previewer|hdg|0.3.0
r|Iku|1.4.2
r-pack|Iku|0.0.2
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
forcecode|Joh|3.22.7
ts-extension-pack|loi|0.2.0
MagicPython|mag|1.1.0
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2427
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.8
vscode-react-native|msj|0.16.1
vuejs-extension-pack|mub|1.2.1
vetur|oct|0.24.0
vscode-react-refactor|pla|1.0.5
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0
r-lsp|REd|0.1.6
vscode-essentials-snippets|rob|2.0.0
highlight-words|rsb|0.1.4
salesforcedx-vscode-apex|sal|48.23.0
salesforcedx-vscode-core|sal|48.23.0
salesforcedx-vscode-lightning|sal|48.23.0
vue-vscode-snippets|sdr|1.9.0
html5-boilerplate|sid|1.0.3
move-ts|str|1.12.0
full-stack-developer-extension-pack|svi|1.1.2
vscodeintellicode|Vis|1.2.9
nodejs-extension-pack|wad|0.1.9
quokka-vscode|Wal|1.0.306
html-snippets|wge|0.1.5
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
material-theme|zhu|3.8.3
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does this also happen if you reload with all extensions disabled? If yes, please post screenshots or animated GIF to help us understand what you mean.

**Comment by knbrlo** [comment]
Hi @gjsjohnmurray, thank you for the quick reply and the help. As requested I disabled all extensions and I'm seeing the same behavior. The folders are now nested horizontally until I make about 5 of them and then it'll let me organize them vertically. The need to organize them vertically allows me to move files into them while I stub out a project and that's where I saw the issue the first time. I've included a gif that shows the steps to reproduce. 

![folder_issue](https://user-images.githubusercontent.com/2896821/86993317-f2a2d400-c160-11ea-8acf-6d1ac2a3ef97.gif)

**Comment by gjsjohnmurray** [comment]
Thanks for the gif. This feature is called 'compact folders'. See https://code.visualstudio.com/updates/v1_41#_compact-folders-in-explorer

You can turn it off if you want. But note that when it is on the individual folders can be acted on using their context menus. How are you moving your files into the folders? Did you try targeting the desired folder in the horizontal list?

**Comment by gjsjohnmurray** [comment]
Looking again at your gif, maybe all you need to do is focus on your workspace root each time before you create a new folder.

**Comment by isidorn** [comment]
You can disable this behavior via 	`"explorer.compactFolders": false,`. Closing this as designed

**Comment by knbrlo** [comment]
@isidorn Thanks!
