### ISSUE TITLE
Support perf metrics for web

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101850]
Goal is to have the ITimerService and the Performance View (F1 > Startup Performance) working for the web. Not all values we currently have apply but things like loading the the main bundle or digesting contributions does apply.

**Comment by jrieken** [comment]
with ea59ae20bee5e76b1d260e34e0b7b696d0b94a7d and 2e802ebcfea5bd69957a496cf6489ce2608869ac the timer service and the perf view is available in the web. What's missing is some critical perf mark to measure startup

**Comment by jrieken** [comment]
@bpasero can you help me to get equivalent marks for `willLoadWorkbenchMain` and `didLoadWorkbenchMain` ( [see here](https://github.com/microsoft/vscode/blob/fe948046015dd9941cd01c9b87e66e6451f66c28/src/vs/code/electron-browser/workbench/workbench.js#L62))

**Comment by bpasero** [comment]
@jrieken I would think that you can add `didLoadWorkbenchMain` here:

https://github.com/microsoft/vscode/blob/c70ac014c39714d2b611407693288728bbc1b4b7/src/vs/code/browser/workbench/workbench.ts#L281

As for `willLoadWorkbenchMain` the only solution I can think of is adding it into the `script` tag of the HTML before we load other scripts (this would not make them appear for Codespaces though as they have their own HTML entry file):

https://github.com/microsoft/vscode/blob/c70ac014c39714d2b611407693288728bbc1b4b7/src/vs/code/browser/workbench/workbench.html#L30

and

https://github.com/microsoft/vscode/blob/c70ac014c39714d2b611407693288728bbc1b4b7/src/vs/code/browser/workbench/workbench-dev.html#L29

This needs tweaks to our CSP though.

**Comment by jrieken** [comment]
> vscode/src/vs/code/browser/workbench/workbench.html

How does that case work? There is no require call in that one

**Comment by bpasero** [comment]
I actually do not remember anymore, quite sure I did this together with @alexdima. But how is that relevant, I think we just need to ensure to put the perf-start-marker as early as possible, no?

**Comment by alexdima** [comment]
In the case of `src/vs/code/browser/workbench/workbench.html`, we use manual `<script>` tags to load the workbench, which is faster than creating script tags from the `loader.js`. The requests can be made in parallel by the browser as soon as the browser parses the `.html` and the evaluation still happens sequentially, but that is OK.

So if you want to know the time it takes to "require" workbench.main.js, I think you could try adding a `<script>` tag in the header and recording the `Date.now()` or perhaps use some special purpose HTML5 API -- https://www.html5rocks.com/en/tutorials/webperformance/basics/.

**Comment by jrieken** [comment]
@alexdima where would I put the "after" mark? What's the signal that all of the workbench.main has been loaded?

**Comment by jrieken** [comment]
> What's the signal that all of the workbench.main has been loaded

nvm - figured that out

**Comment by jrieken** [comment]
Adding `renderer ready` which is purely focused on the renderer and allows us to compare browser perf vs electron-renderer perf

<img width="1047" alt="Screenshot 2020-07-09 at 13 09 15" src="https://user-images.githubusercontent.com/1794099/87032775-65559300-c1e5-11ea-8996-81bccc0734d1.png">

**Comment by bpasero** [comment]
@jrieken I like. I see that for web this is the very first entry in the HTML, but for desktop it is not. Shouldn't we put the `renderer/started` very high up into `src/vs/code/electron-browser/workbench/workbench.html` to compare the same thing?
