### ISSUE TITLE
console color

### ISSUE THREAD

**Issue by panoshar** [microsoft/vscode#101802]
Issue Type: <b>Bug</b>

When I write the word  "console" in a JS file, it turns green and then immediately light blue. It should stay green.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
trailingwhitespacehighlighter|paj|0.0.2
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
quokka-vscode|Wal|1.0.306

</details>

**Comment by mjbvz** [comment]
@aeschli This sounds like semantic highlighting. We also have a text mate rule for console (`support.class.console.ts`) that I can remove if we think it is no longer useful

**Comment by panoshar** [comment]
It's semantic highlighting, you're right. I disabled it and now console is green. Is it a bug, or it's an intended overide?

**Comment by aeschli** [comment]
The TypeScript semantic tokenizer has no concept for console. It will categorize console as a variable, which is how console is defined in node globals d.ts.

The textmate rule considers it a class (`support.class...`), which I think is not really correct.
I would be in favor of changing it to `support.variable.console`. @mjbvz Can you do this?

**Comment by mjbvz** [comment]
I've removed the special text mate grammar rule for `console` since it is not reliable. We see if insiders users have any feedback about this

**Comment by jgu7man** [comment]
Is the same problem here, how can I set console as support.class.console.ts for me, please?
