### ISSUE TITLE
launch:'filedirectory/$-{helloworld}' does not exist visual code kali

### ISSUE THREAD

**Issue by benedictadinku** [microsoft/vscode#101823]
![Screenshot from 2020-07-06 23-27-46](https://user-images.githubusercontent.com/45499343/86666663-d5ce9b00-bfbe-11ea-90c7-b1bd3ddb73dd.png)

**Comment by gjsjohnmurray** [comment]
Dialog button suggested opening launch.json file. Do that, and review what it contains. Check VS Code doc about it. If you can't solve your problem, paste content here (remove any confidential strings first).

**Comment by benedictadinku** [comment]
> Dialog button suggested opening launch.json file. Do that, and review what it contains. Check VS Code doc about it. If you can't solve your problem, paste content here (remove any confidential strings first).

**Comment by benedictadinku** [comment]
Please it didn't work

LAUNCH.JSON
"version": "0.2.0",
    "configurations": [


        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program":"${project}/${cash}"
,
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

**Comment by benedictadinku** [comment]
project is the name of the folder and cash.cpp is the file

**Comment by benedictadinku** [comment]
thanks for the reply i think i solved the  problem

**Comment by gjsjohnmurray** [comment]
@benedictadinku please close the issue.
