### ISSUE TITLE
[Source Control Provider view] mixed up menu items view header context menu

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#101831]
- VSCode Version: 1.46
- OS Version: macOS 10.15.5

Steps to Reproduce:

1. in vscode, open a parent directory which consists of multiple git repositories within its subdirectories.
2. open source control view, then right click on the "Source Control Providers" view header, e.g.:

![image](https://user-images.githubusercontent.com/610161/86719428-a10e2280-c056-11ea-8b62-56762ba3ffef.png)

3. here I have a parent dir named "microsoft", and it consists of local clones of "vscode" and "typescript".
4. as you can see in the context/popup menu, the entries for "vscode" and "typescript" are mixed with other menu items, such as "Issues" and "Repositories"

What's Expected:

The menu items for repositories from subdirectories should be put in a separate grouped, or even in a submenu, rather than mixed up with existing action oriented menu items.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
This UI is now gone, starting from 1.47. The `Source Control Providers` view doesn't exist any more.
