### ISSUE TITLE
Go to symbol ... - symbols are too short

### ISSUE THREAD

**Issue by demeter-macik** [Microsoft/vscode#10186]
- VSCode Version: Code 1.4.0 
- OS Version: Linux x64 4.2.0-42-generic

Steps to Reproduce:

1. Go to symbol Ctrl+Shift+O

Symbols in the list are too short. Is it possible to make them longer?

![goto-symbol-issue](https://cloud.githubusercontent.com/assets/15798474/17435671/b5b053c8-5b12-11e6-9f12-8524fa6db1fb.png)

**Comment by dbaeumer** [comment]
Dups a problem in the tsserver. Will be fixed with TS 2.0.
