### ISSUE TITLE
Remote: workspace color theme setting does not override default on startup

### ISSUE THREAD

**Issue by rhomel** [microsoft/vscode#101893]
- VSCode Version: 1.45, 1.46
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Open a remote SSH folder.
2. Add a custom workbench color theme to the workspace `.vscode/settings.json`:

```
{
    "workbench.colorTheme": "Quiet Light"
}
```

3. Close VSCode and restart. 

After Vscode starts up and opens the remote ssh folder, the workspace theme will not override the default setting.

Does this issue occur when all extensions are disabled?: N/A

This bug does not apply to local folders.

I was not sure where to file this bug since Vscode 1.44.2 works as expected.

**Comment by roblourens** [comment]
I can repro this.

**Comment by bcxpro** [comment]
I have this issue since 1.46, 1.45 works ok for me.
There is an issue about this in vscode remote. https://github.com/microsoft/vscode-remote-release/issues/3190

**Comment by anthonyalayo** [comment]
+1 and thanks for filing, I was struggling with this issue and then I found this ticket. I'm facing this when using WSL.

**Comment by bcxpro** [comment]
Works in today's insider!
```
Version: 1.52.0-insider (user setup)
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:43:01.017Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```
