### ISSUE TITLE
Enable Collapse/Expand of HEREDOC Bash Syntax

### ISSUE THREAD

**Issue by cbluth** [microsoft/vscode#101816]
I searched for an existing issue, i couldnt find anything that matched.

I love vscode, its my favorite tool for the job.
I have an issue with the bash syntax engine. It does not recognize the HEREDOC as capable for collapse/expansion. I would find this feature very useful.
Here is a screenshot:

![image](https://user-images.githubusercontent.com/6709636/86636249-5ba91100-bfd4-11ea-8d59-c8ab1fe49f31.png)

**Comment by aeschli** [comment]
VSCode ships only with basic support  for bash. Folding is based on indentation. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To support folding ranges for HEREDOC, a proper parser for bash is required. This has to come from an extension. https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode is such an extension but unfortunately it also doesn't support folding yet.  https://github.com/bash-lsp/bash-language-server/issues/18 is the feature request.
