### ISSUE TITLE
Debugger will not start C:/program 

### ISSUE THREAD

**Issue by paulsimongb** [microsoft/vscode#101996]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I have tried all the suggestions in #98778 and I am still getting the same error. Looking at the output it seems that the C:/ should be C:\, either than or it is a quote delimeter issue. However, I don't know where to fix this. 

The terminal shows: 

```
C:\AVueNode\UCoAMDM\Server> cmd /C "set "NODE_OPTIONS=--require "c:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" " && set "VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"\\.\pipe\node-cdp.11668-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\Program Files\nodejs\node.exe","onlyEntrypoint":false,"fileCallback":"C:\Users\psim1\AppData\Local\Temp\9\node-debug-callback-529c09196c041188"}" && c:\Users\psim1\AppData\Roaming\npm\nodemon.cmd c:\AVueNode\UCoAMDM\Server\js\server.js "
internal/modules/cjs/loader.js:583
throw err;
^

Error: Cannot find module '"c:/Program'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
at Function.Module._load (internal/modules/cjs/loader.js:507:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at Module._preloadModules (internal/modules/cjs/loader.js:812:12)
at preloadModules (internal/bootstrap/node.js:598:7)
at startup (internal/bootstrap/node.js:272:9)
at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

C:\AVueNode\UCoAMDM\Server>

```

This is the relevant section of launch.json

```
  {
      "name": "Debug Node",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}/Server",
      "runtimeExecutable": "nodemon",
      "program": "${workspaceFolder}/Server/js/server.js",
      "restart": true,
      "console":"integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "autoAttachChildProcesses": true,
      "skipFiles": [
        "<node_internals>/**/*.js*/",
        "<node_internals>/**/*..js*/",
        "${workspaceFolder}/Server/node_modules/**/*.js",
        "${workspaceFolder}/Server/mssqlserver/*.log"
      ],
      "smartStep": true,
      "env": { }
  },
```

This is the relevant part of settings.json

```
"javascript.updateImportsOnFileMove.enabled": "always",
"editor.scrollbar.verticalScrollbarSize": 30,
"editor.scrollbar.verticalScrollbarVisible": true,
"editor.scrollbar.verticalScrollbarMap": false,
"editor.scrollbar.horizontalScrollbarSize": 30,
"editor.find.autoFindInSelection": "always",

"debug.javascript.usePreview": true,

"workbench.colorCustomizations": {
    // Scrollbar
    "editorOverviewRuler.addedForeground": "#0000",
    "editorOverviewRuler.modifiedForeground": "#0000",
    "editorOverviewRuler.deletedForeground": "#0000",

    // Gutter (same as tweaking scm.diffDecorations?)
    "editorGutter.addedBackground": "#0000",
    "editorGutter.modifiedBackground": "#0000",
    "editorGutter.deletedBackground": "#0000",
},
"debug.node.autoAttach": "on",
```

I have tried changing the debug:node.autoAttach to disable, off, etc, but it made no difference.

The debugger was working before I upgraded to 1.46. I am still getting the same issue in 1.47 insider

I am going to revert to 1.45 if I can

Regards

Paul Simon

VS Code version: Code - Insiders 1.47.0-insider (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-08T10:52:52.439Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2665 0 @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (5.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by connor4312** [comment]
Thanks for the issue, this is the same as https://github.com/microsoft/vscode-js-debug/issues/543. I've added nodemon to the lookup/allowlist. This will be available in the [next nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension).

**Comment by paulsimongb** [comment]
Many thanks for prompt reply. I have upgraded to Node 12 and that has cured the issue.
