### ISSUE TITLE
Feature: Impove VSCode delivery - install VSCode with pre-requisits using WinGET

### ISSUE THREAD

**Issue by PavelSosin-320** [microsoft/vscode#101998]
Installation of VSCode with WSL Ubuntu distro and Docker Desktop, the correct tested versions using WinGET utilitiy.
Scrap installation documentation
Make VSCode instantly available!
Cut obsolete versions support

**Comment by Tyriar** [comment]
We're automating releasing Windows to winget this release, it's already available.
