### ISSUE TITLE
Notebook cell sizing issues

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#101940]
- Create a code cell with contents that overflow
- Toggle word wrap on that cell (alt+z)

Height ends up wrong:

![image](https://user-images.githubusercontent.com/323878/86952842-6c5aa380-c108-11ea-896a-6760b98d4fb8.png)

- Have a markdown cell, put it in edit mode
- Open the same notebook in a second editor
- In the second editor, edit that markdown cell to have more or fewer lines
- In the first editor, put the markdown cell back in edit mode, its height is still sized for the original contents

![image](https://user-images.githubusercontent.com/323878/86953098-c8252c80-c108-11ea-81e7-3d054799e804.png)

**Comment by rebornix** [comment]
it looks like a regression (not sure where yet) as word wrap is one of the major manual test suite.

**Comment by rebornix** [comment]
@roblourens  btw, are you seeing this issue in Insiders? I didn't reproduce in both Insiders and my current master.

**Comment by roblourens** [comment]
I see it in both

**Comment by roblourens** [comment]
The markdown one is straightforward, but the word wrap one is odd. When toggling word wrap off:

- Get `onDidContentSizeChange` 
- Results in `editor.layout` with that height
- Which fires `onDidContentSizeChange` again, with a different correct height (I think + the height of the horizontal scrollbar)
- And the two updates to the notebook cell height end up being applied in the wrong order, so the cell is 12px shorter than it should be

**Comment by rebornix** [comment]
> And the two updates to the notebook cell height end up being applied in the wrong order, so the cell is 12px shorter than it should be

After receiving those two size change events, we will queue layout updates with `DOM.scheduleAtNextAnimationFrame`, which ideally should queue the real layout/resize handler in the right sequence. You can probably find why if you add some logs there.

**Comment by roblourens** [comment]
It gets there in the wrong order because the second one is actually triggered by the call to `editor.layout`, and it waits to call layoutNotebookCell until the `editor.layout` call is complete. So basically, the first call triggers the second correct call, waits for it to be done, then calls `layoutNotebookCell` with the wrong height. We could call `layoutNotebookCell` before `editor.layout` and I think that would fix it.

**Comment by rebornix** [comment]
> We could call layoutNotebookCell before editor.layout and I think that would fix it.

Maybe we can even do better by postponing `editor.layout()` always to next frame if it's triggered by `onDidContentSizeChange` since `layout` has synchronous side effects.

**Comment by roblourens** [comment]
If we did that, then I think we would end up actually doing `layoutNotebookCell` twice, once in the next frame then again in the frame after that. I wonder whether it's better to do extra work or to interrupt our code with the sync layout but only do it once.

But it seems like the editor should be able to give us a height that includes the scrollbar on the first time through, so I'll try to figure out why it isn't.
