### ISSUE TITLE
Applocker logs are spammy when running wsl as admin user

### ISSUE THREAD

**Issue by Alslinet** [microsoft/vscode#101992]
- VSCode Version: 1.46.1
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Run Visual Studio Code as admin
2. Applocker logs spammed with code.exe being blocked, but nothing is actually blocked. And there are even rules defined that allow it to run.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Alslinet** [comment]
versjon 1.46.1
Version: 1.46.1 (system setup)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by aeschli** [comment]
The description says `running wsl as admin`. Did you mean `running VSCode as admin'?
