### ISSUE TITLE
The "T" of "Targets" in the label bar is "t"

### ISSUE THREAD

**Issue by penetrater** [microsoft/vscode#101980]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

- VSCode Version:1.46.1
- OS Version:win10 1909
Does this issue occur when all extensions are disabled?: NO

![VCQQU$%3GW`9 E)RZJHXFS1](https://user-images.githubusercontent.com/50835399/87016527-698fa980-c201-11ea-8cd5-b00228ce733b.png)

English from Baidu translation.

**Comment by penetrater** [comment]
![}L 3IPFQ4R3(S%{ARJ ~@{4](https://user-images.githubusercontent.com/50835399/87027132-49ff7d80-c20f-11ea-9f59-242abd3eda6a.png)
i am sorry，the images is error！

**Comment by penetrater** [comment]
![))(9N@630JTZ%}(V})S1WAH](https://user-images.githubusercontent.com/50835399/87027388-acf11480-c20f-11ea-8d84-f83308ef53ee.png)
i am sorry，the image is error！

**Comment by penetrater** [comment]
![~NG9QX%YWV_}AD ZMES`4K2](https://user-images.githubusercontent.com/50835399/87029911-62719700-c213-11ea-96b4-8470e36ee5e7.png)
who is error!

**Comment by bpasero** [comment]
This should be fixed in our 1.47 release.
