### ISSUE TITLE
Where is documentation for language configuration json?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10198]
I can't find much info on the language json files. From playing around I've come up with the following:

- `comments.lineComment` is used for commenting out code via command
- `blockComment` unsure ??
- `brackets` will automatically cause indents if you press enter between a pair (surroundingPairs don't)
- `autoClosingPairs` obviously provides closing character automatically and can be excluded from strings and comments (not sure if there are any other options allowed here?)
- `surroundingPars` highlights the other part of the pair (but without adding the indent functionality that `brackets` get)

Is there a doc somewhere?

**Comment by stkb** [comment]
Is this what you're looking for?
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages

**Comment by DanTup** [comment]
Yes! Not sure how I missed it. Thanks! 😀
