### ISSUE TITLE
"Run without Debugging" causes "Start Debugging" to no longer run with debugging

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#101986]
This one has been puzzling me for a few days! This happens with all debuggers - VS Code is incorrectly passing `noDebug: true` for a debug session if it was previously run without debugging.

To repro:

- create a simple JS script:
  ```
  console.log('test');
  ```
- Add a breakpoint and click Run -> Start Debugging and the breakpoint will be hit (correct)
- Run again with Run -> Run Without Debugging and the breakpoint will not be hit (correct)
- Run aagin with Run -> Start Debugging and the breakpoint will *not* be hit (incorrect)

@isidorn unsure if this is at all related to #100364 (seems like an opposite problem, perhaps related to the fix?)

**Comment by weinand** [comment]
What version is this?

**Comment by DanTup** [comment]
It was in Stable:

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

Seems like it may be fixed in Insiders. Is that version due out soon?

**Comment by weinand** [comment]
Yes, today I guess...
