### ISSUE TITLE
The `enter` key no longer responds.  

### ISSUE THREAD

**Issue by jm-trd-ms** [microsoft/vscode#101962]
Issue Type: <b>Bug</b>

The `enter` key no longer responds.  
Press `ctrl`+`enter` to perform the expected `enter` key action.  
Issue started 2020JUL08.  
Only effects VS Code.  
Remains across reboots and shutdowns.

Symptoms appear to be identical to [12929](https://github.com/microsoft/vscode/issues/12929), bit no solutions was presented in the previous issue.  

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.26GB free)|
|Process Argv|C:\GitHub\repos\ADO\Edge\chromium.WebFundamentals\src\content\en\tools\chrome-devtools\css\reference.md|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
Doxygen|bbe|1.0.0
vscode-doxygen-runner|bet|1.6.0
LinkCheckMD|bla|0.3.1
docs-build|cea|0.1.19
doxdocgen|csc|0.7.2
midl-webidl-syntax|dav|0.0.1
vscode-markdownlint|Dav|0.36.1
vscode-eslint|dba|2.1.6
docs-article-templates|doc|0.2.9
docs-authoring-pack|doc|0.1.8
docs-images|doc|0.0.9
docs-linting|doc|0.0.5
docs-markdown|doc|0.2.76
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.52
docs-yaml|doc|0.2.5
vscode-html-css|ecm|0.2.3
php-debug|fel|1.13.0
doxygen-previewer|hak|0.2.3
vscode-webidl|keq|0.0.1
pretty-formatter|mbl|0.2.1
csharp|ms-|1.22.1
vscode-edge-devtools|ms-|1.0.7
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
cpptools|ms-|0.28.3
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
debugger-for-edge|msj|1.0.15
idl|myt|0.3.1
vscode-yaml|red|0.8.0
code-spell-checker|str|1.9.0

</details>

**Comment by gjsjohnmurray** [comment]
Did you test after running the command to reload with all extensions disabled?

Did you check your keybindings?

**Comment by jm-trd-ms** [comment]
After **reload with all extensions disabled**, the `enter` key functions as expected.  
The issue returns after **docsmsft.docs-authoring-pack** is enabled.

**Comment by manastalukdar** [comment]
Happening on MacOS as well:

```
Version: 1.48.0-insider
Commit: c828a5339bca7222fd8f56ab98361a98f736d185
Date: 2020-07-14T05:40:51.403Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.5.0
```

**Comment by manastalukdar** [comment]
This appears to be an issue with an extension, `Markdown All in One`. Filed an issue [here](https://github.com/yzhang-gh/vscode-markdown/issues/751).

**Comment by manastalukdar** [comment]
Issue appears to be resolved with latest version of Insiders:

```
Version: 1.48.0-insider
Commit: 5e5fa3edde19d38ac512d65ccefe2a12ecab025a
Date: 2020-07-16T13:10:40.625Z
```
