### ISSUE TITLE
VSCode 1.46.1: minimap flickers

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode#101975]
- VSCode Version: 1.46.1
- OS Version: 10.15.5

Hello, I see that https://github.com/microsoft/vscode/issues/95178 is included in "May 2020" milestone.

But I can still reproduce the issue in 1.46.1

**Comment by alexdima** [comment]
@kzhui125  I have tried with the steps in https://github.com/microsoft/vscode/issues/95178#issuecomment-613367896 and I cannot reproduce the flickering anymore. Are there different steps ?

**Comment by kzhui125** [comment]
@alexdima I have upgrade VSCode to 1.47.0, can still reproduce.

reproduce steps:

https://streamable.com/i8clc4

some settings:

```json
    "workbench.sideBar.location": "right",
    "workbench.editor.showTabs": false,
    "editor.minimap.enabled": true,
    "editor.minimap.showSlider": "always",
    "editor.minimap.maxColumn": 60,
    "editor.fontSize": 12.5,
```

Thanks,

**Comment by alexdima** [comment]
@kzhui125 Does this still reproduce?

**Comment by kzhui125** [comment]
@alexdima I can't reproduce now. Thanks.

Closed..
