### ISSUE TITLE
Explore showing indent guide in notebooks as a visual indicator that cells are "under" the markdown headers

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#101934]
Now:

![image](https://user-images.githubusercontent.com/2193314/86940086-38c34d80-c0f7-11ea-8dce-343ef23652d1.png)

Example:

![image](https://user-images.githubusercontent.com/2193314/86940133-4a0c5a00-c0f7-11ea-8310-20855fbcf42c.png)

Maybe this could only show when hovering the twisty or header? This is similar to the list widget.

**Comment by tanhakabir** [comment]
We removed that whitespace and made the layout more compact by default so I'm not sure this is wanted anymore? Going to close for now but feel free to reopen if you feel otherwise
