### ISSUE TITLE
[Question] Bi-directional communication between adapter and extension

### ISSUE THREAD

**Issue by indiejames** [microsoft/vscode#101910]
Is it possible to use custom reverse Requests, similar to `RunInTerminalRequest`? I think I can just use `sendRequest` to send a request and give it a name, but it's not clear how to receive the request on the client side (in my extension code). Or do I have it wrong and there is no way for the adapter to communicate directly with the extension?

Maybe this is a better question for the VS Code forums?

**Comment by weinand** [comment]
@indiejames I've moved the issue to the VS Code repo since the raised question is independent from the npm module that implements a DAP library for node.js.

**Comment by indiejames** [comment]
@weinand that's great to know! I'm so far behind on the state of VS Code extension / debug adapter development :(

**Comment by weinand** [comment]
@indiejames Please check out [Mock Debug](https://github.com/microsoft/vscode-mock-debug).
The debug adapter now runs inside the extension which makes debugging/inspection much easier: just press F5 and you can step everywhere, both the extension and the DA.
The other modes of running the DA are still there and you can configure theme here: https://github.com/microsoft/vscode-mock-debug/blob/dc3ccfeb2195a1d2e5876f40fc9436b3b6f58a40/src/extension.ts#L12-L16
