### ISSUE TITLE
请添加“全站搜索”功能

### ISSUE THREAD

**Issue by xubin727** [microsoft/vscode#101964]
Issue Type: <b>Feature Request</b>

项目搜索在项目维护过程中很常用到。分两种，一种是在项目空间中按类名或文件名搜索文件，一种是在项目空间中按关键字搜索文件内容。这两个功能，可参考eclipse。如果能加上这个功能，我愿意彻底放弃eclipse开发环境。

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

**Comment by jdneo** [comment]
I believe these are all available in VS Code.

> 一种是在项目空间中按类名或文件名搜索文件

Suppose you are using Windows, `ctrl + p` is probably what you want.

> 一种是在项目空间中按关键字搜索文件内容

You can do this in the Search panel `ctrl + h`

**Comment by liqiang-p** [comment]
Ctrl + Shift + F 不知道是不是你想要的

**Comment by bpasero** [comment]
I am closing this and ask you to report an issue in english next time.
