### ISSUE TITLE
WSL2 + Git makes VSCode not show the current branch

### ISSUE THREAD

**Issue by Swader** [microsoft/vscode#101984]
Issue Type: <b>Bug</b>

When using WSL2, the branch name in the bottom left corner does not match the branch name that's in use.

VSCode still uses the proper branch to display code / files and everything works, but Git functionality is broken via WSL2, as if there is some sync issue that isn't being refreshed with the Refresh Explorer command.

Steps to reproduce / what happens:

- use WSL2
- check out any repo
- open folder in VS Code
- in terminal (outside VS Code) switch branch of repo
- observe that there is no change in the lower left corner branch indicator
- the change becomes apparent if I quit and reopen VS Code. If the branch is new (created in the terminal where the switch happened) it will not appear in VS Code's switch branch dialog. If the branch exists in that dialog from before, and the switch is made from within VS Code, it works fine.

![image](https://user-images.githubusercontent.com/1430603/87025452-bad87280-c1da-11ea-8586-e78cad3d1035.png)

What you expect to happen:

- the branch indicator should match that in the terminal

Possible solution:

- make Refresh Explorer check for this type of change as well

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (12.89GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.4.1
laravel-goto-view|cod|1.3.3
vscode-eslint|dba|2.1.6
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
php-debug|fel|1.13.0
auto-close-tag|for|0.5.8
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.4
vscode-power-mode|hoo|2.2.0
discord-vscode|icr|3.15.0
copy-markdown-as-html|jer|1.1.0
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
vetur|oct|0.24.0
laravel-blade|one|1.22.1
laravel5-snippets|one|1.9.0
laravel-artisan|rya|0.0.27
vue-vscode-snippets|sdr|1.9.0
vscode-status-bar-format-toggle|tom|2.0.0
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by joaomoreno** [comment]
If you use WSL, please use the [Remote WSL](https://code.visualstudio.com/docs/remote/wsl) extension.

**Comment by Swader** [comment]
As you can see by my extension list, the Remote WSL extension is already installed and used
