### ISSUE TITLE
Autodetect Encoding

### ISSUE THREAD

**Issue by jockrow** [microsoft/vscode#101930]
**Problem**: When I open a file, I have to guess the encoding or open with another text editor
I set this settings:
"files.autoGuessEncoding": true

This not autodetected ISO-8859-1 encoding in vsCode

**Comment by bpasero** [comment]
This setting is a "guess" so it is perfectly fine if it failed to "guess". We use https://github.com/aadsm/jschardet as library for detection so feel free to report an issue to them with detailed steps how to reproduce.
