### ISSUE TITLE
Integrated terminal's scroll bar disseapers in a GNU Screen session

### ISSUE THREAD

**Issue by jerinjamesm** [microsoft/vscode#101909]
Issue Type: <b>Bug</b>

The scroll bar in VS Code's integrated terminal dissapears after attaching to GNU Screen session. The scroll bar reappers when the GNU Screen session is detached. The key combinations like ctrl+pgdown do not seem to work either.

Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z (2 wks ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

**Comment by Tyriar** [comment]
Screen enters alt mode, which has no scrollback. You're describing exactly what's meant to happen.
