### ISSUE TITLE
Unable to edit first file while comparing files.

### ISSUE THREAD

**Issue by m-garg** [Microsoft/vscode#10193]
- VSCode Version: Version 1.4.0 (1.4.0)
- OS Version: OS X El Capitan (10.11.4)

Steps to Reproduce:

1. Select two files to compare.
2. Unable to edit the file in the left pane.

I think the first file should be read-only only in case of git diff, not while doing manual comparison of 2 files.

**Comment by alexandrudima** [comment]
relevant option is `originalEditable: true` when creating the diff editor.

**Comment by bpasero** [comment]
Thanks for reporting this issue. Please use the issue search next time to see if there is a duplicate already. In this case, the issue has already been reported.

**Comment by bpasero** [comment]
Here is the issue: https://github.com/Microsoft/vscode/issues/4180

And it is not as easy as just setting that editor option because it opens many UI questions (do you get 2 unread markers per each side when you edit left and right? what happens when you invoke the save action and both are dirty?).
