### ISSUE TITLE
Very high CPU usage all the time

### ISSUE THREAD

**Issue by uffanahmed** [microsoft/vscode#101917]
Issue Type: <b>Bug</b>

Very high CPU usage all the time

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.2.1
angular-schematics|cyr|4.3.0
ionic3-vs-ionView-snippets|dan|1.0.2
vscode-eslint|dba|2.1.6
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
vscode-pull-request-github|Git|0.17.0
ionic2-vscode|jgw|1.0.0
angular-essentials|joh|9.0.1
vscode-peacock|joh|3.7.2
ionic-extension-pack|loi|0.2.2
cpptools|ms-|0.28.3
cordova-tools|msj|1.9.4
debugger-for-chrome|msj|4.12.8
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
angular-console|nrw|12.0.0
material-icon-theme|PKi|4.2.0
rxjs-snippets|pko|0.0.2
ionic3-snippets|sit|1.0.1
autoimport|ste|1.5.3
ionic2|Tha|3.0.2
Angular2|UVB|0.4.1
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

https://github.com/microsoft/vscode/wiki/Performance-Issues
