### ISSUE TITLE
VS Code terminal fails to start when virtualized by AppV

### ISSUE THREAD

**Issue by kynisson** [microsoft/vscode#101947]
- VSCode Version: 1.46.1
- OS Version: Windows 10 1903 and above

Steps to Reproduce:

1. Feel free to contact me for a repro machine already setup, but if you want to set up your own I will provide the steps.
2. Get an AppV package of VS Code either by sequencing it yourself, or there is one attached to the MSFT OS bug 27185027
3. On powershell run:
        enable-appv
        Add-AppvClientPackage -Path <vscode.appv> | Publish-AppvClientPackage -Global | Mount-AppvClientPackage -Verbose
4. Launch VS Code and try to open a new terminal, it will fail.

Does this issue occur when all extensions are disabled?: Yes

This should be an issue with Windows/AppV, some regression between 1809 and 1903 but I can't find what is making the terminal fail, or which code.exe process it is happening in and there is not much of any logging around it.

**Comment by Tyriar** [comment]
@sbatten do you know things about AppV? Do we care about it?

> some regression between 1809 and 1903 but I can't find what is making the terminal fail

There was a major change in the terminal in that version, you can drop back down to the legacy (1809) system with `"terminal.integrated.windowsEnableConpty": false`

**Comment by kynisson** [comment]
I have confirmed that setting does fix the issue, thanks for that!

AppV is an enterprise feature for Windows that essentially runs win32 apps in a container by redirecting all registry and file operations to a secluded location. Each application can be sequenced into package which can be pushed down from IT to users to control which applications different employees are allowed to use.

If the legacy terminal wont be phased out and new features wont require the new terminal, then I think there is no reason for any investigation.

**Comment by Tyriar** [comment]
@kynisson it will probably be phased out eventually, but probably looking at a decade or so 😛 

Does the same thing happen if you run it in Windows Terminal? If it's possible to run that in AppV?

**Comment by Tyriar** [comment]
Closing since WT doesn't run in AppV.
