### ISSUE TITLE
ALL MY WORK IS GONE!!!!

### ISSUE THREAD

**Issue by sushi4life** [microsoft/vscode#101954]
Issue Type: <b>Bug</b>

ALL MY WORK IS NOW GONE AND I CAN ONLY FIND1-3 FILES OF MY WORK BUT NOW EVERYTHING IS GONE!! AND THE 1-3 FILES ARENT EVEN ON THE SAME PAGE SO I HAVE TO REPLACE THE FILES BACK INTO VISUAL CODE!!!IF THIS DOESNT GET FIXED IM GOING TO SUE U GUYS!

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3240 @ 3.10GHz (2 x 3092)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (1.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
html5-boilerplate|sid|1.0.3

</details>

**Comment by rafsanjani** [comment]
Really?
