### ISSUE TITLE
Test failure: should indent after simple jsx tag with attributes 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#101922]
This test has failed twice for me today:
https://dev.azure.com/vscode/VSCode/_build/results?buildId=48153&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=d494b5db-eef8-5766-984e-01186010c86f

**Comment by mjbvz** [comment]
This was likely caused by the extension not being activated when the test was run

**Comment by Tyriar** [comment]
@mjbvz not the best fix, timeouts are inherently flaky and this seems to adds .5s to the whole test suite?
