### ISSUE TITLE
Debug session ends but orphans extension host window

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#101955]
Logan reported that when extension host debugging (with webviews, which may or may not be related) that often the debugee window was getting orphaned. The debug session ends cleanly and VS Code normally takes care of window cleanup, so I think the issue is there. I'm having trouble finding exactly where the window gets torn down to be able to trace backwards, cc @weinand if you have pointers or ideas.

The scenario is three debug session:
- [Parent] logical wrapper session. Type `pwa-extensionHost`.
    - [Child] session for the extension host. Type `pwa-chrome` (which we use since there was an issue with nested extensionHost-type debug sessions.)
    - [Child] session for the webview. Type `pwa-chrome`.

Event sequence:

```
Session  |  Time | Direction | Data
wrapper  | +0ms  | received  | { command: disconnect, arguments: { restart: false } }
webview  | +1ms  | received  | { event: thread, body: { reason: 'exited' } }
webview  | +1ms  | send      | { event: terminated, body: {} }
ext host | +1ms  | send      | { event: thread, body: { reason: 'exited' } }
ext host | +2ms  | send      | { event: thread, body: { reason: 'exited' } }
ext host | +2ms  | send      | { event: terminated, body: {} }
wrapper  | +3ms  | send      | { event: terminated, body: {} }
wrapper  | +3ms  | send      | reply to disconnect command: { success: true }
webview  | +13ms | received  | { command: disconnect, arguments: { restart: false } }
webview  | +13ms | send      | reply to disconnect command: { success: true }
ext host | +13ms | received  | { command: disconnect, arguments: { restart: false } }
ext host | +13ms | send      | reply to disconnect command: { success: true }
```

Full logs: [vscode-debugadapter-5.json.gz](https://github.com/microsoft/vscode/files/4893540/vscode-debugadapter-5.json.gz)

@lramos15 fill in the next two sections please 🙂 Please also make note of what session is active when you click ⏹️ in the debug toolbar / what session you click stop on. In the logs you sent it looks like you stopped the logical wrapper session, but if you can (or cannot) reproduce it on other sessions that's useful information.

- VS Code version: Code - Insiders 1.47.0-insider (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-08T10:52:52.439Z)
- OS version: Windows_NT x64 10.0.19041

Steps to Reproduce:
I'm not sure. I just debug the hexeditor extension for about 10 minutes with breakpoints, stepping, and some watch variables and it happens about 80% of the time. I don't have consistent repro steps. The exthost is active when I press the stop button most often, but I've seen it happen with both.

**Comment by lramos15** [comment]
![recording](https://user-images.githubusercontent.com/4544166/87050001-ae98e900-c1cb-11ea-9e17-15e4c74d9402.gif)
Here's a gif of a 100% repo I found. I think the last part is the key. When I step on that single line if (arr1 === undefined || arr2 === undefined) return arr1 === arr2; and arr1 is undefined it just flashes. I assume stepping to the return, I then press stop and it leaves the child orphaned 100% of the time.

**Comment by weinand** [comment]
For extension host debugging we (debug UI) don't take down the window. We just terminate the node.js instance (the extension host) and that triggers some workbench code that closes the window.

@bpasero where is the code that shuts down the window in this case?

**Comment by bpasero** [comment]
@weinand 

https://github.com/microsoft/vscode/blob/b6a40fd71858a16a51b700e5798d26fbfd6c3ecf/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L611

**Comment by connor4312** [comment]
I've not seen this or received other reports of it. Closing for cleanup.

**Comment by connor4312** [comment]
May have been https://github.com/microsoft/vscode-js-debug/commit/1b25635b0ef3b7a3777dd8e9e28910cc01e46e68
