### ISSUE TITLE
blank terminal

### ISSUE THREAD

**Issue by Maheshwari9697** [microsoft/vscode#101926]
Issue Type: <b>Bug</b>

blank terminal command line

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 6.0.6001

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>Extensions: none

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal

**Comment by wraiford** [comment]
Hi @Tyriar, I was going to post another issue but there are already so many open terminal issues. I would infer from there being so many issues recently posted involving the terminal that the vscode team is aware of problems with the terminal and the most recent update. For me personally, it now starts the debugger every time an intermediate npm script executes a command line. For example, here is output of the debugger starting for a single `echo 'hello'` npm script:
```
> Executing task: npm run testvscode <

Debugger listening on ws://127.0.0.1:34089/6345ee2a-9fb1-4a7e-941a-3cdba463dded
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> ts-gib@0.1.13 testvscode /home/wraiford/ibgib/impl/typescript/core
> echo 'hello'

hello
Waiting for the debugger to disconnect...

Terminal will be reused by tasks, press any key to close it.
```

And here is output from a more complex npm script:

```
> Executing task: npm run pack:node <

Debugger listening on ws://127.0.0.1:44945/0d5b40f2-d712-48e5-9ab8-d8a2c1b127b2
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> ts-gib@0.1.13 pack:node /home/wraiford/ibgib/impl/typescript/core
> npm version patch && npm run build:node && npm pack

Debugger listening on ws://127.0.0.1:36707/cac882a2-f231-43f1-ad6f-6f2e71dabbef
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
v0.1.14
Waiting for the debugger to disconnect...
Debugger listening on ws://127.0.0.1:44141/48802d44-a34d-49d2-83c5-13ad41466db1
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> ts-gib@0.1.14 prebuild:node /home/wraiford/ibgib/impl/typescript/core
> ./set_target.sh node && npm run clean

TARGET is: node
[bunch of task-specific output]...
Setting target to node COMPLETE.

Debugger listening on ws://127.0.0.1:43481/d66f0ed7-51ff-44dd-9317-e67527e64a00
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> ts-gib@0.1.14 clean /home/wraiford/ibgib/impl/typescript/core
> rm -rf ./dist

Waiting for the debugger to disconnect...

> ts-gib@0.1.14 build:node /home/wraiford/ibgib/impl/typescript/core
> tsc -b tsconfig.node.json

Debugger listening on ws://127.0.0.1:42419/139a39ae-0007-48e3-a87b-728b670f9c58
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Debugger listening on ws://127.0.0.1:42845/ddbf6e6b-e564-4d37-9536-b67ed06a8304
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

npm notice 
npm notice 📦  ts-gib@0.1.14
npm notice === Tarball Contents === 
[bunch of npm pack output...]
npm notice total files:   52                                      
npm notice 
ts-gib-0.1.14.tgz

Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...

Terminal will be reused by tasks, press any key to close it.
```

So have you indeed noted the large number of terminal issues and is there one of them that is the "main" terminal issue that you are working on?

**Comment by Tyriar** [comment]
@wraiford looks like you're impacted by change to auto attach, this is getting disabled in 1.47.2 that will go out in a few days
