### ISSUE TITLE
JS Scafolding doesnt work in HTML

### ISSUE THREAD

**Issue by vbbalaji** [microsoft/vscode#101935]
- VSCode Version: 1.46
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:
1. Open a .js file and type any standard function for e.g. setTimeout. 
2. When you tab out or press enter, VS Code creates a neat scafolding for that function
3. Now open a HTML file and do the same within <script></script> section. There is no scafolding.

Im guessing this is to do with the same issue I reported earlier about VS Code not realizing the change between css/html/js section within .html page. If it is, apologize for the duplicate issue.

**Comment by aeschli** [comment]
You are talking about the `setTimeout` JavaScript code snippet. 
This works for me:
![image](https://user-images.githubusercontent.com/6461412/87010415-d20d6500-c1c6-11ea-9f10-f32d4adc2ef7.png)

Can you provide reproducible steps with a small sample code?
Also check in your settings if you have snippets enabled.

**Comment by vbbalaji** [comment]
Here is my screenshot from within a HTML and a JS file.
![image](https://user-images.githubusercontent.com/26417800/87043723-80afa680-c1c3-11ea-8677-882bc67acd04.png)

From within JS
![image](https://user-images.githubusercontent.com/26417800/87043999-ebf97880-c1c3-11ea-91e2-9630f353ec80.png)

**Comment by jrieken** [comment]
screen shot doesn't count, please provide the requested information

**Comment by vbbalaji** [comment]
![image](https://user-images.githubusercontent.com/26417800/87045230-a5a51900-c1c5-11ea-8a4d-71ce9d16a1c8.png)

**Comment by vbbalaji** [comment]
![image](https://user-images.githubusercontent.com/26417800/87045394-d5ecb780-c1c5-11ea-9336-3f3a99dde178.png)

**Comment by jrieken** [comment]
Please share a small _code_ sample that allows us to reproduce this

**Comment by vbbalaji** [comment]
I saved a test.html with below code.

`<link rel="stylesheet" type="text/css" href="fonts/css/all.min.css">    
<body>
    <div class=''>
        <div class=' px-0 border-bottom mb-0'>
            <div class='text-right'></div>
            <div class='text-right'>
                <span class='btn'></span>
                <a href='#' class='btn btn-xs bg-light-red'><i class='fas fa-fire-alt fa-1-5x'></i></a>
                <a href='#' class='btn btn-xs bg-light-red'><i class='fas fa-egg fa-1-5x'></a>
            </div>
        </div>
    </div>
</body>
<script>
    function testing(){
        
    }
</script>
`

Now when I type settimeout I only see the function name on the snippet but not the scafolding.

**Comment by jrieken** [comment]
works for me with that snippet

**Comment by jrieken** [comment]
What language is reported when during "f1 > inspect editor tokens and scopes". It should be javascript, like so

<img width="500" alt="Screenshot 2020-07-09 at 17 29 04" src="https://user-images.githubusercontent.com/1794099/87059529-b11a3380-c209-11ea-8a96-57efe730498e.png">

**Comment by vbbalaji** [comment]
![image](https://user-images.githubusercontent.com/26417800/87059818-c0808900-c1d7-11ea-93ab-cf7d972e0085.png)

I can see its not showing javascript. How do I change that?

**Comment by jrieken** [comment]
@aeschli Is that theme dependent?

**Comment by aeschli** [comment]
`source.js` is the scope that should signal that this embedded JavaScript.
The vscode-textmate library runs a grammar against a document and computes both styles and language. So there's a relationship.
But I don't see this with the Dark+
![image](https://user-images.githubusercontent.com/6461412/87065238-132a6700-c211-11ea-9c32-4fb577e3fe27.png)

@vbbalaji  Do you have any other extensions installed that maybe replaces the html grammar? Can you run with all extensions disabled?

**Comment by vbbalaji** [comment]
Yes! By IT had installed these and once I disabled all of them, it worked! Dont know which one was the culprit tho.
![image](https://user-images.githubusercontent.com/26417800/87066716-01c96680-c1e1-11ea-9cd2-07764df5f90d.png)

After disabling I can see the scafolding!!
![image](https://user-images.githubusercontent.com/26417800/87066782-1d347180-c1e1-11ea-8bcc-43381c81221f.png)
