### ISSUE TITLE
replacing in selection

### ISSUE THREAD

**Issue by dpiow** [microsoft/vscode#101907]
Issue Type: <b>Bug</b>

When replacing the search box is automatically filled with a selected string, but if click 'in selection' and change the search string it can't find any (but it is definitely present in a selected text), if de-click 'in selection' then it de-selects the text to search in.

Expected: Select text, click 'replace', update search string, click 'in selection' - replace the search string with the replacement string in the selection

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
@dpiow I assume you mean the Search/Replace in the editor? Not the global?

**Comment by dpiow** [comment]
@bpasero  Yes, local Search/Replace in the editor. Here are the correct steps to see the behavior:

1. without any text selected hit Ctrl-H 
2. choose 'Find in selection'
3. select some text in the editor
4. enter some string in Search field

Search happens across entire file, ignoring previously selected text

Also it can bee seen if text is selected, open Replace form, update search string and hit 'Find in selection' - then original selection is discarded and focus goes to next the next row in the editor with updated search string highlighted, but no any other data can be found in open file anymore.

Example: the text is 
```
abc
bca
```
select abc, hit Ctrl-H, change abc in Search to just b, hit 'Find in selection', change abc in Search to just a - no 'a' can be found in the text

**Comment by rebornix** [comment]
Find in selection needs to be toggled before selection, instead of *after*.
