### ISSUE TITLE
Color theming for notebook not working

### ISSUE THREAD

**Issue by Silfalion** [microsoft/vscode#101987]
- VSCode Version: 1.47
- OS Version: Windows 10

Steps to Reproduce:

1.Go to settings.json
2.Create a "workbench.colorCustomizations" tage
3.Add "notebook.cellBorderColor": "#ff0000", to change the color

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by misolori** [comment]
@Silfalion Which notebook are you using and what version of VS Code? Can you also please provide a screenshot?

**Comment by Silfalion** [comment]
For vscode I'm using the latest insider version.

Here are the screenshots:

Jupyter versions:
![image](https://user-images.githubusercontent.com/23188369/87047604-a3a57f00-c1f2-11ea-9000-1e9ff79c4af9.png)

Notebook interface:
![Screenshot (31)](https://user-images.githubusercontent.com/23188369/87047722-c2a41100-c1f2-11ea-9aab-6f190dacd307.png)

Settings.json:
![Screenshot (32)](https://user-images.githubusercontent.com/23188369/87047732-c46dd480-c1f2-11ea-8325-fea029fd93c5.png)

**Comment by misolori** [comment]
The color tokens you’re trying to use are for the native notebooks, which the Python extension hasn’t adopted yet. You can try using the GitHub Issues Notebook to see this color token working.

**Comment by Silfalion** [comment]
Oh I see, hope they will soon. Thanks a lot for the clarification.

**Comment by misolori** [comment]
They working on the adoption right now, you'll notice a visible change, here's a comparison:

## Current
![image](https://user-images.githubusercontent.com/35271042/87077469-04738e00-c1d8-11ea-9fd7-9f208315ccc1.png)


## Native
![image](https://user-images.githubusercontent.com/35271042/87077516-17865e00-c1d8-11ea-9c76-fffbb36ccf31.png)

**Comment by Silfalion** [comment]
Sick! Looks awesome, really looking forward to it.
