### ISSUE TITLE
Could not load 'markdown.styles' outside workspace

### ISSUE THREAD

**Issue by jonasreiher** [microsoft/vscode#101991]
- VSCode Version: 1.46.1
- OS Version: macOS 10.15.5

Steps to Reproduce:

1. Set path to custom markdown style sheet outside current workspace in settings (markdown.styles)
2. Preview a markdown file

VS Code then issues the warning `Could not load 'markdown.styles': /path/to/css`.
This works fine for style sheets inside the working directory, but I'd like to set a global stylesheet without having to copy it to every workspace.

Also, `Webview: Cannot load resource outside of protocol root` is issued in the developer tools console.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Closing this as by-design. We have this restriction for security reasons.

I think we could come up with a secure workaround but have not seen further user feedback on this issue
