### ISSUE TITLE
Notebook outline navigation does not preview the first few items

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#101941]
Issue Type: <b>Bug</b>

VS Code version: Code - OSS Dev 1.48.0 (Commit unknown, Date unknown)
OS version: Darwin x64 19.5.0

![outline](https://user-images.githubusercontent.com/876920/86953447-4eda0980-c109-11ea-817f-ad07d2a8fd67.gif)

While navigation through outline items, the first two items in above recording doesn't show preview background, https://github.com/microsoft/vscode/blob/4302a389e25f2486935124470c7b4eb4923bf4a6/src/vs/workbench/contrib/notebook/browser/contrib/toc/tocProvider.ts#L53 is not called for the first two items.

**Comment by jrieken** [comment]
The behaviour is now aligned with quick outline and there we don't preview the first element on start, only when re-selected. However, not highlighting the second item is wrong
