### ISSUE TITLE
Typescript debugging: quick watch hover doesn't work for expressions with optional chaining

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#101948]
Issue Type: <b>Bug</b>

Hovering over an expression like "parameterValues.parameterValuesProperty?.nameValue.span" does not show a value.  See attached movie.

[Bildschirmvideo aufnehmen 2020-07-08 um 12.41.07 PM.mov.zip](https://github.com/microsoft/vscode/files/4892892/Bildschirmvideo.aufnehmen.2020-07-08.um.12.41.07.PM.mov.zip
VS Code version: Code - Insiders 1.47.0-insider (376d9d9d785ccca128fdbb16f001446d0ad64d32, 2020-07-03T10:26:01.724Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|-psn_0_1450338|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
todo-tree|Gru|0.0.177
vscode-dotnet-runtime|ms-|0.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by weinand** [comment]
To make this work the Typescript extension needs to contribute an `EvaluatableExpressionProvider`.

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode/issues/18058
