### ISSUE TITLE
Source control tab doesn't update status automatically

### ISSUE THREAD

**Issue by busyengineer** [microsoft/vscode#101979]
The source control is not automatically updated when files are edited. But if I click "refresh" in the source control tab, all changes are displayed correctly and can be staged or commited.
The problem only seems to occur when the opened directory is mapped to a drive using `subst`. The project directory is `C:\Users\busyengineer\dev\project-abc\` and the part `C:\Users\busyengineer\dev\` is mapped to drive `X:\`.
If I open `X:\project-abc` in VS Code the problem occurs, but if I open `C:\Users\busyengineer\dev\project-abc\` everything works fine. Git commands in a terminal on drive `X:\` work as expected.

Steps to Reproduce:

1. Map a folder with `subst x: <path>`
1. Change drive to `X:\`
1. Create a new folder `md project-abc`
1. Change to this folder `cd project-abc`
1. Launch VS Code `code .`
1. Create a new file in VS Code -> source control won't update without hitting "refresh"

- VSCode Version:
Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

- OS Version:
Microsoft Windows [Version 10.0.17134.1550]

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/100274
