### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Prateek-web-boot** [microsoft/vscode#101943]
can you change comment section color back to grey from that greenish! It just not easy recognizable with all other code 
(PRETTIER EXTENSION)

**Comment by RMacfarlane** [comment]
@Prateek-web-boot Can you provide a screenshot of which color you're talking about?

**Comment by Prateek-web-boot** [comment]
darkgrey

**Comment by RMacfarlane** [comment]
Sorry, I meant, where in the UI does this color show up? Is this for code comments of a particular language? Or the comment gutter here?
![Screen Shot 2020-07-23 at 10 48 09 AM](https://user-images.githubusercontent.com/3672607/88320160-06f2df00-ccd2-11ea-9890-9a37b4ef9eb4.png)
Or something else?
