### ISSUE TITLE
Launch fails if launch config type is a platform-specific property

### ISSUE THREAD

**Issue by chausner** [microsoft/vscode#101931]
Issue Type: <b>Bug</b>

1. Create a simple C++ launch config using type `cppdbg`. Put the `type` attribute inside a platform-specific property as documented at https://code.visualstudio.com/docs/editor/debugging#_platformspecific-properties:
   ```json
   {
       "name": "test",
       "request": "launch",
       "linux": {
           "type": "cppdbg",            
           "program": "${workspaceFolder}/a.out",
       },            
       "args": [],
       "stopAtEntry": false,
       "cwd": "${workspaceFolder}",
       "environment": [],
       "externalConsole": false
   }
   ```

2. Attempt to launch the configuration. VS Code will not start the debugger but instead prompt the user to select an environment as if no configuration was selected.

Moving the `type` attribute outside of the `linux` block, or even simply specifying a bogus default `type` attribute that will get overridden by the platform-specific value fixes the issue:
```json
{
    "name": "test",
    "request": "launch",
    "type": "dummy",
    "linux": {
        "type": "cppdbg",            
        "program": "${workspaceFolder}/a.out",
    },            
    "args": [],
    "stopAtEntry": false,
    "cwd": "${workspaceFolder}",
    "environment": [],
    "externalConsole": false
}
```

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 4.15.0-109-generic

Extensions: none

**Comment by weinand** [comment]
The "type" property is needed before the platform is determined, because "type" determines the location (and therefore the platform).

This works as designed (but probably not as documented). I'll fix the doc.

**Comment by chausner** [comment]
> The "type" property is needed before the platform is determined, because "type" determines the location (and therefore the platform).
> 
> This works as designed (but probably not as documented). I'll fix the doc.

Thank you for your quick reply!

It seems strange to me that `type` is required in order to determine the operating system that VS Code is running on. Also, how come I can specify a dummy value as `type` and VS Code still correctly determines the platform and overrides `type` as intended? I am probably missing some details of how this works internally. In any case, I think extending the documentation about the fact that `type` needs to be specified (even a dummy value does the job) would be helpful.

**Comment by weinand** [comment]
if a debug extension is installed on a remote system, the type is associated with that system (and its platform/OS).

**Comment by chausner** [comment]
I see, then it makes sense. Thanks for clarifying.

**Comment by weinand** [comment]
@chausner I've added this note to the, doc:
https://github.com/microsoft/vscode-docs/commit/53f9b3b976d7c04791e7bf7009164bb5ccfd81b1

/cc @gregvanl fyi
