### ISSUE TITLE
Please provide a way to get bugs re-opened

### ISSUE THREAD

**Issue by rgov** [microsoft/vscode#101949]
I understand that there are thousands of bugs coming in and you can't spend a lot of time reviewing bugs over and over again, but perhaps a suitable process could be found. I have had two of the bugs I've filed closed, in my view, incorrectly, without response from the team when I requested that they be re-opened.

* #80129 - Blamed on an extension even though there is no evidence to suggest this. Refiled as #97780.
* #95356 - I replied within 6 minutes of being closed, but no further response.

If you close a bug because it is a duplicate, could you please reference the duplicate bug so this can be tracked? Otherwise it is impossible to judge whether the original captures the same issue or is perhaps subtly different.

**Comment by egamma** [comment]
In general the team reopens an issue when requested and when it makes sense.

I've looked into your issues I've reopened one of them and for the other you already created a new issue that is assigned.
