### ISSUE TITLE
The "default" is not localized under Extension->C/C++ node in the setting (UI) 

### ISSUE THREAD

**Issue by Wanye1062271859** [microsoft/vscode#101972]
- VSCode Version: VSCode 1.46.1 

Steps to Reproduce:
1. Install VSCode
2. Install Language Extension Chinese(Simplified)
3. Open the Setting UI window
4. Search "Code folding" and expand the dropdown options

**Expected:**
The character "default" is localized
![image](https://user-images.githubusercontent.com/29274719/87000856-9f746400-c1e8-11ea-97d9-c96d85125e07.png)

**Comment by isidorn** [comment]
Verified via code review
