### ISSUE TITLE
Not opening all previous windows on startup. "window.restoreWindows": "all"

### ISSUE THREAD

**Issue by SvetoslavAsenov** [microsoft/vscode#101921]
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.0-6-amd64

Steps to Reproduce:
1. Open two separate windows of VS Code.
2. In both windows open some files or folders.
3. Close both windows.
4. Launch VS Code again.

I have in the settings "window.restoreWindows": "all", but still only one window is opening on startup.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
How do you close them exactly?

**Comment by SvetoslavAsenov** [comment]
Your question helped me to figure out the reason :) I close them by the cross on the window. 
But how do I need to close them to reopen the same windows next time?
