### ISSUE TITLE
java 代码问题

### ISSUE THREAD

**Issue by ljjlovely123** [microsoft/vscode#101965]
1、vscode打开java项目下方显示152的错误
2、点击去显示class没有导入，但过了有几秒的时间他会自动导入
3、错误数减少，但有强迫症的人就像把他点掉。下次打开依然如此

**Comment by jdneo** [comment]
@ljjlovely123 Are you using lombok in your project?

**Comment by bpasero** [comment]
I am closing this and ask you to report an issue in english next time.
