### ISSUE TITLE
Preference sync

### ISSUE THREAD

**Issue by KokosTech** [microsoft/vscode#101918]
Issue Type: <b>Bug</b>

Preference sync doesn't work on Arch Linux (Snap installation). When selected the program frezes and 3-5 seconds later it closes itself.

VS Code version: Code - Insiders 1.47.0-insider (04545fa88043fd10d1f3edefd26be1b8245b516f, 2020-07-02T05:34:14.274Z)
OS version: Linux x64 5.7.7-arch1-1 snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 3923)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.61GB (0.99GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by sandy081** [comment]
Can you please 
- Set log level to trace (`F1 > Set Log Level > Trace`) 
- Reproduce the issue
- Provide us the logs from here `View -> Open View… -> Log (Preferences Sync)`

**Comment by KokosTech** [comment]
Hi,
The problem was that it was set to permission 1000. After fixing that everything was fine.
