### ISSUE TITLE
TSServer crashes on sufficiently large projects

### ISSUE THREAD

**Issue by DonIsaac** [microsoft/vscode#101997]
Issue Type: <b>Bug</b>

Hello,
We are developing an enterprise-scale monorepo system. Upon opening one of our larger packages, TSServer exits with code 134.

```
[Info  - 13:32:11.241] Starting TS Server 
[Info  - 13:32:11.241] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 13:32:11.243] <syntax> Forking...
[Info  - 13:32:11.253] <syntax> Starting...
[Info  - 13:32:11.254] <semantic> Forking...
[Info  - 13:32:11.266] <semantic> Starting...
[Error  - 14:12:48.797] TSServer exited with code: 134
```

TSServer then tries to restart, resulting in this error over and over again.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (14.44GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.0
vscode-eslint|dba|2.1.6
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
todo-tree|Gru|0.0.178
svg|joc|1.3.5
docthis|joe|0.7.1
graphql-for-vscode|kum|1.15.3
powershell|ms-|2020.6.0
debugger-for-chrome|msj|4.12.8
vscode-jest|Ort|3.2.0
markdown-preview-enhanced|shd|0.5.12
vscodeintellicode|Vis|1.2.9
vim|vsc|1.14.5
markdown-all-in-one|yzh|3.1.0

</details>

**Comment by mjbvz** [comment]
Have you tried increasing the server's max memory by setting `typescript.tsserver.maxTsServerMemory`?

**Comment by mjbvz** [comment]
Also see https://code.visualstudio.com/docs/typescript/typescript-compiling#_working-with-large-projects

**Comment by ycjcl868** [comment]
+1

**Comment by DonIsaac** [comment]
@mjbvz I'll try out the `typescript.tsserver.maxTsServerMemory` setting and get back to you. Regarding the working with large projects section you linked, I believe we already take these steps. The typescript language server usually only crashes when I open up our largest package in our monorepo.

**Comment by mjbvz** [comment]
Closing this as we need more information to investigate this.

If you are still seeing this after checking those configuration options, are you able share an example project?
