### ISSUE TITLE
"Debug: Add to Watch" option has disappeared after the upgrade to version 1.4.0

### ISSUE THREAD

**Issue by petrlyapin** [Microsoft/vscode#10192]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Run any node.js app in the debug mode and stop on any break point
2. Select any variable and open right click menu for it
3. In the version prior 1.4.0 there was "Debug: Add to Watch" option which is now missing

It was very helpful to have that option, please return it back.

**Comment by isidorn** [comment]
Now it should work as before with one limitation, you are no longer able to use the context menu to add watch expressions while you are not in a debug session.
The reason for this is that we try to keep our context menus minimalistic so we had to cut some actions from it. Thus debug: add to watch will only be present while you are debugging
