### ISSUE TITLE
Increase discoverability of Alt-commands on menu buttons

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#101995]
Issue Type: <b>Feature Request</b>

When [contributing to menus](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) we can use the `alt` property to specify an alternative command that gets run if the Alt key is pressed.

For example the Split Editor button does this, but the feature is not easily discoverable.

I suggest adding a second line to the button tip (title attribute) that displays the text of the alt-command. For example:

![image](https://user-images.githubusercontent.com/6726799/87044184-195b1c00-c1ee-11ea-876b-1fe48d0fdfc3.png)

VS Code version: Code - Insiders 1.47.0-insider (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-08T10:52:52.439Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Another mockup example using a markdown document:

![image](https://user-images.githubusercontent.com/6726799/87044767-eb2a0c00-c1ee-11ea-8336-4afb563d20a6.png)

In this case the alternate command has a keybinding.

Or using an alternative to the square brackets:

![image](https://user-images.githubusercontent.com/6726799/87045118-68ee1780-c1ef-11ea-9f8d-18d3848ab822.png)

**Comment by gjsjohnmurray** [comment]
Another experiment:
![image](https://user-images.githubusercontent.com/6726799/87046942-bbc8ce80-c1f1-11ea-8096-d1d32916d1c8.png)

**Comment by sbatten** [comment]
I like this idea, adding to backlog to explore.

**Comment by gjsjohnmurray** [comment]
This shipped in 1.55
