### ISSUE TITLE
workspace加载多个django项目launch.json参数无效

### ISSUE THREAD

**Issue by Z-Yishion** [microsoft/vscode#101973]
Issue Type: <b>Bug</b>

use workspace 配置多个django项目时  launch.json配置无效  例如port：80  还是全部使用默认的8000  so  

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
I am closing this and ask you to report an issue in english next time.
