### ISSUE TITLE
Editor split button bait and switch on hover

### ISSUE THREAD

**Issue by Chuckatron** [microsoft/vscode#101993]
- VSCode Version: 1.47.0-insider
- OS Version: Ubuntu Linux x64 5.3.0-62-generic

Steps to Reproduce:

1. Sometimes, when hovering over the editor split button, it switches orientation. It's extremely random and I've never been able to find a pattern. The only reproduction step I can offer is "Move mouse over editor splitter button, observe that sometimes the splitter switches orientation on hover"
2. See: https://youtu.be/D1w-6KSkqWE

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
On my Windows platform it changes if I have the Alt key down when I mouse over the button, or if I press Alt down while hovering there. This is intentional. Clicking the button with Alt down will split vertically instead of horizontally.

**Comment by Chuckatron** [comment]
Yes, the Alt behaviour works perfectly. This bug is reporting the case where it switches when I hover with nothing held down.

**Comment by gjsjohnmurray** [comment]
If you click it in that case, does it split down rather than across? In other words, does it fire the alt-command, or is it only showing the alt-icon?

**Comment by Chuckatron** [comment]
It fires the alt-command. If it didn't, I could ignore it, but so many times a day I end up splitting the wrong way :-)

**Comment by bpasero** [comment]
I think something is wrong with your setup then where somehow the `Alt` key is pressed even though you did not press it. Closing as I see no obvious bug in VSCode, but we can reopen if you find steps for me to reproduce.
