### ISSUE TITLE
Regarding Terminal 

### ISSUE THREAD

**Issue by rasheedazhar** [microsoft/vscode#101906]
Issue Type: <b>Bug</b>

Hi I found something.
After clearing terminal if I click on timeline the terminal data which was cleared comes back in terminal.
tried multiple times, same thing happens.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.90GB (7.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|4.2.0

</details>

**Comment by gjsjohnmurray** [comment]
Please confirm that you are talking about the contents of the TERMINAL tab on the Panel, and not the Git view of the OUTPUT tab.

Screenshot might help us understand what you mean. Paste from clipboard directly into GitHub textarea.
