### ISSUE TITLE
Only disable eslint rules for strong reasons

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#101978]
Searching for `disable-eslint` in TypeScript files (ignore test files) yields the list below. We should try to avoid this and only have justified exemptions, e.g put a doc comment why a rule is ignored 

- [x] extensions/git/src/commands.ts @eamodio
- [x] extensions/git/src/git.ts
- [x] extensions/github-browser/src/iterables.ts
- [x] src/vs/workbench/api/common/extHostTimeline.ts
- [x] src/vs/workbench/contrib/timeline/browser/timelinePane.ts
- [x] extensions/typescript-language-features/src/typescriptServiceClient.ts @mjbvz
- [x] src/vs/vscode.proposed.d.ts @isidorn 
- [x] src/vs/base/common/uri.ts @jrieken
- [x] src/vs/platform/contextkey/common/contextkey.ts @alexdima
- [x] src/vs/platform/sign/node/signService.ts @weinand 
- [x] src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts @roblourens
- [x] src/vs/workbench/contrib/terminal/browser/terminalService.ts @Tyriar

**Comment by chrmarti** [comment]
@weinand Reassigning to you for `signService.ts`.
