### ISSUE TITLE
some issue is troubling

### ISSUE THREAD

**Issue by yatisingh** [microsoft/vscode#101915]
Issue Type: <b>Feature Request</b>

hey i have created a folder on my desktop and i opened the file option at the top on the left side of the screen on visual studio code and in the dropdown menu i clicked on the open folder but there i could not find the option of desktop so could you please help me out and tell me what's the problem. 

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 6.1.7601

**Comment by gjsjohnmurray** [comment]
Does "Open Folder..." give you the standard Windows file dialog? If not, you probably have this setting:

```
"files.simpleDialog.enable": true
```
