### ISSUE TITLE
`strictNullChecks: true` breaks imports of non-typescript modules.

### ISSUE THREAD

**Issue by RickCarlino** [Microsoft/vscode#10199]
I posted this one to [StackOverflow](http://stackoverflow.com/questions/38778126/upgraded-to-tsc-2-0-0-node-modules-arent-resolved-by-vs-code-syntax-checker) already with a screenshot.

I am able to "solve" the problem by removing `strictNullChecks` from my `tsconfig.json`, although I really really want to use that feature.

Is this a bug? Misconfiguration on my end?

Thanks. Keep up the great work on VS Code.

**Comment by dbaeumer** [comment]
`strictNullChecks` is a TS 2.0 feature. By default VS Code ships the the official 1.8.10 (2.0 is still in beta). If you want to use 2.0 install it locally using npm install typescript@next and use the `"typescript.tsdk": "./node_modules/typescript/lib"` to tell VS Code to use the 2.0 version.
