### ISSUE TITLE
Setting a breakpoint when multiple debug sessions are present not working properly

### ISSUE THREAD

**Issue by quoctruong** [microsoft/vscode#101945]
- VSCode Version: 1.46.1
- OS Version: Windows_NT x64 10.0.16299

Steps to Reproduce:

My extension launches 2 debug sessions for the same folder.

Let's say `frontend` session for `src/frontend` and `backend` session for `src/backend`.

When I select the `frontend` session from the debug control dropdown and sets a breakpoint, it seems that the breakpoint request is sent to the `backend` session as well. I think this is a bug because it should only be sent to the `frontend` session?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
no, breakpoints are sent to all sessions.
