### ISSUE TITLE
Environment variables are not being defined while debugging

### ISSUE THREAD

**Issue by brennanMKE** [Microsoft/vscode#102]
I use VS Code to start a debugging session and in the configuration I define a value for PORT yet it is always undefined. I cannot seem to access these environment variables. Is there another way to access these environment variables?

`var port = process.env.PORT || 8001;`

Below is the launch.json that I am using for a sample project to try to access environment variables. I'd like to be able to use launch configurations to create multiple configurations with different environment variables.

```
{
	"version": "0.1.0",
	// List of configurations. Add new configurations or edit existing ones.
	"configurations": [
		{
			// Name of configuration; appears in the launch configuration drop down menu.
			"name": "Launch server.js",
			// Type of configuration.
			"type": "node",
			// Workspace relative or absolute path to the program.
			"program": "server.js",
			// Automatically stop program after launch.
			"stopOnEntry": false,
			// Command line arguments passed to the program.
			"args": [],
			// Workspace relative or absolute path to the working directory of the program being debugged. Default is the current workspace.
			"cwd": ".",
			// Workspace relative or absolute path to the runtime executable to be used. Default is the runtime executable on the PATH.
			"runtimeExecutable": null,
			// Optional arguments passed to the runtime executable.
			"runtimeArgs": ["--nolazy"],
			// Environment variables passed to the program.
			"env": {
				"NODE_ENV": "development",
				"PORT" : 8005
			},
			// Use JavaScript source maps (if they exist).
			"sourceMaps": false,
			// If JavaScript source maps are enabled, the generated code is expected in this directory.
			"outDir": null
		},
		{
			"name": "Attach",
			"type": "node",
			// TCP/IP address. Default is "localhost".
			"address": "localhost",
			// Port to attach to.
			"port": 5858,
			"sourceMaps": false
		}
	]
}
```

**Comment by weinand** [comment]
The "env" attribute is a dictionary of **strings**. Please pass the PORT number as a string and not as a number.
We will try to improve the schema for "env" so that your case will be flagged as an error.

**Comment by brennanMKE** [comment]
Thanks. I saw lower in the launch config that there was another port value which is a number and was copying that instance. Is it possible to define these as numbers?

**Comment by montera82** [comment]
Any update per this issue, i am getting undefined for my environment variables while in debug mode

**Comment by weinand** [comment]
@montera82 the issue discussed here was a 'user error' and might only be related to your problem if you are using non-string typed values in the "env" section of your launch configuration. If this is the case please fix it as discussed above.

If you have a different problem, please create a new issue with the detailed steps and infor about your OS and node version.

**Comment by montera82** [comment]
hi @weinand , 
i need to know how to source my environment variables when on debug mode.

All my environment variables are stored in a file in my root folder named .env ( which has an entry like so 
export DATABASE_HOST=127.0.0.1
)

Now when running the project from command line, i can do 

Source .env

Then run

npm start

and the project will be able to resolve the variables.

How do i achieve the same when running same project on debug mode.

Thanks

**Comment by weinand** [comment]
@montera82 you probably have already a launch.json that has a environment variable:
```
"env": {
    "NODE_ENV": "development"
},
```

Just add your environment variables to that like this:

```
"env": {
    "NODE_ENV": "development",
    "DATABASE_HOST": "127.0.0.1"
    // more env vars
},
```

Make sure that all env var values are strings.

You can find debugging help here: https://code.visualstudio.com/docs/editor/debugging

**Comment by montera82** [comment]
Works well, thanks

someone will need to add this on the getting started article, i could not find there.

**Comment by Dewb** [comment]
Is there any other route for defining runtime env-vars other than the tasks.json file? For example, something that would be suitable for secrets that shouldn't be in source control?
