### ISSUE TITLE
Terminal closing when i start it

### ISSUE THREAD

**Issue by aharay** [microsoft/vscode#102010]
- VSCode Version: Dont know just installed today
- OS Version: Windows 10

Steps to Reproduce:

1.View terminal
2. Crashes within seconds

Does this issue occur when all extensions are disabled?: Yes

**Comment by aharay** [comment]
im sorry if this is a bit un professional but im new to coding and dont know why this is happening

**Comment by aharay** [comment]
if it gives you anymore info my terminal is running om cmd

**Comment by Tyriar** [comment]
Can you try installing 1.47 (just went out yesterday), you should get a notification with a help message to follow.

**Comment by aharay** [comment]
already updated

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal

**Comment by aharay** [comment]
ok i made a imagur link https://imgur.com/a/MUOV8oR

**Comment by Tyriar** [comment]
@aharay nothing seems to happen in the link, does your recorder have a delay before it starts and it was missed maybe?

**Comment by aharay** [comment]
one moment

**Comment by aharay** [comment]
your right lemme fix this

**Comment by aharay** [comment]
im uploding a video this time

**Comment by aharay** [comment]
https://imgur.com/PoBASoP here

**Comment by thiagozanetti** [comment]
This is also happening to me and when I open `code` with the `--verbose` flag and I try to open a new terminal window, this is what I get:

`ERROR:gles2_cmd_decoder.cc(4927)] [.RendererMainThread-0x31aff8941700]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete`

**Comment by Tyriar** [comment]
@aharay can you share your settings.json file?

**Comment by aharay** [comment]
https://mega.nz/file/TYkFTAxQ#pZ4W4VrN5hm_CUaGee-ffWm92oKHM7J8Y16Ezmjh7Rs
Heres the settings.json file

**Comment by thiagozanetti** [comment]
With some further inspection I discovered it is related to my zsh/oh-my-zsh configuration. I'll try to narrow it down a bit more.

**Comment by aharay** [comment]
anyone find a fix for this issue?

**Comment by aharay** [comment]
this issue has been hindering me coding for weeks now anyone come op with a fix?

**Comment by Tyriar** [comment]
@aharay please do a trace log when you open the terminal https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging, this should hopefully tell us how the terminal was launched and why it was closed.
