### ISSUE TITLE
[MacOS] Crash when adding New Window Tab in Full Screen mode (Native Tabs)

### ISSUE THREAD

**Issue by bsdahl** [microsoft/vscode#102046]
- VSCode Version: 1.47.0
- OS Version: MacOS Catalina 10.15.5

Steps to Reproduce:

1. Enable Window: Native Tabs `"window.nativeTabs": true`
2. Enter Full Screen mode by clicking green button in top left corner
3. Add new Window Tab from Window > New Tab menu, or from command palette "New Window Tab"

Visual Studio Code will crash every time.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I cannot reproduce, but it would help if we could get the crash dump.

Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by bsdahl** [comment]
@bpasero @deepak1556 I am using VSCode Version 1.47.0 which is running Electron 7.3.2. When I followed the link to https://github.com/deepak1556/minidump-stackwalk-prebuilt/releases, I do not see a release for 7.3.2.

I downloaded 7.3.1 anyway, and gave it a try.

I ran:

`$~/Downloads/minidump_stackwalk -s ~/crash/VSCode\ Crashes/pending/97bed5f1-669b-42d3-992d-45ee307f0199.dmp ~/Downloads/symbols symolicated_stack.txt`

And after a long output I received this error message:

`0x7fff71e8d000 - 0x7fff71ec2fff  libxpc.dylib  1738.120.8.0  (WARNING: No symbols, libxpc.dylib, 68D433B6DCFF385D8620F847FB7D4A5A0)`

What should I do next?

Here is the full about VS Code output

```
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bsdahl** [comment]
@bpasero Okay, I was able to reproduce using the insiders build. I also have a crash dump file, but I don't know how to generate the crash details using minidump.

Also, I have some additional context. I can only reproduce the crash, if I have more than one project window that is restored when opening Visual Studio Code. It doesn't crash if I start from a single project, or a new window. 

This is a common workflow that I use everyday.
1. Open Visual Studio Code, (Several project windows are restored)
2. From the command palette, run Merge all Windows

Then, any time after merging the windows, go to full screen, and run New Window Tab. Code will crash.

**Comment by bpasero** [comment]
@bsdahl feel free to send the dump to me, even mail is fine. I still cannot reproduce (tried with the "Merge all Windows").

**Comment by bsdahl** [comment]
@bpasero Just sent you an email. Thanks for taking a look!

**Comment by bpasero** [comment]
@bsdahl I did not receive anything yet, can you maybe upload to some shared web drive?

**Comment by bsdahl** [comment]
@bpasero Try this link: https://drive.google.com/file/d/1f1brrJOSudyCV7sqYCd-iE1wwuFqjoPR/view?usp=sharing

**Comment by bpasero** [comment]
@deepak1556 tried to add symbols, cannot really help with the crash, maybe you have a clue:

[crash.txt](https://github.com/microsoft/vscode/files/4919951/crash.txt)

**Comment by bsdahl** [comment]
@deepak1556 is there any additional information I can provide?

**Comment by deepak1556** [comment]
sorry for the late reply,

>is there any additional information I can provide?

yes please, the current crash dumps doesn't symbolize properly for unknown reason. Can you generate a new crash dump using the following version https://az764295.vo.msecnd.net/insider/4cca93d6517d02af31e2e514772502a5ea8b4c58/VSCode-darwin-insider.zip

**Comment by bsdahl** [comment]
@deepak1556 thanks for taking a look. I was able to reproduce the crash again using the link you provided. Attached is the crash dump. I also tried symbolizing the dump myself using minidump. I left the output next to the dmp file.

`electron-minidump -f 5fc9f6ba-86ed-41e7-a42c-eff6eb7370d5.dmp -v 9.1.0 -p darwin -a x64`

https://drive.google.com/file/d/1XQRi_POuea2m-XdUU3mQ24EE6tuDFjaQ/view?usp=sharing

**Comment by bsdahl** [comment]
By the way, I tested it again today, and I'm still experiencing the same crash.

I'm now on:
```
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by deepak1556** [comment]
Unable to repro with latest stable, can reopen if the issue is still present.

**Comment by bsdahl** [comment]
@deepak1556 thank you, I can confirm that the issue has been resolved!
