### ISSUE TITLE
Extension Marketplace / WSL connection broken in 1.47

### ISSUE THREAD

**Issue by orgi** [microsoft/vscode#102024]
Issue Type: <b>Bug</b>

Some minutes ago code updated itself on two of my machines to the latest version. After that I see the same behavior on both of them:
* Extension Marketplace is not showing anything (seems to load forever)
* It can no longer connect to any of WSL installations (stuck while connecting)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (2.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
overtype|ada|0.2.0
jenkins-status|ale|4.1.0
pascal|ale|9.0.0
pascal-formatter|ale|2.2.0
project-manager|ale|11.1.0
syncify|arn|4.0.4
run-current-test|asv|0.2.0
code-gnu-global|aus|0.2.2
togglehs|bbe|0.1.2
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-mermaid|bie|1.5.1
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
Gradle|caz|1.1.2
npm-intellisense|chr|1.3.0
regex|chr|0.2.0
vscode-eslint|dba|2.1.6
vscode-instant-markdown|dba|1.4.4
githistory|don|0.6.5
xml|Dot|2.5.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
vscode-reveal|evi|4.0.3
code-runner|for|0.11.0
vscode-perl|hen|1.17.0
beautify|Hoo|1.5.0
innosetup|idl|1.4.0
reg|ion|1.0.1
jenkins-pipeline-linter-connector|jan|1.2.0
quicktask|lky|3.5.6
code-groovy|mar|0.1.2
Kotlin|mat|1.7.1
git-graph|mhu|1.24.0
perl-debug|mor|0.6.3
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
azure-account|ms-|0.8.11
cmake-tools|ms-|1.4.1
cpptools|ms-|0.28.3
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
gradle-language|nac|0.2.3
makefiles-support-for-vscode|nae|0.0.3
node-tdd|pra|0.2.4
qub-msbuild|qub|0.6.3
java|red|0.64.1
vscode-yaml|red|0.8.0
chai-spec-generator|rin|0.4.0
vscode-coverage-gutters|rya|2.5.1
todotasks|san|0.5.0
jenkinsfile-support|sec|0.1.0
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.9.0
html-preview-vscode|tht|0.2.5
markdown-jira-preview|tra|0.0.1
cmake|twx|0.0.17
shell-launcher|Tyr|0.4.1
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-maven|vsc|0.22.0
vsc-tasks|wal|0.9.0
markdown-pdf|yza|1.4.4
material-theme|zhu|3.8.3

(1 theme extensions excluded)

</details>

**Comment by orgi** [comment]
Just confirmed: After downgrading to 1.46.1 it is back to normal.

**Comment by liesauer** [comment]
same problem, btw when new a wsl window, node starts consuming tons of cpu and rams and keeps rising, downgrade to 1.46.1 still have this problem.
![image](https://user-images.githubusercontent.com/8676741/87224129-46a5f680-c3b5-11ea-9078-7f431bad5f67.png)

**Comment by sandy081** [comment]
/duplicate

#102082

**Comment by orgi** [comment]
@sandy081 Hope the WSL connection issue will be covered in the other ticket, too.
