### ISSUE TITLE
After changing Windows user folder name, VSCode fails to update

### ISSUE THREAD

**Issue by EmilyBonar** [microsoft/vscode#102039]
Issue Type: <b>Bug</b>

I changed the name of my user folder in Windows, following official instructions, including changing registry values. Now however, VSCode is trying to update using a folder that no longer exists, and fails. Please help me fix this.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
magic-racket|evz|0.5.6
code-runner|for|0.11.0
python|ms-|2020.6.91350
LiveServer|rit|5.6.1

</details>

**Comment by joaomoreno** [comment]
Please uninstall VS Code. If you can't, simply delete it. And then reinstall it.
