### ISSUE TITLE
Transform to snake_case

### ISSUE THREAD

**Issue by petsuter** [microsoft/vscode#102074]
VSCode already has the following very useful commands:

* Transform to Uppercase
* Transform to Lowercase
* Transform to Title Case

It would be very useful to also add a similar command to **"Transform to snake_case"** that transforms the selected text to lowercase after adding underscore characters between each lowercase / uppercase character pair.

For example it should transform the text `ExampleOne and Also ExampleTwo` to `example_one and also example_two`.

Maybe consider also adding other variations like "Transform to kebap-case" to adds dash characters instead of underscore characters. There are [many (currently 71 results for "snake case")  extensions](https://marketplace.visualstudio.com/search?term=snake%20case&target=VSCode&category=All%20categories&sortBy=Relevance)  providing this or similar functionality and other variations thereof.

**Comment by RootHouston** [comment]
I'd argue that this is something that could be useful in stuff like Python linters, but doesn't need to be built-in. Snake case is really something that is dependent upon language, and a lot of people don't work a language that makes heavy use of it.

One of the strong suits of VS Code is that it is leaner and customizable with lots of extensions. Building in too much generic functionality ends up with something bloated in the long run. We don't want that.

**Comment by a5hk** [comment]
@alexdima Would you accept a PR for this?
