### ISSUE TITLE
the new source control view is a nightmare on my notebook

### ISSUE THREAD

**Issue by isRight** [microsoft/vscode#102083]
the new source control view  make the edit view  and the changed file view more narrow
I need the old version

**Comment by gjsjohnmurray** [comment]
Please paste a screenshot to show what you mean.

**Comment by KaueReinbold** [comment]
On the top of Source Control, we had the possibility to change the way the files will be grouped. This options was right on the left of commit button and now it has disappeared.
![image](https://user-images.githubusercontent.com/22650820/87150321-2fb5b600-c288-11ea-9f04-d08019d3be09.png)

**Comment by KaueReinbold** [comment]
I think he is talking about the option to group files by folder which we had right on the left of commit button, now it has changed to View & Sort.
![image](https://user-images.githubusercontent.com/22650820/87150859-414b8d80-c289-11ea-8ad7-e87083d34503.png)

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/102138
