### ISSUE TITLE
File associations do not accept extensionless files

### ISSUE THREAD

**Issue by CedT83** [microsoft/vscode#102003]
When defining the associated language to a file it is impossible to define a default language or a language to be used for files not which the extension is not given. For example if a file is called "CONFIG_H" I cannot tell VS code to treat it as C code because the file has no extension. 

Why didn't I add an extension? Because it's a professional project hance I can't choose. Also, just get a full glob support in the first place

**Comment by tristan957** [comment]
@CedT83 your issue can be solved by literally saying

```json
"files.associations": {
  "CONFIG_H": "c"
}
```

I do the same for other types of files. The keys in "files.associations" are just basic glob patterns.
