### ISSUE TITLE
VSCode “educational video” format

### ISSUE THREAD

**Issue by eslessons** [microsoft/vscode#102070]
**You** may have already noticed that ~80% of all educational programming language videos are done inside one IDE and/or internet browser (console). 

 **The** size (in GB) of each of this video courses is increasing every day.

 **Wouldn’t** it be nice to give people a new ‘pseudo video’ format based on VSCode IDE. 

**Instead** of spending huge amount of resources recording video, Author opens VSCode, connects his/her microphone and starts programming. 
VSCode saves all his actions in some kind of text format and archive it together with audio file(s). 

**Client** receives one or several archives with size slightly bigger than size of audio track from the same course in original video format. Opens this file(s) inside VSCode. And receives the ability to immediately experiment with author’s code (sandbox feature). 

**Thank you** for your attention.

**Comment by bpasero** [comment]
Maybe https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour helps.
