### ISSUE TITLE
Opening source provider tab freezes on multi folder workspace

### ISSUE THREAD

**Issue by mnunezdm** [microsoft/vscode#102078]
Issue Type: <b>Bug</b>

I have a workspace with 50+ folders. When opening the SCM tab for the first time the window freezes for about 1 min

Then the functionality is correct

I'm currently using the WSL2

![errorSCM](https://user-images.githubusercontent.com/10410852/87132889-cee1aa00-c296-11ea-9beb-6d71493b780e.gif)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (2.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3695)|
|Memory (System)|5.81GB (1.53GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
lit-html|bie|1.11.1
vscode-eslint|dba|2.1.6
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
json-tools|eri|1.0.2
prettier-vscode|esb|5.1.3
vscode-peacock|joh|3.7.2
chat|kar|0.35.0
git-graph|mhu|1.24.0
vscode-autoprefixer|mrm|3.0.1
vsliveshare|ms-|1.0.2427
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
vscode-xml|red|0.13.0
salesforce-vscode-slds|sal|1.1.0
vscode-peacock|joh|3.7.2
vscode-docker|ms-|1.3.1
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.9
material-icon-theme|PKi|4.2.0
material-theme|zhu|3.8.3

</details>

**Comment by joaomoreno** [comment]
To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* reproduce the issue
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by mnunezdm** [comment]
Hello joao, sorry for the delay in the response, I was on vacation and could not reproduce it until now.

I tried running the profiling:

- After running for 130 seconds of having a "blank screen" all the repo appears
- After 180 seconds, the windows starts to respond but with a huge delay
- After 220 seconds, the window starts to work as expected, with some delay but I think is due to the profiling


[Profile-20200722T004648.zip](https://github.com/microsoft/vscode/files/4956794/Profile-20200722T004648.zip)

**Comment by joaomoreno** [comment]
Thanks for the profile!

**Comment by joaomoreno** [comment]
OK the current fix should've improved the perf here considerably.

Once this is out in Insiders, can you give it a try @mnunezdm? Thanks!

**Comment by roblourens** [comment]
I do get a ton of possible leak warning spam when I open a workspace with many folders that have git repos. I won't open an issue for it, because these are often false positives, unless you want one @joaomoreno 

![image](https://user-images.githubusercontent.com/323878/92058999-e728ef00-ed44-11ea-9873-a5127b4996ec.png)
