### ISSUE TITLE
Color coding of TypeScript is broken when using : in @HostListener eventName

### ISSUE THREAD

**Issue by jkyoutsey** [Microsoft/vscode#10205]
- VSCode Version: 1.4.0
- OS Version: Windows 8.1

Color coding of TypeScript is broken when using `:` in `@HostListener` eventName

Steps to Reproduce:
```typescript
    @HostListener("document:click", ["$event"])
    private ...(e) {
        ...
    }
```
![image](https://cloud.githubusercontent.com/assets/3846466/17441725/b08fe49e-5aef-11e6-934b-fd46918e1c7b.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#238
