### ISSUE TITLE
I cant open the Terminal

### ISSUE THREAD

**Issue by rafaelortegar** [microsoft/vscode#102060]
i just try to open the terminal, but in less than one second it is closed, it shows some text that i cant read because of the speed of the closing.

**Comment by SaumitraVerma** [comment]
How are you opening the terminal???

**Comment by rafaelortegar** [comment]
Hello SaumitraVerma , what i am doing is:

Terminal menu --> New Terminal

**Comment by rafaelortegar** [comment]
I am using VS Code on Ubuntu 20.04 LTS, 64 bits  and GNOME version 3.36.2

**Comment by rafaelortegar** [comment]
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-40-generic snap

**Comment by Tyriar** [comment]
Can you update to 1.47 and try again.

**Comment by rafaelortegar** [comment]
I found the problem, the thing is that I am using ZSH with my Terminal, and I have PyEnv on it.

with the installation of PyEnv, I had to put this lines on .zshrc:

#PyEnv Confirguration
# Load pyenv automatically by adding
# the following to ~/.bashrc:

export PATH="/home/rafaelortega/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

so my terminal detects PyEnv.

If I erase that lines, the terminal in Visual Studio works perfectly.

Do you know hoy to use Terminal from VS Code with PyEnv?

**Comment by ticokazuya** [comment]
Reinstala
