### ISSUE TITLE
Regression: SCM - Show changes in tree-like format

### ISSUE THREAD

**Issue by MrCroft** [microsoft/vscode#102068]
- VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
- OS version: Windows_NT x64 10.0.19042
- Remote OS version: Linux x64 4.19.84-microsoft-standard

In the Source control panel, the button/icon to toggle the view mode is missing since today's update (version 1.47). There is no posibility to switch to tree view.
This is also an issue on the latest Insiders build (1.47.0-insider). I've actually started seeing this from a couple of weeks on the Insiders build, but didn't report it because a lot of times I'd see strange behavior in the Insiders build which never made it to the stable build.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
See https://github.com/microsoft/vscode/issues/102041#issuecomment-656401718
