### ISSUE TITLE
Twitching after saving html file

### ISSUE THREAD

**Issue by today-** [Microsoft/vscode#10200]
- VSCode Version: Code - Insiders 1.5.0-insider (1a7ca5a77bf6b63951e499ea93b7316d36118ade, 2016-08-05T07:19:53.669Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Open html file
2. Make any changes
3. Save (Ctrl+S)

It stops after swicthing to another tab. But sometimes, the contents of html files pasting to that new tab.
The problem doesn't appear when I save another filetype (.ts for example)

Screencast, showing this problem
http://recordit.co/o7A1jEJWES

**Comment by Belar** [comment]
Do you use VSCodeBeautify (by HookyQR) plugin by any chance? I have had similar issue after recent (yesterday) update to 1.4.0 and removing the plugin solved it.  

Try running Code with `--disable-extensions` flag and see if problem is still there. If not, it's a  faulty plugin.

**Comment by today-** [comment]
You're right, @Belar, the problem was in extension, this:
https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter
It works well in previous version (1.4.0). but cause such buggy behaviuor after VSCode update to 1.5.0-insider

**Comment by Belar** [comment]
Happens for me on 1.4.0, there was no problem with 1.3.x, but going back won't solve the problem. 

From what I have tasted it happens with all files which are being formatted on save. VSCode falls into endless loop in [applyEdits](https://github.com/Microsoft/vscode/blob/b4937be487b82bff4f1c85cb9027ba4e0d5067e2/src/vs/workbench/api/node/mainThreadEditorsTracker.ts#L317) function, warning:

> Model has changed in the meantime!

**Comment by jrieken** [comment]
@bpasero Did we change anything in that area such that a model receives another update from us on save? That would explain why model versions don't match anymore

**Comment by bpasero** [comment]
In 1.4.0 I was on vacation and did not change anything in this area to my knowledge...

**Comment by jrieken** [comment]
So, from looking at the extension it seems that it modifies the document of the [active editor](https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/blob/master/src/extension.ts#L275) when any document is being changed. That means, have a dirty and saved html file, focus the saved on, hit save all, the active editor receives the format edits
