### ISSUE TITLE
F#: // in block comment highlights rest of file as comment

### ISSUE THREAD

**Issue by tkovacs-dev** [microsoft/vscode#102005]
- VSCode Version: 1.46.1
- OS Version: Windows 10 (18363.900)

Steps to Reproduce:

1. create a new file
2. change language mode to F#
3. type `(* comment// *) "not a comment"`
4. you get this
![image](https://user-images.githubusercontent.com/1266403/87056999-a316e380-c206-11ea-9695-b17552839175.png)
5. the correct higlighting is something like this (one slash removed to fix highlighting)
![image](https://user-images.githubusercontent.com/1266403/87057164-d22d5500-c206-11ea-84d7-76f78d2a8787.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Moved to owning repo: https://github.com/ionide/ionide-fsgrammar/issues/155

**Comment by alexr00** [comment]
Closing in favor of the upstream issue.
