### ISSUE TITLE
Extension 'ms-vscode.vscode-github-issue-notebooks cannot use PROPOSED API

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#102012]
Issue Type: <b>Bug</b>

**repro**
1. Install github issues notebook in stable (I know we say it only works in insiders but the extension is installable and is recommended by the VS Code repo)

**Bug**
In the dev console, see the errors:
```
vscode.vscode-github-issue-notebooks cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)

abstractExtensionService.ts:411 [ms-vscode.vscode-github-issue-notebooks]: notebook/cell/title is a proposed menu identifier and is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-vscode.vscode-github-issue-notebooks
```

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.04GB (3.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by jrieken** [comment]
Proposed API only works in stable, the extension is also pretty clear about it: https://github.com/microsoft/vscode-github-issue-notebooks/blob/master/README.md
