### ISSUE TITLE
Tree experience on Source Control is gone after update

### ISSUE THREAD

**Issue by amithegde** [microsoft/vscode#102041]
Issue Type: <b>Bug</b>

I updated to latest version and Tree viewer on the source control tab is gone. How to enable it back? Modifed files show up as flat list now.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (34.42GB free)|
|Process Argv|c:\One\Storage\XStore|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.3
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.36.1
xml|Dot|2.5.0
gitlens|eam|10.2.2
json-tools|eri|1.0.2
todo-tree|Gru|0.0.178
rest-client|hum|0.24.1
csharpfixformat|Leo|0.0.84
vscode-clang|mit|0.2.3
vscode-azureappservice|ms-|0.17.0
csharp|ms-|1.22.1
python|ms-|2020.6.91350
vscode-pylance|ms-|2020.7.0
azure-account|ms-|0.8.11
cpptools|ms-|0.28.3
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2427
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
vscode-sanddance|msr|3.0.0
gremlins|nho|0.23.0
indent-rainbow|ode|7.4.0
LiveServer|rit|5.6.1
trailing-spaces|sha|0.3.1
vscode-scss-formatter|sib|2.0.1
autoimport|ste|1.5.3
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.1.1
vscode-bond|yiw|0.0.10
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
It was moved under `...` menu View & Sort
![image](https://user-images.githubusercontent.com/1312662/87100919-4216fc00-c256-11ea-861c-673dba9e148b.png)

Can you see it?
