### ISSUE TITLE
Cannot install Visual Studio Code after replacing hard drive

### ISSUE THREAD

**Issue by federico-paolillo** [microsoft/vscode#102027]
- VSCode Version: 1.47.0 x64
- OS Version: Windows 10 Pro x64 2004.20161.1000

Steps to Reproduce:

1. Install Visual Studio Code on a different hard drive than the usual Windows C:/ drive
2. Replace said hard drive with another and format it giving it a different drive letter than before
3. Try to install Visual Studio Code with the official installer

Does this issue occur when all extensions are disabled?: Yes

Visual Studio Code installation is interrupted with this message
![image](https://user-images.githubusercontent.com/31439756/87091801-914f3380-c23a-11ea-9a07-cea45949be72.png)
Although the message says to "Please select another." the installer does not offer the possibility to do so

**Comment by federico-paolillo** [comment]
Apparently, removing the registry key...

Computer\HKEY_USERS\S-1-5-21-1548153122-3847237551-3578602553-1001\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1

...solves the problem.

It would be nice if it would be possible to change the path despite having Visual Studio Code already installed.
In this case it would have been useful because my previous hard drive was broken.

**Comment by joaomoreno** [comment]
Glad to know you've unblocked yourself.
