### ISSUE TITLE
Improve heading spacing on Markdown preview

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#102036]
The spacing on markdown preview has headings (h2,h3) in the middle between text, but they should be spaced less with the content underneath so it looks like a section. Right now the spacing looks even with the content below and above.

Here is an example (using grey matter theme):
<img width="676" alt="markdown-preview" src="https://user-images.githubusercontent.com/936006/87095255-50561f80-c238-11ea-8bcf-c4c2f023c3c1.png">

I've adjusted on photoshop what it should look like:
<img width="676" alt="markdown-preview (1)" src="https://user-images.githubusercontent.com/936006/87095426-a034e680-c238-11ea-9897-b661e828630d.png">

It's only slight but the bottom one brings the heading down slightly so its more together.
I looked into doing this but i could only find https://github.com/microsoft/vscode/blob/06f85af581281a3f45783329d375ecc7694930b4/extensions/markdown-language-features/media/markdown.css

@mjbvz

**Comment by mjbvz** [comment]
Yes that is the correct file to change. Try updating the css rules to adjust the heading spacing.

You can also quickly prototype changes using [your own css in the markdown preview](https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css)

**Comment by jasonwilliams** [comment]
@mjbvz do you have a way of inspecting to see what’s going on? I just get the web view doc when I do.
