### ISSUE TITLE
Can't set breakpoints in Chrome debugging

### ISSUE THREAD

**Issue by craigsh** [microsoft/vscode#102056]
- VSCode Version: 1.4.7
- OS Version: Windows 10

Steps to Reproduce:

1. Upgraded VS Code from 1.4.6 to 1.4.7.
2. Debugging in Chrome works but no breakpoints can be set. (Shows greyed out as "Unbound breakpoint").

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Can you please fill out the template from https://github.com/microsoft/vscode-js-debug/issues/new?template=bug_report.md? Editing this issue to add that info is fine.

Thanks!

/needsMoreInfo

**Comment by craigsh** [comment]
Uninstalling and re-installing 1.4.7 seems to have fixed the issue.
