### ISSUE TITLE
VSCode still recommends Remote-WSL extension after I turn off WSL feature on Windows

### ISSUE THREAD

**Issue by MapleCCC** [microsoft/vscode#102009]
Issue Type: <b>Bug</b>

One year ago I installed WSL on my Windows 10 machine. At that time VSCode detected that WSL was installed and recommended me to use the "Remote-WSL" extension.
Yesterday I tried to remove WSL on my Windows 10 machine by following three steps:

1. Uninstall all linux distro from Microsoft Store.
2. Turn off WSL feature as a whole from the 'Control Panel' -> 'Programs-Features' -> 'Turn on/off Windows features'.
3. Restart the machine.

Yet after the aforementioned steps, VSCode still somehow incorrectly detects that WSL is installed on the machine and recommends the "Remote-WSL" extension.

I wonder how VSCode internally detects the existence of WSL. Is it because VScode has error in its WSL-installation detection mechanism, or because I fail to remove WSL feature completely?

Thank you for any kind help and clarification.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.93GB free)|
|Process Argv|D:\Users\dell\Documents\Git-Repository\@Work-In-Progress\Go playground|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Lemmingh** [comment]
I also wonder why.

Interestingly, “**Remote - WSL**” is recommended to me because *it is installed*. 😂

![2020-07-10_“Remote - WSL” is recommended because it is installed](https://user-images.githubusercontent.com/43396014/87070482-746f2c00-c24b-11ea-9e71-2dea5fcf3e9a.png)

---

Additionally, if I recall correctly, recommendations are never dismissed until I click **Ignore Recommendation**.

**Comment by MapleCCC** [comment]
The problem is solved. Turn out that it requires more than one restart to let the "remove WSL feature" complete it job.

**Comment by aeschli** [comment]
Ok, cool. I tried to reproduce and it worked for me.

But what's strange is the label `The extension is recommended because you have Remote - WSL installed`. @sandy081 FYI.
