### ISSUE TITLE
Remember editor focus when arrowing between code cells

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#102049]
- Have 3 cells, code cell, markdown cell, code cell
- Put cursor in the first cell's editor
- Press down until the markdown cell is focused
- Press down again to focus the next code cell
- Its editor should get focus - the notebook "remembers" that the first code cell had editor focus and carries that across the markdown cell

---

- Same setup
- Cursor in the first cell's editor
- Click the container of the second code cell
- It should have container focus, not editor focus
- The "remembering" only takes effect when using arrow keys to focus cells

**Comment by isidorn** [comment]
This seems to work as expected now, adding verified label.
