### ISSUE TITLE
Extension Development Host can't open when selecting Chinese as language

### ISSUE THREAD

**Issue by mfkwgizhoujian** [microsoft/vscode#102064]
- VSCode Version: 1.47.0
- OS Version: macOS Catalina

Steps to Reproduce:

1. Configure Display Language to zh-cn and restart.
2. Press F5, the vscode will stuck in building.
3. Click the "正在生成..." text to open terminal, then press Ctrl+C, the [Extension Development Host] window will open.
4. Switch Display Language to en, it works correctly.

Does this issue occur when all extensions are disabled?: Yes

before press Ctrl+C
<img width="1828" alt="WeChat14f35c6141f09d23b8156e890aaca25a" src="https://user-images.githubusercontent.com/33543763/87131870-a2925180-c2c7-11ea-901a-9efe1bbe57bb.png">

after press Ctrl+C
<img width="1828" alt="WeChat64a632844eaa1fc21cfa998192f4dd40" src="https://user-images.githubusercontent.com/33543763/87132294-3d8b2b80-c2c8-11ea-8966-9cf94b769d00.png">

**Comment by bpasero** [comment]
Is this from VSCode sources?

**Comment by mfkwgizhoujian** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

This problem happened after I updated vscode to version 1.47.0.
But even if I rollback to 1.46.1, the problem still exist. I don't know why.

**Comment by bpasero** [comment]
@mfkwgizhoujian so you are trying to start an extension, can you share it?

**Comment by bpasero** [comment]
@weinand I can reproduce:
* install chinese simplified language
* enable it
* try to debug (F5) a hello world extension

=> 🐛 ext host window does not start

I could not find any place to understand why the window would not open, e.g. no logs.

**Comment by weinand** [comment]
I cannot reproduce.

What I did:
- created Hello Word extension
- installed "Chinese (Simplified) Language Pack for Visual Studio Code"
- restarted VS Code
- ran "Configure Display Language" and switched to "zn-cn"
- restarted VS Code
- F5

Result:
<img width="1201" alt="2020-07-10_12-12-51" src="https://user-images.githubusercontent.com/1898161/87143710-d27d2d00-c2a6-11ea-8c2e-6a3fd4db529e.png">

Do I have to switch the OS to Chinese as well?

**Comment by bpasero** [comment]
Hm, ok this is weird. Here in the office following my exact same steps, I cannot reproduce. 

Is there any way to tap into the debug launch to get output from that call to see if maybe there is an exception?

**Comment by weinand** [comment]
Chrome DevConsole shows a (harmless) 1000ms  timeout for the new JS debug.

**Comment by weinand** [comment]
@bpasero no, Chrome DevConsole is all we have...

**Comment by bpasero** [comment]
Can you give me instructions how to see that output, then I can try later from home again.

**Comment by weinand** [comment]
Just open the Chrome devtools in VS Code before pressing F5
