### ISSUE TITLE
package.json editor like Settings editor - graphical editing of the json file, with hints etc.

### ISSUE THREAD

**Issue by lukaszpolowczyk** [microsoft/vscode#102054]
package.json editor like Settings editor - graphical editing of the json file, with hints etc.

**Comment by aeschli** [comment]
This would be something to be provided by an extension.

**Comment by lukaszpolowczyk** [comment]
@aeschli Extensions can use the graphical interface used in the `.vscode/settings.json` files?
Because I mean the use of this ready-made graphical interface.

**Comment by aeschli** [comment]
No, the settings UI is internal.
Extensions can create webviews that render HTML.

**Comment by lukaszpolowczyk** [comment]
@aeschli In that case, I would actually like to ask for the extension APIs to generate the settings page.
Not to duplicate functionality.
In webviews this would be a duplication of functionality.

**Comment by aeschli** [comment]
Can you be specific on the API you want?
I'm not sure how the settings UI can be reused for a package.json editor.

**Comment by lukaszpolowczyk** [comment]
The extension (e.g. to GUI for package.json) provides titles, descriptions, field types, default values, available values for fields.

Such an extension is registered as a way to open the package.json file (with the option of opening in a regular text editor), generates the package.json GUI, using ready-made elements used in the GUI settings, including search engine, outline, button to switch between package.json from folders belonging to workspace.
Non-standard fields need to be edited in a text editor, so is the settings GUI - link to edit the field in text form.

This is everything as in the GUI settings.
