### ISSUE TITLE
Improve flow for users stuck on old sync data format that cannot be migrated

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#102001]
I got into this situation by trying to sync to a dev server after a long time since the `{}` -> `{ version: 1, content: ... }` migration has been removed. This may affect a handful of preview users, but it could also happen in the future when/if we remove a version 1->2 migration path. Problems/suggestions below:

This happens when you try to turn on sync:

![image](https://user-images.githubusercontent.com/2193314/87050909-c3698280-c1b3-11ea-8bf7-1457df31b927.png)

I think we should create a specific message for this case where the format is no longer/not compatible with the current version. Perhaps with a button to help action it (open synced data, clear data?).

Once I figured out how to get to the synced data view, clicking on the bad settings gave me this error:

![image](https://user-images.githubusercontent.com/2193314/87051057-f0b63080-c1b3-11ea-8459-4675e4f7c591.png)

What I needed to do was reset the data in the ... menu:

![image](https://user-images.githubusercontent.com/2193314/87051120-01ff3d00-c1b4-11ea-82fc-61763c4228ae.png)

We should add a clear data button to the cannot parse sync data notification to help the user get out of this situation.

**Comment by sandy081** [comment]
Following notification is shown when you have old data in cloud

<img width="471" alt="image" src="https://user-images.githubusercontent.com/10746682/87465342-bfef5480-c614-11ea-97a4-17813e53b23a.png">

Reset action will show following confirmation dialog before resetting

<img width="467" alt="image" src="https://user-images.githubusercontent.com/10746682/87465411-e1504080-c614-11ea-88f2-42193c503ce0.png">

Show synced data action will show sync activity view and opening data will show following error with reset action

<img width="472" alt="image" src="https://user-images.githubusercontent.com/10746682/87466928-69cfe080-c617-11ea-995e-81555bbf5964.png">

**Comment by sandy081** [comment]
@gregvanl It would be great if you have any suggestions for wordings. 

Context - this error is shown when server has older data and client is on newer version that requires to reset data on server.

**Comment by gregvanl** [comment]
@sandy081 The text looks fine except there is an extra "in".
"Preferences sync cannot be turned on because your data in the cloud is older than that of in the client."
I think it should be:
"Preferences sync cannot be turned on because your data in the cloud is older than that of the client."

**Comment by sandy081** [comment]
Not sure if this can be verified as it needs to have some old data or changing code.

@Tyriar Is it possible for you to verify this either by tweaking data in the test server or its also ok to just do code review and looking at the images I attached when this happens?

**Comment by Tyriar** [comment]
I had some trouble verifying as well, reviewed the messages and commit, looks good 👌
