### ISSUE TITLE
Workbench list scroll speed is too slow?

### ISSUE THREAD

**Issue by Xiliusha** [microsoft/vscode#102055]
- VSCode Version:1.47.0 (system setup)
- OS Version:Windows_NT x64 10.0.19041

**I don't know if this is a bug.**

Steps to Reproduce:

1.Check Workbench->List: Smooth Scrolling
![图片](https://user-images.githubusercontent.com/40131112/87105989-f0d72e80-c28e-11ea-85e2-97dcf89f44b1.png)

2.Then the scrolingl speed of the settings editor page will become very slow, and there is no corresponding setting to change the scroll speed.

Does this issue occur when all extensions are disabled?: No

**Comment by joaomoreno** [comment]
How about other lists? The suggest widget for example, does it also get very slow?

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/102261
