### ISSUE TITLE
Test failure: notebook workflow notebook join cells

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#102092]
1) notebook workflow notebook join cells:

      AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=81396&view=logs&j=800c766b-cf7f-545c-6b0a-ae5b31f2fdcf&t=51b4207b-308f-5f00-05c4-35120a101a46&l=94

**Comment by joaomoreno** [comment]
Sorry, @rebornix, I think `bug` categorizes failing tests better than `debt`.

**Comment by rebornix** [comment]
Verifier: 

* Create a new GitHub issue notebook
* Create two code cells, first one `abc`, second one `def`
* Join these two cells (Notebook: Join with next/previous cell)
* Verify if the new cell content is `abc\ndef`.
