### ISSUE TITLE
js-atom-grammar and Tomorrow Eighties color syntax issues

### ISSUE THREAD

**Issue by MaximeDesRoches** [Microsoft/vscode#10207]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Install js-atom-grammar and Theme-TomorrowKit
2. type in:
```
export const loadedRecordsNumber = createSelector(
	[schemaSelector, recordsSelector],
	(schema, allRecords) => {
		const tableIds = Object.keys(allRecords);

		const nLoadedRecords = tableIds.reduce((num, tableId) => {
			const table = schema.tables[tableId];
			if (table && table.type === TYPE_MAIN) {
				return num + Object.keys(allRecords[tableId]).length;
			}
			return num;
		}, 0);

		return {
			nLoadedRecords,
		};
	}
);
```
Outputs:
![code-sample](https://cloud.githubusercontent.com/assets/5558036/17442120/342cecea-5b02-11e6-8ed3-8a6e2c61b469.png)

The same thing happens with a jquery function call:
![code-sample-2](https://cloud.githubusercontent.com/assets/5558036/17442126/373ec55c-5b02-11e6-9a0e-41d8e1938056.png)

**Comment by aeschli** [comment]
Caused by https://github.com/Microsoft/vscode/issues/3008
