### ISSUE TITLE
Tolerate trailing commas in jsonc format

### ISSUE THREAD

**Issue by alexreg** [microsoft/vscode#102061]
Would it be possible to add tolerance for trailing commas to the `jsonc` (JSON With Comments) format? Even as an optional setting that is off by default. While I can understand not adding support to the `json` (spec-compliant) format, there doesn't seem to be a good reason not to add it (either on automatically or configurable) to `jsonc`.

In case there's any doubt over what I mean, here's an example.

```jsonc
{
    "foo": 123,
    "bar": [
        "abc",
        "def",
        "ghi", // trailing comma: okay!
    ], // trailing comma: okay!
}
```

**Comment by aeschli** [comment]
We had that, but changed it back to warn about commas. See https://github.com/Microsoft/vscode/issues/43825

JSONC is not a standard, but there are several tools that use JSON with comment such as `eslint` and `tsconfig`.
However, they don't accept the trailing comma. The editor would not complain and the user would only find out at runtime that there's a trailing comma.
After multiple complaints we changed the default to warn.

However, in out VSCode settings files, trailing commas are accepted. This knowledge comes in through the JSON schema of the file. If the schema says `"allowTrailingCommas": true,` then it's not warned.

I want to leave this as is is now. Do you have a schema for your file?

**Comment by alexreg** [comment]
Ah, I see, thanks for explaining. I think you're right... many "jsonc" parsers accept trailing commas, while many don't. The Python one that I'm using happily does (and indeed I chose it partly for that reason).

Indeed, I was the one (as far as I'm aware) who requested the `allowTrailingCommas` feature for settings files, and that's great. :-)

No, I don't have a JSON schema. Maybe a setting like `allowTrailingCommas` could be added to the `[json]` language section in VS Code settings? Ideally this would be configurable on a per-directory or even per-file basis, but I suppose that comes down to how VS Code workspace settings work in general. Perhaps support for that has recently been added?

**Comment by aeschli** [comment]
We don't have folder/file based settings. I think there's a feature request.
But adding a schema is easy. It can also be done in the user settings:
```
	"json.schemas": [{
		"fileMatch": ["foo.jsonc"],
		"schema": {
			"allowTrailingCommas": true
		}
	}]
```

**Comment by alexreg** [comment]
Oh, I thought you meant [JSON Schema](https://json-schema.org/). That's great, thank you.

**Comment by aeschli** [comment]
"schema" is for user defined JSON schemas. `allowTrailingCommas` is just a (internal) VSCode extension of JSON schema.
