### ISSUE TITLE
Source control not working properly

### ISSUE THREAD

**Issue by jakubpav** [microsoft/vscode#102028]
Issue Type: <b>Bug</b>

I'm using msys2 git. 
I've changed git.path in settings for my user settings.
I have clonned my repo from github, but souce control doesnt seem to read ./.git/ repository and offering me "Initialize Repository" && "Publish to GitHub"  buttons.
So i tried to reinstall vscode but it has no effect.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jakubpav** [comment]
Oh, now I figured out that it's alright on other computer on which i didn't updated vscode to 1.47.0 and using msys2 there too.

**Comment by joaomoreno** [comment]
> I'm using msys2 git.

VS Code is only supported with Git for Windows. Can you reproduce the issue if you use Git for Windows?

**Comment by jakubpav** [comment]
When I'm using got for Windows then it's all right apparently. But it would be nice to have a choice although... ;)

**Comment by jakubpav** [comment]
Is there any why I can't use whatever I want?

**Comment by joaomoreno** [comment]
Yes, we have a limited set of features we support.
