### ISSUE TITLE
Saving untitled file with language mode JSONC uses wrong default extension

### ISSUE THREAD

**Issue by TheWyo** [microsoft/vscode#102032]
Issue Type: <b>Bug</b>

Repro steps:
1) Launch VSCode (reproduces with extensions disabled).
2) Create new file
3) Run "Change language mode" action and pick JSONC.
4) Write some example json
5) Save the file as
6) Enter a file name (without an extension)
7) VSCode saves with .code-workspace instead of .jsonc.

Screenshots:
![2020-07-09_222748](https://user-images.githubusercontent.com/1192064/87093150-a0cb7e00-c234-11ea-839d-c39e4c2b22a2.png)
![2020-07-09_222827](https://user-images.githubusercontent.com/1192064/87093157-a2954180-c234-11ea-934c-5d672a2426de.png)
![2020-07-09_222844](https://user-images.githubusercontent.com/1192064/87093163-a45f0500-c234-11ea-8392-27f01cfc3f77.png)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18362

(Not new to 1.47, noticed in previous version but updated before filing this report.)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.6
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
vscode-todo-plus|fab|4.17.1
vscode-firefox-debug|fir|2.9.0
vscode-postfix-ts|ipa|1.9.1
svn-scm|joh|2.11.5
vscode-codemetrics|kis|1.24.0
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
cpptools|ms-|0.28.3
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2427
debugger-for-chrome|msj|4.12.9
material-icon-theme|PKi|4.2.0
rust|rus|0.7.8
code-settings-sync|Sha|3.4.3
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|3.1.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
This is likely due to this:

https://github.com/microsoft/vscode/blob/561f5b6d26ea702507986aac0d3f66dc4a5c24fc/extensions/configuration-editing/package.json#L30

**Comment by aeschli** [comment]
The save dialog gets the associated file suffice using `modeService.getExtensions`.
They are unsorted and `.code-workspace" happens to be the first one.

We would need something like `modeService.getPrimaryExtension` which would be the first association from the 'main' language definition (e.g. the one that also defines Aliases). @alexdima

**Comment by alexdima** [comment]
Related: #102438

There appears to be another desire, to control what the suggested extension should be even without using `extensions` in the `package.json`.

**Comment by aeschli** [comment]
Using #103882 for the July 2020 candidate fix.
