### ISSUE TITLE
Opening new tabs and see Preview Editors

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#10208]
- VSCode Version: 1.5.0-insider 1a7ca5a Date 2016-08-05T07:19:53:669Z
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

1º Situation

Steps to Reproduce:

1. Open two or more tabs that are not in Preview Editors.
2. Click on the first tab.
3. Open a new tab by double-clicking on the tab bar, or File> New File or Ctrl + N.

Note that the new tab and open the side of the first. I think it would be better to open in the last position equal to browsers.

2º Situation

Steps to Reproduce:

1. Open two or more tabs that are not in Preview Editors.
2. Click on the first tab.
3. Click on a file to open in Preview Editors.

This should open the side of the last tab and not the side that was previously opened.

**Comment by bpasero** [comment]
@Tekbr the first issue you described is fixed. The second issue is an explicit design decision: new tabs (including preview editors) will always open to the side of the currently active one.

**Comment by Tekbr** [comment]
Thank you @bpasero. The second issue, put an option in the settings, if it should appear at the end or near the previous active tab is not in the plans?

Anyway waiting for the next update of the insider.

**Comment by bpasero** [comment]
@Tekbr there is a setting to always open new editors at the end: 

`"workbench.editor.openPositioning": "last"`

**Comment by Tekbr** [comment]
Thanks @bpasero again.

**Comment by Tekbr** [comment]
@bpasero When we click twice on the bar, the tab opens in the last position, but when we use File> New File or Ctrl + N, it continues to open on the side that was previously active.

- VSCode Version: 1.5.0-insider 666ed83 Date 2016-08-10T09:07:54:219Z
- OS Version: Windows 10

**Comment by bpasero** [comment]
Cannot reproduce when I set "workbench.editor.openPositioning": "last"

**Comment by Tekbr** [comment]
Yes, but you said it was fixed for new tab.

> @Tekbr the first issue you described is fixed.

That is if I do not activate this function `workbench.editor.openPositioning": "last"` , the new tab would have to open anyway in the last position. I said to double-clicking on the tab bar, or File> New File or Ctrl + N.

**Comment by Tekbr** [comment]
@bpasero Am I right?

**Comment by bpasero** [comment]
I think any other action should not change it behaviour: For the double click I can see the motivation to open at the end because that is essentially where you are clicking.
