### ISSUE TITLE
Extensions close one by one when I click on explorer

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10202]
Open more than one extension inside a tab and click on the explorer: Only the last active extension closes, not all of them.

**Comment by joaomoreno** [comment]
Check out the [code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionEditor.ts#L84). How else can I do it?

**Comment by bpasero** [comment]
@joaomoreno if you keep all the inputs that get opened in a session while the viewlet is open you can call IEditorService.closeEditor(input). You can ignore the returned promises because they will only apply if an editor is dirty and for you it is not the case.

**Comment by joaomoreno** [comment]
How can I track when an input is opened and closed? I thought the editor would do that for me.

**Comment by bpasero** [comment]
@joaomoreno right, I think the best way for you would be to go over all editors that are open that are of your extension input:

IEditorGroupService.getStacksModel() will give you the entire model of editors that are open and you can iterate over all the groups and each editors in there to decide which one to close.

**Comment by rebornix** [comment]
![closeextension](https://cloud.githubusercontent.com/assets/876920/18151011/44b9a71c-6fa0-11e6-9015-9f108389962e.gif)

Not sure if I understand the question correctly, we do want to close all extension editors when we switch to Explorer, right? Per above video, seems the last extension editor is still not closed.

**Comment by bpasero** [comment]
@rebornix are you sure you tried on a build with this change in?

**Comment by rebornix** [comment]
@bpasero oh right, I suppose this change has not been released yet, it's false negative.
