### ISSUE TITLE
Reading from stdin via tmp file and pipe raise an exception

### ISSUE THREAD

**Issue by kleszcz** [microsoft/vscode#102085]
- VSCode Version: 1.47.0
- OS Version: Windows 10 Pro 1909

Steps to Reproduce:

1. Open PowerShell
2. Run `echo "test" | code -`
3. Observe exception in events.js:180
[VSCode_Pipe_Error_CallStack.txt](https://github.com/microsoft/vscode/files/4902219/VSCode_Pipe_Error_CallStack.txt)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@kleszcz thanks for finding this. a regression we should fix in our recovery release.

**Comment by kleszcz** [comment]
@bpasero I'm glad it helps you. I think this might be related to  #99815  but in my case file opens with content in it.

**Comment by bpasero** [comment]
Yeah maybe related. Thanks for pointing that out.

**Comment by bpasero** [comment]
Pushed to `master` and for June recovery.

**Comment by bpasero** [comment]
**Verification:**
* Open PowerShell
* Run echo "test" | code -
* There should be no exception
