### ISSUE TITLE
debug bootloader breaking vscode terminal

### ISSUE THREAD

**Issue by chasingSublimity** [microsoft/vscode#102063]
Issue Type: <b>Bug</b>

Hi there!

I think the new vscode update broke my terminal. Any time i try and execute a node-based command from the built-in terminal, i get the following error:

```
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module '/var/folders/fv/r99t3znd47s3s02wjzylls6c0000gn/T/vscode-js-debug-bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1345:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/repl.js:18:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
```

Any ideas what could be going on?

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|32.00GB (13.09GB free)|
|Process Argv|-a .|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.10
django-html|bib|1.3.0
django|big|1.0.2
better-toml|bun|0.3.2
gotemplate|cas|0.4.0
vscode-standardjs|che|1.3.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.36.1
vscode-eslint|dba|2.1.6
vscode-quick-select|dba|0.2.8
vscode-deno|den|1.25.0
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
go|gol|0.15.1
npm-dependency-links|her|1.1.0
restructuredtext|lex|128.0.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-cosmosdb|ms-|0.13.0
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
azure-account|ms-|0.8.11
cpptools|ms-|0.28.3
vsliveshare|ms-|1.0.2427
vsliveshare-audio|ms-|0.1.85
debugger-for-chrome|msj|4.12.9
rust|rus|0.7.8
code-settings-sync|Sha|3.4.3
addDocComments|ste|0.0.8
code-spell-checker|str|1.9.0
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.8.0
city-lights-icon-vsc|Yum|1.1.3

(8 theme extensions excluded)

</details>

**Comment by chasingSublimity** [comment]
Ok, so i followed the steps [here](https://github.com/microsoft/vscode-js-debug/issues/374#issuecomment-622239998) and that fixed `Cannot find module` error i posted above. Now, however, the following command just launches two processes and hangs. Here's the output:
```
mocha --inspect-brk=9233 test
Debugger listening on ws://127.0.0.1:50840/48494d59-616b-4bfc-9e05-cb0145f33ac7
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:9233/9c43e463-a1bf-4538-a1d6-06d6c796e61f
For help, see: https://nodejs.org/en/docs/inspector
```

**Comment by connor4312** [comment]
@chasingSublimity unfortunately, due to the way the new debugger works, --inspect-brk is not compatible with auto attach. See https://github.com/microsoft/vscode/issues/99526#issuecomment-640771550 for details.

You have a couple options:

 - Manually add a breakpoint on the first line of your script
 - Set up a launch config (in your launch.json) and use --inspect-brk there, or the `stopOnEntry: true` options

**Comment by connor4312** [comment]
Hi, following up on this issue after feedback from you and other users. There are two things to know:

1. If you don't need to debug on the first line of your program, it's actually safe to just remove `--inspect-brk` from your npm scripts with the new debugger. Previously, it was useful to prevent your program from running before VS Code could attach to it, but this is no longer necessary.

1. We've added some change to gracefully fall back (with a warning) when running a program with --inspect-brk in the config. This flag prevents us from being able to attach to children and unlock some additional new functionality, but it should work. This change will be available in the recovery release coming next week, and is available on our [nightly extension](https://github.com/microsoft/vscode-js-debug/#nightly-extension).

Happy Coding!

**Comment by chasingSublimity** [comment]
Thanks friend!
