### ISSUE TITLE
Automatically detect package manager (npm.packageManager)

### ISSUE THREAD

**Issue by nickmccurdy** [microsoft/vscode#102050]
# Problem
When switching between many JavaScript projects, it's often easy to forget which package manager should be used in each project. JavaScript package managers aren't quite compatible either. Each package manager resolves dependencies differently, so accidentally installing with npm could cause a yarn project to break.

While VSCode has the `npm.packageManager` option to switch between npm, yarn, and pnpm, it's not very convenient to have to remember to set it on every project. Even if a user has a global preference, they will often have to clone several projects they're contributing to using other package managers anyway. Personally, I have so many projects installed that it's too inconvenient for me to set this option, so I end up figuring out which package manager to use manually and running it in the terminal.

# Proposed option changes
I would like `npm.packageManager` to default to a new `auto` option, which would select a package manager based on the presence of workspace and lock files using [`preferred-pm`](https://www.npmjs.com/package/preferred-pm). If a lock file doesn't exist, the user is probably using npm anyway, and we can just default to `npm` like we already are. It would also be nice to set up some sort of warning if multiple lock files are found, as most package managers do this to inform users that their package installations can break because of differences in version resolution.

# Ideas for extension API changes
I'm not actually familiar with the extension APIs, but I think it would be nice to expose this as some sort of generic API for extensions so they don't have to reimplement this functionality or reinstall dependencies. This would also prevent extensions from breaking if VSCode changed its package manager detection heuristics in the future. This also might be useful for other internal features like automatically installing projects when cloned with the right package manager, though with the extension API users would have an alternative if something wasn't officially supported.

**Comment by nickmccurdy** [comment]
I'm also not against making an extension for this, but I figured it would be best to propose it internally first for better support with other extensions.

**Comment by alexr00** [comment]
I am not opposed to an auto option for `npm.packageManager`.

**Comment by shivangg** [comment]
@alexr00 I'm willing to work on this one. 

Should the development be started **only** after this issue has moved from Backlog Candidate to the Backlog?

**Comment by alexr00** [comment]
@shivangg thanks for checking, especially since we aren't always consistent about what to do there. If you start working on it I will move it into the current milestone.

More spec-ing details:

> I would like npm.packageManager to default to a new auto option, which would select a package manager based on the presence of workspace and lock files using preferred-pm. 

Making `auto` the default sounds good to me.

> If a lock file doesn't exist, the user is probably using npm anyway, and we can just default to npm like we already are.

Agree that default should be npm if there is not lock file.

> It would also be nice to set up some sort of warning if multiple lock files are found, as most package managers do this to inform users that their package installations can break because of differences in version resolution.

A warning if there are multiple lock files AND `auto` is set makes sense. There should be no warning if `auto` is not set. However, it is still possible to simply proceed even if there are multiple lock files. So I would expect the behavior to be continue using one of the package managers and also show a warning notification. I would expect order of priority with multiple lock files to be npm, yarn, then pnpm.

**Comment by shivangg** [comment]
@alexr00 Thanks for the reply. Here's a draft PR. 

As `preferred-pm` exposed an `async` function to query the preferred package manager, I had to make many of the dependent functions `async`. Let me know if their if a better/efficient way to prevent this. 

Even after setting `"esModuleInterop": true` in the `vscode/extensions/npm/tsconfig.json`, I still get the warning that 
```
Module '"... /vscode/extensions/npm/node_modules/preferred-pm/index"' 
can only be default-imported using the 'esModuleInterop' flag ts(1259)
```

**Comment by shivangg** [comment]
@alexr00 I'm not sure of the cleanest way to detect multiple lockfiles. `preferred-pm` only returns the preferred pm in priority order `npm` > `yarn` > `pnpm` even in case of multiple lockfiles.

Is there a better way to proceed without deduplicating the `preferred-pm` logic in vs code?

**Comment by alexr00** [comment]
@shivangg, I don't know of a better way.

**Comment by nickmccurdy** [comment]
The pull request looks good to me so far: #102494

**Comment by nickmccurdy** [comment]
Thanks for publishing this. I'm trying to patch the ESLint extension so it also automatically detects the package manager, but it needs to know which package manager has been automatically discovered to provide specific error messages for each package manager. Is there a public API exposing either the currently used package manager (similar to `packageManager` but `auto` is actually resolved to a package manager) or the same logic that VSCode uses internally in the `auto` setting?

**Comment by alexr00** [comment]
Great question! We also ran into this while testing, so we added a command that returns the resolved package manager: `npm.packageManager`. Executing that command should give you what you're looking for (and please ping if it doesn't).

**Comment by nickmccurdy** [comment]
Thanks. How can I access this from the language server code though? I get `Cannot find module 'vscode' or its corresponding type declarations. ts(2307)` when importing `'vscode'`.

**Comment by alexr00** [comment]
I think you will need to do that in your [language client](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#explaining-the-language-client). However, I have not written a language server before, so you would likely know better.
