### ISSUE TITLE
Double paste

### ISSUE THREAD

**Issue by littlefrog1973** [microsoft/vscode#102053]
We have written the needed data into your clipboard because it was too large to send. Please paste.

When I copy text from other software for ex.  MS Edge and paste to VS CODE editor by [Ctrl+V]. It doubled my copied text.

**Comment by craigsh** [comment]
I experience the same thing. Using NX Console to generate Angular components. I paste "abc" into the path textbox and it ends up as "abcabc".

**Comment by pikadun** [comment]
I encountered the same problem.
When I paste the content into the Webview, it will paste twice.

**Comment by tspriggs** [comment]
I have the same issues of duplicate pasting, when copying and pasting code inside an ipynb file.

**Comment by davins90** [comment]
hi guys,

i noticed the same problem after update to the latest version (1.47) when copy and paste in Jupyter notebook extension.

Thanks

**Comment by mjbvz** [comment]
Duplicate of #101946
