### ISSUE TITLE
'vscode.executeDefinitionsProvider' not found

### ISSUE THREAD

**Issue by schmeic** [microsoft/vscode#102020]
- VSCode Version: 1.46.1
- OS Version: Linux Mint 18.3

Steps to Reproduce:

1. Follow steps to create my first extension:
https://code.visualstudio.com/api/get-started/your-first-extension

2. Copy and paste code to executeCommand  'vscode.executeDefinitionsProvider' directly from this guide:
https://code.visualstudio.com/api/extension-guides/command

3. See this error in the debug console:
Error: command 'vscode.executeDefinitionsProvider' not found

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
It is `vscode.executeDefinitionProvider`, with the `s`
