### ISSUE TITLE
Misleading indentation, missing visual separation between repos in single-view Source Control

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#102081]
- VSCode Version: 1.47
- OS Version: Windows 10

I feel that the single-view "Source Control" has some edge(?) cases where the visual separation between repos is missing. See this example:
![image](https://user-images.githubusercontent.com/12128514/87135580-875d1d00-c29a-11ea-8f91-a98339f5719e.png)

I don't know about the general impression, but to me, "cds" and "cia" do not appear to on the same level, visually - cds looks more like a child of cia, which it is not.

The same visual impression is even stronger when changes are not collapsed:
![image](https://user-images.githubusercontent.com/12128514/87135770-c8553180-c29a-11ea-8baa-555a4aac491a.png)

Now cds even appears like one of the changes of cia.

**Comment by gjsjohnmurray** [comment]
Related to #101103 where you can see some experiments.

In your case the fact that the cds repo has no changes etc means it lacks a twistie (>)

Maybe try changing the `scm.providerCountBadge` setting to see if it helps you distinguish repos from files more easily.

**Comment by bersbersbers** [comment]
Thanks for the link!

> Maybe try changing the `scm.providerCountBadge` setting to see if it helps you distinguish repos from files more easily.

I tried `"scm.providerCountBadge": "visible"`, but since "Changes" has the badge, too, it does not offer any visual clue that cds is _not_ parallel to "Changes" (see my first screenshot).

**Comment by joaomoreno** [comment]
@bersbersbers Do you have any suggestions? We don't want to put a horizontal line since that will resemble the split views.

**Comment by Nagarian** [comment]
> @bersbersbers Do you have any suggestions? We don't want to put a horizontal line since that will resemble the split views.

As a suggestion you can take the same design as extensions panel (see screenshots in my issue #102285 )
I think that should be more understandable and that's use a concept we already know

**Comment by gjsjohnmurray** [comment]
@joaomoreno I think the suggestion from @misolori [here](https://github.com/microsoft/vscode/issues/101103#issuecomment-656750762) about retaining the twisties repos with no changes is worth trying. Per his mockup this would be a down-pointing (i.e. expanded) one.

Another idea would be to move the (optional) repo change count badges to the left, between the twistie (if there is one) and the repo label (already bold in an attempt to make it stand out from other rows).

**Comment by bersbersbers** [comment]
> @bersbersbers Do you have any suggestions? 

Unfortunately, no.

**Comment by justinian-tomegea** [comment]
Is there any reason why the SCM repository names are now hard set to a bold font ? Can we instead have some much deserved and consistency with the Explorer pane ? Am I missing a configuration option for disabling the BOLD on the font in the SCM ? Can we have one added ?

**Comment by gjsjohnmurray** [comment]
> Is there any reason why the SCM repository names are now hard set to a bold font ?

@justinian-tomegea see https://github.com/microsoft/vscode/issues/101103#issuecomment-652845274. There was a lot of discussion and experimentation on that thread to achieve some differentiation between repos and their contents.

**Comment by Sesna** [comment]
![image](https://user-images.githubusercontent.com/8176600/87539316-3b620c00-c6d0-11ea-8057-6318aba10731.png)
as the image show, I open 10 repository, it is very hard for me to distinguish each one. and which repository now I operating, I think it is better to highlight which repository I operating now, for example, highlight the repository name, and hide the synchronize, commit button, refresh button of those inactive. since I use the new feature, I had commit changes incorrectly 3 times.

**Comment by gjsjohnmurray** [comment]
> highlight which repository I operating now

@Sesna What determines which repository you are operating on? The one for the currently-focused open file?

Maybe my [proposal for accordion behaviour](https://github.com/microsoft/vscode/issues/102118#issuecomment-657464466) would help here.

**Comment by astrowonk** [comment]
> 
> 
> > highlight which repository I operating now
> 
> @Sesna What determines which repository you are operating on? The one for the currently-focused open file?
> 
> Maybe my [proposal for accordion behaviour](https://github.com/microsoft/vscode/issues/102118#issuecomment-657464466) would help here.

Put a list of repos at the top. We click on a repo, the changed files and commit message appear for that repo, same as the old UI. I don't think it should have anything to do with the currently-focused file. The commit message and changed files should always be in the same place at the bottom. An accordion system still has the commit message field and the widgets for the change moving around with the list of other repos. Just always keeps that interface/control below the list of repos. The old UI had this right.

**Comment by gjsjohnmurray** [comment]
> Put a list of repos at the top.

@astrowonk All of them? Or a scrollable list showing up to _N_ of them at a time? If your list has a large number of repos and you are actively working on files in the first and the last (perhaps in two editor groups), you want to do the scrolling to switch between the two repos in the SCM view?

**Comment by m50** [comment]
This misleading indentation, plus the spacing between everything, with no clear visible separation has made it impossible for me to use the VCS feature in VSCode's latest update. It's an accessibility nightmare for those who have reading disorders, where without proper spacing, letters get jumbled. There doesn't appear (at least that I found) to change the background color or spacing of the titles, so it's completely unusable. The earlier version allowed me to just look at one section at a time, having a separation between the providers and the actual commit section. This was plenty usable, and quite a lot better accessible (at least for reading issues).

I've had to revert my vscode version specifically because of this issue.

**Comment by Sesna** [comment]
> > highlight which repository I operating now
> 
> @Sesna What determines which repository you are operating on? The one for the currently-focused open file?
> 
> Maybe my [proposal for accordion behaviour](https://github.com/microsoft/vscode/issues/102118#issuecomment-657464466) would help here.

The Accordion UI is a good idea to fix this problem, maybe we don't need to highlight the current operating repository, but badly need to distinguish each repository clearly. by the way I think the old version is better too.

**Comment by joaomoreno** [comment]
Merging with #102118
