### ISSUE TITLE
Cannot start terminal in WSL 2

### ISSUE THREAD

**Issue by enzy** [microsoft/vscode#102090]
Issue Type: <b>Bug</b>

- have systemd installed in the WSL 2 distro https://github.com/DamionGans/ubuntu-wsl2-systemd-script
- try to launch terminal from VS Code

![87141613-985e5c00-c2a3-11ea-888a-a64671c5e0c0](https://user-images.githubusercontent.com/809888/87141723-c5ab0a00-c2a3-11ea-9c31-001e85bcb916.png)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.20152
Remote OS version: Linux x64 4.19.121-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu1804|
|OS|Linux x64 4.19.121-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2711)|
|Memory (System)|12.40GB (11.03GB free)|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-babel-coloring|dza|0.0.4
auto-close-tag|for|0.5.8
latte|Kas|0.6.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.3.1
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
sublime-keybindings|ms-|4.0.7
debugger-for-chrome|msj|4.12.9
language-liquid|nei|0.1.1
proto|pet|0.0.2
vscode-nginx|sha|0.6.0
latex-support|tor|3.2.0
vscode-icons|vsc|10.1.1
wordpress-toolbox|wor|1.3.7
JavaScriptSnippets|xab|1.8.0
vscode-caddyfile-syntax|zam|1.0.4
entity-insert|all|0.0.1
All-Autocomplete|Ati|0.0.23
vscode-database|baj|2.2.3
path-intellisense|chr|2.2.1
vscode-devtools-for-chrome|cod|0.0.7
compulim-vscode-closetag|Com|1.2.0
vscode-new-file|dku|4.0.2
xml|Dot|2.5.0
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
html-slim-scss-css-class-completion|gen|1.7.5
path-autocomplete|ion|1.14.0
open-file-from-path|jac|1.3.4
fuzzy-definitions|jri|0.0.3
wrapSelection|kon|0.8.0
vscode-js-annotations|lan|0.11.0
twig-language-2|mbl|0.9.1
rainbow-csv|mec|1.7.0
vscode-docker|ms-|1.3.1
sublime-keybindings|ms-|4.0.7
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.24.0
prettier-vscode|pre|3.14.1
sass-indented|rob|1.5.1
partial-diff|ryu|1.4.1
vscode-fileutils|sle|3.0.1
language-stylus|sys|1.11.0
es-quotes|vil|0.2.6
vscodeintellicode|Vis|1.2.9
expand-selection-to-scope|vit|0.2.0
gitblame|wad|4.1.0
sublime-text-pack|wad|0.0.2
exclude-it|YoR|1.2.2
sublime-commands|Zar|0.1.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
This might be causing the problem 🤷 

https://github.com/DamionGans/ubuntu-wsl2-systemd-script/blob/ca7b15b082d1bf23f43123a019e61ad0926fabbd/enter-systemd-namespace#L45-L47

I think you needs to report this to that repo. To help diagnose this you can get the full environment the terminal launches with by enabling trace logging https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
