### ISSUE TITLE
Web smoke test failure: Language Features

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#102021]
1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Language Features
           verifies settings:
     Error: Timeout: get element '.view-overlays .cdr.squiggly-error' after 20 seconds.
      at C:\Users\rebor\code\vscode\test\automation\out\code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\rebor\code\vscode\test\automation\out\code.js:9:58)

**Comment by rebornix** [comment]
In VS Code it's now a warning (yellow squiggly).

**Comment by aeschli** [comment]
Works for me on HEAD: 622aa939d9ec88f0ed74e6e3eebdc6e7586983c2
Ubuntu 18.04
`yarn smoketest --web` with steps from https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md
