### ISSUE TITLE
UI freezes sometimes

### ISSUE THREAD

**Issue by smartpcr** [microsoft/vscode#102095]
Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19635

Steps to Reproduce:

this happened recently (~1 week ago)
1. after file moves or open a new vs code window 
2. UI would freeze sometimes (not always, several times in an hr)

Does this issue occur when all extensions are disabled?: yes

**Comment by smartpcr** [comment]
will find out which extension is causing the problem.

**Comment by smartpcr** [comment]
still happens after disabled all extensions, freeze time dropped to a few seconds

**Comment by fish-finger** [comment]
Same for me on ubuntu.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by fish-finger** [comment]
Its freezing proceeding a save of the editor, not always but regularly.

**Comment by AlCalzone** [comment]
I'm also getting random freezes with the current version. I haven't found out yet what causes it, but VSCode becomes completely unresponsive and I have to kill it with the process manager (also Windows 10).

Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Datum: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
Betriebssystem: Windows_NT x64 10.0.18362

**Comment by biddster** [comment]
Seeing this too. Can't quite put my finger on what's causing it yet. Anecdotally, it seems to be when I'm interacting with the embedded terminal (I'm using git bash on windows 10).

This did not happen in the previous version.

**Comment by AlCalzone** [comment]
> Anecdotally, it seems to be when I'm interacting with the embedded terminal (I'm using git bash on windows 10).

I'm also using git bash on Windows 10 and if I open a couple instances and close them quickly (using the trash bin icon), freezes happen reproducibly.

**Comment by AlCalzone** [comment]
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/17641229/87677232-d06d0f80-c779-11ea-88df-d3cd64df7fdb.gif)

**Comment by fish-finger** [comment]
That's disappeared now, have not seen freezing for at least a week now over successive releases
