### ISSUE TITLE
Cannot read property 'paths' of undefined in angular cli after VS Code update

### ISSUE THREAD

**Issue by vateseeb** [microsoft/vscode#102094]
- VSCode Version: 1.47.0
- OS Version: Darwin x64 19.5.0

Steps to Reproduce:

1. run `yarn ng g lib <lib-name>` in terminal
2. select stylesheet 
3. error **Cannot read property 'paths' of undefined** occurs 

Does this issue occur when all extensions are disabled?: Yes

This issue is basically independent from VS Code itself but occurred directly after updating to the current release. 
I tried the command right before the update and it worked.
<img width="607" alt="Bildschirmfoto 2020-07-10 um 12 20 40" src="https://user-images.githubusercontent.com/24405448/87144479-1886c080-c2a8-11ea-8a2e-0110ad6663eb.png">
<img width="403" alt="Bildschirmfoto 2020-07-10 um 12 22 26" src="https://user-images.githubusercontent.com/24405448/87144483-19b7ed80-c2a8-11ea-8495-fe53ceac959e.png">

**Comment by bpasero** [comment]
I have a feeling this is not related to VSCode, isn't this an error from the execution of that command? How would that be Code related?

**Comment by vateseeb** [comment]
The error itself isn't Code related but it seems like the code update caused this error somehow. It was just strange that in the one moment the command works as expected and by only performing the Code update the command is broken. 
Have there been any global changes or changes to the environment with the current release?

**Comment by Tyriar** [comment]
The only changes I can think of to the terminal were improvements to links and improving launch errors (should not impact the environment). Maybe try downgrading to the previous version to diff the environment?

**Comment by IllusionMH** [comment]
Could it be because of "broken" NODE_OPTIONS in built-in terminal e.g. #102096 (but these are for debug, now sure if enabled for regular terminal)

**Comment by Tyriar** [comment]
Ping @connor4312

**Comment by connor4312** [comment]
This doesn't _look_ like it's js-debug related, but maybe.

Does the error happen if you set auto attach to disabled and reload the window?

**Comment by vateseeb** [comment]
I also don't think so. If it is related to the Code Update, it has to be something with a change in the environment or so. The command also doesn't work in the standard Mac Terminal. I tested it also on a Windows 10 machine. Also broken command after update. Also in the integrated terminal as well as in the standard.

**Comment by connor4312** [comment]
Okay. If it's happening in the standard terminal, that's definitely outside the bounds of js-debug, and probably outside the bounds of VS Code as well. I'd recommend searching for or filing an issue on Angular with the problem you're facing.

**Comment by Tyriar** [comment]
> Also in the integrated terminal as well as in the standard.

Yes this cannot be related to VS Code, it must have just been a coincidence it happened around our update time (maybe because VS Code was on a pretty old environment?).
