### ISSUE TITLE
Terminal won't run when vscode is opened using "code ." from command prompt

### ISSUE THREAD

**Issue by cnemri** [microsoft/vscode#102004]
- VSCode Version: 1.46.1
- OS Version: Ubuntu 18.04 LTS

Steps to Reproduce:

1. Open folder in vscode using `code .` within terminal instead of right click on desired folder.
2. Opening a terminal within vscode

The terminal prompt is freezed and won't work. Please see attachement.
When vscode is opened using right click on folder. Terminal works properly.

![image](https://user-images.githubusercontent.com/8223469/87056622-2a178c00-c206-11ea-9a76-72ec12fcfeea.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/76542

Remove the `terminal.integrated.inheritEnv` setting to fix this.
