### ISSUE TITLE
No matching version found for @types/vscode@^1.47.0

### ISSUE THREAD

**Issue by ShPelles** [microsoft/vscode#102045]
- VSCode Version: 1.47.0
- OS Version: win 10

Steps to Reproduce:

1. Update VS Code to latest version (1.47.0)
2. Run `yo code` to generate a new extension
3. run `npm i` and you got an error: `No matching version found for @types/vscode@^1.47.0`

Does this issue occur when all extensions are disabled?: Irrelevant

**Comment by eamodio** [comment]
We ran into a minor snafu with the types release and will get it published shortly.

**Comment by eamodio** [comment]
It should be published now -- sorry for the inconvenience
