### ISSUE TITLE
[Minor] The Explorer hierarchy is a bit confusing

### ISSUE THREAD

**Issue by manibharathytu** [microsoft/vscode#102025]
https://i.imgur.com/bOPrCMb.png

In this image, on a glance it looks like a.js is under b folder. Though the icons of both are starting at the same point in x axis, and the line from the b folder arrow ends with the file before a.js, still it looks that way. Its very eye straining to differentiate the hierarcy level. 

Possible reasons I see :

- It is because of the less indentation (half the icon width) for every level.
- The arrow (expandable/collapsible) starting before the a.js

Possible solutions :

- More indentation (icon full width) - An option for adjusting indentation.
- The arrow may be removed? - An option for hiding it. 

As the folder icon shows that it is a folder (expandable/ collapsible), what purpose the arrow serve. the folder open and close also seen in the icon (opened folder icon vs normal folder icon). Thus the arrow seems redundant. If the arrow icon is removed, the line running along the children will come under the folder icon itself.

**Comment by gjsjohnmurray** [comment]
Use `workbench.tree.indent` to set the indent.

Try other File Icon Themes.

You may also like to set `"workbench.tree.renderIndentGuides": "always"`

**Comment by isidorn** [comment]
I like solutions proposed by @gjsjohnmurray , thus closing as designed
