### ISSUE TITLE
[SCM] Scroll is interrupted by the "Message" text boxes, which results in poor scroll UX

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode#102079]
**Description**
When scrolling in SCM view, as soon as the cursor comes in contact eith  the "Message" box, the scrolling stops.

- VSCode Version: 1.47.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a workspace that has git repos and so many changes that it introduces scroll in the SCM view
2. Open SCM view
3. Try scrolling using mouse wheel or touchpad gesture

Does this issue occur when all extensions are disabled?: Yes

**Comment by ryenus** [comment]
Maybe there could be a way to navigate across the repositories with changes,
similar to the **next/prev** change buttons in a diff view?

**Comment by joaomoreno** [comment]
#102144
