### ISSUE TITLE
Breakpoints are out of sync between Javascript and TypeScript

### ISSUE THREAD

**Issue by Githubber2021** [microsoft/vscode#102016]
- VSCode Version: 1.46.1
- OS Version: Windows Version 1909

**Steps to reproduce:**
1) Clone this HelloWorld [example](https://github.com/Githubber2021/vscode-102016-bug)
2) npm i
3) Open a command prompt and enter: `npm run electron:serve-tsc` and `ng serve` let it run in the background
4) Go into VSCode and set a breakpoint [here](https://github.com/Githubber2021/vscode-102016-bug/blob/master/src/app/home/home.component.ts#L12)
5) Switch in the Debugger to: Electron: All 
![image](https://user-images.githubusercontent.com/57302913/87079734-7eb20b80-c1f4-11ea-90aa-cb3beede0ec3.png)

6) Start the debugger, the breakpoint is not resolved nor hit

**Background info**

I used a simple [Hello World](https://github.com/maximegris/angular-electron) boilerplate example and added the `launch.json` from the [vscode-receipes](https://github.com/Microsoft/vscode-recipes/tree/master/Electron) repo, see below. Inside the app the inspector seems to display the `TypeScript` file, and a breakpoint is hit correctly. In VSCode itself, the breakpoint is represented here:

![image](https://user-images.githubusercontent.com/57302913/87076275-87541300-c1ef-11ea-9e7c-6bb4651b3682.png)

In VSCode itself, when I set the breakpoint, this is what I get:
![image](https://user-images.githubusercontent.com/57302913/87076613-fdf11080-c1ef-11ea-8721-0c21e3fad9f8.png)

***launch.json***
```
{
  // https://github.com/Microsoft/vscode-recipes/tree/master/Electron
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Electron: Main",
      "protocol": "inspector",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "runtimeArgs": [
        "--serve",
        ".",
        "--remote-debugging-port=9223", "."],
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
      }
    },
    {
      "name": "Electron: Renderer",
      "type": "chrome",
      "request": "attach",
      "port": 9223,
      "webRoot": "${workspaceRoot}",
      "timeout": 30000
    }
  ],
  "compounds": [
    {
      "name": "Electron: All",
      "configurations": ["Electron: Main", "Electron: Renderer"]
    }
  ]
}
```

**Comment by connor4312** [comment]
Thanks for the issue! Unfortunately I wasn't able to reproduce it using the instructions provided.

Can you do the following to capture a trace log for us?

1. Add "trace: true" to the chrome attach configuration
1. Reproduce the issue (F5 and wait until the app loads to be certain we missed the breakpoint)
1. Share the log file for the session. Its location will be printed to the Debug Console of the renderer debug session

![](https://memes.peet.io/img/20-07-f12ba61d-953c-4983-82e9-d7b3eb0b40bd.png)

/needsMoreInfo

**Comment by bromix** [comment]
I've the same setup (Electron) and breakpoints aren't working anymore.

**Comment by connor4312** [comment]
@bromix can you share a log file using the instructions I posted above?

**Comment by bromix** [comment]
@connor4312 sure. vscode-debugadapter-2 is the renderer and ...-3 is the main process of electron. Let me know if you need something else and thanks.
[vscode-debugadapter-2.json.gz](https://github.com/microsoft/vscode/files/4912778/vscode-debugadapter-2.json.gz)
[vscode-debugadapter-3.json.gz](https://github.com/microsoft/vscode/files/4912779/vscode-debugadapter-3.json.gz)

**Comment by bromix** [comment]
@connor4312 one more information:
https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/80#issuecomment-572066368
This is the complete setup with launch.json and task.json to debug a vue app via vue cli with electron in vscode. This worked for me till v1.47.X

**Comment by connor4312** [comment]
@bromix thanks, looks like the generation of the `urlFilter` regex is different than the old debugger. You should be able to fix this by setting it to `localhost:*` instead of `http://localhost:*`. I'll put in a fix for parity today.

**Comment by bromix** [comment]
@connor4312 you're right. It works! Thanks a lot for the help.
