### ISSUE TITLE
Css isn't working 

### ISSUE THREAD

**Issue by Roobetterbeliveit** [microsoft/vscode#102017]
Issue Type: <b>Bug</b>

my css isn't working at all ,even though i've coded it properly, no matter what styles i try nothing happens, i've tried the same thing on three different css files with the same results;also my live server isn't working at all

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.80GB (12.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|5.1.3
indent-rainbow|ode|7.4.0
LiveServer|rit|5.6.1
highlight-matching-tag|vin|0.9.9

</details>

**Comment by Ashikpaul** [comment]
This doesn't look like an issue with vscode.

**Comment by Roobetterbeliveit** [comment]
it seems i'm only getting issues with one folder.

Regards

**Comment by aeschli** [comment]
Can you describe what is not working? The css editing? Can you make a simple sample that show the problem?

**Comment by Roobetterbeliveit** [comment]
None of my css styles are showing up, but so far the issue seems to be
with this one project and not the others.
I've attached a print screen of the css file and the html code linking the
css file.

Regards

**Comment by aeschli** [comment]
Sorry, I don't see the screenshot.
