### ISSUE TITLE
ISO-2022-JP (Japanese) support

### ISSUE THREAD

**Issue by knok** [microsoft/vscode#102071]
This is similar about the following issue:
https://github.com/microsoft/vscode/issues/94518

ISO-2022-JP is ancient encoding using 7-bit only, but some applications still support it (including google chrome and chromium).
I hope to support the encoding for Japanese users.

**Comment by bpasero** [comment]
Upstream dependency: https://github.com/ashtuchkin/iconv-lite/issues/60

**Comment by bpasero** [comment]
Since this issue has a linked upstream issue referenced, I am going ahead to close this issue as part of our issue grooming effort: https://github.com/microsoft/vscode/wiki/Issue-Grooming
