### ISSUE TITLE
Please improve configuration of the debugger extensions

### ISSUE THREAD

**Issue by cheery** [Microsoft/vscode#10209]
I am lacking options how to setup a debugger for my programming language.

My language has a standalone runtime the developer should be able to place anywhere. I would like the user to set a configuration variable to point out where the runtime is.

Here's an example of such configuration (I will soon pump the whole code up into cheery/vscode-lever):

```
"configuration": {
  "type": "object",
  "title": "Lever tools configuration",
  "properties": {
    "lever.runtime_path": {
      "type": "string",
      "default": "c:\\lever",
      "description": "The folder path to the runtime this editor should use during debugging lever applications."
    }
  }
}
```

I've setup my debugger like this in package.json:

```
"debuggers": [
  {
    "type": "lever",
    "label": "Lever Debugger",
    "enableBreakpointsFor": {
      "languageIds": [
        "lever"
      ]
    },
    "program": "debug.js",
    "runtime": "node",
    "args": [],
    "variables": {
      "getLeverRuntimePath": "extension.getLeverRuntimePath"
    },
    "initialConfigurations": [
      {
        "name": "Lever-Run",
        "type": "lever",
        "request": "launch",
        "program": "${workspaceRoot}/main.lc",
        "lever_path": "${command.getLeverRuntimePath}",
        "stopOnEntry": false
      },
      {
        "name": "Lever-Debug",
        "type": "lever",
        "request": "launch",
        "program": "${workspaceRoot}/main.lc",
        "lever_path": "${command.getLeverRuntimePath}",
        "stopOnEntry": true
      }
    ],
    "configurationAttributes": {
      "program": {
        "type": "string",
        "description": "Workspace relative path to script to run",
        "default": "${workspaceRoot}/main.lc"
      },
      "stopOnEntry": {
        "type": "boolean",
        "description": "Automatically stop after launch.",
        "default": true
      },
      "lever_path": {
        "type": "string",
        "description": "Path to lever's configuration file",
        "default": "${command.getLeverRuntimePath}"
      }
    }
  }
],
```

The problems in this kind of configuration is that the user has to define "lever_path" -variable in their launch.json. I also get the runtime path only after the debugger has officially gone up. This means that I am unable to program my native runtime to fetch debug routine from lib/debugger.lc

Therefore I am forced to implement the debugging API via a node script. This problem prevents me from implementing debugging interfaces of the vscode within my language, and will prevent the spread of this debugging API.

I would prefer to get my config variable lever.runtime_path in environment variable, I tried to set it in extension.js with process.env.LEVER_PATH = vscode.workspace.getConfiguration("lever").get("runtime_path") without success.

(I am also unable to obtain a directory open dialog, so that I could assist the user to fill the configuration option when starting my tool, but I am not sure if that's a feature)

**Comment by weinand** [comment]
You can use the `adapterExecutableCommand` contribution point to let your debugger extension return the executable path of your debug adapter. See
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesdebuggers

Since the implementation of the `adapterExecutableCommand` lives in the debugger extension it has access to the user settings (e.g. your "lever.runtime_path") and it can prompt the user if "lever.runtime_path" is missing.
