### ISSUE TITLE
Suggest status bar screen cheese

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#102089]
* enable suggest status bar
* sometimes you get this 🔽  

<img width="1017" alt="Screenshot 2020-07-10 at 10 59 42" src="https://user-images.githubusercontent.com/1794099/87141507-6d740800-c2a3-11ea-9985-5f0ac0403e94.png">

**Comment by connor4312** [comment]
I haven't used the suggest status bar, so I haved turned the setting on and will remove the verified marker if I encounter the "sometimes" over the course of endgame
