### ISSUE TITLE
Debug nestjs apps (--inspect-brk issue)

### ISSUE THREAD

**Issue by anthowm** [microsoft/vscode#102077]
- VSCode Version: 1.47.0
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.6.0

Steps to Reproduce:
VS update this morning automatically and the problem start when I try to debug my nestjs app my problem is this one https://github.com/microsoft/vscode/issues/102063, I see that there alot of new issues related to the new debugger because it not accept --inspect-brk. 
In nestjs all come out of the box so I just run a command that come with it for debug npm run start:debug

package.json
```
"start:debug": "nodemon --config nodemon-debug.json",
```
nodemon-debug.json
```
{
  "watch": ["src"],
  "ext": "ts",
  "ignore": ["src/**/*.spec.ts"],
  "exec": "node --inspect-brk -r ts-node/register -r tsconfig-paths/register src/main.ts"
}
```
I try this because I read this comment but it not work or maybe need a different config
https://github.com/microsoft/vscode/issues/99526#issuecomment-640771550. If you can help with this @connor4312 thanks
task.json
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "start:debug",
      "problemMatcher": ["$tsc"], // since you mentioned TypeScript
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}

```
launch.json
```
{
  "type": "pwa-node",
  "request": "launch",
  "name": "Programm ausführen (Debug)",
  "program": "${workspaceFolder}/src/main.ts", // or your 'main' file
  "stopOnEntry": true,
  "preLaunchTask": "npm: start:debug" // run the build script before our main program:
}
```
Execute the task with comand + shift + B and still not working

Does this issue occur when all extensions are disabled?: Yes

**Comment by drwharris** [comment]
Ive got a similar issue. I have TS code that forks another TS file and I could debug with --inspect-brk perfectly. Since upgrading to 1.47 its broken. 

Can confirm that downgrading to 1.46.1 fixes the issue.

**Comment by connor4312** [comment]
Thanks for the issue! This is the same as https://github.com/microsoft/vscode/issues/99526#issuecomment-640771550

/duplicate

**Comment by anthowm** [comment]
@connor4312 I try it and still not working ...

**Comment by qLimAxzU16** [comment]
I'm facing the same issue. I'm using this workaround until the issue is fixed.

1. Run ``npm run start:debug`` in a seperate terminal outside of vs code
2. Go to debug window in VS code, add ``"Node.js: Attach"``

Though this doesn't reattach to the process if we do any changes. It's manual and painful.

**Comment by connor4312** [comment]
@qLimAxzU16 the recommended way is to use `stopOnEntry`. For example in this case his configuration turns into

```
"start:debug": "nodemon --config nodemon-debug.json",
```

turns into

```
{
  "type": "pwa-node",
  "request": "launch",
  "name": "Launch Nodemon)",
  "runtimeExecutable": "npm",
  "args": ["run", "start:debug"],
  "stopOnEntry": "${workspaceFolder}/src/main.ts", // stop in this file
}
```

**Comment by connor4312** [comment]
Followup: working on a better 'automatic' fix for this that should require no changes

**Comment by connor4312** [comment]
Hi, following up on this issue after feedback from you and other users. There are two things to know:

1. If you don't need to debug on the first line of your program, it's actually safe to just remove `--inspect-brk` from your npm scripts with the new debugger. Previously, it was useful to prevent your program from running before VS Code could attach to it, but this is no longer necessary.

1. We've added some change to gracefully fall back (with a warning) when running a program with --inspect-brk in the config. This flag prevents us from being able to attach to children and unlock some additional new functionality, but it should work. This change will be available in the recovery release coming next week, and is available on our [nightly extension](https://github.com/microsoft/vscode-js-debug/#nightly-extension).

Happy Coding!
