### ISSUE TITLE
SCM pannel needs a better interactivity

### ISSUE THREAD

**Issue by wolfsilver** [microsoft/vscode#102128]
If there are two repos in one workspace with a same submodule. 
```
git_repo_a
 |_ submodule_c

git_repo_b
 |_ submodule_c
```

Source control panel looks like 
```
git_repo_a
git_repo_b
submodule_c
submodule_c
```

I wish it looks like this kind.
```
git_repo_a
|_ submodule_c
git_repo_b
|_ submodule_c
```

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/101859

**Comment by Awbmilne** [comment]
Duplicated in #101859, PLEASE UPVOTE IT THERE!
