### ISSUE TITLE
Debug protocol: `setVariable` identifies variables by display name

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#10219]
- VSCode Version: 1.4
- OS Version: All

The new `setVariable` request identifies variables by display name.  
This is fragile because the name may have been generated by the adapter (e.g. `[N]` for array indices). 
There may also be more than one variable with the same name in the stack frame in languages that allow variable shadowing.  For example, in C++ one can write 
```c++
int a = 10; 
{ 
    int a = 20;
    ... // There are now two `a`'s here! 
```
The debugger can see both, even though in C++ there's no way to access the outer one.

To make this work robustly, I would suggest adding an optional "handle" field into `Variable`, which gets round-tripped back to the adapter in `setVariable`.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-debugadapter-node#54
