### ISSUE TITLE
Terminal does not work

### ISSUE THREAD

**Issue by caponetto** [microsoft/vscode#102126]
- VSCode Version: 1.47.0
- OS Version: Fedora 32

Steps to Reproduce:

1. Open VS Code **from Applications**
2. Go to Terminal -> New terminal
3. The terminal does not seem to be properly loaded. See screenshot.

Does this issue occur when all extensions are disabled?: Yes

Additional information:

The terminal works fine when I start VS Code via command line.

Screenshot:

![Screenshot from 2020-07-10 11-05-19](https://user-images.githubusercontent.com/638737/87163142-46b2d300-c29d-11ea-9565-4250db906596.png)

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/76542

Remove the `terminal.integrated.inheritEnv` setting to fix this.
