### ISSUE TITLE
Remember last window state

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#10213]
- VSCode Version: 1.4.0
- OS Version: Fedora 24, Xfce4 desktop

Steps to Reproduce:

1. Open VSCode.
2. Maximize the window (not full screen).
3. Close VSCode.
4. Open VSCode, now it defaults to some predefined size.

---

Would you please add option to remember last window size?

I can do that partially with full screen + restore full screen on. However my Xfc4 desktop shows a small top right panel for current time (similar to Windows task bar). If I make the window full screen, that panel is covered (stayed behind the window).

Thanks,

**Comment by bpasero** [comment]
We should preserve the window dimensions, can you see if sizing the window into a specific state and closing/reopen brings it back?

**Comment by haibison** [comment]
Thanks, it does remember all dimensions and positions in normal state. It only reverts back to default dimension/position when I close it in maximized state and re-open it.

It's not a big deal, I can always maximize the window on startup by some shortcut.

Thanks for your hard work  `:-)`

**Comment by bpasero** [comment]
This sounds like an upstream issue with Electron and the Linux distribution you are using. Or maybe an issue with the window manager within.

**Comment by bpasero** [comment]
Assuming this is a distro issue or Electron issue and we recently updated Electron.

**Comment by me0262** [comment]
I want to revisit this bug, as I'm running Windows 10, have my window height-maximized, and when it's closed down and re-opened, it's in the right position, but not height-maximized.
