### ISSUE TITLE
Using version 1.47.0, breakpoint can't be bound

### ISSUE THREAD

**Issue by urapico** [microsoft/vscode#102197]
- VSCode Version: 1.47.0
- OS Version: MacOS 10.15.5
- node version: v10.21.0

Steps to Reproduce:

1. To execute node project with debugger.
2. To make breakpoint but it is unbound.

*It is no problem at version 1.46.1. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mamadoo** [comment]
I have same issue.

**Comment by connor4312** [comment]
Can you collect a trace log using these instructions?

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

/needsMoreInfo

**Comment by gparvind** [comment]
Simple node app debugging was working fine. After vscode upgrade to 1.47 on Ubuntu, debugging broke. App starts in debug mode but not breaking on any breakpoints. Breakpoints are greyed out and shows its unbounded.

**Comment by AlexisMunera98** [comment]
Same problem using:
- Windows: 10.0.18363.900
- VSCode: 1.47.0

**Comment by connor4312** [comment]
If you're using Node 8, please see: https://github.com/microsoft/vscode/issues/102166#issuecomment-657138385

Otherwise, please collect a trace log using the instructions above. Thanks!

**Comment by Abhishek-Singh07** [comment]
I have same issue with vscode version 1.47.0. 
When execute the node project with debugger.

Debugger works fine when run on vscode 1.46.1 version

**Comment by Revo86** [comment]
Temporarily add "`debug.javascript.usePreview": false` to settings.json

**Comment by Squashy83** [comment]
same situation here:

**Comment by connor4312** [comment]
@Abhishek-Singh07 @Squashy83 please try these instructions and let me know if it fixes it https://github.com/microsoft/vscode/issues/102166#issuecomment-657138385

Otherwise, please collect a trace log using the instructions above. Thanks!

**Comment by urapico** [comment]
@connor4312 I did these instructions https://github.com/microsoft/vscode/issues/102166#issuecomment-657138385 you said.
And my debugger has became fine.
Thanks!

**Comment by alexstolrcoti** [comment]
same issue

**Comment by connor4312** [comment]
@alexstolrcoti please try these instructions and let me know if it fixes it https://github.com/microsoft/vscode/issues/102166#issuecomment-657138385

Otherwise, please collect a trace log using the instructions above. Thanks!

**Comment by connor4312** [comment]
A fix for the Node 8 issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!

**Comment by gparvind** [comment]
The issue still exists for me with 1.47.2

**Comment by connor4312** [comment]
@gparvind please collect a trace log using the instructions above. Thanks!

**Comment by urapico** [comment]
@connor4312 I've resolved the issue by https://github.com/microsoft/vscode/issues/102166#issuecomment-657138385. :tada:
Thank you.
