### ISSUE TITLE
i cant start up the vscode-oss-dev i get soo many errors 

### ISSUE THREAD

**Issue by Duui3111** [microsoft/vscode#102160]
so this is what i do 
``git clone https://github.com/<<<your-github-account>>>/vscode.git``
``cd vscode``
``.\scripts\code.bat`` and this is where i get so many errors 
there is the list of errors 
```Error: Cannot find module 'gulp-filter'``` 
```Error: Cannot find module 'event-stream'```
``error Command failed with exit code 1.`` 

and when i do 
``yarn web`` 
i get this 
``Error: Cannot find module 'opn'`` 
but i have installed this nd did not fix the errors 
``` npm install open```
``npm install --global opn``

and i have tryed to do this with vscode 
but i get unable to connect to localhost:port 
and i tried to build

**Comment by gjsjohnmurray** [comment]
Did you use the instructions at https://github.com/microsoft/vscode/wiki/How-to-Contribute ?

**Comment by Duui3111** [comment]
yes, i have did everything it says to do

**Comment by gjsjohnmurray** [comment]
You didn't mention doing this step:
![image](https://user-images.githubusercontent.com/6726799/87193370-7939eb80-c2f0-11ea-9fef-0b5c70606e5d.png)
