### ISSUE TITLE
Restore Tree View Toggle Button

### ISSUE THREAD

**Issue by tomblind** [microsoft/vscode#102138]
As noted in #102041, the tree view toggle in the source control view has been removed in favor of a context sub-menu. Please consider bringing this button back as I switch frequently between both views when I'm selecting changes to stage. Now the process much more tedious as it requires 3 clicks instead of just 1.

**Comment by joaomoreno** [comment]
Duplicates:

- https://github.com/microsoft/vscode/issues/102041
- https://github.com/microsoft/vscode/issues/102068

**Comment by joaomoreno** [comment]
@lszomoru @misolori Thoughts?

**Comment by misolori** [comment]
This one is tough because there are other options in the View/Sort menu, so if you add one you need to add the others:

![image](https://user-images.githubusercontent.com/35271042/87391223-2fa30800-c55f-11ea-9a59-fd777d5d9ba3.png)

I wonder if we could introduce this as a command so that users can apply a keybinding instead of an icon? The icon is more visible but the view already has several other actions so it would add to visual noise.

**Comment by joaomoreno** [comment]
I do think this is the classic "I'm used to it" friction. A keybinding would definitely help, maybe we just do that.

**Comment by tomblind** [comment]
I won't argue that it's something I was used to. I didn't even realize how much I was using it until I lost it. But every time I do a complex commit now, I pine for that button again as I'm clicking through the menu repeatedly. I don't use sorting options as often (almost never), but I do use the view toggle daily. I would put forth the case that UI is best organized around most commonly used features.

**Comment by usernamehw** [comment]
@joaomoreno Is it possible to contribute icon to SCM view at the same place where it was from an extension?

**Comment by InExtremaRes** [comment]
Same here. I change between list and tree _a lot_ so even a shortcut is slower than just have the icon over there. The other options are far less common (for me at least). I appreciate if you consider bringing it back.

**Comment by tomblind** [comment]
@usernamehw I started playing with creating an extension, but without a public command there's no way to actually change the view mode.

@joaomoreno is there something I am missing that might allow this? If not, can we get a command added as you mentioned before?

**Comment by hamzahamidi** [comment]
Why was the Tree View Toggle Button hidden ?
