### ISSUE TITLE
Option to disable instead of completely uninstall a particular extension.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#10216]
- VSCode Version: Code - Insiders 1.5.0-insider (1a7ca5a77bf6b63951e499ea93b7316d36118ade, 2016-08-05T07:19:53.669Z)
- OS Version: Windows_NT ia32 10.0.14393

I would like to be able to temporarily disable an extension without having to uninstall it entirely.

**Comment by joaomoreno** [comment]
#2882
