### ISSUE TITLE
Creating files will add 2 times BOM (UTF-8, 16)

### ISSUE THREAD

**Issue by nurozhikun** [microsoft/vscode#102103]
Issue Type: <b>Bug</b>

with  file encoding  default: utf8bom;
there will be double 'EF BB BF' bytes in the header;
the 6 bytes in the file header will be 'EF BB BF EF BB BF'

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.67GB free)|
|Process Argv|--folder-uri file:///d%3A/works/cppcode|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio|eig|1.0.3
cpptools|ms-|0.29.0-insiders2
powershell|ms-|2020.6.0
korofileheader|OBK|4.7.2
tabnine-vscode|Tab|2.8.8
vscode-icons|vsc|10.1.1
material-theme|zhu|3.8.3

</details>

**Comment by bpasero** [comment]
**Verification:**
* configure files.encoding to be UTF-8 with BOM
* from the file explorer create a new file
* the file should appear empty and should have 3 bytes in them (check with a HEX editor extension)
