### ISSUE TITLE
Running `code -a .` activates the debugger and hangs without completing

### ISSUE THREAD

**Issue by chasingSublimity** [microsoft/vscode#102186]
Issue Type: <b>Bug</b>

Hi there. I'm seeing some weird behavior after updating VS Code. When i run `code -a .` (as well as some other shell commands), the debugger activates and the prompt hangs without ever finishing. Is this expected?

Here's an image, a text representation is provided below.
<img width="766" alt="image" src="https://user-images.githubusercontent.com/21029639/87214062-54914400-c2ef-11ea-8ef3-68f54bdcdf6c.png">

```
➜  fastify git:(Add-missing-type) code -a .
Debugger listening on ws://127.0.0.1:54892/33ce4ff3-60e3-4dda-940b-50ff95213cd1
For help, see: https://nodejs.org/en/docs/inspector
```

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|3.0.10
django-html|bib|1.3.0
django|big|1.0.2
better-toml|bun|0.3.2
gotemplate|cas|0.4.0
vscode-standardjs|che|1.3.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.36.1
vscode-eslint|dba|2.1.6
vscode-quick-select|dba|0.2.8
vscode-deno|den|1.25.0
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
go|gol|0.15.1
npm-dependency-links|her|1.1.0
restructuredtext|lex|128.0.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-cosmosdb|ms-|0.13.0
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
azure-account|ms-|0.8.11
cpptools|ms-|0.28.3
vsliveshare|ms-|1.0.2427
vsliveshare-audio|ms-|0.1.85
debugger-for-chrome|msj|4.12.9
rust|rus|0.7.8
code-settings-sync|Sha|3.4.3
addDocComments|ste|0.0.8
code-spell-checker|str|1.9.0
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.8.0
city-lights-icon-vsc|Yum|1.1.3

(8 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
This is the same as https://github.com/microsoft/vscode/issues/102057. You can avoid this by setting `debug.node.autoAttach: "disabled"`, then reopening the terminal/reloading the window. At that point setting `debug.node.autoAttach: "on"` should work again.
