### ISSUE TITLE
Mocha test cases fail after upgrade to 1.47

### ISSUE THREAD

**Issue by paulgingrich** [microsoft/vscode#102129]
My mocha nodejs test cases fail after upgrading to 1.47.  They fail when launched from the debugger in VSCode, but pass when run at the command line using nodejs.

Here is the launch entry 
{
            "type": "node",
            "request": "launch",
            "name": "Debug Mocha Node Test",
            "cwd": "${workspaceFolder}/designer/v3/components/",
            "program": "${workspaceFolder}/designer/v3/components/node_modules/mocha/bin/_mocha",
            "args": [
                "--no-timeouts",
                "--exit",
                "${workspaceFolder}/designer/v3/components/@ti-NLibs/**/*.spec.js"
            ],
            "stopOnEntry": false
        },

**Comment by connor4312** [comment]
Can you share the output of your tests? What specifically is failing?

/needsMoreInfo

**Comment by paulgingrich** [comment]
The problem is that this code: 
    const mocha_1 = require("mocha");
    mocha_1.describe(...)
throws an exception be cause describe is not defined on mocha_1.  

However this works fine in older versions of VSCode.

I'm guessing that something has changed in the execution environment that is interfering with mocha.

**Comment by connor4312** [comment]
@paulgingrich mocha does not export a `subscribe` function, it's a global function that gets added by the runner. E.g. you can verify this using the node repl, without involving VS Code:

```
PS C:\Users\Connor\Documents\Github\open-ynab> node
Welcome to Node.js v12.14.1.
Type ".help" for more information.
> require('mocha').describe
undefined
```

Based on that import I'm guessing you're using TypeScript and doing something like `import { describe } from  'mocha'`. What you want to do instead is install `@types/mocha`, and then add `"mocha"` to the `"types"` array in your tsconfig.json ([example](https://github.com/connor4312/cockatiel/blob/0cd9c3e5e278bb01bb91d412a4a39541b3ade555/tsconfig.json#L19)). Then TS will recognize that it's available globally.

**Comment by paulgingrich** [comment]
So what does your launch.json look like for mocha tests?  The typeScript stuff is just type safety, it shouldn't effect the test that run.  I'm using the mocha runner to launch the test, same as on the command line outside of VSCode, and I only see the problem in VSCode Version 1.47.
I'm not running this directly form node, it's using the mocha to run node.  Here is my entry in the launch.json

{
"type": "node",
"request": "launch",
"name": "Debug Mocha Node Test",
"cwd": "${workspaceFolder}/designer/v3/components/",
"program": "${workspaceFolder}/designer/v3/components/node_modules/mocha/bin/_mocha",
"args": [
"--no-timeouts",
"--exit",
"${workspaceFolder}/designer/v3/components/@ti-NLibs/**/*.spec.js"
],
"stopOnEntry": false
},
"program": "${workspaceFolder}/designer/v3/components/node_modules/mocha/bin/_mocha",

**Comment by connor4312** [comment]
> The typeScript stuff is just type safety, it shouldn't effect the test that run. 

It sounds like the problem is that you should not be importing `describe` from mocha. It's already a global and is not exported from Mocha.

The launch config you have looks fine. You can take a look at the repo I linked in the example if you want to see my full setup.

**Comment by paulgingrich** [comment]
Ok, I got it working thanks.  Just had to delete all my imports for mocha.   
I do have another issue though that only shows up on 1.47, didn't have a problem on 1.46.
If I add a runtimeExecutable and point to an older version of node (in this case 8.11.4 32-bit), then it looks like the debugger doesn't attach.   It actually gets stuck and there is no "Debugger attached" console message.
