### ISSUE TITLE
CustomTextEditor not detected as activeTextEditor or in onDidChangeActiveTextEditor

### ISSUE THREAD

**Issue by phschaad** [microsoft/vscode#102110]
Issue Type: <b>Bug</b>

When an `onDidChangeActiveTextEditor` event is encountered, if the active text editor is a CustomTextEditor provided via CustomTextEditorProvider, `vscode.window.activeTextEditor` is `undefined`.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19042

**Comment by phschaad** [comment]
Additional observation: When switching back and forth between two CustomTextEditor instances, no `onDidChangeActiveTextEditor` event is fired.

**Comment by mjbvz** [comment]
This is by design. A `CustomTextEditor` is not a [`TextEditor`](https://github.com/microsoft/vscode/blob/fda4c35b27f36b4bd156e84de06f6d5a52d76937/src/vs/vscode.d.ts#L1082). 

More generic view changes events are tracked by #15178
