### ISSUE TITLE
Git: Please show git credential dialog on VSCode window center

### ISSUE THREAD

**Issue by espresso3389** [microsoft/vscode#102143]
When do git-push on left-pane, git credential dialog may be shown on top-center of the VSCode window and it's sometimes an issue if user uses large display. User's eyes are on left-page and they miss the dialog; they don't expect a dialog popup and therefore they don't move their eyes to center-top of the window.

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the git credential dialog?

**Comment by espresso3389** [comment]
When I do git pull/push, VSCode shows the following dialog:

![image](https://user-images.githubusercontent.com/1311400/87250784-518a8500-c4a2-11ea-8f56-523b21e45461.png)

**Comment by joaomoreno** [comment]
Unfortunately since git is an extension, there is no other API than this to prompt the user for a username/password.

Are you using the automatic github authentication?

What version of VS Code are you one?

**Comment by espresso3389** [comment]
I see. I don't need quick fix for this. But I think VSCode should have some API to realize popup input dialog of other style.
Or, for such dialog that user does not expect (at least, I didn't expect the dialog), there should be some other magic to attract user attention.

My VSCode:

Version: 1.48.0-insider (user setup)
Commit: e7920dce7bfd0b707ebfc0a5379c6edd2233e475
Date: 2020-07-10T11:58:37.847Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.20161
