### ISSUE TITLE
Terminal: the cli command entered duplicates in output

### ISSUE THREAD

**Issue by osenvosem** [microsoft/vscode#102107]
- VSCode Version: 1.47.0
- OS Version: MacOS 10.15.5

Steps to Reproduce:

1. install zsh + oh-my-zsh with no plugins
2. Run any bash command in VSCode terminal

Does this issue occur when all extensions are disabled?: Yes

Any cli command in the terminal goes first in the output when zsh+ohmyzsh is used. There is no such behavior with bash or with zsh in any other terminal.

![Screenshot 2020-07-10 at 14 32 30](https://user-images.githubusercontent.com/6762673/87150596-0febb580-c2bb-11ea-9f74-c18c65ee3566.jpg)

**Comment by Tyriar** [comment]
Could you try trace logging to see what is sent by zsh when this happens?

https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by osenvosem** [comment]
@Tyriar there is not `Window` option as in the instruction
![Screenshot 2020-07-10 at 15 38 15](https://user-images.githubusercontent.com/6762673/87155335-74ab0e00-c2c3-11ea-985f-2ef9e6bc05ec.jpg)

**Comment by Tyriar** [comment]
Well that seems like a problem 😕, created https://github.com/microsoft/vscode/issues/102117

**Comment by Tyriar** [comment]
@osenvosem reloading the window should get the log channel to show up

**Comment by osenvosem** [comment]
@Tyriar here you go

[renderer1.log](https://github.com/microsoft/vscode/files/4903358/renderer1.log)

**Comment by Tyriar** [comment]
@osenvosem opps, you actually need to do escape sequence logging 🤦 https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by osenvosem** [comment]
@Tyriar [renderer1.log](https://github.com/microsoft/vscode/files/4903587/renderer1.log)

**Comment by Tyriar** [comment]
@osenvosem that one logs to chromium dev tools (access via Help menu)

**Comment by osenvosem** [comment]
@Tyriar OK 
[log.txt](https://github.com/microsoft/vscode/files/4903858/log.txt)

**Comment by Tyriar** [comment]
Here's the relevant part:

```
sending data "l" Array(1)
log.ts:173 TRACE IPty#write 1 characters
parsing data [32ml[39m[90ma[39m
sending data "s" Array(1)
log.ts:173 TRACE IPty#write 1 characters
parsing data [32ml[32ms[39m[90m -la[39m
sending data " " Array(1)
log.ts:173 TRACE IPty#write 1 characters
parsing data [39m 
sending data "-" Array(1)
log.ts:173 TRACE IPty#write 1 characters
parsing data [39m-
sending data "l" Array(1)
log.ts:173 TRACE IPty#write 1 characters
parsing data [39ml
sending data "a" Array(1)
log.ts:173 TRACE IPty#write 1 characters
parsing data [39ma
sending data "
" Array(1)
log.ts:173 TRACE IPty#write 1 characters
parsing data [?1l>
Switching back to normal keypad.
parsing data [?2004l


parsing data kls\
Unknown ESC code:  Object
parsing data total 704
```

This says that it is indeed zsh sending back `ls`, it might be something with VS Code's environment triggering this but this log verifies it's not bad rendering or anything.

- `sending data "\n" Array(1)`: Press enter
- `parsing data [?1l>`: Enable "Normal Cursor Keys" and Enter VT100 mode
- `Switching back to normal keypad.`
- `parsing data [?2004l`: Enter bracketed paste mode
- `parsing data kls\: Erase all chars to the right and **print "ls"**
- `parsing data total 704`: Print "total 704"

If you want to look more into it, using the trace mode you uses before, that will give you the full environment, the shell exe and args used to launch it.

**Comment by osenvosem** [comment]
@Tyriar the thing is this happens only in VSCode terminal, in iTerm or Alacritty all is fine.
![Screenshot 2020-07-10 at 18 52 41](https://user-images.githubusercontent.com/6762673/87173625-b7c6aa80-c2de-11ea-9ce7-cbad0e6ef459.jpg)
![Screenshot 2020-07-10 at 18 52 26](https://user-images.githubusercontent.com/6762673/87173628-b9906e00-c2de-11ea-848a-d850217bab2b.jpg)

**Comment by Tyriar** [comment]
Does changing `terminal.integrated,shellArgs.osx` to/from `[]` and `["-l"]` help?

**Comment by osenvosem** [comment]
@Tyriar I actually just find a solution, one needs to add `DISABLE_AUTO_TITLE="true" to zsh config.

Thank you for helping. 🙂

**Comment by Tyriar** [comment]
@osenvosem Good to know, not sure what zsh is trying.

@jerch any idea what zsh is trying to do here? It's sending back `ls` followed by `ST` (ESC \).

**Comment by jerch** [comment]
@Tyriar Oh well, `ESC k <some_text> ESC \` is a custom sequence of `screen` to update the internal title of a running terminal in screen. This is a really bad one - it is not officially spec'ed anywhere and even more - it is incompatible to ECMA-35/48.

Not sure why zsh is sending it at all, maybe the `TERM` var wrongly contains some screen derivate?

**Comment by Tyriar** [comment]
@jerch you're a legend for knowing this 😛 I see it's _not_ disabled by default which is unexpected, but I can't seem to reproduce the issue anyway.

@osenvosem can you run `echo $TERM` and paste in the result?

**Comment by osenvosem** [comment]
@Tyriar yep, here you go: `screen-256color`

**Comment by jerch** [comment]
@osenvosem Any clue, where the `screen-*` comes from? Do you forward some `screen` session into the vscode terminal? Note that with normal screen usage within another terminal those sequences should not get exposed to the outer terminal, as screen would handle them internally already.
If in doubt try setting TERM to `xterm-256color`.

**Comment by osenvosem** [comment]
@jerch it was overridden in my zsh config, the value was "screen-256color". That was needed in order to Alacritty + tmux + neovim work consistently with colors. I know that override `$TERM` in shell config is a bad idea. I found another way and removed it.

**Comment by Tyriar** [comment]
Oh ok, well that was the issue then. Since `$TERM` said it was screen, zsh treated it as such with screen-specific sequences that xterm.js doesn't know how to handle.
