### ISSUE TITLE
[SCM] Some Opinions/Pain Points of the New UI

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode#102104]
- VSCode Version: 1.47.0
- OS Version: Windows 10

**I would say that new UI for SCM is worse. Some pain points:**

- Users have to scroll to see the changes in a particular repo. Scrolling to find anything is very hard. always.
- Users have to scroll to perform any action (Write commit message, stage, commit etc)
- Users have to collapse each and every repo's changes to see all the repos in the current workspace.
- New UI is very clumsy as the repo title and changes are combined and only way to differentiate them is by their font-weight
- It has become way harder to see the number of changes as the action icons in front of each branch now require us to sacrifice the editor space to see them
- Because of the the new "commit" icon, the repo name and/or the branch name is hidden
- The branch info such as number of un-pushed commits, un-pulled changes, whether the current branch has been published or not, etc.  are not visible now. (I know, there is status bar. But, it is an extra step to remember to look at the status bar)

Additionally, it causes this issue also: https://github.com/microsoft/vscode/issues/102079

This UI, according to the release notes, is supposed to be more flexible in terms of moving views. But, IMO, these cons outweigh this. 

I would request to at least keep this view as optional and let us switch between the new - old UI, while the team works on improving the new UI.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
>     * It has become way harder to see the number of changes.

Maybe try the `scm.providerCountBadge` setting.

See also #101103 for discussions from when these changes first landed in [Insiders](https://code.visualstudio.com/insiders/).

**Comment by gjsjohnmurray** [comment]
cc @joaomoreno

**Comment by LeonnardoVerol** [comment]
I believe "scm.alwaysShowProviders" should be brought back due do User Usability

**Comment by igoramadas** [comment]
Another discussion going on: #102118

**Comment by joaomoreno** [comment]
@stagefright5 I hope you don't mind that I've moved your comments over here: https://github.com/microsoft/vscode/issues/102118

**Comment by stagefright5** [comment]
> @stagefright5 I hope you don't mind that I've moved your comments over here: https://github.com/microsoft/vscode/issues/102118

Yep. No problem.
