### ISSUE TITLE
Não encontra o caminho de INCLUDE

### ISSUE THREAD

**Issue by CarlosNL2019** [microsoft/vscode#102115]
Issue Type: <b>Bug</b>

Bom dia,

Após atualização para versão 1.47, ao compilar um fonte (ADVPL-Protheus), apresenta o erro abaixo:
C2090 File not found PRTOFDEF.CH appre [1,1]
Só que esse arquivo se encontra na pasta de INCLUDE.
Até ontem quando estava na versão anterior, trabalhei normalmente e ao sair do vsCode, teve esse nova atualização.
E quando foi hoje, começou a dar esse problema.
Como reverter para a versão anterior?

Att.,

Carlos Lima.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ja|MS-|1.47.3
vscode-language-pack-pt-BR|MS-|1.47.3
material-icon-theme|PKi|4.2.0
html5-boilerplate|sid|1.0.3
tds-vscode|TOT|1.0.5

</details>

**Comment by bpasero** [comment]
Please report this issue in english again.

**Comment by CarlosNL2019** [comment]
Benjamin,

This question already solved.
Problem with totvs developer studio extension plugin.

Best regards,

Carlos Lima.

Em sáb., 11 de jul. de 2020 às 02:09, Benjamin Pasero <
notifications@github.com> escreveu:
