### ISSUE TITLE
First line of terminal is clipped after zooming twice

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#102194]
Issue Type: <b>Bug</b>

**Repro**
1. With integrated terminal
1. Zoom in twice 

**Bug**
The first line of the terminal is clipped:

<img width="896" alt="Screen Shot 2020-07-10 at 9 57 38 PM" src="https://user-images.githubusercontent.com/12821956/87216884-996da880-c2f8-11ea-9ef7-60a233b6ea68.png">

VS Code version: Code - Insiders 1.48.0-insider (e7920dce7bfd0b707ebfc0a5379c6edd2233e475, 2020-07-10T11:55:11.286Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|15%|
</details>

**Comment by mjbvz** [comment]
Possibly a duplicate of #101342

**Comment by meganrogge** [comment]
![recording (27)](https://user-images.githubusercontent.com/29464607/98176850-35c24900-1eae-11eb-842c-555dbb3e0a3d.gif)

not seeing this.

**Comment by meganrogge** [comment]
tried this on my personal computer (a mac) and am able to reproduce this issue.

**Comment by jeanp413** [comment]
Created a PR #115907 that depends on https://github.com/xtermjs/xterm.js/pull/3243 fixing this

**Comment by connor4312** [comment]
I don't repro this in stable on my machine, can Matt or Megan verify?
