### ISSUE TITLE
auto attach not working with node

### ISSUE THREAD

**Issue by saru998** [microsoft/vscode#102120]
Issue Type: <b>Bug</b>

Hi team,
auto attach is not working on node

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
python|ms-|2020.6.91350

</details>

**Comment by serkansahinBE** [comment]
I have the same issue on Linux (Fedora 32 64bits), "autoAttachChildProcesses" on NodeJS  is not working since at least VSCode 1.46.1 but working on Windows 10.

**Comment by connor4312** [comment]
Thanks for the issue! What problem are you seeing -- e.g. do you get attach info written to the terminal but it never attaches, or does it just never attach at all?

/needsMoreInfo

**Comment by mendeljacks** [comment]
vscode v1.47.0 debugger autoattaching not working on windows 10 either

**Comment by connor4312** [comment]
We're going to revert auto attach to the previous behavior in the upcoming recovery release on Thursday, see https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467

/duplicate
