### ISSUE TITLE
C2090  File not found PRTOPDEF.CH

### ISSUE THREAD

**Issue by jevsoftwares** [microsoft/vscode#102168]
Issue Type: <b>Bug</b>

ESTÃO ADICIONADOS OS INCLUDES NAS PASTAS DEFAULT E NO ARQUIVO DESENVOLVIDO, MAS NÃO COMPILA O PROJETO.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
tds-vscode|TOT|1.0.5

</details>

**Comment by bpasero** [comment]
Please report again in english with more info.

**Comment by WilsonDavila** [comment]
When trying to compile, the message missing library for compilation is returned, the library path is configured correctly. the returned message is "C2090 File not found PRTOPDEF.CH". The problem started to occur after the last update of VsCode.
