### ISSUE TITLE
notebooks now unstable

### ISSUE THREAD

**Issue by machine-gurning** [microsoft/vscode#102172]
Issue Type: <b>Bug</b>

since last night's update I have been having trouble using the notebooks. It appears that ctrl+c and ctrl+v functionality has been affected: 
- Paste either pastes double of what was copied or blank space
- Copy occasionally erases highlighted characters (as if it was cut)

Identical files to before, no changes whatsoever but for the update

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (1.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.6.91350

</details>

**Comment by jmestradag** [comment]
I have a Windows 10 home edition build 19041 version 2004 with 4GB RAM and Intel i5 8265U CPU, visual studio version 1.47 and having same issue pasting twice a piece of code copied and happens in notebooks.

**Comment by Zusukar** [comment]
I am also getting the same issue where every paste into a notebook is duplicated.  One thing to note is that the undo buffer seems to have the duplicate paste as a separate action.  So to paste correctly I have to press Ctrl-V then Ctrl-Z to remove the duplicate paste.  This is really frustrating and adding bugs to my code when I forget to remove the duplicate paste each time.

**Comment by Zusukar** [comment]
Here's a little [Autohotkey](https://www.autohotkey.com/) script that I am using as a workaround for now.  It will send a Ctrl-Z if you press Ctrl-V and all of these are true:

- The active window's executable is named Code.exe
- "Visual Studio Code" is in the title of the window
- ".ipynb" is in the title of the window (not case sensitive)

```
#IfWinActive, ahk_exe Code.exe
~^v Up::
  WinGetTitle, WindowTitle, A
  If InStr(WindowTitle, "Visual Studio Code") AND InStr(WindowTitle, ".ipynb")
    Send, ^z
Return
#If
```

Use at your own risk. There is a slight race condition in that the Ctrl-Z is sent to whatever window is active, so if somehow your active window changes in the _very_ short time the `If` statement takes to evaluate, the Ctrl-Z could be sent to an unintended window.

**Comment by fkjogu** [comment]
Teasing bot. Knows the other issue but doesn't tell.
