### ISSUE TITLE
'${workspaceFolder}' can not be resolved in a multi folder workspace. Scope this variable using ':' and a workspace folder name.

### ISSUE THREAD

**Issue by lamaks** [microsoft/vscode#102162]
After update to VS Code 1.47.0 the following error prevents to run using workspace config.

![image](https://user-images.githubusercontent.com/40576301/87193522-bb8e0900-c2ad-11ea-9ca0-8131d148384f.png)

workspace.code-workspace

```
 "folders": [
...
        {
            "name": "root",
            "path": "../"
        }
    ],
...
"launch": {
        // Use IntelliSense to learn about possible attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Debug current unit test file",
                "program": "${workspaceFolder:root}/node_modules/jest/bin/jest",
                // ${relativeFile} returns path with back slash. jest can't find the file if we use back slash. So, just passing file name instead
                "args": [
                    "${fileBasename}",
                    "--runInBand",
                    "--coverage=false"
                ],
                "console": "integratedTerminal",
                "internalConsoleOptions": "neverOpen",
                "cwd": "${fileDirname}"
            }
        ]
    }
```

Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by connor4312** [comment]
This looks like an error coming from the config resolution step in our old debugger. You can change your configuration `type` to point directly to our new debugger by setting it to `pwa-node`. This should resolve the issue you're facing.

This should no longer be necessary starting from the next release (at the beginning of August).

Happy Coding! ⌨️
