### ISSUE TITLE
Option to run tasks.json from launch.json even if it doesn't define multiple tasks

### ISSUE THREAD

**Issue by joshtynjala** [Microsoft/vscode#10211]
launch.json offers the preLaunchTask field to run a specific task before debugging. This works great if I'm using Gulp or something else that supports multiple task names. However, if I set up a tasks.json that simply runs an executable, such as a compiler, there seems to be no easy way to run this singular task before launching. There is no task name, so I have nothing to pass to preLaunchTask. I'm forced to manually build with Ctrl+Shift+B before I launch.

It would be great if I could set it up so that my tasks.json would run automatically on launch. Maybe a new field, like the example below, where it runs whatever is associated with Ctrl+Shift+B:

```
{
    "preLaunchRunBuildTask": true
}
```

**Comment by isidorn** [comment]
fyi @dbaeumer

**Comment by dbaeumer** [comment]
@joshtynjala  if you only have one command in the tasks.json you can refer to that 'task' using the command string. If the command is for example 'npm' we generate a task with the name npm which you then can use in the launch.json.

I agree that this might be cumbersome if the command is a full path. Instead of having the launch.json fixing this we should allow to name single tasks in the tasks.json.

**Comment by joshtynjala** [comment]
>  if you only have one command in the tasks.json you can refer to that 'task' using the command string.

Ah, thank you! I didn't realize that. Perhaps a note [in this document](https://code.visualstudio.com/docs/editor/debugging) that makes this special case more obvious would be helpful. I would not have guessed on my own that the "command" field could be used like this.

> I agree that this might be cumbersome if the command is a full path. 

Agreed. Luckily, I'm running things that are in the PATH environment variable.

> Instead of having the launch.json fixing this we should allow to name single tasks in the tasks.json. 

This would be convenient! I'm planning to write some tutorials for the language extension that I'm working on, and I'm sure at least some of my users will prefer to run commands with the full path. Being able to name the task "build" or "compile" in the tutorial would make things cleaner for everyone, full path or not.

**Comment by isidorn** [comment]
ping @gregvanl

**Comment by alexr00** [comment]
You can now add a label to any task, and use that label to refer to the task in `preLaunchTask`
