### ISSUE TITLE
Root element has white background-color on dark themes

### ISSUE THREAD

**Issue by clshortfuse** [microsoft/vscode#102179]
- VSCode Version: 1.46.1
- OS Version: Windows 10 19041.329

Steps to Reproduce:

1. Set a dark theme
2. Drag the edges of the screen quickly
3. See flashes of white

Does this issue occur when all extensions are disabled?: Yes

This is a rather simple fix, maybe. Essentially the root element (`<html>`) has a default `background-color` of `#fff`.  The CSS rule should be changed here:

https://github.com/microsoft/vscode/blob/588097171c872f26ad9dcd9cf0441cf5b1a8b7e7/src/vs/workbench/browser/style.ts#L25

Something like this: `html, .monaco-workbench { background-color: ${workbenchBackground}; }` should work.

**Comment by bpasero** [comment]
@clshortfuse I think I can reproduce this but only up until I restarted, then it seems to be fine. Can you clarify that this does not reproduce once you closed VSCode and reopened again? So the steps are:
* start VSCode
* change from dark to light or light to dark theme depending on what is active
* drag the window
* you see either a black background when you picked light theme or a white background when you picked dark theme
* restart
* the issue is gone

**Comment by clshortfuse** [comment]
@bpasero Sometimes it fixes. Sometimes it's backwards. It might be due to the fact I'm matching theme with Windows 10 Theme. I'm unable to get it to ever show a white dragging background on a light theme, and can only get it to show black background on light (bad), black background on dark (good), or white background on light (bad).

* Closed and Windows set to Dark
* Open VSCode
* (Dark) Dragging background showing black (OK)
* Switches Windows Theme to Light with VS Code Open
* (Light) Dragging background showing black (Bad)
* Close VSCode
* Open VSCode
* (Light) Dragging still black (Bad)
* Close VS Code
* Open VS Code
* (Light) Dragging still black (Bad)
* Switch Windows Theme to Dark
* (Dark) Dragging background switched to White!!! (Bad)
* Switch Windows Theme to Light
* (Light) Dragging background switched to Black!!! (Bad)
* Close VS Code
* Open VS Code
* (Light) Dragging still black (Bad)
* Switch Windows Theme to Dark
* (Dark) Dragging background switched to White!!! (Bad)
* Close VS Code
* Open VS Code
* (Dark) Dragging is background is black (Good).
* Close VS Code
* Switch Windows Theme to Light
* Open VS Code
* VS Code Starts Dark Theme, and switches to Light, still has black dragging background (Bad)
* Close VS Code
* Gives Up 🤣

**Comment by bpasero** [comment]
Moving back to you Martin, I think you added this line which controls the native background color of the window:

https://github.com/microsoft/vscode/blob/4c99db1a05687a67c1d214361946b18e5f65e0cf/src/vs/code/electron-main/window.ts#L163

I do not think that setting the background color on the HTML element has any impact.

**Comment by aeschli** [comment]
When I tried the last time (over a year ago), changing the Electron background color didn't work. 

@clshortfuse The issue is not high on my priority list. If you want to give it a try, I'm happy to review a PR.
