### ISSUE TITLE
Codespaces for https://online.visualstudio.com only shows one tenant during create flow online.

### ISSUE THREAD

**Issue by thenickg** [microsoft/vscode#102154]
Apologies if this shuold be rerouted. 
Codespaces currently is unable to instantiate for multiple tenants, only the first tenant is offered. The subscriptions listed should either be from all tenants or an additional dropdown created for tenant selection.

- VSCode Version: 1.46.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Have an Azure account with multiple tenants (sometimes called directories)
2. Navigate with authenticated Azure Account to https://online.visualstudio.com/environments
3. Click "Create Codespace" Notice how only 1 tenant is shown (namely the first one returned from the management service).

Does this issue occur when all extensions are disabled?: *Yes*

Slightly unrelated: I get "resource validation failed" when creating a codespace via VSCode, so I have no workaround for instantiating a Codespace

**Comment by bpasero** [comment]
Please share via feedback: https://docs.github.com/en/github/developing-online-with-codespaces/about-codespaces
