### ISSUE TITLE
Breakpoints Not Bound (Babel + Jest)

### ISSUE THREAD

**Issue by mdhornet90** [microsoft/vscode#102152]
Issue Type: <b>Bug</b>

Also tested on VSCode 1.48.0-insider

I have the following launch configuration to run a currently-opened Jest test file:
```
    {
      "type": "node",
      "request": "launch",
      "name": "Test Current API File",
      "cwd": "${workspaceFolder}/api",
      "program": "${workspaceRoot}/api/node_modules/jest/bin/jest",
      "args": [
        "-i",
        "${file}"
      ],
      "smartStep": false,
      "skipFiles": [
        "<node_internals>/**"
      ],
      "env": {
        "NODE_ENV": "test",
        "BABEL_ENV": "debug",
      },
      "console": "integratedTerminal",
    }
```

Under the hood I'm using babel in combination with jest to transpile code. Starting with VSCode 1.47.0, breakpoints that I set in the editor are not bound when that launch configuration is run:
![vscode-bug](https://user-images.githubusercontent.com/424092/87187781-934cdd00-c2a2-11ea-92fe-007d391b864e.gif)

Instead, the only thing I find that currently works is spamming the breakpoint until sometime after "Debugger Attached" is printed in the console:
![vscode-bugfix-ish](https://user-images.githubusercontent.com/424092/87187850-aeb7e800-c2a2-11ea-8f6c-948dbb1a7b47.gif)

I suspect this has to do with the interaction of VSCode and Sourcemaps, as disabling them in the launch configuration successfully stops the program in the _transpiled_ file.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 12, 8|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-lcov|ale|0.2.0
cucumberautocomplete|ale|2.15.0
cform|aws|0.0.24
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
vscode-eslint|dba|2.1.6
xml|Dot|2.5.0
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
go|gol|0.15.1
search-node-modules|jas|1.3.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
cpptools|ms-|0.28.3
vsliveshare|ms-|1.0.2427
debugger-for-chrome|msj|4.12.9
vscode-graphql|Pri|0.2.14
ruby|reb|0.27.0
vscode-yaml|red|0.8.0
vscode-coverage-gutters|rya|2.5.1
nodejs-extension-pack|wad|0.1.9
vscode-ruby|win|0.27.0
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by connor4312** [comment]
Thanks, I'll look into this. For the moment you can set `debug.javascript.usePreview: false` to stick with the old debugger, if that worked for you.

**Comment by mdhornet90** [comment]
Thanks for the tip, I'll do that. Let me know if you need any other info from me!

**Comment by connor4312** [comment]
@mdhornet90 can you collect a trace file using these instructions?

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

If you can't, something else that may be useful is to put a `debugger` statement in your code and, when that's hit, observe where that file is opened. VS Code will open the file it _thinks_ the source lives -- this is useful since the most common cause for unset breakpoints is the debugger thinking the source file is in the wrong location.

**Comment by shawnmcknight** [comment]
@connor4312 I'm experiencing the same issue as the OP.  I added the `debugger` statement as you suggested and the correct file was opened by vscode, although still showing the breakpoints unbound.  I've attached my trace logs.
[vscode-debugadapter-4.json.gz](https://github.com/microsoft/vscode/files/4909556/vscode-debugadapter-4.json.gz)

**Comment by mdhornet90** [comment]
Finally had a chance to run trace. It didn't directly print out the name of the log file generated, but it lives in the same folder as the `NODE_OPTIONS=--require /var/path/to/vscode-js-debug-bootler.js`
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/4914033/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment]
Thank you for the logs. I found the repo you were using @shawnmcknight which was helpful in fixing it :)

This was a scenario we actually had a test case for previously, but the test case wasn't correct. Fixed in the linked commit. You can grab the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) (published at 5 PM PST each day) for the fix.

**Comment by mdhornet90** [comment]
> Thank you for the logs. I found the repo you were using @shawnmcknight which was helpful in fixing it :)
> 
> This was a scenario we actually had a test case for previously, but the test case wasn't correct. Fixed in the linked commit. You can grab the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) (published at 5 PM PST each day) for the fix.

Tested with the nightly build and it's back to working as expected. Thanks for fixing this!
