### ISSUE TITLE
Giving incorrect output while manipulating large number input case 

### ISSUE THREAD

**Issue by touchnewshiva** [microsoft/vscode#102119]
- VSCode Version:  1.46.1
- OS Version:Windows 10 pro

Steps to Reproduce:

1.	Add the following JS code
        var aa = 125029734092369566;
        var bb = 2;
        var sum = aa + bb;
        console.log(sum);
2.	Expected Output :  125029734092369568 or Crossed the input size limit
3.	Actual : 125029734092369570 (Incorrect answer)
4.	This issue started from 18th digit onwards. This might be JavaScript error. It would be nice, If Visual Studio Code restricts 
        this.

![JS Bug](https://user-images.githubusercontent.com/65024196/87157874-8220c200-c2dc-11ea-9816-ccfd66d113f4.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
This is not related to VS Code, it's standard JavaScript behavior
