### ISSUE TITLE
[json] Custom CompletionItemProvider cannot provide completions in strings

### ISSUE THREAD

**Issue by SPGoding** [microsoft/vscode#102196]
Issue Type: <b>Bug</b>

I cannot use custom `CompletionItemProvider` to provide completions in JSON's string values.

Here is a simple test snippet, which should provide the completion of `ABCTEST` when requested anywhere in any file:

```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	const provider = vscode.languages.registerCompletionItemProvider(
		[{ scheme: 'file' }, { scheme: 'untitled' }],
		{
			provideCompletionItems() {
				return [ new vscode.CompletionItem('ABCTEST', vscode.CompletionItemKind.Text) ];
			}
		}
	);
	context.subscriptions.push(provider);
}
```

However, the completion doesn't show when you request it in a JSON's string:

![no-json-string-completion](https://user-images.githubusercontent.com/15277496/87218303-16a81600-c317-11ea-8fd5-45ea19cf5abd.gif)

You can clone this repository to test this quickly if you want: https://github.com/SPGoding/completion-test

VS Code version: Code - Insiders 1.47.0-insider (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-08T10:52:52.439Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.87GB free)|
|Process Argv|C:\SPGoding\Projects\SPGoding\Typescript\datapack-language-server.code-workspace|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aeschli** [comment]
You need to provide the a [range](https://github.com/microsoft/vscode/blob/4c99db1a05687a67c1d214361946b18e5f65e0cf/src/vs/vscode.d.ts#L3856) for the completion item...

**Comment by SPGoding** [comment]
Ah never know that as there's no `range` property in LSP's types, though `textEdit` can also do the trick. Sorry for bothering and I appreciate your help!
