### ISSUE TITLE
Can't paste or insert into empty notebook

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#102156]
- Have notebook with one cell
- Cut that cell
- Can't paste, or insert a cell

**Comment by machine-gurning** [comment]
I am experiencing both this problem and the double-paste issue noted elsewhere, where copying something and pasting it into a notebook block results in a double-paste of the contents

**Comment by roblourens** [comment]
You are actually seeing https://github.com/microsoft/vscode/issues/101946

**Comment by connor4312** [comment]
I was able to repro this: https://memes.peet.io/img/20-08-cbceb676-831a-4077-9422-5440ac9fd181.webm
