### ISSUE TITLE
Debugger listening on random port instead of taking into account the one set in the launch.json

### ISSUE THREAD

**Issue by serkansahinBE** [microsoft/vscode#102121]
- VSCode Version: 1.47
- OS Version: Windows 10 10.0.18363 64bits

Hi everyone!

I encountered a weird issue with my VSCode setup today, I tried to launch my NodeJS app (using Nodemon) via VSCode Debugger in order to put breakpoints into my code but the debugger seems to not taking into account the port I have set in my launcher's parameters anymore. It was working still yesterday using VSCode 1.46.1, I will try to downgrade to that version and check if I can reproduce this issue.

#### update 1: 
It is indeed working well with VSCode 1.46.1.

Steps to Reproduce:

1. Having a launch request block in .vscode/launch.json with a port set in parameters.
2. Running the debugger, the debugger does not listen on the given port anymore.

### My launch.json
```json
{
  "configurations": [
    {
      "name": "Start App (Nodemon)",
      "runtimeExecutable": "${workspaceFolder}/node_modules/yarn/bin/yarn",
      "args": [
        "vscode-nodemon"
      ],
      "request": "launch",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "type": "node",
      "console": "integratedTerminal",
      "protocol": "inspector",
      "internalConsoleOptions": "neverOpen",
      "restart": true,
      "port": 9229,
      "autoAttachChildProcesses": true,
      "timeout": 60000
    },
    {
      "name": "Chrome Debugger (webpack)",
      "type": "chrome",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}/src",
      "disableNetworkCache": true,
      "request": "launch"
    }
  ],
  "compounds": [
    {
      "name": "Back/Front Debug",
      "configurations": [
        "Start App (Nodemon)",
        "Chrome Debugger (webpack)"
      ]
    }
  ]
}
```
### package.json
```json
{
  "name": "my-app",
  "status": "production",
  "version": "1.0.0",
  "engines": {
    "node": "12.18.2",
    "npm": "6.x",
    "yarn": "1.22.0"
  },
  "description": "My App",
  "main": "server.js",
  "scripts": {
    "build": "npx webpack -p --config webpack.config.js --env production",
    "dev": "yarn dev-start",
    "dev-build": "npx webpack --config webpack.config.js --env development",
    "dev-build-watch": "npx webpack --config webpack.config.js --watch --env development",
    "dev-simple": "npx nodemon --ignore local_scripts/ --ignore scripts/ --ignore seeders/ --ignore src/ --ignore workers/ server.js --delay 2",
    "dev-limit": "npx nodemon server.js --optimize_for_size --max_old_space_size=920 --gc_interval=100 --delay 2",
    "dev-start": "npx nodemon --ignore local_scripts/ --ignore scripts/ --ignore seeders/ --ignore src/ --ignore workers/ --signal SIGTERM server.js --delay 2",
    "dev-workers": "npx nodemon --watch workers --watch schedulers --watch controllers --watch helpers --watch models workers/index.js --delay 2",
    "vscode-nodemon": "npx nodemon --inspect-brk=0.0.0.0:9229 --ignore local_scripts/ --ignore scripts/ --ignore seeders/ --ignore src/ --ignore workers/ --signal SIGTERM server.js --delay 2",
    "lint": "npx eslint . --ext .js",
    "start": "node server.js",
    "workers": "node workers/index.js",
    "docker-debug": "docker-compose up",
    "test": "npx mocha"
  },
  ...
}
```

### VSCode debugger output
```text
Debugger listening on ws://127.0.0.1:53967/b94d389c-80c0-4d6c-be97-7d769bb61745
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:53972/6093e85c-5351-4f52-ba42-db754f2193e3
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
yarn run v1.22.0
$ npx nodemon --inspect-brk=0.0.0.0:9229 --ignore local_scripts/ --ignore scripts/ --ignore seeders/ --ignore src/ --ignore workers/ --signal SIGTERM server.js --delay 2
Debugger listening on ws://127.0.0.1:53976/89d7f965-0a0a-4660-b26f-063580defd17
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --inspect-brk=0.0.0.0:9229 server.js`
Debugger listening on ws://0.0.0.0:9229/3220acc2-badb-486b-8b9a-a48a08e4ee60
For help, see: https://nodejs.org/en/docs/inspector
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by jmtelljohann** [comment]
I also just started experiencing the same issue after upgrading to 1.47.0 this morning.

**Comment by serkansahinBE** [comment]
I can confirm that it works well on 1.46.1
![1461_works](https://user-images.githubusercontent.com/64956620/87160884-fef37200-c2c3-11ea-8bb6-dc58e4227017.png)

**Comment by connor4312** [comment]
1.47 uses a new debugger that has a different way of attaching to processes, and notably can also attach to spawned child processes of the parent process (which cannot share the same debug port). Therefore it always listens on port 0, which gets turned into any free port by the OS.

If there a workflow you have where a consistent port is expected? That is, is something broken for you? I'm not totally clear on that based on the info provided 🙂 

Thanks for filing an issue!

**Comment by serkansahinBE** [comment]
> 1.47 uses a new debugger that has a different way of attaching to processes, and notably can also attach to spawned child processes of the parent process (which cannot share the same debug port). Therefore it always listens on port 0, which gets turned into any free port by the OS.
> 
> If there a workflow you have where a consistent port is expected? That is, is something broken for you? I'm not totally clear on that based on the info provided 🙂
> 
> Thanks for filing an issue!

Hi @connor4312 ,

I expect the master process to listen on port 9229 and so the same from VSCode debugger. If I set the attribute "port" in my debugger then I expect from it to listen on the given port only and not on all ports of my machine (port = 0). From what you have written, Vscode does not take the port parameter into account anymore, so why letting the choice to the user in that case? Either remove the possibility to set a consistent port or add it in the new debugger (known as pwa-<something> I guess..).

**Comment by connor4312** [comment]
The port is actually invalid when given to js-debug. But there have been a few use cases (e.g. when the launched program is actually a docker container) where the port _will_ be needed, so I will be adding it back in some form. But to get the whole picture and make sure your use case in served I'm interested in knowing if there's a particular reason you are depending on a static port number, or whether you noticed this as more of a 'cosmetic' issue 🙂

**Comment by connor4312** [comment]
> But there have been a few use cases (e.g. when the launched program is actually a docker container) where the port will be needed, so I will be adding it back in some form

Fyi this is now done in https://github.com/microsoft/vscode-js-debug/issues/586#issuecomment-658958272

**Comment by serkansahinBE** [comment]
> The port is actually invalid when given to js-debug. But there have been a few use cases (e.g. when the launched program is actually a docker container) where the port _will_ be needed, so I will be adding it back in some form. But to get the whole picture and make sure your use case in served I'm interested in knowing if there's a particular reason you are depending on a static port number, or whether you noticed this as more of a 'cosmetic' issue 🙂

@connor4312 Simply because I want to control on which port my process listens, the new behavior is a very nice feature for people that do not want to bother with those kind of parameters but in my case I care. Also I tried to use the debugger on a Docker container.. So that is nice to know that it has been fixed 💯 

Thanks mate!

**Comment by connor4312** [comment]
Okay, great!

If you'd like to control the port your process listens on, you can manually add `runtimeArgs: ["--inspect"]` (or `--inspect=12345` to listen on a different port), which js-debug will respect. Any child processes that spawns and debugs will still be on different ports since 9229 will be in use.

It sounds like you have what you need at this point, so I'll close the issue. Give me a shout if you run into any more hiccups 🙂
