### ISSUE TITLE
Endless spam about Git extension. Can't remove due to nonexistant "GitHub" dependency

### ISSUE THREAD

**Issue by JonathanDotCel** [microsoft/vscode#102182]
- VSCode Version: 1.47
- OS Version: Win 10 (not WSL)

Steps to Reproduce:

1. Open any project
2. "hey, you need a different git extension..."
3. Try to disable git
4 "Cannot disable extension "Git", Extension "GitHub" depends on this.
5 Reasonably sure I don't have "GitHub"

Failing that, is there some code I can patch out to make it permanently shush?
(Getting Rider flashbacks :D)

Does this issue occur when all extensions are disabled?: Yes/No
Not applicable.

![image](https://user-images.githubusercontent.com/61208676/87213704-a30a0700-c31e-11ea-9b6c-fdfc71503ee6.png)

Cheers :)

**Comment by gjsjohnmurray** [comment]
What does the `@builitin` search term show? Any Git-related ones? Any of them disabled?

**Comment by joaomoreno** [comment]
> "hey, you need a different git extension..."

Can you show me this notification?

**Comment by JonathanDotCel** [comment]
Hi, long story short the list would not scroll as far as the builtin plugins without collapsing a few other things ("programming languages", "themes", etc - I toggled them a few times and list expanded properly) I wish I had a pre-screenshot to show, but I only have some of other sections.

Possibly related?
(happened once or twice)

![Code_2020-07-11_02-14-33](https://user-images.githubusercontent.com/61208676/87250204-39434780-c45b-11ea-8643-983b6d0751ec.png)

For clarity's sake this was the message, but I'm happy to close this one. Thank you both for the help.
![image](https://user-images.githubusercontent.com/61208676/87250007-3562f580-c45a-11ea-85fd-3d62db374984.png)
