### ISSUE TITLE
Terminal started behaving badly when Zshell theme is present.

### ISSUE THREAD

**Issue by DanielAtKrypton** [microsoft/vscode#102134]
- VSCode Version: 1.46.1
- OS Version: Windows_NT x64 10.0.20161

Steps to Reproduce:

1. Install [debian-dev-boilerplate](https://github.com/DanielAtKrypton/debian-dev-boilerplate) inside WSL.
2. Setup powerlevel 10k.
3. Clone a git repo and enter its folder.
```zshell
git clone git@github.com:DanielAtKrypton/debian-dev-boilerplate.git
cd debian-dev-boilerplate
```
You should now see something like:

![Imgur](https://i.imgur.com/fJxVG33.png)

4. Open vscode from zshell. By typing at the zshell prompt:
```zshell
code .
```

At this point the bug is revealed when the terminal is opened for the first time inside vscode. At first glance, the terminal renders correctly the powerlevel10k theme. After half a second, the theme is deactivated as can be seen in the next picture.

![Imgur](https://i.imgur.com/fcQoxDj.png)

Does this issue occur when all extensions are disabled?: Yes

It is interesting to note that in prior vscode versions this functionality was working alright. For any reason I don't know this issue started to happen in the last couple weeks.

**Comment by Tyriar** [comment]
> At first glance, the terminal renders correctly the powerlevel10k theme. After half a second, the theme is deactivated as can be seen in the next picture.

After zsh is launched, VS Code doesn't talk to it apart from via keyboard input so it couldn't influence it like this. Things you can look into to help diagnose:

- What environment VS Code launches with, check this using [trace logging](https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging)
- Check if you have extensions that could be sending data to terminals
- Try tweaking terminal.integrated.shell.linux/terminal.integrated.shellArgs.linux settings

**Comment by DanielAtKrypton** [comment]
Here is the log file attached.

[exthost.log](https://github.com/microsoft/vscode/files/4904425/exthost.log)

**Comment by DanielAtKrypton** [comment]
I created a [StackOverflow question](https://stackoverflow.com/questions/62839116/terminal-started-behaving-badly-when-zshell-theme-is-present) as suggested.

**Comment by DanielAtKrypton** [comment]
> * Check if you have extensions that could be sending data to terminals

The first time vscode is launched, it installs a vanilla (with no extensions) vscode-server to the linux distro. And still the bug happens.
