### ISSUE TITLE
Regression: Cannot preview image in git diff

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#102191]
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:30:34.302Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.18.0-041800-generic

Steps to Reproduce:

1. Inittialize a repo and commit an image file `imageFile.png`
2. Change/edit `imageFile.png`
3. Open scm view and click on `imageFile.png` in changes group to open diff view for that image
4. :bug: Left side of diff view containing previous version of  `imageFile.png` isn't loaded

From debugging it seems that there is no provider registered for the `git` scheme and throws an error
https://github.com/microsoft/vscode/blob/1ca18ed83c107f1265d0a0f60a5a9c8b425f5207/src/vs/platform/files/common/fileService.ts#L114-L122

**Comment by joaomoreno** [comment]
@bpasero @mjbvz I haven't touched this code lately, can you check your layers?

**Comment by bpasero** [comment]
Confirmed:

![image](https://user-images.githubusercontent.com/900690/87274237-91219300-c4db-11ea-89fd-b83aefa04944.png)

**Comment by bpasero** [comment]
And when staged, even worse:

![image](https://user-images.githubusercontent.com/900690/87274271-a4ccf980-c4db-11ea-8bfd-cf42b31b80f7.png)

**Comment by mjbvz** [comment]
@deepak1556 @bpasero This is another side effect of moving the webview resources logic into the main process. The renderer's file system service understands `untitled:` and `git:` URIs, but the file system service on the main process does not.

A couple of potential options:

- Have the main process delegate back to the render to read files in these cases (this has the downside of adding additional roundtrips)

- Give the main process access to the file systems from the renderers (this may already be possible)
