### ISSUE TITLE
Debug protocol: Please add Variable::settable

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#10217]
- VSCode Version: 1.4
- OS Version: All

When a debug adapter reports that is supports setVariable, all leaf variables become editable, but compound objects do not.  While a reasonable heuristic, this is not optimal because:
- primitive values may be not editable if they are "synthetic" i.e. generated by a visualizer.
- compound objects may be editable, e.g. std::string (which may still want to show individual characters as children, and possibly provide a "raw" view of the implementation as a synthetic child).

I'd suggest adding an explicit "settable" flag into `Variable`.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-debugadapter-node#53
