### ISSUE TITLE
After update to 1.47.0 base direcroty change

### ISSUE THREAD

**Issue by karaka200** [microsoft/vscode#102150]
- VSCode Version: 1.47.0
- OS Version: Windows 10

When I update my vscode to 1.47.0 my base files goes to "_" directory.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Please explain what you mean by "base files". Maybe paste screenshots here.

**Comment by karaka200** [comment]
@gjsjohnmurray  My vscode is in "D:/Programs/Vscode/"
After update to 1.47.0 vscode files moved to "D:/Program/Vscode/_/" folder
Just "unins000.exe" and "unins000.dat"and "unins000.msg" and "swiftshader" are stay in "D:/Programs/Vscode/" folder
I move all files and folders at "D:/Programs/Vscode/_/" folder to "D:/Programs/Vscode/" and work.

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
