### ISSUE TITLE
Triage bot logo is cut off 🪓

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#102136]
![image](https://user-images.githubusercontent.com/35271042/87176122-7e664e80-c28e-11ea-87c7-12b6140bb5ce.png)

We should use [the logo with extra padding](https://github.com/microsoft/vscode-logos/blob/master/images/social-media/code-social-stable.png) or scale down the logo.

**Comment by JacksonKearl** [comment]
\label polish
