### ISSUE TITLE
Poor extension search results when including space in search term

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#102193]
Issue Type: <b>Bug</b>

**Repro**
1. In extensions view, trying to find the `HexEditor` extension.
1. First search `hex editor` (with a space)

    See no `HexEditor` extension: 

    <img width="701" alt="Screen Shot 2020-07-10 at 12 15 53 PM" src="https://user-images.githubusercontent.com/12821956/87216779-a5a53600-c2f7-11ea-9b16-1de6c94632c5.png">

1. Now search `HexEditor` (no space)

     See the correct extension:

     <img width="709" alt="Screen Shot 2020-07-10 at 12 15 58 PM" src="https://user-images.githubusercontent.com/12821956/87216791-c8374f00-c2f7-11ea-8adf-62c9dd16afdd.png">

VS Code version: Code - Insiders 1.48.0-insider (e7920dce7bfd0b707ebfc0a5379c6edd2233e475, 2020-07-10T11:55:11.286Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|15%|
</details>

**Comment by isidorn** [comment]
Here's some more bad examples which we should fix as soon as possible. Since this directly influences the download count of our PR extensions.

fyi @alexr00 

![Screenshot 2020-10-01 at 13 59 51](https://user-images.githubusercontent.com/1926584/94806820-e7bdaf80-03ee-11eb-8691-84ed53c08b75.png)

![Screenshot 2020-10-01 at 14 01 12](https://user-images.githubusercontent.com/1926584/94806824-e8564600-03ee-11eb-8802-bf21a8726482.png)

**Comment by isidorn** [comment]
ping @fiveisprime @kieferrm

**Comment by fiveisprime** [comment]
The Marketplace team has search improvements on their backlog, but it requires some major rework of the existing search implementation. It's being tracked on their backlog.

**Comment by isidorn** [comment]
Upstream issue https://github.com/microsoft/vsmarketplace/issues/154

**Comment by isidorn** [comment]
This is fixed in latest [VS Code Insiders](https://code.visualstudio.com/insiders/). Please try it out and let us know if there are still examples where you think that search is not working.
We expect the fixed search to be in VS Code Stable start of December.
Looking forward to feedback - thanks!
