### ISSUE TITLE
No way to add back source control repositories 

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#102171]
Issue Type: <b>Bug</b>

Prior to 1.47.0, the UI provided a way to hide and re-enable repositories:

![Screenshot from 2020-07-10 14-00-04](https://user-images.githubusercontent.com/13824553/87207970-23e6e580-c2c2-11ea-9cce-9c5ccb31d15f.png)

The new source control pane UI doesn't offer an obvious way to add back repositories once they've been closed:

![Screenshot from 2020-07-10 15-27-08](https://user-images.githubusercontent.com/13824553/87208023-51339380-c2c2-11ea-9e6f-5502f36783b1.png)

Also, the last screenshot illustrates another UX issue: the repository status and action icons are mixed together (why there are two "refresh" icons in there? ... yes, I realize that one is not actually a refresh button)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:30:34.302Z)
OS version: Linux x64 5.4.0-40-generic

**Comment by gjsjohnmurray** [comment]
Looks like some of those icons are for commands contributed by another extension you have installed.

**Comment by tlemo** [comment]
> Looks like some of those icons are for commands contributed by another extension you have installed.

Correct, one of the icons comes from an extension. Here's the equivalent with --disable-extensions:

![Screenshot from 2020-07-11 08-21-12](https://user-images.githubusercontent.com/13824553/87227423-b08bb500-c34f-11ea-97d7-1d2367b6e98c.png)

**Comment by joaomoreno** [comment]
#101145
