### ISSUE TITLE
Show list of symbols (cmd + p @) does not work for PHP classes

### ISSUE THREAD

**Issue by robfe11** [Microsoft/vscode#10214]
- VSCode Version: 1.4
- OS Version: Mac OS X El Capitan

Steps to Reproduce:
1. Open a .php file that contains a class
2. Press `cmd + p`
3. Type `@`

You should see a list of symbols in the file at this point, but it doesn't seem to work for PHP files.  This is pretty crucial in order to switch from another editor to VS Code for PHP developers.

Here is a sample PHP class to test this with, make sure to save the file with a .php extension.

```
<?php

class Vegetable {

   var $edible;
   var $color;

   function Vegetable($edible, $color="green")
   {
       $this->edible = $edible;
       $this->color = $color;
   }

   function is_edible()
   {
       return $this->edible;
   }

   function what_color()
   {
       return $this->color;
   }

} // end of class Vegetable
```

**Comment by aeschli** [comment]
We hope that this can be provided by an extension.

**Comment by robfe11** [comment]
Sure, but to be honest, it's basic functionality that all decent Coding editors support out of the box.

**Comment by robfe11** [comment]
For anyone else that has the same issue, I found an extension that fixes this, but it would be nice if it was included by default:

https://marketplace.visualstudio.com/items?itemName=linyang95.php-symbols

**Comment by felixfbecker** [comment]
PHP IntelliSense supports this
https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense

![documentsymbol](https://cloud.githubusercontent.com/assets/10532611/18989699/a609862a-870d-11e6-9b63-a8ccd3e08d9f.gif)
