### ISSUE TITLE
the `rg.exe` takes up too much CPU

### ISSUE THREAD

**Issue by talking-toaster** [microsoft/vscode#102183]
- VSCode Version:lastest
- OS Version:Win10 1904 professional

Steps to Reproduce:

1.Today, When I was using my computer, I opened two pieces of `vs code` and a process called `rg.exe` appeared in task Manager,which takes up more than 90%CPU for 2 minutes.
2.I can't reproduce this.But it's on a lot of people's `vs code` .

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
That is the process we use for search. Did you trigger a search? If not it may have been started by an extension. Also please check whether the tips here help: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by talking-toaster** [comment]
I don't think I triger a search by opening vscode with a workspace. But the workspace is a little large. I solved it with setting `"search.followSymlinks": false`  from your link.Thanks.
