### ISSUE TITLE
The existed extensions cannot be loaded after upgrade to the latest version v1.47.0

### ISSUE THREAD

**Issue by owen2016** [microsoft/vscode#102178]
- VSCode Version: v1.47.0
- OS Version: window10 (1909)  and deepin 15.11

Steps to Reproduce:

1. after upgrade to 1.47.0 on windows10 an deepin(but ubuntu 18.04 does not have this issue), all existed extensions cannot be loaded.
2. but with the same steps and machines, uninstall v1.47.0 then install the pervious version v1.46.1, there is no issue and vscode can loaded the existed extensions quickly.

![image](https://user-images.githubusercontent.com/16578902/87210887-c007ff80-c349-11ea-9d50-215b3dcd0848.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by gjsjohnmurray** [comment]
There have been several similar reports.

If you launch VS Code from a command prompt using `code - n` do you still have the problem?

What does `code --list-extensions --show-versions` report?

**Comment by owen2016** [comment]
yes, still exists. 

![vscode-issue](https://user-images.githubusercontent.com/16578902/87225230-0139f700-c3be-11ea-8f1a-c158560153c0.PNG)
```

C:\Users\Owen Li>code --list-extensions --show-versions
Alex-Chen.gitee-code-settings-sync@0.1.14
christian-kohler.path-intellisense@2.2.1
DavidAnson.vscode-markdownlint@0.36.1
dbaeumer.vscode-eslint@2.1.6
donjayamanne.githistory@0.6.5
DotJoshJohnson.xml@2.5.0
eamodio.gitlens@10.2.2
EditorConfig.EditorConfig@0.15.1
eg2.vscode-npm-script@0.3.12
felipecaputo.git-project-manager@1.7.1
formulahendry.auto-close-tag@0.5.8
formulahendry.auto-rename-tag@0.1.4
formulahendry.code-runner@0.11.0
foxundermoon.shell-format@7.0.1
golang.go@0.15.1
ivory-lab.jenkinsfile-support@1.1.0
janjoerke.jenkins-pipeline-linter-connector@1.2.0
mohd-akram.vscode-html-format@0.0.4
ms-azure-devops.azure-pipelines@1.170.0
ms-azuretools.vscode-docker@1.3.1
MS-CEINTL.vscode-language-pack-zh-hans@1.47.3
ms-dotnettools.csharp@1.22.1
ms-kubernetes-tools.vscode-kubernetes-tools@1.2.1
ms-python.python@2020.6.91350
ms-vscode-remote.remote-ssh@0.51.0
ms-vscode-remote.remote-ssh-edit@0.51.0
ms-vscode-remote.remote-wsl@0.44.4
ms-vscode.azure-account@0.8.11
ms-vscode.azurecli@0.5.0
ms-vsts.team@1.161.0
msjsdiag.debugger-for-chrome@4.12.9
octref.vetur@0.24.0
pflannery.vscode-versionlens@1.0.8
Pivotal.vscode-spring-boot@1.19.0
redhat.java@0.64.1
redhat.vscode-yaml@0.8.0
ritwickdey.LiveServer@5.6.1
Shan.code-settings-sync@3.4.3
vscode-icons-team.vscode-icons@10.1.1
vscoss.vscode-ansible@0.5.2
yzhang.markdown-all-in-one@3.1.0
zhuangtongfa.material-theme@3.8.3
```

**After reinstall VSCodeUserSetup-x64-1.46.1.exe, the issue disappear.** But it prompts to update and restart. After I reopen vscode,  without notification, vscode v1.46 was forced to upgrade, even the prompt box did not pop up (**No installer pops up and it is loaded directly to 1.47. I don’t have any option to cancel this upgrade**").

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/102082
