### ISSUE TITLE
1.47.0 is not available in apt repo

### ISSUE THREAD

**Issue by adduc** [microsoft/vscode#102127]
It appears the apt repository for VSCode has not yet been updated to 1.47.0.

- VSCode Version: N/A
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Run `apt update` with existing installation of code
2. Run `apt info code` to show the latest version available is still 1.46.1

Does this issue occur when all extensions are disabled?: N/A

**Comment by mikij** [comment]
The same for yum repos: packages.microsoft.com/yumrepos/vscode

**Comment by Tyriar** [comment]
Fixed, there was an issue with credentials. Thanks for the ping 🙂

**Comment by Redmega** [comment]
`apt update` still leaves me with version 1.46. Not sure how to proceed :sweat_smile:

**Comment by bdemirel** [comment]
I have a similar issue. I have updated code to 1.47.1 by downloading the new .deb file from the website a while ago, but apt still doesn't see the 1.47.2 update.
