### ISSUE TITLE
BREAKING CHANGE but not in the update doc.

### ISSUE THREAD

**Issue by pikadun** [microsoft/vscode#102102]
- VSCode Version: v1.47
- OS Version: windows 10 & wls2

https://github.com/microsoft/vscode/issues/97962
https://github.com/microsoft/vscode/issues/102044

@mjbvz I think this is a break update but not in the update doc.

I used `webview.asWebviewUri(Uri.file(<some path>))` and got a url like 
``` text
Old (v1.46): "vscode-resource://file///root/repo/vscode-redis/out/view/js/main.js"
New (v1.47): "vscode-webview-resource://4653f308-3117-4192-97f2-ec249cd8f1a5/file///root/repo/vscode-redis/out/view/js/main.js"
```

The extension installed on wsl2(Ubuntu), and there is something more after vscode resource schema in v1.47.

**Comment by mjbvz** [comment]
`asWebviewUri` returns a uri the works in webviews. We do not document  format of the returned uri and extensions should not rely on it. For example, the result of `asWebviewUri` is completely different when VS Code is run on desktop vs in a browser

If this change caused problems for your extension, please make sure you are not hardcoding `vscode-resource` in your code and instead always call `asWebviewUri`

**Comment by pikadun** [comment]
@mjbvz  But there is one more uuid in the new version, and what is it?
