### ISSUE TITLE
togglePanel + panelPosition keybinding

### ISSUE THREAD

**Issue by butuzov** [microsoft/vscode#102105]
It would be great to have keybinding that helps to not only switch the position of the panels (Left/Bottom/Right) as `workbench.action.positionPanel$Position` doing, but also toggle its visibility. 

 How I see it's can be implemented:

1) Triggering `workbench.action.togglePanel$Position` -> Open/Close panel at position, Close it at previous position if was Opened at different $Position.

2)  Adding `when` settings that tell about  `isWorkbenchPanelVisible` (or something like that)

P/S/
As extension API doesn't provide access to DOM or any other way to get panels position and visibility status of the panels, it makes it impossible to implement it by myself, not via monkey patching.

**Comment by sbatten** [comment]
@butuzov can you explain exactly what the keybinding does? I am not sure I understand

**Comment by butuzov** [comment]
@sbatten I was talking about toggling panel ("View: Toggle Panel") and Changing Position Combination ("View: move panel to Right/Left/Bottom"). So, for example, you can have shortcut to `TogglePanelToBottom` and another one for `TogglePanelToRight`. 

I think vscode already had such functionality, but it was removed for some reason.

**Comment by sbatten** [comment]
When the panel is moved with e.g. `Move Panel Right`, the panel is made visible even if it is not already. What would this new command do differently?

**Comment by butuzov** [comment]
It will hide it. In this case,  user will need to remember a keyboard shortcut less.

**Comment by butuzov** [comment]
Actually even adding to `vscode` when the condition that indicates that panel is open will help.
In this case its will possible to set same keybinding for let's say `Move Panel Right` and `Toggle Panel`, but run `Toggle Panel` with crated when condition.

e.g.
```json
 {
        "key": "cmd+right",
        "command": "workbench.action.positionPanelRight"
},
{
        "key": "cmd+right",
        "command": "workbench.action.togglePanel",
        "when": "positionPanel == 'right' && panelIsVissible"
},
{
        "key": "cmd+j",
        "command": "-workbench.action.togglePanel"
},
```

**Comment by butuzov** [comment]
Damn. Guys, you really need to write more docs. I did some source digging.

```json
    {
        "key": "cmd+right",
        "command": "workbench.action.positionPanelRight"
    },
    {
        "key": "cmd-right",
        "command": "workbench.action.togglePanel",
        "when" : "activePanel != '' && panelPosition == 'right'"
    },
    {
        "key": "cmd+down",
        "command": "workbench.action.positionPanelBottom"
    },
    {
        "key": "cmd-down",
        "command": "workbench.action.togglePanel",
        "when" : "activePanel != '' && panelPosition == 'bottom'"
    },
```

P/S/
Closing as solved.
