### ISSUE TITLE
SERVERLESS Debugger don't attach #bug #serverless #aws

### ISSUE THREAD

**Issue by henriquetgoncalves** [microsoft/vscode#102145]
Hello,

I'm getting an error when i'm trying to debug a AWS Serverless Project in VSCode v1.4.7.

This problem ocurred after the last update. Can you help with this problem, please?

Thank you,
Henrique

**Comment by weinand** [comment]
What serverless debugger are you using?

**Comment by henriquetgoncalves** [comment]
I'm using the serverless offline for debugging by  package.json script. I'm sending the line below. I can tell you more information

"scripts": {
"debug": "SET SLS_DEBUG=* && SET NODE_ENV=testing&&  SET VERTICAL=industrial&& node --inspect-brk ./node_modules/serverless/bin/serverless offline -s dev",

"devDependencies": {
	"moment-timezone": "0.5.27",
	"serverless": "^1.60.5",
	"serverless-delete-loggroups": "0.3.1",
	"serverless-domain-manager": "3.3.0",
	"serverless-offline": "^5.12.1",
	"serverless-offline-scheduler": "0.4.0",
	"serverless-plugin-custom-roles": "1.1.1",
        "serverless-plugin-split-stacks": "1.9.2",
	"serverless-tag-api-gateway": "1.0.0",
	"serverless-tag-cloud-watch-logs": "1.0.0",
	"serverless-tag-sqs": "1.0.0"

Thank you.

**Comment by weinand** [comment]
Sorry, but this functionality is not VS Code's built-in functionality. This must be some extension your are using. Please file this issue against this extension.

**Comment by henriquetgoncalves** [comment]
Hi Weinand,

This is a litle strange, because I disabled all my extensions, and this issue just began when I updated my VSCode... Reinstaling the VSCode v1.42 the issue don't apear. I will use this app version.


Thank you

**Comment by weinand** [comment]
If you want us to look into your issue you will have to provide reproducible steps.
Based on your initial description I have no clue what this issue is all about and how to reproduce it.

In addition I don't understand why you went back to VS Code 1.42 if the issues occurred in 1.47.
A more sensible step would be to go back to 1.46, right?

**Comment by henriquetgoncalves** [comment]
Hi Weinand,

Sorry by not being able to show you  more details of this issue, but I returned to v1.42 because this was my version used before update.

I don't know how can I show you more informations. Can you help me?

Thank you a lot,

**Comment by weinand** [comment]
How does your bug configuration (launch.json) looks like?

**Comment by henriquetgoncalves** [comment]
Hi Weinand,

I'm running the "debug" below script, using "npm run" or in "NPM Scripts" menu running in Debug mode.

"debug": "SET SLS_DEBUG=* && SET NODE_ENV=testing&& SET VERTICAL=industrial&& node --inspect-brk ./node_modules/serverless/bin/serverless offline -s dev"

The script work's fine in v1.42.

Thank you a lot,

**Comment by weinand** [comment]
Sorry, but the npm script only shows how you start your program in debug mode.

It does not show how you actually debug this in VS Code.
Are you using a launch configuration (in launch.json) or are you using the "autoattach" feature?

**Comment by connor4312** [comment]
@henriquetgoncalves it sounds like you may be hitting https://github.com/microsoft/vscode/issues/99526#issuecomment-640771550

As an alternative, you can create a configuration launch.json that does what you need:

```

{
  "type": "node",
  "request": "launch",
  "program": "./node_modules/serverless/bin/serverless",
  "args": ["-s", "dev"],
  "env": {
    "SLS_DEBUG": "*",
    "NODE_ENV": "testing",
    "VERTICAL": "industrial",
  },
  "stopOnEntry": true
}
```

**Comment by connor4312** [comment]
Hi, following up on this issue after feedback from you and other users. There are two things to know:

1. If you don't need to debug on the first line of your program, it's actually safe to just remove `--inspect-brk` from your npm scripts with the new debugger. Previously, it was useful to prevent your program from running before VS Code could attach to it, but this is no longer necessary.

1. We've added some change to gracefully fall back (with a warning) when running a program with --inspect-brk in the config. This flag prevents us from being able to attach to children and unlock some additional new functionality, but it should work. This change will be available in the recovery release coming next week, and is available on our [nightly extension](https://github.com/microsoft/vscode-js-debug/#nightly-extension).

Happy Coding!

**Comment by henriquetgoncalves** [comment]
Hi guys,

First thank you for all suply. I will test the alternatives said here. I realy using debug with "autoattach". I'll show you the result.

Thank you a lot.

**Comment by henriquetgoncalves** [comment]
Hi Guys,

I tried include two launch configuration like @connor4312 has been oriented, but don't worked for me. I will continue trying and will report to you.

Thank you.

**Comment by connor4312** [comment]
Does removing --inspect-brk not work for you? What issue are you running into?
