### ISSUE TITLE
vscode online | working against Azure DevOps repository | moving file to another folder + renaming it --> file is deleted

### ISSUE THREAD

**Issue by dudu-markovitz** [microsoft/vscode#102141]
I have cloned my code from Azure DevOps to visual studio online.
I dragged a file from one directory to another one and then renamed the file.
When I pressed the Source Control Icon and checked the changes, the only change exists was the deletion of the file from the original folder. 
Committing the changed indeed cause the file to be deleted from the repository. 

Visual Studio Code - Insiders
Version: 1.47.0-insider
Commit: b9d7ec9ff367a8e59fe4cc2abee605a55be180e8
Date: 2020-06-19T22:25:04.581Z (2 wks ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.478.61

**Comment by joaomoreno** [comment]
Did you move it outside of the repository? Is the folder to which you moved it into ignored by git?
