### ISSUE TITLE
Debug error on multiple root folder project

### ISSUE THREAD

**Issue by tzurp** [microsoft/vscode#102280]
![ss](https://user-images.githubusercontent.com/45478235/87242461-80b6dd00-c435-11ea-9ca0-3f02eee562d5.jpg)
Issue Type: <b>Bug</b>

The error started after updating to v1.47.0 and disappeared when rverted back to v1.46.x.
I have a multiple root folder project that is configured to use the debug function. After upgrading to 1.47.0 I encountered the following problems:
1. The debug is attached unwillingly when calling tsc --build for example.
2. When clicking the debug button, an error window message appears with "${workspaceFolder) can not be resolved in a multi folder workspace. Scope this variable usin ':' and a workspace folder name" although it is scoped properly.
Thanks

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

**Comment by connor4312** [comment]
Thanks for the issue

> The debug is attached unwillingly when calling tsc --build for example.

This will be fixed in the recovery release which will add (and set a default) to only attach to node programs started with --inspect, see https://github.com/microsoft/vscode-js-debug/commit/6932b620d6d5ea697a1a1cd00f5bdb07b9167ee6

> When clicking the debug button, an error window message appears with "${workspaceFolder) can not be resolved in a multi folder workspace. Scope this variable usin ':' and a workspace folder name" although it is scoped properly.

Can you please share your launch configuration?

In the meantime you can use the old debugger by setting `debug.javascript.usePreview: false` in your user configuration

**Comment by tzurp** [comment]
Attaching the launch part of the workspace file:

`"launch": {
                             "configurations": [
                             {
                                           "type": "pwa-node",
                                           "request": "launch",
                                           "name": "Debug Tests",
                                           "program": "${workspaceFolder:node_modules}/@wdio/cli/bin/wdio.js",
                                           "cwd": "${workspaceFolder:...}/..",
                                           "console": "integratedTerminal",
                                           "args": [
                                                         "${workspaceFolder:configs}/wdio.per.loc.stg.ui.conf.js"
                                           ],
                                           
                                           "skipFiles": [
                                                          "${workspaceFolder:...}/out/**/*.js"
                                           ]
                             }
                             ],
                             "compounds": []
              }
`

**Comment by connor4312** [comment]
Thank tzurp. Unfortunately I'm having a hard time getting this to reproduce on my machine with the configuration you provided.

This was my workspace configuration -- using [the node "demos" folder](https://github.com/microsoft/vscode-js-debug/tree/master/demos/node) and then another empty folder:

```
{
	"folders": [
		{
			"path": "C:\\Users\\Connor\\Downloads\\foo"
		},
		{
			"path": "C:\\Users\\Connor\\Documents\\Github\\vscode-js-debug\\demos\\node"
		}
	],
	"launch": {
		"configurations": [
			{
				"type": "pwa-node",
				"request": "launch",
				"name": "Debug Tests",
				"program": "${workspaceFolder:node}/main.js",
				"cwd": "${workspaceFolder:node}/..",
				"console": "integratedTerminal",
				"args": [
					"${workspaceFolder:node}/wdio.per.loc.stg.ui.conf.js"
				],
				"skipFiles": [
					"${workspaceFolder:node}/out/**/*.js"
				]
			}
		],
		"compounds": []
	},
	"settings": {}
}
```

This worked running on VS Code 1.47.2.

Please make sure you're up to date with js-debug (the latest is version 1.47.5). If you previously installed the nightly, make sure that's up to date as well (the latest is 2020.7.1611). If you're still having trouble it'd be very helpful if you can create a small example/repo where this problem occurs.

**Comment by lSoleyl** [comment]
Also having this issue and cannot launch my existing debug configurations anymore.
I created a simple test setup to reproduce this issue and it looks as follows:

`C:\Users\xx\Desktop\test` 
 * `workspace.code-workspace`
 * `main`
    * `index.js`
 * `utils`

I inserted the  full workspace definition below. As you can see there is no reference to `${workspaceFolder}` anymore, I just inserted the full path. I also tried the following paths always with the same error message:
 * `${file}`  (as was autogenerated by launch config generator)
 * `${workspaceFolder:main}\\index.js`

When just opening the `main` folder with VSCode (as single folder workspace) and generating a debug configuration, everything works fine.

`test\workspace.code-workspace`:
```
{
	"folders": [
		{
			"path": "main"
		},
		{
			"path": "utils"
		}		
	],
	"settings": {},
	"launch": {
		"version": "0.2.0",
		"configurations": [
			{
				"type": "node",
				"request": "launch",
				"name": "Launch Program",
				"skipFiles": [
					"<node_internals>/**"
				],
				"program": "C:\\Users\\xx\\Desktop\\test\\main\\index.js"
			}
		]
	}
}
``` 

Hope this additional info helps with reproducing the issue.
I also disabled all extensions except for `ms-vscode.js-debug` (installed version is 1.47.5) for this workspace.

VSCode version dump:
```
Version: 1.47.2 (system setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by connor4312** [comment]
@lSoleyl try setting your `type` to `pwa-node`

**Comment by lSoleyl** [comment]
Thanks. I don't quite understand why this fixed it, but it now works. Is `"type":"node"` deprecated or does it simply not support multi folder workspaces anymore?

**Comment by connor4312** [comment]
`type: node` has its config resolved using the old debuggers and then redirects the debug request to the new debugger. With `type: pwa-node`, the config is resolved by the new debugger directly, which is able to fill out the options that the old debugger doesn't know about.
