### ISSUE TITLE
Linters fail to work after the version update

### ISSUE THREAD

**Issue by Stephn-R** [Microsoft/vscode#10229]
- VSCode Version: 1.4.0
- OS Version: Mac (El Capitan) 10.11.16

Steps to Reproduce:

1. Download ESLint from the marketplace
2. Enable it by reloading Visual Studio Code
3. Attempt to generate an eslint error (i.e. Write an incomplete function declaration)
4. No errors show when an error should be detected

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-eslint#110

**Comment by dbaeumer** [comment]
Moving to eslint repository.
