### ISSUE TITLE
jupyter notebook  cannot save file anyway

### ISSUE THREAD

**Issue by yyouan** [microsoft/vscode#102232]
Issue Type: <b>Bug</b>

I cannot use icon or commad-s to save file on jupyter notebook somtimes ,and the auto-save didn't work too. I am despair.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|-psn_0_3330861|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
c-cpp-compile-run|dan|1.0.11
gitlens|eam|10.2.2
pyformat|giy|1.0.1
epsilon-eag|gra|0.0.5
Python-autopep8|him|1.0.2
vscode-gutter-preview|kis|0.26.2
git-graph|mhu|1.24.0
vscode-clang|mit|0.2.3
python|ms-|2020.6.91350
cpptools|ms-|0.28.3
postscript|mxs|1.0.1
open-in-browser|tec|2.0.0
html-preview-vscode|tht|0.2.5
pdf|tom|1.0.0
local-history|xyz|1.8.1

</details>

**Comment by Attrams** [comment]
I also face this problem sometimes.

**Comment by GanjinZero** [comment]
Same.
