### ISSUE TITLE
Annoying Editor Selector when New File from File menu

### ISSUE THREAD

**Issue by ericvan76** [microsoft/vscode#102289]
- VSCode Version:  1.47.0
- OS Version: macOS Catalina 10.15.5

Steps to Reproduce:
Every time when I click File -> New File, vscode always asks to select an Editor, but in the list, there is only one Built-in Text editor. it's just a very annoying unnecessary click. 
I don't know since when this has been added, I believe it's a recent change.

Tried to remove all the User settings and start without extensions, didn't help.

See the screenshot. 
<img width="1086" alt="Screen Shot 2020-07-12 at 9 35 03 pm" src="https://user-images.githubusercontent.com/148174/87245947-ea140b80-c488-11ea-8060-88d8eec2724b.png">

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by pfongkye** [comment]
Hi,
I would like to work on this issue if no one else is.

**Comment by zcfan** [comment]
> Hi,
> I would like to work on this issue if no one else is.

Sorry I did't claim before starting, I have fixed it, please correct me if the solution is not ok.

**Comment by RXDA** [comment]
I have same problem

**Comment by RXDA** [comment]
I removed all the User settings and extensions, useless

**Comment by pfongkye** [comment]
> > Hi,
> > I would like to work on this issue if no one else is.
> 
> Sorry I did't claim before starting, I have fixed it, please correct me if the solution is not ok.

No worries. Go ahead 👍
