### ISSUE TITLE
VSCode tries (and fails) to attach debugger to npm scripts

### ISSUE THREAD

**Issue by AntoineChwat** [microsoft/vscode#102211]
Issue Type: <b>Bug</b>

I have a clean install of VSCode with WSL Remote (running WSL1, my Surface Book 3 still doesn't support Windows 2004). Whenever I try to run an npm script (through the npm script explorer or through the integrated terminal) the prompt says "debugger listening on ws://127.0.0.1:..." and then doesn't start anything. I tried disabling/enabling auto attach (which doesn't even show up in my status bar) but nothing works, it's still trying and failing to debug each and every npm script and I can't run anything. Interesting to note that it only started failing to attach the debugger after webpack crashed the integrated terminal when trying to run a Vue.js application on the step "95% emitting HtmlWebpackPlugin" (a command which runs perfectly well on the standard Ubuntu terminal).

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (8.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|Memory (System)|15.60GB (8.66GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.6
mongodb-vscode|mon|0.0.4
python|ms-|2020.6.91350
vetur|oct|0.24.0
remote-wsl|ms-|0.44.4

</details>

**Comment by timrbula** [comment]
@AntoineChwat By disabling the auto attach, do you mean you set `"debug.node.autoAttach": "off",` in the settings.json? That fixed the issue for me

**Comment by AntoineChwat** [comment]
Yep, that's exactly what I did. I tried to simply set it to "disabled" and then set to "off" completely everywhere (in user, remote and workspace) but it's still trying to attach to the debugger somehow

**Comment by connor4312** [comment]
@AntoineChwat can you try the following:

1. Run `rm /tmp/node-cdp.*`
1. Reload the window
1. Set `debug.node.autoAttach` to "on". Wait a moment.
1. Set `debug.node.autoAttach` to "disabled". Wait a moment.
1. Open a terminal and see if you're in a good state

**Comment by AntoineChwat** [comment]
Just tried it and it works, both from the integrated terminal and from the script explorer, thank you so much! It was driving me nuts not to be able to use any of these tools, thanks a lot

**Comment by connor4312** [comment]
Ok, thanks for confirming. This duplicates https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467 then

/duplicate
