### ISSUE TITLE
Ctrl+Shift+1 keybinding doesn't work to replace selected text when using Ctrl+H window

### ISSUE THREAD

**Issue by BrandonRice** [Microsoft/vscode#10220]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open/Create standard HTML File
2. Create the following input line: `<input type="text" name=variable1 size="10" value="">`
3. Press keybinding Ctrl+H to open find/replace window.
4. Enter RegEx string to Find:  `(\bname=\b)(([a-zA-z])+\b)`
5. Enter RegEx string to Replace: `$1"$2" id="$2"`
6. Press F3 to find first instance
7. Press Ctrl+Shift+1

We noticed the id tag was missing from some input variables so and also the quotations around the variable declared name so I created a RegEx expression to find and replace them.

RegEx for find window: `(\bname=\b)(([a-zA-z])+\b)`
RegEx for replace window: `$1"$2" id="$2"`

This finds any match on "name=anyword" where there are no quotes around the variable declared value and replaces it with `name="anyword" id="anyword"`

I was trying to speed up the process so I went to use the keybinding for Replace which when you hover above the Replace icon says the binding is "Ctrl+Shift+1".  When I press that key combination all at once or in sequential order, nothing happens.

**Comment by alexandrudima** [comment]
@BrandonRice I can reproduce on 1.4.0, but on master this works for me. The fix will come out with the August stable release or you can use the insiders channel.

**Comment by alexandrudima** [comment]
Note: I had to change the search regex to `(\bname=\b)(([a-zA-z0-9])+\b)` to accept numbers too

**Comment by BrandonRice** [comment]
> Note: I had to change the search regex to (\bname=\b)(([a-zA-z0-9])+\b) to accept numbers too

Thank you for pointing out the regex error.  I think I also need to update the regex to be 
`(\bname=\b)(([a-zA-Z0-9])+\b)`  where A-z is changed to A-Z to account for all upper case alpha characters. 

Looking forward to the next release!
