### ISSUE TITLE
VS Code Memory consumption rise to > 3 GB

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/vscode#102256]
Issue Type: <b>Performance Issue</b>

I have two TypeScript projects opened but not doing anything.  This morning I took a look at Task Manager and found VS Code consumes > 3.3 GB memory.  The Process List window show that it is the main.

I also noticed that at one time the usage dropped to 2.2 GB, I saved a dump file using Task Manager.  After that, the usage is back to > 3.3 GB.

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.98GB (1.98GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	  3392	 22156	code main
    9	    45	  1124	   shared-process
    0	    11	  2548	   electron-crash-reporter
    0	   178	  4852	   window (baseRecorder.ts - test-utils - Visual Studio Code)
    0	    13	 18412	     watcherService 
    0	     6	 20636	       console-window-host (Windows internal process)
    0	    70	 19364	     extensionHost
    0	    24	  7312	       electron_node eslintServer.js 
    0	    37	  8296	       electron_node tsserver.js 
    0	    25	 11104	       electron_node server.js 
    0	    97	 17932	       electron_node tsserver.js 
    0	    24	 10676	         electron_node typingsInstaller.js typesMap.js 
    0	    23	 18344	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=19364
    0	    25	 19144	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=19364
    1	    71	  8708	   window (Issue Reporter)
    0	    62	 14492	   window (Process Explorer)
    0	   138	 16376	   window (customConsoleLog.ts - storage-blob - Visual Studio Code)
    0	    98	  1128	     extensionHost
    0	    16	  2212	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=1128
    0	    37	  2920	       electron_node tsserver.js 
    0	    12	  6224	         electron_node typingsInstaller.js typesMap.js 
    0	    22	 10216	       electron_node tsserver.js 
    0	    17	 12236	       electron_node eslintServer.js 
    0	    17	 17884	       electron_node server.js 
    0	    16	  6104	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    13	  9756	     watcherService 
    0	     6	  7664	       console-window-host (Windows internal process)
    0	     5	 21340	     console-window-host (Windows internal process)
    0	    24	 18140	   utility
    0	   303	 18856	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (customConsoleLog.ts - storage-blob - Visual Studio Code)
|  Window (baseRecorder.ts - test-utils - Visual Studio Code)
|    Folder (test-utils): 220 files
|      File types: map(56) ts(52) js(37) json(10) md(5) ps1(2) log(2) xml(2)
|                  html(2) css(2)
|      Conf files: package.json(2) tsconfig.json(2)
|    Folder (storage-blob): 2239 files
|      File types: js(583) ts(577) map(454) json(225) html(163) md(9) env(4)
|                  xml(3) css(2) nycrc(1)
|      Conf files: package.json(3) tsconfig.json(3) launch.json(1)
|                  settings.json(1)
|      Launch Configs: node(4);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.4.0
vscode-eslint|dba|2.1.6
prettier-vscode|esb|5.1.3
vscode-pull-request-github|Git|0.16.0
ilspy-vscode|ics|0.8.0
docthis|joe|0.7.1
csharp|ms-|1.22.1
remote-wsl|ms-|0.44.4
debugger-for-chrome|msj|4.12.8
vscode-yaml|red|0.8.0
trailing-spaces|sha|0.3.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Doesn't look like a TS issue from the perf info.

@jeremymeng Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jeremymeng** [comment]
Haven't been it lately
