### ISSUE TITLE
Launch debugger for FireFox/Chrome on external monitor

### ISSUE THREAD

**Issue by DiffMerge** [microsoft/vscode#102200]
I have a 2 monitor setup. 1 monitor on my laptop, and 1 external display. I'm running Windows 10 2004. On Windows I have the FireFox Developer Edition and Google Chrome browsers configured, so that they open on my external monitor full screen. 

In VSCode (1.47) I have 2 debuggers configured via launch.json. FireFox Debugger extension and Google Chrome Debugger extension. When I run the debugger via a Launch Firefox or Launch Chrome option, the browsers open on my 1st monitor and not full screen, which is not ideal. 

I would like to request a feature that will open the browsers on my external monitor full screen, so that the settings are taken from the system. Currently VSCode ignores the system settings and launches the browsers anew on my 1st screen.

**Comment by connor4312** [comment]
At least for Chrome, you may be able to set the --window-position in your runtime args: https://peter.sh/experiments/chromium-command-line-switches/#window-position

**Comment by connor4312** [comment]
Moving to backlog -- probably won't implement a setting for this, but I would like to verify that it is possible to create a setting that does this.

**Comment by connor4312** [comment]
There have been no 👍's on this, so I will suggest that as your solution: use [--window-position](https://peter.sh/experiments/chromium-command-line-switches/#window-position) and [--start-maximized](https://peter.sh/experiments/chromium-command-line-switches/#start-maximized).
