### ISSUE TITLE
Opening a Windows directory from WSL 2 causes several Git malfunctions

### ISSUE THREAD

**Issue by adrianghc** [microsoft/vscode#102243]
- VSCode Version: 1.47.0
- OS Version: Windows 10 19041.330

When opening a Windows directory from WSL 2, there are several problems with the Git experience in VS Code.

One of them is part of what is described in issue #101507:

> When making a change to any file in the project it doesn't show up in the Source Control tab on the left sidebar, unless I close and reopen VS Code or manually click on "Synchronize Changes"

The other occurs when git adding changes from a file editor. git adding part of the changes to a file from the editor reverts all changes to the same file that were previously added. I've made a recording that shows this problem:

![VS Code git add issue](https://user-images.githubusercontent.com/11506007/87232370-b40a5500-c3be-11ea-9170-c3abdd010136.gif)

I don't know if this occurs with WSL 1 and whether this issue manifests itself in other ways besides those two.

**Comment by joaomoreno** [comment]
>Windows directory from WSL 2

This is not recommended.

If you open a Windows folder, don't do it from the WSL side, simply use Git for Windows.

**Comment by adrianghc** [comment]
Well, the idea is that maybe you have a project that you want to build for both Windows and Linux, then you'd want to open the project from both Windows and WSL. One way to do this is simply having the project inside a Windows directory. After all, there is a reason why you are able to open Windows directories from WSL.
This said, I do understand why you don't feel like investing work in fixing this scenario.
