### ISSUE TITLE
No public repository option in "Publish to GitHub"

### ISSUE THREAD

**Issue by jlave-dev** [microsoft/vscode#102268]
Issue Type: <b>Bug</b>

1. Open a folder.
2. Open Source Control panel.
3. Click "Publish to GitHub".

A selector opens up with the option to "Publish to GitHub private repository," but there isn't an option for a pubilc repository. I would expect both public and private repo options to appear.

<img width="638" alt="Screen Shot 2020-07-11 at 11 49 42 PM" src="https://user-images.githubusercontent.com/30740613/87239184-bfb34700-c3d1-11ea-8832-14ab27edcadf.png">

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.6
todo-tree|Gru|0.0.178
dotenv|mik|1.0.1
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
remote-containers|ms-|0.128.0
vscode-react-native|msj|0.16.1
vetur|oct|0.24.0
vscode-sort-json|ric|1.18.0
code-settings-sync|Sha|3.4.3

</details>

**Comment by joaomoreno** [comment]
We didn't want to overcomplicate this UI, especially since it's fairly straightforward to make the repository public after you create it in GitHub.
