### ISSUE TITLE
disable preview in custome tree view

### ISSUE THREAD

**Issue by hamednm87** [microsoft/vscode#102265]
Issue Type: <b>Bug</b>

hi
I create an extension and use tree view in my extension, beffore of install version 1.47 preview open disable and double click on items worked but when install version 1.47 preview open active and double click on item do not work.(by single click on tree view item, it open)
thanks

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.6
tslint|eg2|1.0.44
cobol-isc|h-n|0.0.2

</details>

**Comment by alexr00** [comment]
@hamednm87 can you provide a screen capture showing what you mean? Are you referring to the setting `workbench.list.openMode`? I am still seeing that setting apply correctly to extension contributed trees.
