### ISSUE TITLE
Marketplace: kbd tag not supported in extension readme

### ISSUE THREAD

**Issue by johnbillion** [microsoft/vscode#102222]
## Problem

It's useful to be able to use the `<kbd>` tag in the readme file of an extension. This works as expected on GitHub, but the tag gets stripped out when the readme is shown on the VS Code marketplace.

## Example

One of my extensions includes the following FAQ:

---

### How can I trigger the autocomplete list if it doesn't show up?

Place your cursor within the first parameter of one of the supported functions and hit <kbd>ctrl</kbd>+<kbd>space</kbd>. This works with any autocomplete provider, not only this extension.

---

Observe that here on GitHub the `<kdb>` elements render appropriately, [but it does not do so for my extension here on the Marketplace](https://marketplace.visualstudio.com/items?itemName=johnbillion.vscode-wordpress-hooks).

It would be great if this element was supported.

**Comment by joaomoreno** [comment]
Upstream issue has been created.
