### ISSUE TITLE
Cannot find module 'Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js'

### ISSUE THREAD

**Issue by ati0ns** [microsoft/vscode#102249]
```
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'c:/Users/El�ve/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1346:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
```

- VSCode Version: 1.47.0
- OS Version: What is this ?

Steps to Reproduce:

1. I don't know.
2. I still don't know.

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by anoopijt** [comment]
I am also getting similar issue

`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '"c:/Users/sesa431134/AppData/Roaming/Code/User/workspaceStorage/75338e7a00267faffc18d3c9e47379ab/ms-vscode.js-debug/bootloader.js"'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:901:12)
    at preloadModules (internal/bootstrap/node.js:602:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)`

System details
Version: 1.47.0 (system setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z (2 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by connor4312** [comment]
This is the same as https://github.com/microsoft/vscode-js-debug/issues/563.

For the moment you can set `debug.javascript.usePreview: false` to use the old debugger.

/duplicate

**Comment by ati0ns** [comment]
> 
> 
> This is the same as [microsoft/vscode-js-debug#563](https://github.com/microsoft/vscode-js-debug/issues/563).
> 
> For the moment you can set `debug.javascript.usePreview: false` to use the old debugger.
> 
> @anoopijt you can fix your issue by setting `debug.node.autoAttach` to disabled and then reloading vscode/reopening terminals. Fix for that is on the way.
> 
> /duplicate

This issue says that UTF-8 character is a problem but I always had UTF-8 character without problem before yesterday.

**Comment by connor4312** [comment]
Yes, we have a new debugger now which does things differently. I will be fixing this early next week.

**Comment by markeissler** [comment]
@connor4312 How is the issue reported by @ati0ns the same as [microsoft/vscode-js-debug#563](https://github.com/microsoft/vscode-js-debug/issues/563)? I'm seeing the same thing right now using WSL2 with a remote container.

I added both `ms-vscode.js-debug` and `ms-vscode.js-debug-companion` to `devcontainer.json` and rebuilt the container...the issue persists. I added `debug.node.autoAttach="disabled"` to the remote, rebuilt the container... and the issue persists. I addded `debug.javascript.usePreview: false` to the global settings (locally) and that solved the problem...meaning, disabling the new debugger was the only fix here that worked.

Since disabling the preview all together fixes this, I removed the setting locally and added it to `devcontainer.json` and then it continues to work from there.

IMHO, this is still a bug and different from the referenced bug.

**Comment by connor4312** [comment]
@markeissler what's the output/error you're seeing on the console?

**Comment by markeissler** [comment]
@connor4312 I edited my comment as I referenced the incorrect output. But, the output from @anoopijt (https://github.com/microsoft/vscode/issues/102249#issuecomment-657127530) was the same thing I was seeing. If I disabled the new debugger all together everything was working again. But I did restart VSCode at some point after that in it updated the remote server...which is weird because it didn't do that previously.

Everything seems to be working this morning even with the following settings removed from `devcontianer.json`:

```
        "debug.node.autoAttach": "disabled",
        "debug.javascript.usePreview": false,
```

And `debug.javascript.usePreview: true` is still enabled in the local settings. `We'll see how things go throughout the day. Maybe just restarting and updating the vscode server in the container fixed it.

**Comment by connor4312** [comment]
Outcome and workaround: https://github.com/microsoft/vscode-js-debug/issues/563#issuecomment-659592018

**Comment by eric-burel** [comment]
I am hitting a similar issue on Ubuntu 18:

```
Cannot find module '"/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js
```

**Comment by connor4312** [comment]
@eric-burel you can get around this by adding `nodeVersionHint: 10` in your launch.json. However please also share your launch config so I can make sure we handle that case correctly -- the hint is only given as a bail-out and we should automatically detect the version in most cases.

**Comment by eric-burel** [comment]
Here it is :
```js
{
  "version": "0.2.0",
  "nodeVersionHint": 10,
  "configurations": [
    // work ok, expect server to run already
    {
      "type": "chrome",
      "request": "launch",
      "name": "Next: Chrome",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}",
      "env": {
        "NODE_OPTIONS": "--inspect"
      },
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ]
    },
    // TODO: not working, VS code tries to open its own port 9229 multiple time (changing port with inspect=9300 does not work either)
    {
      "type": "node",
      "request": "launch",
      "name": "Next: Node",
      "runtimeArgs": ["--project", "tsconfig.server.json", "server/index.ts"],
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/ts-node",
      //"runtimeExecutable": "${workspaceFolder}/node_modules/next/dist/bin/next",
      "port": 9229,
      "console": "integratedTerminal",
      // @see https://github.com/TypeStrong/ts-node/issues/537
      "env": {
        "NODE_OPTIONS": "--inspect"
      },
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ]
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Jest All",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "args": ["--runInBand"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest"
      }
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Jest Current File",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "args": ["${fileBasenameNoExtension}", "--config", "jest.config.js"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest"
      }
    }
  ],
  "compounds": [
    {
      "name": "Next: Full",
      "configurations": ["Next: Node", "Next: Chrome"]
    }
  ]
}
```
Note that my config maybe never have worked in the first place, I've wrote this months ago, I just try to run it today. But the error message is still cryptic.

**Comment by SebastiaoMoraes** [comment]
Não consegui resolver. Problema infinito. Editor excelente, mas esses problemas são um saco. Usuario nao tem suporte nenhum.
