### ISSUE TITLE
Error when updating VS Code Server on WSL2 / Ubuntu

### ISSUE THREAD

**Issue by einarpersson** [microsoft/vscode#102284]
- VSCode Version: Unknown (latest?), writing `code --version` prompts an update which fails
- OS Version: Ubuntu 18.04 running on WSL2 Windows 10 Pro

Steps to Reproduce:

1. Trying to start vscode from WSL2 Ubuntu 18.04 (in Windows terminal) as `code .` starts an update which fails. I have been using VSCode under WSL2 for a long time and this is the first time the update fails. The output is the following:

````
Updating VS Code Server to version d5e9aa0227e057a60c82568bf31c04730dc15dcd
Removing previous installation...
Installing VS Code Server for x64 (d5e9aa0227e057a60c82568bf31c04730dc15dcd)
Downloading: 100%
Failed
--2020-07-12 00:10:35--  https://update.code.visualstudio.com/commit:d5e9aa0227e057a60c82568bf31c04730dc15dcd/server-linux-x64/stable
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘update.code.visualstudio.com’
ERROR: Failed to download https://update.code.visualstudio.com/commit:d5e9aa0227e057a60c82568bf31c04730dc15dcd/server-linux-x64/stable to /home/einar/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd-1594505425.tar.gz
````

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by einarpersson** [comment]
I went around the problem by opening VSCode on the Windows 10 Pro system, and from there open a WSL2 Remote. That started the upload process and for some reason this worked. After that I tried once more in the Ubuntu terminal and now it worked.

I have no idea why though.

**Comment by aeschli** [comment]
When `code` is run from the WSL we try to download from the WSL shell. When opening a WSL window fist, it's done from the Windows side.

This looks like a network issue in the WSL. Maybe you are behind a prozy? See here for more information: https://code.visualstudio.com/docs/remote/wsl#_im-behind-a-proxy-and-have-connectivity-issues
