### ISSUE TITLE
Settings file cannot be a symlink

### ISSUE THREAD

**Issue by rogierlommers** [Microsoft/vscode#1022]
The settings file (~/Library/Application Support/Code/User/settings.json) cannot be a symbolic link. Don't know why, but the editor is complaining about when the file is in fact a symlink. Please see screenshot for an example.

However, if the it's a hardlink, then everything is okay. The reason for this issue is that I would like to add the vscode settings file to my dotfiles repository.

![screen shot 2015-12-04 at 19 52 13](https://cloud.githubusercontent.com/assets/3907131/11598202/c52ef538-9ac0-11e5-89f5-e52edbaee10b.png)

**Comment by Tyriar** [comment]
I've been using a symlink for my settings.json and keybindings.json on Ubuntu for a week or two now with no problems.

**Comment by rogierlommers** [comment]
Strange, On OSX El Capitan (0.11.1 (15B42)) it does not work, see my attached screenshot above. Only a hardlink works.

**Comment by ClockworkPirate** [comment]
I use symlinks for my settings.json on both OS X (10.11.1) and Windows (10 1511); no problems here either.

**Comment by rogierlommers** [comment]
@ClockworkPirate thanks! Strange why it's not working here. I'll give it another try... will keep thread posted.

**Comment by rogierlommers** [comment]
FYI, I'm using the sync extension which syncs all settings to a github gist. Works fine and multi-platform.

**Comment by ayrtonmassey** [comment]
Are you sure that the symlink was created correctly? I had this problem but I was running the command:

```powershell
cmd /c mklink C:\Users\me\AppData\Roaming\Code\User\settings.json .\.vscode\settings.json
```

but you need to provide the absolute path to the target:

```powershell
cmd /c mklink C:\Users\me\AppData\Roaming\Code\User\settings.json C:\git\config\.vscode\settings.json
```

You can check if your symlink was created correctly by viewing its filesize (should be nonzero), or running:

```powershell
Get-Content TARGET
```

where `TARGET` is the path to the symlink. If it spits out the content you expect, it's fine. If it gives you an error then you created the link incorrectly.
