### ISSUE TITLE
Opening project from command line creates an editor tab for file: C:\Code.EXE

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#102214]
- VSCode Version: 1.44.2
- OS Version: Windows 8.1

Steps to Reproduce:

1. Create a folder `C:\Projects\my-pytest`
1. Launched VSC through Windows Menu
1. Open the project folder, add a src py-file and a test py-file in a subdir `tests`, enable `pytest` and run the tests.
1. Some files are open and saved
1. exit VSC
1. Start a `cmd.exe` terminal
1. execute the command `"C:\Program Files\Microsoft.VS.Code\Code.exe" C:\Projects\my-pytest`
1. all previous open editors tabs are gone and there is now an editor tab for the file `C:\Code.EXE` and marked as modified (dot in tab label)
1. Close VSC, Do not save modified file.
1. Opening a different project from the command line `C:\Projects\my-app` and all previous editor tabs are there
1. Close VSC.
1. execute the command `"C:\Program Files\Microsoft.VS.Code\Code.exe" C:\Projects\my-pytest`
1. Close the tab for `C:\Code.EXE` and do not save
1. Open a file from the project, it is shown in preview, use `CTRL+K Enter` (workbench.action.keepEditor)
1. Close VSC.
1. execute the command `"C:\Program Files\Microsoft.VS.Code\Code.exe" C:\Projects\my-pytest`
1. it now shows the previous open file

I can't get the project in the error state anymore after the workbench.action.keepEditor command.

Instead of showing the Welcome screen for a project in a particular state it opened with an editor tab for `C:\Code.EXE`. Better would be a file `untitled.txt` in the opened workspace

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
Use `code`, never `Code.exe`.
