### ISSUE TITLE
vscode crashes on opening any dialog

### ISSUE THREAD

**Issue by exprosic** [microsoft/vscode#102247]
- VSCode Version:(1.47.0, d5e9aa0227e057a60c82568bf31c04730dc15dcd, x64, snap)
- OS Version: Manjaro 20.0.3

Steps to Reproduce:

1. Open VSCode
2. Click Help->About, or "Open folder", or "Add workspace folder"
3. VSCode quits with no message.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by exprosic** [comment]
@bpasero The bug turns out to even mess with the crash reporting process.

```
$ time code --crash-reporter-directory vscode_crash/; echo EXIT=$?

real	0m0,203s
user	0m0,144s
sys	0m0,063s
EXIT=0
$ time code; echo EXIT=$?

real	0m0,204s
user	0m0,124s
sys	0m0,083s
EXIT=0
```
The first execution shows no UI. The second one runs normally and quits silently following the procedures described before.
Nothing is logged in nowhere.

**Comment by bpasero** [comment]
Thanks, this probably is a Linux Snap issue then.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/100940 , @exprosic please subscribe to that issue for updates.
