### ISSUE TITLE
Remember windows terminal (cmd) position when closed and re-opened

### ISSUE THREAD

**Issue by alvipeo** [microsoft/vscode#102208]
I have multiple monitors (as many others) and I do not use embedded terminal because it takes up real estate. So I always use __cmd.exe__ and I place it to the second monitor (and not full screen). Obviously, when I close VSCode and then open it again, and then open __cmd__ with Ctrl+Shift+C, it appears just over the editor. I wonder if it's possible to keep cmd position over sessions.

It's a minor one but I think it would be very useful to users.

**Comment by Tyriar** [comment]
I don't believe this is possible
