### ISSUE TITLE
JSDoc comments no longer show up when hovering symbols in TypeScript and JavaScript

### ISSUE THREAD

**Issue by focorner** [microsoft/vscode#102212]
- VSCode Version: 1.47.0
- OS Version: macOS Catalina Version 10.15.5

Steps to Reproduce:

1. Create an empty folder.
2. Open the folder in latest version of VS Code.
3. Create a TypeScript or a JavaScript file.
4. In that file, create a simple class or a variable, and document it using comments.
5. Hover the class name (or other documented properties), and no documentation
shows up in the "hover box".

Does this issue occur when all extensions are disabled?: Yes

![Screenshot of hover box for a class property, with the documentation not showing up](https://user-images.githubusercontent.com/12765575/87224285-707dff80-c35a-11ea-9e4f-c93480de564e.png)

**Comment by mjbvz** [comment]
Those are not documentation (jsdoc) comments; they are normal line comments which we do not consider documentation.

For a documentation comment, make sure to use `/** documentation here */` style comments

**Comment by focorner** [comment]
Hello @mjbvz,

I am sincerely sorry about this. 

It appears that I got my languages mixed up. :)

Nonetheless, thank you for taking the time. It is much appreciated.

Have a great day! A+

Frank
