### ISSUE TITLE
"skipFiles" setting completely ignores "<node_internals>"

### ISSUE THREAD

**Issue by fabis94** [microsoft/vscode#102294]
- VSCode Version: 1.47.0
- OS Version: OSX Catalina 10.15.5

Steps to Reproduce:

1. Use "<node_internals>" inside skipfiles glob patterns
2. The editor will still step inside "<node_internals>/internal/modules/cjs/loader.js"

![image](https://user-images.githubusercontent.com/938316/87247658-d56e4e00-c45d-11ea-8e2c-ebd918d08d71.png)
Tried all kinds of glob patterns and launch settings - none of them help. Depending on the combination of settings VSCode will step inside a different <node_internals> file.

![image](https://user-images.githubusercontent.com/938316/87247674-edde6880-c45d-11ea-9100-345597975bd5.png)

Maybe it's got something to do with the fact that I'm trying to debug a package in a monorepo (something's off with the paths maybe?), but the skipFiles settings targeting node_internals are consistently ignored. Tried different TypeScript versions (3.8, 4), tried latest VSCode for Insiders as well - same thing. Also tried installing `JavaScript Debugger (Nightly) v2020.7.1117` which has the same issue - if I step inside a module import, it doesn't step inside the module source code, but inside the node internals.

Does this issue occur when all extensions are disabled?: Yes

**Comment by houstondapaz** [comment]
Same here.

- VSCode Version: 1.47.0
- OS Version: Windows 10 Home Insider Preview Single Language 20161.1000, with Ubuntu 20.04 LTS in WSL 2

In my case the editor always step into sync_hooks.js when call async functions

**Comment by connor4312** [comment]
Thanks for the issue, fixed this this morning in https://github.com/microsoft/vscode-js-debug/issues/603

/duplicate
