### ISSUE TITLE
Certificate incorrectly recognized as expired

### ISSUE THREAD

**Issue by pkruk2** [microsoft/vscode#102252]
Issue Type: <b>Bug</b>

Hi,

I have a server with valid certificate - accepted by OS browser (firefox), also following code under node v14.4.0 returns status code 302:
```
const https = require('https');
https.get(URL, res => console.log(res.statusCode)).on('error', e => console.log(e));
```

But under vscode the same code gives "Error: certificate has expired".
I've also tried node-fetch and superagent modules, same result.

The server is not visible externally unfortunately.

---

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-groovy|mar|0.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3

</details>

**Comment by joaomoreno** [comment]
> But under vscode the same code gives "Error: certificate has expired".

What do you mean under vscode? In the integrated terminal?

**Comment by pkruk2** [comment]
@joaomoreno no, in custom extension (executed as command from command palette).

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?

**Comment by pkruk2** [comment]
Here's the screenshot:

![obraz](https://user-images.githubusercontent.com/34373523/87310745-aa97fe80-c51e-11ea-8e33-88f94e2a1b30.png)

```
Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
	at TLSSocket.emit (events.js:203:13)
	at TLSSocket._finishInit (_tls_wrap.js:792:8)
	at TLSWrap.onhandshakedone (_tls_wrap.js:606:12)
```

I suspected this could be a bug in node, but I have checked that under node 12.8.1 (same version as shipped with vscode) the problem does not reproduce (certificate is accepted).

**Comment by connor4312** [comment]
Node has its own TLS cert chain. The recommended way to deal with this is leveraging the [NODE_CA_EXTRA_CERTS](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) environment variable.

/question

**Comment by pkruk2** [comment]
@connor4312 I believe the certificate is a proper certificate, not self-signed. I don't understand why would I have to specify any extra certificates? Also, as I mentioned, standalone node accepts the certificate.

**Comment by connor4312** [comment]
Ah, okay, it's a real cert. I'm not sure off the top of my head, I'd have to google for it.

But this is something that Node returns, it's not something we can affect in vscode/debugging. I'd recommend searching online, it looks like there are a few things different that can cause this.

**Comment by pkruk2** [comment]
I though that maybe vscode sets some special flags for node, or ships a modified node? That would explain the difference between standalone node and node under vscode.

**Comment by connor4312** [comment]
Are you developing an extension (running in the extension host) or just debugging a Node program from VS Code?

**Comment by pkruk2** [comment]
I'm developing vscode extension - the code from initial comment is executed from vscode command.

**Comment by connor4312** [comment]
Okay, gotcha. Reopening and sending it to the right person 🙂

**Comment by deepak1556** [comment]
This would be https://github.com/electron/electron/issues/24123 

but just to confirm, @pkruk2 can you check the root CA using `openssl s_client -showcerts -servername <server> -connect <server:443>`

**Comment by pkruk2** [comment]
Thanks @deepak1556 it looks like that's the problem. 
Does this mean that vscode needs to update it's node / electron version, or backport a fix (include new certificate for AddTrust as I understand) ?

--- 
I was able to connect to the server using the openssl command you provided. It listes the AddTrust in the certificate chain:

```
 3 s:C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
   i:C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
```

**Comment by deepak1556** [comment]
yeah this is pending a fix from electron, we will update as soon as fix is available.

**Comment by pkruk2** [comment]
Thanks :) 👍

**Comment by nornagon** [comment]
https://github.com/electron/electron/pull/25313 should fix this.
