### ISSUE TITLE
Ghost Keypresses

### ISSUE THREAD

**Issue by r270d** [microsoft/vscode#102290]
Issue Type: <b>Bug</b>

Despite running latest version of Vs code , i get strange keyboard key 8 typed on files whenever i switch form any app to vs code. there is no fault in keyboard.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:30:34.302Z)
OS version: Linux x64 4.19.113-08528-g5803a1c7e9f9

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/4e (2 x 2599)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|14.19GB (14.16GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vs-keybindings|ms-|0.2.0
LiveServer|rit|5.6.1

</details>

**Comment by gjsjohnmurray** [comment]
Does this still happen after you run the command that reloads with all extensions disabled?

**Comment by r270d** [comment]
Issue resolved after reload of extensions

**Comment by gjsjohnmurray** [comment]
@r270d please close your issue.
