### ISSUE TITLE
VisualStudio Code Intellisense can not correctly identify overloaded methods

### ISSUE THREAD

**Issue by ekr3peeK** [microsoft/vscode#102231]
- VSCode Version: 1.46.1
- OS Version: Microsoft Windows 10
- TypeScript Version: 4.0.0-dev.20200710

Steps to Reproduce:

Consider the following images:
![vscode intellisense bug](https://user-images.githubusercontent.com/12036977/87229743-73f1a500-c3b3-11ea-84e9-161a565cfe7f.png)

![vscode intellisense bug2](https://user-images.githubusercontent.com/12036977/87229766-ac917e80-c3b3-11ea-88f2-5c4658d1fcfc.png)

![vscode intellisense bug3](https://user-images.githubusercontent.com/12036977/87229784-cfbc2e00-c3b3-11ea-90b4-17b577ce93bd.png)

As you can see from the images, VsCode thinks that my `a` element can either be an `Object` or an `App.Components.Select2.Extended` element, thus it gives me the suggestions for both. However, based on the definitions I defined, I would expect that he clearly identifies `a` as an `App.Components.Select2.Extended` element, and gives me suggestion to only those elements.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file an issue upstream](https://github.com/microsoft/TypeScript/issues/new/choose)
