### ISSUE TITLE
Cannot duplicate a file

### ISSUE THREAD

**Issue by vanjmali** [microsoft/vscode#102207]
Issue Type: <b>Bug</b>

**Steps to Reproduce:**
1. Right-click on a file
2. Select 'Copy'
3. Right-click on a folder
4. Option 'Paste' is not selectable, meaning it didn't copy the file at all, it doesn't even work with shortcut keys

VS Code version: Code - Insiders 1.48.0-insider (e7920dce7bfd0b707ebfc0a5379c6edd2233e475, 2020-07-10T11:58:37.847Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.95GB (1.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
language-mcfunction|arc|0.16.0
discord-vscode|icr|3.15.0
skript-vscode|pen|2.1.3
datapack-language-server|SPG|2.1.13

</details>

**Comment by thomasmichaelwallace** [comment]
This is also happening to me (Windows; tested without an extensions as well).
Clipboard is working on the machine and within-file copy and paste is fine too.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/100797
