### ISSUE TITLE
Debugging hangs after logging some amount of text to the Debug Console

### ISSUE THREAD

**Issue by duckdotapk** [microsoft/vscode#102254]
- VSCode Version: 1.47.0
- OS Version: Windows 10 1909 

Steps to Reproduce:

Debug this JavaScript code in Node.js:

```js
for(let i = 0; i < 20000; i++)
{
    console.log(i);
}
```

VSCode should still remain responsive while the loop should seemingly hang somewhere between logging 15,000 and 16,000.

The issue appears to be related to logging some amount of text to the Debug Console.

I also tested this code in 1.46.1 and the issue does not occur in that version.

Does this issue occur when all extensions are disabled?: Yes

**Comment by imagolive** [comment]
Same issues running/debugging mocha tests. Just hangs after a lot of output to the debug window.

Only in 1.47 - related to the new javascript debugger perhaps?

**Comment by connor4312** [comment]
Thanks for the issue. If this is causing problems, you can for the moment use the old debugger by setting `debug.javascript.usePreview: false`

**Comment by connor4312** [comment]
Thanks again, this can be fixed by doing one of the following:

1. After 5PM today, using the latest [nightly extension](https://github.com/microsoft/vscode-js-debug/#nightly-extension) (recommended)
1. Setting `outputCapture: "std"` in your launch.json
1. Setting `debug.javascript.usePreview: false` to use the old debugger until this lands in a stable release

**Comment by duckdotapk** [comment]
Yeah, no problem. Glad to see it's resolved!

**Comment by talr1** [comment]
I've encountered the same issue but only with debugging tests (mocha) for some reason.
happened in latest insiders: 

Version: 1.48.0-insider (user setup)
Commit: cb31fc6ce2b4da3520392b622aa3ebc5b313533b
Date: 2020-07-15T05:34:49.078Z (1 day ago)
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18363

and also in latest stable: 

Version: 1.47.1 (user setup)
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:42:53.386Z (2 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
 
it seems it was enough to set debug.javascript.usePreview: false.
now debugger does not hang

**Comment by connor4312** [comment]
@talr1 see the solution directly above: https://github.com/microsoft/vscode/issues/102254#issuecomment-658247768

**Comment by talr1** [comment]
> @talr1 see the solution directly above: [#102254 (comment)](https://github.com/microsoft/vscode/issues/102254#issuecomment-658247768)

i wrote at the end that the solution works for me :-)
however, was using this option (debug.javascript.usePreview: false)the debug console pane remain empty. if remove this option, it start showing content again (in those cases where the debugger did not hang)
any idea?

**Comment by netpoetica** [comment]
@connor4312 If I use those solutions, I can get the debugger to start running again, but no breakpoints work. Is that expected?

**Comment by connor4312** [comment]
No; please file an issue using the bug template here https://github.com/microsoft/vscode-js-debug/issues/new/choose

**Comment by netpoetica** [comment]
Hey Connor, thank you for responding! It appears there was something else nefarious at work here. I was indeed able to set breakpoints. I don't remember exactly what was going on because it was a crazy day at work, but I think I had maybe not been running a watch task, so sourcemap debug breakpoint locations were incorrect. So the solution above did indeed get the debugger running as well as allow breakpoints to work. Thanks again!

**Comment by Jebtrix** [comment]
Nightly extension does not fix this problem for me, only solutions #2 and #3.

**Comment by connor4312** [comment]
Please file an issue and include a tracelog using the link above!

**Comment by Jebtrix** [comment]
@connor4312 With so many dups of this bug I didn't want to pile on yet another, but will do.
