### ISSUE TITLE
failing ts 

### ISSUE THREAD

**Issue by anujsinghwd** [microsoft/vscode#102220]
Issue Type: <b>Bug</b>

typescript faild 5 times

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|154, 96, 49|
|Memory (System)|8.00GB (0.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.6
es7-react-js-snippets|dsz|2.8.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
flow-for-vscode|flo|1.5.0
vscode-map-preview|jum|0.5.2
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
vetur|oct|0.24.0
material-icon-theme|PKi|4.2.0
polacode|pnp|0.3.4
markdown-preview-enhanced|shd|0.5.12
tabnine-vscode|Tab|2.8.8

</details>

**Comment by mjbvz** [comment]
When you hit there, please use the 'Report issue' button in the notification to generate an issue report with a call stack 

/needsMoreInfo
