### ISSUE TITLE
Not marking files ignored via .gitignore with gray

### ISSUE THREAD

**Issue by jbnjohnathan** [microsoft/vscode#102282]
- VSCode Version: 1.47.0
- OS Version: Windows 10 (2004) WSL 2

Steps to Reproduce:

1. create a file in the root of the repo called `something.log`
2. Add `something.log` to the .gitignore file in the repo root

Does this issue occur when all extensions are disabled?: Yes

According to https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_18.md#git-status-in-file-explorer files that are matched against the .gitignore should be marked with gray color. This is not happening for me.
I am mounting the actual files via SMB to WSL, but I have also tried to copy the repo to my windows desktop and the results are the same.
![2020-07-12 11_58_51-Window](https://user-images.githubusercontent.com/54041505/87243528-fa02ff80-c436-11ea-91c7-87c0a37d36f6.png)

**Comment by jbnjohnathan** [comment]
I opened vscode against another existing project I had in a folder. I saw that I had a `.gitignore` file which had only one entry `node_modules` and I saw that the `node_modules` folder was also grayed out as it should be.
![image](https://user-images.githubusercontent.com/54041505/87243597-88778100-c437-11ea-96ab-df6d87a558fa.png)

I then test by adding another entry in the `.gitignore` file but it is not graying out the folder with the same name
![image](https://user-images.githubusercontent.com/54041505/87243613-a80ea980-c437-11ea-96a7-9322c8ad3d8e.png)
When I save I see that `node_modules` is temporarily not grayed out as it re-calculates which files it should gray, but after that only `node_modules` is gray again, not `public`

**Comment by jbnjohnathan** [comment]
Next step I removed `node_modules` from the `.gitignore` file and the folder was no longer grayed out. I then put in only `flowchart` in the `.gitignore` but that folder was not grayed out. I put back `node_modules` and again `node_modules` was grayed out.

**Comment by jrieken** [comment]
This is not how gitignore works. A file or folder that has been already added to the repo cannot be simply ignored anymore. See this for more insights: https://stackoverflow.com/questions/6618612/ignoring-a-directory-from-a-git-repo-after-its-been-added

**Comment by jbnjohnathan** [comment]
> This is not how gitignore works. A file or folder that has been already added to the repo cannot be simply ignored anymore. See this for more insights: https://stackoverflow.com/questions/6618612/ignoring-a-directory-from-a-git-repo-after-its-been-added

Ah seems the feature was smarter than I thought. Great reply, thanks!
