### ISSUE TITLE
Incorrectly word wrapping in Thai language

### ISSUE THREAD

**Issue by Be1con** [microsoft/vscode#102273]
- VSCode Version: 1.47.0
- OS Version: Windows 10 Pro build 18363.900

Steps to Reproduce:

I am working on a project that is related to create static JSON file as static data in my web application, that contains Thai phases (as shown in image down below). As a person who use word wrapping a lot in my project, I always enable that in settings.

However, when I inserted long sentences of Thai sentences, it is not wrapping the word correctly. In the first image, I typed these following code*:

`        "description": "การออกแบบระบบบริหารจัดการจริยธรรมปัญญาประดิษฐ์สำหรับองค์กร ที่อยู่บนพื้นฐานของความมั่นคงปลอดภัย ความเป็นส่วนตัว ความเป็นธรรม และความน่าเชื่อถือของระบ",`

Which is 175 characters when it is counted based on character on the screen, but actually 151 characters when it excluded tone marks and floating characters, as seen in this following screenshot:

![incomplete](https://user-images.githubusercontent.com/9086431/87240464-0b9ed400-c444-11ea-88d9-4f965dad2f8c.png)

Then, I completed the sentence (with 1 extra character), as seen in this following code*:

`        "description": "การออกแบบระบบบริหารจัดการจริยธรรมปัญญาประดิษฐ์สำหรับองค์กร ที่อยู่บนพื้นฐานของความมั่นคงปลอดภัย ความเป็นส่วนตัว ความเป็นธรรม และความน่าเชื่อถือของระบบ",`

It is, technically 176 characters in coding standpoint, which it should start a psudo-newline. However, when you excluded tone marks and floating characters, it counted as 152 characters on display, as seen in this following screenshot:

![full sentence](https://user-images.githubusercontent.com/9086431/87240467-0e012e00-c444-11ea-85fb-c428967bfe92.png)

It is not effect my workflow with coding, just some annoyance when I code on this project. I really wish that this would be fixed in future updates.

Thank you.

\* Please note that these following code **included** 8 spaces for tab.

**Comment by alexdima** [comment]
@Be1con The default word wrapping algorithm is very efficient, but works correctly only for monospace fonts and monospace letters (like most programming is). Please use `"editor.wrappingStrategy": "advanced"`
