### ISSUE TITLE
Slower zoom in editor

### ISSUE THREAD

**Issue by SimonWoods** [microsoft/vscode#102227]
Issue Type: <b>Feature Request</b>

The editor font zoom is great with a mouse wheel but far too fast on my laptop trackpad. The font changes from unreadably small to hilariously huge with the tiniest movement, and the only way I can get the size I want is to zoom in and out repeatedly until it happens to stop on the desired setting.

Would it be possible to slow it down please (or add a speed setting)?

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18362

**Comment by MShuttle** [comment]
**Steps to reproduce similar frustration**

I also find that the "Editor: Mouse Wheel Zoom" setting is useful and also that it is way too sensitive, making use very frustrating.

It would be helpful if in Settings there were a sensitivity setting similar to that for mouse scrolling. 

MacBook Pro 15" 
macOS 11.6 Big Sur
Mouse Apple Magic Mouse 2

VSCode
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by alexdima** [comment]
Let's track in #72050
