### ISSUE TITLE
Hope to upgrade the chrome kernel version to electron 9 as soon as possible.

### ISSUE THREAD

**Issue by fox-silvery** [microsoft/vscode#102216]
Issue Type: <b>Feature Request</b>

Hope to upgrade the chrome kernel version to electron 9 as soon as possible.
This is more conducive to accessible keyboard interaction。
thank you very much!

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

**Comment by gjsjohnmurray** [comment]
#102011 indicates it is coming.

**Comment by deepak1556** [comment]
Thanks @gjsjohnmurray 

Merging this to https://github.com/microsoft/vscode/issues/100731
