### ISSUE TITLE
Debugger stops on hot reload for Flask in debugger

### ISSUE THREAD

**Issue by melvinkokxw** [microsoft/vscode#102209]
Issue Type: <b>Bug</b>

## Steps to reproduce problem:

1. launch.json configuration as given below:
```
{
            "name": "Docker: Python - Flask",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "docker-run: debug",
            "python": {
                "pathMappings": [
                    {
                        "localRoot": "${workspaceFolder}/web/",
                        "remoteRoot": "/app"
                    }
                ],
                "host": "localhost",
                "port": 5000,
                "jinja": true,
                "projectType": "flask",
                "justMyCode": true
            },
            "removeContainerAfterDebug": true}
        }
```

task.json given below:

```
{
			"type": "docker-build",
			"label": "docker-build",
			"platform": "python",
			"dockerBuild": {
				"tag": "<tag name removed>",
				"dockerfile": "${workspaceFolder}/web/Dockerfile",
				"context": "${workspaceFolder}/web/",
				"pull": true
			}
		},
		{
			"type": "docker-run",
			"label": "docker-run: debug",
			"dependsOn": [
				"docker-build"
			],
			"dockerRun": {
				"containerName": "<container name removed>",
				"env": {
					"FLASK_APP": "<app name removed>",
					"FLASK_ENV": "development",
					"FLASK_DEBUG": "1"
				},
				"volumes": [
					{
					  "containerPath": "/app", "localPath": "${workspaceFolder}/web/"
					},
				],
				"envFiles": [
					"${workspaceFolder}/web/.env"
				],
				"ports": [
					{
						"containerPort": 5000, "hostPort": 5000
					}
				]
			},
			"python": {
				"args": [
					"run",
					"--host",
					"0.0.0.0",
					"--port",
					"5000",
				],
				"module": "flask",
			}
		}
```

2. Run debugger 
3. Make edit anywhere on a python file and save

## Results

Expected results:
Flask hot reloads.

Actual results:
Last line in debug console is:
`* Detected change in '/app/plotter/api/routes.py', reloading`
and debugger simply stops.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.5.0

<details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.1.0
asciidoctor-vscode|asc|2.8.1
bracket-pair-colorizer-2|Coe|0.2.0
githistory|don|0.6.5
gitlens|eam|10.2.2
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
minify|Hoo|0.4.3
latex-workshop|Jam|8.11.1
vscode-azurevirtualmachines|ms-|0.1.1
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
cpptools|ms-|0.28.3
vsliveshare|ms-|1.0.2427
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.3.0
autodocstring|njp|0.5.3
material-icon-theme|PKi|4.2.0
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.9
vscode-wakatime|Wak|4.0.0
markdown-all-in-one|yzh|3.1.0

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
Please file against "docker" debugger.
