### ISSUE TITLE
VSCode is unbelievably slow

### ISSUE THREAD

**Issue by sarthak-pokharel** [microsoft/vscode#102263]
- VSCode Version: 1.47.0 d5e9aa0227e057a60c82568bf31c04730dc15dcd x64
- OS Version: Windows NT (8.1)
- Processor: 1.35 GHz AMD E1-6010 APU dual core with AMD Radeon R2 Graphics
- RAM: 4GB
- PC: Laptop[ Acer [Aspire [ES1 [521 ]]]]

Steps to Reproduce:

1. Open VSCode
2. Open any program to edit

Does this issue occur when all extensions are disabled?: Yes

Can't VSCode upgrade from JavaScript to C or C++ so that, it can run in my low end pc as well?

**Comment by axetroy** [comment]
indeed. It's really slow.
I don’t know if the vscode team has any follow-up optimization strategies, eg. using wasm

**Comment by arpitchauhan** [comment]
It became really slow since the last release. Just before the 1.47 release, I had no issue with it.

**Comment by gjsjohnmurray** [comment]
To investigate performance issues the team needs more information. See https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by jpike88** [comment]
We have been experiencing major slowdowns launching chrome and nodejs. I think the new Javascript debugger might be the culprit

**Comment by jrieken** [comment]
@jpike88 what you say seems unrelated to this issue

**Comment by jpike88** [comment]
Maybe. Issue has opened here anyway

[link](https://github.com/microsoft/vscode-js-debug/issues/598)

**Comment by jrieken** [comment]
ping @sarthak-pokharel
