### ISSUE TITLE
Overridden "type" command does not work properly with heavy processing inside it

### ISSUE THREAD

**Issue by tuttieee** [microsoft/vscode#102291]
- VSCode Version: 1.48.0-insider
- OS Version: Darwin x64 18.7.0

```
Version: 1.48.0-insider
Commit: e7920dce7bfd0b707ebfc0a5379c6edd2233e475
Date: 2020-07-10T11:55:11.286Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 18.7.0
```

Steps to Reproduce:

1. Create an extension that overrides `type` command and executes some heavy processing inside it.
2. Launch VSCode with the extension. When I tested this issue, all other extensions are disabled by `Developer: Reload With Extensions Disabled` command.
3. Enable some IME and input some letters. When I tested this issue, I used macOS' default Japanese IME (https://support.apple.com/ja-jp/guide/japanese-input-method/welcome/mac).
4. Successive letters are strangely input as shown below:
![vscode-type-command-bug-insider](https://user-images.githubusercontent.com/3135397/87246812-96a2bd00-c48a-11ea-9529-386831a9e36f.gif)
In this screenshot, "a" is first typed for "あ" then "i" is typed for "い". After that, another "あ" appeared with delay though no equivalent letter is typed.
After that, Enter is pressed to fix the IME input. Then the extra "あ" is inserted to a different point and does not disappear.

I uploaded the code that I used to reproduce this issue here: https://github.com/tuttieee/vscode-extension-keyboard-bug-example/blob/delayed-type-command-example/src/extension.ts (Please note the branch is not master. And in this code, `replacePreviousChar` is also registered just for inspection, but it is not necessary to reproduce this problem)
In this example code, I used `new Promise((resolve) => setTimeout(resolve, time))` to emulate the heavy processing. This promise-based code is intentional to always reproduce the bug, but it also has been reported the same problem has occurred sometimes with a real plugin that overrides `type` command (https://github.com/tuttieee/vscode-emacs-mcx/issues/115).

Does this issue occur when all extensions are disabled?: Yes
It was tested with the example extension linked above with all other extensions disabled in development mode.

**Comment by alexdima** [comment]
@tuttieee Two things:

1. If you overwrite the `type` command, then you must overwrite the `replacePreviousChar` command as well, and you should probably also overwrite `compositionStart` and `compositionEnd`. Please see a sample at https://github.com/microsoft/vscode-extension-samples/blob/c78e0205a882e09496a75bc6d930d83700370ffe/vim-sample/src/extension.ts#L26-L49

2. If you introduce a single `await`/yielding in your implementation of `type`, then it is your responsibility to implement a queue and not handle the next `type` or next `replacePreviousChar` command until you have finished handling the previous one.

**Comment by tuttieee** [comment]
@alexdima Thank you, 

> 1.
> 2.

I understand, from your advice and the example you gave, that I should just override `replacePreviousChar` and pass the arguments to `default:replacePreviousChar` without any effects, as long as I simply insert some lightweight synchronous logics to `type` before calling `default:type`.
I will try it out as it's a right way, though it in turn faces another problem( #98328 )...

> 3.

I see. I will avoid such implementations.

**Comment by alexdima** [comment]
@tuttieee I will optimistically close this issue for now. Please reopen if there are additional concerns.
