### ISSUE TITLE
Unable to open editor: Unexpected token JSON at position x.

### ISSUE THREAD

**Issue by lroy83** [microsoft/vscode#102251]
- VSCode Version: 1.47.0
- OS Version: mac os Catalina 

Steps to Reproduce:

Does this issue occur when all extensions are disabled?: Yes

after update and restart, for every file i click on i get this error. (with file name instead of ???, but with SAME position number)
It happens only in one project. when i go to source control and click a file there, the file gets opened with his changes.
if i click the same file in explorer I'll get the error.
i get the error trying to open vscode settings file from command palette too.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by lroy83** [comment]
Hi,

Thank you for your reply.

- run code --verbose from the command line and attach the output
`[main 2020-07-12T06:47:02.541Z] Sending env to running instance...
[main 2020-07-12T06:47:02.546Z] Sent env to running instance. Terminating...
[main 2020-07-12T06:47:02.546Z] Lifecycle#kill()`

- attach any output you see in the Console you can find
`/Users/lerman/Applications/VSCode/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2947 Unable to open 'index.vue': Unexpected token l in JSON at position 29324.
onDidChangeNotification @ /Users/lerman/Applications/VSCode/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2947
/Users/lerman/Applications/VSCode/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1670   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
notificationsAlerts.ts:40 Unable to open 'nuxt.config.js': Unexpected token l in JSON at position 29324.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
doHandleOpenEditorError @ editorGroupView.ts:1062
(anonymous) @ editorGroupView.ts:990
async function (async)
(anonymous) @ editorGroupView.ts:979
doShowEditor @ editorGroupView.ts:977
doOpenEditor @ editorGroupView.ts:960
openEditor @ editorGroupView.ts:888
(anonymous) @ editorService.ts:1291
(anonymous) @ explorerViewlet.ts:219
openEditor @ editorService.ts:1290
(anonymous) @ explorerView.ts:440
fire @ event.ts:587
_open @ listService.ts:521
onPointer @ listService.ts:505
(anonymous) @ listService.ts:456
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
onViewPointer @ listWidget.ts:644
onViewPointer @ abstractTree.ts:1129
(anonymous) @ event.ts:91
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
o @ event.ts:16
notificationsAlerts.ts:40 Unable to open 'docker-compose.dev.yml': Unexpected token l in JSON at position 29324.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
doHandleOpenEditorError @ editorGroupView.ts:1062
(anonymous) @ editorGroupView.ts:990
async function (async)
(anonymous) @ editorGroupView.ts:979
doShowEditor @ editorGroupView.ts:977
doOpenEditor @ editorGroupView.ts:960
openEditor @ editorGroupView.ts:888
(anonymous) @ editorService.ts:1291
(anonymous) @ explorerViewlet.ts:219
openEditor @ editorService.ts:1290
(anonymous) @ explorerView.ts:440
fire @ event.ts:587
_open @ listService.ts:521
onPointer @ listService.ts:505
(anonymous) @ listService.ts:456
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
onViewPointer @ listWidget.ts:644
onViewPointer @ abstractTree.ts:1129
(anonymous) @ event.ts:91
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
o @ event.ts:16
notificationsAlerts.ts:40 Unable to open '.gitignore': Unexpected token l in JSON at position 29324.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
doHandleOpenEditorError @ editorGroupView.ts:1062
(anonymous) @ editorGroupView.ts:990
async function (async)
(anonymous) @ editorGroupView.ts:979
doShowEditor @ editorGroupView.ts:977
doOpenEditor @ editorGroupView.ts:960
openEditor @ editorGroupView.ts:888
(anonymous) @ editorService.ts:1291
(anonymous) @ explorerViewlet.ts:219
openEditor @ editorService.ts:1290
(anonymous) @ explorerView.ts:440
fire @ event.ts:587
_open @ listService.ts:521
onPointer @ listService.ts:505
(anonymous) @ listService.ts:456
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
onViewPointer @ listWidget.ts:644
onViewPointer @ abstractTree.ts:1129
(anonymous) @ event.ts:91
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
o @ event.ts:16
`

did reboot - didn't help.
Thanks.

**Comment by bpasero** [comment]
@lroy83 can you attach the contents of your settings file here? I wonder if some setting is corrupt that would explain this. The settings file is in: `~/Library/Application Support/Code/User/settings.json`

**Comment by lroy83** [comment]
`{
    "git.autofetch": true,
    "window.zoomLevel": 1,
    "workbench.colorTheme": "Monokai",
    "explorer.confirmDelete": false,
    "diffEditor.ignoreTrimWhitespace": true
}`

**Comment by bpasero** [comment]
@lroy83 thanks, that does not look like an issue to me. I think the next step would be to try and see if you can reproduce from a new user data dir.

Can you try to run `code --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by aeschli** [comment]
From the exception shown in https://github.com/microsoft/vscode/issues/102251#issuecomment-657183382, the notification dialog is opened from https://github.com/microsoft/vscode/blob/14dabea7c2abd4e6002b66945d3d5d7832861983/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L990

So somewhere in call stack theres an invocation of JSON.parse that is not caught and bubble up.

From patching `JSON.parse` I believe it must be this one:

JSON.parse (editorGroupView.ts:981)
load (memento.ts:78)
ScopedMemento (memento.ts:68)
getMemento (memento.ts:30)
getMemento (component.ts:39)
getEditorMemento (baseEditor.ts:151)
BaseTextEditor (textEditor.ts:70)
TextFileEditor (textFileEditor.ts:56)
NativeTextFileEditor (textFileEditor.ts:50)
_createInstance (instantiationService.ts:110)
createInstance (instantiationService.ts:76)
instantiate (editor.ts:73)
doInstantiateEditorPane (editorControl.ts:128)
doCreateEditorPane (editorControl.ts:105)
doShowEditorPane (editorControl.ts:81)
openEditor (editorControl.ts:63)
(anonymous) (editorGroupView.ts:988)
doShowEditor (editorGroupView.ts:1005)
doOpenEditor (editorGroupView.ts:960)
openEditor (editorGroupView.ts:888)
(anonymous) (editorService.ts:1296)
(anonymous) (explorerViewlet.ts:219)
openEditor (editorService.ts:1295)
(anonymous) (explorerView.ts:440)
fire (event.ts:587)
_open (listService.ts:523)
onPointer (listService.ts:507)
(anonymous) (listService.ts:458)
fire (event.ts:587)
(anonymous) (event.ts:56)
fire (event.ts:587)
(anonymous) (event.ts:56)
fire (event.ts:587)
onViewPointer (listWidget.ts:644)
onViewPointer (abstractTree.ts:1129)
(anonymous) (event.ts:91)
fire (event.ts:587)
(anonymous) (event.ts:56)
fire (event.ts:587)
fn (event.ts:16)

**Comment by aeschli** [comment]
Looking at API clients of the memento, I believe the fix needs to be made there as no client expects and exception.

**Comment by aeschli** [comment]
For users: If my analysis is right, the following should work around the problem:

- Linux: `mv ~/.config/Code/User/workspaceStorage ~/.config/Code/User/workspaceStorage.old`
- Mac: `mv ~/Library/Application\ Support/Code/User/workspaceStorage ~/Library/Application\ Support/Code/User/workspaceStorage.old`
- Windows: `rename %APPDATA%\Code\User\workspaceStorage %APPDATA%\Code\User\workspaceStorage.old`

**Comment by bpasero** [comment]
Added some error logging to diagnose further, but needs a new insiders build and reports from users to action on it.

**Comment by bpasero** [comment]
If a user hits this and wants to share the workspace storage with me, that would also be appreciated 👍

**Comment by bpasero** [comment]
A new insiders version is out including my fix. Can people try this on insiders and see if they possibly get output (run with `--verbose`)?

**Comment by dan-online** [comment]
I've run into this issue today on mac, I believe it was due to my laptop shutting down unexpectantly

**Comment by dan-online** [comment]
Just updated to 1.49.0-insider and everything seems to be working again 😅

**Comment by bpasero** [comment]
@dan-online anything you can see in the logs when you run with `--verbose`?
