### ISSUE TITLE
[Insiders, Ubuntu snap] askpass.sh doesn't symlink to "/current", breaks on auto-update

### ISSUE THREAD

**Issue by GavinRay97** [microsoft/vscode#102258]
(Note: This hasn't happened before until today, if that information is useful is all)

- VSCode Version: `1.48.0-insider`
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Install `code-insiders` via Snap
2. After upgrade to latest release, `askpass.sh` points to previous (non-existent) version instead of (what I assume should be) symlinked `current` folder

```sh
❯ git push
fatal: cannot run /snap/code-insiders/463/usr/share/code-insiders/resources/app/extensions/git/dist/askpass.sh: No such file or directory
```
```sh
☸ microk8s in /snap/code-insiders on ☁️  us-east-1 
❯ tree -L 1
.
├── 477
├── 479
└── current -> 479
```
```sh
☸ microk8s in extensions/git/dist via ⬢ v12.6.0 on ☁️  us-east-1 
❯ pwd
/snap/code-insiders/current/usr/share/code-insiders/resources/app/extensions/git/dist

☸ microk8s in extensions/git/dist via ⬢ v12.6.0 on ☁️  us-east-1 
❯ ls
askpass-empty.sh  askpass-main.js  askpass.sh  main.js  nls.metadata.header.json  nls.metadata.json
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Is the issue fixed if you restart VS Code?

**Comment by GavinRay97** [comment]
It appears to be :thinking:
I switched the remote URL from `https` to `ssh` for temp fix, then switched it back just now and restarted and there's no issue.

Suppose we can close it then, apologies for filing this, should have tried to restart it before I submitted.

**Comment by joaomoreno** [comment]
This is the terminal variable caching: the terminal comes up before the Git extension is activated so it preserves the previous environment. @Tyriar Thoughts? Any chance the git extension can opt-out of the caching?

**Comment by Tyriar** [comment]
@joaomoreno opting out of the caching means the first terminal would not get anything set, the purpose of it is so that the terminal doesn't block on ext host launching. https://github.com/microsoft/vscode/issues/100193 is probably the right fix for this.
