### ISSUE TITLE
Provide settings to configure status bar

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#102250]
Issue Type: <b>Feature Request</b>

It's possible to right click the status bar to enable and disable things that are displayed there. However, I have to manually configure this on each machine. Unlike other display elements such as `debug.toolBarLocation`, `editor.codeLens`, `explorer.openEditors.visible`, `workbench.activityBar.visible`, and others there are no settings to control the status bar.

I'd like to be able to disable elements within the status bar via my settings.json.

![image](https://user-images.githubusercontent.com/484784/87233597-c7490080-c37d-11ea-8368-2b59561ffc18.png)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

**Comment by bpasero** [comment]
You will not need to configure this per machine once settings sync is enabled which we ship next milestone to stable.
