### ISSUE TITLE
scm/git Unified View: missing action buttons when opening single folder

### ISSUE THREAD

**Issue by danielb42** [microsoft/vscode#102297]
Not fixed in code-insiders 1.48.

- VSCode Version: 1.47.0
- OS Version: ubuntu 18.04

Steps to Reproduce:

1. Open more than one folder, Sync (Pull/Push) button is there:
![tworepos](https://user-images.githubusercontent.com/35470293/87247979-41998380-c457-11ea-9d4f-4bedf9d731e5.png)

2. Open only one folder, no Sync buttons. The shown repo is the same as in the pic above with one pending commit. 
![onerepo](https://user-images.githubusercontent.com/35470293/87248015-64c43300-c457-11ea-8970-6b0c777f4b81.png)

Does this issue occur when all extensions are disabled?: Yes.

**Comment by gjsjohnmurray** [comment]
/duplicate This is one of the points made in #102104
