### ISSUE TITLE
[Feature] allow document link provider to support running commands as well

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#102283]
currently DocumentLink only supports `file path` or `url`.

ex. am trying to add a new enhancement to [ext](https://marketplace.visualstudio.com/items?itemName=ctf0.goto-package) which allow removing the package by simply hovering over it and pressing the `remove package link`, 
but sadly i cant find anything related to that in the docs, nor a way around on sof.

so is there a way to add a command to the provider as well?

**Comment by gjsjohnmurray** [comment]
Did you look at [Command URIs](https://code.visualstudio.com/api/extension-guides/command#command-uris)?

**Comment by ctf0** [comment]
@gjsjohnmurray i must have overlooked it, many thanx for the headsup

**Comment by ctf0** [comment]
@gjsjohnmurray am not sure if am missing something or not, but how to show hover for specific positions ? both the examples & https://code.visualstudio.com/api/references/vscode-api#HoverProvider doesnt show how 😢

**Comment by gjsjohnmurray** [comment]
> not sure if am missing something or not, but how to show hover for specific positions

@ctf0 This question is unrelated to your original issue, right?

When you construct the [Hover](https://code.visualstudio.com/api/references/vscode-api#Hover) for your ProviderResult did you try using the optional `range` parameter on the constructor?

**Comment by ctf0** [comment]
no need, thanx for your link, i can actually send a command inside the document link
```
new vscode.DocumentLink(range, vscode.Uri.parse(`command:gotoPackage.removePackage?${encodeURIComponent(JSON.stringify(args))}`))
```

so again thanx for ur help & quick reply.
