### ISSUE TITLE
List: Provide `list.mouseWheelScrollSensitivity` setting

### ISSUE THREAD

**Issue by musm** [microsoft/vscode#102261]
Mouse Wheel Scroll Sensitivity setting does not uniformly apply to all list elements

- VSCode Version: 1.47.0
- OS Version: Windows 10.0.19041

Steps to Reproduce:

1. Increase mouse wheel scroll sensitivity (set it to something large so you can see the difference) `editor.mouseWheelScrollSensitivity`
2. Scroll in the editor windows and compare the scroll sensitivity to other list items, where the scroll sensitivity will be much slower.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
> mouse wheel scroll sensitivity

Is this a VS Code setting?

**Comment by musm** [comment]
editor.mouseWheelScrollSensitivity

**Comment by joaomoreno** [comment]
Related https://github.com/microsoft/vscode/issues/102261

**Comment by musm** [comment]
Looks like you accidentally linked the same issue

**Comment by joaomoreno** [comment]
I did 🤦 this is the one: https://github.com/microsoft/vscode/issues/102055

Thanks!

**Comment by musm** [comment]
for simplicity shouldn't these all be linked to one setting? I don't see a rationale for different sensitivity settings, although it could be useful in some contexts

**Comment by musm** [comment]
bump, would be nice to fix this bug

**Comment by door-bell** [comment]
Hello, first time contributor here, I took a crack at this one! ⏫

**Comment by daslicht** [comment]
Please make this feature also working for teh tree and not just the content

**Comment by musm** [comment]
Can we not just consolidate all the mouseWheelScrollSensitivity options?

**Comment by thany** [comment]
There shouldn't be a setting. Scrollwheel distance is set in the OS preferences. If it just respects that setting properly and applies it to every scrollable thing, we're done.

Now, what still needs to happen to get this fixed? And how can we make that happen?

**Comment by rzhao271** [comment]
Just a note that the PR adds the following settings:

`workbench.list.mouseWheelScrollSensitivity`
`workbench.list.fastScrollSensitivity`

**Comment by thany** [comment]
Again, why?

Why can't VScode just listen to the scrollwheel speed setting in the OS?

**Comment by Tyriar** [comment]
@thany I wasn't involved in this but a similar setting exists for the terminal and the editor, the reason these settings exist is because respecting the OS' setting is not easy when targeting the web. These settings allow flexibility to the user in case their preferences aren't met.

**Comment by thany** [comment]
When targeting the web, just do what the browser offers - it's probably already set to the user's preference. But VScode is mainly a separate program (it running on Chromium is little more than semantics to me) so it has full capability to respect the OS' setting for mousewheel sensitivity.

Afaik, every OS has some sort of settings for this, hidden or otherwise, and not follwing those settings seems like going against user preferences, which is not a good thing as a general rule. Even if this supposed setting is set to the correct initial value, because settings in the OS can change.

**Comment by Tyriar** [comment]
> it's probably already set to the user's preference

You'd think so, but it's not, plus all browsers act differently. We wouldn't have added settings or all the hoops we jump through in monaco to get scroll events if it already did the thing as expected.
