### ISSUE TITLE
Pasting in jupyter notebook

### ISSUE THREAD

**Issue by shubhamsharma10** [microsoft/vscode#102271]
Issue Type: <b>Bug</b>

Suppose we copy any text, and wanted to paste this text in jupyter notebook in vscode, while pasting, the text is repeated 2 times. So for example if we copy `FOO` for pasting, after pasting the cell contains `FOOFOO`. NOTE: This issue is happening after i have update the vscode to version `1.47.0`.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:30:34.302Z)
OS version: Linux x64 5.4.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2741)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|7.67GB (2.84GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.6.91350
vscode-pylance|ms-|2020.7.1
cpptools|ms-|0.28.3
debugger-for-chrome|msj|4.12.9
vscode-icons|vsc|10.2.0

</details>

**Comment by mhutchie** [comment]
@bpasero, The clipboard contents are inserted twice per `CTRL-V` in Webview's from all extensions (this is not specific to Jupyter Notebook). It affects my extension (Git Graph), and every other Webview-based extension I'm aware of. It was definitely introduced in vscode 1.47.0.

FYI: I can only replicate this bug on Windows, my Mac device still functions correctly.

@mjbvz, are you aware of this given your recent changes to the Webview implementation.
