### ISSUE TITLE
Shortcut Ctrl + D is duplicating selection

### ISSUE THREAD

**Issue by itsecurityco** [microsoft/vscode#102255]
I have the following string:

```SELECT tef.id, tef.account_origin, tef.account_dest, c.fullname```

When I highlight the string ```tef.``` and then press ```Ctrl + D``` this is what happens:

```SELECT tef.tef.id, tef.account_origin, tef.account_dest, c.fullname```

The ```tef.``` string is duplicated every time I press Ctrl + D.

```
Extension | Author (truncated) | Version
vscode-docker | ms- | 1.3.1
laravel-blade | one | 1.22.1
intellij-idea-keybindings | k-- | 0.2.41
remote-wsl | ms- | 0.44.4
```

**Comment by gjsjohnmurray** [comment]
Does the problem also happen after you disable the keybinding extension you have installed?

**Comment by itsecurityco** [comment]
> Does the problem also happen after you disable the keybinding extension you have installed?
This fixed it, thanks!
