### ISSUE TITLE
Javadoc tags no longer highlighted in C/C++ code

### ISSUE THREAD

**Issue by AmeliaSZK** [microsoft/vscode#102257]
- VSCode Version: 1.47.0
- OS Version: Linux x64 5.3.0-62-generic snap

Steps to Reproduce:

1. Create a new `.cpp` file
2. Make sure syntax colouring is enabled
3. Copy paste this code:
```C++
#include <iostream>
using namespace std;

/** Displays "Hello World"
 * 
 * @param argc Arguments count
 * @param argv Arguments vector
 *
 * @return 0 on success, something else on failure.
 */
int main(int argc, char* argv[]){
    cout << "Hello World" << endl; 
      
    return 0; 
}
```

## Problem
These lines are all in green:
```
 * @param argc Arguments count
 * @param argv Arguments vector
 * @return 0 on success, something else on failure.
```

## Expected behaviour
The javadoc tags (`@param`, `@return`) should be in a different colour. I think it was dark blue previously? Also, `argc` and `argv` were coloured differently (teal?) from the tags and the comments because they are parameter names.

## When did the problem start
I think it started after I got updated to the June 2020 release? I think I saw today or yesterday the splash page announcing the new features in the June 2020 update, I don't remember seeing a correct colouring after that, and I know it was correctly colouring them like last week. 

I didn't check if the issue was fixed in the insiders build.

Possibly related to issue #102212

Does this issue occur when all extensions are disabled?: Yes

## Edit
In case someone else runs into the same problem: The culprit here was the extension LaTeX Workshop 8.11.1

**Comment by alexr00** [comment]
I'm still seeing those lines get colored correctly in 1.47.0. Are you sure you have all extension disabled?

![image](https://user-images.githubusercontent.com/38270282/87305670-28f0a280-c517-11ea-84e6-d41eb84414e4.png)

**Comment by AmeliaSZK** [comment]
Yes? Am I supposed to do more than just `code --disable-extensions` ??
![javadoc params](https://user-images.githubusercontent.com/49453461/87335378-335a6e80-c50e-11ea-85ef-706921eedac8.png)

**Comment by alexr00** [comment]
`--disable-extensions` should do it. Just in case, can you share a list of the extensions you have installed? Maybe we are not handling the `--disable-extensions` flag correctly.

**Comment by AmeliaSZK** [comment]
* Bats (Bash Automated Testing System) 0.1.7
* C/C++ 0.29.0
* C/C++ Makefile Project 1.1.0
* Language Support for Java(TM) by Red Hat 0.65.0
* LaTeX Workshop 8.11.1
* Markdown+Math 2.5.1
* Oracle Developer Tools for VS Code 19.3.2
* Power Query M Language 1.0.0
* Qt for Python 0.4.2
* Rainbow CSV 1.7.0
* Remote - SSH 0.51.0
* Remote - SSH: Editing Configuration Files 0.51.0
* SQLTools 0.22.10
* Word Count 0.1.0

**Comment by AmeliaSZK** [comment]
Update: The culprit was LaTeX Workshop. The highlights is back when it's disabled.

**Comment by AmeliaSZK** [comment]
Also, after I re-enabled it, I restarted with the --disable-extensions flag, and now the highlights are still back, unlike in my previous comment. (Hopefully that's because of a change in the 1.47.2 update, and not because I screwed up my screenshot 🤦🏻‍♀️)

Anywayz, feel free to close if you have no other questions

**Comment by alexr00** [comment]
Thanks for checking all that!
