### ISSUE TITLE
Source control icon changes if you move it around

### ISSUE THREAD

**Issue by grantborthwick** [microsoft/vscode#102262]
Issue Type: <b>Bug</b>

1. Open the terminal
2. Drag the source control icon to the terminal and split it with the terminal
![image](https://user-images.githubusercontent.com/2301725/87238134-698bd700-c3c4-11ea-8516-28ee37970bf4.png)
3. Drag source control back to the sidebar
![image](https://user-images.githubusercontent.com/2301725/87238137-74466c00-c3c4-11ea-8d5f-af87d23275aa.png)

Expected: it shows the source control icon
Actual: It shows a generic window icon

This also repros on vscode insiders for me with fewer extensions.

Reset Location fixes it, but this is weird!
![image](https://user-images.githubusercontent.com/2301725/87238141-80cac480-c3c4-11ea-80cd-a9c4a337deda.png)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (35.32GB free)|
|Process Argv|--file-uri [path to my workspace].code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-imports|ama|6.1.0
xml|Dot|2.5.0
EditorConfig|Edi|0.15.1
vscode-jasmine-test-adapter|hbe|1.6.2
vscode-test-explorer|hbe|2.19.1
vscode-less|mrm|0.6.3
azure-pipelines|ms-|1.170.0
vscode-azurestorage|ms-|0.9.0
vscode-cosmosdb|ms-|0.13.0
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
hexeditor|ms-|1.1.0
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2427
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
angular-karma-test-explorer|raa|1.2.5
vscode-yaml|red|0.8.0
jstool|sun|1.2006.0
vscodeintellicode|Vis|1.2.9

</details>

**Comment by grantborthwick** [comment]
I've now gotten it into a state where when I reset its location, it goes next to the Problems area at the bottom!

Steps:
1. Open the terminal

2. Drag the source control icon to the terminal and split it with the terminal
![image](https://user-images.githubusercontent.com/2301725/87238134-698bd700-c3c4-11ea-8516-28ee37970bf4.png)
3. Drag it up to make it a new area at the bottom instead of splitting it with the terminal
![image](https://user-images.githubusercontent.com/2301725/87238530-0781a080-c3c9-11ea-88fd-7057ae66c391.png)

4. Drag source control back to the sidebar
![image](https://user-images.githubusercontent.com/2301725/87238137-74466c00-c3c4-11ea-8d5f-af87d23275aa.png)

5. Right click the "new" source control icon and select Reset Location
![image](https://user-images.githubusercontent.com/2301725/87238535-1f592480-c3c9-11ea-9cc4-f6784468bca7.png)


Expected: It fixes the icon and puts it in the right place
Actual: It moves it back to the bottom!
![image](https://user-images.githubusercontent.com/2301725/87238540-3435b800-c3c9-11ea-97f6-4e4eeeead9c8.png)

Resetting it again here moves it to the correct place. I also can repro this with the search panel except without the icon change.

**Comment by grantborthwick** [comment]
I also observe that when the source control panel has the different icon or is on the bottom panel, Ctrl + Shift + G doesn't switch to it anymore.

**Comment by joaomoreno** [comment]
@sbatten Advice, and maybe candidate?

**Comment by joaomoreno** [comment]
Fixed the icon and keyboard shortcut. Moved the the reset issue to https://github.com/microsoft/vscode/issues/102396
