### ISSUE TITLE
alt+click to add multiple cursors also toggles the menu bar

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#10224]
In stable and Insider's build, on Windows.

1. Hide the menu bar (View > Toggle Menu Bar). You can press alt to toggle its visibility.
2. Hold alt and click to place a second cursor
3. When you release alt, the menu bar appears. You can press it again to hide it. But when alt is part of some other action, it shouldn't make the menu bar appear.

**Comment by alexandrudima** [comment]
Possible fix in #9154

**Comment by bpasero** [comment]
Verified this is OK now.
