### ISSUE TITLE
Add a setting to prevent viewlet toggling when using keyboard shortcut

### ISSUE THREAD

**Issue by ghurley** [Microsoft/vscode#10227]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

Right now, the keyboard shortcut for Find Across Files (cmd+shift+F) functions as a toggle (even though the command name is just 'workbench.view.search'). If you are not focused on the search pane, hitting the combo will open it and focus there. Otherwise, it will restore the focus to previous area.

I find this incredibly awkward because I want the keyboard shortcut to always bring me to Search Across Files, rather than sometimes bringing me _away_ from there if that's where my focus already happens to be and I don't notice. Frequently, I assume the focus is in a text pane (the visual distinction is not terribly obvious) and hit cmd+shift+F, and begin typing but because the focus was actually already in the search box, I just ended up toggling back to the editor and entering a bunch of text that I didn't want to enter. It's worse if I happen to have something selected.

It's conceivable that this toggling behavior is helpful to some people sometimes but it would be nice to at least have the option of disabling it. I attempted to override keyboard shortcuts so that cmd+shift+f only worked when: "editorTextFocus" but it had no effect.

**Comment by bpasero** [comment]
If we add an option it should work for all the viewlet shortcuts.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
