### ISSUE TITLE
Publish "Settings Editor" to npm as a standalone JSON editor

### ISSUE THREAD

**Issue by linonetwo** [microsoft/vscode#102270]
Can you publish Settings Editor (which probably located in https://github.com/microsoft/vscode/tree/master/src/vs/workbench/contrib/preferences ) to an npm package for reuse? Just like Monaco editor?

This preference JSON editor in VSCode is a very beautiful and powerful JSON editor that outstands most of JSON editor in the npm, if you can release it, it can certainly help lots of people.

**Comment by roblourens** [comment]
Sorry, this isn't really possible. The Settings Editor is not a generic JSON editor, and it is closely tied to many other parts of VS Code.
