### ISSUE TITLE
certain keyboard keys are not working 

### ISSUE THREAD

**Issue by kishore-1** [microsoft/vscode#102244]
- VSCode Version: 1.47.0
- OS Version: Linux x64 5.4.0-7634-generic
and Pop!_OS 20.04 LTS

Steps to Reproduce:

1.just open the vs code and start typing, for first stroke the key works and after which key strokes are not recognised. but same key in shortcut like ctrl+alt+p works but "p" doesn't work and keys like j,w,f are working but most of the alphanumeric keys are not working. 
P.s.Even the virtual keyboard keys are not working.

Does this issue occur when all extensions are disabled?: Yes
i have uninstalled and reinstalled the vs code and removed the extensions still not working

**Comment by alexdima** [comment]
@kishore-1 
Does this reproduce when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)

**Comment by kishore-1** [comment]
Yes even after disabling I had the issue. So 
I deleted my os and reinstalled it and used the code it worked and now no issues.
