### ISSUE TITLE
Find/Replace in files, numbered capture group doesn't seem to work if replacetext has numbers after group

### ISSUE THREAD

**Issue by untilted-document** [microsoft/vscode#102221]
I have some text in different files:

    abcxxx123
    abcyyy123
    abczzz123

I want to make it like:

    abc???234

The ??? being variable, so I will use a capture group:

    FIND: abc(.*)123
    REPL: abc$1234

The find/replace in files dialog suggests it will carry out the replace with that literal text, it looks like:

> blah ~~abcxxx123~~abc$1234 blah

Tried the rust flavoured replacement text:

    REPL: abc${1}234

No good; the find/repl window now suggests the replacement will be made:

> blah ~~abcxxx123~~abc${1}234 blah

If I put some other char between the 1 and the 234, it works out:

    REPL: abc$1`234

> blah ~~abcxxx123~~abcxxx`234 blah

And now I just have to run another replace to remove the backtick.. But how to do this with one step?

**Comment by untilted-document** [comment]
If I put some other char between the 1 and the 234, it works out:

   REPL: abc$1`234
blah ~~abcxxx123~~abcxxx`234 blah

And now I just have to run another replace to remove the backtick.. But how to do this with one step?

**Comment by ArturoDent** [comment]
See extended discussion and workaround at https://stackoverflow.com/a/62851339/836330

**Comment by ArturoDent** [comment]
This has previously been asked on SO - see link above.  There are workarounds mentioned there but it remains a bug.

You cannot replace with `$1234` where that indicates replace with capture group 1 followed by any digits.  The actual output is the literal `$1234`.  

Yet replacing with `$1$2234` where capture group 2 is empty works properly!, as does "$1$`234" or "$`$1234".

I think this question should remain open.

**Comment by ArturoDent** [comment]
@rebornix Also note that replacing with `$122` where the intent is to replace with capture group 1 followed by 2 digits fails, whereas replacing with `$12` works!  Appending one digit works, any more than that fails.
