### ISSUE TITLE
Code intellisense does not working for new typescript  file util reload window

### ISSUE THREAD

**Issue by mkideal** [microsoft/vscode#102299]
- VSCode Version: 1.47.0
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Create a new ts file, then code intellisense does not working
2. After reload window, it's ok

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
