### ISSUE TITLE
Markdown preview window does not work.

### ISSUE THREAD

**Issue by sarahkittyy** [microsoft/vscode#102267]
- VSCode Version:
```
1.48.0-insider
e7920dce7bfd0b707ebfc0a5379c6edd2233e475
x64
```
- OS Version:
```Linux sarahkitty 5.7.4-arch1-1 #1 SMP PREEMPT Thu, 18 Jun 2020 16:01:07 +0000 x86_64 GNU/Linux```

Steps to Reproduce:
1. Open a markdown file.
2. Open the markdown preview window.
3. Start editing the markdown file.
4. After a minute of editing, the markdown window no longer updates.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please try again in the latest insiders build. This should already be fixed
