### ISSUE TITLE
Save Conflict Compare Tab Not Working

### ISSUE THREAD

**Issue by abdullahseba** [microsoft/vscode#102218]
1.  Make unsaved changes to a file.
2.  Open the file in another editor (e.g. Notepad) and make and save come changes.
3.  Return to VSCode and save the file.  VSCode will warn you of newer changes to file.
4.  Click compare.

See GIF below.  I have also tried this with `--disable-extensions`.  

![vSKbbKoyMO](https://user-images.githubusercontent.com/25548754/87225441-f2831e00-c384-11ea-95b9-7d862e2d456b.gif)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (6.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
markdown-toc|Ala|1.5.6
vscode-apollo|apo|1.16.5
color-info|bie|0.5.1
markdown-emoji|bie|0.0.9
vscode-intelephense-client|bme|1.5.0
phpserver|bra|2.4.6
bracket-pair-colorizer-2|Coe|0.2.0
markdown-table-prettify|dar|2.5.0
vscode-markdownlint|Dav|0.36.1
vscode-eslint|dba|2.1.6
prettier-vscode|esb|5.1.3
php-debug|fel|1.13.0
mdmath|goe|2.5.1
svgeditor|hen|2.9.0
beautify|Hoo|1.5.0
discord-vscode|icr|3.15.0
graphql-for-vscode|kum|1.15.3
auto-collapse-explorer|luk|1.0.0
php-namespace-resolver|Meh|1.1.8
HTMLHint|mka|0.8.0
vscode-edge-devtools|ms-|1.0.7
remote-wsl|ms-|0.44.4
cpptools|ms-|0.28.3
powershell|ms-|2020.6.0
debugger-for-chrome|msj|4.12.9
color-highlight|nau|2.3.0
vetur|oct|0.24.0
vscode-jest|Ort|3.2.0
material-icon-theme|PKi|4.2.0
vscode-css-peek|pra|3.0.2
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.12
code-spell-checker|str|1.9.0
vscode-arduino|vsc|0.3.1
vscode-wakatime|Wak|4.0.0
iis-express|war|1.1.2
markdown-all-in-one|yzh|3.1.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@abdullahseba I cannot reproduce.

Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by abdullahseba** [comment]
Sorry, I tried this again with extensions disabled and it appears to work fine when extensions are disabled.  I assume it must be an extension somewhere.  Not sure what happened the other day.  Feel free to close the issue and I'll see if I can track down the extension and recreate it with the author.

Here are the logs anyway:
<details>
<summary><code>--verbose</code>:</summary>
<br>
<pre><code>
[main 2020-07-13T20:41:19.375Z] Sending some foreground love to the running instance: 22372
[main 2020-07-13T20:41:19.378Z] Sending env to running instance...
[main 2020-07-13T20:41:19.491Z] Sent env to running instance. Terminating...
[main 2020-07-13T20:41:19.491Z] Lifecycle#kill()
</code></pre>
</details>
<details>
<summary>Console:</summary>

<br>
<pre><code>
abstractExtensionService.ts:415 [ms-vscode.powershell]: Command `workbench.action.debug.start` appears multiple times in the `commands` section.
abstractExtensionService.ts:415 [ms-vscode.powershell]: Command `workbench.action.closePanel` appears multiple times in the `commands` section.
abstractExtensionService.ts:415 [ms-vscode.powershell]: Command `workbench.action.positionPanelLeft` appears multiple times in the `commands` section.
abstractExtensionService.ts:415 [ms-vscode.powershell]: Command `workbench.action.positionPanelBottom` appears multiple times in the `commands` section.
7abstractExtensionService.ts:415 [MehediDracula.php-namespace-resolver]: Menu item references the same command as default and alt-command
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.graphql.
Old grammar file: file:///c%3A/Users/Abdullah/.vscode/extensions/apollographql.vscode-apollo-1.16.5/syntaxes/graphql.json.
New grammar file: file:///c%3A/Users/Abdullah/.vscode/extensions/kumar-harsh.graphql-for-vscode-1.15.3/syntaxes/graphql.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope inline.graphql.
Old grammar file: file:///c%3A/Users/Abdullah/.vscode/extensions/apollographql.vscode-apollo-1.16.5/syntaxes/graphql.js.json.
New grammar file: file:///c%3A/Users/Abdullah/.vscode/extensions/kumar-harsh.graphql-for-vscode-1.15.3/syntaxes/graphql.js.json
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] Starting express server on port: 58821 (at LocalWebServer.start (c:\Users\Abdullah\.vscode\extensions\vsciot-vscode.vscode-arduino-0.3.1\out\src\arduino\localWebServer.js:32:17))
console.ts:137 [Extension Host] using default c:\Users\Abdullah\.vscode\extensions\vsciot-vscode.vscode-arduino-0.3.1\out\node_modules\usb-detection\build\Release\detection.node (at Object.loadLibrary [as load] (c:\Users\Abdullah\.vscode\extensions\vsciot-vscode.vscode-arduino-0.3.1\out\node_modules\node-usb-native\lib\native_loader.js:15:13))
console.ts:137 [Extension Host] using default c:\Users\Abdullah\.vscode\extensions\vsciot-vscode.vscode-arduino-0.3.1\out\node_modules\@serialport\bindings\build\Release\bindings.node (at Object.loadLibrary [as load] (c:\Users\Abdullah\.vscode\extensions\vsciot-vscode.vscode-arduino-0.3.1\out\node_modules\node-usb-native\lib\native_loader.js:15:13))
console.ts:137 [Extension Host] Error: Document version already has changed	at c:\Users\Abdullah\.vscode\extensions\naumovs.color-highlight-2.3.0\dist\extension.js:2903:17	at processTicksAndRejections (internal/process/task_queues.js:85:5) (at c:\Users\Abdullah\.vscode\extensions\naumovs.color-highlight-2.3.0\dist\extension.js:2938:24)
log.ts:197   ERR [text file model] handleSaveError(7) - exit - resulted in a save error: Error: Unable to write file 'c:\Users\Abdullah\test.txt' (Error: File Modified Since) file:///c:/Users/Abdullah/test.txt
notificationsAlerts.ts:40 Failed to save 'test.txt': The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
onSaveError @ textFileSaveErrorHandler.ts:184
handleSaveError @ textFileEditorModel.ts:752
(anonymous) @ textFileEditorModel.ts:711
async function (async)
(anonymous) @ textFileEditorModel.ts:700
(anonymous) @ textFileEditorModel.ts:698
processTicksAndRejections @ internal/process/task_queues.js:85
async function (async)
(anonymous) @ textFileEditorModel.ts:642
doSave @ textFileEditorModel.ts:633
save @ textFileEditorModel.ts:569
save @ textFileService.ts:198
doSave @ textResourceEditorInput.ts:182
save @ textResourceEditorInput.ts:168
(anonymous) @ editorService.ts:1036
save @ editorService.ts:1028
j @ fileCommands.ts:410
G @ fileCommands.ts:372
handler @ fileCommands.ts:422
invokeFunction @ instantiationService.ts:61
_tryExecuteCommand @ commandService.ts:84
(anonymous) @ commandService.ts:73
Promise.then (async)
executeCommand @ commandService.ts:73
_doDispatch @ abstractKeybindingService.ts:200
_dispatch @ abstractKeybindingService.ts:159
(anonymous) @ keybindingService.ts:251
6[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
</code></pre>
</details>

<details>
<summary>Console with extensions disabled:</summary>

<br>
<pre><code>
log.ts:197   ERR [text file model] handleSaveError(2) - exit - resulted in a save error: Error: Unable to write file 'c:\Users\Abdullah\test.txt' (Error: File Modified Since) file:///c:/Users/Abdullah/test.txt
notificationsAlerts.ts:40 Failed to save 'test.txt': The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes.
event.ts:19 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
event.ts:19 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
</code></pre>
</details>
