### ISSUE TITLE
A crash occurred when opening the "About" panel (Help->About)

### ISSUE THREAD

**Issue by nikeorever** [microsoft/vscode#102203]
- VSCode Version:1.47.0
- OS Version:Fedora 32

Steps to Reproduce:

1.After updating vscode to 1.47.0
2.Choose Help->About

Does this issue occur when all extensions are disabled?: Yes

Additional information:
vscode from the **snap store**(https://snapcraft.io/code)
Install using the command line:
`sudo snap install code --classic`

**Comment by joaomoreno** [comment]
Can you run with `code --verbose` and the reproduce the issue? Is there any output?

**Comment by nikeorever** [comment]
> Can you run with `code --verbose` and the reproduce the issue? Is there any output?
> 
> @deepak1556 Do you maybe have some ideas?

`
[main 2020-07-12T16:10:20.148Z] menubar#runActionInRenderer { type: 'commandId', commandId: 'workbench.action.showAboutDialog' }
[29271:0713/001020.162824:INFO:CONSOLE(1670)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.showAboutDialog", source: file:///var/lib/snapd/snap/code/36/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js (1670)
[29293:0713/001020.171528:WARNING:x11_util.cc(1399)] X error received: serial 1748, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
(code:29271): GdkPixbuf-WARNING **: 00:10:20.173: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(code:29271): Gtk-WARNING **: 00:10:20.173: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
(code:29271): GdkPixbuf-WARNING **: 00:10:20.173: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:/build/gtk+3.0-24RAPQ/gtk+3.0-3.22.24/./gtk/gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
Server response: {"status":"Success","validDiagnostic
`

**Comment by nikeorever** [comment]
This problem only occurs in the vscode in the snap repository. There is no problem with the vscode in the **yum repository**

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/100940, @nikeorever can you please follow along that issue for updates. Thanks!

**Comment by nikeorever** [comment]
> Merging this to https://github.com/microsoft/vscode/issues/100940, @nikeorever can you please follow along that issue for updates. Thanks!
ok
