### ISSUE TITLE
js-debug should automatically try to append PATHEXTs to binaries on windows

### ISSUE THREAD

**Issue by lengyuxuan** [microsoft/vscode#102235]
Issue Type: <b>Bug</b>

spawn E:\xxxxxx\node_modules\.bin\electron ENOENT
       at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)
launch.json:
{
  // 使用 IntelliSense 了解相关属性。 
  // 悬停以查看现有属性的描述。
  // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Electron Main",
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
      "program": "${workspaceFolder}/out/app.js",
      "skipFiles": [
        "<node_internals>/**"
      ]
    },
  ]
}

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.42GB free)|
|Process Argv|E:\vscode\auth-center|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.6
xml|Dot|2.5.0
gitlens|eam|10.2.2
fund|fan|0.0.2
gist|fan|0.0.2
readbook|fan|0.0.1
svgeditor|hen|2.9.0
polacode-2019|jef|0.5.2
vscode-docker|ms-|1.3.1
vscode-language-pack-zh-hans|MS-|1.47.3
python|ms-|2020.6.91350
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
cpptools|ms-|0.28.3
vscode-typescript-tslint-plugin|ms-|1.2.3
vsc-netease-music|non|0.0.39
vetur|oct|0.24.0
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.12
open-in-browser|tec|2.0.0
vscode-proto3|zxh|0.4.2

</details>

**Comment by connor4312** [comment]
ENOENT indicates that that binary wasn't found. Did you `npm install` beforehand?

/needsMoreInfo

**Comment by lengyuxuan** [comment]
sure, but when I set "runtimeExecutable=${workspaceFolder}/node_modules/.bin/electron.cmd" can run ok. before last version, I needn't append ".cmd"

**Comment by connor4312** [comment]
Ah, interesting. Good find. Will try to fix that up this month.

**Comment by connor4312** [comment]
This will be fixed in the next [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension) available at 5PM PST today.
