### ISSUE TITLE
Bug in python "Jupyter Notebook"

### ISSUE THREAD

**Issue by Mega-Barrel** [microsoft/vscode#102205]
- VSCode Version: JUNE 2020 1.47
- OS Version: Windows 10 pro

Steps to Reproduce:

1. Open Jupyter notebook copy any code or comment and paste it in the cell, the copied text/code gets pasted 2 times.

Eg: I copied df['min_salary'], it got pasted 2 times as df['min_salary']df['min_salary'].

I have also attached a screen-shot of the problem.

![Jupyter_Notebook](https://user-images.githubusercontent.com/34334153/87223109-cd4bdb00-c397-11ea-9085-9b936c65e679.jpg)

Does this issue occur when all extensions are disabled?: Yes/No  No.

**Comment by Karl60** [comment]
Was pasting twice now started pasting 4 times for a single cntrl-v.

**Comment by Sparks-MG** [comment]
This issue started for me a few days ago as well.

**Comment by ARudiuk** [comment]
I have been getting this the past couple days as well

**Comment by woogyumi** [comment]
i have same problem, i hope to fixed this bug early

**Comment by FiratErman** [comment]
Same for me. Don't find any issue for the moment

**Comment by machine-gurning** [comment]
I have the same issue

**Comment by tianyu-liu** [comment]
In my case, it occurs as if I have pressed `Ctrl + V` twice. Therefore, following with `Ctrl + Z`, I can keep using VS Code for now.

**Comment by Mega-Barrel** [comment]
# This issue has been solved.
