### ISSUE TITLE
Deprecated fat arrow functions not crossed out

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#102237]
Such as these in dom.ts:

![image](https://user-images.githubusercontent.com/323878/87231385-ac6d9080-c36b-11ea-811d-eefe73373b79.png)

Usages are not marked as deprecated:

![image](https://user-images.githubusercontent.com/323878/87231389-b8595280-c36b-11ea-8021-ec95621116f5.png)

If I change them to a normal `function`, it works

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/39374
