### ISSUE TITLE
attach by process id not working

### ISSUE THREAD

**Issue by chetank628** [microsoft/vscode#102219]
- VSCode Version:1.47
- OS Version: 10.15.5 mac os catalina (mac book pro 13 2019)

Steps to Reproduce:

1.Add following configuration in Debugger launch.json
```
 {
            "type": "node",
            "request": "attach",
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}",
            "skipFiles": [
                "<node_internals>/**"
            ]
  }
```
2.pick a process from command picker  gets error Breakpoint is unbound

Works perfectly with vscode version 1.46

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Thanks for the issue! Can you enable `trace: true` and share the resulting log file? Its location will be written in the Debug Console

**Comment by chetank628** [comment]
@connor4312 Here is the logs as you suggested 
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode/files/5067646/vscode-debugadapter-1.json.gz)

**Comment by chetank628** [comment]
can we reopen this issue..? or should i open. a new issues

**Comment by connor4312** [comment]
Please try either: 

1. Update off of the end of life Node 8
1. Use the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) and set `enableContentValidation: false`
