### ISSUE TITLE
Formatter implementation not working

### ISSUE THREAD

**Issue by MaxBec** [microsoft/vscode#102286]
Issue Type: <b>Bug</b>

- Launch Extension
- Right click Reformat file (.items file from openhab)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.94GB free)|
|Process Argv|-psn_0_4457536|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.2
npm-intellisense|chr|1.3.0
doxdocgen|csc|0.7.2
vs-treeview|DaG|2.7.0
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.1.3
vscode-pull-request-github|Git|0.17.0
todo-tree|Gru|0.0.178
output-colorizer|IBM|0.1.2
latex-workshop|Jam|8.11.1
oh-alignment-tool|max|1.3.12
theme-monokai-pro-vscode|mon|1.1.17
hg|mrc|1.6.0
cmake-tools|ms-|1.4.1
cpptools|ms-|0.28.3
vscode-typescript-tslint-plugin|ms-|1.2.3
openhab|ope|0.7.0
material-icon-theme|PKi|4.2.0
platformio-ide|pla|1.10.0
java|red|0.64.1
vscode-qt-for-python|sea|0.4.2
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.9.0
code-spell-checker-german|str|0.1.4
latex-utilities|tec|0.3.7
qtvsctools|ton|0.4.0
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0
material-theme|zhu|3.8.3

(2 theme extensions excluded)

</details>

---

Hey guys,

With the following implementation nothing happens when saving the file (format on save enabled) or when reformatting the file with a right click. I tried a lot of other solutions but none of them worked. I hope you can help me.

```typescript
export function activate(context: vscode.ExtensionContext) {
	vscode.languages.registerDocumentFormattingEditProvider("openhab", {
		provideDocumentFormattingEdits(document: vscode.TextDocument, options: vscode.FormattingOptions): vscode.TextEdit[] {
			var range = getDocumentRange(document);
			var content = document.getText(range);
			var result: vscode.TextEdit[] = [];
			var formatted = formatItemFile();
			//if (formatted) {
			//	result.push(new vscode.TextEdit(range, formatted));
			//}
			return formatted;
		},
	});
}
```

```typescript
export function formatItemFile(): vscode.TextEdit[] {
	var result: vscode.TextEdit[] = [];
	// Get the section lengths of each line with an item in it.
	// Only execute if there's an active text editor
	if (!vscode.window.activeTextEditor) {
		return result;
	}

	// Define the basic vscode variables
	let doc = vscode.window.activeTextEditor.document;
	let editor = vscode.window.activeTextEditor;
	let currentPos = editor.selection.active;
	let newPos: vscode.Position;
	let itemArray: Array<Item>;
	itemArray = new Array();

	// Get the format configuration settings
	let config = vscode.workspace.getConfiguration("oh-alignment-tool");
	let preserveWhitespace = config.preserveWhitespace;

	// Reset the comment tracker
	isInBlockComment = false;

	// Clear the file in case of line-by-line item definitions
	for (let index = 0; index < doc.lineCount; index++) {
		// Get Position at the beginning of the current line and start a selection
		newPos = currentPos.with(index, 0);
		editor.selection = new vscode.Selection(newPos, newPos);

		// Get Text of current line and check if there is a comment in it
		let lineText = doc.lineAt(newPos.line);
		var comment = doc.getWordRangeAtPosition(newPos.with(newPos.line, 0), REGEX_COMMENT);
		var blockComment = doc.getWordRangeAtPosition(newPos.with(newPos.line, 0), REGEX_START_BLOCKCOMMENT);
		var endBlockComment = doc.getWordRangeAtPosition(newPos.with(newPos.line, 0), REGEX_END_BLOCKCOMMENT);

		// If line is empty or contains a comment continue to the next line
		if (lineText.text.length === 0 || lineText.isEmptyOrWhitespace) {
			continue;
		} else if (comment) {
			continue;
		} else if (blockComment && endBlockComment) {
			isInBlockComment = false;
			continue;
		} else if (blockComment) {
			isInBlockComment = true;
			continue;
		} else if (endBlockComment) {
			isInBlockComment = false;
			continue;
		} else if (isInBlockComment) {
			continue;
		}

		// Default these to empty. They will be changed
		// if they exist in the item definition
		let itemType = "";
		let itemName = "";
		let itemLabel = "";
		let itemIcon = "";
		let itemGroup = "";
		let itemTag = "";
		let itemChannel = "";
		let itemComment = "";

		// Check if there is leading Whitespace. If Yes add one in size of a tab.
		let leadingWhiteSpace = lineText.firstNonWhitespaceCharacterIndex;

		if (preserveWhitespace === false) {
			leadingWhiteSpace = 0;
		}

		// Discover item Type
		// Count Whitespace or tabs at the begin of the line
		newPos = newPos.with(newPos.line, newPos.character + utils.countWhitespace(doc, newPos));
		var wordRange = doc.getWordRangeAtPosition(newPos, REGEX_ITEM_TYPE);
		if (wordRange && wordRange.isSingleLine) {
			itemType = doc.getText(wordRange);
			highestTypeLength = itemType.length > highestTypeLength ? itemType.length : highestTypeLength;
			newPos = newPos.with(newPos.line, newPos.character + itemType.length);
			newPos = newPos.with(newPos.line, newPos.character + utils.countWhitespace(doc, newPos));

			// Discover item Name
			var itemNameRange = doc.getWordRangeAtPosition(newPos, REGEX_ITEM_NAME);
			if (itemNameRange && itemNameRange.isSingleLine) {
				itemName = doc.getText(itemNameRange);
				highestNameLength = itemName.length > highestNameLength ? itemName.length : highestNameLength;
				newPos = newPos.with(newPos.line, newPos.character + itemName.length);
				newPos = newPos.with(newPos.line, newPos.character + utils.countWhitespace(doc, newPos));
			}
		}
		// Must have a type and name to continue
		if (itemType.length === 0 || itemName.length === 0) {
			continue;
		}
		// Discover item Label
		let itemLabelRange = doc.getWordRangeAtPosition(newPos, REGEX_ITEM_LABEL);
		if (itemLabelRange && itemLabelRange.isSingleLine) {
			itemLabel = doc.getText(itemLabelRange);
			highestLabelLength = itemLabel.length > highestLabelLength ? itemLabel.length : highestLabelLength;
			newPos = newPos.with(newPos.line, newPos.character + itemLabel.length);
			newPos = newPos.with(newPos.line, newPos.character + utils.countWhitespace(doc, newPos));
		}
		// Discover item Icon
		let itemIconRange = doc.getWordRangeAtPosition(newPos, REGEX_ITEM_ICON);
		if (itemIconRange && itemIconRange.isSingleLine) {
			itemIcon = doc.getText(itemIconRange);
			highestIconLength = itemIcon.length > highestIconLength ? itemIcon.length : highestIconLength;
			newPos = newPos.with(newPos.line, newPos.character + itemIcon.length);
			newPos = newPos.with(newPos.line, newPos.character + utils.countWhitespace(doc, newPos));
		}
		// Discover item Group
		let itemGroupRange = doc.getWordRangeAtPosition(newPos, REGEX_ITEM_GROUP);
		if (itemGroupRange && itemGroupRange.isSingleLine) {
			itemGroup = doc.getText(itemGroupRange);
			highestGroupLength = itemGroup.length > highestGroupLength ? itemGroup.length : highestGroupLength;
			newPos = newPos.with(newPos.line, newPos.character + itemGroup.length);
			newPos = newPos.with(newPos.line, newPos.character + utils.countWhitespace(doc, newPos));
		}
		// Discover item Tag
		let itemTagRange = doc.getWordRangeAtPosition(newPos, REGEX_ITEM_TAG);
		if (itemTagRange && itemTagRange.isSingleLine) {
			itemTag = doc.getText(itemTagRange);
			highestTagLength = itemTag.length > highestTagLength ? itemTag.length : highestTagLength;
			//console.log("Tag: " + itemTag);
			newPos = newPos.with(newPos.line, newPos.character + itemTag.length);
			newPos = newPos.with(newPos.line, newPos.character + utils.countWhitespace(doc, newPos));
		}
		// Discover item Channel
		let itemChannelRange = doc.getWordRangeAtPosition(newPos, REGEX_ITEM_CHANNEL);
		if (itemChannelRange && itemChannelRange.isSingleLine) {
			itemChannel = doc.getText(itemChannelRange);
			highestChannelLength = itemChannel.length > highestChannelLength ? itemChannel.length : highestChannelLength;
			newPos = newPos.with(newPos.line, newPos.character + itemChannel.length);
			newPos = newPos.with(newPos.line, newPos.character + utils.countWhitespace(doc, newPos));
		}
		// Discover comment at end of line
		let itemCommentRange = doc.getWordRangeAtPosition(newPos, REGEX_EOL_COMMENT);
		if (itemCommentRange && itemCommentRange.isSingleLine) {
			itemComment = doc.getText(itemCommentRange);
			newPos = newPos.with(newPos.line, newPos.character + itemComment.length);
			newPos = newPos.with(newPos.line, newPos.character + utils.countWhitespace(doc, newPos));
		}

		// Add the new item to the itemArray
		itemArray.push(new Item(index, leadingWhiteSpace, itemType, itemName, itemLabel, itemIcon, itemGroup, itemTag, itemChannel, itemComment));
	}

	// Convert the column lengths to tabs
	highestTypeLength = utils.generateTabFromSpaces(highestTypeLength);
	highestNameLength = utils.generateTabFromSpaces(highestNameLength);
	highestLabelLength = utils.generateTabFromSpaces(highestLabelLength);
	highestIconLength = utils.generateTabFromSpaces(highestIconLength);
	highestGroupLength = utils.generateTabFromSpaces(highestGroupLength);
	highestTagLength = utils.generateTabFromSpaces(highestTagLength);
	highestChannelLength = utils.generateTabFromSpaces(highestChannelLength);

	// Insert the newly formatted items
	itemArray.forEach(function (item) {
		newPos = currentPos.with(item.line, 0);
		editor.selection = new vscode.Selection(newPos, newPos);
		let reformattedItem = formatItem(item);
		if (reformattedItem !== "") {
			let selection = new vscode.Range(newPos, newPos.with(newPos.line, doc.lineAt(newPos.line).text.length));
			result.push(new vscode.TextEdit(selection, reformattedItem));
		}
	});

	// Apply all    clean and formatting Edits
	//textWorkEdit.set(doc.uri, textTextEdits);
	//await vscode.workspace.applyEdit(textWorkEdit);

	return result;
}
```

**Comment by jrieken** [comment]
> With the following implementation nothing happens when saving the file (format on save enabled) 

Means what?

**Comment by MaxBec** [comment]
The code doesn't get formatted.
I debugged the extension and there are changes in the result variable. But they don't get applied somehow. :/
Am 13. Juli 2020, 10:34 +0200 schrieb Johannes Rieken <notifications@github.com>:

**Comment by jrieken** [comment]
> there are changes in the result variable

Are they making any changes? How about returning a formatting "result" that replaces everything with some random string. Then you know that the wiring and setup is correct and you start looking into your results.

**Comment by MaxBec** [comment]
Yes they do. I added a random string (DEBUG) at the end of each line for testing. And it is also visible in the result (1).
But it doesn't appear in the final code (2).

![extension_ts_—_openHAB-Alignment-Tool](https://user-images.githubusercontent.com/8254514/87291183-3e59d280-c4ff-11ea-934b-265cfa812688.png)

![_Extension_Development_Host__-_test_items_—_tests](https://user-images.githubusercontent.com/8254514/87291264-5b8ea100-c4ff-11ea-9f97-52de5417126a.png)

**Comment by jrieken** [comment]
No, I meant to try this `return [new vscode.TextEdit(new vscode.Range(0, 0, 0, 0), 'Foo')]`. Your edits might be flawed in other ways, eg. overlap each other or so. So, try the simplest of all "formatters" and then go from there. Also check the console in dev tools and the window log for suspicious messages

**Comment by MaxBec** [comment]
Ok i tried your line:

1. Foo get's added to the file correctly at the beginning! With each "Format" one more "Foo".
2. Now i tried this and it doesn't work. I really dont get why...

```typescript
function formatItemFile(): vscode.TextEdit[] {
	var result: vscode.TextEdit[] = [];
        itemArray.forEach(function (item) {
		result.push(new vscode.TextEdit(new vscode.Range(0, 0, 0, 0), "Foo"));
	});

	// Apply all    clean and formatting Edits
	//textWorkEdit.set(doc.uri, textTextEdits);
	//await vscode.workspace.applyEdit(textWorkEdit);

	return result;
}
```

**Comment by MaxBec** [comment]
No suspicious message in the dev tools console:

![Developer_Tools_-_file____Applications_Visual_20Studio_20Code_app_Contents_Resources_app_out_vs_code_electron-browser_workbench_workbench_html_config__7B_22__22_3A_5B_5D_2C_22appRoot_22_3A_22_2FApplications_2FVisual_20Studio_20Code_app_2FCo](https://user-images.githubusercontent.com/8254514/87304880-d4005c80-c515-11ea-994c-757edf145486.png)

No messages in the window debug log:

![extension_ts_—_openHAB-Alignment-Tool](https://user-images.githubusercontent.com/8254514/87304911-dfec1e80-c515-11ea-833f-04b2f2a23634.png)

**Comment by jrieken** [comment]
idk - your provider is invoked correctly, running the snippet below 👇  works for me so I'd say that's an issue with the result or non-result of your formatter implementation. The only additional insides is that you edits cannot overlap but they can touch (as they do in the sample)

```
vscode.languages.registerDocumentFormattingEditProvider('plaintext', new class implements vscode.DocumentFormattingEditProvider {
	provideDocumentFormattingEdits(document: vscode.TextDocument, options: vscode.FormattingOptions, token: vscode.CancellationToken): vscode.ProviderResult<vscode.TextEdit[]> {
		return [
			vscode.TextEdit.insert(new vscode.Position(0, 0), "Hello"),
			vscode.TextEdit.insert(new vscode.Position(0, 0), "Hello"),
			vscode.TextEdit.insert(new vscode.Position(0, 0), "Hello"),
		]
	}
})
```

**Comment by MaxBec** [comment]
Ok thank you. I think one problem was the overlapping of TextEdits.
What is the correct approach for multiple formatting steps? E.g. first remove all unnecessary empty lines, and after that format the rest of the code?

**Comment by jrieken** [comment]
> What is the correct approach for multiple formatting steps? E.g. first remove all unnecessary empty lines, and after that format the rest of the code?

Unsure, formatting is tricky and I guess it depends on the use-case and what underlaying data structures you have. Generally, formatting should be a one step thing.

**Comment by MaxBec** [comment]
I found out that with this code the formatting doesn't work. Essential are the first two lines. But why?

```typescript
newPos = currentPos.with(0, 0);
editor.selection = new vscode.Selection(newPos, newPos);
result.push(vscode.TextEdit.insert(new vscode.Position(0, 0), "Hello"));

return result;
```
