### ISSUE TITLE
"enter" doesn't navigate in peek references tree

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#102230]
- Trigger find all references
- Use arrow keys to focus some result
- Press enter
- nothing happens, can use cmd+down though

**Comment by joaomoreno** [comment]
@jrieken I'll take it, since it's very likely due to my changes.

**Comment by joaomoreno** [comment]
I can't repro... this might be a macOS specific issue. @roblourens Can you still reproduce?

**Comment by roblourens** [comment]
Oh yeah I think this was fixed awhile ago.
