### ISSUE TITLE
VSCode remote is out of memory

### ISSUE THREAD

**Issue by assafmendelson** [microsoft/vscode#102387]
- VSCode Version: Version: 1.47.0 (system setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open a very large C++ and python project in vscode using ssh remote
2. work a little. 

cores and reports are being created. The report looks something like this:

`

{
  "header": {
    "event": "Allocation failed - JavaScript heap out of memory",
    "trigger": "FatalError",
    "filename": "report.20200712.202131.8152.0.001.json",
    "dumpEventTime": "2020-07-12T20:21:31Z",
    "dumpEventTimeStamp": "1594574491876",
    "processId": 8152,
    "cwd": "MY_PROJECT_DIR_REPLACED",
    "commandLine": [
      "/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node",
      "/REPLACED_MY_HOME_DIR/.vscode-server/extensions/ms-python.vscode-pylance-2020.7.1/server/server.bundle.js",
      "--cancellationReceive=file:67149040d0c7ff9e7b1af1d3480a9e5b2d2a6316ff",
      "--node-ipc",
      "--clientProcessId=22990"
    ],
    "nodejsVersion": "v12.4.0",
    "glibcVersionRuntime": "2.17",
    "glibcVersionCompiler": "2.17",
    "wordSize": 64,
    "arch": "x64",
    "platform": "linux",
    "componentVersions": {
      "node": "12.4.0",
      "v8": "7.4.288.27-node.18",
      "uv": "1.29.1",
      "zlib": "1.2.11",
      "brotli": "1.0.7",
      "ares": "1.15.0",
      "modules": "72",
      "nghttp2": "1.38.0",
      "napi": "4",
      "llhttp": "1.1.3",
      "http_parser": "2.8.0",
      "openssl": "1.1.1b",
      "cldr": "35.1",
      "icu": "64.2",
      "tz": "2019a",
      "unicode": "12.1"
    },
    "release": {
      "name": "node",
      "headersUrl": "https://nodejs.org/download/release/v12.4.0/node-v12.4.0-headers.tar.gz",
      "sourceUrl": "https://nodejs.org/download/release/v12.4.0/node-v12.4.0.tar.gz"
    },
    "osName": "Linux",
    "osRelease": "3.10.0-514.26.2.el7.x86_64",
    "osVersion": "#1 SMP Tue Jul 4 15:04:05 UTC 2017",
    "osMachine": "x86_64",
    "host": "devvm27.xiolab.lab.emc.com"
  },
  "javascriptStack": {
    "message": "No stack.",
    "stack": [
      "Unavailable."
    ]
  },
  "nativeStack": [
    {
      "pc": "0x0000000000aadaf5",
      "symbol": "report::TriggerNodeReport(v8::Isolate*, node::Environment*, char const*, char const*, std::string const&, v8::Local<v8::String>) [/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node]"
    },
    {
      "pc": "0x000000000098fec3",
      "symbol": "node::OnFatalError(char const*, char const*) [/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node]"
    },
    {
      "pc": "0x0000000000b1552e",
      "symbol": "v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node]"
    },
    {
      "pc": "0x0000000000b158a9",
      "symbol": "v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node]"
    },
    {
      "pc": "0x0000000000f20105",
      "symbol": " [/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node]"
    },
    {
      "pc": "0x0000000000f2aa6b",
      "symbol": "v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node]"
    },
    {
      "pc": "0x0000000000f2b787",
      "symbol": "v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node]"
    },
    {
      "pc": "0x0000000000f2e225",
      "symbol": "v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node]"
    },
    {
      "pc": "0x0000000000ef9250",
      "symbol": "v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node]"
    },
    {
      "pc": "0x00000000011cb0ce",
      "symbol": "v8::internal::Runtime_AllocateInNewSpace(int, unsigned long*, v8::internal::Isolate*) [/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node]"
    },
    {
      "pc": "0x0000000001a93942",
      "symbol": " [/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node]"
    }
  ],
  "javascriptHeap": {
    "totalMemory": 2152955904,
    "totalCommittedMemory": 2148347000,
    "usedMemory": 2052819416,
    "availableMemory": 49586376,
    "memoryLimit": 2197815296,
    "heapSpaces": {
      "read_only_space": {
        "memorySize": 524288,
        "committedMemory": 32024,
        "capacity": 523976,
        "used": 31712,
        "available": 492264
      },
      "new_space": {
        "memorySize": 4194304,
        "committedMemory": 1289624,
        "capacity": 2095904,
        "used": 239512,
        "available": 1856392
      },
      "old_space": {
        "memorySize": 2131353600,
        "committedMemory": 2130809120,
        "capacity": 2037478496,
        "used": 2037196072,
        "available": 282424
      },
      "code_space": {
        "memorySize": 2260992,
        "committedMemory": 2036448,
        "capacity": 1385920,
        "used": 1385920,
        "available": 0
      },
      "map_space": {
        "memorySize": 1052672,
        "committedMemory": 609736,
        "capacity": 496160,
        "used": 496160,
        "available": 0
      },
      "large_object_space": {
        "memorySize": 13520896,
        "committedMemory": 13520896,
        "capacity": 13466584,
        "used": 13466584,
        "available": 0
      },
      "code_large_object_space": {
        "memorySize": 49152,
        "committedMemory": 49152,
        "capacity": 3456,
        "used": 3456,
        "available": 0
      },
      "new_large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 2095904,
        "used": 0,
        "available": 2095904
      }
    }
  },
  "resourceUsage": {
    "userCpuSeconds": 458.096,
    "kernelCpuSeconds": 54.7266,
    "cpuConsumptionPercent": 183.151,
    "maxRss": 2266836992,
    "pageFaults": {
      "IORequired": 0,
      "IONotRequired": 18045112
    },
    "fsActivity": {
      "reads": 0,
      "writes": 22856
    }
  },
  "uvthreadResourceUsage": {
    "userCpuSeconds": 223.646,
    "kernelCpuSeconds": 16.9849,
    "cpuConsumptionPercent": 85.9395,
    "fsActivity": {
      "reads": 0,
      "writes": 0
    }
  },
  "libuv": [
  ],
  "environmentVariables": {
    "REMOVED_MANY_OF_THE_ENIRONMENT_VARIABLES",
    "SHELL": "/bin/bash",
    "HISTSIZE": "10000",
    "QTDIR": "/usr/lib64/qt-3.3",
    "QTINC": "/usr/lib64/qt-3.3/include",
    "HISTSIZE_NORMAL": "10000",
    "QT_GRAPHICSSYSTEM_CHECKED": "1",
    "HISTFILESIZE": "-1",
    "SSH_AUTH_SOCK": "/run/user/REPLACED/vscode-ssh-auth-sock-302511729",
    "VSCODE_AGENT_FOLDER": "/REPLACED_MY_HOME_DIR/.vscode-server",
    "PATH": "/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/bin:/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/bin:/usr/lib64/qt-3.3/bin:/usr/local/share/idea-IC-163.11103.6/bin:/usr/local/bin:/usr/bin:~/bin:/usr/local/sbin:/usr/sbin",
    "PWD": "/REPLACED_MY_HOME_DIR",
    "JAVA_HOME": "/usr/lib/jvm/java-1.8.0-openjdk/",
    "EDITOR": "nano",
    "LANG": "en_US.UTF-8",
    "KDEDIRS": "/usr",
    "HISTCONTROL": "erasedups",
    "SHLVL": "4",
    "HOME": "/REPLACED_MY_HOME_DIR",
    "PYTHONPATH": ":/REPLACED",
    "QTLIB": "/usr/lib64/qt-3.3/lib",
    "PROMPT_COMMAND": "history -a",
    "DEVOPS_BUILD_FLAVOR": "DEBUG",
    "QT_PLUGIN_PATH": "/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins",
    "HISTFILE": "/REPLACED_MY_HOME_DIR/.bash_history_managed",
    "_": "/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/node",
    "VSCODE_INJECT_NODE_MODULE_LOOKUP_PATH": "/REPLACED_MY_HOME_DIR/.vscode-server/bin/d5e9aa0227e057a60c82568bf31c04730dc15dcd/remote/node_modules",
    "VSCODE_LOGS": "/REPLACED_MY_HOME_DIR/.vscode-server/data/logs/20200712T124224",
    "PS1": "[\\u@\\h:\\w \\[\\033[32m\\]($(git branch 2>/dev/null | grep '^*' | colrm 1 2))\\[\\033[00m\\]]$ ",
    "AMD_ENTRYPOINT": "vs/server/remoteExtensionHostProcess",
    "PIPE_LOGGING": "true",
    "VERBOSE_LOGGING": "true",
    "VSCODE_EXTHOST_WILL_SEND_SOCKET": "true",
    "VSCODE_HANDLES_UNCAUGHT_ERRORS": "true",
    "VSCODE_LOG_STACK": "false",
    "VSCODE_NLS_CONFIG": "{\"locale\":\"en\",\"availableLanguages\":{}}",
    "VSCODE_IPC_HOOK_CLI": "/tmp/vscode-ipc-b8265955-9db2-463c-bfe7-44015f569dfb.sock",
    "APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL": "true",
    "ELECTRON_RUN_AS_NODE": "1",
    "ELECTRON_NO_ASAR": "1"
  },
  "userLimits": {
    "core_file_size_blocks": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "data_seg_size_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "file_size_blocks": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "max_locked_memory_bytes": {
      "soft": 65536,
      "hard": 65536
    },
    "max_memory_size_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "open_files": {
      "soft": 50000,
      "hard": 50000
    },
    "stack_size_bytes": {
      "soft": 8388608,
      "hard": "unlimited"
    },
    "cpu_time_seconds": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "max_user_processes": {
      "soft": 100000,
      "hard": 361761
    },
    "virtual_memory_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    }
  },
  "sharedObjects": [
    "/lib64/libdl.so.2",
    "/lib64/librt.so.1",
    "/lib64/libstdc++.so.6",
    "/lib64/libm.so.6",
    "/lib64/libgcc_s.so.1",
    "/lib64/libpthread.so.0",
    "/lib64/libc.so.6",
    "/lib64/ld-linux-x86-64.so.2"
  ]
}
`
Following are some of my definitions in my settings.json (the main one):
`
{
    "files.eol": "\n",
    "editor.mouseWheelZoom": true,
    "editor.renderWhitespace": "all",
    "workbench.editor.enablePreview": false,
    "terminal.integrated.shell.linux": "/bin/bash",
    "cmake.cmakePath": "/usr/bin/cmake",
    "window.zoomLevel": -1,
    "files.exclude": {
        "**/.git": true,
        "CMakeFiles": true
    },
    "files.watcherExclude": {
        "**/localrepo.m2/**": true
    },
    "bashIde.path": "",
    "diffEditor.ignoreTrimWhitespace": true,
    "C_Cpp.exclusionPolicy": "checkFilesAndFolders",
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "C_Cpp.updateChannel": "Insiders",
    "remote.SSH.showLoginTerminal": true,
    "remote.SSH.lockfilesInTmp": true,
    "C_Cpp.default.cppStandard": "c++14",
    "C_Cpp.default.cStandard": "c99",
    "terminal.integrated.scrollback": 100000,
    "C_Cpp.loggingLevel": "Debug",
    "remote.SSH.defaultExtensions": [
        "Name: Bash Debug Id: rogalmic.bash-debug Description: A debugger extension for bash scripts (using bashdb). Version: 0.3.6 Publisher: rogalmic VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=rogalmic.bash-debug",
        "Name: Bash IDE Id: mads-hartmann.bash-ide-vscode Description: A language server for Bash Version: 1.3.3 Publisher: Mads Hartmann VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode",
        "Name: C/C++ Id: ms-vscode.cpptools Description: C/C++ IntelliSense, debugging, and code browsing. Version: 0.26.2 Publisher: Microsoft VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools",
        "Name: CMake Id: twxs.cmake Description: CMake langage support for Visual Studio Code Version: 0.0.17 Publisher: twxs VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=twxs.cmake",
        "Name: Git History Id: donjayamanne.githistory Description: View git log, file history, compare branches or commits Version: 0.4.10 Publisher: Don Jayamanne VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory",
        "Name: Python Id: ms-python.python Description: Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more. Version: 2019.11.50794 Publisher: Microsoft VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-python.python",
        "Name: Rainbow Brackets Id: 2gua.rainbow-brackets Description: A rainbow brackets extension for VS Code. Version: 0.0.6 Publisher: 2gua VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets",
        "Name: vscode-proto3 Id: zxh404.vscode-proto3 Description: Protobuf 3 support for Visual Studio Code Version: 0.3.0 Publisher: zxh404 VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=zxh404.vscode-proto3"
    ],
    "C_Cpp.intelliSenseCacheSize": 15120,
    "files.autoSave": "afterDelay",
    "C_Cpp.default.compileCommands": "${workspaceFolder}/compile_commands.json",
    "merge-conflict.diffViewPosition": "Beside",
    "editor.minimap.enabled": false,
    "remote.SSH.remotePlatform": {
        "devvm27": "linux"
    },
    "cmake.buildBeforeRun": false,
    "cmake.configureOnEdit": false,
    "python.analysis.diagnosticMode": "workspace",
    "python.analysis.typeCheckingMode": "basic",
    "python.languageServer": "Pylance"
}

`

I suspect the main issue is that since our project is large I increased the intellisense cache size for the c++ extension considerably, however, I did not increased any other configuration memory which may be too small.
The machine itself has almost 90GB memory (most of it free) so the problem is not lack of physical memory.

Does this issue occur when all extensions are disabled?: I have not been able to reproduce this without extensions, however, without extensions I am not really doing anything.

**Comment by roblourens** [comment]
If I understand correctly, it looks like this is the pylance server running out of memory. Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
