### ISSUE TITLE
Fuzzy text in intellisense, sometimes completely empty white pane

### ISSUE THREAD

**Issue by tarunzoot** [Microsoft/vscode#10234]
- VSCode Version:1.4.0
- OS Version: Mac OSX El Capitan 10.11.6

Steps to Reproduce:

1. Create new css file, start typing position property, suddenly intellisense becomes fuzzy
Screenshot
<img width="1374" alt="screen shot 2016-08-06 at 1 51 53 pm" src="https://cloud.githubusercontent.com/assets/18568258/17455694/afe6cfb4-5bdd-11e6-99cd-479a20df5faa.png">

**Comment by estruyf** [comment]
Got the same issue with the latest version of VSCode and CSS.

**Comment by joaomoreno** [comment]
@tarunzoot @estruyf Can you give me a case in which you can *always* reproduce it?

**Comment by estruyf** [comment]
It seems to only happen when I open a folder/project (with ts, js, css files in it) and start writing code.

Don't have this behaviour if I open only one file in Code.

**Comment by joaomoreno** [comment]
What I meant was more a specific file and a specific set of steps to get into that state.

**Comment by estruyf** [comment]
Open a CSS file, type `background:` this shows a fuzzy auto-complete list.

OR 

Open a CSS file, start typing `po`, you get a fuzzy auto-complete list.

OR

Open a JS or TS file, type `variable1.` shows a fuzzy auto-complete list.

**Comment by joaomoreno** [comment]
I can't reproduce this. Which version do you have? Which OS? Can you make a screencast of it?

**Comment by estruyf** [comment]
Windows 10 (anniversary edition)
Visual Studio Code: 1.4.0

![snip_20160808152935](https://cloud.githubusercontent.com/assets/2900833/17481338/efe3cb4e-5d7c-11e6-840a-4188ce1511fc.png)

**Comment by joaomoreno** [comment]
Can you make a video recording of what you see?

**Comment by estruyf** [comment]
Here is an example.
![sample-problem](https://cloud.githubusercontent.com/assets/2900833/17481593/3f977f4a-5d7e-11e6-85d5-f1195be2ce21.gif)

**Comment by joaomoreno** [comment]
If you close Code and open it again, you still see it?

**Comment by tarunzoot** [comment]
sometimes

**Comment by estruyf** [comment]
@joaomoreno already closed it a couple of times and got it with various projects.

**Comment by joaomoreno** [comment]
@estruyf Here's what I'm looking for: a video recording of you opening Code for the first time, going into a file and reproducing it, all together. I'm looking for steps that let me reproduce it, since I'm finding it hard to do.

Btw which version are you on?

**Comment by estruyf** [comment]
Re-install seemed to solve it. Cannot reproduce it anymore. @tarunzoot can you?

**Comment by tarunzoot** [comment]
me too @estruyf

**Comment by joaomoreno** [comment]
Good to know. Do you guys have any extensions installed btw?
