### ISSUE TITLE
Ctrl+Click select word still broken

### ISSUE THREAD

**Issue by petera703** [microsoft/vscode#102309]
Issue Type: <b>Bug</b>

### Steps to reproduce
1. Open any text file in VS Code.
2. While pressing CTRL, click a word in the file.

### Expected results (a la Visual Studio)
- The word is selected.

### Actual results
1. Word not selected.
2. Depending on the word clicked, unwanted navigation then occurs.

### Background
This seems to be a longstanding issue (5yrs+?) and has been raised more than once 
(https://github.com/Microsoft/vscode/issues/189, https://github.com/microsoft/vscode/issues/7827, ...) but is not currently resolved. There appear to have been misunderstandings in the past, as some fix discussions refer to moving the mouse; however, mouse movement is not the main point because Ctrl+click should select the whole word immediately&mdash;exactly the same as double-clicking the word. (Mouse movement _after_ that should snap-select subsequent words, just as it does after the double-click word selection.)

### See also
https://stackoverflow.com/questions/37683703/how-to-disable-ctrl-click-in-vs-code
https://github.com/Microsoft/vscode/issues/189
https://github.com/microsoft/vscode/issues/7827

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-6210 APU with AMD Radeon R3 Graphics     (4 x 1797)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.68GB (2.58GB free)|
|Process Argv|W:\Dev\JS\promises\promises.js|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
git-diff-and-merge-tool|dav|1.0.4
vscode-eslint|dba|2.1.6
xml|Dot|2.5.0
vscode-commands|fab|1.3.0
vscode-commandbar|gsp|0.3.1
shortcut-menu-bar|jer|1.3.0
sublime-babel-vscode|jos|0.2.10
debugger-for-chrome|msj|4.12.9

</details>

**Comment by alexdima** [comment]
Ctrl+click never ever selected a word in VS Code, so there is nothing broken, this is a feature request to be able to bind ctrl+click to word selection. Currently, only double click does word selection.

Let's track in #3130

**Comment by petera703** [comment]
Fiar enough! And thanks for linking #3130&mdash;could you also link it to the ones I linked to pls (#189, #7827) as they are locked to me.
