### ISSUE TITLE
Clingy file on Manjaro linux via Snap

### ISSUE THREAD

**Issue by K4rakara** [microsoft/vscode#102308]
I'm having issues with this one file on Manjaro linux. If I try to save the file, VSCode crashes. If I try to close the file, VSCode crashes. If I try to do anything to get rid of the file, it crashes. It also crashes in other scenarios as well. I've tried running `snap remove code && snap install code`, but the issue persisted. 

- VSCode Version: 1.47.0 (According to `code --version`, it crashes when I try to open the about window)
- OS Version: Manjaro Linux
- Kernel Version: 5.5.19-1-MANJARO

Steps to Reproduce:

1. Create a new file with `CTRL+N` 
2. Paste [this](https://pastebin.com/04whyj64) text into it.
3. Try to close the file
4. VSCode crashes

Does this issue occur when all extensions are disabled?: Yes

If theres any files, logs, etc that I can provide to help fix this, just ask.

**Comment by joaomoreno** [comment]
Can you run with `code --verbose` and see if there's any output when the crash happens?

Can you repro with the non-snap release?

**Comment by K4rakara** [comment]
[code.log](https://github.com/microsoft/vscode/files/4912794/code.log)
Heres the log. Of all things, it appears to be a GTK error.

I'm unable to reproduce the bug with OSS-code from the Manjaro repos.

**Comment by madhavparekh** [comment]
I had same issue with v1.47. Creating symlink helped:

`$ sudo mkdir -p /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/ 
$ sudo ln -s /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache`

**Comment by deepak1556** [comment]
Thanks for the details, lets merge this issue to https://github.com/microsoft/vscode/issues/100940
