### ISSUE TITLE
Return anonymous function: Identifier expected

### ISSUE THREAD

**Issue by dotnetCarpenter** [microsoft/vscode#102399]
As an example: `_.reduce('ugu-ug-ba', reduceUntil(a => a === '-')) // <- "ugu"`

```js
const _ = require('underscore')

/**
 * @param {{ (): boolean; (arg0: any): any; }} predicate
 * @returns {function}
 */
function reduceUntil (predicate) {
	let stop = false
	return
		/**
		 * @param {string} accu
		 * @param {string} x
		 */
		function (accu, x) {
			if (accu.length === 0) stop = false // reset if new accu
			if (predicate(x)) stop = true // stop when true
			if (stop) return accu // return the accumulated
			return accu + x	// append next value to accu
		}
}
```
_You can play with the code here: https://repl.it/repls/ThirstyGruesomeComputing_

For the anonymous function the jsdoc has to be after the `return` statement or vscode/ts will not understand that `accu` and `x` are parameters. But that gives me the ts error, **Identifier expected**.
![Identifier expected](https://user-images.githubusercontent.com/43763/87322974-6a407c80-c52e-11ea-935f-4e838e9c6a66.png)

As mentioned, if I move the jsdoc above the `return` statement, I get: **Parameter `accu` implicitly has an `any` type, but a better type may be inferred from uage. ts(7044)**
![Parameter `accu` implicitly has an `any` type, but a better type may be inferred from uage. ts(7044)](https://user-images.githubusercontent.com/43763/87321232-4419dd00-c52c-11ea-81f4-c8bfe194abe5.png)

The TS JavaScript parser seems to have a bug or vscode does not properly understand the AST from TS...

`vscode`: 1.47.0
`typescript`: 4.0.0-dev.20200712 and 3.9.6

+ [X] Searched for similar issues with `is:open typescript "return function" doc`

**Comment by spahnke** [comment]
There must not be a line terminator after a `return` keyword. See https://www.ecma-international.org/ecma-262/#prod-ReturnStatement

<img width="637" alt="Screen Shot 2020-07-13 at 18 04 12" src="https://user-images.githubusercontent.com/25029871/87326701-5fd4b180-c533-11ea-9696-a48e0562708a.png">

**Comment by IllusionMH** [comment]
Looks like you need to fill request in TS repo to support JSDoc before `return function`. Also see https://github.com/microsoft/TypeScript/issues/31836 for one line workaround but I doubt that it will work here.

In the meantime you can use
```js
/**
 * @param {{(): boolean; (arg0: any): any}} predicate
 * @returns {(accu: string, x: string) => string} reducer
 */
function reduceUntil(predicate) {
    let stop = false
    return function(accu, x) {
        if (accu.length === 0) stop = false // reset if new accu
        if (predicate(x)) stop = true // stop when true
        if (stop) return accu // return the accumulated
        return accu + x	// append next value to accu
    }
}
```
[Playground](https://www.staging-typescript.org/play?useJavaScript=true#code/PQKhCgAIUgBAHAhgJ0QW0gb0wCgJQBckARgPakA2ApogHYDckOKA5gAxF0Cehk3Avv0jxkVACYBLAMaIALlSgxYo2QFdktAM5ZmUqaqKbZyCbRYAaSAA9Dx0yzyQAvAD5IRk2aGixqqVWRFYHAAM1VaKVkJUlpIHz8qAFVaKIocEXFpOSpHTChIAupZd1lSeGdIEMQKTQUCgpV1WLCIqJjdfUsrXPz6+okQpkQ9VQA6ajNZAAtnJydINkcjMoqqmqpIYGA4qlrigchaKgB3PhHevsgD9J8s+RxupdLy+eNVDa2SleOpqli3uqXArXZbwRyNDRnfSbbYQ-6-KGqNCqCjZMQXPpwxGQADU1gAkJ9EPB4H8xIcqFZigA3arvSClREXfjgfhAA)

Or function declaration with JSDoc separated from `return`.

---

As for `Identifier expected.` that because of ASI you'll get `return;` and `function (accu, x) {...` will be function declaration (instead of function expression) that doesn't have name which is required.

/assign @mjbvz

**Comment by dotnetCarpenter** [comment]
@IllusionMH I did not think of moving the type definition to the `@return` section. That fixes my issue. Also thank you for the link to the TypeScript repl (https://www.staging-typescript.org/play). It's perfect!

If I do not have any types defined for the return function, then I get a "Quick Fix..." link that results in:

```js
/**
 * @param {{ (): boolean; (arg0: any): any; }} predicate
 */
function reduceUntil (predicate) {
	let stop = false
	return /**
		* @param {string | any[]} accu
		* @param {any} x
		*/
function (accu, x) {
			if (accu.length === 0) stop = false // reset if new accu
			if (predicate(x)) stop = true // stop when true
			if (stop) return accu // return the accumulated
			return accu + x	// append next value to accu
		}
}
```

As both @spahnke and you have noted. This does not work and breaks the code. I believe it's vscode specific and not TS specific?

**Comment by dotnetCarpenter** [comment]
@mjbvz The issue is still not resolved but I could create a more specific issue with **"JSDoc Quick fix breaks return function"** title. Do you want to re-open or should I create another issue?

**Comment by dotnetCarpenter** [comment]
> Looks like you need to fill request in TS repo to support JSDoc before `return function`. Also see [microsoft/TypeScript#31836](https://github.com/microsoft/TypeScript/issues/31836) for one line workaround but I doubt that it will work here.

Actually, it appears to work fine in both TS 3.9.6 and 4.0.0-dev.

```js
/**
 * @param {{ (): boolean; (arg0: any): any; }} predicate
 */
function reduceUntil (predicate) {
	let stop = false
	return /** @type {(accu: string, x: string) => string} reducer */ function (accu, x) {
		if (accu.length === 0) stop = false // reset if new accu
		if (predicate(x)) stop = true // stop when true
		if (stop) return accu // return the accumulated
		return accu + x	// append next value to accu
	}
}
```

**Comment by IllusionMH** [comment]
@dotnetCarpenter AFAIK all built-in refactors and language support for JS and TS come from TypeScript.
I think it makes sense to fill two issue in TS repo: refactoring that leads to broken behavior and better support for JSDoc before `return`.
