### ISSUE TITLE
"move cell up" breaks layout with webview outputs

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#102313]
- Have a code cell with a webview output, move it up

![image](https://user-images.githubusercontent.com/323878/87257116-ff6b4480-c44c-11ea-8e75-5419cfefc34b.png)

**Comment by rebornix** [comment]
It only happens when moving a code cell with outputs beyond a markdown cell.

**Comment by rebornix** [comment]
cc @connor4312 I made observers a map instead of an array to allow easy dispose.

**Comment by connor4312** [comment]
lgtm
