### ISSUE TITLE
Bash intergrated terminal on linux can't find any path related programs.

### ISSUE THREAD

**Issue by AWrongUsername** [microsoft/vscode#102307]
- VSCode Version: 1.47.0
- OS Version: Pop!_OS 20.04 LTS

Steps to Reproduce:

1. Download VSCode using flatpak and launch.
2. Open a new bash terminal. It won't accept any PATH programs.

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by Tyriar** [comment]
You can view what environment the terminal launches with using [trace logging](https://github.com/microsoft/vscode/wiki/Terminal-Issues), changes are you're running with or without login shell mode (see `terminal.integrated.shellArgs.linux`) that is causing the issue.
