### ISSUE TITLE
Integrated terminal typing issue

### ISSUE THREAD

**Issue by Redirts** [microsoft/vscode#102378]
- VSCode Version: 1.47.0
- OS Version: Microsoft Windows [Version 10.0.17763.1282]

Steps to Reproduce:
1. Open new integrated terminal window. New window will appeared scrolled and trying to type will just scroll window but text does not appear.
2. Maximize terminal window and all is fine.
3. Minimize again and we back to the same issue.

See animated gif
![2020-07-13_12-12-01](https://user-images.githubusercontent.com/23477559/87298575-55e68a80-c502-11ea-9438-36abf17aab93.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
