### ISSUE TITLE
Experimental Decorators don't work in `export` statements

### ISSUE THREAD

**Issue by Domiii** [microsoft/vscode#102386]
VSCode version: v1.46.1

## Problem

The following syntax is valid, according to [@babel/plugin-proposal-decorators](https://babeljs.io/docs/en/babel-plugin-proposal-decorators#decoratorsbeforeexport):

```js
export default
@tag('ecm-explainer')
@template('<div></div>')
class MyComp extends Slim {
}
```

but VSCode is not having it.

However, it does work when splitting `export` statement and `class` expression, i.e. this works fine:

```js
@x
class Y {}

export default Y;
```

NOTE: `compilerOptions.experimentalDecorators` is set to `true` in `jsconfig.json`. Making this different from #28097.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
