### ISSUE TITLE
The test tab is unsable 

### ISSUE THREAD

**Issue by XxprogamerxXgame** [microsoft/vscode#102331]
it is telling me to configure the test framework for python i tried extensions 
pytest,and untest it is teling that the test configuration failed
![image](https://user-images.githubusercontent.com/67744136/87269506-021c7700-c4eb-11ea-90bf-1d0ce9f21288.png)
![image](https://user-images.githubusercontent.com/67744136/87269520-0c3e7580-c4eb-11ea-935f-4b4534511b9e.png)

**Comment by connor4312** [comment]
\extPython
