### ISSUE TITLE
golang extension fails to install

### ISSUE THREAD

**Issue by scottstensland** [microsoft/vscode#102379]
Issue Type: <b>Bug</b>

starting from https://code.visualstudio.com/docs/languages/go

I need to install the golang extension so I goto page

https://marketplace.visualstudio.com/items?itemName=golang.go

which says to hit          

ctrl + p

then I paste in value

ext install golang.Go

then I see error in VS code

Error while loading extensions.
connect ENOENT /run/user/1000/vscode-b9b3c598-1.47.0-shared.sock

I have seen this before and was hoping VS bug got fixed ... not yet

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:30:34.302Z)
OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3583)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|11.59GB (0.43GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by scottstensland** [comment]
as a side bug in VS code when I booked above ticket the create a new bug window dropdown to pick Extension was empty ( since crash happened during attempt to install the golang extension so no extensions where installed yet bug is possibly for Extension not VS )

here is content of dir

```
eve@milan /run/user/1000 $ ls -latr
total 4
dr-x------  2 eve  eve    0 Dec 31  1969 doc
dr-x------  2 eve  eve    0 Jul 12 07:12 gvfs
d---------  3 eve  eve  160 Jul 12 07:12 inaccessible
drwxr-xr-x  4 root root  80 Jul 12 07:12 ..
srw-rw-rw-  1 eve  eve    0 Jul 12 07:12 snapd-session-agent.socket
srw-rw-rw-  1 eve  eve    0 Jul 12 07:12 pk-debconf-socket
drwx------  2 eve  eve  140 Jul 12 07:12 gnupg
srw-rw-rw-  1 eve  eve    0 Jul 12 07:12 bus
drwx------  3 eve  eve   60 Jul 12 07:12 dbus-1
drwx------  2 eve  eve   80 Jul 12 07:12 pulse
drwx--x--x  2 eve  eve   60 Jul 12 07:12 gdm
prw-rw-r--  1 eve  eve    0 Jul 12 07:13 gnome-session-leader-fifo
-rw-------  1 eve  eve  314 Jul 12 07:13 ICEauthority
drwx------  3 eve  eve   60 Jul 12 07:13 gnome-shell
drwxr-xr-x  4 eve  eve  120 Jul 12 07:13 systemd
-rw-------  1 eve  eve    0 Jul 12 07:14 update-notifier.pid
drwx------  2 eve  eve  120 Jul 12 07:14 keyring
drwx------  3 eve  eve   60 Jul 12 20:19 snap.gimp
srwxrwxr-x  1 eve  eve    0 Jul 13 07:30 vscode-2d11d12b-1.47.0-main.sock
srwxrwxr-x  1 eve  eve    0 Jul 13 07:30 vscode-git-75fa479cc7.sock
srwxrwxr-x  1 eve  eve    0 Jul 13 07:30 vscode-2d11d12b-1.47.0-shared.sock
drwx------ 14 eve  eve  460 Jul 13 07:30 .
drwx------  2 eve  eve   60 Jul 13 07:31 dconf

```


here is how I just installed VS code

sudo dpkg -i code_1.47.0-1594283939_amd64.deb

**Comment by joaomoreno** [comment]
Is the issue fixed if you restart your machine?

**Comment by scottstensland** [comment]
no,  issue is not fixed after a reboot ... infact I get same bug when installing Vscode on a different Ubuntu 20.04 laptop which has never had Code installed until now

the issue may be caused because I have to set both

GOPATH      /my/path
GOROOT    /some/path

so I defined those in your json file

```

cat ~/config/Code/User/settings.json 
{
    "go.gopath": "/cryptdata6/var/log/tmp/shared/gopath",
    "go.goroot": "/cryptdata6/var/log/tmp/shared/go",
    "go.formatTool": "goimports"
}

```

on a fresh reboot my dir looked like

```

ava@kiev /run/user/1000 $ ls -latr
total 4
dr-x------  2 ava  ava    0 Dec 31  1969 doc
dr-x------  2 ava  ava    0 Jul 16 06:25 gvfs
drwxr-xr-x  4 root root  80 Jul 16 06:25 ..
d---------  3 ava  ava  160 Jul 16 06:25 inaccessible
srw-rw-rw-  1 ava  ava    0 Jul 16 06:25 bus
srw-rw-rw-  1 ava  ava    0 Jul 16 06:25 snapd-session-agent.socket
srw-rw-rw-  1 ava  ava    0 Jul 16 06:25 pk-debconf-socket
drwx------  2 ava  ava  140 Jul 16 06:25 gnupg
drwx------  3 ava  ava   60 Jul 16 06:25 dbus-1
drwx------  2 ava  ava   60 Jul 16 06:25 dconf
drwx------  2 ava  ava   80 Jul 16 06:25 pulse
drwx--x--x  2 ava  ava   60 Jul 16 06:25 gdm
prw-rw-r--  1 ava  ava    0 Jul 16 06:25 gnome-session-leader-fifo
-rw-------  1 ava  ava  310 Jul 16 06:25 ICEauthority
drwx------  2 ava  ava  100 Jul 16 06:25 keyring
drwx------  3 ava  ava   60 Jul 16 06:25 gnome-shell
-rw-rw-r--  1 ava  ava    0 Jul 16 06:25 gnome-shell-disable-extensions
drwx------ 13 ava  ava  380 Jul 16 06:25 .
drwxr-xr-x  4 ava  ava  120 Jul 16 06:25 systemd

```

then I launched Code and got same error message 

by the way it would help if you made the error message copyable  in Code ... so instead of copying it I will resort to taking a screenshot of that error shown here


![Screenshot from 2020-07-16 06-33-01](https://user-images.githubusercontent.com/60258/87661240-48154d00-c72e-11ea-8de9-75d8e1f2417b.png)


at this point when error is shown here is that same dir as shown above


```

ava@kiev /run/user/1000 $ ls -latr
total 4
dr-x------  2 ava  ava    0 Dec 31  1969 doc
dr-x------  2 ava  ava    0 Jul 16 06:25 gvfs
drwxr-xr-x  4 root root  80 Jul 16 06:25 ..
d---------  3 ava  ava  160 Jul 16 06:25 inaccessible
srw-rw-rw-  1 ava  ava    0 Jul 16 06:25 bus
srw-rw-rw-  1 ava  ava    0 Jul 16 06:25 snapd-session-agent.socket
srw-rw-rw-  1 ava  ava    0 Jul 16 06:25 pk-debconf-socket
drwx------  2 ava  ava  140 Jul 16 06:25 gnupg
drwx------  3 ava  ava   60 Jul 16 06:25 dbus-1
drwx------  2 ava  ava   80 Jul 16 06:25 pulse
drwx--x--x  2 ava  ava   60 Jul 16 06:25 gdm
prw-rw-r--  1 ava  ava    0 Jul 16 06:25 gnome-session-leader-fifo
-rw-------  1 ava  ava  310 Jul 16 06:25 ICEauthority
drwx------  2 ava  ava  100 Jul 16 06:25 keyring
drwx------  3 ava  ava   60 Jul 16 06:25 gnome-shell
drwxr-xr-x  4 ava  ava  120 Jul 16 06:25 systemd
srwxrwxr-x  1 ava  ava    0 Jul 16 06:25 vscode-a80c6e9f-1.47.1-main.sock
srwxrwxr-x  1 ava  ava    0 Jul 16 06:25 vscode-git-20f68bfdd5.sock
srwxrwxr-x  1 ava  ava    0 Jul 16 06:25 vscode-a80c6e9f-1.47.1-shared.sock
-rw-------  1 ava  ava    0 Jul 16 06:26 update-notifier.pid
drwx------ 13 ava  ava  440 Jul 16 06:26 .
drwx------  2 ava  ava   60 Jul 16 06:33 dconf

```

and no I do not have another Code running ...  this bug is happening from the one install and one launch of Code

Please advise

**Comment by joaomoreno** [comment]
How did you install VS Code?

**Comment by joaomoreno** [comment]
Can you reproduce if you point Code to a new user data dir? `code --user-data-dir NEWFOLDER`

**Comment by scottstensland** [comment]
Excellent ... finally it runs and allows me to install the golang extension without a crash !!!!!!!!!

**Comment by joaomoreno** [comment]
The default location is `~/config/Code`, but be careful deleting it since your settings are in there.
