### ISSUE TITLE
Unable to connect to extension store. All previous extensions failed to load

### ISSUE THREAD

**Issue by lb091188** [microsoft/vscode#102328]
版本: 1.47.0 (user setup)
提交: d5e9aa0227e057a60c82568bf31c04730dc15dcd
日期: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. After the upgrade to 1.47.0
2. All previous extensions failed to load
3. Unable to connect to extension store
4. The color theme cannot be set
5. Unable to set icon theme

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/102082
