### ISSUE TITLE
 Cannot read property 'column' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#102344]
Issue Id: <b>5ef8005d-2f0e-147b-4511-4c5a6058112e</b><br /><br />*Versions* <br />- 1.47.0<br />-  59c7cbcf15745e4a8adb4fc59b63aa93f14d3cc3<br />-  376d9d9d785ccca128fdbb16f001446d0ad64d32<br />*Stack* <br />TypeError: Cannot read property 'column' of undefined<br />[/vs/editor/contrib/suggest/suggestModel.ts#463:69](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/editor/contrib/suggest/suggestModel.ts#L463:69)<br />

**Comment by jrieken** [comment]
Did occur again
