### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'iconUrl' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#102347]
Issue Id: <b>c847bc94-a725-68e5-25d0-6be70f66d882</b><br /><br />*Versions* <br />- 1.47.0<br />-  376d9d9d785ccca128fdbb16f001446d0ad64d32<br />-  e95f9e63380a139cb1cbe54bacfc6703b96e30b9<br />*Stack* <br />TypeError: Cannot read property 'iconUrl' of undefined<br />[/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts#323:44 (renderElement)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts#L323:44 (renderElement))<br />[/vs/base/browser/ui/list/listWidget.ts#1009:12 (renderElement)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/browser/ui/list/listWidget.ts#L1009:12 (renderElement))<br />[/vs/base/browser/ui/list/listView.ts#730:12 (insertItemInDOM)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/browser/ui/list/listView.ts#L730:12 (insertItemInDOM))<br />[/vs/base/browser/ui/list/listView.ts#496:9 (_splice)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/browser/ui/list/listView.ts#L496:9 (_splice))<br />[/vs/base/browser/ui/list/listView.ts#425:15 (splice)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/browser/ui/list/listView.ts#L425:15 (splice))<br />[/vs/base/browser/ui/list/splice.ts#17:34](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/browser/ui/list/splice.ts#L17:34)<br />    at Array.forEach (<anonymous>)<br />[/vs/base/browser/ui/list/splice.ts#17:19 (splice)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/browser/ui/list/splice.ts#L17:19 (splice))<br />[/vs/base/browser/ui/list/listWidget.ts#1307:56 (fn)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/browser/ui/list/listWidget.ts#L1307:56 (fn))<br />[/vs/base/common/event.ts#819:12 (bufferEvents)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/common/event.ts#L819:12 (bufferEvents))<br />[/vs/base/browser/ui/list/listWidget.ts#1307:21 (splice)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/browser/ui/list/listWidget.ts#L1307:21 (splice))<br />[/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts#170:14 (_updateExtensions)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts#L170:14 (_updateExtensions))<br />[/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts#155:68](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts#L155:68)<br />    at g.doRun (out/vs/workbench/workbench.deskto<br />

**Comment by alexdima** [comment]
@sandy081 the code path that throws came in via https://github.com/microsoft/vscode/commit/7d436d8a85e974d271e98c5df073c689b85be7bd . It looks that `marketplaceInfo` can be `null` or `undefined`.

**Comment by sandy081** [comment]
It looks that marketplaceInfo can be `null` or `undefined`. Unfortunately not reflected in the code

https://github.com/microsoft/vscode/blob/7b5d3adb33325b59a751975b5402837406ed31e3/src/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts#L97-L97

Fixed it by making sure marketplaceInfo is loaded always.
