### ISSUE TITLE
windows overflow screen on maximum

### ISSUE THREAD

**Issue by pizixie** [microsoft/vscode#102354]
Issue Type: <b>Bug</b>

vscode window overflow 2nd screen on click maximum button

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
Sounds like we had issues reported on that topic before already on Windows.

**Comment by pizixie** [comment]
yes, i found another issue like this.
#85592
