### ISSUE TITLE
Views: Reset view puts it in the wrong place

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#102396]
From @grantborthwick:

> I've now gotten it into a state where when I reset its location, it goes next to the Problems area at the bottom!
> 
> Steps (some of the screenshots reused - that's why the branch changes in the middle):
> 1. Open the terminal
> 
> 2. Drag the source control icon to the terminal and split it with the terminal
> ![image](https://user-images.githubusercontent.com/2301725/87238134-698bd700-c3c4-11ea-8516-28ee37970bf4.png)
> 3. Drag it up to make it a new area at the bottom instead of splitting it with the terminal
> ![image](https://user-images.githubusercontent.com/2301725/87238530-0781a080-c3c9-11ea-88fd-7057ae66c391.png)
> 
> 4. Drag source control back to the sidebar
> ![image](https://user-images.githubusercontent.com/2301725/87238137-74466c00-c3c4-11ea-8d5f-af87d23275aa.png)
> 
> 5. Right click the "new" source control icon and select Reset Location
> ![image](https://user-images.githubusercontent.com/2301725/87238535-1f592480-c3c9-11ea-9cc4-f6784468bca7.png)
> 
> 
> Expected: It fixes the icon and puts it in the right place
> Actual: It moves it back to the bottom!
> ![image](https://user-images.githubusercontent.com/2301725/87238540-3435b800-c3c9-11ea-97f6-4e4eeeead9c8.png)
> 
> Resetting it again here moves it to the correct place. I also can repro this with the search panel except without the icon change.

**Comment by sbatten** [comment]
what happens here is logically correct, but not intuitive. making this case intuitive would be quite convoluted. there are a too many cases and fixing this will likely break other cases. what is more noticeable in this case is that a "reset" is desired because of the icon issue. that has since been fixed so I think we can close this one.
