### ISSUE TITLE
Cannot open Windows Terminal settings as default JSON file viewer

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/vscode#102395]
- VSCode Version: 1.47.0
- OS Version: 1903

Steps to Reproduce:

1. Install [Windows Terminal](https://github.com/microsoft/terminal)
2. Set VS Code as your default `.json` file viewer
3. Open Terminal
4. Press <kbd>Ctrl</kbd>+<kbd>,</kbd> to open settings

At this point, Terminal will make the Windows error bloop sound and show this error popup for a fraction of a second _(I could only get a screenshot using a still from screen recording)_:

![Screenshot of a Visual Studio Code popup with black content instead of text](https://user-images.githubusercontent.com/3335181/87228611-61a24780-c370-11ea-84f5-490c6cfcbb12.png)

Switching the default `.json` file viewer to Notepad++ allows settings to open fine.

Does this issue occur when all extensions are disabled?: Yes

Moving issue over from https://github.com/microsoft/terminal/issues/6848.

**Comment by bpasero** [comment]
I doubt this is an issue with VSCode, can you try to run `code <file path of JSON file>` to see if that works? That is the command that should get invoked to open a file via Code.

**Comment by JoshuaKGoldberg** [comment]
Huh, I just tried this again and it works now. 🤷 ... Guess it was a one-time thing. Thanks for the response anyway!

For reference, in https://github.com/microsoft/terminal/issues/6848#issuecomment-657597809 I was pointed to post here.
