### ISSUE TITLE
CTRL+SFT+ALt+Arrow down is not working in Linux

### ISSUE THREAD

**Issue by pragyawebvillee** [microsoft/vscode#102385]
Issue Type: <b>Bug</b>

To copy the line down , this keyboard shortcut is not my working

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:30:34.302Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2558)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.49GB (1.23GB free)|
|Process Argv|--extensions-dir=/home/wv/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github|Kni|0.30.3

(1 theme extensions excluded)

</details>

**Comment by SaumitraVerma** [comment]
Does right clicking and selecting copying work???

**Comment by pragyawebvillee** [comment]
> Does right clicking and selecting copying work???

Yes, it's working.

**Comment by alexdima** [comment]
@pragyawebvillee It is possible that your desktop environment is "eating up" this keybinding. What does VS Code detect when you press the desired key combination? 

![keyboard-input](https://user-images.githubusercontent.com/5047891/80482640-da3e5e00-8954-11ea-9583-0f652b0595a8.gif)
