### ISSUE TITLE
I can't bundle using Webpack -> Can't resolve require('vscode')

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#102314]
- VSCode Version: 1.47
- OS Version: Windows 10

Steps to Reproduce:
1 - Follow these steps to bundle the extension with Webpack https://code.visualstudio.com/api/working-with-extensions/bundling-extension
2 - Every `require('vscode')` can't be resolved.

![image](https://user-images.githubusercontent.com/55927613/87257598-9696c300-c472-11ea-96e5-129ac0bed07f.png)

**Comment by gjsjohnmurray** [comment]
@AllanOricil you need this in your webpack.config.js file:

```
    externals: {
        'vscode': 'commonjs vscode' // the vscode-module is created on-the-fly and must be excluded. Add other modules that cannot be webpack'ed, 📖 -> https://webpack.js.org/configuration/externals/
    },
```

**Comment by AllanOricil** [comment]
> @AllanOricil you need this in your webpack.config.js file:
> 
> ```
>     externals: {
>         'vscode': 'commonjs vscode' // the vscode-module is created on-the-fly and must be excluded. Add other modules that cannot be webpack'ed, 📖 -> https://webpack.js.org/configuration/externals/
>     },
> ```

I think I had it, because I copied the webpack.config.js from the documentation. But let's try again. Thanks man.

**Comment by AllanOricil** [comment]
@mjbvz  could you reopen. I did exactly as it says in the doc and the externals part of webpack is not working.

**Comment by AllanOricil** [comment]
Sorry, I made a mistake :/ 
It was complaining about another lib.
Thanks guys!
