### ISSUE TITLE
Implement multi-select in left-panel file tree

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#1023]
It would be good to be able to move/copy/delete/etc. multiple files in the tree view at once using combinations such as:

**Mouse**
- <kbd>shift</kbd>+`left click`:  Select all items from the currently focused item to the clicked item
- <kbd>ctrl</kbd>+`left click`: Add the clicked item to the selection

**Keyboard**
- <kbd>shift</kbd>+<kbd>&uarr;</kbd>: Add the item above the focused item to the selection (or reduce the selection)
- <kbd>shift</kbd>+<kbd>&darr;</kbd>: Add the item below the focused item to the selection (or reduce the selection)
- <kbd>ctrl</kbd>+<kbd>&uarr;</kbd>: Move the focus up without selecting the item
- <kbd>ctrl</kbd>+<kbd>&darr;</kbd>: Move the focus down without selecting the item
- <kbd>ctrl</kbd>+<kbd>space</kbd>: Add/remove the focused item from the selection

**Comment by yangmillstheory** [comment]
+1 - was just trying to delete multiple files.

**Comment by massimocode** [comment]
Hey I just wanted to do a +1 on this one, this would be a really useful addition!

**Comment by vishal123** [comment]
+1

**Comment by TheColorRed** [comment]
+1

I don't like having to right click and and doing "Reveal in Explorer" (If that is the correct label and doesn't exist on Linux) and then doing what I want there.

**Comment by ianwesterfield** [comment]
:+1:

**Comment by Nimzozo** [comment]
:+1: +1

**Comment by jayrosen1576** [comment]
this is important especially when needing to restructure an app by moving multiple files into other folder locations or deleting many files at once. we tend to do this often when in the early stages of web app development.

**Comment by SylvainEstevez** [comment]
+1

**Comment by jaguarus83** [comment]
+1

**Comment by kazemihabib** [comment]
+1

**Comment by Hacklone** [comment]
:+1:

**Comment by Tyriar** [comment]
Hi all, prefer :+1: reactions on the original issue comment as that helps us with prioritization.

**Comment by AlexanderMattoni** [comment]
:+1:

**Comment by Tyriar** [comment]
I updated the issue with more detail and additional desired keybindings.

**Comment by William-Francis** [comment]
👍

**Comment by jeff881208** [comment]
We need this feature

**Comment by hajar424** [comment]
+1

**Comment by jlin21** [comment]
👍

**Comment by massimocode** [comment]
(thumbsup)

**Comment by invkrh** [comment]
+1

**Comment by pedromvu** [comment]
👍

**Comment by aminmeyghani** [comment]
👍

**Comment by ena1106** [comment]
+1

**Comment by Tyriar** [comment]
Hi all, prefer :+1: reactions on the original issue comment as that helps us with prioritization. If you're on a mobile device you can use reactions by first hitting the "Desktop version" button at the bottom of the page.

**Comment by jveljan** [comment]
+1

**Comment by ctsstc** [comment]
I would love to see this : )
It seems very counter intuitive since most all file explorers have ctrl+click for multi selecting as well as shift clicking for selecting a range of files between file A and file B

**Comment by jsenjoy** [comment]
👍  It's important, and I need. Mutil-select will make vscode be more convenient for developers.

**Comment by FloMaetschke** [comment]
+1 Still needed. Since 1 year now...

**Comment by gitawego** [comment]
+1

**Comment by yuriykuzin** [comment]
+1

I was surprised that is doesn't work.

**Comment by Tyriar** [comment]
I just noticed `ctrl+left click` currently opens the file in the next editor group, we would need to introduce a setting and/or override that.

**Comment by dfroze** [comment]
Don't forget "open selected files" :D

**Comment by Tyriar** [comment]
Mostly just waiting for someone to pick it up, it's high on my personal want list so I might pick it up once I'm freed up.

**Comment by izikorgad** [comment]
+1

**Comment by zhiqiang21** [comment]
i need this feature

**Comment by mtapiero** [comment]
+1

**Comment by Hitmasu** [comment]
+1

**Comment by ozzyknox** [comment]
+1

**Comment by deniswelsing** [comment]
+1

**Comment by PabloMessina** [comment]
+1

**Comment by Tyriar** [comment]
Please prefer :+1: reactions on the original issue comment as that helps us with prioritization and doesn't send notifications to everyone listening to the issue for updates.

**Comment by thekalinga** [comment]
`ctrl+left click` should toggle the selection rather than just select

**Comment by y0n1** [comment]
👍

**Comment by y0n1** [comment]
👍

**Comment by aprilandjan** [comment]
+1

**Comment by adeacetis** [comment]
@Tyriar did this feature made it onto product roadmap ?

**Comment by smccarthy** [comment]
+1

**Comment by kevjames3** [comment]
+1

**Comment by tylerjbainbridge** [comment]
+ 1

**Comment by yay** [comment]
This is especially annoying since you have watch the confirmation dialog animation (on a Mac at least) every freaking time you delete files one by one.

It would be great if there was no animation, even better, just don't show the confirmation dialog and remove to trash, which has a convenient "Put back" option in case one mistakenly deleted something.

**Comment by scarstens** [comment]
+1 when is this coming? need this too.

**Comment by karmoxie** [comment]
+1 please :)

**Comment by alexcushing** [comment]
+1

**Comment by sliechti** [comment]
+1

**Comment by 2pha** [comment]
+1

**Comment by ognjenb** [comment]
+1

**Comment by irvansetiawan** [comment]
+1

**Comment by tsjamm** [comment]
+1

**Comment by matzero** [comment]
+1

**Comment by andreykaipov** [comment]
+1 x10000000

**Comment by raregrass** [comment]
+1 this is important feature for me, please.

**Comment by maxwellhibbert** [comment]
+1 Need this!

**Comment by Naruto-Sasuke** [comment]
Not support now?? terribel

**Comment by hotwer** [comment]
Is it that hard to implement? Just black mask the file that's selected (like while you have not files opened) and then start working with multiple files selection, is that a really big problem?

**Comment by zigang93** [comment]
hell yeah.. why still not add this feature yet?  so hard?

**Comment by yanxiaobo** [comment]
+1

**Comment by stoneChen** [comment]
+1

**Comment by clocksmith** [comment]
+1000

**Comment by cuongnv201194** [comment]
+1

**Comment by Tyriar** [comment]
Please prefer :+1: reactions on the original issue comment as that helps us with prioritization and doesn't send notifications to everyone listening to the issue for updates.

As an update: it's not that this is particularly hard, it just takes some time to do right and the team is all busy doing other stuff. This is near the top of the list of issues sorted by 👍 reactions now though which probably means it will be picked up in the coming months.

**Comment by wuliupo** [comment]
+10086

**Comment by TomBethoule** [comment]
+1

**Comment by liujiede** [comment]
👍

**Comment by simongs** [comment]
+1

**Comment by Globolobo** [comment]
+1

**Comment by taylorsmithgg** [comment]
+1

**Comment by cwtuan** [comment]
+1

**Comment by beniamin-kis** [comment]
This issue is 1.5 year old, really, Microsoft, y u no listen? 
(╯°□°)╯︵ ┻━┻

**Comment by gucoelho** [comment]
+1

**Comment by slowaways** [comment]
Not yet implemented? This should be a priority.

**Comment by fixedmachine** [comment]
This is an obvious one. Still not delivered? Wooow!

**Comment by biskazz** [comment]
WOW. +1. Really handy feature. Should be implemented. 👍  :)

**Comment by hattoriheiji** [comment]
+1

**Comment by landonp1203** [comment]
+1 👍

**Comment by eesteban** [comment]
+1

**Comment by coderas** [comment]
+1

**Comment by coderas** [comment]
It's really pretty irritating ;) but massive 👍 for vscode in general, just works

**Comment by JakubPetriska** [comment]
+1

**Comment by james-bungag** [comment]
+1

**Comment by mr-rahimi** [comment]
+1

**Comment by nshermione** [comment]
+1

**Comment by MatrixV01** [comment]
+1

**Comment by rapidclock** [comment]
+1. This feature is required before VSCode can be really considered as a serious IDE.

**Comment by tomplusplus** [comment]
+1 - Seriously this is not a thing!!!! - I love VS CODE until now....

**Comment by JaumeJBofi** [comment]
Pretty Please?

**Comment by astrikov-d** [comment]
+1

**Comment by ThiagoAugustoBorges** [comment]
+1

**Comment by nvuhung** [comment]
+1

**Comment by GeorgeKaraszi** [comment]
I feel this is a no-brainier feature. +1000

**Comment by KamyarGhajar** [comment]
+1

**Comment by trinath** [comment]
+1
I strongly believe that this feature should be there in any IDE.

**Comment by nischal62019** [comment]
+1
This is a must have!, this is standard in almost all IDEs.

**Comment by silkyland** [comment]
+1 
Please add this feature in to vscode

**Comment by iktw** [comment]
+1

**Comment by vanhumbeecka** [comment]
+ 1

**Comment by guilhermedecampo** [comment]
+1

**Comment by phifa** [comment]
can we get an estimate from the team when this well be added or if this is planned?

**Comment by Tyriar** [comment]
It's not planned right now. I'd love to have it, we just need people to free up.

The best way to influence us working on this is by hitting :+1: on the top comment.

**Comment by csutorasr** [comment]
+1

**Comment by icepoint0** [comment]
is it possible now ?

**Comment by kassyn** [comment]
+1

**Comment by ToMakeSense** [comment]
totally agree on you. I found what you said is very necessary for me in daily work. You spoke it out, great!

**Comment by xueyunquan** [comment]
Oh, my... I can't believe this...

**Comment by andrius-k** [comment]
+1

**Comment by drnachio** [comment]
+1

**Comment by blackberry4311** [comment]
+1, I really need this feature

**Comment by thomas-kahn** [comment]
+1

**Comment by sdolua** [comment]
+1

**Comment by danpora** [comment]
+1

**Comment by jas99** [comment]
+1

**Comment by knezdusan** [comment]
+1

**Comment by Philip-Sultanescu** [comment]
+1

**Comment by winiciuscota** [comment]
+1

**Comment by ibox4real** [comment]
+1

**Comment by flpelluz** [comment]
+1

**Comment by sn1k** [comment]
+1

**Comment by guilhermedecampo** [comment]
there is an estimation for this feature?

**Comment by iarroyo** [comment]
+1

**Comment by SenchiloVictor** [comment]
So... still have no solution??? What the hell guys??

**Comment by Sti2nd** [comment]
Yeah, it is weird that this simple feature doesn't exist

**Comment by Loilo** [comment]
@Sti2nd Such a simple feature, go on implement it and create a pull request, goodness. 🙄

**Comment by Sti2nd** [comment]
Indeed. I guess I meant it is a small but important feature, don't know about the difficulty in implementing it.

**Comment by Loilo** [comment]
Thanks for clarification. Well, it's certainly not technically trivial, especially if you need support for keyboard controls.

I've just made the mistake to subscribe to this issue to be aware of any progress but I mostly get notifications about people spamming "+1" or complaining that such an "easy feature" is not done yet...

**Comment by Sti2nd** [comment]
Yeaaah. I don't know what to say to that except https://help.github.com/articles/unsubscribing-from-conversations/

**Comment by FrimJo** [comment]
+1

**Comment by foxundermoon** [comment]
+10086

**Comment by tprupsys** [comment]
+1

**Comment by jdazacon** [comment]
+1

**Comment by czy0729** [comment]
+1s

**Comment by gulshan** [comment]
Selecting two items should show the "compare" option in the context menu.

**Comment by stammatime** [comment]
+1

**Comment by TAGC** [comment]
+1

**Comment by skunchamwar** [comment]
+1

**Comment by SSkovboiSS** [comment]
+1

**Comment by screendriver** [comment]
Why do everyone vote with a `+1`? Please please please stop it! GitHub has a feature called [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) since **March 2016**. Please use that instead of flooding with unnecessary `+1`'s. With every `+1` everyone of the 128 subscribers gets a useless notification 🙄

**Comment by sn1k** [comment]
You are right @screendriver, +1

**Comment by Martin-Wegner** [comment]
As far as I know feature requests are sort by `thumbs up reactions`:
https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

So the `+1` posts will not help anyone. The only thing you can really do is a `thumbs up reaction` for the first post. Just saying...

**Comment by screendriver** [comment]
> Plus you (or the maintainer) can sort GitHub issues accordingly the reactions and can see which issue is most important. He can't do that with +1s.

As I said 😉

**Comment by iroes** [comment]
> So the +1 posts will not help anyone. The only thing you can really do is a thumbs up reaction for the first post. Just saying... 

Already did. +1 is for rebellion! XD

**Comment by SenchiloVictor** [comment]
So... Is it so really unfixable bag??????  WHAT THE HELL GUYS???

**Comment by SenchiloVictor** [comment]
I have idea - if you do this like "feature" and will sell it for 1$ )) I'm sure everyone will buy it!!

**Comment by Efimster** [comment]
what a shame

**Comment by hyyan** [comment]
+1

**Comment by ezp127** [comment]
It must be just an Easter egg or something. We must discover how to activate this hidden feature.

**Comment by burnaz** [comment]
+1

**Comment by hoangnamitc** [comment]
+1

**Comment by jcyrss** [comment]
+1

**Comment by younth** [comment]
+1

**Comment by tafelglotzer** [comment]
Still waiting for this important feature :(

**Comment by maheeka** [comment]
Is this feature still not supported?

**Comment by jasonsun0310** [comment]
+1. I don't understand why it is still not implemented..

**Comment by margusha** [comment]
just got pissed off by this missing feature, again. Only thing that makes me frustrated about the VS Code :)

**Comment by binshu2013** [comment]
Multiple files selection feature doesn't work on my Mac!!! help please. Is this a bug?

**Comment by Martin-Wegner** [comment]
@binshu2013 this feature can't work on Mac because this issue is a feature request and the feature is not implemented yet ;)

**Comment by binshu2013** [comment]
Martin,

Thank you for your reply. Any idea when this feature will be implemented?

In my opinion, multi files selection is a must-have feature.

-Bin

**Comment by Argun** [comment]
+19260817 +1s

**Comment by jrdbnntt** [comment]
+1

**Comment by cyanid** [comment]
+1

**Comment by wehrstedt** [comment]
+1

**Comment by kkorus** [comment]
+1

**Comment by mustafarian** [comment]
-1

Maybe we should try minuses instead.

**Comment by wehrstedt** [comment]
🙈 

Or a monkey

**Comment by charismafight** [comment]
+1

**Comment by FistMeNaruto** [comment]
The intent is to provide developers with a sense of pride and accomplishment for managing files one by one.

**Comment by Stranger** [comment]
+1

I'm shocked this has not been added yet

**Comment by Artmobile** [comment]
It's been two years! Congrats to the team🥇  Your persistence to core values (whatever they are) is admirable :)

**Comment by serioth** [comment]
Any update here? Most of VS Code is designed with the goal of increasing user efficiency and development speed. The lack of a multi-select feature slows down the workflow and seems contradictory to the overall ambition of the editor.

I am crossing my fingers for an imminent update which includes that feature.

Otherwise, the editor is great.

PS: The docs around launch configurations and tasks are slightly messy and they could use some clean-up work. I spent two days trying to understand how to debug transpiled ES6 code. It is possible that I am a bit slow, but it should not be that hard to understand.

Thanks again for a great editor.

**Comment by Tyriar** [comment]
@serioth the only update is that it's planned in the 6 month roadmap https://github.com/Microsoft/vscode/wiki/Roadmap

**Comment by dogopupper** [comment]
such a long fuss about a simple thing!!!! come on!!!!!! implement it now!!!!!! geez

**Comment by mgss** [comment]
s this feature still not supported?

**Comment by mgss** [comment]
why？？？

**Comment by brgrz** [comment]
wtf this is incredible...

**Comment by iozozturk** [comment]
Really? This is the first thing you implement in an editor, to make it an editor.

**Comment by viewstar000** [comment]
+1

**Comment by wangfengming** [comment]
It's Dec 23 2017 now. 750 days passed.

**Comment by yurymann** [comment]
I just started using vscode yesterday and today found myself looking for a way to select multiple files to copy them to a different sub-folder.

**Comment by sergeome** [comment]
As far as I can say from the previous example, this comment will be downvoted.

However, the same story. The first day, first 10 minutes after WebStorm. Started to look for this feature. Found this thread...

**Comment by bardware** [comment]
> As far as I can say from the previous example, this comment will be downvoted.

Everyone who contributed to this issue is being informed that another comment was added. Noone needs `+1` posts.
Did you upvote the issue?

**Comment by sergeome** [comment]
Yes.
> Added +1 to the main issue description.

Thanks!

**Comment by Tasdid** [comment]
zzzzz

**Comment by wadejensen** [comment]
+1

**Comment by brett-shenk** [comment]
Just spent 10 mins trying to figure out how to select multiple files to upload... then I found out I can't. It would be really useful to do this as well as such a time saver. 

Say you had to upload / delete 20 files? I wouldn't wanna select them 1 by 1. Not very productive or efficient.

**Comment by dogopupper** [comment]
eyyyyyy  🎉 🎉 🎉

**Comment by gregsdennis** [comment]
Okay.... we have a merged PR.  Anyone know how to do it?

**Comment by bpasero** [comment]
This feature will be available in todays insider release. You can give our preview releases a try from: https://code.visualstudio.com/insiders/
