### ISSUE TITLE
Have mnemonic as command model property

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#102361]
Today, commands that use a mnemonic require a special menu registration, e.g. this https://github.com/microsoft/vscode/blob/783970456be0c7634348e01ee61b2abb9a6ef3b1/src/vs/editor/contrib/smartSelect/smartSelect.ts#L173 defines a special title because mnemonic are used for the global menu. This has obvious drawback, like duplication and adding mnemonics to another menu, like the context menu, would be a bigger effort. Instead, mnemonics should be a "model property" like category, icons etc and the menu should know what model property to use when rendering a command.

**Comment by jrieken** [comment]
@sbatten I can add the property but I don't know where global menus are constructed to pickup the mnemonic-info

**Comment by sbatten** [comment]
What do you mean about duplication? The menu widget supports mnemonics in that format, its just a flag whether or not they are displayed for the most part.

**Comment by jrieken** [comment]
It's about the registration. Look at this: https://github.com/microsoft/vscode/blob/d17550f4a8249baab72afe551f67c4c997bd2315/src/vs/workbench/contrib/scm/browser/scm.contribution.ts#L176-L183

There is a command registered but for the mnemonic support another menu registration is needed, now if mnemonics should be used in yet another menu, yet another registration is needed. The mnemonic isn't a property of the command but of the menu registration and we should stop doing that.

**Comment by gjsjohnmurray** [comment]
@jrieken if mnemonic gets defined on the command could there still be cases where a menu item that surfaces the command wants to specify a title with a different mnemonic in an effort to make the mnemonic unique across that menu?

**Comment by jrieken** [comment]
I think that's a question of how mnemonics are modelled and how menus interpret them. Today it uses a funny syntax that's mixed into the title and has legacy in how native/electron menus implement mnemonics. We could chose something different which doesn't require the author to know all other mnemonics in the menu.

**Comment by isidorn** [comment]
It would be great to have this, as I also have a use case for this from debug.
@sbatten are there any plans here?

**Comment by jrieken** [comment]
fyi I have pushed https://github.com/microsoft/vscode/commit/79d6bf6ca829311c7a7982af2ca1933530a7d108 which allows a command/action to provide a label with a mnemonic. E.g like so `title: { value: localize('title.start', "Start Extension Bisect"), original: 'Start Extension Bisect',  mnemonicedTitle: '&&Some Thing'},` Tho, what I still don't know is where/which menu is using mnemonics. It also doesn't solve the unsolved problem with conflicts. 

ping @sbatten - can you update your menus to pick up the mnemonic title instead of the "normal" title

**Comment by isidorn** [comment]
@jrieken awesome, thanks a lot!

**Comment by sbatten** [comment]
@jrieken yea I can adopt, am I to understand that if mnemonics are disabled, we should pick the normal value, otherwise, pick up the mnemonicedTitle? or do I always take the mnemonic if present? what is the expectation of the action/command author?

**Comment by jrieken** [comment]
> what is the expectation of the action/command author?

Command authors shouldn't know/care. Check out the sample below. There is the `ToggleBreakpointsAction` which encapsulates everything that's needed to present it: label, keybindings, menu bindings (actually not show) etc. Now, to get mnemonics rendered it needs separate, additional menu registration. For once this is some unplease "information spreading" but it also means the mnemonics are exclusive to that menu. Instead menus should be free to decide what piece of information they use from the (single) action definition. E.g. the command palette uses "<category>: <label>" and <alias> iff running non-english. Toolbars don't use the category-label but icons. Menus should follow this and use the mnemonic label iff possible and enabled.

<img width="899" alt="Screenshot 2021-01-07 at 17 13 01" src="https://user-images.githubusercontent.com/1794099/103915722-da117780-510b-11eb-9414-0ac91a8c9341.png">


So, in essence the change should be simple: just prefer the `mnemonicedTitle` when avialable, otherwise do whatever is done today.

**Comment by sbatten** [comment]
@jrieken doesn't the mnemonic'd title need to be localized as well?

**Comment by sbatten** [comment]
@jrieken pushed the above commit to switch to a separate property since I believe the mnemonic title needs to be localized as well

**Comment by jrieken** [comment]
> I believe the mnemonic title needs to be localized as well

`ILocalizedString` doesn't mean that a string needs to be localized, it means that a string has been localized and it offers a way to get to its non-localized version. The command palette needs that because when running non-english it shows both variants - that's done for the easy for finding/filtering. I don't think that menus support that feature and do think I have misunderstood `ILocalizedString` so I have reverted your change

**Comment by isidorn** [comment]
Thanks for doing this, I was able to get rid of some duplication via 00a781f926e

**Comment by jrieken** [comment]
Adding `verified` based on @isidorn's last comment
