### ISSUE TITLE
 Cannot read property 'uuid' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#102338]
Issue Id: <b>6d76e6db-892e-c741-fd2a-dda2600c3d63</b><br /><br />*Versions* <br />- 1.47.0<br />*Stack* <br />TypeError: Cannot read property 'uuid' of undefined<br />[/vs/platform/extensionManagement/common/extensionManagementUtil.ts#11:7 (areSameExtensions)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/platform/extensionManagement/common/extensionManagementUtil.ts#L11:7 (areSameExtensions))<br />[/vs/platform/extensionManagement/common/extensionManagementUtil.ts#50:23](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/platform/extensionManagement/common/extensionManagementUtil.ts#L50:23)<br />    at Array.some (<anonymous>)<br />[/vs/platform/extensionManagement/common/extensionManagementUtil.ts#50:13 (findGroup)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/platform/extensionManagement/common/extensionManagementUtil.ts#L50:13 (findGroup))<br />[/vs/platform/extensionManagement/common/extensionManagementUtil.ts#57:16 (groupByExtension)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/platform/extensionManagement/common/extensionManagementUtil.ts#L57:16 (groupByExtension))<br />[/vs/workbench/services/extensionManagement/common/webExtensionsScannerService.ts#122:42 (userExtensions)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/services/extensionManagement/common/webExtensionsScannerService.ts#L122:42 (userExtensions))<br />[/vs/workbench/services/extensionManagement/common/webExtensionsScannerService.ts#80:9](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/services/extensionManagement/common/webExtensionsScannerService.ts#L80:9)<br />    at async Promise.all (index 1)<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#356:9 (_checkEnabledAndProposedAPI)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L356:9 (_checkEnabledAndProposedAPI))<br />[/vs/workbench/services/extensions/electron-browser/extensionService.ts#484:29](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/services/extensions/electron-browser/extensionService.ts#L484:29)<br />[/vs/workbench/services/extensions/common/abstractExtensionService.ts#111:64](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L111:64)<br />

**Comment by sandy081** [comment]
/duplicate

#102082
