### ISSUE TITLE
Source Control not visible after some time

### ISSUE THREAD

**Issue by hunter86bg** [microsoft/vscode#102384]
- VSCode Version: 1.47.0 (user setup)
- OS Version: Windows 10 1809 (OS Build 17763.1282)

Steps to Reproduce:

1.Save files from a gitea repository
2.Open the SCM tab to commit changes

Does this issue occur when all extensions are disabled?: Yes/No
Yes
![VSC_CODE_empty_SCM_tab](https://user-images.githubusercontent.com/22281444/87306588-e92eb880-c520-11ea-9507-4175d3ab5800.jpg)

**Comment by joaomoreno** [comment]
Can you reproduce this issue reliably? What steps do you perform in order to reproduce it?

**Comment by rohmanhm** [comment]
![image](https://user-images.githubusercontent.com/7524911/87320351-09786a80-c555-11ea-8f5b-3155d1635037.png)

I'm getting this issue too.
Please fix.

**Comment by joaomoreno** [comment]
@hunter86bg Can you show me the output of `Developer: Toggle Developer Tools`, the `Console` tab?
