### ISSUE TITLE
Cannot close editor window using Command + W -> see screenshot of error attached

### ISSUE THREAD

**Issue by lensvelt** [Microsoft/vscode#10230]
- VSCode Version: 1.4
- OS Version: El Capitan

Steps to Reproduce:

1. Command + W
<img width="1009" alt="screen shot 2016-08-05 at 23 59 29" src="https://cloud.githubusercontent.com/assets/11645095/17455317/b003f4ce-5b68-11e6-82df-939cbdeaa7cc.png">

.

**Comment by bpasero** [comment]
Some commands changed their ids, see https://github.com/Microsoft/vscode/issues/6605
