### ISSUE TITLE
using debugger is launching a "constructor.js" file automatically

### ISSUE THREAD

**Issue by TwiceBorn7** [microsoft/vscode#102322]
Issue Type: <b>Bug</b>

Hi,

As soon as I run the debugger on a .js file and it hits a line item that has a console.log, a "constructor.js" file is opened with a ton of code I don't recognize. My original .js file remains open. If I switch back to my file and click the "step into" button on the debugger, it goes back to this "constructor.js" fie. The debugger will not move past the console.log without opening this file. And the debugger will not move past the console.log line item.

I have uninstalled and reinstalled the previous VSCode version and this problem goes away. But VSCode keeps reinstalling the update. The update breaks my debugger with the launch of this "constructor.js" file.

I can't get out of this loop and I can't use my debugger.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (25.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.10.21
vscode-eslint|dba|2.1.6
code-runner|for|0.11.0
vscode-auto-open-markdown-preview|hnw|0.0.4
vsliveshare|ms-|1.0.2427
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
markdown-preview-enhanced|shd|0.5.12

</details>

**Comment by connor4312** [comment]
Thanks for the issue!

If this is an open source project, I think seeing your code/setup would be very useful to help get to the root cause.

Otherwise, collecting a debug log using these instructions would be helpful:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

/needsMoreInfo

**Comment by Mamikalata** [comment]
I'm experiencing the same issue. If someone finds a solution please post it. Ty <3

**Comment by connor4312** [comment]
@Mamikalata please collect a trace file using the instructions posted above. Thanks!

**Comment by Mamikalata** [comment]
@connor4312 Yeah, I already did it. Should I send you the file or just the text?

**Comment by connor4312** [comment]
Sending the file is good. It should be gzipped already for you.

**Comment by Mamikalata** [comment]
[vscode-debugadapter-7.json.gz](https://github.com/microsoft/vscode/files/4920259/vscode-debugadapter-7.json.gz)

**Comment by connor4312** [comment]
Thanks for the log. From the path it looks like you're working on a class assignment -- would you mind sharing the code with me so I can repro and verify the problem locally? You can email it to me at connor@xbox.com if you don't want to share it publicly.

**Comment by Mamikalata** [comment]
I don't mind sharing it 
https://pastebin.com/v1RjVgSf

**Comment by connor4312** [comment]
From the logs and code it looked like you just kept stepping in until you hit constructor.js. This is a different issue than it sounds like what @TwiceBorn7 had, and I already fixed that this morning in https://github.com/microsoft/vscode-js-debug/issues/603 🙂

**Comment by Mamikalata** [comment]
HI @connor4312 , I am thanking you for the advice, but it does not work for me. I am pretty sure I have the same issue as TwiceBorn7. I always go to constructor.js file when I hit line 27.  Ty in advance

**Comment by connor4312** [comment]
hm, I'm still a little confused. From the logs I see that the "paused" event where you land in constructor.js, it's immediately preceded by a `stepIn`

![](https://memes.peet.io/img/20-07-506c355f-8475-4a5d-b7aa-eeab8e5f13be.png)

Would you mind taking a recording of what you're seeing? You can use https://gifcap.dev/ to record your screen to a gif.

**Comment by Mamikalata** [comment]
You are right, I think I gave you the wrong file. But I also think I fixed it just by using Continue (F5) and placing breakpoints on every console.log()

**Comment by connor4312** [comment]
We've not heard back from the original author, thus closing the issue
