### ISSUE TITLE
Update/Install Extension fails with 'mkdir', permission issue in Linux?

### ISSUE THREAD

**Issue by saravanabalagi** [microsoft/vscode#102383]
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:30:34.302Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-109-generic snap, Ubuntu 18.04.4 LTS

Steps to Reproduce:

1. Fresh install from apt/snap/microsoft website .deb
2. Update an existing extension or install a new one
3. Error pops up!

Does this issue occur when all extensions are disabled?: No

Error:
```
Error: ENOENT: no such file or directory, mkdir
log.ts:197   ERR ENOENT: no such file or directory, mkdir: extracting: ENOENT: no such file or directory, mkdir
    at file:///snap/code/36/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:548:199
    at async _.extractUserExtension (file:///snap/code/36/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:546:241)
    at async U.extractAndInstall (file:///snap/code/36/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:562:358)
```

Manual install doesn't help either :(

Screenshot:

![image](https://user-images.githubusercontent.com/8567893/87304675-16716b80-c50d-11ea-9846-45af06296563.png)

**Comment by saravanabalagi** [comment]
Just checked `~/.vscode`  directory permissions and it belonged to `root`. This should be owned by the user and can be quickly fixed by `sudo chown -R $USER:$USER ~/.vscode`. But I expect this to work out of the box without hacks.

Previously reported in #91671

**Comment by sandy081** [comment]
This happened because you installed VS Code first as root and now you are using it as a user who do not have permissions.
