### ISSUE TITLE
Take dependents into consideration when using context.extensionMode

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#102323]
In v1.47.0, a new API `ExtensionMode` is introduced. (#95926)

After playing with it, I found that it only works for the extension currently being debugged.

For example, I have two extension `A` and `B`, which `B` depends on `A`. When I debug `B`, It would be helpful if `A` could also be running in `Development` mode.

**Comment by connor4312** [comment]
Thanks for the suggestion, however this opens a sizable box of complexity and there hasn't been other asks or 👍s for this, thus closing it as part of [issue grooming](https://github.com/microsoft/vscode/wiki/Issue-Grooming).
