### ISSUE TITLE
[cshtml] Code formatting doesn't work in *.cshtml files

### ISSUE THREAD

**Issue by slishnevsky** [Microsoft/vscode#10236]
- VSCode Version: 1.4.1
- OS Version: Windows 10

Steps to Reproduce:
Press Shift+Alt+F, 

Result: Should reformat entire page, but nothing happens.
Works for html, but not for cshtml

**Comment by aeschli** [comment]
the built-in razor support doesn't contain a code formatter.

**Comment by MiKom** [comment]
I'll just add, that this is tracked in OmniSharp issue: https://github.com/OmniSharp/omnisharp-roslyn/issues/981
