### ISSUE TITLE
envFile support in launch.json not working with input variable reference

### ISSUE THREAD

**Issue by PaulGrimshaw** [microsoft/vscode#102374]
When I add `envFile` support to the launch.json, all works as expected.  However, the environment variables are not available for use in variables.  E.g.

```
    {
            "name": "Deploy",
            "program": "${workspaceFolder}/dist/index.js",
            "request": "launch",
            "envFile": "${workspaceFolder}/.env",
            "sourceMaps": true,
            "console": "integratedTerminal",
            "args": [
                "deploy",
                "${env:MODULE}",
                "-v",
                "${env:VERSION}"
            ],
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "node"
        }
```
This looks like an ordering issue, the args are evaluated prior to the env file being loaded, as the command is always run with empty parameters.  Once the program runs, all the variables are available.

We are using this to debug common command line runs, and would rather not hard code all the variations into the file.  I'm aware of the "inputs" which works quite well, however due to running this 100s of times as we debug, we don't want to re-enter the arguments in the prompt continuously.  Any other suggestions welcome, however in my view it would be much more intuitive if the envFile was loaded prior to evaluating the variables.

**Comment by weinand** [comment]
Yes, "envFile" is a feature of the node debugger whereas `${}` variables are substituted before the node debugger runs.

**Comment by PaulGrimshaw** [comment]
No problem, thanks for the explanation.  Didn't realise the envFile was a node-debugger feature.
