### ISSUE TITLE
 Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#102343]
Issue Id: <b>b33cb556-8398-a092-0e47-b8fcd0e7fb8a</b><br /><br />*Versions* <br />- 1.47.0<br />*Stack* <br />TypeError: Cannot read property 'call' of undefined<br />[/vs/base/common/event.ts#589:18 (fire)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/common/event.ts#L589:18 (fire))<br />[/vs/workbench/api/common/extHostTextEditors.ts#131:40 (apply)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/api/common/extHostTextEditors.ts#L131:40 (apply))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#402:16 (_doInvokeHandler)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L402:16 (_doInvokeHandler))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#387:31 (_invokeHandler)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L387:31 (_invokeHandler))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#303:18 (_receiveRequest)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L303:18 (_receiveRequest))<br />[/vs/workbench/services/extensions/common/rpcProtocol.ts#230:9 (call)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L230:9 (call))<br />	at \out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:34<br />[/vs/base/common/event.ts#587:15 (fire)](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/common/event.ts#L587:15 (fire))<br />[/vs/base/parts/ipc/common/ipc.net.ts#453:18](https://github.com/microsoft/vscode/blob/d5e9aa0227e057a60c82568bf31c04730dc15dcd/src/vs/base/parts/ipc/common/ipc.net.ts#L453:18)<br />	at \out\vs\workbench\services\extensions\node\extensionHostProcess.js:975:744<br />	at l.fire (\out\vs\workb<br />

**Comment by jrieken** [comment]
This is a bogous extension listener. We should find a way to ignore these errors

**Comment by jrieken** [comment]
closing without action
