### ISSUE TITLE
Please, split 'references' and 'run test' options in code editor

### ISSUE THREAD

**Issue by r105m** [Microsoft/vscode#10238]
Hi, i think, single option 
    **"editor.referenceInfos": true**
for 'references', 'run test' and 'debug test' is not useful.

What if i need to run test from the vscode, but i very don't like 'references'? 

Please, split these options to something like 
    **"editor.referenceInfos": true**
    **"editor.debuggingCommands": true**

Thank you.

**Comment by jrieken** [comment]
Wow - that's an blast from the past. Historically we only had backed in reference info and that we have generalised code lens which is contributed from extensions that setting doesn't make sense anymore...

**Comment by jrieken** [comment]
I have added a new setting `codeLens` that is better name for what it does - the old value is discouraged but still respected. The information that is shown in code lens depends on the the extensions you install. By default VS Code ships with no code lens provider

**Comment by r105m** [comment]
Thank you
