### ISSUE TITLE
problem with cursor

### ISSUE THREAD

**Issue by samarthvaru** [microsoft/vscode#102305]
![2020-07-12](https://user-images.githubusercontent.com/63781024/87252450-c359d300-c490-11ea-9eb2-5e45e806270d.png)
Issue Type: <b>Bug</b>

Whenever i start a tag enter is being pressed automatically. Cannot even use html

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
gitignore|cod|0.6.0
vscode-html-css|ecm|0.2.3
terminal|for|0.0.10
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-babel|mgm|0.0.29
csharp|ms-|1.22.1
python|ms-|2020.6.91350
vscode-react-native|msj|0.16.1
sqltools|mtx|0.22.10
jinja|who|0.0.8

</details>

**Comment by mjbvz** [comment]
This is almost certainly being caused by an extension, likely vscode-language-babel
