### ISSUE TITLE
Cannot tab between windows using Command + ] -> see screenshot of error attached

### ISSUE THREAD

**Issue by lensvelt** [Microsoft/vscode#10231]
- VSCode Version: 1.4
- OS Version: El Capitan
<img width="1007" alt="screen shot 2016-08-06 at 00 04 36" src="https://cloud.githubusercontent.com/assets/11645095/17455351/742b2a20-5b69-11e6-83e8-a543c1065da3.png">

Steps to Reproduce:

1. 
2.

**Comment by bpasero** [comment]
See https://github.com/Microsoft/vscode/issues/6605
