### ISSUE TITLE
Group different file types in sidebar

### ISSUE THREAD

**Issue by pramitbiswas** [microsoft/vscode#102333]
Ability to group same file types in the sidebar (similar to windows explorer), if the number of files in that group more than one?

**Comment by ArturoDent** [comment]
Look at `Explorer: Sort Order` `type` option.  Is that what you are looking for?

**Comment by pramitbiswas** [comment]
It appears I have no option `Explorer: Sort Order`. I have only `Open Editors`, `Outline`, `Folders` and `timeline` options under `Explorer`.

**Comment by ArturoDent** [comment]
That is a setting.
