### ISSUE TITLE
command code-run.runner

### ISSUE THREAD

**Issue by shyamkrishna-1** [microsoft/vscode#102301]
Issue Type: <b>Feature Request</b>

i am getting an issues like 'command' code-run.runner can u please fix this issue man i am tied of to fix this 

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.20161

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?

**Comment by shyamkrishna-1** [comment]
see at the corner of the photo please

**Comment by joaomoreno** [comment]
Please come to Github and upload the screenshot, since e-mail attachments don't work.

**Comment by shyamkrishna-1** [comment]
![Screenshot (49)](https://user-images.githubusercontent.com/63534214/87289144-e54b6800-c519-11ea-8e0c-9aa7d35a7a38.png)

**Comment by shyamkrishna-1** [comment]
this is the one i am getting

**Comment by shyamkrishna-1** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/63534214/87289333-23488c00-c51a-11ea-8662-3a1f7f63534d.png)

**Comment by shyamkrishna-1** [comment]
once see this please help me with this

**Comment by shyamkrishna-1** [comment]
i uploaded the screen shot can u check that out in github

**Comment by joaomoreno** [comment]
Please file an issue to the Code Runner extension: https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner
