### ISSUE TITLE
"Format on save" doesn't trigger with "save on focus change" on Ctrl-Shift-B default build task

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/vscode#102304]
- VSCode Version: 1.47.0
- OS Version: Win10

Steps to Reproduce:

1. settings.json:
```json
"editor.formatOnSave": true,
"files.autoSave": "onFocusChange",
```
With this, if I launch the built-in terminal with a hotkey, file will be saved and `formatOnSave` will trigger.

2. tasks.json (partial):
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "build",
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "detail": "tsc"
    }
  ]
}

```
3. Press Ctrl-Shit-B, then the terminal launches with the default building process, meanwhile the editor loses focus, and the file is saved, but `formatOnSave` doesn't trigger.

Does this issue occur when all extensions are disabled?: 
Not entirely sure, because the `Prettier` extension is also disabled.

**Comment by alexr00** [comment]
It is intentional that format on save actions don't occur when you run a task. This is because the save that happens when you run a build task is an auto save. Format on save actions should only apply when the save action comes directly from the user.
