### ISSUE TITLE
Disable snippets in attributes

### ISSUE THREAD

**Issue by technbuzz** [Microsoft/vscode#10233]
- VSCode Version: 1.4.0
- OS Version: Windows 10 Pro

I have created an HTML snippet but I don't want to see the suggestion when i am writing value for particular attribute. My snippet is triggered with **keyword btn** and while defining class in following snippet I get the same snippet suggestion.
`<input class="btn">`

**Comment by jrieken** [comment]
That's the effect of showing snippets inside the suggest box. Use the `editor.snippetSuggestion=top|inline|bottom|none` setting to control where this goes. Also note that we have dedicated action to only show/insert snippets
