### ISSUE TITLE
Formatting on Save hangs indefinitely

### ISSUE THREAD

**Issue by mustela** [microsoft/vscode#102367]
VSCode Version:
- Version: 1.47.0
- Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
- Date: 2020-07-09T08:01:54.115Z
- Electron: 7.3.2
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.5.0

Steps to Reproduce:
I'm having exactly the same issue as https://github.com/microsoft/vscode/issues/92652, but I can't find the existing issue, so creating a new one to get some visibility.

**Comment by jrieken** [comment]
Disable format-on-save or uninstall the extension that contributed the formatter

**Comment by mustela** [comment]
I did that but, of course, I loose the functionality... So just trying to understand if this is a vscode issue or an extension one.

**Comment by jrieken** [comment]
Clearly an extension issue. The extensions doesn't finish the formatting operation, instead of silently dropping it we show the progress dialog that allows you to (1) cancel that one operation and/or (2) disable format on save for the future (for that language).

**Comment by jrieken** [comment]
Do: F1 > Show Running Extensions to see if an extension has been reported as slow/blocking. It must not always be the formatter extension as other extensions can block the (shared) extension process
