### ISSUE TITLE
Saving files and code action Organize Imports is extremly slow

### ISSUE THREAD

**Issue by philipp985** [microsoft/vscode#102373]
Issue Type: <b>Performance Issue</b>

As far as I remember I have not changed anything in my configuration. It might be related to the latest visual studio 1.47?
Disabeling all extions did not change anything.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (3.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    80	 19772	code main
    1	   232	  4072	   window (● externalIdForm.tsx - PBD.Core.Web.Qm - Visual Studio Code)
    0	    12	 13768	     watcherService 
    0	    11	 19572	       console-window-host (Windows internal process)
    0	   145	 20544	     searchService
    0	   217	 21140	     extensionHost
    0	    72	  9744	       "C:\Users\phili\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\phili\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=21140
    0	    98	 11528	       electron_node server.js 
    0	   157	 15056	       electron_node tsserver.js 
    0	   157	 16428	       electron_node eslintServer.js 
    8	  1538	 17580	       electron_node tsserver.js 
    0	    87	 15120	         electron_node typingsInstaller.js typesMap.js 
    0	    73	 19240	       electron_node server.js 
    0	    41	 11560	   utility
    0	    52	 11564	   electron-crash-reporter
    1	   178	 12192	   gpu-process
    0	    89	 17536	   window (Issue Reporter)
    3	    90	 20748	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● externalIdForm.tsx - PBD.Core.Web.Qm - Visual Studio Code)
|    Folder (PBD.Core.Web.Qm): 12264 files
|      File types: map(3876) cs(1128) tsx(1095) js(1090) ts(763) dll(570)
|                  cshtml(416) css(142) scss(94) PNG(94)
|      Conf files: package.json(20) launch.json(1) settings.json(1) gulp.js(1)
|                  csproj(1) tsconfig.json(1)
|      Launch Configs: chrome;
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.6
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
azure-pipelines|ms-|1.170.0
vscode-azurestorage|ms-|0.9.0
azure-account|ms-|0.8.11
vscode-typescript-next|ms-|4.0.20200712
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.9
angular-console|nrw|12.0.0
vscode-gitignore-generator|pio|1.0.2
csharp2ts|raf|0.0.24
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.9
vscode-import-cost|wix|2.12.0

</details>

**Comment by mjbvz** [comment]
Which type of file are you saving?

**Comment by philipp985** [comment]
I am saving mainly typescript files tsx and ts files. But it took really long for all kind of files. Including my packag.json for example. Actually after a few hours and a couple of restarts of vs code it works again without any problems. So this can be closed now. I have no idea what went wrong or what I did. Bu thank you very much for your reply!

**Comment by aleclarson** [comment]
I'm experiencing a similar slow down of saving TypeScript files that are processed by Prettier. It started happening just recently, after VS Code upgraded itself one day.

**Comment by kennethlynne** [comment]
Same here
