### ISSUE TITLE
An ampersand '&' is added on drag & drop from Explorer Pane to Terminal

### ISSUE THREAD

**Issue by lorenzznerol** [microsoft/vscode#102486]
This following is a full copy of https://github.com/microsoft/vscode/issues/98170 which was closed, although not solved.

An ampersand is added when dragging and dropping on the terminal a folder with a space in its name.

![image](https://user-images.githubusercontent.com/52793248/87423384-7f72e500-c5da-11ea-8c46-b4441a23e1d1.png)

Version: 1.46.0-insider (user setup)
Commit: da3bf75
Date: 2020-05-19T10:07:59.927Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by Tyriar** [comment]
This is by design as the & is required to run the file, some context: https://github.com/microsoft/vscode/pull/65994
