### ISSUE TITLE
Web smoke test: cell action execution

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#102460]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=81723&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=1fbbf8a8-a0a4-519f-def5-b5fd8ca21811&l=93

```
 1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Notebooks
           cell action execution:
     Error: Timeout: get text content '.notebook-editor .monaco-list-row.focused .monaco-editor .view-lines' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)

```

**Comment by rebornix** [comment]
@roblourens do you think I'm waiting for the right thing here? I tried to trigger an action from the UI and the the action will modify the content of the cell through workspace edits, and lastly wait for the content to be applied in the editor.

**Comment by roblourens** [comment]
The test looks fine to me. Have you ever reproed this issue?

**Comment by rebornix** [comment]
Didn't see this issue locally and in today's production build. Let's see if it reproduces again.

**Comment by rebornix** [comment]
The commit was not related.

**Comment by roblourens** [comment]
Can't repro it now, have worked on smoketests recently and don't remember it failing.
