### ISSUE TITLE
Integrated Terminal - Default open/close shortcut not responding when Japanese IME is active

### ISSUE THREAD

**Issue by brianblakely** [Microsoft/vscode#10243]
- VSCode Version: 1.4.0
- OS Version: Microsoft Windows [Version 10.0.14393]

Steps to Reproduce:
1. Switch to Japanese Microsoft IME
2. Press `Ctrl+``

Nothing happens.

**Comment by Tyriar** [comment]
This is an issue with the Japanese Microsoft IME if it's still happening.
