### ISSUE TITLE
CTRL + V Pastes Twice

### ISSUE THREAD

**Issue by mthilen** [microsoft/vscode#102405]
Issue Type: <b>Bug</b>

Issue began today. VS Code pastes the same thing 2x when using ctrl + v, not present in other programs. 

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (18.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
nbpreviewer|jit|1.2.2
python|ms-|2020.6.91350
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0

</details>

**Comment by joco0093** [comment]
Also experiencing this same issue, but have only experienced this in the configuration settings so far (for editing C/C++ configurations). I tried copying and pasting a section of code in the editor and did not experience that issue there.

**Comment by mthilen** [comment]
> Also experiencing this same issue, but have only experienced this in the configuration settings so far (for editing C/C++ configurations). I tried copying and pasting a section of code in the editor and did not experience that issue there.

Interesting, for me the issue was editing a .ipynb notebook
