### ISSUE TITLE
upper and lower vowel in Thai Language is missing

### ISSUE THREAD

**Issue by nati4193** [microsoft/vscode#102483]
My code ::

x = "มีหมู"
print(x)
print(len(x))

Result:

>>> x = "มหม"
>>> print(x)
มหม
>>> print(len(x))
3
>>>

Following my language, it should be 5 charactors in this case.

**Comment by roblourens** [comment]
It sounds like this might be an issue with the Python language itself. I suggest searching around to see how Python handles calculations for these types of combined characters.

**Comment by nati4193** [comment]
I also try it in Pycharm and Google Colab and Python able to read those vowel charactor. I think it might have some bug in VS Code.

![Annotation 2020-07-15 173925](https://user-images.githubusercontent.com/52024510/87535756-31d1a780-c6c2-11ea-9345-8570a3e21d20.png)
