### ISSUE TITLE
Cannot run extension's unit tests on Windows Server 2016: 'getmac.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by bryceitoc9** [microsoft/vscode#102428]
- VSCode Version: 1.47.0
- OS Version: Windows Server 2016 (v 1607), via AWS CodeBuild image `aws/codebuild/windows-base:1.0`

Steps to Reproduce:

1. Run [our extension's](https://github.com/aws/aws-toolkit-vscode) tests on AWS CodeBuild using the following [buildspec file for Windows unit tests](https://github.com/aws/aws-toolkit-vscode/blob/master/buildspec/windowsTests.yml).
2. Execution will fail with the following error:
```
Running Main test suite...
About to set up test instance of VS Code, version stable...
Downloading VS Code 1.47.0 from https://update.code.visualstudio.com/1.47.0/win32-archive/stable
Downloaded VS Code 1.47.0 into .vscode-test/vscode-1.47.0
VS Code test instance location: C:\codebuild\tmp\output\src375675591\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-1.47.0\Code.exe
Starting tests: C:\codebuild\tmp\output\src375675591\src\github.com\aws\aws-toolkit-vscode\dist\src\test\index.js


Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

[main 2020-07-13T16:51:40.607Z] [uncaught exception in main]: Unable to retrieve mac address (Error: Command failed: getmac.exe
'getmac.exe' is not recognized as an internal or external command,

operable program or batch file.

)

[main 2020-07-13T16:51:40.671Z] update#setState idle

[main 2020-07-13T16:52:10.671Z] update#setState checking for updates

[main 2020-07-13T16:52:10.698Z] update#setState idle
```
  a. Of note, this does not occur on v 1.46.0. Our toolkit also does not use `getmac.exe`

Does this issue occur when all extensions are disabled?: Yes (aside from our extension)

**Comment by sbatten** [comment]
@bryceitoc9 We have always used getmac.exe on Windows to retrieve the mac address. I am not sure why this is suddenly failing. For one, I would expect Windows Server 2016 to have the binary and secondly we should be catching this error.

@bpasero I'm not sure what would have made a difference here. Is this somehow related to the sandbox flag being passed?

**Comment by bryceitoc9** [comment]
Hmm, looked into it and it looks like that issue's also thrown when forcing 1.46.0, however, this one starts execution correctly (the following log is from the PR above):
```
Running Main test suite...
About to set up test instance of VS Code, version 1.46.0...
Downloading VS Code 1.46.0 from https://update.code.visualstudio.com/1.46.0/win32-archive/stable
Downloaded VS Code 1.46.0 into .vscode-test/vscode-1.46.0
VS Code test instance location: C:\codebuild\tmp\output\src098465951\src\github.com\aws\aws-toolkit-vscode\.vscode-test\vscode-1.46.0\Code.exe
Starting tests: C:\codebuild\tmp\output\src098465951\src\github.com\aws\aws-toolkit-vscode\dist\src\test\index.js


Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

[main 2020-07-14T15:22:27.283Z] [uncaught exception in main]: Unable to retrieve mac address (Error: Command failed: getmac.exe
'getmac.exe' is not recognized as an internal or external command,

operable program or batch file.

)

[main 2020-07-14T15:22:27.514Z] update#setState idle



  AwsExplorer

    √ displays region nodes with user-friendly region names

    √ refreshes when the Region Provider is updated
```

**Comment by sbatten** [comment]
it seems that the getmac error is not the blocking issue then?

**Comment by bryceitoc9** [comment]
Apparently not, although something is breaking with the move to 1.47.0 (our integration tests are also breaking although I think that's a change with the JS debugger that we're not handling; that's a separate investigation).

Is there anything that we can do to help troubleshoot this?

**Comment by bpasero** [comment]
Do these tests run in `1.47` when executed from within VSCode itself?

I am not seeing any issues in the output, the sandbox option should only be used on Linux but is also not harmful on other OS.

**Comment by bryceitoc9** [comment]
It runs on Windows locally, yes. As far as I can tell this is exclusive to 1.47.0 and up on Windows Server 2016. Is the failure related to the setState lines?
```
[main 2020-07-13T16:51:40.671Z] update#setState idle

[main 2020-07-13T16:52:10.671Z] update#setState checking for updates

[main 2020-07-13T16:52:10.698Z] update#setState idle
```

**Comment by justinmk3** [comment]
The `getmac.exe` failure is a red herring.  Since this issue was reported our CI was fixed by (1) later updates to vscode and (2) changes to our own code.

Incidentally, as a workaround, the `getmac.exe` error can be avoided by installing the python `getmac` package: https://github.com/aws/aws-toolkit-vscode/commit/c0bdf1f5c1223ae92cb35c60a29940f71ec91de5

**Comment by sbatten** [comment]
we have since removed this dependency on the getmac.exe executable.
