### ISSUE TITLE
TSX component's props completionItems missing in 1.47.0

### ISSUE THREAD

**Issue by fyangstudio** [microsoft/vscode#102463]
- VSCode Version: 1.47.0
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. tsx file's component prop interface completionItems missing when use it.

![image](https://user-images.githubusercontent.com/9896768/87393048-24dc8780-c5e0-11ea-90f7-b8ef9c903ae1.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Please provide a complete code example (as text). Where is `Form` defined for example?

**Comment by fyangstudio** [comment]
```tsx
// test.tsx
import * as React from 'react';
import { Button } from '@alifd/next';
// Button interface： https://github.com/alibaba-fusion/next/blob/master/types/button/index.d.ts

const Guide = () => {
  // No completionItems, 1.46 is fine
  return (
    <Button |>
      Hello TS
    </Button>
  );
};

export default Guide;
```
package.json:
```
  "dependencies": {
    "@alifd/next": "^1.19.4",
    "react": "^16.4.1",
    "react-dom": "^16.4.1"
}
```
 look forward to your reply, thx.

**Comment by fyangstudio** [comment]
VS Code 1.47.2 looks fine， thx
