### ISSUE TITLE
Calling method member in discord.py module returns error when not supposed to 

### ISSUE THREAD

**Issue by Zzz9194** [microsoft/vscode#102488]
- VSCode Version: 1.46.1
- OS Version: macOS Catalina Version 10.15.3 (19D76) (x64)

Steps to Reproduce:

1. Install python extension and `discord.py`
2. Create a `.py` file of any kind

3 Copy and paste the code below into the python file you just created

```py
import discord
from discord.ext import tasks, commands

class LoopTasks(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.my_random_task.start()

    @tasks.loop(minutes=20.0)
    async def my_random_task():
        print("Doing stuff...")
```

4. Save the file
5. You should get an error at lines 7 & 8 of the code above

According to the documentation [here]() and the actual code of the `discord` module. The error shouldn't exist as `.start()` is a valid member of the `tasks.loop` method.

Documentation: [Here](https://discordpy.readthedocs.io/en/latest/ext/tasks/index.html)
Repository: [Here](https://github.com/Rapptz/discord.py/)

I had some doubt that it was actually a problem with the editor but for some reason no matter where else I try the issue only comes up in VSC. Let me know if you've found something wrong in my code. (I tested it in multiple instances and the same error popped up)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Since this requires the python extension to reproduce, it is likely caused by the python extension.
