### ISSUE TITLE
Annoying notification from the internal git extension keeps popping up

### ISSUE THREAD

**Issue by brezanac** [microsoft/vscode#102455]
Issue Type: <b>Bug</b>

The integrated Git extension, that comes bundled with Visual Studio Code, currently displays a notification about a newer Git version every time VSCode is started.

This means that there is no way to disable the notification, at least not that I know of.

The problem lies in the fact that Git for Windows 2.27 and newer come with a number of very annoying bugs which force people to stay with version 2.26.2.

Bottom line is - I would like not to be forced to see these notifications every single time VSCode is started. Is there any way to disable them?

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

![vscode](https://user-images.githubusercontent.com/389770/87373621-50348780-c58a-11ea-841c-72ab4d9622a1.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|11.3.1
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
vscode-eslint|dba|2.1.6
gitlens|eam|10.2.2
eml|lei|0.4.0
rainbow-csv|mec|1.7.0
git-graph|mhu|1.24.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.3.1
remote-wsl|ms-|0.44.4
vetur|oct|0.24.0
material-icon-theme|PKi|4.2.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
material-theme|zhu|3.8.3

</details>

**Comment by joaomoreno** [comment]
What specific issues with 2.27 are you referring to?

The fact is that 2.25 and 2.26 are _really_ broken with VS Code, so it is important that we tell users to update.

We can add an option to never ask again, sure.

**Comment by brezanac** [comment]
> What specific issues with 2.27 are you referring to?

There are several serious issues with Git for Windows 2.7, one of them even reported by me [here](https://github.com/git-for-windows/git/issues/2743) regarding problems with PEM based private keys (old format) and weird behavior by the bundled `ssh` client. 

Because of that I can't use anything newer than Git for Windows 2.6.2. until I have a definitive proof that one of the newer stable versions resolves the issue (for now version 2.8 RC does not either).

The notification just adds salt to the wound and the confusing part is that even though it's marked as enabled globally (I guess that means it can't be disabled) there is not an option to supress the notification.

**Comment by joaomoreno** [comment]
I believe you mean 2.27, 2.26 and 2.28 RC.

Yeah, we'll add a suppress option.

**Comment by brezanac** [comment]
> I believe you mean 2.27, 2.26 and 2.28 RC.
> 
> Yeah, we'll add a suppress option.

Yeah, sorry, my bad. I meant 2.27 and up. I corrected all the references.

Thank you.

**Comment by aolszowka** [comment]
FWIW Git 2.27 breaks the git svn bridge (Fixed in the latest prerelease), I got "taken" by the VS Code Update Dialog as well.

**Comment by lptr** [comment]
What are the things that are broken with 2.26? It would be great if the notification linked to some more information. I couldn't find anything about serious problems fixed in Git 2.27 about Windows or VSCode in the Git release notes.

It seems that 2.27 is not a good option either. Is a downgrade possible? If so, it would be useful if the message hinted at a good version number.

**Comment by lptr** [comment]
This comment suggests 2.25 could be a good option: https://github.com/microsoft/vscode/issues/98967#issuecomment-646147576

**Comment by JasonGore** [comment]
We also ran [into issues with git 2.27](https://github.com/git-for-windows/git/issues/2732) preventing us from adopting it. These types of popups would also do well to list actual git issues motivating their appearance so that devs can balance between the issues at play to make a final decision.

**Comment by kenotron** [comment]
It looks we're doing this notification based on known issues of old git versions:
https://github.com/microsoft/vscode/issues/98967

But it looks like we also many known issues of git 2.27:
https://github.com/git-for-windows/git/issues/2732

We need to be careful not to nag at users who have certain versions of git installed. git "api" isn't really changing that quickly - unless it breaks internals of vscode, I would heavily lobby AGAINST having any notifications like this at all. We should get rid of this notification altogether.

**Comment by lptr** [comment]
@kenotron fully agree. Another option is to selectively disable features that are known to be problematic, or better yet, fall back to slower / less convenient behavior. Disabling all of Git functionality is too much.

**Comment by joaomoreno** [comment]
> We need to be careful not to nag at users who have certain versions of git installed. git "api" isn't really changing that quickly - unless it breaks internals of vscode, I would heavily lobby AGAINST having any notifications like this at all. We should get rid of this notification altogether.

The current nag exists because we receive many issues because of the way Git 2.25-26 broke paths on Windows. These issues are resolved in 2.27.

> Another option is to selectively disable features that are known to be problematic

The issue in question is basic git functionality: staging a file doesn't work. We simply can't disable that.

**Comment by lptr** [comment]
> The current nag exists because we receive many issues because of the way Git 2.25-26 breaks path handling on Windows. These issues are resolved in 2.27.

This should be clarified in the message at least. I just got our infra team to upgrade to 2.27, only to read the comments here, after which I asked them to downgrade to 2.25. (From this comment I assumed it was a good version: https://github.com/microsoft/vscode/issues/98967#issuecomment-646147576). I guess we should downgrade to 2.24?

> The issue in question is basic git functionality: staging a file doesn't work. We simply can't disable that.

I haven't noticed problems using Git 2.26 on Windows using it from the command-line, so I'm wondering what exactly it is that doesn't work, and if some basic functionality could be provided despite the errors. It feels unlikely that two entire releases on Git (2.25 and 2.26) are completely broken to the point of uselessness.

**Comment by joaomoreno** [comment]
Here are the issues: https://github.com/microsoft/vscode/issues?q=is%3Aissue+2.27+is%3Aclosed

It's related to git behaving stricter in terms of letter casing with a path's drive letter.

**Comment by isidorn** [comment]
I have verified via code review that we introduced an appropriate setting.
