### ISSUE TITLE
reopenFolders setting ignored on osx

### ISSUE THREAD

**Issue by conceptualspace** [Microsoft/vscode#10244]
- vs code v1.4.1 and v1.5.0 (2016-08-05)
- osx 10.11.6

#### To reproduce
1. Open VSCode and open a project folder in the explorer (and optionally some files)
2. Close window
3. Open VScode
4. No folders or files are open. If the project folder is opened again manually, the files are restored

#### Expected behaviour
Opening vscode restores previously open project folder and files

Was working correctly in v1.2.0 and 1.3.0

User settings of `"window.reopenFolders": "all"` has no effect

See also issue #9428. *Note the expected behaviour in mac land is technically not to quit the app when a window is closed (osx discriminates between closing the window and quitting the app); not sure if that is confusing the reopenFolders setting.* reference: https://discussions.apple.com/thread/3826532?tstart=0, https://support.apple.com/en-ca/HT204005

#### Why it matters
Having to browse for a project directory every time the editor is launched is extremely tedious and every other major editor supports a quick way to enter a project between running instances of the app

**Comment by conceptualspace** [comment]
further testing suggests the issue is related to git, and occurs when the vscode window is closed but the app is not quit --

to replicate issue:

1. Open vscode and open a project folder.
2. Close the vscode window (do not **quit** the app)
3. Checkout a different branch of the same project
4. Re-open vscode. The project folder is **closed**

conversely, the following is working as expected:

1. Open vscode and open a project folder
2. **Quit** the app
3. Checkout a different branch of the same project
4. Re-open vscode. The project folder remains **open**

**Comment by bpasero** [comment]
As designed: when you close the window (not quit), Code is still running. When you then click on the dock icon to launch again, we open empty. This follows OSX guidelines and was a change in 1.3 or 1.4.

**Comment by conceptualspace** [comment]
ah ok. but why ignore the reopenfolders setting? if a user has set this to all, they never expect the app to open empty

**Comment by conceptualspace** [comment]
or maybe the best solution is to create a distinct setting for this -- would you consider adding something like reopenFoldersOnRestore?

**Comment by bpasero** [comment]
The setting is not relevant to this experience, it was introduced to enable opening multiple folders when closing and starting up again. It was also added for those people that never want a folder to be restored.

You can read in https://github.com/Microsoft/vscode/pull/7547#issuecomment-225345072 why we changed it.

**Comment by NatsuLF** [comment]
Pls stop the spaming
