### ISSUE TITLE
Staging a file removes focus from the commit message box (regression)

### ISSUE THREAD

**Issue by pvdstel** [microsoft/vscode#102498]
Version: 1.47.0 (system setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

This is a regression. A previous version of this bug was documented in #92401. This one is slightly different: typing simply does nothing. I did not find any issues related to the current stable version (1.47.0).

I've only tested it with Git.

Steps to Reproduce:

1. Stage a file (using Git, or possibly another VCS)
2. While the staging is in progress, type a commit message.
3. The commit message box will lose focus once staging completes.

Does this issue occur when all extensions are disabled?: Yes

![0001-0324](https://user-images.githubusercontent.com/17430732/87437318-70962d80-c5ee-11ea-9c03-aaafde08f3c4.gif)

**Comment by realStandal** [comment]
I too am receiving this bug; same versions as stated above. The GIF, too, represents the same issue I'm running into.

**Comment by LachlanArthur** [comment]
Just mentioning git here as a keyword for future searches.

**Comment by yukuse** [comment]
It can also happen if you modify an unmodified file, save it, and then quickly focus the commit message box before Git detects the change.

**Comment by Dan503** [comment]
This issue keeps coming back over and over. I think this is the 3rd or 4th time this bug has made it's way into production.

Can some sort of automated test be implemented to stop this issue from constantly coming back?

This is such an incredibly frustrating bug. :(

**Comment by gvlx** [comment]
Also on latest update:
Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by Eldair** [comment]
Same thing on 1.48

**Comment by alexalannunes** [comment]
already fixed?

**Comment by pvdstel** [comment]
@alexalannunes Yup, it's fixed in the insiders release.
