### ISSUE TITLE
Unable to open VS Code on mac

### ISSUE THREAD

**Issue by akshaybabloo** [microsoft/vscode#102451]
- VSCode Version: 1.47.0
- OS Version: mac 10.15.5

Steps to Reproduce:

1. Update from 1.46 to 1.47
2. Try to open it

Does this issue occur when all extensions are disabled?: Yes

I also tried doing `code --verbose` and this is what I got:

```
[main 2020-07-14T02:06:25.532Z] Sending env to running instance...
[main 2020-07-14T02:06:25.540Z] Sent env to running instance. Terminating...
[main 2020-07-14T02:06:25.541Z] Lifecycle#kill()
```

**Comment by roblourens** [comment]
Is it possible that there is a zombie vscode process running in the background somewhere? You might get unstuck by killing it manually.

**Comment by akshaybabloo** [comment]
Ya possible. Restarting the system fixes it. But this happens frequently
