### ISSUE TITLE
ubuntu16.04 update vscode and the older still exist

### ISSUE THREAD

**Issue by liangpu597** [microsoft/vscode#102472]
- VSCode Version: 1.45.1
- OS Version:vubuntu16.04

Steps to Reproduce:

1. open terminal use:
```
wget https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable -O /tmp/code_latest_amd64.deb
sudo dpkg -i /tmp/code_latest_amd64.deb
```
2.
and the older version still exist
![2020-07-14 16-39-46屏幕截图](https://user-images.githubusercontent.com/23580110/87404513-d1bf0080-c5f0-11ea-8c4e-ae264e5b6db5.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
FYI @flexiondotorg, I think the old vscode snap is still published?
