### ISSUE TITLE
Question: How to change behaviour of commenting out a line?

### ISSUE THREAD

**Issue by xiaochuanyu** [Microsoft/vscode#10247]
How is the behaviour for commenting out a line determined (`ctrl+/`)?
I'm trying to fix a language extension for fish shell language (`ext install fish`).
The comment string is supposed to start with "#" not "//" which is what is produced when I do `ctrl+/`.

**Comment by stkb** [comment]
I haven't tested it, but in the `fish.configuration.json` file of that extension, you need to modify the `lineComment` and `blockComment` values. 

[Reference documentation](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages)

**Comment by aeschli** [comment]
@xiaochuanyu, the above answer is correct, you find it in the language configuration file. (Thanks @stkb!)
