### ISSUE TITLE
Support command variables for settings

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#102414]
https://code.visualstudio.com/docs/editor/variables-reference#_command-variables works for `tasks.json` and `launch.json` files, but doesn't resolve the variables when fetching settings via VSCode API.
As we have removed interpreter path from settings, users need a way to reference the selected interpreter path in settings. We were hoping for something like `${command:python.interpreterPath}` which works for `settings.json` as well.

Launching a command is async so this probably can't be done as fetching settings via API is not async. Your thoughts?

**Comment by alexr00** [comment]
@sandy081 I think this is not something we can do, since settings can be fetched at any time, and a command could require user interaction to evaluate. It would be a weird experience to suddenly be prompted to provide input just because a setting is being read.

**Comment by karrtikr** [comment]
Yeah commands could require user interaction. In our case, it doesn't and simply returns the string, which is the internal setting value. But I agree it's not a good solution generally. Can you suggest any alternatives that we can use?

**Comment by alexr00** [comment]
Perhaps environment variables?

**Comment by karrtikr** [comment]
Yeah, although in a multiroot scenario each workspace folder can have its own selected interpreter, so having just one environment variable won't suffice.

**Comment by alexr00** [comment]
For that, you can use folder specific settings (settings.json file in the .vscode folder)

**Comment by karrtikr** [comment]
As I mentioned in the original issue, we have removed the interpreter path setting from settings.json, and storing it in internal VSCode storage. So we can't store it in folder settings.
We have setup things so user can access the interpreter path in `launch.json` and `tasks.json`, using `${command:python.interpreterPath}`. But unfortunately that can't be done for settings.json

**Comment by alexr00** [comment]
What if there was an API to resolve `${}` variables? Would that fit your use case?

**Comment by karrtikr** [comment]
Yes, that should work👍

**Comment by karrtikr** [comment]
@alexr00 Apologies, actually I just realized it might be a problem. I assuming this variable resolving API you are providing have to be asynchronous, because you would be running commands to resolve it.

The setting inside the extension is accessed as a synchronous operation, something like `ConfigService.getSettings(resource).pythonPath`. So we need to do all the resolving synchronously. Changing it to an async operation will require us to change all the places in the extension.

Looks like it'll be easier for the extension to do the resolving itself for this one.

**Comment by alexr00** [comment]
Yes, such an API would have to be asynchronous by its very nature.
