### ISSUE TITLE
Multiple Cursor, LightBuild not working

### ISSUE THREAD

**Issue by SonGokussj4** [microsoft/vscode#102497]
- VSCode Version: code-1.47.0-1594284094.el7.x86_64.rpm
- OS Version: CentOS Linux release 7.7.1908

Steps to Reproduce:

1. Hold CTRL, click on different places, cursor not multiplying.
2. Click on a line where Yellow LightBulb appears. Click on it, nothing hapens.

Does this issue occur when all extensions are disabled?: Yes/No

Don't know. I've already `yum downgrade code-1.46.1-1592429042.el7.x86_64.rpm` and it works again.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by SonGokussj4** [comment]
Interesting... After I installed the version again, it works just fine. ¯\_(ツ)_/¯
Tried newest version: 
Version     : 1.47.1
Release     : 1594686424.el7
Everything works. 

So I'm closing this and sorry for the false alarm.
