### ISSUE TITLE
Left Bottom Gear opens menu in scroll, rather than full layout

### ISSUE THREAD

**Issue by LBensman** [microsoft/vscode#102416]
Issue Type: <b>Bug</b>

1. Open VSC.
2. Click Left button Gear icon that opens up menu (with items like Preference, Check for Updates, etc)
3. Note that menu opens with just couple of items visible, and rest you have to scroll.  It should open fully.

Note that most of the time (at least I, but suspect most people as well) this menu is used to activate update of VSC when it shows badge notifying that there's an update available.  And every time it requires to scroll to it for no good reason.  Without menu being collapsed, one wouldn't need to scroll.

![image](https://user-images.githubusercontent.com/1187128/87341453-a61c1780-c517-11ea-87fd-21620aa73172.png)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|-psn_0_2146828|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
meson|asa|1.3.0
atlascode|atl|2.6.6
code-gnu-global|aus|0.2.2
vscode-database|baj|2.2.3
Nix|bbe|1.0.1
vscode-markdownlint|Dav|0.36.1
restore-editors|eam|0.2.1
gc-excelviewer|Gra|3.0.37
cmake-clangd-helper|Har|0.4.0
svgeditor|hen|2.9.0
c-cpp-flylint|jbe|1.5.0
cmake-tools-helper|mad|0.2.1
vscode-clang|mit|0.2.3
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
python|ms-|2020.6.91350
cmake-tools|ms-|1.4.1
cpptools|ms-|0.28.3
hexeditor|ms-|1.1.0
vs-keybindings|ms-|0.2.0
puppet-vscode|pup|0.27.3
java|red|0.64.1
vscode-yaml|red|0.8.0
trailing-spaces|sha|0.3.1
vscode-hexdump|sle|1.7.2
code-spell-checker|str|1.9.0
ninja|sur|0.0.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.9
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-icons|vsc|10.2.0
debug|web|0.25.0

</details>

**Comment by sbatten** [comment]
https://github.com/microsoft/vscode/issues/90331
