### ISSUE TITLE
Ctrl + Tab sudenly not working

### ISSUE THREAD

**Issue by sebasijan** [microsoft/vscode#102476]
- VSCode Version:1.47.0
- OS Version:Windows 10 64 bit

Steps to Reproduce:

1.Open VS Code
2.Try switching tabs using ctrl+tab
3.Notice that nothing happens

Does this issue occur when all extensions are disabled?: Yes

______

I checked this setting in my keyboard shortcuts, and it seems to be correct but it still doesn't work:

![image](https://user-images.githubusercontent.com/13226838/87405402-4d03c080-c5b7-11ea-963e-e4a4277a3dc1.png)

**Comment by roblourens** [comment]
You have multiple tabs open right? Do you have any extensions that might be adding additional keybindings? You could try starting with `--disable-extensions` to test that.
