### ISSUE TITLE
Code and Code-insiders crash when attempting basic functions

### ISSUE THREAD

**Issue by baine-reynolds** [microsoft/vscode#102448]
Causes crash:
Exploring to "Help" > "About"
Attempting to save a file
Attempting to open a folder
Attempting to close an open tab
Attempting to submit an issue (had to do it manually)

Does not Crash:
Open new tab
Open new window
Exploring to "Preferences" > "Settings" (and making changes)

System Info:
Manjaro on Linux 5.6.16-1
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.0.3
DISTRIB_CODENAME=Lysia
DISTRIB_DESCRIPTION="Manjaro Linux"

Using snap for both Code and Code-insiders
Stable:
snap-id:      Ht0aUHi7ofh9Fbwh6m7jUN2pAy6kzBiu
tracking:     latest/stable
refresh-date: today at 19:52 CDT
channels:
  latest/stable:    d5e9aa02 2020-07-10 (36) 151MB classic

Insiders:
snap-id:      vNVY8DiBL4e2Q8H3Xtsh71c8QSTaxBdp
tracking:     latest/stable
refresh-date: today at 19:34 CDT
channels:
  latest/stable:    3bc3f95d 2020-07-13 (480) 153MB classic

CPUs
AMD Ryzen 9 3900X 12-Core Processor (24 x 2540)

GPU Status
2d_canvas: unavailable_software
flash_3d: disabled_software
flash_stage3d: disabled_software
flash_stage3d_baseline: disabled_software
gpu_compositing: disabled_software
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
opengl: disabled_off
protected_video_decode: disabled_off
rasterization: disabled_software
skia_renderer: enabled_on
video_decode: disabled_software
viz_display_compositor: enabled_on
vulkan: disabled_off
webgl: unavailable_software
webgl2: unavailable_software

Load (avg)    1, 1, 1

Memory (System)    62.83GB (53.50GB free)

Process Argv    --no-sandbox

Screen Reader    no

VM    0%

[symbolicated_stack_insiders.txt](https://github.com/microsoft/vscode/files/4915923/symbolicated_stack_insiders.txt)
[symbolicated_stack_stable.txt](https://github.com/microsoft/vscode/files/4915924/symbolicated_stack_stable.txt)

Launched with `code --disable-extensions` however this continues to crash. (Also, no extensions are installed)

Code was running earlier today so I'm not sure if the snap updated causing this issue or not.

**Comment by bpasero** [comment]
Linux Snap it seems.

**Comment by yamafaktory** [comment]
Hi :hand:,

I can confirm the issue: same distro / also using snap.

It's definitely coming from the latest release (was perfectly fine yesterday evening / Berlin GMT+2).

**Comment by joaomoreno** [comment]
#100940
