### ISSUE TITLE
Per workspace terminal history

### ISSUE THREAD

**Issue by DisasterMan78** [microsoft/vscode#102475]
Users often have multiple workspaces on the go, with very different projects. When switching between workspaces after restarting VS Code, the terminal history is shared, which can be frustrating as when switching to a project that hasn't been worked on for a while, the user then has to plough through a lot of history that is irrelevant to that project.

Proposal:
Per-workspace terminal history.

Each workspace saves it command line history individually, so only commands entered for that project are accessible.

    I have done several searches and haven't found a similar feature request. Apologies if I missed it.

**Comment by Tyriar** [comment]
We can't support this sort of thing generically as we just launch the process and configuring the shell too much would be risky. You may be able to configure this yourself though, eg https://unix.stackexchange.com/a/204928

**Comment by DisasterMan78** [comment]
Entirely fair enough, and thank you for the handy tip!
