### ISSUE TITLE
Shift+Alt+R does not "reveal file in explorer"

### ISSUE THREAD

**Issue by lborgman** [microsoft/vscode#102496]
Issue Type: <b>Bug</b>

If I right-click the tab for an open file it says that Shift+Alt+R should "Reveal file in Explorer.

This key combination instead opens the Run menu.

This is on Windows 10. Default key bindings. Windows 10 Sticky Keys on. 

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU N4200 @ 1.10GHz (4 x 1094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.84GB (0.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.3
cursor-charcode|but|0.9.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.2
vscode-sort|hen|0.2.5
beautify|Hoo|1.5.0
powershell|ms-|2020.6.0
material-icon-theme|PKi|4.2.0
partial-diff|ryu|1.4.1
vim|vsc|1.15.0
json|Zai|1.0.4

</details>

**Comment by ArturoDent** [comment]
Note that <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>R</kbd> has a `!editorFocus` `when` context.  

There is an unbound `revealInExplorer` command you could use to make your own keybinding.

**Comment by roblourens** [comment]
Is the explorer focused when you do this? This should only apply when the explorer is focused, otherwise you can do the change that @ArturoDent suggests to make it global.

**Comment by lborgman** [comment]
Thanks for your comments. It looks like it works as intended.

However I think it should work different by default. What is the reason for this key binding to be state dependent by default in the way it is now? The most common situation where a user wants ot "reveal file in explorer" is probably when focus is in editing this file.

**Comment by roblourens** [comment]
This feels like a task that is more relevant to the file explorer than the editor to me. Typically a user can do everything they need inside vscode and rarely need to use the native system. But that's why it's customizable, you can set it up however you prefer :)
