### ISSUE TITLE
MacOS cannot find VSCode app path during debug, unescaped spaces in the App name?

### ISSUE THREAD

**Issue by mix3d** [microsoft/vscode#102433]
- VSCode Version: 1.47
- OS Version: MacOS 10.15.3

Steps to Reproduce:

1. Run debugger on an app using electron
2. Observe the console error

```
/Users/madison/Workspace/keystone-omni/OmniDesktop/node_modules/.bin/electron .
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '"/Applications/Visual'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:899:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Process exited with code 1
```

Launch Config:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Main Process",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron.cmd"
      },
      "args": ["."],
      "outputCapture": "std"
    }
  ]
}

```

This has also been discussed on StackOverflow: https://stackoverflow.com/questions/62715703/cannot-find-module-applications-visual-when-running-launch-json-config
Was working just fine in v1.46 / the old debugger.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mix3d** [comment]
Based on the output, is there a missing `"` sign or is the unescaped space ending the path finding, meaning spaces in the quoted string are failing somewhere? I'm no expert on platform-specific unique path issues :/

**Comment by connor4312** [comment]
You're hitting a version of https://github.com/microsoft/vscode/issues/102035#issuecomment-656801666. The resolution steps in the comment should work for you.

**Comment by mix3d** [comment]
The possible solution link was not obvious:
There was no option for `nodeVersionHint` in settings in the release version, and upgrading node was not an option, so I'm posting here for clarity:
1.47.x still lets you turn off the new debugger, even if it's on by default now. 

![image](https://user-images.githubusercontent.com/1474137/87480952-3c693f80-c5e3-11ea-8c2f-75087db3e66d.png)

**Comment by connor4312** [comment]
`nodeVersionHint` will only appear as a 'valid' configuration option if your debug type is `pwa-node` (rather than just `node`), but it should still work.

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!

**Comment by AlphaCodeZero** [comment]
@connor4312 Hi, I've updated to 1.47.3 but still suffering this problem, how can I solve it?

**Comment by connor4312** [comment]
@AlphaCodeZero please share the error you are hitting. That option will eventually go away.
