### ISSUE TITLE
github app closes at [Create Issue > microsoft/vscode > Bug report]

### ISSUE THREAD

**Issue by lorenzznerol** [microsoft/vscode#102434]
github app closes at [Create Issue > microsoft/vscode > Bug report]

## Environment data

- iPhone 7
- 13.5.1

**Comment by RMacfarlane** [comment]
Hi @lorenzznerol, this sounds like a problem with the GitHub mobile app, not VSCode. I'm not sure what their preferred way of receiving bug reports is, they give a contact email you could use here: https://docs.github.com/en/github/getting-started-with-github/github-for-mobile#sharing-feedback

**Comment by lorenzznerol** [comment]
Hi @RMacfarlane, I had searched for GitHub repo on GitHub without success ;). Now I mailed the feedback as suggested.
