### ISSUE TITLE
Menus: Dropdown menu gets tiny when opened near the edge of the workbench

### ISSUE THREAD

**Issue by bravecobra** [microsoft/vscode#102409]
- VSCode Version: 1.47
- OS Version: All

Steps to Reproduce:

Just add a lot of repositories
![image](https://user-images.githubusercontent.com/391353/87337904-85b68200-c544-11ea-9308-1cbabfc019f7.png)

The submenu should open to the top instead of always to the bottom when opened in the lower part of the screen. This view is just become unusable.
Is there a way to revert to the previous behaviour? I can't say I'm happy with this new view. With lots of repositories this is not an improvement, on the contrary.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@bravecobra sorry for this. 2 workarounds: the first would be to move the view up toward the top so the menu doesn't try to open like this. the second workaround which even less ideal is to use the native title bar experience. `window.titleBarStyle`. This uses more native menus which don't have this bug but affects the title bar and menu bar styling as well.

**Comment by sbatten** [comment]
fyi @joaomoreno

**Comment by joaomoreno** [comment]
Here's where the SCM single view feedback is being collected: #102118

**Comment by sbatten** [comment]
the menus try to shrink if they think there isn't enough room. normally a menu is drawn in the top left of the window before being positioned, but now dropdowns are using the anchor as the parent of the menu. this means we need to set the position of the container to fixed before rendering the menu to give it enough space to avoid shrinking more than necessary.

**Comment by ryenus** [comment]
It seems the problem still exists with 1.47.2

What's happening:
![image](https://user-images.githubusercontent.com/610161/87802424-cc2d1900-c883-11ea-8507-10f8c1a2ecfa.png)

What's expected:
![image](https://user-images.githubusercontent.com/610161/87803197-bec45e80-c884-11ea-984d-ca35854409f8.png)
