### ISSUE TITLE
keyboard not working after update

### ISSUE THREAD

**Issue by jonathanburnhill** [microsoft/vscode#102400]
- VSCode Version:
- OS Version:

Just had a update and now most keys wont type, anyone else having this problem/?

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including what platform, and whether it still occurs if you run the command to reload with all extensions disabled.

**Comment by tu6ge** [comment]
`Ctrl + S` occasionally causes the keyboard to be unable to work

**Comment by alexdima** [comment]
@tu6ge Please create a separate issue, it doesn't look like you have the same problem.

@jonathanburnhill Do you have any steps?

**Comment by jonathanburnhill** [comment]
Hi Sorry for late reply, it seems to have fixed itsself, sorry for the waste of time
