### ISSUE TITLE
Quick open: Once "file results" are loaded, it resets selected file to the first

### ISSUE THREAD

**Issue by jepperaskdk** [microsoft/vscode#102480]
When searching with `ctrl+p`, "recently opened" will show a list of files. Some time after, "file results" will extend the list with non-recently opened files as well.
The problem is that if i move the "cursor" down in recently opened to e.g. the 3rd item, then the position is reset to the 0th once the file results are retrieved. This is super annoying when you're switching between files in a large workspace.
Hope it makes sense, otherwise I can try to make a GIF showing the problem.

**Comment by bpasero** [comment]
@chrmarti might need your advise here: I am setting the items of the picker here in one place:

https://github.com/microsoft/vscode/blob/2a8c8def27726127d8fe86dfb2a126c9f3f54516/src/vs/platform/quickinput/browser/pickerQuickAccess.ts#L149

My understanding is that this will not preserve any active item that was there before. Can I simply remember the active item via `const activeItem = picker.activeItems[0]` before setting the new picks and then restore that?

**Comment by jepperaskdk** [comment]
Awesome @bpasero, thank you for a quick response - is there a PR for this issue?

**Comment by bpasero** [comment]
No, but the change is https://github.com/microsoft/vscode/commit/4855013f5e971b94ffd4a6816446c717c82ff29a and should be available today in our insiders release.

**Comment by jepperaskdk** [comment]
Works perfectly. :-)

**Comment by isidorn** [comment]
Adding label verified since autho verified it.
