### ISSUE TITLE
Using cmd.exe instead of powershell gives errors sometimes

### ISSUE THREAD

**Issue by n3rd4i** [microsoft/vscode#102464]
Issue Type: <b>Bug</b>

1. Change default shell to `cmd.exe`
2. Open a file in "a directory" [as a project]
3. Close VSCode
4. Reopen VSCode and close a file was opened before VSCode was closed
5. Error appears, something like this:
```
The terminal process "C:\WINDOWS\System32\cmd.exe '-nol'" terminated with exit code: 1.
```

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.43GB (7.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
insertnumbers|Asu|0.9.1
vscode-astyle|chi|0.9.0
gitlens|eam|10.2.2
chocolatey-vscode|gep|0.7.1
beautify|Hoo|1.5.0
git-graph|mhu|1.24.0
python|ms-|2020.6.91350
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
hexeditor|ms-|1.1.0
material-icon-theme|PKi|4.2.0
remove-comments|pli|1.2.2
partial-diff|ryu|1.4.1
windows-terminal|Tyr|0.5.1
markdown-all-in-one|yzh|3.1.0

</details>

**Comment by Tyriar** [comment]
What is `'-nol'`? That's arg is probably what's causing the terminal to exit with code 1. Try removing the setting `terminal.integrated.windows.shellArgs`.
