### ISSUE TITLE
Make "Toggle Status Bar" a global setting

### ISSUE THREAD

**Issue by kendaleiv** [Microsoft/vscode#10246]
It seems "Toggle Status Bar" is bound to the location from where the editor was opened from, rather than as a *global* setting.

## To reproduce

- Create a new folder, `cd` into folder, run `code .`.
- Status bar should be visible, use "Toggle Status Bar" to hide it.
- Close editor, relaunch with `code .` from same location. The status bar should not be visible
- `cd ..` then create a different folder, `cd` into the new folder and run `code .`. The status bar should be visible again. I would expect this setting to be applied globally, rather than in this manner.

This happens on Windows 10 for me, haven't checked it in other environments.

**Comment by bpasero** [comment]
W.T.H
