### ISSUE TITLE
markdown preview can be slow to update and eventually stops updating

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#102430]
Version: 1.48.0-insider (system setup)
Commit: e7920dce7bfd0b707ebfc0a5379c6edd2233e475
Date: 2020-07-10T11:58:37.847Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Load some markdown files
2. Open preview
3. Switch between them

I tested this with extensions off and it was still the same.

![markdown-switch](https://user-images.githubusercontent.com/936006/87355043-8efd1a00-c557-11ea-9f43-6a25e98f872d.gif)

Profile:
[Profile-20200713T222331.zip](https://github.com/microsoft/vscode/files/4915246/Profile-20200713T222331.zip)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This should be fixed in the next insiders build

**Comment by jasonwilliams** [comment]
oh that was quick, was it a known issue?
