### ISSUE TITLE
Live edit the results of a search

### ISSUE THREAD

**Issue by cmario92** [microsoft/vscode#102424]
As a user, while searching for keywords using the `New Search Editor`  I want to be able to have the ability to quick/live edit the results of the search, without navigating to the file.

Editing the search results should indicate the file as `dirty` and prompt the user with indication.

![image](https://user-images.githubusercontent.com/5765285/87349280-b86d7400-c55e-11ea-94c7-3718f2073e6b.png)

**Comment by ArturoDent** [comment]
Have a look at https://marketplace.visualstudio.com/items?itemName=jakearl.search-editor-apply-changes You can apply changes you make in the search editor across files.  It marks the files changes as dirty and all the work is done in the search editor.

**Comment by JacksonKearl** [comment]
I created the extension @ArturoDent suggested, it is the best way to do this.
