### ISSUE TITLE
Editor ignoring tabSize setting

### ISSUE THREAD

**Issue by davelane** [Microsoft/vscode#10248]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Since the update to 1.4.0 tabSize is not working correctly.
Steps to Reproduce:
1. Open a file with indentation of tabSize 4 and space indentation
2.Change the tabSize in the workspace settings to 2
    "editor.tabSize": 2,
    "editor.insertSpaces": true,
3 Hit Shift-Alt-F 
Nothing happens. If I increase the indentation on a line and hit Shift-Alt-F it does reformat, but to tabSize 4

**Comment by whitecolor** [comment]
Right so can not change indentation on existing files.

**Comment by whitecolor** [comment]
Probably this also should allow to cancel formatting action.

**Comment by davelane** [comment]
I actually discovered in the meantime that there is a button in the bottom toolbar (or whatever it is called)  where the current indentation is displayed (e.g. Spaces: 4). You can click on this then -> "Indent using spaces" and then "2". 2 will also be highlighted as "Configured tab size". Would be at least nice to be able to do this from the command palette, but I haven't found a way.

**Comment by whitecolor** [comment]
Right so then it works fine I believe.

**Comment by isidorn** [comment]
Yes, the formater will format based on a language and that does not change the indentation (correct me if I am wrong @jrieken)
And to format indentation we have specifally introduced those actions which you have discovered.
The optimal scenario would be that the language formater would respect our indentation settings - @jrieken would that be possible?

**Comment by jrieken** [comment]
> Yes, the formater will format based on a language and that does not change the indentation (correct me if I am wrong @jrieken)

Technically the formatter can do whatever it wants to do, but most formatters don't change the indentation or use the current editor ident settings when formatting

**Comment by isidorn** [comment]
Thus closing this as designed

**Comment by davelane** [comment]
I would expect the "Format Code" command to do this. This is also what happens in every IDE and editor that I can think of (from memory). Not a biggie anyway. I just figured out issuing "Indent using Spaces" is possible from Command Palette and then you are prompted for the number of spaces. I must say though that nobody could reasonably be expected to figure this out (what is happening, what to do) within 30s. Don't make me think! :)

**Comment by whitecolor** [comment]
I think it is ok that you have to implicitly change tab size.

**Comment by davelane** [comment]
An honest question: what does "editor.tabSize" in settings actually do then? The only thing I can see is that it appears as "configured tab size" when you do an "indent using spaces" from the command palette. It seems to me, if the indentation is detected when a file is opened and formatting a file (Shift Alt F) doesn't use the configured size it will never get used.

**Comment by whitecolor** [comment]
Newly created files are treated with this indentation setting.

**Comment by Enethion** [comment]
Except I run on this with new file. Also I can't fix it...

**Comment by mehas** [comment]
+1, I'm experiencing the same. `editor.tabSize` is set to 2 in my user settings, File > New File creates a new file set to Tab Size: 4, confirmed in the status bar. Switching editor tabs seems to reset the Tab Size to 4 on the file in the tab as well.

**Comment by ivostoykov** [comment]
+1 (ver. 1.13.0; Shell 1.6.6, Renderer 56.0.2924.87, Node 7.4.0 Date 2017-0608)
Same problem - editor.tabSize 2 is rendered as 4 spaces (4 are set in general settings).
The same is if add javascript section
```
"[javascript]": {
    "editor.tabSize": 2
}
```

**Comment by Enethion** [comment]
Try solution from https://github.com/Microsoft/vscode/issues/24938#issuecomment-301220106 it worked for me.
