### ISSUE TITLE
Python jupyter notebook - Not possible to save changes

### ISSUE THREAD

**Issue by OvRad** [microsoft/vscode#102429]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.Open an .ipynb file and change the content
2.Press SAVE / Enable AUTOSAVE 

PS: I am facing serious issues with VSCODE since this update on both Windows 10 and Ubuntu e.g. see duplicate paste issue and others. Can you please ensure for the future a proper testing before releasing? 

BR

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sergiykhan** [comment]
Same here with the latest version of VS Code 1.47. Closing all tabs and restarting VS Code helps when the saving (and auto-saving) stops working. Only Jupyter notebooks seem to be affected.

For duplicate paste issue, turn automatic updates off and then downaload and install the previous version https://update.code.visualstudio.com/1.46.1/win32-x64-user/stable

**Comment by tonibofarull** [comment]
Same problem in VS Code 1.47.1 (Windows 10).

**Comment by Leonardofreua** [comment]
Same problem in VS Code 1.47.1 (Ubuntu 18.04 LTS).
