### ISSUE TITLE
Actions to not invoke when clicking on lower corner of them

### ISSUE THREAD

**Issue by agoretsky** [Microsoft/vscode#10241]
- VSCode Version: 1.5.0-insider
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Click on close button in tab near the icon

I see this bug from 1.3 version

**Comment by bpasero** [comment]
I cannot reproduce.

**Comment by bpasero** [comment]
![editors](https://cloud.githubusercontent.com/assets/900690/17472111/3be16ec2-5d49-11e6-9ed5-ac1372bfbb5e.gif)

**Comment by agoretsky** [comment]
@bpasero, http://g.recordit.co/xdhQncAZCz.gif

**Comment by bpasero** [comment]
Happens with all our actions and why the click handler (https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/actionbar/actionbar.ts#L109) is not being executed but the mouse down (https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/actionbar/actionbar.ts#L116) listener is a total mystery to me.

@joaomoreno fyi

**Comment by bpasero** [comment]
This happens because of the animation we have for actions. Once the action moves up, the click is not received anymore.

From what I remember @jrieken introduced the animation 4 years ago ;)

**Comment by jrieken** [comment]
Yeah - it's time to fix that
