### ISSUE TITLE
contextualTitle property does not work as described

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#102447]
- VSCode Version: 1.47
- OS Version: macOS Catalina

Steps to Reproduce:

1. Create a `viewContainer` and a `view`, like this:
```json
    "contributes": {
        "viewsContainers": {
            "activitybar": [
                {
                    "id": "bookmarks",
                    "title": "Bookmarks",
                    "icon": "images/bookmark-activity-bar.svg"
                }
            ]
        },
        "views": {
            "bookmarks": [
                {
                    "id": "bookmarksExplorer",
                    "name": "Explorer",
                    "contextualTitle": "BooksContextual"
                }
            ]
        },
```

2. The `contextualTitle` property says: _"Human-readable context for when the view is moved out of its original location. By default, the view's container name will be used. Will be shown"_ 

3. Build and Run the extension

4. The `view` in the `Activity Bar` is displayed using the `contextualTitle` value, instead of its `name`. In fact, it replaces the `activityBar.title` instead of the `view.name`.

![Screen Shot 2020-07-13 at 21 47 18](https://user-images.githubusercontent.com/3781424/87368077-0a100180-c553-11ea-9b22-e102a7a1a83b.png)

5. if you move that `view` to the panels, at first, it appears the `contextualTitle` works
![Screen Shot 2020-07-13 at 21 47 31](https://user-images.githubusercontent.com/3781424/87368091-109e7900-c553-11ea-9160-a6ee88f4fa29.png)

6. But if you click it, it again shows just like in the original location.
![Screen Shot 2020-07-13 at 21 47 45](https://user-images.githubusercontent.com/3781424/87368094-14320000-c553-11ea-8050-01cde21558d0.png)

I'm not sure if I'm using the correct approach. Maybe I misunderstood how `contextualTitle` should work, but my intention is  to name that _single view_ as `Bookmarks`, when it is moved out of its `Activity Bar`

Thank you 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sbatten** [comment]
item 4 must have been a bug at the time but has since been fixed. I can no longer repro that behavior. 

item 5&6 are expected, we show the Contextual Title always and if there is only one view inside, we concatenate it. We have special logic that hides the contextual title if the nested view has the same title. Showing the nested view title is important for extensions with multiple views that can now span panel and side bar.
