### ISSUE TITLE
Indicate selected folder in explorer even when focus is not in explorer

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10245]
- VSCode Version: Code - Insiders 1.5.0-insider (1a7ca5a77bf6b63951e499ea93b7316d36118ade, 2016-08-05T07:14:50.554Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Create project with couple of folders
2. Select folder
3. Click somewhere else so that Explorer loses focus
4. Hover icons to create new file/folder
5. It's impossible to tell where the file/folder will be created because there is no highlight of currently selected folder (in this case I have `folder-2` selected):

![image](https://cloud.githubusercontent.com/assets/1723815/17458237/8eae7eae-5bd9-11e6-898b-3762cde08875.png)

Clicking new file:

![image](https://cloud.githubusercontent.com/assets/1723815/17458240/aadeffea-5bd9-11e6-87be-466a7b3d59bc.png)

**Comment by bpasero** [comment]
We fixed this for August 👍
