### ISSUE TITLE
Can open find widget in cell editor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#102441]
- Open notebook, focus editor
- Open debug console
- Press cmd+f with focus in debug console

Probably need to tweak a context key. It should be based on active editor, not editor focus I think.

![image](https://user-images.githubusercontent.com/323878/87362819-9b1bb400-c524-11ea-97fb-ba74057340c0.png)

**Comment by roblourens** [comment]
As long as that doesn't override cmd+f in other places like the terminal

**Comment by rebornix** [comment]
Since it doesn't always happen, my guess is when it happens

* monaco editor thinks it has focus (as its textarea is focused)
* notebook editor doesn't think so, so its cmd+f is not activated

**Comment by rebornix** [comment]
A simpler reproduce steps:

* Open a notebook
* Focus into a code cell
* Menu -> Edit -> Find

**Comment by rebornix** [comment]
@mjbvz I guess we may want to consolidate find/replace menus for *custom editors?

**Comment by mjbvz** [comment]
Yes we should try to unify our find commands, just like we did for the copy/paste and undo/redo commands last iteration

**Comment by rebornix** [comment]
@mjbvz thanks for the pointer, I'll look into it.

**Comment by rebornix** [comment]
Find and Replace commands/actions are now extended to support multiple implementations. Adopted in Notebook and @mjbvz can adopt this in web views.
