### ISSUE TITLE
Smartstep incorrectly activates when source maps exist but fail to load

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/vscode#102431]
- VSCode Version: 1.47
- OS Version: Linux (Debian Bullseye)

Steps to Reproduce:

1. Have a library dependency that has source maps to provide line numbers in exceptions, but doesn't bundle the source code
2. Try to step into a call to that library

Does this issue occur when all extensions are disabled?: Yes

In the "old" (<=1.46) vscode, the nodejs debugger would step into the .js code when loading source maps failed.

Now it just gives you a window that says it couldn't load the source, and you're up the proverbial creek. Often it will even take that window away and just do nothing as far as source code windows when you step in, or try to double-click on such a frame in the call stack view.

**Comment by connor4312** [comment]
I was aware of this issue but there's no separate issue for it.

If you're running into problems with this you can set `smartStep: false` in your launch config, until we get a proper resolution in place.

**Comment by mgabeler-lee-6rs** [comment]
> If you're running into problems with this you can set `smartStep: false` in your launch config, until we get a proper resolution in place.

Appreciate the suggestion, but with well over 100 launch configs across 30+ repositories, that is not a practical workaround for the software stack in which I work ;)

For now I'm dealing with this by just forcing use of the old debugger with `"debug.node.useV3": false` in my user config

**Comment by connor4312** [comment]
Sounds good, this will be fixed in the [next nightly](https://github.com/microsoft/vscode-js-debug/#nightly-extension) build at 5PM PST today.
