### ISSUE TITLE
TreeDataProvider.onDidChangeTreeData.fire() was removed and fire(undefined) doesn't update

### ISSUE THREAD

**Issue by mentat9** [microsoft/vscode#102454]
- VSCode Version: 1.48.0-insider
- OS Version: 2004 (OS Build 19041.329)

Steps to Reproduce:

1. Write an extension that implements TreeDataProvider<T>
2. Attempt to use onDidChangeTreeData.fire() (no parameter) or onDidChangeTreeData.fire(undefined) or onDidChangeTreeData.fire(null).
3. Observe compile failure

Does this issue occur when all extensions are disabled?: Yes/No
N/A

Additional information:
Calling fire(item) when item is undefined or null at runtime works, **but only running under the debugger**. The same code after making a release build and packaging it into .vsix doesn't update the tree.

**Comment by alexr00** [comment]
I can't reproduce this issue. Here is the branch/commit I made in the sample extension to test it out (the vscode engine version number update doesn't matter, I tried with 1.46 and 1.47, running on 1.48).  I built, packaged to a vsix, and installed.

**Comment by mentat9** [comment]
I have confirmed that the issue was caused by package changes, and not by the change to vscode 1.48.0-insider. Thank-you for updating the sample: it was helpful in RCing the issue.
