### ISSUE TITLE
Every CLI executes debugger

### ISSUE THREAD

**Issue by halfnibble** [microsoft/vscode#102422]
Issue Type: <b>Bug</b>

I'm not sure what is causing it,  but I can no longer use the Terminal in VS Code. It auto starts debugger and I can't execute any CLI commands without debugger running first. 

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.20.0
open-in-azure-devops|ben|0.0.1
vscode-intelephense-client|bme|1.5.2
es7-react-js-snippets|dsz|2.8.2
gitlens|eam|10.2.2
apacheconf-snippets|eim|1.3.0
auto-close-tag|for|0.5.8
go|gol|0.15.1
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.17.0
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
azure-account|ms-|0.8.11
vsliveshare|ms-|1.0.2427
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.2.0
java|red|0.64.1
sass-indented|rob|1.5.1
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.23.0
vscode-maven|vsc|0.22.0

(2 theme extensions excluded)

</details>

**Comment by rogerfar** [comment]
Happens in Windows 10 too. Even running `npm outdated` starts the debugger.

**Comment by connor4312** [comment]
Thanks for the issue! Please see https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467

/duplicate

**Comment by halfnibble** [comment]
Thank you @connor4312. I had to do all the things listed in that comment, but I now have my CLI back!
