### ISSUE TITLE
Application runs but breakpoints don't 'Unbound breakpoint' when using Launch Program config

### ISSUE THREAD

**Issue by bhatnagardivyanshu** [microsoft/vscode#102407]
- VSCode Version: June 2020 (version 1.47)
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Add a Launch Program configuration and leave it to default configuration
2. Start debugger and add breakpoints
3. The breakpoints are added but have empty circle shape and say **Unbound breakpoint** on hover
4. The application, on the other hand, is running like nother ever happened
5. Tried removing and adding new breakpoints while the debugger is running

Does this issue occur when all extensions are disabled?: Yes

**Comment by bhatnagardivyanshu** [comment]
Found the solution. https://github.com/microsoft/vscode/issues/102166#issuecomment-657138385

Thanks.

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!

**Comment by bhatnagardivyanshu** [comment]
@connor4312 Thanks for informing. :+1:
