### ISSUE TITLE
Crash in docker container

### ISSUE THREAD

**Issue by magwas** [microsoft/vscode#102461]
- VSCode Version: 1.47.0 d5e9aa0227e057a60c82568bf31c04730dc15dcd x64

- OS Version: DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

Steps to Reproduce:

1. start code
2. see it appear and crash

Does this issue occur when all extensions are disabled?: Yes

[36f77332-8fd8-4344-6c0fe998-b3f9a6ce.dmp.zip](https://github.com/microsoft/vscode/files/4916857/36f77332-8fd8-4344-6c0fe998-b3f9a6ce.dmp.zip)

**Comment by roblourens** [comment]
Can you give some more details? Are you using vscode with the Remote-Containers extension, or trying to run vscode on its own inside a container?

**Comment by magwas** [comment]
In the meantime I have found the cause. The shm memory size was too low. Using --shm-size=512m in the docker command line solved the problem.
