### ISSUE TITLE
Adding the function of reaching the head/tail trough Command+up/down keys

### ISSUE THREAD

**Issue by p5ydn0** [microsoft/vscode#102481]
Thank you very much for all you have done for VSCode; VSCode has helped me a lot. Thank you very much.

When the cell is in edit mode, I can quickly reach the head/tail of the content in the cell by pressing `Command+Up/Down` keys.

But in unselected or command mode, `Command+Up/Down` keys have no effect (just the `up/down` keys to reach the previous or next Cell), I don’t know if you can consider adding the function that I can quickly reach the head/tail of the entire file by pressing `Command+Up Down` keys in unselected and command mode.

Thank you.

**Comment by rebornix** [comment]
If you are using the Jupyter Notebook provided by the Python extension, please file an issue against them. For the native notebook we are shipping in VS Code (Insiders), we already support the keybindings.
