### ISSUE TITLE
Ctrl-V pastes the buffer twice in ipynb

### ISSUE THREAD

**Issue by sergiykhan** [microsoft/vscode#102421]
- VSCode Version: 1.47.0
- OS Version: Windows 10 2004

Steps to Reproduce:

1. Open a file *.ipynb
2. Paste the buffer with Ctrl-V

The buffer will be pasted twice.

**Comment by th3ragex** [comment]
The same happens with Python Interactive window.

![dublepaste](https://user-images.githubusercontent.com/15040273/87355456-b1476580-c560-11ea-8ee1-dd5a1e0486c9.gif)
