### ISSUE TITLE
Pop-under release notes

### ISSUE THREAD

**Issue by dakahler** [microsoft/vscode#102437]
Issue Type: <b>Feature Request</b>

It's great that you're able to constantly update vscode, but the release notes popping up so often is kind of annoying. Sometimes I want to read them, but they shouldn't take precedence over whatever else I was trying to open. It would be great if they opened without that new tab being activated.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

**Comment by joaomoreno** [comment]
Since release notes always open in a new tab, the workaround here is to simply close that tab. 

You can disable automatic release notes showing with the `update.showReleaseNotes` setting.
