### ISSUE TITLE
Remote - SSH plugin is disabled

### ISSUE THREAD

**Issue by adfel70** [microsoft/vscode#102484]
Hi,
Remote - SSH is disabled and commands are not available when pressing F1 (such as Remote-SSH: Connect to Host...)

**Versions:**
Windows_NT x64 10.0.17763
Visual Studio Code 1.41.1
Remote - SSH: Editing Configuration Files 0.51.0
Remote - SSH 0.51.0

OpenSSH client is installed.

Anyone got an idea?
Thanks.

**Comment by roblourens** [comment]
Is the extension actually "disabled" like does it show up as disabled in the extension list? Or do you mean something else?
