### ISSUE TITLE
Change right click and drag to drag the editor

### ISSUE THREAD

**Issue by Destroyer-LDB** [microsoft/vscode#102478]
#Drag Right Mouse to see the whole content of editor
##Commented by Destroyer-LDB
I used to use Code::Blocks to develop C++, but now I use VS Code. I am used to a function of Code::Blocks--drag the right mouse to see the whole content of editor. But VS Code does not support it. I hope VS Code could have it.
*I am sorry that in my last issue of the same name, I didn't give much information.* **As I don't know how to add a video in Github to describe my feature request, I add one to my repository *[my-issue](https://github.com/Destroyer-LDB/my-issue)*. You can find the video named "array.h - Code__Blocks 17.12 2020-07-14 17-37-50.mp4" and I hope you can understand me.**

**Comment by Destroyer-LDB** [comment]
I found how to add a video just now!
Here is the video[array.h - Code__Blocks 17.12 2020-07-14 17-37-50.zip](https://github.com/microsoft/vscode/files/4917963/array.h.-.Code__Blocks.17.12.2020-07-14.17-37-50.zip).

**Comment by alexdima** [comment]
@Destroyer-LDB You can use mouse wheel and shift + mouse wheel to get a very similar behaviour.

**Comment by Destroyer-LDB** [comment]
@alexdima Thank you for telling me! The previous name of this issue may be diffficult to understand, because I am just a middle school student in China and I don't know so much English. Sorry for making you confused!
