### ISSUE TITLE
Show the "Synchronize Changes" button when in a single repository (Source Control)

### ISSUE THREAD

**Issue by lucasbasquerotto** [microsoft/vscode#102499]
It would be great to have the `Synchronize Changes` button alongside the `Commit` and `Refresh` buttons when in a folder with only 1 repository. Currently, the button shows only when there are 2 or more git repositories, like in the images below. 

_Only 1 repository:_

![01](https://user-images.githubusercontent.com/19873627/87437292-7d9e2700-c5c4-11ea-91c2-80f5e54cd477.png)

_More than 1 repository:_

![02](https://user-images.githubusercontent.com/19873627/87437299-80991780-c5c4-11ea-9797-a47d5359bdbd.png)

I use it a lot when pulling and pushing, and although it's not something absolutely needed, I think this should be easy to implement (because it already works where there are more than 1 source control repository, but I can't say for sure).

An alternative solution would be to make the Source Control View works **the same way for a single repository as it works when there are multiple repositories** (could be a setting, similar to `scm.alwaysShowActions` that shows actions that are applied to the repository files, like `Discard All Changes` and  `Stage All Changes`, but in this case a new setting to apply to the repository itself).

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/102118#issuecomment-657592896
