### ISSUE TITLE
Parameter highlighting error

### ISSUE THREAD

**Issue by MicroCBer** [microsoft/vscode#102515]
Issue Type: <b>Bug</b>

Create a Javascript function, defined as
```
function createPullDownMenu(title, onclick, addto_title) {}
```
When you enter createPullDownMenu, the highlight of the input prompt will be marked on the second half of addto_title, as shown in the figure:
![](https://s1.ax1x.com/2020/07/15/UafU4f.png)

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (2.87GB free)|
|Process Argv|C:\IDE|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-rename-tag|for|0.1.4
LiveServer|rit|5.6.1
perl-rename-symbol|utg|0.2.3

</details>

**Comment by mjbvz** [comment]
I'm having trouble reproducing this:

<img width="690" alt="Screen Shot 2020-07-14 at 11 20 04 AM" src="https://user-images.githubusercontent.com/12821956/87461918-f94ba400-c5c3-11ea-86b2-14ca64e3985a.png">

Any additional repo steps?
