### ISSUE TITLE
Can not find name let

### ISSUE THREAD

**Issue by Dangerous-Mind** [microsoft/vscode#102593]
Issue Type: <b>Bug</b>

let in =""; in a ts or tsx returns the message "Can not find name let".

It works ok with other variable other the "in".
It also says the same thing if the variable is "if".

Thanks

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.95GB (3.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
spfx-snippets|eli|1.9.0
vscode-spfx-task-runner|eli|1.2.4
vscode-firefox-debug|fir|2.9.0
vscode-edge-devtools|ms-|1.0.7
powershell|ms-|2020.6.0
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
vscode-spfx-deploy-package|Ren|1.1.0
vscode-scss-formatter|sib|2.0.1

</details>

**Comment by mjbvz** [comment]
The code is invalid since  `in` is a valid operator in JavaScript. Same thing for the `if` keyword
