### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by gbasilveira** [microsoft/vscode#102588]
Issue Type: <b>Performance Issue</b>

I have a DELL XPS which usually allows for a full day battery usage, but today VS Code is using 70%+ of it (according to Windows 10) and drained more than 60% of a full battery in less than an hour.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    84	 12528	code main
    1	    74	 10016	   window (Issue Reporter)
    0	   210	 11972	   window (nodeapi.go - exchange - Visual Studio Code)
    0	    89	 19528	     extensionHost
    0	    32	  1128	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=19528
    0	   163	  1496	       electron_node tsserver.js 
    0	    48	  5540	         electron_node typingsInstaller.js typesMap.js 
    0	    78	  9080	       "C:\Users\Guilherme Silveira\go\bin\gopls.exe" -mode=stdio
    0	     6	  8136	         console-window-host (Windows internal process)
    0	    34	 13612	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=19528
    0	    63	 15924	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=19528
    0	    60	 18232	       electron_node tsserver.js 
    0	    16	 19688	     watcherService 
    0	     6	 19700	       console-window-host (Windows internal process)
    0	    26	 14704	   utility
    1	   163	 18204	   gpu-process
    0	    14	 19548	   electron-crash-reporter
    0	    70	 19824	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (nodeapi.go - exchange - Visual Studio Code)
|    Folder (exchange): 8 files
|      File types: go(3) gitignore(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.15.1
protobuf|kan|1.1.6
mssql|ms-|1.9.0
remote-wsl|ms-|0.44.4

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
