### ISSUE TITLE
VS Code should support the Windows Restart Manager API

### ISSUE THREAD

**Issue by zhuman** [microsoft/vscode#102559]
Apps on Windows should always support the Restart Manager API, which allows Windows to request that the app restore its state automatically in the case of automatic updates. New in Windows 10 version 2004 is a user toggle that enables all system reboots to restart apps, so even user-initiated reboots cause apps to be restored. Full Visual Studio and many other apps support Restart Manager already, but VS Code lags behind, resulting in lost time when rebooting the system to restore potentially many VS Code windows.

**Comment by roblourens** [comment]
I don't know where to send this but it sounds like something you might know about @sbatten

**Comment by sbatten** [comment]
@deepak1556 does electron do anything here?
