### ISSUE TITLE
VS code Freezes when using Flutter

### ISSUE THREAD

**Issue by srineesh** [microsoft/vscode#102587]
Issue Type: <b>Performance Issue</b>

I've been a great fan of VS Code but lately, the editor is getting struck after some usage. It goes blank until i keep the app in the background and after some time it returns to normalcy.

It is even evident when using Zoom/skype and sharing my screen. It becomes frustrating when sharing my screen and suddenly everything freezes.

Please look into this issue.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_45067|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   19	    82	   334	code main
   11	    16	   420	   gpu-process
    0	     0	   517	   utility
    0	  6095	   523	   window (SavedPage.dart — teal-customer-app)
    0	    33	   614	     extensionHost
    0	    16	   673	       electron_node server.js 
    0	     0	   678	       electron_node server.js 
    0	    16	   691	       /Users/saisrineesh/Desktop/flutter/bin/cache/dart-sdk/bin/dart /Users/saisrineesh/Desktop/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.12.2
    0	     0	   693	       bash /Users/saisrineesh/Desktop/flutter/bin/flutter daemon
    0	    16	   720	         /Users/saisrineesh/Desktop/flutter/bin/cache/dart-sdk/bin/dart --packages=/Users/saisrineesh/Desktop/flutter/packages/flutter_tools/.packages /Users/saisrineesh/Desktop/flutter/bin/cache/flutter_tools.snapshot daemon
    0	     0	   840	           /usr/bin/script -t 0 /dev/null xcrun xcdevice observe --both
    0	     0	   841	             /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
    0	     0	   620	     watcherService
    0	     0	 85541	     /bin/zsh -l
   13	    49	   555	   shared-process
    0	     0	 36372	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    82	 36360	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (SavedPage.dart — teal-customer-app)
|    Folder (teal-customer-app): 11739 files
|      File types: class(1261) dex(987) flat(666) xml(453) json(342) jar(276)
|                  txt(240) png(225) len(196) dart(174)
|      Conf files:;
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.0
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
githistory|don|0.6.6
prettier-vscode|esb|5.1.3
todo-tree|Gru|0.0.178
pubspec-assist|jer|1.0.3
vscode-gutter-preview|kis|0.26.2
python|ms-|2020.6.91350
awesome-flutter-snippets|Nas|2.0.4
color-highlight|nau|2.3.0
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.2.0
swdc-vscode|sof|2.2.28
code-spell-checker|str|1.9.0

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
