### ISSUE TITLE
Extension host crashes

### ISSUE THREAD

**Issue by holgerteichgraeberconvoy** [microsoft/vscode#102537]
My extension host crashed and cannot find any extensions. 
I am on OSX and ran 'defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false' in my commandline, after restarting VScode, getting the below error. Did this in order to go right several times in the vim extension using 'l' 

Error received from starting extension host
(anonymous)	@	extensionHostManager.ts:72
extensionHostManager.ts:73 timeout
(anonymous)	@	extensionHostManager.ts:73
lifecycle.ts:134 Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at c.add (lifecycle.ts:134)
    at e._register (lifecycle.ts:164)
    at extensionHostManager.ts:79

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:43:02.577Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.7
githistory|don|0.6.6
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
code-spell-checker|str|1.9.0
vim|vsc|1.15.0

</details>

**Comment by alexdima** [comment]
@holgerteichgraeberconvoy I don't believe the setting `ApplePressAndHoldEnabled` can lead to a crash in the extension host.

Does the extension host crash when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)
