### ISSUE TITLE
Built-in markdown preview & custom command execution

### ISSUE THREAD

**Issue by svsool** [microsoft/vscode#102532]
Hi,

Thanks for working on VSCode and for making it an awesome editor.

I'm working on [this plugin](https://github.com/svsool/vscode-memo/) and had a question what options do I have if I need to execute a custom command in built-in markdown preview on clicking a certain link? I dug into the code and found that it was possible a couple of years ago to execute custom command [using this way](https://stackoverflow.com/questions/45481546/sending-a-command-from-a-virtual-document-in-a-vscode-extension/45494328), but perhaps not anymore. 

Examples:

- Following the link to the note / image works fine both from the text editor and from the preview, which is nice

![1](https://user-images.githubusercontent.com/1452141/87475823-1a48df00-c62e-11ea-99a2-9b080b530435.gif)

- Clicking on a nonexistent link in the text editor will create a new note, whereas preview will just show a tooltip that note can't be created please use text editor. I would like coherent experience between preview and text editor, but apparently there is no way to execute a custom command to create a note on the fly as done via text editor on `cmd + click`. I tried also `<a href="command:_memo.openDocumentByReference?..."` and it did not work, which is not surprising considering [this logic](https://github.com/microsoft/vscode/blob/fdf23dc5f95f4a17b246dbebc9af14dab5043334/extensions/markdown-language-features/src/features/preview.ts#L391-L412)

![2](https://user-images.githubusercontent.com/1452141/87473424-187d1c80-c62a-11ea-9bff-999f6c578a30.gif)

- Clicking on the link to common file type in the text editor for which preview (built-in & on link hover) is not available will open a file in the default app, whereas clicking a link in preview will lead to opening file in VSCode instead of default app. The best I managed for preview in this case is to provide a direct link to the file via html anchor which is consumed by [this api](https://github.com/microsoft/vscode/blob/master/extensions/markdown-language-features/src/features/preview.ts#L411), and openable in VSCode on click. I would like coherent experience between preview and text editor which would allow opening links in preview in the default app by executing a custom command

![3](https://user-images.githubusercontent.com/1452141/87474723-3ba8cb80-c62c-11ea-8e9d-76d40028fa6d.gif)

I found markdown preview secure enough, an excellent job was done there, but as a downside, it reduces the scope of possible use cases.

Do you have some suggestions for me how to handle custom command execution with built-in preview? The idea of building custom preview is not super appealing to me and I find built-in preview good enough except this problem with custom commands execution.

Thank you!

**Comment by mjbvz** [comment]
Yes, we don't enable command links since the markdown content comes from a potentially untrusted workspace

One option to investigate: try adding some custom JavaScript into the markdown preview for your links. Here's the logic the normal VS Code markdown preview uses to handle clicks on links: https://github.com/microsoft/vscode/blob/7099dc0708b3e6c6333641ef162262908ce37a0f/extensions/markdown-language-features/preview-src/index.ts#L154

You should be able to inject your own JavaScript using the  [`markdown.previewScripts`](https://code.visualstudio.com/api/extension-guides/markdown-extension#adding-advanced-functionality-with-scripts) contribution point

Let me know if that works

**Comment by svsool** [comment]
> Yes, we don't enable command links since the markdown content comes from a potentially untrusted workspace
> 
> One option to investigate: try adding some custom JavaScript into the markdown preview for your links. Here's the logic the normal VS Code markdown preview uses to handle clicks on links:
> 
> https://github.com/microsoft/vscode/blob/7099dc0708b3e6c6333641ef162262908ce37a0f/extensions/markdown-language-features/preview-src/index.ts#L154
> 
> You should be able to inject your own JavaScript using the [`markdown.previewScripts`](https://code.visualstudio.com/api/extension-guides/markdown-extension#adding-advanced-functionality-with-scripts) contribution point
> 
> Let me know if that works

Preview script do work and I'm aware of this feature, yet it has no access to API, because `acquireVsCodeApi` gets called before previewScripts executed and `acquireVsCodeApi` can be called only once because it configured so for markdown preview.

> we don't enable command links since the markdown content comes from a potentially untrusted workspace

Could you please explain why? As far as I understand, WebView can be implemented to allow it. Why preview that managed by extension is more untrusted in terms of API access than extension itself? Also external scripts are not permitted until CORS is configured so, that means that the only source of malicious intentions are extensions themselves and they are untrusted by nature, yet they have access to API, but not their WebViews 🤔. Wouldn't list of trusted commands solve this problem?

**Comment by mjbvz** [comment]
Markdown content comes from the workspace and may be untrusted. Extensions have to be installed by a user.

There is currently no concept of trusted commands. Either command uris are enabled, or they are not

**Comment by svsool** [comment]
Thanks for the answer.

> Markdown content comes from the workspace and may be untrusted. Extensions have to be installed by a user.

Workspace has to be opened by user as well and perhaps should be as untrusted as installed extension, yet extension has access to API and webview (preview) doesn't. Also uri should be clicked to lead to any malicious behavior.

> There is currently no concept of trusted commands. Either command uris are enabled, or they are not

I think I understand the thinking behind disabling command uris, but it less obvious for me why access to API disabled from previewScripts. Preview scripts do come with the extension installed by user and I think it should be fine to allow access to API from preview scripts. At least preview script will be controlling which command can be executed instead of untrusted workspace which potentially comes with untrusted command uris. 

Were there related security issues reported in the past?

**Comment by gsmachado** [comment]
Just to let you know that I'm also developing an extension, and this feature would be very handy. 👍

**Comment by mjbvz** [comment]
I'm closing this issue as there's not a good proposal on how to enable this safely and the issue hasn't gotten much interest over the past year
