### ISSUE TITLE
Run code in terminal freezes the VSCode window

### ISSUE THREAD

**Issue by 2504Guimaraes** [microsoft/vscode#102567]
Always when I'm trying to use the integrated terminal in VSCode, to run some code snippet or something else, my window ends up crashing, forcing me to reopen it again or even close it. In other words, my integrated terminal freezes my window if used once or more times. I asked this same question before some time ago, but I didn't understand any answer gave to me, neither figured out how to solve it.  Without any extension installed, it keeps happening, even reinstalling the program this bug persists.

**Comment by daydreamer2469** [comment]
i have a terminal integration too..
Git Bash open more slow than previous version.. and after lastest update i cant use multiple panel.. it didnt load correctly.. below the screenshoot :
![image](https://user-images.githubusercontent.com/68219317/87509918-c4f7e680-c69c-11ea-977e-8d8636bb837a.png)

the right bash is didnt working yet.. anyway i use git v 2.27.0-window.1 and here the visual studio information 
![image](https://user-images.githubusercontent.com/68219317/87510179-48193c80-c69d-11ea-8ccc-8a96e865749c.png)

**Comment by maxeber** [comment]
I am having the same issue, it seems to bug out when I have 2 terminals side by side and when I use some git commands (git push).

**Comment by 2504Guimaraes** [comment]
> I am having the same issue, it seems to bug out when I have 2 terminals side by side and when I use some git commands (git push).

In my case,

**Comment by 2504Guimaraes** [comment]
> I am having the same issue, it seems to bug out when I have 2 terminals side by side and when I use some git commands (git push).

I'm having trouble just by open one single terminal. I needs less than 1 minute to crash everything. As a substitute I'm using repl.it to run snippets and default windows 10 terminal to use git.

**Comment by amagyar** [comment]
I'm having the same issue with bash integrated terminal... The first time I open the terminal it freezes, then it works when I close it and open again. Today, I've noticed that when I was trying to run a java main function it wasn't starting... then I switch to powershell and it was executing.
There are also some other weird issues like when the terminal starts, I have to scroll up to reach the line or the terminal is blank until I type something.
