### ISSUE TITLE
Debugger for Chrome in VSC 1.47 (Bug)

### ISSUE THREAD

**Issue by YagmurG86** [microsoft/vscode#102529]
The Problem is relevant for "June 2020 (version 1.47)". At the Moment i installed the previouse Version and the Bug is not there anymore.

In 1.47 an 1.47.1 debugging was not possible anymore with the extensions "Debugger for Chrome" and "Debugger for Firefox". After the update it didnt work, but after reinstalling 1.46 it perfectly works again.

1) Install VSC 1.47 or 1.47.1
2) Install "Debugger for Chrome"
3) launch.json -> See *1)

*1)
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch index.html",
            "type": "chrome",
            "request": "launch",
            "file": "${workspaceFolder}/Kapitel 6/index.html"
        }
    ]
}
```

4) Start Debugg Mode in VSC (F5)
5) Then Error appears
<img width="425" alt="1" src="https://user-images.githubusercontent.com/68300840/87473389-9ee13080-c621-11ea-9fc3-1faec02e054b.png">

As i said before: If i install version 1.46 and perform the Steps above, everything works fine.

**Comment by connor4312** [comment]
Thanks for the issue, you can set `debug.javascript.usePreview: false` in the meantime to use the old debugger

**Comment by connor4312** [comment]
This will be fixed in the next [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension) released at 5 PM PST.

**Comment by YagmurG86** [comment]
Thanks a lot, `debug.javascript.usePreview = false` works perfectly fine. Debuggin is possible even in VSC 1.47.X
