### ISSUE TITLE
Staging a file removes focus from the message input

### ISSUE THREAD

**Issue by LachlanArthur** [microsoft/vscode#102546]
Issue Type: <b>Bug</b>

1. Stage a file in the git tab.
2. While the git progress bar is running, write a commit message (you'll have to be quick if the repo is small).
3. When the git progress bar finishes, focus is removed from the message input and your typing is lost to the void.

These look like earlier versions of the same bug:
#97727
#92401

VS Code version: Code - Insiders 1.48.0-insider (c828a5339bca7222fd8f56ab98361a98f736d185, 2020-07-14T05:39:53.264Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (13.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by LachlanArthur** [comment]
I was too slow: #102498

Didn't pop up in an initial search because it lacked any mention of git.

**Comment by pvdstel** [comment]
Hey, author of the earlier issue here. I've edited it so that the description now mentions Git, just in case the issue searcher does not search through comments.
