### ISSUE TITLE
Explorer Freezes and Fails

### ISSUE THREAD

**Issue by gatys** [microsoft/vscode#102538]
Issue Type: <b>Bug</b>

In Visual Studio, I was editing several files inside a parent folder. I also had a cmd terminal open (not the integrated terminal, but a seperate terminal) whose current directory was inside the parent folder. In the folder explorer, I clicked on the folder, then pushed F2 to rename the folder. After typing in the new name and pushing enter, the explorer becomes greyed out and unresponsive. The icon and name if the folder I was attempting to rename also disapears, although all sub folders are still visible.  The only way to restore the explore is to restart VS code. Upon doing so, everything returns to normal, and the parent folder retains the name it had before the attempted name change. 

For reference, under the same conditions, whenver I attempt to change the parent folder name in File Explorer, I am prompted with a dialog box that says that the folder is in use by another program and that the name cannot be changed. The dialog also has a try again and cancel button.

VS Code version: Code - Insiders 1.48.0-insider (c828a5339bca7222fd8f56ab98361a98f736d185, 2020-07-14T05:39:53.264Z)
OS version: Windows_NT x64 10.0.20161

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (8.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
json-pretty-printer|eus|1.1.0
vscode-guid|hea|1.4.20
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
cpptools|ms-|0.28.3
hexeditor|ms-|1.1.0
material-icon-theme|PKi|4.2.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
I can not reproduce this.
Can you please provide exact reproducable steps for this.
