### ISSUE TITLE
Working examples of text messages, hover and editors with readonly html

### ISSUE THREAD

**Issue by tylerl0706** [Microsoft/vscode#10250]
I'm wanting to get in to VSCode extension development but I've having a really tough time using some of the APIs without working examples or at least code snippits. I don't see the mapping from the documentation to the code. 

I want to try and use Hovers but I haven't been able to locate any working examples anywhere. Where might I find working examples or code snippits of this and if it doesn't exist can such a thing be added to the documentation?

**Comment by jrieken** [comment]
There is API doc here: https://code.visualstudio.com/docs/d?utm_expid=101350005-20.jAsCkEFcTeqvtdr0STCN9g.3&utm_referrer=https%3A%2F%2Fcode.visualstudio.com%2Fb

Then there is a sample repo here: https://github.com/Microsoft/vscode-extension-samples

Last there a few language extension inside our repo and outside that serve as good samples:

* https://github.com/Microsoft/vscode-go
* https://github.com/OmniSharp/omnisharp-vscode
* https://github.com/Microsoft/vscode/tree/master/extensions/typescript

**Comment by tylerl0706** [comment]
@jrieken: can Hovers be used without specifying the languages? 

For example, a Hover shows up when the cursor is on top of a specific word.

**Comment by jrieken** [comment]
Yes - just use the any-selector (`*`) when [registering](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3730)
