### ISSUE TITLE
event.affectsConfiguration scoping doesn't behave as expected

### ISSUE THREAD

**Issue by EcksDy** [microsoft/vscode#102591]
- VSCode Version: 1.46.1
- OS Version: Windows_NT x64 10.0.18363
- Extension supports engine version ^1.42, specifically to use that functionality

I'm trying to check where the configuration changed(User/Workspace settings). Following the [API](https://code.visualstudio.com/api/references/vscode-api#ConfigurationChangeEvent), I expected that if I provide the workspace folder I'm currently in it will scope the affectsConfiguration check to that specific workspace. 
What actually happens is, if the config was changed in either User/Workspace both checks will return true.

```ts
workspace.onDidChangeConfiguration((event: ConfigurationChangeEvent) => {
  const updated = event.affectsConfiguration(`${EXTENSION_PREFIX}.config.name`);
  const updatedInWorkspace = event.affectsConfiguration(
    `${EXTENSION_PREFIX}.config.name`,
    (workspace.workspaceFolders as WorkspaceFolder[])[0].uri,
  );

  if (updated && updatedInWorkspace)
    window.showInformationMessage('Config was updated in workspace settings');
  else if (updated)
    window.showInformationMessage('Config was updated in global settings');
});
```
Desired outcome:

1. Set up an onDidChangeConfiguration listener(see code above).
2. Change the observed config in User settings.
3. Get 'Config was updated in global settings' message.
4. Change the observed config in Workspace settings.
5. Get 'Config was updated in workspace settings' message.

What happens:

1. Set up an onDidChangeConfiguration listener(see code above).
2. Change the observed config in User settings.
3. Get 'Config was updated in workspace settings' message.
4. Change the observed config in Workspace settings.
5. Get 'Config was updated in workspace settings' message.

**Comment by sandy081** [comment]
Documentation says following:

``` ts
/**
 * Returns `true` if the given section is affected in the provided scope.
 *
 * @param section Configuration name, supports _dotted_ names.
 * @param scope A scope in which to check.
 * @return `true` if the given section is affected in the provided scope.
 */
affectsConfiguration(section: string, scope?: ConfigurationScope): boolean;
```

> Returns `true` if the given section is affected in the provided scope 

It means that the given section has changed and impacts the resources provided in the given scope.  This is nothing to do with the change in workspace settings 

I will update the doc to make it clear.

**Comment by sandy081** [comment]
updated doc

```
/**
		 * Checks if the given section has changed.
		 * If scope is provided, checks if the section has changed for resources under the given scope.
		 *
		 * @param section Configuration name, supports _dotted_ names.
		 * @param scope A scope in which to check.
		 * @return `true` if the given section has changed.
		 */
		affectsConfiguration(section: string, scope?: ConfigurationScope): boolean;
```

**Comment by EcksDy** [comment]
I have to admit it took me a while to understand what you mean. The naming can be confusing since it's `ConfigurationChangeEvent`, and the method name implies we're checking that it affects **configuration**, not the resources.  

So the scope isn't there to check the **source** of the configuration change, it's there to check if the provided **resources** are affected. 

The expected behavior that I understand from your explanation:
1) `config.name` value is changed in workspace settings.
2) `event.affectsConfiguration('config.name', (workspace.workspaceFolders as WorkspaceFolder[])[0].uri);` will return true, since the resources in the workspace folder are impacted by that change.
3) `config.name` value is changed in global settings.
4) `event.affectsConfiguration('config.name', (workspace.workspaceFolders as WorkspaceFolder[])[0].uri);` will return false, since the resources in the workspace folder are NOT impacted by that change anymore, since the workspace settings will override the global config.


Checked it, and it works, thank you :)
