### ISSUE TITLE
Commands from extensions cannot be executed using keybindings, when terminal is focused

### ISSUE THREAD

**Issue by Pand9** [microsoft/vscode#102500]
- VSCode Version: 1.48.0-insider & 1.47.0
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Follow the instructions to setup a template extension workspace: https://code.visualstudio.com/api/get-started/your-first-extension
2. Setup a keybinding to a command originating from extension:
    {
        "key": "f9",
        "command": "extensionName.helloWorld"
    },
3. Press F9 in editor window to confirm that keybinding works in editor.
4. Press F9 in terminal window to reproduce that keybinding doesn't work in terminal. Bash / default will do; I've also tested with another Jupyter-based terminal.
5. Press F3 (to open search) to see that non-extension originating keybindings work.

Expected behavior is that keybindings should work in terminals, whether they are originating from extension or not.
Or, at least, this behavior should be documented.

Does this issue occur when all extensions are disabled?: Yes (all except the one)

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/docs/editor/integrated-terminal#_forcing-key-bindings-to-pass-through-the-terminal

**Comment by Pand9** [comment]
@gjsjohnmurray Thanks!
