### ISSUE TITLE
`source.organizeImports` doesn't respect tsconfig `noUnusedLocals`

### ISSUE THREAD

**Issue by wayou** [microsoft/vscode#102590]
Issue Type: <b>Bug</b>

VSCode config：

```json
...
"editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
...
```

tsconfig:

```json
{
  "compilerOptions": {
    "noUnusedLocals": false,
  }
}
```

unsed imports are removed when saving code.

VS Code version: Code - Insiders 1.48.0-insider (cb31fc6ce2b4da3520392b622aa3ebc5b313533b, 2020-07-15T05:31:08.767Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|-psn_0_3924926|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
This is the current design of the organize imports feature. If you have feedback on this, please [file an issue upstream](https://github.com/microsoft/TypeScript/issues/new/choose) against typeScript
