### ISSUE TITLE
After left panel tree view delete, focus should go on the last file or the file that took its place

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#1025]
Selecting and deleting `c` in this file structure:
- `a`
  - `b`
  - `c`
  - `d`

Currently will move focus to `a`. I would expect this to move focus to `d` to allow multiple deletes in quick succession, so `delete`, `delete`, `delete` could be used to remove all of `a`'s files before focus is moved to `a`.

**Comment by bpasero** [comment]
@Tyriar but how would that work if you have files open in a stack? Currently when you click the file it opens the file and when you delete it shows the one next on the stack.

**Comment by Tyriar** [comment]
Things have changed a little since I filed this but the behavior described is still the same when the deleted file is *not* open.

1. Open some file `a`
2. <kbd>shift</kbd>+<kbd>ctrl</kbd>+<kbd>e</kbd> to focus the explorer
3. Navigate to some file `b` without pressing <kbd>enter</kbd> to activate it
4. <kbd>delete</kbd>, notice focus goes to build instead of one b's closest sibling, it's a little disorienting

So currently it doesn't focus the next file in the stack on the explorer, it opens the next file in the stack in the editor but focuses the parent of the deleted file in the explorer.

---

Related to this, performing multiple actions with the keyboard within the explorer would probably be easier if we could turn off the auto-focus of the editor (I think it used to be like this) #7257. This coupled with #1023 and #7258, it would be convenient to do some real file/directory manipulation from within VSCode.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

PRs that fix are welcome
