### ISSUE TITLE
Consider to use `git ls-files' for file search if possible

### ISSUE THREAD

**Issue by phmx** [Microsoft/vscode#10251]
For quick file lookup in a very large code base under git VCS it is beneficial to use `git ls-files' command. It's fast because it doesn't need to read directory entries to traverse project's structure. It won't show files which are not in git's index, so for completeness this method must be combined with slower recursive file tree walk.

**Comment by chrmarti** [comment]
I don't like the added complexity this would introduce. Let's add it to our list of ideas for #55. Closing as duplicate.
