### ISSUE TITLE
issues with pasting in .ipynb files

### ISSUE THREAD

**Issue by dxt48** [microsoft/vscode#102535]
Issue Type: <b>Bug</b>

When pasting a copied piece of code, it gets pasted twice. 

For example: I want to copy and paste 

round(df.describe(),2)

I hit Ctrl+C, move the curser where I want to paste, and hit Ctrl+V. The result is:

round(df.describe(),2)round(df.describe(),2)

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:44:14.582Z)
OS version: Windows_NT ia32 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (23.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.6.91350

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate (ironically) and will be fixed in upcoming recovery release
