### ISSUE TITLE
SCSS built-in color picker hides itself before one can use it

### ISSUE THREAD

**Issue by dkent600** [microsoft/vscode#102599]
Issue Type: <b>Bug</b>

1. In an .scss file (I haven't tried .css), hover the mouse over a color specification.  Note the color picker is displayed.
2. move the mouse towards the color picker.

**RESULT**:
The color picker disappears as soon as the mouse leaves the color specifier.

**EXPECT**:
The color picker should not disappear and should allow me to use it.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (7.24GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/dkent/Documents/Projects/GitHub/DAOStack/alchemy|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
markdown-preview-github-styles|bie|0.1.6
path-intellisense|chr|2.2.1
vscode-eslint|dba|2.1.7
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
vscode-pull-request-github|Git|0.18.0
vscode-react-typescript|inf|1.3.1
search-editor-apply-changes|jak|0.1.1
graphql-for-vscode|kum|1.15.3
remote-wsl|ms-|0.44.4
powershell|ms-|2020.6.0
typescript-javascript-grammar|ms-|0.0.53
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|sib|2.0.1
vscode-open-in-github|sys|1.14.0
shell-launcher|Tyr|0.4.1
gitblame|wad|4.1.0

</details>

**Comment by aeschli** [comment]
You need to hover over the color value, not the box. Is that what you do?

**Comment by dkent600** [comment]
> You need to hover over the color value, not the box. Is that what you do?

Yes, and I see the palette, just can't use it.
