### ISSUE TITLE
Should `debug.openDebug` default to `openOnFirstSessionStart`?

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#102556]
See: https://github.com/microsoft/vscode-js-debug/issues/598#issuecomment-658530825

I think that `openOnFirstSessionStart` is a better default. Or maybe at least `openOnSessionStart` should only apply to top level sessions.

cc @weinand @isidorn

**Comment by gjsjohnmurray** [comment]
@connor4312 based on what you wrote in the linked issue aren't you proposing the default becomes `openOnFirstSessionStart`?

**Comment by connor4312** [comment]
Oops, yes :)

**Comment by isidorn** [comment]
Yeah I like this change. We can do it start of next milestone to gather feedback.
Also assigning to me and to August.

**Comment by isidorn** [comment]
Actually I did this change couple of days ago, thus assigning to July and closing.
Code pointer https://github.com/microsoft/vscode/blob/5696babbc1dce41788bae04b1a04ad35140bebfb/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L232

**Comment by isidorn** [comment]
To verify.

1. Make sure you do not have `debug.openDebug` in your settings
2. Start debugging -> make sure debug viewlet gets opened
3. Stop debugging. Close debug viewlet (open exporer, or close sidebar)
4. Start debugging -> make sure debug viewlet does **not** get openet
