### ISSUE TITLE
"ext install" installed unrelated extension?

### ISSUE THREAD

**Issue by colemickens** [microsoft/vscode#102540]
- VSCode Version: **VSCodium** 1.46.1
- OS Version: linux x64 5.7.8

Steps to Reproduce:

~~1. Look for "Asciidoctor" in the extensions.~~
~~2. It's not there for some reason **bug 1**.~~
~~3. Try to manually install.~~
4. Ctrl-P
5. Paste "ext install asciidoctor.asciidoctor-vscode"
6. "Language Support for Java(TM)" started installing **bug 2**

edit: The lack of "Asciidoctor" is due to using VSCodium, and Asciidoctor not (yet) existing in Open-VSX.org.

**Comment by roblourens** [comment]
Strange, this works for me. Could you share a screenshot or two to help explain where the problem comes in?

Do you see this?

![image](https://user-images.githubusercontent.com/323878/87485096-d2ee2e80-c5ec-11ea-8f7d-25f5f2ea0c0d.png)

Followed by this?

![image](https://user-images.githubusercontent.com/323878/87485119-dbdf0000-c5ec-11ea-8992-9c1d599383b1.png)

Or at what point do you see it installing Java?

**Comment by roblourens** [comment]
> 1. Look for "Asciidoctor" in the extensions.
> 2. It's not there for some reason bug 1.

And I'm guessing it's just not installed at this point

**Comment by colemickens** [comment]
Correct, it's not already installed :). 
![output](https://user-images.githubusercontent.com/327028/87485257-3aa47980-c5ed-11ea-894a-1c9c9dafd9d7.png)

I probably should have said that I'm using VSCodium. 

Here's a video of a full repro: https://youtu.be/-ipK_A9Q4No

**Comment by colemickens** [comment]
>According to the VS Code Marketplace Terms of Use, you may only install and use Marketplace Offerings with Visual Studio Products and Services. For this reason, VSCodium uses open-vsx.org, an open source registry for VS Code extensions. See the Extensions + Marketplace section on the Docs page for more details.

Right. I forgot.

But still, I don't know why the Java extension was installed.

**Comment by roblourens** [comment]
This is VSCodium, not vscode, we don't support it

**Comment by colemickens** [comment]
I doubt that Codium inserted code to mistakenly install extensions it
wasn't instructed to, but okay.

**Comment by colemickens** [comment]
Sorry... thanks for triaging Rob. So far this doesn't repro in Code,
apologies for wasting your time.
