### ISSUE TITLE
i cant sava any project 

### ISSUE THREAD

**Issue by abdasd** [microsoft/vscode#102545]
when i come to save my project or file the program get stopped working i cant choose the place of savig i cant do any thing  please help me :( 
here video to more deitals https://www.mediafire.com/file/4bc0lwhu87769i9/screen_recorder_video_2020_02_7_17_07_52.mp4

**Comment by roblourens** [comment]
So it looks like vscode hangs as soon as the file save dialog opens, is that basically right?

**Comment by abdasd** [comment]
> So it looks like vscode hangs as soon as the file save dialog opens, is that basically right?

when i come to save file and choose the place of save

**Comment by bpasero** [comment]
@abdasd are you using Linux with Snap?

**Comment by abdasd** [comment]
> @abdasd are you using Linux with Snap?

no i use win 64bit

**Comment by bpasero** [comment]
Does it reproduce if you configure `"files.simpleDialog.enable": true` in settings?
