### ISSUE TITLE
Ctrl+Shift+F is not consistent with mouse click behavior

### ISSUE THREAD

**Issue by lborgman** [microsoft/vscode#102595]
Issue Type: <b>Bug</b>

If I click on the search icon corresponding to Ctrl+Shift+F it shows the seach panel (and focuses the search field) or toggles it.

When I instead use Ctrl+Shift+F it never toggles the search panel.

I think it should toggle search panel if focuse is already in the search field.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.19041

**Comment by roblourens** [comment]
Many people use this keybinding to toggle focus between the editor and the search viewlet, and I don't want to mess with it now. You can use ctrl+b to toggle the sidebar.
