### ISSUE TITLE
Copy breaks when trying to replace 3 instances of a string using CTRL + D

### ISSUE THREAD

**Issue by shah-sid-cutshort** [microsoft/vscode#102516]
Issue Type: <b>Bug</b>

while using ctrl + d to highlight and select matching strings , if the total selected instances are 3 , replacing the instances with a string that is already copied on clipboard using ctrl + v results in unexpected behaviour.

To reproduce the issue - 
highlight and select 3 instances of any matching string using ctrl + d.
try to replace it by any other string using ctrl + v.
It breaks.
It works if the instances is not 3 in number.
It only breaks if the quantity is 3.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:30:34.302Z)
OS version: Linux x64 5.0.0-38-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 2|
|Memory (System)|7.63GB (1.26GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.7
vscode-elasticsearch-snippets|dee|1.1.0
githistory|don|0.6.6
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
auto-close-tag|for|0.5.8
json2ts|Gre|0.0.6
AngularMaterial|har|7.0.1
vscode-mocha-test-adapter|hbe|2.6.2
vscode-test-explorer|hbe|2.19.1
rest-client|hum|0.24.1
docthis|joe|0.7.1
Angular2|joh|9.1.2
dotenv|mik|1.0.1
mongodb-vscode|mon|0.0.4
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
vscode-typescript-tslint-plugin|ms-|1.2.3
typescript-hero|rbb|3.0.0
ruby|reb|0.27.0
vscode-yaml|red|0.8.0
es6-mocha-snippets|spo|0.2.2
python|tht|0.2.3
vscode-ruby|win|0.27.0

</details>

**Comment by roblourens** [comment]
Can you include a screenshot or a better description of what happens when "it breaks"? Works for me
