### ISSUE TITLE
Cannot use Array.includes() in base/platform?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#102566]
What is the reasoning behind not allowing `Array.includes` via the Monaco standalone editor checks? It seems to be valid ES6 when I look at where it is defined:

https://github.com/microsoft/vscode/blob/4855013f5e971b94ffd4a6816446c717c82ff29a/node_modules/typescript/lib/lib.es2016.array.include.d.ts#L27

**Comment by jrieken** [comment]
idk - requires at least edge 14, unsure what our edge minimum version is: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility

**Comment by alexdima** [comment]
Looking at the compat tables, I think it should be safe to use it. I guess it must have been a left-over from the IE era. I don't remember adding any rule like this, so I don't know where to begin looking to remove it.

Leaving it to you @jrieken .

**Comment by bpasero** [comment]
@jrieken @alexdima I opened https://github.com/microsoft/vscode/pull/105404 to do this and it has the advantage that we can get rid of another `d.ts` file in our `typings` folder which actually even seems to have the wrong signature compared to TS.

According to caniuse.com, Edge 13 has very low usages and Edge 14 is out since 2016:

![image](https://user-images.githubusercontent.com/900690/91282196-515ff380-e789-11ea-828c-094244840b11.png)

**Comment by jrieken** [comment]
> we can get rid of another d.ts file in our typings folder (lib.array-ext.d.ts) which actually even seems to have the wrong signature compared to TS.

Unsure how `Array#includes` and `lib.array-ext.d.ts` are connected. Or is this two clean-ups in one? I have added the latter because for the longest time there was a TS bug which would remove type info from arrays after checking `isArray` E.g

```ts
let a: number[] | undefined;
if(Array.isArray(a)) {
  a[0] // infered as any, not number...
}
``` 

If that's now fixed, I am very happy with removing `array-ext`

**Comment by bpasero** [comment]
@jrieken ah good to know, I just checked both in our code and the playground and I see that this no longer seems to be the case:

![image](https://user-images.githubusercontent.com/900690/91293149-d94cfa00-e797-11ea-997f-42fee05dbc4c.png)

I will go ahead and merge my PR then.

**Comment by jrieken** [comment]
🚢 it
