### ISSUE TITLE
Disable plugin update notification

### ISSUE THREAD

**Issue by Pand9** [microsoft/vscode#102509]
I'd like to be able to temporarily disable plugin update notification, this one here:
![image](https://user-images.githubusercontent.com/2797779/87449115-0c2e9a80-c5fd-11ea-942b-347a0f80000d.png)

The use-case is that I'm managing someone else's VS Code instance, and there is some compatibility problem between our code and newest version of ms-python. I don't want them to be prompted to update against my recommendation.

**Comment by sandy081** [comment]
/duplicate

Seems similar to this issue - https://github.com/microsoft/vscode/issues/79689 

Please reopen it if you do not think so
