### ISSUE TITLE
Code completion is adding extra single quote when writing comments

### ISSUE THREAD

**Issue by erictraut** [Microsoft/vscode#10259]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Open a ".ts" or ".tsx" file.
2. Create a new comment and start typing. Include a word that includes an apostrophe like "we're". Note that VSCode inserts an extra single quote after the insertion cursor. This is a recent regression. It didn't do this in previous builds.

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/10068
