### ISSUE TITLE
ctrl+shift+e doesn't work

### ISSUE THREAD

**Issue by Alex69rus** [microsoft/vscode#102571]
Issue Type: <b>Bug</b>

After last update ctrl+shift+e combination was broken.
Now this combination start typing underlined letters.
Before updates this combination was opening Explorer.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-14T00:13:57.513Z)
OS version: Linux x64 4.15.0-109-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3819)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|31.06GB (20.49GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
dotnet-test-explorer|for|0.7.3
go|gol|0.15.1
todo-tree|Gru|0.0.178
csharpextensions|jch|1.3.1
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.13
Kotlin|mat|1.7.1
vscode-docker|ms-|1.3.1
csharp|ms-|1.22.1
quicktype|qui|12.0.46
vscode-icons|vsc|10.2.0
vscode-proto3|zxh|0.4.2

</details>

**Comment by popsu** [comment]
I had the same problem.

Setting the environment variable: `GTK_IM_MODULE="xim"` before runninvg VS Code fixed it for me. See https://github.com/Microsoft/vscode/issues/72642#issuecomment-485951777

**Comment by roblourens** [comment]
Can you confirm whether it is the same issue as the linked one @Alex69rus?

**Comment by Alex69rus** [comment]
Yes. It is the same issue.
Fix from @popsu helped.
Thanks!
