### ISSUE TITLE
markdown code block should be able to highlight new installed language

### ISSUE THREAD

**Issue by timepp** [microsoft/vscode#102548]
I wrote a new language syntax highlight extension (named `wincmd`) to highlight windows command line output. But after I installed the extension, following code block in markdown file doesn't highlight
```
       ```wincmd
       c:\>dir
       ```
```

**Comment by mjbvz** [comment]
See https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example for how your extension can add this using an injection grammar. No short term plans to do this automatically for all languages
