### ISSUE TITLE
Python Virtualenv not activated correctly in debug run

### ISSUE THREAD

**Issue by danlester** [microsoft/vscode#102519]
- VSCode Version: 1.47.1
- OS Version: Mac OS 10.15.5

I don't have the same problem if I downgrade to version 1.46.1.

I'm using Python 2020.6.91350 on both versions of VSCode

Steps to Reproduce:

1. Run Python module debug
2. Cannot find modules expected within the chosen virtualenv

The launch.json entry is like this:
```
        {
            "name": "Hub Local",
            "type": "python",
            "request": "launch",
            "module": "jupyterhub.app",
            "args": [
                "-f",
                "./examples/local_process_spawner.py",
                "--log-level=DEBUG"
            ],
            "justMyCode": false,
            "cwd": "${workspaceFolder}"
        }
```

There is a selected virtualenv for the project.

Under version 1.46 the Terminal output reads as expected: 
```
bash-5.0$ source /Users/dan/.virtualenvs/cdslive/bin/activate
 env /Users/dan/.virtualenvs/cdslive/bin/python /Users/dan/.vscode/extensions/ms-python.python-2020.6.91350/pythonFiles/lib/python/debugpy/launcher 53522 -- -m jupyterhub.app -f ./examples/local_process_spawner.py --log-level=DEBUG 
```

But under version 1.47, for some reason these entries appear the wrong way round (which doesn't make sense, and would explain why the virtualenv isn't correctly activated, and thus the Python modules are not found):

```
bash-5.0$ env /Users/dan/.virtualenvs/cdslive/bin/python /Users/dan/.vscode/extensions/ms-python.python-2020.6.91350/pythonFiles/lib/python/debugpy/launcher 53522 -- -m jupyterhub.app -f ./examples/local_process_spawner.py --log-level=DEBUG 
source /Users/dan/.virtualenvs/cdslive/bin/activate
```

Does this issue occur when all extensions are disabled?: N/A (requires Python extension)

Thank you for any help!

**Comment by brainbrian** [comment]
I'm having a very similar issue between 1.46 and 1.47 in a node-based project where my debugger no longer works and the project won't properly start up.

**Comment by brainbrian** [comment]
I resolved this by changing my `type` to `node-terminal` and changing some of the props from here in the config based on the warnings.
https://github.com/microsoft/vscode-js-debug/blob/master/OPTIONS.md

I have to now use `command` in replacement of `runtimeExecutable`, `args`, `restart` and `console`.
