### ISSUE TITLE
In settings, "keyboard.dispatch" is not working now.

### ISSUE THREAD

**Issue by ataihei** [microsoft/vscode#102570]
Issue Type: <b>Bug</b>

In some cases certain keyboard shortcuts cannot be used in a Japanese environment, depending on the keyboard layout you are using.
I'm currently using a US Layout keyboard, and as a result, I'm not able to use the `` Ctrl + ` `` I can't use shortcuts.
When I use the keybindings settings dialog and type `` Ctrl + ` ``, I get the message "ctrl +unknown" is displayed and not recognized as `` ` ``.

I guess that's because it's a special key.
`` Alt + ` `` and `` Ctrl + ` `` are used to switch the input method in Japanese environment. 

In the past, this was handled by changing `"keyboard.dispatch": "code"` to `"keyboard. dispatch": "keyCode"`, but I just tried this setting and the setting itself is no longer existing now.

Could you please revive the settings or resolve these issues?

Thank you for your help.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (20.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf-hint|han|0.1.0
rainbow-csv|mec|1.7.0
render-crlf|med|1.5.3
vscode-docker|ms-|1.3.1
vscode-language-pack-ja|MS-|1.47.3
csharp|ms-|1.22.1
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
powershell|ms-|2020.6.0
typescript-javascript-grammar|ms-|0.0.53
markdown-all-in-one|yzh|3.1.0
json|Zai|1.0.4

</details>

**Comment by roblourens** [comment]
Seems like that setting still exists to me, are you sure it is set correctly?

**Comment by ataihei** [comment]
In my environment, it doesn't appear to exist as shown in following gif.
![NotAvailable](https://user-images.githubusercontent.com/10428970/87621007-db647780-c75a-11ea-8894-a329d294e36d.gif)

Is there something wrong with my response?

**Comment by roblourens** [comment]
Apparently that setting is only valid for Linux and Mac

**Comment by ataihei** [comment]
Thanks for the answer. That seems to be exactly this case.

Also, I noticed that the same problem was raised in  https://github.com/Microsoft/vscode/issues/63659. I'm sorry for the duplication.
It seems that the OS is reserved for IME and cannot be used.

I'll vote issues that were presented in the suggestions.

**Comment by roblourens** [comment]
Thanks for finding that issue
