### ISSUE TITLE
When using F5 to start debugging, it no any response

### ISSUE THREAD

**Issue by MrSmallLiu** [microsoft/vscode#102568]
- VSCode Version: 1.47.11
- OS Version: Win10

my launch.json:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Egg Debug",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "debug",
                "--",
                "--inspect-brk"
            ],
            "console": "integratedTerminal",
            "restart": true,
            "protocol": "auto",
            "port": 9229,
            "autoAttachChildProcesses": true
        },
        // {
        //     "type": "node",
        //     "request": "launch",
        //     "name": "Egg Test",
        //     "runtimeExecutable": "npm",
        //     "runtimeArgs": [
        //         "run",
        //         "test-local",
        //         "--",
        //         "--inspect-brk"
        //     ],
        //     "protocol": "auto",
        //     "port": 9229,
        //     "autoAttachChildProcesses": true
        // },
        // {
        //     "type": "node",
        //     "request": "attach",
        //     "name": "Egg Attach to remote",
        //     "localRoot": "${workspaceRoot}",
        //     "remoteRoot": "/usr/src/app",
        //     "address": "localhost",
        //     "protocol": "auto",
        //     "port": 9999
        // }
    ]
}
```

my terminal output:

![image](https://user-images.githubusercontent.com/26038018/87508707-967d0a00-c6a2-11ea-9859-6f552eadf027.png)

my developer tools:

![image](https://user-images.githubusercontent.com/26038018/87508772-b14f7e80-c6a2-11ea-8350-764edfea03e9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
I'm not sure I completely understand the issue you're facing. What do you mean by "it no any response"?

**Comment by MrSmallLiu** [comment]
I can start the project with debug(F5) on vscode 1.46.1. 
the terminal oupt:
![image](https://user-images.githubusercontent.com/26038018/88121248-c030b680-cbf7-11ea-854c-04e90539d68f.png)
but no any response on vscode 1.47.1. It disconnect debug after debugger attache. I don't have any operations and it just disconnected itself

**Comment by connor4312** [comment]
Ok, thanks for the issue. I see you're running npm scripts in the terminal on windows, so I think your issue is the same as https://github.com/microsoft/vscode-js-debug/issues/645#issuecomment-662579968

/duplicate
