### ISSUE TITLE
Not able to see debug console log after update VSCode

### ISSUE THREAD

**Issue by tgs-vaibhav** [microsoft/vscode#102563]
Issue Type: <b>Bug</b>

It was working fine till the previous version of VSCode. Since I updated to the latest version it stops displaying debug console details in section.
Can you please help me with a workaround, It is difficult to run and debug together and find code issues.

![image](https://user-images.githubusercontent.com/15323915/87506460-f797e400-c688-11ea-9528-b0a62fa258b0.png)

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6098P CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (5.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-booster|sbu|14.0.1
code-spell-checker|str|1.9.0

</details>

**Comment by roshangupta07** [comment]
Facing same issue, debug console log working with node v12.11.1, but not with other version

**Comment by jameslh** [comment]
I had this issue with node versions v11.9.0 and v12.18.2 although I'm not sure it's specific to the node version.

I was able to resolve by adding `"outputCapture": "std"` to my launch config.

**Comment by connor4312** [comment]
Thanks for the issue! Can either @tgs-vaibhav, @roshangupta07, or @jameslh collect a trace log using these instructions?

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com
