### ISSUE TITLE
"windows cannot find 'null'.Make sure you typed the name correctly,and try agin." error.

### ISSUE THREAD

**Issue by kidus-feleke** [microsoft/vscode#102528]
We have written the needed data into your clipboard because it was too large to send. Please paste
Issue Type: <b>Bug</b>

hello, my Vs code shows me this error "windows cannot find 'null'.Make sure you typed the name correctly, and try again." .when I open my HTML file with live server extension. The problem started to occur when I just started to explore how git works, I'm not sure if it's something I did or if it has anything to do with git but I've tried reinstalling the extension and even the software itself but the error still shows... I can't preview my code on my browser. Is there anything I can do, please??

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.7
vscode-html-css|ecm|0.2.3
beautify|Hoo|1.5.0
rest-client|hum|0.24.1
vscode-language-babel|mgm|0.0.29
python|ms-|2020.6.90262
LiveServer|rit|5.6.1
quokka-vscode|Wal|1.0.307

</details>
e.

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?
