### ISSUE TITLE
Debugger 1.47.1 no longer launches single node jest session, seems to truncate the string

### ISSUE THREAD

**Issue by scottdickerson** [microsoft/vscode#102597]
**Describe the bug**
After the upgrade, this launch.json single file debug configuration never launches the debugger. it seems like somehow the string being passed to the terminal is getting truncated as the debugger process never launches.  And inside the terminal it is as if the enter is never pressed to submit the debug command

This is what the terminal looks like after the debug command is issued:
![image](https://user-images.githubusercontent.com/6663002/87549785-d8428c00-c673-11ea-8dae-ebadac0cf33a.png)

If I press enter in the terminal, it attempts to submit the truncated command, but since it's not complete it fails

**To Reproduce**
Try this launch.json with the latest vscode
```  {
      "type": "node",
      "runtimeVersion": "12.18.2",
      "request": "launch",
      "name": "Jest Current File",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "args": ["${fileBasenameNoExtension}", "--config", "jest.config.js", "--detectOpenHandles"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "env": { "NODE_ICU_DATA": "node_modules/full-icu", "TZ": "America/Chicago" },
      "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest"
      }
    }
```

**Log File**

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4925444/vscode-debugadapter-0.json.gz)

**VS Code Version:** 
1.47.1

**Comment by connor4312** [comment]
@Tyriar any idea what's happening here?

**Comment by scottdickerson** [comment]
a little more info, I seem to be able to get it to work again if I remove this from the launch.json
` "console": "integratedTerminal",`

**Comment by scottdickerson** [comment]
another bit of info, I'm on a Mac and have zsh installed

**Comment by Tyriar** [comment]
My guess is some oh-my-zsh plugin issue. You can use trace logging to see if the shell is sending instructions to do that weird wrapping which is probably is https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
