### ISSUE TITLE
Built-in XSLT extension has 'brackets' setting that prevents bracket-matching for embedded XPath 1.0-3.1

### ISSUE THREAD

**Issue by pgfearo** [microsoft/vscode#102584]
- VSCode Version: 1.47
- OS Version: All

Steps to Reproduce:

Write language extension for 'xsl' that tokenizes XSLT and XPath. Bracket-matching for brackets {}, [], and () cannot be made to work regardless of `brackets` setting. Assumption is that this is because of the 'brackets' setting in VSCode's `vscode/extensions/xml/xsl.language-configuration.json` overriding a more useful `brackets` setting in an external extension.

Does this issue occur when all extensions are disabled?: No, it just prevents XSLT language extensions working properly.

Proposed options to fix:
1. (preferred by OP) Remove built-in XSLT language support as this actually only provides generic XML syntax highlighting and prevents VS Code users being made aware that XSLT language support is available in an extension.

2. (less disruptive) Keep built-in XSLT language support but fix brackets setting to be:

```
	"brackets": [
		["{", "}"],
		["[", "]"],
		["(", ")"]
	],
```

Instead of the existing (intended for XML tags):

```
	"brackets": [
		["<", ">"]
	]
```

**Comment by aeschli** [comment]
Ok to add {}, () and []. But XSLT also has a XML syntax. Why remove "<", ">" ?

**Comment by pgfearo** [comment]
It would help to remove "<",">" because these character's can't be nested like the other bracket characters I listed. Therefore, from my perspective as an XSLT developer, they aren't really that useful as there's no ambiguity about what XML tag your cursor is within.

Also, auto-completion snippets (see screenshot) are likely to be used frequently by XSLT extensions like mine. The faint vertical-lines in these snippets are less likely to be seen clearly with the added noise of the "<",">" bracket-highlighting.
![snippets](https://user-images.githubusercontent.com/2734234/87659794-f8e31280-c755-11ea-8923-85fa9697be39.png)

**Comment by aeschli** [comment]
I kept `< >` and added [""],for consistency with XML.

**Comment by pgfearo** [comment]
It occurs to me now that there's also potentially a more serious issue with matching '<' and '>' for XML tags in XSLT:

The '>' is legal in an XML attribute and also in an XPath expression, so the '<' at the beginning of a start tag with an XPath attribute may incorrectly match with the '>' in the XPath instead of the '>' at the end of the start tag. I'm not sure if the bracket matching algorithm caters for this?

**Comment by pgfearo** [comment]
As this has the 'insiders-released' branch, I tried my extension, modified to use the 'xsl' language id.

I then tried it on the following version:

Version: 1.48.0-insider
Commit: 8c426f9f3b6b18935cc6c2ec8aa6d45ccd88021e
Date: 2020-07-23T05:40:23.559Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

The only bracket matching I got for XSLT/XPath was for the '<' characters. They at least they weren't affected by XPath expression such as `input > $0` but it still makes the extension unusable.

I realise now that there are other parts of VSCode's XSLT configuration that must be contributing to this issue (and quite probably others also), the cause of which I don't fully understand.

To avoid the need for the VSCode team to be experts in the XSLT language (not the most popular language I admit), it's probably best if I avoid conflict with the built-in language configuration by sticking with a language ID other than 'xsl'. 

There are a limited number of XSLT language-aware extensions so, if users require cross-extension compatibility,  I'm hoping I can persuade their maintainers of these extensions to switch from using the 'xsl' language ID also.

That said, I genuinely appreciate the attempts of the VSCode team to help resolve an issue for a not-so popular language.

**Comment by aeschli** [comment]
`"($input > 0)"` is classified a s string, and bracket matching will ignore what's in strings (or regexes, or comments). 

![image](https://user-images.githubusercontent.com/6461412/89917589-3faf1580-dbf9-11ea-8c3f-fd71f4cb7121.png)

**Comment by pgfearo** [comment]
I agree, it is classified by the XSL built in extension as a string, but it is clearly not a string to the XSLT parser, it is part of the XPath language that is embedded in XSLT. My extension uses semantic highlighting instead of a TM grammar. Also XPath expressions may also be embedded in text nodes, which are not classified as a string.

**Comment by aeschli** [comment]
You can still call it a string, but with well defined syntax as content.

But I see, the problem is that we can't teach our bracket matcher about other scopes to ignore. 

I would keep the grammar, keep calling it a string and use semantic highlighting on the syntax inside.

**Comment by pgfearo** [comment]
If I follow your advice, keeping the 'xsl' TM grammar but using semantic highlighting, users of the extension are left with these two problems:

1. The 'xsl' TM grammar marks an entire XPath expression within XML attributes or CDATA sections as a string token. The bracket matcher does not 'see' the semantic tokens inside the string token. Bracket characters `{` `(` and `[` and their matching pair-values `}` `)` and `]` within an XPath expression are disregarded.
2. There is a case where the TM grammar does not mark an entire XPath expression as a string, when the expression is included in a [Text-Value-Template](https://www.w3.org/TR/xslt-30/#text-value-templates) in an XML text-node. In this case, the listing of '>' as a bracket interferes with true bracket-matching within the expression as shown in the screenshot below:

![tagMatching](https://user-images.githubusercontent.com/2734234/90240667-96973380-de21-11ea-9cd1-bcf1dfd92316.png)

In the above screenshot, the cursor is placed just before the `>` char in the expression `string(foo > bar), the expected behaviour would be for the `(` and `)` brackets to be highlighted, but instead, it is the `<` and `>` of the following XML close-tag that is highlighted by the bracket matcher.

If the cursor is placed just after the '>' char in the same expression we get the expected and correct behaviour where the `(` and `)` are highlighted as being the enclosing matching brackets:

![bracketMatching](https://user-images.githubusercontent.com/2734234/90241051-39e84880-de22-11ea-999d-24fc9bcf6951.png)

Thus to keep bracket-matching behaviour correct, I must unfortunately continue avoiding use of the 'xsl' language id for my extension. The benefits of this approach still seem to outweigh the disadvantages which include:

1. My extension continues to be incompatible with any other XSLT extensions that only support the 'xsl' language id. 

2. A developer opening an XSLT file with a 'xsl' extension will not be made aware by Visual Studio Code recommendations that there is an XSLT programming-language extension available for this file type.
