### ISSUE TITLE
Proposed API is only available when running out of dev....

### ISSUE THREAD

**Issue by shiraze** [microsoft/vscode#102530]
Issue Type: <b>Bug</b>

An unchanged extension now shows the "Proposed API is only available when running out of dev or with the following command line switch.." each time VS Code launches. This extension has not changed in two years

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (5.82GB free)|
|Process Argv|--folder-uri file:///c%3A/IS%20Transfer/Source/React/react|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.6
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
vscode-colorize|kam|0.8.17
favorites|kdc|2.4.5
powershell|ms-|2020.6.0
material-icon-theme|PKi|4.2.0
code-spell-checker|str|1.9.0

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
This will be fixed in 1.47.2

**Comment by shiraze** [comment]
Thanks - what's this a duplicate of, because I searched for similar issues before raising.

**Comment by shiraze** [comment]
Looks like it could be a duplicate of #102170

**Comment by shiraze** [comment]
Thanks - definitely fixed in 1.47.2
