### ISSUE TITLE
vscode rendering the wrong c# color themes while using c# ? syntactic sugar at the end of the line

### ISSUE THREAD

**Issue by lzw5399** [microsoft/vscode#102572]
- VSCode Version:

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggrmn93metj30bo06eacr.jpg)

- OS Version: **OSX 10.15.5**

Steps to Reproduce:

1. with c# ? syntactic sugar

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggrn7qs1onj30uh0jqtbo.jpg)

2. remove ?

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggrn8n7rrbj30qx0ih41d.jpg)

Does this issue occur when all extensions are disabled?: Yes/No

**YES**

**Comment by alexr00** [comment]
@lzw5399 can you please provide a copy-pastable example that shows the issue?

**Comment by lzw5399** [comment]
Hi @alexr00 , below is an example
```csharp
using System.Threading.Tasks;
using System;
public class Example
{
    public async Task<string> Ok(string param)
    {
        return await Task.Run(() => "ok");
    }

    public void Method1()
    {
        var list = new List<string>();
        var filteredList = list? // <=
        .Where(it => it.Length > 3)
        .ToList();
    }

    public async Task<string> Error(string param)
    {
        return await Task.Run(() => "error");
    }
}
```

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ghlwlkxsd3j30et0cr3zr.jpg)

**Comment by alexr00** [comment]
Thanks, I can repro. Moved to the repository that we get our C# grammar from https://github.com/dotnet/csharp-tmLanguage/issues/183
