### ISSUE TITLE
API gaps to support Liveshare in Notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#102503]
Currently the editing API for Notebook is slim and may not support all features of Live Share.

**Comment by rebornix** [comment]
Below is a draft list of missing API/features to support co-editing in notebook after analyzing how LiveShare uses text editor APIs.

- Editor
    - [ ] Visible notebook editors & change event(together with visible text editors) (`vscode.window.visibleTextEditors`, `vscode.window.onDidChangeVisibleTextEditors`)
      * Understand which documents are open, split (different columns), closed, and other changes. (E.g editor configuration/layout changes)
    - [ ] Notebook editor selection & text editor selection in cell editor (`vscode.window.onDidChangeTextEditorSelection`)
      * Track the selection changes in a document (E.g. highlights, cursor position) and communicate them to all clients so they can display indicators to the other Participant positions in the documents
    - [ ] Active notebook editor change (`vscode.window.onDidChangeActiveTextEditor`)
      * Handle the changes of the currently active editor -- this is important because not all editors are really considered "editors". E.g the terminal window isn't really an editor. In these cases we need to update states. It's also important because that is where we're doing the updates of people following us / breaking follow when you change your active editor when following someone.
    - [ ] Editor visible range change (`vscode.window.onDidChangeTextEditorVisibleRanges`)
      * update layout info
- Document
    - [ ] Notebook document changes event (`vscode.workspace.onDidChangeTextDocument`)
      * Collect & process actual edits to a document to communicate those changes to the other partcipents, and maintain our own state for those joining later
    - [ ] Notebook document, open, close event (`vscode.workspace.onDidCloseTextDocument`, `vscode.workspace.onDidOpenTextDocument`)
      * When closing a document, we need to clean up state/buffers for our undo management (document could be reopened, which would be new undo state) as well as when a document is deleted, or renamed, where we need to re-wriring of the state.
    - [ ] Notebook document save event (`vscode.workspace.onDidSaveTextDocument`)
      * Saves need to be propagated through the session, so other clients can also save when indicated (guests aren't really saving, for example)
- Navigation
  - [ ] Open/jump to an editor (`vscode.window.showTextDocument`). 
  - [ ] Open/jump to a diff editor (`vscode.diff`)
- Decorations
  - [ ] Show user card/info around the editor/cell selection
- Undo/Redo
  - [ ] Notebook document change events + cell document change events
  - [ ] :runner: Hook up with editor undo/redo command (`undo`, `redo`)
- MISC
  - [ ] Untitled notebook document (`TextDocument.isUntitled`)

cc @lostintangent.

**Comment by lostintangent** [comment]
@rebornix Would there be work left for Live Share to do after you make the above changes? Or would notebooks magically "look" like a series of documents to Live Share? 😄

**Comment by rebornix** [comment]
Examples of how the notebook APIs can be used together with Text Editor APIs for Live Share

### Active Editor change

```tsx
vscode.window.onDidChangeActiveTextEditor((e) => {})
vscode.notebook.onDidChangeActiveNotebookEditor((e) => {})
```

### Document lifecycle

```tsx
vscode.workspace.onDidCloseTextDocument
vscode.workspace.onDidOpenTextDocument
vscode.workspace.onDidSaveTextDocument

vscode.notebook.onDidOpenNotebookDocument
vscode.notebook.onDidCloseNotebookDocument
vscode.notebook.onDidSaveNotebookDocument
```

### Content Changes of a notebook document

```tsx
vscode.workspace.onDidChangeTextDocument((e) => {
  const document = e.document;
  const notebookDocument = document.notebook;
});

vscode.notebook.onDidChangeNotebookCells(e => {
  const notebookDocument = e.document;
});
vscode.notebook.onDidChangeCellOutputs
vscode.notebook.onDidChangeCellLanguage
vscode.notebook.onDidChangeCellMetadata
```

### Participant selection change

```tsx
vscode.window.onDidChangeTextEditorSelection(e => {
  const selections = e.selections;
});

vscode.notebook.onDidChangeNotebookEditorSelection(e => {
  const selection = e.selection; // a notebook cell
});
```

### Unfold recursively from an index in the notebook document to the top

```ts
vscode.commands.executeCommand('notebook.unfold',  {
      "index": 1,
      "direction": "up",
      "levels": 65535
});
```

### Cell Editing

- [ ] 🏃 re https://github.com/microsoft/vscode/issues/105283

### Decorations

- [ ] Decorations for showing participant user name
- [ ] Decorations for showing participant selection

### Viewport information

- [ ] Visible ranges
- [ ] Visible ranges change event

**Comment by lostintangent** [comment]
@rebornix This is looking awesome! Tagging @daytonellwanger as an FYI, since we'll be looking into adding this Live Share support soon 👍

**Comment by rebornix** [comment]
Had offline discussion with @daytonellwanger and found more API limitations: 

* Mock content provider on guest side
  * Currently to register a content provider, the extension needs to register static contribution point in`package.json` first, which will specify file extensions it supports. However when a notebook document is opened in the host side, it's possible that there is no such notebook content provider in the guest side. Also Live Share extension can't register static contribution in advance as the file name patterns are not known yet
  - [ ] Figure out how to register a content provider only at runtime
  - [ ] Figure out how to register an exclusive content provider
- [x] Decorations for rendering name tag https://github.com/microsoft/notebook-extension-samples/tree/master/notebook-editing#decoration-api


Code snippets will be tracked in https://github.com/microsoft/notebook-extension-samples/tree/master/notebook-editing#decoration-api

**Comment by rebornix** [comment]
While attempting to support exclusive content provider registration at runtime, I found more open questions than listed above. Thus we took one step back and re-evaluate what's the best strategy to support notebook editing in Live Share environment:

* Notebook content providers work as Live Share companion extensions
  * Content provider extensions **should** be installed on both host and guest sides, otherwise Live Share won't work.
  * When a notebook is opened on host, LS will open the same document on guest with the same view type if it exists.
  * LS needs to contribute a mock kernel, which redirects the execution/cancel requests to the host
    - [ ] When there are kernel providers for the notebook, the mock kernel needs to be `exclusive`.
* Notebook content providers are mirrored on guest side
  * Content provider extensions are only required on host side.
  * When a notebook is opened on host, LS will
    * register a mirror content provider on guest
      - [ ] the content provider needs to be registered dynamically (no static contribution)
      - [ ] LS needs to know the `viewType`, `displayName`, `selector` and `transientOptions` of the content provider
      - [ ] LS needs to register mirror content providers if there are opened mirror notebook documents in the workspace (for example, when reloading the workspace on guest side)
      - [ ] Again, if users switch the editor to another view type, Live Share won't work, unless we disable view type switching
    * open the document with new mirror view type
  * 💚 LS will register a kernel for the mirror content provider on the guest side, and then redirect the execution requests to the host

**Comment by lostintangent** [comment]
@rebornix 🙌 If possible, it would be awesome to enable option #2 above. Since VS Code already provides the UI/core functionality of notebooks, being able to leverage kernels from the host would enable the setup-free guest experience we already have with language services,  task providers, etc. 

Where are you and @daytonellwanger leaning?

**Comment by rebornix** [comment]
@lostintangent thanks for your feedback, we are leaning towards option 2 as well (majorly for the same reason you mentioned above). option 1 is listed there to ensure us not miss any interesting scenarios and unveil all possible challenges.

**Comment by rebornix** [comment]
Some updates on the exploration: I wrote the VSLS [companion extension](https://github.com/microsoft/notebook-extension-samples/tree/master/notebook-vsls) to help us understand how our APIs are used and what are still missing, it went well and answered questions listed above. Here is what we have now:

![notebook-vsls-execution](https://user-images.githubusercontent.com/876920/93914607-9fe6ac00-fcbb-11ea-901f-1386d4b1f353.gif)

* document syncing (we create mirror/mock content providers on the guest side, no requirements for notebook extensions on guest machine)
* active selection syncing and decorations (show the name tag and active cell border)
* execution on guest (by sending request to the host)
* metadata and outputs syncing (execution elapsed time, outputs update, etc)

Most of the logic/code in [notebook-vsls](https://github.com/microsoft/notebook-extension-samples/tree/master/notebook-vsls) can be used directly in Live Share. There are a few items left in Live Share core to archive a proper co-editing experience:

- [ ] when a cell editor/document is opened on the host machine, don't open a Monaco editor on guest (by checking `TextDocument#notebook`)
- [ ] listen to notebook document content changes on both host and guest sides, ask the server to resolve the conflicts and sync remaining changes back to the document
  - [ ] Notebook Cell Uris are created by the core (VS Code UI) and unique, so it's possible that the cells at the same view index on different machines have different Uris. If LS wants to manipulate the document based on Cell Uri, the LS needs to build a mapping between cells on host and guest. If LS will always work on view index, then it should keep track of notebook document versions.

**Comment by lostintangent** [comment]
@rebornix Wow, this looks amazing! I'm going to have to check out that extension this weekend 😄

**Comment by rebornix** [comment]
@daytonellwanger already pushed the initial notebook support in Live Share and while doing that, we figured out the LS extension may need more info from VS Code

* [x] VS Code API equivalent of vscode.workspace.openTextDocument for notebook documents to avoid our own implementation
  * We added `vscode.notebook.openNotebookDocument`.
* [ ] VS Code API equivalent of vscode.window.showTextDocument for notebook cells
  * @daytonellwanger what's the expected behavior of the equivalent API?
* [ ] 🐛  Decorations being cut off for notebook cells
* [ ] API for getting notebook contents on host without opening notebook on host
  * @daytonellwanger can `vscode.notebook.openNotebookDocument` solve this problem?

**Comment by daytonellwanger** [comment]
> what's the expected behavior of the equivalent API?

It should focus the notebook in the specified column and ideally scroll to the position of the specified cell.

> can vscode.notebook.openNotebookDocument solve this problem?

`vscode.notebook.openNotebookDocument` will actually open the notebook, right? This is an ask for getting the contents without actually opening the notebook, although it's lower priority because I don't think this is possible with regular text documents today either.

**Comment by rebornix** [comment]
> vscode.notebook.openNotebookDocument will actually open the notebook, right? This is an ask for getting the contents without actually opening the notebook, although it's lower priority because I don't think this is possible with regular text documents today either.

@daytonellwanger `vscode.notebook.openNotebookDocument` behaves like `vscode.notebook,openTextDocument`, which will open the document in the background (no editor attached) and then you can access cell and metadata info on the notebook document.

**Comment by daytonellwanger** [comment]
@rebornix perfect! I'll give it a try.

**Comment by rebornix** [comment]
>  VS Code API equivalent of vscode.window.showTextDocument for notebook cells

@daytonellwanger I just added `vscode.window.showNotebookDocument` which can open a notebook and reveal/focus a cell position

```ts
const editor = await vscode.window.showNotebookDocument(document, { viewColumn: vscode.ViewColumn.Beside, selection: { start: 10, end: 11 } });
```

**Comment by rebornix** [comment]
> Decorations being cut off for notebook cells #110769

This one is really challenging to fix completely so instead we pushed a workaround, if there is a decoration which has `top` property set, we will adjust the cell editor's top padding to at least `lineHeight+2`. So for editors in notebook, please always render the name tag above the cursor instead of showing it below the line when cursor is on the first line.

Once the `showNotebookDocument` is shipped with Insiders, I think we don't have any blocking API for your next step @daytonellwanger

**Comment by lostintangent** [comment]
@daytonellwanger Does your list of asks enable us to implement complete "follow" support for notebooks? In addition to being able to open a notebook to a specific scroll position and cell focus, are we also able to track/synchronize subsequent cell navigations and notebook scrolls? The answer is probably mentioned above, but I just wanted to double-check 👍

**Comment by rebornix** [comment]
In order to allow the Live Share extension to create mirror kernels on guest side, we introduced two more API commands


```ts
CommandsRegistry.registerCommand('_resolveNotebookKernelProviders', async (accessor, args): Promise<{
	extensionId: string;
	description?: string;
	selector: INotebookDocumentFilter;
}[]>

CommandsRegistry.registerCommand('_resolveNotebookKernels', async (accessor, args: {
	viewType: string;
	uri: UriComponents;
}): Promise<{
	id?: string;
	label: string;
	description?: string;
	detail?: string;
	isPreferred?: boolean;
	preloads?: URI[];
}[]>
```

**Comment by daytonellwanger** [comment]
If a file has multiple content providers available, the user can choose which content provider to use. It would be an awkward experience to lock the host and guest into using the same content provider. A couple examples:
- The host has the notebook open with Content Provider A while the guest isn't following them. The guest later opens the notebook independently and chooses to use Content Provider B. The guest doesn't know the host has the notebook open with Content Provider A and is forced into using Content Provider A.
- The guest is viewing a document with Content Provider A. The host switches to using Content Provider B. The guest, in the middle of their viewing, is switched to Content Provider B.

I believe the correct UX is for host and guest to be allowed to independently select a content provider (note that if they're using different content providers, coediting will not be supported). 

Today the `vscode.notebook.openNotebookDocument` API will only open the notebook document with the content provider the host has already selected. It will need to be updated to support opening the notebook with a different content provider even if the notebook is already open. Note that we don't necessarily need to support having the notebook open in an editor. We just need the `vscode.notebook.openNotebookDocument` API to support opening the notebook with multiple content providers.

If different participants are using different content providers, their changes will be synced when the content provider persists them. This presents no difficulties if the file is clean for all other participants - we simply update their contents. However, if Participant A has a file open with Content Provider A, and has made changes but not persisted them, and Participant B has the same file open with Content Provider B and just persisted changes, this should be treated the same as a file being updated on disk when open with dirty changes - when Participant A attempts to persist the file, they will receive "The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes."

**Comment by jrieken** [comment]
> It will need to be updated to support opening the notebook with a different content provider even if the notebook is already open.

That will be VERY complex as internally everything is mapped by its uri and it means we need to invent some uri for which combine actual uri and provider type

**Comment by daytonellwanger** [comment]
@jrieken is there another alternative to avoid the awkward situations described above? I imagine the user will be quite confused if they go to open the notebook and explicitly select a content provider and then we open it with a different one. Or if the content provider is changed out from under them in the middle of a session.

I suppose we could show a notification to the user anytime we encounter one of these to give some explanation, but it still feels like a bad experience.

**Comment by jrieken** [comment]
I don't know if there is an alternative. The challenge is that there is one file on disk (on sequence of bytes) which interpreted different depending but always referred to by the same name. So, it is good that this is on the table. It needs some thinking and code analysis to understand the full impact here.

**Comment by daytonellwanger** [comment]
Thanks for the info. For Live Share's v1 then, we'll move forward with the constraint that the notebook can only be open by a single content provider at a time. For most scenarios this should be fine, as I imagine it's rare that host and guest would want to use different content providers. However, if it were simple to support multiple content providers, or there were other use cases that required it, that would of course be preferred for the Live Share scenario 😊.

**Comment by rebornix** [comment]
Thanks @jrieken for bringing up the potential issues of multiple content providers, I did some initial analysis of how we use the Uri. Since we have the restriction in place, when we designed the Uri for notebook document and notebook cell, they don't take view type into account. It made the Uri simple and compatible with existing workbench features.

The notebook document Uri is the resource Uri, untouched. Users can open a resource in both text editor and notebook editor, since they are different editor types (users can also open the resource in a custom editor), we can always identify them. A typical notebook document uri might be like `file:///C:\Users\rebor\code\vscode\.vscode\notebooks\api.github-issues`

The notebook cell uri is based on the notebook uri, with one more information cell handle. Thus the notebook cell Uri will carry following info

* `notebookUri#path`
* `notebookUri#scheme`
* cell handle


The `CellUri` will be used in following places to identify which notebook document it belongs to:
* UndoRedoComparisonKey. `notebookUri.toString()`, e.g., `file:///C:\Users\rebor\code\vscode\src\vs\workbench\contrib\notebook\common\notebookCommon.ts`
* Output renderer, which will be used to find the notebook document in extension host
* Editor Open, `this.editorService.findEditors(notebookUri, group).filter(editor => !(editor instanceof NotebookEditorInput)`
* CellContentProvider
* Diff Editor check whether a cell is in original or modified editor
* MarkerListProvider
* NotebookCellStatusBar

To support multiple content provider for the same document, we will need to store the `viewType` info in the cell uri and then in every place we attempt to revive notebook document, we must always use the `viewType` info from the cell uri.

**Comment by alyssajotice** [comment]
Before migrating to serializers, Live Share needs a way to get a list of the available serializers, similar to the command `vscode.resolveNotebookContentProviders`. We also need a way to add viewOptions when registering a serializer so that we can add a fileNamePattern for the serializer.

**Comment by rebornix** [comment]
Closing this now as @mjbvz is working with Live Share on the API update.
