### ISSUE TITLE
Debugger's Call Stack shows binary name instead of debug configuration name

### ISSUE THREAD

**Issue by thiagoufg** [microsoft/vscode#102592]
- VSCode Version: 2020 June update
- OS Version: macOS Catalina 10.15.5

Steps to Reproduce:

1. Start a compound debug configuration with at least 2 (obviously) configurations at once.
2. Watch the call stack: instead of the configuration name, you see the binary name, such as "node" or "npm" repeatedly.

Detail: if you click on each root item of the call stack, while having the DEBUG CONSOLE open, the drop-down list on the top-right corner of the debug console will change to the configuration name, so it is possible for you to know which configuration you're actually working with. But it gets really confusing if you run 20 configurations at once.

Sometimes, randomly, the names swtich from the binaries to the configuration names, but most times you only see "npm", "npm", "npm", "npm", etc...

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Thanks for the issue, will be looking at this today in https://github.com/microsoft/vscode-js-debug/issues/596

/duplicate
