### ISSUE TITLE
Search Editor fails to load files in named folders

### ISSUE THREAD

**Issue by dreamer88** [microsoft/vscode#102531]
Using the "name": "Display Name" field in the "folders" section a .code-workspace file breaks navigation from the Search Editor. I've attached a sample workspace.

[vscode_search_editor.zip](https://github.com/microsoft/vscode/files/4921444/vscode_search_editor.zip)

Easy Test:
1) Open the code-workspace in base_directory
2) Search for "Text" using the "Search Editor
3) Note that you will have 3 successful results; one in the unnamed "base_directory, one in the unnamed "success_directory" and one in the named directory "Fail"
4) Try to open to result in the "Fail" directory and notice you will receive an "Unable to open" file message as it attempts to open a file in the "failure_directory/fail_directory" directory which does not exist.
5) Note that this is successful in the unnamed "success_directory"
6) If you edit the code-workspace to remove the "name" from "failure_directory", you will be able to successfully able to navigate to the search result.

**Comment by JacksonKearl** [comment]
Thanks for reporting! This looks like https://github.com/microsoft/vscode/issues/100929, which should be fixed in Insiders.
