### ISSUE TITLE
Integrated Terminal - Losing cursor position with Japanese IME

### ISSUE THREAD

**Issue by brianblakely** [Microsoft/vscode#10254]
- VSCode Version: 1.4.0
- OS Version: Microsoft Windows [Version 10.0.14393]

Steps to Reproduce:
1. Open integrated terminal
2. With Japanese IME in Romaji mode, type `chouchou` and press space.

[Screenshot of this happening in a command](http://imgur.com/5jXUIC8)

**Comment by Tyriar** [comment]
A lot has changed in the terminal since this was reported, if you're still having the issue please let me know and give expected output :smiley:
