### ISSUE TITLE
Error: Cannot find module '/var/folders/qx/w81rmn5j26qb18hsh9gd2r000000gn/T/vscode-js-debug-bootloader.js'

### ISSUE THREAD

**Issue by matthewvandergrift** [microsoft/vscode#102557]
- VSCode Version: 
- OS Version:

VSCode Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:43:02.577Z (1 day ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Mac Crashed and now vscode cant npm i on any node project

Console snag:
$ npm i
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '/var/folders/qx/w81rmn5j26qb18hsh9gd2r000000gn/T/vscode-js-debug-bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1278:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Does this issue occur when all extensions are disabled?: Yes/No

Thats the problem.  The 'ms-vscode.node-debug2'  "built in" one wont let me disable it for the project or workspace.

**Comment by connor4312** [comment]
@matthewvandergrift check here for the solution: https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467

/duplicate

**Comment by matthewvandergrift** [comment]
Using the nightly build and turning on the preview worked.  First real issue I have had with VSCode.  I come from Visual Basic and Visual Studio and a long line of various MSFT development tools.  Love it. Keep up the good work.   Consider me a happy client (now that its working) ;)
