### ISSUE TITLE
[TypeScript] Renaming a file with a class gives 'Duplicate identifier' error

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#10256]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create a TypeScript file
2. Add a class
3. Save file
4. Rename or move file

```ts
namespace MyNamespace {
    
    export class MyClass {

    }
    
}
```

When you copy the text of the file, delete the file then paste it in a new file the error stays. Running "Reload Typescript" project does not fix the error.

Here is the before file rename:

![duplicatebefore](https://cloud.githubusercontent.com/assets/1571806/17459907/1e4866b2-5c14-11e6-8206-f35d3cd77c2e.png)

Here is after the file rename:

![duplicateafter](https://cloud.githubusercontent.com/assets/1571806/17459906/1e484bfa-5c14-11e6-8154-4438fb40fd35.png)

If I restart the editor the error goes away.

**Comment by dbaeumer** [comment]
VS Code sends the following messages to the server in the case of rename:
```
Sending request: close (22). Response expected: no. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/10256/test.ts"
}

Sending request: open (23). Response expected: no. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/10256/test2.ts",
    "fileContent": "namespace MyNamespace {\r\n    export class MyClass {\r\n    }\r\n}"
}
```
which IMO is corrent. Moving to the TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10200
