### ISSUE TITLE
Fedora: VS Code snap crashes when using attempting to git clone

### ISSUE THREAD

**Issue by BinaryAura** [microsoft/vscode#102583]
Issue Type: <b>Bug</b>

Install on fedora 32 workstation via snap
Click on Clone Repository
What you type doesn't matter
Attempt to close the Repo

Expected Result:
Git Clones the Repo

Actual Result:
After a couple seconds Code Crashes

I just had this happen attempting to "Preview" the issue on Github a second time.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-14T00:13:57.513Z)
OS version: Linux x64 5.7.7-200.fc32.x86_64 snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor (32 x 2111)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|62.80GB (1.99GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by joaomoreno** [comment]
Is this issue new with this release? Was this working before?

**Comment by joaomoreno** [comment]
This is the same as https://github.com/microsoft/vscode/issues/100940
