### ISSUE TITLE
Open Folder help file should exist

### ISSUE THREAD

**Issue by dusanbass** [microsoft/vscode#102533]
Hi,

I have tried to find on my own inside the VSCode the Open Folder shortcut for macOS and I haven't found it. I find it would be useful if it could be found by the help command

<img width="471" alt="Screenshot 2020-07-14 at 11 36 11 PM" src="https://user-images.githubusercontent.com/8012306/87479006-018afa00-c62b-11ea-9e80-721c43ca1bba.png">

As you can see this shortcut is not stated.

**Comment by roblourens** [comment]
It's just called "Open" and is under the "File" menu
