### ISSUE TITLE
Windows Terminal Integration on VSCode

### ISSUE THREAD

**Issue by amarsgithub** [microsoft/vscode#102547]
Hello, I use my Windows Terminal for almost everything! I would like to know if it would be possible to imbed my Windows Terminal features onto my VSCode. That would be the gold state, and I don't see it being a very difficult process to have another option in the dropdown to just link my Windows Terminal and have it imbedded into the VSCode terminal window!

**Comment by Tyriar** [comment]
Embedding it is not possible, but I've already built an extension to provide better integration https://marketplace.visualstudio.com/items?itemName=Tyriar.windows-terminal
