### ISSUE TITLE
Error copying and pasting on jupyter notebook

### ISSUE THREAD

**Issue by AlanVazquez99** [microsoft/vscode#102551]
Issue Type: <b>Bug</b>

When copying and pasting, the copied text is duplicated (Double pasted) or something distorted in the case of large texts.
The problem only occurs when working with notebooks within VS Code

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.94GB (4.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|11.1.0
vscode-django|bat|0.20.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.36.1
vscode-eslint|dba|2.1.7
docs-markdown|doc|0.2.76
githistory|don|0.6.6
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.1.3
code-runner|for|0.11.0
beautify|Hoo|1.5.0
rainbow-csv|mec|1.7.0
vscode-language-pack-es|MS-|1.47.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.6.91350
vscode-pylance|ms-|2020.7.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
debugger-for-chrome|msj|4.12.9
indent-rainbow|ode|7.4.0
vscode-gitignore-generator|pio|1.0.2
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.8.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
ayu|tea|0.20.1
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by aidosRepoint** [comment]
The same issue +
