### ISSUE TITLE
New js debugger throw on every import

### ISSUE THREAD

**Issue by dmail** [microsoft/vscode#102514]
- VSCode Version:1.47.0
- OS Version: macOS Mojave 10.14.6
- Node version: 14.5 (also reproduced with node 13.8)

Steps to Reproduce:

1. Reproduce the following file structure

    **package.json**
    ```json
    {
      "type": "module"
    }
    ```

    **index.js**
    ```js
    import foo from "./foo.js";
    import bar from "./bar.js";

    debugger;
    console.log(`${foo}${bar}`);
    ```

    **bar.js**
    ```js
    export default "bar";
    ```

    **foo.js**
    ```js
    export default "foo";
    ```

2. Click Run and Debug

3. Select Node.js

4. VsCode throw on every import as if file does not exists.

Does this issue occur when all extensions are disabled?: Yes

Check the following gif illustrating the issue:

![ezgif-2-eaef7b185c8a](https://user-images.githubusercontent.com/443639/87454380-2cae2300-c604-11ea-9930-f2c1344dd28e.gif)

The gif shows that `<node_internals>/internal/url.js` throw Invalid url errors on `./foo.js` and `./bar.js`. It seems node.js tries to perform the following code for some reason.

```js
new URL("./foo.js", undefined)
```

**Comment by connor4312** [comment]
Thanks for the issue, this is working as-designed in VS Code side of things -- you have VS Code set to break on caught exceptions ("Breakpoints" view in the lower left corner), and importing an ESM module causes an exception to be thrown in Node.js' internals.

I've opened an issue in https://github.com/nodejs/node/issues/34367 to see what they think about reworking this behavior.

/asDesigned

**Comment by dmail** [comment]
Thanks :)
