### ISSUE TITLE
Previewing markdown may corrupt the table layout.

### ISSUE THREAD

**Issue by ataihei** [microsoft/vscode#102582]
Issue Type: <b>Bug</b>

When using table syntax, if you use even one `` ` `` after surrounding a `` ` `` with a ``` `` ```, the table layout may be corrupted.

Example:
```markdown
|a|b|
|--|--|
|`` ` ``| `c` |
|`` ` ``| `d |
| `e` | `` ` `` |
|`` ` ``| f |
```
Result
![image](https://user-images.githubusercontent.com/10428970/87532220-c68dd280-c6cd-11ea-9426-5d7cec819072.png)

Thank you for your response.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (17.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf-hint|han|0.1.0
rainbow-csv|mec|1.7.0
render-crlf|med|1.5.3
vscode-docker|ms-|1.3.1
vscode-language-pack-ja|MS-|1.47.3
csharp|ms-|1.22.1
python|ms-|2020.6.91350
remote-wsl|ms-|0.44.4
powershell|ms-|2020.6.0
typescript-javascript-grammar|ms-|0.0.53
markdown-all-in-one|yzh|3.1.0
json|Zai|1.0.4

</details>

**Comment by mjbvz** [comment]
We use markdown-it to power the preview and the VS Code rendering [matches markdown-it's](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7Ca%7Cb%7C%5Cn%7C--%7C--%7C%5Cn%7C%60%60%20%60%20%60%60%7C%20%60c%60%20%7C%5Cn%7C%60%60%20%60%20%60%60%7C%20%60d%20%7C%5Cn%7C%20%60e%60%20%7C%20%60%60%20%60%20%60%60%20%7C%5Cn%7C%60%60%20%60%20%60%60%7C%20f%20%7C%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

If you think this is a bug, please file an issue against the markdown it project
