### ISSUE TITLE
Ctrl-S issue in VS Editor 1.47.0

### ISSUE THREAD

**Issue by ivanburak** [microsoft/vscode#102507]
- VSCode Version: 1.47.0
- OS Version: MS Windows 10

Steps to Reproduce:

1. Load a code file about 2-3 screen length
2. Scroll to the second page
3. Edit any line 
4. Press Ctrl-S (Save changes)
5. A cursor will be moved to the first line

Does this issue occur when all extensions are disabled?: No

**Comment by gjsjohnmurray** [comment]
> Does this issue occur when all extensions are disabled?: No

Please work out which extension is causing this, then report it to the author.

/causedByExtension
