### ISSUE TITLE
Incorrect extension suggestion 

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode#102553]
Version: 1.48.0-insider (user setup)
Commit: c828a5339bca7222fd8f56ab98361a98f736d185
Date: 2020-07-14T05:39:53.264Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open the vscode repo in insiders
2. Open a typescript file

![recording (7)](https://user-images.githubusercontent.com/8235156/87496284-427e1100-c621-11ea-9022-bc8eebc48496.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by 9at8** [comment]
cc @chrisdias

**Comment by chrisdias** [comment]
Sorry about that. I reverted the fix yesterday, it should be fixed in today's Insiders.

```
Commit: cb31fc6ce2b4da3520392b622aa3ebc5b313533b
Date: 2020-07-15T05:31:08.767Z
```
