### ISSUE TITLE
Process explorer: use icon font instead of SVG

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#102560]
Noticed how the process explorer is bundling `expanded.svg` and `collapsed.svg` still. Can we not use Codicons for this?

//cc @misolori

**Comment by bpasero** [comment]
Oh this seems to be used in the issue reporter, not process explorer. But not sure how to actually see it...

**Comment by misolori** [comment]
@RMacfarlane are we actually using these icons? I'm not seeing it:

![image](https://user-images.githubusercontent.com/35271042/87831767-3e2c4080-c839-11ea-9bc5-5f523eeab610.png)

**Comment by bpasero** [comment]
@RMacfarlane @misolori it looks like these are only used when VSCode is connected to a remote to show the remote processes as well. I didn't even know we had that, pretty cool:

![image](https://user-images.githubusercontent.com/900690/91282937-435ea280-e78a-11ea-99f8-e835b9166ff2.png)

Anyhow, my request still seems valid.

**Comment by bpasero** [comment]
PR up at https://github.com/microsoft/vscode/pull/105411
