### ISSUE TITLE
NodeJS+CharkaCore, ERROR in 1.47.0

### ISSUE THREAD

**Issue by karikera** [microsoft/vscode#102607]
I'm using node-chakracore for some reason.
but Now, I cannot debug node-chakracore with VSCode.

- VSCode Version: 1.47.1
- OS Version: Windows 10

Steps to Reproduce:
1. Make `launch.json` with VSCode
2. Download [node-chakracore](https://github.com/nodejs/node-chakracore/releases) release
3. Set "runtimeExecutable" to `node-chakracore`
4. Launch it!

Does this issue occur when all extensions are disabled?: "Yes"

Problem:
`\resources\app\extensions\ms-vscode.js-debug\src\bootloader.bundle.js` contains `spread in object literals` and chakracore cannot parse it.
~~node-chakracore splits "NODE_OPTIONS"(envvar) with whitespace and VSCode put a file path with whitespace.~~ (the problem of node-chakracore)

**Comment by connor4312** [comment]
Thanks for the issue. We don't make any effort to support node-chakracore, which had been archived by the Node team and is no longer maintained. I recommend either:

1. Using Node proper
1. Setting `debug.javascript.usePreview: false` to use the old debugger. This option will eventually go away, but may give you time to update.

**Comment by karikera** [comment]
Thanks for your help :)
