### ISSUE TITLE
Add option for code organization

### ISSUE THREAD

**Issue by psydeepak93** [microsoft/vscode#102692]
Is there a possibility to add a code organization option in VSCode to split code in the file into sections.

**Comment by ConradSollitt** [comment]
Hi @psydeepak93 

Have you tried using these two built-in features? They may help with finding code or organization as they provide a high level overview of the code. Not all languages are supported however these features will work with JavaScript and Python when using a basic install.

**Code Outline**
This will show the file structure of the current file and you can double-click on a function or variable name to quickly navigate to that location in the file.

![image](https://user-images.githubusercontent.com/57777521/87816971-fb5c6f80-c81c-11ea-8b4b-a1c5019e1cfe.png)

**Breadcurmbs**
You can also quickly navigate to classes, functions, variables etc from the breadcrumb nav at the top of the screen. It will also highlight your selection which makes it clear to see the entire code block.

![image](https://user-images.githubusercontent.com/57777521/87816992-01525080-c81d-11ea-9d41-bdf5ffd71201.png)

**Support Links**
Here are some support links that might be related to what you are looking for:
https://code.visualstudio.com/docs/editor/editingevolved
https://code.visualstudio.com/updates/v1_25#_outline-view
https://code.visualstudio.com/updates/v1_26#_breadcrumbs
https://dev.to/vscode/vscode-breadcrumbs-are-here-jkn
