### ISSUE TITLE
Automatically expand the width of code column after focus.

### ISSUE THREAD

**Issue by gylidian** [microsoft/vscode#102655]
Issue Type: <b>Feature Request</b>

At present, the code column function is still static width, and cannot provide a dynamic effect of changing the width with focus.
If we move the mouse to any code column, it will automatically expand the width.
Can you provide an option to enable this function.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:43:02.577Z)
OS version: Darwin x64 19.5.0

**Comment by roblourens** [comment]
You might be looking for the command "Maximize Editor Group and Hide Side Bar" which collapses editor groups that are not focused. If that doesn't help then please explain more about what you are looking for.
