### ISSUE TITLE
Allow hiding the "Reply..." box for a comment thread

### ISSUE THREAD

**Issue by lostintangent** [microsoft/vscode#102665]
Between the [CodeTour](https://aka.ms/codetour) and [GistPad](https://aka.ms/gistpad) extensions, I'm making extensive use of the comments API in order to display "metadata over code" (e.g. guided descriptions of the code, a list of "back links" for the opened file). The comments UX works really well for this, but I continue to find end-users are confused by the `Reply...` text box, since the comments aren't intended to be replied to. If possible, it would be great if the comments API allowed defining that a comment thread was read-only somehow and/or be able to control the visibility of the `Reply...` text box.

**Comment by rebornix** [comment]
I'm thinking about adding some editable/readonly property to support this, one idea is adding this to the `CommentThread`

```diff
export interface CommentThread {
  readonly uri: Uri;
  range: Range;
+ readonly: boolean; // default false
  comments: ReadonlyArray<Comment>;
}
```

`CommentThread.readonly` can only be updated by the object owner (the comment provider).

@RMacfarlane does this make sense to you?

**Comment by RMacfarlane** [comment]
Makes sense, I like this idea

**Comment by rebornix** [comment]
Added `thread.readOnly` to disable replying to a thread.

**Comment by RMacfarlane** [comment]
@rebornix Should this property be optional?

**Comment by rebornix** [comment]
@RMacfarlane `CommentThread` is created by us (extHostComments) so we can guarantee that it always has a value.

**Comment by RMacfarlane** [comment]
Ah, I meant here: https://github.com/microsoft/vscode/blob/d026ae2a79a48258934545163dd634f09eb2656d/src/vs/vscode.proposed.d.ts#L2147

since some extensions use this type directly

**Comment by lostintangent** [comment]
This looks perfect. Thanks so much! 🙌

**Comment by rebornix** [comment]
Verifier: please tweak https://github.com/microsoft/vscode-extension-samples/blob/master/comment-sample/src/extension.ts and verify if setting `readOnly` on a comment thread will hide the reply box.

**Comment by bpasero** [comment]
@rebornix is this still for September?

**Comment by bpasero** [comment]
Moving to next milestone given it is a feature request.

**Comment by rebornix** [comment]
@jrieken we discussed about this at the beginning of this iteration and changed `readOnly` property to `canReply` to reflect its real purpose. Let me know if it makes sense to move it to stable. If so we can briefly mention that in tomorrow's API meeting or we postpone it to next iteration.

```ts
	export interface CommentThread {
		/**
		 * Whether the thread supports reply.
		 * Defaults to true.
		 */
		canReply: boolean;
	}
```
