### ISSUE TITLE
Right Click to open and no response

### ISSUE THREAD

**Issue by 1983cc** [Microsoft/vscode#10264]
- VSCode Version: 1.4.0
- OS Version: Windows 10 professional

Steps to Reproduce:
1.  Open vs code by right-clicking at a folder and choose open with vs code
2.  No responds . vs code can not open

**Comment by joaomoreno** [comment]
Do you see any error/info message? Is Code already running while you do the right click action, or it is not running? Is there a difference when it is running and otherwise?
