### ISSUE TITLE
Update service 

### ISSUE THREAD

**Issue by roshanprajapati03** [microsoft/vscode#102658]
![update](https://user-images.githubusercontent.com/19780417/87622815-8cf6af00-c741-11ea-8020-4c39b2515f75.PNG)
how to fix this problem help me out...

**Comment by gjsjohnmurray** [comment]
Is your Windows properly activated?

**Comment by roshaninstaboy** [comment]
> Is your Windows properly activated?

Nope not now

**Comment by joaomoreno** [comment]
Interesting, it seems your OS doesn't have a proper `tmpdir`.

Can you open `Developer: Toggle Developer Tools`, go into the `Console` and type `require('os').tmpdir()`, what's the output?

**Comment by roshaninstaboy** [comment]
> Is your Windows properly activated?

No my windows is not activated

**Comment by roshaninstaboy** [comment]
> Interesting, it seems your OS doesn't have a proper `tmpdir`.
> 
> Can you open `Developer: Toggle Developer Tools`, go into the `Console` and type `require('os').tmpdir()`, what's the output?

Okay I will try that 😊

**Comment by roshanprajapati03** [comment]
> `Developer: Toggle Developer Tools`

![output](https://user-images.githubusercontent.com/19780417/87842998-513d2000-c8ce-11ea-9387-f313f99a3314.PNG)


this is my output

**Comment by roshanprajapati03** [comment]
![if](https://user-images.githubusercontent.com/19780417/87843053-bf81e280-c8ce-11ea-94a3-28c330e96b7d.PNG)

same problem if i hit that vscode update button

**Comment by joaomoreno** [comment]
What does `echo %TEMP%` return in a Command Prompt?

**Comment by roshanprajapati03** [comment]
> What does `echo %TEMP%` return in a Command Prompt?

hey thank you so much 😊 @joaomoreno now its woking  
![env2](https://user-images.githubusercontent.com/19780417/88247937-25021480-ccbd-11ea-8667-4888b2a501c8.PNG) 

![updates](https://user-images.githubusercontent.com/19780417/88247953-2c292280-ccbd-11ea-886d-51f4027ffe2d.PNG)

**Comment by joaomoreno** [comment]
![woohoo](https://media.giphy.com/media/lMameLIF8voLu8HxWV/giphy.gif)
