### ISSUE TITLE
Issue with connecting to github from vscode

### ISSUE THREAD

**Issue by dkumar431** [Microsoft/vscode#10260]
- VSCode Version: 1.4.0
- OS Version: Windows 7

Steps to Reproduce:

I have started using Visual Studio Code (https://code.visualstudio.com/) recently . Started loving it. But I have some doubts regarding how to connect to Visual Studio Code to github.

I have one folder which contains 15 sub-folders and each sub-folder connected to a git repo. When I open a single sub-folder/git repo using Visual Studio Code, git operations working perfectly. But I want to open the root folder(containing 15 sub-folders) using Visual studio code, because i simultaneously work in all the repos. The root folder is not attached to git, its just a folder on my local which contains all the repos.

Is it possible to do?

**Comment by joaomoreno** [comment]
Not possible to do. Code only works with one git repository at a time and you have to open its root or a subfolder.
