### ISSUE TITLE
June 2020 Recovery 2 Engame

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#102630]
- [x] Create a milestone `<Month> <Year> Recovery 2` **@eamodio**
- [x] Bump the version number **@eamodio**
- [x] [🔖candidate issues](https://github.com/issues?utf8=✓&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22June+2020+Recovery+2%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `master` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `master`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **@eamodio**
- [x] Issues are verified on `stable` build and the `verified` label is added **team**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **@eamodio**
- [x] Update the release notes and include a link to a query for the fixed issues **@ornellaalt**
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) stable bits  (⚠️ MUST run with `--stable-build` argument ⚠️ )
  - [x] Windows - alexr00
  - [x] OS X - @bpasero
  - [x] Linux - @jrieken
- [x] Sanity check of installable bits
  - [x] Windows 32 bit 
    - [x] signed installer 32-bit @JacksonKearl 
    - [x] signed user installer 32-bit @JacksonKearl 
    - [x] zip 32-bit @eamodio
  - [x] Windows 64 bit @JacksonKearl 
    - [x] signed installer 64-bit
    - [X] signed user installer 64-bit
    - [x] zip 64-bit
  - [x] Windows ARM64 @deepak1556 
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
  - [x] OS X - @rebornix 
  - [x] Linux
    - [x] deb package 64-bit @JacksonKearl 
    - [x] rpm package 64-bit **owner**
    - [x] archives **owner**
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`) @9at8 
  - [x] Server ([instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
    - [x] Linux **@roblourens**
    - [x] macOS **@roblourens**
    - [x] WIndows **@roblourens**
- [x] Publish website **@ornellaalt**
- [x] Publish stable build **@eamodio**
- [x] Create an official release **@eamodio**
  - [x] Create a tag: `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)

**Comment by 747001690** [comment]
nice!!!

**Comment by SE2Dev** [comment]
@zgoda I can confirm that I have this issue as well, the deb *is* available on the [downloads page](https://code.visualstudio.com/updates/v1_47) however.
