### ISSUE TITLE
Output is coming two times while pasting the code

### ISSUE THREAD

**Issue by nithinkanil** [microsoft/vscode#102662]
- VSCode Version: 1.47.1
- OS Version: Ubuntu 18.04

I am using the Jupiter notebook in VSCode. While pasting using ctrl+V output is coming two times in the cell.

Steps to Reproduce:

1. Run Jupyter notebook
2. Copy a cell using ctrl+C
3. Past using ctrl +V
4. It will paster the output two times

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ArturoDent** [comment]
See #101946  duplicate

**Comment by gjsjohnmurray** [comment]
/duplicate - Thanks @ArturoDent. Using my special powers to trigger the bot.
