### ISSUE TITLE
Python syntax rip

### ISSUE THREAD

**Issue by wretwe** [microsoft/vscode#102610]
Issue Type: <b>Bug</b>

Press F to Pay respect python snippets.Working only my snippets.Snippets from python package from Microsoft don't work.This happend after Update VSCode to version 1.47.1 

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:44:14.582Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E4700  @ 2.60GHz (2 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|2.00GB (0.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
project-manager|ale|11.1.0
toml|be5|0.5.1
vscode-bad-code-highlighter|bha|0.1.6
better-toml|bun|0.3.2
path-intellisense|chr|2.2.1
githistory|don|0.6.6
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
LogFileHighlighter|emi|2.8.0
prettier-vscode|esb|5.1.3
todo-tree|Gru|0.0.178
vscode-test-explorer|hbe|2.19.1
rest-client|hum|0.24.1
path-autocomplete|ion|1.14.0
vsc-python-indent|Kev|1.10.1
MagicPython|mag|1.1.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
sqltools|mtx|0.22.10
autodocstring|njp|0.5.3
vscode-python-typehint|njq|1.2.0
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.8.0
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.12
snippet-creator|vin|1.1.0
vscodeintellicode|Vis|1.2.9
jinja|who|0.0.8

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Please give more details about what you are trying to do, what is actually happening, etc.

**Comment by wretwe** [comment]
I tried disabling extensions and reload VSC, but it kept on not working...In an hour everything worked.
I think it's because problems with github.
