### ISSUE TITLE
Update fails and breaks "user" install

### ISSUE THREAD

**Issue by dankellett** [microsoft/vscode#102608]
- VSCode Version: ?
- OS Version: Window 10

Steps to Reproduce:

1. Install previous version of VS Code user install.
2. Try update to current version of VS Code as non-admin user.

Does this issue occur when all extensions are disabled?: Yes

Attempting to update to the current version of VS Code "user" install, a permissions error was shown and the update aborts. Now the application will not open and attempting to re-install produces similar permissions errors. Example below.

![image](https://user-images.githubusercontent.com/1899114/87565611-b8609780-c676-11ea-8cea-0423537546dd.png)

**Comment by joaomoreno** [comment]
Does it reproduce if you restart your machine?

**Comment by dankellett** [comment]
Yes.

A successful workaround is to apply local admin rights to the user. This is not an great solution for many.

________________________________

**Comment by joaomoreno** [comment]
If you want to run incremental updates as the user, you should install it initially as that user, instead of installing it as an Administrator. Did you originally install it as an Administrator?

**Comment by dankellett** [comment]
I had originally installed as a non-admin. If it's not a widespread issue, I suspect it's likely caused by system hardening policies on this side.

Thanks for your attention.
________________________________
