### ISSUE TITLE
Issue with Git version 2.27 - Terminal won't work

### ISSUE THREAD

**Issue by dsmoore2020** [microsoft/vscode#102695]
- VSCode Version: 1.47.1
- OS Version: Windows 10 Version	10.0.17763 Build 17763

Steps to Reproduce:

1. Install version 2.27 of git
2. Set bash as default shell
3. Restart
4. Attempt to run command in the bash shell
      -At this point it will not allow you to type in the shell, every character scrolls you to the bottom. 
5. To fix issue down grade to version 2.26.1

I am submitting this bug here as I received the following prompt from VS Code:
![image](https://user-images.githubusercontent.com/61592226/87670722-36d43c80-c73e-11ea-9ef1-856171acea85.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
