### ISSUE TITLE
Search bar opens when clicking on open file / Can't keep open multiple files

### ISSUE THREAD

**Issue by Martin-Karsten** [microsoft/vscode#102622]
- VSCode Version: 1.47.1
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Open any file
2. Click on file on the top bar
3. Search bar will open (see picture)
4. Open other file
5. Previous file won't stay open but is in OPEN EDITORS

Selecting keep open on the file does not keep the tab open

![Screenshot 2020-07-15 at 19 36 50](https://user-images.githubusercontent.com/27967456/87578335-91d14980-c6d4-11ea-8ed4-ce383a960e92.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Sorry, I don't understand, can you explain more what you mean by 

> Previous file won't stay open

**Comment by Martin-Karsten** [comment]
I will try to explain.
It seems like there are 2 issues at once.
As you can see on the picture a file called Settings is open. When i click on this file (where the arrow points in the image) the search bar opens. When i double click on it or select `leave open` this file (or tab) does not stay open. When i click on another file in the sidebar another file opens instead.
Let's say i have another file called index.js. I click on index.js to open it, the Settings file (tab) will close. Settings should stay open but now instead index.js opens and Setting closes. And now when i click on index.js (like with Settigns before) the search bar opens.

**Comment by roblourens** [comment]
Is your issue just that you can't see the Settings tab after opening index.js? Maybe you disabled tabs by mistake then? Check the setting `"workbench.editor.showTabs"`

**Comment by Martin-Karsten** [comment]
You are right. For some reason "workbench.editor.showTabs" was set to false. I don't know how that happened. Sorry to bother you with such a simple problem. I will close this issue. Thanks a lot.
