### ISSUE TITLE
Eslint Client could not be started

### ISSUE THREAD

**Issue by vmittal26** [microsoft/vscode#102621]
My Eslint Extension not getting started , Please refer screen shot ( version and eslint error that is coming)  , I have tried un installing VS code again
![version](https://user-images.githubusercontent.com/34622587/87578197-b982da80-c6f1-11ea-95a7-a1ce2d9e7523.png)
![Esclient_Cleint_Could_Not_Be_Started](https://user-images.githubusercontent.com/34622587/87578272-cef80480-c6f1-11ea-8a60-809081515cc0.png)

**Comment by vmittal26** [comment]
Hi , 

Is there any update for this issue , requesting for resolving this issue , since linting is required for my Project , the problem started coming up when I accidentally installed ts-lint plugin , on removing ts-lint ,is still giving above error

**Comment by Sadi224** [comment]
Hey

**Comment by dbaeumer** [comment]
Which version of ESLint are you using. 

And is there anything in the ESLint output channel.

If not can you provide me with a GitHub repository I can clone that demos this?

**Comment by vmittal26** [comment]
@dbaeumer  I think issue is not related to repo , let me share it though , git repo is 'https://github.com/vmittal26/react-redux-sample-app.git'

issue might be related to somehow my local vs code setup , eslint was working fine in my system , some days back mistakenly installed 'ts-lint' extension that created this issue and even after un installing ts-lint extension problem still exists ,I have tried many options ( uninstalled vscode , removed all extensions folder locally etc.) but problem still exists ,  eslint works fine in my other system though

**Comment by dbaeumer** [comment]
Actually the provided repository works for me without problems. Is there anything in the ESLint output channel?

**Comment by vmittal26** [comment]
Attaching screen shot from ESLINT console

![eslint_issue_image_1](https://user-images.githubusercontent.com/34622587/88774764-7a4c9300-d1a1-11ea-9f87-16bd46147a99.png)

**Comment by dbaeumer** [comment]
How do your settings look like. Could it be that you set trace to `null` which is actually not supported :-)

**Comment by dbaeumer** [comment]
Actually I fixed the problem on latest already: https://github.com/microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/common/connection.ts#L195

As a workaround make sure you don't specify trace values with `null`

**Comment by vmittal26** [comment]
@dbaeumer  sorry but I did not mention explicit set anything , and also I dont know where to set trace values

Could please specify where these settings have to be done
