### ISSUE TITLE
Webview -> VS Code added an outline to an Icon and I can't remove

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#102653]
- VSCode Version: 1.47
- OS Version: Windows 10

Steps to Reproduce:

VSCode added this outline to the icon and I can't remove
![image](https://user-images.githubusercontent.com/55927613/87615996-66595980-c6ea-11ea-872e-e9d9faf12295.png)

![image](https://user-images.githubusercontent.com/55927613/87616217-f4354480-c6ea-11ea-9e02-ceb7bdc592c5.png)

Outside of VSCode this outline is not present
![image](https://user-images.githubusercontent.com/55927613/87616034-82f59180-c6ea-11ea-81e4-e9d316e6bbf9.png)

**Comment by gjsjohnmurray** [comment]
Maybe a focus indicator? Does it disappear if you click into another field on your webview?

**Comment by AllanOricil** [comment]
> Maybe a focus indicator? Does it disappear if you click into another field on your webview?

No haha

**Comment by mjbvz** [comment]
Have you tried using any css to remove it?

**Comment by AllanOricil** [comment]
> Have you tried using any css to remove it?

I just added this and it worked

```css
a:focus,
i:focus{
    outline: none !important;
}
````
