### ISSUE TITLE
Error remove first charactor in document type cs

### ISSUE THREAD

**Issue by trinhpapa** [microsoft/vscode#102674]
When I press Ctrl + S repeatedly many times. The first characters are automatically deleted. I have used unikey to type Vietnamese, it has no problem before.

**Comment by roblourens** [comment]
It might be helpful if you can provide a gif of this?

**Comment by roblourens** [comment]
Also, does it happen if you start with `--disable-extensions`?

**Comment by trinhpapa** [comment]
> 
> 
> Also, does it happen if you start with `--disable-extensions`?

I used except for the extension. It works well and there are no problems. Is there a problem with my extensions? In previous versions it was normal.

**Comment by trinhpapa** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23254838/87806967-e1a14380-c881-11ea-9791-827d3adb5719.gif)

**Comment by rebornix** [comment]
It's caused by one of your extensions, you can find which one is misbehaving by disabling extensions one by one
