### ISSUE TITLE
Symbols break TypeScript syntax highlighting

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode#10269]
- VSCode Version: 1.4.0
- OS Version: Windows 10

![symbols](https://cloud.githubusercontent.com/assets/261509/17462520/42d6858a-5cb0-11e6-9607-394656cc6e26.png)

```ts
class Test {
    public before() {
        // ...
    }

    public [Symbol.iterator]() {
        // ...
    }

    public after() {
        // ...
    }
}
```

Seems to break the GitHub highlighting as well. =)

Generators are also affected: `public *[Symbol.iterator]() { // ... }`

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#236
