### ISSUE TITLE
Ctrl+V pastes twice on Webview running inside VSCode

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#102647]
- VSCode Version: 1.47
- OS Version: Windows 10

Steps to Reproduce:

1. Install sfdx cli (Salesforce CLI)
2. Create a Dev Account on Salesforce to get a DevHub (https://developer.salesforce.com/signup)
3. Authenticate the Dev Hub using `sfdx force:auth:web:login -a NAME`
4. Set the Dev Hub as your defaultdevusername using `sfdx force:config:set defaultusername=NAME -g`
5. Now Install the Salesforce SOQL Editor extension
6. Create an sfdx project using the commnad `sfdx force:project:create -n PROJECT_NAME`
7. Open this project with VS Code.
8. Wait a few seconds until the extension is Activated. It activates onCommand or when it Identifies the file called `sfdx-project.json`
9. Open the extension with the command `SFDX: SOQL Editor`
10. Paste anything inside the Editor (this editor in the webview was made using Codemirror)
11. Notice the text was pasted twice.

#### Webapp running inside vscode
![image](https://user-images.githubusercontent.com/55927613/87610088-b4fef780-c6da-11ea-9bf3-b2166aad7f22.png)

#### Webapp running outside
![image](https://user-images.githubusercontent.com/55927613/87610075-aca6bc80-c6da-11ea-9101-711a37012a04.png)

<b>Obs:</b> I run the app locally, outisde of vscode, and this behavior did not happen. Somehow vscode is triggering the paste twice.

If you can't reproduce, lets do a quick call for me to show it to you.

**Comment by connor4312** [comment]
Thanks for the good issue, this duplicates https://github.com/microsoft/vscode/issues/102647 and will be fixed in the upcoming Insiders (targeting release tomorrow) 

/duplicate
