### ISSUE TITLE
Manjaro Linux: VS Code snap crashes

### ISSUE THREAD

**Issue by Allencs16** [microsoft/vscode#102651]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. in manjaro when you open a new tab and gonna save vs code stop running and closes
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by theopenroad** [comment]
This happens to me too. Latest version of VS code, and Manjaro 20.0.3.

VS code crashes every time I try to open certain files (any `.js`, `.ts`, or `.tsx` file, also trying to open `help:about`).

**Comment by bpasero** [comment]
@Allencs16 @theopenroad are you using Linux Snap?

**Comment by theopenroad** [comment]
@bpasero Yes, VS code is installed from Snap. I have already tried reverting to the previous version using `sudo snap revert code`, but it didn't fix the crashing.

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by mattwr18** [comment]
This is also happening to me on:
```
ManjaroLinux 30.0.3 
vscode 1.47.1
```
here is a screen recording:
![Peek 2020-07-16 09-56](https://user-images.githubusercontent.com/26943915/87643217-da2b4e80-c74a-11ea-9ac7-82c3822022f8.gif)

**Comment by Alex-K1m** [comment]
I had the same issue and I tried to disable eslint as it was mentioned before. That prevented vscode from crashing after startup, but when I select `help > about` from the menu it crashes again. Selecting `about` crashes vscode even with all extensions turned off. Finally I've installed vscode from AUR and it works fine.

<details><summary>System info</summary>
VSCode version: 1.47.1 (snap)
Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.15.0
Kernel Version: 5.4.44-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7.7 GiB of RAM
</details>

**Comment by joaomoreno** [comment]
Ah this is the ESLint native popup!

**Comment by theopenroad** [comment]
@Alex-K1m Thanks for the suggestion. I also just installed Code-OSS from the AUR and everything works. Thank you!

**Comment by mattwr18** [comment]
me too @theopenroad

**Comment by Allencs16** [comment]
> @bpasero Yes, VS code is installed from Snap. I have already tried reverting to the previous version using `sudo snap revert code`, but it didn't fix the crashing.
Vc

Oh you give-me hope for one second

**Comment by Allencs16** [comment]
> This is also happening to me on:
> 
> ```
> 
> ManjaroLinux 30.0.3 
> 
> vscode 1.47.1
> 
> ```
> 
> here is a screen recording:
> 
> ![Peek 2020-07-16 09-56](https://user-images.githubusercontent.com/26943915/87643217-da2b4e80-c74a-11ea-9ac7-82c3822022f8.gif)
> 
> 

Nice thanks
