### ISSUE TITLE
Links can't be followed with the right click menu

### ISSUE THREAD

**Issue by Yash-Singh1** [microsoft/vscode#102648]
When you would like to go forward to a link inside Visual Studio Code you can do Control + Click, but you can't do so in the right-click menu. This is a small feature suggestion. Here is an example. If I have a script tag with the src attribute to say example.com/library.js, then when you click on the link an option appears to do Control + Click to go on to the link. 
![Screenshot from 2020-07-16 13-03-42](https://user-images.githubusercontent.com/53054099/87717201-e4f2dd00-c764-11ea-962e-900bf5f22e98.png)
However, if you right-click on the link saying https://www.example.com/library.js, it will not show in the right-click menu an option to go on to the link in your browser. This isn't that important but it is just a small suggestion.
![Screenshot from 2020-07-16 13-04-47](https://user-images.githubusercontent.com/53054099/87717312-09e75000-c765-11ea-9f76-969dcf021177.png)

**Comment by roblourens** [comment]
A link where? There are different types of links handled differently.

**Comment by roblourens** [comment]
Question is edited, thanks
