### ISSUE TITLE
TypeScript colors get broken for the rest of file

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10267]
- VSCode Version: Code - Insiders 1.5.0-insider (1a7ca5a77bf6b63951e499ea93b7316d36118ade, 2016-08-05T07:14:50.554Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

```ts
let k=true
setTimeout((()=> {
    return (function () {
        return (function () {
            return (function () {
                return (function () {
                    return (function () {
                        return (function ():any {
                            if (k) {
                                if (k) {
                                    return (function () {
                                        if (true) {
                                            return (function() {
                                                return 'broken here';
                                            });
                                        }
                                    });
                                }
                                return 'broken going forward';
                            } else {
                                return 'broken here also'
                            }
                        })
                    });
                });
            });
        });
    })
}));

console.log('will be broken for rest of the file')
```

![image](https://cloud.githubusercontent.com/assets/1723815/17462435/020fced8-5c7b-11e6-99d9-c06e63d34713.png)

**Comment by thienohs** [comment]
Also happen with Javascript file because of deeply nested code (over 14 levels)
VSCode Version: 1.4.0 and 1.5.0-insider
OS Version: Windows 8.1 and Windows 10
Steps to Reproduce:

1. Type the script below in your editor.
`function aFn(){
    function aFn(){
        function aFn(){
            function aFn(){
                function aFn(){
                    function aFn(){
                        function aFn(){
                            function aFn(){
                                function aFn(){
                                    function aFn(){
                                        function aFn(){
                                            function aFn(){
                                                function aFn(){
                                                    function aFn(){
                                                        function aFn(){
                                                            function aFn(){
                                                                function aFn(){
                                                                    function aFn(){
                                                                        function aFn(){
                                                                            function aFn(){
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}`
2. Syntax highlighting will be lost after line 15.
![image](https://cloud.githubusercontent.com/assets/4403470/17467087/b2c82b98-5d5d-11e6-9140-a2ccc03a0e0b.png)

**Comment by thanhtr** [comment]
Same problem as mentioned above with Javascript on Mac, with the same test
VSCode Version: 1.4.0 and 1.5.0-insider
OS Version: OS X El Capitan 10.11.6

**Comment by alexandrudima** [comment]
Dup of #9937
