### ISSUE TITLE
renaming python variable is too slow

### ISSUE THREAD

**Issue by wenmin-wu** [microsoft/vscode#102683]
It takes me about 50 seconds to rename a variable in python file

- VSCode Version: 1.47.1
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Find a python script with about 400 lines.
2. Right-click a variable and select rename, key in the new name, and press the "Enter" button.

Does this issue occur when all extensions are disabled?: Yes

**Comment by MiguelGuthridge** [comment]
Probably belongs on https://github.com/Microsoft/vscode-python.
I haven't got this issue. Renaming takes about half a second in my largest project (about 3000 lines in about 15 files).

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
