### ISSUE TITLE
Bug in jupyter notebook copy and paste function

### ISSUE THREAD

**Issue by SPRYK** [microsoft/vscode#102664]
After VSCode update when I use CTRL+C and CTRL+V on any cell in jupyter notebook (.ipynb). It will happen like I paste twice such as I want to copy "ABCD" but when I paste it will create "ABCD""ABCD". This happen only in jupyter notebook.

**Comment by AngelOnFira** [comment]
@SPRYK just wondering why you closed this? I'm having the same problem, and if there is an easy solution then I wouldn't mind knowing it :smiley:
