### ISSUE TITLE
cannot enable or disable extension

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#102645]
Issue Type: <b>Bug</b>

I cannot enable or disable the ms-vscode.cpptools extension.

repro steps:

- install ms-vscode.cpptools
- disable ms-vscode.cpptools
- attempt to 'enable in workspace'

right-click shows me this:

![image](https://user-images.githubusercontent.com/1088194/87609477-858ac380-c6b7-11ea-9688-f4bf9db2972f.png)

and the details page only shows the 'Uninstall' button:

![image](https://user-images.githubusercontent.com/1088194/87609572-c4b91480-c6b7-11ea-9a95-bc623f16fdb0.png)

i'm pretty sure this is a regression.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (4.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1:2222|
|OS|Linux x64 3.10.0-1127.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|3.70GB (1.79GB free)|
|VM|100%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.2
vscode-markdownlint|Dav|0.36.1
gitlens|eam|10.2.2
php-debug|fel|1.13.0
cmake|twx|0.0.17
change-case|wma|1.0.0
plsql-language|xyz|1.8.2
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4

</details>

**Comment by sandy081** [comment]
I am not able to repro this. May I know how you are disabling the extension?

**Comment by Spongman** [comment]
i used the 'disable' and 'reload required' buttons in the details page.

**Comment by sandy081** [comment]
You are in a VS Code Window that is connecting to WSL - I do not think it shall matter. 

Can you please try to reproduce this on a Window that is not connecting to WSL?

If you are able to repro, can you please record the gif / video and share it with us?

**Comment by sandy081** [comment]
I can reproduce this and it happens only in remote window (WSL). 

As a workaround you can enable the extension from a normal window.

**Comment by seahindeniz** [comment]
Hi @sandy081 

Thanks for referencing this issue. I'd searched for "built-in" related issues and missed this one. Sorry about that 🙂

The workaround you suggest can only be applied to extensions which has globally disabled. If an extension disabled only for a workspace, enabling from a normal window isn't going to help for WSL users, like me 🙁 

I have also shared another workaround here https://github.com/microsoft/vscode/issues/102905#issuecomment-661285115 but that is a "resetting" approach

PS: Following the instructions in here https://github.com/flowtype/flow-for-vscode/blob/master/README.md#setup, had lead me to have this issue in the first place. I didn't know I would be affected by following the instructions with a remote VSCode session.

> * Set `javascript.validate.enable` option to `false` **or** completely disable the built-in TypeScript extension for your project (see gif below):

<p align="center">
  <img src="https://github.com/flowtype/flow-for-vscode/raw/master/readme/flow-disable-tsc.gif"/>
</p>

@orta could you please add at least a warning for WSL users, till this issue has fixed?

**Comment by sandy081** [comment]
> The workaround you suggest can only be applied to extensions which has globally disabled. If an extension disabled only for a workspace, enabling from a normal window isn't going to help for WSL users, like me

Yes, it does not work for workspace disabled extensions.

Fixed it. This will be available in our next stable release in three weeks. You can also user our insiders tomorrow which will have the fix.

**Comment by sandy081** [comment]
To verify

- In a remote window (WSL / Container / SSH), disable any extension that exists on locally and remotely (also try built-in extensions) for the workspace
- Reload window and make sure you can enable the extension back.
