### ISSUE TITLE
Git decorations not working when the folder is opened using a Junction

### ISSUE THREAD

**Issue by carlocardella** [microsoft/vscode#102656]
- VSCode Version:
```
Version: 1.47.1 (user setup)
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:42:53.386Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```
- OS Version:
```
Version 2004 (OS build 19041.388)
```

Steps to Reproduce:

1. Open a local Git repo folder through a folder junction
2. Git decorations are missing from the Explorer tree view
3. Open the same folder using the target path directly (do not use the Junction path): Git decirations are shown as expected

_Junction structure_
```
44 carloc@CARLOC1 2020-07-15T18:56:52 carloc: Get-Item C:\Users\carloc\Git\

    Directory: C:\Users\carloc

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
l----           5/14/2020 10:52 AM                Git -> D:\Git\
```

_Using the junction path: C:\Users\\\<user>\Git\PSToolbox_
![image](https://user-images.githubusercontent.com/5784415/87617992-99412480-c6cd-11ea-9866-4b499982d4fb.png)

_Using the target path: D:\Git\PSToolbox_
![image](https://user-images.githubusercontent.com/5784415/87618053-bece2e00-c6cd-11ea-9e98-51e66d61e666.png)

Does this issue occur when all extensions are disabled?: **Yes**

This problem reproduces in the latest Insiders build

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/100274
