### ISSUE TITLE
VSCode always debugging when executing commands without debug mode

### ISSUE THREAD

**Issue by icoleto** [microsoft/vscode#102689]
- VSCode Version: June 2020 (version 1.47)
- OS Version: macOS Catalina 10.15.5

Steps to Reproduce:

Working on  different NodeJS applications and with option "Auto attach" always on (needed for debug) when I run some command like "`jest` `npm run start`, `npm ci`, `node`, `ts-node`" without debug flags vscode always activate Debugger listener as you can see on the next gif.
When I set "Auto attach" off It never execute debugger mode when using comands with debug mode flags

![crazy-debug](https://user-images.githubusercontent.com/12449936/87658273-41053380-c75c-11ea-80e3-f5318ec6728d.gif)

This happened to me again when update vscode using:
- VSCode Version: June 2020 (version 1.47)
- OS Version: Linux Mint 19.1

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
See https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467. This will be fixed in the recovery release coming in a few hours.

/duplicate
