### ISSUE TITLE
Node debug console does not use the full terminal width

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode#102693]
Issue Type: <b>Bug</b>

When starting a node debug session in the integrated terminal, it no longer (I've noticed this in 1.47.0 for the first time) uses the full terminal width.

This is my `.vscode/launch.json` for a simple TypeScript project:
```jsonc
{
	// Verwendet IntelliSense zum Ermitteln möglicher Attribute.
	// Zeigen Sie auf vorhandene Attribute, um die zugehörigen Beschreibungen anzuzeigen.
	// Weitere Informationen finden Sie unter https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Debug locally",
			"port": 9229,
			"runtimeArgs": [
				"--async-stack-traces",
				"--inspect-brk=9229",
				"-r",
				"ts-node/register/transpile-only.js",
				"${workspaceFolder}/src/index.ts"
			],
			"console": "integratedTerminal",
			"skipFiles": [
				"<node_internals>/**"
			],
			"sourceMaps": true
		}
	]
}
```

When I debug this using <kbd>F5</kbd>, the first time sometimes looks normal. Afterwards all attempts have this weird formatting:
![grafik](https://user-images.githubusercontent.com/17641229/87666667-4e74ea80-c769-11ea-8e73-16ea4f494b42.png)

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (23.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
toggle-excluded-files|eam|1.7.0
EditorConfig|Edi|0.15.1
RunOnSave|eme|0.2.0
json-tools|eri|1.0.2
prettier-vscode|esb|5.1.3
vscode-pull-request-github|Git|0.18.0
vscode-test-explorer|hbe|2.19.1
rest-client|hum|0.24.1
compare-folders|mos|0.14.0
vscode-docker|ms-|1.3.1
vscode-language-pack-de|MS-|1.47.3
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
hexeditor|ms-|1.1.0
hide-gitignored|npx|1.1.0
vscode-jest|Ort|3.2.0
typescript-mono-repo-import-helper|q|0.0.6
project-snippets|reb|0.5.0
vscode-sort-json|ric|1.18.0
sort-lines|Tyr|1.9.0
vscode-icons|vsc|10.2.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by AlCalzone** [comment]
What kind of info do you need?

**Comment by weinand** [comment]
Sorry, for some strange reason my question and even my screencast is missing... So here is it again:

Your screenshot does not show the "debug console" but the integrated terminal.
With it I could not reproduce the problem on Windows:

![2020-07-21_12-43-37 (1)](https://user-images.githubusercontent.com/1898161/88665782-76f0d300-d0df-11ea-894a-4ecaeb5dd748.gif)

Are you running a remote session in the terminal?

**Comment by AlCalzone** [comment]
I've just tested it on another system and I can't reproduce it here. I'll check for differences in settings and extensions, but that won't happen before tomorrow evening.

> Your screenshot does not show the "debug console" but the integrated terminal.

Yes, I've configured the debug session to use the integrated terminal - maybe you guys call that differently.

> Are you running a remote session in the terminal?

No, but I configured VSCode to use `git bash` as the terminal.

**Comment by weinand** [comment]
I remember another instance of this problem where the problem only showed up on one system. In that case a ssh session was used.

In the issue's title you said "debug console", but the screenshot shows an "integrated terminal". That's the reason why I mentioned terminology.

I tried to reproduce by using "git bash" too, so that does not seem to be the source of the problem.

**Comment by AlCalzone** [comment]
> In the issue's title you said "debug console"

Yeah, this is why: 
![grafik](https://user-images.githubusercontent.com/17641229/88928337-04b3f600-d279-11ea-9dcd-84b4f8ed178a.png)

I just checked again with all extensions disabled because I suspected the Remote SSH extension - but it still happens:
![ezgif com-video-to-gif(4)](https://user-images.githubusercontent.com/17641229/88928180-ca4a5900-d278-11ea-8637-d643230964c8.gif)

Not sure what else I can do to help you narrow it down.

**Comment by weinand** [comment]
@Tyriar do you have an idea why output does not cover the full width?

**Comment by AlCalzone** [comment]
For what it's worth, the line seems to be exactly as long as `Debugger listening on ws://...-some-log-url`

**Comment by AlCalzone** [comment]
Doesn't seem to be a layout problem, the div (and containing canvas) stretches across the entire space:
![grafik](https://user-images.githubusercontent.com/17641229/89035631-96843780-d33b-11ea-8349-981e9a90e399.png)

**Comment by Tyriar** [comment]
I would guess the fact that it's Git Bash on Windows is probably the reason for it, Git Bash has always behaved a little weird through conpty in my experience because both of them try to emulate unix ptys. You could try updating git/git bash and using cmd.exe as `terminal.integrated.automationShell.*`

**Comment by AlCalzone** [comment]
Dang! The bug seems to be gone in git for Windows 2.28.
