### ISSUE TITLE
Source control panel empty after using it to commit

### ISSUE THREAD

**Issue by johnjesse** [microsoft/vscode#102623]
- VSCode Version: Version: 1.47.1 (user setup)
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:42:53.386Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
- OS Version: 

Steps to Reproduce:

1. Open Code
2. Make changes, do a commit, and change to search or some other app in the side bar whilst it commits
3. go back to the source control app - the panel is empty

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
Maybe a dup of #102358 which is fixed in upcoming 1.47.2 and already present in Insiders. Are you able to test your case with Insiders?

**Comment by johnjesse** [comment]
so quick :), I should be able to -

**Comment by johnjesse** [comment]
Yes it is, Thankyou!
