### ISSUE TITLE
Enhance experimentation service to support new framework

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#102620]
1. Extend the experimentation service to support the [VS Code Treatment Assignment Service Module](https://www.npmjs.com/package/vscode-tas-client)
2. Test with a new simple experiment

**Comment by sbatten** [comment]
This will be verified through the EXP service during endgame.

**Comment by joaomoreno** [comment]
@sbatten Should this be closed? 🤔

**Comment by isidorn** [comment]
@sbatten can you please provide steps to verify?
Or if you mentioned that will be verified via EXP service should this then not have the verification-needed label?

**Comment by sbatten** [comment]
I can remove the verification-needed label. @sana-ajani please verify with the EXP service and comment here.

**Comment by sana-ajani** [comment]
Yep, this is working, currently we are running the A/A test in insiders.
