### ISSUE TITLE
SCM: Allow different providers sort order

### ISSUE THREAD

**Issue by kakrofoon** [microsoft/vscode#102606]
Especially for folks with dozens of source code providers, it would be helpful to have options to sort the providers parametrically, rather than load order.

In the source control providers currently get:
development-tools
common
image_processing

I would like the option to get:
common
development-tools
image_processing

-Or-

image_processing
development-tools
common

**Comment by A30004028** [comment]
This! Its especially annoying when a newly opened repo is not added to the list but is somewhere in the middle of the unsorted list.

Even the screenshot from the new unified Source Control list shows an unsorted list.

![image](https://user-images.githubusercontent.com/57081675/89958980-b6dabd00-dc7e-11ea-9f30-9a1a9fa6f25b.png)
