### ISSUE TITLE
Lag with GPU acceleration

### ISSUE THREAD

**Issue by galich** [microsoft/vscode#102661]
- VSCode Version:

Version: 1.47.1 (user setup)
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:42:53.386Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

- OS Version: Windows 10 2004

Steps to Reproduce:

1. scroll any text with mouse or keyboard, activate terminal with hotkey, move terminal pane from left to right, scroll in sidebar, resize panes - pretty much any action with any kind of input
2. response time between 2 and 10 seconds

Does this issue occur when all extensions are disabled?: Yes

* Things go back to normal when running `code --disable-gpu`
* Similar lags observed with Insider version

Version: 1.48.0-insider (user setup)
Commit: cb31fc6ce2b4da3520392b622aa3ebc5b313533b
Date: 2020-07-15T05:34:49.078Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041

Performance data collected here https://github.com/microsoft/vscode/issues/101596#issuecomment-658932185

This is all happening inside virtual machine: VMWare, 12 core CPU, 16GB RAM, accelerated graphics.
Host: Windows 10 2004, NVidia GeForce GTX 1070, i8700K CPU 12 virt cores.
No other electron app seems to be affected in that VM and it was working fine previously. Doesn't seem to be related to any rare VMWare or NVidia driver update.

cc @deepak1556

**Comment by deepak1556** [comment]
Are you still experiencing this issue with latest stable ?
