### ISSUE TITLE
Option to hide git repos without any files checked out

### ISSUE THREAD

**Issue by atlanteh** [microsoft/vscode#102685]
I have about 20 repos on my workspace, but I only use 2-3 at a time.
The new consolidated view for all repos is great, but for many repos it creates a problem as all the not used repos clog up the entire pane.
It would be great if there was an option to hide repos that have no checked out files.

See below for reference. I'd like the ability to hide all repos that don't have a chevron next to them
![image](https://user-images.githubusercontent.com/3952700/87653116-bfaea080-c75d-11ea-9666-e5c3422ecf0e.png)

Thx!

**Comment by joaomoreno** [comment]
Merging with #102118
