### ISSUE TITLE
Unable to debug execution

### ISSUE THREAD

**Issue by zhangwf6670123** [microsoft/vscode#102657]
Issue Type: <b>Bug</b>

Nodejs 8.15.0 is used to debug and run without execution

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (12.45GB free)|
|Process Argv|D:\代码仓库\CV_SmartWorx1.0\FWebView2.0\serverCode\dataLayers\pSpace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.47.3
vetur|oct|0.24.0

</details>

**Comment by connor4312** [comment]
Please see https://github.com/microsoft/vscode/issues/102166#issuecomment-657138385 -- this will be fixed in tomorrow's release!

/duplicate

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!
