### ISSUE TITLE
Reopen new search tab

### ISSUE THREAD

**Issue by jaywick** [microsoft/vscode#102659]
When reopening tabs (`workbench.action.reopenClosedEditor`) I'd like to reopen the new search tab as well.

![Search tab not reopening](https://user-images.githubusercontent.com/3955052/87622913-811de380-c767-11ea-847d-b333d740a439.gif)

**Comment by bpasero** [comment]
@JacksonKearl the history in the workbench drives this through this call:

https://github.com/microsoft/vscode/blob/8d8cb8b88348a0e4473422b72540bfe781dec67c/src/vs/workbench/contrib/searchEditor/browser/searchEditor.contribution.ts#L112-L114

A search editor would need to be serializable even when closed to make this work.

**Comment by NotWearingPants** [comment]
Related: #97285 #86864

Although the search editor is not a webview.

**Comment by JacksonKearl** [comment]
\duplicate 99694
