### ISSUE TITLE
Branch UI in status bar doesn't update when switching projects

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#102625]
Version: 1.48.0-insider
Commit: e7920dce7bfd0b707ebfc0a5379c6edd2233e475
Date: 2020-07-10T11:55:11.286Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

I had a project open where I had made a new branch ("sana-ui-updates" in the image). I opened a new window and new folder with a project that had not been initialized yet. The branch UI in the status bar still shows the branch from my previous project. 

![image](https://user-images.githubusercontent.com/9721254/87582845-db4b7580-c68f-11ea-9455-017b91ceefcf.png)

**Comment by joaomoreno** [comment]
Hmm I can't reproduce this. What does the SCM view show?
