### ISSUE TITLE
The top of the screen is not displayed correctly when maximized.

### ISSUE THREAD

**Issue by maccyo12** [microsoft/vscode#102675]
Issue Type: <b>Bug</b>

When the window is maximized, the upper part of the screen (near the title bar) may not be displayed.

This problem occurs about once every half month.
The condition of reappearance is unknown.
Restarting the computer will fix the problem.

When the window is restored to normal size (Windows Key + Down Arrow), it will be displayed normally, but it will not be displayed again when the window is maximized.

note: Translated with www.DeepL.com/Translator (free version)

-----

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.60GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by maccyo12** [comment]
Screen Shot

![vscode_image](https://user-images.githubusercontent.com/21338006/87641829-9dc81480-c783-11ea-828d-dcc9bc852d4d.png)

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ?
