### ISSUE TITLE
C++ syntax highlighting issue

### ISSUE THREAD

**Issue by MrSparc** [microsoft/vscode#102687]
- VSCode Version: June 2020 (version 1.47.1)
- OS Version: Linux 4.12.14-lp151.28.52-default x86_64 GNU/Linux

Steps to Reproduce:

1. Paste the following code using C++ as selected language mode to enable the syntax highlighting
```cpp
void foo(const char *uri)
{
  if (uri == NULL) {
    printf("uri is nullptr\n");
  } else if (strncmp(uri, "/put?", 5) == 0) {
    printf("PUT\n");
#ifdef ALLOW_POST // a comment here prevents the code after the '?' char from being correctly parsed by the grammar syntax rules for C++
  } else if (strncmp(uri, "/post?", 6) == 0) {
    printf("POST\n");
#endif
  } else if (strncmp(uri, "/get?", 5) == 0) {
    printf("GET\n");
  } else {
    printf("unknown\n");
  }
}
```
2. You can see that the syntax highlighting is broken after the '?' char in the line `if (strncmp(uri, "/post?", 6) == 0)`
3. Option 1: Remove the comment or change for a C-style comment (`/*...*/`)  and now the syntax highlighting is ok.
4. Option 2: Remove the `?` char from the line referenced in step 2 and now the syntax highlighting is ok.

This screen-capture shows the bug in action:
![cpp_syntax_higthlight_issue](https://user-images.githubusercontent.com/2487742/87656310-3b562080-c751-11ea-9ebb-22c4df3bb66d.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Moved to the repo that we get our C++ grammar from: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/494
