### ISSUE TITLE
ctrl + cmd + left/right arrows

### ISSUE THREAD

**Issue by rolandleth** [microsoft/vscode#102698]
VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:43:02.577Z), but also older
- OS Version: Darwin x64 20.0.0 - 10.16 (11), but also on 10.15.x

Steps to Reproduce:

1. Press ctrl + cmd + left/right arrows anywhere text input is involved (editor, terminal, search fields)
1a. The error sound isn't triggered anywhere text input isn't involved
2. Observe the error sound

I don't have these configured to any action, they don't seem to be system wide either (outside of VSCode the error doesn't play), it's not something related to Electron as far as I can tell (other Electron apps don't behave like this), they don't _do_ anything and assigning them to back/forward, for example, works, but the error sound _still_ plays.

Does this issue occur when all extensions are disabled?: Yes

Later edit: The bot added the `new release` label, but this happened on older versions as well, if I remember correctly, which is why I was never able to use the standard ctrl + cmd + left/right combination for going back and forth.

**Comment by Tyriar** [comment]
Last time I looked at this it was an Electron-specific issue and it also happened in Atom. Perhaps it will be fixed when we update to Electron 9?

**Comment by rolandleth** [comment]
Found a workaround for this, as it's apparently a Chromium "bug". I say "bug" and not bug, because it's the OS reacting to the fact that it has no action for that key combo, so it reacts with a bonk, because Chromium doesn't seem to intercept that, or tell the system that _it_ can handle that key combo. So it's a grey line 🙃

Either way, this workaround fixes it and not just in VSC, but also in any text field in macOS.

https://bugs.chromium.org/p/chromium/issues/detail?id=916460#c13

**Comment by deepak1556** [comment]
Closing as upstream issue is marked as `wontfix`
