### ISSUE TITLE
TypeScript type comment issue

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10261]
- VSCode Version: Code - Insiders 1.5.0-insider (1a7ca5a77bf6b63951e499ea93b7316d36118ade, 2016-08-05T07:14:50.554Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

```ts
export type Test = string // wrong comment color
                          // should be this
```

![image](https://cloud.githubusercontent.com/assets/1723815/17460530/cf4efefc-5c38-11e6-8c9a-f8608ddae2e1.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#237
