### ISSUE TITLE
Revert Node version limiting

### ISSUE THREAD

**Issue by jdforsythe** [microsoft/vscode#102626]
![Screen Shot 2020-07-15 at 2 55 50 PM](https://user-images.githubusercontent.com/286972/87584472-8fa6c500-c6ab-11ea-8859-b955b9c15c22.png)

We use VSCode to work on new and legacy projects. Starting 10 minutes ago, I can no longer debug the legacy project. This is still a production application and we are working to upgrade Node versions in the services one at a time, but still have a few on v6 due to dependency and other issues we're working through.

Is there a workaround to force VSCode to still switch to Node v6?

**Comment by connor4312** [comment]
You can set `debug.javascript.usePreview: false` to use the old debugger. However, this option will go away at some point in the future; Node <7 uses a different debug protocol which we no longer support.
