### ISSUE TITLE
Can't create file in Codespaces

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoft/vscode#102643]
https://online.visualstudio.com/environment/4e486781-a9f9-44cb-a8cd-ca7fbca7a265 I try to create a new file and I get 
Unable to write file 'vscode-remote://vsonline+4e486781-a9f9-44cb-a8cd-ca7fbca7a265/home/vsonline/workspace/Test.tx' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/home/vsonline/workspace/Test.tx')

What use is an editor with no files?

**Comment by bpasero** [comment]
Can you please report this issue here: https://github.com/MicrosoftDocs/vscodespaces/issues
