### ISSUE TITLE
version 1.47.1 debug prelaunchtask does not get called on restart

### ISSUE THREAD

**Issue by 1057437122** [microsoft/vscode#102615]
- VSCode Version: 1.47.1
- OS Version:mac os 10.15.5

Steps to Reproduce:

1.install vscode 1.47.1
2.open a nodejs project which works fine before this version (like in version 1.46.0)
3.start debug => the status bar shows now is building and then start the project
4.press restart in debugger => some times it calls the prelaunchtask some times it doesnot call
5.reinstall version of 1.46.0 => it works fine

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
Thanks for the issue, see here for a solution https://github.com/microsoft/vscode/issues/102296#issuecomment-658889772

/duplicate
