### ISSUE TITLE
[suggestion] Cursor animations tweak

### ISSUE THREAD

**Issue by traavnik** [Microsoft/vscode#10277]
I like new cursors in v1.4.0 (#7923, #8153), but I don't like how they glitch whenever their position changes.
I would suggest swapping animation direction to make transition more fluid.

Current expanding  animation:
(notice how cursor disappears in a single frame when animation gets loaded)
![cursorbefore](https://cloud.githubusercontent.com/assets/20891943/17464795/58520344-5ce7-11e6-9735-201a5752f2b1.gif)
```
@keyframes cursor-expand {
	0%,
	20% {
		transform: scaleY(0);
	}
	80%,
	100% {
		transform: scaleY(1);
	}
}
```
Inverted animation:
![cursorafter](https://cloud.githubusercontent.com/assets/20891943/17464805/bae2a54a-5ce7-11e6-9593-e911e178e80a.gif)
```
@keyframes cursor-expand {
	0%,
	20% {
		transform: scaleY(1);
	}
	80%,
	100% {
		transform: scaleY(0);
	}
}
```
The glitch is also visible with other cursor options that use soft transitions.

I've also noticed some delay before cursor animations is loaded. I'm not sure if that's by design and what exactly causes it (can't read .ts that well yet, let alone compile stuff to try it out). I would assume it's intentional delay that was originally used for blinking cursor. I think that new cursors could be used without delay, if every animation got inverted.

Edit: It might be better to leave delay as is in order to avoid distracting animations while typing and moving cursor. In such case, blinking animation shouldn't be inverted, only the ones with soft transitions should.

**Comment by alexandrudima** [comment]
I am open to tweaking the animations. PR welcome. fyi @kisstkondoros

**Comment by alexandrudima** [comment]
PR #11093 addressed this. Thanks to @sprinkle131313
