### ISSUE TITLE
Chinese characters in the output panel are displayed in garbled code

### ISSUE THREAD

**Issue by junjian-yuan** [microsoft/vscode#102747]
Open the dotnet project and execute the dotnet restore command.
Chinese characters in the output panel are displayed in garbled code.

VS Code version: Code 1.47.1
OS version: Windows_NT x64 19041.388

![20200717140637](https://user-images.githubusercontent.com/10084420/87754124-ca893400-c836-11ea-9ed0-56da6d11caef.png)

**Comment by sandy081** [comment]
I created a sample output channel with Chinese text and it shows correctly

<img width="604" alt="image" src="https://user-images.githubusercontent.com/10746682/91175248-cfb48b00-e6e0-11ea-918b-d47f82c0a3cd.png">

Please file an issue against dotnet extension or provide a sample extension to reproduce it.
