### ISSUE TITLE
suggest widget size

### ISSUE THREAD

**Issue by eltonlimaribeiro** [microsoft/vscode#102777]
Does anyone know if there is another simpler way to do this?

**This is not a proper solution, but a hack that might break after any program update!**

As VsCode is styled mainly using CSS to change the size you have to simply override default values.
This can be accomplished by using "Custom CSS and JS loader" extension and injecting your own CSS. 

_Width value is static 430px:_ 
`.monaco-editor .suggest-widget {
  width: 430px; 
} `

 _Height value is set inline on element by editor depending on how many suggestions there are so !important is necessary to owerride it:_ 
`.monaco-editor .suggest-widget>.tree {
  height: 300px !important;
}  `

_Originally posted by @povilasbaranovas in https://github.com/microsoft/vscode/issues/29126#issuecomment-639731615_

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest+label%3Aux
