### ISSUE TITLE
新建文件时总是提示选择编辑器

### ISSUE THREAD

**Issue by tinker-li** [microsoft/vscode#102756]
Issue Type: <b>Feature Request</b>

我是用的时Mac版，版本号是2020 (version 1.47).
我点击“file”--“new file”时，每次都提示我“select editor for XXX”。
但是当我使用快捷键“command+N”时，直接给我创建了一个文件。

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

**Comment by tinker-li** [comment]
Mac version 1.47.
Everytime I click “file”--“new file”, the vscode will raise a dialog-"select editor for 'Untitled-4'". The problem is that, everytime it will raise up.
If I choose keyboard shortcuts, I use "cammand+N", the dialog will not raise up.

**Comment by mjbvz** [comment]
Duplicate of #102289
