### ISSUE TITLE
Highlighting broken for "/*" '/*' and `/*`

### ISSUE THREAD

**Issue by DavidSouther** [Microsoft/vscode#10273]
- VSCode Version: Version 1.4.0 (1.4.0)
- OS Version: OSX 10.11.6 (15G31)

Steps to Reproduce:

1. Insert the string '/*' `/*` or "/*" in a Tyepscript file
2. The rest of the file is highlighted as a comment, to the next */

![screen shot 2016-08-07 at 11 14 18 am](https://cloud.githubusercontent.com/assets/498712/17463294/9b56260e-5c90-11e6-81c3-66194db117da.png)

**Comment by DavidSouther** [comment]
Oh hey, it looks like github has the same issue!

**Comment by aeschli** [comment]
I reproduced with the following code snippet:
class A {
    @Route.GET('/*')
    get(q: Request, s: Response): void {
        s.sendFile();
    }
}

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#235
