### ISSUE TITLE
NVM support for tasks.json and autodetected tasks

### ISSUE THREAD

**Issue by jahan01** [microsoft/vscode#102746]
I see there is way to mention runtime version in `launch.json`. But no such thing to specify in `tasks.json` and auto detected tasks.

Currently I am using nvm to manage different node versions and I am loading nvm with `--no-use` to reduce the shell startup times. So the shells started by tasks fails with exit code 127, they are not able to find npm/node runtime.

**Comment by jahan01** [comment]
For instance, in the below example 1st task always fail since there is no default node/npm available in path.
Second tasks works by using `nvm exec npm run watch`, but I cannot get it to work for all auto detected tasks.

<details>
<summary>tasks.json</summary>
<p>

```jsonc
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"options": {
				"shell": {
					"args": []
				}
			},
			"group": "build"
		},
		{
			"label": "nvm:npm watch",
			"type": "shell",
			"command": "nvm",
			"args": [
				"exec",
				"npm",
				"run",
				"watch",
			],
			"options": {
				"cwd": "${workspaceFolder}"
			},
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		},
	]
}
```

</p>
</details>

**Comment by alexr00** [comment]
This is by design. The `npm` task type relies on being able to just run `npm <script>`.

**Comment by alexr00** [comment]
It could be a good idea for a new extension. You could make an extension that handles the additional nvm initialization.
