### ISSUE TITLE
back button

### ISSUE THREAD

**Issue by bksubhuti** [microsoft/vscode#102702]
It would be nice if there was a back and forward button
I jump through my code and want to jump back and forth...
can grab clicks on code or search and clicks..
scrolling would be difficult.

or can also grab last file looked at and last clicked place.

**Comment by IllusionMH** [comment]
There are already actions:
Go Back `workbench.action.navigateBack` <kbd>alt</kbd>+<kbd>←</kbd>
Go Forward `workbench.action.navigateForward` <kbd>alt</kbd>+<kbd>→</kbd>


Is it what you are looking for? If not - describe differences please.

**Comment by gjsjohnmurray** [comment]
And if your mouse has the extra buttons you can use those too.

**Comment by bksubhuti** [comment]
great! I see I need more than three buttons to work by mouse..
Too bad the arrows are taken.

Bhante Subhuti

https://AmericanMonk.org
https://withmetta.net

**Comment by roblourens** [comment]
The above suggestions are the best we can do, we don't plan on adding a toolbar with navigation buttons or anything like that.
