### ISSUE TITLE
Installer only extracting read only file in MAC

### ISSUE THREAD

**Issue by ankitjt** [microsoft/vscode#102700]
- VSCode Version:
1.47.1
- OS Version:
MAC Catalina

Steps to Reproduce:

1. Download the zip from the vs code website
2. Unzip

Does this issue occur when all extensions are disabled?: No,

# Additional Info:

* I tried changing my github credentials that was linked , it got delinked and then couldn't login with new credentials.

* Tried to un-install and install the editor itself, there was no file in 'Application' folder.

* Downloaded a fresh copy and since that it still won't allow to update the editor

__Even after installing a fresh copy it still opens to my last project, is there no way to complete remove the application from my system , I even removed the extensions folder but still the same__

**Comment by joaomoreno** [comment]
What is the actual issue here?

**Comment by ankitjt** [comment]
The installer I get from vs code website is a .zip file and not .dmg file.
Secondly, it's only a "Read-Only" version hence I can't update, can't link my github account with it.

I hope this helps.

**Comment by joaomoreno** [comment]
> The installer I get from vs code website is a .zip file and not .dmg file.

This is as designed. Extract the ZIP and move Code to the Applications folder.

> Secondly, it's only a "Read-Only" version hence I can't update, can't link my github account with it.

What do you mean it's a read-only version? Can you show me a screenshot of the dialog which says that?

**Comment by ankitjt** [comment]
Here's the screenshot of message I get when I check for any updates.

![image](https://user-images.githubusercontent.com/48979824/87765748-d32d3a80-c835-11ea-9a10-94f201772bec.png)

**Comment by joaomoreno** [comment]
Did you click that link?
