### ISSUE TITLE
Webview Crashes while debugging

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#102716]
Issue Type: <b>Bug</b>

1. Debug a webview
2. Step through a function which changes properties of elements in the webview, such as padding.
3. Hit continue after you step out of that function
4. 🐛 The webview crashes

![recording](https://user-images.githubusercontent.com/4544166/87699481-eae7be80-c762-11ea-8c52-5fbe0cca44e4.gif)

VS Code version: Code - Insiders 1.48.0-insider (5e5fa3edde19d38ac512d65ccefe2a12ecab025a, 2020-07-16T13:12:57.510Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (23.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by deepak1556** [comment]
should be fixed in latest inisders.
