### ISSUE TITLE
Terminal VSCODE_GIT_IPC_HANDLE warning triangle

### ISSUE THREAD

**Issue by dbaileyut** [microsoft/vscode#102727]
- VSCode Version: 1.48.0-insider (system setup) 5e5fa3edde19d38ac512d65ccefe2a12ecab025a
- OS Version: Windows 10 x64 10.0.19041

Steps to Reproduce:

1. Launch VS Code insiders with --disable-extensions
2. Open the terminal pane
3. Not the warning that says:
```
Extensions want to make the following changes to the terminal's environment:

VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-114c7062bd-sock
```

Does this issue occur when all extensions are disabled?: Yes

Git version: 2.27.0.windows.1
This occurs with CMD.exe or Powershell.exe as the default terminal

![image](https://user-images.githubusercontent.com/7095040/87721223-b7655e00-c77b-11ea-8f52-c0ac0c9f228e.png)
![image](https://user-images.githubusercontent.com/7095040/87721290-d237d280-c77b-11ea-9109-959cd1c4b47b.png)

**Comment by Tyriar** [comment]
What's the issue?

**Comment by dbaileyut** [comment]
The warning triangle itself appearing in a default/out of box configuration. There doesn't appear to be any breaking behavior.

**Comment by Tyriar** [comment]
I think this is what enables git auth provided by VS Code

**Comment by joaomoreno** [comment]
This just appears to be a usability issue surrounding the feature and its UX, @Tyriar.

**Comment by GitProfAn** [comment]
Just to add my triangle message here. As recommended, I simple re-launch the active terminal.

+++

Extensions want to make the following changes to the terminal's environment:
VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-285b3099df-sock

![VSCODE_GIT_IPC_HANDLE](https://user-images.githubusercontent.com/48450635/95844669-d6ab6180-0d51-11eb-90ab-4fdf98926668.png)

**Comment by Tyriar** [comment]
I think the discoverability issue of this is mostly fixed with relaunch and the upcoming https://github.com/microsoft/vscode/issues/118066, users shouldn't see the warning icon anywhere near as often after these.
