### ISSUE TITLE
Notebook document changes aren't sync'd to all extension hosts

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#102767]
* enable web worker extension host via `"extensions.webWorker": true`
* in dev tools (!) set a breakpoint at `extHostNotebook$acceptModelChanged`
* open a notebook
* add or remove a cell
* 🐛 the breakpoint isn't hit, a notebook document is only sync'd with it the extension host it originated in, not others

**Comment by rzhao271** [comment]
@jrieken wondering if you can verify this issue?

**Comment by rzhao271** [comment]
I'm unable to verify the issue. For step 2, I set a breakpoint at `extHostNotebook$saveNotebook`, because `acceptModelChanged` isn't there anymore.

![Screencap showing failed verification](https://user-images.githubusercontent.com/7199958/127910118-565ecf6e-afa5-4f33-a400-5dd166c3e59e.gif)

**Comment by rebornix** [comment]
> I'm unable to verify the issue. For step 2, I set a breakpoint at extHostNotebook$saveNotebook, because acceptModelChanged isn't there anymore.



this is no longer handled by `acceptModelCHanged` as it's using the new serializer.
