### ISSUE TITLE
Auto update Extension when a new Patch is released

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#102709]
I want my users to have the extension up to date without requiring any manual step when I release a new Patch. I was thinking that maybe you can add an entry on the manifest for the developer to configure this behavior. Or make this behavior standard on vscode. The reason for that is that maybe we fixed a bug but the user did not see the new release. For Minors and Majors it is good to let the user to decide.

I released a couple of patches to my extension but it seems no one is using the most recent one. I know that because Im using vscode telemetry package to track the usage on azure.

**Comment by nrayburn-tech** [comment]
Extensions should automatically update now based on https://code.visualstudio.com/docs/editor/extension-gallery#_extension-autoupdate.  It also looks like this is the default.

Typically auto updates are configured by the end user and not the provider, so it would be unlikely that any extension could enable/disable auto updates.

**Comment by roblourens** [comment]
Extensions are auto updated, users can disable this

**Comment by AllanOricil** [comment]
I gathered some data to show to you that somehow most of the users are not updating to the latest patch. How can I notify them about it?

![image](https://user-images.githubusercontent.com/55927613/87803174-0d083c00-c84a-11ea-8b34-d07c5efe9916.png)
