### ISSUE TITLE
auto attach triggers on every terminal action and on fresh terminal session

### ISSUE THREAD

**Issue by salvationGit** [microsoft/vscode#102786]
![Screen Shot 2020-07-17 at 16 31 12](https://user-images.githubusercontent.com/10929625/87791544-1b0a8c80-c84b-11ea-8f63-f8d0f6c95185.png)
Issue Type: <b>Bug</b>

when auto attach(nodejs project) is enabled it triggers on every command on the terminal and when a fresh terminal session is opened. this will result multiple unwanted debug sessions to run.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
lit-html|bie|1.11.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
vscode-eslint|dba|2.1.6
githistory|don|0.6.6
python-extension-pack|don|1.6.0
xml|Dot|2.5.0
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.1.3
path-autocomplete|ion|1.14.0
graphql-for-vscode|kum|1.15.3
MagicPython|mag|1.1.0
vscode-docker|ms-|1.3.1
python|ms-|2020.6.91350
vsliveshare|ms-|1.0.2427
material-icon-theme|PKi|4.2.0
open-in-browser|tec|2.0.0
python|tht|0.2.3
vscodeintellicode|Vis|1.2.9
gitblame|wad|4.1.0
jinja|who|0.0.8
markdown-all-in-one|yzh|3.1.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Please update to VS Code 1.47.2 where this is fixed!

/duplicate
