### ISSUE TITLE
Markdown projects causing unresponsiveness when closing/saving

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#102733]
Version: 1.48.0-insider (system setup)
Commit: 5e5fa3edde19d38ac512d65ccefe2a12ecab025a
Date: 2020-07-16T13:12:57.510Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041

## Desc

So i've noticed lately that when closing a project which has markdown files in it, nothing happens.. Then after a few seconds VSCode closes (its like something is blocking VSCode from closing).
Then i noticed it does the same when i switch project (ctrl + r), nothing happens, then after a few seconds it switches. 
The delay can be long, and I'm not sure this always happened, it feels like something is wrong. 
Sometimes the whole editor completely locks up for a couple of seconds.

After some investigation it seems to only happen with projects that have markdown files in them, i opened dev tools and tried to find what happens when i click "Reload with extensions disabled", here is an image:
![image](https://user-images.githubusercontent.com/936006/87730427-ab02f480-c7bf-11ea-990a-57feae663834.png)
profile for the above:
[Profile-20200716T235450-1.zip](https://github.com/microsoft/vscode/files/4934769/Profile-20200716T235450-1.zip)

The issue seems to be in the `saveState` operation, which for some reason isn't a problem on other projects.

I can also reproduce the issue by unfocusing from VSCode for a few seconds then clicking into a markdown file (it locks up)
[unfocus-focus.zip](https://github.com/microsoft/vscode/files/4934839/unfocus-focus.zip)

Steps to Reproduce:

1. Using Insiders (1.48.0) open a folder of Markdown files (extensions disabled)
2. Switch to another project or try to close

Does this issue occur when all extensions are disabled?: Yes

Maybe @mjbvz might know something?

**Comment by jasonwilliams** [comment]
Every time i click out then click back in VSCode locks up for a few seconds, ive managed to capture it here:
![image](https://user-images.githubusercontent.com/936006/87731711-08e50b80-c7c3-11ea-82a7-41d34c9aa19e.png)

[focus-lock.zip](https://github.com/microsoft/vscode/files/4934860/focus-lock.zip)

**Comment by mjbvz** [comment]
Thanks for the investigation!

I can't repo this but there was an issue a few days back that could cause the markdown preview to get into a bad state (each preview would end up storing a gigantic string of text as its state). I've pushed a potential fix for this but if you have any old markdown preview tabs still open, they could still trigger this. Please make sure you close all open markdown previews (even if they are not visible). You may also need to run the `Editor: clear editor history` command

Let me know if that fixes the issue for you

**Comment by jasonwilliams** [comment]
@mjbvz my insiders doesn't have any updates, its still on:
Version: 1.48.0-insider (system setup)
Commit: 5e5fa3edde19d38ac512d65ccefe2a12ecab025a
Date: 2020-07-16T13:12:57.510Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041

Do i need to wait for your fix to come through?

**Comment by jasonwilliams** [comment]
@mjbvz it updated today to:
Version: 1.48.0-insider (system setup)
Commit: ff6b1c5984a4c2116a06318f07e871a4169fdb1b
Date: 2020-07-17T13:18:36.126Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041

It looks better, initially i thought the problem was still there but then i ran `File: clear recently opened` and it's very responsive now. So as far as i can tell it's fixed.

**Comment by mjbvz** [comment]
Ok, glad to hear that command fixed things. The bug was causing certain entries in the history to become very, very large, which in turn would slow down shutdown. Manually cleaning the editor history deletes the problematic entries

Please let me know if you hit this again

**Comment by isidorn** [comment]
Adding verified based on user's comment.
