### ISSUE TITLE
Reagrding the freezing of the screen

### ISSUE THREAD

**Issue by vejjutejdeep** [microsoft/vscode#102745]
Issue Type: <b>Bug</b>

My screen freezes after 5 minutes  start the VScode

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
code-metry|cod|0.0.2415
prettier-vscode|esb|5.1.3
code-runner|for|0.11.0
getter-setter-generator|Gab|1.4.0
python|ms-|2020.7.94776
team|ms-|1.161.0
java|red|0.64.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-checkstyle|she|1.3.3
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.22.0

</details>

**Comment by rebornix** [comment]
Can you follow our wiki to provide more details to help troubleshoot https://github.com/microsoft/vscode/wiki/Performance-Issues ?>
