### ISSUE TITLE
Webview -> Ctrl + c stopped to work on Text Area on Webview

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#102736]
- VSCode Version: 1.47.2 (17299e413d)
- OS Version: Windows 10

Steps to Reproduce:
1. Install sfdx cli (Salesforce CLI)
2. Create a Dev Account on Salesforce to get a DevHub (https://developer.salesforce.com/signup)
3. Authenticate the Dev Hub using `sfdx force:auth:web:login -a NAME`
4. Set the Dev Hub as your defaultdevusername using `sfdx force:config:set defaultusername=NAME -g`
5. Now Install the Salesforce SOQL Editor extension
6. Create an sfdx project using the commnad `sfdx force:project:create -n PROJECT_NAME`
7. Open this project with VS Code.
8. Wait a few seconds until the extension is Activated. It activates onCommand or when it Identifies the file called `sfdx-project.json`
9. Open the extension with the command `SFDX: SOQL Editor`
10. Write anything on the Text Area, then try to copy and paste it.
11. Verify that the text was not copied.

<b>Obs:</b> When the app is running outside of VSCode, copying the text with Ctrl+c works.

**Comment by gjsjohnmurray** [comment]
Did this work before you updated to 1.47.2?

**Comment by AllanOricil** [comment]
> Did this work before you updated to 1.47.2?

Yes. Before updating it was the Ctrl+V that was bugged. It was duplicating stuff. Now the Ctrl+c stopped haha.

**Comment by Huachao** [comment]
@mjbvz Is this issue related with the fix #101958

**Comment by bcanzanella** [comment]
the CodeStream extension is also affected by this. It worked with 1.47.1, but not in 1.47.2. For us, it doesn't seem limited to textareas within the the webview, attempting to copy any text inside the webview fails.

**Comment by matiasg77** [comment]
I got the same problem
vscode version: 1.47.2

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by AllanOricil** [comment]
I confirm that my issue was fixed. I copied and pasted the text inside the Webview with no problem

![image](https://user-images.githubusercontent.com/55927613/88239088-c35c8e80-cc59-11ea-9b58-450951af74ae.png)

**Comment by lee-baker** [comment]
I have just installed the insiders build and when using the insiders instance of VSCode I am no longer experiencing this issue.

I am currently seeing this issue with 1.47.2 using the RestClient extension. 
I am unable to copy small chunks of data from the response body which is shown using a WebView.
The extension has an option to show the response in an untitled document, and when I enable this the copying works again.

**Comment by mjbvz** [comment]
@AllanOricil  Did you test on insiders? Which operating system?

**Comment by AllanOricil** [comment]
@mjbvz I confirm the issue is fixed in the Insiders version. I was able to copy something from the text area and then paste it.

**Comment by mjbvz** [comment]
Closing as this is fixed in 1.48 then. Should be out in early august
