### ISSUE TITLE
Can't show the subproject log in git repository when click the 'Git: view history' in Git source control menu

### ISSUE THREAD

**Issue by backoon** [microsoft/vscode#102711]
Issue Type: <b>Bug</b>

1. clone the github repository has multi subprojects.

2. click 'source coltrol' button on VSCODE

3. click 'Git View History(git log)' button on one of the subprojects.

4. It will show the right git log after you seleted some project. 

5. Now, click again 'Git View History(git log)' button on other subproject.

6. It only shows the 'MASTER PROJECT LOG' not a 'SELECTED SUB PROJECT LOG'
(It happened after recently update VSCODE.- and changed some button position)

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.1000.4
vscode-eslint|dba|2.1.8
githistory|don|0.6.7
xml|Dot|2.5.0
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.1.3
vscode-lombok|Gab|1.0.1
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
vscode-language-pack-ko|MS-|1.47.3
python|ms-|2020.6.91350
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-react-native|msj|0.16.1
gradle-language|nac|0.2.3
vetur|oct|0.24.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.19.0
vscode-manifest-yaml|Piv|1.19.0
vscode-spring-boot|Piv|1.19.0
java|red|0.64.1
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-spring-initializr|vsc|0.4.8
vscode-icons|vsc|10.2.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by joaomoreno** [comment]
`Git View History(git log)` is not a command part of VS Code, it must come from an extension, very likely the `githistory` extension you have installed.
