### ISSUE TITLE
Syntax highlight engine is broken after 1.4.0

### ISSUE THREAD

**Issue by hackwaly** [Microsoft/vscode#10274]
Evidence here: https://github.com/hackwaly/vscode-ocaml/issues/42

**Comment by tuktun** [comment]
Same for me for JS syntax highlight:
http://imgur.com/a/HP1wB

**Comment by aeschli** [comment]
@tuktun Please file a separate issue, syntax highlighting issues mostly depend on the grammar which is different for every language. Please always add a the example code as text.

**Comment by aeschli** [comment]
@hackwaly I commented in hackwaly/vscode-ocaml#42, the bug is with the OCaml grammar.
