### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by rlarbals822V2** [microsoft/vscode#102782]
Issue Type: <b>Bug</b>

Hello,
Since the last version (June 2020) when I try to launch a node (discord bot) application I have a error:

"C:\Program Files\nodejs\node.exe" "c:\Hex Support\app.js"
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'c:/Users/MathysCollège/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1278:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

I try to upload a last version (June 2019) I'hyaven't got this problem but when  I start visual studio code the update is automatic.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.90GB (7.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.14
code-runner|for|0.11.0
discord-vscode|icr|4.0.0
discord-js-tools|jas|0.0.3
chat|kar|0.35.0
discord|Kua|0.0.6
vsliveshare|ms-|1.0.2427
vsliveshare-audio|ms-|0.1.85
material-icon-theme|PKi|4.2.0
vscode-css-peek|pra|3.0.2
phpdoc-comment-vscode-plugin|rex|1.3.0
LiveServer|rit|5.6.1

</details>

**Comment by connor4312** [comment]
Thanks for the issue -- you appear to be hitting https://github.com/microsoft/vscode-js-debug/issues/563#issuecomment-659592018. See instructions there for a workaround.

/duplicate
