### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by E-N-G-XOR** [microsoft/vscode#102710]
Issue Type: <b>Bug</b>

I passed my login details, to the git and I am able to push to the repo the first time, but after a few mins, when I commit a new change.... VSCode will not accept my user and password, and I can't push changes.... I have to use a terminal.... Can we add a cred cache for this so it stores my login info for gitlab?

Extension version: 0.18.0
VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:30:34.302Z)
OS version: Linux x64 5.4.0-40-generic snap

**Comment by roblourens** [comment]
> VSCode will not accept my user and password

Can you explain more about exactly what happens?

**Comment by E-N-G-XOR** [comment]
HI, Rob,

So I am using VsCode to update git repos. I installed the "git pull
requests and issues", v0.18.0..... I am running VsCode 1.47.1 on Ubuntu
focal.

So, I am updating files, and the first time VsCode prompted me for a
username and password, which I entered and all is well.... 5 mins down the
road, It is prompting me just for a password. (My issue is my user name
differs for each gitlab server I am on at the time) Just entering in a
password isn't enough.....

Which is sort of a pain now to use.....

I did a presentation on gitops, and in the 30 mins session, I was asked to
enter my username and password every 5 mins.... (THe fact that it was
asking for a username and password each time was nice, but a real pain to
use during the presentation.... I finally dropped VsCode and used a plain
terminal window to push updates.....

Surely, a caching function should be available to store the creds for the
servers I connect to so I don't have to continually enter a password....

maybe...?

Ta,

Lane

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the username/password prompt UI? Thanks.

**Comment by E-N-G-XOR** [comment]
Hi, Joao,

Attached are the prompts I get, but in VsCode, there isn't much to look
at.....

Ta,

**Comment by joaomoreno** [comment]
Can you please login to Github and attach the screenshots in the browser? E-mail attachments don't work.

**Comment by E-N-G-XOR** [comment]
HI Joao,

Totally missed that one! Here are the images...

x-special/nautilus-clipboard
copy
file:///home/lane/Documents/login_pass_prompt.jpg
file:///home/lane/Documents/login_prompt.jpg

**Comment by joaomoreno** [comment]
Got it. You should probably setup a git credential manager: https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage
