### ISSUE TITLE
Copy does not work on preview tab

### ISSUE THREAD

**Issue by remonbonbon** [microsoft/vscode#102743]
- VSCode Version: 1.47.2
- OS Version: Windows_NT x64 10.0.14393

Steps to Reproduce:

1. Open a markdown file and move cursor to any line
2. Open the markdown preview
3. Copy some text from the preview
4. Editor lines are copied instead of the preview

Does this issue occur when all extensions are disabled?: Yes

**Comment by Shankhesh-16** [comment]
while pasting the copied text is pasted 2 times.

**Comment by rwilliaise** [comment]
I cannot reproduce this bug with the steps you provided. I am on VSCode 1.47.2 and macOS Mojave 10.14.6.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
