### ISSUE TITLE
C++ comment tokenization

### ISSUE THREAD

**Issue by Rb37** [microsoft/vscode#102787]
- VSCode Version:
Version: 1.47.2 (user setup)
- OS Version:
OS: Windows_NT x64 6.1.7601

Inside multiline comment the sequence capital letter and colon are not highlighter as comment.
Only if there are additional star after multiline comment

Steps to Reproduce:
1.Type this code

```
/*
A:
*/

/**
A:
*/

/***
A:
*/
```

![c++ comment tokenization 3](https://user-images.githubusercontent.com/16442928/87791330-bf400380-c84a-11ea-9b63-a59dc371ac73.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Moved to the repository where we get our C++ grammar from.
