### ISSUE TITLE
esc. touch when Panel is focused closes the panel

### ISSUE THREAD

**Issue by kud** [microsoft/vscode#102708]
When my mouse or my keyboard are focused on the panel, pressing esc closes the panel.

**Comment by roblourens** [comment]
Do you have a keybinding set up to do this? Or, an extension that adds this keybinding? You can check the keyboard shortcuts or try disabling all extensions by launching with `--disable-extensions`

**Comment by kud** [comment]
Hello @roblourens , hope you're well. 😊

It's in fact a feature request, it's not at the moment the case.

I clicked on "feature request" but it seems that the issue template doesn't add any information (like tag) about this. 😬

**Comment by roblourens** [comment]
Oh ok, it's possible to set up a keybinding for this yourself

**Comment by kud** [comment]
Okay! Thank you! I'll have a try so. :)

**Comment by kud** [comment]
For those interested:

```
  {
    "key": "escape",
    "command": "workbench.action.closePanel",
    "when": "panelFocus"
  }
```
