### ISSUE TITLE
GitHub two-factor authentication not supported.

### ISSUE THREAD

**Issue by EzraLopez** [Microsoft/vscode#10278]
- VSCode Version: 1.4.0
- OS Version: macOS 10.12 Beta

Steps to Reproduce:

1. Have a GitHub account with 2FA enabled
2. Try to set it up with VSCode
3. Enter GitHub credentials 
4. Authentication will fail - it should ask you for a verification code

**Comment by joaomoreno** [comment]
#490 is also about 2FA.
