### ISSUE TITLE
Allow custom names for Virtual Documents

### ISSUE THREAD

**Issue by bryceitoc9** [microsoft/vscode#102739]
I would like extensions to have the ability to programmatically alter the tab name for Virtual Documents, similar to how you would add a name to a webview tab. The reasons are twofold:

1. The only way to pull information from a Virtual Document is through the URI. This means that if you need to send multiple pieces of data to the TextDocumentContentProvider, it all has to be serialized into the URI, which can make the display name unwieldy.
2. URIs containing slashes have all text pre-final slash removed, as the tab interprets it as a file path. In my particular use-case (rendering online log streams), the slashes provide important context into what log stream is being viewed; removing this makes it more difficult to know what resource you're looking at as a user.

**Comment by jrieken** [comment]
The name of a virtual document is defined by its URI and cannot change that. However, to transport "invisible" information you use the query or fragment part of a uri. You can also use the `resourceLabelFormatters` contribution to decide what part of a URI is rendered in what way

**Comment by bryceitoc9** [comment]
I'm having some troubles with the `resourceLabelFormatter`. The strings I want to display can have both `/` and `\` characters in them. With the following rule:
```
            {
                "scheme": "SCHEME",
                "formatting": {
                    "label": "${path}",
                    "separator": ...
                }
            }
```

and the following URIs:
```
const uri1 = vscode.Uri.parse('SCHEME:/something/name')
const uri2 = vscode.Uri.parse('SCHEME:\\somethingelse\\name')
```

I get the following results given different separators:
| separator | `"/"` | `"\\"` | `""` | (no separator field) |
|---|---|---|---|---|
| uri1 (tab name) | `name`  | `name` | `somethingname` | `undefinedsomethingundefinedname` |
| uri1 (URI from hovering over tab) | `/something/name`  | `\something\name` | `somethingname` | `undefinedsomethingundefinedname` |
| uri2 (tab name) | `\somethingelse\name` | `name` | `name` | `name` |
| uri2 (URI from hovering over tab) | `\somethingelse\name` | `\somethingelse\name` | `\somethingelse\name` | `\somethingelse\name` |

Is there a way to force the tabs to show the full, unadulterated path in the tab name? In case it matters, these tests are on Windows (I don't know what this would look like on MacOS or Linux but I can check if necessary).
