### ISSUE TITLE
Status bar item for debugging current launch configuration is confusing to users

### ISSUE THREAD

**Issue by kschaab** [microsoft/vscode#102715]
Issue Type: <b>Bug</b>

The status bar item for launching current launch configuration is confusing to users.  They click on this thinking that it will start the launch configuration in run mode vs. debug mode.  The prefix "debug" doesn't seem to be enough and there seems to be no way to switch to run without debugging.  Considering extending the other work the Code team is doing here to fix this ambiguous situation such as changing the icon to the bug.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:01:54.115Z)
OS version: Darwin x64 19.5.0

**Comment by isidorn** [comment]
Thanks for the feedback. We might change this in the future as you suggest by using a different icon.
Assigning to August to look into it then.

**Comment by isidorn** [comment]
Actually decided to make this change this milestone. I think it makes perfect sense

![Screenshot 2020-08-03 at 15 41 45](https://user-images.githubusercontent.com/1926584/89189126-d8adb300-d59f-11ea-8987-83531f038fea.png)
