### ISSUE TITLE
Debugger still photobombing any node command from the integrated terminal

### ISSUE THREAD

**Issue by trumbitta** [microsoft/vscode#102730]
A known problem, supposedly solved by update 1.47.2, but nothing changed for me.

I have the relevant settings set to off or disable.

**Comment by trumbitta** [comment]
Update: after switching from `off` to `disable` and reloading the window once again, it started working.

I dare to say the feature still needs work.

**Comment by connor4312** [comment]
Indeed, that's why we disabled it in https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467 🙂 

However to clear out variables from existing workspaces you may need to toggle through the "disabled" state.

/duplicate
