### ISSUE TITLE
VS Code Terminal Autocompletion does not working with python interactive shell

### ISSUE THREAD

**Issue by maamiradina** [microsoft/vscode#102749]
I am using VS code in windows 7, and using two internal terminals one is Basic CMD and other is python interactive shell. but Auto completion in both terminal not working. also it do not giving suggestions what am I writing like in workspace with file, which gives suggestion when I am typing a code.
so what is the problem ad what will be the possible solution for that?
Because I am new to programming I want to learn Python. 
So please guide for auto completion of terminal, because I am watching tutorials in which he presses only TAB for automatic insertion, and when I press TAB in terminal, curser goes about 6 spaces like in word and other text editors.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
