### ISSUE TITLE
vs code not working

### ISSUE THREAD

**Issue by Anjaliee** [microsoft/vscode#102766]
app is blank when opened after installation 
![a](https://user-images.githubusercontent.com/67465363/87776189-01fedd00-c845-11ea-8b2e-7be2baf0bee5.JPG)

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart
