### ISSUE TITLE
increase font size for debug window

### ISSUE THREAD

**Issue by richcmwang** [microsoft/vscode#102778]
Font for debug/outline/explore is too small for high-resolution monitor and cannot be adjusted.  It would be very helpful if users can increase the size.

**Comment by gjsjohnmurray** [comment]
How about the `View: Zoom In` command? And if this makes your editor font too big, offset it by using `Editor Font Zoom Out` as well.

**Comment by ArturoDent** [comment]
"Font for debug/outline/explore"  i would say this is a duplicate of https://github.com/microsoft/vscode/issues/519

**Comment by isidorn** [comment]
Please use the following setting 	"debug.console.fontSize": 12,

As for the other views this is a duplicate of #519
