### ISSUE TITLE
Tweet feedback?

### ISSUE THREAD

**Issue by brennanMKE** [microsoft/vscode#102732]
Issue Type: <b>Bug</b>

I will never submit feedback via tweet. I am not even logged into Twitter on my work computer. That is a very bad idea, especially with the major security compromise this week.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:43:02.577Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 9, 7|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
proto3-nav|bri|0.2.2
vscode-markdownlint|Dav|0.36.1
java-decompiler|dgi|0.0.2
githistory|don|0.6.7
prettier-vscode|esb|5.1.3
json2ts|Gre|0.0.6
java-properties|ith|0.0.2
protobuf|kan|1.1.6
typescript-code-navigator|kdc|1.2.4
ts-extension-pack|loi|0.2.0
vscode-brazil|mar|0.31.200728
python|ms-|2020.6.91350
cpptools|ms-|0.29.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
vscode-protolint|ple|0.3.0
tsimporter|pmn|2.0.1
java-ide-pack|pve|1.2.1
typescript-hero|rbb|3.0.0
java|red|0.64.1
vscode-yaml|red|0.9.1
rust|rus|0.7.8
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.22.0
vscode-icons|vsc|10.2.0
gitblame|wad|4.1.0
vscode-java-saber|You|0.1.1
vscode-proto3|zxh|0.4.2

</details>

**Comment by mjbvz** [comment]
Right click in the status bar to disable this:

<img width="385" alt="Screen Shot 2020-07-16 at 4 25 12 PM" src="https://user-images.githubusercontent.com/12821956/87732113-ed591100-c780-11ea-8162-74c80062070a.png">
