### ISSUE TITLE
Virtual Documents do not immediately trigger vscode.workspace.onDidCloseTextDocument on close.

### ISSUE THREAD

**Issue by bryceitoc9** [microsoft/vscode#102737]
Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

Given code similar to the following:
```typescript
    vscode.ExtensionContext.subscriptions.push(
        vscode.workspace.registerTextDocumentContentProvider(
            SCHEME,
            new xDocumentProvider(registry)
        )
    )

    vscode.ExtensionContext.subscriptions.push(
        vscode.workspace.onDidCloseTextDocument(doc => {
            getLogger().debug(`${doc.uri} isClosed: ${doc.isClosed}`)
        })
    )

async function foo () {
    ... // ...generate a URI with scheme === SCHEME
    const doc = await vscode.workspace.openTextDocument(uri)
    vscode.languages.setTextDocumentLanguage(doc, 'log')
    await vscode.window.showTextDocument(doc, { preview: false })
}
```

...the `onDidCloseTextDocument` function is called immediately following the `showTextDocument` line and reports `doc.isClosed` as `false`, likely due to the language change. Closing the text document will eventually fire the `onDidCloseTextDocument` event with `doc.isClosed` as `true` after a few minutes (empirically ~3-5 min). `xDocumentProvider` does include a `public get onDidChange()`, which returns an event.

Questions:
1. Is this delayed behavior expected?
2. Could this fire off a different event on language change? It's a bit jarring that the language change represents a closed document even though the document hasn't been opened by the time the language change takes place.

Does this issue occur when all extensions are disabled?: No, this is an issue with the extension API.

**Comment by jrieken** [comment]
Yes - that the defined behaviour. [Changing the language](https://github.com/microsoft/vscode/blob/88612895970f219120b6e6ac42bdf022c68d403c/src/vs/vscode.d.ts#L9920-L9922) of a document will trigger a close and open event. 

>  though the document hasn't been opened by the time the language change takes place

Sure it has. The line above opens it, the line below shows it in an editor. Those are two different things and open document, close document means an editor has been from its source into memory (open) or has been dettached from its source (close)

**Comment by bryceitoc9** [comment]
Is it expected for there to be a ~5 min delay between closing the editor tab and firing the onDidCloseTextDocument event? Non-virtual documents appear to emit this immediately, even after shifting the language.

**Comment by jrieken** [comment]
Yes - that expected. All documents that explicitly requested by extension are disposed after a while

**Comment by bryceitoc9** [comment]
Is there anything I can use to expedite the disposal? As it stands, I'm using this to run some cleanup on the doc...this interval works OK for my current use-case but I can see many reasons to want a snappier response time.

**Comment by jrieken** [comment]
No, extensions cannot dispose text models.
