### ISSUE TITLE
Implement scroll bounce effect

### ISSUE THREAD

**Issue by albanv** [microsoft/vscode#102712]
Hi,
First, I've actively searched for this feature, but I was unable to find an existing setting/extension/issue/PR (using elastic / bounce scroll as keywords). I apologize in advance if I missed it.
I would like to have an option to activate a bounce effect on scroll when reaching the top/bottom of a scrollview.
IMO it feels very natural when using a trackpad or a touchscreen and it would improve the coherence with (at least) macOS.

**Comment by roblourens** [comment]
I guess this would essentially be a ListView feature request @joaomoreno? I'm not sure whether this would be in scope, it could give a more native feel though. Do you know if it's ever been discussed?

**Comment by joaomoreno** [comment]
Not ListView, but scrollable: @alexdima 

I would definitely mark this as out of scope, though.
