### ISSUE TITLE
Command variable substitution hangs tasks.json

### ISSUE THREAD

**Issue by brianignacio5** [microsoft/vscode#102769]
Issue Type: <b>Bug</b>

Specify a task in tasks.json (also happens in launch.json) that uses ${command: command_id } in args or options env (places I've tried).

As an extension developer, I've made some predefined tasks.json that uses an extension command (specified by command_id) in those tasks with variable substitution. This doesn't seem to work anymore after 1.47 config and workspaceFolder variables seems to work.

Steps to reproduce:

1. Make a task in tasks.json that uses ${command: command_id } of some extension. 
2. Try to execute this task with F1 -> Run task
3. Nothing happens. No Error and no output log.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 5|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|-psn_0_528513|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dash|dee|2.4.0
prettier-vscode|esb|5.1.3
vscode-drawio|hed|0.7.2
vscode-docker|ms-|1.3.1
vscode-language-pack-es|MS-|1.47.3
python|ms-|2020.7.94776
cpptools|ms-|0.29.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.24.0
fix-json|oli|0.1.2
tslint-vue|pro|1.5.6

</details>

**Comment by alexr00** [comment]
I can't repro this issue. Does it still occur if you disable all extensions? It is possible that an extension is getting stuck during activation and is causing this (in which case you can file an issue with that extension).

My task:
```json
    {
      "label": "My Task",
      "type": "shell",
      "command": "echo",
      "args": [
        "${command:extension.helloWorld}"
      ],
      "problemMatcher": []
    }
```

My command:
```typescript
const disposable = vscode.commands.registerCommand('extension.helloWorld', async () => {
		return 'My command output';
	});
```

**Comment by brianignacio5** [comment]
@alexr00 found the root of the problem and is related to the extension. Sorry for the troubles and thank you.
