### ISSUE TITLE
[themes] autoDetectColorScheme not working on Linux

### ISSUE THREAD

**Issue by mcnesium** [microsoft/vscode#102795]
When switching dark/light color themes in the OS, the opposite theme is being set in vscode. It even mixes it up right at the start. Watch the screencast:

![vscode](https://user-images.githubusercontent.com/476060/87803492-d4b92b80-c852-11ea-8345-77c69910f500.gif)

- VSCode Version: 1.47.1 (VSCodium)
- OS Version: Manjaro Linux 20.0.3

Steps to Reproduce:

1. Set prefered dark and light color themes in `settings.json`, e.g.:

    "workbench.colorTheme": "Atom One Light",
    "workbench.preferredDarkColorTheme": "Atom One Dark",
    "workbench.preferredLightColorTheme": "Atom One Light",
    "window.autoDetectColorScheme": true

2. switch to the other theme in OS

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
Do you get the same result if you launch without `--disable-extensions` flag?

**Comment by NotWearingPants** [comment]
This actually makes sense if your default theme is configured to be a dark theme.
What needs to happen is for vscode to check whether the configured theme aligns with the OS setting or not,
and then swap themes to keep the equality or inequality consistent.

i.e. if the OS is configured to light mode and a dark theme is active in vscode,
and then you switch the OS to dark mode, vscode should switch to a light theme.

**Comment by aeschli** [comment]
We rely on Electron/Chrome to notify the OS color scheme change with a media query event

That wasn't supported on Linux, and I also don't see it working on Ubuntu 20.04
![color-scheme-switching](https://user-images.githubusercontent.com/6461412/91891160-d0c15b80-ec90-11ea-8e23-c6fe8783577a.gif)

Can you open the dev tools and set a breakpoint at 'handlePreferredSchemeUpdated' in vs/workbench/services/themes/browser/workbenchThemeService:
https://github.com/microsoft/vscode/blob/df30a1ff768c7c45b1876b6ccc8b8ba0ba708cd5/src/vs/workbench/services/themes/browser/workbenchThemeService.ts#L332

**Comment by mcnesium** [comment]
Okay I didn't realize that. Looks like Chromium does not follow the color scheme at all. Firefox on the left, Chromium on the right:

![chromium](https://user-images.githubusercontent.com/476060/91970230-a1096680-ed17-11ea-9a15-9e387a3d044b.gif)

**Comment by aeschli** [comment]
Instead of using the media event, I'll switch to use the new electron API. I'll give this a try in September

**Comment by aeschli** [comment]
We still don't get an an event from Electron

**Comment by AndreasBackx** [comment]
> We still don't get an an event from Electron

@aeschli should we perhaps create an issue on the Electron issue tracker for this? I couldn't find an existing issue.

**Comment by aeschli** [comment]
The Electron issue is https://github.com/electron/electron/issues/25925.

**Comment by SpineEyE** [comment]
Seeing that this was fixed for electron 13 and the vscode main branch uses electron 13, will this work in the next vscode version?

**Comment by kushraj** [comment]
waiting for an update on this one

**Comment by aeschli** [comment]
I just tested that automatic theme switching based on the OS scheme works in VS Code 1.59 on Ubuntu 21.04.

- set `"window.autoDetectColorScheme": true`
- switching the OS themes with change the VS Code theme according to `workbench.preferredDarkColorTheme` and `workbench.preferredLightColorTheme`
