### ISSUE TITLE
No debug adapter can not send 'terminate'

### ISSUE THREAD

**Issue by devfcr** [microsoft/vscode#102701]
- VSCode Version: 1.47.1
- OS Version: macOS 10.15.6 (19G73)

Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-13T22:43:02.577Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Run Angular Project in debug mode
2. Stop Debugger

Does this issue occur when all extensions are disabled?: Yes

The problem may be related to the problem described at https://github.com/microsoft/vscode-js-debug/issues/570. This problem also occurred to me, but could be avoided by extending the timeout to 20s. Nevertheless the chrome starts very slowly during a debug session. If you try to end the debug session, the error message 'No debug adapter, can not send 'terminate'' appears.

**Comment by connor4312** [comment]
Thanks for the issue -- this is both an issue on VS Code (https://github.com/microsoft/vscode/issues/102037) and the debugger.

**Comment by amalic** [comment]
Having the same problem following this instructions:
https://code.visualstudio.com/docs/nodejs/angular-tutorial

Breakpoints turn from red to empty and tooltip says "Unbound breakpoint"

**Comment by connor4312** [comment]
@amalic that is a different issue, please create a bug here and include the trace log (instructions in the issue template): https://github.com/microsoft/vscode-js-debug/issues/new/choose
