### ISSUE TITLE
Command execution when launching runconfig.

### ISSUE THREAD

**Issue by niosega** [microsoft/vscode#102765]
- VSCode Version: 1.46.1
- OS Version: Xubuntu 18.04, kernel 5.3.0

Steps to Reproduce:

1. Launch a run config for the first time.
2. Type something on the newly created terminal.
3. Relaunch the same run config.

Details:
If you type something inside the terminal created by the launch of a runconfig, the text you type is prepended to the command that launch the next debuuger run. See the following gif for explanation.

![issuevscode](https://user-images.githubusercontent.com/6972578/87775585-a3c30180-c826-11ea-8d30-7e16d5c9f7bd.gif)

Does this issue occur when all extensions are disabled?: No, because it needs a debugger (no matter the debugger).

**Comment by weinand** [comment]
the described behavior is correct.
