### ISSUE TITLE
Let the user specify word separators for all input fields, not just for the editor

### ISSUE THREAD

**Issue by dmstern** [microsoft/vscode#102755]
When modifying the setting `editor.wordSeparators`, this applies only to the editor.
But when I want to rename a symbol, the cursor does not stop at the word separators, obviously because we are not in the editor. The same applies to the quick input message, e.g. when navigating through git branch names.

Could we have a more general setting which also applies to more input fields, like the rename input and the quick input or the scm commit box?

**Comment by roblourens** [comment]
This would be nice but is basically equivalent to promoting all text inputs to full browsers with custom text editor functionality. That just isn't practical for us to do, creating text editors is too expensive, so we have to fall back on native browser functionality here, sorry.

**Comment by dmstern** [comment]
Okay. Nevertheless, thanks for your answer.
