### ISSUE TITLE
Markdown preview takes several seconds to render

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#102734]
- VSCode Version: 1.48.0
- OS Version: Windows 10

Steps to Reproduce:

1. In the vscode-docs repo, open the latest release notes Markdown v1_47.md in the editor.
2. Open Markdown preview

It can take several seconds for the preview to render. It is also slow before you can start scrolling.

If you try to switch back to a regular editor that also is quite slow.

**Comment by mjbvz** [comment]
Potential related to #102733

**Comment by gregvanl** [comment]
The first Insiders release where this occurs is cb31fc6ce2b4da3520392b622aa3ebc5b313533b.
I don't see this behavior on build a7285b471ccb39fb281f096f9c707fbfcd11f9bf

**Comment by mjbvz** [comment]
Should be fixed in the latest insiders by ec8606cb49ec839ccdf90c278f44c5bfa3567063

**Comment by gregvanl** [comment]
Yep, much snappier.
