### ISSUE TITLE
June update breaks debugging my NodeJs Express API project

### ISSUE THREAD

**Issue by ppopadiyn-iv** [microsoft/vscode#102785]
- VSCode Version: 1.47.2
- OS Version: Windows 10, OS build: 19041.388

Steps to Reproduce:

1. Update VS Code to latest version
2.

Does this issue occur when all extensions are disabled?: Yes

This morning, I updated my VS Code to the latest version 1.47.2. This immediately break my NodeJs Express API project in debug mode. HTTP request from a ReactJS (and Postman) project are pending forever. Debugger never hit server side controllers or whatever. Sockets from server to client stopped working.

Issue resolved after downgrading version to 1.46.1.

**Comment by connor4312** [comment]
Please collect a trace log using these instructions:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

/needsMoreInfo

**Comment by ppopadiyn-iv** [comment]
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode/files/4945883/vscode-debugadapter-1.json.gz)
Here is the trace log file.

**Comment by connor4312** [comment]
Thanks for the issue. I'm not seeing anything suspicious in those log files -- are you able to create a small sample reproduction case?

**Comment by ppopadiyn-iv** [comment]
Unfortunately, it will be difficult to reproduce in a standalone sample, as the current solution is quite complex. And problem can be anywhere.
For now, using v1.46.1 works for me. So I guess we might close it.
