### ISSUE TITLE
Terminal stuck and Python extension not working

### ISSUE THREAD

**Issue by QihangYao** [microsoft/vscode#102703]
Issue Type: <b>Bug</b>

I am using a ubuntu 18.04 on WSL1, and use remote WSL extension to edit and run Python files on it. I opened a Python file and an IPython in the terminal and write and test codes. Some time after (very short), I found the autoformatter was not working and when I try to access the IPython that I opened, it stucked. This happens for several times, and I changed from ubuntu 20.04 to ubuntu 18.04 trying to fix it. But I guess it's actually a problem with VSCode now.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1801)|
|Memory (System)|7.82GB (1.36GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-markdownlint|Dav|0.36.1
gitlens|eam|10.2.2
python|ms-|2020.6.91350

</details>

**Comment by roblourens** [comment]
> and when I try to access the IPython that I opened, it stucked

Can you explain more about what happens here? The formatter issue is probably an issue with the Python extension, I need to understand more.

**Comment by QihangYao** [comment]
Hi @roblourens! I am sorry but I can't trace this to any specific operation. Just sometime after my normal workflow (edit .py files, save, auto-formatting, test something in IPython), I will suddenly find the auto-formatting is no longer working (I always use Shift+Alt+F to call them. Are there any similar shortcuts that stuck everything?), and the IPython stuck. 

A detail I can add is that when I press the Python extension in the status bar, there will be a hint in the status bar saying "Activating Python Extension...", but it does nothing. I just closed the VSCode and reopen it and everything went back to normal. I think the Python Extension must have stopped working, but I don't know what can be the cause.

And I can also tell you a test that now I replicate my entire Python environment in a ubuntu 20.04 machine and used Remote SSH extension (So I am still using the same VScode on the local machine) to edit the same codes on that machine. And everything is working fine. The following are the details of that machine.

Remote | SSH: BLACKLOTUS
-- | --
OS | Linux x64 5.4.0-37-generic
CPUs | Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz (4 x 976)
Memory (System) | 7.65GB (0.26GB free)
VM | 0%

Hope these details can help you to locate the problem.

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
