### ISSUE TITLE
Pasting Multiple Lines on 2 multi-cursors doesn't work as expected.

### ISSUE THREAD

**Issue by MLavrentyev** [microsoft/vscode#102720]
- VSCode Version: May 2020 (1.46.1)
- OS Version: Windows 10

Steps to Reproduce:

1. Copy two lines (using <kbd>Ctrl</kbd>+<kbd>C</kbd>. For example copy the lines
```
line 1
line 2
```
2. Multi-select in two different places (using <kbd>Ctrl</kbd>+click). 
3. Paste using <kbd>Ctrl</kbd>+<kbd>V</kbd>.

Expected behavior: The text "line 1\nline 2" (\n means newline) should be pasted in both places.
Actual behavior: The text "line 1" is pasted at the first cursor and "line 2" is pasted at the second cursor.

Note: if you have 3 ore more cursors instead of 2, this works as expected. It only happens when there are exactly 2 cursors.

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
Settings:
```js
"editor.multiCursorPaste": "full",
```

**Comment by MLavrentyev** [comment]
Thanks @usernamehw - this works. Ideally, though, this would be default behavior, with the other being opt-in?

**Comment by MLavrentyev** [comment]
Closing since it's not an issue per say just a weird "feature" that should probably be off by default :) .
