### ISSUE TITLE
The <Enter> is swallowed by the auto-complete box.

### ISSUE THREAD

**Issue by xnsua** [Microsoft/vscode#10270]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. type "abc" and Space
2. type "abc" and Enter

The cursor is at the end of line instead of new line because  the auto complete swallow the Enter.

**Comment by joaomoreno** [comment]
<kbd>Enter</kbd> is the key to accept the current suggestion in the suggestions box, which in your case happens to be `abc`, a word based suggestion. If you don't like word based suggestions, you can disable them using the `editor.wordBasedSuggestions` setting.

**Comment by rhys-vdw** [comment]
For anybody else looking for a fix for this, add the following to your keybindings:

```json
    { "key": "enter", "command": "-acceptSelectedSuggestionOnEnter" },
    // Useful for Vim plugin:
    { "key": "escape", "command": "-hideSuggestWidget" }
```

This way neither <kbd>Enter</kbd> or <kbd>Esc</kbd> are consumed by the suggestion widget. There are plenty of other keys bound by default, I prefer to press <kbd>Tab</kbd> for this particular action.
