### ISSUE TITLE
Allow to detect when my extension is running in the development host

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#10272]
I'd like to be able to detect when running in the dev host to avoid polluting live analytics with development stuff. I've looked at everything I can think of and can't find a way to detect this.

The best I found was in the `confirmSave` method which bails out in the extension host using this:

```
if (!!this.contextService.getConfiguration().env.extensionDevelopmentPath) {
```

however I can't see a way to access the same thing from my extension.

How can I do this? How are other extensions keeping dev usage out of telemetry?

**Comment by bpasero** [comment]
Not to my knowledge. @jrieken fyi

**Comment by DanTup** [comment]
For now I'm using the extensions version and suffixing with "-dev" (and only removing for release) builds, but it sucks a bit. Also not sure if this is the optimal way to do that?

    let packageJson = require('../../package.json');
    this.version = packageJson.version;

**Comment by DanTup** [comment]
@bpasero @jrieken I've noticed that `env.machineId` returns `"someValue.machineId"` in the dev host but a guid in the real one. Is this expected? Is it stable enough for me to use as a check for now instead of the "-dev" suffix on my version?

**Comment by bpasero** [comment]
I would think that the telemetry key is bogus when you run out of extension host because we also do not want to log any telemetry in that case. It seems like a fair assumption to check on that for now.

**Comment by DanTup** [comment]
Great; I'll use that for now, thanks!

**Comment by TylerLeonhardt** [comment]
Here's our current workaround... But would love a more official API than a string compare

https://github.com/PowerShell/vscode-powershell/blob/master/src/session.ts#L59-L63

**Comment by connor4312** [comment]
Merging this into https://github.com/microsoft/vscode/issues/95926 🙂 

/duplicate
