### ISSUE TITLE
Integrated Terminal is slow when wrapping very long line

### ISSUE THREAD

**Issue by crystalin** [microsoft/vscode#102705]
- VSCode Version: 1.47.1 & 1.48.0-insider
- OS Version: Windows NT x64 10.0.19042

Steps to Reproduce:

1. generate a long line in terminal, exemple (javascript):
```
let data = [];
for (let i = 0; i<20000; i++) {
    data.push(Math.floor(Math.random() * 16).toString(16));
}
console.log(data.join(''));
```
2. observe how slow it is (scrolling up into the middle of the text makes it even worse)

This issue appears with `--disable-extensions` also with `--disable-gpu` or with any choice of `terminal.integrated.rendererType`.
This issue is independent of the shell (powershell, cmd, wsl.... all have the issue)
VsCode also freezes when the terminal freezes (If the line is very long, it might trigger notification to "kill or wait vscode")

During the freeze, CPU is at around 10% (high considering there are 8/16 cores), GPU at 0%

Keeping the terminal visible (without any changes in its content) makes VSCode slow. The more of the lines is displayed, but also the longer the text is (outside of the visible area), the slower it gets.

Hiding the terminal by switching to another one restore the UI responsiveness to the normal.

I suspect this is related to the computation of the line wrap.

**Comment by Noh3choo** [comment]
+1 same exact issue here, any very long line printed to the integrated terminal sends 1 thread to 100% and locks up the entire IDE.

**Comment by Tyriar** [comment]
@Noh3choo you might be using the dom renderer, try this setting `"terminal.integrated.rendererType": "experimentalWebgl"`

**Comment by crystalin** [comment]
@Tyriar, it is still failing with `"terminal.integrated.rendererType": "experimentalWebgl"`

**Comment by Tyriar** [comment]
@crystalin your issue is likely the Windows-specific https://github.com/microsoft/vscode/issues/74620

**Comment by Noh3choo** [comment]
> @crystalin your issue is likely the Windows-specific #74620

I don’t think it is, this is a recent regression and not a duplicate.

I am not using the DOM renderer and setting experimentalWebgl has not affect on the bug.

**Comment by Tyriar** [comment]
@Noh3choo on Linux if you have problems scrolling, it's renderer related. You can try launching with `--disable-gpu`, changing the renderer or updating your gpu drivers. Your issue is different to @crystalin's.

**Comment by Noh3choo** [comment]
Thanks Tyriar,

I have tried all of your suggestions and none change the behavior.
