### ISSUE TITLE
unable to run pip on vs code

### ISSUE THREAD

**Issue by sam-19282** [microsoft/vscode#102757]
Issue Type: <b>Bug</b>

i'm trying to install django by pip
but unfortunately pip is not working . i've checked my system variables everything is perfectly fine ,scripts and python location are there in the path. 
pip is working fine on my cmd but not in vs code terminal

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.3
pip-packages|etm|0.4.3
vscode-mysql|for|0.4.0
mssql|ms-|1.9.0
python|ms-|2020.7.94776
sqltools|mtx|0.22.10
sqltools-driver-mysql|mtx|0.1.0

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
