### ISSUE TITLE
Node commands failing

### ISSUE THREAD

**Issue by gorurs** [microsoft/vscode#102763]
Issue Type: <b>Bug</b>

Cannot find module '/var/folders/yv/8mg22m5n14xgdsfqdpw_521r3khmh4/T/vscode-js-debug-bootloader.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:901:12)
    at preloadModules (internal/bootstrap/node.js:601:7)
    at startup (internal/bootstrap/node.js:273:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (11.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
clipboard-history|Anj|1.0.7
path-intellisense|chr|2.2.1
vscode-navigate-edit-history|cod|1.1.0
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.6.8
xml|Dot|2.5.0
gitlens|eam|10.2.2
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.1.3
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
clear-console|mwo|0.0.3
color-highlight|nau|2.3.0
dust|nem|0.0.1
java|red|0.64.1
html-to-jsx|ria|0.0.1
stylelint|shi|0.51.0
vscode-spotify|shy|3.1.0
sort-lines|Tyr|1.9.0
highlight-matching-tag|vin|0.9.9
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.26.0
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.22.0
vscode-import-cost|wix|2.12.0
local-history|xyz|1.8.1
json-helper|zho|1.3.2

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Please toggle "auto attach" to "disabled" and then back to "on" if you'd like to use it.

/duplicate

**Comment by cmawhorter** [comment]
google returns this as the top result when searching so:

- dupe is [here](https://github.com/microsoft/vscode/issues/102557)
- and as mentioned there, the solution is to [download the nightly](https://code.visualstudio.com/insiders/) until an update ships
