### ISSUE TITLE
font size 

### ISSUE THREAD

**Issue by RolandBrake** [Microsoft/vscode#10276]
- VSCode Version:1.4.0
- OS Version:Microsoft Windows [Version 6.1.7600]

how to change the font size of intellisense list in vs code the font is too small to read

**Comment by BinaryResolved** [comment]
@RolandBrake Go to File > Preferences >User settings. Two new editor tabs should open, one being "Default Settings" the other being "settings.json". You can't edit the Default Settings so you override it by putting your edited settings in settings.json. The default font size is set to 14, so in settings.json you would put `"editor.fontSize": 16` chance 16 to your desired font size.

**Comment by RolandBrake** [comment]
@BinaryResolved  the editor.fontSize  property work just for the editor font not for intellisense list any other suggestions?

**Comment by joaomoreno** [comment]
#2465
