### ISSUE TITLE
Execution line is not highlighted in debug mode

### ISSUE THREAD

**Issue by python481516** [microsoft/vscode#102748]
When starting VS Code from Git Bash console with `code .`,  debugger doesn't highlight the line once the breakpoint is hit. This occurs for Python projects, I haven't tried other languages. This issue happens ONLY when VS Code is launched from Git Bash console. Also, it is only present in 1.46.1, 1.47.1 and 1.47.2 versions. Previous versions work fine.

- VSCode Version: 1.46.1, 1.47.1 and 1.47.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open Git Bash
2. Navigate to your project folder and start VS Code by running `code .`
3. Put a breakpoint anywhere in the code
4. Run the debugger.
5. Once the breakpoint is hit, current execution line will not be highlighted. The only good way to determine where the code execution paused is by looking at Call Stack section where it says "Paused on breakpoint" and below there is position indicated (e.g. `1:1`)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by python481516** [comment]
@isidorn can't reproduce, seems to work as expected with Insiders

**Comment by isidorn** [comment]
Then closing this, and you can use vscode insiders or wait for the July stable release.
