### ISSUE TITLE
Indicate files that got moved or copied in explorer with some styling

### ISSUE THREAD

**Issue by eyalsk** [Microsoft/vscode#10284]
I'm not sure whether this was proposed before but what I'm thinking is to style files that are dragged in italic and when you release have them in bold.

The same for copied files, when you copy something, it's going to be styled in italic and when you paste it's going to be bold, this can be quite helpful for times that you don't know whether you copied to the wrong directory or where are the files for some odd reason.

Now the files are going to stay bold until you open them, obviously it can be something different other than italic/bold but that's not really important.

This is just a small quality of life improvement but I think one that _can_ be useful.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
