### ISSUE TITLE
Automatically debugging a process launched by another executable

### ISSUE THREAD

**Issue by rpep** [microsoft/vscode#102802]
Is it possible to write a launch.json configuration which does:

1) Execute one process, for e.g. server.exe (which launches otherProcess.exe)
2) Then attach to otherProcess.exe automatically?

I can obviously attach to otherProcess.exe directly once it's started up, but I really need to capture it as it launches, and I've not managed to find a way to do it so far

**Comment by connor4312** [comment]
You should post this in whichever language extension you're using (e.g. C#/C++/Go...). They should be able to answer this.

/causedByExtension
