### ISSUE TITLE
Run Python Debug Console in Existing Terminal

### ISSUE THREAD

**Issue by keyonvafa** [microsoft/vscode#102846]
When I use the debugger on a Python file (via ```F5```), the Python Debug Console opens in a new terminal. It would be great to have the option to have the Python Debug Console open in an existing active terminal. The reason for this is that I use Remote to develop on a shared cluster. My workflow is: I request a machine for an interactive job, so my terminal is attached to a specific machine. However when I run the debug command, the Python Debug Console opens a new terminal on the main node of the cluster rather than on the machine I'm using for the interactive job. 
Thank you!

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
