### ISSUE TITLE
Cannot run `node` TASKs: $PATH not sourced correctly

### ISSUE THREAD

**Issue by Domiii** [microsoft/vscode#102890]
- VSCode Version: 1.47.2
- OS Version: macOS 10.14.6

**Steps to Reproduce:**

1. Add a new task:
   ```js
    {
      "label": "Test node",
      "type": "shell",
      "command": "node",
      "args": [
        "-v"
      ]
    }
   ```
2. Run task
3. Result: It cannot find node!
   > Executing task in folder dbux: node -e "console.log('hi!');" <
   > /bin/bash: node: command not found
   > The terminal process "/bin/bash '-c', 'node -e "console.log('hi!');"'" failed to launch (exit code: 127).

I would argue that this is a substantial problem, because it prevents me from using any node-based task.

Does this issue occur when all extensions are disabled?: Yes

**Analysis**

This issue has previously been discussed in https://github.com/microsoft/vscode/issues/29412

Here is some more relevant info:

1. If I open a terminal window, and do `which node`, I get:
   > /Users/domi/.nvm/versions/node/v13.12.0/bin/node
2. We know that `nvm` injects it's paths into $PATH via `.bashrc` and, as discussed in #29412, `.bashrc` is not executed explicitely.
   * NOTE: my `.bashrc` does not have the "no-interactive" part in it. It should always execute.
   * This is Ok... Let's assume `.bashrc` is just not sourced
3. @dbaeumer pointed out that the correct $PATH should be sourced for VSCode at start-up anyway, and then be inherited by the shell.
   * For this, @joaomoreno recommended checking Dev Tools -> `project.env.PATH`, which for me is actually correct: 
      `> process.env.PATH`
      `<- "stuff:/Users/domi/.nvm/versions/node/v13.12.0/bin:morestuff"`
4. However, tasks' `$PATH` is just not right. I verified with this task:
   ```json
   {
      "label": "Test node",
      "type": "shell",
      "command": "echo",
      "args": [
         "$PATH"
      ]
   }
   ```
   > /usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.

So the problem is that the $PATH is not inherited from `VSCode` despite the team's own assumption of that to be the case.

Thoughts?

**Comment by Domiii** [comment]
I have found a workaround for now: run `bash` as a login shell (`-l`), and supply command as parameter (`-c`):

```json
{
  "label": "Test node",
  "type": "shell",
  "command": "bash",
  "args": [
    "-lc",
    "--",
    "node -v"
  ],
}
```

> v13.12.0

**Comment by alexr00** [comment]
@Domiii do you have any options set outside the task in your tasks.json, like this?

```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"options": {
		"env": {
			"one": "one"
		}
	},
	"tasks": [
		{
			"label": "npm",
			"type": "npm",
			"script": "watch",
			"problemMatcher": [
				"$ts-webpack-watch"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

**Comment by Domiii** [comment]
@alexr00 No options, nothing. The whole thing is just:

```jsonc
// tasks.json
{
  "version": "2.0.0",
  "tasks": [
  // ...
  ]
}
```

**Comment by alexr00** [comment]
@Domiii when you opened the dev tools with Developer: Toggle Developer Tools and checked `project.env.PATH`, did you do it from the exact same window that you see this issue in VS Code in?

**Comment by Domiii** [comment]
I found the problem: I had `"terminal.integrated.inheritEnv": false` in my User settings. Probably from a while back where I was advised to add it to workaround some other issue I had.

Anyway, all is good. Thanks for the continued support! :)
