### ISSUE TITLE
Webview pasting twice on input/textarea elements

### ISSUE THREAD

**Issue by agrawal-d** [microsoft/vscode#102805]
Issue Type: <b>Bug</b>

Since a recent update, Webview `<input>` and `<textarea>` elments are receving dulpicated strings on paste:

If I paste `abc` from my clipboard (Ctrl+V), `abcabc` appears on the element.

## Minimal reproduction sample

The official webview-api sample extension is enough: https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample

Just add an `<input>` to the HTML string in `extension.ts` `_getHtmlForWebview` function, and try pasting a string into it.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-14T00:13:57.513Z)
OS version: Linux x64 5.4.0-37-generic snap

____

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2797)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (6.41GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by mjbvz** [comment]
Should already be fixed in 1.47.2

**Comment by agrawal-d** [comment]
@mjbvz are there any plans to update the snap? The latest snap version is still `485c41f9` (Updated: Wednesday 15 July 2020)

![image](https://user-images.githubusercontent.com/7714968/87817421-8aea3880-c886-11ea-86e5-6865ad3b32f9.png)

**Comment by abellynow** [comment]
Still present in 1.47.3:
```
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic
```
