### ISSUE TITLE
`searchViewletFocus` doesn't seem to work with `touchBar` menu contributions

### ISSUE THREAD

**Issue by mernen** [microsoft/vscode#102876]
Issue Type: <b>Bug</b>

I'm trying to only show certain actions when the Search sidebar is focused, but the `searchViewletFocus` condition doesn't seem to be respected by Touch Bar contributions. Other values, like `searchViewletVisible` and `editorFocus`, appear to work (not very reliably in `editorFocus`' case, but I'm not sure if it's related, and we may treat that as a separate issue).

I have set up a sample test extension [here](https://github.com/mernen/vscode-touchbar-focus-demo). It has no code at all, only dummy menuBar buttons.

Testing this behavior requires a Mac, preferably one with a physical Touch Bar. If one is not available, it's still possible to try it by opening Apple's Xcode, then going to Window→Touch Bar→Show Touch Bar (Command+Shift+8) before trying the extension.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (1.04GB free)|
|Process Argv|. --disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by roblourens** [comment]
@JacksonKearl I think you made changes here, do you think the keys like `searchViewletFocus` should be set globally too instead of in the scoped context key service? I'm not sure what best practice is here.

**Comment by roblourens** [comment]
@mernen can use the focusedView context key here at least. I probably would have used it for the original issue too, but I don't know. The solution we have now is bulletproof for keybindings but not useful for menus.

**Comment by roblourens** [comment]
I am not sure what the use case is for showing menus based on focus though? @mernen what are you trying to show in this case?

**Comment by mernen** [comment]
I want to show the search options (match case, match whole word, open replace field, etc) as buttons in the Touch Bar when you are in the search pane. I suppose focus-based conditions are not very useful outside of the `touchBar` special menu, though.

**Comment by roblourens** [comment]
Ok. It sounds like the focusedView context key should work for your case?

**Comment by mernen** [comment]
Yes, I can confirm `focusedView  == workbench.view.search` appears to do exactly what I need. Thanks!
