### ISSUE TITLE
Version 1.47.2 not available at https://packages.microsoft.com/yumrepos/vscode/

### ISSUE THREAD

**Issue by rickhg12hs** [microsoft/vscode#102839]
The YUM repo is missing the latest version of `code`.  There is no version `1.47.2`.

**Comment by mikij** [comment]
It seems to me also insiders versions missing there too after July 15th.

**Comment by mikij** [comment]
@Tyriar will you respond. Yum repo is still out of date!!!

**Comment by Tyriar** [comment]
@mikij I'm currently looking into it, was sick yesterday.

**Comment by mikij** [comment]
@Tyriar Sorry to hear that. Hope you are better now.

**Comment by Tyriar** [comment]
This is fixed, there was an issue with the service we use to publish the packages which is all good now. Thanks for the notification.

**Comment by mikij** [comment]
Great thank you.
