### ISSUE TITLE
brackets

### ISSUE THREAD

**Issue by rohitaswchoudhary** [microsoft/vscode#102808]
Issue Type: <b>Bug</b>

not able to change setting for auto complet of brackets for python functions

VS Code version: Code - Insiders 1.48.0-insider (ff6b1c5984a4c2116a06318f07e871a4169fdb1b, 2020-07-17T13:18:36.126Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (1.39GB free)|
|Process Argv||
|Screen Reader|no|
![● 1 py - tutorial - Visual Studio Code - Insiders 17-07-2020 23_45_30](https://user-images.githubusercontent.com/64344633/87818161-c33e4680-c887-11ea-9baf-182cafeb8fb1.png)

|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
code-runner|for|0.11.0
python|ms-|2020.7.94776
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues and please give more details
