### ISSUE TITLE
Write-Output does not display in powershell integrated terminal.

### ISSUE THREAD

**Issue by lachlann562** [microsoft/vscode#102803]
- VSCode Version: 1.47.2
- OS Version: Microsoft Windows NT 10.0.18363.0 (windows 10)

Steps to Reproduce:

1. switch to integrated terminatel
2. write-output 'test'
output:
PS C:\Source\Powershell\Common> write-output 'test'

PS C:\Source\Powershell\Common>
3. switch to normal terminal
4. write-output 'test'
output:
PS C:\source\powershell> write-output 'test'
test
PS C:\source\powershell>

this appears to be sporadic, a new session of vs code does not have this issue but after running a few module debugging sessions it eventually stops working.

Does this issue occur when all extensions are disabled?: Yes/No

cannot test as there isn't a integrated terminal

**Comment by Tyriar** [comment]
I can't reproduce this, it seems more likely that it would be a PowerShell issue as I see many posts about Write-Output not working.

**Comment by lachlann562** [comment]
This issue continues to occur, it seems like it may be a color rather than
output issue. If i pipe it to write-host it has similar problem but if I
change the color to green it outputs. I will confirm this the next time it
happens. I can't find a way to explicitly reproduce it but it seems like
after extended debugging something breaks and it stops working.
