### ISSUE TITLE
Restart to Update not working since version 1.47

### ISSUE THREAD

**Issue by charan9999** [microsoft/vscode#102842]
- VSCode Version: 1.47.2
- OS Version: macOS 11 Beta(20A4300b), 10.15.6, 10.15.5

Steps to Reproduce:

1. After the update is downloaded and ready, the settings icon toggle is highlighted.
2. Click on restart to update
3. The app closes successfully however the app never re-opens.
4. When you open vscode again, the app is successfully updated.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Did you read this? https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469
