### ISSUE TITLE
Problem debugging Deno using VSCode on Ubuntu 20.04 LTS running inside WSL-2: --inspect-brk being removed

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/vscode#102872]
- VSCode Version: 1.47.2
- OS Version:10.0.19645

I am trying to debug Deno using VSCode on Ubuntu 20.04 LTS running inside WSL-2. I setup my launch.json as described in [the Deno manua](https://deno.land/manual/tools/debugger#vscode)l  

`
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Deno",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "deno",
            "runtimeArgs": ["run", "--inspect-brk", "-A", "${fileBasename}"],
            "outputCapture": "std",
            "port": 9229
        }
    ]
}
`

however when I launch Deno the "--inspect-brk" option is being stripped out from the command used to launch Deno. If I modify my launch.json to change the option to "inspect-brk" (removing the leading --) the option shows up on the command line and I get the error:

`
Cannot resolve module "file:///mnt/c/Users/mlwp/projects/deno/inspect-brk"
`
Similarly if I change the name of the option to be "--inspect-brk-fun" then I get the message:

`
Found argument '--inspect-brk-fun' which wasn't expected, or isn't valid in this context
`
Anyone know why VSCode would strip the option or how to debug this

**Comment by connor4312** [comment]
Please see here for instructions for debugging Deno: https://github.com/denoland/vscode_deno/issues/12#issuecomment-658957984

/duplicate
