### ISSUE TITLE
Run In Terminal Error

### ISSUE THREAD

**Issue by subedisdha7** [microsoft/vscode#102854]
Issue Type: <b>Bug</b>

I have done something changes in rgba value now I delete all 4 line[232,343,...] this like value so this made me problem and I can't figure it out in YT also.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by subedisdha7** [comment]
![error](https://user-images.githubusercontent.com/59317282/87846447-9887d880-c8ef-11ea-8541-cbd315e0bcaa.jpg)
 I can't solve this please help

**Comment by Tyriar** [comment]
It's not clear from your write up or screenshot what the issue is.
