### ISSUE TITLE
git diff localization for HEAD in Japanese

### ISSUE THREAD

**Issue by ItGacky** [Microsoft/vscode#10283]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Open git diff view
2. Tab shows "filename (見出し) <=> filename"

HEAD should not be localized to 見出し.

**Comment by joaomoreno** [comment]
cc @lukaschal @dbaeumer

**Comment by dbaeumer** [comment]
Our milestone builds are usually not fully localized since new feature or code reorgs might need changes in the localization files. The next build that will be fully localized is 1.5. @joaomoreno I would opt to close this as long has the code has a proper localize call.

**Comment by joaomoreno** [comment]
@dbaeumer This is about a string that was incorrectly localised, not missing localisation.

**Comment by dbaeumer** [comment]
@joaomoreno thanks. Missed that.

**Comment by lukaschal** [comment]
@joaomoreno  Please, is it possible to add ENU/JPN screenshot ?

**Comment by ItGacky** [comment]
There is the unwanted localization at least in ja, and not in zh-TW. I didn't checked in other locales.

--locale=en
![image](https://cloud.githubusercontent.com/assets/17490154/17661377/b3e7f9d8-6319-11e6-9417-909bb03663a7.png)
--locale=ja
![image](https://cloud.githubusercontent.com/assets/17490154/17661465/4b41f414-631a-11e6-9747-204f71eaa3b4.png)
--locale=zh-TW
![image](https://cloud.githubusercontent.com/assets/17490154/17661462/42c3c6aa-631a-11e6-806e-9ee292a82a25.png)

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
File: src\vs\workbench\parts\git\browser\gitServices.nls.resx
ID: src\vs\workbench\parts\git\browser\gitServices.nls.resx
SRC: {0} (HEAD) ↔ {1}
TGT: {0} (見出し) ↔ {1}

**Comment by lukaschal** [comment]
Fixed on JPN.

**Comment by lukaschal** [comment]
@ItGacky @joaomoreno Please is possible to add screenshots from CHS, ESN, ITA, FRA, KOR, DEU builds to see better context ? or should we revert all langs to ENU without any linguistic input ?

**Comment by joaomoreno** [comment]
cc @dbaeumer

**Comment by dbaeumer** [comment]
@joaomoreno is there anything for me to do? IMO we should revert all languages back to HEAD and add a comment in the corresponding git code that HEAD shouldn't be translated so that this info flows to the translation team.

**Comment by joaomoreno** [comment]
@lukaschal All languages should literally show `HEAD`. I can add a comment in the localize call.

**Comment by lukaschal** [comment]
Fixed on all langs.

**Comment by Tyriar** [comment]
Verified for `HEAD`, created a new issue for `index` #11344
