### ISSUE TITLE
vscode update problem plzzz help me out... 

### ISSUE THREAD

**Issue by roshanprajapati03** [microsoft/vscode#102869]
Issue Type: <b>Bug</b>

when i am updating vscode i get this error.....

ENOENT: no such file or directory, mkdir
Source : Update Service 

help me plzzzzz
Email - instaboy207@hotmail.com
github - roshanprajapati03

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.89GB (2.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
kotlin|fwc|0.2.18
Kotlin|mat|1.7.1
vs-keybindings|ms-|0.2.0
vscodeintellicode|Vis|1.2.9

</details>

**Comment by joaomoreno** [comment]
Have you tried completely reinstalling VS Code?

**Comment by roshanprajapati03** [comment]
> Have you tried completely reinstalling VS Code?

Yes i tried three times to completely reinstall VS Code...i get same error

**Comment by joaomoreno** [comment]
Do you overwrite the `TEMP` environment variable in your system? What does `echo %TEMP%` in a command prompt return?

**Comment by roshanprajapati03** [comment]
> Do you overwrite the `TEMP` environment variable in your system? What does `echo %TEMP%` in a command prompt return?
@joaomoreno 

![return echo](https://user-images.githubusercontent.com/19780417/88124288-607fde80-cbea-11ea-916e-1ab81a23cefe.PNG)


![env](https://user-images.githubusercontent.com/19780417/88124296-68d81980-cbea-11ea-92c5-a058ee89ae24.PNG)

**Comment by joaomoreno** [comment]
That is a problem. Please just set `TEMP` to the same value as `TMP`.
