### ISSUE TITLE
No visible path/directory of project

### ISSUE THREAD

**Issue by vitrivedi07** [microsoft/vscode#102886]
Issue Type: <b>Feature Request</b>

Hey! can I get to see project path/ directory without going somewhere or clicking anywhere. When i m working on two VS code windows with similar name projects and switching between them, it becomes difficult to know.
   Right now i have to hover on a file to know the path. A quick view of path will be really handy.
                                                                                         
                                                                                                   Thank You.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 6.1.7601

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/updates/v1_10#_configurable-window-title

**Comment by IllusionMH** [comment]
In addition to ability to customize window titles you might also check [Peacock extension](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) which allows to quickly generate different colors for each workspace and differentiate them by colors.

**Comment by roblourens** [comment]
Both good suggestions, thanks

**Comment by vitrivedi07** [comment]
> See https://code.visualstudio.com/updates/v1_10#_configurable-window-title

Thank you for help
