### ISSUE TITLE
Contextual menu in NPM Scripts panel does not function if debug button is present

### ISSUE THREAD

**Issue by devuxer** [microsoft/vscode#102847]
- VSCode Version: 1.47.2
- OS Version: Windows Version 10.0.18363 Build 18363

Steps to Reproduce:

1. Open a project containing NPM scripts
2. If necessary, add a script that contains `node --inspect ./path/to/executable.js` to package.json
3. Expand the NPM SCRIPTS panel in the EXPLORER
4. Right-click (or Mac equivalent) the script containing `--inspect` 
5. Note that no contextual menu appears (unlike with scripts that are not debuggable)

Does this issue occur when all extensions are disabled?: Yes (also got same result with Insiders)

**Comment by connor4312** [comment]
Thanks for the issue!
