### ISSUE TITLE
Hot code replace not working for java

### ISSUE THREAD

**Issue by Mike-the-one** [microsoft/vscode#102868]
- VSCode Version: 1.47.1
- OS Version: Deepin GNU/Linux 15.11

Steps to Reproduce:
I have latest java extensions from redhat, all java related extensions are updated to latest code.

In debug session, after I change the source code, save it, the hot code replace doesn't happen.
Tried manual mode, this is message I am getting:

> Cannot find any changed classes for hot replace!

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Please file this on the repo for the Java language extension: https://github.com/redhat-developer/vscode-java/issues

Thanks!
