### ISSUE TITLE
All the extension are useless

### ISSUE THREAD

**Issue by a1019476486** [microsoft/vscode#102863]
The color of each code is loss.  In the bottom where I can choose the type of  programning languages . I can see no  type of programning languages but there is only "log" and "plain text".  The other are lost.  
In the extension, I can not see any extension which are installed but I can search and it mentions that I have installled but don not work out. If I reinstall them, it did not work either.
I have reinstalled vscode,  it still run wrong.

**Comment by alexdima** [comment]
@a1019476486 Perhaps you have disabled all extensions? What does it show if you search for "@disabled" extensions in the extensions viewlet?

![image](https://user-images.githubusercontent.com/5047891/88281637-55ab7380-cce8-11ea-81cf-a141630b5414.png)

Have you tried installing the Insiders version? Are there any errors in the developer tools (`Help > Toggle Developer Tools`)
