### ISSUE TITLE
Vscode Reading mode

### ISSUE THREAD

**Issue by fahadahmed84650** [microsoft/vscode#102811]
dear team,

i want code reading mode where all code errors, warnings, highlights should not show in reading mode except vscode theme styling or extensions
![01](https://user-images.githubusercontent.com/68442286/87820293-752b4200-c88b-11ea-9557-92a2cae26a86.png)

please check attachment what actually i facing issues while reading code.

please add this feature.

Thank you.

**Comment by alexdima** [comment]
@fahadahmed84650 That is interesting. Normally, VS Code does not render so noisy with so many inline errors. So I believe one of your extensions is doing that. Can you please try to disable your extensions, how does the rendering look like then?
