### ISSUE TITLE
JS Debugger tries to run src file instead of build file

### ISSUE THREAD

**Issue by inabahare** [microsoft/vscode#102819]
- VSCode Version: 1.47.2-1
- OS Version: Arch with kernel 5.7.8-arch1-1

So I have this project that uses Babel to transpile JS to JS and I'm getting the following

```
Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/inaba/Programming/Lewd/packages/main-site/src/index.js:1
import express from "express";
```

with the following launch.json

```
{
  "type": "node",
  "request": "launch",
  "name": "Launch Main App",
  "preLaunchTask": "npm: build",
  "program": "src/index.js",
  "sourceMaps": true,
  "outFiles": [
    "dist/**/*.js"
  ],
  "envFile": "${workspaceFolder}/../../.env",
  "runtimeArgs": [
    "--require=dotenv/config"
  ]
}

```

Which (I hope) can be reproduced by cloning [this repo](https://github.com/inabahare/lewd2), going to packages/main-site, ```npm install``` and then running the debugger.

Now I'm not sure if it's a bug or I just misunderstood something, but I have asked on Reddit and Stackoverflow with little luck

**Comment by connor4312** [comment]
It looks like your `program` is set to the source file

```
  "program": "src/index.js",
```

Did you mean to set this to `dist/index.js`?

**Comment by inabahare** [comment]
Dude, conner, marry me!

So yeah I was under the impression I needed it to be assigned to src/index.js because as that's what is seen [here](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-maps) (but with typescript). And I thought it would be the case too since pointing it to dist would mean debugging didn't work. But you're right, the sourcemap urls were borked!

And to the person from Google in 5 years what I needed to do was to add "--public-url ." to the build flags!
