### ISSUE TITLE
hover react native global variable `__DEV__` to display usage of if (DEV) ?

### ISSUE THREAD

**Issue by safarishi** [microsoft/vscode#102848]
- VSCode Version: 1.48.0-insider
- OS Version: macOS Catalina (10.15.4)

Steps to Reproduce:

1. In a react native typescript project
2. Hover the mouse to the __DEV__ global variable but see Typical usage if (`DEV`) instead of if (`__DEV__`)

![image](https://user-images.githubusercontent.com/9312426/87843245-8012c080-c8e5-11ea-8b16-faced0f0b262.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is an issue with the jsdoc for `__DEV__`. It should mark code samples correctly. We parse doc comments as markdown so `__DEV__` outside of a code block will become __DEV__ (bolded)
