### ISSUE TITLE
1.47 Debug Breakpoints appearing in sourcemap files

### ISSUE THREAD

**Issue by brandonlee781** [microsoft/vscode#102833]
- VSCode Version: 1.47.2
- OS Version: macOS 10.15.5

With the newest debugger, the method used to debug our node app no longer works the same. The breakpoints appear unbound, but the breakpoint gets hit inside the sourcemap file, not the original file like it used to. Replication repo: https://github.com/brandonlee781/vs-code-debugging-issue

Steps to Reproduce:

1. Run terminal command "npm run dev"
2. Start the Attach debugger task
3. Place a breakpoint inside the express route. The breakpoint will appear unbound.
4. In a browser go to http://localhost:4000
5. The breakpoint is hit, but it's in the sourcemap file, not the original file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
This is the same as https://github.com/microsoft/vscode-js-debug/issues/636

/duplicate
