### ISSUE TITLE
Multiline comments may become non collapsible

### ISSUE THREAD

**Issue by terje-rosenlund** [microsoft/vscode#102856]
- VSCode Version: 1.47.1 (system setup)
- OS Version: Windows_NT x64 10.0.19041

1. Create a new file
2. Insert:
```
#!/usr/bin/env nodejs
'use strict';
/* 
This 
multiline comment
is collapsible
 */
function test() { }
```
3. Insert this line at line 8 (between comment and function)
`const constTest = '';`
4. The multiline comment is no longer collapsible

The multiline comment is still collapsible when you create a new line at line 8 but the collapse token dissapeares as soon as you start typing

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Looks like an issue in the TypeScript language service

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/40010 to track upstream
