### ISSUE TITLE
can't use the powershell to launch the bash.exe 

### ISSUE THREAD

**Issue by czmecho** [Microsoft/vscode#10288]
- VSCode Version:1.4
- OS Version:win 10 14393.10

Steps to Reproduce:

1. use Ctrl+` to call the powershell 
2. when I want to use the BashOnWindows, it show the result:
![](http://ww3.sinaimg.cn/large/7df5111fgw1f6mejwjfryj215q09qgpp.jpg)
![](http://ww3.sinaimg.cn/large/7df5111fgw1f6mejxf7jsj21ae07lwj2.jpg)

**Comment by Tyriar** [comment]
Try `c:\Windows\sysnative\bash.exe`

**Comment by czmecho** [comment]
@Tyriar thanks,it works.
I try to put c:\Windows\sysnative\ in the environment variable ,and it work when it just use bash to call the bash.exe.
