### ISSUE TITLE
[themes] update theme-seti extention

### ISSUE THREAD

**Issue by azilnik** [microsoft/vscode#102835]
- VSCode Version: Production
- OS Version: MacOS Catalina

Steps to Reproduce:

1. Check out the latest commits https://github.com/jesseweed/seti-ui/commits/master
2. See that is it behind in vscode https://github.com/Microsoft/vscode/tree/master/extensions/theme-seti

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
fixed with https://github.com/microsoft/vscode/commit/bdcf7e10cd7cc1ef323f03d2851651d271aa36f6
