### ISSUE TITLE
Not possible to specify quoted arguments in tasks

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#1028]
eg

"C:\Program Files\Git\bin\bash.exe" -c "ls -a" 

It is impossible to encode "arguments" to resolve to `-c "ls -a"` as far as I can tell. Every attempt to escape quotes or put spaces in an argument string fail.

**Comment by gubatron** [comment]
care to show some code on how you're trying to do it?

**Comment by SteveALee** [comment]
Good point  - I'll add to https://github.com/Microsoft/vscode/issues/1028
For some reason this comment is not appearing there

Steve Lee
OpenDirective http://opendirective.com

**Comment by SteveALee** [comment]
So I set up a new task and commented out all the others (the docs dont say this but it seems what is needed). There **is** a good reason I'm using bash but even so other commands can have similar options. The `ls -a' is just something easy to test. The point is the arg is the switch -`c` followed by a quoted value string with spaces in it.

<pre>
{
	"version": "0.1.0",
	"command": "C:\\Program Files\\Git\\bin\\bash.exe",
	"isShellCommand": true,
	"showOutput": "always",
	"args": ["-c ","ls a"],
	"problemMatcher": "$tsc"
}
</pre>

I realise the problem matcher is not right but for now need to ge the command to run
Here's the various options I tried for `args`

* As `-c "ls a"` is a single arge we try it as a array element and escape the quotes- `["-c \"ls -l\""]` This is difficult as code keep adding extra `"` characters. Had to copy and paste a single `"` Get error 
<pre>
'"C:\Program Files\Git\bin\bash.exe"" -c  "ls' is not recognized as an internal or external command,
operable program or batch file.</pre>
It seems to be missing every following the space after `ls`.

* Ok, so how about making it 2 strings incase the arge parsing is a little borked  `["-c","\"ls -a\""]` but get error
<pre>
'"C:\Program Files\Git\bin\bash.exe"" -c "ls' is not recognized as an internal or external command,
operable program or batch file.
</pre>
Again it seems to break at that space

* lets try 2nd string without quotes in case they get added.`["-c","ls -a"]` again get error
<pre>
'"C:\Program Files\Git\bin\bash.exe"" -c   "ls' is not recognized as an internal or external command,
operable program or batch file.</pre>

I tried even more esoteric options like trying to escape the space, but could find nothing that works.

For what it's worth thing rings a vague bell. Many moons ago I did a lot of 'system' OS programming for developer tools involving launching command sub shell processes and handling env and args etc.. in C. I seem to recall there were to APIs for running the cmd shell; one with an array of args and one taking a string for all args. I also seem to recall similar problems handling all possible args. 

If I get time in coming weeks I'll take a look at the source

**Comment by dbaeumer** [comment]
This got addressed by the new terminal runner and task `2.0.0`. To make use of the new terminal runner please see: https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200

Tasks `2.0.0` support to specify a command line for shell tasks which give full control over quoting and space escaping.
