### ISSUE TITLE
Terminal Not Working

### ISSUE THREAD

**Issue by KKNYT** [microsoft/vscode#102879]
Issue Type: <b>Bug</b>

So I was coding my discord bot and tried to run it in the terminal as intended; so I pressed "run active file" so it automatically put "C:Users/Wyllan/Desktop/Flamingo/bot.py" but it just went to a new new line and put "C:Users/Wyllan/Desktop/Flamingo>" with new line and a space.

I do not know how to replicate but plz help.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-6310 APU with AMD Radeon R4 Graphics     (4 x 1797)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.93GB (2.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.7.94776
atom-keybindings|ms-|3.0.8
mcscript|Ste|0.0.3

</details>

**Comment by KKNYT** [comment]
I disabled extensions and it still didn't work :'(

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
