### ISSUE TITLE
CodeLens Stopped Working for Cells in Python Files

### ISSUE THREAD

**Issue by rafidka** [microsoft/vscode#102896]
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-17T10:49:51.211Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.8-200.fc32.x86_64

Steps to Reproduce:

1. Install Codium via Fedora's Software or gitlab.com_paulcarroty_vscodium_repo repository.
2. Ensure that you have Python plugins installed and CodeLens enabled using the following settings:
```json
    "editor.codeLens": true,
    "python.dataScience.codeLenses": "python.datascience.runcell,  python.datascience.runallcellsabove, python.datascience.debugcell",
```
3. Create a simple Python test file with a couple of cells starting with '# %%'

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
We don't support codium, sorry.

**Comment by rafidka** [comment]
But my understanding is that VSCodium is the same exact code as VSCode, excluding telemetry, no? Is this problem not showing on VSCode on Fedora as well?
