### ISSUE TITLE
Missing characters in integerated terminal 

### ISSUE THREAD

**Issue by AK-CHP1** [microsoft/vscode#102888]
Issue Type: <b>Bug</b>

When I opened the vscode integrated terminal and entered `ls` command I found something like this:
![Screenshot at 2020-07-19 15-14-44](https://user-images.githubusercontent.com/56510780/87872506-e88d9a80-c9d6-11ea-93e2-12b25bf5eff7.png)
I restarted it and when I opened terminal, the prompt was partially blank like this:
![Screenshot at 2020-07-19 15-44-53](https://user-images.githubusercontent.com/56510780/87872536-196dcf80-c9d7-11ea-8e3a-797a99eadbbf.png)
I restarted with the option `--disable-extensions` but the issue was same. However, when I used `--disable-gpu` option, the problem was solved. But I don't think it is the correct solution of this problem. I have also faced same problem in previous versions. How to permanently fix this issue?
 

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 5.4.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E4500  @ 2.20GHz (2 x 2059)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 1|
|Memory (System)|1.93GB (0.07GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
cpptools|ms-|0.29.0
shellcheck|tim|0.9.0
city-lights-icon-vsc|Yum|1.1.3

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
> when I used --disable-gpu option, the problem was solved

If this is the case it's an issue with Chromium and canvas on Linux with your drivers. You can avoid using the canvas-based renderers in the terminal with:

```
"terminal.integrated.rendererType": "dom"
```

This will go to the slower DOM-based renderer which should show up fine. Other things you can do is try updating your graphics drivers or just wait for the fix in Chromium to bubble down to Electron and us.
