### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by ahmad693** [microsoft/vscode#102853]
Issue Type: <b>Bug</b>

Hi , thank u for ur nice VSCODE.

Make it short . Not only I can not rename the folder in WORKSPACE but also I can not do it in my windows folder.

please check u can see some weird things.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
vscode-languagetool-fa|ada|3.8.0
vscode-intelephense-client|bme|1.5.2
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.9.0
beautify|Hoo|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
python|ms-|2020.7.94776
debugger-for-chrome|msj|4.12.9
color-highlight|nau|2.3.0
polacode|pnp|0.3.4
view-in-browser|qin|0.0.5
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.9.0
code-spell-checker-persian|str|0.1.2
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by ahmad693** [comment]
![vscode](https://user-images.githubusercontent.com/65893660/87846387-b3088480-c8e4-11ea-942a-be8a8dc4ff5e.JPG)

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by NetScr1be** [comment]
Came here with the same issue (unable to find how to rename workspace).

All other instances are either just closed (as duplicates of something that is not specified) or closed like this one due to lack of activity.

As a support professional myself what this looks like is gaming the system by arbitrarily closing issues to hit KPI.

Please advise how to rename workspaces.
