### ISSUE TITLE
VS Code Accessibility Call - July 2020

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#102832]
Each month, we try to hold a call where users in our accessibility community can give feedback, bring up problems, and share accessibility practices with members of our team. The June call will be held on Thursday, July 23th at 8am PDT / 5pm CEST / 8:30pm IST.

In order to facilitate richer communication and get more focused feedback, we will limit to 4 people on the call, thus we are asking those who are interested in participating to fill out the sign up link below:

[Sign up to participate](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR56QZY-o1WBHqGH6gasleCBUMFBNTFVIVk1SWlhRUFMxV1VSTlQ3WDA0Sy4u)

### Agenda:
- Introductions

- Problems navigating the settings editor have come up in previous calls, so we have some new ideas to navigate through settings groups and browse smaller non-virtual lists instead of a giant virtual list. (https://github.com/microsoft/vscode/issues/97567) @9at8 

- Feedback on remote collaboration using VS Code and Live Share @venkateshpotluri

We will reach out to confirm those who will be participating in the call and send you a Microsoft Teams link to join the call. We will post the meeting recording and meeting notes at the end of the call.

**Comment by venkateshpotluri** [comment]
We would like to know more about your experience with LiveShare and your experience remotely collaborating on code in the July VSCode accessibility call. You are not required to use LiveShare; we would still like to hear from you! If you choose to try LiveShare, our conversations may be centered around the follow feature of LiveShare. More specific questions can be found at #103116
