### ISSUE TITLE
annoying c/cpp auto completion

### ISSUE THREAD

**Issue by netjune** [Microsoft/vscode#10282]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

insert the following c code in c file:
`int i;`

On the second 'i' char, there was completion with prefix 'i'. It is OK.
On the last ';' char, there should not be auto completion, BUT there was (with all the symbols as candidates). Then I can't hit ENTER cause it will selection the first completion item.

By the way, how can I set the minimal prefix length to begin the auto completion?

**Comment by aeschli** [comment]
@netjune Is this with the c/c++ extension?

**Comment by netjune** [comment]
Yes, it must be. I only installed the following two extensions:
(1) c/c++ (0.8.1)
(2) Toggle Header/Source (0.1.2)

**Comment by jrieken** [comment]
This issue was moved to Microsoft/vscppsamples#141
