### ISSUE TITLE
Custom keybind for opening file/folder isn't loaded until the window has loaded

### ISSUE THREAD

**Issue by ottomated** [microsoft/vscode#102852]
Issue Type: <b>Bug</b>

1. Switch the keyboard shortcuts for `File: Open File...` and `File: Open Folder...` to `Ctrl+K Ctrl+O` and `Ctrl+O` respectively.
2. Open a new window (`Ctrl+Shift+N`).
3. Before the window has loaded (i.e. titlebar text reads "Visual Studio Code" instead of "Untitled-1 - Visual Studio Code"), press `Ctrl+O`.

Actual Result: "Open File" dialog appears

Expected Result: "Open Folder" dialog appears

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-14T00:13:57.513Z)
OS version: Linux x64 5.4.0-40-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 1352)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 2|
|Memory (System)|15.65GB (6.79GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by alexdima** [comment]
@ottomated Do you use the native menu bar or the custom menu bar?

**Comment by ottomated** [comment]
Whichever is the default, I assume native. How would I check?
