### ISSUE TITLE
Newline are not displayed correctly if begin with [ 

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/vscode#102828]
- VSCode Version: 1.47.2
- OS Version: macOS 10.15.5

Steps to Reproduce:

1. We have each 'text' on a newline but when displayed it is not displaying correctly on each line, it displays altogether. (see Images below)

2. To resolve I had to add the \ (only \ no space after) to get the new line to work properly.

Current:
![image](https://user-images.githubusercontent.com/23587151/87831804-1abdc180-c84a-11ea-8cd6-a8ec13b1f160.png)
![image](https://user-images.githubusercontent.com/23587151/87831826-27dab080-c84a-11ea-9257-525cd5930e67.png)

Corrected:
![image](https://user-images.githubusercontent.com/23587151/87831843-36c16300-c84a-11ea-9750-efee899f98f1.png)
![image](https://user-images.githubusercontent.com/23587151/87831853-3a54ea00-c84a-11ea-9fa1-e748df068893.png)

Issue referenced: https://github.com/microsoft/azuredatastudio/issues/11127

**Comment by IllusionMH** [comment]
https://spec.commonmark.org/0.29/#paragraphs

`[1]` has no special meaning therefore treated same as any text.

Render of [soft breaks](https://spec.commonmark.org/0.29/#soft-line-breaks) depends on implementation and can be rendered both ways - `\n` or `<br/>`.
VS Code provides `markdown.preview.breaks` option to control this behavior.

On the other hand [hard breaks](https://spec.commonmark.org/0.29/#hard-line-breaks) (achieved with `\`) - should always be rendered as `<br/>`.
