### ISSUE TITLE
python <filename.py> not responding in terminal

### ISSUE THREAD

**Issue by jaisal1311** [microsoft/vscode#102858]
- VSCode Version: Version: 1.47.2 
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. When python <filename.py> executed on terminal, VS Code is not responding.
2. However, when the file is executed by the green run button on the top right, it is executed successfully.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Are you actually putting < and > either side of your xyz.py filename?

**Comment by jaisal1311** [comment]
Hi John,

Thank you for reverting, I am not using < and > on either side of my
filename.py. I just used them as a placeholder for generalizing the syntax
in the issue.

I tried installing the Software again, and the issue got resolved.

Thank You.
Kind regards.

[image: photo]
Jaisal Shah
Computer science student | University Of Mumbai
A  Mumbai - 64
M  8169764358  <8169764358>
<http://github.com/jaisal1311>
<http://www.linkedin.com/in/jaisal-shah-a427061aa/>
<http://twitter.com/jaisalshah4> <http://www.instagram.com/shah.jaisal/>

You don't have to see the whole staircase. Just take the first step. -
Anonymous
Create your own email signature
<https://www.wisestamp.com/signature-in-email/?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=5783968685359104>
