### ISSUE TITLE
Editing values for variables under WATCH

### ISSUE THREAD

**Issue by xerosugar** [microsoft/vscode#102800]
We have written the needed data into your clipboard because it
Issue Type: <b>Bug</b>

I was testing a web server with node and added some variables I wanted to look at to WATCH, but when I tried to edit their values, I couldn't, which surprised me. Then I tried to edit the same variable under VARIABLES and it worked (the value was updated under WATCH as well). Did you perhaps forget to enable this interaction in the WATCH-panel?

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (23.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
prettify-json|moh|0.0.3
cmake-tools|ms-|1.4.1
gitblame|wad|4.1.0
propertylist|zho|0.0.2

</details>
 was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Probably not available here because you watch expressions, not variables.

**Comment by weinand** [comment]
yes, we do not know whether watch expressions can be assigned to.
