### ISSUE TITLE
Editor context menu lost entries for TS

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10286]
I am not sure how I ended up here but after invoking "Format Code" in a TS file, my editor context menu only shows these entries:

![image](https://cloud.githubusercontent.com/assets/900690/17471084/cbc2cfd4-5d41-11e6-8674-41a377bd47ed.png)

**Comment by bpasero** [comment]
Not reproducible for me after a reload window :-/

**Comment by jrieken** [comment]
No steps, no important ;-)

**Comment by jrieken** [comment]
Can be #10122

**Comment by jrieken** [comment]
just saw this... context looks like this, I am in code editor 3 (tho two visible)

![screen shot 2016-08-08 at 12 41 04](https://cloud.githubusercontent.com/assets/1794099/17477428/8c1bec7a-5d65-11e6-8dbb-05d6bf709ba4.png)

**Comment by bpasero** [comment]
@jrieken can you reproduce this by having 3 editors and closing the CENTER one? In that case editor 3 should move to CENTER and that might be another source of fuck up.

**Comment by bpasero** [comment]
Nevermind, I think that issue about editors moving is solved by my fix 3 weeks ago for always also moving the parent container that holds the context.

**Comment by jrieken** [comment]
closing as duplicate
