### ISSUE TITLE
Tab Highlighting

### ISSUE THREAD

**Issue by KartikM123** [microsoft/vscode#102812]
How can I highlight specific tabs by filepath, both active or not, from an extension using the VSCode extension API? Alternatively,  a way of adding custom file-specific indicators (e.g. dirty file indicator) from an extension would suffice.

For example, I would like some tabs to be highlighted as Purple whether they are active or not, as shown below. 
![image](https://user-images.githubusercontent.com/19193984/87821689-1fbc4a00-c825-11ea-8e13-5b734a11095b.png)

In our use case, we technically would only need to distinguish files provided by a custom file system provider, not the default VS Code file system provider.

**Comment by usernamehw** [comment]
Blocked by #49382 OR (#49382 & #15178)

**Comment by roblourens** [comment]
Thanks @usernamehw!
