### ISSUE TITLE
PowerShell Extension does not start when VSCode is running as admin

### ISSUE THREAD

**Issue by Nu11u5** [microsoft/vscode#102830]
**VS Code:**
Version: 1.47.2 (system setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**PowerShell extension:**
Name: PowerShell
Id: ms-vscode.powershell
Description: (Preview) Develop PowerShell scripts in Visual Studio Code!
Version: 2020.6.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell

**PowerShell Preview extension:**
Name: PowerShell Preview
Id: ms-vscode.powershell-preview
Description: (Preview) Develop PowerShell scripts in Visual Studio Code!
Version: 2020.6.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview

## Steps to Reproduce:

1. Start Code.exe as admin
2. Install "PowerShell" or "PowerShell Preview" extension
3. Create a new PowerShell script file, or open an existing one
4. Observe that the extension does not automatically start and display status bar icon
5. Try to run/debug the PowerShell script file by pressing the F5 key or menu Run > Start Debugging
6. Observe that nothing happens

**Does this issue occur when all extensions are disabled?:** N/A

**Comment by Nu11u5** [comment]
My environment has a separate account for admin privileges.  If I run VSCode under this account without admin elevation the PowerShell extension does start.  It is only when VSCode is started with admin privileges that the issue happens.

**Comment by chrisduda** [comment]
Am having the same issue.  My company requires an elevated administrator account so I have to log into my PC with my non-admin account and run VSC with another account.  1.46, no issues, I have VSC set up to have a powershell terminal session and the powershell extention loads a second session.  When I upgraded to 1.47, only a single powershell terminal will open.  I use the powershell 2020.06 extension and it won't load with 1.47+.  If I try to run a script without debug, I get an error that it couldn't find a debug adapter descriptor for 'powershell'.  Downgrade to 1.46, loads fine with powershell terminal and the powershell extension terminal session.

**Comment by Nu11u5** [comment]
> Downgrade to 1.46, loads fine with powershell terminal and the powershell extension terminal session.

Thanks, I downgraded to 1.46 and can confirm that there is no longer an issue.  The PowerShell extension loads when VSCode is running as admin.

**Comment by Nu11u5** [comment]
I take that back,  It seems like breakpoints do not work on 1.46.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/102642
