### ISSUE TITLE
SourceControlResourceDecorations don't listen to theme style changes

### ISSUE THREAD

**Issue by dcermak** [microsoft/vscode#102818]
- VSCode Version: 1.47.2
- OS Version: openSUSE Tumbleweed

Steps to Reproduce:
1. Create a `SourceControlProvider`, add a `resourceGroup` and add some `resourceStates`
2. add a `dark` and `light` decoration with different icons, e.g.:
```typescript
resourceState.decorations = { 
  dark: { iconPath: "path/to/dark/image.svg" }, 
  light: { iconPath: "path/to/light/image.svg" } 
}
```
3. launch the extension, switch between the light and dark theme and observe that it always uses image from the light theme.

Does this issue occur when all extensions are disabled?: Yes

If I am not mistaken, then the code handling this can be found here: https://github.com/microsoft/vscode/blob/d34560206f1cd95282b62d4bd76873d255619eeb/src/vs/workbench/api/common/extHostSCM.ts#L303
However, when glancing over that, I have absolutely no idea how that can work, as it just pushes the icon paths into an array and **omits** the information whether the icon is for the dark or light theme.

**Comment by joaomoreno** [comment]
cc @jrieken

**Comment by joaomoreno** [comment]
The actual issue here is that the icons do not switch as the theme switches, not that the dark theme never works. If you switch to the dark theme and then reload, it will work.

**Comment by roblourens** [comment]
Beat me by 10 seconds... double verified
