### ISSUE TITLE
showing an error message on compilation

### ISSUE THREAD

**Issue by shuvanshugupta** [microsoft/vscode#102844]
Issue Type: <b>Bug</b>

a file exunc.cpp is used by me, vscode is expected to print something, but it is printing  a message "This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."
please justify this

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.93GB (1.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
prettier-vscode|esb|5.1.3
vscode-gnu-global|jay|0.3.3
python|ms-|2020.6.91350
cpptools|ms-|0.29.0
jinja|who|0.0.8

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This sounds likely to be related to the C++ extension. Please file this issue on the repo for the vscode-cpptools extension:

https://github.com/microsoft/vscode-cpptools/issues

Thanks!
