### ISSUE TITLE
(typo) launch.json config template "Edge: Attach" is named "Attach to Chrome"

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode#102859]
- VSCode Version: 1.47.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open launch.json
2. Select Add Configuration > Edge: Attach

This is what's added:

```json
    {
      "name": "Attach to Chrome",
      "port": 9222,
      "request": "attach",
      "type": "pwa-msedge",
      "webRoot": "${workspaceFolder}"
    },
```

Should be "Attach to Edge". Just a little typo, but possibly confusing to anyone not paying attention when using the templates.

**Comment by israelpgjm** [comment]
[](https://github.com/provenace)

**Comment by connor4312** [comment]
Sorry, missed this issue -- fixed in the latest builds
