### ISSUE TITLE
Color when right click a file

### ISSUE THREAD

**Issue by ProtocolLive** [microsoft/vscode#102893]
Issue Type: <b>Bug</b>

When a file is right clicked, there no selection...
Its confusing...😖

Simple mouse over...
![1](https://user-images.githubusercontent.com/39626142/87874588-5f0fa580-c9a1-11ea-887f-0e611de08c73.jpg)
Right clicked
![2](https://user-images.githubusercontent.com/39626142/87874595-7cdd0a80-c9a1-11ea-821c-85c41779b87f.jpg)
Menu closed
![3](https://user-images.githubusercontent.com/39626142/87874610-8e261700-c9a1-11ea-8e80-dc0e8708a81a.jpg)
Theme used
![4](https://user-images.githubusercontent.com/39626142/87874637-bf064c00-c9a1-11ea-8ddb-c96b5d2fc4f1.jpg)

VS Code version: Code - Insiders 1.48.0-insider (ff6b1c5984a4c2116a06318f07e871a4169fdb1b, 2020-07-17T13:18:36.126Z)
OS version: Windows_NT x64 10.0.20170

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
bracket-pair-colorizer-2|Coe|0.2.0
xml|Dot|2.5.1
toggle-upper-case|epr|0.0.1
html-preview-vscode|tht|0.2.5
vscode-input-sequence|tom|0.2.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This is the "inactive selection" color, since the list does not have focus at this point.
