### ISSUE TITLE
Problems with `Tooltips`!

### ISSUE THREAD

**Issue by rediffusion** [microsoft/vscode#102892]
- VSCode Version:  1.47
- OS Version: Windows 10 2004

 I got problems with 📑 `Tooltips`, please do something!

Steps to Reproduce:

[Screencast](https://www.screencast.com/t/DlPK71QGKgv)

Does this issue occur when all extensions are disabled?: No

**Comment by sbatten** [comment]
we don't draw our own tooltips, seems upstream.

**Comment by rediffusion** [comment]
@sbatten

Aloha! 🙂

I'm so sorry the problem was in another panel which I set. I'm using 📍 «Display Fusion» for multiple monitors.
With «Windows»'s panels no problems!⭐👍
