### ISSUE TITLE
VS Code freezes after killing terminal running Python PyQt5

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#102976]
### THIS IS NOT A PYTHON EXTENSION ISSUE

@adamerose commented on [Fri Jul 17 2020](https://github.com/microsoft/vscode-python/issues/13023)

Issue Type: <b>Bug</b>

Here is a clip of me reproducing this bug
https://www.screencast.com/t/lxwqxamsVDS

In the clip user has used the Python extension to run it, which just sends the command to terminal. But one can just directly type the command without using the extension - and it would still freeze. So this issue is not related to the extension.

I ran into this problem while working on a PyQt5 project but it didn't happen with any other Python scripts, so I managed to take the project file and simplify it down to minimal example that can consistently reproduce this.

```Python
from PyQt5 import QtCore, QtGui, QtWidgets
app = QtWidgets.QApplication([])
app.setWindowIcon(QtGui.QIcon("icon.png"))
window = QtWidgets.QMainWindow()
window.show()
app.exec_()
```

1. Clone this project https://github.com/adamerose/vscode-pyqt-crash
2. Run `main.py` in VS Code. (Using the Python extension or just directly running the command it in terminal)
3. Click the "Kill Terminal" button on the Python process
4. VS Code will freeze

The only extension I have enabled is Python. I disabled hardware acceleration but it didn't make a difference.

Extension version: 2020.7.94776
VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|47.95GB (32.32GB free)|
|Process Argv|C:\_MyFiles\_scratch|
|Screen Reader|no|
|VM|40%|
</details>

**Comment by ArturoDent** [comment]
You should report if this setting:

` "terminal.integrated.windowsEnableConpty": false,`

"fixes" the problem.  Would be useful to know if it is related to similar issues.

**Comment by adamerose** [comment]
> You should report if this setting:
> 
> ` "terminal.integrated.windowsEnableConpty": false,`
> 
> "fixes" the problem. Would be useful to know if it is related to similar issues.

Yes that fixes it

**Comment by ArturoDent** [comment]
Possibly related: https://github.com/microsoft/vscode/issues/76548#event-3057575501
and
https://github.com/microsoft/node-pty/issues/375
