### ISSUE TITLE
Error opening .png file

### ISSUE THREAD

**Issue by Gribesh** [microsoft/vscode#102993]
- VSCode Version: 1.47.1
- OS Version:Ubuntu 20.04 LTS Linux x64 
Steps to Reproduce:

1.
![vscode error](https://user-images.githubusercontent.com/44585698/88023172-4bef0800-cb50-11ea-812d-c0c65a6ea1be.png)

2.

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
So this error only happens when you have extensions enabled?

Can you share the path to the file? Does it contain special characters such as `%` or `#`?

**Comment by Gribesh** [comment]
Enabling or diabling the extensions didn't help but the folder name has special charatcter "#" . I will try removing it and the file once again.

**Comment by Gribesh** [comment]
Reply by : @Gribesh 27-07-2020/21:08
Removing special character (in my case '#' ) solved this problem. Thanks @mjbvz
