### ISSUE TITLE
Debug or Start Error

### ISSUE THREAD

**Issue by Ritm57** [microsoft/vscode#102937]
Issue Type: <b>Bug</b>

C:\Program Files\nodejs\node.exe d:\_tmp\_CarRenta\crm_carrental\app.js
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'c:/Users/������������/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1278:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
Process exited with code 1

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (2.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
beautify|Hoo|1.5.0
regionfolder|map|1.0.11
vscode-language-pack-ru|MS-|1.47.3
material-icon-theme|PKi|4.2.0
vscodeintellicode|Vis|1.2.9

</details>

**Comment by jcampbell1710** [comment]
This started happening to me too with 1.47.2.  Cannot launch test scripts with the same error.

**Comment by Ritm57** [comment]
This is a very serious bug in my opinion. There is no limit to my indignation why to post a non-working update and give people the opportunity to update to a non-working release. Let the developers not be lazy and describe the process of rolling back to the working version of the program. Since I need to work, and not for them to fix bugs and break my head.

**Comment by connor4312** [comment]
@Ritm57 you're facing https://github.com/microsoft/vscode-js-debug/issues/563#issuecomment-659592018

@jcampbell1710 can you collect a trace log using these instructions? Also, you should be able to fix the problem you're facing by adding `nodeVersionHint: 10` to your launch config (we're detecting Node 12 or higher -- or failing to detect Node, but you appear to be running Node 10 or lower). The log file will confirm what's happening.

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

/duplicate

**Comment by Ritm57** [comment]
Excellent work but this configuration does not help in solving the problem. You took and without working on the problem and the fact that you have an error and your software does not recognize the encoding is a big and fat minus. Even more there is a desire to get away from your wretched newproduct. THE PROBLEM IS NOT SOLVED SOLVE IT AND DO NOT PLAY UNSUBSCRIBE!!!

C:\Program Files\nodejs\node.exe d:\_tmp\_CarRenta\crm_carrental\controllers\rl1.js
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'c:/Users/������������/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1278:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
Process exited with code 1

Версия: 1.47.2 (user setup)
Фиксация: 17299e413d5590b14ab0340ea477cdd86ff13daf
Дата: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
ОС: Windows_NT x64 10.0.18363

**Comment by Ritm57** [comment]
@connor4312 This problem is related to the user installer and it does not recognize Russian characters in the path. This is a big and fat minus for you as a specialist who delved into my problem, in the system installers the same trouble if the installation directory is Russian-language. How do you test your versions and roll them out to release in previous versions, there was no such bug. Not developers and do not understand who typed on the ad. I am extremely outraged I demand since this is not an open source project to bring the responsible person who on my question was responsible for negligent attitude to their work and for not knowing the basics of customer support. And if it was a developer, I would have run him down the neck. Who is faced with this problem, we make a system installation in a directory with an English name and will be happy to spend 30 minutes of their time solving other people's errors. The attitude to the product has deteriorated and to the response service, too.

**Comment by connor4312** [comment]
Make sure you follow the complete instructions given in the linked issue (using the nightly and setting attachSimplePort). With those two things, the bootloader will not be injected into your program.
