### ISSUE TITLE
Typescript: Show warning for non-included files in tsconfig.json

### ISSUE THREAD

**Issue by guillaume-humbert** [microsoft/vscode#102981]
When developing a Typescript project, you want to include only certain files for compilation, so you don't include unnecessary files in the final bundle.

Let's say you define a `tsconfig.json` as following:

```
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "target": "ES5"
    },
    "files": ["included.ts"]
}
```

Now if I create another file, say `excluded.ts`, and try to use decorators there, VSCode will show an error saying that `experimentalDecorators` is not enabled.

This is quite problematic in large projects, as you may not realize that the file isn't included in your `tsconfig.json`, and you start looking at the problem elsewhere.

A real use-case where I've seen this happening, is on a large Angular project, where typically you define only `"files": ["main.ts", "polyfills.ts"],`, and when you create a new `.ts` file that is not being referenced by `main.ts`, you get all sort of errors as VSCode tries to compile the file with the `tsc` defaults.

What would be really useful, is that VSCode would not attempt to compile the file (because if you run `tsc` manually, it won't be compiled and not show any error). Instead, it could show a warning such as `This file isn't in scope for compilation according to the settings in tsconfig.json, do you want to include it?`.

**Comment by mjbvz** [comment]
Use the `Typescript: Go to project configuration` command (or click in the TS version in the status bar) to view if the file belongs to any tsconfig or not:

<img width="1220" alt="Screen Shot 2020-07-27 at 2 56 23 PM" src="https://user-images.githubusercontent.com/12821956/88596172-58280900-d019-11ea-89cb-fcedb6178863.png">

Please file a [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) against the TypeScript for the second part about the quick fix  to add the file to the `tsconfig`
