### ISSUE TITLE
Can't copy extension version from the extension page

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#102979]
- Click an extension in the extension viewlet
- Copy the version in the header
- cmd+c
- Paste somewhere - it was not copied.

I can copy other info on the page, but not text in the header

**Comment by sandy081** [comment]
Is this due to new clipboard changes?

**Comment by bpasero** [comment]
I somewhat doubt it, but it does not reproduce in Stable.

@mjbvz @rebornix do you recall any changes to copy/paste in editors during the milestone that could trigger this? Something webview related maybe?

**Comment by sandy081** [comment]
I can reproduce it in latest stable. I cannot copy and paste content in the header part.

**Comment by bpasero** [comment]
Interestingly this works when you select Edit > Copy, but not via keybinding. I don't think any of my changes caused a regression given it works fine from the menu.

@alexdima might also know.

**Comment by bpasero** [comment]
I was able to `git bisect` this back to https://github.com/microsoft/vscode/commit/8e99a2ab7154a5847b09f493e39f5777a03ca33d
