### ISSUE TITLE
Support hiding markdown preview button

### ISSUE THREAD

**Issue by kevinslin** [microsoft/vscode#102908]
The vscode builtin markdown preview shows a menu button whenever the user is looking at a markdown file.  

Other extensions that re-implement markdown preview from scratch via a webview  (eg. https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) also show a menu button for preview which results in a confusing UI. See [here](https://www.evernote.com/l/AA3zORLOet9FGoghhB5cD9VXNFLHX_Kmbtk)

This is a request to support hiding the markdown preview button.

**Comment by mjbvz** [comment]
I don't think an extension can reasonably hide its individual icons with current APIs, so closing this in favor of the more general solution tracked by #46403
