### ISSUE TITLE
Lost Anguar code

### ISSUE THREAD

**Issue by rounak48** [microsoft/vscode#102994]
Issue Type: <b>Bug</b>

I had a project of Angular and had multiple lines of code and components under it. When I opened the project after few weeks I see that all the codes and components as well as the ts files are lost. The build code is still present in the dist folder. But the actual source code is the initial code that you get when you start an Angular project from scratch. Can you please let me know why and how did this happen as now I have to write my whole code again.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (4.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
vscode-docker|ms-|1.3.1
autoimport|ste|1.5.3

</details>

**Comment by joaomoreno** [comment]
How do you know VS Code was responsible for the code gone missing? Could any other tool have deleted it? Did this happen with any other folder in your system?
