### ISSUE TITLE
Launch the app via open cmd on macOS

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#102975]
Currently some users hit an issue where the app launched from command line doesn't have an active dock icon, menu and the window cannot be focused.

Thanks for help from @MarshallOfSound  with the debugging we were able to narrow the source of issue. The cli wrapper is a node process which then spawns the actual app https://github.com/microsoft/vscode/blob/master/src/vs/code/node/cli.ts#L331 , this doesn't work well with entitlements. Can read for some background about inherited entitlements https://github.com/microsoft/vscode/issues/95062#issuecomment-625553211 .

The underlying issue is not known here but we expect some sort of malformed state has been entered by the entitled app. To fix this we can adjust the spawn callsite with a call to macOS `open` cmd.

**Comment by bpasero** [comment]
@deepak1556 we have to be careful to still support our command line flags. Here is a simple test that fails if we switch to `open`:
* run `alias code='open -b com.microsoft.VSCode "$@"'` in terminal
* type `code --list-extensions`
* it fails

See also some related discussion in https://github.com/microsoft/vscode/issues/60579

//cc @joaomoreno

**Comment by deepak1556** [comment]
@bpasero the open command is only meant to be used for spawning the final app executable https://github.com/microsoft/vscode/blob/master/src/vs/code/node/cli.ts#L331, it is not meant to replace the cli  wrapper which respects those command line arguments.

`const child = spawn('open', ['-b', 'com.microsoft.VSCode', '--args', argv], options);`

**Comment by bpasero** [comment]
@deepak1556 oh I see!

**Comment by joaomoreno** [comment]
LGTM!

**Comment by deepak1556** [comment]
Thanks @segevfiner , definitely is related to this issue.

**Comment by memeplex** [comment]
Will this work with the `--wait` flag? Currently launching code with that flag produces not only recent icon duplicates but also duplicated icons in the app switcher (https://github.com/microsoft/vscode/issues/112782). Neither `open -b com.microsoft.VSCode --wait` nor `open -W -b com.microsoft.VSCode --wait` work properly (even when the editor is closed, the command at the CLI keeps waiting).
