### ISSUE TITLE
integrated terminal does not work

### ISSUE THREAD

**Issue by quantitative-technologies** [microsoft/vscode#102907]
Issue Type: <b>Bug</b>

When I open my python project, which was previously working, the terminal is no longer working. There is just a white cursor. I cannot enter any text.

This means I cannot for example use VS code for debugging.

I have tried the settings

"terminal.integrated.shell.linux": "/usr/bin/bash",
"terminal.integrated.automationShell.linux": "/usr/bin/bash"

but this makes no difference.

Please help.

Note: Remote OS version is listed below. However, this project is local. This problem does not exist when running remotely, btw.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 5.4.0-7634-generic
Remote OS version: Linux x64 5.3.0-1030-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4381)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|62.77GB (1.35GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: ec2-54-82-194-7.compute-1.amazonaws.com|
|OS|Linux x64 5.3.0-1030-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (8 x 3237)|
|Memory (System)|30.91GB (26.28GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
csharp|ms-|1.22.1
vscode-postgresql|ms-|0.3.0
python|ms-|2020.7.94776
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.29.0

</details>

**Comment by quantitative-technologies** [comment]
Very strange: I noticed that the  problem goes away when I run `code` from a bash terminal. The problem happens when I click the code icon on the desktop. 

I guess there is some issue with environment variable, but do you know specifically what might cause this?

**Comment by bkbartonDesign** [comment]
I am having a similar issue. When I open the terminal, the window 'self scrolls' to the bottom and in order for me to see the terminal prompt, i must scroll up. When I try to input a prompt, the keystroke forces the terminal window to 'self scroll' to the bottom, once more. My input prompt is not respected.


VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.4
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.2
vs-color-picker|lih|1.0.0
git-graph|mhu|1.24.0
csharp|ms-|1.22.1
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
angular-console|nrw|12.0.0
material-icon-theme|PKi|4.2.0
addDocComments|ste|0.0.8
vscodeintellicode|Vis|1.2.9
vscode-todo-highlight|way|1.0.4
primengsnippets|yig|1.0.5

**Comment by Tyriar** [comment]
Can you capture a trace log of the good case and the bad case and diff the environment variables? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

My guess is your .bashrc (via `code` cli) has some required setup that your .bash_profile (via icon) does not.

**Comment by jamespero** [comment]
I'm also seeing this behavior on a clean install of the latest version of VS Code on Windows 10.

I looked through the trace logs but saw no indicators other than the terminal being set to powershell and no errors of any kind were visible. I'm not at liberty to attach the log without redacting due to client restrictions.

**Comment by BenjamNathan** [comment]
I am also seeing this on bash terminals on Windows with versions above Git-2.26.2. The first terminal opens OK. The rest scroll to the bottom and don't allow text input.

**Comment by Tyriar** [comment]
Closing due to lack of info from OP. Note that if you're on Windows, you're likely seeing a different issue.
