### ISSUE TITLE
Enabled extension list refresh

### ISSUE THREAD

**Issue by jomarko** [microsoft/vscode#102995]
- VSCode Version: 1.46.1
- OS Version: Fedora

Steps to Reproduce:

1. Find any uninstalled extension on market place
2. Keep screen for its installation open
3. In the extensions panel list all enabled extensions
4. Click install button for the extension found in first step
5. The extension is usually successfully installed without prompting user to reload VS Code, however the list of enabled extensions in the extensions panel was not refreshed and the last installed extension is not listed
6. If VS Code is restarted/reloaded, the extension is listed correctly as enabled

The same holds true for uninstall phase. Without reloading whole VS Code the extensions panel can be in inaccurate state.
Either all extensions should ask user to reload VS Code once installed/uninstalled or the extensions panel should be refreshed automatically. 

Does this issue occur when all extensions are disabled?: No, related to extensions

**Comment by jomarko** [comment]
@sandy081 hello, could you please link the issue to track progress on solving?
This was closed as duplicate, however I can not see any referencing number.

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/68584
