### ISSUE TITLE
Breakpoints jump to incorrect line when using new preview Javascript Debugger

### ISSUE THREAD

**Issue by sceee** [microsoft/vscode#102923]
Issue Type: <b>Bug</b>

I am experiencing a weird debugger behavior in the latest VS Code Versions.
When using the preview Javascript debugger (which is activated by default - the regular default preview, without having the Nightly extension installed), Breakpoints set towards the end in longer (~400 lines of Code) files (= Breakpoint in l419 in a file with 425l of Code) jump to another location in the same file (e.g. l368).

It's a TS project using babel to transpile and generate the sourcemaps. I can confirm the sourcemaps are correct as disabling the preview JS Debugger causes the Debugger to work as expected.

Also, even though the red bubble jumped to l368
![image](https://user-images.githubusercontent.com/11340487/87914443-eaa43780-ca70-11ea-8b28-861af6715820.png)
the "original" location of the breakpoint still hits sometimes and breaks but without displaying the red bubble:
![image](https://user-images.githubusercontent.com/11340487/87914411-dfe9a280-ca70-11ea-9032-434433b5f737.png)

But that's not always the case, it kind of depends on the line number.
A breakpoint in l419 (at the for of loop, the first line in the following code)
```
for (const x of y) {
}
```
lets the breakpoint jump to l368 when being set whereas a breakpoint in l418
```
let abc = 0;
```
stays there correctly.

Disabling the preview debugger makes both breakpoints work as expected.
Installing the latest Nightly Extension of the new Javascript Debugger does not solve the problem.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

**Comment by connor4312** [comment]
Thanks for the issue. Can you either collect a trace log using these instructions, or provide a reproduction case for what you're hitting?

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by sceee** [comment]
@connor4312 I emailed you trace logs.

**Comment by connor4312** [comment]
Thanks @sceee. I think what's happening: babel-node compiles in-process, but js-debug also will try to scan the workspace for sourcemaps. It looks like you have compiled files in your `dist` folder, but you also compile it (again?) at runtime to get a second set of files with sourcemaps. There are two sets of sourcemaps, those and those at runtime. Two things that may work:

1. Maybe this setup is unintentional -- did you mean to run the source code instead with babel-node, or use normal `node` to execute the compiled files?
1. You can probably fix the weirdness by setting `outFiles: []` in your launch.json so that we don't scan for sourcemaps anywhere on disk.

**Comment by sceee** [comment]
Thank you @connor4312, that's a good hint.
I switched to proposal 1 (compile first, then debug "regular" JS) and it seems to be working now as intended using the new JS debugger.
