### ISSUE TITLE
Add ability for plugins to annotate code with computed stuff like references, author, code coverage etc.

### ISSUE THREAD

**Issue by bluemmc** [Microsoft/vscode#10290]
I would like to be able to create a plugin that shows extra computed information like function callers, author of last change to function, code coverage etc. Sometimes this should insert extra pseudo-lines of meta-information above functions like in visual studio 2015, sometimes it should cause the individual lines to be colored differently (useful to specify code coverage).

**Comment by jrieken** [comment]
The editor supports this as code lens: https://code.visualstudio.com/docs/editor/editingevolved#_reference-information. In the API we have exposed it as [CodeLensProvider](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1516). A sample that uses this API is [C#](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/codeLensProvider.ts)

**Comment by bluemmc** [comment]
@jrieken Thanks for the info about CodeLensProvider. What if I want to re-color background of lines in the editor depending on external data such as code coverage etc. ? I.e. essentially overwrite the coloring of existing plugins for various languages ?

**Comment by jrieken** [comment]
You would use editor [decorations](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3255) for that. A sample that uses decorations is here: https://github.com/Microsoft/vscode-extension-samples/tree/master/decorator-sample
