### ISSUE TITLE
Allow to set and save your editor window size at startup

### ISSUE THREAD

**Issue by Leonid74** [microsoft/vscode#102957]
Issue Type: <b>Feature Request</b>

Крайне не хватает возможности установить и сохранить свой размер окна редактора при запуске

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

**Comment by fearintino** [comment]
Translate is: Extremely missing the ability to set and save your editor window size at startup

**Comment by Leonid74** [comment]
> Translate is: Extremely missing the ability to set and save your editor window size at startup

yeah, that is right

**Comment by Leonid74** [comment]
Thank you! Will wait fo upvotes

**Comment by fearintino** [comment]
@Leonid74 а как ты видишь для себя эту фичу?
