### ISSUE TITLE
Debug start button gets hidden when the sidebar is too narrow

### ISSUE THREAD

**Issue by takumif** [Microsoft/vscode#1029]
![screen shot 2015-12-04 at 4 49 19 pm](https://cloud.githubusercontent.com/assets/5505433/11602718/71c4909e-9aaa-11e5-9808-04e1db48f10d.png)

When the sidebar is at its narrowest allowed width, the green start button gets hidden, and there is nothing that indicates that it's hidden. This is especially confusing when you've opened the debug view for the first time.

**Comment by isidorn** [comment]
@bpasero I would like to be able to specify minimum viewlet width. I do not think something like this is possible at the moment, right?

**Comment by bpasero** [comment]
@isidorn no it is hardcoded in the layout code today.

**Comment by isidorn** [comment]
@bpasero please review, now I am using flex for action bar in composite title. I checked all the viewlets and panels and all looks good

**Comment by bpasero** [comment]
:100:
