### ISSUE TITLE
Indentation Problem

### ISSUE THREAD

**Issue by llTheBlankll** [microsoft/vscode#102941]
Issue Type: <b>Bug</b>

| is the cursor

I open up my VS Code and type div and press enter but the result is

<div>
|</div>

I want this
<div>
    |
</div>

Why?

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Load (avg)|undefined|
|Memory (System)|3.92GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.1.4
php-intellisense|fel|2.3.14
beautify|Hoo|1.5.0
material-icon-theme|PKi|4.2.0
html5-boilerplate|sid|1.0.3
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
you can turn off auto indent `"editor.autoIndent": "none"`.
