### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by epiqu1n** [microsoft/vscode#102922]
Issue Type: <b>Feature Request</b>

This is not a feature request but rather general praise; couldn't find a more appropriate avenue for it though.  I just want to say as an amateur web developer how much I love VSC.  I had used Eclipse for years contentedly and now I wouldn't consider for a moment going back to it.   The interface of VSC is beautiful and clean, the settings are relatively easy to customize considering how much you can change, and the combination of JSDoc support and Intellisense makes coding so, *so* much easier.

Thanks so much for making this and keeping it free.

VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.19041

**Comment by mjbvz** [comment]
Thanks!
