### ISSUE TITLE
Allow language extensions to override editor.wordSeparators

### ISSUE THREAD

**Issue by eric-wieser** [microsoft/vscode#102942]
Continues from gh-33701:

> There's a pretty common request from PowerShell extension users to enable double-click selection of variable names like `$myVar` including the initial dollar sign character. After some research it seems that the only way to control this double-click selection behavior is by having the user change their `editor.wordSeparators` setting to remove the `$` which is included by default.

In that issue, [it was shown that a user can configure this manually](https://github.com/microsoft/vscode/issues/33701#issuecomment-469491567) as:

```json
{
    "[powershell]": {
        "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
    }
}
```
However, this does not address the original question of what _language extensions_ should do.

How can / should a language extension provide a default value for a setting within a `"[mylanguage]"` key?

**Comment by manoutoftime** [comment]
@eric-wieser would this do?

https://code.visualstudio.com/api/references/contribution-points#contributes.configurationDefaults
```json
{
    "contributes": {
        "configurationDefaults": {
            "[powershell]": {
                "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
            }
        }
    }
}
```

**Comment by aeschli** [comment]
@eric-wieser You need to add `$` to the powershell word-pattern in the language-configuration: https://code.visualstudio.com/api/language-extensions/language-configuration-guide#word-pattern
