### ISSUE TITLE
Request for bootstrap from source documentation

### ISSUE THREAD

**Issue by ericherman** [microsoft/vscode#102996]
Source-based distribution creators, users of Linux From Scratch, and others interested in bootstrapping would appreciate more clear documentation on how to bootstrap an initial build of Visual Studio Code.

See also: https://bootstrappable.org/best-practices.html

**Comment by IllusionMH** [comment]
There is documentation how to run it locally:
https://github.com/Microsoft/vscode/wiki/How-to-Contribute#prerequisites
https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run
https://github.com/Microsoft/vscode/wiki/How-to-Contribute#packaging

Is something missing there?

**Comment by ericherman** [comment]
When I walked through the steps this morning, the install dependencies immediately failed with:

```
~/src/vscode$ yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
```

Perhaps I missed something. I can try to look deeper, perhaps this evening.

**Comment by joaomoreno** [comment]
https://github.com/yarnpkg/yarn/issues/2821
