### ISSUE TITLE
VSCode asks for permission to use ESLint every single time I open it

### ISSUE THREAD

**Issue by kaitlynbrown** [microsoft/vscode#102972]
- VSCode Version: 1.47.1
- OS Version: Windows 10 v1903 build 18362.959

Steps to Reproduce:

1. Create a node.js project
2. Install eslint via npm
3. Ensure ESLint extension is installed and enabled
4. If VSCode is open, exit it.
5. Run VSCode and open the project you created

Result:
![image](https://user-images.githubusercontent.com/1388240/87973266-14635b80-ca7d-11ea-95e1-31b19c2959ca.png)

This pop-up appears *every single* time I open VSCode. It has been happening since VSCode was last updated, therefore it seems to be an issue with VSCode and not the extension.

I shouldn't have to give permission for VSCode to use ESLint at all, let alone every single time I open the program.

Does this issue occur when all extensions are disabled?: N/A

**Comment by MarMun** [comment]
Same here. Any insights?

Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-14T00:13:57.513Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-40-generic (Ubuntu 20.04 LTS)

**Comment by MarMun** [comment]
I just realize this is a [duplicate](https://github.com/microsoft/vscode-eslint/issues/1012)
