### ISSUE TITLE
Some selection and deletion keybindings do not work in refactor popup

### ISSUE THREAD

**Issue by jbree** [microsoft/vscode#102965]
- VSCode Version: 1.47.2
- OS Version: Windows 10

Steps to Reproduce:

1. Press `F2` while cursor is on a symbol name to open "Refactor" popup
2. Use keybindings for actions such as `deleteWordPartLeft` or `cursorWordPartRightSelect`.
3. Instead of affecting the text in the popup, these keyboard shortcuts affect the source code at the original cursor position

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Arename

**Comment by jbree** [comment]
For future reference, this duplicates #53666
