### ISSUE TITLE
Extensions: Offer the user the ability to disable all dependencies when disabling an extension with dependents

### ISSUE THREAD

**Issue by avi10malhotra** [microsoft/vscode#102906]
Issue Type: <b>Bug</b>

Cannot activate the 'GitHub' extension because it depends on the 'Git' extension, which is disabled. Would you like to enable the extension and reload the window?

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2701)|
|Memory (System)|3.90GB (0.42GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
project-manager|ale|11.1.0
code-gnu-global|aus|0.2.2
gitignore|cod|0.6.0
git-extension-pack|don|0.1.3
githistory|don|0.6.8
gitlens|eam|10.2.2
code-runner|for|0.11.0
terminal|for|0.0.10
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.7.94776
cpptools|ms-|0.29.0
vscode-yaml|red|0.9.1
vscode-open-in-github|ziy|1.3.6
project-manager|ale|11.1.0
theme-monokai-pro-vscode|mon|1.1.17
remote-wsl|ms-|0.44.4
vscode-icons|vsc|10.2.0
material-theme|zhu|3.8.4

(9 theme extensions excluded)

</details>

**Comment by avi10malhotra** [comment]
Edit: The git-extension-pack and all other git related extensions have been uninstalled.

**Comment by heygrain** [comment]
same issue
vscode version: 1.47.2
os version: macos 10.15.6
remote os version: debian 8
And when I roll back to 1.47.1 everything is fine.

**Comment by joaomoreno** [comment]
@sandy081 This is what I see when I try to disable `Git`:

![image](https://user-images.githubusercontent.com/22350/88155602-8f0cb200-cc08-11ea-9af0-e002f9ea2e67.png)

Should we instead offer the opportunity for the user to still disable the entire dependency chain, in that notification? Something like `Do you want to disable all these extensions?`.

**Comment by avi10malhotra** [comment]
![image](https://user-images.githubusercontent.com/28999322/88157976-12d69680-cc29-11ea-98d2-80dfa3612329.png)

^This is exactly what it says for me whenever I open VScode. However, when I open it without my WSL: Ubuntu remote, it doesn't show this error...

**Comment by sandy081** [comment]
> Should we instead offer the opportunity for the user to still disable the entire dependency chain, in that notification? Something like Do you want to disable all these extensions?.

Yeah makes sense.

**Comment by joaomoreno** [comment]
@avi10malhotra For now, enable the Git extension. Then, if you still want git features to stay disabled, set the `git.enabled = false` setting.

**Comment by sandy081** [comment]
Install `Git Blame` extension and try to disable `Git` extension and you will get following message. `Disable All` action will disable Git and all its dependencies.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/10746682/98855805-e86d4b00-245c-11eb-8d4f-bb12876bd549.png">
