### ISSUE TITLE
Can't Install User and System Visual Studio Code

### ISSUE THREAD

**Issue by 2D43** [microsoft/vscode#102904]
- VSCode Version: 1.47
- OS Version: Windows 10

Steps to Reproduce:

1. I tried to install, like Administrator (Right Click / Run as Administrator) and like User (only double click)
2. In both situations I have the same result.

![Iss_Inst](https://user-images.githubusercontent.com/5728054/87881757-fa644300-c9c0-11ea-861c-3e6427f46fa9.PNG)

I have administrator role, on my lap. Please any help.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by 2D43** [comment]
I tried, in another pc and I had no problems, I could vscode.

**Comment by joaomoreno** [comment]
Please delete the installation folder and try again, simply by just double clicking the setup.

**Comment by 2D43** [comment]
Thank you. :)
