### ISSUE TITLE
Webview errors when resizing the window

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#102969]
Issue Type: <b>Bug</b>

* Open a github issue notebook
* Resize the window

```
Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at WebviewMainService.registerWebview (vscode/out/vs/platform/webview/electron-main/webviewMainService.js:26:167)
 
```

VS Code version: Code - OSS Dev 1.48.0 (Commit unknown, Date unknown)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.08GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|8%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
dotnet-interactive-vscode|ms-|1.0.136501
vscode-dotnet-runtime|ms-|0.1.2
vscode-markdown-notebook|ms-|0.0.10

</details>

**Comment by mjbvz** [comment]
I just tried this with a GitHub issues notebook. Rapidly resizing the VS Code window did not trigger this error

Let me know if you are still seeing this issue.
