### ISSUE TITLE
Tabs disappear when opening an Untitled new file

### ISSUE THREAD

**Issue by Dragory** [Microsoft/vscode#10292]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Open an Untitled file with File -> New File
2. Tabs disappear

Screenshots:

Before
![tabs_before](https://cloud.githubusercontent.com/assets/2606411/17474774/706abf56-5d60-11e6-8eac-5b66c6bf3009.png)

After
![tabs_after](https://cloud.githubusercontent.com/assets/2606411/17474773/706473c6-5d60-11e6-81a8-d70090c5a119.png)

Errors in console:

![tabs_errors](https://cloud.githubusercontent.com/assets/2606411/17474845/c09248fa-5d60-11e6-91bd-6feb36c215f7.png)

**Comment by glen-84** [comment]
Does it happen with the `vscode-icons` extension disabled?

**Comment by Dragory** [comment]
Disabling the extension completely didn't fix it (I had tried running with `--disable-extensions` earlier), but running the extension's `Icons Disable` command did. Thanks!

**Comment by robertohuertasm** [comment]
@Dragory Check [issue 10299](https://github.com/Microsoft/vscode/issues/10299)
This has been already solved in [#153](https://github.com/robertohuertasm/vscode-icons/issues/153#issuecomment-238259419)
