### ISSUE TITLE
Hover Messages are not shown when debugging

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#102939]
- VSCode Version: 1.46
- OS Version: Win 10

# Steps to Reproduce:

1. Launch VS Code & Install Git Lens
2. Hover over a git blame decoration (details are shown in a hover message)
3. Start Debugging
4. Hover over a git blame decoration (no hover message is shown)

# Expected Behaviour

a) Either hover messages are shown even when debugging
b) Or the docs of hover messages read that hover messages aren't shown when debugging

In the case this issue is resolved to b), a) would be a feature request.

# Background

This is related to #47466.

The docs say this about `hoverMessage`:
![image](https://user-images.githubusercontent.com/2931520/87927530-a40c0880-ca83-11ea-8381-bb5add8311de.png)
(A message that should be rendered when hovering over the decoration.)

I want to implement a hover message in a custom extension that enriches the debugging experience.
The decoration with the hover message is only set by my extension when the VS Code instance is debugging.

Since (as reported with this issue) VS Code does not show any hover messages when debugging, the observed behaviour was that hover messages don't work at all. It took me some time to realize that they do work, but not when in debug mode. This behaviour is not documented anywhere.

**Comment by weinand** [comment]
When debugging, the debugger's hover messages take precedence.
VS Code does not merge debugger hovers with other hovers.

**Comment by hediet** [comment]
Please update the docs at least if this issue does not get that many upvotes!

I wasted at least an hour with implementing stuff that does not make sense anymore since there is no way to call it. A link in a hover messages would have been my approach to trigger the heavily parametrized command.

**Comment by hediet** [comment]
Btw. this issue makes it very hard to understand errors squiggles while debugging, as no error message is shown when you hover over it:

![image](https://user-images.githubusercontent.com/2931520/88288906-b476ea00-ccf4-11ea-831b-ab3114eb6e09.png)
