### ISSUE TITLE
I need a new feature

### ISSUE THREAD

**Issue by xubin727** [microsoft/vscode#102960]
Issue Type: <b>Feature Request</b>

I need a new feature, like the eclipse's CTR+H

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

**Comment by heartacker** [comment]
你在说啥

**Comment by joaomoreno** [comment]
Can you describe such a feature?
