### ISSUE TITLE
Keybinding watch expression for NOT not working

### ISSUE THREAD

**Issue by Aminadav** [microsoft/vscode#102921]
- VSCode Version: 1.47.2
- OS Version: Mac Catallina

Steps to Reproduce:

I'm trying that when pressing CMD+SHIFT+R it will open the source control.
But if I'm in the search editor to search again.
I have two key bindings. but it always switch to source control, even when I'm in the search editor.

![image](https://user-images.githubusercontent.com/3584317/87913714-36a6aa80-ca78-11ea-9c95-47fdb7221f47.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Could you check if you can reproduce this in Insiders build? https://code.visualstudio.com/insiders/

Unable to reproduce this in Insiders build, but on Windows.

**Comment by JacksonKearl** [comment]
I expect `inSearchEditor` to be true if the focus is inside a search editor, and false otherwise. That seems to be consistent with what I'm seeing testing out in 1.47.2 on MacOS just now. Could you share what you expect and what you're seeing? /gifPlease
