### ISSUE TITLE
Extensions stored in iCloud Drive sometimes break

### ISSUE THREAD

**Issue by rgov** [microsoft/vscode#102971]
Issue Type: <b>Bug</b>

I have my VS Code extensions folder on iCloud Drive so that it syncs between my two Macs. Sometimes macOS seems to clear its local cached copy and this breaks VS Code.

This may not be a configuration that VS Code wants to support but perhaps it should warn if it detects you have done this (ditto for Dropbox or OneDrive or whatever).

To work around, open the extensions folder and click the "cloud download" icon next to each extension that has been offloaded.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0
Remote OS version: Linux x64 4.15.0-111-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 9, 9|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|14%|

|Item|Value|
|---|---|
|Remote|SSH: lrauv-vm.local|
|OS|Linux x64 4.15.0-111-generic|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (2 x 3502)|
|Memory (System)|3.83GB (1.93GB free)|
|VM|100%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
vscode-dash|dee|2.4.0
nc-gcode|ML|0.13.0
vscode-docker|ms-|1.3.1
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.9

</details>

**Comment by Crazykado-iphone8MacProOs** [comment]
$sudo.install.sudo.bin.sh/hash.sh

**Comment by Crazykado-iphone8MacProOs** [comment]
$sudo.install.sudo.bin.sh/hash.sh

**Comment by roblourens** [comment]
I don't think we have control over macOS here, but I recommend using settings sync to do this sort of thing instead: https://code.visualstudio.com/updates/v1_47#_settings-sync
