### ISSUE TITLE
vscode popup alert version 1.47.1

### ISSUE THREAD

**Issue by Panchalkishan** [microsoft/vscode#102940]
hi all,

![image](https://user-images.githubusercontent.com/38061833/87929143-96667b00-caa3-11ea-83c1-93c14640e795.png)

i am facing issue with current version of vs code.
![image](https://user-images.githubusercontent.com/38061833/87929297-d88fbc80-caa3-11ea-954a-07a9c0dd37e8.png)

this is continuously showing popup message after every 50 to 45 min.. i have attached snapshot for your reference please do the needful and fix this issue.

**Comment by gjsjohnmurray** [comment]
The current release is now 1.47.2, and 1 1.47.3 security update is imminent.

I suggest you restart Windows, then launch VS Code. Watch the gearwheel icon on the lower left. If it doesn't indicate it's started updating, right-click and choose to update.

**Comment by Panchalkishan** [comment]
@gjsjohnmurray  thanks it works.. 👍

**Comment by gjsjohnmurray** [comment]
@Panchalkishan that's good to hear. Please close the issue.
