### ISSUE TITLE
Saving a file takes Insance amount of time (never saves).

### ISSUE THREAD

**Issue by vickylance** [microsoft/vscode#102956]
Issue Type: <b>Performance Issue</b>

I use Go Extension and I have a huge Go lang project repo ~1500+ files I think. Any time I modify a file and save it I see this popup with this text "Saving 'filename.go': Getting code actions from "Go"" and its just loads indefinitely to save the file but it never saves the file

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   131	  1632	code main
   15	    82	  1678	   gpu-process
    0	    33	  1699	   utility
    0	    98	  1718	   shared-process
    0	     0	  5800	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
   18	   557	  2889	   window (insurance_service.go — wealth-api)
    0	   492	  2894	     extensionHost
    0	    82	  2902	       electron_node serverMain.js 
    0	    82	  2904	       electron_node server.js 
    0	   279	  2906	       electron_node server.js 
    0	  1163	  2965	       /Users/vickylance/go/bin/gopls -mode=stdio
    0	    16	  5776	         go list -e -json -compiled=true -test=true -export=false -deps=true -find=false -- /Users/vickylance/go/src/api/.gopath/pkg/mod/gopkg.in/goracle.v2@v2.24.1/conn_test.go
    0	     0	  5808	         (go)
    0	    66	  4671	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=2894
    0	    49	  2895	     watcherService
    0	    33	  2903	     searchService
    0	    82	  5763	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (service.go — api)
|    Folder (api): more than 20349 files
|      File types: go(11847) mod(422) md(311) lock(272) s(263) dat(172)
|                  json(166) zip(153) golden(153) gitignore(117)
|      Conf files: makefile(27) package.json(3) launch.json(2) tasks.json(2)
|                  tsconfig.json(2) tslint.json(2) gulp.js(1)
|      Launch Configs: go;
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
es7-react-js-snippets|dsz|2.8.2
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
vscode-go-test-adapter|eth|0.1.3
vscode-jest-runner|fir|0.4.22
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
go|gol|0.15.1
vscode-test-explorer|hbe|2.19.1
vscode-import-formatter|hen|0.1.8
vscode-styled-components|jpo|0.0.29
vscode-colorize|kam|0.8.17
vscode-react-native|msj|0.16.1
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.2.0
gotestexplorer|pre|0.1.11
vscode-yaml|red|0.9.1
partial-diff|ryu|1.4.1
code-spell-checker|str|1.9.0
vscode-stylelint|sty|0.84.0
errorlens|use|3.1.1
highlight-matching-tag|vin|0.9.9

(1 theme extensions excluded)

</details>

**Comment by ronilaukkarinen** [comment]
Getting the same when saving SCSS... have been monitoring logs and disabled extensions but have not figured out what's causing this. This problem did not occur before the two of the latest updates.

Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

![Screenshot](https://i.imgur.com/YNmR0gj.png)

**Comment by vickylance** [comment]
Anyone any update on this?

**Comment by heemoe** [comment]
related issues
https://github.com/microsoft/vscode-eslint/issues/999#issuecomment-669762238

**Comment by jrieken** [comment]
> Getting code actions from "Go"

⬆️ It's likely the go extension and that you have configured to run code actions before saving. So, please follow up with the go extension authors.
