### ISSUE TITLE
No colorisation for ellipse tag in Sass

### ISSUE THREAD

**Issue by bastienmoulia** [Microsoft/vscode#10295]
- VSCode Version: 1.4.0
- OS Version: Win 7

Steps to Reproduce:

1. Create a new file
2. Use the Sass colorisation
3. Write `svg circle, svg ellipse { stroke: red; }`
4. The `ellipse` tag is not well colorised

![ellipse](https://cloud.githubusercontent.com/assets/686196/17479477/05c27cc6-5d73-11e6-9434-0d5505dde9a1.png)

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#162
