### ISSUE TITLE
code opens window by using the window dimension of the last code invocation

### ISSUE THREAD

**Issue by lauatic** [microsoft/vscode#102986]
- VSCode Version:
$ code --version 
1.47.1
485c41f9460bdb830c4da12c102daff275415b53
x64

- OS Version:
Ubuntu 18.04.4 LTS

Steps to Reproduce:

I searched and found this issue https://github.com/microsoft/vscode/issues/24227 and it did not help me with what I wanted to do.
1. Invoke `code <folder>` and the window is opened in maximized mode.  I click the minimize on the top right and resize the window to my need.
2. When I'm done with code, I exit code with ctrl-Q.
3. When I invoke `code <folder>` again, code opens the window in maximized mode again and I have to resize the window.  I was hoping that code could remember the dimension that I used last and opens the window with that dimension.
4. Is there a setting in settings.json that I can set to tell code to remember.

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
I cannot reproduce this behaviour.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by lauatic** [comment]
I did not find the time to try the insider builds.
Yesterday, all of a sudden, code can remember the previous dimension setting I used.  After few `code <folder>` calls, code stopped remembering and opens windows in maximized mode again.
