### ISSUE TITLE
"Format Code" causes tslint failure with type assertions

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#10296]
_From @LOZORD on August 5, 2016 3:14_

If I have code like this:

``` ts
const bar = <Bar> Thing.getFoo();
```

and then "Format Code" (alt-shift-F on Mac), I get this:

``` ts
const bar = <Bar>Thing.getFoo();
```

The missing space after the closing angled bracket causes a spacing failure with tslint. I removed the settings in my `.vscode/settings.json` that have to do with JS/TS spacing, and the error still occurred. Is there something else I can configure to solve this?

_Copied from original issue: Microsoft/vscode-tslint#69_

**Comment by egamma** [comment]
Format Code is provided by `vscode`. Moving the issue to vscode.

**Comment by dbaeumer** [comment]
@egamma the error @LOZORD complains about comes from tslint. I am not sure what VS Code should do about this expect filing a feature request to TS to support an option to have a space after a cast operator.

**Comment by LOZORD** [comment]
I guess the easiest fix might just be to _not_ include the `check-typecast` rule under [`whitespace`](http://palantir.github.io/tslint/rules/whitespace/) in `tslint.json` 😕

**Comment by egamma** [comment]
@dbaeumer agreed, this is really a feature request for the TS formatter to support an option to have a space after a cast operator.

**Comment by LOZORD** [comment]
So how should I/we proceed?

**Comment by dbaeumer** [comment]
@LOZORD best is to open a feature request for the formatter here: https://github.com/Microsoft/typescript

**Comment by csentis** [comment]
Could someone please let me know how to activate this in vscode? I do not get the expected results when putting this into my settings:
```
"typescript.format.insertSpaceAfterTypeAssertion": true
```

**Comment by dbaeumer** [comment]
@mjbvz is this support already. Looks like TS merged a PR for this but we don't have a setting for this yet in VS Code.

**Comment by mjbvz** [comment]
This formatting option doesn't seem to be in the TSServer protocol yet. Adding it is being tracked by https://github.com/Microsoft/TypeScript/issues/14661

**Comment by lucap86** [comment]
a quickFix as we wait for feature additions 

clone typescript repo in ad folder i call it FOLDER
than add 
```
insertSpaceAfterTypeAssertion: true,
```
in FOLDER/lib/tsserver.js at line 68794
than in vscode settings
```
"typescript.format.insertSpaceAfterTypeAssertion": true,
"typescript.tsdk": "PATH_TO_FOLDER/lib/",
```

**Comment by mjbvz** [comment]
This should be in TS 2.4: https://github.com/Microsoft/TypeScript/issues/14661

Added to the June plan

**Comment by csentis** [comment]
@mjbvz if I read the [June Iteration Plan](https://github.com/Microsoft/vscode/issues/28387) properly, this has been deferred. Can you correct me?

**Comment by mjbvz** [comment]
@csentis Thanks for the reminder. This should be in for June with TS 2.4

**Comment by csentis** [comment]
@mjbvz Thank YOU

**Comment by roblourens** [comment]
@mjbvz with TS 2.4.1, `"typescript.format.insertSpaceAfterTypeAssertion": true` is an "unknown config setting" and it still removes the space when formatting.

**Comment by mjbvz** [comment]
@roblourens The change went in pretty recently and isn't in the current insiders build. Can you try a build from master? The next insiders should also have this change

**Comment by roblourens** [comment]
Oops, didn't notice the timestamp

**Comment by chrmarti** [comment]
Verified the setting exists and works as expected.
