### ISSUE TITLE
Do not execute task with pickstring on escape

### ISSUE THREAD

**Issue by af-productions** [microsoft/vscode#102931]
I have several build tasks for a makefile project, which use a pickString to execute different make targets. When i press the escape button, the task still executes but without a make target. 
Instead it should cancel the execution and close the build tasks window

Update:
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 3.10.0-327.el7.x86_64

**Comment by af-productions** [comment]
Update:
VS Code version: Code 1.47.2 (17299e4, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 3.10.0-327.el7.x86_64

**Comment by alexr00** [comment]
I'm not able to reproduce this issue. My tasks.json:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Pick a Number",
            "type": "shell",
            "command": "echo ${input:pickNumber}"
        }
    ],
    "inputs": [
        {
            "id": "pickNumber",
            "description": "Pick a Number",
            "type": "pickString",
            "options": [
                "one",
                "two",
                "three"
            ],
            "default": "one"
        }
    ]
}
```

Do you see the issue when you use that tasks.json?

**Comment by af-productions** [comment]
Yes. I executed the task and instead of selecting a number, i pressed the escape button. Then a new Terminal Session opened with the Following Output:
```
> Executing task: echo ${input:pickNumber} <

Terminal will be reused by tasks, press any key to close it.
```

**Comment by af-productions** [comment]
When I execute the same Task and select a number, say one, I get the following output:
```
> Executing task: echo one<

[Here was my company´s session info output]
one

Terminal will be reused by tasks, press any key to close it.
```

**Comment by alexr00** [comment]
Only occurs when using a remote.

**Comment by af-productions** [comment]
I just tested it locally on my Windows machine and can confirm, that the issue didn´t occure there. It only happens when I´m connected to the remote machine.
