### ISSUE TITLE
VSCode doesn't do a hot reload after code being saved.

### ISSUE THREAD

**Issue by rahuliamsarkar** [microsoft/vscode#102974]
Issue Type: <b>Bug</b>

VSCode doesn't do a hot reload after code being saved.

I had both flutter and vscode upgraded.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.7.94776
vscode-yaml|red|0.9.1

</details>

**Comment by roblourens** [comment]
This would be an issue with flutter or whatever you are using to do hot reloading.
