### ISSUE TITLE
Highlighting the argument name is string matching, instead of highlighting the actual argument number

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#10293]
_From @prashantv on May 14, 2016 3:22_

If the argument name is a substring of the function name (or a previous argument), the wrong thing is highlighted.

E.g.
![image](https://cloud.githubusercontent.com/assets/140159/15265914/370fd22a-1948-11e6-87eb-9c137900fd97.png)

_Copied from original issue: Microsoft/vscode-go#327_

**Comment by egamma** [comment]
_From @lukehoban on May 15, 2016 19:40_

@egamma Is this expected to be possible to fix in extensions?  As far as I can tell, this is controlled by logic in VS Code.

**Comment by egamma** [comment]
_From @prashantv on August 6, 2016 18:48_

Should I file an issue on the vscode repository instead?

**Comment by egamma** [comment]
Moving to vscode

**Comment by jrieken** [comment]
That's a short coming of our API - when building the UI we search for the first occurrent of a [parameter label](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2082). We need to allow for a precise way of telling where a parameter in the signature label exists...

**Comment by prashantv** [comment]
Ah, I see. A short-term fix could be to look after the first open parens `(`

**Comment by jrieken** [comment]
Only if your programming language used `(` and `)`. Maybe instead of `indexOf` I can try `lastIndexOf` start with the last parameter and so on

**Comment by jrieken** [comment]
I improved the heuristic to look for parameters at the end of the string. Not perfect but should make things better

**Comment by jrieken** [comment]
Closing as there is now a better heuristic for this and since the real change will require API breakage which we aren't eager on

**Comment by joaomoreno** [comment]
Oh wow. How come we came out with this API? Should we just stop highlighting the arguments in the method definition?
