### ISSUE TITLE
Problems in the tab bar.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#10299]
- VSCode Version: 1.5.0-insider dde41be
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Steps to Reproduce:

1. Open a tab that is not in Preview Editors.
2. Click here to see the extensions, click on an extension.
3. Note that the tab bar disappears.
4. Open a new tab by double-clicking on the tab bar, or File> New File or Ctrl + N.
5. Note that the open tabs still does not appear.
6. Now click explorer.
7. See which still guides do not appear until you close the explorer the extensions tab.

**Comment by jrieken** [comment]
@Tekbr Can you please attach an animated gif?

**Comment by StephD** [comment]
- VSCode Version: 1.4.0
- OS Version: Win 7

I got the problem too. Same problem with extension and new tab (by double clicking)

![output_jkgw00](https://cloud.githubusercontent.com/assets/1171858/17480636/1d1de378-5d79-11e6-8359-f8e44a539a86.gif)

**Comment by Tekbr** [comment]
Thanks @StephD .

**Comment by StephD** [comment]
There isn't any arrow to show where i click, where it's missing but I hope you got it.

The tab problem with new file (by double clicking and tab bar) is super easy to reproduce. (Also works with ctrl+n and with menu)

**Comment by Treri** [comment]
Is my problem the same with this issue reported?

The opened files tabs are disappeared when I press `cmd + n` to create an untitled file.
If I close the untitled tab, the tabs appear again.

Is this designed or incorrect?

![f](https://cloud.githubusercontent.com/assets/2631733/17482413/44b8a360-5db4-11e6-8368-e78d495b3f18.gif)

**Comment by Tekbr** [comment]
I removed all extensions and installed one by one, and the problem seems to be with the extension icons (vscode-icons). Disabling the extension, the problem does not happen.

I think it has to do with this issue [#152](https://github.com/robertohuertasm/vscode-icons/issues/153).

**Comment by bpasero** [comment]
We are working on providing official API for the extension to provide icons. We discourage the way this extension is changing our core.

@aeschli @egamma @chrisdias @kieferrm fyi we do currently not have it on the plan to show the icons in the tab as well, but this is what the extension seems to do now.

**Comment by Tekbr** [comment]
@bpasero Happy to see what you said.

> We are working on providing official API for the extension to provide icons.

I do not see time to see it officially in VSCode. Could you tell me which issue are arguing more often on the icons in VSCode.

I thank you for the help. Sorry about that.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10294

**Comment by StephD** [comment]
https://github.com/robertohuertasm/vscode-icons/issues/153#issuecomment-238259419
