### ISSUE TITLE
Add actions to move tabs within groups (Ctrl-Shift-PgUp and Ctrl-Shift-PgDown)

### ISSUE THREAD

**Issue by haibison** [Microsoft/vscode#10291]
- VSCode Version: 1.4.0
- OS Version: Windows 10; Fedora 24 (Xfce4 desktop)

Hi VSC team,

It would be great if you add these shortcuts to move current tab:

- `Ctrl-Shift-PgUp`: move to the left.
- `Ctrl-Shift-PgDown`: move to the right.

Thank you  `:-)`

**Comment by bpasero** [comment]
@haibison that is, to move the tab within a group to another location in that group, not across groups?

@sandy081 are the commands you added for VIM assignable via keybindings?

**Comment by haibison** [comment]
I haven't used Groups yet, so I think it's moving the tab within current group.

Just in case, you can add one more key `Alt` to move across groups...

**Comment by bpasero** [comment]
Ok I do not think we have these actions yet exposed (except for moving tabs across groups), so this feature request is about having actions to move tabs within groups.

**Comment by rebornix** [comment]
@bpasero , @sandy081 added commands for moving tabs within groups as well but these commands require arugments like `{ to: "first" }`, I'm afraid this can not be used in keybindings?

A sample command to move tab: `vscode.commands.executeCommand("activeEditorMove", { to: "first" });`: move current tab to the first position of current group.

**Comment by bpasero** [comment]
@rebornix thanks I can nicely use the commands from my action.

**Comment by haibison** [comment]
Thanks to team for your hard work. I got 2 issues resolved today, awesome  `:-D`

**Comment by bpasero** [comment]
@rebornix fyi filed minor issue with the commands, maybe you could have a look (https://github.com/Microsoft/vscode/issues/10312)
