### ISSUE TITLE
JSDoc: function with param or null

### ISSUE THREAD

**Issue by liangjiancang** [microsoft/vscode#102925]
Example:

```js
/**
 * @param {?((n: number) => void)} add - shows [ add: (n: number) => void ]
 * @param {?(() => void)} delete - shows [ delete: (() => void) | null) ]
 */
function example(add, delete) {
    add && add(1)
    delete && delete()
}
```

The first line should be `add: ((n: number) => void) | null`

**Comment by mjbvz** [comment]
VS Code's JS intellisense is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) for recognizing JSDoc's nullable types. 

You can use TS Types instead:

```
 * @param {null | ((n: number) => void)} add - shows [ add: (n: number) => void ]
```
