### ISSUE TITLE
Unable to resize the GIT list between source control providers and the changes list

### ISSUE THREAD

**Issue by jcuffe** [microsoft/vscode#102967]
Issue Type: Bug

Click on source control
Expand out the Source Control Providers list
Click on a specific repo
Expand out the Changes list

Hover over the area where you would resize the divider between the two sections, the arrow doesn't change from the selector icon to the arrow resize icon.

VS Code version: Code - 1.47.2
OS version: Windows 10

Seems like the solution to #70933 is no longer viable and this is now just a "feature"

**Comment by joaomoreno** [comment]
All source control providers are in the same tree now. There is no resizer.
