### ISSUE TITLE
Wrong syntax highlighting when using \. in regex inside HEREDOC

### ISSUE THREAD

**Issue by lucasbasquerotto** [microsoft/vscode#102958]
- VSCode Version: 1.47.1
- OS Version: Linux x64 5.3.0-62-generic snap (Ubuntu 18.04)

Steps to Reproduce:

1. Paste the below code:

```
#!/bin/bash

cat <<SHELL > /path/file2
	if [[ "$myvar" =~ ^(([0-9]|[1-9])\.)$ ]]; then
		echo "test"
	fi
SHELL
```

2. Verify that the closing SHELL is highlighted as a string (not with the same color as the starting SHELL), and from there on till the end of the file (if there is more content), the highlight will consider the code as if it was inside the HEREDOC (even tough it isn't).

This **does not happen** if I remove `\.` from the regex (but this **changes** what it does):

```
#!/bin/bash

cat <<SHELL > /path/file2
	if [[ "$myvar" =~ ^(([0-9]|[1-9]))$ ]]; then
		echo "test"
	fi
SHELL
```

This also doesn't happen if I wrap `\.` with brackets (it's the **current workaround** I'm using):

```
#!/bin/bash

cat <<SHELL > /path/file2
	if [[ "$myvar" =~ ^(([0-9]|[1-9])(\.))$ ]]; then
		echo "test"
	fi
SHELL
```

**Comment by alexr00** [comment]
We get our grammar for shell script syntax highlighting from https://github.com/atom/language-shellscript, but they aren't supporting the grammar anymore. I'll keep this bug around in case we update where we get our grammar from.

**Comment by alexr00** [comment]
Linking and closing in favor of https://github.com/microsoft/vscode/issues/77675, which tracks considering a new shellscript grammar.
