### ISSUE TITLE
Support reading from stdin with encoding configured in calling shell

### ISSUE THREAD

**Issue by imba-tjd** [microsoft/vscode#102917]
- VSCode Version: 1.47
- OS Version: Win10 20H2 and Win7 x86 in VM

Note

* This issue is related to the shell. That command **works** in cmd according to my test (if you set files.autoGuessEncoding to false or manually change the encoding to UTF8 but that's another question).
* The results of PS 5.1 and pwsh are different.
* In pwsh, the result `浣犲ソ` is the same as saving `你好` as UTF8 and reopen as GBK, and is the same as setting `chcp 65001` ahead in cmd. But `chcp 65001` has no effect in pwsh.

Steps to Reproduce:

`echo 你好 | code -`

![图片](https://user-images.githubusercontent.com/24759802/87904525-0cadb200-ca91-11ea-8bad-91528ab6afa7.png)

![图片](https://user-images.githubusercontent.com/24759802/87904796-ad03d680-ca91-11ea-8ac5-6f7870da749d.png)

![图片](https://user-images.githubusercontent.com/24759802/87904893-f9e7ad00-ca91-11ea-8cd6-e360896bc3ac.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We internally use `chcp` command to figure out the encoding and maybe that does not yield the expected results. What is your output when you run it in the different shells?

Also, please add the `--verbose` flag to VSCode invocation, that should print a bit more details about the detected encoding from the terminal.

**Comment by imba-tjd** [comment]
1. All of them shows `Active code page: 936`
2.
  ![图片](https://user-images.githubusercontent.com/24759802/87908278-b3e21780-ca98-11ea-89c7-5662da471034.png)

**Comment by bpasero** [comment]
Since this seems to be working fine in cmd, I suspect an upstream issue possibly in powershell? Can you file an issue with them?

**Comment by imba-tjd** [comment]
There is one issue with cmd. By using `chcp 65001` VSCode still gets 936, though it's not for ordinary use.

![图片](https://user-images.githubusercontent.com/24759802/87921244-e0a02a00-caac-11ea-86f7-f77321fe81d3.png)

**Comment by bpasero** [comment]
Ok renaming the issue then. If someone wants to investigate, opening for help wanted.

**Comment by imba-tjd** [comment]
I think the title is not accurate. The daily env and the issue I meet is under chcp 936. 65001 is only for testing.

**Comment by bpasero** [comment]
@imba-tjd this issue has split into two things:
* your issue is now reported here: https://github.com/PowerShell/PowerShell/issues/13216
* you indicated that there is another issue in https://github.com/microsoft/vscode/issues/102917#issuecomment-660909552

I am confused, what should I do now with this issue?

**Comment by imba-tjd** [comment]
Well, I personally don't think this is a pwsh issue :joy:. What if they think it's a VSC's issue and won't fix. I don't want my issue lost. The main goal is that I want to use `code -` in chcp 936 in pwsh.
Anyway do as you like.

**Comment by bpasero** [comment]
Ok let's see what PowerShell folks have to report about this. If there is a different way to get the terminal encoding that is not via `chcp` then maybe we have to change that.

**Comment by bpasero** [comment]
@imba-tjd I think I can explain the issue now, we use node.js `exec` to run `chcp` and this is probably using `cmd.exe` and not Powershell. 

As a workaround you can set environment variable `VSCODE_CLI_ENCODING` to fix this. We pick this value up and ignore the result from `chcp`.

**Comment by imba-tjd** [comment]
Yes, By setting `$env:VSCODE_CLI_ENCODING = "utf8"` in $profile can fix this in a way.

Although that don't work for PS 5.1 in my test (tried "cp1252" and "us-ascii" and "1252"), I hardly use legacy PS, so no another workaround is needed.

**Comment by bpasero** [comment]
It should work in any terminal/shell that can set environment variables that reach VSCode, maybe PS 5.1 did not have this concept yet.

**Comment by bpasero** [comment]
Great analysis starting from https://github.com/PowerShell/PowerShell/issues/13216#issuecomment-661130448 why this currently does not work.

Workaround for now is to configure `VSCODE_CLI_ENCODING` from the shell that VSCode is started from.

Leaving this open as feature request to do something better here, but I am not very optimistic.
