### ISSUE TITLE
The terminal process "/bin/zsh '-l', 'vcode'" terminated with exit code: 127.

### ISSUE THREAD

**Issue by SeanDunford** [microsoft/vscode#102955]
- VSCode Version:
```
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z (4 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```
- OS Version:
![image](https://user-images.githubusercontent.com/1704718/87950011-c2b6d300-ca74-11ea-9995-216f66c42541.png)

Steps to Reproduce:
1. Open Command Palette (cmd + shift + p)
2. open integrated terminal

Does this issue occur when all extensions are disabled?: Yes. 

I've also completely emptied my `.bashrc` and `.zshrc` file. I've reinstalled vscode a few times. Not really sure what is wrong here. I searched for duplicates and while there are similar issues. None of them had the exact error for mac. Happy to provide any other details if needed. Thank you. 

```
The terminal process "/bin/zsh '-l', 'vcode'" terminated with exit code: 127.
```

![image](https://user-images.githubusercontent.com/1704718/87950774-bb43f980-ca75-11ea-8303-0beb11496ff2.png)

**Comment by Tyriar** [comment]
What is `vcode`? Does running `zsh -l vcode` fail in a terminal?

**Comment by SeanDunford** [comment]
Yes. I'm not sure what vcode is or where it's defined. This is nearly a fresh laptop. Let me try to peak in my dotfiles for this alias or something.

**Comment by Tyriar** [comment]
@SeanDunford check your settings.json file, as it looks like you have `terminal.integrated.shell.osx` set to include `vcode`.

**Comment by SeanDunford** [comment]
This was in my `settings.json` file

```
{
    "terminal.integrated.shellArgs.osx": [
        "-l",
        "vcode"
    ],
```

I've removed all non-default settings and this has returned to normal. Thank you for the help. Sorry it was just a typo!
