### ISSUE TITLE
Source Control doesn't detect changes made to files

### ISSUE THREAD

**Issue by rori4** [microsoft/vscode#102936]
Source control left side panel doesn't detect changes after Windows update. I recently updated to Windows Build 19041 (I guess its related) and now the source control sidebar **doesn't detect changes made to cloned repos from remote or previously existing repos on the machine.**

**HOWEVER,  if I create a new local folder and repo with `git init` it acts normally and detects all changes.**

Related Issues: 
- https://github.com/microsoft/vscode/issues/45768
- https://github.com/Microsoft/vscode/issues/48097
- (and some more but they were not that related)

Things I have tested and doesn't help:
- reinit the repo with `git init`
- disabling all extensions
- downgrading VSCode version to 1.47.1
- reinstalling VSCode
- reinstalling Git
- cloning a repo in System drive and testing it from there
- adding `"git.autorefresh": true,` to settings.json
- changing files from outside of VSCode (changes still not detected)
- tried running vscode from the folder with `code . --verbose --disable-extensions` and performed a change to a file. Opened the console `Help > Toggle Developer Tools > Console` in hope to see any error but there was nothing.

Files Watcher Exclude settings:
```
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/*/**": true
  },
```

Versions:
- VSCode Version: 1.47.2
- OS Version: Windows 10.0.19041 Build 19041
- Git Version: 2.17.1

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by rori4** [comment]
I just reverted my Windows to Version 10.0.18362 Build 18362 and I can confirm that it resolved the issue **so its definitely the  Windows Build 19041**

**Comment by joaomoreno** [comment]
cc @bpasero
