### ISSUE TITLE
CompletionItem need a click Event, When selecting a completion item .

### ISSUE THREAD

**Issue by monster-hui** [microsoft/vscode#102915]
the return completion item form CompletionItemProvider.provideCompletionItems
When selecting a completion item in the editor,I want to get the selected completion item，and count the number。

**Comment by jrieken** [comment]
[`CompletionItem#command`](https://github.com/microsoft/vscode/blob/f0283ed23950bd5c729ded6964874452c593994f/src/vs/vscode.d.ts#L3896)
