### ISSUE TITLE
after June 2020 update...Powershell command issue

### ISSUE THREAD

**Issue by jim-dickinson** [microsoft/vscode#102988]
Issue Type: <b>Bug</b>

After June 2020 update, the powershell commend "connect-microsoftteams" no longer launches modern authentication. This still works from Powershell and ISE...but not from Code anymore.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (21.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-edit-csv|jan|0.3.0
powershell|ms-|2020.6.0
material-theme|zhu|3.8.5

</details>

**Comment by Tyriar** [comment]
Are you sure it doesn't just show up behind the VS Code window? That's a known issue https://github.com/microsoft/vscode/issues/42356
