### ISSUE TITLE
Error: listen EPERM: operation not permitted /home/USER/.config/Code/1.47.1-main.sock

### ISSUE THREAD

**Issue by pobv** [microsoft/vscode#102952]
When starting visual studio code over x2go on a kvm machine with a cifs mounted directory (don't ask, we must do it that way) 
it does not start. Directly starting it, I get the following error
```
/usr/share/code $ ./code 
[main 2020-07-20T13:58:06.047Z] Error: listen EPERM: operation not permitted /home/USER/.config/Code/1.47.1-main.sock
    at Server.setupListenHandle [as _listen2] (net.js:1211:19)
    at listenInCluster (net.js:1276:12)
    at Server.listen (net.js:1375:5)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:207:673
    at new Promise (<anonymous>)
    at Object.t.serve (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:207:610)
    at Object.doStartup (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:624:488)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:622:532
    at u.invokeFunction (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:283:612)
    at Object.startup (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:622:375)
```

The actual path is disguised and replace by USER. The mount is 

```
//<host>/<path>/USER on /home/USER/nethome type cifs (rw,relatime,vers=3.0,cache=strict,username=USER,forcegid,addr=<addr>,file_mode=0700,dir_mode=0700,soft,nounix,serverino,mapposix,nobrl,mfsymlinks,rsize=4194304,wsize=16384,bsize=1048576,echo_interval=60,actimeo=1) and 
$ ls -ld ~/.config
lrwxrwxrwx 1 6660815 39 Jul 20 13:48 /home/USER/.config -> /home/USER/nethome/.config
```

and the folder .config/Code is under cifs-mount.

Any help appreciated!

**Comment by joaomoreno** [comment]
Maybe start it with a different user data directory: `--user-data-dir FOLDER`

**Comment by pobv** [comment]
Thanks, at least it starts now. However, the settings.json is also in the user-data-dir. If that is local I loose the personal settings after each login/logout; which is exactly the reason the config folder is on a network share in the first place. If I use any other folder on the network share, then it fails again.
Are there any secret options to just move the .sock but not the user-data-dir to another place? Thanks in advance

**Comment by joaomoreno** [comment]
There is no option for that currently. Since CIFS doesn't seem to support UNIX sockets, we don't really support storing user data dir in CIFS, sorry!

**Comment by pobv** [comment]
To help others stumbling over this issue... It happens in `environmentService.ts` in the function `getNixIPCHandle` and is handled similarly in 3 different locations in the code. Quite nicely, it tries to adapt to the environment and either creates the `..sock` in a `/run/user/<id>/` directory or in `.config/User/`. On our platform it concludes (maybe rightly) that `/run/user/<id>/` is fine, which it isn't because we use purely numeric usernames (yes, that is a very very bad idea indeed) and `pam_systemd` fails to create that directory when domain names are attached to the user. However, we can fixup visual studio code, by forcing visual studio code to use another directory. vscode gets its information from `XDG_RUNTIME_DIR`, which we can simply create and provide
```
#!/bin/sh
export XDG_RUNTIME_DIR=$(mktemp -d)
exec /usr/bin/code
```
That works fine now. However, after a couple of weeks and hundreds of users cleaning up the `/tmp/` directory might be advisable.
All the best...
