### ISSUE TITLE
Icon for Nim

### ISSUE THREAD

**Issue by ShalokShalom** [microsoft/vscode#102943]
Nim, the programming language, has no icon in the tab element.

![Screenshot_20200720_132931](https://user-images.githubusercontent.com/6344099/87933864-4af5a200-ca8e-11ea-883a-7372d80a7d42.png)

**Comment by aeschli** [comment]
The request to add an icon `nim` to the Seti theme needs to be filed against https://github.com/jesseweed/seti-ui/issues

**Comment by ShalokShalom** [comment]
https://github.com/jesseweed/seti-ui/pull/579
