### ISSUE TITLE
VS Code Terminal Intergrated Shell Linux - Terminal Launch Failure 

### ISSUE THREAD

**Issue by whiteca5125** [microsoft/vscode#102913]
Report Issue - 
The terminal process failed to launch: Path to shell executable "usr/bin/bash" 
Note: the bash folder exists on the Ubuntu WSL. 

Additionally, a test bash folder was used to confirm the path functionality. The test folder worked briefly, however, the test bash folder is no longer working. "usr/bin/bashTESTFOLDER/bash". Can anyone explain the disruption of service? 

---Thank You Very Much,

-Christopher White

**Comment by Tyriar** [comment]
1. How are you launching the terminal?
2. Can you share your settings.json file?
3. Can you show a [gif](https://gifcap.dev/) of it happening?

**Comment by whiteca5125** [comment]
Thank you for the response -

This is an Attached  Photo of the JSON File (Below): 

![JSON_FILE_VSCODE](https://user-images.githubusercontent.com/13409564/89478636-8797ed80-d75e-11ea-9597-8bb1bf8154c2.gif)

This is an Attached Photo of the Error Code (Below):

![Error_Code](https://user-images.githubusercontent.com/13409564/89478651-9088bf00-d75e-11ea-9fee-d4886adda515.gif)

`The terminal maintains all functionality but terminal start-up  (basically the Ubuntu WSL is accessible through VSCODE, but the terminal is dysfunctional)?

**Comment by Tyriar** [comment]
`usr/bin/bash` is not a valid absolute path, use `/usr/bin/bash`
