### ISSUE TITLE
Install Latest Update is failing

### ISSUE THREAD

**Issue by mirather** [microsoft/vscode#102963]
Issue Type: <b>Bug</b>

my present version is 1.47.1 and trying to update to latest version 1.47.2 
it is failing to update after the download, installing, and restarting the VS Code.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (3.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.1.3
debugger-for-chrome|msj|4.12.9
vscode-scss-formatter|sib|2.0.1

</details>

**Comment by joaomoreno** [comment]
Can you show me the error? Maybe a screenshot?
