### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by aloshon** [microsoft/vscode#102977]
Issue Type: <b>Feature Request</b>

I am having trouble changing the file I want to debug, for some reason it is stuck on debugging python code even though it is javascript

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

**Comment by weinand** [comment]
What steps are you doing in order to debug?
How does your launch.json look like?
