### ISSUE TITLE
Make "Toggle Word Wrap" On Application Instance Level.

### ISSUE THREAD

**Issue by jenson** [microsoft/vscode#102978]
Current "Toggle Word Wrap" Works at the Opened File level. This means If any new file gets Opened, He/She has to Explicitly select this Option (Or **Alt+Z**) to Toggle Word Wrap. Can this be done on the Opened Application Instance Level?? So User need to select this Option separately in all other Files. Thanks.

**Comment by alexdima** [comment]
@jenson The action Toggle Word Wrap is for quickly toggling word wrap on the current file. There is a setting that can be set, `"editor.wordWrap": "on"`, which will make it that all opened files are word wrapped.

**Comment by jenson** [comment]
> @jenson The action Toggle Word Wrap is for quickly toggling word wrap on the current file. There is a setting that can be set, `"editor.wordWrap": "on"`, which will make it that all opened files are word wrapped.

That Helps. Thanks @alexdima Cheers.
