### ISSUE TITLE
Integrated Terminal Locks Files After Debugging

### ISSUE THREAD

**Issue by Quilamir** [microsoft/vscode#102927]
Issue Type: <b>Bug</b>

when running a debug session two terminals are created:

1. build from TS to JS.
2. server begins to run named "Node Debug Console" with debug enabled.

from there on the files in my dist directory become locked (busy) and any change to them causes the EBUSY error.

the second terminal is also keeping the files in a read-only state, even if i change the property outside vscode it reverts it back to read-only immediately.

if i restart vscode the lock is removed, if i trash the second terminal within vscode the lock is also removed.

also, the same project when debugging on a linux machine or a mac does not have this issue at all

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (11.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
vscode-docker|ms-|1.3.1
remote-containers|ms-|0.128.0
remote-wsl|ms-|0.44.4
vscode-typescript-tslint-plugin|ms-|1.2.3
html-preview-vscode|tht|0.2.5

</details>

**Comment by roblourens** [comment]
Debugging with which extension?

**Comment by Quilamir** [comment]
i have removed all extensions to make sure they are not in the way, the same issue happens.

the extensions i use normally are listed in the OP under extensions.

i did look into the WSL though in this case i am not using the WSL functionality as i am running on windows

also the environment is very simple, not in a docker or anything like that.

**Comment by roblourens** [comment]
What language though? I need exact steps to reproduce this issue, your report is very vague.

**Comment by Quilamir** [comment]
the project is written in Typescript

**Comment by roblourens** [comment]
Ok. The js debugger or the terminal do not lock your files, so this is likely something that your app is doing, or a build task, or a process linked to an extension or something else.

**Comment by Quilamir** [comment]
i have created a stripped down project that includes the environment without the code of the application

https://github.com/Quilamir/vscode

if you try and run the launch QA you will see the first time it will run the build and code and the second time it will fail to build and files in dist directory will be locked

**Comment by roblourens** [comment]
It really sounds like this is an issue with this build setup which still looks complex with a lot of dependencies.
