### ISSUE TITLE
Tabs don't update column counter

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#103]
Repro:
1. Hit the tab key
2. Column count in gutter doesn't update

![tabsdontupdatecolumns](https://cloud.githubusercontent.com/assets/972891/11254395/4745d61e-8df5-11e5-8c25-75383824e586.gif)

Forgive the GIF quality.

**Comment by boyP** [comment]
Hi, can I work on this bug?

**Comment by bpasero** [comment]
@boyP yes we do accept pull requests :).

**Comment by bpasero** [comment]
@alexandrudima not sure the fix is right, I can also change the editorStatus.ts to react on any types.

**Comment by alexandrudima** [comment]
Indeed, I think the status bar should reflect the cursor state, regardless of the reason the cursor changed its state. So the fix should be made in editorStatus

**Comment by alexandrudima** [comment]
Thanks for fixing this!

**Comment by bpasero** [comment]
:heart:

**Comment by DanielRosenwasser** [comment]
:tada: Thanks!
