### ISSUE TITLE
v1.48.0-insider can't copy and paste file in vscode,if I want to copy and paste,only can do in file system,but v1.47.2 can copy

### ISSUE THREAD

**Issue by Heaiai** [microsoft/vscode#103072]
- VSCode Version:v1.48.0-insider
- OS Version:windows10 x64

Steps to Reproduce:

1.copy file and choose new folder to paste,but no paste options
2.I install v1.47.2 don't has this question

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/100797
