### ISSUE TITLE
Program hangs after a certain number of messages in the debug console

### ISSUE THREAD

**Issue by pashka64** [microsoft/vscode#103013]
- VSCode Version: 1.47.2
- OS Version: Windows 10 Pro

Program hangs after a certain number of messages in the debug console
![image](https://user-images.githubusercontent.com/16876572/88056750-178c4380-cb72-11ea-9821-9281c8dd3541.png)

**Comment by connor4312** [comment]
/duplicate https://github.com/microsoft/vscode/issues/102254

You can use the [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension) until the fix for this is released in VS Code stable in the July release (which will be 1.48 at the beginning of next month)
