### ISSUE TITLE
[ruby] Add indentationRules

### ISSUE THREAD

**Issue by factormystic** [Microsoft/vscode#10307]
- VSCode Version: 1.4.0
- OS Version: Windows 10 v1511 b10586.494

Steps to Reproduce:
1. Open a ruby file
2. Define a new method at normal indent level (eg, type `def whatever`
3. Press <kbd>enter</kbd> to start a new line at the method body indent level
4. Type `end` to end the method block

I expected the text `end` to be auto-de-indented 1 level, so it matches `def whatever`. What actually happened is nothing at all.

That's the request. The question is, is this expected to be core behavior, or something I need an extension for since it's language specific?

**Comment by factormystic** [comment]
FYI this is real annoying when combined with https://github.com/Microsoft/vscode/issues/10197. I basically have to hit </kbd>backspace</kbd> `n` times instead of 0 times (this issue) or 1 times (related issue, if pre-indent whitespace was selectable.

**Comment by aeschli** [comment]
As auto indenting in ruby is a bit more tricky that needs to be done in code, using
indentationRules in the LanguageConfiguration.
See https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2530.

I see that the [vscode-ruby](https://github.com/rubyide/vscode-ruby) does it.
Have you tried that?

I'm happy to take a pull request if you want that in the default-ruby plugin.

**Comment by factormystic** [comment]
I do have that ruby extension installed. I also uninstalled it to confirm it wasn't an extension problem.

**Comment by pharmmd-rich** [comment]
+1

Any luck with this?  Makes it rather annoying to use VS Code for Ruby or Rails projects.  Please fix `end`!

**Comment by rebornix** [comment]
Dup of #2272 . Let's track it there. This sprint we'll at least indent `end` correctly when you press `enter.`
