### ISSUE TITLE
TypeScript language: auto close `<`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#103001]
When I type the following code in a TypeScript file:

```ts
type Foo = Bar<
```

… I would like VS Code to auto close the `<` character with a matching `>`.

I understand this behaviour is defined for each language. Could we consider auto closing `<` just for TypeScript?

**Comment by IllusionMH** [comment]
Looks useful however this might conflict with "less than" (especially `if (value<`, `const a = value<`) or JSX so will make sense only somewhere in type declarations/annotations.

Interesting if possible to add support for `"onlyIn": ["types"]` to mirror `notIn` for `autoClosingPairs`.

**Comment by mjbvz** [comment]
@IllusionMH Identified why this is not enabled

No plans to look into this in the short term

**Comment by OliverJAsh** [comment]
Lots of interest for this here: https://www.reddit.com/r/vscode/comments/ednx1l/is_it_possible_to_automatically_add_a_closing/

**Comment by OliverJAsh** [comment]
I'm curious if this has been discussed in any other issues, especially this idea:

> add support for `"onlyIn": ["types"]` to mirror `notIn` for `autoClosingPairs`.

**Comment by roife** [comment]
> I'm curious if this has been discussed in any other issues, especially this idea:
> 
> > add support for `"onlyIn": ["types"]` to mirror `notIn` for `autoClosingPairs`.

I'm very interested in this feature and I'm wondering if it could be added to VSCode. Perhaps we need to open a separate issue for this?
