### ISSUE TITLE
2019 mac air collapse

### ISSUE THREAD

**Issue by chaseyoungcn** [microsoft/vscode#103091]
Issue Type: <b>Feature Request</b>

On the MAC, tasked.json in VSCODE, when I swiped the trackpad with my fingers, suddenly the program crashed and couldn't close. The problem was solved only when I rebooted the computer

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.6.0

**Comment by deepak1556** [comment]
Are you still facing this crash ? If so, can you launch code with `--crash-reporter-directory <path>`, once the crash happens can you attach the `*.dmp` file generated under the `<path>`. Thanks!

It is also worth verifying if the crash happens with our exploration builds https://az764295.vo.msecnd.net/exploration/f0e1fbf4cb8c4c27d6290f0310f5a4d63597cd21/VSCode-darwin-exploration.zip
