### ISSUE TITLE
"Attach to Node Process" breakpoints not being hit

### ISSUE THREAD

**Issue by hbnrmx** [microsoft/vscode#103093]
- VSCode Version: 1.48.0-insider
- OS Version: macOS Catalina 10.15.6

Steps to Reproduce:

(See video: https://streamable.com/syfrwq)
1.  launch most basic app (`node --inspect app.js`)
2. Start Task `Debug: Attach to Node Process` > `node --inspect app.js`
3. Set breakpoint in app.js

expected result: breakpoint should be hit.
actual result: breakpoint is active but not hit.

4. Cancel
![Screenshot 2020-07-22 at 14 59 56](https://user-images.githubusercontent.com/46070579/88179326-06077200-cc2c-11ea-85cd-d3341cea94df.png)

_app.js_:
```
setInterval(() => {
  console.log("Hello world")
}, 3000);
```

Are there any logs to check out to see why the attach failed?

Does this issue occur when all extensions are disabled?: Yes

Thank you!

**Comment by connor4312** [comment]
Does this work if you use the "Attach to Node Process (preview)" command? The command you used runs in our older debugger, which will be going away at some point in the future.

**Comment by hbnrmx** [comment]
Hi, thanks for the quick response!
The issue remains with `Attach to Node Process (preview)`

**Comment by hbnrmx** [comment]
Could this be an issue with mismatched node versions?
`Code - Insiders` > `About Visual Studio Code - Insiders` reports `Node.js: 12.14.1`
while
 ```
> where node
/usr/local/bin/node

> node -v
v14.6.0
```

Not sure where vscode is getting the above version from...

**Comment by connor4312** [comment]
Ok, thanks, can you collect a trace log using these instructions?

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by hbnrmx** [comment]
It looks like my debug console is not working correctly.

I added `"trace: true"` to my launch.json like this,

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}",
            "request": "attach",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node",
            "trace": true
        }
    ]
}
```

but when I execute and pick the process as described above
the debug console stays empty. 

Could you tell me what the default log route is so I can try to find it manually?

**Comment by connor4312** [comment]
Hm, okay. So something is happening that keeps us from even trying to start the session. When the timeout happens, can you see if there's any errors in the console in the window that opens when `Developer: Toggle Developer Tools` is run?

**Comment by hbnrmx** [comment]
Oddly enough, without updating the OS, VS Code, Insiders or node, _the issue disappeared!_
Since both Code and Code Insiders started working again, I will assume it was a weird OS mishap.

Closing, as I cannot seem to reproduce any more...
Again, thanks for your support! 👍
