### ISSUE TITLE
Fail to activate virtual python environment in vscode terminal

### ISSUE THREAD

**Issue by Oakento** [microsoft/vscode#103011]
I selected a virtual environment named "data" for running a python script which requires numpy but failed to import it, receiving "ImportError: Unable to import required dependencies: numpy: xxxxxx Importing the numpy C-extensions failed." error.  I'm convinced numpy was properly installed in the environment and the script worked fine on system terminal(windows 10 powershell).

Then I tested vscode terminal by Input:
```
conda activate data

python -c "import numpy"
```
receives Output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
```

**Comment by sharur7** [comment]
Try doing this:-
conda install --force-reinstall numpy=1.17.5

**Comment by Oakento** [comment]
> Try doing this:-
> conda install --force-reinstall numpy=1.17.5

Hey, I tried reinstalling to 1.17.0 but still the same. 

The problem is that, calling `conda activate {venv_name}` wouldn't actually activate virtual environments in VS Code terminal, while in earlier version, it would respond to that command, activating virtual environments. However, if you create a environment through `python -m venv {venv_name}` or `vritualenv {venv_name}` if using virtualenv, environments can be activated through .\{venv_name}\Scripts\activate in the current version of VS Code terminal.

**Comment by sharur7** [comment]
Did that solved your error?

**Comment by Oakento** [comment]
> Did that solved your error?

no, it didn't
