### ISSUE TITLE
File Saving Problem

### ISSUE THREAD

**Issue by younoch** [microsoft/vscode#103074]
When I try to save any file then I get this massage:

Failed to save '_grid.scss': Unable to write file '/media/younoch/Official/Professional_Files/Leaning_Resource/Web_Development/Udemy_Advanced_CSS_Sass/advanced-css-course-master/advanced-css-course-master/Natours/starter/layout/_grid.scss' (Unknown (FileSystemError): Error: EROFS: read-only file system, open '/media/younoch/Official/Professional_Files/Leaning_Resource/Web_Development/Udemy_Advanced_CSS_Sass/advanced-css-course-master/advanced-css-course-master/Natours/starter/layout/_grid.scss')

I faced this problem after update THE VS CODE.

**Comment by joaomoreno** [comment]
> read-only file system

You're trying to save to a read-only filesystem. Please save the file somewhere else.
