### ISSUE TITLE
Readme.md cpp syntax highlighting doesn't works on start

### ISSUE THREAD

**Issue by gurrrung** [microsoft/vscode#103064]
- VSCode Version: 1.46.1
- OS Version: Ubuntu 18

Steps to Reproduce:

1. Create a Readme.md file with CPP code syntax highlighting like this:

````
``` cpp
#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}
``` 
````

2. Save the file and Close VSCode and open again, syntax highlighting doesn't work and you have to close that file and open it again for it to work.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I can't repo this. Do you see it in VS Code 1.47+?

**Comment by gurrrung** [comment]
I updated to 1.47 and its fixed there.
