### ISSUE TITLE
Code - OSS includes test extensions as builtin

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#103086]
I built Code - OSS from source, launched it as looked at the end of the Features section of the @builtin list of extensions:

![image](https://user-images.githubusercontent.com/6726799/88164623-46ef8e80-cc0c-11ea-800f-762d1b0bfc33.png)

Compare with the same list from the Insiders I built from:

![image](https://user-images.githubusercontent.com/6726799/88164755-77372d00-cc0c-11ea-9aa6-7f4c04ccc0ba.png)

Is it intentional that the OSS build includes extensions from the test suite?

VS Code version: Code - OSS Dev 1.48.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
Yeah, we selectively package extensions for the build and in sources we do not.

**Comment by gjsjohnmurray** [comment]
Fair enough, but it results in some interesting content in defaultSettings.json

![image](https://user-images.githubusercontent.com/6726799/88270617-d01aca00-cccd-11ea-83b6-872c42346173.png)

**Comment by sandy081** [comment]
Yeah not nice but I think its fine
