### ISSUE TITLE
Support a few recent Git versions (do not require most recent)

### ISSUE THREAD

**Issue by lptr** [microsoft/vscode#103014]
Issue Type: <b>Bug</b>

With a remote connection to a Windows box I get an error telling me I need to upgrade Git to 2.27 in order to have the Git functionality work in VSCode. (I have 2.26.2.windows.1 installed.)

![image](https://user-images.githubusercontent.com/495366/88056341-adb76e00-cb60-11ea-88c6-318a128b3564.png)

The requested version has been released just six weeks ago, and is currently the latest available version of Git. Requiring such a fresh installation is hard to fulfill in organizations where cloud instances are managed centrally, so upgrading Git is not as simple as downloading and running an installer. It's also not easy to understand why the requirement is there given that the same functionality worked just fine a week ago.

It would be preferable if VSCode always supported a few minor versions of Git at least, perhaps going back a year or so. That would give users a wide-enough window to keep their Git installs up-to-date.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0
Remote OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|32.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: windows45|
|OS|Windows_NT x64 10.0.18363|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (6 x 3600)|
|Memory (System)|28.00GB (18.43GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.2
Kotlin|mat|1.7.1
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.9
debugger-for-edge|msj|1.0.15
material-icon-theme|PKi|4.2.0
open-in-browser|tec|2.0.0
reopenclosedtab|uyi|1.1.0

(1 theme extensions excluded)

</details>

**Comment by lptr** [comment]
Sorry, didn't read it properly. This is not about a lack of support but about known issues.

It would be nice to get some more info about what those known issues are.

Also, mentioning that a downgrade could solve the problem would be nice.

**Comment by IllusionMH** [comment]
Implemented in scope of #100701 that has #98967 as example.

There's #102455 which tracks improvements for notification (e.g. don't show button) - you can add suggestion about downgrade suggestion there.

/cc @joaomoreno

**Comment by lptr** [comment]
Thanks, I moved my comments to https://github.com/microsoft/vscode/issues/102455#issuecomment-661852083.
