### ISSUE TITLE
Webview local resource loading stalled

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#103036]
- VSCode Version: OSS Dev
- OS Version: macOS

Steps to Reproduce:

1. Clone https://github.com/microsoft/notebook-extension-samples
2. `npm install && npm run build` (choose the first option if you see prompt for dependencies)
3. Run OSS with extensions folder set `./scripts/code.sh --extensions-dir ../notebook-extension-samples`
4. Open https://github.com/microsoft/vscode-notebook-testdata/blob/master/nteract/nteract-1-perf-text.test.ipynb
5. Run the first cell
6. The output takes seconds to show up

The profiling shows that it stuck at loading the js resources into the webview

![image](https://user-images.githubusercontent.com/876920/88089695-4b9b4080-cb41-11ea-9d1e-52df9b1e0b6d.png)

![image](https://user-images.githubusercontent.com/876920/88089669-3faf7e80-cb41-11ea-9c70-d37125b5f778.png)

It happens only when loading files from local file resource but not through http.

**Comment by mjbvz** [comment]
Should be fixed by ec8606cb49ec839ccdf90c278f44c5bfa3567063
