### ISSUE TITLE
quick fix , auto fix  are hard to use

### ISSUE THREAD

**Issue by lxsnum1** [microsoft/vscode#103061]
Issue Type: <b>Feature Request</b>

Currently the quick fix & auto fix are invocked somewhere  around the mouse arrow by the shortcut, but you have to move  the mouse to look the fix suggestion. Instead, it  would be  better to invoke the suggestion around the cursor. 

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

**Comment by mjbvz** [comment]
I don't understand the issue. Can you please provide screenshots that explain this
