### ISSUE TITLE
TypeScript - ability to rename/move file (refactoring)

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10305]
- VSCode Version: Code - Insiders 1.5.0-insider (dde41be0231d6f8397d1da969ddab351f137b833, 2016-08-08T06:03:58.264Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Code:
```ts
// file test.ts
export const test = 5

// file main.ts
import { test } from './test'
```
2. It would be fantastic if one could put cursor into `./test` and hit `F2` (Rename Symbol) to rename/move file and TypeScript would update all import statements that used that file to reflect the change. Right now it's pretty painful to rename/move files (one needs to fix imports manually)

It would go great with this feature request https://github.com/Microsoft/vscode/issues/9349 so that one could rename it as `../new-test` and it would move and rename file in one step.

Currently if you do `Rename Symbol` on import path then popup shows up but when you change value and hit enter nothing happens (popup just dissapears) - in other cases there is message in vscode that this element cannot be renamed - so probably minor bug
![image](https://cloud.githubusercontent.com/assets/1723815/17482127/57958680-5d4e-11e6-9f44-85f447c37a4a.png)

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#10218
