### ISSUE TITLE
alert: The terminal process bash terminated with exit code: x

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#103067]
- VSCode Version: 1.47.2
- OS Version: macOS 10.15.6

Steps to Reproduce:

1. open integrated terminal
2. run these commands: `false; exit`
3. the alert is shown

![image](https://user-images.githubusercontent.com/610161/88132627-a486d980-cc12-11ea-83d5-fd31b11e3805.png)

Is it possible to make this alert less annoying? maybe turn it to a warning in the log? 99% of cases I just want to close it and doing that is boring, maybe not really a bug but it bugs me and probably others too.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Either type `exit 0` or set `"terminal.integrated.showExitAlert": false`
