### ISSUE TITLE
Python parser incorrect errors found Fedorda 32

### ISSUE THREAD

**Issue by newnativeabq** [microsoft/vscode#103058]
Issue Type: <b>Bug</b>

Open repository (https://github.com/c19-rnd-dashboard/py-api-vac-rnd-dash) and begin editing.  Restart of VSCode solves problem temporarily.  Afer unspefic number of file operations and git commands, parser suddenly starts seeing newline errors everywhere.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-14T00:13:57.513Z)
OS version: Linux x64 5.7.8-200.fc32.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600X Six-Core Processor (12 x 2070)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.29GB (0.77GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|plasma|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.11.0
go|gol|0.15.1
chat|kar|0.35.0
kite|kit|0.121.0
rainbow-csv|mec|1.7.0
vscode-docker|ms-|1.3.1
mssql|ms-|1.9.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.7.94776
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
vsliveshare|ms-|1.0.2478
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
vscode-yaml|red|0.9.1
vscodeintellicode|Vis|1.2.9

</details>

**Comment by safetymonkey** [comment]
+1. This is happening to me on MacOS Catalina as well. I'll come back and paste a clearer example later (I just restarted vscode to confirm it would temporarily fix the problem), but interestingly it looked like the parser was somehow interpreting the git history of the file.

For example, on the following file (this is literally the entire file, verbatim):
```python
from __future__ import absolute_import
import os


class ServerSettings(object):
    @staticmethod
    def is_debug_server():
        return os.environ.get('SERVER_ENVIRONMENT') != 'PRODUCTION'
```
it complained on the final line about an invalid or unrecognized symbol `TARTSWITH('DEVELOPMENT')` on the final line. Interestingly, several commits ago we changed the final line, it used to be `return os.environ.get('SERVER_ENVIRONMENT').startswith('DEVELOPMENT')`. So clearly it's looking at the history of the file in some way.

**Comment by aeschli** [comment]
You are talking about errors in the problems view?

Out of the box, VSCode does no validation of Python. Can you find out which extension creates the problems? I assume it's the Python extension? Can you file the issue there? https://github.com/Microsoft/vscode-python
