### ISSUE TITLE
Copy character from the line above cursor

### ISSUE THREAD

**Issue by lubrogit** [microsoft/vscode#103032]
It would be nice to have a built-in function that copies the character from the line just above the current cursor position. I rely on this function since QEdit (later SemWare Editor TSE) and if not available, I create a macro, such as the following one:

"macros": {
        "copyCharFromLineAbove": [
            "cursorUp",
            "cursorRightSelect",
            "editor.action.clipboardCopyAction",
            "cursorLeft",
            "cursorDown",
            "editor.action.clipboardPasteAction",
        ]
    },

By a habit, I bound the macro to Ctrl+- (VK_OEM_MINUS 0xBD; the default .zoomOut is also on NumPad_Subtract key). 

There are two problems in the macro. 1 - The macro rewrites clipboard. 2 - The macro runs slower than the keyboard repeat (on Dell Precision with I7 2.9GHz), and copying must be done by a separate keyboard press for each character.

If anyone has a solution, please, make a notice.

Luděk Brož

**Comment by usernamehw** [comment]
Pretty specific feature. I think what you want is to create an extension. It takes maybe 5-15 minutes to make a new one:

https://code.visualstudio.com/api/get-started/your-first-extension

The code would be something like:

```ts
vscode.commands.registerTextEditorCommand('copyCharAbove', editor => {
	const activeLine = editor.selection.active.line;
	const activeChar = editor.selection.active.character;
	const charAbove = editor.document.getText(new vscode.Range(activeLine - 1, activeChar, activeLine - 1, activeChar + 1));
	if (!charAbove) {
		vscode.window.showWarningMessage('No character above');
		return;
	}
	vscode.commands.executeCommand('editor.action.insertSnippet', {
		snippet: charAbove,
	});
});
```
