### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by BrandX3** [microsoft/vscode#103089]
Issue Type: <b>Bug</b>

Attempt to update when the gear icon in bottom left indicates that an update is available.

here's the log file:

Jul 22 05:10:42.864 INFO Starting: C:\Program Files\Microsoft VS Code\Code.exe, false
Jul 22 05:10:42.868 INFO Checking for running Code.exe processes... (attempt 1)
Jul 22 05:10:42.876 INFO Code.exe is running, wait a bit
Jul 22 05:10:43.376 INFO Checking for running Code.exe processes... (attempt 2)
Jul 22 05:10:43.384 INFO Code.exe is running, wait a bit
Jul 22 05:10:43.886 INFO Checking for running Code.exe processes... (attempt 3)
Jul 22 05:10:43.894 INFO Code.exe is running, wait a bit
Jul 22 05:10:44.394 INFO Checking for running Code.exe processes... (attempt 4)
Jul 22 05:10:44.404 INFO Code.exe is running, wait a bit
Jul 22 05:10:44.905 INFO Checking for running Code.exe processes... (attempt 5)
Jul 22 05:10:44.913 INFO Code.exe is running, wait a bit
Jul 22 05:10:45.414 INFO Checking for running Code.exe processes... (attempt 6)
Jul 22 05:10:45.421 INFO Code.exe is running, wait a bit
Jul 22 05:10:45.922 INFO Checking for running Code.exe processes... (attempt 7)
Jul 22 05:10:45.930 INFO Code.exe is running, wait a bit
Jul 22 05:10:46.432 INFO Checking for running Code.exe processes... (attempt 8)
Jul 22 05:10:46.442 INFO Code.exe is running, wait a bit
Jul 22 05:10:46.943 INFO Checking for running Code.exe processes... (attempt 9)
Jul 22 05:10:46.951 INFO Code.exe is running, wait a bit
Jul 22 05:10:47.452 INFO Checking for running Code.exe processes... (attempt 10)
Jul 22 05:10:47.459 INFO Code.exe is running, wait a bit
Jul 22 05:10:47.961 INFO Checking for running Code.exe processes... (attempt 11)
Jul 22 05:10:47.969 INFO Code.exe is running, wait a bit
Jul 22 05:10:48.470 INFO Checking for running Code.exe processes... (attempt 12)
Jul 22 05:10:48.478 INFO Code.exe is running, wait a bit
Jul 22 05:10:48.978 INFO Checking for running Code.exe processes... (attempt 13)
Jul 22 05:10:48.987 INFO Code.exe is running, wait a bit
Jul 22 05:10:49.488 INFO Checking for running Code.exe processes... (attempt 14)
Jul 22 05:10:49.497 INFO Code.exe is running, wait a bit
Jul 22 05:10:49.998 INFO Checking for running Code.exe processes... (attempt 15)
Jul 22 05:10:50.007 INFO Code.exe is running, wait a bit
Jul 22 05:10:50.507 INFO Checking for running Code.exe processes... (attempt 16)
Jul 22 05:10:50.515 INFO Code.exe is running, wait a bit
Jul 22 05:10:51.016 INFO Checking for running Code.exe processes... (attempt 17)
Jul 22 05:10:51.024 INFO Code.exe is running, wait a bit
Jul 22 05:10:51.525 INFO Checking for running Code.exe processes... (attempt 18)
Jul 22 05:10:51.534 INFO Code.exe is running, wait a bit
Jul 22 05:10:52.036 INFO Checking for running Code.exe processes... (attempt 19)
Jul 22 05:10:52.045 INFO Code.exe is running, wait a bit
Jul 22 05:10:52.545 INFO Checking for running Code.exe processes... (attempt 20)
Jul 22 05:10:52.554 INFO Code.exe is running, wait a bit
Jul 22 05:10:53.055 INFO Checking for running Code.exe processes... (attempt 21)
Jul 22 05:10:53.064 INFO Code.exe is running, wait a bit
Jul 22 05:10:53.565 INFO Checking for running Code.exe processes... (attempt 22)
Jul 22 05:10:53.573 INFO Code.exe is running, wait a bit
Jul 22 05:10:54.074 INFO Checking for running Code.exe processes... (attempt 23)
Jul 22 05:10:54.082 INFO Code.exe is running, wait a bit
Jul 22 05:10:54.583 INFO Checking for running Code.exe processes... (attempt 24)
Jul 22 05:10:54.592 INFO Code.exe is running, wait a bit
Jul 22 05:10:55.093 INFO Checking for running Code.exe processes... (attempt 25)
Jul 22 05:10:55.102 INFO Code.exe is running, wait a bit
Jul 22 05:10:55.603 INFO Checking for running Code.exe processes... (attempt 26)
Jul 22 05:10:55.612 INFO Code.exe is running, wait a bit
Jul 22 05:10:56.113 INFO Checking for running Code.exe processes... (attempt 27)
Jul 22 05:10:56.121 INFO Code.exe is running, wait a bit
Jul 22 05:10:56.622 INFO Checking for running Code.exe processes... (attempt 28)
Jul 22 05:10:56.630 INFO Code.exe is running, wait a bit
Jul 22 05:10:57.131 INFO Checking for running Code.exe processes... (attempt 29)
Jul 22 05:10:57.140 INFO Code.exe is running, wait a bit
Jul 22 05:10:57.641 INFO Checking for running Code.exe processes... (attempt 30)
Jul 22 05:10:57.650 INFO Code.exe is running, wait a bit
Jul 22 05:10:58.150 INFO Checking for running Code.exe processes... (attempt 31)
Jul 22 05:10:58.159 INFO Code.exe is running, wait a bit
Jul 22 05:10:58.660 INFO Checking for running Code.exe processes... (attempt 32)
Jul 22 05:10:58.671 INFO Code.exe is running, wait a bit
Jul 22 05:10:59.172 INFO Checking for running Code.exe processes... (attempt 33)
Jul 22 05:10:59.187 INFO Code.exe is running, wait a bit
Jul 22 05:10:59.688 INFO Checking for running Code.exe processes... (attempt 34)
Jul 22 05:10:59.700 INFO Code.exe is running, wait a bit
Jul 22 05:11:00.212 INFO Checking for running Code.exe processes... (attempt 35)
Jul 22 05:11:00.235 INFO Code.exe is running, wait a bit
Jul 22 05:11:00.736 INFO Checking for running Code.exe processes... (attempt 36)
Jul 22 05:11:00.745 INFO Code.exe is running, wait a bit
Jul 22 05:11:01.246 INFO Checking for running Code.exe processes... (attempt 37)
Jul 22 05:11:01.254 INFO Code.exe is running, wait a bit
Jul 22 05:11:01.756 INFO Checking for running Code.exe processes... (attempt 38)
Jul 22 05:11:01.763 INFO Code.exe is running, wait a bit
Jul 22 05:11:02.265 INFO Checking for running Code.exe processes... (attempt 39)
Jul 22 05:11:02.273 INFO Code.exe is running, wait a bit
Jul 22 05:11:02.774 INFO Checking for running Code.exe processes... (attempt 40)
Jul 22 05:11:02.785 INFO Code.exe is running, wait a bit
Jul 22 05:11:03.286 INFO Checking for running Code.exe processes... (attempt 41)
Jul 22 05:11:03.294 INFO Code.exe is running, wait a bit
Jul 22 05:11:03.796 INFO Checking for running Code.exe processes... (attempt 42)
Jul 22 05:11:03.805 INFO Code.exe is running, wait a bit
Jul 22 05:11:04.305 INFO Checking for running Code.exe processes... (attempt 43)
Jul 22 05:11:04.313 INFO Code.exe is running, wait a bit
Jul 22 05:11:04.815 INFO Checking for running Code.exe processes... (attempt 44)
Jul 22 05:11:04.825 INFO Code.exe is running, wait a bit
Jul 22 05:11:05.326 INFO Checking for running Code.exe processes... (attempt 45)
Jul 22 05:11:05.334 INFO Code.exe is running, wait a bit
Jul 22 05:11:05.836 INFO Checking for running Code.exe processes... (attempt 46)
Jul 22 05:11:05.846 INFO Code.exe is running, wait a bit
Jul 22 05:11:06.346 INFO Checking for running Code.exe processes... (attempt 47)
Jul 22 05:11:06.354 INFO Code.exe is running, wait a bit
Jul 22 05:11:06.856 INFO Checking for running Code.exe processes... (attempt 48)
Jul 22 05:11:06.867 INFO Code.exe is running, wait a bit
Jul 22 05:11:07.368 INFO Checking for running Code.exe processes... (attempt 49)
Jul 22 05:11:07.376 INFO Code.exe is running, wait a bit
Jul 22 05:11:07.877 INFO Checking for running Code.exe processes... (attempt 50)
Jul 22 05:11:07.885 INFO Code.exe is running, wait a bit
Jul 22 05:11:08.386 INFO Checking for running Code.exe processes... (attempt 51)
Jul 22 05:11:08.394 INFO Code.exe is running, wait a bit
Jul 22 05:11:08.895 INFO Checking for running Code.exe processes... (attempt 52)
Jul 22 05:11:08.902 INFO Code.exe is running, wait a bit
Jul 22 05:11:09.403 INFO Checking for running Code.exe processes... (attempt 53)
Jul 22 05:11:09.410 INFO Code.exe is running, wait a bit
Jul 22 05:11:09.912 INFO Checking for running Code.exe processes... (attempt 54)
Jul 22 05:11:09.920 INFO Code.exe is running, wait a bit
Jul 22 05:11:10.421 INFO Checking for running Code.exe processes... (attempt 55)
Jul 22 05:11:10.429 INFO Code.exe is running, wait a bit
Jul 22 05:11:10.929 INFO Checking for running Code.exe processes... (attempt 56)
Jul 22 05:11:10.937 INFO Code.exe is running, wait a bit
Jul 22 05:11:11.438 INFO Checking for running Code.exe processes... (attempt 57)
Jul 22 05:11:11.446 INFO Code.exe is running, wait a bit
Jul 22 05:11:11.948 INFO Checking for running Code.exe processes... (attempt 58)
Jul 22 05:11:11.956 INFO Code.exe is running, wait a bit
Jul 22 05:11:12.457 INFO Checking for running Code.exe processes... (attempt 59)
Jul 22 05:11:12.464 INFO Code.exe is running, wait a bit
Jul 22 05:11:12.966 INFO Checking for running Code.exe processes... (attempt 60)
Jul 22 05:11:12.978 INFO Gave up waiting for Code.exe to exit
Jul 22 05:11:12.979 INFO Checking for possible conflicting running processes... (attempt 1)
Jul 22 05:11:12.990 INFO Kill process if found: 3984, Code.exe
Jul 22 05:11:12.992 INFO Kill process if found: 10876, Code.exe
Jul 22 05:11:12.992 INFO Kill process if found: 33864, Code.exe
Jul 22 05:11:12.992 INFO Kill process if found: 10028, Code.exe
Jul 22 05:11:12.992 INFO Kill process if found: 34592, Code.exe
Jul 22 05:11:12.992 INFO Kill process if found: 25980, Code.exe
Jul 22 05:11:12.992 INFO Kill process if found: 29016, Code.exe
Jul 22 05:11:12.992 INFO Kill process if found: 24892, Code.exe
Jul 22 05:11:12.992 INFO Kill process if found: 34752, Code.exe
Jul 22 05:11:12.992 INFO Found Code.exe running, pid 34752, attempting to kill...
Jul 22 05:11:12.993 INFO Successfully killed Code.exe, pid 34752
Jul 22 05:11:12.993 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:12.993 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:12.993 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:12.993 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:12.993 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:12.993 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:12.993 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:12.993 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.044 INFO Checking for possible conflicting running processes... (attempt 2)
Jul 22 05:11:13.053 INFO Kill process if found: 3984, Code.exe
Jul 22 05:11:13.053 INFO Kill process if found: 10876, Code.exe
Jul 22 05:11:13.053 INFO Kill process if found: 33864, Code.exe
Jul 22 05:11:13.053 INFO Kill process if found: 10028, Code.exe
Jul 22 05:11:13.053 INFO Kill process if found: 34592, Code.exe
Jul 22 05:11:13.053 INFO Kill process if found: 25980, Code.exe
Jul 22 05:11:13.053 INFO Kill process if found: 29016, Code.exe
Jul 22 05:11:13.054 INFO Kill process if found: 24892, Code.exe
Jul 22 05:11:13.054 INFO Kill process if found: 16884, Code.exe
Jul 22 05:11:13.054 INFO Found Code.exe running, pid 16884, attempting to kill...
Jul 22 05:11:13.054 INFO Successfully killed Code.exe, pid 16884
Jul 22 05:11:13.054 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.054 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.054 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.054 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.055 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.055 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.055 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.055 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.255 INFO Checking for possible conflicting running processes... (attempt 3)
Jul 22 05:11:13.264 INFO Kill process if found: 3984, Code.exe
Jul 22 05:11:13.264 INFO Kill process if found: 10876, Code.exe
Jul 22 05:11:13.264 INFO Kill process if found: 33864, Code.exe
Jul 22 05:11:13.264 INFO Kill process if found: 10028, Code.exe
Jul 22 05:11:13.264 INFO Kill process if found: 34592, Code.exe
Jul 22 05:11:13.265 INFO Kill process if found: 25980, Code.exe
Jul 22 05:11:13.265 INFO Kill process if found: 29016, Code.exe
Jul 22 05:11:13.265 INFO Kill process if found: 24892, Code.exe
Jul 22 05:11:13.265 INFO Kill process if found: 8712, Code.exe
Jul 22 05:11:13.265 INFO Found Code.exe running, pid 8712, attempting to kill...
Jul 22 05:11:13.265 INFO Successfully killed Code.exe, pid 8712
Jul 22 05:11:13.265 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.265 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.265 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.265 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.265 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.266 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.266 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.266 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.715 INFO Checking for possible conflicting running processes... (attempt 4)
Jul 22 05:11:13.725 INFO Kill process if found: 3984, Code.exe
Jul 22 05:11:13.725 INFO Kill process if found: 10876, Code.exe
Jul 22 05:11:13.725 INFO Kill process if found: 33864, Code.exe
Jul 22 05:11:13.725 INFO Kill process if found: 10028, Code.exe
Jul 22 05:11:13.725 INFO Kill process if found: 34592, Code.exe
Jul 22 05:11:13.725 INFO Kill process if found: 25980, Code.exe
Jul 22 05:11:13.725 INFO Kill process if found: 29016, Code.exe
Jul 22 05:11:13.725 INFO Kill process if found: 24892, Code.exe
Jul 22 05:11:13.726 INFO Kill process if found: 7924, Code.exe
Jul 22 05:11:13.726 INFO Found Code.exe running, pid 7924, attempting to kill...
Jul 22 05:11:13.726 INFO Successfully killed Code.exe, pid 7924
Jul 22 05:11:13.726 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.726 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.726 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.726 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.726 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.726 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.726 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:13.727 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:14.527 INFO Checking for possible conflicting running processes... (attempt 5)
Jul 22 05:11:14.537 INFO Kill process if found: 3984, Code.exe
Jul 22 05:11:14.537 INFO Kill process if found: 10876, Code.exe
Jul 22 05:11:14.537 INFO Kill process if found: 33864, Code.exe
Jul 22 05:11:14.537 INFO Kill process if found: 10028, Code.exe
Jul 22 05:11:14.537 INFO Kill process if found: 34592, Code.exe
Jul 22 05:11:14.537 INFO Kill process if found: 25980, Code.exe
Jul 22 05:11:14.537 INFO Kill process if found: 29016, Code.exe
Jul 22 05:11:14.537 INFO Kill process if found: 24892, Code.exe
Jul 22 05:11:14.538 INFO Kill process if found: 948, Code.exe
Jul 22 05:11:14.538 INFO Found Code.exe running, pid 948, attempting to kill...
Jul 22 05:11:14.538 INFO Successfully killed Code.exe, pid 948
Jul 22 05:11:14.538 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:14.538 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:14.538 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:14.538 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:14.538 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:14.538 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:14.538 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:14.538 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:15.788 INFO Checking for possible conflicting running processes... (attempt 6)
Jul 22 05:11:15.797 INFO Kill process if found: 3984, Code.exe
Jul 22 05:11:15.797 INFO Kill process if found: 10876, Code.exe
Jul 22 05:11:15.797 INFO Kill process if found: 33864, Code.exe
Jul 22 05:11:15.797 INFO Kill process if found: 10028, Code.exe
Jul 22 05:11:15.797 INFO Kill process if found: 34592, Code.exe
Jul 22 05:11:15.797 INFO Kill process if found: 25980, Code.exe
Jul 22 05:11:15.798 INFO Kill process if found: 29016, Code.exe
Jul 22 05:11:15.798 INFO Kill process if found: 24892, Code.exe
Jul 22 05:11:15.798 INFO Kill process if found: 17804, Code.exe
Jul 22 05:11:15.798 INFO Found Code.exe running, pid 17804, attempting to kill...
Jul 22 05:11:15.798 INFO Successfully killed Code.exe, pid 17804
Jul 22 05:11:15.798 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:15.798 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:15.799 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:15.799 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:15.799 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:15.799 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:15.799 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:15.799 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:17.599 INFO Checking for possible conflicting running processes... (attempt 7)
Jul 22 05:11:17.607 INFO Kill process if found: 3984, Code.exe
Jul 22 05:11:17.607 INFO Kill process if found: 10876, Code.exe
Jul 22 05:11:17.607 INFO Kill process if found: 33864, Code.exe
Jul 22 05:11:17.607 INFO Kill process if found: 10028, Code.exe
Jul 22 05:11:17.607 INFO Kill process if found: 34592, Code.exe
Jul 22 05:11:17.607 INFO Kill process if found: 25980, Code.exe
Jul 22 05:11:17.607 INFO Kill process if found: 29016, Code.exe
Jul 22 05:11:17.607 INFO Kill process if found: 24892, Code.exe
Jul 22 05:11:17.607 INFO Kill process if found: 25696, Code.exe
Jul 22 05:11:17.607 INFO Found Code.exe running, pid 25696, attempting to kill...
Jul 22 05:11:17.607 INFO Successfully killed Code.exe, pid 25696
Jul 22 05:11:17.608 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:17.608 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:17.608 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:17.608 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:17.608 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:17.608 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:17.608 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:17.608 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:20.058 INFO Checking for possible conflicting running processes... (attempt 8)
Jul 22 05:11:20.065 INFO Kill process if found: 3984, Code.exe
Jul 22 05:11:20.065 INFO Kill process if found: 10876, Code.exe
Jul 22 05:11:20.066 INFO Kill process if found: 33864, Code.exe
Jul 22 05:11:20.066 INFO Kill process if found: 10028, Code.exe
Jul 22 05:11:20.066 INFO Kill process if found: 34592, Code.exe
Jul 22 05:11:20.066 INFO Kill process if found: 25980, Code.exe
Jul 22 05:11:20.066 INFO Kill process if found: 29016, Code.exe
Jul 22 05:11:20.066 INFO Kill process if found: 24892, Code.exe
Jul 22 05:11:20.066 INFO Kill process if found: 8116, Code.exe
Jul 22 05:11:20.066 INFO Found Code.exe running, pid 8116, attempting to kill...
Jul 22 05:11:20.066 INFO Successfully killed Code.exe, pid 8116
Jul 22 05:11:20.066 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:20.066 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:20.067 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:20.067 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:20.067 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:20.067 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:20.067 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:20.067 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:23.267 INFO Checking for possible conflicting running processes... (attempt 9)
Jul 22 05:11:23.275 INFO Kill process if found: 3984, Code.exe
Jul 22 05:11:23.275 INFO Kill process if found: 10876, Code.exe
Jul 22 05:11:23.275 INFO Kill process if found: 33864, Code.exe
Jul 22 05:11:23.275 INFO Kill process if found: 10028, Code.exe
Jul 22 05:11:23.275 INFO Kill process if found: 34592, Code.exe
Jul 22 05:11:23.275 INFO Kill process if found: 25980, Code.exe
Jul 22 05:11:23.276 INFO Kill process if found: 29016, Code.exe
Jul 22 05:11:23.276 INFO Kill process if found: 24892, Code.exe
Jul 22 05:11:23.276 INFO Kill process if found: 1384, Code.exe
Jul 22 05:11:23.276 INFO Found Code.exe running, pid 1384, attempting to kill...
Jul 22 05:11:23.276 INFO Successfully killed Code.exe, pid 1384
Jul 22 05:11:23.276 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:23.276 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:23.276 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:23.276 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:23.277 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:23.277 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:23.277 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:23.277 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:27.327 INFO Checking for possible conflicting running processes... (attempt 10)
Jul 22 05:11:27.341 INFO Kill process if found: 3984, Code.exe
Jul 22 05:11:27.341 INFO Kill process if found: 10876, Code.exe
Jul 22 05:11:27.341 INFO Kill process if found: 33864, Code.exe
Jul 22 05:11:27.341 INFO Kill process if found: 10028, Code.exe
Jul 22 05:11:27.341 INFO Kill process if found: 34592, Code.exe
Jul 22 05:11:27.341 INFO Kill process if found: 25980, Code.exe
Jul 22 05:11:27.341 INFO Kill process if found: 29016, Code.exe
Jul 22 05:11:27.342 INFO Kill process if found: 24892, Code.exe
Jul 22 05:11:27.342 INFO Kill process if found: 25424, Code.exe
Jul 22 05:11:27.342 INFO Found Code.exe running, pid 25424, attempting to kill...
Jul 22 05:11:27.342 INFO Successfully killed Code.exe, pid 25424
Jul 22 05:11:27.342 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:27.342 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:27.343 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:27.343 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:27.343 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:27.343 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:27.343 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:27.344 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:32.343 INFO Checking for possible conflicting running processes... (attempt 11)
Jul 22 05:11:32.355 INFO Kill process if found: 3984, Code.exe
Jul 22 05:11:32.355 INFO Kill process if found: 10876, Code.exe
Jul 22 05:11:32.355 INFO Kill process if found: 33864, Code.exe
Jul 22 05:11:32.355 INFO Kill process if found: 10028, Code.exe
Jul 22 05:11:32.355 INFO Kill process if found: 34592, Code.exe
Jul 22 05:11:32.356 INFO Kill process if found: 25980, Code.exe
Jul 22 05:11:32.356 INFO Kill process if found: 29016, Code.exe
Jul 22 05:11:32.356 INFO Kill process if found: 24892, Code.exe
Jul 22 05:11:32.356 INFO Kill process if found: 18428, Code.exe
Jul 22 05:11:32.356 INFO Found Code.exe running, pid 18428, attempting to kill...
Jul 22 05:11:32.356 INFO Successfully killed Code.exe, pid 18428
Jul 22 05:11:32.356 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:32.357 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:32.357 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:32.357 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:32.357 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:32.357 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:32.357 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:11:32.358 WARN Kill error Failed to open process: Access is denied.

Jul 22 05:12:24.035 ERRO Failed to open process: Access is denied.

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.30GB free)|
|Process Argv|C:\Users\seth.watt\AppData\Local\Temp\vscode-inno-updater-1595419842.log|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
kixtart|cya|0.0.1
xml|Dot|2.5.1
json-tools|eri|1.0.2
gc-excelviewer|Gra|3.0.39
beautify|Hoo|1.5.0
vscode-elixir|mjm|1.1.0
csharp|ms-|1.22.1
mssql|ms-|1.9.0
hexeditor|ms-|1.1.0
js-debug-nightly|ms-|2020.7.2117
powershell|ms-|2020.6.0
vs-keybindings|ms-|0.2.0
printcode|nob|3.0.0
edi-x12-support|Sil|1.1.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
