### ISSUE TITLE
nvm is not compatible with the npm config "prefix" option: currently set to "" on Mac OX

### ISSUE THREAD

**Issue by aftershock-teial** [microsoft/vscode#103049]
Latest update broke my ability to use npm from the integrated terminal.

I get this error message:
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v10.13.0 --silent` to unset it.

I tried updating these settings, but the error persists.  Please advise    

"terminal.integrated.shellArgs.osx": ["-l"],

**Comment by Tyriar** [comment]
https://code.visualstudio.com/docs/editor/integrated-terminal#_why-is-nvm-complaining-about-a-prefix-option-when-the-integrated-terminal-is-launched

**Comment by aftershock-teial** [comment]
Hello,

I did try that and it didn't work for me.

Thanks,
Teial

**Comment by Tyriar** [comment]
Issues like this with nvm are related to your environment, you will need to investigate further yourself.

**Comment by rublev** [comment]
> Issues like this with nvm are related to your environment, you will need to investigate further yourself.

Unacceptable answer TBH. I have the same issue and have been "investigating" for 8 hours now :) I am ready to blow out my brains. I have literally no other solutions. [This guy](https://stackoverflow.com/questions/62922875/vs-code-integrated-terminal-throws-cannot-find-module-nvm-is-not-compatible) has the same issue.

I have uninstalled node/nvm/npm/homebrew. Reinstalled all and every combination suggested under the sun. I simply can't get node working in my terminal. There is an obvious error somewhere.

![image](https://user-images.githubusercontent.com/470273/88326799-6c57c780-ccf4-11ea-941e-38a4b8bb3f67.png)

`Cannot find module '"/Users/rublev/Library/Application'` - there is a mission `"`

**Comment by aftershock-teial** [comment]
I totally agree! I did all of those things.  Nothing in my environment
related to npm or node has changed recently.  This issue started happening
after the last June release.

**Comment by Tyriar** [comment]
What happens when you run these in the VS Code terminal and an external terminal where you're not seeing the issue?

```
echo $PATH # sanitize this if necessary
which node
which npm
which nvm
```

Does changing `terminal.integrated.shellArgs.osx` to `["-l"]` or `[]` change this?
