### ISSUE TITLE
Auto-complete popup puts redundant "item" prefix per suggested code for screen readers

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#103095]
CC @isidorn

This issue has been also filed on [NVDA repo #11404](https://github.com/nvaccess/nvda/issues/11404#issuecomment-662043116), and confirmed that the fix has to be addressed on VSCode end.

## System Info

Version: 1.48.0-insider (system setup)
Commit: 0a7364f00514c46c9caceece15e1f82f82e3712f
Date: 2020-07-22T05:49:27.463Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Microsoft® Windows® Operating System Version 10.0.19041.1
NVDA v2020.1

## Steps to Reproduce:

1. With NVDA loaded, create any source code file in VSCode (e.g., test.py).
1. Try using code suggestion feature (e.g., type cl and press Ctrl+Space and arrow-down to find class keyword).

## Actual behavior:

NVDA and other screen readers (e.g., JAWS) keep announcing redundant prefix, "item," per suggested code in the auto-complete popup.

## Expected behavior:

It would be ideal to filter out this prefix for NVDA users to quickly navigate through suggested code items.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@jooyoungseo thanks for feedback. I have pushed a fix for this. You can try it out with vscode insiders from Wednesday and let us know if it is good for you.

**Comment by jooyoungseo** [comment]
Thanks very much @isidorn! I will try that out on Wednesday, and keep you posted.

**Comment by jooyoungseo** [comment]
I have confirmed that this issue has been resolved via the latest commit:

Version: 1.48.0-insider (system setup)
Commit: 15e798e081984a17eae00de91adf4479190d5ed2
Date: 2020-07-28T10:39:18.007Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Thanks very much again @isidorn for this fix!

**Comment by isidorn** [comment]
Great, thanks for letting us know. Adding verified label.
