### ISSUE TITLE
Go constants with omitted assignment are not syntax highlighted correctly

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#103050]
Reopening #76073 as the issue on the Go grammer repo was punted on since they don't seem to be interested in maintaining the Go TextMate grammer as they are migrating to a different engine for syntax highlighting in Atom. (https://github.com/atom/language-go/issues/173)

- VSCode Version: 1.47.2
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Open the following .go file in VS Code:
   ```go
   package foo

   const (
	   Value1 = iota
	   Value2
	   Value3
	   Value4
   )
   ```
2. `Value2`, `Value3` and `Value4` are not highlighted like `Value1`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Looks like issue has already been reported in the repo we get the Go grammar from: https://github.com/jeff-hykin/better-go-syntax/issues/6

**Comment by segevfiner** [comment]
Alright. Hope that one is indeed maintained 🤷‍♂️
