### ISSUE TITLE
Sources in the web worker extension host are offset

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103027]
If we have a compiled file like

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
const vscode = require("vscode");
```

This gets wrapped and executed in the runtime as

```js
(function anonymous(module,exports,require
) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
const vscode = require("vscode");
```

due to the `new Function`

https://github.com/microsoft/vscode/blob/786af3a8d0bc0221d979a9f22596fde825691729/src/vs/workbench/api/worker/extHostExtensionService.ts#L54

Offsets here are a problem, since it means the sourcemap is no longer correct. It can deal with adjusting these, but to do so I need to detect when functions are loaded like this. Here's a sample of the 'scriptParsed' event I get for that source:

```json
{
  "endColumn": 2,
  "endLine": 29,
  "executionContextId": 1,
  "hasSourceURL": true,
  "hash": "35cb73df719944051de479b21f2a168e007ac816",
  "isLiveEdit": false,
  "isModule": false,
  "length": 1586,
  "scriptId": "7",
  "sourceMapURL": "extension.js.map",
  "stackTrace": {
    "callFrames": [
      {
        "columnNumber": 481,
        "functionName": "_loadCommonJSModule",
        "lineNumber": 846,
        "scriptId": "5",
        "url": "file:///C:/Users/Connor/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/services/extensions/worker/extensionHostWorker.js"
      }
    ],
    "parentId": {
      "id": "21"
    }
  },
  "startColumn": 0,
  "startLine": 0,
  "url": "file:///c:/Users/Connor/Documents/Github/vscode-js-debug/demos/extension/out/extension.js"
}
```

The simplest approach I think would be to add a query string or fragment on the `sourceURL` like `extension.js?isVsCodeWebWorkerExtension`, which I can detect and then apply the appropriate offsets needed. Right now I'm pattern-matching against the call frame in the stackTrace, but this is considerably more fragile.

(note: it's not safe to globally apply the offset to _all_ `new Function`s, since some build systems generate functions and produce adjusted sourcemaps by default)

**Comment by alexdima** [comment]
Thank you, that makes good sense!

I've pushed a change where the sourceURL should now have a fragment `#vscode-extension` at the end.
