### ISSUE TITLE
Add a "skip this version" option

### ISSUE THREAD

**Issue by yoyoyoohh** [microsoft/vscode#103094]
aaHi, I was wondering if a "skip this version" option is possible. Because when there is a new release whose new features are unnecessary for me, I would not choose to update it, but vscode would pop up a "there is an available update" notification every time I opened it, which is annoying. I know that I can turn off the update notification permanently, but I am afraid of losing some important updates in the future, so I hope that there could be a "skip this version" button, resulting in not popping up the notification until another release is available.

**Comment by joaomoreno** [comment]
There is no such option, but you can change updates to be manually applied by setting `update.mode = manual`. That way updates are only applied if you run the `Check for updates` action.
