### ISSUE TITLE
Cannot turn on settings sync

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#103005]
Version: 1.48.0-insider (user setup)
Commit: 6c21258b65e4c9448323c930fabb1ac6b734c597
Date: 2020-07-20T05:33:03.267Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:
1. Turn on settings sync
`Error while starting Sync: Cannot read property 'version' of null`

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
To verify:

- Machine 1: Make sure you do not have keybindings.json file (Delete it if you have). Have some settings (for eg: theme)
- Machine 1: Turn on Sync
- Machine 1: Turn off Sync (only on this machine)
- Machine 2: Start fresh (use new user data dir and extensions dir)
- Machine 2: Turn on Sync
- Machine 2: Change theme and sync
- Machine 1: Turn on Sync and you will see a dialog to replace/merge. Choose Replace local.

Verify that Replace Local succeeds and sync is turned on without errors.
