### ISSUE TITLE
Syntax highlighting stops working when TypeScript keywords appear as object keys

### ISSUE THREAD

**Issue by takumif** [Microsoft/vscode#1030]
![screen shot 2015-12-04 at 5 22 50 pm](https://cloud.githubusercontent.com/assets/5505433/11602866/bb196534-9aab-11e5-9c22-82d8ea20ab56.png)

When a keyword such as `class` appears as a key in an object, syntax highlighting for method declaration no longer works for the rest of the file.

```typescript
class A {
	private getSomeObj() {
		var obj = {
			class: 'Class Name',
			id: 1
		};
		return obj;
	}

	private someOtherMethod() {
		return 0;
	}
}
```

**Comment by aeschli** [comment]
Sublime shows the same problem, so it looks like a problem in the grammar, not our textmate engine.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#21
