### ISSUE TITLE
Tasks are not discovered in the latest Insiders

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103039]
```
Version: 1.48.0-insider (user setup)
Commit: eb1ca267d6a478734bd7f3d629ac9b80926ee9d1
Date: 2020-07-21T12:42:19.326Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
```

1. On any folder, run `Tasks: Configure Task`
1. Pick any task or Other
1. `Tasks: Run Task`
1. Nothing appears

![](https://memes.peet.io/img/20-07-a0a6be02-5d33-4549-accc-ad6c77c56c64.png)

This also prevent debugging with a preLaunchTask (it's not just UI)

**Comment by alexr00** [comment]
Is this with a remote setup? I can't get it to repro.

**Comment by connor4312** [comment]
It's in a local setup -- I continue to see the issue after updating VS Code this morning. No errors in the console log. Let me know if there's anywhere I should set breakpoints to try to debug.

**Comment by alexr00** [comment]
Is there anything in the output panel under Tasks?

**Comment by connor4312** [comment]
ah, there we go: one line

```
Warning: npm tasks are unavailable in the current environment.
```

**Comment by alexr00** [comment]
Talked offline, and this is happening because `WorkerExtHostTask` is getting loaded. This doesn't need to happen when `WorkerExtHostTask` is loaded.
