### ISSUE TITLE
'${workspaceFolder}' can not be resolved in a multi folder workspace - While using Node JS auto attach debugger

### ISSUE THREAD

**Issue by ep1cman** [microsoft/vscode#103099]
- VSCode Version: 1.47
- OS Version: Mac OS 10.15.5

Looks like there has been a a regression and the issue occurs again with the latest release
See here: https://github.com/microsoft/vscode/issues/94725
Downgrading to 1.46 fixes and it works as expected

**Comment by AskAlice** [comment]
I'm getting this. Probably related to ms-vscode.node-debug as seen in #94725

**Comment by joscarras** [comment]
Same here with 1.47.2

**Comment by AskAlice** [comment]
switch your type to `pwa-node`, seems to fix it, though there are some configuration quirks that don't seem to translate over

**Comment by ep1cman** [comment]
How do I set that for the auto attach debugger? I use to be able just run commands in the built in terminal rather than via launch.json and it would allow me to debug.

**Comment by AskAlice** [comment]
@ep1cman - i mentioned your above comment here: 103099#issuecomment-665195383

**Comment by JWess** [comment]
I'm having the same issue with auto-attach not working on 1.47.3

**Comment by connor4312** [comment]
This will be fixed in the upcoming stable release next week, and also available in the next VS Code Insiders
