### ISSUE TITLE
Redirecting to class instantiated Method from Different class

### ISSUE THREAD

**Issue by rohitkrmishra** [microsoft/vscode#103007]
Team, I would suggest it would make the developer job easy if we can provide this feature - Allowing redirecting to the instantiated class's method definition:
Code Snip:
```
ApexClassName classInstance = new ApexClassName();
classInstance.methodName(Parameters);
```
For example this snippet is used in different class say ApexClassName2, so on going to definition for the above method methodName(Parameters), It should open that method in  new tab.

Please let me know if you need more details.
Thanks!

**Comment by jrieken** [comment]
> so on going to definition for the above method methodName(Parameters), It should open that method in new tab.

And it doesn't do that? What happens instead?

**Comment by rohitkrmishra** [comment]
It shows **No definition found for '<method name>'**

**Comment by jrieken** [comment]
and what language is that? what extension are you using for it?

**Comment by rohitkrmishra** [comment]
Language: Salesforce's Apex. Extension name: Apex, Salesforce Extension Pack
