### ISSUE TITLE
Allow to suppress confirmation of multi-file undo for custom editors

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode#103071]
Our team develops a custom editor that has to work with two strongly related files at once (think of a `.xaml.cs` and a `.xaml` file in WPF; or a `.cs` and a `.designer.cs` in WinForms).

One major difficulty is that when a user requests to undo an edit that spans multiple files (say, adding an button on a form that also adds some boilerplate to the `.cs` file), they get prompted for confirmation. I would like to be able to suppress that prompt.

Or please tell me if there's a more proper way to build editors that work with two text files at once (preferably, without having to reimplement the undo/redo text edit logic).

**Comment by alexdima** [comment]
@iliazeus What vscode APIs are you currently using? Do you have a simple sample?
