### ISSUE TITLE
Provide a warning when launching browsers user data directories where a browser is already running

### ISSUE THREAD

**Issue by JSchatral** [microsoft/vscode#103083]
We
Issue Type: <b>Bug</b>

Unable to debug two different applications at the same time - Error message: Unable to attach to browser. In version 1.47.1 there was another bug in the debugger, but the simultaneous debugging of two applications was still possible - now in 1.47.2 the other bug in the debugger is out, but unfortunately the simultaneous debugger of two different applications is no longer possible.
Scenario:
Two identical debug environments are set up for ports 3000 and 3001 in the launch.json file:
 "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http: // localhost: 3001",
            "webRoot": "$ {workspaceFolder}"
        }
    ]

Greetings from Germany. KIND REGARDS. J. Schatral

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz (4 x 2610)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.36GB (1.94GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.2
vscode-eslint|dba|2.1.8
emulate|Die|1.4.0
vscode-babel-coloring|dza|0.0.4
debugger-for-chrome|msj|4.12.9
vscode-react-native|msj|0.16.1
sass-indented|rob|1.5.1

</details>
 have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by connor4312** [comment]
js-debug shares the user profile directory per workspace, and trying to launch a browser with one already open for debugging is a known failure case. I think a fix for this would be to make the user data dir also include a hash of the launch configuration name to avoid this issue.

@JSchatral for the moment I believe you can get around this by manually specifying _different_ `userDataDir` properties for each of your two launch configurations.

**Comment by Paosder** [comment]
Is there any update for this? 
This issue produces useless `debug.log` file when it fails to attach debugger.

**Comment by connor4312** [comment]
The comment above describes the most common failure case:

> trying to launch a browser with one already open for debugging is a known failure

**Comment by connor4312** [comment]
In the linked issue I've made some changes to make this error more explicit and user-friendly. It turns out that when Chrome is running it creates a `lockfile` in the user data dir -- easy enough to detect, and although it's an implementation detail it should be free of false-positives (only false-negatives if they change how it works at a later point in time).

![](https://memes.peet.io/img/20-08-044c3b1a-f521-435e-8e71-d18ef9db54e7.png)

Closing the issue with this addition as there's been no more specific guidance from the original poster.

**Comment by isidorn** [comment]
@connor4312 do you have some concise steps to verify this? Thanks!

**Comment by connor4312** [comment]
1. Have a launch config like 

  ```
  {
    "configurations": [
      {
        "type": "pwa-chrome",
        "request": "launch",
        "url": "https://github.com",
        "name": "chrome2",
        "userDataDir": "${workspaceFolder}/.chrome-profile"
      },
      {
        "type": "pwa-chrome",
        "request": "launch",
        "url": "https://github.com",
        "name": "chrome1",
        "userDataDir": "${workspaceFolder}/.chrome-profile"
      }
    ]
  }
  ```

2. Debug chrome1. It should work
3. Debug chrome2. It should show a warning. If you 'debug anyway', it will fail to attach.

*also:* I realized that Chrome's lockfile on OSX is different. That will be fixed in the next Insiders, today this only works on Windows
