### ISSUE TITLE
TypeScript React conditional operator coloring issue

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10303]
- VSCode Version: Code - Insiders 1.5.0-insider (dde41be0231d6f8397d1da969ddab351f137b833, 2016-08-08T06:03:58.264Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Create `test.tsx` file with `const test = (true) ? <p>Broken Color</p> : <p>Also Broken Color</p>`
2. Issue:
![image](https://cloud.githubusercontent.com/assets/1723815/17481499/84c554f8-5d4b-11e6-8189-7d54c9d86645.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#239
