### ISSUE TITLE
Using picked in a QuickPickItem does not pre-select item in QuickPick

### ISSUE THREAD

**Issue by AttilioCapocchiani** [microsoft/vscode#103084]
- VSCode Version: 1.47.2
- OS Version: Mac OS 10.15 Catalina

Steps to Reproduce:

1. Write an extension for vscode
2. Include this code
```
const quickpick = await vscode.window.createQuickPick();
quickpick.canSelectMany = true;

const items: vscode.QuickPickItem[] = [
         { label: 'Item 1', picked: false },
         { label: 'Item 2', picked: true },
        ];

quickpick.items = items;
quickpick.show()
```

3. Item 2 does not look pre-selected during the quick pick

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Does your example work if you use the simpler showQuickPick API and set `canPickMany: true` in your QuickPickOptions?

Something like this (untested):
```
const picks = await vscode.window.showQuickPick([{ label: 'Item 1', picked: false }, { label: 'Item 2', picked: true }], { canPickMany: true });
```

**Comment by AttilioCapocchiani** [comment]
Thank you @gjsjohnmurray this is working.
