### ISSUE TITLE
Unable to log into Microsoft Account in Code

### ISSUE THREAD

**Issue by m-garb** [microsoft/vscode#103065]
Issue Type: <b>Bug</b>

Reinstalled Code after a Windows reinstall.  There is nowhere to sing in to my Microsoft account.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18362

**Comment by IllusionMH** [comment]
Are you looking for log in for settings sync?

If yes - it's still in [Insiders builds](https://code.visualstudio.com/insiders/) only. 
[Docs] (https://code.visualstudio.com/docs/editor/settings-sync)
