### ISSUE TITLE
Naming multiple terminals

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#103043]
From our NPS survey, one respondent brought up a feature suggestion for terminals. When using multiple terminals, it's difficult to navigate through them, so it would be helpful to be able to name terminals in the dropdown to make it easier to switch. 

![image](https://user-images.githubusercontent.com/9721254/88108098-21f01280-cb5d-11ea-94aa-45698068d3ab.png)

**Comment by gjsjohnmurray** [comment]
/duplicate of #22325

Try setting `"terminal.integrated.experimentalUseTitleEvent": true`

After doing this on my Windows platform, if I open a new cmd terminal and issue the command `title foo` that works.

**Comment by sana-ajani** [comment]
@gjsjohnmurray thanks! didn't realize that setting existed. doesn't work for me on my Mac with a bash shell though.
