### ISSUE TITLE
@connor4312 This problem is related to the user installer and it does not recognize Russian characters in the path. This is a big and fat minus for you as a specialist who delved into my problem, in the system installers the same trouble if the installation directory is Russian-language. How do you test your versions and roll them out to release in previous versions, there was no such bug. Not developers and do not understand who typed on the ad. I am extremely outraged I demand since this is not an open source project to bring the responsible person who on my question was responsible for negligent attitude to their work and for not knowing the basics of customer support. And if it was a developer, I would have run him down the neck. Who is faced with this problem, we make a system installation in a directory with an English name and will be happy to spend 30 minutes of their time solving other people's errors. The attitude to the product has deteriorated and to the response service, too.

### ISSUE THREAD

**Issue by Ritm57** [microsoft/vscode#103081]
@connor4312 This problem is related to the user installer and it does not recognize Russian characters in the path. This is a big and fat minus for you as a specialist who delved into my problem, in the system installers the same trouble if the installation directory is Russian-language. How do you test your versions and roll them out to release in previous versions, there was no such bug. Not developers and do not understand who typed on the ad. I am extremely outraged I demand since this is not an open source project to bring the responsible person who on my question was responsible for negligent attitude to their work and for not knowing the basics of customer support. And if it was a developer, I would have run him down the neck. Who is faced with this problem, we make a system installation in a directory with an English name and will be happy to spend 30 minutes of their time solving other people's errors. The attitude to the product has deteriorated and to the response service, too.

_Originally posted by @Ritm57 in https://github.com/microsoft/vscode/issues/102937#issuecomment-662346835_

**Comment by Ritm57** [comment]
Ahaha minusanul. Instead of minuses, Visual Studio doesn't have these bugs. And if you took on the project VS Code nedrazrabotchikov it is Yes every update bug is funny. Learn to write your code cleaner and explain you have an analyst and a programmer and a tester in your staff where they all looked when the release was pumped into production. Apparently excellent quality of the product.

**Comment by connor4312** [comment]
Please see https://github.com/microsoft/vscode-js-debug/issues/563#issuecomment-659592018 for a solution

/duplicate
