### ISSUE TITLE
All of my extensions (like Git and Python Language Server) takes several minutes to activate and run

### ISSUE THREAD

**Issue by nnethery** [microsoft/vscode#103096]
- VSCode Version: 1.47.2
- OS Version: macOS Catalina 10.15.5

Steps to Reproduce:

1. Open VSCode
2. Click the Git extension window on the left sidebar
3. Click a modified file in the working tree
4. Wait several minutes for the diff of the working tree to display

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

When I disable extensions, I see that the Git extension still loads, so this problem still occurs. 

It takes 4 minutes just to get a diff of the working tree to appear after I click the modified file in the sidebar. The Python extension is also extremely slow, and I can see the same performance with the Prettier and Docker extensions. I think it's safe to say all of my extensions are ridiculously sluggish. This has been happening to me since November 2019 and I can't keep ignoring it now. 

It's hardly even worth posting a video unless you want to see "Python extension loading" for 5 minutes. Even reinstalling VSCode and trying the Insiders build does not help.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide more info about performance according to tips in https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by nnethery** [comment]
This is a screenshot of me using the Git plugin to add this change to my stage. I am running VSCode with plugins disabled. 
<img width="1792" alt="Screen Shot 2020-07-28 at 3 05 18 PM" src="https://user-images.githubusercontent.com/11582381/88710016-f7193780-d0e3-11ea-8d87-324658122a06.png">

Attached is the `code --status` log for this VSCode window.
[status.txt](https://github.com/microsoft/vscode/files/4990579/status.txt)

Here is the CPU profile of me using the Git plugin to stage changes to the `create_distance_records.py` file. I turned off profiling after 10 min because it still didn't stage my changes in 10 minutes. 
[https://drive.google.com/file/d/1ml7WggCHwsGDhjyndwVHFgnwRsyD2IZA/view?usp=sharing](Profile)

**Comment by joaomoreno** [comment]
> When I disable extensions, I see that the Git extension still loads, so this problem still occurs.

Can you run with `code --disable-extensions` and see if the slowness still occurs, despite the fact that the Git extension still loads.

**Comment by nnethery** [comment]
> > When I disable extensions, I see that the Git extension still loads, so this problem still occurs.
> 
> Can you run with `code --disable-extensions` and see if the slowness still occurs, despite the fact that the Git extension still loads.

Yes, the slowness still occurs when I run VS Code with `code --disable-extensions`

**Comment by joaomoreno** [comment]
When running with `code --disable-extensions`, can you run `Developer: Show Running Extensions` and show me that view?

**Comment by alexdima** [comment]
@nnethery I looked at the CPU profile and I see something very bizzare around proxies / CAs:

![image](https://user-images.githubusercontent.com/5047891/89664230-1c255b80-d8d7-11ea-9dec-3ae301f11df2.png)

Are you using some weird proxying ?
