### ISSUE TITLE
TS server did not start

### ISSUE THREAD

**Issue by krishbha** [microsoft/vscode#103055]
Issue Type: <b>Bug</b>

Mac OS : 10.15.6 
It gave the warning on the console so reporting it

VS Code version: Code - Insiders 1.48.0-insider (6c21258b65e4c9448323c930fabb1ac6b734c597, 2020-07-20T05:27:28.503Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.1.0
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.8
git-extension-pack|don|0.1.3
githistory|don|0.6.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-azureappservice|ms-|0.17.0
azure-account|ms-|0.9.1
vscode-yaml|red|0.9.1
prophet|Sqr|1.3.21
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by mjbvz** [comment]
Please include the error message it generates  when it prompts you to report an issue

/needsMoreInfo
