### ISSUE TITLE
Folder

### ISSUE THREAD

**Issue by KPNoncheva19** [microsoft/vscode#103000]
Issue Type: <b>Feature Request</b>

Please make folders to can be deleate. There is no way to delete it I search everything but there is no way for this version I only can hide it, but I wanna to can be delete.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment]
/needsMoreInfo

Can you describe cases when you can't delete folders and what folders?
