### ISSUE TITLE
Git notification blocks extension integration test on Windows

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#103053]
![image](https://user-images.githubusercontent.com/876920/88116678-ffb2c080-cb6d-11ea-8186-9055bc396b87.png)

Not saying that I don't want to upgrade `git` but I'm surprised why a notification blocks the execution of whole integration tests. Especially when running integration tests without debugging, it fails silently.

**Comment by joaomoreno** [comment]
> blocks the execution of whole integration tests

Looking at the code, it appears the extension doesn't finish activating until that notification is _resolved_. Maybe that prevents a _ready_ event somewhere, since not all extensions would be activated until the notification is resolved. I decoupled that.
