### ISSUE TITLE
Option to change Regex Engine

### ISSUE THREAD

**Issue by sanjeev543** [microsoft/vscode#103079]
Currently Visio Code is supporting only  .NET regular expressions, can we have an option to change this?
Can we  switch to PCRE Regex Engine?

**Comment by IllusionMH** [comment]
VS Code doesn't use .NET regular expressions.
ripgrep (compatible with PCRE2) is already used for Find in files functionality (for not open editors) and JS engine used only for open editors.

Bringing ripgrep to replace JS engine requires separate investigation https://github.com/microsoft/vscode/issues/98076#issuecomment-631465518

/cc @roblourens

**Comment by roblourens** [comment]
Thanks for the excellent response @IllusionMH
