### ISSUE TITLE
Unknown error msg show in scm and problem

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#103070]
Issue Type: <b>Bug</b>

what is this?
![GIT_EROR](https://user-images.githubusercontent.com/1876302/88136834-c1280f00-cc1c-11ea-9a92-f8e9efec7dc1.png)

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.67GB (1.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
@sandy081 How can the user see from which extension the error comes from?

**Comment by sandy081** [comment]
Seems caused by an extension. To know which extension is generating errors please enable log level to trace and check the extension host logs.

- F1 > Developer: Set Log Level - Trace
- F1 > View: Open View > Log (Extension Host)

and file issue against the extension.
