### ISSUE TITLE
Debugger Keeps attaching itself when calling any npm package

### ISSUE THREAD

**Issue by apham-sy** [microsoft/vscode#103033]
Issue Type: <b>Bug</b>

**Summary**
On startup of a couple of projects, the debugger attaches itself in the terminal and i must exit with ctr + c. 
```
Debugger listening on ws://127.0.0.1:53672/c5f5e056-3a6f-4a18-b1ee-4d9195fc62b3
For help, see: https://nodejs.org/en/docs/inspector
```

and whenever I call anything with `npm` it triggers the same attachment. The same happens when a script calls npm. This happens when calling `sls, eslint, slss` which is installed under `/root/.nvm/versions/node/v12.14.1/bin/` and npm is installed under `/root/.nvm/versions/node/v12.14.1/bin/npm` however calling `aws` does not trigger this as its installed under `/usr/local/bin/aws`

Testing this in another vscode window in a working project folder does not exhibit the same problems, despite using the same extensions and connection to WSL: Ubuntu-18.04

This project has worked before with the same extensions, and npm packages so not sure what triggered this to happen in these folders. 

**Troubleshooting steps:**
Removed `.vscode`
Turned Auto Attach Off
Deleted entire folder and entered same project
Changed terminal types from zsh to bash
Tested this with a working project folder, all packages and npm is installed in same location but it does not exhibit the same behavior.
Ran `ls -al` to make sure repo was empty and it was.
Using a separate terminal (windows terminal) in the same location works as intended.
Switching between a broken project folder to a working one works fine.
Cloning the same project and opening it in a different location works as intended.
Calling `.code` to open the broken project folder exhibits the broken behavior.

So it looks like vscode decides to attach itself/exhibits this behavior ONLY when they're launched from these specific folder paths. 

Working path `/root/work/api-node-platform-integrationsTest`
Broken Path `/root/work/api-node-platform-integrations`

**Other things I noticed:**
When calling exit on bash in the broken project window, I receive `The terminal process "/bin/zsh" terminated with exit code:130` or exit code 126. But when calling `exit` in a working vscode window it exits without throwing an error.

When trying to enter bash from the `zsh` console by typing `bash` I should expect it to switch to bash, however it shows the debugger attachment, and then after a ctr + c it enters bash. Calling `which bash` shows `/bin/bash`

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**<details>
<summary>System Info</summary>**

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (45.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|Memory (System)|63.95GB (45.67GB free)|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|Memory (System)|63.95GB (45.67GB free)|
|VM|40%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.4.0
terraform|4op|0.1.10
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
terraform-autocomplete|erd|0.0.8
terraform|has|2.1.1
azure-account|ms-|0.8.11
vsliveshare|ms-|1.0.2478
vscode-yaml|red|0.9.1
serverless-ide-vscode|Thr|0.5.24
vscode-docker|ms-|1.3.1
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.9
terraform-doc-snippets|run|0.4.0
code-settings-sync|Sha|3.4.3

</details>

**Comment by stevenroussey-privicy** [comment]
Have the same issue, at the root folder of the project. I can not `npm update` or install anything now without opening a terminal outside of VS Code.

**Comment by connor4312** [comment]
Please check out the instructions here for a fix: https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467

/duplicate
