### ISSUE TITLE
Is the return object of `MarkdownString.to` correct?

### ISSUE THREAD

**Issue by iuyoy** [microsoft/vscode#103015]
Hi vscode,

I can't get a right `Hover` result to display by calling `commands.executeCommand('vscode.executeHoverProvider', ···)`, when I try to build an extension to support more language features for embedded languages. 

After reading some source code, I find that the return object doesn't seem to match the return type in the following function.
https://github.com/microsoft/vscode/blob/6a9f98bc864bd879cbc6d556983ab05781942c16/src/vs/workbench/api/common/extHostTypeConverters.ts#L336-L338

Is it right here?

**Comment by jrieken** [comment]
> Is it right here?

I say yes. Proof me wrong.

**Comment by iuyoy** [comment]
All right, my root problem is that I can't display `Hover` info by calling `commands.executeCommand('vscode.executeHoverProvider', ···)`:
![image](https://user-images.githubusercontent.com/11738832/90354267-664ad180-e07b-11ea-974d-c793cae7ac39.png)

I have to convert the result `Hover` object  to another `Hover` object:
![image](https://user-images.githubusercontent.com/11738832/90354225-356a9c80-e07b-11ea-8f8e-b608d6f7db40.png)

**Comment by jrieken** [comment]
Screenshots? How about something that allows me to reproduce/

**Comment by iuyoy** [comment]
> Screenshots? How about something that allows me to reproduce/

Here it is
```typescript
provideHover: async (document, position, token, next): Promise<any> => {
    let results = await commands.executeCommand(
        'vscode.executeHoverProvider',
        document.uri,
        position,
    )
    console.log("results", results[0]);
    // if (results && results[0]) {
    //     let contents =[];
    //     results[0].contents.forEach(element => {
    //         contents.push(element.value);
    //     });
    //     console.log(contents);
    //     return new Hover(contents, results[0].range);
    // }
    // return ;
    if(results){
        return results[0];
    }
    return results;
}
```

**Comment by jrieken** [comment]
And what do you expect? The result is an array of `vscode.Hover`-elements and that's what's to be expected

**Comment by iuyoy** [comment]
It should be an array of `vscode.Hover`, but it isn't as I see.

**Comment by jrieken** [comment]
Where do you see that?

**Comment by iuyoy** [comment]
I add a breakpoint at `results`, and get the `results` as follows
![image](https://user-images.githubusercontent.com/11738832/90367937-e4b76b80-e09b-11ea-8f6c-870c54c875c2.png)
And the definition of `vscode.Hover` is 
![image](https://user-images.githubusercontent.com/11738832/90368161-44ae1200-e09c-11ea-8081-25855f5dc2d4.png)
![image](https://user-images.githubusercontent.com/11738832/90368185-4c6db680-e09c-11ea-9e0a-4f696afa8e01.png)

The element of `vscode.Hover.contents` should be a `string` or a object which has a string property `value`. 

There is a little difference of definition of `value` between `results` and `vscode.Hover`.
I don't know much about ts, but the phenomenon is that I can get value by calling `results[0].contents.value`, but vscode can't display the hover info when `results[0]` is returned.

**Comment by jrieken** [comment]
> The element of vscode.Hover.contents should be a string or a object which has a string property value.

No - it's an array of that. See https://github.com/microsoft/vscode/blob/37a7ef133b8b87cd48b9e59ce17850c781c4b0c8/src/vs/vscode.d.ts#L2539
