### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by devomaa** [microsoft/vscode#103092]
- VSCode Version: 1.47.2
- OS Version: (I'm gonna just put my uname -a here) `Linux no 5.7.8-arch1-1 #1 SMP PREEMPT Thu, 09 Jul 2020 16:34:01 +0000 x86_64 GNU/Linux`

Steps to Reproduce:

1. Get VPN
2. Get "Github Pull Requests And Issues" extension
3. Try to sign in while VPN is on
4. This appears in output of GitHub Authenticator
```
[Info  - 12:59:38.591] Logging in...
[Info  - 12:59:59.927] Treating input as token
[Info  - 12:59:59.928] Getting user info...
[Error  - 13:00:00.344] Getting account info failed: Unauthorized
[Error  - 13:00:00.344] Unauthorized
[Error  - 13:00:00.345] Error: network error
```  

Does this issue occur when all extensions are disabled?: Yes/No --

**Comment by juhovan** [comment]
Hi,

did you manage to solve this? I'm seeing this on multiple machines (Manjaro & Ubuntu) without any VPN connection..
VSCode 1.48.0-insider

**Comment by devomaa** [comment]
I solved this.
