### ISSUE TITLE
Show plugin name for actions in Command Palette

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10308]
- VSCode Version: Code - Insiders 1.5.0-insider (dde41be0231d6f8397d1da969ddab351f137b833, 2016-08-08T06:03:58.264Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

It would be great to be able to see plugin name (if possible) that registers action in Command Palette - like here I am inside TypeScript file and Command Palette offers me these actions:

![image](https://cloud.githubusercontent.com/assets/1723815/17487560/652e8e62-5d63-11e6-9222-278183f73783.png)

But they are not applicable to TypeScript and it's not clear where they are coming from

When I try to use them I get:
![image](https://cloud.githubusercontent.com/assets/1723815/17487614/a1dc66fe-5d63-11e6-9c53-5673e5e480cd.png)

**Comment by stevencl** [comment]
I understand the problem, I just don't think that adding the name of the extension to the command palette would be the best solution. We need to spend time thinking about our overall commanding model throughout the whole product. We will consider how best to solve this problem when we look at commanding as a whole.

I will close this for the moment but we will focus on addressing this in the future when we look at commanding overall.
