### ISSUE TITLE
Incorrect copy paste with hotkey ctrl + c

### ISSUE THREAD

**Issue by anton-marchenko** [microsoft/vscode#103077]
- VSCode Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

- OS Version: Windows 7 Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Open 2 tabs with text (or code). For example:

1st tab:
```
test
```
2nd tab:
```
test2()
```
2. in 1st tab put cursor to the end of line (in the oend of the word "test")
3. Make Ctrl+C
4. Go to 2nd tab
5. Put cursor between "()"
6. Make Ctrl+V

Expected result:
```
test2(test)
```
Real result:
```
test
test2()
```

Does this issue occur when all extensions are disabled?:

Maybe yes, because https://stackblitz.com (who use similiar engine as I understand) has same issue.

**Comment by gjsjohnmurray** [comment]
I think this is probably behaving as designed. When you use Ctrl+C with nothing selected VS Code treats this as an instruction to copy the current line (as a line). Then Ctrl+V will paste it as a line. If you have nothing selected when you paste, the copied line is pasted above the line the cursor is on.

In your example as step 2a) press Shift+Home to select the word 'test' before copying to clipboard.
