### ISSUE TITLE
better branch switch control  on statusbar for multiroot workspace

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#103025]
Issue Type: <b>Feature Request</b>

when opening a workspace with multiroot which each folder has it's own git repo. it is hard to switch branch within status-bar scm-button. please make it better,3q

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

**Comment by joaomoreno** [comment]
Each repository appears as a row in the SCM view, along with a control to switch branches. Do you see them?

**Comment by heartacker** [comment]
> Each repository appears as a row in the SCM view, along with a control to switch branches. Do you see them?

hi, as the pic:
work on multi repo workspace,
![image](https://user-images.githubusercontent.com/1876302/88511054-c4553d80-d016-11ea-9c07-9b8dbb9e2696.png)
When I'm in the File Explorer view, I want to quickly switch to a branch of one workspaceroot, but a button makes it hard to tell which repository or branch it is unless I open a particular file in particular repository.
![image](https://user-images.githubusercontent.com/1876302/88511624-bce26400-d017-11ea-96a6-0bd1ecdf7175.png)

**Comment by joaomoreno** [comment]
The status bar will always show the repo of the last focused file.

If you want the general command, simply run `F1` > `Git: Checkout...` that should show you a repository picker.
