### ISSUE TITLE
Copying from Python Interactive Console

### ISSUE THREAD

**Issue by vemvir** [microsoft/vscode#103029]
The double pasting issue that the integrated Jupyter Notebook was having has been fixed but at the cost of being able to copy from the Notebook.

Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

The only extension I have installed is Python.

To reproduce:
1: Launch VS Code and open an Interactive Python console.
2: Type and run any code in the console.
3. Copy and paste the output from inside the console to anywhere. It just doesn't copy to the clipboard

**Comment by trbot86** [comment]
Not the OP, but I still have double pasting problems in the same version. Any time I paste in an Integrated Jupyter Notebook it also pastes in the Integrated TERMINAL (running the paste as command(s)). Using remote ssh.

Version: 1.47.2 (system setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
