### ISSUE TITLE
problem in 'defaultsettings.json'

### ISSUE THREAD

**Issue by hhasi** [microsoft/vscode#103009]
Issue Type: <b>Bug</b>

I
![problem-in](https://user-images.githubusercontent.com/50325055/88054911-f3376380-cb7f-11ea-8586-29070070843f.jpg)
n my 'defaultSettings.json' file in there, line = 3573 and column = 48 have an error and I want to fix it but it says 'not edit in read-only editor'. 

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200G with Radeon Vega Graphics     (4 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.93GB (0.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.0
vscode-pull-request-github|Git|0.18.0
start-git-bash|McC|1.2.1
cpptools|ms-|0.29.0
vsliveshare|ms-|1.0.2478

</details>

**Comment by jtsom** [comment]
This is still happening in the latest Insiders:
![image](https://user-images.githubusercontent.com/13488/89646424-bc549380-d889-11ea-821d-0812cf825c01.png)
```
Version: 1.48.0-insider
Commit: 20cba51fb305868238eddc69758d259c29b3230d
Date: 2020-08-07T05:30:01.305Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```

**Comment by sandy081** [comment]
It seems to be happening on workspace settings, can you please open separate issue for this?
