### ISSUE TITLE
Debug dots appear when i click on a line of code

### ISSUE THREAD

**Issue by Raman077** [microsoft/vscode#103085]
Issue Type: <b>Bug</b>

On my Windows 10 system, I debugged my code. After I was done with the debugging, whenever I clicked on the code, line corresponding to it was marked red, just like how we mark a line of code for debug. This process continues for every part of code. And during all this, when I try to copy a part of code, the red dot is pasted in its place and it doesnt copy correctly. Interesting thing is that this happened with visual studio 2019 too on the same machine.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.29.0

</details>

**Comment by Raman077** [comment]
![image](https://user-images.githubusercontent.com/20419185/88164709-1b7f9a80-cc32-11ea-97ff-6000f6159619.png)


This is a sample of how its working. The corresponding red dots were created when I tried to click on that line number.

**Comment by gjsjohnmurray** [comment]
Looks like you are clicking too far to the left of the line numbers. Try clicking on the actual numbers.

**Comment by Raman077** [comment]
Thing is, I am not working with debug mode on. I am just trying to code right now and during that when I switch line numbers by clicking on a part of code or just scrolling through it, this red dot appears on the line corresponsing to wherever my cursor goes and starts flickering. I click on it again to remove it and it gets removed but the same cycle happens when I move my cursor through mouse clicks or keyboard arrow keys.

**Comment by gjsjohnmurray** [comment]
Breakpoints can be set even when you are not actively debugging. The dark red dots in your screenshot come from when you clicked in that column. If you only want to select the line (not set a breakpoint on it), click on the number.
