### ISSUE TITLE
Remove Rating on VSCode Marketplace for Extensions marked as Preview

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#103028]
I would like to add a functionality to the preview in the manifest. Whenever it is in preview, ratings can't be added to the extension. I've received a rating of 2 for a bug that Happened because of vscode 1.47.1, I told the guy how to fix it, he did not answer if I helped him, nor opened a github issue later. Now the extension has a rate of 4. something for a problem that was not only caused by my code.

**Comment by usernamehw** [comment]
Related #94743
