### ISSUE TITLE
VS Code not opening

### ISSUE THREAD

**Issue by Gatik744** [microsoft/vscode#103066]
- VSCode Version:1.47
- OS Version: Windows 7

My VS Code is simply not opening and it doesn't throw any error and it does not start any process in task manager.

 Things to Note:-
1. This Problem is from like 8 days or so, So My System has been restarted quite a few times.
2.I've Reinstalled it atleast 10-15 times So,Thats also not helping 

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

Hope to get an Answer.

**Comment by joaomoreno** [comment]
Do you get some interesting output if you run `code --verbose` from the command line?

**Comment by Gatik744** [comment]
code --verbose is throwing a bunch of errors regarding unhandled promise rejections

btw you meant powershell in windows right?????

**Comment by joaomoreno** [comment]
Sure. Please show me the entire output of `code --verbose`?

**Comment by Gatik744** [comment]
how should i give you its a very long error and i think you cant copy things from powershell

**Comment by Gatik744** [comment]
PS C:\Users\Pankaj Garg> code --verbose

[main 2020-07-29T11:27:22.411Z] Error: UNKNOWN: unknown error, mkdir
[main 2020-07-29T11:27:22.413Z] Lifecycle#kill()
(node:5632) UnhandledPromiseRejectionWarning: Error: UNKNOWN: unknown error, scandir 'c:\Users\Pankaj Garg\AppData\Roami
ng\Code\User'
(node:5632) UnhandledPromiseRejectionWarning: Error: UNKNOWN: unknown error, scandir 'c:\Users\Pankaj Garg\AppData\Roami
ng\Code\User'
(node:5632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing insi
de of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:5632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing insi
de of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:5632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections
 that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections
 that are not handled will terminate the Node.js process with a non-zero exit code.
PS C:\Users\Pankaj Garg>

**Comment by joaomoreno** [comment]
I don't think this is a VS Code issue, but rather a Windows issue. Did you rename your user or so? Do you have issues with other applications?

**Comment by Gatik744** [comment]
no im running other apps as usual

**Comment by Gatik744** [comment]
can we talk or chat together on something like discord or something?????
Just because its taking way too much time so if possible.

**Comment by joaomoreno** [comment]
Have you tried completely reinstalling VS Code?

**Comment by Gatik744** [comment]
yes, at least 8-9 times ive reinstalled VS Code and this problem is occuring from almost 2 weeks so my system has been restarted quite few times

**Comment by joaomoreno** [comment]
Can you save the contents of `c:\Users\Pankaj Garg\AppData\Roaming\Code`, then delete that folder and then start VS Code again?

**Comment by Gatik744** [comment]
Can you explain a bit more???

**Comment by joaomoreno** [comment]
1. Shutdown Code
2. Delete `c:\Users\Pankaj Garg\AppData\Roaming\Code`
3. Launch Code again

**Comment by Gatik744** [comment]
I'm getting an error while deleting the folder saying:-

Error 0x80070091: the directory is not empty.

**Comment by joaomoreno** [comment]
This sounds like an issue with your OS, I would suggest asking in StackOverflow to see if someone can unblock you.
