### ISSUE TITLE
.md in preview window - cannot copy&paste

### ISSUE THREAD

**Issue by anporumb** [microsoft/vscode#103114]
- VSCode Version: 1.47.2 (system setup)
- OS Version: Windows 10 - 2004. 19041.388

Steps to Reproduce:

1. Open Visual Studio Code
2. Load .md file + preview of the .md
3. Use mouse to select some text in the preview window
4. Press CTRL + C
5. go to another program (like notepad)
6. press CTRL + V
7. 3 possible outcomes
   a) the selected text makes it to notepad
   b) some random text previously pasted will be pasted
   c) blank line is pasted

Does this issue occur when all extensions are disabled?: Yes!!!!!!!

![image](https://user-images.githubusercontent.com/9283365/88216547-1ad70c00-cc12-11ea-874c-10521f5a9f73.png)
![image](https://user-images.githubusercontent.com/9283365/88216583-24607400-cc12-11ea-9e66-5f0db554f9fc.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by anporumb** [comment]
Let me check that...

**Comment by anporumb** [comment]
OK, so far so good with insiders edition.

I will come back to this issue:
1) in a few days if it doesn't reproduce during those days
2) as soon as it reproduces.

Best Regards,
Andrei Porumb

**Comment by mjbvz** [comment]
Ok, thanks for testing. Closing this as fixed. We will verify it again before 1.48 is released

**Comment by isidorn** [comment]
Can not reproduce, adding verified label
