### ISSUE TITLE
Product Icon should not simply be a different color than the Visual Studio 2019 icon

### ISSUE THREAD

**Issue by PerryCodes** [microsoft/vscode#103102]
The difference between VS Code and Visual Studio 2019 product icons are color and an almost non-visible connecting line.

The icons for these two very different products should be more distinguishable from each other.

**Comment by gjsjohnmurray** [comment]
See #71827

**Comment by PerryCodes** [comment]
After reading the link posted by gjsjohnmurray, I realized to things:

1. If I'm going to post issues, my content-creation-skills needs quite a bit of work.
2. I didn't put enough effort into searching before posting.
