### ISSUE TITLE
unable to install vscode extension : XHR failed

### ISSUE THREAD

**Issue by alee0510** [microsoft/vscode#103142]
Issue Type: <b>Bug</b>

unable to open extension when try to install extension from vscode, XHR failed.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
code-runner|for|0.11.0
material-icon-theme|PKi|4.2.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
See #102714 for a similar recent report that the reporter resolved by changing DNS settings.
