### ISSUE TITLE
Absolute path for `program` property of node launch configuration is interpreted as a relative path when it exists on a different drive than the ${workspaceFolder} and integratedTerminal is used

### ISSUE THREAD

**Issue by mwpenny** [microsoft/vscode#103197]
- VSCode Version: 1.48.0
- OS Version: Windows 10 1809 (OS Build 17763.1282)

Does this issue occur when all extensions are disabled?: Yes

---

Steps to Reproduce:

1. Create a `launch.json` like so (`program` must be on a different drive than `${workspaceDirectory}`):
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Program",
            "type": "node",
            "request": "launch",
            "program": "D:\\test.js",
            "console": "integratedTerminal"
        }
    ]
}
```

2. Run the launch configuration and observe the following error
```
Error: Cannot find module 'C:\Path\To\Workspace\Dir\d:\test.js'
```

The absolute `program` path is treated as relative and concatenated with the path to the currently open workspace (i.e., `${workspaceFolder}`). I suspect this is a bug in the "resolve path" code, which likely assumes that `program` exists relative to `${workspaceFolder}`.

The command that is actually run is:
```powershell
PS C:\Path\To\Workspace\Folder>  ${env:NODE_OPTIONS}='--require "c:/Program Files/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" '; ${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.32948-4.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"fileCallback":"C:\\Users\\mpenny\\AppData\\Local\\Temp\\node-debug-callback-d94fd6de841a4f43"}'; & 'C:\Program Files\nodejs\node.exe' '.\d:\test.js'
```

Note that the argument to `node.exe` is prefixed with `.\` (i.e., a relative path). The issue does not occur if I remove `"console": "integratedTerminal"` from the launch configuration. This works properly on 1.46.x.

**Comment by weinand** [comment]
What exactly are you trying to achieve by launching VS Code with a `--extensionDevelopmentPath` argument?
`--extensionDevelopmentPath` is used internally for extension debugging.

**Comment by mwpenny** [comment]
@weinand I am developing a VSCode extension that creates a project and autogenerates a `launch.json` file. Users of the extension can then launch this newly-created configuration, among other things.

So I am launching the node configuration (with the `program` attribute) from within the VSCode instance that is running the extension that I am debugging. Not from the VSCode instance which I am writing the extension within.

So my workflow looks like this:
* VSCode instance 1 is where I write the extension. It has a launch configuration that looks like this:
```json
{
    "type": "extensionHost",
    "request": "launch",
    "name": "Run dev tools extension",
    "args": [
        "--extensionDevelopmentPath=${workspaceFolder}"
    ],
    "outFiles": [
        "${workspaceFolder}/dist/**/*.js"
    ]
}
```
* VSCode instance 2 is started from VSCode instance 1 (with `extensionDevelopmentPath`) when I want to debug the extension
    * From VSCode instance 2 (Extension Development Host, running my extension), I try to launch the problematic configuration mentioned in my original post (`"type": "node", "program": "C:\\Some\\Absolute\\Path\\To\\A\\Script.js"`) and observe the issue. However, you don't even need to be debugging a real extension to reproduce this issue, which is why I simplified the situation for my original post.

If I build my extension into a .vsix and install it, then try to run the aforementioned node launch configuration, the absolute path for `program` works as expected.

**Comment by weinand** [comment]
I cannot reproduce your problem on macOS. Now trying on Windows...

**Comment by weinand** [comment]
Cannot reproduce on Windows either:

![2020-07-23_23-46-47 (1)](https://user-images.githubusercontent.com/1898161/88342055-fcbafa00-cd3e-11ea-9c3a-f452d4023e92.gif)

**Comment by weinand** [comment]
Could you please try to reproduce the problem with the simple "hello world" extension?

**Comment by mwpenny** [comment]
It turns out that the reproduction steps for this issue are much simpler than I originally thought. The error occurs if the script that is specified for `program` exists on a different drive than the workspace does.

So it has nothing to do with extension development. The reason I was seeing the problem during extension development only is because my extension's source files are on a different drive and the path generated for `program` depends on the drive where the extension is running (it points to a JS file of the extension).

So the simplified reproduction steps are:

1. Create a `launch.json` like so (`program` must be on a different drive than `${workspaceDirectory}`):
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Program",
            "type": "node",
            "request": "launch",
            "program": "D:\\test.js",
            "console": "integratedTerminal"
        }
    ]
}
```

2. Run the launch configuration and observe the following error
```
Error: Cannot find module 'C:\Path\To\Workspace\Dir\d:\test.js'

I have edited my original post.
```

**Comment by mwpenny** [comment]
I see this issue still has the `needs more info` label. Are you able to reproduce based on the updated description?

**Comment by weinand** [comment]
@mwpenny I'm not able to reproduce this issue with VS Code 1.51 on Windows 10:

<img width="917" alt="2020-11-09_16-23-37" src="https://user-images.githubusercontent.com/1898161/98560426-0e052380-22a8-11eb-9a29-4d5bc5266490.png">

A recent switch to a completely new JavaScript debugger (js-debug), might have fixed this.

**Comment by mwpenny** [comment]
@weinand Thanks for the heads up, I was just able to verify that it no longer occurs for me as well.
