### ISSUE TITLE
Unable to use dotnet CLI with ZSH

### ISSUE THREAD

**Issue by themccallister** [Microsoft/vscode#10318]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Install Oh My ZSH 
2. Install Visual Studio Code
3. Install dotnet and scaffold new application

Using any of the `dotnet` tools from within Code results in the following:

<img width="635" alt="screenshot 2016-08-08 16 44 47" src="https://cloud.githubusercontent.com/assets/5354908/17495552/77890794-5d87-11e6-8df8-60489d8fba0a.png">

I'm assuming that is because my default terminal is *not* the bash that ships with macOS?

**Comment by Tyriar** [comment]
The handling of this command is left entirely to `zsh`, what you're likely experiencing is that `dotnet` is not on your `$PATH`. Not sure about `zsh`, but for `bash` this sort of thing often happens when users expect their `~/.bash_profile` to be run which requires passing in the `-l` arg to `bash` via `terminal.integrated.shellArgs.osx`

**Comment by themccallister** [comment]
@Tyriar, switching into terminal and running `dotnet` puts out the following information:

<img width="1402" alt="screenshot 2016-08-09 16 12 31" src="https://cloud.githubusercontent.com/assets/5354908/17531931/20082d68-5e4c-11e6-81c0-dab4c95f592b.png">

I do not think this is related to my path, as I can use `dotnet` from the CLI... Maybe I am misunderstanding the issue?

Also, my path looks like this:

```
export PATH="/Users/jasonmccallister/.developer:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jasonmccallister/.composer/vendor/bin"
```

**Comment by themccallister** [comment]
Ah, I did set an alias to the path for `dotnet`:

```
alias dotnet="/usr/local/share/dotnet/dotnet"
```

Is this an issue with Code or the dotnet installer?

**Comment by Tyriar** [comment]
Where is the alias set?

**Comment by themccallister** [comment]
The alias is set in my `.zshrc` file.

Removing the alias and setting:

    export PATH="/usr/local/share:$PATH" 

Gives me a permissions denied message:

    zsh: permission denied: dot net

By default, the installer places `dotnet` in:

    /usr/local/share/dotnet/dotnet

**Comment by Tyriar** [comment]
Can you run `/usr/local/share/dotnet/dotnet` directly with the absolute path?
