### ISSUE TITLE
Node.js debugger does not support Node's versions below 8.x

### ISSUE THREAD

**Issue by iandrc** [microsoft/vscode#103150]
- VSCode Version: 1.47.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Choose Node.js version `6.x.x` (in my case it was `6.17.1`)
2. Insert some breakpoints to JS files
3. Try to run the debugger with `Node.js` option
4. See the output:

![Untitled](https://user-images.githubusercontent.com/63982045/88280758-12a0ce80-ccef-11ea-9e0b-83805a1ef1e8.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@iandrc you can enable "node.js legacy" support by changing the setting `debug.javascript.usePreview` to `false`.

**Comment by iandrc** [comment]
@weinand that works, thanks :)
