### ISSUE TITLE
New Source Control Feature Broke

### ISSUE THREAD

**Issue by tthrash** [microsoft/vscode#103173]
Issue Type: <b>Bug</b>

I recently had an update which gave me what appears to be a feature experiment that is broken. There is a new source control button and now my source control is somewhat broken. It's not showing the number of changes badge when I make changes, and it's not picking up changes I make on my Visual Studio instance (for .net framework project), which it used to do. It's forcing me to reinstall VS Code.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
dotnet|for|0.0.4
coldfusion|ili|1.0.1
Angular2|joh|9.1.2
pwa-tools|joh|0.1.0
Angular-BeastCode|Mik|8.1.2
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.4.1
csharp|ms-|1.22.1
debugger-for-chrome|msj|4.12.9
angular-console|nrw|12.0.0
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0

</details>

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by jgerhold** [comment]
I had the same problem. I could restore the git icon and number of changes badge by using "Reset location".

**Comment by joaomoreno** [comment]
> Can you please provide a [screen recording](https://gifcap.dev/)?

👍

**Comment by jgerhold** [comment]
> > Can you please provide a [screen recording](https://gifcap.dev/)?
> 
> 👍

Sorry, I can’t recreate the issue and provide a screen recording.
