### ISSUE TITLE
Editor submenu disappears

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#103167]
1. Open a TypeScript file
2. Right click on the editor
3. Hover `Peek`
4. Wait 1 second

🐛 Submenu disappears after 1 second

**Comment by sbatten** [comment]
started only in today's build, likely from the shadow dom changes

**Comment by nrayburn-tech** [comment]
I believe this PR may be relevant, https://github.com/microsoft/vscode/pull/93667.
