### ISSUE TITLE
Incorrect indentation due to file language detection ?

### ISSUE THREAD

**Issue by saminton** [microsoft/vscode#103147]
Issue Type: <b>Bug</b>

I have a php file with the following

```
<div>|</div>
```

"|" being the cursor. When hitting enter with the cursor between the two html brackets I get

```
<div>
|</div>
```
Instead of 

```
<div>
   |
</div>
```

I have to manually set the file language to html and back to php for it to correctly work. Happens whenever I open a workspace.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
project-manager|ale|11.1.0
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-intelephense-client|bme|1.5.3
jshint|dba|0.10.21
vs-code-xml-format|fab|0.1.5
vscode-indent-on-paste|gaz|2.3.5
vscode-peacock|joh|3.7.2
code-settings-sync|Sha|3.4.3
sass-indented|syl|1.8.9

</details>

**Comment by rebornix** [comment]
We don't have comparable indentation rules for php. Considering that indentation rules are regex based and always not good enough, please consider using formatters for the same purpose.

**Comment by saminton** [comment]
Sorry I don't fully understand. When you suggest using a formatter, that means using an extension such as https://github.com/RiFi2k/format-html-in-php ? I have tried this but it doesn't really solve the problem. As far as I can tell the formatting isn't automatic, having to manually format the document via command via 'format document' each time I create a HTML tag is extremely time consuming.

What I don't understand is that the expected behaviour works fine when I change the file language via 'select language mode' from PHP to HTML and back to PHP, even with no extension installed so VSCode Does correctly take into account the auto indentation on HTML within PHP. But just not when I first open the project. So I am guessing this is in fact a bug ?
