### ISSUE TITLE
Text formatting problems when copy/paste from VS Code to Wordpress editor

### ISSUE THREAD

**Issue by nirmalsinghoo7** [microsoft/vscode#103135]
Hello Team,
I am new to VS code but I used 5+ years sublime and Notepad++.
I found this issue while developing website on Wordpress. I am duplicating the website. I copy the text content and paste in VS Code to remove the code formatting. 
When I copy content from VS Code and paste in wordpress editor, It breaks the code after hyphen and breaks the words.

You can see the details here - https://support.brizy.io/hc/en-us/community/posts/360071478751-It-s-breaking-the-words?page=1#community_comment_360012120671

I tried by copy/paste content from Sublime and Windows Notepad to wordpress editor and it's working fine.

Please find a solution for this.

Regards,
Nirmal Singh

**Comment by rebornix** [comment]
You may want to disable `editor.copyWithSyntaxHighlighting` to copy/paste plain text.
