### ISSUE TITLE
The language set by `vscode.languages.setTextDocumentLanguage` does not persist

### ISSUE THREAD

**Issue by xorye** [microsoft/vscode#103198]
- VSCode Version: 1.48.0-insider
- OS Version: Linux

![image](https://user-images.githubusercontent.com/20326645/88330558-919b0480-ccf9-11ea-9e16-2b3f5b59ea99.png)

Steps to reproduce the issue:

1. Open a plaintext file and set the languageId to `Batch`

2. Change the languageId to `C` using `vscode.languages.setTextDocumentLanguage`. To do this, I created a vscode extension with this code:
```
export function activate(context: vscode.ExtensionContext) {

	context.subscriptions.push(vscode.commands.registerCommand('languageSetter.setLanguage', async () => {

		if (!vscode.window.activeTextEditor) {
			return;
		}

		const languageId: string = 'c';
		await vscode.languages.setTextDocumentLanguage(vscode.window.activeTextEditor.document, languageId);
		vscode.window.showInformationMessage(`Language has been set to ${languageId}`);
	}));
}
```
and called the `languageSetter.setLanguage` command.

3. Navigate to a different tab (in the gif, I navigate to Settings)

4. Go back to the file, the languageId is `Batch` instead of `C`.

![vscode-languageid](https://user-images.githubusercontent.com/20326645/88332532-b6dd4200-ccfc-11ea-83b7-06be0ea4df72.gif)

Expected Behavior:
I expected the language to be `C` instead of `Batch` since my command set it to `C`.

`Batch` and `C` were just examples. This problem happens on other languages too.

Does this issue occur when all extensions are disabled?: Yes, I've disabled every extension except my example extension that I use to reproduce the problem.

**Comment by bpasero** [comment]
I cannot reproduce anymore, maybe this was fixed meanwhile.

@xorye can you still using latest insiders?
