### ISSUE TITLE
System busy spinner showing up every 20 seconds or so

### ISSUE THREAD

**Issue by devilb0x** [microsoft/vscode#103187]
Issue Type: <b>Bug</b>

Ever since the last update the spinner pointer appears constantly. After a lot of trial and error, I've determined that it only shows up while VS Code is running. 

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.29.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
platformio-ide|pla|1.10.0

</details>

**Comment by joaomoreno** [comment]
> the spinner pointer

What do you mean? Can you show me a screenshot of this? A screen recording?

**Comment by devilb0x** [comment]
I've attached a recording. It's rather long to show the approximate interval between the spinner's appearances.
![recording](https://user-images.githubusercontent.com/5402222/88427804-e3eb2c80-cdb0-11ea-8a30-dadea6bfbbec.gif)

**Comment by clrvsn-ab** [comment]
I'm getting exactly the same symptoms under Windows 7 if that's any help.

**Comment by connor4312** [comment]
Huh, that's interesting. Can you grab a CPU profile over the timespan of a couple of these spinners (a minute or so I suppose)? 

Instructions: https://www.nicoespeon.com/en/2019/11/fix-vscode-extension-performance-issue/#how-to-measure-the-performance-of-a-vs-code-extension

**Comment by devilb0x** [comment]
Here is a couple minutes of the profiler running.

[CPU-20200727T163751.557Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/4983216/CPU-20200727T163751.557Z.cpuprofile.txt)

**Comment by connor4312** [comment]
Thanks. I _think_ I see what's happening, and should have a fix in the linked commit. Please try the upcoming [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) and let us know if that works for you.

**Comment by isidorn** [comment]
Hard to repro. @devilb0x can you be so kind to try out the vscode insiders and let us know if it is fixed for you? Thanks
https://code.visualstudio.com/insiders/

**Comment by clrvsn-ab** [comment]
Afraid it's still showing same symptoms using Insiders under Windows 7. 

Version: 1.48.0-insider (user setup)
Commit: cfbd1999769f4f08dce29629fb92fdc0fac53829
Date: 2020-08-06T05:59:51.622Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

[CPU-20200806T191511.236Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/5037579/CPU-20200806T191511.236Z.cpuprofile.txt)
