### ISSUE TITLE
Edit settings.json inserts entry on open

### ISSUE THREAD

**Issue by capegreg** [microsoft/vscode#103156]
Issue Type: <b>Bug</b>

I believe this issue first appeared in version 1.47.2.

To reproduce the issue, go to Preferences->Settings. Find any setting in the enhanced settings page that has an "Edit in settings.json" link and click it. When the settings.json file opens, the cursor immediately inserts a new line in whatever setting you chose and intellisense inserts a new settings item with the cursor set inside empty quotes.

For example:
 "terminal.integrated.automationShell.linux": "" <--cursor will be inside quotes with a tooltip message "No suggestions"

You will now need to undo the unwanted setting. This happens on any setting that is edited in settings.json.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

**Comment by gjsjohnmurray** [comment]
I'm not clear why you describe this as an unwanted setting. Didn't you click the "Edit in settings.json" link underneath that exact setting?

![image](https://user-images.githubusercontent.com/6726799/88295533-74643700-ccf5-11ea-85f2-7424d88413b2.png)

If you've been using an arbitrary "Edit in settings.json" link as a way of opening the settings.json file so you can do other things with it I suggest you instead use the dedicated button for doing that:

![image](https://user-images.githubusercontent.com/6726799/88295737-ba20ff80-ccf5-11ea-9768-a832b4337f26.png)

**Comment by capegreg** [comment]
Ok. Thanks. I will close this. I was looking at it as an issue if I just wanted to view a specific settings in settings.json without actually editing it. After your suggestion to use the dedicated button, I see that it will not automatically add an entry for the section. The only thing here is that the settings.json opens to the section my cursor was last positioned so that I have to search the entire json file to examine the section. I can live with that.
