### ISSUE TITLE
EXE renamed to one with spaces in the filename

### ISSUE THREAD

**Issue by ghurlman** [microsoft/vscode#103112]
Issue Type: <b>Bug</b>

Adding spaces to the executable name just makes life a little more difficult when scripting things, for absolutely no benefit. Pleae change it back.

To repro:

- Download the latest Insider build

Expected: code-insiders.exe
Actual: "code - insiders.exe"

VS Code version: Code - Insiders 1.48.0-insider (6c21258b65e4c9448323c930fabb1ac6b734c597, 2020-07-20T05:33:03.267Z)
OS version: Windows_NT x64 10.0.20170

**Comment by joaomoreno** [comment]
It has been this way forever and it isn't likely to change any time soon. Sorry about that!

**Comment by IllusionMH** [comment]
There should be `code-insiders` (`bin/code-insiders.cmd`) in `PATH`  and as I understand - running this from CLI is preferred method.
