### ISSUE TITLE
[source control][git] After "Undo Last Commit", the next Commit can't input message

### ISSUE THREAD

**Issue by rhdlilj** [microsoft/vscode#103155]
After "Undo Last Commit", the next Commit can't input message. and the commit message will use Last Commit's message as default.

**Comment by joaomoreno** [comment]
What do you mean? The input box is not editable?

**Comment by rhdlilj** [comment]
1. add file to stage.
2. commit stage.
3. input the message in pop out inputbox.
4. press enter, commit it.
5. undo last commit.
6. add file to stage.
7. commit stage, here is theissue,no inputbox be pop out, it commit directly.

**Comment by joaomoreno** [comment]
When you undo last commit, the commit message should be restored in the commit input, do you see it? When you commit, that message will be used and you won't be prompted for a message at all.

Did you maybe hide the input box with the `git.showCommitInput` setting?

**Comment by rhdlilj** [comment]
oh, it's hide. maybe it's not a bug, but it's a issue for users.
