### ISSUE TITLE
Multiple cursors via "Find in Selection" mode (Ctrl + D) are faulty

### ISSUE THREAD

**Issue by Karanjot-singh** [microsoft/vscode#103115]
- VSCode Version: 1.47.1
- OS Version: Linux x64 5.3.0-28-generic

In addition to feature request #103080, The Multiple cursors via "Find in Selection" mode (Ctrl + D) are faulty. Inconsistent results are seen as all instances are not selected and edited by this key binding.

Steps to Reproduce:

1. select any recurring text(more than 2 times) throughout the document, say 'function'
2. Use Ctrl + D keybinding to edit all occurrences
3. Note that all instances are not selected.

Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by alexdima** [comment]
@Karanjot-singh I have tried with your provided steps, but I cannot reproduce:

![Kapture 2020-07-22 at 23 25 02](https://user-images.githubusercontent.com/5047891/88230379-98caff80-cc72-11ea-99cf-9ddcb28cd9f7.gif)

**Comment by ArturoDent** [comment]
Are you looking for the `Select all Occurrences of Find Match` command?  Ctrl+Shift+L on W10.

Ctrl+D only gets the next, not all, find matches.

**Comment by Karanjot-singh** [comment]
Seems to be a misinterpretation on my part. I apologise for the inconvenience @alexdima @ArturoDent. I am closing the issue.
