### ISSUE TITLE
source code view updated features are not clear/consistent

### ISSUE THREAD

**Issue by vrachels** [microsoft/vscode#103195]
Issue Type: <b>Bug</b>

Workspace with multiple repos as individual workspace folders.

The list view hides the dropdown/expand icon on repos with no changes.  This was not clear what was going on, as the 'publish changes' and 'commit' buttons were still available.

'Close Repository' option clears a repo from the list, but it reappears within a few seconds.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-53-generic

**Comment by joaomoreno** [comment]
Closing as duplicate, there are already issues to address this feedback assigned for July. Thanks!
