### ISSUE TITLE
Hex Editor File Watching testing

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#103175]
https://github.com/microsoft/vscode-hexeditor/issues/76

- [x] macOS @JacksonKearl 
- [ ] Windows
- [x] Linux @mjbvz 

Complexity: 2
Author: @lramos15 

[Create Issue](https://github.com/microsoft/vscode-hexeditor/issues/new?body=Testing%20https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fissues%2F103175)

---

Testing Steps:

1. Install this VSIX  (change from .zip to .VSIX)
[hexeditor-1.2.0.zip](https://github.com/microsoft/vscode/files/4967712/hexeditor-1.2.0.zip)
2. Test file watching support in the hex editor. A few cases are with edits + file deleted, with edits + file changed, without edits + file changed, without edits + file deleted, and SCM view. Make sure the behavior feels natural and everything works as expected.

**Comment by mjbvz** [comment]
File watching looks good on Linux. Tested on Ubuntu

**Comment by JacksonKearl** [comment]
Watching looks good on MacOS too. Saw a couple of the same bugs as in Linux (#118, #119)
