### ISSUE TITLE
Please enable a required extension for a time

### ISSUE THREAD

**Issue by Johnson-Devloper** [microsoft/vscode#103178]
While opening a visual studio code all extensions are loading.
It take time and hanging for a 4GB ram devices.

So enable required extension(get from last workspace) on start-up.

**Comment by deitry** [comment]
Oh, I know this problem.

There is such possibility. You can pass `--extensions-dir <path to som dir>` when launching Code from command line or put it into shortcut properties - this would launch Code with empty extension list and you can install only necessary ones.

**Comment by alexdima** [comment]
Does VS Code hang when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)
