### ISSUE TITLE
'Find in Selection' should be automatically selected based on editor selection

### ISSUE THREAD

**Issue by vk-coder** [microsoft/vscode#103160]
Arch        : x86_64
Version     : 1.47.2
Release     : 1594838045.el7

bash-4.2$ uname -a
Linux panini 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

If the user has already selected a region and then enters find and replace (Ctrl + H) then 'Find in Selection' should be automatically selected. The additional step of Alt + L is not required because by selecting the region user has already made his/ her intentions clear.

Reproducible steps

1. select multiple lines from the code using shift up/ down arrows
2. press ctrl + H to enter find and replace
3. observe that selection is still present in the editor and find box has the focus now
4. start typing in find and observe that selection is gone and find start with the whole file

**Comment by rebornix** [comment]
You can use `editor.find.autoFindInSelection` to control when/how the find in selection should be used.

**Comment by vk-coder** [comment]
I tried the option you suggested but it has a drawback as it also affect the Ctrl + F functionality. Generally you select text and then enter find mode (Ctrl + F) but now enters 'Find in Selection' and never finds another occurrence of the selected text.

so the options should either only work in Find or add separate option for Find & Replace.
