### ISSUE TITLE
Issue in SCSS variables containing colors

### ISSUE THREAD

**Issue by chiragbhansali** [microsoft/vscode#103131]
- VSCode Version: 1.47.2 (user setup)
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Create a `.scss` file
2. Make a variable that stores a color,  $primary
3. Make another variable which contains the name of the previous variable ($primary)  in its name, $primaryHover
4. The $primaryHover variable will have a background color, same as that of $primary

![image](https://user-images.githubusercontent.com/22539632/88245932-8e325980-ccb6-11ea-874f-2d56625ab4a3.png)

Does this issue occur when all extensions are disabled?: No

After following the above step, I tried disabling only the SCSS Intellisense extension (I have no other extension for Sass/SCSS) but found that the issue still existed.

**Comment by ArturoDent** [comment]
It looks like you have an extension that "colorizes" the background of css/scss color values (perhaps `Colorize` https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-colorize).  

I am pretty sure that isn't built-in functionality of vscode.

Disable such ana extension and if the problem goes away, file an issue with that extension.

**Comment by chiragbhansali** [comment]
@ArturoDent Thanks. It turns out that the issue was in [Color Highlight](https://github.com/egonyans/vscode-ext-color-highlight/) extension. I have filed an [issue](https://github.com/egonyans/vscode-ext-color-highlight/issues/106) there.
