### ISSUE TITLE
智能提示突然消失

### ISSUE THREAD

**Issue by MacrazdHao** [microsoft/vscode#103133]
未找到规律，随机出现，一开始正常使用，但用着用着智能提示会消失，变为"正在加载..."，无论等多久都无法恢复。

查过相关解决方法，比如restart ts server，也没反应，无法解决。

唯一能解决的办法是重新开启VSCode，但过不了多久又会重复出现这个问题。

极度影响使用体验，建议尽快找出原因，并提出官方解决方案，不只我会出现这个问题。

**Comment by joaomoreno** [comment]
What feature is this? Can you share a screenshot?

**Comment by Joker0824** [comment]
![image](https://user-images.githubusercontent.com/26892349/90602932-11e75380-e22d-11ea-944e-c1ff132e173b.png)
This is the question , as same as  MacrazdHao
