### ISSUE TITLE
moveEditor command behaves weird when tabs are disabled

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10312]
I am successfully using the new moveEditor command from my actions to move an editor left or right and things work great when tabs are enabled, but when tabs are disabled it looks like you are changing the command based on tabs enabled or not (see https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorCommands.ts#L76)

That is OK by me however when you have 3 editors open and move the third editor to the left it ends up in the LEFT position and not CENTER because in your conversion you are not taking my arguments into account.

To reproduce:
* disable tabs
* open 3 editors side by side
* focus the third editor
* invoke "Move Editor Left" from the command palette

=> editor moves to position 0 instead of 1.

**Comment by sandy081** [comment]
@bpasero I have aligned arguments

```
ActiveEditorMovePositioning.LEFT
ActiveEditorMovePositioning.RIGHT
ActiveEditorMovePositioning.CENTER
```
to
```
Position.LEFT,
Position.RIGHT,
Position.CENTER
```
Hence `moveActiveEditor` command moves the active editor to above positions on `left`, `right` and `center` respectively. 

I think changing the behavior as following makes sense to me

- Change the command to move active editor relative left, right on left, right respectively. Just like moving active tab. `ActiveEditorMovePositioning.FIRST`,  `ActiveEditorMovePositioning.CENTER`, `ActiveEditorMovePositioning.LAST` and `ActiveEditorMovePositioning.POSITION` to move to Positions.

**Comment by bpasero** [comment]
Reopening because the issue is still there when you try to follow my steps. Can you advise me how to change my command to make this work when tabs are disabled? The command is in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorActions.ts#L1313

**Comment by sandy081** [comment]
@bpasero It works for me following the steps in the description.. As expected editor in Group 3 is moved to Group 2. It works using action from Command Pallette and also through key board shortcut.

**Comment by sandy081** [comment]
![aug-15-2016 15-00-16](https://cloud.githubusercontent.com/assets/10746682/17665101/043f141e-62f9-11e6-8993-8447aac900a5.gif)

**Comment by bpasero** [comment]
Great, I must have been on an old version 👍
