### ISSUE TITLE
Have a setting to not show recent workspaces in jump list to make room for recent files

### ISSUE THREAD

**Issue by fvogliotti** [microsoft/vscode#103161]
Issue Type: <b>Feature Request</b>

Can you please make room for recent files in Jump Lists? Instead of Recent Workspaces that takes up all Jump List room!
Thank you!

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17134

**Comment by bpasero** [comment]
@fvogliotti "Recent Files" already exists:

![image](https://user-images.githubusercontent.com/900690/91652290-1a922200-ea96-11ea-8c19-8869dd8159da.png)

Can you clarify what you mean?

**Comment by fvogliotti** [comment]
Hi Benjamin! In my original request I said that "Recent Workspaces" take up
all Jump List room and that I cannot see "Recent files" any more. Like this:

[image: image.png]

Thank you!

**Comment by bpasero** [comment]
i am not seeing any screenshot in your comment

**Comment by fvogliotti** [comment]
Can you please confirm if the screenshot can be seen? Thanks!!! I attached
it

**Comment by bpasero** [comment]
No cannot.

**Comment by fvogliotti** [comment]
Is there a way for me to upload the screenshot? Can I post it in the
discussions tab on GitHub?

**Comment by fvogliotti** [comment]
[
![Image 516](https://user-images.githubusercontent.com/13700892/91739321-24944d80-eb88-11ea-8e58-3c1a5dd37970.jpg)
](url)

**Comment by bpasero** [comment]
@fvogliotti so you say that Windows reduces the number of recent files when you have many recent workspace?

**Comment by fvogliotti** [comment]
Yes, in fact it takes all the Jump List room and I left with no recent files whatsoever. The funny thing is that I never use Workspaces. I only open files or folders. I whish I could have them in the list. Thank you Benjamin.

**Comment by bpasero** [comment]
Ok renaming this then to reflect the intent.
