### ISSUE TITLE
Hex Editor Test Find and Replace

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#103176]
https://github.com/microsoft/vscode-hexeditor/issues/76

- [x] macOS @roblourens
- [x] Windows @Tyriar
- [x] Linux @chrmarti

Complexity: 3
Author: @lramos15 

[Create Issue](https://github.com/microsoft/vscode-hexeditor/issues/new?body=Testing%20https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode%2Fissues%2F103176)

---

Testing Steps:

1. Install this VSIX  (change from .zip to .VSIX)
[hexeditor-1.2.0.zip](https://github.com/microsoft/vscode/files/4967712/hexeditor-1.2.0.zip)
2. Test the find widget in the hex editor. Make sure cancellation, regex, case match, find next, and find previous all work as expected
3. Test that using ctrl / cmd +f focuses the find widget and changes the mode correctly
4. Test replace and preserve case. Make sure undo / redo with replace works as expected.

**Comment by chrmarti** [comment]
Didn't find a way to make search run long enough to test cancellation.
