### ISSUE TITLE
Breakpoints in jest tests are not fire

### ISSUE THREAD

**Issue by salos1982** [microsoft/vscode#103151]
Issue Type: <b>Bug</b>

I've used test configuration for a long time and until last update of Visual Studio Code debugging works well. But after update breakpoints are not fired if I start jest configuration. 

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 5.4.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 3622)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.24GB (0.39GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
vscode-eslint|dba|2.1.8
python-preview|don|0.0.4
githistory|don|0.6.8
python-extension-pack|don|1.6.0
gitlens|eam|10.2.2
vscode-jest-runner|fir|0.4.22
pythonsnippets|frh|1.0.2
Python-autopep8|him|1.0.2
shortcut-menu-bar|jer|1.3.0
vsc-python-indent|Kev|1.10.1
MagicPython|mag|1.1.0
python-path|mge|0.0.11
git-graph|mhu|1.24.0
python|ms-|2020.7.96456
debugger-for-chrome|msj|4.12.9
partial-diff|ryu|1.4.1
git-merger|sha|0.4.1
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.9
jinja|who|0.0.8

</details>

**Comment by mjashanks** [comment]
Can confirm this is happening. A downgrade to 1.46.1 fixes.... https://github.com/jest-community/vscode-jest/issues/605

**Comment by weinand** [comment]
Please try this in the latest VS Code.
Since we have a new JavaScript debugger, this should work now.
