### ISSUE TITLE
Missing close button and is_modified icon on file tab

### ISSUE THREAD

**Issue by floatingpurr** [microsoft/vscode#103106]
- VSCode Version: Version: 1.47.2
- OS Version: macOS 10.15.6

Looks like after updating to Version: 1.47.2 **close buttons** and the **is_modified icons** (the bright circle appearing when you modify a file) are not displayed on editor tabs anymore.

![foo](https://user-images.githubusercontent.com/14820600/88198506-0e6ba700-cc44-11ea-8aaf-d8e2458d9d5c.png)

Steps to Reproduce:

1. Update to Version: 1.47.2
2. Open up a file

Not sure if it's a bug or a change in settings.

**Comment by ArturoDent** [comment]
I believe the close button only appears on hover over the tab (unless `Workbench > Editor : Tab Close Button` got set to `off` in which case it still wouldn't appear).

**Comment by floatingpurr** [comment]
In my case `Workbench > Editor : Tab Close Button` is already set to `right` but I can't see it. After the update, something changed. I'd like to restore the old behavior of tab icons.

**Comment by floatingpurr** [comment]
Ok fixed. Turned out that in my settings I had: 

`"workbench.editor.showTabs": false`

Removing it gets rid of my problem.
I do not know if it was introduced in the last update, or maybe if I accidentally activated this option (more probable).

Thanx
