### ISSUE TITLE
@deprecated support in TypeScript

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10316]
- VSCode Version: Code - Insiders 1.5.0-insider (dde41be0231d6f8397d1da969ddab351f137b833, 2016-08-08T06:03:58.264Z)
- OS Version: Darwin x64 15.6.0

Would be nice to be able to type @deprecated in comment on method (etc.) and have `vscode` be able to render the method with `strikethrough` style in both editor and intellisense

**Comment by jrieken** [comment]
That's something an extension should do using the [text decoration API](https://github.com/Microsoft/vscode/blob/joh/miniedits/src/vs/vscode.d.ts#L3255) esp since @deparated isn't part of the TypeScript spec

fyi @dbaeumer

**Comment by rcjsuen** [comment]
@jrieken Where is this "text decoration API"? Your hyperlink appears to be broken. Do you have a [canonical link](https://help.github.com/articles/getting-permanent-links-to-files/) to the relevant file and line number?

**Comment by jrieken** [comment]
there you go: https://github.com/Microsoft/vscode/blob/0c59c951f4e384c1387c72b304e526b1469d5bdd/src/vs/vscode.d.ts#L1074
