### ISSUE TITLE
Debugged extension doesn't show its configuration page

### ISSUE THREAD

**Issue by PELock** [microsoft/vscode#103162]
Version: 1.48.0-insider (user setup)
Commit: 0a7364f00514c46c9caceece15e1f82f82e3712f
Date: 2020-07-22T05:49:27.463Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Create new VScode extension
2. Create configuration settings in package.json
3. Run extension in debug mode F5 
4. A new instance of VScode is open with the debugged extension activated
5. You won't be able to find the debugged extension on the extension list
6. You won't be able to find the debugged extension settings

So the problem is - you are not able to see the extension settings page while the extension is debugged. You need to temporarily pack the extension to `vsix` format and install it manually to be able to see how its configuration panel looks like or to even try the configuration settings. This is a half-way solution to debug extensions with configuration options.

Solution:

1. Extension should be visible in the VScode debugged session under Extension list, maybe with @debugged label so it's possible to open its configuration page

**Comment by gjsjohnmurray** [comment]
>     6. You won't be able to find the debugged extension settings

Are you expecting to access the extension settings via the context menu on the gearwheel icon alongside the extension (not) in the list on the Extensions view?

Instead, open the Setting Editor, expand the Extensions section. You should find in there the section contributed by the extension you are debugging.

**Comment by PELock** [comment]
Meh, you are right, I've been looking for this everywhere...

I think it would be easier if it was listed as a temporary extension in the left side panel under "@debugged" label

Thank you for your help.
