### ISSUE TITLE
Can't see "Turn On Preferences Sync..." in bottom-left  gear-menu list

### ISSUE THREAD

**Issue by lexxl** [microsoft/vscode#103101]
Issue Type: <b>Bug</b>

My current version of VS Code is 1.47.2 and still I have no such item in the menu.
I have 'Accounts' icon above the 'Manage' icon in the bottom left corner, but see no option to sign-in.

See attached screenshot:
![image](https://user-images.githubusercontent.com/14275924/88190962-99986d00-cc43-11ea-82f6-55b806edf461.png)

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (3.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
vscode-eslint|dba|2.1.8
githistory|don|0.6.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
auto-close-tag|for|0.5.8
vscode-test-explorer|hbe|2.19.1
rest-client|hum|0.24.1
mssql|ms-|1.9.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
sqltools|mtx|0.22.10
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0

</details>

**Comment by IllusionMH** [comment]
/question

Settings sync is still in development and available only in Insiders builds https://code.visualstudio.com/insiders/

See docs for details https://code.visualstudio.com/docs/editor/settings-sync
