### ISSUE TITLE
Please support the automatic completion of the javaScript method in the html file

### ISSUE THREAD

**Issue by mxm646690173** [microsoft/vscode#103138]
Please support the automatic completion of the javaScript method in the html file，for example:

I want to use the splice method of javaScript in the html file, but it will not automatically prompt. Only in the file named .js or .ts will he automatically prompt. It seems that the js in the html is isolated.

**Comment by ArturoDent** [comment]
You should show your code.  This works for me to provide all the array methods in an html file:

```
<script>

    let arr = [];   // did you initialize the array variable so vscode could recognize it as  an array?

    arr.  (get all intellisense array methods here when type the .)

</script>
```

**Comment by mxm646690173** [comment]
抱歉，这是我的问题，我找到了他，因为我正在使用vue渲染HTML，会由于没有声明变量，导致code无法提示

**Comment by mxm646690173** [comment]
Sorry, this is my problem, I found him, because I am using vue to render HTML, the code cannot prompt because there is no variable declaration
