### ISSUE TITLE
Ability to search for text across files in the workspace

### ISSUE THREAD

**Issue by pjuangph** [microsoft/vscode#103118]
When you use vs code to open a folder. I would like the ability to do CTRL+F and search for a text in any readable file in the open folder.

**Comment by ArturoDent** [comment]
Shift+Alt+F will do that if the folder is focused in the Explorer (or you can right-click on that folder and there is a menu item `Find in Folder...`

`filesExplorer.findInFolder` is the command if you wish to rebind it.  Ctrl+F does have many other uses depending on the context.


To rebind if you wish to Ctrl+F:

```
  {
    "key": "ctrl+f",
    "command": "filesExplorer.findInFolder",
    "when": "explorerResourceIsFolder && explorerViewletVisible && filesExplorerFocus && !inputFocus"
  },
  {
    "key": "shift+alt+f",
    "command": "-filesExplorer.findInFolder",
    "when": "explorerResourceIsFolder && explorerViewletVisible && filesExplorerFocus && !inputFocus"
  },
```

Is that sufficient for you or is there a different workflow you were looking for?

**Comment by pjuangph** [comment]
I think this works. I didn't know CTRL+SHFT+F was a feature.
