### ISSUE TITLE
[shellscript] Bash highlighting bug

### ISSUE THREAD

**Issue by hm1992** [Microsoft/vscode#10314]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11

Steps to Reproduce:

1. Open a bash script with 
```
#!/usr/bin/env bash

DEVELOPER=$(xcode-select -print-path)
LIPO=$(xcrun -sdk iphoneos -find lipo)
```
2. Highlighting is wrong (all of second line is red like a string

**Comment by aeschli** [comment]
Fixed by c927cca3656cb71727c40cb0bc1a2609574aeb3f
