### ISSUE TITLE
regarding unsupported file type 

### ISSUE THREAD

**Issue by techjunaid** [microsoft/vscode#103136]
Issue Type: <b>Bug</b>

Vs code showing unsupported in my pc and also giving me error that your installation is corrupt please reinstall. i have been reinstall vs code many times but the problem occurs ....

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-16T14:30:29.392Z)
OS version: Windows_NT ia32 10.0.19041

<details>
<summary>System Info</summary>

**Comment by gjsjohnmurray** [comment]
Any antivirus messing with the installed files?

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?

**Comment by techjunaid** [comment]
Yes,  
![IMG20200723135937](https://user-images.githubusercontent.com/53346421/88266548-0156c280-cced-11ea-91cd-d991c7e7ce45.jpg)

**Comment by joaomoreno** [comment]
What extensions do you have installed?

**Comment by techjunaid** [comment]
> What extensions do you have installed?

Only inbuilt extensions have installed of vs code

**Comment by joaomoreno** [comment]
Let's try once again: uninstall VS Code. Then, restart your machine. Then install it. Then let me know if the notification still shows up.

**Comment by techjunaid** [comment]
> Let's try once again: uninstall VS Code. Then, restart your machine. Then install it. Then let me know if the notification still shows up.

i have done this many times but the problem not solved, 
I have replaced vs from 64 to 32 but the same problem occurs.

**Comment by joaomoreno** [comment]
I'm sorry but I do not know what software is causing the corruption of VS Code's installation on your machine. Unfortunately you're going to have to find that out in order to fix the issue.
