### ISSUE TITLE
Debugger crashed after program done.

### ISSUE THREAD

**Issue by nanixne** [microsoft/vscode#103107]
- VSCode Version: 1.47.x (1.46.x are all fine)
- OS Version: Windows 10
- Node 14.3.0 or later, (14.2.0 or earlier are all fine)

Steps to Reproduce:

1. node.js is 14.3.0 and later (14.6.0), 14.2.0 do not have this issue 
2. and when I just direct run `node app.js` or `node --inspect app.js` in command line (as well as VSCode terminal) , everything goes well. (app.js is my program)
3. run app.js in vscode debugger by press F5, code run correctly, but it has some error messages after my program last output. sorry I cannot provide my app.js code, but it seems after I comment some `await fsPromise.writeFile`, the messages are gone. 
**all these ONLY happen when I run app.js in VSCode debugger[1], VS Code 1.47.x[2] and Node 14.3.0[3]. (all three need meet together)**

error message is

Debugger listening on ws://127.0.0.1:51841/4fb8eedf-3d50-4eac-911a-79b7f1a06526
For help, see: https://nodejs.org/en/docs/inspector
undefined:0

illegal access
FATAL ERROR: 
node::inspector::Agent::ToggleAsyncHook Cannot toggle Inspector's AsyncHook, please report this.
 1: 00007FF6D057FF3F napi_wrap+110015
 2: 00007FF6D0525F36 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::NumberOfElementsOffset+33350
 3: 00007FF6D0526D06 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::NumberOfElementsOffset+36886
 4: 00007FF6D05265A9 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::NumberOfElementsOffset+35001
 5: 00007FF6D04328FC v8::internal::Debug::ArchiveSpacePerThread+43164
 6: 00007FF6D084CB17 v8_inspector::V8Inspector::Counters::getCounterPtr+100967
 7: 00007FF6D083E2CF v8_inspector::V8Inspector::Counters::getCounterPtr+41503
 8: 00007FF6D082DA71 v8_inspector::V8StackTraceId::ToString+56689
 9: 00007FF6D082DC04 v8_inspector::V8StackTraceId::ToString+57092
10: 00007FF6D043061D v8::internal::Debug::ArchiveSpacePerThread+34237
11: 00007FF6D04337CA v8::internal::Debug::ArchiveSpacePerThread+46954
12: 00007FF6D0430A70 v8::internal::Debug::ArchiveSpacePerThread+35344
13: 00007FF6D041CE40 std::basic_ostream<char,std::char_traits<char> >::put+3200
14: 00007FF6D041D2E9 std::basic_ostream<char,std::char_traits<char> >::put+4393
15: 00007FF6D041D894 std::basic_ostream<char,std::char_traits<char> >::put+5844
16: 00007FF6D041D0D6 std::basic_ostream<char,std::char_traits<char> >::put+3862
17: 00007FF6D057E2EE napi_wrap+102766
18: 00007FF6D057E3D5 napi_wrap+102997
19: 00007FF6D056EC58 napi_wrap+39640
20: 00007FF6D057EC19 napi_wrap+105113
21: 00007FF6D05A0A48 node::FreeEnvironment+72
22: 00007FF6D04DF9C4 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet,1>::NumberOfBucketsOffset+9684
23: 00007FF6D05537F0 node::Start+288
24: 00007FF6D03B678C RC4_options+339596
25: 00007FF6D133F8CC v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+156316
26: 00007FF9B6377974 BaseThreadInitThunk+20
27: 00007FF9B6ACA271 RtlUserThreadStart+33
Process exited with code 134

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
See https://github.com/nodejs/node/issues/27261

/duplicate
