### ISSUE TITLE
"Stage Selected Lines" missing!?

### ISSUE THREAD

**Issue by SrTobi** [Microsoft/vscode#10315]
In previous versions I was able to select `Stage Selected Lines` from the `...`-menu in the git diff editor. This menu item is now missing... maybe it was removed or I am too blind to find it... so how can I stage only the selected lines?

**Comment by bpasero** [comment]
It is still there in the same spot if you are using .4.

**Comment by SrTobi** [comment]
...Wut? I swear it wasn't there yesterday :smile:. I am using this option for month now and there is no way that I have overlooked it :expressionless:... Nevertheless thanks. I will reopen the issue if this happens again.

**Comment by bpasero** [comment]
Nevermind, we might have an issue with contexts and the menu so we are still looking into this area.
