### ISSUE TITLE
waste of time 

### ISSUE THREAD

**Issue by yashpatwa60** [microsoft/vscode#103149]
We have written the needed data i
Issue Type: <b>Performance Issue</b>

when I close the vs code it starts to update and after that, it uninstalls automatically sending an error message and I have to install it once again,
also, live server plugin does not work whenever I click on go-live nothing happens, I tried to manually add IP but,

VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:42:53.386Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    87	  5044	code main
    0	    69	 14656	   shared-process
    0	    66	 16916	   window (Issue Reporter)
    0	    14	 18736	   electron-crash-reporter
    0	   155	 19200	   window (default.html - Bootstrap - Visual Studio Code)
    0	    67	 13152	     extensionHost
    0	    54	 39572	       "C:\Users\91787\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\91787\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=13152
    0	    11	 46412	     watcherService 
    0	    11	 74352	       console-window-host (Windows internal process)
    0	    33	 72464	     searchService
    0	   141	 20104	   gpu-process
    0	    25	 72000	   utility
    0	    11	 75772	   C:\Users\91787\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-17299e413d5590b14ab0340ea477cdd86ff13daf.exe /verysilent /update="C:\Users\91787\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-17299e413d5590b14ab0340ea477cdd86ff13daf.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	    36	 12036	     "C:\Users\91787\AppData\Local\Temp\is-0L6BA.tmp\CodeSetup-stable-17299e413d5590b14ab0340ea477cdd86ff13daf.tmp" /SL5="$461544,56782182,168960,C:\Users\91787\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-17299e413d5590b14ab0340ea477cdd86ff13daf.exe" /verysilent /update="C:\Users\91787\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-17299e413d5590b14ab0340ea477cdd86ff13daf.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (default.html - Bootstrap - Visual Studio Code)
|    Folder (Bootstrap): 8 files
|      File types: html(2) json(1) css(1) js(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details>
nto your clipboard because it was too large to send. Please paste.

**Comment by joaomoreno** [comment]
> an error message

Can you show me a screenshot of the error message?

**Comment by HakanKartal** [comment]
I don't know if this will be of any help, but i would like to add that the ransomware protection of malwarebytes premium watches and prevents any file-changing of sorts in the local AppData folder, where for most people vscode resides inside. when you get the "try again" dialog, disable your anti-ransomware and (and disable anti-malware just in case aswell) in malwarebytes, hit try again, and it should go through. (Be sure to enable it right after again!)

This was my fix anyways, it might not just be related to only malwarebytes. I've also added the entire vscode folder to my exceptions in malwarebytes, but i don't know if this will fix the issue necessarily (yet).

Hope it helps! 😄
