### ISSUE TITLE
Microsoft privacy issue

### ISSUE THREAD

**Issue by medmedin2014** [microsoft/vscode#103159]
You claim your source is open source and free of spying telemetry, but your binaries are packaged with many spying options that collect users code and behavior, even after disabling (hoping it is disabled) all telemetry options found on many blogs I still found that the process is connecting to internet and sending and receiving some data ?
I use C# extension with VScode, is this spying behavior related to the extensions ? I even don't have auto updated enabled !
Why every product related to Microsoft is armed with spying tools that users can't disable ?
Are you giving a free tool to get free privacy data from users to sell it ?

**Comment by CoffeeFueledPanda** [comment]
@medmedin2014 ,

Like you I don't particularly care for programs calling home, however VScode is probably one of the few programs, that tells you in advance that you can switch it off. It also mentions that extensions can call home and/or collect data, this is just something they can't control. You can always just have a look through the extension(s) settings or their github page, and change the settings accordingly or disable the extension.

> " VS Code lets you add features to the product by installing Microsoft and third-party extensions. These extensions may be collecting their own usage data and are not controlled by the telemetry.enableTelemetry setting. Consult the specific extension's documentation to learn about its telemetry reporting and whether it can be disabled."
- Source: [https://code.visualstudio.com/docs/getstarted/telemetry](https://code.visualstudio.com/docs/getstarted/telemetry)

Hope this helps,

Stay safe out there :smiley:

**Comment by joaomoreno** [comment]
Thanks for the concerns @medmedin2014. And thanks @CoffeeFueledPanda for some information.

Please note that we take privacy very seriously and as such have dedicated a lot of effort into making the process both transparent and optional.

> your binaries are packaged with many spying options that collect users code and behavior, even after disabling (hoping it is disabled) all telemetry options found on many blogs I still found that the process is connecting to internet and sending and receiving some data ?

If you have **specific** details about this other than suspicion, I'd love to hear more about it.

In any case, you can find all information related to telemetry on VS Code on our documentation: https://code.visualstudio.com/docs/getstarted/telemetry

**Comment by medmedin2014** [comment]
@joaomoreno In fact your editor is always connecting to internet while all my telemetry options are disabled ! I'm on Manjaro with upgrades disabled and even auto NTP sync disabled and firewalld set to block any incoming connection from outside, so my machine can't and won't even try to connect to any website without my permission at all, but when I open VSCode I see many connections established inside wireshark !

**Comment by medmedin2014** [comment]
@joaomoreno It's like your claims to be able to totally disable telemetry (spying) are false ! And I see why there is VSCodium in the corner yelling hard !

**Comment by joaomoreno** [comment]
@medmedin2014 Did you disable **all** settings described in https://code.visualstudio.com/docs/getstarted/telemetry?

And if so, please provide firewall logs proving that VS Code is indeed making those connections. Run with `code --disable-extensions` to disable third party extensions.

**Comment by medmedin2014** [comment]
For me the editor is usefull only for dotnet core, for other languages there are better real open source alternatives.
But after reading the link you provided and found :

> In preparation for GDPR, we made several updates to VS Code

You first intentions were clearly evil towards users, and no one trusts you will abide by privacy laws !

> One question we expect people to ask is to see the data we collect. However, we don't have a reliable way to do this as VS Code does not have a 'sign-in' experience that would uniquely identify a user. We do send information that helps us approximate a single user for diagnostic purposes

Hmm you collect data but can't provide a way for users to view it at least before sending !

> We do send information that helps us approximate a single user for diagnostic purposes (this is based on a hash of the network adapter NIC) but this is not guaranteed to be unique.

Who believe you hash everything ! and even the hash is no longer a security standard to be trusted.

> VS Code collects telemetry about which extensions are being activated for what file types and what workspaces/folders. Specific folders are identified by computing a hash of each of the folder's Git remotes.
> We use this information to precompute anonymous recommendations.
> Some precomputed recommendations are shipped as part of the product while additional precomputed recommendations are fetched at runtime from an online Microsoft service.

I'm out. Good luck.

**Comment by rob3c** [comment]
@joaomoreno VSCode Insiders build still connects to `https://default.exp-tas.com/vscode/ab` even when telemetry is disabled. It does this every 30 minutes.

Here's a sample redacted request/response pair:
```
GET https://default.exp-tas.com/vscode/ab HTTP/1.1
Host: default.exp-tas.com
Connection: keep-alive
X-MSEdge-ClientId: [REDACTED]
X-VSCode-TargetPopulation: insider
X-VSCode-Build: Visual Studio Code - Insiders
User-Agent: [REDACTED]
X-FD-Corpnet: 
X-VSCode-AppVersion: 1.48.0-insider
Accept: application/json, text/plain, */*
X-VSCode-Language: en
X-VSCode-ExtensionName: vscode-core
X-MSEdge-Market: 
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
If-None-Match: [REDACTED]
```
```
HTTP/1.1 304 Not Modified
ETag: [REDACTED]
X-Content-Type-Options: nosniff
X-ExP-TrackingId: [REDACTED]
X-MSEdge-Ref: [REDACTED]
Access-Control-Allow-Origin: *
Date: [REDACTED]
```

**Comment by joaomoreno** [comment]
@rob3c I believe that is a third party extension. Can you reproduce if you shutdown Code and restart with `code --disable-extensions`? If so, please file an issue to the extension.

**Comment by joaomoreno** [comment]
Actually you are 100% correct, it's a new feature which I wasn't aware of. Created this issue to follow up: https://github.com/microsoft/vscode/issues/104293
