### ISSUE TITLE
Branch from closed repository shows in status bar

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#103144]
I had two repositories open. I closed one by right clicking on the repository SCM tree item and choosing "Close Repository".
Now, the status bar still has the old branch in it. Since closing the repository I have used the SCM view to commit some changes in the still open repository.

![image](https://user-images.githubusercontent.com/38270282/88270630-360b4f80-ccd6-11ea-8981-a3bce2c84ed7.png)

**Comment by joaomoreno** [comment]
Great catch!
