### ISSUE TITLE
Editor context menu doesn't scroll

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#103169]
1. Open TypeScript file
2. Decrease workbench height such that it can't fit the entire editor context menu
3. Open editor context menu

🐛 It doesn't provide scrolling behavior in order to reach the overflowing actions

**Comment by nrayburn-tech** [comment]
This PR may be relevant here, https://github.com/microsoft/vscode/pull/91214.

**Comment by enricoreich** [comment]
Have the same issue and it would be really great if a solution could be found as soon as possible.

BTW: It is possible to go through all menu entries by using keyboard arrow buttons (up, down).
