### ISSUE TITLE
Franklin syntax-highlighting support

### ISSUE THREAD

**Issue by fusion809** [microsoft/vscode#103132]
Thanks for creating one of the finest text editors the world has ever known, and providing it to end-users for free. I'm using the VSCode to write the content for my [Franklin](https://franklinjl.org)-powered website and it'd be just fantastic if VSCode's Markdown syntax-highlighting appropriately syntax-highlighted my content files. Content files for Franklin websites are predominantly written in Markdown format (with the .md file extension), but with some additions. Namely:

* Content between single and double dollar signs (`$`, `$$`) is rendered using KaTeX (so LaTeX syntax-highlighting would be awesome). 
* Franklin allows users to insert Julia code blocks that will be evaluated while the website is being built. These code blocks look like this:

<pre>
```julia:./path/to/outputfile
code block
```
</pre>

currently these code blocks aren't syntax-highlighted as Julia code. To insert the output of evaluated Julia code blocks one uses the command:

```md
\output{./path/to/outputfile}
```

it would be awesome if that was syntax-highlighted too. 

* Franklin also supports some additional LaTeX-like commands like `\fig{./path/to/file}`, `\figalt{alt}{path}`, `\tableinput{header}{path}`, etc. 

Further information of what distinguishes Franklin-augmented Markdown and regular Markdown can be found on the Franklin official website https://franklinjl.org/syntax/markdown/ (also look at the other entries under syntax in the sidebar menu).

**Comment by mjbvz** [comment]
This seems like good extension candidate. VS Code's built-in markdown preview can be extended in a few different ways:

- https://code.visualstudio.com/api/extension-guides/markdown-extension
- https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example
