### ISSUE TITLE
Notebooks: explore dragging and holding a cell to join cells

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#103119]
We saw this come up on a user study and thought it was an interesting interaction we could explore. We sort of do this in the editor by selecting text and dragging the text (see line 43):

![image](https://user-images.githubusercontent.com/35271042/88224629-216b8080-cc1e-11ea-9a43-e5d775f0c1bc.png)

Here's a very rough mockup:

![image](https://user-images.githubusercontent.com/35271042/88227013-ce93c800-cc21-11ea-8826-e8f244d9b23e.png)

We would have to watch out for how this works with regular drag and drop and make sure it doesn't get accidentally triggered.

cc @rebornix

**Comment by roblourens** [comment]
Eh, we can experiment but I am very suspicious. I think the drop zone for normal DND is fairly narrow, and accidentally joining cells with this would be very annoying.
