### ISSUE TITLE
Cannot reload or quit VSCode after debugging extension on macOS

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#103179]
- VSCode Version: 1.47.2, 1.48.0-insider
- OS Version: macOS 10.15.6

Steps to Reproduce:

1. Start debugging https://github.com/REditorSupport/vscode-r-lsp
2. Quit the extension host window
3. Quit or reload the extension editor window nothing happens. I could only quit VSCode by force quit.

Following is a screencast to demonstrate the issue:

![Kapture 2020-07-24 at 0 35 58](https://user-images.githubusercontent.com/4662568/88313172-b6b56480-cd45-11ea-986c-132aba425bed.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
Cannot reproduce with 1.47.2 on macOS 10.15.6:

![2020-07-23_20-22-20 (1)](https://user-images.githubusercontent.com/1898161/88323404-7b556e80-cd22-11ea-8e45-b99a35ac721e.gif)

Does the problem also happen if you launch with all extensions disabled?

**Comment by renkun-ken** [comment]
Yes, it still happens if I launch with all extensions disabled.

I also tried only open the vscode-r-lsp project without open any files, and launch the debugger without open any files in the extension host, but unluckily it still occurs. 

I tried with debugging another extension but everything works well.

Something must happen in background for this specific project I work with.

**Comment by weinand** [comment]
As long As I cannot reproduce the issue, I'll not be able to investigate...

**Comment by renkun-ken** [comment]
I also tried with 1.48.0-insider and the behavior is exactly the same.

Is there any logging output I could put here to help?

**Comment by renkun-ken** [comment]
In the latest release, this problem no longer exists. Closing now.
