### ISSUE TITLE
Blank lines in Hovers are unexpectedly removed

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10311]
- VSCode Version: 1.4.0
- OS Version: Windows 10

A user of my extension raised [an issue](https://github.com/DanTup/Dart-Code/issues/41#issuecomment-238290657) reporting that blank lines are unexpectedly stripped from tooltips:

![Formatting lost](https://cloud.githubusercontent.com/assets/1078012/17488410/29739e5c-5d91-11e6-99d9-b1fcd1224348.gif)

This seems to be being done by Code. Is there something I need to do to preserve them?

Both this user and I would expect them to remain. An extension can strip them out if that's how it chooses to display them but it seems strange/unexpected if they're always stripped for us.

**Comment by jrieken** [comment]
stuff is being send through markdown...

**Comment by DanTup** [comment]
Does this mean it's intended or is this just notes on investigation?

**Comment by DanTup** [comment]
@jrieken Is it expected that contents indented with 4 spaces will be treated as code blocks? Currently they only seem to come through as code if they have explicit backticks around them, but not if just indented.

**Comment by DanTup** [comment]
Actually, I think they are coming from code (they're whiter than the rest), it's probably just because it doesn't know what language they should be.

**Comment by DanTup** [comment]
Ignore last comment; this is fixable by us :)

**Comment by DanTup** [comment]
@jrieken I think the fix for this may have introduced more spacing than expected. Check out this sample:

```
`/// _italic_ **bold**.

And some \`inline code\`.

* List item 1
* List item 2

	* Indented list item

Code blocks are supported

	final name = "Danny";
	print(name);

Links can be:

* http://www.just-a-bare-url.com
* [with the URL inline](http://google.com)
* [or separated out][ref link]

[ref link]: http://google.com

# A Header

## A subheader

### A subsubheader

#### If you need this many levels of headers, you're doing it wrong`
```

and here's how it renders:

![Hovers](https://cloud.githubusercontent.com/assets/1078012/18033706/bd661864-6d23-11e6-9341-b7528ae92a6a.png)

**Comment by jrieken** [comment]
That's a problem with list-tag-element we are tracking separately

**Comment by DanTup** [comment]
@jrieken Great; thanks. I can't find a case so if you know what it's called so I can subscribe to it let, let me know (not a big deal if not easy to find though). Thanks!

**Comment by DanTup** [comment]
@jrieken Did anything change in yesterday/todays Insiders that would cause this to come back? It doesn't look like there were any more changes to the file you updated, but in Insiders I'm seeing it broken again?

![Newlines](https://cloud.githubusercontent.com/assets/1078012/18140607/2e18f78e-6fae-11e6-9a59-28e31cd07e3c.png)

**Comment by DanTup** [comment]
Here's a screenshot from last week vs today:

![Hovers](https://cloud.githubusercontent.com/assets/1078012/18140789/ee35e89c-6fae-11e6-8b16-3c5ac14708b5.png)

The string I'm returning is:

```text
_italic_ **bold**.

And some \`inline code\`.

* List item 1
* List item 2

    * Indented list item

Code blocks are supported

    final name = "Danny";
    print(name);

Links can be:

* http://www.just-a-bare-url.com
* [with the URL inline](http://google.com)
* [or separated out][ref link]

[ref link]: http://google.com

# A Header

## A subheader

### A subsubheader

#### If you need this many levels of headers, you're doing it wrong
```

**Comment by jrieken** [comment]
@DanTup Do not comment on closed issues esp not with stuff like 'I also saw this thing'

**Comment by DanTup** [comment]
@jrieken Apologies, but I'm seeing the same issue that I raised this case for so I figured you'd rather re-open the existing case than get an exact dupe.

There are a couple of closed issues I commented on; should I always raise new issues even if they're the same or relating to the fix?

**Comment by joaomoreno** [comment]
@DanTup You might want to follow [#2330](https://github.com/Microsoft/vscode/issues/2330#issuecomment-243157831), I will give hover a well deserved facelift.

**Comment by DanTup** [comment]
@joaomoreno Cool; I was thinking the hovers could be tidied up a little :)

Markdown normally preserves normal space between paragraphs, lines aren't all shoved together. However I raised #11409 after @jrieken requested not to comment on closed issues, there's some better discussion about this there :-)
