### ISSUE TITLE
Wrap content in a div

### ISSUE THREAD

**Issue by ThePotato10** [microsoft/vscode#103193]
Often, I'll be editing some HTML, and I'll want to wrap content in another element, like a div. As it currently is, this is annoying to do. It would be great if there was a way to select a few tags, use a keyboard shortcut, and then have a `<div>` tag appear at the start and end of the selected tags

**Comment by ArturoDent** [comment]
Are you using the `Emmet: Wrap with Abbreviation` command?

**Comment by ThePotato10** [comment]
Thank you! I wasn't aware this feature existed
