### ISSUE TITLE
Tab in text editor and console plugin doesn't work

### ISSUE THREAD

**Issue by pochojordan** [microsoft/vscode#103140]
Hello,
With the new update when I tab to autocomplete or simple make a tab doesn't work, starts changing the cursor through the different visualcode menus.

I come back to previus version to work. 1.47.1

My OS is Ubuntu if that helps.

Thanks for your work.

**Comment by alexdima** [comment]
@pochojordan This is a feature that perhaps you have activated by accident. The action:
![image](https://user-images.githubusercontent.com/5047891/88281816-9acfa580-cce8-11ea-9aae-34be9a8ce273.png)

makes it that <kbd>Tab</kbd> switches from inserting tab characters or spaces to becoming a key to navigate through the UI elements, like menus, etc. When this is active, a status bar entry is rendered:
![image](https://user-images.githubusercontent.com/5047891/88281876-be92eb80-cce8-11ea-8ef2-8825bc349146.png)

The mode can be left by running the action again or by clicking on the status bar entry.

**Comment by pochojordan** [comment]
I'm so sorry, for wasting your time, it just happened to me when I updated the version.

Thanks for the help.
