### ISSUE TITLE
Synchronize Changes doesn't push git tags

### ISSUE THREAD

**Issue by jackHedaya** [microsoft/vscode#103281]
(I apologize in advance if this is considered a feature request or if this functionality was intended)

- VSCode Version: 1.47.2
- OS Version: macOS Catalina

Steps to Reproduce:

1. Add a git tag using `yarn version` or the like.
2. Press "Synchronize Changes "
3. Navigate to GitHub and see that the tag was not pushed.
4. In the directory, run `$ git push --tags` and the tags will be synced.

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by joaomoreno** [comment]
A booolean setting here would be good: `git.pushTags`.

**Comment by jackHedaya** [comment]
What should the setting default to?

**Comment by joaomoreno** [comment]
The current behavior: `false`.

**Comment by diablodale** [comment]
The setting `git.pushTags` is unknown to the settings text editor. In that editor, it does not appear in the intellifind, it is dim when fully typed, and has no assistive text. As if it wasn't in settings schema somehow.

```
Version: 1.52.0 (system setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by joaomoreno** [comment]
Sorry about that, the setting name ended up being `git.followTagsWhenSync`.
