### ISSUE TITLE
Ability to use settings sync when one of the account extensions is disabled

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#103238]
As a user I would like to disable one of the Microsoft Account or Github Authentication extensions and I can still use Settings Sync.

**Comment by aabbccddff9961** [comment]
Tanks

**Comment by aabbccddff9961** [comment]
> As a user I would like to disable one of the Microsoft Account or Github Authentication extensions and I can still use Settings Sync.

**Comment by sandy081** [comment]
To verify, before turning on settings sync

- disable any of the auth (Microsoft/Github) account extensions
- Make sure Turn on Settings Sync action is still available and you can turn on sync

**Note:** There is a separate issue to track disallowing disabling auth extension if settings sync is using it - https://github.com/microsoft/vscode/issues/103405

**Comment by sandy081** [comment]
Reverting this feature because of 

https://github.com/microsoft/vscode/issues/103507
https://github.com/microsoft/vscode/issues/103501

Proper fix needs Settings Sync feature to know until when to wait for the required auth providers are registered which depends on - https://github.com/microsoft/vscode/issues/103507

**Comment by sandy081** [comment]
To verify, before turning on settings sync

- disable any of the auth (Microsoft/Github) account extensions
- Make sure Turn on Settings Sync action is still available and you can turn on sync
- When both extensions are disabled, Turn on Settings Sync action is not available.

**Comment by lszomoru** [comment]
@sandy081, I have disabled both auth extensions yet I am still seeing the `Turn on Settings Sync` in the Gear and Accounts menus as well as in the command palette. Based on the verification steps that does not seem to be expected. Running Insiders:

Version: 1.49.0-insider
Commit: 00754e4babebc9ee5aa881234bc16366c4f32aa9
Date: 2020-09-02T05:43:25.834Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.0.0

**Comment by sandy081** [comment]
Good catch !!!. You shall see the action, not showing the action might confuse users. Instead an error is thrown while turning on sync.

**Comment by sandy081** [comment]
New steps to verify, before turning on settings sync

- disable any of the auth (Microsoft/Github) account extensions
- Make sure Turn on Settings Sync action is still available and you can turn on sync
- When both extensions are disabled, turning on settings sync action fails with an error.

Note: There is a known issue https://github.com/microsoft/vscode/issues/105955 if you turn on sync after enabling the auth extension.
