### ISSUE TITLE
Can't  delete 5000 Changes

### ISSUE THREAD

**Issue by alanhamid** [microsoft/vscode#103287]
We have written the needed data into your clipboard because it was too large to send. Please paste
Issue Type: <b>Bug</b>

When I try to delete these change instead of committing, I get the error msg:  Failed to remove, Hamid\AppData\Local\Comms\Unistore\data\7\a\60000000000000073701.dat C:\Users\Alan 
and, also 5000 other lines get out put:  
Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.27.0.windows.1 from C:\Program Files\Git\cmd\git.exe
> git rev-parse --show-toplevel
> git rev-parse --git-dir
Open repository: c:\Users\Alan Hamid
> git status -z -u
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git check-ignore -v -z --stdin
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git clean -f -q -- C:\Users\Alan Hamid\.gitignore
> git clean -f -q -- C:\Users\Alan Hamid\.vscode\argv.json C:\Users\Alan Hamid\.vscode\launch.json
> git clean -f -q -- C:\Users\Alan Hamid\.vscode\extensions\christian-kohler.path-intellisense-2.2.1\dist\path-intellisense-2.2.1.tgz
> git clean -f -q -- C:\Users\Alan Hamid\.vscode\extensions\ms-vscode.azure-account-0.8.11\.vsixmanifest C:\Users\Alan 

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (3.68GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by joaomoreno** [comment]
Don't delete those changes, that will delete files you don't want to delete!

You have accidentally created a git repository in your home folder: please delete the `c:\Users\Alan Hamid\.git` folder.
