### ISSUE TITLE
Import error appears for right imports

### ISSUE THREAD

**Issue by anton-marchenko** [microsoft/vscode#103237]
- VSCode Version: 1.47.2 (user setup)
Commit: 17299e4
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

- OS Version: Windows 7 Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Sometimes (I can not reproduce this bug explicitly) when I open some files, I see an error about wrong input (but actually import is correct):
![002](https://user-images.githubusercontent.com/45929621/88378603-00d03180-cdaa-11ea-9013-142ebbc367b1.png)
2. After I change the import path to wrong path:
![003](https://user-images.githubusercontent.com/45929621/88378670-20675a00-cdaa-11ea-8777-4ea30764a110.png)
3.  After I change the import wrong path to right path again and the error disappear:
![004](https://user-images.githubusercontent.com/45929621/88378706-3248fd00-cdaa-11ea-8b4f-3a92387710a0.png)

I used VSCode since January 2020 to this summer and everything works fine. It started to happen in this summer (maybe after some new VSCode updates).

Does this issue occur when all extensions are disabled?: I do not know because I can not reproduce this bug explicitly.

My extensions list:

![image](https://user-images.githubusercontent.com/45929621/88379716-15adc480-cdac-11ea-805a-ab0f54bc7cab.png)

**Comment by mjbvz** [comment]
It is not possible to investigate this without more info.

Please test with extensions disabled to see if one of them is causing this. You can also try enabling TS logging and then share the log when the issue happens:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
