### ISSUE TITLE
Cannot Search Extensions Since Update

### ISSUE THREAD

**Issue by geauxtigers** [microsoft/vscode#103220]
- VSCode Version: 1.47
- OS Version: Windows 10

Steps to Reproduce:

1.  Open VS Code
2.  Search for Extension

Does this issue occur when all extensions are disabled?: Yes

Since I updated to v 1.47, I am having an issue where I cannot search the Extensions.  I started my current version with with extensions disabled and still cannot search.  The Developer Tools output with extensions disabled is shown below.  I also installed the insiders and I can search but there .

After installing 1.47, after it loaded I found it odd that a github app window popped up and asked for my git credentials.  In addition, neither Chrome nor Firefox have been able to connect to github.com since the upgrade.  It is the same error as shown below by VS Code:  ERR_CONNECTION_RESET.

Any ideas?

![vs code error](https://user-images.githubusercontent.com/8951542/88357597-7e0b9000-cd31-11ea-9472-51c26ea01db6.PNG)

**Comment by sandy081** [comment]
Are you on latest stable release - 1.47.2 ?

Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by geauxtigers** [comment]
Thank @sandy081.  I was not on 1.47.2 but I did upgrade.  I received the same errors as shown in the previous post when loading VS Code normally. 

![vs code error](https://user-images.githubusercontent.com/8951542/88398181-9a87e680-cd8a-11ea-9590-9728644cf020.PNG)

I can view the python logo at the address you gave.  I have had my DNS set to 1.1.1.1 primary and 8.8.8.8 secondary for a couple of years.  I did confirm the settings are still in place.  I do believe it is some sort of network issue.  It is odd that it started immediately after the 1.47.0 update and the only impacts I have found are with VS Code, Chrome, and Firefox.  In the browsers, it also appears to be only with gihub.com or maybe, more specifically, http requests to github.com.  Edge is not impacted.  On Edge I can go to github with no issue.  That is the browser I am using right now.  I have several five step and seven step programs and have come across nothing that resolves the issue (Dns settings, flushing dns, reinstalling programs, etc).  I am not behind a proxy.

Also, the address `https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery` shown as failed in VS Code console is accessible in Chrome.  So no issue there in the browser.  I receive the response

```
{"count":1,"value":{"Message":"The requested resource does not support http method 'GET'."}}
```

I said above it happened immediately after the 1.47.0 update.  But these issues were not the first thing that I noticed.  That day I  went into VS Code and it showed an update was available.  I applied the update (1.47.0) and VS Code was restarted.  When it restarted a github window asked for my credentials.  I resumed my coding but at that point VS Code was unusable.  The cursor lag was terrible.  I restarted my computer an tried again, experiencing the same lag.  I began using another computer to which the upgrade was not applied but kept trying to diagnose the issue on this computer.  VSC was consuming a high level of resources, constantly.  I am not sure why, but the cursor lag went away after about a week and here I am today.  Any further help is appreciated because after nearly two weeks of searching github, googling, etc I have made no progress.  I certainly appreciate your time!

**Comment by geauxtigers** [comment]
Anyone have a similar issue after the update?

**Comment by sandy081** [comment]
@deepak1556 Anything to do with chromium internals?

**Comment by bbttxu** [comment]
I experienced the issue of losing the ability to query marketplace going from 1.45.0 to 1.46.1. Ended up down-grading back to 1.45.0 and was able to access Marketplace again. 

I was able to query the marketplace search URL directly from the command line, outside of VSCode, with good results while on 1.46.1.

```
curl 'https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery' -H 'X-Market-User-Id: dfeb9512-24ef-4f7b-a5e7-838006ffe957' -H 'Accept: application/json;api-version=3.0-preview.1' -H 'Origin: file://' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.36.1 Chrome/69.0.3497.128 Electron/4.2.5 Safari/537.36' -H 'X-Market-Client-Id: VSCode 1.36.1' -H 'Content-Type: application/json' --data-binary '{"filters":[{"criteria":[{"filterType":8,"value":"Microsoft.VisualStudio.Code"},{"filterType":12,"value":"4096"},{"filterType":10,"value":"test"}],"pageNumber":1,"pageSize":50,"sortBy":0,"sortOrder":0}],"assetTypes":[],"flags":914}' --compressed
```

**Comment by geauxtigers** [comment]
@bbttxu did you have any issues outside VSC after you upgraded before downgrading?  Once I upgraded to 1.47, http(s) for github (only) quit working in Chrome and FF.  It seemed odd that after upgrading, a gihub window popped up.  My credentials were already available to VSC prior to the upgrade and only one other time do I remember having to resubmit credentials.  As I said, I am at a loss.  This error is driving me crazy and I am really tired of not being able to search extensions and having to use Edge to access anything github.  @sandy081 the chromium internals sound like a possibility but I cannot comment intelligently on that. :(

**Comment by bbttxu** [comment]
@geauxtigers i've had no other issues, though i'm in the process of setting up a new machine, so not really "up to speed" with the full workflow yet.

**Comment by geauxtigers** [comment]
@sandy081, I uninstalled all versions of Chrome, Firefox, and VSC.  After a fresh reboot I installed VSC and the errors remain as shown.

![Capture](https://user-images.githubusercontent.com/8951542/89129371-9cf0eb80-d4c2-11ea-8155-a5c53f2f29f2.PNG)

I did notice that after I re-installed VSC my extensions were still there .  Undoubtedly an uninstall is not a complete uninstall.  Any ideas of other actions that I can take?

**Comment by geauxtigers** [comment]
Any idea what the ERR_FILE_NOT_FOUND series of errors in the first block could be attributed to?

**Comment by sandy081** [comment]
> Undoubtedly an uninstall is not a complete uninstall. Any ideas of other actions that I can take?

@joaomoreno This is known limitation, is there an issue open for it ?

> Any idea what the ERR_FILE_NOT_FOUND series of errors in the first block could be attributed to?

No idea

@deepak1556 Can you please help in debugging these requests and why `ERR_CONNECTION_RESET` is thrown?

**Comment by deepak1556** [comment]
Sorry for the delayed response,

@geauxtigers can you start vscode with `--log-net-log=<path>/netlog.json` , make sure `<path>` is absolute. Perform some extension searches, quit the app. Please attach the log in this issue.

**Comment by geauxtigers** [comment]
@deepak1556 I seem to have resolved the issue though I cannot give much insight other than what I have provided.  I have uninstalled and reinstalled anything that I felt could be related.  I did try starting vscode with the command line option but no file was generated and I received no error for an invalid command line switch.  With that said, thanks for trying to help!

**Comment by deepak1556** [comment]
@geauxtigers can you share what you used as value for `--log-net-log` ?

> I seem to have resolved the issue

good to know,, can we close this issue then ?
