### ISSUE TITLE
console.error prints error message twice

### ISSUE THREAD

**Issue by vsDizzy** [microsoft/vscode#103282]
![image](https://user-images.githubusercontent.com/5798340/88437450-28a5b080-ce0f-11ea-9acf-bd327e51e9b7.png)

- VSCode Version: 1.47.2
- OS Version: Win 10

Steps to Reproduce:

1. Launch `app.js`:
```js
console.log('once');
console.error('twice');
```

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by connor4312** [comment]
Thanks for the issue, this is fixed in the [latest nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)

/duplicate
