### ISSUE TITLE
Ctrl + Click doesn't opens the clicked file

### ISSUE THREAD

**Issue by gurrrung** [microsoft/vscode#103222]
- VSCode Version: 1.47.2
- OS Version: Ubuntu 18 LTS

Steps to Reproduce:

1. Create two files as shown in the screenshot.
2. Try `Ctrl + Click` on a new file. It will open the same file in half split while it should open the clicked file.

![ezgif com-optimize](https://user-images.githubusercontent.com/30543444/88359364-ff920b00-cd8f-11ea-9963-d72fd152282d.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Works fine for me.

**Comment by gurrrung** [comment]
Yes, I can reproduce it in `1.48.0-insider`.

**Comment by isidorn** [comment]
Can you clarify your steps, from the gif it is not exactly clear.
So minimal exact steps would be great. Thanks

**Comment by gurrrung** [comment]
1) open two files side by side.
2) single click on any file.
3) Now, ctrl+click on any other file, it will open the wrong file.

**Comment by isidorn** [comment]
Works for me. Let's leave this open to see if other users also hit this. 
Thanks

**Comment by gurrrung** [comment]
Can we keep this open?

**Comment by isidorn** [comment]
Sure, we can keep it open for a bit more time and we see if more users hit this.
