### ISSUE TITLE
Not able to run files on terminal.

### ISSUE THREAD

**Issue by jaysalhan** [microsoft/vscode#103283]
Issue Type: <b>Feature Request</b>

Hi,
Whenever i try to run any file in terminal it throws this error

D:\exercise>node rough.js
'node' is not recognized as an internal or external command,
operable program or batch file.

kindly help me how to files on terminal. May be i am doing it in a wrong way.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sanket-bhalerao** [comment]
@jaysalhan it appears you don't have nodejs installed on your system.
verify node installation by running 'node -v'. if it is not there then install node and restart VSCode.
