### ISSUE TITLE
Feature request : Show/hide items in unstaged git changes

### ISSUE THREAD

**Issue by mvdcorput** [microsoft/vscode#103233]
I think a very cool feature of the git implementation in VsCode could be to enable showing/hiding items in unstaged git changes. Hidden items shouldn't be staged when using the UI to stage all / stage files.

The display of staged items should not custom show/hide any items in my opinion..

**Comment by joaomoreno** [comment]
Thanks for the suggestion! As we try to stay pretty aligned with Git, I'm not so sure introducing yet another set of changes concept is such a good idea.

If you want to ignore certain files from ever being pushed, you can always add them to gitignore.
