### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#103249]
* `yarn web`
* find all references
https://github.com/microsoft/vscode-references-view/blob/7d4f1bbd432efed0df77d968b7dd056019a4488b/src/history.ts#L81

**Comment by jrieken** [comment]
Adding @aeschli since his x-cross compile logic seems to be missing this

**Comment by jrieken** [comment]
The project is now free of nodejs dependencies
