### ISSUE TITLE
hideFromUser is not exposes in creationOptions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#103288]
https://github.com/microsoft/vscode/blob/c53cc6546f90d3d78e0e2f7510e8cdba5f2b691e/src/vs/workbench/api/common/extHostTerminalService.ts#L453-L460

https://github.com/microsoft/vscode-python/issues/11122

**Comment by Tyriar** [comment]
The property only shows up atm on the extension host that creates it. Python is running remote, ssh is local.

**Comment by isidorn** [comment]
Adding verified via code review
