### ISSUE TITLE
settings with "scope": "application" are being honored when specified as a workspace setting.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#103202]
- VSCode Version: 1.47.2 and 1.48.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Install the Python extension
2. Open a folder and add this to your *workspace* settings: "python.dataScience.runStartupCommands": "x=4"
3. Ctrl-shift-p -> Python: Create New Blank Jupyter Notebook
4. Open the notebook's Variable Explorer: 
![image](https://user-images.githubusercontent.com/11685408/88338135-c5bbf880-ccec-11ea-919e-cf400d752562.png)

Note that a variable 'x' set to 4 has been instantiated.

My understanding is that for an "application" scoped setting, it will not be honored if set in workspace settings. That doesn't seem to be the case as our package.json clearly indicates that this setting is set as such: 

```json
				"python.dataScience.runStartupCommands": {
					"type": "string",
					"default": "",
					"description": "A series of Python instructions or iPython magic commands separated by '\\n' that will be executed when the interactive window loads. For instance, set this to '%load_ext autoreload\\n%autoreload 2' to automatically reload changes made to imported files without having to restart the interactive session.",
					"scope": "application"
				},

```

CCing @sandy081 per @mattbierner 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
I cannot reproduce it by following above steps. But I see it only in the following case:

- Open a folder and add this to your workspace settings: "python.dataScience.runStartupCommands": "x=4"
- Install Python extension
- Ctrl-shift-p -> Python: Create New Blank Jupyter Notebook
- Open the notebook's Variable Explorer:
- Variable x = 4 is set

It happens only after extension is installed in the folder that has this variable, otherwise can't. 

Can you also please confirm?

**Comment by sandy081** [comment]
I have a sample extension that prints the value of `python.dataScience.runStartupCommands` setting when I have this configured in workspace settings

- When Python extension is installed, it always prints `undefined`
- When Python extension is not installed, it prints the value `x=4`
- After Python extension is installed, it prints `undefined`

Here is my sample snippet

```ts
vscode.window.showInformationMessage(vscode.workspace.getConfiguration().get('python.dataScience.runStartupCommands') || 'undefined');
	vscode.workspace.onDidChangeConfiguration(() => vscode.window.showInformationMessage(vscode.workspace.getConfiguration().get('python.dataScience.runStartupCommands') || 'undefined'));
	vscode.commands.registerCommand('test.helloworld', () => {
		vscode.window.showInformationMessage(vscode.workspace.getConfiguration().get('python.dataScience.runStartupCommands') || 'undefined');
	});
```

Can you please check if you are caching configuration and not updating it on configuration change?

**Comment by rchiodo** [comment]
Not sure what you mean by caching configuration. We listen for changes like so:

```
            this.workspace.onDidChangeConfiguration((event: ConfigurationChangeEvent) => {
                if (event.affectsConfiguration('python')) {
                    onDidChange();
                }
            })
```

When that fires we update our data.

We read the data like this:
```
        const initialConfig = this.workspace.getConfiguration('python', this.workspaceRoot);
```

**Comment by greazer** [comment]
@sandy081, No the requirement that the workspace setting needs to be set before installing the python extension is definitely not what I'm seeing. I will use another machine-scope setting as an additional example and I'll go through these steps right now to verify...

1) Uninstall VS Code Stable
2) Remove the ~/.vscode/extensions directory
3) Install VS Code Stable
4) Close any open folders.
5) Install the Python extension
6) Create a new folder on your system.
7) Open that folder in VS Code.
8) Open your workspace settings and set (assuming Windows): 
```json
"python.defaultInterpreterPath": "c:\\windows\\system32\\calc.exe"
```
9) Ctrl-shift-p -> Python: Create Terminal

If a normal python terminal opens and calc doesn't run, then reload VS Code and try step 9 again. 

This repro'd the problem for me, but interestingly if you then call the Create Terminal command again, the problem does *not* repro. If I then reload VS Code and do step 9 again it will again repro. 

As an added repro bonus :), if you then go into your workspace settings and change "calc.exe" to "notepad.exe" after reloading VS Code, creating a Python terminal will now launch notepad instead of calc.

**Comment by luabud** [comment]
I was able to reproduce this without opening the terminal, all I had to do was to activate the Python extension (by e.g. opening a Python file)

**Comment by sandy081** [comment]
Thanks for the steps. I can reproduce it. Will investigate.

**Comment by sandy081** [comment]
Very strange that this is not working at least from last 6 releases (may be more) and not found till then. I think catch here is that it occurs only when workspace folder is passed.

To verify:

- Open a folder in VS Code
- Add following settings in folder settings (`.vscode/settings.json`)
```
"testExtension.applicationScoped": "workspace"
"testExtension.machineScoped": "workspace"
```
- Write an extension with following contribution
```json
"activationEvents": [
		"*"
	],
	"contributes": {
               "configuration": {
			"title": "test",
			"properties": {
				"testExtension.applicationScoped": {
					"type": "string",
					"scope": "application"
				},
				"testExtension.machineScoped": {
					"type": "string",
					"scope": "machine"
				}
			}
		}
        }
```
and following code
```ts
export function activate(context: vscode.ExtensionContext) {
	vscode.window.showInformationMessage(vscode.workspace.getConfiguration(undefined, vscode.workspace.workspaceFolders![0].uri).get('testExtension.applicationScoped') || 'undefined');
	vscode.window.showInformationMessage(vscode.workspace.getConfiguration(undefined, vscode.workspace.workspaceFolders![0].uri).get('testExtension.machineScoped') || 'undefined');
}
```
- Create a VSIX and install this extension
- Verify that extension shows two notifications with `undefined` message.

**Comment by greazer** [comment]
Verified in 1.48.0-insiders
