### ISSUE TITLE
Allow Customization of Shortcut Menu

### ISSUE THREAD

**Issue by seujza** [microsoft/vscode#103234]
When I installed some kinds of extensions, my shortcut menu will have more and more items. it will be difficult for me to find a specific item. I hope vscode can allow me to select which items will be displayed in shortcut menu     
![image](https://user-images.githubusercontent.com/12457615/88377596-0d688000-cdd2-11ea-85a3-724c32456043.png)

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Amenus
