### ISSUE TITLE
nodeJS version cannot be upgraded for debugger 

### ISSUE THREAD

**Issue by pcanella** [Microsoft/vscode#10321]
- VSCode Version: 1.4.0 and lower
- OS Version: Mac OS X - El Capitan

Steps to Reproduce:

1. Write some Node 4.x compatible ES6
2. Try to run debugger
3. It will error out

I can't for the life of me figure out how to upgrade NodeJS JUST for the debugger. I can do it in the built in terminal just fine, but it does not reflect on the Debugger. I am still stuck on 0.10.x. Is this a known issue?

**Comment by weinand** [comment]
@pcanella by default the VS Code debugger launches 'node' (and expects to find this on the PATH). If you install a newer version of node, this should be on the 'PATH' and VS Code should pick it up automatically. 
You can override this behaviour by setting the 'runtimeExectuable' attribute in the launch configuration to a different executable (e.g. different node version).

**Comment by weinand** [comment]
@pcanella do you really have multiple versions of installed on your OS X?
If not, then the VS Code debugger should use the one and only node.

If VS Code uses a different version of node than the one found in a terminal, then it could be that your terminal uses a different 'PATH' as VS Code. Is this the source of your problem?

**Comment by pcanella** [comment]
@weinand adding my node v 4.4.5 PATH with a `runtimeExecutable` did the trick. Thanks so much! This can be closed.
