### ISSUE TITLE
Settings lost

### ISSUE THREAD

**Issue by Pherocity** [microsoft/vscode#103204]
- VSCode Version: 1.48 Insiders
- OS Version: Xubuntu 20.04, Windows 10

Steps to Reproduce:

1.Try to Sync Settings after having enjoyed the feature for a couple months.
Result: Unable to open 'settings.json (Remote) ↔ settings.json (Merges)': Unable to read file 'c:\Users\fadmin\AppData\Roaming\Code - Insiders\User\sync\settings\preview\settings.json' (Error: Unable to resolve non-existing file 'c:\Users\fadmin\AppData\Roaming\Code - Insiders\User\sync\settings\preview\settings.json').

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by xgdgsc** [comment]
I' ve seen this recently for 2 times. Have no idea how to find out why.

**Comment by sandy081** [comment]
Sorry for what happened. Is it possible to get the sync log while this happened? You can see the log using the command 

`F1 -> View -> Open View… -> Log (Preferences Sync)`

**Comment by catssie** [comment]
I had to wipe everything to get it to work since it was days between when you asked.  Just for the record, bugs without logs don’t go away magically.  This is some Trump level thinking here.

**Comment by xgdgsc** [comment]
I just lost it again after reboot, don' t think this log is helpful:
```
[2020-08-14 12:09:22.397] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-08-14 12:09:22.397] [userDataSync] [info] Auto Sync is disabled.
```

**Comment by sandy081** [comment]
Can you please disable all extensions and see if you can reproduce this?
