### ISSUE TITLE
Add a setting to allow Insiders users to use the Stable sync service

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#103246]
Eg. `sync.useStableService`

Not sure we ever created an issue for this?

**Comment by sandy081** [comment]
![Kapture 2020-07-28 at 17 33 19](https://user-images.githubusercontent.com/10746682/88692845-d3afb600-d0fe-11ea-8801-add990d54c9c.gif)

**Comment by Tyriar** [comment]
> `Settings Sync: Switch Settings Sync Service...`

How about `Settings Sync: Select Service...`

**Comment by sandy081** [comment]
To verify:

Use `Settings Sync: Select Service...` to switch between insiders / stable settings Sync service. Make sure switching is smooth and works as expected.

**Comment by alexr00** [comment]
See https://github.com/microsoft/vscode/issues/104067, I get conflicts and settings don't sync.

**Comment by sandy081** [comment]
@alexr00 Are you seeing any other issues other than the one you reported #104067 ? If not shall we close this item and track the other?

**Comment by alexr00** [comment]
#104067 covers what I am seeing

**Comment by sandy081** [comment]
To verify:

- Run command `Settings Sync: Select Service...` 
- Switch between insiders / stable settings Sync service. 

Make sure switching is smooth and works as expected (Settings sync continues to sync after switching)
