### ISSUE TITLE
Stuck in usable state, crashes from multiple reasons

### ISSUE THREAD

**Issue by Putr** [microsoft/vscode#103248]
- VSCode Version: 1.47.1
- OS Version: Manjaro 20.0.3

Steps to Reproduce:

1. Create new unsaved file, add ~20 lines of text, sort it (maybe, probably, can't check, VSCode stuck in unusable state)
2. This causes all unsaved files created after this *that have had content added* to become frozen. Opening and closing an unsaved file is fine. 

Things that cause a crash (i.e it closes and has to be restarted):

1. Clicking on Help > About
2. Pressing CTRL+A in the unsaved file
3. Trying to close the unsaved file 
4. Trying to close "All/Other" files
4. Trying to save the unsaved file
5. Submitting a bug report though the interface
6. Trying to open a different workspace
7. Trying to open a different project (project manager plugin)
8. Clicking CTRL+W in the file
9. Opening a new windows and trying to close the affected one (causes crash, opens both windows on restart)
10. Removing all content from unsaved file and trying to close it

What works:
- closing/opening any opened files
- committing and other git operations
- searching
- etc. most other things I tried

Other notes:
 - Opening developer tools > Console shows no errors when trying to do any of the abotu crash-causing things
 - All other logs under output show no errors

Does this issue occur when all extensions are disabled?: Yes

**Comment by Snakeyesz** [comment]
- VSCode Version: 1.47.2
- OS Version: Manjaro 20.0.3
- Kernel: 5.7.9-1-MANJARO

I'm also experiencing crashes in many (but not all) of the same situations. Just want to add i'm experiencing crashes when attempting to do a Replace All as well.

As op said noted, I can't seem to find any logs to help figure out this. If there is some other way to capture crash logs i would be happy to get those.

**Comment by deepak1556** [comment]
@Putr  @Snakeyesz are you using the snap builds of vscode ?

**Comment by Snakeyesz** [comment]
@deepak1556 I am. Below is an output of `snap list code` if that's any help. Also I've since updated to vscode version 1.47.3, but all the same crashes remain.

Name  Version   Rev  Tracking       Publisher  Notes
code  91899dce  39   latest/stable  vscode✓    classic

**Comment by deepak1556** [comment]
@Snakeyesz this would be the same issue as https://github.com/microsoft/vscode/issues/100940 , can you try the workarounds mentioned in that issue. Thanks!

**Comment by Snakeyesz** [comment]
@deepak1556 Looks like you're correct, I should have taken a better look through the open issues. I tried the workaround noted **[in this comment](https://github.com/microsoft/vscode/issues/100940#issuecomment-651225395)** and it worked perfectly. 

I believe this issue can be closed and marked as a duplicate.

Thanks for the help.

**Comment by deepak1556** [comment]
Thanks for confirming, I will wait for response from @Putr before closing the issue.

**Comment by Putr** [comment]
@deepak1556 thanks for waiting (was sick for a few weeks).

[This comment](https://github.com/microsoft/vscode/issues/100940#issuecomment-651225395) resolves the issues for me as well.

I was on Manjaro snap build of VSCode. 

Thank you for everything!
