### ISSUE TITLE
Too much cpu uses

### ISSUE THREAD

**Issue by VimLeSai** [microsoft/vscode#103298]
Both stable and insider version of vscode is taking too much CPU uses in windows while running node.js app. and make hang up in every 1-2 minutes. I had to  move in another ide because of this. please fix it faster
i also disabled lots of extension but didn't worked.

If possible please provide feature to see which extension uses what amount of memory and cpu and which one i running.

CPUs | Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 11.91GB (5.61GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
better-comments | aar | 2.1.0
project-manager | ale | 11.1.0
npm-intellisense | chr | 1.3.0
gitignore | cod | 0.6.0
bracket-pair-colorizer | Coe | 1.0.61
vscode-eslint | dba | 2.1.8
es7-react-js-snippets | dsz | 2.8.2
gitlens | eam | 10.2.2
EditorConfig | Edi | 0.15.1
vscode-npm-script | eg2 | 0.3.12
prettier-vscode | esb | 5.1.3
auto-rename-tag | for | 0.1.4
docthis | joe | 0.7.1
dotenv | mik | 1.0.1
vscode-autoprefixer | mrm | 3.0.1
debugger-for-chrome | msj | 4.12.9
material-icon-theme | PKi | 4.2.0
autoimport | ste | 1.5.3
front-end-ext-pack | Vim | 0.0.2
highlight-matching-tag | vin | 0.9.9
vscodeintellicode | Vis | 1.2.9

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`

**Comment by VimLeSai** [comment]
[720:0804/091824.739:ERROR:network_change_notifier_win.cc(141)] WSALookupServiceBegin failed with: 0
Version:          Code - Insiders 1.48.0-insider (5696babbc1dce41788bae04b1a04ad35140bebfb, 2020-08-03T05:51:31.732Z)
OS Version:       Windows_NT x64 10.0.20180
CPUs:             Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)
Memory (System):  11.91GB (3.29GB free)
VM:               0%
Screen Reader:    no
Process Argv:     
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    1       83    4848  code-insiders main
    0      116    1464     shared-process
    0       42   11620     utility
   14      304   13548     window (PriceFilter.jsx - textile-aadhar - Visual Studio Code - Insiders)
    0      114    2436       searchService
    0        7    2636       "C:\Program Files\Git\bin\bash.exe"
    0       12   10144         "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0        8    9936       console-window-host (Windows internal process)
    0       16   11504       watcherService
    0       12   16916         console-window-host (Windows internal process)
    0        8   14104       console-window-host (Windows internal process)
    0        6   15736       "C:\Program Files\Git\bin\bash.exe"
    0       12   16804         "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
   17      493   16408       extensionHost
    0       13    4684         c:\Users\VimLeSai\.vscode-insiders\extensions\tabnine.tabnine-vscode-2.9.0\binaries/2.9.2/x86_64-pc-windows-gnu/TabNine.exe --client=vscode --client-metadata clientVersion=1.48.0-insider pluginVersion=2.9.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 ide-restart-counter=1
    0     1199    3936           "c:\Users\VimLeSai\.vscode-insiders\extensions\tabnine.tabnine-vscode-2.9.0\binaries/2.9.2/x86_64-pc-windows-gnu/TabNine.exe" --client=vscode --client-metadata clientVersion=1.48.0-insider pluginVersion=2.9.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 ide-restart-counter=1 --inner
    0       12    5936           console-window-host (Windows internal process)
    0       94   14956         electron_node tsserver.js
    0      114   16704         electron_node eslintServer.js
   23      327   17928         electron_node tsserver.js
    0       89    1780           electron_node typingsInstaller.js typesMap.js
    0       94   18048         "C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=16408
    0       58   14972     electron-crash-reporter
    4      409   15912     gpu-process

Workspace Stats:
|  Window (PriceFilter.jsx - textile-aadhar - Visual Studio Code - Insiders)
|    Folder (textile-aadhar): 6343 files
|      File types: json(5671) js(166) less(87) webp(37) jsx(26) png(20)
|                  jpg(19) xml(17) ttf(12) svg(10)
|      Conf files: package.json(1)

**Comment by mjbvz** [comment]
Can you explain what 'too much cpu usage' means? Are there specific cases where the cpu usage seems too high?

**Comment by VimLeSai** [comment]
Yes, it happens while I'm running any node.js applications. Generally when I use windows's powershell or cmd it does not use that much cpu percentage but in vscode it frequently makes high cpu uses which also causes vscode to hang sometime while writing code or moving through files.

**Comment by mjbvz** [comment]
Do you mean running node applications using VS Code's integrated terminal?

**Comment by VimLeSai** [comment]
Yes

**Comment by mjbvz** [comment]
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

If you can share the log, I will take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by VimLeSai** [comment]
Will do.

**Comment by VimLeSai** [comment]
@mjbvz Hi,sorry for late reply. due to work schedule i moved into KDE Neon and it was working really nice, but now again i see the same problem. i will try to share everything i could.

I have already removed some extenstions. and not now i'm using KDE NEON and Stable Version of VSCode.

ExtensionLetency:
Roundtrip latency: 425.177ms
Up: 328.5 Mbps
Down: 67.7 Mbps

/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/snap/code/45/usr/share/code/../../lib/x86_64-linux-gnu/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
[356833:0927/202058.991653:ERROR:appcenter_api.cc(52)] expecting appcenter url prefix
[356833:0927/202100.096344:ERROR:gl_surface_glx.cc(90)] glXGetFBConfigs failed.
[356833:0927/202100.106777:ERROR:gl_surface_glx.cc(130)] Failed to get GLXConfig
[356833:0927/202100.108702:ERROR:gl_surface_glx.cc(479)] CreateDummyWindow(gfx::GetXDisplay()) failed
[356833:0927/202100.109046:ERROR:gl_initializer_x11.cc(148)] GLSurfaceGLX::InitializeOneOff failed.
[356833:0927/202100.125012:WARNING:x11_util.cc(1520)] X error received: serial 366, error_code 8 (BadMatch (invalid parameter attributes)), request_code 78, minor_code 0 (X_CreateColormap)
[356833:0927/202100.140870:ERROR:viz_main_impl.cc(152)] Exiting GPU process due to errors during initialization
[356974:0927/202100.168252:ERROR:appcenter_api.cc(52)] expecting appcenter url prefix
[356972:0927/202100.273336:ERROR:appcenter_api.cc(52)] expecting appcenter url prefix
Version:          Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:26:09.944Z)
OS Version:       Linux x64 5.4.0-48-generic
CPUs:             Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2494)
Memory (System):  11.61GB (1.78GB free)
Load (avg):       10, 6, 6
VM:               0%
Screen Reader:    no
![image](https://user-images.githubusercontent.com/27373883/94368030-bb104c00-00ff-11eb-8f9c-72f84de8605e.png)
Workspace Stats: 
|  Window (xyz.less - xyz - Visual Studio Code)
|    Folder (xyz): 3514 files
|      File types: json(1795) js(113) less(87) jsx(73) png(61) overrides(46)
|                  variables(46) jpg(12) svg(10) xml(9)
|      Conf files: gulp.js(1) jsconfig.json(1) package.json(1)

![image](https://user-images.githubusercontent.com/27373883/94367548-0aa14880-00fd-11eb-88da-11faff7dfd56.png)
![image](https://user-images.githubusercontent.com/27373883/94367882-e0508a80-00fe-11eb-9dd0-dfb4ae8be905.png)
![image](https://user-images.githubusercontent.com/27373883/94367331-9a45f780-00fb-11eb-8576-889dc61b7ce5.png)

**Comment by mjbvz** [comment]
@VimLeSai Can you please try [collecting the TypeScript log file](https://github.com/microsoft/vscode/issues/103298#issuecomment-675184016) and sharing that as well?

**Comment by VimLeSai** [comment]
@mjbvz give me some time i will do it with some opensource projects. so i don't have to reveal personal info about my projects.

**Comment by VimLeSai** [comment]
@weinand @mjbvz I think it was issue of my settings for ts server. it was before,
```
  "typescript.referencesCodeLens.enabled": true,
  "typescript.suggest.completeFunctionCalls": true,
  "typescript.tsserver.experimental.enableProjectDiagnostics": true, <---- this
  "typescript.tsserver.maxTsServerMemory": 4096,
  "javascript.suggest.completeFunctionCalls": true,
  "workbench.editor.closeOnFileDelete": true,
  "workbench.editor.limit.enabled": true,
  "Workbench.editor.limit.value": 6,
  "typescript.tsserver.log": "verbose" <----- due to this my log file of vscode was exceed 115GB
```

Due to this my cpu uses increased and also size of ts server's logs was increased.

Solution:
I have changed my setting into,

```
  "typescript.tsserver.experimental.enableProjectDiagnostics": false,
  "typescript.tsserver.maxTsServerMemory": 512,
  "typescript.tsserver.log": "off"
```
Now it's working fine. Thanks for support  @mjbvz.
