### ISSUE TITLE
Pasting in webview also pastes into the terminal

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#103200]
- VSCode Version: 1.47.2
- OS Version: Windows 10
Steps to Reproduce:

1. Download the vscode extension samples: (https://github.com/microsoft/vscode-extension-samples.git)
1. Modify the html in the cat coding webview sample to have a <textarea>
1. Run the cat coding webview
1. Give focus to a terminal
1. Give focus back to the cat coding text aread
1. Paste

Result will end up in both locations (terminal and webview text area)
![doublepaste](https://user-images.githubusercontent.com/19672699/88337716-049d7e80-ccec-11ea-8890-1f5aae1ec3e6.gif)

Does this issue occur when all extensions are disabled?: NA

**Comment by mjbvz** [comment]
I can't repo in the latest insiders builds (1.49). Tested on MacOS and Windows

Closing for additional verification

**Comment by rchiodo** [comment]
Verified it no longer repros with 1.49
