### ISSUE TITLE
F2 rename doesn't work in TypeScript

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#103213]
- VSCode Version: 1.48 - Insiders
- OS Version: macOS

Steps to Reproduce:

1. open VS Code repo
2. F2 rename a symbol
3. nothing happens

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I'm not able to reproduce this. Are there any logs in the developer console when this error happens?

**Comment by rebornix** [comment]
@mjbvz I'm not seeing any error in dev tools. Any thing else I should run to troubleshoot?

**Comment by mjbvz** [comment]
Is `rename` listed in the editor context menu or command palette? I want to make sure the JS/TS rename provider is actually registered

**Comment by rebornix** [comment]
Yes, Rename symbol is in command palette and context menu.

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/88425773-d334b980-cda4-11ea-9590-738a91c72933.png)

I'm seeing this status bar info: "could not load the TypeScript version at this path"

**Comment by mjbvz** [comment]
@rebornix Can you please share the `TypeScript` output. It should include the full file path of the server:

<img width="1725" alt="Screen Shot 2020-07-27 at 4 42 25 PM" src="https://user-images.githubusercontent.com/12821956/88602742-35512100-d028-11ea-82bf-a172e7ebe2e1.png">

**Comment by mjbvz** [comment]
I can't repo the rename bug but have seen the `could not load TypeScript at this path`. This can happen when you try using a workspace version of TypeScript but do not have TypeScript installed locally.

I've pushed a fix for this (it was a regression from getting the JS/TS extension to run on web). @rebornix Please let me know if you see rename not working again after

**Comment by Shubanshii** [comment]
> @rebornix I also ran into the same issue today, it appears Ctrl + F2 is the correct key combination for rename refactoring. The interactive playground page (Accessible via Help > Interactive Playground) lists the incorrect key (F2).

I ran into this issue today.  I'm fine pressing Ctrl + F2, but would like to see any issues with this tutorial cleared up.
