### ISSUE TITLE
vscode.ThemeColor("myext.colorStuff") does not return a hex color

### ISSUE THREAD

**Issue by warrenbuckley** [microsoft/vscode#103241]
## What
I am trying to build an extension that can theme different parts of my extension but using
`const myColor = new vscode.ThemeColor("myext.colorStuff");` only returns me an object with an id property of the key 'myext.colorStuff'

My expectation was for it to return a hex color that I can use. So if the theme property uses a reference to another theme color such as `debugIcon.startForeground` it would resolve that & return that hex colour value for me.

## Why
Well I have been trying to implement the suggestion for my other feature request to allow colored codicons in tree views that an extension contributes.

```
const colorThemeEvent = vscode.window.onDidChangeActiveColorTheme(e => {
	// Update our SVGs fill attribute on disk (Copies of the codicon)
	// That are used with vscode.TreeItem.iconPath for our tree

	// TODO: Need a way to find out the hex color stored in the ThemeColors ?!
	const startIcon = new vscode.ThemeColor("iisexpress.startIcon");
	const stopIcon = new vscode.ThemeColor("iisexpress.stopIcon");
	const restartIcon = new vscode.ThemeColor("iisexpress.restartIcon");

	// Help how can I get the color value stored in the theme 'workbench.colorCustomizations'
});
```

## Missing docs
I believe there is little documentation around extension authors contributing colors to their extension and how they can use/consume them in their own extensions, as I seem to be hitting a lot of barriers but an example or two on the documentation may help clear things up on how extension authors can use/consume them

https://code.visualstudio.com/api/references/theme-color#extension-colors

**Comment by usernamehw** [comment]
Related #32813

**Comment by aeschli** [comment]
Yes, https://github.com/microsoft/vscode/issues/32813 is what you want. ThemeColor is a handle to a color that you can use in various APIs (e.g. in the status bar)
