### ISSUE TITLE
jsconfig.json with suffix in file name is not opened in JSONC mode

### ISSUE THREAD

**Issue by pastelmind** [microsoft/vscode#103240]
- VSCode Version: 1.47.2 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Create a file named `jsconfig.build.json` in any directory.
2. Open the file with VS Code.
3. The file is opened with the "JSON" language mode (instead of the expected "JSON with Comments" mode).

Other file names, e.g. `jsconfig.test.json`, are also opened in "JSON" language mode.

In contrast, `tsconfig.json` is opened in "JSON with Comments" mode even if the file name contains suffixes, e.g. `tsconfig.build.json`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by NotWearingPants** [comment]
This is easily fixable, look at the relevant code:
https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/extensions/typescript-basics/package.json#L40-L50

Submit a PR 😊

**Comment by pastelmind** [comment]
Thank you. Is a build/test warranted, or would a direct PR suffice? Asking because I don't have a local build environment right now.
