### ISSUE TITLE
Native support for Deno

### ISSUE THREAD

**Issue by newtack** [microsoft/vscode#103250]
Currently there is a 3rd party VSCode extension and a Typescript plugin to have at least some support for Deno. 

But the VSCode experience for Deno is horrible.  And I am not even talking about debugging (which the insiders version works OK), but just regular Intellisense. There are big delays (> 10s), errors when there shouldn't be (have to restart VSCode, etc.) and several other issues.

I want native support for Deno in Typescript (file name with extension, which IS the browser standard) and built-in support in VSCode for Deno (import map, url based imports, etc.). It should work out of the box without 3rd party extension.

The momentum for Deno is growing and it is a very important Typescript platform going forward. Please help it by providing native support for it.

**Comment by mjbvz** [comment]
VS Code's built-in JS/TS support comes from the [TypeScript project](http://github.com/microsoft/typescript). Any improved Deno support would also have to come through TypeScript

Closing this as an upstream TypeScript issue. Please try following up there
