### ISSUE TITLE
Jupyter Notebook syntax coloring incorrect

### ISSUE THREAD

**Issue by evilpegasus** [microsoft/vscode#103299]
Issue Type: <b>Bug</b>

1. Create a Jupyter Notebook and open it in vscode
2. Type a code comment with "#" that contains "NOTE" in caps. For example:

#NOTE

"NOTE" will be incorrectly colored blue even though it should be green because it is in a Python comment.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (9.64GB free)|
|Process Argv|C:\Users\mingf\Desktop\git\Halite-2020|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
python-extension-pack|don|1.6.0
vsc-material-theme|Equ|32.8.0
prettier-vscode|esb|5.1.3
github-actions|for|0.0.1
html-preview-vscode|geo|0.2.5
gc-excelviewer|Gra|3.0.39
latex-workshop|Jam|8.11.1
vscode-peacock|joh|3.7.2
chat|kar|0.35.0
MagicPython|mag|1.1.0
csharp|ms-|1.22.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.7.96456
cpptools|ms-|0.29.0
vsliveshare|ms-|1.0.2478
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
material-icon-theme|PKi|4.2.0
java|red|0.65.0
vscode-yaml|red|0.9.1
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.23.0
jinja|who|0.0.8

</details>

**Comment by evilpegasus** [comment]
Image of bug:
![image](https://user-images.githubusercontent.com/50010165/88451278-36a50280-ce0a-11ea-8b38-05259b1cffe7.png)

**Comment by tusharsadhwani** [comment]
I'm pretty sure NOTE and TODO comments are supposed to be highlighted
