### ISSUE TITLE
Unable to read file "vscode-userdata"

### ISSUE THREAD

**Issue by joaoeudes7** [microsoft/vscode#103294]
Issue Type: <b>Bug</b>

Do not load some configs of editor, zoom not works, not found file of configs

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 5.7.9-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 1744)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|15.54GB (0.38GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
30-seconds-of-code|30-|1.0.0
better-comments|aar|2.1.0
sqlformatter|bre|0.0.7
better-toml|bun|0.3.2
path-intellisense|chr|2.2.1
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
es7-react-js-snippets|dsz|2.8.2
vscode-wasm|dts|1.3.1
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
crystal-lang|fau|0.4.0
auto-close-tag|for|0.5.8
lintlens|ghm|3.0.0
vscode-sublime-merge|gio|1.0.1
vscode-pull-request-github|Git|0.18.0
go|gol|0.15.2
todo-tree|Gru|0.0.178
terraform|has|2.1.1
vue-snippets|hol|0.1.11
vscode-git-tags|how|1.4.4
output-colorizer|IBM|0.1.2
vscode-heroku|iva|1.2.6
polacode-2019|jef|0.5.2
mips|kda|0.0.5
vscode-github|Kni|0.30.3
pomodoro|lky|1.1.3
smalise|Loy|0.0.8
git-graph|mhu|1.24.0
dotenv|mik|1.0.1
vscode-azureterraform|ms-|0.3.0
vscode-docker|ms-|1.4.1
python|ms-|2020.7.96456
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
cpptools|ms-|0.29.0
vsliveshare|ms-|1.0.2478
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.9
sqltools|mtx|0.22.11
color-highlight|nau|2.3.0
gremlins|nho|0.23.0
vetur|oct|0.25.0
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.9.1
synthwave-vscode|Rob|0.1.6
rust|rus|0.7.8
vue-vscode-snippets|sdr|1.9.0
git-merger|sha|0.4.1
vscode-scss-formatter|sib|2.0.1
vscode-fileutils|sle|3.0.1
vscode-taskexplorer|spm|1.26.3
code-spell-checker|str|1.9.0
sass-indented|syl|1.8.9
vue-html-syntax-highlighter|Tri|0.2.0
vscodeintellicode|Vis|1.2.9
vscode-conventional-commits|viv|1.10.1
vscode-ansible|vsc|0.5.2
vuetify-vscode|vue|0.2.0
vscode-wakatime|Wak|4.0.0
markdown-all-in-one|yzh|3.1.0
material-theme|zhu|3.8.5

(4 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
@joaoeudes7 Are there any steps to reproduce this issue?

Does this happen when you disable all installed extensions and try?
