### ISSUE TITLE
The terminal process "C:\WINDOWS\System32\wsl.exe" terminated with exit code: 4294967295.

### ISSUE THREAD

**Issue by jayeshgharat** [microsoft/vscode#103224]
We have written the needed data into your clipboard because it was too large to sen
Issue Type: <b>Bug</b>

Terminal error:
The terminal process "C:\WINDOWS\System32\wsl.exe" terminated with exit code: 4294967295.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|2.0.0
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
vscode-eslint|dba|2.1.8
react-native-react-redux|EQu|2.0.4
prettier-vscode|esb|5.1.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
terminal|for|0.0.10
go|gol|0.15.2
kite|kit|0.121.0
vscode-docker|ms-|1.4.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.7.96456
remote-wsl|ms-|0.44.4
debugger-for-chrome|msj|4.12.9
vscode-react-native|msj|0.16.1
material-icon-theme|PKi|4.2.0
java|red|0.65.0
vscode-yaml|red|0.9.1
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.22.0

(2 theme extensions excluded)

</details>
d. Please paste.

**Comment by Tyriar** [comment]
Can you share your settings.json file? Have you installed wsl properly? Try running wsl.exe in a cmd.exe window.
