### ISSUE TITLE
Terminal Not Working

### ISSUE THREAD

**Issue by ajithsubash** [microsoft/vscode#103227]
Issue Type: <b>Bug</b>

In the terminal not even me to type any letters

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.29GB free)|
|Process Argv|C:\Users\Cloobot-Ajith\Desktop\Process Mining|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|3.0.39
python|ms-|2020.7.96456

</details>

**Comment by LogicalBlonde** [comment]
I also started having this issue yesterday.  Both bash and PowerShell terminals are behaving this way.

**Comment by biddster** [comment]
Same. 1.47 has been poor for terminal integration. I have the same setup, using git bash on windows. 

The terminal frequently hangs up for minutes on end and I get odd characters at the prompt whilst it's unresponsive:

E.g.

```bash
Me@computer MINGW64 /c/git/MyProject
$ ddddddddddddDDDDDDDDDDDD
```

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal

Please also try updating git bash if you're using that.

**Comment by d-ac** [comment]
I'm having a similar issue

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-7634-generic (Pop OS 20.04)

![recording](https://user-images.githubusercontent.com/48023588/89059545-eb7e7880-d350-11ea-943a-2256c3e1ae81.gif)

pressing any keys or switching terminal does nothing

However, when in root mode:

![recording(1)](https://user-images.githubusercontent.com/48023588/89059704-30a2aa80-d351-11ea-8dc4-dfc65e23cd7c.gif)

not sure what's going on

**Comment by Tyriar** [comment]
@d-ac you may have run vscode as root once which messed up file permissions? Try checking the permissions of ~/.vscode and where ever `code` is installed.

**Comment by d-ac** [comment]
@Tyriar I did run it once as root in the past. I checked the 'code' file in /usr/bin (where it is installed for me) and the owner was root, tried changing to my user and the permissions from read-only to read and write but the issue persists.

I also checked ~/.vscode but the permissions seem normal.

**Comment by Tyriar** [comment]
Do you see any errors in the devtools (Help > Toggle Developer Tools) console when you open the terminal? If that doesn't give any clues a trace log of the launch might help https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by d-ac** [comment]
Yesterday this wasn't working but when i launched code with the --log trace flag it worked!, the integrated terminal worked fine.

I tried running code from terminal without the flags too and it also showed up the integrated terminal fine. It seems like it just does not work well from the shortcut provided by the OS after installation.

Is there any way to enable trace logging after launching code from the shortcut? to at least see what's going on when I launch it from there

**Comment by Tyriar** [comment]
@d-ac the only way to do that is by modifying the .desktop entry to include `--log trace` on Linux. I'd expect the same thing to happen though.

**Comment by dreth** [comment]
@Tyriar Hello!
So i actually got around to doing it, for speed purposes i had been launching it from console.

my code.desktop [desktop entry] block shows the following:
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
**Exec=/usr/share/code/code --no-sandbox --unity-launch --log trace %F**
Icon=com.visualstudio.code
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-empty-window;
Keywords=vscode;



and as for the integrated terminal opening, the code console returns the following when opening the console:

TRACE terminalInstance#ctor (id: 5) {}
workbench.desktop.main.js:sourcemap:1670   ERR A system error occurred (EACCES: permission denied, open '/proc/2635/environ'): Error: EACCES: permission denied, open '/proc/2635/environ'
workbench.desktop.main.js:sourcemap:1670 TRACE [storage state.vscdb] updateItems(): insert(Map(1) {workbench.panel.hidden => false}), delete(Set(0) {})
workbench.desktop.main.js:sourcemap:1670 TRACE [storage state.vscdb] Trace (event): BEGIN TRANSACTION
workbench.desktop.main.js:sourcemap:1670 TRACE [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('workbench.panel.hidden','false')
workbench.desktop.main.js:sourcemap:1670 TRACE [storage state.vscdb] Trace (event): END TRANSACTION

**Comment by Tyriar** [comment]
> workbench.desktop.main.js:sourcemap:1670 ERR A system error occurred (EACCES: permission denied, open '/proc/2635/environ'): Error: EACCES: permission denied, open '/proc/2635/environ'

Set the `terminal.integrated.inheritEnv` to true`
