### ISSUE TITLE
second editor opens when debugger starts

### ISSUE THREAD

**Issue by rvanbree** [microsoft/vscode#103263]
Issue Type: <b>Bug</b>

starting debugging on node/typescript project causes a new editor window with dupilcat source code to open.  filename.ts is opened but has the JS in tab instead of TS filename. 

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.8
githistory|don|0.6.8
json-tools|eri|1.0.2
docthis|joe|0.7.1
git-graph|mhu|1.24.0
vscode-docker|ms-|1.4.1
js-debug-nightly|ms-|2020.7.2317
sqltools|mtx|0.22.11
sqltools-driver-mysql|mtx|0.1.0
vscode-graphql|Pri|0.2.14
vscode-icons|vsc|10.2.0
material-theme|zhu|3.8.5

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Can you do two things?

1. See if the problem happens on our nightly build https://github.com/microsoft/vscode-js-debug#nightly-extension
2. If so, capture a trace log using these instructions:

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

/needsMoreInfo
