### ISSUE TITLE
Console Log is not showing Json Array in tree view if debug point is disabled

### ISSUE THREAD

**Issue by DebashishSaha** [microsoft/vscode#103214]
Steps : 
1. Run node js program  without debug point where console.log(JSON ARRAY) is there 
2.Now just before console.log put a debug point .
3. JSON ARRAY shows correctly in tree view

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
If yes can you please share exact steps with the minimal program so we see this issue?
