### ISSUE TITLE
"Sort By" in Extensions filter options intermittently is disabled or freezes/hangs entire interface

### ISSUE THREAD

**Issue by mureni** [microsoft/vscode#103232]
Issue Type: <b>Bug</b>

Steps to replicate:

1) Open Extensions panel
2) Search for anything that has at least 3 results
3) Select filter button/menu and hover mouse or use keyboard to highlight "Sort By"

Applies when accessing local extensions with remote extension disabled, and when accessing either local or remote extensions with remote extension enabled. 

Troubleshooting limitations used: 
 - Remote extension disabled to eliminate possibility of it being primary cause
 - Search options identical between tests
 - Window/panel sizes identical between tests
 - Window focus unchanged between search input and menu focus 
 
Accessing the "Sort By" menu will:
  a) Display fully functional options menu - Appropriate behavior
  b) Display entirely disabled options menu - May be appropriate behavior if menu is truly inapplicable, e.g. 0 or 1 result(s)
  c) Momentarily display entirely disabled options menu - Inappropriate behavior for all cases; confusing and inconsistent UX
  d) Cause the entire interface, other than base Electron window, to freeze/hang - Inappropriate behavior for all cases.

Experiences: 
The inappropriate behaviors (c and d) listed above happen more frequently with higher numbers of results of the search.
 - Using an uncommon term with 3 results, it took at least 54 attempts to access the "Sort By" menu before it showed one of the above "inappropriate" behaviors, usually disabled menu either consistently displayed or disappearing unexpectedly and unintentionally.
 - Using a more common term with 20 results, it took 6 attempts before increasingly inappropriate behaviors began to manifest, and 23 subsequent attempts before a complete freeze occurred. 
 - Using a very common term such as "theme" caused the interface to freeze or hang every single time the "Sort By" menu was accessed. 

No other menus seem to show these inappropriate behaviors under the same circumstances used in the above examples. 

VS Code version: Code - Insiders 1.48.0-insider (731f9c25632dbbf01ee3a7892ad9d2791fe0260c, 2020-07-24T05:57:10.466Z)
OS version: Windows_NT x64 10.0.20170

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.97GB (22.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
vscode-firefox-debug|fir|2.9.0
vscode-nginx-conf-hint|han|0.1.0
animate-css|Hri|1.0.0
vscode-react-typescript|inf|1.3.1
dotenv|mik|1.0.1
vscode-json5|mrm|1.0.0
vscode-docker|ms-|1.4.1
csharp|ms-|1.22.1
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
js-debug-companion|ms-|1.0.2
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
vscode-versionlens|pfl|1.0.8
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0
synthwave-vscode|Rob|0.1.6
vscode-nginx|sha|0.6.0
gitconfig|sid|2.0.1
move-ts|str|1.12.0
JavaScriptSnippets|xab|1.8.0

(4 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
I can see the sort options getting disabled but I do not see the freeze. 

<img width="632" alt="image" src="https://user-images.githubusercontent.com/10746682/88818285-d245c280-d1be-11ea-99d3-8531d9da66b8.png">

I added a fix to reuse sort actions instead of recreating them. This fix will be available in tomorrow's insiders. Please try out and see if you can repro again?
