### ISSUE TITLE
Node Debugger Consistently hangs

### ISSUE THREAD

**Issue by gfoltz** [microsoft/vscode#103275]
Issue Type: <b>Bug</b>

The new debugger in 1.47 needs to be reverted. It consistently hangs on me when executing our tests. I downgraded to 1.46 and it went away. Then VSCode auto updated and the problem is back.

Please turn off this new debugger until you have worked out all the issues. This is very painful.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.1.10
vscode-eslint|dba|2.1.8
githistory|don|0.6.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
copy-github-url|mat|0.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vim|vsc|1.16.0

</details>

**Comment by weinand** [comment]
You can get the previous node debugger by adding a `"debug.javascript.usePreview": false` to your settings.

**Comment by connor4312** [comment]
Can you do either of the following?

- If it's consistent, are you able to easily create or share a reproduction case?
- If not, a trace log using these instructions is also very useful 🙂 

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

/needsMoreInfo

**Comment by ValYouW** [comment]
The new debugger hangs on me as well. Trying to track down the issue it comes to a `console.log` command that just not returns. Adding this to my launch config "solve" the issue:
```js
"console": "integratedTerminal",
```
This happens on my server startup on debug mode where the logger is set to "verbose" and there is ton of logging. In order to confirm this is the issue I change the log level to "error" and debugger does not hang.
Hope it helps...

**Comment by connor4312** [comment]
That is issue https://github.com/microsoft/vscode/issues/102254

**Comment by connor4312** [comment]
I didn't think of it previously, but this is most likely a duplicate of https://github.com/microsoft/vscode/issues/102254#issuecomment-658247768
