### ISSUE TITLE
Can't build a new Extension

### ISSUE THREAD

**Issue by zflovedota** [microsoft/vscode#103244]
- VSCode Version:1.47.0
- OS Version:Windows 10 X64 

My First Extension Can't Work. (https://code.visualstudio.com/api/get-started/your-first-extension)

1.
> What type of extension do you want to create? New Extension (TypeScript)
> What's the identifier of your extension? helloworld
> What's the description of your extension? helloworld
> Enable stricter TypeScript checking in 'tsconfig.json'? Yes
> Setup linting using 'tslint'? Yes
> Initialize a git repository? Yes
> Which package manager to use? npm

2.Then, inside the editor, press F5  -> nothing appeared, just **building** .......**No new Extension**

![火星图片_20200724_191047](https://user-images.githubusercontent.com/36480715/88385927-ed40bd00-cde1-11ea-87fe-aebcb3e11823.jpg)

I've tried it on more than four computers.

3.However，When I choose JS.....  It will compile and run the extension in a new Extension.

> What type of extension do you want to create? New Extension (JavaScript)

![image](https://user-images.githubusercontent.com/36480715/88386278-a1424800-cde2-11ea-9d84-46f3071196e1.png)

Currently the package.json file looks like this(TypeScript):
```
{
	"name": "helloworld",
	"displayName": "helloworld",
	"description": "",
	"version": "0.0.1",
	"engines": {
		"vscode": "^1.47.0"
	},
	"categories": [
		"Other"
	],
	"activationEvents": [
        "onCommand:my.helloWorld"
	],
	"main": "./out/extension.js",
	"contributes": {
		"commands": [
			{
				"command": "my.helloWorld",
				"title": "Hello World"
			}
		]
	},
	"scripts": {
		"vscode:prepublish": "yarn run compile",
		"compile": "tsc -p ./",
		"lint": "eslint src --ext ts",
		"watch": "tsc -watch -p ./",
		"pretest": "yarn run compile && yarn run lint",
		"test": "node ./out/test/runTest.js"
	},
	"devDependencies": {
		"@types/vscode": "^1.47.0",
		"@types/glob": "^7.1.1",
		"@types/mocha": "^7.0.2",
		"@types/node": "^13.11.0",
		"eslint": "^6.8.0",
		"@typescript-eslint/parser": "^2.30.0",
		"@typescript-eslint/eslint-plugin": "^2.30.0",
		"glob": "^7.1.6",
		"mocha": "^7.1.2",
		"typescript": "^3.8.3",
		"vscode-test": "^1.3.0"
	}
}

```

Currently the launch.json file looks like this(TypeScript):
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			]
		},
		{
			"name": "Extension Tests",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--extensionTestsPath=${workspaceFolder}/test/suite/index"
			]
		}
	]
}
```
Help!

**Comment by rebornix** [comment]
Starting from @alexr00 as the task information is not helpful.

**Comment by alexr00** [comment]
@zflovedota your launch.json doesn't have any `prelaunchTask`. How are you building your extension?
