### ISSUE TITLE
Please add an unsaved indicator to the Zen Mode.

### ISSUE THREAD

**Issue by capedghost** [microsoft/vscode#103225]
In Zen Mode(hide tabs is on),there is no unsaved indicator:
![S20200724123034](https://user-images.githubusercontent.com/44280081/88361371-5f49df80-cdab-11ea-9f1c-2ab18b20f78b.png)
Please add an unsaved indicator next to the file name:
![S20200724123258](https://user-images.githubusercontent.com/44280081/88361171-cc10aa00-cdaa-11ea-9d8c-9f2ffeedde4b.png)
Like the title bar in normal mode:
![S20200724123400](https://user-images.githubusercontent.com/44280081/88361271-0c702800-cdab-11ea-9afa-4ce5d8da57c6.png)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by capedghost** [comment]
> This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

Okay,that feature is not important,it should be just on backlog.
And thanks for your work in vscode.

**Comment by MilanKladivko** [comment]
Do I really have to go solve it with an extension? Isn't it against the "zen" to have to think about if I saved or not or spam the save button after every change one makes?

To me, it's just a dot. It should be there in the first place, it doesn't make any sense to hide it. We shouldn't even have to talk about it.
To me, it's a bug. A long-forgotten bug.

Please fix it.

**Comment by MilanKladivko** [comment]
To save someone the effort, if you enable the status line when in zen, this extension works well: 
https://marketplace.visualstudio.com/items?itemName=esamatti.unsaved
