### ISSUE TITLE
debugger - unbound break point. 

### ISSUE THREAD

**Issue by rvanbree** [microsoft/vscode#103205]
Issue Type: <b>Bug</b>

Bode/Typescrip - new update I cannot attach debugger and set break points - says breakpoint is unbound. 

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

**Comment by connor4312** [comment]
Please do two things:

1. See if this still happens on our [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension)
2. If so, collect a trace log using these instructions:

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com


/needsMoreInfo

**Comment by rvanbree** [comment]
I followed these instructions.  Still had issue.

But then I tried something else. I had been launching app in hosted
terminal using npm then attached to process.  I noticed that the debugging
showed the process as a remote process.  So I added a npm launch to
launch.json ... that works as expected.  The terminal+attach had always
worked before.

So I assume attach is the issue?

Thanks for your help.

**Comment by connor4312** [comment]
Attaching in via launch.json will usually be more reliable, particularly in the presence of sourcemaps. We try to infer the right paths for attached process automatically, but particularly when dealing with sourcemaps they have to be set up 'just right' to map onto the disk.

Glad you got it working!
