### ISSUE TITLE
node_modules folder don't update automatic

### ISSUE THREAD

**Issue by microlv** [microsoft/vscode#103219]
node_modules delete one folder and reinstall ,  the new folder don't show
example:
node_modules has some folders
-@babel
-@rollup
-axios

delete @babel , them run "npm install", the @babel don't show again

**Comment by microlv** [comment]
FYI:
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
This is by design, we configure the setting for excluded folders in our file watcher by default to include `node_modules` to reduce CPU load since this folder is very dynamic. Does it reproduce if you change this setting from the default?
