### ISSUE TITLE
Invalid regular expression: Invalid escape

### ISSUE THREAD

**Issue by ddejohn** [microsoft/vscode#103266]
```
Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```

![](https://i.imgur.com/3Aqq4bD.png)

Steps to Reproduce:

1. Use this regex pattern:
```
```([\w\+\=\,\ \-\*\'\"]*)```
```
This pattern works online (using PCRE and Javascript as compilers) here: https://regex101.com/r/lRpdUq/3

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by roblourens** [comment]
This is probably from the Rust regex engine. It is stricter about unnecessary escapes. The quotes and the space, for example, don't need to be escaped.

**Comment by ddejohn** [comment]
I realize the escapes aren't necessary, and even without them I get the same error:

```
```([\w\+\=, \-\*'"]*)```
```

**Comment by roblourens** [comment]
Also the `=`
