### ISSUE TITLE
JavaScript debugger can't prettify git lens extension.js

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#103273]
Issue Type: <b>Bug</b>

This file:

extensions/eamodio.gitlens-10.2.2/dist/extension.js

If I say yes to prettifying it, it appears to never finish.

VS Code version: Code - Insiders 1.48.0-insider (8c426f9f3b6b18935cc6c2ec8aa6d45ccd88021e, 2020-07-23T05:40:23.559Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|--crash-reporter-id 28a909e2-0b30-47b4-bfa3-dcb1734aca95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
todo-tree|Gru|0.0.178
vscode-dotnet-runtime|ms-|0.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by connor4312** [comment]
Thanks for the issue. This is because of our dependence on js-beautify, which it appears ends up changing some structure of the minified code which prevents the comparison we use to build sourcemaps. I've been wanting to move us away from js-beautify for this reason. This is tracked in https://github.com/microsoft/vscode-js-debug/issues/371

/duplicate
