### ISSUE TITLE
Program 'tsc' failed to run

### ISSUE THREAD

**Issue by Dhivyadharani-DS** [microsoft/vscode#103252]
Issue Type: <b>Bug</b>

Create a Folder and create a sample ts file(app.ts) with just console.log("Hello")
In terminal run npm install -g typescript
once installed run "tsc app.ts"
Getting below error
Program 'tsc' failed to run: No application is associated with the specified file for this operationAt line:1 char:1

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
https://stackoverflow.com/questions/62816911/program-ng-failed-to-run
