### ISSUE TITLE
Crash on Insiders using Ubuntu 18.04

### ISSUE THREAD

**Issue by importnetminecraft** [microsoft/vscode#103276]
- VSCode Version: Insiders
- OS Version: Ubuntu 18.04 LTS dual boot

Steps to Reproduce:

1. Install vs code insiders
2. Try to open it
3. Notice it turns gray then closes preventing you from doing anything

Does this issue occur when all extensions are disabled?: Yes

**Comment by importnetminecraft** [comment]
This only happens on insiders and not on release btw.

**Comment by deepak1556** [comment]
Are you using the snap build of insiders ?

**Comment by importnetminecraft** [comment]
Yes I am

**Comment by deepak1556** [comment]
Thanks for confirming, this is a known crash issue with snap insiders, merging to https://github.com/microsoft/vscode/issues/103060
