### ISSUE TITLE
VS Code 1.47.2 can't update extensions automatically

### ISSUE THREAD

**Issue by pihglez** [microsoft/vscode#103291]
Issue Type: <b>Bug</b>

Can not update extensions automatically.
VS Code doesn't report almost anything but...
i.e.: can not update "ms-python.python" and also more extensions
It allows to download manually for a manual installation.
Boring error/bug...

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|11.3.1
project-manager|ale|11.1.0
vscode-sqlite|ale|0.8.2
atlascode|atl|2.6.6
vscode-python-docstring|aza|0.0.5
vscode-django|bat|0.20.0
kivy-vscode|Bat|0.5.5
path-intellisense|chr|2.2.1
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
python-snippets|cst|0.2.0
vscode-eslint|dba|2.1.8
template-generator-vscode|Den|0.4.1
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
vscode-gitignore-syntax|dun|0.1.2
gitlens|eam|10.2.2
pyfilesgen|ffa|1.0.2
code-runner|for|0.11.0
pythonsnippets|frh|1.0.2
glitch|gli|0.1.6
todo-tree|Gru|0.0.178
gitignore-templates|has|1.0.1
Python-autopep8|him|1.0.2
py-paste-indent|hye|0.1.2
output-colorizer|IBM|0.1.2
bridlensis|idl|1.0.1
nsis|idl|3.27.1
nsis-plugins|idl|1.3.0
pynsist|idl|0.9.1
python-coding-conventions|igr|0.0.4
r|Iku|1.4.3
fbp|leu|0.1.1
code-bitbucket-pipelines|luk|0.4.2
MagicPython|mag|1.1.0
python-path|mge|0.0.11
gitignore|mic|1.0.1
r|Mik|0.0.9
kvlang|Mon|0.0.5
theme-monokai-pro-vscode|mon|1.1.17
vscode-docker|ms-|1.3.1
vscode-language-pack-es|MS-|1.47.3
csharp|ms-|1.22.1
python|ms-|2020.7.94776
remote-wsl|ms-|0.44.4
vscode-typescript-next|ms-|4.0.20200717
python-docs|Muk|0.8.3
python-coding-tools|nil|1.0.3
autodocstring|njp|0.5.3
hide-gitignored|npx|1.1.0
vscode-gitignore-generator|pio|1.0.2
vscode-yaml|red|0.9.1
r-lsp|REd|0.1.6
vscode-qt-for-python|sea|0.4.2
open-in-browser|tec|2.0.0
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0
jinja|who|0.0.8
copy-python-path|yar|1.0.4

</details>

**Comment by sandy081** [comment]
Can you please update to latest (1.48.1) and check if you are still having this issue?
