### ISSUE TITLE
Shortcuts to open left panel should close it if it's already opened

### ISSUE THREAD

**Issue by haibison** [Microsoft/vscode#10327]
- VSCode Version: 1.4.0
- OS Version: Windows 10; Fedora 24

Steps to Reproduce:

1.  Open VSC, close the left panel (to only show the editor).
2. Press a shortcut to open the left panel, for examle: `Ctrl-Shift-E`, `Ctrl-Shift-X`...
3. Press the same shortcut in step `#2` again. VSC won't close the panel.

---

I often work with 150-columns per line code base, and not use the left panel much. So space is value. Would you consider adding support to close the left panel by shortcut, if it's already opened?

Thank you,

**Comment by bpasero** [comment]
Try with Ctrl+B

**Comment by haibison** [comment]
Thanks, that works  `:-)`

Since you added this issue to milestone Backlog, I'm not closing it.

**Comment by siva636** [comment]
Is it possible to customize this combination?
