### ISSUE TITLE
Improve app update options for people with metered connections

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode#103230]
I'm often working on a metered connection (LTE, no wired service available).

It looks like the Code team has previously decided it won't add support for pausing automatic app and extension updates on metered connections (that's unfortunate; I think you should support this Windows feature).

For extension updates, there's at least an acceptable fallback: leave `extensions.autoCheckUpdates` enabled, but disable `extensions.autoUpdate`. When I see the notification for an update, I can decide when to download it.

For app updates, it appears there's no equivalent option. Here are the options and descriptions for `update.mode`:

> - none: Disable updates.
> - manual: Disable automatic background update checks. Updates will be available if you manually check for updates.
> - start: Check for updates only on startup. Disable automatic background update checks.
> - default: Enable automatic update checks. Code will check for updates automatically and periodically.

If the descriptions are accurate, my choices are to let Code download every update it sees, or to stop Code from checking for updates at all. There doesn't seem to be a check-but-don't-download option. That seems like a clear gap.

**Comment by joaomoreno** [comment]
@aaronadamsCA You definitely want `update.mode = manual`. This makes it that Code won't ever check for updates automatically, but it's up to you to run the `Check for updates` action when you are in a good network connection.

Maybe we need the equivalent for extensions.

**Comment by aaronadamsCA** [comment]
Sorry, did you mean the other way around, that Code needs the same _as_ extensions?

If so, I'd be all for that; unbundling `autoCheckUpdates` and `autoUpdate` for app updates would generally solve my problem.

I still want to know as soon as an update is made available, especially if it's a security update; then I can head to a cafe and use their Wi-Fi to download the update. (I never meant to become a shut-in living off LTE, but COVID-19 had other plans!)

**Comment by sandy081** [comment]
> For extension updates, there's at least an acceptable fallback: leave extensions.autoCheckUpdates enabled, but disable extensions.autoUpdate. When I see the notification for an update, I can decide when to download it.

@joaomoreno it seems user is asking for configuring app updates and extension updates can be configurable

**Comment by joaomoreno** [comment]
Merging with https://github.com/microsoft/vscode/issues/103451
