### ISSUE TITLE
word diff view: something similar to ms-office revisions

### ISSUE THREAD

**Issue by Nadano** [microsoft/vscode#103285]
Edited for clarity:

I'm trying to have people in my team work with git, and I believe it would make things way more clear for them to have diff results that are similar to the ones used in word revisions.

Looking into the options I believe "git diff --color-word=." is the most natural for people used to office tools, explained [here](https://medium.com/@porteneuve/30-git-cli-options-you-should-know-about-15423e8771df#7d7e)

![](https://miro.medium.com/max/671/1*Mb16aJnq46sv87QcYwZu-Q.png)

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/Docs/editor/versioncontrol#_vs-code-as-git-diff-tool

**Comment by Nadano** [comment]
Looking into the options I believe "git diff --color-word=." is the most natural for people used to office tools, explained [here](https://medium.com/@porteneuve/30-git-cli-options-you-should-know-about-15423e8771df#7d7e)

**Comment by cristian3d** [comment]
Upvoted! 

But, please, don't forget about this one https://github.com/microsoft/vscode/issues/3562 .  It'd be a huge improvement, and is a standard feature. Or at least comment why is not possible, so we stop dreaming about it :)

**Comment by hediet** [comment]
I think this shouldn't be too hard to implement.

My suggested attack plan would look like this:
* Add a new settings (e.g. `diffEditor.inlineView.inlineWordDiffs`) - default `false` (I think if this works well we can turn it on by default later)
* If set, diff hunks where each inner (character-level) range diff is single line and not too big shouldn't get the viewzone
* Instead, the deleted part should be rendered using a decoration and injected text.
