### ISSUE TITLE
editor.hide function not working on peek editor

### ISSUE THREAD

**Issue by skdeng** [microsoft/vscode#103269]
Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Create a new extension
2. Open the peek view using the `editor.action.peekLocations` command
3. Use `vscode.window.visibleTextEditors` to find the peek view editor (using document name or something)
4. Call `editor.hide()`

Expected: peek view editor will be hidden
Actual: nothing happens

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by skdeng** [comment]
`editor.hide()` has a comment saying that the function is deprecated and `workbench.action.closeActiveEditor` should be used instead. But it's not clear whether that command can be used to close a specific `vscode.TextEditor` object, rather than the active editor.

**Comment by jrieken** [comment]
Peek is a special editor and the generic closeActiveEditor won't work. You can need to execute the corresponding command, e.g. `closeReferenceSearch`
