### ISSUE TITLE
Initializing JS/TS language features taking too long

### ISSUE THREAD

**Issue by felixjb** [microsoft/vscode#103280]
Issue Type: <b>Bug</b>

On opening VSCode on a relatively large repository, the following message appears on the bottom bar:

> Initializing JS/TS language features

![image](https://user-images.githubusercontent.com/16679401/88436438-b4511a00-cdda-11ea-811d-d7d2897b13bf.png)

After a while, a notification appears with the following message:

> The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

![image](https://user-images.githubusercontent.com/16679401/88436391-97b4e200-cdda-11ea-801d-7c7f58dd782a.png)

One thing I noticed is that features like path completion don't work.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 5.4.0-42-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 4, 4|
|Memory (System)|15.54GB (0.17GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|11.3.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
testify|fel|1.4.0
todo-tree|Gru|0.0.178
rest-client|hum|0.24.1
vscode-peacock|joh|3.7.2
chat|kar|0.35.0
dotenv|mik|1.0.1
vscode-postgresql|ms-|0.3.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2478
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
vscode-versionlens|pfl|1.0.8
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.0.1
es6-mocha-snippets|spo|0.2.2
vscode-icons|vsc|10.2.0
quokka-vscode|Wal|1.0.310
vscode-import-cost|wix|2.12.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by felixjb** [comment]
Scenarios I tested:
- With VS Code **Insiders** with extensions **enabled**: JS/TS language features initialize after aprox. 30 seconds;
- With VS Code **Insiders** with extensions **disabled**: JS/TS language features initialize after aprox. 30 seconds;
- With VS Code (stable) with extensions **enabled**: JS/TS language features are NOT initialized;
- With VS Code (stable) with extensions **disabled**: JS/TS language features initialize after aprox. 30 seconds;

But, weirdly, after I opened VS Code (stable) with extensions disabled, using the available command for that, and then reloaded the window with all extensions back on, the JS/TS language features initialize after approximately 30 seconds.

Now, I don't know yet if that "fixes" it, it feels more like a temporary workaround.

**Comment by mjbvz** [comment]
Sounds like one of your extensions could be causing issues. Have you been able to track down which one specifically seems to cause problems?

Since you said your project is relatively large, it may take some time to process when you first load it. See [this documentation](https://code.visualstudio.com/docs/typescript/typescript-compiling#_working-with-large-projects) for some advice for working with larger projects

**Comment by klemenoslaj** [comment]
I have the same problem with VSCode recently and I figured out what is the cause of it in my case.

We are having a big monorepo and since we migrated our tsconfig.json to solutions style VSCode is hanging with `Initializing JS/TS language features`.
The exact same is happening with all extensions disabled, I even tried to reinstall VSCode completely and try it clean - did not help.

Small solutions configuration does not reproduce the issue tho.

**Comment by mjbvz** [comment]
@klemenoslaj can you please open a separate issue against typescript with more info about your project: https://github.com/microsoft/TypeScript/issues/new/choose

**Comment by felixjb** [comment]
> Since you said your project is relatively large, it may take some time to process when you first load it. See this documentation for some advice for working with larger projects

@mjbvz That puts me in a difficult position. The project is a production working application of the startup I work at. It would be very hard to put that much effort to separate code into smaller pieces given the complexity of our business domains.

Although, I haven't had that problem ever since I reloaded VSCode without extensions, and then with extensions again.

**Comment by mjbvz** [comment]
If that's the case, it wounds like one of your extensions could be causing it then? Any idea which one?

**Comment by felixjb** [comment]
I'll try to find out which one and answer here. Any other way simpler than disable one by one? 😰

**Comment by mjbvz** [comment]
TypeScript tslint is one candidate since it modifies the TypeScript server

You can also check running extension with the `Developer: Show running extensions` command

**Comment by felixjb** [comment]
@mjbvz I can't reproduce the bug anymore :cry: Maybe we could close the issue and reopen it if I find new information

**Comment by mjbvz** [comment]
Sounds good. Let me know if you start seeing this again
