### ISSUE TITLE
I can't copy the contents of the split editor

### ISSUE THREAD

**Issue by MyWorldG** [microsoft/vscode#103231]
Issue Type: <b>Bug</b>

I can't copy the contents in the split editor. For example, after clicking an extension, the introduction in the split editor on the right can be copied, sometimes it can't be copied, and most of the time it can't be copied

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (6.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.23.2
vscode-language-pack-zh-hans|MS-|1.47.3

</details>

**Comment by MyWorldG** [comment]
bug

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/) of the issue?

**Comment by sleien** [comment]
I have the same problem.
Also 1.47.2

![recording](https://user-images.githubusercontent.com/6773732/88396132-68927680-cdc2-11ea-8f9c-4e5305f34664.gif)

It copies the last selected string/line instead of the selected one in the response window. 
The "copy body" button still works.
Right-click is disabled, not sure if this was the case before the update.

**Comment by caizicheng** [comment]
Same issue as well.

**Comment by MyWorldG** [comment]
![vscodebug](https://user-images.githubusercontent.com/53108767/88443891-e602c900-ce4c-11ea-8791-243cc26c9e8f.gif)

**Comment by MyWorldG** [comment]
Drag and drop it into the main editor to copy it normally. However, when it is split to the right, sometimes it can be copied, sometimes it can't be copied. Most of the time, it doesn't work
![vscodebug2](https://user-images.githubusercontent.com/53108767/88444341-44c94200-ce4f-11ea-8408-49fecab8dda4.gif)

**Comment by joaomoreno** [comment]
Can you reproduce with `code --disable-extensions`?

**Comment by alexdima** [comment]
@MyWorldG @sleien You both appear to be using the same extension that creates editors labeled `"Response(xms)"`. As @joaomoreno asked, does this issue reproduce when disabling all extensions?

**Comment by MyWorldG** [comment]
> @MyWorldG @sleien You both appear to be using the same extension that creates editors labeled `"Response(xms)"`. As @joaomoreno asked, does this issue reproduce when disabling all extensions?

No, it only appears when using this extension

**Comment by MyWorldG** [comment]
@joaomoreno 
No, it only appears when using this extension

**Comment by MyWorldG** [comment]
@alexdima 
No, it only appears when using this extension

**Comment by MyWorldG** [comment]
When I disable the extension, I can use copy and paste normally

**Comment by alexdima** [comment]
Thank you for the extra information. Please report this problem directly against the extension.
