### ISSUE TITLE
The Run window's panels on the Side Bar are not horizontal scrollable

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#103215]
- VSCode Version: **1.47.2 zip 64 bit**
- OS Version: **Windows 10 Enterprise 64 bit**

Steps to Reproduce:

1. Start a debugging session.
2. Check the Run windows on the Side bar. Observe that all panels cannot be scrolling. See the below screenshot, when the lines are very long, some info cannot be viewed conveniently. For example, the first variable in the `VARIABLES` panel. Particularly in this case, some calls shown in the `CALL STACK` panel, cannot be fully displayed even I made the width of the `Side Bar` to the max.
![image](https://user-images.githubusercontent.com/19678455/88348714-4426a200-cda2-11ea-98f5-e8bec24b1cff.png)

**Comment by isidorn** [comment]
I acknowledge this limatation. As a workaround I suggest that you move the VARIABLES view to the horizontal bottom panel. You can do this by Drag and Drop.
