### ISSUE TITLE
tabCompletion=onlySnippets says "No suggestions." when there are multiple matches

### ISSUE THREAD

**Issue by JasonWoof** [microsoft/vscode#103267]
- VSCode Version: 1.47.2
- OS Version: debian unstable

Steps to Reproduce:

1. Spend hours trying to disable everything that covers text near the cursor while I'm typing, and make the tab key expand snippets:
```
    "editor.acceptSuggestionOnCommitCharacter": false,
    "editor.quickSuggestions": false,
    "editor.quickSuggestionsDelay": 1000,
    "editor.snippetSuggestions": "none",
    "emmet.showAbbreviationSuggestions": false, // required to kill popup
    "emmet.showExpandedAbbreviation": "never", // required to kill popup
    "editor.tabCompletion": "onlySnippets",
    "editor.hover.enabled": false,
    "editor.suggest.filterGraceful": false
```

2. Define some handy snippets:
```
    "abcde": {
        "prefix": "abcde",
        "body": [
            "(abcde)"
        ]
    },
    "cde": {
        "prefix": "cde",
        "body": [
            "(cde)"
        ]
    },
```
(my actual useful snippets were ``--`` to generate a unicode n-dash and ``---`` to generate a unicode m-dash, but I used letters to demonstrate that this has nothing to do with symbols, and that the bug is caused by the ends (not beginnings) of the prefixes matching.)

3. type ``cde`` and press tab and see that it correctly replaces with ``(cde)``

4. type ``abcde`` and press tab.

Expected: placed with ``(abcde)``. That is, I expect it to choose the snippet with the longest prefix match be expanded. But I'd also be OK with it picking which ever matching snippet was defined first.

Actual results: no change to the text, and get a popup that says "No suggestions." This popup persists and does weird stuff if I press space and start typing another word. 

This error message is the opposite of what's true (there are too many matches, not to few) and it's weird that it says "suggestions" when they are actually snippets, and it shouldn't be generating an error when there's an obvious way to pick one, and the error should go away instead of bothering me as I type the next word.

Does this issue occur when all extensions are disabled?: Yes

**Comment by JasonWoof** [comment]
I just want to add that getting rid of the popup is not just about distraction and obscuring the text I am editing. With the popup I would get different behavior for the same keystrokes (period then tab) depending on how fast I typed them and how fast the popup appeared.

The popup would run a broken emmet tag when I press tab, but if I pressed tab before the popup appeared then I'd get my snippet.

I consider race conditions between my keyboard and the interface to be a bug. My editor should respond to my keystrokes in the same way regardless of how fast I press them and how slow/busy my computer is.

Having to pay attention to my editor to make sure it's keeping up and it's OK for me to keep pressing keys is distracting. It's hard enough to think and type at the same time. I want to keep my focus on what I'm creating/doing/solving not on my editor.

I reported the broken emmet tag separately: https://github.com/microsoft/vscode/issues/103253

**Comment by jrieken** [comment]
`"editor.snippetSuggestions": "none",` is the problem

**Comment by JasonWoof** [comment]
Interesting!

When I comment out that setting, I get a popup when I hit tab. That seems less buggy. For people who like popups, that's cool.

This bug report is requesting that snippet expansion work better with popups disabled.

Specifically, I'd like the snippet that matches the most characters to the left of the cursor to be expanded when I press tab.

I'm fine remapping keys, I just want tab to the the "expand" key in my setup.

I'll make/find another key combo(s) to make popups appear when I want a menu of options/matches/etc.

**Comment by jrieken** [comment]
This got fixed/implemented
