### ISSUE TITLE
Intellisense needs filter configuration

### ISSUE THREAD

**Issue by cjqpker** [Microsoft/vscode#10324]
- VSCode Version:1.4.0
- OS Version:OS X EI

Steps to Reproduce:
1. example in golang, "log.Println" cannot be matched when I input "log.prln"

**Comment by jrieken** [comment]
It uses the `fuzzyContiguousFilter` logic, unsure if that is out of scope for that or how it should work?

**Comment by bpasero** [comment]
I introduced fuzzySeparateFilter to ignore characters between matches for fuzzy matching in quick open but it is not used for intellisense.

**Comment by joaomoreno** [comment]
Intellisense uses _camelCase_ matching. Meaning it would match `PrintLn`, but not `Println`. Substring matching would cause *way* too much noise. @cjqpker Would you like a feature setting, even knowing that it would produce extra noise?

**Comment by cjqpker** [comment]
Fuzzy match did produce noise,  and extra noise may be better than matching failed, I think, and not every programming language uses "camelCase". Maybe a feature setting default closed is a compromise way.

**Comment by joaomoreno** [comment]
@jrieken How are we here?

**Comment by jrieken** [comment]
implemented via #22153
