### ISSUE TITLE
Outline View: Symbols' Visibility

### ISSUE THREAD

**Issue by ailixter** [microsoft/vscode#103305]
It would be very helpful if an outline view could display symbol visibility (private, public, etc.) and do filter by it (just like many IDEs).
Is it possible?

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Afeature-request+label%3Aoutline

**Comment by ailixter** [comment]
really sorry if it's duplicate. unfortunately, however, I have never been able to find the original.
anyway, i'm sure it exists and I looking forward to this useful feature. 
thank you
