### ISSUE TITLE
Focus should be returned to text editor content after git commit

### ISSUE THREAD

**Issue by chrisnorman7** [microsoft/vscode#103320]
Issue Type: <b>Bug</b>

1. Open a project and navigate to a file.
2. Make some edits.
3. Press control shift G to go to the git commit message box.
4. Type a commit message and hit control enter to finalise the commit.
5. The focus used to be returned to the active document, now an initial press of f6 is required.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (1.18GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
vscode-markdownlint|Dav|0.36.1
vscode-eslint|dba|2.1.8
githistory|don|0.6.8
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
vscode-pull-request-github|Git|0.18.0
indentation-level-movement|kai|1.2.1
python|ms-|2020.7.96456
vscode-pylance|ms-|2020.7.3
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
cpptools|ms-|0.29.0
debugger-for-chrome|msj|4.12.9
sqltools|mtx|0.22.11
cargo|pan|0.2.3
vscode-yaml|red|0.9.1
rust|rus|0.7.8
crates|ser|0.5.2
rust-pack|Swe|0.2.29
vscode-counter|uct|2.0.0
vscode-wakatime|Wak|4.0.0
change-case|wma|1.0.0

</details>

**Comment by chrisnorman7** [comment]
Sorry, that should be "Focus should be returned to document content", not "documentation".

**Comment by joaomoreno** [comment]
I'm not really sure this is such a great idea. Focus should stay in SCM.

@JAspeling there is already an issue for that problem.
