### ISSUE TITLE
launching vscode causes extra settings to appear in .vscode/settings.json

### ISSUE THREAD

**Issue by imyjimmy** [microsoft/vscode#103377]
Issue Type: <b>Bug</b>

Everytime I launch from terminal, I get extra settings I didn't ask for in .vscode/settings.json:

```
...
    "activityBar.activeBackground": "#0d8eff",
    "activityBar.activeBorder": "#ffbfe1",
    "activityBar.background": "#0d8eff",
    "activityBar.foreground": "#e7e7e7",
    "activityBar.inactiveForeground": "#e7e7e799",
    "activityBarBadge.background": "#ffbfe1",
    "activityBarBadge.foreground": "#15202b",
    "statusBar.background": "#0074d9",
    "statusBar.border": "#0074d9",
    "statusBar.foreground": "#e7e7e7",
    "statusBarItem.hoverBackground": "#0d8eff",
    "titleBar.activeForeground": "#e7e7e7",
    "titleBar.border": "#0074d9",
    "titleBar.inactiveForeground": "#e7e7e799"
  },
  "peacock.color": "#0074d9"
}
```
My original settings: 

```
{
  "workbench.colorCustomizations": {
    "titleBar.activeBackground": "#0074d9",
    "titleBar.inactiveBackground": "#0074d999"
  }
}
```

Not sure why these extra settings keep getting appended.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (9.08GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
vscode-peacock|joh|3.7.2
chat|kar|0.35.0
vsliveshare|ms-|1.0.2478
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0

</details>

**Comment by gjsjohnmurray** [comment]
I suspect the Peacock extension that you have chosen to use.

/causedByExtension
