### ISSUE TITLE
The below 2 extension(s) in workspace recommendations have issues: robertohuertasm.vscode-icons (not found in marketplace) shinnn.stylelint (not found in marketplace)

### ISSUE THREAD

**Issue by huangup** [microsoft/vscode#103347]
- VSCode Version: 1.47
- OS Version: macOS 10.15.6

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/13741256/88471176-6e11cd00-cf38-11ea-86cd-06c0307c365b.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by huangup** [comment]
what is the problem?

**Comment by huangup** [comment]
What causes this？

**Comment by nrayburn-tech** [comment]
The workspace you are using has two extension recommendations that cannot be found in the vscode marketplace.  Some more information about extension recommendations here, https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions.

**Comment by sandy081** [comment]
VS Code does not have any info about the old names hence cannot be redirected. 

Only way is to update workspace recommendations with new names.
