### ISSUE TITLE
Blurry Terminal

### ISSUE THREAD

**Issue by FloridaStream** [microsoft/vscode#103341]
Issue Type: <b>Performance Issue</b>

the TERMINAL presents the blurry and obfuscated log in the center, after the latests updates.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3220 @ 3.00GHz (2 x 2998)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    99	  9344	code main
    0	   177	   204	   window (C:\Users\Casa\Desktop\Nova pasta (2)\xampp\htdocs\synchttp.py)
    0	    37	  7228	     watcherService
    0	     6	  8280	     console-window-host (Windows internal process)
    0	    68	  9056	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    59	 10632	     extensionHost
    0	    59	  1012	   utility
    2	    78	  1664	   shared-process
    0	    64	  3216	   window (Notificador de Problemas)
    2	   193	  5996	   gpu-process
    0	    14	  7088	   electron-crash-reporter
```

</details>
Extensions: none

**Comment by usernamehw** [comment]
Do you have zoom enabled? `window.zoomLevel`

If so - duplicate of #85154, upstream - https://github.com/xtermjs/xterm.js/issues/2662

**Comment by FloridaStream** [comment]
@usernamehw `window.zoomLevel` is on `-1`.

**Comment by usernamehw** [comment]
Default is `0`. `-1` means it's enabled.
