### ISSUE TITLE
Extension always show building when using typescript

### ISSUE THREAD

**Issue by EricDDK** [microsoft/vscode#103390]
- VSCode Version: 1.47.2
- OS Version: windows 10

Steps to Reproduce:

1.https://code.visualstudio.com/api/get-started/your-first-extension
2.command yo code to create ts extesion.
3.run extension in vscode then always building.
4.js extension is OK.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/33505774/88502240-687fba00-d000-11ea-817b-23937edfb0fb.png)

![image](https://user-images.githubusercontent.com/33505774/88502321-a5e44780-d000-11ea-9c4e-52c6f6b0719c.png)

**Comment by shihaonan369** [comment]
Temporarily, you can replace tasks.json with below code.
```
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": {
				"base": "$tsc-watch",
				"background": {
					"activeOnStart": true,
					"beginsPattern": ".*Starting compilation in watch mode\\.\\.\\.",
					"endsPattern": ".*Watching for file changes\\."
				}
			},
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

**Comment by EricDDK** [comment]
> Temporarily, you can replace tasks.json with below code.
> 
> ```
> // See https://go.microsoft.com/fwlink/?LinkId=733558
> // for the documentation about the tasks.json format
> {
> 	"version": "2.0.0",
> 	"tasks": [
> 		{
> 			"type": "npm",
> 			"script": "watch",
> 			"problemMatcher": {
> 				"base": "$tsc-watch",
> 				"background": {
> 					"activeOnStart": true,
> 					"beginsPattern": ".*Starting compilation in watch mode\\.\\.\\.",
> 					"endsPattern": ".*Watching for file changes\\."
> 				}
> 			},
> 			"isBackground": true,
> 			"presentation": {
> 				"reveal": "never"
> 			},
> 			"group": {
> 				"kind": "build",
> 				"isDefault": true
> 			}
> 		}
> 	]
> }
> ```

I tried it, nothing changed, still showing building

**Comment by WeAthFoLD** [comment]
I meet this problem as well. Solved by changing "npm watch" to "npm compile", at the cost of .ts not being able to hot reload.

**Comment by EricDDK** [comment]
> I meet this problem as well. Solved by changing "npm watch" to "npm compile", at the cost of .ts not being able to hot reload.

Well done. be sloved.

**Comment by alexr00** [comment]
The tsc-watch problem matcher is not locale agnostic: https://github.com/microsoft/vscode/issues/46373
You can modify the problem matcher to your locale.
