### ISSUE TITLE
Bad CPU type in executable when running "code" command in zsh on macOS Catalina

### ISSUE THREAD

**Issue by ToMissTheMarc** [microsoft/vscode#103332]
- VSCode Version: 1.47.2
- OS Version: macOS Catalina 10.15.6

Steps to Reproduce:

1. Install VSCode.
2. Run command in VSCode "Install 'code' command in PATH"
3. Run "code ." in directory with project
4. Receive error "/usr/local/bin/code: line 6: /usr/local/bin/python: Bad CPU type in executable"
5. Receive second line error "/usr/local/bin/code: line 10: ./MacOS/Electron: No such file or directory"

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Interesting, what happens if you run `/usr/local/bin/python` from a  macOS terminal?

**Comment by ToMissTheMarc** [comment]
> /usr/local/bin/python

`zsh: bad CPU type in executable: /usr/local/bin/python`

**Comment by ToMissTheMarc** [comment]
You pointed me in the right direction. I installed python 3.5.8 via homebrew and ran the following commands:
`unlink /usr/local/bin/python`
`ln -s /usr/local/bin/python3.8 /usr/local/bin/python`

I can now successfully open vscode now. Thanks!
