### ISSUE TITLE
Proxy Dialog does not go away

### ISSUE THREAD

**Issue by stonecharioteer** [microsoft/vscode#103392]
- VSCode Version: Insiders 1.48
- OS Version: Macintosh Mojave 10.14.5

Steps to Reproduce:

1. Be on company proxy, without any proxy related configurations.
2. Open VS Code.
3. It will randomly pop up a dialog asking for a proxy
4. Enter username and password, attempt to submit.
5. the dialog does not do anything on clicking either ok or cancel. This happens unpredictably.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@deepak1556 Can you check this one?

**Comment by stonecharioteer** [comment]
It's a bit difficult to add an image to this problem since it happens
randomly. I do not know what triggers it, but it does not let me submit the
proxy information. Neither of the buttons in the popup dialog do anything.
-Vinay Keerthi K.T.

**Comment by Nxt3** [comment]
I'm having the same issue. Seems to be similar to this for me: https://github.com/microsoft/vscode/issues/97199

Only problem is the `auth.html` file I'm supposed to edit doesn't exist in the location specified; so there is no workaround for me.

_Version: 1.48.0-insider
Commit: 15ada625f20086007e2c4aa0d760234360cd648f
Date: 2020-07-30T14:46:01.621Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.3.0_

**Comment by deepak1556** [comment]
Sorry for the delayed response, this will be fixed in today's insider.

/duplicate https://github.com/microsoft/vscode/issues/104603
