### ISSUE TITLE
setting to hide explorer views per workspace

### ISSUE THREAD

**Issue by binyamin** [microsoft/vscode#103383]
_I know that you can do this globally via a context menu, but I'd like to be able to do it differently for different workspaces._

## Suggestion
Expose a setting with which users can disable and enable explorer views. The setting could be a single array or a setting for each built-in view. If it was an array, the setting could control views added by extensions.

## Use-case
When writing documentation in its own workspace, the timeline view may be useless.

## Environment
- **VS Code**: 1.48.0-insider
- **OS**: Xubuntu 20.04
---
Related to #73694

**Comment by sandy081** [comment]
@eamodio Since use case is specific to timeline view assigning to you to see if this can be made visible on demand.

**Comment by b3u** [comment]
@sandy081 That was simply an example. I would also like to be able to hide the outline view, per workspace.

**Comment by eamodio** [comment]
@sandy081 re-assigning back, as it is for more than just the Timeline.

Also sounds similar to this, but user-controlled defaults: https://github.com/microsoft/vscode/issues/101283
