### ISSUE TITLE
Cmd-P doesn't find existing files

### ISSUE THREAD

**Issue by andig** [microsoft/vscode#103302]
Here is the proof:

<img width="1920" alt="Screenshot 2020-07-25 at 11 36 45" src="https://user-images.githubusercontent.com/184815/88453920-aeefe000-ce6b-11ea-9aa3-3d18bb580c17.png">

I've seen this sporadically but cannot identify any pattern. This time its a file that has existed for quite some time.

- VSCode Version: 1.47.2
- OS Version: OSX 10.5.

Steps to Reproduce:

1. no sure, happens rarely

Does this issue occur when all extensions are disabled?: Cannot repro on demain

**Comment by roblourens** [comment]
Thanks for the screenshot, you can see that the file is grayed out in the explorer probably because it is matched by your `.gitignore` file, and these files are excluded from search.

**Comment by andig** [comment]
Thanks @roblourens it's not very obvious that I shouldn't be able to NOT find git-ignored files. For example, I have lots of config files for testing that must not be committed to git but I'd still like to find them.

Could you please reopen this so I can change title accordingly?

**Comment by roblourens** [comment]
You can disable it with `"search.useIgnoreFiles": false`, does that help?
