### ISSUE TITLE
Can't copy text from webview

### ISSUE THREAD

**Issue by Almenon** [microsoft/vscode#103325]
Issue Type: <b>Bug</b>

I can't copy text from my extension's webview. This error was also reported by [one of my users](https://github.com/Almenon/AREPL-vscode/issues/346)

1. install [AREPL](https://github.com/Almenon/AREPL-vscode) & python3
2. open new arepl instance
3. paste in below code
```python
x=1
print('hello world')
raise Exception('foo')
```
4. try to copy the variable / print / exception output on the right
5. paste - nothing is pasted

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|1.0.24
gitlens|eam|10.2.2
vscode-mocha-test-adapter|hbe|2.7.0
vscode-test-explorer|hbe|2.19.1
python|ms-|2020.7.96456
es6-mocha-snippets|spo|0.2.2
wolf|tra|0.3.10
quokka-vscode|Wal|1.0.311
livecode|xir|1.3.10

</details>

I remember being able to copy and paste from the webview before so this is a regression bug.

**Comment by Almenon** [comment]
Perhaps related: https://github.com/microsoft/vscode/issues/102979

**Comment by Almenon** [comment]
Another one that might be related: https://github.com/microsoft/vscode/issues/65452

However, that issue is with Mac and when there is another iframe inside the webview's iframe. The only iframe in my webview is the one inserted by VSCode.

**Comment by gjsjohnmurray** [comment]
Definitely sounds like an issue recently fixed. Can you test with Insiders?

**Comment by Almenon** [comment]
I can't replicate in insiders. Hopefully insiders will fix it then :)
