### ISSUE TITLE
Cann't open more than 50Mb log and txt file

### ISSUE THREAD

**Issue by TBWISK** [Microsoft/vscode#10331]
- VSCode Version:1.3.1 (1.3.1)
- OS Version:OS X EI Capitan  10.11.4 (15E65)

Steps to Reproduce:

1. when i use vscode to open log file,and this log file more than 50Mb ,than it would show 文本无法在编辑器中显示，因为它是二进制文件、非常大或使用不支持的文本编码。sorry beacuse i am a chinese,so my error it would show chinese.

2. this log file create by linux  uwsgi ,and sublime can open it.   

3:how can i use vscode to open it ?

**Comment by alexandrudima** [comment]
There is a file size limit enforced in VSCode to prevent OOM situations.
