### ISSUE TITLE
Auto-hide pop-up notifications

### ISSUE THREAD

**Issue by alexreg** [microsoft/vscode#103376]
It would be nice to have a configuration setting for auto-hiding them after some interval. I think they're called "workbench notifications" — they pop up in the bottom-right of the editor portion of the window.

**Comment by sanket-bhalerao** [comment]
@alexreg , if you press `esc` key these notification goes away. is that what you are looking for?

**Comment by alexreg** [comment]
@sanket-bhalerao That's helpful, thanks, though I'd still like this feature.

**Comment by alexreg** [comment]
Up-votes would be much appreciated, folks! :)
