### ISSUE TITLE
Source maps loading error from bundled node_modules asar archive

### ISSUE THREAD

**Issue by Mon-ius** [microsoft/vscode#103344]
MAC Version `10.15.6 (19G73)`
Code Version
```
1.48.0-insider
8c426f9f3b6b18935cc6c2ec8aa6d45ccd88021e
x64

```
DevTools failed to load SourceMap: Could not load content for file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/node-pty/lib/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/node-pty/lib/unixTerminal.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/node-pty/lib/terminal.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/node-pty/lib/eventEmitter2.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/node-pty/lib/utils.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/semver-umd/lib/semver-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/xterm-addon-unicode11/lib/xterm-addon-unicode11.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/xterm-addon-search/lib/xterm-addon-search.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js.map:

**Comment by nrayburn-tech** [comment]
I believe this is a chromium issue, https://bugs.chromium.org/p/chromium/issues/detail?id=1052872.  According to this comment, there are three actual issues.
https://bugs.chromium.org/p/chromium/issues/detail?id=1052872#c14

**Comment by deepak1556** [comment]
Thanks @nrayburn-tech based on the discussion in that thread it is intended change to show all the sourcemap errors that were previously hidden https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/1872581

@Mon-ius how are you launching insiders ? you should be only seeing the warnings in console when `--verbose` is used.

**Comment by nrayburn-tech** [comment]
@deepak1556 I receive the warnings when opening vscode by just clicking the app in my dock, or using `code-insiders` in terminal.

The error comes from the devtools, not from vscode.  I don't know if `--verbose` is intended to control that or not.  There is a setting inside of devtools to disable source maps.

![SourceMapError](https://user-images.githubusercontent.com/52075362/88569379-f8713400-cfff-11ea-9f90-7f385631cb45.png)

![SourceMapSetting](https://user-images.githubusercontent.com/52075362/88569533-2eaeb380-d000-11ea-8401-c42c839cc2ae.png)

**Comment by Mon-ius** [comment]
Yes, it could help. But I prefer to know what causes these problems? If there is a way to help to load the source map instead of ignore them?

**Comment by deepak1556** [comment]
Thanks for the clarification, seeing the warning in devtools makes sense. I was under the impression the original issue was about warnings in console without `--verbose` flag.

As for why they are not loaded, that is something to be investigated.

**Comment by archfz** [comment]
Note that I am experiencing the same issue, with electron-webpack, the maps of the projects js files cant be loaded `DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_**/resources/app.asar/dist`.

**Comment by deepak1556** [comment]
Closing as issue does not repro in recent versions.
