### ISSUE TITLE
[Feature Request] Add Ability to Star/Favorite Scripts

### ISSUE THREAD

**Issue by williamluke4** [microsoft/vscode#103306]
## Example

![](https://user-images.githubusercontent.com/10773719/88406109-df3a6e80-cdd8-11ea-9f85-093e44a8c967.png)

## Workspace Settings
```json
//  settings.json
{
  "npm.favorites": [
    {
      "path": "path/to/package.json",
      "script": "dev"
    }
  ]
}
```

**Comment by NotWearingPants** [comment]
I think a better solution is to allow specifying a custom order for some of the scripts, because a star is boolean, but what you really want here is to sort the scripts by usefulness.

**Comment by williamluke4** [comment]
@NotWearingPants Could that no be achieved by using the index of the item in the `npm.favorites` array?
