### ISSUE TITLE
Lost all user settings after updating to Version: 1.47.2

### ISSUE THREAD

**Issue by edwardleardi** [microsoft/vscode#103352]
- VSCode Version: 1.47.2
- OS Version: macOS Catalina 10.15.5

Steps to Reproduce:

1. Updated to Version: 1.47.2

Does this issue occur when all extensions are disabled?: Not sure

After a VS Code update user `settings.json` was completely empty. Please let me know what other info you might need to diagnose this issue.

**Comment by sandy081** [comment]
Unfortunate and sorry for that. From which version did you update from?

**Comment by edwardleardi** [comment]
Not 100% sure but I'm guessing from 1.47.1 as VS Code is my primary editor and I've kept it fairly up to date.

**Comment by sandy081** [comment]
Can you please try to install 1.47.1 from [here](https://az764295.vo.msecnd.net/stable/485c41f9460bdb830c4da12c102daff275415b53/VSCode-darwin-stable.zip) and try updating again and let me know if you can repro?

Please backup your settings just to be safe in case you loose them again.
