### ISSUE TITLE
Typescript language server died 5 times in June 2020 version

### ISSUE THREAD

**Issue by thakkery** [microsoft/vscode#103340]
Log of the bug below
Issue Type: <b>Bug</b>
```
[Info  - 01:00:39.510] Starting TS Server 
[Info  - 01:00:39.510] Using tsserver from: /Users/ythakker/Documents/GitHub/philosoraptor/node_modules/typescript/lib
[Info  - 01:00:39.512] <syntax> Forking...
[Info  - 01:00:39.515] <syntax> Starting...
[Info  - 01:00:39.517] <semantic> Forking...
[Info  - 01:00:39.520] <semantic> Starting...
[Error  - 01:00:39.873] TSServer exited with code: 1
[Info  - 01:00:39.874] Starting TS Server 
[Info  - 01:00:39.874] Using tsserver from: /Users/ythakker/Documents/GitHub/philosoraptor/node_modules/typescript/lib
[Info  - 01:00:39.874] <syntax> Forking...
[Info  - 01:00:39.877] <syntax> Starting...
[Info  - 01:00:39.877] <semantic> Forking...
[Info  - 01:00:39.880] <semantic> Starting...
[Error  - 01:00:40.129] TSServer exited with code: 1
[Info  - 01:00:40.129] Starting TS Server 
[Info  - 01:00:40.129] Using tsserver from: /Users/ythakker/Documents/GitHub/philosoraptor/node_modules/typescript/lib
[Info  - 01:00:40.129] <syntax> Forking...
[Info  - 01:00:40.132] <syntax> Starting...
[Info  - 01:00:40.133] <semantic> Forking...
[Info  - 01:00:40.135] <semantic> Starting...
[Error  - 01:00:40.374] TSServer exited with code: 1
[Info  - 01:00:40.374] Starting TS Server 
[Info  - 01:00:40.374] Using tsserver from: /Users/ythakker/Documents/GitHub/philosoraptor/node_modules/typescript/lib
[Info  - 01:00:40.374] <syntax> Forking...
[Info  - 01:00:40.377] <syntax> Starting...
[Info  - 01:00:40.377] <semantic> Forking...
[Info  - 01:00:40.380] <semantic> Starting...
[Error  - 01:00:40.623] TSServer exited with code: 1
[Info  - 01:00:40.623] Starting TS Server 
[Info  - 01:00:40.623] Using tsserver from: /Users/ythakker/Documents/GitHub/philosoraptor/node_modules/typescript/lib
[Info  - 01:00:40.623] <syntax> Forking...
[Info  - 01:00:40.626] <syntax> Starting...
[Info  - 01:00:40.627] <semantic> Forking...
[Info  - 01:00:40.629] <semantic> Starting...
[Error  - 01:00:40.866] TSServer exited with code: 1
[Info  - 01:00:40.866] Starting TS Server 
[Info  - 01:00:40.866] Using tsserver from: /Users/ythakker/Documents/GitHub/philosoraptor/node_modules/typescript/lib
[Info  - 01:00:40.866] <syntax> Forking...
[Info  - 01:00:40.869] <syntax> Starting...
[Info  - 01:00:40.870] <semantic> Forking...
[Info  - 01:00:40.872] <semantic> Starting...
[Error  - 01:00:41.116] TSServer exited with code: 1
```
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.28GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
color-info|bie|0.5.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
Angular2|joh|9.1.2
vscode-styled-components|jpo|0.0.29
vscode-scss|mrm|0.9.0
python|ms-|2020.7.96456
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.2.0
vscode-graphql|Pri|0.2.14
vscode-yaml|red|0.9.1
sass-indented|rob|1.5.1
mdx|sil|0.1.0
autoimport|ste|1.5.3
vscode-mdx-preview|xyc|0.3.0

(14 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Also, it looks like you are using a local TypeScript version. Which TypeScript version do you have locally? Has it been modified in any ways, such as by yarn 2?
