### ISSUE TITLE
Keyboard Input Wrong When Using Combination

### ISSUE THREAD

**Issue by SeanRamey** [microsoft/vscode#103339]
Issue Type: <b>Bug</b>

I use a different keyboard layout, Workman-p. When I am using the editor or the embedded terminal, and I try to copy paste with the shortcuts ctrl-c and ctrl-v it acts as if my keyboard were no longer set to the workman-p layout but qwerty instead. But, when I type a single key and not a ctrl combination, it types the correct character. You can test by going into the keybindings, finding the "copy" shortcut, and try binding it. It will show what is actually being input, and it is wrong. The shortcuts work perfectly fine everywhere else on the system.

So:
* the "C" key on my keyboard should type "M"
* the "V" key on my keyboard should type "C"
* the "B" key on my keyboard should type "V"
* when I type a single key, it works correctly, "V" -> "C", "B" -> "V"
* when I use "Ctrl+V" on my keyboard, the input should be "Ctrl+C", but it is actually "Ctrl+V"
* when I use "Ctrl+B" on my keyboard, the input should be "Ctrl+V", but it is actually "Ctrl+B"

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 5.7.10-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.58GB (9.59GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.2.1
gitlens|eam|10.2.2
todo-tree|Gru|0.0.178
cpptools|ms-|0.29.0
c-cpp-definition-generator|rei|0.0.2
code-settings-sync|Sha|3.4.3
swdc-vscode|sof|2.2.38
vscode-counter|uct|2.0.0

</details>

**Comment by alexdima** [comment]
Have you seen our troubleshooting wiki -- https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

> ![image](https://user-images.githubusercontent.com/5047891/92171928-d60ed980-ee3b-11ea-8c6a-187363180ad9.png)

**Comment by SeanRamey** [comment]
That troubleshooting link looks like it might contain a solution. Since reporting this I've found that a couple of other programs behave in a similar way. I'll try some stuff out and let you know.

**Comment by alexdima** [comment]
:+1: Did you try `"keyboard.dispatch": "keyCode"` ?

**Comment by SeanRamey** [comment]
@alexdima That worked perfectly!
