### ISSUE TITLE
Battery Draining 

### ISSUE THREAD

**Issue by sbassmed** [microsoft/vscode#103348]
Immediately I open VS CODE Version: 1.47.2 the battery of my Macbook Pro 16 " 2019 drains rapidly it's just draining the battery with opening it even without running anything or write code. Also, gets really hot.

PUs | Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 16.00GB (0.61GB free)
Process Argv | -psn_0_479349
Screen Reader | no
VM | 0%

CPU %	Mem MB	   PID	Process
   16	    82	  1083	code main
    0	    33	  1087	   gpu-process
    0	    16	  1089	   utility
    0	   164	  1090	   window (sebas)
    0	    33	  1096	     extensionHost
    0	    16	  1108	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1096
    0	     0	  1248	     /bin/zsh -l
  156	  2343	  1347	     watcherService
    0	    49	  1407	     searchService
    0	    66	  1104	   shared-process
    0	     0	  1413	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    82	  1409	   window (Issue Reporter)

Window (sebas)
|    Folder (sebas): more than 54283 files
|      File types: jpg(1993) icloud(1332) code(1264) svg(1031) keep(788)
|                  rb(719) qml(706) qmlc(706) pdf(548) txt(227)
|      Conf files: package.json(34) settings.json(2)
		

Extension | Author (truncated) | Version
-- | -- | --
bracket-pair-colorizer | Coe | 1.0.61
LiveServer | rit | 5.6.1
vscode-icons | vsc | 10.2.0

**Comment by deepak1556** [comment]
The offending process seems to be the watcher service, is there any minimal repro to verify ? for ex, the issue happens on a particular folder etc..
