### ISSUE TITLE
[json] Colorisation of JSON in VSC breaks part way down the file

### ISSUE THREAD

**Issue by snicholson13** [Microsoft/vscode#10338]
- VSCode Version: 1.4.0

- OS Version: Windows 8.1 enterprise

Issue:

1. There was an update for my VSC on 8th August 2016 - the date in the about information says 2016-08-04, post this update the colorisation stops part way down the file
2. A JSON file of 6076 lines, the colour stops at line 1242
3. A JSON file of 2628 lines, colour stops at line 1777

**Comment by aeschli** [comment]
Can you attach the JSON file?

**Comment by snicholson13** [comment]
Hi Martin

Thank you for coming back to me. Unfortunately I am not allowed to upload the file for confidentiality reasons. I have been working on the same files for the last couple of months and the colourisation has always been fine

Sarah | BA | 02037 579 019
snicholson@neworbit.co.uk<mailto:snicholson@neworbit.co.uk>

**Comment by aeschli** [comment]
I tried to reproduce this with a huge file of JSON, but wasn't able to.
Any chance you can create a sample that does?
Anything special in your file? Comments? Numbers on interesting formats, escapes in strings? Deep object structures?

**Comment by snicholson13** [comment]
Hi

I have very deep object structures and a tiny bit of HTML (only <br/>). I don’t think there is anything else special about it?
I will try to create a sample file for you but it might not be today.

Sarah | BA | 02037 579 019
snicholson@neworbit.co.uk<mailto:snicholson@neworbit.co.uk>

**Comment by snicholson13** [comment]
The colour is going at line 243 in my VSC

Sarah | BA | 02037 579 019
snicholson@neworbit.co.uk<mailto:snicholson@neworbit.co.uk>

From: Sarah Nicholson
Sent: 15 August 2016 14:11
To: Microsoft/vscode <reply@reply.github.com>; Microsoft/vscode <vscode@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Microsoft/vscode] Colorisation of JSON in VSC breaks part way down the file (#10338)

Hi

I have very deep object structures and a tiny bit of HTML (only <br/>). I don’t think there is anything else special about it?
I will try to create a sample file for you but it might not be today.

Sarah | BA | 02037 579 019
snicholson@neworbit.co.uk<mailto:snicholson@neworbit.co.uk>

**Comment by aeschli** [comment]
@snicholson13 I'd still need a reproducible example.
Do you have a 30 objects nested in each other? That would explain it. It would be the same issue as #9937

**Comment by aeschli** [comment]
Closing as dup of #9937

**Comment by snicholson13** [comment]
Hi Martin

I see you closed this. I don’t think my file is 30 deep. I have reinstalled an older version so this bug goes away for now


Sarah | BA | 02037 579 019
snicholson@neworbit.co.uk<mailto:snicholson@neworbit.co.uk>

From: Sarah Nicholson
Sent: 16 August 2016 15:42
To: 'Microsoft/vscode' <reply@reply.github.com>; 'Microsoft/vscode' <vscode@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [Microsoft/vscode] Colorisation of JSON in VSC breaks part way down the file (#10338)

The colour is going at line 243 in my VSC

Sarah | BA | 02037 579 019
snicholson@neworbit.co.uk<mailto:snicholson@neworbit.co.uk>

From: Sarah Nicholson
Sent: 15 August 2016 14:11
To: Microsoft/vscode <reply@reply.github.com>; Microsoft/vscode <vscode@noreply.github.com<mailto:vscode@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [Microsoft/vscode] Colorisation of JSON in VSC breaks part way down the file (#10338)

Hi

I have very deep object structures and a tiny bit of HTML (only <br/>). I don’t think there is anything else special about it?
I will try to create a sample file for you but it might not be today.

Sarah | BA | 02037 579 019
snicholson@neworbit.co.uk<mailto:snicholson@neworbit.co.uk>
