### ISSUE TITLE
Request for building VSCode from source without Visual Studio 2017+

### ISSUE THREAD

**Issue by shrihanDev** [microsoft/vscode#103368]
# Request for building VSCode from source and change some things

Hello! 
I want to build vscode from source and change the code to see what happens _behind the scenes_ and just see what I can do with it.

I just want to tell that, Can I do the above **without Visual Studio 2017+**, as I don't have enough requirements for that.

Please!

**Comment by alexr00** [comment]
All the details for how to build VS Code are in the wiki: https://github.com/microsoft/vscode/wiki/How-to-Contribute
