### ISSUE TITLE
Pressing tab once moves cursor 3 tabs instead of 1.

### ISSUE THREAD

**Issue by vaibhavrajsingh2001** [microsoft/vscode#103371]
Issue Type: <b>Bug</b>

Where: While working in HTML and JSX.
What: Pressed tab once and the cursor moved 3 tabs instead of moving to the correct scope.

![ezgif com-crop](https://user-images.githubusercontent.com/47082523/88485397-09d02700-cf93-11ea-86e7-545559557728.gif)

VS Code version: Code - Insiders 1.48.0-insider (731f9c25632dbbf01ee3a7892ad9d2791fe0260c, 2020-07-24T05:57:10.466Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.48GB free)|
|Process Argv|D:\Asynamite --crash-reporter-id 19ffe319-9a80-46ac-a1a3-3e236a7b4f12|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-node-readme|ben|3.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
es7-react-js-snippets|dsz|2.8.2
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.1.3
auto-rename-tag|for|0.1.4
code-runner|for|0.11.0
vscode-pull-request-github|Git|0.18.1
remote-wsl|ms-|0.44.4
typescript-javascript-grammar|ms-|0.0.53
reload|nat|0.0.6
java|red|0.65.0
LiveServer|rit|5.6.1
trailing-spaces|sha|0.3.1
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.23.0
vscode-icons|vsc|10.2.0
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@vaibhavrajsingh2001 sorry for reaching out late. Could you please share more info about how to reproduce? For example, a minimal HTML file which you can reproduce the issue, your settings, etc.

**Comment by vaibhavrajsingh2001** [comment]
@rebornix It seems fixed it that month itself. Might be related to some other issue I guess. Hence closing this. (Thanks for reaching out :raised_hands:)
