### ISSUE TITLE
Matches multiple schemas when only one must validate in launch.json

### ISSUE THREAD

**Issue by sbr2567** [microsoft/vscode#103350]
I am receiving this problem message in my launch.json file, and I am completely unable to use the debugger in vscode. It simply doesn't work. To just run one line of code takes 5 minutes. And functions won't run at all. I don't know if this problem message has any relevancy to the debugger not working, but both issues have occurred at the same time so I'm assuming that this is the case.

I've also tried to uninstall the javascript debugger, and instead installed the overnight addition of the debugger in case their was bug fixes I missed, but the problem still persists.

If anyone can help me with this issue i'd greatly appreciate it, as I can't really code at all until this is resolved.
Thanks.

**Comment by weinand** [comment]
Could you please shared the affected launch config?
And a screenshot showing the message in context would help too.
