### ISSUE TITLE
It's easy to mis-click inline replace button in the search sidebar

### ISSUE THREAD

**Issue by OneMoreSecond** [microsoft/vscode#103398]
Issue Type: <b>Bug</b>

Reproduction steps:
1. Open a project
2. Search something in the search sidebar
3. I want to click a candidate line but mis-click a hidden replace button
4. Project files are edited unexpectedly.

#### The design issue
There are two buttons at the end of each candidate line: replace and dismiss.
They are **hidden** if the mouse is not focusing on the line.
Then it's easy for users to click them by mistake and make unexpected changes, especially for users unaware of this feature.

![image](https://user-images.githubusercontent.com/16792948/88516798-6d546600-d020-11ea-8809-21053b847313.png)

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 5.3.0-1020-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: GCRAZGDL694.redmond.corp.microsoft.com|
|OS|Linux x64 5.3.0-1020-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (6 x 2593)|
|Memory (System)|110.04GB (13.42GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
vscode-terminals|fab|1.12.9
kite|kit|0.121.0
python|ms-|2020.7.96456
vscode-pylance|ms-|2020.7.3

</details>

**Comment by IllusionMH** [comment]
Doesn't looks like a bug per se (it's implemented in this way), so not clear what action items here are expected. Could you please clarify what fix expected?

`"search.actionsPosition": "right"` can be used to move action to right instead so they will have "fixed" position.

**Comment by roblourens** [comment]
That setting is probably what you want. The request to make that the default has come up multiple times and I might do that...

**Comment by OneMoreSecond** [comment]
It's better if they are not hidden
