### ISSUE TITLE
VS code is crashing in every 4-5 minutes

### ISSUE THREAD

**Issue by Ganesh8999** [microsoft/vscode#103304]
Issue Type: <b>Bug</b>

VScode is crashing in every 4-5 minutes. I don't know why , it suddenly became slow and then  simply closing without throwing any error. It's really irritating I have to open again and again. Resolve this issue and give new update as soon as possible.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
(1 theme extensions excluded)

**Comment by deepak1556** [comment]
Can you launch with `--crash-reporter-directory <path>` and provide the generated crash dump.
