### ISSUE TITLE
Toggle Gutter Keybind

### ISSUE THREAD

**Issue by soulshined** [microsoft/vscode#103389]
As someone who doesn't show line numbers and is a heavy keybind user (think collapsing and expanding), the padding around a given editor takes up a lot of valuable space, outside of using it for breakpoints, when you don't use it or hover it. It also visually doesn't fit it's counterpart (the scroll bar width on the right side). Would be nice to consider implementing a toggle shortcut for this, since it's pretty much a standard setting for all other UI elements/panels.

Edit: Add a picture for visual reference, if needed:

![Annotation 2020-07-27 094730](https://user-images.githubusercontent.com/11242654/88556209-5dbc2980-cfee-11ea-9ca9-b9e2d33e2dd0.png)

The circle on the left is what it looks like when you don't have line numbers enabled or use it for hovering to collapse or breakpoints, and the circle on the right is my scroll bar width

**Comment by soulshined** [comment]
I was thinking, should this be disabled by default in zen mode you think? Or this too extreme?

**Comment by alexdima** [comment]
Have you seen https://github.com/microsoft/vscode/issues/30795#issuecomment-410998882

I suggest we track in #30795

**Comment by soulshined** [comment]
I have not seen that, didn't google how to make it smaller because I just wanted to disable it altogether. Thanks for the share. Not a fan of disabling folding for a work around, but I see it's in the discussion.
