### ISSUE TITLE
VS Code Auto Restarts My PC

### ISSUE THREAD

**Issue by Terminator-24** [microsoft/vscode#103329]
It causes a blue screen and then auto restarts my pc every time I launch this software. This happened after I tried to install an extension inside the VS code, but I checked and I know the extension installation was not successful.  I have tried reinstall the vs code and reinstall all of the extensions. But that does not help.

**Comment by joaomoreno** [comment]
> It causes a blue screen and then auto restarts my pc every time I launch this software.

How do you know its VS Code that causes the blue screen? Do you have a log?
