### ISSUE TITLE
Ignore directories for loading

### ISSUE THREAD

**Issue by Milo123459** [microsoft/vscode#103313]
Hey! I have a quick little suggestion for a config per directory, say for instance I want to load all directories except for node_modules, in the .vscode/config.json I could have a property like: exemptPaths: ["node_modules/**/*"]
Basically, rather then loading all directories, you can ignore some which won't load to make the loading process / experience of coding nicer, and you can change the config at any time.

**Comment by joaomoreno** [comment]
The setting is `files.exclude`.
