### ISSUE TITLE
The application hangs when moving a file to the trash (Ubuntu/KUbuntu/KDE)

### ISSUE THREAD

**Issue by Vitaly-Rudenko** [microsoft/vscode#103311]
- VSCode Version: **1.47.2**
- OS Version: **KUbuntu 20.04**
![Screenshot_20200725_171633](https://user-images.githubusercontent.com/1491646/88459029-b7abda80-ce9a-11ea-8a88-f9f88e68aa3d.png)

Steps to Reproduce:

1. Delete a file in file explorer (move to the trash)

Sometimes it doesn't hang, so maybe I could provide some logs or something.
I just don't know what would help to localize the problem.

Does this issue occur when all extensions are disabled?: **Yes**

It looks like it's the same issue as here: https://github.com/microsoft/vscode/issues/54493

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/101920
