### ISSUE TITLE
Wrong syntax highlight

### ISSUE THREAD

**Issue by peach-lasagna** [microsoft/vscode#103362]
Issue Type: <b>Bug</b>

I write "var = " in .py file, save him, then delete ALL letters(символы) from file and write "var = 5" if i will not save file i catch wrong highlight and "Invalid syntax" from linters, but if I will save file Everything will be good.
I tried disable extentions and reboot vscode, but nothing changed.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.82GB (0.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.1.0
toml|be5|0.5.1
path-intellisense|chr|2.2.1
githistory|don|0.6.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
todo-tree|Gru|0.0.178
vscode-test-explorer|hbe|2.19.1
rest-client|hum|0.24.1
path-autocomplete|ion|1.15.0
vsc-python-indent|Kev|1.10.1
kite|kit|0.121.0
MagicPython|mag|1.1.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.4.1
python|ms-|2020.7.96456
vscode-pylance|ms-|2020.7.3
remote-wsl|ms-|0.44.4
sqltools|mtx|0.22.11
autodocstring|njp|0.5.3
vscode-python-typehint|njq|1.2.0
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.9.1
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.12
vscodeintellicode|Vis|1.2.9

(1 theme extensions excluded)

</details>

**Comment by peach-lasagna** [comment]
![image](https://user-images.githubusercontent.com/59787538/88479650-eef1b880-cf7a-11ea-8abf-2b56c59166c8.png)
SAVE FILE
![image](https://user-images.githubusercontent.com/59787538/88479682-1e082a00-cf7b-11ea-8335-7d940f6c780e.png)

**Comment by alexr00** [comment]
I am not able to reproduce the issue. This sounds like a problem with your linting or extensions.
![recording (13)](https://user-images.githubusercontent.com/38270282/89993381-ebeb0d80-dc86-11ea-8442-230cb122de0f.gif)
