### ISSUE TITLE
Monaco uses outline-offset css which is not supported in IE/Edge

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#10330]
Basically, the bug is that Monaco uses the CSS “outline-offset” with high contrast styling, but this is not supported in IE (or Edge).  See https://developer.mozilla.org/en-US/docs/Web/CSS/outline-offset.  This results in some wacky looking scrollbar outlines, as shown below from Edge.

![image](https://cloud.githubusercontent.com/assets/5047891/17507624/ef4b5cb2-5e10-11e6-97fb-37bf4c1c01b5.png)

**Comment by Tyriar** [comment]
`src/vs/base/browser/ui/messageList` uses `outline-offset`, is anything in `src/vs/base/` part of Monaco?

**Comment by bpasero** [comment]
Verified that we do not have outline-offset in base, platform and editor. The one in message list is not being used within the editor.
