### ISSUE TITLE
Python debugger - if exception detected in collapsed code in a *.py does not expand

### ISSUE THREAD

**Issue by ianfinlay-csiro-au** [microsoft/vscode#103355]
Issue Type: <b>Bug</b>

1. create py file 
2. create divide by zero function in py file
3. collaps above function 
4. menu Run (F5) 
5. none the wiser about whats going on until expand the function to discover an exception

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.7.96456
remote-wsl|ms-|0.44.4

</details>

**Comment by weinand** [comment]
@isidorn when debugging breaks on a line (for whatever reason), are we automatically expanding collapsed code?

**Comment by isidorn** [comment]
@weinand no we are not doing this explicitly.

@aeschli @bpasero currently we are simply using the `editorService.openEditor`. I would expect that the `editorService` automatically unfolds a position if I pass a folded location.
Let me know what you think.

**Comment by weinand** [comment]
If the editorService doesn't do it, then we should do it.
But I think they should do it (or have an option on the method to do it).

**Comment by isidorn** [comment]
@weinand it should be handled globably in the editor service since this can happen whenever a user click on any link to a file for example in the terminal, output, problems panel...

**Comment by bpasero** [comment]
@isidorn I simply pass the view state to the editor, you should ask Alex or Martin why that would not unfold. I agree that passing a line number and/or position should unfold.

**Comment by isidorn** [comment]
@aeschli @alexdima regarding unfodling a line number when it is passed to the editor to be revealed.

**Comment by alexdima** [comment]
I'm afraid at this time folding only unfolds when the cursor moves to a folded location, not when someone calls editor reveal API on a folded location.
