### ISSUE TITLE
HTML intellisense not working

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#103370]
Issue Type: <b>Bug</b>

In the past week, I noticed I no longer get intellisense hints on my HTML files.  This is an Angular 10 project.  I used to be able to type as attribute as "(c" and get "(click)" suggested. It also used to complete the names of functions and variables in the corresponding TS file.  Now it does nothing at all.

I no longer get any hints for anything Angular or Javascript-related in the HTML.

Not sure if it is related, but when I open any project in the last week that I haven't opened for a while,  I get this cryptic dialog about ESLINT: 

![CleanShot 2020-07-26 at 13 08 17](https://user-images.githubusercontent.com/835148/88485057-30fe0880-cf41-11ea-9521-05ac0b10ebc6.jpg)

 I confess I have no idea why, or what this means, so I took the default button.

I assume some setting got changed somehow but have no idea which, but not having hints in HTML is annoying.

VS Code version: Code - Insiders 1.48.0-insider (731f9c25632dbbf01ee3a7892ad9d2791fe0260c, 2020-07-24T05:51:27.957Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (2.22GB free)|
|Process Argv|-psn_0_6186470 --crash-reporter-id 2989f78b-23b4-466d-ae73-bbe6c5fe1c40|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|1.6.2
Bookmarks|ale|11.3.1
project-manager|ale|11.1.0
ng-template|Ang|0.1000.4
change-color-format|bbu|1.0.0
vscode-multi-line-tricks|big|0.0.3
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
vscode-npm-script|eg2|0.3.12
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.1.3
todo-tree|Gru|0.0.178
rainbow-csv|mec|1.7.0
ecdc|mit|1.3.0
HTMLHint|mka|0.8.0
theme-monokai-pro-vscode|mon|1.1.17
js-debug-companion|ms-|1.0.2
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
angular-console|nrw|13.0.0
angular-component-extension|oni|0.0.14
vscode-versionlens|pfl|1.0.8
quicktype|qui|12.0.46
format-html-in-php|rif|1.6.2
code-settings-sync|Sha|3.4.3
rewrap|stk|1.13.0
sort-lines|Tyr|1.9.0
vscode-icons|vsc|10.2.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.2.0

(4 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
The eslint dialog is not related to html code completions.

Can you try with all extensions disabled? You should get code completions here:

![image](https://user-images.githubusercontent.com/6461412/89919230-4a6aaa00-dbfb-11ea-969a-8f13666ef97d.png)
```
<html>
<script>
	
</script>
</html>
```

Make sure the editor is in `html` mode.

The `(click)` suggestions likely come from an angular extension.

**Comment by smlombardi** [comment]
I had to do this to get it working: https://github.com/angular/vscode-ng-language-service/issues/876#issuecomment-667900859

Seems like an issue with Angular 10.
