### ISSUE TITLE
Open file diff in "preview mode" when pressing "space" in the list of changed files

### ISSUE THREAD

**Issue by CombeeMike** [microsoft/vscode#103366]
- VSCode Version: `1.47.2`
- OS Version: `Win 10, Version 2004`

Steps to Reproduce:

1. Navigate through list of changed files in "Source Control" panel using the keyboard
2. Press `space` on any file
--> ❌ The diff view does not open in "preview mode" like when doing the same in the "files explorer"

Does this issue occur when all extensions are disabled?: Yes

# Details about my use case

I'd like to establish a workflow where I can navigate through the diffs of all changed files using only the keyboard as explained in #50434. Since this doesn't seem to be possible with VSCode built in features, I implemented a workaround using AHK (see [this comment](https://github.com/microsoft/vscode/issues/24916#issuecomment-662884119) for details).

Whilst this is working pretty good thus far, I'm getting a new tab with a diff view every time I'm navigating using my script which is a little cumbersome. That would be solved, if I could open the diff view in "preview mode" using the `space` bar of my keyboard instead of opening it in "pinned mode" using `enter`.

**Comment by isidorn** [comment]
Does not work for me, reopening.
I see it for a moment in preview mode and then it gets pinned.

My steps:
1. Make changes to debug.ts
2. Close all editors, make sure you have workbench preview enabled
3. Open git view, press space when focus on debug.ts -> the diff view is not in preview

**Comment by isidorn** [comment]
Verified out of source
