### ISSUE TITLE
提示功能只显示"正在加载..."

### ISSUE THREAD

**Issue by tongle3000** [microsoft/vscode#103363]
VS code 打开项目,前面几分钟,鼠标悬浮在 代码(方法,变量)上面,有正常提示功能,  但是过几分钟后, 所有的就只显示"正在加载...". 而且输入代码的时候,没有IntelliSense提示功能.

**Comment by Joker0824** [comment]
不知道这个问题为什么关闭，都好久了，还没解决正在加载的问题

**Comment by Joker0824** [comment]
![image](https://user-images.githubusercontent.com/26892349/90603142-67bbfb80-e22d-11ea-8ad9-4a5ae5461883.png)

**Comment by Joker0824** [comment]
![image](https://user-images.githubusercontent.com/26892349/90608000-97223680-e234-11ea-9ae5-c6b7b78795f9.png)
when i press alt+/ to trigger suggest,it always show loading(正在加载)

**Comment by Joker0824** [comment]
![Kapture 2020-08-19 at 15 55 12](https://user-images.githubusercontent.com/26892349/90608206-df415900-e234-11ea-8208-a74882de941e.gif)
When i press alt+/ to trigger suggest,it always show loading(正在加载)
