### ISSUE TITLE
Non-ASCII characters get automatically replaced with other ones

### ISSUE THREAD

**Issue by adrians** [Microsoft/vscode#10336]
Sometimes, when I open a file, then save that file and close it, certain (non-ASCII) characters get replaced with other ones, and this causes problems. It's not a serious issue, but it's annoying.

To reproduce, create a file which contains only the "0x93" byte. Open it with VS Code, don't do any change to it, save it, close the editor and hexdump it. After saving it the file contains "0xEF 0xBF 0xBD".

Details:
- VSCode Version: 1.4.0
- OS Version: Windows 7

**Comment by bpasero** [comment]
@adrians Looks like an issue with the encoding. If you do not configure your encoding we save as UTF-8 which ends up using 3 bytes. 

This should be OK once you change the encoding to the right one for your characters.

**Comment by adrians** [comment]
You are right, the encoding was causing the issue.

To work on the project I've added `"files.encoding": "windows-1252"` to my settings and now it's running fine. The fact that it doesn't auto-detect the encoding or at least warn me that it's about to change the file's encoding is still strange, but shouldn't impact me now.

Thanks for the help.

**Comment by adrians** [comment]
It looks like a duplicate of #7048 so we can close it.
