### ISSUE TITLE
Filter TypeScript errors for selected files

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#10337]
Hi, first of all, thanks for the awesome project. You're doing fantastic work.

I am in the process of gradually moving a codebase to using TypeScript. There are certain compiler options which I want to enable, namely no implicit any and strict null checking, however because I am moving things gradually, I only want to enforce these stricter rules on a subset of TypeScript files.

My solution to this is to wrap the TypeScript compiler, filtering out error messages from no implicit any and strict null checking where the file is not whitelisted as “strict”. For example: https://github.com/Microsoft/TypeScript/issues/8855#issuecomment-237915223

However, I do not want to use such a solution in my project without corresponding feedback in my IDEs.

Is there any way I can wrap the TypeScript compiler used in vscode similarly to how I wrapped the TypeScript compiler in https://github.com/Microsoft/TypeScript/issues/8855#issuecomment-237915223?

Or, perhaps I could use my wrapped compiler and send those errors to vscode instead of using the built in TypeScript errors?

Is there somewhere I can find the code that sends the TypeScript errors to vscode?

I want to achieve this for other plugins in other IDEs too, to suit all the developers in my team, but also because I think this will be useful to other people who are gradually moving their codebase to TypeScript and want to start using some of the stricter compiler options.

Thanks,
Olly

**Comment by jrieken** [comment]
You should be able to use the task framework for that

**Comment by OliverJAsh** [comment]
Do you have any more details? I'm not sure what you are referring to :-)

**Comment by jrieken** [comment]
this one: https://code.visualstudio.com/docs/editor/tasks but dirk knows best

**Comment by dbaeumer** [comment]
Closing issue assuming that the task documentation help addressing this.
