### ISSUE TITLE
Odd white bars in the terminal.integrated.commandsToSkipShell setting

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#103301]
Issue Type: <b>Bug</b>

**Repro**
1. Open settings
1. View `terminal.integrated.commandsToSkipShell`

**Bug**
The setting description has a pair of white bars:

<img width="1390" alt="Screen Shot 2020-07-25 at 12 57 39 AM" src="https://user-images.githubusercontent.com/12821956/88452261-1416e780-ce12-11ea-8706-8af7f196b563.png">

These are markdown horizontal rules but look out of place. I think they are the only place I've seen them used in the settings UI

VS Code version: Code - Insiders 1.48.0-insider (731f9c25632dbbf01ee3a7892ad9d2791fe0260c, 2020-07-24T05:51:27.957Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|17%|
</details>

**Comment by gjsjohnmurray** [comment]
I added these as part of my PR #100445. IMO this setting is unusual in its complexity, and the lines are intended to help the user parse the large quantity of information being presented.

**Comment by Tyriar** [comment]
I think they look alright personally, maybe a little heavy if anything?

**Comment by mjbvz** [comment]
This is the only setting I see that uses them so I feel they look out of place. A normal paragraph break the sections would probably work

If we keep the horizontal rules, my recommendations would be:

- Add top and bottom padding to them
- Adjust the color to be less bright 
- Potentially adjust the width to only span part of the text width

@misolori may be able to provide better suggestions

**Comment by roblourens** [comment]
I agree with @mjbvz's suggestions

**Comment by gjsjohnmurray** [comment]
Using Developer Tools I added the following to the first <hr> element created by the markdown:
```
 */
    margin-top: 10px;
    margin-bottom: 10px;
    margin-left: 20px;
    margin-right: 20px;
    opacity: 0.4;
```
Result is:
![image](https://user-images.githubusercontent.com/6726799/88646716-413af280-d0bd-11ea-8787-80d2e04f7620.png)

Then I added `border-bottom-width: 0px;` and applied the styling to both lines to get this:

![image](https://user-images.githubusercontent.com/6726799/88647374-ddfd9000-d0bd-11ea-8dbd-cb690e98c849.png)

And with the default light theme:

![image](https://user-images.githubusercontent.com/6726799/88647658-21f09500-d0be-11ea-81b3-b52807b0181a.png)

Is that more acceptable?

**Comment by mjbvz** [comment]
What does it look like with a normal paragraph break?

**Comment by gjsjohnmurray** [comment]
![image](https://user-images.githubusercontent.com/6726799/88685021-69424a00-d0ed-11ea-8104-43556d87690f.png)

Or removing the italics and splitting that into its own para:

![image](https://user-images.githubusercontent.com/6726799/88685425-d655df80-d0ed-11ea-8887-c7cedd86bd20.png)

**Comment by Tyriar** [comment]
The paragraphs are just as impactful as the rules imo.

**Comment by mjbvz** [comment]
@gjsjohnmurray The second example with the newlines look good to me. Thanks for taking a look!

We may also want to check in the css to make the horizontal rules look better since settings from extension could use them
