### ISSUE TITLE
Add ability to bookmark an extension and sync the bookmarks

### ISSUE THREAD

**Issue by x-strong** [microsoft/vscode#103391]
Add the ability to star / favorite extension and sync to vscode account.

**Comment by gjsjohnmurray** [comment]
Sync is already previewing in the Insiders build.

**Comment by heartacker** [comment]
> Sync is already previewing in the Insiders build.

 `star` / `favorite` supportting, thanks

**Comment by sandy081** [comment]
Can you please elaborate what do you mean by star / favourite?

As said we already support Sync in our insiders and can you please try that and let us know if that suffice your requirement?

**Comment by x-strong** [comment]
> Can you please elaborate what do you mean by star / favourite?
> 
> As said we already support Sync in our insiders and can you please try that and let us know if that suffice your requirement?

"star / favourite" is somewhat like that in web brower, which allow we mark and remember those extensions that we consider is useful and easily to install them in a new VS Code on new PC. We can find back and install them as long as we login our VS Code account.

Did I make it clear?

I don't think that the Sync in insiders VS Code meet this requirement, does it?

**Comment by sandy081** [comment]
I see. you want to bookmark an extension.

**Comment by x-strong** [comment]
![VS Code Extension Favorites](https://user-images.githubusercontent.com/3232261/88825493-3b96f700-d1fa-11ea-8617-77fa149d0dd2.png)
