### ISSUE TITLE
Error within commit textbox

### ISSUE THREAD

**Issue by Cristian-A** [microsoft/vscode#103324]
Sometimes this happens, I don't really know why, but it happens when I use json files (which by the way are presenting very weird errors even if the file is perfectly fine and the syntax is also correct).

<img width="493" alt="Screenshot 2020-07-25 at 20 13 15" src="https://user-images.githubusercontent.com/30161685/88463533-b2a75500-ceb3-11ea-89ea-27dcb6db0eb7.png">

**Comment by usernamehw** [comment]
Generated by some outdated extension.

https://github.com/Togusa09/vscode-tmlanguage/issues/14

**Comment by Cristian-A** [comment]
Confirmed. Removing the Textmate Language extension solves the problems.
