### ISSUE TITLE
create new file should ask where in the workspace directory the file should be created.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#103319]
Issue Type: <b>Feature Request</b>

current behavior:
1. press ctrl + n, an untitled file is opened in the editor
2. press ctrl + s, a system popup is opened, to save the file
3. to change directory mouse interaction is required

expected behavior:
1. press ctrl + n (to create a new file)
2. this should open a breadcrumbs style menu to confirm/change the directory the file should be created in
![image](https://user-images.githubusercontent.com/9264813/88462164-e9d33180-cec6-11ea-8917-4c058231ff31.png)
3. it asks the file name with extension.
4. once created the file is opened as editor tab.

VS Code version: Code - Insiders 1.48.0-insider (731f9c25632dbbf01ee3a7892ad9d2791fe0260c, 2020-07-24T05:57:10.466Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
You can already do this by right clicking on the target folder in the Explorer tree.

**Comment by sanket-bhalerao** [comment]
@gjsjohnmurray it can be done that way but for that one needs to 
1. open the explorer (ctrl +b)
2. click on the folder with the mouse 
3. click to create a new file.

or if you want to use the keyboard
1. open explorer (ctrl + b), focus on the file view by pressing tab at least a few times
2. or focus on files view ( alt + f)
3. if you have an open file the context menu you get is of the open file not to create a new file.
4. travel to the folder where you want  to create a file
5. pull up the context menu and select a new file

don't get me wrong, what VSCode has now is awesome. I am just trying to see if the click/selection interactions can be minimized.

**Comment by NotWearingPants** [comment]
I agree with OP, I think that the folder selector that appears when you want to open a folder in a remote VSCode window fits perfectly here.

This can be a separate command - "Save File in Workspace", and also "New File in Workspace".

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on the immediate plan, thus assigning to backlog.
In the meantime maybe an extension can contribute a command to introduce something similar. Extensions can not control the breadcrumbs, but it could use the quick pick for the folder choice for example.
