### ISSUE TITLE
Import Directory Problem

### ISSUE THREAD

**Issue by Shubham-Agrawal1206** [microsoft/vscode#103309]
Issue Type: <b>Bug</b>

When doing import files in react projects from local project directory, the auto suggestion for path shows every files/folders 2 times

VS Code version: Code - Insiders 1.48.0-insider (731f9c25632dbbf01ee3a7892ad9d2791fe0260c, 2020-07-24T05:57:10.466Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.75GB free)|
|Process Argv|--crash-reporter-id 93197b37-39d9-43b7-89b6-36fcb9277067|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
vscode-eslint|dba|2.1.8
es7-react-js-snippets|dsz|2.8.2
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.12
prettier-vscode|esb|5.1.3
vscode-firefox-debug|fir|2.9.0
webpack-snippets|gog|0.0.4
search-node-modules|jas|1.3.0
webpack|jer|2.2.0
vscode-peacock|joh|3.7.2
chat|kar|0.35.0
rainbow-csv|mec|1.7.0
vscode-language-babel|mgm|0.0.29
git-graph|mhu|1.24.0
dotenv|mik|1.0.1
mongodb-vscode|mon|0.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.7.96456
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2478
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.9
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.9.1
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.12
python|tht|0.2.3
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0
nodejs-extension-pack|wad|0.1.9
webpack-progress|wk-|0.0.8
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
material-theme|zhu|3.8.5
html-css-class-completion|Zig|1.19.0

</details>

![image](https://user-images.githubusercontent.com/57083796/88457435-f2664080-cea3-11ea-9141-159902219fbd.png)

**Comment by mjbvz** [comment]
VS Code's built-in JS/TS support provides path completions and you also have path intellisense plugins installed. Do you see this after disabling all your path IntelliSense plugins?

**Comment by Shubham-Agrawal1206** [comment]
Which plugins to remove?
Please tellme more about it

**Comment by mjbvz** [comment]
Try disabling the  path IntelliSense ones you installed
