### ISSUE TITLE
VSCODE KEEPS DISABLING MY EXTENSIONS,  AND SOMETIMES CRASHES

### ISSUE THREAD

**Issue by danielmedvec** [microsoft/vscode#103322]
Issue Type: <b>Bug</b>

Im just editing code, and it keeps disabling my extensions. 

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3516)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|16.00GB (5.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-color|ans|0.4.5
simple-react-snippets|bur|1.2.3
jquerysnippets|don|0.0.1
jquery-snippets|Hri|1.0.0
vscode-peacock|joh|3.7.2
chat|kar|0.35.0
vsliveshare|ms-|1.0.2478
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
swdc-vscode|sof|2.2.38

</details>

**Comment by gjsjohnmurray** [comment]
I recommend that you disable your extensions one at a time until you find which one is causing the problem. I guess one of them is crashing the Extension Host process which they all share.

**Comment by alexdima** [comment]
@danielmedvec The `chat` extension is known to cause crashes.
