### ISSUE TITLE
Better renaming support for files with multiple filename extensions

### ISSUE THREAD

**Issue by philo23** [microsoft/vscode#103335]
Currently when you rename a file with multiple file extensions, for example `example.blade.php`, currently `example.blade` gets selected by default when really it'd make more sense to just select `example` in this context.

I've not looked very far, but I guessing that file renaming just needs to become aware of file extension defined for that files language [like this extension for example](https://github.com/onecentlin/laravel-blade-snippets-vscode/blob/902ac67c68daed56b8dfdd21e20b66f984793f45/package.json#L56) or [the built-in XML support](https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/extensions/xml/package.json#L22)

I'm not sure if it's possible to define a language without a file extension against it, but in those cases I'd assume it's safe to fallback to the current behavior of selecting everything before the last `.` in the file name, and in most cases existing behavior isn't going to change as most files are going to have just one file extension anyway.

There's probably a few additional cases to think about like for files without a known language or when multiple extensions match (pick the longest one?)

![image](https://user-images.githubusercontent.com/171550/88467695-869acc80-ced1-11ea-99f1-e95a994f6b50.png)
![image](https://user-images.githubusercontent.com/171550/88467698-987c6f80-ced1-11ea-8053-784e4d8f2bc6.png)

**Comment by isidorn** [comment]
Currently we select all the way to the last `.`, and what you want is to select up to the first `.`.
I can leave this open as a feature request, however I would not change this for now since it might break some users muscle memory

**Comment by philo23** [comment]
No problem, but just to clear up one thing. It wouldn't necessarily select up to the first `.`, but up to the first matched file extension for the relevant document type.

Eg: for a file named `a.longer.example.blade.php` it would detect that the file to be renamed is a Blade template document, lookup the related file extension for that document (`.blade.php`) and then default the selection to `a.longer.example` instead of `a.longer.example.blade` as it does currently.
