### ISSUE TITLE
git push triggers the UI

### ISSUE THREAD

**Issue by sezanzeb** [microsoft/vscode#103334]
I'm sorry, but triggering some sort of UI promt to configure github in vscode when using the git cli (`git push` in this case) is, at least for me, absolutely out of the question. I'm using the cli because I'm already used to it, and so it feels comfortable. If I want to have something user friendly I would use some sort of buttons on the UI, not the console.

I don't think that blurring the boundary between console and UI, watching for specific git commands, is a good idea. I type a cli command into the console, I hit enter in the console, I expect the next step to be part of the cli in the console as well. Also, vscode is the only place in the universe where `git push` does that.

Unfortunately, disabling git also means disabling the diff button. In my eyes, this is just ridiculous.

![image](https://user-images.githubusercontent.com/28510156/88467263-87cdf880-ced5-11ea-867f-339080445f06.png)
please just let me use the username and password prompt in the console instead. Don't force this feature

manjaro, 1.47.1-1

**Comment by sezanzeb** [comment]
I just downgraded to 1.43.1 (https://archive.archlinux.org/packages/c/code/)

There, the console is actually a console

**Comment by sezanzeb** [comment]
and if this is some sort of feature that makes authorizing easier, because I don't have to type in the password, I could just use ssh instead anyways and get the same effect.

**Comment by joaomoreno** [comment]
Simply disable the `git.terminalAuthentication` setting.
