### ISSUE TITLE
Ability to change the background color of the current scope

### ISSUE THREAD

**Issue by ssoher** [microsoft/vscode#103312]
I want to be able to change the background color of the scope the cursor is currently in. When the cursor enters a scope, that scope will be colored differently from the rest of the file. Please see the below image of what I aim for.

Is this possible with an editor extension? If so please let me know how I can get the current scope from the extension api.

![scope_highlight](https://user-images.githubusercontent.com/4283979/88459253-9fd55600-ce9c-11ea-9d2c-88d765a46500.jpg)

**Comment by ArturoDent** [comment]
See https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.scoper fro example.

**Comment by ssoher** [comment]
@ArturoDent Scoper is exactly what I wanted, thank you very much!
