### ISSUE TITLE
An error occured while loading the image (WSL2)

### ISSUE THREAD

**Issue by mnunezdm** [microsoft/vscode#103482]
Issue Type: <b>Bug</b>

1. Open a project inside WSL2
1. Open an image
1. Error appears (An error occured while loading the image)

![image](https://user-images.githubusercontent.com/10410852/88658746-317ad880-d0d4-11ea-94bc-6514d94bf2e5.png)

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3695)|
|Memory (System)|5.80GB (0.93GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3695)|
|Memory (System)|5.80GB (0.93GB free)|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-pmd|chu|0.5.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
json-tools|eri|1.0.2
prettier-vscode|esb|5.1.3
sfdx-autoheader|Hug|0.7.0
vscode-peacock|joh|3.7.2
chat|kar|0.35.0
git-graph|mhu|1.25.0
vscode-autoprefixer|mrm|3.0.1
vsliveshare|ms-|1.0.2478
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
vscode-xml|red|0.13.0
salesforce-vscode-slds|sal|1.1.0
salesforcedx-vscode|sal|49.2.0
salesforcedx-vscode-apex|sal|49.2.0
salesforcedx-vscode-apex-debugger|sal|49.2.0
salesforcedx-vscode-apex-replay-debugger|sal|49.2.0
salesforcedx-vscode-core|sal|49.2.0
salesforcedx-vscode-lightning|sal|49.2.0
salesforcedx-vscode-lwc|sal|49.2.0
salesforcedx-vscode-visualforce|sal|49.2.0
vscode-peacock|joh|3.7.2
vscode-docker|ms-|1.4.1
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.9
material-icon-theme|PKi|4.2.0
material-theme|zhu|3.8.5

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by mnunezdm** [comment]
Works fine in insiders

![image](https://user-images.githubusercontent.com/10410852/88770897-c0dcc600-d17e-11ea-902e-3e872342df5f.png)
