### ISSUE TITLE
how to sign in

### ISSUE THREAD

**Issue by samarlogan** [microsoft/vscode#103413]

**Comment by IllusionMH** [comment]
/needsMoreInfo

If it's about Settings sync - it's still in development and available only in Insiders builds https://code.visualstudio.com/insiders/

See docs for details https://code.visualstudio.com/docs/editor/settings-sync

**Comment by samarlogan** [comment]
okay sir i got it 

> /needsMoreInfo
> 
> If it's about Settings sync - it's still in development and available only in Insiders builds https://code.visualstudio.com/insiders/
> 
> See docs for details https://code.visualstudio.com/docs/editor/settings-sync

thnx sir i got that, issue was about syncing
