### ISSUE TITLE
Cannot find module vscode-js-debug-bootloader.js

### ISSUE THREAD

**Issue by rkrueger11** [microsoft/vscode#103490]
- VSCode Version: Version: 1.47.3
  - Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
  - Date: 2020-07-23T13:08:29.692Z
  - Electron: 7.3.2
  - Chrome: 78.0.3904.130
  - Node.js: 12.8.1
  - V8: 7.8.279.23-electron.0
  - OS: Darwin x64 19.5.0
- OS Version: macOS Catalina 10.15.5 (19F101)

Steps to Reproduce:

1. Cannot start webpack using the integrated terminal, using a external terminal and everything runs fine

Does this issue occur when all extensions are disabled?: Yes; auto attach is also off.

I looked for duplicates, but those seemed to suggested they are windows specific

**Comment by connor4312** [comment]
Please see https://github.com/microsoft/vscode/issues/102057#issuecomment-657728467

/duplicate
