### ISSUE TITLE
I can't sign in my account

### ISSUE THREAD

**Issue by cemsit** [microsoft/vscode#103495]
Issue Type: <b>Bug</b>

I want to open my microsoft account on Visual Studio Code, but I cannot see the account opening menu among the options.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (84)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
project-manager|ale|11.1.0
mongoose-deps-gen|alx|0.1.3
expressjs|ama|2.0.0
laravel-extra-intellisense|ami|0.3.1
vscode-file-header-comment|Ani|0.10.1
vscode-color|ans|0.4.5
chronicler|arc|0.1.8
atlascode|atl|2.6.6
vscode-intelephense-client|bme|1.5.3
turbo-console-log|Cha|1.4.0
laravel-goto-view|cod|1.3.3
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
vscode-faker|dee|1.4.1
javascript-ejs-support|Dig|1.3.1
githistory|don|0.6.8
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|2.8.2
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
json-tools|eri|1.0.2
prettier-vscode|esb|5.1.3
html-to-javascript-string|evi|0.0.6
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
vscode-auto-open-markdown-preview|hnw|0.0.4
vue-snippets|hol|0.1.12
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
adonisjs-snippets|Hri|1.0.2
icon-fonts|idl|2.3.1
vue|jcb|0.1.5
sublime-babel-vscode|jos|0.2.10
vscode-styled-components|jpo|0.0.29
react-native-snippet|jun|0.5.6
vscode-js-annotations|lan|0.11.0
sftp|lix|1.12.9
edge|luo|0.3.2
vscode-language-babel|mgm|0.0.29
dotenv|mik|1.0.1
vs-code-quick-require|mil|3.1.3
vscode-language-pack-tr|MS-|1.47.3
mssql|ms-|1.9.0
vscode-react-native|msj|0.16.1
sqltools|mtx|0.22.11
clear-console|mwo|0.0.3
color-highlight|nau|2.3.0
prettier-standard-vscode|num|0.8.1
vetur|oct|0.25.0
laravel-blade|one|1.22.1
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.9.0
prettier-vscode-with-tabs|pas|1.1.0
material-icon-theme|PKi|4.2.0
vscode-css-peek|pra|4.0.0
java|red|0.65.0
vscode-yaml|red|0.9.1
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.27
vue-vscode-snippets|sdr|1.9.0
html5-boilerplate|sid|1.0.3
swdc-vscode|sof|2.2.41
adonis-js-goto-controller|ste|0.0.4
adonis-js-goto-view|ste|0.0.2
laravel-goto-controller|ste|0.0.7
addDocComments|ste|0.0.8
vscode-surround|Swo|1.0.1
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-maven|vsc|0.23.0
quokka-vscode|Wal|1.0.311
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
local-history|xyz|1.8.1

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

If it's about Settings sync - it's still in development and available only in Insiders builds https://code.visualstudio.com/insiders/

See docs for details https://code.visualstudio.com/docs/editor/settings-sync

**Comment by cemsit** [comment]
When I click to mannage button like in this link  "https://code.visualstudio.com/docs/editor/settings-sync" there is no "Turn On Preferences Sync..." option. So i can't sign in.

**Comment by cemsit** [comment]
> /needsMoreInfo
> 
> If it's about Settings sync - it's still in development and available only in Insiders builds https://code.visualstudio.com/insiders/
> 
> See docs for details https://code.visualstudio.com/docs/editor/settings-sync

I missed that my mistake is only valid for Visual Studio Code Insider. Thank you
