### ISSUE TITLE
Can't see how to create a second folder at top level

### ISSUE THREAD

**Issue by lepkon** [Microsoft/vscode#10343]
- VSCode Version: all
- OS Version: windows

Steps to Reproduce:

1. create a first folder at top level
2. create a second folder by selecting project. second folder will be under first folder instead of being under projet as for first folder

**Comment by bpasero** [comment]
You can click outside of the folder anywhere in the empty area.

**Comment by lepkon** [comment]
ah yes ok :+1:  (still not very intuitive, and why on earth does the icons disappear when folding the whole project :) )
