### ISSUE TITLE
Allow font setting overrides per theme

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#103422]
Issue Type: <b>Feature Request</b>

I find that when using  a light theme, I need a heavier weight of my coding font.

I switch between light and dark often, if I am coding outdoors or in a bright room I prefer a light theme.

I was suprised I could not do something like
```
    "[Ayu Light]": {
      "editor.fontFamily": "JetBrainsMono-Medium",
    }
```
Something like this would be ideal.

VS Code version: Code - Insiders 1.48.0-insider (731f9c25632dbbf01ee3a7892ad9d2791fe0260c, 2020-07-24T05:51:27.957Z)
OS version: Darwin x64 19.6.0

**Comment by alexdima** [comment]
fyi @sandy081 - theme specific settings.
