### ISSUE TITLE
Why are multiple debugging threads being started in integrated Python-debugging of VS Code?

### ISSUE THREAD

**Issue by AndreasLuckert** [microsoft/vscode#103408]
**- VSCode Version:** 1.47.2
17299e413d5590b14ab0340ea477cdd86ff13daf
x64
**- OS Version:** Operating System: Ubuntu 18.04.4 LTS
            Kernel: Linux 5.4.0-42-generic
      Architecture: x86-64

**Steps to Reproduce:**

1. Open a python-code (.py-file) in VS Code.
2. Start debugging via F5.
3. See how multiple threads are starting debugging the code simultaneously while slowing down the entire computer unnecessarily:
![Python_debugging_VS_Code_multiple_processes_in_parallel](https://user-images.githubusercontent.com/52284494/88540621-98848880-d013-11ea-8ebb-3421dd853748.png)

For all the other details, please visit my [question on StackOverflow](https://stackoverflow.com/questions/63011957/why-are-multiple-debugging-threads-being-started-in-integrated-python-debugging).

I'm asking for help in this issue here as well since on StackOverflow there was no significant activity regarding the solving of this matter.

Does this issue occur when all extensions are disabled?: Yes/No
I cannot do this since I need at least the python-extension for debugging with python.

**Comment by weinand** [comment]
VS Code only shows what is being requested by the Python debugger. So you'll have to ask over there...
