### ISSUE TITLE
Sfdx commands keep running when executed....

### ISSUE THREAD

**Issue by jpoonam4** [microsoft/vscode#103491]
Summary
From past few days the SFDX commands are taking way to long to execute, infact I had to cancel them because they are just shown as running for infinite

For Ex: 1.SFDX: Create Project will run infintly,it will create project on system but vsc don't reload/ shows the created project.
I observed this for more than 20 min and i have to cancel that.

     2.SFDX: Authorize an Org / SFDX: Deploy Source to Org command progress indicator keeps on running.
Steps To Reproduce:
1:execute sfdx command : SFDX: Create Project
used Standard standard project template(default)

Expected result
Project should be created and it should open in vsc.

Actual result
The command progress indicator keeps on running.
It creats Project folder on system but command do not terminate.
Not getting 2nd Output on vsc which contains ended with exit code 0.

execute sfdx command : SFDX: Authorize an Org
Expected result
![actual](https://user-images.githubusercontent.com/22389139/88681329-15485d00-d10f-11ea-8e67-5bdf7a09c580.jpg)

Actual result
The command progress indicator keeps on running.
![result actual](https://user-images.githubusercontent.com/22389139/88681288-095c9b00-d10f-11ea-963b-0f13e0c9ffce.png)

Additional information:

VS Code Version:
1.47.3

SFDX CLI Version:
sfdx-cli/7.60.0-e2bb2907cb win32-x64 node-v10.15.3

Java Version:
1.8.0_261

System type :
64-bit Operating System,x64-based processor
Windows 10

**Comment by gjsjohnmurray** [comment]
/causedByExtension you are using the Salesforce extension(s) so please report the issue there.

**Comment by jpoonam4** [comment]
Thanks
