### ISSUE TITLE
Git:Clone not available 

### ISSUE THREAD

**Issue by szoha29** [microsoft/vscode#103468]
Issue Type: <b>Feature Request</b>

When I searched for Git:Clone in the Command Palette then no search result found. I am using VS Code on windows 10.

Steps:
1. In VS Code, open the Command Palette using Ctrl+Shift+P.
2. Type: git clone

Actual Result: Nothing in the search result.
Expected Result: Git:Clone should show in the search result.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.16299

**Comment by joaomoreno** [comment]
Can you run `Developer: Show Running Extensions` and show me a screenshot of that?
