### ISSUE TITLE
It gets hanged. 

### ISSUE THREAD

**Issue by VEDdroid** [microsoft/vscode#103424]
We have written the needed d
Issue Type: <b>Performance Issue</b>

Whenever after a medium usage of VS Code in a day, it gets hanged  unexpectedly. Kindly hep to tackle this issue.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (4.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    90	 11684	code main
    0	   157	  2220	   window (pract 2 dsl.py - Visual Studio Code)
    0	    82	  5592	     extensionHost
    0	    25	 10564	       C:\Users\91897\AppData\Local\Programs\Python\Python38-32\python.exe c:\Users\91897\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\pyvsc-run-isolated.py c:\Users\91897\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\completion.py
    0	    11	  3668	         console-window-host (Windows internal process)
    0	    17	  9108	         C:\Users\91897\AppData\Local\Programs\Python\Python38-32\python.exe c:\Users\91897\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\lib\python\jedi\inference\compiled\subprocess\__main__.py c:\Users\91897\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\lib\python 3.8.4
    0	    11	  2360	           console-window-host (Windows internal process)
    0	    23	  3576	   utility
    0	    74	 10048	   window (Issue Reporter)
    0	   181	 10884	   gpu-process
    0	    11	 17108	   electron-crash-reporter
    0	    67	 17772	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.7.96456

</details>
ata into your clipboard because it was too large to send. Please paste.

**Comment by rebornix** [comment]
Can you please follow our wiki https://github.com/microsoft/vscode/wiki/Performance-Issues to provide detailed information to help troubleshoot?
