### ISSUE TITLE
Search does not work when the file path contains non-alphanumeric characters

### ISSUE THREAD

**Issue by jneale** [microsoft/vscode#103481]
Issue Type: <b>Bug</b>

1. Create a folder path with your files to search including a non-alphanumeric character, e.g. "./workspace/[ws] Test/"
2. Right click on the folder in your workspace and "Find in folder".
3. Try searching for something within that folder. All that is displayed is "No results found in ..." where you expect to see the results.
4. Remove the folder with the non-alphanumeric characters from the "files to includes" input (i.e. just searching in "./workspace/") and see all the search results show up as expected.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/82415
