### ISSUE TITLE
--inspect-brk not being passed to the command.

### ISSUE THREAD

**Issue by KrisChambers** [microsoft/vscode#103411]
- VSCode Version: 1.47.1
- OS Version: Manjaro Lysia 20.0.3

Steps to Reproduce:

I outlined the problems here:
https://github.com/denoland/deno/issues/6855#issuecomment-663355253

Does this issue occur when all extensions are disabled?: Yes

I know this isn't a node specific issue, but Deno uses the node launch configuration in vscode. I have not checked that this is an issue when not using "deno" as the runtime executable, but I will do a little test later to confirm that.

As I state in the linked issue. It looks like --inspect-brk is being eaten up somewhere when launched.

**Comment by connor4312** [comment]
Check out https://github.com/denoland/vscode_deno/issues/12#issuecomment-658957984 for instructions

/duplicate
