### ISSUE TITLE
Duplicate Issue bot is broken

### ISSUE THREAD

**Issue by DylanYoung** [microsoft/vscode#103433]
- VSCode Version: Irrelevant
- OS Version: Irrelevant

Steps to Reproduce:

1. Create an issue that is similar to another, but different.
2. Wait for the Duplicate Issue bot to close it.

Now this isn't the worst in itself, but (and I'm not sure what is triggering this):

1.  The bot doesn't actually identify the duplicate issue (making it largely useless)
2. The bot seems to close out comments and prevent re-opening of issues.  It's great to 
have an automatic triage system, but if the person filing the issue looks at the "flagged duplicate"
and knows it *is not* a duplicate, the bot should respect the fact that it doesn't have human intelligence. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Could you point us at an example?
