### ISSUE TITLE
When docked, the "disconnect" and "stop" icons in the debug toolbar don't update properly

### ISSUE THREAD

**Issue by devuxer** [microsoft/vscode#103463]
- VSCode Version: 1.47.2
- OS Version: Windows 10.0.18363 Build 18363

Steps to Reproduce:

1. Set the debug toolbar to docked in the settings.
2. Debug a Node project using `node --inspect-brk=127.0.0.1:9223`
3. Debug a React project using Debugger for Chrome
3. Once both projects have started up, select each project from the menu in the debug toolbar.
4. Observe that the icon sometimes gets "stuck" as a red square rather than switching between "disconnect" (for the React project) and "stop" (for the Node project).
5. Now switch to the debug toolbar to floating, and note that the icon now correctly updates.

Does this issue occur when all extensions are disabled?: Not possible to test because Debugger for Chrome is required to reproduce this bug

Reference: https://github.com/microsoft/vscode/issues/99786#issuecomment-664344658

**Comment by isidorn** [comment]
I acknowledge this issue and we have always behaved like this. Assigning to next milestone to investigate more then.

**Comment by isidorn** [comment]
I actually pushed a fix.
To verify:
1. Have `"debug.toolBarLocation": "docked"` setting
2. Start two debug sessions, one is `launch`, another `attach`
3. Change focus between them by clicking in the CALL STACK view
4. Make sure the Stop / Disconnect icon is always correct in the docked debug toolbar

**Comment by devuxer** [comment]
@isidorn , Nailed it! Icon seems to update reliably now with Insiders.

**Comment by isidorn** [comment]
@devuxer great, thanks for letting us know. Adding verified label.
