### ISSUE TITLE
Show dialog when open new project

### ISSUE THREAD

**Issue by jindalAnuj** [microsoft/vscode#103401]
Issue Type: <b>Feature Request</b>

If a project is currently opened  and another project is required the vs code directly open the second one project in the same window.

A Dialog is required asking

1.Open in new tab
2 Close this tab and open in current one.
Thanks

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

**Comment by gjsjohnmurray** [comment]
By "project" do you mean "workspace"? If you are picking a workspace off the "Open Recent..." option of the "File" menu, use Shift+Click to open it in a new window.

**Comment by jindalAnuj** [comment]
No not workspace. A window with only a folder is opened like a project. and if i want to open a folder in new tab then the functionality is not there

**Comment by gjsjohnmurray** [comment]
How about "New Window" from the "File" menu, then "Open Folder..." in the new window?

**Comment by jindalAnuj** [comment]
Sorry for late reply.
But that is not very comfortable when we need to open old projects for some really small reference . Also working on multiple project together hard with new window
