### ISSUE TITLE
Custom Auto Imports

### ISSUE THREAD

**Issue by amiratak88** [microsoft/vscode#103429]
It would be nice to add "customAutoImports" to settings.
example:
```
{
  "typescript.customAutoImports": {
    "types": "import * as types from 'src/types';"
  }
}
```

**Comment by mjbvz** [comment]
I believe you could also use snippets for that example

**Comment by amiratak88** [comment]
@mjbvz right, that's I have it setup at the moment. but it's not the same as auto import. I'll try to write an extension for it.
