### ISSUE TITLE
Invisiable ASCII 

### ISSUE THREAD

**Issue by lqiang79** [Microsoft/vscode#10342]
- VSCode Version: 1.3.1
- OS Version: Windows 7

There is some invisiable ASCII 01 chars in my file. In Sublime Text and Notepad++  they can be displayed as 'SOH'. Here in VSCode not. 

Steps to Reproduce:

1. Use this String from https://gist.github.com/lqiang79/2013d793f90821d7fa8191b6e6daee42, copy past into the notepad++ adn VSCode, you can see different

Maybe an auto render for all of the ASCII Control Characters.

**Comment by alexandrudima** [comment]
@lqiang79 Would `View > Toggle Control Characters` work for you?

![image](https://cloud.githubusercontent.com/assets/5047891/17524206/ec0fb6cc-5e5d-11e6-8d91-f401af26fa90.png)

**Comment by lqiang79** [comment]
It looks real nice on you screenshot. But I got error 

No handler found for the command: 'editor.action.toggleRenderControlCharacters'. An extension might be missing an activatio
