### ISSUE TITLE
Remove some deprecated code in ./src/vs/base

### ISSUE THREAD

**Issue by LeuisKen** [microsoft/vscode#103454]
I find that following methods are deprecated:

```
7 results - 2 files

src/vs/base/browser/dom.ts:
  74  };
  75  
  76: /** @deprecated ES6 - use classList*/
  77  export function hasClass(node: HTMLElement | SVGElement, className: string): boolean { return _classList.hasClass(node, className); }
  78: /** @deprecated ES6 - use classList*/
  79  export function addClass(node: HTMLElement | SVGElement, className: string): void { return _classList.addClass(node, className); }
  80: /** @deprecated ES6 - use classList*/
  81  export function addClasses(node: HTMLElement | SVGElement, ...classNames: string[]): void { return _classList.addClasses(node, ...classNames); }
  82: /** @deprecated ES6 - use classList*/
  83  export function removeClass(node: HTMLElement | SVGElement, className: string): void { return _classList.removeClass(node, className); }
  84: /** @deprecated ES6 - use classList*/
  85  export function removeClasses(node: HTMLElement | SVGElement, ...classNames: string[]): void { return _classList.removeClasses(node, ...classNames); }
  86: /** @deprecated ES6 - use classList*/
  87  export function toggleClass(node: HTMLElement | SVGElement, className: string, shouldHaveIt?: boolean): void { return _classList.toggleClass(node, className, shouldHaveIt); }
  88  

src/vs/base/common/strings.ts:
  15  
  16  /**
  17:  * @deprecated ES6: use `String.padStart`
  18   */
  19  export function pad(n: number, l: number, char: string = '0'): string {
```

I'd like to send a pull request to remove these deprecated methods and refactor all usages if you want.

**Comment by rebornix** [comment]
Starting from @mjbvz , not sure where the deprecation information are from.

**Comment by jrieken** [comment]
> I'd like to send a pull request to remove these deprecated methods

:-1: We do not accept pull requests like that

**Comment by jrieken** [comment]
This is driven from `.vscode/searches/es6.code-search` and each and every user of the listed functions needs to become active.

**Comment by jrieken** [comment]
The classList usage is usually a big change, the others should be small... Starting with @joaomoreno, please pass it on to the next person

**Comment by joaomoreno** [comment]
@jrieken I am out this month... sorry.

**Comment by mjbvz** [comment]
Remaining:

- [ ] `src/vs/base/common/strings.ts` — `pad`
- [ ] `src/vs/base/common/strings.ts` — `startsWith`
- [ ] `src/vs/base/common/strings.ts` — `endsWith`
- [ ] `src/vs/base/common/strings.ts` — `repeat `

- [ ] `src/vs/base/common/objects.ts` — `assign`

- [ ] `src/vs/base/browser/dom.ts` — `removeNode`
- [ ] `src/vs/base/browser/dom.ts` — `hasClass` and friends

- [ ] `src/vs/base/common/arrays.ts` —  `first`
- [ ] `src/vs/base/common/arrays.ts` —  `find`

**Comment by isidorn** [comment]
I have replaced my usages of the deprecated code. I believe I have cought all places, however if some remain feel free to ping me.
Assigning this to @joaomoreno since I saw a lot of usages in our widgets, though feel free to pass it on to the next person.

**Comment by joaomoreno** [comment]
Here's a useful find/replace input pair:

```
FIND: (add|remove|toggle)Class\(([^,]+), 
REPLACE: $2.classList.$1(
```

**Comment by joaomoreno** [comment]
The unfortunate choice of having multiple class names on a single string `Codicon.classNames: string` and having `DOM.addClass` support that is the hardest problem here. Going with simple refactoring, powered by TypeScript, you immediately hit **very bad things**:

![image](https://user-images.githubusercontent.com/22350/93088170-de67df80-f699-11ea-8640-b897dbdcf45a.png)

**Comment by joaomoreno** [comment]
After looking at all references from [here](https://github.com/microsoft/vscode/issues/103454#issuecomment-690741424), I believe I got a good picture of the people who would do most of the rest of the changes. Assigning more people.

**Comment by bpasero** [comment]
@joaomoreno I missed it, what should I do if my class contains a space?

**Comment by isidorn** [comment]
Hmm I see that `strings.pad` is deprecated in favor of `String.padStart`. But they do not have the same functionality. Am I missing something here?
Code pointer https://github.com/microsoft/vscode/blob/fcb916f02c49a05a841663f319b8d9dbb3ee2daa/src/vs/base/common/strings.ts#L19

**Comment by jrieken** [comment]
Isn't `strings.pad(1, 10, '0') === String(1).pad(10, '0')`

**Comment by isidorn** [comment]
@jrieken thanks. I have misread the method.

**Comment by sbatten** [comment]
I believe the change I just pushed removes the last usages of `removeNode`

**Comment by bpasero** [comment]
I don't think I own any of the remaining ones but I went through `hasClass` across all usages, I think it's better someone just does them all:

![image](https://user-images.githubusercontent.com/900690/93874935-653d3d80-fcd4-11ea-9862-b889486b9d20.png)

**Comment by jrieken** [comment]
@bpasero there was still some usage of the strings#repeat in your land

**Comment by bpasero** [comment]
@jrieken can you point me to that code please

**Comment by jrieken** [comment]
`src/vs/platform/diagnostics/node/diagnosticsService.ts` you were the last to touch it

**Comment by bpasero** [comment]
@RMacfarlane can you please see https://github.com/microsoft/vscode/commit/02710ecca2d675e98e411f07a2f8879ffc3aba41 if it works as you intended it, I think you are the original author.

**Comment by RMacfarlane** [comment]
Thanks @bpasero, your changes look good!

**Comment by jrieken** [comment]
almost there... @joaomoreno @alexdima @sandy081 @mjbvz for `strings#pad`

**Comment by joaomoreno** [comment]
I've deleted `strings#pad`.

**Comment by mjbvz** [comment]
Remaining (all under `dom.ts`):

- [ ] [`addClass`](https://github.com/microsoft/vscode/blob/cd2a92ae134d4eb20f20f8f6250a4a89c86e7abb/src/vs/base/browser/dom.ts#L72)
- [ ] [`addClasses`](https://github.com/microsoft/vscode/blob/cd2a92ae134d4eb20f20f8f6250a4a89c86e7abb/src/vs/base/browser/dom.ts#L72)
- [ ] [`removeClasses`](https://github.com/microsoft/vscode/blob/cd2a92ae134d4eb20f20f8f6250a4a89c86e7abb/src/vs/base/browser/dom.ts#L72)
- [ ] [`toggleClass`](https://github.com/microsoft/vscode/blob/cd2a92ae134d4eb20f20f8f6250a4a89c86e7abb/src/vs/base/browser/dom.ts#L72)

@joaomoreno Assigning you to start. Please reassign to correct owners for this

**Comment by joaomoreno** [comment]
- Terminal @Tyriar 
- Webview @mjbvz 
- Scrollbar @alexdima 
- Lightbulb Widget @aeschli 
- Workbench Theme Service @aeschli

**Comment by jrieken** [comment]
oh, wow actually done

**Comment by jrieken** [comment]
👏 and thanks everyone involved here
