### ISSUE TITLE
vscode consumes all the memory of OS in one path preview

### ISSUE THREAD

**Issue by cpusam** [microsoft/vscode#103493]
- VSCode Version: 1.45.1
- OS Version: Linux XUbuntu 18.04

BUG explanation:
VScode try to list all the modules from node_modules and so get all the memory of OS (memory leak)

Steps to Reproduce:
1.open vscode 1.45.1 in a linux
2.make a project with many modules
3.try import the module and when go to digit the path, just press ' and the leak will occur

Does this issue occur when all extensions are disabled?: Yes/No
I don't know. Maybe only in javascript files.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by cpusam** [comment]
@mjbvz man, was my error, the "bug" wasn't in the vscode but in my JVM. The bugs occurs at random times and when I'm using the vscode, so I suspected of it. Sorry for the false alarm.
Thanks, I will close the issue.
