### ISSUE TITLE
The icon of the extension details tab is set by extension ID

### ISSUE THREAD

**Issue by tomoki1207** [microsoft/vscode#103438]
At the extension detail tab, the icon may set or may not set.
It seems that the last part of the extension ID(used as extension name) is the cause.

If the extension name matches any file extension that has an icon, the tab will have this icon.
e.g. `redhat.java`
![image](https://user-images.githubusercontent.com/3643499/88594309-ed6be180-d09b-11ea-9bc6-8252dba289a6.png)

Otherwise, use the default icon(same as plain text).
e.g. `ms-dotnettools.csharp`
![image](https://user-images.githubusercontent.com/3643499/88594381-0c6a7380-d09c-11ea-83bb-40addc841183.png)

Sometimes the extension icon is appropriate(like `golang.go`), but this is rare and maybe coincidence.

The extension ID is described as `author.extension-name` and it can't rename after publish, the extension author control this appearance is difficult.
I think that the icon of the extension detail tab is either of the following is better.
1. Use common icon (the Extensions icon in the Activity Bar is good) 
1. Use the extension's icon configured at package.json.

- VSCode Version: 1.47.3
- OS Version: macOS 10.15.6

Steps to Reproduce:

1. Open extension details tab from the extension view.

Does this issue occur when all extensions are disabled?: Yes

**Comment by JohnTheFarmer** [comment]
use  original extension's icon would be good , but most of them are PNG right?  and vscode tab icon only allow glyph in an icon font ? most of the icons are from seti.woff ,  so maybe the developers provide their own glyph   or vscode add support for PNG icon
