### ISSUE TITLE
VS Code will mess up Git commits

### ISSUE THREAD

**Issue by mhjartstrom** [microsoft/vscode#103475]
Issue Type: <b>Bug</b>

I've noticed a very disturbing behavior in VS Code, where it seems to retain the state of a conflicted merge in Git even though it has been resolved. I'm on a branch, e.g. "work", and I do a git rebase to edit a couple of commits on that branch:

work> git rebase -i master (choose edit on at least one commit)
work> git commit --amend (accept changes)
work> git rebase --continue

Now there's a conflict in one of the later commits, so I use an external tool (Beyond Compare 4) to do a three-way merge and since I have that configured as my merge tool and to "trustexitcode" from that all is handled properly.

work> git mergetool
work> git status (all files are staged to be committed automatically)
work> git diff (shows nothing...)
work> git diff HEAD (shows all changes perfectly)

Now, the thing is that VS Code will still show the highlighted conflict markers in the code with the codelens "Accept changes" and so on... I'm on Windows running VS Code in WSL, doing Python development and handling Git in a Windows Terminal Bash prompt. Beyond Compare 4 is a Windows process and the files are all stored in My Documents accessed through /mnt/.

work> git rebase --continue

What happens now is beyond me... For some reason, next time I have a look at the commit it'll have the conflict markers left in the code. Even though the code was staged and ready to be committed, with no markers present! It's as if VS Code automatically stages the conflicted files as soon as the rebase operation is triggered!

If I go through the same process but I leave VS Code closed from calling git mergetool until the whole operation is finished it'll work!

This is disturbing on so many levels, mainly because VS Code makes you question wheather the version control system actually works or not.

You NEED to fix this a.s.a.p. (like immediately i.m.h.o.)!

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (7.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2801)|
|Memory (System)|15.83GB (7.74GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.0
python|ms-|2020.7.96456
vscode-pylance|ms-|2020.7.3
bash-debug|rog|0.3.9
vscodeintellicode|Vis|1.2.9
remote-wsl|ms-|0.44.4
code-settings-sync|Sha|3.4.3

(1 theme extensions excluded)

</details>

**Comment by Jupakabra** [comment]
This is happening for a while from what I remember.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/103617
