### ISSUE TITLE
Control + F Stopped working on partial string search

### ISSUE THREAD

**Issue by AlxSts** [microsoft/vscode#103432]
Running June 2020 (version 1.47.3)

If you have a string "Function Test()" and try to Ctr+F "on Test" no result is found.

Thanks in advance to all those guys that make VS Code such a nice tool.

Alexandre Santos

![image](https://user-images.githubusercontent.com/17136246/88584513-16eb2580-d028-11ea-8324-c7110243a1a3.png)

**Comment by gjsjohnmurray** [comment]
You have enabled "Match Whole Word"

![image](https://user-images.githubusercontent.com/6726799/88585293-d3ee7980-d04a-11ea-98b1-b2762ff0d2ca.png)

**Comment by roblourens** [comment]
Thank you @gjsjohnmurray, good catch!

**Comment by AlxSts** [comment]
Ooops! Sorry. Thank you very much!
