### ISSUE TITLE
vscode with chrome dev on error

### ISSUE THREAD

**Issue by shanike** [microsoft/vscode#103474]
- VSCode Version: 1.47.3

Steps to Reproduce:

1. some compilation error
2. on chrome dev tool (localhost:3000) an error page will appear with an option to click on the error
3. on click, vscode opens a new app window (with the cursor on the line of said error), instead of redirecting existing vscode application to said file
up till now vscode used to open the file with the cursor on the error line. I updated vscode (June 2020) and instead of opening the file with the error in _current_ window, it opens a new one ugh 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
Could you please provide some recording/gif of what happened? I didn't follow what you described above.

**Comment by shanike** [comment]
say I got this error:
![Screenshot from 2020-07-29 09-15-03](https://user-images.githubusercontent.com/56911506/88763706-41e68e00-d17c-11ea-8ab0-6c7c733818dd.png)

when I click it, it used to take me to my vscode file (App.js) to the line the error occurred on
BUT after the June 2020 update, it opens a **new vscode window** (open on the file with the error in in-App.js) but it shouldn't. It should open the **existing** vscode window and open me the right file (as it has been up till yesterday)

**Comment by shanike** [comment]
was fixed, don't know why or who
