### ISSUE TITLE
Pasting text with new line in with multiple cursors does not act as expected 

### ISSUE THREAD

**Issue by software-opal** [microsoft/vscode#103456]
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
emojisense|bie|0.7.0
markdown-checkbox|bie|0.1.3
gitignore|cod|0.6.0
macros|ctf|0.0.4
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
vscode-firefox-debug|fir|2.9.0
code-runner|for|0.11.0
vscode-pull-request-github|Git|0.18.0
go|gol|0.15.2
terraform|has|2.1.1
output-colorizer|IBM|0.1.2
vscode-essentials|jab|1.5.0
search-editor-apply-changes|jak|0.1.1
elixir-ls|Jak|0.5.0
vscode-text-pastry|jkj|1.2.0
vscode-peacock|joh|3.7.2
jq-syntax-highlighting|jq-|0.0.2
vscode-github|Kni|0.30.3
vscode-format-context-menu|lac|1.0.4
bash-ide-vscode|mad|1.10.2
metago|met|4.2.0
MetaJump|met|1.1.1
MetaWord|met|1.2.1
git-graph|mhu|1.25.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.4.1
python|ms-|2020.7.96456
hexeditor|ms-|1.1.0
gremlins|nho|0.23.0
polacode|pnp|0.3.4
explorer-exclude-vscode-extension|Red|1.2.0
elixir-formatter|sar|1.3.0
rewrap|stk|1.13.0
code-spell-checker|str|1.9.0
shellcheck|tim|0.9.0
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0
codetour|vsl|0.0.34
gistfs|vsl|0.1.8

(1 theme extensions excluded)

</details>

Steps to Reproduce:

1. Create a document with multiple lines. Ex:
   ```
   aaa
   bbb
   ccc
   ```
2. Make a selection across two lines. Ex:
   ```
   a
   bbb
   ```
3. Place two cursors, and paste(for example at the end of `bbb` and `ccc`).

What should result is:
```
aaa
bbba
bbb
ccca
bbb
```

What actually results is:
```
aaa
bbba
cccbbb
```

This is very confusing and frustrating. The 'correct' result occurs when more than 2 cursors are selected(for example at the end of `aaa`, `bbb`, and `ccc`):
```
aaaa
bbb
bbba
bbb
ccca
bbb
```

![Two line paste](https://user-images.githubusercontent.com/2038057/88618234-a9ed9380-d0ec-11ea-8cce-ba69c14adde0.gif)
![Three line paste](https://user-images.githubusercontent.com/2038057/88618230-a823d000-d0ec-11ea-86f4-c8e945b0767a.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/102720#issuecomment-659582912 for the setting to get the behaviour you want.
