### ISSUE TITLE
Can vscode automatically configure common languages such as C + + / Java / Python?

### ISSUE THREAD

**Issue by Craker0003** [microsoft/vscode#103402]
I'm a friend from China. I don't speak English very well. This passage is translated by translation software. It may be strange to read.
I am an information science competition student who is learning C + +, I will not configure vscode
The answer on the browser is not satisfactory, and official documents are useless
I hope you can solve the configuration problem as soon as possible

**Comment by Craker0003** [comment]
You can do a survey. I think at least 50% of people can't configure vscode

**Comment by devqazi** [comment]
First, it is not an IDE. It is a code editor and just that. It edits code, it does configure development environments. Installing compilers  , runtime etc is the job of the user. 

What you are looking for is an IDE.
