### ISSUE TITLE
Explore open/install an extension from the Market Place

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#10340]
The idea here is to support URLs such as `vscode:extension/${UUID}`. These could make Code open that extension in its UI, allowing for a fast path towards extension installation from the Marketplace.

Code is in https://github.com/joaomoreno/vscode/tree/urlservice

- [x] Propagate Electron's `app.on('open-url')` to the last focused Window
- [x] Make Extension contribution listen on `onOpenUrl` events and open the extension UI
- [x] Figure out how to do the same when Code is not running	69e8c7a
- [x] Implement for Windows 8609a07
- [x] Talk to Marketplace guys about this, along with a demo @waderyan 
- [x] Coordinate with @hamenon on the UI for the marketplace @waderyan
- [x] Create docs for figuring out your VS Code version @waderyan

**Comment by joaomoreno** [comment]
> @hamenon says:

CC: @waderyan @joaomoreno @seanmcbreen 

With the direct application URL handler changes coming in this next iteration we're working on changes to the Marketplace UX to allow direct installation of extension from Marketplace. We wanted to run a few options by you to get your thoughts as well, as there are a few factors to consider:

- The VS Code insiders build has a separate application handler so needs to be handled separately

- Older versions of the client won’t support the application handler hence copy command option still needs to be present

Following are two options we're considering:
Option 1:
![vscode install1](https://cloud.githubusercontent.com/assets/13758921/17803615/27e0aa08-6615-11e6-84c1-e26071499693.png)
Option 2:
![vs code install2](https://cloud.githubusercontent.com/assets/13758921/17803619/2e683738-6615-11e6-9f92-dc961f2368c2.png)

Current preference is toward option 1, the reasoning being:

- A majority of the users are generally on the latest build and hence that should be the most prominent CTA (Install button)
- We can also take a call to remove the helper message once enough users have moved to the latest version.

**Comment by joaomoreno** [comment]
How about something like this?

![image](https://cloud.githubusercontent.com/assets/22350/17804049/1ea5775e-65fa-11e6-9e4e-a3bdd385a865.png)

The main button would be the `Install` action. The dropdown would expose another option to install in the insiders build and the description to install with `ext install`.

**Comment by waderyan** [comment]
@joaomoreno yeah I like that. 

1. User clicks on the Install button
2. User determines which VS Code version
3. User clicks the appropriate version. 

The second step (2 from above) does cause cognitive friction. How many users know what their version is? If we could do the above, but with something making it obvious that if you've updated recently use this one. 

Here's a slight addition to @joaomoreno's. 

![image](https://cloud.githubusercontent.com/assets/2449568/17817424/4f847430-65f3-11e6-984f-2bacc6351579.png)

The goal is to reduce the cognitive friction of __having to find out your version__. I think its obvious to us how to find the version, but it may or may not be to others. 

ping @hamenon - see above.

**Comment by hamenon** [comment]
The issue I have is around discoverability. At least at launch majority of the users will be on the older version which supports only the copy based method. For those users the install button click which is the primary action based on the above design will fail, and they'll then have to click on the arrow portion to choose the appropriate version etc. 

Also if the idea is to phase out the copy based option eventually wouldn't it make more sense to simplify and have both install options (latest and insiders) present directly as opposed to under a menu?

**Comment by waderyan** [comment]
@hamenon I think I'm seeing your point. In your mind:

1. User sees the install button. 
2. User clicks install button (main action)
3. Nothing happens for users on an older version. 
4. User comes back to the site and has to know to click the arrow portion of the button. 

Is that correct?

**Comment by waderyan** [comment]
We might be in the weeds and losing marginal benefit. 

I would be in favor of the option below, as long as we add something about finding the version of VS Code. It could be a link to VS Code's docs (we can make a short section on how to find your version). I'm concerned a non trivial number of users won't know what their version is. 

![image](https://cloud.githubusercontent.com/assets/2449568/17866367/1eb53672-685b-11e6-92c5-f4394474cfe6.png)

@joaomoreno thoughts?

**Comment by hamenon** [comment]
@waderyan Yup, thats exactly it. 

I see your point about users not knowing what version they are on. We can improve the message below the install to include something like a "Find out yours" link that points to documentation on finding out the VS Code version.

**Comment by joaomoreno** [comment]
Sounds good to me!

**Comment by waderyan** [comment]
cc @seanmcbreen see above on design iterations.

**Comment by waderyan** [comment]
ping @hamenon 

@joaomoreno a question came up during our call today. For earlier versions of VS code that do not have the URL handler what will happen if they click the install button? My assumption is nothing will happen because there is no URL handler (i.e. we won't show them a warning or anything). 

Timing update from Marketplace
- Looking at doing the work for this a week after August release.

**Comment by joaomoreno** [comment]
Closing the exploration as it seems our work is done in macOS and Windows.

**Comment by joaomoreno** [comment]
Verification only in Windows and macOS. Format:

```
vscode:extension/vscodevim.vim
vscode-insiders:extension/vscodevim.vim
```

**Comment by chrmarti** [comment]
OSX: Verified vscode-insiders: with Safari, Chrome, Firefox
Windows: Verified with Edge, Chrome, Firefox

On Windows, if VSCode is already running, its window does not get to the top. The user might not notice anything has happened at all.

Removing the verified label again so we can confirm it is working the stable release.
