### ISSUE TITLE
JavaScript language support reports assignment to function as error instead of warning

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#1034]
This is a holdover from TS language service errors.

![image](https://cloud.githubusercontent.com/assets/972891/11605161/233b6576-9aad-11e5-9400-5191d1b9bda5.png)

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).
