### ISSUE TITLE
TFS: File not found when setup VS Code as diff tool

### ISSUE THREAD

**Issue by minhhut** [Microsoft/vscode#10349]
- VSCode Version: 1.4.0
- OS Version: Window 10 64 bits

Steps to Reproduce:

1. Setup VS Code as Diff tool in TFS (code -d -r %1 %2)
2. Show diff from TFS by click a file and sometime get this error below

![image](https://cloud.githubusercontent.com/assets/656141/17521863/474d6d62-5e55-11e6-84c9-11f4d67734d8.png)

**Comment by bpasero** [comment]
If the file does not exist, it means it was not created by TFS in time.

**Comment by minhhut** [comment]
Same setup with kdiff (kdiff %1 %2) and don't see problem

**Comment by minhhut** [comment]
This only happen when i use option -r to open in same window (code -d **-r** %1 %2)

**Comment by bpasero** [comment]
Likely https://github.com/Microsoft/vscode/issues/14534
