### ISSUE TITLE
README Preview doesn't supports checkboxes 

### ISSUE THREAD

**Issue by jai-dewani** [microsoft/vscode#103441]
- [x] Search the issue repository to ensure your report is a new issue
- [x] Recreate the issue after disabling all extensions
- [x] Simplify your code around the issue to better isolate the problem
### Version Info
- Version: 1.47.2 (user setup)
- Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
- Date: 2020-07-15T18:22:06.216Z
- Electron: 7.3.2
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Windows_NT x64 10.0.18362

### Steps to Reproduce:

1. Create a README.md 
2. Enter markdown for checkboxes
```
- [x] step 1
- [ ] step 2
```
3. Open preview for the readme. It should look something like this
![image](https://user-images.githubusercontent.com/33520257/88597454-db327900-d084-11ea-8f3e-27e5841abdfc.png)

Instead, the preview must have been something like this: 
- [x] step 1
- [ ] step 2

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox
