### ISSUE TITLE
Disallow disabling auth extensions while being used by settings sync

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#103405]
Currently one can disable an auth extension that provides auth token for settings sync. 

We shall disallow this.

**Comment by sandy081** [comment]
@RMacfarlane This needs extension declaring auth providers through `package.json`. By doing so, we can detect if an extension is contributing an auth provider and check if those auth providers are being used for settings sync or not and prevent it from disabling.

**Comment by sandy081** [comment]
@RMacfarlane Is there a request to track static contributions for authentication providers?

**Comment by RMacfarlane** [comment]
Yeah, here's the issue for it: https://github.com/microsoft/vscode/issues/103507

**Comment by sandy081** [comment]
To verify:

- Make sure you can disable auth provider extensions (Github/Microsoft) can be disabled only globally. 
- Disabling these extensions at workspace level is not allowed
- If Settings Sync is on and using one of these accounts, Make sure you cannot disable that extension at all.
