### ISSUE TITLE
Add score sorting to text search so that search results can be provided by relevance

### ISSUE THREAD

**Issue by damienmg** [microsoft/vscode#103465]
Hello,

Ordering by path in a big repository is rarely the good option, it buries the interesting results deep.

I would like to keep the relevance of search results from the search service I am using (similar to the service backing http://source.chromium.org), the cleanest way I found was to extend the sorting ability by adding `scoreAscending` and `scoreDescending` sorting options and a `score` parameter to the `IFileMatch` interface.

I am willing to contribute directly to whichever solution seems adequate but I thought it would be better to open a discussion first, especially since I found the following related issues:

* #103052, #83462: issues for file search, related, happy to try to solve it together with this one as this is also a problem for us.
* #84926: incremental search should be fixed with that ordering, as the default score would be the insertion order.
* #63797: allow text search provider to return relevance order is exactly the same proposal but the conversion got locked down.

Thanks for this awesome IDE!

**Comment by JacksonKearl** [comment]
To be clear, are you referring to results provided by the (proposed) `provideTextSearchResults` API? Is the idea that individual results would have `score`'s, or that `URI`'s would have them? IMO having results scored and not grouped by URI would be very odd, and it would break a lot of assumptions we make in how results are displayed.

**Comment by damienmg** [comment]
> To be clear, are you referring to results provided by the (proposed) `provideTextSearchResults` API?

Yes I am speaking about the result of provideTextSearchResults API

> Is the idea that individual results would have `score`'s, or that `URI`'s would have them? IMO having results scored and not grouped by URI would be very odd, and it would break a lot of assumptions we make in how results are displayed.

Sorry I should have been clearer. A FileMatch is getting a score, not the individual match. So that would mean a score is given by URI. In my case, the matches are grouped by file.

**Comment by JacksonKearl** [comment]
I see... though the `FileMatch` is internal, the text search resolver only speaks in `TextSearchResult`s, which are individual match items. Thus this would likely come with a pretty substantial API change. cc @roblourens

**Comment by damienmg** [comment]
Right sorry our extension is current implemented as a contrib, so we use the internal API. Although I was having a mental matching of TextSearchMatch to FileMatch but it is indeed wrong at the moment.

A simple proposal would be to allow to return multiple text preview on a TextSearchMatch as there is multiple ranges (so that one can return multiple text in one TextSearchMatch), although that might make the API too hairy.

Another idea I see would be to add the score to `TextSearchMatch` and then textSearchProvider can provide a method to merge scores. In that case, in my view, the best default score for a URI would be the maximum of all scores [i.e. you get the best matches first, but still grouped by URI].

If you search [Chromium Code Search for example](https://source.chromium.org/search?q=foo%20bar%20language:c%2B%2B%20-f:aosp), you get the following results:

![Screen Shot 2020-07-30 at 9 54 21 AM](https://user-images.githubusercontent.com/3721087/88896802-a7a14b80-d24a-11ea-8863-5f1a3ff95932.png)

You can see that the results themselves are scored since not all of them would appear without expansion.

So the natural ordering would be to order all matches by score inside a file and to order file by aggregated score.

(I hope that make sense).

**Comment by roblourens** [comment]
This would make sense, however that API will not be stabilized anytime soon, so I would be careful using it.

**Comment by damienmg** [comment]
@roblourens, @JacksonKearl  so what would be the next step? How can I help? (as I said early, I am more than happy to do both API proposals and send the necessary PR to make this happen).

**Comment by roblourens** [comment]
It hasn't been touched for awhile and needs much more thought. We are involved with other things right now and I don't plan to revisit it in the near future. But it would be helpful if you tell me more about your use case because I want to keep track of what people would like to use it for.

**Comment by damienmg** [comment]
My use case is exactly to integrate with a search backend since our repository is a little too big to index. The public version of that search engine can be seen on [Chromium](https://cs.chromium.org), [Android](https://cs.android.com) and [our others opensource projects](https://cs.opensource.google).

The source themselves are served with a distributed file system and doing a linear regexp search on them would be way too expensive.

**Comment by bolinfest** [comment]
@damienmg Note that #83462 lists a bunch of open design questions from @roblourens when we brought this up before.

**Comment by damienmg** [comment]
Thanks @bolinfest! I don't know how I missed that bug during my search.

**Comment by roblourens** [comment]
Closing in favor of the main API issue, I expect that it would support this use case but we don't have a near-term plan to work on this.
