### ISSUE TITLE
remote debugging isn't working

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#10346]
- VSCode Version:1.4.0
- OS Version:ubuntu 16.4

Steps to Reproduce:
1. run an app on debug more `node --debug`
2. try to connect to the remote server ip running the debugger
3. it will stop if you specified the --debug-brk option on the first line but once when you hit continue it no longer stops in the break points you specify in vscode 

not: i havent tried using `debugger` keyword inside code since its already on the server its not the best way i think

**Comment by weinand** [comment]
@NikosEfthias please read the section "Remote Debugging Node.js" in https://code.visualstudio.com/docs/editor/debugging for learning how to map local and remote paths by using `localRoot` and `remoteRoot`attributes. Without this, breakpoints won't work.

**Comment by weinand** [comment]
@NikosEfthias could you solve the issue by setting the `localRoot` and `remoteRoot` attributes?

**Comment by NikosEfthias** [comment]
hi sorry i didnt have time yet on weekend hopefully i will try

**Comment by NikosEfthias** [comment]
hi @weinand shoudl i pass a full remote path something like /home/<user>/<projectBase>

**Comment by weinand** [comment]
The output of the remote node.js is only available on the remote system. VS code has no access to it because VS Code did not launch the remote node.js.
