### ISSUE TITLE
The program will not respond when dragging tabs or file items with the mouse.

### ISSUE THREAD

**Issue by userbabu** [microsoft/vscode#103450]
Issue Type: <b>Bug</b>

The program will not respond when dragging tabs or file items with the mouse.

I want to drag and drop the tab to another partition or drag and drop files to other folders will cause the program to stop working for more than ten seconds

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.95GB (16.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
html-snippets|abu|0.2.1
vscode-intelephense-client|bme|1.5.3
path-intellisense|chr|2.2.1
vscode-eslint|dba|2.1.8
es7-react-js-snippets|dsz|2.8.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
file-icons|fil|1.0.25
auto-rename-tag|for|0.1.4
mvcstarter|gab|1.2.2
beautify|Hoo|1.5.0
crane|Hvy|0.3.8
ftp-sync|luk|0.3.9
twig-language-2|mbl|0.9.1
theme-monokai-pro-vscode|mon|1.1.17
vscode-language-pack-zh-hans|MS-|1.47.3
powershell|ms-|2020.6.0
material-icon-theme|PKi|4.2.0
tsimporter|pmn|2.0.1
explorer-exclude-vscode-extension|Red|1.2.0
synthwave-vscode|Rob|0.1.6
vscode-icons|vsc|10.2.0
twig|wha|1.0.2
qf|Wsc|6.8.63

(7 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen after you run the command to reload with all extensions disabled?

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
