### ISSUE TITLE
sudo code ignoring --user-data-dir parameter?

### ISSUE THREAD

**Issue by mmattocks** [microsoft/vscode#103434]
- VSCode Version: 1.47.2
- OS Version: Linux Mint 20

Steps to Reproduce:

1. sudo code --user-data-dir="/home/main/.config/Code"
2. observe that code opens a window with the appropriate user theme before unloading in favour of the default, does not load extensions

No set of permissions on main is sufficent- I have tried recursively setting permissions to 777 from the user directory down. I never had this problem before, but after updating to Linux Mint 20 and reinstalling Code, it appeared. If anyone has a hint of where to start looking for an error message regarding the user directory, I would appreciate it!

Does this issue occur when all extensions are disabled?: Yes, still does not load the appropriate user theme

**Comment by aeschli** [comment]
@bpasero Why did you assign me?

**Comment by bpasero** [comment]
@aeschli 

> observe that code opens a window with the appropriate user theme before unloading in favour of the default

**Comment by bpasero** [comment]
@mmattocks can you maybe clarify what exactly your problem is, I assumed this is about the theme briefly showing as before and then switching to the default one?

**Comment by aeschli** [comment]
I assume you want to run as root but with the same user data dir as you normally do
I tried to reproduce with my setup on Ubuntu, but all seems to work. The user dir was picked up with the proper user settings and extensions.
`sudo code-insiders --user-data-dir /home/martin/.config/Code\ -\ Insiders/`

**Comment by mmattocks** [comment]
> I assume you want to run as root but with the same user data dir as you normally do
> I tried to reproduce with my setup on Ubuntu, but all seems to work. The user dir was picked up with the proper user settings and extensions.
> `sudo code-insiders --user-data-dir /home/martin/.config/Code\ -\ Insiders/`

Thank you for checking this out! Do you have any suggestions as to where I might look for errors or other output pertaining to the loading of the profile? The thing that's strange to me is that I do initially see my theme before it's unloaded for the default. A CSS styling plugin I use for contrast whilst coding outdoors (which is where I am most of the time) requires superuser access with the profile folder loaded, so I would like to figure out what's going on here. Thanks again for your time and attention!

**Comment by bpasero** [comment]
I am going ahead and close this, we generally do not encourage to use `sudo` when running VSCode at all. And if you must, best to use a different `user-data-dir`. You can enable settings sync to get all your user data synchronised between the two.
