### ISSUE TITLE
VScode unstable editing a very long CSS file

### ISSUE THREAD

**Issue by druellan** [Microsoft/vscode#10345]
- VSCode Version: 1.4.0 / 1.5.0-insiders
- OS Version: Windows 7 64bits / Windows 10 64bits

I'm editing a very long ~11.000 lines CSS file (attached), and VSCode is behaving surprising well, but I've found some problems:

[global.zip](https://github.com/Microsoft/vscode/files/409009/global.zip)

1- TAB insertion is very slow, every time I push TAB the editor halt for about 1 second.
2- Sometimes the editor becomes unresponsive, and a popup instructs me to close or restart
3- Sometimes seems that only Monaco halts. I can change tabs, etc, but I can't edit any file.

That usually happens when I'm editing near the end of the file. Extensions make things worse, but I can reproduce the problem without any extensions.

To reproduce: try to type fast and use TAB and ENTER as much as possible. CTRL+S from time to time. In my tests I can hang the editor just hitting TAB and ENTER like a maniac.

I'm really "ok" about some slowness giving the size of the file, but I believe that the editor should try not to hang and lose the user work.

![2016-08-09 10_24_58-program manager](https://cloud.githubusercontent.com/assets/6965667/17517866/c0e124a0-5e1b-11e6-8eda-aec9b9a18e68.png)

**Comment by jrieken** [comment]
The time is spend in emmet

<img width="889" alt="screen shot 2016-08-09 at 17 34 08" src="https://cloud.githubusercontent.com/assets/1794099/17522493/8a5ea7ae-5e57-11e6-9645-f0c4bf0192b8.png">


[CPU-20160809T173241.cpuprofile.zip](https://github.com/Microsoft/vscode/files/409276/CPU-20160809T173241.cpuprofile.zip)

**Comment by egamma** [comment]
@druellan you can disable emmet completions on tab using the setting `emmet.triggerExpansionOnTab`.

**Comment by druellan** [comment]
@egamma perfect. That seems to fix the problem for now.
I have the feeling that emmet should be disabled by default, it is more related to the user coding style than the actual code IMHO.

**Comment by egamma** [comment]
@druellan changing a default is always challenging since users are now getting used to have emmet available out of the box. 

Another option would be to add a setting to define the file size when emmet should be disabled and choose a decent default for this setting, e.g., 1000 lines.

**Comment by ramya-rao-a** [comment]
This is fixed with the work done as part of #43470

We now parse only a small section around the cursor, instead of parsing the complete file when expanding emmet abbreviations
