### ISSUE TITLE
Failing portion in webview web integration test

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#103419]
I commented it out for now via 88e641626546dceb53285aa0ddb44786324cb1bf

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=83065&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=087c9a82-9b9b-5b5f-17f2-a070cb4808e3

**Comment by alexdima** [comment]
@mjbvz I'm sorry I had to comment this out and partially revert your change via f485d7560550f95e761a329df2772efd954cd0fa because today's build failed again in this area https://dev.azure.com/monacotools/Monaco/_build/results?buildId=83112&view=logs&j=800c766b-cf7f-545c-6b0a-ae5b31f2fdcf&t=51b4207b-308f-5f00-05c4-35120a101a46&l=274

I have tried to troubleshoot the problem on Windows web integration tests, and here is what I saw as input and output to that function:
```
input: file:///c%3A/Alex/src/vscode/extensions/vscode-api-tests/testWorkspace/sub/image.png
output: vscode-remote://localhost:9888/vscode-resource?%7B%22requestResourcePath%22%3A%22%2Fc%253A%2FAlex%2Fsrc%2Fvscode%2Fextensions%2Fvscode-api-tests%2FtestWorkspace%2Fsub%2Fimage.png%22%7D
```

**Comment by mjbvz** [comment]
Closing this in favor of #113769
