### ISSUE TITLE
Error in debug extension mode in case if my extension depends on other which is not installed

### ISSUE THREAD

**Issue by greybax** [microsoft/vscode#103439]
- VSCode Version: 
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

- OS Version: Windows 10 Enterprise
![image](https://user-images.githubusercontent.com/3235047/88594702-86581980-d016-11ea-87da-59241a027502.png)

Steps to Reproduce:

1. develop extension `A` which is depends on extension `B`
2. Run extension `A` in debug mode
![image](https://user-images.githubusercontent.com/3235047/88594913-f49cdc00-d016-11ea-9338-14b6e0bf7e91.png)

Does this issue occur when all extensions are disabled?: Yes

_**Please note**_ that if I'll pack extension via `vsce package` command and will install it, this error will dissapear. So it can be reproduced only in case of VSCode extension debug mode

**Comment by weinand** [comment]
Is extension B installed in the VS Code you are using when debugging extension A?
If not, then you must make both extensions available for debugging.
For this just add another "extensionDevelopmentPath" argument:
```json
		{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--extensionDevelopmentPath=${workspaceFolder}/../extensionB"
			],
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}"
		},
```

**Comment by greybax** [comment]
I don't have access to "Debugger for Chrome" extension which is `extension B` in my case, so not sure what path I have to put into `--extensionDevelopmentPath` parameter

**Comment by weinand** [comment]
but you can install that extension from the marketplace, correct?

**Comment by greybax** [comment]
@weinand yes, it's installing with my `extension A` , but not sure what path exactly I have to use for this extension. I've found extensions under these folders:

* Windows %USERPROFILE%\.vscode\extensions
* Mac $HOME/.vscode/extensions
* Linux $HOME/.vscode/extensions

Should I use these paths for passing into `--extensionDevelopmentPath`?

**Comment by weinand** [comment]
You can just install the "Debugger for Chrome" in the VS Code that you use to debug your extension. There is no need to add it to the "--extensionDevelopmentPath".

**Comment by greybax** [comment]
I use "Debugger for Chrome" as part of my extension. I'm developing the extension which is allowed to debug applications creating using my extension via "Debugger for Chrome".
