### ISSUE TITLE
Reports error with project aliases

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#103425]
Issue Type: <b>Bug</b>

We have set up aliases in our tsconfig.base.json in our ngxs/nestjs Angular 10 project:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@spg/auth": ["libs/auth/src/index.ts"],
      "@spg/shared": ["libs/shared/src/index.ts"],
      "@spg/address": ["libs/address/src/index.ts"],
      "@spg/print": ["libs/print/src/index.ts"],
      "@spg/settings": ["libs/settings/src/index.ts"],
      "@spg/layout": ["libs/layout/src/index.ts"],
      "@spg/user": ["libs/user/src/index.ts"],
      "@spg/config": ["libs/config/src/index.ts"],
      "@spg/error": ["libs/error/src/index.ts"],
      "@spg/remote": ["libs/remote/src/index.ts"],
      "@spg/dashboard": ["libs/dashboard/src/index.ts"],
      "@spg/history": ["libs/history/src/index.ts"],
      "@spg/orders": ["libs/orders/src/index.ts"]
    }
  },
  "exclude": ["node_modules", "tmp"]
}
```
This way, we use imports like `import { HeaderComponent, FooterComponent } from '@spg/layout';`

The app compiles and runs fine, but VSCode always flags an error on these:

![CleanShot 2020-07-27 at 14 02 42](https://user-images.githubusercontent.com/835148/88575856-835b2a00-d012-11ea-9e60-f0d37f8fde9f.jpg)

I have reloaded Code, quit and relaunched to no avail

VS Code version: Code - Insiders 1.48.0-insider (731f9c25632dbbf01ee3a7892ad9d2791fe0260c, 2020-07-24T05:51:27.957Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id 2989f78b-23b4-466d-ae73-bbe6c5fe1c40|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|1.6.2
Bookmarks|ale|11.3.1
project-manager|ale|11.1.0
ng-template|Ang|0.1000.4
change-color-format|bbu|1.0.0
vscode-multi-line-tricks|big|0.0.3
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.12
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.1.3
todo-tree|Gru|0.0.178
rainbow-csv|mec|1.7.0
ecdc|mit|1.3.0
theme-monokai-pro-vscode|mon|1.1.17
js-debug-companion|ms-|1.0.2
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
angular-console|nrw|13.0.0
angular-component-extension|oni|0.0.14
vscode-versionlens|pfl|1.0.8
quicktype|qui|12.0.46
format-html-in-php|rif|1.6.2
code-settings-sync|Sha|3.4.3
rewrap|stk|1.13.0
ayu|tea|0.20.1
sort-lines|Tyr|1.9.0
vscode-icons|vsc|10.2.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.2.0

(4 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please provide a small example project that demonstrates this

**Comment by mjbvz** [comment]
Also, VS Code only uses files named `tsconfig.json` for IntelliSense project (not `tsconfig.base.json`). Make sure you TS files are part of the project by opening them and running `TypeScript: go to project configuraiton`

**Comment by smlombardi** [comment]
It says they are not imported.  The dev who set it up only imports the components, not the modules. Each library has a `tsconfig.json` file like this:
```
{
  "extends": "../../tsconfig.base.json",
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.lib.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

**Comment by mjbvz** [comment]
Can you share an example project?

**Comment by smlombardi** [comment]
It would appear this is an issue with NX workspaces, VSCode does not understand the tsconfig.json "extends" to get the data in the base file and ignores it.  I hope this is fixed, as all the Angular tooling is broken, including Angular Language Service.

What's odd is this was working at one point and then ceased working.

**Comment by mjbvz** [comment]
Sounds like https://github.com/microsoft/TypeScript/issues/39632. 

Closing this as upstream. Please follow up on TypeScript

**Comment by smlombardi** [comment]
I have  this problem as well, with multiple tsconfig.json files extening a root-level tsconfig.base.json and editors like VScode no longer providing intellisense or error checking.

I followed this advice: angular/vscode-ng-language-service#876 (comment)

And for now I've gotten it back.
