### ISSUE TITLE
command 'markdown.showPreview' not found

### ISSUE THREAD

**Issue by amoore877** [microsoft/vscode#103418]
Issue Type: <b>Bug</b>

shift+ctrl+V on a `.md` file yields error:
```
command 'markdown.showPreview' not found
```
I'd expect at most some error with the file itself, not with finding the built-in preview command.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
go-outliner|766|0.1.20
vscode-bazel|Baz|0.3.0
better-toml|bun|0.3.2
thrift|cdu|0.0.1
systemd-unit-file|coo|1.0.6
go|gol|0.15.2
puppet-vscode|jpo|0.24.2
cql|Law|0.8.7
vscode-docker|ms-|1.4.1
python|ms-|2020.7.96456
team|ms-|1.161.0
gradle-language|nac|0.2.3
vscode-buck|onq|0.1.5
proto|pet|0.0.2
ruby|reb|0.27.0
java|red|0.65.0
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.23.0
vscode-ruby|win|0.27.0
vscode-proto3|zxh|0.4.2

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
