### ISSUE TITLE
Switch keyword in switch expression has incorrect syntax highlighting

### ISSUE THREAD

**Issue by marlongerson** [microsoft/vscode#103423]
- VSCode Version: 1.47.2
- OS Version: Linux x64 5.4.0-42-generic snap

Steps to Reproduce:

1. Create switch expression
2. Notice that switch keyword is not syntax highlighted.

![image](https://camo.githubusercontent.com/3a35e04233435470971305a70abc30ebdd868fe4/68747470733a2f2f692e696d6775722e636f6d2f30445468455a6e2e706e67)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Can you please provide a copy pastable example?

**Comment by marlongerson** [comment]
```
public enum Foo
{
    Bar,
    Baz,
}

public class A
{
    public int B(Foo foo) =>
        foo switch
        {
            Foo.Bar => 0,
            Foo.Baz => 1,
        };
}

**Comment by alexr00** [comment]
Thanks. This is caused by the grammar we use for syntax highlighting. Moved to the repo that owns the grammar: https://github.com/dotnet/csharp-tmLanguage/issues/184
