### ISSUE TITLE
I can't copy the contents of the split editor

### ISSUE THREAD

**Issue by MyWorldG** [microsoft/vscode#103458]
I can't copy the contents in the split editor. For example, after clicking an extension, the introduction in the split editor on the right can be copied, sometimes it can't be copied, and most of the time it can't be copied

**Comment by MyWorldG** [comment]
![vscodebug](https://user-images.githubusercontent.com/53108767/88627619-25e0df00-d0df-11ea-9420-76464e2207b4.gif)
![vscodebug2](https://user-images.githubusercontent.com/53108767/88627639-2f6a4700-d0df-11ea-97ca-f34bba40cd4c.gif)

**Comment by MyWorldG** [comment]
Drag and drop it into the main editor to copy it normally. However, when it is split to the right, sometimes it can be copied, sometimes it can't be copied. Most of the time, it doesn't work

I'm sorry, this is the second time I've submitted this question. It's really annoying

**Comment by MyWorldG** [comment]
This is the version information

![vscodeinfo](https://user-images.githubusercontent.com/53108767/88628000-d0f19880-d0df-11ea-91c1-66f054510a2b.jpg)

**Comment by rebornix** [comment]
@MyWorldG can you try go to the menu -> edit -> copy and see if it works?

**Comment by rebornix** [comment]
@MyWorldG can you try go to the menu -> edit -> copy and see if it works?

**Comment by MyWorldG** [comment]
@rebornix Copy and paste are still not allowed

![vscodebug3](https://user-images.githubusercontent.com/53108767/88743648-c1259300-d177-11ea-883c-3ce80fd43021.gif)

**Comment by rebornix** [comment]
This is an known issue with the webview and it should already be fixed.
