### ISSUE TITLE
code going blank

### ISSUE THREAD

**Issue by Milo123459** [microsoft/vscode#103443]
- VSCode Version: latest
- OS Version: windows 10

I was coding and well my PC unexpectedly shut off, and now when I open my files, it looks like this: https://salvage.is-inside.me/xNhKtgOE.png is there a way I can revert this?

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by IllusionMH** [comment]
You can try to reopen file with different encodings.
https://code.visualstudio.com/docs/editor/codebasics#_file-encoding-support

**Comment by Milo123459** [comment]
thanks

**Comment by Milo123459** [comment]
which one would I choose? to make my code visible

**Comment by IllusionMH** [comment]
Try different to see if it helps. I can't guess it for you
