### ISSUE TITLE
Cannot install any extensions on 1.46.1

### ISSUE THREAD

**Issue by thescripter** [microsoft/vscode#103420]
Issue Type: <b>Bug</b>

Cannot install any extensions on the tar.gz version of VSCode on Linux. I've tried both, automatic and manual. Always get the Corrupt Zip File: End of Central Not Found or something to that extent. I was able to install on 1.46, but can't on 1.46.1. I have tried everything, including deleting user-prefs/.vscode and .config/Code. This bug seems to be recurring. I have seen posts from 2018 that have raised this bug.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 3.10.0-1062.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz (24 x 1998)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|125.67GB (95.92GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by sandy081** [comment]
Can you please try using a fresh user data dir? Start code from command line by passing a fresh user data dir like follows:

`code --user-data-dir <user data folder path>`

**Comment by thescripter** [comment]
Yes, I have tried that, and it's still the same result. Like I have said in my original post, I have also deleted my user directory and the config directory and re-ran code and I still can't install any extensions. I am using the non-installed (tar.gz) version of VS Code.

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by thescripter** [comment]
I am able to access that page and see a python logo. I must say that while attempting to install any extension from the marketplace on Code fails, I am unable to install any extension manually either.

Attached are the logs.

```
console.ts:137 [Extension Host] Git installation not found.
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
extensionsActions.ts:1907 Error: Corrupt ZIP: end of central directory record signature not found
(anonymous) @ extensionsActions.ts:1907
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
(anonymous) @ extensionsActions.ts:1906
Promise.then (async)
(anonymous) @ extensionsActions.ts:1901
Promise.then (async)
run @ extensionsActions.ts:1897
runAction @ extensionRecommendations.ts:62
run @ extensionRecommendations.ts:74
(anonymous) @ notifications.ts:703
run @ actions.ts:161
runAction @ actions.ts:198
runAction @ notificationsActions.ts:160
run @ actions.ts:190
(anonymous) @ notificationsViewer.ts:448
fire @ event.ts:587
(anonymous) @ button.ts:90
notificationsAlerts.ts:40 Failed to install 'ms-python.python'.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
prompt @ notificationService.ts:171
(anonymous) @ extensionsActions.ts:87
invokeFunction @ instantiationService.ts:61
re @ extensionsActions.ts:77
(anonymous) @ extensionsActions.ts:1908
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
(anonymous) @ extensionsActions.ts:1906
Promise.then (async)
(anonymous) @ extensionsActions.ts:1901
Promise.then (async)
run @ extensionsActions.ts:1897
runAction @ extensionRecommendations.ts:62
run @ extensionRecommendations.ts:74
(anonymous) @ notifications.ts:703
run @ actions.ts:161
runAction @ actions.ts:198
runAction @ notificationsActions.ts:160
run @ actions.ts:190
(anonymous) @ notificationsViewer.ts:448
fire @ event.ts:587
(anonymous) @ button.ts:90
log.ts:197   ERR Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at file:///u/thescripter/VSCode-linux-x64/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:561:607
```

**Comment by sandy081** [comment]
Can you please share logs from all of the following locations

Help -> Toggle Developer Tools -> Console
View -> Command Pallette... -> Toggle Shared Process -> Console
View -> Open View… -> Log (Shared)
View -> Open View… -> Log (Window)

**Comment by thescripter** [comment]
All of the logs are the same and that's why I didn't include them. In case you want to ask me to install manually, I would like to repeat that I get the same error when attempting a manual install.

FWIW, here are all the logs,

**Help -> Toggle Developer Tools -> Console**
/u/thescripter/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:266 [Extension Host] Git installation not found.
t.log @ /u/thescripter/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:266
viewLine.ts:418 monospace assumptions have been violated, therefore disabling monospace optimizations!
monospaceAssumptionsAreValid @ viewLine.ts:418
monospaceAssumptionsAreValid @ viewLine.ts:321
_checkMonospaceFontAssumptions @ viewLines.ts:543
(anonymous) @ viewLines.ts:147
doRun @ async.ts:651
onTimeout @ async.ts:645
setTimeout (async)
schedule @ async.ts:632
renderText @ viewLines.ts:609
_actualRender @ viewImpl.ts:386
(anonymous) @ viewImpl.ts:344
(anonymous) @ viewImpl.ts:534
_renderNow @ viewImpl.ts:344
_flushAccumulatedAndRenderNow @ viewImpl.ts:221
_onRenderScheduled @ viewImpl.ts:340
execute @ dom.ts:272
s @ dom.ts:312
requestAnimationFrame (async)
(anonymous) @ dom.ts:232
t.scheduleAtNextAnimationFrame @ dom.ts:323
t.runAtThisOrScheduleAtNextAnimationFrame @ dom.ts:335
_scheduleRender @ viewImpl.ts:334
layoutContentWidget @ viewImpl.ts:501
addContentWidget @ viewImpl.ts:487
_attachModel @ codeEditorWidget.ts:1534
setModel @ codeEditorWidget.ts:426
setInput @ textResourceEditor.ts:79
async function (async)
setInput @ textResourceEditor.ts:63
setInput @ outputView.ts:241
setInput @ outputView.ts:149
showChannel @ outputView.ts:76
showChannel @ outputServices.ts:115
async function (async)
showChannel @ outputServices.ts:113
accept @ viewQuickAccess.ts:168
(anonymous) @ pickerQuickAccess.ts:263
fire @ event.ts:587
(anonymous) @ quickInput.ts:770
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
(anonymous) @ event.ts:56
(anonymous) @ event.ts:810
fire @ event.ts:587
_set @ listWidget.ts:167
set @ listWidget.ts:154
setSelection @ listWidget.ts:1400
onViewPointer @ listWidget.ts:641
(anonymous) @ event.ts:91
fire @ event.ts:587
(anonymous) @ event.ts:56
fire @ event.ts:587
o @ event.ts:16
extensionsActions.ts:1907 Error: Corrupt ZIP: end of central directory record signature not found
(anonymous) @ extensionsActions.ts:1907
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
(anonymous) @ extensionsActions.ts:1906
Promise.then (async)
(anonymous) @ extensionsActions.ts:1901
Promise.then (async)
run @ extensionsActions.ts:1897
runAction @ extensionRecommendations.ts:62
run @ extensionRecommendations.ts:74
(anonymous) @ notifications.ts:703
run @ actions.ts:161
runAction @ actions.ts:198
runAction @ notificationsActions.ts:160
run @ actions.ts:190
(anonymous) @ notificationsViewer.ts:448
fire @ event.ts:587
(anonymous) @ button.ts:90
notificationsAlerts.ts:40 Failed to install 'ms-python.python'.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:587
addNotification @ notifications.ts:207
notify @ notificationService.ts:106
prompt @ notificationService.ts:171
(anonymous) @ extensionsActions.ts:87
invokeFunction @ instantiationService.ts:61
re @ extensionsActions.ts:77
(anonymous) @ extensionsActions.ts:1908
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
(anonymous) @ extensionsActions.ts:1906
Promise.then (async)
(anonymous) @ extensionsActions.ts:1901
Promise.then (async)
run @ extensionsActions.ts:1897
runAction @ extensionRecommendations.ts:62
run @ extensionRecommendations.ts:74
(anonymous) @ notifications.ts:703
run @ actions.ts:161
runAction @ actions.ts:198
runAction @ notificationsActions.ts:160
run @ actions.ts:190
(anonymous) @ notificationsViewer.ts:448
fire @ event.ts:587
(anonymous) @ button.ts:90
log.ts:197   ERR Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at file:///u/thescripter/VSCode-linux-x64/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:561:607

**View -> Command Pallette... -> Toggle Shared Process -> Console**
EMPTY

**View -> Open View… -> Log (Shared)**
[2020-07-30 12:06:08.382] [sharedprocess] [info] main {"machineId":"0d16610c078ee42b91cfc8f91c289a9a1f6048d013bf8ee415eb8121f84bc2d3","windowId":2}
[2020-07-30 12:06:48.397] [sharedprocess] [info] Starting to clean up unused language packs.
[2020-07-30 12:07:36.923] [sharedprocess] [info] Installing extension: ms-python.python
[2020-07-30 12:07:36.938] [sharedprocess] [info] Downloaded extension: ms-python.python /u/thescripter/.config/Code/CachedExtensionVSIXs/ms-python.python-2020.7.96456
[2020-07-30 12:07:36.954] [sharedprocess] [error] Failed to install extension: ms-python.python Corrupt ZIP: end of central directory record signature not found

**View -> Open View… -> Log (Window)**
[2020-07-30 12:07:36.983] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at file:///u/thescripter/VSCode-linux-x64/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:561:607

**Comment by sandy081** [comment]
Can you please try installing other extensions (also try themes extensions) and let us know if you are getting the same error?

**Comment by thescripter** [comment]
Hi! I get the same error for most of the language-based extensions, but I am able to install theme extensions. I mainly want to install Python and C/C++ extensions and they both fail with the same error. I was able to install C#, but no other language-based.

**Comment by sandy081** [comment]
Are you able to download the VSIX from marketplace and install it ? If you are getting the same error can you please share the VSIX?

**Comment by thescripter** [comment]
In my very first message, I have mentioned that I cannot install them manually either, and I get the same error.
I'm unable to attach the files. Github just keeps saying "Something went really wrong, and we can't process that file. Try again.", no matter how many times I try.

Here are the links to the files,
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/cpptools/0.29.0/vspackage
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2020.7.96456/vspackage

**Comment by sandy081** [comment]
You have to change the VSIX file extension from `.vsix` to `.zip` and you can attach it. 

Reason I am asking the VSIX you downloaded because I am not seeing this issue and this could be some caching issue somewhere. So checking the VSIX you downloaded might confirm it.

**Comment by thescripter** [comment]
I tried attaching the extensions after having renamed them to .zip, and I still get the same error. It's probably some caching issue or they're not getting downloaded correctly. But I'm not sure why these in particular would error out, so would like to get to the bottom of it.

**Comment by sandy081** [comment]
I am sorry why it is not working (attaching). If it is ok you can also email the VSIX to me - sasomava@microsoft.com ?
