### ISSUE TITLE
The order of Git Menu items

### ISSUE THREAD

**Issue by RezaRahmati** [microsoft/vscode#103499]
Issue Type: <b>Bug</b>

Hi there
The location of "Drop stash" in the menu is not good, especially it looks like "Pop stash" and easily you migth click on the wrong menu, and there is no confirmation, 
By mistake I droped a big stash, although I recovered it!

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.5.0

**Comment by joaomoreno** [comment]
Git menus are about to get cleaned up this week, according to the plan. Closing as duplicate.

**Comment by RezaRahmati** [comment]
@joaomoreno My vscode is updated for Git Menu, but my concern is still not resolved, `Drop` and `Pop` look like the same, and since there is no confirm dialog for `Drop stash` you can easily make mistake

![image](https://user-images.githubusercontent.com/10086092/90335328-3f6c9c80-dfa2-11ea-8694-f8c7c99f3df2.png)
