### ISSUE TITLE
Snippet don't save ${}

### ISSUE THREAD

**Issue by amitco2468** [microsoft/vscode#103469]
- VSCode Version: 1.47.3
- OS Version: Windows 10

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

When I use snippet it's don't saving the ${} variables,

pls check it.

(sry for my english)

Amit

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
