### ISSUE TITLE
Title bar corners glitches on Big Sur

### ISSUE THREAD

**Issue by VincentDondain** [microsoft/vscode#103427]
Version: 1.48.0-insider
Commit: 731f9c25632dbbf01ee3a7892ad9d2791fe0260c
Date: 2020-07-24T05:51:27.957Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.0.0

macOS Big Sur beta 3

Steps to Reproduce:

<img width="1054" alt="Screenshot 2020-07-27 14 43 02" src="https://user-images.githubusercontent.com/7839202/88579247-bfdd5480-d017-11ea-9716-a944770fcc57.png">

1. Simply launch VSCode insiders on macOS Big Sur

_Note: This seems to only happen with VSCode insiders_

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by deepak1556** [comment]
This is an electron issue https://github.com/electron/electron/issues/24319#issuecomment-661986360 marked to be fixed by  https://github.com/electron/electron/pull/24642 , it hasn't been released yet. Will update once the version with fix is available.

**Comment by deepak1556** [comment]
Should be fixed in latest insiders, please check. Thanks!

**Comment by VincentDondain** [comment]
Hi, this also appears to be fixed in stable VSCode:

```
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 20.0.0
```

Confirmed fixed!
