### ISSUE TITLE
List View viewzone API

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#103437]
While building side by side diff view for notebook (https://github.com/microsoft/vscode/issues/94810), I ran into another challenge with dynamic cell heights.

At the beginning, List View supports dynamic items at creation/rendering time but it doesn't support item height change once it's rendered. Then we introduced `updateElementHeight` API to allow notebook cells grow its height (when there are outputs). Rendering notebooks side by side has more requirements: if a cell is modified/changed (for example, outputs are different), its scroll top in two editors should be the same, and its accumulated total height should be the same as well.

To solve this problem, we can either leverage `updateElementHeight` to update cell heights based on diff information (then `cellHeight = inputHeight + outputsHeight + additionalHeight`), or introduce a view zone API which is identical to Monaco's view zone. The API would allow you to preserve a whitespace area after an index:

```ts
interface IViewZone {
  afterIndex: number;
  heightInPx: number;
}

addZone(zone: IViewZone): string;
removeZone(id: string): void;
layoutZone(id: string): void;
```

The diff component can then use this API to adjust the scroll tops of cells without messing up with the layout info of cells. Diff information would be transparent to `NotebookEditor` or `ListView`.

**Comment by rebornix** [comment]
@roblourens is working on moving the height calculation logic into the List View other than doing all the math in notebook renderer. Maybe this can also be done by `addViewZone` and then update the height of the viewzone when DOM changes.

**Comment by joaomoreno** [comment]
@rebornix Are we still planning on doing this?

**Comment by rebornix** [comment]
@joaomoreno we probably don't need this anymore for now.
