### ISSUE TITLE
Visual Studio Code uninstalled itself

### ISSUE THREAD

**Issue by s0er3n** [microsoft/vscode#103484]
- VSCode Version: I dont know
- OS Version: Windows 10

After rebooting my pc Visual Studio Code wasnt installed anymore. After reinstalling all my settings and extensions are still there.

**Comment by casedup** [comment]
samething just happened to me... everything was fine taking care of some homework now i cant even use it

**Comment by joaomoreno** [comment]
> After rebooting my pc Visual Studio Code wasnt installed anymore. After reinstalling all my settings and extensions are still there.

Glad to know you're back to coding!
