### ISSUE TITLE
 Symbol recognition error from Python3.6.8

### ISSUE THREAD

**Issue by majikayo00** [microsoft/vscode#103449]
Issue Type: <b>Bug</b>

Hello. We will send it by machine translation. I updated from ver1.46.1 to 1.47.3, but the symbol is no longer displayed in the outline. Even if the mouse is on the function, no help is given, which affects the work. If you reinstall it, it will be a very old version, but it will cure. Hope it will be improved.

P.S. Outline doesn't change even if VScode is closed and auto-uploaded, but when I click "refresh" I get this issue. Similar effects were seen on other PCs.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (27.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ja|MS-|1.47.3
python|ms-|2020.7.96456
cython|tcw|0.1.0

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
