### ISSUE TITLE
getDebugAdapterTrackers code breaks debugger when debugging development extensions

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#103477]
Whenever I debug my extension code from source and then start a debug session, the debugger (in the VS Code that's hosting my source code) breaks on a timeout:

<img width="1688" alt="Screenshot 2020-07-28 at 11 30 51" src="https://user-images.githubusercontent.com/1078012/88654947-f5d91200-d0c5-11ea-9b31-b38ae4a8a89d.png">

I only have the debug settings to break on "Uncaught exceptions", but it still breaks here. I believe the source is this code here:

https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/workbench/api/common/extHostDebugService.ts#L800-L817

I'm not sure why the code is timing out (or exactly what it's doing), but it's quite annoying to have to click resume in the debugger back in the "other" VS Code when trying to test things in my extension host.

(I can't repro this in MockDebug, but I don't know why - I'm not familiar with what this code is trying to do).

**Comment by foxsofter** [comment]
I had the same problem, and when I packaged into VSIX the extension didn't work.
