### ISSUE TITLE
Unsupported title and extensions not working

### ISSUE THREAD

**Issue by Ravi16209990** [microsoft/vscode#103479]
Issue Type: <b>Feature Request</b>

Error showing :- Your code installation appears to be corrupt. Please install.
I even reinstalled after that. But the problem remains same.  

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
Do you have an antivirus product on your PC? If so, which one?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
