### ISSUE TITLE
terminal.integrated.env.windows does not work from .code-workspace

### ISSUE THREAD

**Issue by pwm1234** [microsoft/vscode#103415]
When I put 

    "terminal.integrated.env.windows": {
		"foo": "bar2"
	}

in my user settings.json file it works. But when I put it in my project.code-workspace file it does not.

(Note I tried submitting this issue from withing vscode using Help->Report Issue, but I got an error about the content being too large.)

Help->About:
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by Tyriar** [comment]
Does it work when you allow workspace shell permissions using this command? 
![image](https://user-images.githubusercontent.com/2193314/89207418-894f8e80-d56f-11ea-85d7-cb7dbb7e59a5.png)

**Comment by pwm1234** [comment]
Yes, it works after I allow workspace shell permissions. Is this a permanent setting or will I need to allow this every time I open the workspace?

**Comment by Tyriar** [comment]
It's meant to be remembered but there is a but specifically for multi-root workspaces: https://github.com/microsoft/vscode/issues/80674

/duplicate

**Comment by pwm1234** [comment]
Thank you!
