### ISSUE TITLE
Does vscode support the ES6 module intelligent tips by d.ts file so far?

### ISSUE THREAD

**Issue by cike8899** [Microsoft/vscode#10351]
- VSCode Version: 1.4
- OS Version: win10

Steps to Reproduce:

After my test, in the case of the installation of the typings file, I found that vscode only supports intelligent commonjs way, but does not support the ES6 module loaded intelligent tips, is there  any way to solve it?

**Comment by waderyan** [comment]
Hello @cike8899 thank you for opening an issue. 

I'm not sure I completely understand. Can you please clarify a few things about your issue? 

I'm confused by "only supports intelligent commonjs way" and "does not support the ES6 modules loaded intelligent tips." 

* What is "intelligent commonjs way"?
* What is "ES6 modules loaded intelligent tips"? 

Some relevant documentation that may or may not solve your issue. 

As described in the [IntelliSense](https://code.visualstudio.com/docs/languages/javascript#_intellisense) section of the JavaScript doc (copied here for ease of reference). 

> JavaScript uses the same inference as TypeScript to determine the type of a value.

> The following patterns are also recognized:

> "ES3-style" classes, specified using a constructor function and assignments to the prototype property.
> CommonJS-style module patterns, specified as property assignments on the exports object, or assignments to the module.exports property.

> The AMD (Asynchronous Module Definition) module pattern is currently not supported.

In your JavaScript project file `jsconfig.json` you can specify different module code generation, as described in this [section](https://code.visualstudio.com/docs/languages/javascript#_compiling-javascript-downlevel) (copied here for ease of reference). 

> Specify module code generation. The values are "commonjs", "system", "umd", "amd", "es6", "es2015"

**Comment by cike8899** [comment]
When I  import third part library as ES6 module,as below :import * as React from "react"; then I type React. Nothing will show in vscode, I mean there is no any tips from vscode even though I create a jsconfig.json file in the root directory  of  my project.But I import the same library with commonjs module,"var React = require('react')",then I type React.   some tips will show.

**Comment by waderyan** [comment]
To make sure I understand.

You have written. 

```
import * as React from 'react'
```

When you type `React.` you get no intelliSense?

However, if you do the following

```
var React = require('react')
```

Then type `React.` you receive IntelliSense?

If that is correct can you send me the contents of your jsconfig.json file?

**Comment by cike8899** [comment]
That is correct,I set jsconfig.json as following:
{
	// See https://go.microsoft.com/fwlink/?LinkId=759670
	// for the documentation about the jsconfig.json format
	"compilerOptions": {
		"target": "es6",
		"module": "commonjs",
		"allowSyntheticDefaultImports": true
	},
	"exclude": [
		"node_modules",
		"bower_components",
		"jspm_packages",
		"tmp",
		"temp"
	]
}

**Comment by waderyan** [comment]
Ok I setup your same project. Unfortunately, I am not seeing your issue. 

![image](https://cloud.githubusercontent.com/assets/2449568/17778344/912e89ce-6518-11e6-947d-cd63ee78d9f1.png)

Couple additional things to try. 

1. Run VS Code with extensions disabled. 

```
code --disable-extensions .
```

2. Remove all your settings (you can save them to a temporary location) and add this setting.

```
{
  "typescript.tsserver.trace": "verbose"
}
```

3. Open the developer tools console (Help -> Toggle Developer Tools) and send me a picture of what you see in the console.

**Comment by waderyan** [comment]
Closing until more info is provided.
