### ISSUE TITLE
syntaxes: end pattern invalidating start pattern

### ISSUE THREAD

**Issue by bobmagicii** [Microsoft/vscode#10356]
is it possible that you can make the end pattern invalidate the start pattern in the syntax files?

for example i am trying to add support to php for php 7 and to be more flexible in the formatting:

```php
public function
Whatever():
Bool { }
```

because of what appears to be limitations of the syntax engine i cannot quite get this fully pulled off though. the problem seems to be that i cannot tell the difference between a call and a define unless the function name is on the same line as function. it seems to be completely unable to check the line before the current line using any of the regex tricks i can devise.

this lead me to attempting to invalidate the start pattern by using the end pattern. e.g., if end pattern ends with : or { then its a define, else its a call. the problem is that the end pattern does not invalidate the start pattern. so the start pattern will begin highlighting, and if the end pattern is invalid it will break the rest of the file.

this could be done via an additional option to the json for that pattern as to not break all your syntax files, assuming it is possible at all.

**Comment by bobmagicii** [comment]
i have already gotten very close, though it has the current issue of all calls() are treated as definitions now. https://github.com/Microsoft/vscode/compare/master...bobmagicii:master

![cpxugyvuiaavadi](https://cloud.githubusercontent.com/assets/881944/17527401/d3b10c2a-5e30-11e6-8a6f-14e28a1b854e.jpg)

**Comment by jrieken** [comment]
Maybe our text mate wizards @alexandrudima and @aeschli know?

**Comment by aeschli** [comment]
The TextMate grammar engine lets you only look one line a time. You can push a new scope based on what you see, but can't modify that scope later when looking at succeeding lines.
See https://manual.macromates.com/en/language_grammars, 12.2 Language Rules, last paragraph for the reason for that.
