### ISSUE TITLE
git branch not updating when using Remote WSL

### ISSUE THREAD

**Issue by saiyen2002** [microsoft/vscode#103597]
- VSCode Version: 1.4.7.3
- OS Version: Version 20h2 (OS Built 19042.421)

Git branch does not change when browsing between different projects in the explorer when using the Remote WSL.

Steps to Reproduce:

1. open connection to with remote WSL. I am using ubuntu 20.04
2. Open folder/workspace containing mulitple git projects that reside inside of WSL folders. In my case I go via symlink that points to my windows directory   /home/arahman/work --> /mnt/c/Users/athiq/Woskapces/work
3. move between the projects, the branch in bottom left highlighted in blue does not change. only sticks to the first branch in the first folder browsed to
4. This problem does not occur when not using WSL

Does this issue occur when all extensions are disabled?: Yes, Kind of. I cannot disable the Remote WSL extension. All other extensions are disabled

**Comment by joaomoreno** [comment]
You should use Remote WSL to edit files inside WSL. If you want to edit files on the Window side, please just use the regular VS Code.
