### ISSUE TITLE
Action item to toggle showing excluded files

### ISSUE THREAD

**Issue by loligans** [microsoft/vscode#103536]
It would be very helpful to be able to view excluded (hidden) files from time to time.

![image](https://user-images.githubusercontent.com/3218210/88761008-1c796600-d123-11ea-8918-71c56e84c8ec.png)

**Comment by IllusionMH** [comment]
In meantime you can use https://marketplace.visualstudio.com/items?itemName=eamodio.toggle-excluded-files 

/cc @eamodio if he knows any anything about building it into editor

**Comment by eamodio** [comment]
As mentioned the [Toggle Excluded Files](https://marketplace.visualstudio.com/items?itemName=eamodio.toggle-excluded-files) extension covers this functionality. And if https://github.com/microsoft/vscode/issues/108271 gets added, then I could improve the extension's UX even more.
