### ISSUE TITLE
Add ability to set default custom terminal title.

### ISSUE THREAD

**Issue by prbsparx** [microsoft/vscode#103589]
Please provide a way to custom the default integrated terminal title so that when you create a new integrated terminal it can automatically have a set value.

For me, my goal is to be able to have the process name that is running (example: zsh), then a pipe, then the folder I'm in. i.e. "zsh | docker" or "zsh | kubernetes"

This is especially helpful when bouncing between 4 sub-folders.

An already designed field that can be used as a basis is the "Window:Title" field.

**Comment by Tyriar** [comment]
Try using `"terminal.integrated.experimentalUseTitleEvent": true`, this will allow the process to set the title.

**Comment by prbsparx** [comment]
Setting `"terminal.integrated.experimentalUseTitleEvent": true` does appear to allow this.
You also have to add `echo -en "\e]2;$(basename $SHELL) | $(basename $(pwd))\a"`  to ~/.zshrc
