### ISSUE TITLE
VS Code doesn't give code snippets and doesn't run any console when not elevated

### ISSUE THREAD

**Issue by quadzz** [microsoft/vscode#103562]
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Run VS Code with EPM software on

Does this issue occur when all extensions are disabled?: Doesn't matter, but yes.

When launching VS Code without elevated privileges - I cannot start any console and I do not get code snippets of any sort.
Extensions work like a charm.

Same situation occured when working with Windows Terminal - cannot run any console.

It is connected with EPM software (CyberArk to be exact) as it blocks anything that runs with elevated privileges from non-elevated session. 
When VS Code is running as admin - everything goes back to normal.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
