### ISSUE TITLE
Renaming import changes the import name

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#103598]
- Press F2 on some name which is imported from another TS file
- It doesn't rename the thing globally but renames the import with `as`

Is this new or has it been like this for a long time? I was hitting it and it makes mass refactoring sort of inconvenient as I have to stop and check where the thing is defined before renaming it. I would see "rename import" as a separate action than "rename"

**Comment by IllusionMH** [comment]
@roblourens I think that this behavior is there for about a year.
However you can try `"typescript.preferences.useAliasesForRenames": false` which should switch from aliases to global renames.
It's description mentions only object shorthand properties but should work with named imports as well.

Unfortunately #93501 didn't enough votes 😢

**Comment by roblourens** [comment]
Oh, that's perfect thanks
