### ISSUE TITLE
Support internal links to other cells

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#103519]
Jupyter supports links to other cells in the same notebook using markdown syntax

```
[click to go to header](#header)
```

navigates to another cell

```
# header
```

We will have to search all cells for a matching header

**Comment by tanhakabir** [comment]
Lot's of online lessons use internal linking like: Answer to Exercise 1a in [Exploratory Computing with Python](https://nbviewer.jupyter.org/github/mbakker7/exploratory_computing_with_python/blob/master/notebook1_basics_plotting/py_exploratory_comp_1_sol.ipynb#ex1a)

**Comment by IanMatthewHuff** [comment]
Looked good to me with both the markdown header syntax and with the <a id="section_ID"></a> syntax. Validated.
