### ISSUE TITLE
Typescript intellicode wrongly puts an extra question mark after an optional interface property

### ISSUE THREAD

**Issue by planetoryd** [microsoft/vscode#103573]
- VSCode Version: 15e798e081984a17eae00de91adf4479190d5ed2
- OS Version: kubuntu 20.04

Steps to Reproduce:

1. Write an interface with an optional property
2. Use intellicode
![Peek 2020-07-30 00-58](https://user-images.githubusercontent.com/68096727/88830609-baba0a00-d1bd-11ea-88aa-69fd6ac18387.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is the designed behavior since `prop` is nullable, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

Set `"typescript.suggest.includeAutomaticOptionalChainCompletions": false` to disable this (although your code may then crash at runtime)
