### ISSUE TITLE
disable jupyter editor in vscode

### ISSUE THREAD

**Issue by ericsoul1987** [microsoft/vscode#103526]
like the title mentioned, how to disable jupyter editor in vscode? 
the user case is followed:
every time,I want to new a file just for text or markdown,I do not like to appear a choice between two, but just default for the inner editor applied by vscode. and how can I configure this. for right now,I never need to use jupyter notebook. It seems to be appeared unexpected after vscode update or installed some python package.

I have asked on stackoverflow, but get no answer.It seems to be a new feature for ux.
https://stackoverflow.com/questions/63048691/how-to-disable-jupyter-editor-in-vscode?noredirect=1#comment111642887_63048691

**Comment by rebornix** [comment]
This can be disabled by `python.dataScience.useNotebookEditor` if you are using the Python extension.
