### ISSUE TITLE
Cannot Open... Projects (Mac, Catalina 10.15.5)

### ISSUE THREAD

**Issue by relnetops** [microsoft/vscode#103568]
Issue Type: <b>Bug</b>

Using either the File menu, or the keyboard shortcut "Open..." does nothing.  Also, clicking the "Open folder..." link in the Welcome page does nothing.

"Open Recent -> {foo}" and "Open Recent -> More..." work fine.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|-psn_0_61848312|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.36.2
gitlens|eam|10.2.2
gitlab-workflow|Git|3.1.0
vscode-yaml|red|0.9.1
shellcheck|tim|0.9.0
markdown-all-in-one|yzh|3.2.0

</details>

**Comment by relnetops** [comment]
Please note: I'm currently working around this by using the cli:
```sh
code .
```

**Comment by ShivanshRakesh** [comment]
Strange, but I'm not facing this issue. I'm using VSCode 1.47.3 too, but on MacOS 10.15.6 (Catalina, version: Darwin 19.6). Though it worked fine on MacOS 10.15.5 too. As expected, the Open (or `cmd+O`) command fires up a Finder window.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by relnetops** [comment]
```
% code --verbose 
[main 2020-08-12T13:46:57.335Z] Sending env to running instance...
[main 2020-08-12T13:46:57.339Z] Sent env to running instance. Terminating...
[main 2020-08-12T13:46:57.339Z] Lifecycle#kill()
```

With Dev Tools | Console open, I've clicked the "Open folder..." link in the Welcome page and selected "Open..." from the file menu (also tried the keyboard shortcut).  There is no output in the Dev Tools Console.

Also, If I open a new file, I'm not able to save it.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by deepak1556** [comment]
Seems like a corrupted state, possible duplicate of https://github.com/microsoft/vscode/issues/102975, can you also do a system restart and  see if the issue continues to happen ?

**Comment by relnetops** [comment]
Thanks.  I've updated to 10.15.6, which included a restart.  The issues seem to be resolved.  I agree that it was probably a corrupt state.  Thanks!
