### ISSUE TITLE
onLanguage:sass does not work

### ISSUE THREAD

**Issue by jakopo87** [microsoft/vscode#103547]
Issue Type: <b>Bug</b>

In the `package.json` of my extension I added:
    ...
    "activationEvents": [
        "onLanguage:sass",
        "onLanguage:scss"
    ],
    ...
Both language identifiers are listed in the [docs](https://code.visualstudio.com/docs/languages/identifiers) for SCSS, however my extension is activated when a `.scss` file is opened.
Is `sass` still a valid language identifier or the docs are outdated ?

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/7312#issuecomment-227064046 looks relevant

**Comment by jakopo87** [comment]
I did read that, but `onLanguage:scss` does nothing when I open a `sass` file, as soon as I open any `scss` file it activates the extension, plus vscode treats the file as plain text, changing it to scss makes it complain about the syntax.
As a workaround i'm using `workspaceContains:**/*.s[ac]ss` and works fine.

**Comment by gjsjohnmurray** [comment]
Perhaps you need to install an extension that implements that Language ID and uses it for .sass files. According to the Feature Contributions manifest syler.sass-indented does this, but I have no personal experience of it.

**Comment by aeschli** [comment]
Yes, there needs to be an extension that contributes the `sass` language id, including the file extension associations. You can also define that in your extension, as multiple declarations for the same language will be merged.
See https://code.visualstudio.com/api/references/contribution-points#contributes.languages
