### ISSUE TITLE
"Menu" button works incorrectly when focus on an item in Folder View

### ISSUE THREAD

**Issue by NikiforovAll** [microsoft/vscode#103500]
- VSCode Version: 1.47.3 
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open folder in vscode
2. Focus on Folders View
3. Press menu key to simulate _Right Mouse Click_ on some folder.

Demo: 
As you can see, the focus is on `XMindAPI` folder, but the wrong item is selected. It is not even a folder in this case.

![vscode-menu-bug-in-folders-view](https://user-images.githubusercontent.com/8037439/88689633-65212700-d103-11ea-82e2-00fbc8758514.gif)

Notes: This does not happen if you press some control keys. E.g. _LAlt_ + _Menu_

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by isidorn** [comment]
There is already an issue for this 100% I am just not sure which one exactly it is. Maybe search for issue tagged with file-explorer

**Comment by NikiforovAll** [comment]
Ref: #100151
