### ISSUE TITLE
VS Code keeps recommending extensions I already have

### ISSUE THREAD

**Issue by qidydl** [microsoft/vscode#103575]
Issue Type: <b>Bug</b>

VS Code keeps recommending I install the C# extension, even though I already have it installed. I tried removing and reinstalling the extension and that did not help. I can reproduce by opening a folder and then opening a .csproj file to edit.

![image](https://user-images.githubusercontent.com/5160192/88836995-994d2400-d1a5-11ea-8482-a8497c90320c.png)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (20.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
cform|aws|0.0.24
vscode-eslint|dba|2.1.1
githistory|don|0.6.8
xml|Dot|2.5.1
EditorConfig|Edi|0.14.4
vscode-cfn-lint|kdd|0.14.0
vscode-docker|ms-|1.1.0
csharp|ms-|1.21.18
mssql|ms-|1.9.0
azure-account|ms-|0.8.11
powershell|ms-|2020.4.0
team|ms-|1.161.0
vscode-yaml|red|0.9.1
code-spell-checker|str|1.8.0
vscode-icons|vsc|10.2.0

</details>

**Comment by sandy081** [comment]
I cannot repro it. 

It seems you are on old version of VS Code (`1.42.1`). Can you please update to latest and try it out?
