### ISSUE TITLE
Cannot close pane with cmd+w when tabs are disabled.

### ISSUE THREAD

**Issue by cleversprocket** [Microsoft/vscode#10357]
- VSCode Version: 1.4.0 
- OS Version: OSX 10.10.5

Steps to Reproduce:

1. Disable Tabs by setting the rule `"workbench.editor.showTabs": false` in User settings settings.json
2. Select a file to edit with cmd+p.
3. Repeat step 2 with several different files.
4. Open a new editor pane with cmd+2.
5. Use step 2 in the new pane to open a file for editing.
6. Repeat step 3 in the new pane.
7. Attempt to close the new pane with cmd+w.

Expected Results:
The pane closes using cmd+w.

Actual Results:
cmd+w just closes the the file but the pane (or possibly the editor group?) remains open.

Notes:
This behavior started happening after Tabs was introduced. I've tried `workbench.action.closeAllEditors` and `workbench.action.closeEditorsInGroup` and the pane still will not close.

**Comment by bpasero** [comment]
See https://github.com/Microsoft/vscode/issues/6605

**Comment by cleversprocket** [comment]
@bpasero I mentioned in the Notes section of the bug that using `workbench.action.closeEditorsInGroup` does not work.

**Comment by bpasero** [comment]
@cleversprocket can you demo this in a video? or screenshots?
