### ISSUE TITLE
[Editor][Request] Insert {Tab} key

### ISSUE THREAD

**Issue by quangkieu** [microsoft/vscode#103590]
I tried to search 2-4 page for this issued but could not spot one so here is my request
I would like insert {tab} key in the text when I am in Space Indent mode.
I could suggest shortcut like Ctrl+Alt+T, Ctrl+Alt+T to trigger this. 
Or better, vscode could detect if current cursor is not at start of line then just intercepts tab key as is instead of translate to spaces

**Comment by alexdima** [comment]
This is possible via keybindings. e.g.:
```
{ "key": "cmd+t", "command": "type", "args": { "text": "\t" }, "when": "editorTextFocus" },
```
