### ISSUE TITLE
Debugger freeze 

### ISSUE THREAD

**Issue by wolfgangWS** [microsoft/vscode#103545]
Issue Type: <b>Bug</b>

I use VSC under Win10 to write Javascript modules for node.js (windows installation). 

Debugging with bulit-in node-debug worked very well until two months ago. Since then - with new VSC updates - breakpoints are only possible if they were set in only one JS module. With breakpoints in two or more modules the debugger freezes after the first breakpoint reached and must be restarted. In some cases, the debugger can only be terminated with the Win Task Manager.

Another thing: starting the debugger takes a very long time, i.e. about 20 s.

Are there any comments to my difficulties?

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.33GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by connor4312** [comment]
Can you try two things?

1. See if the [nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension) fixes any of your issues
2. If not, collect a trace log using these instructions:

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by aavanian** [comment]
I have a similar problem, though the debugger never actually launches and reach breakpoint.
Using [these instructions](https://www.electronjs.org/docs/tutorial/debugging-main-process-vscode) which work on OS X lead to VS Code not reaching the first breakpoint and two (hanging?) processes:

* `C:\Users\alexa\Documents\Projects\electron-quick-start\node_modules\electron\dist\electron.exe --version`
* `"node" "C:\Users\alexa\Documents\Projects\electron-quick-start\node-modules\.bin\\...\electron\cli.js" --version`

that need to be killed by hand.

* nightly extension doesn't fix it.
* `"debug.javascript.usePreview": true` fixes it.

Attaching log from `"trace": true`:
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/5033957/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment]
`"debug.javascript.usePreview": true`, did you mean `"debug.javascript.usePreview": false`?

I'm not seeing any output given from electron's stdout/err, which would be expected even if all else failed. What version of Node and Electron are you running?

**Comment by aavanian** [comment]
indeed, I meant `false`, edited above.

Node.js 12.14.1
Chromium 83.0.4103.122
Electron 9.1.2.
(these versions are from the project) and VS Code 1.47.3

**Comment by connor4312** [comment]
Okay, thanks. Try setting your `type` to `pwa-node` instead of `node`, and adding `"nodeVersionHint": 10,` to your launch config.

**Comment by aavanian** [comment]
so indeed with those changes and `usePreview` back to `true`, the debugger launches.

However, the output is a bit different than with `usePreview: false`:

`"usePreview": true` , `"type": "pwa-node"`, `"nodeVersionHint": 10`:
```
C:\Users\alexa\Documents\Projects\electron-quick-start/node_modules/.bin/electron.cmd .
Debugger listening on ws://127.0.0.1:53804/cbd7d9ce-cf7a-48cc-8427-29741274d00b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

Debugger listening on ws://127.0.0.1:53808/d17f2e22-8265-4a51-8e50-93e8e5f0b51d
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
test: main process reporting
```

`"usePreview": false`:
```
C:\Users\alexa\Documents\Projects\electron-quick-start/node_modules/.bin/electron.cmd --inspect-brk=19977 . 

Debugger listening on ws://127.0.0.1:19977/897058d5-e589-47d8-8c6d-7a91e5dda68b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
test: main process reporting
```

**Comment by connor4312** [comment]
That's expected -- we debug _all_ processes, including the electron 'wrapper' process (there's probably some more correct word for that).

Good to hear the issue is fixed. I'm not sure why you get stuck on `C:\Users\alexa\Documents\Projects\electron-quick-start\node_modules\electron\dist\electron.exe --version`, though. What happens if you run `./node_modules/.bin/electron.cmd --version` in a terminal?

**Comment by aavanian** [comment]
Right on! It hangs, be it in powershell or cmd, not sure why...

**Comment by connor4312** [comment]
Hm. I'm curious whether it still fails if you set `"electron": "^11.0.0-nightly.20200805"` in the package.json (and npm install). If it does we should file an issue on Electron.

**Comment by aavanian** [comment]
yep, hangs as well (i had to use "electron-nightly": "^11.0.0-nightly.20200805" and remove the "electron" dependency but i suppose this is what you meant)

**Comment by connor4312** [comment]
Okay, interesting, thanks. I'll open an issue and tag you on it. Since I haven't received reports of this from other users, I am not planning to put a mitigation in place within js-debug at the moment, but I'll keep an eye out.
