### ISSUE TITLE
error：The terminal process terminated with exit code: 1

### ISSUE THREAD

**Issue by BetaMee** [Microsoft/vscode#10353]
- VSCode Version: 1.4
- OS Version:1511

Steps to Reproduce:
1. create  a  folder with Chinese characters like *G:\WebFloder\project\测试*
2. then press <kbd>Ctrl+`</kbd> to open Terminal   

3.vscode will throw error `The terminal process terminated with exit code: 1`
4.if the folder created like  *G:\WebFloder\project\test* ,it works normally

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7727

**Comment by EyasChen** [comment]
I faced this issue too on windows 10

**Comment by dfrho** [comment]
This worked for me:
Hit Command + Shift + P
Scroll to Reload Window
Select It
