### ISSUE TITLE
Hijacks OSX "paste without formatting"

### ISSUE THREAD

**Issue by philipithomas** [Microsoft/vscode#10354]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Copy text
2. Try to paste without formatting: `command-shift-v`
3. New tab opens with preview

Expected behavior: Plaintext is pasted

**Comment by alycda** [comment]
There is a default Keyboard shortcut:

```` javascript
{ "key": "shift+cmd+v",           "command": "markdown.showPreview",
                                     "when": "!terminalFocus" },
````

There may not be a workaround of defining a different keybinding for `markdown.showPreview`, as I don't see a relevant `editor.action.clipboardPasteWithoutFormattingAction` that could be assigned to `shift+cmd+v`

**Comment by jrieken** [comment]
Correct - since we only support plain paste it's bound to `Cmd+V` - else you can unbind or rebind the keys as you like
