### ISSUE TITLE
Menus do not behave correctly

### ISSUE THREAD

**Issue by sloth77** [microsoft/vscode#103572]
Issue Type: <b>Bug</b>

Standard Windows applications allow you to choose menu items by:

1.  Mouse down on menu title (eg. File)
2.  Drag the mouse to the desired menu item (eg. Save As)
3.  Release the mouse

For Visual Studio Code, it is necessary to then click the menu item after step 3.  Simply releasing the mouse is not sufficient.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.83GB (47.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
Seems to be fixed in Insiders (1.48). Maybe a consequence of the new Electron version.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/101537
