### ISSUE TITLE
VS Code Still Attaching Node Debugger with Run Without Debugging in 1.47.3

### ISSUE THREAD

**Issue by RyanLamanskyInsite** [microsoft/vscode#103515]
- VSCode Version: 1.47.3
- OS Version: Windows 10 Professional 10.0.18363.959

Steps to Reproduce:

1. Configure launch.json with a target of "node" and a JS file.
2. Run without debugging

Expected:
1.46 and older behavior where it sends Node console output to the Debug tab but otherwise doesn't attach to the process in any way.

Actual:

A variant of https://github.com/microsoft/vscode/issues/102057 where Node operates in an attached debugger mode with severe performance loss and this console output:

```
C:\Program Files\nodejs\node.exe c:\ISC\FrontEnd\startDevelopment.js
Debugger listening on ws://127.0.0.1:7607/ef0be773-49f8-4d75-8462-cf04a603d401
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
```

I was monitoring the linked issue with the hope that it would resolve this, but the problem remains in 1.47.3.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
This comment explains what's happening: https://github.com/microsoft/vscode/issues/102057#issuecomment-656440073

In our tests there is little to no performance impact -- the 'debugger' domain isn't enabled, and by far the greatest runtime impact in debugging comes from enabling async stack trace tracking, which requires V8 to do extra bookkeeping. Let's continue the disucssion on the linked issue if you have more feedback to give. Thanks!

/duplicate

**Comment by makingglitches** [comment]
one thing that does not make sense is debugging was working throughout and there was no recent update to node js before the issue began.

**Comment by makingglitches** [comment]
didnt work.
