### ISSUE TITLE
VSCode doesn't open the provided directory when invoked from the command line on MacOS Catalina

### ISSUE THREAD

**Issue by cedw032** [microsoft/vscode#103528]
- VSCode Version:
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z (5 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

- OS Version: MacOS Catalina 10.15.5 (19F101)

Steps to Reproduce:
1. Enter the following into the command line: `code /Users` (Make sure you are not already in this directory)
2. Observe Bug: VSCode will open the current directory rather than the specified directory.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I cannot reproduce.
