### ISSUE TITLE
Cant add folder from mounted network drive to workspace

### ISSUE THREAD

**Issue by globules-io** [microsoft/vscode#103555]
- VSCode Version: 1.47.3
- OS Version: Window 10 x64

Steps to Reproduce:

1. Map a network drive
2. Add folder to workspace
3. Only local drives are available, network drives do not show in the "select folder" window

Does this issue occur when all extensions are disabled?: Yes

**Comment by globules-io** [comment]
For real? It's the window that opens to select the folder to add to workspace.
There is no network drive in it.

**Comment by globules-io** [comment]
![LOL](https://user-images.githubusercontent.com/13317159/90011200-2ba5fb00-dc6f-11ea-9460-3d7bd92821ef.jpg)

**Comment by bpasero** [comment]
We do not control this dialog, it originates from Windows. I suggest you report an issue against Windows support.

**Comment by globules-io** [comment]
Any other window not opened from VSCODE shows the mapped folder.
