### ISSUE TITLE
ctrl + F12 hotkey on Linux to go-to-implementation doesn't work.

### ISSUE THREAD

**Issue by NTaylorMullen** [microsoft/vscode#103517]
![image](https://user-images.githubusercontent.com/2008729/88721120-cc76b100-d0da-11ea-9342-54737fa6d67f.png)

Steps to Reproduce:

1. On Linux do Ctrl + F12 to go to implementation on any language

Expected:
You go to implementation

Actual:
You don't. Note: If you right click => go-to-implementation everything works as expected. It's just the hotkey that doesn't work

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@NTaylorMullen can you open keybindings editor and start recording, and then press ctrl+f12 and see what's being recorded?

**Comment by NTaylorMullen** [comment]
@rebornix oh wow, ya it doesn't pick up the ctrl + f12 at all (just captures the ctrl). That or any of the F keys. If I try combining ctrl with other keys such as shift, a, alt etc. things work as expected.

For extra context, I'm remoting into my Linux box. Is this a problem with how VSCode captures keys or potentially the remoting software i'm using?

**Comment by rebornix** [comment]
@NTaylorMullen yup, the problem is there is another application which hijacks (or overrides) ctrl+f12 and VS Code doesn't get a chance to receive the keyboard shortcuts.
