### ISSUE TITLE
Strange colors in vscode 

### ISSUE THREAD

**Issue by MukeshKalaga** [microsoft/vscode#103513]
Issue Type: <b>Bug</b>

Sometimes strange glitches (dont know what to call them) appear. screenshot uploaded

![Screenshot (27)](https://user-images.githubusercontent.com/21159332/88713429-e941d180-d138-11ea-9e5b-8f058c0a4904.png)
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
materialdesignicons-intellisense|luk|3.0.0
sublime-keybindings|ms-|4.0.7
vscodeintellicode|Vis|1.2.9
html-css-class-completion|Zig|1.19.0

</details>

**Comment by deepak1556** [comment]
Does the issue happen when you run with `--disable-extensions` ?

These are mostly due to gpu rendering issue, you can try disabling hw acceleration using https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

Also you can check if the issue repros with latest insiders https://code.visualstudio.com/insiders

**Comment by MukeshKalaga** [comment]
> Does the issue happen when you run with `--disable-extensions` ?
> 
> These are mostly due to gpu rendering issue, you can try disabling hw acceleration using https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
> 
> Also you can check if the issue repros with latest insiders https://code.visualstudio.com/insiders

Thank you for the quick reply. But the issue happens very rarely is there a way to check if the issue is solved. Usually when it occurred i restarted vs code and since then i didn't see that issue.

**Comment by deepak1556** [comment]
This seems to be gpu specific based on other similar reports, I don't have idea about verifying the fix.

Next when the issue happens, can you attach the following profile.

* Open window devtools
* Go to performance tab
* Enable advanced paint instrumentation under settings
* Click start profiling and reload page icon
* Download the profile

<img width="625" alt="Screen Shot 2020-08-05 at 6 06 00 PM" src="https://user-images.githubusercontent.com/964386/89478930-5d3a3600-d746-11ea-81e7-1d629b2a618c.png">

**Comment by deepak1556** [comment]
merging to https://github.com/microsoft/vscode/issues/93356 for now.
