### ISSUE TITLE
Machine slows down with many git.exe sessions running

### ISSUE THREAD

**Issue by paulelong** [microsoft/vscode#103514]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

1. Open project, which is pretty large
2. Watch task manager as git session get created for many minutes

At this point while the git session are happening my machine slows down.  The git sessions seem to stop after a while, but then can get retriggered again, not sure why or when.

If I disable extensions, I don't see git session show up anymore.  This repository is a Axon's git repository and not github.

(BTW, you can't select File On as Extension because the drop down is blank)

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (0.74GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by joaomoreno** [comment]
Unfortunately this is a consequence of us using git.exe for the git features. You can disable the git extension in that workspace by using the `git.enabled` setting.
