### ISSUE TITLE
Intellisense issue with NODE_PATH evnvironment variable

### ISSUE THREAD

**Issue by lekhnath** [Microsoft/vscode#10359]
- VSCode Version:1.4
- OS Version: Ubuntu 13.10

Steps to Reproduce:

**Project Structure**
```
<project-root>
  + libs
       - utils.js
  - app.js
```

**utils.js**
exports.greetings = function(msg){console.log(msg);}

**app.js**
var utils = require('libs/utils');
utils.greetings('Hello');

The problem is I am not getting intellinsense working properly but the program runs fine if run with :
`NODE_PATH=./ node app`

But the relative require `require('./libs/utils')` gives the intellisense.

**Comment by dbaeumer** [comment]
To my knowledge the TS compiler and language server don't support this resolution pattern. Will move to the TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10248

**Comment by pedro-mass** [comment]
How's this a Typescript only issue?
I've got this same problem in my `create-react-app` Javascript project. 

There's a setting for the linters
```
"eslint.nodePath": null,
  "tslint.nodePath": ""
```
but nothing similar for updating the intellisense path
