### ISSUE TITLE
terminal pane filename detection doesn't handle line wrapping

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#103520]
Issue Type: <b>Bug</b>

- open terminal pane
- run build process with long filenames 
- shrink the window enough (horizontally) so the filenames wrap
- attempt to ctrl-click on one of the filenames
- bug: the clicked filename is truncated

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64
Remote OS version: Linux x64 4.4.0-19041-Microsoft

**Comment by Tyriar** [comment]
Are you in a Windows workspace or a WSL where this happens? For Windows there are cases where it won't work until a Windows update goes out with https://github.com/microsoft/terminal/issues/405, for WSL I can't reproduce, can you give more information and a [gif](https://gifcap.dev/)?
