### ISSUE TITLE
terminal bar is hiding automatically

### ISSUE THREAD

**Issue by Jackbost16** [microsoft/vscode#103532]
Issue Type: <b>Bug</b>

whenever i try to run code my terminal bar runs and hides automatically. i don't know why it's happening after the latest update

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD E-450 APU with Radeon(tm) HD Graphics (2 x 1645)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.60GB (1.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.0
cpptools|ms-|0.29.0

</details>

**Comment by Jackbost16** [comment]
see the terminal is hiding automatically

**Comment by Jackbost16** [comment]
![1](https://user-images.githubusercontent.com/68938052/88883778-c0adfa80-d252-11ea-9b48-1e0966b2b1cd.png)
the terminal comes for 2 seconds then again hides automatically. I was not facing this problem before

**Comment by Jackbost16** [comment]
> /gifPlease

![1](https://user-images.githubusercontent.com/68938052/88883861-f18e2f80-d252-11ea-9c7a-b67af0b2c613.png)
the terminal comes for 2 seconds then again hides automatically. I was not facing this problem before

**Comment by lszomoru** [comment]
What happens if you choose `Terminal -> New Terminal` from the main menu? Does the Terminal window appear?

**Comment by Jackbost16** [comment]
> What happens if you choose `Terminal -> New Terminal` from the main menu? Does the Terminal window appear?

yes it appears but when I try to run the code it runs and then disappears in 2 seconds

**Comment by lszomoru** [comment]
Thanks! 

Are you able to reproduce this with running any other code than C?

Do you mind recording a gif?

>Thanks for reporting this issue! Unfortunately, it's hard for us to understand what issue you're seeing. Please help us out by providing a screen recording showing exactly what isn't working as expected. While we can work with most standard formats, .gif files are preferred as they are displayed inline on GitHub. You may find https://gifcap.dev helpful as a browser-based gif recording tool.

>If the issue depends on keyboard input, you can help us by enabling screencast mode for the recording (Developer: Toggle Screencast Mode in the command palette).

**Comment by Jackbost16** [comment]
it has solved!! it was because of a virus. Even cmd was getting off after 1-2 seconds of running
