### ISSUE TITLE
Feature Request: Collapsible chained methods.

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [microsoft/vscode#103558]
Many times I use chained methods in javascript. For example:
```
var m = new Map()
    .set("apple", "red")
    .set("banana", "yellow")
    .set("grapes", "purple")
```
The problem is that bigger chians take up a lot of space on the screen, and it would be much move convenient if they were collapsible. With how the current collapsible things look, I imagine it would look like this when collapsed:
```
> var m = new Map()...
  )
```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by ChocolateLoverRaj** [comment]
I opened an issue upstream: [https://github.com/microsoft/TypeScript/issues/39825](https://github.com/microsoft/TypeScript/issues/39825).
