### ISSUE TITLE
Git autorefresh is not working in WSL

### ISSUE THREAD

**Issue by valdineifer** [microsoft/vscode#103534]
Issue Type: <b>Bug</b>

1. Open a git project.
2. Edit any file that are not excluded by .gitignore.
3. Save.

After that, the VSCode will indicate with that blue bar next to the row numbers where the change is. However, the editor doesn't indicate with the letters U (for new files) or M (for modified files).
Besides that, the VSCode doesn't refresh and show the changes in the Source Control sidebar. I have to click on "Refresh" at the top or restart the VSCode.
I'm creating this issue because I didn't find any solution here. Also I've tested in another repository and I got the same problem.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.32GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/mnt/d/dev/js/ugamers-api --remote=wsl+Ubuntu-18.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.89GB (2.32GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
todo-tree|Gru|0.0.178
markdown-all-in-one|yzh|3.2.0
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
vscode-inline-sql|jtl|0.1.4
dotenv|mik|1.0.1
remote-wsl|ms-|0.44.4
vs-keybindings|ms-|0.2.0
material-icon-theme|PKi|4.2.0
rocketseatreactjs|roc|3.0.2
rocketseatreactnative|roc|3.0.1
code-settings-sync|Sha|3.4.3

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Are you editing files which live on the WSL side?

**Comment by valdineifer** [comment]
When you say "live on the WSL side" you mean that are on my Linux file section? No, the files are in other partition. I have to use/edit inside the Linux section?

**Comment by joaomoreno** [comment]
Exactly. Only use Remote WSL to edit files which live inside the Linux file section. If they are outside, you're better off editing them with VS Code directly.
