### ISSUE TITLE
Suppress settings sync badge while window is loading

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#103501]
- Have settings sync enabled
- Reload the window
- See the blue (1) badge appear on the accounts activity bar item appear briefly

I keep seeing this and thinking there's something wrong, then it disappears. Would be a little nicer if it would wait a couple seconds before deciding whether to show it

**Comment by sandy081** [comment]
/duplicate

@RMacfarlane this needs static authentication provider contribution as I am not sure until when to wait  - https://github.com/microsoft/vscode/issues/103405
