### ISSUE TITLE
Allow to compare folders to see changes to another folder

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#10350]
- VSCode Version: 1.4.0
- OS Version: Windows 10

currently only 1 file can be viewed in a diff mode, please enable diffing folders

**Comment by bpasero** [comment]
@aleksey-bykov maybe install a tool for diffing? why would VS Code allow you to diff 2 folders?

**Comment by aleksey-bykov** [comment]
i use "meld" (http://meldmerge.org/) for diffing folders, by the same reasoning you might be wondering why i am not using VS2015 for writing code in TypeScript, well because i like everything in one place

**Comment by bpasero** [comment]
You need a folder diff tool to work on TypeScript?

**Comment by aleksey-bykov** [comment]
any text file please

**Comment by aleksey-bykov** [comment]
real life use case:
- doing code reviews using `git difftools` from `master` againast a `feature` branch

**Comment by aleksey-bykov** [comment]
related: https://www.google.com/search?q=git+difftool+directory+diff

**Comment by bpasero** [comment]
@aleksey-bykov wait, now you talk about comparing git branches, for that we already have a feature request and that makes a lot more sense to me.

If so I would close this one because it draws the impression you want to compare 2 real folders on dirks.

**Comment by aleksey-bykov** [comment]
this is what happens behind the scene, git creates 2 folders for you, all you need to do is to feed them to a tool capable of diffing folders

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6898
