### ISSUE TITLE
Close window and shutdown gives corrupted files

### ISSUE THREAD

**Issue by mrelarsen** [microsoft/vscode#103537]
- VSCode Version: Hard to say since it corrupted my files but pre-latest as it has updates
- OS Version: Windows 10 Pro N 1909

Steps to Reproduce:

1. You want to shut down your PC.
2. You close the MS VS Code windows (not knowing if it has some updates to install).
3. Shutdown computer right after.
4. Start PC and find your MS VS Code inaccessible.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mrelarsen** [comment]
It has happened to me twice now which is why I am giving feedback

**Comment by bpasero** [comment]
What does this mean exactly:

> Start PC and find your MS VS Code inaccessible

**Comment by mrelarsen** [comment]
@bpasero The shortcut that I used to open VS Code was a broken link and I was not able to find the exe file at the previous location, this is what I mean by inaccessible
