### ISSUE TITLE
An extension can't control the capitalization of its name in the settings UI

### ISSUE THREAD

**Issue by thalesx** [microsoft/vscode#103592]
- VSCode Version: 1.47.3
- OS Version: Windows 10

Steps to Reproduce:

1. Install an extension like CMake Tools ("CMake") or GitLens ("GitLens")
2. Open that extension's settings page.
3. Note the UI shows the extension name capitalized as "Cmake" or "Gitlens", and there doesn't seem to be a way for the extension to control the capitalization of its displayed name (see attachment below). 
4. Note "CMake" or "cmake" are the standard capitalizations for the term.

![Cmake](https://user-images.githubusercontent.com/26282603/88861646-437f7880-d1b3-11ea-9658-470e8692184c.PNG)

**Comment by gjsjohnmurray** [comment]
Yes, I think the solution at the moment is to get entries added to source here:
https://github.com/microsoft/vscode/blob/f732547a3d548a640e5120eca4bfb59cbedc3c48/src/vs/workbench/contrib/preferences/browser/settingsLayout.ts#L244-L248

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/70589
