### ISSUE TITLE
VSCode wipes my files every time to try to clear the changelop

### ISSUE THREAD

**Issue by iNoobBoi** [microsoft/vscode#103580]
- VSCode Version: 1.47.3
- OS Version: 10.12.6

Steps to Reproduce:

1. Open VSCode
2. Click on Changes
3. Right-click on Changes
4. Click "discard all changes"
5. confirm
6. and it deletes EVERYTHING on your computer and it doesn't even put it in the trash can, just poof, gone, forever.

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by joaomoreno** [comment]
So... after confirming the following dialog you are still surprised the files got deleted?

![image](https://user-images.githubusercontent.com/22350/88900180-58a9e500-d24f-11ea-8168-1d9ad687a216.png)

**Comment by iNoobBoi** [comment]
There appears only to be 2 changes, the only dialogue popping up is "Confirm discard all changes?", and then the everything gets wiped.

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/) of that?

**Comment by iNoobBoi** [comment]
I do not want to delete all my files again. Is there another way I can provide you with the necessary information?

**Comment by joaomoreno** [comment]
You can simply use temporary files which you create for the specific purpose of showing me the issue.

**Comment by iNoobBoi** [comment]
![Screen Shot 2020-08-03 at 11 10 31 AM](https://user-images.githubusercontent.com/59546554/89213298-b99c2a80-d579-11ea-8157-318bc0276617.png)
![Screen Shot 2020-08-03 at 11 10 33 AM](https://user-images.githubusercontent.com/59546554/89213300-ba34c100-d579-11ea-83ac-bbc0312a2fd4.png)
![Screen Shot 2020-08-03 at 11 10 35 AM](https://user-images.githubusercontent.com/59546554/89213302-ba34c100-d579-11ea-9875-c2314e09bd61.png)
![Screen Shot 2020-08-03 at 11 10 43 AM](https://user-images.githubusercontent.com/59546554/89213303-bacd5780-d579-11ea-91de-7c18dae17027.png)
Here are the screenshots of what happens.

Also, I am not saying I am surprised that the files are deleted after I confirm the popup, I am surprised that I need to delete all my files to clear the changes, and that VSCode doesn't send then to the trash can.

**Comment by iNoobBoi** [comment]
Oh, and I forgot to mention, it also clears all my history, cookies, site data, etc.

**Comment by joaomoreno** [comment]
Can you expand the CHANGES row, by clicking on that little arrow on the left?

Also, DON'T click the `Delete Files` button any more. You are surely deleting things you don't want to delete.

Run `git rev-parse --show-toplevel` to find out where your git repository root is. If that should not be a git repository, then delete the `.git` folder contained within it.

**Comment by iNoobBoi** [comment]
![Screen Shot 2020-08-04 at 9 59 42 AM](https://user-images.githubusercontent.com/59546554/89322335-f11ddc00-d638-11ea-88d4-46a4168654a0.png)
Thanks

**Comment by joaomoreno** [comment]
You have created a git repository in your user home. I believe you didn't do this on purpose. Delete the `~/.git` folder which lives in your user home and the git extension will stop treating it as a git repository.
