### ISSUE TITLE
Right Click Option to search selected text in browser with a pre-defined search template.

### ISSUE THREAD

**Issue by tommmc** [microsoft/vscode#103554]
The ability to select text and then have a right click option to search for that text in my browser.
Could add a default template to the search like "python " + {selected text}.

**Comment by roblourens** [comment]
Can you explain some more? Are you talking about searching here? 
![image](https://user-images.githubusercontent.com/323878/88938788-9c462400-d23a-11ea-983b-23d34dc670e7.png)

If so you can select text then press ctrl+shift+f (or cmd+shift+f)

**Comment by tommmc** [comment]
I was thinking more like a shortcut for an internet browser search. Like search for selected text on stackoverflow or search in chrome for selected text? 

What i do currently is select snippet or text > copy > open browser > paste > add context to the search (for example 'python:') > then go.

Its a just a small task I find myself doing constantly to learn more about code snippets etc. Be nice to have it as a shortcut or menu option where i can set default search templates.

**Comment by roblourens** [comment]
Oh I see. An extension could do this. Actually I made one a long time ago (dunno if it still works) I think the space of things that you would want to is very large so it doesn't make sense for vscode to do this itself.
