### ISSUE TITLE
VSCode gets stuck with "The window has crashed"

### ISSUE THREAD

**Issue by christophberlin** [Microsoft/vscode#10352]
- VSCode Version: 1.4
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. If I would know, I would be wiser

This happened:

VS Code launched and stated than an update is available. I clicked update, restart and then this happened. See attached GIF. Unfortunately, this particular behavior is worse than it seems. I cannot get out of the loop, I even deleted VS Code, deleted settings in Application Support, but nada. My Code installed is stuck. The machine is still available for repro if required.

![aug-08-2016 20-38-27](https://cloud.githubusercontent.com/assets/7737992/17524544/ee360356-5e13-11e6-8968-239184efb516.gif)

**Comment by joaomoreno** [comment]
Can you launch it from the command line? `code --verbose`

**Comment by christophberlin** [comment]
Well, it doesn't seem to be an option on OSX.

> Christophs-MBP:Desktop Christoph$ open -a Visual\ Studio\ Code --verbose
open: unrecognized option `--verbose'
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-b <bundle identifier>] [-a <application>] [filenames] [--args arguments]
Help: Open opens files from a shell.
      By default, opens each file using the default application for that file.  
      If the file is in the form of a URL, the file will be opened as a URL.
Options: 
      -a                Opens with the specified application.
      -b                Opens with the specified application bundle identifier.
      -e                Opens with TextEdit.
      -t                Opens with default text editor.
      -f                Reads input from standard input and opens with TextEdit.
      -F  --fresh       Launches the app fresh, that is, without restoring windows. Saved persistent state is lost, excluding Untitled documents.
      -R, --reveal      Selects in the Finder instead of opening.
      -W, --wait-apps   Blocks until the used applications are closed (even if they were already running).
          --args        All remaining arguments are passed in argv to the application's main() function instead of opened.
      -n, --new         Open a new instance of the application even if one is already running.
      -j, --hide        Launches the app hidden.
      -g, --background  Does not bring the application to the foreground.
      -h, --header      Searches header file locations for headers matching the given filenames, and opens them.
<

**Comment by joaomoreno** [comment]
Can you try `/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --verbose`?

**Comment by michaelmanus** [comment]
I just downloaded (5minutes ago) the current build of vs code on https://code.visualstudio.com/Download

For OSX and I'm getting the same as above.

Here is the console output:

michaelmanus@Michaels-MacBook-Pro:~$ /Applications/Visual\ Studio\ Code\ 2.app/Contents/Resources/app/bin/code --verbose
(6:58:54 PM) Sending env to running instance...
(6:58:54 PM) Sent env to running instance. Terminating...
michaelmanus@Michaels-MacBook-Pro:~$

Oddly, it works when it's launched from the downloads folder - perhaps because I launched an older version of the application from there before and it expects a file that was created there.

**Comment by christophberlin** [comment]
Ok, didn't know that you wanted me to run the binary directly. Here is the Output BUT once I ran the code binary with --verbose directly, the app actually launched and launches ever since.

Here is the output from the first launch:

> Christophs-MBP:bin Christoph$ ./code --verbose
(10:34:27 AM) ### VSCode main.js ###
(10:34:27 AM) /Applications/Visual Studio Code.app/Contents/Resources/app { pathArguments: [],
  programStart: 0,
  enablePerformance: false,
  verboseLogging: true,
  debugExtensionHostPort: undefined,
  debugBrkExtensionHost: false,
  logExtensionHostCommunication: false,
  debugBrkFileWatcherPort: undefined,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  diffMode: false,
  extensionsHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  disableExtensions: false,
  locale: undefined,
  waitForWindowClose: false }
(10:34:29 AM) IPC#vscode:setDocumentEdited
(10:34:29 AM) IPC#vscode:startCrashReporter
(10:34:29 AM) IPC#vscode:setRepresentedFilename
(10:34:29 AM) IPC#vscode-workbenchLoaded
(10:34:32 AM) App#activate

**Comment by joaomoreno** [comment]
That's great to know, even though we didn't figure out the problem. I'll close the issue.

One more thing: you should _upgrade_ your command line launcher:

1. Remove the `code` alias from your `.bashrc` that you set up long ago
2. Execute the `Shell Command: Install 'code' command in PATH` command from the command palette <kbd>Cmd Shift P</kbd>

**Comment by alisherabd** [comment]
I actually resolved it by removing it from Applications folder and putting a new app back

**Comment by CalvinDale** [comment]
I'm encountering this issue now. The OS (Windows 10) either crashed or ran some updates automatically restarted. Now after logging in when I attempt to launch VS Code it displays "The window has crashed" dialog. And this dialog doesn't permit escape to the editor. The `--verbose` flag doesn't seem to have any effect. I suppose I'll have to reinstall VS Code.

**Comment by dattz** [comment]
The --verbose flagged worked for me on Windows 7 64 Bit.

For newbies:
Run "code --verbose" from command line.

**Comment by danielfranca** [comment]
This issue started to me after update VS Code.
Tried running with -verbose, which doesn't help
```
/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --verbose
[main 4:25:00 PM] Sending env to running instance...
[main 4:25:01 PM] Sent env to running instance. Terminating...

```

Also tried removing from Applications folder and re-adding... the issue persists.

**Comment by jtlapp** [comment]
I had two windows open and one ended up stuck in a loop of saying it's crashed but never letting me close it -- only redisplaying the error message saying to close or reopen. I finally resolved the issue by exiting VSC entirely and relaunching it.

I have no idea what the circumstances might have been. On Mac OS X. VSC 1.16.0 (1.16.0).
