### ISSUE TITLE
On startup / Sometimes can't use the integrated terminal

### ISSUE THREAD

**Issue by DaCurse** [microsoft/vscode#103563]
- VSCode Version: 1.47.3
- OS Version: Windows 10 Enterprise LTSC 64 bit 1809

Steps to Reproduce:
I'm not sure

Does this issue occur when all extensions are disabled?: Yes

I'm using Git Bash as my terminal, and when I start up VSCode or sometimes when I create a new terminal, the cursor doesn't blink, I can't see what I'm typing and it scrolls down a bunch
![image](https://user-images.githubusercontent.com/26578884/88813862-19818280-d1c2-11ea-96e4-6af15264ad54.png)

When I type a command like `clear` for example then it starts working again and I can use the terminal normally. I am not sure what is causing this issue, I tried to re-install Git Bash but the issue still persists.
I also tried to use an empty `.bashrc` but that changed nothing.
This only happens within VSCode, nothing similar is happening when I start Git Bash on it's own.

Here is my `settings.json` file:
```json
{
	"workbench.startupEditor": "newUntitledFile",
	"workbench.colorTheme": "One Dark Pro",
	"workbench.activityBar.visible": true,
	"workbench.iconTheme": "vscode-icons",

	"terminal.integrated.shell.windows": "D:\\Program Files\\Git\\bin\\bash.exe",
	"terminal.integrated.shellArgs.windows": ["--login", "-i"],

	"explorer.confirmDelete": false,
	"explorer.confirmDragAndDrop": false,
	"editor.fontSize": 14,
	"editor.defaultFormatter": "esbenp.prettier-vscode",
	"editor.tabSize": 2,
	"editor.insertSpaces": false,
	"editor.detectIndentation": true,
	"editor.formatOnSave": true,
	"editor.codeActionsOnSave": {
		"source.organizeImports": true
	},
	"editor.fontFamily": "Fira Code",
	"editor.fontLigatures": true,
	"editor.minimap.enabled": false,
	"editor.suggestSelection": "first",
	"files.eol": "\r\n",
	"window.zoomLevel": 0,
	"javascript.updateImportsOnFileMove.enabled": "always",
	"typescript.updateImportsOnFileMove.enabled": "always",
	"python.pythonPath": "D:\\Program Files (x86)\\Python38-32\\python.exe",
	"prettier.useTabs": true,
	"prettier.endOfLine": "crlf",
	"prettier.singleQuote": true,
	"prettier.trailingComma": "es5",
	"sync.removeExtensions": false,
	"vsicons.dontShowNewVersionMessage": true,
	"telemetry.enableTelemetry": false,
	"vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
	"tabnine.experimentalAutoImports": true,
	"extensions.ignoreRecommendations": true,
	"[rust]": {
		"editor.defaultFormatter": "rust-lang.rust"
	}
}
```

**Comment by DaCurse** [comment]
It appears that this is related somehow to the height of the integrated terminal window, if I make it really tall and then start up VSCode I can use it normally, but if I resize it and make it smaller it will repeat the behaviour I mentioned above.

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
