### ISSUE TITLE
Can't copy text from python interactive window to code editor

### ISSUE THREAD

**Issue by asalcedo29** [microsoft/vscode#103571]
Issue Type: <b>Bug</b>

Trying to copy part of an output from the python interactive window (a long string that I need to use my code to filter) and when pasting I'm not getting the expected result (but rather whatever I had previously copied). This is an erratic behavior; in a few cases the copy command will work but in most it just pastes the incorrect element. 

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.7.96456
highlight-words|rsb|0.1.4
tabnine-vscode|Tab|2.8.12
vscodeintellicode|Vis|1.2.9

</details>

**Comment by gjsjohnmurray** [comment]
Sounds like an issue recently fixed. Can you test with [Insiders](https://code.visualstudio.com/insiders/)?

**Comment by Fennehk** [comment]
I had the same problem with version 1.47.3 however the problem seems to have been fixed in the insiders version. That being said, I had tried previously tried to workaround this issue  by using the mouse right click, however no contextual menu with the usual copy / paste / cut functions opens. Is there a reason for that?

**Comment by lszomoru** [comment]
If you are still experiencing the issue with mouse right click, can you please file a separate issue for that? Thank you!
