### ISSUE TITLE
npm.fetchOnlinePackageInfo is not respected in latest build

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#103540]
```
Version: 1.48.0-insider
Commit: 15e798e081984a17eae00de91adf4479190d5ed2
Date: 2020-07-28T10:40:03.139Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
```

## Steps to Reproduce:

1. set `"npm.fetchOnlinePackageInfo": false`
2. check any dep in `package.json` 
3. package info still being fetched

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
You are correct, the hover would still make online requests. I push a fix.

Note that even with `"npm.fetchOnlinePackageInfo": false` it's still possible to get hovers and proposals when you have the `npm` command on the PATH.

**Comment by ctf0** [comment]
> Note that even with "npm.fetchOnlinePackageInfo": false it's still possible to get hovers and proposals when you have the npm command on the PATH.

but how to disable it completely ?

**Comment by aeschli** [comment]
There's no setting for that. But you can disable the npm extension.
