### ISSUE TITLE
Codelens feature causing unexpected diff areas in git diff view

### ISSUE THREAD

**Issue by thoughtentity** [Microsoft/vscode#1035]
When the codelens feature pops in the editor to show reference info while viewing a git file diff it causes additional diff areas to show up in areas where the codelens UI gets inserted.

![image](https://cloud.githubusercontent.com/assets/208549/11605563/e85b01c2-9ab7-11e5-862d-b1fbbe03b85a.png)

**Comment by aeschli** [comment]
That's the expected bahaviour. Codelens should only show up on the side representing the current file content.
