### ISSUE TITLE
Allow Webview Developer Tools to be docked on the main Window

### ISSUE THREAD

**Issue by laike9m** [microsoft/vscode#103576]
In VS Code, when you open the **Webview Developer Tools** window, it cannot be docked to the main Window.

There's no docking option in the Developer Tools menu:

[![enter image description here][1]][1]

And even if I use the command menu to let it dock, it doesn't work

[![enter image description here][2]][2]

It would be nice if the Webview Developer Tools window can be docked like Developer Tools window. Or is there a reason that we can't?

  [1]: https://i.stack.imgur.com/aVH17.png
  [2]: https://i.stack.imgur.com/7fPtF.png

**Comment by mjbvz** [comment]
This is not supported by electron

**Comment by laike9m** [comment]
> This is not supported by electron

That makes sense. Just out of curiosity, why can the normal Developer Tools window be docked?
