### ISSUE TITLE
new vscode workspace always opens on 1st Gnome workspace where a vscode workspace was opened

### ISSUE THREAD

**Issue by jlmagee** [microsoft/vscode#103549]
Issue Type: <b>Bug</b>

on some Gnome workspace say 17
1. open a terminal window
2. cd to some directory
3.  type "code-insiders ."   

and vscode opens with the selected directory  in that gnome workspace
then move to a different Gnome workspace say 4
repeat steps 1-3 above using a different directory
vscode opens in Gnome workspace 17 when it should have opened in Gnome workspace 4

This started several insider releases ago.  It could possibly be a Gnome change but I do not think so.

VS Code version: Code - Insiders 1.48.0-insider (15e798e081984a17eae00de91adf4479190d5ed2, 2020-07-28T10:39:40.074Z)
OS version: Linux x64 5.7.9-100.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 3566)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|62.66GB (20.27GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id eaf9ffa4-897c-4051-b2ab-50ca4d1de991|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.21.1
npm-intellisense|chr|1.3.0
vscode-postgres|cko|1.1.11
vbscript|Dar|1.0.4
vscode-eslint|dba|2.1.8
githistory|don|0.6.8
xml|Dot|2.5.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.12
json-tools|eri|1.0.2
prettier-vscode|esb|5.1.3
shell-format|fox|7.0.1
cloudcode|goo|1.4.1
beautify|Hoo|1.5.0
vscode-hexdump|ili|1.8.2
vscode-rufo|jnb|0.0.1
svn-scm|joh|2.11.5
puppet-vscode|jpo|0.24.2
graphql-for-vscode|kum|1.15.3
rainbow-csv|mec|1.7.0
import-sorter|mik|3.3.1
vscode-docker|ms-|1.4.1
python|ms-|2020.7.96456
cpptools|ms-|0.29.0
powershell-preview|ms-|2020.6.1
debugger-for-chrome|msj|4.12.9
ruby|reb|0.27.0
java|red|0.65.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.23.0
vscode-ruby|win|0.27.0
hex-ascii-converter|yrp|0.0.1

</details>

**Comment by jlmagee** [comment]
This issue does not occur with code-insiders-1.48.0-1594705773.el7.x86_64
It started occurring with code-insiders-1.48.0-1595570144.el7.x86_64

Also, this error started appearing with code-insiders-1.48.0-1595570144.el7.x86_64
[Error - 7:27:56 AM] (node:1626347) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
This error seems to be associated with extension clolkman-vscode.postgres.  After disabling that extension, this error message no longer appears but the Gnome workspace issue still occurs.

**Comment by jlmagee** [comment]
I cannot work this way.  Please respond.

I'm currently using a build from a couple of weeks ago

**Comment by deepak1556** [comment]
sorry for the delayed response, can confirm the issue on ubuntu 20.04. This seems to be an issue with how we handle browser window alignment, base electron app doesn't repro.

/cc @bpasero

**Comment by bpasero** [comment]
> This seems to be an issue with how we handle browser window alignment

Can you clarify?

**Comment by jlmagee** [comment]
Any estimate about when this will be addressed?

**Comment by jtwatson** [comment]
This just bit me in the stable release. I am running Fedora 32, GNOME 3.36.5. Vscode 1.49.0

Any estimate on fixing this?

**Comment by deepak1556** [comment]
Can you check if latest insiders https://code.visualstudio.com/insiders/ fixes it ?

**Comment by jlmagee** [comment]
@deepak1556 It is fixed for me.  Thanks.

**Comment by deepak1556** [comment]
Thanks for testing, merging this to https://github.com/microsoft/vscode/issues/106727
