### ISSUE TITLE
NodeJS debugger freezing indefinitely after outputting too much

### ISSUE THREAD

**Issue by hedgehog90** [microsoft/vscode#103511]
Issue Type: <b>Bug</b>

Simply calling console.log repeatedly, outputting large strings is enough to completely break the debugger.
It doesn't just stop outputting to the debugger console, the entire program will completely freeze. For instance, if I am running an http server in the debugger and it writes too many large logs, the whole program will freeze and the server will not respond to any requests.
It's a completely silent, traceless killer.
Running the following in vscode's debugger will print 9 times in quick succession before freezing inexplicably. No error is produced. Running from a command line however it runs without issue:

```
setInterval(()=>console.log("123456789 ".repeat(1000), 500);
```

Edit:
I believe I've been encountering this issue for quite some time, but I've only just realised it's triggered by writing too much to the debug console.
I've found if I leave a node program running in vs code's debugger for long enough, I eventually encounter this issue.
The trigger appears to be if I try to write around 100kb of strings in the console.
However, I can't find anyone else complaining about it online which makes me think it might be something on my end.
I have tested vs code with all extensions disabled and it doesn't help.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (17.17GB free)|
|Process Argv|--file-uri file:///c%3A/Projects/Sites/cabtv/cabtv.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.3
vscode-nextgenas|bow|1.2.1
vscode-swf-debug|bow|1.2.1
tslint|eg2|1.0.44
prettier-vscode|esb|5.1.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
go|gol|0.15.2
haxe-hl|Hax|1.1.0
blender-development|Jac|0.0.12
MagicPython|mag|1.1.0
csharp|ms-|1.22.1
python|ms-|2020.7.96456
remote-wsl|ms-|0.44.4
cpptools|ms-|0.29.0
mono-debug|ms-|0.15.8
powershell|ms-|2020.6.0
debugger-for-chrome|msj|4.12.9
vshaxe|nad|2.21.4
lime-vscode-extension|ope|1.4.0
rewrap|stk|1.13.0
vscode-lua|tri|0.12.4
haxe-debug|vsh|1.2.3
hxcpp-debugger|vsh|1.2.4
</details>

**Comment by connor4312** [comment]
See here for a solution, this will be release in the next vs code stable release. Thanks for filing an issue! https://github.com/microsoft/vscode/issues/102254#issuecomment-658247768

/duplicate
