### ISSUE TITLE
Auto create new window with current tab when drag outside current window

### ISSUE THREAD

**Issue by trinhcanhphuc** [microsoft/vscode#103504]
Issue Type: <b>Feature Request</b>

Auto create new window with current tab when drag outside current window like jetbrains ide

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 5.4.0-42-generic snap

**Comment by yume-chan** [comment]
Duplicate of #10121
