### ISSUE TITLE
Keys not responding 

### ISSUE THREAD

**Issue by argd14** [microsoft/vscode#103587]
Issue Type: <b>Bug</b>

Certain keys are not responding in VS code, it just suddenly happens and another developer here at my company is having the same issue , what we do to fix it is to reopen vs code, but after a day or 2 it happens again

Below is the information of my vs code build -

Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx   (4 x 2495)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|10.70GB (3.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-intelephense-client|bme|1.5.3
phpserver|bra|2.4.6
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
gitlens|eam|10.2.2
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.1.3
php-debug|fel|1.13.0
auto-rename-tag|for|0.1.4
vscode-mysql|for|0.4.0
vscode-pull-request-github|Git|0.18.0
beautify|Hoo|1.5.0
mysql-syntax|jak|1.3.1
vscode-docker|ms-|1.4.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
powershell|ms-|2020.6.0
vsliveshare|ms-|1.0.2478
vsliveshare-audio|ms-|0.1.85
debugger-for-chrome|msj|4.12.9
vscode-react-native|msj|0.16.1
material-icon-theme|PKi|4.2.0
vscode-css-peek|pra|4.0.0
LiveServer|rit|5.6.1
highlight-matching-tag|vin|0.9.9
vscodeintellicode|Vis|1.2.9
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0
livereload|zii|0.2.5

(4 theme extensions excluded)

</details>

**Comment by TheUnlocked** [comment]
I experienced a similar issue for the first time earlier today, with paste not working. Developer: Reload Window fixed it. It happened for me after hitting a series of keyboard shortcuts (I don't exactly know which ones, but I think paste was in there) very quickly, though I'm not sure if that was a coincidence or if it's actually related to the issue.

I'd be happy to share logs, though I have no idea which logs to share.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-186-generic
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: (redacted)|
|OS|Linux x64 4.4.0-186-generic|
|CPUs|AMD Opteron(tm) Processor 4180 (12 x 800)|
|Memory (System)|62.90GB (41.81GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|15.88GB (3.58GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
ng-template|Ang|0.1000.4
vscode-intelephense-client|bme|1.5.3
hoogle-vscode|jca|0.0.7
language-haskell|jus|3.3.0
cpptools|ms-|0.29.0
haskero|Van|1.3.1
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.9
postscript|mxs|1.0.1
open-in-browser|tec|2.0.0

**Comment by alexdima** [comment]
Please let me know if you see this again if you find any steps.
