### ISSUE TITLE
java11 or recent java is required to run.

### ISSUE THREAD

**Issue by tripadeep** [microsoft/vscode#103531]
Issue Type: <b>Bug</b>

i have downloaded the recent version still my vs code is not working

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.3
cpptools|ms-|0.29.0
java|red|0.65.0
python|tht|0.2.3
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.23.0

</details>

**Comment by tripadeep** [comment]
few days back it was working fine. But al of sudden I started facing this problem

**Comment by rebornix** [comment]
> java11 or recent java is required to run

@tripadeep where do you get this error?

**Comment by tripadeep** [comment]
> > java11 or recent java is required to run
> 
> @tripadeep where do you get this error?

@rebornix whenever i try to run my program i face this problem along with it it shows there is problem activating inteli  for language java

**Comment by chucknelson** [comment]
> > > java11 or recent java is required to run
> > 
> > 
> > @tripadeep where do you get this error?
> 
> @rebornix whenever i try to run my program i face this problem along with it it shows there is problem activating inteli for language java

@tripadeep - Are you using Java extensions, specifically the popular [Language Support for Java by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java)?

If so, you'll be getting that error if your extension auto-updated, as the latest version `0.65.0`, released about a week ago, [requires Java 11](https://marketplace.visualstudio.com/items/redhat.java/changelog). 

You can roll back to the prior extension version and it'll work, or you can move to Java 11...which may not be possible depending on your project.

**Comment by tripadeep** [comment]
> @chucknelson ok.. I'll check it once...

**Comment by tripadeep** [comment]
> > > > java11 or recent java is required to run
> > > 
> > > 
> > > @tripadeep where do you get this error?
> > 
> > 
> > @rebornix whenever i try to run my program i face this problem along with it it shows there is problem activating inteli for language java
> 
> @tripadeep - Are you using Java extensions, specifically the popular [Language Support for Java by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java)?
> 
> If so, you'll be getting that error if your extension auto-updated, as the latest version `0.65.0`, released about a week ago, [requires Java 11](https://marketplace.visualstudio.com/items/redhat.java/changelog).
> 
> You can roll back to the prior extension version and it'll work, or you can move to Java 11...which may not be possible depending on your project.

@chucknelson ok I'll check it once
