### ISSUE TITLE
Have a mode to show what's causing a keyboard shortcut conflict

### ISSUE THREAD

**Issue by pingshunhuangalex** [microsoft/vscode#103524]
**Is your feature request related to a problem? Please describe.**
I forgot where I saw the feature, maybe Atom. When you are tweaking your keyboard shortcut, if it runs into a conflict, the editor will list out what actions are bound to this shortcut and which ones are not being triggered. Something like that. This is extremely helpful if you are configuring VSCode Vim to work with normal VSCode.

**Describe the solution you'd like**
Having something similar would be really nice. Just a way to list out all the actions and their conditions when I press a shortcut and marking out which one is being executed and which ones are not.

**Describe alternatives you've considered**
Well, I mean without the feature, VSCode is still amazing. I just need to spend more time to wrap my head around and figure out why a specific shortcut is not working. I guess it's nice to have...

**Comment by IllusionMH** [comment]
It's already in VS Code. When you perform Add Keybinding or Change Keybinding action in Keyboard Shortcuts view it will show that there are commands that have provided shortcut
![image](https://user-images.githubusercontent.com/1312662/88741472-6a549500-d148-11ea-9c50-00ab02d7a371.png)

Click on "13 existing commands..." will perform search by this shortcut to show you whole list

If it's not what you are looking for - please add more details how it should be different from current behavior.

**Comment by pingshunhuangalex** [comment]
Sorry, I'm more talking about when I'm actually using a shortcut in a file. Not in the keyboard shortcut page. I know people may think the difference is subtle, but I think the context here can be quite handy. Again I think it's just a good to have if this never makes it to the priority list. Thanks.

**Comment by IllusionMH** [comment]
Oh, I was confused by

> When you are tweaking your keyboard shortcut, if it runs into a conflict, the editor will list out what actions are bound to this shortcut

Where "tweaking" looks more like changing/adding than actually using.

**Comment by pingshunhuangalex** [comment]
Sorry for the confusion, I was picturing using Vim in VSCode when I typed that "tweaking"
