### ISSUE TITLE
Option to turn off the DISTRACTING VSCode Update badge

### ISSUE THREAD

**Issue by folarinmartins** [microsoft/vscode#103548]
Just that. Please add an option to turn off UI update notification located over the Settings icon at the button-left corner of the window. It's distracting everytime I open VS Code to work. IT IS SIMPLY DISTRACTING

**Comment by gjsjohnmurray** [comment]
How about updating to the latest, then setting `"update.mode": "manual"` so you don't get notified ever again?

I guess you may also want to set `"extensions.autoCheckUpdates": false` so you don't get notified of updates to any of your extensions.

Then cross your fingers and hope no security vulnerabilities are discovered and you don't hear about.
