### ISSUE TITLE
[json] Suggestions to upgrade package is not displayed if the cursor is on the letter

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#10355]
- VSCode Version: 1.4.0
- OS Version: Windows 10 Redstone 1

Steps to Reproduce:

  1. Add dependency with dot separated identifiers to the `dependencies` section in `package.json`.
  2. Place the cursor on the digits and press <kbd>Ctrl + Space</kbd>. You will be prompted to 
upgrade version.
  
  ![2016-08-09_20-51-33](https://cloud.githubusercontent.com/assets/7034281/17527204/17556e34-5e73-11e6-8a91-ebf362a47a4e.gif)

  3. Place the cursor on the letter and press <kbd>Ctrl + Space</kbd>. No suggestions.

  ![2016-08-09_20-52-34](https://cloud.githubusercontent.com/assets/7034281/17527238/36bc3bfe-5e73-11e6-8a0f-b4829ec2d5b6.gif)

**Comment by mrmlnc** [comment]
In addition, the proposal will not appear if the cursor is before the dot.

![2016-08-09_20-54-31](https://cloud.githubusercontent.com/assets/7034281/17527334/9c19c7aa-5e73-11e6-83b7-a4acaca21182.gif)

**Comment by aeschli** [comment]
We currenlty only provide code completion for the latest version

**Comment by mrmlnc** [comment]
It's works fine for me in VS Code 1.6.1. I think we can close this issue, @aeschli?

![2016-10-27_19-11-06](https://cloud.githubusercontent.com/assets/7034281/19775468/21b21d3e-9c79-11e6-8237-f346b8bc11c4.gif)

**Comment by aeschli** [comment]
Thanks for following up.
