### ISSUE TITLE
Lost login status after each update

### ISSUE THREAD

**Issue by llk2yq** [microsoft/vscode#103675]
Issue Type: <b>Bug</b>

**After each update, I need to log back in to the sync extension.**

VS Code version: Code - Insiders 1.48.0-insider (15ada625f20086007e2c4aa0d760234360cd648f, 2020-07-30T14:46:01.621Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 8, 6|
|Memory (System)|16.00GB (2.63GB free)|
|Process Argv|-psn_0_680102 --crash-reporter-id f5ea5240-bf6c-4a3a-ae71-140382dfde1f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
uniapp-snippet|dlh|0.0.2
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
code-runner|for|0.11.0
todo-tree|Gru|0.0.178
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.48.1
korofileheader|OBK|4.7.2
vetur|oct|0.25.0
vue-vscode-snippets|sdr|1.9.0
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0
material-theme|zhu|3.8.5

</details>

**Comment by sandy081** [comment]
Are you seeing the number badge on account icon and asking to sign in?

Which account are you using?

**Comment by sandy081** [comment]
I can also reproduce this and I am sure that this caused by this https://github.com/microsoft/vscode/issues/103238

Root cause is that there is no deterministic way to know if the required auth providers are registered are not. Hence this causing a race condition while updating auth token.

Hence, I would like to revert the change in #103238 wait until #103507 is implemented.

**Comment by llk2yq** [comment]
I used to use Github account , and in Last two months. I'm  using MS account now, and in latest version(2020-08-07T05:30:01.305Z) ,this problem still exists.

**Comment by sandy081** [comment]
Can you please provide the Settings Sync logs from output view when it happens?
