### ISSUE TITLE
"Find" operation and selection

### ISSUE THREAD

**Issue by o3di** [microsoft/vscode#103647]
Prerequisite: VS Code has option "Auto Find In Selection" is set to "multiline".

Reproduction steps:
1. run VS Code
2. open a text file that has some copies of same word;
3. select  that word;
4. press 'Ctrl-F': selected word fills the search template and "Find in selection" option is ON;
5. press 'Enter: there is no editor jump to the next word copy.

Expected behavior:
"Find in selection" option must be OFF and result of action step 5 should be - cursor, selection and editor view jump to the next word copy.

Reason of expected behavior:
description of "multiline" option states that it "Turn on Find in selection automatically when multiple lines of content are selected"; because selected word belongs to one line, no "Find in selection" option should be enabled and the whole file should be viewed.

Thank you for help.

**Comment by rebornix** [comment]
I'm not able to reproduce this issue in latest Insiders, can you help confirm? It would be great if you can provide the sample text which leads to the bug.
