### ISSUE TITLE
Commands to jump between git-hunks

### ISSUE THREAD

**Issue by astier** [microsoft/vscode#103651]
I propose two new commands. `git.hunkNext` and `git.hunkPrevious` which would enable to jump between git-hunks.

**Comment by NotWearingPants** [comment]
Where? In the diff view?

**Comment by astier** [comment]
Hm. I rather meant in a normal editor. With hunks I mean the git-changes which are indicated on the left side in the screenshot.

![2020-07-31-102650_182x273_scrot](https://user-images.githubusercontent.com/36510152/89016145-8575ff00-d318-11ea-8caf-78e29f1fc2dc.png)

It is inspired by the vim plugin [gitgutter](https://github.com/airblade/vim-gitgutter#hunks) which lets you move the cursor between hunks with simple keyboard-shortcuts.

**Comment by joaomoreno** [comment]
The commands are already there: `workbench.action.editor.previousChange` and `workbench.action.editor.nextChange`
