### ISSUE TITLE
Dull color for C# Documentation XML

### ISSUE THREAD

**Issue by Banyc** [microsoft/vscode#103616]
It is too bright for tags of XML in C#, which dims the normal C# code.

```csharp
        /// <summary>
        /// This is the summary
        /// </summary>
        /// <param name="index">the index</param>
        /// <returns>...</returns>
        public int Repeat(int index)
        {
        }
```

**Comment by alexr00** [comment]
Can you provide a screen shot?

**Comment by Banyc** [comment]
> Can you provide a screen shot?

![image](https://user-images.githubusercontent.com/36535895/90352168-1963fc80-e075-11ea-91df-d5013b6f11c4.png)

...undelightful parts are underscored.

**Comment by alexr00** [comment]
Thanks for the screenshot. It looks like the those tokens are getting the color that they are set to get, so it isn't a bug. However, if you don't like the color you can set a different theme.
