### ISSUE TITLE
File rename can close editors

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10360]
In some cases we lose an opened editor:
- rename a file that is opened as inactive tab (https://github.com/Microsoft/vscode/issues/9485)
- rename the casing of a file (https://github.com/Microsoft/vscode/issues/10150)

Note that it is unlikely we can solve this for changes that happen outside of VS Code because file watchers do not know if a file was renamed or not (for them it shows as delete and add).

**Comment by bpasero** [comment]
Verify:
* renaming or moving a file updates it if it is opened in any editor group, even when not the active tab
* same works when renaming to same path with different casing

**Comment by jetaro1** [comment]
thank you :)
