### ISSUE TITLE
annoying vertical line

### ISSUE THREAD

**Issue by orket** [microsoft/vscode#103662]
Issue Type: <b>Bug</b>

vertical line on my .dart files only despite having no rulers set in my settings

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 5.4.0-42-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3338)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|7.66GB (0.51GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.12.2
flutter|Dar|3.12.2
python|ms-|2020.7.96456
material-icon-theme|PKi|4.2.0

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Have you checked if there is Dart specific configuration (object in `[dart]` property) in User or Workspace settings JSON file? It won't be visible in Settings UI as modified
![image](https://user-images.githubusercontent.com/1312662/88977278-4b7c0d00-d2c6-11ea-866c-927431d65cb5.png)

Tried without extensions in Insiders build - there are no rules in `.dart` file.

**Comment by orket** [comment]
It disappears when all extensions are disabled

**Comment by orket** [comment]
What does that mean?

**Comment by orket** [comment]
Never mind I figured it out

**Comment by wuzzar321** [comment]
what was the fix?

**Comment by wuzzar321** [comment]
Never mind I figured it out

**Comment by orket** [comment]
under these directories depending on your Os:

   - Windows %APPDATA%\Code\User\settings.json
   - macOS $HOME/Library/Application Support/Code/User/settings.json
   - Linux $HOME/.config/Code/User/settings.json

The settings.json file under "editor.rulers":[] was modified and should be
empty

**Comment by devorrah** [comment]
I have the same problem. `"The editor.rulers": [],` is set correctly. Please help.
![vs code line](https://user-images.githubusercontent.com/25807788/89953498-3162f880-dbfd-11ea-803d-c0ee7b8b70f4.png)

**Comment by abhayswee2** [comment]
**Solution**

In **settings.json** file, you will find code similar to below :
```

  "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.rulers": [
            80
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
```
set 
```
"editor.rulers": [
            80
        ]
```
to 
`"editor.rulers": [ ],`
