### ISSUE TITLE
explorer.confirmDragAndDrop doesn't work

### ISSUE THREAD

**Issue by whitecolor** [microsoft/vscode#103642]
- VSCode Version: insiders 1.48.0-insider
- OS Version: Windows 10

I'm not sure if it should but setting `explorer.confirmDragAndDrop` doesn't work and seem to be unknown for vscode.

![image](https://user-images.githubusercontent.com/736697/88953447-680e4a00-d2b2-11ea-96c4-d0649ca19352.png)

**Comment by isidorn** [comment]
Works for me 

![Screenshot 2020-07-30 at 19 55 59](https://user-images.githubusercontent.com/1926584/88957121-b44f8f00-d29e-11ea-9cac-69f0520b2dab.png)

Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by IllusionMH** [comment]
Can't repro as well
Version: 1.48.0-insider (user setup)
Commit: 15ada625f20086007e2c4aa0d760234360cd648f
Date: 2020-07-30T14:43:12.691Z
OS: Windows_NT x64 10.0.18363

![image](https://user-images.githubusercontent.com/1312662/88967955-32b82b00-d2b7-11ea-85ad-163ab45ec476.png)

**Comment by gjsjohnmurray** [comment]
@whitecolor have you put it more than once in your settings.json file?

![image](https://user-images.githubusercontent.com/6726799/88970791-ee269280-d2aa-11ea-93bf-39c658ab0ca3.png)

**Comment by whitecolor** [comment]
> @whitecolor have you put it more than once in your settings.json file?
> 
> ![image](https://user-images.githubusercontent.com/6726799/88970791-ee269280-d2aa-11ea-93bf-39c658ab0ca3.png)

Right! sorry my bad -)
