### ISSUE TITLE
Sanity Test Settings Sync

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#103613]
- [x] windows @RMacfarlane
- [x] mac @connor4312
- [x] linux @weinand

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103613%0A%0A)

---

## Set Up

You can use two insiders opened with different user data directory (`--user-data-dir`) and extension directory (`--extensions-dir`) for test syncing across machines.

## Testing

We are planning to enable Settings Sync for stable users in this release. So, I would ask the assignees to do an exploratory end to end testing of following settings sync features.

- Make sure you get a preview confirmation dialog when you turn on sync for the very fist time. Even though we are enabling for stable users this feature will be still in preview mode.
- Make sure **Settings Sync** term is used in the product to represent this feature
- Test settings, keybindings, snippets, extensions and UI state are syncing across devices flawlessly.
  - Test `machine` and `machine-overridable` scoped settings are ignored by default. These are typically settings that has local paths  as values.
  - Test enablement state of extensions is synced 
  - Test advanced features like ignoring settings, extensions and syncing keybindings across platforms
  - Test you can able to handle and resolve conflicts if they occur
- Make sure you can track and monitor sync activity and discover all necessary sync features.
  - Test Sync Activity & Machines view using the command `Settings Sync: Show Synced Data`
  - Test the actions available in these views (Restoring, editing machine name & turning off sync on a machine)
- Test turning off Settings Sync either on current machine or on all machines.

Authors: @sandy081 @Tyriar

**Comment by connor4312** [comment]
> Test machine and machine-overridable scoped settings are ignored by default. These are typically settings that has local paths as values.

I'm not sure what these are, how do I find out which settings are machine/machine-overridable?

**Comment by sandy081** [comment]
@JacksonKearl Sorry for not being clear about machine scoped settings. These settings are those whose scope is defined as `machine` or `machine-overridable` while being registered. UI does not represent it. Here are some machine scope settings:

- `git.path`
- `typescript.npm`
- `typescript.tsserver.pluginPaths`
- `php.validate.executablePath`

**Comment by JacksonKearl** [comment]
I think you meant @connor4312 but good to know 🙂

**Comment by sandy081** [comment]
Oops sorry.

**Comment by weinand** [comment]
After testing Settings Sync for a day, I must say that it works "smooth as silk". Great job!
