### ISSUE TITLE
Window stops working.

### ISSUE THREAD

**Issue by TheGhoul27** [microsoft/vscode#103698]
- VSCode Version: 1.47.3 (user setup)
- OS Version: Windows 10 2004

Steps to Reproduce:

1. I am facing this issue where the window stops working when an error is encountered while running the code.
  ![image](https://user-images.githubusercontent.com/59188455/89035855-43b97880-d359-11ea-8ac5-9a42c9fd9b16.png)
Please help me out with this.

Does this issue occur when all extensions are disabled?: No

**Comment by gjsjohnmurray** [comment]
> Does this issue occur when all extensions are disabled?: No

I suggest you enable your extensions one at a time until you find the one that is causing the problem. Then report it to the extension author.

**Comment by Tyriar** [comment]
Does this happen after you close a terminal? https://github.com/microsoft/vscode/issues/76548
