### ISSUE TITLE
VSCode seems to delete/uninstall itself somewhat on work laptop.

### ISSUE THREAD

**Issue by ADoublin** [microsoft/vscode#103632]
- VSCode Version: 1.45.1 (SCCM)
- OS Version: 

Steps to Reproduce:

1. I believe it occurs when Visual Studio Code was updated. Now my PC acts like it isn't installed, but there are some leftover files in the [Microsoft VS Code] folder, but some are missing and no executable besides Code.exe and unins000.exe exist and Code.exe doesn't launch

EDIT:
2. I tried to Uninstall/reinstall and during the uninstallation, I got an error saying "Message File "C:\Program Files\Microsoft VS Code\unins000.msg" is missing. Please correct the problem or obtain a new copy of the program." so I am now stuck

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you completely remove and reinstall VS Code once again?

**Comment by ADoublin** [comment]
Hey, I found what I think is the issue. When looking around, it seems like an update seems to have caused this whole issue. I guess the update may have failed or something and this is what caused the issue. I have completely removed and reinstalled VS Code and it seems to be working fine now, although I am afraid once it updates again it might have the same issue.

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.
