### ISSUE TITLE
[Feature Request] Improved GitHub Functionality

### ISSUE THREAD

**Issue by tamimmirza** [microsoft/vscode#103690]
As we know VS Code already comes with Git bundled and an existing project can be initialized as a Git repo but I found out that the user would have to manually create a repo on GitHub and then link it to the Git repo in VS Code.

I suggest that a functionality to automatically create a repository via VS Code using GitHub user authentication (along with two-factor authentication), GitHub SSH keys to allow VS Code to utilize the GitHub API to do just that and finally once the repository (along with any README, License files if selected) is created then VS Code can automatically push the files to the repository on GitHub without leaving VS Code.

**Comment by gjsjohnmurray** [comment]
Did you find the "Publish to GitHub" command in the Command Palette? And is there a "Publish to GitHub" button on the SCM view in VS Code?

**Comment by tamimmirza** [comment]
Yes I found the button but I encountered a problem when using it

I created a repository on GitHub then initialized my current project as a
Git repo then tried to use "Push to GitHub" and it did not upload it to
GitHub.

**Comment by gjsjohnmurray** [comment]
Maybe provide more details of what did and didn't happen? Screenshots might help.

**Comment by tamimmirza** [comment]
Unfortunately I cannot provide any logs or screenshots because I deleted the project on my PC after I manually uploaded the files to GitHub and haven't tried it again. It's quite possible that I did not use it properly.

Does the "Push to GitHub" button do the tasks I have specified above? If so, does it have some documentation that I can look at?

**Comment by tamimmirza** [comment]
The "Push to GitHub" button in VS Code solves my problem so I am closing this issue.
