### ISSUE TITLE
Autocompletion error when adding #includes with C/C++ extension

### ISSUE THREAD

**Issue by mfarver** [Microsoft/vscode#10363]
- VSCode Version: 1.3.1
- OS Version: Linux Ubuntu 16.04

Steps to Reproduce:

1.  With the Microsoft C/C++ Extension installed create a new/ empty .C file
2.  Start typing <code>#include <stdio.h></code>.  When you reach the end of the line the IDE will attempt to offer autocompletion options, and pressing enter to move to the next line will select the topmost entry in the autocomplete instead of moving to the next line.  A mouse click is required to move to the next line, slowing data entry.

**Comment by jrieken** [comment]
@mfarver Can you paste a screen shot of what it is suggesting?

**Comment by mfarver** [comment]
I tried to grab a screen shot on a machine with 1.4.0 and I was unable to replicate.  I will grab a screen shot from the 1.3.1 system tonight, but I will say that it is likely that this is resolved.
