### ISSUE TITLE
Test turning on sync experience

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#103604]
Testing #100346 #102581

- [x] windows @rebornix
- [x] mac @mjbvz
- [x] linux @9at8

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103604%0A%0A)

---

## Set Up

You can use two insiders opened with different user data directory (`--user-data-dir`) and extension directory (`--extensions-dir`) for test syncing across machines.

## Testing

This test plan item is intended to test the experience of turning on settings sync in various scenarios and make sure it is working as expected.

- Test setting up Settings Sync on a machine for the first time ever (You have not synced from any other machine before)
  - Test when you have not changed any configuration (empty settings, keybindings, snippets & extensions).
  - Test when you have already configured VS Code with changes to settings, keybindings, snippets & extensions.
- Test setting up Settings Sync on another machine for the first time (You have already synced from another machine before) and you have not changed any configuration (empty settings, keybindings, snippets & extensions). 
- Test re-enabling Settings Sync on a machine if you last synced from the same machine (turn off sync on the machine, either do or do not do any configuration changes and turn on sync) 

In all above scenarios, turning on Sync shall start syncing without any user intervention. It means after you sign in you shall see `Settings Sync is turned on` notification.

- Test setting up Settings Sync on another machine for the first time (You have already synced from another machine before) and you have already configured VS Code with some changes to settings, keybindings, snippets & extensions. Since you are trying to merge data in this case, you shall see a **Merge or Replace** dialog asking for user input.
  - Test this dialog is helpful to understand the above case during the set up
  - Test `Replace Local` & `Merge` actions are working as expected
  - Test `Cancel` action or Esc cancels turning on sync
  - You can also choose to merge manually to turn on sync. Please follow below steps to test manual merge.

### Test Manual Merge

- Test view shows configuration entries (settings, keybindings, snippets, extensions) those were changed.
- Test merging them using the actions (replace with cloud, replace with local, merge) available on each entry.
- Test handling conflicts if you choose to merge and there are conflicts.
- Test removing the snippets in the cloud/local if they are new in local/cloud respectively..
- Test the entry is deemphasised and a check mark is shown at the end after accepting using above action.
- Test revert action is shown on the entry once accepted - pressing it shall reset the entry to its original state.
- Test `Cancel` actions is enabled always and on pressing this cancels turning on sync
- Test `Turn on Settings Sync` action is disabled until all entries are merged manually. 
- Test this manual merge view in general (wordings, flow etc).
- Test pressing `Turn on Settings Sync` action 
  - Merges the data correctly (as you chose)
  - Closes sync viewlet 
  - Shows sync is turned on notification

Overall, test if above flow(s) are helpful to the user while turning on sync.

**Comment by rebornix** [comment]
Not sure how but I get `Unable to open 'globalState.json ↔ globalState.json': Too many requests. Allowed only 100 requests in 5 minutes..` while testing ;(

**Comment by sandy081** [comment]
@rebornix Did you try to open the globalState.json from Sync Activity view?

**Comment by rebornix** [comment]
@sandy081 I actually got the error with any operation during that period. It seems it's very easy to run into the request limit if you have 3 machines connected and playing around with the settings. Note that I'm not stress testing, but just comparing settings, turning on and off.

**Comment by sandy081** [comment]
I see your point but I have not seen any reports of this while self hosting except once - https://github.com/microsoft/vscode/issues/101878. 

I do not know what is the best client side limit but as of now 100 per 5 mins seems reasonable unless user does not play around with sync activity view.

I will have eye open for it and increase the limit.
