### ISSUE TITLE
Intellisense in go does not work - creates high CPU go process

### ISSUE THREAD

**Issue by ericoff** [Microsoft/vscode#10369]
- VSCode Version: 1.4.0
- OS Version: 10.12 Beta (16A270f)

Steps to Reproduce:

1. In any context where intellisense should pop-up start typing the name of any existing function
2. Notice intellisense does not show
3. Press Ctrl-Space - a small window pops up that reads "Loading..."
4. Check activity monitor and a process named `go` will be consuming high CPU. No intellisense after waiting at least 1 minute.

If there's any other information I can give to help diagnose this, I'll be happy to provide.

**Comment by jrieken** [comment]
This issue was moved to Microsoft/vscode-go#421
