### ISSUE TITLE
Debugger does not display values of C++ STL Containers within an object

### ISSUE THREAD

**Issue by bcaddy** [microsoft/vscode#103657]
- VSCode Version: 1.47.3
- OS Version: macOS 10.15.6, remotely debugging on Red Hat Linux 3.10.0-1062.4.1.el7.x86_64

Steps to Reproduce:

1. Create an object with a public C++ STL container (vector in this case)
2. Run debugger, all public STL containers in the object show their value as `{...}`

I have a struct called Grid1D which contains several std::vector<doubles>. When I'm using an object of that struct the debugger displays `{...}` as the value, even when I try to copy the value.

Does this issue occur when all extensions are disabled?: Yes/No - I'm working in a remote machine and I'm not sure how to test this

**Comment by bcaddy** [comment]
Which extension(s)? Can you provide some direction?

**Comment by weinand** [comment]
C++

**Comment by bcaddy** [comment]
If I disable the C/C++ extension ([this one](https://github.com/Microsoft/vscode-cpptools)) then debugging fails entirely with the error `Configured debug type 'cppdbg' is not supported.`.

That is the only C++ extension I have installed

**Comment by weinand** [comment]
Please file this issue against the C++ extension. VS Code has no builtin C++ functionality. So we cannot help you.

**Comment by bcaddy** [comment]
Understood. Thank you
