### ISSUE TITLE
in the vscode'terminal,I can't use the history command

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/vscode#10368]
_From @czmecho on August 9, 2016 1:35_

Please use the following bug reporting template to help produce actionable and reproducible issues:

* Your Windows build number win 10 14393.10 && vscode 1.4
when I use the powershell or cmd ,I can use the PgUp or the PgDn keys to roll back to use the history command.
but when I call the bash.exe ,it don't work.
![](http://ww1.sinaimg.cn/large/7df5111fgw1f6n8s035krj2149091ta7.jpg)
btw,can I change the background color ,I don't like the color like this.

_Copied from original issue: Microsoft/BashOnWindows#828_

**Comment by bitcrazed** [comment]
_From @fpqc on August 9, 2016 15:3_

Yeah, seems to be related to the same problem we've had to work around since about day 1 with ConEMU.   It's another console glitch.  In ConEmu you could get around it by launching bash with special arguments like -cur_console:p, but I don't know if VS code has similar arguments you can throw in to make its integrated terminal work right.

**Comment by bitcrazed** [comment]
_From @zadjii-msft on August 9, 2016 22:38_

I would open this as a bug on the VSCode team (https://github.com/Microsoft/vscode) as this is more an issue with their built-in console, rather than an embedded conhost window

**Comment by bitcrazed** [comment]
Moved from BashOnWindwos repo.

Please be sure to notify OP (@czmecho) when investigating.

**Comment by fpqc** [comment]
@bitcrazed Probably should change the title (which made sense in the BashOnWindows repo, but will probably not be specific enough here)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10163
