### ISSUE TITLE
[themes] settings: support for multiple theme names in VSCode colorCustomization

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#103694]
Reading the documentation on [theme customisation](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme), the syntax only allows an override for one theme.

Sometimes overrides may need to apply to different themes (e.g. all dark, light or material themes), for reasons mainly about accessibility and comfort. This has actually been asked about on [StackOverflow](https://stackoverflow.com/questions/55054156/how-to-customise-the-textmaterules-for-multiple-themes-in-vs-code).

Patterns might be useful, i.e. (`[...Material Theme...]`, `[...Material Theme Lighter]`).
Also arrays with any syntax you recommend: `[Atom One Dark] [Default Dark+]`.

[12/08/2020] Editing this to add a gist for code bloat: [`settings.json`](https://gist.github.com/nedevel/3c44ea606e0ab19765b527e4a642eee1#file-settings-json). While extracting those settings into an MVCE, I saw 3 JSON errors.

**Comment by rbenson** [comment]
For both `workbench.colorCustomizations` and `editor.tokenColorCustomizations`, if you do ` "textMateRules": [{...}]`, changes will effect everything regardless of theme picked. If you add a `"['theme name']"`  block, or whatever the technical name is, before the ` "textMateRules": [{...}]`, you target just that theme. My guess is you could do `"['theme name',  'second theme']"`,

**Comment by lmn8** [comment]
Looks okay for theme arrays syntax wise - I can try write a pull to update the code related to https://github.com/microsoft/vscode/issues/36860.

https://github.com/microsoft/vscode/blob/76d612786aa01ce9430e3964649b981f954155ab/src/vs/workbench/services/themes/common/colorThemeData.ts#L357

**Comment by aeschli** [comment]
What happens if there are multiple sections that match a theme?

**Comment by lmn8** [comment]
* Settings are updated by key, and last section wins.
* `...` also selects the theme name without any `...`.

**Comment by aeschli** [comment]
To verify:
use new syntax `*` in front or after a label to match more than one theme
```
        "editor.tokenColorCustomizations": {
                "[*Dark]": {
                        "strings": "#FF0000"
                }
        },
 ```

**Comment by laurentlb** [comment]
Does this feature allow me to match all dark themes? (even if they don't have `dark` in their name)

**Comment by aeschli** [comment]
@laurentlb No we don't have that
