### ISSUE TITLE
Git synchronizer does not working after you execute git commands on the integrated terminal

### ISSUE THREAD

**Issue by siderlan** [Microsoft/vscode#10364]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:49:32.489Z)
- OS Version: Linux x64 4.4.0-31-generic

Steps to Reproduce:

1. I've opened the integrated terminal and I've executed the git status command. It has executed successfully.
2. After that I've tried to execute a git synchronization from the git status bar and the following output has been displayed - fatal: Unable to create '/my-project-folder/.git/index.lock': File exists.
3. I've tried to fix it by removing the index.lock file but it seems not exists indeed.

**Comment by siderlan** [comment]
No. The issue is keeping occurring

**Comment by joaomoreno** [comment]
Ok, can you try exactly the same, but using your system terminal instead of the integrated terminal?

**Comment by siderlan** [comment]
I've tried and the issue is still happening. Doesn't matter whether you use the system or the integrated terminal. You can't use the synchronize after you use them. And if you list the files the index.lock doesn't exists.

**Comment by joaomoreno** [comment]
What's your git version? Make sure you have at least v2.

**Comment by siderlan** [comment]
I've installed the 2.7.4. The latest version available in the Ubuntu packages.

**Comment by joaomoreno** [comment]
This seems to be a git specific issue, in which git fails to delete the `index.lock` file. I suggest you file an issue on the git issue tracker. Here are a few reference links:

-http://stackoverflow.com/questions/7860751/git-fatal-unable-to-create-path-my-project-git-index-lock-file-exists
- http://stackoverflow.com/questions/9282632/git-index-lock-file-exists-when-i-try-to-commit-but-cannot-delete-the-file
- http://stackoverflow.com/questions/11838793/git-git-index-lock-file-exists
