### ISSUE TITLE
VSCode opens "Run" tab every time a debugging process is restarted

### ISSUE THREAD

**Issue by GonziTaji** [microsoft/vscode#103638]
VSCode about info:

* Version: 1.47.3 (user setup)
* Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
* Date: 2020-07-23T13:12:49.994Z
* Electron: 7.3.2
* Chrome: 78.0.3904.130
* Node.js: 12.8.1
* V8: 7.8.279.23-electron.0
* OS: Windows_NT x64 10.0.18362

When restarting a debugging a process in VSCode, the Sidebar will open with, or change to, the "RUN" tab. Not long ago this didn't happen, and I'm assuming it's a bug due to how annoying it can be

This is more noticeable/annoying when using an utility like `nodemon` as `runtimeExecutable`. Everytime a file is saved, the "Run" tab will re-open.

Steps to Reproduce:

1. Open a folder with a long-running script in VSCode, like

```javascript
// test.js
setInterval(() => {
    console.log('one second has passed')
}, 1000);
```

2. Add basic configuration to launch.json

```json
{
    "name": "Launch Program",
    "program": "${workspaceFolder}/test.js",
    "request": "launch",
    "skipFiles": [
        "<node_internals>/**"
    ],
    "type": "node",
},
```

3. Launch program

4. Close the sidebar

5. Restart program

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by GonziTaji** [comment]
With the commit in hand I see that was always an option, my bad. Was there a reason it was changed?

**Comment by isidorn** [comment]
We did not change the default.
I just changed it now, becuase I think that default was too agresssive and personally did not like it

**Comment by GonziTaji** [comment]
Weird, I don't remember changing that in my settings, but I remember it not being like this. Thank you anyways
