### ISSUE TITLE
Contents on screen getting blurred 

### ISSUE THREAD

**Issue by levelsevencrew** [microsoft/vscode#103673]
Issue Type: <b>Performance Issue</b>

Hello, developers ! when i use visual studio code..while doing my work on it the contents and the text and also the buttons are getting blurred. i hover my mouse aroung the blurred part and then it gets clear but again in someminutes it gets blurred again . i request to look upon this issue..it is very irritating

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.85GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    82	  6220	code main
    0	    67	  1996	   window (Issue Reporter)
    0	    16	  3112	   electron-crash-reporter
    0	   188	  4060	   window (python - Visual Studio Code)
    1	   112	  6284	     extensionHost
    0	    31	 10892	       "C:\Users\Aman Kumar\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Aman Kumar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=6284
    0	    21	 11856	       "c:\Users\Aman Kumar\.vscode\extensions\ms-vscode.cpptools-0.29.0\bin\cpptools.exe"
    0	    11	  8344	         console-window-host (Windows internal process)
    0	    36	 10092	     searchService
    0	    15	 10396	     watcherService 
    0	    11	  1504	       console-window-host (Windows internal process)
    0	    33	  8008	   utility
    0	    77	  9080	   shared-process
    0	   141	 12020	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (python - Visual Studio Code)
|    Folder (python): 31 files
|      File types: py(9) xml(8) iml(2) json(2) pyc(2) gitignore(1)
|      Conf files: launch.json(1) settings.json(1)
|      Launch Configs: cppdbg python;
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
code-runner|for|0.11.0
MagicPython|mag|1.1.0
python|ms-|2020.7.96456
cpptools|ms-|0.29.0

(2 theme extensions excluded)

</details>

**Comment by dhanisalghifari** [comment]
i have same issue
![Untitled](https://user-images.githubusercontent.com/28486482/90015370-b79d3e80-dcd2-11ea-8801-214e4ded92b8.png)

**Comment by deepak1556** [comment]
Do you see this issue with a particular theme or any theme ?

Can you check if the issue happens with exploration build https://az764295.vo.msecnd.net/exploration/45f2f912b8c3bdf45bb92dc613b902136a1b60ed/VSCodeUserSetup-x64-1.49.0-exploration.exe

**Comment by levelsevencrew** [comment]
No, the problem occurs with the default theme also, but i got a work around bu launching vs code with --disable-gpu. 
i think its due to hardware acceleration to render. but i wonder i have other app too which use hardware acceleration but i never experienced problem like this!

**Comment by deepak1556** [comment]
Does the issue still happen with exploration build without disable hardware acceleration ?

**Comment by levelsevencrew** [comment]
Sorry, but i didn't tried that.

**Comment by levelsevencrew** [comment]
> i have same issue
> ![Untitled](https://user-images.githubusercontent.com/28486482/90015370-b79d3e80-dcd2-11ea-8801-214e4ded92b8.png)

In my case all the text gets blurred unless i hover my muse pointer around it.

**Comment by deepak1556** [comment]
> Sorry, but i didn't tried that

It would be great if you can try it, I would like to confirm if newer runtime fixes the gpu issue.

> Also i getting the same Text and content blur issue in the new Chromium based Microsoft edge.

which website did you try ? what is the version of edge used ? Also can you navigate to `edge://gpu` and provide the result. Thanks!

> In my case all the text gets blurred unless i hover my muse pointer around it.

can you attach the following profile.

* Open window devtools
* Go to performance tab
* Enable advanced paint instrumentation under settings
* Click start profiling and reload page icon
* Hover the mouse into affected areas which causes the blur to go away
* Download the profile

<img width="625" alt="Screen Shot 2020-08-05 at 6 06 00 PM" src="https://user-images.githubusercontent.com/964386/89478930-5d3a3600-d746-11ea-81e7-1d629b2a618c.png">

**Comment by dhanisalghifari** [comment]
I tried using this method and it worked.

right click on VsCode and click properties. and select the shortcuts tab then add this command behind the target column

"--disable-gpu --enable-use-zoom-for-dsf "

![solved](https://user-images.githubusercontent.com/28486482/90490363-bd7aa000-e168-11ea-9bf1-f5df53033685.png)

**Comment by dhanisalghifari** [comment]
I tried using this method and it worked.

right click on VsCode and click properties. and select the shortcuts tab then add this command behind the target column

"--disable-gpu --enable-use-zoom-for-dsf "

![solved](https://user-images.githubusercontent.com/28486482/90490655-10545780-e169-11ea-9b43-51b7e0985827.png)

**Comment by levelsevencrew** [comment]
The same method is used 👍

**Comment by deepak1556** [comment]
Closing based on https://github.com/microsoft/vscode/issues/103673#issuecomment-676325951
