### ISSUE TITLE
Source control UI regression + mix projects / workspaces in list

### ISSUE THREAD

**Issue by qt1** [microsoft/vscode#103640]
Issue Type: <b>Bug</b>

Source control UI is getting consistently worse in the last 5 releases or so.
Now it is barely usable.

The list/tree is extremely confusing.

* It is very hard to understand what is changed. 
* Source control of different projects are intermixed in the same list.

Here is how it looks. 
Repositories from two different projects with different workspaces get into the same list

![vscode_project_mix](https://raw.githubusercontent.com/qt1/share/master/vscode_source_control_cluttered.png)

Update: I do not know what is changed but at the moment the duplication does not occur. This seems to be an inconsistent/unpredictable behaviour.

This used to be one on the better features of VSCode but now it is very hard to dechipher the display and and use the build in source control interface.

I am now using `git diff` from terminal. more convenient than finding my way in the UI clutter.

Please bring back the UI from a couple of months ago. (list of repos on top, details below)

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 5.4.0-42-generic

CPUs | Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 4700)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: disabled_softwareskia_renderer: disabled_off_okvideo_decode: unavailable_offviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 1, 1, 1
Memory (System) | 31.30GB (0.96GB free)
Process Argv | . --no-sandbox
Screen Reader | no
VM | 0%

**Comment by qt1** [comment]
So, after working OK for some time, now again the source control displays a mix of two projects.

This is a serious and inconsistent behaviour.

Problem persists ater closing vscode and then running again `code .` on linux, in one of the folders.

![](https://raw.githubusercontent.com/qt1/share/master/vscode_source_control_cluttered2.png)

**Comment by joaomoreno** [comment]
Merging with https://github.com/microsoft/vscode/issues/102118
