### ISSUE TITLE
Extension details view should show extension contributions

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#10366]
Extensions can contribute commands to the command palette, editor menus, and the explorer context menu. In addition, commands can be bound to keyboard shortcuts.

The extension details view should give users a way to better understand the contributions an extensions makes and if those contributions cause conflicts with core VS Code keyboard shortcuts or with keyboard shortcuts used by other installed extensions.

**Comment by joaomoreno** [comment]
| Point            | Thoughts                                                                               |
|------------------|----------------------------------------------------------------------------------------|
| `configuration`  | Display a list of the config property names.                                           |
| `commands`       | Display a list of the command ids.                                                     |
| `menus`          | Show a table of the menu labels and context associated with the commands. Maybe combine with the `commands` table? |
| `keybindings`    | Show a table of the keybindings associated with the commands. Maybe combine with the `commands` table? |
| `languages`      | Show a table of language ids and file extensions.                                      |
| `debuggers`      | Show a list of the debuggers' labels.                                                  |
| `grammars`       | Maybe combine with the `languages` table?                                              |
| `themes`         | Show a list of the themes' names.                                                      |
| `snippets`       | Show whether a language has snippets or not. Maybe combine with the `languages` table? |
| `jsonValidation` | Show a list of file matches.  |

**Comment by joaomoreno** [comment]
Maybe each section can be implemented...

<details>
<summary>using...</summary>
the details tag!
</details>

**Comment by joaomoreno** [comment]
Displaying of contributions is ✅ .

cc @egamma @kieferrm 

Conflicts are much harder. While an extension provides a keybinding with a given context, I can't  unequivocally say that it will or won't conflict with another existing keybinding that has a different context. The same keybinding might come from two extensions and act in mutually exclusive contexts, thus never conflicting.

Unless I'm not seeing the full picture, @alexandrudima .

**Comment by alexandrudima** [comment]
I have a mini "SMT solver" in there, that's why I kept the language constrained to have only `&&`. I can prove if one keybinding item absolutely overwrites another keybinding item.

https://github.com/Microsoft/vscode/blob/a3493c75934a67ddadff71818ab8f7201eeb0fbf/src/vs/platform/keybinding/common/keybindingResolver.ts#L205

**Comment by joaomoreno** [comment]
Pretty cool, I'll give it a try.

**Comment by joaomoreno** [comment]
@alexandrudima Any pointers on how to get a hold of **all** registered keybindings along with their configured `when` clause?

**Comment by joaomoreno** [comment]
Decided to remove the conflicts out of this plan item.
