### ISSUE TITLE
Symlinked folders do not show git changes in explorer sidebar or main window

### ISSUE THREAD

**Issue by gullevek** [microsoft/vscode#103667]
- VSCode Version: 1.47.3
- OS Version: macOS Catalina 10.15.6

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

Folders added via
Remote SSH
or
on SMB mounted folder

Steps to Reproduce:

1. Add a folder where some part is a symlink
2. Open File and change it
3. No git highlight changes are visible in the sidebar of the open file or in the explorer bar
4. Open same folder withouth the symlink inside
5. Open the same file
6. All changes are visible

Left is non symlink folder, right is symlink folder
<img width="1348" alt="Screen Shot 2020-07-31 at 8 43 47" src="https://user-images.githubusercontent.com/855861/88985492-5f962d80-d30b-11ea-8d42-a1574863ec43.png">
In the GIT area the changes are correctly visible

Does this issue occur when all extensions are disabled?: Yes/No
Remote SSH Extension is necessary.
Local macOS symbolic links (ln -sf created) do not work the same way or do not show the same problemv

**Comment by joaomoreno** [comment]
#5970
