### ISSUE TITLE
Integrated Terminal Option+Arrow no longer jumps words

### ISSUE THREAD

**Issue by bfsmith** [Microsoft/vscode#10365]
- VSCode Version: 1.4
- OS Version: OSX 10.11.4

Steps to Reproduce:

1. Open Integrated Terminal
2. Use Option/Alt+Left Arrow or Option+Right Arrow

Expected: Cursor moves forward and back words.
Actual: Prints character codes to the terminal line (;3D;3C) for Option+Left, Option+Right

This works as expected in VSCode 1.3.1.

**Comment by Tyriar** [comment]
@bfsmith could you try repro this on https://github.com/sourcelair/xterm.js ?

**Comment by bfsmith** [comment]
It repro's there as well.

**Comment by Tyriar** [comment]
@bfsmith thanks for checking, I'm going to move the issue over there.

**Comment by Tyriar** [comment]
This issue was moved to sourcelair/xterm.js#225
