### ISSUE TITLE
add language mode for nodejs

### ISSUE THREAD

**Issue by Truth1984** [microsoft/vscode#103686]
Currently we have few main language selections for javascript, (i.e. javascript / javascript React), but I found none of them working correctly with node environment.

while running `code --disable-extensions` with version `1.47.3`.
typing `dom` in plain `.js` file and using `javascipt / babel javascript` mode will auto suggest `DOMError` for you. 

![image](https://user-images.githubusercontent.com/36292372/89020867-3482fc80-d352-11ea-8fa5-f5484a7ee453.png)

so in this case, vscode should only suggest `process` ?

**Comment by IllusionMH** [comment]
IIRC `javascriptreact` needed to match `typescriptreact`, which has special handling for syntax.

In your case you can create `jsconfig.json` (based on [node12 example](https://github.com/tsconfig/bases/blob/master/bases/node12.json)) where you specify `lib` that doesn't include `dom` (which is part of default config)
```json
{
    "compilerOptions": {
        "lib": ["es2019", "es2020.promise", "es2020.bigint", "es2020.string"],
        "module": "commonjs",
        "target": "es2019"
    },
    "exclude": ["node_modules", "**/node_modules/*"],
    "typeAcquisition": {
        "enable": true,
        "include": ["node"]
    }
}
```

Also see docs [jsconfig.json](https://code.visualstudio.com/docs/languages/jsconfig) and [Typings and Automatic Type Acquisition](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition)

**Comment by Truth1984** [comment]
thank you, I already had `eslint` set up.

just wonder if vscode can add a quick nodejs language mode, (maybe the language mode auto add `jsconfig.json`) because
1. the document is pretty hard to find
2. the user base of nodejs is huge 
3. everyone has to go though document, reconfigure and set up correctly, which takes a lot of time if you added it up.
4. auto-completing "wrong" variable is annoying

**Comment by mjbvz** [comment]
The language mode controls the supported syntax elements in a given file; the jsconfig controls which environment you are targeting.

@IllusionMH's answer notes how you can configure this. The default environment is allows browser types since that has a larger user base than node
