### ISSUE TITLE
Single header markdown cell hard to drag

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#103652]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install GitHub Issue Notebooks
2. Create a github issue notebook file, insert a markdown cell with content `## header 2` and a code cell below it
3. Fold the markdown cell
4. Now try to drag the cell, the drag area is too small

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Fixed in 2b090abd0fdab7b21a3eb74be13993ad61897f84
