### ISSUE TITLE
Keyboard shortcuts on tab context menu are not right-aligned

### ISSUE THREAD

**Issue by corydeppen** [microsoft/vscode#103637]
Issue Type: <b>Bug</b>

- Right-click a tab in the editor window
- Observe not all keyboard shortcuts are right-aligned

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<img width="270" alt="Screen Shot 2020-07-30 at 11 28 19 AM" src="https://user-images.githubusercontent.com/313264/88942858-cdcde800-d258-11ea-9ab4-a99035c8711c.png">

**Comment by NotWearingPants** [comment]
Interesting, here is the relevant code:
https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L443,L456

**Comment by etuden** [comment]
Also here?
https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/workbench/browser/parts/editor/editorCommands.ts#L480-L501

**Comment by yume-chan** [comment]
Duplicate of #75561

**Comment by bpasero** [comment]
A limitation of the macOS menus that cannot display chords.

**Comment by corydeppen** [comment]
> A limitation of the macOS menus that cannot display chords.

@bpasero Curious why some are displayed as expected and others are not.

**Comment by bpasero** [comment]
@corydeppen chords are displayed inline, others natively.
