### ISSUE TITLE
control click on error message on embedded terminal not work

### ISSUE THREAD

**Issue by esmaeelE** [microsoft/vscode#103607]
In embedded terminal if I click on some erro message for C project it is not work.
But this feature works for python

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
