### ISSUE TITLE
Quick open actions become always visible after opening explorer context menu

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#103681]
1. Open quick open, all is good
2. Right click in Explorer to open the context menu
3. Open quick open, all actions are visible

![image](https://user-images.githubusercontent.com/22350/89016903-c589b180-d319-11ea-9310-2c1069613bd2.png)

Bug is somewhere in this CSS which overwrites the `display: none` quick open depends on:

https://github.com/microsoft/vscode/blob/067059651b1e901453b509729599fc454203bb82/src/vs/base/browser/ui/menu/menu.ts#L952-L960

I thought all that CSS was only meant for the shadow DOM, shouldn't all of that be properly scoped?

**Comment by sbatten** [comment]
for menus that do not use shadow dom like global menu, we push this css to a shared top-level element in the dom. I'm not sure why this is happening now since this css exists in actionbar.css as well, but I will scope mine to monaco-menu as a fix
