### ISSUE TITLE
Test simplified extensions overflow and filter dropdown menu

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#103615]
Testing https://github.com/microsoft/vscode/issues/100756

- [x] anyOS @eamodio
- [x] anyOS @lszomoru

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103615%0A%0A)

---

### Test Default Views

Test default views in extensions viewlet which is made consistent and configurable: **Installed, Enabled, Disabled & Recommended**. By default Installed & Recommended are shown but you can configure to show the views you want using `Views` submenu under overflow actions. 

### Test Extension filters

Extensions viewlet overflow menu is simplified by moving extensions filters under a primary filter action. 

- Test newly added `Featured` filter - this should show those featured extensions that [Marketplace](https://marketplace.visualstudio.com) page shows
- Test newly added category filter 
- Make sure all other filters are working as expected (like in previous release)

**Comment by eamodio** [comment]
Good great!
