### ISSUE TITLE
CScope Style Source list for big projects

### ISSUE THREAD

**Issue by gaodingpan** [microsoft/vscode#103609]
Hi guys, I am a Kernel developer using heavily vscode. The major problem I have encountered is that, while vscode is lightweight and fast enough for the whole Kernel source file search and indexing, is it possible we add a feature letting vscode filter all the files that are not used by the kernel/project compilation? Like what they have done with source insight or CScope.

**Comment by roblourens** [comment]
We don't have any way to know which files are used for compilation here, but you can configure it yourself by setting some globs in the `files.exclude` or `search.exclude` settings. If that doesn't do it for you, please explain some more.
