### ISSUE TITLE
Feature request: Highlight + Right click to add/create snippet

### ISSUE THREAD

**Issue by chris-larsen** [microsoft/vscode#103660]
Think I'd really value to option to highlight a block of code, right click and create a new snippet. Additional nuance could have menu items to replace/update a snippet. 

Think this would be pretty elemental in creating boiler plate codes, as the current way to create/add snippets is fairly clunky.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Afeature-request+label%3Asnippets
