### ISSUE TITLE
Initializing JS/TS language features

### ISSUE THREAD

**Issue by kprasadbio** [microsoft/vscode#103678]
Issue Type: <b>Bug</b>

Launch VScode in windows or Mac.
load any project
wait for the project to load
Then try to do a drill down to a function
or write any line of code TSlin (install the plugin) is not giving error for any violation due to the issue that: Initializing JS/TS language features keep on running for inifinite

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0
![image](https://user-images.githubusercontent.com/17196589/89008717-c6760f80-d328-11ea-9e00-05c656227e21.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-tslint-plugin|ms-|1.2.3
material-icon-theme|PKi|4.2.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by kprasadbio** [comment]
I am using version (1.47.3), are you referring to a higher version than
what i am using now?
also by disabling the extensions (TSlint)  i don't see the issue.  able to
drill down/intellisense is working fine.
let me know, how can i make sure of extension without getting the issue.
[image: image.png]

**Comment by boonier** [comment]
Having same issues here; the Insiders build fixes it seemingly:

Version: 1.48.0-insider
Commit: 5696babbc1dce41788bae04b1a04ad35140bebfb
Date: 2020-08-03T05:41:11.473Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by mjbvz** [comment]
@kprasadbio Please try filing an issue against whichever extension is causing this problem
