### ISSUE TITLE
TIMELINE view doesn't work properly with SQL files

### ISSUE THREAD

**Issue by jarvistu** [microsoft/vscode#103603]
Issue Type: <b>Bug</b>

It almost always shows "no timeline information was provided" with any SQL file.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.9.0

</details>

**Comment by gjsjohnmurray** [comment]
Are you committing changes to a Git repository?

**Comment by jarvistu** [comment]
> Are you committing changes to a Git repository?

Yes, Git works normally but only TIMELINE view hardly works.

**Comment by gjsjohnmurray** [comment]
pinging @eamodio

**Comment by eamodio** [comment]
@jarvistu Can you provide more details on your repository? The Timeline view doesn't do anything specific with different files types as it just gets all its information from Git directly. Do you have any special git configuration? What happens if you run the following in a terminal?

```
git log --format="%H%n%aN%n%aE%n%at%n%ct%n%P%n%B" -z -n21 -- <put-your-file-path-here>
```

**Comment by jarvistu** [comment]
> 
> 
> @jarvistu Can you provide more details on your repository? The Timeline view doesn't do anything specific with different files types as it just gets all its information from Git directly. Do you have any special git configuration? What happens if you run the following in a terminal?
> 
> ```
> git log --format="%H%n%aN%n%aE%n%at%n%ct%n%P%n%B" -z -n21 -- <put-your-file-path-here>
> ```

@eamodio Thanks for your reply. 
I don't have any special git configuration with my repository.
After I had ran the command with absolute file path in bash, it showed 
> fatal: not a git repository (or any of the parent directories): .git
But if I change the shell working directory to my repository root first, the command runs properly with relative file path as following
>JarvisTu@JTXPS12R MINGW64 /d/OneDrive/Development/Navicat/SQL Server/Servers (master)
>$ git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z -n21 -- wlb2/WLBKQ/dbo/testing.sql
>3bdcd4db75f26de3bfe63953c981747815e8f956
>jarvistu
>jarvistu@foxmail.com
>1601008885
>1601008885
>8596486db0cd70b6e2f01c7c466364e22828a6a9
>20200925 add new files
>^@ac0555b719460eb3705a30cf563f29460c2b10a7
>Hantron
>jarvistu@foxmail.com
>1596074300
>1596074300
>65387e79c66a7a8815ee80973b9d3a445ec3e4aa
>create view clock on and off
>^@7a6eba8e89927cd612c6bc073ba852fa908b1464
>Hantron
>jarvistu@foxmail.com
>1595898504
>1595898504
>
>Navicat MSSQL WLB2 20200728
>^@

I have no idea if I did anything wrong in bash terminal. 
The TIMELINE view works properly with same SQL file in another project with different path that without space charater. 
I guess the issue was caused by space character in the file path.

**Comment by jarvistu** [comment]
> 
> 
> Hey @eamodio, this issue might need further attention.
> 
> @jarvistu, you can help us out by closing this issue if the problem no longer exists, or adding more information.

The problem still exists. I think that the problem is caused by the space characters in the file path. Perhaps we can do something about it.

**Comment by eamodio** [comment]
Hrm, I can't reproduce the issue even with spaces in the path. Maybe it is a specific issue with mysysgit. In the Output panel, under the `Git` channel -- do you see a log line that looks like `git log --format="%H%n%aN%n%aE%n%at%n%ct%n%P%n%B" -z -n21 -- <put-your-file-path-here>` if so, can you paste it here -- does it look correct? and if you run it from the command line with double-quotes around the filename if there are spaces does it work?

**Comment by eamodio** [comment]
I also wonder if your full path is too long for git, if you have a long path > 260 characters, you could try setting `git config core.longpaths true` to see if that makes any difference.
