### ISSUE TITLE
no conecction

### ISSUE THREAD

**Issue by jhonnjairoleal** [microsoft/vscode#103646]
Issue Type: <b>Bug</b>

check for updates net::ERR_PROXY_CONNECTION_FAILED

Extencion install We cannot connect to the Extensions Marketplace at this time, plase try again later

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19619

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 1796)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by jhonnjairoleal** [comment]
Yes, but I already made the changes in the proxy and the dns

**Comment by joaomoreno** [comment]
Does it work if you run `code --no-proxy-server`?
