### ISSUE TITLE
[notebook] Reduce vertical space between output data.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#103661]
- VSCode Version: 1.48.0-insider
- OS Version: Win10

Steps to Reproduce:

1. Install [.NET Interactive Notebook extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode)
2. Open an existing file (can be blank) with the extension `.dib`.
3. Set cell contents to this and execute:

``` csharp
Console.WriteLine(1);
Console.WriteLine(2);
```

Does this issue occur when all extensions are disabled?: N/A

The C# code snippet essentially mimics `"1\n2"` but the rendering makes it look like it was `"1\n\n2"`.  The same output is observed if `WriteLine` is changed to `Write` which doesn't append a newline.

Actual output:
![image](https://user-images.githubusercontent.com/926281/88975974-15ac3980-d270-11ea-98e9-71cb1e08d824.png)

Desired output (**faked with paint**):
![image](https://user-images.githubusercontent.com/926281/88976127-61f77980-d270-11ea-83af-eddfe178a261.png)

**Comment by rebornix** [comment]
@roblourens are you aware of spacing changes recently? It used to be small.

**Comment by roblourens** [comment]
It looks like your change to absolutely position outputs moved the padding from the outside container to the inside container, I can fix it

**Comment by roblourens** [comment]
Actually, I don't know, it looks like it was on `.foreground` which is still on each individual output. Is this what we want though or does it make sense to pad outputs a little?

**Comment by rebornix** [comment]
I temporarily make it `4px` instead of `8px` to make it more compact. The reason we didn't go with `0` is in quite a few cases outputs looks weird without any spacing.

**Comment by roblourens** [comment]
I dunno what the plan is. When does it look weird? Should it just be different for text outputs?

**Comment by jhoneill** [comment]
Is anything being done about this double spacing behaviour ? 
I logged https://github.com/dotnet/interactive/issues/799  nearly a year ago and the following is still true today, and seems to apply to all languages.


When PowerShell generates output it sends one or more items to the pipeline, and each one is rendered as a separate block and in the ipynb file each one becomes an object under `outputs` with      
```
"output_type": "execute_result",
"data": {
      "text/plain": 
```
This is different from .net interactive in Jupyter which outputs a single object with an `output type` of `stream`

The objects are then double spaced in the print out. 
Piping objects through `Out-String` produces a more desirable  behaviour spacing like this:
![image](https://user-images.githubusercontent.com/16209593/94362624-a0fd4c00-00b4-11eb-8e0b-7e3741d76732.png)

**Comment by brettfo** [comment]
@jhoneill I was about to close this (I'm the one that originally opened it) because just a few days ago some changes were merged that _should_ have fixed this, can you try it on the latest in stable VS Code and let us know if it's what you expect?  This is what I currently get on my machine:

![image](https://user-images.githubusercontent.com/926281/128894846-73d62e64-67ed-4a37-9ff7-e42f4a22d27d.png)

**Comment by jessiewestlake** [comment]
I still have the problem.

>Version: 1.59.0 (system setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.18363

![image](https://user-images.githubusercontent.com/19229263/128916638-194d753d-6a52-4186-bc3e-e42e028ad2c2.png)

**Comment by jhoneill** [comment]
@brettfo  It's now working for me in the stable build,  and definitely wasn't when I posted that :-) 
I'm on a slightly newer build of windows than @jessiewestlake  but  VS Code reports exactly the same versions 
The .NET interactive notebooks extension is v1.0.2409020 and .NET interactive itself is 1.0.240403

**Comment by jessiewestlake** [comment]
I just launched VSCode again today, and saw that .NET Interactive updated again, and it is **currently working**. Coincidence? I don't know.

> Version: 1.59.0 (system setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.18363

.NET Interactive version: v1.0.2409020

**Comment by tanhakabir** [comment]
Closing since it seems to be working
