### ISSUE TITLE
Python - comments are not formatted properly when using def __init__

### ISSUE THREAD

**Issue by anna072020** [microsoft/vscode#103612]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I am using white theme and my comments are usually green.
If creating a new method, then comments  are not longer formatted greed, but staying black

1. Create new method on python, e.g. 
"def __init__(self) -> None:"
2. Add a comment in the next line:
"# Comment 12345"
3. Comment remains black instead of turning green

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 4.15.0-108-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 3427)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|7.54GB (1.52GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.4.1
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.7.96456
vscode-yaml|red|0.9.1
python|tht|0.2.3
json|Zai|1.0.4

</details>

**Comment by alexr00** [comment]
I can't repro this issue. Can you try disabling all extensions and seeing if it still happens:
![image](https://user-images.githubusercontent.com/38270282/89992356-72065480-dc85-11ea-83e9-5cff047548d6.png)
