### ISSUE TITLE
Allow users to save a default custom view/sidebar layout

### ISSUE THREAD

**Issue by jaydee864** [microsoft/vscode#103654]
In the May 2020 update, VSCode released the ability to drag and drop views around in the sidebar and bottom panel. I took advantage of the feature to move the Timeline view and the GitHub Pull Request plugin view to the Source Control tab in the sidebar. I chose the following order for the sidebar based on how often I used each view: Source Control on top, Timeline in the middle, and GitHub Pull Request on the bottom, like so:
![image](https://user-images.githubusercontent.com/7988064/88961774-5600bd00-d25a-11ea-9625-7d1e0b676b3f.png)

However, I've noticed for at least the last couple of weeks, whenever I open a project I have not recently worked on or open a new project, VSCode defaults to a different order for the tab, as shown below, and I have to manually rearrange the views on each project.
![image](https://user-images.githubusercontent.com/7988064/88961910-88121f00-d25a-11ea-992b-83a074728c06.png)

Please allow users to override this default ordering of views so we don't have to manually adjust the views to our liking on every project we open.

**Comment by xgdgsc** [comment]
Also I want to save custom editor tab layout.

**Comment by waynebloss** [comment]
@sbatten or anyone else - this is completed? How do I save the panel layouts?
