### ISSUE TITLE
CompletionItem.sortText is not respected

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#103682]
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

---

1. Copy below code to https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-minimal-sample
2. Open a `plaintext` file. Enter a dot `.`
3. Complete

```ts
const vscode = require('vscode');

function activate(context) {
  vscode.languages.registerCompletionItemProvider('plaintext', {
    provideCompletionItems() {
      return [
        {
          label: 'pp',
          sortText: '01',
          kind: 5,
        },
        {
          label: 'pp-1',
          filterText: '.pp-1',
          sortText: '02',
          kind: 5,
          textEdit: {
            range: {
              start: { line: 0, character: 0 },
              end: { line: 0, character: 1 },
            },
            newText: '.pp-1',
          },
        },
      ];
    },
  });
}

module.exports = {
  activate,
};
```

Expected: `pp` show up before `pp-1`, as `'01' < '02'`
Actual:

![image](https://user-images.githubusercontent.com/4033249/89018196-0bf90380-d34e-11ea-89e3-1bd2bf969259.png)

Related: https://github.com/vuejs/vetur/issues/1804

@jrieken

**Comment by jrieken** [comment]
The sortText is only respected when no prefix is selected and since the latter item selects a prefix a score is computed and assigned.
