### ISSUE TITLE
What have u done guys?

### ISSUE THREAD

**Issue by Husirxd** [microsoft/vscode#103648]
Issue Type: <b>Bug</b>

My VSC dont show hints about metods,variables etc. in any language. 
Your messiness info bug all the time and occlude my code. 
Pls do something. Lov ya all

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

**Comment by JDWilson1980** [comment]
BotNeT/infusion/deVop/

Host/playbook/cybercrime/OP

FakeNew.txt 
Cesspool.txt
Angry birds.txt
RobbyRaccon.txt
NotOnMyDomain.txt
RemoverNewDevOppLinl
OmniRon.dev
Age of Ultron.txt

Word.press/Axios
Spot.ishares.net
Dev.ishares.qrl
Fed.blockcoin.repos
Tv.repos/monero
Tv.repos/Axios
Tv.repos/moot
Tv.repos/criticalErr
