### ISSUE TITLE
Markdown extension doesn't support checkboxes

### ISSUE THREAD

**Issue by andradei** [Microsoft/vscode#10367]
"- [ ] Item to be checked"

should be rendered as
- [ ] Item to be checked

**Comment by f111fei** [comment]
fyi https://github.com/chjj/marked/issues/689

**Comment by andradei** [comment]
So it is a GitHub flavor. Could the extension get that behavior as a _githubFlavor_ option?

**Comment by rarrarrarr** [comment]
This is my #1 request of vscode and I'm willing to work on making it happen, but I'm not sure where to start.

**Comment by mjbvz** [comment]
This is not something we really want to add to the core markdown extension, but #22916 added an experimental API in vscode 1.11 that allows extensions to extend the markdown preview. 

Here's an example extension that adds github style checkbox support: https://github.com/mjbvz/vscode-markdown-checkboxes

If you are interested in working with this API or run into any issues with it, please let me know

**Comment by andradei** [comment]
Sounds good. That being the route taken, I'm going to close this issue.

**Comment by Tom-Spring** [comment]
Hi Matt, it would be great to have a similar solution for VSTS:  https://github.com/mjbvz/vscode-markdown-checkboxes!

**Comment by mjbvz** [comment]
@Tom-Spring Could you please explain more? Do you mean supporting checkboxes in VSTS online readmes?

**Comment by andradei** [comment]
@mjbvz I think he meant he'd like the linked extension integrated natively into VSCode's Markdown feature.

**Comment by Tom-Spring** [comment]
@mjbvz<https://github.com/mjbvz> My Goal would be to be able to add DODs as checkboxes using Markdown to a "multiple Line Text Field" of a work item in vsts. Similar to the tasklists decribed at this Link
https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments


Von: Matt Bierner [notifications@github.com]
Gesendet: Dienstag, 10. Oktober 2017 18:35
An: Microsoft/vscode
Cc: Tom Spring; Mention
Betreff: Re: [Microsoft/vscode] Markdown extension doesn't support checkboxes (#10367)


@Tom-Spring<https://github.com/tom-spring> Could you please explain more? Do you mean supporting checkboxes in VSTS online readmes?

**Comment by mjbvz** [comment]
@Tom-Spring Sorry but I don't understand what you are requesting. If this is related to something on VSTS, please try filing feedback against VSTS. Otherwise, please open a new issue and provide an example of what you are talking about
