### ISSUE TITLE
problem with edit environment variable

### ISSUE THREAD

**Issue by tusharsinare99** [microsoft/vscode#103672]
so to write cpp code in vs code i had installed minw-w64 .after that when i went to edit environment variable there could not opened the window of edit environment variable instead edit system variable window is opening.please provide me solution over it.
![Capture1](https://user-images.githubusercontent.com/60302068/88993320-751f3f00-d29a-11ea-841e-31c09ae36e20.PNG)

**Comment by Tyriar** [comment]
I don't understand the problem but it seems to be related to Windows, not VS Code?
