### ISSUE TITLE
Workspace extensions are not running in remote window

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#103608]
From the build - https://monacotools.visualstudio.com/Monaco/_build/results?buildId=83323&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=f43345f0-e90d-5fa7-e3aa-7e223f6f3b99

Remote integration tests are failing because remote extensions are not running.

Also confirmed in our test resolver window

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/10746682/88889951-2beed100-d241-11ea-8c5e-66f15849446a.png">

**Comment by sandy081** [comment]
@alexaubry  Added temporary fix 69f3970e843ffcc836a67780297f5585f3dc5485 to unblock the build. Please feel free to revert it and add proper fix.

**Comment by alexdima** [comment]
Sorry about that and thank you!

The fix was correct, as part of a refactoring I forgot to pass in `remoteExtensions` to the method call.
