### ISSUE TITLE
VsCode not detecting my internet

### ISSUE THREAD

**Issue by poojan0099** [microsoft/vscode#103653]
Issue Type: <b>Bug</b>

Deleted and installed VScode so many times but it is not detecting my internet 
market place is not working.
I don't know the issue please help!

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G    (2 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.89GB (1.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by poojan0099** [comment]
No

**Comment by poojan0099** [comment]
I don't know whats the main reason.
My wifi is working well on all other platforms.
I have never used any proxy.
This may be helpful :
![image](https://user-images.githubusercontent.com/48233985/89061843-11bd0c00-d383-11ea-8ffa-8b71f99b0b09.png)
![image](https://user-images.githubusercontent.com/48233985/89061900-2b5e5380-d383-11ea-95e0-c77e8d6d4d28.png)

**Comment by poojan0099** [comment]
@joaomoreno ?

**Comment by poojan0099** [comment]
@sandy081 bhaiya help chaiye ASAP.
Kuch nahi samajh raha

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by poojan0099** [comment]
- I can open the given link [https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default]. So I think there is no DNS issue.

- Also i did this: [https://1.1.1.1/dns/. ]

- But still the problem persist.

- So sharing all the files requested above:

[VSconsole.log](https://github.com/microsoft/vscode/files/5023726/VSconsole.log)

[Toggle Shared Process.log](https://github.com/microsoft/vscode/files/5023730/Toggle.Shared.Process.log)

[sharedprocess.log](https://github.com/microsoft/vscode/files/5023732/sharedprocess.log)

[log(window).log](https://github.com/microsoft/vscode/files/5023734/log.window.log)

**HOPE this helps and solves the ISSUE. Waiting for your COMMENT**

**Comment by sandy081** [comment]
@poojan0099 I am seeing following errors in your log

```
vscodeexperiments.azureedge.net/experiments/vscode-experiments.json:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:1670   ERR net::ERR_TUNNEL_CONNECTION_FAILED: Error: net::ERR_TUNNEL_CONNECTION_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2657:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
workbench.desktop.main.js:266 [Extension Host] Git installation not found.
t.log @ workbench.desktop.main.js:266
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:1670   ERR XHR failed: Error: XHR failed
    at XMLHttpRequest.r.onerror (file:///C:/Users/Jarvis/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:442:141)
workbench.desktop.main.js:6836 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:6836
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:6836 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:6836
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:6836 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:6836
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:6836 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:6836
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:6836 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:6836
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:6836 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:6836
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
workbench.desktop.main.js:6836 Error querying extensions gallery XHR failed
(anonymous) @ workbench.desktop.main.js:6836
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
```

ERR_TUNNEL_CONNECTION_FAILED happens when using proxy to connect to the internet. Please check your proxy settings.

**Comment by poojan0099** [comment]
Can anyone take access to my PC with TeamViewer or Anydesk and solve this
problem?
I have literally done and checked all the solutions and suggestions
described.
Please help!

**Comment by chrmarti** [comment]
Could you start VS Code with `--log-net-log=netlog.json`, search for an extension like in your screenshot and then post the created netlog.json here?

**Comment by poojan0099** [comment]
where should i type this command: `--log-net-log=netlog.json`
@chrmarti

**Comment by poojan0099** [comment]
![image](https://user-images.githubusercontent.com/48233985/89673364-d8951680-d903-11ea-9727-e4f86c86e7c1.png)

The Screen shot of Command Prompt.

**Comment by poojan0099** [comment]
@chrmarti ?

**Comment by poojan0099** [comment]
@chrmarti ?

**Comment by chrmarti** [comment]
I was out for a few days.

The JSON in the netlog.zip somehow seems corrupt. Could you check and upload again?

**Comment by poojan0099** [comment]
No need.
Problem Solved!
Was adding Python to PATH and found "http:proxy" = localhost.
Just deleted that line, and checked VScode and it was working fine.
