### ISSUE TITLE
search bar

### ISSUE THREAD

**Issue by yunusemreayhan** [microsoft/vscode#103621]
Issue Type: <b>Bug</b>

put a long search text into search everywhere input box. It is not possible to modify end of search string. i am using inside linux mate.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:15.161Z)
OS version: Linux x64 4.4.121-92.125-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (8 x 2593)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|0, 0, 0|
|Memory (System)|31.25GB (1.63GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
sourcetrail|ast|0.0.2
vscode-markdownlint|Dav|0.36.2
githistory|don|0.6.8
xml|Dot|2.5.1
gitlens|eam|10.2.2
bitbake|Eug|1.1.2
path-autocomplete|ion|1.15.0
vscode-filesize|mkx|2.1.4
python|ms-|2020.7.96456
cpptools|ms-|0.29.0
rust|rus|0.7.8
partial-diff|ryu|1.4.1
markdown-all-in-one|yzh|3.2.0

</details>

**Comment by roblourens** [comment]
Need more details
