### ISSUE TITLE
Get the editor for a TextDocumentContentProvider provided content

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#10379]
- VSCode Version: `Version 1.5.0-insider (1.5.0-insider)` 13b6e6d
- OS Version: `Version 10.11.6 (15G31)`

From a `TextDocumentContentProvider` is there any way to get access to the editor the content will be opened into?

I am trying to apply decorations to the provided content, but I haven't found a reliable (non-hack) way to get access to the opened editor. You can see my hack [here](https://github.com/eamodio/vscode-git-codelens/blob/master/src/contentProvider.ts#L42)

Also is there any way to control the order of "reference" in the peek ui? I'm attempting to hijack that UI to provide git blame history but I can't control the order -- so it will be very confusing :)

Thanks!

**Comment by jrieken** [comment]
> From a TextDocumentContentProvider is there any way to get access to the editor the content will be opened into?

No, that's not possible and because a document can be opened outside of an editor (`openTextDocument`) or in multiple editors it's not the right place to add it to the provider. Most likely the active editor will change but we also have a request for an event when any of the visible editors has changed.

> Also is there any way to control the order of "reference" in the peek ui? I'm attempting to hijack that UI to provide git blame history but I can't control the order -- so it will be very confusing :)

Do you implement a `ReferenceProvider` or do you just use the command to show the reference UI?

**Comment by jrieken** [comment]
The issue about an event when editors have changed: https://github.com/Microsoft/vscode/issues/643#issuecomment-230319130

**Comment by eamodio** [comment]
@jrieken How can I best provide text decorations for a custom document provided by my TextDocumentContentProvider?

I don't currently have a ReferenceProvider. I am triggering the command based of my code lens.

**Comment by jrieken** [comment]
Being a CodeLens provider is a good approach for this. So, is that you wanna control the order of the inline reference window? How they appear on the right hand side list and what editor is shown first?

![screen shot 2016-08-10 at 11 51 22](https://cloud.githubusercontent.com/assets/1794099/17550346/d555a51c-5ef4-11e6-9629-7c50d76c1a82.png)

**Comment by eamodio** [comment]
@jrieken Yes exactly -- the virtual doc is on the right pane of the peek, and the ordering I'm looking for is exactly what you are pointing to.

![image](https://cloud.githubusercontent.com/assets/641685/17558089/76b12bb0-5ee7-11e6-9425-39974bf62916.png)

I was also toying with the idea of trying to get a diff view in that right pane, but I don't even know if that is possible.

**Comment by jrieken** [comment]
Cool - so the sorting was definitely not designed for your use-case but I provide some internals that you can work with ;-) So the references are sorted by their [uri and range](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/referenceSearch/browser/referencesModel.ts#L166). Also, the widget tries to find and reveal the [nearest](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/referenceSearch/browser/referencesModel.ts#L215) reference. Not really made for this use-case but you might get it to work better with that knowledge.

I guess what you really want is this: https://github.com/Microsoft/vscode/issues/3220. It's currently not planned but it is likely to happen
