### ISSUE TITLE
Python Relative Path

### ISSUE THREAD

**Issue by erikb42** [microsoft/vscode#103758]
- VSCode Version: 1.47.3
- OS Version: macOS 10.15.5

Steps to Reproduce:

1. Run a Python script and it cannot find files in same directory when called with relative path.
2. Able to fix by using 'cd' in VSCode's terminal to navigate to the same working directory as my .py file.

Essentially when you hit run in VSCode, it runs all paths relative to where the Terminal thinks it is, not where the .py file is.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
