### ISSUE TITLE
Multi-line replace field jump-scrolls to the top at every input

### ISSUE THREAD

**Issue by graue70** [microsoft/vscode#103777]
- VSCode Version: 1.47.3
- OS Version: Linux x64 4.15.0-112-generic (Linux Mint 19.1)
- OS Version: Windows 10

Steps to Reproduce:

1. Open any folder in VS Code.
2. Press Ctrl + Shift + H for 'Replace in Folder'
3. Put any multi-line text in the Replace text box (press Shift + Enter to go to next line). It needs to have enough lines to require scrolling.
4. After every keyboard input (and some mouse inputs) the text box suddenly jumps to the top of the text which means that you don't see the cursor any more. If you keep typing, this creates a flickering effect in which you barely see what you are typing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/103952
