### ISSUE TITLE
Intellisense failure to match inserts random text

### ISSUE THREAD

**Issue by KevinBuchs** [microsoft/vscode#103702]
Issue Type: <b>Bug</b>

Editing a PlainText document. I type certain text and don't pay attention to what Intellisense might be showing. In certain cases and especially on "bad days" this can happen more often. Today, I was typing the word "Found" and it got replaced with "
tFjNot_4GK5Rq8dH1QlFfDJvJ2Duiuiwdj0yXCs9o827taGzW48WyINJ8A". I can see some letters from the word are matched, just single letters. Here is a video of the problem happening: https://drive.google.com/file/d/1GtVmXzhZHVoQiiaYtk6RwLUDH0jwH4-u/view?usp=sharing . Maybe I can attach it to this issue. A couple of Control-Z s and I have my desired text back and can go on, but it is still frustrating.

VS Code version: Code - Insiders 1.48.0-insider (15e798e081984a17eae00de91adf4479190d5ed2, 2020-07-28T10:39:40.074Z)
OS version: Linux x64 4.15.0-1091-oem

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1927)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|15.32GB (0.47GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 1a05d78c-3feb-4705-abd9-948bee78da39|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
insert-unicode|bru|0.8.0
bracket-pair-colorizer|Coe|1.0.61
vscode-ruby-test-adapter|con|0.7.1
insert-file|cre|0.9.0
vscode-markdownlint|Dav|0.36.2
githistory|don|0.6.8
xml|Dot|2.5.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
vscode-todo-plus|fab|4.17.1
url-encode|fle|1.1.0
go|gol|0.15.2
terraform|has|2.1.1
vscode-test-explorer|hbe|2.19.1
beautify|Hoo|1.5.0
vscode-insertdatestring|jsy|2.3.0
chatscript-language|kuz|1.3.0
npm-scripts|luk|1.0.0
markdown-shortcuts|mdi|0.12.0
vscode-azurefunctions|ms-|0.23.0
vscode-docker|ms-|1.4.1
csharp|ms-|1.22.1
vscode-dotnet-runtime|ms-|0.1.2
python|ms-|2020.7.96456
azure-account|ms-|0.9.1
cpptools|ms-|0.29.0
powershell|ms-|2020.6.0
azurerm-vscode-tools|msa|0.11.0
debugger-for-chrome|msj|4.12.9
vscode-json-editor|nic|0.2.3
try-material-icon-theme|raf|3.9.0
typescript-hero|rbb|3.0.0
ruby|reb|0.27.0
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
easy-compile|ref|1.2.1
LiveServer|rit|5.6.1
text-marker|ryu|1.11.0
markdown-preview-enhanced|shd|0.5.12
sort-lines|Tyr|1.9.0
vscode-icons|vsc|10.2.0
vscode-ruby|win|0.27.0

(8 theme extensions excluded)

</details>

**Comment by KevinBuchs** [comment]
Video:
[vscode-burp.zip](https://github.com/microsoft/vscode/files/5007712/vscode-burp.zip)

**Comment by jrieken** [comment]
Use the `editor.quickSuggestions` setting to control this, e.g disable it for plain text
