### ISSUE TITLE
Wrong editor focus when opening settings while code is minimized

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#10376]
Maybe related to the editor read-only issue...

OS X only
1. Have a single file open
2. Hit <kbd>Cmd M ,</kbd> (that is, keep <kbd>Cmd</kbd> held while you hit <kbd>M</kbd> and <kbd>,</kbd>. Code will minimise
3. Maximise Code. The user settings file will be read-only.

**Comment by joaomoreno** [comment]
@bpasero I can still repro this in the office machine, I'll show ya

**Comment by bpasero** [comment]
Dunno, I blame it on Chrome: Even the active element is the textarea in the right hand editor so I am not sure what kind of focus f**** up we end in.

**Comment by basarat** [comment]
I've had tabs in alm.tools for a while and occasionally it looks like *one monaco editor* is in focus but the input gets send to some other one :-/. Subscribing to this thread to see what happens :rose:

**Comment by bpasero** [comment]
Does not reproduce anymore.
