### ISSUE TITLE
Typing the 'src="."' source link of an image, is showing image list of another project!

### ISSUE THREAD

**Issue by flamurbeqiraj** [microsoft/vscode#103781]
Issue Type: <b>Bug</b>

Hello VSC team, Im facing 3rd time the same issue, I opend a new project, while working with it, I was about to add an image in HTML, when I write "src='.'" it shows me a list of files of another project, It should show me the list of the files that is currently opened!
Hope this was helpful enough.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.3
vscode-eslint|dba|2.1.8
jquerysnippets|don|0.0.1
php-intellisense|fel|2.3.14
beautify|Hoo|1.5.0
sftp|lix|1.12.9
vsliveshare|ms-|1.0.2478
live-sass|rit|3.0.0
LiveServer|rit|5.6.1

</details>

**Comment by aeschli** [comment]
Can you add a screenshot that also shows the VSCode file explorer?
