### ISSUE TITLE
How to integrate terminal whth babun on windows?

### ISSUE THREAD

**Issue by applee** [Microsoft/vscode#10373]
- VSCode Version: 1.4.x
- OS Version: Windows 7

If I config the terminal.shell with minity.exe, it open a new shell window not in vscode terminal.How can I config it?

**Comment by jhasse** [comment]
You'll need to set bash or zsh instead of minity.exe. It's a little tricky on Windows atm, have a look at #8429.

**Comment by applee** [comment]
yeah, I have set zsh.exe instead, but it can not change to path to current folder.

**Comment by jhasse** [comment]
This is what I use in `tasks.json`:

```sh
	"windows": {
		"command": "C:\\msys64\\usr\\bin\\bash",
		"args": ["-lc", "cd \"\"${workspaceRoot}\"\" && waf $0 && $@"]
	},
```

But for the integrated terminal you'll need to manually change the path until #8429 is fixed.

**Comment by applee** [comment]
Thank you.

**Comment by superxp1412** [comment]
I found a better way to make babun initialise from current directory.
Add on command in ~/.babunrc : 
cd $OLDPWD

**Comment by ball6847** [comment]
This is my workaround on this issue.

```json
{
  "terminal.integrated.shell.windows": "C:\\Users\\username\\.babun\\cygwin\\bin\\zsh.exe",
  "terminal.integrated.shellArgs.windows": ["-l"]
}
```

To make it initialize from current directory append this code to ~/.babunrc or ~/.zshrc

```sh
# vscode shell integration
[ ! -z $VSCODE_CWD ] && cd $VSCODE_CWD
```

Hope this help.

**Comment by Suzal3579** [comment]
@superxp1412  you made my day sir. Thanks a lot 👍
