### ISSUE TITLE
Tabs vanish when using diff view

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode#10378]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Use vscode with a git repo
2. Change a file
3. go to diff view
4. select file to view diffs
5. Tabs vanish (maybe wanted?)
6. go to workspace explorer
7. tabs are gone as well

The tabs are coming back, as soon as one closes the diff view.

Diff view:
![diff](https://dl.dropboxusercontent.com/spa/agn3r6rkwi4rxn7/gfsfpnb7.png)

Explorer:
![explorer](https://dl.dropboxusercontent.com/spa/agn3r6rkwi4rxn7/fycm20em.png)

and as soon as the diff view is closed:

![yay](https://dl.dropboxusercontent.com/spa/agn3r6rkwi4rxn7/9_umr_ti.png)

**Comment by buehler** [comment]
Hey @jrieken 
Yep, just confirmed. It's caused by the `vscode-icons` plugin. 
Nevermind ;-)

Cheers

**Comment by jrieken** [comment]
This is caused by the icons extension changing the internals of VS Code. We are in the process of adding real API, until then I would recommend not using it.

**Comment by robertohuertasm** [comment]
@buehler This issue was already fixed in [#153](https://github.com/robertohuertasm/vscode-icons/issues/153).

**Comment by buehler** [comment]
@robertohuertasm Thanks! :-)
