### ISSUE TITLE
How to detect if a line is visible (in the Viewport)?

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#10374]
Hi,

Is there any public API to detect if a `line`, `range` or `position` is currently _visible to the user_ (in the Viewport)? I'm naming _Viewport_ because that's how it appears in `vscode.TextEditorRevealType` (`InCenterIfOutsideViewport`).

Thanks in advance

**Comment by jrieken** [comment]
That's currently not possible. @alefragnani Can you detail on your use-case? We try to abstract all view'ish things away such that things are easier to reason about

closing this as a dup of #588

**Comment by alefragnani** [comment]
Hi @jrieken ,

My use-case is exactly the same as #588. Like @jsturtevant, the intention was to create the AceJump extension for VSCode. 

By definition (https://www.emacswiki.org/emacs/AceJump), it only highlights (decorates) the chars/words in the visible area (Viewport). 

And for the _highlight_ I was thinking to use the newly available `before` decorator API, since I cannot create highlights like those Visual Studio screenshots. Or can I?

Thanks

**Comment by jrieken** [comment]
That's pretty cool extension... With the enhanced decorations you can do the _before_ and _after_ trick but you won't know anything about the viewport. That will harm perf but I see how you'll quickly run out of single character jumps

**Comment by alefragnani** [comment]
Thanks for the input. It will end up bit different from the original extension, but that's not a big deal :+1: 
 
Since it will be no more than 36 matches (26 characters and 10 numbers), starting from current line going up and down, performance should be no problem. Adding to that, the fact that it will use the decorator API, it should be even smoother :smile:

**Comment by staltz** [comment]
Hi, I have a similar use case. Can I ask what was meant with "*With the enhanced decorations you can do the before and after trick*", or links to more explanations on that?

**Comment by alefragnani** [comment]
@staltz It's based on `before` and `after` properties added to `DecorationRenderOptions` interface. You can get more details in https://code.visualstudio.com/docs/extensionAPI/vscode-api#ThemableDecorationRenderOptions.

**Comment by staltz** [comment]
Thanks

**Comment by jsturtevant** [comment]
@alefragnani do you have a link to the extension you are developing?  never got around to finishing it my self. excited to see someone else developing it and would love to use it 👍

**Comment by alefragnani** [comment]
@jsturtevant sorry to say, but it is still just an _idea_. I paused the dev after playing with this decorator and didn't look at the _keyboard handling_ yet (_vim/emacs style_). Unfortunatelly nothing usefull/usable to share. I still have some other projects to finish before going back to this one.

I didn't know you were the author of AceJump for VS, and was creating it to VSCode too, until reference your issue here. In fact I would be glad to help you to migrate the extension. So, if you need any help, we could work together :+1:

**Comment by staltz** [comment]
Yeah I also wanted to build a similar plugin for VSCode, perhaps I could help too. Just don't know where to get started since I didn't understand the "decorator hack".

**Comment by wmaurer** [comment]
@alefragnani, @jsturtevant, @staltz I published an early (slightly buggy, but hopefully usable) version of a jumpy extension https://marketplace.visualstudio.com/items?itemName=wmaurer.vscode-jumpy

As noted in this issue, there's no way of finding the visible lines in the currently visible editor right now (hopefully #588 will trigger an improvement to the API). Right now I just add and subtract and hardcoded number of lines from the current cursor position.

I'll be improving this extensions over the next days and then as VSCode's API improves.

**Comment by alefragnani** [comment]
Hi @wmaurer , I just installed your **Jumpy** extension and, may I say, it's awesome, congratulations 🎉  .

I'm starting to learn CSS and had no idea I could _move_ the decorator to stay _over_ the text, instead of using the pre-defined area. And the use of _pre created_ SVG was clever 😄 .

It was stable enough for me (no crash). I just missed two things, and I would be glad to make PRs, if you agree:

1. Some keybinding to cancel Jumpy state (like `ESC`)
1. The _word regex_ is based on _CamelCase_ format. I would like to be _case insensitive_. But for this, I think a better option is to put the word regex as `User Setting`, just like Atom. 

The **AceJump** extension is a bit different in _navigation_, but the _core concepts_ are the same. Your extension should work as a great start 👍

**Comment by wmaurer** [comment]
Hi @alefragnani, thanks for the nice words!

You can cancel Jumpy state by with a non `a-z` key, e.g. `space`, or `enter`. `ESC` doesn't work right now without an extra command binding as I'm intercepting command `type` which doesn't recognise `ESC`. I'll add a note to the `README` so that users know.

I've already implemented the *regex* as `User Setting` (thanks for the offer of a PR!). I'll release this feature along with a bug fix in the next day or so.

If you have other feedback, feel free to raise an [issue](https://github.com/wmaurer/vscode-jumpy/issues)

Cheers

**Comment by wmaurer** [comment]
@alefragnani The default regex is now case insensitive, but you can also change it via a setting. You can also map `extensions.jumpy-exit` to `ESC` in your `keybindings.json`. Both features are described in the README.
