### ISSUE TITLE
Terminal not launching

### ISSUE THREAD

**Issue by hushadi** [microsoft/vscode#103715]
Issue Type: <b>Bug</b>

hello, 
I'm a student at Abu Dhabi University and I'm trying to develop using Visual Studio Code but the terminal would not open. i get this error "The terminal process "C:\WINDOWS\System32\wsl.exe" failed to launch (exit code: 4294967295)" 
Your help is much appreciated.
Hussein Majid

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.44.4
powershell|ms-|2020.6.0

</details>

**Comment by Tyriar** [comment]
Do you have wsl installed? Try changing the default shell

![image](https://user-images.githubusercontent.com/2193314/89072456-76e61280-d32d-11ea-9cd3-02bb48e83377.png)

**Comment by hushadi** [comment]
I got it to work
thank you
