### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by sunny7903814947** [microsoft/vscode#103771]
Issue Type: <b>Bug</b>

error in running the program as
hi = hello sunny
print(hi)

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.85GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
python-extension-pack|don|1.6.0
MagicPython|mag|1.1.0
python|tht|0.2.3
vscodeintellicode|Vis|1.2.9
jinja|who|0.0.8

</details>

**Comment by weinand** [comment]
/needsMoreInfo including what language are you debugging, a set of clear repro steps, and what exact error are you seeing (screenshot)
