### ISSUE TITLE
Tab size Issue with pipe() arguments on separate lines

### ISSUE THREAD

**Issue by ryanbuening** [microsoft/vscode#103720]
- VSCode Version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Set `"editor.tabSize": 4`
2. Set `"editor.insertSpaces": true`
3. Copy below code to a new TypeScript file

```
import { catchError, tap, map } from 'rxjs/operators';

export class ProductService {
    productsWithCategory$;
    productsUrl;

    // comment out starting on the line below
    products$ = this.http.get<Product[]>(this.productsUrl)
        .pipe(
            tap(data => console.log('Products: ', JSON.stringify(data))),
            catchError(this.handleError)
        );
    // to here to fix the tabbing

    selectedProduct$ = this.productsWithCategory$

}
```

4. Do the following:

![tab repro](https://user-images.githubusercontent.com/812974/89067486-60e04e00-d33d-11ea-885c-76a74399d391.gif)

**Expected result**
- Tabbing should only insert 4 spaces.

**Actual result**
- Tabbing inserts 8 spaces

I'm assuming it is doing this to match where the pipe arguments are. If the pipe arguments are all on one line, tabbing works as intended.

Does this issue occur when all extensions are disabled?: Yes

Related StackOverflow post [here](https://stackoverflow.com/questions/63180913/vs-code-tab-size-on-an-empty-line).

**Comment by rebornix** [comment]
I'm not able to reproduce this issue in latest Insiders, can you try again?

**Comment by ryanbuening** [comment]
Still happening on Insiders 1.51.0.

![issue](https://user-images.githubusercontent.com/812974/95863435-2c701180-0d32-11eb-850c-6a8d2cc94fa3.gif)

**Comment by ryanbuening** [comment]
@rebornix what other information is needed?
