### ISSUE TITLE
render issue

### ISSUE THREAD

**Issue by memohit18** [microsoft/vscode#103789]
Issue Type: <b>Bug</b>

the software  always look like the visual image is breaking like in pixel

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.3
cortex-debug|mar|0.3.7
python|ms-|2020.7.96456
cpptools|ms-|0.29.0
particle-vscode-core|par|1.12.2
particle-vscode-pack|par|1.12.2
particle-vscode-snippets|par|1.12.2
LiveServer|rit|5.6.1
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by memohit18** [comment]
![Uploading Screenshot (15).png…]()

**Comment by memohit18** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/23547848/89127210-7bffb900-d509-11ea-8e6c-54529e9966e0.png)

**Comment by deepak1556** [comment]
Does this happen for any theme ?

can you check if the issue happens with exploration build https://az764295.vo.msecnd.net/exploration/45f2f912b8c3bdf45bb92dc613b902136a1b60ed/VSCodeUserSetup-x64-1.49.0-exploration.exe

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/93356

you can workaround with disabling hardware acceleration.
