### ISSUE TITLE
Visual Studio code is not responding. it shows window is not responding

### ISSUE THREAD

**Issue by masternikhilgupta** [microsoft/vscode#103744]
when i am writing/running a code in visual studio code, it shows window is not responding. i have uninstall the Visual studio code & reinstall it, but the problem has not been solved yet.

**Comment by masternikhilgupta** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/69069049/89095896-8ded3900-d3ef-11ea-83c2-b2a5370d23cc.png)

**Comment by deepak1556** [comment]
Can you check if the freeze happens with exploration build thats on a newer runtime https://az764295.vo.msecnd.net/exploration/f0e1fbf4cb8c4c27d6290f0310f5a4d63597cd21/VSCodeUserSetup-x64-1.48.0-exploration.exe

If the freeze continues, can you also check with `--disable-extenions`

**Comment by masternikhilgupta** [comment]
> Can you check if the freeze happens with exploration build thats on a newer runtime https://az764295.vo.msecnd.net/exploration/f0e1fbf4cb8c4c27d6290f0310f5a4d63597cd21/VSCodeUserSetup-x64-1.48.0-exploration.exe
> 
> If the freeze continues, can you also check with `--disable-extenions`

I have tried, but the same problem exists again. i have attached the Screenshot also.
![Screenshot (24)](https://user-images.githubusercontent.com/69069049/89657960-8cd67300-d8eb-11ea-919f-8844da4d5cca.png)

**Comment by masternikhilgupta** [comment]
kindly solve my issues. 
my vs code is not responding.

**Comment by moizgh** [comment]
I have started see this too.
![image](https://user-images.githubusercontent.com/25937675/92178949-b5ca2500-ee11-11ea-9d76-32a80918a829.png)

**Comment by janw** [comment]
Started seeing this here as well on macOS. For me it seems to be related to the scroll back buffer of the integratedTerminal; scrolling back as well as running commands with large amounts of output cause the window to freeze. Disabling extensions did not solve the issue.

<details><summary>Version: 1.49.2</summary>
<pre>
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z (6 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
</pre>
</details
