### ISSUE TITLE
Undo Bug

### ISSUE THREAD

**Issue by BAbdulBaki** [microsoft/vscode#103763]
Issue Type: <b>Bug</b>

If you modify the code outside of VSCode, VSCode automatically updates the changes (GOOD).  However, the undo commands are no longer valid (BAD) and they need to be reset.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz (8 x 3602)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (56.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
pip-packages|etm|0.4.3
latex-workshop|Jam|8.11.1
language-julia|jul|1.0.0
MagicPython|mag|1.1.0
latexcompile|mat|0.7.1
csharp|ms-|1.22.1
python|ms-|2020.7.96456
cpptools|ms-|0.29.0
powershell|ms-|2020.6.0
python|tht|0.2.3
language-j|tik|0.4.0
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.9
jinja|who|0.0.8

</details>

**Comment by alexdima** [comment]
@BAbdulBaki I could not reproduce. I have tried the following steps:
1. open a file
2. edit the file from another process
3. undo in the file

![Kapture 2020-08-05 at 14 44 23](https://user-images.githubusercontent.com/5047891/89414133-340bac80-d72a-11ea-8907-7c7e75cf3a17.gif)

**Comment by BAbdulBaki** [comment]
Try changing the file from a different application, say Notepad, while it's still open in VSCode.

**Comment by alexdima** [comment]
@BAbdulBaki The terminal is a separate application. Here I am trying with a separate GUI application, and I still cannot reproduce:

![Kapture 2020-08-05 at 15 17 53](https://user-images.githubusercontent.com/5047891/89417403-ee051780-d72e-11ea-9875-b0d4ea075e4f.gif)

**Comment by BAbdulBaki** [comment]
It's flakey for me.  It works for a few edits now, but still fails for multiple edits back and forth between apps. I really should stop using multiple apps.

**Comment by alexdima** [comment]
Please let me know if you find some repro steps, AFAIK we listen to file changes and compute a diff between the new state on disk and the state in memory and push an edit to bring the file in memory to the state on disk (which also lands on the undo stack).
