### ISSUE TITLE
Integrate bash

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#1037]
I'm finding VS Code is fairly hard to use efficiently without an integrated terminal.
I have to type make repeatedly in a separate bash window (remembering to hit ctrl-s every time!), and from there, I can't double-click on compile errors to go to the line+file.
At a minimum, it would be good to have an integrated shell, and support clicking errors to go to the source.

Ideally, once integrated, a macro could: save all -> execute `make`, and productivity would increase substantially.

**Comment by egamma** [comment]
Have you tried to configure a task https://code.visualstudio.com/docs/editor/tasks, then you can trigger make using a short cut, and navigate from errors shown in the output window inside Code, back to your code

**Comment by TurkeyMan** [comment]
Awesome, thanks for the headsup.

**Comment by bbenoist** [comment]
@TurkeyMan If you need to run more rare commands, I've just released an extension which allows you to run commands from vscode.
See https://marketplace.visualstudio.com/items?itemName=bbenoist.shell for more info

**Comment by Tyriar** [comment]
Integrated terminal issue: https://github.com/Microsoft/vscode/issues/143

**Comment by willin** [comment]
+1 https://atom.io/packages/terminal-panel

**Comment by Tyriar** [comment]
I'm going to close this as a duplicate of #143
