### ISSUE TITLE
Tab size is wrong inside tooltips

### ISSUE THREAD

**Issue by kaiyoma** [microsoft/vscode#103723]
Issue Type: <b>Bug</b>

I have my tab size set to 2 spaces, but when I hover over source code and get a (TypeScript) tooltip, the tab size for the code inside the tooltip is 4 spaces. I've looked everywhere and I can't find a setting for this or an open issue.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|1.4.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.1.3
gc-excelviewer|Gra|3.0.39
jenkins-declarative-support|jmM|0.1.0
vscode-colorize|kam|0.8.17
code-groovy|mar|0.1.2
material-icon-theme|PKi|4.2.0
code-settings-sync|Sha|3.4.3
vscode-stylelint|sty|0.84.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
opened https://github.com/microsoft/TypeScript/issues/40142 to track upstream
