### ISSUE TITLE
I want to use macOS key bindings under linux

### ISSUE THREAD

**Issue by yueduz** [microsoft/vscode#103776]
There are too many emacs keybinding extensions, but they are not very easy to use. And macOS keyboard binding and emacs style are similar, so can you provide an option to use macOS keyboard binding in linux?

All emacs key binding extensions can only be used in the main text edit box. They are not available in the command bar and search bar.

--------------------Translate from Chinese to English using Google

有太多的emacs键绑定扩展,但是都不怎么好用.而macOS的键盘绑定和emacs的风格是相似的,所以能不能提供一个选项在linux也能使用macOS的键盘绑定.

所有的emacs 键绑定扩展都只能在主文本编辑框内使用.在命令栏和搜索栏无法使用.

**Comment by rebornix** [comment]
You can use Emacs key map https://marketplace.visualstudio.com/search?term=emacs&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by yueduz** [comment]
The emacs extension cannot be used at the red line mark of the picture
![2020-08-03 08-21-26 的屏幕截图](https://user-images.githubusercontent.com/1448159/89135783-797d7d80-d562-11ea-9f48-e16978250ce3.png)
