### ISSUE TITLE
Make UI clearer in Output tab about which log channels are relevant to user's project

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#103716]
When developing a Vue.js app in a remote dev container, I wanted to use console.log messages throughout the development process to help me iterate upon and debug my app. However, I wasn't sure where console.log messages appear. 

When I navigated to the Output tab in the integrated terminal, there were many options. I clicked through all of them when I ran my program, but wasn't sure where to see my logs, and I wasn't successful in locating them:

![image](https://user-images.githubusercontent.com/25310137/89061301-58761c00-d319-11ea-890b-f72e7593797c.png)

Upon discussions with @chrmarti, I got feedback that it depends on where they run, i.e. they could go to the browser's console if run in the browser, or they could go to the Tasks output channel or an integrated terminal if they run in a Node server, depending on how/where Node is started.

The UI could be clearer about which channels are relevant to the user's project and which are relevant for diagnosing VS Code. Perhaps some kind of sorting, division into a "relevant" category (potentially related to #94681 if it would help users see which channels are relevant to them), or alternative wording would help.

**Comment by chrmarti** [comment]
/fyi @sandy081 (since this might otherwise be closed unseen by the feature workflow)
