### ISSUE TITLE
Hitting "Escape" when in various fields does not "leave focus" as one would expect

### ISSUE THREAD

**Issue by macintacos** [microsoft/vscode#103728]
It doesn't seem like VSCode is consistent with its treatment of the `ESC` key when you're in a text input field.

For the way that I'd expect it to work, let's take the Source Control panel as an example. When typing a commit message, if I hit `ESC`, the text input field is no  longer the focus, and thus VSCode's keybinding `when` clause sets `inputFocus` to false, which works as expected. [Here's a gif explaining what I mean](https://p-37FYgJ.b1.n0.cdn.getcloudapp.com/items/geuzk9y6/Screen%20Recording%202020-07-31%20at%2017.41.07.gif?v=5c73a159abe23ba4e6f849719808fb46).

There are a number of input fields in the UI that don't behave this way. When pressing `ESC`, either nothing happens, or the text is selected but focus remains in the text field. [Here's a gif explaining what I mean, using the "Search Extensions in Marketplace" text field as an example](https://p-37FYgJ.b1.n0.cdn.getcloudapp.com/items/WnuJ1jPE/Screen%20Recording%202020-07-31%20at%2017.49.23.gif?v=52ab373b68aa4e7ca1d2438d4e587057).

The text fields that I have found that exhibit this behavior are:

1. Search field in the "Extensions: Marketplace" pane
2. Global "Search" pane
3. "Problems" pane's filter box

There might be others, the above isn't an exhaustive list. Is any of this intentional?

### Version Details

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

### Steps to Reproduce

1. Put your text cursor in one of the text fields mentioned above.
2. Press `ESC`

I would typically expect that `ESC` would cause the input field to lose focus. In these fields, it doesn't.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by macintacos** [comment]
Same behavior is exhibited in the "Settings" search text field and the "Keyboard Shortcuts" search text field. Input doesn't leave the field after hitting `ESC`.

**Comment by davidkharbin** [comment]
I'm having this issue too, but only on my Linux machine.  The Linux PC is a ThinkPad X1 Carbon Gen 6 with Manjaro.  I first noticed it a couple weeks ago when it stopped working with the VIM extension, but I soon noticed the function of the escape key was not working globally within VSCode.

Still works fine on my Windows box.

**Comment by macintacos** [comment]
To clarify, the `ESC` key works fine in the editor for me; just the behavior of input fields seems to be not what I would expect across the board. It doesn't seem to be consistent across all text input fields in VSCode.

**Comment by joaomoreno** [comment]
The decision to lose focus on Escape is a per-feature decision. _Consistency_ will be hard to achieve, since the expected result depends a lot on the main user interact around the feature.

You even mention that losing focus is expected on SCM. That was actually an accidental regression which was fixed last week: it should not lose focus at all.

**Comment by macintacos** [comment]
That's a shame. 

Would opening a feature request to add a command to "leave text input focus" make sense then? I'd really like this functionality, but I don't know if it already exists in VSCode or not. @joaomoreno

**Comment by joaomoreno** [comment]
This is strange since that behavior doesn't align with most expectation surrounding text areas. Chrome URL bar, Github comment text box, etc. None of them have <kbd>Escape</kbd> losing focus.

**Comment by macintacos** [comment]
I guess it's just my expectations then when I'm in a text editor that I never noticed before until I needed it. 

Do you know if such a command to "lose focus if in input field" exist? If not, I'll open an issue for it, because it'd be really useful for my workflow. I'll explain more in the issue that I open why that'd be useful for me.

**Comment by macintacos** [comment]
@joaomoreno I won't ask for this issue to be reopened because I already opened a new issue to ask for this functionality to be added as a bespoke command (which I think will satisfy all parties involved), however I did some more testing across many applications on the Mac and found that there are _many_ places where `Escape` leaves text focus. In fact, at least on the Mac, apps that don't do it seem like outliers in this regard. Here's what I found based on my testing:

## Applications where, if you're in a text field, a majority of the time the user is spending is in a field where pressing `Escape` will leave/unfocus the text field you're in

This is largely true for these apps, some exceptions - this is by no means an exhaustive list:

- [OmniFocus](https://www.omnigroup.com/omnifocus/)
- [Things 3](https://culturedcode.com/)
- [Finder](https://support.apple.com/en-us/HT201732)
- [Forklift](https://binarynights.com/)
- [Alfred](https://www.alfredapp.com/)
- [Due](https://www.dueapp.com/)
- [Tot](https://apps.apple.com/us/app/tot/id1491071483?mt=12)
- [Notion](https://www.notion.so/desktop)
- [Maps](https://support.apple.com/guide/maps/get-directions-mps4d8a6bd2f/mac)
- [Photos](https://www.apple.com/macos/photos/)
- [Dash](https://kapeli.com/dash)
- [Safari](https://www.apple.com/safari/)
- [Mailplane](https://mailplaneapp.com/) (granted, this is essentially just a native app wrapping around the Gmail website, but `Escape` works as expected pretty much anywhere and everywhere)
- Most websites with textareas/input fields like Github (you mentioned that this doesn't work in Github comment boxes, but it seems to work fine for me?. I'd say a majority of websites work as expected when you hit `Escape` (the textarea/input field you're in loses focus).

Some of these apps, you'd have to hit `Escape` twice - once would clear the field if there was text in it, the second time it would leave focus (the Maps app comes to mind). I still count this as being able to hit `Escape` to lose focus.

## Applications where, if you're in a text field, a majority of the time the user is spending is in a field where pressing `Escape` will do nothing

This is largely true for these apps, with some some exceptions - this is by no means an exhaustive list:

- [VSCode](https://code.visualstudio.com/)
- [Slack](https://slack.com/) (the main function it performs, sending messages, doesn't allow you to lose focus when hitting `Escape`; most other input fields can be unfocused/dismissed by hitting `Escape` though, so honestly I could be persuaded to move this to the other group)
- [Discord](https://discord.com/) (this falls into the same group as Slack; most fields unfocus/dismiss with `Escape`, but it's main functionality (sending messages) does not.)
- [HEY](https://hey.com/apps/) (only seems to work in search fields, not in compose view)
- [Ulysses](https://ulysses.app/) (main text entry you can't `Escape` to unfocus, but in other fields like entering keywords, searching for things, you can unfocus)
- [Messages](https://support.apple.com/en-us/HT202549) (main text you can't `Escape` to unfocus, search fields you can)

Lastly, I'd like to note a common theme for most apps that fell into the second camp were applications where the main function was entering text, which makes sense; I think that a user could reasonably expect in a text editor like VSCode or a messaging app like Slack, hitting `Escape` shouldn't lose focus if you're typing out a message or writing some code. _However_, this isn't a universal rule in those applications; pretty much every application that did this (like Slack/Discord/Hey/Messages/Ulysses/etc.) did NOT follow the same rule in what I would call "supplementary" fields, which is what I'd categorize something like the Search Panel or the SCM commit message field in VSCode.

As I said initially, at this point I think that everyone would be satisfied if there were just a command that would enable this functionality in VSCode (I'd map it to `Escape` everywhere I could, as you can imagine 😄), so I'm fine with #103845 being "the way forward". However (again, at least on macOS) this seems to be behavior that is not in line with the rest of the OS, at least from my testing.
