### ISSUE TITLE
Saving untitled file always defaults to .txt

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode#103704]
Version: 1.48.0-insider (user setup)
Commit: c9a2f78283b6e5ef708fb8869e2a5adaa476e42f
Date: 2020-07-31T05:52:44.330Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create new untitled file
2. Change language to something else - like SQL
3. Save file

Expected : File save dialog suggestions SQL extension by default (current behavior in stable)

![image](https://user-images.githubusercontent.com/28519865/89052147-214c3e80-d30a-11ea-8f3d-1c7c2a529831.png)

Actual : .txt extension is suggested by default 

![image](https://user-images.githubusercontent.com/28519865/89052232-43de5780-d30a-11ea-86f1-fbcc05f1c6d2.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
I feel https://github.com/microsoft/vscode/commit/9f7139a4d71c4861b01915b8dc631ffb65910b5b addressed this but we should backport to stable.
