### ISSUE TITLE
Conflict between setting "Editor: Font Size" and "Editor: Mouse Wheel Zoom"

### ISSUE THREAD

**Issue by Li-YangZhong** [microsoft/vscode#103736]
Issue Type: <b>Bug</b>

After I turned on "Editor: Mouse Wheel Zoom" and modified the font size using the Mouse Wheel, the setting on "Editor: Font Size" will not work properly anymore.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (1.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
LiveServer|rit|5.6.1

</details>

**Comment by alexdima** [comment]
@Li-YangZhong The mouse wheel zoom is a multiplier applied to font size. So if you configure `editor.fontSize: 16` and zoom in once with ctrl + mouse wheel, the effective font size will be `16 * 1.1`, etc.

**Comment by Li-YangZhong** [comment]
Good explanation. Thanks for the tip, bro @alexdima
