### ISSUE TITLE
Dark start window

### ISSUE THREAD

**Issue by denji** [microsoft/vscode#103767]
At the start of the Visual Code Studio (1.47.3), the window is white color effect, but the theme is dark.
It's a little disappointing.

```
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.0-3-arch
```

**Comment by aeschli** [comment]
Can you explain more, maybe a screenshot/cast?

**Comment by denji** [comment]
@aeschli https://i.imgur.com/j7GrihQ.mp4

**Comment by aeschli** [comment]
When VSCode is closed, we remember the background color and use that the next time for the initial window color. Can it be that you had a white theme when you closed VSCode the last time?

Because I don't see what you are seeing (Ubuntu 18.04 in my case)

**Comment by denji** [comment]
@aeschli I've never used white themes, xfce4 has a dark theme, too.

https://aur.archlinux.org/packages/visual-studio-code-bin
PKGBUILD https://aur.archlinux.org/cgit/aur.git/tree/?h=visual-studio-code-bin
