### ISSUE TITLE
Debug adapter process has terminated unexpectedly when trying to debug an extension

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#10377]
- VSCode Version: `Version 1.5.0-insider (1.5.0-insider)` 13b6e6d096c479f4174d025d647385054b1e43d7
- OS Version: `Version 10.11.6 (15G31)`

Steps to Reproduce:

1.  Open any extension and try to debug it
2. Results in `Debug adapter process has terminated unexpectedly`

This was working perfectly until the latest insiders build.

**Comment by johnfn** [comment]
Confirming I'm seeing same thing - definitely introduced in the latest version.

**Comment by weinand** [comment]
The module 'request-light' is missing from node-debug. I'll fix the gulpfile...

**Comment by NikosEfthias** [comment]
the same on mac

**Comment by weinand** [comment]
I've started new insider builds...

**Comment by weinand** [comment]
In the meantime you can just do a `npm install` in the insider's node-debug extension folder (and ignore the error about the missing gulp file).
After that extension host debugging should work fine.

**Comment by weinand** [comment]
New insider builds are available that fixes the issue.

**Comment by sandy081** [comment]
Verified that able to debug an extension.
