### ISSUE TITLE
Cannot format multiple selections

### ISSUE THREAD

**Issue by aicest** [microsoft/vscode#103745]
- VSCode Version: 1.47.3
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. use `ctrl+d` select multiple
2. run `format selection` to format them

Demo: https://webmshare.com/play/eadOq

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
To verify:

* use TypeScript or another language for which you have selection formatting support
* select multiple code snippets and run "Format Selection"
* make sure all selections are formatted in a single operation, e.g a single undo operation is enough to undo the formatting changes
* make sure empty selections are expanded to the whole line
* make sure selections on the same line works as well as selections on different lines
