### ISSUE TITLE
Problem with Installer of Visual Studio Code for Java developers

### ISSUE THREAD

**Issue by pawarashish564** [microsoft/vscode#103786]
- VSCode Version:1.47.3
- OS Version:Windows 10 version 1909 (OS Build 18363.959)

# Installer of Visual Studio Code for Java developers 
I'm using installer for java setup for VSCode . I had some issues with Java autocompletion.

![image](https://user-images.githubusercontent.com/29516182/89125795-984a2880-d4fe-11ea-8a54-2fb5f998ed0c.png)

## I'm getting this error .
![image](https://user-images.githubusercontent.com/29516182/89125811-ae57e900-d4fe-11ea-9f19-007686f6bbf5.png)

Do I have to restart vscode or do something else to do this ?

Does this issue occur when all extensions are disabled?: IDK

**Comment by joaomoreno** [comment]
Please provide this feedback to the Visual Studio Code for Java developers team.

**Comment by pawarashish564** [comment]
Where should I give this feedback ?
