### ISSUE TITLE
key press issue

### ISSUE THREAD

**Issue by pankajsaboo** [microsoft/vscode#103749]
After opening of Visual code studio, Unable to type in editor. Only few keys like n,j, space, enter are working. 

Memory - 7.7GiB
Processor - Intel core i5-5200 CPU @ 2.20GHzX4
Graphics - Mesa Intel HD Graphics 5500
Disk Capacity - 500 GB

OS Name - Ubuntu 20.04LTS
OS Type - 64-bit
GNOME Version - 3.36.2

**Visual code details**
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-40-generic snap
Windowing system - X11

**Comment by alexdima** [comment]
Does this reproduce when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)
