### ISSUE TITLE
Typescript Extension Failure

### ISSUE THREAD

**Issue by koolamusic** [microsoft/vscode#103780]
Issue Type: <b>Bug</b>

VScode Typescript Extension fails on start

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.4.12-100.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2865)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 2|
|Memory (System)|15.56GB (5.01GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-apollo|apo|1.16.6
clojure|avl|0.13.1
markdown-preview-github-styles|bie|0.1.6
vscode-styled-jsx|bla|1.5.0
phpserver|bra|2.4.6
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.35.2
vscode-eslint|dba|2.1.1
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|2.8.0
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
minify|Hoo|0.4.3
githd|hui|2.2.4
smarty|imp|0.3.0
vscode-react-typescript|inf|1.3.1
diff-tool|jin|0.0.1
vscode-styled-components|jpo|0.0.29
rainbow-csv|mec|1.7.0
vscode-language-babel|mgm|0.0.27
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
vscode-docker|ms-|1.1.0
mssql|ms-|1.9.0
python|ms-|2020.3.71659
remote-containers|ms-|0.101.1
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.42.4
vscode-remote-extensionpack|ms-|0.20.0
sublime-keybindings|ms-|4.0.7
vsliveshare|ms-|1.0.2478
sqltools|mtx|0.22.11
sqltools-driver-mysql|mtx|0.1.1
sqltools-driver-pg|mtx|0.1.0
sqltools-driver-sqlite|mtx|0.1.0
deepdark-material|Nim|3.2.1
react-proptypes-intellisense|OfH|1.0.3
es6-css-minify|olb|3.3.2
material-icon-theme|PKi|4.2.0
heroku-command|pko|0.0.8
vscode-graphql|Pri|0.2.14
prettier-now|rem|1.4.9
LiveServer|rit|5.6.1
mdx|sil|0.1.0
js-jsx-snippets|sky|10.1.0
autoimport|ste|1.5.3
html-preview-vscode|tht|0.2.5
clojure-warrior|ton|0.2.4
vscodeintellicode|Vis|1.2.9
vscode-wakatime|Wak|4.0.0
vscode-import-cost|wix|2.12.0
markdown-all-in-one|yzh|3.2.0
material-theme|zhu|3.8.5
html-css-class-completion|Zig|1.19.0

(5 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
You are on many months old VS Code install

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by koolamusic** [comment]
I updated this now, it does not happen again, I guess I needed to update the app.
