### ISSUE TITLE
Variable scopes are collapsed hitting BPs in VS Code

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103707]
https://github.com/microsoft/vscode/issues/100368#issuecomment-659384604

**Comment by connor4312** [comment]
I'm not sure if @isidorn fixed anything recently but I tried to reproduce that collapsed scope issue in the same place @jrieken hit it and didn't run into the problem

![](https://memes.peet.io/img/20-07-929964ed-a033-44e5-a5ae-ff9083fcb348.png)

Marking as CNR unless we see this come up...

**Comment by isidorn** [comment]
@connor4312 last timme I changed this was before vacation, so that was 4 weeks ago..

**Comment by jrieken** [comment]
This happens, simply selfhost on debugging

**Comment by jrieken** [comment]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/1794099/90385356-491a0100-e083-11ea-81b7-674a3db69b22.png">

**Comment by isidorn** [comment]
I told Rob to keep his eyes open for this while he is self hosting on Debug. In the meantime there are no actionable items here thus closing (since we already try to keep the variables as stable as possible). In case Rob hits this he plans to investigate further.
