### ISSUE TITLE
Node.js debugger does not stop at breakpoints or print output to debug console

### ISSUE THREAD

**Issue by r3nderer** [microsoft/vscode#103762]
- VSCode Version: 1.47.3
- OS Version: Windows 10 Home 18362.959

Steps to Reproduce:

1. Create a JS file with a single line: `console.log("Hello world");`
2. Set a breakpoint on that line.
3. Press F5 and select "Node.js". In the debug console you will see "Process exited with code 0". The debugger will not have stopped at the breakpoint, nor will "Hello world" appear in the console.
5. Add a second line: `while (true);`
6. Repeat the above steps to run the debugger. "Hello world" will now appear in the debug console but the debugger will still not stop at the breakpoint. The process will not exit because it is in an infinite loop, as expected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Please do two things:

1. See if the nightly build fixes the problem for you https://github.com/microsoft/vscode-js-debug#nightly-extension
1. If not, collect a trace log using these instructions:
>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

/needsMoreInfo

**Comment by harvest-L** [comment]
> * VSCode Version: 1.47.3
> * OS Version: Windows 10 Home 18362.959
> 
> Steps to Reproduce:
> 
> 1. Create a JS file with a single line: `console.log("Hello world");`
> 2. Set a breakpoint on that line.
> 3. Press F5 and select "Node.js". In the debug console you will see "Process exited with code 0". The debugger will not have stopped at the breakpoint, nor will "Hello world" appear in the console.
> 4. Add a second line: `while (true);`
> 5. Repeat the above steps to run the debugger. "Hello world" will now appear in the debug console but the debugger will still not stop at the breakpoint. The process will not exit because it is in an infinite loop, as expected.
> 
> Does this issue occur when all extensions are disabled?: Yes

It may be a problem with the node version. When I use node 9.10.0, I don't ignore the breakpoints directly, but when I switch to 10+, it works.

**Comment by r3nderer** [comment]
The nightly build seems to fix the issue.

**Comment by connor4312** [comment]
Thank you for confirming! The currently-nightly changes will be released in VS Code stable next week.
