### ISSUE TITLE
Annoying tab mannager

### ISSUE THREAD

**Issue by ManelGonzalez-ops** [microsoft/vscode#103759]
Issue Type: <b>Feature Request</b>

Why when I click a file,  your window system (or tab system whatever) is closing the last file I was looking at??  That's very annoying . If I want to close a open tab I just have to click in the X with the mouse on the top, not need you to sabotage my actions whenever I open I file. 

I am a bit tired of having to put a space everytime  (so vsc will market it as edited and I prevent be close) I want to open two files in diferent tabs without the first tab being replaced by the second one.

Maybe is just me.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

**Comment by nrayburn-tech** [comment]
If you double click the file, it will remain open.  If it is only temporarily opened, then the file name will be in italics.
I am not sure if there is a setting to keep the file open after a single click in the file explorer.

Stays Open
<img width="140" alt="Perm" src="https://user-images.githubusercontent.com/52075362/89109289-6ef9a180-d405-11ea-8cb8-102bdb8a96b8.png">

Replaced with Next Opened File
<img width="139" alt="Temp" src="https://user-images.githubusercontent.com/52075362/89109295-7456ec00-d405-11ea-911a-4048adfbd35c.png">

**Comment by ManelGonzalez-ops** [comment]
Hey! Thanks for you response.
Actually I've just found the setting which turn vsc code to achieve that.
In the package.json file of the vsc user settings, I added "workbench.editor.enablePreview": false 
Now works as it is expected :)
