### ISSUE TITLE
Rename/move file doesn't use git mv

### ISSUE THREAD

**Issue by andrewroazen** [microsoft/vscode#103731]
Issue Type: <b>Bug</b>

Git tracked project:
1. Select file in left hand pane
2. Rename file
3. Go to make commit

_Expected result:_
Tracker knows it's the same file and commits it with all of its previous history
_Actual result:_
Commit treats it like a deletion of original file and creation of new file with no previous commit history 

git-enabled projects should handle file renames/moves through git-mv instead of native methods so as to preserve history.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
coldfusion|ili|1.0.1

</details>

**Comment by 1C0D** [comment]
really? it seems like a so basic feature even 4 a new user like me...
