### ISSUE TITLE
Add codeActionsOnSave per language

### ISSUE THREAD

**Issue by jramiresbrito** [microsoft/vscode#103775]
When you work with multiple languages, there are also multiple linters that require some specific configurations. So in some cases I need to have codeActionsOnSave enabled and some cases don't. 
But actually this setting does not support per-language configuration. Would be nice to have support on paste per-language as we have support on save.

![feature-request](https://user-images.githubusercontent.com/47673606/89121069-102e3980-d492-11ea-916c-606a8787d87e.png)

**Comment by ChildishGiant** [comment]
This'd also be nice for if I wanted to autosave when writing in one lang and not to in another.

**Comment by mjbvz** [comment]
What is `editor.codeActionsOnPaste`? Does it come from an extension?

`editor.codeActionsOnSave` can already be set per language

**Comment by jramiresbrito** [comment]
> What is `editor.codeActionsOnPaste`? Does it come from an extension?
> 
> `editor.codeActionsOnSave` can already be set per language

You're right. But it would be nice to also set Actions on Paste. Having this available I would format the code on Paste.

**Comment by mjbvz** [comment]
Please open a feature request for running code actions on paste (there may already be an issue tracking this).

Closing this since it looks like codeActionsOnSave is working as expected
