### ISSUE TITLE
Unable to use Bash as integrated terminal

### ISSUE THREAD

**Issue by rjf2016** [microsoft/vscode#103797]
Issue Type: <b>Bug</b>

#### Issue description
Visual Studio Code version: 1.47.3, git version 2.27.0.windows.1. For the past few months I've been unable to use bash as VSCode's integrated terminal. It's set as default, when I open up the terminal most of the time I dont get a prompt, until I open up a second instance in the terminal. When I do get a prompt, I try an 'ls' command and it either works, returns nothing, or returns 'segmentation fault (core dumped)'. 

#### Steps to reproduce the issue

1. Make Git Bash default terminal
2. Open integrated terminal
3. If I get a prompt (50-50 chance), run 'ls' command a few times

 #### What's the expected result?

-  Running 'ls' works

#### What's the actual result?

- The first time it will usually run the 'ls' command. If I go to run it again (or any other command like 'clear'), it returns 'segmentation fault' or 'segmentation fault (core dumped)'.

#### Additional details / Things I've tried / screenshot

Running Git Bash outside of VSCode works perfect as expected, it runs in Windows Terminal. Also running CMD or PS as VSCode's integrated terminal works as expected. I had VSC/bash working on this machine a few months ago with no problems.

I've tried adding git binaries to windows defender exclusion list (read that might be a fix), but that didn't solve it. I've also uninstalled/reinstalled VSCode and Git for windows, tried multiple Git bash versions, still nothing.

![terminalScreenShot](https://user-images.githubusercontent.com/19439032/89130208-01b34280-d4d1-11ea-9a98-e68afa303f09.PNG)

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (26.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by rjf2016** [comment]
```json
{
    "extensions.ignoreRecommendations": false,
    "explorer.confirmDelete": false,
    "window.zoomLevel": 1,
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
}
```

**Comment by Tyriar** [comment]
I think the only thing this could be is an upstream issue in conpty, the component which launches the process, which also drives Windows Terminal. You say it doesn't happen in Windows Terminal which is on a newer version of conpty so maybe the fix will hit Windows 10 within the next 12 months?
