### ISSUE TITLE
npm keybindings listed but not working

### ISSUE THREAD

**Issue by ShMcK** [microsoft/vscode#103799]
- VSCode Version: 1.47.3
- OS Version: macOS 10.15.6

Steps to Reproduce:

1. select code > preferences > keybindings > search for "npm", see list of npm commands:

![image](https://user-images.githubusercontent.com/4660659/89132771-71beca00-d4cb-11ea-878c-337127049d54.png)

2. attempt to run one of the NPM commands by either:
   - 1. attach a key binding and press the hot key (nothing happens)
   - 2. run from the command prompt (ctrl/cmd + shift + P), `>npm` ("no matching commands")
   - 3. run `vscode.commands.executeCommand('npm.runInstall') in an extension (nothing happens)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Do you have this settings set? `"task.autoDetect": "off"`

The npm extension relies on being able to autodetect npm tasks.

**Comment by ShMcK** [comment]
With `task.autoDetect: "off"` there doesn't seem to be a change.

I've also asked a number of other people to try running an NPM action in VScode using the 2b method above- none have been successful.

**Comment by alexr00** [comment]
Sorry, I meant can you remove the setting `task.autoDetect` if you have it set.

**Comment by ShMcK** [comment]
I've turned off autoDetect under settings, but same result.

**Comment by alexr00** [comment]
I still wasn't clear, sorry, I meant can you set `autoDetect` to `on`. 

Also, do you have a folder open with a packag.json?

**Comment by ShMcK** [comment]
yes. The "npm debug" consistently runs appears as an option, but none of the other commands listed under keybindings appear.

![image](https://user-images.githubusercontent.com/4660659/89548034-60233e00-d7bb-11ea-91cc-2defb08282df.png)

Similarly when vscode is launched without extensions (`code --disable-extensions`)

**Comment by alexr00** [comment]
@ShMcK this is intentional. Those are the only npm commands that you can run "on demand" like that. The others are used to support the NPM Scripts view.
