### ISSUE TITLE
VS Code Insiders 1.48 User Setup fails to create desktop icon (Public Desktop folder)

### ISSUE THREAD

**Issue by byroniac** [microsoft/vscode#103746]
- VSCode Version: 1.48.0-insider
- OS Version: Windows 10 version 2004 build 19041.421

Steps to Reproduce:

1. Run the User Setup installer
2. Choose to create a Desktop icon

For some reason, it tries to create the Desktop icon shortcut in the Public folder instead of the user desktop folder, and fails, of course. It's easy enough to copy the shortcut to my desktop manually, so that's what I did. Everything else seemed to install correctly (but I did not do the register file types for editing option on the Insiders edition or the regular edition before it, but the regular edition had no problem creating a desktop icon shortcut in the proper user folder, 1.47.3, and I am installing both on a newly purchased, fresh machine).

Does this issue occur when all extensions are disabled?: Yes (N/A)

![vscode-insiders-error](https://user-images.githubusercontent.com/4079416/89095888-72564400-d397-11ea-96a0-d5af5d9347f8.png)

**Comment by joaomoreno** [comment]
Does the `C:\Users\Public\Desktop` folder exist? Does your user have permissions to it?

**Comment by byroniac** [comment]
> Does the `C:\Users\Public\Desktop` folder exist? Does your user have permissions to it?

Yes. No, but it should from looking at the access permissions (see image below). Why did this change the way it works from the standard 1.47.3 VSCode installer?

![c-users-public](https://user-images.githubusercontent.com/4079416/89160154-3dccbe80-d536-11ea-86cb-df9c527eb23b.png)

**Comment by joaomoreno** [comment]
We updated our setup framework, so this could simply be a regression from that update.

**Comment by byroniac** [comment]
OK. Wait. I didn't look at the C:\Users\Public\Desktop folder itself. It does exist, and my user had a security entry with special permissions, but none of the security entries were inherited. I removed them and inherited from the C:\Users\Public folder, but I should not have to do that on a fresh machine. When I look at the VSCode icon, I remember that I am using OneDrive to backup my important system folders, including the desktop folder. Could that be the problem? Maybe it doesn't detect what it expects and tries to redirect to the Public desktop folder?

![vscode](https://user-images.githubusercontent.com/4079416/89161589-6b1a6c00-d538-11ea-9466-2c647955c71a.png)

**Comment by vrtareg** [comment]
Hi

I have same issues.
I am user on my laptop, no Admin rights.

User Installer should create shortcut on User Desktop, not Public all Desktop ...

Same is happening for Stable an Insiders User Installer.

Regards,
Areg

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/104981
