### ISSUE TITLE
The terminal process failed to launch of vscode

### ISSUE THREAD

**Issue by mr-abhi-k** [microsoft/vscode#103769]
Error:The terminal process failed to launch: Starting directory (cwd) "D:\vs code\march long 2020" does not exist.
Json file:
{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "C_Cpp.updateChannel": "Insiders",
    "files.autoSave": "afterDelay",
    "java.saveActions.organizeImports": true,
    "window.zoomLevel": 0,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.windowsEnableConpty": false,
    "json.schemas": [
    
    ]
}

whenever compiling a code terminal does not launch and gives the above mention error.
![Uploading SharedScreenshot.jpg…]()

error pic link:[https://stackoverflow.com/posts/63027440/revisions]

**Comment by Tyriar** [comment]
The screenshot failed to open. Make sure that directory does actually exist, that message should only ever display when it does not.

**Comment by mr-abhi-k** [comment]
i updated the issue with similar error pic with different error message.

**Comment by Tyriar** [comment]
How do you launch the terminal? Do you have extensions installed?

**Comment by mr-abhi-k** [comment]
yes everything is installed.I think problem arised when i deleted some files in my computer to make it clean and now i can't recover the files also.

**Comment by Tyriar** [comment]
Run `code --list-extensions` and paste in the output and please show a [gif](https://gifcap.dev/) of the problem.

**Comment by mr-abhi-k** [comment]
![recording](https://user-images.githubusercontent.com/52717415/89403066-67076d80-d735-11ea-92df-2a95ab0817aa.gif)

i wrote code then compiled and got error msg.

**Comment by Tyriar** [comment]
Your anti-virus says threats detected so it probably blocked the native call, whitelist these files: https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch#_error-connectnamedpipe-failed-windows-error-232
