### ISSUE TITLE
nodejs debugger attaches but never shows breakpoint on first line

### ISSUE THREAD

**Issue by chriskinsman** [microsoft/vscode#103726]
Issue Type: <b>Bug</b>

It just hangs there.

It seems to be related to one project, I don't see it as often in other projects.

I can occasionally get it to work if I turn off auto attach and use the debug tab.

Long time user and this just started happening in the last week.  Really odd.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.5.0
Bookmarks|ale|11.3.1
project-manager|ale|11.1.0
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
jsrefactor|cms|2.20.6
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.8
git-extension-pack|don|0.1.3
githistory|don|0.6.9
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.12
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
terraform|has|2.1.1
vscode-mocha-test-adapter|hbe|2.7.1
vscode-test-explorer|hbe|2.19.1
search-node-modules|jas|1.3.0
code-beautifier|mic|2.3.3
terraform-snippets|min|2.1.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.4.1
vscode-kubernetes-tools|ms-|1.2.1
mssql|ms-|1.9.0
vsliveshare|ms-|1.0.2478
vsliveshare-audio|ms-|0.1.85
debugger-for-chrome|msj|4.12.9
vetur|oct|0.25.0
proto|pet|0.0.2
vscode-versionlens|pfl|1.0.8
material-icon-theme|PKi|4.2.0
vscode-css-peek|pra|4.0.0
vscode-yaml|red|0.9.1
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.9
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by netpoetica** [comment]
I see this as well w/ VSCode 1.47.3 and mocha 3.3.0 - using nightly extension allows the tests to run, but breakpoints just never work at all. This just came out of nowhere in the last 2 weeks or so, maybe 3.

**Comment by connor4312** [comment]
Please do two things:

1. See if it happens using the nightly build https://github.com/microsoft/vscode-js-debug#nightly-extension
1. If so, collect a log file using these instructions:

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by chriskinsman** [comment]
So far that looks to have resolved the issue...

**Comment by connor4312** [comment]
Okay, thanks for letting us know! The current nightly bits will be released in the upcoming stable build next week.
