### ISSUE TITLE
"Change All Occurrences" incorrectly accounting for the lack of spaces between matching strings.

### ISSUE THREAD

**Issue by awsumpwner27** [Microsoft/vscode#10370]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.4 LTS

Steps to Reproduce:
1. Take the following text:
   
   ```
   abc
   abc abc
   abcabc
   ```
2. Right click the "abc" in the first line to bring up the option to "Change All Occurrences" and select it.
3. Begin typing ("def" for example) to see this result:
   
   ```
   def
   def def
   def
   ```
   
   Although there's a match made between "abcabc" and "abc", the changes are made as if "abcabc" were a single occurrence of "abc".

**Comment by alexandrudima** [comment]
This has been fixed with the fix for #6661
