### ISSUE TITLE
editor.wordBasedSuggestions should not be tied to select word (ctrl+D) behavior

### ISSUE THREAD

**Issue by ecraig12345** [Microsoft/vscode#10372]
- VSCode Version: 1.4.0
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

1. Turn off `editor.wordBasedSuggestions` in settings (I did this because overall I find word-based suggestions more annoying than helpful)
2. Open a file (Typescript in my case) and put the cursor inside a string literal
3. Press `ctrl+D` to select the word

Previously, `ctrl+D` would select the word as expected. Now it doesn't unless I turn `editor.wordBasedSuggestions` back on. 

One of the many cases in which this is annoying to me is when renaming a TypeScript import, like `import IFoo from './IFoo'`. I used to put the cursor on the first `IFoo`, press `ctrl+D` to select it, then press `ctrl+D` again to select the second instance inside the string. Now that doesn't work.

If this was an intentional change, it would be nice if the behavior was configurable via a setting.

EDIT: I'm also having trouble with `ctrl+D` not working in other assorted circumstances even with `editor.wordBasedSuggestions` off, sometimes seemingly randomly--it won't work, I'll move the cursor, move it back, and it works.

**Comment by jrieken** [comment]
@ecraig12345 How about attaching a sample source file with steps that allow us to reproduce this?

**Comment by ecraig12345** [comment]
Now this has stopped reproing for me even though it was quite consistent at the time I opened the issue... I'll let you know if the problem comes back.
