### ISSUE TITLE
Replace panel: allow to validate using keyboard any time, no only when replace string is active

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#103816]
![image](https://user-images.githubusercontent.com/199648/89160972-362b0b00-d572-11ea-9c68-d0ce2c0bd5d9.png)

Right now this won't work:

- press `cmd + alt + f` to open the search & replace panel
- type something in the search input
- press `cmd + enter`

You have to activate the replace field in order for the `cmd + enter` shortcut to work.

What if you want to replace the search string with an empty string (ie: remove the search string)? In this case you have to focus the replace input just to be able to press `cmd + enter` to validate.

I think the `cmd + enter` shortcut should work anywhere in the panel, not only when the replace input has focus.

I could have a look at the code to do it myself.

**Comment by roblourens** [comment]
Sure, I would take a PR for that.

**Comment by Brayden-Paley** [comment]
Hi, I'd like to take a look at solving this issue, I am a part of GraceHopper OSD

**Comment by isidorn** [comment]
Hi there,

This is part of the find widget commands.
I would start in this Code Area https://github.com/microsoft/vscode/blob/b8e87aae6dca78fe0f8dbffd9d6a34921d9913f4/src/vs/editor/contrib/find/findWidget.ts#L21

And would search for the command that binds Cmd+enter. Basically it needs to be active in more cases
@Brayden-Paley if you do not find the specific location let me know and I can try to find a more precise opinter

**Comment by isidorn** [comment]
Maybe somewhere around here https://github.com/microsoft/vscode/blob/b8e87aae6dca78fe0f8dbffd9d6a34921d9913f4/src/vs/editor/contrib/find/findController.ts#L872

**Comment by Brayden-Paley** [comment]
Hi @isidorn 
I was looking to see if the function at this line may be able to link to the cmd + enter functionality by creating a condition where the input is in focus but the replace value is undefined.

https://github.com/microsoft/vscode/blob/b8e87aae6dca78fe0f8dbffd9d6a34921d9913f4/src/vs/editor/contrib/find/findWidget.ts#L785

But at this time I'm still unable to find where the cmd + enter function is located to then expand its functionality to hopefully solve the issue. Please let me know if you have any ideas!
