### ISSUE TITLE
Powershell terminal crashes on Ctrl+C

### ISSUE THREAD

**Issue by ManuSQLGeek** [microsoft/vscode#103872]
- VSCode Version:1.47.3
- OS Version: 10.0.18362 x64

Steps to Reproduce:

1. Open a Powershell terminal
2. Run any command and hit Ctrl+C to cancel the command

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal

**Comment by JDWilson1980** [comment]
DDOS.frank.global/care

U/cli.oauth.enterprise.soltions
(cyber comm)

Inspector.sniff
Raccon.mirror.host
Load.build.ncis.net

Tv.ncis.teals.co
