### ISSUE TITLE
v 1.47.3 won't start

### ISSUE THREAD

**Issue by orionlee** [microsoft/vscode#103856]
Issue Type: <b>Bug</b>

I can't start the latest update v1.47.3. Clicking on the Code application appears to do nothing. The editor is not launched, nor is there any error dialog.

I disabled all extensions and tried again. It still does not start
So I had to stay with v1.47.2.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by orionlee** [comment]
I got some error messages by starting Code from command line `bin\code.cmd`: 

```
#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 000000BC7F0FF040
```

**Comment by lszomoru** [comment]
Could you try installing `1.47.3` using the [installer](https://code.visualstudio.com/Download) instead of the `.zip`?

**Comment by orionlee** [comment]
My bad - The `1.47.3` `.zip` had no issue. I accidentally extracted only part of the `.zip`, missing some of the files.
