### ISSUE TITLE
VSCode Task runner should be able to read scripts from package.json

### ISSUE THREAD

**Issue by slowmove** [Microsoft/vscode#10380]
It would be nice if VSCode, if a package.json is detected in the project, reads the scripts from the package.json to run thru the task runner without the need of creating a tasks.json calling the npm run methods.

![skarmavbild 2016-08-09 kl 09 39 42](https://cloud.githubusercontent.com/assets/624182/17546143/f87b34f8-5ee0-11e6-887a-2a71fd2c5cff.png)

![skarmavbild 2016-08-10 kl 09 58 28](https://cloud.githubusercontent.com/assets/624182/17546161/0740b350-5ee1-11e6-95a5-b702812b788d.png)

**Comment by dbaeumer** [comment]
Dups #1777
