### ISSUE TITLE
Setting Sync: multiple conflicts shows weirdly worded options

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#103863]
![image](https://user-images.githubusercontent.com/35271042/89227027-d0e71200-d591-11ea-86cd-97f6fd8534c3.png)

1. Turn off sync on machine A
2. Make a change on machine B
3. Make a conflicting change on machine A
4. Turn on sync on machine A
5. :bug: notification appears

These options feel really different from the regular conflicts we've had:

![image](https://user-images.githubusercontent.com/35271042/89227093-e9efc300-d591-11ea-98ee-c4bf8627a7c7.png)

I think these two should be consistent and more like the later. cc @Tyriar

**Comment by Tyriar** [comment]
They seem to be pretty much the exact same actions but the first screenshot introduces new terminology ("merges") and does not do very well to indicate that Accept Replace is a fairly destructive action.

Suggestion:

- Accept Replace -> Replace Local
- Accept Merges -> Merge
- Show Merges -> Merge Manually...

The positions should probably align as well.

We can keep the cancel button off it still as the cross is there.

**Comment by JDWilson1980** [comment]
qRL.syntax.ipv6.enterprise
Host/domain/Distro

SQL.oemMicrsoft/manifold.dll
SQL8.onboarding/CyberCm

**Comment by sandy081** [comment]
While fixing other issues, I changed the flow, when there are conflicts while turning on sync, to align with manual sync.

- Turn on Sync on a second machine that has potential conflicts
- You get merge/replace dialog

<img width="650" alt="image" src="https://user-images.githubusercontent.com/10746682/89427920-147d7f80-d73c-11ea-8f9c-b589f64b6e6b.png">

- You choose to merge
- If there are conflicts, following dialog is shown asking user to merge manually

<img width="454" alt="image" src="https://user-images.githubusercontent.com/10746682/89476443-01de6700-d78b-11ea-94ba-8b5aa10d371c.png">

- This opens Manual Merge view allowing user to merge manually where user has options to accept local or remote or merge and resolve conflicts.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/10746682/89428102-50184980-d73c-11ea-9d2d-59cbfa20bda7.png">

- User can turn on sync after resolving all

The conflicts notification appears only when there are conflicts while sync is on.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/10746682/89476827-fc355100-d78b-11ea-845a-aa1c4c3bda90.png">

Going forward I would align handling conflicts with manual merge behaviour - #104136

**Comment by misolori** [comment]
<img src="https://user-images.githubusercontent.com/10746682/89476443-01de6700-d78b-11ea-94ba-8b5aa10d371c.png">

I think the button here should be "Merge Manually..." instead of "Ok"
