### ISSUE TITLE
More Actions Drop Down Menu - Native Notebook Editor

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#103894]
"More Actions" drop down menu only displayed in a stable manner when in cell selected mode. 
When in cell editor mode, menu drop down and cell editor outline flashing. 

- [ ] Drop down menu should be displayed in a stable manner in either mode. 

- [ ] "Change cell to Code" should only be option for a markdown cell and vice versa. 

![More Actions Menu Drop Down](https://user-images.githubusercontent.com/19276747/89246909-fccdbc00-d5c0-11ea-97f1-98b8b2397cc3.gif)

![More Actions](https://user-images.githubusercontent.com/19276747/89246540-305c1680-d5c0-11ea-9fc3-08fa8321a2ba.png)

**Comment by roblourens** [comment]
Merging the first into #103926, the second into #103922
