### ISSUE TITLE
Bad output height calculation for empty output

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#103877]
- Execute github issue query that returns some results
- Change the query so that it will return 0 results
- Rerun it
- The output goes away but the same amount of space is consumed

![image](https://user-images.githubusercontent.com/323878/89233854-5f15c500-d59f-11ea-9b82-a088bde1dc0b.png)

**Comment by rebornix** [comment]
@roblourens are you seeing this issue 100% of the time? I can't reproduce it.

**Comment by roblourens** [comment]
Yeah. I can debug it

**Comment by JDWilson1980** [comment]
Envelop.kubernates(service.threat.circle.bash) 

Moot(critical.devops.circle)
Uptick(refUser.data.circle)
Down(refUset.data.circle)

Blogs (enterprise.servo.namely)
Ad(offers.inside.metadata)
Bash(repositorys.tier5.bat)

**Comment by roblourens** [comment]
It's gone
