### ISSUE TITLE
VSCode not display all emoji in ubuntu 18

### ISSUE THREAD

**Issue by ViniciusFXavier** [microsoft/vscode#103853]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by JDWilson1980** [comment]
Host(sniff.ui)
Def(Mirror.link.care.mod)
Playbook.cybercom.net/RacconCity.sno
Frost.wire.box/cybercomm
In(touchdown.playbook.vs)
Omni(Brand.ncis.build.tv)
