### ISSUE TITLE
Add search to search all result

### ISSUE THREAD

**Issue by phmngocnghia** [microsoft/vscode#103805]
VSCode allow to filter in the list result by pressing `/` in the list result, and type the keyword.
![image](https://user-images.githubusercontent.com/36730355/89136151-5fd93780-d55c-11ea-8c9c-a234f471d04d.png)

But I can't search the list result in the search all menu. I'm not sure if this is a bug. Press `/` on the search all list result doesn't trigger search list result
![image](https://user-images.githubusercontent.com/36730355/89136166-80a18d00-d55c-11ea-9605-860289aefe11.png)

This is so in-consistent. I know there's an option called 'files to include', but using `/` search list result feature to filter the list result would be much more "handy", and better UX

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/67397
