### ISSUE TITLE
Why can't you get Visual Studio Code on Steam.

### ISSUE THREAD

**Issue by Haselden** [microsoft/vscode#103837]
I was always curious about that, like you can buy Video editing software, photoshop programs, and yes even blender.

But why can’t you get Visual Studio code or any real Text viewers on steam.

**Comment by joaomoreno** [comment]
We're not really interested in (1) and we already have automatic updates (2). Thanks for the suggestion tho!

**Comment by WilliamShockleyfake** [comment]
make it available on steam please I want to show my friends that I'm coding not playing games

**Comment by M1XT3NZ** [comment]
+1
Visual studio itself should also be on Steam,
there is no reason why it should not be

**Comment by lucasmaffazioli** [comment]
It's a cool feature to have, I can add a 3rd item:
- To log how much time you spend coding in a nice platform that you'll ever have (if you play games and such)

**Comment by CreeperKong** [comment]
Just select add non steam game. And run it from Steam, it will show friends that you are playing VSC unless the status is Invisible.

**Comment by batu1579** [comment]
> Just select add non steam game. And run it from Steam, it will show friends that you are playing VSC unless the status is Invisible.

For some reason, I added vscode to steam and it didn't show that I was playing. My status just showed that I was playing vscode, but then I was online again.

**Comment by syberphunk** [comment]
@gregvanl / @joaomoreno What a surprisingly short-sighted attitude "we're not interested" , no, but the people who actually use it are. Just think, this could have been pre-deployed on Steam and made available for everyone who's picked up a Steam Deck.

Especially considering there'll be game developers creating for the Steam Deck, and others who simply use the Steam Deck as a home computer, especially with the cost of electricity what it is.

You can even have it deploy the Linux or Windows version depending on the environment, just think, seamless and simple for end users.

Not too late to reconsider though.

**Comment by joaomoreno** [comment]
Let me clarify: we're not interested in _supporting_ this. Like every software development team, our resources are limited so we have to be smart about the things we commit to maintaining. Thanks for understanding.

**Comment by RedSTARO** [comment]
Like I wanna know how many time I spent on VSCode

**Comment by tonsvz** [comment]
> Let me clarify: we're not interested in _supporting_ this. Like every software development team, our resources are limited so we have to be smart about the things we commit to maintaining. Thanks for understanding.

Bro thinks he speak for all of us.

**Comment by RedSTARO** [comment]
> > Let me clarify: we're not interested in _supporting_ this. Like every software development team, our resources are limited so we have to be smart about the things we commit to maintaining. Thanks for understanding.
> 
> Bro thinks he speak for all of us.

I think he's reply was reasonable, though I really wanna VSCode available on  Steam so that I can get time statistics

**Comment by M1XT3NZ** [comment]
„Maintaining“ yeah a task that can be automated 🙄

**Comment by linonetwo** [comment]
There is a port here lol https://store.steampowered.com/app/779260/Kode_Studio/

Anyway, you can add non-steam game like this https://youtu.be/NRa_9y9y7sI?si=nBvjpEhAPtjT9JFS

And sadly

> For those who are wondering if doing this, you will be able to see the time played, the answer is no, the non-Steam game does not have any type of Steam feature, you'll only be able to see the time played and the achievements if you buy the game on steam

Also it won't show you are playing VSCode after a while, while this should have worked for most of non-steam games.
Even it could, if you start vscode from desktop shortcut, it won't too.

**Comment by RedSTARO** [comment]
> There is a port here lol https://store.steampowered.com/app/779260/Kode_Studio/
> 
> Anyway, you can add non-steam game like this https://youtu.be/NRa_9y9y7sI?si=nBvjpEhAPtjT9JFS
> 
> And sadly
> 
> > For those who are wondering if doing this, you will be able to see the time played, the answer is no, the non-Steam game does not have any type of Steam feature, you'll only be able to see the time played and the achievements if you buy the game on steam
> 
> Also it won't show you are playing VSCode after a while, while this should have worked for most of non-steam games. Even it could, if you start vscode from desktop shortcut, it won't too.

It is looks like KcodeStudio do not update actively for a while, I also wanna microsoft can do this because this won't take long and this will be a nice way to destribute

**Comment by linonetwo** [comment]
Maybe you can do this in https://github.com/VSCodium/vscodium repo, add a Github Action to release it to Steam, just need to decide to release under whose account, which is the most difficult part: https://github.com/CleverRaven/Cataclysm-DDA/discussions/49020

**Comment by Anankin12** [comment]
Having vscode on steam could be used to download and run it in some streaming services, like GeForce Now, and take advantage of that hardware's capabilties. Or maybe id doesn't make sense idk

**Comment by WRXinYue** [comment]
I added a non-Steam game, but it seems that VSCode doesn't show as playing. I found a pretty good alternative: [https://github.com/Chelovedus/Coding-Time-Tracker-For-Steam](https://github.com/Chelovedus/Coding-Time-Tracker-For-Steam). It works really well. It tracks my work hours and lets my friends know that I’m coding, not gaming.
