### ISSUE TITLE
Image data returned from `FileSystemProvider` not rendering

### ISSUE THREAD

**Issue by APLmath** [microsoft/vscode#103807]
- VSCode Version: 1.47.3
- OS Version: macOS 10.15.5 (19F101)

Steps to Reproduce:

1. Run an extension that registers a custom `FileSystemProvider`.
2. Open an image file from that custom file system.
3. VS Code complains that "An error occurred while loading the image".

I created an example `FileSystemProvider` that simply acts like a passthrough for the normal filesystem: https://github.com/APLmath/passthrough-fs-vscode/releases/tag/0.0.1

Using this sample extension, I opened an image file normally (left), and then also opened it using the `PassthroughFS` (right):
<img width="1358" alt="Screen Shot 2020-08-02 at 7 37 55 PM" src="https://user-images.githubusercontent.com/1169103/89140903-d42dbf80-d4f7-11ea-9852-74a2263d8499.png">

The Uint8Array returned in both cases should be identical.

I think this used to work a year ago? Haven't tried to reproduce on older version yet.

Does this issue occur when all extensions are disabled?: No (this bug is about an extension API)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by APLmath** [comment]
@mjbvz Good call. With one of the extensions I was developing seriously, it does _not_ reproduce in Insiders Version: 1.48.0-insider. However, it _does_ reproduce with the sample "passthrough" extension I linked above. I'm looking to see if it's a bug with my sample.

**Comment by JDWilson1980** [comment]
MSP.host.net/IMEI

Build.cybercommand.sql
UpgradeCOMtier6.botnet/sofort.mod
Snif.global.playbook.spin
Swamp.bat
Cesspool.bat
CyberCm.dev
TriagePAX.dll
User.exchange.dev
Playbook.law.err
Hob.test/repos
Backlogs.ert/repo
Repository/critical/5
