### ISSUE TITLE
Startup Issues - Very long to load

### ISSUE THREAD

**Issue by Acrith** [microsoft/vscode#103878]
Issue Type: <b>Performance Issue</b>

At my home station, clean VScode loads for about 10-15 seconds straight. I cant find any informations related to why is it happening, yet most of the actions I take in software like loading info about extension, loading issue reporter - all those take huge amounts of time (like, window is rendered, but content is not loading for long time - this also happens while starting up VScode - including the first startup).

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3311)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.97GB (1.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    78	 32136	code main
    0	    15	 27148	   electron-crash-reporter
    0	   110	 33844	   gpu-process
    0	    25	 34976	   utility
    1	    69	 36444	   window (Issue Reporter)
    0	   171	 39944	   window (Visual Studio Code)
    0	    70	 39088	     extensionHost
    0	    76	 40492	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by deepak1556** [comment]
Can you start vscode with `--trace-startup --trace-startup-duration=20` , once the window has finished loading quit the application and there should be a file called `chrometrace.log` under the current directory. Please attach that file, thanks!

Can you check for any antivirus software scanning the vscode installation path ?

**Comment by Acrith** [comment]
Hello.
Sorry for long no response - I am attaching the file required.

About the antivirus - I don't really understand the question. I have MS Defender only, before I had also a SpyBot but I've uninstalled it for this test.

[chrometrace.log](https://github.com/microsoft/vscode/files/5059095/chrometrace.log)

**Comment by deepak1556** [comment]
@Acrith can you check if the latest insiders fixes the issue https://code.visualstudio.com/insiders
