### ISSUE TITLE
Latest update is available for linux version like ubuntu. It allows me to install update. When installation is done, It never updates my vs code version and gives me update notification regularly. Please check this issue asap

### ISSUE THREAD

**Issue by Haseeb-075** [microsoft/vscode#103827]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
How did you install VS Code?

**Comment by Haseeb-075** [comment]
Simply download & install .deb version of linux from vs code official
website

**Comment by Tyriar** [comment]
When you install the deb package it will install the repository into your system. You can then use your system update mechanism to update the package. VS Code will not update automatically when using the deb package but it will tell you when updates are available.

It's possible you were seeing some temporal issues when our repository was not getting the latest versions.
