### ISSUE TITLE
Output renderers miss initialization events if output mime type picked from user

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#103842]
- VSCode Version: 1.48-Insiders
- OS Version: macOS

Originally reported by @DonJayamanne , they built a pure renderer which uses the new renderer API to render outputs and it works fine if the custom mime type supported by the renderer has highest display order (meaning it's rendered by default). However if the display order is modified to show other mime types by default (so the renderer will not be loaded initially) and then choose the custom mime type from the mime type picker, the output is not rendered at all. Besides, it only happens for the first time, the next output doesn't run into this issue.

**Comment by connor4312** [comment]
This works for me--a delay for some reason, but it gets the event and renders content

![](https://memes.peet.io/img/20-08-805a2643-5a62-4bee-9af8-df2290dda50a.gif)

Is the event listener being registered synchronously when the script loads? / Is this code in a repo where I can try it out?

**Comment by rebornix** [comment]
@DonJayamanne can you provide more details?

**Comment by DonJayamanne** [comment]
Will provide this shortly.

**Comment by DonJayamanne** [comment]
Ok, its working now. I promise this wasn't working last week.
Please feel free to close this issue.

**Comment by rebornix** [comment]
Cool, we can reopen if we see this issue again.

**Comment by isidorn** [comment]
Adding verified label since author verified it
