### ISSUE TITLE
Test: Notebook cell collapse

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#103887]
Refs: #100308

- [x] macOS @connor4312
- [x] linux @joaomoreno
- [x] windows @dbaeumer

Complexity: 3

Authors: @roblourens @rebornix 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103887%0A%0A)

---

Test the new ability to collapse cells and their outputs

- Open a github issues (or other) notebook
- Find the "Collapse Cell Input" and "Collapse Cell Output" commands under the `...` menu
- "Collapse Cell Output" should only appear when the cell has output
- You should be able to click the collapse indicator that shows up to expand it
- When both output and input are collapsed, you should just see one "expand" button
  - And it should always expand the input first, regardless of in which order the parts were collapsed

The collapse state is not currently saved when reopening the editor, although it will be in the future, pending ext api update

**Comment by joaomoreno** [comment]
When using the Markdown Notebook editor, I only see `Collapse Cell Input` which makes it look kinda strange:

![image](https://user-images.githubusercontent.com/22350/89272324-44def400-d63e-11ea-9c6e-80cc8ca22896.png)

I guess this editor isn't a great example for this feature.
