### ISSUE TITLE
Terminal fecha soiznho

### ISSUE THREAD

**Issue by FabioPegoraro** [microsoft/vscode#103868]
Issue Type: <b>Bug</b>

Toda vez que tento abrir o  terminal do meu VSCode e fecha logo em seguida, já desinstalei e instalei novamente e não adiantou.
Não acho nada sobre isso na internet, vocês sabem o porque isso pode estar acontecendo?

Every time I try to open the terminal of my VSCode and close it right away, I have already uninstalled and installed it again and it was no use.
I don't think anything about it on the internet, do you know why this could be happening?

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.18GB (0.68GB free)|
|Process Argv|C:\Users\fabio\Desktop\ArByte\Aulas-Atividades\Arbyte-Atividades\turma-2\FabioPegoraro|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-pt-BR|MS-|1.48.1
vscode-js-console-utils|wht|0.7.0
material-theme|zhu|3.8.5

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
