### ISSUE TITLE
Azure DevOps - test improvements

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#103814]
- [x] Adopt a multi-stage pipeline for better visibility into dependencies
- [x] Review all test suites and ensure that they emit XML test results
- [x] Add pipeline task to publish the test results

**Comment by JDWilson1980** [comment]
NSS.cybersec.microsoft.com
G
Hubspot.ncis.host
Info.subscriber.report.net
Workflows.sysAutorun.IT6.1
BuildCyberSecurity.bat
Norton365.axio.net
Link.observe.solutions.deploy/Global-Axiom
Omni.brand.cybercommand.ntr
oP.github.hubspot.net
Unity.project.net
Repo.tv.net
Globalsolution.cyber.us
