### ISSUE TITLE
Enable right clicking on breadcrumbs

### ISSUE THREAD

**Issue by samdenty** [microsoft/vscode#103870]
Currently you can only left click on breadcrumbs to jump to them.

![CleanShot 2020-08-03 at 22 44 41](https://user-images.githubusercontent.com/13242392/89230413-25fb4600-d5db-11ea-9326-4850c313ef25.gif)

This is annoying when you want to eg. find all references on a method:
 - You first have to click on the breadcrumb to jump to it
 - You then have to click into the code to jump to it
 - Then you have to locate the token in your code, and right click it

---

It'd be much simpler if you could just right click on the breadcrumbs themselves, and then do find-all-references there (without having to right click on the code).

**Comment by samdenty** [comment]
This is similar to https://github.com/microsoft/vscode/issues/56494, but for code tokens as well as folders / files

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Abreadcrumbs+label%3Afeature-request
