### ISSUE TITLE
Application menubar actions run twice on click

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#103820]
1. Open today's Insiders on Windows
2. Use the mouse to choose `File > New Window`

Two windows show up

**Comment by gjsjohnmurray** [comment]
Interestingly, if I click down on File, move the mouse downward, and release when over New File then I only get one new file tab. And this operation (down, drag, release) doesn't work in 1.47 (there's an open issue about it). It started working on Insiders when that used Electron 9. Maybe someone has been trying to fix it even after the revert to E7.

**Comment by karolz-ms** [comment]
Extension-contributed commands are affected too https://github.com/microsoft/vscode-docker/issues/2218
