### ISSUE TITLE
Add `product` and `runCommand` on notebook renderer API

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103864]
## Problem

Notebook renderers need to be able to communicate back to the content provider and/or kernel in several cases. For example, @DonJayamanne described a case where double-clicking on ipywidget graphs opens a separate window with more information. In a case where I have a .cpuprofile notebook, I would also want to be able to run a command to open a file or apply code lenses.

Currently we have the NotebookCommunication object that allows a pure renderer to communicate with the notebook content provider and kernel. This implies that renderers and content providers share a contract, but a goal of renderers is to have them be generic, standalone, swap-able bits of functionality. I should be able to write a flame chart renderer that takes .cpuprofile-formatted data without mandating that the content provider be one that I write.

## Solution

Notebook renderer types are here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode-notebook-renderer/index.d.ts

This adds two new fields to the renderer API:

```ts
/**
 * Name of the product and its version displaying the renderer.
 */
product: { version: string; name: string };

/**
 * Runs a command in the context of the renderer. Returns a promise with
 * the command result.
 */
runCommand<T>(name: string, ...args: unknown[]): Promise<T>;
```

- The `product` field is added so that renderers can discern appropriate functionality for the current environment. Until this point, the notebook renderer API was generic and independent of any particular editor. However, this change introduces a the ability to interact with the outside world, so `product` is added to make sure the renderer can interact correctly.
- `runCommand` is self-explanitory

In VS Code, when the command is invoked it will run the registered command. It will prepend the notebook context to the arguments list, which is:

```ts
interface NotebookCommandContext {
  document: NotebookDocument;
}
```

## Limitations

Having the document is required in many scenarios, so it needs to be somewhere in the context of the command:
 - appending the context to the arguments means that a command can't add more arguments without breaking backwards compatibility
 - prepending a context, or wrapping the arguments in a context+data object, means that you won't be able to invoke commands that aren't made to be called from a notebook renderer

One alternative would be to provide some "notebook document placeholder" symbol in the renderer (providing the entire NotebookDocument is not practical and would allow undesired mutations) that the renderer could pass up to be replaced with the NotebookDocument interface in the call.

One entirely different alternative would be to not use standard commands, but have a separate `registerNotebookRendererCommand` API that extensions could use.

cc @rebornix

**Comment by JDWilson1980** [comment]
API(NCIS.autoRUN)
Sandbox.api

NCIS.USCIS.mod

Sniff.spit.onBoard.global

**Comment by DonJayamanne** [comment]
We'd also need to pass the cell and mimetype/cellOutput as part of the NotebookCommandContext. This would help is identify the cell output in the document for which the command was invoked

**Comment by DonJayamanne** [comment]
Isn't firing commands dangerous, ie any 3rd party js lib could execute any command without any user interaction.

**Comment by connor4312** [comment]
> We'd also need to pass the cell and mimetype/cellOutput as part of the NotebookCommandContext. This would help is identify the cell output in the document for which the command was invoked

Unfortunately with a message sent from JavaScript code, we don't know what cell it's associated with automatically. However the cell output and mime type are accessible from the output event, so while it may not be incredibly efficient the renderer could pass that back up in the command as necessary. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode-notebook-renderer/index.d.ts#L20-L21

> Isn't firing commands dangerous, ie any 3rd party js lib could execute any command without any user interaction.

I'd thought Rob added support for our command links, but looking through the code it appears I was mistaken about that, maybe we just talked about it during standup.

You have a good point about the danger there. It may be possible to verify that events are only sent during user-initiated actions, but this is more fragile and not necessarily sufficient (e.g. a mouseover is a user-initiated interaction). An additional point favor of having a separate `registerCommand` sepcifically for notebooks.

**Comment by DonJayamanne** [comment]
Why not allow extensions to contribure an `outputId`. If this is provided by extensions, then VS Code could use this, else VS Code generates an output Id (as is the case today).
Yes, extensions use `1` for all output ids, but at this point, its `garbage in garbage out`

**Comment by connor4312** [comment]
Following up after some discussion internally:

A significant point of concern with this API is that it reduces renderer portability. We introduce a product field here for developers to disambiguate, but it's vanishingly unlikely that developers will test their renderer outside of VS Code. The golden path is to have a shared marketplace between VS Code and Azure Notebooks where everything is guaranteed to work seamlessly between them; the pure renderer gave us that, and this API corrupts that.

So, two things here:

1. For communication with the kernel, I think allowing an optional output ID is... fine. We would not persist it to the content provider most likely, it would be solely an internal handle. Cc @rebornix @roblourens  who are doing examinations around the output API.
1. Side effects in general can be accomplished simply by additional methods exposed to the renderer. For hypothetical example, "open data uri in new window", or "open file by path".
