### ISSUE TITLE
"powershell.exe" does not exist

### ISSUE THREAD

**Issue by Abdullah25-web** [microsoft/vscode#103830]
When i go to run a c program it shows an error on the right bottom corner, that "The terminal process failed to launch: Path to shell executable "pwershell.exe" does not exist."
![Screenshot (8)](https://user-images.githubusercontent.com/69150030/89180469-44e1e400-d5ab-11ea-8090-563a7e00571c.png)

**Comment by Tyriar** [comment]
You spelled pwershell.exe wrong somewhere, check `terminal.integrated.shell.windows` in your settings.json file.
