### ISSUE TITLE
Test unified undo/redo/copy/paste/find actions in Notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#103860]
re https://github.com/microsoft/vscode/issues/102441, https://github.com/microsoft/vscode/issues/103861

- [x] macOS @egamma
- [x] windows @bamurtaugh

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103860%0A%0A)

---

Previously we create dedicated commands/actions for undo/redo/copy/paste/find/replace in Notebook. This iteration, we merged them into the editor commands, so users can use the keybindings they are familiar with and also run these commands through Menu. 

Install GitHub Issue Notebook and test

* Undo/Redo/Find/Replace through Keybindings or Menu. The behavior should be consistent no matter if the focus is in an embed Monaco editor in notebook, or on the notebook cell container.
* Copy/Cut/Paste through Keybindings or Menu.
* Copy in notebook:
  * Select some text in cell editor and then copy
  * Run a query, select some text in the ouputs and then copy
  * Switch the output mime type to `text/markdown`, select some text and then copy
  * Make sure in all three scenarios, the right text is copied into the clipboard

**Comment by rebornix** [comment]
Undo/Redo was hijacked by webview actions in today's Insiders, fixed by https://github.com/microsoft/vscode/commit/e64364ffaa94a95e2c5dc295697364ab8090e59a and should be good from tomorrow Insiders.

**Comment by bamurtaugh** [comment]
@rebornix I see Erich opened an issue about Undo/Redo. Closing issue for now, but if you'd like us to re-test after tomorrow's Insiders, please just let me know, and I'd be happy to re-open and test again.
