### ISSUE TITLE
Open wrong file on the browser

### ISSUE THREAD

**Issue by crespo21** [microsoft/vscode#103817]
Opened a different file and clicked "Go live" but see a different file on the browser. Navigated locally on my machine, deleted that file even in my Trash box, and close vs code, reopened, clicked "Go live" still the deleted file is running.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you using https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer extension for "Go live"? If yes - you should report this problem in extension's repo.
