### ISSUE TITLE
Extension ... menu missing actions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#103812]
Stable

![Screenshot 2020-08-03 at 09 17 05](https://user-images.githubusercontent.com/1926584/89155925-1bed2f00-d56a-11ea-851d-a0072533e30e.png)

Insiders

![Screenshot 2020-08-03 at 09 17 17](https://user-images.githubusercontent.com/1926584/89155939-23acd380-d56a-11ea-836c-695a10c34052.png)

I love shorter menus, but this is probably a bug, a some of those actions should be under a submenu, for example Sort.

fyi @joaomoreno since you wokred on menu submenu changes

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/89156547-278d2580-d56b-11ea-94d4-c8f9909aa64c.png)
