### ISSUE TITLE
Test: GitHub authentication sample extension

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#103867]
Refs: https://github.com/microsoft/vscode/issues/100995

- [x] anyOS @alexdima
- [x] anyOS @bamurtaugh

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103867%0A%0A)

---

Please read through the new sample extension showing how to authenticate to GitHub: https://github.com/microsoft/vscode-extension-samples/tree/master/github-authentication-sample

Test that the extension runs as expected, and that the comments and code are clear. Note that the link to `authentication.getSession` in the API will be broken until we publish the website.

**Comment by bamurtaugh** [comment]
I believe the comments and code look clear to me- left a minor suggestion in the remaining open issue. And it looks like the PR just merged for the other issue did fix the npm problem!
