### ISSUE TITLE
Nightly build of of JS Debugger does not consistently stop at breakpoints.

### ISSUE THREAD

**Issue by captainkout** [microsoft/vscode#103844]
- VSCode Version: 1.47.2
- OS Version: Windows 10 Enterprise 10.0.18362 build 18362
- Extended Version information
Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Execute command via powershell/cmd/bash  "start chrome http://localhost:4200/hicris/home/welcome --remote-debugging-port=9222"
2. run command via powershell/cmd/bash "ng serve hicris-web"
3. set breakpoint in file in VSCode
4. run "Attach to chrome" debugger-routine then navigate to the appropriate page
5. Detach and re-attach, refresh the page until the breakpoint is hit. The inconsistency is the problem. After navigating to a page, it often take 3-5 detach then reattach cycles before execution stops on specified breakpoint.

Does this issue occur when all extensions are disabled?: No, but the extension necessary to duplicate the issue.

**Comment by connor4312** [comment]
Thanks for the issue, and for using nightly! Can you grab a trace log using these instructions?

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

/needsMoreInfo

**Comment by JDWilson1980** [comment]
Engage(cybercomm.playbook.devops)
Repo(faults.err.helpBot)
Repo(Tech.cyber.info)
Repo(mirror.co/global)
Repo(string.build.kueber)
Repo(err.moot.com)
Repo(reports.law.zoom)
Repo(Azure.Acess.Cloud)
Repo(Bug.info.nationwide)
Repo(indeed.bot.class)

**Comment by captainkout** [comment]
(top section is in debug file "0")
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/5022164/vscode-debugadapter-0.json.gz)
I think this is a related situation with a visual to accompany it, which isn't always possible. In the image below, I set a breakpoint, the breakpoint was "unbound." Sometimes unbound means that the file has been changed. I have not changed this file. Navigating to menu option "File > Save All" is disabled and there are no unsaved files in the workspace. However, when I press "ctrl+s" the project is recompiled (console = "[WDS] App updated. Recompiling" and "[WDS] App reloading", the browser page refreshes, but the breakpoint remains unbound.
![image](https://user-images.githubusercontent.com/13241145/89295008-54eed780-d62e-11ea-9dfc-736e9e39a171.png)
![image](https://user-images.githubusercontent.com/13241145/89295440-ff66fa80-d62e-11ea-8714-515ba5a7e0ea.png)


(below is in debug file "1")
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode/files/5022168/vscode-debugadapter-1.json.gz)
After taking those images, I unattach the debug session, and the second breakpoint from the image disappears. I refresh the browser and navigate back to the page, the breakpoint is hit.
![image](https://user-images.githubusercontent.com/13241145/892957

**Comment by captainkout** [comment]
I have another expansion on this issue or a slightly different expression of the problem. 
[vscode-debugadapter-3.json.gz](https://github.com/microsoft/vscode/files/5022721/vscode-debugadapter-3.json.gz)

I have an unbound breakpoint, no unsaved files in the workspace, but repeated presses of "ctrl+s" will recompile the project indefinitely. The image below is the first instance of saving.
![image](https://user-images.githubusercontent.com/13241145/89306208-89b65b00-d63d-11ea-81e0-dc8e09244158.png)
Showing there are no unsaved files.
![image](https://user-images.githubusercontent.com/13241145/89306288-a783c000-d63d-11ea-8688-03fd772d121e.png)
No changes made, I simply pressed "ctrl+s" again after the previous recompile and browser page had been refreshed.
![image](https://user-images.githubusercontent.com/13241145/89306405-d0a45080-d63d-11ea-8322-80d87edb27da.png)

**Comment by captainkout** [comment]
I verified that turning the prettier extension and also setting edit.formatonsave did not resolve this issue. 
![image](https://user-images.githubusercontent.com/13241145/89677527-99db6e00-d8bb-11ea-96f3-5bc23ff86858.png)

**Comment by connor4312** [comment]
Thanks for the detailed logs and info:

In your first comment, it looks like the breakpoint was in the wrong place after one or more page reloads. I know there are some cases where reloading sources / loading new sources doesn't update cached sourcemaps correctly. I will look into that in the immediate future.

In the second comment with being unable to attach, it looks like we got a connection refused on localhost:9222. This isn't an issue with the debugger; it indicates Chrome wasn't listening on that port. Maybe the browser wasn't launch/wasn't launched correctly, or something happened to cause Chrome to stop listening on that port. In the second log, it looks like Chrome failed to load your site, presenting the chrome error page, telling us that the top frame is

```
{
  "id": "B3BF2754B0517B8318B5B4AB6248768F",
  "loaderId": "ADA93D9520EDD3A10461579E9B23DF4D",
  "url": "chrome-error://chromewebdata/",
  "securityOrigin": "://",
  "mimeType": "text/html",
  "unreachableUrl": "http://localhost:4200/hicris/home/welcome"
}
```

**Comment by connor4312** [comment]
Tracking the reload issue in https://github.com/microsoft/vscode/issues/101762

/duplicate
