### ISSUE TITLE
Test taskDefinition when property

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#103835]
Refs: https://github.com/microsoft/vscode/issues/102477

- [x] macOS @JacksonKearl
- [x] linux @weinand
- [x] windows @rebornix

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103835%0A%0A)

---

The task definition contribution point now has a `when` property that allows entire task types to be removed from all task entry points:
```
    "taskDefinitions": [
      {
        "type": "typescript",
        "required": [
          "tsconfig"
        ],
        "properties": {
          "tsconfig": {
            "type": "string",
            "description": "%taskDefinition.tsconfig.description%"
          },
          "option": {
            "type": "string"
          }
        },
        "when": "shellExecutionTasksSupported"
      }
    ],
```

There are three suggested values to use with the `when` property:  `shellExecutionSupported`, `processExecutionSupported`, and `customExecutionSupported`. You can start with the [task provider sample](https://github.com/microsoft/vscode-extension-samples/tree/master/task-provider-sample), or with the one of the built in task providing extension, such as npm.

Verify: 
- That `shellExecutionSupported`  and `processExecutionSupported` cause the task type to only be available when shell and process are supported.
- That setting the `when` property to another context value works
- That, by default, a task definition without a `when` is available.
- That the json description for the `when` property makes sense.

**Comment by weinand** [comment]
I was not able to get the [task provider sample](https://github.com/microsoft/vscode-extension-samples/tree/master/task-provider-sample) to work on linux (mostly because setting up a Rake project was not as straightforward as I thought).

But VS Code's builtin npm task provider was working fine.

**Comment by JacksonKearl** [comment]
Looks good, tested on the npm provider. Neat to be able to use `config.*` keys in there.

**Comment by JacksonKearl** [comment]
> That `shellExecutionSupported` and `processExecutionSupported` cause the task type to only be available when shell and process are supported.

Could you explain this further? Not sure how to get into a state where only one or the other of these would be supported.
