### ISSUE TITLE
Markdown preview indented images overlap preceeding text 

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#103848]
- VSCode Version: 1.48 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open a Markdown file with an indented image (3 spaces) such as vscode-docs\docs\containers\quickstart-node.md
2. Open Markdown preview (same editor group or side-by-side)

Notice that image overlaps proceeding line of text. Following text link is fine.

![image](https://user-images.githubusercontent.com/12818376/89209427-23fd9c80-d573-11ea-859d-4a15dad7002b.png)

Does not reproduce if the image isn't indented. Does not repro on Stable

**Comment by mjbvz** [comment]
Result of https://github.com/microsoft/vscode/issues/102036

@jasonwilliams Can you please test the fix I just pushed (bd11c7f95ada261400e797d19dd0e2de00ab39cc) to make sure the original problem with the header/paragraph spacing still looks ok

**Comment by jasonwilliams** [comment]
My insiders only goes up to Commit: 5696babbc1dce41788bae04b1a04ad35140bebfb
@mjbvz

**Comment by mjbvz** [comment]
Fix will be in the next insiders

**Comment by jasonwilliams** [comment]
@mjbvz still looks ok Commit: 62503719349d04686a0704f7646b761aaf495b3d
