### ISSUE TITLE
package.json debug button not shown

### ISSUE THREAD

**Issue by fyangstudio** [microsoft/vscode#103810]
- VSCode Version: 
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
- OS Version: 10.15.6

Steps to Reproduce:

1. Open contains "scripts" key's package.json file.

Does this issue occur when all extensions are disabled?: Yes
My VS Code:
![image](https://user-images.githubusercontent.com/9896768/89145765-5c59a680-d584-11ea-918b-44fe852448dc.png)

Expect debug button show:
![image](https://user-images.githubusercontent.com/9896768/89145635-f40ac500-d583-11ea-89b8-455bae2463dd.png)

**Comment by connor4312** [comment]
What are the values of the settings `editor.codeLens` and `debug.javascript.codelens.npmScripts`?

**Comment by fyangstudio** [comment]
![image](https://user-images.githubusercontent.com/9896768/89245727-0b0cee00-d63c-11ea-8e09-588cffaf8c87.png)
thx,  after i open `editor.codeLens` switching, the bebug button shown
