### ISSUE TITLE
Do not terminate active running task when running another

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [Microsoft/vscode#10388]
It would be nice if there would be ability to run multiple tasks without killing that once already running like in webstorm.
e.g. i Have active gulp watch task but meanwhile i need to run another gulp task (like generate some code) and vscode now suggest me to kill watch task before running another. 

If it possible can you share how because I cannot find anything on google.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/981
