### ISSUE TITLE
Test: Authentication providers - consumer API

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#103871]
Refs: https://github.com/microsoft/vscode/issues/100993

- [x] macOS @sandy081
- [x] linux @9at8
- [x] windows @bamurtaugh
- [x] windows @eamodio 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103871%0A%0A)

---

In this iteration, part of the `authentication` API has been moved to stable, allowing extensions to consume GitHub and Microsoft authentication.

Please test that
- The API itself is clear, comments are readable and contain enough information, and names make sense.
- `getSession` behaves as expected with different options passed into it.
-  Calling `getSession` causes the authentication provider to activate if it has not done so already; there shouldn't be any issues with accessing a session immediately on startup.
- `onDidChangeSessions` is fired on login and logout

**Comment by eamodio** [comment]
Great work!

**Comment by sandy081** [comment]
Works great 👏
