### ISSUE TITLE
Execution Count/Green Check - Native Notebook Editor

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#103892]
Users during Python Extension Native Notebook QP were running cells and had difficulty understanding if the cells had run or not. 
This was due to the fact that the green check and execution time were not always displayed in the bottom toolbar (when execution was extremely fast) and that the execution count was not always displayed (covered by hover mode). 

Changes necessary: 
- Display execution count at all times 
- If cell has been run have green check always appear, regardless of how short the execution time is

**Comment by rebornix** [comment]
> If cell has been run have green check always appear, regardless of how short the execution time is

@roblourens I'm not seeing green check markdown as well with our Jupyter sample.

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/89348654-c5fbb280-d661-11ea-9279-484fdbe09fa1.png)

?

**Comment by rebornix** [comment]
The python extension is listening to cell outputs change event and when it's empty, it clears the execution count

Call stack:

```
t.updateCellModelWithChangesToVSCCell = function(e, t) {
            switch (e.type) {
            case "changeCellOutputs":
                return function(e, t) {
                    if (!e.cells.every(e=>0 === e.outputs.length))
                        return !1;
                    return e.cells.forEach(e=>{
                        e.metadata.runState !== l.NotebookCellRunState.Running && (e.metadata.runState = void 0,
                        e.metadata.executionOrder = void 0),
                        e.metadata.statusMessage = void 0,
                        e.metadata.lastRunDuration = void 0,
                        e.metadata.runStartTime = void 0;
                        const n = a.findMappedNotebookCellModel(e, t.cells)
                          , r = e.metadata.runState !== l.NotebookCellRunState.Running;
                        t.clearCellOutput(n, r),
                        c.updateVSCNotebookCellMetadata(e.metadata, n)
                    }
                    ),
                    !0
                }(e, t);
```

cc @DonJayamanne

**Comment by roblourens** [comment]
The Python extension is reacting to cell outputs changing and clearing all these fields, probably reacting to the "clear outputs" command, but here it gets hit when a cell executes with no outputs. We will give extensions a better way to handle this with https://github.com/microsoft/vscode/issues/104137. I think we discussed that solution with @DonJayamanne last week
