### ISSUE TITLE
VS code hangs While using it 

### ISSUE THREAD

**Issue by shubham15gupta09** [microsoft/vscode#103808]
Hi 

I am using VS code version 1.47.3 on my PC

PC Specification :
Company  :HP
Processor : Intel i5 8250U
OS : Windows 10 ( build 2004 ) home single Language ( Preinstalled with the PC)

When Problem occur : 
1 ) When I open more files in the editor 
2 ) When I click some test and jumps to other file
3 ) When i type too fast.

This happens with VS code only . With other editor its working fine

**Comment by deepak1556** [comment]
Can you check if the issue happens with our exploration builds https://az764295.vo.msecnd.net/exploration/f0e1fbf4cb8c4c27d6290f0310f5a4d63597cd21/VSCodeUserSetup-x64-1.48.0-exploration.exe

**Comment by shubham15gupta09** [comment]
No more issue ocured so closing the issue
