### ISSUE TITLE
Create WebView Panel with custom size and position in vscode API

### ISSUE THREAD

**Issue by AZbang** [microsoft/vscode#103828]
Now, when creating a new webview panel, I can specify the viewColumn, but I cannot specify which side and with what fixed size I want to open this panel.

For example, I want to open a panel from the bottom with a fixed height of 400px. For this I would like to do something like this:
```ts
vscode.window.createWebviewPanel(
      'webview', 'Webview',
      vscode.ViewColumn.Custom, // for custom column
      {
        viewPosition: vscode.ViewPosition.Bottom, // Up, Left, Right,
        viewSize: 400 // Fixed size for resizable side (for up and bottom it height, for left and right -- width),
        viewSize: 1/4 // Or maybe I want create panel with 25% size from available space for panels
      }
);
```

**Comment by mjbvz** [comment]
We don't give extension direct control over editor sizing and don't plan on adding this specifically for webviews (although, if we ever expose an API for controlling editor size, webview would should support it)

[Webview views](https://github.com/microsoft/vscode/issues/46585) are often the better fit for cases where you'd want a specific sized webview
