### ISSUE TITLE
Duplicate autocomplete suggestions in latest monaco build

### ISSUE THREAD

**Issue by basarat** [Microsoft/vscode#10389]
- VSCode Version: Master
- OS Version: MacOSX

Steps to Reproduce:

1. Build latest monaco
2. Try autocomplete with any language e.g CSS 
3. See duplicates in autocomplete

<img width="631" alt="screen shot 2016-08-10 at 9 31 09 pm" src="https://cloud.githubusercontent.com/assets/874898/17552217/e8ddb4a6-5f41-11e6-9a37-c63097dd76b9.png">

**Comment by aeschli** [comment]
To reproduce run monaco-editor standalone server and run
http://localhost:8080/monaco-editor/test/index.html?editor=dev#sample - css

**Comment by basarat** [comment]
Thanks! 🌹❤️
