### ISSUE TITLE
Up arrow key not working R shell in integrated terminal (v1.47.3 / Windows 10.0.18363)

### ISSUE THREAD

**Issue by mrechesketch** [microsoft/vscode#103801]
This issue is pretty strange. One day my arrow keys to recall previous commands stopped working. I have two computers running visual studio code (v1.47) and R (versions 3.5.0 and 3.6.3) and both of them no have arrow key functionality. It took several weeks for the 2nd computer to stop working. It mysteriously stopped working after I caused an error in the interpreter.

- Launching cmd and R on it's own works
- Launching external terminal from VS code also works
- When I change the version of R to 4.0.2, the arrow keys seem to work

Unfortunately one of the libraries I am dependent on has not been implemented in R 4xx so I can't make the switch yet. I've seen this issue previous resolved in previous versions. Anyone else getting this issue too?

Thanks,
Alex

**Comment by Tyriar** [comment]
I think R and some other shells have always had some issues with arrow keys, but they seem to be fixed in the latest version of R. You can reach out to them to see if it's possible to backport the fix?
