### ISSUE TITLE
Markdown dropdowns automatically collapse in preview when being edited

### ISSUE THREAD

**Issue by DAmNRelentless** [microsoft/vscode#103804]
- VSCode Version: v1.47.3
- OS Version: Windows 10 2004 64 Bit

Steps to Reproduce:
1. open up a markdown file and create a dropdown menu like this:
```
<details>
    <summary>
        Testing Purpose
    </summary>

*Details*:
- test

*Info*:
- more test
</details>
```
2. open up the markdown preview and expand the dropdown menu
3. edit anything within the markdown file
4. the menu automatically collapses and you need to reopen it

Does this issue occur when all extensions are disabled?: Yes

I was mentioning this issue in an extension I thought was related to this but it seems like this is an internal bug because it has the same behaviour without the extension. You can find the submission here: https://github.com/yzhang-gh/vscode-markdown/issues/772

**Comment by DAmNRelentless** [comment]
@mjbvz Are the upvotes needed on the bot reply or is the triage bot only updating like every 24 hours to automatically add the feature to the backlog?

**Comment by DAmNRelentless** [comment]
Current workaround:
- add the `open` attribute to the `<details>` while editing
- make sure to delete them after done with editing

**Comment by DAmNRelentless** [comment]
I find this decision really sad and my personal opinion is that this was closed because it's hard to implement.
I find it very harsh to say that there is no plan to add this in foreseeable future if there are many upvotes from the community and just closing it.
If this is added in one year or maybe two, it would be fine but just closing it with no further explanation and reasoning is very sad to see from a community-driven software.

**Comment by mjbvz** [comment]
You are welcome to submit a PR.

I closed this because we don't plan on addressing it ourselves anytime soon and don't want to give people false hope by keeping it open forever
