### ISSUE TITLE
Test: Run Smoke Test

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#103819]
- [x] Windows @lszomoru
- [ ] macOS @RMacfarlane  
- [x] Linux @deepak1556
- [x] Web (Chromium, anyOS) @lszomoru 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103819%0A%0A)

---

**NOTE:** Desktop & Web tests MUST run with `--build` argument

**NOTE:** Desktop tests MUST run with `--stable-build` argument additionally

Documentation: https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md#run.

If the automated tests fail, create and issue for that and run the tests manually: https://github.com/microsoft/vscode/wiki/Smoke-Test

**Comment by lszomoru** [comment]
Desktop smoke tests on Windows passed using the following builds:
- Stable - 1.47.3, 91899dcef7
- Insiders - 1.48.0-insider, 7906d414c0

Web smoke tests on Windows, Chromium using Insiders - 1.48.0-insider, 7906d414c0, contain a failed test. Filed issue for it.

**Comment by deepak1556** [comment]
for the stable build test on linux, there was one flaky test

```
Stable vs Insiders Smoke Tests: This test MUST run before releasing by providing the --stable-build command line argument
         Datamigration
           verifies that 'hot exit' works for dirty files:
     Error: Timeout: is active element '.editor-instance .monaco-editor[data-uri$="Untitled-1"] textarea' after 20 seconds.
      at /home/demohan/github/vscode/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/demohan/github/vscode/test/automation/out/code.js:9:58)
```

but a rerun made it pass, just heads up.

**Comment by RMacfarlane** [comment]
All tests passed on Mac 🎉
