### ISSUE TITLE
Test view visibility contribution point finalization

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#103833]
Refs: https://github.com/microsoft/vscode/issues/101283

- [x] macOS @rebornix 
- [x] macOS @sandy081
- [x] linux @gregvanl
- [x] windows @misolori

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103833%0A%0A)

---

The `visibility` property has been added to views, which can be set to `visible`(default), `hidden`, or `collapsed`
```json
    "views": {
      "explorer": [
        {
          "id": "npm",
          "name": "%view.name%",
          "when": "npm:showScriptExplorer || config.npm.enableScriptExplorer",
          "icon": "images/code.svg",
          "visibility": "hidden"
        }
      ]
    }
```

Using any extension that contributes a view as a starting point, set the `visibility` of the view.
Verify: 
- That the `visibility` is only respected when the visibility state of the view hasn't already been set by the user (launch VS Code with a fresh user-data-dir to test)
- That `visible` is the default
- That `hidden` and `collapsed` both work
- That all json descriptions make sense.

**Comment by sandy081** [comment]
Works great 👍
