### ISSUE TITLE
Submenu positioning broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#103815]
![image](https://user-images.githubusercontent.com/22350/89160344-324ab900-d571-11ea-9852-76101d7efe5e.png)

![image](https://user-images.githubusercontent.com/22350/89160401-4b536a00-d571-11ea-9136-3dbd0af52553.png)

**Comment by IllusionMH** [comment]
No problem if `workbench.sideBar.location` set to `"right"` but same behavior for `"left"`
