### ISSUE TITLE
Test: Submenu API

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#103832]
Refs: https://github.com/microsoft/vscode/issues/100172, https://github.com/microsoft/vscode/pull/102784

- [x] macOS @deepak1556
- [x] linux @roblourens
- [x] windows @alexr00

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103832%0A%0A)

---

You're going to have to write an extension, so let me offer my condolences upfront. But there are good and bad news. Good news is that you don't have to write much Type/JavaScript. Bad news is that you're going to have to write a bunch of JSON. 😛 

As a reminder, here's how you can create a base extension, you can choose JavaScript to keep it simple:

```
npm install -g yo generator-code
yo code
```

**Note:** This API is still proposed, so add the following to `package.json`:

```json
"enableProposedApi": true
```

Contributing a submenu via API is a two step process: first you contribute the submenu as its own entity, then you reference it from other menus. Here's the full syntax: https://github.com/microsoft/vscode/issues/100172#issuecomment-645203070. Notice the difference between referencing a command and a submenu, when adding menu items to a menu.

- You should be able to contribute a submenu
- You should be able to reference submenus from most menus in the API (notable exclusions are `commandPalette` and `touchBar`)
- You should be able to reference submenus from any submenu
- Submenu contributions have labels (for textual menus) and icons (for action bars)
- Submenu references can have a `when` clause
- VS Code should offer good JSON support by suggesting fields and documenting as you edit `package.json`. This applies to the `contributes.submenus` section as well as `contributes.menus.SUBMENU_ID` sections. What isn't allowed

**Comment by gjsjohnmurray** [comment]
@joaomoreno when I try this with current Insiders I get the following:

![image](https://user-images.githubusercontent.com/6726799/89192057-b87bf500-d59b-11ea-878b-31cc450e24db.png)

**Comment by joaomoreno** [comment]
I assume you're referring to the `undefined` at the end, just pushed fix, thanks!

**Comment by gjsjohnmurray** [comment]
No, to the fact that it's proposed API. If that's how it's shipping in 1.48 then the tester(s) probably need to be aware.

**Comment by joaomoreno** [comment]
Oh. I can make that explicit.

**Comment by ghiscoding** [comment]
hey guys, I wrote a comment on the original issue #102109, I just realized I should have write it here... the UI is a bit broken on my side as I wrote in this [comment](https://github.com/microsoft/vscode/issues/102109#issuecomment-668097940) and I'm on Windows. More info in the comment that I referenced. Thanks.

**Comment by alexr00** [comment]
Very cool and useful API!
