### ISSUE TITLE
Test: Pure Notebook Output Renderer

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103885]
Refs: https://github.com/microsoft/vscode/issues/102644

- [x] anyOS @sbatten 
- [x] anyOS @devinvalenciano

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103885%0A%0A)

---

This month we introduced the concept of a "pure" renderer which is solely a webview/iframe-side bundle using the i/o from the renderer API.

- Make sure `"webview.experimental.useIframes": true` is set to be able to test debugging
- You can take one of two paths running this test plan:
    - If you own an existing impure notebook output renderer, convert it to the new API! 
         - You can use the [renderer starter code](https://github.com/microsoft/vscode-notebook-renderer-starter) or my pure branch of the [github issues notebook](https://github.com/microsoft/vscode-github-issue-notebooks/tree/pure-renderer) as guides
         - Let me know if you run into any difficulty or hiccups
    - Otherwise, you can use the Yeoman generator which already has been updated to the new API: https://github.com/microsoft/vscode/issues/101319
        - Ensure the test provider is good, as well as code without the test provider (you can generate a renderer for the mime type `x-application/github-issues` that will render output from Joh's github issue notebooks)
        - Test that you can debug the client side code, that it hot reloads as you change it, and is sane overall.

**Comment by sbatten** [comment]
@connor4312 after quite some time, I was able to figure out how to port my kusto extension into the new model. I very much like the code now, but let's chat tomorrow to talk about this since its hard for me to file issues as opposed to share my experience.

**Comment by roblourens** [comment]
Maybe @rebornix or I can join for that too?

**Comment by devinvalenciano** [comment]
I was able to complete the steps in the test item above, to the best of my knowledge.  Everything was functional, but one recommendation - the user could benefit from more documentation/guidance, especially in the generated README.md.  The README doesn't explain how to use the test provider, how to understand each component of the renderer, where to begin customizing, etc...  Unless you have a firm understanding of notebook architecture and mime types going in (which may be the only intended audience), it's going to be a challenge to get up to speed.
