### ISSUE TITLE
Execution Count Not Always Updated - Native Notebook Editor

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#103890]
Users during Python Extension Native Notebooks QP were running cells and the execution count was not being updated. 
Brackets remained empty with no number.

**Comment by rebornix** [comment]
@DonJayamanne can you confirm if the execution is set always from the Python extension?

**Comment by roblourens** [comment]
And if @DonJayamanne can't repro an issue then seeing the video might help. In theory this UI is totally driven by the extension.

**Comment by DonJayamanne** [comment]
> can you confirm if the execution is set always from the Python extension?

I can confirm we set the execution count.
@claudiaregio do we have a repro or the video for this.

**Comment by claudiaregio** [comment]
I was able to repro this just now. 

Could this be disguised as a run button not always responding bug? 

![Execution Count Not Updated](https://user-images.githubusercontent.com/19276747/89474738-46daad00-d73b-11ea-994f-5711a10db006.gif)

**Comment by rebornix** [comment]
Shared the same root cause as https://github.com/microsoft/vscode/issues/103892 .
