### ISSUE TITLE
C/C++ intellisense working weird not working all of a sudden

### ISSUE THREAD

**Issue by amithrc** [microsoft/vscode#103888]
- VSCode Version: 
Version: 1.47.3 (system setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

OS Version:
Windows 10 

Steps to Reproduce:

1. Installed remote ssh development, connected to the remote server
2. Installed c/c++ on the remote server
3. The connection is successful but sometimes the vscode says Searching include path (My header within the workfolder)
4) F12 usually takes me to the function definition but this longer works always take me to function declaration.

Here are the settings from JSON file

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            },
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c18",
            "cppStandard": "c++20",
            "intelliSenseMode": "${default}"
        }
    ],
    "version": 4

5) I tried to uninstall reinstall, downgrade upgrade :( couple of times spent a couple of hours
}
Does this issue occur when all extensions are disabled?: Yes/No

6) Most of the variables jumping to it say no definition found

7) All the header files cannot be included, its highlighted and when I hover on them, it says searching the include path. This was working great for almost a year without any trouble

**Comment by vljubisavljevic** [comment]
Same issue here
