### ISSUE TITLE
Provide command to "leave input focus"

### ISSUE THREAD

**Issue by macintacos** [microsoft/vscode#103845]
I'm trying to find a command to "leave current text input focus" such that, if you begin typing, your cursor does not enter text anywhere (essentially setting `inputFocus` to `false`). In my mind, I think it'd be the equivalent of clicking the title bar with the mouse. If this command exists, what is it, and if it doesn't exist, can it be added?

The above was the TLDR. Here's my reasoning:

I'm trying to adopt the [VSpaceCode](https://github.com/VSpaceCode/VSpaceCode) and [vscode-which-key](https://github.com/VSpaceCode/vscode-which-key) extensions into my workflow. A big thing about this workflow is the use of the `SPACE` key to invoke the extension. In the editor, this is easy enough with the Vim extension, since you can detect when you're in a specific mode and allow `SPACE` to invoke the extension when you're not entering text. However, when you're in a text input area outside of the editor (such as the Extensions Marketplace search box, the Search Panel search field, etc.), this gets a little bit complicated.

As one would expect, if you're in a text input field, hitting `SPACE` shouldn't invoke an extension, it should insert a `SPACE` character, which it does. However, because there doesn't appear to be a straightforward way in all text input fields to "leave focus", I now have two options as I see it to get this extension to work with the tools I have available to me now:

1. Change the invocation method from `SPACE` to some keyboard modifier + `SPACE` (undesirable, because the `SPACE` invocation is very convenient and is a big reason why I want to use this extension), or...
2. Lift my hands from the keyboard and use the mouse click on an element outside of the input field to make it "lose focus" so that I can hit `SPACE` to invoke VSpaceCode (this is also undesirable since I'd like to minimize my use of the mouse when in VSCode as much as possible).

I had originally (naively) thought that hitting `ESCAPE` would cause the input field to lose focus, mostly because when I think of the word `ESCAPE` I think of "get me out of where I am right now", i.e. "please lose focus", but (as evidenced by #103728) this is not expected behavior.

At the end of the day, I think this could be solved by a command that essentially just clicks the title bar in VSCode to "lose focus". This works today; if I'm in an input field and click the title bar, all input fields lose focus as expected, and I can then hit `SPACE` to invoke VSpaceCode. If this command were made available, I would map it to `ESCAPE` when in input fields that are not the editor, and I think that would solve my issue entirely.

Please let me know if any of the above doesn't make sense. Thanks!

**Comment by joaomoreno** [comment]
Command is `workbench.action.blur`.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/commit/0fe9f7ef1809103b5d56a80013c374b87e7821a6
