### ISSUE TITLE
persistent notification covers the settings button when panel is on the right

### ISSUE THREAD

**Issue by LER0ever** [microsoft/vscode#103829]
This is a UX nitpicking. Currently whenever there is a long-running notification that cannot be dismissed, the "Settings" gear icon will be covered and not clickable if the user moves the panel to the right.

- VSCode Version: 1.47.3
- OS Version: Windows 10 2004

Steps to Reproduce:

1. Move panel to the right (Ctrl-P: "View: Move Panel Right")
2. Let, for example, the C++ extension to install the required dependencies, just like the screenshot below.

![image](https://user-images.githubusercontent.com/10568668/89179219-de1bf500-d5c1-11ea-9edb-4d006cc96557.png)

Does this issue occur when all extensions are disabled?: Yes/No
No, because then there will be no such notifications at all...

**Comment by sbatten** [comment]
@misolori should we just offset it by the activity bar width or do you have something better?

**Comment by misolori** [comment]
@sbatten yea I'd say activity bar (48x) + 8px (the current offset)

**Comment by sbatten** [comment]
I think the notification center which originates from the status bar, needs to remain in place and it is dismissible. However, the toasts need to be moved or be dismissible. This creates a bit of awkardness I think.

![image](https://user-images.githubusercontent.com/6561887/137788090-74fc58b8-0ae4-4f38-aab1-72cfce5f8da3.png)


![image](https://user-images.githubusercontent.com/6561887/137788107-d8eb30e6-950f-486d-9c89-90ed42fc95ea.png)

**Comment by benibenj** [comment]
Closing as notifications can be dismissed. Also, there is a issue open for showing settings dropdown using command palette.
