### ISSUE TITLE
Test important exe based recommendation for WSL

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#103851]
Testing https://github.com/microsoft/vscode/issues/101903

- [x] windows @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23103851%0A%0A)

---

Regression testing: Since syntax of exe based recommendations was changed in this milestone, please test 
- WSL extension is recommended if you have WSL installed on your system and you do not have WSL extension installed

**Comment by alexr00** [comment]
Uninstalled the WSL extension, then re-launched VS Code with a new --user-data-dir. WSL extension was recommended.
