### ISSUE TITLE
Can I show some message after change extensions.all ?

### ISSUE THREAD

**Issue by shangchengxiang** [microsoft/vscode#103825]
```
export namespace extensions {

		/**
		 * Get an extension by its full identifier in the form of: `publisher.name`.
		 *
		 * @param extensionId An extension identifier.
		 * @return An extension or `undefined`.
		 */
		export function getExtension(extensionId: string): Extension<any> | undefined;

		/**
		 * Get an extension by its full identifier in the form of: `publisher.name`.
		 *
		 * @param extensionId An extension identifier.
		 * @return An extension or `undefined`.
		 */
		export function getExtension<T>(extensionId: string): Extension<T> | undefined;

		/**
		 * All extensions currently known to the system.
		 */
		export const all: ReadonlyArray<Extension<any>>;

		/**
		 * An event which fires when `extensions.all` changes. This can happen when extensions are
		 * installed, uninstalled, enabled or disabled.
		 */
		export const onDidChange: Event<void>;
	}
```

 I see this api can happen after extensions.all changed , so I want to show some messages to users . 
But I don't know how to use them . 
I'm write a example but it doesn't work.
Just like this : 
```
public static extensionsChangeListening() {
        vscode.extensions.onDidChange(() => {
            this.showInfo('success');
            console.log('success');
            vscode.window.showWarningMessage('success');
        });
    }
```
If this api can't be used like this , please tell me how to use it .

**Comment by shangchengxiang** [comment]
Emmm  today i have atry . It's already does work.  I have a question . Can this api discriminate different  Scenarios. For example , installed ,uninstalled ,enabled or disabled . Because i want to show different messages to users . My English is not perfect ,please forgive me .

**Comment by shangchengxiang** [comment]
Emmm.  Today i have a try again . It's already does work. I have a question . Can this api discriminate different Scenarios. For example , installed ,uninstalled ,enabled or disabled . Because i want to show different messages to users . My English is not good ,please forgive me .

**Comment by shangchengxiang** [comment]
Emmm. Today I have a try again . It's already does work. I have a question . Can this api discriminate different Scenarios. For example , installed ,uninstalled ,enabled or disabled . Because i want to show different messages to users . My English is not good ,please forgive me .

**Comment by shangchengxiang** [comment]
Emmm. Today I have a try again . It's already does work. I have a question . Can this api discriminate different Scenarios ? 
For example , installed ,uninstalled ,enabled or disabled . Because i want to show different messages to users . 
My English is not good ,please forgive me .

**Comment by alexdima** [comment]
@shangchengxiang :+1: You are using the API correctly. There is no further details regarding the root cause for the change.
