### ISSUE TITLE
Unexpected order of fuzzy find results

### ISSUE THREAD

**Issue by drew-gross** [microsoft/vscode#103889]
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/558242/89243324-888f1a80-d5b8-11ea-9e3e-4feed19ab333.png)

1. Create a folder with files names `managed_object.h.template` and `generated_types.h.template`
2. Open fuzzy find and type `gt.h.template`
3. Expect **g**enerated_**t**ypes.h.template to be found first, instead managed_object.h.template is found first

It's unclear whether this is intentional, and I'm not sure how fuzzy find is intended to work, but coming from Sublime Text, the current behaviour is not very intuitive to me. Sublime Text puts **g**enerated_**t**ypes.h.template first.

![image](https://user-images.githubusercontent.com/558242/89243503-f76c7380-d5b8-11ea-8910-c7ad20771059.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This is a consequence of our scorer preferring consecutive matches the longer they get. `gt.h.template` is having more consecutive matches on `generated_types.h.template` compared to `managed_object.h.template`.

If you leave out the dots, it will sort properly:

![image](https://user-images.githubusercontent.com/900690/90116653-13f57200-dd56-11ea-81de-9394fee30dcc.png)
