### ISSUE TITLE
VS Code launches itself when I plug in a USB drive 

### ISSUE THREAD

**Issue by rushikesh-mallanath** [microsoft/vscode#103849]
Issue Type: <b>Bug</b>

VS Code launches itself when I plug in a USB drive -- never requested

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 5.4.0-42-generic

**Comment by Tyriar** [comment]
This must be an OS thing, nothing to do with vscode.
