### ISSUE TITLE
Git commit message limited to 50 characters while other tools dont have that limit

### ISSUE THREAD

**Issue by andrew-maust** [microsoft/vscode#103803]
- VSCode Version: 1.47.3

- OS Version: MacOS Catalina 10.15.6

Steps to Reproduce:

1. Stage a change in a git/github repository 
2. Type a message in the message box
3. Observe the 50 character limit

Does this issue occur when all extensions are disabled?: **Yes**

The reason that I feel that this is a issue is because Github desktop doesnt have this limitation on it.

**Comment by andrew-maust** [comment]
If this is deemed to be a valid bug depending how how difficult this task would be I would like to give it a shot

**Comment by andrew-maust** [comment]
Upon further inspection it appears that the warning doesnt do anything and it still allowed you to make the message and the line changes dont show anything in github so maybe it doesnt need edited it might need removed im not sure

**Comment by gjsjohnmurray** [comment]
Did you try looking for a setting that controls this warning?

**Comment by joaomoreno** [comment]
Settings to control this are: `git.inputValidationLength`, `git.inputValidationSubjectLength`

**Comment by andrew-maust** [comment]
Thank you sorry for not looking closer haha
