### ISSUE TITLE
"copy/paste cell" should not copy metadata

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#103881]
- Execute a github issue cell
- Copy/paste the cell
- The new cell has the same run state metadata, it should actually have the default new cell metadata

**Comment by rebornix** [comment]
This is interesting, I guess we should only copy `custom` metadata and leave others default?

**Comment by roblourens** [comment]
I dunno, or maybe it's a case for run state metadata just being different. Or actually, should it copy the outputs as well? Then this metadata would make sense

**Comment by JDWilson1980** [comment]
Playbook.phishing.com/hacks

**Comment by roblourens** [comment]
But not if it's in the "running" state. Uhhhh

**Comment by rebornix** [comment]
I made a few changes to copy/paste cells. We will only copy metadata which are not execution related, e.g., editable, runnable, etc. `execution_count`, `lastRunDuration`, etc are now treated in the same way as outputs.
