### ISSUE TITLE
The 'details' link in the settings sync turned on notification opens the Tasks output channel

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#103927]
Testing #103604

I've enabled settings sync.
Clicked on the 'details' link opens the Output panel with the 'Tasks' channel selected. 
I would have expected that this link shows some settings sync specific log
![image](https://user-images.githubusercontent.com/172399/89275834-1c0d2d80-d643-11ea-8fb4-c1ddc3d14338.png)

**Comment by sandy081** [comment]
@egamma I cannot repro it.

If you can repro, can you please expand the output channels dropdown and check if Settings Sync log exists or not?
