### ISSUE TITLE
Need to be able to set the size of the undo history

### ISSUE THREAD

**Issue by daden** [Microsoft/vscode#10396]
- VSCode Version: 1.3.1
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Make many changes in a file.
2. Try to undo them. 

I haven't counted but it seems that it will only go back about 20 - 25 changes. I would like to be able to set this higher but don't see a config setting for it.

**Comment by jrieken** [comment]
Actually there is no limit to the undo history so it must be something else... @daden Any chance the file did change in anther editor? In that case we would drop the undo history cos we don't know what happened outside

**Comment by sandy081** [comment]
Closing this issue since we did not get enough info. Please provide required info and reopen. Thanks.

**Comment by idibidiart** [comment]
Problem: vscode does not have deep enough undo history. 

What other info do you need?

**Comment by akanshgulati** [comment]
@sandy081  I think you should reopen it. There should be a setting to store more past code change history in VSCode, we could simply provide a numeric value of number of changes VSCode has to retain in history so that we can `Undo` it easily.
