### ISSUE TITLE
For kids of India; for android.

### ISSUE THREAD

**Issue by lkiThakur** [microsoft/vscode#103963]
**VS code editor for phone (especially android).** 
New education policy of India (2020) asks students to start coding from 6th grade
India has largest number (315 million) of students in the world but most of them are not financially capable of having a laptop so gifting them with a code editor for android will be of great help. I know coding without laptop is laughable as it is to study without personnel lighting source, but there are peoples who did the latter & now there are kids asking for a chance to do the former.
I know I was not worthy of writing this to the peoples who already know a lot about end user needs and market opportunities but I was unable to sit idle at this situation.
Links:  [Education policy New](https://www.thequint.com/news/india/new-education-policy-students-to-learn-coding-from-class-6th-onwards#:~:text=The%20New%20Education%20Policy%20allows,coding%20from%20class%206th%20onwards.&text=According%20to%20the%20New%20Education,as%20early%20as%20class%206th)
[315 million students-Times of India](https://timesofindia.indiatimes.com/india/At-315-million-India-has-the-most-students-in-world/articleshow/37669667.cms )

**Comment by sana-ajani** [comment]
Hi, thanks for creating the issue and bringing this up. We are interested in making VS Code more accessible for all and have recently created Linux ARM builds, which can work on Chromebooks and Raspberry Pi too. Unfortunately, supporting android devices is too out of scope for us.
