### ISSUE TITLE
Add indicator for the selected sort option

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#103941]
Testing #103615

Add a "tick mark" to indicate the selected sort option:

![image](https://user-images.githubusercontent.com/3372902/89290099-9e541c80-d658-11ea-9dc7-4be78f997fde.png)

**Comment by jrieken** [comment]
<img width="555" alt="Screenshot 2020-12-01 at 12 34 47" src="https://user-images.githubusercontent.com/1794099/100735554-b141e800-33d1-11eb-8ec2-1f472a0c6ee8.png">

That's all I see

**Comment by lszomoru** [comment]
@jrieken, it looks like the `Views` item is not present in the context menu when you search (expected @sandy081). If you clear the search field, you should see something similar in the context menu depending on the view that you have open:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/3372902/100739469-65923d00-33d7-11eb-9483-19b309a8aa05.png">

**Comment by jrieken** [comment]
I see the view thing but no "sort by" menu

**Comment by lszomoru** [comment]
sorry, my bad. it looks like indeed you need to run a search (ex: `foo`), then in the filter context menu there is an option to sort the search results. If you pick any of the options, the next time you open the context menu, you should see a `tick` that indicates the current sorting option:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/3372902/100744584-595dae00-33de-11eb-98a0-2cde07d7621e.png">

**Comment by sandy081** [comment]
- Search for extensions in Marketplace by typing some text or use the predefined filters in the filter menu
- Choose sort options from Sort by sub menu
- Make sure that check mark is shown for the sort option that is used.

**Comment by jrieken** [comment]
wow - it took me very long to find that menu
