### ISSUE TITLE
StopDebugging should have the session optional

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#103934]
Testing #103857

Current signiture 
```
		export function stopDebugging(session: DebugSession | undefined): Thenable<void>;
```
I propose the following

```
		export function stopDebugging(session?: DebugSession): Thenable<void>;
```

This makes the caller `vscode.debug.stopDebugging()` more nice compared to `vscode.debug.stopDebugging(undefined)` 

I think it will also align well with some existing editor API. Also I did not find any current debug api which has this semantic of `undefined = all`

**Comment by weinand** [comment]
Yes, I agree.
