### ISSUE TITLE
Split Button Creating Blank Lines - Native Notebook Editor

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#103993]
![Split Extra Line](https://user-images.githubusercontent.com/19276747/89341655-7794e680-d656-11ea-9a49-482da9d30d93.gif)

**Comment by rebornix** [comment]
Good catch.

Verifiers, please test two following cases:

First, create a code cell with two lines

```
a
b
```

put the cursor after `a`, split. The first cell should then contains `a\n`, and the second cell should be `b`

Second: insert a cell with three lines

```
a

b
```

Put the cursor at line 2, split. The first cell should then contains `a\n`, and the second cell should be `\nb`
