### ISSUE TITLE
Can't access a local file in html when I call the API 'vscode.showPreview'

### ISSUE THREAD

**Issue by 928PJY** [Microsoft/vscode#10392]
- VSCode Version:1.3.0
- OS Version:Win10

Just as the [markdown preview](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/extension.ts)  ,I want to load a .js file to render the html 
```ts
    public provideTextDocumentContent(uri: Uri): Thenable<string> {

        return workspace.openTextDocument(Uri.parse(uri.query)).then(document => {
            const content = [].concat(
                '<!DOCTYPE html>',
                '<html>',
                '<head>',
                '<meta http-equiv="Content-type" content="text/html;charset=UTF-8">',
                `<link rel="stylesheet" type="text/css" href="${this.getMediaPath('token.css')}" >`,
                '</head>',
                `<script type="text/javascript" src="${this.getMediaPath('render.js')}"></script>`,
                '<body>',
                `<p> This is a test</p>`,
                '</body>',
                '</html>'
            ).join('\n');

            return content;
        });
    }
```
And the render.js likes 

```js
   // Get JSON data
treeJSON = d3.json("test.json", function(error, treeData) {
   process(treeData)
}
```

But I can't access the 'test.json' unless I run 'http-server' , Is there a better way?
Any Help will be appreciated！！

**Comment by jrieken** [comment]
Yes - you should read the file when you 'generate' the html content and just inline the contents. You also might run a server but that isn't recommended

**Comment by stackerJobs** [comment]
I have met the same problem too , I am looking for a way to achieve the communication between the extension.ts and javascript loaded in the html. Is there some advise?
Any help will be appreciated!

**Comment by jrieken** [comment]
There are three options listed in order of preference

* Know stuff when generating the html 
* Signale a change using the [`onDidChange`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1308)-event of the provider
* Run a (http)-server on localhost and connect to it from the page (xhr or web sockets)
