### ISSUE TITLE
onDidChangeActiveTextEditor fires multiple time

### ISSUE THREAD

**Issue by badSmilie** [microsoft/vscode#103939]
Hello, 

I have a Problem with the onDidChangeActiveTextEditor event at the moment.
I have created an extension which opens a web view in a viewcolumn beside a code file to show a preview (looks like the .md preview).
example:
tab file A  tab file B | tab webView (always visible)
- When I first focus tab B then mouseclick inside the webView and after that click on tab A 
     -> the onDidChangeActiveTextEditor is fired multiple times in random order ex. first for tab A and then for tab B
- When I first focus tab B then click the TAB of the webView and after that click on tab A 
     -> the onDidChangeActiveTextEditor is called correctly once for tab A.

Maybe there is somekind of alternative for onDidChangeActiveTextEditor to get informed when a tab is focused?
Or is it possible to prevent the webView from getting the focus in any case?

**Comment by jrieken** [comment]
> is fired multiple times in random order ex. first for tab A and then for tab B

There is no Math.random in this... Can you please note down the sequence of events that you are seeing and the sequence you are expecting.

**Comment by jrieken** [comment]
> first for tab A and then for tab B

@bpasero to confirm but this is likely because the click first activates the group of editors and only then reaches the tab to reveal the other editor

**Comment by bpasero** [comment]
Tracing the editor events I see the following things happening:
* first: group gets active making the current editor active (B)
* second: editor corresponding to the clicked tab gets active (A)

I would not expect the events in the extension to be AB, rather BA if any... I did not check on that.
