### ISSUE TITLE
Diffs in "sync activity" view diff against current settings rather than previous version

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103971]
Testing #103613

I was kind of confused about what I saw in the "sync activity" view. Having gotten used to Git, I would have expected that the diff shown in the view compared against the previously synced version, but it actually compares against my local settings.

This comparison makes since because I don't really care about the diff history of settings, but maybe there's a way we can indicate what's happening more explicitly.

**Comment by RMacfarlane** [comment]
I was also confused by this view, the first thing I opened was a `globalState.json` diff where the entire left hand side was deleted and I didn't understand what I was looking at. I hadn't really paid attention to the timestamps, so I was actually expecting this to just show me what was on the remote, not a diff at all. I think it would be useful if the editor tab title were more verbose, "globalState.json <> globalState.json" didn't really give me any information.

**Comment by sandy081** [comment]
Here is the feature request to show diff with previous version - https://github.com/microsoft/vscode/issues/94203

Agreed that it is better to include some information that this is diff between remote and local. Updated the titles to represent that.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/10746682/89436389-7347f680-d746-11ea-8eac-78084f78d063.png">
