### ISSUE TITLE
Provide an option to disable syncing for absolute paths

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103968]
Testing https://github.com/microsoft/vscode/issues/103613

I've been using my windows PC for the last couple months and went to test on my mac. At this point I realized that I've had a bunch of absolute paths creeping into my settings file which I hadn't yet manually went and excluded from settings.

Since absolute paths in settings are likely to break between computers, it would be nice if there was some kind of prompt the first time settings sync is enabled which would discover absolute paths in the user settings and let them easily exclude these settings before the first sync happens.

**Comment by sandy081** [comment]
Unfortunately we do not know if a setting is a path setting or not, instead we allow extensions to provide a scope for a setting. Settings defined with `machine` or `machine-overridable` scopes are ignored during sync.
