### ISSUE TITLE
[Insiders][Git] Ability to customize "More Action" root level menus

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode#103916]
### Problem
Some of the actions that I (and possibly others) use frequently are now tucked away somewhere inside some nested menu. This is an extra thing to learn as a user and will hinder the workflow.

### Possible Solution
Ability to customize what should show up at the root level of the "More Actions" menu will help a lot in smoothing the workflow

### Detalis
VS Code Insiders - 1.48.0-insider
Platform - Windows 10

**Comment by joaomoreno** [comment]
> Some of the actions that I (and possibly others) use frequently are now tucked away somewhere inside some nested menu. This is an extra thing to learn as a user and will hinder the workflow.

As a programmer, my suggestion is to start getting used to <kbd>F1</kbd> to execute commands or, better yet, keyboard shortcuts which VS Code has excellent support for. The `...` menu exists for discoverability reasons, so it is bound to get filled with lots of actions. The new format is objectively better as it organizes similar actions together and declutters the view. Closing this as designed.
