### ISSUE TITLE
Find References leaks documents

### ISSUE THREAD

**Issue by kjeremy** [microsoft/vscode#103959]
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Turn on tracing for your LSP server of choice
2. Use find references on a symbol that resolves to a closed document
3. Watch that `textDocument/didOpen` is sent but `textDocument/didClose` is never sent to the server.

Does this issue occur when all extensions are disabled?: Yes/No

See https://github.com/microsoft/vscode-languageserver-node/issues/652 for a more complete description and video showing the problem.

**Comment by jrieken** [comment]
> sent but textDocument/didClose is never sent to the server.

What makes you think so?

**Comment by kjeremy** [comment]
All LSP traffic is logged and the close documentation never shows up in the
trace output. It does it I close a file though.

See the video in the linked issue.

**Comment by jrieken** [comment]
> See the video in the linked issue.

The video isn't 3 minutes long...

**Comment by kjeremy** [comment]
3 minutes? Are you saying that there is a timer that goes off in 3 minutes that would close the file?

**Comment by jrieken** [comment]
🙄 https://github.com/microsoft/vscode/issues/103959#issuecomment-671222576

**Comment by kjeremy** [comment]
Ha! Your response never showed up in my email which is what I was using to reply... 🤦

**Comment by kjeremy** [comment]
Okay I tried it and waited for 3 minutes and received the `didClose` notification at the end of those 3 minutes.
