### ISSUE TITLE
Dragging Cell Indicator - Native Notebook Editor

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#103994]
Steps to reproduce: 
1. Drag a cell to 2nd to last position in notebook - take note of blue line location
2. Drag a cell to last position in notebook - take note of blue line location

Actual Behavior: 
Blue line for the different locations above are in the same place (above print(one_hot_score) cell) 

Expected Behavior: 
When moving cell to last position in notebook, blue line should be below the last cell. 

![Blue Line Moving Cells](https://user-images.githubusercontent.com/19276747/89342607-e0309300-d657-11ea-89d4-c4ab7c29de12.gif)

**Comment by roblourens** [comment]
I think this was fixed with other dnd changes, I can't repro anymore
