### ISSUE TITLE
With some files, VS Code cannot find modules that exist

### ISSUE THREAD

**Issue by jankalfus** [Microsoft/vscode#10391]
Sometimes when I open my project, VS Code is unable to find imported external modules. I've got typings for the modules installed, all files in the project compiles fine using `tsc`, but I get red squiggly lines in the editor. The weird thing is that I get the squiggly lines only for some .tsx files, while it works for others.

The file src/web/App.tsx is fine:
![web](https://cloud.githubusercontent.com/assets/12714276/17553706/9f148050-5f07-11e6-8721-fd1e3a99cac2.png)

While I get squiggly lines for the file src/native/App.tsx:
![native](https://cloud.githubusercontent.com/assets/12714276/17553710/a3c8f266-5f07-11e6-9ab0-69ce23c46a0c.png)

My tsconfig.json content is the following:
```
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": false,
        "jsx": "react",
        "noImplicitAny": true,
        "experimentalDecorators": true,
        "module": "commonjs",
        "target": "es5",
        "rootDir": "src"
    },
    "exclude": [
        "node_modules",
        "src/native",
        "app",
        "app-native",
        "tools",
        "test"
    ]
}
```

Both `react ` and `react-native` are installed as global typings.

Unfortunately, I cannot post the source code right now, but basically, the structure of the source files is as following:
```
src
 |-- common
 |-- native
       |-- index.ts
       |-- App.tsx
 |-- web
       |-- App.tsx
 |-- index.ts (this one is for web)
```

- VSCode Version: 1.4.0
- OS Version: Windows 10

Any ideas?

**Comment by jankalfus** [comment]
I have noticed that if I use `File ->Close` folder and then `File -> Open Folder...` and open the project folder again, the errors are gone. If I just restart VS Code instead, I keep getting the errors. I presume that some internal cache gets cleared?

**Comment by jankalfus** [comment]
More to this issue: I get the errors every time I create a new folder and ts/tsx file inside. Unfortunately, the workaround I've suggested in the previous comment doesn't work.

**Comment by jankalfus** [comment]
I've published the source code. To reproduce this issue:
1. Go to [https://github.com/gina-system/react-starter](https://github.com/gina-system/react-starter)
2. Use the steps in the quick start section of the readme
3. Open the src/native/App.tsx file.

**Comment by dbaeumer** [comment]
@waderyan let me know when you need assistance

**Comment by waderyan** [comment]
I have reproduced this per @jankalfus's instructions. 

I'm seeing a "Cannot Find Module" when I hover over `react-native`

![image](https://cloud.githubusercontent.com/assets/2449568/17606916/068dccbc-5fd7-11e6-8096-6c8660be24ae.png)

Developer shows a seemingly unrelated error. 

![image](https://cloud.githubusercontent.com/assets/2449568/17606936/2b45a28c-5fd7-11e6-8238-3e6b2e4c6a91.png)

It seems like typings directory is configured correctly. 

![image](https://cloud.githubusercontent.com/assets/2449568/17607005/a209100c-5fd7-11e6-8c8a-5f8822d32573.png)

**Comment by waderyan** [comment]
Ok this is strange... I reopened the project to grab another screen shot and this is what I saw. 

![image](https://cloud.githubusercontent.com/assets/2449568/17607226/5336f65e-5fd9-11e6-9229-45b990156143.png)

Everything looks good now. 

I retraced my steps. 
1. re-cloned  https://github.com/gina-system/react-starter in a separate dir. 
2. followed the README steps (`npm install`, `typings install`)

Looks good again. 

Ping @dbaeumer please advise what to try next.

**Comment by dbaeumer** [comment]
@waderyan there is not much you can do. I would move it to the TS team since at the end of the day the error message is generated by the tsserver.

**Comment by waderyan** [comment]
Moved to [TypeScript](https://github.com/Microsoft/TypeScript/issues/10346)

**Comment by aquasan** [comment]
Closing VS Code and starting it again fixes the issue for me.
