### ISSUE TITLE
Not able to connect to Extension Marketplace 

### ISSUE THREAD

**Issue by madharamu** [microsoft/vscode#103977]
Not able install any extensitons from vscode. When we are trying it is showing warning message like below. 
"We cannot connect to the Extensions Marketplace at this time, please try again later."

When I open vs code in run as admin, then it is worknig fine
![VS Code extensions error](https://user-images.githubusercontent.com/17488990/89328955-c7ea6380-d6ab-11ea-9c64-e0958c2f1a6a.jpg)

**Comment by sandy081** [comment]
Seems proxy issue

**Comment by madharamu** [comment]
How to resolve this issue?

**Comment by chrmarti** [comment]
@madharamu  Could you start VS Code with `--log-net-log=netlog.json`, search for an extension like in your screenshot and then post the created netlog.json here? Also do this when running as admin, so we can compare the two logs.

**Comment by umer-ilyas** [comment]
I have same issue 

where is _netlog.json_ located , (i am using this on windows 10)

**Comment by madharamu** [comment]
When I run as admin the vscode working fine with connecting to extension
marketplace. But when I open vscode normally and try to connect market
place for extensions it is throwing error message as I mentioned earlier
"not able to connect to extension marketplace"

Is it anything to do with environmental variables? If so, please let me
know the details.

Thanks & Regards,
Ramakrishna Madha

**Comment by chrmarti** [comment]
You might have HTTP_PROXY or HTTPS_PROXY set.

**Comment by madharamu** [comment]
ALL_PROXY
HTTPS_PROXY
HTTP_PROXY

**Comment by madharamu** [comment]
Hi Microsoft/Vscode,

I have set below variables with my company address and port.
ALL_PROXY
HTTPS_PROXY
HTTP_PROXY

Thanks,
Ramakrishna Madha
