### ISSUE TITLE
Add a setting to disable notifications

### ISSUE THREAD

**Issue by sandorvasas** [microsoft/vscode#103907]
Could you please add a new setting to disable notifications? They are killing me. Every extension wants me to take a survey, showing updates are available, I should configure my XY env, how satisfied am I, should it report bugs, etc.. Hard to focus on development if VS code acts like Facebook and there are 5-6 notifications at a time on top of each other. And include a "don't show again" button when a VS code update is available or a "remind me later tomorrow"? whenever an update comes out, and I restart VS code, or just reload the window, the notification pops up. I have 4-6 instances of VS code running at once, and at each reload I have to dismiss them all if I want to install the update at a later time.

**Comment by zwhitchcox** [comment]
Please do this and also disable where they can joke open a random page every time you start the application.

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/90393736-ad18e580-e0d4-11ea-9d9d-2263690ee634.png)

Please make these stop, they are anything **BUT** helpful. In fact they are outright annoying when I spin a new instance of Code every few minutes.

**Comment by zwhitchcox** [comment]
Just want to turn off all notifications. I don't think I've ever seen a notifications that was actually helpful. Literally all they do is cause me to have to close them.

If you really insist on making me see your notifications, make them collapsible in the sidebar.

Literally anything to just turn off the useless notifications.

**Comment by ericalbers** [comment]
I agree All interruptions of ANY kind must be disabled by default.

To do otherwise is evil.

**Comment by Tandolf** [comment]
wow, that this feature doesn't exists already in vscode amazes me. How can it NOT exist.

**Comment by bpasero** [comment]
Merging into https://github.com/microsoft/vscode/issues/46676

**Comment by realdanielbyrne** [comment]
Please! Please! Please! The notifications are obnoxious.  They are an intrusion to creativity.  

Ralph Waldo Emerson once said, "Concentration is the secret of strength." 

Also from Og Mandino, "It is those who concentrates on but one thing at a time who advance in this world."  

This editor is specifically designed for people who make their livelihoods from concentrating.  It is therefore the anthesis of the purpose of this editor to systematically interrupt its user over and over and over again.

**Comment by stonecharioteer** [comment]
+1 Please implement this feature. The only time I need to use a mouse with vscode is to dismiss notifications. At least enable autotimeout, or give us a config to silence all of them, or selectively.
