### ISSUE TITLE
There is no task provider registered for tasks of type "cargo".

### ISSUE THREAD

**Issue by smokku** [microsoft/vscode#103942]
- VSCode Version: 1.47.3
- OS Version: Windows_NT x64 10.0.19041

### Steps to Reproduce:

With Rust (`rust-lang.rust`) and Rust Analyzer (`matklad.rust-analyzer`) extensions installed:

1. `Shift+Ctrl+P` -> `Tasks: Run Task` -> Select `cargo` -> Select `rust: cargo build`. Wait for build complete.
2. `Shift+Ctrl+P` -> `Tasks: Run Task` -> Select `rust: cargo build (recently used)`

#### Expected:
1. `rust: cargo build` task run, project built.

#### Actual:
1. Error popup with message: `There is no task provider registered for tasks of type "cargo".`

Does this issue occur when all extensions are disabled?: N/A

### Note:
Selecting `Shift+Ctrl+P` -> `Tasks: Rerun Last Task` does work as expected.

**Comment by alexr00** [comment]
What extension do I need to install to get cargo tasks?

**Comment by opSSO** [comment]
Incubator.weeb.norton365

Migration.mod/dyanamoVC
Conference/tvDev100TB
Cyber dev.op

**Comment by smokku** [comment]
> What extension do I need to install to get cargo tasks?

`rust-lang.rust` and `matklad.rust-analyzer` extensions.

I also have the following setting enabled:

    "rust-client.engine": "rust-analyzer",

**Comment by alexr00** [comment]
I can't repro the issue, the build task completes as expected when run from the `rust` tasks section and when run from the recently used tasks section. If you can provide a simple example repository I can take another look.

**Comment by smokku** [comment]
Sure.
I have this issue when working on my Rust project: https://github.com/smokku/rust_roguelike_tutorial

**Comment by smokku** [comment]
I just checked and it also reproduces with a newly created project with a simple "cargo init".

```
> mkdir test_vscode
    Directory: C:\devel
Mode                 LastWriteTime         Length Name       
----                 -------------         ------ ----       
d----          04.08.2020    17:47                test_vscode

> cd .\test_vscode\
> cargo init
     Created binary (application) package
```

**Comment by smokku** [comment]
I just checked on Linux Fedora 32, with the same `cargo init` created project and I can reproduce the issue.

**Comment by smokku** [comment]
I deleted my VSCode configuration completely (both `~/.vscode` and `~/.config/Code`).

Installed `rust-lang.rust` and `matklad.rust-analyzer` extensions only.
```
> ls ~/.vscode/extensions/
matklad.rust-analyzer-0.2.266/
rust-lang.rust-0.7.8/
```

With the following, minimal `settings.json` I am **able** to reproduce the issue:

```json
> cat ~/.config/Code/User/settings.json

{
    "workbench.startupEditor": "newUntitledFile",
    "rust-client.autoStartRls": false,
    "rust-client.engine": "rust-analyzer"
}
```

**Comment by alexr00** [comment]
Thanks for providing simple steps with the `cargo init` (I'm not really familiar with rust). I'm still seeing everything work:
![recording (11)](https://user-images.githubusercontent.com/38270282/89389065-36a7db00-d705-11ea-83c5-964040eff311.gif)

Is there anything in the console if you open the developer tools (command Developer: Toggle Developer Tools)

**Comment by smokku** [comment]
I get the following error in the JavaScript console:
![image](https://user-images.githubusercontent.com/147687/89395682-f26d0880-d70d-11ea-80a7-9faf5407b705.png)

**Comment by alexr00** [comment]
I was hoping there might be something there from the extension, since task providers shouldn't be vanishing like that.

What version of the two extensions do you have installed?

**Comment by smokku** [comment]
```
> ls ~/.vscode/extensions/
matklad.rust-analyzer-0.2.266/
rust-lang.rust-0.7.8/
```

**Comment by alexr00** [comment]
Maybe the extension isn't activated. I can see in it's activation events that it doesn't activate on `'onCommand:workbench.action.tasks.runTask'`:

https://github.com/rust-lang/vscode-rust/blob/master/package.json#L37-L40

Can you make sure you have a rust file open before you try to run the task?

**Comment by smokku** [comment]
I do have `main.rs` open. I even wait for rust-analyzer annotations to appear.

**Comment by alexr00** [comment]
When you run the task from the recently used section do you still see cargo listed in the contributed section?
![image](https://user-images.githubusercontent.com/38270282/89400945-dd47a800-d714-11ea-9227-197d3e3f9dca.png)

**Comment by smokku** [comment]
When I press `Shift`+`Ctrl`+`P`, I get:
![image](https://user-images.githubusercontent.com/147687/89429029-52c76e80-d73d-11ea-86a6-c8bf0fe1b406.png)

then, when I press `Enter` I get:
![image](https://user-images.githubusercontent.com/147687/89429190-899d8480-d73d-11ea-836f-eef491e5b0f7.png)

and then when I press `Enter` again, I get the `There is no task provider registered for tasks of type "cargo".` notification.

**Comment by smokku** [comment]
BTW, it started happening about a week or two ago. It worked fine before.
(That's why I am noticing it, as I got used to reruning my project by hitting Shift+Ctrl+P and then Enter twice.)

**Comment by alexr00** [comment]
At this point, since I can't repro the issue and there's nothing suspicious in the console, I have to ask if you can help debug it. If you can help here's what's next:

- Open the developer tools, go to the sources tab, ctrl + p, search for abstractTaskService.ts
- Put a breakpoint in that file here: https://github.com/Microsoft/vscode/blob/d59430ffaa32bff1109692c4d5738c029399b602/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L559-L559
- Try to run the task as usual with the developer tools open
- When the breakpoint hits, share the value of `configuringTask`, the parameter to that method
- Set another breakpoint here https://github.com/Microsoft/vscode/blob/d59430ffaa32bff1109692c4d5738c029399b602/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L568-L568
- Share the value of `matchingProvider` at that breakpoint
- Set a breakpoint here https://github.com/Microsoft/vscode/blob/d59430ffaa32bff1109692c4d5738c029399b602/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L584-L584
- Share the value of `tasks` at that breakpoint, the first time it hits

**Comment by smokku** [comment]
> * Put a breakpoint in that file here: https://github.com/Microsoft/vscode/blob/d59430ffaa32bff1109692c4d5738c029399b602/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L559-L559
> * Try to run the task as usual with the developer tools open
> * When the breakpoint hits, share the value of `configuringTask`, the parameter to that method

![image](https://user-images.githubusercontent.com/147687/89618815-21f64f00-d88d-11ea-8a3e-b496327c5549.png)


> * Set another breakpoint here https://github.com/Microsoft/vscode/blob/d59430ffaa32bff1109692c4d5738c029399b602/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L568-L568
> * Share the value of `matchingProvider` at that breakpoint

![image](https://user-images.githubusercontent.com/147687/89619122-b82a7500-d88d-11ea-8177-30415bb3bd16.png)


> * Set a breakpoint here https://github.com/Microsoft/vscode/blob/d59430ffaa32bff1109692c4d5738c029399b602/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L584-L584
> * Share the value of `tasks` at that breakpoint, the first time it hits

![image](https://user-images.githubusercontent.com/147687/89619429-3dae2500-d88e-11ea-965f-795b32510e1e.png)

**Comment by alexr00** [comment]
@smokku thank you for collecting all that! I think I see the problem. Both of the rust extensions contribute `cargo` tasks, so when the the task is resolved, the correct extension must provide the task. That isn't happening, it's only asking the wrong extension to resolve the task.

**Comment by smokku** [comment]
Glad I could help.

**Comment by alexr00** [comment]
This is going to require a complex fix. Ideally, the rust analyzer and rust extension wouldn't both contribute very similar cargo tasks. However, it should be possible to deal with this in the tasks system.

**Comment by alexr00** [comment]
As a work around for you in the mean time @smokku , you should be able to use the Configure Task command to create a tasks.json with the rust tasks you care about.

**Comment by alexr00** [comment]
Given the complexity of the fix, it would be better if the rust analyzer and rust extension wouldn't contribute tasks with the same type.
