### ISSUE TITLE
stopDebugging return value and jsdoc 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#103925]
Testing #103857

From stopDebugging jsdoc
```
@return A thenable that resolves when the sessions could be stopped successfully.
```

I do not like this wording, since it feels like the promise will never be resolved if we could not stop the debug session. Can we somehow make this clearer?

If the session is stopped successfuly maybe for consistence we shuold be returing a `Thenable<boolean>` like the `startDebugging` does. Though in practice I think stopDebugging should not fail, so I does not make a lot of sense to return a boolean.

**Comment by weinand** [comment]
I checked other places in `vscode.d.ts` where a `Promise<void>` is returned and noticed that they do not even have a jsdoc for the return value. This makes sense because return `void` means to have no return value.
