### ISSUE TITLE
execvp(3) failed: no such file or directory deleted file

### ISSUE THREAD

**Issue by RachelAttah33** [microsoft/vscode#103962]
- VSCode Version:
- OS Version:

I accidentally deleted some files and caused a disconnect of the terminal window. I repeatedly get this error in the terminal window over and over again.

**Error code:
execvp(3) failed: no such file or directory deleted file**
****

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
It looks like you might have deleted a shell or you're targeting a working directory that doesn't exist. Things to try:

- Check your settings.json file for all `terminal.integrated` settings
- Reinstall VS Code?
- Reinstall OS (I have no idea what you deleted)
