### ISSUE TITLE
Automatically update Sync Activity when there are changes

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#103982]
Testing #103613

- `Settings Sync: Show Synced Data`
- Make some edits to something that's being synced

It would be nice if the view automatically updated with the newest sync activity.

**Comment by sandy081** [comment]
Agreed its good to have the data refreshed automatically but these views are for advanced purposes like trouble shooting and administering. So its ok to click on refresh button to update the data.

I see how it is helpful to have the data refreshed while testing but not an issue in real time scenarios. Hence I would not rush on this.
