### ISSUE TITLE
Debug Log filtering not working correctly 

### ISSUE THREAD

**Issue by szmcdull** [microsoft/vscode#103945]
#click on debug log pane
1. Press SHIFT+TAB
2. Key in something
3. Click Enable Filter On Type
4. The filtered result is not correct, desired content not showing up, or other content show up instead.

![image](https://user-images.githubusercontent.com/2098590/89284250-10d8f280-d681-11ea-93a1-8844a449242e.png)

- VSCode Version: 1.47.3
- OS Version: Windows 10 1909

Steps to Reproduce:

1. click on debug console pane
2. Press SHIFT+TAB
3. Key in something
4. Click Enable Filter On Type
5. Sometimes the filtered result is not correct, desired content not showing up, or other content show up instead.

**Comment by szmcdull** [comment]
I suspect it is because vscode incorrectly treat some logs as one line (I can tell from the hovering highlight). When filtering, it records the line number of lines including the filtering text. The line number is incorrect. Then when it displays the filter result, it is referencing the wrong line.

**Comment by isidorn** [comment]
@szmcdull you are correct, this seems to be due to the fact that vscode incrorectly treats some logs as one line.
