### ISSUE TITLE
When Windows theme is dark, tooltips mixes white and black

### ISSUE THREAD

**Issue by whpac** [microsoft/vscode#103937]
- VSCode Version: 1.47.3 (system setup)
- OS Version: Windows 10 build 19041
- Theme: Dark+ (default dark)

Steps to Reproduce:

1. Go to Windows Settings > Personalization > Colors.
2. Enable dark theme for apps (the system theme setting doesn't matter).
3. Go back to VS Code or launch it.
4. Hover anything that has a tooltip associated (i.e. Explorer icon in the Side Bar).

Tooltip will have a black background (like #000) with a white border and a white text on it (like #fff). This looks inconsistently with the rest of the UI. Moreover the contrast is as high as it would be in a high-contrast theme (where the rest of interface has lower contrast levels).

Does this issue occur when all extensions are disabled?: Yes

![IMG_20200804_125513](https://user-images.githubusercontent.com/26907199/89286311-3ef30e00-d652-11ea-84da-999ecfa6610e.jpg)

**Comment by aeschli** [comment]
Some controls that VSCode uses are native controls such as hovers, menus. Theming for these comes from the OS theming.
So what you see is expected.
You can change the VSCode theming to a matching theme.
Are you saying we VSCode not use any native controls or not follow the OS settings?

**Comment by whpac** [comment]
I meant to say that: VS Code's dark theme is based on dark and light shades of gray. But the tooltips use - on contrary - black and white. I thought they could have slightly brighter background and less intense border (something like tooltip over Start Menu tiles).

I understand that these are native controls but I feel like the colors are - simply - not matching the rest of the UI.

**Comment by aeschli** [comment]
This is a dup of https://github.com/microsoft/vscode/issues/64327
