### ISSUE TITLE
Diff for setting sync extensions.json and globalState.json is always empty

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103976]
Testing #103613

I'm syncing extensions on both my PC and my macbook, but on both when I look at extensions the right-hand side of the diff view is always empty:

<img width="1686" alt="image" src="https://user-images.githubusercontent.com/2230985/89328118-bbc9bc00-d641-11ea-92f8-aa21fda4defb.png">

Edit: this seems to also affect the UI state

**Comment by sandy081** [comment]
/duplicate

#103995
