### ISSUE TITLE
Strange extension icon behavior in 1.47.3

### ISSUE THREAD

**Issue by traits** [microsoft/vscode#103917]
- VSCode Version: 1.47.3 (portable)
- OS Version: Windows 10

Steps to Reproduce:

- Launch vscode

The extension icon is missing in the left-most pane. It can be made visible using the `View` menu or by keyboard shortcut and it activates also the extension pane itself in this case. When closing the pane by clicking the icon, the icon vanishes again. Even if left open, the setting doesn't survive the session.

Possible influencing/causing factors:

- Upgrade to  1.47.3
- Installing the Julia vscode extension [v1.0.2] (its adding an own collection of sidebar icons)

**Comment by yume-chan** [comment]
Right click the activity bar (the left-most pane you are talking about) and make sure "Extensions" is checked.

**Comment by traits** [comment]
> Right click the activity bar

So simple. I will close this. No idea what turned the setting off.
