### ISSUE TITLE
Can not change default terminal

### ISSUE THREAD

**Issue by quyetmv** [microsoft/vscode#103933]
I installed vsc on window 10
but version 1.47.3 can not change default terminal from powershell to wsl

**Comment by quyetmv** [comment]
it always restore to default powershell

**Comment by Tyriar** [comment]
You can change the default terminal here
![image](https://user-images.githubusercontent.com/2193314/89298712-89f12f00-d61a-11ea-96e1-6593b376ac3c.png)

**Comment by quyetmv** [comment]
> You can change the default terminal here
> ![image](https://user-images.githubusercontent.com/2193314/89298712-89f12f00-d61a-11ea-96e1-6593b376ac3c.png)

yes. i can change but after open new window it not use default shell. it always resets

**Comment by Tyriar** [comment]
All that does is changes a setting https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration, maybe you have an extension changing the setting then.
