### ISSUE TITLE
Support flags for external terminal command

### ISSUE THREAD

**Issue by MathiasKandelborg** [microsoft/vscode#103929]
I recently made some upgrades and changes to my system, one of the effects being opening my terminal with a desired font. Those upgrades enable me to test other fonts and have another quickly - and change - system font defaults  without problems. In my terminal, I now have to add the -f flag and specify the font I want to use. Otherwise, it uses the default. All in all, a quite reasonable upgrade I don't think is too custom.

Not using a proper font in my terminal messes up my beloved p10k theme, which isn't a problem. That is unless I have a program (Code *ahem*) that allows me to specify a command to spawn a terminal __*without*__ the ability to add flags.

To boil it down to something more general: I use X(some) terminal. I want to spawn it with options, also when using Code. However, as far as I'm aware, Code only spawns a terminal with a command, not options for that command.

At the moment using the command `st  -f "MesloLGS NF"` for spawning a terminal in Linux from Code results in the following error:

```
[renderer1] [error] spawn st -f MesloLGS NF ENOENT: Error: spawn st -f MesloLGS NF ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11
```

I'm curious if this is a feature (in which case someone should make an error/describe why it isn't possible) or if this functionality just needs to be added to Code. To me, there's no reason not to support flags for running _any_ command. I'd be happy to make a PR for it provided some guidance for where to look, it's not that intuitive when not familiar with the source structuring.

**Comment by yume-chan** [comment]
Are you looking for the `terminal.integrated.shellArgs.linux` setting?

**Comment by MathiasKandelborg** [comment]
No @yume-chan, I'm looking for an equivalent for the spawning an **external** terminal. This just makes it weirder, as it already is an option for the integrated terminal.

I don't need an integrated terminal when I have several screens. I have no use for it and as such only use my native terminal. This probably isn't an edge-case, as I'm sure many people have enough screen real estate to use more than one window at once.

**Comment by MathiasKandelborg** [comment]
It seems to me this is a missing feature. Can you elaborate on how this isn't a planned 'feature' and why 20 people have to upvote it to make it into VS Code at some point?

I think this is a trivial feature, and it makes so much sense that I don't see the reason for RFC or doing the voting thing. I know this might be the first time the feature is suggested ( which I'd find weird), but it shouldn't be a question if it should be added or not - it is an objectively essential and trivial feature in a lot of cases.

**Comment by MathiasKandelborg** [comment]
Hmm, I guess I have to make a better suggestion lol
