### ISSUE TITLE
Change cell actions from Markdown Notebook editor show up in GitHub issue notebook editor

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#103930]
Testing #103887

<img width="1036" alt="capture" src="https://user-images.githubusercontent.com/1931590/89277907-b3738000-d645-11ea-893f-a0a8332f03fe.png">

**Comment by dbaeumer** [comment]
This seems to be intentionally since all notebooks have code and markdown cells. However the action `Change Cell to Code` is very misleading since what the most common thing is `Change to GitHub query`.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/103922
