### ISSUE TITLE
cant run the app from within the Applications folder on my Mac.  

### ISSUE THREAD

**Issue by dreed47** [Microsoft/vscode#1039]
cant run the app from within the Applications folder on my Mac.

**Comment by rhires** [comment]
Can you provide more info? Mac OS version, which version of Code you have...I'm sure there's more...

**Comment by egamma** [comment]
Please refer to https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions for how to submit issues.

Closing the issue until more steps are provided.

**Comment by dreed47** [comment]
Osx El Capitan version 10.11.2  vscode Version 0.10.3 (0.10.3)
