### ISSUE TITLE
Allow selection of a file without opening it

### ISSUE THREAD

**Issue by kaineub** [microsoft/vscode#103902]
I accidentally permanently deleted a file that I spent many hours working on. I'm hoping that this feature request would prevent this from happening to someone in the future.

A project that I'm working on requires a large amount of data to be written to files. One of these files had data that I no longer needed and I wanted to free up the disk space. I clicked on it in the explorer window and pressed the delete key and confirmed the deletion. I then noticed that a crucial file that I had been working on had disappeared.

Unfortunately, the file I wanted to delete was too large to be open in the editor so a warning appeared in the bottom right corner asking me to restart VSCode with more memory allocated to it. My selection instantly switched back to the most recent file I had open in the editor, which was my important file that of course had not been committed yet. I hadn't noticed the warning in the bottom right or that my selection was no longer the file I clicked on until it was too late.

I think it would be a worthwhile feature to have the selection stay on the clicked file, even if the file is too large to be loaded into memory.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by JDWilson1980** [comment]
Zulu.Pkg/box
