### ISSUE TITLE
Cell `...` actions should always be available on right click

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#103920]
Testing #103887

Right clicking a notebook cell does nothing. Can we just have the `...` actions appear in the context menu for a cell? I feel my wrist in pain every time I have to go hunt for that `...` box inside the invisible action box on the right.

**Comment by roblourens** [comment]
@rebornix how about using our cool new submenus to add a "Notebook" submenu inside the editor in this case? Since merging the notebook and editor context menus would probably be too long. And right clicking outside the editor can give a flat context menu

**Comment by rebornix** [comment]
@roblourens sounds good to me.
