### ISSUE TITLE
Adding /node_modules/ prefix to imports after moving

### ISSUE THREAD

**Issue by byeze** [microsoft/vscode#103948]
Version: 1.47.3 (system setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Move a tsx file that imports React, and other component inside a folder
2. Rename that folder to whatever you want (here all the files of that folder will be opened for renaming/fixing the imports)
3. Now the imports of your packages include "/node_modules/"

![image](https://user-images.githubusercontent.com/7424138/89295774-d7c86000-d637-11ea-98f4-e1fc26387755.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so, please include steps to reproduce (i.e. an example project we can use to reproduce this)

**Comment by byeze** [comment]
Fixed by removing an extension. Thank you!
