### ISSUE TITLE
Persist SCM view state when switching between files across different repos

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#103989]
- VSCode Version: 1.48-Insiders
- OS Version: macOS

Steps to Reproduce:

1. Open a multi workspace with at least git repo A and B
  * A has no pending changes
  * B has at least one pending change
2. Open files from both A and B, and leave the editor group open for file from A
3. Open SCM view, collapse all
4. Switch to file from B
5. SCM view state lost

![Kapture 2020-08-04 at 11 17 39](https://user-images.githubusercontent.com/876920/89329843-3f84a800-d644-11ea-816e-ac92d05fad5a.gif)

TBH I'm a fan of the old UI https://github.com/microsoft/vscode/issues/102118 but that's not constructive feedback, so I'll go case by case and explain what's my scenario and my suggestion. For this particular case:

* I have a multi root workspace
* I have a main repo `vscode`, whose status I care about the most
* I have multiple secondary repos, test data and test extensions, which has pending changes as I don't always push them to upstream

The new UX is really hard to use as I can no longer focus on `vscode` repo and ignore others for most of the time.

**Comment by joaomoreno** [comment]
I believe https://github.com/microsoft/vscode/issues/104151 will make you much happier, do I get that right?

**Comment by rebornix** [comment]
@joaomoreno yes, the proposal looks great to me.

**Comment by joaomoreno** [comment]
Awesome, I'll close this for now and let me know what you think when that lands. 🙏
