### ISSUE TITLE
[Feature Request] Context menu on explorer 'Open folder in Vs Code'

### ISSUE THREAD

**Issue by gabrielcapanogyp** [Microsoft/vscode#10393]
The title is self-explanatory 

What do you guys think?

**Comment by jrieken** [comment]
> The title is self-explanatory

Sorry, no

**Comment by gabrielcapanogyp** [comment]
Exactly @wallverb 

Like we have for notepadd++ in windows but for folders 

![image](https://cloud.githubusercontent.com/assets/13614858/17557931/679256ec-5eef-11e6-80ef-93690967892b.png)

**Comment by joaomoreno** [comment]
This is supported in Windows. Just use that option at installation time.
