### ISSUE TITLE
Stopping an already stopped session does not throw

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#103936]
Testing #103857

If an extension author call stopDebugging and passes an already stopped session there is no error message or any notification in any way.
If our stopDebugging would return a boolean, we could for example return false here.
Or at least we could throw an error.

If you would like an error to be thrown you can simple pass `false` here to not include inactive sessions
https://github.com/microsoft/vscode/blob/6dd9bda34d96cd6cf442dcc177c7961ebb393d91/src/vs/workbench/api/browser/mainThreadDebugService.ts#L269

**Comment by connor4312** [comment]
If we don't throw an error it makes the method idempotent; the request is to move the session into a "stopped" state, and if it's already stopped then it's already in the target state.

Are there other cases in the API where we do or don't throw in similar scenarios?

**Comment by weinand** [comment]
Yes, methods like this must be idempotent because otherwise they would be painful to use: either by verifying upfront that the debug session is not already stopped, or by putting a try/catch block around them just to ignore the exception...
