### ISSUE TITLE
Opening multiple files from file explorer causes new VS code windows instead of files becoming tabs.

### ISSUE THREAD

**Issue by BenMcGarry** [Microsoft/vscode#10390]
Opening multiple files from within file explorer causes each file to open its own VS Code window instead of becoming tabs within a single window. Gif of it in action (files opened after gif cut off): https://gfycat.com/UnawarePepperyBream

- VSCode Version: 1.4.0
- OS Version: Windows 10 Pro 1607 (14393.67)

Steps to Reproduce:

1. Select multiple files within a file explorer (highlight them)
2. Right click and open with code

Expected: Each file opens as its own tab within one VS code window.
Actual: Each file opens its own VS code window.

**Comment by bpasero** [comment]
Can you try with setting `"window.openFilesInNewWindow": false` ?

**Comment by BenMcGarry** [comment]
Yep that resolves the issue, is there a reason the setting isn't set to false as standard? It is a lot nicer experience to have this and is the same functionality as other software.

**Comment by stevencl** [comment]
@BenMcGarry and I spoke about this earlier (he's in the same office as me... :-) )

I think this might be a hold over from our earlier pre-Tab design? It would seem to make sense that we set this to false by default if tabs are on by default.

**Comment by bpasero** [comment]
@stevencl this setting has an impact on a wide range of open operations including the command line so if someone is willing to make a pass over all combinations how things should on all OS I am happy to try to see if it is possible to implement it. Some examples:
* Doubleclick when running
* Doubleclick when NOT running
* Command line when running
* File menu
* Drop on Dock when running

And for each of these variants you have:
* one FILE
* one FOLDER
* multiple FILEs
* multiple FOLDERs

And for each of these variants you have:
* file already opened somewhere
* folder already opened somewhere

I am sure I missed some things :)

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/9479
