### ISSUE TITLE
Trailing Comma in default settings.json

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#103940]
Issue Type: <b>Bug</b>

There's a trailing comma in the defaut settings.json file and shows as an error in the Problems pane. Have to "Reload Window" to clear it out.

Shows with and without extensions enabled.

To reproduce, open the settings (Command-comma), click the button to show the settings.json and look in the Problems panel.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/13488/89289798-d2621a00-d625-11ea-97aa-db69ab21d5bf.png">

<img width="655" alt="image" src="https://user-images.githubusercontent.com/13488/89289696-aba3e380-d625-11ea-98d4-6014a7f90eb7.png">

VS Code version: Code - Insiders 1.48.0-insider (7906d414c0af9e1e6cc4497559add84250d35d49, 2020-08-04T09:39:40.910Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (14.21GB free)|
|Process Argv|-psn_0_12901453|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sandy081** [comment]
/duplicate

#103009
