### ISSUE TITLE
Type script service crash

### ISSUE THREAD

**Issue by barissenkal** [microsoft/vscode#103924]
Issue Type: <b>Bug</b>

Openned project with long files, after openning files for 30 seconds the crash notification showed up

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
Bookmarks|ale|11.3.1
smali|cra|1.0.1
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
file-icons|fil|1.0.25
macros|ged|1.2.1
todo-tree|Gru|0.0.178
contextualduplicate|laf|0.2.0
sublime-keybindings|ms-|4.0.7
vetur|oct|0.25.0
code-settings-sync|Sha|3.4.3
sql-bigquery|shi|1.4.0
code-spell-checker|str|1.9.0
tabnine-vscode|Tab|2.9.0
ayu|tea|0.20.1
vsfire|tob|1.4.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo
