### ISSUE TITLE
Pressing F12 - "Go to Definition" does not work

### ISSUE THREAD

**Issue by VonCede** [Microsoft/vscode#10395]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.2

Steps to Reproduce:

1. Select function call in code.
2. Press F12 to "Go to Definition"
3. Cursor stays on same place. iMac volume is increased.

**Comment by jrieken** [comment]
> Cursor stays on same place. iMac volume is increased.

You are not pressing `F12` but the 'Increase Volume'-button. By default on mac F-keys are only active when pressing `fn`. 

<img width="656" alt="screen shot 2016-08-11 at 11 23 23" src="https://cloud.githubusercontent.com/assets/1794099/17584311/15f74e6a-5fb6-11e6-980b-00b3b9d3dddb.png">
