### ISSUE TITLE
An ignore setting removes indentation on the line preceeding it

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103978]
Testing #103613

I have the "prettierPath" ignored in my settings. Whenever I add it, indentation is always lost on the preceding line

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/2230985/89330404-0ac52080-d645-11ea-8eb1-6b4861e71413.png">

**Comment by sandy081** [comment]
@connor4312 I cant repro it, do you have any special indentation configured?

**Comment by connor4312** [comment]
Nothing other than `editor.tabSize: 2`

**Comment by sandy081** [comment]
@connor4312 Are you able to repro this still? If so, can you please provide me the steps to repro it as I am not able to?
