### ISSUE TITLE
Exception in Console upon launch

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#103938]
Issue Type: <b>Bug</b>

There's an exception in the console upon boot. Shows up with extensions disabled.

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/13488/89289468-4c45d380-d625-11ea-8615-bae3c53116ac.png">

VS Code version: Code - Insiders 1.48.0-insider (7906d414c0af9e1e6cc4497559add84250d35d49, 2020-08-04T09:39:40.910Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (14.70GB free)|
|Process Argv|-psn_0_12901453|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by weinand** [comment]
@sandy081 is this something in your area?

**Comment by sandy081** [comment]
This is account activity, @RMacfarlane owns this.

**Comment by RMacfarlane** [comment]
To verify, hide the accounts icon in the activity bar and reload the window, check there is nothing in the console.

**Comment by jtsom** [comment]
The accounts icon was already hidden, and the error still shows:

![image](https://user-images.githubusercontent.com/13488/89316108-a9538080-d649-11ea-806b-4ce26b55bf10.png)

**Comment by RMacfarlane** [comment]
@jtsom Ah, to clarify, I was posting instructions on how to verify that this has been fixed as we prepare for our release. Hiding the icon is necessary to trigger the console error. The fix will go out in tomorrow's insiders.
