### ISSUE TITLE
Sometime if i change some code in my css file the changes are not depicted in php file or html file.I have faced  several times this issue .

### ISSUE THREAD

**Issue by imran414141** [microsoft/vscode#103909]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by JDWilson1980** [comment]
//willie.axios.net
Outlook.com
wilson.jonpaul@gmail.com

Google.net/CARES/NYS

**Comment by JDWilson1980** [comment]
build/yarn.lock
