### ISSUE TITLE
File turn into empty one after saving

### ISSUE THREAD

**Issue by akelalix** [microsoft/vscode#103903]
Hi all,

Good day.

I have decided to try to edit my code using vscode, unfortunately I have encountered a weird issue. After editing my vue file ( note: this is an intermittent issue ), when I trigger Save ( CMD+S), the vscode will delete all lines/content of the file I have been working on. Please see attached gif file for details for sample scenario
![sample](https://user-images.githubusercontent.com/15134332/89255081-5ed70180-d653-11ea-9022-adea54008b84.gif)

Currently, I havent catch any pattern for the said issue. Usually after the fresh install vscode will run smoothly but after a few minutes/hour I will encountered the said issue

- VSCode Version: Version: 1.47.3
- OS Version: MAC OS Catalina 10.15.6

Extensions installed :  PHP Intelephense, PHP Intellisense, Vetur

Thank you so much

**Comment by lszomoru** [comment]
Are you able to reproduce the same behavior in any other files other than a `vue` file?

**Comment by JDWilson1980** [comment]
Trojan.V.1
Watson.ibm.co

work.spaces.net/distro
Google.VSP.axioS.com
