### ISSUE TITLE
Visual Studio allows you to gitignore .gitignore

### ISSUE THREAD

**Issue by Yash-Singh1** [microsoft/vscode#103999]
# About

- VSCode Version: 1.47.3
- OS Version: Ubuntu 20.04

 # Steps to Reproduce:

1. Create a .gitignore file in a directory
2. Run ```git init``` in the directory to make sure it is a git repository
3. Type in ```.gitignore``` in your .gitignore
4. You will notice that there is no error and that .gitignore gets faded out

# Info
## Settings
Does this issue occur when all extensions are disabled?: Yes
Were any settings changed?: No
## Screenshots
Below are is a screenshot depicting this effect:
![gitignoreFailure](https://user-images.githubusercontent.com/53054099/89346973-c47cbb00-d65e-11ea-8a19-4911dff6a9e9.png)

**Comment by joaomoreno** [comment]
This is a valid git usecase: https://stackoverflow.com/a/767213
