### ISSUE TITLE
ability to bind ctrl+shift+i and override other Chrome shortcuts

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#10399]
Is it possible to add the ability to override Chrome keyboard shortcuts? For example, I would like to bind `ctrl+shift+i` to a command, but it always opens up the developer tools instead.

(vscode 1.4.0, Win8.1)

**Comment by jhasse** [comment]
`ctrl+shift+i` is `Format Code` from the [Clang-Format extension](https://github.com/xaverh/vscode-clang-format-provider) for me on Linux, vscode 1.4.0. So it seems to be possible, you might want to have a look at the extensions source code.

**Comment by siegebell** [comment]
@jhasse Aha! `ctrl+shift+i` will open Chrome developer tools only when running in an extension development host. This makes debugging annoying, but is perhaps not a huge problem...

**Comment by siegebell** [comment]
closed in favor of #10416
