### ISSUE TITLE
Unable to Signin/Signup

### ISSUE THREAD

**Issue by iaxat** [microsoft/vscode#103906]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install extension
2. Try to sign in

Does this issue occur when all extensions are disabled?: Yes/No
yes it does

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by iaxat** [comment]
I think it is working now, I tried to record while doing the same steps and it worked. I think there is for sure a bug because I tried it many times and it was failing to load up. But somehow it worked now. I am sorry if I bothered. How can I contribute to this project.
