### ISSUE TITLE
Visual Studio 2019 Dark/Light color themes missing in remote WSL

### ISSUE THREAD

**Issue by NejcBW** [microsoft/vscode#103912]
- VSCode Version:  1.48.0-insider and 1.47.3
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open VSCode locally and select "Visual Studio 2019 Dark" or "Visual Studio 2019 Light" color theme
2. Open VSCode in WSL and check the color theme list: "Visual Studio 2019 Dark" or "Visual Studio 2019 Light" themes are not available

Does this issue occur when all extensions are disabled?: The reproduction of this bug requires at least the remote extensions. However, with all extensions uninstalled/disabled (except for the Remote Development) the bug still exists.

There are no errors in the Dev Tools Console.

The attached image shows the list of available color themes when in WSL development mode. The "Visual Studio 2019 Dark" or "Visual Studio 2019 Light" themes are missing from the list.

![bug-report](https://user-images.githubusercontent.com/49614740/89260898-78fde900-d62d-11ea-847b-0b3d849f646c.png)

**Comment by aeschli** [comment]
"Visual Studio 2019 Dark" or "Visual Studio 2019 Light" come from an extesnsion. Which extension is that?
Can you check that the extension is installed in the WSL window as well?

**Comment by NejcBW** [comment]
That's the problem, these themes come from the C# extension while I was somehow sure they were default themes. So everything is fine, I am closing this issue.
