### ISSUE TITLE
Search and replace input text fields are unusable with multi-line text

### ISSUE THREAD

**Issue by stodge** [microsoft/vscode#103952]
- VSCode Version: 

```
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.9-100.fc31.x86_64
```

- OS Version:

```
Fedora 30 (I think)
Linux 5.7.9-100.fc31.x86_64 #1 SMP Fri Jul 17 17:18:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Steps to Reproduce:

1.    Press CTRL+SHIFT+H to initiate a global replace
1.    Paste multiple lines of text into the Search box (e.g. 10+ lines)
1.    Try to use the cursor keys to move around the input box - weird things happen and the input box is unusable
1.    Use the mouse wheel to scroll and click in different spots to place the cursor - weird things happen and the input box is unusable
1.    Repeat this for the second input box (replace text input box)

Does this issue occur when all extensions are disabled?: Sorry, I haven't tried this.

**Comment by roblourens** [comment]
I can repro - not sure what happened here
