### ISSUE TITLE
Can you please get back Source Control menu?

### ISSUE THREAD

**Issue by alvipeo** [microsoft/vscode#103923]
Issue Type: <b>Feature Request</b>

Please get the version where Pull, Push wasn't on the submenu!

VS Code version: Code - Insiders 1.48.0-insider (62503719349d04686a0704f7646b761aaf495b3d, 2020-08-04T05:32:46.194Z)
OS version: Windows_NT x64 10.0.19041

**Comment by joaomoreno** [comment]
Sorry, but the git `...` menu is much better right now since we can organize and add missing commands to it now that we support submenus.

**Comment by alvipeo** [comment]
Got it. Is there any alternative? Like keyboard shortcuts?

**Comment by joaomoreno** [comment]
Absolutely. All commands in VS Code can be assigned to keyboard shortcuts! [Read more about this](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor).

And, my favorite, they can also be easily run from the Command Palette: <kbd>F1</kbd>, or <kbd>Ctrl Shift P</kbd>

**Comment by JanBN** [comment]
Stupid decision. I know you are all happy you have sub menus, but it doesn't mean you need to use it everywhere for everything. Either way someone would create extension for just adding these commands to the first layer menu.

**Comment by alvipeo** [comment]
Yeah, since this genius invention I NEVER used this menu again. But good you made it.

**Comment by gjsjohnmurray** [comment]
For those wanting faster menu access to Pull and Push, as a workaround I just published a [simple extension](https://marketplace.visualstudio.com/items?itemName=georgejames.gitfavorites).

**Comment by ELI7VH** [comment]
I think a good middleroad here is to put
```
- push
- pull
- commit
```
at the top of the menu, and put all the submenus in some "advanced" section. 

I'm sorry, but this was a very bad UI decision.

**Comment by Citrusu** [comment]
this was a realy very bad bad bad bad bad bad bad decision ,please get back put it to top menu !!

**Comment by isaiahtaylorhh** [comment]
This breaks 10x / day muscle memory for me and I would assume many others. Mostly "push".

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/104762
