### ISSUE TITLE
Git: Clone to an alternate directory location

### ISSUE THREAD

**Issue by jdandrea** [microsoft/vscode#103987]
When performing a `git clone` I'd like the option to specify an alternate target directory, just as I can with `git clone` on the command line. 

For example, this can be useful when cloning a template repository, making a few edits, then pushing back to a new origin.

Workaround for now is to rename the directory after the push or use the `git` CLI prior to engaging VSC.

**Comment by joaomoreno** [comment]
The `Git: Clone` action always asks where to place the repository. Don't you see a folder location dialog when running it?

**Comment by jdandrea** [comment]
I was under the impression that the folder location refers to the parent of the repository, not the repository folder itself. I will recheck!

**Comment by jdandrea** [comment]
@joaomoreno - The problem is that the chosen location becomes the repository's _parent_ directory. It does not represent the destination directory proper.

VSCode appears to do the equivalent of this:
```
$ mkdir -p /home/jdandrea/git/my-repo && cd $_
$ git clone https://url/to/repo.git
Cloning into 'repo'...
. . .
```

What I want to be able to do instead is this:
```
$ git clone https://url/to/repo.git /home/jdandrea/git/my-repo
Cloning into '/home/jdandrea/git/my-repo'...
. . .
```

Note the different clone target of `my-repo` vs `repo`.

I tried renaming the directory just after cloning, expecting VSCode to follow the name change, however this does not work and is out-of-scope per #20071.
