### ISSUE TITLE
Show single notification for multiple important extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#103954]
If there are more than one important recommended extensions for an exe or file type then instead of showing multiple notifications, show a single notification.

Eg: Given an exe installed

1. if there is one important recommendation - message can just name that extension
2. if there are two important recommendations - message can include the names of both extensions
3. if there are more than two important recommendations - message can include first two and others for eg: `The Extension A, Extension B and other extensions are recommended...` and have an action to see all recommendations?

**Comment by opSSO** [comment]
Nsd.framework.dev
Hub.onboard.ibm/warp
Actionable git.servo.local.rul
