### ISSUE TITLE
Incorrect undo/redo state after adding a markdown cell and adding some text to it

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#103983]
Testing #103860  
 - using undo/redo from the Edit menu in the global menu bar on OS X
- using the `my-work.github-issues` notebook

The following sequence results in an incorrect state:
- new Markdown cell -> empty Markdown cell is added
- add 'text' to the cell -> inserts 'text'
- undo -> undos the insertion of 'text'
- undo -> empty Markdown cell is removed
- redo -> Markdown cell is added again
- :bug: redo -> 'text' is not inserted again
- :bug: undo -> empty cell is not removed

**Comment by rebornix** [comment]
Verifier: 

Preparation:
* new Markdown cell -> empty Markdown cell is added
* add 'text' to the cell -> inserts 'text'
* undo -> undos the insertion of 'text'
* undo -> empty Markdown cell is removed
* redo -> Markdown cell is added again, note that the markdown cell is in preview mode

Please then test following two scenarios:

* stay in preview mode, the preview says "Empty Markdown Cell, double click or press enter to edit"
  * redo -> the preview becomes 'text'
  * undo -> the preview becomes "Empty Markdown Cell, double click or press enter to edit"
  * undo -> the cell is removed again
* double click the markdown cell, switch to editing mode, now the focus is in an empty Monaco editor
  * redo -> 'text' is inserted into the editor
  * undo -> 'text' is removed
  * undo -> the cell is removed again
