### ISSUE TITLE
Make it more clear that keybindings are synced per platform by default

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103984]
Testing #103613

I automatically unchecked syncing "keybindings" initially because I assumed they would get messed up syncing between OSX and Windows. It seems like the only place we tell the user that they're actually per-platform by default is on the setting description, which is not discoverable.

Maybe the label should be `Keybindings (per Platform)` to make this more clear.

**Comment by sandy081** [comment]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/10746682/89402441-226cd980-d717-11ea-9495-6b3aeac05d7d.png">
