### ISSUE TITLE
Cancel merge does not clear the setting sync state

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#103998]
Testing #103604

* Open Insiders with a new user data dir
* Change theme
* Turn on sync
* Choose Manual merge
* Close the diff editor (do not perform any merge)
* Gear icon -> Turn off Settings Sync
* Gear icon shows a loading badge and the context menu has a greyed out item "Turning on Settings Sync" but no way to continue or quit

**Comment by rebornix** [comment]
Reloading the window or sign out doesn't solve the problem.

**Comment by sandy081** [comment]
I can't repro if I choose Manual merge. But I can repro it if I choose `Merge` option. 

Can you please confirm if you choose Manual merge or just merge?

**Comment by sandy081** [comment]
I am sure that this can happen only with `Merge` action and not with `Merge Manually...` 😉 

Fixed it when it happens with `Merge` action. Please reopen if you can repro this with `Merge Manually...` action.

**To verify:**

- Sync from Machine A (make sure theme is set)
- From Machine B or Open Insiders with a new user data dir
- Set to a different theme than that of Machine A
- Turn on sync and make sure you get Merge/Replace dialog
- Choose **Merge** action
- Make sure you get conflicts confirmation and on pressing OK manual merge view is opened showing following entries
  - Entries with conflicts (in this case settings) are shown with user actions
  - Entries without conflicts are shown accepted
- On merging/accepting conflicts `Turn on Settings Sync...` action is enabled and you can turn on sync
