### ISSUE TITLE
Global Typescript Interfaces are only recognized if the declaring file is open in VSCode

### ISSUE THREAD

**Issue by VSDekar** [microsoft/vscode#103905]
- VSCode Version: 1.47.3
- OS Version: Linux Mint 20

Steps to Reproduce:

1. Open VS Code
2. create `index.ts`
```ts
const foo: Bar = {
    BarId: 1
}
```
3. create `models.ts`
```ts
interface Bar {
    BarId: number;
}
```
4. If you have opened both files in VSCode, everything works fine and the type `Bar` is recognized.
5. Close `models.ts`
6. You get an Error in `index.ts` `Cannot find name 'Bar'.ts(2304)` 
7. Open again `models.ts`. The error disappears (And you get intellisense)

Additional Hint 1:
I get the same behavior when i use these interfaces in JSDoc. And i get the same behavior if i have a @typedef in a seperate file. As long as i have the files somewhere open in vscode, they are recognized.

Additional Hint 2:
The declared Interfaces (exported or global) only show up in intellisense if i have the declaration file open.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Try creating a `tsconfig.json`: https://code.visualstudio.com/docs/typescript/typescript-tutorial#_tsconfigjson

This will make all TS files in your workspace be treated as part of the same project

**Comment by VSDekar** [comment]
@mjbvz 
Thanks, i will try this as soon as i am at home. But anyway its a very weird behavior, that as soon as the file with the typing is open in VSCode, that there is no error and as soon as it's closed some errors appear.

In my eyes this is a bug. It should behave consistent, no mather if the file with the typings is open in the editor or not.
