### ISSUE TITLE
Wrong diffs for globalState.json and extensions.json

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode#103995]
Testing #103604

I am using settings sync when I'm normally using code-insiders, and I have signed in using GitHub. For testing, I signed in using a Microsoft account, and I am using a different user-data-dir and extensions-dir as mentioned in the test plan item.

1. Turn on settings sync, sign in using MS
2. "Settings Sync: Show synced data"
3. Activity/State from both accounts is visible

On my MS account, I don't have any extensions installed.

![Screenshot from 2020-08-04 16-47-41](https://user-images.githubusercontent.com/8235156/89343415-3e6a6f80-d672-11ea-96c9-acf6e307e177.png)

**Comment by sandy081** [comment]
> On my MS account, I don't have any extensions installed.

Built in extensions are also included to sync their enablement state. So Extensions entry include both built in & installed. Can you please open Extensions and make sure that is the case? 

If you are also seeing installed extensions or data which you did not synced can you please provide the steps to repro, above steps do not look complete enough.

**Comment by 9at8** [comment]
> Built in extensions are also included to sync their enablement state.

Ah yes, that seems to be the case indeed. :see_no_evil: 

Although turning on sync for the first time gives me this activity.

![Screenshot from 2020-08-05 10-38-32](https://user-images.githubusercontent.com/8235156/89426198-e3835780-d707-11ea-992c-349f6b48736b.png)

As you said, it looks like these are all the built-in extensions, but I'm not really sure what the diff view signifies in this case. As I turned on sync for the first time, I expected the diff view to look something like this:

![Screenshot from 2020-08-05 10-41-27](https://user-images.githubusercontent.com/8235156/89426494-3b21c300-d708-11ea-97b2-deb9c23fb43a.png)

or 

|Old|Current|
|---|---|
|`{}`|`{ "window.zoomLevel": 1 }` |

**Comment by 9at8** [comment]
Might be related. If it's not I can create another issue.

The diffs are confusing for globalState.json as well. No matter what change I make, it always shows up like this:

![Screenshot from 2020-08-05 10-48-41](https://user-images.githubusercontent.com/8235156/89427676-87213780-d709-11ea-93af-f0f265ceeb6d.png)

**Comment by sandy081** [comment]
Diffs seem wrong to me. Please update the description and it would be great if you can provide me the steps to repro.

**Comment by 9at8** [comment]
@sandy081 steps to repro are:

1. Turn on settings sync
2. Make some changes / move around some UI
3. "Settings Sync: Show Synced Data"
4. Click on diffs
