### ISSUE TITLE
Integrated terminal cannot scroll

### ISSUE THREAD

**Issue by kunalbhagawati** [Microsoft/vscode#10404]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04 64 using i3 Tiling Window Manager
- HP dv6 (laptop) trackpad 

Steps to Reproduce:

1. Open the integrated terminal.
2. `cat` a long file
3. The terminal does not scroll.

**Comment by Tyriar** [comment]
Are you on oh-my-zsh?

**Comment by Tyriar** [comment]
Duplicate of #7817
