### ISSUE TITLE
Clicking cursor keys is making unexpected selections

### ISSUE THREAD

**Issue by anikets** [microsoft/vscode#104046]
* Pressing any cursor key starts selecting text, instead of just moving the cursor.
* This issue starts happening randomly.
* Issue is observed even after switching to a different file.
* Issue is resolved after restarting VS Code.
* Screen recording video is attached.
[Screen Recording.mov.zip](https://github.com/microsoft/vscode/files/5027395/Screen.Recording.mov.zip)

**Comment by alexdima** [comment]
I cannot reproduce this issue. Does this reproduce when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)
