### ISSUE TITLE
Debugging deno code jump to wrong place.

### ISSUE THREAD

**Issue by yubaoquan** [microsoft/vscode#104045]
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Write ts code with comments;
2. Debug, use deno to run it;
3. step over each line;

debug config: 
```
{
 "version": "0.2.0",
  "configurations": [
  {
    "type": "node",
    "request": "launch",
    "name": "Deno",
    "runtimeExecutable": "deno",
    "port": 9229,
    "runtimeArgs": ["run", "--inspect-brk", "-A", "index.ts"],
    "cwd": "${workspaceFolder}/leetcode/ts",
    "outputCapture": "std"
  }
  ]
}
```

tsconfig
```
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "sourceMap": true,
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "preserveConstEnums": true,
    "noImplicitUseStrict": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "lib": ["es7", "dom"],
    "baseUrl": "./",
  }
}

```

The code I debug:
```
/*
 *
 *
 */

function foo() {
  console.info(1); // breakpoint 2
  console.info(2);
  console.info(3);
  console.info(4);
  console.info(5);
  console.info(6);
  console.info(7);
  console.info(8);
  console.info(9);
}

foo(); // breakpoint 1

```

Breakpoint 1 never paused.
What's more important is the line account of comment affects the position of wrong jumping. 
For example, if comment is 
```
/*
 *
 */
``` 
The cursor will jump to a file named `02_console.js` after execute `console.info(8)`

 if comment is 
```
/*
 *
 *
 */
``` 
The cursor will jump to a file named `02_console.js` after execute `console.info(7)`

 if comment is 
```
/*
 *
 *
 *
 */
``` 
The cursor will jump to a file named `02_console.js` after execute `console.info(6)`

Does this issue occur when all extensions are disabled?: Yes

![deno](https://user-images.githubusercontent.com/2340296/89394720-01b87a00-d73f-11ea-8605-c0fe4b880b69.gif)

**Comment by connor4312** [comment]
You appear to be using the old desbugger `debug.javascript.usePreview: false`, which does not handle in-place sourcemaps gracefully. Please use the new debugger which handles this better, instructions: https://github.com/denoland/vscode_deno/issues/12#issuecomment-656412152
