### ISSUE TITLE
No default value is set when visibility property is selected

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#104062]
Testing #103833

No default value is set for `visibility` property. When I select `visibility` property from intell-sense default value shall be populated automatically.

**Comment by alexr00** [comment]
It seems that we don't support having both an `enum` and a `default` set in JSON. 
For example, try using intellesense to complete `editor.semanticHighlighting.enabled` in settings.json. It has a default value of `configuredByTheme`, but it doesn't populate.

**Comment by alexr00** [comment]
@aeschli a `default` property set on a json property that also has an `enum` set doesn't get automatically set by intellisense in json files. This is easily tested with the setting `editor.semanticHighlighting.enabled` in settings.json. It has a default value of configuredByTheme, but it doesn't populate when you use intellisense to complete it.

**Comment by aeschli** [comment]
I'm not sure I understand the issue.
Having enum and default in a schema is very common, especially with configuration settings.
Code completion shows them all:
![image](https://user-images.githubusercontent.com/6461412/90019961-6fb8f000-dcaf-11ea-9d17-51ef5ff9c50d.png)

**Comment by aeschli** [comment]
Maybe a filtering issue? As soon as there are already some characters (e.g. `"`), some proposals will be filtered.

**Comment by alexr00** [comment]
What I mean is that the actual JSON file gets a default value inserted. In the following example, `terminal.integrated.shell.windows` has a default value of `null` and that is inserted into the document when I accept the suggested setting name. However, when I accept the suggested setting name for `editor.semanticHighlighting.enabled`, no default value is inserted into the document:

![recording (15)](https://user-images.githubusercontent.com/38270282/90120049-a435b600-dd5a-11ea-9cda-a54fb435a13d.gif)

**Comment by aeschli** [comment]
Oh, I see. Yes, that's intended. If there are more than one proposals (e.g. from an enum) then we don't fill in a value, but retrigger code assist t let the user choose.

Closing the issue, but @sandy081 let me know why the current behavior is not optimal.

**Comment by sandy081** [comment]
Inserting the default value helps user to know the default value. I think we do that for property (setting) that is object type and default value.
