### ISSUE TITLE
Cannot upgrade 1.47.2

### ISSUE THREAD

**Issue by mcorning** [microsoft/vscode#104001]
Issue Type: <b>Bug</b>

Many options to accomplish the upgrade. For example:
Open VSC
Prompt appears to update
Upgrade now
VSC closes
Open Task Manager
Note VSC Setup running
Dialog appears saying it cannot kill the code process.
Task Manager does not show any other code processes running
Switch to VSC Insiders

^m

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
30-seconds-of-code|30-|1.0.0
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.36.2
vscode-eslint|dba|2.1.8
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.1.3
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
vscode-pull-request-github|Git|0.18.0
svgeditor|hen|2.9.0
vscode-auto-open-markdown-preview|hnw|0.0.4
html-tag-wrapper|hwe|0.2.3
search-node-modules|jas|1.3.0
vscode-svg-dev|kon|0.8.16
node-module-intellisense|lei|1.5.0
start-git-bash|McC|1.2.1
markdown-shortcuts|mdi|0.12.0
vscode-azureappservice|ms-|0.18.0
vscode-azurefunctions|ms-|0.23.0
vscode-azurestorage|ms-|0.9.0
vscode-docker|ms-|1.4.1
csharp|ms-|1.22.1
python|ms-|2020.7.96456
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
azure-account|ms-|0.8.11
debugger-for-chrome|msj|4.12.9
vetur|oct|0.26.0
vue-beautify|pea|2.0.4
material-icon-theme|PKi|4.2.0
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|2.0.0
python|tht|0.2.3
vscode-status-bar-format-toggle|tom|2.0.0
nodejs-extension-pack|wad|0.1.9
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.2.0

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
