### ISSUE TITLE
Unable to set view visibility to hidden

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#104092]
Testing #103833

I'm using our [tree view sample](https://github.com/microsoft/vscode-extension-samples/tree/master/tree-view-sample) for this and have the following views set to hidden:

```json
		"views": {
			"package-explorer": [
				{
					"id": "nodeDependencies",
					"name": "Node Dependencies",
					"icon": "media/dep.svg",
					"contextualTitle": "Package Explorer",
					"visibility": "hidden"
				}
			],
			"explorer": [
				{
					"id": "jsonOutline",
					"name": "Json Outline",
					"when": "jsonOutlineEnabled",
					"visibility": "hidden"
				},
				{
					"id": "ftpExplorer",
					"name": "FTP Explorer",
					"visibility": "hidden"
				},
				{
					"id": "fileExplorer",
					"name": "File Explorer",
					"visibility": "hidden"
				},
				{
					"id": "testView",
					"name": "Test View",
					"visibility": "hidden"
				}
			]
		},
```

Yet, when I run the extension they are all still visible:

![image](https://user-images.githubusercontent.com/35271042/89439733-78358780-d6ff-11ea-9edb-5624bf425228.png)

![image](https://user-images.githubusercontent.com/35271042/89439957-ce0a2f80-d6ff-11ea-9e46-c79bdef54319.png)

**Comment by alexr00** [comment]
@misolori did you try using a fresh `--user-data-dir`?

**Comment by misolori** [comment]
I believe this is because of #104100, launched my extension first then modified settings and they didn't change.
