### ISSUE TITLE
Yo Code generator for Notebook renderer

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#104012]
Testing #103883 on MacOS

I used the `yo code` generator for the Notebook renderer and think some things are outdated in the generated package.json:

1. Change the "notebookProvider" contribution to "notebookContentProvider" 
2. Should `viewtype` for "notebookProvider" include "renderer"? 
3. Had a hard time getting the extension to activate when testing and seeing the option to "open with", so maybe changing the activation event to *
4. In the `yo code` set up, I just used the same identifier ("test-notebook") for all the options, I didn't expect to see "undefined_publisher" when choosing the kernel
![image](https://user-images.githubusercontent.com/9721254/89354223-25ab8b00-d66d-11ea-9d31-b4bb2334cb92.png)

![image](https://user-images.githubusercontent.com/9721254/89354260-41af2c80-d66d-11ea-9e58-c2d4c17de51f.png)

**Comment by connor4312** [comment]
Fixed these over time the past few weeks, thanks for the issue!
