### ISSUE TITLE
[security] Windows Security flags memfs.ts file as a threat

### ISSUE THREAD

**Issue by profnandaa** [microsoft/vscode#104049]
While setting up the dev environment for VSCode on my Windows, the `extensions\vscode-web-playground\src\memfs.ts` file is being flagged:

I suspect that this might be the cause, don't see why a `shell_exec` is being done in a sample file?
https://github.com/microsoft/vscode/blame/master/extensions/vscode-web-playground/src/memfs.ts#L108 

![image](https://user-images.githubusercontent.com/261265/89400139-20594980-d71c-11ea-8736-c35f512d1eab.png)

```
Threat detected: Backdoor:PHP/Dirtelti.OD
Alert level: Severe
Category: Backdoor
Details: This program provides remote access to the computer it is installed on
```

**Comment by soulshined** [comment]
This also happens with me on windows 10 but for `Dirtelti.OD`:

![Annotation 2020-08-07 145622](https://user-images.githubusercontent.com/11242654/89683506-461e5400-d8be-11ea-87f2-7cf641a5497f.png)

**Comment by xtqqczze** [comment]
?

https://github.com/microsoft/vscode/blob/466da1c9013c624140f6d1473b23a870abc82d44/extensions/vscode-web-playground/src/memfs.ts#L108

**Comment by bpasero** [comment]
Maybe @aeschli took care via https://github.com/microsoft/vscode/commit/14dabea7c2abd4e6002b66945d3d5d7832861983#diff-38312a033d92845f2c188a35c0f9eead

**Comment by xtqqczze** [comment]
> 
> 
> Maybe @aeschli took care via [14dabea#diff-38312a033d92845f2c188a35c0f9eead](https://github.com/microsoft/vscode/commit/14dabea7c2abd4e6002b66945d3d5d7832861983#diff-38312a033d92845f2c188a35c0f9eead)

Works for me.

**Comment by profnandaa** [comment]
@bpasero -- thanks for the follow up. As for the diff, what changed on L108, looks like it just moved to L110 or I'm mistaken?

**Comment by bpasero** [comment]
Looks like it, but I let him comment for the reasoning.

**Comment by aeschli** [comment]
I just tried various file modifications until scanner didn't complain anymore. I assume Windows Defender is also based on fingerprints and we were unlucky.
But I agree that we should improve the PHP sample code.

**Comment by bpasero** [comment]
I removed `shell_exec` from the sample.
