### ISSUE TITLE
Settings editor is awesome - could make it available to user projects

### ISSUE THREAD

**Issue by chsasank** [microsoft/vscode#104044]
Settings UI and the backend json is awesome. It's simple and the paradigm is very generic. It could be used for managing config/settings of other projects. Eg. settings of [Windows Terminal](https://github.com/microsoft/terminal) 

This whole paradigm could be made generic, documented and UI could be made available to other projects.

**Comment by roblourens** [comment]
It's not actually generic, it's tightly tied to vscode's settings model.

**Comment by chsasank** [comment]
vscode's settings model - the backend and frontend - is fairly generic. Configuration and settings are a necessity for every application out there. But good UX for settings is a rarity. vscode solved this UX issue and I propose this solution could be made available to other apps.

1. Users could use vscode settings model (i.e. documented jsons) for their own projects 
2. If some key of json is present (say like schema), vscode interprets these jsons and opens UI for editing these jsons
3. Taking 1 and 2 to extreme, settings model and UI could be separated out into a package which could be reused by other apps. I understand that this is more work.

I hope this makes my proposal clearer. I must admit I don't understand the internals of vscode very well - I'm a python dev. But I can't but appreciate our settings module and wish it is available for my project.

**Comment by roblourens** [comment]
Thanks for the idea but what you are proposing isn't a feature request, it's like a new product request. The code is tightly coupled to vscode and there is a lot of it. It's not a generic json schema editor, it's optimized for vscode's extensions of this and the subset that we use.

**Comment by chsasank** [comment]
> Thanks for the idea but what you are proposing isn't a feature request, it's like a new product request

I agree!

> Someone else is welcome to do the huge refactoring necessary to make this useful for other products but I think it might be faster to start over.

I think you're right about this. Starting over is easier. Would you be able to point me to the current code for settings editor and its backend. It'll help me and others whoever is interested in such a project. Thanks!

**Comment by yume-chan** [comment]
Many times, parts of Code are so good, but too tightly coupled with other parts to be extracted or reused.

**Comment by roblourens** [comment]
You can find the file `settingsEditor2.ts` and start from there.

**Comment by chsasank** [comment]
Thanks!
