### ISSUE TITLE
Add the ability to hide Action icons at the top of File Explorer

### ISSUE THREAD

**Issue by swrobel** [microsoft/vscode#104009]
The action icons at the top of the Explorer view are not useful to me, and take up a lot of space, especially when all other views are disabled. There are icons for:
* New File
* New Folder
* Refresh Explorer
* Collapse Folders in Explorer

<img width="171" alt="Screen Shot 2020-08-04 at 4 05 56 PM" src="https://user-images.githubusercontent.com/157270/89353963-740c5a00-d66c-11ea-8bf0-2eb821449da5.png">

I would like to remove this entire bar with these action icons so that my entire sidebar is the folder tree.

**Comment by cmedley** [comment]
@swrobel was able to remove them Custom CSS and JS Loader extension with the following in custom.css
`.title-actions { 
  display: none;
}`

so much better without those icons

**Comment by swrobel** [comment]
@cmedley thanks! how about an upvote so this has some chance of making it into the dev queue?

**Comment by soffes** [comment]
Bummer this is closed. Would love to see a preference for this :)

**Comment by swrobel** [comment]
@soffes lol @ commenting but not upvoting

**Comment by soffes** [comment]
@swrobel where should I upvote it?
