### ISSUE TITLE
Process explorer refreshes every few seconds

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#104013]
I'm just scrolling down in the gif:

![recording (21)](https://user-images.githubusercontent.com/2193314/89354686-58a24e80-d66e-11ea-94f9-cb8f560ce5f7.gif)

Version: 1.48.0-insider (user setup)
Commit: 459610f3ef11b956968afadff704bad3bc1a0de2
Date: 2020-08-04T12:40:10.231Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by Tyriar** [comment]
The process explorer is unusable for me without full screening it because of this, it's happening because the table is getting rebuilt every refresh instead of updated in place.

![recording (3)](https://user-images.githubusercontent.com/2193314/93606432-e74c0000-f97c-11ea-8fbc-fed87e3ced23.gif)

https://github.com/microsoft/vscode/blob/593e17873dd6bba9bc69c1fa70ad19ed9145ef46/src/vs/code/electron-sandbox/processExplorer/processExplorerMain.ts#L231-L272

**Comment by aeschli** [comment]
I like the process explorer but the refreshing makes the process explorer unusable. Any chance to prioritize the issue?

**Comment by Tyriar** [comment]
The scroll reset is fixed but it still feels weird using because of the refreshes https://github.com/microsoft/vscode/issues/115227
