### ISSUE TITLE
Creating a fork from a git push "fails" when on a different branch

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#104061]
Testing: https://github.com/microsoft/vscode/issues/102393

1. I cloned a repo I didn't have any permissions on.
2. Checkout a branch, in this case alexr00/testBranch
3. SCM menu -> push
4. Follow create a fork flow
5. Fork is created 🎉

Expected: My branch is also created
Actual: I get an error dialog: Couldn't find remote ref alexr00/testBranch

**Comment by hey24sheep** [comment]
Hi, can I work on this? I think this [PR](https://github.com/microsoft/vscode/commit/413e660e53049b5acc29990fbd170911fa705c84) will help me get started right? I could use these [Octokit](https://octokit.github.io/rest.js/v18#repos-list-forks) too. A little help would be appreciated. Thanks
