### ISSUE TITLE
Cannot Copy Text from HTML Output - Native Notebook Editor

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#104095]
Cannot copy text from HTML output

Steps to Reproduce:
1. print any data frame in output (HTML)
2. try to copy an element from the table and paste in another cell

**Comment by rebornix** [comment]
@claudiaregio are you testing on latest Insiders?

**Comment by claudiaregio** [comment]
Yes, updated everything this morning just in case to double check. Originally this issue was going to include Text output but after updating I saw that at least copying for that output had been fixed.

**Comment by rebornix** [comment]
@misolori I saw you played with data frames recently, can you reproduce this issue? I'm not able to reproduce.

**Comment by misolori** [comment]
On today's insiders I don't see this, though I did run into this issue before as well. @rebornix do you know when this was fixed?

**Comment by rebornix** [comment]
I fixed yesterday so it should be in today's Insiders. @claudiaregio can you provide screen recordings to help troubleshoot?

**Comment by claudiaregio** [comment]
1. Copied element from text output and pasted in new cell
2. Copied element from HTML output and tried to paste in new cell - failed and pasted code of cell. We had the exact same behavior in the QP. 
3. Tried a different element and was not able to paste anything at all. 

As a side note and potentially different issue, when I double click to select the element in the text output (1) it selects all the spaces that come after that element. Current notebook behavior is to not select any trailing spaces. 

![Copy from HTML ](https://user-images.githubusercontent.com/19276747/89480060-42b58c00-d749-11ea-8d54-7623f8abf34e.gif)

**Comment by rebornix** [comment]
@claudiaregio 

> I fixed yesterday so it should be in today's Insiders. @claudiaregio can you provide screen recordings to help troubleshoot?

We need recording of "Copied element from HTML output and tried to paste in new cell - failed and pasted code of cell. We had the exact same behavior in the QP." instead of above recording, which indicates the copy/paste is working as expected.

**Comment by rebornix** [comment]
@claudiaregio thanks, can you please run "Toggle Screencast Mode" and record again? Similar to below

![copy](https://user-images.githubusercontent.com/876920/89566140-75f12d00-d7d4-11ea-8bdc-9be21a051111.gif)

It would also be better if you can share the test file.

**Comment by claudiaregio** [comment]
I promise I was trying to copy and paste ;) 
I also went ahead and updated again this morning just in case, still working the same. 

I find it most interesting that the first copy I do with HTML output grabs the entire cell in the code, and the second grabs nothing... 

As requested: 

![Copy from HTML ](https://user-images.githubusercontent.com/19276747/89575543-cb343b00-d7e2-11ea-8ddd-478c99430b3e.gif)

**Comment by misolori** [comment]
I've tested this today on both plain text and the HTML output and can't repo. Both @rebornix and I are on Mac and I wonder if this is a Windows related issue?

**Comment by claudiaregio** [comment]
I am on windows.

**Comment by rebornix** [comment]
> I am on windows.

@claudiaregio thanks for helping figure out the root cause :)

**Comment by connor4312** [comment]
This works by default but not if `"webview.experimental.useIframes": true`. So this may break in the future if/when that becomes non-experimental

**Comment by claudiaregio** [comment]
+1 Customer reached out to me saying they're still currently experiencing this issue. 

I am also still experiencing this issue and now am getting an error in the bottom right. 

![image](https://user-images.githubusercontent.com/19276747/94718228-4e1ad300-0306-11eb-99b7-0648acdd63ad.png)

**Comment by claudiaregio** [comment]
+1 another customer still experiencing this issue with the same error 
https://github.com/microsoft/vscode-python/issues/14335

**Comment by ajasja** [comment]
(just wanted to add that in my case I can't copy either from the HTML or the plain text output)

**Comment by rebornix** [comment]
Pushed changes to mitigate this issue and verified on both macOS and Windows. Please verify if you are still seeing it.

**Comment by ajasja** [comment]
Works well for me in windows using python v2020.11.311084263-dev and vscode 
Version: 1.52.0-insider (user setup)
Commit: 65f805d98e798b979901b74d4c8810c05455b792
Date: 2020-11-10T08:05:00.147Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
