### ISSUE TITLE
Cannot open keybindings.json in diff view

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode#104077]
Testing #103604

![Screenshot from 2020-08-05 10-28-46](https://user-images.githubusercontent.com/8235156/89425074-889d3080-d706-11ea-8bc0-b0e0efebd4d4.png)

1. Turn on sync
2. Change some keybindings and sync them
3. Close vscode and delete the data directory and extensions directory
4. Open up vscode and don't change anything
5. Turn on sync and replace all remote data with local data
6. "Settings Sync: Show Synced Data..."
7. Click on keybindings.json

**Comment by sandy081** [comment]
Great catch
