### ISSUE TITLE
Can't use open folder or open file. Open file dialog not visible.

### ISSUE THREAD

**Issue by punkscience** [microsoft/vscode#104083]
Try open file, open folder -- basically anything that would use an open file dialog. Nothing happens and no files can be opened. The same thing occurs for 'Save as' when a new file is created. It appears as though dialog boxes may be hidden and/or off-screen.

Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)
--
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 1, 2, 2
Memory (System) | 32.00GB (1.16GB free)
Process Argv | -psn_0_10238403
Screen Reader | no
VM | 22%

Extension | Author (truncated) | Version
-- | -- | --
vscode-m3u | af4 | 1.0.0
mermaid-markdown-syntax-highlighting | bpr | 1.0.3
go | gol | 0.16.0
csharp | ms- | 1.22.1
python | ms- | 2020.7.96456
dot | Ste | 0.0.1
graphviz-interactive-preview | tin | 0.0.9
vscode-mermaid-preview | vst | 1.5.2

**Comment by isidorn** [comment]
Can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
@punkscience is this a Linux Snap installation?
