### ISSUE TITLE
Name for git repos

### ISSUE THREAD

**Issue by FStefanni** [microsoft/vscode#104068]
Hi,

I am using a multi-root workspace which has some repo folders with the same name, e.g. "test-project".
The built-in git plugin shows the repos by folder names, and in this case it makes it harder to understand which repo is which.
It could be nice (whether there is no current way -- I did not found one...) to set a specific name for each repo,
in order to easily distinguish the two folders with the same name.
For example, by using the name associated into the workspace configuration file (but also any other setting is fine too).

Regards.

**Comment by joaomoreno** [comment]
#40548
