### ISSUE TITLE
Chinese (and other languages) IME does not work correctly in Edge and IE11

### ISSUE THREAD

**Issue by jayspadie** [Microsoft/vscode#10407]
Using the Chinese (and other languages) IME (Input Method Editors) with Monaco in Windows 10 does not work correctly with Monaco in Edge and IE11 browsers.  It seems to work fine in Chrome.

Setup to use Chinese IME, as shown below in Windows 10 task bar:
![image](https://cloud.githubusercontent.com/assets/5246869/17568837/860ab276-5f13-11e6-9ca0-3502b6c71f5d.png)

Typing hazni<space> should give 哈祝你 as it does here.  I have no idea what this spells.  Hopefully, nothing offensive.

Now try to do that in Monaco at https://microsoft.github.io/monaco-editor/playground.html 
Using Chrome - works pretty well
Using IE - flaky, but sometimes works
Using Edge - doesn't really work at all

**Comment by jrieken** [comment]
This issue was moved to Microsoft/monaco-editor#104
