### ISSUE TITLE
Screen malfunctioning

### ISSUE THREAD

**Issue by Kaushty** [microsoft/vscode#104099]
Issue Type: <b>Bug</b>

I'm not sure whether the problem lies with VS Code or with my laptop, but this happens only when I'm using Vs Code. While using it, whenever I switch tabs and come back to VS the screen gets covered by these green matrix-like characters, as if the screen is defective. But this has never happened with any other app.

![Screenshot (126)](https://user-images.githubusercontent.com/54596479/89444943-1d884400-d770-11ea-9dc2-e9388a5b42f8.png)

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (0.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.13.1
flutter|Dar|3.13.1
es7-react-js-snippets|dsz|2.8.2
prettier-vscode|esb|5.1.3
solidity|Jua|0.0.75
python|ms-|2020.7.96456
java|red|0.65.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.23.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is this problem reproducible if you launch it as `code --disable-gpu`?

Details: [Disable GPU acceleration](https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration)

**Comment by Kaushty** [comment]
"disable-hardware-acceleration: true" was commented out, I uncommented it and it now it works fine. Thank you.

**Comment by IllusionMH** [comment]
Strange.

/cc @deepak1556 to see if it's something new or known problem

**Comment by deepak1556** [comment]
Thanks @IllusionMH , yeah have seen one another report similar to this.

@Kaushty this is probably fixed in recent version of chromium, can you test our exploration build without disabling hardware acceleration https://az764295.vo.msecnd.net/exploration/f0e1fbf4cb8c4c27d6290f0310f5a4d63597cd21/VSCodeUserSetup-x64-1.48.0-exploration.exe
