### ISSUE TITLE
Powershell Intergrated Console Won't Run Powershell Command after ps module version was updated

### ISSUE THREAD

**Issue by noendscripting** [microsoft/vscode#104084]
Extension version: 2020.6.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Update AZ powershell module in a seprate powershell window 
2. Attempt to run any command from Az.Compute module in the Intergrated Treminal
3. Receive following errors 

PS C:\GitRepo\Labdeploy> Publish-AzVMDscConfiguration

Publish-AzVMDscConfiguration: The 'Publish-AzVMDscConfiguration' command was found in the module 'Az.Compute', but the module could not be loaded. For more information, run 'Import-Module Az.Compute'.

PS C:\GitRepo\Labdeploy> Get-AzVM            

Get-AzVM: The 'Get-AzVM' command was found in the module 'Az.Compute', but the module could not be loaded. For more information, run 'Import-Module Az.Compute'.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
What does `Import-Module Az.Compute` say?

**Comment by noendscripting** [comment]
Import-Module Az.Compute doesn’t throw any errors, but when trying to run an AZ command, getting same error as above.
I tried various combinations of Import-Module/Restart Integrated Shell/Restart VS code and only restarting the whole computer worked

Michael Resnick | Premier Field Engineer - US PFE - East Region
michael.resnick@microsoft.com|<mailto:michael.resnick@microsoft.com%7C> (o) 980.776.7793  (c) 917.696.1690
Premier Support: 1.800.936.3100 | Premier Online: https://premier.microsoft.com<https://premier.microsoft.com/>
[cid:image001.jpg@01D670A1.5F439B00]
https://twitter.com/AzureSupport<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FAzureSupport&data=02%7C01%7CMichael.Resnick%40microsoft.com%7C64ccece7594a4936f83808d7a8f9380f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637163660759497841&sdata=1sFlBVPr%2B9nm%2F%2BJNHTzBkr%2FsLOmgLAksNstTqNg7nqQ%3D&reserved=0>
https://twitter.com/MSFT365Status<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FMSFT365Status&data=02%7C01%7CMichael.Resnick%40microsoft.com%7C64ccece7594a4936f83808d7a8f9380f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637163660759497841&sdata=S05MkNQN5RJN5%2Fo59OtO88m%2B9wL1xDbJMJuJ2l7YCnI%3D&reserved=0>
If you have any feedback about my work, please let either myself or my manager, Daryl Tutton  (Daryl.Tutton@microsoft.com<mailto:Daryl.Tutton@microsoft.com>)

[cid:image002.png@01D670A1.5F439B00] [cid:image003.png@01D670A1.5F439B00]
