### ISSUE TITLE
Register Cmd+Up as cursor position change in editor history

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#10409]
- VSCode Version: Code - Insiders 1.5.0-insider (666ed83a2d465257201cdac215a553ddee3cccbe, 2016-08-10T09:04:04.509Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:
1. Open file
2. Go to line 10
3. Go to line 20
4. Go to line 30
5. Press Cmd + Up
6. Press Ctrl + -
7. Press Cmd + Up
8. Press Ctrl + -

It should jump to line 30, but it jumps to line 20

if you repeat `Cmd + Up and Ctrl + -` it will go to line 10

Compared it with Sublime and they are doing it right (it goes to line 30)

Use case is this: 
Im working on given line and use something that is not imported - so I click Cmd+Up to add new import and then I want to go back - but often time it will go to some previous location making it dissorienting

**Comment by bpasero** [comment]
@normalser what action is triggered when you press Cmd+Up or Cmd+Minus, are they "Go Back" and "Go Forward"?

**Comment by normalser** [comment]
@bpasero `Cmd+Up` is `jump to first line` and `Ctrl+-` is `Go Back` - but I tried the original issue and it seems like it's solved (working currently on my latest insiders). Thanks a lot
