### ISSUE TITLE
Auto format destroys text when there is a comment with an umlaut in it

### ISSUE THREAD

**Issue by Bekaer** [microsoft/vscode#104060]
We have written the needed data into your clipboard because it was too large to send. Please paste.enter this text in any c file
e.g. test.h

// copy from here
// ä

void test()
{
auto kp = 1;
}
// to here

Enable option to auto format on save.
Save this file.

it results in:

// ä

void test()
{
a    uto kp = 1;
}

the source code gets completly destroyed for any auto formated line.
When you remove the ä (or any other commetn with umlaut in it) it works again.
Encoding for file is UTF8.

**Comment by yume-chan** [comment]
Code doesn't have a built-in formatter for C. So, it must be some of your extensions did that (and you forgot to paste the essential information, including your extension list, from your clipboard). 

Please check your extensions and report to the corresponding repo.

**Comment by Bekaer** [comment]
Stupid me...
You are absolutely right!

Gonna post it in the MS c++ extension repo!
