### ISSUE TITLE
Creating an Extension - Extension is not compatible with Code 1.46.1. Extension requires: ^1.47.0.

### ISSUE THREAD

**Issue by henryboisdequin** [microsoft/vscode#104036]
- VSCode Version: 1.46.1
- OS Version: 10.15.5

Type: Bug

I'm creating a VSCode extension and when debugging/running F5, I get an error: [/Users/henryboisdequin/Desktop/VSCode-Extension/firstextension]: Extension is not compatible with Code 1.46.1. Extension requires: ^1.47.0. With this error, the hello world program doesn't work. Help would be appreciated. Thanks

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Does your extension's `package.json` contain this?

```json
  "engines": {
    "vscode": "^1.47.0"
  },
```

**Comment by henryboisdequin** [comment]
Yes, now I understand why I have that error. Thanks
