### ISSUE TITLE
Number badge is not set when I am accessing the session with createIfNone set to false

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#104076]
Testing #103871

I am using the [GitHub authentication example](https://github.com/microsoft/vscode-extension-samples/blob/master/github-authentication-sample). During initialisation it requests for sessions with `createIfNone` set to false. In this case I would expect the extension entry to be shown under accounts activity bar icon. But it is now shown

<img width="395" alt="image" src="https://user-images.githubusercontent.com/10746682/89424920-a5eaf280-d738-11ea-8d2f-eab5954914cf.png">

**Comment by sandy081** [comment]
I am using the sample and I see that the sample is asking for the sessions with `createIfNone` to false which means that a number badge shall be shown for this sample extension

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/10746682/89525390-6549b280-d7e6-11ea-9f99-64ebc8b8ecba.png">

But it is not

<img width="402" alt="image" src="https://user-images.githubusercontent.com/10746682/89525403-6b3f9380-d7e6-11ea-8709-41b623f31c1a.png">

**Comment by RMacfarlane** [comment]
@sandy081 I'm having trouble reproducing this, do you mean nothing is shown on the accounts icon, or it shows the incorrect count? From your screenshot, I think I see the sliver of a badge, so is it showing a 1 instead of a 2?

**Comment by sandy081** [comment]
Because of the following call extension makes, I expect the extension entry in the drop down as mentioned in the documentation of `createIfNone`. But I see only entry from Github Pull Request Nightly Build extension and not from the sample.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/10746682/89525390-6549b280-d7e6-11ea-9f99-64ebc8b8ecba.png">

**Comment by RMacfarlane** [comment]
To verify:
- Sign out of GitHub
- Run the [GitHub authentication example](https://github.com/microsoft/vscode-extension-samples/blob/master/github-authentication-sample
- Check that a badge is displayed on the accounts icon and an entry in the accounts menu that says "Sign in to use github-authentication-sample"
