### ISSUE TITLE
Change the default command prompt from "code-insiders" back to "code."

### ISSUE THREAD

**Issue by Jhirai20** [microsoft/vscode#104005]
On the insider version of vscode the command prompt to launch vscode has been changed. 
Please change the default command prompt from "code-insiders" back to "code" on windows 10. This is a minor annoyance but one that can save al ot of time for new comers.

**Comment by IllusionMH** [comment]
> On the insider version of vscode the command prompt to launch vscode has been changed.

It was in this way in Insiders builds for more than a year, not sure what change you are referring to.
Moreover this helps to avoid conflicts for those who have both Insiders and Stable installed at the same time. 

> can save al ot of time for new comers

IMHO newcomers shouldn't use Insiders builds unless there is fix for major issues that is in latest Stable build.

Anyway if `code-insiders` is long - it's really easy to create alias or just copy/rename related launch file.
