### ISSUE TITLE
Notebook delete cell action should be at the end

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#104082]
![image](https://user-images.githubusercontent.com/35271042/89430753-f2600f00-d6f3-11ea-94b0-625c2fd54bd5.png)

This came up during the Python user study about a concern of having the delete cell action so close to the other actions because it's such a destructive action. In the terminal panel, the delete action is also on the far right side for this reason:

![image](https://user-images.githubusercontent.com/35271042/89430971-2c311580-d6f4-11ea-90ca-fa6f3924e24b.png)

We might think about moving this to the far right as well next to the ellipsis (on either side).

**Comment by roblourens** [comment]
In the panel it seems like it's also sandwiched between two other actions. Same in the editor title: 
![image](https://user-images.githubusercontent.com/323878/89469653-c01fd300-d72e-11ea-9031-b9e648d6791a.png). I think the toolbar forces the `...` to be the last but we could give it the capability to customize this ordering. Or just make the delete action a special case in its own action bar or something

**Comment by misolori** [comment]
I've noticed that some apps do move the "deleted" into the context menu. Depending on how often this gets used, this could be another option?

Slack
<img width="300" src="https://user-images.githubusercontent.com/35271042/89472235-c9ac3980-d734-11ea-829c-a85a88097d6f.png">

Outlook
<img width="300" src="https://user-images.githubusercontent.com/35271042/89472234-c7e27600-d734-11ea-9a9b-79b886662741.png">

Teams
<img width="300" src="https://user-images.githubusercontent.com/35271042/89472262-dd57a000-d734-11ea-90e9-1878f2483342.png">

**Comment by rebornix** [comment]
We can experiment moving it into the context menu. It scarifies a bit usability for mouse users but it's much less possible to misclick.

**Comment by roblourens** [comment]
Ah true

**Comment by roblourens** [comment]
Feedback in the call last week was negative regarding putting the action only in the context menu. Other options

- Put it by itself on the right side
- Keep it in the same toolbar, just on the right side

**Comment by misolori** [comment]
Had a quick chat with the Python designer and they actually weren’t opposed to having it in the context menu. So we can add that as an additional option if we decide moving it to the side doesn’t work.

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/90705593-2d138c80-e248-11ea-8979-fbfd6f0763b1.png)

**Comment by roblourens** [comment]
We can try this or just do context menu, whatever
