### ISSUE TITLE
js-debugger error when open a project usin Open Workspace 

### ISSUE THREAD

**Issue by geordanisb** [microsoft/vscode#104002]
- VSCode Version: 1.47.3
- OS Version:Linux x64 4.15.0 (ubuntu 18.04)

Steps to Reproduce:
1. Open a project using Open Workspaces.
2. Follow the https://github.com/microsoft/vscode-js-debug#whats-new  steps
3- Get the error: '${workspaceFolder}' can not be resolved in a multi folder workspace. Scope this variable using ':' and a workspace folder name.

note: if i open the same project using Open Folder instead of Open Workspace --all works as expected

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
Please try two things:

1. Setting your launch.json `type` to `pwa-node` instead of `node`
1. If that doesn't work, share the launch.json with it

**Comment by geordanisb** [comment]
Thank you very much for responding so soon!
the same result with the config specified by you
my simple launch.json:
{
"configurations": [
{
"type": "pwa-node",
"request": "attach",
"name": "Attach by Process ID",
"processId": "${command:PickProcess}",
"skipFiles": [
"<node_internals>/**"
]
}
]
}

error:
[image: image.png]

should i have to config a launch.json for each folder within my workspace?
that would not be practical because there are many folders and continue to
increase; i decide to using workspace because when use Open Project and try
to search files with Ctrl +p there many files that not shown in the search
result.
Regards!

**Comment by connor4312** [comment]
You can add an option to your launch config like `"cwd": "${workspaceFolder:someScope}"` to set the folder to use as context for the config.

**Comment by geordanisb** [comment]
the same result with the config:
{
"folders": [
{
"path": "/home/geo/main"
},
{
"path": "/home/geo/main/scriptdirs/src/core"
},
{
"path": "/home/geo/main/scriptdirs/src/base"
}
],
"settings": {
"debug.node.autoAttach": "on"
},
"launch": {
"configurations": [
{
"type": "pwa-node",
"request": "attach",
"name": "Attach by Process ID",
"processId": "${command:PickProcess}",
"skipFiles": [
"<node_internals>/**"
],
"cwd": "${workspaceFolder:main}"
}
],
"compounds": []
}
}

>

**Comment by connor4312** [comment]
Are you trying to use auto attach or your custom configuration? The auto attach issue is tracked here https://github.com/microsoft/vscode/issues/103099

**Comment by geordanisb** [comment]
First auto attach and then Custom configuration both With the same result

**Comment by connor4312** [comment]
Thanks, these both should be fixed in the next VS Code Insiders versions, and the stable release coming next week.

**Comment by geordanisb** [comment]
Thank you very much for the help
