### ISSUE TITLE
ifconfig/ip not guaranteed to be in /sbin

### ISSUE THREAD

**Issue by Muzer** [microsoft/vscode#104016]
- VSCode Version: 1.47.3
- OS Version: Gentoo latest stable

Steps to Reproduce:

1. Run ./code on Gentoo
2. Notice errors printed to the console relating to /sbin/ifconfig

Does this issue occur when all extensions are disabled?: Yes

ifconfig and ip aren't guaranteed to be installed into /sbin. On Gentoo, they are installed into /bin, to ensure they are in unprivileged users' PATH (since it's a common requirement for users to check the IP address of the system). You probably shouldn't be hardcoding paths to these, I would say.

**Comment by sbatten** [comment]
This was resolved separately

**Comment by bpasero** [comment]
I think we no longer execute `ifconfig` iirc.
