### ISSUE TITLE
Link to docs on what `when` clauses mean

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#104000]
Testing #103835

Can't seem to find docs on what exactly these values mean and when they're enabled. 

![image](https://user-images.githubusercontent.com/8586769/89347384-7fa55400-d65f-11ea-8085-eeda0255ac20.png)

**Comment by kimadeline** [comment]
verified:
![image](https://user-images.githubusercontent.com/51720070/144334441-0538c001-3fc5-4898-b248-ec5ab5877eff.png)

![image](https://user-images.githubusercontent.com/51720070/144334472-22c09ac5-3929-4106-9e2c-aacf90aee616.png)
