### ISSUE TITLE
Add a focus mode (Feature request made for nomenclature uniformaty)

### ISSUE THREAD

**Issue by NicTanghe** [microsoft/vscode#104098]
Please add a focus mode to Vscode on windows. (also all other programs)
Dont tell me but it`s hard.
Every other code editor has a focus mode.

**Comment by lszomoru** [comment]
Could you please elaborate on what you mean by `focus mode`?
Are you aware of the `zen mode` feature - https://code.visualstudio.com/updates/v1_8#_zen-mode?

**Comment by NicTanghe** [comment]
Yes i`m fully aware of the zenmode that requires fullscreen and is therefor
not verry zen.

Zenmode is Microsoft own term for mode to remove 100% useless titlebar.



Op wo 5 aug. 2020 om 19:38 schreef Ladislau Szomoru <
notifications@github.com>:

**Comment by gjsjohnmurray** [comment]
> 100% useless titlebar.

/gifPlease

**Comment by NicTanghe** [comment]
I meen the a feature that just allows us to toggle the titlebar existing (like shift + f11).
If you need a screenshot to understand what a titlebar is i wonder how you go through life.

Below no shift+F11
![p6xFa9eIcC](https://user-images.githubusercontent.com/13624265/89541149-46571a80-d7fe-11ea-8f37-d9d86aa5470d.png)

Below shift + F11 working on the terminal but not in vscode
![image](https://user-images.githubusercontent.com/13624265/89541231-671f7000-d7fe-11ea-8a32-05d2cf23828a.png)

**Comment by NicTanghe** [comment]
NOte that it shouldn`t delete the tabbar in vscode only in the terminal.

**Comment by isidorn** [comment]
Closing as will not fix

**Comment by NicTanghe** [comment]
I meen the a feature that just allows us to toggle the titlebar existing
(like shift + f11).
If you need a screenshot to understand what a titlebar is i wonder how you
go through life.



Op wo 5 aug. 2020 om 22:56 schreef VS Code Issue Triage Bot <
notifications@github.com>:
