### ISSUE TITLE
git.api.getRemoteSources provider label already includes icon

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#104050]
Testing https://github.com/microsoft/vscode/issues/102394

```typescript
providerLabel: (provider: RemoteSourceProvider) => {
	return `My fancy label ${provider.name} $(${provider.icon ?? 'zap'})`;
},
```

Since I get to set the label and have access to the icon, I expect that there isn't already an icon at the beginning of the label:

![image](https://user-images.githubusercontent.com/38270282/89400280-f69c2480-d713-11ea-9fbe-e86088ee25db.png)

**Comment by joaomoreno** [comment]
Hmm not sure... the GitHub remote source provider gives me an icon it wants all its rows to have... so I place it at the beginning. You can just control the phrasing around each item like `Clone from []` or `Publish to []`.  Closing as designed, sorry! 😨
