### ISSUE TITLE
Allow hovers to show at cursor's x position instead of the left of the target element

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#104058]
Current:

![89308368-78d40c80-d672-11ea-8248-6ed0d0cb0b2f](https://user-images.githubusercontent.com/2193314/89413551-dc475400-d6dd-11ea-8870-9eed0bdc4015.gif)

Desired:

![image](https://user-images.githubusercontent.com/2193314/89413451-b28e2d00-d6dd-11ea-8cff-65c1f3a5ba66.png)

Context: https://github.com/microsoft/vscode/issues/100741

**Comment by eamodio** [comment]
I would also say it should be "pop" down, rather than up (unless there is no room) -- like normal tooltips. Although much less of an issue than the x position.

**Comment by eamodio** [comment]
Related issue: If a hover is too wide for the tree, it seems to cause it to move down and ends up covering the row its for

Here the view is wide enough and its fine

![image](https://user-images.githubusercontent.com/641685/89992716-ac56fe00-dc53-11ea-828a-57cc2b7fb419.png)

But here its too narrow, and you can't see the item for which the hover is for

![image](https://user-images.githubusercontent.com/641685/89992741-b678fc80-dc53-11ea-9e71-5211899a10e2.png)

**Comment by Tyriar** [comment]
> I would also say it should be "pop" down, rather than up (unless there is no room) -- like normal tooltips. Although much less of an issue than the x position.

It aligns with hovers in the editor now, I'd rather not make things inconsistent without a compelling reason.

> But here its too narrow, and you can't see the item for which the hover is for

Looks like a bug, please create another issue

**Comment by Tyriar** [comment]
@alexr00 there's now an `x?: number` on the target for this, let me know if there are issues 🙂

**Comment by alexr00** [comment]
Works nicely, thank you!
