### ISSUE TITLE
Go to definition shows Node require statement as definition

### ISSUE THREAD

**Issue by gorgos** [microsoft/vscode#104021]
I'm simply doing

```
const { calcMargin } = require('../../order-utils');
...
calcMargin()
```

and the `calcMargin` call shows two definitions: 1. the require line and 2. the actual function definition that I want to go to.

![vs-goto-small](https://user-images.githubusercontent.com/659390/89249826-ab303a80-d66f-11ea-98dd-3ebc7cc8f5d1.gif)

```
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```

Same issue in Typescript: https://github.com/microsoft/TypeScript/issues/39895

Related but not identical to https://github.com/microsoft/TypeScript/issues/37816.

**Comment by mjbvz** [comment]
Closing as upstream TypeScript issue
