### ISSUE TITLE
Rename `git.enableSmartCommit` to `commitAllChangesWhenNoChangesAreStaged`

### ISSUE THREAD

**Issue by JayBazuzi** [microsoft/vscode#104017]
The setting `git.enableSmartCommit` doesn't explain what it does - how am I supposed to know what "smart" is? I go look it up and find:

```
    // Commit all changes when there are no staged changes
    "git.enableSmartCommit": true,
```

Suggest renaming the option to describe what it actually does.

**Comment by joaomoreno** [comment]
This is why we document every single setting. You can see its documentation if you hover over it, if you use intellisense or in the settings editor.

![image](https://user-images.githubusercontent.com/22350/89391430-82a84f00-d708-11ea-915c-3dd904453206.png)

![image](https://user-images.githubusercontent.com/22350/89391551-a66b9500-d708-11ea-91a2-39ab7451eef1.png)

![image](https://user-images.githubusercontent.com/22350/89391618-b8e5ce80-d708-11ea-8bff-531c3b427ea6.png)
