### ISSUE TITLE
Cannot open Extension Development Window [Windows specific]

### ISSUE THREAD

**Issue by unkemptArc99** [microsoft/vscode#104038]
Issue Type: <b>Bug</b>

I am unable to open the Extension Development Window in VS Code on Windows. It is stuck on "Building" notification (see the image) on the lower pane and nothing happens even after waiting for a long time.

![Stuck on Building notification](https://user-images.githubusercontent.com/19533670/89388160-433a2c80-d721-11ea-8b43-1d0e1e1b1cf6.png)

<b>Steps to Reproduce</b>
1. Create the hello world extension template following the steps in [Your First Extension](https://code.visualstudio.com/api/get-started/your-first-extension) guide.
2. Press `F5` for opening the Extension Development Window.

<b>Extra observations</b>
1. I am only experiencing this issue in Windows. I have tried the same on Mac and Linux and in both the cases, it works perfectly fine.
2. I have tried compilation commands separately in terminal window, and everything executes properly. The `compile` command exits after compiling and the `watch` command watches on file changes and compiles successfully.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
code-gnu-global|aus|0.2.2
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
gitlens|eam|10.2.2
git-project-manager|fel|1.7.1
guid|kos|0.0.1
musupport|Mic|0.0.6
python|ms-|2020.7.96456
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
cpptools|ms-|0.30.0-insiders
powershell|ms-|2020.6.0
vscode-asl|Tho|1.0.0
vscode-icons|vsc|10.2.0
edk2-vscode|wal|1.0.3
markdown-pdf|yza|1.4.4

</details>

**Comment by OnePieceJoker** [comment]
I also encountered this problem today. Reproduction steps are the same as you

VS Code version: Code 1.47.3 (91899dc, 2020-07-23T13:12:49.994Z)
OS version: Windows 10 1903

**Comment by OnePieceJoker** [comment]
I hope this helps. When I use the computer to execute the same project, I can debug the plug-in normally. Then, after I upgraded the local node.js version to 12.18.3, I couldn't debug the plugin.

### Before upgrading nodejs

### Related configuration of my computer
VS Code version: 1.47.3 (91899dc, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363
Node.js version: 12.13.1
npm version: 6.12.1

![image](https://user-images.githubusercontent.com/25676220/89431096-119d8180-d772-11ea-82e7-d737b2201580.png)

### After upgrading nodejs

### Related configuration of my computer
VS Code version: 1.47.3 (91899dc, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363
Node.js version: 12.18.3
npm version: 6.14.6

![image](https://user-images.githubusercontent.com/25676220/89431877-0eef5c00-d773-11ea-8ac7-33336db0759e.png)

**Comment by OnePieceJoker** [comment]
> I hope this helps. When I use the computer to execute the same project, I can debug the plug-in normally. Then, after I upgraded the local node.js version to 12.18.3, I couldn't debug the plugin.
> 
> 
> 
> ### Before upgrading nodejs
> 
> 
> 
> ### Related configuration of my computer
> 
> VS Code version: 1.47.3 (91899dc, 2020-07-23T13:12:49.994Z)
> 
> OS version: Windows_NT x64 10.0.18363
> 
> Node.js version: 12.13.1
> 
> npm version: 6.12.1
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/25676220/89431096-119d8180-d772-11ea-82e7-d737b2201580.png)
> 
> 
> 
> ### After upgrading nodejs
> 
> 
> 
> ### Related configuration of my computer
> 
> VS Code version: 1.47.3 (91899dc, 2020-07-23T13:12:49.994Z)
> 
> OS version: Windows_NT x64 10.0.18363
> 
> Node.js version: 12.18.3
> 
> npm version: 6.14.6
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/25676220/89431877-0eef5c00-d773-11ea-8ac7-33336db0759e.png)
> 
> 
> 
> 


This is the result of my operation on my personal computer

**Comment by connor4312** [comment]
`Building` happens before the handoff to the debugger, thus pinging Alex R

**Comment by unkemptArc99** [comment]
@OnePieceJoker Thank you for the information. So, I do remember updating nodejs, but I didn't think that the problem might be tied to that, because all terminal builds were working perfectly. At this present moment -
- Node.js - v12.16.3
- npm - v6.14.4

I will rollback to previous versions and see if it solves the problem.

**Comment by unkemptArc99** [comment]
@OnePieceJoker In my case, I am still facing this issue with older version of node.js . Maybe the problem has some combination with nodejs version and some other issue.

**Comment by alexr00** [comment]
If `Building` never goes away, that indicates that the build task never finished, or the problem matcher couldn't tell that build task finished. In your launch configuration, what is the `prelaunchTask`? Can you also share your tasks.json?

**Comment by alexr00** [comment]
Can you also share the output from the `prelaunchTask`? I'm suspecting something like https://github.com/microsoft/vscode/issues/104157

**Comment by unkemptArc99** [comment]
@alexr00 Following is my tasks.json
```
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

And the following is my launch.json -
```
// A launch configuration that compiles the extension and then opens it inside a new window
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}"
		},
		{
			"name": "Extension Tests",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--extensionTestsPath=${workspaceFolder}/out/test/suite/index"
			],
			"outFiles": [
				"${workspaceFolder}/out/test/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}"
		}
	]
}
```

**Comment by alexr00** [comment]
Thanks for sharing those. To get the output of your `prelaunchTask` you can simply click on the `Building` in the status bar. That will open the terminal that the task is running in and you can copy the contents of the terminal.

**Comment by unkemptArc99** [comment]
Okay, I found one more observation with this issue.

I normally use Powershell as my default terminal in VSCode. While capturing the output of `preLaunchTask` with Powershell, I found the following output -
```
> Executing task: npm run watch <

PS C:\Users\<folder-path>\hello-world>
```

Since, I had run `npm run watch` separately in a Powershell terminal window, I knew that this is not the exact output of `npm run watch` and it does spew a lot more logs than simply displaying the message `> Executing task: npm run watch <`, so I changed the default terminal to Command Prompt, and ran the Build task again. This time, the Extension development window did open and I received the following output -
```
> Executing task: npm run watch <


> hello-world@0.0.1 watch C:\Users\<folder-path>\hello-world
> tsc -watch -p ./

[4:27:59 PM] Starting compilation in watch mode...

[4:28:03 PM] Found 0 errors. Watching for file changes.
```

**Comment by alexr00** [comment]
Can you share all the `task` and `terminal` settings you have set?

**Comment by unkemptArc99** [comment]
These are my `terminal` settings in VSCode -
```
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.shellArgs.windows": [
        "-ExecutionPolicy", "Bypass",
        "-NoLogo",
        "-NoProfile",
        "-NoExit",
        "-Command", ". '<path-to-profile file>'"
    ],
    "terminal.integrated.fontFamily": "Meslo LG M for Powerline",
```
and the following is the profile for Powershell that I am using - 
```
Import-Module Get-ChildItemColor

Set-Alias l Get-ChildItemColor -Option AllScope
Set-Alias ls Get-ChildItemColorFormatWide -Option AllScope

function cws { Set-Location c:\ws }

function cuserprofile { Set-Location ~ }
Set-Alias ~ cuserprofile -Option AllScope

function U
{
    param
    (
        [int] $Code
    )
 
    if ((0 -le $Code) -and ($Code -le 0xFFFF))
    {
        return [char] $Code
    }
 
    if ((0x10000 -le $Code) -and ($Code -le 0x10FFFF))
    {
        return [char]::ConvertFromUtf32($Code)
    }
 
    throw "Invalid character code $Code"
}

Import-Module -Name posh-git

if (! (ps | ? { $_.Name -eq 'ssh-agent'})) {
    Start-SshAgent
}

Import-Module -Name oh-my-posh
Set-Theme agnoster
```

I don't think I understand the `task` settings that you require. Isn't the `task` setting the same as the ones listed in `tasks.json`. Sorry I am not knowledgeable about this.

**Comment by alexr00** [comment]
@unkemptArc99 the task system works by passing the `-Command` argument to your chosen shell. In this case, since you have a bunch of `shellArgs` set, that doesn't work. You should be able to solve this by simply setting `"terminal.integrated.automationShell.windows"` to the shell of your choice. Can you try setting that setting to powershell and see if it solves your problem?

**Comment by OnePieceJoker** [comment]
@alexr00 it's not work for me. The configuration of my task.json and launch.json files is the same as @unkemptArc99 , These are my `terminal` settings in VSCODE:

```
"terminal.integrated.shell.windows": "D:\\Program Files\\Git\\bin\\bash.exe",
"terminal.external.windowsExec": "D:\\Program Files\\Git\\git-bash.exe",
"terminal.integrated.automationShell.windows": "D:\\Program Files\\Git\\bin\\bash.exe",
```

And this is my build output:

```
> Executing task in folder ximalaya-on-vscode: npm run watch <


> ximalaya-on-vscode@0.0.1 watch F:\vscodeworkspace\project\ximalaya-on-vscode
> tsc -watch -p ./

[8:48:50 ├F10: PM┤] Starting compilation in watch mode...

[8:48:52 ├F10: PM┤] Found 0 errors. Watching for file changes.
```

**Comment by alexr00** [comment]
@OnePieceJoker you are seeing https://github.com/microsoft/vscode/issues/104157.

**Comment by unkemptArc99** [comment]
> You should be able to solve this by simply setting `"terminal.integrated.automationShell.windows"` to the shell of your choice. Can you try setting that setting to powershell and see if it solves your problem?

@alexr00 This worked! Thank you for your help. 😄

**Comment by OnePieceJoker** [comment]
> @OnePieceJoker you are seeing #104157.

@alexr00 I found #103390 through #104157, it solved my problem very well, thank you for your help.
