### ISSUE TITLE
The terminal process exited with code 1 - Can't open terminal

### ISSUE THREAD

**Issue by Eli-Goldberg** [Microsoft/vscode#10406]
- VSCode Version: 1.4
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open VSCode
2. Press Ctrl+` to open integrated terminal
3. The message "The terminal process exited with code 1" is displayed always (attached)

![image](https://cloud.githubusercontent.com/assets/19211868/17568089/dad6d29e-5f4a-11e6-88f5-3a3b96f5bd2f.png)

**Comment by Tyriar** [comment]
Can you check if there are errors in the dev tools console? (Help > Toggle Developer Tools)

Also do you have anything in your `settings.json`? Anything running in your `.bashrc` that could be causing the exit?

**Comment by Eli-Goldberg** [comment]
The dev console doesn't show any errors, settings.json is empty, .bashrc hasn't been changed.
It appears that after installing zsh, console is now working.
I think this is a local issue, If it happens again I'll try to dive deeper.
Thank you for your help @Tyriar.
