### ISSUE TITLE
my code gets scatterred when saved a react code

### ISSUE THREAD

**Issue by jazzy19** [microsoft/vscode#104027]
Issue Type: <b>Bug</b>

my code gets scatterred when saved a react code

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (6.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-tailwindcss|bra|0.4.1
path-intellisense|chr|2.2.1
vscode-html-css|ecm|0.2.3
auto-close-tag|for|0.5.8
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
csharp|ms-|1.22.1
vscode-css-peek|pra|4.0.0
LiveServer|rit|5.6.1
vscode-icons|vsc|10.2.0
beauty|yhp|0.0.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by Temaska** [comment]
@jazzy19 it seems one of your extensions is formatting code when save. Try to disable all or at least `vscode-JS-CSS-HTML-formatter` and `beauty`
