### ISSUE TITLE
Keybindings are cleared after merging changes

### ISSUE THREAD

**Issue by 9at8** [microsoft/vscode#104085]
Testing #103604

Window 1: `code-insiders --user-data-dir ./data --extensions-dir ./extensions`
Window 2: `code-insiders --user-data-dir ./data-2 --extensions-dir ./extensions-2`

1. Enable settings sync in window 2 and change a keybinding
2. Change the same keybinding to something else in window 1
3. Enable settings sync in window 1
4. Click on "Merge"
5. Unable to merge dialog is shown, click "Show merges"
6. "Accept Remote"
7. Keybindings are gone

![recording (2)](https://user-images.githubusercontent.com/8235156/89431219-a02be780-d70d-11ea-94f3-200b3759f00b.gif)

**Comment by sandy081** [comment]
Great catch again 👍

**Comment by roblourens** [comment]
I think this happened again. I clicked "accept remote and it looks like it accepted local.

**Comment by sandy081** [comment]
@roblourens I followed the steps again and it seems fixed to me. Here is the video showing the steps I followed:

![Kapture 2020-08-11 at 10 34 58](https://user-images.githubusercontent.com/10746682/89876183-977c5b00-dbbe-11ea-8b33-bdac75638580.gif)

**Comment by roblourens** [comment]
I see where I went wrong. After clicking "accept remote", the diff editor is replaced with the local keybindings.json. I then have to go back to the viewlet and click "Turn on settings sync" to continue, and see that it did actually accept the remote keybindings. I just got lost in the flow.
