### ISSUE TITLE
Unexpected text copied after switching output mimetype

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#104003]
Testing #103860

- Switch output mimetype to `text/markdown`, select some text and then copy -> correct text is copied and pasted into notepad
![image](https://user-images.githubusercontent.com/25310137/89347811-51744400-d660-11ea-8703-1f57efb7d36f.png)
- Switch output mimetype back to `text/html`, select some text and then copy -> I didn't expect the code cell's contents would be copied, rather than the output content I highlighted
![image](https://user-images.githubusercontent.com/25310137/89347924-808ab580-d660-11ea-9e38-24dc8d949fe9.png)

Is there a way we can allow users to copy and paste the html output? Or is that the point of switching to the markdown format?

If this is the correct/expected behavior, please feel free to close.

**Comment by rebornix** [comment]
@bamurtaugh can you confirm if you are still seeing this issue in latest Insiders?

**Comment by bamurtaugh** [comment]
@rebornix Yes, I just tried again and am still experiencing this. I can copy and paste markdown output, but attempting to highlight and copy the html output still pastes the input cell's contents rather than the output.

![image](https://user-images.githubusercontent.com/25310137/89572338-d3d64280-d7dd-11ea-81cc-d13a9a9462c7.png)

![image](https://user-images.githubusercontent.com/25310137/89572506-0849fe80-d7de-11ea-8649-818321b841c7.png)

Version: 1.48.0-insider (user setup)
Commit: cfbd1999769f4f08dce29629fb92fdc0fac53829
Date: 2020-08-06T05:59:51.622Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by rebornix** [comment]
The bug is already fixed in master.
