### ISSUE TITLE
ctrl+c ctrl+v not working

### ISSUE THREAD

**Issue by yashGuleria** [microsoft/vscode#104026]
Issue Type: <b>Bug</b>

copy paste option not working for the ipynb notebook 

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (21.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.36.2
vscode-eslint|dba|2.1.8
vscode-great-icons|emm|2.1.47
gc-excelviewer|Gra|3.0.39
beautify|Hoo|1.5.0
vscode-map-preview|jum|0.5.5
python|ms-|2020.7.96456
LiveServer|rit|5.6.1
pdf|tom|1.1.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.8.5

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Likely fixed in current Insiders, slated to become the 1.48 release next week.
