### ISSUE TITLE
all extensions syntax highlight not working

### ISSUE THREAD

**Issue by baniyasi** [microsoft/vscode#104093]
Issue Type: <b>Bug</b>

all syntax is recognized as plaintext, all is white, all extensions syntax highlight not working

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:04:33.747Z)
OS version: Linux x64 2.6.32-696.el6.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (48 x 1200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|3, 3, 3|
|Memory (System)|125.96GB (21.20GB free)|
|Process Argv|/usr/local/VSCode-linux-x64/code|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by tristan957** [comment]
@baniyasi you get no syntax highlighting at all for any kind of file? Or what specific kinds of files?

**Comment by baniyasi** [comment]
> any kind of file,

**Comment by tristan957** [comment]
@baniyasi does this happen with all extensions disabled? And do you possibly having `files.associations` set in your settings.json?

**Comment by baniyasi** [comment]
i just installed it, my settings.json is empty. Is it because the version I use is too old? I use CentOS 6 system

**Comment by baniyasi** [comment]
code completion works well, the problem is highlight, even settings.json's highlight is not work

**Comment by tristan957** [comment]
I don't think that should matter. How did you install VSCode? Through the RPM repo? I am not even sure if CentOS 6 is a supported platform by Electron anymore.

**Comment by baniyasi** [comment]
> I don't think that should matter. How did you install VSCode? Through the RPM repo? I am not even sure if CentOS 6 is a supported platform by Electron anymore.

install by extract  .gz file.   i know that some people use this version of vscode in CentOS 6 as I do, but they don't have the highlight problem, others have the same problem as me.   anyway, thanks for your reply and help

**Comment by tristan957** [comment]
Do you see any errors in your developer tools console?

Could you also provide a screenshot of the issue?

**Comment by baniyasi** [comment]
> Do you see any errors in your developer tools console?
> 
> Could you also provide a screenshot of the issue?

i found an ERR in the developer tool that required glibc2.14. Now that the problem has been solved, thank you very much

**Comment by tristan957** [comment]
No problem. Have a good one :).
