### ISSUE TITLE
Terminal powerline font is distorted

### ISSUE THREAD

**Issue by Phaenyxx** [microsoft/vscode#104070]
- VSCode Version: 1.47.3
- OS Version: Fedora 32

Steps to Reproduce:

1. Install code
2. Add a powerline font to the terminal (Tested with different fonts, the problem is always the same)

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/27176415/89421048-d714f400-d733-11ea-9b98-23b25edf87f8.png)
The rest of the windows is also pretty much blurry, is there a way to tweak the subpixel rendering as it looks like this is the problem ?

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/84432

For the rest of the window I'm not sure, something doesn't look right. Perhaps the really small font sizes are part of the problem?
