### ISSUE TITLE
Data Frame in Output - Native Notebook Editor

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#104094]
When VS Code window is large enough, data frames in outputs are displayed fine. 

![image](https://user-images.githubusercontent.com/19276747/89439967-d2364d00-d6ff-11ea-88d8-913d1950042c.png)

When VS Code window is too small, no horizontal scroll bar appears to see the rest of the data frame. 
Would also be worth checking if horizontal scroll appears when VS Code window is maximized and number of columns in a data frame is large. 

![image](https://user-images.githubusercontent.com/19276747/89440314-4a9d0e00-d700-11ea-8487-9979a726aec8.png)

**Comment by rebornix** [comment]
cc @misolori who is seeing scrolling issue with data frame.

**Comment by misolori** [comment]
Yep, planning to fix today and already have an issue for it: https://github.com/microsoft/vscode/issues/103981
