### ISSUE TITLE
How do I make a command that only appears in the command pallet when my extension is loaded?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10401]
I'd like to some commands that only appear when a Dart project is open (eg. my extension is activated). If I add a command to `packages.json` it seems to always be available in the command pallet. (These commands are equiv of `nuget restore` etc., you wouldn't want them visible when you open a Perl project, for example).

I'm sure I'm missing something; but I just can't figure out how to control this :(

**Comment by jrieken** [comment]
You can actually not... Today all commands are known upfront to decouple UI for a command from the actual command implementation. We do that to prevent eager loading of the world. I do understand tho that you want some additions after the fact...

**Comment by DanTup** [comment]
Is there an existing convention for what to do here? Do other extensions just add it to the list, Allow it to activate the extension and then show a message?

Or is there anything better than commands for this sort of thing?

**Comment by DanTup** [comment]
Just noticed PoSh "Expand Alias" is listed in there and just fails with "command not found" when the extension isn't loaded. I guess I'll do the same for now (eg. not include the commands as activation events).

Any reason why the same criteria applied to activating extensions couldn't be applied? You're already scanning for this (or grabbing it at install time)?

**Comment by DanTup** [comment]
Just noticed PoSh "Expand Alias" is listed in there and just fails with "command not found" when the extension isn't loaded. Does this seem like a reasonable behaviour to copy for now (eg. don't add it to `activateOn`)?

> We do that to prevent eager loading of the world

Registering a command in `activate` and disposing in `deactivate` (or pushing to subscriptions) would allow what we want without introducing any issues like that? (Actually, we already register in activate... so maybe just hiding a command that has no handlers registered is a clean fix?)

**Comment by jrieken** [comment]
Well, `registerCommand` is about assigning an identifier to a function. The `commands` and also the `menuitems`-part is to assign UI to that identifier. So, when not having a command activation event nothing bad will happen but it's also not necessarily the recommended way - that why we have the `onCommand:xyz` activation event. 

This is a fair feature request, at least the F1 commands list should be dynamic in some way

**Comment by eamodio** [comment]
Without any changes here -- is there anyway today to have an extension get rid of command defined in `package.json`? I've gotten a [request](https://github.com/eamodio/vscode-gitlens/issues/31) in [GitLens](https://github.com/eamodio/vscode-gitlens) to "disable" when there is no git repository. I currently detect that case and don't initialize, but all the commands still show up in the command palette as well as in all the context menus. The only way I know that I could get the commands removed from the context menus, is to have some hidden config setting that gets enabled/disabled in this case, and have all the menus conditional on it. But that doesn't help with the command palette.

Is there another (better) way to get this to work for the menus and/or the command palette?

**Comment by jrieken** [comment]
With https://github.com/Microsoft/vscode/issues/19345#issuecomment-277953793 we added the ability to show a command only in some cases

**Comment by eamodio** [comment]
@jrieken that sounds great -- but is there another way to use `when` that isn't something built-in or configuration setting? For example just a flag or something on the extension itself? I'd rather not have to set a "transient" configuration setting to signal commands on and off

**Comment by jrieken** [comment]
Yeah, we have an half-official command that lets you set custom context keys but it needs some doc. I'll make we have proper docs when this happens

**Comment by eamodio** [comment]
Great! FYI -- I'll be happy with only half-official docs too ;)

**Comment by jrieken** [comment]
:-) there is the [`setContext`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/contextkey/browser/contextKeyService.ts#L307)-command. So from an extension you should be able to do this: `vscode.command.executeCommand('setContex', 'myExtKey', true)`

**Comment by eamodio** [comment]
@jrieken that changes everything! ;) Thank you!

**Comment by jrieken** [comment]
Glad you like it. We have a request to APIify the context keys et al but this will work for now

**Comment by DanTup** [comment]
@jrieken Is there any example of this? I'm not sure how to make it work? I can set a context at startup but can I add `when` to the `commands` in `packages.json`? Should this work in insiders? Thanks!

**Comment by eamodio** [comment]
@DanTup You can see an example of this [here](https://github.com/eamodio/vscode-gitlens/blob/master/src/extension.ts#L57) and [here](https://github.com/eamodio/vscode-gitlens/blob/master/package.json#L449). Seems to work in both stable and insiders. I have also added the new `commandPalette` support in insiders [here](https://github.com/eamodio/vscode-gitlens/blob/master/package.json#L392).

Hope that helps -- if not let me know.

**Comment by DanTup** [comment]
Yeah I spotted the typo (also `s` missing from `commands`!) but it didn't work - looking at your code it seems I was putting it in the wrong place (in command definitions). I'll give it another go when next working on this - thanks! 👍

**Comment by DanTup** [comment]
@eamodio @jrieken Sorry to be a pain, but I still can't make this work :( Here's the changes I've made - I've added `when`'s to my `packages.json` and some `setContext` calls, but the commands always still appear. Eg. I hit `F5` to load the extension host and *do not* have a Dart project open but the commands are still listed in the command palette.

![Changes](https://cloud.githubusercontent.com/assets/1078012/26025452/023563d2-37e0-11e7-8e29-bb141f14fdde.png)

![Testing](https://cloud.githubusercontent.com/assets/1078012/26025455/07d47724-37e0-11e7-9408-ee0b903ff33a.png)

**Comment by DanTup** [comment]
lol, I should've re-read my last comment here before coming back to this. I did the exact thing that hadn't worked last time (put them in command defs)!

**Comment by DanTup** [comment]
ok, so I should've re-read my previous comment - I did the same thing (put in command definitions). However, even if I add them to the menus parts they won't work.

Unfortunately the samples linked above don't match up now because they weren't linked to specific versions and the code has all moved around. Any pointers appreciated!

![Still stuck!](https://cloud.githubusercontent.com/assets/1078012/26025482/bcafed86-37e0-11e7-834d-78da9ad459ba.png)

**Comment by DanTup** [comment]
Ok, sorted this out - I was missing the `commandPalette` section! :-)

**Comment by jrieken** [comment]
Yeah, closing this issue because we have the `commandPalette` section and context keys. A sample is here: https://code.visualstudio.com/updates/v1_10#_context-specific-visibility-of-command-palette-menu-items
