### ISSUE TITLE
can not search all

### ISSUE THREAD

**Issue by zzlu1004** [microsoft/vscode#104037]
Issue Type: <b>Bug</b>

when I search all,zhe result is opened file.I don't know if it's a configuration problem.I can't find out some configuration .Re installation still doesn't work

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (6.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.48.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Looks like you are launching [Search Editor](https://code.visualstudio.com/updates/v1_43#_search-editors) instead of "Find in files"

How do you launch search? Does "Editor > Find in Files" have same results?

**Comment by zzlu1004** [comment]
![image](https://user-images.githubusercontent.com/30038200/89399525-32031700-d745-11ea-901b-f1246862cc95.png)
Like this, the search results only show the contents of the open file in the edit bar. In fact, the function name also exists in other files. I try to right-click and search in the folder; the same effect

**Comment by zzlu1004** [comment]
![image](https://user-images.githubusercontent.com/30038200/89400431-78a54100-d746-11ea-8599-bded13b62758.png)
this is my setting.json

**Comment by zzlu1004** [comment]
> / needsMoreInfo
> 
> 似乎您正在启动[搜索编辑器，](https://code.visualstudio.com/updates/v1_43#_search-editors)而不是“查找文件”
> 
> 您如何启动搜索？“编辑器>在文件中查找”是否有相同的结果？
![image](https://user-images.githubusercontent.com/30038200/89400589-b013ed80-d746-11ea-87e2-cacce8316dea.png)
![image](https://user-images.githubusercontent.com/30038200/89400600-b4d8a180-d746-11ea-9e49-87750b651a5e.png)
Like this, the search results only show the contents of the open file in the edit bar. In fact, the function name also exists in other files. I try to right-click and search in the folder; the same effect

**Comment by IllusionMH** [comment]
@zzlu1004 is it expected to be closed?
