### ISSUE TITLE
Extensions have made changes to this terminal's environment

### ISSUE THREAD

**Issue by gabrielf7** [microsoft/vscode#104022]
- VSCode Version: VSCodeUserSetup-x64-1.47.3
- OS Version: Windows 8.1

Steps to Reproduce:

I tried these issues, but to no avail:  #96250  #96740 #96574  #46696

1. When I go to the Visual Studio Code integrated terminal it happens that it doesn't start up correctly, looking like this:
<img src="https://github.com/gabrielf7/studies-git/blob/master/err-1.png" >

2. And it is remarkable that there is a warning in the right corner, but I don't know how to proceed, this appears:
Extensions have made changes to this terminal's environment
VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-c671050bca-sock
GIT_ASKPASS=c:\Users\{name.use}\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh
VSCODE_GIT_ASKPASS_NODE=C:\Users\{name.use}\AppData\Local\Programs\Microsoft VS Code\Code.exe
VSCODE_GIT_ASKPASS_MAIN=c:\Users\{name.use}\AppData\Local\Programs\Microsoft VS Code\resources\app\extension
\git\dist\askpass-main.js

And informs that it is related to the Git that is working normally, I don't know if I need to quit Git to solve this. Visual Studio Code has already uninstalled and installed again and I couldn't fix it.

Does this issue occur when all extensions are disabled?: Yes

"Also please test using the latest insiders build to make sure your issue has not already been fixed: https://code.visualstudio.com/insiders/"
The Insiders of 1.48.0 worked the integrated terminal again, with the warning ⚠ Extensions want to make the following changes to the terminal's environment: with the same previous bug.

Link: https://code.visualstudio.com/insiders/
File: VSCodeUserSetup-x64-1.48.0-insider.exe

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/102727

It's not clear at the moment but all you need to do is to either ignore it or relaunch the terminal using the button. If you relaunch, VS Code will be able to authenticate when you use git in the terminal.
