### ISSUE TITLE
Blazor template impossible to get up and running

### ISSUE THREAD

**Issue by jagdriver** [microsoft/vscode#104011]
Issue Type: <b>Bug</b>

I use VS Code, and would like to use  Blazor Webassembly, so i downloaded the latest Framework (I am developing on a Mac) and created a solution. My intention are to make a client that's calling a backend API. I succeeded in calling the API, but the response did not contain the http headers from my API. With Postman the headers are all there. So I tried borrowing a Windows 10 PC and generating the solution, but to my supprise, the solution would not build, something with missing *.json files. Ok, Then I tried using Visual Studio 2019 community, and created the solution from the default template, but it actually got worse, nothing seem to work. now i ask for an explanation, Is this a new standard from Microsoft, I have developed c++/c# solutions for 30 years, and never seen the like, are Blazor a hobby project or something that Microsoft want the community to take serius? / Niels   

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G840 @ 2.80GHz (2 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.83GB (0.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-npm-script|eg2|0.3.13
vscode-npm|fkn|3.3.0
csharpextensions|jch|1.3.1
csharp|ms-|1.22.1
cpptools|ms-|0.29.0
qub-msbuild|qub|0.6.3
arduino-snippets|ron|1.0.2
vscode-arduino|vsc|0.3.1

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
