### ISSUE TITLE
View is not visible when contributed to built in container and doc is not helpful

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#104065]
Testing #103833

<img width="723" alt="image" src="https://user-images.githubusercontent.com/10746682/89418972-15f57a80-d731-11ea-8b07-5248b22762fe.png">

I think it would be helpful if we elaborate that views contributed to built in containers (explorer, scm , debug) are collapsed by default if visible ?

**Comment by alexr00** [comment]
New text will be: "The default initial state for the view. In most containers, the view will be expanded, however; some built-in containers (explorer, scm, and debug), show all contributed views collapsed regardless of the `visibility`.
