### ISSUE TITLE
\n replace with \n not recognized when regex replace 

### ISSUE THREAD

**Issue by sheldonhull** [Microsoft/vscode#10402]
- VSCode Version:  1.5.0-insider
- Date: 2016-08-08
- OS Version: Windows 10

Steps to Reproduce:

1.  Put in the following text
`Fashion axe organic man bun you probably haven't heard of them.\nUllamco next level tofu kitsch skateboard. \nId  helvetica kinfolk synth, flexitarian viral aliquip proident chicharrones nihil sriracha.\nShabby chic man bun beard, labore cred everyday carry adipisicing meditation sint  dolor  single-origin coffee.\nPork belly ullamco swag, pug twee delectus nihil.`

2. Control+H  to enter replace dialogue. 
3. Enable regex replace
4. Type `\n` as the regex match
5. Enter replacement text as `\n` to enter lines breaks
Result: Nothing happens. 

Expected result: 
```
Fashion axe organic man bun you probably haven't heard of them.
Ullamco next level tofu kitsch skateboard. 
Id  helvetica kinfolk synth, flexitarian viral aliquip proident chicharrones nihil sriracha.
Shabby chic man bun beard, labore cred everyday carry adipisicing meditation sint  dolor  single-origin coffee.
Pork belly ullamco swag, pug twee delectus nihil.
```

Allow the \n match to be replaced by actual line breaks. This reproduces behavior consistent with other text editors such as Sublime. 

To currently get it to work you have to double escape like this `\\n`

**Comment by wallverb** [comment]
Hmm, vscode works the same as Sublime in this case. If you use regexp expression search you need to follow regexp rules - Nothing happens in your Step 5 - because nothing is matched (you do not have new lines in your text)

**Comment by sheldonhull** [comment]
I'm sorry, brain was fried. Good point. Matching literal \n is totally different than matching \n new line. Chalk it up to a day of PowerShell troubleshooting :-)
