### ISSUE TITLE
Selected text in high contrast mode is not readable in Edge browser

### ISSUE THREAD

**Issue by jayspadie** [Microsoft/vscode#10405]
When in high contrast mode using Edge, selected text remains white with the selected white background making it unreadable.

Here is selected text in Chrome:
![image](https://cloud.githubusercontent.com/assets/5246869/17567885/35ea8752-5f0f-11e6-86a3-2df390b25a89.png)

And here is the same selected text in Edge:
![image](https://cloud.githubusercontent.com/assets/5246869/17568024/cb25b5da-5f0f-11e6-9f24-3cf2ba5a893a.png)

**Comment by jrieken** [comment]
This issue was moved to Microsoft/monaco-editor#105
