### ISSUE TITLE
Comment not working on vsCode last version

### ISSUE THREAD

**Issue by anasidrissi** [microsoft/vscode#104071]
the issue : 
when clicking ctrl + k + c i got this kind of comment even if vscode treat it as comment i get errors since i work with angular

`{# <div>
        <p>hello github</p>
    </div> #}`

notice i recognized that html files has a weird icon that i didn't recognize
my first tought was that vscode treat html files as a template like (twig)

notice 2 :  emmet not working also

![image](https://user-images.githubusercontent.com/11528819/89421208-a335d080-d72b-11ea-9083-91527f63ced8.png)

**Comment by aeschli** [comment]
What is the editor language for your file (status bar lower right corner). Can you verify it is `html`?
If it is `html`, maybe there's an extension that redefines the html comment tokens? Can you run with extensions disabled?
