### ISSUE TITLE
Layout breaks on next execution after clearing a collapsed cell output

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104119]
Testing #103887

https://memes.peet.io/img/5c0e7a36-5559-47ba-b346-b6b9d7c32231.mp4

1. Execute a cell
1. Collapse its output
1. Clear it
1. Execute it again 🐛

**Comment by connor4312** [comment]
This also appears to happen when I run a cell when its output is collapsed; seems like one part of VS Code remembers the output should be collapsed, and another part forgets

<img width="694" alt="image" src="https://user-images.githubusercontent.com/2230985/89464478-68309e80-d725-11ea-901e-a1080ae9b882.png">

**Comment by roblourens** [comment]
We will still render outputs when the output is collapsed. Let's discuss this later @rebornix there are a couple options but also I see that `createInset` is async and I think there will be trouble if `hideInset` can ever be called in the middle of that, not sure what is safe

**Comment by rebornix** [comment]
Similar bug https://github.com/microsoft/vscode/issues/104110 , which we somehow displays the output even if the cell is hidden. We need a better APIs in BacklayerWebview.

**Comment by connor4312** [comment]
I'm happy to help. I will want to be touching that area a lot when pure renderers are finalized.

Maybe the most reliable way to do things (i.e. make the BacklayerWebview API hard to misuse) is having all inset and other mutations be synchronous, and use those to maintain an internal state which the UI will update to reflect. Sort of the redux/kubernetes model. Having things be async and requiring consumers to enqueue or lock around calls leaks complexity.

**Comment by connor4312** [comment]
Looks like this is fixed now
