### ISSUE TITLE
Clickable area to expand should go across entire cell

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104114]
Testing #103887

I feels like I should not have to click on the icon exactly, but instead the area to rexpand should cover the entire horizontal area of the cell.

**Comment by roblourens** [comment]
I dunno, it seems more likely that someone would click it on accident. I wouldn't want to do that without some hover feedback or something, big empty areas should not be active.

**Comment by rebornix** [comment]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/876920/89566384-f7e15600-d7d4-11ea-80fb-eb9ebc9ee69b.png">

The border made me think it's clickable/actionable.

**Comment by misolori** [comment]
Agreed that we'd need some type of hover feedback. Depending on what we do in #104115, this could be solved by using an alternate treatment for collapsed cell.

**Comment by misolori** [comment]
We've updated the collapse state since this original issue and think it's been solved now:

<img width="366" alt="CleanShot 2021-10-04 at 16 03 57@2x" src="https://user-images.githubusercontent.com/35271042/135936067-76296f32-480b-4a57-9f14-617ec0f4796a.png">
