### ISSUE TITLE
SCM: Bring back SCM Providers view

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#104151]
From #102118

Let's bring back the SCM Providers view:

- It should look and feel the same as before
- Its selection should reflect the visibility of the repositories in the SCM View, instead of messing around with view panes

This will make it easier to manage many repositories.

**Comment by joaomoreno** [comment]
**Good news**

![recording (18)](https://user-images.githubusercontent.com/22350/89913517-19d34200-dbf4-11ea-8890-4cc4cc6a9fe1.gif)

- The `Source Control Repositories` view is now back (it used to be called `Source Control Providers`. It lets you control visibility of multiple repos in the `Source Control` view.
- The setting `scm.repositories.visible` is now back (it used to be called `scm.providers.visible`).
- I've sprinkled visibility actions both in the context menu of the `Source Control` view as well as the `...` menu, to make it easier to control the visibility without using the `Source Control Repositories` view.
- This will all be available in the next Insiders, hopefully this week.

**Bad news**

I'm out on vacation until the end of the month so no more work will happen this month here apart from critical bugfixing. Here's the state for now:

- The workbench opens the exact same way as today. On any given workspace, one must make the `Source Control Repositories` view visible manually. Once visible in a workspace, it will remain visible. I expect this to change and make the view visible depending on (1) the stored visibility state or (2) the number of repositories.
- No repository visibility state is stored yet. On reload, they will all be loaded once again. I expect this to change to simply remember which repositories were visible since the last session, per workspace.

**Comment by bpasero** [comment]
Very cool, I think this solution is elegant, will selfhost on it and report back if I find issues.

**Comment by michaelhays** [comment]
Thank you for this!

There were a lot of (justifiably) critical comments on #102118, so I just wanted to reiterate our appreciation for listening and bringing this functionality back.

**Comment by joaomoreno** [comment]
@michaelhays Thanks for the kind words 🙏

**Comment by raschan** [comment]
Thank you, for bringing back the old View of the SCM panel, I really appreciate it 🙏 

I still have one detail, that is bothering me a lot: in the old view, all the options and extensions were only visible on the "Changes" pane, leaving the different repos looking clean. My major problem with new look was this clean space got cluttered, and sadly this change doesn't really solve that.

I'm not sure if it is doable, but if it is, could we please have it back that all the various options are:
a) selectable (so I can turn it off, if I don't need it)
b) only appear on the selected Source Controls and not in the Source Control Repositories section.

for reference, this is how it looks like for me:
![Screenshot 2020-09-18 at 16 26 38](https://user-images.githubusercontent.com/6605186/93609360-0cb42a80-f9cc-11ea-8c2a-d58b97e52d35.png)

Until this can happen (or confirmed that it is impossible), I'm gonna go back to 1.46, hopefully temporary.

**Comment by pd93** [comment]
My thanks to you too for allowing us to choose which view we use. I much prefer the old UI.

However, I agree with everything @raschan said. The Source Control Provider list is way too cluttered with all those icons. Combined with a long branch name this results in it hiding the name of repo which makes it even more confusing. It also stops me from being able to easily select the repos I want to see. I just end up clicking the branch name by accident every time which brings up the branch selection drop-down.

**Comment by astrowonk** [comment]
> My thanks to you too for allowing us to choose which view we use. I much prefer the old UI.
> 
> However, I agree with everything @raschan said. The Source Control Provider list is way too cluttered with all those icons. Combined with a long branch name this results in it hiding the name of repo which makes it even more confusing. It also stops me from being able to easily select the repos I want to see. I just end up clicking the branch name by accident every time which brings up the branch selection drop-down.

I also agree but this probably would be better to open as its own issue, @raschan, than to post here in this closed one.
