### ISSUE TITLE
c+o chord does not expand collapsed output

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104113]
Testing #103887

Video: https://memes.peet.io/img/9775ea1e-d7c1-48a8-9392-6dc706c05646.mp4

c+c works for input, though.

**Comment by connor4312** [comment]
I realized the "Expand Cell Output" context menu action also does nothing, probably the same root cause. I can only click on the collapsed icon to re-expand.

**Comment by roblourens** [comment]
derp
