### ISSUE TITLE
Give extension authors access to the Github Codespaces beta

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#104199]
We (the Julia extension) are now getting reports from users that use our extension with the Github Codespaces beta because they apparently are in. None of us, the core devs of the extension, are part of the beta, and it is tricky to help them with anything.

Could authors of popular extensions jump the queue and get added to the beta so that we can make sure everything works with our extension? In my case, it would just be the Github account here.

**Comment by IllusionMH** [comment]
I wonder if https://github.com/microsoft/vscode/wiki/How-to-Contribute#run can help here
> Web (Chromium, Firefox or Safari only)
>
> ```
> yarn web
> ```

**Comment by davidanthoff** [comment]
That is not related at all, I'd like to be part of the GitHub Codespaces beta, like some of our users already are.

**Comment by fiveisprime** [comment]
Sorry for the lack of movement, I'll pick this up this week and may be reaching out for more info to get you in.

**Comment by fiveisprime** [comment]
I reached out to the Codespaces team and they said your best bet is just to sign up here: https://github.com/features/codespaces
The demand to get in is high and they're letting people in as quickly as they can. I'll keep pushing, but it's not looking good.

In the meantime, the image that backs Codespaces is available [here](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/codespaces-linux) (warning, it's kind of gigantic) if you want to try to repro the issues without access. You might want to try to repro with a smaller, more basic container image first.

**Comment by RandomFractals** [comment]
yeah, that's unfortunate since many devs given access to github codespaces beta try most popular extensions when they get in & how would extension devs provide support for that without being added to that program first.

perhaps, githbu & codespaces teams need to recalibrate that beta access approach.

**Comment by davidanthoff** [comment]
I added myself to the beta request queue months ago, I think essentially on the first day it was possible, but haven't been able to get in yet...

I do think there should be some priority for folks that contribute popular extensions.

**Comment by RandomFractals** [comment]
I agree. I applied for it back in May I believe when it was first announced.

There certainly should be some higher priority set for those contributing to vscode ecosystem & popular 'twitter' devs just trying that github/codespaces integrations.

**Comment by RandomFractals** [comment]
here is an idea: I think github and code spaces integration teams should connect with vs marketplace team, get 1K of top downloaded extensions with publisher info, which is mostly our github handles & upload that list into their next github/codespaces beta access granted queue to send out.

should not be this hard.

**Comment by davidanthoff** [comment]
Ok, I just got in :) I guess because of the VS and GitHub Codespaces merge, which seems like great news also!

**Comment by RandomFractals** [comment]
@davidanthoff are you referring to this announcement?

https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/

That is great news!

**Comment by RandomFractals** [comment]
@fiveisprime also, not sure if this is the best place for it, but would be nice if vscode team provided a short tutorial & best practices guide on enabling vscode extensions for code spaces.

per my reads we need to mark our extensions as UI type in package.json & use new vscode.fs api for file access, but I am sure there is more to it.

@mattbierner & @eamodio are there any docs or vscode ext. examples you'd recommend for that vscode ext. update dev effort?

**Comment by davidanthoff** [comment]
Yes, I had a VS Online account for a while, and I believe everyone who had one of those accounts automatically got a GitHub Codespace account now?

**Comment by RandomFractals** [comment]
@davidanthoff that's great! some of us did not :(

also, @alefragnani kindly pointed me to this doc on marking extesions as workspace, not UI, as I originally mentioned from my memory of reading those updates ...

https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location

**Comment by RandomFractals** [comment]
more info on vscode.workspace.fs released back in vscode v1.37 to make fs work for extensions that support remote workspaces:

https://code.visualstudio.com/updates/v1_37?ref=codebldr#_vscodeworkspacefs

**Comment by RandomFractals** [comment]
+ all about that new github codespaces integration in one place for ext. devs to peruse :)

https://github.com/lynnlangit/learning-codespaces/blob/master/README.md

**Comment by fiveisprime** [comment]
I'm going to go ahead and close this. If any publishers still need access, let me know either here or through email and I'll make sure you get in.
