### ISSUE TITLE
Bottom border of collapsed cell looks messy

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104115]
Testing #103887

The extra border here looks rather messy:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/2230985/89462302-0c184b00-d722-11ea-97bd-dda71dda154b.png">

If we want to indicate there's folded content, maybe a light or dashed border aligned with the vertical centerline of the folded icon would look better?

**Comment by rebornix** [comment]
IMHO the bottom border for the collapsed outputs is not intuitive. I'm wondering if we can show a gray italic text "_collapsed outputs_" cc @misolori ?

**Comment by misolori** [comment]
We could either add a `...` in place:

<img width="400" src="https://user-images.githubusercontent.com/35271042/89584180-7dbeca80-d7f0-11ea-9afe-9574de1a2128.png">

Or add text:
<img width="400" src="https://user-images.githubusercontent.com/35271042/89584450-f2920480-d7f0-11ea-9c70-32cb5549fad7.png">

I think I like the simpler `...` approach and we can show a title tooltip when you hover over it

**Comment by roblourens** [comment]
If we have a `...` do we need the other expand codicon button? A `...` button is literally just Jupyter's solution. Not opposed to it though.

**Comment by misolori** [comment]
I would still keep our expand icon on the side, it’s more intuitive. The ... by itself is but vague. We also show the ... on folded regions in the editor And show the folded chevron on the side, so it aligns there.

**Comment by connor4312** [comment]
To me having the folded icon beside the `...` icon feels weird. We basically have two icons that do the same thing. I prefer the text version.

**Comment by misolori** [comment]
@connor4312 but isn't that the same behavior in editor though?

![image](https://user-images.githubusercontent.com/35271042/89588077-c6c64d00-d7f7-11ea-8898-0c4c146a1f8c.png)

**Comment by connor4312** [comment]
Yea, but in the editor the context is different -- the gutter shows me my blocks (which just happens to be collapsed in this instance) while the editor shows me the content, which it indicates is collapsed.

`...` to the middle I think would look nicer. Particularly if we decide to make the whole bar clickable. This is similar to what the Azure portal does extensively

![](https://memes.peet.io/img/20-08-771a1667-bb14-413c-9534-5362ee14c437.gif)

**Comment by misolori** [comment]
Oh I definitely like that. One thing we'd need to work around is how it looks when it's centered because of our add new cell buttons:

![image](https://user-images.githubusercontent.com/35271042/89588942-89fb5580-d7f9-11ea-9616-4197d8d656d6.png)

**Comment by misolori** [comment]
Collapsed cell has been updated:

<img width="366" alt="CleanShot 2021-10-04 at 16 03 57@2x" src="https://user-images.githubusercontent.com/35271042/135936130-432be6eb-1b4b-4de7-a009-e37f877d8792.png">
