### ISSUE TITLE
'Setting Sync: Open local backups folder' resulted in an error if run before sync is enabled

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#104121]
Issue Type: <b>Bug</b>

Testing #103604

**repro**
1. In a VS Code instance without setting sync enabled
1. From the command palette, run the `Setting Sync: Open local backups folder` command

**Bug**
This produces the error:

```
workbench.desktop.main.js:sourcemap:2988 Command 'Settings Sync: Open Local Backups Folder' resulted in an error (Unable to resolve non-existing file 'vscode-userdata:/Users/matb/projects/san/c/data/User/sync')
```

The command should likely not show up in the command palette until setting sync is enabled

VS Code version: Code - Insiders 1.48.0-insider (d13d2fc56da7a2f8bcad4256212db0661fcbba45, 2020-08-05T05:26:44.946Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.28GB free)|
|Process Argv|--user-data-dir=./c/data --extensions-dir=./c/extension|
|Screen Reader|no|
|VM|14%|
</details>

**Comment by sandy081** [comment]
It is not trivial to hide the command, instead following info is shown

<img width="467" alt="image" src="https://user-images.githubusercontent.com/10746682/89478158-7e734480-d78f-11ea-975c-c4875383e1f2.png">
