### ISSUE TITLE
Error running command workbench.actions.sync.editMachineName

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#104125]
Issue Type: <b>Bug</b>

Testing #103604

**Repro**
1. On two instances of VS Code (A and B) with setting sync enabled
1. Open the sync view on both
1. Now try renaming machines on A
1. Wait a moment. The B doesn't seem to sync the names (possibly a bug)
1. Now try renaming the machines on B

**Bug**
See the alert:

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2988 Error running command workbench.actions.sync.editMachineName:
POST request 'https://vscode-sync.trafficmanager.net/v1/resource/machines' failed because of Precondition Failed (412). There is new data exists for this resource. Make the request again with latest data.. This is likely caused by the extension that contributes workbench.actions.sync.editMachineName.
```

VS Code version: Code - Insiders 1.48.0-insider (d13d2fc56da7a2f8bcad4256212db0661fcbba45, 2020-08-05T05:26:44.946Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.71GB free)|
|Process Argv|--user-data-dir=./a/data --extension-dir=./a/extension|
|Screen Reader|no|
|VM|14%|
</details>

**Comment by sandy081** [comment]
> Wait a moment. The B doesn't seem to sync the names (possibly a bug)

There is no auto refresh because we do not have events from server. So you need to refresh manually.

I tried the steps and I am not getting this error. Am I missing some steps?

**Comment by mjbvz** [comment]
Nope, I can't repo this anymore either. Seems to have either been fixed in the client or server
