### ISSUE TITLE
Cell drag area very small

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#104164]
1. Have a notebook cell, for example my-work.github-issues
2. Try to drag the `My Bugs` section. Notice how the drag area is very very small 🐛 

Due to this it is very hard for users to discover that sections can be dragged and dropped, and it is very tedious to find the right location where I can start dragging.

**Comment by misolori** [comment]
Related to https://github.com/microsoft/vscode/issues/104104. One proposal is to make the entire markdown cell moveable.
