### ISSUE TITLE
skipFiles not working for the latest nightly build

### ISSUE THREAD

**Issue by queston02** [microsoft/vscode#104195]
- VSCode Version: 1.48.0-insider
- OS Version: MAC Catalina 10.15.6

Debugger is stepping into `<node_internals>/domain.js`, `<node_internals>/internal/_stream_writable.js`

Steps to Reproduce:

1. Create new launch.config with following value.
```
{
    "name": "Launch & Attach to App",
    "type": "pwa-node",
    "request": "launch",
    "runtimeExecutable": "sam",
    "runtimeArgs": [
        "local",
        "invoke",
        "-e",
        "${workspaceFolder}/event.json",
        "-n",
        "${workspaceFolder}/env-vars/local.json",
        "-d",
        "5858",
        "-t",
        "${workspaceFolder}/template.yaml",
        "HelloWorld",
        "--region",
        "us-west-2"
    ],
    "attachSimplePort": 5858,
    "localRoot": "${workspaceFolder}/",
    "remoteRoot": "/var/task",
    "stopOnEntry": false,
    "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "<node_internals>/**"
    ]
}
```
2. Run the debugger

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
If you use `"<node_internals>/**/*.js"` does it make a difference?

**Comment by queston02** [comment]
Nope. Tried that as well.

**Comment by connor4312** [comment]
Thanks for the issue, I applied what I believe to be a fix for the scenario you were hitting in the linked commit. If this doesn't fix it for you, please capture a trace log and send it over 🙂

**Comment by queston02** [comment]
Connor thanks for the fix. Should i take the latest nightly build now or tomorrow to test the fix?

**Comment by connor4312** [comment]
Tomorrow -- nightly publishes slightly after 5 PM PST each day

**Comment by connor4312** [comment]
@queston02 did this end up fixing the problem for you?

**Comment by queston02** [comment]
Nope. I just debugged my project and got the issue. I got the screen shot also but cannot attach it here. In screen shot you could see it going into domain.js file of node_internals. Below is my launch.config
```
{
    "type": "node",
    "request": "attach",
    "name": "Attach by Process ID",
    "processId": "${command:PickProcess}",
    "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "<node_internals>/**/*.js"    
    ]
}
```
Below is VS Code Insider details:-

Version: 1.49.0-insider
Commit: b6d4fec3714ff897f72c1dab8cc02b7421a8f131
Date: 2020-09-01T05:48:29.841Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by connor4312** [comment]
Can you grab a fresh set of logs using the recent debug adapter?

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by queston02** [comment]
Emailed you the trace file. Also what is the difference between ```type="node"``` and ```type="pwa-node"```? Are they the same debugger or different debugger?

**Comment by hellorayza** [comment]
```
```

**Comment by hellorayza** [comment]
debug express with es6,
`skipfile` not work
```
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by connor4312** [comment]
@queston02 in the log file you sent, it seems that you are not using the nightly build. You'll need to do so in order to get the fix.

@hellorayza please try the nightly build that contains this fix. If it doesn't work for you, collect a log file using the instructions above.

**Comment by queston02** [comment]
I can confirm now that the latest nightly build is skipping the files in `node_modules` while debugging i.e. when I do F11 it doesn’t step into the method that is defined in `node_modules` but issue remains with `<node_internals>`. I can consistently reproduce it. Emailed you the latest trace file.

**Comment by connor4312** [comment]
Thanks for the logs. I cannot repro on my machine but I found a race condition that I think you are hitting.

Please try the next nightly build of the debugger itself and let me know if it works better for you (you're on VS Code Insiders, but the debugger has its own nightly 🙂). Directions: https://github.com/microsoft/vscode-js-debug#nightly-extension

**Comment by queston02** [comment]
As suggested by you I got the latest nightly build for the debugger. I am still getting the issue in my company’s project where the debugger is stepping into `<node_internals>` methods. I even created separate project to try to reproduce the issue but couldn’t. As far as  `node_modules` is concerned debugger is skipping it  so we are good for that. I have emailed you the latest trace file in case you try to investigate further.

**Comment by connor4312** [comment]
\closedWith 12c36762037937a25decc05d8113390408983630

**Comment by nodorious** [comment]
hi connor - 

i'm experiencing this issue now (skipfiles not respecting node_internals exception). 

i just tried enabling skipfiles for the first time, and noticed the problem. 

if you have a potential fix available i'd like to try it (caveats understood). 

thank you...

**Comment by nodorious** [comment]
i just tried the insiders build and i can confirm that for the it resolves the problem that i am also having with v1.49.2 (skipfiles ignores exception for node_internals when entered per the documentation). thank you...

**Comment by connor4312** [comment]
Ok, thanks for confirming. I haven't heard back from the original poster, so I will mark this as verified for this release.

**Comment by nodorious** [comment]
ok, i did find a problem. using the insiders edition does resolve the problem above, as reported, when debugging remotely. 

but i am now having a problem using the insiders edition when debugging the same code locally. i am syncing settings between my ms code versions, and i am using the same launch.json file in both cases. 

i have two local debugging scenarios... with "runtimeExecutable": "nodemon" and without. 

in the insiders edition, when i try debug locally without nodemon ms code does launch node successfully and i can debug, but when i stop the debugger node exits with code 1.

in the insiders edition when i try to debug locally with nodemon ms code fails to launch node successfully. 

launch command from v1.49.2 of ms code (which works): 
PS C:\work\antibsmachine>  cd 'c:\work\antibsmachine'; ${env:NODE_OPTIONS}='--require "c:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" --inspect-publish-uid=http'; ${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.1924-2.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\jotha\\AppData\\Local\\Temp\\node-debug-callback-a6c5abf2e86c1fb1"}'; & 'C:\Users\jotha\AppData\Roaming\npm\nodemon.cmd' '.\start.js' 
 
launch command from insiders edition (which fails): 
PS C:\work\antibsmachine> /Microsoft VS Code Insiders/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" --inspect-publish-uid=http'; ${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.31152-5.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\jotha\\AppData\\Local\\Temp\\node-debug-callback-19b3ff13082ce317"}'; & 'C:\Users\jotha\AppData\Roaming\npm\nodemon.cmd' '.\start.js'

the second one is missing:
cd 'c:\work\antibsmachine'; ${env:NODE_OPTIONS}='--require "c:/Program Files

relevant part of my launch.json

      {
          "name": "local debug",
          "type": "node",
          "request": "launch",
          "program": "${workspaceFolder}\\start.js",
          "skipFiles": [
            "${workspaceFolder}/node_modules/**/*.js",
            "<node_internals>/**/*.js"
          ]
        },

      {
          "name": "local debug w/nodemon",
          "type": "node",
          "request": "launch",
          "runtimeExecutable": "nodemon",
          "program": "${workspaceFolder}\\start.js",
          "restart": true,
          "console": "integratedTerminal",
          "internalConsoleOptions": "neverOpen",
          "skipFiles": [
            "${workspaceFolder}/node_modules/**/*.js",
            "<node_internals>/**/*.js"
          ]
        },

i'm happy to provide more details if you need please just let me know. thank you...

**Comment by connor4312** [comment]
@nodorious can you create a new issue for that?
