### ISSUE TITLE
Cell "run" button goes missing if execution completes for a collapsed cell

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104117]
Testing #103887

https://memes.peet.io/img/f4ca4cf1-7cb4-4cd6-ae84-59d49f6871d5.mp4

1. Execute a cell
1. Before output is shown, collapse it
1. Expand the cell after output is visible
1. The run button is gone 🐛 
1. Make any change to the cell input, the run button re-appears

**Comment by roblourens** [comment]
Whoa, good catch
