### ISSUE TITLE
Readonly notebooks allow copying and pasting of cells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#104176]
- VSCode Version: 1.48.0-insider
- OS Version: Darwin x64 19.6.0
Commit: cfbd1999769f4f08dce29629fb92fdc0fac53829
Date: 2020-08-06T05:40:40.871Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

Steps to Reproduce:

1.Open a Notebook
2.Ensure the notebook is not editable (notebook and cells all have editable metadata set to false)
3. Cells cannot be added, deleted, edited
4. Copy and cell and paste (it will now insert a new cell below the copied cell)

Found that following three keyboard shortcuts result in notebook being edited:
* Cut
* Copy + Paste
* Undo

@rebornix /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sbatten** [comment]
@rebornix still able to copy cells from the toolbar and paste them with command palette or ctrl+shift+v
