### ISSUE TITLE
workbench.action.quickOpen opens file in existing tab instead of creating a new tab

### ISSUE THREAD

**Issue by rmartinez-ellation** [Microsoft/vscode#10417]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Make these your keyboard shortcuts and save:
// Place your key bindings in this file to overwrite the defaults
[
    { "key": "alt+shift+s",          "command": "workbench.action.gotoSymbol" },
    { "key": "alt+g",                   "command": "editor.action.goToDeclaration",
                                     "when": "editorTextFocus" },
    { "key": "alt+shift+f",             "command": "editor.action.referenceSearch.trigger",
                                     "when": "editorTextFocus" },
    { "key": "alt+o",                "command": "workbench.action.quickOpen" },
    { "key": "alt+shift+o",                "command": "workbench.action.quickOpen" },
    { "key": "f7",          "command": "workbench.action.tasks.build" },
    { "key": "ctrl+k ctrl+d", "command": "editor.action.format" }
]

2. Open a project folder.

3. Navigate to a file.

4.  Press keyboard shortcut "alt+shift+o" to trigger workbench.action.quickOpen

5. Type in a file name.

Result:
File opens in the existing tab.

Expected:
File opens in a new tab.

**Comment by bpasero** [comment]
`"workbench.editor.enablePreviewFromQuickOpen": false`
