### ISSUE TITLE
Use Markdown newline logic when displaying JSDOC info onhover

### ISSUE THREAD

**Issue by christiantjl** [microsoft/vscode#104188]
# Description
Currently, single newlines in JSDOC comments are parsed as newlines when you hover over a relevant identifier, but IMO they should be parsed like Markdown, where it takes two newlines to actually cause a line break.

# Visual example
```javascript
/**
 * ❌ This is a description that spans multiple lines, but it should only
 * compile to a single line when rendered.
 *
 * ✅ This should be a new paragraph, since it's preceded by *two* newlines.
 */
```
![image](https://user-images.githubusercontent.com/1657236/89564102-1ef25480-d7e2-11ea-8d79-b430d2c959e2.png)

**Comment by mjbvz** [comment]
Can you explain the problem in more detail. It looks to me like your example shows the correct behavior

**Comment by christiantjl** [comment]
@mjbvz The first time I thought I noticed this, it must've been a line break coincidentally where the single newline was - you're right lol, the example I posted clearly shows it's working as expected. Sorry about that 😅
