### ISSUE TITLE
debugger sidebar data presentation

### ISSUE THREAD

**Issue by bobmagicii** [Microsoft/vscode#10418]
this is how the PHP Debug extension is presenting output - it is the only one i have used so i do not know if this is common.

![screen shot 2016-08-10 at 7 45 03 pm](https://cloud.githubusercontent.com/assets/881944/17575926/6582d7a2-5f33-11e6-9370-b0c2af684c9a.png)

is there a better way to view this than waiting 3 seconds for the hover tooltip (which sometimes doesn't happen), like line wrapping that sidebar section, or being able to redock that section to be under the code editor similar to the integrated terminal, or some such thing.

to be honest, it would probably still need line wrapping even if redocked. those messages are long and the information needed is generally over half way in.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/1128
