### ISSUE TITLE
Trailing commas in bundled Javascript snippets break JSON parsing

### ISSUE THREAD

**Issue by abulka** [microsoft/vscode#104141]
Issue Type: <b>Bug</b>

The bundled Javascript snippets e.g. 
`/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/javascript/snippets/javascript.code-snippets`
have a couple of trailing commas which breaks official JSON parsing. Seems to have been introduced recently.

```json
	"Log warning to console": {
		"prefix": "warn",
		"body": [
			"console.warn($1);",        <--- note erroneous trailing comma
		],
		"description": "Log warning to the console"
	},
	"Log error to console": {
		"prefix": "error",
		"body": [
			"console.error($1);",        <--- note erroneous trailing comma
		],
		"description": "Log error to the console"
	}
```

late 2019 the same JSON was correct:

```json
	"Log warning to console": {
		"prefix": "warn",
		"body": [
			"console.warn($1);",
			"$0"
		],
		"description": "Log warning to the console"
	},
	"Log error to console": {
		"prefix": "error",
		"body": [
			"console.error($1);",
			"$0"
		],
		"description": "Log error to the console"
	}
```

@MrNossiom your commit fc8b56a966b2df75676158ea4e6b9477d2d033a8 removed the `"$0"` from the snippet and left a couple of trailing commas, making the JSON not parse using libraries like `jsonc.parse`. Luckily this does not affect normal vscode snippet insertion operations - vscode must use a more resilient parser.

The fix is to remove the two trailing commas, which turns the file into standard JSON again.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|32.00GB (1.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
vscode-browser-preview|auc|0.6.7
django-snippets|bib|1.1.1
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.13.2
flutter|Dar|3.13.2
vscode-eslint|dba|2.1.8
gc-excelviewer|Gra|3.0.39
todo-tree|Gru|0.0.178
plantuml|jeb|2.13.12
vscode-position|jtr|1.0.1
Kotlin|mat|1.7.1
python|ms-|2020.7.96456
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.29.0
vscode-typescript-tslint-plugin|ms-|1.2.3
awesome-flutter-snippets|Nas|2.0.4
vscode-code-outline|pat|0.2.1
mathpad|sag|0.0.2
rewrap|stk|1.13.0
html-preview-vscode|tht|0.2.5
snippet-creator|vin|1.1.0
codetour|vsl|0.0.34
viml|Xad|1.0.0

</details>

**Comment by MrNossiom** [comment]
Ok I fix it... Thanks
