### ISSUE TITLE
Two extra colons added when pressing tab or enter, when completing a CSS pseudo-selector

### ISSUE THREAD

**Issue by Dean-NC** [microsoft/vscode#104111]
- VSCode Version: 1.47.3
- OS Version: Windows x64 10.0.18363

Steps to Reproduce:

1. Similar steps as with issue #30176. For CSS in <style> tag in .html (haven't tested .css file), type any selector, example: div, then type 2 colons.  Intellisense may/may not show _::before_ as a hilighted suggestion.  If it does, press the tab or enter key, and you'll end-up with 4 colons.

2. If intellisense does not show _::before_ as a higlighted suggestion, type "be", so that you have "div::be" typed so far.  Intellisense should be showing _::before_ as a highlited suggestion. Press the tab or enter key, and you'll end-up with 4 colons.

![Untitled](https://user-images.githubusercontent.com/12361341/89460961-2c073900-d739-11ea-8e73-06c5bc8cfbca.png)

It seems the coders only tested typing a single colon when testing intellisense and auto-completion.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Sorry, you have to provide more detailed steps, I'm not able to reproduce.

![Peek 2020-08-12 15-52](https://user-images.githubusercontent.com/6461412/90023651-42227580-dcb4-11ea-8175-cd12b80398b9.gif)

**Comment by Dean-NC** [comment]
Here's 2 of the same demo files (small, stripped-down), 1 that works correctly and 1 that doesn't. The cause  seems to be a combination of the preceding style rule and the following comment and style rule.

[Demo files.zip](https://github.com/microsoft/vscode/files/5069774/Demo.files.zip)

![ExtraColons](https://user-images.githubusercontent.com/12361341/90150770-fde6b200-dd53-11ea-897f-0c76ed70861a.gif)
