### ISSUE TITLE
Go back should remember line / column

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10412]
- VSCode Version: Code - Insiders 1.5.0-insider (666ed83a2d465257201cdac215a553ddee3cccbe, 2016-08-10T09:04:04.509Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Go to some line/column (eg. `10:30`)
2. Press `Cmd + Up`
3. Press `Cmd + Shift + Enter` to enter new line above (eg. to put new import)
4. Press `Ctrl + -` to go back to location you were editing

Cursor will jump to line number `10` and most likely column `1` (if this happens to be empty line)

Ideally if it would jump to line `11:30` so you can continue typing whatever you were typing

Sublime handles it pretty good (will go to exact location that cursor was - code wise - not line number wise)

Use case is similar to: https://github.com/Microsoft/vscode/issues/10409

**Comment by bpasero** [comment]
The navigation history is currently hardcoded to 5 lines but we have an issue to make this configurable. Closing as duplicate.
