### ISSUE TITLE
Keyboard shortcut to dismiss notificaitons

### ISSUE THREAD

**Issue by DeeTrueSnyder** [microsoft/vscode#104198]
Users should be able to quickly dismiss the most recent notification popup using a keyboard shortcut so they don't have to take their hands off the keyboard in order to acknowledge and dismiss incoming notifications. 

Users should be able to quickly clear all notification popups using a keyboard shortcut so they don't have to take their hands off the keyboard in order to acknowledge and dismiss incoming notifications.

**Comment by IllusionMH** [comment]
Have you checked existing actions available for notifications?
![image](https://user-images.githubusercontent.com/1312662/89579807-13804700-d83d-11ea-9c7a-19788ea9e1a0.png)

You can easily add convenient shortcut for you (or tune condition on existing)
https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_customize-your-keyboard-shortcuts

**Comment by DeeTrueSnyder** [comment]
Did not know this was a thing. Thank you!
