### ISSUE TITLE
Open current file in new window doesn't appear to allow editing in WSL mode

### ISSUE THREAD

**Issue by addshore** [microsoft/vscode#104175]
Issue Type: <b>Bug</b>

I have a project loaded using vscode on Windows, where the project is in WSL and thus vscode is in its WSL remote mode.

I select the "Open Active file in New Window" option and a new window opens and appears to have the file open.

If I make a change to the file and try to save the file it reverts to its origional state.
I can only imagine this has something to do with WSL integration.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

**Comment by aeschli** [comment]
I'm not able to reproduce. Anything special about the file? Generated or write protected?

**Comment by addshore** [comment]
Seems to be working just fine for me now, and seemingly on the exact same version.

```
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

> I'm not able to reproduce. Anything special about the file? Generated or write protected?

Nope, they were not generated or write-protected files.
I'll keep an eye out and try to investigate further if it happens more.
