### ISSUE TITLE
String which contains double slash is highlited as a comment

### ISSUE THREAD

**Issue by mikhail-yurin** [microsoft/vscode#104152]
Just add a line of code:
```const myvar = `.//*[text()="${nodeName}"]/../..//*[text()="Deleted"]`;```

everything after "//" is highlighted like a comment
![image](https://user-images.githubusercontent.com/18097686/89503408-28be8c80-d7cf-11ea-849d-e9323b09f642.png)

<details><summary>Installed extensions</summary>
Extension | Author (truncated) | Version
-- | -- | --
better-comments | aar | 2.1.0
html-snippets | abu | 0.2.1
vscode-javascript-snippet-pack | aka | 0.1.6
MochaSnippets | Ala | 0.0.1
Bookmarks | ale | 11.3.1
project-manager | ale | 11.1.0
vscode-color | ans | 0.4.5
flutter-internationalize | api | 0.1.5
vscode-node-readme | ben | 3.0.2
path-intellisense | chr | 2.2.1
gitignore | cod | 0.6.0
dakara-foldplus | dak | 1.4.0
dart-code | Dar | 3.13.2
flutter | Dar | 3.13.2
vscode-eslint | dba | 2.1.8
bazel-code | Dev | 0.1.9
git-extension-pack | don | 0.1.3
githistory | don | 0.6.9
xml | Dot | 2.5.1
eslint-disable-snippets | drK | 1.2.0
es7-react-js-snippets | dsz | 2.8.2
gitlens | eam | 10.2.2
vscode-html-css | ecm | 0.2.3
vscode-npm-script | eg2 | 0.3.13
json-tools | eri | 1.0.2
prettier-vscode | esb | 5.1.3
vs-code-xml-format | fab | 0.1.5
vscode-diff | fab | 1.4.0
vscode-todo-plus | fab | 4.17.1
flutter-mobx | Flu | 0.0.6
vscode-test-explorer | hbe | 2.19.1
stylelint-disable-snippets | hed | 1.0.3
beautify | Hoo | 1.5.0
git-last-commit-message | Jan | 1.9.0
docthis | joe | 0.7.1
vscode-styled-components | jpo | 0.0.29
google-search | kam | 0.0.1
node-module-intellisense | lei | 1.5.0
browser-debugger-extension-pack | mag | 1.0.0
rainbow-csv | mec | 1.7.1
dotenv | mik | 1.0.1
ecdc | mit | 1.3.0
vscode-scss | mrm | 0.9.0
vscode-docker | ms- | 1.4.1
python | ms- | 2020.7.96456
vscode-typescript-tslint-plugin | ms- | 1.2.3
gradle-language | nac | 0.2.3
react-proptypes-intellisense | OfH | 1.0.3
convert-css-in-js | pau | 1.1.3
material-icon-theme | PKi | 4.2.0
vscode-graphql | Pri | 0.2.14
subtle-brackets | raf | 3.0.0
startanyshell | rem | 0.3.1
highlight-words | rsb | 0.1.4
partial-diff | ryu | 1.4.1
color-stamp | s3a | 1.0.0
bash-beautify | sha | 0.1.1
code-settings-sync | Sha | 3.4.3
vscode-scss-formatter | sib | 2.0.1
git-prefix | srm | 1.2.0
vscode-stylelint | sty | 0.84.0
sass-indented | syl | 1.8.9
open-in-browser | tec | 2.0.0
json2yaml | tux | 0.2.0
errorlens | use | 3.1.1
tensorflow-snippets | vah | 0.3.3
open-in-web | VCa | 1.0.1
highlight-matching-tag | vin | 0.9.9
vscode-jss-snippets | vis | 0.2.2
gitblame | wad | 4.2.0
vscode-todo-highlight | way | 1.0.4
JavaScriptSnippets | xab | 1.8.0
local-history | xyz | 1.8.1
markdown-all-in-one | yzh | 3.2.0
propertylist | zho | 0.0.2
vscode-open-in-github | ziy | 1.3.6
</details>

<details><summary>System info</summary>
CPUs | Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 4000)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: disabled_softwareskia_renderer: disabled_off_okvideo_decode: unavailable_offviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 0, 1, 1
Memory (System) | 15.49GB (2.08GB free)
Process Argv | --no-sandbox --unity-launch
Screen Reader | no
VM | 0%

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
