### ISSUE TITLE
`shellExecutionSupported` true even in yarn web

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#104106]
Testing #103835

Made a task provider extension like:
```
		"taskDefinitions": [
			{
				"type": "helloworld",
				"required": [
					"name"
				],
				"properties": {
					"name": {
						"type": "string",
						"description": "whom to greet"
					}
				},
				"when": "shellExecutionSupported"
			}
		]
```

```
	vscode.workspace.registerTaskProvider('helloworld', {
		provideTasks: () => [
			new vscode.Task({ type: 'helloworld' }, vscode.TaskScope.Global, 'Hello! :)', 'helloworld-ext')
		],
		resolveTask: (task) => task
	});
```

and when loading in yarn web, found that the tasks were still provided even though (I believe?) we don't support them.

If I set the when to `false` they don't show up, so it seems `shellExecutionSupported` is resolving true.

**Comment by alexr00** [comment]
I debugged through and `shellExecutionSupported` is set correctly. However, I'm not seeing my task provider extension's contribution get properly registered here: https://github.com/Microsoft/vscode/blob/1998f254ad3f835a0372664c34b9e0863aa8d8a9/src/vs/workbench/contrib/tasks/common/taskDefinitionRegistry.ts#L109-L109

**Comment by alexr00** [comment]
Looks like I just needed to restart yarn web since some things are cached. @JacksonKearl maybe the same thing happened to you? Can you make your above changes again, then restart (or start if it wasn't already running) yarn web?

**Comment by JacksonKearl** [comment]
Yes, looks like a caching issue
