### ISSUE TITLE
Please add syntax parsing for the internal terminal display, which can be customized by users

### ISSUE THREAD

**Issue by Anders-Zhang-Github** [microsoft/vscode#104140]
Like sublime terminal display. reference console.sublime-syntax:

%YAML 1.2
---
name: console
hidden: true
scope: source.build_output
contexts:
  main:
    # for gnu gcc.
    - match: '^(..[^:\n]*):([0-9]+):?([0-9]+)?:? '
      scope: entity.name.filename
    - match: '\b(warning|error): '
      scope: message.error

    # for ti gcc.
    - match: '^\"(.*?)\", line ([0-9]*):'
      scope: entity.name.filename
    - match: '(.*)\.out'
      scope: entity.name.filename
    - match: '(.*)\.lib'
      scope: entity.name.filename
    - match: '\b(warning|error) #[0-9]+(-D){0,1}:'
      scope: message.error
    - match: '\bfailed'
      scope: message.error

    - match: '\b[eE]rror[ !]'
      scope: message.error

    - match: '^\[.+\]$'
      scope: comment

**Comment by Tyriar** [comment]
The process running within the terminal is in control of colors.
