### ISSUE TITLE
Allow right arrow on a collapsed cell to expanded

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104116]
Testing #103887

I tested with multiple collapsed cells using the keyboard to navigate between them. I automatically pressed the right arrow key on a cell to expand it, like I would an item in the tree view. Maybe we should make that keybinding work as well  for collapsed cells?

**Comment by roblourens** [comment]
It actually should work, the question is why it didn't. Can you try again?

**Comment by roblourens** [comment]
Oh sorry I was thinking about folding

**Comment by roblourens** [comment]
I don't want to do this because of the way it confuses these keybindings with folding.
