### ISSUE TITLE
Allow Pointer Lock for Webview?

### ISSUE THREAD

**Issue by AZbang** [microsoft/vscode#104169]
I want use pointer lock api in my webview panel, but:
`
Blocked pointer lock on an element because the element's frame is sandboxed and the 'allow-pointer-lock' permission is not set.
`

**Comment by mjbvz** [comment]
What is the use case?

**Comment by AZbang** [comment]
@mjbvz I want create graph editor (something like that [react-diagrams demo](http://projectstorm.cloud/react-diagrams/?path=/story/simple-usage--simple-example)) in webview panel and i need to use pointer lock for dragging playground without lose focus from webview panel.

**Comment by Yngwarr** [comment]
@mjbvz we want to allow continuous dragging without letting go mouse button. Something like this: [demo video](https://drive.google.com/file/d/1-Fi9mpBh-7bl2hXP--SG1VZCgTDsRPaO/view?usp=sharing).

**Comment by connor4312** [comment]
This works for electron webviews, but not when `"webview.experimental.useIframes": true`
