### ISSUE TITLE
Uncaught ReferenceError: monaco is not defined (Integrating Editor)

### ISSUE THREAD

**Issue by itskhurram** [Microsoft/vscode#10415]
Hello,
I am facing this issue while i am integration Monaco Editor in my application. I managed to run the simple sample successfully of editor. but when i moved it to my application. Addling loader link in index.html and 
Div in my template and 

" require.config({ paths: { 'vs': 'node_modules/monaco-editor/dev/vs' } });
        require(['vs/editor/editor.main'], function () {
            var editor = monaco.editor.create(document.getElementById('EditorIDE'), {
                value: [
                    'function x() {',
                    '\tconsole.log("Hello world!");',
                    '}'
                ].join('\n'),
                language: 'javascript'
            });
        });"
in my controller i am getting error "monaco is not defined" Please help.

**Comment by alexandrudima** [comment]
Do you get any errors on the console or in the network tab before this code fails?

Do you have a stack trace? (monaco is used in other places, including inside editor.main.js)

**Comment by itskhurram** [comment]
managed to resolve it.

**Comment by JamesBlack001** [comment]
So how did you resolve this?

**Comment by itskhurram** [comment]
Hi,
Please make sure followings.
1- Add the loader link in the body instead of header tag. better in the bottom of the body.
2- Put the initialization function in some scope function and call it on init in the template.
3- make sure the paths are correct.
