### ISSUE TITLE
Add Code cell action cropped

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#104170]
See attached screen shot.

<img width="694" alt="capture" src="https://user-images.githubusercontent.com/1931590/89523461-2d8d3b80-d7e3-11ea-9db3-34073c597059.png">

The Notebook is already scrolled all the way to the bottom

**Comment by roblourens** [comment]
I see this with `"editor.scrollBeyondLastLine": false`. There is something strange going on where it seems like the scroll height of the notebook is note calculated correctly. Like here I am scrolled all the way down, but the scrollbar doesn't go to the bottom:

![image](https://user-images.githubusercontent.com/323878/89551692-1557f500-d7c0-11ea-9247-e25bcd57fa49.png)


but sometimes it does go to the bottom, then the space under the cell is cut off. That space is added to the total height of the cell like anything else so this is weird. With `scrollBeyondLastLine` enabled everything works fine.

**Comment by rebornix** [comment]
Based on the results from Inspect Notebook Layout, the height for every cell is calculated correctly (comparing the good one and bad one), but it seems the list view height is miscalculated.
