### ISSUE TITLE
Debugger is not attaching for SAM application when request is launch

### ISSUE THREAD

**Issue by queston02** [microsoft/vscode#104142]
- VSCode Version: 1.47.3
- OS Version: MacOS, Catalina, 10.15.6

Steps to Reproduce:

1. Create HelloWorld AWS SAM application using the nodeJS 10.7 template 
2. Create the launch configuration for application debugging using the below code
```js
{
            "name": "Launch to SAM",
            "type": "node",
            "request": "launch",
            "runtimeExecutable": "sam",
            "runtimeArgs": [
                "local",
                "invoke",
                "-e",
                "${workspaceFolder}/events/event.json",
                "-d",
                "5858",
                "-t",
                "${workspaceFolder}/template.yaml",
                "HelloWorldFunction",
                "--region",
                "us-west-2"
            ],
            "address": "localhost",
            "port": 5858,
            "localRoot": "${workspaceFolder}/hello-world",
            "remoteRoot": "/var/task",
            "protocol": "inspector",
            "stopOnEntry": false,
            "skipFiles": [
                "${workspaceFolder}/node_modules/**/*.js",
                "<node_internals>/**/*.js"
            ]
        }
```
3. Debugger starts but never attaches to the application
4. URL for the project https://github.com/queston02/TestSAM

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Try changing you `type` to `node` and `port` to `simpleAttachPort`

**Comment by queston02** [comment]
As soon as i change `type` to `pwa-node` intellisense shows `Property port is not allowed.` . Anyways i still went ahead changed the `port` as well to the value suggested by you but nothing happened. Debugger still wouldn't budge. It refused to attach to the process running inside the container.

On another note when i use `request` as `attach` then debugger attaches without any issue to the already running process inside the container. You can find the exact parameters in the [projects](https://github.com/queston02/TestSAM) launch configuration.

**Comment by connor4312** [comment]
Can you grab the [nightly extension](https://github.com/microsoft/vscode-js-debug#nightly-extension) and collect a trace log using these instructions?

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

The nightly build also fixes the skipFiles issues.

**Comment by queston02** [comment]
DIdn't find anything wrong in the logs. Have emailed you the log file.

**Comment by connor4312** [comment]
Thanks for the logs. It looks like in your launch config it's still using `port` instead of `simpleAttachPort`

**Comment by queston02** [comment]
Yeah i changed it when nothing happened. Let me end you fresh logs with your suggested changes.

**Comment by connor4312** [comment]
It looks like we're still not getting a value for `attachSimplePort`. What does your launch.json look like?

**Comment by queston02** [comment]
Sent you the new logs having the changes suggested by you in the launch configuration

**Comment by queston02** [comment]
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to SAM",
            "type": "node",
            "request": "attach",
            "address": "localhost",
            "port": 5858,
            // From the sam init example, it would be "${workspaceFolder}/hello-world"
            "localRoot": "${workspaceFolder}/hello-world",
            "remoteRoot": "/var/task",
            "protocol": "inspector",
            "stopOnEntry": false,
            "skipFiles": [
                "${workspaceFolder}/node_modules/**/*.js",
                "<node_internals>/**/*.js"
            ]
        },
        {
            "name": "Launch to SAM",
            "type": "pwa-node",
            "request": "launch",
            "runtimeExecutable": "sam",
            "runtimeArgs": [
                "local",
                "invoke",
                "-e",
                "${workspaceFolder}/events/event.json",
                "-d",
                "5858",
                "-t",
                "${workspaceFolder}/template.yaml",
                "HelloWorldFunction",
                "--region",
                "us-west-2"
            ],
            "address": "localhost",
            "port": "simpleAttachPort",
            "localRoot": "${workspaceFolder}/hello-world",
            "remoteRoot": "/var/task",
            "protocol": "inspector",
            "stopOnEntry": false,
            "skipFiles": [
                "${workspaceFolder}/node_modules/**/*.js",
                "<node_internals>/**/*.js"
            ],
            "trace": "all"
        }
    ]
}`

**Comment by connor4312** [comment]
You want to set `attachSimplePort: 5858`

**Comment by queston02** [comment]
Sent you the latest having `attachSimplePort: 5858`

**Comment by connor4312** [comment]
`attachSimplePort`, you have `simpleAttachPort`. I typo'd the original comment up above.

**Comment by queston02** [comment]
Sorry my bad. Changing to `attachSimplePort` helped. Now debugger is getting attached. Sending you the new logs.

**Comment by connor4312** [comment]
Looks like it's working for you as far as I can see. Thanks for filing the issue. I will clarify in documentation the steps needed for this scenario.

**Comment by queston02** [comment]
skipFiles is still not working. I am using the nightly build. Debugger is steppimg into `<node_internals>/domain.js`, `<node_internals>/internal/_stream_writable.js`. Below is my launch configuration.

```
        {
            "name": "Launch & Attach to App",
            "type": "pwa-node",
            "request": "launch",
            "runtimeExecutable": "sam",
            "runtimeArgs": [
                "local",
                "invoke",
                "-e",
                "${workspaceFolder}/events/test.json",
                "-n",
                "${workspaceFolder}/env-vars/local.json",
                "-d",
                "5858",
                "-t",
                "${workspaceFolder}/template.yaml",
                "Payment",
                "--region",
                "us-west-2"
            ],
            "attachSimplePort": 5858,
            "localRoot": "${workspaceFolder}/",
            "remoteRoot": "/var/task",
            "stopOnEntry": false,
            "skipFiles": [
                "${workspaceFolder}/node_modules/**/*.js",
                "<node_internals>/**"
            ]
        }
```

Below is the VS Code version details

```
Version: 1.48.0-insider
Commit: cfbd1999769f4f08dce29629fb92fdc0fac53829
Date: 2020-08-06T05:40:40.871Z (12 hrs ago)
```

**Comment by connor4312** [comment]
Tracking that in https://github.com/microsoft/vscode/issues/104195
