### ISSUE TITLE
Changing visibility after being set does not change

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#104100]
Testing #103833

1. Set a view to `hidden`
2. Launch extension, view is hidden
3. Change view to `collapsed`
4. Relaunch extension
5. :bug: visibility does not change

I would only expect this to not be respected only when the user has made a change to the view

**Comment by gregvanl** [comment]
Agree, seems like after launching once, VS Code remembers the view state even it I didn't touch the view. The only way I could get changes to `visibility` to take was to set a new --user-data-dir each time to simulate first launch.

**Comment by alexr00** [comment]
This is intentional, visibility is only respected the first time. We don't want to start changing the visibility of views for existing users.

**Comment by misolori** [comment]
Not sure I agree with this, I'd imagine from an extension author's perspective it would be annoying that you couldn't hide/collapse certain views for existing users if they didn't modify that view.
