### ISSUE TITLE
 Application so slow

### ISSUE THREAD

**Issue by MueenM** [Microsoft/vscode#10419]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Application so slow and heavy on load, Specially when open an existing file using VS Code

**Comment by mrmlnc** [comment]
Please provide more details.

**Comment by sandy081** [comment]
Closing this issue since we did not get enough info. Please provide required info and reopen. Thanks.
