### ISSUE TITLE
Do not prompt "Update imports" while renaming file

### ISSUE THREAD

**Issue by leoselig** [microsoft/vscode#104155]
### Steps to reproduce
1. Open VS Code in a TypeScript project
2. Move a file that is `import`-ed by other `.ts(x)`-files to a different location
3. Before the _"Update imports for..."_-prompt shows up, start renaming that file via the left-hand file tree UI

-> see prompt interupting the rename (actual) instead of "waiting" until rename is finished (expected)

Does this issue occur when all extensions are disabled?: **Yes**

### Version information
```
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z (2 wks ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

### Original feature request (outdated)

This is a proposal for a change in UX.

I discovered this usability issue after I moved a file in a Typescript project. Just after I did so, I started renaming a file via the left-hand file tree (selected file and pressed _return_ key). While editing the file name, the _"Update imports for..."_ prompt showed up. I skipped the update (out of annoyence since I wanted to finish renaming) but it repeatedly showed up for different update suggestions.

My specific proposal is to **avoid such import update prompts while currently renaming** a file. However, this might neither be limited only to the text input element for renaming nor to the prompt for import updates.

**Comment by yume-chan** [comment]
Isn't there a "Never automatically update imports" button? Click that and the prompt won't appear again.

![image](https://user-images.githubusercontent.com/1330321/89513970-d2ba0b00-d807-11ea-85e0-6d8714fa33e3.png)

**Comment by mjbvz** [comment]
The dialog should only show up when you finish renaming a file. Is that not what you are seeing?

/needsMoreInfo

**Comment by leoselig** [comment]
@yume-chan The button is there and I was aware that this would have worked around the issue. However, I don’t want to turn it off – the fact that my renaming got interrupted is the core issue for me.

@mjbvz Correct. The dialog DID show up anyway so that’d make it a bug then I guess. I’ll try to reproduce it tomorrow and provide further info.

**Comment by mjbvz** [comment]
Also, test this with extensions disabled to make sure one of them is not causing this

**Comment by leoselig** [comment]
@mjbvz I am reliably able to reproduce both with extensions enabled and disabled.
I added that fact, proper steps to reproduce and the version information to the original issue description.

**Comment by mjbvz** [comment]
Thanks. 

Unfortunately we don't allow extensions to block the rest of the VS Code UI. I don't think this bug is worth the engineering work that would be required to try to change this. Closing as out of scope
