### ISSUE TITLE
Mr Darko

### ISSUE THREAD

**Issue by dmaksimovic** [microsoft/vscode#104108]
Issue Type: <b>Performance Issue</b>

Visual Studio is making my computer hot like a red hot pepperoni, please control Code Helper

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.4.0

**Comment by lszomoru** [comment]
Can you please collect a CPU profile? Thanks!

```
To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue
```
