### ISSUE TITLE
Layout issues with dragging folded cells with outputs

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#104102]
- Open a github issues notebook
- Have two markdown header cells at the same or different levels
- Put a code cell under the second markdown cell, execute it
- Collapse the second markdown cell
- Drag it above the first one
- It becomes expanded with a bad layout

![image](https://user-images.githubusercontent.com/323878/89450674-bd61b580-d70f-11ea-88fe-3d3cb5bfb222.png)

**Comment by rebornix** [comment]
This is a regression, let's get it fixed this month.
