### ISSUE TITLE
Cannot open a folder

### ISSUE THREAD

**Issue by pedroha** [microsoft/vscode#104190]
Issue Type: <b>Bug</b>

The last release of vscode doesn't open a project. None of the files are showing up.

I used to open a project in a folder with the following terminal command
```
code .
```

But the folder does not open. Even manually, when I select the folder, the files don't show up.

When I select my previous projects
-> File -> Open Recent -> My project

"My project" does not opened.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.9
xml|Dot|2.5.1
vscode-great-icons|emm|2.1.47
vscode-peacock|joh|3.7.2
debugger-for-chrome|msj|4.12.9
vscode-json-editor|nic|0.2.3
material-icon-theme|PKi|4.2.0
java|red|0.65.0
markdown-preview-enhanced|shd|0.5.12
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.23.0
gitblame|wad|4.2.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

Also assigning to @deepak1556 as this might be one of the duplicate can not open on Linux issues

**Comment by deepak1556** [comment]
Is this only happening to a specific folder or you cannot open any folder ?

when you open vscode from the finder.app does the issue still happen ?

@isidorn is there any kind of project state cache we maintain that can be reset ? Cache about last folder opened.

**Comment by isidorn** [comment]
@deepak1556 yes, we have the recently opened folders list. I believe we store that in storage.

However to reset that I suggest that the user simply uses a new `user-data-dir`.

@pedroha can you please from the terminal open VS Code, something like this
```
code --user-data-dir PATH_TO_SOME_FOLDER_WHERE_VSCODE_WILL_STORE_TMP_DATA
```

**Comment by pedroha** [comment]
Greetings,

I downloaded visualcode insiders and I can open folders fine!

I tried the command

code --user-data-dir .

and it did not open the current directory; however, after that, I was able
to manually open folders: File -> open
And I'm also able to drop and open folders.

Thanks for the help!

Let me know if you need anything else.

Regards,
Pedro

**Comment by deepak1556** [comment]
> I tried the command
>
> code --user-data-dir .

don't specify the current directory, please provide an absolute path `code --user-data-dir /tmp/code-temp-profile`

Seems like a corrupt state, https://github.com/microsoft/vscode/issues/102975 should fix this as well. Closing this in favor of it.
