### ISSUE TITLE
tsserver.js remote ssh extension consumes too much memory 

### ISSUE THREAD

**Issue by axelhuizinga** [microsoft/vscode#104187]
- VSCode Version:1.47.3
- OS Version: debian 10 - x64 4.19.0-10

Steps to Reproduce:

1. start remote ssh project with typescript compilation
2.up to 10 instances of tsserver.js running with above 40-100% Memory consumption
3. runs with --enable-telemetry but I have disabled telemetry on all configuration levels

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information
