### ISSUE TITLE
code --telemetry hangs on WSL

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#104191]
```
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

open an ubuntu instance on windows/wsl
run `code --telemetry`

result: Nothing, it seems to hang, never returns, have to ^C to kill it

works fine if run from windows side/command line

**Comment by aeschli** [comment]
Fixed by removing `--telemetry` from the list of valid parameters in code for WSL
