### ISSUE TITLE
Errors found where errors aren't occuring

### ISSUE THREAD

**Issue by megscholl** [microsoft/vscode#104197]
In this instance:

    this.data.getParkCampgrounds(this.park).then(data =>{
            res = JSON.parse(data);
            list = res.campgrounds;
            this.openAmenityListPage(item, list);
          });

the multiple spaces before "this.data.getParkCampgrounds" are highlighted for error stating "Declaration or statement expected.ts(1128)", and one single character in "getParkCampgrounds" will be highlighted for error and say that a semi-colon is expected. Errors like these are found often, and never give an error explanation that makes any sense.

**Comment by IllusionMH** [comment]
/needsMoreInfo

This code doesn't produce issue if copied as is from GitHub, so it's something with surrounding code (e.g. [parse issue](https://github.com/microsoft/TypeScript/issues/32914) with arrow functions) or there are some unexpected characters before it (you can use [Highlight Bad Chars](https://marketplace.visualstudio.com/items?itemName=wengerk.highlight-bad-chars) to check ).

Do you see any of this patterns? Could you reduce your file to minimal structure structure that has same problems?

/assign @mjbvz
