### ISSUE TITLE
Make Markdown Cells Grabbable - Native Notebook Editor

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#104104]
Users during Python Extension Native Notebook QP had a very difficult time moving markdown cells where the area for grabbing is extremely small. Potential solution discussed during notebook design review was to make the entire markdown cell grabbable. 

![image](https://user-images.githubusercontent.com/19276747/89452288-44179200-d712-11ea-90d0-ee92a447737b.png)

**Comment by roblourens** [comment]
The tradeoff is that users would then not be able to click/drag to select text, which Jupyter allows. I think that is useful and I would use it often. But we can keep discussing it.

**Comment by claudiaregio** [comment]
Yes users would just have to enter edit mode to be able to copy the content. Are there any other proposed solutions? The currently shared space among the collapse icon and the drag and drop area is tiny (even for the largest font size of markdown) and is a real nuisance.

**Comment by misolori** [comment]
I think you are more likely to move cells than select & copy text. Typically the copying happens from code cell outputs (to copy certain strings/columns), and sometimes there are code cell blocks in markdown you might want to copy (if it's a tutorial notebook). But to me it feels like moving cells would be significantly more common so I'd vote for that.

**Comment by roblourens** [comment]
Sure. Is it a problem that it will be inconsistent with code cells then? If they can't find the drag region on the side of a markdown cell then they probably won't find it on a code cell either.

**Comment by misolori** [comment]
That's a good point. Would we be able to make the entire cell around (minus the code + output portions) draggable?

**Comment by claudiaregio** [comment]
During the first day of QPs where users still had to move cells one by one (not move a group by collapsing under markdown) they did not have any issue grabbing the code cells. 
1. Code cells tend to be larger than the markdown cells 
2. Even an empty code cell has much more real estate to grab than the largest markdown text shared with the collapse icon. 

Provided current grab area in red as reference below. 

![image](https://user-images.githubusercontent.com/19276747/89589632-da26e780-d7fa-11ea-8500-db9b4c20b778.png)

**Comment by roblourens** [comment]
Good point. Although I should also mention that I fixed a bug last week where the fold button of the markdown cell had become un-draggable, when the user should be able to drag it, or click to fold/unfold. Users may not expect that to work though.

**Comment by claudiaregio** [comment]
Miguel mentioned that, I think that would be really hard for them to discover. The cursor changes to pointer when over the chevron.

**Comment by bpasero** [comment]
I verified that I can drag a markdown cell from anywhere. I cannot select text anymore though, not sure this is the expected outcome.
