### ISSUE TITLE
 run yarn web,can not get extensions

### ISSUE THREAD

**Issue by 280185386** [microsoft/vscode#104145]
Version: 1.47.3
Commit: Unknown
Date: Unknown
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
Steps to Reproduce:

when I run yarn web,can not get extensions
(base) PS D:\Projects\vscode-1.47.3> yarn web --port=9898
yarn run v1.22.4
$ node resources/serverless/code-web.js --port=9898
Web UI available at   http://localhost:9898
[11:11:10] Warning: Make sure to run yarn gulp watch-web
Could not find the following browser main files:
configuration-editing\dist\browser\configurationEditingMain.js
github-authentication\dist\browser\extension.js
github-browser\dist\browser\extension.js
image-preview\dist\browser\extension.js
html-language-features\client\dist\browser\htmlClientMain.js
json-language-features\client\dist\browser\jsonClientMain.js
merge-conflict\dist\browser\mergeConflictMain.js
python\dist\browser\pythonMain.js
npm\dist\browser\npmBrowserMain.js
vscode-web-playground\dist\browser\extension.js
markdown-language-features\dist\browser\extension.js
css-language-features\client\dist\browser\cssClientMain.js
Error: ENOENT: no such file or directory, stat 'D:\Projects\vscode-1.47.3\extensions\vscode-web-playground\dist\browser\extension.js'
Error: ENOENT: no such file or directory, stat 'D:\Projects\vscode-1.47.3\extensions\github-authentication\dist\browser\extension.js'
Error: ENOENT: no such file or directory, stat 'D:\Projects\vscode-1.47.3\extensions\merge-conflict\dist\browser\mergeConflictMain.js'
Error: ENOENT: no such file or directory, stat 'D:\Projects\vscode-1.47.3\extensions\npm\dist\browser\npmBrowserMain.js'

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
The error is there:

> Warning: Make sure to run yarn gulp watch-web
