### ISSUE TITLE
Submenu jumps when scrolling on up/down arrow

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#104135]
Issue Type: <b>Bug</b>

**Repro**
1. Using custom menus
1. Make the window fairly small so that menus will overflow
1. Open a submenu (such as the `recently opened` menu)
1. Put the mouse on the submit
1. Then use the up/down arrow keys to scroll the menu

**Bug**
When the menu scrolls, it then jumps back up the mouse position:

In this gif, I'm only hitting the down arrow key:

![Aug-05-2020 16-45-43](https://user-images.githubusercontent.com/12821956/89474944-d54f2e80-d73b-11ea-8c0a-3aeb000437da.gif)

VS Code version: Code - Insiders 1.48.0-insider (d13d2fc56da7a2f8bcad4256212db0661fcbba45, 2020-08-05T05:30:25.429Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.04GB (2.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>

**Comment by sbatten** [comment]
very corner case, optimizing isn't worth the risk imo
