### ISSUE TITLE
Mime type picker is orphaned upon clearing cell output if the output was collapsed

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104118]
Testing #103887

https://memes.peet.io/img/1cb5619b-e6b3-4053-96b9-83cf1c5518d9.mp4

1. Execute a cell
1. Collapse the cell or its output
1. Expand it
1. Clear the output
1. The mime type picker sticks around  🐛

**Comment by roblourens** [comment]
Can be folded into https://github.com/microsoft/vscode/issues/104119
