### ISSUE TITLE
Shift+tab in settings editor can land on .settings-tree-focus-sink

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#104133]
![recording (23)](https://user-images.githubusercontent.com/2193314/89474411-5f969300-d73a-11ea-8f04-2370c94bbaff.gif)

Version: 1.48.0-insider (user setup)
Commit: d13d2fc56da7a2f8bcad4256212db0661fcbba45
Date: 2020-08-05T05:30:25.429Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by 9at8** [comment]
The sink might end up getting removed completely with what I am working on. But I'm gonna leave it open till then.

**Comment by roblourens** [comment]
Now obsolete :)
