### ISSUE TITLE
Grab Hand Top of Cell (to be removed) - Native Notebooks Editor 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#104103]
Remove hand cursor from top of code cell that indicates ability to drag cells. 

![image](https://user-images.githubusercontent.com/19276747/89451034-6c9e8c80-d710-11ea-80c8-0b36ed78a039.png)

**Comment by roblourens** [comment]
Already fixed in b873dc659aa5e11c28274eb209dbc20ed8de6f45
