### ISSUE TITLE
Copying a cell copies its execution state

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104189]
While verifying https://github.com/microsoft/vscode/issues/101462

This issue as described is fixed but I noticed that we still copy the cell execution state, even without copying the output

![](https://memes.peet.io/img/20-08-08097d42-c1c4-4a8d-ae38-f055c839af62.png)

If the cell is copied while it's executing, the spinner will keep going infinitely

![](https://memes.peet.io/img/20-08-ee9f02a5-48fa-4ab5-960c-8196859711cb.png)

I think we should just not copy the execution state (especially if we don't copy the output)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/103881
