### ISSUE TITLE
Notebook layout issue when collapsing and moving cells

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#104112]
![Kapture 2020-08-05 at 13 31 47](https://user-images.githubusercontent.com/35271042/89461055-294c1a00-d720-11ea-9fad-c6b07e0d971d.gif)

Steps to Reproduce:

1. Fold a cell with a nested code + output 
2. Move cell above another section
3. :bug: When cell is moved, it is expanded and layout issues appear

**Comment by connor4312** [comment]
Happened to see this issue when glancing though -- may have just filed a duplicate https://github.com/microsoft/vscode/issues/104120

**Comment by rebornix** [comment]
Already fixed via https://github.com/microsoft/vscode/commit/408ad5d67dcc050ec13b2e02cd9a6735a3bbd3d4
