### ISSUE TITLE
Unable to map letter `z` to `undo` command with a when clause

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#104194]
- VSCode Version: 1.48.0-insider
- OS Version: Darwin x64 19.6.0
Commit: cfbd1999769f4f08dce29629fb92fdc0fac53829
Date: 2020-08-06T05:40:40.871Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

Steps to Reproduce:

1. Add the following into `package.json`
```json
            {
                "mac": "Z",
                "win": "Z",
                "linux": "Z",
                "key": "Z",
                "when": "editorLangId == abc",
                "command": "undo"
            },
```
2. The expectation is this will never work unless a text editor is opened with the language `abc`
3. However, when ever you type `z` it performs an undo

**Observation**
Seems to be special for `undo`. I.e. if i replace `undo` with a custom command, then nothing happens & the letter `z` gets written into the text editor.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by lszomoru** [comment]
I believe that this is by design due to the fact that there is a default keybinding for `z`.

![image](https://user-images.githubusercontent.com/3372902/89646716-97c5df00-d8bc-11ea-8a2c-7b39b2a975cd.png)

**Comment by DonJayamanne** [comment]
Closing this issue as it has been fixed. 
@rebornix confirmed that the issue was resolved and we werre to use `notebook.undo` instead of using `undo`.
