### ISSUE TITLE
Dragging group above a title hides the title

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104120]
Testing https://github.com/microsoft/vscode/issues/99882

Video: https://memes.peet.io/img/20-08-b280da55-dc5b-44f8-b291-c61341541957.webm

1. Have two groups of titles/content, A and B
2. Collapse A and drag it above B
3. B expands and breaks 🐛

**Comment by rebornix** [comment]
fixed via https://github.com/microsoft/vscode/commit/408ad5d67dcc050ec13b2e02cd9a6735a3bbd3d4
