### ISSUE TITLE
Allow to disable developer related keybindings in extension host

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#10416]
- VSCode Version: 1.4.0
- OS Version: Win8.1

The extension development host maps `ctrl+shift+i` to Chrome developer tools and does not allow this to be overridden by keyboard shortcut settings. Are there any other keyboard shortcuts that the development host overrides? Is it possible to remove this behavior so that the development host behaves closer to normal-mode vscode?

**Comment by bpasero** [comment]
Hardcoded in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/index.html#L115 and tough to just take out because every other extension developer will be used to it.

**Comment by siegebell** [comment]
@bpasero when are extension developers expected to use the Chrome developer tools panel?

**Comment by bpasero** [comment]
@siegebell we in the team use it all the time to debug the extension host together with an extension when we run out of sources. even when you run a real build it is sometimes helpful being able to debug everything, not just the extension but also the extension host communication and processing.
