### ISSUE TITLE
`$tsc-watch` pattern could not match `[3:48:11 ├F10: PM┤]`

### ISSUE THREAD

**Issue by JounQin** [microsoft/vscode#104157]
版本: 1.47.3
提交: 91899dcef7b8110878ea59626991a18c8a6a1b3e
日期: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.3
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

Does this issue occur when all extensions are disabled?: Yes

Not sure why but `new Date().toLocaleTimeString()` results different format with my Chrome browser on Node 12, and if I upgrade to Node 14 it will result same format with Chrome.

I don't know should we change the pattern to match it.

The problem is `\D` will not match `├F10: PM┤`.

**Comment by JounQin** [comment]
Just notice the clarification at https://github.com/microsoft/vscode/issues/103390#issuecomment-664838470

@alexr00 But can we optimize the pattern to match this format? It is very confusing.

**Comment by alexr00** [comment]
You can modify the problem matcher yourself to support the format of the string in the language you have set.  Example:

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "option": "watch",
      "isBackground": true,
      "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared"
      },
      "problemMatcher": {
        "base": "$tsc-watch",
        "background": {
          "activeOnStart": true,
          "beginsPattern":
            "File change detected\\. Starting incremental compilation\\.\\.\\.$",
          "endsPattern": "Compilation complete\\. Watching for file changes\\.$"
        }
      },
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

**Comment by alexr00** [comment]
Might be able to add this into the existing regex without too much difficulty. Something like:
```
^\s*(?:message TS6042:|\[?\D*\d{1,2}[:.]\d{1,2}[:.]\d{1,2}\D*(├\D\d{1,2}[:.]\D*┤)?(?:\]| -)) (?:Compilation complete\.|Found \d+ errors?\.) Watching for file changes\.
```

**Comment by JounQin** [comment]
I understand the workaround, but this issue only occurs on Node 12, and `new Date().toLocaleTimeString(locale)` will always result `├F10: PM┤` except `locale` being `en/en-US`, etc.

So I think it could be common issue on Node 12, what means changing current regex should be preferred.

**Comment by IllusionMH** [comment]
`├F10: PM┤` instead of `PM` looks more like problem ICU data used by Node and not reproducible on Windows

```
$ npx node@14
Welcome to Node.js v14.7.0.
Type ".help" for more information.
> new Date(2020,0,1,2,30,1).toLocaleTimeString('en')
'2:30:01 AM'
> new Date(2020,0,1,2,30,1).toLocaleTimeString('en-US')
'2:30:01 AM'
> new Date(2020,0,1,12,30,1).toLocaleTimeString('en')
'12:30:01 PM'
> new Date(2020,0,1,12,30,1).toLocaleTimeString('en-US')
'12:30:01 PM'



$ npx node@12
Welcome to Node.js v12.18.3.
Type ".help" for more information.
> new Date(2020,0,1,2,30,1).toLocaleTimeString('en')
'2:30:01 AM'
> new Date(2020,0,1,2,30,1).toLocaleTimeString('en-US')
'2:30:01 AM'
> new Date(2020,0,1,12,30,1).toLocaleTimeString('en')
'12:30:01 PM'
> new Date(2020,0,1,12,30,1).toLocaleTimeString('en-US')
'12:30:01 PM'
```

**Comment by alexr00** [comment]
@JounQin what locale are you using?

**Comment by IllusionMH** [comment]
Oh, I misread comment about `en`/`es-US` - these two are works correctly in case described by @JounQin and passing something else causes problem. So my comment above isn't relevant.

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString)

>  Before version 13.0.0, only the locale data for en-US is available by default. When other locales are specified, the function silently falls back to en-US. To make full ICU (locale) data available for versions prior to 13, see Node.js documentation on the --with-intl option and how to provide the data.

However it looks more like some "default locale data" is used in this case, not `en-US`.

I found device with `ru-RU` locale it always print same format as Russian locale and without `├F10: PM┤`
```
Welcome to Node.js v12.18.3.
Type ".help" for more information.
> new Date(2020,0,1,16,23,03).toLocaleTimeString()
'16:23:03'
> new Date(2020,0,1,16,23,03).toLocaleTimeString('en')
'4:23:03 PM'

> new Date(2020,0,1,16,23,03).toLocaleTimeString('ru')
'16:23:03'
> new Date(2020,0,1,16,23,03).toLocaleTimeString('ar')
'16:23:03'
> new Date(2020,0,1,16,23,03).toLocaleTimeString('es')
'16:23:03'
> new Date(2020,0,1,16,23,03).toLocaleTimeString('kr')
'16:23:03'
```

So it looks more like Node 12 or Node 12 + unexpected system info.

**Comment by JounQin** [comment]
> @JounQin what locale are you using?

```log
> process.env.LANG
'zh_CN.UTF-8'
> Intl.DateTimeFormat().resolvedOptions().locale
'zh-CN'
```

**Comment by JounQin** [comment]
@IllusionMH Yes, it is very weird on Node 12:

```log
Welcome to Node.js v12.18.3.
Type ".help" for more information.
> new Date(2020,0,1,16,23,03).toLocaleTimeString()
'4:23:03 ├F10: PM┤'
> new Date(2020,0,1,16,23,03).toLocaleTimeString('en')
'4:23:03 PM'
> new Date(2020,0,1,16,23,03).toLocaleTimeString('ru')
'4:23:03 ├F10: PM┤'
> new Date(2020,0,1,16,23,03).toLocaleTimeString('ar')
'4:23:03 ├F10: PM┤'
> new Date(2020,0,1,16,23,03).toLocaleTimeString('es')
'4:23:03 ├F10: PM┤'
> new Date(2020,0,1,16,23,03).toLocaleTimeString('kr')
'4:23:03 ├F10: PM┤'
```

**Comment by alexr00** [comment]
To verify, open a typescript project that has a tsc-watch task (most of extension samples are good for this). Run the watch task. Verify that the "Building" status bar item goes away (indicating that the end pattern has matched) after the build has completed. Make a change that triggers the build to start again. Verify that "Building" comes back, and then goes away again. Do this once for en-us, and once for another locale where this unexpected timestamp occurs, such as zh-CN.

**Comment by JacksonKearl** [comment]
How can I configure my tsc to log under a different locale? I tried changing my system to chinese and I got:

```
> new Date(2020,0,1,16,23,03).toLocaleTimeString('ar')
'4:23:03 PM'
> process.env.LANG
'zh_CN.UTF-8'
> Intl.DateTimeFormat().resolvedOptions().locale
'und'
```

**Comment by alexr00** [comment]
Hmm, I'm not sure how you can do that. @JounQin would you be able to download the latest insiders build and see if the problem matcher is working for you now? https://code.visualstudio.com/insiders/ It installs side by side with stable.

**Comment by JounQin** [comment]
@alexr00 I'm using this insiders build and can confirm it works.

**Comment by alexr00** [comment]
Many thanks @JounQin !
