### ISSUE TITLE
and, or, ... keywords not highlighted

### ISSUE THREAD

**Issue by jhasse** [Microsoft/vscode#10411]
For readability it would great, if the keywords `and`, `or`, etc. are highlighted in languages where they are available like Python and C++. See GitHub's highlighting as an example:

Python:
```python
if a or b and c:
    pass
```

C++:
```cpp
if (a or b and c || d && e) {
}
```
(notice how ||, && aren't red here)

**Comment by aeschli** [comment]
Highlighting depends on the language's grammar and the theme you choose. Some laguages decide to call them keywords, other call the operators.

You would have to file such a change request directly against the language's grammar. 
For C++ we use https://github.com/atom/language-c, for python we use https://github.com/textmate/python.tmbundle

**Comment by jhasse** [comment]
Thanks! For reference: I've created these two issues:

https://github.com/atom/language-c/issues/157
https://github.com/textmate/python.tmbundle/issues/56

**Comment by jhasse** [comment]
According to [this comment](https://github.com/atom/language-c/issues/157#issuecomment-239817914) the C++ grammar already defines the keywords correctly.

If I understand it correctly VSCode's syntax theme needs some adjustments. Can you reopen this issue to track this or should I create a new one?

**Comment by aeschli** [comment]
C++ uses scope 'keyword.operator' for 'and' and 'or'. 
The VSCode default theme renders with the default color. It does that as other grammars (e.g. Typescript) also uses that scope for operators like '+', '_' ... and we want them to all have the default color.

Did you try a different theme?

**Comment by jhasse** [comment]
I see. Yes, some of the other themes do this differently.

Is there some way to change this and leaving +, -, ... for Typescript in tact? I really like the Light+ theme and would love to use it for C++ and Python ;)
