### ISSUE TITLE
Emmet: Remove Tag - also unindent the tag content

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#104173]
- VSCode Version: 1.46
- OS Version: Win 8.1

Steps to Reproduce:

1. Create a HTML file with the following content
```
<pre><code>class ClassName {
  constructor({ thisName:  thisName, another: another}) {
    this.thisName = thisName
    this.another = another // this is create
  }
}
</code></pre>
```
1. Place the cursor after `<code>`
1. Execute the command `Emmet: Remove Tag`
1. The `code` tag is removed but also everything is unindented 1 step
```
<pre>class ClassName {
constructor({ thisName:  thisName, another: another}) {
  this.thisName = thisName
  this.another = another // this is create
}
}
</pre>
```

If you do the process by hand:
1. `Emmet: Balance (outward)`
1. <kbd>Ctrl</kbd>+<kbd>X</kbd>
1. `Emmet: Balance (outward)`
1. <kbd>Ctrl</kbd>+<kbd>V</kbd>
1. The result is correct
```
<pre>class ClassName {
  constructor({ thisName:  thisName, another: another}) {
    this.thisName = thisName
    this.another = another // this is create
  }
}
</pre>
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by vinku** [comment]
I am interested in this and would be working on it.

**Comment by vinku** [comment]
VsCode implementation just removes an indent/tag (exactly one indent i.e a tab or x spaces) at the start of the line for the lines in between the tags opening and closing(if there is enough blank space)

Testing the behavior here [https://docs.emmet.io/actions/remove-tag/](https://docs.emmet.io/actions/remove-tag/),

it is clear that the content should be adjusted for indentation if the indentation of content is more than that of tags. Also, if there is an adjustment needed, the adjustment should be the difference in the indent levels not just plainly one indent.

**Comment by rioj7** [comment]
@vinku  I have configured VSC to not create any indent for any tag. Also this is inside a pre tag so no indentation modification should be done. It could also be a span tag that changes the color of the code in the pre tag. a code tag is not a tag that modifies indentation.

**Comment by rzhao271** [comment]
I'm not very familiar with this part of Emmet functionality yet. Will take a look at the PR after patching up some other parts of Emmet.
