### ISSUE TITLE
Erratic behavior in Node.js debugger when a class has a public class field

### ISSUE THREAD

**Issue by discombobulateme** [microsoft/vscode#104269]
- VSCode Version: 1.47.3 
- OS Version: macOS 10.15.6

**Steps to Reproduce:**

1. Copy/Paste this code into your VSC
```
class Fruit {
  kind = 'fruit'
}
const tomato = new Fruit()
console.log(tomato.kind)
```
2. Insert a breakpoint on line 4
3. Start debugger
4. It stops on line 4. Click on Step Over
5. It doesn't stop on line 5 and finishes the execution
6. Note: it was also checked and on 1.48.0-insider (and doesn't work)
The debugger should have stopped on line 5, but instead, it behaves as if we hit the continue bottom

![vsc-bug](https://user-images.githubusercontent.com/7980624/89682816-abdb0200-d8f7-11ea-84dc-a2f952c0b189.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Thanks for the issue and nice repro. You can get around this for the moment by making the first line of the file not empty.

**Comment by connor4312** [comment]
Actually, this is the same root problem as https://github.com/microsoft/vscode-js-debug/issues/223. I will follow up there.

/duplicate
