### ISSUE TITLE
 Keyboard usability issue in quickopen file command

### ISSUE THREAD

**Issue by yuval-gilboa** [microsoft/vscode#104256]
Issue Type: <b>Bug</b>

From anywhere in VSCode:

1. Click Ctrl+P 
2. QuickOpen prompt opens
3. Start typing file name
4. Quick partial results list is shown
5. Move with down arrow to move focus to one of the files but don't press Enter yet
6. Full results list is returned and focus is moved to first line
7. Press Enter - the first file will be selected instead of the file intended

The focus change on step (6) causes usability issue because many times the list changes just as you press Enter, causing the wrong file to be selected.

Proposed solution: don't change focus when full files list is fetched if the selected file is within the list of files shown initially.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (19.66GB free)|
|Process Argv|--file-uri file:///c%3A/GM/code/gml-gallery/.vscode/gml-gallery.code-workspace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
easy-less|mrc|1.6.3
vscode-typescript-tslint-plugin|ms-|1.2.3
autolaunch|phi|2.0.3
yuval-icons|yuv|0.2.0
markdown-all-in-one|yzh|3.2.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
I think I fixed this last milestone. Can you update to latest?
