### ISSUE TITLE
Debug: clicking on reconnect in attach case causes endless reconnect

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10426]
Following these steps: https://blog.docker.com/2016/07/live-debugging-docker/

When you attach press the "Reconnect" button and see endless reconnects happening. This is on Mac.

**Comment by isidorn** [comment]
Seems to only happen for the docker case (can not repro for express app), setting to september to investigate then

**Comment by isidorn** [comment]
Nobody else complained - will reopen if more people see this in the meantime closing this as will not fix since I do not want to setup docker.
