### ISSUE TITLE
When deleting a folder or file in GitHub Code Spaces the delete dialogbox does not hide after clicking delete

### ISSUE THREAD

**Issue by nickfloyd** [microsoft/vscode#104266]
**Steps to reproduce:**
1. Open a new or existing project in Code Spaces
2. Create a file or folder
3. Right-click on the created item - choose "Delete permanently"
4. Click "delete" in the dialog box

Note: The dialog box does not hide.

**Env details:**
Google Chrome
Version 84.0.4147.105 (Official Build) (64-bit)

Code Spaces details:
* Settings sync is on
* Logged in with a GH profile
* Project language is go

![2020-08-07 13 51 19](https://user-images.githubusercontent.com/139819/89678691-40704080-d8b5-11ea-8010-69842c152baf.gif)

**Comment by isidorn** [comment]
Please file this against the code space repository. This is not part of core vscode. Thanks
