### ISSUE TITLE
IMHO suggest widget should not bind Home/End by default

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#10423]
It makes the suggest widget mess with my typing.

Here I am not using the suggest widget explicitly, it is popping up by itself.
* I type `lines`
* then `End`
* then `;`
* the result is broken code

IMHO it is cool that I can go to the end of the suggestion list, but I think the usefulness of that is far smaller than the usefulness of going to the end of the line while typing (having not triggered suggestions manually). 

![rjw74swwmp](https://cloud.githubusercontent.com/assets/5047891/17580489/45d4f9dc-5f9f-11e6-86d0-ce78c417357b.gif)

**Comment by joaomoreno** [comment]
Related to #10263

@haibison, I think @alexandrudima is right in comparing the pros and cons of having this, so I will revert the commit.

**Comment by haibison** [comment]
Thank you, I understand...
