### ISSUE TITLE
Bug at keyboard-shortcuts-windows.pdf

### ISSUE THREAD

**Issue by szabi79** [microsoft/vscode#104290]
Issue Type: <b>Bug</b>

Hello!

Bug at Help!
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

Display 
Ctrl+ = / - Zoom in/out 

is correct:
Ctrl+ +/ - Zoom in/out 

Best, Szabi

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gregvanl** [comment]
Hi @szabi79 `Ctrl + +/-` will work on Windows and there are actually three keyboard shortcuts by default:

![image](https://user-images.githubusercontent.com/12818376/89796228-39784680-dade-11ea-8516-70a7ba34b6da.png)

but the most visible keybinding for **Zoom In** is `Ctrl + =` as you can see from the Command Palette:

![image](https://user-images.githubusercontent.com/12818376/89796073-08981180-dade-11ea-92f6-f601caac0e30.png)
