### ISSUE TITLE
Creating random rg.exe processes filling CPU and memory

### ISSUE THREAD

**Issue by zero1hac** [microsoft/vscode#104205]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I open VScode, do a git pull, it goes rogue.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (2.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.5.1
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.10.21
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.1.3
graphql-for-vscode|kum|1.15.3
azurecli|ms-|0.5.0
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.9
markdown-preview-enhanced|shd|0.5.12
autoimport|ste|1.5.3
alphabetical-sorter|ue|2.0.1

</details>

**Comment by roblourens** [comment]
See whether the tips here help: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
