### ISSUE TITLE
Some test: Localization test is pending...

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#104230]
Running the smoke test results in pending localization tests.

**Comment by dbaeumer** [comment]
OK. I tracked this down. The tests are skipped because of @isidorn marking them as skipped (an issue would have been nice :-))

Looking into why they got skipped is that the API for loading an extension has changed. The new API (https://github.com/microsoft/vscode/blob/master/test/automation/out/extensions.d.ts#L8) now requires a version number and the version provided didn't exist (the version is the extension version not the VS Code version). Hence the test was failing :-)

I reenabled the test with a language pack version of 1.48.2 which is the latest version. However I need API that allows me to pass 'undefined' as the version to indicate I want latest. @sandy081 is this possible right now?

**Comment by sandy081** [comment]
Looks like @isidorn introduced this version for aria label. We need a way to find the element by id instead of name / version.

**Comment by sandy081** [comment]
Introduced `data-extension-id` attribute that smoke test can depend on and removed the dependency on label, version & publisher. So you can install an extension just by passing id.

**Comment by isidorn** [comment]
I also saw the same...
