### ISSUE TITLE
VSCode Marketplace Theme moderation?

### ISSUE THREAD

**Issue by eliashdezr** [Microsoft/vscode#1042]
So I see that the user **genare** contributed to a [huge list of themes](https://github.com/gerane/VSCodeThemes), and props to that, but it is a really a PIA try to preview each one of them because the only description we have is a link to another site to see how it looks like.

So users that put a better effort to show us their themes, are difficult to find in that flooded list by **genare**. For example. look at this submission by [**Tarique Naseem**](https://marketplace.visualstudio.com/items/tnaseem.theme-seti), that's how I think it should be submitted each theme extension.

I know that some people would say "do a PR?", but that is not the point, the thing is, we should have quality over quantity.

**Comment by chrisdias** [comment]
This is good feedback, thanks, and i agree it would be better to have a preview of the theme as an icon. I see that you've already created an issue in that theme repository. Other than asking genare to do this work, I don't know what else I can do to resolve this issue as it is more feedback than a task.  I'm going to close this and if you've have something specific I can do, please re-open it.
