### ISSUE TITLE
\" won't be replace to " in launch.json

### ISSUE THREAD

**Issue by F-Unction** [microsoft/vscode#104226]
- VSCode Version: 1.47.3
- OS Version: Windows 10 2004 19041.388

Steps to Reproduce:

1.Enter these into `launch.json`
```json
            "program": "cmd",
            "args": [
                "/C",
                "echo \"test\" & pause",
            ],
```
2.Open a file, start debug

Then it opens a cmd.exe, there are `\"test\"` but not `"test"`
![Snipaste_2020-08-07_15-46-32](https://user-images.githubusercontent.com/51352133/89622621-e62bab80-d8c5-11ea-86e9-c8f525b265f9.png)
How can I enter `"` into it?

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@F-Unction what debugger are you using?
VS Code is not interpreting the args in any special way...

**Comment by F-Unction** [comment]
> @F-Unction what debugger are you using?
> VS Code is not interpreting the args in any special way...

gdb
So how can I enter `"` into args
