### ISSUE TITLE
VS Code Crash 

### ISSUE THREAD

**Issue by anvesh437** [microsoft/vscode#104254]
Issue Type: <b>Bug</b>

VS code is getting crash when I do coding. Faced twice today.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.70GB (6.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-beautifier|mic|2.3.3
remote-wsl|ms-|0.44.4
vscode-typescript-tslint-plugin|ms-|1.2.3
angular-console|nrw|13.0.0

</details>

**Comment by deepak1556** [comment]
Does the crash happen with latest insiders https://code.visualstudio.com/insiders ? If so can you follow the steps here https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the dmp file. Thanks!
