### ISSUE TITLE
Extra spaces between braces when formatting JavaScript objects

### ISSUE THREAD

**Issue by alexanderby** [Microsoft/vscode#10424]
There seems to be no option to prevent inserting extra space after and before braces when formatting JS objects.
For example, when I expect
`var obj = { x: 5, y: 7 };`
to look like
`var obj = {x: 5, y: 7};`

**Comment by jrieken** [comment]
<img width="455" alt="screen shot 2016-08-11 at 11 03 23" src="https://cloud.githubusercontent.com/assets/1794099/17583817/43192cd6-5fb3-11e6-8516-bb9db23b7347.png">

These are all the options TypeScript/JavaScript currently supports. For more please file an feature request here: https://github.com/Microsoft/TypeScript

**Comment by joshrivers** [comment]
See issue https://github.com/Microsoft/TypeScript/issues/10282
