### ISSUE TITLE
Allow file explorer to have sticky parent directory

### ISSUE THREAD

**Issue by RyanAfrish7** [microsoft/vscode#104271]
In the explorer view (and possibly other tree views), when dealing with directories having thousands of children items (eg. node_modules), there is no quick way to collapse such a directory and go one level up. I propose making the immediate parent directory element sticky at the top as shown in the image below.

![image](https://user-images.githubusercontent.com/9781909/89685680-75fb4500-d91a-11ea-94a5-175e7b9d395c.png)

**Comment by isidorn** [comment]
You can just press `left` and you will get navigated to the parent.
Having a sticky parent element is a fair feature request which I honestly think we will not add. though I can leave it open for now.

**Comment by RyanAfrish7** [comment]
Will submitting a PR make any difference?

**Comment by isidorn** [comment]
No.

**Comment by starball5** [comment]
No longer out of scope? Completed in / duplicate of #161207 ?
