### ISSUE TITLE
The file name could not be modified correctly

### ISSUE THREAD

**Issue by onlywanna** [microsoft/vscode#104227]
I have changed my file name, but the file is still the same name when it was introduced.
![image](https://user-images.githubusercontent.com/34205436/89625860-188bd780-d8cb-11ea-9340-4e68eaec720f.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

What OS do you use? Does it have case insensitive file system?

Looks like #100763

**Comment by onlywanna** [comment]
My operating system is Microsoft Windows 1909 version.

I turn off my vscode and restart it twice.
It behaves normally.

**Comment by onlywanna** [comment]
VSCode Version: 1.47.3

**Comment by onlywanna** [comment]
> /needsMoreInfo
> 
> What OS do you use? Does it have case insensitive file system?
> 
> Looks like #100763

![image](https://user-images.githubusercontent.com/34205436/89634503-18460900-d8d8-11ea-8250-e4ba043b7877.png)

**Comment by jrieken** [comment]
This element with the wrong casing is provided by the vue extension it it seems that it hasn't caught up with the change.
