### ISSUE TITLE
I can't find the documentation about the codeActionsOnSave feature 

### ISSUE THREAD

**Issue by Luxcium** [microsoft/vscode#104219]
I feel like I will create a duplicate but I know than @mjbvz will be able to point me to it so I can find the answer to my question unless I go on youtube and look at Matt videos... I mention that because I know indeed a video that would answer to my question but I would like to have the authoritative source...

How can I find the list of the vscode default behaviour for  `"editor.codeActionsOnSave": [/* ... */]`, 
and is it possible to have an autocompletion in the near future?

I fell like a little more documentation should be available and I am not sure how to ask you that I know you are working hard to make it perfect and that maybe I should have searched more ...

**Comment by Luxcium** [comment]
This is the video I was referring to... But I feel like I should be able to find that information from the vscode docs and I was unable to ... [VS Code tips: Add missing imports on save for JavaScript and TypeScript ](https://www.youtube.com/watch?v=Hd8yMapJCAw) by Matt Bierner on the Code 2020 Youtube channel

**Comment by gunadhya** [comment]
Hi @mjbvz , I'd like to work on this.

**Comment by KDharmindar** [comment]
Hello @gunadhya have you been able to fix this? Are you working on this?

**Comment by gunadhya** [comment]
@KDharmindar Hi, yes I'm working on it.

So looking through the vscode-docs I was able to find `codeActionsOnSave ` feature on this [commit](https://github.com/microsoft/vscode-docs/commit/792ded4db54bfc4f6acfac32c9fb5390ef3f5d5f#diff-33003541724706f07c97e9ba009323aeR197)
and I confirmed it by going on the main site and found references to `codeActionsOnSave` [here](https://code.visualstudio.com/docs/languages/javascript#_organize-imports) and [here](https://code.visualstudio.com/docs/getstarted/settings#_default-settings) and some other places but I could not find [missing imports](https://code.visualstudio.com/updates/v1_46#_add-all-missing-imports-source-action) and [fixall](https://code.visualstudio.com/updates/v1_46#_add-all-missing-imports-source-action) on the docs but they do exist in the update releases page as referenced above.
So should I transfer those to the docs? And are any other changes needed ?

**Comment by mjbvz** [comment]
Yes, there should likely just be a new section in one of the docs pages for `codeActionsOnSave`. The fixes all come from extensions but we can document the couple of built-in ones

**Comment by gunadhya** [comment]
So should I add the `codeActionOnSave ` documentation after this [section](https://github.com/microsoft/vscode-docs/blob/559f854fd9a0edc8a73ae6eb32e8a2e8471eec92/docs/languages/javascript.md#organize-imports ) on both [javascript.md](https://github.com/microsoft/vscode-docs/blob/559f854fd9a0edc8a73ae6eb32e8a2e8471eec92/docs/languages/javascript.md  ) and [typescript.md](https://github.com/microsoft/vscode-docs/blob/559f854fd9a0edc8a73ae6eb32e8a2e8471eec92/docs/languages/typescript.md)
vscode-docs or any other suggestions?

**Comment by mjbvz** [comment]
Sure, that sounds good

**Comment by Luxcium** [comment]
What about the fixes (or actions) that come from extensions? will it be possible to have support somehow in the JSON Validation (in settings.json file)? I mean I can look at the Feature Contribution of each of the installed extensions... At this moment I think only ESLint contributes (from my installed extensions)  but I have 57 extensions installed and I would like to have a quick way to know what is possible to include in my codeActionsOnSave array... What should I expect? is it to the creator of the extension to implement something to make this work?  because I already have support to find `"eslint.codeActionsOnSave.mode"` with the autocompletion system but not for `    "source.fixAll.eslint"` in the `"editor.codeActionsOnSave"`
 
![Screenshot_20200814_075718](https://user-images.githubusercontent.com/42672814/90247112-eebf3d00-de03-11ea-8854-10046d4fccd7.png)
![Screenshot_20200814_075731](https://user-images.githubusercontent.com/42672814/90247113-ef57d380-de03-11ea-831a-69e552c5ce36.png)

**Comment by Luxcium** [comment]
These settings are probably redundant I never noticed it before ... 

![Screenshot_20200814_075806](https://user-images.githubusercontent.com/42672814/90247257-38a82300-de04-11ea-91c6-fba33e90c0dc.png)
