### ISSUE TITLE
Ripgrep search provider incorrectly treats `search.exclude` globs as non-strict.

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#104204]
The `include` and `exclude` fields in the search view/search editor use a "loose" glob interpretation: 
```test -> **/test/**, **/test```
```.test -> **/*.test```
etc.

`search.exclude` however uses strict globs. However, the ripgrep search provider seems to be interpreting the globs in `search.exclude` loosely:

For instance: Try searching "searchEditor" in vscode standard:
![image](https://user-images.githubusercontent.com/8586769/89565069-d2ebe380-d7d2-11ea-8c36-d65575bb47f7.png)

Now try adding `"**/workbench": true` to search.exclude. This *should* only remove results with basename workbench. In actuality, it filters out all of `**/workbench/**`:
![image](https://user-images.githubusercontent.com/8586769/89565158-fca50a80-d7d2-11ea-9af4-d3fb318036a9.png)

**Comment by roblourens** [comment]
Oh, I see. From rg's perspective, it will not search inside `workbench/` as it walks the folder tree because the workbench folder itself is excluded. I don't think we can even override this. vscode has always been this way and I wouldn't want to change it now.

**Comment by JacksonKearl** [comment]
Hm I see. cc @burntsushi for visiblity, but will close out of scope for now.
