### ISSUE TITLE
In the find tree view, entering on results no longer brings focus to the editor

### ISSUE THREAD

**Issue by Neurrone** [microsoft/vscode#104299]
/CC @isidorn 

Issue Type: <b>Bug</b>

1. Press ctrl+shift+f and search for something for the current workspace.
2. Tab thrice to move to the tree view of results. Press enter on a result.

Expected: moves focus to the line in the editor where the match was found
Actual: focus does not move.

This is a recent regression because I remember this working for me as recently as this week.

VS Code version: Code - Insiders 1.48.0-insider (2277c8e2a3e1cc630a6397301ba54a1dccd8a60d, 2020-08-07T11:32:09.993Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.13GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|17%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
notes|can|1.0.1
vscode-markdownlint|Dav|0.36.2
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
foam-vscode|foa|0.3.1
go|gol|0.16.1
rest-client|hum|0.24.1
vscode-markdown-notes|kor|0.0.13
python|ms-|2020.7.96456
remote-wsl|ms-|0.44.4
cpptools|ms-|0.29.0
vsnotes|pat|0.7.1
rust|rus|0.7.8
markdown-preview-enhanced|shd|0.5.12
code-spell-checker|str|1.9.0
markdown-links|tch|0.7.0
vscode-webhint|web|1.5.7
markdown-all-in-one|yzh|3.2.0

</details>

**Comment by Neurrone** [comment]
actually, this is not just happening in that particular instance, I believe its probably all instances where tree views like this are used, so is somewhat noticeable for me now.

Another instance of this are error / warnings. When you move focus to them and press enter, focus does not move to the corresponding place in the editor as expected but stays in the tree.

**Comment by isidorn** [comment]
Yeah this is a regression. Enter should always pass focus to the editor.
I can reproduce this problem. Assigning to July so we try to fix if possible before the release and forwarding for now to @joaomoreno 
Feel free to assign back to me
