### ISSUE TITLE
"Content is newer on disk" keeps showing up even though I'm not editing anything

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#104209]
I have a github issues notebook open, and I dont think I'm interacting with it really, and certainly not in two locations, but I keep getting this popup...
![image](https://user-images.githubusercontent.com/8586769/89589130-df376700-d7f9-11ea-8e2b-eadc7614e120.png)

**Comment by JacksonKearl** [comment]
Steps: 
1) Edit notebook and save.
2) reset file via git (Note: reset doesn't appear in the editor)
3) Attempt to save notebook


So maybe notebook isnt listening on the ondidchange event enough?

**Comment by rebornix** [comment]
@JacksonKearl isn't the behavior the same as text files? When the file on disk is different with what you have in the editor, *Save* will trigger the notification?

**Comment by JacksonKearl** [comment]
The problem is when I revert the file in Git, the notebook isn't automatically updated to reflect that.

**Comment by rebornix** [comment]
@JacksonKearl that's reasonable. non-dirty document should behave like you said.

**Comment by rebornix** [comment]
My first attempt of fixing this issue https://github.com/microsoft/vscode/pull/104677 but figured out it's not that simple.

In the PR, we add a file watch on the resource and when it's newer than the document in the workspace (by checking file stats), we will reload the document. However, in GitHub Issue Notebook, outputs are not saved to disk, meaning if you run a cell and get a list of results, your document is not dirty. Thus when a `git revert` happens and we resolve the latest the `NotebookData` from the content provider, we can't just replace the document in the workspace with the new data as it doesn't contain the outputs, replacing means data loss (even though the outputs are never saved to disk, it's a data loss of current session).

Ideally we should merge the data, but only the content provider knows how to correctly merge them. This is no different from extension listening to content change on disk and then apply them to the notebook document through editing API. For short, content provider is the best one to implement this feature.

Another proposal from @roblourens is showing a notification when we detect file changes and ask if users want to reload. I'm wondering if it's similar to the save notification we have right now.

**Comment by JacksonKearl** [comment]
Does the notebook provider get an event when the document changes on disk? It could be responsible for figuring out what to do (either merge changes or show the dialog). 

Alternatively, the dialog text could just be simplified... currently it doesn't really make sense to me. 

```

**Comment by JacksonKearl** [comment]
Does the notebook provider get an event when the document changes on disk? It could be responsible for figuring out what to do (either merge changes or show the dialog). 

Alternatively, the dialog text could just be simplified... currently it doesn't really make sense to me. 

>The content of the file is newer [what content is newer than what?]. Please revert your version with the file contents [<- this phrase isn't super grammatically clear to me] or overwrite the content of the file with your changes.

> `revert` [<- not really accurate, we're "revert"ing the unchanged file *forward* to the version on disk? We're kinda *overwrite*-ing the editor with the file on disk.]
> `overwrite` [<- also strange, how can I overwrite if I haven't made changes? This is really *revert*ing the file on disk back to the editor's state...]

It almost feels like the command labels are flipped from what they should be, but it's odd either way...

Maybe if the editor is non-dirty we could instead show something like:

> This notebook file has been externally modified. Refresh to view the latest changes. 

> `refresh`

? 

Then at least it's one button (less cognitive load), and it's very clear what it will do.

**Comment by rebornix** [comment]
This would be handled by the file service / working copy consolidation work.
