### ISSUE TITLE
pwd mounting in Docker doesn't seem to work

### ISSUE THREAD

**Issue by WyriHaximus** [microsoft/vscode#104295]
In Github Codespaces using something like ```docker run --rm -w `pwd` -v `pwd`:`pwd` -it wyrihaximusnet/php:7.4-zts-alpine3.12-dev ls -lasth``` Doesn't seem to mount pwd in the docker images you're running.

**Comment by chrmarti** [comment]
Continuing in https://github.com/MicrosoftDocs/vscodespaces/issues/748.
