### ISSUE TITLE
may be i made a mistake,i don't know what happen, just use the sync setting extension.

### ISSUE THREAD

**Issue by apawn** [Microsoft/vscode#10420]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by apawn** [comment]
ERROR ! Logged In Console (Help menu > Toggle Developer Tools). Please open an issue in Github Repo using 'Sync : Open Issue' command.
and it tell me that if i type shift+alt+u or shift + alt + d.
i can't sync the seting
i need help.
thank you.

**Comment by jrieken** [comment]
Please file against the extension

**Comment by apawn** [comment]
oh  i use the visual studio code setting sync.
and first i made a mistake. it want me to enter the token key,but i type 'Sync',and then ie begin alert the error msg.

**Comment by jrieken** [comment]
@apawn This is still the wrong repository we don't a setting sync feature with VS Code. On the marketplace you can find the right repo to file issues for that extension.

![screen shot 2016-08-11 at 12 57 39](https://cloud.githubusercontent.com/assets/1794099/17586651/4d3ff7de-5fc3-11e6-961c-cd98deb400c2.png)

**Comment by apawn** [comment]
thank you. i will try , and  file the result.
