### ISSUE TITLE
error window on `code` command: the following argument /c was not expected

### ISSUE THREAD

**Issue by sanbox-irl** [microsoft/vscode#104221]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Be on my computer
2. Run `code` in any terminal
3. Get an amorphous window popup:

![image](https://user-images.githubusercontent.com/31973761/89613624-871f5580-d837-11ea-8da2-9d89d4c28081.png)

I have no idea what this is! Running `code --help` gets the same message, but I suspect that this isn't from vsc at all

Does this issue occur when all extensions are disabled?: Yes

**Comment by sanbox-irl** [comment]
More specifically: looks like

```
"%~dp0..\Code.exe" "%~dp0..\resources\app\out\cli.js" %*
```

triggers an error as well. "cannot find file specified". To be honest, I'm so unfamiliar with cmd issues that I'm not sure how to parse that string at all, and googling it gives me...some results, but perhaps I just don't have the brainpower to understand some string concatenations.

I'm calling this from Powershell 7, if that makes any difference

**Comment by sanbox-irl** [comment]
As an additional hint (though this may be completely unrelated) -- I am now seeing this little popup in my terminal, with this text accompanying:

```
Extensions want to make the following changes to the terminal's environment:

VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-79850c0a63-sock
GIT_ASKPASS=c:\Users\jjspi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh
VSCODE_GIT_ASKPASS_NODE=C:\Users\jjspi\AppData\Local\Programs\Microsoft VS Code\Code.exe
VSCODE_GIT_ASKPASS_MAIN=c:\Users\jjspi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js
```

I think this is some deep weird git thing and I don't know what's going on at all

**Comment by Tyriar** [comment]
> Extensions want to make the following changes to the terminal's environment:

This is by design but it needs some UX work to better communicate there is no issue: https://github.com/microsoft/vscode/issues/102727

**Comment by Tyriar** [comment]
@joaomoreno any ideas where this `/c` could come from in the CLI?

**Comment by sanbox-irl** [comment]
it *also* appears when I try to open an external editor using the shortcut. that setting is:
```
    "terminal.external.windowsExec": "wt.exe",
```

and then the new windows terminal fails to load...this could be real the cause, tho I don't know how the code command would invoke this

**Comment by sanbox-irl** [comment]
ehhh maybe not.

revert that setting to the default `**C:\WINDOWS\System32\cmd.exe**` doesn't make a difference -- same error message, and cmd doesn't come up

**Comment by sanbox-irl** [comment]
Hey guys -- I'm going to go ahead and close this.

After much JOY I believe it is related to https://github.com/electron-userland/electron-prebuilt/issues/263

Or whatever hte underlying cause is.
