### ISSUE TITLE
Unexpected behavier when close a file

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#10429]
- VSCode Version: macOS 10.12
- OS Version: 1.4.9

Steps to Reproduce:

1.  The file list in sidebar is so long that produce a scroll bar.
2.  Close file in editor.
3. Then focus in sidebar will jump to bottom.

**Comment by isidorn** [comment]
This is as designed, once you close a file in the Open Editors list we will reveal and focus the currently opened file.
If you think this is unexpected please provide a short gif video showing this issue and I will reopen this issue.

**Comment by leaxoy** [comment]
Thanks！  @isidorn 😁
