### ISSUE TITLE
Live Server extension no longer works correctly after update.

### ISSUE THREAD

**Issue by ASLAVA** [microsoft/vscode#104264]
- VSCode Version: 1.47.3
- OS Version: Linux x64 5.4.55-1-lts

Steps to Reproduce:

1. Install Live Server, Go Live
2. Server does not auto-update after update. Must save file after each change for live server to show changes

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by DEVANGYDV** [comment]
Server does not auto-update after update
