### ISSUE TITLE
markdown internal file links don't work anymore

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/vscode#104267]
- VSCode Version: Insiders
- OS Version: not OS specific.

Steps to Reproduce:

1. Open any markdown file with relative file links
2. Click open the link, it doesn't open the file instead it opens the file explorer and focuses document open in the editor.

We're using webview to show markdown files. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
Note that this is specifically for non-md files.

Attached some [sample files](https://github.com/microsoft/vscode/files/5043401/issue.zip) to demonstrate the issue. In VS Code stable both links in index.md open the respective files. In Insiders only the markdown link works.

The change that seems to have broken this is https://github.com/microsoft/vscode/commit/fdf23dc5f95f4a17b246dbebc9af14dab5043334#diff-ac54e693c637dc86bf104bdc419aa7dc - OpenDocumentLinkArgs was modified to take in path as an object (URI?) but the line calling it is still passing in a string https://github.com/microsoft/vscode/commit/fdf23dc5f95f4a17b246dbebc9af14dab5043334#diff-fb00b7760468d6ca1cf7843106d5015fR411

**Comment by Maxim-Mazurok** [comment]
I'm experiencing the same issue in the stable VS Code.

Version: 1.48.1 (user setup)
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:12:13.244Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by Charles-Gagnon** [comment]
This doesn't seem to repro for me either anymore.

@MaddyDev Could you verify whether you can repro it and if you can't close this out?

**Comment by Maxim-Mazurok** [comment]
@Charles-Gagnon it works for me now

**Comment by MaddyDev** [comment]
@leemun1 It doesn't repro for me either but can you point me to which change fixed this. Thanks.

**Comment by leemun1** [comment]
@MaddyDev It looks like [this commit](https://github.com/microsoft/vscode/commit/24b28f57be22fe3029cb17a1dd72d8d9c2d6468b) fixed the issue

**Comment by MaddyDev** [comment]
Thanks @leemun1. Closing this since we can't repro the issue anymore.
