### ISSUE TITLE
Collapse Chevron - Native Notebooks Editor

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#104260]
Users during Python Extension Native Notebooks QP (5/8) failed usability test on collapse cells. 

Potential solution is to make the chevron marker larger or more bold.

**Comment by misolori** [comment]
During the QP studies we had the chevrons always hidden except on hover, which I believe made them really hard to discover. After the studies I did change this behavior (via https://github.com/microsoft/vscode/commit/3bd820b15c79eebf0d5a86e53d8ca189b7a98c6b) to always be visible. Let's see how this improves the discoverability.
