### ISSUE TITLE
assigning short-cut keys to workspace snippets not working.

### ISSUE THREAD

**Issue by rholland** [microsoft/vscode#104279]
The example json entry from docs is:
```
  "key": "cmd+k 1",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus",
  "args": {
    "langId": "csharp",
    "name": "myFavSnippet"
  }
```
where langld is the file name of the "json user snippet file".  A workspace snippet file has the name  name.code-snippets.  But assigning keys using that approach does not work. Should it?  I have confirmed that the snippets are found and they work.

**Comment by jrieken** [comment]
This is working for me. Can you share the file in which you define your snippet or update your sample with a dummy snippet
