### ISSUE TITLE
English mixed monospace aberrant

### ISSUE THREAD

**Issue by ifzm** [Microsoft/vscode#10421]
- VSCode Version: 1.4.0
- OS Version: Windows 7 +

![123](https://cloud.githubusercontent.com/assets/12740295/17578418/ecdd4c0a-5fba-11e6-8ab6-ef938091953a.png)

This is Sublime Text 
![321](https://cloud.githubusercontent.com/assets/12740295/17578439/2d6d5aa8-5fbb-11e6-9669-7826e992272e.png)

PS：The same font settings

**Comment by alexandrudima** [comment]
Chromium ultimately renders the text. As a workaround I suggest a different font that enforces monospace CJK characters.

**Comment by ifzm** [comment]
Right.  At present, it's the only way, Such as use " SimSun " ...

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
