### ISSUE TITLE
VSCode behind a corporate Firewall, extensions show up “Failed to install”

### ISSUE THREAD

**Issue by Schizo** [microsoft/vscode#104203]
- VSCode Version: 1.47.2
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Sit behind a corporate firewall
2. Whitelist `*.gallerycdn.vsassets.io *.visualstudio.com`

Does this issue occur when all extensions are disabled?: Yes

I first tried the SO Question, but I didn't get a response wihtin a week. We are sitting behind a corporate firewall and we did white list `*.gallerycdn.vsassets.io *.visualstudio.com` which removed all the network errors in the developer tools. However, now we are getting the following message:

`Error: corrupt ZIP: end of central directory record signature not found
Failed to install `eamodio.gitlens`
`

Not sure what else we need to get this working? [SO](https://stackoverflow.com/questions/63224806/vscode-behind-a-corporate-firewall-extensions-show-up-failed-to-install) Question:

**Comment by sandy081** [comment]
The downloaded VSIX will be available in the folder `<user_settings_folder>/../CachedExtensionVSIXs`. Please provide us the VSIX?

Can you also try downloading the VSIX manually from Marketplace and install it? Are you getting the same error? Please compare if both are same.

**Comment by Schizo** [comment]
I just checked those files and they seem to have the html pages downloaded from the firewall instead of the VSIX extensions. How can I figure out, what link vs-code tried to access? In the Developer Tools Network tab, I don't see any blocked entry, but on hitting `install` there mus a procedure pulling data from a 3rd party link?

**Comment by chrmarti** [comment]
You also need to whitelist `az764295.vo.msecnd.net` for the VSIX download. See https://code.visualstudio.com/docs/setup/network for a list of hostnames VS Code might access.
