### ISSUE TITLE
Is it possible to extend exising API 'vscode.extensions.onDidChange()' to 'vscode.extensions.onDidChange(evntType)'?

### ISSUE THREAD

**Issue by caozhaohong** [microsoft/vscode#104283]
I am facing same problem as issue:
    https://github.com/microsoft/vscode/issues/103825

AS-IS: vscode.extensions.onDidChange() can only being called in case 'installed/uninsalled/diable/enable' happened.

TO-BE: I can get onDidChange() only in case 'uninsalled' happened.

My application scenario is:
1) When developer uninsallled my exention, I want to show him a message 'Dear after uninstalled this exention, please be informed you should do xxxx.'
2) But in case my extension is installed or disabled or enabled, I no need prompt message.
3) So I need  'vscode.extensions.onDidChange(evntType=para1, extension=para2)' then I can :
         if eventType=Uninstlled & para2='MyExtension‘’:
                I can do something here;
         else //means my extension is instlled/Enabled/Disabled, or any other extensions is Uninstalled/instlled/Enabled/Disabled
                I will do nothing here

Thank u.

**Comment by alexdima** [comment]
This is not possible. It is not possible to observe your own extension being disabled while your extension is executing. The reason for that is that uninstalling an activated extension will not uninstall it immediately, it will mark it for uninstalling and will uninstall it next time VS Code starts up.
