### ISSUE TITLE
File list refresh doesn't work

### ISSUE THREAD

**Issue by zidad** [Microsoft/vscode#10428]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Remove files using shell (rm **/*.orig in my case)
2. Project file list doesn't refresh (*.orig files are still visible, showing an error when opening)
3. Manual refresh using the refresh button doesn't work either (files still show up in the list)

**Comment by bpasero** [comment]
@zidad can you run "code --verbose" and attach the output you get when doing this operation from the developer console?

**Comment by zidad** [comment]
Hi @bpasero,

I've restarted the editor, and now I can't seem to reproduce it anymore, maybe temporary corruption of the instance...

I'll reopen if it happens again, thanks!

**Comment by keverw** [comment]
Interesting I noticed on macOS using VSCode Version 1.6.1 (1.6.1) if I drag a file into my project or drag files from the root of my project to sub folders the sidebar doesn't update until I restart the app...
