### ISSUE TITLE
Action builds are failing on fork

### ISSUE THREAD

**Issue by hey24sheep** [microsoft/vscode#104218]
- VSCode Version: Latest
- OS Version: Windows 10 Latest

Steps to Reproduce:

1. Fork vscode

After forking, workflow actions are auto queued. They fail with error

Run failed for master (20cba51)
Repository: hey24sheep/vscode
Workflow: Latest Release Monitor
Duration: 23.0 seconds
Finished: 2020-08-07 04:44:18 UTC

##[warning]Unexpected input(s) 'appInsightsKey', valid inputs are ['token', 'storageKey']
Run ./actions/latest-release-monitor
  with:
/home/runner/work/vscode/vscode/actions/node_modules/@actions/core/lib/core.js:76
        throw new Error(`Input required and not supplied: ${name}`);

-Another error with Deep Classifier: Runner

Run ./actions/classifier-deep/apply/fetch-sources
  with:
    from: 40
    until: 5
    configPath: classifier
    blobContainerName: vscode-issue-classifier
/home/runner/work/vscode/vscode/actions/node_modules/@actions/core/lib/core.js:76
        throw new Error(`Input required and not supplied: ${name}`);

**Comment by JacksonKearl** [comment]
Thanks for reporting this!

I'm not sure what the correct approach is here... forks probably don't need any of our actions - while I could add logic to make them exit immediately on forks, they'd still be running briefly and consuming your action minute quotas. 

IMO it'd be better if GitHub had a way to explicitly include/exclude actions on forking, in the time being your best bet might be to just delete the `.github/workflows` directory, keeping in mind that you'll need to not include that change in any patches you might upstream.

If you have suggestions I'd be happy to hear!

**Comment by hey24sheep** [comment]
Thanks @JacksonKearl , for now, I have disabled Actions in settings for my fork but I created this bug cuz I wasn't expecting to get actions setup for your branch to run on mine. As a result it created this error regarding keys/secret. So, I thought maybe someone know some other solution to this issue. 

My solution : Disable "Actions" in repository settings

Any other elegant or good solution would be awesome.

**Comment by JacksonKearl** [comment]
I think disabling actions in the repository settings is the correct solution here, I didn't know that was an option. 

In that case, I'd prefer to leave in the errors to prompt forkers to disable actions rather than silently consume action minutes.

**Comment by hey24sheep** [comment]
@JacksonKearl can we have a note or something in contribution guide regarding this? Would be helpful.

**Comment by JacksonKearl** [comment]
I have added a note here https://github.com/microsoft/vscode/wiki/How-to-Contribute#getting-the-sources

**Comment by hey24sheep** [comment]
Thanks 👍
