### ISSUE TITLE
How to stop VS Code to duplicate files? (FileName 2.css)

### ISSUE THREAD

**Issue by rafaelperozin** [microsoft/vscode#104234]
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (2 wks ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

I'm using VSCode in Mac and usually, they auto duplicate some file randomly. I suspect that could be related to some git config or command. As you can see, this time the VisualStudio Code generated only 263 files with 2 at the end of the name, but sometimes this happens to 3,000 or 5,000 files.

Why does this happen?

How can I stop it?

You can see some screenshots and more info at https://stackoverflow.com/questions/62692264/how-to-stop-vs-code-to-duplicate-files-filename-2-css

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Does this happed in latest stable build 1.47 ?
