### ISSUE TITLE
Ncurses reports that VSCode integrated terminal can change colors, but redefining colors has no effect

### ISSUE THREAD

**Issue by akacyra** [microsoft/vscode#104291]
VS Code version: Code - OSS 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-30T16:19:47.070Z)
OS version: Linux x64 5.7.11-arch1-1

Steps to Reproduce:

1. Compile the minimal reproduction program:
```
#include <curses.h>
int main() {
    initscr();
    start_color();
    if (has_colors() == TRUE && can_change_color() == TRUE) {
        init_color(1, 0, 0, 1000); // redefine red to blue
        init_pair(1, 1, 0); // fg=blue, bg=black
        attron(COLOR_PAIR(1));
        printw("Hello, world!"); // should be blue
        attroff(COLOR_PAIR(1));
        refresh();
        getch();
    }
    endwin();
    return 0;
}
```
`gcc repro.c -lncurses -o repro.out`
This program uses Ncurses to redefine the default terminal red color to blue and prints a string with the new color, only if the terminal (as reported by Ncurses) supports colors and redefining colors.

2. Run `repro.out` in an external terminal. The text should be blue (assuming your terminal supports colors and redefining them).
3. Run `repro.out` in the VSCode integrated terminal. The text will be red (bug).

From the integrated terminal:
```
echo $TERM
> xterm-256color
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I'm guessing xterm.js doesn't (yet) support this. Can you enable [escape sequence logging](https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging) and check the console for what sequences are sent by ncurses?

**Comment by akacyra** [comment]
Escape sequence log:
```
/usr/lib/code/node_modules.asar/xterm/lib/xterm.js:1 xterm.js: parsing data ./repro.out 
/usr/lib/code/node_modules.asar/xterm/lib/xterm.js:1 xterm.js: sending data "
" [13]
/usr/lib/code/node_modules.asar/xterm/lib/xterm.js:1 xterm.js: parsing data 

/usr/lib/code/node_modules.asar/xterm/lib/xterm.js:1 xterm.js: parsing data [?1049h[22;0;0t[1;17r(B[m[4l[?7h[39;49m]4;1;rgb:00/00/FF\[39;49m[37m[40m[H[2J[31m[40mHello, world!(B[m[39;49m[37m[40m
/usr/lib/code/node_modules.asar/xterm/lib/xterm.js:1 xterm.js: Unknown OSC code:  {identifier: 4, action: "START", data: undefined}
/usr/lib/code/node_modules.asar/xterm/lib/xterm.js:1 xterm.js: Unknown OSC code:  {identifier: 4, action: "PUT", data: "1;rgb:00/00/FF"}
/usr/lib/code/node_modules.asar/xterm/lib/xterm.js:1 xterm.js: Unknown OSC code:  {identifier: 4, action: "END", data: true}

```

**Comment by Tyriar** [comment]
Moving upstream https://github.com/xtermjs/xterm.js/issues/3036

/duplicate
