### ISSUE TITLE
Git Indentation Line in collapsing with the Icons

### ISSUE THREAD

**Issue by pmkary** [microsoft/vscode#104257]
### Version
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

### Problem

I guess the image is worth all the words :) The indentation line and all the icons are in bad place:

<img width="412" src="https://user-images.githubusercontent.com/2157285/89669423-acbe6480-d8f4-11ea-9cab-9ffaf0e3ed6a.png">

**Comment by joaomoreno** [comment]
This is bound to happen with the default indentation level. Feel free to increase the indentation level with the `workbench.tree.indent` setting.
