### ISSUE TITLE
Typescript debugger "broken" on 1.47.x and 1.48.0-insider, working up to 1.46.1 (Ubuntu)

### ISSUE THREAD

**Issue by andreafdaf** [microsoft/vscode#104239]
As the title says, looks like Typescript debugger is "broken" on 1.47.x and 1.48.0-insider, was working up to 1.46.1

- VSCode Version: 1.48.0-insider, 1.47.3-1595520028, 1.47.2-1594837870, 1.47.1-1594686231
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. I have the following debug configuration, I'm not using the tsc task inside the debug config because I keep tsc watch running on the background:
```
{
  "type": "node",
  "request": "launch",
  "name": "API",
  "program": "${workspaceFolder}/../api/src/index.ts",
  "cwd": "${workspaceFolder}/../api",
  "outFiles": ["${workspaceFolder}/../api/build/**/*.js"],
  "sourceMaps": true,
  "protocol": "inspector",
  "env": {
    "MONGODB_URI": "x",
    "EMAILS_QUEUE": "x",
    "AWS_ACCESS_KEY_ID": "x",
    "AWS_SECRET_ACCESS_KEY": "x",
    "AWS_REGION": "x"
  }
}
```
2. It works fine on VSCode up to 1.46.1-159242889, on 1.47.x and 1.48.0-insider the debugger crashes telling me:
```
/home/user/workspace/api/src/index.ts:1
import express = require('express')
^^^^^^

SyntaxError: Cannot use import statement outside a module
```
Like it is reading the actual Typescript file and trying to execute it with node directly

As simple as that, I've been using this config for quite some time now and it always worked before 1.47.x

Does this issue occur when all extensions are disabled?: Yes

**Comment by el** [comment]
I can confirm this issue is present in `VS Code 1.47.3` and `Ubuntu 18.04.4`
![image](https://user-images.githubusercontent.com/1488164/89659792-0add4e80-d8d9-11ea-8768-4784ba65682a.png)

**Comment by connor4312** [comment]
```
  "program": "${workspaceFolder}/../api/src/index.ts",
```

You can fix this by pointing your program at the compiled file, rather than the source file.

/duplicate https://github.com/microsoft/vscode/issues/102873
