### ISSUE TITLE
Bash shell syntax highlighting broken by here document in backticks

### ISSUE THREAD

**Issue by steveblomeley** [microsoft/vscode#104201]
Issue Type: <b>Bug</b>

Example: editing a bash shell script that captures the output of a SQL command run within a heredoc:

1    #!/bin/bash
2    result=`` ` ``sqlplus -s user/pwd@db <<EOF
3        some sql query;
4        exit
5    EOF`` ` ``
6
7    bash commands
8    more bash commands
 
At line 2, syntax highlighting is disabled after the first backtick ` character, and remains disabled throughout the heredoc

EXPECTED BEHAVIOUR: At line 5, would expect syntax highlighting to become enabled after the end of the heredoc, and the enclosing backtick

ACTUAL BEHAVIOUR: syntax highlight is disabled from line 2 for the rest of the shell script, including valid bash commands after the heredoc has been terminated.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (7.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2901)|
|Memory (System)|15.90GB (7.79GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.44.4

</details>

**Comment by alexr00** [comment]
@steveblomeley can you provide a full copy-pastable example?
