### ISSUE TITLE
Drag folded cells + undo, redo

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#104263]
![Aug-07-2020 10-54-13](https://user-images.githubusercontent.com/323878/89674069-5c1b1d00-d89c-11ea-9d85-233b9ed46ef8.gif)

- Follow the steps for the first item in https://github.com/microsoft/vscode/issues/99882
- Drag the cell under 2, it works
- Undo, it's correct
- Redo, now cells are out of order

**Comment by roblourens** [comment]
This doesn't repro every time

**Comment by rebornix** [comment]
Fixed via bdfef57b0a02f046c1cd713126f7641a053a3c21
