### ISSUE TITLE
Pressing Enter on "problem" does not put focus to editor

### ISSUE THREAD

**Issue by payonel** [microsoft/vscode#104287]
With a "problem" selected and the Problems view is in focus, pressing ENTER does not switch the focus to the related line of code in the editor. Double clicking works

Notes:
1. The line of code is selected in the edit window - each time a new problem is selected
2. Again, double click works. But I like to work without a mouse as much as possible

I really think this is a recent problem; I really think this used to work.

Version: 1.48.0-insider
Commit: 2277c8e2a3e1cc630a6397301ba54a1dccd8a60d
Date: 2020-08-07T12:51:53.850Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.1.0-050100-generic
Steps to Reproduce:

1. run a task with a problem matcher (i use c++, gcc, and a simple makefile)
2. shift+contrl+m to focus problem window
3. arrow key to select a problem
4. press [ENTER] <-- 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by sandy081** [comment]
@joaomoreno I also see this is not working for search, Is there something changed in underlying `onDidOpen` event?

**Comment by joaomoreno** [comment]
This is now fixed.
