### ISSUE TITLE
When I rename a branch in git and use vscode's git it seems to take the old branch after renaming

### ISSUE THREAD

**Issue by Wellers0n** [microsoft/vscode#104253]
- VSCode **Version: 1.47.3**
- OS Version: **ubuntu 18.4**

Steps to Reproduce:

1. Use a branch with name: plug
2. rename this branch to: plugin (use: git branch -m plugin)
3. then use git in vscode to commit. It will commit to the old branch

Does this issue occur when all extensions are disabled?: No

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?
