### ISSUE TITLE
Publish to GitHub appears to be no-op

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#104248]
verifying https://github.com/microsoft/vscode/issues/101795

1. Create new folder
2. Open folder in VS Code
3. Add a file hellofile.js, don't add anything to the file
4. SCM view -> Publish to Github
5. Nothing appears to happen

![recording (12)](https://user-images.githubusercontent.com/38270282/89655236-170ddf80-d8ca-11ea-922c-9c9c04aaa0ae.gif)

**Comment by alexr00** [comment]
Nothing in the git or GitHub Athentication output.

**Comment by joaomoreno** [comment]
Can you check devtools?

**Comment by joaomoreno** [comment]
Great catch, I broke it this week!
