### ISSUE TITLE
Code crashes all conversions

### ISSUE THREAD

**Issue by SuperNova-beep** [microsoft/vscode#104233]
We have written the needed data into your clipboard because it was too
Issue Type: <b>Bug</b>

When I use this command : 
double cash;
cash = Convert.ToDouble(Console.ReadKey());

It crashes the whole conversion system,
It then says this :
Exception has occurred: CLR/System.InvalidCastException
An unhandled exception of type 'System.InvalidCastException' occurred in System.Private.CoreLib.dll: 'Unable to cast object of type 'System.ConsoleKeyInfo' to type 'System.IConvertible'.'

I use C# 

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3530  @ 2.16GHz (4 x 2167)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.22.1
vscode-icons|vsc|10.2.0

</details>
 large to send. Please paste.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please specify how it's related to VS Code editor itself?

Looks like it some runtime problem which is not related to editor.
