### ISSUE TITLE
The command "install 'code' command in path" cannot be found.

### ISSUE THREAD

**Issue by lonelam** [microsoft/vscode#104294]
Issue Type: <b>Bug</b>

The command "install 'code' command in path" cannot be found.
I press ctrl+shift+p, and search with key words. the command cannot be found as usual.
![image](https://user-images.githubusercontent.com/16681599/89710130-fd949280-d9b2-11ea-989d-626b1bcc8fec.png)

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (54.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by joaomoreno** [comment]
This command is only available on macOS for which there is no installer. On Windows, the installer places Code on the path.
