### ISSUE TITLE
Notebook execution hangs even after output completes

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#104262]
![image](https://user-images.githubusercontent.com/35271042/89672146-190b7a80-d899-11ea-9d4c-6c5288962e37.png)

It's hard to repro this but if you run all cells and then clear all output and re-run a couple of times you will end up in a state where the cell progress hangs even though the output completes. It ends up affecting a lot of cells and hard to tell what's going on:

![image](https://user-images.githubusercontent.com/35271042/89672274-45bf9200-d899-11ea-9bcb-f8d4a92dcc77.png)

**Comment by rebornix** [comment]
Considering that the reproduce steps include "run all cells and then clear all output", I think it might be the Python extension not handling the token cancellation well. cc @DonJayamanne

**Comment by rebornix** [comment]
The next Insiders from master will have logging for execution and metadata change. Once that's out, @misolori can you set the Developer Log Lever to Debug and then try to reproduce? Once you reproduce the issue, you can share the logs from Output (Window) and then we can troubleshoot.

**Comment by roblourens** [comment]
I'm sure it's the same
