### ISSUE TITLE
Preserve the Location ordering in Definition from DefinitionProvider

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#104200]
https://code.visualstudio.com/api/references/vscode-api#Definition

DefinitionProvider for some languages may return a Definition corresponding to multiple Locations if the language allows the definition to spread across multiple locations. Go is one of such languages. For example,  a `package` can be defined with  multiple files.

We cannot assume which one of those many files the user would be interested in, so returning all the file locations is a desirable choice. But when there are multiple files, there can be always a better one to start with. In the `package` definition example, the file that contains the documentation for the package may be a more useful starting point than other files.

Behavior of VS Code when receiving such Definition with multiple Locations is not defined.
I cannot tell how VS Code decided to open one of the location as a result of 'Go to Definition' action, but most of time, that's not one of the best, nor matches the ordering of the provided result.

![image](https://user-images.githubusercontent.com/4999471/89564794-88c32c00-d7eb-11ea-899a-e5b9e31bc046.png)

The definition provider would know what's best to be presented first. So, how about making the ordering significant and clarifying it in the API spec?

**Comment by jrieken** [comment]
We remember the first (*) reference and then sort result by file/folder names. IMO that makes most sense but there might be cases in which we don't use the first reference. Do you `peek` or `gotoAndPeek` mode?

* using the provider sort order (or having a first item) isn't as simple as it sound as the feature is collaborative and allows multiple extensions to define results here. We merge these different sorted results by sorting them on the uri and range.

**Comment by hyangah** [comment]
Thanks @jrieken 

I am observing the same behavior in both `peek` and `goto -> peak` modes. 
The current behavior doesn't seem to choose the first item from the result our language server returned even when there is only one Go definition provider. May be the ordering was changed somewhere from the language client node library to vscode.

I see sorting is not easy, when multiple DefinitionProviders got involved (for some reasons...). We encountered the similar issue with the completion providers. Is it an option to have a provider mark the most preferred one, and when multiple providers are involved, select any of those preferred ones?

**Comment by jrieken** [comment]
> Is it an option to have a provider mark the most preferred one, and when multiple providers are involved, select any of those preferred ones?

The first one should be that preferred location. Can you write down exact steps, e.g do you invoke "Peek Definition" or "Goto Definition"?
