### ISSUE TITLE
Command to reload all VSCode windows at once

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#104220]
I knew `workbench.action.reloadWindow` could reload the current VSCode window, how to reload all windows at once, I searched through the keybindings, but didn't find one.

Some use cases:
1. After upgrading extensions that require reload.
2. VSCode slowed down for unclear reason, trying reload.

**Comment by cyberbiont** [comment]
I'd like to know this too. I'm developing an extension that needs to do exactly this.

**Comment by wenfangdu** [comment]
@cyberbiont Dude, let's upvote this.
