### ISSUE TITLE
Installation on Fedora 32 fails

### ISSUE THREAD

**Issue by Ka0o0** [microsoft/vscode#104231]
**Problem Description**

I'm trying to install VS Code on a Fedora 32 virtual machine and followed the guidlines from [here](https://code.visualstudio.com/docs/setup/linux). 
I receive an invalid checksum error. I also tried to install 1.47.2 but get the same error.
I already tried to clean the dnf caches, removed and readded the repo but still no luck.
Any suggestions on what I might be doing wrong or is there an known error with the yum repository?

<details><summary>Terminal Output</summary>
<p>

```
sudo dnf check-update

sudo dnf install code

Last metadata expiration check: 0:02:05 ago on Fr 07 Aug 2020 10:27:45 CEST.

Last metadata expiration check: 0:02:07 ago on Fr 07 Aug 2020 10:27:45 CEST.

Dependencies resolved.

================================================================================

 Package      Architecture   Version                         Repository    Size

================================================================================

Installing:

 code         x86_64         1.47.3-1595520197.el7           code          86 M



Transaction Summary

================================================================================

Install  1 Package



Total download size: 86 M

Installed size: 256 M

Is this ok [y/N]: y

Downloading Packages:

[MIRROR] code-1.47.3-1595520197.el7.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 9cd4fddf5fd8f4bdd50dde3a9fff12a4fb794d79e942449acf34e99417c4eecb(sha256)  Expected: e5b88133f67e5f04a6c135da69f9acec9840445e7a9516beffc01920d6fbbb41(sha256) 

[MIRROR] code-1.47.3-1595520197.el7.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 1560be0f701a4602ce23b54f36757abc5bc8f7e682df54b31653475d067a3be2(sha256)  Expected: e5b88133f67e5f04a6c135da69f9acec9840445e7a9516beffc01920d6fbbb41(sha256) 

^Cde-1.47.3-15955201 13% [==-                 ] 1.0 MB/s |  11 MB     01:11 ETA

The downloaded packages were saved in cache until the next successful transaction.

You can remove cached packages by executing 'dnf clean packages'.

Error: Error downloading packages:

  Interrupted by a SIGINT signal
```
</p>
</details>

**Environment**
- VSCode Version: 1.47.3
- OS Version: Fedora 32

Does this issue occur when all extensions are disabled?: -

**Comment by Tyriar** [comment]
This worked for me on a fresh VM so it's likely an issue with your environment.

![image](https://user-images.githubusercontent.com/2193314/89807296-43557600-daed-11ea-9962-acff7bdc3155.png)

It's possible it's related to repo geo replication, can you try again today to see if it's fixed, if not check http://packages.microsoft.com/yumrepos/vscode/ to see if 1.47.3 shows up?

![image](https://user-images.githubusercontent.com/2193314/89807435-7566d800-daed-11ea-9c5f-78183e128bf0.png)

Also we'll be releasing a new version this week which typically fixes metadata issues with the repo service we use.

**Comment by Ka0o0** [comment]
I did a metadata update and retried it today and it worked now. I don't know why exactly but anyhow, thanks.
