### ISSUE TITLE
typescript language feature failed 5 times

### ISSUE THREAD

**Issue by mlaopane** [microsoft/vscode#104243]
Issue Type: <b>Bug</b>

Starting VSCode show up the error popup. I have no idea why.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.58GB (7.23GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
cucumberautocomplete|ale|2.15.0
vscode-color|ans|0.4.5
vscode-styled-jsx|bla|1.5.0
vscode-intelephense-client|bme|1.5.3
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.36.2
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
vscode-firefox-debug|fir|2.9.0
terraform|has|2.1.1
graphql-for-vscode|kum|1.15.3
dotenv|mik|1.0.1
vscode-docker|ms-|1.4.1
mssql|ms-|1.9.0
vsliveshare|ms-|1.0.2478
vetur|oct|0.26.1
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.2.0
vscode-graphql|Pri|0.2.14
gruvbox-material|sai|6.3.3
code-settings-sync|Sha|3.4.3
open-in-browser|tec|2.0.0
serverless-ide-vscode|Thr|0.5.26
twig|wha|1.0.2
better-align|wwm|1.1.6
material-theme|zhu|3.8.5

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mlaopane** [comment]
The project's typescript version was `3.9.4`.
By selecting the VSCode typescript version (`3.9.7`), the error stopped occuring.

I'm closing this issue then.

Thanks for your time.
