### ISSUE TITLE
Manually checking for extension update puts VSCode in hang state.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#104222]
Issue Type: <b>Bug</b>

Declaration: I have a lot of extensions installed, most are in a disabled state. I enable them as required for tutorials or to resolve issues in various projects I am part of.

steps to reproduce:
1. install a bunch of extensions (I have 82 at the moment, 22 out of them are enabled rt now, I use most of the extensions on a weekly basis)
2. use the "check for extension updates" from extension tab to see if you have updates available
3. try to click anywhere (menu, file explorer, editors) all should be un-responsive till the time you get the no-updates available or x updates available popup/notification.

my expectations: I am fine with the check itself taking time to complete, however, I feel that the UI should be usable while this check is in progress

Is this happening only because of all the extensions I have?
Is there any solution/fix to this other than "uninstall the extensions"?

VS Code version: Code - Insiders 1.48.0-insider (cfbd1999769f4f08dce29629fb92fdc0fac53829, 2020-08-06T05:59:51.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1000.7
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.1.3
go-nightly|gol|2020.8.521
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.132.0
remote-ssh|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
cordova-tools|msj|1.9.5
debugger-for-chrome|msj|4.12.9
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
sonarlint-vscode|Son|1.17.0
code-spell-checker|str|1.9.0
vscode-stylelint|sty|0.84.0
vscodeintellicode|Vis|1.2.9

</details>

**Comment by sandy081** [comment]
Can you please follow this wiki  https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process and provide us the profile when this slowness happens?

**Comment by sanket-bhalerao** [comment]
@sandy081 where should is attach/send this profile?

**Comment by sandy081** [comment]
Please attach to the issue if it works for you otherwise email to me - sasomava@microsoft.com

**Comment by sanket-bhalerao** [comment]
sent you an email on the email id.

**Comment by heartacker** [comment]
me to
 ![image](https://user-images.githubusercontent.com/1876302/92948755-78f2d380-f48c-11ea-89f8-f874b752a8a3.png)

**Comment by sandy081** [comment]
@sanket-bhalerao We have done some improvements and fixed some memory leaks. Can you please try with our latest insiders and see if you can still reproduce this? If you want to wait for stable release let me know.

You can download insiders from here - https://code.visualstudio.com/insiders/

**Comment by sanket-bhalerao** [comment]
@sandy081 I tried with the latest insiders and I can not reproduce the issue anymore.

**Comment by sandy081** [comment]
Thanks for confirming.
