### ISSUE TITLE
vscode could not formatting huge xml file correctly!

### ISSUE THREAD

**Issue by zardlee1937** [microsoft/vscode#104353]
- VSCode Version: 1.47.3
- OS Version: windows version 1909(build 18363.778)

Steps to Reproduce:

1. open a large xml file. in my case, the file size is bigger than 4m.
2. ctrl+shift+p, type Format Document, then watching your xml code style.

Does this issue occur when all extensions are disabled?: Yes/No
No idea.

**Comment by aeschli** [comment]
VSCode doesn't provide a XML formatter out of the box. You must be using an extension. Please file the issue against the extension that you are using.
