### ISSUE TITLE
Three dots in the settings

### ISSUE THREAD

**Issue by MdFahaad** [microsoft/vscode#104314]
Issue Type: <b>Feature Request</b>

There are no three dots shown on the settings right corner.
I got it to know when my instructor was teaching Python.
I hope you solve my problem.
ThankYou

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
Do you mean you are missing this menu? 

![image](https://user-images.githubusercontent.com/323878/89720407-a082e780-d986-11ea-9279-f9ac76aab921.png)

Can  you share a screenshot of what you are seeing?
