### ISSUE TITLE
Source Control panel More actions folded

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/vscode#104300]
Version: 1.48.0-insider (user setup)
Commit: 2277c8e2a3e1cc630a6397301ba54a1dccd8a60d
Date: 2020-08-07T11:32:09.993Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/5390719/89712933-aef0f380-d9c6-11ea-8708-f4a3e379cdd1.png)

This menu didn't be categorized in the previous VSCode version. Categorize this menu slows down the git action I want to take and it also breaks my muscle memory about a specific common git task.

I report this cause I didn't find a new setting to switch back to the old behavior.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
As a workaround I just published a [simple extension](https://marketplace.visualstudio.com/items?itemName=georgejames.gitfavorites) that adds Pull and Push to the top of the first-level menu.

**Comment by Jack-Works** [comment]
what I used most commonly is "undo last commit" and "drop all changes" cause it's hard to remember which command I should use. Now I add a git alias for it, no longer need use the vscode git menu 😅
