### ISSUE TITLE
Hide Useless path in Terminal !

### ISSUE THREAD

**Issue by RexNext** [microsoft/vscode#104305]
Hi, I think it's better if we have  a shortened path in the terminal, 
and VsCode automatically hide the long path and replacing it by ". . .",  and once mouse over on, show us the long path, 

in my mind, I'd like instead of  this long path
`C:\mainDir\internalDir\otherDir\SecoundDir\EndDir>`
I have to have a short path, something like this
`C:\\\\\EndDir>`
or 
`C:\...\EndDir>`
and once mouse over it, show us the full path.

**Comment by ArturoDent** [comment]
If you are referring to the _command prompt,_ it isn't a vscode issue.  For example, see https://stackoverflow.com/questions/52107170/hiding-the-full-file-path-in-a-powershell-command-prompt-in-vscode/52107556?r=SearchResults&s=1|55.6972#52107556 for changing the command prompt in cmd.exe.  There are similar answers for other shells.

**Comment by RexNext** [comment]
I'm sorry for opening an inappropriate issues

**Comment by ArturVasyliev** [comment]
That's not an issue, but it may be a cool feature.

**Comment by dineshr93** [comment]
This would be a great feature for those who are working with shorter screens
