### ISSUE TITLE
Unable to autocomplete base class methods when trying to override them

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#104313]
When I want to override a method in a subclass, I start typing the base class method's name, but it does not autocomplete.

For example, if I have a base class like

```ts
class Foo {
  protected method() {}
}
```

then when I try to make a base class, like

```ts
class Bar extends Foo {
  meth|
}
```

where my cursor is at the location denoted by `|`, then I do not see any autocomplete suggestions, and if I press `ctrl+space` (in Linux) I see the result "no suggestions".

I'm not sure if this is a bug, or a feature that doesn't exist yet.

**Comment by trusktr** [comment]
I can't reproduce this in this simple [playground example](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oAcBO8AuApsIQCbQC2BeAFvCQBQCUKAvqm6qJDAEJjbQCAD0IA7EjARI0GcuyA).

I reality I have a lot more code, and I'm making heavy use of class-factory mixins. So I think this is a bug that has to do with that.

**Comment by trusktr** [comment]
I've noticed sometimes it works, sometimes it doesn't. I'm unable to reproduce it in playground still, but in my project for some methods it doesn't work. If I figure how to reproduce, I'll report back.

**Comment by mjbvz** [comment]
yes, please share a specific code sample that shows this because I can't reproduce with the original example
