### ISSUE TITLE
Add titlebar proxy icon to Mac version

### ISSUE THREAD

**Issue by ericestes** [microsoft/vscode#104304]
Natively, Mac app titlebars have proxy icons that allow for taking action on the file: seeing its file path, opening any of the folders in that path, dragging to the Finder to move the file in the file system, dragging the file to another app, etc. It'd be great if vscode supported this behavior.

There's also usually a dropdown next to the filename that allows for primarily renaming and moving the file. That'd also be really useful.

**Comment by sbatten** [comment]
@ericestes if you change the setting `window.titleBarStyle` to `native`, does this do what you expect?
