### ISSUE TITLE
Push with Merge Request options

### ISSUE THREAD

**Issue by mani25th** [microsoft/vscode#104344]
Hi all, thanks your contribution to VSCode to community. I would like to request a feature for git support. Try to push menu with merge request parameter. Below is example of git command for merge request.
git push -u origin manibranch -o merge_request.create -o merge_request.target=master -o merge_request.title="Title of Merge Request"

[
<img width="216" alt="Push with Merge Request - Visual Studio Code" src="https://user-images.githubusercontent.com/25317753/89754780-b7087a80-db0f-11ea-8174-8aea2a04db1d.png">
](url)

 If this  menu added in VSCode than it will be very easy for us as developer to use.

Regards,
Mani

**Comment by IllusionMH** [comment]
This one looks like specific for GitLab, and most likely work for GitHub, Bitbucket etc.

Instead you can use extension specific for your repository provider which provides more functions related with provider specific workflows:
**GitHub** https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
**GitLab** https://marketplace.visualstudio.com/items?itemName=GitLab.gitlab-workflow
**Bitbucket** https://marketplace.visualstudio.com/items?itemName=Atlassian.atlascode

**Comment by IllusionMH** [comment]
This one looks like specific for GitLab, and most likely work for GitHub, Bitbucket etc.

Instead you can use extension specific for your repository provider which provides more functions related with provider specific workflows:
**GitHub** https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
**GitLab** https://marketplace.visualstudio.com/items?itemName=GitLab.gitlab-workflow
**Bitbucket** https://marketplace.visualstudio.com/items?itemName=Atlassian.atlascode

/cc @alexr00

**Comment by alexr00** [comment]
@IllusionMH is correct. Please try out one of the repository provider extensions to get functionality like that!
