### ISSUE TITLE
Backspace in soft keyboard can't work in editor of vscode(terminal and other places works well) in a android browser. But physical keyboard(bluetooth or wired connected to mobile) works well in editor. This issue may related to android keyboard mechanism.

### ISSUE THREAD

**Issue by ramumanavalan** [microsoft/vscode#104336]
same issue, backspace in soft keyboard can't work in editor of vscode(terminal and other places works well) in a android browser. But physical keyboard(bluetooth or wired connected to mobile) works well in editor. This issue may related to android keyboard mechanism.
You can test the difference between soft keyboard and physical keyboard's behavior in android browser in https://keycode.info
physical keyboard works normally on this website and soft keyboard works not very well.

_Originally posted by @SpinningK in https://github.com/microsoft/vscode/issues/90472#issuecomment-589914851_

You can edit your settings.json to solve this issue
"keyboard.dispatch": "keyCode"

**Comment by alexdima** [comment]
@ramumanavalan Can you please open https://microsoft.github.io/monaco-editor and try backspace in that editor?
