### ISSUE TITLE
Stabilize API `scmResourceState` in `when` clauses for SCM

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#104325]
Finalize the API from https://github.com/microsoft/vscode/issues/86180

https://github.com/microsoft/vscode/blob/f41efe546c5fad1f75ad938c563aa57e28e0014d/src/vs/vscode.proposed.d.ts#L1990

**Comment by jrieken** [comment]
closing this in favour of https://github.com/microsoft/vscode/issues/86180
