### ISSUE TITLE
Feature request: per-language settings

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#10432]
Feature request: per-language settings (split from #6918).

I propose one of the two following feature be added to settings.json:
1. Allow certain editor settings to be configured per language. Example:
```json
"editor.language-specific" : [
  { "language": "java", "tabSize": 4 },
  { "language": ["haskell","**/*.ks"],
    "tabCompletion": false,
    "tabSize": 2
  }
]
```
*or*
2. Support a general mechanism for language-specific configuration. Settings, provided by vscode or extensions, may specify whether they are allowed to be language specific in their schema. Let `workspace.getConfiguration` take an optional language-id argument (where the default behavior is to return the language-agnostic setting). Example:
```json
"language-specific" : [
  { "language": "java",
    "editor.tabSize": 4,
    "myextension.foo": false
  },
  { "language": ["haskell","**/*.ks"],
    "editor.tabCompletion": false,
    "editor.tabSize": 2,
    "myextension.foo": true
  }
]
```

**Comment by siegebell** [comment]
@tobia wrote in #6918:
> For example, I might want to use different values for editor.useTabStops, editor.trimAutoWhitespace, and the proposed editor.fontFeatures when I'm editing Python code vs. JSON files. I think this would make a lot of sense and is already provided by most programming editors, including Sublime Text.

**Comment by jrieken** [comment]
@siegebell https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by siegebell** [comment]
@jrieken 1) per-*language* editor configuration 2) configuration of extensions 3) configuring per-language options *globally* rather than in a bunch of `.editorconfig` files scattered in subdirectories.

I imagine there are a bunch of other properties that would be nice to set but are not supported by `TextEditorOptions` (what EditorConfig wraps)... why is it so limited?

**Comment by alexandrudima** [comment]
@siegebell Can we fold this into #1587 ?

**Comment by siegebell** [comment]
@alexandrudima you're right, this seems to be a dup of #1587.
