### ISSUE TITLE
Visual garbage in user folder

### ISSUE THREAD

**Issue by duzenko** [microsoft/vscode#104355]
Issue Type: <b>Bug</b>

Why is VSCode generating this content in the user profile? 
Is user supposed to do something manually with this?
If yes, give it a readable name.
If no, move it to %APPDATA% or somewhere else.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:31:37.228Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (6.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
delphi-keybindings|ale|9.1.0
angular-schematics|cyr|4.3.0
vscode-firefox-debug|fir|2.9.0
vscode-flatland-icon-theme|geb|0.0.6
cpptools|ms-|0.29.0
shader|sle|1.1.4

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/1481807/89764683-8d465800-dafd-11ea-9cf3-ca98a066434a.png)

**Comment by IllusionMH** [comment]
Looks like this should be covered in #3884 

/assign @Tyriar as author of linked issue
