### ISSUE TITLE
Open with encoding keyboard shortcut.

### ISSUE THREAD

**Issue by Shanduur** [microsoft/vscode#104346]
I'm working with large codebase which has multiple different encodings for files. Problem occurs, when single file extension can be saved with Windows 1250, UTF-8 or ISO 8859-2 encoding. Is there possibility to add option inside settings to create shortcut for **Reopen with Encoding** to open encoding selection, or even have possibility to create shortcut for every encoding?

![Adnotacja 2020-08-10 082827](https://user-images.githubusercontent.com/32583062/89756660-7f83d900-dae3-11ea-977f-29cd6b88c89f.png)

**Comment by bpasero** [comment]
I think this can be a contribution small enough to accept via PR if someone wants to chime in. I would expect both "Reopen with encoding" and "Save with encoding" as commands.

**Comment by GustavoASC** [comment]
Hi @bpasero
I will try to send a PR for this next month, when I finish my graduation. I will have a free time after that 😄

Could you reopen this issue please? So I can submit a PR.

Thanks!

**Comment by bpasero** [comment]
@GustavoASC do you still plan on working on this?

**Comment by GustavoASC** [comment]
Hi @bpasero, 

I started looking at EditorStatus.ts to create two more classes extending Action (similar to ChangeEncodingAction), but I still haven't got time to work on it :cry: 

The graduation is taking a little longer than I thought. it's being a rush here.
I'm really sorry for that, but I don't plan to work on this anymore... at least not this year...

**Comment by bpasero** [comment]
No problem!
