### ISSUE TITLE
Cannot run vscode on linux

### ISSUE THREAD

**Issue by svurgun** [microsoft/vscode#104349]
I am trying to run VSCode on a linux box. I don't have root access. I get this error when I try to run code:

./code: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

How do I resolve this issue? As far as I can tell, the box has libgtk 2.0 version only.

VS Code version: download file is named code-stable-1595520402.tar.gz
OS: sles 11.4
Installation process: Following the process in https://code.visualstudio.com/docs/editor/portable
- Download .tar.gz file from https://code.visualstudio.com/download
- Unzip it
- Create data directory
- Run  VSCode-linux-x64/bin/code

**Comment by IllusionMH** [comment]
/needsMoreInfo

You should specify what's VS Code version, OS version, installation process etc. (as required by issue template)

**Comment by svurgun** [comment]
Updated the issue to add details
