### ISSUE TITLE
Cannot copy code from notebook cell into a script file

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/vscode#104396]
Issue Type: <b>Bug</b>

1. Open up a python notebook that has python code in it.
2. Open up a python ".py" file and have the two open tabs side by side
3. Select some lines of code from a single cell in the notebook, and select Edit->Copy
4. Go to the script file and try to paste the code into the script

The code from the notebook does not paste into the script file.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (19.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
indent4to2|Com|0.1.2
vscode-markdownlint|Dav|0.36.2
xml|Dot|2.5.1
vscode-pandoc|Dou|0.0.8
prettier-vscode|esb|5.1.3
getter-setter-generator|Gab|1.4.0
mdmath|goe|2.5.1
language-cython|guy|0.0.6
vsc-python-indent|Kev|1.10.1
restructuredtext|lex|129.0.0
pandoc-format|mon|0.0.3
mssql|ms-|1.9.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.7.96456
vscode-pylance|ms-|2020.8.0
remote-wsl|ms-|0.44.4
autodocstring|njp|0.5.3
java|red|0.65.0
vscode-yaml|red|0.9.1
markdown-preview-enhanced|shd|0.5.12
rewrap|stk|1.13.0
vscodeintellicode|Vis|1.2.9
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.10.2
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.23.0
markdown-all-in-one|yzh|3.2.0

</details>

**Comment by rebornix** [comment]
Based the reproduce steps, it's a duplicate of https://github.com/microsoft/vscode/issues/102736 (and tracking issue https://github.com/microsoft/vscode-python/issues/11796 in the Python extension). It's already fixed in Insiders and will be available in next stable release.
