### ISSUE TITLE
Why isn't theme applied on jupyter mode?

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [microsoft/vscode#104333]
1.  The theme i installed isnt working completely, some color looks missing even though it is working on file.py correctly.

2. Super heavy ram allocation when i active big csv compared to jupyter lab web!
Typing is too delayed, and incredibly slow. 

3. Dosent work Shift + tab (quick docs for module func's explanation) 

- VSCode Version:latest
- OS:ubuntu 20

**Comment by aeschli** [comment]
Please only one problem per issue.

Can you explain how the theme doesn't work? Maybe a screenshot?
