### ISSUE TITLE
Debug console only shows automatically for first debugging session.

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#10437]
_From @seraku24 on August 11, 2016 2:59_

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
VS Code version: 1.4.0
C# Extension version: 1.3.0

## Steps to reproduce
1. Create a new C# project (e.g. use `dotnet new` and `dotnet restore` for the "Hello, World!" template).
2. Launch VSCode and open the created project.
3. Start a debugging session.
4. Observe: The output window appears and displays the build process.
5. Observe: The debug console appears (replacing the output window) as the debugger launches the program.
6. After the program completes, start another debugging session.
7. Observe: The output window appears (replacing the debug console) and displays the build process, which in this case is a message that the project was already compiled.

## Expected behavior
The debug console, again, appears (replacing the output window) as the debugger launches the program.

## Actual behavior
The debug console is not shown and requires manual activation via the button on the debug UI toolbar or the keyboard shortcut (Ctrl+Shift+Y).

This could be a case where it might be wise to introduce a user-configurable setting that controls the behavior of the debug console.  I see at least three potentially useful modes:
- `"always"` The debug console is always shown automatically upon starting a debugging session.
- `"preserve"` The debug console will be re-shown automatically provided it was visible before being replaced by the output window.
- `"never"` The debug console will never be shown automatically when starting a debugging session.

_Copied from original issue: OmniSharp/omnisharp-vscode#653_

**Comment by gregg-miskelly** [comment]
@seraku24 thank you for reporting this issue. This issue an issue with VS Code itself rather than the C# extension, so I will port your bug over to them.

**Comment by isidorn** [comment]
This is already supported, more details can be found here https://github.com/Microsoft/vscode/issues/4045
