### ISSUE TITLE
suggest that vs could add default markdown to html with css

### ISSUE THREAD

**Issue by kylinhao** [Microsoft/vscode#10431]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
@kylinhao A little more then a title would be nice and help us learn what you are wishing for

**Comment by sandy081** [comment]
Closing this issue since we did not get enough info. Please provide required info and reopen. Thanks.
