### ISSUE TITLE
Overview ruler does not respect breakpoint color

### ISSUE THREAD

**Issue by oaahmad** [microsoft/vscode#104322]
When "debug.showBreakpointsInOverviewRuler" is true, and "debugIcon.breakpointForeground" is set, the color of the breakpoint in the overview ruler does not respect "debugIcon.breakpointForeground" (it is always red in the overview ruler). I am reporting this as a bug because @isidorn mentioned that the plan was to respect "debugIcon.breakpointForeground" here: https://github.com/microsoft/vscode/pull/82787#issuecomment-543592293. It is possible plans changed since then.

- VSCode Version: 1.47.3
- OS Version: macOS 10.15.6 (Catalina)

Note: I also tested this on the latest insiders build with no extensions (1.48.0-insider)

Steps to Reproduce:

1. Add this to your settings file:
```json
"debug.showBreakpointsInOverviewRuler": true,
"workbench.colorCustomizations": {
    "debugIcon.breakpointForeground": "#0000ff"
}
```
2. Add a breakpoint in any file
3. Observe how the breakpoint is red in the overview ruler, but blue in the gutter:

![Screen Shot 2020-08-09 at 12 51 08 AM](https://user-images.githubusercontent.com/26692282/89726692-8115aa00-d9da-11ea-83ec-8385fdbd4ac5.png)

Does this issue occur when all extensions are disabled?: Yes

Thanks

**Comment by isidorn** [comment]
@oaahmad good point. I have pushed a change so this should now nicely work. 
You can try out vscode insiders in a couple of days (Friday) and try it out.
