### ISSUE TITLE
Extensions will not install

### ISSUE THREAD

**Issue by rdcoe** [Microsoft/vscode#10436]
- VSCode Version: 1.3.1
- OS Version: Windows 7 x64

Steps to Reproduce:

1. ctrl+p
2. install any extension
3. button changes to "Installing" but nothing gets installed.

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by rdcoe** [comment]
It is a corporate network, so there is a security gateway involved.  I
suspect that is the cause but the barcode documentation I've read doesn't
explain what ports are required.

**Comment by joaomoreno** [comment]
Can you check with your network admin what kind of proxy you have in that environment?

**Comment by rdcoe** [comment]
Sorry, I will not disclose information related to our secure gateway.  Can you provide me information about how vscode connects to the extension repository?  If I knew what transport/application protocols were in-play, as well as port information, then I should be able to define policy that allows the traffic.

**Comment by joaomoreno** [comment]
HTTPS to `marketplace.visualstudio.com`.

**Comment by rdcoe** [comment]
I'm guessing that whatever is implementing the HTTP over TLS connection in vscode is the problem.  I can access that site through my browser and by using a simple curl connect.  Since there are no issues with the server cert, I'm guessing there's a problem in the client making the request.

**Comment by joaomoreno** [comment]
How about from within Node?

```
node -e "require('https').get('https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/csharp/1.3.0/assetbyname/Microsoft.VisualStudio.Code.Manifest', res => console.log(res.statusCode))"
```

I get `200` out of that command.
