### ISSUE TITLE
Spaces showing as "á"

### ISSUE THREAD

**Issue by erileff** [microsoft/vscode#104315]
Issue Type: <b>Bug</b>

Every space is showing up in VSC as an "á". It's only VSC -- in Sublime Text, for example, the spaces are just spaces.

In VSC, it looks like:
```
áááá<diváid="content">
áááááááá<article>
```
<img src="https://user-images.githubusercontent.com/7518276/89721058-ea7bc580-d9a6-11ea-8567-296c4509aff2.png" width="300">

The á symbols aren't really "there" -- they copy as spaces.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|-psn_0_61455|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What font are you using and what is your `editor.renderWhitespace`setting value.

It may be characters instead of dots representing whitespace.

**Comment by erileff** [comment]
The issue appears to have been with the font -- I'm not sure which font it was (I'm using shifty, so fonts change every half hour). Thanks!
