### ISSUE TITLE
Can't replace spaces in "selection only"

### ISSUE THREAD

**Issue by tifDev** [microsoft/vscode#104351]
- VSCode Version: 1.47.3
- OS Version: Ubuntu 18.04

Steps to Reproduce:
1. Select some text (containing spaces)
1. alt+l
1. Search field: Put a space " "
1. Replace field: Put nothing or other character
1. Hit button replace

You will see that the spaces don't get replaced.

**Comment by rebornix** [comment]
I'm not able to reproduce this issue, can you help confirm whether it works or not if you toggle the Find In Selection mode with mouse? A screen recording can help troubleshoot.

**Comment by tifDev** [comment]
I was now testing again to record a video but this time the spaces got replaced. 
I will track if this happens again.

Thanks
