### ISSUE TITLE
Option to always open the diff-editor in full window disregarding the current editor layout

### ISSUE THREAD

**Issue by ylilarry** [microsoft/vscode#104341]
Currently when you click on a git Changes, the diff preview editor opens by splitting the current editor.
For instance, when your open 2 editors in vertical-split mode like this
![Screen Shot 2020-08-09 at 10 55 29 PM](https://user-images.githubusercontent.com/8177295/89748953-c649e280-da93-11ea-8072-eff698b4a674.png)

and then you click on a git change, the diff editor is opened in the left editor, splitting the left editor like this (pink area):

![Screen Shot 2020-08-09 at 10 55 29 PM](https://user-images.githubusercontent.com/8177295/89749040-2b9dd380-da94-11ea-8005-9f441695cd54.png)

The feature request is to have an option to always open the diff-editer in full window, disregarding the current editor layout:

![Screen Shot 2020-08-09 at 10 55 29 PM](https://user-images.githubusercontent.com/8177295/89749139-95b67880-da94-11ea-80f9-769ad3fa460c.png)

**Comment by piavgh** [comment]
+1

Love the way Webstorm did with a separate diff window on top of the current window.
Personally, I feel it easier for my eyes.

![Screenshot 2020-08-10 10:25:38](https://user-images.githubusercontent.com/4060207/89749900-ea3d1080-daf3-11ea-8b3d-71af93072963.png)

**Comment by zimski** [comment]
A double click on the tab will increase the width and make it more comfortable to work with
Hope this will help!
