### ISSUE TITLE
VSCode hangs and crashes upon closing pwsh terminal instance

### ISSUE THREAD

**Issue by amunger3** [microsoft/vscode#104363]
Issue Type: <b>Bug</b>

Upon closing a terminal instance, VSCode will become unresponsive for a mintute or so before a dialog appears asking if you'd like to reload it. It occurs regardless of whether extensions are enabled but only appears to happen if the shell being closed is PowerShell Core. It doesn't matter whether its the Integrated PowerShell Terminal or otherwise.

#### Steps to reproduce: 

1. open VSCode (it happens whether or not there is a folder open)

2. Set default shell to PowerShell Core (mine is v7.0.3 if it is relevant); open a new terminal.

3. Close the instance (don't just hide it)

4. The VSCode window should now be unresponsive.

(P.S. I suppose it could be a PowerShell issue not specific to VSCode. If so, I apologize for addressing the wrong party.)

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.20185

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.84GB (2.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllusionMH** [comment]
Most likely #76548 but that was for old Windows builds, not Insiders(Dev Channel).

/cc @Tyriar is it still an issue not only in old Windows builds?

**Comment by Tyriar** [comment]
@IllusionMH this one is an issue in new Windows 10 builds (1903+), there's a fix done for node-pty (https://github.com/microsoft/node-pty/pull/415) but electron doesn't support workers in renderer processes (https://github.com/electron/electron/issues/18540#issuecomment-665752233) so we need to wait until the terminal process is hosted in a node process that's a child of the main process (https://github.com/microsoft/vscode/issues/74620).
