### ISSUE TITLE
Inconsistent behavior of Reveal in Side Bar for untracked files

### ISSUE THREAD

**Issue by marco-pm** [microsoft/vscode#104391]
If I have an open editor of a file located at least 2 levels under the repository root (_I'm not 100% sure about this condition, however I tried with files in the main path and under 1 level and the bug is not present_) and add a new file to the repository, locating it in the sidebar (with "Reveal in Side Bar") doesn't always work: the first time it works, the second time it locates the current opened file in the editor, the third time it works, the fourth time it locates the current opened file in the editor, etc.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/53403229/89821039-3c128480-db4e-11ea-9d24-05c593a2e231.gif)

- VSCode Version: 1.47.3
- OS Version: WLS 2 Ubuntu-20.04 on Windows 10 2004

Steps to Reproduce:

1. Open a file that's located at least 2 levels under the workspace root (e.g. /root/dir1/dir2/file.js) in the editor
2. Add a new, untracked file to the repository (don't open it in the editor; if it's opened, close it)
3. Click on the Source Control tab
4. Right click on the new file and select "Reveal in Side Bar"
5. Repeat steps 3 and 4

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This seems to work just fine for me.
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by marco-pm** [comment]
> This seems to work just fine for me.
> Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
> Might be due to WSL. fyi @aeschli if you saw something like this

Yes, just tried with the insiders version (still using the WSL extension) and the bug is still present.

**Comment by isidorn** [comment]
No plan to tackle this. Closing as will not fix
