### ISSUE TITLE
automationShell.osx doesnt work when set in workspaceFolder

### ISSUE THREAD

**Issue by jahan01** [microsoft/vscode#104380]
- VSCode Version: 1.47 - Tested with insider version as well
- OS Version: Mac 10.15

Steps to Reproduce:

1. Open a vscode workspace
2. Set the following in workspace settings ( `.vscode/settings.json`)
```jsonc
"terminal.integrated.automationShell.osx": "/bin/bash"
```
3. Launch a build task (tested with default `tsc build task` without anything in `tasks.json`), it still runs in the default shell.
4. Keep the same setting in global user settings.
5. Launch a build task, opens in the configured shell correctly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
This is intentional, we don't want random repositories you clone to set your shell without your knowledge. To enable the behavior you want, use the command **Terminal: Manage Workspace Shell Permissions**.

**Comment by jahan01** [comment]
thanks, it works.. setting description or docs doesn't provide any information on this. Perhaps a note in the settings description, describing this behaviour would have avoided me creating this ticket and thus would have saved some your time.

**Comment by alexr00** [comment]
@Tyriar FYI on above comment

**Comment by Tyriar** [comment]
We will likely be revisiting workspace permissions UX soon 👍
