### ISSUE TITLE
Missing Preferences Sync option in settings (VScode)

### ISSUE THREAD

**Issue by JacobB34** [microsoft/vscode#104324]
Issue Type: <b>Feature Request</b>

I am very new to everything here. Currently working the Odin project so I am not even sure if this is the correct issue. But I am trying to perform an assignment using Git. I am running Xubuntu on Oracle VM VirtualBox. I linked Git. The assignment is to creat a file & open it in my text editor. And the file is not appearing in my text editor. I have spent hours trying to figure out why & it is probably a simple fix. Through my problem solving I noticed that the option "Turn on Preferences Sync" is NOT available in my settings. I have uninstalled & reinstalled numerous times, I've restarted my computer, I've gone through the steps numerous times. I believe the issue to be my text editor VScode is not linked or sync'd. Please help. Thank you

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
Preferences Sync or Settings Sync is not available in stable release yet. We are planning to make it available from next release.
