### ISSUE TITLE
Prompts for loss of changes when closing split

### ISSUE THREAD

**Issue by pcolmer** [Microsoft/vscode#10430]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Open a document
2. Click on the Split Editor button
3. Make a change to the file
4. Go to close one of the two splits

You now get warned about data loss and whether or not to save the changes, even though you aren't closing the file completely. If you click on "Don't save", one of the splits closes, leaving you with the file still open, but your changes are lost! This happens regardless of which split you made the changes in and which split you close.

The desired behaviour would, surely, be just to close the split, leaving the file still open, no loss of changes and no prompt of loss of changes?

**Comment by bpasero** [comment]
Thanks for reporting this issue. Please use the issue search next time to see if there is a duplicate already. In this case, the issue has already been reported.

**Comment by pcolmer** [comment]
Hi

I did perform an issue search before submitting this and could not find one. Can you please provide a reference to the existing issue so that I can see what I should have been searching for?

**Comment by bpasero** [comment]
@pcolmer https://github.com/Microsoft/vscode/issues/8983, https://github.com/Microsoft/vscode/issues/9210, https://github.com/Microsoft/vscode/issues/9275, https://github.com/Microsoft/vscode/issues/9847, https://github.com/Microsoft/vscode/issues/9960, https://github.com/Microsoft/vscode/issues/9356, https://github.com/Microsoft/vscode/issues/9532, https://github.com/Microsoft/vscode/issues/9946, https://github.com/Microsoft/vscode/issues/9070

**Comment by pcolmer** [comment]
Thank you - I can see what happened. I only searched with the default "is:issue is:open", assuming (presumably incorrectly) that issues would only be closed after generally released, not just fixed.

I will search all issues in future.
