### ISSUE TITLE
Authentication: Sometimes Sign Out doesn't fully sign out

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#104399]
### Starting with no accounts
![image](https://user-images.githubusercontent.com/641685/89832686-ae26a180-db2d-11ea-9412-7ea83ce65a9b.png)

### Sign into the GitHub Browser extension
![image](https://user-images.githubusercontent.com/641685/89832772-cf878d80-db2d-11ea-9354-10045c078535.png)
![image](https://user-images.githubusercontent.com/641685/89832794-d910f580-db2d-11ea-8532-950935e37acd.png)

### Sign into the GitHub Pull Request Nightly Build extension

Notice that it still says the PR extension hasn't used this account

![image](https://user-images.githubusercontent.com/641685/89832854-fa71e180-db2d-11ea-8962-cad70dadcbba.png)
![image](https://user-images.githubusercontent.com/641685/89832838-f1811000-db2d-11ea-9a4f-d7e22279d3aa.png)

If I try to sign out here, it will only say the account is used by _GitHub Browser_ -- and often will not fully sign out (though it looks like it has). If you reload the window, it will show that it is still signed in, but only for the _GitHub Browser_ and _GitHub Pull Request Nightly Build_

But if I wait a bit (~30s or more) then it will show up

![image](https://user-images.githubusercontent.com/641685/89833015-4de42f80-db2e-11ea-9c17-613132caab93.png)

Though, if now I try to sign out here, it will only say the account is used by _GitHub Browser_ and _GitHub Pull Request Nightly Build_-- and sometimes this will also not fully sign out as above.

**Comment by TylerLeonhardt** [comment]
This should be fixed now
