### ISSUE TITLE
When running Tasks on Windows, check if file is executable before trying to execute

### ISSUE THREAD

**Issue by hannahchan** [microsoft/vscode#104343]
I have the following two tasks defined in my `tasks.json` file.

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Start Infrastructure",
      "command": "docker-compose",
      "dependsOn": ["Stop Infrastructure"],
      "type": "process",
      "args": ["up", "-d", "postgres", "grafana", "jaeger", "prometheus"],
      "presentation": {
        "echo": true,
        "reveal": "never",
        "focus": false,
        "panel": "shared",
        "showReuseMessage": true
      },
      "problemMatcher": []
    },
    {
      "label": "Stop Infrastructure",
      "command": "docker-compose",
      "type": "process",
      "args": ["down"],
      "presentation": {
        "echo": true,
        "reveal": "never",
        "focus": false,
        "panel": "shared",
        "showReuseMessage": true
      },
      "problemMatcher": []
    }
  ]
}

```

When I run one of these tasks, I get the following error message in Windows 10 which does not occur when running in macOS.

```
The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 193).
```

Upon investigation I find out that in the `bin` directory of Docker Desktop, there is both an file that is named `docker-compose` and `docker-compose.exe`. It looks like vscode is trying to run the `docker-compose` file which is a bash script in Windows.

![Annotation 2020-08-10 144422](https://user-images.githubusercontent.com/22674140/89752507-0c488a00-db18-11ea-9a08-bfeefe486067.png)

**Is there a way to get vscode to detect which file is executable and select the correct one when something like this happens?**

## Workarounds

There are 3 workarounds which I've identified however all of which I don't believe are really suitable.

**Workaround 1** - Remove the `docker-compose` bash script in the `bin` directory

This is not practical as those files are put there by the Docker Desktop installer and it is probably not wise to mess with those. Every person who checks out the repo will also need to do this.

**Workaround 2** - Change `"command": "docker-compose"` to `"command": "docker-compose.exe"`

Every person who checkouts the repo on their platform will need to remember to add/remove `.exe` for their given platform.

**Workaround 3** - Change `"type": "process"` to `"type": "shell"`

This works however it doesn't quite feel right as you're not trying to execute a shell command. All I want to do in Windows is run the `.exe`. I don't need to spawn a shell.

**Comment by alexr00** [comment]
@hannahchan after looking into this further, I think the current behavior is correct. If your task specifies that the command is "docker-compose" then the file that most closely resembles "docker-compose" should be run. 

This exact kind of scenario is why we support OS specific task properties. You can do the following to have your task run docker-compose.exe on Windows:

```json
		{
			"label": "Stop Infrastructure",
			"command": "docker-compose",
			"windows": {
				"command": "docker-compose.exe"
			},
			"type": "process",
			"args": [
				"down"
			],
			"presentation": {
				"echo": true,
				"reveal": "never",
				"focus": false,
				"panel": "shared",
				"showReuseMessage": true
			},
			"problemMatcher": []
		}
```
