### ISSUE TITLE
annoying automatic text replacer

### ISSUE THREAD

**Issue by vammex** [microsoft/vscode#104352]
Issue Type: <b>Performance Issue</b>

any time i insert "fun" in order to write "function" I get an automatic

function name(params) {
    
  }

which i don't like
i can change it with smth else but in fact the next time i open VS code i have to reset it again and again, because this replacer set itself as a primary one over all my custom replacing phrases

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.13

</details>

**Comment by gjsjohnmurray** [comment]
Assuming your document language mode is JavaScript (see indicator at right-hand end of status bar), maybe add these two settings to your settings.json

```
"javascript.suggest.enabled": false,
"editor.suggest.showSnippets": false,
```

But you also wrote

> all my custom replacing phrases

so maybe that will turn off too much. In that case, give us more information about your problem.

**Comment by rebornix** [comment]
@vammex can you confirm if @gjsjohnmurray 's suggestion helps?
