### ISSUE TITLE
What is this empty space for?

### ISSUE THREAD

**Issue by duzenko** [microsoft/vscode#104357]
![image](https://user-images.githubusercontent.com/1481807/89765149-6d636400-dafe-11ea-9003-eda783dfd5ed.png)

Issue Type: <b>Bug</b>

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:31:37.228Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (6.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
delphi-keybindings|ale|9.1.0
angular-schematics|cyr|4.3.0
vscode-firefox-debug|fir|2.9.0
vscode-flatland-icon-theme|geb|0.0.6
cpptools|ms-|0.29.0
shader|sle|1.1.4

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
File type icon

**Comment by duzenko** [comment]
I don't see any icons there

**Comment by IllusionMH** [comment]
For some reason your icon theme doesn't show icons for files in breadcrumbs, explorer, and editor tabs as well
![image](https://user-images.githubusercontent.com/1312662/89802463-3743d580-db3a-11ea-959a-07d4b7228d34.png)

What theme are you using? Because when I select `"workbench.iconTheme": null` there are no placeholders for icons.

**Comment by duzenko** [comment]
![image](https://user-images.githubusercontent.com/1481807/89803024-f7312280-db3a-11ea-83c6-3fd9a68b7b78.png)

**Comment by IllusionMH** [comment]
/causedByExtension

Because extension provides empty icon for files - these places has empty space and not skipped in the same way as with `"workbench.iconTheme": null`.

https://github.com/gebilaoxiong/vscode-flatland-icon-theme/issues/1
