### ISSUE TITLE
The operand of a 'delete' operator must be optional

### ISSUE THREAD

**Issue by TheoMer** [microsoft/vscode#104364]
Version: 1.47.3 (system setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

"nexus": "^0.26.0-next.3",

Steps to Reproduce:

1. Create file graphql.ts
2. In file type following code

```
    import { schema } from 'nexus'

    t.field('createAddress', {
      type: 'Address',
      nullable: false,
      args: {
        userId: schema.idArg({ nullable: false}), 
        email: schema.stringArg({ nullable: false}), 
        address_line: schema.stringArg({ nullable: false}),
        city: schema.stringArg({ nullable: false}), 
        postcode: schema.stringArg({ nullable: false}), 
        country: schema.stringArg({ nullable: false}), 
        card_name: schema.stringArg({ nullable: false}),
      },
      resolve: async (_, args, ctx) => {

         // remove the id and email from args
        delete args.userId; // VSCode issues error here
        delete args.email; // VSCode issues error here

        const address = await ctx.client.address.create({
          data: {
            user: {
              connect: {
                id: ctx.req.userId,
              },
            },
            ...args,
          },
        })

        // add the email to the return object
        return address;

      }
    })
```

Does this issue occur when all extensions are disabled?: No

**Comment by IllusionMH** [comment]
Looks like you are using TS 4.0-beta or later ant this is intended change

See more details in https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#breaking-changes

**Comment by TheoMer** [comment]
Hey @IllusionMH I'm actually using typescript 3.9.6

**Comment by IllusionMH** [comment]
This error doesn't exist in 3.9.6.

As you've mentioned - this doesn't happen with extension disabled. What extensions do you have?
Do you have [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)?

**Comment by TheoMer** [comment]
Hey @IllusionMH Yes, I do have 'JavaScript and TypeScript Nightly' installed.

**Comment by IllusionMH** [comment]
Then VS Code uses TSServer from extension which is `typescript@4.1.0-dev.20200809`(latest version) for providing language features and diagnostics.

You should either pick local TS version (from `node_modules`) instead on latest built-in version (from extension) so both `tsc` and VS Code will show same errors (but lost latest features), or update signature for `args` to make `userId` and `email` optional.

**Comment by TheoMer** [comment]
Hey @IllusionMH Removing typescript nightly did the trick. You've been a great help. Many thanks.
