### ISSUE TITLE
Devtools do not open (Stable and Insiders) (fresh installed insiders)

### ISSUE THREAD

**Issue by Venipa** [microsoft/vscode#104395]
Issue Type: <b>Bug</b>

Video of issue:
https://i.mavis.moe/f/4xFesJt5pk/2020-08-10-21-53-55mp4.mp4

VS Code version: Code - Insiders 1.48.0-insider (2277c8e2a3e1cc630a6397301ba54a1dccd8a60d, 2020-08-07T11:32:09.993Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (14.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
remote-wsl|ms-|0.44.4
vscode-typescript-next|ms-|4.1.20200809
debugger-for-chrome|msj|4.12.9
vetur|oct|0.26.1
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.2.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Since yoy don't have any webviews open, the `Open Webviews Developer Tools` command is not expected to do anything

Assigning @deepak1556 for the normal dev tools not opening

**Comment by Venipa** [comment]
@mjbvz didnt know that but here's an example with a created webview:
https://i.mavis.moe/f/J5E5EHTrxr/2020-08-10-23-03-04mp4.mp4

**Comment by giakas** [comment]
Seeing the same issue..  Even the Help->Toggle Developer tools is not working. that is supposed to work regard less of webview.

**Comment by giakas** [comment]
![image](https://user-images.githubusercontent.com/5192456/89844837-a5d06580-db31-11ea-8401-00f68dfea6d7.png)

Tried re-installing vscode, disabling all extensions, restarting machine. Didn't fix the issue.

![VSCodeDevTools](https://user-images.githubusercontent.com/5192456/89844935-f6e05980-db31-11ea-8d6c-5ae1873ec175.gif)

**Comment by deepak1556** [comment]
@Venipa @giakas can you launch with `--verbose` flag, try to toggle developer tools and attach the output from the command line, not sure what the issue is hopefully the logs have some details.

**Comment by giakas** [comment]
Here is the log, but not much useful logs in there.. 
[vscode.log](https://github.com/microsoft/vscode/files/5054609/vscode.log)

just lines like 
[18036:0810/203436.440:INFO:CONSOLE(1670)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.toggleDevTools", source: file:///C:/Users/giakas/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1670)

**Comment by giakas** [comment]
ping me on teams if you want to see the issue or debug on my machine. giakas is my Microsoft alias.

**Comment by deepak1556** [comment]
Thanks! yeah the logs don't contain useful info, pinged on teams for additional debugging.

**Comment by giakas** [comment]
Looks like this is happening when VSCode is opened with Elevated admin permissions. Installed insider version which was not set to open as administrator, and it worked fine.

**Comment by Venipa** [comment]
> Looks like this is happening when VSCode is opened with Elevated admin permissions. Installed insider version which was not set to open as administrator, and it worked fine.

fresh install of vscode insiders on notebook:
- installed with system installer
- run with admin results that devtools do open
![image](https://user-images.githubusercontent.com/17952364/90019410-a7736800-dcae-11ea-86b6-da65a55f8947.png)
- run without admin also results that devtools do open
![image](https://user-images.githubusercontent.com/17952364/90019373-9aef0f80-dcae-11ea-8ccd-643e758e0447.png)

ill try it on my pc once im home... weird.

**Comment by yume-chan** [comment]
I just want to point out that it's an old issue #84804 (it didn't say administrator in title, but do in one comment)

**Comment by rzhao271** [comment]
Works for me on Windows 10 using VS Code v1.52.1 (stable).
@Venipa or @giakas can either of you still reproduce this issue with the latest Stable or Insiders version of VS Code?

**Comment by Venipa** [comment]
@rzhao271 cant reproduce it anymore it seems.
