### ISSUE TITLE
Remove invisible characters from vscode.d.ts

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#104301]
If you try to copy paste glob pattern from `vscode.d.ts` - then it simply won't work because it contains invisible characters:

https://github.com/microsoft/vscode/blob/6d913c4c14bc9d7924cef5f502682873c89bab2d/src/vs/vscode.d.ts#L1901

You can search for regular expression: `[\u200B-\u200D\uFEFF]` or use an extension https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins to find them.

**Comment by jrieken** [comment]
The problem is that you cannot type `*​/` inside a jsdoc comment. That's why these invisible characters are being used. Open for suggestions
