### ISSUE TITLE
when i am write (code) in Terminal{PS C:\Users\Anant Choudhary\flutter_dev> code}he shows 

### ISSUE THREAD

**Issue by anantcho** [microsoft/vscode#104379]
cd : An object at the specified path C:\Users\Anant Choudhary\flutter_dev\... does not exist.
At line:1 char:2
+  cd ...
+  ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.SetLocationCommand

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com).

/label "needs more info"
