### ISSUE TITLE
Vs code debugging console opens automatically

### ISSUE THREAD

**Issue by Abhijeetrkushwaha** [microsoft/vscode#104360]
- VSCode Version: 1.4
- OS Version: window 10 

Steps to Reproduce:

1. When starts vs code this start happening of once 
2. When I use wifi(net) that start again but this time it goes in a loop and because of that my pc gets slow down

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Put this in your settings 	
`"debug.internalConsoleOptions": "neverOpen"`

**Comment by Abhijeetrkushwaha** [comment]
> Put this in your settings
> `"debug.internalConsoleOptions": "neverOpen"`

Ok I will do those changes. Thank you for your time.
