### ISSUE TITLE
Crash upon opening "open folder" prompt

### ISSUE THREAD

**Issue by KresimirCosic** [microsoft/vscode#104383]
Issue Type: <b>Bug</b>

Using 20.04 LTS of Pop!_OS (Ubuntu based). Never had this issue before, even on the same OS version, but I haven't used VSCode in 3-4 months so something might have changed.

Upon opening the prompt to "open a folder location" the program just freezes and crashes eventually in a few seconds.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 5.4.0-7634-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 1770)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.50GB (7.25GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.1.3

(1 theme extensions excluded)

</details>

**Comment by KresimirCosic** [comment]
Hi again, it seems the issue is related to integrated graphics processor in the CPU. To save battery I have been using integrated GPU, but now that I have switched to discrete GPU to utilize multiple displays, the issue is gone.

This is definitely related since around that time I stopped coding few months ago, I have switched to integrated GPU to prolong battery life.

I hope this helps!

**Comment by deepak1556** [comment]
Can you try the exploration builds which come with newer runtime and see if the issue happens ?

https://az764295.vo.msecnd.net/exploration/45f988139ce0ef09e4657aa4fd34df8a7e8fb525/code-exploration-1596782786.tar.gz
https://az764295.vo.msecnd.net/exploration/45f988139ce0ef09e4657aa4fd34df8a7e8fb525/code-exploration_1.48.0-1596782473_amd64.deb

**Comment by KresimirCosic** [comment]
Hi, I have installed the *.deb version and the few extensions I had on the old one, switched to explicitly integrated graphics and it doesn't happen anymore. Interestingly, it didn't happen before on opening a file, but specifically opening a folder prompt.

Not sure if it was related, but it seems like the GPU had something to do with it.

Is this exploration version suitable for use or should I switch back to the default/stable release?

BR
