### ISSUE TITLE
Option to select "Unified Source Control" or "Old Source Control"

### ISSUE THREAD

**Issue by alber70g** [microsoft/vscode#104386]
I'd like to see an option to select the old view. For me the new view is very cluttered and hard to get focus. The old view was for me much cleaner and easier to focus. Especially when working in a "monorepo with git submodules" style project that has over 20 submodules.

Old: https://code.visualstudio.com/updates/v1_20#_git-submodules

![Old Source Control](https://user-images.githubusercontent.com/516972/89813915-acb3a400-db42-11ea-94a1-54b22b10d205.png)

Single View: https://code.visualstudio.com/updates/v1_47#_single-view

![Single View Source Control](https://user-images.githubusercontent.com/516972/89813941-b89f6600-db42-11ea-8abc-28a9c2d97c69.png)

Also: scrolling in the Unified View stops when the cursor is in the input field for commit messages, which is quite annoying when all the submodules are opened

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/104151
