### ISSUE TITLE
Holding Cmd while hovering a symbol shows LocationLink's "targetSelectionRange" instead of "selectionRange" as preview

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#104369]
When returning `Location` classes from a `DefinitionProvider`, VS code shows a preview of the code if you hold Cmd while hovering over a symbol:

<img width="613" alt="Screenshot 2020-08-10 at 14 33 29" src="https://user-images.githubusercontent.com/1078012/89788126-91cb3a80-db16-11ea-9a30-eda1a006ba96.png">

Multiple lines are shown, leading me to believe this is intended to show a snippet of the code that defines this symbol.

However, if I switch to using `LocationLink` where `targetRange` points at the full code snippet and `targetSelectionRange` includes only the name of the function (the LSP docs say "e.g the name of a function" for `targetSelectionRange`) then the preview only shows the `targetSelectionRange` code, which means the preview shows only the function name (which seems a bit pointless):

<img width="603" alt="Screenshot 2020-08-10 at 14 36 17" src="https://user-images.githubusercontent.com/1078012/89788366-f1c1e100-db16-11ea-8404-771c7137f266.png">

It seems like maybe this should be using the `targetRange` so there is some preview of the code, as it did for `Location`?

**Comment by jrieken** [comment]
this came in via https://github.com/microsoft/vscode/commit/459939b9051e86653ef49f910c408a2b64f27bff

**Comment by mjbvz** [comment]
@jrieken Do you know what about that commit is incorrect? 

@DanTup Can you please provide steps to reproduce this so we can investigate?

**Comment by DanTup** [comment]
My guess is that [this line](https://github.com/microsoft/vscode/commit/459939b9051e86653ef49f910c408a2b64f27bff#diff-0ce495caad094e6c7241c2b766c87120R174) should be using `targetRange`.

To reproduce, you just need to return a `LocationLink` that has a `targetSelectionRange` that covers a small range (eg. the name of a function, which is what the LSP docs give as an example) and a `targetRange` that is much greater (the whole function body), and then hold `Cmd` while hovering over a reference to the function. The preview will only show the name (as shown in the second screenshot above), but it's expected to show a preview of the code (as it does in the first screenshot, when not using `LocationLink`).

**Comment by mjbvz** [comment]
Hmm, I believe TS already does this though: https://github.com/microsoft/vscode/blob/6dd0a9a64dbd9cbf032be18311eb97b42fea1d94/extensions/typescript-language-features/src/languageFeatures/definitions.ts#L43

Do you have a self-contained example for this or a build of dart that uses definition links? I'd like to be able to debug what is going on.

`result.range` seems like the correct value to use at that point in the code as the other two properties are selection ranges: 

<img width="447" alt="Screen Shot 2020-08-10 at 8 15 34 PM" src="https://user-images.githubusercontent.com/12821956/89853448-44ff5800-db46-11ea-8a0e-a86005430e98.png">

**Comment by DanTup** [comment]
Ok, I'm a little confused :-)

The screenshot above shows code completion showing `range` but no `targetRange` - what type is that? `LocationLink` has no `range` but does have a `targetRange` (the other fields match).

I tried to reproduce this in a simple VS Code extension, but could not - it seemed to work as expected (despite the linked code above seemingly using `targetSelectionRange`). However, I do still see this in LSP.

Here's what my logged LSP traffic looks like:

```
==> {
	"jsonrpc": "2.0",
	"id": 6,
	"method": "textDocument/definition",
	"params": {
		"textDocument": {
			"uri": "file:///Users/danny/Desktop/TestProjects/test_2710/lib/main.dart"
		},
		"position": {
			"line": 57,
			"character": 22
		}
	}
}
<== {
	"id": 6,
	"jsonrpc": "2.0",
	"result": [
		{
			"originSelectionRange": {
				"start": {
					"line": 57,
					"character": 20
				},
				"end": {
					"line": 57,
					"character": 25
				}
			},
			"targetUri": "file:///Users/danny/Dev/Google/flutter/packages/flutter/lib/src/material/icons.dart",
			"targetRange": {
				"start": {
					"line": 8,
					"character": 0
				},
				"end": {
					"line": 17034,
					"character": 1
				}
			},
			"targetSelectionRange": {
				"start": {
					"line": 62,
					"character": 6
				},
				"end": {
					"line": 62,
					"character": 11
				}
			}
		}
	]
}
```

This generates the second screenshot from the original comment. It shows only `Icons` (which is what the `targetSelectionRange` points at) and not a preview of the class (which is what `targetRange` points at).

The LSP changes to use `LocationLink` aren't available in a pre-built Dart SDK yet so running it locally might be a bit clumsy (though they might be in tonights nightly build). I guess you don't have an equiv of MockDebug for LSP to make a small sample?

**Comment by DanTup** [comment]
I did find there's some different handling for long ranges:

https://github.com/microsoft/vscode/blob/5e4f1b081bf1659144706b264d8de2adc2ac90f1/src/vs/editor/contrib/gotoSymbol/link/goToDefinitionAtPosition.ts#L220-L222

I don't think it explains this, though I think that would be tripped up where the `targetRange` includes leading comments (since it'll only include the first two lines, as they both have the same indentation). The docs don't seem to be specific about whether leading comments should be included in the `targetRange` (if they should not, I think this should be explicitly documented).

Despite this, I still can't repro the behaviour seen using LSP without LSP. I did find a second definition of `LocationLink` that has `range` instead of `targetRange`, though I'm not sure how they're mapped (or whether it's relevant here).

**Comment by mjbvz** [comment]
@dbaeumer Seems like there is a bug in the LSP, although it seems like this logs was added to work around a previous issue: https://github.com/microsoft/vscode-languageserver-node/blob/51cf328886b9bddb4d5eb72cde983872c5564084/client/src/common/protocolConverter.ts#L583

@jrieken For VS Code itself, would it make sense to trim the passed in range rather than falling back to use `getPreviewRangeBasedOnIndentation` for long lines? What do you think?

**Comment by jrieken** [comment]
> @jrieken For VS Code itself, would it make sense to trim the passed in range rather than falling back

The "how to trim" is the interesting part... We used to have a simple crop bit it would often look awkward when only seeing increasing indentation

**Comment by DanTup** [comment]
> Seems like there is a bug in the LSP, although it seems like this logs was added to work around a previous issue: https://github.com/microsoft/vscode-languageserver-node/blob/51cf328886b9bddb4d5eb72cde983872c5564084/client/src/common/protocolConverter.ts#L583

Oh, that explains that. I can move this issue to that repo if makes sense. I'm not sure I understand the workaround though - showing just the name of the element in the preview doesn't seem very useful. 

> We used to have a simple crop bit it would often look awkward when only seeing increasing indentation

This makes assumptions about how the language indents and that documentation is not included. I think if VS Code is going to do things like this, it would be good to have it noted in the API - it can be confusing as an extension author when VS Code is showing different ranges to we're sending and the only way to understand why is to check out the VS Code codebase and try to locate the code that's doing it (which isn't always simple for us not familiar with the code).

But in lieu of doc updates, can someone confirm that leading documentation comments should definitely not be included in `targetRange`?

**Comment by dbaeumer** [comment]
I added that workaround since the new LocationLink was not wired up correctly on the VS Code side (see https://github.com/Microsoft/vscode/issues/58649) and using the `targetSelectionRange` was the closest to the old behavior. 

I will change it to use `targetRange` now and rely on VS Code to have it wired up correctly.

**Comment by mjbvz** [comment]
Thanks @dbaeumer!

@DanTup We can double check with @jrieken on this but I believe that the ranges should not include documentation. They should be  ranges of the symbols themselves

**Comment by DanTup** [comment]
@dbaeumer 

> I will change it to use `targetRange` now and rely on VS Code to have it wired up correctly.

Perfect, thanks!

@mjbvz 

> We can double check with @jrieken on this but I believe that the ranges should not include documentation. They should be ranges of the symbols themselves

Yeah, I think that's the case - I think it would be worth adding a note in the docs though, since it's not obvious so if any language servers already have a range that includes this and just send it over, they might not realise it causes a bad experience here.

**Comment by DanTup** [comment]
I tested this in vNext of the LSP client package and it seems to work as expected now. Thanks @mjbvz @dbaeumer!
