### ISSUE TITLE
Can't type into the terminal at launch without closing the terminal and starting a new terminal

### ISSUE THREAD

**Issue by animeinabox** [microsoft/vscode#104317]
Issue Type: <b>Bug</b>

1. Launch Visual Studio Code
2. Observe that you can't type in the terminal
3. Close the terminal 
4. Launch a new terminal process using _CTRL + `_
5. Observe that you can type in the terminal

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G4560 @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (11.32GB free)|
|Process Argv|--log trace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.7.96456
cmake-tools|ms-|1.4.1
cpptools|ms-|0.30.0-insiders

</details>

![vscode-terminal-not-working](https://user-images.githubusercontent.com/62572234/89722312-ff535b80-d99c-11ea-9467-12569c866eb9.png)
![vscode-terminal-not-working-03](https://user-images.githubusercontent.com/62572234/89722337-63761f80-d99d-11ea-8364-ac5a663b3661.png)

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
