### ISSUE TITLE
File watching breaks on macOS with a case insensitive file-system

### ISSUE THREAD

**Issue by gerarts** [microsoft/vscode#104340]
- VSCode Version: 1.47.3 (Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e)
- OS Version: macOS Catalina 10.15.5 (Darwin x64 19.5.0)
- File-System: APFS Volume (Encrypted)

_More detailed information attached below_

Steps to Reproduce:

1. Create a file on a volume with a case-insensitive file-system (APFS)
1. Open the file in VSCode
1. Change the case of one or more characters in the filename (e.g. `MyFile.txt` => `myFile.txt`)
1. Delete the file on disk (The file will now correctly show as _"{{filename}} (deleted)"_ in VSCode's tab-bar)
1. Create a file with the name of the deleted file with different contents (e.g. `myFile.txt`, not with VSCode)

At this point VSCode recognises that the file has been recreated and the _"(deleted)"_ tag disappears from the tab-bar, but it doesn't load the latest version from disk until you force VSCode to read the file from disk (for example by running the _"File: Revert file"_ command).

Does this issue occur when all extensions are disabled?: Yes

> #### About Visual Studio Code
>
> Version: 1.47.3
> Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
> Date: 2020-07-23T13:08:29.692Z
> Electron: 7.3.2
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Darwin x64 19.5.0

> #### Disk Utility volume information for _Macintosh HD_
>
> | Key | Value |
> |---|---|
> Volume name | Macintosh HD
> Volume type | APFS Volume
> BSD device node | disk1s1
> Mount point | /
> System | macOS 10.15.5 (19F101)
> File system | APFS (Encrypted)
> Connection | PCI-Express
> Is case-sensitive | No
> Volume capacity | 250.685.###.###
> Free space | 130.011.###.###
> Used space | 10.991.###.###
> File count | 372.###
> Owners enabled | Yes
> Is encrypted | Yes
> System Integrity Protection supported | Yes
> Can be verified | Yes
> Can be repaired | Yes
> Bootable | Yes
> Journaled | No
> Disk number | 1
> Partition number | 1
> Media type | Generic
> Ejectable | No
> Solid state | Yes
> SMART status | Not Supported
> Parent disks | disk1
>
> ##### NOTE: Capacity values have been obfuscated and unique identifiers have been omitted for privacy reasons

**Comment by gerarts** [comment]
Simplest case I could create

```sh
echo "orig" > MyFile.txt; mv MyFile.txt myFile.txt
```
Open the file in VSCode
```sh
rm myFile.txt; echo "hello" > myFile.txt
```
No update until I force VSCode to update the file

**Comment by bpasero** [comment]
I cannot reproduce when I run from `master` today. Can you try using our latest insider build? And if that still reproduces, maybe attach the output from `code-insiders --verbose` around the file watcher entries? We log each file change that we receive there.
