### ISSUE TITLE
error dialog for typescript

### ISSUE THREAD

**Issue by windoncloud** [microsoft/vscode#104362]
Issue Type: <b>Bug</b>

error dialog for typescript

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (1.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vue-jsdoc|bej|0.0.2
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
gitlens|eam|10.2.2
code-runner|for|0.11.0
terminal|for|0.0.10
Hap|hap|0.0.8
docthis|joe|0.7.1
vscode-leetcode|Lee|0.17.0
vscode-language-pack-zh-hans|MS-|1.45.1
vsliveshare|ms-|1.0.2478
vetur|oct|0.24.0
partial-diff|ryu|1.4.1
open-in-browser|tec|2.0.0
html-preview-vscode|tht|0.2.5
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Provide more info. At least what's message in this dialog (screenshot etc,), what was before this dialog etc..
