### ISSUE TITLE
Ctrl+s doesn't work when foreign language is selected

### ISSUE THREAD

**Issue by gitDawn** [microsoft/vscode#104348]
Issue Type: <b>Bug</b>

I found out that the shortcut for quick save, ctrl+s, doesn't work when foreign language (Hebrew in my case) is selected. Switching to English and ctrl+s works again.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (10.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ml-net-model-builder|fra|0.0.3
csharp|ms-|1.22.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.7.96456
remote-wsl|ms-|0.44.4
vscode-yaml|red|0.9.1

</details>

**Comment by alexdima** [comment]
@gitDawn When the keyboard layout is Hebrew, if you open the Command Palette (F1) and search for `File: Save`, what keybinding is rendered next to it? If you press that keybinding, does the command execute?

**Comment by alexdima** [comment]
@gitDawn I have installed the Hebrew keyboard layout and pressing Ctrl+S works for me:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/99779761-cedf9980-2b15-11eb-9428-c6c25b92a1ee.gif)


Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command Developer: Toggle Keyboard Shortcuts Troubleshooting
  * This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* You can then press your desired keybinding and check what keyboard shortcut VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and we can help decipher it for you.
