### ISSUE TITLE
VSCode will not remove record of extension that no longer exists

### ISSUE THREAD

**Issue by dan-drago** [microsoft/vscode#104337]
- VSCode Version:
1.47.3
- OS Version:
10.15.6

Problem:

When I use the extension "Settings Sync", it uploads an extension that no longer exists. [Here](https://gist.github.com/dan-drago/a4d7fbc8aed685726259dabffbba542f) is the uploaded gist. This is the part for a past extension called "sass-indent". 

```
{
    "metadata": {
      "id": "e52bce95-a629-455f-8626-e7301b9e372a",
      "publisherId": "robinbentley.sass-indented",
      "publisherDisplayName": "robinbentley"
    },
    "name": "sass-indented",
    "publisher": "robinbentley",
    "version": "1.5.1"
  }
```

When I try to sync my settings on another machine, Sync Settings will fail when it arrives at this no-longer existing extension.

Obviously, there is a record somewhere on my system of this extension that never got removed. When I search for this extension in VSCode, I can't find it (since it doesn't exist), and so I cannot manually remove reference to it. I also have been unable to find a file on my system where I can remove reference to this extension (I've tried Googling all sort of things like "where is vscode extensions.json stored on a Mac?". 

I tried removing the dir for this extension at ~/.vscode/extensions, but that did not solve the problem. Settings Sync still thinks that I have this extension on my system.

**Comment by sandy081** [comment]
This feature is not part of VS Code and is contributed by Settings Sync extension. Please file an issue against it.
