### ISSUE TITLE
Slows Down Occasionaly

### ISSUE THREAD

**Issue by nirmalnishant645** [microsoft/vscode#104381]
Issue Type: <b>Performance Issue</b>

I don't think I can descrbe it, just slows down occasionaly when I am working and it makes it difficult to do anything at all. And then gets back to normal.
It happens while working on files with .py .html .css .js extensions.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1999)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|3.76GB (0.12GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   135	 17399	code main
    0	    35	 17403	   zygote
    2	   108	 17425	   gpu-process
    0	    54	 17443	   utility
    0	   127	 17485	   shared-process
    0	     0	 18458	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 18459	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    1	   304	 18207	   window (app.py - Python-Programming - Visual Studio Code)
    0	   258	 18251	     extensionHost
    0	    54	 18314	       electron_node serverMain.js 
    0	    66	 18262	     watcherService
    0	    62	 18284	     searchService
    1	   112	 18438	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (app.py - Python-Programming - Visual Studio Code)
|    Folder (Python-Programming): 202 files
|      File types: py(130) ipynb(20) txt(8) json(3) md(3) png(2) csv(2)
|                  gitattributes(1) pyc(1) html(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-intelephense-client|bme|1.5.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
angular2-snippets|dan|1.0.21
jshint|dba|0.10.21
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
es7-react-js-snippets|dsz|2.8.2
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
carbon-now-sh|eri|1.2.0
vscode-todo-plus|fab|4.17.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
vue-snippets|hol|0.1.12
phpcs|ika|1.0.5
path-autocomplete|ion|1.15.0
Angular2|joh|9.1.2
php-cs-fixer|jun|0.1.155
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
php-import-checker|mar|0.5.0
Angular-BeastCode|Mik|8.1.2
dotenv|mik|1.0.1
python|ms-|2020.7.96456
cpptools|ms-|0.29.0
vscode-typescript-tslint-plugin|ms-|1.2.3
php-docblocker|nei|2.1.0
vetur|oct|0.26.1
laravel-blade|one|1.22.1
laravel5-snippets|one|1.9.0
material-icon-theme|PKi|4.2.0
vscode-nginx|sha|0.6.0
markdown-preview-enhanced|shd|0.5.12
php-docblock-generator|vin|0.0.1
JavaScriptSnippets|xab|1.8.0
vscode-surround|yat|1.0.2
markdown-all-in-one|yzh|3.2.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by nirmalnishant645** [comment]
No it did not, thanks for pointing out that extensions might be dragging it down. I have fitered out a lot of unused extensions and it seems to be working properly for now.
