### ISSUE TITLE
Allow addition of custom textmate scopes without modifying theme

### ISSUE THREAD

**Issue by epiqu1n** [microsoft/vscode#104350]
Issue Type: <b>Feature Request</b>

I would very much like to add custom scopes to VSCode or at least to my current project so that I may style them.  For instance, I would like to highlight the parens for ternary operators `(a ? b : c)` (especially since there is already scopes for the `?`/`:`) and paired opening/closing tags for sections in Mustache files.

However, there are no existing scopes specific to these things, and I cannot figure out if there is a way to add additional scopes without creating a custom theme.  Unless there is some technical limitation, we should be able to add custom scopes into `settings.json` just like we can add custom highlighting for existing scopes.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

**Comment by aeschli** [comment]
Custom theming rules can already be added using `editor.tokenColorCustomizations` setting as seen here:
https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting

However, you first need a scope that expresses what you want to highlight. It's the grammar that generates the scopes. I guess your talking about JavaScript/TypeScript. The TypeScript grammar does not generate any usefull scopes for ternary expressions (only the ternary tokens). So you need to modify or replace the grammar.

A way to modify a grammar is through [injection grammars](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars). That said, writing a injection grammar is a very advanced task, and I'm not sure if that's even possible in this case as there's quite some lookahead needed that is not doable in a TextMate grammar. Also, this is not something you can do in settings.json, it requires your own extension. Injection-grammars is not something we want to allow in settings anyways, as, if badly written, they can kill the highlighting performance.

**Comment by epiqu1n** [comment]
Thank you for the detailed response.  Yes sorry, what I mean is that I want to add custom grammars, so that I may use token color customizations as I already do to style more things.

I did try for a little bit to set up an injection grammar, and though I thought I understood it, I could not get it to work at all in practice (even the demo).

That is a fair point about performance with poorly written grammars.  Still, if it ever is possible without significantly impacting performance, it would be really great if perhaps there was some simplified built-in way to add new grammars for things like custom keywords/pairs.

**Comment by aeschli** [comment]
If you are not scared of writing an extension, you can also look into a extension that uses the TypeScript library to parse the code, walk the AST and generate editor decorations from it. See https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API for more about the TS compiler API.

**Comment by epiqu1n** [comment]
That seems to be a bit more than I could handle right now, but thank you for the suggestion.
