### ISSUE TITLE
Proxy Connection Failed (not using a proxy)

### ISSUE THREAD

**Issue by rjmccabe3701** [microsoft/vscode#104342]
I'm getting:

```
net::ERR_PROXY_CONNECTION_FAILED
```

But I'm not even using a proxy server.  I even started code with ``--no-proxy-server`` and I'm getting the same error.  The docs suggest that vscode accesses the web the same way chromium does, but chromium works ...

I'm running on Windows 10

**Comment by chrmarti** [comment]
Which version of VS Code is this? (`Help` > `About`.)

**Comment by rjmccabe3701** [comment]
@chrmarti: Looks like vscode updated itself and the problem went away (the new working version is 1.48.0).  Thanks.  Closing.
