### ISSUE TITLE
Underlines of problems are glitched since switching to electron 9

### ISSUE THREAD

**Issue by PF4Public** [microsoft/vscode#104326]
- VSCode Version: 1.48+
- OS Version: linux 64

Steps to Reproduce:
Started occuring after electron was updated to 9. Didn't happen on electron 8 and 7.
* Since electron 9, all underlines of problems (errors, warnings, infos) are visually wrong.
![image](https://user-images.githubusercontent.com/10319700/89730541-36cb1200-da48-11ea-858d-c678e0508b2a.png)
![image](https://user-images.githubusercontent.com/10319700/89730619-ff109a00-da48-11ea-8a98-680413518367.png)

I'm aware of the fact, that electron 9 support was reverted, just letting you know, this probably needs to be addressed before switching to electron 9.

**Comment by sandy081** [comment]
@deepak1556  Assigning to you as it is electron 9 related. Let me know if I have to do something while it is being adopted. Thanks.

**Comment by deepak1556** [comment]
Can we create a minimal repro with chromium so that a bug report can be created in upstream issue tracker.

/cc @alexdima I remember you had some similar issue upstream wrt to underline ?

**Comment by PF4Public** [comment]
> Can we create a minimal repro with chromium so that a bug report can be created in upstream issue tracker.

Can I help with this? If yes, then, how?

**Comment by deepak1556** [comment]
@PF4Public what are the steps to repro this in vscode ?

**Comment by PF4Public** [comment]
Simplest would be to create an empty Javascript file and trigger a syntax error, like this:
![image](https://user-images.githubusercontent.com/10319700/90004399-417ee480-dc9e-11ea-9ec3-aa2a84ab2787.png)

**Comment by deepak1556** [comment]
![underline](https://user-images.githubusercontent.com/964386/90058366-83a42800-dc96-11ea-881e-b4c58184ae50.png)

Unable to repro with electron 9, what is the theme you are using ?

**Comment by PF4Public** [comment]
I'm using Monokai Dimmed Theme.
My screen has ~142 dpi, could it be related to that?

**Comment by deepak1556** [comment]
Tried that dpi along with the theme, still same issue

```
demohan@ubuntu:~$ xdpyinfo | grep resolution
  resolution:    142x142 dots per inch
```

are you able to repro on any other OS ? 

also can you check if the issue disappears when you run with 

1) `--disable-gpu`
2) `--disable-features="LayoutNG"`

**Comment by PF4Public** [comment]
> also can you check if the issue disappears when you run with
> 
> 1. `--disable-gpu`
> 2. `--disable-features="LayoutNG"`

None of these helped.

I tried with developer tools and come across a peculiar thing with
```javascript
document.querySelector("#workbench\\.parts\\.editor > div.content > div.grid-view-container > div > div > div > div.split-view-container > div > div > div.editor-container > div > div > div.overflow-guard > div.monaco-scrollable-element.editor-scrollable.vs-dark > div.lines-content.monaco-editor-background > div.view-overlays > div:nth-child(1) > div.cdr.squiggly-error")
```

By default its height is 19 and it looks glitched:
![image](https://user-images.githubusercontent.com/10319700/90117035-055f8880-dd5f-11ea-8e1e-b889cfcca974.png)

Turns out any uneven value here corrupts it, like 17 or 15:
![image](https://user-images.githubusercontent.com/10319700/90117288-61c2a800-dd5f-11ea-8d8b-9802bf2836d0.png)

Even numbers are good, like 16:
![image](https://user-images.githubusercontent.com/10319700/90117416-8f0f5600-dd5f-11ea-8bc9-7fa7c3e56420.png)
Or 20:
![image](https://user-images.githubusercontent.com/10319700/90117833-152b9c80-dd60-11ea-9c78-0533f0a801d1.png)

With every resize this height (19px) gets recalculated for every line:
![image](https://user-images.githubusercontent.com/10319700/90118376-d1856280-dd60-11ea-8eeb-b1b53b8e9204.png)

Changing editor font size gives similar results.
Default is 14:
![image](https://user-images.githubusercontent.com/10319700/90118741-5cfef380-dd61-11ea-91b4-a76e691bf002.png)
Here is 15:
![image](https://user-images.githubusercontent.com/10319700/90118799-7011c380-dd61-11ea-8485-be52da5e1b11.png)
Any higher value does not corrupt the underline.
Here is 13:
![image](https://user-images.githubusercontent.com/10319700/90118932-99caea80-dd61-11ea-89c0-59f334c4d286.png)
12 Does not corrupt, but 11 does in a weird way:
![image](https://user-images.githubusercontent.com/10319700/90119077-c54dd500-dd61-11ea-95f0-a330751e5e57.png)
10 and 9 are fine:
![image](https://user-images.githubusercontent.com/10319700/90119330-178ef600-dd62-11ea-8fc9-28c893c6b054.png)
Unlike 11, 8 does it differently:
![image](https://user-images.githubusercontent.com/10319700/90119539-5f158200-dd62-11ea-8845-f69428b7624f.png)

**Comment by deepak1556** [comment]
Thanks, thats helpful info!

I am still unable to repro with those sizes, one thing I would like to try is change my font family to what you are using. Can you provide the details.

also looping in @rebornix for additional thoughts on debugging

**Comment by PF4Public** [comment]
>change my font family to what you are using. Can you provide the details.

It is "Fira Code"

Updating Electron to 9.2 didn't help either.

I have remembered that my screen's true dpi is 141,76744186 by 141,402061856 and Xorg was fine with determining it. At some point I did however set my dpi to 142 via my Desktop environment settings (xfce if you're curious). So I tried to revert this setting to "by default" or "unset". And this solved the issue. Should I set my dpi to 142 again, I see glitched underlines again.

In this light this looks like a Chromium/Electron issue. But I couldn't recreate this issue in Chromium 84. Either it is fixed there, or my test was incomplete:
![image](https://user-images.githubusercontent.com/10319700/90311147-c0735780-df00-11ea-811f-d59c604b7408.png)

Perhaps you could provide me with a test-html excerpt, that I could test in Chromium 84.

How could we proceed next?

**Comment by alexdima** [comment]
The editor at https://microsoft.github.io/monaco-editor/ is the same editor as in VS Code, just a bit older at this point, so it could be used to try to repro outside of Electron, in Chromium.

**Comment by PF4Public** [comment]
Unfortunately, cannot recreate this in Chromium 85:
![image](https://user-images.githubusercontent.com/10319700/91728690-2243ea80-ebac-11ea-8464-cd87e4d95bf7.png)

**Comment by PF4Public** [comment]
I have updated Electron to 11 and compiled vscode from master and no longer can reproduce this issue. Looks like it is indeed fixed in 11. Should I close this issue, or wait till next release of vscode arrives, test again and only then close it?

**Comment by deepak1556** [comment]
I would leave this open till insiders with electron 11 goes out.
