### ISSUE TITLE
When using Surface Dial, Focused Editor does not Scroll

### ISSUE THREAD

**Issue by darthtrevino** [microsoft/vscode#104389]
Issue Type: <b>Bug</b>

When using a Surface Dial, the "scrolling" behavior does not align to the selected pane.

![scrollpanes](https://user-images.githubusercontent.com/113544/89814604-38541300-daf8-11ea-877d-151b8da100e9.gif)

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.20185
Remote OS version: Linux x64 4.19.121-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (16.72GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/chtrevin/ws/privacy-dashboard --remote=wsl+Ubuntu-20.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.121-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|7.77GB (6.66GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|2.0.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
vscode-pull-request-github|Git|0.18.0
vscode-styled-components|jpo|0.0.29
graphql-for-vscode|kum|1.15.3
vscode-typescript-next|ms-|4.1.20200809
remote-wsl|ms-|0.44.4

</details>

**Comment by alexdima** [comment]
@darthtrevino VS Code is built with Electron, which is built with Chromium. Can you please also try https://vscode-web-test-playground.azurewebsites.net/ in Chrome? Does the issue reproduce there? How about in Firefox?

**Comment by darthtrevino** [comment]
I tried this out that sandbox in Edge Chromium and the issue did reproduce there

**Comment by alexdima** [comment]
We simply react to `mousewheel` events. This is very weird indeed. It looks like the Surface Dial sends the `mousewheel` events to the center of the screen or something like that and whatever editor is in the center will receive the scroll event.
