### ISSUE TITLE
"Focus Window On Break" setting does not work as expected

### ISSUE THREAD

**Issue by xaviergmail** [microsoft/vscode#104316]
Issue
===
The `debug.focusWindowOnBreak` setting does not work consistently. It seems to work fine with other debuggers (javascript, for example). However, the VSCode window does not gain focus when a breakpoint gets triggered when using the Unity Debugger extension. 

Version Information
===

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-sqlite|ale|0.8.2
glua|aSt|1.1.0
vscode-intelephense-client|bme|1.5.3
dart-code|Dar|3.13.2
flutter|Dar|3.13.2
gitlens|eam|10.2.2
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
csharp|ms-|1.22.1
python|ms-|2020.7.96456
remote-wsl|ms-|0.44.4
vsliveshare|ms-|1.0.2478
material-icon-theme|PKi|4.2.0
platform-settings|run|0.0.2
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.12
ayu|tea|0.20.1
unity-debug|Uni|2.7.5
vscode-icons|vsc|10.2.0
vim|vsc|1.16.0
markdown-all-in-one|yzh|3.2.0

(4 theme extensions excluded)

</details>

Steps to Reproduce
===
1. Install "Debugger for Unity" extension
2. Run the debugger, set a breakpoint and attach to a Unity project
3. Hit Play from the Unity Editor
4. Cause the breakpoint to trigger
5. Notice

Does this issue occur when all extensions are disabled?: N/A - I do not believe this to be an issue specific to the extension at play, considering it does in fact trigger the breakpoint on the VSCode side of things.

**Comment by xaviergmail** [comment]
@weinand I don't think the issue is caused BY the extension itself. VSCode should respect the option regardless of how a breakpoint gets triggered

**Comment by weinand** [comment]
You said that "Focus Window On Break" works fine with other debuggers. 
From this I conclude that there is an issue with the specific extension.
