### ISSUE TITLE
Hotreloading does not work whether using `attach` or `launch`

### ISSUE THREAD

**Issue by rajsinghUSA** [microsoft/vscode#104323]
VSCode Version: 1.47.3
OS Version: Windows 10 v19041 (Build 19041.388)

Steps to Reproduce:

**Hotreloading** does not work whether using `attach` or `launch` with the following `"scripts"` line in `package.json`
```js
    "debug": "NODE_ENV=development DEBUG='knex:*' nodemon --inspect ./server.js"
```
And the following `launch.json`:
```json
{
  "configurations": [
    {
      "name": "Attach",
      "port": 9229,
      "request": "attach",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "type": "pwa-node"
    },
    {
      "name": "Launch via NPM",
      "request": "launch",
      "restart": true,
      "trace": true,
      "runtimeArgs": [
        "run-script",
        "debug"
      ],
      "runtimeExecutable": "npm",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "type": "pwa-node"
    }
  ]
}
```

Does this issue occur when all extensions are disabled?: Yes/No/ Is this no longer possible to test with WSL? It won't even load the project directory because the WSL extensions are disabled.

**Comment by connor4312** [comment]
What do you mean by "does not work"? Does debugging not work? Does the hot reload never occur?

/needsMoreInfo

**Comment by rajsinghUSA** [comment]
> What do you mean by "does not work"? Does debugging not work? Does the hot reload never occur?
> 
> /needsMoreInfo

With the `launch.json` and `package.json` shown, `debugger;` works but hot reload never occurs when a file is saved.

**Comment by connor4312** [comment]
Okay, thanks for the info. This is not something that the debugger controls, I suggest raising the issue on Nodemon.

**Comment by rajsinghUSA** [comment]
This turned out to be a WSL 2 issue, since it does not use inotify: https://github.com/microsoft/WSL/issues/4739

Someone suggested that using VSCode somehow overcomes this issue, but that did not solve the issue for me. I just moved the project to the linux ext4 filesystem and hotreloading works again as expected.

**Comment by connor4312** [comment]
Interesting, thanks for the info!
