### ISSUE TITLE
VS Code stop to work when search for 'DIV'

### ISSUE THREAD

**Issue by BrunoGiubilei** [microsoft/vscode#104393]
I searched for DIV and sent it. It caught everything. I had to shut down Visual Studio.
[https://streamable.com/3ae19u](url)

**Comment by JacksonKearl** [comment]
Thanks for reporting this! Is there any public repo that you can reproduce this on?

**Comment by BrunoGiubilei** [comment]
how can i do that?

**Comment by JacksonKearl** [comment]
Is there any public repository you can share that causes vscode to crash? 

For instance, if you search "let" in the vscode repo (`git clone https://github.com/microsoft/vscode.git`), can you trigger this crash?

**Comment by BrunoGiubilei** [comment]
i would try this tomorrow

**Comment by roblourens** [comment]
Also, it looks like you built Code-OSS yourself. Can you try with an official build?

**Comment by mjbvz** [comment]
Unmarking as bug so this doesn't show up in our verification query
