### ISSUE TITLE
Inconsistent options between "Find" and "Replace"

### ISSUE THREAD

**Issue by sweettyler** [microsoft/vscode#104332]
Issue Type: <b>Bug</b>

1) Open a ".ipynb" file;
2) Select a cell (in edit mode) and press "Ctrl +F", then a search box pops out at the top right corner (ref. attached snapshot). you'll notice options such as "match case" and "match whole word" are not available;
3) However, if I press "Crtl+H", then "match" and "match whole word" are available in find and replace box.

VS Code version: Code - Insiders 1.48.0-insider (2277c8e2a3e1cc630a6397301ba54a1dccd8a60d, 2020-08-07T12:51:53.850Z)
OS version: Linux x64 3.10.0-693.17.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (32 x 2100)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|187.41GB (148.26GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.7.96456
cpptools|ms-|0.29.0
material-icon-theme|PKi|4.2.0

</details>

**Comment by sweettyler** [comment]
I guess this is more like an extension bug so I also reported it in https://github.com/microsoft/vscode-python/issues/13362.

![ctrl_H](https://user-images.githubusercontent.com/49961658/89741125-35074b80-da54-11ea-8211-81a493ac8b6d.png)
![ctrl_F](https://user-images.githubusercontent.com/49961658/89741126-359fe200-da54-11ea-9b86-6c58a4916e86.png)

**Comment by sweettyler** [comment]
according to what was replied by a developer, " CTRL+H is coming from our extension, CTRL+F is provided by VS code for webviews", vscode WebView is actually the root causing the problem.

**Comment by mjbvz** [comment]
Webviews only provide basic search, not replace. In this case, the extension should intercept  ctrl+f to show the same find/replace UI they show for ctrl+h

**Comment by sweettyler** [comment]
I agree that webview does provide basic search function, but it's too basic - not able to match case, whole word, I can't believe it's 2020 now.
