### ISSUE TITLE
Allow for menu contributions in folders of the explorer

### ISSUE THREAD

**Issue by gfrancischini** [Microsoft/vscode#10433]
Would be possible to add a menu contribution only when the object of click is a folder?

"explorer/context": [
        {
          "command": "myCommand",
          "group": "myhroup",
          "when": "resource == folder"
        }
      ],

Thanks

**Comment by jrieken** [comment]
We don't have a resource key ala `isFolder`

**Comment by bpasero** [comment]
@jrieken what would be needed to make this happen from the explorer side? is this low hanging?

**Comment by jrieken** [comment]
Yeah, fairly simple. Create a context key ala `explorerResourceIsFolder` and set that to true/false whenever the selection changes. The same could then be done with files etc. We current have `resourceLangId` and `resourceScheme` defined [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerView.ts#L101).

**Comment by bpasero** [comment]
@jrieken when I debug this call I can see that we do set the resource to be the one of the folder so I would expect this to work already? Folders have a resource too.

**Comment by jrieken** [comment]
Yes, but the URI is sort of internal and cannot be referred to from the `keybinding.json` file and how would you tell from an URI whether the resource is a folder or a file?

**Comment by bpasero** [comment]
@jrieken I see. what about enriching `ResourceContextKey` with the optional knowledge if the resource is a file or a folder? I would think in almost all places the default is that it is a file but in that particular explorer context we actually know exactly if it is a folder or not.

**Comment by jrieken** [comment]
Not a big of that cos it's also used by the editor title. I believe that starting with explorer context keys isn't bad. There will for sure be more requests in that area (`explorerFileFolderIsInsideWorkspace`, `explorerHasMultiselection`, etc, etc). For the editor we have a bunch of `editorXYZ` keys and I would stick to that pattern

**Comment by bpasero** [comment]
I added a new `explorerResourceIsFolder` that can be used to contribute commands to folders in the explorer.
