### ISSUE TITLE
CPU maxes when returning to docking station

### ISSUE THREAD

**Issue by apassy** [microsoft/vscode#104370]
1.  This is persistent across several versions - I have been using VS code since last Sept, and this has happened across all versions.
2.  It is NOT consistent.  I haven't actually gathered data, but I'd say it happens about half the time.
3.  Setup - two laptops connected through a USB3 switch to a Dell USB3 docking station/port replicator, with 3 monitors and single kbd/mouse.  
4. Currently on Win 7 on the machine that it happens on, as I've said multiple VS code versions, I think it's related to the python extension.

The Problem:
When I switch away for a length of time (a quick switch is not usually what does it), when I return, VS code has maxed the CPU, or in some cases, a process spawned by VS code.  I bring up Task Manager, and usually, killing VS code does the trick.  Sometimes I'm required to Kill a python child process, or two, that has become disconnected from the parent VS code window.

It would also occasionally happen when moving between home docking station and work docking station.  Work is a USB-C Dell dual-monitor docking station with a USB-driven third monitor.

To be honest, I know that this is a niche enough problem that you probably can't replicate or fix it, but i thought I'd document it anyway.

**Comment by deepak1556** [comment]
Does this happen when you disable the python extension ? If it does, then can you try our latest insiders https://code.visualstudio.com/insiders ?
