### ISSUE TITLE
Inconsistent indication of keyboard shortcuts

### ISSUE THREAD

**Issue by yannl35133** [microsoft/vscode#104406]
Issue Type: <b>Bug</b>

Some keyboard shortcuts (eg. Open file...) are cleanly indicated on the right of menus, while others (eg. Open Folder...) are indicated between square brackets.
Could you solve this inconsistency?

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 5.4.0-42-generic snap

![image](https://user-images.githubusercontent.com/40719961/89846431-82350b80-db81-11ea-90ac-df1838a86a31.png)

**Comment by yannl35133** [comment]
I get that it's a duplicate of the issue you mentioned, but that one is closed yet the bug is still present.
Why is that so ?

**Comment by sbatten** [comment]
This is an upstream issue with electron. We support custom menus that don't have this issue which you can enable via `window.titleBarStyle` => `custom`. @deepak1556 to comment if there is any change for electron

**Comment by yannl35133** [comment]
I've enabled this feature, but that doesn't mean that the bug is solved. Shouldn't we keep one open issue here, with a link to the corresponding issue for electron, so that other users complaining for this understand it all?
