### ISSUE TITLE
Dimmed Window with HDR

### ISSUE THREAD

**Issue by syntafin** [microsoft/vscode#104420]
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Activate HDR in Windows Settings
2. Open VSC
3. Window is dimmed and editor window is not complete loaded.

Does this issue occur when all extensions are disabled?: Yes

Workaround:  
  
1. Open Terminal/CMD/Powershell
2. Goto folder
3. ``code . --force-color-profile srgb``

That Issue was said to be fixed in https://github.com/microsoft/vscode/pull/81644, referred from old Issue https://github.com/Microsoft/vscode/issues/68069.

**Comment by IllusionMH** [comment]
/duplicate 
This problem is currently tracked in #88491
