### ISSUE TITLE
Clarify documentation on when and where the 'text' for StoppedEvent shows up in the UI

### ISSUE THREAD

**Issue by polinasok** [microsoft/vscode#104475]
My goal is to implement a StoppedEvent when a go program stops due to a segfault. I am considering setting the event's reason to 'exception' or maybe something more custom, but in either case I need a way to report the detailed error to the user. The spec says 
```
   /**
     * Additional information. E.g. if reason is 'exception', text contains the exception name. This string is shown in the UI.
     */
    text?: string;
```
I am setting 'text' in the event I send to the client:
```
[-> to client]{"seq":0,"type":"event","event":"stopped","body":{"reason":"exception","threadId":1,"text":"bad access","allThreadsStopped":true}}
```
But I do not see it displayed anywhere in the UI, including when I hover as suggested in https://github.com/Microsoft/vscode/issues/3101
![image](https://user-images.githubusercontent.com/51177946/89862703-5b64de00-db5d-11ea-980b-26258f25f450.png)
Is this feature still operational? Should it work with any reason? Where should it appear? The only related issue I found is https://github.com/microsoft/vscode/issues/63416, which suggests that this feature worked a while back, but doesn't offer any screenshots with the details.

**Comment by weinand** [comment]
I've moved the issue to VS Code because the discussion has revealed a VS Code implementation issue.

**Comment by isidorn** [comment]
Ok. I will make the change as I suggested above, hover over the whole Session element will show the text if adapter provided it.

**Comment by polinasok** [comment]
I am able to get the hover when raising an exception in Python. The log shows:
``` 
                 "type": "event", 
                 "event": "stopped", 
                 "body": {
                     "preserveFocusHint": false, 
                     "description": "('spam', 'eggs')", 
                     "text": "Exception", 
                     "allThreadsStopped": true, 
                     "reason": "exception", 
                     "threadId": 1
                 }
```
![image](https://user-images.githubusercontent.com/51177946/90058089-1f816400-dc96-11ea-985a-2b9976b42dec.png)

Setting the exact same stopped event fields in my new Go adapter:
```
{"seq":0,"type":"event","event":"stopped","body":{"reason":"exception","description":"Some description","threadId":1,"text":"Exception","allThreadsStopped":true}}
```
I get very different UI behavior. Description is ignored.
![image](https://user-images.githubusercontent.com/51177946/90060610-d7644080-dc99-11ea-8588-582d5a6bb8e3.png)
When I hover, "paused on exception" turns into a control panel
![image](https://user-images.githubusercontent.com/51177946/90062188-28753400-dc9c-11ea-828c-7275a7b53679.png)

So there seems to be more to impacting what the UI shows, then just setting the fields in the Stopped Event. Perhaps, having or not having support for ExceptionInfo plays into this as well?

**Comment by weinand** [comment]
@isidorn any additional insights?

**Comment by isidorn** [comment]
Insiders with my fix is not yet released. Please try this out with VS Code insiders from tomorrow or next week.
As for the description of the exception, that seems like a different but similar issue, can you please file a new issue for this. Thanks
