### ISSUE TITLE
Not recognizing node project

### ISSUE THREAD

**Issue by IamKayrox** [microsoft/vscode#104431]
Issue Type: <b>Bug</b>

Intelisense is missing from my Node project.
In the past this wasn't an issue with this same project.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460S CPU @ 2.90GHz (4 x 2899)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (9.20GB free)|
|Process Argv|C:/Users/Kayrox/Documents/Projects/alfred-ui/|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.4
ng-template|Ang|0.1000.7
gitlens|eam|10.2.2
material-icon-theme|PKi|4.2.0
markdown-all-in-one|yzh|3.2.0

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
There are no suggestions for globals lile `Buffer`?

VS Code should download node definitions if there are imports for built-in node modules (`fs`, `path` etc.) if Automatic Types Acquisition is not disabled.

See https://github.com/microsoft/vscode/issues/103686#issuecomment-667051304 for config and useful links about ATA etc.
