### ISSUE TITLE
Allow editable right hand side when viewing Staged Changes

### ISSUE THREAD

**Issue by tekumara** [microsoft/vscode#104417]
When viewing Staged Changes side by side, the right hand side is not editable.

Would be great to be able to edit the right hand side of the diff.

<img width="914" alt="Screen Shot 2020-08-11 at 5 59 00 pm" src="https://user-images.githubusercontent.com/125105/89872521-6d498e00-dbfc-11ea-9fab-9692ae98f4b9.png">

vscode 1.47.3

**Comment by IllusionMH** [comment]
See https://github.com/microsoft/vscode/issues/91274#issuecomment-590442267
