### ISSUE TITLE
Debugging: Connection to Postgres Database doesn't release connection

### ISSUE THREAD

**Issue by EddieE79** [microsoft/vscode#104455]
VScode version: 1.47.3

When debugging a typescript project in VSCode, connecting to a postgres DB using typeORM, after a few queries connected session to the db just hangs and doesn't return a result.
This only happens when debugging - it runs fine when not debugging.

Reverting VScode  to version 1.46.1 fixed the issue for us.

As reverting the version of VScode fixed the issue it looks more like a change between version 1.46.1 and 1.47.3 had an unexpected consequence on certain aspects of debugging.

Here are some of the other details though
* node 12.18.3
* typescript 3.9.7
* typeORM 0.2.25

**Comment by connor4312** [comment]
Can you please try the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) and see if that works for you?

/needsMoreInfo
