### ISSUE TITLE
VS Code doesn't open links with custom URL schema

### ISSUE THREAD

**Issue by felixbinder** [microsoft/vscode#104429]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

VS code fails to open links of the sort 'marginnote3app://note/29FD177B-8169-451E-A168-A244CCE9614D', ie with a custom URL scheme. They are recognized as links (in markdown files, not otherwise) and are clickable, however, clicking them does nothing. In other applications, they open the correct application (here: MarginNote), VS Code does nothing.

The console shows:
marginnote3app://note/29FD177B-8169-451E-A168-A244CCE9614D ERR Unable to resolve non-existing file '/Users/USERNAMEREDACTED/Cloud/Notes/Grad School/Block Construction/marginnote3app:/note/29FD177B-8169-451E-A168-A244CCE9614D.md': EntryNotFound (FileSystemError): Unable to resolve non-existing file '/Users/USERNAMEREDACTED/Cloud/Notes/Grad School/Block Construction/marginnote3app:/note/29FD177B-8169-451E-A168-A244CCE9614D.md'
	at _handleError (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:657:25)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async l.tryOpen (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/markdown-language-features/dist/extension.js:1:21570)

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
foam-vscode|foa|0.3.1
matlab|Gim|2.0.0
markdown-image|han|1.0.8
vscode-markdown-notes|kor|0.0.13
python|ms-|2020.7.96456
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
vscode-fileutils|sle|3.0.1
code-spell-checker|str|1.9.0
code-spell-checker-german|str|0.1.4
markdown-links|tch|0.6.0
markdown-all-in-one|yzh|3.2.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Where are you clicking the link? In the file source or in the markdown preview?

**Comment by felixbinder** [comment]
This happens for both the preview and the file source

**Comment by Goodwine** [comment]
This bug not only happens in Markdown, it happens with any link provider such as the extension [ragnoroct.linkme](https://marketplace.visualstudio.com/items?itemName=ragnoroct.linkme).

This affects any link to apps like Quip or Slack. For example:
- `quip://DOC_ID_HERE`
- `slack://CHANNEL_ID_HERE`

My expectation is that the appropriate app that handles those links is opened, but instead vscode throws an error saying “Unable to open `''` -  Unable to resolve resource for `LINK_HERE`”

**Comment by patrickmburrell** [comment]
I've been working around this problem by copying the custom URL link and pasting it into Alfred to open it. (Of course, Spotlight works as well.) But using cmd+click would be so much nicer!

This has been difficult to google for because most results from searching for variations on "vscode", "links", "custom URL", "markdown", etc, mention how to use "vscode://" to open a source file. I want to link out of VSCode, not into it! :)

Here's a link where someone seems to have tracked down the source of the problem: https://www.reddit.com/r/vscode/comments/gdryqg/extension_to_make_a_new_url_with_custom_scheme/

My first thought was to solve this with an extension but I've never created one and I'm not sure this functionality is even extensible. If possible, I'd like to work on it.
