### ISSUE TITLE
not able to do Copy and Paste 

### ISSUE THREAD

**Issue by sshude** [microsoft/vscode#104444]
Dear Team, 
Problem -1 : I am not able to copy and paste and sometime I am not able to write a code in my VS code. 

Problem -2: When i am trying to open Terminal window, getting an error - The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 3221225781.

**Comment by Tyriar** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

/label "needs more info" integrated-terminal
