### ISSUE TITLE
Bug Report UX issue when no source is selected

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#104472]
Issue Type: <b>Bug</b>

When no source is selected under "File on", the "Preview on GitHub" button should be clearly disabled. The form cannot be sent unless a source is picked. The dialog does not reflect the invalid state of the UI or direct the user towards the missing input.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (36.52GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/backend/core-web3 --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|Memory (System)|50.14GB (39.13GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|Memory (System)|50.14GB (39.13GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|Memory (System)|50.14GB (39.13GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|Memory (System)|50.14GB (39.13GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
eslint-disable-snippets|drK|1.2.0
vscode-docker|ms-|1.4.1
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|10.2.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.8
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
vs-code-xml-format|fab|0.1.5
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
terraform|has|2.1.1
vscode-esformatter|how|1.6.0
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.4.1
vscode-paste-image|mus|1.0.4
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
lit-plugin|run|1.2.1

(2 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
Currently, validation is performed when clicking "Preview on GitHub", which should highlight any missing fields:

<img width="812" alt="Screen Shot 2020-08-12 at 8 29 51 AM" src="https://user-images.githubusercontent.com/3672607/90034935-15e80400-dc76-11ea-94bf-7e8d896fc2c0.png">

Would showing a validation message next to these fields help?

**Comment by oliversalzburg** [comment]
It's probably a problem with my theme then:
![image](https://user-images.githubusercontent.com/1658949/90036160-f925ed80-dcc2-11ea-9a20-ebce8db75acb.png)

Only now am I seeing the faint asterisks in my UI too.

Maybe a message _would_ help to ensure themes don't interfere.

**Comment by RMacfarlane** [comment]
I added a validation message:
<img width="812" alt="Screen Shot 2020-08-12 at 10 45 45 AM" src="https://user-images.githubusercontent.com/3672607/90049190-5309c180-dc89-11ea-9b58-aadb564b0227.png">

**Comment by oliversalzburg** [comment]
Nice. I'm sure it will save me in the future. Thanks 😊

**Comment by GitMensch** [comment]
@RMacfarlane can you please add a "Preview in Editor" button (sorry for the short-cut of not creating an issue, they tend to get lost very easy and you've adjusted the UX two days ago)? I'm using vscode one a restricted system without any internet access, and can't use it because of the missing "offline" option.
