### ISSUE TITLE
Black Screen if VS Code open for too long

### ISSUE THREAD

**Issue by katlew** [microsoft/vscode#104499]
Hi Allison (PM) & Engineers,

I put the SurfaceBook Laptop on sleep and has VS code open for a while. It ended up with a black screen when I logged back in this morning. After restarting it went back to normal. Please identify what the RCA is for this. I would hate for this to happen to other engineers :(. I have not had these issues with Sublime. Thanks!

**Comment by deepak1556** [comment]
Does this issue happen with our latest insiders https://code.visualstudio.com/insiders ?
