### ISSUE TITLE
Closing a C# code block corrupts text elsewhere in the file

### ISSUE THREAD

**Issue by df-adam** [Microsoft/vscode#10443]
- VSCode Version: Code - Insiders 1.5.0-insider (3313a641ec505098c8625c459e49af3e8f5eb793, 2016-08-11T06:04:17.155Z)
- OS Version: Darwin x64 15.6.0
- CSharp Extension 1.3.0

Steps to Reproduce:

1.  Create a C# class
![screen shot 2016-08-11 at 11 24 41 am](https://cloud.githubusercontent.com/assets/11727578/17599963/5a97f7fe-5fb6-11e6-96bb-5b6427805392.png)

2.  Add the closing brace
![screen shot 2016-08-11 at 11 25 02 am](https://cloud.githubusercontent.com/assets/11727578/17599999/7b91fff4-5fb6-11e6-8c75-81233e27eec4.png)

3.  Observe the corruption in line 1 (using System;)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#654
