### ISSUE TITLE
Problems inside of notebook cells are not highlighted while navigating through problem list

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#104454]
- VSCode Version: 1.48.insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open a notebook that causes a problem (jupyter notebooks will soon support linting if you can't generate a problem otherwise)
2. Click on a problem in the problems window

Expected:
Line in cell is highlighted like it is for normal files

Actual:
Cell is scrolled but no highlighting occurs.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
It turns out to be as-designed, what happens is 

* A problem info in problems panel contains a `range` info
* When click the problem, we will open the editor (either text editor or reveal the cell editor in notebook)
* Then we will select the `range` of text. 

If the range is empty, it's then a single cursor, the line highlight will be rendered. If the range is not empty, then a range of text is selected, we don't render the line highlight but only render the selection highlight.

**Comment by rebornix** [comment]
@rchiodo can confirm if it's what happens under the hood.

**Comment by rchiodo** [comment]
>  If the range is not empty, then a range of text is selected, we don't render the line highlight but only render the selection highlight.

Why is this different than a normal file? It will highlight the line.

**Comment by rebornix** [comment]
@rchiodo it's the same, can you confirm that in both text file and the notebook scenario, the problem has the same range (and they are not empty at all)?

**Comment by rchiodo** [comment]
Here's a notebook after creating a problem and clicking on the problem:
![image](https://user-images.githubusercontent.com/19672699/90265598-aa35a080-de07-11ea-87e7-e4c33acfe4cb.png)

It looks like the range is 3,5

Here's the same problem in a python file:
![image](https://user-images.githubusercontent.com/19672699/90265679-c46f7e80-de07-11ea-8812-6fb4cb709fc6.png)

**Comment by rchiodo** [comment]
Note: I'm working on adding linting to notebooks (and it's not submitted yet) so there's not an easy way to do this without making your own artificial diagnostics for a notebook.

**Comment by connor4312** [comment]
This seems to be quite inconsistent when dealing with multiple editors, recording: https://memes.peet.io/img/20-09-905b2c11-2603-4e8f-906e-6b5107bf6023.mp4

**Comment by connor4312** [comment]
It seems like reliably steps are:

1. Have notebook1 with problems open in the left hand side and nodebook2 open on the right
1. Put your focus in notebook2
1. Click on the problems view
1. notebook1 will open on the right hand side, but the line/code cell will not be highlighted 🐛

**Comment by vuthanhlong94** [comment]
Thank
