### ISSUE TITLE
ANSI color code in Notebook cell output inadvertently switches to HTML output

### ISSUE THREAD

**Issue by brandon-rhodes** [microsoft/vscode#104446]
- VSCode Version: 1.47.3
- OS Version: Linux 5.4.0-42-generic

Steps to Reproduce:

1. Create or open a Jupyter Notebook with VS Code’s notebook extension.
2. Run this Python code in a cell: `print('| \033[31m <b>foof</b> \033[0m |')`

With the standard Jupyter Notebook server running in a Google Chrome tab, the text is printed as normal for Python `print()`, with a bit of color thrown in by the ANSI color escape code:

![image](https://user-images.githubusercontent.com/166162/89931316-00bd9780-dbda-11ea-9248-d913840a1b23.png)

But when this same cell is run in the VS Code Notebook viewer, the angle brackets are not printed but interpreted as HTML “bold”:

![image](https://user-images.githubusercontent.com/166162/89931532-48442380-dbda-11ea-845f-2bd1b44d9dcf.png)

My guess is that when VS Code sees the ANSI escape sequences in the output, it flips to using an `HTML()` object to render the colors, but forgets to HTML-escape all of the normal plain text in the output.

Does this issue occur when all extensions are disabled?: No — with extensions disabled, a Jupyter Notebook displays as simple JSON rather than as an interactive environment.

**Comment by rebornix** [comment]
Since you are VS Code stable, the jupyter notebook experience is provided by the Python extension so please file issue there.

/extPython

**Comment by brandon-rhodes** [comment]
In retrospect, it should have occurred to me that this was an extension behavior. Thanks. Filed as: https://github.com/microsoft/vscode-python/issues/13396
