### ISSUE TITLE
Sync settings are excluded from settings editor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#104401]
` WARN SettingsEditor2: Settings not included in settingsLayout.ts: sync.ignoredExtensions, sync.ignoredSettings, sync.keybindingsPerPlatform`

**Comment by roblourens** [comment]
Oh, these are deprecated. Maybe the error only shows up because I have configured them. Anyway I can add a simple change so that they show up (configured deprecated settings will be shown in the settings UI)

**Comment by isidorn** [comment]
Closing this since PR got merged

**Comment by sandy081** [comment]
To verify

- Open Developer tools console
- Open Settings editor (UI)
- make sure above warning is not shown
