### ISSUE TITLE
Source Control Working Tree does not make it clear which is the current file.

### ISSUE THREAD

**Issue by bsutton** [microsoft/vscode#104405]
When checking code into via 'Source Control' it displays the 'Working Tree'.
The problem is that the UI does not make it clear which version is the 'edit' version and which is the original 'unedit' version.

I will often come back to a project that has some outstanding commits and not remember specially what the work was. (I often get dragged away on other projects with incomplete work).

It will make life much easier if the UI gave a clear indication as to which window was showing the edited vs original version of the code.

**Comment by joaomoreno** [comment]
The original version is always the left-hand side text document which you can't edit at all. You can clearly see it by the colors of the decorations as well:

![image](https://user-images.githubusercontent.com/22350/89933098-dafeb580-dc0e-11ea-8e48-2c9882bd06f2.png)

By editing a line, you're effectively deleting it and adding a new one.

**Comment by bsutton** [comment]
Sorry but you statement is neither correct nor an acceptable method.

There are some circumstance where neither window is editable.
I think this happens after you stage a commit.
This is exactly the moment when you need to know which is which.

Its also not acceptable to suggest that a user has to make bogus edits to determine which window is the update version.

Other ide's recognise this as an issue and provide an appropriate indication.

This is a common workflow issue and a constant annoyance.
