### ISSUE TITLE
Not able to Update successfully

### ISSUE THREAD

**Issue by nedrizv** [microsoft/vscode#104492]
Issue Type: <b>Bug</b>

1. Install any version update 
2. The installation doesn't succeed.
3. VSCode becomes corrupt and Needs to be uninstalled.

Windows 10

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
