### ISSUE TITLE
Allow to rename a workspace file inside VSCode

### ISSUE THREAD

**Issue by NetScr1be** [microsoft/vscode#104497]
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.0-kali2-amd64

Steps to Reproduce:

1. File > Save Workspace as..
     1.1 Apparently this is the only way to name/rename a workspace despite multiple feature requests and bug reports closed because it was deemed unnecessary
2. (With VSCode open) na tovigate folder containing workspace (this was done using the GUI but suspect using CLI would return the same result)
3. Rename the folder (changed one character in this case)
4. VScode immediately changes  to 'No Folder Open'
    4.1. All open files closed
5. Workaround issue via File > Open Workspace
    5.1. Workspace opens but files remain closed

This behaviour shows VSCode is monitoring the workspace filename in realtime, is able to update the VSCode file explorer dynamically but chooses to just dump the workspace rather than **just change the updated name**.

Does this issue occur when all extensions are disabled?: Yes/No

If this is to be a requirement of bug reporting it would help to include instructions on how to do this.

[Documentation](https://code.visualstudio.com/docs/editor/extension-gallery) doesn't specify a method 

Docs do talk about disabling all Extensions (on the fly) via Disable All Installed Extensions command in the More Actions (...) drop-down menu in the Command Palette. _This is not the same as *launching* with extensions disabled_.

Disabling all extensions as above and re-launching VSCode returns the same result

**Comment by bpasero** [comment]
Yes we monitor the workspace file via a file watcher and that currently does not support renames. I think this issue asks for a way to rename workspace files without loosing the list of opened folders inside the current session. Changing to feature request thereby.
