### ISSUE TITLE
delete is not effective

### ISSUE THREAD

**Issue by Mollyll** [microsoft/vscode#104410]
Issue Type: <b>Bug</b>

When I use VSCode to code for several hours, I can't delete code until restart.
I think there was no confict keymaps as I can use delete key when I restart it.

Please reply me if there was any solution. Thanks!

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:33.119Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|MacOS:10.13.6|
</details>

**Comment by mjbvz** [comment]
You are on an old VS Code version. Do you see this with VS Code 1.47+?
