### ISSUE TITLE
Allow debugging all scripts in the npm scripts view/extension

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104403]
Currently the npm scripts view only allows debugging scripts that have `--inspect` or `--inspect-brk` flags, however we're now capable of debugging scripts even when this is not the case.

We should update the npm scripts view to enable debugging on all scripts. This adds capability and simplifies our code as well.

**Comment by isidorn** [comment]
I have verified that debugging is now enabled as a context menu actions on all scripts in the NPM SCRIPTS view.
