### ISSUE TITLE
I am a suggested contact for myself

### ISSUE THREAD

**Issue by deFractal** [microsoft/vscode#104413]
Issue Type: <b>Bug</b>

I signed back into Liveshare, using the same GitHub account, after long enough away that my previous GitHub OAuth token had expired. I then saw myself listed as a suggest contact for myself.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
vscode-firefox-debug|fir|2.9.0
vscode-peacock|joh|3.8.0
chat|kar|0.35.0
python|ms-|2020.7.96456
cpptools|ms-|0.29.0
github-issues-prs|ms-|0.9.2
vsliveshare|ms-|1.0.2478
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
vscode-yaml|red|0.9.1
vscode-vuln-cost|sny|1.3.6

</details>

**Comment by mjbvz** [comment]
Please file this issue against the live share extension
