### ISSUE TITLE
Break on conditional exceptions in node debugger

### ISSUE THREAD

**Issue by cdaringe** [microsoft/vscode#104453]
[ref 1](https://github.com/microsoft/vscode/issues/53795)

# Problem

It is often challenging to narrow the emitter of an exception using node + vscode tooling. For example, many node internals throw exceptions often, as do userland libraries. `skipFiles` is a noble attempt that helps to aide with this problem, but requires that the user collect possibly large domains of possible paths up front, where often it is unknown _whom_ is responsible for emitting an exception. As suggested in similar threads, I cannot reasonably _use_ `<node_internals>` in my skipFiles, as code that is-on-the-fly compiled is put into VM scripts, and is thus ignored. Further, in some cases, i'm OK breaking inside of internals. During _daily_ debugging, I have knowledge about an exception (perhaps stderr output from a prior run), that I really want to hone in on--and thus want a conditional breakpoint to rapidly narrow my search.

**This feature would add a mechanism like conditional breakpoints**, but just to exceptions. Perhaps it would be as follows:

- select `[x] All exceptions` in the debugger
- right click => add condition
- observe placeholder prompt "`err => `
- user fills in function
- user hits enter to save the function

```
err => err && err.message.match(/react/)
```

the need for a lamba here is because the exception of course isn't otherwise in scope--providing a function lets us introspect the error.

**Comment by connor4312** [comment]
I've decided this is best implemented as a formal DAP feature and opened a proposal there: https://github.com/microsoft/debug-adapter-protocol/issues/137 Moving this issue to backlog until that's resolved. (September release at the soonest, as our iteration ends on Monday)

**Comment by rrmistry** [comment]
@connor4312 , would conditional breakpoints be a separate DAP feature request?

I tried but couldn't find an existing issue (open / closed) for this exact feature request.

**Comment by connor4312** [comment]
Conditional breakpoints are already supported in DAP and in VS Code https://code.visualstudio.com/docs/editor/debugging#_conditional-breakpoints

**Comment by rrmistry** [comment]
Never mind. I found it. For anyone else on the same path, the way to set conditional breakpoints is right click the breakpoint and select `Edit Breakpoint`:
![image](https://user-images.githubusercontent.com/25514145/94514952-7d3f2080-01f0-11eb-9631-15e0e6c1d91f.png)

**Comment by connor4312** [comment]
This is implemented in VS Code in https://github.com/microsoft/vscode/issues/111227, which debuggers will need to adopt to enable; I'll use this feature request to track adding to the JS debugger.

**Comment by connor4312** [comment]
This will be in the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Comment by cdaringe** [comment]
I am thrilled! I'll be installing nightly immediately to try this out. @weinand and @connor4312, deep gratitude for this killer feature

**Comment by isidorn** [comment]
@connor4312 adding the on-testplan since this should be covered by a test plan item, thus no further verification should be needed if I am nto mistaken.
