### ISSUE TITLE
Extension with two Activation Events can't be activated by the second activation event if the activation during the first event threw an exception

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#104435]
- VSCode Version: 1.47.3
- OS Version: Win 10

Steps to Reproduce:

1. Create an Extension with the following two activation events "workspaceContains:ANY_FILE", "onCommand:YOUR_COMMAND"
2. Throw an exception in the activation for the event "workspaceContains:ANY_FILE"
3. Then try to activate using the event "onCommand" and check that VSCode will not try to activate it again. It will display "Your command is not available"

Expected Behavior:
The user should be able to activate the extension if the automatic activation failed. In this case the automatic activation event is triggered when the workspace has a certain file name.

Actual Behavior:
The user can't manually activate the extension after the automatic activation failed.

**Comment by alexdima** [comment]
@AllanOricil This is as designed. All activation events call the exact same `activate()` function exported from the extension. Activation can be triggered by multiple events, but it only happens once. If it fails, it will not run again. More information is available at https://code.visualstudio.com/api

**Comment by alexdima** [comment]
> But if it fails, what the user should do to try again? Close and open VSCode?

This is a bug that needs to be fixed by the extension.

> My extension is activate when a file with an extension is added to the root of the workspace or the user manually calls a command. If the user calls the command without configuring a CLI that my extension uses, the error will be thrown. Then after fixing the error, the user tries to call the command again but he can't, because it can only be called once. Can't we negotiate this? I don't think it is a good idea not letting the users try to activate the extension by command a second time. My user will have to close VSCode and open it again o.o

A misconfigured extension should never throw in its `activate` function. If code is written that is sensible, then please use a try-catch around the code that throws to make sure that you do not throw from your `activate` function. In the catch block you can present an informative error to the user. Throwing from the `activate` function indicates that the extension is broken.

**Comment by AllanOricil** [comment]
> > But if it fails, what the user should do to try again? Close and open VSCode?
> 
> This is a bug that needs to be fixed by the extension.
> 
> > My extension is activate when a file with an extension is added to the root of the workspace or the user manually calls a command. If the user calls the command without configuring a CLI that my extension uses, the error will be thrown. Then after fixing the error, the user tries to call the command again but he can't, because it can only be called once. Can't we negotiate this? I don't think it is a good idea not letting the users try to activate the extension by command a second time. My user will have to close VSCode and open it again o.o
> 
> A misconfigured extension should never throw in its `activate` function. If code is written that is sensible, then please use a try-catch around the code that throws to make sure that you do not throw from your `activate` function. In the catch block you can present an informative error to the user. Throwing from the `activate` function indicates that the extension is broken.

Ok I will change it. I threw the error to make the user aware that he did not do one of the steps in the config.
