### ISSUE TITLE
[outline] add "expand all" and "collapse all" options

### ISSUE THREAD

**Issue by ashahrior** [microsoft/vscode#104465]
Clicking on the **Outline** section returns the tree view fully expanded. This seems quite overwhelming at first glance for large codes and also requires extensive scrolling. It would be amazing to have an "**expand all - collapse all**" toggle option. So when going to the outline section, it won't bombard the user with the entire tree-view rather display a more simplified structure where the user would expand and collapse sections according to their preferences afterward. Because currently, at initial click I go to the outline section and then have to manually collapse all the tree views that I don't require at the time to reduce over-exposure.

**Comment by gjsjohnmurray** [comment]
See #53262
