### ISSUE TITLE
Debug Console (Typescript debugging): doesn't sort completions

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#104451]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/6913354/89931774-884adc80-dbc1-11ea-9a81-80b068cebb10.png)

VS Code version: Code - Insiders 1.48.0-insider (4c23fc22ced6d0c1f58215ce91ccd08d0c8a0006, 2020-08-11T10:13:04.551Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|-psn_0_2310708|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
todo-tree|Gru|0.0.178
vscode-dotnet-runtime|ms-|0.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by connor4312** [comment]
Currently the console sorts the method by distance in its prototype chain, and then alphabetically ([code](https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/templates/enumerateProperties.ts#L49-L78) -- sortText is what's used for sorting). This does have the side effect of making deeply hierarchical objects somewhat ugly like this.

Open to discussion for improving this behavior.
