### ISSUE TITLE
Add a setting to hide the number of selected characters in status bar

### ISSUE THREAD

**Issue by jamesderlin** [microsoft/vscode#104471]
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.14-2rodete5-amd64

Steps to Reproduce:

1. Open a file.
2. Select some text.

Does this issue occur when all extensions are disabled?: Yes

See https://github.com/microsoft/vscode/issues/99807 and the other referenced issues.  I consider this to be more a bug than a feature request because:

1. The text displayed in the status bar is ambiguous at best.
2. I suspect it counts the number of UTF-16 code units, and (to me, at least) that seems like a worse choice than bytes or grapheme clusters.
3. The current behavior violates the [stated design goal](https://github.com/microsoft/vscode/pull/17955#issuecomment-275347066) of not wasting space in the status bar for unimportant features, particularly when they could be handled by an extension instead.

I apologize for filing what is clearly a duplicate, but the other referenced issues are all closed and locked, preventing discussion.  So far I have not seen any explanation or justification for showing the selected number of characters.  Is there evidence that the selected number of characters is "important enough for the majority of ...  users"?

**Comment by bpasero** [comment]
This can only be a feature request because removing this from the status bar will cause users that like this feature to be upset. If this feature is not receiving sufficient upvotes in 60 days it will close.

**Comment by jamesderlin** [comment]
> This can only be a feature request because removing this from the status bar will cause users that like this feature to be upset.

Do you have any metrics for users who like this feature?

How is the ambiguity of what is being displayed *not* a bug?

It seems a bit Kafkaesque that:

* The selected character count won't go away because some people might like it.
* People *demonstrably* care about the selected line count, and I'd wager that more people care about the selected line count than the selected character count.  Yet the line count won't be added, even though there have been repeated requests for it, and which *have* met the requirement for 20 upvotes.

IMO the most consistent stance would be to move the selected character count to an extension, possibly shipped and enabled by default (if that's possible).

**Comment by bpasero** [comment]
> IMO the most consistent stance would be to move the selected character count to an extension, possibly shipped and enabled by default (if that's possible).

How is that different from simply adding a setting into the product? The advantage of the current way it works is that the number of selected characters is very close to the line/col indicator (it is the same status item), if it was a separate one it would visually be more disconnected.

> Do you have any metrics for users who like this feature?

I think a good metric for this is to see how many upvotes this issue gets, wouldn't you agree? We show selected characters pretty much since the beginning of the status bar and I have not heard complaints from users so far.

**Comment by jamesderlin** [comment]
> How is that different from simply adding a setting into the product? The advantage of the current way it works is that the number of selected characters is very close to the line/col indicator (it is the same status item), if it was a separate one it would visually be more disconnected.

I agree that moving it to an extension would be a worse experience.

I am asking for *consistency*.  The various requests to add a selected line count were all closed with "Status bar space is limited, and this can be done with an extension".  No thought was given to make the selected number of lines optional (to address the space concern) nor about the lack of visual consistency from forcing it into an extension.

I personally don't really care if the selected number of characters is removed.  I *do* care that it seems to display UTF-16 code points (yuck) and is ambiguous.  I *do* care about having a selected number of lines.  I *do* care that selected characters and selected lines are treated consistently instead of relegating the more popular of the two to second-class status.

> > Do you have any metrics for users who like this feature?
> 
> I think a good metric for this is to see how many upvotes this issue gets, wouldn't you agree? We show selected characters pretty much since the beginning of the status bar  and I have not heard complaints from users so far.

Not really.  Upvotes are biased toward things that prevent people from getting work done or things that are publicized on social networks and toward the whims of vocal people.  Upvotes won't tell you who *uses* the feature but instead would partly tell you who doesn't.  And even then, most people who don't care about the selected character count just mentally tune it out anyway and wouldn't bother with hiding it, especially if there's nothing better (like a selected line count) to occupy the space instead.

**Comment by jamesderlin** [comment]
I was wrong about what I said about the character count being UTF-16 code units.  I tried it again, and either my earlier observation was mistaken or it's something that was fixed since I tried it last.

**Comment by xgdgsc** [comment]
Selected character count is useless. Would be much better if show selected line count.

**Comment by jamesderlin** [comment]
@xgdgsc Seeing as the VSCode team seems to care only about upvoted issues, please upvote this if you agree with it.
