### ISSUE TITLE
Text under icons in activity bar

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#104452]
People who are new to VS Code could benefit if we put names under the extension icons in the activity bar. In user studies with students, they tended to click on text over icons when first exploring the editor. Could we use the default extension name as the text? Something like this:

![image](https://user-images.githubusercontent.com/9721254/89950134-d79f0600-dbdd-11ea-9dfe-0236ae5d697d.png)

**Comment by isidorn** [comment]
I agree this would help new users but it looks ugly imho
Also brings too much details, and nowhere else in vscode we have this pattern of icons + text.
New users would just have to figure to use hover for discovery

Also I like helping new users but I do not think we should sacrifice the existing experience.
So an improved Welcome page is the way to go imho
And on top of the welcome page we can add some overlay which would point to what is what in vscode

**Comment by misolori** [comment]
I think this only works well when you have single word for each view, like Teams:

<img width="100" src="https://user-images.githubusercontent.com/35271042/90650841-3291b800-e1f1-11ea-9b3d-bf3d18a8d3dc.png">

Unfortunately for us we have a lot of views with long words and extension names can be even longer (like `GitHub Pull Requests and Issues`). @isidorn has a point that we don't have this pattern in our other actions that are icon only. I do think having a revamped "User Interface Overview" will help new people discover how to use the tool better.

**Comment by sana-ajani** [comment]
Thanks for the feedback! From UX discussion, we can potentially consider adding explicit call outs to the activity bar icons in the Interface Overview or consider having custom tooltips (like in Slack) that also has the keyboard shortcut

**Comment by isidorn** [comment]
So ideas for explicit call outs:
* When user preses `alt` to navigat the main menu and see the main menu shortcuts that we show the names here
* When the user has the Welcome view open (he might be new and exploring)

But IMHO the custom tooltip which appears faster would be the best solution.

**Comment by misolori** [comment]
Going to move this to https://github.com/microsoft/vscode/issues/115641 since we have that as the exploration for adding labels:

<img width="281" alt="CleanShot 2021-10-05 at 07 31 59@2x" src="https://user-images.githubusercontent.com/35271042/136043758-90fdcd81-0cbc-4c80-a6d1-1383b5e8bd29.png">
