### ISSUE TITLE
Failed to start OmniSharp

### ISSUE THREAD

**Issue by mm75** [Microsoft/vscode#10442]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:49:32.489Z)
- OS Version: Linux x64 4.2.0-42-generic

[INFO] Starting OmniSharp at '/home/jhondoe/www/hwapp'...
[INFO] Started OmniSharp from '/home/jhondoe/.vscode/extensions/ms-vscode.csharp-1.3.0/out/.omnisharp-coreclr/OmniSharp' with process id 15200...
Failed to initialize CoreCLR, HRESULT: 0x80131500
[ERROR] Error: Failed to start OmniSharp

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#655
