### ISSUE TITLE
Markdown language features disabled in WSL

### ISSUE THREAD

**Issue by Zeroji** [microsoft/vscode#104439]
The built-in extension `code.markdown-language-features` is disabled in WSL (Ubuntu 18.04), disabling Markdown Preview and other rich features. I also noticed that many rich features extensions are disabled (HTML, Jake...).

![image](https://user-images.githubusercontent.com/15339858/89918310-2a86b680-dbfa-11ea-83d1-782eafd81ef6.png)
When faced with this alt-text I cannot find any way to install the extension, running `code --install-extension` from within WSL does not work either.

When doing the same test outside WSL (same extensions, same settings, just not in WSL), everything works normally. Preview worked normally about 2 months ago, but I'm not sure when the issue actually started to occur.

- VSCode Version: 1.47.3
- OS Version: Windows 10.0.18363 (WSL Ubuntu 18.04)

Steps to Reproduce:

1. Open a file with language Markdown
2. Try to press `Ctrl+K,V` to open the preview or search `markdown` in the command palette

Does this issue occur when all extensions are disabled?: Not applicable, if all extensions are disabled Remote-WSL does not work

**Comment by mjbvz** [comment]
@sandy081

**Comment by Zeroji** [comment]
I managed to "reinstall" the extension by copying `%appdata%/Local/Programs/Microsoft VS Code/resources/app/extensions/markdown-language-features` into `$HOME/.vscode-server/bin/9189...1b3e/extensions/`, now it works again.

The WSL extensions folder is pretty empty compared to the Windows one, it has less than half the folders. Again, preview used to work in WSL and I didn't manually change things, I simply let VS Code update itself.

**Comment by sandy081** [comment]
Can you please update to latest stable (1.48) and let us know if you are still seeing the issue?
