### ISSUE TITLE
Integrated Terminal Is Not Working

### ISSUE THREAD

**Issue by mangilal23** [microsoft/vscode#104427]
Issue Type: <b>Bug</b>

I Team,

I have added Git as my fefault terminal in VS Code, but when I am trying to open this terminal is opening outside of IDE.
VS Code Version: 1.47.3
Git Varion: 2.23.0.windows.1

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
terraform|has|2.1.1
vscode-docker|ms-|1.4.1
python|ms-|2020.7.96456

</details>

**Comment by Tyriar** [comment]
You're probably not specifying a shell, but just some program that isn't meant to be run as a terminal (ie. git). Try set it using the Select Default Shell dropdown instead.
