### ISSUE TITLE
Issue in debugging the node js code 

### ISSUE THREAD

**Issue by arun9216684797** [microsoft/vscode#104438]
When i am trying to debugging a node js code base,i am getting unbound breakpoints.plss help me

**Comment by connor4312** [comment]
Please collect a trace log using these instructions:

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by arun9216684797** [comment]
@connor4312  as per your instruction i have edited my launch.js.I am running ubantu linux where to find the log file

**Comment by connor4312** [comment]
The location of the log file on your disk will be written to the Debug Console

**Comment by arun9216684797** [comment]
![wqWQWW](https://user-images.githubusercontent.com/20280859/89924891-456c2180-dc20-11ea-8977-6d233e2497b1.png)

**Comment by arun9216684797** [comment]
i have uploaded the logs to here  https://microsoft.github.io/vscode-pwa-analyzer/index.html  i cannot understand the log

**Comment by connor4312** [comment]
Please share the log file with us

**Comment by arun9216684797** [comment]
@connor4312 i have send you a log file  on this email address connor@xbox.com pls look into it [sender email arun111143@gmail.com ]

**Comment by connor4312** [comment]
Thanks for the logs. Please try either of these things:

1. Upgrading from Node 8 (which is end of life as of 2020)
1. Using the [js-debug nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) and setting `enableContentValidation: false` in your launch.json

**Comment by arun9216684797** [comment]
@connor4312 thank you very much bro..It worked

**Comment by connor4312** [comment]
Okay, thanks for confirming!
