### ISSUE TITLE
Report trusted type violation during build and in editor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#104489]
Part of https://github.com/microsoft/vscode/issues/103699 should be to make trusted types violations visible so that

* devs don't re-introduce violations that have been fixed already
* violations become visible and are fixed by devs themselves

One candidate would be the tsec-tool: https://github.com/googleinterns/tsec, e.g run it during builds and on dev-boxes

**Comment by koto** [comment]
That sounds good! I am not sure tsec is good for that *just yet*, but we're currently improving the engine and its rules to have less false-negatives and false-positives. Adding @siegrift and @uraj who are working on it. 

We want to eventually integrate it into the vscode build toolchain to prevent regressions.

**Comment by jrieken** [comment]
Closing since we have everything we need for this. The last and final step will be to cause build failures when TT violations are encountered
