### ISSUE TITLE
Search feature misses untracked git files in search

### ISSUE THREAD

**Issue by apaparazzi0329** [microsoft/vscode#104437]
- VSCode Version: 1.47.3
- OS Version: macOS Catalina (10.15.5)

Not sure if this is intended; however, when searching through the files of my project for a specific url string I was unable to find the string due to it being in an untracked (in .gitignore) file. Upon removing this file from .gitignore the url was easily searched. I also found that the string could be searched if the file it was in was opened in the editor

Steps to Reproduce:

1. Have some tracked and .gitignored untracked files in a local git repo
2. With no currently opened files in the editor, search for anything in the untracked files and realize they cannot be searched

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/question

This is intended behavior. See https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options especially paragraph with

> Also note the Use Exclude Settings and Ignore Files toggle button in the files to exclude box.

To quickly switch whether search or not in excluded files.
