### ISSUE TITLE
broken syntax coloring in Ruby on list used as default parameter

### ISSUE THREAD

**Issue by matkoniecz** [microsoft/vscode#104423]
Issue Type: <b>Bug</b>

![screen03](https://user-images.githubusercontent.com/899988/89882761-8edc5280-dbc7-11ea-9efa-8862ce541ac6.png)

```
module CartoCSSHelper
  def self.test_tag_on_real_data(tags, new_branch, old_branch, zlevels, types = ['node', 'closed_way', 'way'], min = 4, skip = 0)
    types.each do |type|
      test_tag_on_real_data_for_this_type(tags, new_branch, old_branch, zlevels, type, min, skip)
    end
  end
end
```

It is a valid syntax that will confuse code highlighting

VS Code version: VSCodium 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-28T10:50:43.978Z)
OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T6600  @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|3.81GB (0.11GB free)|
|Process Argv|--no-sandbox --unity-launch /home/mateusz/Documents/install_moje/OSM software/bicycle_osm/clearing_cache_run_znajdywanie_celów.sh|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|Lubuntu|
|XDG_CURRENT_DESKTOP|LXQt|
|XDG_SESSION_DESKTOP||
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
kotlin|fwc|0.2.14
csharp|ms-|1.22.1
vscode-unitymeta|PTD|0.0.7

</details>

**Comment by alexr00** [comment]
Moved to the repo we get our syntax highlighting grammar from: https://github.com/textmate/ruby.tmbundle/issues/135
