### ISSUE TITLE
Typescript: definitions from files in tsconfig aren't loaded in editor

### ISSUE THREAD

**Issue by angusmglfraser** [microsoft/vscode#104482]
Issue Type: <b>Bug</b>

1. Open a typescript project
2. Include a reference to a file with type definitions in the `files` attribute of tsconfig.json
3. Open a typescript file that uses those types defined in that file
4. The editor is filled with warnings

I've found that as a workaround you can open the definitions file in the editor, but if I then open another typescript file I have to reload the editor tab with the definitions. 

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.33GB free)|
|Process Argv|--disable-extensions .|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by mjbvz** [comment]
It sounds like a configuration issue with the project

If you believe this is a bug, please share an example project so we can investigate

**Comment by angusmglfraser** [comment]
https://github.com/angusmglfraser/vscode_ts_files_example

Here's an example. If you open only `index.ts`, the editor will show a warning for the reference to `Phaser` even though it builds without issues. If you open the type definition file at `node_modules/phaser-ce/typescript/phaser.d.ts` in another tab the editor warnings aren't shown anymore.
