### ISSUE TITLE
Persist character encoding of open files across restart

### ISSUE THREAD

**Issue by bruceiv** [Microsoft/vscode#10444]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 12.04

Steps to Reproduce:
1. Open a file.
2. Re-open the file using a non-default encoding (e.g. Windows 1252).
3. Close VS Code.
4. Re-open VS Code; layout of editor, open files, etc. will be persisted, character encoding will not be.

Expected behaviour:
Once I have explicitly re-opened a file in a different encoding, that encoding should be persisted along with the other session state (note that I am not asking for encoding auto-detection here, just that I don't have to manually specify it for the same open file every time I restart VS Code).

**Comment by bpasero** [comment]
Pushed a change to persist and restore encodings configured for any opened editor. Once an editor is closed and opened again the encoding will be picked again from the files.encoding setting. The only exception are when using `UTF-8`, `UTF-16 LE` and `UTF-16 BE` with a BOM where we can auto-detect the encoding.
