### ISSUE TITLE
When saving files, VScode will remove all file content.

### ISSUE THREAD

**Issue by gjes86077** [microsoft/vscode#104424]
- VSCode Version: 1.47.3
- OS Version: Windows 10 
![](https://ftp.bmp.ovh/imgs/2020/08/3a54e95a3148d548.png)
Steps to Reproduce:

1. edit script (php , js , css...)
2. save
[video](https://youtu.be/zw6IltuYI0w)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Are you sure this reproduces when extensions are disabled? Make sure to restart VS Code after disabling extensions

**Comment by aitc-h** [comment]
From the video it seems that the button they are pressing is not save. This could be an issue with the recording, but needs clarification.

**Comment by gjes86077** [comment]
> From the video it seems that the button they are pressing is not save. This could be an issue with the recording, but needs clarification.

My setting is auto saved when without focus. so when I leave the edit panel VS code will auto save.

> Are you sure this reproduces when extensions are disabled? Make sure to restart VS Code after disabling extensions

I am sure that,extensions is disabled. and I had tried to reinstall VS code but still....
