### ISSUE TITLE
Include select service flow into the configure command and turn on sync wizard

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#104496]
In order to make the select service more discoverable and to help the user understand that it's a thing, we should add it to the flow for turning on settings sync _for Insiders only_:

Step 1:

![image](https://user-images.githubusercontent.com/2193314/90025240-b506fe80-dc6a-11ea-9e21-bc0532bba5a0.png)

Step 2:

![image](https://user-images.githubusercontent.com/2193314/90025231-b2a4a480-dc6a-11ea-82d6-12fd0c6bc3a0.png)

Step 3: Account selection

We should also roll the select service into the `Settings Sync: Configure...` command and remove the extra select service command.

**Comment by sandy081** [comment]
TBH I am not a big fan of adding too many steps to the flow, might be a bad user experience. It would be nice if all configuration is available in single step. For eg., It would be nice, if we can show the option to use stable service in the first step itself.

**Comment by Tyriar** [comment]
This will be a much bigger problem when syncing doesn't work as expected for users of Codespaces. The proposal is a way to allow desktop Insiders users to discover and fix the problem themselves instead of reporting issues to us and Codespaces.

**Comment by sandy081** [comment]
Sorry, attached the fix to the wrong issue.

**Comment by sandy081** [comment]
Insiders user can now select the settings sync service while turning on sync.

![Kapture 2020-09-17 at 20 28 00](https://user-images.githubusercontent.com/10746682/93512311-6cef9180-f924-11ea-866d-03427c28f467.gif)


To sync with another service, turn off and turn on again.

**Comment by sandy081** [comment]
To verify:

- Open VS Code insiders
- Turn on Settings Sync (if it is already turned on, turn it off and turn it on)
- Make sure you are asked to use insiders or stable settings sync service while turning on (during turn on flow)
- Select the service and make sure that data is synced correctly (You can use your VS Code stable client to verify sync if you are using stable settings sync service)

**Comment by roblourens** [comment]
I remember seeing this in the past but I don't see the service selection now. I see the configuration step then the account picker and that's it...

**Comment by sandy081** [comment]
I still see it. Please check if you have configured settings sync store in settings, if so remove it and try.
