### ISSUE TITLE
Maxed-out searches gives different results with context lines

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#104400]
When a search is maxed out (10k results+), adding context lines causes the total number of results to decrease.

For instance:
1. Search "test" in search editor, see 10k results
2. Add context lines, see results drops to like 4k.

I noticed this at first with the JS search implementation and figured the search provider impl was incorrect, but then saw it also with ripgrep, which leads me to think core has some incorrectness.

Potentially limiting total result lines to 10k vs number of results? 

cc @roblourens

**Comment by JacksonKearl** [comment]
Confirmed searches are ending as limitHit at around 10k lines, including context, @roblourens do you think that's expected or should it always give 10k results, even if that might take many more thousands of lines?

**Comment by roblourens** [comment]
The motivation for having a limit is

- Tree perf
- You probably want to scope down your search if you have 10k results

I think that from an API perspective, `maxResults` should be results, not lines

**Comment by JacksonKearl** [comment]
I agree it's a lot of content, but it's also all content the user asked for - having 10k results in the viewlet then running the same search in the editor and getting 4k seems much more unexpected. Unless defaults are changed, it would only end up being 30k lines, which isn't terribly much for a monaco.

**Comment by JacksonKearl** [comment]
Played around with maxed out searched with 20+ context lines and performance seemed reasonable given the ~400k lines (probably decently fewer than that because of overlaps).
