### ISSUE TITLE
skipFiles are not skipped

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#104421]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/1658949/89878371-be885c00-dbc1-11ea-8c4b-f2f153c48639.png)

I have launch configurations that specify `"skipFiles": ["<node_internals>/**/*.js"]`, but the files I expect to be skipped aren't.

I expect the files to be skipped to not be stepped into by the debugger. I also expect the names of the skipped files to be displayed dimmed in the debugger call stack.

None of this is the case and I'm constantly stepping into `async_hooks.js`.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (41.36GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/backend/core-web3 --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3672)|
|Memory (System)|50.14GB (42.75GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
eslint-disable-snippets|drK|1.2.0
vscode-docker|ms-|1.4.1
remote-containers|ms-|0.128.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|10.2.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.8
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
vs-code-xml-format|fab|0.1.5
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
terraform|has|2.1.1
vscode-esformatter|how|1.6.0
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.4.1
vscode-paste-image|mus|1.0.4
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
lit-plugin|run|1.2.1

(2 theme extensions excluded)

</details>

**Comment by oliversalzburg** [comment]
Following the steps outlined https://github.com/microsoft/vscode-js-debug#nightly-extension and using the nightly build of the new debugger, resolves the situation to meet my expectations. The nightly build seems unstable though as it already pops up error messages right after installing it.

**Comment by connor4312** [comment]
Thanks for confirming the nightly fixes it. What's the error message that pops up?

**Comment by oliversalzburg** [comment]
I'll try to reproduce it again tomorrow and report it over in the js-debug repo, but right now I've managed to end up in a situation without the nightly installed but being unable to re-enable the builtin debugger. It worked pretty well though after the first impression.

**Comment by connor4312** [comment]
Okay. Closing this issue as a dupe since as you saw it's fixed on nightly. Please follow up with the error message if you see it again. You can open a separate issue for us if you're stuck being unable to re-enable the built-in extension.

/duplicate
