### ISSUE TITLE
Open Webview with a specified Width

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#104433]
I would like to open the Webview with a specified Width. It could be placed in the options.

**Comment by mjbvz** [comment]
Can you share your used case?

**Comment by mjbvz** [comment]
Closing this due to lack of follow up.

Possible use cases may fall under https://github.com/microsoft/vscode/issues/46585. Not in favor of supporting fixed width webviews because webview are shown in normal editor groups that normal text files can also be opened in
