### ISSUE TITLE
Allow workspace file to be named .code-workspace

### ISSUE THREAD

**Issue by janderudder** [microsoft/vscode#104418]
A request for a tiny feature.

The extension of workspace files is quite plain and descriptive, as it is `code-workspace`. 
But the editor won't recognize a workspace file named just `.code-workspace` (the file is named only with a point and the extension). 
For now, at least on Windows with Code 1.47.3, it seems impossible to:
- save a workspace under that name from within the editor
- restore a workspace of that file name 

Having a `.code-workspace` file at project's root would look nice and stand as any other project's tool configuration file. There should also be, imo, a setting to permit loading this anonymous workspace as the default when opening a folder, if present. Additionally or alternatively, Code could look into `.vscode/` for default workspace.

**Comment by gjsjohnmurray** [comment]
Previously came up as #73326 and @bpasero suggested it could be taken on by a contributor. But he subsequently closed it.

**Comment by janderudder** [comment]
Oh ok, sorry, searched but didn't find.
