### ISSUE TITLE
Insiders "Restart to Update" should always check for the latest

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#10440]
- VSCode Version: Code - Insiders 1.5.0-insider (3313a641ec505098c8625c459e49af3e8f5eb793, 2016-08-11T06:07:38.135Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Delay update because I'm in the middle of something
2. Forget (or not convenient to update) until the next morning
3. Help -> Restart to Update & Install
4. Wait for a few minutes or do Help -> Check for Updates
5. Another build is available
6. Restart to update & install again

It would be nice if when restarting to update, it would check for the most recent installer and install that, instead of installing and then checking again, so that I need to install again.

**Comment by joaomoreno** [comment]
#9546
