### ISSUE TITLE
Open last active file when closing a file

### ISSUE THREAD

**Issue by aroemen** [Microsoft/vscode#1044]
It would be nice to have a feature to open the most recent active file when the current file gets closed. Ideally this would be a configurable options.

**Comment by stevencl** [comment]
Thanks for the suggestion. It's on our UX backlog and is something we would like to work on at some point in the near future.

**Comment by warpdesign** [comment]
+1

**Comment by bpasero** [comment]
This is on plan for June with our tabs work.

**Comment by warpdesign** [comment]
@bpasero that's good news! Any idea when this will reach insiders build ?

**Comment by bpasero** [comment]
Probably next week after the May release is wrapped up.
