### ISSUE TITLE
opening new document replaces the one in an existing tab

### ISSUE THREAD

**Issue by pradhul-dev** [Microsoft/vscode#10445]
- VSCode Version: 1.4.0
- OS Version:Ubuntu 14.04

Steps to Reproduce:
1. Open a document from the sidebar menu
2. Open another document from the sidebar menu, code won't create extra tabs for showing the new document but replaces the existing one

This issue is not always reproducible and sometimes this happens while opening a 3rd window, instead of creating a 3 rd tab it will replace the 2nd

**Comment by bpasero** [comment]
`"workbench.editor.enablePreview": false`

**Comment by pradhul-dev** [comment]
thanks ,not quite understood even after reading [this](https://github.com/Microsoft/vscode/issues/8496) will try that and update here if the problem happens again.
