### ISSUE TITLE
Tree no longer shows progress when expanding slow folder

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10459]
- expand a large folder (tests/baseline in TypeScript repo is a good one)

=> expand takes 30 seconds and you do not see the spinning folder animation we used to have so as a user you think everything is fine and the folder is empty.

**Comment by joaomoreno** [comment]
I haven't touched it since forever... didn't you mess around with [SVG icons recently](https://github.com/Microsoft/vscode/blob/release/1.4/src/vs/base/parts/tree/browser/loading.svg)?

**Comment by bpasero** [comment]
@joaomoreno nah, this is out of sources and there the SVGs are untouched.
