### ISSUE TITLE
open *.min.js  30% cpu usage stuck

### ISSUE THREAD

**Issue by mj520** [microsoft/vscode#104539]
open *.min.js 30% cpu usage stuck
example file: https://cdn.bootcdn.net/ajax/libs/jsoneditor/9.0.3/jsoneditor.min.js

Sometimes it will be stuck when punching in, and a lot of rg.exe appears
![image](https://user-images.githubusercontent.com/6768732/90113439-f0e1b700-dd83-11ea-9389-e03b1c9c849e.png)

**Comment by mj520** [comment]
![image](https://user-images.githubusercontent.com/6768732/91019250-48eda880-e623-11ea-92fb-bfd38debd1dd.png)

**Comment by mj520** [comment]
Suddenly there will be hundreds of processes in the search, and then they will be stuck. The memory takes up 4g+, the CPU usage is very high, and it cannot be operated.

**Comment by roblourens** [comment]
What did you do before this? Did you run a search? Also, do you have lots of workspace folders in this window?

**Comment by mj520** [comment]
windows   two react typescript project, When there is no search,open *.min.js or   js or ts will be very stuck .Don't know what triggered the search

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by mj520** [comment]
The last two versions have not found this problem
