### ISSUE TITLE
cursor blink

### ISSUE THREAD

**Issue by parisgraphe** [microsoft/vscode#104509]
Issue Type: <b>Bug</b>

Hey VSCode 🙂 
Why is the cursor stop blinking after a while when I've selected other than the default blink?
Love you anyway 😘

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

**Comment by alexdima** [comment]
This is intentional and it is to save your battery life, or if you prefer, to save your CPU cycles. For custom animations, which actually run at 60FPS or more, we stop the blinking cursor after about 10 blinks or so. That is to not consume CPU when you are not doing anything (i.e. idle).
