### ISSUE TITLE
Unterminated string literal.

### ISSUE THREAD

**Issue by yelloxing** [microsoft/vscode#104546]
stay demo.html Error adding code similar to the following:

```html
    <script>

        var temp="</script>";

    </script>
```

**Comment by yelloxing** [comment]
Version:1.47.3

Electron:7.3.2

Chrome:78.0.3904.130

Node.js:12.8.1

V8:7.8.279.23-electron.0

OS:Windows_NT_x64 10.0.18362

**Comment by yelloxing** [comment]
![捕获](https://user-images.githubusercontent.com/23074691/90116589-47e98b00-dd88-11ea-91fe-d672b9100faf.PNG)

**Comment by IllusionMH** [comment]
That how script tags work in HTML?
![image](https://user-images.githubusercontent.com/1312662/90122831-9423d380-dd66-11ea-863a-d6544fd87a89.png)

See https://stackoverflow.com/questions/1659749/script-tag-in-javascript-string
