### ISSUE TITLE
extension host terminated unexpectedly

### ISSUE THREAD

**Issue by arisdanang** [microsoft/vscode#104572]
when i open my Reactjs project in VS Code,it shows the alert "extension host terminated unexpectedly"

**Comment by alexdima** [comment]
@arisdanang 
Does the extension host crash when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)?
