### ISSUE TITLE
Error c++ color when using "/** blabla **/" to comment out codes

### ISSUE THREAD

**Issue by heroes999** [microsoft/vscode#104544]
![image](https://user-images.githubusercontent.com/13531432/90111056-aca0e780-dd80-11ea-8efc-eb3216a00480.png)

As you can see from the pic, all codes after comments( /** blabla **/) are ill colored.

mac vs version: 1.47.3
extension installed: c/c++ && c/c++ intellisense
color theme: Visual Studio 2019 Theme

**Comment by alexr00** [comment]
If you disable the C++ extension do you still see the issue?

Can you please provide a copy pastable example?

**Comment by heroes999** [comment]
1. the issue remains after I disable both C/C++ extension and C/C++ Intellisense
2. copy pastable example as following:
/***************************************************************************
 *
 * Copyright (c) 2017 xx.com, Inc. All Rights Reserved
 *
 **************************************************************************/

/**
 * @author heroes999
 * @brief
 *
 **/

#ifndef TEST_H
#define TEST_H

#include <iostream>

DECLARE_switch(test_glag);

namespace A {
namespace B {

class Test {
public:
    void func();
};

![image](https://user-images.githubusercontent.com/13531432/90354737-ba09ea80-e07c-11ea-85fd-86ab5e645cfa.png)

@alexr00

**Comment by alexr00** [comment]
Thanks for the example. I'm not seeing the same issue. Can you try running all extensions disabled?

![image](https://user-images.githubusercontent.com/38270282/91732566-b01dd680-eba8-11ea-9fbb-ff4b60246a40.png)
