### ISSUE TITLE
Make SCM view good again

### ISSUE THREAD

**Issue by fernandopsilveira** [microsoft/vscode#104588]
Issue Type: <b>Feature Request</b>

New unfinished SCM view just sucks!

Why is it so hard simply give an option to show only selected repos?
Oh, wait, it's not... You just don't want to.

This is not the right way to do open source community software.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
Closed as as going against our [code of conduct](https://github.com/microsoft/vscode#code-of-conduct)
