### ISSUE TITLE
contributes.commands disabled commands bad documentation

### ISSUE THREAD

**Issue by retepaskab** [microsoft/vscode#104549]
- VSCode Version: 1.47.3
- OS Version: Win10

Steps to Reproduce:
https://code.visualstudio.com/api/references/contribution-points#contributes.commands
"However, the Command Palette doesn't show icons nor disabled commands. The editor context menu, on the other hand, shows disabled items but doesn't show the category label."
It is the opposite, context menu shows only enabled commands, and command palette shows all commands.

Does this issue occur when all extensions are disabled?: Yes/No
I tested this with my extension so this makes no sense to check disabled.

**Comment by jrieken** [comment]
> I tested this with my extension so this makes no sense to check disabled.

Show me the code, allow me to reproduce this

**Comment by retepaskab** [comment]
https://code.visualstudio.com/api/extension-guides/command This clears it up, the enablement property wasn't mentioned and menus.commandPalette wasn't explained at the contribution points page.

**Comment by retepaskab** [comment]
Could you make it clearer there, or giving a link for further explanation?

**Comment by jrieken** [comment]
I still don't understand the issue here
