### ISSUE TITLE
Drag and drop vsix from explorer not installing extension

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#104506]
1. Have two instances of VS Code open (one w/ a vsix file another w/ extensions view)
2. Drag a vsix file from one instance to the other's extensions view
3. :bug: nothing happens

Would expect this to work since the explorer supports dragging and dropping files across instances.

**Comment by lszomoru** [comment]
At the moment we only support dragging and dropping files from the desktop, and not from another instance of VSCode.

**Comment by lszomoru** [comment]
We did recently add the capability to right click on a VSIX in the explorer and install it, so that should cover this scenario.
