### ISSUE TITLE
the screen seems to be black and white

### ISSUE THREAD

**Issue by Andrew-Samir** [microsoft/vscode#104515]
[Issue](url

) Type: <b>Bug</b>

Visual studio code screen always make black and white dots when i run it 

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (7.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.3.71659

</details>

**Comment by Andrew-Samir** [comment]
There is a screenshot

**Comment by mjbvz** [comment]
Looks like the screenshot did not upload. Please upload it again through GitHub

**Comment by Andrew-Samir** [comment]
[image: 117649307_422227962058538_8299422017693613576_n.png]

**Comment by Andrew-Samir** [comment]
Sry there was an error uploading on github

**Comment by mjbvz** [comment]
Still didn't work. Make sure to use GitHub instead of email

**Comment by Andrew-Samir** [comment]
![117649307_422227962058538_8299422017693613576_n](https://user-images.githubusercontent.com/62807873/90076287-a28ad480-dcff-11ea-974e-f9f8967bb57b.png)

**Comment by deepak1556** [comment]
Does this happen for any color theme ?

can you check if the issue happens with exploration build https://az764295.vo.msecnd.net/exploration/45f2f912b8c3bdf45bb92dc613b902136a1b60ed/VSCodeUserSetup-x64-1.49.0-exploration.exe

**Comment by IllusionMH** [comment]
Looks like #93356 or #94523

Usual fix is to disable hardware acceleration if exploration buid doesn't work.

**Comment by Andrew-Samir** [comment]
Thank you disabling hardware acceleration fix it

**Comment by deepak1556** [comment]
@Andrew-Samir can you also try the exploration build without disabling hardware acceleration, I would like to confirm if newer runtime fixes the gpu issue. Thanks!

**Comment by Andrew-Samir** [comment]
I did try it but unfortunately it doesn't work

**Comment by deepak1556** [comment]
thanks for confirming, that helps
