### ISSUE TITLE
Flaky test: showQuickPick, select first two

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#104554]
```
1) vscode API - window showQuickPick, select first two:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

```

Build https://dev.azure.com/vscode/VSCode/_build/results?buildId=50441&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=d494b5db-eef8-5766-984e-01186010c86f&l=274

Found this one that I filed before which maybe is related: https://github.com/microsoft/vscode/issues/70887

**Comment by chrmarti** [comment]
Added diagnostic output for the next time it fails.

**Comment by bpasero** [comment]
I have not seen this one failing in a very long time.

**Comment by TylerLeonhardt** [comment]
Same. Let’s close it

**Comment by bpasero** [comment]
```
  1 failing
  1) vscode API - window
       showQuickPick, select first two:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\_work\1\s\extensions\vscode-api-tests\out\singlefolder-tests\window.test.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=166511&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6a86faf8-ed15-56db-877e-46756fb8e8fa&l=683

**Comment by TylerLeonhardt** [comment]
Closing optimistically
