### ISSUE TITLE
Extension is enabled on 'SSH: *’, but disabled locally.

### ISSUE THREAD

**Issue by neveroldmilk** [microsoft/vscode#104533]
- VSCode Version: 1.47.3
- OS Version: Windows 10 1909 OS inside version 18363.900 (Windows_NT x64 10.0.18363)

1. The client PC uses an ssh connection to a remote Ubuntu 20.04 LTS server to develop python and C++ programs.
2. Install the python, C/C++, and all other extensions.
3. All installed extensions' status is marked with an exclamation mark, and show status "Extension is enabled on 'SSH: *’, but disabled locally."
4. Disable and enable all extensions do not work. Reload vs code and reboot both the client and host computer does not work.

Does this issue occur when all extensions are disabled?: Yes.

**Comment by sandy081** [comment]
> All installed extensions' status is marked with an exclamation mark, and show status "Extension is enabled on 'SSH: *’, but disabled locally."

Where are you seeing this status? Are these extensions are under local installed extensions section? Can you please provide a screenshot of it?

**Comment by neveroldmilk** [comment]
> > All installed extensions' status is marked with an exclamation mark, and show status "Extension is enabled on 'SSH: *’, but disabled locally."
> 
> Where are you seeing this status? Are these extensions are under the local installed extensions section? Can you please provide a screenshot of it?

In the client computer's extension management window, the screenshot is attached. You may find that all the extensions used locally are marked as "disabled locally". The more odd thing is that these extensions marked as "disabled" may function properly.

![D9AFD76F82334D3ABD252C99E5BE0B59](https://user-images.githubusercontent.com/5287765/90389470-34a62a80-e0bc-11ea-9a2e-4a38fd488fd6.jpg)

**Comment by sandy081** [comment]
As the message says these are enabled on SSH machine. You have these extensions installed both locally and also in SSH machine and since these extensions can run only on SSH machine they are blurred out and you can see them enabled under SSH installed extensions section.
