### ISSUE TITLE
Better "Debug: Open link" with button and saved URL

### ISSUE THREAD

**Issue by cyrilletuzi** [microsoft/vscode#104585]
First, thank you for the new `Debug: Open link` feature in version 1.48, it is really awesome!

I have 2 ideas that would make this feature even better:

1. Adding a button to launch it directly from the `Run and debug` tab (instead of having to open the Palette). Currently the `Run and debug` tab only proposes to create a `launch.json` file, or to use Node.js Debug Terminal, but now it would be simpler to propose the `Open link` feature directly.

2. It would also be great if, when the URL is filled, it is automatically saved in `.vscode/settings.json`, to avoid to have to fill it again every time.

**Comment by isidorn** [comment]
As far as I know @connor4312 added this, thus forwarding this issue to him.

**Comment by connor4312** [comment]
Thanks for the suggestion, I have implemented both in the linked commit

**Comment by cyrilletuzi** [comment]
@connor4312 Thank you 👍🏻
