### ISSUE TITLE
VSCode considers *.h files as C, not C++, despite files.associations settings

### ISSUE THREAD

**Issue by nmusolino** [microsoft/vscode#104504]
**Steps to Reproduce:**

1.  Open a C++ project where the C++ header files have a `.h` extension. 
2.  Check the icons in the file explorer.
![image](https://user-images.githubusercontent.com/3150861/90039681-f9a78f80-dc94-11ea-8f31-0469444a01ec.png)

This is essentially the same issue as #42279, which was closed.

My workspace settings contain the following (copied as JSON from Settings dialogue):
```
"files.associations": {
  "*.h": "cpp"
}
```

To open this project, I am using the "Remote - SSH" extension, although I have no reason to think that is related to the problem.

**Extensions:**
* Local:  Remote - SSH; Remote - SSH: Editing Configuration Files
* Remote: None

**VSCode details** (copied from Help > About):

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.14.186-146.268.amzn2.x86_64

**Comment by bpasero** [comment]
I see the following class on the icon:

```
monaco-icon-label file-icon test.h-name-file-icon h-ext-file-icon ext-file-icon cpp-lang-file-icon explorer-item
```

So maybe the file extension class is winning over the language mode?

**Comment by aeschli** [comment]
The seti theme explicitly associates the `.h` file extension with a `c` icon with a specific color:
https://github.com/jesseweed/seti-ui/blob/719e5d384e878b0e190abc80247a8726f083a393/styles/components/icons/mapping.less#L26

This overrides our language associations.

**Comment by aeschli** [comment]
We are importing the Seti theme from https://github.com/jesseweed/seti-ui.
To request a change please file an issue there. Maybe they can change the `.h` icon to a `H` ?
