### ISSUE TITLE
VS Code 1.48 won't restore last window positition/state and folder when reopened

### ISSUE THREAD

**Issue by leandro-manifesto** [microsoft/vscode#104597]
Issue Type: <b>Bug</b>

1. Place VS Code's window somewhere other than the initial position
2. Open any folder in VS Code
3. Close VS Code
4. Reopen VS Code

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor              (12 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor              (12 x 3793)|
|Memory (System)|15.95GB (8.18GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.1.0
better-toml|bun|0.3.2
EditorConfig|Edi|0.15.1
git-graph|mhu|1.25.0
csharp|ms-|1.22.1
remote-wsl|ms-|0.44.4
rust|rus|0.7.8
unity-debug|Uni|2.7.5

</details>

I updated to VS Code 1.48 today and found out that it won't restore last window positition/state and opened folder.
I have projects on both Windows and WSL and neither of them are being reopened.
I open VS Code through a shortcut that calls the `Code.exe` installed in my user's AppData folder without any extra arguments.
I also tested with the `--disable-extensions` flag through `cmd` and it didn't work as expected either.

**Comment by bpasero** [comment]
I cannot reproduce, I believe something is not well configured on your system.

**Comment by leandro-manifesto** [comment]
Yeah, I started it up today and its working fine.

The ONE thing I changed was that I had renamed my computer's network name and didn't restart right away.
