### ISSUE TITLE
Slack community link no longer active

### ISSUE THREAD

**Issue by polinasok** [microsoft/vscode#104507]
Following instructions here: https://github.com/microsoft/vscode/wiki/Feedback-Channels#slack
Using the link to join the Slack workspace https://aka.ms/vscode-dev-community I get:
![image](https://user-images.githubusercontent.com/51177946/90045781-65353100-dc84-11ea-99ea-a9f71f375428.png)

**Comment by eamodio** [comment]
This should now be resolved.
