### ISSUE TITLE
If a workbench hover is too wide for a view, it ends up covering the row its for

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#104508]
Related issue: If a hover is too wide for the tree, it seems to cause it to move down and ends up covering the row its for

Here the view is wide enough and its fine

![image](https://user-images.githubusercontent.com/641685/89992716-ac56fe00-dc53-11ea-828a-57cc2b7fb419.png)

But here its too narrow, and you can't see the item for which the hover is for

![image](https://user-images.githubusercontent.com/641685/89992741-b678fc80-dc53-11ea-9e71-5211899a10e2.png)

_Originally posted by @eamodio in https://github.com/microsoft/vscode/issues/104058#issuecomment-672729077_

**Comment by Tyriar** [comment]
@eamodio verifying this one early would be good, I'm not 100% sure if it fixes all cases but it does fix the case I was testing.

**Comment by eamodio** [comment]
@Tyriar its better, but it seems like it can still happen if the area is narrow enough to cause the hover to wrap, then it will cover the hovered upon item.

**Comment by eamodio** [comment]
@Tyriar I figured out the issue only happened with a window border (since it adds a 2px border)

**Comment by roblourens** [comment]
How do I get these hovers in gitlens @eamodio? Is there a vsix to download?

**Comment by eamodio** [comment]
Put your sidebar on the right, and then you should be able (not) see it with any custom tree tooltip. So any GitLens view, just hover over an item on the right edge and it should display (wrap if needed) without overlapping the item you are hovering on. Also make sure to use a theme or set the workbench customization for a window border.
