### ISSUE TITLE
Add Education extension category

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode#104568]
- [x] Add category to marketplace @fiveisprime @prashantvc
- [x] Update completions for package.json @sandy081
- [x] Update completions for extensions view @sandy081
- [x] Update completions for cli @sandy081
- [ ] Update documentation @fiveisprime

**Comment by joaomoreno** [comment]
VSCE doesn't hardcode categories.

**Comment by fiveisprime** [comment]
Thanks @joaomoreno, I wasn't sure so figured I'd cover it just in case. :)

I opened an issue with the marketplace team to get this onto the sprint plan.

**Comment by tanhakabir** [comment]
Reopening for the last 2 tasks

**Comment by sandy081** [comment]
@tanhakabir I think we can check off 4th item right?

**Comment by tanhakabir** [comment]
Ah I didn't test this but if the constants fix this too then sounds good!

**Comment by fiveisprime** [comment]
Reference is updated here: https://github.com/microsoft/vscode-docs/pull/4397
