### ISSUE TITLE
Editor-junction drag resizing from wrong pane junction 

### ISSUE THREAD

**Issue by picarro-msimpson** [microsoft/vscode#104514]
Issue Type: <b>Bug</b>

I have the "Explorer" pane open on the left, two editor-windows open in the middle (stacked vertically), and another open editor on the right.
Looks like this:
```
_ _ _ _ _ _ _ _ _ _
|     |     |     |
|     |-----|     |
| _ _ | _ _ | _ _ |
```

When I hover over the window junction of the middle, veritcally stacked editors, and the "Explorer" pane on the left, the cursor turns to the "cross-drag" icon. However when I try and drag the junction, the other junction (two vertical editors, and the editor on the right) moves instead. I can move the left pane by itself with the normal "horizontal-drag", and the two vertical panes by themselves with the "vertical-drag".

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (4.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
gitlens|eam|10.2.2
vscode-pull-request-github|Git|0.18.0
rainbow-csv|mec|1.7.1
snapcode|moy|1.1.0
vscode-docker|ms-|1.4.1
csharp|ms-|1.22.1
mssql|ms-|1.9.0
python|ms-|2020.7.96456
vscode-pylance|ms-|2020.8.0
remote-wsl|ms-|0.44.4
cpptools|ms-|0.29.0
powershell|ms-|2020.6.0
autodocstring|njp|0.5.3
vscode-yaml|red|0.9.1
vscode-sort-json|ric|1.18.0
cython|tcw|0.1.0
sort-lines|Tyr|1.9.0
vscode-icons|vsc|10.2.0

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by picarro-msimpson** [comment]
@joaomoreno I have not seen this since I filed this ticket. I closed and reopened vscode and the bug went away.
