### ISSUE TITLE
Ctrl+Backspace in built-in terminal (Powershell) doesn't work on Windows

### ISSUE THREAD

**Issue by silasalberti** [microsoft/vscode#104513]
- VSCode Version: 1.47.3
- OS Version: Windows 10 Home Build 19041
- Locale: German keyboard layout (didn't try on English keyboard layout)

Steps to Reproduce:

1. Open a built-in terminal (Powershell)
2. Try to delete the last word using Ctrl+Backspace, but instead "^W" appears.

I use Ctrl+Backspace to quickly delete stuff all the time and it works in the native Powershell, in the native CMD prompt and in the new Windows Terminal. Moreover, it works everywhere else in Windows (file explorer, search bar, Chrome, Notepad, ...). Why doesn't it work in the VSCode built-in terminal?

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Ctrl+backspace support was added recently, if it's not working the problem is likely PSReadline is not loaded correctly.

> Why doesn't it work in the VSCode built-in terminal?

The reason is because it's a very different mechanism, instead of directly changing text, we serialize ctrl+backspace into `^W` and send it to PowerShell to modify its prompt.
