### ISSUE TITLE
Format on Save and Go To Decl/Def in Remote-SSH

### ISSUE THREAD

**Issue by cycheng** [microsoft/vscode#104547]
Hi,
I am using VSCode 1.47.3, I found that the Format on Save, and Go to Declaration/Go To Definition do not work in Remote-SSH.

Could VSCode also support these functions for Remote-SSH? Because that would be super convenient!

Thanks,
CY

**Comment by roblourens** [comment]
They do work, you need to make sure you have the relevant extensions installed on your remote.

If that doesn't address it for you, please give some more details
