### ISSUE TITLE
Source control tab flashes loading icon  every five seconds

### ISSUE THREAD

**Issue by bol-com-pschmitz** [microsoft/vscode#104558]
Issue Type: <b>Bug</b>

The Source Control tab flashes a loading icon every five seconds. It's very distracting. Can this be disabled?

It only appears to happen when the window has the focus.

No other programs are running.

There are no messages appearing in the development console. Let me know if I can enable debug logging somehow that would indicate why it is refreshing the Source Control tab.

This is on a workspace using Git and Java. I can't give steps to reproduce, as simply opening another Git based project doesn't trigger it. There must be an additional factor.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (6.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vsliveshare|ms-|1.0.2619
java|red|0.65.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.11.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.0
vscode-maven|vsc|0.24.0

</details>

**Comment by bol-com-pschmitz** [comment]
Here is a screen recording demonstrating the problem:

[Screen Recording 2020-08-13 at 14.24.27.mov.zip](https://github.com/microsoft/vscode/files/5069041/Screen.Recording.2020-08-13.at.14.24.27.mov.zip)

**Comment by misolori** [comment]
@bol-com-pschmitz can you look in your settings and see if there is anything set for git? There is a setting, `git.autofetchPeriod`, that controls this and wonder if yours maybe got changed?

**Comment by bol-com-pschmitz** [comment]
FYI: I just updated to this version and thought it had been fixed, but after a short while it started doing it again:
```
Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
```

**Comment by bol-com-pschmitz** [comment]
@misolori `git.autofetchPeriod` is set to 180 seconds. And also, `git.autofetch` is set to off.

**Comment by misolori** [comment]
@bol-com-pschmitz can you try disabling extensions and reloading to see if this goes away? You can do this from the extension viewlet in the context menu:

![image](https://user-images.githubusercontent.com/35271042/90447734-c439e200-e098-11ea-857d-5af90bf66a5b.png)
