### ISSUE TITLE
dialog windows popping up on "wrong" screen

### ISSUE THREAD

**Issue by rhaschke** [microsoft/vscode#104550]
vscode opens dialog windows (confirmation dialogs, etc.), always on my laptop screen although an external monitor, attached to it, is made the _default_ screen as well as the _current_ screen, displaying vscode.

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-112-generic

Steps to Reproduce:

1. Use a dual-display setup. Run vscode on the external screen.
2. Open a dialog, e.g. `File Open`.
3. Observe how the dialog opens on the screen that is not _current_. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Using normal electron APIs, I am not sure how I can influence the location on screen, sounds like an upstream issue to me.

**Comment by deepak1556** [comment]
Does this happen with latest stable ?

**Comment by rhaschke** [comment]
No, seems to be fixed with latest stable. Thanks.

**Comment by deepak1556** [comment]
thanks for confirming!
