### ISSUE TITLE
VS Code keeps opening new debug console instances

### ISSUE THREAD

**Issue by leosdad** [microsoft/vscode#104596]
Issue Type: <b>Bug</b>

For some time now, the _Start Debugging_ and the _Run Without Debugging_ commands give the exact same results for my node projects, i.e. **the debugger is always listening** regardless. This also has the very bad collateral effect of stacking **multiple unfinished debug sessions**. So if I launch a configuration 10 times, I have to click the Clear button in the debug console several times.

This started with some of the VS Code updates some months ago and I never was able to fix it anymore. I tried resetting all my configurations (or at least that's what I think I did) to no avail.

Below is a launch.json example. I tried tweaking `console`, `outputCapture` and `autoAttachChildProcesses`, but nothing changed.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "My project",
      "type": "node",
      "request": "launch",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "cwd": "${workspaceFolder}",
      "program": "${workspaceFolder}/src/cli.ts",
      "console": "internalConsole",
      "outputCapture": "std",
      "args": [
        "${workspaceFolder}/project.json"
      ],
      "autoAttachChildProcesses": false,
      "outFiles": [ "${workspaceFolder}/js/*.js" ]
    }
  ]
}
```

Thanks in advance.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
vscode-css-formatter|aes|1.0.1
path-intellisense|chr|2.2.1
jsrefactor|cms|2.20.6
file-tree-to-text-generator|d-k|1.2.1
vscode-eslint|dba|2.1.8
LogFileHighlighter|emi|2.9.0
nunjucks-template|ese|0.3.1
git-commits|Exe|3.7.4
vscode-highlight|fab|1.4.1
todo-tree|Gru|0.0.178
git-last-commit-message|Jan|1.9.0
vue|jcb|0.1.5
hjson|lak|0.3.2
vetur|oct|0.26.1
vscode-sort-json|ric|1.18.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
nunjucks|ron|0.3.0
vscode-scss-formatter|sib|2.0.1
code-spell-checker|str|1.9.0
code-spell-checker-portuguese-brazilian|str|0.1.2
language-stylus|sys|1.11.0
es6-string-html|Tob|1.8.8
txt-syntax|xsh|0.0.4
markdown-all-in-one|yzh|3.2.0

</details>

**Comment by connor4312** [comment]
This is intentional -- see here https://github.com/microsoft/vscode-js-debug/issues/523#issuecomment-651878531. Something that will happen this month is (at least for Node 12+) adding a flag that hides the "debugger listening on" screen cheese https://github.com/microsoft/vscode-js-debug/issues/558.

Open to feedback/suggestions for this.

**Comment by leosdad** [comment]
So it was disabled intentionally? If _Start Debugging_ and _Run Without Debugging_ are the same, it's not clear why the two commands were kept. Still, I believe the _Run Without Debugging_ option is useful. The debugger should not be launched at all times (probably with a performance gain) and no new console instances would be created with every Ctrl+F5 (no point in using more memory, the task should be closed). It would be great to have the option as before: with or without debugging, just users choose what they want.

**Comment by connor4312** [comment]
One kind of interesting thing is that, with the design of V8, there are 'degrees' of debugging. Normally when debugging we enable a bunch of debug domains, notably the "Debugger" domain which allows us to apply breakpoints, request the V8 collect async stack traces, and so on. This latter feature is where the bulk of overhead in debugging comes from.

In "run without debugging" we enable some domains, such a the "Runtime" domain to track console messages. However, we don't enable the Debugger domain, so breakpoints don't apply, debugger; statements aren't hit, and we don't have much performance overhead. We're more of a passive observer.

As I understand from your issue, the major UX concern you have is around the use of the debug console. As far as I know / can see we use the debug console the same way that the old debugger did. It might help if you could take a screen recording of what you're seeing (https://gifcap.dev/ is useful)

**Comment by leosdad** [comment]
I understand that the debugger has a minimal overhead, but it certainly doesn't look like it. Here's a typical screen for Run without debugging:

![image](https://user-images.githubusercontent.com/7026091/90435680-b2127080-e0a5-11ea-8ad7-71a751499c11.png)

I believe it's a lot for an inactive debugger! Now, here's the same, for 'Start debugging':

![image](https://user-images.githubusercontent.com/7026091/90435804-f00f9480-e0a5-11ea-8403-02b724fca9b3.png)

The is no difference, so one immediate consequence is that I cannot tell if the debugger is actually active or not.

**Comment by connor4312** [comment]
Yea, that's a bit ugly right now.

I linked above that we intend to put in the fix to tell Node not to print that extra cruft. Is there more changes you'd like to see beyond that?

**Comment by leosdad** [comment]
Besides removing the cruft, there is also the issue of opening multiple instances of the debug console. It's easy to stack dozens or even hundreds of consoles, but that's not necessary. Reusing the same console would be much better, I believe. Perhaps an option would be ideal.

Also, the "Waiting for the debugger to disconnect..." message always appears at the end, complete with ellipsis, which may lead people to think it is waiting for something. If that's inevitable, at least a "Disconnected" message might be appended to that, like this:

```
Waiting for the debugger to disconnect... Disconnected.
```

**Comment by connor4312** [comment]
> Besides removing the cruft

This is done in the latest nightly!

> Also, the "Waiting for the debugger to disconnect..." message always appears at the end, 

This is added by Node and is not under our control unfortunately.

> It's easy to stack dozens or even hundreds of consoles, but that's not necessary. Reusing the same console would be much better, I believe

You mean that after you clear the debug console, you see the output from the last run?

![recording(1)](https://user-images.githubusercontent.com/2230985/91480630-1d9fcf00-e858-11ea-978b-e8681bff7075.gif)

(I'm clicking on the 'clear' button near the end, the cursor position is bugged on high dpi displays)

I'm not sure I can control this from the debugger side of things -- @isidorn is this configurable in any way?

**Comment by leosdad** [comment]
> > Besides removing the cruft
> This is done in the latest nightly!

Thanks! I believe this is the most important thing.

> > Also, the "Waiting for the debugger to disconnect..." message always appears at the end,
> This is added by Node and is not under our control unfortunately.

Okay, thanks.

> You mean that after you clear the debug console, you see the output from the last run?

I mean like this:

![2020-08-27_15-34-36](https://user-images.githubusercontent.com/7026091/91481551-02928680-e87b-11ea-8dcb-15d3c7a258f7.gif)

There are several stacked consoles here (about 10 in this example), I believe only one would suffice.

**Comment by isidorn** [comment]
@connor4312 If I understood your question correctly you want to clear the debug console.
You could execute the following command `workbench.debug.panel.action.clearReplAction` from your extension. Might not be the nicest but should get the job done.
Code pointer of the command https://github.com/microsoft/vscode-distro/blob/3bee0990639605949d893d57687ce2c2aa5e41ac/src/vs/workbench/contrib/debug/browser/repl.ts#L810

**Comment by connor4312** [comment]
Maybe an extension that runs that when a new debug session is started could fill the reporter's use case. I could add an option for this in js-debug, but the console duplication behavior hasn't been raised by any other users and I'm not sure I want to add another fiddly option for it.

**Comment by isidorn** [comment]
@connor4312 I would not add it yet. Just my 2 cents.

**Comment by connor4312** [comment]
Yea. I will mark that as an extension opportunity, pending more feedback from others.

**Comment by leosdad** [comment]
Was this behavior always like this? I don't recall seeing multiple debug console instances before. I believe this started some months ago along with some changes in debugger. I may be wrong, though.

**Comment by connor4312** [comment]
I think this will have existed before.

Also -- you can set `"console": "integratedTerminal",` to run inside an integrated terminal, which _will_ be reused.

**Comment by leosdad** [comment]
Okay, thanks.
