### ISSUE TITLE
Slow Extension Running

### ISSUE THREAD

**Issue by Aryankpoor** [microsoft/vscode#104560]
- VSCode Version: 1.47
- OS Version: Windows 7

Steps to Reproduce:

1. There is some problem with the loading of live sever preview.
2. Whenever I want to run the extension live server preview, it atleast takes 5 minutes before opening the preview in a split tab. Please decrease the time taking, I do other things while it is still opening preview

Does this issue occur when all extensions are disabled?: Yes

**Comment by gregvanl** [comment]
Some other users are saying that the Live Server extension isn't working after the 1.48 release.

From the Live Server Ratings & Reviews https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer&ssr=false#review-details:
"Recently it started not working, it doesn't refresh anymore. It started on the computer, today it doesn't work on the laptop either. I reinstalled the plugin, then vscode, nothing helped."

1.48 release notes comment:
"Its a good update but when i updated my vscode it started taking more ram than regularly and its bit laggy and my live server is not working. Whenever i am trying to open my live server it is opening but it is not redirecting me to my webpage."

**Comment by Aryankpoor** [comment]
I am still on v1.47. I will try updating and see if it works.

**Comment by Aryankpoor** [comment]
The live server extension is a bit faster after the new update thanks for the help!
