### ISSUE TITLE
Integrated terminal not working

### ISSUE THREAD

**Issue by BarunBapari** [microsoft/vscode#104576]
Issue Type: <b>Bug</b>

After troubleshooting on vscode my integrated terminal nort working...

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.64GB free)|
|Process Argv|--log trace|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|1.0.24
vscode-django|bat|0.20.0
python-extension-pack|don|1.6.0
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
MagicPython|mag|1.1.0
python|ms-|2020.8.101144
material-icon-theme|PKi|4.2.0
python|tht|0.2.3
vscode-terminal-here|Tyr|0.2.4
vscodeintellicode|Vis|1.2.10
jinja|who|0.0.8

(2 theme extensions excluded)

</details>

**Comment by usernamehw** [comment]
Since launching vscode with compatibility mode disabled mode fixed it, I'm going to close this issue as a duplicate.
