### ISSUE TITLE
Git rebase stuck after resolving conflicts

### ISSUE THREAD

**Issue by guoyunhe** [microsoft/vscode#104502]
- VSCode Version: 1.47.3
- OS Version: openSUSE Tumbleweed

Steps to Reproduce:

1. Checkout a branch that has conflicts with master/main branch
2. Run `git rebase master`
3. Resolve conflicts in VS Code
4. Click the :heavy_check_mark: icon in VS Code Git side panel

Result: the progress bar keeps rolling but never successfully rebase. I have to go to console and manually run `git rebase --continue`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
> 4\. Click the ✔️ icon in VS Code Git side panel

What does  `Git: Show Git Output` show when you run the ✔ icon?

**Comment by guoyunhe** [comment]
```
> git rebase --continue
> git ls-tree -l :2 -- /home/guo/git/kde/kdeplasma-addons/kdeds/potd/kded_potd.desktop
fatal: Not a valid object name :2
> git show --textconv :2:kdeds/potd/kded_potd.desktop
> git ls-tree -l :2 -- /home/guo/git/kde/kdeplasma-addons/kdeds/potd/kded_potd.desktop
fatal: Not a valid object name :2
> git show --textconv :2:kdeds/potd/kded_potd.desktop
> git ls-tree -l :2 -- /home/guo/git/kde/kdeplasma-addons/kdeds/potd/kded_potd.desktop
fatal: Not a valid object name :2
> git show --textconv :2:kdeds/potd/kded_potd.desktop
```

**Comment by joaomoreno** [comment]
Is your branch called `2`?

**Comment by guoyunhe** [comment]
@joaomoreno of course no. it is calld `fix-tmp-path`

**Comment by guoyunhe** [comment]
Here is another case when it stuck:
```
> git rebase --continue
> git ls-files --stage -- /home/guo/git/advclb/peili-app/src/components/ServiceTab/index.tsx
> git cat-file -s f0cedf3aa31f4b03898d58d45e3b63bb1b06db3d
> git show --textconv :src/components/ServiceTab/index.tsx
> git ls-files --stage -- /home/guo/git/advclb/peili-app/src/components/ServiceTab/index.tsx
> git cat-file -s f0cedf3aa31f4b03898d58d45e3b63bb1b06db3d
> git show --textconv :src/components/ServiceTab/index.tsx
> git ls-files --stage -- /home/guo/git/advclb/peili-app/src/components/ServiceTab/index.tsx
> git cat-file -s f0cedf3aa31f4b03898d58d45e3b63bb1b06db3d
> git show --textconv :src/components/ServiceTab/index.tsx
> git ls-files --stage -- /home/guo/git/advclb/peili-app/src/components/ServiceTab/index.tsx
> git cat-file -s f0cedf3aa31f4b03898d58d45e3b63bb1b06db3d
> git show --textconv :src/components/ServiceTab/index.tsx
> git ls-files --stage -- /home/guo/git/advclb/peili-app/src/components/ServiceTab/index.tsx
> git cat-file -s f0cedf3aa31f4b03898d58d45e3b63bb1b06db3d
> git show --textconv :src/components/ServiceTab/index.tsx
> git ls-files --stage -- /home/guo/git/advclb/peili-app/src/components/ServiceTab/index.tsx
> git cat-file -s f0cedf3aa31f4b03898d58d45e3b63bb1b06db3d
> git show --textconv :src/components/ServiceTab/index.tsx
```

**Comment by joaomoreno** [comment]
Can you reproduce this on other repositories? What git version do you have installed? What git config do you have setup?

**Comment by guoyunhe** [comment]
I can reproduce this on any repository, every time. git version 2.28.0. My global git configuration is:

```
[user]
        name = Guo Yunhe
        email = i@guoyunhe.me
[cola]
        spellcheck = true
        hidpi = 1
        theme = default
        fontdiff = Source Code Pro,10,-1,5,50,0,0,0,0,0,SemiCondensed
        statusshowtotals = false
        boldheaders = false
        statusindent = false
[url "ssh://git@invent.kde.org/"]
        insteadOf = kde:
[url "ssh://git@invent.kde.org/"]
        pushInsteadOf = kde:
```

**Comment by joaomoreno** [comment]
So strange. Do you mind providing a [screen recording](https://gifcap.dev/) of the issue, while having the `Git: Show Git Output` view open?

**Comment by guoyunhe** [comment]
Here is my screen recording https://www.youtube.com/watch?v=OqkJXY8j8iY

**Comment by joaomoreno** [comment]
What git version? Can you try updating it to the latest git version?

**Comment by guoyunhe** [comment]
I am using the latest version 2.28.0

**Comment by joaomoreno** [comment]
Hm... what would happen if you run `git rebase --continue` from the terminal instead of clicking the ✔️ ?

Also, can you open `Developer: Toggle Developer Tools` and see if there are any errors in there?

**Comment by guoyunhe** [comment]
`git rebase --continue` results the same, as long as I solve the conflicts in VS Code. If I solve conflicts in VI or other editors, here is no errors. I will try developer tools later.

**Comment by joaomoreno** [comment]
> `git rebase --continue` results the same, as long as I solve the conflicts in VS Code. If I solve conflicts in VI or other editors, here is no errors. I will try developer tools later.

Could you show me a recording of the whole process?
