### ISSUE TITLE
Notebook editor widget is reinstantiated when dragging between notebook between groups

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#104535]
- Open a github issues notebook and execute a cell
- Drag it from group 1 to group 2
- You can tell that the notebook webview is recreated by the way the output blinks and loses any transient state like selections, it should be reused in the new group

**Comment by roblourens** [comment]
@bpasero please review, also @rebornix this changed slightly since you saw it

**Comment by bpasero** [comment]
Change LGTM, thanks for ping.
