### ISSUE TITLE
Writing to a file in a zip archive reports success when it fails

### ISSUE THREAD

**Issue by JulianOrteil** [microsoft/vscode#104590]
- VSCode Version: 1.47.3 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Create a file whose default program is VSCode (for example, vscode is the default program for JSON files for my setup)
2. Put it into a zipped archive (for example, using Windows' built-in archiver in File Explorer, right click on the file > Send to > Compressed (zipped) folder)
3. Double click the archive to open it and then double click the file in the archive.
4. In VSCode, enter some text into the file and save it.

You should see this in the bottom-right:
![image](https://user-images.githubusercontent.com/23083317/90184397-ab6cbc00-dd7a-11ea-889f-da441b3d3c70.png)

5. Choose 'Overwrite', accept the UAC prompt (if there is one). The circle in the file tab noting an unsaved file will be gone (indicating the file saved successfully).
![image](https://user-images.githubusercontent.com/23083317/90184550-e7078600-dd7a-11ea-9d4e-b325cc21240c.png)
![image](https://user-images.githubusercontent.com/23083317/90184655-0acacc00-dd7b-11ea-85f1-cdefb5c79bbb.png)

6. Close and reopen the file; notice no change to the file

What I wanted to write to my JSON file (a lot of empty space) vs what is there:
![image](https://user-images.githubusercontent.com/23083317/90184780-45346900-dd7b-11ea-8536-3c41c2f92047.png)
![image](https://user-images.githubusercontent.com/23083317/90184895-7876f800-dd7b-11ea-94b2-0242eb17cd50.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

There should be another prompt indicating the file failed to save to avoid confusion. I'm unsure as to whether or not this extends to other 'read-only' files.

**Comment by isidorn** [comment]
I am not sure that we support this scenario. Anyways sounds like file-io, moving to @bpasero

**Comment by bpasero** [comment]
@JulianOrteil I doubt this works as you think it does. When you open a file from a zip archive I would think that the OS temporarily unzips the file and puts it into some temp location with write protection. VSCode can overwrite it but the contents would never go back to the zip archive.

**Comment by JulianOrteil** [comment]
@bpasero 

I see the problem now. I completely forgot that Windows does that. My bad.
Thank you for clearing that up.
