### ISSUE TITLE
Git integration with multiple git directories inside of workspace

### ISSUE THREAD

**Issue by bkinsey808** [Microsoft/vscode#10450]
Is there a way to handle multiple git repos within a single vscode workspace? I have my workspace directory with many git repos. I'd love to take advantage of vscode's git integration, but it seems like it requires my root level workspace directory to be the git repo.

- VSCode Version: 1.4.0
- OS Version: mint

**Comment by joaomoreno** [comment]
This is not a supported scenario. You can only either open the root of a git repository or one of its subdirectories.

**Comment by bkinsey808** [comment]
Thanks. I hope this issue is reconsidered someday. I like having multiple git repos handy, and being able to search across them simultaneously. And also git integration would be handy.

**Comment by jcrben** [comment]
Seems like this could ultimately be handled by https://github.com/Microsoft/vscode/issues/396?
