### ISSUE TITLE
Quick fixes not listed when multiple problems occur at the same place

### ISSUE THREAD

**Issue by addshore** [microsoft/vscode#104574]
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard

Reported at https://github.com/DEVSENSE/phptools-docs/issues/79 to begin with

Steps to Reproduce:

1. Have some code with 2 problems listed at the same place
2. Load the hover over problem dialog
3. Look at the "quick fix" suggestions

![2020-08-13_15-56-24](https://user-images.githubusercontent.com/3308769/90150450-96455c80-dd7d-11ea-81c5-427223dc5a97.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Please share steps to reproduce, including example code

**Comment by addshore** [comment]
Minimum reproduction with the phptools extension for vscode in an empty project:

file1.php
```
<?php

namespace One;

class ClassOne {}

class ClassThree extends ClassOne{}
```

file2.php
```
<?php

namespace Two;

class ClassTwo {

	function __construct() {
		$this->someFunction( new ClassThree );
	}

	function someFunction( ClassOne $one ) {
		// ...
	}

}
```

The problems reported on the issue line are:

```
{
	"resource": "/home/adam/dev/git/gerrit/mediawiki/core/test2.php",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "PHP0406",
	"severity": 4,
	"message": "Argument '1' passed to someFunction() is expected to be of type Two\\ClassOne, Two\\ClassThree given",
	"source": "PHP",
	"startLineNumber": 8,
	"startColumn": 24,
	"endLineNumber": 8,
	"endColumn": 38
}
```
and
```
{
	"resource": "/home/adam/dev/git/gerrit/mediawiki/core/test2.php",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "PHP0413",
	"severity": 4,
	"message": "Use of unknown class: 'Two\\ClassThree'",
	"source": "PHP",
	"startLineNumber": 8,
	"startColumn": 28,
	"endLineNumber": 8,
	"endColumn": 38
}
```
Problems correctly displayed in the UI but with no quick fixes available:

![image](https://user-images.githubusercontent.com/3308769/90396870-e3cc0d00-e08e-11ea-8031-90321965f2b1.png)


Quickfix is actually available:

![image](https://user-images.githubusercontent.com/3308769/90396923-f8a8a080-e08e-11ea-8c61-d2295b644fac.png)

I imagine this is probably reproducible with other reported problems if they can be made to appear on the same line.
If anyone has suggestions I can give it a go!

**Comment by mjbvz** [comment]
Does the extension mark its code actions with [`CodeActionKind.QuickFix`](https://github.com/microsoft/vscode/blob/6445a9633d428e0879d172d4f392c542ba887768/src/vs/vscode.d.ts#L2009)?

**Comment by jakubmisek** [comment]
@mjbvz yes, it is marked with "QuickFix". The quick fix works as expected if there is just one problem at that location. Once there are two overlapping problems, quickfix is not suggested by VSCode

**Comment by sandy081** [comment]
I am not able to use above extension as it needs license. 

VS Code asks for code actions with the given range of the problem, can you please check the range and the quick fixes you are returning?

**Comment by jakubmisek** [comment]
@sandy081 @mjbvz thank you for the response - as expected it was a problem in our LS. Overlapping spans resulted in the code action being filtered out.

Thank you for your time! The issue can be closed.
