### ISSUE TITLE
KeybindingsRegistry does not allow lazy registration

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#104577]
In our source code all the instances of `KeybindingsRegistry.registerCommandAndKeybindingRule` are done on startup. If any of them are changed to be done with a 1000ms timeout the command will get registered, however the `keybinding` will be ignored.

Repro steps: take any keybdingins registration and add a `setTimeout` of a 1000ms around it. For example [Breadcrumbs focus and select](https://github.com/microsoft/vscode/blob/bea0de31e4ac83d7146c64115af3e57e2a5546d8/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L583). Notice how the command gets registered but the keybinding is not there.

Looking at the registration, the keybindings properly ends up in the `_coreKeybindings` array [here](https://github.com/microsoft/vscode/blob/bea0de31e4ac83d7146c64115af3e57e2a5546d8/src/vs/platform/keybinding/common/keybindingsRegistry.ts#L216)

Looking at the abstractKeybindingDispatch the map in `keybindingResolver` does not have anything for the keybinding [here](https://github.com/microsoft/vscode/blob/34dee12ff383689d9d5e62f6b263ed644e4df44d/src/vs/platform/keybinding/common/keybindingResolver.ts#L277)

**Comment by alexdima** [comment]
@isidorn I think we can close this, since you now use context keys?

For posterity: the reason the keybinding registry doesn't allow for lazy registered keybindings is because it would be costly to always resolve again all the keybindings after each registration. I mean we could do it, but if there's no need for it, I'd rather not.

**Comment by isidorn** [comment]
Correct Alex. Sorry I forgot to close this as designed and there is no need for it since we did an alternative approach
