### ISSUE TITLE
"コードの書式設定" is translation error.

### ISSUE THREAD

**Issue by nemu626** [Microsoft/vscode#10457]
- VSCode Version:1.4.0
- OS Version: windows10 

"Format Code" => "コードの書式設定"
This Japanese translation is strange.This sentence means "configure coding format"

I found a same issue but request was rejected and issue has closed.
(https://github.com/Microsoft/vscode/pull/5296)

Correct translation is here : 
"Format Code" => "コードのフォーマット"

**Comment by johnliu2016** [comment]
@lukaschal Please recheck current translations of "Format Code"

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
@nemu626 Please, is it possible to add ENU and JPN screenshots for better context ?

**Comment by nemu626** [comment]
@lukaschal 
<img width="468" alt="ja" src="https://cloud.githubusercontent.com/assets/2967565/17697713/5f95f2e4-63f1-11e6-94ad-eacd90e02f4f.png">
<img width="449" alt="enu" src="https://cloud.githubusercontent.com/assets/2967565/17697716/61ee2fe8-63f1-11e6-9157-d93823eb136a.png">

**Comment by lukaschal** [comment]
Fixed as suggested.

SRC: Format Code
NEW TGT: コードのフォーマット
