### ISSUE TITLE
code: 3221225477.

### ISSUE THREAD

**Issue by ragnar007007** [microsoft/vscode#104503]
Issue Type: <b>Bug</b>

when i open terminal it open's for 1 second and then it closes 
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 3221225477
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
binary-preview|asu|0.0.2
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.1.3
php-debug|fel|1.13.0
search-node-modules|jas|1.3.0
node-module-intellisense|lei|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
mssql|ms-|1.9.0
js-debug-nightly|ms-|2020.8.1117
debugger-for-chrome|msj|4.12.9
LiveServer|rit|5.6.1

</details>

**Comment by Tyriar** [comment]
See https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch to try diagnose the issue
