### ISSUE TITLE
"Open with" markdown is experimental?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#104541]
I am not sure why we call our markdown preview experimental?

![image](https://user-images.githubusercontent.com/900690/90107103-a2fb8d80-dd48-11ea-8edc-cb3507142342.png)

**Comment by mjbvz** [comment]
Yes, this is the custom editor based preview which is not production ready

**Comment by bpasero** [comment]
This is a bit confusing though because visually it looks like the normal "Open Preview" editor. Would be good to transition to one in the end.

**Comment by mjbvz** [comment]
I think that custom editors should ultimately be the better solution for the markdown preview but we need a few more API features to get there, such as easy support for showing a split custom editor. 

We also have 5 years of people who are now used to how our current, less than ideal markdown preview works so we'll probably have to keep the current preview around in some form
