### ISSUE TITLE
Support `preserveFocus` flag when opening editors or an output channel

### ISSUE THREAD

**Issue by Draivin** [Microsoft/vscode#1045]
When showing an `OutputChannel`, it will steal the current focus. In an atempt to be less disruptive and keep the user's current focus, I tried the following code:

```typescript
let textDocument = vscode.window.activeTextEditor.document;
let channel = vscode.window.createOutputChannel('test');
channel.show(2);
vscode.window.showTextDocument(textDocument);
```

This returns the focus to the previously focused document, but it has one quirk, when any quick panel is opened and then closed, the focus will go to the `OutputChannel` instead of going to the previously focused document.

**Comment by jrieken** [comment]
We should add an option to control is `open` does focus or not. Internally we already have that notion.
