### ISSUE TITLE
Unable to drag and drop from Explorer to browser window

### ISSUE THREAD

**Issue by kaovilai** [microsoft/vscode#104534]
Version: 1.47.3 (system setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open https://www.dragdrop.com/test/ (applies to other drag and drop capable sites such as Moodle.org deployments)
2. Open VSCode
3. Open a folder in VSCode Explorer
4. Drag file from Explorer to drop area on the website in your favorite browser

Does this issue occur when all extensions are disabled?: Yes
Expected: File upload box appears
Actual: Nothing happens upon releasing file

When using Windows Explorer, actual matches expected but not via VSCode Explorer. Reproducible on latest Chrome and Firefox.

**Comment by isidorn** [comment]
Seems like a dup of https://github.com/microsoft/vscode/issues/91132
