### ISSUE TITLE
How to transition to "Settings Sync Insiders service"?

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#104584]
I tried the **Settings Sync: Select Service...** command but it created a new profile for me, i.e., it didn't transfer the history of my settings.

What I want to achieve:

1. In **Insiders**, _move_ my synced settings to that "Insiders service".
2. Somehow clear the original "Stable" storage.
3. Turn on Settings Sync in **Stable**.

Do I understand correctly that for both services (Insiders and Stable), I can use the same GitHub account, right?

**Comment by Tyriar** [comment]
History will not be transferred. Essentially the previous service Insiders used became the stable service, and insiders is brand new. This saves us from doing any migration work, if you need history you can either keep using the stable service or use the stable client.

**Comment by borekb** [comment]
@Tyriar Thanks for the comments. I miss the simplicity of Gists + [this extension](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) though – I simply had two gists, one for Insiders, one for Stable, it was such a simple mental model, I could point any VSCode instance to any of the two (or more) gists. Simple, elegant.

Now, I'm basically in a "data loss" situation if I want to transition to two separate Sync services. It's not such a big deal, plus I know it's in Insiders and therefore experimental, but if you can come up with a way to store _my_ data to _my_ storage (Gist, GitHub repo, Dropbox, whatever), that would be great. (That is tracked in https://github.com/microsoft/vscode/issues/92357.)
