### ISSUE TITLE
Can't hover top cell toolbar

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#104583]
When I try to click a toolbar button on the first cell in the list, I trigger the new top insertion menu instead

**Comment by rebornix** [comment]
Nice catch, the hover container of the insert toolbar overlaps with the cell toolbar. Same thing happens with the insert toolbar below the cell and the language picker.

![toolbar-overlap](https://user-images.githubusercontent.com/876920/90191913-a9a0f980-dd76-11ea-9fad-01916b71bdb5.gif)

cc @misolori I'm wondering how we would solve this problem completely as the toolbar overlaps with the cell and we make its width 100% to ensure that it's accessible on hover.

**Comment by rebornix** [comment]
I increased the top padding of the document a bit to `24px`, if you still hover on the top of the cell toolbar, it still triggers the insertion toolbar. I didn't make it larger as if I make it `32px`, it looks weird, too much whitespace at the top of the document.

**Comment by rebornix** [comment]
nvm, I made it the same as other insertion toolbars, whose zindex is lower than the cell toolbar.
