### ISSUE TITLE
Markdown styling missing in quite a few bundled themes

### ISSUE THREAD

**Issue by orionlee** [microsoft/vscode#104530]
This is essentially a more general issue of the closed #104467

Markdown styling support are missing in the following, missing bold and italic:
- Solarized Light
- Red 
- Abyss
- Solarized Dark
- Tomrrow Night Blue

See screenshot below for an example.

For High Contrast, section heading (`# heading`) are not in bold. I am unclear if it's a bug or intentional.

---

Screenshot for Solarized Dark

![image](https://user-images.githubusercontent.com/250644/90079709-82d2bc80-dcbd-11ea-9aa6-fbba355ac43a.png)

**Comment by ZainChen** [comment]
Hi, I tried bold and italic with these themes:

- theme-tomorrow-night-blue
- theme-solarized-dark
- theme-solarized-light
- theme-red
- theme-kimbie-dark
- theme-abyss
- hc_black_defaults(High Contrast)
