### ISSUE TITLE
Source control does not auto-refresh for projects under a mount point

### ISSUE THREAD

**Issue by craigktreasure** [microsoft/vscode#104592]
Issue Type: <b>Bug</b>

On Windows 10, I have a drive assigned as a "mount point" assigned to my `C:\users\<username>\repos` directory (see [here](https://www.windowscentral.com/how-mount-hard-drive-folder-windows-10)). So, I have a `G:\` drive that also maps to the `C:\users\<username>\repos` folder. Any projects that I open under `C:\users\<username>\repos` fail to auto-refresh the "Source Control" tab for Git as I make changes. If I open them directly from mount point source drive (`G:\`), then things work as expected.

P.S. I don't believe this is a regression.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1660 v3 @ 3.00GHz (16 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (18.34GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.36.2
docs-article-templates|doc|0.2.9
docs-authoring-pack|doc|0.1.8
docs-images|doc|0.0.9
docs-linting|doc|0.0.5
docs-markdown|doc|0.2.78
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.54
docs-yaml|doc|0.2.5
xml|Dot|2.5.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
dotnet-test-explorer|for|0.7.4
vscode-test-explorer|hbe|2.19.1
beautify|Hoo|1.5.0
docomment|k--|0.1.18
render-crlf|med|1.5.9
vscode-docker|ms-|1.4.1
csharp|ms-|1.22.1
remote-containers|ms-|0.134.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.29.0
hexeditor|ms-|1.2.1
powershell|ms-|2020.6.0
material-icon-theme|PKi|4.2.0
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
copy-relative-path-posix|rss|0.0.4
trailing-spaces|sha|0.3.1
code-spell-checker|str|1.9.0
msbuild-project-tools|tin|0.3.8

</details>

**Comment by joaomoreno** [comment]
#5970
