### ISSUE TITLE
Markdown in notebook output with local images references is not rendered

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#104529]
- VSCode Version: 1.48.insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Create image called 'Blue.png' in a test folder
1. Start jupyter from this test folder
1. Run this cell : 
```
from IPython.display import display, Markdown
display(Markdown("![alt text](./Blue.png)"))
```
4. Verify image shows in jupyter
![image](https://user-images.githubusercontent.com/19672699/90078905-2d95ab80-dcbb-11ea-9180-87fd3307f46e.png)

5. Save notebook
5. Open notebook in VS code

Image does not appear

![image](https://user-images.githubusercontent.com/19672699/90078875-1bb40880-dcbb-11ea-9a9d-3fa993495934.png)

Does this issue occur when all extensions are disabled?: N/A

**Comment by rchiodo** [comment]
Okay now I'm not sure which renderer is being used. Is it the python extension or the default one?

**Comment by rchiodo** [comment]
So the bug may be we can't set the working directory in our renderer.

**Comment by roblourens** [comment]
What do you think about this @rebornix is it ok to add the notebook URI to `IOutputTransformContribution`?

**Comment by rebornix** [comment]
@roblourens I think it's ok to pass in notebook URI and use that as the default path for the markdown renderer.
