### ISSUE TITLE
Missing File system provider blocks quiting VS Code

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#104593]
Issue Type: <b>Bug</b>

When the error triggers, I can't reload the window or quit VS Code.
```
An unexpected error prevented the application from closing (Unable to resolve filesystem provider with relative file path 'vscode-notebook:Untitled-2.ipynb').
```

VS Code version: Code - Insiders 1.48.0-insider (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-11T23:14:32.083Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.33GB free)|
|Process Argv|-psn_0_30198987 --enable-proposed-api ms-vscode.vscode-notebook-history|
|Screen Reader|no|
|VM|11%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.2
tsl-problem-matcher|eam|0.3.0
vscode-pull-request-github-insiders|Git|2020.8.18186
vscode-fluent-icons|mig|0.0.1
vscode-docker|ms-|1.4.1
vscode-language-pack-zh-hans|MS-|1.48.3
python|ms-|2020.8.101144
remote-containers|ms-|0.134.0
remote-ssh-edit-nightly|ms-|2020.8.13860
remote-ssh-nightly|ms-|2020.8.13860
hexeditor|ms-|1.2.1
js-debug-nightly|ms-|2020.8.1217
powershell|ms-|2020.6.0
vscode-github-issue-notebooks|ms-|0.0.39
vscode-markdown-notebook|ms-|0.0.10
vscode-notebook-history|ms-|0.0.1
debugger-for-chrome|msj|4.12.9
toggle|reb|0.0.1
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
rust|rus|0.7.8
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.5.3

(5 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@rebornix steps?

**Comment by bpasero** [comment]
I think the error message is misleading, the procedure is not prevented. I just verified this by adding a promise to the shutdown that errors after 1s and I could both quit and reload window.

**Comment by rebornix** [comment]
I don't have a stable reproduce steps there. will reopen next time I see it again.
