### ISSUE TITLE
[decorators] spaced are collapsed in contentText (before/after decoration attachments)

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#10456]
- VSCode Version: 1.4.0, 1.5.0-insider
- OS Version: Win8.1

The spaces in `contentText` are not preserved when rendered, but are instead collapsed to one space. A fix is to substitute each space for a non-breaking space (\u00a0).

This should be documented if it is the intended behavior, although my preference is for all spaces to be preserved (the current behavior is unintuitive because it is not a `MarkedString` nor HTML).

Steps to Reproduce:

``` typescript
const dec = vscode.window.createTextEditorDecorationType({
    before: { contentText: "B     B", },
    after: { contentText: "A     A", },
  });
function lineRange(line, start, end) { return new vscode.Range(line,start,line,end) }
const editor = vscode.window.activeTextEditor;
if (editor) {
  const lines = [
    "--- some-text ---",
    "END OF EXAMPLE", "", "", ]
  editor.edit((edit) => {
    edit.insert(new vscode.Position(0,0), lines.join('\n'));
  }).then(() => {
    editor.setDecorations(dec, [lineRange(0,4,13)]);
  });
}
```
#### Expected result:

`some-text` should be rendered as <code>B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bsome-textA&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A</code>
#### Actual result:

`some-text` is rendered as `B Bsome-textA A`; i.e. the spaces are collapsed

**Comment by aeschli** [comment]
@alexandrudima Alex, do you have an opinion on this one? I can set white-space: pre; but it would not look right if a proportional editor font is used.

**Comment by alexandrudima** [comment]
@aeschli Perhaps we can do the replace on our side? I would not use `white-space: pre` on the line's spans, maybe you can only target the `:before` and `:after`

**Comment by aeschli** [comment]
The `white-space: pre` would only be on the :before/:after

**Comment by alexandrudima** [comment]
I think either ways could work fine. I don't think `white-space: pre` works only with monospace fonts. AFAIK it just control the behaviour of repeated spaces

**Comment by siegebell** [comment]
In 1.4.0, `white-space: pre` seems to work fine for monospaced fonts. I also tested it with Arial and Times New Roman, and it *almost* works: the before decoration is corrected, but the after decoration has an extra half-space between the As.

MWE: (this uses a code injection hack)
```typescript
const dec1 = vscode.window.createTextEditorDecorationType({
    before: { contentText: "B     B", },
    after: { contentText: "A     A", },
  });
const dec2 = vscode.window.createTextEditorDecorationType({
    before: { contentText: "B     B", textDecoration: "none; white-space: pre", },
    after: { contentText: "A     A", textDecoration: "none; white-space: pre", },
  });
const dec3 = vscode.window.createTextEditorDecorationType({
    before: { contentText: "B\u00a0\u00a0\u00a0\u00a0\u00a0B", },
    after: { contentText: "A\u00a0\u00a0\u00a0\u00a0\u00a0A", },
  });
function lineRange(line, start, end) { return new vscode.Range(line,start,line,end) }
const editor = vscode.window.activeTextEditor;
if (editor) {
  const lines = [
    "--- some-text --- test",
    "--- some-text --- test with white-space: pre",
    "--- some-text --- test with nonbreaking spaces (\\u00a0)",
    "--- B     Bsome-textA     A --- EXPECTED",
    "--- B Bsome-textA A --- OBSERVED (no `white-space: pre`)",
    "END OF EXAMPLE", "", "", ]
  editor.edit((edit) => {
    edit.insert(new vscode.Position(0,0), lines.join('\n'));
  }).then(() => {
    editor.setDecorations(dec1, [lineRange(0,4,13)]);
    editor.setDecorations(dec2, [lineRange(1,4,13)]);
    editor.setDecorations(dec3, [lineRange(2,4,13)]);
  });
}
```

Observed:
![capture](https://cloud.githubusercontent.com/assets/16118166/18067381/8673d91c-6e0a-11e6-8977-490907d17631.PNG)

**Comment by aeschli** [comment]
The change broke #11296. I reverted the change for now.

**Comment by aeschli** [comment]
The regular space is a variable-width space. You can not make any assumptions on the width it will be rendered.
In your case you should use a 'fixed-width' space: https://www.cs.tut.fi/~jkorpela/chars/spaces.html
