### ISSUE TITLE
Dropping a cell on a folded markdown cell should drop behind all children

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#104522]
See this for unexpected results:

![kEOC5bZxs7](https://user-images.githubusercontent.com/4674940/90069222-dbe32600-dca6-11ea-9499-1e69fabe78c9.gif)

**Comment by rebornix** [comment]
@roblourens I think it's already fixed via the refactoring of moving cells, but you can confirm you are stilling it also in OSS (I don't)

**Comment by roblourens** [comment]
Yes, thanks @rebornix
