### ISSUE TITLE
vscode.window.activeTextEditor goes undefined for a split second when opening a file (in preview mode)

### ISSUE THREAD

**Issue by DavidGoldman** [microsoft/vscode#104571]
- VSCode Version: 1.48.0-insider
- OS Version: macOS 10.15.5

Steps to Reproduce:

Put following code in an extension:

```
import * as vscode from 'vscode';
vscode.window.onDidChangeActiveTextEditor(editor => {
	console.log(`New active file ${editor?.document?.uri?.toString()}`, editor);
});
```

1. Open a file in preview mode
2. Open another file in preview mode, observe that undefined gets logged before the new file is reported in the active editor

Expected Behavior:

Undefined only reported when the user has closed all editors, not is opening a new one

**Comment by jrieken** [comment]
> Open a file in preview mode

What do you mean by preview mode?

**Comment by DavidGoldman** [comment]
> > Open a file in preview mode
> 
> What do you mean by preview mode?

See the [VS Code docs](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode) on preview mode. 
Just open any file from the side bar while `Workbench › Editor: Enable Preview` is enabled and it should be in italics. The bug occurs when you have an editor in preview mode and it gets replaced by a new editor for a different file in preview mode.

**Comment by jrieken** [comment]
Ok, thanks for clarifying. What you see happens because we first close the document which resets the editor and only then we open a new document which set the editor again. This might be unexpected but nothing is wrong, esp since the active editor can be undefined anyways. No change planned, closing
