### ISSUE TITLE
Freeze when delete a file

### ISSUE THREAD

**Issue by selfrefactor** [microsoft/vscode#104557]
The issue happens also on `Insiders`. I changed to `stable` with hope that this bug is fixed there to no avail.

The `gif` file demonstrates that delete several files cause 30 seconds of frozen VSCode. Similar happens if it is even a single file, that is deleted. Frustrating issue.

- VSCode Version: 1.47.3
- OS Version: Manjaro

Steps to Reproduce:

1. Delete a single or multiple files 
2. Try to interact with VSCode
3. Wait about 10-30 seconds VSCode to be again fully interactive

Does this issue occur when all extensions are disabled?: Yes

![vscode](https://user-images.githubusercontent.com/2149294/90132069-d0aafb80-dd75-11ea-88c5-b4bc45e4ef4c.gif)

**Comment by selfrefactor** [comment]
Fixed if `"disable-hardware-acceleration": true`. Still, as much as I know, this is settings used for slow machines. Now it seems that it should be used even for fast machines.

**Comment by nicolaslima321** [comment]
I'm with the same problem, adding this line at my `argv.json` solved my problem, thanks @selfrefactor !

By the way, i'm using:
- OS: Linux - Fedora 31
- VSCode version: 1.47.3
**Update VSCode doesn't solved

If anyone are dealing with this, for more details, actually this probably will fix: https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by bpasero** [comment]
Sounds like an Electron issue with the OS trash to me, this is Linux @deepak1556
