### ISSUE TITLE
Auto-indentation problem with promise blocks

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/vscode#10453]
- VSCode Version: 1.5.0-insider (666ed83a2d465257201cdac215a553ddee3cccbe)
- OS Version: 10.11.6

Steps to Reproduce:

1. Create a Typescript file and start writing code using promises
2. Auto-indent file using ~~Shift+Alt+D~~ Shift+Alt-F

Expected Result:

```typescript
return output
.then((result: ControllerResponse) => {
  return res
  .status(result.statusCode)
  .json(result.payload);
})
```

Actual Result:

```typescript
return output
  .then((result: ControllerResponse) => {
    return res
    .status(result.statusCode)
    .json(result.payload);
  })
```

Description:

The problem with the current way is that it leads to a strange indentation on the closing braces:
```typescript
    });
}
```

Here, the closing curly braces and parentheses for the `.then()` block are indented 4 spaces instead of 2 spaces as they should be.

**Comment by waderyan** [comment]
Couple questions. 
1. Do you mean Format Code when you say auto-indent? I cannot find the command auto-indent. 2. The keybinding for Format Code is <kbd>cmd+shift+f</kbd>. Did you change your keybinding to <kbd>cmd+shift+d</kbd>?
3. What is your spacing / tab preferences? (lower bottom right corner)

Here I have copied your code sample and ran format code with spaces set at 4. I have repeated the same test with no issues for spaces preference set to 2 and set to tabs. 

![formatcode](https://cloud.githubusercontent.com/assets/2449568/17626572/9dc56244-6062-11e6-9e79-9498c1816831.gif)

**Comment by lumaxis** [comment]
1. Ah, yes of course. I've ever only used the keyboard shortcut as I was always searching for a command containing "auto" or "indent" but never found Format Code.
2. You're of course right, it's actually alt+shift+f.
3. 2 spaces

**Comment by waderyan** [comment]
Ok. Unfortunately, I can repo your issue. Is there anything else you can think of the makes your setup different than me? 

I'm on the same OS and same Insiders build... I have tried with all spaces / tabs configuration but cannot see the behavior you described. 

@dbaeumer - I can't repo. Do you have any ideas?

**Comment by lumaxis** [comment]
@waderyan But I can see the issue repro in your gif. I'll try to give a clearer example:

Correctly formatted code:
```typescript
function doStuff() {
  new Promise(function () {
    return "some string";
  })
  .then((something: string) => {
    something.split(" ");
  });
}
```

After VS Code "Format Code":

```typescript
function doStuff() {
  new Promise(function () {
    return "some string";
  })
    .then((something: string) => {
      something.split(" ");
    });
}
```

Notice how the `.then()` block is indented two more spaces although the scope did not go one level deeper.

**Comment by waderyan** [comment]
Thank you for clarifying. Yes I see the issue and was able to repo. 

I agree with your preference.

**Comment by dbaeumer** [comment]
This is the tsserver formatting the code that way.

@waderyan to see whether something is a tsserver bug you can enable message tracing by setting `"typescript.tsserver.trace": "verbose"`. Doing so and formatting the above code returns the following response from the tsserver:
```
Response received: format (3). Request took 47 ms. Success: true 
Result: [
    {
        "start": {
            "line": 5,
            "offset": 1
        },
        "end": {
            "line": 5,
            "offset": 3
        },
        "newText": "    "
    },
    {
        "start": {
            "line": 6,
            "offset": 1
        },
        "end": {
            "line": 6,
            "offset": 5
        },
        "newText": "      "
    },
    {
        "start": {
            "line": 7,
            "offset": 1
        },
        "end": {
            "line": 7,
            "offset": 3
        },
        "newText": "    "
    }
]
```

Which changes the two spaces to four. Moving to the TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10335
