### ISSUE TITLE
I'm using Notebook in insiders

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [microsoft/vscode#104609]
Issue Type: <b>Feature Request</b>

1. The new version of Jupyter is well made. Im always not happy with "Previous version", if file is bigger, scrolling is getting slow and typing is too laggy. i think it is almost solved and happy to use New version with fresh UX

2. THE Default KEY(Ctrl enter and Shift enter) dosent work as default function of Jupyter, please check it, i need to modify my key again.

3. im using theme, but theme's color covered whole result sheet including matplot graph. it looks hard to see clearly, ofcourse i love New UX and their customization, but only have problem with seeing ourput as a result.

VS Code version: Code - Insiders 1.48.0-insider (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-12T08:04:29.917Z)
OS version: Linux x64 5.4.0-42-generic

**Comment by misolori** [comment]
@JUNGHUNKIM-7 can you post a screenshot of the matplot graph you mentioned?
