### ISSUE TITLE
Support syncing global tasks

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#104685]

**Comment by McNerdius** [comment]
Indeed... I use Custom Tasks *a lot*.  For instance - I love being able to wrap up common CLI use cases in a Global/User level Task - assign a keybinding, use `inputs` to gather the info in a straightforward manner, slap `args` together properly...  Half the typing, less thinking, very powerful.  👍

**Comment by sandy081** [comment]
/duplicate

#91011
