### ISSUE TITLE
Rename refactoring does not respect cursorWordPartRight & cursorWordPartLeft shortcuts

### ISSUE THREAD

**Issue by ssoher** [microsoft/vscode#104679]
Issue Type: <b>Bug</b>

When the rename factoring is initiated, the rename popup cursor movement does not work with cursorWordPartRight/Left even when their shortcuts are set to CTRL + Left / Right. Instead of moving cursor to the next camel case word, it moves to start/end.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Arename
