### ISSUE TITLE
Unresponsive authentication dialog when trying to install extentions

### ISSUE THREAD

**Issue by relativistic** [microsoft/vscode#104670]
- VSCode Version: 1.49.0-insider
- OS Version: macOS 10.14.6 (Mojave)

Steps to Reproduce:

1. Open VS Code
2. Go to extension sidebar (extensions are visible)
3. Choose an extension (e.g. Python), click on green "Install" button
4. A dialog appears popping down from top of vs code window asking for username and password, with no details on what for. There is a curious amount of whitespace, making me think text is missing. Comparing with similar dialog I've seen at this point on Windows, I'm guessing its a proxy authentication request
5.  "OK" and "cancel" buttons animate when clicked (turn blue), but nothing happens. I'm forced to quit out of VSCode, as I can't get rid of dialog box.

The dialog looks the same as in the closed issue #97199. Similar symptoms also. But, I assume this should have been fixed in the latest insider's build?

Not sure what "environment" vscode pulls proxy information from, but I tried a few things. I've tried with and without setting http_proxy and https_proxy in shell environment before launching code from terminal. I've also tried hand-setting it in the proxy settings. Nothing prevents this problem. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
Sounds like a duplicate of #104603, which offers a workaround.

**Comment by relativistic** [comment]
Okay, thanks, installing the old version there seems to have worked. I assume the missing script is installed in the old version, and should stay through upgrades.
