### ISSUE TITLE
OS Hangs

### ISSUE THREAD

**Issue by schnautz** [microsoft/vscode#104695]
Issue Type: <b>Performance Issue</b>

MacOS hangs when loading VS Code. Mouse cursor responds, but window management hangs for several seconds.

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 7, 5|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|25%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	    98	  6003	code main
    0	    49	  6006	   gpu-process
    0	    33	  6009	   utility
    0	   229	  6010	   window (Untitled-1)
    0	    66	  6017	     extensionHost
    0	    98	  6014	   shared-process
    0	     0	  6030	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    82	  6027	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.7.96456
Industrial-Robots|Rob|0.1.4

</details>

**Comment by mjbvz** [comment]
Do you see this in VS Code 1.48 as well?

**Comment by schnautz** [comment]
I'm unsure how to recreate the issue. It's happened twice in two days.

Both times, I noticed that I was connected to WiFi but had no internet or a mismatched DNS server. I wonder if it was trying to auto-update something or do some other type of 'phone home' operation.

I've tried to recreate that scenario tonight (still in 1.47), but was unable to. I'll update to 1.48 and see if the issue returns.

**Comment by mjbvz** [comment]
Closing this for now since we haven't heard back. Let us know if you are still seeing this in VS Code 1.48
