### ISSUE TITLE
"Collapse Folders In Explorer" button doesn't work properly

### ISSUE THREAD

**Issue by piavgh** [microsoft/vscode#104641]
- VSCode Version: 1.48.0
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Add some folders into a workplace
2. Add a folder (folder A) that contains only 1 file into the same workplace
3. Expand all folders
4. Click "Collapse Folders In Explorer" button
5. See the result

The interesting thing is: if you collapse the folder A, the "Collapse Folders In Explorer" button works normally again

This is an animation to demonstrate that:
![Untitled_ Aug 14, 2020 5_08 PM](https://user-images.githubusercontent.com/4060207/90239022-1a1c4900-de51-11ea-850a-351fc5e60611.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Works fine for me. Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

Also if you F1 > developer tools > console do you see some errors?
fyi @roblourens

**Comment by piavgh** [comment]
I tried with Insider version, the result is the same, bug still happens.
And when I open the console log, there is nothing. I guess the logic in code is incorrect, so it doesn't throw any error.

Please check this gif below:

![Untitled_ Aug 15, 2020 10_06 AM](https://user-images.githubusercontent.com/4060207/90304217-98bfc780-dedf-11ea-9e73-44103137aa2d.gif)

**Comment by jeanp413** [comment]
I can easily reproduce with a workspace containing two just two folders:
- root_folder _1
  - file_1.js
- root_folder _2
  - file_2.js
  - file_3.js

I'll create a PR with a fix.
