### ISSUE TITLE
Warning about async/await even when using Typescript 2 against ES5

### ISSUE THREAD

**Issue by matthiasg** [Microsoft/vscode#10469]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. use async/await in code
2. configure tsconfig target es5

**Comment by DickvdBrink** [comment]
I believe `async/await` for ES5 is only available in the `transforms` branch which can be found [here](https://github.com/Microsoft/TypeScript/tree/transforms)

They also talk about this in there blog post for the 2.0 beta (https://blogs.msdn.microsoft.com/typescript/2016/07/11/announcing-typescript-2-0-beta/)

**Comment by matthiasg** [comment]
actually it is in it when targeting es2015 instead of es5 .. sadly typescript then doesnt transpile things like the spread operator etc, which leads to errors with uglify and also leaves IE11 behind.  Hejlsberg mentioned in the BUILD demo that they did extra work targeting async/await for downlevel es3/es5 targets without generator support. 

so the wait for usable async/await in the browser remains...
