### ISSUE TITLE
shortCut Not Working

### ISSUE THREAD

**Issue by coddeee** [microsoft/vscode#104684]
Issue Type: <b>Bug</b>

Alt + Enter to show suggestions is not working 

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.13.2
flutter|Dar|3.13.2

</details>

**Comment by mjbvz** [comment]
Please provide steps to reproduce the problem. For example, what language is this for?

/needsMoreInfo

**Comment by coddeee** [comment]
There are no specific steps required at my end, it is not working at all times, and I am only using this for Dart for the time being.
other shortcuts seem to work though I have not tested this extensively.

**Comment by mjbvz** [comment]
Start by filing this against the dart extension
