### ISSUE TITLE
After July update, and after setting up settings sync, Extensions Browser is not showing local installed extensions, and Settings Sync command has disappeared

### ISSUE THREAD

**Issue by jerryasher** [microsoft/vscode#104683]
Vscode updated itself yesterday and I set up sync and at some point I discovered All my local extensions have disappeared from the extensions browser (https://i.imgur.com/Q93VpQM.png) thought not when I list out the extensions from win/git shell  https://i.imgur.com/NiHLfSA.png  

The settings sync command, which I used to set up sync a few hours ago has disappeared! https://i.imgur.com/XcF89k4.png https://i.imgur.com/4exSaz6.png (THEY SHOULD BE FOUND LIKE THIS: https://i.imgur.com/CFEkOTQ.png)

- VSCode Version:
- OS Version:

Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Update to July
2. Set up settings sync, login with github

Does this issue occur when all extensions are disabled?: Yes/No

Yes.

I tried again with extensions disabled and saw similar behavior
https://i.imgur.com/AH4xnwv.png
https://i.imgur.com/TbWJ1Iz.png

**Comment by sandy081** [comment]
Can you please check if following built in extensions are enabled

-  Go to extensions view
- Click on filter (funnel) icon and select built in
- Look for authentication extensions

<img width="346" alt="image" src="https://user-images.githubusercontent.com/10746682/90390267-59ce7500-e08b-11ea-8dbb-84d1350fd210.png">

Please let me know if above extensions are enabled?

**Comment by jerryasher** [comment]
So, nothing shows as local in the extensions view, not even builtins, what I experience are blank panels and a constantly moving right and looping progress bar

![image](https://user-images.githubusercontent.com/666633/90466230-22c98500-e0c6-11ea-8197-2e9512814cb9.png)

> code --list-extension in powershell yields:

```
code --list-extensions
ahmadawais.shades-of-purple
atomiks.moonlight
burkeholland.simple-react-snippets
ChakrounAnas.turbo-console-log
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
dracula-theme.theme-dracula
eamodio.gitlens
emmanuelbeziat.vscode-great-icons
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
esbenp.prettier-vscode
firefox-devtools.vscode-firefox-debug
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
GitHub.github-vscode-theme
johnpapa.vscode-peacock
johnpapa.winteriscoming
ms-python.python
MS-RichCodeNav.richcodenav
ms-vscode-remote.remote-wsl
msjsdiag.debugger-for-chrome
Nimda.deepdark-material
PKief.material-icon-theme
rokoroku.vscode-theme-darcula
sdras.night-owl
vscode-icons-team.vscode-icons
wholroyd.jinja
xabikos.JavaScriptSnippets
```

**Comment by sandy081** [comment]
Start code with --verbose `code --verbose` from command line and please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by jerryasher** [comment]
Apologies, I uh couldn't wait for this to be diagnosed further, so I uninstalled, (deleted all keys in state,vscdb pointing to sync) then reinstalled vscode.

To my surprise, this fixed the problem, and yet, I expected all uninstall to delete any installed extensions, but it didn't.

At any rate, let me know if you still want this information, or if my reinstalling mooted the bug report

**Comment by sandy081** [comment]
Closing this as user got resolved the issue.
