### ISSUE TITLE
BUG: Saving file adds unknow text

### ISSUE THREAD

**Issue by Aukstkalnis** [microsoft/vscode#104627]
Issue Type: <b>Bug</b>

When I press ctrl+s to save file, for some reason I get unexpected code inserted in the file...

![rebase-example](https://user-images.githubusercontent.com/9738294/90225198-95620880-de19-11ea-8706-b0aeac64c44c.gif)

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|11.3.1
project-manager|ale|11.1.0
better-toml|bun|0.3.2
gitignore|cod|0.6.0
arm|dan|1.4.0
xml|Dot|2.5.1
gitlens|eam|10.2.2
vscode-test-explorer|hbe|2.19.1
uncrustify|Lau|2.20.6
restructuredtext|lex|129.0.0
kconfig|luv|1.0.3
cortex-debug|mar|0.3.7
vscode-todo-parser|min|1.9.1
cpptools|ms-|0.29.0
hexeditor|ms-|1.2.1
makefiles-support-for-vscode|nae|0.0.3
vscode-ceedling-test-adapter|num|1.5.2
material-icon-theme|PKi|4.2.0
devicetree|plo|0.1.1
trailing-spaces|sha|0.3.1
gitconfig|sid|2.0.1
code-spell-checker|str|1.9.0
ninja|sur|0.0.1
pdf|tom|1.1.0
cmake|twx|0.0.17
vim|vsc|1.16.0
vscode-todo-highlight|way|1.0.4
material-theme|zhu|3.8.5
linkerscript|Zix|1.0.1

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Aukstkalnis** [comment]
I disabled only Go extension and yes, it looks like this this extension's problem.
