### ISSUE TITLE
editor.formatOnSave removes semicolons & whitespace

### ISSUE THREAD

**Issue by tomorrowevening** [microsoft/vscode#104668]
- VSCode Version: 1.48.0
- OS Version: OSX 10.15.6

Steps to Reproduce:

1. "editor.formatOnSave": true in settings.json
2. Here's a screenshot of my [settings.json](https://twitter.com/VisualStudio/status/1294270048136306696)
3. I've even uninstalled/reinstalled, and removed all cache of previous versions + extensions...

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
