### ISSUE TITLE
SCM diff gutter is not working since v1.48

### ISSUE THREAD

**Issue by JohnstonCode** [microsoft/vscode#104640]
- VSCode Version: v1.48
- OS Version: Fedora 32

Steps to Reproduce:

1. Use the vscode extension
2. Make changes to a tracked file
3. No gutter appears

Does this issue occur when all extensions are disabled?: Yes (with all other extensions apart from the svn one)

Works in VSCode v1.47.3

**Comment by JohnstonCode** [comment]
https://github.com/JohnstonCode/svn-scm/issues/1042

**Comment by jordankaiser** [comment]
Confirming the same behavior, diff gutters are gone.

VS Code: Version: 1.48.0
OS: Max OS 10.12.4

**Comment by hdpoliveira** [comment]
Confirming the same behavior in vscode-hg: https://github.com/mrcrowl/vscode-hg/issues/158

**Comment by hdpoliveira** [comment]
Looking at git extension, seems it is using registerFileSystemProvider, while vscode-hg uses registerTextDocumentContentProvider. I'm not sure what the differences are between the two.

**Comment by hdpoliveira** [comment]
I've reimplemented Mercurial's context provider in terms of registerFileSystemProvider and the gutter indicator works.

Used https://github.com/microsoft/vscode/blob/master/extensions/git/src/fileSystemProvider.ts as reference.

**Comment by hdpoliveira** [comment]
@joaomoreno @mjbvz please let us know if SCM extensions should be moved to use FileSystemProvider or stick to TextDocumentContentProvider

TextDocumentContentProvider was removed from git on 15 Apr (https://github.com/microsoft/vscode/commit/b8512b2055f4cfa63971bd83f49ea4c835e9cfcc)

**Comment by isidorn** [comment]
since @joaomoreno is on vacation forwarding to @eamodio as he might know more

**Comment by eamodio** [comment]
@hdpoliveira As for a recommendation, I would say it depends on the use-case. If you were to start today, I would definitely recommend using a `FileSystemProvider` (even though its harder to use, it provides the ability to do a lot more and better deals with any encoding issues (since it uses the built-in vscode encoding mechanisms). At the same time, if you have a narrower use-case and `TextDocumentContentProvider` is fulfilling your needs, I don't see a reason to switch. And we aren't planning to deprecate the `TextDocumentContentProvider` or anything.

I will dig into what changed with the `TextDocumentContentProvider` that's causing this issue.

**Comment by hdpoliveira** [comment]
Hi @eamodio !
I decided to switch to FileSystemProvider in Mercurial extesion, given that Git extension is using it and Perforce extension is too.

**Comment by eamodio** [comment]
I'm pretty sure this was introduced because of this commit: https://github.com/microsoft/vscode/commit/003a3678c879ee5e9a72ad9e5088d89672d75bd8, but still investigating a fix

**Comment by isidorn** [comment]
@eamodio thanks for investigating, should this be a candidate (sounds like a regression, but not high impact). You would know better.

**Comment by henry000dev** [comment]
The issue has gone away - I can see the gutters are now available again with release 1.48.2.

**Comment by RLThomaz** [comment]
> The issue has gone away - I can see the gutters are now available again with release 1.48.2.

The issue is still there for me - Ubuntu 18.04, vscode 1.48.2.

**Comment by brneor** [comment]
Can confirm gutter diff is showing up again on 1.48.2 under Windows and Linux.

**Comment by RLThomaz** [comment]
Okay, gutter diff is showing up again, but only if you get the latest version of SVN-SCM (https://github.com/JohnstonCode/svn-scm/pull/1053), the fix was not due to the new VSCode release (1.48.2).

**Comment by joaomoreno** [comment]
> @joaomoreno @mjbvz please let us know if SCM extensions should be moved to use FileSystemProvider or stick to TextDocumentContentProvider

This was definitely an unintended breakage. Looking into where the assumption actually breaks down...

**Comment by joaomoreno** [comment]
I believe the wrong assumption lies here: https://github.com/microsoft/vscode/blob/018e9a21f1c50e8b09ff72e523bb431da36dc309/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L1145-L1145

This breaks down with model references coming in from `TextDocumentContentProvider`, in `ref.object` is an instance of `ResourceEditorModel` which does not implement `IResolvedTextFileEditorModel`. @bpasero I remember we did this together, can you guide towards a solution here?

**Comment by joaomoreno** [comment]
Thanks to @bpasero for the help in fixing this!

**Comment by misolori** [comment]
Confirmed that this works now works using an [svn](https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm) project:

![image](https://user-images.githubusercontent.com/35271042/92155615-851bc880-eddc-11ea-82e5-e75465546a7f.png)

**Comment by DavidGoldman** [comment]
When will this fix by released? v1.49?

**Comment by misolori** [comment]
@DavidGoldman yes, this will be in out in the August release (1.49) which should drop next week.
