### ISSUE TITLE
Insiders: Settings sync notification link doesn't link to information about the separate service

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#104652]
The 'release notes' link in the notification

![image](https://user-images.githubusercontent.com/172399/90249257-6c9e3b00-de3a-11ea-9cf9-64833f3c0e94.png)

points to the insiders release notes, which doesn't include information about the separate service.

(simplest fix is to have a link from the insiders release notes to the 1.48 release notes section that explains the separate service.

**Comment by Tyriar** [comment]
As a workaround I copied over the section from the 1.48 release notes in its entirety as it's quite small (better than 2 link jumps for a tiny explanation). We should switch the link to point at https://code.visualstudio.com/updates/v1_48#_settings-sync instead of opening the release notes.

**Comment by sandy081** [comment]
This is insiders only feature and hence removing from recovery milestone.

**Comment by sandy081** [comment]
Instead of showing release notes, I would like to point to Settings Sync doc that talks about Settings Sync Services (insiders & stable) - https://code.visualstudio.com/docs/editor/settings-sync#_syncing-stable-versus-insiders
