### ISSUE TITLE
Open and delete file cause vscode to crash

### ISSUE THREAD

**Issue by guocongyun** [microsoft/vscode#104604]
- VSCode Version:1.48
- OS Version: Manjaro

Steps to Reproduce:

1. clone repository from github
2. rm -rf the repository cloned
3. code 'repository name' or code 'file name' (I'm not sure which step is the cause)

I can not open or delete file or folder on my computer atm, so I'm not able to recreate the issue
Right now, open file, delete file, open folder causes vscode to become unresponsive for about 1 second and then close by itself. When I tried (code 'file name' ) vscode creates a unsaved 'file name' tab that I am unable to close.
I have tried to reinstall or use the insider version of vscode, however vscode still crashes when I attempt to open file from folder.
Does this issue occur when all extensions are disabled?: Yes

**Comment by guocongyun** [comment]
the vscode 1.47.1 from pacman seem to work, but the 1.48.0 version from snap craft is still not able to open folder properly.

**Comment by bpasero** [comment]
@guocongyun to clarify, VSCode crashes when you select File > Open?

**Comment by guocongyun** [comment]
Yes, File > Open, File > Open Folder, File > Open Workspace causes VSCode to crash. And deleting file also causes VSCode to crash

**Comment by guocongyun** [comment]
The problem appears to be similar to #55934 and #104383

**Comment by bpasero** [comment]
@guocongyun did you install from Snap store?

**Comment by guocongyun** [comment]
Yeah, its the version 1.48 from Snap store thats not working.

**Comment by guocongyun** [comment]
But since there is already a existing similar issue, I'm just going to close this one
