### ISSUE TITLE
Need git tools to manage git projects in subdirectories

### ISSUE THREAD

**Issue by senlinding** [microsoft/vscode#104630]
Issue Type: <b>Feature Request</b>

Need git tools to manage git projects in subdirectories.
In a large project, there are multiple git projects.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.15.0-107-generic
Remote OS version: Linux x64 4.15.0-107-generic

**Comment by gjsjohnmurray** [comment]
You may like to try what's coming in the next release. Today's Insiders gives us https://github.com/microsoft/vscode/issues/104151

**Comment by isidorn** [comment]
Seems like this is done, thus closing
