### ISSUE TITLE
VScode flags nested from group as error

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#104660]
Issue Type: <b>Bug</b>

Every time I use an Angular formGroup in a nested component, VScode flags it as an error although the app runs fine and there are no console errors.  I assume it's something  about typing confusing it, but I've tried all I can think of and I get this error: 
<img width="813" alt="Screen Shot 2020-08-14 at 9 59 33 AM" src="https://user-images.githubusercontent.com/835148/90257232-e7545f80-de14-11ea-9a47-6828e25256c4.png">

Here is my setup:

## Parent Component
```html
  <h5>Billing Address</h5>
  <form [formGroup]="addressBlockForm">
    <spg-shared-address-block-au [formGroup]="addressControl"> </spg-shared-address-block-au>
  </form>
```

```typescript
import { Component, OnInit } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';

@Component({
  selector: 'spg-user-dialog-add-payment',
  templateUrl: './dialog-add-payment.component.html',
  styleUrls: ['./dialog-add-payment.component.scss']
})
export class DialogAddPaymentComponent implements OnInit {
  constructor(
    private fb: FormBuilder
  ) {}

  addressBlockForm = this.fb.group({
    country: ['AU', Validators.required],
    addressForm: this.fb.group({ // this is a duplicate of fields in nested form
      address: ['', Validators.required],
      address2: [''],
      postalCode: ['', Validators.required],
      city: ['', Validators.required],
      state: ['', Validators.required]
    })
  });

	// "addressControl" is what you passed as the formGroup input in the html of the component
  get addressControl() {
	  // "addressForm" is the name of the group control above inside "addressBlockForm"
    return this.addressBlockForm.controls.addressForm as FormGroup
  }

  ngOnInit(): void {}


}
```

## The child component
```typescript
import { Component, OnInit } from '@angular/core';
import { FormBuilder, Validators, ControlContainer, FormGroupDirective } from '@angular/forms';

import { STATES } from './states';

@Component({
  selector: 'spg-shared-address-block-au',
  templateUrl: './address-block-au.component.html',
  viewProviders: [
    {
      provide: ControlContainer,
      useExisting: FormGroupDirective
    }
  ],
  styles: []
})
export class AddressBlockAuComponent implements OnInit {
  states = STATES;

  constructor(private fb: FormBuilder) {}

  addressForm = this.fb.group({
    address: ['', Validators.required],
    address2: [''],
    postalCode: ['', Validators.required],
    city: ['', Validators.required],
    state: ['', Validators.required]
  });

  get f() {
    return this.addressForm.controls;
  }

  ngOnInit(): void {}
}
```

```html
<form class="form" [formGroup]="addressForm" autocomplete="off" novalidate>
  <div class="row">
    <div class="col-12">
      <div class="form-group">
        <label for="address">Address Line 1</label>
        <input
          id="address"
          autocomplete="address-line1"
          type="text"
          name="address1"
          class="form-control"
          [ngClass]="{ 'is-invalid': f.address.invalid && f.address.touched }"
          formControlName="address"
          required
        />
        <p class="invalid-feedback">Enter an address.</p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="form-group">
        <label for="address2"
          >Address Line 2
          <span class="optional">(optional)</span>
        </label>
        <input type="text" id="address2" class="form-control" autocomplete="address-line2" formControlName="address2" />
      </div>
    </div>
  </div>

  <div class="form-row">
    <div class="col-sm-4">
      <div class="form-group">
        <label for="postalCode">Postal Code</label>
        <input
          type="text"
          id="postalCode"
          class="form-control"
          autocomplete="postal-code"
          [ngClass]="{ 'is-invalid': f.postalCode.invalid && f.postalCode.touched }"
          formControlName="postalCode"
          required
        />
        <p class="invalid-feedback">Enter a valid postal code.</p>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="form-group">
        <label for="city">Town/City</label>
        <input
          type="text"
          id="city"
          class="form-control"
          autocomplete="address-level2"
          [ngClass]="{ 'is-invalid': f.city.invalid && f.city.touched }"
          formControlName="city"
          required
        />
        <p class="invalid-feedback">Enter a town or city.</p>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="form-group">
        <label for="state">State </label>

        <select
          id="state"
          class="form-control"
          autocomplete="address-level1"
          [ngClass]="{ 'is-invalid': f.state.invalid && f.state.touched }"
          formControlName="state"
        >
          <option value="">Select</option>

          <option *ngFor="let state of states" [value]="state.code">{{ state.name }}</option>
        </select>
      </div>
    </div>
  </div>
</form>

```

#angular/forms

VS Code version: Code - Insiders 1.49.0-insider (bd08768fd310d34cdd4423a53e5f3ca77340fea5, 2020-08-14T06:47:57.598Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (1.77GB free)|
|Process Argv|-psn_0_561289 --crash-reporter-id 2989f78b-23b4-466d-ae73-bbe6c5fe1c40|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|1.6.2
Bookmarks|ale|11.3.1
project-manager|ale|11.1.0
ng-template|Ang|0.1000.7
change-color-format|bbu|1.0.0
vscode-multi-line-tricks|big|0.0.3
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
vscode-npm-script|eg2|0.3.13
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.1.3
todo-tree|Gru|0.0.178
json-to-ts|Mar|1.7.5
rainbow-csv|mec|1.7.1
ecdc|mit|1.3.0
HTMLHint|mka|0.8.0
theme-monokai-pro-vscode|mon|1.1.17
debugger-for-edge|msj|1.0.15
angular-console|nrw|13.0.0
vscode-versionlens|pfl|1.0.8
quicktype|qui|12.0.46
code-settings-sync|Sha|3.4.3
rewrap|stk|1.13.0
ayu|tea|0.20.1
vscode-input-sequence|tom|0.2.0
sort-lines|Tyr|1.9.0
vscode-icons|vsc|10.2.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.2.0

(4 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

Most likely this one comes from one of extension you are using (I guess it's `ng-template`. Similar error reported there https://github.com/angular/vscode-ng-language-service/issues/842)
![image](https://user-images.githubusercontent.com/1312662/90277876-11d30680-de6f-11ea-8173-5478a1d51ad2.png)

Errors with types (from TS) has `ts(code)` format:
![image](https://user-images.githubusercontent.com/1312662/90277958-3d55f100-de6f-11ea-8e0c-fbffc53f8448.png)
