### ISSUE TITLE
terrible ui decision in the source control dropdown

### ISSUE THREAD

**Issue by ELI7VH** [microsoft/vscode#104688]
- VSCode Version: latest
- OS Version: ubuntu 18.04

Steps to Reproduce:

1. go to source control tab
2. open it, see how WRONG it is

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/11658002/90293458-55168080-de41-11ea-9195-eb7b79c04fbc.png)

don't put things that are often used in a sub menu. that is like UI 101. fire the person who did this.

**Comment by ELI7VH** [comment]
now that I have cooled off from rage: let's put all the most used elements of the menu in the top of it.

- push
- pull 
- commit

**Comment by JanBN** [comment]
totally agree

**Comment by gjsjohnmurray** [comment]
As a workaround I just published a [simple extension](https://marketplace.visualstudio.com/items?itemName=georgejames.gitfavorites).
