### ISSUE TITLE
VSCode does not detect file changes made outside of vscode

### ISSUE THREAD

**Issue by IronChris** [Microsoft/vscode#10462]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10463

**Comment by bpasero** [comment]
@IronChris steps?

**Comment by IronChris** [comment]
i had a file open in vscode , but made a change in notepad on the same file 
after closing the file in vscode and reopening  , i could see the changes.
before closing vscode asked me to save changes , which would destroy my work in notepad 

the files are part of an angular2 progect the lite-server was running 

i was trying to reproduce it , but now the changes are , in view directly after saving it in notepad
