### ISSUE TITLE
Release notes / extension page scrolling issue

### ISSUE THREAD

**Issue by wyrd-code** [microsoft/vscode#104665]
Issue Type: <b>Bug</b>

Hi guys,

this might not be a bug, but it certainly is a frustrating feature. Whenever I read new release notes or an extension page, I go to check out a settings page or another tab to see what the release notes are describing. When I change focus from the release notes tab, it loses it's scroll position and I have to scroll down every time to continue reading where I left off.

That's horrible UX and is not consistent with how code tabs are handled.

Please fix that. Thank you kindly

VS Code version: VSCodium 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T19:08:44.569Z)
OS version: Linux x64 4.15.0-112-generic snap

**Comment by gjsjohnmurray** [comment]
/duplicate of #27498

@mjbvz maybe you can get #85982 merged for next time?
