### ISSUE TITLE
Trusted Types compatibility: use DOM API for creating HTML elements instead of string concatenation in cellRenderer.ts

### ISSUE THREAD

**Issue by annkamsk** [microsoft/vscode#104661]
The next step in resolving #103699. It aims to replace construction of HTML elements by string concatenation in all of the simple cases (i.a. when the text content of the element is not rendered in any special way).

For example:
Replace
```this._domNode.innerHTML = ‘<span>no commands</span>’;```
with
```this._domNode.innerText = ‘’;
this._domNode.appendChild(createHTMLElement<HTMLSpanElement>(‘span’, ‘no commands’);
```

This issue is separated from #104643 as it occurs in what appears to be a more sensitive code, covered with more test cases and placed in a separate module. The issue type and fix strategy should be the same though.

Edit: + @koto @engelsdamien

**Comment by jrieken** [comment]
@roblourens fyi - I have pushed a fix for not using `innerHTML` tho it does seems the logic of `getMarkdownDragImage` can be improved: https://github.com/microsoft/vscode/blob/e6cf885abb16458fd822730005761e3dfefd1fca/src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts#L456-L468

It seems to be only interested in a small subset of nodes of the original element
