### ISSUE TITLE
master

### ISSUE THREAD

**Issue by seveneElevenup** [microsoft/vscode#104642]
Issue Type: <b>Bug</b>

拉取是dev分支但是坐下角还是显示master

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (2.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
cssrem|cip|0.1.0
auto-close-tag|for|0.5.8
go|gol|0.16.1
vscode-language-pack-zh-hans|MS-|1.48.3
cpptools|ms-|0.29.0
vetur|oct|0.26.1
open-html-in-browser|pea|2.1.3
highlight-matching-tag|vin|0.9.9
markdown-all-in-one|yzh|3.2.0

(1 theme extensions excluded)

</details>

**Comment by mochaaP** [comment]
Please do a checkout to your `dev` branch.

---

请 Checkout 到你的 `dev` 分支。

**Comment by mjbvz** [comment]
Closing as more information needed
