### ISSUE TITLE
Make editor.snippetSuggestions: bottom the default

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10467]
I think we should make `editor.snippetSuggestions: bottom` the default. If I am a user and I see this:

![screen shot 2016-08-12 at 12 29 00](https://cloud.githubusercontent.com/assets/900690/17619865/7e49e978-6088-11e6-8412-808f3b96f1b3.png)

My first reaction is that IntelliSense is stupid and not picking up the valid values. When I change to the setting, I get this:

![screen shot 2016-08-12 at 12 29 12](https://cloud.githubusercontent.com/assets/900690/17619877/8fcbc112-6088-11e6-94fa-c45ad30fbf20.png)

Which indicates to  me that the editor actually knows what I am doing.

@jrieken @aeschli @egamma fyi

**Comment by jrieken** [comment]
👍

**Comment by egamma** [comment]
No objections.

**Comment by animanoir** [comment]
How can I revert this strange change to make VSC wonderful again?

**Comment by jrieken** [comment]
Add the following to your settings: `"editor.snippetSuggestions": "top"`
