### ISSUE TITLE
FileSystemProvider whose uris use the query element is not properly handled by conflict resolution feature

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#104698]
I am developing an extension that implements a FileSystemProvider for which the query element of the uri is significant.

When an edited document is saved and VS Code detects that the target file is newer, VS Code correctly offers this notification:

![image](https://user-images.githubusercontent.com/6726799/90298835-9764af80-de8b-11ea-955e-9e3816ffbc6c.png)

But when the 'Compare' option is taken, the uri sent to the FSP has lost its query string.

The fault is here:

https://github.com/microsoft/vscode/blob/cc29a814476d9d9366e7687a16cff1af0641fbdf/src/vs/workbench/contrib/files/common/files.ts#L166-L172

`resourceToTextFile` sequesters the query element to stash the original scheme when setting a new scheme. Later `textFileToResource` reverses this process, but in doing so it has lost the query element of the original uri.

I will submit a PR.

**Comment by bpasero** [comment]
@gjsjohnmurray I oversaw test unit failures in https://github.com/microsoft/vscode/blob/185bf255ad6e5e26c293725846dc6608db86a42a/src/vs/workbench/contrib/files/test/browser/fileOnDiskProvider.test.ts#L23. I reverted the change and it would require a new PR + fix to address.

**Comment by bpasero** [comment]
@gjsjohnmurray thought I would have a closer look into it and noticed that the test was not ideal. All in all pushed it back via https://github.com/microsoft/vscode/commit/e55f6c99ccb126137375cb1636a581d7678b85c3

**Comment by gjsjohnmurray** [comment]
@bpasero thanks very much.
