### ISSUE TITLE
Extension list not load behind corp proxy with NTLM

### ISSUE THREAD

**Issue by McMlok** [Microsoft/vscode#10461]
- VSCode Version: 1.3.1
- OS Version: Windows 7

Steps to Reproduce:
1. Open VS Code
2. CTRL+P
3. ext install csharp

My settings.json is 
{
    "http.proxy": "http://[DOMAIN]%5C[USER]:[PASS]@proxy.corp.cz:8080",
    "https.proxy": "http://[DOMAIN]%5C[USER]:[PASS]@proxy.corp.cz:8080",
    "http.proxyStrictSSL": false
}

There is no error but nothing happens.

I look at WireShark and see 
CONNECT marketplace.visualstudio.com:443 HTTP/1.1\r\n
Proxy-Authorization: Basic ZHNcbXRvbWFzb3Y6TWFsYWNoaSoyNTY=\r\n
        Credentials: [DOMAIN][USER]:[PASS]

But our proxy needs NTLM not Basic. Is there chance to say VS Code to use NTLM?

Thanks

**Comment by joaomoreno** [comment]
Can you try with the [latest insiders release](https://code.visualstudio.com/insiders)?

**Comment by McMlok** [comment]
I try it with same result.

**Comment by maibaum** [comment]
Experiencing a similar issue behind SSL-breaking firewall - details: https://github.com/Microsoft/vscode/issues/10540

**Comment by Lakritzator** [comment]
I have the same problem, just wanted to confirm that I cannot use Visual Studio Code behind a Corporate proxy. Had a hard time installing it, as the installer need admin right, but in the end it was for nothing as there is not much sense of using it without extensions :disappointed:

**Comment by ywmail** [comment]
before v1.5.1, I use cntlm to translate the NTLM proxy to a none encrypted proxy, it worded ok. After update to 1.5.1, neither NTLM proxy or  cntlm works. I also have `"http.proxyStrictSSL": false` set, but it seems does nothing with promotes `unable to verify the first certificate`.

**Comment by joaomoreno** [comment]
@ywmail #11702

**Comment by McMlok** [comment]
cntlm as workarround works. Thanks

**Comment by f-mon** [comment]
same issue, no extension gallery working on 1.9.1 behind corporate proxy.
it seems proxy configurations in settings.json doesn't affect the extension gallery.
Any news on this bug?

**Comment by joaomoreno** [comment]
@f-mon #18103

**Comment by er06645810** [comment]
Same issue for me too. Notably, installing via the command line works for most extensions. However, some extensions like cpptools attempt to download additional components when vscode launches the first time after installation, and that fails.

**Comment by joaomoreno** [comment]
Support comes with #22369

Merging with #27838
