### ISSUE TITLE
Missing prompt to save changes when closing VSCode

### ISSUE THREAD

**Issue by joh423** [microsoft/vscode#104690]
There are three serious problems:
1. VSCode just showed me i can no longer trust that it shows me the actual file I'm opening. Instead, it might show me some changes i made before i last closed VSCode but which somehow haven't been committed to the file system.
2. VSCode fails to ask me what to do with my unsaved changes when i close VSCode
3. Closing VSCode (e.g. with ALT+F4 or clicking the X in the top right of the window) fails to exit the actual process

Maybe it's a feature, but if it is i find it more dangerous than helpful and if not resolved, because I need to be able to trust my editor with respect to what it's loading:
1. Open a file in VSCode
2. Modify the file but don't save it.
3. Close VSCode (click the X in the top right corner of the window or press ALT+F4)
4. Note VSCode just closes without asking you what to do with your unsaved changes. Note further that the process is still visible in task manager. Closing VSCode behaved more like minimizing it (without showing a remnant in the task bar or task tray). 
5. Open the edited file in a **_different_** editor (e.g. notepad, or use "more" on the command line). Note the file hasn't changed since you modified it.
6. Open the file in VSCode again. Note how VSCode magically opens that file with your unsaved changes intact... instead of showing you the current version from the file system.

IF THIS IS INDEED A FEATURE:
1. give the user an option to "save state" when closing VSCode while there are pending changes, in addition to saving files or dismissing changes. Give the user an option here to opt into "always save state when i close VS, don't ask me again"
2. when opening VSCode with pending changes restored, notify the user that some files were loaded with unsaved previous changes, and how to identify those files (e.g. the color circle in the file tab). Give the user an option to never show this warning again.use it was too large to send. Please paste.

CPUs | Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (4 x 2112)
-- | --
GPU Status | 2d_canvas: unavailable_softwareflash_3d: disabled_softwareflash_stage3d: disabled_softwareflash_stage3d_baseline: disabled_softwaregpu_compositing: disabled_softwaremultiple_raster_threads: enabled_onoop_rasterization: disabled_offopengl: disabled_offprotected_video_decode: disabled_offrasterization: disabled_softwareskia_renderer: disabled_off_okvideo_decode: disabled_softwarevulkan: disabled_offwebgl: unavailable_softwarewebgl2: unavailable_software
Load (avg) | undefined
Memory (System) | 8.00GB (1.57GB free)
Process Argv | C:\Users\jo\Downloads\test.json --crash-reporter-id 40b02b05-c1f7-4777-810d-3f3d6b531e4f
Screen Reader | no
VM | 0%

Extensions: none

**Comment by gjsjohnmurray** [comment]
This feature is called [Hot Exit](https://code.visualstudio.com/docs/editor/codebasics#_hot-exit)

**Comment by joh423** [comment]
That sounds like a cool feature. Can we please tell users about it before we just turn it on by default? (see bottom part of my feedback on "if this is indeed a feature")

**Comment by Tyriar** [comment]
We don't plan on making these changes, hot exit is largely modelled after other editors which acts very similarly and is also enabled by default. We have many features that we would love to tell people about but if we did, VS Code would change from a lightweight editor to a heavy annoying mess filled with popups and notifications, it's a difficult balance that we have to find and based on the number of incoming issues like these, we find hot exit rarely causes confusion.

You have the following options:

- Disable hot exit: `"files.hotExit": "off"`
- Enable auto save: `"files.autoSave": "afterDelay"`
- Check the save indicator before you start editing: 
   ![image](https://user-images.githubusercontent.com/2193314/92613500-e544bb80-f26f-11ea-9360-5690a583521e.png)
