### ISSUE TITLE
Git: Pull changes

### ISSUE THREAD

**Issue by edudiak** [microsoft/vscode#104624]
Issue Type: <b>Feature Request</b>

It is very inconvenient that now i have to open many sub-items to make a pull https://prnt.sc/tzedbz , please return as it was before

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041

**Comment by gjsjohnmurray** [comment]
As a workaround I just published a [simple extension](https://marketplace.visualstudio.com/items?itemName=georgejames.gitfavorites).
