### ISSUE TITLE
[folding] Folding via regex

### ISSUE THREAD

**Issue by dwall60** [microsoft/vscode#104667]
@dwall60 Thanks for the feedback. Would you mind filing a separate issue that also shows a bit how this works in SlickEdit. I'm curious to know how users provide the regexes and how the regexes look like (one regex for the whole region, or separate start end regexes)

_Originally posted by @aeschli in https://github.com/microsoft/vscode/issues/18805#issuecomment-673949486_

A single regex is applied to the currently open file and you can choose to only view lines that match the regex or hide lines that match it.

Example file contents:
line 1
random text
line 2
something else

regex: line.+\d+

I've chosen to show all lines that match the regex:
line 1
line 2

If I choose to hide all lines that match:
random text
something else

You can also choose to copy only the visible lines to paste somewhere, which is how I was able to paste the lines above.

You can try SlickEdit as a trial to see what it does if you want. The feature is called "Selective Display".

**Comment by dwall60** [comment]
I believe I now understand the source of your question. The regex applies to the whole file and not a region, although it could apply to a region I guess.

In embedded development in which we work with devices, it is very common to obtain a log from a device and collapsing that log on a set of messages gives a view into the progression of an issue related to the remaining data after the other data is folded away. Then it is beneficial to go to a particular folded message and expand it to see what the surrounding messages look like as well. So this is a situation where the regex should apply to the whole file.

An Android logcat file would be another example. So folding is very beneficial not only for code files.

Here's how it is done in SlickEdit:
![image](https://user-images.githubusercontent.com/67444431/90311495-64411100-dec9-11ea-9d3e-35025e22ae91.png)

**Comment by aeschli** [comment]
Thanks a lot, the screenshot is very helpful. If I get this right, the main purpose is to temporarily hide some content. How do you turn off the selective display again?

**Comment by dwall60** [comment]
When it's collapsed on the regex, it looks like this:
![image](https://user-images.githubusercontent.com/67444431/90424917-e7f72b00-e08c-11ea-8f0c-63e7246ae12e.png)

You can click on a '+' to expand a single fold (like the '>' in VS Code), or you can press a key combination to expand all or collapse all.
