### ISSUE TITLE
Call native logging APIs when debugging in the extension host

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104686]
Currently in extension host debugging, logged messages are placed directly in the Debug Console and bypass js-debug.

However, now (as of https://github.com/microsoft/vscode-js-debug/issues/412) js-debug has the capability to replace paths stacktraces thrown from compiled code with their respective source locations, so there's a compelling benefit to change this behavior. Either to actually call the native APIs (which would be the easiest for me 😄) or implement some custom DAP message to pass the log through the debugger here

https://github.com/microsoft/vscode/blob/cc29a814476d9d9366e7687a16cff1af0641fbdf/src/vs/workbench/contrib/debug/browser/debugService.ts#L144

**Comment by weinand** [comment]
Since extension debugging is a private feature of VS Code, we can use any mechanism that works...

However, there is the DAPTracker API and we have LiveShare that uses the tracker to do their magic.
So we should always keep this in mind when bypassing anything.

**Comment by isidorn** [comment]
@connor4312 let me know you would like to tackle this with me? I am flexible.

**Comment by connor4312** [comment]
Sure. I'm available next week, feel free to send an invite or grab me whenever we're both online.

**Comment by connor4312** [comment]
Isi and I looked at this on a call this morning. The best way to deal with, among other alternatives, would be to have the extension host call the native methods, as in the title. This would also, as opposed to a custom dap message, allow us to expand and inspect logged objects link we normally would. It would also let us filter out messages that don't come from your extension, which I would personally _love_ to have, since we get a stacktrace in CDP log messages.

The log messages are replaced in bootstrap-fork:

https://github.com/microsoft/vscode/blob/2a1c8bbaf295cb138df5ad04a2b4e277b6f5a377/src/bootstrap-fork.js#L139-L147

I've made these call native APIs in the linked commit. However, there's also manual handling of output, which results in duplicate log messages being output.

https://github.com/microsoft/vscode/blob/6f87c1cf7f3e23226778503e32fce79767b2ab89/src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts#L232

It seems like @joaomoreno authored this code, a long time ago. I'm not sure what the best approach is. Ideally we could call the console log method and avoid writing to stdout, but that doesn't seem possible. You can make a [new Console](https://nodejs.org/docs/latest-v12.x/api/console.html#console_new_console_options), but this does not result in the required CDP methods firing. Maybe we write a "marker" byte around the console messages so that the output handling skips them?

**Comment by weinand** [comment]
I like the approach to call the native methods (and the "marker byte" workaround sounds OK to me).

In general we should strive for minimising the amount of custom code for extension debugging.

**Comment by isidorn** [comment]
I also like this approach! Nice work @connor4312

**Comment by connor4312** [comment]
ping @isidorn if you wanted to verify this 🙂

**Comment by isidorn** [comment]
Thanks for the ping, I have verified that this works fine.
