### ISSUE TITLE
Setting "workbench.editor.restoreViewState: false" does not work for non-active editors closing

### ISSUE THREAD

**Issue by etthree** [microsoft/vscode#104676]
The position will be reset only in the current tab, but should be in all, it works fine at 1.46

- VSCode Version: 1.48
- OS Version: Windows 10 2004

Steps to Reproduce:

1. Open file
2. Move the cursor to another line
3. Open another file
4. Move the cursor in this file to another line
5. Close all (Ctrl+K W)
6. Open files again

The position will be reset only in the active tab, another files will be restored.
Also works if you close current files one by one.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I can reproduce.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/1689304b527a97e79317d5094b35eef00b433ea0
