### ISSUE TITLE
[v1.48] [Breaking] Cannot authenticate proxies

### ISSUE THREAD

**Issue by matthewkwong2** [microsoft/vscode#104603]
Same issue as #97199, just on a different version.

- VSCode Version: 1.48
- OS Version: Windows 10

Does this issue occur when all extensions are disabled?: Yes

Edit
**Possible reason: In `<installation_folder>\resources\app\out\vs\code\electron-sandbox\proxy`, `auth.js` is missing. `auth.html` imports this script but it is not there. This might explain why the submit action does nothing.**

Edit 2
Thanks, @ota-meshi for the workaround:
1. Download [`auth.js`](https://github.com/microsoft/vscode/blob/master/src/vs/code/electron-sandbox/proxy/auth.js)
2. Place it in `<installation_folder>\resources\app\out\vs\code\electron-sandbox\proxy`

**Comment by matthewkwong2** [comment]
Possible reason: In `<installation_folder>\resources\app\out\vs\code\electron-sandbox\proxy`, `auth.js` is missing. I notice `auth.html` imports `auth.js` but this file does not exist.

**Comment by ota-meshi** [comment]
FYI, I was able to get it working by downloading and placing the following file.
https://github.com/microsoft/vscode/blob/master/src/vs/code/electron-sandbox/proxy/auth.js

**Comment by shamarin** [comment]
Confirm, an old bug returned.

**Comment by shamarin** [comment]
> FYI, I was able to get it working by downloading and placing the following file.
> https://github.com/microsoft/vscode/blob/master/src/vs/code/electron-sandbox/proxy/auth.js

Where to place it?

**Comment by matthewkwong2** [comment]
> Confirm, an old bug returned.

Not exactly an old bug. It's more like the devs team forgot to bundle the 1 single script.



> > FYI, I was able to get it working by downloading and placing the following file.
> > https://github.com/microsoft/vscode/blob/master/src/vs/code/electron-sandbox/proxy/auth.js
> 
> Where to place it?

See my edit of the OP.

**Comment by ota-meshi** [comment]
I think the easiest workaround is to install the downgraded VSCode from the following link.
https://code.visualstudio.com/updates/v1_47

**Comment by Relax594** [comment]
same on MacOS. Makes the whole tool useless as you can't click anything than force quit the application.

**Comment by bpasero** [comment]
@deepak1556 looks like this file needs to be explicitly listed somewhere here (I think the `auth.css` does not exist anymore and can be removed):

https://github.com/microsoft/vscode/blob/185bf255ad6e5e26c293725846dc6608db86a42a/build/gulpfile.vscode.js#L82

**Comment by deepak1556** [comment]
Sorry about the breakage.

Thanks @ota-meshi for narrowing down the issue.

**Comment by deepak1556** [comment]
Steps to verify:

* Clone https://github.com/joaomoreno/proxy-containers
* cd basic-auth && ./run.sh
* open code-insiders
* Settings > Proxy > http://127.0.0.1:3129
* Open developer tools > fetch('https://github.com') or perform any network request
* play with the auth dialog
