### ISSUE TITLE
Setting Git Sync Keybinding Breaks Git View Keybinding

### ISSUE THREAD

**Issue by sebasijan** [Microsoft/vscode#10468]
- VSCode Version: 1.3.1
- OS Version: Windows 7 Professional (SP1)

Steps to Reproduce:

1. Change `keybindings.json` to the following: 

        // Place your key bindings in this file to overwrite the defaults
        [
            {"key": "ctrl+shift+g ctrl+shift+s",    "command": "workbench.action.git.sync"}                                     
        ]

2. The new action works, but now when trying to access git with `ctrl + shift + g`, I am seeing the message:

> (Ctrl + Shift + G) was pressed. Waiting for second key of chord...

Even though the default keybindings still contain

`{ "key": "ctrl+shift+g",          "command": "workbench.view.git" }`

 3. I also tried including `"when": "editorFocus"` to my Sync keybinding but with no luck.

**Comment by jrieken** [comment]
`ctrl+shift+g ctrl+shift+s` defines a cord - that means `ctrl+shift+g` isn't a short cut anymore but only the first part of a double short cut.
