### ISSUE TITLE
download speed very poor

### ISSUE THREAD

**Issue by war1644** [Microsoft/vscode#10460]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.download speed very poor,  avg speed < 30kb/s

**Comment by jrieken** [comment]
@war1644 of extensions or the editor. and would also help to know where you are located and what your average speed is

**Comment by sandy081** [comment]
Closing this issue since we did not get enough info. Please provide required info and reopen. Thanks.
