### ISSUE TITLE
Can't close an auto-opened window

### ISSUE THREAD

**Issue by Nexflame** [Microsoft/vscode#10466]
- VSCode Version: 1.4.0
- OS Version: Windows 10 (10.0.10586)

Steps to Reproduce:

1. Create a file (name it X)
2. Delete file, but do not close the auto-opened window,
3. Create a folder with same name as the file (X)
4. Try to close the opened window.

L.E: 'Error: File is directory (c:\blabla\X)'

**Comment by bpasero** [comment]
@Nexflame What is "the auto-opened window"? Can you share a video or screenshots?

**Comment by Nexflame** [comment]
Sorry for being misleading: what i call "the auto-opened window" is the main view (or window, or Tab) of the program, where you see the content of the file. When you create a file this view is automatically opened.
![2016-08-14 1](https://cloud.githubusercontent.com/assets/1640443/17649523/1d68b0e4-6240-11e6-888b-8634965f4a08.png)
In this screenshot you can see 3 "auto-opened windows": 1."src", 2."test", 3."test2"

Remaking this seems that you have to type something in the file X and to not save it for this bug to occur. So the steps to reproduce are:

Steps to Reproduce:

1. Create a file (name it X)
2. Type something in the file, but DO NOT save
3. Delete file X, but do not close the auto-opened window.
4. Create a folder with same name as the file (X)
5. Try to close the opened window.

**Comment by bpasero** [comment]
Ok thanks, this is fixed for the next release. You cannot delete a file when it is dirty anymore.
