### ISSUE TITLE
Same view for source control

### ISSUE THREAD

**Issue by ZiTAL** [microsoft/vscode#104621]
When project has 1 or more source control, there is a helper with branch name, when has 1 only, the helper is hidden, I think it will be better with the helper always on, thank you

![2020-08-14-08-20-25](https://user-images.githubusercontent.com/2283548/90220293-3778f500-de08-11ea-8fb0-21195e40df5d.png)

**Comment by gjsjohnmurray** [comment]
Set `"scm.alwaysShowRepositories": true`

**Comment by ZiTAL** [comment]
works like a charm, thank you
