### ISSUE TITLE
Can't turn on Settings Sync with Microsoft Account while working with Remote Extensions

### ISSUE THREAD

**Issue by wilhem-meignan** [microsoft/vscode#104628]
Actions
* Click Turn on Settings Sync...
* Click Turn On
* Click sign in & turn on
* Click sign in with Microsoft

Observations
* A browser opens locally and tries to load a URL starting with http://127.0.0.1 but the page does not load.

I suppose the the server is running on the remote computer while the browser is trying to contact the local computer (127.0.0.1). So it does not work.

Notes:
* Opening the page to sign in with Microsoft does work when not in an active remote session.
* Using GitHub instead of Microsoft does work even when in an active remote session.

**Comment by adexios** [comment]
I'm getting a similar issue. It's taking me to localhost when I click "Sign in with Microsoft". It's taking me to localhost.

**Comment by wilhem-meignan** [comment]
Cool! Thanks the fixing that.
