### ISSUE TITLE
Code navigation

### ISSUE THREAD

**Issue by arun9216684797** [microsoft/vscode#104653]
- VSCode Version:1.48.0
- OS Version:Linux 5.5.0

Steps to Reproduce:

1.Define a function in different files.
2.Require(node js) the file in another file,when i try to navigate to that function with holding ctrl + click its not going.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Please a code examples and steps to reproduce this using it

**Comment by arun9216684797** [comment]
1. var shippingModel = require('../models/shipping.model');
2. shippingModel.getV2(request, function (error, data) {
        if (error) {
            return response.status(error.statusCode).send({
                status: false,
                data: error
            });
If i hold ctrl and click on "shippingModel" on line number 2 cursor will go to line one as this is its definition.Similarly when i hold ctrl and click on function "getV2" [thats is defined inside file shipping.model.js] **VS CODE** should open shipping.model.js file and direct to that particular function.
**Note:**Earlier vs code was behaving normally but after updating  node version from 8 to 10 i am getting this issue

**Comment by arun9216684797** [comment]
@mjbvz Any update here???

**Comment by mjbvz** [comment]
I'm not sure how you use your code example.

Please either put together a small GitHub repo showing the problem or a complete code example that shows all the relevant part of your project

**Comment by mjbvz** [comment]
Closing this as not actionable without a small, self-contained code example
