### ISSUE TITLE
Support opening files in external application

### ISSUE THREAD

**Issue by rigtorp** [microsoft/vscode#104678]
- Be able to right click on a file in the file explorer and click "Open in external application", this would invoke `xdg-open` or Windows equivalent on the file.
- Be able to configure certain file types (for example PDFs) to always open in external application.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by quhsi** [comment]
Optimally, there should be two options: one opening the registered default application (if it is not VS Code) and one allowing to select the external application using standard OS dialogs.
