### ISSUE TITLE
Allow settings sync history to be exported

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#104657]
Currently history can be accessed by viewing synced data:

![image](https://user-images.githubusercontent.com/2193314/90254508-b74a9380-ddf7-11ea-86e3-cb7993851156.png)

However @borekb calls out in https://github.com/microsoft/vscode/issues/92357#issuecomment-673952213 that there is no way to export this history. How about we add a new export action to the sync activity views which exports all these files to a folder? Eg. a flat folder with files of the form:

```
<epoch>-settings.json
<epoch>-globalState.json
<epoch>-globalState.json
etc.
```

**Comment by borekb** [comment]
Would be great to have this!

I don't know how the service stores the data but I'd like to suggest that a **Git repo** is considered as an export format – it is a natural and efficient format for versioned data.

**Comment by Tyriar** [comment]
Also note that local backups are on disk (Open Local Backups Folder command), it's just remote that is not. For the local synced data view we could have a button that just runs `Open Local Backups Folder`.

**Comment by sandy081** [comment]
This is supported via `Download Settings Sync Activity` command
