### ISSUE TITLE
SCM repositories view does not remember selection

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#104629]
Testing https://github.com/microsoft/vscode/issues/104151

It looks like everytime I open a workspace, the SCM repo view defaults to selecting all repos:

![image](https://user-images.githubusercontent.com/900690/90226054-b5da9480-de12-11ea-893c-17e5018c0573.png)

**Comment by gjsjohnmurray** [comment]
Already mentioned in the "Bad news" section at https://github.com/microsoft/vscode/issues/104151#issuecomment-672001440, but having this separate issue will ensure it gets dealt with.

**Comment by bpasero** [comment]
I really need this :).

**Comment by bpasero** [comment]
![image](https://media.giphy.com/media/x28cIQSn19Tbi/source.gif)
