### ISSUE TITLE
Is the blank page app icon broken?

### ISSUE THREAD

**Issue by chadlavi** [microsoft/vscode#104607]
Issue Type: <b>Bug</b>

details

What is going on with this:
<img width="1024" alt="Screen Shot 2020-08-13 at 21 53 09" src="https://user-images.githubusercontent.com/7226642/90203882-e210f980-ddaf-11ea-80a6-09ab25ca56fd.png">

VS Code version: VSCodium 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T19:51:58.435Z)
OS version: Darwin x64 20.0.0 - macOS Big Sur beta (20A5343i)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz (8 x 1200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
synthwave-vscode|Rob|0.1.5
rewrap|stk|1.11.1
lorem-ipsum|Tyr|1.2.0
markdown-all-in-one|yzh|3.0.0
vscode-asciiflow2|zen|0.2.0

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by chadlavi** [comment]
@mjbvz no it doesn't, but it is reproducible in latest build of vscodium with extensions disabled.

**Comment by chadlavi** [comment]
Ah jeez I'm sorry, it seems that VSCodium has changed their app logo in general with their latest release, I didn't notice it anywhere but the blank document page previously. Closing this, sheepishly.
