### ISSUE TITLE
Cannot overwrite read only files anymore

### ISSUE THREAD

**Issue by Sumo-MBryant** [microsoft/vscode#104651]
On previous versions of VSCode (1.47) you received a message when attempting to save a file that was marked read only:

![image](https://user-images.githubusercontent.com/7024366/90248259-41165300-de30-11ea-9a6c-b8fac8422fd0.png)

As of 1.48, you receive a different message **_that lacks an overwrite option_**:

![image](https://user-images.githubusercontent.com/7024366/90248435-9a7e8200-de30-11ea-8f4d-ce434ac15c2a.png)

When a file is simply marked as read only, retrying as admin is not an appropriate option and fails to resolve the issue.

Please restore Overwrite functionality as it is very useful for us that use archaic source control systems that rely on making files read only.

- VSCode Version: 1.48.0
- OS Version: Windows 10 (1903)

Steps to Reproduce:

1. Open a file with the read only flag set
2. Make a change to the file
3. Save the file

Does this issue occur on the latest insiders build?: Yes
Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Thanks, a regression we can probably fix for recovery.

**Comment by crysyn** [comment]
Was just about to post this as well. This changed about 3-4 weeks back in VSCode Insiders as well if that time frame helps.

**Comment by isidorn** [comment]
Works great, I have verified the fix on windows with read-only files.

**Comment by CRYPTOBRIGHTBUTTERFLY** [comment]
I just went on my Twitter and the same picture was on my profile filling me with no friends and no tweets I report and blocked
