### ISSUE TITLE
"Always show repositories" with multiple repositories

### ISSUE THREAD

**Issue by arshia11d** [microsoft/vscode#104749]
### Client details
Version: 1.48.0 (user setup)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

### Steps to reproduce
- Open a a folder/workspace with **several active repositories**
- Activate/Deactivate the settings "SCM: Always Show Repositories" (`scm.alwaysShowRepositories`). Nothing happens.

### What should have happened?
If this is supposed to be the old repository view, it should generate one pane view per repository, as I vaguely remember from older versions of VS Code!

### Does this issue occur when all extensions are disabled?
Yes

**Comment by gjsjohnmurray** [comment]
No, that setting only makes a difference in the single-repository case.

Changes to improve handling of multiple repositories are covered by #104151 and are already available in Insiders.

**Comment by isidorn** [comment]
Closing as designed.
