### ISSUE TITLE
PS1 wrap in Integrated Terminal

### ISSUE THREAD

**Issue by marsqing** [Microsoft/vscode#10477]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Open Integrated Terminal
2. cd to a directory with "-" in name
3. bash's PS1 will wrap to newline at "-"
<img width="276" alt="screen shot 2016-08-12 at 22 33 19" src="https://cloud.githubusercontent.com/assets/71290/17625790/e8cbd41a-60dc-11e6-855a-2b90480d2770.png">

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
