### ISSUE TITLE
SCM: Support workspace diff navigation

### ISSUE THREAD

**Issue by yittg** [microsoft/vscode#104768]
For now, when we are comparing two files(contents), we can move to the previous/next change via the toolbar or shortcut. And it will automatically move to the first/last change if it touch the end/start.

When we are reviewing a change which usually consists of multiple files, it would be better to move to the next/previous file  if it touch the end/start.

Maybe we can submit multiple diff pairs to the `vscode.diff` command, or wrap them with a new command, like `vscode.multidiff`.

**Comment by joaomoreno** [comment]
Dupe: https://github.com/microsoft/vscode/issues/24389

Related: https://github.com/microsoft/vscode/issues/24916
