### ISSUE TITLE
Tracking of the modifications is broken

### ISSUE THREAD

**Issue by IperStan** [microsoft/vscode#104786]
Issue Type: <b>Bug</b>

Hi,
with the new release 1.48.0 I lost the feature of tracking my changes in the code.
I believe the screenshots are self explanatory

IT ONLY happens with SVN repository. I tried with a git-like repo and it seems working as usual.
I have to downgrade back to the 1.47.3.

VSCode 1.47.3
![IssueVSCodeVCSPanel](https://user-images.githubusercontent.com/43338672/90369951-db62da80-e06c-11ea-93ea-222b851ad253.jpg)

VSCode 1.48.0
![IssueNewVSCodeVCSPanel](https://user-images.githubusercontent.com/43338672/90369899-c8e8a100-e06c-11ea-92fa-64b793803a7e.jpg)

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
alignment|ann|0.3.0
bracket-pair-colorizer|Coe|1.0.61
indent4to2|Com|0.1.2
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
gitlens|eam|10.2.2
tortoise-svn|fan|0.1.1
auto-close-tag|for|0.5.8
beautify|Hoo|1.5.0
svn-scm|joh|2.12.3
vscode-cflint|Kam|0.3.4
vscode-cfml|Kam|0.5.3
eml|lei|0.4.0
HTMLHint|mka|0.8.0
vscode-filesize|mkx|2.1.4
prettify-json|moh|0.0.3
sublime-keybindings|ms-|4.0.7
color-highlight|nau|2.3.0
vetur|oct|0.26.1
vscode-yaml|red|0.9.1
sass-indented|rob|1.5.1
vscode-paste-and-indent|Rub|0.0.8
vscode-sql-beautify|sen|0.0.4
open-in-browser|tec|2.0.0
vscode-icons|vsc|10.2.0
markdown-all-in-one|yzh|3.2.0

</details>

**Comment by davestevens** [comment]
Having the same issue with the Perforce plugin, looks likes its related to 003a3678c879ee5e9a72ad9e5088d89672d75bd8

**Comment by IperStan** [comment]
With the new version 1.48.2 my issue seem to disappear. So far everything looks normal

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/104640

**Comment by intafon** [comment]
Still seeing this issue with git in version 1.48.2 for mac.

**Comment by IperStan** [comment]
> Still seeing this issue with git in version 1.48.2 for mac. Running with --disable-extensions still shows this issue.

Make sure you updated the SVN extension
![image](https://user-images.githubusercontent.com/43338672/91863869-dbb7c400-ec6f-11ea-8bda-5622b4b4fbdb.png)
