### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by Thura-Naing** [microsoft/vscode#104799]
Issue Type: <b>Feature Request</b>

can't down to next line

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041

**Comment by isidorn** [comment]
Pleae file issue with steps. This does not have enough information for us to reproduce

**Comment by Thura-Naing** [comment]
[cid:image007.png@01D67A3E.FBCAC7E0][cid:image008.png@01D67A3E.FBCAC7E0][cid:image009.png@01D67A3E.FBCAC7E0]
Please, check that screen shot. There are abnormal.
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Thura-Naing** [comment]
Thanks for your patience.
I’m make disable all extensions, then all errors not shown. But setting.py is not import os and base_dir path is different of standard setting.py file. It’s happen in Django 3.1?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
