### ISSUE TITLE
Issue #50408 should probably be reopened

### ISSUE THREAD

**Issue by richardeschloss** [microsoft/vscode#104733]
Please re-open #50408, since that's where the issue was tracked and it will be easier to continue the discussion there. This refers to the files.watcherExclude not being respected. It appears from the warnings that node_modules is being watched when it shouldn't, and that's the root of the issue. My opinion is that while the following steps documented [here](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc) can alleviate the problem, it's clearly more of a workaround than the proper solution. 

- VSCode Version: 
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
The OP of that issue closed it and opened #50417 under a different id. That one got closed after no response to a request by @bpasero for more info. It was subsequently locked automatically.

**Comment by richardeschloss** [comment]
Ok, I think that one may need to be re-opened, but to give the vscode the benefit of the doubt, I still will troubleshoot on my end to see if I can provide better details. This issue is reproducible running a project on the Nuxt framework (running their dev script "nuxt"). I only observe the issue after running "nuxt" when vs code is open (even with extensions disabled, and node_modules excluded). It's possible other Nuxt users have faced this issue and may have found a solution that works for them, so I'll check with them too.
