### ISSUE TITLE
Disable spelling suggestion code action

### ISSUE THREAD

**Issue by pgsandstrom** [microsoft/vscode#104718]
When I want to use the "import" code action, I almost always get a irrelevant spelling suggestion as my first suggestion. I wish I could disable this spelling suggestion.

I do not have a spelling extension installed. It is present even when I disable all extensions. So if a extension is causing this, it must be a built in one.

![annoying](https://user-images.githubusercontent.com/1449130/90314844-14893680-df17-11ea-8986-7f50cd9e18da.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Looks more like some spellchecker extension and not built-in TS.

**Comment by pgsandstrom** [comment]
It is present when I disable all extensions. It started showing up a few months ago when I updated to the latest vscode version. Unfortunately I dont remember exactly what version that was.

My current version:
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

But the issue also appears on my work computer, which runs osx.

**Comment by pgsandstrom** [comment]
I have also searched through my entire settings json to find anything spelling related, I have found nothing.

**Comment by pgsandstrom** [comment]
I just realized it must come from the typescript service. It doesn't come directly from vscode. I'll see if I can solve it by configuring typescript somehow.
