### ISSUE TITLE
[quick fix] context menu stuck using Ctrl + . command.

### ISSUE THREAD

**Issue by mrunixus** [Microsoft/vscode#10479]
- VSCode Version: 1.4.0
- OS Version: Windows 7

Steps to Reproduce:
Ctrl + .  command, to import a namespace in C#

1.  make the method async
2.  the context method got stuck
![capture](https://cloud.githubusercontent.com/assets/1231598/17628260/9beb6e1c-6082-11e6-8be5-b60c313793b6.PNG)

**Comment by jrieken** [comment]
@mrunixus Can you check if there is an error in the developer console (F1 > Toggle Developer Tools)

**Comment by mrunixus** [comment]
Good afternoon @jrieken , here it's the error in the developer console.

[consoleOutput.txt](https://github.com/Microsoft/vscode/files/418565/consoleOutput.txt)

Thanks, Pedro Morales.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#664

**Comment by alexandrudima** [comment]
@aeschli Created Omnisharp/omnisharp-vscode#663 for the omnisharp folks to investigate the exception stack trace. I would give this to you to please check that the quick fix menu does not stay open indefinitely when a command is "broken".

**Comment by aeschli** [comment]
To verify one needs to create a quick fix that has command that crashes. I'll work on one.

**Comment by aeschli** [comment]
Verified.
