### ISSUE TITLE
Typescript and Javascript Language Features Unresponsive

### ISSUE THREAD

**Issue by PocketNachos** [microsoft/vscode#104728]
Issue Type: <b>Bug</b>

It is subtitled as a performance issue.

Activation: 7661ms
Profile: 311.00ms

Everything else starts up in 11ms or less. This is the one build in extension that makes my startup times longer than 15 seconds. 

VS Code version: Code - Insiders 1.49.0-insider (bd08768fd310d34cdd4423a53e5f3ca77340fea5, 2020-08-14T05:56:40.601Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (10.50GB free)|
|Process Argv|--crash-reporter-id 7df2a94c-bb03-4b44-b11c-c5550c3d8d0a|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Can you please collect a profile of this. See [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues)

**Comment by mjbvz** [comment]
@jrieken Any advice on how a user can easily profile the startup of an extension?

**Comment by jrieken** [comment]
* F1 > Show Running Extensions
* Select "Start Extension Host Profile" in editor toolbar
* (trigger TS activation, e.g open a file)
* Stop profiling (see status bar), save and share the profile with us

**Comment by mjbvz** [comment]
Closing as we need a profile to investigate this. @PocketNachos If you are still seeing this issue, please follow @jrieken's instructions to try collecting the profile.

To trigger the TS activation, start VS Code with all JavaScript and TypeScript files closed and then open any js/ts file
