### ISSUE TITLE
Move editor actions into the window title to free up space

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#104738]
with [https://code.visualstudio.com/api/references/vscode-api#StatusBarItem](https://code.visualstudio.com/api/references/vscode-api#StatusBarItem) 
there are to many statusbar item  to be added by extensions. it is too many to show those tabs, even hard to select one tab. 
 catastrophic extrusion of tabs.
I think, the statusbarItem is good idea, but it is also a bug of designe of interact-surface.
title bar is another good layout to place those statusbaritems in stead of tabs collectiion.
![image](https://user-images.githubusercontent.com/1876302/90325496-e5be9f00-dfae-11ea-82f5-f5d04bade1d6.png)

just like vs
![image](https://user-images.githubusercontent.com/1876302/90325687-48189f00-dfb1-11ea-8ee6-bd338b8eebf8.png)

**Comment by gjsjohnmurray** [comment]
I think your screenshot shows extension contributions to the `editor/title` menu, not StatusBarItems

https://code.visualstudio.com/api/references/contribution-points#contributes.menus

**Comment by gjsjohnmurray** [comment]
Related to #46403 but the suggestion to use the window title looks new.

**Comment by heartacker** [comment]
> Related to #46403 but the suggestion to use the window title looks new.

 thx, but I don't wanna hide them, they are useful,  just want to move to another position for better experience. 
I believe  title bar is an better place to layout

**Comment by gjsjohnmurray** [comment]
Understood. That is why I didn't tag this as a duplicate. Might be a challenge to get what you want on all platforms though.

**Comment by ronjouch** [comment]
👎 for me, I don't even _have_ a title bar.

**Comment by heartacker** [comment]
> 👎 for me, I don't even _have_ a title bar.
> 
> I stand by my suggestion at [#46403 (comment)](https://github.com/microsoft/vscode/issues/46403#issuecomment-472642154) :
> 
> > To an eventual implementer for this feature request: Firefox's "Overflow Menu" seems like a UX good inspiration. See how a contextual action lets users choose which addons deserve an icon in the bar (the most commonly used, to the user taste), and which should remain "pinned" in the Overflow Menu (the uncommonly-used ones).
> > It's usable, obvious, and for minimalists it would limit icon creep to a single "Overflow Menu" icon, which IMHO is reasonable:
> > ![firefox-overflow-menu](https://user-images.githubusercontent.com/522085/54320595-e25a0380-45c3-11e9-81a1-18454b4c40a1.gif)

thanks for your `-1`👎. and also  appreciate your insistence and minimalists. 
but I think you're misunderstand the meaning of action-icon. action-icon provide an efficient short uct related to activited file for user  to perform a quick action. Although it is efficient,but it took up too much TAB space at the same time. for you minimalists, moving to title-bar has no impact with ` I don't even _have_ a title bar` since you want hide them. 
My point of view, we need to keep its High efficiency, and also need to fix the extrusion. so we can move to another position. in fact, I don't care about where it is moved, Such as title bar or bottom of current document.

Your point of view is only for your minimalism, and don't forget that there are many people who need efficient coding rather than minimalism. What we're going to do is for both.

**Comment by ronjouch** [comment]
> I think you're misunderstand the meaning of action-icon. action-icon provide an efficient short uct related to activited file for user to perform a quick action. Although it is efficient,but it took up too much TAB space at the same time. for you minimalists, moving to title-bar has no impact with ` I don't even _have_ a title bar` since you want hide them.
> My point of view, we need to keep its High efficiency, and also need to fix the extrusion. so we can move to another position. in fact, I don't care about where it is moved, Such as title bar or bottom of current document.
> 
> Your point of view is only for your minimalism, and don't forget that there are many people who need efficient coding rather than minimalism. What we're going to do is for both.

@heartacker your characterization of the problem as Minimalists vs. The Rest Of The World misses one point: I *do* use these actions too, so it's not true that *"moving to title-bar has no impact"*.

Some of these actions are useful to me, some of them are not, and I'd like to hide the latter, put them "in the drawer". Contrarily, the solution you offer would suck for me, as it would make *all of them* completely invisible/unusable to me, including the ones I *do* use!

The "Overflow Menu" UX I suggest stealing from Firefox is great, because:

1. It enables me to decide what is allowed to consume precious bar space.
2. Items I use frequently can be kept out of the drawer...
3. ... and even what is used not-so-frequently remains only one Overflow Menu click away.
4. For minimalists, the bar space cost is minimal: one single icon.

**Comment by caelwithcats** [comment]
The problem with this is the linux version of vs code doesn't have the custom titlebar like windows. 
![](https://imgur.com/zNRVkzU.png)
