### ISSUE TITLE
The debugger doesn't work properly in versions > 46

### ISSUE THREAD

**Issue by irtaza-ebryx** [microsoft/vscode#104781]
Issue Type: <b>Bug</b>

- Set a breakpoint
- Keep the file with the breakpoint open
- Start debugger on a NodeJS project
- The breakpoint dissappears.
- When the breakpoint is hit, the same file is opened with the debugger stopped at the breakpoint. And in this file the breakpoint is also visible.

P.S. In versions <= 47.2 debugging wasn't working at all. The behavior above is for versions >= 47.3.

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:08.304Z)
OS version: Linux x64 4.15.0-112-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
|Screen Reader|no|
|DESKTOP_SESSION|ubuntu|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.2
gc-excelviewer|Gra|3.0.39
easy-icons|jam|0.3.1
dotenv|mik|1.0.1
graphql|mqu|0.1.2
vscode-docker|ms-|1.4.1
python|ms-|2020.7.96456
prisma|Pri|2.3.0
nunjucks|ron|0.3.0
code-settings-sync|Sha|3.4.3
octave|toa|0.0.3
pdf|tom|1.1.0

</details>

**Comment by connor4312** [comment]
Please collect a trace log using the following instructions:

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

/needsMoreInfo

**Comment by altair-jan** [comment]
Guys, I see the same issue. This started happening after the latest update. Please fix it and really annoying and making unusable. I have to put debugger in the code to actually hit the breakpoint.

**Comment by altair-jan** [comment]
@connor4312  - I have emailed the log, please do the needful.

**Comment by connor4312** [comment]
In the log you sent, it doesn't look like you hit a breakpoint at all. Can you send a log where you do this?

The most common cause of this problem is using Node 8 (which is end of life as of 2020) and the best solution to the problem is to update to a most recent version if possible. A complete log file will determine whether this is happening for you.

**Comment by altair-jan** [comment]
That is the issue where when I set a breakpoint, it says its unbound and doesn’t hit.

**Comment by connor4312** [comment]
Okay. What version of Node are you using, and how are you launching the program you're trying to attach to?

**Comment by irtaza-ebryx** [comment]
I was running node version 8, tried version 10 and 12 using `runtimeVersion` option in `launch.json`, and it worked for me. Thanks.
