### ISSUE TITLE
Exits very often

### ISSUE THREAD

**Issue by mohanrajanna15** [microsoft/vscode#104752]
Issue Type: <b>Bug</b>

When I am working , vscode exits very often

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
gitlens|eam|9.9.1
vscode-sshfs|Kel|1.16.3
vscode-docker|ms-|0.7.0
python|ms-|2019.6.24221
debugger-for-chrome|msj|4.12.4
java|red|0.46.0
yang-vscode|typ|2.0.3

</details>

**Comment by gjsjohnmurray** [comment]
Your version is sixteen months out of date. Please start by updating to the current release, 1.48.
