### ISSUE TITLE
Cannot start WAMP server from terminal

### ISSUE THREAD

**Issue by crnogaj** [Microsoft/vscode#10476]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:
1. Use powershell in terminal
2. Open wampmanager.exe directly or as alias

I use powershell in terminal and I have WAMP alias set in my _Microsoft.Powershell_profile.ps1_
`new-item alias:wamp -value C:\wamp\wampmanager.exe`
When I start it with `wamp` or directly with `C:\wamp\wampmanager.exe` my WAMP server starts but with all services inactive (red icon) and I can't activate them.

But it works when I use it directly in powershell. Why is that?

**Comment by Tyriar** [comment]
Could this be to do with running 32 bit powershell which is the default? You can see if this works using the 64 bit one here https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration

**Comment by JakobCrnogaj** [comment]
Thanks but still no changes when I do:

`"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"`

My WAMP is 64bit version if that means something to you.

**Comment by Tyriar** [comment]
@daviwil any ideas on this one?

**Comment by daviwil** [comment]
Hmmm...  Not sure why it'd still be having trouble if you're running 64-bit PowerShell.  Does wampserver have any log output you could check to see why the services aren't starting?  I've never used it before so I'm not familiar at all.

**Comment by JakobCrnogaj** [comment]
When I start it with integrated terminal wamp doesn't write any logs (there are 4 types of logs in it: access, mysql, php and apache).

With normal powershell it writes this in apache log:

```
[Fri Aug 12 20:57:43.543328 2016] [auth_digest:notice] [pid 2536:tid 876] AH01757: generating secret for digest authentication ...
[Fri Aug 12 20:57:43.652709 2016] [mpm_winnt:notice] [pid 2536:tid 876] AH00455: Apache/2.4.17 (Win64) PHP/5.6.16 configured -- resuming normal operations
[Fri Aug 12 20:57:43.652709 2016] [mpm_winnt:notice] [pid 2536:tid 876] AH00456: Apache Lounge VC14 Server built: Oct 11 2015 11:49:07
[Fri Aug 12 20:57:43.652709 2016] [core:notice] [pid 2536:tid 876] AH00094: Command line: 'C:\\wamp\\bin\\apache\\apache2.4.17\\bin\\httpd.exe -d C:/wamp/bin/apache/apache2.4.17'
[Fri Aug 12 20:57:43.652709 2016] [mpm_winnt:notice] [pid 2536:tid 876] AH00418: Parent: Created child process 7820
[Fri Aug 12 20:57:44.934025 2016] [auth_digest:notice] [pid 7820:tid 792] AH01757: generating secret for digest authentication ...
[Fri Aug 12 20:57:45.043407 2016] [mpm_winnt:notice] [pid 7820:tid 792] AH00354: Child: Starting 64 worker threads.
```

When I check state of services (wamp function) after starting it in terminal then it returns this:

![12-08-2016_21-12-04](https://cloud.githubusercontent.com/assets/12704451/17634173/941c3348-60d1-11e6-95d7-fa50c1c37841.png)

Normally it returns that all 3 services are started, when starting it outside integrated terminal.

**Comment by Tyriar** [comment]
If you have any more info on why this is failing, please let us know.
