### ISSUE TITLE
platform io not in market place

### ISSUE THREAD

**Issue by lubello** [microsoft/vscode#104725]
Issue Type: <b>Bug</b>

click extension and writr 'platform' , no  platform io in list

VS Code version: VSCodium 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-14T10:39:08.568Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.98GB (0.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.30.0-insiders2
color-highlight|nau|2.3.0
vscodeintellicode|Vis|1.2.9

</details>

**Comment by tamuratak** [comment]
That is because you are using VSCodium.

See open-vsx/publish-extensions/issues/86
