### ISSUE TITLE
Allow window to close and keep unsaved files

### ISSUE THREAD

**Issue by renannprado** [microsoft/vscode#104716]
I usually open many vscode editors at the same in different folders/repositories. Each instance of the vscode has its set of `unsaved` files 'cause these, as I understand, exist in the scope of the each folder so to say. 
However when you have many instances opened and you want to close only one, there's no option (see screenshot) to allow closing only one instance while keeping the files in the `unsaved` mode. I either have to save them, discard or just keep the instance open. The only way to do what I want today is basically by using `CRTL+Q` to close all instances and then vscode won't cask me if I want to saved these files.

![image](https://user-images.githubusercontent.com/2359543/90314700-f3741600-df15-11ea-862e-6539e5c2a181.png)

So feature would basically having a fourth button at this point which would allow me to close the instance/window anyway while keeping those unsaved files.

**Comment by IllusionMH** [comment]
@renannprado have you checked **Files: Hot Exit** setting?
Setting it to `"files.hotExit": "onExitAndWindowClose"` don't show prompt and preserves unsaved files

**Comment by renannprado** [comment]
Didn't know about that one :smile:.

It works! Thanks!
