### ISSUE TITLE
yarn watchd starts twice for me

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#104782]
- OS Version: macOS

Steps to Reproduce:

1. run `yarn watchd` from the command line outside VSCode
2. run web selfhost bits
3. hit `Cmd+Shift+B` inside web selfhost

=> 🐛 you can see another `yarn watchd` starting, not connecting to the first

I think this used to work before.

//cc @alexr00 for tasks

**Comment by joaomoreno** [comment]
The scope is the cwd. Is the cwd exactly the same?

**Comment by joaomoreno** [comment]
Oh. This has changed since I made core and extensions each run on its own process which improved the build times.

When running Ctrl Shift B, you get both `yarn watch-clientd` and `yarn watch-extensionsd`, not `yarn watchd`.

**Comment by bpasero** [comment]
Yes, that explains it.
