### ISSUE TITLE
extendMarkdownIt not work in notebook 

### ISSUE THREAD

**Issue by eightHundreds** [microsoft/vscode#104723]
- VSCode Version:
- OS Version:

https://github.com/microsoft/vscode-markdown-notebook/issues/3#issue-670740495

How to customize the rendering of markdown in notebook?

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Closing as upstream issue for vscode-markdown-notebook. The standard notebook functionality uses marked instead of markdown-it
