### ISSUE TITLE
[v1.48] Cannot authenticate proxies

### ISSUE THREAD

**Issue by Dan503** [microsoft/vscode#104766]
Bug #97199 has returned in v1.48

**Comment by marco-cc** [comment]
Reference to v1.45 fix
https://github.com/microsoft/vscode/commit/5a42c9f62775252878fc22f11ed8affcfeb74fab

compare to v1.48 proxy/auth.html
In meta data header, 'script-src' attribute miss 'unsafe-inline' value again

**Comment by ota-meshi** [comment]
Duplicate of #104603

**Comment by Dan503** [comment]
Ok yep. Closing in favour of #104603
