### ISSUE TITLE
Wrong highlighting of shell files

### ISSUE THREAD

**Issue by Kreyren** [microsoft/vscode#104707]
**NOTICE: This is an issue transfer from https://github.com/VSCodium/vscodium/issues/467**

### Describe the bug

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
 - I don't use vscode -> Unable to test
 - Confirmed by https://github.com/VSCodium/vscodium/issues/467#issuecomment-666695065

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

### To Reproduce
1. Open shell file that contains

```sh
#!/bin/sh

# shellcheck shell=sh # Written to be posix-compatible

MAINTAINER_REPOSITORY="something"

cat <<-EOF > /etc/apt/sources.list
	# WARNING-DO_NOT_EDIT(Krey): This file is auto-maintained by $MAINTAINER_REPOSITORY
	deb [arch=amd64,i386] tor+http://devuanfwojg73k6r.onion/merged chimaera main contrib non-free
	deb-src [arch=amd64,i386] tor+http://devuanfwojg73k6r.onion/merged chimaera main contrib non-free
EOF
```

2. Notice that '$MAINTAINER_REPOSITORY' is not properly highlighted (expecting same color as other variables)

![image](https://user-images.githubusercontent.com/11302521/88963955-e9f97580-d2a8-11ea-8943-71d4496bd258.png)

**Expected behavior**

Expecting variables `\$[a-zA-Z_{}]+` within [heredoc](https://en.wikipedia.org/wiki/Here_document) to be highlighed as variables since they will be expanded on runtime

```console
kreyren@leonid:~$ someVar="hello"
kreyren@leonid:~$ cat <<-EOF
> $someVar
> EOF
hello
```

**Desktop (please complete the following information):**
 - **OS**: Kreyrock GNU/FrankenLinux (Custom Linux From Scratch using sandbox for other kernels and distributions, observed on devuan/chimaera sandbox)
 - **Architecture**: amd64
 - **Version**: 9999-Anubis

**Comment by smilegodly** [comment]
I would like to help with this issue if that is alright.

**Comment by alexr00** [comment]
We do not support VSCodium. If the issue occurs in VS Code then I would be happy to investigate.
