### ISSUE TITLE
Trusted notebook outputs

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#104787]
There are notebooks that allow to run arbitrary code (JS, SVG) as their output and we should let users know about that.  Currently such a notification/prompt is implemented by the python extension but it should be part of the core. Maybe something similar as [`MarkdownString#isTrusted?: boolean;`](https://github.com/microsoft/vscode/blob/6445a9633d428e0879d172d4f392c542ba887768/src/vs/vscode.d.ts#L2465) would be enough. E.g the `NotebookData`-type could have a similar flag saying that this notebook does/will contain arbitrary code (that's code written by users, not extension authors)

**Comment by jrieken** [comment]
related (second part) https://github.com/microsoft/vscode/issues/103713#issuecomment-673567826

**Comment by rebornix** [comment]
This is now covered by the trust workspace story.
