### ISSUE TITLE
 Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#10473]
Issue Id: <b>b772371c-e100-d7e4-9d4b-f77381ec98cf</b><br /><br />*Versions* <br />- 1.3.1<br />-  e724f269ded347b49fcf1657fc576399354e6703<br />-  93e65224d7598017bfa0b188a0d82b66a2ee9698<br />-  9f2c1b7ddfdc631198e9b541072489af78b7cade<br />-  0aa920603e48ad2333722d9ee97257e40ea24d12<br />-  f4780e67933164a2289b86f2c279aaa05fda672f<br />-  01a3f868552dc8011adf4e79bee8cfb09babfe31<br />-  89c428f438fd50b96ca36aa7e1b499e9af18134e<br />-  4656fe3ff2952e9538d81e7a7571674352e5d62f<br />-  6ef86d5f85a531caa59bfb1715469fcfaa8d2efd<br />-  825a1e71a436007d88796cb1cf0bad85ad534e53<br />-  e3758d2cdaae78082a08a45ae28ea1bed5f47e8c<br />-  1a7ca5a77bf6b63951e499ea93b7316d36118ade<br />-  6276dcb0ae497766056b4c09ea75be1d76a8b679<br />-  dde41be0231d6f8397d1da969ddab351f137b833<br />-  fc167f86c1aee27951b7d4b4db51229f62d0a0ad<br />-  4c0676ab472a92f5269ac4995cdc81db8bc94896<br />-  a1293f5056e79c3f0e2cd3e24909f41ff4eef472<br />-  a21c12346f388e51858c930875ca30968604c116<br />-  f6227ca157caed3ce3224ad9f760a8d5c8ed0e4d<br />-  0c5f6e8867fb117b6fa41cc647dc650bb9856dc4<br />-  50a0945d8de129472b154fa514ba5328897d3be1<br />-  4d0b2f5f15bf7011d3a99888763a7b46a5953d95<br />-  9c4890399293ee5c87c4f7bfb5405d120ea650c6<br />-  798b41ab1cf3636a27042020a54ddfb4cfb8d23c<br />-  d0c2b891903d73e83dcdc7786398ebfa764fc4ee<br />-  4b84f6d791203e71fee10537f27fc8add9357160<br />-  a2b9738a942237b59cb920940b93a0206f1b61d0<br />-  0421a3492317a4ca1adaa7f3513391d312cb10c3<br />-  583f439c1d49128a4775c1ba5a1ac8c6ddd63d5f<br />-  531a56f772fc33ec88910328b88f4dbd7ae5df43<br />-  a6aa32032dc559aa88cf0f4a9d77ef5d8c3d89c1<br />-  d808ba31a697998f36c9c2cbdfc5f8d8e8b16ca2<br />-  3abddec3580ab09c11c7f7cc5a2954908b9a4522<br />-  5eaf9f05038b0a9818ebff510e1aafe07ac1ae68<br />-  716f76458e4dc93e865b6a999e437ed45774744e<br />-  b985edc9f5441678cf071fc7925a569e623e7431<br />-  06d85431730fe33beff7c56b5ef6f4514ad326ba<br />-  3313a641ec505098c8625c459e49af3e8f5eb793<br />-  13b6e6d096c479f4174d025d647385054b1e43d7<br />-  666ed83a2d465257201cdac215a553ddee3cccbe<br />-  ce3c8642a9b11de40abd8d18133926e9a4dbeffc<br />-  2dc1d5157a5f5cf3bed1b35df2fa304805d46cc9<br />-  5d1affed4b860a0dd6a1504ed6d767fcd2d67d1d<br />-  616201eff8f8d8de02edd2b9b18eae3b1096fb53<br />-  8a4bdea8b17fb0030aa1eec83404edef13f38e6e<br />*Stack* <br />TypeError: Cannot read property 'match' of undefined<br />    at e.renderElement (<br />    at e.renderElement (<br />    at e.renderElement (<br />    at e.insertItemInDOM (<br />    at <br />    at Object.r [as each] (<br />    at e.splice (<br />    at <br />    at e.bufferEvents (<br />    at e.splice (<br />

**Comment by bpasero** [comment]
@joaomoreno looks like coming from https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L93

Has many many hits.

**Comment by joaomoreno** [comment]
@aeschli:

```typescript
suggestion.documentationLabel.match(colorRegExp) 
```

**Comment by jcity** [comment]
@aeschli I'm on the latest version (1.5.2) and I'm still getting this error upon saving a typescript file.

Happy to provide more info if you can let me know where to find something thats useful for you.

**Comment by aeschli** [comment]
This issue is not related to saving a typescript file. Please file a separate issue.
