### ISSUE TITLE
initialize Repository has no response

### ISSUE THREAD

**Issue by jianboy** [microsoft/vscode#104763]
Issue Type: <b>Bug</b>

initialize Repository has  no response.
![2](https://user-images.githubusercontent.com/11532015/90341919-6aa0cb80-e036-11ea-8cef-27e986929df5.gif)

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.55GB free)|
|Process Argv|E:\downloads\php|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
git-project-manager|fel|1.7.1
vscode-drawio|hed|0.7.2
vscode-docker|ms-|1.4.1
remote-containers|ms-|0.134.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0

</details>

**Comment by gjsjohnmurray** [comment]
Does the same happen if you first run the Command Palette command to reload with all extensions disabled?

If yes, please go to the Terminal tab and run this command:

```git --version```

What does this return?

**Comment by jianboy** [comment]
> Does the same happen if you first run the Command Palette command to reload with all extensions disabled?
> 
> If yes, please go to the Terminal tab and run this command:
> 
> `git --version`
> **git version 2.16.2.windows.1**
> What does this return?

cmd Terminal  is ok. I click "initialize repository" button, it has no reponse. **but It has created a git repo.** 

![3](https://user-images.githubusercontent.com/11532015/90343398-9924a380-e042-11ea-9fc0-17636227c36b.gif)

I everytime must restart vscode. then it can recognition the git repo.

**Comment by joaomoreno** [comment]
You seem to be missing file events. Please go through the following steps:

1. Run `Git: Set Log Level...` and choose `Trace`
2. Run `Git: Show Git Output`
3. Reproduce the issue and wait 10-20 seconds
4. Paste the whole output here
