### ISSUE TITLE
[Setting Sync] can't accept merge if difference is last empty line when manually merge local with remote

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#104748]
Version info:

```
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Steps to Reproduce:

![screenshot_2020-08-16_17-40-31](https://user-images.githubusercontent.com/41773861/90331510-99dc1c00-dfe7-11ea-9968-cc69ec6179b7.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes!

**Comment by arshia11d** [comment]
I was just having this issue.

What I did was to go to VSCode Insiders which synced that file in the first place and override the file slightly and sync it again.
Then when I went back to VSCode, it could go through merging and initiating the Sync functionality.

That would be a temporary fix until it is fixed.

**Comment by sandy081** [comment]
/duplicate

#104626
