### ISSUE TITLE
Can no longer set breakpoints via the gutter in any editor group other than 1

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#104773]
Open a file (or files) in 2 editor groups, you can set a breakpoint in the left file (first group), but can't set a breakpoint in any other group via the gutter. And even if you use the shortcut (F9), it will set the BP, but it won't show in any editor group other than the first.

Started in a very recent insiders build.

**Comment by isidorn** [comment]
Thanks for filling this. I have done some refactoring here which are probably to blame.
