### ISSUE TITLE
Terminal input not  passed to python in vscode >= 1.47.1

### ISSUE THREAD

**Issue by jaydeedub** [microsoft/vscode#104765]
I also commented at issue 104753 thinking it may be related (sorry, I hadn't read the guidelines re: similar, but different issue)
The issue is that when debugging a Python program which uses the input() method, execution hangs at the input() statement. as simple as:
```python
while True:
    x = input("Input something (q to quit): ")
    if x == 'q':
        break
    print(x)
```
Execution does not contnue past the input statement. After I use the Code "Stop" button, the shell in the terminal complains:
bash: q: command not found
Indicating that the input is in a buffer, but it gets passed to the shell,
This is code=1.47.0-1594283939 amd64 on Debian Buster.

**Comment by denialmx** [comment]
I'm also experiencing the same problem.
all my Inputs while debugging now go to the shell instead of the variable. Debugger hangs. I am using this on Windows connecting to Remote SSH on an Ubuntu 16.04

**Comment by LimeInkling** [comment]
I am also experiencing this issue on 1.48. I am using the OSS build on Arch Linux (the one in the repos).
