### ISSUE TITLE
Source Control View

### ISSUE THREAD

**Issue by MichelleStreeter** [microsoft/vscode#104717]
Issue Type: <b>Feature Request</b>

I really dislike the new Source Control view.  I liked that the edits were put down on the bottom and not in line with the repos.  Putting it inline makes it messy.  And now, the branch name hides the repo name.  So if I have a branch named the same for two repos, I have no idea which repo it is without having to expand the window size until the repo name is reavealed.  Also, I liked seeing how many changes are in a repo.  It brought attention to that repo without all this clutter.   needless to say, I liked the old way before you started messing with it.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-148-generic

**Comment by gjsjohnmurray** [comment]
See #104151 which you can already try out in Insiders.

**Comment by joaomoreno** [comment]
This was tackled with https://github.com/microsoft/vscode/issues/104151
