### ISSUE TITLE
OS X - Terminal process "/bin/{shell} '-c', 'npm run watch'" failed to launch - see also 69547

### ISSUE THREAD

**Issue by ww2406** [microsoft/vscode#104736]
When trying to run a new VS Code extension project on OS X, receive:
`The terminal process "/bin/zsh '-c', 'npm run watch'" failed to launch (exit code: 127).`
Also tested setting the terminal to bash, same result. Appears to be same issue as [69547]( https://github.com/Microsoft/vscode/issues/69547) that was not resolved. Tried running the `npm compile` task as suggested, received the same output.

- VSCode Version: 1.48
- OS Version: OS X 10.15.6

Steps to Reproduce:

1. Use yeoman to generate a new vs code extension project
2. Attempt to run by pressing F5

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Can you share any `terminal.*` and `task.*` settings you have?

**Comment by turnerguo** [comment]
I guess it maybe the OS X 10.15.6 capability issue, since it was running correct yesterday before I was update to 10.15.6, but I got this issue this morning too.  😑

**Comment by ww2406** [comment]
Sure!

terminal:
```
"terminal.integrated.inheritEnv": false,
"terminal.integrated.shell.osx": "/bin/bash"
```
task:
none

**Comment by qiweiwang-hiretual** [comment]
set
`"terminal.integrated.inheritEnv": true`
this work for me

**Comment by pfan8** [comment]
set
"terminal.integrated.inheritEnv": true
this work for me, if you set shell to bash, make sure .bash_profile has node path env

**Comment by alexr00** [comment]
@pfan8 is correct. You will need to set `"terminal.integrated.inheritEnv": true`. Unless you configure specific arguments for your tasks, they always run in a non-login, non-interactive shell, which means that it doesn't know where `npm` is unless you set `"terminal.integrated.inheritEnv":true`.

**Comment by jugalw13** [comment]
I'm still facing this error when developing an extension for vs code 
```The terminal process "/bin/zsh '-c', 'npm run watch'" failed to launch (exit code: 127)```

I've already tried ```"terminal.integrated.inheritEnv":true```.
But the same error still exists
