### ISSUE TITLE
Middle-click on a link doesn't open the link properly

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#104776]
I have muscle memory for middle-clicking on links (to open in a new tab) and it doesn't work in VS Code.

![image](https://user-images.githubusercontent.com/641685/90356818-d8d99400-e01e-11ea-88a7-8d8b4a738016.png)

If I middle-click on the link above, it opens a browser to `file:///C:/Users/Eric/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/workbench.html`

**Comment by bpasero** [comment]
@eamodio are you using VSCode in Electron or Web? Does it work when you click normally and if so what happens then?

**Comment by eamodio** [comment]
This is in Electron (haven't tried on the web). And it works perfectly on a normal click.

**Comment by bpasero** [comment]
OK, making this open for help if someone wants to chime in.

**Comment by jeanp413** [comment]
Created a PR #104885 to fix this

**Comment by bpasero** [comment]
History shows @jrieken as the one introducing the `click` handler but I am not sure who the owner is today.
