### ISSUE TITLE
Wrong order of Nuget package versions

### ISSUE THREAD

**Issue by ORuban** [Microsoft/vscode#10475]
- VSCode Version:  1.4.0
- OS Version: Window 10 Pro

Steps to Reproduce:

1.  Open default ASP.NET Core project
2.  Open project.json file and add "NLogEx" as dependency
3. The following suggestion list will appear:
 
![image](https://cloud.githubusercontent.com/assets/5214320/17623832/bc33eef6-60aa-11e6-9d70-cbe747e9aacd.png)

**Comment by jrieken** [comment]
That's how `localeCompare` works

```
"1.0.2".localeCompare("1.0.10") === 1
```

**Comment by joaomoreno** [comment]
Ugh

**Comment by jrieken** [comment]
Actually, we do allow completion items to set a `sortText` by which we then sort instead of the label. @aeschli Do you happen to know where those completions come from?

**Comment by joaomoreno** [comment]
Yeah... but how would those look like?

**Comment by aeschli** [comment]
The value proposals are created here:
https://github.com/Microsoft/vscode/blob/master/extensions/json/server/src/jsoncontributions/projectJSONContribution.ts#L190

**Comment by aeschli** [comment]
Completion proposals are textual completions and therefor I think the current textual sort order is fine. I would do any tricks here.

**Comment by jrieken** [comment]
That's a point of view but if we decide fix this it should happen inside the json contribution

**Comment by aeschli** [comment]
Won't fix as explained above.
