### ISSUE TITLE
Timeline view disappeared

### ISSUE THREAD

**Issue by msorens** [microsoft/vscode#104700]
Issue Type: <b>Bug</b>

1. Had timeline view with "Git History Enabled".
2. Turned off the "Git History Enabled".
3. The entire Timeline view disappeared. 
Expected Behavior: The Timeline view header bar should remain present and the Timeline view contents should become empty.

4. Restarting VSCode and the Timeline view is still completely gone.
5. Also tried context menu in file explorer to "Open Timeline" but nothing happens.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 9, 10|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
Bookmarks|ale|11.3.1
ng-template|Ang|0.1000.7
vscode-color|ans|0.4.5
better-toml|bun|0.3.2
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.36.3
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.13
code-runner|for|0.11.0
vscode-pull-request-github|Git|0.19.0
sass-lint|gle|1.0.6
vscode-atom-javascript-snippet|glu|0.2.1
go|gol|0.16.1
terraform|has|2.1.1
vscode-test-explorer|hbe|2.19.1
vscode-guid|hea|1.4.20
javascript-unit-test-snippet|iZD|1.0.0
plantuml|jeb|2.13.13
git-tree-compare|let|1.9.2
AWK|lug|0.0.2
HTMLHint|mka|0.8.0
debugger-for-chrome|msj|4.12.9
sqltools|mtx|0.22.11
git-file-history|pom|1.0.1
vscode-css-peek|pra|4.0.0
angular-karma-test-explorer|raa|1.2.5
ruby|reb|0.27.0
vscode-yaml|red|0.9.1
vscode-scss-formatter|sib|2.0.1
code-spell-checker|str|1.9.0
opa|tsa|0.6.1
vim|vsc|1.16.0
quokka-vscode|Wal|1.0.312
wallaby-vscode|Wal|1.0.230
vscode-ruby|win|0.27.0
vscode-proto3|zxh|0.4.2

</details>

**Comment by eamodio** [comment]
@msorens until this gets released, you can remove the `timeline.excludeSources` setting from your user settings, and that should restore the view.
