### ISSUE TITLE
Unable to save files 

### ISSUE THREAD

**Issue by dcapers333** [microsoft/vscode#104755]
Issue Type: <b>Bug</b>

I am unable to open a folder, create a folder, or save any files. When I select these options nothign happens 

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
I suggest you start by updating to the current release (1.48). Yours is five months out of date.

**Comment by isidorn** [comment]
Will just close this and save everyone the trouble.
Please always use latest vscode.
