### ISSUE TITLE
rename action fails, or wrong rename result

### ISSUE THREAD

**Issue by idonov** [microsoft/vscode#104759]
Issue Type: <b>Bug</b>

Have two projects, one server nodejs, rename(f2) works ok.
Angular project rename action fails, or renaming is wrong.
ex. try rename 'var1' to 'var2' results in 'var122'

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.00GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/igord/OneDrive/Desktop/GitRepos/tindrpol/app|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
remote-wsl|ms-|0.44.4
vscode-yaml|red|0.9.1
preview-vscode|sea|2.1.0
vscode-scss-formatter|sib|2.0.1

</details>

**Comment by mjbvz** [comment]
Please provide clear steps to reproduce with example code

**Comment by idonov** [comment]
Did some more testing. the repeatable pattern is:
if I try to add to the name, it gets added doubled. rename 'a' to 'b' results in 'abb'. If I keep trying by just adding to the name, the same result happens always.
if I try to remove from the name, I get this error and no rename:
[https://i.imgur.com/sYixG0s.jpg](url)

**Comment by idonov** [comment]
I also have another similar doubling issue, with find all references:
![image](https://user-images.githubusercontent.com/7294596/90791208-37498f80-e309-11ea-91f7-b5a4ac775c98.png)

**Comment by idonov** [comment]
I have already tried disabling all extensions.

**Comment by idonov** [comment]
This is really weird. copying the folder outside, deleting the original, and moving back the copy fixed my problem in both projects(eventually both the android and server project got affected).

I initially thought creating and saving a workspace file fixed it, not sure still if that had an effect. I did have a workspace file for both projects.

Maybe OneDrive had something to do with it, my folders sit on the desktop and are synced to OneDrive, I often have to pause syncing while debugging to avoid issues with file locks.

**Comment by idonov** [comment]
> I also have another similar doubling issue, with find all references:
> I get each entry reported twice.
> 
> ![image](https://user-images.githubusercontent.com/7294596/90791208-37498f80-e309-11ea-91f7-b5a4ac775c98.png)

The copy/delete procedure did not fix my "find all references problem", but adding a workspace for the folder fixed it.

**Comment by idonov** [comment]
Unfortunately it returns. Not sure about the steps, I tried to reproduce it with a new angular universal app.
Somewhere while debugging while  running ng dev:ssr, stopping at breakpoints in the browser debugger, changing code and auto recompiling it starts to happen again.

Repeating the copy/delete/replace fixes it for a short while, but then it reappears. :(
This was not happening until 2 3 weeks back.

**Comment by mjbvz** [comment]
We can't investigate this without clear steps to reproduce the problem and example code (as text or a GitHub repo) that demonstrates it. Please put those together
