### ISSUE TITLE
win 10 install error

### ISSUE THREAD

**Issue by cuibty** [microsoft/vscode#104702]
- VSCode Version: 1.48.0
- OS Version: Win10 2004 (19041.388)

Steps to Reproduce:

![2020-08-15 120142](https://user-images.githubusercontent.com/12811343/90304920-61591700-deef-11ea-8592-8b6499d17b93.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by cuibty** [comment]
#104545

**Comment by isidorn** [comment]
Closing as duplicate
