### ISSUE TITLE
Sync setting sees my two computers as one

### ISSUE THREAD

**Issue by mrvkino** [microsoft/vscode#104732]
I have two Apple laptop and when I signed in the second machine VSCode Sync Setting sees the two machine as one. I tried renaming each of them to a unique name, but the name is being reflected to each of them. I have tried with the extension disabled and disabling/re-enabling the sync one at a time. But to no avail.

Sync setting sees both of my machine as the same. The insider did not have this issue.

The log show that everything when well. It never shown me a dialog to merge the settings. Could it be because I used [setting sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) to have the same setup, it caused the system to see both my laptop as the same?

- VSCode Version: 1.48.0
- OS Version: MacOS 10.15.6 (19G2021)

Steps to Reproduce:

1. Sync first machine with Github account
2. Sync second machine with Github account
3. Both machine are shown as if there is one machine

Does this issue occur when all extensions are disabled?: Yes

This the name of the second machine (remote) that is shown as if it where my local machine. I had the local (current) one named "Visual Studio Code (MBP-Work)".
<img width="396" alt="image" src="https://user-images.githubusercontent.com/279511/90323238-9172db00-df2c-11ea-94af-9300a684902f.png">

**Comment by lunelson** [comment]
I have the exact same issue, with the same software versions.
1. I activated sync on my work machine, authorized via Github account.
2. I activated sync on my personal machine a day later, authorized via same method. It did not ask me to merge settings, which I thought was strange, so I looked in to settings and discovered only one machine was listed. 
3. Going back to my work machine today, the sync process happened, again seeing only one machine.

**Comment by sandy081** [comment]
Can you please open Settings Sync log and check which service each machine is using. It is logged as first entry.

**Comment by mrvkino** [comment]
On my work machine I have the following in the log:

```log
[2020-08-17 08:04:16.204] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-08-17 08:04:16.204] [userDataSync] [info] Auto Sync is enabled.
[2020-08-17 08:04:16.204] [userDataSync] [info] Auto Sync: Suspended until auth token is available.
[2020-08-17 08:04:33.120] [userDataSync] [info] Auto Sync: Started
[2020-08-17 08:04:33.120] [userDataSync] [info] Auto Sync: Triggered by Interval
```

For my personal machine I recall seeing the same service, but I will check later today when I have access to it.

**Comment by mrvkino** [comment]
On my second computer I have the same service:
```
[2020-08-15 19:17:07.224] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-08-15 19:17:07.224] [userDataSync] [info] Auto Sync is disabled.
[2020-08-15 19:17:36.755] [userDataSync] [info] Did reset the local sync state.
[2020-08-15 19:17:39.801] [userDataSync] [info] Settings: No changes found during synchronizing settings.
```

**Comment by sandy081** [comment]
Weird.

Are you still seeing this issue on the above two machines?

**Comment by mrvkino** [comment]
Yes. I am still seeing one machine. I tried disconnecting and reconnecting, clearing the data on the cloud, but it didn't solve the issue.

Is there a way to reinitialize the whole thing?

Btw: I connected using my GitHub account on both machine, maybe this would help?

**Comment by sandy081** [comment]
To reinitialise, turn off sync completely (enable the check mark to turn off on all devices) and try again?

**Comment by mrvkino** [comment]
I did turn off sync on each machine and select both time the turn off on all device and erase data on the cloud. Still see the same one machine name marked as current on both.

But I saw that the first machine to start a sync with the cloud is the machine who is going to force the name. So if the work machine sync restart the sync to cloud the name will be "Visual Studio Code (MBP-Work)", if my personal machine is the first to sync to the cloud I see "Visual Studio Code (MBP-Perso)" as the name for both.

Is there any test or debug mode I can run to help?

**Comment by sandy081** [comment]
Can you please try following on both machines?

- View -> Command Pallette... -> Toggle Shared Process -> Network
- Look for `/v1/resource/machines/latest` request and see what response it returns

Also try this out after turning off completely and turning on and check the difference.

**Comment by mrvkino** [comment]
Ok, got the response.

**Baseline**
Work Laptop (Visual Studio Code (MBP-Hardent)) response for the `/v1/resource/machines/latest` request:
{"version":1,"machines":[{"id":"b64b74ca-07b9-4cc2-8917-bab8b0672dbf","name":"Visual Studio Code (MBP-Hardent)"}]}

Home laptop (Visual Studio Code (MBP-Perso)) response for the `/v1/resource/machines/latest` request:
{"version":1,"machines":[{"id":"b64b74ca-07b9-4cc2-8917-bab8b0672dbf","name":"Visual Studio Code (MBP-Hardent)"}]}

**Right after reset of sync setting**

This was the first machine to reconnect.
Work laptop (Visual Studio Code (MBP-Hardent)) response for the `/v1/resource/machines/latest` request:
No response data available
After restart of VSCode
{"version":1,"machines":[{"id":"b64b74ca-07b9-4cc2-8917-bab8b0672dbf","name":"Visual Studio Code (MBP-Hardent)"}]}

```
HTTP/1.1 200 OK
Content-Length: 114
Content-Type: application/octet-stream
ETag: 4a527ab9-6553-4405-afc5-d4ea689fd3d2
Vary: Origin
request-context: appId=cid-v1:7314e4bb-c502-4f04-b61f-a0b4ebae90dd
X-Operation-Id: a97461abc9ef44c89d8c0ec0742b7ebe
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: etag
Date: Mon, 31 Aug 2020 12:06:59 GMT
```

Home laptop (Visual Studio Code (MBP-Perso)) response for the `/v1/resource/machines/latest` request (I have 2 request):
1) No response data available
2) {"version":1,"machines":[{"id":"b64b74ca-07b9-4cc2-8917-bab8b0672dbf","name":"Visual Studio Code (MBP-Hardent)"}]}

```
GET /v1/resource/machines/latest HTTP/1.1
Host: vscode-sync.trafficmanager.net
Connection: keep-alive
Cache-Control: no-cache
X-Account-Type: github
X-Machine-Id: b64b74ca-07b9-4cc2-8917-bab8b0672dbf
X-Client-Version: 1.48.2
X-Client-Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
authorization: Bearer a4644050542166d4f7ecbff5e08ba1c352946bed
X-Machine-Session-Id: b1bfe325-1701-460f-af2b-113eeafe59ae
If-None-Match: 803fa0f6-0f14-477a-8749-d410087ec4f0
X-User-Session-Id: 915c3a01-b2e7-4dcb-9dd2-d8d9b9310f36
X-Client-Name: code
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.48.2 Chrome/78.0.3904.130 Electron/7.3.2 Safari/537.36
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
```

Both are using the name "Visual Studio Code (MBP-Hardent)"

**Comment by sandy081** [comment]
Great thanks for sharing info. Not sure if you turned on sync on both machines after resetting? So, please follow these steps and provide more info

From Work Machine:
- Turn off Sync and check the option to turn off on all devices
- Restart VS Code
- View -> Command Pallette... -> Toggle Shared Process -> Network
- Turn on Sync
- Look for all `resource/machines/` requests and share us each request and response info. Check what machine id and name is being posted to server and the response from the server.

Do the same from Home machine and check if this machine is getting the machine data updated by your work machine or not

**Comment by mrvkino** [comment]
I did turn on sync on both machine after resetting. I will do the steps and give you the results asap.

**Comment by mrvkino** [comment]
Here are all the request from both machine following the steps you have listed. I installed on the home machine the docker extension when the work machine was shutdown. When performing the steps above, the docker extension was not added on the work machine. When I uninstalled and reinstalled the extension when both machine were booted with VSCode sync active, the extension installed/uninstalled status was mirrored. The sync still sees one machine with the same name on both as the current machine.

Work Machine

First request:
GET /v1/resource/machines/latest HTTP/1.1
Host: vscode-sync.trafficmanager.net
Connection: keep-alive
X-Machine-Id: b64b74ca-07b9-4cc2-8917-bab8b0672dbf
Cache-Control: no-cache
X-Client-Version: 1.48.2
X-Client-Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
authorization: Bearer 7b312454800909e2e52c7293322356b74ad1d1ae
X-Machine-Session-Id: 183db37a-d259-4fe0-9bd9-670e52e52910
X-Account-Type: github
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.48.2 Chrome/78.0.3904.130 Electron/7.3.2 Safari/537.36
X-User-Session-Id: 8942a158-2245-4343-b55d-7bcf88573478
X-Client-Name: code
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US

First response:
HTTP/1.1 204 No Content
ETag: 0
Vary: Origin
request-context: appId=cid-v1:7314e4bb-c502-4f04-b61f-a0b4ebae90dd
X-Operation-Id: 47edc9ab7dbf4743b5c9304c61eb80f8
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: etag
Date: Mon, 07 Sep 2020 00:46:49 GMT

Second request:
POST /v1/resource/machines HTTP/1.1
Host: vscode-sync.trafficmanager.net
Connection: keep-alive
Content-Length: 114
Cache-Control: max-age=0
Origin: file://
X-Machine-Id: b64b74ca-07b9-4cc2-8917-bab8b0672dbf
X-Client-Version: 1.48.2
X-Client-Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
authorization: Bearer 7b312454800909e2e52c7293322356b74ad1d1ae
Content-Type: text/plain
X-Machine-Session-Id: 183db37a-d259-4fe0-9bd9-670e52e52910
X-Account-Type: github
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.48.2 Chrome/78.0.3904.130 Electron/7.3.2 Safari/537.36
X-User-Session-Id: 8942a158-2245-4343-b55d-7bcf88573478
If-Match: 0
X-Client-Name: code
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US

Second response:
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: text/plain; charset=utf-8
ETag: 33c9e224-4bb1-46dc-b347-22f3e78d6d11
Vary: Origin
request-context: appId=cid-v1:7314e4bb-c502-4f04-b61f-a0b4ebae90dd
X-Operation-Id: 0b0b58098e0c4eca9c7374328a6098fb
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: etag
Date: Mon, 07 Sep 2020 00:46:50 GMT

Home Machine

Had to turn sync setting on, since it was turned off because of the step done on the work machine.

First request:
GET /v1/resource/machines/latest HTTP/1.1
Host: vscode-sync.trafficmanager.net
Connection: keep-alive
X-Machine-Id: b64b74ca-07b9-4cc2-8917-bab8b0672dbf
Cache-Control: no-cache
X-Client-Version: 1.48.2
X-Client-Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
authorization: Bearer a4644050542166d4f7ecbff5e08ba1c352946bed
X-Machine-Session-Id: b1dba4fe-7c82-4ee3-aa08-8546b467b56e
X-Account-Type: github
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.48.2 Chrome/78.0.3904.130 Electron/7.3.2 Safari/537.36
X-User-Session-Id: d40a2e6d-a936-4623-8d59-b4a929593225
X-Client-Name: code
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US

First response:
HTTP/1.1 204 No Content
ETag: 0
Vary: Origin
request-context: appId=cid-v1:7314e4bb-c502-4f04-b61f-a0b4ebae90dd
X-Operation-Id: 4dc74dc44a1f4066b7a88e49720e855e
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: etag
Date: Mon, 07 Sep 2020 01:01:18 GMT

Seconde request:
POST /v1/resource/machines HTTP/1.1
Host: vscode-sync.trafficmanager.net
Connection: keep-alive
Content-Length: 112
Cache-Control: max-age=0
Origin: file://
X-Machine-Id: b64b74ca-07b9-4cc2-8917-bab8b0672dbf
X-Client-Version: 1.48.2
X-Client-Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
authorization: Bearer a4644050542166d4f7ecbff5e08ba1c352946bed
Content-Type: text/plain
X-Machine-Session-Id: b1dba4fe-7c82-4ee3-aa08-8546b467b56e
X-Account-Type: github
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.48.2 Chrome/78.0.3904.130 Electron/7.3.2 Safari/537.36
X-User-Session-Id: d40a2e6d-a936-4623-8d59-b4a929593225
If-Match: 0
X-Client-Name: code
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US

second response:
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: text/plain; charset=utf-8
ETag: 796f68ee-b001-4513-9f35-62757fceab9f
Vary: Origin
request-context: appId=cid-v1:7314e4bb-c502-4f04-b61f-a0b4ebae90dd
X-Operation-Id: 4e5e12fc6c5b4b4a8ff1e61496915fbb
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: etag
Date: Mon, 07 Sep 2020 01:01:19 GMT

Hope this will help.

**Comment by sandy081** [comment]
May I know if your home machine and work machine are in the same region network or any of the machines are connected to a VPN in a different region?

I also assume that you are using same login user on both machines.

**Comment by mrvkino** [comment]
Right now, both machine are at my home, since I am working from home. 

I don't recall if, at first, I enabled the sync from my work laptop at work and then enabled the home laptop sync at home, or both at home.

I am using the same user name to login on both laptop.

The machine's hostname are different.

**Comment by Eugenii10** [comment]
I have the same issue. I have a PC and a notebook at home. Both machines are connected to the same ethernet home router. User names at the both machines are identical, but they have different "Computer name" (machine name) values. I used my GitHub account for sync.
I use VS Code 1.49.2 User Setup. First machine has Windows 10 x64, second machine has Windows 7 x64.

**Comment by sandy081** [comment]
I see that both machines are having same `machine-id`.

@mrvkino Can you please open your user data directory - use command `Open Local Backups folder` and go two folders above. There will be a file called `machineid`. Can you please check what value you have there? Please check the value for both machines.

**Comment by Eugenii10** [comment]
Yep, my both computers had the same id in the `machine-id` file. So I have fixed this by:
1) Close VS Code on both machines.
2) Delete `machine-id` file on both machines.
3) Open VS Code, run command `Setting Sync: Show Sync Data`.
4) In the opened `Settings Sync` tab select `Clear Data in Cloud...` which also turns `Setting Sync` off. Close VS Code.
5) Repeat steps 3-4 on the second machine.
6) Open VS Code. Turn `Settings Sync` on at the first machine, then on the second machine.
7) If you still see the only one machine in the `Synced Machines` tab, repeat steps 3-6. I managed to get this to work with a 2nd attempt (probably I did something wrong in first time).

**Comment by mrvkino** [comment]
Sorry for the delay, my work laptop is in repair for a swollen battery. I'll report on @sandy081 when I get my laptop back and after I will try @Eugenii10 fix to see if it solves the issue.

**Comment by sandy081** [comment]
Thanks @Eugenii10 for confirming. 

@mrvkino Sure.

**Comment by mrvkino** [comment]
I also have the same `machineid` on both machine. I think is because I was using the [sync setting extension](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync).

I tried @Eugenii10 fix and it worked. It seem the extension moved the `machined` filed and cause some issue. Because, once I deleted the `machineid` file VSCode created the new file with different id.

**Comment by sandy081** [comment]
Thanks for confirmation, closing this since it is caused by the extension.
