### ISSUE TITLE
Uncomment does not work on change window in Mac

### ISSUE THREAD

**Issue by vaideeswaranr** [microsoft/vscode#104703]
Issue Type: <b>Bug</b>

Command + K, Command + U does not work on the code diff window on Mac. Command + K, Command + C works.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3

</details>

**Comment by alexdima** [comment]
@vaideeswaranr I cannot reproduce. `cmd+k cmd+u` works for me:
![Kapture 2020-08-30 at 17 36 17](https://user-images.githubusercontent.com/5047891/91663155-60c3a180-eae7-11ea-88c8-8f893bd889f9.gif)

**Comment by vaideeswaranr** [comment]
Hi Alexandru,

I tried again today on my mac and it doesnt seem to work. I have a screen recording but it exceeds the allowed 4 MB size. Is there another way to share it?
________________________________

**Comment by alexdima** [comment]
@vaideeswaranr What are you doing differently than me? I am pressing cmd+k, cmd+u and the code is uncommented. Do you perhaps have a different command defined in your `keybindings.json` file for this keybinding? Can you try to invoke the command via the command palette (`F1`)? Is this a keybinding problem or is the command not working for you?
