### ISSUE TITLE
It freezes after long usage or if i put pc on sleep and open it again, and some sections like terminal and more gets blur

### ISSUE THREAD

**Issue by tarun080698** [microsoft/vscode#104742]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

just keep on using it for long time in Ubuntu and also try it by put PC to sleep and wake up. try to use Vs Code, some portions will be blurred and after some time it freezes.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.4.0-42-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2969)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.66GB (0.16GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   125	 13208	code main
    0	    39	 13210	   zygote
    0	   180	 13231	   gpu-process
    0	    55	 13240	   utility
    0	   267	 13257	   window (BotandButton.css - scratch-bot - Visual Studio Code)
    0	   212	 13299	     extensionHost
    0	    86	 13357	       electron_node tsserver.js 
    0	   243	 13358	       electron_node tsserver.js 
    0	   125	 13431	         electron_node typingsInstaller.js typesMap.js 
    0	   102	 13376	       electron_node eslintServer.js 
    0	    55	 13377	       electron_node serverMain.js 
    0	    55	 13391	       electron_node languageserver.js 
    0	   133	 13421	       electron_node server.js 
    0	    63	 13517	       electron_node server.js 
    0	    71	 13734	       /snap/code/40/usr/share/code/code /snap/code/40/usr/share/code/resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=13299
    0	    63	 13314	     watcherService
    0	    63	 13422	     searchService
    0	     0	 13755	     /bin/bash
    0	    39	 13767	       npm
    0	     0	 13778	         sh -c react-scripts start
    0	    31	 13779	           node /home/tarun/VsCode/scratch-bot/node_modules/.bin/react-scripts start
    0	   204	 13786	             node /home/tarun/VsCode/scratch-bot/node_modules/react-scripts/scripts/start.js
    0	   118	 13330	   shared-process
    0	     0	 17325	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 17326	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   102	 17299	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (BotandButton.css - scratch-bot - Visual Studio Code)
|    Folder (scratch-bot): 47 files
|      File types: js(8) jsx(8) css(7) json(4) gitignore(1) md(1) txt(1)
|                  ico(1) html(1) jpg(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
vscode-browser-preview|auc|0.6.7
regex|chr|0.2.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
es7-react-js-snippets|dsz|2.8.3
prettier-vscode|esb|5.1.3
auto-rename-tag|for|0.1.4
code-runner|for|0.11.0
terminal|for|0.0.10
vscode-colorize|kam|0.8.17
katalium|kat|1.0.5
vscode-github|Kni|0.30.3
start-git-bash|McC|1.2.1
vscode-language-babel|mgm|0.0.29
theme-monokai-pro-vscode|mon|1.1.17
python|ms-|2020.8.101144
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
sublime-keybindings|ms-|4.0.7
vsliveshare|ms-|1.0.2619
debugger-for-chrome|msj|4.12.9
sqltools|mtx|0.22.11
vscode-css-peek|pra|4.0.0
java|red|0.65.0
vscode-yaml|red|0.9.1
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.27.1
vscode-java-pack|vsc|0.10.0
vscode-icons|vsc|10.2.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
The blue is probably https://github.com/Microsoft/vscode/issues/69665

Not sure about the freeze, could you elaborate what you mean by freeze (unresponsive, crash?) and post a screenshot? How long after this does it happen?
