### ISSUE TITLE
Setting profile

### ISSUE THREAD

**Issue by Nakarmi23** [microsoft/vscode#104706]
I work with different languages and frameworks like React, angular, Flutter etc. and i normally turn off all the extensions i don't need for a project. It would be great if you could create a profile which saves all the user preferences, then we can simply switch between those profiles as per need for our project.

**Comment by sandy081** [comment]
/duplicate

There is a feature request for this already and you can find it here - https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aextensions+label%3Afeature-request
