### ISSUE TITLE
Hierarchical workspace settings for multi-project repositories

### ISSUE THREAD

**Issue by narfanar** [microsoft/vscode#104760]
Provide some way to reference a "parent" .code-workspace file and inherit all non-overridden settings from it. And so on upwards.

Motivation:
Allow managing multi-project repositories where some users can choose to focus on a certain project (sub-folder) or open the entire repo at once from the root workspace. All that without duplicating settings.

The way I see it, _all_ settings would be inherited by default except the folders list and any settings put in a "skip_inheritance" list option next to the "inherit_workspace" key.

**Comment by sandy081** [comment]
There is an issue exists already for multi level project settings. Please go through the issues labelled `config` to find it.

**Comment by narfanar** [comment]
Closest I found in open issues was this: #15909

It doesn't cover doing the same for .code-workspace files though.
