### ISSUE TITLE
npm test fails on Windows

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10474]
- VSCode Version: 1.4
- OS Version: Windows 10

I don't know if I'm doing this right, but I'm trying to set up my extension up on AppVeyor to run tests. It works fine on Jenkins (Linux and OS X) but fails on AppVeyor. I can repro on my Windows desktop.

I'm running `npm test` (I presume this is correct - it seems to do the expected thing on Linux/Mac) but I get this output:

```
npm test --silent
### VS Code Extension Test Run ###
Current working directory: C:\projects\dart-code
Downloading VS Code into "C:\projects\dart-code\.vscode-test" from: https://vscode-update.azurewebsites.net/1.4.0/linux-x64/stable
Running extension tests: C:\projects\dart-code\.vscode-test\VSCode-linux-x64\code C:\projects\dart-code\out\test --extensionDevelopmentPath=C:\projects\dart-code --extensionTestsPath=C:\projects\dart-code\out\test
Failed to execute tests: Error: spawn C:\projects\dart-code\.vscode-test\VSCode-linux-x64\code ENOENT
Tests exited with code: -4058
Command exited with code 1
```

It seems to be downloading a **Linux** version of code. I tracked this back to `node_modules/vscode/bin/test` which has a platform check that only supports Linux and Mac:

    var platform = (process.platform === 'darwin') ? 'darwin' : 'linux-x64';

So, two questions:

1. What's the correct way to run tests on Windows/AppVeyor (I found [this](https://github.com/Microsoft/vscode/pull/5979/files) though I'm not sure if relevant)
2. Is there any reason `npm test` can't be made to work? All the pieces are cross-platform, it would be nice if this just worked the same everywhere

**Comment by bpasero** [comment]
Sorry, but we do currently not support running integration tests for extensions on Windows. See https://code.visualstudio.com/docs/extensions/testing-extensions

**Comment by bpasero** [comment]
This issue was moved to Microsoft/vscode-extension-vscode#30
