### ISSUE TITLE
Breaking points not working when the launch type is `extensionHost`

### ISSUE THREAD

**Issue by pd4d10** [microsoft/vscode#104761]
- VSCode Version: 1.48.0
- OS Version: Darwin x64 19.5.0

Steps to Reproduce:

1. Follow [this guide](https://code.visualstudio.com/api/get-started/your-first-extension) to create a helloworld extension
2. Run `Run Extension` in `launch.json`
3. Add a breakpoint to line 11 of `src/extension.ts`, which would not work and shows **unbound breakpoint**

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
In your steps to reproduce I do not see a step "run the Hello World action".
Without that step the extension will not activate and the breakpoint cannot be hit.

**Comment by pd4d10** [comment]
Oh, it does not activate until we do something. After the `run the Hello World action` step it works.

Thanks! Closing

**Comment by weinand** [comment]
> Oh, it does not activate until we do something. 
clever, isn't it?
