### ISSUE TITLE
无法识别符号

### ISSUE THREAD

**Issue by lcc184** [microsoft/vscode#104789]
Issue Type: <b>Bug</b>

刚安装上，环境配好了，别的都没问题，符号识别不了

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.78GB free)|
|Process Argv|C:\Users\lenovo\AppData\Local\Temp\k52zip_{B85A3812-33C8-4EEB-8CFB-090C39AA1AF7}\Readme.md|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio|hed|0.7.2
vscode-drawio-insiders-build|hed|0.7.301
vscode-language-pack-zh-hans|MS-|1.48.3
python|ms-|2020.8.101144
python|tht|0.2.3
vscodeintellicode|Vis|1.2.10

</details>

**Comment by lcc184** [comment]
Just installed, the environment is configured, everything else is ok, the symbol can't be recognized




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "VS Code Issue Triage Bot"<notifications@github.com&gt;; 
发送时间: 2020年8月17日(星期一) 下午4:21
收件人: "microsoft/vscode"<vscode@noreply.github.com&gt;; 
抄送: "Cardiac acid I "<2922898462@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [microsoft/vscode] 无法识别符号 (#104789)





 
感谢您创建此问题！
 
然而，由于您没有使用英语，我们很难进行处理。如果可能，请您将此问题描述修改为英文。请您直接编辑此问题，不要提交回复或新问题。
 
请注意，机器翻译服务通常无法处理用于讨论软件问题所需的技术性语言，所以我们推荐您寻找一位熟悉相关技术的人来协助翻译。
 
如果您无法做到，没有关系。此问题已经被标记为需要翻译，等待社区成员志愿进行翻译。
 
 
Thanks for creating this issue!
 
Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.
 
In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.
 
Otherwise, we have marked this as needing translation and a community member may be able to help out.

**Comment by isidorn** [comment]
Closing as will not
