### ISSUE TITLE
Avoid that a recommendation for an open editor becomes stale

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#104791]
As can be seen in the screenshot below it can appear that a recommendation is incorrect.
What happened is that:
- the user opened a docker file -> the recommendation appears
- the user closes the docker file and the Makefile is now that active editor, but the recommendation still shows up.

![image](https://user-images.githubusercontent.com/172399/90374477-d81f1d00-e073-11ea-8eb0-3252925b0b88.png)

The recommendation should be closed when currently open editor is closed.

**Comment by sandy081** [comment]
@egamma recently I improved recommendation text and following prompt is shown when you open a file that has recommendation

<img width="558" alt="image" src="https://user-images.githubusercontent.com/10746682/91488134-1f48b180-e8af-11ea-86f5-b78b94cb9fd1.png">

Prompt now includes the language context so switching files does not have reported confusion. I see that dismissing the recommendation might be good but if user switches back to the file that has recommendation showing back the prompt might be noisy? 

So, I would recommend to close this given that prompt has the context now?

**Comment by sandy081** [comment]
Closing this with above explanation/

**Comment by Tyriar** [comment]
We don't hide it due to potential noisiness/lifecycle issues, but we no longer mention "this file" which was the main problem as it gets stale fast.
