### ISSUE TITLE
Support local machine settings

### ISSUE THREAD

**Issue by cloudhan** [microsoft/vscode#104784]
As of 1.48, vscode officially supports setting syncing. However, some settings are conflict on different machine, or it depends on specific environment.

E.g.
- proxy settings #75616
- path-like settings  (clang-format, compiler pathes, and other tool pathes)

There are many more.

Currently, with VSCode Remote, it supports add settings to `<remote server>:~/.vscode-server/data/Machine/settings.json` that only applies to the host.

Now that with syncing enabled, User settings edited on one local machine will propagate them to other machine(s), which makes a whole bunch of chaos. Adding `<local>:~/.config/Code/Machine/settings.json` that is not syncing across machines might solve all these problems.

**Comment by sandy081** [comment]
Settings that are tagged as machine settings (`machine` scope) are not synced by default. You can also ignore manually those settings you do not want to sync. See - https://code.visualstudio.com/docs/editor/settings-sync#_configuring-synced-data

Closing as this is supported.
