### ISSUE TITLE
Exploration builds for apple silicon

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#104780]
- [x] Update `electron-11.x.y` to `v11.x.y`
- [x] Publish build from ci
- [x] selfhost

**Comment by deepak1556** [comment]
This is now complete, `electron-11.x.y` branch creates exploration build for apple silicon.

**Comment by deepak1556** [comment]
Build that can run on DTK, please do file any issues that you may encounter

https://az764295.vo.msecnd.net/exploration/02c157e4258b4fc59515cad3194cda3f17eaa505/VSCode-darwin-exploration-arm64.zip

**Comment by tarasis** [comment]
> Build that can run on DTK, please do file any issues that you may encounter
> 
> https://az764295.vo.msecnd.net/exploration/02c157e4258b4fc59515cad3194cda3f17eaa505/VSCode-darwin-exploration-arm64.zip

This is working for me on DTK. However after a bit it says there is an update, if you let it update then you get the “The window has crashed” error.

I assume updates will only appear here for now? (I’m disabling updates for the moment)

**Comment by deepak1556** [comment]
> I assume updates will only appear here for now? (I’m disabling updates for the moment)

Yeah update system is still being worked on, will create a tracking issue for it.

> should bugs for this build be posted in this thread

please create separate issues on the repo issue tracker. Thanks!

**Comment by pearcy** [comment]
Thank you deepak.

Working on DTK after I disabled the update.

**Comment by deepak1556** [comment]
Please use the following exploration build for apple silicon https://az764295.vo.msecnd.net/exploration/3cd7aea778b5886abc7acb0a8c1871d6f4bec6da/VSCode-darwin-arm64.zip , the previous version had an issue of pointing to incorrect update url. This new version should support automatic updates.

**Comment by rknall** [comment]
Thanks for the update! Makes my life easier on the DTK by a mile. Any idea, when this will be part of the inside builds or even the regular ones?

**Comment by deepak1556** [comment]
the runtime bits for apple silicon are only available with Electron 11 which is still under beta release, so insiders won't be available until we adopt stable electron 11 which will be sometime in November.
