### ISSUE TITLE
Debug variable hover not rendering 0 (zero) properly

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#104775]
I noticed this some time ago -- for some reason the hovers seem to render 0 (zero) differently than in the watch (it looks like an O)
![image](https://user-images.githubusercontent.com/641685/90356532-d3c81500-e01d-11ea-92d9-b591a76c5666.png)

I checked the DOM for each of these and they both seem to have the same content, a 0 (zero), and have the same font rule.

**Comment by isidorn** [comment]
Can not repro.
If you change the `editor.fontSize` can you still repro?

![Screenshot 2020-08-17 at 15 22 00](https://user-images.githubusercontent.com/1926584/90400854-69ef5000-e09d-11ea-8c54-f279092e19c7.png)

**Comment by eamodio** [comment]
@isidorn I looked into this more, and it seems to be caused by my `editor.fontLigatures` setting -- specifically the `'ss07'` one

```json
"editor.fontFamily": "Fira Code Retina",
"editor.fontLigatures": "'ss02', 'ss04', 'ss06', 'ss07'",
```

The `ss07` one is "Regex matching" so really unsure how that affects things.
![image](https://user-images.githubusercontent.com/641685/90422856-75d11700-e089-11ea-9234-21cd8a68eec7.png)

If I remove `ss07` then it displays properly. Really unsure why it works in the watch/editor/etc, but doesn't in the hovers.

**Comment by isidorn** [comment]
Thanks for providing more details. I also have no clue why this is happening, I am not doing anything special in the hover. 
The only difference is that the Hover belongs to the editor, and maybe editor handling of this is somehow affecting the hover...
Let's leave this open and maybe there is some smartness from the community.
