### ISSUE TITLE
Run Build Task List Not Sorting

### ISSUE THREAD

**Issue by bramankp** [microsoft/vscode#104714]
Issue Type: <b>Bug</b>

Recent update to 1.48.0 seems to have killed sorting the Run Build Task list by most recently used. In fact, the list doesn't appear to change order at all (not sorting lexicographically, either).

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (24.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-open-in-application|fab|1.0.5
cortex-debug|mar|0.3.7
cpptools|ms-|0.29.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.10
clang-format|xav|1.9.0
linkerscript|Zix|1.0.1

</details>

**Comment by alexr00** [comment]
To verify:
- Open a folder with build tasks, such as the VS Code repo. If you use the VS Code repo, in the tasks.json change the `group` of the `Build VS Code` task to simply be `"build"` (no `isDefault`).
- Run the Tasks: Run Build Task command
- Choose a build task and run it from that quick pick
- Run the Tasks: Run Build Task command again. Verify that the task you just ran shows at the top of the list in the recently used section.
- Repeat with another build task.

**Comment by aeschli** [comment]
Verified in Version: 1.48.1
Commit: 6387e6645f9ce6d7fb29ced2a12758424c3a4e49
Date: 2020-08-18T17:06:48.722Z
