### ISSUE TITLE
App crash on press "Tweet" on feedback 

### ISSUE THREAD

**Issue by ken0x0a** [microsoft/vscode#104771]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I have a feedback, but I can't tweet as app clash on press "Tweet"

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 5, 4|
|Memory (System)|40.00GB (4.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
vscode-styled-jsx|bla|2.0.0
better-toml|bun|0.3.2
firecode|ChF|1.2.10
dart-code|Dar|3.13.2
flutter|Dar|3.13.2
githistory|don|0.6.9
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
auto-close-tag|for|0.5.8
code-runner|for|0.11.0
vscode-google-translate|fun|1.4.8
vscode-graphiql-explorer|Gab|1.3.0
vscode-pull-request-github|Git|0.19.0
todo-tree|Gru|0.0.178
rest-client|hum|0.24.1
text-transformer|Jac|0.0.4
vscode-edit-csv|jan|0.3.0
vscode-graphviz|joa|0.0.6
tera|kar|0.0.2
vscode-svg-dev|kon|0.8.16
Kotlin|mat|1.7.1
change-string-case|max|1.1.2
markdown-shortcuts|mdi|0.12.0
dotenv|mik|1.0.1
vscode-mjml|mjm|1.0.1
vscode-json5|mrm|1.0.0
pyright|ms-|1.1.63
remote-containers|ms-|0.134.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
atom-keybindings|ms-|3.0.8
vscode-mscgen|msc|1.2.0
debugger-for-chrome|msj|4.12.9
vscode-react-native|msj|0.17.0
vscode-sanddance|msr|3.1.0
vscode-ios-common-files|Ort|1.0.5
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
crates|ser|0.5.2
autoimport|ste|1.5.3
code-spell-checker|str|1.9.0
svelte-vscode|sve|101.9.2
sass-indented|syl|1.8.9
cmake|twx|0.0.17
extension|vla|0.1.3
vscode-icons|vsc|10.2.0
vscode-todo-highlight|way|1.0.4
vscode-capnp|xmo|1.0.0
markdown-all-in-one|yzh|3.2.0
vscode-firstupper|zki|0.2.1
vscode-proto3|zxh|0.4.2

</details>

**Comment by deepak1556** [comment]
Does the crash happen with latest insiders https://code.visualstudio.com/insiders ?

**Comment by ken0x0a** [comment]
As I'm not using "insiders" and this is not an often-used-feature for me, I'm closing this once.
I'll reopen this if I confront this issue next time.
