### ISSUE TITLE
Confusing behaviour with word highlighter overriding document highlighter

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10470]
It's possible this is intended, or a problem with our code, but I can't find any discussion about it to confirm...

- VSCode Version: 1.4
- OS Version: Windows 10

We've implemented a document highlighter that highlights symbols in the document. If you put your cursor inside an item, it works as expected:

![As expected](https://cloud.githubusercontent.com/assets/1078012/17621440/3c05ea28-608b-11e6-88d0-aa69416d173f.png)

However if you double-click to highlight the element, then the results from the document highlight are overriden (or supplemented with) word highlgihts be vscode (resulting in incorrect things behind highlighted):

![Not expected](https://cloud.githubusercontent.com/assets/1078012/17621457/5598b128-608b-11e6-973b-3c82df88b3c4.png)

I see the same behaviour in TypeScript so I don't think it's our bug (and is probably intended) but I thought it was worth clarifying. It's not what I'd expect (as a user). If there is no document highlighter registered this would be fine, but in this case I think extensions should have the say in what's highlighted. (I think Fat VS does what I'm asking for here?)

**Comment by jrieken** [comment]
Yeah, that's on purpose and can be control using the find widget controls (match whole word, match casing). Those knobs are also respected when the widget isn't visible.

![screen shot 2016-08-12 at 14 52 31](https://cloud.githubusercontent.com/assets/1794099/17622761/955e4da2-609c-11e6-8f8c-e9894dc527b3.png)

**Comment by jrieken** [comment]
Closing as design, speak up if your really hate the behaviour.

**Comment by DanTup** [comment]
I do kinda hate it (VS(?) has taught me to double-click to select symbols when then looking for them) but that's just muscle memory and I'm just one dev. Is it something I can turn off (for me, as a user)?

I think it'd be really useful in the case where there's no extension providing it, but when there is, highlighting all instances of a word is (IMO) likely never better than delegating to the language service.

**Comment by jrieken** [comment]
Don't confuse it with word highlight since one is based on smarts and the other is just looking at whatever is currently selected. Actually, there is a setting for this `"editor.selectionHighlight": false|true`

**Comment by DanTup** [comment]
Slightly confused by your last comment; confuse what with word highlights? Document highlights (provided by extensions) is good, but the other behaviour (which I presume is word highlights) I'm not keen on (not where there's a language service, anyway).

> Actually, there is a setting for this "editor.selectionHighlight": false|true

Excellent, that's done exactly what I wanted. I didn't find it because I was searching for things with "word" in them. Doh!

Thank you!
