### ISSUE TITLE
PHP: Break statement breaks indentation

### ISSUE THREAD

**Issue by HaikuOezu** [microsoft/vscode#104836]
Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z (4 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

If I type a break statement inside a block (such as a foreach loop) code indentation seems to break, verified by using the "Reindent lines" command

**Screenshots**
Before:
<img width="336" alt="Schermata 2020-08-17 alle 17 34 58" src="https://user-images.githubusercontent.com/814403/90415060-dde72380-e0b0-11ea-8b72-26d14a20a8cb.png">
After:
<img width="360" alt="Schermata 2020-08-17 alle 17 35 38" src="https://user-images.githubusercontent.com/814403/90415079-e2abd780-e0b0-11ea-8f76-51ab581873d3.png">
(Notice the last two lines)

Indentation also seems broken in Switch statements to me
<img width="155" alt="Schermata 2020-08-17 alle 17 42 41" src="https://user-images.githubusercontent.com/814403/90415208-12f37600-e0b1-11ea-8c56-bc3a7023054c.png">

I've tried searching around but found nothing.. am I doing something wrong here? It doesn't seem right that typing a break statement pushes everything back.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Does the `Reindent lines` command come from some PHP extension? If so please file this on that extension

**Comment by HaikuOezu** [comment]
> Does the `Reindent lines` command come from some PHP extension? If so please file this on that extension

Oh, I thought it was a built in command because it still appears even when launching with extensions disabled... shouldn't that disable every command coming from an extension?
Just to be sure I uninstalled EVERY extension in VSCode and I still get the same problem.
It should be noted that it's not even necessary to run Re-indent lines... when I type break; VSCode automatically shifts it left.

<img width="218" alt="Schermata 2020-08-18 alle 03 51 45" src="https://user-images.githubusercontent.com/814403/90461269-24b33880-e106-11ea-8414-971f57cd2bd4.png">

**Comment by roblourens** [comment]
Yeah I think 

- In a switch, break should not be at the same indentation level of `case`, but it does end an indentation level
- In a for loop, it shouldn't affect indentation

maybe we should just revert the original fix and live with the not quite correct behavior in a switch. It looks like the original issue exists in TS

**Comment by connor4312** [comment]
Just reverting the original change

**Comment by rzhao271** [comment]
`Reindent Lines` is still broken for me on this case:
```php
<?php
function test()
{
    $arr = [1, 2, 3, 4];
    $val = null;
    foreach ($arr as $key) {
        if ($key == 2) {
            $val = $key;
            break;
        }
    }
    $val2 = null;
    switch ($val) {
        case 1:
            $val2 = 3;
            break;
            
            default:
            $val2 = 0;
            break;
        }
    }
    ?>
```
`Format Document` works on it, though.

**Comment by connor4312** [comment]
That's the intended state of things with the rollback. There's not a good solution with the limited capabilities available in the regex
