### ISSUE TITLE
Add "editor.gotoLocation.multipleDeclarations": "gotoAndFind"

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#104824]
It would go to a single result immediately and open the references view for multiple results.

Why:
- "peek" is like a keyhole, too small to work with. Same with "gotoAndPeek" for multiple results.
-  "goto"'s statusbar indicator is too subtle.
- Find All References is great, but what about declarations vs. implementations vs. type definitions ... ?

Same for "editor.gotoLocation.multipleDefinitions", "editor.gotoLocation.multipleImplementations", "editor.gotoLocation.multipleReferences" and "editor.gotoLocation.multipleTypeDefinitions".

**Comment by n0099** [comment]
Value `gotoAndPeek` will do that.
