### ISSUE TITLE
Git: Add support to delete remote git tags using command palette

### ISSUE THREAD

**Issue by Oran** [microsoft/vscode#104845]
Be able to delete remote git tags using  this command using command palette

`git push --delete origin tagname`

currently only deletes local tags

**Comment by SMAKSS** [comment]
@joaomoreno Well, if this one still opens for participating, I would love to give you a hand with it. 😀

**Comment by CubixPro** [comment]
@joaomoreno @SMAKSS  I would like to work too. We can work on this together.

**Comment by Shubhamurkade** [comment]
@joaomoreno I saw this issue open and I was able to get it working with the PR that I've submitted above. If nobody was working on this then could you please look at the PR?

**Comment by tlu1717** [comment]
Hello, can I try working on this PR? I am from GHC OSD. If so, how can I start? I'm new to this.

**Comment by rolimans** [comment]
Is this issue being take care of? I'm looking to start contributing and thought I may help

**Comment by deniskutovskiy** [comment]
Hello, I'm new to contributing. So can I try working on this PR?

**Comment by ps-19** [comment]
@Tyriar @Oran if it is still open assign me please. I will love to work on it.

**Comment by joaomoreno** [comment]
Closed by https://github.com/microsoft/vscode/pull/170415

**Comment by lszomoru** [comment]
Verification steps:
* Create a new repository on GitHub or use one of your existing GitHub repositories
* Open the folder/workspace that contains the git repository in VS Code Insiders
* Create a new tag, and push the tag to the remote
  * Open the repository on GitHub.com and confirm the tag has been pushed to the remote
* Open the command palette and invoke the "Git: Delete Remote Tag" command
  * Confirm that the remote tag appears in the quick pick widget
* Pick a tag to be deleted
  * Open the repository on GitHub.com and confirm the tag has been deleted

**Comment by eleanorjboyd** [comment]
The tag was successfully deleted but two tags showed up in the `delete remote tag` dropdown that were for the same branch just one had additional brackets.
<img width="969" alt="Screenshot 2023-01-25 at 8 32 31 AM" src="https://user-images.githubusercontent.com/26030610/214621234-e74833a4-eef7-47d7-b1c8-de5dc999baf7.png">

**Comment by lszomoru** [comment]
🤔 Could you run the following command from the integrated terminal:
```
git ls-remote --tags
```

What does it return? Also do you have a consistent repro of these tags showing up after you deleted a remote tag?

**Comment by eleanorjboyd** [comment]
output:
```
eleanorboyd@Eleanors-MacBook-Pro tester_for_git_issues % git ls-remote --tags

From git@github.com:eleanorjboyd/tester_for_git_issues.git
7874ad06af697a46c189a6fc6191bc7305808178        refs/tags/tester-tag-delete
9984b844794fb0a92e18ebf8a88dfd6e4e18b2d8        refs/tags/tester-tag-delete^{}
```

**Comment by eleanorjboyd** [comment]
also once I delete `tester-tag-delete` then `tester-tag-delete^{}` also disappears. Output to above command following using the `delete remote tag` command:

```
eleanorboyd@Eleanors-MacBook-Pro tester_for_git_issues % git ls-remote --tags

From git@github.com:eleanorjboyd/tester_for_git_issues.git
```

**Comment by lszomoru** [comment]
@eleanorjboyd, could you please go through the steps using VS Insiders released on Friday. 

The issue here is that when you create a tag in VS Code, it creates an annotated tag, which be being represented by two refs on the remote (ex: `tagName` and `tagName^{}`). With the latest changes we deduplicate the annotated and lightweight tags so the quick pick should not show entries that end with `^{}`. Delete a tag on the remote will delete both the annotated and the lightweight tags.

**Comment by eleanorjboyd** [comment]
Hello! I am still seeing the duplicate tag name on the dropdown. (sorry for the delay, my VS Code was really struggling to download the newest version of insiders). 
<img width="943" alt="Screenshot 2023-01-26 at 1 28 38 PM" src="https://user-images.githubusercontent.com/26030610/214954861-7da20338-5807-4120-9eaa-d833ec7221ce.png">

**Comment by lszomoru** [comment]
@eleanorjboyd, the fix is included in Friday's Insiders build. Could you please attempt to validate this today.

**Comment by eleanorjboyd** [comment]
Yep was also able to verify- thanks
