### ISSUE TITLE
findTextInFiles fails on redundant glob

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104889]
Refs https://github.com/microsoft/vscode/issues/104648#issuecomment-675242945

There's an outfile pattern that we compile to `new RelativePattern('<workspaceFolder>', 'dist/**/*.js, dist/*.js')`. This fails to match anything, but `new RelativePattern('<workspaceFolder>', 'dist/**/*.js')` works.

Complete options:

```js
findTextInFiles(
  { pattern: 'sourceMappingURL', isCaseSensitive: true },
  {
    include: {
      base: "E:\\TestBed\\vscode-ts-debug-failure",
      pattern: "dist/**/*.js, dist/*.js",
    },
    exclude: "",
    useDefaultExcludes: false,
    useIgnoreFiles: false,
    useGlobalIgnoreFiles: false,
    followSymlinks: true,
    beforeContext: 0,
    afterContext: 0,
    previewOptions: {
      charsPerLine: 9007199254740991,
      matchLines: 1,
    },
  },
)
```

**Comment by roblourens** [comment]
Should it be wrapped in `{}`?

**Comment by connor4312** [comment]
We use `new RelativePattern` -- this was just the result of me copying the options directly from the debugger https://github.com/microsoft/vscode-js-debug/blob/7dd5107733e7982888c129279c06cf13da6c4f93/src/common/sourceMaps/codeSearchStrategy.ts#L86

**Comment by roblourens** [comment]
Yeah

**Comment by connor4312** [comment]
Ok. Is that something we should do for _all_ patterns? That is, change

```
forceForwardSlashes(files.patterns.filter(p => !p.startsWith('!')).join(', ')),
```

to

```
'{'+ forceForwardSlashes(files.patterns.filter(p => !p.startsWith('!')).join(', ')) + '}'
```

**Comment by roblourens** [comment]
I believe so

**Comment by connor4312** [comment]
Yea, it works in general, just not this case. I'll give it a shot.

**Comment by connor4312** [comment]
It seems like ripgrep doesn't like that, `{**/*.js, out/*.js}` and `{**/*.js}` don't match any files

**Comment by connor4312** [comment]
This also seems to fail if the pattern `base` is a workspace folder and the pattern navigates outside of it (e.g. `../foo/**/*.js`)
