### ISSUE TITLE
Shortcut to list down only methods/fucntions from JS or TSX file in the VS Code Quick Open (CTRL+P) window

### ISSUE THREAD

**Issue by pavangayakwad** [microsoft/vscode#104847]
Issue Type: <b>Feature Request</b>

For now, when I click CTRL + E and then @, The quick open windows shows me all the methods and variables declared in the currenly opened file.

![image](https://user-images.githubusercontent.com/1834890/90422376-67f6b280-e0d8-11ea-9ac8-78aac9481ce5.png)

It would be great if there is a way to list down only the Javascript functions/methods so that we can easily navigate between methods quickly. 

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041

**Comment by mjbvz** [comment]
Type `@:` instead of `@` to sort the list by type

**Comment by pavangayakwad** [comment]
Thanks for the comment, it works partially though.

Please find the below screenshot, the @: jumbling variable assignments with method name list. Expected vscode to identify these and group them properly.

![image](https://user-images.githubusercontent.com/1834890/90473019-817f1500-e13f-11ea-85d0-b2370ad17580.png)

**Comment by mjbvz** [comment]
I may be misunderstanding your screenshot but the part to the right of the symbol name is the symbol that contains it. `@:` groups based on the type of the symbol itself

**Comment by pavangayakwad** [comment]
Expecting behavior similar to Visual Studio 2019 code window. Please find the screenshot of VS2019 below. The methods and only the global variables are listed in the navigation dropdown menu. However, in VSCODE it consider private variables inside the methods (which is good). It would be great if the VSCODE quick open menu group methods and variables (can be made configurable to ON or OFF grouping from the VSCODE settings).

![image](https://user-images.githubusercontent.com/1834890/90728064-e07c8f80-e2e1-11ea-931c-377101f1ec31.png)

**Comment by pavangayakwad** [comment]
...and when I said "grouped", I meant this:

![Untitled](https://user-images.githubusercontent.com/1834890/90729982-fccdfb80-e2e4-11ea-9070-eccec3316b49.jpg)
