### ISSUE TITLE
Hover state for adding new cells is hard to find

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#104854]
During the Python user studies we discovered that some users had a hard time finding the add new cell toolbar at the bottom However, once they discovered it they really liked the position of it. We should explore to see if we can improve this discoverability. A few ideas below:

## 1. Increase the hover target 

We can try to increase the vertical hover target to allow users to trigger this. We'd need to be cautious to make sure this can work with interactive elements above it like the status bar.

![image](https://user-images.githubusercontent.com/35271042/90428859-7792de80-e079-11ea-9234-b0972b734fca.png)

## 2. Always visible on hover

Similar to our cell toolbar, but this adds visual noise while making it highly discoverable. The other cells can still be triggered on hover.

![Kapture 2020-08-17 at 11 13 35](https://user-images.githubusercontent.com/35271042/90429535-c3925300-e07a-11ea-8254-b81a5345eb6f.gif)

**Comment by roblourens** [comment]
Increased the hover range so that it covers the whole area between cells, and some equal extra space above the actual toolbar. We can see how this feels.
