### ISSUE TITLE
SQL: Incorrect syntax highlighting with backslash (\) in strings

### ISSUE THREAD

**Issue by olibraun** [microsoft/vscode#104810]
VSCode seems to (incorrectly) think that the backslash (\\) is an escape cahracter for the single quote in SQL - which it is not.
Therefore as soon as you have a string ending in a backslash, all the remaining SQL code in a file will also be highlighted as if it were part of that string.

Here's a GIF that shows this incorrect behavior.

![2020-08-17_13h11_27](https://user-images.githubusercontent.com/29063670/90390564-d95c4400-e08b-11ea-9c4f-68663bcfc977.gif)

- VSCode Version: 1.48.0
- OS Version: Windows 10 Pro Version 1809

Steps to Reproduce:

1. Set VSCode to syntax highlight for SQL.
2. Enter a query with a string (single quotes) which ends in a backslash (\\)
3. Write some SQL code after that - it will incorrectly be highlighted as if it were part of the string as well.
4. Remove the backslash to see the correct highlighting.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
@olibraun are you sure you have all extension disabled (that MSSQL in the status bar is suspicious). I'm not able to reproduce the issue:

![image](https://user-images.githubusercontent.com/38270282/91732778-fe32da00-eba8-11ea-8d98-904707c1790e.png)

**Comment by olibraun** [comment]
@alexr00 You're right, I think I failed to properly disable all extensions when I initially created this issue.
Also, looks like you're on the right track with regard to that "MSSQL" in the status bar. That comes from Microsoft's SQL Server extension in VSCode, where the behaviour I described is a known issue, see https://github.com/microsoft/vscode-mssql/issues/1680
Looks like this isn't a bug in VSCode after all, sorry and thanks for the hint towards the extension :-)
