### ISSUE TITLE
Revisit collapse shortcuts

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#104860]
- VSCode Version: 1.49.insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open an ipynb notebook
1. Collapse a cell using the context menu
1. Attempt to do the same with the keyboard shortcut ('C C').

Does not seem to work. Maybe I'm not understanding what ```C C``` means though. (I'm holding down SHIFT and hitting C twice).

Does this issue occur when all extensions are disabled?: N/A

**Comment by roblourens** [comment]
No shift. Just `c c`. I'm not sure about this keybinding though, I think we should come up with a new one at some point. But I understand that Jupyter doesn't have a default keybinding for this.

**Comment by jrieken** [comment]
These shortcuts do work for me - but there is screen cheese when collapsing output

**Comment by roblourens** [comment]
There are a few issues with showing outputs right now that need some work

**Comment by DavidKutu** [comment]
I'm adding the keybinding that executes the command 'notebook.cell.collapseCellContent' to the python ext. And it takes it as copy twice, I can make it work by using another keybinding, like 'S C' for example.

**Comment by roblourens** [comment]
> I'm adding the keybinding that executes the command 'notebook.cell.collapseCellContent' to the python ext.

We can fix the keybinding in vscode. I don't really care what it is, jupyter has no precedent from what I understand. We just have to pick one and change it. Would rather have a good common set of keybindings in vscode than have extensions override everything.

**Comment by roblourens** [comment]
Changed to:

- Collapse cell input: `cmd+K cmd+C`
- Collapse cell output: `cmd+K T`

These are ctrl on windows
