### ISSUE TITLE
I messed up

### ISSUE THREAD

**Issue by Tim9-cpu** [microsoft/vscode#104802]
Issue Type: <b>Feature Request</b>

Hello,

I tried some stuff and messed everything up, I would like to reset everything but when I uninstall then reinstall, it keeps my data so everything is still messed up.  Does anyone know a better/ faster way to do this?

Thank you,

Tim

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18362

**Comment by 7Ragnarok7** [comment]
@Tim9-cpu You can delete this .json file located at this location: %APPDATA%\Code\User\settings.json
Also make sure to turn off synchronisation and delete all synced data from settings before doing the above if you are signed in with github or microsoft
