### ISSUE TITLE
VSCode on Linux is opening root file alongside the targeted directory

### ISSUE THREAD

**Issue by saandre15** [microsoft/vscode#104882]
# How to reproduce the issue?
Terminal
```shell
cd ~/Documents/Repos/project
code .
```

# What the issue?
Two instances of VSCode opens. One with the project directory and the other with the /etc/sudoers. This only happens on non-root users. There no problem when I'm using sudo to run VSCode on a directory. I'm unable to save the /etc/sudoers file because I'm opening it as a non-root users. This may be an issue with the file save handler. 

# What I'm looking to do?
1. Use code . and just open the targeted directory.

**Comment by bpasero** [comment]
Possibly the file is dirty and thus we decide to open it in the second window, can you close the editor?

**Comment by saandre15** [comment]
This is a recursive issue. Since the file can't be saved w/o root privilege and I can't open the file as root. And thus I'm forced to close out of VSCode w/o saving the file. Next time I open the program, I'll be greeted with the same issue as well. Is there any state file I can modify to fix the issue?

**Comment by saandre15** [comment]
Reinstalling VSCode doesn't alleviate the issue. So there probably some sort of last state/config file that causing an issue.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by saandre15** [comment]
I don't use debian nor fedora based linux distribution. Which git channel is the current VSCode Insider on? I'll just compile from source.

**Comment by saandre15** [comment]
I already installed the insider branch and it worked properly. So the issue must of been in the config files. I just deleted all the configs and let VSCode reinstate the config again. I guess this issue has something to do with workspace persistence and saving files. I don't know if the insider preview fixed this issue as I'm unable to to replicate it again.
