### ISSUE TITLE
File getting deleted on its own. Unable to restore the deleted file as well.

### ISSUE THREAD

**Issue by shrutipant7** [microsoft/vscode#104837]
- VSCode Version: 1.48.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1.  Happening randomly anytime.
2.  While I'm editing some piece of code, the file is getting deleted on its own. Getting error message "Unable to resolve non-existing file" when I try to restore and save it again.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by shrutipant7** [comment]
Also, if I create the file again with same name as before, its not getting created.  Trying it with a different name works.

**Comment by bpasero** [comment]
This does not sound like a problem inside VSCode, but anything in the OS may decide to delete the file or even an extension?

I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by shrutipant7** [comment]
I tried running my project on VS with extensions disabled. The issue is not resolved.

- I get error saying "Unable to resolve non-existing file <filename>" when I tried creating the file again with the same name as before in the same directory.

- I'm not able to restore the deleted file from source control panel by discarding changes (in which my file got deleted
![Screenshot (47)](https://user-images.githubusercontent.com/29400237/90494699-67562e80-e161-11ea-9880-19207c2d07e4.png)
).

**Comment by shrutipant7** [comment]
Everytime this happens, I'm left with just one solution - Creating the same file again with a different name. And its happening very frequently (once very 3-4 hours).

**Comment by bpasero** [comment]
Does this happen with every file type?

**Comment by shrutipant7** [comment]
I'm working with .ts files currently. Didn't check for others. Does pressing keyboard shortcut "CTRL + S" for saving the file after editing have any relation with this problem?

**Comment by bpasero** [comment]
@shrutipant7 well, do you have auto save enabled? Does it reproduce with auto save?

**Comment by shrutipant7** [comment]
I have also tried downgrading to VS Code v 1.47 (June 2020 release).  The problem is still there. I don't have auto save enabled.

**Comment by bpasero** [comment]
Sorry I cannot be of more help without a way for me to reproduce the files getting deleted.

**Comment by NikitaVaidya99** [comment]
im facing exactly the same problem with js files
VSCode Version: 1.48.2
OS Version: Windows_NT x64 10.0.19041
