### ISSUE TITLE
Hoping to use high level encoding, like gbk when auto guess gb2312

### ISSUE THREAD

**Issue by shutaozhenzhen** [microsoft/vscode#104895]
GBK completely include gb2312. In VSCode, I use auto guess encoding, but some file in gbk read as gb2312 and cause problem. I think in languages like Chinese, always read as gbk when guess gb2312 is helpful, or adding an check like try to read as gb2312, if error happen, auto change to gbk instead.

And can we set a list of encoding which auto guess only choose from them?  Sometimes files are too small to guess encoding, and a gb2312 file being read as windows1252. I think a way to make sure some encoding never be choosed can be helpful.

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.
