### ISSUE TITLE
Issue with VbScript code

### ISSUE THREAD

**Issue by dlbjr** [Microsoft/vscode#10482]
- VSCode Version: Code - Insiders 1.5.0-insider (e9c80f036645caae7759b3954fc72dbe6c644edf, 2016-08-12T06:07:39.195Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1. Open a VBScript with a class defined in it
2. The "End Property" and "End Class" Statements are not being recognized as reserved words and turning blue as expected.

**Comment by Bill-Stewart** [comment]
Duplicate of #10481
