### ISSUE TITLE
July update cause java highlight break

### ISSUE THREAD

**Issue by ericsia** [microsoft/vscode#104811]
Issue Type: <b>Bug</b>

I had so much pain working with java now.
Now the highlight is glitchy, it don't highlight properly.
Comment don't get highlighted :( I feel sad

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.14393

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
java|red|0.65.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.11.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.1
vscode-maven|vsc|0.24.0
generic-pseudocode|Wil|1.2.0

</details>

**Comment by alexr00** [comment]
Does this issue still happen if you disable all extensions? 

If it does still happen with all extension disabled, can you please provide a copy/pastable example?

**Comment by alexr00** [comment]
@aeschli FYI about the semantic highlight.

**Comment by aeschli** [comment]
@ericsia Please file the issue against the Java extension which provides the semantic highlighting: https://github.com/redhat-developer/vscode-java/issues.
When doing so, please provide a small Java code sample and screenshot that show the problem.

**Comment by ericsia** [comment]
> @ericsia Please file the issue against the Java extension which provides the semantic highlighting: https://github.com/redhat-developer/vscode-java/issues.
> When doing so, please provide a small Java code sample and screenshot that show the problem.
I hate to turn it on again but this is what it look like
![email](https://user-images.githubusercontent.com/24624808/91446739-6aac9100-e8aa-11ea-8802-ec83abc1fc1d.png)
