### ISSUE TITLE
"JetBrains Mono" setted to editor.fontFamily stop working.

### ISSUE THREAD

**Issue by dlagg** [microsoft/vscode#104809]
Issue Type: <b>Bug</b>

1. Install on your system jetbrains mono font. (**ttf-jetbrains-mono** on my archlinux).
2. Set in your settings.json: 
"editor.fontFamily": "JetBrains Mono"
3. Open a file. 
4. The font isn't rendered. Before the update it worked.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.8.1-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.53GB (2.74GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.2
vscode-eslint|dba|2.1.8
eppz-code|epp|1.2.52
prettier-vscode|esb|5.1.3
auto-using|Fud|0.7.15
csharpextensions|jch|1.3.1
vscode-csharp-snippets|jor|0.3.1
vscode-gist|ken|3.0.3
csharp|ms-|1.23.0
indent-rainbow|ode|7.4.0
aspnet-helper|sch|0.6.4
vim|vsc|1.16.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.2.0

(21 theme extensions excluded)

</details>

**Comment by hiredtocode** [comment]
Have you selected all the TTF files and right-click > install?

**Comment by dlagg** [comment]
> Have you selected all the TTF files and right-click > install?

I installed the font with **pacman** the package is `ttf-jetbrains-mono`.
Seems the new update isn't detecting the font. In fact the autocompletion only shows `"'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'"` (default).

**Comment by dlagg** [comment]
I try with `Cascadia Code` and after restart vscode works.

**Comment by dlagg** [comment]
Okey, the problem was the Font Weight, it seems was set to lowest.
