### ISSUE TITLE
Format Code not working

### ISSUE THREAD

**Issue by johanneskopf** [Microsoft/vscode#10487]
- VSCode Version: 1.5.0-insider
- OS Version: Windows 10, Build 14901

I work with Unity, but no matter if I open a whole solution or only a .cs file: the formatting of the code with (Shift+Alt+F), or by using the action in the command palette, isn't working.

**Comment by brandonmp** [comment]
Will just add-on to this one though my circumstances are diff't:

VSCode v. 1.4.0
OS: Ubuntu 16.04

Has worked flawlessly for months, but just stopped yesterday. Uninstalled/reinstalled a few times, and tried in various projects/languages (namely: JS, JSX, and Python), still no formatting (either via shortcut or via command palette).

Admittedly I'm not sure how to -fully- uninstall the app, as every time I re-install, it remembers what files I had opened.  I imagine there are settings leftover somewhere, so I'll keep trying to find/delete those.

**Comment by johanneskopf** [comment]
I tried to reinstall VS Code, deleting the extension folder and the VS Code Folder in APPDATA, but nothing changed.

**Comment by brandonmp** [comment]
Does VSCode leave any windows registry keys?  Since it's a bug that starts spontaneously, I have to imagine there's some residual settings somewhere. 

If you install logged in as a  diff't user, any luck?

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#660

**Comment by brandonmp** [comment]
thanks @jrieken . my issue was multi-language (javascript, JSX, python), so I'm not sure it falls under OmniSharp. Is there another place I should post it besides VSCode? If not, I'll create a new issue to split it from the OP's C# problems

**Comment by jrieken** [comment]
@brandonmp The rule is like this: One problem, one issue. Don't mix in [other](https://github.com/brandonmp) [things](https://github.com/brandonmp). 

Regarding formatting: There is not one formatter to rule them all, but each language extension can bring in a formatter for its language. That's why also that must be kept separate

**Comment by brandonmp** [comment]
Thanks @jrieken , understood. 

If code formatting is solely a function of the language extension, then my problem is separate from OPs (and thus a separate issue). Can you point me to where the JS/JSX formatting issue is best posted then?

**Comment by jrieken** [comment]
Depends - if you believe it's a problem with the underlying TypeScripte/JavaScript we use please refer to https://github.com/Microsoft/TypeScript else create a new issue with a sample etc here. Thanks

**Comment by esuus** [comment]
Formatting just stopped working for me out of nowhere yesterday. Neither right-click > format document, nor Alt+Shift+F.
Has this been solved?
