### ISSUE TITLE
Scroll with mouse wheel in Explorer tab while dragging file

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#104884]
Issue Type: <b>Feature Request</b>

User experience of the Explorer tab would be improved if one could scroll with the mouse wheel while they were dragging a file/folder/etc.. The current functionality forces you to drag an element to the top or bottom of the tab to get to that invisible spot where the tab will start to scroll. This works but is not nearly as tactile a feeling as having control with the scroll wheel. This is especially the case where the tab is populated with many elements and one would need to scroll further than usual to find what they are looking for, sometimes accidentally scrolling past what was being looked for and then having to scroll back - which means moving your mouse all the way back up or down to the other end of the tab in awkward hand movement fashion.

The mouse wheel is faster and feels far more natural.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
DUp of https://github.com/microsoft/vscode/issues/95744
