### ISSUE TITLE
Expose 'sendInputEvent' to extensions to allow simulating keypresses

### ISSUE THREAD

**Issue by berknam** [microsoft/vscode#104832]
Is it possible to expose the 'sendInputEvent' function from `window.webContents` or create some command like 'sendInput' or 'sendKey' to extensions?

This is related to issue #30009. In VSCodeVim if we want to be able to support macros with code completion and snippet use and store those macros on disk we need to store the macros as key presses, but for that we need to capture the \<tab\> key in insert mode, which is currently disabled so that the correct behavior is used (insertSnippet, autocomplete, jumpToNextSnippetPlaceholder or something else from other extension).

If we could resend the \<tab\> key, we could then capture it and send it again while ignoring our sent key by using the `when` clause with a context like `when !vim.ignoreTabKey` which we would set before sending the key and unset after. This way we would be able to at least know that the \<tab\> key was pressed and we could repeat that by sending the key whenever needed (either through macros, or the dot `.` command, even when using \<C-a\> in insert mode to insert last inserted text.

Basically the pretended feature would be a command like this:
```ts
vscode.commands.executeCommand('sendKey', { key: 'tab' });
```
That would trigger the registered command with that key but instead of skipping the current command like @rebornix mentioned here https://github.com/microsoft/vscode/issues/30009#issuecomment-313242509 it would be up to the extension to ignore it using the `when` clause, like this:
```ts
await vscode.commands.executeCommand('setContext', 'vim.ignoreTabKey', true);
await vscode.commands.executeCommand('sendKey', { key: 'tab' });
await vscode.commands.executeCommand('setContext', 'vim.ignoreTabKey', false);
```
contributes.keybindings:
```json
{
  "key": "tab",
  "command": "extension.vim_tab",
  "when": "editorFocus && vim.active && !vim.ignoreTabKey && !inDebugRepl"
},
```

Of course that if it is possible to skip the current command like @rebornix said that would be even better because the way I'm proposing would probably make the \<tab\> key slower depending on the machine and if the extensionHost is busy or not.

**Comment by rebornix** [comment]
It's an interesting idea, and not specific to editor. It's actually asking to mimic browser behavior (key pressing) from the extension host. I wonder if it's something we want to support.

**Comment by berknam** [comment]
@rebornix @jrieken 
Maybe instead of exposing 'sendInputEvent' it might be easier, safer and better to expose 'dispatchKeyBinding' from 'src/vs/platform/driver/electron-main/driver.ts'.

Basically the idea is to be able to send a keypress from an extension and let vscode handle it normally as if it was a keypress by the user.

**Comment by berknam** [comment]
This is also somewhat related to the issue #1431 because if we could send a key to vscode that would be handled normally we could consume the TAB key and then resend it again (ignoring it this second time).

This is a major issue right now because of the overhaul that happened recently to the remapper in VSCodeVim. Now the remapper works more like it does in real Vim and the timeout has been implemented the same way as in Vim. This means that if the user creates a remap like `jk -> <Esc>` in insert mode, after pressing `j` the character won't be inserted until another key is pressed or the timeout finishes (in the mean time there will be a TextEditorDecoration showing a 'j' to give feedback to the user).

The problem is if while waiting for timeout the user presses a keybinding that is bound directly to a command (like the TAB key, or pressing `alt+s` in markdown to make the text be strike through or any other key that doesn't trigger the `type` command or isn't one of our bound keys) then we will not know that the user just pressed a key, so the timeout will eventually finish and we will run the key that was waiting.

Example:
- In insert mode with the remap `jk` -> `<Esc>`
- The user types `proj` and the autocompletion widget shows up (notice however that the `j` wasn't actually inserted yet since it was a potential remap, the document currently has the text `pro` with a `j` shown has a TextEditorDecoration)
- The user presses TAB to autocomplete to `project`
- Vim won't know about that TAB keypress, so the timeout will finish and a `j` will be inserted resulting in `projectj`

If we could send a key back to vscode, we could add TAB to our bound keys meaning that when the user pressed TAB we would know about that keypress that broke the potential remap (since `j<Tab>` wasn't remapped) and then we would insert 'j' and send the TAB key back to vscode, which would then run the `acceptSelectedSuggestion` on a document that now has the text `proj` resulting in `project`.
