### ISSUE TITLE
Recently Used Tasks list is not updated anymore

### ISSUE THREAD

**Issue by s-kipnis** [microsoft/vscode#104817]
- 1.48.0
- Ubuntu 20.04

Steps to Reproduce:

1. Ctrl-Shift-B: Run any task except first one.
2. Ctrl-Shift-B: No changes in the list 'recently used task'.
Previously last executed task had been moved at the top of the list.

Killing caches and workspace in home/.config/Code doesn't help too, just recently used task list disappears fully

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Duplicate of #104714
