### ISSUE TITLE
Some unexpected issue

### ISSUE THREAD

**Issue by denissabramovs** [microsoft/vscode#104821]
Issue Type: <b>Bug</b>

**It said, that it was not responding for 5 mins.**

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.4.0-42-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 3819)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 3, 2|
|Memory (System)|31.22GB (14.14GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|11.3.1
sort-imports|ama|6.2.0
mergetool-navigator|aps|0.1.0
prettier-vscode-standard|bys|0.22.1
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.36.3
mustache|daw|1.1.1
vscode-eslint|dba|2.1.8
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.1.3
vscode-yarn|gam|1.7.1
bettercomment|Gru|0.0.9
todo-tree|Gru|0.0.178
beautify|Hoo|1.5.0
intellij-idea-keybindings|k--|0.2.41
linecounter|lyz|0.2.7
git-graph|mhu|1.25.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|4.1.20200816
debugger-for-chrome|msj|4.12.9
vscode-yaml-sort|Pas|2.3.1
linesinfostatusbar|pet|0.0.3
typescript-hero|rbb|3.0.0
vscode-yaml|red|0.9.1
prettier-now|rem|1.4.9
addDocComments|ste|0.0.8
go-to-method|tri|0.2.0
alphabetical-sorter|ue|2.0.1
vscode-todo-highlight|way|1.0.4
disable-eslint-rule|Woo|0.0.2
sort-js-object-keys|zen|1.0.6
file-size|zh9|0.1.3

</details>

**Comment by denissabramovs** [comment]
This is a duplicate or not enough info?

**Comment by denissabramovs** [comment]
Server is not responding...

**Comment by isidorn** [comment]
Please provide exact reproducable steps and we will reopen, thanks

**Comment by denissabramovs** [comment]
Huh? Your dialog poppen on it's own, saying that your server was not-responsive for 5 or more minutes. How do you think i can reproduce it myself if it's done automatically on the background? :)
