### ISSUE TITLE
VS Code Source control panel locked

### ISSUE THREAD

**Issue by alonfai** [microsoft/vscode#104806]
Hey,

I'm using the latest stable build of vs code and notice an issue with the source control side panel.

My current settings:

Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Use git installed globally using `homebrew`
2. Have several Git repos (both typescripts but different version) inside a given workspace. I'm using 4 together but seen this occurs also in 2 repos only.
2. Modify one or more files in a repo, and then try to add/commit/undo changes inside the source control sidebar.

I noticed that changes aren't reflected inside the repo (modify/added a new file) and aren't shown as untracked change. Instead, it keeps showing as loading/refreshing in the background.

P.S. I noticed it only in the latest vs code release (ver: 1.47 and below it was working without issues)

Does this issue occur when all extensions are disabled?: Yes

Any help will be appreciated (at the moment I'm just using a standard terminal or SourceTree to bypass this issue)

**Comment by joaomoreno** [comment]
Can you show me the full output of `Git: Show Git Output`?
