### ISSUE TITLE
Run Build Task command doesn't show warning messages on Zen Mode

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#104869]
- VSCode Version: 1.48.0
- OS Version: macOS Catalina

I'm developing an extension (like https://github.com/alefragnani/vscode-read-only-indicator for instance), so I use a `npm watch` task to build the extension, which is described in `package.json` as:

```json
    "scripts": {
      "watch": "webpack --watch --mode development --info-verbosity verbose"
    }
```

Steps to Reproduce:

1.Enter on Zen Mode
2.Run a Task: `Task: Run Build Task`
3.Run the same task again
4.It should show a notification message to `Terminate` or `Restart` the task, but it doesn't
5.Exit Zen Mode
6.Run the same task again
7.Now it shows the warning message

This is the message I'm talking:

![Screen Shot 2020-08-17 at 19 06 40](https://user-images.githubusercontent.com/3781424/90448987-da599980-e0bc-11ea-935f-99c80897e5c4.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is due to the reason that zen mode hides all notifications except errors.
@alexr00 I believe we should change that notification to be an Error, or at least a Warning

**Comment by alexr00** [comment]
@isidorn thanks for the info about zen mode!

**Comment by alefragnani** [comment]
Hi @isidorn ,

Thanks for the info. I thought it would indeed be _by design_. Great to see it would work simply changing the notification to be a _Warning_.

I decided to play again with the settings, and now I found `"zenMode.silentNotifications"`. Turning it to `false` made the notification appear. I'm not sure this setting could/should be updated to allow user to decide which kind of notification could be silenced, but that's another idea. 

Thank you

**Comment by isidorn** [comment]
I am not sure if it will work for warning, but for sure it will work for errors. I can make a change in zen to also show warning - have to decide on that.

I would not change the default of that setting, since the point of zen mode is to not be disturbed and thus to see less notificaitons.

**Comment by alexr00** [comment]
The tasks message should be a Warning, not an Info. It also doesn't make sense as an Error since it isn't actually an error. I have updated it to be a Warning. I will leave it up to @isidorn whether warnings should be shown in zen mode.

**Comment by isidorn** [comment]
It makes sense to change it to a wanring. 
For now I would not change zen mode, since none of the users complained that they miss warning notificaionts in Zen mode. And I still think users should only be bothered with Errors.

Of course I am open to reconsider in the future when we get more feedback from users.

**Comment by alefragnani** [comment]
No need to change Zen mode. The `zenMode.silentNotifications` setting worked perfectly for me.

Changing this message to _warning_ also helps, because users will probably pay more attention 😁.  

Thank you

**Comment by isidorn** [comment]
Thank you for sharing your feedback.

**Comment by aeschli** [comment]
Verified that the message is a warning now
