### ISSUE TITLE
[monaco-editor-core] Language diagnostics cannot be changed after the first language change.

### ISSUE THREAD

**Issue by RoboPhred** [Microsoft/vscode#10483]
The monaco-editor repository indicates monaco-editor-core issues should be reported here.  Please let me know if this is the right place.

vscode version: Monaco Editor Playground

Steps to reproduce:
1.  Configure the editor to switch between 2 languages on command
2.  Provide valid code in one of the two languages.
3. Switch to the other language, make note of the error decorators that appear.
4.  Switch back to the original language.

Expected behavior:
The editor should reevaluate the language and remove the error decorators from the old language.

Actual behavior:
After the second language switch, the error decorators from the old language remain, and new code is still treated as the second language for diagnostics.

This can be reproduced at the [monaco editor](https://microsoft.github.io/monaco-editor/playground.html) with the following code
```
// validation settings
monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
	noSemanticValidation: true,
	noSyntaxValidation: false
});

// compiler options
monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
	target: monaco.languages.typescript.ScriptTarget.ES6,
	allowNonTsExtensions: true
});


var jsCode = 'const foo = 42;';

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});

editor.addAction({
    id: "lang_js",
    label: "lang to js",
    run: () => {
        monaco.editor.setModelLanguage(editor.getModel(), "javascript");
    }
});

editor.addAction({
    id: "lang_json",
    label: "lang to json",
    run: () => {
        monaco.editor.setModelLanguage(editor.getModel(), "json");
    }
});
```
To cause the issue, invoke the "lang to json" action, then the "lang to js" action.  The json language will flag const as "Expected a JSON object, array, or literal".  This error will remain even when the language is switched back into javascript.  Additionally, any additional code typed into the editor will always be processed with json, regardless of which language is set.

**Comment by jrieken** [comment]
This issue was moved to Microsoft/monaco-editor#111
