### ISSUE TITLE
Keyboard Shortcuts Settings UI: Add columns for co

### ISSUE THREAD

**Issue by robole** [microsoft/vscode#104831]
If you want to add a shortcut that uses an editor action such as `insertSnippet`, in the Settings UI there is no way to differentiate between them. The `command` and `when` clauses can be identical, however the actions are totally different based on the command `args`. Could you display this as part of the command description, or a separate column?

For example, to have shortcuts for the built-in markdown snippets for "Insert bold text" and "Insert italic text", you can see how it appears in the Setting UI and in *keybindings.json* below

![keyboard](https://user-images.githubusercontent.com/3703647/90410772-59f76080-e0dd-11ea-9823-f13f17fcdffa.png)

**keybindings.json**
```json
[
  {
        "key": "ctrl+b",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus && editorLangId == markdown",
        "args": {
          "langId": "markdown",
          "name": "Insert bold text"
         }
    },
   {
        "key": "ctrl+i",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus && editorLangId == markdown",
        "args": {
          "langId": "markdown",
          "name": "Insert italic text"
        }
  }
]
```

This makes it difficult for sharing shortcuts for these kind of actions as part of an Extensions. The only alternative is to make your own commands for this, which requires redefining the snippets through the method `insertSnippet(snippet: SnippetString, location?: Position | Range | ReadonlyArray<Position> | ReadonlyArray<Range>, options?: {undoStopAfter: boolean, undoStopBefore: boolean}): Thenable<boolean>` of [TextEditor](https://code.visualstudio.com/api/references/vscode-api#TextEditor), uness there is another way? In any case, its difficult to make it clear to the user what similar shortcuts actually represent.

**Comment by sandy081** [comment]
/duplicate

#84072
