### ISSUE TITLE
[vb] syntax highlighting for "End Property" and "End Class"

### ISSUE THREAD

**Issue by dlbjr** [Microsoft/vscode#10481]
- VSCode Version: Code - Insiders 1.5.0-insider (e9c80f036645caae7759b3954fc72dbe6c644edf, 2016-08-12T06:07:39.195Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1. Open a VBScript with a class defined in it
2. The "End Property" and "End Class" Statements are not being recognized as reserved words and turning blue as expexted.

**Comment by chrisdias** [comment]
@aeschli this PR was accepted, will you pick up a new bundle?
