### ISSUE TITLE
Editor IME break when using selection inside IME

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#10484]
- VSCode Version: Code - Insiders 1.5.0-insider (e9c80f036645caae7759b3954fc72dbe6c644edf, 2016-08-12T05:59:43.814Z)
- OS Version: Linux x64 4.4.0-31-generic, Ubuntu 16.04 with Japanese iBus IME

Steps to Reproduce:
1. Turn on Japanese IME
2. Type "this" (てぃs)
3. ctrl+shift+left
4. Type "this" again, you get this:
   
   ![image](https://cloud.githubusercontent.com/assets/2193314/17630784/adc37678-6075-11e6-8b70-899fee0d82eb.png)

I think the ideal fix for this is to disable selection while an IME composition is happening.

**Comment by alexandrudima** [comment]
I cannot reproduce on Windows when typing `sennsei` => `せんせい`

**Comment by rebornix** [comment]
@Tyriar I can't reproduce this issue in latest Insider with Japanese iBus IME on Ubuntu 16.04, can you help verify?

**Comment by Tyriar** [comment]
Seems fixed now
