### ISSUE TITLE
NPM SCRIPT EXPLORER doesn't show up anymore

### ISSUE THREAD

**Issue by badB00l** [microsoft/vscode#104848]
Issue Type: <b>Bug</b>

I updated VS code and NPM SCRIPT EXPLORER is gone!
I tried to go to the settings and reactivate it again, uninsatll an reinstall  but nothing happens.

the option to be put in the settings is npm.enableScriptExplorer

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.4.0-42-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 4285)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 4, 4|
|Memory (System)|15.51GB (2.09GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
ng-template|Ang|0.1000.7
vscode-eslint|dba|2.1.8
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
auto-rename-tag|for|0.1.4
code-runner|for|0.11.0
gitlab-workflow|Git|3.2.0
git-graph|mhu|1.25.0
vscode-docker|ms-|1.4.1
mssql|ms-|1.9.0
debugger-for-chrome|msj|4.12.9
angular-follow-selector|san|1.2.0
sonarlint-vscode|Son|1.17.0

</details>

**Comment by andrewortwein** [comment]
I'm seeing the same thing, but only for workspaces where I don't have a top-level package.json file.
