### ISSUE TITLE
"for"-template not initially selected

### ISSUE THREAD

**Issue by johanneskopf** [Microsoft/vscode#10488]
- VSCode Version: 1.5.0-insider
- OS Version: Windows 10, Build 14901

Steps to Reproduce:

1. Open a c# file
2.  Write "for"
3. You have to press (Down) and (Tab) to use the "for"-template, it's not possible to write "for" and press (Tab) to use that template on the go.
Selecting the template initially would speed up coding.

![opened_single_file_for](https://cloud.githubusercontent.com/assets/13490371/17638274/4da34c2c-60e9-11e6-8780-eaf33d22b8dc.png)

![opened_solution_for](https://cloud.githubusercontent.com/assets/13490371/17638275/5064cbf2-60e9-11e6-98d3-5c24bd8ffdf6.png)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#659

**Comment by ivanz** [comment]
@johanneskopf This is not a bug - as of VSCode 1.4 `"editor.snippetSuggestions": "top"` can be used to change the default VSCode behavior.

**Comment by johanneskopf** [comment]
Thanks for the hint!
It's working great using that setting.
