### ISSUE TITLE
File transfer information

### ISSUE THREAD

**Issue by Syntle** [microsoft/vscode#104861]
I often transfer files to/from my server while being connected to it through SSH on VSCode, the issue is I can't see a list of the files being transferred or any progress info about the transfer.

It would be very helpful to know certain things like:
  - List of files being transferred
  - Progress of current file being transferred
  - Download/upload speed
  - Transfer ETA

**Comment by isidorn** [comment]
Somewhat a duplicate of progress for long running operations. We would not add anything specific to SSH, and due to that closing this as a duplicate https://github.com/microsoft/vscode/issues/73996
