### ISSUE TITLE
Find/Next Previous in Files List loses list position after making edit.

### ISSUE THREAD

**Issue by chris-mullins** [microsoft/vscode#104862]
Steps to Reproduce:
These steps probably work in all languages, it seems to happen when you make an edit that causes the language server to run. But lets do it in typescript.

1.  Find Text in Find files: Choose a function that appears in at least 4 or 5 files
2.  Go to a match in the middle of the list and click it or use Find/Next hotkey to select it.
3.  Add and remove a parenthesis from the function
4. Go to the next result Using the hotkey for **Search: Focus Next Search Result (search.action.focusNextSearchResult)**
5. It jumps back to the First item in the Find list

I have noticed this issue for a long time.  In Visual Studio I found it very helpful to search for something and using the keyboard jump through the search list make and edit, and move to the next seamlessly, but I can't do this in VS Code due to the fact that the list focus resets back to the top.  

Here is a recording of the issue using the steps above
https://recordit.co/hV2DonylTM

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/20467
