### ISSUE TITLE
Unable to open a file from search results.

### ISSUE THREAD

**Issue by deepanjyoti-sarkar** [microsoft/vscode#104878]
We have written the needed data into
Issue Type: <b>Bug</b>

1. Open a folder (a \\UNC path0 with a lot of log files with VSCode.
2. Search in the folder (Ctrl + Shift + F) for a specified text.
    --> This gives a list of results which match the text.
3. Open the search results in editor for a clearer preview of all hits.
4. Try to click on one of the preview of the hits with an intent to go to the specific file & specific line.
     Expected : This used to work in previous versions.
     Observed : Its broken with the latest update. It fails with

Unable to open 'filename': Unable to read file 'full UNC path to the file' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat 'full UNC path to the file').

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.75GB free)|
|Process Argv|\\hcssrvd35\logs\chsingla\0817\TMA-Dumps-Restart\SupportPackage\DVM1577-00023-200817-1054\VM1577-00023\hcslogs|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
CppSnippets|har|0.0.14
csharp|ms-|1.23.0
sarif-viewer|MS-|2.14.0
azure-account|ms-|0.9.2
cpptools|ms-|0.29.0
mono-debug|ms-|0.15.8
powershell|ms-|2020.6.0
team|ms-|1.161.0
usql-vscode-ext|usq|0.2.15
vscode-icons|vsc|10.2.0

</details>
 your clipboard because it was too large to send. Please paste.

**Comment by JacksonKearl** [comment]
Could you share a screenshot of the editor? In particular what the paths look like (and, if possible are they different from before)
