### ISSUE TITLE
It would be nice to have the terminal under the file explorer

### ISSUE THREAD

**Issue by simkessy** [microsoft/vscode#104897]
Something like this
![image](https://user-images.githubusercontent.com/5871660/90481051-f9b8ec80-e0e5-11ea-8d08-caa99570040c.png)

**Comment by isidorn** [comment]
This is possible, just use drag and drop
![Screenshot 2020-08-18 at 09 30 46](https://user-images.githubusercontent.com/1926584/90483771-82ab4480-e135-11ea-993f-ebe9ed880447.png)

**Comment by simkessy** [comment]
Mind blown
