### ISSUE TITLE
bookmarks support

### ISSUE THREAD

**Issue by ArtechChu** [microsoft/vscode#104881]
shortcut and function example like below:
CTRL+SHIFT+1:create a bookmark，eg：bookmark1
CTRL+1:go to bookmark1

CTRL+SHIFT+2:create a bookmark，eg：bookmark2
CTRL+2:go to bookmark2
...
CTRL+SHIFT+9:create a bookmark，eg：bookmark9
CTRL+9:go to bookmark9

**Comment by ArturoDent** [comment]
Are you using a bookmarks extension or are you asking that that functionality be built in to vscode?

**Comment by ArtechChu** [comment]
> Are you using a bookmarks extension or are you asking that that functionality be built in to vscode?

yep,I'm using the [booksmarks](https://github.com/alefragnani/vscode-bookmarks.git) extension.
I hope it can be built in to vscode and extend the funtion like the bookmarks supported by resharper.(bookmarks supported by resharper in visual studio is very efficent)
