### ISSUE TITLE
Unable to open 'Settings': Horizontal scrolling and dynamic heights not supported simultaneously.

### ISSUE THREAD

**Issue by brl0** [microsoft/vscode#104843]
Issue Type: <b>Bug</b>

1. Open File menu
2. select Preferences
3. select Settings

VS Code version: Code - Insiders 1.49.0-insider (652a432f59f54733bf17b79c9f2b7a925971a53d, 2020-08-17T10:50:00.911Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3396)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (22.82GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 3b8664e8-e19f-42a3-9b14-8df59e843638|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by roblourens** [comment]
Oh, I see this when horizontal scrolling is enabled. Thanks
