### ISSUE TITLE
Save and Save As function do not work, they do not do anything

### ISSUE THREAD

**Issue by brosenheim** [microsoft/vscode#104851]
Issue Type: <b>Bug</b>

If I change code I am writing in a Jupyter notebook, I see that the editor knows I have made changes (there is a * appended to the visible file name), but it will not allow me to save or save as.  Save is not an option - I cannot even select that from the drop down menu.  Save as is an option, but absolutely nothing happens.  No dialog box, no error message, nothing.  When I close VSCode, I am prompted to save the file, but the changes are not saved.  Obviously this is very disruptive for developing new code.  I am running Windows 10 on a SurfacePro 3 and I am saving to a network drive.  My version of VSCode is:
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.8.101144

</details>

**Comment by rebornix** [comment]
/extPython

Please file issue against the Python extension which is currently providing the notebook feature through the webview.
