### ISSUE TITLE
`vscode.workspace.findTextInFiles` include pattern doesn't match a single file

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#104849]
Refs: https://github.com/microsoft/vscode/issues/102873#issuecomment-674999289

Steps to Reproduce:

1. Run a `this.vscode.workspace.findTextInFiles` and have an include pattern that matches a single file / without glob characters, e.g.

![](https://memes.peet.io/img/20-08-1f033997-e646-4e5e-850b-4e6152345bdc.png)

2. The search doesn't produce any results 🐛 
3. Running the same search in the search view works

![](https://memes.peet.io/img/20-08-a339d6ce-10b8-4596-a39b-aa6f1e1ee553.png)

**Comment by roblourens** [comment]
This works on mac, on windows the search returns results but the results do not make it to the search result callback. I think they are probably getting caught by some glob post-processing I do. But there is a general issue where our search model/api doesn't really work for targeting individual files. Part of https://github.com/microsoft/vscode/issues/20530. Is this blocking something in js-debug?

**Comment by connor4312** [comment]
No, not blocking. For js-debug I think it is super rare (and generally not desirable) to target a single file in the glob pattern. I wanted to report it though since a user indirectly brought it up .

**Comment by roblourens** [comment]
I'll call it a dupe of that issue
