### ISSUE TITLE
Install borked after user profile+directory rename

### ISSUE THREAD

**Issue by EzraEn1** [microsoft/vscode#104826]
Issue Type: <b>Bug</b>

Due to an extension handling spaces in profile directories badly (gradle-tasks), I was forced to rename my user folder and profile in order to get it to run. Ironically, this has created complications for many other aspects of VSCode, including screwing up the Installer, All the Open in Code context menu actions, as well as updating VSCode as a whole. Not sure how to fix this, as Gradle is a huge part of the projects i'm working with right now, and reverting my user profile change is going to be a hassle.

How to Reproduce:

1. Be me on a clean Windows install. Have a space in your name when creating your local profile (not a Microsoft account)
2. Install VSCode - Insiders (unknown reproducibility on stable)
3. Follow [this tutorial](https://www.tenforums.com/tutorials/89060-change-name-user-profile-folder-windows-10-a.html) to rename your profile. 
4. Check for updates, or even run VSCode's installer again. Find that everything is still stuck on old profile directory.

Expected Result: No problems using context menu, updating

Reality: Broken VSCode context menu items, unable to update or run installer
![image](https://user-images.githubusercontent.com/7076802/90406956-7513a180-e0d8-11ea-9c5b-f78c8ea93e0e.png)

VS Code version: Code - Insiders 1.49.0-insider (bd08768fd310d34cdd4423a53e5f3ca77340fea5, 2020-08-14T05:56:40.601Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.35GB free)|
|Process Argv|--crash-reporter-id 53f2a398-977c-4e96-9d8a-9a197cf47730|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.1.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.36.3
githistory|don|0.6.9
gitlens|eam|10.2.2
vsc-material-theme-icons|equ|1.2.0
kotlin|fwc|0.2.18
vscode-pull-request-github|Git|0.19.0
todo-tree|Gru|0.0.178
vscode-peacock|joh|3.8.0
restructuredtext|lex|129.0.0
Kotlin|mat|1.7.1
git-graph|mhu|1.25.0
python|ms-|2020.8.101144
remote-wsl|ms-|0.44.4
vsliveshare|ms-|1.0.2619
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
gradle-language|nac|0.2.3
material-icon-theme|PKi|4.2.0
java|red|0.65.0
vscode-gradle|ric|3.4.2
vscode-gradle-extension-pack|ric|0.0.2
swdc-vscode|sof|2.2.48
sonarlint-vscode|Son|1.17.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.11.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.1
vscode-maven|vsc|0.24.0
vscode-icons|vsc|10.2.0
vscode-import-cost|wix|2.12.0
markdown-all-in-one|yzh|3.2.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
