### ISSUE TITLE
Horizontal pane in diff comparison

### ISSUE THREAD

**Issue by jpfreire** [microsoft/vscode#104855]
Adding horizontal view in diff-editor would  be a better feature than just rotating vertical split( #26856). Like the way Winmerge do it. 
Side buttons to collapse either vertical/horizontal panes would be a plus.

![WinMerge-interface](https://user-images.githubusercontent.com/820623/90428856-fe0be800-e09a-11ea-84e2-67a2261ed821.png)

**Comment by ArturoDent** [comment]
Just in case you don't know it, there is an `inline` option setting `Diff Editor: Render Side By Side` which at least gets you a "vertical" look rather than the side-by-side default.  Perhaps you will find it helpful.  You can't get both with it if that is what you are looking for.

**Comment by Nadano** [comment]
What about this solution?

https://github.com/microsoft/vscode/issues/103285
