### ISSUE TITLE
Old Pull/Push/Stash Git View Menu Option

### ISSUE THREAD

**Issue by smaglio81** [microsoft/vscode#104850]
I've worked with the "New Git View submenus" for a few days (maybe a week) now, and I am really not liking it. (https://code.visualstudio.com/updates/v1_48#_git-overflow-menu-cleanup)

Is there an option to go back to the single menu?

**Comment by IllusionMH** [comment]
Looks like duplicate of #104762

Could you check it and see if your request covered there?

**Comment by smaglio81** [comment]
Thank you. Definitely a duplicate (#104762).
