### ISSUE TITLE
TextEditorSelectionChangeKind on selection change events is sometimes 'undefined'

### ISSUE THREAD

**Issue by berknam** [microsoft/vscode#104856]
- Version:
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. When you press \<tab\> to insert a snippet it results in a selection change event with kind 'undefined' (shouldn't it be 'Keyboard'?)
2. If you then press \<tab\> again to `jumpToNextSnippetPlaceholder` it results in a selection change event with kind 'keyboard'

Also if you press `<DownArrow>` or `<Shift+DownArrow>` it results in kind `Keyboard` as it should but if you call the corresponding commands from an extension for example with `executeCommand` it also gets kind `Keyboard`, but shouldn't it be `Command`.

This is a little bit hard to make sense of this 'Kind' attribute, because if you press a keybinding that is set to `editor.action.smartSelect.grow' that gets kind 'Command' even though you pressed the keyboard to do that. I thought 'Keyboard' was like command or action resulting from a user pressed key or key combination and 'Command' was an actual command executed from other command or extension.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Yeah, it can be undefined has stated here: https://github.com/microsoft/vscode/blob/6445a9633d428e0879d172d4f392c542ba887768/src/vs/vscode.d.ts#L539-L543

**Comment by berknam** [comment]
@jrieken Can you explain to me the logic behind kind a little bit better. Like when is it supposed to be `Keyboard` instead of `Command`.

Because like I mentioned there are situations where you type a key and get kind `Command` and situations where you call a command with `executeCommand` and you get kind `Keyboard`.
