### ISSUE TITLE
Add "(approximate)"  to TS partial mode hovers / IntelliSense

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#104859]
Follow up on https://github.com/microsoft/TypeScript/pull/40061

/cc @DanielRosenwasser

**Comment by mjbvz** [comment]
Here's what this now looks like:

<img width="992" alt="Screen Shot 2020-08-17 at 5 49 03 PM" src="https://user-images.githubusercontent.com/12821956/90457987-f441af00-e0b1-11ea-912a-7a164f2ab75d.png">

For verification:

1. Open the VS Code workspace
1. Open a TS file
1. While the status bar loading indicator is showing, hover over a variable
     - Confirm `(loading...)` is shown in the hover
1. Now wait for TS to finish loading.
1. Hover again 
     - Confirm that there is no longer any `(loading...)` indicator

Also test hover in the serverless cases. This should never display `(loading...)` since we will never load the full server

**Comment by DanielRosenwasser** [comment]
Looks good! I'm a fan and agree with the serverless mode behavior.

**Comment by jrieken** [comment]
Verified but I would have preferred to see some pretty codicon, like the loading codicon
