### ISSUE TITLE
explorer window new file, no focus

### ISSUE THREAD

**Issue by joshua-agee** [microsoft/vscode#104865]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

right clicking in the explorer sidebar, choosing new file, a new file appears with a box to enter the name, but it doesn't get focus immediately as expected - you must explicitly click it again to enter text.  

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|2.8.3
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
vscode-firefox-debug|fir|2.9.0
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
search-node-modules|jas|1.3.0
python|ms-|2020.8.101144
hexeditor|ms-|1.2.1
vsliveshare|ms-|1.0.2619
sqltools|mtx|0.22.11
sqltools-driver-mssql|mtx|0.1.0
sqltools-driver-sqlite|mtx|0.1.0
indent-rainbow|ode|7.4.0
geo-data-viewer|Ran|2.1.0
markdown-preview-enhanced|shd|0.5.13
code-spell-checker|str|1.9.0
highlight-matching-tag|vin|0.9.9
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Works for me. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
