### ISSUE TITLE
[html] auto remove closing-tag

### ISSUE THREAD

**Issue by fuweichin** [microsoft/vscode#104891]
When editing markup language files like HTML, XML, JSX, if I type `/` before opening tag's `>` of an empty element (clearly I want to make it self-closing), then I want VSCode auto-removing the closing tag.

For example, If I type `/` on `<Foo |></Foo>` (assuming `|` is the cursor), then I want `<Foo />` rather than `<Foo /></Foo>`

There are already 'expanding' content assistant features like Emmet, why not a 'collapsing' content assistant features like this, if neccessary.

**Comment by aeschli** [comment]
That's an interesting idea. I would be great if an extension author can implement it so we can get some experience with it.
