### ISSUE TITLE
Reusing repo README for marketplace is restrictive; add an option

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10485]
Apologies if this is the wrong place for this...

The docs for the manifest file state:

> Have a README.md Markdown file in your extension's root folder and we will include the contents in the body of the extension details (on the Marketplace). 

I recently got some comments that the Readme for my extension on GitHub is not very good to tell people what the project. I could add this to the top of the README, but it's redundant on the marketplace (as is installation instructions, which currently appear twice because I have them in my readme).

It would be great to have the option of using a different file than the same readme that GitHub will show on a repo page. That way, the GitHub-displayed README.md could explain what the project is and how to install it, whereas the marketplace-displayed file could omit this stuff (people on the marketplace or inside Code already know it's an extension and how to install it).

**Comment by joaomoreno** [comment]
Won't fix any time soon. Sorry.
