### ISSUE TITLE
Expected Publish to be in Pull/Push menu

### ISSUE THREAD

**Issue by kaylfc** [microsoft/vscode#104818]
Hey guys,

When pushing to a new remote branch, the usual popup appears to say do you want to publish to an upstream branch. I therefore would previously skip one step and directly Publish from the menu.
With the new nested menus, intuitively I expected Publish to be in the Pull/Push menu as publishing to me is related to pushing. I understand why its in the Branch menu but there is a use case for it being under Pull/Push too.

Cheers

---
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
This is why we have the command palette: so you can find the command no matter where it is.
