### ISSUE TITLE
Manual Extensions Updating: streamlined UX to see outdated list and Changelogs

### ISSUE THREAD

**Issue by myfonj** [microsoft/vscode#104825]
## Proposal:
**§A**: successful manual extensions **update check opens** Extensions sidebar with **`@outdated`** filter active, 
**§B**: primary action of extension tile in `@outdated` sidebar filter opens **Changelog** content tab.

## User story:
As a user having extension Auto Updating turned off in order to check all release notes, I'd like to reach "Changelog" tab as quick as possible. _Extensions: Check for Updates_ action presents me list of available updates immediately. Clicking extension tile then presents me its Changelog.

## Motivation:
Current flow of actions for given user story is
1) Having Extension pane open, auto updates disabled.
2) Invoke `…` (_Views and More actions…_) > _Check for Extension Updates_ (or invoke corresponding action from Command Palette).
3) (Extension filter resets to "" what is currently equivalent of `@installed` [0])
4) **Enter `@outdated` query into search field.** [1]
5) Select outdated extension.
6) **Switch to Updates tab** .
7) Repeat 4) and 6) for next results.

This proposal removes necessity for step 4) and (repeated) step 6).
Step 4) is currently crucial in case user has many "pages" of installed extension. It is solved by proposal §A.
Step 6) is predictable as well, solved by proposal §B.

## Counterarguments / Discussion
§A might seem like unrequested side effect, but since current behaviour (described in note [0]) does something similar or even worse, it does not seems to be much a concern anyway.
§B might be problematic because it changes "default action" so it breaks consistency principle. I think in this case it is excusable, because given context (`@outdated` filter in effect) can be considered as clear signal of user's preference to see Updates tab, not default Description.

---

### Notes
[0] This filter reset always felt weird, considering user might have `@outdated` (or other) filter active before invoking update check but ends up losing it. This apparently breaks "least surprise" and "no unexpected side effect" UX recommendations.
[1] Side note:  <del>there seems to be no visual entry for this filter value after 1.48.0 in new `…` (_Views and More actions…_) menu. There does not seem to be filed bug for this at this moment.</del><ins>NM, moved to funnel button to the left of "..." button.</ins>

**Comment by sandy081** [comment]
I am sorry that I did not understood the problem and proposed solution. 

I do not see this happening `(Extension filter resets to "" what is currently equivalent of @installed [0])`

What do you mean by `Switch to Updates tab` ?

Is it possible to provide a gif of the issue you are seeing?
