### ISSUE TITLE
Visual Studio Code Crashes on Startup on Lubuntu 19.10

### ISSUE THREAD

**Issue by Tom-KK** [microsoft/vscode#104814]
VSCode could not start from one moment to the next and crashs on startup.

- VSCode Version: 1.49.0-insider
bd08768fd310d34cdd4423a53e5f3ca77340fea5
x64
- OS Version: LUbuntu 19.10

Steps to Reproduce:

1. I start Visual Studio Code
2. Programm starts and I see the Visual Studio Code Editor for about 1 Secound  (no file is open)
3. After about 1 Secound Visual Studio Code close

Il tryed various things:
> Start with '--disable-extensions' parameter
> Start with '--disable-extensions --max-memory=12288mb' parameter
> completely delete the App Directory for resetting default settings

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tom-KK** [comment]
https://youtu.be/sw3jAtKIKrw

**Comment by deepak1556** [comment]
Sorry for the delayed response, are you using the snap build of vscode ?

**Comment by Tom-KK** [comment]
Yes

**Comment by deepak1556** [comment]
thanks, this is a known crash tracked here https://github.com/microsoft/vscode/issues/103060. A solution is being worked on, in the meantime you can use the deb package. Merging to the linked issue.
