### ISSUE TITLE
无法使用设置同步

### ISSUE THREAD

**Issue by hanhua1994** [microsoft/vscode#104875]
设置-打开设置同步-出现弹窗点击打开-设置同步选项点击登录并打开，之后就没有任何反应了

**Comment by xiaocao162020** [comment]
Dear @vscode-triage-bot and other collaborators of the visual studio code, 
here is the translation of the issue.


>### Title: I cannot set the sync function of the vscode.
>**Content: I went to "Settings - Turn on Sync", and there is a message box, I opened it, and clicked"turn on", and to"Sync Settings - Login and Turn on", and the Visual Studio Code stopped replying to my action. (Which means it didn't redirect to any websites, nor did it appear a message box.**

I translated by myself and there might be some grammar mistakes, or even offensive. Please forgive me if that really happens. Thank you.

Xiaocao162020,[contact](mailto:xiaocao162020@xiaocao.onmicrosoft.com?subject=From%20the%20vscode%20issues)
