### ISSUE TITLE
Give a file with the name UNLICENSE the license icon

### ISSUE THREAD

**Issue by emilengler** [microsoft/vscode#104812]
Many projects that use [The Unlicense](https://unlicense.org) have a file in their repository called UNLICENSE. I would suggest that it also has the license icon like files with the name LICENSE and COPYING do.

**Comment by emilengler** [comment]
By the way, the official website (link above) also suggests to use a file called UNLICENSE rather than COPYING or LICENSE

**Comment by aeschli** [comment]
I assume this is for the Seti theme, https://github.com/jesseweed/seti-ui is the right place for this. I see you have filed an issue there. We will pick the change up once changes are made on https://github.com/jesseweed/seti-ui
