### ISSUE TITLE
Client should retry the request when receiving 409

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#104834]
Client should retry the request when receiving a `409` and `412`  from the server.

**Comment by sandy081** [comment]
@Tyriar FYI

**Comment by misolori** [comment]
We should also update the error message. From a user's perspectives, these mean nothing and don't provide any guidance.

![image](https://user-images.githubusercontent.com/35271042/90415880-9340b980-e066-11ea-946a-0871ad79c0e4.png)

![image](https://user-images.githubusercontent.com/35271042/90415890-963baa00-e066-11ea-9420-284d2d178865.png)

**Comment by sandy081** [comment]
@misolori These message are not supposed to be surfaced to user. Currently `412` error is handled and retried without bailing out. Can you please provide the settings sync log when you saw `412` ?

**Comment by misolori** [comment]
@sandy081 sorry I wasn't able to retrieve those logs, I'll see if it appears again.

**Comment by sandy081** [comment]
Reopening for candidate discussion

**Comment by sandy081** [comment]
@misolori I would recommend to file a separate issue for 412 scenario you are seeing.

**Comment by isidorn** [comment]
Fix looks good, adding verified label.
