### ISSUE TITLE
Settings UI thinks v3 / js-debug is disabled by default

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/vscode#104839]
Issue Type: <b>Bug</b>

1. Load the settings UI
2. Observe that the default value for all the "Debug > XYZ: Use V3" options is false
3. Observe that the V3 / js-debug extension is in fact enabled by default for at least some of these, despite showing as being not in use

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.7.0-2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 2242)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|31.27GB (3.61GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.5.0
Bookmarks|ale|11.3.1
markdown-preview-github-styles|bie|0.1.6
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.1.3
go|gol|0.16.1
beautify|Hoo|1.5.0
vscode-peacock|joh|3.8.0
vscode-styled-components|jpo|0.0.29
bash-ide-vscode|mad|1.10.2
openapi-lint|mer|1.2.0
vscode-docker|ms-|1.4.1
python|ms-|2020.8.101144
debugger-for-chrome|msj|4.12.9
vscode-yaml|red|0.9.1
lit-plugin|run|1.2.1
vscode-workspace-switcher|sad|1.15.1
vscode-nginx|sha|0.6.0
code-spell-checker|str|1.9.0
html-preview-vscode|tht|0.2.5
reflow-paragraph|Tro|1.3.0

(1 theme extensions excluded)

</details>

**Comment by mgabeler-lee-6rs** [comment]
This means you actually _can't turn it off_ via the settings UI, because turning it off in fact resets it to the default, so your choices are either implicitly enabled or explicitly enabled. To disable it requires editing `settings.json`

**Comment by roblourens** [comment]
@connor4312 should those settings be marked as deprecated? 

@mgabeler-lee-6rs the correct setting is debug.javascript.usePreview

**Comment by mgabeler-lee-6rs** [comment]
> the correct setting is `debug.javascript.usePreview`

And yet that is not the setting that is toggled in the UI, and the setting the UI toggles _does_ work ;)

**Comment by connor4312** [comment]
Yea, we should probably kill the `useV3` settings. It was useful when js-debug had wildly differing parity for different types of debugging, but usePreview is the way to go now.

**Comment by roblourens** [comment]
Yes @mgabeler-lee-6rs they have the wrong defaults, and should have the 'experimental' tag removed, and be marked deprecated. I missed updating those after we got moved onto the new setting. I'll do that, thanks for pointing it out.
