### ISSUE TITLE
Invisible(?) password prompts prevent text expansion on macOS (secure input issue)

### ISSUE THREAD

**Issue by finn-matti** [microsoft/vscode#104803]
Issue Type: <b>Bug</b>

**Original Description**

I originally raised this issue [here](https://github.com/SchoofsKelvin/vscode-sshfs/issues/211).

If there is an open secure input prompt left open for a long time, it seems that the box loses focus and/or becomes invisble - maybe leading to secure input not being disabled and in turn preventing tools like Keyboard Maestro or Text Expander from working.

Truth be told: The problem is hard to reproduce and my description is bad, however I'm certain this only happens while VS Code is open.

Thanks for looking into this.

**Reproducible steps (1... 2... 3...) that cause the issue**

Leave password input open for extended periods of time. Realize that the prompt vanished later. See that secure input is still activated.

**What you expected to see, versus what you actually saw**

If there is no password input box, secure input should be disabled.

**Errors from the Dev Tools Console (open from the menu: Help > Toggle Developer Tools)**

No error.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|-psn_0_139298|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
swagger-viewer|Arj|3.0.1
vscode-intelephense-client|bme|1.5.3
vscode-toggle-quotes|Bri|0.3.3
rona|Bru|1.0.1
liquibase-snippets|chr|1.3.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
indent4to2|Com|0.1.2
confluence-markup|den|0.1.8
codeception-snippets|die|0.0.4
githistory|don|0.6.9
xml|Dot|2.5.1
gitlens|eam|10.2.2
tslint|eg2|1.0.44
json-tools|eri|1.0.2
prettier-vscode|esb|5.1.3
php-debug|fel|1.13.0
json2ts|Gre|0.0.6
todo-tree|Gru|0.0.178
px2rem-plus|hex|0.3.4
error-gutters|Igo|1.0.1
composer|ika|0.7.1
vscode-codeception|joe|1.1.0
vscode-sshfs|Kel|1.18.2
duplicateselection|kka|1.0.1
expand-region|let|0.1.4
ts-extension-pack|loi|0.2.0
terminal-inplace|Map|2.0.2
rainbow-csv|mec|1.7.1
openapi-lint|mer|1.2.0
HTMLHint|mka|0.8.0
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.4.1
vscode-postgresql|ms-|0.3.0
python|ms-|2020.8.101144
debugger-for-chrome|msj|4.12.9
sqltools|mtx|0.22.11
vscode-versionlens|pfl|1.0.8
nested-comments|phi|2.3.1
tsimporter|pmn|2.0.1
savebackup|pur|0.0.4
bracketeer|pus|1.2.7
vscode-data-preview|Ran|2.0.0
typescript-hero|rbb|3.0.0
vscode-xml|red|0.13.0
vscode-yaml|red|0.9.1
code-settings-sync|Sha|3.4.3
gitconfig|sid|2.0.1
vscode-fileutils|sle|3.0.1
code-spell-checker|str|1.9.0
code-spell-checker-german|str|0.1.4
move-ts|str|1.12.0
shellcheck|tim|0.9.0
errorlens|use|3.2.0
sensitive-replace|vil|0.1.1
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|10.2.0
vscode-wakatime|Wak|4.0.0
vscode-todo-highlight|way|1.0.4
joinlines|web|1.1.1
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
php-sniffer|won|1.2.6
markdown-all-in-one|yzh|3.2.0

</details>

**Comment by finn-matti** [comment]
I tried to add some more info. If something else is missing: Please specify. Thanks!

**Comment by finn-matti** [comment]
Another observation: It seems that this happens when I wake my mac up and it might be connected the usage of VPN/network issues. When the mac is woken back up the network connection is not yet there (because the vpn is reconnecting) but the prompt to reconnect is already shown. I assume if I enter my password before the reconnect has happened that problem then arises. The last part is an assumption though...

**Comment by isidorn** [comment]
Forwarding to @RMacfarlane for now since she owns user authentication.

**Comment by finn-matti** [comment]
@isidorn @RMacfarlane WTF? What information is missing? Why is nobody answering. I am supposed to create an exact copy of this issue? How to proceed? Please advise.

**Comment by isidorn** [comment]
This is an error from the bot. Let's reopen and give @RMacfarlane more time to respond. She is on vacation.

**Comment by finn-matti** [comment]
Thanks! I'm happy to help, if I can. 😃

**Comment by RMacfarlane** [comment]
Hi @finn-matti, I'm not exactly sure what secure input you are talking about. Is this a quick pick opened from an extension? Can you send a screenshot of what you mean, or steps including how to open the input?

**Comment by finn-matti** [comment]
@RMacfarlane Secure input is a feature of mac OS. See this technical note from apple: https://developer.apple.com/library/archive/technotes/tn2150/_index.html

**Comment by chrmarti** [comment]
Not sure which input box this is. @finn-matti Could you attach a screenshot? Before and after the problem occurs (if that makes sense). Thanks.

**Comment by finn-matti** [comment]
I have the problem when using this input box (from [this extension](https://github.com/SchoofsKelvin/vscode-sshfs), see [this now closed issue](https://github.com/SchoofsKelvin/vscode-sshfs/issues/211)):

<img width="1792" alt="Screenshot 2020-09-10 at 10 09 34" src="https://user-images.githubusercontent.com/56148301/92693053-bbfa5d00-f34d-11ea-9ddd-d05c96b5f7cc.png">

An after screenshot would be the same but without the box and the effect that text expansion doesn't work anymore (os-wide).

**Comment by chrmarti** [comment]
@deepak1556 This sounds like an Electron/Chromium issue. Do you have any insights on it?

**Comment by finn-matti** [comment]
Nobody has any idea? Not even where to start?

**Comment by finn-matti** [comment]
Hey @TylerLeonhardt this issue has been opened so long ago, that I barely remember my struggles, but I'll try to answer:

>So Secure Input is an macOS thing that probably gets enabled when we show you an input box with a type of password.

Yes.

>What you're seeing is that after an extended period of time and (or?) when you put your mac to sleep and wake it up again the input disappears.

I think it is _and_ here. The input box was visible, the mac goes to sleep and I can't reauth, because the box vanished, but secure input never got disabled.

>So why is Secure Input left on? .... maybe because the input box that had set type to password has not been totally cleaned up?

That would be my guess. The box is not visible, but the appropriate os api is not called to disable secure input.

Now to your actual questions:

>When you say "the input disappears" do you mean the entire quick input (like the whole vscode UI box) disappears or just the input box inside of the quick input box disappears? Or is it that the text inside of the input box disappears?

I mean that the entire quick input ui box disappears.

>Have you figured out any workaround for this? I would be interested in you trying to open the Command Palette (cmd +shift + p) to see if that kicks the Secure Input back into place

Since this problem is/was specific to an issue with vscode-sshfs, I worked around it by using their ssh-socket implementation and unlock my ssh keys using ssh-add through the shell.

>I have to be honest, this doesn't seem like an issue a lot of users have so I can't promise a lot of traction in this space, but we can discuss it and maybe come up with a workaround or a solution that you could try send a PR for if that's cool with you.

That's fine. As per my last answer: I have a workaround and so there isn't too much more that needs to be done. I just wanted to close the loop with my answer and document the issue here , for future reference.

**Comment by TylerLeonhardt** [comment]
I think since we haven't received a single other report of this issue, I'm going to close this. If you do end up seeing this again though, please don't hesitate to reach out and we can do more investigation!
