### ISSUE TITLE
Pycharm like jupyter control 

### ISSUE THREAD

**Issue by bigcats01** [microsoft/vscode#104893]
Instead of having a plus button to add a new cell, can we make a new cell using the '#%%' and '#%% md' statements. Also, instead of having the output viewed directly under the cell, can we have an option move outputs to the side. 
![23ae1b95-4dad-466f-ae97-41d0b18725ee](https://user-images.githubusercontent.com/49263742/90475876-5d4b1600-e0f6-11ea-8e96-9f0ae73063f3.gif)

**Comment by bigcats01** [comment]
I think this [extension](https://marketplace.visualstudio.com/items?itemName=pavan.VSNotebooks) did the part of showing the output on the side (though it does not seem to work now. The interactive notebook makes cells with '#%%' but cant work with markdown cells '#%% md'

**Comment by misolori** [comment]
@bigcats01 is this different than using `#%%` in a python file with the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) and seeing the side by side?

![image](https://user-images.githubusercontent.com/35271042/92008767-6b0ab900-ecfc-11ea-8b02-e71d6c35c590.png)

**Comment by bigcats01** [comment]
I dont think so, this is my mistake

**Comment by misolori** [comment]
@bigcats01 does this solve your question then?

**Comment by bigcats01** [comment]
No, we can use #%% in a .py and it uses the ipykernel cells, but it 
doesn't support #%% md

also, saving this .py file isnt the same as the .ipynb

i hope this was more clear, sorry

**Comment by shohid96** [comment]
Amazing, very well done!
