### ISSUE TITLE
Inconsistent types for IWorkingCopy and TextFileEditorModel&IResolvedTextFileEditorModel

### ISSUE THREAD

**Issue by mtaran-google** [microsoft/vscode#104866]
- VSCode Version: head
- OS Version: n/a

This is a bug/inconsistency in the VSC codebase, which is currently obscured because of the specific way the code is written. This wouldn't really matter, but when using a build step that generates .d.ts files for dependencies, the `1 << 1` gets evaluated down to `2` and compilation fails. And overall, it'd be nice for the types to align in a sensible way.

Steps to Reproduce:

1. in `src/vs/workbench/services/workingCopy/common/workingCopyService.ts`, replace `Untitled = 1 << 1` with `Untitled = 2`
2. open `src/vs/workbench/services/textfile/common/textFileEditorModel.ts`

Expected: compiles fine

Actual: there are a number of errors like `Property 'getFirstLineText' does not exist on type 'never'.
  The intersection 'this & IResolvedTextFileEditorModel' was reduced to 'never' because property 'capabilities' has conflicting types in some constituents.ts (2339)` because `TextFileEditorModel` says that its capabilities field is readonly and 0, while the `IWorkingCopy` interface it is supposed to implement (by virtue of implementing `IResolvedTextFileEditorModel` after `this.isResolved()` is known to be true) says capabilities should be a readonly 2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Since this seems to concern only you with your specific setup, wanna do a PR to fix this?

**Comment by mtaran-google** [comment]
I would be more than happy to, but I'm not sure what approach you'd find (in)appropriate. 

1. I could type `capabilities` in `IWorkingCopy` as a number instead of an enum (since checks against it are anyways done via bitwise-and)
2. I could change `capabilities` in `TextFileEditorModel` to actually be 2 instead of 0 (though it seems like you also use 0 for this field in other places like `MainThreadCustomEditorModel.capabilities`, and somehow TSC doesn't care...)
3. I could add a `None` enum value of 0 to `WorkingCopyCapabilities`, since it seems like that's how you use it.

I'm leaning towards approach 3. What are your thoughts?

**Comment by bpasero** [comment]
Yeah I think we can give 3. a try in a PR.
