### ISSUE TITLE
html, editor.autoClosingBrackets doesn't work well

### ISSUE THREAD

**Issue by tailgo** [Microsoft/vscode#1048]
When I am typing a html file and adding a class to a tag such as :
 `<div class="some-class"></div>`
when I type `class="`, the double quotes doesn't auto closing.
editor.autoClosingBrackets doesn't work well when cursor in `<...>`

**Comment by Spown** [comment]
![](https://drive.google.com/uc?id=0B-OJBofmehO3Y2VIOG1XSmRaTm8)
fixed?

**Comment by tailgo** [comment]
@Spown yes, it works well. thanks~
