### ISSUE TITLE
Branch name overrun repo name in Source Control panel

### ISSUE THREAD

**Issue by hagaishapira** [microsoft/vscode#104801]
Issue Type: <b>Bug</b>

Introduced in the new 1.48.0.
In the Source Control sidepanel, if you have a repo with a long enough branch name such that the sidepanel size doesn't allow for both the repo and the branch name to appear side by side, then the branch name overruns the repo name.
The previous and "correct" behaviour is that the repo name always appear even if the branch name must be collapsed.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 9, 6|
|Memory (System)|16.00GB (0.81GB free)|
|Process Argv|-psn_0_15822614|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by antcodd** [comment]
Would be good if this could be a candidate for a recovery build, this makes dealing with multiple repositories that use long JIRA generated branch names like ``bugfix/VSC-123-some-really-long-ticket-title`` quite annoying. When the branch name is long enough the repository name disappears all together and makes the branches almost look like subtree entries.

**Comment by joshburkart** [comment]
This is a big usability issue for me too unfortunately... Very common to have long branch names, which make navigating multiple checkouts much more difficult with the new behavior...

**Comment by joaomoreno** [comment]
Actually there's no winning here. The solution you're proposing was implemented first and then came the issues: https://github.com/microsoft/vscode/issues/102108

There will always be people which really want to see the repository name. There will also always be people which really want to the see the checked out branches. We're sticking with the latter for now, sorry about that.
