### ISSUE TITLE
CTRL + F Not Working

### ISSUE THREAD

**Issue by Cooldogyum** [microsoft/vscode#104955]
Issue Type: <b>Bug</b>

I am unable to press CTRL + F to open the search on a file.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.8
javascript-ejs-support|Dig|1.3.1
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
vscode-pull-request-github|Git|0.19.0
rest-client|hum|0.24.1
csharp|ms-|1.23.0
vscode-css-peek|pra|4.0.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.9.0
pdf|tom|1.1.0
vscode-icons|vsc|10.2.0
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen after you run the command to reload with all extensions disabled?

**Comment by Cooldogyum** [comment]
The problem still exist with no extensions enabled, I'm not sure what caused it to stop working. It was recently working a few days ago and nothing has changed. The only thing I can think of is maybe an update caused it to break.

**Comment by Cooldogyum** [comment]
Appears it was a system issue, after going into safe mode and trying some system repairs it seems to have fixed itself.
