### ISSUE TITLE
can't open terminal

### ISSUE THREAD

**Issue by aviram120** [microsoft/vscode#104941]
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. terminal -> new ternital
and I got this error:
The terminal process "C:\WINDOWS\System32\cmd.exe" terminated with exit code: 259.

Does this issue occur when all extensions are disabled?: Yes

**Comment by zhangpy** [comment]
can't open on ubuntu 16.04 also.

**Comment by aviram120** [comment]
@Tyriar 
any update?

**Comment by Tyriar** [comment]
Check out the troubleshooting guide https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch, if you still have an issue after reading through that please link your settings.
