### ISSUE TITLE
Extension XHR failed

### ISSUE THREAD

**Issue by yozhmx** [microsoft/vscode#104948]
Issue Type: <b>Bug</b>

i do intent install vert extension and VScode show this messae "Error while loadinf extensions, XHR failed"

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
/duplicate - search for XHR to find some. #102714 includes a comment from someone solving it by changing DNS settings.
