### ISSUE TITLE
emmet.extensions not working

### ISSUE THREAD

**Issue by kangTaehee** [microsoft/vscode#104962]
Issue Type: <b>Bug</b>

The "emmet.extensionsPath" related settings do not work after the update.
Before the update, I was using it well.

It's the same thing with the reinstallation and the samples.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by shurinskiy** [comment]
Yes, that is right. After the update, custom snippets stopped picking up. It became inconvenient to work. This is a very useful tool.

**Comment by TD540** [comment]
Not working here also:
VS Code version: 1.48.2
OS version: macOS Catalina

**Comment by poltavchenko** [comment]
When do you plan to fix this bug?

**Comment by shurinskiy** [comment]
There have been four updates since the error appeared

**Comment by poltavchenko** [comment]
> 
> 
> There have been four updates since the error appeared

ok, in the latest build the problem is solved?

**Comment by shurinskiy** [comment]
> > There have been four updates since the error appeared
> 
> ok, in the latest build the problem is solved?

No! This is the problem. Already four updates in a row, such a necessary tool is ignored :(

**Comment by rzhao271** [comment]
Reopening because it auto-closed.
@TD540 can you confirm whether the fix works tomorrow in the next insider's build for macOS? Thanks in advance

**Comment by rzhao271** [comment]
Confirmed it works on latest Windows insiders. Will re-close and add this issue to current milestone.

**Comment by rzhao271** [comment]
\closedWith 2dbd0ae

**Comment by TD540** [comment]
Thank you to whoever fixed this!

**Comment by rzhao271** [comment]
For verifiers:

1. Write an Emmet snippets file or use the example as per https://code.visualstudio.com/docs/editor/emmet
2. Change the emmet.extensionsPath setting to point to that file
3. Create a new HTML or CSS file and type one of the snippets. Ensure that the snippet is suggested in the Intellisense.
