### ISSUE TITLE
c++ header <iostream> not recognised in vscode 1.4.0

### ISSUE THREAD

**Issue by claus022015** [Microsoft/vscode#10495]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04.1 LTS

Hi all,

I've discovered a small bug while trying to code in c++ using vscode. I have to point out that i`m a noob in vscode.
It doesn't recognise the iostream header, unless i edit c_cpp_properties.json file.
By default, in this config file the includePath is set to "includePath": ["/usr/include"]. 
In order to make vscode compile my program, i needed to edit the includePath to  ["/usr/include/"].
The odd behaviour is that vscode does not show the error below for all programs.
Some programs are compiled without modifying the includePath.

![include_error_in_vsc](https://cloud.githubusercontent.com/assets/11255266/17642356/dde6a944-614a-11e6-95e0-f6cdc60f44be.PNG)

If you have any ideas why this is happening, please share them, i would like to edit vscode's settings to take effect globally, on all c++ programs, without having to manually edit the includePath individually for each c++ program.

Thanks!

**Comment by jrieken** [comment]
This issue was moved to Microsoft/vscppsamples#147
