### ISSUE TITLE
Allow quick preview from file explorer

### ISSUE THREAD

**Issue by saveriomiroddi** [microsoft/vscode#104935]
Something I really miss from $your_famous_competitortm™ is the quick preview from the file explorer.

The use case is very simple: sometimes, I need to peek into the siblings of given file.

With $your_famous_competitor™, I can move the focus to the file explorer, then, when moving through the files, they're automatically displayed in the editor panel in quick preview mode.

**Comment by isidorn** [comment]
Yeah just use up / down arrow and press `space`
We will not support to open the files immediatly as you go up and down for now.
Thus closing as designed.
