### ISSUE TITLE
Windows: update list of not allowed filenames to include Aux.*

### ISSUE THREAD

**Issue by vendra95** [microsoft/vscode#104903]
- VSCode Version: 1.48.0
- OS Version: 10.0.190414 (Windows)

Steps to Reproduce:

1. Create a new file with name Aux.php
2. Save file

Windows cannot delete the file and git shows an error.
Windows does not allow to create files with reserved words but visual studio can.

Remove the ability to save files with reserved words in Windows.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I cannot create `Aux.php` with VS:

![image](https://user-images.githubusercontent.com/900690/90491633-77a9e180-e140-11ea-8e2e-9cecc35550b4.png)

We should probably revisit our logic in [`isValidBasename`](https://github.com/microsoft/vscode/blob/e55f6c99ccb126137375cb1636a581d7678b85c3/src/vs/base/common/extpath.ts#L146). 

If someone wants to revisit this, bring up a PR with tests.

**Comment by vendra95** [comment]
I finally removed the file just changing the name.

**Comment by vendra95** [comment]
I was wrong to describe the problem!

Steps to Reproduce:

1. Create a new file with name test.php
2. Save file
3. Rename file in Aux.php (important with extension!)

![image](https://user-images.githubusercontent.com/24313233/90495627-1e907c80-e145-11ea-96d7-1c0c3ba0f6b5.png)

the bug occurs only with the extension
![image](https://user-images.githubusercontent.com/24313233/90495703-36680080-e145-11ea-9e91-00795279750c.png)

**Comment by bpasero** [comment]
**Verification:** follow on Windows https://github.com/microsoft/vscode/issues/104903#issue-680783637
