### ISSUE TITLE
 my .tsx files have no errors hi-lighted on windows, on mac i get a bunch of error hi-lighting. i want to have the same config, they both appear the same but act differently. I cant disable them.

### ISSUE THREAD

**Issue by lachlangreenbank** [microsoft/vscode#104970]
Issue Type: <b>Bug</b>

I just switched to mac,

I opened the same files in Mac on code and im getting "Property 'createSeed' does not exist on type 'Readonly<{}> & Readonly<{ children?: ReactNode; }>'.ts(2339)" and others.

How di i disable these errors because it compiles fine.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.1.3

</details>

**Comment by CRYPTOBRIGHTBUTTERFLY** [comment]
Please remove this off my account!!!

**Comment by mjbvz** [comment]
Please share a complete, self contained code sample that demonstrates the problem

**Comment by lachlangreenbank** [comment]
<img width="1218" alt="Screen Shot 2020-08-24 at 1 17 21 pm" src="https://user-images.githubusercontent.com/16291813/91000316-3b78f400-e60c-11ea-84b4-01141962cb05.png">

The exact same code running on Windows. Save version, same prettify version. Set on Typescript react. Has no errors at all. For some reason on latest on Mac i'm getting a ton of type errors. 

<img width="1218" alt="Screen Shot 2020-08-24 at 1 24 28 pm" src="https://user-images.githubusercontent.com/16291813/91000713-26e92b80-e60d-11ea-9b6c-325a3214f225.png">

I have the same tsconfig.json on both too.

What should i do?

Thanks for the help

**Comment by lachlangreenbank** [comment]
This isnt about solving one error because there are so many types that have suddenly popped up. I just want them not so show up at all. can i disable certain codes or anything like that? 

I have synced my VS code acress machines but apparently that hasn't helped either

**Comment by mjbvz** [comment]
If there are errors, then IntelliSense and other features also will not work properly

Please  share a small project that demonstrates the issue (as text or a GitHub repo)
