### ISSUE TITLE
Support to define the placeholder text for the repository picker command

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#104932]
The new command works nicely!

![image](https://user-images.githubusercontent.com/172399/90609043-c0769e80-e203-11ea-93b4-6c998786d7ed.png)

I would like to show some more information to the user. Currently we show:
![image](https://user-images.githubusercontent.com/172399/90522936-9a51ef80-e16c-11ea-9be8-ddb932fa8275.png)

This could be done in the placeholder text (which currently is dynamic and depends on whether there is a provider).

**Comment by egamma** [comment]
Thinking about it. We are currently using a single command for cloning a repo, PR, branch. We could also split this command into several commands:

- Remote-Containers: Clone Repository in Container Volume - the existing one. This one would show up in the remote command palette
- Remote-Containers: Clone a Github Branch in Container Volume - new, as an advanced option it would not show up in the remote command palette and only in the normal command palette. The command you provide a picker with the branches for a repository. It mentions Github since the URL is Github specific.
- Remote-Containers: Clone a Github Pull Request in Container Volume - same explanation 

//CC @chrmarti @Chuxel

**Comment by chrmarti** [comment]
Discoverability would be worse for the new commands. Not sure I understand the placeholder proposal: The placeholder is only shown when there is no text input yet. (The prompt below the input box is only supported for InputBox not QuickPick at the moment.)

**Comment by joaomoreno** [comment]
@egamma Yeah I thought the same as @chrmarti: the placeholder only shows when there is no input.
