### ISSUE TITLE
Error message on zoom level change

### ISSUE THREAD

**Issue by nilueps** [microsoft/vscode#104989]
Issue Type: <b>Bug</b>

1. Open vscode
2. Change zoom level with keyboard or  menu

The error does not appear on every change

The following message appears in the logs (`# journalctl`):
`ERROR:gles2_cmd_decoder.cc(4927)] [.RendererMainThread-0x150221e2ac00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete`

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.7.14-200.fc32.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4079)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|31.01GB (12.82GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
god|bas|0.0.95
vscode-eslint|dba|2.1.8
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.1.3
html5-boilerplate|sid|1.0.3

</details>

**Comment by deepak1556** [comment]
You can ignore that message, are you seeing any incorrect behavior ?
