### ISSUE TITLE
Can‘t set a breakpoint when opening a project the first time in VSCode Insiders

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode#104964]
**OS:** Win10/Mac
**VSCode Insiders:**
![image](https://user-images.githubusercontent.com/62053665/90582809-3fb6a300-e201-11ea-9085-2b27c3d8b128.png)

**Steps to Reproduce:**

1. Install Azure Functions extension.
2. Open an empty folder in VSCode Insiders -> F1 -> Azure Functions: Create New Project -> Select the folder -> Select a language -> Select "HTTP trigger" -> Provide a function name -> Select "Function".
3. Set some breakpoints in index.js file and check the result.

**Expect:**
You can set a breakpoint.

**Actual:**
You can‘t set a breakpoint.

**More Info:**

1. Reopen this folder in VSCode Insiders can fix this issue.
2. This issue doesn't reproduce for VSCode Insiders version 1.48.0.

**Comment by weinand** [comment]
@isidorn should be fixed in latest Insiders, correct?

**Comment by isidorn** [comment]
Yeah, it should just work. Closing and @v-mengwe please let me know if you stil lsee with latest insiders and I will reopen.
I appologize for the issue.
