### ISSUE TITLE
Option to always expand open editors section by default

### ISSUE THREAD

**Issue by intrnl** [microsoft/vscode#104940]
I have tabs disabled, and it's a hassle to me that I can't find a way to make the open editors section expanded by default.

**Comment by isidorn** [comment]
As soon as you expand the first time it should remain expanded forever. Is that not what you are seeing?

**Comment by intrnl** [comment]
It is for existing projects, but not for new blank window or new projects

**Comment by isidorn** [comment]
Aha yes I understand. Yes we can keep this open as a feature request, even though I personally am not a fan.

**Comment by jonathanbell** [comment]
Too bad. I, for one, would love this.

**Comment by piengeng** [comment]
so freaking annoying have to click on the "OPEN EDITORS" every single freaking time, what a time waster if i must say.

**Comment by andf-mongodb** [comment]
+1 to this request. I open many small workspaces per day, the clicking adds up. Thanks for consideration.

If adding, make default "expand always" option expanded even with zero edited files. Editing first file automatically shows up entry under always-expanded "OPEN EDITORS" heading, without needing to change state of heading.

**Comment by tpneumat** [comment]
Plus one

**Comment by rbm-radius** [comment]
Same
