### ISSUE TITLE
Completion of staging a git submodule file sets focus at the top message box (if project has git submodules)

### ISSUE THREAD

**Issue by AndreyWV** [microsoft/vscode#104931]
- VSCode Version: 1.48.0 (db40434f5)
- OS Version: Linux x64 5.4.0-42-generic

Steps to Reproduce:

1. Open a folder with a git repo
2. Make a change to a file in project
3. Make a change to a file in git submodule project
4. Click the stage button in git submodule
5. Start typing a commit message to git submodule
6. When the file is successfully staged, focus switches to top commit message box (project, not git submodule)

Does this issue occur when all extensions are disabled?: Yes

![screen-record_2020-08-18 16_39_47](https://user-images.githubusercontent.com/29225873/90520266-cf147580-e171-11ea-88ec-e204500913f9.gif)

**Comment by RMacfarlane** [comment]
The focus no longer goes to the top input, but now I see it jump to the beginning of the current input:
![commit_focus](https://user-images.githubusercontent.com/3672607/92183568-a8a63980-ee03-11ea-803a-b8fa7645a5c9.gif)

**Comment by joaomoreno** [comment]
Good catch
