### ISSUE TITLE
Can't save file in another HDD partition

### ISSUE THREAD

**Issue by Andr3sfc** [Microsoft/vscode#1049]
Simply trying to save a file to D:\ raises the following error:

EPERM: operation not permitted, mkdir 'd:\'

**Comment by Tyriar** [comment]
Looks like a duplicate of https://github.com/Microsoft/vscode/issues/379, should be fixed in the next version.

**Comment by Andr3sfc** [comment]
Seems like it. So I'm closing this issue. Thanks.
