### ISSUE TITLE
Documentation and information on web version of vscode-oss

### ISSUE THREAD

**Issue by bigpod98** [microsoft/vscode#104968]
I think there should be more information on what is happening with web verison of vscode build from this repository since i cant find much besides yarn web

**Comment by bigpod98** [comment]
is there any new information about this things

**Comment by bpasero** [comment]
@bigpod98 can you clarify what you expect?

**Comment by bigpod98** [comment]
i cant find any information/documentation on how to this into a standalone web version of VSCODE beyond a single mention of yarn web which is used for debugging even when i saw references to being buildable into web version. there evne are some things inside the build stuff i think the software is called gulp that references web but does nothing

**Comment by bpasero** [comment]
@bigpod98 got it, I agree we should document this better.

//cc @kieferrm @egamma

**Comment by egamma** [comment]
@bigpod98 I'm sorry, but there are currently no plans to support a standalone web version of VS Code.
