### ISSUE TITLE
MOVE CURSOR TO TERMINAL AFTER RUN( ctrl+alt+n) 

### ISSUE THREAD

**Issue by hrittikhere** [microsoft/vscode#104993]
Issue Type: <b>Feature Request</b>

The following stuff is important for the user who don't use mouse so ofent. I have to drag my mouse to the terminal everytime I run the code which is time consuming when you debugging a big chunk of code or even when am using codeforces as time delay is there. Secondly, this is bit irritating.

I have demonstrated in a video what the issues is .   https://youtu.be/FJTbr8wLf9I

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041

**Comment by Tyriar** [comment]
ctrl+` can be used after you run to focus the terminal.
