### ISSUE TITLE
Snippets + Auto-closing pairs don't compliment each other

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#104952]
Version: 1.49.0-insider
Commit: 11dc5a81ba248cc2678888391f1b24dccabddaf8
Date: 2020-08-17T17:11:16.078Z (1 day ago)
Electron: 9.2.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

Add the following python snippet:
```json
"listcompPy": {
		"prefix":"[x for x in",
		"body":[
			"[x for x in range(1,20) if x%2==0 ]"
		]
	}
```
or PowerShell snippet:
```json
"PSCustomObject": {
        "prefix":"[PSCustomObject",
        "body":[
            "[PSCustomObject] @{ Key = Value }"
        ]
    }
```

1. type: `[` which will cause auto-closing pair... (at this point you have `[|]` where `|` is the cursor)
2. then add a `x` or `psc` and hit TAB or ENTER on the intellisense item

#### Python

```
[x for x in range(1,20) if x%2==0 ]
```

#### PowerShell

```
[PSCustomObject]@{
    Name = Value
}
```

#### Python

```
[x for x in range(1,20) if x%2==0 ]]
```

#### PowerShell

```
[PSCustomObject]@{
    Name = Value
}]
```

NOTE THE TRAILING `]`. Snippets and auto-closing pairs should play nice together so that the whole experience generates valid code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by TylerLeonhardt** [comment]
Here's a javascript example for array destructuring:

```json
"arraydestructuring": {
        "prefix": "[a",
        "body": [
            "[a, b, ...next] = ${1:array}"
        ],
        "description": "arraydestructuring"
    }
```

which gets you:

```
[a, b, ...next] = array]
```

when you type: `[a<TAB or ENTER to accept intellisense>`

**Comment by TylerLeonhardt** [comment]
better example!

A javascript example for `Symbol.iterator`:

```json
"SymbolIterator": {
		"prefix": "[Symbol.iterator",
		"body": [
			"[Symbol.iterator]: () => {",
			"    return {",
			"        next: () => {",
			"            return { value: value, done: false };",
			"        }",
			"    };",
			"}"
		]
	}
```

which gets you:

```js
[Symbol.iterator]: () => {
        return {
            next: () => {
                return { value: value, done: false };
            }
        };
    }]
```
> Notice the extra `]` at the end

when you type: `[Symbol<TAB or ENTER to accept intellisense>`

**Comment by TylerLeonhardt** [comment]
for verification, this:

```
"PSCustomObject": {
        "prefix":"[PSCustomObject]",
        "body":[
            "[PSCustomObject] @{ Key = Value }"
        ]
    }
```

should get you:

```
[PSCusomObject] @{ Key = Value }
```

on insert mode replace (default is SHIFT + ENTER)

**Comment by ArturoDent** [comment]
I'll note that it works fine in non-json files, but is reversed in a json file (as are the insert/replace hints in the suggestion box).

W10

**Comment by TylerLeonhardt** [comment]
that seems like a separate issue not related to this fix. Can you open a new issue?

**Comment by ArturoDent** [comment]
Yes, I'll open another issue.
