### ISSUE TITLE
Inno breaking change with 6.0.0 for mapping user form of common folder constants

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#104981]
We rely on `commondesktop` constant to create desktop shortcut link https://github.com/microsoft/vscode/blob/master/build/win32/code.iss#L92. This will no longer map to the correct value in user setup and lead to issue https://github.com/microsoft/vscode/issues/104545

From `6.0.0-beta` of https://jrsoftware.org/files/is6-whatsnew.htm

```
Change in default behavior: The "common" shell folder constants are no longer mapped to their "user" form if the
installation is running in non administrative install mode. Instead they simply return the requested common directory.
The list of affected "common" constants is: {commonappdata}, {commondesktop}, {commondocs},
{commonprograms}, {commonstartmenu}, {commonstartup}, and {commontemplates}.
```

**Comment by lszomoru** [comment]
In the same document they mention the new `auto` constants (ex: autodesktop) that do the mapping. Testing a fix for this right now.

**Comment by deepak1556** [comment]
Great catch, I shouldn't have skimmed through the document. Thanks @lszomoru
