### ISSUE TITLE
Could not convert to async function, this quick fix not shown.

### ISSUE THREAD

**Issue by liudonghua123** [microsoft/vscode#104961]
- VSCode Version:
```
Version: 1.48.0 (system setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:06.060Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT ia32 10.0.19041
```

Steps to Reproduce:

1. Create a js file
2. Paste the following code into it
```js
function example1() {
  return Promise.resolve(1)
    .then((value) => {
      console.log(value);
    })
    .catch((err) => {
      console.log(err);
    });
}

function example2() {
  return fetch('http://example.com/movies.json')
  .then(response => response.json())
  .then(data => console.log(data));
}
```
3. The quick fix for `example1` can show `convert to async function` menu, and it worked as expected. But the `example2` could not show `convert to async function`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Works fine for me in VS Code 1.49-insiders with TypeScript 4.0

<img width="719" alt="Screen Shot 2020-08-19 at 3 49 03 PM" src="https://user-images.githubusercontent.com/12821956/90697559-84f3c880-e233-11ea-9919-6c1fb1d2a674.png">

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by liudonghua123** [comment]
@mjbvz Hi, I tried the latest VS Code with the same version in another computer, it did work. It's strange, how can I find which extension make this strange behavior (The `example1` did work, another `example2` did not work).

**Comment by mjbvz** [comment]
Have you tried disabling extensions on your original computer to see if that fixes the problem?

**Comment by liudonghua123** [comment]
I tried disabling extensions on my original computer, it fixed the problem, `convert to async function` quick fix shown on both `example1` and `example2` . Now I just want to find which extension may occure this strange behavior. Why `example1` worked and another `example2` did not.

**Comment by mjbvz** [comment]
Closing this as not-reproducible with extensions disabled.

If you find reliable steps to reproduce the problem with extensions disabled, please share them so we can investigate
