### ISSUE TITLE
download

### ISSUE THREAD

**Issue by TheCodingTech** [microsoft/vscode#104925]
Issue Type: <b>Bug</b>

when i try to download a different laguage, i have to install it manually and it doesn't work

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.4.40-04224-g891a6cce2d44

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/4c (2 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|2.77GB (2.75GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details>Extensions: none

**Comment by dbaeumer** [comment]
@TheCodingTech what exactly do you mean with install manually. The installation of an additional language can be done via the extensions viewlet.
