### ISSUE TITLE
please always show english tip in git menu even user chosing cjk display language

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#104999]
I'm glad vscode localization, but I'd like to propose:
please always show english tip in git menu even user chosing cjk display language, because after switching to a different language, it's hard to guess what the git menu item really means.
For Latin users, it may be easy to understand the localization of git menus. but it will be hard for cjk users to understand.
![image](https://user-images.githubusercontent.com/1876302/90649677-8e9a2200-e26d-11ea-981a-1be9a2ab5de5.png)

like :
![image](https://user-images.githubusercontent.com/1876302/90652301-82639400-e270-11ea-82f2-d31f92455b3c.png)

THANKS and Please

**Comment by dbaeumer** [comment]
Assigning to @joaomoreno since this either needs to have special treatment in the Git menu or in the base menu actions. We have this support right now for commands which take a translated and the default string.

**Comment by joaomoreno** [comment]
@dbaeumer Can you point me to that implementation?

**Comment by dbaeumer** [comment]
https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/browser/task.contribution.ts#L315 is an example.
