### ISSUE TITLE
Cannot disable auto update for vscode

### ISSUE THREAD

**Issue by trafcio** [Microsoft/vscode#10497]
- VSCode Version: 0.9.2 (or any other version that is not the latest one)
- OS Version: 10.10.5 Yosemite

Steps to Reproduce:

1. Install visual studio code.
2. Put:	    
`"update.channel": "none"`
in user settings.json
3. Restart visual studio code.
4. Wait for Info message: **Visual Studio Code will be updated after it restarts**.

I cannot opt-out from auto update. I am using this:
[https://code.visualstudio.com/docs/supporting/faq](https://code.visualstudio.com/docs/supporting/faq
)

Furthermore my default settings are different from these:
[https://code.visualstudio.com/docs/customization/userandworkspace#_settings-file-locations](https://code.visualstudio.com/docs/customization/userandworkspace#_settings-file-locations)
I do not have:     `"update.channel": "default",` option on the left side.

I have [Intellisense Omnisharp Unity issue](https://github.com/Microsoft/vscode/issues/1535), that is why I need to use the older version.
Any Ideas how can I disable auto update?

Thank you.

**Comment by joaomoreno** [comment]
Can't reproduce. Updates stop coming when I set that setting and restart. Even the `Check for Updates` option is not there:

![screen shot 2016-08-15 at 12 06 43](https://cloud.githubusercontent.com/assets/22350/17661649/be7a9f38-62e0-11e6-99f8-f2aee0d8f1eb.png)

0.9.2 is way too old, and it could be that this was not even implemented by then, given the lack of that setting in the left side.

Try changing the value of `quality` to `none` in `Visual\ Studio\ Code.app/Contents/Resources/app/product.json`.

**Comment by trafcio** [comment]
Thank you :-)
I changed it `"update.channel": "none"` here: "~/Library/"Application Support"/Code (Mac)." and now it works.
Got help here: [https://github.com/OmniSharp/omnisharp-vscode/issues/269#issuecomment-220969116](https://github.com/OmniSharp/omnisharp-vscode/issues/269#issuecomment-220969116)

**Comment by thorn0** [comment]
I'm facing this issue with the latest Insiders builds. Even though, I have `"update.channel": "none",` in `settings.json`, it keeps updating itself and the `Check for updates...` menu item is still there. I'm on mobile data now and would be happy to disable these updates ASAP.

**Comment by joaomoreno** [comment]
@thorn0 Are you on OS X?

**Comment by thorn0** [comment]
Windows 7, x64.

**Comment by joaomoreno** [comment]
Thanks for the ping, @thorn0

**Comment by Tyriar** [comment]
Verified via code review :+1:

**Comment by dmngu9** [comment]
did you guys fix it?
