### ISSUE TITLE
Sync Settings can not change acconts easily, please add login function like VS

### ISSUE THREAD

**Issue by OzelotVanilla** [microsoft/vscode#104934]
Issue Type: <b>Feature Request</b>

[Ctrl + ,    Open *Settings*]
Sync Setting: On;
Manage [Button Click]: *Turn on Setting Sync...*

I want to sync my settings to both of my acconts, but I have to turn off sync and turn it on in order to let me choose the accont to hold sync data.
If VSCode can have an apparent icon on the upper right side and show us the login status, it may be more handful.
That's my first time writing issue, if I have any problems in writing issue, please tell me, thank you very much!!

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

**Comment by OzelotVanilla** [comment]
OK.
I mean when press the user icon above settings icon, Choose "Username(Github)" can let us be able to change account quickly, above the option "Signout".
![image](https://user-images.githubusercontent.com/59910575/90718958-c5ac1a00-e2e5-11ea-80db-e6975b8885a7.png)

**Comment by sandy081** [comment]
I see. 

Tagging this out of scope, since there is a way to switch account currently.

**Comment by chipbite** [comment]
https://stackoverflow.com/a/79000868/3701019
