### ISSUE TITLE
Html cursor shifting to beggening of a line 

### ISSUE THREAD

**Issue by theharshrastogi** [microsoft/vscode#104936]
Issue Type: <b>Bug</b>

whnever im going to next line my cursor is indentg its proper location

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:06.060Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (1.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
material-icon-theme|PKi|4.2.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|syl|1.8.9

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Can you give more details, e.g. a screen capture or screenshot with steps?

Does it reproduce with extensions disabled?
