### ISSUE TITLE
Terminal output layout for arrays and objects.

### ISSUE THREAD

**Issue by hiredtocode** [microsoft/vscode#104971]
I'm not sure if this is set to default but when I console log or run the code, arrays or objects are displayed in 2 columns instead in one line. 
```
]
  {
    firstName: 'Antonio',
    lastName: 'Gonzalez',
    DOB: '03/24/1985',
    department: 'Office Management',
    salary: '49000',
    fullname: 'Antonio Gonzalez'
  },
  {
    firstName: 'Aaron',
    lastName: 'Garrett',
    DOB: '09/04/1985',
    department: 'Development',
    salary: '39000',
    fullname: 'Aaron Garrett'
  }
]
```
I've tried searching the web to see if there's any way for me to change this format but no avail. Not too sure if this is caused from plugins but I've disabled any formatting plugins and tried running the code again but same. 
I can console.table to view it as a table but I think it'll be good to have a setting that can set different formats. 
If I have a big array of numbers this takes up a lot of space in the terminal but not only that it's hard to compare the results when editing.. It'll be cool if I can change the display setting for the output so that it displays inline across the big empty space to the right. Thanks.

**Comment by Tyriar** [comment]
We don't control how text is output in the terminal, that's the program you're running's job (node, python?).
