### ISSUE TITLE
Bottom right / left corner the "Manage wheel" update number

### ISSUE THREAD

**Issue by hiredtocode** [microsoft/vscode#104967]
- VSCode Version: Version: 1.49.0-insider
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

Number is displayed on the Manage button but when you click it, menu pops up but it doesn't display "what" the displayed number was about. Later, found out that there was a pending update. It was a guessing game. 

Does this issue occur when all extensions are disabled?: Forgot to check with the extensions disabled but I don't think it's related since this happened a little after installing the latest insiders version and was in middle of installing plugins.

**Comment by gjsjohnmurray** [comment]
What improvement do you suggest?

The tooltip for the 'Manage' gearwheel already changes when there's an update available.

No update available:

![image](https://user-images.githubusercontent.com/6726799/90614614-cfa91c80-e202-11ea-9d13-f0bec4256fd4.png)

Update available:

![image](https://user-images.githubusercontent.com/6726799/90614353-780ab100-e202-11ea-9eca-807f42f461dd.png)

And the additional menu option echoes the number:

![image](https://user-images.githubusercontent.com/6726799/90614503-a4bec880-e202-11ea-9387-b5772fcced9a.png)

**Comment by hiredtocode** [comment]
Sorry, I didn't see the tooltip. The tooltip works fine but I don't see that (1) in my manage menu. Here's the screenshot. 
![1](https://user-images.githubusercontent.com/68050282/90715543-8087e800-e2e5-11ea-8686-528d8bdd7bc1.JPG)
![3](https://user-images.githubusercontent.com/68050282/90715610-b0cf8680-e2e5-11ea-920d-cad73a956b03.jpg)
![2](https://user-images.githubusercontent.com/68050282/90715541-7f56bb00-e2e5-11ea-92dc-dd8191d4d58c.jpg)

I'd love to see (1) indicator beside the install update as your snippet.

**Comment by misolori** [comment]
Thanks for the screenshot, assigning to @sbatten

**Comment by sbatten** [comment]
@misolori It looks like when we added the (1) to the menu item https://github.com/microsoft/vscode/commit/6e90f387d170f60b68d122ce8902d787f85e2dba, we just didn't do it for others. I think we just need to add it to "Download Update" and "Install Update...", yes?

**Comment by misolori** [comment]
Ah, I guess that was me who added it 🙈 . But yes we'd need to add it to both, so it would be:
- `Download Update (1)`
- `Install Update (1) ...`?
