### ISSUE TITLE
View Extention Packs

### ISSUE THREAD

**Issue by MisterJ936** [microsoft/vscode#104972]
Hi, I just want to suggest an option to view "installed extension packs". In that way is easy for me to disable and enable extensions I need for development, and I don't have to type this in the search bar "@category:"extension packs" @installed". I want it to add in the ... -> view -> extension packs.
![Untitled](https://user-images.githubusercontent.com/31676163/90593897-b5c80380-e21b-11ea-85fe-678858e7797a.png)

**Comment by sandy081** [comment]
I can understand that it will be a use case that makes it easy for you but I do not think it is a good idea to add a view specific for a category. Hence we added filters and as you demonstrated this can be done through filters.

Sorry that we cannot take this up.
