### ISSUE TITLE
macOS: Allow Command+Tilde to switch windows

### ISSUE THREAD

**Issue by jt3k** [microsoft/vscode#104917]
is related to #69050, but it's closed

Version: 1.48.0
Build: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
Steps to Reproduce:

1. Open two vscode window 
2. Press CMD+` combination

I expect to change the active editor window, but I don't get it.

Does this issue occur when all extensions are disabled?: Yes

**UPD**

it happens on the Apple Magic Keyboard with the Russian keyboard layout. 
![image](https://user-images.githubusercontent.com/1261240/90511314-f57fe400-e164-11ea-921b-d08f200866dc.png)

I also use [Ilya Burman's keyboard layout](https://ilyabirman.net/projects/typography-layout/), where the tilde key is moved below the Escape key (to the left of the number_1_key).

I don't have that problem in other programs. But I only have a problem with vscode. Please, research and fix it :)

**Comment by bpasero** [comment]
Since I do not see us doing anything to block this keybinding from happening, I do not think this is a bug but something we need to support, e.g. by adding a related command to the menu possibly?

Marking as help wanted if someone has energy to look into it (I do not).

**Comment by bpasero** [comment]
@jt3k actually I found https://github.com/microsoft/vscode/issues/10021#issuecomment-307637284 which is a workaround to do this via VSCode own keybindings.

**Comment by jt3k** [comment]
Thank you, but..: 
1. it's just a workaround, and I'd like to help everyone who has the same problem.
2. The system window to select the active window will not be shown

**Comment by jt3k** [comment]
The current working combination in vscode, for those looking for workaround:
```json
  {
    "key": "cmd+`",
    "command": "workbench.action.quickSwitchWindow"
  },
  {
    "key": "cmd+`",
    "command": "workbench.action.quickOpenSelectNext",
    "when": "inQuickOpen"
  },
```
