### ISSUE TITLE
Hangul is broken via SSH extensions

### ISSUE THREAD

**Issue by nijkah** [microsoft/vscode#104900]
- VSCode Version: 1.48.0 (user setup)
- OS Version: Windows 10 Pro 18363.1016

Hagul(Korean) is broken when connecting it via Remote - SSH extension(v0.51.0).
But it is okay when I connect it via SSH in terminal.
To my memory, it didn't happen before.

FYI, File encoding format in VS CODE is UTF 8.

Steps to Reproduce:

1. connect to remote server via SSH Extension(in my case, I connect to docker container by port forwarding)
2. Go to a directory which contains hangul files. Furthermore, I cannot type Hangul in this terminal although it is available when I use ssh in terminal.

Does this issue occur when all extensions are disabled?: Yes/No
I couldn't test it because it requires SSH extension.

![image](https://user-images.githubusercontent.com/25769408/90482193-d2a5fd80-e16d-11ea-89a0-bd7086d1df92.png)

+ When I change display language from `en` to `ko`, it displays normal texts.
![image](https://user-images.githubusercontent.com/25769408/90484510-4269b780-e171-11ea-8941-ad0574114bfc.png)

**Comment by Tyriar** [comment]
I think you need to configure your `$LANG` environment variable in your `.bashrc` file. VS Code will set this for you automatically based on the display language, this is why it works when you set the language to Korean.
