### ISSUE TITLE
SIGSEV when launching tests on RHEL 8 on jenkins

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#104988]
- VSCode Version: 1.48.0
- OS Version: RHEL 8

Steps to Reproduce:

1. build one of this project on a Jenkins instance https://github.com/redhat-developer/vscode-java https://github.com/redhat-developer/vscode-quarkus https://github.com/camel-tooling/vscode-camelk
2. the tests are not launched, there is a SIGSEV error

Does this issue occur when all extensions are disabled?: Yes/No

Additional information:
- try to upgrade node version to 12.13.1 --> same result
- unable to retrieve logs using `archiveArtifacts artifacts:"~/.config/Code/logs/**/*" ` in JenkinsFile (how to configure it?)
- works fine on Travis CI
- works fine locally on Fedora 31
- was working fine with VS Code 1.47.3 on Jenkins with same environment
- console log in our codebase lead to this line throwing the SIGSEV https://github.com/camel-tooling/vscode-camelk/blob/03a5288bfd20d30dec55415c9e86fb2816e6ce54/src/test/runTests.ts#L20

How to investigate the root cause of the SIGSEV error?

Jenkins log:
```
+ npm test --silent
extensionDevelopmentPath = /mnt/hudson_workspace/workspace/vscode-temporary-testing
extensionTestsPath = /mnt/hudson_workspace/workspace/vscode-temporary-testing/out/src/test/suite/index
Downloading VS Code 1.48.0 from https://update.code.visualstudio.com/1.48.0/linux-x64/stable
Downloaded VS Code 1.48.0 into .vscode-test/vscode-1.48.0
vscodeExecutablePath = /mnt/hudson_workspace/workspace/vscode-temporary-testing/.vscode-test/vscode-1.48.0/VSCode-linux-x64/code
Installing extensions...
Extension 'ms-kubernetes-tools.vscode-kubernetes-tools' is already installed.
VS Code extension ms-kubernetes-tools.vscode-kubernetes-tools installed
Installing extensions...
Extension 'redhat.java' is already installed.
VS Code extension redhat.java installed
Exit code:   null
Done

Failed to run testsSIGSEGV
```

**Comment by apupier** [comment]
@isidorn what make you think that it is caused by an extension? Several extensions are impacted. it looks more a problem of VS Code itself in a specific environment (RHEL 8/Jenkins)

**Comment by fbricon** [comment]
@isidorn the build failure affects several vscode extensions built on the Red Hat CI farm, all since the vscode update

**Comment by apupier** [comment]
this issue was on our RHEL 8 image which received an update at the same time than VS Code 1.48.0 upgrade.
hint for people hitting same kind of issue: when an x server is missing, the VS Code tests are just sending a SIGSEV error.
