### ISSUE TITLE
while python-Remote debugging, VSCODE cannot really identify valid relative directories of debugging file

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#104910]
- VSCode Version: 1.48
- OS Version: win10_x64 1607

Steps to Reproduce:

1.
I am using PTVSD to debug python, there is one local-preocess runing within a local_py_file. as the same time, i use vscode to attach the process, the The key problem is that the local-process has difference cwd with my vscode-cwd
```json
        {
            "name": "Py13579_gui_source",
            "type": "python",
            "request": "attach",
            "port": 13579,
            "host": "0.0.0.0",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}/../",   // the process cwd is the father folder of vscode workspaceroot
                    "remoteRoot": "."                                 
                },
            ],
            "justMyCode": false,
        },
```
2. vscode can open the right file. but there is also the Relative paths, unlike the `real-same cwd debugging`.
![image](https://user-images.githubusercontent.com/1876302/90490639-6b8a4800-e171-11ea-84f9-c4a9f5f1392a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by heartacker** [comment]
1. debugging is able to work,  like run, stepin. stepout and so on
![image](https://user-images.githubusercontent.com/1876302/90492548-e48a9f00-e173-11ea-8a48-c01c8e895f57.png)

2. the debugging experience is different from `read-file` debugging
eg: unable to see step-yello-arrow(above pic: line:175, code is pause here but no step-yello-arrow), file became readonly

**Comment by weinand** [comment]
Please file against Python extension.
