### ISSUE TITLE
Make notebook status bar contributable

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#104958]
It would be great if extensions could provide richer functionality via the status bar, like we currently do in our Core status bar. One idea is this will allow for extensions to provide content actions that are separate from cell actions, like a Markdown WYSIWYG:

![image](https://user-images.githubusercontent.com/35271042/90573561-8eb1f900-e16b-11ea-9ef3-37d9dceaffe6.png)

**Comment by roblourens** [comment]
A couple ways to think about this

- Like status bar API
  - Dynamic
  - An extension can show/hide individual items per cell
- Like a menu/toolbar
  - Static
  - An extension can register entries with visibility controlled by "when" clause

In the use cases we care about, there are some items that we will want to add only to a particular cell, and also cases where we want to add an item to, say, every markdown cell. The dynamic option will be inconvenient for getting items to show up on new cells.

The static option would work if we had the ability to dynamically change custom context keys for different cells. As far as I know, we can only set global custom context keys (`executeCommand('setContext'`), and the tree and comments APIs allow for setting one context key per item, which is not dynamic. I think the solution would be a map of custom context keys/values on `NotebookCell`, a sibling of metadata, that can be changed at any time and referenced by static contributions of status bar items.

**Comment by roblourens** [comment]
And there is also work going to support working with complex context keys here https://github.com/microsoft/vscode/pull/104625

**Comment by roblourens** [comment]
The things that should go into the contribution look basically like `StatusBarItem`

- alignment (left/right)
- priority
- text
- tooltip
- color (?)
- command
- accessibility info (label/role)

I think it's not clear that all these things can be set statically. I need to know more about use-cases in Python.

**Comment by roblourens** [comment]
Talking to Kai, we clearly need a statusbar-like API, we may _also_ have a toolbar-type API, but these are distinct usecases.

```ts
namespace notebook {
	export function createCellStatusBarItem(cell: NotebookCell, alignment?: StatusBarAlignment, priority?: number): NotebookCellStatusBarItem;
}

export interface NotebookCellStatusBarItem {
	readonly cell: NotebookCell;
	readonly alignment: StatusBarAlignment;
	readonly priority?: number;
	text: string;
	tooltip: string | undefined;
	color: string | ThemeColor | undefined;
	command: string | Command | undefined;
	accessibilityInformation?: AccessibilityInformation;
	show(): void;
	hide(): void;
	dispose(): void;
}
```
