### ISSUE TITLE
Support two layers of settings.json in .vscode for team settings and personal settings

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/vscode#104943]
There are times when the team wants to enforce some settings in `.vscode/`, so they commit it to git, which is good for most members, but might not be good for one particular member. Some other times a user might want to add some additional settings of their own preference.

A contrived example: suppose this is a project setting of my team, committed to git:

.vscode/settings.json:
```json
"editor.codeActionsOnSave": [
  "source.organizeImports"
],
"search.exclude": {
  "package-lock.json": true
}
```

Then suppose I want to override it with my own setting, and also add one more thing:
```json
"search.exclude": {
  "package-lock.json": false
},
"files.exclude": {
  "build": true
}
```
But I don't want to commit my own preference. 

I propose adding something like a `.vscode/settings.override.json` which I can put into `.gitignore`, or maybe something like a `.vscode/settings.team.json` which should be committed but will be overridden by `.vscode/settings.json`.

**Comment by sandy081** [comment]
/duplicate

#40233
