### ISSUE TITLE
Regression: Source Control message input loses focus

### ISSUE THREAD

**Issue by rajbos** [microsoft/vscode#104908]
- VSCode Version: 1.47.3
- OS Version: Windows_NT x64 10.0.18363

The source control message input loses focus on any action regarding changes. This was not the case before.
Workflow: 
* Make some edits to files
* Navigate to source control pane
* Start typing a message. 
* Do something that changes the status (examples below)
* Message input loses focus
* Before committing (CTRL+Enter), you now need to click in the input
* Annoyed user that has to use the mouse now, where before this could be done with just the keyboard)

Note: only checked with Git as SCM.

Steps to Reproduce (after adding a message):

1. Save all open editors --> Focus lost

-- or --

1. Select some files and stage them --> Focus lost

-- or --

1. You where faster than the editor noting any changes to files and started typing before Git noticed the changes --> Focus lost

**Comment by isidorn** [comment]
Does not sound urgent, so leaving this for @joaomoreno once he comes back
fyi @eamodio

**Comment by usernamehw** [comment]
This issue should be fixed in the latest version **1.48.0**.

**Comment by isidorn** [comment]
Awesome, thanks @usernamehw
