### ISSUE TITLE
PowerShell in integrated terminal sometimes has no cmdlet like "Set-PSReadLineOption" and fails to load module

### ISSUE THREAD

**Issue by vilic** [Microsoft/vscode#10490]
- VSCode Version: 1.4.0
- OS Version: Windows 10.0.14393

Steps to Reproduce:

1. Configure settings:

```json
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
```

2. Launch integrated terminal (related commands are configured in my PS profile):

```
Set-PSReadLineOption : The term 'Set-PSReadLineOption' is not recognized as the name of a cmdlet, function, script file, or operable program.

Import-Module : The specified module 'posh-git' was not loaded because no valid module file was found in any module directory. 
```

The interesting thing is that, sometimes everything will just work without an issue.

**Comment by Tyriar** [comment]
It may be to do with using the 32-bit Powershell instead of 64-bit Powershell, see [config instructions here](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration). Let me know if this doesn't solve your issue.
