### ISSUE TITLE
Synchronize button rotates inaccurately

### ISSUE THREAD

**Issue by kapunchan** [microsoft/vscode#104965]
Issue Type: <b>Bug</b>

When click synchronize button, it rotates in a different position, which seems inaccurate.

![image](https://user-images.githubusercontent.com/18475036/90586034-cd49c100-e208-11ea-849f-0aeb116cf5ac.png)

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 17.7.0

**Comment by Tyriar** [comment]
@misolori fyi this spinner look pretty awful on windows+standard dpi monitor, here's a zoom level 0:

![image](https://user-images.githubusercontent.com/2193314/92029628-addb8980-ed1a-11ea-87f2-20cdb01994a4.png)

![image](https://user-images.githubusercontent.com/2193314/92029640-b2a03d80-ed1a-11ea-812c-1453c17354c9.png)

**Comment by misolori** [comment]
@Tyriar that's likely because the font-size is smaller (12px) than in the status bar (14px)
