### ISSUE TITLE
Issue #97199 is reproduced again in 1.48

### ISSUE THREAD

**Issue by skaeff** [microsoft/vscode#104922]
- VSCode Version: 1.48
- OS Version: Windows 10

Steps to Reproduce:

1. download 1.48 - issue https://github.com/microsoft/vscode/issues/97199
2. downgrade to 1.47.3 - all fine

Does this issue occur when all extensions are disabled?: Yes

**Comment by skaeff** [comment]
but where is duplicate? the previous one is closed and i can't reopen it!

**Comment by gjsjohnmurray** [comment]
#104603 and will be fixed in upcoming recovery release
