### ISSUE TITLE
Git: Stage selected ranges on unsaved file stages everything

### ISSUE THREAD

**Issue by alexanderkjeldaas** [microsoft/vscode#104945]
- VSCode Version: 1.48.0
- OS Version: OS X

Steps to Reproduce:

1. Do multiple changes in a file without saving the file.
2.  Select one of the changes for inclusion in the next commit "Stage Selected Ranges"
3. Try committing.

<img width="554" alt="Skärmavbild 2020-08-18 kl  20 22 14" src="https://user-images.githubusercontent.com/339369/90550708-96d05f80-e190-11ea-9768-2ee6d5c3d0d0.png">

Select "Save All & Commit".

Now you will see that all changes in the file was included in the commit.

What happens is "Save All & Commit All".  What I want is either that the dialog box is updated to indicate what is happening, or that the selected range is the only part that is committed.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by anish-94** [comment]
Looking at this bug. Would swapping the order of `await Promise.all(documents.map(d => d.save()));` and `await repository.add(documents.map(d => d.uri));` help address this?

https://github.com/microsoft/vscode/blob/e6b0f45556ff76631c4cf4621aa8e2be564f674e/extensions/git/src/commands.ts#L1374-L1376

**Comment by alexanderkjeldaas** [comment]
I see another related issue:  When selecting "Commit Staged (Amend)" when nothing is staged, it will also commit everything.

Expected is that I will just update the commit message.

**Comment by joaomoreno** [comment]
Changed the first button to `Commit Staged Changes` to make it clear what's happening.
