### ISSUE TITLE
Problem with PHP syntax check in Visual Code.

### ISSUE THREAD

**Issue by vanloc0301** [Microsoft/vscode#10493]
- VSCode Version: 1.4
- OS Version: Windows 10.

Steps to Reproduce:
1. I open a file PHP, show error like:

> phpcs: Unable to locate phpcs. Please ad phpcs to your global path or use composer dependency manager to install it in your project locally.
> 
> phpmd: No such phpmd executable: phpmd
1. I tried to fix it by install pear.phar.

2.1. `php go-pear.phar`
2.2. `pear install PHP_CodeSniffer`
2.3. 

```
pear channel-discover pear.phpmd.org
pear channel-discover pear.pdepend.org
pear install --alldeps phpmd/PHP_PMD
```

And edit user config to:

```
{
    "files.encoding": "windows1252",
    "php.validate.executablePath": "C:/wamp64/bin/php/php5.6.19/php.exe",
    "phpmd.validate.executablePath": "C:/wamp64/bin/php/php5.6.19/phpmd.bat",
    "php.validate.run": "onType"
}
```
1. Don't have an error but syntax checker seems to have a problem.
   You can see, I don't have any error, but it shows much errors(red line):

![capture](https://cloud.githubusercontent.com/assets/4168981/17641643/5da6e67e-6152-11e6-8a16-993c5dbd2177.PNG)

**Comment by dbaeumer** [comment]
@vanloc0301 does this work on the command line? It looks like the php.exe can't find its prereqs.

**Comment by vanloc0301** [comment]
Real path is correct. I using Wamp at path: `C:\wamp\bin\php\php5.6.19`.

**Comment by dbaeumer** [comment]
@vanloc0301 what do the errors say ?

**Comment by asamanta123** [comment]
I am a newbie in this app and have just opened it for editing my php codes. But I'm finding these messages:



phpmd: No such phpmd executable: phpmd

phpcs: Unable to locate phpcs. Please add phpcs to your global path or use composer depency manager to install it in your project locally.

PHP executable not found. You need PHP 7 installed and in your PATH

Cannot validate the php file. The php program was not found. Use the 'php.validate.executablePath' setting to configure the location of 'php'

Anybody please help me how to vanish these.

**Comment by roblourens** [comment]
It looks like the original issue was with a phpmd extension, or something that isn't relevant anymore. Let me know if there's still a problem.
