### ISSUE TITLE
promptString textbox disappears when losing focus

### ISSUE THREAD

**Issue by QAnders** [microsoft/vscode#104915]
- VSCode Version: 1.48.0
- OS Version: Win10 1909

Steps to Reproduce:

1. Create a `launch.json` that has inputs as `promptString`
2. Start the Debugger and see the prompt for a value
3. Focus on any other window to copy a value and the Prompt disappears

Does this issue occur when all extensions are disabled?: Yes

This is more of an annoyance than a bug really but we have `launch.json` that asks for two or three parameters using `promptString` where two of them might be config- or data-files.
I often then switch to the file explorer to copy the file name but when I return the focus to the VSCode window the Prompt textbox is gone.

This is especially annoying if I have to copy multiple things or e.g. a notice pops up stealing the focus...

I'd like the Prompt textbox to still be there when I return focus to VScode...

![image](https://user-images.githubusercontent.com/12028885/90500916-d759ba00-e14b-11ea-9eab-19cae8f31db5.png)

**Comment by isidorn** [comment]
Yes, we should always pass stable option to the peek when it is being invoked for input. So users can move focus to another app.
I am not sure who triggers this quick pick, is it the extension or a shared mechanism in the variable resolver.
Anyways starting by first assigning to @weinand
