### ISSUE TITLE
installetion bug

### ISSUE THREAD

**Issue by khaledhelmyg** [microsoft/vscode#104919]
Issue Type: <b>Bug</b>

When I wanted to install the prettier code formatter in visual studio code, this error appeared
Unable to open 'Extension: Prettier - Code formatter': XHR failed.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU       M 640  @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.44GB free)|
|Process Argv|C:\Users\abker\Downloads\esbenp.prettier-vscode-5.1.3.vsix|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
/duplicate - search for XHR to find some. https://github.com/microsoft/vscode/issues/102714#issuecomment-660050590 is an example of someone solving it by changing DNS settings.
