### ISSUE TITLE
notebook.visibleNotebookEditors & notebook.activeNotebookEditor not returning the correct item

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#104956]
- Version: 1.49.0-insider
- Commit: 3d5b2fecf2e6788cb9877d7d868d964fbc3ecd53
- Date: 2020-08-18T06:45:26.867Z
- Electron: 9.2.0
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Darwin x64 19.6.0

**Steps to Reproduce:**

This is with the Python Extension

1. Open two notebooks
2. Ensure both are pinned (A, B)
3. Assume A is the active notebook editor.
3. Switch between the two notebooks.
4. Now B is the active notebook editor.
4. VSC invokes the extension contribution `KernelProvider.provideKernels` 
	* At this point the argument `document` points to `B` (correct)
	* Use the VS Code API `notebook.visibleNotebookEditors` and it contains one item in the array pointing to `A`. (wrong)
	* Both editors are visible hence, we expect A & B to be in the array.

**Note:**
* We're accessing this to get hold of the active kernel for the active notebook using `NotebookEditor.active`
	* This allows us to return the same kernel as the `preferred` kernel when returning a list of kernels
* I guess we could use `activeNotebookEditor` as well, however thats us making an assumption that this method will only be called when the same notebook is active (when VSC calls `KernelProvider.provideKernels`.
	* Found that `notebook.activeNotebookEditor` too returns the incorrect item

@rebornix /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
> Use the VS Code API notebook.visibleNotebookEditors and it contains one item in the array pointing to A. (wrong)

@DonJayamanne are you still seeing this issue? I can't reproduce this issue locally.
