### ISSUE TITLE
when i use the git,the vscode will broke down

### ISSUE THREAD

**Issue by WinDaX** [Microsoft/vscode#10494]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
@WinDaX We can only help you if you provide sufficient informations. That includes precise steps to reproduce and a description of the problem

**Comment by dbaeumer** [comment]
Closing since no response happened in 14 days.
