### ISSUE TITLE
Extension commands best practices

### ISSUE THREAD

**Issue by peterjuras** [Microsoft/vscode#10496]
Hi,

I have a question regarding the best practices / conventions for commands that are provided by extensions: 

**Should command be prefixed with a common name that identifies the extension or rather not?**

In my case I have two commands:

- Sort imports
- Save file without sorting imports

Should I prefix them? e.g.:

- sort-imports: Sort imports
- sort-imports: Save file without sorting imports

Sorry if this is the wrong place to ask.

**Comment by jrieken** [comment]
> Should command be prefixed with a common name that identifies the extension or rather not?

I would recommend that because command identifier must be unique. I would go for `<extension_id>.<command_id>`

**Comment by peterjuras** [comment]
Sorry for the confusion, but I meant the strings that are displayed to the user.

The technical ids are prefixed already.

**Comment by jrieken** [comment]
Ah... Keep the label short but you can use another `category` label. In the F1 list we will then render `<category>: <label>` but in menu for instance just `<label>`.
