### ISSUE TITLE
Zen mode screen size detection

### ISSUE THREAD

**Issue by gim913** [microsoft/vscode#105062]
@isidorn in #44794 mentioned that

> In the future we should look at monitor size to decide if we should center or not

I'm using rotated display (1080 x 1920), default centerLayout = true in zenMode looks pretty bad in such configuration.

**Comment by isidorn** [comment]
Please just change the setting 	"zenMode.centerLayout": false,
As for looking at monitor size to decide if we shuold center - we will not do that and closing as out of scope.
