### ISSUE TITLE
Window crashes when python outputs too much in terminal

### ISSUE THREAD

**Issue by tom-programming** [microsoft/vscode#105030]
### Version of VS Code
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

### Your operating system
Windows 10 Enterprise, version 1909, build 18363.1016

### List of extensions that you have installed
```
cg-cnu.vscode-path-tools
Gimly81.matlab
kriegalex.vscode-cudacpp
ms-python.python
ms-vscode.hexeditor
ms-vscode.powershell
nhoizey.gremlins
stkb.rewrap
tht13.html-preview-vscode
```

It occurs even with all the extensions disabled
### Reproducible steps (1... 2... 3...) that cause the issue
You need python installed (I don't know if it can be reproduced in other ways, but I know that there are no crashes in terminals different from VSCode's one, and that trying to output a huge file with `type` does not provoke the crash)

1. Open the terminal
2. Write `python` to open a python prompt
```
s=11000000*'5'
s
```
3. Click or play a bit with the mouse in the upper section of the window (i.e. not on the terminal)
### What you expected to see, versus what you actually saw
I expect the printing of a very long series of '5''s

What happens is that the window crashes after a while

### Images, animations, or a link to a video showing the issue occurring
[link to a video](https://streamable.com/f27585). 

### Errors from the Dev Tools Console (open from the menu: Help > Toggle Developer Tools)
<s>No error there</s>

EDIT: actually if the Dev Tools are open it pauses with the writing "Paused before potential out-of-memory crash"

stack trace:
```
_event._event (C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\xterm\lib\xterm.js:1)
e (C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\xterm\lib\xterm.js:1)
get (C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\xterm\lib\xterm.js:1)
_provideLinks (terminalProtocolLinkProvider.ts:40)
provideLinks (terminalBaseLinkProvider.ts:14)
(anonymous) (C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\xterm\lib\xterm.js:1)
t._askForLink (C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\xterm\lib\xterm.js:1)
t._onHover (C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\xterm\lib\xterm.js:1)
t._onMouseMove (C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\xterm\lib\xterm.js:1)
```

**Comment by DougPlumley** [comment]
I'm seeing this issue as well

`Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0`

**Comment by Tyriar** [comment]
Looks like the link length is too long (11000000 characters in length 🤯), we need to cap out how much data to try create links for.
