### ISSUE TITLE
Combining char with special char (such as ‒̥) followed by Korean letter is incorrectly displayed

### ISSUE THREAD

**Issue by eelstork** [microsoft/vscode#105045]
- VSCode Version: 1.48.0
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Open a new file (plain text is fine; bug also observed with code editors)
1. Cut and paste the following text into VSCode:

```
‒̥ var     // combining char with special symbol followed by latin letter no issue
‒̥ シ      // combining char with special symbol followed by katakana letter no issue
‒̥ ᆩ      // combining char with special symbol  followed by korean char, BROKEN 
◠̥ ㅅ       // combining char with special symbol  followed by korean char, BROKEN 
︲̑ ᆩ     // combining char with special symbol  followed by korean char no issue 
u̥ ᆩ       // combining char with latin letter followed by korean char no issue 
_̥ ᆩ       // combining char with underscore followed by korean char BROKEN
_̂ ᆩ       // combining char with underscore followed by korean char BROKEN
_̂ᆩ        // combining char with underscore  followed by korean char without spaces BROKEN
_̂    ᆩ     // combining char with underscore followed by multiple spaces followed by korean char BROKEN
_̂
ᆩ          // combining char with underscore followed by a line break followed by korean char no issue
_̂/*+-.,^&*(!@#$%^&*()_0123456ᆩ     // BROKEN

```

2. Observe that, in lines marked "BROKEN", the combining char is incorrectly rendered *to the right* of the special character (should be under).
3. Select the first characters in any line marked "BROKEN".
4. Observe that while selection covers the combining char, it is temporarily "put back" to its correct location (this behavior may vary depending on considered sample)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alexdima** [comment]
VS Code is built with Electron, which is built with Chromium. I have created a test page at https://jsfiddle.net/4vs5wb72/ to check how Chrome renders this text, compared to Safari. I can confirm that Chrome is not rendering the text in the same way as Safari.

| Browser | Screenshot |
|---|---|
| Chrome | ![image](https://user-images.githubusercontent.com/5047891/92042746-1e19f780-ed7b-11ea-9d00-0a6e4cdc092b.png) |
| Safari | ![image](https://user-images.githubusercontent.com/5047891/92042782-2e31d700-ed7b-11ea-9533-6b7fe5d3dc79.png) |

As this is an issue with Chromium, please create an issue directly against Chromium (or find an existing one) at https://bugs.chromium.org/p/chromium/issues/list . Feel free to point them to the jsfiddle I've created or you can create your own.

**Comment by eelstork** [comment]
Thanks @alexdima ; scanned issues related to Korean language, nothing. Opening upstream https://bugs.chromium.org/p/chromium/issues/detail?id=1124606

**Comment by alexdima** [comment]
There is nothing we can do on our side. The issue is reported upstream and, if it gets addressed there, we will benefit from it via a future Electron update.
