### ISSUE TITLE
VSCode can't rename project folders

### ISSUE THREAD

**Issue by DavidHanover** [microsoft/vscode#105024]
- VSCode Version: 1.48
- OS Version: Windows 10 Pro Version 10.0.018362

Steps to Reproduce:

Seems to rarely work without error, for unknown reasons, but usually exhibits following behavior:

1. Try to rename any folder in project
2. VSCode file browser turns dark, hangs, VSCode eventually throws following error: 
```
Error: EPERM: operation not permitted, rename 'c:\Users\Me\Documents\Code\Project\folder' -> 'c:\Users\Me\Documents\Code\Project\new_folder_name'

```

Does this issue occur when all extensions are disabled?: Yes

**Comment by DavidHanover** [comment]
have tried: system restart, vscode restart, disabling all extensions, running as administrator.  nothing fixes it. 

only noticed after recent updates.

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by erronintila** [comment]
Same thing happened to me while running my application on development local server. I managed to resolved it by stopping the application using that folder and renamed it. It seems that VSCode can't update files if it is currently being used in production. Make sure to set all modifications first and then run your application.
