### ISSUE TITLE
Debugger controls duplicate

### ISSUE THREAD

**Issue by JasonFoglia** [microsoft/vscode#105010]
If you debug more then one project at a time. I see duplicate buttons on the debugger controls. Debugger controls duplicate when you drag it.

<img width="960" alt="2020-08-19_9-29-08" src="https://user-images.githubusercontent.com/1066476/90663453-8787fb00-e1fe-11ea-9485-6379a7fcbd42.png">

**Comment by isidorn** [comment]
@JasonFoglia I can not reproduce this. Here's me debugging two programs at the same time:
What are you doing specially? Can you reproduce if you disable all your extensions?
Do you have exact repro steps?

![Screenshot 2020-08-20 at 10 09 58](https://user-images.githubusercontent.com/1926584/90733803-57f3f400-e2cd-11ea-8595-b42b3be6a8d9.png)

**Comment by JasonFoglia** [comment]
I'm unable to reproduce myself. I simply shut down and restarted.
