### ISSUE TITLE
Multi-Line Edit is Wrongly Deleting Text from Wrapped Lines

### ISSUE THREAD

**Issue by gustavofrizzo** [microsoft/vscode#105038]
- VSCode Version: 1.48.0
- OS Version: Microsoft Windows 10 Pro 10.0.18363 N/A Build 18363

![multiline_bug](https://user-images.githubusercontent.com/4195793/90702710-53462600-e262-11ea-87b7-f5eb6d8b8d1c.gif)

Steps to Reproduce:

1. The setting "Word Wrap" is on.
2. Create a line with enough text to be wrapped.
3. Select the begging of multiple lines to edit by pressing SHIT + ALT + Mouse Left Click 
4. Notice that the wrapped text that belongs to the previous line is also selected.
5. Start to press the "Delete" key. Pay attention to the end of the lines. 
6. **The wrapped text at the end of the line is also deleted (the part "same line shouldn't be deleted").**
7. For reference, Notepad++ handles this correctly by not deleting the part of the text that is wrapped.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
related: #26393
