### ISSUE TITLE
Electron crashed when calling `getPossibleBreakpoints`

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#105019]
1. I set a breakpoint here https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L626 (note: I had done so at that same spot before, so probably not directly related to location)
1. Immediately the window crashed

![](https://memes.peet.io/img/20-08-bca4c3cf-5ef2-4a0d-ac62-4064aa5ee26b.png)

From the logs it looks like js-debug sent a request for breakpoint locations, to which Electron never responded and instead crashed:

![](https://memes.peet.io/img/20-08-79c4f330-55de-409b-a1d7-0a6ef7e829ab.png) 

Complete log file:  [vscode-debugadapter-2.json.gz](https://github.com/microsoft/vscode/files/5098447/vscode-debugadapter-2.json.gz)

Ref: https://github.com/microsoft/vscode/issues/100368

**Comment by pedroassis** [comment]
I am having a similar issue, if I run something with no breakpoints it works, but if I start with a breakpoint set vscode crashes in the same way.

It works if I set the breakpoint after the code is running, but the breakpoint stays unbound.

I'm going back to 1.3x again

```Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z (6 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0```

**Comment by connor4312** [comment]
Are you debugging VS Code itself or your own program? If the latter, please file and issue and fill out the template here: https://github.com/microsoft/vscode-js-debug/issues

**Comment by pedroassis** [comment]
@connor4312 I am debugging my own application, I am not the OP btw.

Using an old version of vscode solved the issue.

It's not the first issue I have with debugging recently, I believe it's a new debugging feature.

**Comment by connor4312** [comment]
This issue is specific to debugging VS Code itself. Please file an issue using the link above 🙂

**Comment by pedroassis** [comment]
@connor4312 sorry for the inconvenience, I am seeing the same error message that's why I posted here, anyways I deleted my previous comments, good luck!

**Comment by connor4312** [comment]
no worries -- if you're seeing the exact same dialog, please [open that on VS Code](https://github.com/microsoft/vscode/issues/new/choose) (or use the "submit a bug" link in the feedback icon on the lower-right of VS Code) as it's unlike to be caused directly by debugging. For general debugging errors, you can use the link I posted.

**Comment by deepak1556** [comment]
Does this repro with `electron-11.x.y` branch ?

**Comment by connor4312** [comment]
I haven't tried on that branch. This seems rare enough (I've only hit it a handful of times) that I don't want to spend a ton of dedicated time testing on that branch. I will just close it for now in the name of issue grooming and we can reopen it if we see this happening again on E11.
