### ISSUE TITLE
Reloading extension host results in "Unable to open polyfills.js" error notification

### ISSUE THREAD

**Issue by mattacosta** [microsoft/vscode#105047]
Issue Type: <b>Bug</b>

**Steps to reproduce:**
1. Start up the extension development host.
2. Press `ctrl+r` to reload.
3. The debugging window reports the following notification, and the extension host does not load the extension. This only happens on every other reload, so it alternates between loading correctly and throwing this error.

```
Unable to open 'polyfills.js': Unable to read file 'c:\Users\Matt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js' (Error: Unable to resolve non-existing file 'c:\Users\Matt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js').
```

VS Code version: Code - Insiders 1.49.0-insider (f694b07825a23005985b470e767a68927a83a553, 2020-08-19T05:47:42.278Z)
OS version: Windows_NT x64 10.0.19041

**Comment by weinand** [comment]
I cannot reproduce this on Windows.
Could you please try to reproduce this with the unmodified "hello world" extension (https://code.visualstudio.com/api/get-started/your-first-extension).
If the problem doesn't exist there, then it is most likely a problem with your extension.

**Comment by mattacosta** [comment]
Hmm, I can't reproduce using the hello world extension either. 

That said, debugging shows a promise rejection with this message being thrown:
`"ENOENT: no such file or directory, stat 'c:\\Users\\Matt\\AppData\\Roaming\\Code - Insiders\\logs\\20200819T190415\\exthost9\\output_logging_20200820T034543'"`

...which is highly unlikely to be something my extension is directly accessing.

Call stack:
```
<anonymous> (Unknown Source:280)
callback (c:\Users\Matt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js:295)
<anonymous> (<node_internals>/original-fs.js:158)
```

Since the first entry is grayed out, the second is automatically selected. Could this be related to the call stack's tree view item?

<details>
<summary>Console entry:</summary>
<pre>
notificationsAlerts.ts:40 Unable to open 'polyfills.js': Unable to read file 'c:\Users\Matt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js' (Error: Unable to resolve non-existing file 'c:\Users\Matt\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\graceful-fs\polyfills.js').
onDidChangeNotification @ breadcrumbsModel.ts:307
(anonymous) @ breadcrumbsModel.ts:307
fire @ event.ts:584
addNotification @ notifications.ts:188
notify @ notificationService.ts:69
doHandleOpenEditorError @ editorGroupView.ts:1018
(anonymous) @ editorGroupView.ts:923
async function (async)
(anonymous) @ editorGroupView.ts:923
doShowEditor @ editorGroupView.ts:923
doOpenEditor @ editorGroupView.ts:923
openEditor @ editorGroupView.ts:880
openEditor @ editorService.ts:509
openInEditor @ debugSource.ts:71
openInEditor @ debugModel.ts:350
focusStackFrame @ debugService.ts:753
n @ debugSession.ts:770
(anonymous) @ debugSession.ts:825
async function (async)
(anonymous) @ debugSession.ts:770
fire @ event.ts:584
(anonymous) @ rawDebugSession.ts:123
processQueue @ abstractDebugAdapter.ts:152
async function (async)
processQueue @ abstractDebugAdapter.ts:152
acceptMessage @ abstractDebugAdapter.ts:54
$acceptDAMessage @ mainThreadDebugService.ts:254
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:584
fire @ ipc.net.ts:412
_receiveMessage @ ipc.net.ts:746
(anonymous) @ ipc.net.ts:599
fire @ event.ts:584
acceptChunk @ ipc.net.ts:231
(anonymous) @ ipc.net.ts:157
t @ ipc.net.ts:822
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
</pre>
</details>

**Comment by Paril** [comment]
I get this quite often while trying F5 our extension as well. Same error as the OP.

**Comment by tjx666** [comment]
Same here

**Comment by tjx666** [comment]
![image](https://user-images.githubusercontent.com/41773861/92999000-12cf8480-f550-11ea-88bd-ab31605e5d4d.png)

**Comment by tjx666** [comment]
Version Infos: 

```
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

The reproduce  steps is same as @mattacosta  said.

My extension repository: [https://github.com/tjx666/vscode-fe-helper](https://github.com/tjx666/vscode-fe-helper)

**Comment by connor4312** [comment]
Can you collect a trace log using the following instructions? 

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by tjx666** [comment]
@connor4312 [vscode-debugadapter-2.json.gz](https://github.com/microsoft/vscode/files/5214486/vscode-debugadapter-2.json.gz)

**Comment by connor4312** [comment]
Thanks. It looks like you have pause on exception setup, and it's actually pausing on the error that you saw above

![](https://memes.peet.io/img/20-09-85b89032-e8ea-49f5-b351-63e3c4ed330d.png)

(cc @sandy081 on that -- I think you're the right person?)

I think the electron-shimmed fs lets us read files in the .asar, so we report `c:\applications\Microsoft VS Code\resources\app\node_modules.asar\graceful-fs\polyfills.js` as existing, when it should not exist.

**Comment by sandy081** [comment]
>  I think you're the right person?

You are right. Please let me know how can I help here.

**Comment by tansaku** [comment]
I'm getting this same issue on OSX 10.15.6 (19G2021)

**Comment by connor4312** [comment]
@sandy081 I think the thing for you would be to look at why that error is being thrown and avoid doing so 🙂 

The task for me is to not have it open the "Unable to open 'polyfills.js': Unable to read file " editor, and instead open the file with correct contents.

**Comment by connor4312** [comment]
This is now done

![](https://memes.peet.io/img/20-09-ac4955a5-f99b-4b3a-ab8e-3e6ca38d6c82.png)

**Comment by mikededo** [comment]
I'm facing the same issue. How can it be solved?

**Comment by boltex** [comment]
I'm also getting this issue on ubuntu 18.04 with this extension https://github.com/boltex/leointeg (dev branch)

Complete message is 
Unable to open 'polyfills.js': Unable to read file '/usr/share/code/resources/app/node_modules.asar/graceful-fs/polyfills.js' (EntryNotADirectory (FileSystemError): Error: ENOTDIR: not a directory, stat '/usr/share/code/resources/app/node_modules.asar/graceful-fs/polyfills.js').

heres a screenshot:

![Screenshot from 2020-09-22 00-58-11](https://user-images.githubusercontent.com/847716/93845410-b4508780-fc6e-11ea-82ef-d50c7cd4013a.png)

**Comment by connor4312** [comment]
> How can it be solved?

You can uncheck "uncaught exceptions" in the breakpoints view. Adding `"skipFiles": ["**/node_modules.asar/**"],` to your launch.json may also work, though I can't reproduce this at the moment to verify that.

**Comment by sandy081** [comment]
@connor4312 Is it possible to get the stack trace of the error [here](https://github.com/microsoft/vscode/issues/105047#issuecomment-691690768), it would be interesting to know where is this error being thrown.

**Comment by connor4312** [comment]
Here's the trace from a log someone posted above. Unfortunately it doesn't look like CDP gives us the async stack trace in this scenario...

```
[
  {
    "id": 1,
    "name": "<anonymous>",
    "line": 280,
    "column": 18,
    "presentationHint": "normal"
  },
  {
    "id": 2,
    "name": "callback",
    "line": 295,
    "column": 20,
    "source": {
      "name": "c:\\applications\\Microsoft VS Code\\resources\\app\\node_modules.asar\\graceful-fs\\polyfills.js",
      "path": "c:\\applications\\Microsoft VS Code\\resources\\app\\node_modules.asar\\graceful-fs\\polyfills.js",
      "sourceReference": 0
    },
    "presentationHint": "normal"
  },
  {
    "id": 3,
    "name": "<anonymous>",
    "line": 158,
    "column": 21,
    "source": {
      "name": "<node_internals>/original-fs.js",
      "path": "<node_internals>/original-fs.js",
      "sourceReference": 1200056501
    },
    "presentationHint": "normal"
  }
]
```

**Comment by tjx666** [comment]
This issue greatly affects my creative experience of vscode extension.

**Comment by sandy081** [comment]
@connor4312 I looked into the code that creates above directory and I see it is safely wrapped with try/catch block and handling errors. 

https://github.com/microsoft/vscode/blob/558e362801f6385510f0737d882615278493fb60/src/vs/workbench/api/node/extHostOutputService.ts#L85-L98

I do not know of other places where we create exthost output channel dir. 

It would be great to get the stack trace to see where this error is coming from, otherwise it seems I am helpless.

**Comment by sandy081** [comment]
Not sure if it helps but I simplified line 88 and broke it down.

**Comment by connor4312** [comment]
Yea that code looks just fine 🤔

I think in the next release for extensionhost debugging I will probably add everything outside the cwd to skipFiles anyway. That would wallpaper over this and also let people use "All Exceptions" / "All Exceptions" breakpoints without breaking in all their other extensions or internal code.

**Comment by sandy081** [comment]
Makes sense. 

Let me know if there is anything to be done from my side?

**Comment by mikecentola** [comment]
Sorry I created a duplicate issue. Having this same issue on 1.50.0 on windows.

**Comment by roblourens** [comment]
Looks fine, but it looks like this was hard to repro, so someone who was seeing this, please try to verify that it's fixed in VS Code Insiders.
