### ISSUE TITLE
Allow including cell context in postMessages sent from notebook cells

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#105037]
## Problem

Salvaging Don's request from https://github.com/microsoft/vscode/issues/103864#issuecomment-675132563, Python needs a way to link messages sent from the webview with specifics outputs/cells in their communication with the kernel.

## Solution

For this I propose making the following change to the [notebook renderer api](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vscode-notebook-renderer/index.d.ts):

```diff
    /**
     * Sends a message to the renderer extension code. Can be received in
     * the `onDidReceiveMessage` event in `NotebookCommunication`.
     */
-   postMessage(msg: unknown): void;
+   postMessage(msg: unknown, outputId?: string): void;
```

Cells already are given output IDs in the `onDidCreateOutput` events. This placement in the methods also joins nicely with the native DOM [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) method; where the target origin is given in DOM, instead the target output is given.

This would then involve propagating that to the `NotebookCommunication` object in the extension host. Where we currently fire `onDidReceiveMessage`, it will instead be a `NotebookMessageEvent<any>` (note: breaking change)

```ts
/**
 * Data fired in the {@link NotebookCommunication.onDidReceiveMessage} event.
 */
export interface NotebookMessageEvent<T> {
	/**
	 * Contents originally sent in the `postMessage`.
	 */
	contents: T;

	/**
	 * If a valid `outputId` was passed to `postMessage` inside the webview,
	 * the context will contain the cell and output it referenced.
	 */
	context?: {
		cell: NotebookCell;
		output: CellOutput;
	};
}
```

Note that the associated document is already given in the NotebookCommunication object, so it's not included again in the context.

## Limitations

Renderer messages are asynchronous to cell execution. For instance, output may be cleared as a message is being transmitted in postMessage. We can either:

1. Still transmit the message in this case, with a undefined context (or with some "unknown" marker?)
1. Drop the message if it refers to an invalid output

I would prefer the second option; it would be easy for extension authors to not realize the possibility of a race here and use a null assertion / unstrict null checks. If the cell is gone, its message is probably not relevant.

cc @DonJayamanne

**Comment by DonJayamanne** [comment]
Thanks for looking into this.
@rebornix i know you are looking into adding some transient metadata for cells and the like.
Is it not possible for us to use that.
I.e. add some transient metadata to a cell output (contains an ID that extension generates), then the renderer has this ID and can pass this to the extension host using the stock standard postMessage api.
Extension host gets the ID, and uses that to perform a lookup and identify the corresponding Cell & CellOutput.

This way, we don't need changes to the communication api and we can utilize the `transient` metadata that you're exploring for SCM and the like.

**Comment by connor4312** [comment]
This can now be accomplished with metadata
