### ISSUE TITLE
VSCode auto recompile again and again

### ISSUE THREAD

**Issue by kubo0212monsterpixel** [microsoft/vscode#105046]
System specifications:
- VSCode Version: 1.48.0 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:
- Behave: It occurs when I search (Ctrl + Shift + F) some text or just even switch between tabs file.
- Frequency: Sometime not 100%.

I used ```nodemon --verbose``` to watch files which trigger compile and I cannot see any files change and trigger build. You could check my image below: 
![Annotation 2020-08-19 183838](https://user-images.githubusercontent.com/34226751/90713503-a7d3ba80-e2cf-11ea-9d1d-d5f94570b36c.png)

Does this issue occur when all extensions are disabled?: 
- All extension are disabled and with user, workspace config used VSCode's default.

**Comment by leidegre** [comment]
I'm seeing this as well with the most recent version of Code (1.48.0/db40434f562994116e5b21c24015a2e40b2504e6). It triggers file system changes event when just browsing/looking at certain files.

**Comment by JacksonKearl** [comment]
> or just even switch between tabs file

Are you here saying that this will happen when just opening tabs normally, not necessarily only when searching?

**Comment by leidegre** [comment]
It just happened again for me while searching, so I could be related to searching.

**Comment by JacksonKearl** [comment]
> I used nodemon --verbose to watch files which trigger compile and I cannot see any files change and trigger build. You could check my image below:

It's odd to me that nodemon is re-running and it isn't able to tell you why, even under `--verbose`. If it was vscode emitting a file change event, I'd expect nodemon to be able to say so.

**Comment by kubo0212monsterpixel** [comment]
It's odd to me too. I setup new win 10 version 2004 and got that issue. I am double checking it occurs from VSCode or Win because when I only open files from Explorer it also recompile without any file change. ```nodemon``` cannot detect file change but I using tool which say to me some file change but no different content. Now, I downgraded Win 10 version 2004 to 1909 and check it.

**Comment by JacksonKearl** [comment]
> when I only open files from Explorer it also recompile without any file change

This suggests to me it's not a vscode bug.

> I using tool which say to me some file change but no different content

To clarify - you are using a different file watching tool that also reports a file change with no content change has occurred, and this can be triggered by opening files in Windows Explorer (i.e. not using vscode at all)

**Comment by leidegre** [comment]
Happened again, while navigating a TypeScript definition to another file in my project. This isn't limited to nodemon. The Node.js file system watcher API is generating events as well. Could be a Windows thing as I recently upgraded to build 2004 but It would be nice if we could find the root cause before we try to close this.

**Comment by leidegre** [comment]
Yeah, something is wrong with VS Code.

I just opened procmon and looked at file system events from VS Code. It is repeatedly scanning the entire folder file system. Over and over again. It's calling into `uv_fs_utime` which according to the libuv docs can change file last access and modification times.

This doesn't sit right with me.

**Comment by leidegre** [comment]
Check this out.

![image](https://user-images.githubusercontent.com/63085/90867993-7ffb5a00-e396-11ea-8134-1580f024188a.png)

I bet you this is the problem. It's Windows Defender that's causing the fuss. I'll try disabling Windows Defender for a while and see if the problem goes away. At least then we know.

---

@JacksonKearl Du you know if I can disable the polling behavior of VS Code, to me it seems excessive...

**Comment by kubo0212monsterpixel** [comment]
> Check this out.
> 
> ![image](https://user-images.githubusercontent.com/63085/90867993-7ffb5a00-e396-11ea-8134-1580f024188a.png)
> 
> I bet you this is the problem. It's Windows Defender that's causing the fuss. I'll try disabling Windows Defender for a while and see if the problem goes away. At least then we know.
> 
> @JacksonKearl Du you know if I can disable the polling behavior of VS Code, to me it seems excessive...

I setup last Win 10 version 1909 and anything seems good now (no file change, no recompile even click, search or change tabs). I will check few a day to confirm the issue occurs from VSCode or Win.

**Comment by kubo0212monsterpixel** [comment]
After I downgrade Window 10 version 2004 to version 1909 and has checked few a day. The issue gone and I absolutely confirm issue occurs from Window 10 version 2004. It is not VSCode.

**Comment by lhude** [comment]
Hello,
Windows 10 version 2004 is the version deployed in my company, and all VS Code users experience this problem.
Downgrading Windows version is not an option here.
I don't understand why this issue has been closed.
