### ISSUE TITLE
containerName on SymbolInformation is unexpectedly stripped of data in WorkspaceSymbolProvider results

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10504]
- VSCode Version: 1.4
- OS Version: Windows 10

If you set `containerName` to `null` when returning symbol results, Code displays the full file path:

![Full path displayed](https://cloud.githubusercontent.com/assets/1078012/17645432/e2dfb852-619d-11e6-97c9-7b8dc606e997.png)

However this isn't very pretty for imported Dart packages so we want to tweak it. However, if you set a value for `containerName` then everything up to the last dot gets stripped:

    containerName: "c:\test\danny.dart"

![Stripped path](https://cloud.githubusercontent.com/assets/1078012/17645436/099393c4-619e-11e6-96c2-cfc0576bb630.png)

This doesn't seem very logical. If it's valid for Code to display the name when a `containerName` is not provided, it should be valid for us to provide a similar value (for example, we might wish to display just a relevant part of the tree, `thing\file.dart` which currently also just displays `dart`).

**Comment by devoncarew** [comment]
I can repro this on the latest stable release, but do not see the issue on the latest VSCode Insider's release.

**Comment by jrieken** [comment]
I have cleaned that up 2 weeks ago (https://github.com/Microsoft/vscode/commit/36a2a04f862db09c9f8f3bc18ceb8d533debacbb#diff-00712023721c685fc8697e7bc7e85cb6). No clue why had those funny rules...

**Comment by DanTup** [comment]
Aha, that's why I couldn't find the code that was doing this, it's since gone!

Thanks (again!)
