### ISSUE TITLE
Search Editor: editable information text

### ISSUE THREAD

**Issue by guywaldman** [microsoft/vscode#105034]
- VSCode Version: **1.48.0**
- OS Version: **Windows_NT x64 10.0.19041**

Steps to Reproduce:

1. Open Search Editor (from Command Palette: `Search Editor: Open Search Editor`)
1. Type in some search term
1. Information about matches and files appears above all results:
  
    ![image](https://user-images.githubusercontent.com/6546430/90696998-15f38f80-e286-11ea-8e34-8a7f725e6da4.png)
1. Edit that information text:
  
    ![image](https://user-images.githubusercontent.com/6546430/90697022-24da4200-e286-11ea-80ca-c957610b614c.png)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by JacksonKearl** [comment]
Thanks for reporting this! Yeah, it's just a part of the result text. It could be a separate element, but that would suggest that it's a "live" value and modifying the editor would change it, which it doesn't. In other search editors (like sublime), it's the same. Going to close as-designed.
