### ISSUE TITLE
JetBrains Mono font with ligatures broken on Linux

### ISSUE THREAD

**Issue by SuperSandro2000** [microsoft/vscode#105067]
- VSCode Version: 1.49.0-insider 3d5b2fecf2e6788cb9877d7d868d964fbc3ecd53 x64
- OS Version: KDE Plasma 5.17.5, Debian

Steps to Reproduce:

1. Install JetBrains Mono font verison 2.001
2. Set VSCode font to JetBrains Mono

```
{
  "editor.fontFamily": "'JetBrains Mono'",
  "editor.fontLigatures": true
}
```
3. Observe totally broken font

The line numbers on the left are the emoji variant and the spaces in the middle are double with. Also ligatures are broken

![image](https://user-images.githubusercontent.com/7258858/90754382-1b7ac500-e2da-11ea-9696-887ae9b286fa.png)

JetBrains Mono with ligatures works with programs like Konsole or Kwrite correctly without any issues but not VSCode.

![image](https://user-images.githubusercontent.com/7258858/90754533-49f8a000-e2da-11ea-8630-4ea715865453.png)

If I switch to to the none ligature variant (``JetBrains Mono NL``) the font is rendered correctly but obviously without any ligatures which I would like to have.

![image](https://user-images.githubusercontent.com/7258858/90754439-2df4fe80-e2da-11ea-8b8a-f4573708b490.png)

Does this issue occur when all extensions are disabled?: Yes

The same happens with VSCode 1.48 release version.

**Comment by SuperSandro2000** [comment]
This exact config also works for me on two Windows Desktops.

I tested this over on vscode-web-test-playground in Chromium and Firefox and both work fine with the example config I provided in the first post. I also retested both VSCode and VSCode Insider and the issue is still there.

If I can provide any other info let me know.

**Comment by alexdima** [comment]
@deepak1556 Do you have any ideas?

**Comment by SuperSandro2000** [comment]
.....

**Comment by deepak1556** [comment]
@SuperSandro2000 can you check if the issue is present with our [exploration builds](https://az764295.vo.msecnd.net/exploration/b09dd7858771abf03f0abad6f5a5704839c13dd7/code-exploration_1.52.0-1604559376_amd64.deb)

**Comment by SuperSandro2000** [comment]
Still an issue with your linked version and with ``1.52.0-1605019262``.

**Comment by alexdima** [comment]
I tried today on Ubuntu 20.04 with:

```
	"editor.fontFamily": "'JetBrains Mono'",
	"editor.fontLigatures": true
```

and there it works fine:

![image](https://user-images.githubusercontent.com/5047891/101609203-f506a400-3a06-11eb-87c0-2d10909ae1d4.png)

So I think this is not a general problem on linux, but maybe only reproduces on KDE Plasma 5.17.5, Debian

**Comment by alexdima** [comment]
I have just installed KDE Plasma on Ubuntu 20.04 and it works there too:

![image](https://user-images.githubusercontent.com/5047891/101628076-93066880-3a1f-11eb-8e66-159fc1d346b1.png)
