### ISSUE TITLE
Ignore files/folders from intellisense

### ISSUE THREAD

**Issue by tgreen7** [microsoft/vscode#105029]
- VSCode Version: 1.48.0
- OS Version: macos 10.14.6

In our app repo we have a lot of generated database files which get regenerated. These files are tracked in git and are huge (thousands of lines of code). It seems like every time i regenerate these files my vscode intellisense slows to a crawl. When i try to cmd-click jump to definition it is stuck loading for 60 seconds. Same with snippet suggestions not popping up. This continues until i follow https://github.com/microsoft/vscode/issues/71751#issuecomment-480126916 and delete those caches and restart code. I think this means that those caches are full of all the changing autogenerated code instead of the files I am actually writing in.

Is there a way to ignore tracking of files in intellisense?

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by tgreen7** [comment]
It seems like the tsserver is taking a lot of cpu

``` 103      524   68470         electron_node tsserver.js 
    0       33   68474           electron_node typingsInstaller.js typesMap.js ```

**Comment by jrieken** [comment]
Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by mjbvz** [comment]
Do you have a tsconfig/jsconfig? Have you ensured the generated files are not included in those projects?

Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Potentially related: https://github.com/microsoft/TypeScript/issues/36035

**Comment by tgreen7** [comment]
@mjbvz We do not have a jsconfig in the project, but maybe adding one with include/excludes might help this issue. Also it doesn't happen every time the files are generated so it is hard to reproduce consistently

**Comment by mjbvz** [comment]
Were you able to try adding a jsconfig and configuring it to include only the files that are part of your JS project?
