### ISSUE TITLE
jsconfig error : File 'insert random module name here' not found.

### ISSUE THREAD

**Issue by airtonix** [microsoft/vscode#105052]
We need a way to reliably diagnose and fix these problems.

if the problem is that some module author needs to do something special then vscode should gracefully accept that this won't happen and let us continue to enjoy jsconfig features without a perfect world scenario.

- VSCode Version: 7.8.279.23-electron.0
- OS Version: Windows_NT x64 10.0.20190

```
Version: 1.48.0 (system setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.20190
```

- I work on non typescript things
- I'm not in control of what gets npm/yarn installed
- randomly jsconfig features break beacuse: 
![image](https://user-images.githubusercontent.com/61225/90721961-0bbea900-e2f9-11ea-8908-456df00eb618.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
This is likely a project configuration problem. Please share an example project that demonstrates this behavior
