### ISSUE TITLE
Unable to type accented characters in integrated terminal

### ISSUE THREAD

**Issue by wazybr** [microsoft/vscode#105051]
- VSCode Version: 1.49.0-insider
- OS Version: Linux 5.4.0-42 (Ubuntu 20.04.1)

Steps to Reproduce:

1. Set Brazilian Portuguese as your input language.
2. Open VSCode's integrated terminal.
3. Try typing any accented characters using accent key + letter key combination (~ + a).
4. See that they don't show up in the terminal.

Here I tried typing "título início razão metrô" in VSCode's integrated terminal:
![image](https://user-images.githubusercontent.com/49368302/90719425-c1064800-e28a-11ea-86fa-5c0a12993545.png)

Here I tried the same in gnome-terminal:
![image](https://user-images.githubusercontent.com/49368302/90719473-e1360700-e28a-11ea-8988-4d2bc2bf7e68.png)

Does this issue occur when all extensions are disabled?: Yes, it does.

Additional notes:
- My input method system is set to XIM. I switched to it to be able to bind the Ctrl+Shift+U key combination to an action.
- Pasting accented characters works.

**Comment by grlgmrs** [comment]
I have the same problem, it started to happen after I switched my keyboard to a USA International

**Comment by wazybr** [comment]
Maybe related to MicrosoftDocs/live-share#3818.

**Comment by grlgmrs** [comment]
I was able to fix this bug. I uninstalled vscode through Ubuntu software, then changed the name of the .vscode and .config/Code folders. Then I installed it using the .deb of the site itself, and the accents were working again.
I renamed the names of the folders I had changed again, to return to the old settings, and voiala

**Comment by wazybr** [comment]
Strange, I thought they both were the same version, same package, just distributed through distinct channels.

**Comment by grlgmrs** [comment]
I also found it strange, but tried to install it in other ways to check it out.
By the sudo snap install code, it didn't work. Not for apt-get either. I tried to reinstall using Ubuntu Software itself, and it didn't work either, but when I installed it with .deb, it worked...
