### ISSUE TITLE
option for Source Control to start as collapsed.

### ISSUE THREAD

**Issue by MichelleStreeter** [microsoft/vscode#105077]
Issue Type: <b>Bug</b>

Please add a setting to have the Source Control start as collapsed rather than expanded.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-148-generic

**Comment by joaomoreno** [comment]
#102831
