### ISSUE TITLE
Gutter source control highlights don't work with nested repositories

### ISSUE THREAD

**Issue by xster** [microsoft/vscode#105015]
- VSCode Version:
- OS Version:
Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

Have a project directory structure with a root git repository and nested git respositories in subfolders. 

Open a file in one of the nested repositories. Make some file edit. The gutter doesn't display the source control change status for the edited lines. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by xster** [comment]
@ bot, no, it's a different issue. The nested directories show in the source control tab's 'repositories' pane. This is about the gutter.

**Comment by gjsjohnmurray** [comment]
If this used to work for you prior to 1.48 then perhaps it is related to #104640 

cc @eamodio

**Comment by xster** [comment]
That issue seems to say all gutter diff indicators are gone? Single plain repo scenarios still work ok for me. The nested repo's diffs are gone.

**Comment by gjsjohnmurray** [comment]
Yes, but if what you're seeing is a 1.48 regression then I figure it might be related.

**Comment by joaomoreno** [comment]
@xster Do you have a sample repository I can clone and reproduce?

**Comment by xster** [comment]
Unfortunately the reproduction might not be super straightforward :S. I'm seeing it on https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment. It takes a few steps to setup but the outcome is somewhat simple. It's just a git repository with other (non-submodule) git repositories nested. Changes to those nested repositories don't appear in those repository's files' gutters. 

Thinking about this a bit more, the top repository .gitignores the nested repository. Perhaps that's the source of this issue and of https://github.com/microsoft/vscode/issues/105092?

**Comment by joaomoreno** [comment]
Yeah this is #37947
