### ISSUE TITLE
QuickHeal detected JS.Nemucod.AF

### ISSUE THREAD

**Issue by RushiVachhani** [microsoft/vscode#105056]
- VSCode Version: 1.48 
OS Version: Windows 10 2004, OS Build 19041.450

My QuickHeal detected and deleted file called **_JS.Nemucod.AF_** and now the copy vs VSCode shows **[Unsupported]** in the title bar.
Also on every startup of VSCode 2 notifications popup saying: 
a) Extension Host terminated unexpectedly. 
b) Your code installation appears to be corrupt. Please reinstall.

**Comment by RushiVachhani** [comment]
**Here is the detailed report of QuickHeal Antivirus:**

Report for - Quick Heal Virus Protection
Thursday, 20 August, 2020, Time, 12:43:44
-------------------------------------------------------------------------------------------
**Detected:** **JS.Nemucod.AF in
C:\Users\{User_Name}\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js**
Action taken: Deleted

**Comment by gjsjohnmurray** [comment]
Back in April there were several reports of a similar problem with QuickHeal. Search "quickheal" here to find them. I think you either need to report it to them as a false positive or add an exception.

**Comment by RushiVachhani** [comment]
Are you really sure that it rally doesn't contain any trojan or anything else ?

**Comment by gjsjohnmurray** [comment]
I just ran mine (from the 1.48.0 Stable install) through VirusTotal, and 0 of 57 engines detected any problem. The list includes one named "CAT-QuickHeal".

https://www.virustotal.com/gui/file/d1b3f20da4cf9551b6d583e4a8198df9cd8b47a406ab511597e70ad8017d9c04/detection

**Comment by RushiVachhani** [comment]
Thanks man it helped... 🙏
