### ISSUE TITLE
Open Search Editor should replace text input when run with text selected

### ISSUE THREAD

**Issue by swrobel** [microsoft/vscode#105031]
When selecting text in an editor and running "New Search Editor," or "Open Search Editor" without an existing Search Editor tab open, the selected text is entered into the search box in that editor. When selecting text and running "Open Search Editor" (if an existing search editor is already open), any existing text in the input is not replaced with the selection. It makes intuitive sense that in this case, you want to search for the newly-selected text, not run the old search, so this should be the default (and IMHO, only) behavior.

Suggested by @pstrum & acknowledged by @JacksonKearl here: https://github.com/microsoft/vscode/issues/100048#issuecomment-675143736

**Comment by JacksonKearl** [comment]
After using this option myself for a bit I agree it should always replace the query text and trigger a new search if you have a selection.

**Comment by JacksonKearl** [comment]
To verify:

1. Have some search editor open but not visible, with a query in it.
2. In some other editor, select text and run "Open Search Editor"
3. Expect the selected text to be searched for (or, if you don't have searchOnType enabled, simply placed in the query box)

**Comment by swrobel** [comment]
@JacksonKearl exactly! 🙏
