### ISSUE TITLE
Bug: Visual studio code closed all instances when i clicked File -> Exit

### ISSUE THREAD

**Issue by xkmodi** [microsoft/vscode#105083]
- VSCode Version:
- OS Version:

Steps to Reproduce:

**1.Open multiple projects/instances in visual studio code 
2.Click on File -> Exit Menu link. This will close all the open instance. 

It should only close the current instance not all the instances.**

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
AFAIK that's the difference between "Exit" and "Close Window".

**Comment by isidorn** [comment]
Yeah, closing as designed.
