### ISSUE TITLE
Indentation by language

### ISSUE THREAD

**Issue by tstringer** [Microsoft/vscode#10502]
- VSCode Version: v1.4.0
- OS Version: OS X 10.11.6

Is there support to have custom indentation by language?  I.e. 2 spaces indentation for JavaScript and 4 spaces indentation for Python.

I see a few things around from searching, but mostly people asking the same question and no real definite answer.

Is this possible in VS Code, and if so how can this be achieved?

Apologies in advance if this is documented.  Thanks!

**Comment by orta** [comment]
It doesn't look like it from the docs, you'd need to override those settings per project, and if it's a mix-language project - it looks like you're out of luck. 

I wonder if this could be built via an extension.

**Comment by orta** [comment]
This issue is a subset of https://github.com/Microsoft/vscode/issues/10432

**Comment by jrieken** [comment]
There is an `editorconfig` extension for that: https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by tstringer** [comment]
Thanks @jrieken for pointing me to that extension!  Is there any plans for the future to go away from this model?  I.e. detect language from file and use that particular indenting.  The reason I say this is because requiring an additional file (`editorconfig`) is not ideal.

Thanks in advance! 👍

**Comment by DanTup** [comment]
I think an extension providing support for a language should be able to provide sane defaults here too (eg. Dart convention is two spaces (as crazy as that is)). Currently we're having to override it at document open time which has some flaws!

```
export class DartIndentFixer {
	onDidChangeActiveTextEditor(editor: vs.TextEditor) {
		if (editor && editor.document.languageId === "dart" && config.setIndentation) {
			editor.options = {
				insertSpaces: true,
				tabSize: 2
			};
		}
	}
}
```

**Comment by jrieken** [comment]
We use and promote `editorconfig` because that supported by almost all editors/IDEs and we didn't invent our own thing

**Comment by DanTup** [comment]
I think that's great for per-project settings, but doesn't help with defaults. Not letting a language extension set a default doesn't give a great experience - you create a new Dart file and it's all intended one way, and then you press Format (or even Save, we're thinking of an option to format-on-save if Code doesn't have one) and everything changes (the dart formatter will always use 2 spaces, which is accepted Dart convention).

The only options seem to be:

1. The hack in my previous comment (which has issues)
2. Tell the user to install another extension and add a new file to every project, even though they want every Dart project to use the same settings

It feels weird that there's no ability for either an extension author nor a user to say "use 2 spaces for all Dart files, use tabs for everything else".

**Comment by DanTup** [comment]
Btw @tstringer:

> detect language from file and use that particular indenting

This is already an option within a file (but doesn't work on new files)

**Comment by tstringer** [comment]
Ok so after using `editorconfig` it looks like this is a good solution.  It appears as though you can include an `.editorconfig` file in a root location (i.e. user home) so that all child directories don't need to explicitly specify this.  Provided your dev files are in sub folders of a parent folder that has this single `.editorconfig` this appears to be a good solution.
