### ISSUE TITLE
Javascript autocomplete and intellisense not working

### ISSUE THREAD

**Issue by mwjaco** [microsoft/vscode#105008]
Issue Type: <b>Bug</b>

Please excuse me if I am mistakenly conflating autocomplete and intellisense, but both appear to be broken.  Two examples:

Autocomplete does not infer previously declared variable or function names in the same file.  Declaring the function "addUsers" and later referencing that function in the same scope, typing "addU" does not introduce the autocompleted option of "addUsers". This only stopped working in the last few days.

Meanwhile, extensions like "Simple React Snippets" have also stopped working. "imr," "impt," or "sfc" do not trigger the usual autocomplete options I am accustomed to seeing.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.1.3
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.8
path-autocomplete|ion|1.15.0
node-module-intellisense|lei|1.5.0
sftp|lix|1.12.9
vscode-html-format|moh|0.0.4
prettify-json|moh|0.0.3
sublime-keybindings|ms-|4.0.7
prettier-vscode|pre|3.14.1
ActiveFileInStatusBar|Ros|1.0.3
addDocComments|ste|0.0.8
vscode-stylelint|sty|0.85.0
react-proptypes-generate|sum|1.6.0
vscodeintellicode|Vis|1.2.10
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please provide a code example that shows what you are trying to do

**Comment by mjbvz** [comment]
Also, do you see this with all extensions disabled? You have Flow installed for example, which replaces VS Code's built-in JS intellisense
