### ISSUE TITLE
Option to choose which repository to show in "source control pane" with nested repositories

### ISSUE THREAD

**Issue by xster** [microsoft/vscode#105092]
When opening a directory with nested repositories, all repositories show under the repositories pane. But only the root repository shows under the source control pane. 

![Screen Shot 2020-08-20 at 9 59 58 AM](https://user-images.githubusercontent.com/156888/90802313-e9626680-e2cb-11ea-82eb-1069d8fa9d6b.png)

It would be nice to be able to choose a different nested repository to show the working directory's status of.

**Comment by xster** [comment]
https://github.com/microsoft/vscode/issues/37947 is actually related as a meta-bug but doesn't very explicitly call out this UI feature ask.

**Comment by joaomoreno** [comment]
> repositories pane

Not sure where that pane comes from, but it's not part of VS Code core.

Can you right click on the titlebar of the SCM and show the `Source Control Repositories` view? Is there only a single repository there?

**Comment by xster** [comment]
Ah sorry, I got mixed up. That second "repositories" pane is actually from gitlens. Though the original feature request still stands. In a folder with nested git repositories, have a way to pick which repository to show in the first pane.

**Comment by joaomoreno** [comment]
Due to performance reasons we tend to not crawl the entire workspace looking for git repos. Because of that we have the `git.scanRepositories` workspace setting which lets you list relative folders that the Git extension must scan for repositories. Does that help?

**Comment by xster** [comment]
Thanks. That option seems like exactly what I need. I probably have to play with it a bit more. At first try, I couldn't seem to get it to work describing the nested repository as relative paths in the workspace settings.
