### ISSUE TITLE
Terminal tab disappears after switching to Problems/Output/Debug Console tab

### ISSUE THREAD

**Issue by fuhrmanator** [microsoft/vscode#105085]
- VSCode Version: 1.48.0
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. View > Terminal :
![image](https://user-images.githubusercontent.com/7606540/90778356-845a4100-e2ca-11ea-8aea-81b678db1bb5.png)

2. Click a tab such as PROBLEMS, and the TERMINAL tab disappears. Must repeat step 1 (or use keyboard shortcut). This is a usability bug.
![image](https://user-images.githubusercontent.com/7606540/90778097-3a715b00-e2ca-11ea-92b6-d3a84b4c5c59.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by fuhrmanator** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Terminal - Support for multiple terminals as tabs instead of dropdown list (#97672)](https://www.github.com/microsoft/vscode/issues/97672)

No, this is not about the dropdown menu. It's about the Terminal tab disappearing, even though there are still terminals active.

**Comment by fuhrmanator** [comment]
> If you drag the visible terminal tab left so another tab is the rightmost one, does the problem affect the new rightmost one in the same way?

So, if I move the Terminal tab to the left, 

![image](https://user-images.githubusercontent.com/7606540/90816636-9d7ae600-e2fa-11ea-8079-39f8981add6a.png)

it sticks after switching:
![image](https://user-images.githubusercontent.com/7606540/90816674-b1264c80-e2fa-11ea-9c6d-d5eb997533fb.png)

Then, if I move it back to the right (and click on the "..." to see it), 
![image](https://user-images.githubusercontent.com/7606540/90816774-d1560b80-e2fa-11ea-8d8c-a68b008a8e62.png)

I can re-select it
![image](https://user-images.githubusercontent.com/7606540/90816859-ee8ada00-e2fa-11ea-955a-2c4b05f1c37b.png)

and it sticks after moving back to another tab:
![image](https://user-images.githubusercontent.com/7606540/90816926-0a8e7b80-e2fb-11ea-9ac4-c563664e7230.png)

I recently updated VSCode so here are the latest settings:

Version: 1.48.1 (system setup)
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:12:13.244Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

I quit VSCode and now I can't reproduce the problem!

**Comment by sbatten** [comment]
sorry never got a repro, if it happens in the future maybe we can get the exact dimensions from dev tools, this might be pixel perfect repro
