### ISSUE TITLE
Unable to register Codespace

### ISSUE THREAD

**Issue by martellaj** [microsoft/vscode#105016]
Issue Type: <b>Bug</b>

I've been using Codespaces since Microsoft started WFH. Today, I was unable to connect to my Codespace that's registered on my dev box at work. I connected to my machine and tried unregistering and re-registering it, but it gets stuck (~over 15 minutes~ indefinitely) on the "Registering Codespace..." step. 

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (24.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
sort-typescript-imports|mic|1.4.1
vscode-azureappservice|ms-|0.18.0
csharp|ms-|1.23.0
azure-account|ms-|0.9.1
vscode-typescript-tslint-plugin|ms-|1.2.3
vsonline|ms-|1.0.2669
debugger-for-chrome|msj|4.12.10
polacode|pnp|0.3.4
vscode-graphql|Pri|0.2.35
ejs-language-support|Qas|0.0.1
project-snippets|reb|0.5.0
vscode-icons|vsc|10.2.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by amyngu** [comment]
Running into the same issue as well. 

VSCode about info:
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Chuxel** [comment]
Thanks for raising the issue.  Would you mind opening this in the VS Codespaces repository here: https://github.com/microsoftdocs/vscodespaces  Unfortunatley I can't transfer it. 😢 

Any log info would be useful too! There seem to be a few on this topic: https://github.com/MicrosoftDocs/vscodespaces/issues?q=is%3Aissue+is%3Aopen+label%3A%22area%3A+self-hosting%22

Thanks!
