### ISSUE TITLE
Option to always open new windows maximized

### ISSUE THREAD

**Issue by garfieldbanks** [Microsoft/vscode#10505]
- VSCode Version: 1.4.0
- OS Version: W10

I'd like an option in user settings to have new windows always open maximized.

**Comment by garfieldbanks** [comment]
Maybe a command line option?

**Comment by rozzzly** [comment]
How about opening new windows which are still a part of the same session/workspace?

Right now you can "open file in a new window". However this new window appears to be a completely separated workspace. So, when you open the file, even if it's within the same dir root as your current project, it will just load that file, ignoring any of the settings from `./vscode/*`. This is really apparent if say you set a custom font in `./vscode/settings.json`; the new window will completely ignore those configurations. In fact, if in the new window you try `File->Open folder` and select the same dir as the original workspace's root, it appears to do nothing. From the quick attempts/tests I've made, it seems that the new window/workspace can't load the same folder while it's the root of the workspace in your original window.

For duel+ screen users such as myself, this is a super important feature. Being able to split the window vertically, arrange/group tabs was a huge leap forward. But, I think multiple windows are  must. Perhaps not a top priority, but something I'd like to see in the next few months.

A few other things that would perfect it: Context for menus for "open in new window" or "open group in new window" should be added, drag a tab out of the editor and it spawns a new window, move tabs from windows to window.

-- 

I can't imagine I'm the first person to mention this, but I follow the repo activity pretty closely and haven't seen anyone talking about this so yeah.

**Comment by bpasero** [comment]
One thing that I see other editors doing is to open the new window based on the dimensions of the currently active one: If the currently active one is maximized, other windows open maximized. If not, they take the same dimension and open slightly below the active window. We could do the same.

@stevencl any objections?

**Comment by glen-84** [comment]
That won't help if you use `New Window` from the jump list/menu (although it would still be an improvement).

**Comment by bpasero** [comment]
@glen-84 you mean for the case where no other window is opened I assume?

**Comment by glen-84** [comment]
I guess so. I thought that by "active" you meant that the window actually had to have focus (i.e. you would need to use the File menu item).

**Comment by bpasero** [comment]
Yup, I see use cases where a setting like this would make sense independent from opening the second window with the dimensions of the first.

**Comment by garfieldbanks** [comment]
@bpasero The behavior you describe would be a definite improvement. However I agree with @glen-84 that there are most certainly cases where a --maximized option(, or equivalent) would be helpful.

**Comment by bpasero** [comment]
See https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_9.md#control-the-dimensions-of-new-windows
