### ISSUE TITLE
autocomplete & emmett not working when in Multi-cursor mode?

### ISSUE THREAD

**Issue by bnhovde** [Microsoft/vscode#1050]
Not sure if this is by design, but for example, when editing markup with Multi-cursor enabled I cannot get autocomplete to work.

To recreate: 
Add multiple cursors, type "div" and hit tab.

**Comment by egamma** [comment]
The current emmet implementation does not support multiple cursors.

**Comment by amirm3hdi** [comment]
@bnhovde Yea, it's a feature I always used with Sublime, but it should be fixed here.

**Comment by ramya-rao-a** [comment]
Set `emmet.useNewEmmet` to `true` in VS Code 1.14
- As long as you have not turned off `editor.quickSuggestions`, you will now see emmet expanded values in the suggestion list. This will work with multi cursors as well. 
- `Emmet: Expand Abbreviation` command will run in multi-cursor mode. But it is no longer bound to the tab key for reasons explained here: https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list
    - We recommend to use the emmet expansion in the suggestion list
    - If you have turned off `editor.quickSuggestions`, then bind any other key to the command `editor.emmet.action.expandAbbreviation`
