### ISSUE TITLE
Files marked read-only on windows no longer can be saved on vscode 1.48.0

### ISSUE THREAD

**Issue by ashjas** [microsoft/vscode#105054]
- VSCode Version:1.48.0
- OS Version:win10

Steps to Reproduce:

1. open a file marked as read-only in properties.
2. try to change it and save
3. vscode prompts to retry as adimn,saveAs,discard. ![image](https://user-images.githubusercontent.com/788766/90723991-5fba9500-e2db-11ea-8f56-db7c24f90268.png)
4. before vscode 1.48.0 upgrade, on 1.47.3 it used to prompt for overwrite.
![image](https://user-images.githubusercontent.com/788766/90724212-cb9cfd80-e2db-11ea-8620-5b01df693273.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/104651
Will be fixed in the recovery release
