### ISSUE TITLE
Pressing buttons in VSCode toast notification window pauses Spotify's desktop app

### ISSUE THREAD

**Issue by liamlaverty** [microsoft/vscode#105064]
- VSCode Version: 1.48.0
- OS Version: Windows x64 10.0.18362

Steps to Reproduce:

1. play some music in Spotify desktop app
2. Click a toast notification in VSCode
3. Music is now paused

Does this issue occur when all extensions are disabled?: 
Unable to test, I can't get a popup to appear in this version

**Comment by isidorn** [comment]
🎶

**Comment by bpasero** [comment]
I suggest to report this to Spotify as this seems like they are doing something based on this condition?

**Comment by isidorn** [comment]
Also good luck with reporting issues to Spotify
