### ISSUE TITLE
vscode execute ~/.zprofile when startup with zsh as default shell

### ISSUE THREAD

**Issue by zszszsz** [Microsoft/vscode#10500]
- VSCode Version:compiled from git, Aug 13 , 2016
- OS Version:manjaro linux, linux 47, wayland, weston, oh-my-zsh, Aug 13, 2016

just run vscode and you can find the zprodile executed.

That is usually mot a problem, but I start weston in my zprofile, so that is reallly a bug for me.

**Comment by Tyriar** [comment]
You likely need to pass in `-l` to run the shell as a login shell:

```json
  "terminal.integrated.shellArgs.linux": [
      "-l"
  ]
```
