### ISSUE TITLE
Built-in command `editorScroll` lags when scrolling up.

### ISSUE THREAD

**Issue by Espylapiza** [microsoft/vscode#105094]
- VSCode Version: 1.48.0
- OS Version: Darwin Kernel Version 19.6.0 and 5.4.57.1-MANJARO (both occurs)

Steps to Reproduce:

1.
Set up shortcuts in `keyboards.json`.
```
{
    {
        "key": "alt+down",
        "command": "editorScroll",
        "when": "editorTextFocus",
        "args": {
            "to": "down",
            "by": "line",
            "value": 1,
            "revealCursor": false
        }
    },
    {
        "key": "alt+up",
        "command": "editorScroll",
        "when": "editorTextFocus",
        "args": {
            "to": "up",
            "by": "line",
            "value": 1,
            "revealCursor": false
        }
    },
    // The following does the same.
    /*{
        "key": "alt+up",
        "command": "editorScroll",
        "when": "editorTextFocus",
        "args": {
            "to": "down",
            "by": "line",
            "value": -1,
            "revealCursor": false
        }
    }*/
}
```

Hold `alt+down` and `alt+up`, and `alt+down` scrolls much smoother and faster than `alt+up`.

2.

Does this issue occur when all extensions are disabled?: Yes/No

Yes.

**Comment by alexdima** [comment]
I do not observe such slowness. Could you please create and attach a CPU profile of the renderer process. Here are the steps -- https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process
