### ISSUE TITLE
Insiders build won't update from commit bd08768f

### ISSUE THREAD

**Issue by petkahl** [microsoft/vscode#105027]
- Version: 1.49.0-insider (user setup)
- Commit: bd08768fd310d34cdd4423a53e5f3ca77340fea5
- Date: 2020-08-14T05:56:40.601Z
- Electron: 9.2.0
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Install this version
2. Search for Updates/wait for update to show
3. Restart to update
4. Remains on the same version (I've tried 4-5 times)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Does it work if you disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`?

**Comment by petkahl** [comment]
It updated at some point, so I can't answer. May have been intermittent or something fixed by windows update or similar. 

Closing.
