### ISSUE TITLE
Differentiate between the "extension provided tasks" and "user tasks in tasks.json file"

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode#105012]
Configure Task Command shows a list of "extension provided tasks" and "user tasks in tasks.json file". 
When a user creates a task, the name will be the same as what extension suggests for the provided tasks. As a result, "extension provided tasks" and "user tasks in tasks.json file" will end up having the same names, unless the user changes the names.

For example, this is a list of extension provided tasks: 
![image](https://user-images.githubusercontent.com/16143955/90663139-206a4680-e1fe-11ea-9445-0a225662a675.png)

and this is the result if the user creates the provided tasks and doesn't change the template names in tasks.json file:
![image](https://user-images.githubusercontent.com/16143955/90663095-10526700-e1fe-11ea-89fa-afcd4034db58.png)

It would be good if there could be a difference between these two tasks. 
I could think of two approaches.
1. The extensions could have the following ability: the extension shows the name **"C/C++ extension provided task X"** in quick-pick, and if the user chooses this template, the name that is written in the tasks.json file will be **"Task X"**. As a result, the user will see this (this approach is similar to creating MSBuild, Maven, and .Net Core template tasks): 
![image](https://user-images.githubusercontent.com/16143955/90664748-eac65d00-e1ff-11ea-81df-16e612e6a124.png)

2. Or the extension could have this ability to change the details of the user tasks while showing them in the dropdown menu (the tasks.json file will not be modified).
![image](https://user-images.githubusercontent.com/16143955/90665587-185fd600-e201-11ea-8f70-fbcaf3f79d7f.png)

3. Or, the extension can have both abilities :) 
![image](https://user-images.githubusercontent.com/16143955/90665385-ccad2c80-e200-11ea-9a8e-2b868fd7fc6a.png)

**Comment by alexr00** [comment]
A lot of work was done recently to remove all calls to the extension when showing the task quick pick to improve performance, and option 2 directly contradicts that. 

Why can't the user just give the task a new label in the tasks.json?

**Comment by elahehrashedi** [comment]
How about option one? Most probably it won't affect the performance, and it has already been implemented for MSBuild, Maven, and .Net Core template tasks.

**Comment by bobbrow** [comment]
The user could go back and give the task a new name, but we also create a launch configuration that takes a dependency on the generated task and they'd have to update that too.

**Comment by alexr00** [comment]
I think letting the extension change the label of the task when a user tries to configure it can cause a lot of confusion. The user has chosen to configure "Task XYZ". If the task suddenly has a new name that would be unexpected. 

How is the launch configuration created? I'm wondering where you're getting the name for prelaunch task currently.

Regarding the templates for MSBuild, Maven, and .Net Core: those are just static templates that we write into the tasks.json. There is a feature request to allow those static templates to be contributed by extensions, but they would still be static.

**Comment by elahehrashedi** [comment]
the process of choosing the names for prelaunch task is similar to those of build tasks. The best we can do is to set a different detail for them, to create a difference between the build tasks that the user generates and the prelaunch tasks that are generated during the debugging.
