### ISSUE TITLE
Crashing on modal dialog open on Gnome 3.36

### ISSUE THREAD

**Issue by ddaws** [microsoft/vscode#105072]
VSCode is crashing when a preLaunchTask is added to a launch config. This started happening either after updating VSCode or my kernal / packages. Here is a repo with the minimal setup that recreates the issue for me:

https://github.com/ddaws/vscode-105072

## Versions

- VSCode Version: July 2020 (version 1.48)
- OS Version: 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 GNU/Linux

**Note:** VSCode was installed via [`snap`](https://snapcraft.io/)

```
$ snap list
Name               Version                     Rev   Tracking  Publisher     Notes
code               db40434f                    40    stable    vscode✓       classic
```

## Steps to Reproduce:

1. Open VSCode for the example project linked
2. Attempt to run the launch profile 

> Does this issue occur when all extensions are disabled?:

Yes, I have confirmed that VSCode still crashes with extensions disabled

## Questions

- Where can I find crash logs for VSCode?

**Comment by ddaws** [comment]
@weinand is there anymore information I can collect for you in the meantime?

**Comment by isidorn** [comment]
When running the launc configuration in the sample workspace you provided I get a simple error. VS Code does not crash.
![Screenshot 2020-08-26 at 15 40 58](https://user-images.githubusercontent.com/1926584/91310784-96e4e680-e7b2-11ea-8c17-f298024e43cc.png)

Can you reproduce using vscode insiders?

**Comment by ddaws** [comment]
Confirmed, this also crashes VS Code Insiders

```bash
$ code-insiders --version
1.49.0-insider
b6d4fec3714ff897f72c1dab8cc02b7421a8f131
x64
```

```bash
$ snap list
Name               Version                     Rev   Tracking  Publisher     Notes
code               a0479759                    42    stable    vscode✓       classic
code-insiders      b6d4fec3                    514   stable    vscode✓       classic
```

Some other actions that are causing VS Code Insiders to crash :( 

- Attempting to open Help > About
- Attempting to open Help > Check for updates...

Opening Help > Process Explorer does not cause VS Code Insider to crash. Maybe this is because VS Code is attempting to open some system default dialogue which isn't handled properly on my Arch Linux setup? 

Maybe worth noting I am running Gnome 3.36.4 using Wayland 

-----

Re "Could not find the task 'yarn build'", is the cwd the project root by default? I was under the impression it was, so yarn build should reference the build command defined in the project's package.json in the root.

**Comment by isidorn** [comment]
Sounds like an electron issue when a modal dialog is opened that the whole app crashes. Forwarding to @deepak1556

**Comment by deepak1556** [comment]
Most likely duplicate of https://github.com/microsoft/vscode/issues/100940

@ddaws can you check if the workaround posted there helps, thanks!

**Comment by ddaws** [comment]
@deepak1556 linking gdp-pixbuf libs to the folder expected by electron appears to fix things. Thank you for point me in the right direction, and thank you @isidorn for your time!

I think we can close this issue as a duplicate. In case it's useful, some more version info

```
Version: 1.49.0-insider
Commit: b6d4fec3714ff897f72c1dab8cc02b7421a8f131
Date: 2020-09-01T05:49:18.149Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.7.10-arch1-1 snap
```

**Comment by deepak1556** [comment]
Thanks for confirming!
