### ISSUE TITLE
Open Search Editor does not always select all existing text in the input field

### ISSUE THREAD

**Issue by swrobel** [microsoft/vscode#105032]
- VSCode Version: 1.48.0
- OS Version: macOS 10.15.6

Steps to Reproduce:

1. Open a search editor and perform a search
1. Switch to another tab
1. Run "Open Search Editor" (without selecting any text in an editor) and sometimes all of the existing input text will be re-selected, but not always. I do this many times per day, and often it is selected, but sometimes it isn't. I can't figure out what the exact steps are to reproduce it, as it seems random to me.

Sorry @JacksonKearl but I'm tagging you on this one too ;)

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by JacksonKearl** [comment]
To verify: 
1. Have a search editor with some query in your workspace (open but not visible)
2. In some other editor, run "Open Search Editor" without any text selected 
1. Expect the search editor to become visible and the query field to be selected and focused.
6. Try focusing a variety of different elements in search editor (focus results editor, search query inputs, etc.), and repeat to verify that no matter where focus started, it is set to the query input box on running "Open Search Editor" with no selected text, and that the text in the box is selected.

**Comment by swrobel** [comment]
@JacksonKearl sounds exactly as I was imagining! 🚀

**Comment by swrobel** [comment]
@JacksonKearl I was really hoping this would come in 1.48.1 but will I have to wait until 1.49?
