### ISSUE TITLE
Extension host keeps crashing!

### ISSUE THREAD

**Issue by dkok1988** [microsoft/vscode#105057]
- VSCode Version:1.48.0(user setup)
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. It's random. It feels like a freeze than my i7 cpu starts to heavily load and fans are blowing than it crashes and I need to restart the host.
![Capture1](https://user-images.githubusercontent.com/42012449/90734621-8f62a080-e2cd-11ea-8f9a-a1abde67afac.PNG)
![Capture2](https://user-images.githubusercontent.com/42012449/90734631-8ffb3700-e2cd-11ea-98d4-532bfb839ed8.PNG)
![Capture3](https://user-images.githubusercontent.com/42012449/90734638-8ffb3700-e2cd-11ea-9f0f-e9e0c5d4a92e.PNG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Actually you disabled all extensions. Let me reopen and can you repro with vscode insiders?

**Comment by philsherry** [comment]
@isidorn I'm getting this on two Macs. Happy to help test anything that might fix it.

**Comment by dkok1988** [comment]
I found out that is was prettier. Somehow it couses conflicts. I think with my eslint. I disabled it and did not got the error for now in days. Tried the insiders, but that wont run well with my workspace project. It starts but, I can not colapse folders.
