### ISSUE TITLE
New version of vscode makes it impossible to overwrite read-only files

### ISSUE THREAD

**Issue by daltairwalter** [microsoft/vscode#105097]
In previous versions of vscode, attempts to save a readonly file would bring up a prompt for overwrite.  This has been replaced by an open as administrator link.  The other option is save as which brings up a save dialog and also doesn't allow overwriting read-only files.  Is there another way to overwrite read-only files now?

Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Please update to 1.48.1 that just came out, then retest and report back
