### ISSUE TITLE
Git: Support spawning git on a shell script

### ISSUE THREAD

**Issue by terroirman** [microsoft/vscode#105011]
- VSCode Version: 1.48.0
- OS Version: CentOS Linux release 7.7.1908

Description: 
I sometimes use machines where its not easy to install a newer version of git. For instance, CentOS 7.7.1908 ships with git 1.8. As a workaround, I use a docker container to quickly pull a newer version and use it instead of the os provided version. I'm trying to make vscode points to a wrapper script to use this git instance version and it doesn't work.

Example of what is happening through the OUTPUT->git console:
```
Looking for git in: /home/username/git.sh
Looking for git in: git
Using git 1.8.3.1 from git
...
```

Expected result would be something like:
```
Looking for git in: /home/username/git.sh
Using git 2.26.2 from /home/username/git.sh
...
```

Should I expect this to work ? Is this behavior by design ?

Note: I'm actually experiencing this through remote ssh. Can't really test this directly on my local machine (windows). So in practice, I am experiencing this issue when adding the git.path setting to the "Remote [SSH: host]" section of vscode settings. 

Steps to Reproduce:

1. Create a bash script /home/username/git.sh
```bash
#/bin/bash
(docker run -ti --rm -v ${HOME}:/root -v $(pwd):/git alpine/git "$@")
```
2. add this to the git.path setting through json
`"git.path": "/home/username/git.sh"`

3.  Reload vscode window

4. Check OUTPUT->Git console

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
The problem here is that probably Node can't spawn that shell script.
