### ISSUE TITLE
auto-indent issue with Ruby syntax

### ISSUE THREAD

**Issue by chriskacerguis** [Microsoft/vscode#10507]
- VSCode Version: 1.4.0 (1.4.0)
- OS Version: OSX (El Capitan) 10.11.6 (15G31)

Steps to Reproduce:

1. Create a new file (set language to "Ruby")
2. Type the following: "def test_foo" (press enter) -> no auto-tab
3. Type "if cond == true" (press enter) -> no auto-tab
4. Type "p 'hello'"
5. Type "end" (press enter) -> You will note here, that the "end" does not auto-align with the "if"
6. Type "end" (press enter) -> again, same thing, end should be aligned with the "def"

What I get from the above steps:
```ruby
def test_foo
if cond == true
p 'hello'
end
end
```

What I expect to have
```ruby
def test_foo
  if cond == true
    p 'hello'
  end
end
```

**Comment by orta** [comment]
I think this PR fixes that - https://github.com/rubyide/vscode-ruby/pull/37 - might want to see it's status on getting merged.

**Comment by aeschli** [comment]
Please file this against the ruby extension..

**Comment by chriskacerguis** [comment]
Hello @aeschli thanks for replying.  The issue is both on the vscode-ruby extension and on vscode.  It looks like this is contributing to the issue (https://github.com/Microsoft/vscode/issues/2262) I can confirm that the PR @orta referenced does not fix the issue (it does add the decreaseIndentPattern to the extension), however due to issue #2262 it doesn't fix the problem.  

Apologies for not looking into the issue more.

**Comment by rebornix** [comment]
@chriskacerguis the issue on Code side is #2272 and @alexandrudima confirmed it.
