### ISSUE TITLE
Run task script failed from package scripts

### ISSUE THREAD

**Issue by turnerguo** [microsoft/vscode#105049]
Issue Type: <b>Bug</b>

I got a new issue this morning, this maybe a new issue because it was running correct before latest update. 

```
> Executing task: npm run lint <

zsh:1: command not found: npm
The terminal process "/bin/zsh '-c', 'npm run lint'" failed to launch (exit code: 127).

Terminal will be reused by tasks, press any key to close it.
```

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.61GB free)|
|Process Argv|/Users/xxx/xxx|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.2.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
debugger-for-chrome|msj|4.12.10
quicktype|qui|12.0.46
code-settings-sync|Sha|3.4.3
open-in-browser|tec|2.0.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by alexr00** [comment]
Can you share any `terminal.*` and `task.*` settings you have?
How did you launch VS Code?
Can you toggle the developer tools (command palette -> Toggle Developer Tools) and in the console there run `process.env` and share the output?

**Comment by turnerguo** [comment]
@alexr00 I didn't customize my `terminal.*` and `task.*` settings, and I usually launch vscode directly click the app from dock.
BTW, my vscode working correctly today, I checked the version was changed to 1.48.1, maybe fixed in this version?
