### ISSUE TITLE
cann't use ctrl+v/x/c short cut when git clone

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#105043]
- VSCode Version: 1.48.0
- OS Version: 1607

Steps to Reproduce:

1. execute git clone

can't use ctrl+v to paste
![image](https://user-images.githubusercontent.com/1876302/90709386-a3f36880-e2ce-11ea-9a78-adfa78b6577b.png)
 
have to use right-click menu to paste
![image](https://user-images.githubusercontent.com/1876302/90709393-a786ef80-e2ce-11ea-8d89-43aae0cee3ed.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This works for me. Can you show me your full keyboard shortcuts?
