### ISSUE TITLE
Right click not working in Python Interactive and extension details panels

### ISSUE THREAD

**Issue by Fennehk** [microsoft/vscode#105071]
Version: 1.48.0 (system setup)
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
Steps to Reproduce:

1.  Launch a Python Interactive terminal
2. Right click in this panel, there should be a contextual menu with items such as copy, paste etc...
Nothing happens, even if you select text.

The same issue happens with extension details page.

**Comment by Fennehk** [comment]
It's been 11 days since the issue has been opened, and it has not been even acknowledged, is there a reason for that?

**Comment by Tyriar** [comment]
Right click in the terminal defaults to copying and pasting depending on whether there's a selection. See `terminal.integrated.rightClickBehavior` in settings.

**Comment by Fennehk** [comment]
The issue is with the Python Interactive terminal (which is a a kind of special terminal) the settings you suggest do not seem to affect the faulty behavior which is that no menu appears when you right click in that panel whether or not you've selected text.

**Comment by Tyriar** [comment]
Maybe ask https://github.com/microsoft/vscode-python then, it sounds like you just need to change your right click behavior setting though.

**Comment by Fennehk** [comment]
Sorry but it is not my role to investigate these sort of things. I do think it is a bug as it is the default behavior of the Python Interactive window. It seems that you haven't even tried to properly look at it or replicate it. So I won't spend more time on it and if you have more important to do be it.

**Comment by Tyriar** [comment]
@Fennehk this is the repository for VS Code. I do not know how you're launching this python interactive window, but Python support is handled by the VS Code Python team over there 👉 https://github.com/microsoft/vscode-python

If it's just a regular terminal, setting `"terminal.integrated.rightClickBehavior": "default"` will give you the context menu as I mentioned before:

![image](https://user-images.githubusercontent.com/2193314/91857997-818e1300-ec1d-11ea-8c5d-2c9e0c95effc.png)

![image](https://user-images.githubusercontent.com/2193314/91857798-44298580-ec1d-11ea-8713-5d4735edffae.png)

This is not the default behavior as mentioned in the documentation https://code.visualstudio.com/docs/editor/integrated-terminal#_right-click-behavior

**Comment by Fennehk** [comment]
Thanks for the response, it was unclear under which repo, this should be reported. I will close it then end reopen in the other repository.
