### ISSUE TITLE
I don't want to save as txt

### ISSUE THREAD

**Issue by gokhankocak** [microsoft/vscode#105080]
Issue Type: <b>Feature Request</b>

I'm tired of having to save the files as txt format.
I want to give an extension myself.
Everytime I have to go to the end of list of available formats and select "no extention".
This is very annoying.
I want to create a new file and I want to give the extention myself, I do not want to save every file as txt.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19041

**Comment by gjsjohnmurray** [comment]
Maybe this is #103704, which will be fixed in 1.48.1 very soon. Probably later today...
