### ISSUE TITLE
[css] property suggestions not correctly ordered 

### ISSUE THREAD

**Issue by GreatRequest** [microsoft/vscode#105039]
Issue Type: <b>Bug</b>

Started working with css and found that VScode (insiders) gives me some wild suggestions for the properties, eg. need "font-size: ;", first sugestion is "font-size-adjust: ;", need "line-height: ;" first suggestion is "line-height-step: ;". Can you please fix this, thanks.

VS Code version: Code - Insiders 1.49.0-insider (bd08768fd310d34cdd4423a53e5f3ca77340fea5, 2020-08-14T05:56:40.601Z)
OS version: Windows_NT x64 10.0.20190

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.87GB (8.47GB free)|
|Process Argv|O:\OneDrive\USER PROFILE\Desktop\Projects\Xanda Cutups\winnerlot-competitions --crash-reporter-id 195724cf-b023-494f-bd5b-8d48f67ba7b9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
php-intellisense|fel|2.3.14
html-slim-scss-css-class-completion|gen|1.7.5
phpcs|ika|1.0.5
sftp|lix|1.12.9
remote-wsl|ms-|0.44.4
vscode-scss-formatter|sib|2.0.1
code-spell-checker|str|1.9.0

</details>

**Comment by xuchenrui-z** [comment]
我草

**Comment by aeschli** [comment]
change: https://github.com/microsoft/vscode-css-languageservice/commit/5b588f21fbd69051b6a18e7e44997480721f9d9b

**Comment by AleksandrHovhannisyan** [comment]
This still seems to be a problem. I see this was part of the August milestone. Will it be released sometime this month?

**Comment by aeschli** [comment]
The August release has just been released (1.49). If you still see a problem, please file a new issue with a small code sample and a description of what you see and what you expect.
