### ISSUE TITLE
"Missing Shortcut" error when launching VS Code after update

### ISSUE THREAD

**Issue by alecoot** [microsoft/vscode#105095]
Issue Type: <b>Bug</b>

Setup - Yesterday while using VS Code, I was prompted to install an update - I installed and subsequently said "install later".

Later in the day, I had problems launching code. Here are my repro steps:

1) Press Start Menu
2) Type 'Visual Studio Code'
3) Select Visual Studio Code

Expected Outcome: VS Code launches
Actual Outcome: "Missing Shortcut - Windows is searching for code.exe" and "Problem with Shortcut" errors
![Missing code exe](https://user-images.githubusercontent.com/10603874/90805747-e7e76d00-e2d0-11ea-9e26-3823fc059dba.jpg)
![Missing code2 exe](https://user-images.githubusercontent.com/10603874/90805749-e9189a00-e2d0-11ea-86b9-8dfda6036819.jpg)
![VS Code Folder](https://user-images.githubusercontent.com/10603874/90805822-064d6880-e2d1-11ea-971c-743e59063506.jpg)
![Code App in '_' folder](https://user-images.githubusercontent.com/10603874/90805942-30068f80-e2d1-11ea-8853-43e0d992b316.jpg)

Debug notes: %programfiles%\Microsoft VS Code\code.exe is now missing, however there is a new "_" directory with a copy of code here: %programfiles%\Microsoft VS Code\_\code.exe

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:01:24.309Z)
OS version: Windows_NT arm64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Microsoft SQ1 @ 3.0 GHz (8 x 1670)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.47GB (9.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.8.101144
remote-wsl|ms-|0.44.4
azure-account|ms-|0.9.2
usql-vscode-ext|usq|0.2.15

</details>

**Comment by SamStonehouse** [comment]
Also had this issue, following the same process updating to 1.48.0.

I also happened to install a large Windows update this morning, prior to trying to open VSCode too, in case that is related.

**Comment by joaomoreno** [comment]
This appears to have been a broken update.

/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
