### ISSUE TITLE
`vscode://schemas/ignoredExtensions` is maybe wrong.

### ISSUE THREAD

**Issue by wraith13** [microsoft/vscode#105063]
- VSCode Version: 1.48.0
- OS Version: Windows

Steps to Reproduce:

1. Install [this extension](https://marketplace.visualstudio.com/items?itemName=wraith13.sysinfo-vscode).
2. Execute `System Information: Show Schema` command from Command Palette, And select `vscode://schemas/ignoredExtensions`.

Currently it is as below.

```json
{
    "type": "string",
    "pattern": "^([a-z0-9A-Z][a-z0-9-A-Z]*)\\.([a-z0-9A-Z][a-z0-9-A-Z]*)$",
    "errorMessage": "Expected format '${publisher}.${name}'. Example: 'vscode.csharp'."
}
```

Isn't this correct?

```json
{
    "items": {
        "type": "string",
        "pattern": "^([a-z0-9A-Z][a-z0-9-A-Z]*)\\.([a-z0-9A-Z][a-z0-9-A-Z]*)$",
        "errorMessage": "Expected format '${publisher}.${name}'. Example: 'vscode.csharp'."
    }
}
```

Does this issue occur when all extensions are disabled?: Yes/No

cf. https://github.com/wraith13/vscode-schemas/blob/master/en/v1.48.0/schemas/ignoredExtensions.json

**Comment by aeschli** [comment]
I assume `vscode://schemas/ignoredExtensions` is by you?

**Comment by sandy081** [comment]
There is nothing wrong with this schema - it represents the pattern that defined how each entry in the array shall be. Since values are dynamic they are not added to schema, instead, values are provided through completion provider.

**Comment by wraith13** [comment]
OK, Please, forget second comment.
Still, current schema seems wrong to me. And `settingsSync.ignoredExtensions`'s string pattern checking is not working in settings.json.

![image](https://user-images.githubusercontent.com/645907/91186017-7a509c00-e729-11ea-9728-c0a2ed767ca1.png)

**Comment by sandy081** [comment]
Good point, will open to investigate this.

**Comment by sandy081** [comment]
Removed this schema and inlined it/

**Comment by aeschli** [comment]
verified that schema is gone
