### ISSUE TITLE
Format Code Html inside <script> tag

### ISSUE THREAD

**Issue by HanojHanu** [microsoft/vscode#105053]
iam facing a problem like inside script tag format code is not happing.
`<script type="text/template" >`
`<div>`
`<span></span>`
 `</div>`
`</script>`

**inside tags or not Formating in html file**

**Comment by aeschli** [comment]
The html extension does not know the syntax scripts with`type="text/template". Therefore it will not attempt to format it. Note that formatting can also do harm as some contents must not be changed.

To get formatting your script tag must be for example `text/javascript`.
