### ISSUE TITLE
unable to start terminalprocess: CreateProcess

### ISSUE THREAD

**Issue by akhilesh2595** [microsoft/vscode#105078]
I am getting below error while in VS .
The terminal process failed to launch: A native exception occurred during launch (Unable to start terminal process: CreateProcess failed).

**Comment by akhilesh2595** [comment]
![image](https://user-images.githubusercontent.com/45933735/90773574-bd6ad380-e313-11ea-9b5a-667539451656.png)

**Comment by Tyriar** [comment]
Do you have anti-virus software installed? If so, try whitelisting the files listed here: https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch#_error-connectnamedpipe-failed-windows-error-232
