### ISSUE TITLE
Watch name and column should be spaced evenly

### ISSUE THREAD

**Issue by duzenko** [microsoft/vscode#105065]
When a watch name is too long then its value is obscured
Both the name and the value should be evenly spaced out, like in 'real' IDE's
![image](https://user-images.githubusercontent.com/1481807/90752083-a3af9900-e2df-11ea-896f-c49afff3967a.png)
![image](https://user-images.githubusercontent.com/1481807/90752299-e1142680-e2df-11ea-8e55-3af51b602ce3.png)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by duzenko** [comment]
😠
