### ISSUE TITLE
When installing VSCode extensions, if mv fails fall back to cp+delete

### ISSUE THREAD

**Issue by theSaarco** [microsoft/vscode#105068]
I'm running VSCode in a setup where the extensions directory is hosted on a FUSE mount in Linux. The fuse driver we have does not support mv operations for directories due to internal implementation reasons.
I'm using VSCode version 1.46 on a Docker container running Ubuntu 18.04, with the Fuse driver as mentioned.
 
When VSCode installs an extension, it starts by placing the extension files in /extension/path/.extension_name, and then attempts to rename the folder removing the leading dot in the directory name. This renaming operation fails in our case due to the fuse driver limitations (it returns an ENOTSUP response).

I couldn't find any record or documentation of a way to change or tweak this behaviour.
My proposal is for VSCode to attempt a mv operation and if that fails, fall back to performing a cp+delete operation for the extension files. Of course it's not optimal in terms of data processing and time taken, but it will expand support for VSCode to additional configurations.

**Comment by sandy081** [comment]
Reason we do move because it is a single transaction operation and on fail it will not leave in intermediate state. Where as with copy and delete, on failure/terminating copy can cause intermediate state.

I am sorry if we can do anything here.

**Comment by theSaarco** [comment]
Thank you for the answer. 
I certainly understand that a mv is easier to manage, but even in the mv case you still need to make sure you don't leave any intermediate state - after all, the temporary folder is still there is mv failed, and you still need to make sure you delete it (I've checked - vscode already does that when mv fails). 
So, there is already some sort of a cleanup stage in the process. If using cp then you just need to make sure you cleanup 2 folders on failure rather than a single one (on failure). Is that an unacceptable complication to the code?

**Comment by sandy081** [comment]
Yeah, we handle when mv fails. But it is mostly about if user quits or restart VS Code while this operation happening. In this case, with `mv`, the temporary dot folder exists but the original folder does not as this operation is atomic. So the extension can be shown as uninstalled after reopening VS Code. With `cp` we will not be sure if the original folder is complete or not causing to have broken extensions.

**Comment by theSaarco** [comment]
It can be done with a similar (but reversed) logic - if the dot folder does exist upon reopening then you know cp wasn't finished (since rm to the dot folder immediately follows the cp), and cleanup or attempted re-copy can be done. If the dot folder does not exist then you can assume extension is properly installed.

**Comment by sandy081** [comment]
What happens if VS Code shuts down exactly after cp is completed and before rm starts?
Also, I think rm (recursively removing a dir) is not atomic which would add more unknown states to handle right?
