### ISSUE TITLE
I want a "yank buffer"

### ISSUE THREAD

**Issue by jakeoshins** [microsoft/vscode#105096]
I use VSCode for lots of things, and because it is getting so much traction, I'd like to use it for everything I do.  There is still one thing really tying me to SlickEdit, though.  SlickEdit, like Emacs, allows me to copy lots of things and then paste them all in later.  Emacs calls this the "yank buffer."

In practice, what I do is to look at header files and other sources, thinking about the function that I'm about to write.  I go collecting all the type names, snippets of code that I need, etc, hitting "ctrl-c" on all of them.  Then I go to write my function, pasting lines from the yank buffer into the places where they belong.

When I copy all the source material, it goes onto what sort of looks like a stack of clipboards.  In SlickEdit, instead of hitting ctrl-v to paste, I hit ctrl-shift-v and a window pops up showing me all the recent things that are in that stack.  I can choose any one of them to paste.

I miss this deeply when using VSCode.  Thanks for listening.

**Comment by boltex** [comment]
Good idea for an extension bro. (seriously)

I might do it for fun... This will only take an evening or two : Mind giving me more details? Like is it OK to accumulate in that special buffer with another keyboard shortcut? if so which would you prefer to be consistent with slieckedit and emacs ? fallback options if not possible? 

 (The more details, and possibilities for flexibility to obtain the features you need, the easier to write.)

Thanks for your idea(s)!! 
--
Félix

**Comment by jakeoshins** [comment]
I'm not picky about key bindings.  Of course I'd like consistency with old editors, but that's not a hard requirement.  Thanks.

Both SlickEdit and Emacs always accumulate everything you copy with ctrl-c.  The yank buffer isn't "special" in that regard.  I guess what I'm saying is that this feature isn't really an extension to those editors but a very integrated thing.
