### ISSUE TITLE
[Feature request] Background image for Center Layout

### ISSUE THREAD

**Issue by quhsi** [microsoft/vscode#105001]
When having Center Layout enabled on a large screen, it would be nice to have a custom background image spanning the margins of the Center Layout. Something like that (achieved by manually editing `workstation.desktop.main.css` and thus breaking the VS Code installation):

![Screenshot](https://user-images.githubusercontent.com/66925589/90652265-6559a180-e22d-11ea-9bd3-5253957a8b12.jpg)

Why not choose such a wallpaper for the desktop and resize the whole window?

- Resizing the window when toggling sidebars becomes tedious.
- The desktop itself may be cluttered which may obstruct the Zen mode experience.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
