### ISSUE TITLE
Code can't be colored properly.

### ISSUE THREAD

**Issue by wanzzhehe** [microsoft/vscode#105041]
Issue Type: <b>Bug</b>

When I use vscode to write my code oneday, I found that my code's variable is just white.

Just like this ![](https://s1.ax1x.com/2020/08/20/d3s6MT.png), the variable v0, v1, a, b, c, and the TEST is white, not being colored.

I don't know whether it's a bug or just my wrong settings, but before the situation happened, I change nothing.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2601)|
|Memory (System)|15.92GB (6.83GB free)|
|VM|40%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.48.3
remote-wsl|ms-|0.44.4
vim|vsc|1.16.0
vscode-language-pack-zh-hans|MS-|1.48.3
cmake-tools|ms-|1.4.1
cpptools|ms-|0.29.0
cmake|twx|0.0.17

</details>

**Comment by alexr00** [comment]
Can you please provide a copy/pastable example? And, can you try disabling all extensions and see if the issue still occurs?
