### ISSUE TITLE
Feature request: reload button on git tab

### ISSUE THREAD

**Issue by J-Siu** [Microsoft/vscode#10506]
- VSCode Version:1.4.0
- OS Version:OS X

Steps to Reproduce:

1. Open a folder without git
2. Issue "git init" in that folder
3. VSCode git tab will not refresh unless re-opening the folder

![screen shot 2016-08-13 at 18 38 13](https://cloud.githubusercontent.com/assets/3171920/17646001/2cbc5818-6185-11e6-8d79-26e1c2d1e2cb.png)

It will be nice if the reload/refresh button is available in the above situation.

**Comment by joaomoreno** [comment]
That screenshot shows me that Code will never work on that folder simply because it has way too many files. Are you saying that it does open that folder, once you reload?

If you hit the Initialize button on a smaller folder, it will work, no need for a _reload_ button.
