### ISSUE TITLE
Random keystrokes in terminal

### ISSUE THREAD

**Issue by ManojNairOnline** [microsoft/vscode#105198]
- VSCode Version: 1.48.0
- OS Version: Ubuntu 20.04.1 LTS

Steps to Reproduce:

1. Add a project - new or existing. In my case Jekyll sites
2. Start Terminal to compile and start the server which runs in the background while I work on the code
Please note  I use a Docker image to execute the project server.. the command line for the execution is as under:
docker run --rm  --volume="/home/manoj/wiki:/srv/jekyll" -p 4000:4000  -it jekyll/jekyll:3.8 jekyll serve

3. This happens randomly - @ symbol appears on the terminal command line..The @ symbol repeats endlessly on the command line
4. This can happen at the start of the command being executed or half way through when the gems are being installed or load for during the compilation
5. If I stop the execution and open a normal Ubuntu console inside the project folder and execute the same command this issue with '@' never happens
6. Have been using Visual Studio Code for a couple of months without problem. This is a recent 1-2 month old issue.

Pl let me know if more details are required. In case this issue has been reported earlier , my apologies and pl point me towards the solution.

Does this issue occur when all extensions are disabled?: Yes/No - Not able to replicate as the issue is random

**Comment by Tyriar** [comment]
You can enable escape sequence logging to see what VS Code is sending to the process and what the process is sending back. This will identify whether the cause is with VS Code or the shell/Jekyll https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by ManojNairOnline** [comment]
Thanks @Tyriar for the info. Have enabled escape sequence logging and will share the log the next time it happens.

**Comment by ManojNairOnline** [comment]
This issue has not recurred after I enabled sequence logging. Closing the issue here.
