### ISSUE TITLE
VSCode with gdb remote attach support

### ISSUE THREAD

**Issue by chenxiemin** [Microsoft/vscode#10510]
- VSCode Version:1.3
- OS Version:Ubuntu 16.04

Hi, can vscode support remote gdb attach so that I can use it on Android native development?
I notice that vscode can config the attached process id on local machine, as folowing:
"processId": "enter program's process ID",

Is vscode already support gdb remote attach now? Or still need working on it?
Thanks very much.

Sincerely

**Comment by weinand** [comment]
@chenxiemin 'gdb' support is provided by an extension and is not part of VS Code. Please file this question against the gdb extension.

**Comment by chenxiemin** [comment]
Yes, I found the extension a few days ago, thanks.
