### ISSUE TITLE
Tests: Abort trap: 6 crash making them fail sometimes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#105136]
Ever since I think the Electron 9 update I sometimes see unit tests fail with the following output:

```
/scripts/test.sh: line 38:  4378 Abort trap: 6           ELECTRON_ENABLE_LOGGING=1 "$CODE" test/unit/electron/index.js "$@"
```

For example in: https://dev.azure.com/vscode/VSCode/_build/results?buildId=50971&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=b16e48eb-d187-5f92-5721-e17908fef4e2&l=13631

Unfortunately I am not seeing a crash dump attached, but maybe worth checking what is going on.

**Comment by deepak1556** [comment]
Closing this due to no new reports, please reopen otherwise.
