### ISSUE TITLE
Setting up the BASH config Settings.json after WSL2 installation

### ISSUE THREAD

**Issue by westerdaled** [microsoft/vscode#105131]
Hi
I have installed WSL2 as I want to run Azure CLI Kung fu which requires BASH terminal.
```
`
 WSL --list
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
docker-desktop-data
docker-desktop
`
```
Next I want to set up my Bash Terminal ( not as default) so I can select it in the Terminal drop down. Is there a tidy way to configure this ?

At the moment my settings.json has  a couple of issues:

```

  "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",     <- I want to be able to switch between shells
    
"shellLauncher.shells.windows": [{
        "shell": "C:/Program Files/PowerShell/7/pwsh.exe",
        "label": "PowerShell 7 Core"
    },
    {
        "shell": "C:/Windows/system32/WindowsPowerShell/v1.0/powershell.exe",
        "label": "Windows PowerShell 5.1"
    ,
    
  "terminal.integrated.shell.linux": "C:/Windows/sysnative/bash.exe"       <--- this is incorrect



```

Any suggestions are welcome. Note, I haven't installed GIT Bash shell up to now as I normally run all my commands from a PS terminal.

**Comment by Tyriar** [comment]
👍 this extension will likely get rolled into core eventually https://github.com/microsoft/vscode/issues/45444
