### ISSUE TITLE
Notebook deletes wrong cell

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#105109]
![Kapture 2020-08-20 at 14 42 30](https://user-images.githubusercontent.com/35271042/90828943-bd5adb80-e2f3-11ea-9a31-18633de2de1f.gif)

Steps to Reproduce:

1. Focus a code cell
2. Go to another cell that isn't focused and delete
3. :bug: the focused cell gets deleted

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Good catch, thanks!
