### ISSUE TITLE
Odd intellisense issue with JSDoc

### ISSUE THREAD

**Issue by alesbolka** [microsoft/vscode#105132]
Issue Type: <b>Bug</b>

I'm experiencing an odd intellisense issue in one of my projects. I have a certain approach to tests, where I define a factory function and annotate it with a JSDoc comment to show what it returns (see image example). Every module unit test will have a function like that.
In this particular project, I've noticed that the intellisense gets confused and starts picking up the definition from other files. Using "go to definition" on that function actually opens the other file. I have failed to find a deterministic way to reproduce this error, though simply cloning the repo and adding a new test will show this problem, sometimes in existing files as well. If I delete the file it incorrectly picks up the definition from, it will jump to another file and pick up its definition. 
Issue appears both on Ubuntu 20 and Windows 10, even with extensions disabled. I have yet to successfuly reproduce it from scratch in a new project. Copying the entire project folder and opening it as a new project retains the issue, copying only certain relevant files does not; does project size affect the intellisense? I have a few large js files with API reply examples for the purpose of testing, can I add them to an ignore list to not be parsed?
![example image](https://user-images.githubusercontent.com/7642917/90865582-d8305d00-e392-11ea-92d5-6aa8efb79a22.png)

Edit: I just noticed, I can also no longer open anything installed in node_modules by using "go to definition" on the require - it simply says "no definition found for X" (on a package like got or request), nor does it offer help when importing packages.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|15.47GB (5.45GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
mustache|daw|1.1.1
xml|Dot|2.5.1
terraform|has|2.2.0
material-icon-theme|PKi|4.2.0
jinjahtml|sam|0.15.0
scala|sca|0.4.2

</details>

**Comment by mjbvz** [comment]
Can you share exact steps on how to reproduce the problem

**Comment by alesbolka** [comment]
Hi, here are how I can reproduce it using the project I added you to (they are also in the readme on the master branch of the project):

1. Switch to the rate-limit branch in that repo
2. Open test/unit/api/rateLimit/RatePolicy.test.js
3. use "go to definition" on line 23 factory function call

You can also define a new test file (in any folder in my case) and copy the following code:
```javascript
const factory = () => {
  return 2;
}

describe('foo.test.js', () => {
  it('does things', () => {
    factory();
  });
});
```
Using the "goto definition" or implementation on the factory call inside the test for me leads to another file.
If you remove the test\unit\api\AuthAPI.test.js file, the factory definition in other files should jump to another file.

**Comment by mjbvz** [comment]
Can you please create a minimal repo that demonstrates this issue and share that. These types of problems are often configuration issues and it's not a good use of our time to debug through complex projects to discover this

**Comment by alesbolka** [comment]
I have tried reproducing it in a simpler project, but have unfortunately not been able to. I guess you can close it for now and I'll open another issue if I find another project with the same issue and identify the common link...
