### ISSUE TITLE
Unwanted "Preferences: Azure Extensions" option showing up

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode#105107]
In recent versions, whenever I search for "pref" commands, vscode has unwanted "Preferences: Azure Extension" showing up: 
![image](https://user-images.githubusercontent.com/2473545/90826597-1d13af80-e311-11ea-8e3b-2d0500591d2c.png)

Not only this is annoying because it takes over other commands, but also the option seems to be an ad for azure, because what it does it to open the "Extensions" view and search for "azure". 

I don't expect VS Code to start showing ads and promoting unwanted and unused microsoft services. 

Perhaps in future VS Code versions it will be necessary to install an ad blocker?

**Comment by phgmacedo** [comment]
There seems to be no way from removing this option, and preventing it from showing up in the menu. Awful and extremely annoying.

**Comment by sandy081** [comment]
@chrmarti It seems you introduced this for welcome page, not sure why it is shown in command pallette and under preferences category and you can use `SearchCategoryAction` action now.

**Comment by chrmarti** [comment]
@sandy081 Thanks, missed that! `SearchCategoryAction`s are not registered as commands it seems.

**Comment by sandy081** [comment]
Yeah it is not registered as a command. I see why you need a command. I would recommend following:

- Register open azure extensions action using [registerAction2](https://github.com/microsoft/vscode/blob/fe83bef/src/vs/platform/actions/common/actions.ts#L487) that executes `SearchCategoryAction` by passing Azure category.
- Make sure this is shown in command pallette.

**Comment by chrmarti** [comment]
@sandy081 Saw your advice late, using `CommandsRegistry.registerCommand()` now. Hope that is fine, thanks.
