### ISSUE TITLE
Restart to Update has a huge delay

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode#105114]
Issue Type: <b>Bug</b>

I noticed this during the Insiders phase of this version but always forgot to report it, but ever since the start of the last cycle, "Restart to update" takes ages on macOS. It happened that I was done working and hit the button and then completely forgot about it until an hour later VS Code opened up again.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:09:41.484Z)
OS version: Darwin x64 20.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
tasks|act|0.6.1
stylus|Ala|0.0.4
TabOut|alb|0.2.0
html-end-tag-labels|ant|0.3.0
color-info|bie|0.5.1
jsdoc-markdown-highlighting|bie|0.0.1
markdown-emoji|bie|0.0.9
markdown-mermaid|bie|1.8.1
markdown-shiki|bie|0.1.1
markdown-yaml-preamble|bie|0.0.4
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-github-actions|csc|0.7.0
postcss|css|1.0.9
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
ejs-vue|Dig|0.1.1
javascript-ejs-support|Dig|1.3.1
dotfiles-syntax-highlighting|dot|0.1.0
gitlens|eam|10.2.2
tsl-problem-matcher|eam|0.3.0
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
shell-format|fox|7.0.1
vscode-pull-request-github|Git|0.19.0
path-autocomplete|ion|1.15.0
markdown-extended|jeb|1.0.17
vscode-peacock|joh|3.8.0
selene-vscode|Kam|1.0.1
vscode-remark|mrm|1.2.1
vscode-scss|mrm|0.9.0
csharp|ms-|1.23.1
python|ms-|2020.8.101144
vscode-pylance|ms-|2020.8.1
remote-containers|ms-|0.134.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
powershell|ms-|2020.6.0
vetur|oct|0.26.1
vscode-ts-config-plugin|oct|0.2.0
material-icon-theme|PKi|4.2.0
vscode-css-peek|pra|4.0.0
qub-xml-vscode|qub|1.2.8
vscode-yaml|red|0.10.0
rust|rus|0.7.8
jinjahtml|sam|0.15.0
vscode-wow-toc|sta|0.0.2
code-spell-checker|str|1.9.0
vscode-stylelint|sty|0.85.0
lua|sum|0.20.3
shellcheck|tim|0.9.0
shell-launcher|Tyr|0.4.1
sort-lines|Tyr|1.9.0
windows-terminal|Tyr|0.6.0
vscode-todo-highlight|way|1.0.4
material-theme|zhu|3.8.5

</details>

**Comment by joaomoreno** [comment]
@deepak1556 Mind checking this out? Seems related to Squirrel.

**Comment by Stanzilla** [comment]
I noticed it with Figma as well, I think they are using Squirrel, too.

**Comment by andrewbranch** [comment]
I started getting this after updating to the macOS Big Sur beta. Let me know if you want me to run any profiling or anything.

**Comment by Stanzilla** [comment]
https://github.com/Squirrel/Squirrel.Mac/commit/a3a5b3f03b824441c014893b18f99a103b2603e9 might be worth a try

**Comment by deepak1556** [comment]
Can you check if this is an issue with exploration builds based on Electron 11 https://az764295.vo.msecnd.net/exploration/1441f82102c7fe5945c5135c2c518c5776ac2c62/VSCode-darwin.zip ?

**Comment by Stanzilla** [comment]
@deepak1556 do exploration builds get auto updates?

**Comment by deepak1556** [comment]
yup they do, we use exploration builds to test newer runtimes before promoting them to insiders and then stable. Electron 11 update will be pushed to insiders sometime early next week https://github.com/microsoft/vscode/pull/110759, so you can also wait and test then.

**Comment by Stanzilla** [comment]
I'll install exploration and report back with my findings, thank you!

**Comment by Stanzilla** [comment]
Tried it on Insiders today and it is still broken there, weird.

**Comment by rami3l** [comment]
@Stanzilla I checked today that, even 1.52.0-insider (f4187f2) is still base on Electron 9.3.5 :(

**Comment by Stanzilla** [comment]
oh maybe it was reverted?

**Comment by rami3l** [comment]
@Stanzilla Let's hope that #111931 will finally get merged 🚀
