### ISSUE TITLE
Multiple Explorers

### ISSUE THREAD

**Issue by sandorvasas** [microsoft/vscode#105194]
I know this might be a far-fetched idea, but for me personally it would be very useful to have multiple project explorers side-by-side. I.e. use case: I have a subdirectory in my project root dir that contains results (logs) of each run of  my program. A new log file is generated at each run, so this folder quickly gets populated with 100+ files and it becomes difficult to scroll up and down. Another use case is when node_modules folder is open with its 1000+ packages. It'd be practical to have one explorer open for the project as now, and another on its right side to browse other folders.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks
