### ISSUE TITLE
Matching multiline problems does not work for problems with more than 2 lines

### ISSUE THREAD

**Issue by bojomojo** [microsoft/vscode#105150]
- VSCode Version: 1.48
- OS Version: Mac OS Catalina

My task outputs something like this:

../../file/path/name.c(450:12) : error: (error line 1)
error line 2
error line 3
error line 4
error line with a different pattern

there could be more lines in between. Can we accumulate patterns?

**Comment by sandy081** [comment]
not sure what you mean by accumulating, can you please explain in detail about your use case.

**Comment by bojomojo** [comment]
It means To have one problemmatcher matching 
Problem 1 line 1
Problem 1 line 2

And
Problem 3 line 1
Problem 3 line 2
Problem 3 line 3

**Comment by sandy081** [comment]
@alexr00 Assigning to you as it seems related to problem matcher.

**Comment by alexr00** [comment]
This would be accomplished using programmatic problem matching: https://github.com/microsoft/vscode/issues/59337
