### ISSUE TITLE
Progress bars should have a way to report what they are about

### ISSUE THREAD

**Issue by rslemos** [microsoft/vscode#105162]
Issue Type: <b>Bug</b>

This is a rather general issue on vscode UX choice for it's busy indicator (aka throbber, or "that flying dash under assorted elements throughout the interface").

Whenever my vscode is busy for a long time, I'm always curious about "what is going on". Nowhere is this information available, and it should be.

I have simply many issues with git and typescript in vscode, but I can't even start writing the issues, because you will "need more information".

That's it: to start, I think there should be a clear indication about tasks that were started but not completed... something that tells us why is there a "flying dash" under open file tabs, or under "explorer view title", or elsewhere.

VS Code version: Code - Insiders 1.48.0-insider (2277c8e2a3e1cc630a6397301ba54a1dccd8a60d, 2020-08-07T11:32:09.993Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3340 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.44GB (3.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
xml|Dot|2.5.0
gitlens|eam|10.2.1
vscode-lombok|Gab|1.0.1
java-properties|ith|0.0.2
git-graph|mhu|1.23.0
vscode-typescript-tslint-plugin|ms-|1.2.3
java-ide-pack|pve|1.2.1
java|red|0.59.1
vscode-xml|red|0.11.0
vscode-yaml|red|0.8.0
vscodeintellicode|Vis|1.2.7
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.1
vscode-java-test|vsc|0.22.3
vscode-icons|vsc|10.1.1
vscode-java-saber|You|0.1.1

</details>

**Comment by alexr00** [comment]
Sounds like something that could be added with the progress service. Assigning to @bpasero.

**Comment by bpasero** [comment]
@rslemos can you give a suggestion for how to improve this, maybe for the particular thing with fulltext search?

**Comment by rslemos** [comment]
I suppose that many "flying dash rails" are shared by many tasks, so you could **at least** have a tooltip on these rails telling which task prompted the progress bar to be shown. This is the very least, I think... **a string we could cling onto**, so that we have the opportunity to google around.

But it could be more... a view of ongoing tasks, where said tasks could update their status. For example, a long running task that scans files could update this view before trying the next file/folder. If some file/folder is taking longer than usual, I'll know there is a problem there (maybe a lock?).

And finally, it seems to me that some of these eternally running tasks are realy gone.... an error has perhaps been thrown and the task is forever lost. If this is really the case, such errors must be caught (to be shown on the view of ongoing - now zombie - tasks?).

**Comment by bpasero** [comment]
@rslemos we do have support to show long running tasks as notifications in the notification center (bottom right) and that gives users a chance to report more detailed info about the task as well as giving the user a chance to cancel or see output from the task. 

But this needs adoption for anyone that wants to appear there and it may be not the ideal place given it is disconnected from where you triggered a task (e.g. search).

But I like the idea of indicating in the progress bar somehow what the task is about.

**Comment by misolori** [comment]
I'd imagine something _like this_?

![image](https://user-images.githubusercontent.com/35271042/91320207-1e5e3580-e772-11ea-8a03-0069ceee801d.png)

**Comment by rslemos** [comment]
In the case you presented (the "search view"), the flying dash rail is not shared by many tasks (I suppose), so this generic message won't be very helpful... perhaps it could state where in the tree (either folder or file) it is looking currently; if the search is working correctly (i.e., it is not blocked and has not bailed out), this message will appear flashing many strings in a short time, then vanish... this is expected for. If blocked or bailed out, we'll know where and will have the chance to remediate the situation (perhaps killing another process that is locking a file for instance).

But my issue is more general. I'm actually complaining about the rails that are shared, like that one under the open files tabs, or the one in "explorer view". These are the most problematic ones, since we can't even have a glimpse of what is happening under the hood.
