### ISSUE TITLE
Support predefined variables in find/replace

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#105144]
Sometimes i would like to replace an occurrence with the fileName of that file, or do something a little more dynamic.
I don't know how feasible this is, but it would be really useful if you could use these variables inside the replace box.

**Example:**
I have many files that export default, i need to individually change them one by one to match up with the fileName.
If i could use the variable i could do this action in one go. 
![image](https://user-images.githubusercontent.com/936006/90883806-695cff00-e3a6-11ea-8681-8d3e27bbf4c6.png)

I understand some of these variables are not applicable, like `execPath` and `selectedText`.
but things like the filename and directory would be great to use.

## Variables Reference
https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables

**Comment by JacksonKearl** [comment]
This is an interesting idea and I can see the potential benefit, though as it stands the major concern I have is how escaping this would work. We currently support escaping to substitute and modify regex in the replace input, but that's somewhat different from this.

**Comment by jasonwilliams** [comment]
@JacksonKearl thanks for picking this up. Do you have any ideas? What is different about the Regex escape that can’t be copied for this?

**Comment by JacksonKearl** [comment]
Hm, looking at it now it seems we don't really allow for escaping escape regex capture group identifiers either. I will look more into this if it gets accepted for backlog 🙂

**Comment by jasonwilliams** [comment]
@JacksonKearl isnt the syntax slightly different? Regex being $1 and variables being ${}

**Comment by JacksonKearl** [comment]
That is correct. I'm not sure what your point is though?

**Comment by jasonwilliams** [comment]
Ignore me I think I misread your earlier comment, I’m guessing you mean named capture groups would be the same syntax and you don’t support them either right now
