### ISSUE TITLE
Terminal io encoding

### ISSUE THREAD

**Issue by caoyunxuan07** [Microsoft/vscode#10519]
- VSCode Version:1.4
- OS Version:Windows7 64bit

Steps to Reproduce:
When I use VSCode to write some python program (with python plug-in)
1. set Terminal (cmd.exe) encoding as utf-8 and set font as console
2. set enviroment variable PYTHONIOENCODING as utf-8
then i can print some Chinese word or special symbol like ♥(\u2665) and input chinese on Terminal.
I can output and input Chinese in VSCode too before i do step 2 because default io encoding is gbk, which supports Chinese word.
But now Terminal in VSCode show mojibake when I print and input Chinese word.

`"files.encoding": "utf8",` 
```
key = input(('中文:'))
print(key)
```

**Comment by Tyriar** [comment]
Can you add a screenshot? Also where are you setting the terminal encoding, in cmd.exe's properties?

**Comment by caoyunxuan07** [comment]
input `CHCP 65001` in command line. 
em...you remind me.maybe I can do this in VSCode integrated terminal too...
it's solved. integration terminal is a different one with system build-in?

**Comment by Tyriar** [comment]
You can't currently change the encoding in the integrated terminal, is this a feature you would want?

**Comment by caoyunxuan07** [comment]
I can't change it from a setting option, but I can check io encoding by enter `CHCP ` (show 936, the gbk code at first) and change it by enter `CHCP 65001`(65001 is the utf8 code) just like what i do in windows cmd.exe.
that's totally worked. Although I got a EOFError when input some chinese word, this would be a python problem.
Thanks anyway. : )

**Comment by jwknz** [comment]
Hi - yes I would really like this feature. Having to use an external terminal app just to make sure my encoding is all correct seems a little overkill - can this be integrated please?
