### ISSUE TITLE
References view should automatically reload after TS initializes

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#105184]
In TS there's now the mode where it works in the local file until the entire project is initialized. So there's now a case:

1. Open some large project
1. "Find all references" on an identifier
1. References view opens but stays empty or displays a subset of results forever

It would be very nice if the references view was able to automatically update after the project has finished loading instead of requiring me to re-run find all references later.

**Comment by jrieken** [comment]
Hm... Not so easy as there is no (API) event when a provider is added or removed...
