### ISSUE TITLE
Heavy CPU usage when waiting for admin credentials before update

### ISSUE THREAD

**Issue by tpoatsy3** [microsoft/vscode#105105]
Issue Type: <b>Bug</b>

While VS Code was waiting for administrator credentials up to update, the process "Electron" ran the CPU consistently at rates above 90%. This started while I was using a different account on my Mac. As soon as I changed users and entered my admin credentials, it resolved.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
python|ms-|2020.8.101144
LiveServer|rit|5.6.1
vscode-scss-formatter|sib|2.0.1
vscode-djaneiro|the|1.4.2

</details>

**Comment by deepak1556** [comment]
Is this still an issue with our latest insiders https://code.visualstudio.com/insiders ?
