### ISSUE TITLE
Web: problems counter disappears when output panel is clicked

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#105138]
Steps to Reproduce:

1. open https://vscode-web-test-playground.azurewebsites.net/?enter=true
2. bring up the panel
3. notice the "2" at the problems place
4. click on Output

=> 🐛 the 2 is removed from the problems badge

![recording (1)](https://user-images.githubusercontent.com/900690/90872042-4d546000-e39c-11ea-8089-0ad694b5d560.gif)

//cc @sandy081

**Comment by sandy081** [comment]
This is because web playground extension is resetting the problems when Output panel is opened. Output panel contains editor and window active editor is set to it.
