### ISSUE TITLE
Can version control support add git tags

### ISSUE THREAD

**Issue by rustedwizard** [microsoft/vscode#105115]
Please correct me if I am wrong. I think VSCode does not support add tag to git repository. As a result, I have to do it in command line. Can we have that capability in VSCode please.

**Comment by SneakyFish5** [comment]
Is the first option, `Git: Create Tag`, not what you're looking for?

![Screenshot (2)](https://user-images.githubusercontent.com/32284796/90840917-e5acff00-e320-11ea-9393-e626eee99098.png)

**Comment by rustedwizard** [comment]
Thanks, I completely forget about that.
