### ISSUE TITLE
 i cant use the caret

### ISSUE THREAD

**Issue by lunabartolozzi** [microsoft/vscode#105106]
Issue Type: <b>Performance Issue</b>

Hi, for a few days the caret has been blocked and it does not let me write or edit the text, just select letters but I can not write in my project in any way.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T08:03:27.059Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2557M CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    94	   623	code main
    0	    49	   629	   gpu-process
    0	    12	   631	   utility
    0	   242	   632	   window (Configuración)
    0	    66	   642	     extensionHost
    0	    25	   662	       /private/var/folders/fz/8byt80q569g4s_6xvrvk1v7w0000gn/T/AppTranslocation/79648DCA-FA33-490E-865B-3AB34CB04CB3/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /private/var/folders/fz/8byt80q569g4s_6xvrvk1v7w0000gn/T/AppTranslocation/79648DCA-FA33-490E-865B-3AB34CB04CB3/d/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=642
    0	    20	   682	       /private/var/folders/fz/8byt80q569g4s_6xvrvk1v7w0000gn/T/AppTranslocation/79648DCA-FA33-490E-865B-3AB34CB04CB3/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /private/var/folders/fz/8byt80q569g4s_6xvrvk1v7w0000gn/T/AppTranslocation/79648DCA-FA33-490E-865B-3AB34CB04CB3/d/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=642
    0	     0	   715	     /bin/bash -l
    2	    53	   638	   shared-process
    0	     0	   723	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    3	    70	   720	   window (Notificador de problemas)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
bracket-pair-colorizer-2|Coe|0.2.0
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.1.3
todo-tree|Gru|0.0.178
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-pack-es|MS-|1.48.3
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.2.0
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
bunker|sld|1.1.6
open-in-browser|tec|2.0.0
vim|vsc|1.16.0
vscode-todo-highlight|way|1.0.4
emmet-live|yse|1.0.0

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
@lunabartolozzi It looks like you have installed the `vim` extension. That extension enables a completely different way to interact with the text of the editor. It appears that you did not want to install it, so simply disable or uninstall the `vim` extension.
