### ISSUE TITLE
Unable to update VSCode

### ISSUE THREAD

**Issue by angusgraham** [microsoft/vscode#105169]
- VSCode Version: 1.47.3 (System Setup)
- OS Version: 1903

Steps to Reproduce:

1. Install Update

Does this issue occur when all extensions are disabled?: Yes

When updating VSCode it always fails.
I have to install and do a fresh install to update.
This has been the case for years.
First I get a dialog that says 
<img width="350" alt="dialog1" src="https://user-images.githubusercontent.com/11641291/90910129-b54e7a80-e38b-11ea-899b-5ca2786acb92.PNG">

----------------------------------

There was an error while marking a file for deletion:

Failed to mark file for deletion: Access is denied.

Please verify there are no Visual Studio Code processes still executing.
[Retry] [Cancel]

----------------------------------

I have verified that; these are the VSCode processes that are running:
inno_updater.exe
CodeSetup-stable-3dd905126b34dcd4de81fa624eb3a8cbe7485f13.exe
CodeSetup-stable-3dd905126b34dcd4de81fa624eb3a8cbe7485f13.tmp

No amount of Retrying works.

Pressing cancel leads to another dialog that says:

----------------------------------

Failed to install Visual Studio Code update.

Updates may fail due to anti-virus software and/or runaway processes. Please try restarting your machine before attempting to update again.

Please read the log file for more information:
C:\Users\grahama\AppData\Local\Temp\vscode-inno-updater-1598025104.log

----------------------------------
<img width="389" alt="dialog2" src="https://user-images.githubusercontent.com/11641291/90911270-95b85180-e38d-11ea-9006-d6215b91b974.PNG">

[vscode-inno-updater-1598025104.log](https://github.com/microsoft/vscode/files/5109858/vscode-inno-updater-1598025104.log)

Restarting does not fix the problem.

This machine does seem to have some "Endpoint Security" installed by corporate called "Crowdstrike Falcon". Obviously uninstalling it is not an option.

All other software is able to update correctly.

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
