### ISSUE TITLE
Is it possible to have Intellisense for application defined constants?

### ISSUE THREAD

**Issue by cankut** [Microsoft/vscode#10518]
- VSCode Version: 1.5.0

```javascript
(function () {

    var app = angular.module('app', [])
    .constant('MY_CONSTS', {
        foo: 'foo',
        bar: 'bar'
    });

    app.run(function (MY_CONSTS) {
        //MY_CONSTS.
    });

} ());
```

Like this:
![image](https://cloud.githubusercontent.com/assets/6057634/17649535/672a7802-6240-11e6-9b9d-4c8f1ab9fdea.png)

Instead of this:
![image](https://cloud.githubusercontent.com/assets/6057634/17649541/934ec51e-6240-11e6-92d2-b6345946ea82.png)

**Comment by jrieken** [comment]
You can create a `d.ts` file as part of your project which defines this, like so
```
declare const MY_CONST = {
 foo:string;
 bar:string;
}
```
