### ISSUE TITLE
Always displays 0 Projects

### ISSUE THREAD

**Issue by aaronOS** [Microsoft/vscode#10511]
- VSCode Version: 1.4.0
- OS Version: El Capitan 10.11.6

When opening the folder where my Unity projects are and selecting one of those, the lower right project icon always displays 0 projects. Even though I select any of the two example projects I made, it just goes to "running" before displaying 0 projects again. Why does this happen?

I attached two photos.
<img width="604" alt="screen shot 2016-08-14 at 2 22 33 am" src="https://cloud.githubusercontent.com/assets/17736280/17648357/17c47080-61c6-11e6-8755-ede4234c8615.png">

<img width="1026" alt="screen shot 2016-08-14 at 2 18 35 am" src="https://cloud.githubusercontent.com/assets/17736280/17648355/11bef3f4-61c6-11e6-95ca-5bdb259ac033.png">

**Comment by aaronOS** [comment]
I also seem to be missing the csharp.sln file for the project. I only have the .sln file. Does this have something to do with it just saying 0 projects? Also, the Omnisharp log shows this

[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/Users/Shared/Unity/Spaceship Project'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files

What does this mean? 

PS I am a student trying to learn how to code and I am completely baffled as to why it only shows 0 projects beside the little flaming icon. Im sorry if this is so simple but I am thoroughly confused right now.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#658

**Comment by aaronOS** [comment]
Sorry! :)
