### ISSUE TITLE
Does not detect change of spaces

### ISSUE THREAD

**Issue by hckhanh** [Microsoft/vscode#10516]
- VSCode Version: 1.5.0-insider
- OS Version: Windows 10 (version 1607)

As you can see this, the last two lines does not be highlighted. I think it should be a UI bug.
It doesn't detect the change of spaces

![image](https://cloud.githubusercontent.com/assets/6380436/17649280/0e50a1c8-625b-11e6-903c-669bb36450c7.png)

**Comment by jrieken** [comment]
There is a setting for this. To reduce visual noise it's turned off by default

![screen shot 2016-08-15 at 10 51 37](https://cloud.githubusercontent.com/assets/1794099/17659936/3ba93678-62d6-11e6-83a7-31fcc646681c.png)
