### ISSUE TITLE
Fail to start up WSL as appropriate user resulting in RLS startup failure

### ISSUE THREAD

**Issue by axler8r** [microsoft/vscode#105122]
We have written the needed da
Issue Type: <b>Bug</b>

I've customized an Ubuntu 20.04 WLS distribution to serve as a base for more WSL instances. I created a user called sysadmin as part of the initial WSL Ubuntu setup. I exported he distro and imported it as U2004R for Rust development. I installed all the rust stuff and added the RLS and so on.

Now when I start the U2004R with `wsl -u sysadmin -d U2004R` from the Microsoft Terminal App it logs me in to the U2004R instance as sysadmin. When I navigate to my project folder and start Visual Studio Code with `code .` it starts VS Code as root, hence I keep on getting "Couldn't start client Rust Language Server" and "Rustup not available..." errors.

When I open an integrated terminal and type `whoami` it reports root. Executing `rustc` or `cargo` fails because those tools were installed for sysadmin. Switching users in the terminal with `zsh -l sysadmin` solves the issue of the missing tools, but there is no way to start RLS as sysadmin.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (22.06GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+U2004R/home/sysadmin/Projects/Azure/decor8r --remote=wsl+U2004R|
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|WSL: U2004R|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|Memory (System)|24.95GB (24.57GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.134.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
material-icon-theme|PKi|4.2.0
vim|vsc|1.16.0
asciidoctor-vscode|asc|2.8.3
better-toml|bun|0.3.2
rust|rus|0.7.8
vim|vsc|1.16.0

(1 theme extensions excluded)

</details>
ta into your clipboard because it was too large to send. Please paste.

**Comment by aeschli** [comment]
The Remote WSL extension always uses the default user of the distro. So one way to solve your problem is to set the default user:

`ubuntu config --default-user username`
or
in `etc/wsl.conf`: see https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-18980

We have issue https://github.com/microsoft/vscode-remote-release/issues/286 to support a non-default user.
