### ISSUE TITLE
Duplicate identifier - NPM with Typings

### ISSUE THREAD

**Issue by giacomorebonato** [Microsoft/vscode#10517]
- VSCode Version: Version 1.5.0-insider (1.5.0-insider)
- OS Version: OS X El Capitan

Steps to Reproduce:
I am working on a Typescript front-end project and I am using Firebase 3, which already comes with Typescript Typings in the package.

If I install the Typings separately ```typings install npm~firebase``` the intellisense experience in VSCode is great... but during compilation I get the duplicate identifier message, because the typings are present 2 times  
```
ERROR in [default] /Users/grebonato/JavaScript/mino_material/node_modules/firebase/firebase.d.ts:374:2
Duplicate identifier 'export='.

ERROR in [default] /Users/grebonato/JavaScript/mino_material/typings/modules/firebase/index.d.ts:498:0
Duplicate identifier 'export='.
```

Instead if I don't install the typings separately, the compilation works fine, but VSCode doesn't see the typings in the NPM package

<img width="658" alt="firebase" src="https://cloud.githubusercontent.com/assets/630796/17649459/d9c31bfc-622d-11e6-94b0-f23d482f7a41.png">  

How am I supposed to make VSCode aware of NPM Firebase Typings ?

**Comment by TheColorRed** [comment]
Have you installed the typings in the project?

```
tsd install firebase
```

**Comment by giacomorebonato** [comment]
I am using [typings](https://github.com/typings/typings).  
```typings install npm~firebase```  
As I have explained if I do this VSCode becomes aware of Firebase, but Typescript compiler throws out the warning.  

Why should I install the typings again if they are already inside the npm package in node_modules?

**Comment by TheColorRed** [comment]
Sorry, I missed that line. 

According to the config docs (https://www.typescriptlang.org/docs/handbook/tsconfig-json.html), adding the exclude will exclude the file.

> If the "exclude" property is specified, the compiler includes all TypeScript (*.ts or *.tsx) files in the containing directory and subdirectories except for those files or folders that are excluded.

So, having this in your `tsconfig.json`, should get rid of the compile error if I am not mistaken.

```json
{
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by giacomorebonato** [comment]
I already have this in my tsconfig.json  
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": false,
        "jsx": "preserve",
        "sourceMap": false,
        "removeComments": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    },
    "exclude": [
      "node_modules"
    ]
}
```  
I am able to get rid of the compiler error only if I don't install the definitions through the typings tool, but the VSCode doesn't recognise Firebase (probably because of the exclude flag).  
So... as you are pointing out the problem could be Typecript ignoring the exclude list?

**Comment by TheColorRed** [comment]
It could be that it just can't find them. In my project installing the definitions isn't always enough, you sometimes need to also have a reference to them.

So, in my project I am using `Reflect`, and I could not get it to recognize that the files existed, so I had to add a reference to the definition file like this:

```js
/// <reference path="../../../node_modules/reflect-metadata/Reflect.d.ts"/>
```

vscde was then able to recognize the import along with being able to compile to javascript.

**Comment by giacomorebonato** [comment]
When you run ```typings install <package>``` it creates the following file with all the typings dependencies.  
```
/// <reference path="globals/mocha/index.d.ts" />
/// <reference path="globals/node/index.d.ts" />
/// <reference path="globals/react-dom/index.d.ts" />
/// <reference path="globals/react-flex/index.d.ts" />
/// <reference path="globals/react/index.d.ts" />
/// <reference path="globals/service_worker_api/index.d.ts" />
/// <reference path="modules/firebase/index.d.ts" />
/// <reference path="modules/react-router/index.d.ts" />
```

**Comment by waderyan** [comment]
@giacomorebonato thank you for bringing this issue to our attention. 

I have tried to recreate your issue, but have not been able to. Can you run through these steps and tell me 

1. if I did something different than you described above or 
2. you can see it on your machine even though I can't on my mine? 

Here is a [link](https://github.com/waderyan/vscode-js-samples/tree/master/intellisense/typescript-firebase) to the repo I'm working off of. 

1. I opened a new window of VS Code
2. I created a new directory `typescript-firebase`
3. I created a new file `main.ts`
4. I created a new `package.json` file. 
5. I created `tsconfig.json` with your contents. 
6. I installed typings with `typings install npm~firebase` as you described above. 
7. I installed firebase with `npm install --save firebase`
8. I compiled `main.ts` with `tsc` (no parameters, I simply ran `tsc` in the directory). 
9. I confirmed `main.js` was created as expected. 

Here are the contents of my files. 

main.ts
```
import firebase = require('firebase');

console.log(firebase.SDK_VERSION);

console.log('hello world');
```

main.js (after compilation)
```
"use strict";
const firebase = require('firebase');
console.log(firebase.SDK_VERSION);
console.log('hello world');
```

package.json
```
{
  "name": "typescript-firebase",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "firebase": "^3.3.0"
  }
}
```

tsconfig.json
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": false,
        "jsx": "preserve",
        "sourceMap": false,
        "removeComments": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    },
    "exclude": [
      "node_modules"
    ]
}
```

Full directory
![image](https://cloud.githubusercontent.com/assets/2449568/17826840/a9bf9f0c-6629-11e6-8c0d-7923a3aae2e7.png)

**Comment by giacomorebonato** [comment]
it is exactly what I am doing. I will try again with a clean project and close the issue if it works.

**Comment by giacomorebonato** [comment]
Tried again with a small example and the problem is NOT present.
Thanks for your time.

**Comment by waderyan** [comment]
No problem. @giacomorebonato if you can isolate the problem in a different way let me know and we'll try and track it down.

**Comment by giacomorebonato** [comment]
Ok, I am going to re-open this.  
I have isolated the problem [in this repo](https://github.com/giacomorebonato/firebase_ts_problem).
I think this is a problem with Typescript that doesn't seem to exclude the typings in the node_modules... even though it is in the exclude list.

**Comment by waderyan** [comment]
Excellent. Thank you for the clear steps. Moving to TypeScript as this is a TS issue.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10504
