### ISSUE TITLE
Files were Problems are detected are not listed in the same order they are detected

### ISSUE THREAD

**Issue by bojomojo** [microsoft/vscode#105146]
- VSCode Version: 1.48
- OS Version: Mac OS Catalina

Steps to Reproduce:

1. Run any task with an attached problemMater
2. The files were the problems are detected are sorted in an unknown order. I expected them to be sorted in the same order they are detected.

My task does run quite some tests, and the problem matcher catches the errors in those tests (eqch file has a number of test cases. Due to the nature of the tests, I would like to fix problems that are detected first before others.

Note: Problems within a file are sorted correctly. However the files themselves are wrongly sorted in the problems view

**Comment by sandy081** [comment]
/duplicate

#62942
