### ISSUE TITLE
Too fast vertical scrolling in terminal with font Ubuntu Mono or with larger font size

### ISSUE THREAD

**Issue by mirao** [Microsoft/vscode#10513]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04
- HW: HP Envy 13" Skylake, with touchpad

**Steps to Reproduce:**

1. Set font `"editor.fontFamily": "'Ubuntu Mono'"` with default font size = 14 or another font (e.g. 'Courier New' or 'Liberation Mono') with font size = 18
2. Open integrated terminal
3. Make some longer output
4. Scroll up and down in the terminal window

**Expected result:**
* normal speed (as in gnome-terminal)

**Actual result:**
* very fast, hard to scroll to a specific line

**Comment by Tyriar** [comment]
The scrolling changed a lot in the latest build with the introduction of the scroll bar, it should not feel like a native scroll view. Can you try out in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by mirao** [comment]
I can confirm the issue isn't in 1.5.0-insider-2016-08-15T05:59:29.052Z
Good to know insiders builds exist, thanks.
