### ISSUE TITLE
Test: debug console filter

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#105185]
Refs: https://github.com/microsoft/vscode/issues/20838

- [x] anyOS @roblourens
- [x] anyOS @kieferrm

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23105185%0A%0A)

---

Debug console now supports a filter. So start debugging (for example our smoke test express applicatino), have some output in the debug console and verify:

* As you type in the filter input the debug console content gets filtered. 
* You can do exclude patterns when you start your input with `!`
* `esc` clears the filter and tree is reset
* You can use `up` / `down` to navigate through previous filters
* Cmd + F focus on the filter input field

**Comment by shashikantdurge** [comment]
It does not focus on the Filter input field on keyboard shortcut Cmd+F

**Comment by isidorn** [comment]
@shashikantdurge thanks for pointing this out. I have tackled it via dd3e9ee04b and should be available in VS Code insiders from Monday.

**Comment by roblourens** [comment]
I think a search mode would be useful in addition to a filter mode

**Comment by isidorn** [comment]
@roblourens yeah good idea. When we introduce Find in the Debug Console it should be merged with this experience - so there is just an inline toggle to switch between the two.

**Comment by roblourens** [comment]
Maybe. I think they can be used together as well.
