### ISSUE TITLE
Ctrl+0 to restore zoom level

### ISSUE THREAD

**Issue by uipoet** [microsoft/vscode#105171]
In web browsers, we can zoom in/out with `Ctrl`+`+`/`Ctrl`+`-`. We can also return to the default zoom level with `Ctrl`+`0`.

In VSCode, we can zoom in/out with the identical shortcuts. However, there is no way to restore to the default zoom level. The shortcut `Ctrl`+`0` is instead mapped to focusing the sidebar.

Proposing:

- reassign sidebar focus to an alternate shortcut
- add a preference for preferred default zoom level (defaults to 0)
- add a new method to reset zoom level to the preferred default zoom level
- assign new reset zoom level method to `Ctrl`+`0`

By making VSCode's zoom shortcuts mirror browsers, new users will not have to learn anything new. Context switching between VSCode and a browser becomes simpler. When presenting code via screen sharing, it is common to bump up the zoom level a few notches until viewers acknowledge readability is achieved. Returning the the exact previous zoom level afterword is tedious.

**Comment by SneakyFish5** [comment]
Switching around the keybindings is easy enough, however I'm confused about the other requests about a default zoom and a new method for that. I agree that reset zoom should be `Ctrl + 0` to be inline with browsers.

**Comment by uipoet** [comment]
@SneakyFish5 The default zoom of `0` is way too small on my monitor, so I manually change my zoom to `2`. I need a way after increasing it to `4` or `5` when screen sharing back to `2`, instead of resetting to `0` and then needing to zoom twice to get back to `2`.

**Comment by joshuacookdev** [comment]
@uipoet - it seems like you want 2 things: 

1. setting ```Ctrl + 0``` as the default keybinding for reset zoom
2. Create "User Default Zoom Level" - is this accurate (allowing you to set 2 as default for resets)?

If so, I'd likely open point 2 as a separate feature request, as that seems to be a lot more likely to pick up steam than having VS reconfigure default key-bindings (when you can reconfigure that on your own machine).

**Comment by uipoet** [comment]
@joshuacookdev I think your assessment is accurate, though I disagree with your recommended strategy. Regardless of technical separation between these features, the experience is universal. Advanced users may have less trouble overall if only #2 were accomplished, but #1 is needed to address the new user experience.
