### ISSUE TITLE
On VScode launch, BSOD error with KERNEL HEAP MODE CORRUPTION

### ISSUE THREAD

**Issue by Henry-Asante** [microsoft/vscode#105145]
- VSCode Version: 1.47.3 91899dcef7b8110878ea59626991a18c8a6a1b3e x64
- OS Version: Microsoft Windows [Version 10.0.18363.959]

Steps to Reproduce:

1. Immediately as I launch, I get the BSOD error and shutdown is required
2.
![image](https://user-images.githubusercontent.com/30865594/90884565-85a96d80-e39f-11ea-9c14-9bd2628ba4c1.png)

Yes, it does the same when the extensions are disabled.

My search, says it might be a memory leak. 
I used to think it was my video card driver problem but same issues, neither is it RAM.

**Comment by Henry-Asante** [comment]
@deepak1556 @doudou @threeve @AArnott  

I got the issue today. after using the software for some time, this is really disturbing my workflow and don't know any progressive way to fix it, please help me out!

**Comment by deepak1556** [comment]
Can you check if the issue continues to happen with insiders https://code.visualstudio.com/insiders

is it possible to update your windows version to 2004 ?

**Comment by Henry-Asante** [comment]
I actually did that just 2 hours ago. The same thing happened, I used it for like 30mins

My PC, for some reason, reverts back to 18... when I do major updates. Am sure my hardware doesn't support it or because of my old copies of windows etc

**Comment by deepak1556** [comment]
Thanks for testing, I am not familiar with debugging BSOD error, would be good to reach out in windows community forum and they can help track down the issue.

**Comment by Henry-Asante** [comment]
The advice fetched me no results,

Most of the help were based on a software using memory that wasn't available.

Also VScode is the only software doing this, 
I have switched to Webstorm

**Comment by deepak1556** [comment]
Did you file an issue on the Feedback hub app ? If not, can you please do that. This requires inspecting the memory dump file generated at `C:/Windows/*.dmp` which cannot be shared here. Thanks!
