### ISSUE TITLE
无限需要更新

### ISSUE THREAD

**Issue by yangdaozhao** [microsoft/vscode#105117]
Issue Type: <b>Bug</b>

更新后 重新启动还要更新

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.94GB (4.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
px2rem|art|0.0.3
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.1.3
auto-rename-tag|for|0.1.4
gitee|g8u|0.0.4
vue-snippets|hol|0.1.12
easy-less|mrc|1.6.3
vscode-language-pack-zh-hans|MS-|1.48.3
LiveServer|rit|5.6.1
tabnine-vscode|Tab|2.9.2
vscode-icons|vsc|10.2.0
super-translate|xue|1.0.11
vue|znc|0.0.9

</details>

**Comment by joseph1125** [comment]
Question Body: After updating VSCode and restart, VSCode still ask for user to install updates
