### ISSUE TITLE
CSS intellisense is suggesting uncommonly used properties. More frequently used properties are farther down the list.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [microsoft/vscode#105112]
- VSCode Version: 1.48.1 (user setup)
- Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open a `.scss`, `.css`, etc. file, or simply open a new tab and do `Change Language Mode > CSS` via the command palette.
2. Create any selector and start typing `background-`.
3. Observe that `background-color` and `background` are way at the bottom of the list, while properties like `background-blend-mode` are high up in the auto-complete list.

Does this issue occur when all extensions are disabled?: Yes

**Comment by cdswyda** [comment]
I have same problem

**Comment by cheeroque** [comment]
Same here. CSS IntelliSense pretty much unusable in 1.48+

**Comment by aeschli** [comment]
duplicate of #105039
