### ISSUE TITLE
Make suggested keyboard shortcuts clickable

### ISSUE THREAD

**Issue by joaogui** [microsoft/vscode#105192]
<img width="1392" alt="Screen Shot 2020-08-21 at 18 05 17" src="https://user-images.githubusercontent.com/10387335/90935545-d50c8f80-e3d9-11ea-8814-f0abd228e98b.png">

**Comment by chrmarti** [comment]
Last time we discussed this we agreed that it would either be hard to discover and maybe unexpected if the mouse cursor does not change on hover or the changing mouse cursor would be distracting during regular work.

**Comment by joaogui** [comment]
@chrmarti About your points:

* For me, it was unexpected when I clicked and nothing happened.
* I do not think the mouse cursor should change on hover (see https://github.com/microsoft/vscode/issues/55346).
* To solve the discoverability problem they could be styled as buttons.

Overthinking here, maybe the user could be able to configure his set of "quick actions".
