### ISSUE TITLE
Integrated terminal File linking optimisations for different file/line formatting

### ISSUE THREAD

**Issue by bojomojo** [microsoft/vscode#105147]
Within the integrated terminal, FileName:LineNumber works fine (detected and opens the file and line correctly.

however, my task outputs are like: FileName(lineNumber:ColumnNumber) here only the file name is detected.
I was able to create a problemMatcher to detect this syntax, but it only reflects in the Problems tab, and not in the terminal links.

I would like to have an option to have the terminal understand this syntax and open the file/line number

**Comment by Tyriar** [comment]
What tool are you using that outputs that?
