### ISSUE TITLE
Word selection doesn't work the same in both directions

### ISSUE THREAD

**Issue by GuskiS** [microsoft/vscode#105152]
It seems that only `right` direction from https://github.com/microsoft/vscode/issues/48046 seems to be working. However, it doesn't look like that it works for `left`. @alexdima

Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:40:55.768Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic

For right I have:
```
{
  "key": "ctrl+right",
  "command": "cursorWordEndRight",
  "when": "textInputFocus"
}
```

I tried these left binds:
```
{
  "key": "ctrl+left",
  "command": "cursorWordStartLeft",
  "when": "textInputFocus"
}
```
```
{
  "key": "ctrl+left",
  "command": "cursorWordEndLeft",
  "when": "textInputFocus"
}
```
but they both perform the same.

Steps to Reproduce:
Use `this.sample.object.structure`
1. Move all the way to right with `ctrl+right`
2. Move all the way to left with `ctrl+left`

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
I agree that the default keybindings are not balanced. I have remapped that `ctrl+left` maps to `cursorWordLeft` which is different than `cursorWordStartLeft`/`cursorWordEndLeft`.

I have pushed a change to map `ctrl+left` and `ctrl+shift+left` to the "faster" implementation, `cursorWordLeft`.

You can workaround using:
```
{ "key": "ctrl+left", "command": "cursorWordLeft", "when": "textInputFocus" },
{ "key": "ctrl+shift+left", "command": "cursorWordLeftSelect", "when": "textInputFocus" },
```
