### ISSUE TITLE
Pylance extension fails to install with EPERM: operation not permitted

### ISSUE THREAD

**Issue by mas-dse-juremigi** [microsoft/vscode#105181]
Version: 1.48.1 (user setup)
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:12:13.244Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Language Server version: 2020.8.2
OS and version: Windows 10 x64 1909 Build 18363.1016
Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.8.5
Steps to Reproduce:

1.  Open VSCode
2.  Command Palette: "install from vsix"

Does this issue occur when all extensions are disabled?: No

Logs:
`[2020-08-21 11:30:28.340] [sharedprocess] [error] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat 'c:\Users\foo\AppData\Roaming\Code - Insiders\User\snippets'
[2020-08-21 11:30:38.437] [sharedprocess] [info] Installing the extension: ms-python.vscode-pylance
[2020-08-21 11:30:50.054] [sharedprocess] [error] Failed to install the extension: ms-python.vscode-pylance EPERM: operation not permitted, open 'c:\Users\foo\.vscode-insiders\extensions\.ms-python.vscode-pylance-2020.8.2\server\typeshed-fallback\third_party\2and3\nmap\__init__.pyi'`

**Comment by sandy081** [comment]
I see you are trying to install from VSIX and it can happen that the extension is running already and installing it is replacing it and this might be blocked. Can you please try

- uninstall the existing extension
- restart vs code
- install the extension from VSIX?
