### ISSUE TITLE
Bug resizing when editor splitted in 4

### ISSUE THREAD

**Issue by pibenett** [microsoft/vscode#105134]
Hello,

Unfortunately when my editor in splitted in 4 wiews and when I try to resize the 2 lower parts together with the crossed arrows to make them smaller than the 2 upper parts, only one (random?) part is resized like if it was done with the single arrow.
It would be very great to fix that.

Thank you very much
Have a good day

![resizing-bug-vscode](https://user-images.githubusercontent.com/28758779/90867143-33634f00-e395-11ea-9063-f0265334efd3.gif)

**Comment by joaomoreno** [comment]
How did you create that 2x2 grid?

Does it reproduce if you choose `View > Editor Layout > Grid (2x2)`?

**Comment by pibenett** [comment]
Indeed when I use `View > Editor Layout > Grid (2x2) `, the resizing is working well!
But when I manually split the editor in 4 by drag and dropping windows it is not.
Anyway now I know this workaround this it's not a big deal anymore.

Thank you :)

**Comment by joaomoreno** [comment]
Yeah the _grid_ feature only works if you go to it via the 2x2 command, not by painstakingly aligning the sashes. 👍
