### ISSUE TITLE
I cant sign in vs code

### ISSUE THREAD

**Issue by fayaz-md5K** [microsoft/vscode#105274]
Issue Type: <b>Bug</b>

i cant sign in vs code.command failed is occuring..

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU         550  @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|1.87GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vsliveshare|ms-|1.0.2666
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0

</details>

**Comment by RMacfarlane** [comment]
@fayaz-md5K Can you please share the steps to reproduce this? Are you trying to sign into settings sync or an extension?
