### ISSUE TITLE
vscode will shutdown and re-activate extensions when we move/remove the first workspace folder

### ISSUE THREAD

**Issue by PhilipAbed** [microsoft/vscode#105285]
- VSCode Version: 1.48.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. add 3 folders to workspace
2. in the 3rd workspace folder, add a file for example package.json that is not valid(so that vscode will give u an error on json format)
3. move the top folder(first one) to the bottom, or remove folder from workspace
4. Note that "Problems" section is REMOVED and then re-calculated.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

i've tried this on my extension, 
the result was that all the problems on ALL folders were removed...
i was able to put debug in 
activate(context:vscode.ExtensionContext)
deactivate()
onDidChangeWorkspaceFolders()

i know it goes into 
onDidchangeWorkspaceFolders and deActivate for 1second.. then my DEBUG Is dead,
then i get this error: 
`a shutdown.[2020-08-24 10:14:17.422] [renderer5] [error] timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///C:/Users/PhilipAbed/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3208:226)
    at file:///C:/Users/PhilipAbed/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3207:532
    at async t.RawDebugSession.shutdown (file:///C:/Users/PhilipAbed/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3205:536)`

then debugger goes directly back to "Activate(context)" function and continues to work like nothing happened.

my problem is: All the problems get deleted on all folders, while im deleting only 1 folder, i want to catch the onDidChangeWorkspaceFolders and delete only problems from the currently removed workspace folder.. not ALL of them.

**Comment by gjsjohnmurray** [comment]
This is documented behaviour:

![image](https://user-images.githubusercontent.com/6726799/91041582-387c0480-e608-11ea-8c3a-85fa5b4be923.png)

**Comment by PhilipAbed** [comment]
it is documented now i see that, but still doesnt resolve my problem.. 
now i must SAVE ALL my stuff in a global state and handle them in cache so if this happened i can refresh the info...
seems to me like a lot of extra work..
