### ISSUE TITLE
Auto import with multi cursor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#105203]
- Have two cursors while typing a TS type with intellisense
- Trigger the intellisense with an auto import that renames the type
- Only the main cursor gets the corrected name

Example:
![Aug-21-2020 18-40-36](https://user-images.githubusercontent.com/323878/90946126-cc6a8800-e3de-11ea-905d-76aa22f6d6e2.gif)

Have the code

```ts
let x: 
let y:
```

in extHostNotebook. Type to pick the ThemeColor from extHostTypes, so that it renames the type to `extHostTypes.ThemeColor`. The first one changes, and the second one doesn't.

**Comment by mjbvz** [comment]
This is the same root issue as #90695

While it is a bug, fixing it is not easy and would require changes on both the TS side and in VS Code. Closing as out of scope
