### ISSUE TITLE
[insiders] "Select and start" debugging command appears twice and with strange description text

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#105278]
When testing #103471 in insiders, I see this command duplicated, and the description seems to include the command name:

<img width="749" alt="Screenshot 2020-08-24 at 10 27 09" src="https://user-images.githubusercontent.com/1078012/91027832-7c650e80-e5f4-11ea-9652-d2969a37c257.png">

(@isidorn it doesn't seem like it's related to that fix, but FYI just in case!)

**Comment by isidorn** [comment]
I can not reproduce this with latest VS Code insiders (f57a418b019926b38d2e6949265c33002a8f6f6b)
Are you doing something special?
I am just F1 > type "select"

![Screenshot 2020-08-24 at 11 50 53](https://user-images.githubusercontent.com/1926584/91030885-18e0de00-e600-11ea-9c0e-05ad12e7d43d.png)

**Comment by DanTup** [comment]
Noting special, but I noticed it only happens in some cases. I'm using:

```
Version: 1.49.0-insider
Commit: f57a418b019926b38d2e6949265c33002a8f6f6b
Date: 2020-08-24T08:17:33.759Z
Electron: 9.2.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0
```

If I open `~/Dev/Google/flutter_gallery` (a Flutter project) on its own, I do not see it:

<img width="647" alt="Screenshot 2020-08-24 at 11 06 58" src="https://user-images.githubusercontent.com/1078012/91032512-f21fa900-e5f9-11ea-9d0d-b478b4710131.png">

If I open `/Users/danny/Dev/Dart-Code/src/test/test_projects/flutter_hello_world` (also a Flutter project) on its own, I do not see it:

<img width="645" alt="Screenshot 2020-08-24 at 11 07 44" src="https://user-images.githubusercontent.com/1078012/91032575-0e234a80-e5fa-11ea-9aa2-3a8553296a57.png">

However if I open one of them and then **File -> Add Folder to Workspace** to add the other, I do:

<img width="676" alt="Screenshot 2020-08-24 at 11 08 26" src="https://user-images.githubusercontent.com/1078012/91032640-25face80-e5fa-11ea-9f61-74e0a3e1e24e.png">

The only difference I can think of here, is that there would be multiple sets of configs returned (as shown in https://github.com/microsoft/vscode/issues/103471#issuecomment-679015703).

**Comment by isidorn** [comment]
Yes. I can reproduce, but only for multi root workspaces, let me look into a fix. Thanks for reporting this.

**Comment by DanTup** [comment]
Fix LGTM, thanks!

<img width="623" alt="Screenshot 2020-08-25 at 09 55 51" src="https://user-images.githubusercontent.com/1078012/91154224-2dcd7800-e6b9-11ea-8170-59109ea2d327.png">

**Comment by isidorn** [comment]
Thanks for letting us know, adding verified label.
