### ISSUE TITLE
Vertical Split Panel Views

### ISSUE THREAD

**Issue by AssafLS** [microsoft/vscode#105245]
Currently (Aug 2020), we can decide if we want the panel view (containing the tabs for terminal, debug console, output, etc.)
on the left/right side but we cannot split this view into two or more columns like we can with the editor view.

This is a standard capability in many IDEs and more than a few developers could benefit from this kind of layout 
when working on languages such as Julia and Matlab.

**Comment by sbatten** [comment]
@AssafLS are you aware of the features demonstrated here? https://code.visualstudio.com/updates/v1_46#_flexible-layout

**Comment by AssafLS** [comment]
@sbatten thanks for the quick response, first of all I updated my comment, this only happens when docking a view to the left/right and not when docking to the to/bottom. 
Basically i was trying to do the demonstrated drag operation in the link but the drag/drop position options do not feature vertical splitting when the view is docked vertically. 
This is also true to the split view button in the code editor and terminal views.

**Comment by sbatten** [comment]
@AssafLS thank you for your response. currently to maintain the simplicity and lightweight nature of VS Code we opt for vertical and horizontal layout of views based on dock position. I understand that you would like to have more flexibility, and this will be under consideration as we improve the flexibility of the layout going forward.
