### ISSUE TITLE
preview for rst file is not updated when content changed...

### ISSUE THREAD

**Issue by chenjie4255** [Microsoft/vscode#10527]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.2.0

Steps to Reproduce:

1.open a rst file and edit it.
2.use command + shift +v to open a preview for this file.
3.close preview
4.make some modify on this rst file.
5.open preview again but it have not been updated...

**Comment by jrieken** [comment]
I believe we listen on `md` files only

**Comment by chenjie4255** [comment]
@jrieken but vscode support preview for rst file, does it?

**Comment by kieferrm** [comment]
@chenjie4255 we don't support `rst` files out of the box. There are extensions that provide that support: https://marketplace.visualstudio.com/search?term=rst&target=VSCode&category=All%20categories&sortBy=Relevance
