### ISSUE TITLE
Scala plugin color error.

### ISSUE THREAD

**Issue by YangliAtGitHub** [Microsoft/vscode#10529]
![bad color](https://cloud.githubusercontent.com/assets/15964600/17654104/e34398e2-62d1-11e6-9593-56955135646f.png)
![correct color](https://cloud.githubusercontent.com/assets/15964600/17654105/e34792a8-62d1-11e6-8d94-7d13d9401ffd.png)

- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.Write a test.scala file.
package progscala2.introscala.shapes;

object Message {
    object Exit
    object Finished
    case class Response(message: String)
}

import akka.actor.Actor

class ShapesDrawingActor extends Actor {
    import Messages._                    //here    
    def receive = {
        case s: Shape =>
            s.draw( str => println( s"ShapesDrawingActor:$str" ))
            sender ! Response( s"ShapesDrawingActor: $s drawn")
        case Exit =>
            println($"ShapesDrawingActor:exiting... ")
            sender ! Finished
        case unexpected =>  //default. Equivalent to "unexpected: Any"
            val response = Response( s"ERROR: Unknown message: $unexpected")
            println(s"ShapesDrawingActor:$response")
            sender !response
    }
}

2.then color error

**Comment by jrieken** [comment]
This is caused by an extension because we don't ship a scala mode. Please the issue against that extension
