### ISSUE TITLE
Strange extension recommendation for .bak files

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode#105296]
Opening a file with the `.bak` extension recommends the extension [ucavalcante.altitude-script-language](https://marketplace.visualstudio.com/items?itemName=ucavalcante.altitude-script-language), which doesn't seem right.

![image](https://user-images.githubusercontent.com/1186948/91062659-d5777700-e5e1-11ea-9391-7dd677462710.png)

![image](https://user-images.githubusercontent.com/1186948/91062703-e32cfc80-e5e1-11ea-8e14-d252f4ab63b1.png)

**Comment by RMacfarlane** [comment]
For file extension based recommendations, VSCode queries the marketplace for extensions that have listed these file extensions as something they handle in the their package.json: https://github.com/ucavalcante/altitude-script-language/blob/67616081f24ab9e38493009fe0fe8c747f3c9c5e/package.json#L23

I think this should be reopened on the extension
