### ISSUE TITLE
Allow window to restore over multiple displays

### ISSUE THREAD

**Issue by mrmsbarnes** [microsoft/vscode#105258]
Issue Type: <b>Bug</b>

Displaying Spit Editor (2 columns) with SEARCH displayed in right side bar.  Window is stretched so Editor fills most of the main display with SEARCH shown on a second display to the right of the main display. 
File > Exit
Restart Visual Studio Code.  The VS Code window does not have the same size as when it was exited.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.1
python|ms-|2020.8.103604

</details>

**Comment by mrmsbarnes** [comment]
Sorry, that's Split Editor.

**Comment by sbatten** [comment]
@deepak1556 I am not on multimon right now, but as a first step, does this sound familiar as an electron issue?

**Comment by deepak1556** [comment]
@mrmsbarnes is this still an issue with latest insiders https://code.visualstudio.com/insiders/ , if so can you share some screenshots. Thanks!

**Comment by mrmsbarnes** [comment]
This is still a bug to me with latest insider version.  Screenshots (on adjacent monitors) are with Electron 9.2.1 but it still happens with latest version with About shown in CodeVersion.jpg.  I have adjusted to different feature usage, but it would be nice if Code remembered from Exit to restart the layout I wanted.

It's going to take me a while to figure out how to attach files.  drag and drop, cut and pasted don't seem to work.

**Comment by mrmsbarnes** [comment]
![SetAsWanted](https://user-images.githubusercontent.com/8269732/96704165-9b5bf480-1348-11eb-95c1-36c7ce2def53.jpg)
![SaveExitRestart](https://user-images.githubusercontent.com/8269732/96704205-a9aa1080-1348-11eb-97fc-9579551fe31c.jpg)
![CodeVersion](https://user-images.githubusercontent.com/8269732/96704220-af075b00-1348-11eb-9138-229676bd6511.jpg)

Hope screenshots came through.

**Comment by mrmsbarnes** [comment]
Since no one else works with dual monitors, I am closing this isssu.

**Comment by deepak1556** [comment]
@mrmsbarnes I would suggest to try the latest stable based on Electron 9.3.3 that contains fix for your use case https://github.com/electron/electron/pull/25980.

**Comment by mrmsbarnes** [comment]
Sorry, Electron 9.3.3 doesn't solve the problem for me.  I WANT the Explorer window to bleed over to my 2nd monitor.  AND I wanted Visual Studio Code to remember how I set the the app's window when I exit.  When I start again, I wanted the window to be exactly where I set it (all boundaries upper left corner, width and height I set).  I can see if I made display changes this might not be achievable.  But if my desktop is still the same, I wanted Visual Studio Code to resume where I left it.

**Comment by deepak1556** [comment]
@sbatten the authors request is more about in-app view layout persistence, moving it to you for further triage.

**Comment by sbatten** [comment]
From the screenshots it appears the in-app layout is correctly remembered except for the window size. That means upon restart we are not getting the same window dimensions. Looking into the code, I see this logic may be clipping the dimensions in a multi-mon case. @bpasero 

https://github.com/microsoft/vscode/blob/38f55ece05a937a0821c4eeb15e9194a46b2d36e/src%2Fvs%2Fcode%2Felectron-main%2Fwindow.ts#L1016-L1056

**Comment by deepak1556** [comment]
@bpasero what is the history behind the window clipping logic steven posted above ? Is it still required with latest electron versions where we had some fixes for framless on windows

**Comment by bpasero** [comment]
The change was mainly done to prevent one case where the window might overlap to the top and left so that you cannot interact with the controls anymore. I felt it dangerous to allow the window from exceeding the display bounds, but I can see how it might be useful in a multi-monitor setup.

Since this is intentional, marking as feature request.
