### ISSUE TITLE
Way to undo the revealRange action 

### ISSUE THREAD

**Issue by laslzo** [microsoft/vscode#105221]
Currently, when calling revealRange(), and the code block is highlighted, to remove that highlight the user must click somewhere else within the window or document. Adding something like undoRevealRange() that could be called when a button is clicked for example would mean that the highlighted range could be cleared, or only part of it if necessary, for example, only wanting to further highlight one part of the range.

**Comment by alexdima** [comment]
@laslzo I'm not sure I understand. Are you calling `TextEditor.revealRange()` ? AFAIK that method results in the editor scrolling, but no highlight is added to the range that is being revealed.
