### ISSUE TITLE
ColorProvider wrong color

### ISSUE THREAD

**Issue by Marcinbar** [microsoft/vscode#105287]
- VSCode Version: 1.48.1
- OS Version:Windows 10

Steps to Reproduce:
```
    vscode.languages.registerColorProvider('plaintext', {
        provideDocumentColors(document, token) {
            return [new vscode.ColorInformation(new vscode.Range(0,0,0,10), new vscode.Color(255, 128, 0, 255))];
        }
    });
```

It should be orange and it's yellow. ColorProvider show only basic color like: white, red, green blue, purple, yellow etc.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
The range for each color component is [0, 1].
