### ISSUE TITLE
let is set to a variable under semantic token type

### ISSUE THREAD

**Issue by hiredtocode** [microsoft/vscode#105260]
- VSCode Version:Version: 1.48.1 
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Set semanticTokenColorCustomizations > enable: true 
2. Add color for variable
3. Add different color for storage.type.js in textmate colors
4. type var, let, const in different lines. 
For some reason the keyword "let" is registered under the "variable" under semantic token type which gives different colors.
"let" & "console" keywords should be not declared as a variable under semantic token type right? 
There might be more but not sure how to check by type.. Let me know how and I'll double check them.

![let](https://user-images.githubusercontent.com/68050282/90989750-2766cf80-e5d7-11ea-8c34-8c1dfe80fdef.JPG)
![let 2](https://user-images.githubusercontent.com/68050282/90989754-27ff6600-e5d7-11ea-8b6d-0d67950c449c.JPG)
![let 3](https://user-images.githubusercontent.com/68050282/90989755-2897fc80-e5d7-11ea-9791-b3b950252ecf.JPG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
In your sample you in fact define a variable called `let`. Semantic highlighting gets it right, but the TextMate grammar used for syntax highlighting is tricked here.

Semantic highlighting is based on a proper compiler AST, while TextMate grammars can only parse line by line, and would need to define a extra state to get this right.

So, yes, you demonstrated why it's beneficial to have semantic highlighting.

You can run the following sample in NodeJS to see that it's valid to use `let` as variable name:
```
var let = 'test';
console.log(let);
```

**Comment by hiredtocode** [comment]
Ahhh Thank you!!
