### ISSUE TITLE
Multi Sync

### ISSUE THREAD

**Issue by ahmedelfateh** [microsoft/vscode#105218]
Give the ability to create multiple setting sync on the same account, it will be helpful for the diversity of development extension from env to env

**Comment by sandy081** [comment]
Do you mean multiple sync profiles?

**Comment by ahmedelfateh** [comment]
@sandy081 
yes, more profile to choose from when syncing the setting. This meant to be easy when pulling this setting back in a new editor.
My idea is to use it to separate my development env, because having, for example, all python packages and setting with java and frontend make the load on VSCode #105228 multiple profiles will help with that.

**Comment by sandy081** [comment]
/duplicate

#92393
