### ISSUE TITLE
"Select TypeScript Version" inserts full path to tsserver.js which breaks the language service

### ISSUE THREAD

**Issue by rbuckton** [microsoft/vscode#105202]
Using the version selector for TypeScript overwrites the `"typescript.tsdk"` setting, replacing it with the full path to `tsserver.js`. Restarting VS Code then produces a warning about an invalid tsserver install.

Steps to Reproduce:

1. Open a folder with a `.vscode/settings.json` having a `"typescript.tsdk"` pointing to a folder containing a valid `tsserver.js` installation.
2. Use the `Select TypeScript Version` command to chose the version specified in `settings.json`:
![overrides tsdk](https://user-images.githubusercontent.com/3902892/90945775-f0789a00-e3db-11ea-8068-a17ac4e5ea9d.gif)
3. Notice that the path is replaced with a fully qualified path to the `tsserver.js` file.
4. Reload VS Code (either restart, or use the `Developer: Reload Window` command) and see the following error:
![image](https://user-images.githubusercontent.com/3902892/90945770-e8205f00-e3db-11ea-969e-1f8272b5aac5.png)

VS Code shouldn't be overwriting my setting for `"typescript.tsdk"`, or at the very least should point it to the parent folder containing `tsserver.js` and not the file itself.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code - Insiders 1.49.0-insider (8e872f41d4ba7807e58938bbf861ca6a22d534aa, 2020-08-20T05:37:43.249Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (40.93GB free)|
|Process Argv|--crash-reporter-id 99273024-ceec-4453-aefb-860cdbf17aa9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tsserver-debug|and|1.3.0
gitlens|eam|10.2.2
vscode-pull-request-github|Git|0.19.0
vscode-gist|ken|3.0.3
vscode-docker|ms-|1.5.0
vscode-typescript-next|ms-|4.1.20200821
vsliveshare|ms-|1.0.2666
deoptexplorer-vscode|rbu|0.0.4
grammarkdown-language|rbu|0.4.3
tsserver-live-reload|rbu|1.0.1
vscodeintellicode|Vis|1.2.10

</details>

**Comment by atsikov** [comment]
Got similar error after updating TS to 4.0.2 (don't know if it is related).
After selecting "Use workspace version", VS Code shows an error
```
The path <absolute path to project>/node_modules/typescript/lib/tsserver.js/tsserver.js/tsserver.js/tsserver.js/tsserver.js doesn't point to a valid tsserver install. Falling back to bundled TypeScript version.
```

In my case typescript folder is a symlink, as it's a rush and pnpm managed monorepo.

VS Code version: 1.48.2
OS version: macOS 10.15.6

**Comment by jrieken** [comment]
<img width="1394" alt="Screenshot 2020-09-03 at 07 28 13" src="https://user-images.githubusercontent.com/1794099/92074724-0ceedc00-edb7-11ea-9675-6883fd3e8866.png">

**Comment by rbuckton** [comment]
I'm not clear as to why vscode is even updating this setting if the path is already set and resolves to the same location. On Windows this rewrites a path that uses `/` chars to use `\` chars, which could cause problems for a vscode instance open to the same path in WSL.

**Comment by mjbvz** [comment]
VS Code automatically detects `typescript` versions installed under `node_modules` and shows these in the version picker. If you select the version from `node_modules`, we persist that selection into your settings. 

If the selected version already comes from a setting—such as this case—we should likely not write anything to your settings

**Comment by jeanp413** [comment]
I took a second look at this and will make another PR
