### ISSUE TITLE
Tree item command execute twice on double click

### ISSUE THREAD

**Issue by mmmyddd** [microsoft/vscode#105256]
Issue Type: <b>Bug</b>

With setting ID: **workbench.list.openMode** set to doubleClick

 Tree Item (un-expandable item)  command execute twice when double click on it.

 BTW, Tree Item command not executed on single click if WorkBench > List: Open Mode set to doubleClick

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.54GB (0.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|
</details>

**Comment by mmmyddd** [comment]
https://github.com/microsoft/vscode-extension-samples/tree/master/tree-view-sample

With the sample above, I can reproduce the issue with vscode 1.48.1

**Comment by isidorn** [comment]
Might be introduced with the tree open refactor that @joaomoreno did. First forwarding to him

**Comment by mmmyddd** [comment]
In addition, I believe the  Tree Item (not expandable item)  behaviour is not quite sync with workbench.list.openMode settings.

Sometime I have set doubleClick, but the in-expandable item behave just like singleClick is set.

**Comment by isidorn** [comment]
fyi @alexr00 for CustomTrees

**Comment by alexr00** [comment]
When I change from `singleClick` to `doubleClick` **without reloading**, [`onDidOpen`](https://github.com/Microsoft/vscode/blob/144f90443a8a82af28b6155236137d3e994c3f10/src/vs/platform/list/browser/listService.ts#L445-L445) is not fired for the single click, but is called twice for a double click.

If I reload after changing from `singleClick` to `doubleClick`, `onDidOpen` is fired for a single click and then fired a second time for the second click in a double click.

This inconsistency seems like a bug in the tree.

Aside from that, when `doubleClick` is set, the command for a custom tree item shouldn't be called twice. Instead, it should only be run on double click. I see two ways to accomplish this:
 - The tree only fires `onDidOpen` on the double click when `doubleClick` is set
 - The tree view reads `workbench.list.openMode` and makes its own decision about what to do. The browser event that is passed with `onDidOpen` has enough information for me to only pay attention to the double click when appropriate.

**Comment by alexr00** [comment]
Verified out of source. Works great!

**Comment by mmmyddd** [comment]
Verified, it's good now, thank you!
