### ISSUE TITLE
Language selector shows incorrect Icons for Javascript.

### ISSUE THREAD

**Issue by MetaMmodern** [microsoft/vscode#105244]
So, this issue is here for a long time in vscode, i've just noticed another issue with it. Basically, vsCode shows incorrect icons, see on the screensot:
![image](https://user-images.githubusercontent.com/42899786/90974581-4dd42e80-e535-11ea-8eaa-02f4313025f4.png)
You see that it shows react icon for babel js and simple js icon for react js.
I actually know that it may be better to use .jsx files for react project, but is there any way to fix this?
and also
**Is there a way to automaticaly recognize whether the file is for react or simple javascript(by detecting import/require export/module.exports statements or smth else)??** This is the main question for the issue.

- VSCode Version: 1.48.1(Latest)
- OS Version: Windows 10 2004

Steps to Reproduce:

1. Click on the language selector in right bottom corner.
2. Type in Javascript.

Does this issue occur when all extensions are disabled?: Yes, and it also shows more incorrect variant.
![image](https://user-images.githubusercontent.com/42899786/90974541-fdf56780-e534-11ea-8971-447588923644.png)

**Comment by aeschli** [comment]
I don't see this in 1.48.1
![image](https://user-images.githubusercontent.com/6461412/91174177-320c8c00-e6df-11ea-8783-8ca3cf153817.png)

Can you try without custom extensions? (close all windows and run code --disable-extensions`)

**Comment by MetaMmodern** [comment]
> I don't see this in 1.48.1
> ![image](https://user-images.githubusercontent.com/6461412/91174177-320c8c00-e6df-11ea-8783-8ca3cf153817.png)
> 
> Can you try without custom extensions? (close all windows and run code --disable-extensions`)

i've already mentioned in my answer that i tried without extensions and provided a screenshot. It shows react icon for both js and react js.

**Comment by aeschli** [comment]
I think you have the following setting configured. Is that correct?
```
	"files.associations": {
		"*.js": "javascriptreact"
	},
```

**Comment by MetaMmodern** [comment]
> I think you have the following setting configured. Is that correct?
> 
> ```
> 	"files.associations": {
> 		"*.js": "javascriptreact"
> 	},
> ```

Yep, you are right. Should i remove that setting entirely or change it? 
Also the main question was: can VSCode automatically detect whether js file is for react or vanilla js?

**Comment by aeschli** [comment]
It's a bug in the language selection dialog. For getting the langauge icon, we use the icon of the first file extension. In your case that file extension has be reassigned to a different language. I create a PR.

**Comment by MetaMmodern** [comment]
> It's a bug in the language selection dialog. For getting the langauge icon, we use the icon of the first file extension. In your case that file extension has be reassigned to a different language. I create a PR.

Great, good luck and notify me if some actions from my side will be needed)

**Comment by aeschli** [comment]
I pushed a fix. You can already try it out in our insiders build or in the next stable release.

**Comment by bpasero** [comment]
@aeschli I am not sure this is fixed, what are the steps? I configured my settings as outlined.

I see this:

![image](https://user-images.githubusercontent.com/900690/92131093-d4c2ba00-ee05-11ea-80ac-44262ad8c56a.png)

**Comment by MetaMmodern** [comment]
> @aeschli I am not sure this is fixed, what are the steps? I configured my settings as outlined.
> 
> I see this:
> 
> ![image](https://user-images.githubusercontent.com/900690/92131093-d4c2ba00-ee05-11ea-80ac-44262ad8c56a.png)

great, i'll check it in nearest stable update)

**Comment by MetaMmodern** [comment]
Ok, but the main reason I started this issue is if vscode can automatically detect reactjs files and set the propper icon. So @aeschli please, tell me if I need to start a new issue or if there is a solution for this "problem"

**Comment by aeschli** [comment]
@MetaMmodern Yes, a new issue is needed.
That said, it's a difficult request as language detection has to be very efficient as there can be hundreds of files visible in a view.
Analyzing the content and even parsing it or resolving imports would be very expensive.
 Fee free to file the issue anyways, but I don't think we can do it.
