### ISSUE TITLE
Option to stop changing the extension folder version when updating the extension

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode#105268]
Due to https://github.com/microsoft/vscode/issues/90649 that I closed for lack of support, I decided to create my language-specific workspaces folders and to symlink some extensions from `.vscode-insiders/extensions` in each workspace, usting `code-insiders --extensions-dir`.

But when you update the extensions (for example, `budparr.language-hugo-vscode-1.1.8` to `budparr.language-hugo-vscode-1.2.0`), it changes the extension folder version (for example, `1.1.8` to `1.2.0`, resulting in broken symlinks (for example, the folder was symlinked to `1.1.8`). I was forced to re-symlink all extensions every time I keep updating the extensions. 

In the `.vscode-insiders/extensions`, it should be like, instead of:

```
budparr.language-hugo-vscode-1.2.0
```

to

```
budparr.language-hugo-vscode
```

So, without version in the folder name, the symlinks would not be broken.

**Comment by sandy081** [comment]
Sorry I do not think we can use the unique name for different version of same extension because extension might be running while being updated and we cannot simply rename.
