### ISSUE TITLE
Code always launches a login shell in linux/zsh

### ISSUE THREAD

**Issue by Four-Griffins** [microsoft/vscode#105208]
- VSCode Version: 1.48.0
- OS Version: Arch Linux kernel 5.8.1

Steps to Reproduce:

When starting VS Code the `~/.zprofile` file is being sourced. In my case that file contains some system configuration things that shouldn't be run twice. I found #10500 and tried setting `terminal.integrated.shellArgs.linux` to `-l` and to nothing, but to no avail.
I'm pretty sure it's not the integrated terminal doing this, I can restart it without any effects, and if I add `echo "hello"` to `.zprofile` it doesn't show up.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
By default the terminal will _not_ launch as a login shell on Linux. Setting `terminal.integrated.shellArgs.linux` to `["-l"]` will cause it to run as a login shell. You can see the exact args the shell launches by taking a trace log https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
