### ISSUE TITLE
Better icon name on Linux / Deb.

### ISSUE THREAD

**Issue by pete-otaqui** [Microsoft/vscode#10523]
- VSCode Version:
1.5
- OS Version:
Ubuntu Gnome

Steps to Reproduce:

1. Install the *.deb
2. View the vscode.desktop file

The icon name in the vscode.desktop file is "code". This is too generic for theme creators.

If you used "vscode" instead, it would be much better.

See this ticket:

https://github.com/numixproject/circle-core/issues/3370

**Comment by Tyriar** [comment]
The icon name matches the application name, I would prefer to keep it consistent. As a bit of background some petitioned to change the name of the application for the same reasons but it was ultimately turned down. See https://github.com/Microsoft/vscode/issues/2722 for more context, closing this as there are no plans to fix.

**Comment by term1nal** [comment]
No alternative for Numix Square icon theme? Only seems to work with Circle icon theme.
