### ISSUE TITLE
New lite version of vsc

### ISSUE THREAD

**Issue by tec-wizard** [microsoft/vscode#105250]
Please introduce a lite version of vsc as the current version for consumes around 400 mb of ram. It would be of great help as I use it for most of my projects and want to keep it like this for all my future projects.

**Comment by diogoeichert** [comment]
Have you considered Atom as a lighter alternative to VS Code?

**Comment by tec-wizard** [comment]
yes, I did but switched to vsc when I came to know about vsc. Atom used around 280-320 mb's for me
