### ISSUE TITLE
embedded API: configuration default doesn't seem to be picked up

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#105291]
- In https://github.com/microsoft/vscode/blob/master/src/vs/code/browser/workbench/workbench.ts#L426
add a configuration default:
```
		configurationDefaults: {
			"workbench.colorTheme": "Abyss"
		}
```
.
- open vscode in the web and set a breakpoint in the `workbenchThemeService` where the theme setting is accessed:
https://github.com/microsoft/vscode/blob/f3ac25fdd0d57cd22e8e964164a071550b226b30/src/vs/workbench/services/themes/browser/workbenchThemeService.ts#L162

- The old default (`Default Light+`) is returned.

**Comment by sandy081** [comment]
Good catch.
