### ISSUE TITLE
filter problems by type ('errors', 'warnings') didn't work in python

### ISSUE THREAD

**Issue by Jackiexiao** [microsoft/vscode#105237]
- VSCode Version: 1.48.1
- OS Version: Window10

Steps to Reproduce:

I want to filter problem by typing "errors" instead of click at "filter" and choose only show errors 

![image](https://user-images.githubusercontent.com/18050469/90969944-5a568800-e531-11ea-863d-15c66b6564fa.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
You can only filter by type using the filters and use text to filter by text.
