### ISSUE TITLE
GUI crash when trying to open a folder

### ISSUE THREAD

**Issue by shay972** [Microsoft/vscode#10520]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. File, Open folder
2. Choose any folder
3. Getting msgbox "We are sorry for the inconvenience..."

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by shay972** [comment]
did not help

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\shayb>cd "c:\Program Files (x86)\Microsoft VS Code"

c:\Program Files (x86)\Microsoft VS Code>code --disable-extensions

c:\Program Files (x86)\Microsoft VS Code>
[7172:2376:0814/223047:VERBOSE1:crash_service_main.cc(68)] Session start.
cmdlin
e is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash
--appli
cation-name=VSCode --v=1]
[7172:2376:0814/223047:VERBOSE1:crash_service.cc(142)] window handle is
0006052A

[7172:2376:0814/223047:VERBOSE1:crash_service.cc(290)] pipe name is
\\.\pipe\VSC
ode Crash Service
dumps at C:\Users\shayb\AppData\Local\Temp\VSCode Crashes
[7172:2376:0814/223047:VERBOSE1:crash_service.cc(294)] checkpoint is
C:\Users\sh
ayb\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[7172:2376:0814/223047:VERBOSE1:crash_service_main.cc(84)] Ready to process
cras
h requests
[7172:1928:0814/223047:VERBOSE1:crash_service.cc(323)] client start. pid =
600
[7172:1928:0814/223047:VERBOSE1:crash_service.cc(323)] client start. pid =
5256
[4560:6944:0814/223048:VERBOSE1:crash_service_main.cc(68)] Session start.
cmdlin
e is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash
--appli
cation-name=VSCode --v=1]
[4560:6944:0814/223048:VERBOSE1:crash_service.cc(142)] window handle is
00020418

[4560:6944:0814/223048:VERBOSE1:crash_service.cc(290)] pipe name is
\\.\pipe\VSC
ode Crash Service
dumps at C:\Users\shayb\AppData\Local\Temp\VSCode Crashes
[4560:6944:0814/223048:VERBOSE1:crash_service.cc(294)] checkpoint is
C:\Users\sh
ayb\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[4560:6944:0814/223048:ERROR:crash_service.cc(301)] could not start dumper
[7172:2068:0814/223059:VERBOSE1:crash_service.cc(331)] client end. pid = 600
[VS Code]: render process crashed!
[7172:2068:0814/223103:VERBOSE1:crash_service.cc(331)] client end. pid =
5256
[7172:2068:0814/223104:VERBOSE1:crash_service.cc(352)] zero clients. exiting
[7172:2376:0814/223104:VERBOSE1:crash_service.cc(490)] session ending..
[7172:2376:0814/223104:VERBOSE1:crash_service.cc(495)] clients connected :2
clients terminated :2
dumps serviced :0
dumps reported :0
[7172:2376:0814/223104:VERBOSE1:crash_service_main.cc(89)] Session end.
return c
ode is 0

**Comment by bpasero** [comment]
@shay972 does "code -n" from the command line work at least?

**Comment by shay972** [comment]
code -n, opens the VS. GUI
but when I choose folder, it crash:
Is there a way to debug the GUI itself - why it is crashing?
I also tried previous version - also crashing


C:\Users\shayb>cd "c:\Program Files (x86)\Microsoft VS Code"

c:\Program Files (x86)\Microsoft VS Code>code -n

c:\Program Files (x86)\Microsoft VS Code>
[7632:3884:0815/101259:VERBOSE1:crash_service_main.cc(68)] Session start.
cmdlin
e is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash
--appli
cation-name=VSCode --v=1]
[7632:3884:0815/101259:VERBOSE1:crash_service.cc(142)] window handle is
001303A0

[7632:3884:0815/101259:VERBOSE1:crash_service.cc(290)] pipe name is
\\.\pipe\VSC
ode Crash Service
dumps at C:\Users\shayb\AppData\Local\Temp\VSCode Crashes
[7632:3884:0815/101259:VERBOSE1:crash_service.cc(294)] checkpoint is
C:\Users\sh
ayb\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[7632:3884:0815/101259:VERBOSE1:crash_service_main.cc(84)] Ready to process
cras
h requests
[7632:4668:0815/101259:VERBOSE1:crash_service.cc(323)] client start. pid =
4140
[7632:4668:0815/101259:VERBOSE1:crash_service.cc(323)] client start. pid =
8016
[3888:3752:0815/101300:VERBOSE1:crash_service_main.cc(68)] Session start.
cmdlin
e is [--reporter-url=https://ticinocrashreporter.azurewebsites.net/crash
--appli
cation-name=VSCode --v=1]
[3888:3752:0815/101300:VERBOSE1:crash_service.cc(142)] window handle is
000406FC

[3888:3752:0815/101300:VERBOSE1:crash_service.cc(290)] pipe name is
\\.\pipe\VSC
ode Crash Service
dumps at C:\Users\shayb\AppData\Local\Temp\VSCode Crashes
[3888:3752:0815/101300:VERBOSE1:crash_service.cc(294)] checkpoint is
C:\Users\sh
ayb\AppData\Local\Temp\VSCode Crashes\crash_checkpoint.txt
server is https://ticinocrashreporter.azurewebsites.net/crash
maximum 128 reports/day
reporter is electron-crash-service
[3888:3752:0815/101300:ERROR:crash_service.cc(301)] could not start dumper
[7632:1816:0815/101308:VERBOSE1:crash_service.cc(331)] client end. pid =
4140
[VS Code]: render process crashed!
[7632:1816:0815/101311:VERBOSE1:crash_service.cc(331)] client end. pid =
8016
[7632:1816:0815/101312:VERBOSE1:crash_service.cc(352)] zero clients. exiting
[7632:3884:0815/101312:VERBOSE1:crash_service.cc(490)] session ending..
[7632:3884:0815/101312:VERBOSE1:crash_service.cc(495)] clients connected :2
clients terminated :2
dumps serviced :0
dumps reported :0
[7632:3884:0815/101312:VERBOSE1:crash_service_main.cc(89)] Session end.
return c
ode is 0

**Comment by bpasero** [comment]
@shay972 can you monitor CPU/Memory usage of the Code processes to see if this crash is an out of memory situation or high CPU usage?

**Comment by shay972** [comment]
no
cpu not moving, memory peek of 15%+-
see this maybe it can help:


C:\Users\shayb>cd "c:\Program Files (x86)\Microsoft VS Code"
c:\Program Files (x86)\Microsoft VS Code>Code.exe c:\SHAY\Angular2.0\seed
c:\Program Files (x86)\Microsoft VS Code>
[VS Code]: render process crashed!

**Comment by bpasero** [comment]
@shay972 does it crash if you pick a really empty folder to open?

**Comment by shay972** [comment]
yes
even if the folder is empty it crashes
(also if not empty)

**Comment by bpasero** [comment]
@shay972 very weird. another try: run "`code --verbose <folder>`" from the command line to get some more output until the crash happens. Also make sure no other instance is running (maybe do a PC restart to ensure).

**Comment by shay972** [comment]
I already tried pc reboot - did not help

c:\Program Files (x86)\Microsoft VS Code>code --verbose c:\1\

c:\Program Files (x86)\Microsoft VS Code>
(10:55:51 AM) ### VSCode main.js ###
(10:55:51 AM) c:\Program Files (x86)\Microsoft VS Code\resources\app {
pathArgum
ents: [ 'c:\\1' ],
  programStart: 0,
  enablePerformance: false,
  verboseLogging: true,
  debugExtensionHostPort: undefined,
  debugBrkExtensionHost: false,
  logExtensionHostCommunication: false,
  debugBrkFileWatcherPort: undefined,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  diffMode: false,
  extensionsHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  disableExtensions: false,
  locale: undefined,
  waitForWindowClose: false }
[VS Code]: render process crashed!
(10:55:57 AM) Lifecycle#window-all-closed
(10:55:57 AM) Lifecycle#before-quit
(10:55:57 AM) App#will-quit: disposing resources

c:\Program Files (x86)\Microsoft VS Code>

**Comment by bpasero** [comment]
@shay972 ok I am running out of ideas, maybe a complete uninstall helps? Can you uninstall Code and also delete the directory where settings are stored: C:\Users\bpasero\AppData\Roaming\Code

This means however to loose all your settings and keybindings, so maybe keep a backup of storage.json and keybindings.json if you want.

**Comment by shay972** [comment]
Tried what you say above, still crashing

**Comment by bpasero** [comment]
Ok broadening assignees. @alexandrudima @joaomoreno any more ideas? this user gets a crash as soon as he opens a folder. From the output I do not see how that can happen and a reinstall also did not help.

**Comment by joaomoreno** [comment]
@shay972 Can you try the same with our [latest insiders release](https://code.visualstudio.com/insiders)?

**Comment by shay972** [comment]
did it yesterday, same issue

**Comment by joaomoreno** [comment]
To confirm: you are on Windows 7, correct?

**Comment by alexandrudima** [comment]
@shay972 Did VSCode ever run on your machine ? i.e. is this the result of an update?

**Comment by shay972** [comment]
yes, windows 7 SP1 enterprise , 64 bit, on Lenovo X230 laptop

**Comment by joaomoreno** [comment]
Just installed Code Insiders on the same Windows version and it runs without issues.

**Comment by shay972** [comment]
and with regular build it is crashing also for you?

**Comment by shay972** [comment]
b.t.w there is no issue if I open file, and not a folder

**Comment by bpasero** [comment]
@shay972 would you be able to run Code out of sources as outlined in https://github.com/Microsoft/vscode/wiki/How-to-Contribute to see if that changes anything?

**Comment by shay972** [comment]
I followed the instructions (but did not installed studio, I have something
installed on my laptop)
I ran the script/code.bat
the windows open, I only get the upper menu (file, edit, view...) no left
menu.
and the funny thing is that only "open folder" is responding
but when I choose folder, nothing happened

**Comment by brian-thornton** [comment]
I see this crash as well.   In my case, I want to run two windows of Code.  The folder opens correctly in my first window.  When I create a new window and try to open a folder I see the crash.  I'm running Windows 10 and Code 1.4.0 both installed on 8/11/2016.

**Comment by bpasero** [comment]
@shay972 can you open developer tools (from the help menu) in that state?

**Comment by shay972** [comment]
yes

**Comment by brian-thornton** [comment]
File > New Window from the first window.  Then File > Open Folder in the new window.  The crash happens when I click Open Folder.  I do not see any folder selection dialog.

**Comment by shay972** [comment]
wow this is weird
I went back to 1.4, and I followed Brian steps to create the crash, but
this opened my directory
so for me this is the only way to open the folder (using second window) and
for Brian this causes a crash

**Comment by bpasero** [comment]
@brian-thornton if you use another tool that allows to open folders, does the same thing happen? your issue sounds unrelated to @shay972 issue because you see the crash when the native dialog shows up and @shay972 gets the crash after he picked a folder (if I understand correctly).

@shay972 are you always opening the folder using command line? did you ever try starting from an empty window and doing File > Open Folder?

**Comment by shay972** [comment]
I tried opening the folder from GUI or from CMD
I tried opening empty and folder with files
all the above crashed

**Comment by bpasero** [comment]
Did it work with previous versions of Code?

**Comment by shay972** [comment]
yes 1.3 - same issue

**Comment by brian-thornton** [comment]
I was able to identify a more specific cause of my issue.  I launch Code in compatibility mode because I have old monitors at work.  Selecting 'Reduced color mode' seems to be causing this problem.  If I remove this selection I can open folders without an issue.

**Comment by bpasero** [comment]
Jesus.........

**Comment by shay972** [comment]
I reduced the colors from 32 bit to 16 bit
seems you are correct

I closed the folders, close the GUI, open the GUI, open the folder - did
not crash

**Comment by joaomoreno** [comment]
Wow. We should investigate this, maybe propagate the issue to Electron.
