### ISSUE TITLE
Error while starting (Settings) Sync: Proxy Authentication Required

### ISSUE THREAD

**Issue by Dan503** [microsoft/vscode#105261]
- VSCode Version: Stable v1.48
- OS Version:

![image](https://user-images.githubusercontent.com/10610368/90991180-9ac60c80-e5ea-11ea-9e25-ccb3714b8463.png)

**Steps to Reproduce:**

1. Set up your internet connection to require a proxy server (I'm not sure how to do this)
2. Save [auth.js](https://github.com/microsoft/vscode/blob/master/src/vs/code/electron-sandbox/proxy/auth.js) into this folder: `C:\users\{username}\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-sandbox\proxy` (fixes bug with proxy server access)
3. Open VS Code
4. Enter Proxy authentication details
5. File > Preferences > Turn on Settings Sync...
6. Press "Turn On" button
7. Click "Sign in & Turn on"
8. Click "Sign in with GitHub"
9. Click "Continue"
10. Click "Open Visual Studio Code"
11. Click "Open"
12. Error messages appear

> Error while starting Sync: Proxy Authentication Required

> Sign in failed: Proxy Authentication Required
> Source: GitHub Authentication (Extension)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Dan503** [comment]
It's possible that this is more an issue to do with the security restrictions of my work environment than an issue with VS Code, but the error message suggests a proxy error rather than an authorization failure.

**Comment by gjsjohnmurray** [comment]
> Save auth.js into this folder: 

FYI this should no longer be necessary if you update to 1.48.1

**Comment by RMacfarlane** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/111824
