### ISSUE TITLE
Open editors list visual bug

### ISSUE THREAD

**Issue by tntc4** [microsoft/vscode#105211]
Issue Type: <b>Bug</b>

The "open editors" list has a little margin on bottom and this cause the list to render a scroll bar that has a veird behaviour.
see screenshots I have attached.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 6.1.7601

![Screenshot_1](https://user-images.githubusercontent.com/3246834/90954541-c1b30000-e47d-11ea-9400-27be5fd3f74c.png)
![Screenshot_2](https://user-images.githubusercontent.com/3246834/90954548-cd9ec200-e47d-11ea-9818-7bcf6adbfa90.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|23.91GB (16.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|4.2.0

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/67643
