### ISSUE TITLE
Overwrites environment variable ${LANG}: en_AU.utf8 -> en_GB.UTF-8

### ISSUE THREAD

**Issue by HaleTom** [microsoft/vscode#105206]
- VSCode Version: 
```
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.14-1-MANJARO
```

Steps to Reproduce:

1. Run VS Code with explicit `LANG=en_AU.utf8`:
`LANG=en_AU.utf8 /opt/visual-studio-code/code --no-sandbox --unity-launch --disable-extensions`
2. In a VS Code terminal, type: `echo $LANG`

The output of step 2 is:
```
en_GB.UTF-8
```

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by Tyriar** [comment]
You can disable this via `"terminal.integrated.detectLocale": "off"`. Looks like [`.utf8` is a valid format](https://serverfault.com/a/617075) as well that we should support when it's set to `"auto"`, so this is a valid bug.

**Comment by HaleTom** [comment]
Chapter and verse allowing mixed case:
https://unix.stackexchange.com/a/605777/143394

Also, `$LC_ALL` supercedes `$LANG` if set.  I'm working on a PR that is cognisant of this.

**Comment by Tyriar** [comment]
@HaleTom those improvements are also welcome 🙂

**Comment by HaleTom** [comment]
@Tyriar, there is no basis for the assertion that the non-hyphenated version is also valid.

I have provided a link to IANA and RFC specifications that show that names are case insensitive, so `uTf-8` is also valid.  But the `-` is required as per specifications.

PR coming within 2 weeks.

**Comment by HaleTom** [comment]
> Looks like [`.utf8` is a valid format](https://serverfault.com/a/617075) 

I just answered the same ServerFault question with chapter and verse showing that `.utf8` is not valid, but strangely `csUTF8` (this time case sensitive) is actually valid.

IANA Character set **names** are case **in**sensitive (here, `UTF-8`, the hyphen is important)
IANA Character set **aliases** are case sensitive (here `csUTF8`).

**Comment by Tyriar** [comment]
@HaleTom cool, have an upvote 👍. If it's not in the spec but still works let's support it as `auto`'s intent is meant to only replace when we're pretty sure the user hasn't got anything set up.

**Comment by Tyriar** [comment]
To verify:

1. Set `export LANG=en_AU.utf8` in your `.bashrc`/`.zshrc`
2. Relaunch VS Code
3. Open a terminal and make sure `$LANG` is not overridden (using the default `"terminal.integrated.detectLocale": "auto"`)

**Comment by HaleTom** [comment]
Cheers, I'll look into this shortly.
