### ISSUE TITLE
asAbsolutePath-usage in web

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105277]
The usage of `asAbsolutePath` as seen here https://github.com/microsoft/vscode/blob/890d7c61af3f6664b2c1460ad5af4274455a0b04/extensions/css-language-features/client/src/browser/cssClientMain.ts#L20 only works because there is there is special code to return a url-string (instead of a path, see [here](https://github.com/microsoft/vscode/blob/c30092a8384090993be53b65645cec0fbf62232d/src/vs/workbench/api/common/extHostExtensionService.ts#L389-L394)). For loading extension relative resources the `extensionUri` and `Uri.joinPath` should be used. That is the new, web-ready replacement API

**Comment by jrieken** [comment]
fyi @alexdima

**Comment by dbaeumer** [comment]
@jrieken tried to adopt this. When will `joinPath` be available. I can't find it in `1.48.x`.

**Comment by dbaeumer** [comment]
Opened https://github.com/microsoft/vscode-eslint/issues/1050 for ESLint

**Comment by jrieken** [comment]
It's in the API since 4 months...
