### ISSUE TITLE
[PLEASE] add a new key bingding for `Trigger suggestion` to deal with windows ime legacy-issue of history

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#105207]
for windows that language is chinese(I'm not sure about other non-English languages windows os), 
Whether it's Windows 7 or Windows 10, ctrl+space is bound by default as a shortcut to switch languages ime. This is a serious conflict with trigger suggestion. 
All these years have passed.Users are used to switching languages using this shortcut.
In Chinese operating system, users using vscode will encounter shortcut problems.
![image](https://user-images.githubusercontent.com/1876302/90947916-21a0ab00-e46c-11ea-8aa4-b364b3196754.png)

- [https://superuser.com/questions/363873/how-to-disable-ctrl-space-selecting-chinese-keyboard-on-windows-7](https://superuser.com/questions/363873/how-to-disable-ctrl-space-selecting-chinese-keyboard-on-windows-7)
- [https://www.google.com/search?q=windows+ctrl%2Bspace+ime](https://www.google.com/search?q=windows+ctrl%2Bspace+ime)

- [https://www.google.com/search?q=windows10+ctrl%2Bspace+ime](https://www.google.com/search?q=windows10+ctrl%2Bspace+ime)

Regarding the ctrl-space switch input method, cancellation is also supported until windows 10 (1903), but it is only  able to turn off and it turn on by default.
This is a legacy-issue of history.
![image](https://user-images.githubusercontent.com/1876302/90947728-b99d9500-e46a-11ea-8f52-256370b65929.png)

For this issue, you might say I can change the shortcut binding by myself. But I found that everyone around me found this problem when using vscode. Whether it's win7 or win 10. my work mates class mates, chats groups. 
It's impossible ASKING everyone to rebind the shortcuts themselves.

I have compare all key default-bingding of windows,linux and macos,
Only `ctrl+i` is a shortcut that is not currently in use and is ideal for triggering suggestion.

**Strongly request the addition of a new shortcut to solve this problem.** of cause, `ctrl+i` is a good choice, but it is up to you and vscode team.
after that, user can use `ctrl+space` or `ctrl+i` to trigger. 

please consider, thanks very much

**Comment by heartacker** [comment]
@rebornix hi, peng lyn, is there any idea to deal with it. I believe you would have the same problem when you‘re using chinese-language edition. In fact, It is very easy to fix it if you and your team have decided. On behalf of Chinese users  to say Thank you

**Comment by rebornix** [comment]
@heartacker thanks for your feedback!

>  I believe you would have the same problem when you‘re using chinese-language edition

I do. I hate it every time when I have to use Chinese IME. I love the idea of adding another default keybindings for it then everyone running into this problem can find one available keybinding to use when searching in the keybindings editor. `ctrl+I` is a good candidate, appreciate it!

**Comment by jrieken** [comment]
On macOS we support `Alt+ESC` to trigger completions for a very similar reason

**Comment by heartacker** [comment]
> On macOS we support `Alt+ESC` to trigger completions for a very similar reason

hi @jrieken @rebornix  thanks for your replies, and it seem that every platform have the some issues for key binding. I believe that it is  better having the same backup key-shot-cut like `ctrl+i`  for all platform than add different key-short-cut for each platform. 

you can compare each short-cut-reference pdf, you will find that there is no short-cut that using `ctrl+i`. i think it is a better choice.

**Comment by jrieken** [comment]
We have picked `Alt+ESC` because that's actually used for xcode - so kind of a platform thing. Tho, also adding ctrl/cmd+i sounds like a viable option to me

**Comment by heartacker** [comment]
> We have picked `Alt+ESC` because that's actually used for xcode - so kind of a platform thing. Tho, also adding ctrl/cmd+i sounds like a viable option to me

ok, thanks, and now, is time to figure it out. I tend to use the same shortcuts. Anyway, being able to add a new shortcut to all affected users was enough for me. so that  it will do not  make the "trigger suggestion" unavailable. But base on it,  it is a better choice to solve the problem of each platforms, after all, VSCode is a cross-platform product

**Comment by jrieken** [comment]
Too late for August, but adding for September. 

> Teams and mates including me are waiting for something changing. I do not know the development process of vscode, forgive me for my urged.

Well, you can always define your own keybinding while we haven't tackled this

**Comment by jrieken** [comment]
I have pushed a new, additional keybinding which is <kbd>Cmd+i</kbd> on macOS and <kbd>Ctrl+i</kbd> on Linux/Windows

**Comment by heartacker** [comment]
> I have pushed a new, additional keybinding which is <kbd>Cmd+i</kbd> on macOS and <kbd>Ctrl+i</kbd> on Linux/Windows. This change will be in next 1.50 Insiders (not 1.49) which will be release mid/end of week.

Great~~ Thank you very very much :smile
