### ISSUE TITLE
color picker resets back to old color on save

### ISSUE THREAD

**Issue by hiredtocode** [microsoft/vscode#105201]
- VSCode Version:Version: 1.49.0-insider (system setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open Code > settings.json
2. semanticTokenColorCustomizations > change color > save.

As soon as you save, the color picker mouse pointer "resets" to the previous color. 

Please note that workbench.colorCustomizations > change color > save works fine. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
@hiredtocode Sorry, the steps are too compressed. What do you mean by `Open Code > settings.json > F5` and `semanticTokenColorCustomizations > change color > save`.
What is the the color picker mouse pointer? Maybe add some screenshots to clarify. Thanks!

**Comment by hiredtocode** [comment]
@aeschli I was trying to make screenshots and create a reply but it was a bit comber-sum so I decided to make a short video so it's clear for both of us to diagnose this bug. Here's the link : https://youtu.be/q-JCOE5hKu4 
Let me know if it's not clear. Thanks.

**Comment by aeschli** [comment]
@hiredtocode Thanks a lot for the video! I can reproduce the issue.

**Comment by aeschli** [comment]
@rebornix Seems to be an issue with the color picker:
- Have the settings:
```json
{
    "json.trace.server": "verbose",
    "files.autoSave": "off",
    "editor.semanticTokenColorCustomizations": {
        "rules": {
            "*.declaration": "#000000"
        }
    }
}
```
- hover over the color decorator, in the color picker, change the color to all black
- press save while the color picker is open
- color picker switches to white (value is still black)

Looking at the `JSON Language Server` log:
- the black color information is correctly returned after the document update
- the color picker then asks for the color presentation of the white color to which the JSON server response to that request with the formatted white color. The color picker seems to hold on to the white.

**Comment by rzhao271** [comment]
Nvm, verified it locally, sorry about that
