### ISSUE TITLE
In Jupyter mode, when I use pandas.Dataframe(), the output column names are wrong aligned with actual columns

### ISSUE THREAD

**Issue by ztibeike** [microsoft/vscode#105276]
- VSCode Version: 1.46.1(user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. python programming in Juypter mode
2. use pandas to analyze data
3. print  pandas.DataFrame(), the output column names are wrong aligned with actual columns
 like this:
![image](https://user-images.githubusercontent.com/35754452/91023249-e5667980-e628-11ea-8cb7-097bc127b07b.png)
the right output is:
![image](https://user-images.githubusercontent.com/35754452/91023366-0af38300-e629-11ea-9f07-3568e85da904.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ztibeike** [comment]
I have only 'Python' extension enabled, and this problem still exists. Could you please tell me which extension causes this problem,  thanks @vscode-triage-bot

**Comment by ztibeike** [comment]
I have only 'Python' extension enabled, and this problem still exists. Could you please tell me which extension causes this problem, thanks @vscode-triage-bot @weinand

**Comment by weinand** [comment]
The Python extension.

**Comment by ztibeike** [comment]
Thanks, my fool😂 @weinand
