### ISSUE TITLE
VS Code is removing unused vars even when settings tell it not to do so

### ISSUE THREAD

**Issue by ScoRoc** [microsoft/vscode#105234]
- VSCode Version: 1.48.1
- OS Version: macOS 10.15.6

Steps to Reproduce:

Just save by hitting cmd + s.

I have removed all eslint and related packages from package.json, I have removed eslint and prettier extensions, I turned off format on save and turned off all codeActionsOnSave and VS Code is still deleting unused vars. I don't see any settings to stop this. It is literally making my code unusable since I cannot save.

Does this issue occur when all extensions are disabled?: Yes.

I tried launching with the disable extensions flag and it still doesn't work. I tried manually removing all extensions and it still doesn't work.

This issue started happening with the update about a week ago. Since it stopped working I've tried removing all eslint related packages, files, and settings to try and get it working and it _still_ removes the unused vars.

Here's the relevant files, which were working until the update about a week ago:

"settings.json"
(note, I've tried using `"source.fixAll.eslint": false` and `"editor.formatOnSave": false` and it still doesn't work)

```
{
  "workbench.colorTheme": "1Dark Poncho",
  "editor.minimap.enabled": false,
  "editor.tabSize": 2,
  "todo-tree.tree.showScanModeButton": false,
  "todo-tree.highlights.defaultHighlight": {
    // "background": "#5FF084",
    // "background": "#F0D769",
    "background": "#CF9FF0",
    "foreground": "black"
  },
  "eslint.options": {
    "configFile": "./.eslintrc"
  },
  "eslint.validate": ["html", "javascript"],
  "prettier.singleQuote": true,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.organizeImports": false
  },
  "prettier.jsxSingleQuote": true,
  "prettier.arrowParens": "avoid",
  "bracket-pair-colorizer-2.colors": ["Gold", "Orchid", "LightSkyBlue"],
  "window.zoomLevel": 0,
  "editor.formatOnSave": true
}
```

".eslintrc"
(note, I tried adding `"no-unused-vars": "off"` under rules to fix this but it didn't work)

```
{
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "node": true
  },
  "extends": ["eslint:recommended", "plugin:prettier/recommended"],
  "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": 2020
  },
  "plugins": ["prettier"],
  "rules": {
    "eqeqeq": "error",
    "linebreak-style": ["error", "unix"],
    "prettier/prettier": [
      "error",
      {
        "printWidth": 100,
        "singleQuote": true,
        "trailingComma": "all"
      }
    ],
    "singleQuotes": 0
  }
}
```

".prettierrc"

```
{
  "arrowParens": "avoid",
  "printWidth": 100,
  "singleQuote": true,
  "trailingComma": "all"
}

```

"package.json":
relevant eslint packages in devDependencies
(no other eslint packages in this file)

```
"devDependencies": {
    ...
    "eslint": "^7.7.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-config-standard": "^14.1.1",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    ...
    "prettier": "^2.0.4",
    ...
}
```

Furthermore, when clicking the ESLint extension in the status bar, it opens to the OUTPUT tab. When I switch to the PROBLEMS tab while using `"no-unused-vars": "off"` there are _no_ problems shown yet VS Code is _still_ deleting my unused vars.

**Comment by mjbvz** [comment]
One idea: maybe you opened up a different directory that caused the setting to apply? But it could also have been a VS Code update or any number of other factors

Let us know if you track down what was going on. Closing for now
