### ISSUE TITLE
Vs code consuming too much RAM since last update

### ISSUE THREAD

**Issue by mentamarindos** [microsoft/vscode#105281]
Issue Type: <b>Bug</b>

VS Code is consuming 30% of memory since the last update. I only got 4gb of ram and 30% is way too much. before the update it only uses like 15% - 20%.
Please fix it, thanks.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.83GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by FaruNL** [comment]
For what it's worth: [Some RAM usage](https://imgur.com/a/uKBy5S6)

Before I realized it, it was up to 6GB of RAM usage, in about 2 to 3 hours, again just for 4 tabs opened.

**Comment by deepak1556** [comment]
Can provide the output of `code --status` with latest stable.
