### ISSUE TITLE
How to trigger `registerCompletionItemProvider` when customized languages with "name"  = string

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode#105294]
I've write a plug in used to support language completions, and i trigger it with 
```shell
export const build_provider = languages.registerCompletionItemProvider(
   {language:"mylanguage"}, { provideCompletionItems }, '.');
```
where `mylanguage` is a new language defined in my `package.json`. It works well except when i edit in the params which is decorated with `string.quoted.docstring.multi.mylanguage`  in my `tmLanguage.json`. it's wired and i want to trigger the completions all the time. Hope for your help. Thanks a lot.

**Comment by jrieken** [comment]
The `language` is only going for the name of the language, not the scope or token name. There is no way to access those scope we as completion providers to understand the structure of a language in more depth than using just tokens

**Comment by Abbyyan** [comment]
> The `language` is only going for the name of the language, not the scope or token name. There is no way to access those scope we as completion providers to understand the structure of a language in more depth than using just tokens

Thanks a lot . Does that mean, If i named some string with `string.xxx` token name, It won't trigger in  `registerCompletionItemProvider ` only if the edit char is in `triggers`?

**Comment by jrieken** [comment]
Depends how you trigger IntelliSense. When pressing Ctrl+Space it will always be asked, when typing a word and when quick suggestions are enabled it will also be asked, last when setting certain trigger characters like `.` or `:`  it will be asked when those occur. Tho, all of it is independent of tokens

**Comment by Abbyyan** [comment]
> quick suggestions

Got it ! Thanks a lot.
