### ISSUE TITLE
Why is the account data not cleaned up

### ISSUE THREAD

**Issue by WangShuoran** [microsoft/vscode#105273]
I use the built-in sync, but I have a demand
I want to start over with an account, like a factory reset.
But I did not find that option, which means I don’t know what settings the account has, and restore it.
I want to completely clean up the account data and start over.

**Comment by sandy081** [comment]
Please follow this link to delete data from your account and start fresh - https://code.visualstudio.com/docs/editor/settings-sync#_how-do-i-delete-my-data
