### ISSUE TITLE
can switch preview support location?

### ISSUE THREAD

**Issue by chenjie4255** [Microsoft/vscode#10526]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.2.0

Steps to Reproduce:

when I edit a md file(eg in 50% location) I want change the view to preview to see the modified content, but the preview window just local the position in the begging.I thinks this could be  make a improvement.

**Comment by mjbvz** [comment]
I believe this would fall under editor/preview synchronization: #5047
