### ISSUE TITLE
VS Code Accessibility Call - August 2020

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#105293]
Each month, we try to hold a call where users in our accessibility community can give feedback, bring up problems, and share accessibility practices with members of our team. The next call will be held on Thursday, September 3rd at 8am PDT / 5pm CEST / 8:30pm IST.

In order to facilitate richer communication and get more focused feedback, we will limit to 4 people on the call, thus we are asking those who are interested in participating to fill out the sign up link below:

[Sign up to participate](https://aka.ms/vscode-a11y)

### Agenda:
- Introductions

- In previous calls, we've gotten feedback on settings editor accessibility (https://github.com/microsoft/vscode/issues/97567), primarily about tab and keyboard navigation through the virtualized list of settings, row selection, table of contents. We have worked on two new versions of a settings editor (one of which is currently in Insiders) and would like to discuss the UX. You can try out both versions here: (https://github.com/microsoft/vscode/issues/104318) @roblourens 

- We will leave some time at the end for folks to bring up some new topics or questions for our team to consider

We will reach out to confirm those who will be participating in the call and send you a Microsoft Teams link to join the call. We will post the meeting recording and meeting notes at the end of the call.

**Comment by isidorn** [comment]
We have done the accessibility call with some great feedback from our community regarding the settings editor.
Due to that closing this issue.
