### ISSUE TITLE
Outdated apt repository (insiders version) 

### ISSUE THREAD

**Issue by furai** [microsoft/vscode#105289]
Hey,

OS: Ubuntu 20.04

Apparently the last version that made it through to the repo is from 18th of August. Since then there were no updates in apt while from website I can download newer deb.

https://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/
vs
https://az764295.vo.msecnd.net/insider/f57a418b019926b38d2e6949265c33002a8f6f6b/code-insiders_1.49.0-1598247726_amd64.deb

Cheers,
Furai

**Comment by Tyriar** [comment]
We're aware of this and hope to have it updating again soon.

**Comment by furai** [comment]
It has just updated for me from the apt, so I guess it's resolved. Thanks! :)

**Comment by chrmarti** [comment]
Should indeed be fixed for .deb, .rpm and snap packages. When you do another update, the latest Insiders should be installed. There is a delay between VS Code detecting the update and the .deb package becoming installable, you might just have hit that.

**Comment by furai** [comment]
Yup, was exactly that, just got the latest version via apt.
