### ISSUE TITLE
Open same folder in Windows and WSL

### ISSUE THREAD

**Issue by razimgit** [microsoft/vscode#105248]
Issue Type: <b>Bug</b>

Can't open the same folder in Windows and WSL. I have two VS Code windows open: one is on Windows with an opened folder and one is on WSL. When I try to open the same folder from the WSL window it just throws me to local VS Code without opening the folder in WSL VS Code

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.8.103604
remote-wsl|ms-|0.44.4
cpptools|ms-|0.29.0
rewrap|stk|1.13.0

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
I just opened a local Window on `c:\\test\foo` and WSL window on `//mnt/c/test/foo`. That worked for me.

Is that what you tried to do? 

In the WSL window, did you click on the `Open Local` button? Don't do that, as this will switch to a local window. If the folder is already open in a local window, then VSCode will just focus to that window. That's how it is expected.

**Comment by razimgit** [comment]
Got it! Thanks for clarifying.
