### ISSUE TITLE
Running multiple configurations with same name is not working

### ISSUE THREAD

**Issue by tedovn** [microsoft/vscode#105272]
- VSCode Version: 1.48
- OS Version: macOS Catalina 10.15.6 / Windows 10 / Linux

Steps to Reproduce:

1. Tying to launch two nodes in one vscode window not working. Last version of vscode in which this worked is: 1.45 . Can you investigate this and fix it please. Thanks in advance.
2. The button for running a second project is not working.
3. I am attaching a screenshot with the issue button.

![Screenshot 2020-08-24 at 10 35 20](https://user-images.githubusercontent.com/7550128/91016585-a5d26a00-e5f5-11ea-89a9-31bf6ed5f4dd.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
This works just fine for me. And if you can reproduce with Insiders please create a minimal reproducable repository on GitHub which I can clone and just reproduce this issue. Thanks

**Comment by tedovn** [comment]
@isidorn 

In fact, I discovered what creates this issue. When you start two nodes with the same name in the launch.json file, you cannot start them both.

until version 1.45 this worked, but after her this stopped working. i am attaching repository to test it:
[https://github.com/tedovn/test-vscode-workspace](url)

**Comment by isidorn** [comment]
Yeah, we do not support that. I can leave this open as a feature request. Thanks for providing a repository

**Comment by tedovn** [comment]
Thanks for the fast response. I believe this will be fixed in future version.
