### ISSUE TITLE
The Azure CLI Tools is not working

### ISSUE THREAD

**Issue by kunalk06** [microsoft/vscode#105284]
We have written the nee
Issue Type: <b>Bug</b>

using Az login recieving the following error 
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#work-behind-a-proxy. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.18363

**Comment by chrmarti** [comment]
`az login` is part of the Azure CLI. Please open an issue there: https://github.com/Azure/azure-cli/issues
