### ISSUE TITLE
[Insiders] Custom task provider cannot use windows definition

### ISSUE THREAD

**Issue by kaysonwu** [microsoft/vscode#105215]
- VSCode Version: 11.49.0-insider (system setup)
-  OS Version:  Windows_NT x64 10.0.18363
- Commit: 44ad54d9faa4604ab17628e8396e072258187737
- Date: 2020-08-21T06:26:21.718Z
- Electron: 9.2.0
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0

When I add the `windows` specific command configuration, it will report that the command is not found, but it is normal when using `linux` and `osx`. I debugged my extension and made it clear that the problem should come from vscode

Steps to Reproduce:

1. download extension source code and example  code:

```shell
git clone https://github.com/kaysonwu/cpptask.git

git clone https://github.com/kaysonwu/cpp-examples.git

cd cpptask

yarn install
```

2. use `vscode-insiders`  open `cpptask` project.
3. Start debugging extension.
4. Open `cpp-examples` project  and debug `hello-world` example
5. Everything is normal.
6. Add windows platform configuration to `tasks.json` 

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Build C/C++ Project",
      "type": "cpp",
      "sources": [
        "${fileDirname}/**/*.cc"
      ],
      "output": "${workspaceFolder}/debug/${fileBasenameNoExtension}.exe",
      "options": {
        "cwd": "${fileDirname}"
      },
      "includePath": [
        "${workspaceFolder}/vendor/**/include"
      ],
      "libraryPath": [
        "${workspaceFolder}/vendor/**/lib/*"
      ],
      "compilerPath": "g++", 
      "compilerArgs": [
        "-g"
      ],
      "problemMatcher": [
        "$gcc"
      ],
+      "windows": {
+       "options": {
+          "cwd": "${workspaceFolder}"
+       }
+     },
      "group": "build"
    }
  ]
}
```

7. Re-debug the `hello-world` example
8. You will see the task cannot be found

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Platform specific properties in tasks are only supported for `shell` and `process` tasks.
