### ISSUE TITLE
Extensions stopped working

### ISSUE THREAD

**Issue by KPTousey** [microsoft/vscode#105255]
Issue Type: <b>Bug</b>

Extensions stopped working on the second day of use prompting two reloads. Both of which resulted in the same event.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 2127U @ 1.90GHz (2 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (1.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.2.0
path-intellisense|chr|2.2.1
prettier-vscode|esb|5.1.3
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
color-highlight|nau|2.3.0
LiveServer|rit|5.6.1
vscode-paste-and-indent|Rub|0.0.8

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
Can you please disable `auto-close-tag` and `auto-rename-tag`. AFAIK they cause a lot of performance problems with large files.
