### ISSUE TITLE
On Type Rename tests consume 20% of all unit test time

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#105269]
![image](https://user-images.githubusercontent.com/900690/91009596-2f2b7180-e5e1-11ea-8b8b-6c2557fb6c46.png)

I think this came with the introduction of some delayer.

**Comment by aeschli** [comment]
There's a denouncing timeout in there. Didn't realize it's taking so much time compared to the rest of the tests. Fixing...

**Comment by bpasero** [comment]
Thanks!
