### ISSUE TITLE
Incorrect error in TypeScript code

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#1052]
I'm using version df352367df2efcfa9d602d471e4e2f42140a0f05

For this code I get an incorrect error. 

```typescript
  /**
   * Removes all the children from `<div class="children"></div>` element
   *
  */
  removeChildren() {
    if (this.element.querySelector('div.children')) {
      this.element.removeChild(this.element.querySelector('div.children'));
    }
  }
```
TypeScript compiler does not complain for this code but VSCode throws this error:

<img width="1199" alt="cap" src="https://cloud.githubusercontent.com/assets/543633/11614942/575d0dae-9c07-11e5-8caf-7dd6da702b20.png">

**Comment by mohsen1** [comment]
I thought I should share this knowledge with you as well. Taking an screenshot from the hover popup was impossible with the regular <b><code>⌘+⇧+4</code></b> key combination won't work since pressing those keys will make the popup disappear. I found out I can schedule a screenshot using `screenshot` command with `-T` flag in OSX:

```shell
screencapture -T 5 -C ~/Desktop/cap.png
```

**Comment by dbaeumer** [comment]
This looks like a buffer sync issue. Need to check whether tsserver 1.7.x already supports sending the content of a buffer on open which should avoid this.

@mohsen1 after closing and reopening VS Code is the error still there or does it disappear?

**Comment by mohsen1** [comment]
Closing and re-opening fixed the issue.

**Comment by dbaeumer** [comment]
@jrieken: this is hard to verify since it depends on upstream behavior of the tsserver. Please verify that the TS buffer sync support now sends the content on open and doesn't rely on disk sync anymore.

**Comment by jrieken** [comment]
Verifying I see [this](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/bufferSyncSupport.ts#L31) and that it's being called
