### ISSUE TITLE
Feature Request: VSCode plugin for quickly opening a PR to fix/improve types.

### ISSUE THREAD

**Issue by ccorcos** [microsoft/vscode#105242]
Have you ever cmd+clicked in VSCode, landed in some `@types/<package>` and wanted to fix or improve the types?

Then you think of the time it would take and the distraction it is creating so you don't fix the types and you move on.

Now imagine there was a new feature in VSCode and when you save a file inside `node_modules/<package>`, VSCode offers to create a PR with your change.

It could take you less than a minute to propose changes which will make it easier for everyone to contribute to maintaining community types. 😄

**Comment by mjbvz** [comment]
You may be able to leverage the PR extension to build this: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
