### ISSUE TITLE
Can not register self-hosted codespace

### ISSUE THREAD

**Issue by enhuichang** [microsoft/vscode#105321]
Issue Type: <b>Bug</b>

Can not register self-hosted codespace

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1265L V2 @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.84GB (13.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.19.0
azure-account|ms-|0.9.2
vsonline|ms-|1.0.2688
team|ms-|1.161.0

</details>

**Comment by enhuichang** [comment]
Hi there,

I tried all day. still doesn't work.

**Comment by RMacfarlane** [comment]
Hi @enhuichang, can you reopen this in the Codespaces repository? (https://github.com/microsoftdocs/vscodespaces). I'm unfortunately not able to transfer this issue
