### ISSUE TITLE
tsconfig/jsconfig exclude doesn't work with '.' directories

### ISSUE THREAD

**Issue by dschnare** [Microsoft/vscode#1053]
Hello,

I've been using Visual Studo Code for quite some time and love the tsconfig and jsconfig concept, however I've found that when specifying a folder such as ".meteor" in the exclude array the IDE/editor still traverses the ".meteor" directory. I would expect it not to.

**Comment by egamma** [comment]
Is this for both jsconfig and tsconfig? For tsconfig please file the issue against microsoft/typescript. Jsconfig attempts to be a subset and feature compatible with jsconfig.

**Comment by jrieken** [comment]
For `jsconfig` it was fixed as part of the work for #703

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).
