### ISSUE TITLE
vscode doesn't load types that are in subfolder

### ISSUE THREAD

**Issue by Upd4ting** [microsoft/vscode#105399]
- VSCode Version: 1.8.41
- OS Version: Window 10 version 1909 (18363.1016)

Steps to Reproduce:

I'm having a folder `www` with a nuxt application inside.

My tsconfig look likes this:

```
{
  "compilerOptions": {
    "target": "es2018",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": ["esnext", "esnext.asynciterable", "dom"],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"]
    },
    "types": ["@types/node", "@nuxt/types"]
  },
  "exclude": ["node_modules", ".nuxt", "dist"]
}
```

I created a `types` folder with an `index.d.ts` inside:

```
import Vue from 'vue';

declare module 'vue/types/vue' {
  interface Vue {
    $test: string;
  }
}
```

where i'm trying to augment the typing of Vue and when i'm trying to use my `$test` property i'm getting the error `Property '$test' does not exist on type 'default'.Vetur(2339)`

But if i'm opening directly the `www` folder into vscode instead of the parent directory, that's working fine.

Any solutions to this?

Does this issue occur when all extensions are disabled?: Yes

**Comment by triforcely** [comment]
Wrong project, try https://github.com/vuejs/vetur instead.

**Comment by Upd4ting** [comment]
Sorry, issue has been moved here: https://github.com/vuejs/vetur/issues/2196
