### ISSUE TITLE
opening a file associated to vscode using start-process show electron output on console

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/vscode#105374]
Issue Type: <b>Bug</b>

opening a file associated to vscode using start-process show electron output on console
![image](https://user-images.githubusercontent.com/43626415/91233254-2df46480-e707-11ea-875e-7ad5f9590ae0.png)

even worse is that if the console is closed so is vscode

---
Steps to Reproduce:
1. use start-process PowerShell cmdlet to open a file that is associated to open in vscode (I used .ps1)

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.58GB free)|
|Process Argv|C:\Users\luanv\Documents\PowerShell\Microsoft.PowerShell_profile.ps1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
githistory|don|0.6.9
vscode-great-icons|emm|2.1.47
vscode-pull-request-github|Git|0.19.0
discord-vscode|icr|4.0.0
c-cpp-flylint|jbe|1.5.1
vscode-language-pack-pt-BR|MS-|1.48.3
remote-wsl|ms-|0.44.4
cpptools|ms-|0.29.0
hexeditor|ms-|1.2.1
powershell|ms-|2020.6.0
code-spell-checker|str|1.9.0
code-spell-checker-portuguese-brazilian|str|0.1.4
windows-terminal|Tyr|0.6.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
It seems like the console sessions is getting attached, any ideas @deepak1556?

I'm not familiar with Start-Process but this could be by design? Why not just run `$PROfile` instead?

**Comment by LuanVSO** [comment]
I you can use start to open any file with its default program. if I just run $profile it will just print out the path to the PowerShell profile settings.
here is the output from the help command:
```
DESCRIPTION
    The `Start-Process` cmdlet starts one or more processes on the local computer. By default,
    `Start-Process` creates a new process that inherits all the environment variables that are defined in
    the current process.

    To specify the program that runs in the process, enter an executable file or script file, or a file that
    can be opened by using a program on the computer. If you specify a non-executable file, `Start-Process`
    starts the program that is associated with the file, similar to the `Invoke-Item` cmdlet.

    You can use the parameters of `Start-Process` to specify options, such as loading a user profile,
    starting the process in a new window, or using alternate credentials.
```

**Comment by deepak1556** [comment]
If you are opening vscode without using the wrapper scripts `code.cmd` or `code.exe`, then please set the environment `ELECTRON_NO_ATTACH_CONSOLE` to avoid attaching to the console.
