### ISSUE TITLE
Settings Sync not available in stable build

### ISSUE THREAD

**Issue by vickz84259** [microsoft/vscode#105310]
I was trying to turn on Settings Sync but when I click the **Manage** gear menu there's no **Turn on Settings Sync** option. (https://imgur.com/RmTlUcW) Also, searching for **Settings Sync** in the command palette or the settings doesn't bring up anything. Interestingly though in the Output window there is a **Log (Settings Sync)** and when started with --verbose, the output just shows:

[2020-08-19 23:57:48.877] [userDataSync] [trace] GlobalState: Checking for local changes...

This output is repeated multiple times.

- VSCode Version: 1.48.0
- OS Version: Linux x64 5.8.1-arch1-1

Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T19:02:57.619Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.8.1-arch1-1

Steps to Reproduce:

1. Update to version 1.48
2. Click **Manage** gear menu
3. Expected **Turn on Settings Sync** option is missing

Does this issue occur when all extensions are disabled?: Yes

I think this may be related to #104683. In my case though, local extensions are all visible and I hadn't setup Settings Sync

**Comment by sandy081** [comment]
Can you please check if following built-in extensions are enabled?

- Microsoft Account
- GitHub Authentication

If both of them are enabled, I suspect your installation might be corrupted because I would expect following as first entry in the output

`[2020-08-25 09:24:31.789] [userDataSync] [info] Using settings sync service https://....`

**Comment by vickz84259** [comment]
Yes, both extensions are there and enabled. Let me try reinstalling. I will get back to you on how that goes.

**Comment by Kriechi** [comment]
Same problem here.
```
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

I do see the big button at the top-right in my settings. However, after selecting which settings to sync sync and clicking on "Sign in & turn on" nothing happens. The Output box does not show anything more. Both built-in auth extensions are enabled.

**Comment by codewithtomi** [comment]
Same issue here.  Here is version info:

Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:56:10.074Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-47-generic

1. there's no Turn on Settings Sync option
1. Setting Sync: Show Setting->Turn on Setting Sync(button Click prompt)->Turn On. Nothing happens.

**Comment by Shatur95** [comment]
Is Settings Sync available for open source builds? On Linux usually used open source version (Code - OSS) from repos.

**Comment by codewithtomi** [comment]
Hi. Version 1.49.0 fixed this to me. I managed to setup setting sync now and  `Setting sync is on` now appears in manage gear.

Thanks!

Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:20:50.359Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-47-generic

**Comment by sandy081** [comment]
Thanks for confirming @codewithtomi.

@Kriechi Let me know if you still have the issue after updating?

@Shatur95 Settings Sync is not available on open source build.

**Comment by Shatur95** [comment]
@sandy081, will Settings sync be available for OSS builds in the future?

**Comment by sandy081** [comment]
As of now no plans.
