### ISSUE TITLE
Synchronize menu bar colors with color themes

### ISSUE THREAD

**Issue by RiceReallyGood** [microsoft/vscode#105338]
Issue Type: <b>Feature Request</b>

I'm using Ubuntu 20.04LTS with standard window color. And my VScode's color theme is defult dark. The appearance of the VScode  window is ike this 
![appearance](https://user-images.githubusercontent.com/61447011/91147630-1ad39b80-e6eb-11ea-9d77-4a683fb1adac.png)
![appearance2](https://user-images.githubusercontent.com/61447011/91147839-6a19cc00-e6eb-11ea-92ee-aae9e5d83312.png)
can you Synchronize menu bar colors with color themes?
Thanks!

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:11:59.963Z)
OS version: Linux x64 5.4.0-42-generic

**Comment by RiceReallyGood** [comment]
The menu bar color is always white whatever the color theme is. It's weird when using dark themes.

**Comment by RMacfarlane** [comment]
Hi @RiceReallyGood, you can make the title bar themeable by changing the `window.titleBarStyle` setting to "custom" instead of the default "native".
