### ISSUE TITLE
File Explorer as Ctrl-P popup

### ISSUE THREAD

**Issue by LucaGabi** [microsoft/vscode#105337]
VSCode dose a very good job to allow fast navigation when it comes to files, no mouse needed but ..not when it comes to adding files or folders. 

### **The request:** allow the current ctrl-p files filter to also 

1. **_show the tree structure of the files (including folders) filtered_** and with:
- shift-enter on any entry folder or file show an input to enter name for a **_new folder_** relative to the path of the item that was active
- alt-enter show an input to enter name for a **_new file_** relative to the path of the item that was active

2. **_select multiple files_** (with insert key) then: 
- at enter **_open files_**, 
- at F5 **_copy_**, F6 **_move_** the selection to a chosen folder, 
- at Del **_delete_** the selection with confirmation
3. star key **_marks as current selection expanding_** in the current branch of the active item
4. ctrl-star **_clears all selected files_**

_Note: selected files remain marked on new filter expression_

**Reason:**
Fast coding is the first feature of vscode also doing fast fs operations helps with fast coding flow.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
