### ISSUE TITLE
When OnTypeRenameProvider API will be moved to stable API?

### ISSUE THREAD

**Issue by angelozerr** [microsoft/vscode#105394]
We have experimented the  `OnTypeRenameProvider` API in our XML Language Server and it works pretty well. But we cannot consume it since it's a experimental API for the moment.

@octref  have you some idea when `OnTypeRenameProvider` will move to stable API?

Thanks for your answer.

**Comment by RMacfarlane** [comment]
Hi @angelozerr, since there is an existing issue for this, please continue discussion on it there: https://github.com/microsoft/vscode/issues/94316
