### ISSUE TITLE
Import Syntax Highlighter for JS behaving unreliably

### ISSUE THREAD

**Issue by jethroFloyd** [microsoft/vscode#105393]
Issue Type: <b>Bug</b>

Try out the following piece of code: 

```
import React from "react";

import StickyButton from "./StickyButton";
import Button from "./Button";

class ExpandButton extends React.Component {
  state = {};
  render() {
    return (
      <div>
        <StickyButton text={this.props.headliner} />
      </div>
    );
  }
}

export default ExpandButton;
```

In this code, VS Code says that React is declared but not used (and hence not highlighted), and on the other hand shows that the component Button is being used (which is not true). 

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:09:41.484Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.32GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.2.1
go|gol|0.16.1
vscode-peacock|joh|3.8.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.5.0
vscode-data-preview|Ran|2.0.0

(2 theme extensions excluded)

</details>

Screenshots:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/8988029/91274296-17e4b380-e79c-11ea-8f12-908ed5336a19.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/8988029/91274325-203cee80-e79c-11ea-9eec-d66059b1a014.png">

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jethroFloyd** [comment]
Thanks, @mjbvz for your response. No, this doesn't reproduce in the Insiders Build or the Stable Releases anymore. 
Seems to have been a one-off issue. I am closing this issue, and if I am able to reproduce it reliably, I will re-open it. 

Thanks!
