### ISSUE TITLE
Untrack files

### ISSUE THREAD

**Issue by ZanderBrown** [Microsoft/vscode#10539]
- VSCode Version: 1.4.0
- OS Version: Windows 8.1 x86

Call me lazy but it would be really good to have the ability to right click files and untrack them from Git.

**Comment by joaomoreno** [comment]
Use a [`.gitignore`](https://git-scm.com/docs/gitignore) file for this. You can even edit it in VS Code.

**Comment by ZanderBrown** [comment]
yeah I know but it could be useful

**Comment by joaomoreno** [comment]
The extension API now has support for [menu contributions](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus). You can implement your idea as an extension, how about giving that a try?

**Comment by mrmlnc** [comment]
@ZanderBrown, I can create this extension.

**Comment by ZanderBrown** [comment]
looks about perfect 😄
