### ISSUE TITLE
Quick open file search: flickers when typing while open

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10537]
Looks like a regression from 1.4.

**Comment by bpasero** [comment]
@chrmarti this seems to be caused by your changes in the last PR we merged. Steps to reproduce:
* open quick open for file search
* start to type until you see "no results"
* continue typing and notice each keystroke flickers
* same happens when you widen the search by removing characters

My first feeling is this might be related to moving the cache out of process so it takes time to get the results back and as such the UI has a chance to render quickly and we see flicker?

**Comment by chrmarti** [comment]
The time to get the results from the cache is similar to before. The main difference is that we no longer do that synchronously, so now the UI can redraw during that time.

What if we let the old results display for a few more 100ms before we remove them and indicate progress?

**Comment by bpasero** [comment]
But the file search could always take some time, at least when widening the search I would expect flicker in previous versions too.

**Comment by chrmarti** [comment]
Previously OpenAnythingHandler.getResults() would return a resolved promise with the result if that was available from the cache. With the cache residing in the search process, the returned promise is always pending when returned.

When the returned promise was resolved, the UI would not redraw without results, but directly show the new results.

In 1.4.0 a widening search flickers only if it can't be served from the cache. For that you need to be quick in typing a few characters for the first search and then backspace one by one to see the flicker.

**Comment by bpasero** [comment]
Right. As it works now I do not have a good idea how to improve the situation. I think quick open handlers need more control over the underlying model and tree in order to implement the logic we want. Currently the model is so disconnected that introducing a delay before updating the tree would cause issues for all other handlers of quick open.

**Comment by bpasero** [comment]
I can investigate for a fix for August that quick open can be configured to have a certain delay before updating the UI.

**Comment by chrmarti** [comment]
That would be great. I was wondering if maybe getResults() could return either TPromise<QuickOpenModel> or an object holding the promise and additionally a flag to indicate that the UI should not update immediately. That would be non-breaking for existing handlers.

**Comment by bpasero** [comment]
Still bad.
