### ISSUE TITLE
Load 'node-pty' async

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#105345]
I see no reason why `node-pty` needs to be loaded sync, as I think it is only used when an integrated terminal is opened. Loading it via `await import('node-pty')` could save some ms on startup:

![image](https://user-images.githubusercontent.com/900690/91155587-535f7f00-e6c3-11ea-9250-7d61ca6ed9f1.png)

//cc @jrieken

**Comment by Tyriar** [comment]
:+1: already do this for xterm.js

**Comment by bpasero** [comment]
PR is up: https://github.com/microsoft/vscode/pull/105401
