### ISSUE TITLE
Visual Studio Code marketplace is unavailable

### ISSUE THREAD

**Issue by pleabargain** [microsoft/vscode#105354]
![no marketplace data Peek 2020-08-25 16-19](https://user-images.githubusercontent.com/640846/91179210-e06bfd80-e6ee-11ea-9cc6-be9841f16674.gif)

Latest version same problems!

Version: 1.48.1
Commit: 3dd9051
Date: 2020-08-19T17:11:59.963Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic snap

bug was closed 
https://github.com/microsoft/vscode/issues/101497
reopening as the problem still exists

review the extensive details I posted
https://github.com/microsoft/vscode/issues/101497

And, I'm getting messages from other users via youtube that they are having the same problem with Visual Studio Code

**Comment by sandy081** [comment]
Closing this and reopened #101497.
