### ISSUE TITLE
Settings does not reflect.

### ISSUE THREAD

**Issue by neerajrk2509** [microsoft/vscode#105332]
Issue Type: <b>Bug</b>

I had changed the tabSize to 2 for one of my projects and again to 4 for my other project but it isnt reflecting in my project.
TabSize remains on 2 even though if I open the indentation action and shows 4 as configured tab size.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (2.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.4
ng-template|Ang|0.1000.7
vscode-color|ans|0.4.5
blamer-vs|bea|0.5.2
vscode-multi-line-tricks|big|0.0.3
node-snippets|chr|1.1.1
angular-schematics|cyr|4.3.0
angular2-snippets|dan|1.0.21
githistory|don|0.6.9
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
vscode-svn|eli|0.1.0
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.1.3
tortoise-svn|fan|0.1.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-ionic-snippets|fiv|2.2.2
auto-rename-tag|for|0.1.4
vscode-icontheme-nomo-dark-macos|Gau|1.0.3
triggertaskonsave|Gru|0.2.16
theme-macos-classic|hua|1.2.1
easy-icons|jam|0.3.1
angular-essentials|joh|9.0.1
vscode-peacock|joh|3.8.0
svn-scm|joh|2.12.3
vscode-icon-theme|jtl|1.6.6
angular1-code-snippets-johnpapastyle|lpe|0.1.0
code-beautifier|mic|2.3.3
vscode-autoprefixer|mrm|3.0.1
vscode-scss|mrm|0.9.0
debugger-for-chrome|msj|4.12.8
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.3.0
angular-console|nrw|13.0.0
vscode-html-scss|P-d|0.0.42
material-icon-theme|PKi|4.2.0
seti-icons|qin|0.1.3
try-material-icon-theme|raf|3.9.0
vscode-seedling-icon-theme|ras|0.5.0
typescript-hero|rbb|3.0.0
ts-import-assistance|Sam|0.0.10
code-settings-sync|Sha|3.4.3
bootstrap4-vscode|the|6.1.0
Angular2|UVB|0.4.1
vscode-angular-support|vis|0.1.4
vscodeintellicode|Vis|1.2.10
vscode-todo-highlight|way|1.0.4
local-history|xyz|1.8.1
material-theme|zhu|3.8.5
html-css-class-completion|Zig|1.19.0
svn-helper|Zlo|1.0.3

(5 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
That's an old version of vscode, can you try updating?
