### ISSUE TITLE
Press <F3> to search for a string

### ISSUE THREAD

**Issue by yashshah1** [microsoft/vscode#105327]
Currently, after highlighting a word, pressing `Ctrl+F`, triggers a search and then repetitively pressing `<F3>` will sequentially show you all the matches.

However, pressing `<F3>` after highlighting a word, will bring up the last searched item (if it isn't the first word you're searching for; if it is, it will search for the word).

## Feature Request
Pressing `<F3>` after highlighting a word triggers the find menu with the highlighted word

**Comment by RMacfarlane** [comment]
You could configure the keybinding for "Find" (`Ctrl+F`) to instead be `F3`. https://code.visualstudio.com/docs/getstarted/keybindings

Does that achieve what you want?

**Comment by yashshah1** [comment]
@RMacfarlane not really.

Ideally I would want both `Ctrl-F` and `<F3>` to allow me to search for things. 

Currently, after using ctrl+F on a highlighted bit of text, I can use F3 to see the next search result, but can't use it to trigger a new search which seems a little inconsistent. 

I could be wrong here, but setting a custom Key binding will not allow me to use both of those keys, right?

**Comment by roblourens** [comment]
You could probably get this to work with the right "when" clauses for your keyboard shortcuts. Basically you want F3 to run the ctrl+f command when focus is in the text editor.

**Comment by yashshah1** [comment]
Okay, thank you! Will take a closer look at the key bindings. 

However, is there no way this could be shipped as a default behaviour, with the facility to turn it off?

**Comment by roblourens** [comment]
I wouldn't want to change the default behavior, or add a new keybinding, and it feels odd for a setting to change this. But I will leave the decision to the expert.

**Comment by yashshah1** [comment]
Any update on this?
