### ISSUE TITLE
user snippets odd logic

### ISSUE THREAD

**Issue by vammex** [microsoft/vscode#105387]
Issue Type: <b>Performance Issue</b>

I am in trouble with using user snippets. Sometimes it is really weird.
I created a simple snippet for javascript.some function.
The trigger key is "sss".
Once I write "sss" in a code row, I see the pic.2 with no my snippet appears in the suggestion list.
But after that I backspace "sss" letters and... write them again - and I see pic.3 WITH my snippet inside.
Someone can explain this weird behavior? I tried to find it with arrow keys at the second step - no snippet at all.
How to force it showing the snippet immediately? 
<a href="https://ibb.co/VDfpTDQ"><img src="https://i.ibb.co/pZYrdZR/99999.png" alt="99999" border="0"></a>
<a href="https://ibb.co/JkFJgVZ"><img src="https://i.ibb.co/ZT1D759/88888888.png" alt="88888888" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>free image hosting</a><br />
<a href="https://ibb.co/26GQBSV"><img src="https://i.ibb.co/0XHS3K4/88888888888.png" alt="88888888888" border="0"></a>

my settings that may be involved:
     "workbench.editor.enablePreview": false,
      "editor.suggest.snippetsPreventQuickSuggestions": true,
    "editor.tabCompletion": "onlySnippets",
    "editor.snippetSuggestions": "top",

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.13

</details>

**Comment by jrieken** [comment]
please provide the snippet and sample file as text, not images. also please write down the exact sequence of what you are typing

**Comment by vammex** [comment]
the snippet: 

"some ": {
		"prefix": "sss",
		"body": [
			"some(function ($1) { return $2 == $1;})"
		],
		"description": "some"
	}

and i write a word "function" and then  "sss" and expect to get a corrent suggestion

**Comment by jrieken** [comment]
in what language is this?
