### ISSUE TITLE
show all editors

### ISSUE THREAD

**Issue by adrielwerlich** [microsoft/vscode#105353]
Issue Type: <b>Feature Request</b>

Show editors has 2 options
'edt mru' most recently used and 
and by appearance
But would be interesting to have a third option
Simply list all editors available in the project folder, meaning, if I have a vue app, show all my single file component (SFC) available

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.18363

This is what I get currently
![image](https://user-images.githubusercontent.com/20656722/91176993-76853100-e6b9-11ea-8244-9f5a6de6e8e5.png)

This is what I should be able to get in one shortcut key stroke, withouth having to backspace in the command line
![image](https://user-images.githubusercontent.com/20656722/91177055-9288d280-e6b9-11ea-8875-75bd95cb76ea.png)

**Comment by RMacfarlane** [comment]
@adrielwerlich You can open this view with the `Go to file...` command, which is by default bound to Ctrl+p on Windows
