### ISSUE TITLE
VSCode crashing Mac while is idle on external monitor 

### ISSUE THREAD

**Issue by adsonvinicius** [microsoft/vscode#105377]
- VSCode Version: Latest Mac Version
- OS Version: Mojave or catalina

Steps to Reproduce:

1. Using VSCode/MacOS on external monitor
2. Let it be idle

Does this issue occur when all extensions are disabled?: Yes

It's weird for me because I never saw a problem like that. I have a MBP Mid 2012 (With 2016 3 thunderbolt motherboard) and always when I let my Mac idle with VS code on external monitor my Mac crashes and reboot, I even made a counter to register after exactly 21 minutes it crashes. It just happens when the VSCode is opened and I leave computer idle. This only happens if the external monitor is cable-connected (even turned off)

Is there any explanation for it?

**Comment by deepak1556** [comment]
Does this happen when you use https://code.visualstudio.com/insiders/ ?

If the crash continues to happen with insiders, please launch with `--crash-reporter-directory /tmp/vscode-crash`. Attach the generated dump files.

**Comment by adsonvinicius** [comment]
It becomes unpredictable, I will close this issue for now.
