### ISSUE TITLE
Weird mouse behavior on visual studio  code

### ISSUE THREAD

**Issue by shahab570** [microsoft/vscode#105384]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

I am unable to use CTRL+V for paste and other keyboard shortcut such as copy,cut. Whenever i use these shortcuts nothing happens .sometimes it changes text randomly such as everytime I type Ctrl+X for cut, it reduces variable value in the selection.How can i solve this? 

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (4.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    77	   444	code main
    0	    27	  2780	   utility
    0	   184	  2900	   gpu-process
    0	   173	  3828	   window (style.css - css pracctive - Visual Studio Code)
    0	    13	  2968	     watcherService 
    0	    11	  6780	       console-window-host (Windows internal process)
    0	    35	  5860	     searchService
    0	   115	  7420	     extensionHost
    0	    44	  7668	       electron_node agent.js 
    0	    33	  8708	       "C:\Users\Shahab Uddin\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Shahab Uddin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=7420
    0	    55	  9964	       "C:\Users\Shahab Uddin\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Shahab Uddin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=7420
    0	    27	  9996	       electron_node eslintServer.js 
    0	    28	 10028	       electron_node serverMain.js 
    0	    14	  6028	   electron-crash-reporter
    0	    66	  8032	   window (Issue Reporter)
    0	    79	  8256	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (style.css - css pracctive - Visual Studio Code)
|    Folder (css pracctive): 28 files
|      File types: jpg(14) svg(7) webp(1) png(1) html(1) js(1) mp3(1) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
emojisense|bie|0.7.0
path-intellisense|chr|2.2.1
codestream|Cod|8.3.3
hex-to-rgba|dak|1.0.0
vscode-eslint|dba|2.1.8
es7-react-js-snippets|dsz|2.8.3
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.2.1
auto-rename-tag|for|0.1.4
auto-comment-blocks|kev|1.0.1
vscode-duplicate|mrm|1.2.1
LiveServer|rit|5.6.1
js-snippets|run|0.2.6
vim|vsc|1.16.0
quokka-vscode|Wal|1.0.315
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you reload with all extensions disabled? There is a Command Palette item that does this.

**Comment by shahab570** [comment]
> Does the problem also happen if you reload with all extensions disabled? There is a Command Palette item that does this.

When i selected "Reload with extensions disabled", this problem solved. Problem gone. But I need to use extensions.

**Comment by gjsjohnmurray** [comment]
/causedByExtension 

Disable all extensions. Then enable them one at a time until you find the one causing your problem. Then report it to the extension author.

**Comment by shahab570** [comment]
At last I found out the problem. There was an extension named "Vim" was causing the problem. Thanks a lot guys for your help.
