### ISSUE TITLE
avoid lookups to api.npms.io for invalid package names

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#105334]
- open a package.json
- start editing a package dependency with the mouse over the dependency
- accesses are made to npm.exe or `api.npms.io` to look up the description

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode/commit/88664e267a5ec3d7ed43a542b4cd3c8e456a9fd9
and https://github.com/microsoft/vscode/commit/ed1597336011643e627aa3f5a191647c049ac974

**Comment by isidorn** [comment]
Since this is fixed closing

**Comment by aeschli** [comment]
To verify:
- have a machine with no npm installed
- use the network view to verify that api.npms.io is not accessed if you have package names that have characters not valid in URLs
