### ISSUE TITLE
Support fish shell for tasks

### ISSUE THREAD

**Issue by sahilrajput03** [microsoft/vscode#105344]
Version: 1.48.1 (user setup)
OS: Windows_NT x64 6.3.9600

Steps to Reproduce:

1. Set fish executable in the settings(json) like below - 
![](https://i.imgur.com/rZMDENV.png)
2. Set some scripts like this -
![](https://i.imgur.com/iyomrOr.png)
2. Clicking on any script start or build, will give output as - 
![](https://i.imgur.com/0da6L4t.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sahilrajput03** [comment]
What is this "Unable to read input file: Is a directory" issue???
I'm having no other difficulty in terminal while I do, "npm run build" or "npm run watch".

**Comment by alexr00** [comment]
I'm guessing that we just don't support fish correctly. If you are willing to use a supported shell for you tasks you can use the setting `terminal.integrated.automationShell.windows`.

**Comment by sahilrajput03** [comment]
> I'm guessing that we just don't support fish correctly. If you are willing to use a supported shell for your tasks you can use the setting `terminal.integrated.automationShell.windows`.

Can you please explain how i can pass args to executable via this vscode option?

**Comment by sahilrajput03** [comment]
Amazing !!, you actually solved my issue..! now that i have set below option -
  "terminal.integrated.automationShell.windows": "C:\\Windows\\System32\\cmd.exe",
now, i can use my scripts with no errors, thanks a lot.
And good thing is i have fish with termianl too. 

Amazing!!

😍😍😍😍

**Comment by sahilrajput03** [comment]
So, I'm closing this issue!!
Thanks, @alexr00 !
You helped me, it was amazing talking to you. 😋😋

**Comment by sahilrajput03** [comment]
For people wondering how i have set up my fish with vscode:

I have just used this setting in my settings.json file -
  "terminal.integrated.shell.windows": "C:\\msys64\\usr\\bin\\fish.exe",
