### ISSUE TITLE
dubuger for edge

### ISSUE THREAD

**Issue by liam-bonner** [microsoft/vscode#105363]
Issue Type: <b>Feature Request</b>

a debuger that runs in the new edge

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.19041

**Comment by weinand** [comment]
Just install this extension: https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-edge
