### ISSUE TITLE
Option to rebase / merge

### ISSUE THREAD

**Issue by fab1o** [microsoft/vscode#105300]
I like the multitude of **git** commands in the new version of VSCode. It would be nice if we could also do **rebase** and **merge**.

Consider this a Feature Request.

Thank you

**Comment by RMacfarlane** [comment]
Hey @fab1o, both of these are already available as commands:
`Git: Merge Branch...`
`Git: Pull (Rebase)`

These are available from the command palette, and from the "..." context menu in the source control viewlet.

**Comment by fab1o** [comment]
But my Suggestion is to include it here:

![Screen Shot 2020-08-25 at 15 47 18](https://user-images.githubusercontent.com/6663243/91220549-5326aa00-e6ea-11ea-93f6-9917b34bf6d8.png)
