### ISSUE TITLE
Allow to Close/Open project in workspace

### ISSUE THREAD

**Issue by rameshkatare9** [microsoft/vscode#105348]
I would be great if there is feature of open/close project from workspace instead adding/removing project from workspace. This feature is available in Eclipse Editor.

**Comment by RMacfarlane** [comment]
@rameshkatare9 Can you describe in more detail the behavior you want to see? Is it something like, if you have a workspace with folders A and B, you want to quickly be able to open A?

**Comment by rameshkatare9** [comment]
Please see url: https://help.eclipse.org/2019-12/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-47.htm

Similar to this, this should be in VS code.
