### ISSUE TITLE
Linux: VSCode does not get updated via apt (Ubuntu)

### ISSUE THREAD

**Issue by trainto** [microsoft/vscode#105361]
- VSCode Version: 1.48.0
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Download .deb and install
2. apt update && apt upgrade

Does this issue occur when all extensions are disabled?: Yes

I installed VSCode via downloading .deb and It had no problem with updating until 1.48.0

/etc/apt/sources.list.d/vscode.list
`
deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
`

I also checked
> sudo apt-cache madison code

and 1.48.0 is there, but there isn't 1.48.1 which is the current latest version.

**Comment by gjsjohnmurray** [comment]
Is this #105316?

**Comment by trainto** [comment]
@gjsjohnmurray Yes, It seems that it can be merged into #105316 
I'll close this, and plus couple of hours ago my ubuntu 20.04 got updated 1.48.2.
Thanks.
