### ISSUE TITLE
PHP code format issue.

### ISSUE THREAD

**Issue by littlerun** [Microsoft/vscode#10531]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.Open a php file based on the PHP5.4 syntaxes, the source code as shown below:
![image](https://cloud.githubusercontent.com/assets/4374293/17654529/9858bdbc-62d6-11e6-8680-034a08317ff6.png)

2.Press Alt+Shift+F to format the source code,  I would get something like this:
![image](https://cloud.githubusercontent.com/assets/4374293/17654617/8e1fb656-62d7-11e6-9264-b579350bd6ab.png)

**Comment by jrieken** [comment]
@littlerun Looking at our sources,  I  don't see that VS Code ships with a php formatter. Please file this issue against the extension your are using.
