### ISSUE TITLE
Vscode suddenly closes when i type a letter.

### ISSUE THREAD

**Issue by bhanuprakash9980** [microsoft/vscode#105331]
- VSCode Version:1.48.1
- OS Version:Windows 10

Steps to Reproduce:

1.Start editing a file which sends an api json response with large data nearly 500MB

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Does this happen with our latest insiders https://code.visualstudio.com/insiders ?
