### ISSUE TITLE
VSCode Debug step by step breakpoint, debuggerworker  cpu 100%, this is caton.

### ISSUE THREAD

**Issue by genghongkai** [microsoft/vscode#105349]
![11](https://user-images.githubusercontent.com/15643017/91159876-4494be80-e6fb-11ea-8697-97e80e43fa91.png)

**Comment by genghongkai** [comment]
Hello, can you take a look at this problem ?

**Comment by connor4312** [comment]
Please collect a trace log using these instructions:

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by connor4312** [comment]
Sorry, didn't see this is react native, not js debugging. Please open an issue on https://github.com/microsoft/vscode-react-native
