### ISSUE TITLE
Esc is behaving differently in in Find functionality when editor has selection

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#10536]
<kbd>esc</kbd> is behaving differently in following scenarios

Scenario 1:
1. Select some text where there is at least one find match
2. <kbd>ctrl</kbd>+<kbd>f</kbd> to open find widget. Provide search string
3. <kbd>esc</kbd> to cancel
Notice that selection is cleared

Scenario 2:
1. Select some text where there is no find match
2. <kbd>ctrl</kbd>+<kbd>f</kbd> to open find widget. Provide search string
3. <kbd>esc</kbd> to cancel
Notice that selection is not cleared

See the attached videos:

![jul-28-2016 12-27-58](https://cloud.githubusercontent.com/assets/10746682/17209810/6731d720-54bf-11e6-9695-3830b25b2c61.gif)

![jul-28-2016 12-28-55](https://cloud.githubusercontent.com/assets/10746682/17209815/6c01076c-54bf-11e6-9766-1b9a054f81dc.gif)

**Comment by alexandrudima** [comment]
@sandy081 In the first gif, you press Escape twice: the first time it hides the find widget and the second time it clears the selection. 

In the second gif, you press Escape only once that hides the find widget. To cancel the selection please also press Escape twice.
