### ISSUE TITLE
Integrate Windows Terminal into VSCode

### ISSUE THREAD

**Issue by mcarthur-cpt** [microsoft/vscode#105350]
As Windows Terminal is the modern replacement for the old windows terminal emulator it would make sense to integrate Windows Terminal into VSCode. And not just into the Windows VSCode but for all platforms.

**Comment by costincaraivan** [comment]
Windows Terminal is a Windows app, you're basically suggesting that they port Windows Terminal to all the platform. And probably DirectX, too, while they're at it, I'm pretty sure Windows Terminal is hardware accelerated.

**Comment by Tyriar** [comment]
This would not work for many reasons, VS Code uses [xterm.js](https://github.com/xtermjs/xterm.js) which is an open source terminal frontend for the web platform which also features hardware acceleration (`"terminal.integrated.rendererType": "experimentalWebgl"`). VS Code also uses Windows Terminal's backend for hosting the processes on Windows only.
