### ISSUE TITLE
Failed to mark file for deletion - Update 1.48.2

### ISSUE THREAD

**Issue by cmdub** [microsoft/vscode#105380]
- VSCode Version: 1.48.1
- OS Version: Windows 10 Enterprise 1909 - Latest CU

Steps to Reproduce:

1. Attemp install of 1.48.2
2.

Does this issue occur when all extensions are disabled?: Yes
[vscode-inno-updater-1598411092.log](https://github.com/microsoft/vscode/files/5127369/vscode-inno-updater-1598411092.log)

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
