### ISSUE TITLE
Language server not working with notebook cells

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#105391]
- VSCode Version: 1.49.0-insider
- OS Version: Ubuntu 20.04

Related: https://github.com/Ikuyadeu/vscode-R/issues/396.

Steps to Reproduce:

1. Install vscode-R notebook visx from https://github.com/renkun-ken/vscode-R/actions/runs/211732805
2. Install [vscode-r-lsp](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r-lsp) and [languageserver](https://github.com/REditorSupport/languageserver)
3. Debug the vscode-R extension and open an `*.Rmd` file as a notebook.
4. The language server does not work with notebook code cells.

I have not seen any documentation (e.g. https://code.visualstudio.com/api/extension-guides/notebook) or example (e.g. https://github.com/microsoft/vscode-nodebook) yet talking about how existing language server/clients should be modified to work with notebook cells. It looks like [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) is made to support notebook but it is not open source.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
@renkun-ken please ask me anything about this ;-) We have this (preview) guide/intro: https://github.com/microsoft/notebook-extension-samples/blob/master/notebook-language-guide/notebook-language-guide.md. Our findings are that this needs involvement from language service authors but we are happy to help!

**Comment by renkun-ken** [comment]
@jrieken Thanks!

I made some [changes](https://github.com/REditorSupport/vscode-r-lsp/compare/notebook) to vscode-r-lsp and the language server now works nicely with notebook code cells!

But `executeCell` seems no longer works as `cell.document` got `undefined` at runtime. I'm not sure if there's significant api or runtime changes?

**Comment by jrieken** [comment]
> I made some changes to vscode-r-lsp and the language server now works nicely with notebook code cells!

Looking very promising... So, you create a new service per notebook-file since a notebook roughly corresponds to a project, right? 

> But executeCell seems no longer works as cell.document got undefined at runtime. Also, changing cell.outputs does not work either. I'm not sure if there's significant api or runtime changes?

Hm, that shouldn't happen and I cannot reproduce locally. Are you latest insiders and latest `vscode.proposed.d.ts`? Things are still changing quite a lot these days. With more steps I can also try to debug locally

**Comment by renkun-ken** [comment]
>Looking very promising... So, you create a new service per notebook-file since a notebook roughly corresponds to a project, right?

Yes, the R language service uses a multi-server approach to handle untitled documents, out-of-workspace files, and multi-root workspace. A notebook behaves like to a project with multiple documents which share the same language server workspace.

>Are you latest insiders and latest vscode.proposed.d.ts?

Yes, I'm using the latest `vscode.proposed.d.ts` and latest vscode insiders. `cell.document` simply got `undefined`. I could reproduce this on both Ubuntu 20.04 and macOS 10.15.6. Not sure if I'm missing something?

**Comment by jrieken** [comment]
> cell.document and cell.metadata simply got undefined at runtime.

Can you point me to some code or let me try this? I have done some refactorings in that area but `cell.document` being undefined should really not happen given that we hold a reference to the document from start and don't allow to change it anymore ([reference](https://github.com/microsoft/vscode/blob/470966b066f88e86629451b57b004b638816ccba/src/vs/workbench/api/common/extHostNotebook.ts#L118))

**Comment by renkun-ken** [comment]
https://github.com/Ikuyadeu/vscode-R/pull/394 is the R notebook implementation under development.

At https://github.com/Ikuyadeu/vscode-R/pull/394/files#diff-896fa9128d2e83307ffcf26741d257d2R66-R70, I got `cell.document = undefined` at runtime when I tried to evaluate a cell, which worked nicely previously but not with the latest version.

I could not get the text of the cell and nor could I set the output of the cell. It's very likely that I have messed up something here. It would be nice if you could clone the project and see if you could reproduce it.

**Comment by jrieken** [comment]
@renkun-ken we have changed how kernels are registered. That might be the problem here. Instead of having it exposed as `kernel` field it must now be explicitly registered. E.g like so https://github.com/microsoft/vscode-github-issue-notebooks/blob/de869b2d2525f28c1fb7083830fe0d78f2f79b68/src/extension/notebookProvider.ts#L154

**Comment by renkun-ken** [comment]
I tried the following but still no luck. I'm not sure how I could fill in the `viewType` field as the notebook document selector?

```typescript
public label = 'R Kernel';
  // public kernel = this;

  private kernelScript: string;
  private disposables: vscode.Disposable[] = [];
  private readonly notebooks = new Map<string, RNotebook>();

  private runIndex: number = 0;

  constructor(kernelScript: string) {
    this.kernelScript = kernelScript;
    this.disposables.push(
      vscode.notebook.registerNotebookKernelProvider({
        viewType: 'r'
      }, {
          provideKernels: () => {
          return [this];
        }
      }),
      vscode.notebook.onDidOpenNotebookDocument(document => {
        const docKey = document.uri.toString();
        if (!this.notebooks.has(docKey)) {
          const notebook = new RNotebook(this.kernelScript, document);
          notebook.restartKernel();
          this.notebooks.set(docKey, notebook);
        }
      }),
      vscode.notebook.onDidCloseNotebookDocument(document => {
        const docKey = document.uri.toString();
        const notebook = this.notebooks.get(docKey);
        if (notebook) {
          notebook.dispose();
          this.notebooks.delete(docKey);
        }
      }),
    );
  }
```

**Comment by jrieken** [comment]
Try `r-notebook` as `viewType` in the selector

**Comment by renkun-ken** [comment]
`r-notebook` makes it work! 😄  Thanks!

**Comment by renkun-ken** [comment]
Closing now.

Thanks for your timely answers! I'll file new issue if needed.

May I type @jrieken in the issues of vscode-R or vscode-r-lsp extensions repo regarding notebook questions? It's so efficient to get problem solved.

**Comment by jrieken** [comment]
> May I type @jrieken in the issues of vscode-R or vscode-r-lsp extensions repo regarding notebook questions? It's so efficient to get problem solved.

Yes, please do so! We are super keen on seeing what others do with native notebooks and we are very interested in feedback and issues that early adopters are facing. So, please let the feedback come, be it API or UX. 

I will also subscribe you to https://github.com/microsoft/vscode/issues/93265 on which we announce new and changed APIs.

**Comment by renkun-ken** [comment]
Thanks!
