### ISSUE TITLE
can't launch tests twice because build won't stop (regression from last month)

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#105323]
Issue Type: <b>Bug</b>

1) git clone https://github.com/microsoft/vscode-azurearmtools.git
2) cd vscode-azurearmtools
3) git checkout saw/bug-test
4) npm i
5) load vscode-azurearmtools in vscode
6) set debug config to "Launch Tests"
7) F5
8) build takes about 20s, then 6 tests run and pass
!) When tests host closes, you'll notice that vscode is still "Building..."
9) F5
!) nothing happens (should immediately launch tests the 2nd time)
10) if you repeat this with "Launch Extension" instead of "Launch Tests", this does not repro

VS Code version: Code - Insiders 1.49.0-insider (11dc5a81ba248cc2678888391f1b24dccabddaf8, 2020-08-17T17:11:16.078Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|--crash-reporter-id 28a909e2-0b30-47b4-bfa3-dcb1734aca95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
todo-tree|Gru|0.0.178
vscode-dotnet-runtime|ms-|0.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by connor4312** [comment]
I don't repro this on stable or insiders. But I also get no tests running

![](https://memes.peet.io/img/20-08-4bbefd5e-7645-4809-a297-78696d6ae9f2.png)

Are there additional setup steps needed?

**Comment by StephenWeatherford** [comment]
Corrected the branch name, should be "saw/bug-tests".  Were you able to git checkout saw/bug-tests?

Also fixed the launch.json, it should pick up 12 passing tests now.  With these instructions I repro'ed on a new machine.  Please try again, thanks!

**Comment by connor4312** [comment]
Thanks, I'm able to repro with your latest set of changes.

VS Code seems to be doing things right. It looks like running test triggers a file change. TS then tries to rebuild that, but never finishes doing so. I'm guessing your tests might cause new files to be generated in the workspace, maybe large ones that TS hangs up on.

Changing your tsconfig.json to remove the "exclude" and instead only "include" directories you're interested in fixes this for me:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "outDir": "out",
        "noLib": false,
        "sourceMap": true,
        "noUnusedLocals": true,
        "strict": true,
        "alwaysStrict": true,
        "typeRoots": [
            "./node_modules/@types",
            // This is needed because ts-node ignores files which are not
            // discoverable through dependencies (which means it won't find
            // *.d.ts files, even though tsc would). But doing it this way means
            // that you can't simply have loose .d.ts files under ./typings, they
            // must instead be structured as node modules with separate folders
            // and index.d.ts files
            "./typings"
        ]
    },
    "include": [
        "src",
        "test"
    ]
}
```

**Comment by StephenWeatherford** [comment]
THat solved it, thanks!
