### ISSUE TITLE
Initializing JS/TS language features taking too long

### ISSUE THREAD

**Issue by knguyen1794** [microsoft/vscode#105381]
Issue Type: <b>Bug</b>

"Initializing JS/TS language features" is taking forever to load inside a Dev Container.

1. Open a project in a dev container
2. Open a .js file
3. The JS/TS server is reloading forever.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

**Comment by mjbvz** [comment]
How large is your project and have you ensured it does not include unnecessary files?

**Comment by knguyen1794** [comment]
@mjbvz it's actually a medium-sized project and when I open it locally, it takes a couple of second to initialize the TS server. However, when I open in the dev container, it literally takes forever.

**Comment by mjbvz** [comment]
Forever as in it never ever completes? Does it complete on a smaller project?

Also do disk operations work normally inside the container or all they very slow?

**Comment by knguyen1794** [comment]
@mjbvz yup, it never completes, at least for half an hour now. I have not tried on a smaller project but essentially, this same project when not in dev container, it takes a couple of seconds.

Also do disk operations work normally inside the container or all they very slow? => how could I check this?

**Comment by martellaj** [comment]
I've also noticed this becoming an issue for my project (OWA). Eventually I get an error: "TypeScript language server exited with error. Error message is: Unexpected end of JSON input". Unsure if this is related or not.

**Comment by mjbvz** [comment]
@knguyen1794 Can you please try collecting the TS Server log so that we can see what is triggering the slowdown:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

If you can share that log file, it should help us see which files TypeScript is trying to process or which operation is slow

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
