### ISSUE TITLE
Allow grouping extension on user side. 

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#105342]
Issue Type: <b>Feature Request</b>

Why :
1. Extension packs are available but one need to create extension pack and publish it in order to create their own prefered grouping in order to use it (i assume)
2. enable extension for workspace is a good option, however if a new workspace is created then you need to enable disable all required extensions each time.

request: allow user to group extensions together on user side. group can be enabled/disabled. 
-user can add/remove extension from the group.
-a single extension can be part of few different groups

VS Code version: Code - Insiders 1.49.0-insider (8ba70d8bdc3a10e3143cc4a131f333263bc48eef, 2020-08-25T05:33:08.027Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/40239
