### ISSUE TITLE
Load 'tas-client' async

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#105343]
It looks like we added a new dependency to `tas-client` which adds substantial time to our startup:

![image](https://user-images.githubusercontent.com/900690/91155632-65412200-e6c3-11ea-92d3-8d40c1ad72ec.png)

This module should be loaded via `await import('tas-client')` only when used.

//cc @jrieken

**Comment by jrieken** [comment]
Yeah, this is a really bulky module since it doesn't seem to be bundled in any way. Ideally, this loaded async and bundled

<img width="377" alt="Screenshot 2020-08-25 at 11 09 05" src="https://user-images.githubusercontent.com/1794099/91155645-6a9e6c80-e6c3-11ea-9642-5bc297eb7594.png">

**Comment by bpasero** [comment]
On top of this discussion, we also need to think about wether this module should be supported in web and then it should be webpacked accordingly, similar to our UMD variants (`semver-umd`, ...).

**Comment by sbatten** [comment]
@bpasero I have published the umd variant https://www.npmjs.com/package/tas-client-umd (though i messed up the typings so it needs an update), it just needs adoption.

**Comment by bpasero** [comment]
@sbatten sounds good. Loading this dependency async would be good in any case, even if you pick up the UMD variant as we avoid having to load the contents right on startup if not needed.

**Comment by bpasero** [comment]
@sbatten PR is up: https://github.com/microsoft/vscode/pull/105400
