### ISSUE TITLE
overflowWidgetsDomNode and onDidBlurEditorWidget don't work together

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105346]
* open GH issue notebook 
* select F2 (rename) on a variable
* :bug: widget shows, widget hides

The underlying problem is that the rename widget is rooted under the overflowContent-node, e.g not within the editor node, and that causes the editor to loose widget focus as soon as the rename widget gets focus (and in return the rename widget closes because the editor has lost widget focus...)

**Comment by alexdima** [comment]
The adoption of `overflowWidgetsDomNode` was temporarily rolled back in the Notebook editors via 342899271ddf12f0f095bbab27ee3c98b6654b2a . Let's try to tackle this in September.

**Comment by joaomoreno** [comment]
Let's move this to cleanup month: October.

**Comment by joaomoreno** [comment]
Closing since the issue doesn't repro no more.
