### ISSUE TITLE
override the emmet html template

### ISSUE THREAD

**Issue by aram535** [microsoft/vscode#105360]
Would like to be able to change the default html template that is generated by emmet. 
! generates a basic doc, but it would be great if we could personalize this, and override it to add more tags such as link and script tags. 

existing:
"doc": "html[lang=${lang}]>(head>meta[charset=${charset}]+meta:vp+title{${1:Document}})+body",

my personalized one: 
"doc": "html[lang=${lang}]>(head>meta[charset=${charset}]+meta:vp+title{${1:Document}})+link:css+script:src+body",

**Comment by aeschli** [comment]
See https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets.

The snippet files allows you to add more tenplates, but also to replace existing ones (reload might be needed after making changes to the snippet file)

**Comment by aram535** [comment]
Thanks for this. Is there a trick to overriding an exiting emmet with another emmet? When I do it's no longer parsed as an emmet but regular text.

The body is the existing emmet for "doc", I'm simply overriding it but it is no longer expanding out.

```
"Extended html template": {
		"prefix": "doc",
		"body": [
			"html[lang=${lang}]>(head>meta[charset=${charset}]+meta:vp+title{${1:Document}})+body",
		],
		"description": "Better html template"
	}
```

**Comment by aeschli** [comment]
This looks like a regular user snippet.
Did you try the emmet snippets as described in the [link](https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets)? Here are the steps I tested this with
- in your workspace, create a folder `emmet`
- put inside a file called `snippets.json`
```
{
  "html": {
    "snippets": {
      "doc": "html[lang=${lang}]>(head>meta[charset=${charset}]+meta:vp+title{${1:Document}})+body"
    }
  }
}
```
- in the workspace settings (Command: `Preferences: Open workspace settings (JSON)`) add 
```
{
    "emmet.extensionsPath": "./emmet"
}
```
- reload the vscode window (Command: `Developer: Reload Window`)
- type `doc` in html file

**Comment by aram535** [comment]
Yes, I was trying to make it a global emmet replacement... The change you suggest seems to be a workspace specific change.
