### ISSUE TITLE
Pass Cache-Control: no-cache header when syncing via the Sync Now command

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#105366]
This is required as a last resort workaround an issue that may occur if a user manages to connect to 2 separate region instances in the backend since they leverage separate caches.

**Comment by sandy081** [comment]
To verify:

- Open Shared process developer tools using command `Developer: Toggle Shared  Process`
- Open network tab there
- From the VS Code window, run `Settings Sync: Sync Now` command from Settings Sync dropdown menu
- Verify that the manifest request has **"Cache-Control": "no-cache"** header
