### ISSUE TITLE
Cannot type until extension host is started

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#10535]

**Comment by alexandrudima** [comment]
We need to figure out where we can take a shortcut. My thinking is that https://github.com/Microsoft/vscode/blob/master/src/vs/platform/commands/common/commandService.ts#L23 could be the place

**Comment by jrieken** [comment]
if [this](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/commands/common/commandService.ts#L27) is positive we go run the command send the activation event afterwards/in parallel. Still, it does introduce a tiny semantic change
