### ISSUE TITLE
Pyaudio error

### ISSUE THREAD

**Issue by Rishab2006** [microsoft/vscode#105355]
Issue Type: <b>Performance Issue</b>

This is a serious issue regarding pyaudio library. I have tried several methods to install pyaudio but it always shows error. I am not able to fix this. Help required urgently. Hope you will look into this issue.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    49	  7836	code main
    0	    36	  1260	   shared-process
    0	    15	  2124	   utility
    0	   157	  3760	   window (James.py - Visual Studio Code)
    0	    33	  5000	     searchService
    0	     1	  6964	     console-window-host (Windows internal process)
    0	    61	  7032	     extensionHost
    0	    38	  1304	       C:\Users\risha\AppData\Local\Microsoft\WindowsApps\python.exe c:\Users\risha\.vscode\extensions\ms-python.python-2020.8.103604\pythonFiles\pyvsc-run-isolated.py c:\Users\risha\.vscode\extensions\ms-python.python-2020.8.103604\pythonFiles\completion.py
    0	     5	  6856	         console-window-host (Windows internal process)
    0	    29	 10820	         C:\Users\risha\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe c:\Users\risha\.vscode\extensions\ms-python.python-2020.8.103604\pythonFiles\lib\python\jedi\inference\compiled\subprocess\__main__.py c:\Users\risha\.vscode\extensions\ms-python.python-2020.8.103604\pythonFiles\lib\python 3.8.5
    0	    11	 12428	           console-window-host (Windows internal process)
    0	    12	 15484	         C:\Users\risha\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe c:\Users\risha\.vscode\extensions\ms-python.python-2020.8.103604\pythonFiles\lib\python\jedi\inference\compiled\subprocess\__main__.py c:\Users\risha\.vscode\extensions\ms-python.python-2020.8.103604\pythonFiles\lib\python 3.8.5
    0	     5	 12600	           console-window-host (Windows internal process)
    0	     6	  9124	       "C:\Microsoft VS Code\Code.exe" "c:\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=7032
    0	    11	 11060	       "C:\Microsoft VS Code\Code.exe" "c:\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=7032
    0	     2	  7884	     console-window-host (Windows internal process)
    0	    34	 10308	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     4	 12684	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     3	  8356	   electron-crash-reporter
    1	   185	 11900	   gpu-process
    0	    58	 15932	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.8.103604
python|tht|0.2.3

</details>

**Comment by Rishab2006** [comment]
can you tell me the extension which I should download?

**Comment by usernamehw** [comment]
If it's related to python extension, then file an issue against python extension https://github.com/Microsoft/vscode-python/issues

Otherwise, create a quesion / search for similar problem at https://stackoverflow.com/search?tab=votes&q=[python]+[pyaudio]+error
