### ISSUE TITLE
Theme color customization > Panel colors

### ISSUE THREAD

**Issue by hiredtocode** [microsoft/vscode#105352]
- VSCode Version: 1.49.0-insider 
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open your theme color edit.json file
2. Add "panel.background": (color you want) I've set my color to red to take a screen shot.
![1](https://user-images.githubusercontent.com/68050282/91174126-ceec1b00-e719-11ea-932a-a19ad3545492.JPG)
![2](https://user-images.githubusercontent.com/68050282/91174130-cf84b180-e719-11ea-997b-b6751ecc0494.jpg)
![3](https://user-images.githubusercontent.com/68050282/91174133-d01d4800-e719-11ea-9cf5-7e4726ae6e10.jpg)
![4](https://user-images.githubusercontent.com/68050282/91174136-d0b5de80-e719-11ea-884b-ed5556814106.jpg)
![5](https://user-images.githubusercontent.com/68050282/91174137-d0b5de80-e719-11ea-87d0-b0a28c21b667.jpg)

As I understand "panel.background" should set the background section of the panel (the black part in the first screenshot. NOTE: this section is black because I've explicitly set the color to black by setting the "terminal.background" to black ) and the "panelSectionHeader.background" should set the background of the panel header which is the top bar of the panel section.

Also, I noticed that not only "panelSectionHeader.background" but "panelSectionHeader.foreground", "panelSectionHeader.border", "panel.dropBackground", "panel.dropBorder" doesn't work either. 

One more thing to point out (This is not a bug but somehow related)
In the [panel color section of the vscode website](https://code.visualstudio.com/api/references/theme-color#panel-colors)  section there are multiple places stating "Panels are shown below the editor area and contain views like output and integrated terminal." 
Not sure if this was done on purpose but I think it should be cleaned up since it's already described under the header tag.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
I can reproduce that
```
  "workbench.colorCustomizations": {
    "panelSectionHeader.background": "#ff0000"
  }
```
has no effect. Also in the code it seems that `panelSectionHeader.background` is not used anymore

**Comment by bpasero** [comment]
These colors seem to have come in via https://github.com/microsoft/vscode/commit/bd99f9033b91c0c7bf2b75a0a1ff418e8905e621 from @sbatten 

//cc @isidorn

**Comment by sbatten** [comment]
Panel Section Header is Panel equivalent of Side Bar Section Header. It's the view headers:

![image](https://user-images.githubusercontent.com/6561887/91338131-4dcc6c80-e789-11ea-86fe-bb3c0c7321c2.png)

**Comment by sbatten** [comment]
I updated the text here to make it clearer that panel sections are views within the panel. this nomenclature mimics the side bar which predates the new theme keys. Everything is working as expected.
