### ISSUE TITLE
Use standard scrolling behaviour of the OS

### ISSUE THREAD

**Issue by autr** [microsoft/vscode#105357]
The scrolling speed and acceleration / deceleration on macOS is very disconcerting, as it's different to the rest of the operating system.

It's like landing on a webpage that hijacks the scroll wheel.

I'm curious as to why this would be the case - that normal scroll pane behaviour isn't used - if the core is Blink / Chromium?

**Comment by alexdima** [comment]
@autr 
The VS Code editor also ships independently as the Monaco Editor and can run in a web browser. Can you please try out the editor at https://microsoft.github.io/monaco-editor/ in Chrome and in Safari and scroll with the touchpad? On my machine, in both programs the editor scrolls "normally".

**Comment by autr** [comment]
Hi @alexdima 

Had a look at Monaco Editor and all is scrolling is fine 👍

In VSCode its slightly irregular in the tweening, so could be lag rather than a different speed / acceleration profile? A quick poke around the scroll controller and I see requestAnimationFrame referenced - so hazarding a guess the position is updated once texture is drawn? 

I'm on v1.48.1 with a 2015 MBP Pro w. integrated graphics set to...

<img width="348" alt="Screenshot 2020-08-25 at 20 40 20" src="https://user-images.githubusercontent.com/56603487/91214340-39e62380-e713-11ea-9fde-3d4b88fffdd5.png">

**Comment by autr** [comment]
Yep, confirming it’s rendering: the Monaco Editor frame is quite small so very responsive, and likewise for VSCode changing the size of the window from small to fullscreen affects the lagginess (where fullscreen is 3360px wide on Iris Intel graphics)

**Comment by alexdima** [comment]
@autr Could you please try to profile the renderer process and attach the profile here?
