### ISSUE TITLE
NORMAL cant type text on terminal

### ISSUE THREAD

**Issue by davidotu** [microsoft/vscode#105303]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

NORMAL cant type text on terminal

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:09:41.484Z)
OS version: Darwin x64 14.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 5, 5|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    86	  1550	code main
    2	    29	  1552	   gpu-process
    0	    16	  1555	   utility
    4	    74	  1573	   shared-process
    1	     0	  1755	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   188	  1681	   window (bloggers.html — boole1)
    0	   123	  1687	     extensionHost
    0	    57	  1727	       /Users/davidotu/Desktop/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Users/davidotu/Desktop/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=1687
    0	    25	  1731	       /Users/davidotu/Desktop/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Users/davidotu/Desktop/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1687
    0	    25	  1688	     watcherService
    0	    29	  1691	     searchService
    0	     0	  1695	     /bin/bash -l
    2	    74	  1753	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (bloggers.html — boole1)
|    Folder (boole1): 11 files
|      File types: DS_Store(3) html(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
code-gnu-global|aus|0.2.2
vscode-django|bat|0.20.0
c-compiler|bra|0.0.4
python-preview|don|0.0.4
jupyter|don|1.1.5
python-extension-pack|don|1.6.0
mithril-emmet|Fal|0.7.5
code-runner|for|0.11.0
pythonsnippets|frh|1.0.2
live-html-previewer|hdg|0.3.0
coffee-emmet-mithril|jhe|0.1.2
vscode-peacock|joh|3.8.0
chat|kar|0.35.0
vsc-python-indent|Kev|1.10.1
MagicPython|mag|1.1.0
python-path|mge|0.0.11
python|ms-|2020.8.103604
vsliveshare|ms-|1.0.2666
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
elmmet|nec|1.0.1
live-server-preview|neg|0.1.4
open-html-in-browser|pea|2.1.3
java|red|0.65.0
LiveServer|rit|5.6.1
preview-vscode|sea|2.1.0
emmylua|tan|0.3.49
python|tht|0.2.3
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.12.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.1
vscode-maven|vsc|0.24.1
vim|vsc|1.16.0
jinja|who|0.0.8
emmet-live|yse|1.0.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
