### ISSUE TITLE
Typescript server dies after 5 tries

### ISSUE THREAD

**Issue by meisterveda** [microsoft/vscode#105318]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

just opened the project via command line with "code ." after that went and opened any of the .ts files on my project and the typescript would fail to load.

<details>
<summary>Log content</summary>

> Info 0    [18:35:13.577] Starting TS Server
> Info 1    [18:35:13.578] Version: 3.9.7
> Info 2    [18:35:13.578] Arguments: /snap/code/41/usr/share/code/code /snap/code/41/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js --syntaxOnly --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/4dde705799c167ae2e64/tscancellation-e21e13cdd3215082b8f6.tmp* --logVerbosity verbose --logFile /home/gcabezal/.config/Code/logs/20200824T183508/exthost1/vscode.typescript-language-features/tsserver-log-2MqeT3/tsserver.log --globalPlugins typescript-vscode-sh-plugin,typescript-tslint-plugin,@vsintellicode/typescript-intellicode-plugin --pluginProbeLocations /snap/code/41/usr/share/code/resources/app/extensions/typescript-language-features,/home/gcabezal/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3,/home/gcabezal/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.10 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
> Info 3    [18:35:13.578] Platform: linux NodeVersion: 12 CaseSensitive: true
> Info 4    [18:35:13.584] request:
>     {"seq":0,"type":"request","command":"configure","arguments":{"hostInfo":"vscode","preferences":{"providePrefixAndSuffixTextForRename":true,"allowRenameOfImportPath":true,"includePackageJsonAutoImports":"auto"},"watchOptions":{}}}
> Info 5    [18:35:13.584] Host information vscode
> Info 6    [18:35:13.584] Host watch options changed to undefined, it will be take effect for next watches.
> Info 7    [18:35:13.585] response:
>     {"seq":0,"type":"response","command":"configure","request_seq":0,"success":true}
> Perf 8    [18:35:13.586] 0::configure: async elapsed time (in milliseconds) 2.6533
> Info 9    [18:35:13.587] request:
>     {"seq":1,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"/home/gcabezal/projects/agromanager/libs/ui-kits/footer/src/lib/ui-kits-footer.module.ts","fileContent":"import { NgModule } from '@angular/core';\nimport { CommonModule } from '@angular/common';\nimport { FooterComponent } from './footer/footer.component';\n\n@NgModule({\n  imports: [CommonModule],\n  declarations: [FooterComponent],\n  exports: [FooterComponent],\n})\nexport class UiKitsFooterModule {}\n","projectRootPath":"/home/gcabezal/projects/agromanager","scriptKindName":"TS"}]}}
> Info 10   [18:35:13.594] Loading global plugin typescript-vscode-sh-plugin
> Info 11   [18:35:13.594] Enabling plugin typescript-vscode-sh-plugin from candidate paths: /snap/code/41/usr/share/code/resources/app/extensions/typescript-language-features,/home/gcabezal/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3,/home/gcabezal/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.10,/snap/code/41/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..
> Info 12   [18:35:13.594] Loading typescript-vscode-sh-plugin from /snap/code/41/usr/share/code/resources/app/extensions/typescript-language-features (resolved to /snap/code/41/usr/share/code/resources/app/extensions/typescript-language-features/node_modules)
> Info 13   [18:35:13.613] typescript-vscode-sh-plugin initialized. Intercepting getEncodedSemanticClassifications and getEncodedSyntacticClassifications.
> Info 14   [18:35:13.613] Plugin validation succeded
> Info 15   [18:35:13.613] Loading global plugin typescript-tslint-plugin
> Info 16   [18:35:13.613] Enabling plugin typescript-tslint-plugin from candidate paths: /snap/code/41/usr/share/code/resources/app/extensions/typescript-language-features,/home/gcabezal/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3,/home/gcabezal/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.10,/snap/code/41/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..
> Info 17   [18:35:13.613] Loading typescript-tslint-plugin from /snap/code/41/usr/share/code/resources/app/extensions/typescript-language-features (resolved to /snap/code/41/usr/share/code/resources/app/extensions/typescript-language-features/node_modules)
> Info 18   [18:35:13.653] Loading typescript-tslint-plugin from /home/gcabezal/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3 (resolved to /home/gcabezal/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3/node_modules)
> Info 19   [18:35:13.710] [typescript-tslint-plugin] "Create"
> Info 20   [18:35:13.710] [typescript-tslint-plugin] "loaded"
> Info 21   [18:35:13.711] Plugin validation succeded
> Info 22   [18:35:13.711] Loading global plugin @vsintellicode/typescript-intellicode-plugin
> Info 23   [18:35:13.711] Enabling plugin @vsintellicode/typescript-intellicode-plugin from candidate paths: /snap/code/41/usr/share/code/resources/app/extensions/typescript-language-features,/home/gcabezal/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3,/home/gcabezal/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.10,/snap/code/41/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..
> Info 24   [18:35:13.711] Loading @vsintellicode/typescript-intellicode-plugin from /snap/code/41/usr/share/code/resources/app/extensions/typescript-language-features (resolved to /snap/code/41/usr/share/code/resources/app/extensions/typescript-language-features/node_modules)
> Info 25   [18:35:13.715] Loading @vsintellicode/typescript-intellicode-plugin from /home/gcabezal/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3 (resolved to /home/gcabezal/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3/node_modules)
> Info 26   [18:35:13.717] Loading @vsintellicode/typescript-intellicode-plugin from /home/gcabezal/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.10 (resolved to /home/gcabezal/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.10/node_modules)
> Info 27   [18:35:13.775] IntelliCode plugin: starting configuration: {"name":"@vsintellicode/typescript-intellicode-plugin","global":true}
> Info 28   [18:35:13.776] Plugin validation succeded
> Info 29   [18:35:13.777] Starting updateGraphWorker: Project: /dev/null/inferredProject1*
> Info 30   [18:35:13.777] Finishing updateGraphWorker: Project: /dev/null/inferredProject1* Version: 1 structureChanged: undefined Elapsed: 0ms
> Info 31   [18:35:13.778] Project '/dev/null/inferredProject1*' (Inferred)
> Info 32   [18:35:13.778] 	Files (0) NoProgram
> 
> Info 33   [18:35:13.778] -----------------------------------------------
> Info 34   [18:35:13.778] Project '/dev/null/inferredProject1*' (Inferred)
> Info 34   [18:35:13.778] 	Files (0) NoProgram
> 
> Info 34   [18:35:13.778] -----------------------------------------------
> Info 34   [18:35:13.778] Open files: 
> Info 34   [18:35:13.779] 	FileName: /home/gcabezal/projects/agromanager/libs/ui-kits/footer/src/lib/ui-kits-footer.module.ts ProjectRootPath: /home/gcabezal/projects/agromanager
> Info 34   [18:35:13.779] 		Projects: /dev/null/inferredProject1*
> Perf 34   [18:35:13.779] 1::updateOpen: elapsed time (in milliseconds) 192.1493
> Info 35   [18:35:13.779] response:
>     {"seq":0,"type":"response","command":"updateOpen","request_seq":1,"success":true,"body":true}
> Info 36   [18:35:13.798] request:
>     {"seq":2,"type":"request","command":"configurePlugin","arguments":{"pluginName":"typescript-tslint-plugin","configuration":{}}}
> Info 37   [18:35:13.798] response:
>     {"seq":0,"type":"response","command":"configurePlugin","request_seq":2,"success":true}
> Perf 38   [18:35:13.798] 2::configurePlugin: async elapsed time (in milliseconds) 0.5216
> Info 39   [18:35:13.804] request:
>     {"seq":3,"type":"request","command":"navtree","arguments":{"file":"/home/gcabezal/projects/agromanager/libs/ui-kits/footer/src/lib/ui-kits-footer.module.ts"}}
> Perf 40   [18:35:13.820] 3::navtree: elapsed time (in milliseconds) 15.9623
> Info 41   [18:35:13.820] response:
>     {"seq":0,"type":"response","command":"navtree","request_seq":3,"success":true,"body":{"text":"\"ui-kits-footer.module\"","kind":"module","kindModifiers":"","spans":[{"start":{"line":1,"offset":1},"end":{"line":10,"offset":36}}],"childItems":[{"text":"CommonModule","kind":"alias","kindModifiers":"","spans":[{"start":{"line":2,"offset":10},"end":{"line":2,"offset":22}}],"nameSpan":{"start":{"line":2,"offset":10},"end":{"line":2,"offset":22}}},{"text":"FooterComponent","kind":"alias","kindModifiers":"","spans":[{"start":{"line":3,"offset":10},"end":{"line":3,"offset":25}}],"nameSpan":{"start":{"line":3,"offset":10},"end":{"line":3,"offset":25}}},{"text":"NgModule","kind":"alias","kindModifiers":"","spans":[{"start":{"line":1,"offset":10},"end":{"line":1,"offset":18}}],"nameSpan":{"start":{"line":1,"offset":10},"end":{"line":1,"offset":18}}},{"text":"UiKitsFooterModule","kind":"class","kindModifiers":"export","spans":[{"start":{"line":5,"offset":1},"end":{"line":10,"offset":35}}],"nameSpan":{"start":{"line":10,"offset":14},"end":{"line":10,"offset":32}}}]}}
> Info 42   [18:35:13.857] request:
>     {"seq":5,"type":"request","command":"navtree","arguments":{"file":"/home/gcabezal/projects/agromanager/libs/ui-kits/footer/src/lib/ui-kits-footer.module.ts"}}
> Perf 43   [18:35:13.858] 5::navtree: elapsed time (in milliseconds) 1.1323
> Info 44   [18:35:13.858] response:
>     {"seq":0,"type":"response","command":"navtree","request_seq":5,"success":true,"body":{"text":"\"ui-kits-footer.module\"","kind":"module","kindModifiers":"","spans":[{"start":{"line":1,"offset":1},"end":{"line":10,"offset":36}}],"childItems":[{"text":"CommonModule","kind":"alias","kindModifiers":"","spans":[{"start":{"line":2,"offset":10},"end":{"line":2,"offset":22}}],"nameSpan":{"start":{"line":2,"offset":10},"end":{"line":2,"offset":22}}},{"text":"FooterComponent","kind":"alias","kindModifiers":"","spans":[{"start":{"line":3,"offset":10},"end":{"line":3,"offset":25}}],"nameSpan":{"start":{"line":3,"offset":10},"end":{"line":3,"offset":25}}},{"text":"NgModule","kind":"alias","kindModifiers":"","spans":[{"start":{"line":1,"offset":10},"end":{"line":1,"offset":18}}],"nameSpan":{"start":{"line":1,"offset":10},"end":{"line":1,"offset":18}}},{"text":"UiKitsFooterModule","kind":"class","kindModifiers":"export","spans":[{"start":{"line":5,"offset":1},"end":{"line":10,"offset":35}}],"nameSpan":{"start":{"line":10,"offset":14},"end":{"line":10,"offset":32}}}]}}
> Info 45   [18:35:13.879] request:
>     {"seq":10,"type":"request","command":"configure","arguments":{"file":"/home/gcabezal/projects/agromanager/libs/ui-kits/footer/src/lib/ui-kits-footer.module.ts","formatOptions":{"tabSize":2,"indentSize":2,"convertTabsToSpaces":true,"newLineCharacter":"\n","insertSpaceAfterCommaDelimiter":true,"insertSpaceAfterConstructor":false,"insertSpaceAfterSemicolonInForStatements":true,"insertSpaceBeforeAndAfterBinaryOperators":true,"insertSpaceAfterKeywordsInControlFlowStatements":true,"insertSpaceAfterFunctionKeywordForAnonymousFunctions":true,"insertSpaceBeforeFunctionParenthesis":false,"insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis":false,"insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets":false,"insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces":true,"insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces":false,"insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces":false,"insertSpaceAfterTypeAssertion":false,"placeOpenBraceOnNewLineForFunctions":false,"placeOpenBraceOnNewLineForControlBlocks":false,"semicolons":"ignore"},"preferences":{"quotePreference":"auto","importModuleSpecifierEnding":"auto","allowTextChangesInNewFiles":true,"providePrefixAndSuffixTextForRename":true,"allowRenameOfImportPath":true,"includeAutomaticOptionalChainCompletions":true,"provideRefactorNotApplicableReason":true}}}
> Info 46   [18:35:13.880] Host configuration update for file /home/gcabezal/projects/agromanager/libs/ui-kits/footer/src/lib/ui-kits-footer.module.ts
> Info 47   [18:35:13.880] response:
>     {"seq":0,"type":"response","command":"configure","request_seq":10,"success":true}
> Perf 48   [18:35:13.880] 10::configure: async elapsed time (in milliseconds) 0.8440
> Info 49   [18:35:14.54] request:
>     {"seq":11,"type":"request","command":"getOutliningSpans","arguments":{"file":"/home/gcabezal/projects/agromanager/libs/ui-kits/footer/src/lib/ui-kits-footer.module.ts"}}
> Perf 50   [18:35:14.58] 11::getOutliningSpans: elapsed time (in milliseconds) 3.9439
> Info 51   [18:35:14.58] response:
>     {"seq":0,"type":"response","command":"getOutliningSpans","request_seq":11,"success":true,"body":[{"textSpan":{"start":{"line":1,"offset":1},"end":{"line":3,"offset":61}},"hintSpan":{"start":{"line":1,"offset":1},"end":{"line":3,"offset":61}},"bannerText":"...","autoCollapse":false,"kind":"imports"},{"textSpan":{"start":{"line":5,"offset":11},"end":{"line":9,"offset":2}},"hintSpan":{"start":{"line":5,"offset":11},"end":{"line":9,"offset":2}},"bannerText":"...","autoCollapse":false,"kind":"code"},{"textSpan":{"start":{"line":6,"offset":11},"end":{"line":6,"offset":26}},"hintSpan":{"start":{"line":6,"offset":12},"end":{"line":6,"offset":26}},"bannerText":"...","autoCollapse":false,"kind":"code"},{"textSpan":{"start":{"line":7,"offset":16},"end":{"line":7,"offset":34}},"hintSpan":{"start":{"line":7,"offset":17},"end":{"line":7,"offset":34}},"bannerText":"...","autoCollapse":false,"kind":"code"},{"textSpan":{"start":{"line":8,"offset":11},"end":{"line":8,"offset":29}},"hintSpan":{"start":{"line":8,"offset":12},"end":{"line":8,"offset":29}},"bannerText":"...","autoCollapse":false,"kind":"code"},{"textSpan":{"start":{"line":10,"offset":32},"end":{"line":10,"offset":35}},"hintSpan":{"start":{"line":5,"offset":1},"end":{"line":10,"offset":35}},"bannerText":"...","autoCollapse":false,"kind":"code"}]}
> Info 52   [18:35:15.919] request:
>     {"seq":12,"type":"request","command":"configurePlugin","arguments":{"pluginName":"@vsintellicode/typescript-intellicode-plugin","configuration":{"modelPath":"/home/gcabezal/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.10/cache/1A3F919CD5B7725108B03C349630A1C82B03_0F0BA3C08C954A17AD992F382AE21E98"}}}
> Info 53   [18:35:15.919] response:
>     {"seq":0,"type":"response","command":"configurePlugin","request_seq":12,"success":true}
> Perf 54   [18:35:15.919] 12::configurePlugin: async elapsed time (in milliseconds) 0.4885
> Info 55   [18:35:19.528] request:
>     {"seq":13,"type":"request","command":"getOutliningSpans","arguments":{"file":"/home/gcabezal/projects/agromanager/libs/ui-kits/footer/src/lib/ui-kits-footer.module.ts"}}
> Perf 56   [18:35:19.529] 13::getOutliningSpans: elapsed time (in milliseconds) 1.2011
> Info 57   [18:35:19.529] response:
>     {"seq":0,"type":"response","command":"getOutliningSpans","request_seq":13,"success":true,"body":[{"textSpan":{"start":{"line":1,"offset":1},"end":{"line":3,"offset":61}},"hintSpan":{"start":{"line":1,"offset":1},"end":{"line":3,"offset":61}},"bannerText":"...","autoCollapse":false,"kind":"imports"},{"textSpan":{"start":{"line":5,"offset":11},"end":{"line":9,"offset":2}},"hintSpan":{"start":{"line":5,"offset":11},"end":{"line":9,"offset":2}},"bannerText":"...","autoCollapse":false,"kind":"code"},{"textSpan":{"start":{"line":6,"offset":11},"end":{"line":6,"offset":26}},"hintSpan":{"start":{"line":6,"offset":12},"end":{"line":6,"offset":26}},"bannerText":"...","autoCollapse":false,"kind":"code"},{"textSpan":{"start":{"line":7,"offset":16},"end":{"line":7,"offset":34}},"hintSpan":{"start":{"line":7,"offset":17},"end":{"line":7,"offset":34}},"bannerText":"...","autoCollapse":false,"kind":"code"},{"textSpan":{"start":{"line":8,"offset":11},"end":{"line":8,"offset":29}},"hintSpan":{"start":{"line":8,"offset":12},"end":{"line":8,"offset":29}},"bannerText":"...","autoCollapse":false,"kind":"code"},{"textSpan":{"start":{"line":10,"offset":32},"end":{"line":10,"offset":35}},"hintSpan":{"start":{"line":5,"offset":1},"end":{"line":10,"offset":35}},"bannerText":"...","autoCollapse":false,"kind":"code"}]}

</details>

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:11:59.963Z)
OS version: Linux x64 5.4.0-42-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2711)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 2, 1|
|Memory (System)|7.68GB (1.92GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
better-toml|bun|0.3.2
path-intellisense|chr|2.2.1
dart-code|Dar|3.13.2
flutter|Dar|3.13.2
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.1.3
auto-close-tag|for|0.5.8
go|gol|0.16.1
beautify|Hoo|1.5.0
Angular2|joh|9.1.2
vscode-docker|ms-|1.5.0
csharp|ms-|1.23.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.8.103604
cpptools|ms-|0.29.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2666
debugger-for-chrome|msj|4.12.10
angular-console|nrw|13.0.0
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.10.0
vsfire|tob|1.4.1
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|10.2.0
eno|Wsc|2.3.10

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
