### ISSUE TITLE
Horizontal scroll bar, Outline

### ISSUE THREAD

**Issue by Gizmodo** [microsoft/vscode#105317]
Issue Type: <b>Feature Request</b>

Please add horizontal scroll inside OUTLINE window

VS Code version: Code - Insiders 1.49.0-insider (f57a418b019926b38d2e6949265c33002a8f6f6b, 2020-08-24T08:17:33.759Z)
OS version: Darwin x64 19.6.0

**Comment by Gizmodo** [comment]
nothing like this

**Comment by jrieken** [comment]
Actually, that's already supported as a general option: `workbench.list.horizontalScrolling: true`
