### ISSUE TITLE
Redesigned Windows File Explorer

### ISSUE THREAD

**Issue by mcarthur-cpt** [microsoft/vscode#105367]
While a lot of the UI's present in Windows are being redesigned the File Explorer has basically stayed the same(more or less). Would a WinUI look better or a Fluent based one.

![WinUI File Explorer](https://user-images.githubusercontent.com/69404152/91218217-04443900-e719-11ea-9f0e-d367790f2198.png)

**Comment by RMacfarlane** [comment]
Hi @mcarthur-cpt, this repo is meant for issues and features requests for Visual Studio Code.

**Comment by mcarthur-cpt** [comment]
Apologies. I'm so tired I though this was the WinUI repo.
