### ISSUE TITLE
cut code replaced by empty copy command

### ISSUE THREAD

**Issue by silly-panda** [Microsoft/vscode#10533]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:
1. select some code
2. press ctrl+x
3. select a place to paste the code but accidentally press ctrl-c.
4. press ctrl+v

Upon pressing ctrl+v nothing is pasted as the ctrl+c has caused the value to be overwritten with nothing so nothing is pasted. Now I have to press ctrl+z a few times to get my old code back and do the same process to be sure not to accidently press ctrl+c again. Precious seconds lost, so sad.

**Comment by alexandrudima** [comment]
This is happening because of a feature we have where if you do `ctrl+c` or `ctrl+x` even without a selection we take the line under the cursor and put that in the clipboard. We need to add a setting to control this behaviour

**Comment by alexandrudima** [comment]
Since a long time there is the option `editor.emptySelectionClipboard` that can be set to false to control this.
