### ISSUE TITLE
SCM: Have repository switcher in status bar

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#105476]
for multi-workspace or one workspace having multi-git-repos, that is very confuse each time when want to qucikly switch branch.
1. there is no info show which repo I am operating.
2. can‘t not select specific repo.
![image](https://user-images.githubusercontent.com/1876302/91407949-a24d1600-e875-11ea-9ba6-ac7d4cbde1d1.png)

at least, please show me the repo name of the repo which I am operating, PLEASE
secondly, provide selection for user to select a repo,not the default or activited file.

**Comment by SneakyFish5** [comment]
If https://github.com/microsoft/vscode/pull/104561 is merged, I think it should fix at least part of your issue correct?

**Comment by heartacker** [comment]
> If #104561 is merged, I think it should fix at least part of your issue correct?

maybe,  it will be better to show repo name in multi-workspace and hide it in signal workspace.
