### ISSUE TITLE
All breakpoints deleted on bad breakpoint deletion

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#105445]
Issue Type: <b>Bug</b>

Unfortunately I only have the information to reproduce half of this issue.

I found a breakpoint in my breakpoints tab that was assigned to a line that didn't exist in a file because the total amount of lines in that file was less than the line number that the problem breakpoint was assigned to. I don't know how the breakpoint became assigned to a non existent line. 

I disabled and re-enabled the bad breakpoint in the breakpoints tab, then I deleted it, which caused all of my other breakpoints to become deleted. 

Could some kind of safety check be implemented to prevent all breakpoints from being deleted in this case? Thanks!

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
Thanks for filling this issue. I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by ariffjeff** [comment]
I don't think I'm going to be able to test it anymore at all as I don't know how to get a breakpoint to show up incorrectly on a nonexistent line. :( I guess this is just one of those rare enough things that can't be fixed.

**Comment by isidorn** [comment]
Let's keep it open for a bit more, and if you hit it again please let us know. Thanks

**Comment by ariffjeff** [comment]
Will do.

**Comment by isidorn** [comment]
Closing this for now, and we can reopen if you see it again
