### ISSUE TITLE
Windows vscode doesn't change caps letters on rename feature.

### ISSUE THREAD

**Issue by PalantirMHM** [microsoft/vscode#105423]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Rename a class that is already imported by other files
2. The file is renamed correctly in lower case, but in the file where the class is used the path is renamed with upper case, building a typescript project in windows works, but building in the pipeline gitlabs cause ts2307 error, file not found.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
It sounds like you are on a case-insensitive file system (this would be the case under windows). 

To make sure your project also works on case-sensitive machines, try setting `"forceConsistentCasingInFileNames": true` in your jsconfig or tsconfig. You can read more information about the compiler options [here](https://www.typescriptlang.org/docs/handbook/compiler-options.html)
