### ISSUE TITLE
prevent jumping to line when find text in file

### ISSUE THREAD

**Issue by maisen20** [microsoft/vscode#105468]
Is it possible to change the behavior when searching in a file, so that the editor does not jump to the first found text when insert/paste text in the input field?

**Comment by yume-chan** [comment]
`"editor.find.cursorMoveOnType": false` ?

**Comment by maisen20** [comment]
There's no such setting when i go to Preferences > Settings.

**Comment by rebornix** [comment]
It's available in Insiders and will ship with next Stable.
