### ISSUE TITLE
Error terminal

### ISSUE THREAD

**Issue by Yunittt** [microsoft/vscode#105453]
Issue Type: <b>Bug</b>

error The terminal process C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe terminated with exit code: 4294901760.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N2808  @ 1.58GHz (2 x 1583)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
See suggestion in https://github.com/microsoft/vscode/issues/101697#issuecomment-654874715

**Comment by Tyriar** [comment]
Please see https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch to help diagnose.
