### ISSUE TITLE
Live Share Terminal

### ISSUE THREAD

**Issue by casonadams** [microsoft/vscode#105467]
Issue Type: <b>Bug</b>

Live Share terminal on shared connections has a very small viewport after closeing and reopening the host terminal.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.7.16-200.fc32.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 2557)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|15.60GB (0.25GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vsliveshare|ms-|1.0.2708
rust|rus|0.7.8
vim|vsc|1.16.0

</details>

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/55718, https://github.com/microsoft/vscode/issues/79246
