### ISSUE TITLE
Remove Context Menus On Uninstall/Reinstall

### ISSUE THREAD

**Issue by Json2CSharp** [microsoft/vscode#105435]
- VSCode Version:
- OS Version:

Steps to Reproduce:
1 - When uninstall the application -> Should remove "Open With Code" context menu
2 - When installing the application -> Should remove any regedits from the registry and set the context menus again

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
I cannot reproduce this issue. When I uninstall, the context menu action is gone. Can you reproduce this on another machine?

**Comment by Json2CSharp** [comment]
I resolved this by fixing the regedit exe paths, im not sure how i got to this point but ill close this ticket thank you very much for your help
