### ISSUE TITLE
visual studio codespaces - all ipynb files open as blank

### ISSUE THREAD

**Issue by AnkitJain09** [microsoft/vscode#105420]
While i am trying learn using visual studio codespaces online features, i am not able to open ipynb post python extensions loadinig.

all files open as blank.

![image](https://user-images.githubusercontent.com/22028657/91310349-65c6df00-e7cf-11ea-8b66-826386aed7d5.png)

**Comment by AnkitJain09** [comment]
also i see this error : 

![image](https://user-images.githubusercontent.com/22028657/91310893-0cab7b00-e7d0-11ea-8db6-de472e19cb2d.png)

**Comment by RMacfarlane** [comment]
Hi @AnkitJain09, can you please reopen this issue on the python extension? https://github.com/Microsoft/vscode-python/issues Thank you!
