### ISSUE TITLE
GitHub integration intermittently fails in latest update

### ISSUE THREAD

**Issue by chuck-confluent** [microsoft/vscode#105438]
- VSCode Version: 1.48.2
- OS Version: Ubuntu 18.04 running on WSL2 on kernel 4.19.84-microsoft-standard

Steps to Reproduce:

1. Enable GitHub integration
2. Open vscode (which will open all windows that were open when I Iast shut down my machine)
3. Commit change and push to remote
4. Error:
```
fatal: cannot run /home/chuck/.vscode-server/bin/3dd905126b34dcd4de81fa624eb3a8cbe7485f13/extensions/git/dist/askpass.sh: No such file or directory
```
5. Close vscode and open again and it now works

Maybe there is some cache pointing to the old vscode-server that is not getting updated properly.

Does this issue occur when all extensions are disabled?: Yes/No

I get an error that --disable-extensions is not supported

**Comment by joaomoreno** [comment]
> Maybe there is some cache pointing to the old vscode-server that is not getting updated properly.

This can happen if your integration terminal opens before the Git extension is activated, unfortunately. cc @Tyriar
