### ISSUE TITLE
VSCode get a net::ERR_PROXY_CONNECTION_FAILED error behind a proxy server

### ISSUE THREAD

**Issue by wrlu** [microsoft/vscode#105464]
- VSCode Version: 1.48.2 (system setup)
- OS Version: Windows 10 Version 2004 Build 19041

Steps to Reproduce:

1. When use the VSCode behind a proxy server, we get a `net::ERR_PROXY_CONNECTION_FAILED` error. I am sure that my proxy settings in Windows is all right.
2. I try to configure my proxy in the VSCode proxy settings but it failed and still show a `net::ERR_PROXY_CONNECTION_FAILED` error.
3. I have 2 enterprise PCs. One works ok before I upgraded the VSCode to version 1.48.2, and another one works bad on version 1.47.3 for it cannot upgrade itself automatically.

Does this issue occur when all extensions are disabled?: Yes

**Comment by wrlu** [comment]
By the way, I have checked enterprise security control software & antivirus software log, it shows that they did not ban my VSCode process.

**Comment by chrmarti** [comment]
Could you start VS Code with `--log-net-log=netlog.json`, do what you do to trigger the error and then post the created netlog.json here?

**Comment by wrlu** [comment]
> Could you start VS Code with `--log-net-log=netlog.json`, do what you do to trigger the error and then post the created netlog.json here?

I have just used this parameter to start VS Code and got the netlog.json file. I am sorry to say that I have some file transfer & USB limitation in my company so I cannot upload the log file here.  I will keep watching this issue until anyone else have solution or I just fix it by myself. Thanks for your help.   : )
