### ISSUE TITLE
VSCode’s renderer helper process using 100% of CPU

### ISSUE THREAD

**Issue by jeandat** [microsoft/vscode#105442]
As asked by the team in this [ticket](https://github.com/microsoft/vscode/issues/87509), I'm creating my own one.

Issue description is simple. One vscode process named "Code Helper (Renderer)" is eating all my CPU.
I'm restarting vscode every day because of this. I can reproduce it every day but not on purpose.
It happens after some time, don't know what triggers it specifically.

I'm working on a single angular project with typescript on a large codebase.
I precise that the angular language service vscode extension eats a lot of cpu also on its own but it is disabled on my machine for the sake of my sanity. Hearing the fans all day is exhausting.

```
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z (1 day ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

Steps to Reproduce:
- Normal day-to-day job of an angular dev on a big typescript project.

What do you need from me to look deeper into that matter?

**Comment by RMacfarlane** [comment]
Hi @jeandat, can you follow https://github.com/microsoft/vscode/wiki/Performance-Issues#the-rendererwindow-process-consumes-a-lot-of-cpu and see if different folders/settings have any impact on this? (It would also be good to confirm that this is the renderer process using the Process Explorer.) There are also instructions there on how to profile the renderer process
