### ISSUE TITLE
Auto import suggestion is not working

### ISSUE THREAD

**Issue by HasanLisbon** [microsoft/vscode#105460]
I am building a react app and while I am writing the code in jsx, when I insert a class syntax it does not show error that if it has been imported or not, which before showed a red underline on the class name, and I could click on the underline and it would import the class automatically. I am attaching a screenshot here:
![eror](https://user-images.githubusercontent.com/35339345/91369720-69c12400-e804-11ea-9161-bf1d4eefddbb.jpg)
In the image you can see that the Counter class is not imported yet the class tag is not marked the red underline which it did before, and which allowed me to auto import the class.

**Comment by mjbvz** [comment]
Please fill out the issue template and also provide steps to reproduce the problem

/needsMoreInfo
