### ISSUE TITLE
Open source server code

### ISSUE THREAD

**Issue by jscsharp** [microsoft/vscode#105430]
I have 2 questions:
1) Is it possible to make final web build public  ( minimize version which you have in https://vscode-web-test-playground.azurewebsites.net/)?

Currently, gulpfile.vscode.web.js  is empty.

2)  Is there any plan to make "src/vs/server" part open source or will it remain proprietary?

Thanks

**Comment by bpasero** [comment]
Related / duplicate: https://github.com/microsoft/vscode/issues/101087

**Comment by bpasero** [comment]
Extracting the web portion of this ask into https://github.com/microsoft/vscode/issues/101087

**Comment by egamma** [comment]
I'm sorry, but we currently have no plans the change the current build setup.
