### ISSUE TITLE
vscode opens with extensions disabled

### ISSUE THREAD

**Issue by pavittarx** [microsoft/vscode#105410]
This is similar to #82359

I am experiencing vscode opening up with extensions disabled. I am using Manjaro Linux with  KDE Desktop Enviornment. I haven't updated vscode or added or removed any extension or anything that would affect vscode, yet I am experiencing this error out of the blue. 

VS Code version: 1.46.1
OS: Manjaro Linux + KDE
Kernel Version: 5.8.1-3

**Comment by sandy081** [comment]
Can you please update your VS Code and see if the issue reproduces ?

**Comment by pavittarx** [comment]
yes, I have tried a couple of things, that includes reinstalling vscode, both code-oss version and "visual-studio-code-bin"

The issue was earlier being reproduced in workspaces. I thought the workspace files were causing the issue, so I created a new one. But, I encountered the same issue in the new workspace as well. The issue usually comes up after reboot.

I have tried opening the folder independently, but that was useless. The issue was somwhow gone this time, when I renamed the folder. But, I am not sure if it will behave the same with next reboot. 

I will share more specifics, but I have spent most of my day installing, reinstalling and trying to get a fix. Fixes are temporary and I usually get the same behaviour after reboot.

**Comment by sandy081** [comment]
Can you please try starting vs code using a different user data directory? 

`code --user-data-dir <path to folder>`

**Comment by pavittarx** [comment]
Yes, I did remove all vscode installations. including the configs. These were -
1. The configs in ~/.config (this was probably causing the error). 
   The folders were `~/.config/code` , `~/.config/Code - OSS` , `~/.config/VSCodium`
2. An vscode installation under `/usr/share/code/code`. Since, I was using `visual-studio-code-bin` This installation was somehow installed by vscode, during updates. Hence, causing the conflict, and was corrupting vscode.    

FInally a fresh installation of vscode from aura repository and, I haven't seen these issues in a last few days/ 

For someone else, encountering the issue, I would suggest backing up 
* `settings.json`
* list of your installed extensions `$ code --list-extensions`

Finally, thanks! @sandy081 for your suggestions, it helped me fix this.
