### ISSUE TITLE
Add ability to merge local git branches

### ISSUE THREAD

**Issue by mlewis-everley** [Microsoft/vscode#10542]
It does not currently appear possible to merge local git branches in VS Code.

Quite a common workflow is to have a "development" branch to develop new features on (or alternatively have feature specific branches). When the development is finished, the development branch is then merged into the "master" branch before release.

This can be done via the integrated terminal, but as VS Code's git implementation is so wizzy, it would be great to be able to replicate this workflow using the GUI.

**Comment by fredrikaverpil** [comment]
I can't believe there aren't more 👍 for this... what's the current alternatives?
An extension, or have you guys set up a task for this?

**Comment by ialex90** [comment]
+1, I think that feature should be considered as almost "mandatory" for the git extension, it's a really nice implementation and with merging, would be perfect. No news?

**Comment by mherodev** [comment]
It'd be lovely to be able to trigger a merge from the command palette, e.g.

cmd + shift + p
`Git: Merge Branch` > Enter
Select a branch to merge from via search-dropdown

Any opportunity to avoid having to dip back into the command line is lovely.

Thanks in advance!

**Comment by freMea** [comment]
Weird it is still not implemented. It spoils the git integration in Code as if the feature was unfinished. We can still rely on built-in terminal or extension but it is not a consistent Code workflow

Same for git stash #1904

**Comment by ghiscoding** [comment]
I also would like to see a Git Merge implemented eventually without going in the console. 

@freMea you might be interested to know that there's an open PR #29138 to `add Git Stashing` which will hopefully land soon.

There's actually also a PR #10542 for `Git Merge` but changes were asked over a month ago and it wasn't done yet, so it might not land.

**Comment by joaomoreno** [comment]
Fixed in #25731
