### ISSUE TITLE
VSCode starting up with its title bar outside monitor

### ISSUE THREAD

**Issue by peter-pakanun** [microsoft/vscode#105469]
VSCode keeps starting up with its title bar overflow outside monitor (Y value in the minus), I need to use Win+Arrow to move it out every time.

![image](https://user-images.githubusercontent.com/6493474/91387095-a3267d80-e85e-11ea-8397-e4a60e4d6314.png)

If I make it into a small window and close the program, this fixes the issue somewhat, and then it reappears again later.

This may have to do with me using multiple instances of VSCode on a multiple Visual Desktop (Win+Tab)

I'm running Windows 10.

PS. My multi-monitor setup has all the monitors on a parallel plane (All start at the same Y coordinate) so I don't think it's the problem with my multi-monitor setup.

**Comment by deepak1556** [comment]
Does this happen with latest insiders https://code.visualstudio.com/insiders ?
