### ISSUE TITLE
 "editor.semanticHighlighting.enabled": false is not honored and console.log is wrong color. should be green. after update

### ISSUE THREAD

**Issue by bantingGamer** [microsoft/vscode#105478]
create a new JavaScript file

type conosle.log("hello world")
console.log looks the same as any other method and this is no nice to and difficult to work with.
 i have look everywhere on the internet and no one gives a solution that actually works.

**Comment by aeschli** [comment]
duplicate of https://github.com/microsoft/vscode/issues/104616

**Comment by bantingGamer** [comment]
Finally i found a workaround for this issue.

you have to enable semanticHighlighting and then add a property that will change the color manually 

create a folder called **.vscode** 
create a file called **settings.json**
add the following code:
```
{
  "editor.semanticTokenColorCustomizations": {
    "enabled": true,
    "rules": {
      "variable.defaultLibrary": "#4EC9B0"
    }
  }
}
```
hope this helps peeps in distress 😝
