### ISSUE TITLE
Change codeql action to run based on a schedule

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#105447]
Run codeql weekly or monthly as it's using a lot of vm time.

**Comment by joaomoreno** [comment]
> lot of vm time

Where can we see this?

**Comment by Tyriar** [comment]
@joaomoreno 5718 runs multiplied by ~40 minute runtime https://github.com/microsoft/vscode/actions?query=workflow%3A%22Code+Scanning%22

**Comment by joaomoreno** [comment]
But like, is there a budget? Limits?

**Comment by Tyriar** [comment]
@joaomoreno no limits afaik, just reducing our azure resources burden.
