### ISSUE TITLE
Terminal on Linux: need to run as root or suid

### ISSUE THREAD

**Issue by JCKodel** [microsoft/vscode#105403]
Issue Type: <b>Bug</b>

Whenever I try to issue a command on the VSCode built-in terminal, the following message is displayed: 

```
need to run as root or suid
```

This happens, for example, in the command `flutter clean` (which does NOT require any kind of elevated permissions).

If I try to elevate something in the built-in terminal, this error is thrown:

```
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

No matter if I'm using zsh or bash.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 5.4.0-42-generic (Neon KDE - Ubuntu 20)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|31.32GB (11.15GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-languagetool|ada|3.8.0
vscode-languagetool-pt|ada|3.8.0
tt-processor|ais|0.8.0
tinypng|and|0.3.3
dart-code|Dar|3.13.2
flutter|Dar|3.13.2
gitlens|eam|10.2.2
vscode-google-translate|fun|1.4.8
todo-tree|Gru|0.0.178
output-colorizer|IBM|0.1.2
customize-ui|ioc|0.1.47
monkey-patch|ioc|0.1.10
pubspec-assist|jer|2.0.0
svg|joc|1.3.8
vscode-gutter-preview|kis|0.26.2
dart-import|lua|0.2.0
regionfolder|map|1.0.12
csharp|ms-|1.23.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
hexeditor|ms-|1.2.1
sqltools|mtx|0.23.0
sqltools-driver-sqlite|mtx|0.2.0
awesome-flutter-snippets|Nas|2.0.4
vscode-xml|red|0.13.0
multi-command|ryu|1.4.0
vscode-taskexplorer|spm|1.26.3
comment-divider|sta|0.2.2
unique-window-colors|stu|1.0.51
sort-lines|Tyr|1.9.0
errorlens|use|3.2.1
vscode-icons|vsc|10.2.0
t4-support|zbe|0.5.0

</details>

**Comment by Tyriar** [comment]
Do you have `"terminal.integrated.inheritEnv": false` set in your settings by chance?

**Comment by JCKodel** [comment]
> Do you have `"terminal.integrated.inheritEnv": false` set in your settings by chance?

Nop. And this is not an issue since last update. Don't know what went wrong.
