### ISSUE TITLE
[json] Hover/completion not working for scoped packages

### ISSUE THREAD

**Issue by qdouble** [Microsoft/vscode#10541]
- VSCode Version: Version 1.5.0-insider (1.5.0-insider)
- OS Version: OSX 10.11.6

Feature Request:

Can you guys please add the ability to see the latest version of a package that starts with an @ symbol? Currently, if I hover any package in my package.json I can see what is the latest version, but with stuff like @types and @angular and others, I'm not able to see it so I'd have to manually search for what is the latest version of their packages.

**Comment by joaomoreno** [comment]
@aeschli Verification tips?

**Comment by aeschli** [comment]
In your package.json, add a dependency to a [scoped package](https://docs.npmjs.com/misc/scope), e.g. `@types/babel-types`.
Check that the hover as well as version code completion works.

**Comment by joaomoreno** [comment]
Pretty cool, didn't even know about that.
