### ISSUE TITLE
When saving a file on VSCode running under WSL (Editing on WSL:Ubuntu-18.04), terminal freezes. 

### ISSUE THREAD

**Issue by gitmayoor** [microsoft/vscode#105465]
Issue Type: <b>Bug</b>

I've my development server configured under WSL Ubuntu. I've my git repository under WSL as well. I use VSCode on WSL to edit files. I'm constantly facing Terminal freeze after I 'save' my edits everytime under this environment. 

Only way to recover from this is to close and restart VSCode. 

I'm not facing issues with normal files. Only files under git. 

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|31.72GB (17.36GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-peacock|joh|3.8.0
remote-containers|ms-|0.134.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
dart-code|Dar|3.13.2
flutter|Dar|3.13.2
gitlens|eam|10.2.2
remotefs|lix|0.0.16
python|ms-|2020.8.103604
remote-vscode|raf|1.1.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
So you have a terminal open, you go to an editor, make a change and save it and then the terminal freezes? Could you show a [gif](https://gifcap.dev/) of the issue?
