### ISSUE TITLE
Electron 9: increase in binary size

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#105416]
Something to check when we update Electron is increase binary sizes. So far I can see some increase comparing stable to insiders:

![image](https://user-images.githubusercontent.com/900690/91304358-a90e5700-e7a9-11ea-9c5f-359a86d1bab9.png)

Not sure if there is a build issue in Electron that could explain this or simply new code that accounts for this.

Something I noticed while checking randomly: `libGLESv2.dylib` is now 10 MB when it was 4 MB before.

**Comment by deepak1556** [comment]
There is now a 3MB increase in `Electron Framework` executable and 6MB increase in `libGLESv2.dylib`, there is no issue with stripping here, the framework increase is newly added code. As for the gl library, it is the same 10MB size in chrome app as well. I will check with upstream about what caused this size increase but there is nothing actionable at the moment.

**Comment by deepak1556** [comment]
This is a known size increase in chromium and they are investigating possible solutions.
