### ISSUE TITLE
Extra dot applied on a property at second entry with IntelliSense

### ISSUE THREAD

**Issue by Kenya-West** [microsoft/vscode#105498]
- VSCode Version: 1.48.2
- OS Version: Windows 10 (1909)

Steps to Reproduce:

1. Create a Typescript document: Ctrl+N, F1, type "Lang", then Enter and choose Typescript
2. Insert this snippet:

```typescript
const kek = {
    keks: 1,
    kek2: 0
}

kek.keks = kek["keks"]
```

3. Select the property `keks` and press Ctrl+D to select another entry
4. Hit Backspace to remove selected entries
5. Use Intellisense (Ctrl+Space) to get hints and choose any of suggesstions
6. Second entry will have a dot applied. It should not have this, this is a bug

A gif for clarification: 

![](https://im7.ezgif.com/tmp/ezgif-7-3ba0130214cb.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is the same root issue as #90695

Closing as out of scope. The VS Code suggest api does not always play nicely with multi cursor but it's also not simple to fix this

/cc @jrieken
