### ISSUE TITLE
implement debugger PerfTips

### ISSUE THREAD

**Issue by Trass3r** [microsoft/vscode#105417]
![image](https://user-images.githubusercontent.com/4764609/50218826-68bfca00-0374-11e9-8651-7697d36d9816.png)
 
 https://docs.microsoft.com/en-us/visualstudio/profiling/perftips

**Comment by petke** [comment]
Last time it was closed as not enough votes:
https://github.com/microsoft/vscode/issues/65384
Maybe it gets more votes this time around. I'd find it useful for gdb linux

**Comment by Trass3r** [comment]
It shouldn't be too hard to implement either. I'm also measuring time between calls in my own extension like this:
```ts
let lastCalled = new Date();
function doStep(...) {
    const diff = <any>new Date() - <any>lastCalled;
    lastCalled = new Date();
```
You "just" need to add it as a [decoration](https://vscode.rocks/decorations).

**Comment by weinand** [comment]
"Just" submit a PR and we will consider it... ;-)

**Comment by Trass3r** [comment]
I actually tried solving it via an extension using DebugAdapterTracker.
The only problem is how to get the current editor when the stopped event arrives. `activeTextEditor` is undefined for whatever reason and onDidChangeActiveTextEditor doesn't fire either.

**Comment by weinand** [comment]
@Trass3r Please consider to publish your extension on the Marketplace.

**Comment by Trass3r** [comment]
That's the plan. Need a better name and some time.
