### ISSUE TITLE
Unstable

### ISSUE THREAD

**Issue by csicky** [microsoft/vscode#105495]
I use some extensions, I work in Vue.js development, since many years, since the beginning. At that time many things were missing, VS Code was just a text editor. 
Now, VS Code tries to be an IDE, I think, but the work is spread al over the extensions platform, which is like a wild west. I am sure each extension author tests their own work, but it is impossible for them to test all the combinations. This issue is here to signal the **instability** and unhealthiness of the whole VS Code **extensions ecosystem**. Most of the time I update an extension something will break. Like every week I loose either the formatting, or the linting, or something else. Then I have to either hunt down what went wrong, what settings changed, what extension works with another one at which version. 
Most of the time it's Prettier, Vetur, ESLint or VS Code itself. One of these, or some combination.
Until now I couldn't upgrade Vetur from 0.25.0 because it would stop formatting because some dependency of their own. 
Today I upgraded Prettier. I can't save my work anymore.
![image](https://user-images.githubusercontent.com/3931907/91451459-1db6c380-e886-11ea-8cd8-cad28323ec7e.png)

I know, each issue means me to open a new issue for the specific extension, or update my settings, and all that. But, I was working just fine, then came the upgrade of the extension. From that point it stopped working and I can't work, I get interrupted. When will this whole thing be more stable? What if this would be a car, and I would be stuck on the side of the road because I dared updating an extension?

I know this issue will be closed quickly, the point is please read it and think about this, how to make upgrading an extension less dangerous. Thank you.

**Comment by RMacfarlane** [comment]
Hi @csicky, thanks for taking the time to write this, I'm sorry that your experience has been so frustrating. Having extensions break hurts productivity and hurts trust in the product.

As you say, I am going to go ahead and close this issue since there is not a specific bug we can fix here, but we will keep this feedback in mind.
