### ISSUE TITLE
Debug does not show values for object children

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10548]
- VSCode Version: Code - Insiders 1.5.0-insider (2e54e84905a76b2278c7c0bccc86a69f03b2d5d4, 2016-08-15T06:04:11.629Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Debug code
2. Hover object eg. `mapping`:
You get:
![image](https://cloud.githubusercontent.com/assets/1723815/17667608/88c51178-62d3-11e6-965d-975bde11cd22.png)

3. Hover child eg. `selector` in `mapping.selector` and nothing happens:
![image](https://cloud.githubusercontent.com/assets/1723815/17667629/9de037ae-62d3-11e6-9be2-6b7151ebb092.png)

**Comment by isidorn** [comment]
What language are you debugging?
In order for us to investigate this we need a simple code snippet for which we can reproduce this. Can you please provide this?
In the variables view do you see a value for mapping.selector?

**Comment by wallverb** [comment]
Typescript.
I will create separate issues with reproducible steps
