### ISSUE TITLE
Filename extensions with suitable orders in the 'Save as type' drop-down menu when save the file.

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/vscode#105463]

**Comment by gonghenghai** [comment]
The filename extension order is not suitable when saving a file. For example, when saving a file and choose 'Java' In the 'Save as type' drop-down menu, the file will be saved as '.class' file by default. Because the Java item shows like this: Java(*.class; *.java; *.jav; .java; .jav), '*.class' before of '*.java'. that can confuse some users.

**Comment by bpasero** [comment]
@gonghenghai what operating system are you running?

**Comment by testforstephen** [comment]
Same for macOS Catalina 10.15.5.

Save the Untitled file to Java format, the default filename extension is .class. It should be .java.

![image](https://user-images.githubusercontent.com/14052197/91684930-6a9ee080-eb8b-11ea-9a08-4bafb45519b3.png)

**Comment by testforstephen** [comment]
```
Version: 1.50.0-insider
Commit: e13875b77c89b95f20ccb5667e14ff164c198e57
Date: 2020-09-15T05:31:36.744Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0
```

@bpasero When i tried to save an Untitled file to Java format in macOS, the default file extension is still `.class`. Looks like this issue is not fixed with the latest upstream electron.

**Comment by bpasero** [comment]
I cannot reproduce that, steps:
* new untitled file
* hit `Cmd+S`
* pick Java from the dropdown

![image](https://user-images.githubusercontent.com/900690/93296498-a4a8ed00-f7ef-11ea-9083-f33c78d1390e.png)

**Comment by testforstephen** [comment]
By using the insider at 2020-09-15, actually i can reproduce it in both windows 10 and macOS 10.15.5. 

![newfile](https://user-images.githubusercontent.com/14052197/93297844-b3f65d80-f824-11ea-98b9-283b75ef8048.gif)

**Comment by bpasero** [comment]
@testforstephen you possibly have a Java extension installed? Does it reproduce when you disable that extension?

**Comment by testforstephen** [comment]
Yes, disable all installed extensions, the default extension name becomes `.java`. I'm wondering how the Java extension affect the file save logic?

**Comment by bpasero** [comment]
@aeschli can you advise what an extension needs to do to get `.java` as first entry? I assume they need to change the order in `package.json`?

**Comment by testforstephen** [comment]
Java extension added the following section to package.json.
```json
{
  "contributes":
   {
    "languages": [
      {
        "id": "java",
        "extensions": [
          ".class"
        ],
        "configuration": "./language-configuration.json"
      }
    ]
  }
```

If i added ".java" before ".class" in "extensions" field, the Untitled file will be saved to `.java` by default. But for Windows, the file extension candidates will contain a duplicated .java in file dialog. Is there any way to fix this?

Before:
![image](https://user-images.githubusercontent.com/14052197/93317133-abf7e700-f83f-11ea-908b-3eb48cc90b45.png)

Fix:
![image](https://user-images.githubusercontent.com/14052197/93317250-d2b61d80-f83f-11ea-836c-0d9199bb106f.png)

**Comment by aeschli** [comment]
@testforstephen I pushed a fix for the duplicated file extensions (https://github.com/microsoft/vscode/commit/02cf31cda7af3d38200d61ddcc05bbde1dc1d37f)

**Comment by testforstephen** [comment]
@aeschli Cool, thanks for the quick fix.
