### ISSUE TITLE
"Report issue" do not quote/escape the "System info" text properly

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#105494]
Issue Type: <b>Bug</b>

Try submitting the issue in workspace opened from UNC path.
The workspace path will be mangled. Like in this issue.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 3303)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (7.64GB free)|
|Process Argv|\\HOST\share\Documents\project|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
php-debug|fel|1.13.0
todo-tree|Gru|0.0.178
sqltools|mtx|0.23.0

</details>

**Comment by RMacfarlane** [comment]
@AnrDaemon I'm not quite sure what you mean here, can you provide an example of a workspace path and what you expect to be?

**Comment by AnrDaemon** [comment]
This should be `\\HOST` at the very least.
