### ISSUE TITLE
can we have the auto-disappear notification?

### ISSUE THREAD

**Issue by zesluo** [microsoft/vscode#105412]
Hello! I want to pop up a notification, and it will disappear automatically after a short while. Can we have this one? Thanks
![image](https://user-images.githubusercontent.com/46309533/91297123-54320700-e7d0-11ea-8080-9b1c45fea482.png)

**Comment by RMacfarlane** [comment]
@zesluo This should be the current behavior of notifications - if they don't have a button, they should disappear after a while. Are you not seeing this?
