### ISSUE TITLE
PCRE2 not supported on ARM

### ISSUE THREAD

**Issue by TheNeverK** [microsoft/vscode#105443]
Hi.

I've encountered an interesting issue. Currently i'm working remotely, through SSH extension on a Raspberry Pi 4 (newest Raspbian/Raspberry OS) and I've had problems with searching in all files from working directory. While the problem itself was caused by a deprecated PCRE setting on the Windows host, the reason I wasn't getting any results was caused by the fact that currently ripgrep included with the VS Code server is not compiled with the `--features 'pcre2'` flag (at least for a 'arm-unknown-linux-gnueabihf' target). This effectively disables look-around and backreferences on some platforms, because according to the deprecation warning, PCRE2 is still used in those cases automatically. While i'm not sure about other ARM platforms, i've had no problems with compiling ripgrep with that flag on RPi and replacing the bundled `rg` binary.
Maybe it would be worth providing users with a choice which version to include? Or even it could be automatically selected based on the capabilities of the platform?

Not sure if i should submit this here or to the [ripgrep-prebuilt](https://github.com/microsoft/ripgrep-prebuilt), so sorry in advance.

**Comment by roblourens** [comment]
Yeah, I don't build with PCRE2 for ARM, I think I had issues with that originally. But I'll see whether I can make it work now.

**Comment by roblourens** [comment]
Now fixed

**Comment by roblourens** [comment]
Steps if someone else is able to verify on an ARM device

- Use vscode on linux ARM, remote is ok
- Do a search that involves a lookbehind regex, for example `(?<=a)b` would match the `b` in `ab`
- It should work and not give an error

**Comment by chrmarti** [comment]
Verified with an ARM container (using the QEMU emulator, https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers).
