### ISSUE TITLE
[bug] Odd tab index from Search/Replace

### ISSUE THREAD

**Issue by mrmokwa** [microsoft/vscode#105492]
# Bug

## Description of the problem
Tab Index should respect the top-down order.

**Current**
Search > Replace > Buttons inside search > Buttons inside replace

**Expected**
Search > Buttons inside search > Replace > Buttons inside replace

## Steps to Reproduce:
![vscode_search_tab_index](https://user-images.githubusercontent.com/12090931/91449768-e62e2400-e851-11ea-9aeb-e02bcdc9e64a.gif)

- VSCode Version: 1.48.2
- OS Version: Windows_NT x64 10.0.19041

**Comment by roblourens** [comment]
It used to be that way, but I think this was is much more ergonomic since users probably want to switch between search/replace more than focusing the buttons.
