### ISSUE TITLE
CTRL+X

### ISSUE THREAD

**Issue by M4shy** [microsoft/vscode#105402]
Issue Type: <b>Feature Request</b>

I'm a bit disappointed when I'm cutting (ctrl+x) some code and trying to paste it afterwards (ctrl+v). VC is right cutting the characters on screen but doesn't seem to keep it into clipboard in case of further usage.

Did I miss something ?

Cheers,
John

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

**Comment by M4shy** [comment]
I've updated VS this morning and this behaviour seems not happening anymore.

**Comment by weinand** [comment]
Does it make a difference if you paste the clipboard with the "Paste" menu action (instead of using the keyboard shortcut)?

**Comment by M4shy** [comment]
Hello, I wasn't yet able to reproduce it but I'll let you know as soon as it will happen again.

**Comment by M4shy** [comment]
Hello, I wasn't yet able to reproduce but I'll let you know as soon as it will happen again.

**Comment by M4shy** [comment]
I can't reproduce it. Maybe my old habit to delete the cutted empty line with a key.
Remembered me that VI editor allowed this by pressing twice the 'D' key.

**Comment by M4shy** [comment]
I can't reproduce it. Maybe my old habit to delete the cutted empty line with a key.
Remembered me that VI editor allowed this by pressing twice the 'D' key.

**Comment by M4shy** [comment]
I can't reproduce it. Most probably my old habit to delete the remaining empty line after a cut.
Remembered me that VI editor allowed this by pressing twice the 'D' key (instead of ctrl+x).
