### ISSUE TITLE
Persist "Source Control Repositories" selection across reload

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#105444]
I just realized that I can get the old repos view back in the SCM view, and that made me very happy. I would be even happier if it would remember my selection in that list when reloading the window. Currently it always selects all of them after reloading.

**Comment by gjsjohnmurray** [comment]
Related to a point made by @joaomoreno in the "Bad news" section of https://github.com/microsoft/vscode/issues/104151#issuecomment-672001440

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/104629
