### ISSUE TITLE
No settings UI to add a default formatter for a specific language

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#105433]
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

There's no way user can add this setting: set a default formatter for a specific language.

In settings.json, users can easily set

```json
{
  "[vue]": {
    "editor.defaultFormatter": "octref.vetur"
  }
}
```

Although it's hard for users to discover how to set such settings.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/74195
