### ISSUE TITLE
Status bar keeps showing 'Select Python Intrepreter'

### ISSUE THREAD

**Issue by allan5050** [microsoft/vscode#105426]
Issue Type: <b>Bug</b>

VS Code keeps asking me to 'Select Python Intrepreter' in the status bar, even though I've done it like 3 times to select the path, e.g. C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe

The bar won't go away now.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
vscode-html-css|ecm|0.2.3
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
python|ms-|2020.8.103604
cpptools|ms-|0.29.0
vscode-scss-formatter|sib|2.0.2
python|tht|0.2.3
tensorflow-snippets|vah|0.3.3
jinja|who|0.0.8
html-css-class-completion|Zig|1.19.0

</details>

**Comment by RMacfarlane** [comment]
Hi @allan5050, can you please reopen this on the Python extension? https://github.com/Microsoft/vscode-python Thank you!
