### ISSUE TITLE
Extension connection problems

### ISSUE THREAD

**Issue by xXGoziXx** [Microsoft/vscode#10540]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.go to extensions
2.look for extensions e.g. @popular
3.nothing shows up to be installed

**Comment by maibaum** [comment]
Also experiencing this - no extensions populate in the sidebar for any of the filters: @popular, @outdated, @recommended, and .Show Installed Extensions'.

Same steps to reproduce as @xXGoziXx stated above.
    
- VSCode Version: Code 1.5.0-insider (Commit dde41be0231d6f8397d1da969ddab351f137b833)
- OS Version: Windows 7


![extension-issue](https://cloud.githubusercontent.com/assets/4589329/17666820/059af7ca-62d0-11e6-999f-7d685334debf.png)

**Comment by maibaum** [comment]
`"http.proxyStrictSSL": false` fixed this issue for me.

**Comment by joaomoreno** [comment]
@xXGoziXx If you are behind a proxy, make sure to configure it [appropriately](https://code.visualstudio.com/docs/setup/setup-overview#_proxy-server-support). Also try the `http.proxyStrictSSL` option.

**Comment by xXGoziXx** [comment]
Yeah I had a feeling it was to do with that. It was my work laptop that I was using.
