### ISSUE TITLE
Rename notebook activation event

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105496]
Today, it is `onNotebookEditor:XYZ` but it should be `onNotebook:XYZ` since we will open and edit notebooks without an editor showing for it

**Comment by jrieken** [comment]
FYI @DonJayamanne @TylerLeonhardt @colombod @renkun-ken @dlschmidt @darknoon @weinand - this change will happen this week. Please adopt your extensions in two steps

1. in addition to the old event add the new event, `onNotebook:XYZ`
1. when this change is done and shipped remove the old event

Also, note that we are doing this change to make it more clear that a notebook can be opened and modified without having an editor. So please revisit assumptions that you might have about documents only being opened/editing with an editor.

**Comment by TylerLeonhardt** [comment]
Thanks for the heads up... I'll try to get an update out but currently drowning in other work for Ignite.

**Comment by DonJayamanne** [comment]
> assumptions that you might have about documents only being opened/editing with an editor

This doesn't make sense. An example would be good.
Do you mean, we can edit notebooks without a notebook editor?

**Comment by jrieken** [comment]
> Do you mean, we can edit notebooks without a notebook editor?

Yes - that's the whole point of the workspace edit api, e.g LiveShare is such a case in which notebook edits are just replayed when they have happened in another editor.
