### ISSUE TITLE
Add right click option to add file or folder to .gitignore/.gitkeep

### ISSUE THREAD

**Issue by TurboCooler** [microsoft/vscode#105450]
As a developer, I want to right-click on a file or folder in the File Explorer in VSC and automatically add the file to .gitignore.  If a .gitignore file does not exist, then create the .gitignore file and add the path for the file or folder to gitignore.

In a similar fashion, I wish to add files of folders to gitkeep.

**Comment by gjsjohnmurray** [comment]
IIRC there is already a way of doing this from an untracked file in the SCM view.

**Comment by gjsjohnmurray** [comment]
Re .gitkeep is this the file you mean?

https://stackoverflow.com/a/7229996

**Comment by TurboCooler** [comment]
@gjsjohnmurray -- yes.  The use case is this.  You create a database and externalize the data files.  We have this automated so that the docker container is created on our laptops and files placed in a specific directory.  If we check in the empty dir then that will work on any laptop.

**Comment by TurboCooler** [comment]
> IIRC there is already a way of doing this from an untracked file in the SCM view.

Yes, but only for files and if I have a hundred of files to check in that is lot to scroll through versus being in the current working directory.

Also, directories are not shown in the view at least no for me.

**Comment by gjsjohnmurray** [comment]
> > IIRC there is already a way of doing this from an untracked file in the SCM view.
> 
> Yes, but only for files and if I have a hundred of files to check in that is lot to scroll through versus being in the current working directory.
> 
> Also, directories are not shown in the view at least no for me.

#81724 implies all untracked files in a folder can be added in a single operation. You probably need to toggle from flat view to folder view in the SCM view. Look for this toggle in the title bar or its menu.
