### ISSUE TITLE
Typescript debugger doesn't stop on object destructing assignment before executing RHS

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#105470]
Issue Type: <b>Bug</b>

1) git clone https://github.com/microsoft/vscode-azurearmtools.git
2) cd vscode-azurearmtools
3) git checkout saw/bug-destructuring-debugger
4) npm i
5) open vscode-azurearmtools in vscode
6) Find both lines with "<< BREAKPOINT HERE" and add a breakpoint on each
```
const { items: completions } = await pc.getCompletionItems(options.triggerCharacter); // << BREAKPOINT HERE (ONE)
```
and also the first line of getCompletionItems:`
```
    public async getCompletionItems(triggerCharacter: string | undefined): Promise<ICompletionItemsResult> {
        const tleInfo = this.tleInfo; // << BREAKPOINT HERE (TWO)
```
7) set configuration to "Launch Tests"
8) F5
EXPECTED: Should hit ONE first before getCompletionItems is called, then TWO as the call to getCompletionItems is executed
ACTUAL: Hits TWO first, then ONE

VS Code version: Code - Insiders 1.49.0-insider (11dc5a81ba248cc2678888391f1b24dccabddaf8, 2020-08-17T17:11:16.078Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id 28a909e2-0b30-47b4-bfa3-dcb1734aca95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
todo-tree|Gru|0.0.178
vscode-dotnet-runtime|ms-|0.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by connor4312** [comment]
This is a Chrome issue which is tracked here: https://bugs.chromium.org/p/chromium/issues/detail?id=782461&can=4&q=breakpoint&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

/duplicate
