### ISSUE TITLE
Change error message for missing DA on variable expansion

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#105436]
Someone brought up on Twitter https://twitter.com/brandonscript/status/1298010182979444736 which I think makes sense.

We don't expose the concept of "debug adapters" to end users, so this error message is confusing. A better message here could be something like:

> Cannot request variable information after the debug session has ended

cc @isidorn

**Comment by isidorn** [comment]
This makes perfect sense.
Note that there are many places where we use "debug adapter" in errors. Note the Debug sesssion file, bascially all those should be more speciifc. Code pointer https://github.com/microsoft/vscode/blob/860a68747f1ca4cafcc3c96309b468e85ff89382/src/vs/workbench/contrib/debug/browser/debugSession.ts#L267

If you are passionate you can start on this and I can also help if needed.

**Comment by connor4312** [comment]
I changed `No debug adapter,...` to `No debugger available, ...`

**Comment by isidorn** [comment]
Great, thanks.
