### ISSUE TITLE
"Show more" button does not disappear from notebook cell output

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#105432]
Issue Type: <b>Bug</b>

1. Use GitHub Issues Notebook extension and a `.github-issues` file to run a query that results in many issues, such that a "Show More" button is rendered at the bottom of the output
2. In the same cell, run a query that returns only a few results

The button now shows "Show 0 More":
![Screen Shot 2020-08-26 at 7 56 36 AM](https://user-images.githubusercontent.com/3672607/91320133-0be3fc00-e772-11ea-9259-85739108edf3.png)

VS Code version: Code - Insiders 1.49.0-insider (7df29b1236ecf8a21af9fe19a52923f6d69e0577, 2020-08-26T07:45:54.661Z)
OS version: Darwin x64 18.7.0

**Comment by connor4312** [comment]
I think this was specifically if you queried exactly enough items to match the page size 😛
