### ISSUE TITLE
File is a directory

### ISSUE THREAD

**Issue by florenso** [microsoft/vscode#105472]
- VSCode Version: 1.48.2
- OS Version: windows_NT x64 10.0.1864

Steps to Reproduce:

1.  create two files: "c:/a.py" & "c:/b.py"
2. create hyperlink in file a pointing to file b "# file://c:/b.py"
3. ctrl+click on link

What i expected: opens file b in vscode.
What i get:
![error](https://user-images.githubusercontent.com/9743844/91388681-2385b800-e838-11ea-94c4-9e78891a7a7a.PNG)

Does this issue occur when all extensions are disabled?: Yes

found this closed issue that is related
https://github.com/microsoft/vscode/issues/62251

**Comment by gjsjohnmurray** [comment]
As shown in https://github.com/microsoft/vscode/issues/62251#issuecomment-434884631 change your // to /// and retry.

**Comment by florenso** [comment]
I missed that, thanks!

i still consider it a bug because:

1. Error message is wrong, it is a file, not a directory.
2. A linkt to a website does not require a triple backslash.
     - example: # https://github.com/microsoft/vscode/issues/105472
