### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by jonlofty** [microsoft/vscode#105497]
- VSCode Version: 1.48.0
- OS Version: Win 10 Enterprise v1809 Build 17763.1339

![image](https://user-images.githubusercontent.com/18631019/91454453-e1309b00-e878-11ea-83e8-03196f632cd1.png)

Get the above error when using the windows context menu to open a file in VS Code. Running instance is not affected, but no further instances can be opened.

Only fix so far is to remove and reinstall VSCode.

Process launches 3 instances in task manager per attempt. These have to be process killed to stop.

![image](https://user-images.githubusercontent.com/18631019/91454879-57350200-e879-11ea-9493-c0161e8ebf8f.png)

Steps to Reproduce:

1. Select file to open
2. Right click file
3. Select Open with VS Code

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Seems like incorrect installation of vscode, does this happen with latest stable ?
