### ISSUE TITLE
Cannot login / use codespaces in Safari

### ISSUE THREAD

**Issue by dbogatov** [microsoft/vscode#105452]
- VSCode Version: whatever is latest in codespaces now
- OS Version: browser (Safari)

**I honestly tried to use Microsoft support, but that seems to be for business customers only**

Steps to Reproduce:

1. Go to online.visualstudio.com
2. Click "Sign in" button
3. Observe constant redirects
4. Observe "Login failed due to an unexpected error. Please log out and try again."

**I am absolutely sure that my account is OK, I can login with Chrome and I know my password!**

Also, I tried private tab, clearing cookies etc.
From googling I see that people generally can use codespaces from iPad and Mac Safari.
So I think there may be something wrong with my account.
Could you please help?

Does this issue occur when all extensions are disabled?: N/A

**Comment by RMacfarlane** [comment]
Hi @dbogatov, can you please reopen this issue in the Codespaces repo? https://github.com/MicrosoftDocs/vscodespaces Thank you!
