### ISSUE TITLE
Renaming files

### ISSUE THREAD

**Issue by danieltillero** [microsoft/vscode#105458]
Issue Type: <b>Bug</b>

Cant rename files when vs code is open in remote wsl

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (8.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|15.74GB (8.77GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
remote-wsl|ms-|0.44.4
path-intellisense|chr|2.2.1
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.3.0
code-runner|for|0.11.0
pomodoro|lky|1.1.3
vsliveshare|ms-|1.0.2666
LiveServer|rit|5.6.1
code-spell-checker|str|1.9.0
pdf|tom|1.1.0
gitflow|vec|1.2.1
vscodeintellicode|Vis|1.2.10

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
I believe this is a WSL issue, thus first assigning to @aeschli

**Comment by aeschli** [comment]
File or folders? If folders, see https://code.visualstudio.com/docs/remote/troubleshooting#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace.
