### ISSUE TITLE
Keyboard Shortcut: Command for workbench.action.debug.selectandrun

### ISSUE THREAD

**Issue by jahan01** [microsoft/vscode#105429]
I would like to select and run the configuration in `launch.json`. This is similar to `workbench.action.debug.selectandstart` but for running the program without debugging. vscode already supports `workbench.action.debug.run` but it runs last  launched debug configuration by default and doesn't provide mechanism to choose

**Comment by jahan01** [comment]
Note: This is a feature request

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by jahan01** [comment]
@isidorn suddenly all my issues and feature requests become out of scope in month of October. It has already become so discouraging to file bugs or feature requests anymore

**Comment by spangaer** [comment]
Seems like this request is simple enough not to just get dumped.

**Comment by nevespt** [comment]
nothing yet?

**Comment by weinand** [comment]
Please feel free to submit a pull request for this.
