### ISSUE TITLE
C# Extension & Debugger Unsupported Linux Platform

### ISSUE THREAD

**Issue by alpox** [Microsoft/vscode#10545]
- VSCode Version: 1.4.0
- OS Version: Linux Manjaro KDE Version (Arch x64)
                      uname -a --> Linux elias-pc 4.4.16-1-MANJARO #1 SMP PREEMPT Wed Jul 27 21:09:47 UTC 2016 x86_64 GNU/Linux

I get the following error when trying to install the .NET Debugger with Ctrl-Shift-P: Debug: Download .NET Core Debugger

![image](https://cloud.githubusercontent.com/assets/12485194/17664643/de573c0c-62f5-11e6-943e-1695a61f732a.png)

Steps to Reproduce:

1. Install Manjaro KDE Version
2. Install dotnet-cli from the AUR with the following patch http://www.pastefile.com/5T8qbi (Sadly there was no other option available which worked for installing the dotnet-cli on this system)
3. Install visual-studio-code
4. Install C# Extension
5. Try to install the .NET Core Debugger

I'm aware that you didn't focus on such linux systems yet so the error message is quite obvious. I wonder though, if you will try to bring better support for C# development for other linux platforms like Arch Linux as well.

**Comment by alexandrudima** [comment]
Moved to OmniSharp/omnisharp-vscode#661
