### ISSUE TITLE
OpenDialogOptions.filters does not recognize Makefile

### ISSUE THREAD

**Issue by queeniema** [microsoft/vscode#105461]
Issue Type: <b>Bug</b>

I only want to allow users to open `Makefile` files. The code I've tried is the following:

```typescript
window.showOpenDialog({
  canSelectFiles: true,
  canSelectFolders: false,
  canSelectMany: false,
  filters: {
    Makefile1: ['Makefile'],
    Makefile2: ['makefile'],
    Makefile3: ['make'],
  },
  openLabel: 'Open'
})
```

However, none of these filters work (`Makefile` files in Finder dialog are greyed out).

---

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|17, 24, 25|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|-psn_0_110619|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
filters are passed on to Electron, and can only be file types. And #94277 indicates that on macOS there's a limitation that a filter of, say, `tar.gz` will be treated as `gz`

**Comment by queeniema** [comment]
Does this means that I need to remove `filters` and manually check the user's file selection?

**Comment by gjsjohnmurray** [comment]
I guess so.

**Comment by jrieken** [comment]
/adding @deepak1556 for FYI and for maybe knowing the upstream issue
