### ISSUE TITLE
Custom Titlebar Missing after Update

### ISSUE THREAD

**Issue by ian-emsens-sb** [microsoft/vscode#105413]
Issue Type: <b>Bug</b>

I opened Visual Studio Code after being prompted to update and the Close / minimize / expand buttons are intersecting with the Visual Studio Code UI.

Will attach screenshot.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:09:41.484Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 4, 3|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|-psn_0_12041083|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.3.2
beautify-blade|api|1.0.1
vscode-apollo|apo|1.16.7
vscode-intelephense-client|bme|1.5.4
laravel-goto-view|cod|1.3.3
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.2.1
vs-code-xml-format|fab|0.1.5
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-lombok|Gab|1.0.1
rainbow-csv|mec|1.7.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.5.0
mssql|ms-|1.9.0
python|ms-|2020.8.103604
vsliveshare|ms-|1.0.2666
vetur|oct|0.26.1
laravel-blade|one|1.22.1
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.9.0
laravel-artisan|rya|0.0.27
laravel-goto-controller|ste|0.0.7
vscode-icons|vsc|10.2.0
twig|wha|1.0.2

(1 theme extensions excluded)

</details>

**Comment by ian-emsens-sb** [comment]
After expanding + minimizing once, the issue no longer occurs.

**Comment by ian-emsens-sb** [comment]
https://i.imgur.com/y3FaFSa.png

Open project / GIT branch name hidden

**Comment by sbatten** [comment]
please let me know if you still see this

**Comment by ian-emsens-sb** [comment]
WIll do, sorry for not being able to provide accurate steps to reproduce.
