### ISSUE TITLE
SourceControlResourceGroup duplicated when new groups are added

### ISSUE THREAD

**Issue by mjcrouch** [microsoft/vscode#105483]
- VSCode Version: Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Have an extension that creates a `SourceControlResourceGroup` using `SourceControl.createResourceGroup()`
2. Call `dispose` on the returned `SourceControlResourceGroup`
3. Observe that the resource group still appears in the scm view

edit: above is misleading, see my next post below this one

the circled objects have been disposed, but are still visible. This is from the mjcrouch.perforce extension:

![image](https://user-images.githubusercontent.com/49367953/91421914-681c4e00-e84e-11ea-94f0-b25a795410b1.png)

This will be a big problem for the perforce extension because changelists are temporary, so this is something we do quite a lot.

I know @joaomoreno has recently done a lot of refactoring in this  area and I can see the disposal has changed in `extHostSCM.ts`, but I am having difficulty getting a VS code build to launch properly to step into the code and see where the issue is exactly, but I can confirm from debugging my extension that we're definitely calling dispose.

Does this issue occur when all extensions are disabled?: Yes (ignoring the extension that does the disposal)

**Comment by mjcrouch** [comment]
Managed to get my build working again (I just had to clean my git area).

The actual problem turns out to be that the `createdResourceGroups` map was never being cleared out after being processed by `eventuallyAddResourceGroups`. This results in the same groups being re-added again next time you add resource groups.

My original assertion about disposal was not quite right, it's just that we dispose all the groups and add new ones on every refresh, so they happen to have been disposed, but I believe the same would happen if we just added new groups without disposing of the old ones.

**Comment by roblourens** [comment]
@mjcrouch could you confirm that this now works as expected in Insiders?

**Comment by mjcrouch** [comment]
@roblourens confirmed - no duplicates appearing on insiders

**Comment by roblourens** [comment]
Thanks!
