### ISSUE TITLE
New Search Editor focuses results instead of query input when seeded (use focusResults: false by default)

### ISSUE THREAD

**Issue by benalavi** [microsoft/vscode#105597]
- VSCode Version: 1.48.1
- OS Version: Mac OS 10.14.6

Steps to Reproduce:

1. Select text
2. Open New Search Editor (either via command pallet or key binding)
3. Cursor jumps to first line of results (summary info, i.e. `1 result - 1 file`)

Does this issue occur when all extensions are disabled?: Yes/No

Yes

-----------------------------

TL;DR: `"focusResults": false` might be a more expected default for __Search Editor: New Search Editor__

__Expected Behavior__: I expected that upon opening a __Search Editor: New Search Editor__ the query term would be highlighted and the focus would remain on the query term. In the below screenshot I would expect "Foo" is highlighted and the query bar has focus.

<img width="407" alt="Screen Shot 2020-08-28 at 7 41 56 AM" src="https://user-images.githubusercontent.com/7473/91580451-f9003180-e901-11ea-88dd-ba37ad40e78d.png">

Note that when there is no highlighted text this is the behavior when opening a New Search Editor:

<img width="686" alt="Screen Shot 2020-08-28 at 8 24 07 AM" src="https://user-images.githubusercontent.com/7473/91584686-dc66f800-e907-11ea-80d3-61c659745cf7.png">

I expected this behavior because it is the same behavior as the other two search cases:

__Find__:

<img width="422" alt="Screen Shot 2020-08-28 at 8 01 14 AM" src="https://user-images.githubusercontent.com/7473/91582464-b55af700-e904-11ea-9332-41b41ee7fcf3.png">

...and __Search: Find in Files__

<img width="244" alt="Screen Shot 2020-08-28 at 8 03 21 AM" src="https://user-images.githubusercontent.com/7473/91582682-fce18300-e904-11ea-9d87-bfc319f67180.png">

This often becomes an annoyance for me because of the following use case:

* Have __Search Editor: New Search Editor__ bound to <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd>
* Working in a file, happen to have some highlighted text
* Realize I might need to make some change in another file, open a New Search Editor w/ <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> to find out
* Highlighted text is searched for automatically
* Start typing/paste what was on my clipboard thinking it will override the search term
* End up inadvertently editing the search results
* Press <kbd>Esc</kbd> to get back to the search query
* Try typing/pasting again
* Eventually try to close the New Search Editor and am modally prompted to save it because I inadvertently edited it earlier
* Close the modal w/ mouse or <kbd>Cmd</kbd>+<kbd>D</kbd> (which I learned because of this, silver linings)

I believe this might be relatively recent behavior that was added w/ https://github.com/microsoft/vscode/issues/95582 and/or https://github.com/microsoft/vscode/issues/97823

Based on those I found that I could get the functionality I expected by setting `"focusResults": false` in `keybindings.json`, i.e:

```json
    {
        "key": "shift+cmd+f",
        "command": "search.action.openNewEditor",
        "args": {
            "focusResults": false
        }
    }
```

...at which point I considered just not bothering posting an issue 😅  But because the behavior seems to be inconsistent I think `"focusResults": false` might be a more sensible default for `search.action.openNewEditor`.

Complete conjecture but I imagine the current behavior might have led to issues like: https://github.com/microsoft/vscode/issues/105034 as my first instinct was to wonder why the search results were editable at all.

**Comment by JacksonKearl** [comment]
I think this makes sense, to be consistent with the other search widgets.
