### ISSUE TITLE
Wrong display on integrated terminal

### ISSUE THREAD

**Issue by lwchkg** [microsoft/vscode#105573]
Issue Type: <b>Bug</b>

See screenshot. The text should be left aligned, but several lines of the display is broken. The only possible factor I can say is the existence of CJK characters in the terminal (sadly, all CJK characters in the screenshot are redacted because of personal information).

In the first 4 our of 5 broken lines, Chinese characters are displayed double (e.g. ＸＹＺ becomes ＸＸＹＹＺＺ).
Scrolling up/down don't appear to improve the display.

![Code_ehZMuH81AB](https://user-images.githubusercontent.com/4113719/91549251-3d6aec00-e959-11ea-8d60-ebbd379ac354.png)

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 2396)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.8.3
php-intellisense|fel|2.3.14
vscode-phpfmt|kok|1.0.30
python|ms-|2020.8.103604
powershell|ms-|2020.6.0
rewrap|stk|1.13.0
vscode-sftp|sun|1.1.1

</details>

**Comment by Tyriar** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

Thanks for understanding.
