### ISSUE TITLE
Debugger does not show strings with tabs/newlines etc correctly

### ISSUE THREAD

**Issue by greggman** [microsoft/vscode#105552]
Issue Type: <b>Bug</b>

## Steps to reproduce

1. put this code in test.js

```
const s = "abc\ndef";
const t = "abc\\ndef";

debugger;
```

2. Debug with node.js option
3. hover over `s` and `t` and view them in "VARIABLES"

## What should happen:

They should show as different

## What happens instead

They show as the same

![miUprCpt5e](https://user-images.githubusercontent.com/234804/91521213-1e0c9880-e932-11ea-8e05-8783593c0198.gif)

note on the far left as well

Compare to Chrome's devtools

![Ibh9lcA3my](https://user-images.githubusercontent.com/234804/91521186-1220d680-e932-11ea-8121-be1400f64d75.gif)

note on the far right as well

I thought I was going crazy trying to debug my code and the debugger showing me the strings as the same

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900XT 12-Core Processor            (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (48.07GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by weinand** [comment]
@connor4312 the old node debuggers show this:

<img width="211" alt="2020-08-28_14-54-00" src="https://user-images.githubusercontent.com/1898161/91562944-531ee800-e93e-11ea-8522-b8aa4069005e.png">

a missing ending quote is an indication that there are multiple lines.

And the hover shows multiple lines:

<img width="167" alt="2020-08-28_14-55-28" src="https://user-images.githubusercontent.com/1898161/91563068-89f4fe00-e93e-11ea-8705-c9c539cb793f.png">

And js-debug shows this:

<img width="129" alt="2020-08-28_14-57-38" src="https://user-images.githubusercontent.com/1898161/91563279-e2c49680-e93e-11ea-8b24-c258cd0d6726.png">

which is a problem.

I like the devtools approach...

**Comment by connor4312** [comment]
> a missing ending quote is an indication that there are multiple lines.

This is actually an artifact of https://github.com/microsoft/vscode/issues/73845#issuecomment-577607174

> I like the devtools approach...

It looks like the devtools 'beautifies' the string, which also destroys some escaped characters. I don't like this approach -- I want to see exactly what my string contains. Particularly important when doing string-manipulation-type tasks.

![](https://memes.peet.io/img/20-08-43f5ebd7-e2a7-40c9-8ee9-df517c7dfb05.png)

Instead I have just updated js-debug to show backslashes as escaped in its previews:

![](https://memes.peet.io/img/20-08-cc411565-c66b-4610-b809-729f008758c8.png)
