### ISSUE TITLE
Notebook output cell "Show more" button has low opacity

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#105595]
Issue Type: <b>Bug</b>

1. Use GItHub Issues Notebook and a .github-issues, run a query that returns many issues

The show more button has low opacity and looks almost like it's disabled:

![Screen Shot 2020-08-28 at 8 26 31 AM](https://user-images.githubusercontent.com/3672607/91585078-6c0ca680-e908-11ea-9181-c6442b631732.png)

VS Code version: Code - Insiders 1.49.0-insider (b58f4549b2919fa3a5dc52df83f4ba60780c625f, 2020-08-27T05:39:40.559Z)
OS version: Darwin x64 18.7.0

**Comment by RMacfarlane** [comment]
It looks like it's still a lower opacity than other buttons - instead of changing that on hover/focus, how about applying `background: var(--vscode-button-hoverBackground)`?

**Comment by connor4312** [comment]
Yea, good idea, I must have fixed this before I had my 🍵
