### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by debashishpatel** [microsoft/vscode#105521]
We have written the needed data into your clipboard because it was 
Issue Type: <b>Performance Issue</b>

whenever i am opening the vscode some kind of lines are appearing without any reason 

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   112	 13036	code main
    0	    60	  2900	   window (Issue Reporter)
    0	    26	  3536	   utility
    2	   144	  9916	   gpu-process
    0	    13	 10156	   electron-crash-reporter
    0	    11	 12104	   C:\Users\DEBASH~1\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-a0479759d6e9ea56afa657e454193f72aef85bd0.exe /verysilent /update="C:\Users\DEBASH~1\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-a0479759d6e9ea56afa657e454193f72aef85bd0.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	    38	  2952	     "C:\Users\DEBASH~1\AppData\Local\Temp\is-VCJNG.tmp\CodeSetup-stable-a0479759d6e9ea56afa657e454193f72aef85bd0.tmp" /SL5="$2E04E6,57616694,828416,C:\Users\DEBASH~1\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-a0479759d6e9ea56afa657e454193f72aef85bd0.exe" /verysilent /update="C:\Users\DEBASH~1\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-a0479759d6e9ea56afa657e454193f72aef85bd0.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	   151	 13184	   window (main.dart - flutter - Visual Studio Code)
    0	     4	  3880	     C:\WINDOWS\System32\cmd.exe
    0	    11	  5852	     watcherService 
    0	    11	  9104	       console-window-host (Windows internal process)
    0	     5	  7832	     console-window-host (Windows internal process)
    0	    96	  7872	     extensionHost
    0	     4	 10808	       C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\src\flutter\bin\flutter.bat" "daemon""
    0	   128	  9480	         "C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe"  --disable-dart-dev --packages="C:\src\flutter\packages\flutter_tools\.packages"  "C:\src\flutter\bin\cache\flutter_tools.snapshot" "daemon" 
    0	    11	 17024	         console-window-host (Windows internal process)
    0	     4	 16464	       C:\WINDOWS\system32\cmd.exe /d /s /c ""C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe" "C:\src\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot" "--client-id=VS-Code" "--client-version=3.13.2""
    0	   304	 11768	         "C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe"  "C:\src\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot" "--client-id=VS-Code" "--client-version=3.13.2"
    0	    11	 14028	         console-window-host (Windows internal process)
    0	    34	  9636	     searchService
    0	    73	 16528	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (main.dart - flutter - Visual Studio Code)
|    Folder (flutter): 125 files
|      File types: png(23) xml(10) plist(4) json(3) gitignore(3) gradle(3)
|                  properties(3) xcconfig(3) iml(2) md(2)
|      Conf files:;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.13.2
flutter|Dar|3.13.2
code-runner|for|0.11.0
cpptools|ms-|0.29.0

</details>
too large to send. Please paste.

**Comment by RMacfarlane** [comment]
@debashishpatel Please provide steps to reproduce this problem. What kind of lines do you mean? Can you include a screenshot? Does this happen with every folder you open? Does this happen when extensions are disabled?
