### ISSUE TITLE
Incorrect number of unsaved files shown after rename symbol

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10556]
- VSCode Version: 1.4
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file
2. Rename a symbol that is used in other files

Other files that referenced it are opened and show as dirty in tabs, the file list and the count on the explorer badge, but it still says "1 unsaved" next to the "open editors" heading.

![Incorrect unsaved files count](https://cloud.githubusercontent.com/assets/1078012/17674704/9bee7276-631e-11e6-8885-04c025a8c306.png)

**Comment by bpasero** [comment]
@isidorn can you look into this?

**Comment by ramamurthynagaraj** [comment]
Hi guys, submitted a PR for this issue. Please let me know if there are any issues.

**Comment by bpasero** [comment]
@isidorn I think any unread indicator needs to react to events from the text file service and not the stacks model to find out that something got dirty. You might want to revisit this in openEditorsView.ts

**Comment by isidorn** [comment]
Thanks! @ramamurthynagaraj
