### ISSUE TITLE
Per OS settings

### ISSUE THREAD

**Issue by steveoh** [microsoft/vscode#105545]
Code setting sync has [sync pragmas](https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas#per-os) that allow you do do the following

```json
{
  // @sync os=linux
  "window.zoomLevel": "1"
}
```

This would be a great feature to support as I believe many people from code setting sync were using it and that will help adoption.

**Comment by sandy081** [comment]
/duplicate

#5595
