### ISSUE TITLE
Communicate an extension's deprecated status

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#10551]
The Marketplace is adding functionality to deprecate extensions. 

We'll want to indicate something to the user in product. Something like

> This extension is deprecated and is no longer maintained, however, you are free to continue using it. 

@joaomoreno any way you would change the messaging? any thoughts on the UI? 

I was thinking something along these lines. 

![image](https://cloud.githubusercontent.com/assets/2449568/17671063/d05ab8e4-62c9-11e6-9185-78350e659a33.png)

Ping @hamenon

**Comment by AkashGutha** [comment]
How about a deprecation badge update ? 

this should remove the necessity of manually checking the extensions every time.

![untitled](https://cloud.githubusercontent.com/assets/10159531/17673105/43ed7648-633d-11e6-993a-f8bafbdb03d9.png)

**Comment by joaomoreno** [comment]
@waderyan We should probably also add a decoration to the extension in the list, not only in the _editor_. I'd make it less prominent, yet still catchy. I can sketch something up.

@AkashGutha I'd not make it into a _badge notification_ since it's not really urgent to the user.

**Comment by waderyan** [comment]
From MP mail it looks like there is no difference to them between unpublish and deprecate. This means we can keep `vsce` the same, as the language is a sufficient warning. 

```
read(`This will FOREVER delete '${ fullName }'! Are you sure? [y/N] `)
```

A UI change here will communicate the `unpublish` status. 

>  I'd make it less prominent, yet still catchy. I can sketch something up.

Sounds great.

**Comment by waderyan** [comment]
FYI - this is what Atom does. 

![image](https://cloud.githubusercontent.com/assets/2449568/18069805/4d157754-6dfe-11e6-9842-0a99d41f5d6f.png)

**Comment by waderyan** [comment]
Ping @hamenon

Note:
API will provide an `unpublished` flag in the JSON response
Marketplace will use the language of "unpublished" so to stay consistent we should use "unpublished" and not use "deprecated."

**Comment by joaomoreno** [comment]
So... when people search for extensions, the _unpublished_ ones will still appear in the results?

**Comment by hamenon** [comment]
The API will still give all extension in the result. The ones that are unpublished will include an unpublished flag as Wade mentioned. On the website we have logic to not display an extension in the results if it is unpublished. Ideally I think we should do so for the search on the editor side of things as well so that the results are consistent across the site and the editor.

**Comment by waderyan** [comment]
@hamenon can you provide the exact syntax of the unpublished flag so we can get this in on our end?

**Comment by hamenon** [comment]
In the extension query response there is a field called flags for each extensions. If an extension is unpublished the word "unpublished" will be present in the flags. 
Ex: flags picked from another extension `"flags": "validated, public, unpublished",`

**Comment by joaomoreno** [comment]
Thanks!

**Comment by joaomoreno** [comment]
@hamenon Is there any way I can query for all non `unpublished` extensions?

**Comment by joaomoreno** [comment]
@hamenon Ping. Today's the last chance we could get it in the September release.

**Comment by AkashGutha** [comment]
@joaomoreno as @hamenon said . it would better to implement the same kind of filtering on client side since the API doesn't provide a way to filter data on server side.

**Comment by joaomoreno** [comment]
That's not so great.

Client filtering works terribly in a paging UI. If the server says there are 10000 items, and we render a paging view for 10000 items, and it turns out that 100 need to be filtered out, how will they render when coming into view? An empty rectangle? An _uninstallable_ extension?

Additionally, why would the server waste its time collecting and sending us data for which we have no use?

Server-side filtering is necessary for this to happen.

**Comment by AkashGutha** [comment]
@joaomoreno yes ! that is true. but the feature to be implemented this would be the only way till the visualstudio marketplace code is fixed.

Can't we do the filtering before rendering the UI.  that should do the work.
Check each extension for unpublished flag, only add to the collection if it is is published.

**Comment by hamenon** [comment]
Copying @modigrv response here as well.
We can query to get just the published extensions, ie. exclude unpublished extensions.

For every extension which is unpublished, has a flag named Unpublished (0x1000).
In the extensions query we have made a separate filter named ExcludeWithFlags ( FilterType : 12) with value as the flag value to be excluded (Integer equivalent in string form) as “4096”, or if there are multiple flags to be excluded OR all of them and then use that integer value as value for the filter.

I think for your case only the FilterType : 12 and value : “4096” will do the work and exclude all extensions which are marked with unpublished flag.
