### ISSUE TITLE
Getting this issue suddenly/

### ISSUE THREAD

**Issue by ferozstk** [microsoft/vscode#105599]
Suddenly crashing VS code without any reason. It's really too disgusting to work with. Please solve this issue from mac.

![image](https://user-images.githubusercontent.com/41797881/91589656-ecb8ba80-e97b-11ea-86c1-1d3929d6c9b0.png)

**Comment by deepak1556** [comment]
Which version are you seeing the crash ?

Does it repro if you use the insiders version https://code.visualstudio.com/insiders

Launch with `--crash-reporter-directory <some-absolute-path>` and if it crashes, provide the crash dump generated at the directory location. Thanks!
