### ISSUE TITLE
Freeze and Crash with 100% CPU usage

### ISSUE THREAD

**Issue by BG-dotcom** [microsoft/vscode#105535]
Issue Type: <b>Bug</b>

I downloaded Visual Studio Code for Mac today, and just using it for basic text editing for SQL, it has frozen up, spiked my CPU at 100% each time, requiring me to Force Quit the application, or even restart my MacBook.  The first time it froze it crashed my machine and I had to reboot everything.  Please advise on how to fix this.  I like the app when it works.  The only real feature I need is block/column select, so this should not be happening.  

Brian

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 6|
|Memory (System)|16.00GB (3.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by deepak1556** [comment]
Can you check if the issue happens with insiders version https://code.visualstudio.com/insiders/

If it still continues, can you take a sample of the process following

* Open Activity Monitor
* Find the Code process that has high cpu usage
* Double-click on the row
* Click the Sample button in the process's information window

**Comment by BG-dotcom** [comment]
Thank you I will try the Insiders version.  Will let you know if issue persists.  Thanks again

**Comment by BG-dotcom** [comment]
Hi all -thanks for the follow up on this, but I think I am good now.  We can close this out.  Thanks again!
