### ISSUE TITLE
vscode suddenly  automatically generates dist dir and copies the file into dist dir

### ISSUE THREAD

**Issue by guglo** [microsoft/vscode#105514]
- VSCode Version:
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

- OS Version:
MacBook Pro (16-inch, 2019)

Steps to Reproduce:

Note: it was fine before, it just happened a couple days ago. I suspected some new updates caused it. I am trying to find a way to disable it. But I could out. 

1. modify a java script in the folder and save it
2. dist dir will appear at the same folder and the saved java script file will be copied to the dist folder
3. the duplicate files will cause problem for running angular...I have to manually delete the dist folder and restart angular. 

Does this issue occur when all extensions are disabled?: Yes/No
I am not using command line. I don't know how to disable extension.

**Comment by mjbvz** [comment]
This can only happy if you have a compile task/script running or if an extension is doing this. Have you started a compile script?

**Comment by guglo** [comment]
@mjbvz  I am running grunt serve which runs angularjs code.  The problem is it was ok a couple days ago...it suddenly happens out of no where.

**Comment by guglo** [comment]
@mjbvz  if I manually change the code outside vscode, there is no issue. I didn't update or install anything lately unless vscode updates automatically.

**Comment by mjbvz** [comment]
VS Code's built-in JS/TS support does not compile TypeScript code so this must be caused by angular `serve` script or some other script you are running. 

Try figuring out exactly which script is causing this and either disabling or re-configuring it

**Comment by RodeoNate** [comment]
I had this [compile hero](https://github.com/Wscats/compile-hero) vscode plugin that was causing the issue for me.
