### ISSUE TITLE
client_id created on each launch in project's root

### ISSUE THREAD

**Issue by furai** [microsoft/vscode#105519]
Issue Type: <b>Bug</b>

Hey,

Whenever I open visual studio code `client_id` file gets created. It didn't behave like that yesterday and I can't figure out what has changed since yesterday.

Cheers,
Furai

VS Code version: Code - Insiders 1.49.0-insider (b58f4549b2919fa3a5dc52df83f4ba60780c625f, 2020-08-27T06:48:09.328Z)
OS version: Linux x64 5.8.4-050804-generic

<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
gitlens|eam|10.2.2
go|gol|0.16.1
twig-language-2|mbl|0.9.2
dotenv|mik|1.0.1
python|ms-|2020.8.103604
cpptools|ms-|0.29.0
php-docblocker|nei|2.1.0
laravel-blade|one|1.22.1
glassit|s-n|0.2.2
twig|wha|1.0.2

</details>

**Comment by RMacfarlane** [comment]
@furai Where is this file being created? Does this happen when all extensions are disabled?

**Comment by furai** [comment]
`client_id` file contains some hash, which is different each time it gets recreated.
`55b99d39-0f97-41e3-828a-b8e683420dee`

I'm going into project folder, by opening it via command line. 
I first cd into the folder and then open it directly from there:
```bash
cd /path/to/project/
code-insiders ./
```
I've just investigated and if I open it from within project root like this the client_id gets created.
What's more curious is that if I do it a bit different, like: 
```bash
cd /path/to/
code-insiders project/
```
Then the `client_id` still gets created, but not in the project's folder but one level below. Like it's created in current working directory when executing `code-insiders`.
If I just run the code-insiders via shortcut then the `client_id` gets created in my home folder. Same when I run it via cmd line without any parameters.

Also like you have requested I've just tested without extensions enabled by running `code-insiders --disable-extensions`. 
All extensions were successfully disabled but `client_id` file still got created.

I hope this is enough information to reproduce my issue.

**Comment by weinand** [comment]
Most likely one of your installed extensions created this `client_id` file.
Please disable all extension and see whether the file is still created.
If not, enable extensions one-by-one and try to find the creator of the file.

**Comment by furai** [comment]
> Also like you have requested I've just tested without extensions enabled by running code-insiders --disable-extensions.
All extensions were successfully disabled but client_id file still got created.

Like I said above, I've disabled all the extensions and issue was still happening. The only thing different that I have recently done is maybe try to open file on remote (github). Other than that it might have been code-insiders recent update.

**Comment by racingicemen** [comment]
Seeing the same behavior on Arch Linux: client_id gets created in the folder from where code-insiders is launched. Each folder has a different hash in client_id. Also noticed the file is created only upon exiting Visual Studio Code.

**Comment by CalvoM** [comment]
I am having the same issue. I am using Ubuntu 20.04 code-insiders  **Version: 1.49.0-insider**

**Comment by yushijinhun** [comment]
I found `client_id` file created by vscode in my home directory. All extensions are disabled.

Audit log:
```
type=PROCTITLE msg=audit(08/31/2020 04:54:32.444:299) : proctitle=/usr/share/code-insiders/code-insiders --inspect-port=0 /usr/share/code-insiders/resources/app/out/bootstrap-fork --type=extensi 
type=PATH msg=audit(08/31/2020 04:54:32.444:299) : item=1 name=client_id inode=2311170 dev=00:1a mode=file,664 ouid=yushijinhun ogid=yushijinhun rdev=00:00 nametype=CREATE cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=PATH msg=audit(08/31/2020 04:54:32.444:299) : item=0 name=/home/yushijinhun inode=80311 dev=00:1a mode=dir,750 ouid=yushijinhun ogid=yushijinhun rdev=00:00 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(08/31/2020 04:54:32.444:299) : cwd=/home/yushijinhun 
type=SYSCALL msg=audit(08/31/2020 04:54:32.444:299) : arch=x86_64 syscall=creat success=yes exit=62 a0=0x7fffba009ca8 a1=0666 a2=0x20 a3=0x7fffba00958d items=2 ppid=14480 pid=14511 auid=yushijinhun uid=yushijinhun gid=yushijinhun euid=yushijinhun suid=yushijinhun fsuid=yushijinhun egid=yushijinhun sgid=yushijinhun fsgid=yushijinhun tty=(none) ses=1 comm=code-insiders exe=/usr/share/code-insiders/code-insiders key=(null) 
```

code-insiders version: 1.49.0-1598635026

**Comment by weinand** [comment]
For an explanation please see https://github.com/microsoft/vscode/issues/105743#issuecomment-683865682
