### ISSUE TITLE
Add delay to autosave

### ISSUE THREAD

**Issue by tonyeung** [Microsoft/vscode#1055]
I have a watch on my source files and while autosaving is great, every change triggers the rebuild process which is pretty crazy. Is it possible to have autosave wait till i stop typing(pause > configurable time) like search box debouncing.

**Comment by egamma** [comment]
There is a delay. I think what you are looking for is a less aggressive auto save, i.e., only on focus lost?
You know that you can also turn off auto save.

**Comment by b12k** [comment]
Also related with: https://github.com/Microsoft/vscode/issues/353

**Comment by tonyeung** [comment]
@egamma yes, but what i mean is more like a save when idle, where the idle period is configurable. For example, autosave is triggered 10 seconds after I stop typing. 

I currently have auto save turned off, but I miss not having to worry about saving. 

@b12k save on focus would also work. A combination of both would be best :D

**Comment by tonyeung** [comment]
@b12k  found an interesting line of code:

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/options.ts#L43

	/**
	 * A number indicating the auto save delay in ms. A time of -1 indicates that
	 * auto save indicates that auto save is turned off completly.
	 */
	autoSaveDelay?: number;

**Comment by bpasero** [comment]
I am making progress on this feature request. I would like to avoid showing the dirty indication in the workbench at all cost because imho that is distracting. However this means, if you have configured auto save delay to be 10 seconds, the file will not be saved after that time without indication to the user. Any feedback on this is appreciated.

**Comment by tonyeung** [comment]
@bpasero I don't know if any indication is needed. This setting isn't something most people are going to change, I think. Those who do make the change should be aware that there is a delay.

If some sort of indication is really needed, perhaps something along the lines of number of dirty files? It would be similar to how the git icon has the number of modified files. The number of modified files sets a precedent. So, its not as if it would get any more distracting for anyone who thinks the dirty dots are.. uh.. dirty.

**Comment by bpasero** [comment]
I just find it interesting that other editors seem to keep all dirty indicators but save after some condition. That is not really a benefit to me, I really like that I also do not have to see any dirty indicators whatsoever because the application takes care of it.

**Comment by bpasero** [comment]
The delay is now configurable from the new `files.autoSaveAfterDelay` setting.

**Comment by tonyeung** [comment]
@bpasero  thanks! this will be in the January release?

**Comment by bpasero** [comment]
@tonyeung yes!
