### ISSUE TITLE
Multiple linux shell path as fallback

### ISSUE THREAD

**Issue by pankaj-webkul** [microsoft/vscode#105574]
I personally use ZSH. There are times I need to launch remote ssh VS Code, where ZSH is not installed.
It would be great, if like fonts, I could set multiple shells.

`"terminal.integrated.shell.linux": "'/bin/zsh','/bin/bash','/bin/sh'"`

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/45444

You can use this extension in the meantime https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
