### ISSUE TITLE
Notebook Text Model Edit API debt

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#105523]
Currently the `NotebookTextModel` has two sets of API

* `applyEdits` which applies edits from the extension host currently. It supports `Undo/Redo`.
* `insertNewCell` which handles cell insertion. It supports `Undo/Redo`.
* `moveCellToIdx`/`removeCell` handles edits from view model but doesn't handle `Undo/Redo` (managed by ViewModel)

We should use `applyEdits` only which handles edits from all sources (multi extension host and UI) and also handle Undo/Redo.

**Comment by jrieken** [comment]
@rebornix Came to the conclusion that `replaceCells` is enough to represent insert and remove but not "move", right?

**Comment by rebornix** [comment]
Didn't make decision yet if "move" should just a `replace` or stay what it is now.
