### ISSUE TITLE
Scrolling and focused coding area idea. (Keeping your coding centered)

### ISSUE THREAD

**Issue by hiredtocode** [microsoft/vscode#105540]
Not sure if this feature is available in other text editors but I was thinking about scrolling while coding and when you scroll your code with arrow keys.

Basically this is the idea: When we code and our code hits the bottom of our screen or when it's floating on top of the built in terminal. We usually hit `enter` a couple of times to make our code portion move up and either use our up arrow key or grab our mouse to go back to where we were coding OR we grab our mouse and scroll down to create space underneath our coding line so that our active coding line has some room to breath down there right? 

But what if we have a setting where we can set an amount of lines from the bottom of the window OR top bar of the panel so that our coding line always stay above the set amount of lines in the settings?  This way, we NEVER have to purposely make lines underneath. This will also help our posture while coding for hours since when we get zoned, our eyes will always look "above" the threshold. =)

Also, while we're at it, I think it'll be good to add a setting for the up or down arrow buttons as well so that they function like the mouse wheel. 

What do I mean by this? 

You know how when we're scrolling the page up and down to navigate? Our cursor has to hit the very top of the screen OR very bottom of the screen to reveal the next line. But when we scroll with our mouse wheel, the cursor doesn't have to move out of place(not saying I want this but emphasizing the idea here) but rather, when we scroll with our up or down keys; it will travel only so far to the top or to the bottom before scrolling starts to happen. Think of it as a margin or padding which scrolling effect gets activated when the cursor hits that line. 
This way we will be saving a few seconds each time we're scrolling with our up and down arrow keys.

Let me know if you want me to make a picture or a short video explaining my idea. I'll be more than glad to provide. 

Thanks for reading all the way to the end and let me know what you think!

**Comment by RMacfarlane** [comment]
Hi @hiredtocode, there's a setting called `editor.cursorSurroundingLines` that sounds like what you're describing. Does that do what you want?

**Comment by hiredtocode** [comment]
@RMacfarlane Holy molly oh my baby!! that's EXACTLY what I wanted LOL Thanks!!
