### ISSUE TITLE
Ignore pycodestyleArgs do not work with more than one rule

### ISSUE THREAD

**Issue by felipeor93** [microsoft/vscode#105500]
Issue Type: <b>Bug</b>

I'm trying to ignore some rules from PEP8 and the command "python.linting.pycodestyleArgs": ["--ignore=E501", "--ignore=E402"] cannot work for both E501 and E402 rules, for example.

I'm only able to ignore one rule? Why?

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
git-graph|mhu|1.25.0
python|ms-|2020.8.103604
vscode-todo-highlight|way|1.0.4

</details>

**Comment by RMacfarlane** [comment]
Hi @felipeor93, please reopen this issue on the Python extension: https://github.com/Microsoft/vscode-python
Thanks!
