### ISSUE TITLE
Trusted Types compatibility: use DOM API for creating HTML elements instead of string concatenation in inspectEditorTokens.ts

### ISSUE THREAD

**Issue by annkamsk** [microsoft/vscode#105509]
The next step in resolving #103699. Simirarly to #105501, it aims to replace construction of HTML elements by string concatenation in `src/vs/editor/standalone/browser/inspectTokens.ts` file. The code contains mainly a table construction by concatenating strings of `<tr><td class=”foo”>foobar</td><td class=”bar”>barfoo</td></tr>`. The goal is to replace them all with `dom.ts#$` function calls.

**Comment by aeschli** [comment]
I verified by running the monaco editor from source and testing the inspect token hover

**Comment by aeschli** [comment]
To verify, open the `Inspect Editor Tokens and Scope` hover and verify it looks all proper.
