### ISSUE TITLE
How to prevent code changes while using beautify command

### ISSUE THREAD

**Issue by AkashGutha** [Microsoft/vscode#10553]
when working with the repository in vscode by using the command  

> shift+alt+f => editor.action.format

makes changes to code that are not inline with the repository coding guidelines .
especially when a PR needs to be made, it shows lot of changes. especially in huge files.

How to counter this?

**Comment by alexandrudima** [comment]
@AkashGutha Do you mean that the vscode sources files are not formatted or that the formatter edits them in a wrong way?

**Comment by AkashGutha** [comment]
1. I cloned vscode repo and opened up a file.
2. I made some minimal changes.
3. Used the **beautify** command to beautify.
4. This creates a lot of changes.
5. This created problem 
6. when you do a PR the actual changes are lost in the ocean of small changes.

Example from another repo :
The red part is the actual changes made but there are many other changes due to beautify command.

My Question is how to avoid this still using beautify command?

![untitled](https://cloud.githubusercontent.com/assets/10159531/17692627/60361ae6-63b8-11e6-8820-81b739a12202.png)

**Comment by alexandrudima** [comment]
You could select only the relevant code in the diff editor and use `Stage selected lines`. Then only the edits you wish will be staged and you can clean the unstaged parts. 

This brings up the discussion if we should format/beautify all our sources. (fyi @egamma)

**Comment by AkashGutha** [comment]
That doesn't seem fair enough.
Do a push and then just sit and modify the whole file.

i think beautifying the whole project must do the trick.

**Comment by alexandrudima** [comment]
:+1: I brought it up for discussion in today's stand-up. No concrete action yet.

**Comment by AkashGutha** [comment]
@alexandrudima good to hear.

**Comment by chris-gunawardena** [comment]
@AkashGutha You can highlight the code you modified and then press `shift+alt+f => editor.action.format`, this will only beautify the highlighted code.

**Comment by egamma** [comment]
Closing this issue we have added a commit hook to format the changed files using the `typescript-formatter` module.
