### ISSUE TITLE
Keyboard cannot enter characters

### ISSUE THREAD

**Issue by gumuming** [microsoft/vscode#105570]
VSCode Version: 1.48.2
OS Version: Windows_NT x64 10.0.19041

When writing code, the keyboard suddenly cannot enter characters
occur frequently，Seriously affect development efficiency

**Comment by jsburckhardt** [comment]
I'm having the same issue
OS Version: Ubuntu 20.04.1 LTS
I did a clean install of VSCODE and I'm having the same issue. Read different articles and they suggest can be an extension... but even when I start VSCODE without extension most keys don't work ... is driving me crazy :S

**Comment by aeschli** [comment]
When you get this, what about other applications? Do they still react to input?

**Comment by jsburckhardt** [comment]
My issue was happening only in vscode. But I figured it out. I had Ubuntu Accessibility on, after disabling it everything went back to normal.
