### ISSUE TITLE
VScode hangs when click on link in terminal

### ISSUE THREAD

**Issue by major697** [microsoft/vscode#105568]
- VSCode Version: 1.48.2
- OS Version: Windows 10 Home ver. 2004

![image](https://user-images.githubusercontent.com/18541212/91545079-e6492500-e920-11ea-90a8-645ac0dcae77.png)
My terminal is Github bash
When I write `git status` I have list of files. When I click on e.g `assets/scss/components/forms/eventForm.scss` terminal and VScode hangs. I waiting 1-2 minutes and VSCode show me info about reopen VScode.

**Comment by Tyriar** [comment]
I can't repro this, a bunch of link-related changes just went in so you could try insiders 1.50 which will be out in a few days (the day after the next stable version 1.49 goes out.

**Comment by major697** [comment]
Hi @Tyriar I check again this error and:
when I hold `ALT` and click left mouse, then I cant write enything in terminal, and when I click `kill terminal` the all VScode is hanging. And VSCode show alert to reopen.

Now I have VSCode in version: 1.49.1

**Comment by Tyriar** [comment]
Hanging when closing terminals is a known issue: https://github.com/microsoft/vscode/issues/76548

**Comment by rzhao271** [comment]
@major697 can you try using ctrl+click to follow links, and seeing if that helps?
Alt+click has an issue https://github.com/microsoft/vscode/issues/101136

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/108734
