### ISSUE TITLE
No option to disable Configure Java Runtime window from appearing when opening .java file

### ISSUE THREAD

**Issue by cnmoise** [microsoft/vscode#105515]
- VSCode Version: 1.48.2
- OS Version: Windows_NT x64 10.0.17763

Issue:
There is no option to disable the Java configuration warning of VSCode and it can't detect when Java has been installed on a remote host so the warning never goes away.

Suggestion: add a checkbox similar to the welcome page that disables the behavior that opens the Configure Java Runtime window when opening a Java file for situations where Java isn't detected on a remote system.

Steps to Reproduce:

1. Use SSH extension to connect to remote host
2. Open a .java file

Does this issue occur when all extensions are disabled?: No - because this is untestable without extensions

**Comment by weinand** [comment]
Since VS Code does not have any built-in Java functionality, it cannot post a Java configuration warning.
