### ISSUE TITLE
Right arrow is not working on editor

### ISSUE THREAD

**Issue by reijovosu** [microsoft/vscode#105583]
- VSCode Version: Version: 1.49.0-insider
Commit: bd2a40195f1c904a0cc0dd161371c0e3e3957052
- OS Version: Mac OS 11.0 Beta (20A5354i)

Steps to Reproduce:

1. With default shortcut map. Right arrow is not working

Does this issue occur when all extensions are disabled?: Yes/No Have not tried

Right arrow is not working in editor when shortcut "Notebook: Unfold Cell" is also marked as right arrow.

**Comment by ThiefMaster** [comment]
Same problem for me, I can confirm that removing this particular shortcut fixes it.

**Comment by IAmHopp** [comment]
Instead of removing it, using the same `when` that's used for the Fold Cell shortcut also fixed the issue.

**Comment by bpasero** [comment]
/duplicate https://github.com/microsoft/vscode/issues/105576

We since released a new insiders that contains a fix.
