### ISSUE TITLE
[Request] Use an icon other than "C" for ".h" files

### ISSUE THREAD

**Issue by Colengc** [microsoft/vscode#105533]
It could be confusing to C++ users to see "C" associated with their ".h" files.  (We had this bug opened against the C/C++ Extension: https://github.com/microsoft/vscode-cpptools/issues/5667 )

![image](https://user-images.githubusercontent.com/10354649/91496454-facde480-e870-11ea-9368-0edc4f326a36.png)

(i.e. test.h and header.h)
Perhaps an "H" icon could be used for header files instead?

**Comment by aeschli** [comment]
We use the Seti theme as defined by https://github.com/jesseweed/seti-ui and the Seti theme has defied the purple C for `.h` file.
You can file an issue there.
