### ISSUE TITLE
please allow a filter on not installed extensions too

### ISSUE THREAD

**Issue by t2kx** [microsoft/vscode#105564]
Issue Type: <b>Feature Request</b>

now you can only filter on the installed ones , but the inverse woul be much more interesting , especially in combo with publisher 

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.20197

**Comment by sandy081** [comment]
@t2kx Can you please explain more about what filters you are talking about?

**Comment by t2kx** [comment]
> @t2kx Can you please explain more about what filters you are talking about?

in the extension blade/side bar one can filter on the extensions
![image](https://user-images.githubusercontent.com/37438394/91836459-165b3580-ec4b-11ea-8ed8-ef36a5654bda.png)
please add a filter to also only select the NOT INSTALLED extensions too, e.g. let's say for instance you want to install all extensions by a certain publisher Microsoft. if this publisher has 200 extensions then i'm not interested in the ones I have already installed. I then want to FILTER on the NOT INSTALLED ones, minimizing the list.

**Comment by steve-ross** [comment]
I think this would be handy, I Found this issue by trying to filter by: `@popular !@installed`
