### ISSUE TITLE
Allow copying the extension ID from the extension info view

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode#105504]
When authoring recommended extensions for a project and/or container environment, it would be helpful if we could copy the ID of an extension right from the extension info view. The label is already selectable, and I recall this actually used to work: you could triple click the ID to select all the text (at least in Windows) and press Ctrl+C to copy, though that would copy a terminating new line character that was a bit annoying, but easy to remove. IIRC, this no longer works at the time of opening this feature request (or maybe it's a bug IIRC).

This would mitigate spelling errors getting a recommended environment authored and generally save time.

**Comment by sandy081** [comment]
#102979
