### ISSUE TITLE
Code highlighting color issue for C# for strings containing //

### ISSUE THREAD

**Issue by sen-trenser** [microsoft/vscode#105553]
Issue Type: <b>Bug</b>

The quoted C# string syntax highlighed as a comment string.
`Api.GetObjectFieldValue("(//*[@name='KeyIcon(Clone)'])[0]/Key[fn:component('UnityEngine.UI.Image')]/@color")`

![image](https://user-images.githubusercontent.com/62234705/91523436-6029e000-e91a-11ea-89ba-6d1b374dd667.png)

System Info:

CPUs	Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)
GPU Status	2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
protected_video_decode: enabled
rasterization: enabled
skia_renderer: disabled_off_ok
video_decode: enabled
viz_display_compositor: enabled_on
viz_hit_test_surface_layer: disabled_off_ok
webgl: enabled
webgl2: enabled
Load (avg)	undefined
Memory (System)	7.79GB (1.39GB free)
Screen Reader	no
VM	0%

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
hlsl-preview|A2K|0.9.6
better-comments|aar|2.1.0
shaderlabvscodefree|aml|1.2.0
bracket-pair-colorizer|Coe|1.0.61
vscode-install-vsix|fab|1.4.0
vscode-solution-explorer|fer|0.3.11
code-runner|for|0.11.0
auto-using|Fud|0.7.15
todo-tree|Gru|0.0.178
vscode-edit-csv|jan|0.4.1
csharpextensions|jch|1.3.1
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.18
shaderlabformatter|lit|0.4.0
rainbow-csv|mec|1.7.1
git-graph|mhu|1.25.0
csharp|ms-|1.23.1
vs-keybindings|ms-|0.2.0
shader|sle|1.1.4
code-spell-checker|str|1.9.0
python|tht|0.2.3
hlsltools|Tim|1.1.301
unity-debug|Uni|2.7.5
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|10.2.0

</details>

**Comment by alexr00** [comment]
I'm not able to repro this issue:
![image](https://user-images.githubusercontent.com/38270282/94533878-092c6900-0240-11eb-83e4-9fa9d3e8503c.png)
It is likely caused by one of the extension you have installed.
