### ISSUE TITLE
Support to run web playground in remote env

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#105566]
I'm playing with it on remote host under https and there are different issues like:
- `ws` protocol is hardcoded, although it should be wss if the page is served under `https`
- source maps are not working in Chrome, since they expect `file` scheme. I can work around it by checking out locally the same version, but it is not very convenient.

**Comment by bpasero** [comment]
Since the web playground works fine via HTTPS from https://vscode-web-test-playground.azurewebsites.net/?enter=true what else is there to do?
