### ISSUE TITLE
[show unused]  doesn't work

### ISSUE THREAD

**Issue by sunyum** [microsoft/vscode#105571]
Issue Type: <b>Bug</b>

One of my react projects has lost its [show unused] function,  and unused import is no longer grayed out, but there is no problem opening another project

What may be the cause of this?

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.2.1
vscode-markdownlint|Dav|0.36.3
umi-pro|Dia|0.7.2
githistory|don|0.6.9
xml|Dot|2.5.1
es7-react-js-snippets|dsz|2.8.3
EditorConfig|Edi|0.15.1
vscode-element-helper|Ele|0.5.6
prettier-vscode|esb|5.5.0
auto-rename-tag|for|0.1.4
docthis|joe|0.7.1
vscode-language-pack-zh-hans|MS-|1.48.3
debugger-for-chrome|msj|4.12.10
vetur|oct|0.26.1
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.10

</details>

**Comment by mjbvz** [comment]
Please share some example code

/needsMoreInfo

**Comment by sunyum** [comment]
I have found the cause of this problem
tsconfig.json ->  "noUnusedLocals": true,

I set "noUnusedLocals":false,   now  unused import is grayed out

**Comment by mjbvz** [comment]
Ok, closing since this sounds like a configuration question
