### ISSUE TITLE
plugin list save function

### ISSUE THREAD

**Issue by fegg** [Microsoft/vscode#10550]
hi, some time recover operator system, re-install vscode.
^-^ now, want to quickly install before plugin. hope can store plugin information.
heihei~

1. account sync plugin information.
2. or have a json config file, can store, after import it can auto install config's plugin json list.

== it is idea~thanks vscode.

**Comment by joaomoreno** [comment]
Maybe this helps? https://marketplace.visualstudio.com/items?itemName=golf1052.code-sync
