### ISSUE TITLE
WorkspaceConfiguration.get(section, defaultValue) doesn't merge defaultValue

### ISSUE THREAD

**Issue by scottmwyant** [microsoft/vscode#105550]
- VSCode Version: 1.48.2
- OS Version: Windows 10 Home (x64) 1909.18363.1016

**Summary**

[The documentation](https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration) says explicitly that the _effective_ value returned by `WorkspaceConfiguration.get<T>(section: string, defaultValue: T)` is a merge of the inheritance for object value types, overrides for all other types.

Steps to Reproduce:

1. Provide `{a: 1}` as the second parameter of `WorkspaceConfiguration.get<T>(sectionL string, defaultValue: T)`
2. Have `{b: 2}` in your user settings or workspace settings.
3. See the return is {b: 2}, not {a: 1, b: 2} as expected from reading the documentation.

Note that the docs may only be talking about defaults provided in `package.json` but that is not clear.  Is the intent to have the `defaultValue` provided in the API overriden?

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by RMacfarlane** [comment]
The second parameter is used only when no value for the section could be found, i.e. when it is undefined. This documentation is confusing because `defaultValue` is sort of overloaded. In that paragraph it's talking about the default value of the setting from how it is defined by an extension or vscode:
```json
        "githubPullRequests.logLevel": {
          "type": "string",
          "enum": [
            "info",
            "debug",
            "off"
          ],
          "default": "info",
          "description": "Logging for GitHub Pull Request extension. The log is emitted to the output channel named as GitHub Pull Request."
        },
```

If this is an object, it would be merged.

**Comment by RMacfarlane** [comment]
I created an issue to clarify the docs. Thanks!
