### ISSUE TITLE
git "commit-msg" hook isn't called when I commit

### ISSUE THREAD

**Issue by hanhan9449** [microsoft/vscode#105575]
- VSCode Version: 1.48.2
- OS Version: Linux x64 5.8.3-arch1-1

Steps to Reproduce:

1. initial an angular project
2. add "commitlint" support and add angular profile
3. add husky hooks in packages.json
4. try to use a commit that doesn't meet specifications
5. it commits successful but shouldn't
![Peek 2020-08-28 18-28](https://user-images.githubusercontent.com/28822945/91551110-40b3a700-e95c-11ea-9398-0f6a7953283c.gif)

Does this issue occur when all extensions are disabled?: No

**Comment by joaomoreno** [comment]
Does the hook run if you run `git commit` from the terminal?

**Comment by hanhan9449** [comment]
After I reboot the computer, now It works fine. Sorry.
