### ISSUE TITLE
different highlights on win10 and on linux Debian

### ISSUE THREAD

**Issue by ivatih** [Microsoft/vscode#10558]
Why different syntax highlights on win10 and on linux Debian? What happened on linux? Extensions on two computers indentical.

- VSCode 1.4;
- OS win10:

![vscode_win](https://cloud.githubusercontent.com/assets/19560929/17676399/0f8ce2ae-6337-11e6-8bf8-c22930666910.png)

- VSCode 1.4;
- OS Linux Debian "Jessie":

![vscode_linux](https://cloud.githubusercontent.com/assets/19560929/17676429/2e37a2d4-6337-11e6-912b-86d4a9bd71fc.png)

**Comment by alexandrudima** [comment]
@ivatih Are you using the same theme? `F1 > Preferences: Color Theme`. At one point we shipped with Dark (Visual Studio) as the default and then we shipped with Dark+ (default dark) as the default. Depending on when you installed VSCode you might have one or the other even if you didn't touch the theme setting, as the update process maintains the current selected theme.

**Comment by ivatih** [comment]
Please forgive me)) It's stupid question)
