### ISSUE TITLE
Use content hash to decide if a file if dirty indicator should show or not

### ISSUE THREAD

**Issue by ingelity** [Microsoft/vscode#10552]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 14.04

Steps to Reproduce:
1. enter any character or whitespace
2. delete that character or whitespace

Visual Studio Code will now show that the file has changed (i.e. not the same as before making and undoing the changes) even though it's the same as when it was opened, and when u go to git it will not show the file among changed files which is correct since the file is exactly the same. 
This works well in Atom.io.
This is annoying since whenever you try to close such file, the save file dialog will pop up, and also you can't be sure whether file has really changed or not, so you would have to undo all changes with "ctrl + z".

**Comment by AkashGutha** [comment]
I _**counter**_ this by using these user settings

```json
 "files.autoSave": "onFocusChange"
````
or 
```json
"files.autoSave": "afterDelay",
"files.autoSaveDelay": 1000
```

this ensures that the files are saved as soon as you do some edits though you ctrl+z those edits. the important part is you can watch the git icon if there are changes really. for your case using this will ensure the popup will not show up and all changes will be visible from the Git integration.

**Comment by ingelity** [comment]
Thanks for the tip, but I don't want to use the auto saving feature.

**Comment by AkashGutha** [comment]
presently there is no such system to stop those popups since there is no file tracking attached to the editor.

**Comment by alexandrudima** [comment]
The dirty indicator is not content equality based. @ingelity Do I understand correctly that you'd want the dirty indicator to disappear if by subsequent edits you bring the file in the exact same state as you started?

**Comment by AkashGutha** [comment]
@alexandrudima Yes ! @ingelity was exactly talking about that.
if Subsequent edits bring your file back to same state as last saved then vscode shouldn't consider it dirty. Could be a feature but i don't think it's something that everyone would want.

**Comment by bpasero** [comment]
I am not sure this would be confusing users...

**Comment by ingelity** [comment]
How can it be confusing? I really liked this feature of Atom. It's confusing if you are never sure whether you actually made some changes to a file or not, and it could be even considered a bug because if an editor asks me whether I want to save my changes then I would expect to see those "changes" in git diff, but of course git wouldn't show anything since there are no changes. 
If you think that it would be confusing to users then you can make it an optional choice in the settings, although everyone I worked with think this is a great feature.

**Comment by glen-84** [comment]
Related: https://github.com/Microsoft/vscode/issues/919
