### ISSUE TITLE
settings ui: focus border hidden under tree

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#105580]
- open the settings ui in the dark+ theme
- enter a search term and focus on the results
-> the focus border is incomplete

![image](https://user-images.githubusercontent.com/6461412/91557581-01259480-e935-11ea-84c8-9ebb6694ee53.png)

**Comment by roblourens** [comment]
This is just from the new settings editor experiment which has rough edges. It won't ship.

**Comment by roblourens** [comment]
Fixed, folding into #106897
