### ISSUE TITLE
Setting sync account Microsoft automatically logout 

### ISSUE THREAD

**Issue by darkRaspberry** [microsoft/vscode#105503]
- VSCode Version:1.49.0-insider
- OS Version:Windows_NT x64 10.0.20190

Steps to Reproduce:

1. To sync setting sign in with Microsoft account. And make a successfully sign in.
2. After correctly setup exit vs-code(insiders) and open Microsoft account is sign out.
3. If not open and close the vs-code some more time to get this error.

Does this issue occur when all extensions are disabled?: Yes

This issue exists from some 10-12 builds I thought it's side effect of insiders rough edge. But now it's seriously irritating.

**Comment by RMacfarlane** [comment]
@darkRaspberry Can you open the output panel, select "Microsoft Authentication", and copy the output here?

**Comment by mareklinka** [comment]
I'm having the same issue and JUST managed to capture the moment it failed:

```
(last evening)

[Info  - 19:44:33.18] Token refresh success
[Info  - 19:44:33.19] Token available from cache, expires in 3598999 milliseconds
[Info  - 19:44:33.19] Token available from cache, expires in 3598999 milliseconds

(this morning - computer went to sleep in the meantime)

[Info  - 06:59:42.269] Refreshing token...
[Error  - 06:59:42.279] Refreshing token failed
[Info  - 06:59:42.279] Logging out of session '[trimmed for brevity]'
[Info  - 06:59:42.280] Refreshing token...
[Error  - 06:59:42.361] Refreshing token failed
[Info  - 06:59:42.361] Logging out of session '[trimmed for brevity]'
```

So it seems like the token has expired, VSCode tried to refresh it twice at the same time, failed both times, then logged me out. I wonder if the computer sleep might play into this?

**Comment by maxklock** [comment]
I have the same issue with the same output as @mareklinka.

Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by darkRaspberry** [comment]
I thought i was only one.
@RMacfarlane Still need me to send output.

**Comment by RMacfarlane** [comment]
Thanks for the output! I'll work on a fix

**Comment by aeschli** [comment]
Are there verification steps that don't require waiting 2 days?

**Comment by RMacfarlane** [comment]
Yes :)

1. Sign into settings sync with a Microsoft account
2. Turn off wifi
3. Reload window
The Microsoft auth provider will take a while to activate as it repeatedly tries to connect and backs off, maybe 30 sec. After that a "Microsoft is currently unavailable" item should appear in the accounts menu

4. Turn wifi back on
Provider should reconnect, and the account should show up in the accounts menu again

**Comment by aeschli** [comment]
Thanks a lot, works!
