### ISSUE TITLE
Add toml front matter support for Markdown

### ISSUE THREAD

**Issue by McShelby** [microsoft/vscode#105517]
As done in [Add yaml front matter support for Markdown](https://github.com/microsoft/vscode/pull/15218) I would request the same feature but for TOML formatted front matter (as used at least in [hugo](https://gohugo.io/content-management/front-matter/#front-matter-formats).

While YAML front matter is printed nicely in the markdown preview, TOML front matter looks - well - unstructured to say at least. 

Everything is better (in my opinion) than to print this unstructured data. Even just hiding the TOML front matter at all from the markdown preview in a first iteration would be much appreciated.

Not quite sure if this belongs to vscode or better should be done in an extension like [Better TOML](https://github.com/bungcip/better-toml)

**Comment by mjbvz** [comment]
Marking as help wanted for basic support (stripping out the front matter)

More advanced rendering belongs in an extension (see [the yaml front matter extension](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-yaml-preamble) for an example)
