### ISSUE TITLE
VS Code asks me to allow a "Helper Tool" on every update

### ISSUE THREAD

**Issue by danzil** [microsoft/vscode#105518]
Issue Type: <b>Bug</b>

It's annoying to have to type an administrator password every time VS Code is updated. I run as a Standard User. Thanks for fixing this, VS Code rocks otherwise!

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.6.0

**Comment by RMacfarlane** [comment]
Sounds like https://github.com/Microsoft/vscode/issues/22363, can you try https://github.com/Microsoft/vscode/issues/7426#issuecomment-425093469
