### ISSUE TITLE
ArrowRight doesn't expand tree node anymore

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105576]
* select a folder in the explorer
* select `ArrowRight`
* :bug: nothing happens

**Comment by jrieken** [comment]
This seems to trigger `notebook.unfold`

<img width="1395" alt="Screenshot 2020-08-28 at 12 38 56" src="https://user-images.githubusercontent.com/1794099/91552051-72604a00-e92b-11ea-9be0-dc7ffebaeada.png">

**Comment by jrieken** [comment]
caused by https://github.com/microsoft/vscode/commit/b4b67b8e7eacafb504e545a05f31a60012df20e7

**Comment by jrieken** [comment]
mitigated via 21ebf4d282accd98b58bc118bff9b38d562309b4

**Comment by bpasero** [comment]
Would be great to have a test for this to prevent this in the future. I.e. testing that the most basic editor commands work via keys.
