### ISSUE TITLE
Can't push changes to GitHub workflows when VS Code has authenticated as OAuth GitHub app

### ISSUE THREAD

**Issue by dgholz** [microsoft/vscode#105546]
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.20197

Steps to Reproduce:

0. Set up VS Code as an OAuth GitHub app so long ago you've forgotten the steps
1. Clone a repo
2. Edit a file in `.github/workflows`
3. `git push` from the terminal
4. Search for the error message
  _refusing to allow an OAuth App to create or update workflow `.github/workflows/hello.yml` without `workflow` scope_
5. Find #97396 and wonder if it was fixed already
6. Help -> Install Update, restart
7. Try again
8. Wonder why there was no prompt to re-authorize VS Code as a GitHub app with the new scope
9. Figure the change from #97396 would be applied when cloning
10. Clone repo to a new location
11. Make the same changes to a file in `.github/workflows/`
12. `git push`
9. Open this issue with the hope someone will share the steps needed to reauthorize the app with the necessary scope

Does this issue occur when all extensions are disabled?: No (but expected as GitHub is an extension)

**Comment by joaomoreno** [comment]
Fixed by https://github.com/microsoft/vscode/issues/97396
