### ISSUE TITLE
Huge .browse.VC.db file

### ISSUE THREAD

**Issue by bharathitman** [Microsoft/vscode#10557]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1. I was working on a simple angular 2 application for a few hours. When I was about to push the code I got an error saying there was this huge file .browse.VC.db (~720 MB in size). I had to add this to git ignore
2. I think I do get the purpose of the file, but is it supposed to be this huge? or is the behavior strange?

**Comment by AkashGutha** [comment]
Had same problems but was 40Mb in size though ?
What is this file about ?

**Comment by alexandrudima** [comment]
It is coming from the C++ extension. Moved the issue over to Microsoft/vscppsamples#150 which is where the C++ extension tracks its issues.
