### ISSUE TITLE
Weird overcaching of code while debugging extensions

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#105512]
- VSCode Version: 1.48.2
- OS Version: Win10 10.0.19041.450

I hit a very strange issue with the wrong code being used when debugging extensions, loaded from cache instead of from the real location.

What I was seeing was my extension failing to activate because a dependency (`LocationListStep.js` from `vscode-azureextensionui`) was trying to `require` a module that wasn't present (`azure-arm-resource`). However, in the code for that dependency, it was actually doing `require('@azure/arm-subscriptions')`--so whatever code had been loaded in the extension host did not match what was actually on disk and was out-of-date.

Eventually I traced things over to `%appdata%\Code\CachedData\baadf00d\LocationListStep-abcd1234.code`. That file was some sort of compiled old version of `LocationListStep.js` with the no-longer-valid `require`. When I deleted that file and tried again, it was regenerated and everything worked fine. I have not been able to reproduce this since.

Is there some reason this could be over-caching like this?

**Comment by weinand** [comment]
Extension debugging doesn't do anything special with regards to caching.

@alexdima or @jrieken are you aware of any caching into `%appdata%\Code\CachedData\baadf00d\LocationListStep-abcd1234.code`?

**Comment by jrieken** [comment]
Yes, that's v8 code caching. You can reverify by starting with `--no-cached-data`

@bwateratmsft What I am wondering is how you got into this issue? Is it when developing an extension or when tweak an installed extension? Also, is there something on the dev tools console that mentions cached data?

**Comment by bwateratmsft** [comment]
Working on developing the Docker extension. One of our dependencies (`vscode-azureextensionui`) just upgraded to the new Azure SDK for JS, and I was working on doing the same.

I updated our references in package.json, then did a `git clean -xfd` before `npm i`, to ensure I was completely removing the old dependencies.

It was extra confusing because when debugging into LocationListStep.js, it showed the new `require('@azure/arm-subscriptions')`, but then errored anyway saying `azure-arm-resource` wasn't found.

**Comment by jrieken** [comment]
Did you see this message in any of the consoles `FAILED TO VERIFY CACHED DATA, deleting stale 'XYZ' now, but a RESTART IS REQUIRED`

**Comment by bwateratmsft** [comment]
I didn't see that but I wasn't looking for it either. I did try restarting VSCode completely (close all windows) before finding that cached file, but that did not have any effect.
