### ISSUE TITLE
Issue with extensionPack and extensionDependency

### ISSUE THREAD

**Issue by shyam-arora** [microsoft/vscode#105511]
**Use case**

test1, test2, test3, test4 are four vscode extensions.

**test3** has extensionPack that contains two extensions **test1** and **test2** as follows.
```
{
	name: 'test3',
	...
	...
	extenstionPack: ["test1","test2"]
	...
}
```

**test4** extension depends on **test2** as follow

```
{
	name: "test4",
	...
	...
	extensionDependency: ["test2"]
	...
}
```
Now, I can't uninstall **test2** because **test4** depends on it, as expected.

**Problem:**
Uninstall **test3** it will uninstall **test1** and **test2**, Uninstallation should not have happened because **test2** depends on **test4**.

![Image](https://user-images.githubusercontent.com/25132374/91467060-a9901600-e8ad-11ea-9fa5-3db6d3c32d11.png)

**Comment by vsjha18** [comment]
I am also facing the issue. It seems that `Extension Packs` are given higher precedence than `Extension Dependencies`. But this doesn't seem right. It can potentially create situations where a given extension can loose its dependencies without user being aware of it. Please take this seriously.

**Comment by sandy081** [comment]
To verify

- Install `sandy081.999-test-pack` extension (packed with `sandy081.999-test-code` extension)
- Install `sandy081.999-test-dep` extension (depends `sandy081.999-test-code` extension)
- Try uninstalling the pack extension and make sure it shows about  `sandy081.999-test-dep` extension depending on `sandy081.999-test-code` extension
