### ISSUE TITLE
Open contextual window

### ISSUE THREAD

**Issue by XVincentX** [Microsoft/vscode#10555]
Is there any way to open a contextual window like `Find all references` and put inside some custom data?

![image](https://cloud.githubusercontent.com/assets/1416224/17673245/99b8153c-6320-11e6-949f-8e26b5e8f6f4.png)

Basically I wrote a test reporter and I'd like to show the results from a CodeLens command, but I cannot find the proper way to do it.

**Comment by jrieken** [comment]
That current not possible. Closing as dup of #3220
