### ISSUE TITLE
When switch config, it would great switch target device automaticly

### ISSUE THREAD

**Issue by jerryzhoujw** [microsoft/vscode#105556]
### Background:

I have a flutter project, which include `multi-flavor` if it run on Android.

So the `.vscode/launch.json` looks like bellow:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter android",
            "request": "launch",
            "type": "dart"
            ,
            "args": [
                "--flavor",
                "someFlavor"
            ]
        },
        {
            "name": "Flutter iOS",
            "request": "launch",
            "type": "dart"
        },
    ]
}
```

It's works when I run on iOS with `Flutter iOS` and run Android with `Flutter android`.

### My feature request:

When I `switch the config` to debug, it would be great the `selected device` can switch between android and iOS(The first image) `auto`, no need to switch it by hand(The second image)

<img width="352" alt="截屏2020-08-28 下午1 58 08" src="https://user-images.githubusercontent.com/6405390/91526896-3e8b2180-e937-11ea-9675-cbb5b1748cd3.png">

<img width="284" alt="截屏2020-08-28 下午1 58 22" src="https://user-images.githubusercontent.com/6405390/91526905-464ac600-e937-11ea-91c6-b9d50b735237.png">

**Comment by weinand** [comment]
This feature would require a new event "onSelectedDebugConfigurationChanged"...

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
