### ISSUE TITLE
New TypeScript files are not part of a tsconfig/jsconfig project

### ISSUE THREAD

**Issue by Yolo-plop** [microsoft/vscode#105584]
- VSCode Version: 1.48.2
- OS Version: Windows 10/64
- TypeScript Version: 3.9.7

Does this issue occur when all extensions are disabled?: Yes

**Related issues**
- https://github.com/microsoft/vscode/issues/50329
- https://github.com/microsoft/TypeScript/issues/33564

Since at least yesterday, newly created files in my Angular projects are not considered part of the TypeScript project. When trying to use absolute part for imports, the linter can't resolve the path, i'm also having issues with functionalities marked as experimental. 

I've been scratching my head on this for a while, finally found that old files are base on my tsconfig.app.json file while with new ones i have the message "Create tsconfig: This file is currently not part of a tsconfig/jsconfig project.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

The insiders build includes a new version of TypeScript

**Comment by Yolo-plop** [comment]
Yes, same issue with the insider version.

**Comment by mjbvz** [comment]
Thanks for testing. Can you share steps to reproduce this? I don't see this in a simple project

**Comment by Yolo-plop** [comment]
I tested on another machine (wsl debian10) and was able to find the step that causes the problem.

sudo apt-get install nodejs
sudo apt-get install npm
npm install -g @angular/cli
ng new test

The file src/app/app.module.ts is part of the project.
Create file src/app/test.ts, it is part of the projet.

Update file tsconfig.base.json and set "baseUrl": "./src/app", the file is no longer part of the project and imports show an error when trying to import using 'app/...' absolute path. But the application compiles fine.

However, adding the setting in tsconfig.app.json (which extends tsconfig.base.json) seems to fix the issue.

So maybe this is by design, but my old files are fine, only new ones show the issue.

**Comment by Yolo-plop** [comment]
I'm going crazy over reproducing this. I've created a new project on another machine.

sudo apt-get install nodejs
sudo apt-get install npm
npm install -g @angular/cli
ng new test

Create file src/app/test.ts, "export class Test { }

File seems ok. Open another file. Come back to test.ts, not part of the project anymore. Created more files, got back to test.ts, it was ok again, new files are not ok.

Now this causes an issue when updating tsconfig.app.json to set src as the root path, which allows to import files using absolute paths. Imports in VSCode will show an error while the project compiles fine. VSCode is not able to read the config file.

**Comment by mjbvz** [comment]
I followed those steps but could not reproduce this issue.

Are you running under wsl on windows? If so, are you using the [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) extension? Or did you open the folder directly somehow?

**Comment by Yolo-plop** [comment]
Sorry, i missed your answer. I am using Remote SSH plugin connected to a Debian 10 machine.
