### ISSUE TITLE
Ctrl + /

### ISSUE THREAD

**Issue by mogles** [microsoft/vscode#105530]
Issue Type: <b>Bug</b>

Select Ctrl + / on large group of code does not toggle the closing parentheses when on it's own line.

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:50:42.600Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-django|bat|0.20.0
django-html|bib|1.3.0
django|big|1.0.2
python-snippets|cst|0.0.8
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
python-coding-conventions|igr|0.0.4
kite|kit|0.122.0
python|ms-|2020.8.103604
python-template-snippets|Ric|1.1.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.0.3
jinja|who|0.0.8

</details>

**Comment by alexdima** [comment]
@mogles What programming language are you using? Can you give a small snippet of source code and an example of the selection you do and what happens vs what you would expect to happen?
