### ISSUE TITLE
Add debug flag in scrollbar

### ISSUE THREAD

**Issue by FarhanMS123** [microsoft/vscode#105577]
Hello.

I had like to have debug flag (such as something color) in the scroll bar. It would make easier to debugging, or flagging a line to find. 

Thankyou.

**Comment by isidorn** [comment]
Use the following setting 
	"debug.showBreakpointsInOverviewRuler": true,

Apart from that we will not add anything else. Thus closing this

**Comment by FarhanMS123** [comment]
Ooh... thanks.
