### ISSUE TITLE
backgrounddownloader.exe

### ISSUE THREAD

**Issue by creationmz** [microsoft/vscode#105520]
Issue Type: <b>Bug</b>

This exe (backgrounddownloader.exe) is annoying in every 30 mins. My firewall can't block this, because it starting different folders every time.

How can I turn it off?

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 1200 Quad-Core Processor            (4 x 3094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (9.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
cpptools|ms-|0.30.0-insiders2
notepadplusplus-keybindings|ms-|1.0.5
platformio-ide|pla|1.10.0

</details>

**Comment by RMacfarlane** [comment]
Not sure if this is from code or an extension, can you try changing the `update.Mode` setting to manual or none? Does this reproduce with extensions disabled?
