### ISSUE TITLE
Code Helper (Renderer) memory leak

### ISSUE THREAD

**Issue by stutommi** [microsoft/vscode#105516]
- VSCode Version: 1.48.2
- OS Version: Darwin x64 18.7.0

I was testing my c-project for leaks, and thought it would be nice to verify that the parent process of VSC-terminal shows clean result. I was confused when I saw this wasn't the case. I'm not sure if leaks command can give false positives, hope someone else can also verify this. :)

Steps to Reproduce:

1. Open visual studio code
2. Navigate to the terminal inside visual studio code
3. run command 'leaks $PPID'

-- OUTPUT OF LEAKS BELOW --
```
Path:            /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)
Load Address:    0x10da52000
Identifier:      Code Helper (Renderer)
Version:         ???
Code Type:       X86-64
Parent Process:  Electron [42776]

Date/Time:       2020-08-27 20:08:11.636 +0300
Launch Time:     2020-08-27 20:06:45.135 +0300
OS Version:      Mac OS X 10.14.6 (18G3020)
Report Version:  7
Analysis Tool:   /Applications/Xcode.app/Contents/Developer/usr/bin/leaks
Analysis Tool Version:  Xcode 11.3.1 (11C504)
----

leaks Report Version: 4.0
Process 42781: 76301 nodes malloced for 15533 KB
Process 42781: 4424 leaks for 702704 total leaked bytes.

(specific leak output continues...)
```

Does this issue occur when all extensions are disabled?: Yes

Additional information:
```
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Comment by deepak1556** [comment]
This would be from the runtime electron , closing as its out of scope.
