### ISSUE TITLE
How to Show Validation Errors while using Custom Language in Editor 

### ISSUE THREAD

**Issue by itskhurram** [Microsoft/vscode#10559]
Hi,
I have added my customer Language in which i have 2 or 3 global functions. I have added the global functions signature and also have defined the keywords & tokenizer. 

Now i am able to highlight the syntax but if my functions signature are not correct the editor did not show any validation errors. Please help.

**Comment by alexandrudima** [comment]
@itskhurram You can use `monaco.editor.setModelMarkers(model, 'markersOwnerId', markers)`.

Here is an example:
* https://github.com/Microsoft/monaco-typescript/blob/master/src/languageFeatures.ts#L111

**Comment by itskhurram** [comment]
but how can i use the diagnostics because i am developing application using angularjs with webapi as backend. Until now what i did is defined my language with some custom keywords and "registerCompletionItemProvider", Above example does not help much. I tired to find any other resource where someone has used "setModelMarkers" but faild.

**Comment by alexandrudima** [comment]
@itskhurram 
* https://github.com/Microsoft/monaco-typescript/blob/master/src/languageFeatures.ts#L111
* https://github.com/Microsoft/monaco-css/blob/master/src/languageFeatures.ts#L81
* https://github.com/Microsoft/monaco-json/blob/master/src/languageFeatures.ts#L90

**Comment by itskhurram** [comment]
Hello Alexandrudima,
is there any way to get markers because i see a function of getMarkers in Line object but it does not has information for markers.

khurram

**Comment by alexandrudima** [comment]
No support at this time. Let's track your request in Microsoft/monaco-editor#30
