### ISSUE TITLE
Code Helper (rendered) high cpu load

### ISSUE THREAD

**Issue by tikonoff** [microsoft/vscode#105582]
Issue Type: <b>Bug</b>

Run VSCode. Get 100%+ cpu load. 

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
react-hooks-snippets|AlD|1.1.7
vscode-color|ans|0.4.5
solidity-extended|bea|3.0.2
vscode-standardjs-snippets|cap|0.8.15
path-intellisense|chr|2.2.1
prettier-vscode|esb|5.5.0
todo-tree|Gru|0.0.178
solidity-solhint|idr|1.1.4
solidity|Jua|0.0.76
vscode-github|Kni|0.30.3
graphql-for-vscode|kum|1.15.3
web3js-snippets|lem|0.2.1
goto-next-previous-member|mis|0.0.5
vscode-docker|ms-|1.5.0
debugger-for-chrome|msj|4.12.10
color-highlight|nau|2.3.0
prettier-standard-vscode|num|0.8.1
material-icon-theme|PKi|4.2.0
code-settings-sync|Sha|3.4.3
ReactSnippetsStandard|Tim|1.1.0
highlight-matching-tag|vin|0.9.9
quokka-vscode|Wal|1.0.116
wallaby-vscode|Wal|1.0.234
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code --status`

**Comment by apar-garg** [comment]
The issue is still problematic
