### ISSUE TITLE
Settings Sync missing in gear menu and "Sign in & Turn on" button does nothing

### ISSUE THREAD

**Issue by jeremiahlee** [microsoft/vscode#105538]
- VSCode Version: 1.48.2
- OS Version: macOS 10.15.6

Steps to Reproduce:

1. Tap on Manage gear menu. It does not contain "Turn on settings sync..."
2. Open Settings panel instead.
3. Tap "Turn on Settings Sync"
4. On "Synchronizing your settings is a preview feature, please read the documentation before turning it on." prompt, tap "Turn on"
5. Leave all settings checked. Tap "Sign in & Turn on". Nothing happens.

Video: https://twitter.com/JeremiahLee/status/1299092407800258560

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Can you please provide logs from following locations while this happens?

- View: Open View > Log (Settings Sync)
- View: Open View > Log (Window)

Also check if Microsoft / Github account (authentication) extensions are available and enabled?

**Comment by jeremiahlee** [comment]
From View: Open View > Log (Settings Sync):
> [2020-08-28 22:27:06.123] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
> [2020-08-28 22:27:06.123] [userDataSync] [info] Auto Sync is disabled.

There was nothing in View: Open View > Log (Window).

For extensions, there is the GitHub extension that only has one line in Settings ("Controls whether to enable automatic GitHub authentication for git commands within VS Code") and it is enabled. The copy setting as JSON output: `"github.gitAuthentication": true`

**Comment by Hamza141** [comment]
I'm having the same issue on my personal computer running windows 10. However I don't have the GitHub extension installed like Jeremiah does.
However, I didn't have any issues with the setting sync on my work laptop that runs windows 10 when I turned on the feature a couple of days ago.

**Comment by sandy081** [comment]
Can you please open extensions view and add `@builtin authenti` in the input box and let us know what you are seeing? For example, I have following extensions enabled

<img width="408" alt="image" src="https://user-images.githubusercontent.com/10746682/92237768-393e5180-eeb8-11ea-97e5-6a4f2dc4952a.png">

**Comment by jeremiahlee** [comment]
Fascinating. I don't recall ever disabling the GitHub Authentication, but it was not enabled. I enabled it, then the Sync Settings appeared in the gear menu and I was able to start settings sync without a problem. Thank you!

<img width="260" alt="Screen Shot 2020-09-04 at 19 44 14" src="https://user-images.githubusercontent.com/244377/92271542-4bd07f00-eee8-11ea-976c-6f1870e89695.png">

**Comment by Hamza141** [comment]
Those were enabled for me but it randomly started working today.

**Comment by Kriechi** [comment]
possible duplicate #105310
I think this is related to #94299

I managed to successfully enable sync! The caveat: I am using multiple windows on macOS - but with the OS-native document-tabs. Meaning multiple tabs in one VSCode window.

After opening a fresh window with a single workspace, I finally saw the menu item and succeeded in enabling sync!

**Comment by sandy081** [comment]
I do not know why it got enabled randomly, I suspect a VS Code restart would have done it. But since it is resolved, closing this.
