### ISSUE TITLE
Bug: quick open shows recently-opened files that should be excluded

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#10564]
- VSCode Version: 1.4.0
- OS Version: Windows 10 (Anniversary Update)

Steps to Reproduce:

1. Open a file in a subfolder and make some edits, then save and close
2. Add the folder to the "search.exclude" settings
3. Quick open and start typing the filename

![image](https://cloud.githubusercontent.com/assets/298883/17684915/bc1ac052-63a2-11e6-8a81-b0b7ce90c316.png)

I want to see files in my "archive" folder in the sidebar so that I can navigate to them if I need to, but I don't want them coming up in searches or to show up via the "quick open" bar. Note that the exclusion settings pictured above were put in place after the file was originally opened.

_The fact that a file was recently opened should **not** cause "search.exclude" settings to be disregarded._

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6502
