### ISSUE TITLE
characters can't appear in terminal when the lines more then terminal window can holded.

### ISSUE THREAD

**Issue by feiyingjiancg** [microsoft/vscode#105682]
subject : characters can't appear in terminal when the lines more then terminal window that can holded.
platform : ubuntu16.04
vscode version : installed from apt
problem :  some lines will not be showed which is middle lines in the terminal window.

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal

**Comment by feiyingjiancg** [comment]
![2020-09-15 15-56-30 screen shot](https://user-images.githubusercontent.com/18224493/93183403-87333f00-f76d-11ea-8e22-09208febdfb3.jpg)
this is the problem's screenshot , anything help?

**Comment by feiyingjiancg** [comment]
> Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
> 
> /label "needs more info" integrated-terminal

Thanks. 
I found solution in the wiki page. Use the setting below: "terminal.integrated.rendererType": "dom"
