### ISSUE TITLE
THE ACTIVE editor cannot provide  outline information

### ISSUE THREAD

**Issue by Sendy101** [microsoft/vscode#105632]
Issue Type: <b>Bug</b>

I dont hav and click bottom to create new folder file copy it or enything, I can do nothing with files so I cant work 

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 2117U @ 1.80GHz (2 x 1796)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icons|vsc|10.2.0

</details>

**Comment by RMacfarlane** [comment]
Outline information is provided for some programming languages by default, but some others might require installing an extension. 

> I dont hav and click bottom to create new folder file copy it or enything, I can do nothing with files so I cant work

I'm having trouble understanding this, can you provide a screenshot of what you mean?
