### ISSUE TITLE
Add title description support to custom tree views

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#105667]
![image](https://user-images.githubusercontent.com/641685/91652159-590de980-ea62-11ea-96c0-d032a0607dc3.png)

**Comment by alexr00** [comment]
Re-opening for tracking the API.

**Comment by alefragnani** [comment]
@eamodio thanks for reopening this...

BTW, are _upvotes_ necessary here too? 😁

**Comment by eamodio** [comment]
Nah, this will hopefully be shipping in 1.50

**Comment by alefragnani** [comment]
Haha.. that’s great!

Thank you!
