### ISSUE TITLE
Duplicate search results after changing the case of filename

### ISSUE THREAD

**Issue by fangbinwei** [microsoft/vscode#105612]
- VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
- OS version: Darwin x64 19.6.0

Steps to Reproduce:

1. create file `demo.js`, input some text
2. change the case of filename, e.g. `Demo.js`
3. search text in files, but get duplicate results

![image](https://user-images.githubusercontent.com/13298807/91602534-108cf800-e99e-11ea-8ac3-8873d3377ddf.png)

![image](https://user-images.githubusercontent.com/13298807/91602446-efc4a280-e99d-11ea-9264-8de409fee00c.png)

Does this issue occur when all extensions are disabled?: Yes

This problem occurs on windows and macOS, Linux is ok. I know windows and macOS are case insensitive, and I find there are several issues related with case insensitive, I guess this problem is caused by a similar reason. I am sorry if this issue is duplicated.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/90926
