### ISSUE TITLE
Launching with --prof-startup causes window to crash

### ISSUE THREAD

**Issue by nrayburn-tech** [microsoft/vscode#105629]
Issue Type: <b>Bug</b>

When running `code-insiders --prof-startup`, the window frequently crashes and request to be closed or relaunched.  Relaunching causes it to just crash again.  Adding `--disable-extensions` does not seem to make a difference.

This also happens when launching the developer tools, starting the JavaScript CPU profiler, and then reloading the window.  (Following this process, [Performance-Issues#profiling-the-renderer-process](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process).)

[35dab05d-9905-4b7b-a6f1-c99090cf0dc9.dmp.zip](https://github.com/microsoft/vscode/files/5144585/35dab05d-9905-4b7b-a6f1-c99090cf0dc9.dmp.zip)

VS Code version: Code - Insiders 1.49.0-insider (6384e3246884694cbc34eacc70281ada15e2c7f2, 2020-08-28T16:02:16.834Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (6.01GB free)|
|Process Argv|--crash-reporter-id 03f31147-8ebd-457f-9df0-cdf4b9cd93d5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   32	    98	 23313	code-insiders main
    7	    49	 23316	   gpu-process
    0	    16	 23318	   utility
   34	    82	 23606	   shared-process
    0	     0	 23618	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
   28	   246	 23607	   window (Untitled-1)
    2	   115	 23608	     extensionHost
    2	    33	 23615	       /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer) /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=23608
   47	    49	 23616	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.5.0
dotenv|mik|1.0.1
debugger-for-chrome|msj|4.12.10
vscode-wakatime|Wak|4.0.7

</details>

**Comment by bpasero** [comment]
Related / duplicate: https://github.com/microsoft/vscode/issues/101350
