### ISSUE TITLE
VS Code appears tiny in the MacOS Dock

### ISSUE THREAD

**Issue by toddysm** [microsoft/vscode#105660]
**- VSCode Version:** 
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
**- OS Version:** MacOS Catalina 10.15.6

This seems to be the same as https://github.com/microsoft/vscode/issues/63068 but I am still able to reproduce it with latest versions of both VS Code and MacOS

<img width="149" alt="image" src="https://user-images.githubusercontent.com/1007103/91646988-4667c600-ea0a-11ea-82ae-cbbcf91aa232.png">

Does this issue occur when all extensions are disabled?: Yes

`KillAll Dock` fixes it.

**Comment by deepak1556** [comment]
Should be fixed with https://github.com/microsoft/vscode/issues/102975, please follow that issue for updates. Thanks!
