### ISSUE TITLE
Support RHEL Linux platform

### ISSUE THREAD

**Issue by simonyhchen** [Microsoft/vscode#1056]
Dear developers,

Since Redhat enterprise linux would be standard in the linux world.
But we cannot successful install it on RHEL5 or RHEL6.

Could your teams enhance this?

Thanks,
Simon

**Comment by Tyriar** [comment]
Does extracting the [zip](https://code.visualstudio.com/) and running `Code` not work? Do you get an error message?

**Comment by simonyhchen** [comment]
Dear friend,

I just unzip the VSCode and ran on RHEL6.7.
It shows:

./Code: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./Code)
./Code: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./Code)
./Code: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/simonyhchen/Downloads/VSCode-linux-x64/libnode.so)
./Code: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/simonyhchen/Downloads/VSCode-linux-x64/libnode.so)
./Code: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/simonyhchen/Downloads/VSCode-linux-x64/libgcrypt.so.11)
./Code: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /home/simonyhchen/Downloads/VSCode-linux-x64/libgcrypt.so.11)

**Comment by Tyriar** [comment]
Looks like code is assuming glibc 2.14 is present. I'm not too familiar with RHEL, you can try use `yum` to install the correct version, `yum install glibc` (or something)?

**Comment by simonyhchen** [comment]
Dear Daniel,

After google to upgrade glibc in RHEL5/6, we give up.
Could you porting your code by using the RHEL6(glibc2.12).
Many mature tools did this before so that both Ubunth/RHEL can share same
binary.

Regards,
Simon

2015-12-08 23:44 GMT+08:00 Daniel Imms <notifications@github.com>:

> Looks like code is assuming glibc 2.14 is present. I'm not too familiar
> with RHEL, you can try use yum to install the correct version, yum
> install glibc (or something)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode/issues/1056#issuecomment-162922260>.
>



-- 
Simon Yi-Hung Chen

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/vscode/issues/3603

**Comment by simonyhchen** [comment]
Really appreciate your effort.
Hope we can use it in RHEL6 recently.

Regards,
Simon

2016-03-02 3:39 GMT+08:00 Daniel Imms <notifications@github.com>:

> Closing in favor of #3603
> <https://github.com/Microsoft/vscode/issues/3603>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode/issues/1056#issuecomment-190867872>.
>



-- 
Simon Yi-Hung Chen

**Comment by Tyriar** [comment]
@simonyhchen you can see #3603 for a detailed update, currently we will not support <= RHEL6 since it doesn't have C++11 out of the box. Atom has the same issue and I'm not sure if we will invest in this in the future.

It may be possible to get Code running on RHEL6, but you will have to get all the dependencies installed and build the OSS version yourself.
