### ISSUE TITLE
Prompt the user for multiple arguments in a launch.json

### ISSUE THREAD

**Issue by PfisterFactor** [microsoft/vscode#105616]
I am trying to create a C++ development environment in VSCode for class. I have everything set up except for creating a launch configuration that allows arguments to pass through. I can define an input variable with a type of promptString to prompt the user for a single program argument, but I cannot specify multiple arguments because VSCode doesn't allow any way to pass a string of arguments to the program, it must be an array.

I believe it would be beneficial to expand the input variable functionality, or allow passing program arguments as a single string rather than an array. Are there any extensions that can do this currently?

**Comment by weinand** [comment]
> because VSCode doesn't allow any way to pass a string of arguments to the program, it must be an array.

VS Code knows nothing about arguments passed to programs. That functionality is provided by the debug extension.
Please file a feature request against the C++ extension to support a property with command line syntax (in addition to the "args" array property).
