### ISSUE TITLE
VSCode staging changes to files that didn't change

### ISSUE THREAD

**Issue by iagowp** [microsoft/vscode#105654]
Issue Type: <b>Bug</b>

I'm not really sure how it happens, or how to reproduce. It only happens in one project.

When I'm working sometimes I'm not even doing anything on the project, out of nowhere all my files turn green on file explorer (untracked marker),  when I check Source Control, I see that all my 81 tracked files are marked as deleted and staged, and then I have another 81 changes creating new 81 files. If I unstage the deletion, or stage the changes, it all disappears

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:09:41.484Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 10, 8|
|Memory (System)|4.00GB (0.06GB free)|
|Process Argv|-psn_0_90134|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
EditorConfig|Edi|0.15.1
dotenv|mik|1.0.1
sublime-keybindings|ms-|4.0.7
vetur|oct|0.26.1

(1 theme extensions excluded)

</details>

![Screen Shot 2020-08-29 at 4 42 47 PM](https://user-images.githubusercontent.com/1161036/91644944-4de19c00-ea17-11ea-9aff-403c48ee279b.png)

![Screen Shot 2020-08-29 at 4 42 40 PM](https://user-images.githubusercontent.com/1161036/91644942-491ce800-ea17-11ea-9b42-49e17aae3f58.png)

I've just opened a file and was checking git output to see what it was doing, got this:

> git show --textconv :src/validations/order.validation.js
> git ls-files --stage -- /Users/iagowp/Desktop/freelas/compostar/compostar-node/src/validations/order.validation.js
> git cat-file -s 6a3a290dac2c5a8293dc9d7d216073428a452415
> git ls-files --stage -- /Users/iagowp/Desktop/freelas/compostar/compostar-node/src/validations/order.validation.js
> git show --textconv :src/validations/order.validation.js
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template

**Comment by joaomoreno** [comment]
That is quite interesting. It appears something is staging the deletion of those files. I doubt that it is Code doing this, though. Maybe an extension or an external tool. Any thoughts?

**Comment by iagowp** [comment]
It happened even with all extensions disabled.
I am not aware of any tool I might have on my computer other than VSCode that uses git commands, so thats why I imagined it was here

I had taken a quick look at these logs, and thought it was VSCode staging it, but there doesn't seem to be any `git add` so I guess that's my mistake

**Comment by joaomoreno** [comment]
Does it repro with another repositories?
