### ISSUE TITLE
Unable to exit VS Code with a conflicted notebook

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#105601]
Steps to Reproduce:

1. Make an edit to a notebook in two places
1. You can never exit VS Code 🐛 https://memes.peet.io/img/20-08-47154de7-a07c-48b5-bd36-9a0a2a52ff65.webm

**Comment by rebornix** [comment]
I'm not seeing issues in today's Insiders or OSS. Can you share a bit more info about how to reproduce this issue? especially your settings of auto save / hot exit.

**Comment by connor4312** [comment]
I have auto save set to after delay, but no hot exit setting. I'll see if I can repro in a bit or in the morning

**Comment by connor4312** [comment]
I can't seem to get a repro for this.
