### ISSUE TITLE
View fails to load when reopening a markdown preview

### ISSUE THREAD

**Issue by jppianta** [microsoft/vscode#105621]
- VSCode Version: 1.48.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a markdown file on a tab
2. Click to preview the markdown
3. Close the preview tab
4. Use Ctrl + Shift + T to reopen the preview tab

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
