### ISSUE TITLE
Cant able to run my code in browser

### ISSUE THREAD

**Issue by cherukurinaveen036** [microsoft/vscode#105639]
Issue Type: <b>Feature Request</b>

I was trying to run my code in my browser and came up witha an error,i tried a lot to resolve this but cannot able to resolve please fix it 

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by RMacfarlane** [comment]
@cherukurinaveen036 Please provide concrete steps to reproduce the problem. What were you trying to run, and how? What was the error?
