### ISSUE TITLE
TS extension won't work well when type definition file is very complex, but yet valid

### ISSUE THREAD

**Issue by macabeus** [microsoft/vscode#105662]
- VSCode Version: 1.48.2
- OS Version: macOS Catalina 10.15.6

Steps to Reproduce:

1. Create a very complex `.d.ts` file [like that](https://gist.github.com/macabeus/b9bdd539c87619b2e99288c8287dec0d)
2. Despite VS will can read this file and use these types on autocomplete, will show error on lines that are fine, for example:

![image](https://user-images.githubusercontent.com/9501115/91649179-fbc96680-ea68-11ea-9db8-ea6ea0464559.png)

![image](https://user-images.githubusercontent.com/9501115/91649279-18b26980-ea6a-11ea-8036-d856676a45a7.png)

Notice that this `.d.ts` file has two long union type and two conditional type with many cases, that are used to overload `getMessage` and `formatPattern`.

## Use Case

Probably you are scared by this `.d.ts` file,  but it's valid and necessary for [this devtool](https://github.com/macabeus/fluent-typescript) that I'm developing.
This `.d.ts` is autogenerated by `fluent-typescript`, that compiles a localisation file `.ftl` into a type definition file. So if there are many messages on localisation, we'll need to generate a long `.d.ts` file as well, because is necessary to generate the type for each message.

VSCode works fine when there are few messages, but it doesn't work when there are many messages.

Despite that, it still show the type inference:
![image](https://user-images.githubusercontent.com/9501115/91649247-d12bdd80-ea69-11ea-892e-8b3732840ab9.png)

Related: https://github.com/macabeus/fluent-typescript/pull/16

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

I can't find `Expected token` string in VS Code or TypeScript repo and `E0003` doesn't look like TS related error wthich usually look like `ts(2304)`.

**Comment by IllusionMH** [comment]
Unable to reproduce this with code from https://github.com/macabeus/fluent-typescript/tree/master/example-vanilla with content of `assets/locales/translations.ftl.d.ts` replaced with linked `bug.d.ts`.
Works well with `typescript@3.8.3` (used in example-vanilla) and with `typescript@next`.

**Comment by macabeus** [comment]
@IllusionMH I checked now, and apparently works fine with extensions disabled.
And my fault. This error is from an extension that I'm developing, [vscode-fluent](https://github.com/macabeus/vscode-fluent).

I really don't know why it's trying to check the syntax on a `.ts` file, but yeah, it's the origin of the problem.
