### ISSUE TITLE
New custom view hover is not preserving newlines

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#105646]
I am not using a markdown string here

![image](https://user-images.githubusercontent.com/641685/91642595-a6567080-e9fa-11ea-9b2c-0a2432654fa6.png)

**Comment by eamodio** [comment]
To fix this, I think we just need to double the newlines.

**Comment by eamodio** [comment]
It now seems to be doubling line breaks:

![image](https://user-images.githubusercontent.com/641685/92152353-87881d80-edf0-11ea-80fb-8d5224ca75b3.png)

**Comment by alexr00** [comment]
That's just how newlines are shown in the markdown hover.
