### ISSUE TITLE
Python files not running inside VSCode terminal

### ISSUE THREAD

**Issue by naveedunjum** [microsoft/vscode#105686]
- VSCode Version: 1.48.2
- OS Version: Linux Mint 20
Whenever I try to run python files inside VSCode, the terminal pops up but nothing happens as shown in the image. Even Start REPL gives the same window. The terminal is unresponsive always and nothing appears. The interpreter is selected as is evident from the pic. Any fix?
![image](https://user-images.githubusercontent.com/37370766/91667449-74d8c480-eb22-11ea-92d4-18a2e6c592b1.png)

Does this issue occur when all extensions are disabled?: Not applicable

**Comment by jdematos** [comment]
Hi there! :) 

I wonder if you're not using the default path to your shell executable.

Can you go to: File -> Preferences -> Setting -> Features -> Terminal and search for "integrated shell: Linux" and then click "edit in settings.json". What is the value you have for the key "terminal.integrated.shell.linux"? 

Also, still under -> Terminal, search for inherit env and see if that's checked or not.

**Comment by Tyriar** [comment]
All good questions from @jdematos. Also how are you running the python files, via an extension?

**Comment by naveedunjum** [comment]
Thanks @jdematos. The inherit env option under Terminal was not checked. Turning it on solved the problem. Thanks once again.
