### ISSUE TITLE
Broken powerline font in terminal 

### ISSUE THREAD

**Issue by hegerdes** [microsoft/vscode#105673]
# Broken powerline font in vscode terminal 
- VSCode Version: 1.48.2
- OS Version: Debian 10 Buster

## Settings

Steps to Reproduce:

1. Install zsh, oh_my_zsh, powerline font
2. Use a powerline theme like "agnoster"
3. Open system terminal - everything works
4. Open vscode terminal - font is broken

## Pictures
**System terminal emulator:** ![Xfce emulator with powerline font](https://i.imgur.com/zTzoAw7.png) 

**VSCode terminal:** ![vscode broken terminal font](https://i.imgur.com/z68iHkH.png) 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
Does changing the rendererType used in settings help? Do you know where the ~ and branch symbols come from?

**Comment by hegerdes** [comment]
I tried all rendertypes. Nothing changed. The arrow like symbols and branch symbols are still not showing. Seems like the terminal renderer can't find the font. It is called [Poweline Symbols](https://github.com/powerline/fonts).

It is an additional font I installed in the usual font dir - as recommended. 
Output form `fc-list | grep -i powerline
`:     
`/usr/share/fonts/opentype/PowerlineSymbols.otf: PowerlineSymbols:style=Medium`

**Comment by Tyriar** [comment]
Did you set the font in the `terminal.integrated.fontFamily` setting?

**Comment by hegerdes** [comment]
Just tried that. Then the symbols show up. But all symbols have a very wide spacing and vscode shows a warning that only momospace fonts are supported. 
![VSCode Terminal](https://i.imgur.com/LxHAg53.png)

Should't vscode automatically pick missing symbols from a font that provides these symbols. Similar the the google-noto-emoji font. The emoji font is only used if the primary font doesn't provide the symbol

**Comment by Tyriar** [comment]
@hegerdes it looks like you need a primary monospace font and a fallback for the symbols. Try using css notation in that setting, eg. `courier, PowerlineSymbols`. I think the problem is you're not using a real "powerline font" which is a regular font patched with the powerline symbols.
