### ISSUE TITLE
`.gitignore` can not make files list color reset dark gray.

### ISSUE THREAD

**Issue by yukilzw** [microsoft/vscode#105631]
- VSCode Version: v1.48.2
- OS Version: WIN10

Steps to Reproduce:
`.gitignore` can not make files list color which are ignored reset dark gray. but the source control is always useful.
I try to Re install `vscode` & `git`  but it is unhelpful.
Is there any editor setting for this?

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you show me a screenshot of what you mean?

**Comment by yukilzw** [comment]
It will be expected color opacity like this:
![image](https://user-images.githubusercontent.com/21005519/91861993-015cc180-eca0-11ea-969f-3898d6efd73f.png)

but in my computer:
![image](https://user-images.githubusercontent.com/21005519/91862268-4ed92e80-eca0-11ea-8d1c-2f8780c77063.png)

In editor git source control is working.

**Comment by joaomoreno** [comment]
Can you show me the full output of `Git: Show Git Output`?

Doe sit repro on every repository on that machine?

**Comment by yukilzw** [comment]
Every repository on this machine is bad.
Git of machine is working done.
![image](https://user-images.githubusercontent.com/21005519/92005648-4bb07200-ed76-11ea-9cee-436bc752857d.png)
The editor of this machine was normal before. Once the hard disk was damaged and VSCODE & Git was reinstalled from Disk D:/ to Disk F:/, which meant that it was not uninstalled normally before. Since then this problem has appeared and no solution can be found

**Comment by yukilzw** [comment]
Is Git Output this？
![image](https://user-images.githubusercontent.com/21005519/92130018-d5277900-ee36-11ea-957d-e8cdec0185ce.png)

**Comment by joaomoreno** [comment]
Can you update to the latest Git 2.28.0?

**Comment by yukilzw** [comment]
It seems that the command line of GIT version has changed, and it has been fixed after upgrading
