### ISSUE TITLE
npm start from VS Code terminal no longer works

### ISSUE THREAD

**Issue by ButchAnton** [microsoft/vscode#105602]
Issue Type: <b>Bug</b>

Up until a couple of nightly builds ago, I was able to run "npm start" or "npm run test" from the VS Code terminal for my project and it would properly execute the target.  Now, I get the following instead:

❯ npm start
Debugger listening on ws://127.0.0.1:63259/e3cb3f0b-268c-4240-9873-87dbcdd8823e
For help, see: https://nodejs.org/en/docs/inspector
^C
❯ npm run test
Debugger listening on ws://127.0.0.1:63751/001e9924-d2af-424b-93b8-4c188da4115e
For help, see: https://nodejs.org/en/docs/inspector
^C

It seems like it's always trying to debug the code.

Can you please help me to understand why there has been this change in behavior?

Thank you!

VS Code version: Code - Insiders 1.49.0-insider (b58f4549b2919fa3a5dc52df83f4ba60780c625f, 2020-08-27T05:39:40.559Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (7.63GB free)|
|Process Argv|--crash-reporter-id ac49dfc4-814e-4cff-8590-cbf53789d84e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
project-manager|ale|11.2.0
arepl|alm|1.0.24
vscode-color|ans|0.4.5
code-gnu-global|aus|0.2.2
vscode-custom-css|be5|3.0.10
color-info|bie|0.5.1
regex|chr|0.2.0
open-html-in-browser|cod|0.1.21
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
jshint|dba|0.10.21
vscode-eslint|dba|2.1.8
vscode-dash|dee|2.4.0
vscode-faker|dee|1.4.1
git-extension-pack|don|0.1.3
githistory|don|0.6.9
xml|Dot|2.5.1
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.5.0
code-runner|for|0.11.0
gc-excelviewer|Gra|3.0.40
todo-tree|Gru|0.0.178
vscode-guid|hea|1.4.20
vscode-emacs|hir|0.1.1
beautify|Hoo|1.5.0
replace-curly-quotes|jin|1.1.0
vscode-peacock|joh|3.8.0
chat|kar|0.35.0
vscode-gutter-preview|kis|0.26.2
git-indicators|lam|2.1.2
MagicPython|mag|1.1.0
rainbow-csv|mec|1.7.1
ui5-explorer|mic|0.5.0
xml-format|mik|1.0.2
vscode-ui5|mil|1.0.2
vscode-clang|mit|0.2.3
prettify-json|moh|0.0.3
vscode-docker|ms-|1.5.0
python|ms-|2020.8.105045
atom-keybindings|ms-|3.0.8
cpptools|ms-|0.29.0
vsliveshare|ms-|1.0.2708
vsliveshare-audio|ms-|0.1.85
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.10
color-highlight|nau|2.3.0
vscode-print|pdc|0.7.14
polacode|pnp|0.3.4
vscode-css-peek|pra|4.0.0
view-in-browser|qin|0.0.5
java|red|0.65.0
vscode-xml|red|0.13.0
vscode-format|rya|0.0.6
nightwatch-js-snippets|san|0.2.0
todotasks|san|0.5.0
code-settings-sync|Sha|3.4.3
vscode-hexdump|sle|1.7.2
guides|spy|0.9.3
python|tht|0.2.3
gitflow|vec|1.2.1
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.12.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.1
vscode-maven|vsc|0.24.1
vscode-icons|vsc|10.2.0
gitblame|wad|4.2.0
quokka-vscode|Wal|1.0.315
vscode-todo-highlight|way|1.0.4
debug|web|0.25.0
change-case|wma|1.0.0
html-css-class-completion|Zig|1.19.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Can you try toggling `debug.node.autoAttach` to `disabled` (and then back on again if you want) to refresh your settings? Some changes were made during one Insiders build which could cause this under certain conditions.

**Comment by connor4312** [comment]
Closing due to lack of info

**Comment by ButchAnton** [comment]
Sorry, toggling the default a couple of times solved the problem.
