### ISSUE TITLE
con not debug vscode extension

### ISSUE THREAD

**Issue by BUPTlhuanyu** [microsoft/vscode#105645]
- VSCode Version: 1.48.2
- OS Version: Mac OS 10.15.6

Steps to Reproduce:

1. download the project [my-new-extension.zip](https://github.com/Microsoft/vscode/files/1691243/my-new-extension.zip)
2. run yarn
3. presse F5
4. presse F1, and type Hello...
5. the breakpoint not hit, and the debuger disconnect quickly

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
This works fine in VS Code 1.50.0 on macOS.

Do you still see the problem in VS Code 1.50.0?
