### ISSUE TITLE
No menu titles

### ISSUE THREAD

**Issue by luismendes070** [microsoft/vscode#105610]
`Issue` Type: <b>Bug</b>

No menu titles

![image](https://user-images.githubusercontent.com/11665035/91604153-85cbdf00-e944-11ea-8cad-b5caee9a79f1.png)

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.91GB (2.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sbatten** [comment]
I don't quite understand what issue is being reported.

**Comment by luismendes070** [comment]
I want to read the menu bar please

**Comment by luismendes070** [comment]
The default install was used.

**Comment by sbatten** [comment]
Can you open settings and check your setting for `window.titleBarStyle` and `window.menuBarVisibility`

**Comment by luismendes070** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/11665035/91768813-94203200-ebb4-11ea-8bef-a92ed23f0c0e.png)
