### ISSUE TITLE
Saving a jupyter as .py problem

### ISSUE THREAD

**Issue by Rfariaspoblete** [microsoft/vscode#105619]
We have written the needed data into your clipboard because it was too large to send. Please paste. 
Issue Type: <b>Bug</b>

When i try to save any jupyter as .py its show me the new .py just with the first three lines. 

It is a very usefull function, so please tell me, what can i do right now.

Regards, 

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.26GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.0.27
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.36.3
gitlens|eam|10.2.2
code-runner|for|0.11.0
latex-workshop|Jam|8.11.1
kite|kit|0.122.0
theme-monokai-pro-vscode|mon|1.1.17
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.8.105045
vscode-pylance|ms-|2020.8.2
remote-containers|ms-|0.134.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
autodocstring|njp|0.5.3
vscode-data-preview|Ran|2.0.0
vscode-yaml|red|0.10.1
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.9.0
code-spell-checker-spanish|str|1.0.5
redberry-icons|Ten|0.0.5
pdf|tom|1.1.0
material-theme|zhu|3.8.5

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@Rfariaspoblete How are you saving the file? Is this a command from an extension?

**Comment by Rfariaspoblete** [comment]
Something very weird Just happen. I upgrade the Latex version on Windows and I can now save correctly.

Regards.
