### ISSUE TITLE
tab titles not changing after renaming js function name and the file name

### ISSUE THREAD

**Issue by bychis** [microsoft/vscode#105611]
- VSCode Version: 1.48.2
- OS Version: windows 10 version 19041

Steps to Reproduce:

1. create a js file named addSomething with function named addSomething included 
2. rename the file and the function to AddSomething
3. the tab still be addSomething instead of AddSomething

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
> rename the file and the function to AddSomething

How exactly?
