### ISSUE TITLE
Package tree suddenly empty:  "No tree view with id ‘view-legato-system’ registered."

### ISSUE THREAD

**Issue by mbpetersen** [microsoft/vscode#105620]
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:56:10.074Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic snap

Steps to Reproduce:

1.  Open VScode (for current Legato app project)
2. Select Legato on Activity Bar
     LEGATO: HIERARCHY VIEW    is completely empty.
     on occasion will capture a Notification which states:
               "**No tree view with id ‘view-legato-system’ registered.**"

Does this issue occur when all extensions are disabled?:  _Not applicable_ - without the Leaf and Legato extensions there will be no access to the Legato Tree view.

Function was fine until a Storm-induced reset forced reboot of VirtualBox VM - Ubuntu and execution of VScode.   It was suddenly empty.  Before shut-down it was fine - all was well.

Reviewed many settings & config files but nothing corrupt or missing was noted (clearly I'm missing something).   But I notein Legato Forum's - many dealing with this: an Empty Legato Hierarchy view.

**Comment by RMacfarlane** [comment]
Please reopen this issue on the Legato extension, thank you.

**Comment by mbpetersen** [comment]
@RMacfarlane 
Please forward a link to this location (Legato extension).

**Comment by RMacfarlane** [comment]
https://github.com/legatoproject/VsCodePlugin

**Comment by mbpetersen** [comment]
@RMacfarlane 

oddly I also note that code -v indicates 1.47.3, yet opening code the version indicates it is 1.48.2  ??  ...with no Updates available.
Code installed and maintained via snap - ubuntu 18.04LTS.  
$snap list
code                  a0479759                    42    latest/stable    vscode✓     classic
