### ISSUE TITLE
Custom view hovers: Email addresses get auto-linked, but to a broken link

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#105649]
The tooltip is being provided as a string (not a markdown string), and you can see that the auto-link is bogus

![image](https://user-images.githubusercontent.com/641685/91642847-a48dac80-e9fc-11ea-9fc4-d25bbeadac2e.png)

**Comment by RMacfarlane** [comment]
@eamodio Can you share what you set as the tooltip? I'm not sure how to get the auto-link to happen

**Comment by eamodio** [comment]
@RMacfarlane I can verify this
![image](https://user-images.githubusercontent.com/641685/92151803-b0f47980-edef-11ea-9e75-5822dd17012c.png)
