### ISSUE TITLE
[bug] Unable to open CSS color picker by clicking on color preview box in the CSS source code.

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#105614]
The [documentation says](https://code.visualstudio.com/docs/languages/css#_syntax-coloring-color-preview) that we should be able to click on the color preview in a CSS file to open the color picker. This has never worked for me. I've never seen this feature, but I've always thought it would make sense to click on the boxes and open a color picker. 

```
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-14T22:01:14.734Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.52-1-MANJARO
```

Steps to Reproduce:

1. Open a CSS file with a color in it.
2. Click the color preview box.
3. Nothing happens (no color picker)

Does this issue occur when all extensions are disabled?: **Yes**

Here I am trying clicks and double-clicks:

![Peek 2020-08-28 11-52](https://user-images.githubusercontent.com/297678/91605283-11ce0e80-e925-11ea-9c25-d4e833291e32.gif)

**Comment by trusktr** [comment]
According to https://github.com/microsoft/vscode/issues/82206, the color picker should appear when hovering. Hovering didn't work either.

I don't think it should. It should be on click, while hovering does not get in the way of the code editing experience (that would be too annoying).

**Comment by nicasi** [comment]
The colorpicker does appear on hover, if you hover "the right way". If you enter the color value from the "wrong" side it will not show. This confused me a lot in the beginning but I somewhat got used to it. Brackets does a better job, the color picker is revealed with a keyboard shortcut.

I agree with @trusktr that clicking the color preview box to reveal the color picker would be a better user experience.

![2020-09-09_09-51-34](https://user-images.githubusercontent.com/332098/92570371-1f1ebd80-f282-11ea-9c0e-41caff532e40.gif)

**Comment by TheMissJ** [comment]
color picker isn't showing for me at all when I hover from the bottom.  what is the keyboard shortcut, if there is one?
