### ISSUE TITLE
copy - paste in Edge browser not working

### ISSUE THREAD

**Issue by dimaai** [microsoft/vscode#105689]
hi, the Ctr+c/ Ctr+V doesn't work in Edge. Paste I could do with Ctr+Shft+V ,but copy couldn't manage to do. 
This is a disaster to code without copy-paste working!

**Comment by RMacfarlane** [comment]
@dimaai It's not clear to me how this is related to VSCode, please clarify if you think this is a problem with Visual Studio Code and not Edge.

**Comment by dimaai** [comment]
No, this is not Edge. This same problem persists in Chrome. This seems to be a bug in VS Code Codespaces.

**Comment by RMacfarlane** [comment]
Please report this on codespaces: https://github.com/MicrosoftDocs/vscodespaces
