### ISSUE TITLE
Multiple outfiles folders in tsconfig.json no longer work in 1.48 debugger

### ISSUE THREAD

**Issue by JoshuaMGoldstein** [microsoft/vscode#105626]
Issue Type: <b>Bug</b>

1. Create a multi-project workspace with two folders imporrted
helloworld/
library/

2. run npm init in helloworld folder

3. npm install -S @types/node
   npm install -S @types/reflect-metadata

4. create a tsconfig.json with 

```
{
    "compilerOptions": {
        "target": "es2017",
        "lib": ["es2017","dom"],  
        "types": ["reflect-metadata","node"], 
        "module": "commonjs", 
       "sourceMap": true,
         "outDir": "app",
        "baseUrl": "src"
    },
    "include": [
        "src/**/*",
    ]
}
```

5. Create src/helloworld.ts

```
import "reflect-metadata"
console.log("Hello world");
```

6. Create launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "name": "Launch",
            "cwd": "${workspaceFolder}",
            "sourceMaps": true,
            "program": "${workspaceFolder}/src/helloworld.ts",
            "outFiles": [
                "${workspaceFolder}/app/**/*.js",
                "${workspaceFolder:library}/**/*.js",
            ],
         }
 }
```

7. Start debugging, you will receive an error on the line importing "reflect-metadata" in v1.48

Works in  v.1.47!!

8. Remove the second outFiles: [ ] entry   "${workspaceFolder:library}/**/*.js" and it will work again in v.1.48... but this means that working with typescript/javascript files across multiple project folders is no longer possible.

VS Code version: Code 1.48.2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.92GB (2.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by connor4312** [comment]
Can you please try with the [night extension](https://github.com/microsoft/vscode-js-debug#nightly-extension)? Previously the 'bootloader' script we injected use reflect-metadata internally which may have caused your issue.
