### ISSUE TITLE
I can't create html files because they've seen files in Djungle

### ISSUE THREAD

**Issue by ArthurCaio** [microsoft/vscode#105680]
I'm a beginner who ta learning I can not program in html and js because every time I put a file in **html turns dj** out of nowhere someone mi help why I do my things I presiso do **.htm** and ta giving error already in my browser

**Comment by aeschli** [comment]
Sorry, I don't exactly understand what happening. Can you add detailed steps with a code sample and maybe add some screenshots as well?
