### ISSUE TITLE
Color Theme for C++ Class Object 

### ISSUE THREAD

**Issue by sstaub** [microsoft/vscode#105675]
The color of a class object (e.g. `MyClass myObject`) in C++ is interpreted as the color of a variable (`"scope": "variable"`).
It should possible to give the class objects their own color definition in the color theme .json file

The same for the class method, in the moment the color of a class method is the same as the color for a function.
It will help to differ methods from functions

**Comment by alexr00** [comment]
@sstaub can you please give a full example?

**Comment by sstaub** [comment]
Here some screenshot for better understanding:
first I use a grey color for the _scope "variable"_, then red for the second example.
<img width="352" alt="variable grey" src="https://user-images.githubusercontent.com/6450325/94548100-8364e980-0250-11eb-91f6-a1f6a295128f.png">
<img width="352" alt="variable red" src="https://user-images.githubusercontent.com/6450325/94548166-9b3c6d80-0250-11eb-8d70-9efc0fae0eab.png">
 here what happens in the code when 'variable' is grey:
<img width="416" alt="code var grey" src="https://user-images.githubusercontent.com/6450325/94548243-b60ee200-0250-11eb-8d42-9742ec02934c.png">
now when red:
<img width="426" alt="code var red" src="https://user-images.githubusercontent.com/6450325/94548271-c45cfe00-0250-11eb-8714-5d7e97ef88ce.png">
The  color of the green marked 'variable' is changing together with cyan marked 'class object'.
I would expect that a 'class object' has a different color.
The same for the orange marked 'functions', the first function is real single 'function', the second one
is also a function but also a 'class member', therefore there should also different colors.

**Comment by alexr00** [comment]
Can you provide some of the code from your example that I can copy/paste?

**Comment by sstaub** [comment]
Here is the PlatformIO project I used for the example and my personal color theme.
[Ticker.zip](https://github.com/microsoft/vscode/files/5298860/Ticker.zip)
[dark++.zip](https://github.com/microsoft/vscode/files/5298867/dark%2B%2B.zip)

**Comment by alexr00** [comment]
Thanks for the samples! We get our syntax highlighting grammar from https://github.com/jeff-hykin/cpp-textmate-grammar/, so that is where the token scopes that allow you to color types differently come from. I recommend filing the issue as a feature request in that repo.

**Comment by sstaub** [comment]
got this answer from https://github.com/jeff-hykin/cpp-textmate-grammar/issues/517

There should be some difference in the scope between the different colored boxes you can use the command palpate action > Developer: Inspect Editor Tokens and Scopes to examine the scope. However due to how textmate grammars work it's not always possible to determine the correct scope for each token. You may want to try the semantic coloring for the C/C++ extension.

Edit: After examining the provided examples, I can see that you are using the semantic coloratization. You may wish to file an issue with the cpptools extension.

With this grammer with regards to functions you can distinguish between:

function definitions: entity.name.function.definition
free function calls: entity.name.function.call
member function calls: entity.name.function.member
