### ISSUE TITLE
feature request: rename "JavaScript React" Language to something more appropriate.

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#105606]
JSX is a spec that defines a syntax extension for JavaScript. JSX is not specific to React and does not define what the runtime output should be.

Because of this there are frameworks that compile JSX to different outputs that are completely incompatible and unrelated to React.

The name "JavaScript React" is a misnomer for projects that have no trace of React in them (other than a syntax that React projects also use).

Changing the name would be one step towards acknowledging JSX-is-no-React. Improving TypeScript's type system for JSX so that it doesn't depend on React output would be great too, but for another issue.

**Comment by trusktr** [comment]
As an example to back up the idea of JSX not being React, [Solid](https://github.com/ryansolid/solid/tree/master/packages/babel-preset-solid)'s JSX compiler allows us to do this:

```jsx
let code
const div = <div>This is <code ref={code}>fixed width</code>.</div>

console.log(div instanceof HTMLDivElement) // true
console.log(code instanceof HTMLElement) // true

document.body.append(div)
```

Solid's form of DOM manipulation (which the JSX compiles down to) is one of the fastest in @krausest's renowned [JS Framework Benchmark](https://krausest.github.io/js-framework-benchmark/current.html).

I've built a custom element system on top of Solid's JSX over at [lume/element](https://github.com/lume/element). The combination of JSX-to-DOM with custom elements is such a great fit (and nothing to do with React except that they published the JSX spec, then used it first)!

```js
import {Element} from '@lume/element'

class MyEl extends Element {
  template = () => (
    <div>
      Some content <span>or something.</span>
      <button ref={this.btn}>Back to top.</button>
    </div>
  )

  // Scoped styles.
  static css = /*css*/`
    button {
      background: cornflowerblue;
      border: 2px solid red;
      color: white;
    }
  `

  connectedCallback() {
    // HERE! It's just DOM!
    // Apply a good ol' jQuery plugin to the button, for example.
    $(this.btn).scrollAnchor(/* ... */);
  }

  disconnectedCallback() {/* ...cleanup... */}
}
```

**Comment by mjbvz** [comment]
I think your proposal is technically correct but would require migration work and end up introducing more complexity without offering a real user benefit

JSX in JavaScript users can just use the normal `JavaScript` language mode in almost all cases

JSX in TypeScript users have to use `TypeScript React` but we have not seen other people reporting that they are confused about the `react` part in the name


I agree that if were starting fresh calling it `JavaScript+JSX` would be better, but I don't think the benefit of a rename is worth the pain at this point
