### ISSUE TITLE
Cannot open "recent" markdown files from Windows Taskbar

### ISSUE THREAD

**Issue by tjbarbour** [microsoft/vscode#105665]
Issue Type: <b>Bug</b>

1. Open vscode on windows, pin it to taskbar
2. Create a markdown file, take note of name/location it was saved.
3. Close the markdown file.
4. Right click on vscode windows taskbar icon
5. Select the markdown file under the "Recent" list
6. Observe the error below:

> "The item you selected is unavailable.  It might have been moved, renamed, or removed.  Do you want to remove it from the list?"

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.56GB free)|
|Process Argv|C:\Users\tjbar\.omnisharp\~omnisharp.json|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.52
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
dotnet-test-explorer|for|0.7.4
csharpextensions|jch|1.3.1
csharp|ms-|1.23.1
powershell|ms-|2020.6.0
hide-gitignored|npx|1.1.0
code-spell-checker|str|1.9.0

(1 theme extensions excluded)

</details>

## Notes:

I first thought this was a windows issue, but I tried the same steps with notepad and had no problems which made me wonder if it is something specific to vs code.  I have observed this with multiple files in multiple locations  See this screenshot to clarify what I'm referring to:

![image](https://user-images.githubusercontent.com/412467/91651082-dd4d7600-ea3c-11ea-94d0-6b98b8b5d3fc.png)

Opening the file in vscode from the File > Open prompt or other means doesn't cause any issues.

**Comment by bpasero** [comment]
I cannot reproduce, this error should only appear for files that do not exist anymore on disk. Is this a special file system? Network drive? UNC?

**Comment by tjbarbour** [comment]
Afraid not, a typical windows laptop referring to a local file within the same user profile 😬

I'll try reproducing on another machine today

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by tjbarbour** [comment]
Update: I reproduced on another system.  Same effect weather it's recent or pinned by the way.
Pending: need to try with preview build.
Thanks for your help/patience

**Comment by bpasero** [comment]
Thanks
