### ISSUE TITLE
[Debug filter] View gets empty when the input is empty

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#105679]
#105185

Issue Type: <b>Bug</b>

1. Type something into the filter
1. Clear the filter (delete all text)
1. The debug console is empty now

![demo](https://user-images.githubusercontent.com/9638156/91657784-76779d80-eacc-11ea-80b1-19ac661d6cbe.gif)

VS Code version: Code - Insiders 1.49.0-insider (6384e3246884694cbc34eacc70281ada15e2c7f2, 2020-08-28T16:02:44.602Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
I also can not reproduce this after my latest refactorings. Do you still see this with latest?
And thank you very much for testing it.

**Comment by usernamehw** [comment]
f66741d No difference. Still reproduces.

**Comment by isidorn** [comment]
I can not reproduce with latest out of source. Also can not repro when I build insiders from latest locally. I believe the next insiders will have the fix.
If you still see it tomorrow please let me know. Thanks a lot! For now closing

**Comment by usernamehw** [comment]
❌ Not fixed.

**Comment by isidorn** [comment]
Ok, let's reopen.

**Comment by isidorn** [comment]
Repro steps:
make sure to have `editor.accessibilitySupport: "on"` in your settings.json
