### ISSUE TITLE
Unable to change key bindings on keyboard shortcuts

### ISSUE THREAD

**Issue by kamula** [microsoft/vscode#105655]
Issue Type: <b>Bug</b>

I have tried to change the mode of creating new line on a file from ctrl+enter to ENTER key only but it is impossible

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 5.4.0-42-generic

**Comment by sandy081** [comment]
/duplicate

#85850
