### ISSUE TITLE
Alternate cursor movement shortcut is not applied to auto completion list

### ISSUE THREAD

**Issue by hwooo** [microsoft/vscode#105650]
- VSCode Version: 1.48
- OS Version: Windows 10 2004

Steps to Reproduce:

1. Bind another shortcut to 'cursor up/down/left/right'.
2. Test new shortcut when auto-completion list is generated.

I can't move cursor focus on completion list with my alternate shortcut **alt+i/j/k/l** so still I must to use arrow keys.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
You need to use list-command, e.g `list.focusUp`
