### ISSUE TITLE
Live server is not running in VSCode. I have tried to fix this issue by editting in settings.json file and also my default custom browser is "chrome". Still Live Server is not running.

### ISSUE THREAD

**Issue by mak-19** [microsoft/vscode#105688]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mak-19** [comment]
Dear Microsoft/Vscode,
I am not getting what solution you are saying. Please help me regarding
this.

Thanks & Regards
Mayank Sharma

**Comment by weinand** [comment]
Please file the issue against the Live Server extension.
