### ISSUE TITLE
Use md Table for PerfViewEditor

### ISSUE THREAD

**Issue by nrayburn-tech** [microsoft/vscode#105627]
The perfViewEditor currently uses tabs for raw perf marks, which makes it difficult to read.

```
willLoadMainBundle	1598659485447	20	166
didLoadMainBundle	1598659485535	88	254
main:loadWindow	1598659485654	119	373
renderer/started	1598659485916	262	635
willShowPartsSplash	1598659485917	1	636
```

Using a markdown table turns it into this more legible format.
```
| willLoadMainBundle                               | 1598659760104 | 2     | 87    |
| didLoadMainBundle                                | 1598659760257 | 153   | 240   |
| main:loadWindow                                  | 1598659760361 | 104   | 344   |
| renderer/started                                 | 1598659760632 | 271   | 615   |
| willShowPartsSplash                              | 1598659760633 | 1     | 616   |
```

**Comment by jrieken** [comment]
> The perfViewEditor currently uses tabs for raw perf marks, which makes it difficult to read.

That's on purpose. The format allows the data to be saved into CSV-files and imported into further processing software, like Excel. That's why it's called raw perf marks, the easy to read and digest data is shown in the tables above.
