### ISSUE TITLE
How to make a TextDocument to be *pinned*?

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#10568]
Hi,

Is there a way to make a TextDocument, currently in _preview_ to be _pinned_?

I found [this issue](https://github.com/Microsoft/vscode/issues/9138) to add a `pinned` option to `showTextDocument`, but my intention is turn a previewed document to pinned.

Thanks in advance

**Comment by jrieken** [comment]
My current thinking is make editors using `showTextDocument` always be `pinned` - mostly for the sake of simplicity. @alefragnani what is your use-case for this?

**Comment by alefragnani** [comment]
@jrieken the use-case is related in [this issue](https://github.com/alefragnani/vscode-bookmarks/issues/30) in my **Bookmarks** extension. The intention is to _pin_ the editor when the user adds a Bookmark.

What do you think?

**Comment by muellerkyle** [comment]
I'm the original requestor for the item on the Bookmark extension. I'd like to add a reference to my original request with the VSCode team, which was referred to the Bookmark extension. It seems that this is blocking him from being able to implement this outside of VSCode.

See: https://github.com/Microsoft/vscode/issues/224#issuecomment-218665430

**Comment by jrieken** [comment]
With https://github.com/Microsoft/vscode/pull/23641 we now have the option to open a document as preview-tab and when to turn a preview-tab into a pinned one. It's a one way tho.

Simply call `showTextDocument` a second time: 

```
// open a preview-tab
return vscode.window.showTextDocument(doc, { preview: true });


// open a pinned-tab _or_ turn into pinned-tab
return vscode.window.showTextDocument(doc, { preview: true });
```

**Comment by eamodio** [comment]
@jrieken I think in the 2nd example you meant:
```
// open a pinned-tab _or_ turn into pinned-tab
return vscode.window.showTextDocument(doc, { preview: false });
```

**Comment by jrieken** [comment]
Thanks @eamodio. Corrected above
