### ISSUE TITLE
[Debug filter] Polish filter style when dragged from default position

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#105677]
#105185

1. Move debug view out of default position so it's in a split state

---

* No margin between **`DEBUG CONSOLE`** text and the input
* Input focus border is only displaying left and right border

![Screenshot (323)](https://user-images.githubusercontent.com/9638156/91657360-04518980-eac9-11ea-8db3-4b4ef353eaef.png)

**Comment by usernamehw** [comment]
The placement is great and I think Problems View should have its input in the same place (just with a bit of margin):

![Screenshot (325)](https://user-images.githubusercontent.com/9638156/91657635-319f3700-eacb-11ea-932c-0ea9cbb614ad.png)

**Comment by isidorn** [comment]
I did some refatctoring here on Friday and can not reproduce with latest insiders. Do you still see this?

**Comment by usernamehw** [comment]
Version: 1.49.0-insider (user setup)
Commit: f66741dc2b4944e153719bb48bcaa9c565cc40f7
Date: 2020-08-31T05:32:36.938Z

**Comment by usernamehw** [comment]
It seems like problems view filter can be in the header, but debug console and problems behave differently. Still no margin and the focus border is broken in debug console.

**Comment by usernamehw** [comment]
![demo](https://user-images.githubusercontent.com/9638156/91696899-f3605100-eb78-11ea-8f26-dafaa2144325.gif)

**Comment by isidorn** [comment]
Thanks for filling this. I have pushed a fix for the main issue.
The problems and the debug console still do not behave 100% the same when it comes to resize of the filter. We should probably align better in the future.

**Comment by usernamehw** [comment]
* ✅ Margin is in place
* ❌ Border is still not fixed (try using light color theme)

**Comment by isidorn** [comment]
For the border I have opened a new issue: https://github.com/microsoft/vscode/issues/105801
For the margin adding verified label based on your comment
