### ISSUE TITLE
[Webview view] select all selects text in editor instead of webview input

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#105670]
Testing #105764

1. Create webview view
1. Focus input
1. Press <kbd>Ctrl</kbd>+<kbd>A</kbd>

Expected: Focus is stays in a webview
Actual: Text in editor selected and focus shifted to the editor

![demo](https://user-images.githubusercontent.com/9638156/91653992-18d45880-eaae-11ea-8ac7-95ce36bed7ac.gif)

**Comment by usernamehw** [comment]
Not fixed for me. Still shifts focus to the editor.

**Comment by mjbvz** [comment]
Fixed the wrong thing
