### ISSUE TITLE
Scrolling very choppy after Win10 2004 update

### ISSUE THREAD

**Issue by narfanar** [microsoft/vscode#105640]
Issue Type: <b>Performance Issue</b>

Update to Win10 2004 with my current version of VSCode Insider.
Open a large workspace and try scrolling in any file. Very choppy.

VS Code version: Code - Insiders 1.49.0-insider (6384e3246884694cbc34eacc70281ada15e2c7f2, 2020-08-28T16:02:44.602Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (4.07GB free)|
|Process Argv|--crash-reporter-id 99e317c3-0ab7-4106-9d83-dcf6c481fe98|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   155	 19848	code-insiders main
    0	   271	  3192	   window (wmt14 (Workspace) - evaluate-conv.sh - Visual Studio Code - Insiders)
    0	    89	  1740	     "C:\Program Files\PowerShell\7-preview\pwsh.exe"
    0	    20	 13424	     watcherService 
    0	    11	 27160	       console-window-host (Windows internal process)
    0	    79	 14468	     searchService
    0	   156	 15496	     extensionHost
    0	    69	  7716	       "%USER%\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "%USER%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=15496
    0	    94	 22920	       electron_node server.js 
    0	    71	 25144	       electron_node server.js 
    0	   285	 26180	       electron_node bundle.js 
    0	     7	 16508	     console-window-host (Windows internal process)
    0	   193	  9060	   window (philly-expts (Workspace) - Settings - Visual Studio Code - Insiders)
    0	   115	  7292	     extensionHost
    0	    65	 21652	       electron_node server.js 
    0	    71	 27544	       "%USER%\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "%USER%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=7292
    0	    19	 10524	     watcherService 
    0	     6	 22900	       console-window-host (Windows internal process)
    4	    94	 15512	   shared-process
    2	    88	 16388	   window (Issue Reporter)
    0	    40	 19796	   utility
    1	   330	 22104	   gpu-process
    0	   191	 23684	   window (curriculum (Workspace) - main.py - Visual Studio Code - Insiders)
    0	   116	  3636	     extensionHost
    0	    65	  7420	       "%USER%\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "%USER%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=3636
    0	    65	 18152	       electron_node server.js 
    0	    66	 24856	       electron_node server.js 
    0	   110	 26340	       electron_node bundle.js 
    0	    13	 25632	     watcherService 
    0	     6	 13600	       console-window-host (Windows internal process)
    0	    24	 24248	   crashpad-handler
    0	   220	 24864	   window (deepcrit - attn_model.py - Visual Studio Code - Insiders)
    0	   137	 17336	     extensionHost
    0	    71	 18964	       "%USER%\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "%USER%\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=17336
    0	   163	 20244	       electron_node bundle.js 
    0	    14	 24872	     watcherService 
    0	     6	 20132	       console-window-host (Windows internal process)
```

</details>
<details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
Bookmarks|ale|11.3.1
better-toml|bun|0.3.2
indented-block-highlighting|byi|1.0.7
path-intellisense|chr|2.2.1
docs-yaml|doc|0.2.5
githistory|don|0.6.9
gitlens|eam|10.2.2
shell-format|fox|7.0.1
gc-excelviewer|Gra|3.0.40
todo-tree|Gru|0.0.178
language-cython|guy|0.0.6
latex-workshop|Jam|8.11.1
favorites|kdc|2.4.5
l13-diff|L13|0.27.0
bash-extension-pack|liz|0.0.4
bash-ide-vscode|mad|1.11.0
rainbow-csv|mec|1.7.1
csharp|ms-|1.23.1
python|ms-|2020.8.105045
vscode-pylance|ms-|2020.8.3
remote-ssh-edit-nightly|ms-|2020.8.19620
remote-ssh-nightly|ms-|2020.8.19620
remote-wsl|ms-|0.44.4
powershell|ms-|2020.6.0
git-semantic-commit|nit|2.0.0
cargo|pan|0.2.3
subtitles-editor|pep|1.0.4
bib|phr|0.3.0
qub-xml-vscode|qub|1.2.8
vscode-coconut|Qwe|0.0.1
vscode-yaml|red|0.10.1
perl|ric|2.1.0
rust|rus|0.7.8
powerquerymlanguage|sea|1.0.0
crates|ser|0.5.2
unique-window-colors|stu|1.0.51
rust-pack|Swe|0.2.29
latex-support|tor|3.2.0
terminal-tabs|Tyr|0.2.0
vscodeintellicode|Vis|1.2.10
markdown-all-in-one|yzh|3.2.0

(22 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
fyi @deepak1556

**Comment by deepak1556** [comment]
Does this issue appear when you launch with `--disable-extensions` ? If it does, please provide performance profile following

* Open devtools
* Go to Performance tab
* Enable advanced paint instrumentation 
<img width="722" alt="Screen Shot 2020-08-31 at 2 14 46 AM" src="https://user-images.githubusercontent.com/964386/91703897-c5a2ea00-eb2f-11ea-97fd-641b389348dd.png">

* Record
* perform scroll that shows slowdown

**Comment by narfanar** [comment]
Issue seems mostly gone after the 2020-09-02 update (which I got _just now_). I'll still see about the performance report if it resurfaces.
