### ISSUE TITLE
Blank terminal

### ISSUE THREAD

**Issue by Derrick98** [microsoft/vscode#105659]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Nothing seems to work in my terminal including the blinking cursor making it impossible to type anything

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz (2 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.58GB free)|
|Process Argv|--open-url -- vscode:extension/Lwlz.autofix|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
jslint|ajh|1.2.1
code-gnu-global|aus|0.2.2
vscode-standardjs|che|1.3.0
jshint|dba|0.10.21
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
autofix|Lwl|1.0.0
MagicPython|mag|1.1.0
csharp|ms-|1.23.1
python|ms-|2020.8.105045
cpptools|ms-|0.30.0-insiders3
js-debug-nightly|ms-|2020.8.2017
debugger-for-chrome|msj|4.12.10
java|red|0.65.0
LiveServer|rit|5.6.1
vscode-javascript-booster|sbu|14.0.1
python|tht|0.2.3
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.12.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.1
vscode-maven|vsc|0.24.1

</details>

**Comment by usernamehw** [comment]
Do you have Windows 10 as OS?

**Comment by KonstantinKlepikov** [comment]
try

"terminal.integrated.inheritEnv": true

... but i am not sure if this works for windows
