### ISSUE TITLE
TypeScript + Debug - synchronization request

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10560]
- VSCode Version: Code - Insiders 1.5.0-insider (2e54e84905a76b2278c7c0bccc86a69f03b2d5d4, 2016-08-15T06:04:11.629Z)
- OS Version: Darwin x64 15.6.0

It would be great to be able to synchronize TypeScript compilation process with Debug runner.

Currently when TS file is changed one need to make sure to wait when compilation finishes (`watch task`) and then to start Debugger session after that (otherwise it's very easy to start debugger on old js code).

It would be great if debugger could wait for compilation to finish (by default or via option in `launch.json`)

Also the flag to auto restart debugger on change in TS file would be very helpful

**Comment by weinand** [comment]
It is already possible to synchronise TypeScript compilation process with Debug runner.
Use 'nodemon' to restart node.js after JavaScript has changed (triggered by TypeScript compilation).
In VS Code use an 'Attach' lauch config and add a `"restart": "true"` attribute/value. This will make VS Code to restart the debug session whenever it detects that node.js was restarted.
