### ISSUE TITLE
unused arguments and "arguments" for typescript in vscode

### ISSUE THREAD

**Issue by mwambler** [microsoft/vscode#105638]
if vscode detects a reference to "arguments" in the body of a method or function, is it possible for it to set the individual arguments as being used? Below is an example where all the arguments are passed to a helper to create a parametrized value object for a db query. Note that id and value are grey since vscode doesn't recognize their use in the body of the function/method:

![image](https://user-images.githubusercontent.com/4339945/91636518-48f8fa00-e9cf-11ea-89ef-9c428d9b3e30.png)

**Comment by mjbvz** [comment]
This is not possible to infer statically. Try rewriting your code to not use `arguments` in this way
