### ISSUE TITLE
'revealFileInOS' is opening current focused file instead of the given URI

### ISSUE THREAD

**Issue by SrBrahma** [microsoft/vscode#105666]
- VSCode Version: 1.48.2
- OS Version: Ubuntu 20.04 (Linux x64 5.4.0-42-generic snap)

Steps to Reproduce:

1. I have a extension with a Tree view that the items have a context menu and an icon that executes vscode.commands.executeCommand('revealFileInOS', Uri.file(itsPath)).
2. The context menu always works right. The icon only works if there is no file focused in the VsCode Explorer menu. They call the same command. Looks like the context menu deselects the focused file and clicking the icon doesn't.

Looks like it's a similar problem to https://github.com/microsoft/vscode/issues/87804

Does this issue occur when all extensions are disabled?: Is an extension only issue.

**Comment by isidorn** [comment]
Correct. The file explorer is currently not respecting the passed URI when getting multi selected resources.
Code pointer https://github.com/microsoft/vscode/blob/bb6a1431d7b48d20cec0aa142ad6eb46bdfb440b/src/vs/workbench/contrib/files/browser/files.ts#L63

We might change that in the future.
revealFileInOS is not actual API so we migth break it's contract.
