### ISSUE TITLE
Don't delete files when replacing dir

### ISSUE THREAD

**Issue by nihiluis** [microsoft/vscode#105691]
Suppose you have two dirs.

<project>/server/http/middleware

has file test.go

Now you have the 2nd dir.

<project_second>/server/http/middleware

has file test2.go

If you drag the dir /server/http/middleware from <project_second> into <project>, test.go will be deleted.

This is not what I would expect after 15 years of using Windows and Linux. I know the message is clear on it, but UI should be better than that.

Please don't delete the already existing file OR if you do, please make the file recoverable. Just had this issue and had some progress wiped.

**Comment by isidorn** [comment]
This makes sense.
@bpasero can we do this on the fileService layer, or should I handle the mergining on the File Explorer level?

**Comment by bpasero** [comment]
@isidorn this cannot be done on the file service layer, it would require new API to adopt by every file system implementation out there to offer a new "merge" strategy.

**Comment by isidorn** [comment]
@bpasero thanks
Ok, assigning to September to investigate to add this to the Explorer.

**Comment by isidorn** [comment]
We are now using the `bulkEditService` for moving resources. In order to have this the explorer would first have to move all the resources inside it.
We accept a clean PR which potentially adds this functionality
Code pointer https://github.com/microsoft/vscode/blob/0a78fe165a37e264e8ade282cdb2f3d340968baa/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L1408

For now moving this to Backlog

**Comment by plainerman** [comment]
@isidorn, I would like to give this issue a shot (if help is still appreciated) :)

After investigating this issue for quite some time, I believe that the main change should *not* happen in a core util like `fileService.ts` but somewhere along:
https://github.com/microsoft/vscode/blob/5fcd9f7484549db8febcb7f3ac181c4a475f16c1/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L1487-L1490
In there, we could fetch all conflicting folders and recursively add them to the list of edits (`resourceFileEdits`). Files and folders without a conflict will end the recursive-call-chain. 

I also think, that users should have the decision whether to replace the folders (i.e. current behavior) or to _merge_ them.

I would like to add, that this issue does not occur when copying folders (instead as moving), as conflicts will get the suffix "copy" appended.

**Comment by isidorn** [comment]
@plainerman sounds great. Yeah I think you are spot on, this should be handled on the Explorer side.
Yeah the user decision for replace vs merge can either be a setting or a modal dialog. Probably a setting.
Best would be if you sketh out a PR and just ping me on it and we can contiue the discussion there. Let me know if that works for you.
Thanks for your help!

**Comment by plainerman** [comment]
Great, I have just created a draft PR where I would like to discuss a few things https://github.com/microsoft/vscode/pull/115054

**Comment by isidorn** [comment]
Thanks, let's continue the discussion there.

**Comment by isidorn** [comment]
We are transferring the ownership of a file explorer to a new engineer. So I am cleaning up issues which I am not 100% certain that we want to tackle. Due to that I am closing this as out of scope, so we have a clean slate.
We might reopen this in the future if we receive more feedback.
