### ISSUE TITLE
Relative path to "env" binary may break

### ISSUE THREAD

**Issue by moltar** [microsoft/vscode#105642]
**Describe the bug**

Every debug call is prefixed with an `env` setting. I am not entirely sure it is coming directly from this extension, but the fact that extension name is in the path, it leads me here :)

Example:

```
env 'NODE_OPTIONS=--require "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" ' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/var/folders/7v/v2jvmrwd3r94bw1vrg8r5nch0000gp/T/node-cdp.91805-3.sock","deferredMode":false,"waitForDebugger":"","execPath":"/Users/user/.nvm/versions/node/v12.18.2/bin/node","onlyEntrypoint":false,"fileCallback":"/var/folders/7v/v2jvmrwd3r94bw1vrg8r5nch0000gp/T/node-debug-callback-46fe6f46e7619851"}'
```

This leads to an error:

```
sort: No such file or directory
```

**To Reproduce**

Create a debugger with the following config and run it:

```
    {
      "name": "Debug Jest Tests",
      "type": "node",
      "request": "launch",
      // "args": [
      //   // "--runInBand"
      // ],
      "cwd": "${workspaceFolder}",
      "runtimeArgs": [
        "--inspect-brk",
        "${workspaceRoot}/node_modules/.bin/jest",
        "--runInBand"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      // "disableOptimisticBPs": true,
      // "program": "${workspaceFolder}/node_modules/.bin/jest"
    },
```

**VS Code Version:**

Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Additional context**

N/A

**Comment by connor4312** [comment]
We execute using the standard `runInTerminal` request, cc Andre

**Comment by moltar** [comment]
Right, but instead of executing `env` it should execute `/usr/bin/env`.
