### ISSUE TITLE
Jupyter automatically runs markdown cells when you click to another program. This makes copying from another source more time consuming than necessary.  

### ISSUE THREAD

**Issue by hannibal90** [microsoft/vscode#105692]
- VSCode Version: 1.48.2
- OS Version: Windows 10 and Ubuntu 20.04

Steps to Reproduce:

1. Run Jupyter kernel in VS Code
2. Type a paragraph in a Markdown cell
3. Select a different program, copy some text, and come back to VS Code

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Since you are using Stable, please file issues against Python extension which is currently providing the notebook feature.
