### ISSUE TITLE
[bug] Can not "Go to Definition" for CSS @import statements.

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#105608]
The [documentation says](https://code.visualstudio.com/docs/languages/css#_go-to-declaration-and-find-references) that we should be able to navigate `@import` statements, but this doesn't work for me.

```
Version: 1.47.1
Commit: 485c41f9460bdb830c4da12c102daff275415b53
Date: 2020-07-14T22:01:14.734Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.52-1-MANJARO
```

Steps to Reproduce:

1. Hover on an `@import` statement that points to a relative file.
2. Run `Go to Definition`
3. It says "No definition found".

Does this issue occur when all extensions are disabled?: **Yes**

![Screenshot from 2020-08-28 11-22-56](https://user-images.githubusercontent.com/297678/91603458-e138a580-e921-11ea-90f6-39fcd40de56d.png)

**Comment by aeschli** [comment]
Goto definition typically works on a symbols, not on links.

For links you press Ctrl-Click to navigate, as the link hover says. Does that work for you?
