### ISSUE TITLE
Better alignment of Sidebar components when Activity Bar is hidden

### ISSUE THREAD

**Issue by andreiborisov** [microsoft/vscode#105643]
- VSCode Version: 1.48.2
- OS Version: macOS Catalina 10.15.6

Does this issue occur when all extensions are disabled?: Yes

### Steps to reproduce.

1. Hide Activity Bar.

### The issue.

There is barely any space between the caret symbols inside Explorer and the window border.

![CleanShot 2020-08-29 at 18 48 04@2x](https://user-images.githubusercontent.com/13354491/91640730-60b09c80-ea28-11ea-8ba3-639767d42722.png)

Here is how elements are aligned inside the sidebar currently (they are not):

![CleanShot 2020-08-29 at 18 29 13@2x](https://user-images.githubusercontent.com/13354491/91640469-791fb780-ea26-11ea-976d-20b704f4d8b9.png)

### Proposed solution.

Tweak alignment so the carets are inline with a status bar Git symbol and Explorer top-level icons are inline with EXPLORER title text.

![CleanShot 2020-08-29 at 18 31 46@2x](https://user-images.githubusercontent.com/13354491/91640528-e4698980-ea26-11ea-8aae-fc2b00d26fa5.png)

This is a simple CSS tweak:

```css
#workbench\.view\.explorer > div > div > div.split-view-container {
  left: 9px;
  width: calc(100% - 9px);
}
```

In my opinion, it looks much cleaner.

**Comment by isidorn** [comment]
This should be the same across all trees for conistency.
I believe there have been other feature requests like this, though leaving up to @joaomreno to decide

**Comment by andreiborisov** [comment]
> This should be the same across all trees for consistency.

Absolutely, I’m just using Explorer as an example.

**Comment by joaomoreno** [comment]
This definitely isn't a widget-level fix.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog.We will probably not tackle this to be honest. Thanks
