### ISSUE TITLE
Treat SConstruct/SConscript files as python automatically

### ISSUE THREAD

**Issue by philosophicles** [microsoft/vscode#105623]
[SCons ](https://scons.org/) is a popular software build tool, a little like GNU Make, created with python. 

By default and convention, it uses build definition files named `SConstruct` and `SConscript` in a source code directory hierarchy. These files are basically python scripts, albeit with some SCons-specific idioms. 

VSCode should automatically recognize these special filenames and apply python language support, in much the same way that a file named `Makefile` is already recognized as special. 

I am aware that it's [easy to define this in Settings](https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language) for a particular install of VS Code, but these filenames are quite universal and unlikely to ever be used for something other than SCons.

**Comment by aaronfranke** [comment]
It also uses `SCsub` files as well, to allow splitting the SCons code into multiple files and for uses such as modules.

**Comment by mwichmann** [comment]
> It also uses `SCsub` files as well, to allow splitting the SCons code into multiple files and for uses such as modules.

`SCsub` is not a standard SCons thing.  You can call the subsidiary files anything you want, as calling them is done by passing a filename to a method call, `SConscript` is just the conventional name, but using it is very common.

**Comment by aeschli** [comment]
I'm not a Pythpn expert. Can you give me the complete list of filenames I should add to Python?

**Comment by philosophicles** [comment]
@aeschli yes, confirmed, just these two filenames please:

1. `SConstruct`
2. `SConscript`

_(Rationale: both the above are referenced many times in the official SCons documentation. SCsub is not referenced at all in same.)_

**Comment by bdbaddog** [comment]
Here's the default SConstruct file name variations from the manpage:
( https://scons.org/doc/production/HTML/scons-man.html )

`When invoked, scons searches for a file named SConstruct (it also checks alternate spellings Sconstruct, sconstruct, SConstruct.py Sconstruct.py and sconstruct.py in that order)`

**Comment by aeschli** [comment]
I added the two file names above and would leave it at that until we get requests. Hope that's ok.

**Comment by bdbaddog** [comment]
@aeschli  - Yup. Just figured I'd paste the definitive answer here for future reference.  Most build systems actually use SConstruct and SConscript.  Having VSCode recognize they're python files will certainly lessen the desire/need for SConstruct.py, etc.. Thanks!
