### ISSUE TITLE
******* Extension to disable plugins automatically

### ISSUE THREAD

**Issue by ProgrammerAuditore** [microsoft/vscode#105653]
They should include an extension to disable all extensions that are not necessary when programming in a programming language.
For example, if I am programming in web development, I want the Java, Python, etc. extensions to be automatically deactivated.
They should be organized by category for example web development, global extensions, etc.

**Comment by sandy081** [comment]
/duplicate

This feature is already requested. You can find it [here](https://github.com/microsoft/vscode/labels/extensions)
