### ISSUE TITLE
can't  open  the everything 

### ISSUE THREAD

**Issue by WLswert** [Microsoft/vscode#10566]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

today  i open the vscode ,but it display the black, like this:
![image](https://cloud.githubusercontent.com/assets/12693684/17685514/5b6bd5d0-6397-11e6-9e95-0da333f88035.png)

and All the options  can't use . I used the version of VSCode-win32-stable.zip

**Comment by alexandrudima** [comment]
@WLswert are there any errors showing up in the console at `Help > Toggle Developer Tools` (Last menu + 3rd from the bottom). Does VSCode start up when launching with `code --disable-extensions`? Do you see any errors in the console if launching code from a command prompt?

**Comment by WLswert** [comment]
I used the `code --disable-extensions` start up ,but it also don't work .
there are five errors in the console: 
`loader.js:136Loading "vs/workbench/workbench.main" failedt @ loader.js:136
loader.js:137Detail:  Error: No define call received from module vs/workbench/workbench.main.(…)t @ loader.js:137
loader.js:139Error: No define call received from module vs/workbench/workbench.main.
    at e._onLoad (loader.js:1103)
    at Object.callback (loader.js:1488)
    at e.triggerCallback (loader.js:1559)
    at loader.js:1553
    at loader.js:1763
    at tryToString (fs.js:414)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401)t @ loader.js:139
loader.js:141Here are the modules that depend on it:t @ loader.js:141
loader.js:142Array[1]0: "===anonymous1==="length: 1__proto__: Array[0]concat: concat()constructor: Array()copyWithin: copyWithin()entries: entries()every: every()fill: fill()filter: filter()find: find()findIndex: findIndex()forEach: forEach()includes: includes()indexOf: indexOf()join: join()keys: keys()lastIndexOf: lastIndexOf()length: 0map: map()pop: pop()push: push()reduce: reduce()reduceRight: reduceRight()reverse: reverse()shift: shift()slice: slice()some: some()sort: sort()splice: splice()toLocaleString: toLocaleString()toString: toString()unshift: unshift()Symbol(Symbol.iterator): values()Symbol(Symbol.unscopables): Object__proto__: Objectt @ loader.js:142`

**Comment by alexandrudima** [comment]
This usually indicates a corrupt installation of sorts.

Can you double check you have no left-over "dead" processes:
![image](https://cloud.githubusercontent.com/assets/5047891/17691230/9f071d12-6393-11e6-8459-91469b0b7cb5.png)

Can you double check that this file exists on disk at the location where you extracted the zip:
`your_folder_path\resources\app\out\vs\workbench\workbench.main.js` and is of 2,876,899 bytes.

Is it possible the zip extraction failed for some reason (i.e. antivirus blocking `.js` files, etc)

**Comment by WLswert** [comment]
thanks!
I replace it with the bak files ,and it's working now. It may be caused by not normally closed.
![image](https://cloud.githubusercontent.com/assets/12693684/17691410/d75034e6-63c6-11e6-843f-f87ec24ae725.png)

**Comment by alexandrudima** [comment]
@WLswert Did you install an extension that perhaps "messed up" VSCode's sources?

**Comment by WLswert** [comment]
yes, I  updated the vim extension yesterday , at that time it can be used.
but  today it had errors  when i opened the  VSCode

**Comment by alexandrudima** [comment]
Ok, closing for now as there's no action on our side.

It is pretty weird, if you ever figure out how those `.back` files got there and how `workbench.main.js` got to 0 bytes, please reopen.

**Comment by bpasero** [comment]
@WLswert did you have `vscode-icons` extension installed maybe?

**Comment by WLswert** [comment]
@bpasero  yes ,does it matter?

**Comment by mrmlnc** [comment]
@WLswert, yes. From `vscode-icons` docs:

> This extension modifies some VS Code files so use it at your own risk. Currently, icons are not supported by the extension functionality that VS Code provides so this extension solves this issue by injecting code into two files:

>  * workbench.main.js
>  * workbench.main.css

**Comment by WLswert** [comment]
@mrmlnc  oh ,thank you very much!
i got it .
