### ISSUE TITLE
Disable or remove options in new file

### ISSUE THREAD

**Issue by nsoria1** [microsoft/vscode#105661]
Hi! 👋

It looks like VSCode is adding some Jupyter features, which is probably great for people who care, but I don't think the current New File behavior should be the default for everyone who uses VSCode.

Every time I select "New File" from the menu now, I get a popup menu asking me if I want a Jupyter Notebook new file or a regular text file. I don't and won't ever need to create a new file for a Jupyter Notebook in VSCode, and I want to disable this choice so I can keep the previous behavior of just making a new file and letting me write stuff. This new behavior seems to be core to VSCode for some reason and I cannot find a way to remove or disable it. None of the menu options I tried remove this behavior.

Preferable behavior would be that this is not enabled by default, or there's some way to tell VSCode "disable everything that has to Jupyter", or there's a way to restore the original New File behavior so it just creates a new editor without a useless (to me) choice.

Even though I've uninstalled the jupyter notebook extension, it still prompts both options.

Thank you for considering this bug!

**Comment by nsoria1** [comment]
Thanks! I've checked and even though it's the same issue, it wasn't solved in the copied issue.

**Comment by gjsjohnmurray** [comment]
Yes, that one is still open and is currently assigned to someone for fixing. Hence closed this one as a duplicate.
