### ISSUE TITLE
Loaded Scripts source code does not show when debugging node against a remote process

### ISSUE THREAD

**Issue by rfossella** [microsoft/vscode#105695]
- VSCode Version: 1.48.2
- OS Version: Windows 10 & Windows 7 / Centos 7

Steps to Reproduce:

1. Start remote nodejs app running in docker under Centos
2. (Node app started via PM2 using  **node_args: ["--inspect=0.0.0.0:9229"]**)
3. Open necessary port 9229
4. Connect to container from Windows and successfully establish remote debugging session.

Does this issue occur when all extensions are disabled?: Yes

I have a nodejs app running in docker container in Linux. I am using VSCode in Windows 7&10 to remotely debug it. I successfully connect to the container and VSCode accurately displays remote logs in Debug Console. If I manually add a 'debugger' statement in the node code (in published docker image) I get the correct break in VSCode. Then, and only then, can I add dynamic breakpoints to ONLY that js file.

How do I get the code to stream down? I understand it is read-only and that's all I care about.

My launch.json file contains the following config:

```
{
    "type": "node",
    "request": "attach",
    "name": "Attach to Remote QA",
    "port": 9229,
    "address": "11.222.333.444",
    "localRoot": "${workspaceFolder}",
    "remoteRoot": "/opt/myApp",
    "protocol": "inspector",
    "sourceMaps": true
}
```
Thanks in advance for any assistance. Rob

**Comment by rfossella** [comment]
Anyone have experience getting this to work?

**Comment by weinand** [comment]
Loaded scripts view can only show the code that was actually loaded by the node runtime.
So files not yet accessed by the runtime will not show up there.

In general I suggest to use our great "Remote Development" extension that supports transparent debugging in Docker. In most cases it does not require any special setup and supports debugging without a need for "debugger" statements and the Loaded Scripts view.

But your approach with remote debugging and use of "localRoot" and "remoteRoot" properties should work fine as long as you have the source files available in your workspace. In this case the files in your docker container and the workspace will be mapped to each other by means of the "remoteRoot" and "localRoot" paths.
