### ISSUE TITLE
in remote-wsl running  image of docker  by  vscode 

### ISSUE THREAD

**Issue by Mhunter132** [microsoft/vscode#105644]
![微信截图_20200830000059](https://user-images.githubusercontent.com/46363359/91640992-180ed880-ea54-11ea-977c-81be46b80f7a.png)
![d90a1398f8cea5f5079cb04d119a0c1](https://user-images.githubusercontent.com/46363359/91641050-8358aa80-ea54-11ea-994b-6892cb7b7d99.png)

Steps to Reproduce:

1.link remote-wsl 

2. righ click to run  image of docker

Does this issue occur when all extensions are disabled?:  yes , when disconnect remote-wsl  ,it will works out  

i guess it is maybe   slash and backslash causes this question

**Comment by Mhunter132** [comment]
i have review some of issues but  there are not the same as my issue

**Comment by Mhunter132** [comment]
a little bit minutes passed i  add  and chenge some variate of setting.json ,but still not work 
{
 "terminal.integrated.shell.windows":"c:\\Windows\\System32\\wsl.exe",
    "terminal.integrated.shell.linux": "/bin/bash ",
    "terminal.integrated.cwd":"c:\\Windows\\System32\\wsl.exe",
    "terminal.integrated.env.linux":{
      "VSCODE_INTEGRATED_TERMINAL": "true"
    },
    "terminal.integrated.inheritEnv":true,
    "terminal.integrated.windowsEnableConpty":false,
}
--------------------------------------------------------------------------
Executing task: docker run --rm -d  -p 7700:7700/tcp getmeili/meilisearch:latest <

The terminal process failed to launch: Path to shell executable "c:\Windows\System32\wsl.exe" does not exist.

Terminal will be reused by tasks, press any key to close it.

**Comment by aeschli** [comment]
Maybe you need to file the issue against the Docker extension as they know better what is expected to work how.
By default docker is a UI extension. That means even when you are in a WSL window, the extension still runs in Windows. That means `docker` from Windows is used.
When I try that setup: I get a warning:
![image](https://user-images.githubusercontent.com/6461412/98120919-e2042f80-1eae-11eb-8b51-cbe78494aac1.png)

'Switch to WSL' will allow you to install the docker extension on the WSL side. With that `docker` from the WSL distro will be used.
![image](https://user-images.githubusercontent.com/6461412/98121369-7d95a000-1eaf-11eb-9b01-b1806e83ebd3.png)
