### ISSUE TITLE
Random tooltips from background windows not disappearing

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode#105613]
- VSCode Version: 1.48.2
- OS Version: Windows 2004

**Steps to Reproduce:** The issue occurs highly sporadically and could not yet be reproduced. It occurs very seldomly, but when it occurs, it can be extremely annoying. When it occurs, there will appear some random tooltip with the default Electron design somewhere on the screen. If you go through all your open VS Code windows, maybe you are lucky and find the source of the tooltip. By hovering that widget again, the tooltip is finally destroyed. To illustrate, in my example, one tooltip said "20 Errors".

From what we know, the issue is connected to the use of touchscreens on Windows.

The same problem was already reported for Chromium here: <https://bugs.chromium.org/p/chromium/issues/detail?id=1052238#makechanges>. I have no clue of Electron development, but there is any common denominator with Chromium, isn't it?

**Comment by Poopooracoocoo** [comment]
Upstream bug (in Chromium): https://bugs.chromium.org/p/chromium/issues/detail?id=1052238

**Comment by deepak1556** [comment]
Thanks for the report, tooltip support does come from chromium, electron doesn't handle it. I will keep this issue open to track the chromium issue filed. Do update if you find a reliable repro, thanks!

**Comment by Poopooracoocoo** [comment]
virtual desktops are another common factor

**Comment by Poopooracoocoo** [comment]
@deepak1556 Could you get in touch with the people who work on Edge for desktop? They should look at this. Filing feedback every few months is pointless. ~~speaking of virtual desktops i still cant get over all the explorer crashes since that rewrite~~

**Comment by DragoCubed** [comment]
@deepak1556 Uh. Are you there? Can't you get in contact with Windows developers??? What's the point of VS Code being from MS?

**Comment by deepak1556** [comment]
Closing as upstream issue has been resolved.

**Comment by Poopooracoocoo** [comment]
For some reason Chromium still seems to send a touch event to all open windows?

**Comment by LinqLover** [comment]
@deepak1556 Would it be possible to share a link to the upstream patch that you found?
