### ISSUE TITLE
In terminal, shift+cmd+a selects all, even if assigned to something else

### ISSUE THREAD

**Issue by jacobweber** [microsoft/vscode#105607]
Issue Type: <b>Bug</b>

When the Terminal is focused, shift+cmd+a runs the command assigned to cmd+a (Terminal: Select All).

This doesn't happen in a normal editor; shift+cmd+a doesn't run the command assigned to cmd+a (Select All).

This becomes an issue if I assign a custom command to shift+cmd+a; when I press that combination with the Terminal focused, it runs my custom command AND selects all text in the terminal.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.98GB free)|
|Process Argv|-psn_0_307275|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.2.0
ng-template|Ang|0.1000.8
vscode-intelephense-client|bme|1.5.4
npm-intellisense|chr|1.3.0
dart-code|Dar|3.13.2
mustache|daw|1.1.1
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
vscode-powertools|ego|0.61.0
php-debug|fel|1.13.0
vscode-favorites|how|1.8.0
vscode-hexdump|ili|1.8.2
svn-scm|joh|2.12.4
vscode-apache|mrm|1.2.0
python|ms-|2020.8.105045
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
debugger-for-chrome|msj|4.12.10
java|red|0.65.0
vscode-yaml|red|0.10.1
slack|soz|0.0.14
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.12.0
vscode-java-pack|vsc|0.10.0
vscode-maven|vsc|0.24.1
sync-rsync|vsc|0.36.0
jinja|who|0.0.8

</details>

**Comment by chenjigeng** [comment]
After a few hours of debugging, I think xterm is the cause of this problem.

xterm only judges by command + a, there is no strict comparison

![image](https://user-images.githubusercontent.com/14784326/100468031-88d69700-310e-11eb-85a6-14581a32c103.png)

**Comment by Tyriar** [comment]
Not planning on another xterm.js update for Jan, pushing to Feb.
