### ISSUE TITLE
Slow opening a C# file across the network

### ISSUE THREAD

**Issue by gstar42** [Microsoft/vscode#10562]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1. right click in explorer and 'open with code'
2. wait ~ 8 seconds

(doing the same with notepad++ takes less than 2 seconds

The file is a 45 line C# program.

**Comment by bpasero** [comment]
Pretty much limited in terms of node.js IO performance.
