### ISSUE TITLE
Code highlighting color issue for PHP for function named "fn"

### ISSUE THREAD

**Issue by ottopic** [microsoft/vscode#105742]
- VSCode Version: 1.48.2
- OS Version: 10.15.6

![Schermata 2020-08-31 alle 17 19 09](https://user-images.githubusercontent.com/5537554/91737069-de9eb000-ebae-11ea-814a-86b79128d8f0.png)

**Comment by roblourens** [comment]
Is it legal to have a function named `fn`? I think that's a reserved keyword. Can you share the full code?

**Comment by ottopic** [comment]
It's legal it isn't reserved keyword. 

```
<?

function fn(){
	// do something
};

?>
<div><?=fn()?></div>
```

**Comment by roblourens** [comment]
Moved to https://github.com/atom/language-php/issues/401
