### ISSUE TITLE
Test webview view api proposal

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#105764]
Refs #46585

- [x] Mac @sbatten
- [x] Linux @RMacfarlane 
- [x] Windows @sandy081

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23105764%0A%0A)

---

## Overview

The new webview view API allows extensions to contribute views build on webviews. For this exploratory test plan item, try using the new API and discovering what works and what doesn't. Areas to focus on:

- Start with the [webview view extension sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/webview-view-sample)

- Review the docs for the new apis in `vscode.proposed.d.ts`

- Look at webview view lifecycle (and showing and hiding view)

     - Does the dispose lifecycle make sense?
     - Are events for show/hide fired when you expect?

- Look at state management for the webview views

    - Make sure that webview state is persisted when: vscode is reloaded, a view is collapsed, a view is moved, a view is hidden.
    - Try using `retainContextWhenHidden`

**Comment by sandy081** [comment]
I used `retainContextWhenHidden` but did not understand what difference it is making in the example. It would be nice if there is a sample that demonstrates it.
