### ISSUE TITLE
Make 'download' in file explorer an API

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#105751]
There's a 'download' button in the file explorer when connecting vscode to remote:
![image](https://user-images.githubusercontent.com/44103947/91750179-81d3d300-eb77-11ea-9dde-d808ffadc5e8.png)

Currently to download a file from remote in an extension, a file server is needed on the remote. Making this download button an API would greatly simply such work in extensions.

**Comment by bpasero** [comment]
I would think that `vscode.fs` covers this + maybe some other API we have to produce a external URI.

**Comment by jrieken** [comment]
Not that I understand the issue. Are you an UI extension and want to download files? Did you try the `vscode.workspace.fs` API for that? It should allow you to fetch a file

**Comment by xisui-MSFT** [comment]
Yes we want to download a file in the UI extension. So workspace.fs.readFile + writeFile work in this case? Does the download button do the same thing, and would this method have any impact on the performance of vscode?

**Comment by jrieken** [comment]
> Does the download button do the same thing, and would this method have any impact on the performance of vscode?

More or less yes. For best performance use the `fs.copy` function

**Comment by jrieken** [comment]
closing as question since we have everything that's needed here
