### ISSUE TITLE
Connecting to ssh server uses wrong host name

### ISSUE THREAD

**Issue by justageek** [microsoft/vscode#105765]
- VSCode Version: 1.48.2
- OS Version: Mac OS 10.14.6

Steps to Reproduce:

1.  Try to connect to my host brian@brian.development.cashtn.com
2.  The password prompt says "enter password for brian@development.cashtn.com" which is the wrong host name.

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
This prompt assumes that you are providing a hostname or the name of a host in your SSH config file. I recommend adding this configuration to your ssh config file, details here https://code.visualstudio.com/docs/remote/ssh#_remember-hosts-and-advanced-settings
