### ISSUE TITLE
Intellisense for es6 class members doesn't work?

### ISSUE THREAD

**Issue by DenysYefimenko** [Microsoft/vscode#10578]
- VSCode Version: 1.4
- OS Version: Windows 10

Steps to Reproduce:

Intellisense for class members defined in es6 class constructor don't appear in class functions. 
It works if I use prototype syntax.

![prototype_intellisense](https://cloud.githubusercontent.com/assets/14803329/17696537/aad9a69a-63b7-11e6-9cfc-e2daeff75ba4.png)
![es6class_intellisense](https://cloud.githubusercontent.com/assets/14803329/17696544/b3ace6c4-63b7-11e6-940f-5e05556eee61.png)

**Comment by waderyan** [comment]
Good find. Moving to TypeScript as this is a Salsa issue.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10373
