### ISSUE TITLE
[Snap] File chooser is laggy when changing selection

### ISSUE THREAD

**Issue by ninja-** [microsoft/vscode#105728]
- VSCode Version: 1.48.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Install vscode snap, use wayland
2. Open vscode file/folder opener
3. Try selecting different files
4. You should see a lag between changing selected files

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Does not reproduce on flatpak version.

**Comment by Tyriar** [comment]
Likely an issue with the snap system and/or its interface with Electron.

**Comment by deepak1556** [comment]
Can you confirm if the insiders version has the issue https://code.visualstudio.com/insiders/

**Comment by ninja-** [comment]
The issue does not happen on non-sandboxed version

**Comment by deepak1556** [comment]
Can you also confirm if the insiders snap build has the issue ?

**Comment by ninja-** [comment]
@deepak1556 it does

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/99419
