### ISSUE TITLE
Up and down arrow key does not work in integrated terminal when using ubuntu bash as an integrated terminal.

### ISSUE THREAD

**Issue by sameerkattel** [Microsoft/vscode#10579]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1. // Place your settings in this file to overwrite the default settings
{
    **_"terminal.integrated.shell.windows": "\\WINDOWS\\sysnative\\bash.exe"_**
}
2. Open integrated terminal.
3. Enter some command in the terminal.
4. Try to navigate the history using up key and this does not function.
5. I also tried to navigate through a file in vi in the integrated term using up and down arrow key . This also does not function.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/BashOnWindows/issues/770
