### ISSUE TITLE
React Code Highlighting issue

### ISSUE THREAD

**Issue by vinodsai-a** [microsoft/vscode#105707]
Issue Type: <b>Bug</b>

React code highlighting issue for empty tag </>. It works properly if we use "Typescript React". "Javascript React" has a problem. 

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (1.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
aws-toolkit-vscode|ama|1.13.0
vscode-intelephense-client|bme|1.5.4
simple-react-snippets|bur|1.2.3
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
es7-react-js-snippets|dsz|2.8.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.2
react-native-react-redux|EQu|2.0.4
prettier-vscode|esb|5.5.0
vs-code-xml-format|fab|0.1.5
php-debug|fel|1.13.0
flow-for-vscode|flo|1.5.0
shell-format|fox|7.0.1
todo-tree|Gru|0.0.178
react-native-snippet|jun|0.5.6
git-tree-compare|let|1.9.2
aws-cli-configure|mar|0.3.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.5.0
mssql|ms-|1.9.0
python|ms-|2020.8.105045
remote-wsl|ms-|0.44.4
debugger-for-chrome|msj|4.12.10
vscode-react-native|msj|0.17.0
vscode-codedeploy|mzi|0.5.3
java|red|0.65.0
addDocComments|ste|0.0.8
move-ts|str|1.12.0
serverless-ide-vscode|Thr|0.5.26
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.12.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.1
vscode-maven|vsc|0.24.1
gitblame|wad|4.2.0
vscode-todo-highlight|way|1.0.4

</details>

![image](https://user-images.githubusercontent.com/28802436/91693973-7d181a80-eb89-11ea-845d-82bf26413ac7.png)
![image](https://user-images.githubusercontent.com/28802436/91694012-94570800-eb89-11ea-8f38-f6daf9ac00c6.png)

**Comment by mjbvz** [comment]
This is very likely caused by the Babel extension you have installed. It is 4 years old and seemingly unmaintained
