### ISSUE TITLE
Test: Screencast mode - Customize keyboard overlay timeout period

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#105723]
Refs: #105160 

- [x] anyOS @aeschli
- [x] anyOS @dbaeumer

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23105723%0A%0A)

---

We've added settings to customize the timeout period (screencastMode.keyboardOverlayTimeout) of the keyboard overlay in screencast mode. Enable `Screencast Mode` using the command palette and use the following steps to validate the two new settings:

* Open the `Screencast Mode` settings and locate the `Keyboard Overlay Timeout` setting
* Validate that the default value of the setting is 800.
* Validate that you can only specify numbers for the setting.
* Validate that you cannot set values outside the range of [500, 5000].
* Change the setting value and confirm that the keyboard overlay timeout updates.

**Comment by dbaeumer** [comment]
Works as advertised. Only question: why do we limit it to 5 seconds?

**Comment by lszomoru** [comment]
Thanks! No real reason other than I wanted to pick a reasonable upper limit.
