### ISSUE TITLE
vscode test debug can not debug step by step

### ISSUE THREAD

**Issue by mlicheng** [microsoft/vscode#105718]
Background: a node backend project written by Typescript, i wanna debug unit test written with Mocha & TypeMoq. 
    when i set the breakpoint and run , it can stopped at the breakpoint , but on the debug tools bar `step over`, `step into`,`step out` can not be clicked, it has been disabled , and the debug VARIABLES flash away, and then the debug VARIABLES is empty.

```
.vscode/launch.json
{
            "type": "node",
            "request": "launch",
            "name": "Test",
            "runtimeArgs": [
                "-r",
                "ts-node/register/transpile-only"
            ],
            "program": "${workspaceFolder}/test/bootstrap.ts",
            "args": [
                "--spec",
                "./**/es-plugin.spec.ts"
            ]
}
```
- VSCode Version:1.48.2
- Node.js: v10.18.1
- OS: Darwin x64 19.6.0

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
@isidorn when do we disable these buttons? I'm not sure how the debug adapter effects these states.

**Comment by isidorn** [comment]
@connor4312 `step over`, `step into` and `step out` are only enabled when the program is paused. So if a debug adapter has sent out a `stopped` event.
@mlicheng can you please share a minimal repository which we can clone and get into this state?
