### ISSUE TITLE
Notebook diff says the whole notebook changed

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#105778]
- Open `api.github-issues`
- Change one cell
- Open the notebook diff
- The whole left side is deleted, the whole right side is added

![image](https://user-images.githubusercontent.com/323878/91782005-c0d24a80-ebb0-11ea-895a-78aa4c37f65c.png)

**Comment by rebornix** [comment]
Good catch. Not sure what's wrong with LCS diff algorithm.

**Comment by rebornix** [comment]
No, it's me ;(
