### ISSUE TITLE
VS code window gets freezed

### ISSUE THREAD

**Issue by ChennaiArun** [microsoft/vscode#105713]
Issue Type: <b>Performance Issue</b>

Hi, Do not know when or what makes the window to get freezes. I need to close the editor and restart to make it work. Kindly support to rectify the issue.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    77	 24584	code main
    0	    60	  7468	   window (Issue Reporter)
    0	    14	 10872	   electron-crash-reporter
    0	    26	 11728	   utility
    0	    75	 11944	   shared-process
    0	   185	 22244	   window (index.html - D014_ec - Visual Studio Code)
    0	    38	 14408	     searchService
    0	    95	 21836	     extensionHost
    0	   117	  8204	       "C:\Users\TKAP00354\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\TKAP00354\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=21836
    1	    34	 24044	       electron_node server.js 
    1	    38	 28860	       electron_node server.js 
    0	    12	 28404	     watcherService 
    0	     9	 12728	       console-window-host (Windows internal process)
    0	   159	 27280	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - D014_ec - Visual Studio Code)
|    Folder (D014_ec): 24 files
|      File types: png(16) php(2) sql(2) json(1) html(1)
|      Conf files: launch.json(1)
|      Launch Configs: php(2);
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|11.3.1
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
vsc-material-theme|Equ|32.8.0
prettier-vscode|esb|5.5.0
php-debug|fel|1.13.0
debugger-for-chrome|msj|4.12.10
indent-rainbow|ode|7.4.0
vscode-css-peek|pra|4.0.0
LiveServer|rit|5.6.1
vba|spe|1.6.2
code-spell-checker|str|1.9.0
bootstrap-v4-snippets|Zac|1.1.3
html-css-class-completion|Zig|1.19.0

</details>

**Comment by RMacfarlane** [comment]
@ChennaiArun Can you help us narrow down the issue by trying
- Disabling all extensions temporarily
- Seeing if different folders have the same behavior
- Temporarily removing your settings

https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by interstates21** [comment]
Same issue. All of the extensions are disabled. Probably appeared with the update around 2 weeks ago

**Comment by AlCalzone** [comment]
Same thing happens here. Disabling extensions and removing settings does not really make sense in my case, since the problem sometimes happens after several minutes or hours of working with VSCode.

**Comment by ChennaiArun** [comment]
Hi,
After long time, again the same issue surfaced. Today I got the updated to
1.49.0 version. Till now haven't disabled any extentions.

Arun

**Comment by ChennaiArun** [comment]
The same error re surfaced after today's update 1.49.1.

Regards
Arun

**Comment by kieferrm** [comment]
Unfortunately, none of the information provided is actionable. Comment https://github.com/microsoft/vscode/issues/105713#issuecomment-687607344 seems to get the closest but misses concrete steps. If any of you can provide some, please file a new issue. Thanks a ton!
