### ISSUE TITLE
Trusted Types compatibility: script for identifying violations

### ISSUE THREAD

**Issue by annkamsk** [microsoft/vscode#105747]
As mentioned in the #103699 thread by @jrieken, there is a need for a tool that would help developers engaged in the VSCode project identify the Trusted Types violations. This can be achieved by adding [tsec](https://github.com/googleinterns/tsec) as a devDependency and an appropriate yarn script.

**Comment by jrieken** [comment]
I have also added a task-definition so that tsec errors show in the editor itselfs

<img width="1472" alt="Screenshot 2020-09-01 at 13 07 22" src="https://user-images.githubusercontent.com/1794099/91842287-16abfe80-ec54-11ea-8a4f-01d8569ad93f.png">
