### ISSUE TITLE
Font not rendering correctly in Windows

### ISSUE THREAD

**Issue by mahaveer0496** [microsoft/vscode#105712]
- VSCode Version: 1.48.2
- OS Version: windows version 2004 (OS Build 19041.450)

Steps to Reproduce:
1. Use DankMono font with Night Owl Light theme in both Codesandbox and VSCode

Does this issue occur when all extensions are disabled?: **Yes**

Settings Used in both VScode and Codesandbox
```js
{
  "editor.formatOnSave": true,
  "editor.fontSize": 20,
  "editor.fontFamily": "dm, Menlo, Monaco, 'Courier New', monospace",
  "editor.tabSize": 2,
  "editor.minimap.enabled": false,
  "workbench.editor.openSideBySideDirection": "down",
  "svelte.plugin.typescript.diagnostics.enable": false,
  "typescript.locale": "en",
  "javascript.autoClosingTags": false,
  "typescript.autoClosingTags": false,
  "html.autoClosingTags": false,
  "typescript.tsserver.useSeparateSyntaxServer": false,
  "workbench.colorTheme": "Night Owl Light",
}
```

Screenshots to compare 

**VSCode**
![image](https://user-images.githubusercontent.com/23198481/91697571-fa925980-eb8e-11ea-87ee-ae76035b0575.png)

**Code Sandbox**
![image](https://user-images.githubusercontent.com/23198481/91697625-10a01a00-eb8f-11ea-80ed-7860b1be5899.png)

The font is a lot smoother in Codesandbox.

**Comment by alexdima** [comment]
@mahaveer0496 Does this also reproduce with our insiders build (the insiders build uses a newer Electron version) -- https://code.visualstudio.com/insiders/ ?

**Comment by mahaveer0496** [comment]
@alexdima Yes with insiders as well 
![image](https://user-images.githubusercontent.com/23198481/91753634-cac27080-ebe5-11ea-9194-c89f474861c2.png)

```
Version: 1.49.0-insider (user setup)
Commit: f66741dc2b4944e153719bb48bcaa9c565cc40f7
Date: 2020-08-31T05:32:36.938Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by alexdima** [comment]
@mahaveer0496 Could you please also try in Chrome to open https://vscode-web-test-playground.azurewebsites.net/ and configure it with the same font family? Please let us know what Chrome version you tried and how it rendered.
