### ISSUE TITLE
createFileSystemWatcher did't work 

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode#105711]
I want to use `createFileSystemWatcher` to monitor my file `"compile_commands.json"` , so i use it as follows.
```javascript
const compileCommandsPath = vscode.workspace.rootPath ? vscode.workspace.rootPath : "";
const compile_path = path.join(compileCommandsPath, "compile_commands.json")
this._fileSystemWatcher = vscode.workspace.createFileSystemWatcher(compile_path);
this._fileSystemWatcher.onDidCreate(() => {
      console.log("in file system watcher onDidCreate");
    });
```
But when i create the compile_commands.json, it has no response. Is there any wrong in my using?  Thanks a lot. 
By the way, my engine is `1.42.0`
```json
 "engines": {
    "vscode": "^1.42.0"
  },
```

**Comment by jrieken** [comment]
glob issue?

**Comment by Abbyyan** [comment]
> To rule out path issues, ensure you are using `RelativePattern` instead of constructing the path.

It's wired that i use current workspace to create the `createFileSystemWatcher ` in my extension. It doesn't work in my opened folder, but when i create a `compile_commands.json` under the folder where my extension's installed, the trigger response. How can i watcher the files under my opened folder please?

**Comment by bpasero** [comment]
@Abbyyan ah so this file is not inside the workspace? we do not support that currently, can you confirm?

**Comment by Abbyyan** [comment]
> @Abbyyan ah so this file is not inside the workspace? we do not support that currently, can you confirm?

The file is under the opened workspace. I can't find why it watch the files in my extension rather than the opened workspace. Because the file may sometimes not inside the workspace, so i change to use `fs.watch` to watch the files like [this](https://thisdavej.com/how-to-watch-for-files-changes-in-node-js/). Anyway, thanks a lot.
