### ISSUE TITLE
Publish to GitHub when repository is already initialized asks if I want to ignore .git

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#105708]
1. Initialize a new repository locally with some commit.
2. Publish to GitHub.
3. Being asked if I want to ignore the `.git` folder. 🐛 
4. `.gitignore` generated with `.git` in it and pushed to new remote.

**Comment by joaomoreno** [comment]
This is strange, since we won't ask to generate a gitignore file if the repository is already detected by VS Code. Did VS Code not detect your just-initialized repository?

**Comment by chrmarti** [comment]
Just reproduced by:
- Open empty folder.
- Add some files (a .devcontainer config in my case).
- `git init, add, commit` in the terminal.
- Publish to GitHub via Command Palette.
- Seeing:
![image](https://user-images.githubusercontent.com/9205389/92081502-7379f700-edc3-11ea-9be4-f38b016f9d41.png)

Canceled and reran after checking the SCM viewlet looks initialized:
![image](https://user-images.githubusercontent.com/9205389/92081661-b63bcf00-edc3-11ea-9466-fc61747401c5.png)
