### ISSUE TITLE
Python 3.8 Support

### ISSUE THREAD

**Issue by datadaly** [microsoft/vscode#105781]
Issue Type: <b>Feature Request</b>

Again, Microsoft is not leading but trailing development.  Microsoft lost the browser war because they did not accept any standards.  Now Visual Studio does not support Python 3.8.  I will uninstall Microsoft Visual Studio Code and switch all of my students over to Pycharm for Python.  I wish this product luck future as it now old technology.  Python is the one of the fastest growing computer languages.  Microsoft has missed the mark again.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

**Comment by Tyriar** [comment]
The Python extension says it supports >= v3.6 https://github.com/microsoft/vscode-python, if you want to draw attention to a lack of support you should do it in that repository.

/cc @DonJayamanne

**Comment by naughtong** [comment]
I can use python 3.8 with visual studio 2019 but I run into problems when trying to use Python/C++ mixed-mode debugging.
It is surprising that Microsoft is taking for long, there were plenty of issues reported over a year ago for Python 3.8.

**Comment by Tyriar** [comment]
@naughtong you should report to the python extension team as mentioned above

**Comment by naughtong** [comment]
Thanks, I posted on the ink that you mention:  https://github.com/microsoft/vscode-python

**Comment by datadaly** [comment]
Gerard:

 

Microsoft does not support F-string in Python 3.8.  This is one of the best features they have developed.  I have instructed my students that I do not recommend using Microsoft Visual Code for Python .

This falls along the same line of the Microsoft browsers.  The lack of the W3C support in their development of their browsers could be why Chrome has 69% of the market share compared to Microsoft’s 7% share.

It appears Microsoft need to stop and smell the roses.

 

Garry Daly

**Comment by Tyriar** [comment]
@datadaly you really should report to the Python team _who can actually do something about it_ as it seems your issue differs from @naughtong's. https://github.com/microsoft/vscode-python/issues/14131
