### ISSUE TITLE
Typescript freezes and never being initialized

### ISSUE THREAD

**Issue by vtereshyn** [microsoft/vscode#105792]
Typescript freezes and never being initialized at the random situation. Restarting doesn't help. The only thing that can fix that issue is close/open VSCode. But sometimes after opening a random typescript file the issue repeats. 

I already tried to disable/enable built in typescript plugin but nothing helps to get rid of this issue. LMK if I can provide more information

Thank you in advance

![image](https://user-images.githubusercontent.com/32247411/91813489-7518b300-ec3b-11ea-8c22-04faf5f4c527.png)

**Comment by mjbvz** [comment]
Please fill out the issue template

/needsMoreInfo

Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
