### ISSUE TITLE
Linux: Running code-oss out of sources creates client_id file

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#105743]
> There is a client_id file generated from electron but that should be under the crash reporter directory, the default one should be under user data dir unless the path is configured via --crash-reporter-directory <path> flag

**Comment by deepak1556** [comment]
`client_id` file is used by the crash reporter code in chromium, but the bug here is that it gets created under the current directory by default.

**Comment by weinand** [comment]
For an explanation please see https://github.com/microsoft/vscode/issues/105743#issuecomment-683865682

**Comment by shaneturner** [comment]
Confirmed on Ubuntu 20.04

**Comment by joaomoreno** [comment]
Oh man this is soooo annoying.

**Comment by joaomoreno** [comment]
Added `client_id` to my local `.git/info/exclude` list.

**Comment by jhpratt** [comment]
Providing a second confirmation of this behavior on Ubuntu 20.04.1.
