### ISSUE TITLE
[javascript] An incorrect color scheme is selected for function argument names

### ISSUE THREAD

**Issue by mykola-mokhnach** [microsoft/vscode#105703]
- VSCode Version: 1.48.2
- OS Version: MacOS 10.15.6

Steps to Reproduce:

1. Load the following js code snippet into VSCode:

```js
import _ from 'lodash';

function isSubClass (candidateClass, superClass) {
  return _.isFunction(superClass) && _.isFunction(candidateClass)
    && (candidateClass.prototype instanceof superClass || candidateClass === superClass);
}
```

Actual result:

The color of `candidateClass` and `superClass` arguments in the second row is different from the one in the first row:
<img width="674" alt="highlight" src="https://user-images.githubusercontent.com/7767781/91688079-783f7080-eb61-11ea-81df-70def674d7f7.png">

Expected result:

The color of `candidateClass` and `superClass` arguments in the second row should be the same as in the first row.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
@aeschli Looks like semantic highlighting. On the first line of the return, `candidateClass` is tagged `parameter`. On the second line, it is tagged `function`

**Comment by aeschli** [comment]
TypeScript finds out that after the the positive  `isFunction` test, candidate must be a function.
Semantic highlighting reflects that information.

The hover shows the same information.

**Comment by mykola-mokhnach** [comment]
Thanks for looking into that @aeschli 

For me the current behaviour looks like a bug. I don't expect function arguments highlighing to be changed inside of the function body. This is probably fine for local vars, but arguments should keep their color, especially for the cases where these are not visible in the same viewport due to scrolling.

**Comment by mykola-mokhnach** [comment]
Also reassigning of function argument values is considered being an antipattern, but the current highlighting logic does support that antipattern in some sense.
