### ISSUE TITLE
JavaScript string with a double slash in HTML attribute will display as a comment

### ISSUE THREAD

**Issue by Namorzyny** [microsoft/vscode#105779]
- VSCode Version: 1.48.2
- OS Version: Microsoft Windows [Version 10.0.19041.450]

Steps to Reproduce:

1. Input some code like: `<input type="button" value="text" onclick="location.href='https://www.google.com'">`
2. The code will display as a comment:

![コメント 2020-09-01 083349](https://user-images.githubusercontent.com/17642329/91781851-fff2b100-ec2d-11ea-8833-37036e90eec5.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
The embedded JavaScript grammar acts strange here.
It's in scope `string quotes.single.js` but seems to end that scope at `:`

![image](https://user-images.githubusercontent.com/6461412/91822503-2f0e2000-ec38-11ea-9692-9be66afa012b.png)

**Comment by alexr00** [comment]
Not sure what's going on here. It only occurs if the `//` is in there. The character before the `//` will get `invalid.illegal.newline.js` but I don't know why. Opened an issue for the owners of the html grammar to see if they know more: https://github.com/textmate/html.tmbundle/issues/113
