### ISSUE TITLE
NotebookTextModel debt

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105735]
The `NotebookTextModel` is an important backbone of the notebooks model and therefore we should cleanup some debt that has accumulated:

* [x] `NotebookTextModel#selections` is a view/editor property and not a model property
* [x] the `this._onDidModelChangeProxy`-event in combination with `emitToExtHost`. There should be no difference is model changes that go to the extension host and other subscribers/consumers. All events should be equal and `mainThreadNotebook` is just one of many consumers which special role is to manage a "copy" in the extension host
* [x] some duplication in how cells are inserted, removed, and edited. We should make `applyEdit` the one-stop-shop.
* [x] a notebook text model knows if its dirty and emit corresponding events. One could argue that dirty-state manage is the business of `NotebookEditorModel` which is already doing saving etc. 
* [x] every change of the version id must be forwarded to the extension host (see https://github.com/microsoft/vscode/issues/105624#issuecomment-684858993)

**Comment by rebornix** [comment]
nice, this issue now has an older brother/sister https://github.com/microsoft/vscode/issues/105523

**Comment by rebornix** [comment]
The only missing part now is Undo/Redo around outputs. The reason that we didn't wrap it into Undo elements yet is it might change how outputs are updated during execution.
