### ISSUE TITLE
Test: Add `in` operator support to when clauses

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#105777]
Refs: #97544

- [x] anyOS @bpasero
- [x] anyOS @alexr00

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23105777%0A%0A)

---

Create a simple extension that optionally shows a command depending on if 1 context key's value exists in another context key's value.

### Example 1

```ts
vscode.executeCommand('setContext', 'supportedFolders', [ 'test', 'foo', 'bar' ]);

// or

vscode.executeCommand('setContext', 'supportedFileExtensions', { 'test': true, 'foo': 'anything', 'bar': false });
```
> NOTE: in the object case, the value doesn't matter, as it is just the existence of the key on the object

```json
"menus": {
	"explorer/context": [
		{
			"command": "ext.showOnlyOnCertainFolders",
                        "when": "explorerResourceIsFolder && resourceFilename in supportedFolders"
		}
	]
}
```

### Example 2

```ts
vscode.executeCommand('setContext', 'supportedFileExtensions', [ '.js', '.ts' ]);

// or

vscode.executeCommand('setContext', 'supportedFileExtensions', { '.js': true, '.ts': 'anything' });
```
> NOTE: in the object case, the value doesn't matter, as it is just the existence of the key on the object

```json
"menus": {
	"explorer/context": [
		{
			"command": "ext.showOnlyOnCertainFiles",
                        "when": "!explorerResourceIsFolder && resourceExtname in supportedFileExtensions"
		}
	]
}
```

**Comment by bpasero** [comment]
Pretty cool 👍
