### ISSUE TITLE
Activity bar: visibility of things is not synced

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#105793]
For example, I hide the accounts icon but this state is not synced. Maybe this was not marked for syncing? Should we maybe do a pass over new keys that were added that need to be marked as sync?

**Comment by sandy081** [comment]
Yes, This key is not registered to sync. 

@bpasero I think we need a better strategy. Idea:

- Introduce machine storage scope and consider those stored in global scope for sync?

**Comment by bpasero** [comment]
@sandy081 or alternatively we could flip it around and say that a key needs to be explicitly excluded if you don't want to sync it. I am not sure I would tie storage service and storage syncing together. Ideally the storage sync layer would observe what keys are used globally and then react to it.

**Comment by bpasero** [comment]
I pushed https://github.com/microsoft/vscode/commit/fee01671a9238d348835079262507a71e26fe563 as a fix.
