### ISSUE TITLE
Test: Smoke tests

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#105750]
- [x] Windows @joaomoreno 
- [x] macOS @lszomoru
- [x] Linux @rebornix
- [x] Web (Chromium, anyOS) @lszomoru 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23105750%0A%0A)

---

**NOTE:** Desktop & Web tests MUST run with `--build` argument

**NOTE:** Desktop tests MUST run with `--stable-build` argument additionally

Documentation: https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md#run.

If the automated tests fail, create and issue for that and run the tests manually: https://github.com/microsoft/vscode/wiki/Smoke-Test

**Comment by lszomoru** [comment]
Ran smoke tests on Mac using Stable (1.48.2 - a0479759d6), and Insiders (1.49.0-insider - b6d4fec371). 
Only failed test is being tracked with https://github.com/microsoft/vscode/issues/105330

**Comment by lszomoru** [comment]
Also ran Web smoke test on Windows using Insiders (1.49.0-insider - b6d4fec).
The two failures are already being tracked: https://github.com/microsoft/vscode/issues/105330 ,and https://github.com/microsoft/vscode/issues/103949

**Comment by joaomoreno** [comment]
@devinvalenciano I can take this.

**Comment by joaomoreno** [comment]
Nothing works in the Notebook test suite on Windows: https://github.com/microsoft/vscode/issues/105928
