### ISSUE TITLE
VS CODE v1.48.2 has some bug

### ISSUE THREAD

**Issue by devin91** [microsoft/vscode#105776]
- 

- VSCode Version: 1.48.2
- OS Version: ubuntu 20.04

Steps to Reproduce:

1.  when I start the vscode ,  the cpu used upto 100%
2. when I start the vscode , the mem has been increasing.
3. also, the vscode will breakdown after  using  a period of time

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by gjsjohnmurray** [comment]
Please review https://github.com/microsoft/vscode/wiki/Performance-Issues to gather detailed information.

**Comment by Tyriar** [comment]
Please re-create the issue following the above link to help make this more actionable.
