### ISSUE TITLE
Test task detail

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#105737]
Refs: https://github.com/microsoft/vscode/issues/69785

- [x] macOS @lszomoru
- [x] linux @jrieken
- [x] windows @sana-ajani

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23105737%0A%0A)

---

The built-in npm extension has used the API for months. Things to verify:
- Take a look a the use of this API in the npm extension. Verify that it makes sense.
- Verify that the doc comments make sense.
- Verify that when you run the Configure Task command and choose an npm task, that the detail gets copied into the tasks.json.
- Verify that when you run Run Task and choose the npm folder that the npm tasks have a detail.
- Verify that the setting `task.quickOpen.detail` controls whether the detail is shown.

**Comment by lszomoru** [comment]
👏🏻

**Comment by sana-ajani** [comment]
minor comment on the "task.quickOpen.detail" setting, should we edit it to be:

"Controls whether to show the task detail for task**s** that have a detail in the Run Task **and Configure Task** quick pick"
![image](https://user-images.githubusercontent.com/9721254/92016796-d9fa0900-ed20-11ea-9478-fa7f1cd5df4f.png)

**Comment by alexr00** [comment]
New string for setting: "Controls whether to show the task detail for tasks that have a detail in task quick picks, such as Run Task."
