### ISSUE TITLE
No way to show settings sync icon after hiding it?

### ISSUE THREAD

**Issue by driftingdream** [microsoft/vscode#105709]
- VSCode Version:
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Click settings sync icon
![image](https://user-images.githubusercontent.com/16973422/91695047-25d17480-eba0-11ea-9b30-3eb4687eefa6.png)

2. Click hide

**Comment by RMacfarlane** [comment]
If you right click on the activity bar, you see an option for "Show Accounts":
![Screen Shot 2020-08-31 at 9 14 01 AM](https://user-images.githubusercontent.com/3672607/91742005-67472d00-eb6a-11ea-8522-d618da109678.png)

Were you expecting a command in the command palette as well?

**Comment by driftingdream** [comment]
Thank you! It is not quite intuitive for me, given the button meaning "Settings Sync" to me.
