### ISSUE TITLE
JavaScript for loop template completion needs more context

### ISSUE THREAD

**Issue by jeffmcaffer** [Microsoft/vscode#1057]
The JavaScript editor does not well support the common pattern of a for loop with a loop variable called 'i'.

When writing a JavaScript for loop a common pattern is 
- type 'foo' and chose the for loop template
- the template comes up with the complete structure and suggests "index" as the name of the loop variable.  
- 'i' is a common loop variable name.  If the user types i to replace index, the code completion engine suggests the 'if' control structure. 
- of course, if you hit enter that inserts an if structure in the middle of the first line of the for loop 
- if you hit any other key to dismiss the 'if' suggestion, that punts you out of the template completion and you have to manually change all of the array names, etc.

The template completion needs more context to know that a variable name is being entered so a control structure is not a good suggestion.

**Comment by MattiasPernhult** [comment]
By pressing esc key it is possible to continue to use the for loop template, still it would be a nice feature.

So +1 for this.

**Comment by mjbvz** [comment]
I believe that most of the described behavior has been fixed.

Preventing the `if` snipped suggestion from being shown is being tracked by #1304

Please give this a try in VSCode 1.9 and let me know if you still see this issue or notice any new ones.

Thanks
