### ISSUE TITLE
Test notebook UX changes

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#105769]
Refs: https://github.com/microsoft/vscode/issues/104772

- [x] Linux @gregvanl
- [x] macOS @bpasero
- [x] windows @RMacfarlane

Complexity: 2

Authors: @roblourens @rebornix @jrieken @connor4312 @misolori 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23105769%0A%0A)

---

We added two settings for users to customize the notebook view:

- `notebook.cellToolbarLocation` to move the cell toolbar to the left, right, or hide it
- `notebook.showCellStatusbar` to hide or show the cell statusbar

Please test that these work as expected and don't break the view. They can be tested using a github-issues notebook, like the ones checked into the vscode repo.

Then please take a few minutes to play with a notebook and file issues or comment here if you see any problems or have any hot takes about notebook UX in general.

**Comment by bpasero** [comment]
Had to use macOS as my Linux at work is not healthy.

**Comment by gregvanl** [comment]
I can switch to Linux.

**Comment by bpasero** [comment]
@gregvanl thanks!
