### ISSUE TITLE
Implement debug target launching in integrated terminal

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#10574]
This is the frontend implementation for Microsoft/vscode-debugadapter-node#47.
The implementation for node-debug is this: https://github.com/Microsoft/vscode-node-debug/issues/85
The implementation would be based on #9957.

**Comment by weinand** [comment]
@isidorn I've added a first cut of this to the debug protocol and node-debug.
If you pass a `supportsRunInTerminalRequest` with value true to the InitializeRequest, node_debug will call the `runInTerminalRequest` on VS Code. See https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/node/v8Protocol.ts#L69

**Comment by Tyriar** [comment]
Keep in mind that the command sent would be sent to the currently configured shell (bash, zsh, powershell, cmd, etc.).

**Comment by DanTup** [comment]
@weinand  I'm not familiar with/haven't installed the Insiders builds yet - that change is in master, does that mean we can try it out in insiders from tomorrow? :)

(Also,  how releases are cut; presumably not from master if there's in-progress stuff like this that might not make the release? I searched but couldn't find any info on the relationship between branches/releases/etc.)

**Comment by weinand** [comment]
@DanTup you can try this as soon as this issue is closed. Currently the VS Code side of things is missing.

Releases are cut from Master. In-progress stuff will either be disabled or just not not mentioned in the release notes.

**Comment by isidorn** [comment]
Released a first version of this. Please note the following:
* I am not using the Terminal extension API since vscode debugger UI is not running as an extension, so I am accessing the TerminalService directly
* Currently ignoring: `env`, `cwd` and `processID`

**Comment by weinand** [comment]
@DanTup before you jump on this: please note the limitations mentioned above. I'll work on this via https://github.com/Microsoft/vscode/issues/10880

**Comment by isidorn** [comment]
Also `externalConsole` now might not be the best name since the intergrated terminal is not external.

**Comment by weinand** [comment]
@isidorn For node-debug I've introduced a new `console` attribute with these values:
"internalConsole", "integratedTerminal", "externalTerminal"

The `externalConsole` attribute has been deprecated in hover help. If it is still used, a value of true is identical to `"console": "externalTerminal"`.

**Comment by DanTup** [comment]
@weinand This sounds great; we'll give it a go! With https://github.com/Microsoft/vscode-node-debug/issues/85 closed does this mean there's a working example of for Node runnable in insiders from Monday?

**Comment by DanTup** [comment]
@weinand Had a quick go, and this seems to work great!

One question though - the `supportsRunInTerminal` flag - when would it ever be false? If it's only for <= Code 1.4 is there a way we can flag the extension to only run in >=1.5? (I'd rather ditch that code path if we don't need it, but I can't figure it out).

**Comment by weinand** [comment]
@DanTup great to hear that runInTerminal works.
The flag supportsRunInTerminal does not exist in VS Code <= 1.4, so prepare for this (and not that it is false).
You can set the vscode engine version in the package.json to 1.5:
```json
	"engines": {
		"vscode": "^1.5.0",
		"node": "^4.1.1"
	},
```

**Comment by DanTup** [comment]
@weinand I had updated `engines/vscode` to `1.5` but I wasn't sure if that would stop people being able to install in 1.4 - is that correct? If so, it's safe for me the to assume integrated terminal support always?

**Comment by weinand** [comment]
@DanTup yes, that should stop people installing your extension in 1.4. 
But I've never tried that myself, so I suggest that your try it to better understand what users of your extension will experience.
