### ISSUE TITLE
Filed to save “html file” :unable to write file ‘disk\folder\htmlfile’ (unknown(FileSystemError):Error:EBUSY:resource busy or locked, open ‘disk;\folder\htmlfile’)

### ISSUE THREAD

**Issue by saadmater** [microsoft/vscode#105756]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. I have html file on a disk saved in folder the problem is every time I try to add any thing this error appear to me
2.I Gave the full permission to editing this disk 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by saadmater** [comment]
It’s windows version

**Comment by saadmater** [comment]
It’s windows version

**Comment by saadmater** [comment]
It’s windows version

**Comment by saadmater** [comment]
It’s windows version

**Comment by saadmater** [comment]
Please help

**Comment by aeschli** [comment]
Maybe another program that also uses the file?
Restart windows and see if it works then...
