### ISSUE TITLE
Renaming folders to different case does not update opened editors

### ISSUE THREAD

**Issue by hedgehog90** [microsoft/vscode#105720]
- VSCode Version: Latest
Windows 10

With a NodeJS project I've noticed when I rename a folder outside of VS Code (ie, in windows explorer) with the same name but a different case - eg, Lib to lib - If I then try and search for a snippet of code, it will appear twice in the results under the folders Lib and lib.

Also if I set a breakpoint in an opened file under one of these directories, if it has it registered as existing under the old path, breakpoints do not work properly (it pauses but it won't allow inspection of variables by hovering)

**Comment by connor4312** [comment]
This doesn't sound like a debugger issue. If the debugger is given the wrong path, it's expected that breakpoints won't get bound.

**Comment by bpasero** [comment]
@hedgehog90 can you report the debug issue separately so that we keep this issue for the "Search" issue.

If I understand correctly, you see duplicate search results after renaming a folder. Do you see that also when you close all editors? Since we do search through opened editors as well as all the workspace, maybe you ended up seeing some results from opened editors in the search results.

**Comment by hedgehog90** [comment]
> @hedgehog90 can you report the debug issue separately so that we keep this issue for the "Search" issue.
> 
> If I understand correctly, you see duplicate search results after renaming a folder. Do you see that also when you close all editors? Since we do search through opened editors as well as all the workspace, maybe you ended up seeing some results from opened editors in the search results.

I think that's what was happening, I usually have like 50 tabs open and they get restored on each startup, and hidden amongst there were probably some tabs with the old path.

Even so it's a bit confusing.
I suggest the editor run a check specifically for Windows users to update the currently opened paths if the cases don't match the file system.

**Comment by bpasero** [comment]
We currently do not have a good story for detecting such renames.
