### ISSUE TITLE
JavaScript - while debugging Set object entries are not displayed properly in both WATCH panel and the on-hover snippet

### ISSUE THREAD

**Issue by RomanDavlyatshin** [microsoft/vscode#105739]
- VSCode Version: 1.48.2 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Add debug configuration for Node.js
2. Add a script that operates Set, e.g.
```
const a = new Set()
a.add(1);
a.add(2);
a.add(3);
a.add(4);
a.add(5);
a.add(6);
a.add(7);
console.log(a);
```
3. Set a breakpoint on the line with `console.log(a)` and launch debug
4. Inspect `a` value
5. See set with an incorrect number of elements displayed in curly braces
![image](https://user-images.githubusercontent.com/34244611/91734644-3c85c480-ebbc-11ea-9398-d9514dfe7006.png)

Suggestion: I suggest implementing the behavior similar to displaying arrays (add ellipsis if it's impossible to fit all entries). The current implementation is confusing, especially for a brief glance.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
I think in node-debug we are showing the first three values and then an ellipsis.
