### ISSUE TITLE
Test notebook cell status bar contributions

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#105768]
Refs: https://github.com/microsoft/vscode/issues/104958

- [x] macOS @sandy081
- [x] linux @chrmarti
- [x] windows @joaomoreno

Complexity: 4

Authors: @roblourens @rebornix @jrieken @connor4312 @misolori

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23105768%0A%0A)

---

We added API for extensions to contribute status bar items to individual cells. Please use this API from an extension and test that it works as expected.

- Here is an example extension: https://github.com/roblourens/cell-statusbar-example. You can clone this and tweak it.
- The API works basically the same as the normal statusbar API
- Extensions can show and hide status bar items but when the notebook is closed, they will be automatically cleaned up.

**Comment by joaomoreno** [comment]
>Here is an example extension: https://github.com/roblourens/cell-statusbar-example. You can clone this and tweak it.

👏 Thanks a lot!

**Comment by joaomoreno** [comment]
This API feels weird... shouldn't these simply be menu items contributed to a menu?

**Comment by joaomoreno** [comment]
Just found https://github.com/microsoft/vscode/issues/105809 👍
