### ISSUE TITLE
React - Debug session disappeas

### ISSUE THREAD

**Issue by davewurtz** [microsoft/vscode#105759]
We have wri
Issue Type: <b>Bug</b>

I have been running fine for several months using React with my own web site.  Since the last VSCode update, when I start a debug session with either Edge Chromium or Chrome, the opening page appears correctly.  After going through my custom login process (which 'logs into' a web api), the debug session simply disappears.  I have turned on 'Caught Exceptions' and 'Uncaught Exceptions', but it does not stop - the app simply disappears.  I have not changed anything in the login process and it does successfully log in so I don't believe that is the problem.

Running Edge/Chrome directly against my local web site works fine.  Any ideas on how to debug my debugger?

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3691)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (22.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|5.5.0
vscode-firefox-debug|fir|2.9.1
debugger-for-chrome|msj|4.12.10
debugger-for-edge|msj|1.0.15

</details>
tten the needed data into your clipboard because it was too large to send. Please paste.

**Comment by connor4312** [comment]
This sounds like https://github.com/microsoft/vscode-js-debug/issues/729

/duplicate
