### ISSUE TITLE
Test DebugAdapterNamedPipeServer

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#105763]
Refs: https://github.com/microsoft/vscode/issues/84643

- [x] macOS: @isidorn 
- [ ] windows: @connor4312 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23105763%0A%0A)

---

Beginning with this milestone VS Code supports communicating with debug adapters via "named pipes".
The [`DebugAdapterNamedPipeServer`](https://github.com/microsoft/vscode/blob/a288b1f1ea90cc227c0fc6170c494a93dad1248a/src/vs/vscode.d.ts#L10943-L10956) has been added as another [`DebugAdapterDescriptor`](https://github.com/microsoft/vscode/blob/a288b1f1ea90cc227c0fc6170c494a93dad1248a/src/vs/vscode.d.ts#L10989).

Mock Debug has already been prepared to support the `DebugAdapterNamedPipeServer`. Just make Mock-Debug use `vscode.dt.s` from Insiders and enable this [line](https://github.com/microsoft/vscode-mock-debug/blob/ca76f5aa640129ad9824da81f24b9ff74b7449a7/src/extension.ts#L232) and set the `runMode` to `namedPipeServer`. 

Alternatively use a `DebugAdapterNamedPipeServer` in any other debug extension.

Verify that a `DebugAdapterNamedPipeServer` works identical to the already existing `DebugAdapterServer`.

**Comment by isidorn** [comment]
I have verified this works fine with Mock debug on macOS.

**Comment by connor4312** [comment]
I adopted this in js-debug in https://github.com/microsoft/vscode-js-debug/commit/b206c9127d862ec6da47762f08c6b21f8bc678cb (will merge after endgame). Seems to work well.

Thanks @TylerLeonhardt :)
