### ISSUE TITLE
Test cell base text diff view for Notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#105770]
Refs: https://github.com/microsoft/vscode/issues/99877#issuecomment-679215838

- [x] anyOS @sana-ajani
- [x] anyOS @isidorn 

Complexity: 3

Authors: @rebornix @misolori @jrieken @roblourens @connor4312 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23105770%0A%0A)

---

We added a new cell based diff view editor for notebooks. It's not full featured side by side rich diff view. Instead it's more or less an enhanced text diff view, which presents your changes to the notebook cells, please test

* Install [GitHub Issue Notebook](https://github.com/microsoft/vscode-github-issue-notebooks), create a notebook file, add some cells
* `git add` the file
* Modifying the notebook, adding new cells, modifying cell content, running cells
* Open SCM view and open the diff view from the viewlet.

**Comment by isidorn** [comment]
I created some issues and assigned all of them to @rebornix 
Since I see there are quite some authors writing here so people can grab issues if they are reponsible for some area.

**Comment by rebornix** [comment]
Since @isidorn already helped out, the testing for this feature is done.
