### ISSUE TITLE
Completion provider show completions at the end of the list

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#105719]
@mjbvz Is it possible to show completions at the end of the list?

I'm using this one:

`completionItem.sortText = "\uffff9999" + i;`

But still completions are not at the end of the list. I know they are sorted additionally by the text you typed, etc. but maybe there's a way to make them at the end of the list always?

**Comment by jrieken** [comment]
No, that's not possible as suggestions get also sorted by the match score of the selected prefix and there is no reason why we should hide a good matching suggestion

**Comment by jrieken** [comment]
The only possible workaround is to have no prefix selected and to re-compute suggestions with each keystroke (which can be accomplished via incomplete suggestion). But on a metalevel: why would you hide your suggestions at all?
