### ISSUE TITLE
Word Wrap doesn't work in compare view

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#10572]
- VSCode Version:
  ![image](https://cloud.githubusercontent.com/assets/8189808/17689920/5ec6ba8a-638b-11e6-866e-1c1a76dace57.png)
- OS Version: Win 10 x64

Steps to Reproduce:
1. Compare two files with long lines
2. No word wrap

I'm unable to enable word wrap when in compare view.

**Comment by fungilation** [comment]
Note that since VSCode v1.10, wordwrap is now "forced" on in the compare view, with rendering bug: #21703

**Comment by alexandrudima** [comment]
Let's track in #11387 (it has 24 upvotes there)
