### ISSUE TITLE
Comparing two big files throw: "Cannot compare files because one file is too large."

### ISSUE THREAD

**Issue by gsusI** [microsoft/vscode#105797]
- VSCode Version: 1.48.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Install gitlens
2. Open repo with big file (53MB)
3. Make changes to this file
4. Try to see side by side the changes made in the file
5 The error "Cannot compare files because one file is too large." is presented. Differences are not highlighted

Does this issue occur when all extensions are disabled?: Probably not, as I use GitLens to compare the files

**Comment by gjsjohnmurray** [comment]
As the message says, there's a limit:

https://github.com/microsoft/vscode/blob/11479ca7596c8f3404316e2c353324e8e545bf37/src/vs/editor/common/model/textModel.ts#L191

**Comment by gsusI** [comment]
Thanks for the explanation @gjsjohnmurray. 

However, Is not unusual for developers to have laptops with 16GB/32GB/(even) 64GB memory and fast SSD storage.

Having a decent number of developers using this high performing devices should be a reason good enough to consider making this limit editable through settings.

> Similarly to how `editor.stopRenderingLineAfter` accepts a parameter `-1` for those who use devices with enough resources to deal with extremely long lines.
