### ISSUE TITLE
box select

### ISSUE THREAD

**Issue by ksdavidc** [microsoft/vscode#105761]
Issue Type: <b>Performance Issue</b>
I seem to be unable to turn off box/column select. In other words, if I try to select across multiple lines, I only get a box select, as opposed to the usual behavior where entire lines are selected as I add lines.  

I am using version 1.48.2 on a mac.

I must have pressed option+shift or some other such code inadvertently and now I can only select boxes. I have looked at my keyboard shortcuts but I don't know what to look for...

Unfortunately searching for solutions via google or SE only produces results for how to turn it on, not off! I don't know what the opposite mode is. "line select" seems to be just to select the current line, not for entire lines across multiline selections.

![Screen Shot 2020-09-01 at 4 18 27 AM](https://user-images.githubusercontent.com/62230004/91758041-4f26ea80-ec0a-11ea-95b0-36d3075abbb9.png)
![Sep-01-2020 04-20-45](https://user-images.githubusercontent.com/62230004/91758247-a5942900-ec0a-11ea-9efb-94ecac1fc7f9.gif)

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	    98	 87078	code main
    3	    49	 87079	   gpu-process
    0	    33	 87081	   utility
   11	   344	 87082	   window (Mon202000828Plan.md — kyotolesson-class (Workspace))
    0	     0	 87118	     /bin/bash -l
    6	   426	 87149	     extensionHost
    0	    33	 87158	       electron_node server.js 
    0	    33	 87159	       electron_node server.js 
    0	    49	 87177	       CodeStream
    0	    82	 87185	       electron_node server.js 
    0	    49	 87193	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=87149
    0	    33	 87153	     watcherService
    0	    33	 87161	     searchService
    6	    98	 87117	   shared-process
    0	     0	 88569	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    6	    82	 88564	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Mon202000828Plan.md — kyotolesson-class (Workspace))
|    Folder (kyotolesson-class.github.io): 1467 files
|      File types: png(275) html(210) PNG(188) jpg(122) css(95) md(83) sjr(62)
|                  js(33) gif(31) DS_Store(14)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (138)</summary>

Extension|Author (truncated)|Version
---|---|---
get-style-from-html|a45|1.0.1
better-comments|aar|2.1.0
Bookmarks|ale|11.3.1
project-manager|ale|11.2.0
markdown-imsize|amo|0.0.2
vscode-subtitles|ast|0.3.3
All-Autocomplete|Ati|0.0.23
atlascode|atl|2.7.0
vscode-browser-preview|auc|0.6.7
emojisense|bie|0.7.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-footnotes|bie|0.0.7
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
latexize|cbu|0.0.5
vscode-opennewinstance|chr|0.0.7
codestream|Cod|8.3.4
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
macros|ctf|0.0.4
vscode-terminal-themes|ctf|0.1.0
git-diff-and-merge-tool|dav|1.0.4
jekyll-run|Ded|1.4.3
githistory|don|0.6.9
jquerysnippets|don|0.0.1
brackethighlighter|Dur|2.0.0
git-cheatsheet|dzh|1.1.1
gitlens|eam|10.2.2
remotehub|eam|0.5.0
vscode-html-css|ecm|0.2.3
vscode-author-generator|edw|0.2.1
auto-import|Ele|0.3.12
prettier-vscode|esb|5.5.0
rightclick-git|Eve|1.0.0
vscode-open-in-github|fab|1.2.3
vscode-optimize-images|fab|1.1.0
eventlistener-intellisense|fat|0.0.1
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.0
dupe-file|gie|1.0.6
ginfuru-vscode-jekyll-syntax|gin|0.1.1
vscode-jekyll-snippets|gin|0.9.3
vscode-pull-request-github|Git|0.19.0
todo-tree|Gru|0.0.178
vscode-commandbar|gsp|0.3.1
markdown-preview-bitbucket|hbr|1.0.0
vscode-settings-cycler|hoo|1.0.1
html-tag-wrapper|hwe|0.2.3
output-colorizer|IBM|0.1.2
vscode-dimmer-block|ima|2.2.0
easy-snippet|inu|0.6.2
customize-ui|ioc|0.1.47
monkey-patch|ioc|0.1.10
vscode-essentials|jab|1.5.0
search-editor-apply-changes|jak|0.1.1
vscode-placeholder-images|Jak|0.1.0
latex-workshop|Jam|8.11.1
hungry-delete|jas|1.6.0
latex-snippets-jeff|Jef|1.2.3
shortcut-menu-bar|jer|1.3.0
vscode-text-pastry|jkj|1.2.0
html-better|joe|1.0.0
vscode-insertdatestring|jsy|2.3.0
pdf|k5h|4.2.1
chat|kar|0.35.0
wordcounter|kir|2.3.0
vscode-gutter-preview|kis|0.26.2
vscode-format-context-menu|lac|1.0.4
aw-watcher-vscode|lin|0.4.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vsls-whiteboard|los|0.0.11
vscode-now|luc|0.1.0
image-resizer|luk|0.1.0
git-emoji|mai|1.0.6
web-browser|mas|0.0.1
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|1.7.1
MetaJump|met|1.1.1
MetaWord|met|1.2.1
git-graph|mhu|1.25.0
gitignore|mic|1.0.1
vscode-checkpoints|mic|1.3.1
dotenv|mik|1.0.1
HTMLHint|mka|0.8.0
vscode-html-format|moh|0.0.4
vsliveshare|ms-|1.0.2731
vsliveshare-audio|ms-|0.1.85
debugger-for-chrome|msj|4.12.10
vscode-paste-image|mus|1.0.4
preview-vscode|myh|1.3.0
color-highlight|nau|2.3.0
gremlins|nho|0.23.0
latex-formatter|nic|1.0.5
indent-rainbow|ode|7.4.0
nowignore|par|0.0.1
subtitles-editor|pep|1.0.4
polacode|pnp|0.3.4
git-file-history|pom|1.0.1
vscode-css-peek|pra|4.0.0
subtle-brackets|raf|3.0.0
vscode-yaml|red|0.10.1
explorer-exclude-vscode-extension|Red|1.2.0
rescuetime|Res|1.0.1
LiveServer|rit|5.6.1
workspacetheme|sag|1.0.1
vscode-open|san|0.1.0
git-merger|sha|0.4.1
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.13
git-autoconfig|shy|0.0.1
html5-boilerplate|sid|1.0.3
git-identity|ste|1.0.1
rewrap|stk|1.13.0
code-spell-checker|str|1.9.0
unique-window-colors|stu|1.0.51
control-snippets|svi|1.9.1
open-in-browser|tec|2.0.0
latex-utilities|tec|0.3.7
vscode-markdown-paste-image|tel|0.12.3
vscode-markdown-link-suggestions|Tom|13.0.0
pdf|tom|1.1.0
vscode-workspace-explorer|tom|1.5.0
git-rebase-shortcuts|tre|1.0.5
vscodeintellicode|Vis|1.2.10
vscode-image-changes|Vla|0.0.3
vscode-icons|vsc|10.2.0
codetour|vsl|0.0.35
gistfs|vsl|0.1.8
gitdoc|vsl|0.0.6
spaces|vsl|0.1.2
github-issues|yop|1.3.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.3.0
html-css-class-completion|Zig|1.19.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by ksdavidc** [comment]
Just found the answer myself looking for something else. The "Editor: Column Selection" setting  controls this. The default is off, but I must have turned it on somehow without realizing it. I have proposed an amendment to the help page. https://github.com/microsoft/vscode-docs/compare/master...ksdavidc:patch-1

**Comment by weinand** [comment]
@ksdavidc glad to hear that you could help yourself.
And thanks for the doc PR.
