### ISSUE TITLE
Add disable auto sort of provideCompletionItems result

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/vscode#105798]
![image](https://user-images.githubusercontent.com/15936231/91827753-d8253c80-ec71-11ea-801d-039da25c610b.png)
![image](https://user-images.githubusercontent.com/15936231/91827781-e410fe80-ec71-11ea-9969-cc8474279987.png)

why resort my result, I want disable it

EDIT: [this api](https://code.visualstudio.com/api/references/vscode-api#CompletionItemProvider.provideCompletionItems) when I return sorted CompletionItem[], vscode somehow resorted it, that's not what I want

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
