### ISSUE TITLE
Params error should limit to specific call in call chain

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#10573]
- VSCode Version: 1.4.0
- OS Version: OSX El Capitan
![image](https://cloud.githubusercontent.com/assets/3254987/17690119/644e0b88-6341-11e6-965a-a4900a2723ab.png)

In the example above, only the last call (`.option()`) has invalid parameter.
It would be better if the error only limit to that function call.

**Comment by alexandrudima** [comment]
@unional What language are you using? Can you also provide a reproducible case in textual form (good for copy-paste)

**Comment by unional** [comment]
Sure. It's TypeScript
```ts

let x = []
  .concat()
  .entries(1)
```

**Comment by alexandrudima** [comment]
@unional In this case, I believe the error is showing at the right spot:

![image](https://cloud.githubusercontent.com/assets/5047891/17691324/2d5eed4c-6394-11e6-8ead-45fb34d022ed.png)

**Comment by unional** [comment]
That's strange:

![image](https://cloud.githubusercontent.com/assets/3254987/17691406/13416e08-6349-11e6-9b7c-01c2dd251335.png)

**Comment by unional** [comment]
Ok. Know why. I'm using TypeScript@2.0.0

**Comment by alexandrudima** [comment]
Oh, cool

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10372
