### ISSUE TITLE
Test: chrome attachment in remote scenario

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#105772]
Refs: https://github.com/microsoft/vscode-js-debug/issues/456

- [x] macOS @btholt
- [x] linux @mjbvz
- [x] windows @fiveisprime

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23105772%0A%0A)

---

Previously in remotes, we only attached via stdio pipes. There was work this iteration to add parity to allow attaching to browsers running the UI, as well as launching browsers with debug ports rather than pipes. You can test both of these things at once!

From a remote environment (container, ssh, or wsl), have a folder with `.vscode/launch.json`

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-chrome",
      "request": "launch",
      "name": "launch",
      "url": "https://github.com",
    },
    {
      "type": "pwa-chrome",
      "request": "attach",
      "name": "attach",
      "address": "127.0.0.1",
      "port": 9229,
    }
  ]
}

```

1. Run "launch". Verify that a browser opens to github.com. Check that it works, enter `document` in the Debug Console and see that it exists.
1. Run "attach". This should _not_ work and eventually time out (or you can cancel it)
1. Add `"port": 9229` to "launch". Stop the running debug session, and then run it again.
1. Now run "attach". It should successfully attach.

**Comment by fiveisprime** [comment]
Looks good

Tested on Windows with Remote-WSL and with some of my personal JAMstack apps. It's nice to see this working!

**Comment by btholt** [comment]
Tested on a create-react-app with a Node.js dev container.

This is siiiiiick. People are going to love it.
