### ISSUE TITLE
Incorrect table format in Markdown preview

### ISSUE THREAD

**Issue by wongyah** [microsoft/vscode#105796]
Issue Type: <b>Bug</b>

I added a CSS file in the setting item "Markdown: Style".

The CSS code for element "table" and "thead" take effects. But the code for table elements "th" "td" "tr" "tbody" don't work at correctly.

For example, my CSS code is:

![image](https://github.com/wongyah/Img/blob/master/TableFormatCSS.jpg)

The table looks like:

![image](https://github.com/wongyah/Img/blob/master/TableAppearance.jpg)

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.86GB (1.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
excel-to-markdown-table|csh|1.2.2
vscode-language-pack-zh-hans|MS-|1.48.3
material-icon-theme|PKi|4.2.0
vscode-icons|vsc|10.2.0

</details>

**Comment by weinand** [comment]
Your images are not showing. Please don't put private links into comments. Just drag-and-drop the image into the comment.

**Comment by wongyah** [comment]
My CSS code:

![TableFormatCSS](https://user-images.githubusercontent.com/38174537/91830215-153efe00-ec75-11ea-936d-fd3831cfea9c.jpg)

The table looks like this:

![TableAppearance](https://user-images.githubusercontent.com/38174537/91830288-2be55500-ec75-11ea-9038-661d56921d33.jpg)

**Comment by mjbvz** [comment]
Please share the css and markdown source as text

**Comment by wongyah** [comment]
Initially I found the strange table display in my articles written by Markdown when I copied my CSS code for the extension " Markdown Preview Enhanced" to the CSS file for VS Code default preview. Then I did some tests to see what is wrong with it, using very simple table.

# Markdown Text of Sample Table

```
| text | text | text | text |
|:----:|:-----|:-----|:-----|
| text | text | text | text |
| text | text | text | text |
| text | text | text | text |
```

# Test Cases

## Base Case

The decoration for \<table\> and \<thead\> looks good.

### CSS

```
table {
    margin: 0 auto;
    border-top: 2pt solid;
    border-bottom: 2pt solid;
    font-size: 9pt;
  }
  
 thead {
    border-bottom: 2pt solid;
  }
```
### Preview

![Base](https://user-images.githubusercontent.com/38174537/91924305-e96b5900-ed04-11ea-9be5-b9b14bcb9b07.jpg)

## Case 1

**Change:** Add border to \<td\>.

**Result:** The decoration for \<td\> takes effect on the first row (\<tr\>) of \<tbody\>, but the \<td\>s in the other \<tr\> elements of \<tbody\> and the \<td\> elements in \<thead\> were not influenced.

### CSS:
```
table {
    margin: 0 auto;
    border-top: 2pt solid;
    border-bottom: 2pt solid;
    font-size: 9pt;
  }
  
 thead {
    border-bottom: 2pt solid;
  }
  
 td {
    border: 1pt solid;
  }
```
### Preview

![td](https://user-images.githubusercontent.com/38174537/91922943-c25f5800-ed01-11ea-9c5d-75c749db1199.jpg)

## Case 2

**Change:** Add border to all descentdants of \<tbody\>.

**Result:** The decoration takes effect on the first row (\<tr\>) of \<tbody\>, but the \<td\>s in the other \<tr\> elements of \<tbody\> were not influenced.


### CSS

```
table {
    margin: 0 auto;
    border-top: 2pt solid;
    border-bottom: 2pt solid;
    font-size: 9pt;
  }
  
 thead {
    border-bottom: 2pt solid;
  }
  
 tbody * {
    border: 1pt solid;
  }
```

### Preview

![tbody](https://user-images.githubusercontent.com/38174537/91924269-d789b600-ed04-11ea-8641-588916deccda.jpg)

## Case 3

**Change:** Add border to \<tr\>.

**Result:** The decoration takes effect on the left border and right border of \<tr\>, but the top border and the bottom border were not decorated.

### CSS

```
table {
    margin: 0 auto;
    border-top: 2pt solid;
    border-bottom: 2pt solid;
    font-size: 9pt;
  }
  
 thead {
    border-bottom: 2pt solid;
  }
  
 tr {
    border: 1pt solid;
  }
```

### Preview

![tr](https://user-images.githubusercontent.com/38174537/91924335-f7b97500-ed04-11ea-9d04-528595bb5c4d.jpg)

## Case 4

**Change:** Add border to the bottom of \<tr\>.

**Result:** The decoration don't work.

### CSS

```
table {
    margin: 0 auto;
    border-top: 2pt solid;
    border-bottom: 2pt solid;
    font-size: 9pt;
  }
  
 thead {
    border-bottom: 2pt solid;
  }
  
 tr {
    border-bottom: 1pt solid;
  }
```

### Preview

![tr_bottom](https://user-images.githubusercontent.com/38174537/91924477-626ab080-ed05-11ea-9581-88fe0bf172e9.jpg)

I then test the left-border and right-border decoration for \<tr\>, they did add the according border the table. So the conclusion in Case 3 is ture.

**Comment by mjbvz** [comment]
Here's the html of that markdown table:

<img width="515" alt="Screen Shot 2020-11-02 at 1 38 18 PM" src="https://user-images.githubusercontent.com/12821956/97922046-b3505280-1d10-11eb-9f50-882f1c05c425.png">

I believe the behavior of the CSS is correct based on this html and when you consider the default markdown styling that VS Code contributes. With the markdown preview open, you can use the `Developer: Open webview developer tools` command to inspect the html and css. 

However I will adjust some of these css rules to make overriding these styles easier

**Comment by mjbvz** [comment]
For verification, to override the typing on an element such as `td`, you should now be able to write a rule like:

```css
.vscode-body td {
    border: 1pt solid white;
}
```

Alternatively, you can use a theme specific selector:

```css
.vscode-dark td {
    border: 1pt solid white;
}
```

**Comment by wongyah** [comment]
Ok, I see.

Thank you very much!
