### ISSUE TITLE
search is not working in the latest update

### ISSUE THREAD

**Issue by praneetc** [microsoft/vscode#105762]
- VSCode Version: 1.48.2
- OS Version: Windows 10

Steps to Reproduce:

1. The search is not working in the latest update. It is able to search in open file but not able to search in other files.
2. When I search for a any fields it always shows loading.

Does this issue occur when all extensions are disabled?: Yes/No - Yes

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/wiki/Search-Issues for some advice.
