### ISSUE TITLE
Terminal scroll to bottom does not work

### ISSUE THREAD

**Issue by mbarzeev** [Microsoft/vscode#10575]
- VSCode Version: Version 1.5.0-insider (1.5.0-insider)
- OS Version: OSX - Yosemite

Steps to Reproduce:

1. Open the terminal
2. Perform some Git command
3. When command completes the terminal is not scrolled to the last line.

type something afterwards make the terminal scroll to the bottom.

**Comment by Treri** [comment]
Are you using oh-my-zsh?
This may help you
https://github.com/Microsoft/vscode/issues/8219#issuecomment-239602780

**Comment by mbarzeev** [comment]
Thanks, that seemed to fix it :)

**Comment by Tyriar** [comment]
Closing as duplicate, thanks @Treri
