### ISSUE TITLE
Backspace key is disabled when extensions are loading

### ISSUE THREAD

**Issue by arkrumbe** [microsoft/vscode#105862]
Issue Type: <b>Bug</b>

Extension details are attached. When I first open Code, and am typing in a document, the backspace key is unresponsive. All other keys register keypresses but backspace doesn't. Following extension load, ALL previous presses of backspace register instantaneously.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.20201

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (12.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.6
vscode-select-same-text|eha|1.0.1
devinsights|Mic|2020.8.3-1
tdpcode|Mic|1.4.1
vscode-nmake-tools|Mic|3.0.200717006
csharp|ms-|1.23.1
python|ms-|2020.8.105369
cpptools|ms-|0.30.0-insiders3
powershell|ms-|2020.6.0
word-counter|plu|0.0.1
vscode-xml|red|0.13.0
rust|rus|0.7.8
markdown-preview-enhanced|shd|0.5.13
ayu|tea|0.20.1
markdown-all-in-one|yzh|3.3.0

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
Does this reproduce when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)
