### ISSUE TITLE
Typing "/" (in XML-Tag) always inserts ">" automatically, even if I deactivate "Auto Closing Bracket" completely

### ISSUE THREAD

**Issue by DrPepperBianco** [microsoft/vscode#105871]
Issue Type: <b>Bug</b>

When I type XML I often write "/>" at the end of stand-alone tags in XML. VS Code now thinks it is clever, and automatically inserts ">" after I type "/" (inside an xml tag). Problem is, I type "/>" so often, that I automatically write both characters everytime. In VS Code I always end up with something like this "<br/>>" instead of "<br/>".

This is annoying and often leads to errors. I tried deactivating this feature, but whatever I setup, it still works. (I basically deactivated everything with auto in its name).

I assume "Auto Closing Brackets" is the setting, that should be applied. But it also doesn't work.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.18363

**Comment by aeschli** [comment]
VScode has no such feature in the built-in XML extension 
Maybe it's another extension?
