### ISSUE TITLE
if .vscode folder doesn't exist, the tasks.json won't be created when running "Run and Debug"

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode#105865]
- VSCode Version: 1.49.0-insider
- OS Version: Win64

Steps to Reproduce:

1. Delete .vscode folder from the project folder
2. go to "Run and Debug" 
![image](https://user-images.githubusercontent.com/16143955/91890324-23c0f180-ec44-11ea-8f94-453605997785.png)
3.  Continue to select an environment and select a configuration
4. The launch.json file will be created, 
5. But the tasks.json that needs to include the preLaunchTask won't be created.
--------------------------------------------------------------------------------------------
6. Now delete all files from .vscode folder, but keep the folder
7. Follow steps 2 and 3
8. Both launch.json and tasks.json will be created.

**Comment by isidorn** [comment]
Yes, we do not automatically create a tasks.json file. I guess this is a fair feature request.
@alexr00 is there API to create tasks.json so that the C++ extnesion could do it. Or is there internal api for this?

**Comment by alexr00** [comment]
From extension API, the only way to modify tasks.json is with the configuration API:
https://github.com/microsoft/vscode/blob/42226a9169340756897e12b65045c721af9f860b/src/vs/vscode.d.ts#L4826-L4826

For internal API, if you know the task you want to write then you can use `customize`
https://github.com/microsoft/vscode/blob/76b7d047188f05062c29170376511831098952f7/src/vs/workbench/contrib/tasks/common/taskService.ts#L92-L92

However, a tasks.json isn't required for the prelaunch task. If the prelaunch task already exists as an extension contributed task, then the tasks.json would only be needed if the user wanted to modify that task.

**Comment by isidorn** [comment]
So this sounds like this should be handled by the C++ extension...

**Comment by alexr00** [comment]
I agree that this should be handled by the C++ extension. The provider of the launch configuration is the only one who knows whether the task needs additional configuration to make a good prelaunch task.
