### ISSUE TITLE
All User settings deleted after reloading window 

### ISSUE THREAD

**Issue by AhmadBilal3000** [microsoft/vscode#105829]
Issue Type: <b>Bug</b>

After reloading vscode window, all the user settings got deleted automatically. The issue could not be reproduced and it is still unknown what exactly caused this issue.    

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.63GB (9.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
code-gnu-global|aus|0.2.2
spellright|ban|3.0.52
vscode-coloured-status-bar-problems|bra|0.1.2
file-properties-viewer|bru|0.5.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|0.7.2
vscode-markdownlint|Dav|0.36.3
gtest-adapter|Dav|1.8.3
gitlens|eam|10.2.2
LogFileHighlighter|emi|2.9.0
change-case|Fin|0.0.1
x8664assembly|fre|0.1.0
gc-excelviewer|Gra|3.0.40
todo-tree|Gru|0.0.178
better-cpp-syntax|jef|1.14.32
hex-fmt|ker|1.0.0
rainbow-csv|mec|1.7.1
python|ms-|2020.8.105369
cpptools|ms-|0.29.0
autodocstring|njp|0.5.3
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.10.1
jinjahtml|sam|0.15.0
markdown-preview-enhanced|shd|0.5.13
indenticator|Sir|0.6.0
code-spell-checker|str|1.9.0
code-spell-checker-german|str|0.1.6
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.10
jinja2-snippet-kit|Wya|2.0.0
linkerscript|Zix|1.0.1

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Sorry that this happened. Are you using Settings Sync?

**Comment by AhmadBilal3000** [comment]
At the time this happened, I was not using Setting Sync. (But now I have enabled it, to be on the safe side in case this happens again, plus I am keeping a local copy of user settings as well, as it took me almost 3 hours to reconfigure all the VSCode and plugin settings.)

Furthermore, when I reloaded the windows and before all the settings were auto reset, VS Code popped a notification that the  Microsoft Python Language Server had some issue and is switching back to default language server. But this notification appeared for a very short duration of time, so I just had a glimpse of it for few seconds before the user settings were automatically reset.

In case you need more information, please feel free to ask.

**Comment by sandy081** [comment]
Thanks for providing info. Enabling settings sync will definitely be handy in these cases. But I do not understand how are your extensions are wiped out. I am suspecting a race condition while writing into settings would have caused it. Is it possible to repro it?

**Comment by AhmadBilal3000** [comment]
> But I do not understand how are your extensions are wiped out.

Not extensions only their settings which are normally saved in **User** ``settings.json`` 

> Is it possible to repro it?

I am unable to reproduce this issue. It just happened when I updated some settings in the ``settings.json`` and reloaded the window (**Developer: Reload Window** from the command pallet)

**Comment by sandy081** [comment]
Sorry that this happened, but with out steps to repro the issue it is hard to understand what would have caused this. Not sure what action can be taken here/

**Comment by disco0** [comment]
Possibly had the same issue just now—had a few instances of Insiders open in the background, focused back to them about 30 minutes later and my user settings file was overwritten with two settings (with the original version not in undo history in any of the windows). Unfortunately I can't remember if I triggered a reload window before switching out.

Only thing of note I noticed—I toggled macOS's high contrast and reduced transparency accessability options in system settings, and this was the first/earliest state written into my user settings:

``` json
{
  "workbench.colorTheme": "Default High Contrast",
  "editor.matchBrackets": "never"
}
```

**Comment by AhmadBilal3000** [comment]
>but with out steps to repro the issue it is hard to understand what would have caused this.

I am unable to reproduce this issue myself. This is weird but it happened, and I am sorry that I am unable to provide any further information regarding the issue or its reproducibility.

**Comment by sandy081** [comment]
Looking at the scenarios from both users, I suspect this is causing when a setting is written into the file programatically by multiple windows at the same time and causing a race condition. I remember there is an issue that is similar to that. Marking this as duplicate - https://github.com/microsoft/vscode/issues/47763
