### ISSUE TITLE
Debug: Rename JavaScript Auto Attach Filter setting `explicit` value

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#105840]
Testing #105771

![image](https://user-images.githubusercontent.com/22350/91857213-e706f180-ec67-11ea-8390-ffbf5012a344.png)

The `explicit` setting value at first seems to contradict this setting's description. But after some thought, I believe it's just a bad setting value name. Shouldn't it simply be called `none`, for _no filter_?

**Comment by connor4312** [comment]
`no filter` to me implies `always`. Kind of a double-negative.

Maybe just call it `onlyWithFlag`?
