### ISSUE TITLE
closing a Tab: Animation happens but tab is not closing

### ISSUE THREAD

**Issue by pradhul-dev** [Microsoft/vscode#10585]
- VSCode Version:1.4.0
- OS Version:Ubuntu 14.04

I don't really know that this is a valid bug or not . But this issue really annoy me a lot. When I close a tab from VSCode the animation happens ( the close icon goes up slightly and comes back) but the window won't close.

Steps to reproduce : 
When I click right over the close Icon everything is fine the animation happens and the window closes. but if I clicked slightly down the X mark the animation still happens made me think it will close but it never does. Does the animation means something else?

**Comment by alexandrudima** [comment]
I think this might be the 'x' going up from under the cursor. @jrieken did you already fixed this?

**Comment by bpasero** [comment]
Yup.
