### ISSUE TITLE
WVV is not disposed when collapsed

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#105873]
Testing #105764

From the sample, I simply added a onDispose listener which does not fire when the webview is collapsed even when `retainContextWhenHidden` is not set to true

**Comment by mjbvz** [comment]
This is the current design. The lifecycle of webview views is:

- expand/collapse maps to a visibility change.
- Switching visible views also maps to a visibility change.
- Show/hide via the context menu maps to dispose.

`retainContextWhenHidden` does not change when any of these events are fired, it instead controls when the underlying webview element is destroyed.

**Comment by mjbvz** [comment]
fbf81bdd1bbdc2ca90856ddfd641c59e52e641be also expands the docs on the lifecycle
