### ISSUE TITLE
Allow modification of the "file path detection" in the terminal

### ISSUE THREAD

**Issue by tp** [microsoft/vscode#105835]
When running a Dart/Flutter project in VS Code's integrated terminal, one often sees stack traces using Dart's import syntax

```
[...]
#4      UserArea.build.<anonymous closure> (package:aym/pages/user_area/user_area_widget.dart:58:51)
[...]
```

VS Code identifies `package:aym/pages/user_area/user_area_widget.dart:58:51` as a path, but when CMD clicking it, the modal says "No matching results".

In this case I have to go to the left and remote the `package:` (which is Dart's default package-level import prefix), as well as the `aym/` (which is the prefix for the current project I am in).

Do you think it'd be valuable for VS Code to support modifying this behavior, or should this be better taken up with the stack-trace-printing project to use (full/relative) file paths?

**Comment by Tyriar** [comment]
The terminal link provider API is stable in the upcoming version, so Dart can implement their own link detection logic to do exactly this 🎉

**Comment by Tyriar** [comment]
👉 https://github.com/Dart-Code/Dart-Code/issues/2581
