### ISSUE TITLE
Notebook status bar setting should be two words and match other setting capitalization

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#105877]
Testing #105769

The convention for settings names is to use "Status Bar" and "status bar" in the description.

![image](https://user-images.githubusercontent.com/12818376/91896866-5a036e80-ec4e-11ea-858d-71a9bf9a3768.png)

If the user searches on "status bar", with a space, the Notebook setting isn't displayed.

**Comment by gregvanl** [comment]
Looking at the fix commit, the desciption still says "statusbar", without a space.

**Comment by roblourens** [comment]
Fixed
