### ISSUE TITLE
Adopt service library for all IPC communication main <=> renderer

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10587]
**Requests: Renderer → Main**

- [x] `vscode:openFilePicker`
- [x] `vscode:openFolderPicker`
- [x] `vscode:openFileFolderPicker`
- [x] `vscode:reloadWindow`
- [x] `vscode:toggleDevTools`
- [x] `vscode:windowOpen`, to open windows
- [x] `vscode:closeFolder`
- [x] `vscode:openNewWindow`
- [x] `vscode:toggleFullScreen`
- [x] `vscode:setFullScreen`
- [x] `vscode:openDevTools`
- [x] `vscode:setRepresentedFilename`
- [x] `vscode:setMenuBarVisibility`
- [x] `vscode:flashFrame`
- [x] `vscode:openRecent` → `getRecentlyOpened`
- [x] `vscode:focusWindow`
- [x] `vscode:showWindow`
- [x] `vscode:switchWindow`, has a result
- [x] `vscode:setDocumentEdited`
- [x] `vscode:toggleMenuBar`
- [x] `vscode:setHeaders`, we could remove this now that the gallery service doesn't depend on the telemetry service for the extra headers
- [x] `vscode:log`
- [x] `vscode:closeExtensionHostWindow`
- [x] `vscode:showItemInFolder`
- [x] `vscode:openExternal`
- [x] `vscode:startCrashReporter`

**Requests: Main → Renderer**

- [ ] `vscode:resolveKeybindings`, `vscode:keybindingsResolved`, done at startup to any one renderer
- [ ] `vscode:beforeUnload`, `vscode:ok`, `vscode:cancel`, done at shutdown to all renderers
- [ ] `vscode:runAction`
- [ ] `vscode:telemetry`
- [ ] `vscode:reportError`
- [ ] `vscode:openFiles`
- [ ] `vscode:showInfoMessage`
- [ ] `vscode.toggleAutoSave`
- [ ] `vscode:enterFullScreen`
- [ ] `vscode:leaveFullScreen`

**Events: Renderer → Main**

- [ ] `vscode:exit`
- [ ] `vscode:workbenchLoaded`

**Others**

- [ ] `broadcast`, renderer → main, main → renderer. Used to broadcast messages among all renderers. We should look into each of the use cases and fix them semantically:
  - [ ] `ICON_THEME_CHANNEL`
  - [ ] `COLOR_THEME_CHANNEL`
  - [ ] `EXTENSION_ATTACH_BROADCAST_CHANNEL`
  - [ ] `EXTENSION_LOG_BROADCAST_CHANNEL`
  - [ ] `EXTENSION_TERMINATE_BROADCAST_CHANNEL`
- [x] `vscode:update*`, renderer ↔ main
- [x] `_workbench.ipc` command
  - [x] `vscode:openFolderPicker`
  - [x] `vscode:windowOpen`

**Comment by joaomoreno** [comment]
Discovered some more requests going from main to renderers... added them to the list.

Cleaned up the `update` messages into a proper `IUpdateService` (719a8252955eedc3c053f2697932e2e54c260844)... which could only be fixed by introducing a telemetry service in main... which also fixed the `vscode:telemetry` messages (072c0aef5fdd75290980881966d20a33c87a4fc0).

The amount of debt in this world is crazy.

![foo](https://m.popkey.co/bf074d/7NOG.gif)

See ya next month!

**Comment by joaomoreno** [comment]
See ya never. Closing this.
