### ISSUE TITLE
Rename on Type: linked edit mode is terminated when the tag becomes empty

### ISSUE THREAD

**Issue by ornellaalt** [microsoft/vscode#105860]
Testing #105760

![renameontype](https://user-images.githubusercontent.com/44654695/91888855-caf05980-ec41-11ea-86db-593bcfce2187.gif)

Repro: 
on macOS
set Rename on Type to true in both user and workspace
Create HTML file
Try changing opening tag

Didn't see any syncing happening, I also tried changing the closing tag and did not see syncing.

**Comment by ornellaalt** [comment]
It did work for me when pasting in a character, i.e. <head> </head> paste x in -- synced up to <heaxd> </heaxd>

**Comment by aeschli** [comment]
In the screencast, when you delete `head` you see that the closing tag is modified as well. 
But it's a bug that the sync mode ends once the tag is empty. I'll look at that.
