### ISSUE TITLE
It is unclear which groups exist in the context menu in variables view

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#105830]
Testing #105593

I could not find any documentation about the group names that exist in that context menu.

**Comment by dbaeumer** [comment]
Some doc here would be helpful: https://code.visualstudio.com/api/references/contribution-points#Sorting-of-groups

**Comment by isidorn** [comment]
Completely agree. Assigning to August to try to tackle tomorrow, might get pushed to debt week.

**Comment by isidorn** [comment]
I have transitioned the variables to be commands so that they all use proper groups. To verify:
1. Start debugging, hit a breakpoint
2. Verify all actions in the Variables context menu work as expected

The documentation I will do as part of Friday doc update.
