### ISSUE TITLE
'Recently used' custom tasks keeps growing

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#105812]
Issue Type: <b>Bug</b>

#105736

Not sure when another one is added, but there is only one in tasks.json:

![image](https://user-images.githubusercontent.com/9205389/91843994-f7fb3700-ec56-11ea-98f5-f7a860a8e01d.png)

VS Code version: Code - Insiders 1.49.0-insider (b6d4fec3714ff897f72c1dab8cc02b7421a8f131, 2020-09-01T05:48:29.841Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 7aad610c-0e6b-48aa-ba87-b704b1b543cf|
|Screen Reader|no|
|VM|22%|
</details>

**Comment by alexr00** [comment]
This is happening because you keep changing the task. Each time the task is run, we save it as a different recently used task. It isn't ideal, but we can't tell that the task is the same as the one you've already run (because it actually isn't the same, you've changed its core properties).

**Comment by chrmarti** [comment]
Couldn't you remove those that are no longer in the task.json?

**Comment by alexr00** [comment]
Since tasks in the recently used list could also come from extensions (ex. npm, typescript, etc.) I don't immediately know if a recent task came from tasks.json or from an extension. I could annotate tasks that came from the tasks.json and remove those I suppose.
