### ISSUE TITLE
TabCompletionController causes severe perf hit

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#10586]
fyi @jrieken 

* Open attached file
* Go to last line
* click around

![image](https://cloud.githubusercontent.com/assets/5047891/17702983/5b433718-63d0-11e6-8655-199f356acedf.png)

[result - Copy.zip](https://github.com/Microsoft/vscode/files/420500/result.-.Copy.zip)

[getNonWhitespacePrefix-CPU-20160816T164203.cpuprofile.txt](https://github.com/Microsoft/vscode/files/420513/getNonWhitespacePrefix-CPU-20160816T164203.cpuprofile.txt)

**Comment by jrieken** [comment]
Coool. Would it make sense to push that down to the model?

**Comment by alexandrudima** [comment]
I'd wait for one more consumer besides snippets before doing that
