### ISSUE TITLE
Screen cheese with unrealistic execution order

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105836]
* press run 100000-times or write an extension to set `executionOrder` to `100000`
* 🧀 execute button moves off the screen

<img width="213" alt="Screenshot 2020-09-01 at 15 21 58" src="https://user-images.githubusercontent.com/1794099/91856503-f174bb80-ec66-11ea-936c-02ef67a438ad.png">

**Comment by roblourens** [comment]
I know, we are moving it
