### ISSUE TITLE
Vscode completion api bug?

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/vscode#105899]
I have nonempty CompletionList returned by provideCompletionItems, but vscode didn't show it, instead, showed `No suggestions`
I don't know if it was a bug, if not, why this happened and how to let it work?

![image](https://user-images.githubusercontent.com/15936231/91925589-e756c980-ed07-11ea-8f99-6597982d9b27.png)

![image](https://user-images.githubusercontent.com/15936231/91925659-0f462d00-ed08-11ea-90fe-786c389e6bd2.png)

![image](https://user-images.githubusercontent.com/15936231/91925395-7b746100-ed07-11ea-8727-859da4afb567.png)

but delete `a` will work correctly
![image](https://user-images.githubusercontent.com/15936231/91928102-c1342800-ed0d-11ea-8602-0469ebb496dc.png)

**Comment by jrieken** [comment]
A completion item provider is invoked, returns completions but they don't show up! 😕  What's the issue? Filtering! Filtering compares completions with a prefix and hides those that don't match.

#### Example

* trigger completions here: `say.he|` (`|` is the cursor)
* provider returns `abc`, `help`, `hood`
* the editor takes the `he`-prefix and scores it against `abc`, `help`, and `hood`. 
* scoring yields these result: 
  * `abc` - no match, don't show
  *  `help` - good match, show
  * `hood`  - no match, only `h` occurs, don't show
* editor shows `help` suggestion, does *not* show `abc` and `hood` suggestion

#### Extensions Rule!

The above sample was using "defaults" to determine the prefix and the filter criteria. 

 * `prefix:`  each completion can define its very own prefix via [`vscode.CompletionItem#range`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3803). Taking the example above, valid prefixes can be `say.he` or `.he` or ` ` (the empty string). Any range is valid as long as it includes the cursor position and is single line only.
* `filter:` each completion can define what string to use when filtering. The default is the label but via [`vscode.CompletionItem#filterText`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3776) any string can be defined

When to use what? It depends on the language, its word definition, and if you control/understand the word definition or not. The defaults usually work well enough but some languages might use a non-intuitive word definition, or completions span multiple words, or completions include non-word character etc. In all those cases the `range`-property should be used.

**Comment by CGQAQ** [comment]
@jrieken Wow!! Thank you so much, I appreciate that
