### ISSUE TITLE
Registering a tree view for web view type throws no data provider error

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#105822]
Testing #105764

- Register a tree view for web view type
- Expected more appropriate error

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/10746682/91850266-8b376b00-ec5d-11ea-85f9-3535412300e2.png">

**Comment by mjbvz** [comment]
Closing as won't fix. We can revisit if real world extension authors are confused by how to contribute the various view types
