### ISSUE TITLE
Notebook cell status bar API

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105809]
We have a proposal for cell status bar items but we should revisit its design. The current proposal is modelled closely after the existing global status bar API. However the global status bar and cell status bars have a very different lifecycle: the global status bar is always there and shares the lifecycle of the editor. Cells on the other hand are usually short-lived, often not visible (not scrolled in view, hidden editor etc pp). 

This is what's needed to manage the status bar for cells: https://github.com/microsoft/vscode-github-issue-notebooks/blob/edf85a2e9db0d28166526c844e479724434209b6/src/extension/notebookProvider.ts#L156-L182 and it shows a couple of weaknesses of the design

* it has much semantic overlap with commands/menus
* it listens to output changes of any notebook (no matter if visible or not), e.g it actively needs to manage status bar item which is often error-prone
* it doesn't know anything about the lifecycle because the workbench will dispose the object the extension has created. That's generally fishy because only object-creator should call dispose.

So, I think we should first justify why context keys and commands aren't sufficient and then we should turn this into a provider model. E.g have a `NotebookCellStatusBarItemProvider` which we ask for cell's items, e.g

```ts
class NotebookCellStatusBarItem {
  command: Command;
  text: string;
}

interface NotebookCellStatusBarItemProvider {
  // provider has changed, 
  onDidChange?: Event<void>;

  provideCellStatusBarItem(cell: NotebookCell): ProviderResult<NotebookCellStatusBarItem>;
}
```

We decide when to call `provideCellStatusBarItem`, like on output change etc, and it will return short-lived data-only objects that we manage.

**Comment by joaomoreno** [comment]
> I think we should first justify why context keys and commands aren't sufficient and then we should turn this into a provider model

100% agree.

**Comment by roblourens** [comment]
I agree, this isn't finalized, we just had to get it off the ground. I would like to see a model that lets an extension write a static contribution for a cell status bar item but it needs to be able to plug in dynamic data (like for the title). This would need

- a new type of contribution point
- the ability to set new arbitrary context keys on a cell, or a single object-type context key that multiple parties can contribute to
  - this would be a new concept in vscode, TreeItems only let you set a single context key
- A way to plug in dynamic data, I like the concept of a title that references a custom metadata field

I don't think the provider model works. The extension needs to be in total control of when the items change. And maybe we have solved  these issues with other providers, but wouldn't it have to do the same bookkeeping to keep track of whether an item has already been added to a cell? I think a static contribution model would be easiest, especially for items that don't have dynamic content.

**Comment by roblourens** [comment]
Talked with Peng about it and I see how the provider model makes sense. I still like the static contribution model because it fits a lot of usecases very easily but maybe it requires too much new stuff.

**Comment by jrieken** [comment]
> lets an extension write a static contribution for a cell status bar item but it needs to be able to plug in dynamic data (like for the title).

What's the use-case for that? This has come up for commands as well, e.g. the ability to change its title, but we have always stayed away from that because of the confusion that will cause. Is not being able to update (command) title a blocker or something that's nice to have?

**Comment by roblourens** [comment]
Most of the scenarios that we've seen from the python extension would be served with static titles. Some of them have dynamic titles and some of them it's easy to imagine how dynamic data would show up - maybe the title is just an icon but then you want to have a tooltip with details or a timestamp or something.

one example -

![image](https://user-images.githubusercontent.com/323878/92010538-c2118d80-ecfe-11ea-9001-cb6ade72599b.png)

and it would be very cool to have something like a gitlens annotation here. I think an API that only works like a toolbar would be incomplete.

**Comment by roblourens** [comment]
Here's what we're planning, hopefully for March if I can finish it:

- Remove `createCellStatusBarItem`
- Remove the `statusMessage` cell metadata
- Replace it with this provider pattern

```ts
export class NotebookCellStatusBarItem {
    readonly text: string;
    readonly alignment: NotebookCellStatusBarAlignment;
    readonly command: string | Command | undefined;
    readonly tooltip: string | undefined;
    readonly priority?: number;
    readonly accessibilityInformation?: AccessibilityInformation;

    constructor(text: string, alignment: NotebookCellStatusBarAlignment, command?: string | Command, tooltip?: string, priority?: number, accessibilityInformation?: AccessibilityInformation);
}

interface NotebookCellStatusBarItemProvider {
    onDidChangeCellStatusBarItems?: Event<void>;
    provideCellStatusBarItems(cell: NotebookCell, token: CancellationToken): ProviderResult<NotebookCellStatusBarItem[]>;
}

export namespace notebook {
    export function registerNotebookCellStatusBarItemProvider(selector: NotebookDocumentFilter, provider: NotebookCellStatusBarItemProvider): Disposable;
}
```

**Comment by jrieken** [comment]
> // Called when a cell becomes visible

I'd say also when a cell output changes and likely others
