### ISSUE TITLE
Support --no-verify variant of commit

### ISSUE THREAD

**Issue by septatrix** [microsoft/vscode#105881]
For the source control tab I would like to be able to issue a commit without verification. This is currently not possible.

**Comment by joaomoreno** [comment]
Force push is supported by enabling `git.allowForcePush`.

**Comment by SneakyFish5** [comment]
Should this be implemented as a `git` setting or a new command?

**Comment by septatrix** [comment]
To make it consistent with force push a setting might be appropriate. However I would like to enable this option for a single commit/push only. For a commit it might also be possible to offer this as an alternative in the error message which opens when a commit fails.

**Comment by septatrix** [comment]
Personally I was hoping for both of these to be an alternative command in the menu of the version control tab so these can be used as a one-off and do not need to be enabled by default.

**Comment by joaomoreno** [comment]
**Verification**

Once you enable the `git.allowNoVerifyCommit` setting, you should have access to all the matching commands:

![image](https://user-images.githubusercontent.com/22350/94449748-bc4b8280-01ac-11eb-96fd-bef9561adc16.png)

**Comment by septatrix** [comment]
Tested at a colleague's pc who has insider installed and it seem to work as expected, thanks!
