### ISSUE TITLE
JavaScript auto attach doesn't work

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#105837]
Testing #105771

On a fresh user data dir:

1. Enable `debug.node.autoAttach`
2. Open Terminal
2. Launch a node script

🐛 It doesn't auto attach

This combined with the mess of https://github.com/microsoft/vscode-js-debug/issues/731 makes for an incredibly flaky experience. Notice my struggle as I toggle settings around, only getting into unexpected situations:

![recording (19)](https://user-images.githubusercontent.com/22350/91856723-3b5da180-ec67-11ea-8b7b-e4399407ada4.gif)

**Comment by connor4312** [comment]
@joaomoreno I fixed that issue and will bump stuff in the next Insiders. Please give this another quick try tomorrow and see if it's better for you.

**Comment by joaomoreno** [comment]
This still doesn't work in:

```
Version: 1.49.0-insider (user setup)
Commit: 8c9b4015feb0297d99c8051c35e85d208ffe83e3
Date: 2020-09-03T06:00:27.719Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by joaomoreno** [comment]
Nope, it works, I was forgetting the `--inpect` flag, I thought it wasn't necessary.

**Comment by connor4312** [comment]
@joaomoreno running `node main.js`, the --inspect flag should only be required if `debug.javascript.autoAttachFilter` is set to `onlyWithFlag`. Is that the case for you?

**Comment by joaomoreno** [comment]
No, I have it set to `smart`.

![image](https://user-images.githubusercontent.com/22350/92218513-89f28200-ee99-11ea-8390-7322b7a6b547.png)

This is Windows, Node 12.13.1

**Comment by connor4312** [comment]
Ok, thanks, what does `echo $env:VSCODE_INSPECTOR_OPTIONS` sohw?

**Comment by connor4312** [comment]
I repro'd this today. I'm not sure how it was working before, I definitely was using this for a while 🤔

**Comment by connor4312** [comment]
Note to verifiers: you may need to auto attach twice to see the fix if you previously had auto attach on. The first auto attach+activation, the cached bootloader will be updated and contain the code changers.
