### ISSUE TITLE
Comma triggers IntelliSense in JSON

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#105804]
Issue Type: <b>Bug</b>

In 1.48 typing a comma at the end of a line within an array does not trigger IntelliSense in 1.49 it does. The problem with that is when I add a comma after the last entry in an array and then press enter to add another entry on the next line, `Enter` instead accepts the first proposal. That's unexpected.

VS Code version: Code - Insiders 1.49.0-insider (b6d4fec3714ff897f72c1dab8cc02b7421a8f131, 2020-09-01T05:48:29.841Z)
OS version: Darwin x64 19.4.0

**Comment by aeschli** [comment]
I'm not aware of any changes. I just checked, trigger characters are `"` and `:`.

Do you have a small sample?

**Comment by chrmarti** [comment]
Cannot reproduce anymore and don't remember the exact steps. 😬 Closing.
