### ISSUE TITLE
Show number of filtered debug console items

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#105866]
Testing https://github.com/microsoft/vscode/issues/105185

Just another feature request. It would be useful to see how many debug console items are filtered out. Especially if I see this number going up, then I know I am missing new messages.

**Comment by isidorn** [comment]
Yeah great idea. I think this could be shown in the filter area.
This could be a shared experience also in the Problems view @sandy081 

I am opening this up for PRs.

**Comment by sandy081** [comment]
@isidorn FYI, problems view already show this like below

<img width="458" alt="image" src="https://user-images.githubusercontent.com/10746682/91958545-caba9180-ed07-11ea-9c7a-ab7c6b194975.png">

**Comment by isidorn** [comment]
Great! Then we should just copy what Problems is doing 
https://github.com/microsoft/vscode/blob/00754e4babebc9ee5aa881234bc16366c4f32aa9/src/vs/workbench/contrib/markers/browser/markersViewActions.ts#L393

Assigning to September so I tackle then if no PR's arrive

**Comment by pfongkye** [comment]
Hi @isidorn 
I can take a look into this if no one else is assigned.

**Comment by isidorn** [comment]
@pfongkye sounds great. We should just have the exact same functionality as the Problems view, so checking how it is done there is a good start.

**Comment by isidorn** [comment]
@pfongkye friendly ping regarding this, since if you are not looking into it I might take a look next week...

**Comment by pfongkye** [comment]
> @pfongkye friendly ping regarding this, since if you are not looking into it I might take a look next week...

Hi @isidorn sorry, I didn't have time last week. I've just started looking into the issue. I hope to have something ready for next week if it's ok with you. I'll keep you updated. Thanks.

**Comment by isidorn** [comment]
@pfongkye great thanks. Since you are already on this I will remove the `help wanted` label

**Comment by isidorn** [comment]
Thanks to @pfongkye we now have this.
Adding verification needed so we get this verified:
* Start debugging and verify when using the debug filter that the filter shows what is the number of hidden items
