### ISSUE TITLE
Store ssh password

### ISSUE THREAD

**Issue by vmiheer** [microsoft/vscode#105858]
There is existing issue: https://github.com/microsoft/vscode/issues/74890,
For mac/linux such solutions exists: https://code.visualstudio.com/blogs/2019/10/03/remote-ssh-tips-and-tricks#_controlmaster
And for windows, git credentials are store via wincred: https://code.visualstudio.com/docs/remote/troubleshooting#_sharing-git-credentials-between-windows-and-wsl

I hope it would be possible for storing ssh passwords as well.

**Comment by roblourens** [comment]
Those links aren't really related to storing passwords, and no, there is no way for us to securely store a password.

**Comment by vmiheer** [comment]
Is this because of nodejs limitation?

**Comment by roblourens** [comment]
Storing user passwords is just an area that I don't want to touch. Would rather people stick to standard ssh auth methods like using ssh keys: https://code.visualstudio.com/docs/remote/troubleshooting#_configuring-key-based-authentication
