### ISSUE TITLE
Should there be `onDispose` for Notebook statusbar items?

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#105839]
#105768

It look like the code I write dealing with statusbar items in the Notebook tends to run in the context of the notebook or in the context of the extension. So the lifecycle of that code is different from the lifecycle of the statusbar item which is disposed when its cell is removed or when the notebook is closed.

Should there be `onDispose` for Notebook statusbar items, such that the code managing it knows when it is gone?

**Comment by jrieken** [comment]
related https://github.com/microsoft/vscode/issues/105809

**Comment by jrieken** [comment]
Lets close this in favour of the larger overhaul of this
