### ISSUE TITLE
How to control the terminal length using vscode api

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode#105807]
I'm using the vscode api like this 
```javascript
import {window} from 'vscode';
const cmd="cd ~/.vscode-server/extensions/xxx.terminal-0.0.1; sh test.sh";
const terminal =window.createTerminal("patchbuild");
terminal.sendText(cmd);
terminal.show();
```
The actual `cmd` send to terminal is composed of several shell commands through a semicolon. After i run the cmd, the created terminal changed like this. 
![image](https://user-images.githubusercontent.com/12140508/91837180-669fbb00-ec7e-11ea-97d9-b504a8b5a0d4.png)

![image](https://user-images.githubusercontent.com/12140508/91836313-2b50bc80-ec7d-11ea-836c-3f34d8a9daa8.png)
Only a few characters can be displayed per line, resulting in incomplete command display. 

The normal display should be as follows.
![image](https://user-images.githubusercontent.com/12140508/91836680-b7fb7a80-ec7d-11ea-8150-6462d96038c9.png)

 Is there something wrong with my using? Hope for your help. Thanks a lot.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/3595

**Comment by Abbyyan** [comment]
> /duplicate [microsoft/vscode-remote-release#3595](https://github.com/microsoft/vscode-remote-release/issues/3595)

It has not been fixed yet, right?

**Comment by Tyriar** [comment]
@Abbyyan yes, it is still open.
