### ISSUE TITLE
Hover window semantic token colouring

### ISSUE THREAD

**Issue by H0stman** [microsoft/vscode#105892]
Would be nice if the overridden colours in editor.semanticTokenColorCustomizations would show up in hover windows.
![image](https://user-images.githubusercontent.com/25237346/91913398-d0878700-ecb5-11ea-8643-d830a5cd4237.png)
![image](https://user-images.githubusercontent.com/25237346/91913403-d41b0e00-ecb5-11ea-8c3c-c0e9469a3640.png)

**Comment by aeschli** [comment]
I personally think it's better to to stick with using TextMate only for the code snippets in hovers
- getting semantic tokens would require another roundtrip to the language server, making the hover slower
- our current semantic token API is based on documents, so we would have to create a virtual document
- semantic highlighting is based on project context (resolving types) which is not possible if one gives just a snippet.
