### ISSUE TITLE
WVV visibility change is not set when view is hidden via context menu

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#105861]
Testing #105764

Repro Steps:
1. Add visibility handler to webview view sample

```ts
webviewView.onDidChangeVisibility(() => {
  vscode.window.showInformationMessage(`Webview is now ${webviewView.visible ? 'visible' : 'hidden'}.`);
});
```
2. Run webview view sample
3. Right click hide the view in explorer

:bug: => no visibility change event is triggered

**Comment by mjbvz** [comment]
This view is disposed when it is hidden via the context menu. You can use the `onDidDispose` listener to handle this.

The thinking is that hiding a view is a longer term action than simply collapsing it
