### ISSUE TITLE
[rename on type] undo of paste edit is not linked

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#105808]
Testing #105760

- `<head></head>`
- paste 'x' into the tag
- `<heaxd></heaxd>`
- undo
-> `<head></heaxd>`

I need to do another undo to get back to - `<head></head>`

**Comment by aeschli** [comment]
Yes, it's two undos, that's an open bug I want to look at with @alexdima

**Comment by aeschli** [comment]
@alexdima I assume you worked on the undo story this with Pine: https://github.com/microsoft/vscode/blob/aeschli/remoteThemeFix/src/vs/editor/contrib/rename/onTypeRename.ts#L222. Can you help?
