### ISSUE TITLE
No info/error while registering a web view provider when type is not provided

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#105820]
Testing #105764

- Used [webview view extension sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/webview-view-sample)
- Open `package.json` and remove `"type": "web"` property for the view
- Run the extension and open the view

View is empty and there is no info/error

**Comment by mjbvz** [comment]
Closing as we have not seen additional reports of this

On note: if you remove `"type": "webview"`, the contribution is still valid but becomes for a tree based view instead
