### ISSUE TITLE
${command:foobar} called with unexpected arguments

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#105819]
Issue Type: <b>Bug</b>

#105736

Looks like the list of variables I'm using:

![image](https://user-images.githubusercontent.com/9205389/91848645-1105e700-ec5b-11ea-9c01-200c1b20bb2c.png)

The task:
```json
        {
            "type": "custombuildscript",
            "flavor": "A${input:chooseFlag}B${input:someCommand}C${input:chooseNumber}D",
            "flavor2": "${command:foobar}X${defaultBuildTask}A${input:chooseFlag}B${input:someCommand}C${input:chooseNumber}D",
            "flags": [
                "${workspaceFolder}",
                "${workspaceFolderBasename}",
                "${file}",
                "${relativeFile}",
                "${relativeFileDirname}",
                "${fileBasename}",
                "${fileBasenameNoExtension}",
                "${fileDirname}",
                "${fileExtname}",
                "${cwd}",
                "${lineNumber}",
                // "${selectedText}",
                "${execPath}",
                "${defaultBuildTask}",
                "${env:USERNAME}",
                "${config:editor.fontSize}",
            ],
            "problemMatcher": [],
            "label": "custombuildscript: 64"
        },
```

VS Code version: Code - Insiders 1.49.0-insider (b6d4fec3714ff897f72c1dab8cc02b7421a8f131, 2020-09-01T05:48:29.841Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 7aad610c-0e6b-48aa-ba87-b704b1b543cf|
|Screen Reader|no|
|VM|22%|
</details>

**Comment by alexr00** [comment]
After looking into it, this is how variable resolution of commands has always worked. The command is passed the object that it was resolved from. For tasks, that means that it is passed an array of variables that are used in tasks.
