### ISSUE TITLE
Error while Signing in to Github 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#105817]
- I tried to turn on settings sync from my windows VM (parallels) and I got following error

<img width="471" alt="Screenshot 2020-09-01 at 13 49 00" src="https://user-images.githubusercontent.com/10746682/91845845-30504480-ec5a-11ea-8927-b06ec9155e6f.png">

**Comment by RMacfarlane** [comment]
@sandy081 What version of windows is your VM? it looks like it's using an unsupported TLS version

**Comment by sandy081** [comment]
Sorry for not providing info here, I did not access my VM yet, Will check again and let you know tomorrow.

**Comment by sandy081** [comment]
It works for me now.
