### ISSUE TITLE
Crashing on OS X 10.8.3

### ISSUE THREAD

**Issue by tarunjuneja** [Microsoft/vscode#1058]
Hi,

The moment i upgraded from an older version to v0.10.1it started crashing. I can not open it anymore.

I tried downloading greater version like 
- v0.10.2
- v0.10.3

But that does not work either. Please see attached file [crash info.txt](https://github.com/Microsoft/vscode/files/53608/crash.info.txt) for more information.

Thanks

**Comment by egamma** [comment]
@bpasero duplicate of atom/electron#3530?

**Comment by bpasero** [comment]
@egamma yes, we do not support 10.8, same as Atom.
