### ISSUE TITLE
Auto attach versus debug terminal

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#105852]
> My 2 cents: the node auto attach feature should be unified with the JavaScript Debug Terminal. To make a smoother unified experience. I understand this will probably not make all the users happy but just feels like they should be one thing to me.

_Originally posted by @isidorn in https://github.com/microsoft/vscode/issues/105771#issuecomment-684842595_

>Yeah, for something that should be a smooth experience (auto attaching to a node process), I must say the following points make it confusing:
>
> - There are two non-obvious entry points (enable a setting and use terminal or use javascript terminal). Can't we just have one obvious entry point? Eg: a notification which opens up the first time a node process is spawned from any terminal _Do you wanna debug? Yes, Always, No, Don't Bother Me Again_.
> - Settings intersect and have complex dynamics between them. Setting values and descriptions are confusing. But then again, maybe users won't be spending much time playing around with these settings.

_Originally posted by @joaomoreno in https://github.com/microsoft/vscode/issues/105771#issuecomment-684859805_

**Comment by connor4312** [comment]
I understand this perspective and agree with it to some extend. The thing that auto attach gets us, particularly if 'smart' is the default for all users, is 'zero knowledge' debugging -- people just learning how to program can run `node hello-world.js` in the terminal and get debugging without knowing about the debug terminal, or launch configs, or our other entrypoints.

cc @kieferrm as we were discussing this

**Comment by weinand** [comment]
In https://github.com/microsoft/vscode-js-debug/issues/732 we basically agreed that there is no need for having "on/off/disabled" setting for auto-attach. This means that "auto-attach" is no longer visible in the UI.

This raises the question whether every integrated terminal is capable to "auto attach" or only the "javascript terminal".

If we answer 'every integrated terminal is capable to "auto attach"', then we do no longer need the "javascript terminal", and have simplified 'zero knowledge' debugging to the max. This is a model I like. The only problem I can see is that it is no longer straightforward to run a JavaScript program without debugging (and a performance penalty).  

If we answer "auto attach" is only enabled in the "javascript terminal" then we have the problem to guide JavaScript users to the "javascript terminal".

**Comment by isidorn** [comment]
I like how @weinand layed out this problem.
 
I vote: let's go aggressive start of milestone and get feedback on Insiders. Being aggressive means option 1: every integrated terminal is capable to "auto attach". On top of that:
* We need to have good "smart" setting which would ignore some scripts which the users are usualy not interested in debugging (@connor4312 already has this I believe)
* We should help the user disable the auto attach behavior if he does not like it. For example: if the user stops the auto attach debug session as soon as it starts we could pop a notification saying "Would you like to disable auto attach bla bla". Alternative ideas: jsDebug could contribute an action to the Debug Toolbar "Disable Auto Attach", so when the toolbar appears the user can click on that.
