### ISSUE TITLE
Infinite progress when webview view provider is not registered

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#105834]
Testing #105764

- Register a webview view in package.json
- Do not register webview view provider
- Open the webview and there is an infinite progress
- It is expected to show an error at some point of time

**Comment by mjbvz** [comment]
How long do you give tree views to resolve?

**Comment by sandy081** [comment]
2 seconds

https://github.com/microsoft/vscode/blob/908559b/src/vs/workbench/contrib/views/browser/treeView.ts#L1034

**Comment by mjbvz** [comment]
Closing this due to lack of additional feedback. Happy to take a PR though if anyone is feeling ambitious and wants to explore fixing this
