### ISSUE TITLE
Screencast: return mouse indicator entry back to "red" after invalid entry, or add warning

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#105854]
Testing #105721

The `Mouse Indicator Color` setting functions properly when I enter an invalid color: it defaults back to a red indicator. But I was thinking perhaps adding a warning message to users that they have entered an invalid color (like the warning for invalid `Mouse Indicator Size`), and/or auto-filling the entry back to red would emphasize to them why their indicator has turned red again.

**Comment by lszomoru** [comment]
The setting is of type string, with `format: "color-hex"` which provides a good error message while editing the setting in the JSON file. As far as I can tell there is no way to currently get the same experience in the settings UI. I do agree that it would be nice to have a better experience for editing color settings in the settings UI. 

@roblourens, have we ever considered adding a `color` type/validation for a setting?

**Comment by roblourens** [comment]
We have to implement these individually and that format isn't implemented yet

**Comment by roblourens** [comment]
It would be a feature request for the settings editor, probably easy, feel free to assign it to me

**Comment by lszomoru** [comment]
@roblourens, would you be opened for me to submit a pull request? 
I would be happy to take a stab at this in my free time to learn more about our codebase.

**Comment by roblourens** [comment]
Sure! Here are our string validations:

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/preferences/common/preferencesValidation.ts#L93
