### ISSUE TITLE
graphic glitch

### ISSUE THREAD

**Issue by Thuse91** [microsoft/vscode#105850]
Issue Type: <b>Bug</b>

literally have to do nothing and it occurs. if i tab out, change screen, or just hover it comes. if i type in a field it will occur everywhere except that field. if i stop typing it will occur in that field aswell.
Have tried reinstalling, removing extensions, adding ""disable-hardware-acceleration": true "
havent had any improvements.
![siiiiighlol](https://user-images.githubusercontent.com/68929562/91879331-4670fb80-ec80-11ea-9711-989353bd6eaf.png)

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.5.0
material-icon-theme|PKi|4.2.0
LiveServer|rit|5.6.1

</details>

**Comment by gjsjohnmurray** [comment]
> adding ""disable-hardware-acceleration": true "

Where did you add this?

**Comment by Thuse91** [comment]
Open the Command Palette (Ctrl+Shift+P).
Run the Preferences: Configure Runtime Arguments command. 
in here.
altho i just found the issue. it was image sharpening from Nvidia control panel that broke it.

**Comment by Thuse91** [comment]
some people sugested to put the "disable-hardware-acceleration": true in the VSC
but found a small comment on reddit saying it was an image sharpening issue.
so if this problem occurs for someone else it might be solved by going into you nvidia control panel.
into 3d settings. go into visual studio code, disable image sharpening for that program.
