### ISSUE TITLE
Errors when reviewing TS changes

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105842]
* use PR extension
* select a TS file from a PR
* :bug: you see errors for the left hand side

<img width="1552" alt="Screenshot 2020-09-01 at 16 16 50" src="https://user-images.githubusercontent.com/1794099/91862704-9b0b7b00-ec6e-11ea-8c56-3d73f23db323.png">

**Comment by mjbvz** [comment]
For now, I'm going to disable JS/TS language entirely in `pr:` schemed files (this is how it used to be as far as I can tell)
