### ISSUE TITLE
Clean-up cell output debt

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105846]
Some debt has accumulated around cell output and we should start to clean things up

* [x] there is `transformEditsOutputs` and `transformSpliceOutputs` which feel like they are on the wrong layer, e.g should this be part of the serialisation of output
* [x] similar to transfromOutputs is `IProcessedOutput` which also seems wrongly placed. Maybe the internal model object specs all the data of those two and the API types are directly converted into those types
* [x] the proposed API is very rough, esp the `outputKind`-marker is an api-alien concept

**Comment by rebornix** [comment]
This one relates the renderer work @connor4312 is doing now. If the output renderers are all pure and lives in the webview, then we don't need `IProcessedOutput` or `transform*Outputs` at all as there is no back and forth between the UI and ExtHost, raw outputs will be the source of truth.

**Comment by connor4312** [comment]
Yea, I can clean these up this month.

**Comment by jrieken** [comment]
@connor4312 Can you/we tackle those debt items before going all-in on the new API and such?

**Comment by jrieken** [comment]
@rebornix @roblourens I have created #110855 which removes the transform logic and moves that into a single place

**Comment by connor4312** [comment]
Sure, I should have time this month to tack some of that

**Comment by connor4312** [comment]
Hi, finally have some unallocated time to do this 🙂 

Before I just in, I know you have been working on hammering out the final versions of these APIs. Does that work affect this cleanup, or can I go ahead and take care of this tomorrow?

**Comment by jrieken** [comment]
Please hold back or join us in #115817

**Comment by jrieken** [comment]
We are done with this
