### ISSUE TITLE
WVV title not persisted no reload

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#105867]
Testing #105764

Not sure if this is actually better behavior, but if I set a webview view title and then reload, the view title is not preserved.

**Comment by mjbvz** [comment]
To verify:

1. Create webview view with a custom title
1. Reload.
1. Make sure the title is displayed correctly.
1. Also make sure the `.title` property on the WebviewView is correct
1. Try this again but with the webview collapsed when you do the reload

**Comment by mjbvz** [comment]
Actually, after discussing this at the extension authors call, I am reverting this change.

Say you have a webview view that shows the current editor's name in its title. You then collapse that view and reload VS Code. That title will now not be updated until the webview becomes visible again. It makes more sense to show the generic webview title in this case
