### ISSUE TITLE
"New file" link from Welcome page presents selector that "New File" from File menu doesn't

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#105825]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/6726799/91851138-9509a000-ec56-11ea-9640-d5c4fe65f0be.png)

This selector does not appear whan I use File\New File or its Ctrl+N shortcut.

Is this difference intentional?

VS Code version: Code - Insiders 1.49.0-insider (b6d4fec3714ff897f72c1dab8cc02b7421a8f131, 2020-09-01T05:54:42.740Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
This does not look good to me, but I am not sure where this originates from, adding @chrmarti for welcome and @mjbvz for custom editors.

**Comment by bpasero** [comment]
@rebornix fyi I think a regression from one of your changes, you check on `args` to get a `viewtype` but there can be other args passed to this command and I think we only want to go into this picker when a `viewtype` is provided. Please check my fix in https://github.com/microsoft/vscode/commit/7686b52a823e231dacda4e86d86932998cafab19
