### ISSUE TITLE
Make the other debug actions a button to improve discoverability

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode#105893]
When there is a file open, and no debug configurations, vscode shows multiple options, but the only one that stands out is the big "run and debug" button. 

It actually took me a few minutes to find out the option I want, which is to add a new configuration, clicking in the link "create a launch config", or "show" all configs.

![image](https://user-images.githubusercontent.com/2473545/91915536-3f9eb480-ec91-11ea-83b1-50511499f263.png)

Other things I tried before figuring this out was searching (f1) for "debug new", "debug create", or something similar. 
Since I did not know exactly the keywords (launch config), I could not quickly figure out what to do as well.

There has to be some way to improve searchability of commands with non obvious names.

**Comment by phgmacedo** [comment]
I also tried searching (f1) for "add configuration", "add debug", "debug config", none of these options have fruitful results.

**Comment by isidorn** [comment]
This is a fair request, however we have designed the current experince on purpose - that is you can debug withuot having a launch.json.
I do however understand your point of view and I would leave this issue open to see if more users hit this issue.
Thanks for feedback.

**Comment by phgmacedo** [comment]
I'm not suggesting to remove the  "run and debug" option, I'm just asking to consider making the 2 other options more visible - maybe adding 2 other buttons to this screen, to create the launch, and to show the available debug config.
