### ISSUE TITLE
Execution order color

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#105898]
Testing #105769

There is no hover explaining the sequence counter (I think that's what the block is showing). Being unfamiliar with Notebooks, I didn't know what that UI element was for. It seems to increase as cells are executed. I initially thought it was a result count until I turned on the Notebook status bar.

![image](https://user-images.githubusercontent.com/12818376/91925228-6b1da100-ec89-11ea-8d38-70c5374ce1d7.png)

**Comment by gregvanl** [comment]
There might also be a color contrast issue as the block is small and very faint.

**Comment by roblourens** [comment]
Maybe it could get a tooltip. I'm not sure about color contrast, @misolori

**Comment by misolori** [comment]
You're right in the selected state it doesn't pass the ratio. If we bump the opacity to `.7` it will pass:

<img width="350" src="https://user-images.githubusercontent.com/35271042/92010396-9db5b100-ecfe-11ea-8859-65a196e5c819.png">

![image](https://user-images.githubusercontent.com/35271042/92010601-d6ee2100-ecfe-11ea-93eb-853dfa14158b.png)
