### ISSUE TITLE
Welcome content is not shown in webview View

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#105832]
Testing #105764

- Add welcome content to a webview View

```json
"viewsWelcome": [
			{
				"contents": "this is sample",
				"view": "calicoColors.colorsView"
			}
		],
```

content is not shown

**Comment by mjbvz** [comment]
@sandy081  For webview based views, I believe an extension can already show a custom "welcome view" if it is empty so I don't know if we need this contribution point as we did for tree views. Can you please explain how you think `viewsWelcome` should work with webview based views?

(welcome view issue for my own reference: https://github.com/microsoft/vscode/issues/89080)

**Comment by sandy081** [comment]
Yeah I agree that welcome view contribution is not necessary, but it has to be clear if extension author uses it, probably throw an error or log the error in dev tools?

**Comment by mjbvz** [comment]
Thanks.  Next iteration:

- I'll update the docs on `viewsWelcome` to make it clear they only apply to tree views.
- Add a notification if a webviewView is registered for a webview view

**Comment by gjsjohnmurray** [comment]
Might extension B want to contribute welcome content to a webview view belonging to extension A?

Or from the other perspective, maybe the author of extension A could have a way of declaring whether or not viewsWelcome contributions to A's webview view by other extensions are, well, welcome?

**Comment by mjbvz** [comment]
The welcome views only show fro empty tree views. There's no equivalent of being empty for a webview view.

We also want the webview view to full control its presentation. A webview based view could pull in content from other extensions through contributions, but this is not something we can standardize in the same way as tree views

**Comment by mjbvz** [comment]
I decided just to update the API documentation here. Unless we see this contribution point causing lots of confusion, I don't think we need runtime warnings for developers
