### ISSUE TITLE
Cmd + A in `Save as` input doesn't select whole text

### ISSUE THREAD

**Issue by korzio** [Microsoft/vscode#10581]
![screen shot 2016-08-16 at 14 11 03](https://cloud.githubusercontent.com/assets/1259644/17698393/477e047a-63bb-11e6-977b-e20deb81644c.png)
- VSCode Version: 1.4.0
- OS Version: 10.11.4 (15E65)

Steps to Reproduce:

1.  New File
2. Cmd + S (Save file)
3. Blur `Save As` input (click on folder or somewhere else)
4. Focus on `Save As` input
5. Cmd + A (try select the whole text inside `Save As` input)
6. Text is not selected

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/797
