### ISSUE TITLE
When running previous cell could run

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#105882]
- VSCode Version: 1.49.0 Insider
- OS Version: Win10

Adding cells and running them perform runs in wrong order

![bug_run](https://user-images.githubusercontent.com/375556/91906500-310bc980-eca0-11ea-9ee0-f98c2416c680.gif)

**Comment by colombod** [comment]
@jrieken, @rebornix, @brettfo Do you encounter this before?

**Comment by roblourens** [comment]
Sorry, it's kind of hard to tell what's going on. I guess you clicked run on one cell and it ran the whole notebook. The extension decides when a cell runs. Can you tell whether `executeAllCells` was run instead of `executeCell`? If not, I think you'll have to see what the extension is doing.
