### ISSUE TITLE
VScode not connecting to ipykernel

### ISSUE THREAD

**Issue by saurav2608** [microsoft/vscode#105971]
- VSCode Version: 1.48.2
- OS Version: macOS Catalina 10.15.6

Steps to Reproduce:

1. create a new folder test. Run pipenv to install packages (jupyter, ipykernel)
2. Open folder in VSCode and create a new notebook using the interpreter 'test'. 
3. Error message : Unable to start session for kernel Python 3.8.3 64-bit ('test': pipenv). Select another kernel to launch with.

*Note*: preexisting pipenv interpreters are working fine. For example selection pre-existing env in step 2. 

Does this issue occur when all extensions are disabled?: NA. Python extension is needed for notebooks.

**Comment by spiffyspider** [comment]
I have exactly the same problem.  VS Code Version 1.48.2, macOS Catalina 10.15.6.  Cannot connect to kernels created by pipenv.

**Comment by saurav2608** [comment]
Just for information. I resolved the issue following the steps [here](https://github.com/microsoft/vscode-python/issues/13701#issuecomment-685097996).
