### ISSUE TITLE
Notebook diff: reverting changes does not update diff view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#105917]
Testing #105770

1. Open `my-work.github-issues` from the `vscode` repository and make some changes to it
2. Open in SCM diff view. Click on the Revert button
3. Changes get reverted, however what is shown is stale (it still shows the file as changed)

Compare how this works nicer for regualr files, where on revert the diff view gets auto updated.

**Comment by sana-ajani** [comment]
seeing the same thing, changes are gone from SCM view but the open file is not changed or reverted.

**Comment by isidorn** [comment]
Works nice now, thanks for fixing.
