### ISSUE TITLE
Open Editors View dirty change handler is slowing down typing

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#105968]
- VSCode Version: 1.49-Insiders
- OS Version: macOS

* Turn off auto save
* Have Open Editors View open
* Open a text file, modify, save
* Open again, type, the typing is sometimes sluggish

<img width="1761" alt="image" src="https://user-images.githubusercontent.com/876920/92025985-263f4c00-ed15-11ea-886d-05be6ffd78d4.png">

**Comment by rebornix** [comment]
From the screenshot above, most of the time (hundreds of ms) are spent in Open Editors View.

**Comment by bpasero** [comment]
@isidorn making a file dirty is one of the conditions under which we consider a file as pinned (= no more preview). Other actions are double click on the title, or e.g. moving the tab to another place.

**Comment by isidorn** [comment]
Yes, but that should happen only once, not on every type. So let's wait for @rebornix performance profile...

**Comment by bpasero** [comment]
@isidorn I think @rebornix has a very aggressive auto-save interval below 1s, so maybe this is happening due to that.

For reference the code that pins is here:

https://github.com/microsoft/vscode/blob/4c3f4a5eb5e37f2e48e2965fef9580254acf98da/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L651

**Comment by isidorn** [comment]
@bpasero good point.
@rebornix can you repro if you decrease your auto-save interval?

**Comment by rebornix** [comment]
[Profile-20200903T095901.json.txt](https://github.com/microsoft/vscode/files/5170099/Profile-20200903T095901.json.txt) (change it to .json)

I checked that I have auto save turned off and internal set back 1s. The profiling might amplify the result but in the attached perf log, the typing dirty state handler took 73ms, which I think is not doing right. I remember in old days I filed a similar issue to @bpasero complaining the Tab dirty indicator slows down the typing by 5 to 10ms most of the time, we didn't tackle that one as that's small but this one is much worse.

My suspicion is `contextKeyService.setContext` is somehow significantly slow. In a notebook document, where there are more context key handlers than the normal text editor, the typing latency can go to 200ms and all of them are spent in `contextKeyService.setContext`.

**Comment by bpasero** [comment]
As far as I remember, the performance profile for context key is bogus, you can clearly see that there is a lot of time spend in `setTimeout`:

![image](https://user-images.githubusercontent.com/900690/92206016-1b0c2d80-ee87-11ea-8f0b-8bdb20efd90e.png)

@jrieken or @alexdima might know more about this

**Comment by alexdima** [comment]
IIRC it is best to use JavaScript Profiling to get a closer picture to real world performance.
