### ISSUE TITLE
can trigger suggest after using npm 

### ISSUE THREAD

**Issue by Joker0824** [microsoft/vscode#105918]
- VSCode Version:
版本: 1.48.2
提交: a0479759d6e9ea56afa657e454193f72aef85bd0
日期: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
- OS Version:
 macOS Catalina 10.15.6 (19G2021)

Steps to Reproduce:
1.  see the file
[Kapture 2020-09-02 at 16.46.02.gif.zip](https://github.com/microsoft/vscode/files/5161096/Kapture.2020-09-02.at.16.46.02.gif.zip)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
> see the fileKapture 2020-09-02 at 16.46.02.gif.zip

A gif does not replace steps, please add them along with all other needed info
