### ISSUE TITLE
Notebooks: notebookProvider config to support untitled files better

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#105962]
In the PowerShell extension I had to create two viewTypes to handle the following scenario:

* For `*.Notebook.ps1` files, open with `priority: default`
* For `*.ps1` files, open with `priority: option`

The best way to do this now is with the following configuration:

```json
"notebookProvider": [
      {
        "viewType": "PowerShellNotebookMode",
        "viewType": "PowerShellNotebookModeDefault",
        "displayName": "Powershell Notebook",
        "selector": [
          {
            "filenamePattern": "*.Notebook.ps1"
          }
        ],
        "priority": "default"
      },
      {
        "viewType": "PowerShellNotebookModeOption",
        "displayName": "Powershell Notebook",
        "selector": [
          {
            "excludeFileNamePattern": "*.Notebook.ps1",
            "filenamePattern": "*.ps1"
          }
        ],
        "priority": "option"
      }
],
```

which defines two viewType's with different `priority` and uses `exclude` in the second one to ignore those `*.Notebook.ps1` files

The problem here, is with Untitled files... if I do File->New here's what I see:

![image](https://user-images.githubusercontent.com/2644648/92020328-cd6bb580-ed0c-11ea-9781-3b1afdd2f768.png)

2 "PowerShell Notebook"s. Granted, clicking either works, but we shouldn't see that.

### Proposal

1. If I could specify in the `selector` or somewhere in the config that my viewType supports Untitled files that works I can just choose one of them
2. If I could set the priority based on the selector then I could have only 1 viewType (this doesn't really solve the greater issue, but would solve my issue)

**Comment by TylerLeonhardt** [comment]
This might be important for .NET Interactive notebooks too.

**Comment by gjsjohnmurray** [comment]
See also #110342
