### ISSUE TITLE
Slow markdown preview

### ISSUE THREAD

**Issue by datocrats-org** [microsoft/vscode#105983]
Issue Type: <b>Bug</b>

Markdown preview takes a minute to load and no status is given while waiting

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.55GB (47.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
markdown-shiki|bie|0.1.1
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.2
render-crlf|med|1.5.11
gitignore|mic|1.0.1
vscode-docker|ms-|1.5.0
python|ms-|2020.8.105369
remote-ssh-edit|ms-|0.51.0
debugger-for-chrome|msj|4.12.10
vscode-yaml|red|0.10.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.13
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|10.2.0
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
You have  bunch of markdown related extensions installed. Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
