### ISSUE TITLE
Notebook diff: Stage / Unstage / Revert selected ranges command does not work

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#105920]
#105770

1. Open the `my-work.github-issues` file
2. Have some changes, open the diff view
3. Select some changes. Context menu -> Stage Selected Ranges -> no effect 🐛 

The Unstage Selected Ranges and Revert Selected Ranges equally do not work.

![Screenshot 2020-09-02 at 10 55 03](https://user-images.githubusercontent.com/1926584/91960951-cfcd1000-ed0a-11ea-8d4f-1a7c6b8eb2db.png)

**Comment by rebornix** [comment]
Good catch. It's really interesting as it's a diff editor for notebook cells and the git extension is not aware of that currently.

To improve this experience, the Git extension can detect if the document is a composite document in a notebook document, and then use the Notebook API to update the cell document accordingly. cc @joaomoreno and I'll send PR to polish this next iteration.

**Comment by rebornix** [comment]
It's unknown yet what we should do with git actions in embed virtual diff editor thus we hide them from the notebook diff editor.

**Comment by isidorn** [comment]
I verified that the Git actions are no longer shown in the context menu -> verified.
However the Git stage selected lines is still available in the command palette and triggering it has no effect. Ideally it should not be shown in the command palette.
