### ISSUE TITLE
Notebook diff: rendering glitch with Show Whitespace Differences button

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#105921]
Refs: #105770

1. Open the my-work.github-issues file
2. Make some changes to it, open it in the changes view
3. Notice the blue button rendering glitch in the top right corner

If you do not see it immediatly. Press `tab` a couple of times and it should show up.

![Screenshot 2020-09-02 at 10 55 52](https://user-images.githubusercontent.com/1926584/91961120-0a36ad00-ed0b-11ea-87b3-c895c3fa8956.png)

**Comment by rebornix** [comment]
Verifier: when updating the cell content, you can just add one single space to the end. You should be able to the whitespace diff in the diff eidtor
