### ISSUE TITLE
[LOC(ja-jp)]Fixed inappropriate japanese  "番号"→"いいえ" (Extension：Settings Sync)

### ISSUE THREAD

**Issue by hyoshioka0128** [microsoft/vscode#105932]
Extension：Settings Sync
![Sync](https://user-images.githubusercontent.com/40815708/91970415-9a4c1500-ed52-11ea-84b7-9ec08d6fde19.png)
　↑Fixed inappropriate japanese  "番号"→"いいえ"

**Comment by sandy081** [comment]
This is not coming from built in settings sync feature. I suspect this is coming from Settings Sync extension.
