### ISSUE TITLE
Github repository picker loses search results if I pause for a moment

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#105942]
If I start searching for repos, they show up. But then if I pause or keep typing, they vanish. The playground repos shown are private.
![recording](https://user-images.githubusercontent.com/38270282/91987801-cce41680-ed2e-11ea-8dff-da4062c7585e.gif)

**Comment by joaomoreno** [comment]
This appears to simply be a bug in GH search API.

**Comment by joaomoreno** [comment]
This should be fixed by now since all repos now always show up in quick open even if they dont match.
