### ISSUE TITLE
Obscure error when mistyping renderer entrypoint

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105946]
* playing with new renderer
* make a mistake and mistyped the entry point name
* the error is quite obscure and well hidden, took me some time to figure what the problem was.

Would be great if we can validate the entry point or report it being wrong more clearly

**Comment by connor4312** [comment]
We now show it in the output

![](https://memes.peet.io/img/20-09-8334b59e-927a-4d39-b885-19d6a9a4e6fd.png)
