### ISSUE TITLE
Launch node

### ISSUE THREAD

**Issue by NicolasPopy** [microsoft/vscode#105948]
Issue Type: <b>Bug</b>

launch.json : 
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\Server\\app.js",
            "outputCapture": "std"
        }
    ]
}

ERROR : 
#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 000000E54DB8E330Process exited with code 3221225477

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (4 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.8
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.5.0
vscode-solution-explorer|fer|0.3.11
auto-complete-tag|for|0.1.0
vscode-yarn|gam|1.7.1
vue-snippets|hol|0.1.12
search-node-modules|jas|1.3.0
vscode-language-pack-fr|MS-|1.48.3
remote-wsl|ms-|0.44.5
debugger-for-chrome|msj|4.12.10
vuejs-extension-pack|mub|1.2.1
vetur|oct|0.26.1
vscode-essentials-snippets|rob|2.0.0
vue-vscode-snippets|sdr|2.1.4
tabnine-vscode|Tab|3.0.0
shell-launcher|Tyr|0.4.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by connor4312** [comment]
Please share reproduction steps for your issue

/needsMoreInfo
