### ISSUE TITLE
Mouse scroll-wheel support for iPad OS

### ISSUE THREAD

**Issue by dmitryyankowski** [microsoft/vscode#105906]
I'm using Github Codespaces and I notice that on my iPad Pro (iOS 14), I can't use my Bluetooth mouse scroll-wheel to scroll down on my files :/ 

Any ideas when this will be supported?

**Comment by alexdima** [comment]
fyi @rebornix

**Comment by rebornix** [comment]
It's a bug of iPadOS which is not fixed yet.

**Comment by alefragnani** [comment]
@rebornix you labeled this issue as a _duplicate_ but didn’t linked the issue. 

Are you referring to #85254?

**Comment by VincentDondain** [comment]
https://github.com/microsoft/vscode/issues/106232 maybe?

**Comment by alefragnani** [comment]
@VincentDondain probably, as I commented here https://github.com/microsoft/vscode/issues/85254#issuecomment-700131697 👍 

Thanks
