### ISSUE TITLE
Settings sync: Disabled due to too many requests

### ISSUE THREAD

**Issue by haebler** [microsoft/vscode#105985]
Issue Type: <b>Bug</b>

Disabled due to too many requests.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.36.3
docs-article-templates|doc|0.2.9
docs-authoring-pack|doc|0.1.8
docs-images|doc|0.0.9
docs-linting|doc|0.0.5
docs-markdown|doc|0.2.80
docs-metadata|doc|1.0.5
docs-preview|doc|0.3.55
docs-yaml|doc|0.2.5
latex-workshop|Jam|8.11.1
vscode-docker|ms-|1.5.0
vscode-edge-devtools|ms-|1.0.8
vscode-kubernetes-tools|ms-|1.2.1
anaconda-extension-pack|ms-|1.0.1
devicesimulatorexpress|ms-|2020.0.36321
python|ms-|2020.8.105369
remote-containers|ms-|0.134.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-ssh-explorer|ms-|0.51.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.29.0
hexeditor|ms-|1.2.1
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.10
vscode-yaml|red|0.10.1
code-spell-checker|str|1.9.0
vscode-arduino|vsc|0.3.2

</details>

**Comment by sandy081** [comment]
This is expected and designed. Please restart and you can turn on Sync again .

Can you please provide us the Settings Sync log from Output view when this happened? If you restarted VS Code and lost the log when this issue occurred, you can find it in the logs folder on your disk (run the command `Open Logs Folder...`). This will show us the requests to diagnose.
