### ISSUE TITLE
Unresponsive when expanding a folder with a lot of files

### ISSUE THREAD

**Issue by andrew-w-ross** [Microsoft/vscode#10594]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1.  Clone the [Microsoft/Typescript](https://github.com/Microsoft/typescript) project
2.  In the explorer expand the tests/baselines folder

Code will stop responding. There are a lot of files in it's child folder so it's unreasonable to expect it to list them immediately but having it freeze doesn't feel like the best user experience either.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/9962
