### ISSUE TITLE
New VS Code Install Causes CreateProcess Failed Error Code 216

### ISSUE THREAD

**Issue by grayspace** [Microsoft/vscode#10592]
- VSCode Version: 1.4
- OS Version: Windows 7 Professional (Service Pack 1) 64-bit

The error is related to whether the application is 32-bit or 64-bit. From the error messages, it appears to not be able to determine which one to install for.

Steps to Reproduce:

1. Install VSCode
2. Run Code.exe

This is the error when setup is finished:
![image](https://cloud.githubusercontent.com/assets/5733194/17710490/132a5406-63b3-11e6-94db-6baf0d4252bd.png)

This is the error when program is run:
![image](https://cloud.githubusercontent.com/assets/5733194/17710531/41b9c7fc-63b3-11e6-9d4f-62e791a235be.png)

**Comment by joaomoreno** [comment]
Does it happen with the archive too? https://code.visualstudio.com/Docs/?dv=winzip

**Comment by grayspace** [comment]
No, it does not happen with the archive version. Just the .exe install. Thanks!

**Comment by joaomoreno** [comment]
And it happens if you reinstall it? Or redownload it?

**Comment by grayspace** [comment]
Yes, redownloading and reinstalling the exe causes the same error for me. I also tried uninstalling, rebooting, and then reinstalling, with the same result.

**Comment by joaomoreno** [comment]
Any interesting Anti Virus software somewhere?

**Comment by grayspace** [comment]
Yes, both Microsoft System Center Endpoint Protection and McAfee Endpoint.

**Comment by joaomoreno** [comment]
Can you try reinstalling while disabling them?

**Comment by grayspace** [comment]
Unfortunately no. This is happening on my work machine and I don't have perms to do that.

**Comment by joaomoreno** [comment]
Does it work for any of your colleagues?

**Comment by grayspace** [comment]
I'll have to get back with you on that.

**Comment by joaomoreno** [comment]
@grayspace Any updates?

**Comment by grayspace** [comment]
@joaomoreno No updates. Looks like I'm the only one using Code at the moment. Close if you wish.

**Comment by joaomoreno** [comment]
It could be your antivirus software blocking the launch of the executable. I have to suggest using the zip archive. 👍  Thanks for the update.

**Comment by mattflix** [comment]
This is happening to me today immediately after allowing version 1.7.1 upgrade itself to 1.7.2.

After the upgrade, launching code.exe would only display a message box with:

```
Unable to execute file:
C:\Program Files (x86)\Microsoft VS Code\Code.exe
CreateProcess failed; code 216.
This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

Re-installing the same or even a previous versions does not help.  I tried 1.7.1 and 1.6.1.

I also tried system restore to get me back to pre-update, but this did not completely work.  I was left with a code.exe that would launch, but the window contained nothing other than a menu bar.  No editor windows.  Most commands would do nothing.

Maybe the archive build will work for me?  But, where do I get it?  I can only find .exe installers.

**Comment by mattflix** [comment]
Hmm...  the culprit seems to the Windows Firewall.  (Btw, I am running Windows 10.)

My experience:

1. Starting with non-working VSC 1.7.2 (code.exe gives "CreateProcess failed; code 216").
2. I uninstalled VSC.
3. I disabled the Windows Firewall.
4. I re-installed VSC.
5. Newly-installed VSC launches fine.
6. I re-enabled the Windows Firewall.
7. VSC still launches fine.
8. I uninstalled VSC.
9. I re-installed VSC  (from exactly the same installer .exe used in Step 4).
10. Newly-installed VSC does not work (code.exe gives "CreateProcess failed; code 216").

(I was also able to repeat Steps 1-5 to get back to a working VSC.)

So...  the firewall (when enabled) seems to affect VSC installation in some way that leaves code.exe unable to run.

Maybe the VS Code team and the Windows Firewall team need to have a chat?

**Comment by grayspace** [comment]
My issue turned out to be anti-virus related. There was another program that would not install/run correctly, so IT disabled anti-virus for me, and I was able to reinstall and run it and Code with no issues. SentinelOne was the AV causing an issue.

**Comment by mattflix** [comment]
Same thing (CreateProcess error 126) happening to me again with the 1.9 update.

This time, disabling the Windows firewall did not help, but I also have SentinelOne like @grayspace (which IT won't disable for me).

I found another workaround:
1) Run the installer as usual (so you can choose options, desktop icon, PATH, etc.).
2) Afterward, copy over the entire contents of the same-version .zip installer to wherever the installer placed the files.
3) Then, launching works fine.

This apparently fixes something about one of the files the installer copied (who knows, maybe just Code.exe is affected -- but I copied everything over).

I wish you guys would fix whatever SentinelOne doesn't like about your install...  Either by getting the SentinelOne folks to stop detecting VS Code as a virus (or whatever) or learn what it is that makes it think so and avoid doing it.
