### ISSUE TITLE
File Quick Pick shows duplicate entries

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#105905]
- VSCode Version: 1.49.0 Insiders
- OS Version: Windows 10

I somehow got into a state where there are duplicate file entries in the file Quick Pick (Ctrl+P).

![image](https://user-images.githubusercontent.com/12818376/91929464-4b8b7600-ec93-11ea-9ed9-8b2e3d42176b.png)

Repros with extensions disabled and after a restart.

**Comment by bpasero** [comment]
@gregvanl the only way this can happen is if you opened the workspace folder with different casing. Since on Windows and macOS you can open the same folder with different case to get the same files, the history may show duplicate entries. Could that have happened?

**Comment by gregvanl** [comment]
Here's another piece of the puzzle:

One file has a breadcrumb that shows a relative path:

![image](https://user-images.githubusercontent.com/12818376/92002221-7823aa00-ecf4-11ea-9f83-e7561bf1e96a.png)

while the other is showing an absolute path:

![image](https://user-images.githubusercontent.com/12818376/92002352-a1dcd100-ecf4-11ea-9ffa-3fe8860ecbeb.png)

**Comment by gregvanl** [comment]
Hmm, now I have three entries:

![image](https://user-images.githubusercontent.com/12818376/92002686-f8e2a600-ecf4-11ea-9146-50d8275ee013.png)

**Comment by bpasero** [comment]
@gregvanl at this point it would be best if you gave me steps to reproduce this locally. Can you record your steps from a `code --user-data-dir <empty dir>` session to ensure the state is fresh and see how to get there?

**Comment by gregvanl** [comment]
This issue doesn't reproduce with a new user-data-dir. I'll play around to see if I can get a repro but it may take some time. 
Is there anything you'd like to look at in my default AppData\Roaming files? Or something I could check in Local Storage or elsewhere?

**Comment by bpasero** [comment]
@gregvanl yeah you could run this from the command palette: "log storage contents" and try to find the list of files in the workspace storage. It would probably reveal the exact path of all the entries and show the diff.
