### ISSUE TITLE
Hitting a breakpoint doesn't active window

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105913]
* attach to extension host
* use vscode-dev
* hit a breakpoint
* 🤷 be confused because VS Code doesn't "active" itself to let you know that you are paused on a breakpoint

**Comment by jrieken** [comment]
related https://github.com/microsoft/vscode/issues/100368

**Comment by isidorn** [comment]
This should just work, by calling `hostService.focus` [here](https://github.com/microsoft/vscode/blob/5dc43b2bd39f27d8861e47b1169887376e6df26c/src/vs/workbench/contrib/debug/browser/debugSession.ts#L816)
Unless you have it disabled via 	
```
"debug.focusWindowOnBreak": false
```

I just tried it out and this works for me. What are you doing differently than me?
Here are my steps

1. `scripts/code.sh`
2. VS Code inisders, launch `Attach to Extension Host` config
3. Put a breakpoint [here](https://github.com/microsoft/vscode/blob/5dc43b2bd39f27d8861e47b1169887376e6df26c/src/vs/workbench/api/common/extHostDebugService.ts#L297) in VS Code insiders and minimize the window. This is on the EH side.
4. In `scripts/code.sh` start debugging
5. Notice how the brekapoint gets hit and VS Code insiders gets revealed and focused

![recording](https://user-images.githubusercontent.com/1926584/91967823-0bb8a300-ed14-11ea-87b0-3eb25bdb6922.gif)

**Comment by jrieken** [comment]
I don't minimize, the window is simply in the background, go into debug mode (status bar change) but doesn't activate

[rec.40.mov.zip](https://github.com/microsoft/vscode/files/5161570/rec.40.mov.zip)

**Comment by isidorn** [comment]
Aha, yes now I get the same. That seems to be the issue with the `hostService.focus` on mac.
Let's aslo assign to @bpasero and @deepak1556 since this is controled by Electron
Gist from above: `hostService.focus` does not bring window to front. If window is minimized then it works fine.

**Comment by bpasero** [comment]
Say hello to https://github.com/microsoft/vscode/issues/102997

**Comment by isidorn** [comment]
Thanks Ben!

**Comment by ArturoDent** [comment]
On W10 hitting a breakpoint doesn't switch focus back to vscode.  It does the **first time** that breakpoint is hit, but never thereafter.  Chrome debugger, vscode insider, W10.0.20206 - dev channel/fast ring.

![breakpoint](https://user-images.githubusercontent.com/31813701/92180199-b6f45580-ee03-11ea-95d4-03fe37364491.gif)




Version: 1.49.0-insider (user setup)
Commit: e2f63c9013a2b55db2d593d45b8c8aecdbe70f25
Date: 2020-09-03T17:27:16.893Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20206

**Comment by isidorn** [comment]
@bpasero can you double check this on Windows? I can also..

**Comment by bpasero** [comment]
@isidorn at least from the Electron side of things this change should only impact macOS, no other platforms. And my change is also only having an effect on macOS, not Windows.

But it is possible that Windows has a similar protection that it does not allow a background app to come to the foreground, I suggest you try it out with VSCode stable vs insiders to check.

**Comment by isidorn** [comment]
It works just fine both with Stable and with latest insiders.

@ArturoDent are you sure you do not have some special setting set, like for example `"debug.focusWindowOnBreak": false`

1. VS Code insiders, clone smoketest express sample from [here](https://github.com/microsoft/vscode-smoketest-express)
2. Open express repo in VS Code insiders, npm install from terminal
3. Put a breakpoint in routes.ts line 6
4. Open the browser, put VS Code insiders in breakpoint
5. visit localhost:3000 - breakpoint nicely hit and the VS Code window gets nicely activated

I can repeate step 5 any number of times I want and VS Code window gets activated every time (it blinks in the windows status bar)
