### ISSUE TITLE
Don't show recommendation on every window, every reload

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#105914]
From @kieferrm 

The `exe` recommendation is show for every window, every reload, ...  In the example below, I could tolerate that the Python recommendation is shown to be, but that the docker recommendation comes up again and again is hard to swallow. I have given no indication whatsoever that I'm interested in docker or work with docker right now. 

We should show the recommendation only occasionally or at most once per VS Code restart but not per window, not per window reload.

![L0mBKPGc1J](https://user-images.githubusercontent.com/4674940/91907855-72c85000-ec5f-11ea-8fb5-1d75934727ec.gif)

**Comment by sandy081** [comment]
Showing exe based recommendations in every window is not new - we did this for WSL (@aeschli FYI).

@aeschli May I know if it works for you, if this changed once per VS Code restart?

**Comment by aeschli** [comment]
I agree that showing it for every window does not make sense. (I was not aware of it)
