### ISSUE TITLE
Feature request: Event onWillSaveTextDocument()

### ISSUE THREAD

**Issue by Agetorp** [Microsoft/vscode#1059]
As proposed by @jrieken  in my earlier issue, #967, it would be nice if an even listener could listen to an event like this, to enable format on save and the possibility to run other commands before the save is actually done.

**Comment by jrieken** [comment]
depends on #239

**Comment by jrieken** [comment]
Actually, treating as duplicate. Once we have the event internally, we will expose on it on the api
