### ISSUE TITLE
VSCode Gray Out When HDR is enablled

### ISSUE THREAD

**Issue by jasonbergh** [microsoft/vscode#105996]
Issue Type: <b>Bug</b>

VSCode presents all gray and washed out when Display Settings -> Windows HD Color -> Use HDR is set to On. This makes the entire VSCode app look like it is unavailable and waiting on some background task when in reality HDR has washed out the colors of the app. This goes away the minute Use HDR is set to Off.

This is in Windows 10 Pro (2004), Monitor is a Samsung C49RG9x which is a 49" HDR capable monitor.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 2950X 16-Core Processor  (32 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.90GB (103.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.44.5

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by itsAnuga** [comment]
Nice monitor choice, I have the same :)

This has been a known bug since earlie 2019: 
https://github.com/microsoft/vscode/issues/68069

I've had the issue since then.
