### ISSUE TITLE
[Debug] Failure returned for configurationDone is not displayed in UI

### ISSUE THREAD

**Issue by edumunoz** [Microsoft/vscode#10596]
- VSCode Version: all
- OS Version: all

Steps to Reproduce:

1. Create a debug adapter that sets the `supportsConfigurationDoneRequest` flag to true in initialize.
2. Have the `configurationDone` handler return a failure with an error message.

Expected:
VSCode ends the debug session (by sending a `disconnect` request) and displays the error message.

Actual:
VSCode swallows the failure and the (failed) debug session continues.

@isidorn @weinand @jacdavis

**Comment by weinand** [comment]
@isidorn yes, since a configuration failure is typically fatal the expected behaviour is to end the debug session.
