### ISSUE TITLE
Line breaks in logpoints

### ISSUE THREAD

**Issue by alexeyr** [microsoft/vscode#105953]
In a logpoint, I expected `\n` to insert a line break. At least in Python it doesn't. Based on #88158, it should be language-independent, but currently may not be.

**Comment by weinand** [comment]
No, the logpoint message text is used literally and '\n' has no special meaning. Only exception are expressions in curly brackets. They are evaluated by the underlying debugger/runtime.

So if you want to output a newline, you can place it between curly brackets, e.g. like `hello{'\n'}world`
