### ISSUE TITLE
Breakpoint group.

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/vscode#105927]
User could split breakpoints to some groups, so user could enable/disable them quickly. 
There should have a default group so the breakpoints not belong to any group find their positions.(You can think current vscode 
 only have the default group.)

This would be very helpful when debug a complex feature.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by lukasgolino** [comment]
This feels like a must have feature. The breakpoint window becomes useless when you are debugging something complex.

**Comment by merrazquin** [comment]
Now that this feature has been added to Visual Studio, is there any chance we'll be seeing it in VSCode?

**Comment by ShuiRuTian** [comment]
Hi, @merrazquin . I guess the answer is still no, at least for now.

There is a same new issue recently https://github.com/microsoft/vscode/issues/177635, and the team just closed it.

The team suggest to implement such feature in extension in [this issue](https://github.com/microsoft/vscode/issues/164569).

But it's also not possible(please correct me if it's wrong!), because the TreeItem2(which has checkbox) is still in [proposal API](https://code.visualstudio.com/api/advanced-topics/using-proposed-api)

**Comment by dimateos** [comment]
Damn I really liked the idea, at least grouped by file like suggested in https://github.com/microsoft/vscode/issues/116594. 

I dont know if the UI is possible right now with the API, but so far there are not many extensions for breakpoints either.
* There is [Breakpoint Bookmarks](https://marketplace.visualstudio.com/items?itemName=OmarDulaimi.breakpoint-bookmarks) to export/import breakpoints to a file (a bit buggy tho).
* Also [Branch Breakpoint](https://marketplace.visualstudio.com/items?itemName=armanio123.branch-breakpoints) to have breakpoints per git branch (did not try it).
