### ISSUE TITLE
Clicking on Download Packages shows command not found

### ISSUE THREAD

**Issue by bw-space** [microsoft/vscode#105929]
Issue Type: <b>Bug</b>

install a package from extensions, then click on the downloading packages on the status bar.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|/Volumes/NO NAME/Unity Games/Jigsaw Trolley -g /Volumes/NO NAME/Unity Games/Jigsaw Trolley/Assets/Scenes/sphereRoll.cs:1:0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.13.2
flutter|Dar|3.13.2
lex-flex-yacc-bison|fau|0.0.3
code-runner|for|0.11.0
chapel|fru|0.0.1
vscode-opencl|gal|0.6.6
gc-excelviewer|Gra|3.0.40
plantuml|jeb|2.13.13
8051|jun|0.1.0
vscode-sshfs|Kel|1.18.3
csharp|ms-|1.23.1
python|ms-|2020.8.105045
cmake-tools|ms-|1.4.1
cpptools|ms-|0.30.0-insiders3
material-icon-theme|PKi|4.2.0
java|red|0.65.0
csspreview|san|1.0.4
vscode-hexdump|sle|1.7.2
unity-tools|Tob|1.2.3
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.12.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.1
vscode-maven|vsc|0.24.1

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
May I know what packages you mean? Can you please provide a screenshot?

**Comment by bw-space** [comment]
![image](https://user-images.githubusercontent.com/43056530/92115781-967ec800-ee10-11ea-839f-71d71c2a4029.png)
This is the error

**Comment by sandy081** [comment]
Seems coming from C# extension. Please file issue against that extension.
