### ISSUE TITLE
Debouncing seems too short

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#105977]
Testing #105185

It seems to me that the debouncing is too short. When I arrow up and down through the history I see something like "conso" followed by "console" rather than just "console". I tried that several times and I think my typing speed is OK, i.e. there is no perceived time gap between any of the characters.

**Comment by isidorn** [comment]
Agree. I have increased the delay from 200ms to 400ms both for Debug Console and the Problems view.
fyi @sandy081

**Comment by connor4312** [comment]
Verified the debounce is better.

But I think a nicer heuristic might just be to save a history item when either focus is lost, or the input contents are cleared.

**Comment by isidorn** [comment]
@connor4312 good idea, we can try to tackle that in the future also for the problems and the debug console filter.
