### ISSUE TITLE
Notebook diff: sometimes opens in json diff view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#105923]
Testing #105770

1. Open the my-work.github-issues file
2. Make some changes to it, open it in the changes view
3. Click on it again in the change view. Now it gets opened in plain json editor view.

So only the first time I click on it do I see the rich view.

**Comment by sana-ajani** [comment]
Is this expected behavior? First time I click on the file in the scm view, it opens up the rich diff view. Second time I click on it, the json diff view is opened. If I click on the "Go back" arrow in any of the two diff views, a plain json editor view of the file is opened.

**Comment by rebornix** [comment]
It's arguable if the current behavior is good, my feeling is it will lead to confusion at this moment.

**Comment by isidorn** [comment]
Works nice now, thanks for fixing

**Comment by rebornix** [comment]
This original bug was verified by @isidorn and we don't have any further changes.
