### ISSUE TITLE
Code cell vs markdown cell

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#105933]
On the API we don't make a strong (typed) difference between code cell and markdown cell - we only have the `CellKind`-hint. That makes some things a little cumber some, e.g

* Implementors of `executeAllCell` need to make sure they [don't execute a markdown cell](https://github.com/microsoft/vscode-github-issue-notebooks/blob/edf85a2e9db0d28166526c844e479724434209b6/src/extension/notebookProvider.ts#L295). Should we have `notebook#codeCells` or `notebook#getCell(filter: CellKind)`?
* One can assign output to a markdown cell which I believe isn't wanted
* We always allow to change the language of a code cell to markdown, which at least for GH notebooks is unwanted

So, I wonder if notebooks should draw a more crisp line between code cells and markdown cells so that they are harder to confuse and more restricted in what you can do with them.

**Comment by DonJayamanne** [comment]
> One can assign output to a markdown cell which I believe isn't wanted

I personally find this useful. In a non-jupyter scenario, one could use notebooks to create a q/a style document with list of answers that can be selected (questions in the markdown) and reach answer is an output.
I understand this isn't something in Jupiter, however I find it useful

**Comment by jrieken** [comment]
@DonJayamanne Wouldn't it than be a code cell with language markdown?

**Comment by DonJayamanne** [comment]
> language markdown?

Silly me yes.

**Comment by jrieken** [comment]
An idea from @mjbvz is to rename the `Markdown` cell kind to `Markup` and allow different rendered markup cells, e.g a markup cell could be html instead of md and always be rendered

**Comment by jrieken** [comment]
fyi @colombod

**Comment by colombod** [comment]
> An idea from @mjbvz is to rename the `Markdown` cell kind to `Markup` and allow different rendered markup cells, e.g a markup cell could be html instead of md and always be rendered

This would be killer and allow for much more compact notebook. @DonJayamanne how would such cell roundtrip in ipynb with the jupyter ecosystem?

**Comment by jrieken** [comment]
The enum is now called `NotebookCellKind.Markup` and with that the language property makes sense. Output is still questionable but I think that we can live with that.

I now wonder if we should combine the `notebookOutputRenderer` and `notebookMarkupRenderers` extension points. Today they are very similar and instead of having two there could be a property to distinguish them, like `kind: markup | output` @mjbvz Ideas?

**Comment by jrieken** [comment]
Closing
