### ISSUE TITLE
Notebook: Split cell button doesn't work while editing Markdown cell 

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#105901]
Testing #105769

Open a Markdown cell for editing and the split cell button appears in the tool bar. 

Trying to split the cell doesn't do anything.

![image](https://user-images.githubusercontent.com/12818376/91926129-678b1980-ec8b-11ea-8fee-a95fd6b5596f.png)

**Comment by rebornix** [comment]
@gregvanl do you focus into the cell editor? It seems there is no selection/cursor in the editor and then it won't split.

**Comment by gregvanl** [comment]
Yes, the cursor is within the editor and the blue outline indicates that the cell editor has focus.

**Comment by rebornix** [comment]
@gregvanl sorry for asking again, can you still reproduce this issue in Insiders? I'm not able to reproduce.

**Comment by gregvanl** [comment]
@rebornix The split cell button has no effect if the cursor is as the start or end of the cell. It will split if the cursor is placed somewhere within the Markdown text.
By default, when you start editing a cell, the cursor is in front of the first character so Split Cell appears to do nothing.
Maybe close as "by design"? Or should the Split Cell button be disabled unless the command can actually split the Markdown text?

**Comment by rebornix** [comment]
Good point, we should do at least one of your suggestions.
