### ISSUE TITLE
Recommendation is too aggressive on first run

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#105915]
From @kieferrm 

I started up with a clean user data dir and clean extensions dir. When I start VS Code I get immediately the docker extension recommendation. As this is the first run experience, this feels much too aggressive. Also, we tell the user that we don't only send telemetry, we also tell them we already inspected their local system.

I think we should take our time and prompt on the 2nd or 3rd day of usage.

![image](https://user-images.githubusercontent.com/4674940/91907038-fda84b00-ec5d-11ea-8fb6-0b3c4ff61645.png)

**Comment by sandy081** [comment]
@aeschli FYI

This is exe based recommendations which is also used for WSL. I remember @aeschli did some experiments to show this after some time (3s).

**Comment by misolori** [comment]
+1 that this recommendation should come after subsequent usage. We previously had the "You don't have git installed" toast that we deferred until you opened a git workspace to reduce the visual noise on first run. Is there a reason why only showing this when a user opens a project w/ a container is not sufficient?

**Comment by sandy081** [comment]
> Is there a reason why only showing this when a user opens a project w/ a container is not sufficient?

Reason being WSL extension recommendation when WSL is installed does not need any workspace opened.

**Comment by sandy081** [comment]
Recommendation also includes Docker extension which is not related to workspace right?

**Comment by misolori** [comment]
Correct. My suggestion is to not show this since we already show a notification when a workspace has a container file.

**Comment by sandy081** [comment]
I see, Container file recommendation does not include Docker extension
