### ISSUE TITLE
Noticable flicker 2 seconds after opening notebook diff

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#105924]
Refs 105770

1. Open the my-work.github-issues file
2. Make some changes to it, open it in the changes view
3. Notice that the whole notebook diff view flickers 1-2 seconds after it was opened

**Comment by rebornix** [comment]
Verifier: 

* Open a github issue notebook, modify it
* Open the diff view from SCM view
* Close it
* Open again, make sure you don't see any blinking after the views are rendereded.

**Comment by isidorn** [comment]
Works great now. However in that commit you have commited a `console.log`. Maybe you want to remove that?

**Comment by rebornix** [comment]
@isidorn yup thanks! got it removed.
