### ISSUE TITLE
Troubleshoot Terminal launch failures  (code: 259)

### ISSUE THREAD

**Issue by TeachBoy1** [microsoft/vscode#105993]

**Comment by TeachBoy1** [comment]
The terminal process "C:\Windows\system32\cmd.exe" terminated with exit code: 259.

**Comment by gjsjohnmurray** [comment]
Please post version info from Help/About

**Comment by Tyriar** [comment]
This means your shell exited with that code. Please follow this guide before creating an issue https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch and be sure to include the information is asks for.
