### ISSUE TITLE
Smoke Test: Notebooks fail altogether in Windows

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#105928]
Testing #105750

Everything fails in the Notebooks Windows smoke test suite, and it subsequently fails a lot of other unrelated tests afterwards:

```
      Notebooks
** Timeout!
        1) inserts/edits code cell
** Timeout!
Did not pass accept function
        2) inserts/edits markdown cell
** Timeout!
Did not pass accept function
        3) moves focus as it inserts/deletes a cell
        - moves focus in and out of output
** Timeout!
Did not pass accept function
        4) cell action execution
```

Here's a screenshot when the first failure happened.

![image](https://user-images.githubusercontent.com/22350/91963693-7ff04800-ed0e-11ea-84d8-70cc160e8b6c.png)

Error is:

```
Command 'Create New Notebook' resulted in an error (command 'vscode-notebook-tests.createNewNotebook' not found)
```

**Comment by roblourens** [comment]
It works for me on mac and windows. The error makes it sound like the smoketest extension (just some extension under ./extensions) is missing. Can you just make sure you are all built fully?

**Comment by roblourens** [comment]
Or we don't really have to debug it, I think it's fine. They are working in CI.

**Comment by joaomoreno** [comment]
> It works for me on mac and windows. The error makes it sound like the smoketest extension (just some extension under ./extensions) is missing. Can you just make sure you are all built fully?

This was against an actual build, not against sources. Are we reaching outside of the `test/smoke` folder?

**Comment by roblourens** [comment]
How are you running the smoketests? We do copy the extension out of the extensions dir into the smoketest extensions dir, the same way it works for `'vscode-test-resolver'`.

**Comment by joaomoreno** [comment]
> We do copy the extension out of the extensions dir into the smoketest extensions dir, the same way it works for `'vscode-test-resolver'`.

Oh I did not know this. That explains it.

It used to be possible to do `yarn --cwd test/smoke && yarn smoketest --build BUILD` to run the smoketests on a clean repo. It seems this is not possible any more.

**Comment by roblourens** [comment]
Is it ok to close this and just say that the extensions must be built for smoketest to run, or is this an important scenario?

For example extensions that support smoketest could live in the smoketest directory and get built along with smoketest.
