### ISSUE TITLE
activeTerminal undefined when there is a terminal

### ISSUE THREAD

**Issue by andycraig** [microsoft/vscode#105944]
Should `vscode.window.activeTerminal` ever be `undefined` when there is one or more terminals?

I contribute to an [R extension](https://github.com/Ikuyadeu/vscode-R/), and a user has reported an error message that the extension only raises in a codepath like this: 

```typescript
if (window.terminals.length > 0) {
    if (window.activeTerminal !== undefined) {
        // Happy path
    } else {
        // Error message
    }
}
```

I'm trying to work out if this is an expected situation that we (the extension authors) need to be handling better, or if it means there's possibly a bug associated with `vscode.window.activeTerminal`.

The [VS Code API documentation](https://code.visualstudio.com/api/references/vscode-api) says this about `activeTerminal`: 'The currently active terminal or `undefined`. The active terminal is the one that currently has focus or most recently had focus.' After reading this I'm still a bit unclear when it would be `undefined`. (Maybe if it's created without being focussed?)

Steps to Reproduce:

The user has reported that they only rarely see the error message, and I have not been able to reproduce it.

Here the user describes a time they encountered the error: https://github.com/Ikuyadeu/vscode-R/issues/385#issuecomment-675359065

Does this issue occur when all extensions are disabled?: No, but it's a possible bug with the VS Code API that is only evident when using an extension.

Thank you.

**Comment by Tyriar** [comment]
If there is one terminal but it has never been visible, activeTerminal is meant to be undefined. Is this what you're hitting?

**Comment by andycraig** [comment]
Hi @Tyriar, thank you for the quick response. That helps a lot. I'd say that's almost certainly what we're encountering. We'll update the extension to handle that situation.

Not a VS Code bug, so I'll close. Thanks again!

**Comment by bersbersbers** [comment]
Hello there,
this is the user who reported https://github.com/Ikuyadeu/vscode-R/issues/385. I am currently able to reproduce the bug ("Error identifying terminal") while the terminal *is* visible, as you can see from this GIF:

![AV2Oqh4biT](https://user-images.githubusercontent.com/12128514/92119869-a5598080-edf8-11ea-8e75-7871c498b42d.gif)

In fact, I have used this terminal before and it has run code from the same extension successfully before (although I cannot say for sure that the terminal became visible when I ran the code, but it usually does). What I am doing in the GIF is pressing F5 to try running the R code, which is what I have done before to run code a few minutes ago.

Scrolling up and down the terminal (using the mouse wheel, without activating the terminal) did not fix the issue. Clicking into the list of termins did not fix it, either. What did fix it was to click into the terminal, thereby activating it.

**Comment by Tyriar** [comment]
https://github.com/Ikuyadeu/vscode-R/blob/67ea4de10d4c4220af307894662a15d0454a7279/src/rTerminal.ts#L82-L95

@andycraig fwiw `window.terminals.length === 1` could happen at the same time `activeTerminal` is `undefined`, this should check `windows.terminals.length > 0`, no?

**Comment by andycraig** [comment]
@Tyriar Thank you for having a look at the code. That section is inside a `windows.terminals.length > 0` condition. The `=== 1` is there to deal with an old VS Code ‘first terminal’ bug (maybe #53104?). Creating a terminal when there wasn’t already one would show it, but `activeTerminal` was always `undefined`. That code is specifically checking for that situation. If `activeTerminal` is `undefined` but `windows.terminals.length` is not  1, I set it to raise an error because I didn’t think that situation should ever occur. I now know that this could occur if there were multiple terminals but none of them had never been visible.

That said, in the GIF from @bersbersbers (thank you for recording it!) it does look like `activeTerminal` is `undefined` even though a terminal is visible. It also looks like it is reaching a part of the code that should only be reached when the number of terminals is not 1, while the GIF shows only one terminal. I am really confused as to how this is happening.

I think that old VS Code ‘first terminal’ bug is resolved now and the workaround is no longer necessary, so my plan is to delete that whole section and rearrange some other code so that it’s a lot more robust to `activeTerminal` being `undefined` and how many terminals there are.
