### ISSUE TITLE
can't open vs code from wsl2 terminal

### ISSUE THREAD

**Issue by Ryder05** [microsoft/vscode#105940]
Issue Type: <b>Bug</b>

when i run this command 'code .' 
i get this msg ==> 
To use Visual Studio Code with the Windows Subsystem for Linux, please install Visual Studio Code in Windows and uninstall the Linux version in WSL. You can then use the `code` command in a WSL terminal just as you would in a normal command prompt.
Do you want to continue anyway? [y/N] y
To no longer see this prompt, start Visual Studio Code with the environment variable DONT_PROMPT_WSL_INSTALL defined.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz (4 x 2593)|
|Memory (System)|6.14GB (5.20GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
auto-close-tag|for|0.5.8
remote-wsl|ms-|0.44.5
debugger-for-chrome|msj|4.12.10
material-icon-theme|PKi|4.2.0
highlight-matching-tag|vin|0.9.9
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
The message tells you the problem already; uninstall vscode inside wsl, and install it in windows.

**Comment by Ryder05** [comment]
Do you think i am unable to read the message ? thank you for nothing !

**Comment by Tyriar** [comment]
What's the output of `which code`?
