### ISSUE TITLE
Allow comparing three way git changes with base commit

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#105937]
Suppose you wrote some code in `master`

```
func IsPrime(n int) bool {
  if n < 0 { n = -n }
  switch {
  case n == 2:
    return true
  case n < 2 || n % 2 == 0:
    return false
 
  default:
    for i = 2; i*i <= n; i += 2 {
      if n % i == 0 { return false }
    }
  }
  return true
}
```

Now you modify it in your branch, perhaps you fix the indentation by converting it from spaces to tabs (the best way to indent code):

```
func IsPrime(n int) bool {
	if n < 0 { n = -n }
	switch {
	case n == 2:
		return true
	case n < 2 || n % 2 == 0:
		return false
 
	default:
		for i = 2; i*i <= n; i += 2 {
			if n % i == 0 { return false }
		}
	}
	return true
}
```

Meanwhile someone else changes `master` in some unobvious way:

```
func IsPrime(n int) bool {
  if n < 0 { n = -n }
  switch {
  case n == 2:
    return true
  case n < 2 || n % 2 == 0:
    return false
 
  default:
    for i = 3; i*i <= n; i += 2 {
      if n % i == 0 { return false }
    }
  }
  return true
}
```

If you try to rebase this, by default VSCode's conflict view will give you something like this:

![image](https://user-images.githubusercontent.com/376842/91980501-45db7200-ed1f-11ea-92b8-ba2bcb3cf52b.png)

You can improve it a bit by setting Git's `merge.conflictstyle` option to `diff3`:

![image](https://user-images.githubusercontent.com/376842/91980532-52f86100-ed1f-11ea-9e13-42e346e45b2d.png)

However this still doesn't adequately answer the question I obviously want to ask at this point:

> What did someone else change that meant I have a conflict? In other words, if I want to use my version, what changes do I need to integrate into it?

This example is small enough that you can visually scan and find the answer:

> They changed a 2 to a 3, so I need to do that in my code too.

But it sucks that you have to find the differences manually. For longer diffs this is almost impossible, especially if you move or remove large blocks of code. To put it in visual terms:

![image](https://user-images.githubusercontent.com/376842/91981530-e716f800-ed20-11ea-916e-5c68d296f66a.png)

I think a nice solution would be to change "Compare changes" to "Compare with incoming", and add another link "Compare with parent" (or "Compare with base"?). These would allow you to diff the current change against the base commit, and also clarify what the existing "Compare changes" link does because it isn't obvious, especially if you have `diff3` enabled.

**Comment by joaomoreno** [comment]
#5770
