### ISSUE TITLE
Shortcut conflict of Alt+R

### ISSUE THREAD

**Issue by champignoom** [microsoft/vscode#105960]
- VSCode Version: 1.48.0
- OS Version: Manjaro 20.1

Steps to Reproduce:

1. Open a text file, press Alt+R, expecting the "Run" menu to expand
2. Regex matching for text search is toggled, although not searching or replacing anything

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@rebornix this is linux, so the native menus. if they aren't greedily taking the keybind, we will have to scope down when the command applies.

just to confirm @champignoom , other mnemonics are working, such as Alt+F file menu

**Comment by champignoom** [comment]
@sbatten Yes, alt+[FESVGTH] all work.

**Comment by sbatten** [comment]
@rebornix this means it is up to command registration to scope appropriately, the when clause should probably include find widget focus

**Comment by rebornix** [comment]
@sbatten actually we set the when clause to `editorFocus` intentionally as the find options will affect ctrl+d. This is more or less a keybinding conflict. Users can workaround this issue by changing the keybinding's when expression to `editorFocus && findInputFocussed`
