### ISSUE TITLE
"Cannot read property 'textBuffer' of undefined" when changing cell content 

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#105958]
Testing #105770

Open a notebook file, change the repo in the query, open the diff view and seeing an error "Cannot read property 'textBuffer' of undefined" and cannot open diff view. Tried running the cell before opening the diff view and I still see same error.

![recording (8)](https://user-images.githubusercontent.com/9721254/92015217-7373eb80-ed1e-11ea-964a-f77de9af994a.gif)

**Comment by rebornix** [comment]
Are you seeing this issue with all GitHub notebooks files you have locally? I'm not able to reproduce this issue.

**Comment by sana-ajani** [comment]
Using this notebooks file: https://github.com/sana-ajani/notebooks/blob/master/foo.github-issues

**Comment by rebornix** [comment]
I'm not able to reproduce with this file, let's see if you can still reproduce with tomorrow's Insiders.
