### ISSUE TITLE
本来用记事本都是可以打开正常查看的，结果用vscode 打开就变成乱码了？

### ISSUE THREAD

**Issue by yz1309** [Microsoft/vscode#10599]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

**Comment by rebornix** [comment]
*Translate* The file can be opened correctly in Notepad but in VS Code the content is incorrectly encoded.

**Comment by bpasero** [comment]
You can change the encoding in settings.

**Comment by yz1309** [comment]
那为什么不能做到自动转码呢？
