### ISSUE TITLE
getExtension api behave differently when tests is invoked by using script

### ISSUE THREAD

**Issue by ShenChen-Amazon** [microsoft/vscode#105902]
Issue Type: <b>Bug</b>

Here is the codebase for our extension: https://github.com/alexa/ask-toolkit-for-vscode.

I am trying to set up some tests for our extension. And there are two tests available under test/extension.test.ts. When I invoke the tests through debug tab and execute the task extension tests: https://github.com/alexa/ask-toolkit-for-vscode/blob/master/.vscode/launch.json#L20, those two tests could pass successfully. However, if I invoke the runTest script: https://github.com/alexa/ask-toolkit-for-vscode/blob/master/test/runTest.ts, both two tests failed because the getExtension api returns undefined. 

I am not sure what's the differences by using the two test methods. Did i miss setup something in the script ?

Thanks,
Shen

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:09:41.484Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 6|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.5.0
vscode-codemetrics|kis|1.24.0
vscode-github|Kni|0.30.3
vscode-docker|ms-|1.5.0
vscode-typescript-tslint-plugin|ms-|1.2.3
code-spell-checker|str|1.9.0
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by alexdima** [comment]
@ShenChen-Amazon Here is what I have tried:
* `npm install -g yo code-generator`
* I did a fresh TypeScript extension using `yo code` (this is to eliminate any other changes that might have been done in the repository)
* I used the name `webtest` and the publisher name `alex`.
* I have edited `src/test/suite/extension.test.ts` and added:
```ts
		const ext = vscode.extensions.getExtension('alex.webtest');
		if (ext) {
			console.log(JSON.stringify(ext.packageJSON));
		} else {
			console.log(`no extension`);
		}
```

When I run `npm run test`, I see the package json being printed in the console.

**Comment by ShenChen-Amazon** [comment]
Hi @alexdima ,

Thanks for your help. I finally figure out the issue is caused by the wrong extensionDevelopmentPath. My folder structure is slightly different with the samples. Resolving the issue.

Thanks,
Shen
