### ISSUE TITLE
Allow menu customization from settings

### ISSUE THREAD

**Issue by jeffr-spire** [microsoft/vscode#105974]
Allowing customization (for example, change the order of items to have the most common at the top rather than in a submenu), of menus through settings would enable a simple and very useful customization without requiring a user to create an extension for the purpose.

Inspired by this [recent change](https://code.visualstudio.com/updates/v1_48#_git-overflow-menu-cleanup) --  previously, the most common actions in my workflow - `push` and `pull` - were directly in the menu, but they have been moved to a cascading submenu, making them harder to get to.   Meanwhile, `clone` which you only ever run once on a repository is front and center.

**Comment by joaomoreno** [comment]
Push and pull are now front and center again.

There's another feature request open for user customization of menus.
