### ISSUE TITLE
XHR failed

### ISSUE THREAD

**Issue by Khaya56** [microsoft/vscode#105954]
![Screenshot (99)](https://user-images.githubusercontent.com/36347158/92006921-9b2a7a00-ed45-11ea-919d-45deb37ec1a1.png)

Issue Type: <b>Performance Issue</b>

Every time I try to download an extension on the marketplace , I get XHR failed

**Comment by sandy081** [comment]
Can you please let us know if there are any errors in 

- Help -> Toggle Developer Tools -> Network
- Also share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by Khaya56** [comment]
![Screenshot (100)](https://user-images.githubusercontent.com/36347158/92025175-717e4c80-ed5f-11ea-8ac8-2c10c29a8089.png)

**Comment by sandy081** [comment]
Seems proxy issues

**Comment by chrmarti** [comment]
@Khaya56  Could you start VS Code with --log-net-log=netlog.json, retry searching for extensions and then post the created netlog.json here?

**Comment by Khaya56** [comment]
> @Khaya56 Could you start VS Code with --log-net-log=netlog.json, retry searching for extensions and then post the created netlog.json here?

@chrmarti Thank you, I tried but it is still showing the same error

**Comment by chrmarti** [comment]
@Khaya56 Could you post the created netlog.json here?

**Comment by pmarella2** [comment]
Having the same issue on Windows. I did the following so far:
1. Completely uninstalled and reinstalled
2. Changed DNS
None of them worked. VS Code extensions viewing/installing work fine on both my Macbooks and the DNS settings are the same as on my Windows machine.

I am not sure what else to do to figure out why this is happening.
![VSCodeXHR](https://user-images.githubusercontent.com/9484118/92301837-8a9d1e00-ef56-11ea-8392-6e8e4c87ac8c.PNG)

**Comment by chrmarti** [comment]
Could you start VS Code with --log-net-log=netlog.json, retry searching for extensions and then post the created netlog.json here?

**Comment by pmarella2** [comment]
Here is the netlog file. Attempted to lookup some extensions and tried to install one extension.|

[netlog.zip](https://github.com/microsoft/vscode/files/5195693/netlog.zip)

**Comment by pmarella2** [comment]
@chrmarti

**Comment by chrmarti** [comment]
@pmarella2 Are you using a VPN client or some local firewall? Can you turn these off and retry?
