### ISSUE TITLE
Perform http calls and websocket from the client to a process after the extension host

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#105982]
In .NET Interactive notebooks fronted and use code si allowed to consume js apis that are able to

- request static content from the .NET Interactive process
- read variables from different kernels
- use signalR client to perform commands and listen to events

As each notebook tab will have its own .NET Interactive host it will need to be able to tunnel requests from the notebook webview all the way to the .NET Interactive http server.

This is a .NET Interactive feature working on local networks but that is not possible at the moment in scenarios where the extension host and / or the .NET Interactive process are not on the same machine or the ports in use are not publicly visible.

I  would be interesting to be able to configure / compute a valid forwarding address that the webview can use to traverse the network into the extension host and from there into the .NET Interactive process.

**Comment by colombod** [comment]
@jrieken, @rebornix, @alexr00, @brettfo @jonsequitur
I have changed our architecture to use the api ```asExternalUri``` and then using the property ```preloads``` on the Notebook class.

This works while I debug the extension. if I load a vsix (locally built or from marketplace) the uri looks very different and the webview devtools report errors

this is the uri I see while debugging ```http://localhost:53417/apitunnel/vscode/2d20a616f39343a096a66f28eb286ce1/bootstrapper.js```

but this is what I see loading the extension via vsix ```vscode-webview-resource://27b50667-cf17-4025-a082-5409e739fe73/http//localhost%3A53417/apitunnel/vscode/2d20a616f39343a096a66f28eb286ce1/bootstrapper.js```

this is the error i see reported in devtools. Same issue reproduces on windows and macos

![imgo](https://user-images.githubusercontent.com/375556/92480865-6606a780-f1dd-11ea-8b26-238f3d167c8e.jpg)

**Comment by jrieken** [comment]
> this is the uri I see while debugging http://localhost:53417/apitunnel/vscode/2d20a616f39343a096a66f28eb286ce1/bootstrapper.js

> but this is what I see loading the extension via vsix vscode-webview-resource://27b50667-cf17-4025-a082-5409e739fe73/http//localhost%3A53417/apitunnel/vscode/2d20a616f39343a096a66f28eb286ce1/bootstrapper.js

@connor4312 it looks like all preload urls get some special treatment to become 'vscode-webview-resource'-url. Is this a case where preload should not be used?

**Comment by connor4312** [comment]
Previously we only allowed localhost preloads while in development mode, this was built to enable using the webpack-dev-server. However with the pure renderer API this was no longer a concern, and this functionality was removed in https://github.com/microsoft/vscode/commit/24b712d7c201f74a6bd50742f1eb7602f699e640#diff-6510457264ab51e9d8b0af934351c92eL805-L810 (are you using recent VS Code Insiders?)

So right now we don't support loading any preloads from localhost or remote URIs by design.

**Comment by colombod** [comment]
> Previously we only allowed localhost preloads while in development mode, this was built to enable using the webpack-dev-server. However with the pure renderer API this was no longer a concern, and this functionality was removed in [24b712d#diff-6510457264ab51e9d8b0af934351c92eL805-L810](https://github.com/microsoft/vscode/commit/24b712d7c201f74a6bd50742f1eb7602f699e640#diff-6510457264ab51e9d8b0af934351c92eL805-L810) (are you using recent VS Code Insiders?)
> 
> So right now we don't support loading any preloads from localhost or remote URIs by design.

This would be a problem for us as our kernel supports loading additional component at runtime, specially js libraries. What would be the path forward?

**Comment by colombod** [comment]
@connor4312 , @rebornix if I have a js resource with the extension that gets loaded and it is able to intercept messages sent to the webview would it work? I could have the bootstrapper ready to go and just need to trigger the uri configuration and setup for the communication with backend

**Comment by connor4312** [comment]
We discussed this in our daily notebook sync.

There are a couple ways this can be solved. First -- what's the purpose of having the bootstrapper.js loaded from localhost rather than loaded from the filesystem/extension?

**Comment by colombod** [comment]
I followed that pattern and we then use post message api to finish the configuration. Thank you for the help

**Comment by connor4312** [comment]
Okay, gotcha. So you've got stuff working now using `postMessage` for communication?

**Comment by colombod** [comment]
I load the bootstrapper as static js and I finish setting up the api url using the post message api. I still need to load some js files at runtime from our extensions

**Comment by connor4312** [comment]
Ok, cool. You can use the tunnel API to expose localhost (if necessary -- on a remote) and load your supplemental scripts through there.

**Comment by colombod** [comment]
> Ok, cool. You can use the tunnel API to expose localhost (if necessary -- on a remote) and load your supplemental scripts through there.

Perfect, that is already in place, the only thing i spotted is that the uri i get after using the asExternalUri is kind of strange in code spaces and that is then blocked by the cors settings.

**Comment by connor4312** [comment]
What request are you making + what's the CORS issue you're seeing? (A captured HAR also works)
