### ISSUE TITLE
UX meeting agenda 17th August 2016

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#10591]
- Horizontal panel UX.
- Debug UX
  https://github.com/Microsoft/vscode/issues/10437
  https://github.com/Microsoft/vscode/issues/9740
  https://github.com/Microsoft/vscode/issues/1931

**Comment by bpasero** [comment]
@stevencl fyi Isidor is still on vacation.

**Comment by bgashler1** [comment]
#10546 Tabs for integrated terminal? (see my last comment in this issue)

**Comment by bgashler1** [comment]
@bpasero here are the icons.
[Simple Explorer Icons.zip](https://github.com/Microsoft/vscode/files/421516/Simple.Explorer.Icons.zip)

**Comment by bpasero** [comment]
Thanks!
