### ISSUE TITLE
Status bar toggle should switch between On, Smart, Off

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#105963]
Testing #105771

It would be nice if the status bar item to toggle auto-attach, would switch between On, Smart, Off
![image](https://user-images.githubusercontent.com/641685/92020791-b6d25800-ed26-11ea-9c75-097bfd1eda92.png)

**Comment by connor4312** [comment]
With https://github.com/microsoft/vscode-js-debug/issues/732#issuecomment-684979209 this will make more sense.
