### ISSUE TITLE
[Feature] allow using json file for theme tokenColors

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#105930]
currently we can only use `tmTheme` file as a template for the `tokenColors` config, however it would be much easier if we can also use a json file, so multi themes extension can extend the syntax definition without the need for a build tool.

**Comment by aeschli** [comment]
We support `tmTheme` files, but also have our own, JSON base, `*.color-theme.json` format. That format is recommended as it  allows to set workbench colors as well as semantic colors.

Sorry if I misunderstood your request.  Can you explain in more detail what you are doing?

**Comment by ctf0** [comment]
> Sorry if I misunderstood your request. Can you explain in more detail what you are doing?

sure, lets say u have 2 themes with different `colors` but with identical `tokenColors`.

according to the [docs](https://code.visualstudio.com/api/extension-guides/color-theme#create-a-new-color-theme) we can only use `tmTheme` file to extend from.

so i was asking if its possible to also allow `json` files to be included/extended as well.

**Comment by aeschli** [comment]
So it's a request for the yeoman generator to also accept JSON?

**Comment by ctf0** [comment]
mostly yes, or if possible is it possible to bypass the yeoman step and get the `vsce` command to do that on compiling time ?

**Comment by aeschli** [comment]
`vsce` ist the command for publishing

**Comment by aeschli** [comment]
No sure if that's helpful, the color-theme.json also support to include another theme definition.
https://github.com/microsoft/vscode/blob/f1d7f7f6ce3d0a343bf03bea198aeedefa6cfaf2/extensions/theme-defaults/themes/dark_plus.json#L4-L4

So you can have one theme file just defining the token colors and other file (with different `colors`) include that one,

**Comment by ctf0** [comment]
thank you so much, thats exactly what i was looking for, where do you find those information ?

thanx again. 🏆
