### ISSUE TITLE
Single File IntelliSense not working on new file

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#10597]
WORKING ON THE SPECIFIC STEPS HERE... CLOSE TO IDENTIFYING THE EXACT STEPS 

- VSCode Version: 1.5.0-Insider 11ffcfcf69608c07e7db4b4c77856854d5083497
(Also observed on Stable)

- OS Version: 10.11.1

Steps to Reproduce:

1. Open an empty directory
2. Create a new JavaScript file `test.js` through File -> New File (note this will not reproduce when clicking the new file icon). 
3. Write the following code. 

```
var x = {
    a: 1, 
    b: 2
}

x.
```

I expect to see IntelliSense. 

Instead I see. Loading does not resolve. 

![image](https://cloud.githubusercontent.com/assets/2449568/17720782/89bae5a6-63d9-11e6-8784-e25aab88a739.png)

4. Reload JavaScript Project, Reload Window, close and open the file, or restart VS Code. 

RIGHT NOW SOMETIMES IT WILL WORK IF YOU CLOSE AND OPEN THE FILE, SOMETIMES NOT. TRYING TO NARROW IT DOWN. 

```
➜  vscode-intellisense git:(master) ✗ tsc --version
Version 1.9.0-dev.20160130
```

I have repeated this twice and confirmed it with @ramya-rao-a. 

Possibly what I was seeing in this issue - https://github.com/Microsoft/vscode/issues/9913

**Comment by dbaeumer** [comment]
@waderyan what usually helps tracking this down is to enable TS message tracing.

**Comment by dbaeumer** [comment]
This works for me (I assumed you saved the file you created with New -> File; otherwise the file is of text mode). The TS trace I see is:
```json
Sending request: open (0). Response expected: no. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/10597/test.js",
    "fileContent": ""
}

Sending request: geterr (1). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "p:/mseng/VSCode/Playgrounds/bugs/10597/test.js"
    ]
}

Sending request: projectInfo (2). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/10597/test.js",
    "needFileNameList": true
}

Response received: projectInfo (2). Request took 71 ms. Success: true 
Result: {
    "fileNames": [
        "c:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/extensions/typescript/server/typescript/lib/lib.d.ts",
        "p:/mseng/VSCode/Playgrounds/bugs/10597/test.js"
    ]
}

Event received: syntaxDiag (0).
Data: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/10597/test.js",
    "diagnostics": []
}

Event received: semanticDiag (0).
Data: {
    "file": "p:/mseng/VSCode/Playgrounds/bugs/10597/test.js",
    "diagnostics": []
}
```
and code assist works. Do you have any special auto save settings?

**Comment by waderyan** [comment]
@dbaeumer thanks for your help with this. Unfortunately, its still not working for me. 

Here is everything I have in User Settings. I have nothing in Workspace Settings. 

```
{
  "typescript.tsserver.trace": "verbose"
}
```

I have no extensions installed. 

I am seeing nothing in the console (although I would expect I would see the TS trace - do I have the correct setting?)

![image](https://cloud.githubusercontent.com/assets/2449568/17777787/a01f2fee-6516-11e6-9078-bf078f4e91dc.png)

Here is the code repo I am working from. Neither `test.js` nor `test.ts` are working for me. 

https://github.com/waderyan/vscode-js-intellisense-samples

**Comment by dbaeumer** [comment]
@waderyan  I would day that the TSServer or even the TS/JS plugin didn't get activated. Do you have VS Code in source and does it reproduce there as well. If so we could debug it to see what is going on.

**Comment by waderyan** [comment]
I do have source but cannot reproduce (and I'm not seeing it in other workspaces). 

Is there a way to kick start the TSServer or TS / JS plugin? I was hoping Reload Window would do this or even restarting.

**Comment by dbaeumer** [comment]
@waderyan then we can only try to debug the production. You can start vscode with --debugBrkPluginHost 6004 (or another port). This will start the extension host in debug break mode. You can then attach a debugger to it (e.g. VS Code itself running another instance). Then set a breakpoint into `resources/app/extensions/typescript/out/typeScriptMain.js` from you installation and see if the TS plugin gets activated. If yes we need to debug further.

**Comment by waderyan** [comment]
Tracked in https://github.com/Microsoft/TypeScript/issues/10735

**Comment by zhengbli** [comment]
This looks like the issue https://github.com/Microsoft/TypeScript/issues/9610.
