### ISSUE TITLE
Drag and drop code is often identified as copied code

### ISSUE THREAD

**Issue by huye** [microsoft/vscode#105992]
Issue Type: <b>Feature Request</b>

Drag and drop without holding down the Ctrl key is often identified as copying content.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:04.923Z)
OS version: Linux x64 5.3.0-3-amd64

**Comment by weinand** [comment]
Please be more specific: drag and drop of what, where, and how?

**Comment by huye** [comment]
I select the text in the edit area, hold down and drag the mouse to another line, and then release the mouse. The correct action should be to move the text block, but occasionally the text in the old position does not disappear here. I guess there is a mistake in the judgment of the status of the Ctrl key. When something goes wrong, I need to press the Ctrl key and release it to restore normal.

**Comment by huye** [comment]
In short: when I was not holding down the Ctrl key, but appeared the behavior of the Ctrl key.

**Comment by rebornix** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/61867
