### ISSUE TITLE
Notebook diff: cell metadata change does not stand out

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#105916]
Testing #105770

1. Open the `my-work.github-issues` file
2. Unlock some cell
3. Notice how the file appears as modified in the Git changes view, however no change is shown

I would expect that my change to unlock / lock a cell is shown in the diff view.

**Comment by rebornix** [comment]
I didn't reproduce it, I'm wondering if it's because the metadata change indicator doesn't stand up

![image](https://user-images.githubusercontent.com/876920/92014571-4f0b1580-ed04-11ea-8888-b4030c65bb97.png)

**Comment by isidorn** [comment]
Yeah, the indicator did not stand out...
