### ISSUE TITLE
Signature Help shows only 2 lines of the method's comments

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#10593]
Signature Help shows only 2 lines of the method's comments. Auto-complete shows a single truncated line with ellipsis and an option to expand to see the whole text. Signature Help should also have a similar feature. This happens to all extensions that implement the `SignatureHelpProvider`

_From @ahmetalpbalkan on July 12, 2016 22:25_

if I type `ioutil.TempDir(` the tooltip that comes up is only showing 2 lines of the godoc:

![image](https://cloud.githubusercontent.com/assets/159209/16785796/e94825a2-4844-11e6-842c-f17e13161e31.png)

_Copied from original issue: Microsoft/vscode-go#391_

**Comment by joaomoreno** [comment]
I'll put it under #2330
