### ISSUE TITLE
Notebook diff: needs some UX love

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#105919]
Testing #105770

1. Make some change to the `my-work.github-issues` file
2. Open it in the SCM diff view:

What I do not like from this view is:
* Too horizontal vertical lines, reminds me of a real life note book
* Does not look like the original notebook view. Why can't we just render two notebook views side by side with the diffs outlined with some background
* No clear Vertical line that splites Left and Right side
* Looks very different compared to our regular Diff view

fyi @misolori

![Screenshot 2020-09-02 at 10 49 52](https://user-images.githubusercontent.com/1926584/91960308-0b1b0f00-ed0a-11ea-9499-47621e948908.png)

**Comment by rebornix** [comment]
> Too horizontal vertical lines, reminds me of a real life note book

I take that as a compliment ❤️

**Comment by rebornix** [comment]
> Does not look like the original notebook view. Why can't we just render two notebook views side by side with the diffs outlined with some background
> No clear Vertical line that splites Left and Right side

At the beginning the UX is similar to what you described I think (see https://github.com/microsoft/vscode/issues/99877#issuecomment-678857384)

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/876920/90993945-cf46b380-e56b-11ea-9322-7627f7624c0c.png">

We found that most of the time users don't care about metadata or outputs change and they attract too much attention in Jupyter Notebook.

However I agree that in current UX, it looks noisy when the document has many one liner.

**Comment by isidorn** [comment]
Maybe we could present this in one UX call in September? Seems like an interesting topic.

**Comment by misolori** [comment]
Yea we can definitely bring it up in the UX sync next week 👍

**Comment by rebornix** [comment]
We will show a couple of options and pros/cons behind them.

**Comment by tanhakabir** [comment]
There hasn't been any recent activity on this issue so I'll be closing it. Feel free to reopen if you think otherwise
