### ISSUE TITLE
Terminal selection does not appear after scrolling once

### ISSUE THREAD

**Issue by Ahmed-Nematallah** [microsoft/vscode#105979]
Issue Type: <b>Bug</b>

When selecting text in a terminal (CMD, PowerShell and Git Bash tested), then scrolling so the selected text isn't in the screen, and then scrolling once to view the selected text, the selection does not appear, it only appears after scrolling again with the text still on screen.

For example, if I select x on the screen and then scroll so that x is not on the screen and scroll once to make x visible, it does not appear selected, once I scroll again with x still visible, it will appear selected again.

Tested on Windows 10.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.26.0
code-gnu-global|aus|0.2.2
gitlens|eam|10.2.2
systemverilog|eir|0.10.10
file-icons|fil|1.0.25
tcl-language-support|go2|0.1.2
latex-workshop|Jam|8.11.1
hex-fmt|ker|1.0.0
vscode-docker|ms-|1.5.0
csharp|ms-|1.23.1
python|ms-|2020.8.105369
cpptools|ms-|0.30.0-insiders4
hexeditor|ms-|1.2.1
material-icon-theme|PKi|4.2.0
vscode-hexdump|sle|1.7.2
vscode-icons|vsc|10.2.0
p4|xi|0.0.3
material-theme|zhu|3.8.7

(6 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
I can't reproduce:

![recording (1)](https://user-images.githubusercontent.com/2193314/92184761-df318380-ee06-11ea-9836-bd2c49f108fa.gif)

**Comment by Ahmed-Nematallah** [comment]
Maybe this is a windows-only issue?

I can also reproduce it with multiple lines selected

![Media1](https://user-images.githubusercontent.com/19266669/92185207-8b00c080-ee53-11ea-8bf4-6c1a096f78d3.gif)

**Comment by Tyriar** [comment]
To verifier: This only happens when `"terminal.integrated.rendererType": "canvas"`
