### ISSUE TITLE
Notebook: Can't grab scroll bar unless status bar is visible

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#105903]
Testing #105769

Turn off the cell status bar.

For the  verification.github-issues Notebook, hover on the Config cell which has a long set of definitions. The scroll bar appears on hover but you can't grab it.

If you turn on the cell status bar, you can grab it.

**Comment by roblourens** [comment]
Just got this in https://github.com/microsoft/vscode/issues/105875
