### ISSUE TITLE
Extension recommendations should not be shown after I uninstalled an extension

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#105947]
1) I got an `exe` based recommendation
2) Install docker extension
3) Reload window -> no recommendation
4) Uninstall docker extension 
5) Reload window -> recommendation comes back

After uninstalling, there should be no recommendation. I gave it a try, I didn't like it. I shouldn't we forced to manually select `Don't show again`.

**Comment by sandy081** [comment]
Updated strategy:

- Recommendation will not be prompted again if user has acted upon (installed / opened) the recommendation.
