### ISSUE TITLE
Snippets question

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/vscode#105991]
How to disable snippets only once by adding some code in place 1, and show snippets in the other time
or at least let my completion results show on top, I tried set sortText to a very small value, but didn't work
![image](https://user-images.githubusercontent.com/15936231/92069548-366e2e80-eddc-11ea-8fcc-d2165e1589f3.png)

![image](https://user-images.githubusercontent.com/15936231/92069346-adef8e00-eddb-11ea-8855-fc0b4ca6213e.png)

**Comment by jrieken** [comment]
Please do not explain an issue with screen shots only. Use precise and easy to follow steps and optionally use screen captures to illustrate an issue

**Comment by CGQAQ** [comment]
> Please do not explain an issue with screen shots only. Use precise and easy to follow steps and optionally use screen captures to illustrate an issue

SO, I want to disable snippets when my `provideCompletionItems` have result, or at least let my result sit on top of completions, I tried set my CompletionItem.sortText to a very small value, but it didn't work

**Comment by jrieken** [comment]
I assume those are static snippets from your or another extension, right? This isn't possible as we don't allow a provider to suppress completions from another source. 

Just like filtering, sortText is only applied when not having a prefix and once a prefix exists the match quality defines sort order.

**Comment by CGQAQ** [comment]
> I assume those are static snippets from your or another extension, right? This isn't possible as we don't allow a provider to suppress completions from another source.
> 
> Just like filtering, sortText is only applied when not having a prefix and once a prefix exists the match quality defines sort order. E.g your completions would rank much higher when they select/replace a larger prefix, e.g the whole import string

Oh, I see, thank you
