### ISSUE TITLE
Uri to jump to a specific line in file

### ISSUE THREAD

**Issue by kantlove** [Microsoft/vscode#10598]
Hi, 
Currently I am writing an extension that will output a file path and line number to an OutputChannel. Something like this:

> From file: [c:\code.java]() Line 64

vscode turns the file path into a link leading to a file and that is nice. However, I wonder if there is a way to combine the "Line 64" part too. Something like:

> From file: [c:\code.java:line=64]()

Clicking this link will open the **code.java** file and move the cursor to the start of **line 64**.

**Comment by bpasero** [comment]
Thanks for reporting this issue. Please use the issue search next time to see if there is a duplicate already. In this case, the issue has already been reported.

**Comment by kantlove** [comment]
I did search around but could not find the issue. Could you give me information on that issue?
Thank you.

**Comment by kantlove** [comment]
Ok, found it #586
