### ISSUE TITLE
Make language tokens and scopes part of command list

### ISSUE THREAD

**Issue by AzuStar** [microsoft/vscode#105949]
_Nothing remotely similar has been found, when searching for similar feature requests._

Why?
----
Feature would enable developers and even users with macros to have better code control.

How does it work?
----
Normally, language analyzer identifies tokens and scopes from the typed text. From there the analyzer still understands and expects certain tokens in the future. For example, statement would expect to see terminal `punctuation.terminator.statement`
Example terminal for TS
![image](https://user-images.githubusercontent.com/52426335/91825692-801c1500-ec34-11ea-9f75-41ee37e7096f.png)
Example terminal for C
![image](https://user-images.githubusercontent.com/52426335/91827327-94f9a800-ec36-11ea-87a5-ee96bdf8426b.png)
Example terminal in Java
![image](https://user-images.githubusercontent.com/52426335/91827408-b65a9400-ec36-11ea-9855-ff11024674aa.png)
You get the picture - it's pretty much identical across languages.
Adding language token as commands that can be executed would be amazing.
Below are examples of use, that would be really helpful.

Examples
----
Excuseuar my partially poor recordings
Before:
![Before_1](https://user-images.githubusercontent.com/52426335/92154570-e6b05700-ee1d-11ea-9464-356c86820714.gif)

After:
![After_1](https://user-images.githubusercontent.com/52426335/92154650-09427000-ee1e-11ea-963e-041608b68008.gif)

This is just a mockup of example use.

**Comment by weinand** [comment]
@AzuStar the animated gifs are not readable:

<img width="553" alt="2020-09-02_23-10-13" src="https://user-images.githubusercontent.com/1898161/92037048-764bfc00-ed71-11ea-8263-e2f79484a443.png">

Please don't use private links in comments - Instead just drag and drop the gifs into the comment (in edit mode). Github will store them...

**Comment by AzuStar** [comment]
Compressed Gif size so github can load itю

**Comment by EPonyA** [comment]
It took me a few minutes to fully understand this feature request, but now that I get it, I am very excited by the idea!
