### ISSUE TITLE
VMW Workstation: VS Code hits 97% CPU and won't start for a couple of minutes

### ISSUE THREAD

**Issue by bobwoodard** [Microsoft/vscode#106]
I'm in VMW Workstation 11.1.3 with a 8GB/single core/Win764bit and when I start code.exe from the start menu, it jumps to 97% of cpu and will take a couple of minutes to start.  I'm not opening any folders with code or doing anything with the commandline, this is a plain vanilla start from the menu.  I also noticed that I can sometimes speed up the starti[ by starting 4 or 6 instances (each click from the start menu seems to start 2 instances in the taskmanager, but not the desktop) and then the ide will kick in, but I'm left with all the instances until I shut down the ide and then all instances close.

I've seen this same behavior on VMs I've created at work and at home (not the same VM on two different computers).

**Comment by bobwoodard** [comment]
As a follow-up, using the same VM specs, but installed Win10-64bit and VS code pops right up with no problem.

**Comment by bpasero** [comment]
We have heard issues before like this that running Code inside a VM is not behaving nicely. We have to investigate.

**Comment by mwootendev** [comment]
I'm having the same issue. VS Code running in a VirtualBox Windows VM takes several minutes to start.

**Comment by bpasero** [comment]
Can you check how Atom behaves please and report back. Thanks!

**Comment by bobwoodard** [comment]
Ok, I see somewhat similar behavior in starting the editor from Atom.  The differences are that atom spins up 4 processes (vs 2 for code) and while it's delayed in starting, it doesn't use 97% of CPU (the highest cpu utilization is 37%) and it starts up in less than 15 or secs and exit/relaunching atom is almost instantaneous, vs code which goes though the whole delay as if from scratch.

**Comment by bpasero** [comment]
@bobwoodard any chance you could use a process explorer that is able to identify the process within vs code that consumes so many resources? preferable that would be the arguments passed to the process (it helps identifying what the process does).

**Comment by bpasero** [comment]
Also can you try running "code.exe --disable-gpu" from a command prompt from the installation folder of code to see if it makes any difference?

**Comment by bobwoodard** [comment]
From the command line, time to load has improved.  

 

When the editor appears, the drawing of the interface is notable, compared to normal.  

 

Another difference is that instead of two code.exe tasks, there is just one (until it loads and then there are 4).

**Comment by bpasero** [comment]
Yes, running with this command will disable the process for GPU acceleration. So you say the user interface is now drawing slower but the startup time is normal?

**Comment by bobwoodard** [comment]
Startup time is still slow, just quicker than without it.

 

When it comes up, it’s hard to describe, but rather than just snapping into place on the screen, it seems like I see the outside border and the inside parts start to appear.  It happens quickly, just not all at once.

**Comment by bpasero** [comment]
This is likely #335

**Comment by bpasero** [comment]
To people hitting this issue: We might not be able to release a new version until next week. **But there is a workaround**: 

If you can start Code eventually:
* select File | Open Recent | Clear Items
* restart and things should be fast again

If you cannot start Code:
* close Code
* locate storage.json (see https://code.visualstudio.com/Docs/supporting/FAQ#_how-do-i-opt-out-of-vs-code-autoupdates for how to find it)
* delete the file or rename it
* start Code

Sorry for the trouble :heart:
