### ISSUE TITLE
Running a python script when Code is installed causes the script to open in Code.

### ISSUE THREAD

**Issue by JRosanowski** [microsoft/vscode#106015]
I can't run python scripts from the command line specifying just the script name. Code is hijacking it and opening the file.
If I uninstall Code I can again run without an issue. Is there an option to disable this?

**Comment by weinand** [comment]
Please provide detailed steps so that we can try to reproduce.

**Comment by JRosanowski** [comment]
Ok, maybe my fault. It was due to this registry entry but I'm not sure how I ended up with it. Deleting it and reinstalling Code, I don't have a problem.

Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\VSCode.py]
@="Python Source File"
"AppUserModelID"="Microsoft.VisualStudioCode"

[HKEY_CLASSES_ROOT\VSCode.py\DefaultIcon]
@="C:\\Program Files\\Microsoft VS Code\\resources\\app\\resources\\win32\\python.ico"

[HKEY_CLASSES_ROOT\VSCode.py\shell]

[HKEY_CLASSES_ROOT\VSCode.py\shell\open]

[HKEY_CLASSES_ROOT\VSCode.py\shell\open\command]
@="\"C:\\Program Files\\Microsoft VS Code\\Code.exe\" \"%1\""
