### ISSUE TITLE
keyboard shortcut 

### ISSUE THREAD

**Issue by hyahm** [microsoft/vscode#106084]
- VSCode Version:   1.48.2
- OS Version:  window10 and fedora32

Steps to Reproduce:
can not set ctrl+alt + left  | right | up | down

**Comment by weinand** [comment]
please provide reproducible steps

**Comment by hyahm** [comment]
manager -> keyboard Shortcuts
click any line
press ctrl+alt + left,  only show ctrl+alt

**Comment by weinand** [comment]
Sorry, I still do not understand.
What do you mean by "manager"?

**Comment by hyahm** [comment]
![image](https://user-images.githubusercontent.com/22030094/92294274-51b47780-ef5d-11ea-9f9d-5e840b408df5.png)
![image](https://user-images.githubusercontent.com/22030094/92294281-63961a80-ef5d-11ea-8fb2-3dba369579ba.png)
![image](https://user-images.githubusercontent.com/22030094/92294286-6db81900-ef5d-11ea-855c-cc26fa4f3f6d.png)

**Comment by alexdima** [comment]
@hyahm This is indicative that some software or the OS itself is consuming those keybindings and that is why they do not reach our application. On Windows, in the past, I have seen some graphics drivers that would rotate the screen when using that keybinding. Please check that other applications can receive the keybinding.

**Comment by hyahm** [comment]
My system is an integrated video card. I'm sure it's not a problem with the binding key of the video card. I press Ctrl + Alt + left | right and nothing happens
Another computer, the same system, vscode version: 1.48.0, can be set up
