### ISSUE TITLE
Two clicks requires to dismiss dialog

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#106014]
* safari, web playground
* get the auth message to show, e.g don't be logged in and author GH issue notebook
* dialog appears
* :bug: it needs two clicks to 'cancel'

[Screen Recording 2020-09-03 at 09.23.23.mov.zip](https://github.com/microsoft/vscode/files/5166880/Screen.Recording.2020-09-03.at.09.23.23.mov.zip)

**Comment by sbatten** [comment]
That looks like 2 dialogs, not 2 clicks on the same dialog. Notice the shadow brightening after the first click. I think the auth service should not be sending multiple dialogs.

**Comment by RMacfarlane** [comment]
Can repro with a test extension that makes multiple getSession requests in parallel:
```
export async function activate(context: vscode.ExtensionContext) {
	context.subscriptions.push(vscode.commands.registerCommand('extension.login', async _ => {
		Promise.all([getPassword(), getPassword()]).then(_ => {
			vscode.window.showInformationMessage('Done');
		})
	}));

	async function getPassword() {
		const session = await vscode.authentication.getSession('github', ['repo'], { createIfNone: true });	
		vscode.window.showInformationMessage(`Signed in as ${session.account.label}!`);
	}
}
```

Repros on desktop and web
