### ISSUE TITLE
Can't open SCM change if file is already open

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#106042]
1. Open a file
2. Make a change, save it
3. Go to SCM view and click the changed file row

🐛 File does not open

**Comment by bpasero** [comment]
@rebornix could this be related to notebooks and your diff editor work? I see that this code is on the path possibly changing the way the command works?

![image](https://user-images.githubusercontent.com/900690/92123207-a7254300-edfc-11ea-96db-f7294ed93222.png)

**Comment by rebornix** [comment]
I reverted my previous change and will fix that issue next iteration. It's dangerous to modify the override without knowing its intention/source (like, if users want to open the same diff editor again by clicking scm entry once more, or they want to open it in text diff). It sounds like the same debt we had with editor view type. Will see how to improve this in an elegant way.

**Comment by rebornix** [comment]
Fixed via e2f63c9013a2b55db2d593d45b8c8aecdbe70f25

**Comment by joaomoreno** [comment]
Thanks @rebornix!
