### ISSUE TITLE
typescript format code broken

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/vscode#10604]
- VSCode Version: 1.5.0.insider latest
- OS Version: OSX  El Capitan

With the latest vscode insider, the format code is broken for typescript files.
If i use the official build it works correctly.
The second screenshot shows how classes are indented (variables are put on the same line).
<img width="1039" alt="screen shot 2016-08-17 at 08 57 14" src="https://cloud.githubusercontent.com/assets/655344/17727366/1bbf6bb4-6459-11e6-89ce-94a9dcc56779.png">
<img width="1039" alt="screen shot 2016-08-17 at 08 57 55" src="https://cloud.githubusercontent.com/assets/655344/17727367/1bc39c98-6459-11e6-89d2-f9531c0befd5.png">

**Comment by alexandrudima** [comment]
fyi @dbaeumer

**Comment by waderyan** [comment]
@farfromrefug thank you for opening an issue. 

Let's see if we can narrow down the issue. I've created this simple example, but cannot reproduce the behavior you have described. 

```
class Dog {

    constructor(name) {
        this.name = name;
    }

    bark() {
        console.log('bark');
    }

    name: 'Fido'
}
```

1. I selected the entire class. 
2. Right clicked to Format Code

I expected to see `name: 'Foo'` end up on the same line as the closing brace of `bark`. 

Can you look at my example and build off of it to recreate your bug? This will help us in identifying the bug you are seeing.

**Comment by farfromrefug** [comment]
@waderyan 
Yes it works fine with your code. The issue is when you declare a variable an object like this:
```
class Dog {
  constructor(name) { this.name = name; }

  bark() { console.log('bark'); }

  name = {}
  name2 = 'Fido'
}
```
Also i remember now that cast ```<>``` causes issues too like this:
```

class Dog {
  constructor(name) { this.name = name; }

  bark() { console.log('bark'); }

  name : Array<number>
  name2 = 'Fido'
}
```
name2 ends up on name's line 

and also same things with imports without the ```;``` they end up on the same line

**Comment by waderyan** [comment]
@farfromrefug I'm not seeing this on my end. 

My setup. 
1. I created a file `test.ts`
2. I copied the code you provided. 
3. I right clicked and chose Format Code. 

Are those the exact steps you have done? 

![format_ts_issue](https://cloud.githubusercontent.com/assets/2449568/17777507/a4c1fe38-6515-11e6-97e7-66b7c67a9151.gif)

**Comment by farfromrefug** [comment]
@waderyan yes they are.
I even tried it in a new window to be sure.
What i have not done though is without any extension (can they change the behavior?)
Is there a way to disable my extensions without having to remove them all?
<img width="596" alt="screen shot 2016-08-18 at 16 38 21" src="https://cloud.githubusercontent.com/assets/655344/17777839/3df605b2-6562-11e6-9828-1b607b65245e.png">
<img width="592" alt="screen shot 2016-08-18 at 16 38 29" src="https://cloud.githubusercontent.com/assets/655344/17777838/3df3ed72-6562-11e6-8f56-d6293e039ec3.png">


Also here is my config file
```
// Place your settings in this file to overwrite the default settings
{
    // Configure glob patterns for excluding files and folders.
    "files.exclude": {
        "**/.metadata": true,
        "**/.bzrmeta": true,
        "**/.bzr": true,
        "**/.git": true,
        "**/.vscode": true,
        "**/tags": true,
        "**/.tags*": true,
        "**/.zip": true,
        "**/.DS_Store": true,
        "build": true
    },
    "search.exclude": {
        "**/git": true,
        "dist": true,
        "**/node_modules": true,
        "build": true
    },
    "editor.folding": false,
    "editor.wrappingColumn": 130,
    "editor.wrappingIndent": "indent",
    "editor.renderWhitespace": true,
    "explorer.autoReveal": false,
    "telemetry.enableTelemetry": false,
    "beautify.CSSfiles": [
        "css",
        "rjss"
    ],
    "beautify.JSfiles": [
        "ts"
    ],
    "color-highlight.languages": [
        "rjss",
        "ts",
        "typescript"
    ],
    "eslint.enable": false,
    "clang-format.executable": "/usr/local/bin/clang-format",
    "git.enabled": true,
    "color-highlight.markerType": "background"
}
```

**Comment by waderyan** [comment]
Ok. Yes let's try those two things as I don't have extensions or settings. 

Start code from the command line with `--disable-extensions`

```
code-insiders --disable-extensions <file-name>
```

Remove all your settings (I'd copy them to a temp file) except add

```
{
  "typescript.tsserver.trace": "verbose"
}
```

Look in the console and send a picture of it. There may be an error from the tsserver. 

If this works, then we'll be able to isolate on an extension or a setting. If it doesn't work I'll open an issue with TypeScript. `

**Comment by farfromrefug** [comment]
@waderyan i found the guilty one!
It's actually not a vscode issue but a clang-format issue!
I am sorry i did not see it before :s I did not even think an extension could override format code.
Plus i didn't think clang-format was actually formatting typescript ...

And after a little search, putting ```clang-format.language.typescript.enable``` to ```false``` even fixed it with the extension still installed
Thanks

**Comment by waderyan** [comment]
Great. Glad to see you were able to resolve it.
