### ISSUE TITLE
Command clicking on a function/var shouldn't open another tab if it's already open.

### ISSUE THREAD

**Issue by fabtjar** [microsoft/vscode#106065]
If I had 2 tabs splits on my screen (classA and classB) and command click a function/var in classA (that's would link to classB) it opens it again instead of just going to the already open tab on classB.
It works like that on PyCharm.

**Comment by gjsjohnmurray** [comment]
@fabtjar Initially are classA and classB open in two separate editor groups?

**Comment by gjsjohnmurray** [comment]
If yes, try setting `"workbench.editor.revealIfOpen": true`

**Comment by fabtjar** [comment]
> @fabtjar Initially are classA and classB open in two separate editor groups?

Yes. If the tabs are both in the same editor group it works how I expect. When they are in separate groups it's opening another tab up in the group I command clicked in.

**Comment by fabtjar** [comment]
> If yes, try setting `"workbench.editor.revealIfOpen": true`

This works how I want it to. Vscode seems to have a setting for all my needs!
