### ISSUE TITLE
VSCode cannot show whitespace correctly

### ISSUE THREAD

**Issue by zhoudotnet** [Microsoft/vscode#10603]
- VSCode Version: 1.4.0
- OS Version:Windows7

I have changed the setting to diplay whitespace, but VSCode cannot show it correctly.
Attached my setting as below:
{
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "editor.fontSize": 13,
    "editor.insertSpaces": false,
    "editor.renderWhitespace": true,
    "editor.renderControlCharacters": true
}

Steps to Reproduce:
1. Create a new file: click 'File' -> 'New File'
2. Copy this text "  test  space  "into new file, VSCode cannot show whitespace correctly.

**Comment by alexandrudima** [comment]
@zhoudotnet Do you mean the non-leading, non-trailing spaces?

![image](https://cloud.githubusercontent.com/assets/5047891/17734164/cffa7666-647a-11e6-8a38-87706845ed7f.png)

**Comment by zhoudotnet** [comment]
Yes, the non-leading, non-trailing spaces don't render. How can it implement it?

**Comment by alexandrudima** [comment]
Let's track in #3828

**Comment by zhoudotnet** [comment]
Hi Alexandrudima,
When this function can be implemented?
