### ISSUE TITLE
Not install JAVA tools and language install suppot.

### ISSUE THREAD

**Issue by imhasib062** [microsoft/vscode#106064]
![Screenshot from 2020-09-04 00-12-06](https://user-images.githubusercontent.com/50325055/92152206-1bcfa000-ee44-11ea-9db6-c6c35a51b74f.png)
 I've tried for 3 days after a few for a long day but it shows up installing. I've kept it up for 4 hours or more times but there is no change in there. Suddenly shows up Corrupt ZIP as you can see in the screenshot. And also it keeps up for Python, PHP too. To fix it first :)

I'm trying to install JAVA from this sequence: 
![Screenshot from 2020-09-04 00-31-18](https://user-images.githubusercontent.com/50325055/92153401-0a879300-ee46-11ea-996b-33288848ebc7.png)

By the way, I'm on a Linux machine and it's UBUNTU 20.04 LTS.

And my information is:
![Screenshot from 2020-09-04 00-28-19](https://user-images.githubusercontent.com/50325055/92153172-a6fd6580-ee45-11ea-971a-2b9c3a380a0e.png)
Auto info. added not applied so unexpectedly giving manual. :(

**Comment by sandy081** [comment]
Can you please provide the steps you followed to reproduce this?

**Comment by imhasib062** [comment]
> Can you please provide the steps you followed to reproduce this?

I've done it even I can do it manually and manual integration solves my problem. Sorry for bothering you.
