### ISSUE TITLE
Behavior of default value in the setting panel is confusing

### ISSUE THREAD

**Issue by AokabiC** [microsoft/vscode#106092]
When I change the user setting like `"files.autoSave": "afterDelay"`, Workspace tab in the setting panel is shown below:
![コメント 2020-09-04 154047](https://user-images.githubusercontent.com/25875917/92207896-08b0e480-eec5-11ea-9572-b54343e04a70.png)

I think that's a little confusing because these values shown in Workspace tab is VSCode default value, not the applied setting actually. 

This problem is more severe when you override a setting in Workspace tab.
If I intended to set the setting value default only in this workspace (e.g. set "Files: Auto Save -> off" in Workspace tab, while "Files: Auto Save -> afterDelay" in User settings), it seems like these setting is overridden by the workspace, by the looks of the setting panel (shown above). 

To actually override the configuration as intended, you need to open `settings.json` in `.vscode/` and write the following: `"files.autoSave": "off"`. 

In my opinion, this is very unkind behavior even if it says "modified in: User". To improve this, I suggest that:
- display actual setting. like "Files: Auto Save -> afterDelay (inherited from User)"
- be able to overridden by the default value

**Comment by roblourens** [comment]
Good points, and this is discussed more in https://github.com/microsoft/vscode/issues/58038
