### ISSUE TITLE
[WebviewView] Changing Title When `webviewView.visible === false`

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/vscode#106083]
Testing #105764

When the WebviewView is not visible, changing the title is not reflected visually:
```
        this._webviewView.onDidChangeVisibility(e => {
            this._webviewView.title = this._webviewView.visible ? "All Good!": "Never Displayed";
        });
```

**Comment by mjbvz** [comment]
Doesn't reproduce for me:

![Sep-08-2020 15-01-20](https://user-images.githubusercontent.com/12821956/92531994-34450f00-f1e4-11ea-8d01-a711fc8f70b6.gif)


Can you please share your full example?

**Comment by GordonSmith** [comment]
I should have mentioned that his is when its in a bottom "Panel" and not a side tree.

**Comment by mjbvz** [comment]
@sbatten I believe the issue in `CompositePart` here:

https://github.com/microsoft/vscode/blob/12fc18ba86ae8197f8ad538e2ba280512514649d/src/vs/workbench/browser/parts/compositePart.ts#L288

If an extension updates the title when switching away from a view—or updates the title of a non-active view—then the if condition fails so we never call `this.updateTitle`.

Could we move the `updateTitle` call outside of the conditional?

**Comment by sbatten** [comment]
reverted 2ac15236ea0940c34a3367ea4d63de09596ffc32, will fix with a separate implementation of update title like panelPart has
