### ISSUE TITLE
visual isnt working

### ISSUE THREAD

**Issue by alexim36** [microsoft/vscode#106030]
Issue Type: <b>Feature Request</b>

visual code is  not working  with the new windows 10 update due to a software error

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19042

**Comment by IllusionMH** [comment]
/needsMoreInfo

What error does it show?

**Comment by alexim36** [comment]
thats the thing it doesnt show it just says that this app cant run on your pc

**Comment by IllusionMH** [comment]
Are there any errors if you run in crom CMD with `--verbose` flag? like `code --verbose`
