### ISSUE TITLE
asp.net core with vc code

### ISSUE THREAD

**Issue by chopetra** [Microsoft/vscode#10602]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

make asp.net core basic dir file with console 
dotnet new -t web 

and vs code f5 or ctrl+f5 then display result site
but this is wrong result

in cmd dotnet run that makes good result

vs code developer plz answer me
why ?

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
Moved to OmniSharp/omnisharp-vscode#668
