### ISSUE TITLE
All golang types to be highlighted the same

### ISSUE THREAD

**Issue by jawadcode** [microsoft/vscode#106055]
Custom types/structs are syntax highlighted in white whereas the primitive/built-in types are highlighted in the usual turquoise-ish green, I believe that it would make more sense for all types to be the same (turquoise-ish green) colour

P.S. I was thinking of posting this issue in bug reports but I am unsure if it is a bug or intentional
P.P.S I am using the default Dark + theme

**Comment by aeschli** [comment]
Can you add a small code sample?
