### ISSUE TITLE
Notebook: support line numbers and actions to toggle it

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#106054]
We may want to support users to customize their line numbers and allow them to toggle line numbers with shortcuts.

**Comment by claudiaregio** [comment]
Question: 

Would it look like this? (Numbering per cell) 
Cell 1: 1 2 3 
Cell 2: 1 2 3 

![image](https://user-images.githubusercontent.com/19276747/92640358-074f3580-f292-11ea-8793-42a5eed78be5.png)

Or like this? (Numbering for all code regardless of cell) 
Cell 1: 1 2 3 
Cell 2: 4 5 6
![image](https://user-images.githubusercontent.com/19276747/92640460-29e14e80-f292-11ea-965a-8bd2598b7a90.png)

Would there be a way for users to pick which way they'd like to see it or is there a strong lean towards one version?

**Comment by DonJayamanne** [comment]
I'd prefer we as extension authors could provide defaults as well.
If running the second cell & there are errors in the cell, then Jupyter returns line numbers in the error message, however the line numbers start from 1 for the cell that was executed.

I.e. in the case of Jupyter, we don't need line numbers in subsequent cells to continue from previous cells (at least not for our Python extension).

**Comment by joyceerhl** [comment]
https://github.com/microsoft/vscode-jupyter/issues/4810 is a related request to display the line and column number ticker in the status bar.

**Comment by rebornix** [comment]
In Jupyter, users can press `L` to toggle the line numbers for active cell, or `Shift+L` to toggle line numbers for all cells (and this config is also persisted).

**Comment by claudiaregio** [comment]
@rebornix is this supposed to work today? Does Jupyter need to do anything to enable it? I tried this out in my notebook and it doesnt work :(

**Comment by Syndorik** [comment]
@claudiaregio as far as VScode insider is concerned, I don't think it works. I can't activate/deactivate the line number per  celll either

**Comment by rebornix** [comment]
We didn't have this yet. The note above is for me to capture what Jupyter does now.

**Comment by claudiaregio** [comment]
@rebornix ah ok this makes much more sense now, thanks

**Comment by rebornix** [comment]
Fixed via 804c1fc594d8f19787c884faa3cf58496b136446 .
