### ISSUE TITLE
Download procedure when on remote ssh

### ISSUE THREAD

**Issue by hodjaev** [microsoft/vscode#106047]
Hello,
I'd like vscode to inform me about the completion of the download folder procedure when I am on remote ssh.

```
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

![image](https://user-images.githubusercontent.com/69766846/92131126-40108a00-ee0e-11ea-8403-b43d78d9a36c.png)

**Comment by isidorn** [comment]
Dup of "Progress on long running file system operation" feature request
