### ISSUE TITLE
Command categories are repeated in many places

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#106019]
Search for `"Developer"`, which is used to define the category for commands. There are 19 results of this category being repeated in different files.

IMHO it would make sense to consolidate these categories in a central place such that we don't duplicate this all the time, or have a typo, etc.

**Comment by bpasero** [comment]
Added and adopted:

https://github.com/microsoft/vscode/blob/f3454533fb3403f1668897e5799a71be3a260a8a/src/vs/workbench/common/actions.ts#L128-L132
