### ISSUE TITLE
Extension API: Allow to have hidden unsaved documents

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#106026]
# Context

If you open a text document with

```ts
const doc = await workspace.openTextDocument(uri);
```

It is hidden - no editor will be spawned.
However, as soon as an edit is applied to it, a visible editor is spawned by VS Code:

```ts
const edit = new WorkspaceEdit();
edit.insert(uri, new Position(0, 0), "Some content");
await workspace.applyEdit(edit);
```

# Request

It would be really useful if an extension could open a text document in a way that API edits don't open a visible editor!

```ts
// This crashes if vscode already did open that document in non-hidden context.
const doc = await workspace.openTextDocument(uri, { hidden: true });
```

# Reason

If that was possible, generic language embedding could be implemented by extensions.
Lets say we have a markdown document like this:
````
Demo:

```typescript
import { baz } from "foo";
baz({ someParam: 10 });
```
````
An extension could create a document for the code block and save it to a temporary folder.
The extension could keep the document in sync by projecting changes to the code block to the document.
Since VS Code already exposes an API to query for autocompletion, the extension could project many language-service features available in the virtual document back to the markdown document.

Currently, changes cannot really be projected to documents without VS Code spawning an editor for them. This would be a very annoying user experience.
Writing directly to the file system and waiting for VS Code to reload the document is too slow for meaningful language service projection.

# Problems

1) If the extension does not dispose the hidden document, it would allocate resources forever.
2) It is unclear what happens if the user opens the very same document. Maybe it should then turn into a normal document, but the lifetime should still be managed by the extension.

**Comment by jrieken** [comment]
> If that was possible, generic language embedding could be implemented by extensions.

The common pattern for that is to use a virtual document (see `registerTextDocumentContentProvider`-api) which takes a "composed" document and breaks that into actual "language" documents. It has the advantage of being a pull model and not being an unsaved document - for which we show an editor so that users can save it.

**Comment by hediet** [comment]
Thanks for the quick response!

`registerTextDocumentContentProvider` has the problem, however, that it requires its own scheme (which technically makes sense).
This means that the content cannot really interact with other documents from the workspace.

For readmes, it would be invaluable to check demos that refer to some library:
````
```ts
import { ... } from "my-lib";
```
````
This would require that typescript can resolve "my-lib" from the location the text document is hosted on.

I wonder if a virtual file system provider can register the same scheme and simulate a symlink into the workspace folder.

**Comment by jrieken** [comment]
Welcome to the challenge of embedded languages ;-)

> This means that the content cannot really interact with other documents from the workspace.

Well, uri-path-math is always possible but you cannot expect the "to be embedded" language to know these kinds of things. And that's where the trouble starts. For instance, TypeScript will report errors and warnings for the extracted snippet and you won't have a way to prevent this. And there is also no way to teach TypeScript to find references of symbols inside md-files because those files are not part of typical TS projects. The list goes on and the key message is that the virtual document approach falls apart as soon as multiple files or validation is involved, every things that's single file-ish work well tho. The alternative, but that's not generic, is to consume TS as a library and manage a language service yourselves. That's for instance what html does.

**Comment by hediet** [comment]
> Well, uri-path-math is always possible but you cannot expect the "to be embedded" language to know these kinds of things

Lets say we have a workspace, containing all the source files of a project:
```
./node_modules/...
./src/index.ts: export * from "./leftPad";
./src/leftPad.ts: export function leftPad() { ... }
./tsconfig.json: ... "include": ["src/**/*"], ...
./README.md
...
```

Lets further say the readme has different code blocks:
````
Demo 1:
```ts
// this is codeblock 1
import { x } from "some-workspace-lib";
x();
```

Demo 2:
[//]: # ({ "codeblock-kind": "continuation" })
```ts
// this is codeblock 2
x("foo");
```

Demo 3:
```ts
// this is codeblock 3
import { leftPad } from "../src/leftPad";
```
````

What I had in mind was writing the content of codeblock 1 + codeblock 2 to `./.tmp-codeblocks/codeblock1.ts` and codeblock 3 to `./.tmp-codeblocks/codeblock3.ts`.
Because of how the module resolution works in js, everything would work as expected. Typescript would even load these files and consider them if symbols get renamed (you can verify this by just creating these files manually - even if those files are not included by the tsconfig).

This (possible bi-directional) projection would map a section of one document into another document and keep them synced.

Ideally, these files would not be on disk, but I guess it is not a good idea for VS Code to allow extensions to map virtual files into the "file" scheme. However, with proper symlinks and a custom file scheme this could be solved (sadly we cannot implement custom file system providers with proper symlink support in a way that VS Code understands where the symlink points to).

But even if we accept writing to disk (which I think is ok for a third-party extension), this still cannot be implemented, since I cannot really write into these temp files (without relying on vscode watching these files or without vscode opening these files).

> we have failed to invent the gold hammer that solves this for all use-cases.

While a 100% solution would be nice for VS Code, even a 50% solution would be awesome as third-party extension. Even if it only supports javascript/typescript this would be great.
However, I think the approach I described works for many languages (in particular all single-file based languages like html and css).

**Comment by jrieken** [comment]
> Because of how the module resolution works in js, everything would work as expected. Typescript would even load these files and consider them if symbols get renamed

Maybe. I see how you put the files into the project folder itself but it would still require a tsconfig-file that's not strict in what it includes. Also, would you create the readme-projections eagerly or what happens if I have only ever opened leftPad.ts and when you rename its symbols - those file aren't there yet, right?

> However, with proper symlinks and a custom file scheme this could be solved (sadly we cannot implement custom file system providers with proper symlink support in a way that VS Code understands where the symlink points to).

Assuming we have all of this it would still not help you because tsserver is a separate application that uses node-fs, not the vscode-api. You would need something like FUSE to create virtual files that tsserver then would see. 

> this still cannot be implemented, since I cannot really write into these temp files (without relying on vscode watching these files or without vscode opening a visible editor for them).

You can always use `vscode.workspace.fs.writeFile`

**Comment by hediet** [comment]
> Also, would you create the readme-projections eagerly or what happens if I have only ever opened leftPad.ts and when you rename its symbols - those file aren't there yet, right?

Yeah, that is a problem - the projections would be eagerly. But this is a problem with typescript too, afaik. If you have the typescript projects A and B in a workspace with B depending on A and rename a symbol in A without opening any file from B before, it used to be the case that references in B did not get renamed.

> Assuming we have all of this it would still not help you because tsserver is a separate application that uses node-fs

Oh I see :(
I only tested it with the untitled scheme and it worked, but that seems to be a special case.
(Btw. relative imports from untitled typescript files are buggy.)
I had other ideas for hosting typescript files in a virtual file system too. But without language service support they are not going to work out.

> You would need something like FUSE to create virtual files that tsserver then would see.

Or a tsc plugin like yarn berry provides for pnp support. But I don't really want to go that route.

> You can always use vscode.workspace.fs.writeFile

This would only work if VS Code is notified about file changes quickly enough. Do you think I can rely on that?

**Comment by jrieken** [comment]
> This would only work if VS Code is notified about file changes quickly enough. Do you think I can rely on that?

Fingers crossed...🤞 File watching and embedding languages - two very hard problems but it should work.

**Comment by jrieken** [comment]
btw - for TypeScript specifically there is the notion of external projects: https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#external-project. In theory it would enable to achieve what you want. However, I have explored that a tiny bit for notebooks (see https://github.com/microsoft/vscode/issues/101923) and wasn't very successful. Tho, I might revisit that

**Comment by hediet** [comment]
It works surprisingly good:

![image](https://user-images.githubusercontent.com/2931520/92302999-56832680-ef71-11ea-9f3e-0c8aa8efa4dc.png)

However, autocompletion is quite slow if the list is large.
I guess you cannot really delegate all the language service features since the API exposed via vscode commands differs from the API you need to implement for certain features.

**Comment by hediet** [comment]
Also, after some time, the projection document is closed by vscode and the diagnostics disappear.
But I guess I can listen for the close event and just reopen the document.

Trigger characters for autocompletion are a problem though, since, afaik, they cannot be provided dynamically.

**Comment by jrieken** [comment]
> Trigger characters for autocompletion are a problem though, since, afaik, they cannot be provided dynamically.

You can add a new provider per language or unregister or re-register the existing provider with a merged set of trigger characters
