### ISSUE TITLE
File System provider and Typescript files

### ISSUE THREAD

**Issue by nmorenor** [microsoft/vscode#106073]
- VSCode Version: 1.48.2
- OS Version: OSX

Steps to Reproduce:

1. Create an extension that provides a file system.
2. Open a typescript/javascript/typescriptreact file with this file system scheme uri
3. VSCode go unresponsive you have to kill it, can't do anything on the UI

Does this issue occur when all extensions are disabled?: Yes, even disabling the microsoft builtin typescript javascript extensions.

**Comment by mjbvz** [comment]
Can you share the extension that causes this?

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by nmorenor** [comment]
Unfortunately I can't share the extension. Although i have this issue consistently, I don't have this problem with any other type of files just with .ts, .js, .tsx files. Any ideas on how to properly diagnose this problem? I have not tried on latest insiders build, but is something I can try.
