### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by shrmaky** [microsoft/vscode#106028]
Everytime am running a new instance of VSCode getting this error.

CPUs | Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 1, 2, 2
Memory (System) | 16.00GB (0.11GB free)
Process Argv | .
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
vscode-twig-pack | baj | 1.1.0
vscode-intelephense-client | bme | 1.5.4
vscode-tailwindcss | bra | 0.4.3
vscode-eslint | dba | 2.1.8
gitlens | eam | 10.2.2
prettier-vscode | esb | 5.5.0
php-intellisense | fel | 2.3.14
json2ts | Gre | 0.0.6
vscode-docker | ms- | 1.5.0
vscode-typescript-tslint-plugin | ms- | 1.2.3
live-sass | rit | 3.0.0
LiveServer | rit | 5.6.1
vscode-react-component-generator | ssw | 0.2.1
quokka-vscode | Wal | 1.0.317
bootstrap-v4-snippets | Zac | 1.1.3

**Comment by mjbvz** [comment]
What VS Code version is this for?

/needsMoreInfo

**Comment by mjbvz** [comment]
Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
What about in insiders with extensions disabled?
