### ISSUE TITLE
Is there vertical selection? Is there documentation?

### ISSUE THREAD

**Issue by urbanhop** [Microsoft/vscode#1060]
1. I am trying to select text vertical such as it is possible in Visual Studio.

2. Not finding a way to do so, I search the keyboard shortcut preference settings. No find either. So I try to search for documentation. More or less, there is none? I mean, at https://code.visualstudio.com/Docs, there is a rough overview but I cannot find an answer to this question.

Anyway, great tool even beside VS, thx for delivering and open sourcing it.

**Comment by egamma** [comment]
Please use ctrl+alt+down/up  (the action is called insert cursor below/above)

**Comment by urbanhop** [comment]
perfect, thank you!

ctrl+alt+down/up does not do anything on my machine, maybe because of my apple keyboard (+ key remapper). anyway after remapping it to shift+alt it works.

**Comment by mphaney** [comment]
Greatly appreciate the attention to this issue (and all of the team's hard work), but the solution suggested is NOT quite what was originally asked for on UserVoice.  The request stated clicking-and-dragging with the mouse, which can result in selecting space after a line has ended.  I believe the desired functionality is like so:

![blockselection](https://cloud.githubusercontent.com/assets/2546626/13466388/8f28d9d0-e04e-11e5-8ff7-10df486bc9a0.gif)

Any chance of re-reviewing this issue?  Or should I post a new one?

**Comment by egamma** [comment]
pls see #1515

**Comment by TimTheTinker** [comment]
This may accomplish vertical text selection, but I think what the community wants is rectangular selection (of which multiple adjacent insertion-point cursors on the same column is a subset)

**Comment by egamma** [comment]
This is now support in the insiders build https://code.visualstudio.com/download?insiders=true
pls see: https://code.visualstudio.com/download?insiders=true
