### ISSUE TITLE
Output windows shows Chinese character incorrectly 

### ISSUE THREAD

**Issue by hanbaobao2005** [Microsoft/vscode#10608]
- VSCode Version:1.4.0
- OS Version: Windows 10 Pro, version 1511, OS build 10586.545

Steps to Reproduce:
1. Python Code
url = r"公交"
print(url)
2. Output window shows Chinese characters incorrectly
![image](https://cloud.githubusercontent.com/assets/1937472/17732973/efa33058-64a6-11e6-9b78-4b0a366a63bc.png)

**Comment by lishinko** [comment]
looks like your python code is GBK-encoded rather than utf-8?

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/974
