### ISSUE TITLE
Feature request : remember the state of the workspace

### ISSUE THREAD

**Issue by pom421** [Microsoft/vscode#10607]
- VSCode Version: 1.4.0 
- OS Version: OS X 10.11

When i relaunch VS Code, my tabs are kept, it's what i want. 
But the view "Output" is showed again while i decided to hide it before i quit. 
Same thing for the breakline, it's systematically on when i launch VS Code.

It's only two examples but I would appreciate if my workspace is in the same state than when i quit previously.

**Comment by bpasero** [comment]
@pom421 are you saying we keep restoring the output panel all the time after restart? can you show a screenshot?
