### ISSUE TITLE
Clearning output in a notebook should mark the notebook as being dirty

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#106050]
Version: 1.49.0-insider
Commit: 00754e4babebc9ee5aa881234bc16366c4f32aa9
Date: 2020-09-02T05:43:25.834Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Python extension with content provider `transientOutputs: false,`
2. Open an existing notebook and clear the output.
3. At this point the document should be dirty.

Does this issue occur when all extensions are disabled?: N/A

@rebornix /cc

**Comment by rebornix** [comment]
I'm not able to reproduce this issue, do you have auto save turned on somehow?

**Comment by DonJayamanne** [comment]
Can i be forgiven for making a rookie mistake.... 🤦
