### ISSUE TITLE
Binding Ctrl+X such that it does not delete a blank line if no selection is present

### ISSUE THREAD

**Issue by verslyfr** [microsoft/vscode#106058]
Issue Type: <b>Bug</b>

I oftentimes switch between Visual Code and Emacs. Emacs uses a combination Ctrl-X Ctrl-S to save a file. Unfortunately, Ctrl-X on Visual Code uses Ctrl-X to delete a line if no selection is present. I tried to change the Ctrl-X behavior by using the When clause in the keybindings. I have set the When clause to "editorHasSelection && editorTextFocus", but this seems to have no impact on the Ctrl-X key behavior, it still deletes a line when there is no selection. 

I am looking for work arounds. I have searched for other options to disable this functionality, but have been unable to find one yet. 

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
python-snippets|cst|0.0.8
remote-wsl|ms-|0.44.5
vscode-autohotkey|sle|0.2.2
TabOut|alb|0.2.0
save-as-snippet|art|0.0.1
excel-to-markdown-tabl

**Comment by alexdima** [comment]
This can be controlled via `"editor.emptySelectionClipboard"`. You can set it to `false`.
