### ISSUE TITLE
[WebviewView] Ability to "show" via API

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/vscode#106085]
Testing #105764

When hosting the WebviewView in a "Panel" we should be able to "show" it via API, in my example below:

1.  User clicks an item in a custom `TreeDataProvider`.
2.  I update the content and title of the WebviewView (title does not update see:  https://github.com/microsoft/vscode/issues/106083)
3.   I would like to force "show" the WebviewView panel.

![image](https://user-images.githubusercontent.com/966863/92199377-e2f8f080-ee6e-11ea-8e6b-40abb56dd22b.png)

For comparison the `vscode.Terminal` has  `show` and `hide` methods.

**Comment by GordonSmith** [comment]
Possible Workaround:
```
    vscode.commands.executeCommand("CUSTOM_VIEW_ID.focus");
``` 
Seems to work

**Comment by GordonSmith** [comment]
@mjbvz how do you "show" a WebviewView which has not been resolved yet?

It feels like we should be able to resolve the hosting panel and "show" it?

**Comment by mjbvz** [comment]
You can use the command for that. We don't want to activate the extension that provides the webview until the view itself needs to be rendered
