### ISSUE TITLE
VS Code puts non-breaking whitespace in copied syntax highlighted code

### ISSUE THREAD

**Issue by ayush-j** [microsoft/vscode#106077]
Issue Type: <b>Bug</b>

When copying text from VS Code, normal space characters are converted to non-breaking whitespace (&#160;) in clipboard. Due to this, if I copy paste code from VS Code -> (some other app which supports html) -> back to VS Code, the code breaks because of different space characters.

Usecase is that I regularly copy/paste code from VS Code to OneNote and then back to OneNote. I want to retain syntax highlighting but don't want the space to be converted.

VS Code version: Code - Insiders 1.48.0-insider (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-11T23:21:50.282Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (21.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ayush-j** [comment]
Duplicate of which issue?

**Comment by MarinMlinarevic** [comment]
I think this is considered a duplicate of issue #88178
