### ISSUE TITLE
Focusing Outline & hitting [ Enter ] on a symbol no longer focuses the editor

### ISSUE THREAD

**Issue by AidanVIII** [microsoft/vscode#106025]
- VSCode Version: 1.48.2 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Use the Outline's shortcut to focus it
2. Use arrows to focus a symbol/heading
3. Hit [ Enter ]

![Capture](https://user-images.githubusercontent.com/20214995/92095137-944b4800-edd5-11ea-89d3-a5d6d1c95b9b.PNG)

Snippet:
```
# Heading 1
# Heading 2
```

Errors in the Dev Tools Console:
No.

Expected:
Editor focuses the editor and puts the cursor at the end of the line.

Saw:
Focus remains on the outline's symbol.

Does this issue occur when all extensions are disabled?: 
Yes

**Comment by jrieken** [comment]
This is the `onDidOpen`-event from the tree. Not sure what/if anything changed there

**Comment by joaomoreno** [comment]
I cleaned up the `onDidOpen` event which now has much more information. @jrieken can you review and verify?

**Comment by jrieken** [comment]
The change doesn't make sense to me but it seems to work

**Comment by jrieken** [comment]
Ah, no it makes sense. We would make `preserveFocus === true` too often.

**Comment by joaomoreno** [comment]
The problem was the expression `!!e.editorOptions.preserveFocus || !e.editorOptions.pinned`

**Comment by jrieken** [comment]
verified in master
