### ISSUE TITLE
Problem editor overlay should auto dismiss after problem is rectified.

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#106066]
VSCode: 1.48.2

Observed Behaviour:
When I rectify a problem in code, the overlay that was present at the line does not auto dismiss when the problem is resolved and the file is saved. I subsequently have to press esc key to dismiss the overlay.

Desired Behaviour:
Once the problem is resolved, and the file is saved, the overlay should immediately dismiss.

**Comment by weinand** [comment]
When I rectify a problem by editing or moving the cursor the problem hover immediately disappears:

![2020-09-03_22-48-40 (1)](https://user-images.githubusercontent.com/1898161/92165739-cee5cc80-ee37-11ea-8087-77678cf060f8.gif)

Are you seeing different behaviour?

**Comment by safield** [comment]
Sorry, to clarify there is a different problem dialog that is inlined in the editor.

-create a problem on a line of code
-press F8 to jump to next problem.
-a different overlay dialog will show.
-rectify the problem
-the dialog remains.

This dialog should behave like the dialog you have depicted in your post.

**Comment by sandy081** [comment]
@jrieken Currently we show the error peek view as stale. What do you think about closing the peek view when it becomes stale?

**Comment by jrieken** [comment]
Today it's the way it is to ensure a stable editing experience. Image an error widget shows above your cursor location and while you type you fix the error it shows. The whole contents and cursor would jump upwards when hiding the widget.

**Comment by sandy081** [comment]
Makes sense. 

Closing this as won't fix.
