### ISSUE TITLE
Angular localserver keep reloading

### ISSUE THREAD

**Issue by akrishh** [microsoft/vscode#106059]
Issue Type: <b>Bug</b>

After the latest update, the Angular Server keep reloading, and an auto save happens though it was selected.

Below is the Visual Studio Code updated information:
Version: 1.48.2 (system setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
Please provide steps to reproduce the issue

**Comment by mjbvz** [comment]
Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
