### ISSUE TITLE
Custom hover keeps lingering around 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#106096]
1. Do find all referneces on some term
2. References view gets opened, hover over an item -> get the custom hover
3. While the custom hover is shown, press Ctrl + Shift + E -> explorer gets opened and the custom hover keeps lingering around like a zombie 🧟 

I can repro 100% on macOS. If you can not repro let me know

**Comment by alexr00** [comment]
@Tyriar is this something that can be solved at the hover layer since the hover layer takes care of hiding?

**Comment by Tyriar** [comment]
@alexr00 the terminal fixes this by calling `IHoverService.hideHover` when the panel should be hidden.

This has some downsides (eg. a hover in the tree view will hide if you hide the panel with the terminal visible) but we could always refine that later. Eventually I think the context view service (that the hover leverages) should support multiple context views with keys, that way we can associate a key for the hover and only hide the hover with the requested key.

**Comment by Tyriar** [comment]
Had a chat with @alexr00, created a new issue to solve problem generically: https://github.com/microsoft/vscode/issues/106127

**Comment by eamodio** [comment]
I've also seen this recently with editor debug hovers that seemingly get stuck for many seconds -- though that could be a very different issue

**Comment by Tyriar** [comment]
@eamodio editor hovers have a different lifecycle mechanism managed by monaco.

**Comment by eamodio** [comment]
Ah ok -- thanks

**Comment by isidorn** [comment]
This works as excepted in VS Code insiders -> verified
