### ISSUE TITLE
Wiki build tip has an inaccurate shortcut for MacOS 

### ISSUE THREAD

**Issue by anish-94** [microsoft/vscode#106081]
- VSCode Version: N/A
- OS Version: MacOS

The build [section](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build) in the wiki has a tip - 
>  Tip! You can also run the build in a terminal with `yarn watchd`. Pressing Ctrl+C will leave it running in the background. Pressing Ctrl+D will kill it permanently (CMD+C and CMD+D on macOS).

This needs to be updated to stay Ctrl+C and Ctrl + D on MacOS as well. Looking at the [Terminal User Guide](https://support.apple.com/guide/terminal/keyboard-shortcuts-trmlshtcts/mac), the CMD + D splits the window into two panes and CMD + C is the regular text copy (just to confirm that it wasn't my custom shell environment).

**Comment by Tyriar** [comment]
Fixed, thanks
