### ISSUE TITLE
Format On Save Not Working For Build Tasks

### ISSUE THREAD

**Issue by bramankp** [microsoft/vscode#106043]
Issue Type: <b>Bug</b>

Once changes are made to a file, a manual save will trigger the Format On Save behavior. However, if I instead run a Build Task (which saves the file before the task is run) the Format On Save behavior is no longer being run.

I noticed this after a recent update to 1.48 (although I can't confirm exactly when it changed).

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (21.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.9
vscode-open-in-application|fab|1.0.5
cortex-debug|mar|0.3.7
cpptools|ms-|0.29.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.10
clang-format|xav|1.9.0
linkerscript|Zix|1.0.1

</details>

**Comment by alexr00** [comment]
This is currently intentional. More info and a feature request for configuration [here](https://github.com/microsoft/vscode/issues/104296)
