### ISSUE TITLE
Request to enable font customization for other non-editor window

### ISSUE THREAD

**Issue by johncruise** [Microsoft/vscode#10605]
- VSCode Version: 1.4.0-insider (2016-07-22T05:07:03.113Z)
- OS Version: Windows 7

Steps to Reproduce:
1. File -> Preferences -> User Settings/Workspace Settings

The default font for the Explorer/Search/Git/Debug/etc pane and other windows like Debug/Console/etc are not optimal for screen with not so big screen and using a split window.  Those other windows takes too much spaces when using it.

I'd like to request per subject to independently have a way to customize the font sizes for all those non-editor window.  Example...

``` properties
# current way to change the editor window font size
"editor.fontSize": 14,
# other non-editor font settings
"global.other.editor.fontSize": 12,
# or maybe per individual panel/window settings... although this may be too much
"window.debug.fontSize": 12,
"window.console.fontSize": 12,
```

**Comment by raelb** [comment]
Such an option is also very useful for another purpose.

I want the editor text to have the same appearance as text in Sublime Text editor. There, the default font size is 10. If I change the `editor.fontSize` to 10 in VS Code, the text becomes *tiny*. I can solve this by setting the `window.zoomLevel` to something like 2.5. But then the rest of the UI becomes disproportionately large.

To put in other words, there seems to be some discord between the editor font and the rest of the UI fonts. When I set `editor.fontSize` to 10, the font is very very small, and does not correspond to a "normal" fontsize 10 of other applications.

I'm using VS Code v1.4, Window 7
Screen Res 1600x900 and custom font size set to 120%.

**Comment by jyavenard** [comment]
:+1:

**Comment by envygeeks** [comment]
Please, or at least select the current environments fonts on Linux.  Ubuntu's font family isn't my preferred font, I use custom fonts through and through and VS Code looks out of place.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/519
