### ISSUE TITLE
 Syntax highlighting bug, with quotes, in bash shell script

### ISSUE THREAD

**Issue by HA3IK** [microsoft/vscode#106078]
- VSCode Version: 1.48.2
- OS Version: Win10 Pro (1909)

Steps to Reproduce:

0. The line looks fine and is working.
1. Open this file: [yii2-app-basic/vagrant/provision/once-as-root.sh](https://github.com/yiisoft/yii2-app-basic/blob/0b94c3142b5070b44fa389be74ff2191a783af10/vagrant/provision/once-as-root.sh) **_(GitHub highlighting also is failed)_**
2. And we see the following syntax highlighting in VSCode:
![VS Code's syntax highlighting bug](https://user-images.githubusercontent.com/3060791/92143237-e2c80900-ee0c-11ea-85ff-d5cab711ad2b.png)  

As I noticed, you have a lot of issues where quotes break the syntax highlighting of the bash shell 😅

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
We get our grammar for shell script syntax highlighting from https://github.com/atom/language-shellscript, but they aren't supporting the grammar anymore. I'll keep this bug around in case we update where we get our grammar from.

**Comment by alexr00** [comment]
Linking and closing in favor of #77675, which tracks considering a new shellscript grammar.
