### ISSUE TITLE
Create an extension with simple icons support

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10600]
Using attached set: 
[Simple.Explorer.Icons.zip](https://github.com/Microsoft/vscode/files/421766/Simple.Explorer.Icons.zip)

Looking at vscode-icons, they
* set a CSS class in the form of `<language-id>-file-icon` on the file label (e.g. `dockerfile-file-icon`)
* set a CSS class of `default-file-icon` if the language ID cannot be resolved
* override some CSS for the case of `folder-icon` to show a folder icon and also add some CSS for when the parent row is expanded to support the expanded folder icon. maybe we want to make this more explicit and introduce `expanded-folder-icon` and `collapsed-folder-icon`?
* when showing an icon, the CSS properties to show it are `padding-left: 22px;` and `background-size: 16px !important;`. we could make this a convention and ask our icon providers to provide good versions for 16px dimensions. this would work for SVG and PNG. 
* we need to account for light, dark and hc theme

**Comment by rmunn** [comment]
Is this necessary, given that https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons exists? What would this extension do that vscode-icons doesn't?

**Comment by aeschli** [comment]
vscode-icons patches the VSCode source code. We'd like to create an 'official' API/contribution point so that vscode-icons (and others) can use instead.

**Comment by bpasero** [comment]
@rmunn we are in the process of allowing an extension like vscode-icons to add icons without patching our sources. We would also like to provide an extension that uses the simple icon set designed by us so that users have the choice once we release for August.

**Comment by bpasero** [comment]
@aeschli updated the description with my findings from vscode-icons

**Comment by robertohuertasm** [comment]
Hi, have you already deployed new changes regarding icon integration in the new Insiders update? It would be great to know how the new API will work in order to change vscode-icons accordingly and cause no pain to the current users. :grinning:

**Comment by aeschli** [comment]
Hi @robertohuertasm, I'm working on the documentation in https://github.com/Microsoft/vscode/issues/10804.
You also want to check out the built-in [standard icons]((https://github.com/Microsoft/vscode/tree/master/extensions/theme-defaults)).

**Comment by aeschli** [comment]
New contribution point got added and is available in the latest insider builds.
See #10804 for the documenatation
