### ISSUE TITLE
Seeing custom and native hovers in custom tree views

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#106007]
I was using web:

![recording](https://user-images.githubusercontent.com/900690/92081515-7aa10500-edc3-11ea-8034-ade7e8548556.gif)

I also feel the delay to make the custom hover appear could be a bit longer.

**Comment by Tyriar** [comment]
@alexr00 shouldn't the custom hover also show the full path like the `title` tooltip was?

**Comment by alexr00** [comment]
That came from the resource label. Since we do the hover at the tree level and not at the resource label level we now don't have the full path. I could copy the code that the resource label uses or expose this on the resource label to accomplish this if we want to add the full path back.
