### ISSUE TITLE
GitHub provider doesn't always show up in repository picker 

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#106003]
Refs #102394

I'm using the new `git.api.getRemoteSources` command in the GitHub Browser extension, but often (at least the first coupe of times) the GitHub provider doesn't show up.

```ts
const value = await commands.executeCommand('git.api.getRemoteSources', {
					providerLabel: (provider: RemoteSourceProvider) => `Open Repository from ${provider.name}`,
					urlLabel: 'Open Repository from URL',
				});
```

/cc @egamma

**Comment by joaomoreno** [comment]
> the first coupe of times

On startup? Remember both the Git and GitHub extensions need to be activated for the command to fully work. This is a limitation which is very hard to get around, there isn't proper lifecycle here.

**Comment by eamodio** [comment]
Yeah on startup, though shouldn't the command cause the activation and wait until activated?

**Comment by joaomoreno** [comment]
The command belongs to the Git extension, so yeah that will be activated. But not the GitHub extension. 😢
