### ISSUE TITLE
Crash with "window no longer responding" message

### ISSUE THREAD

**Issue by moizgh** [microsoft/vscode#106071]
Issue Type: <b>Bug</b>

duplicate of https://github.com/microsoft/vscode/issues/103744
submitting to capture logs.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19645

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1660 v3 @ 3.00GHz (16 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|31.91GB (10.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
gitlens|eam|10.2.2
prettier-vscode|esb|5.5.0
git-tree-compare|let|1.9.2
vscode-typescript-tslint-plugin|ms-|1.2.3

</details>

**Comment by deepak1556** [comment]
Does this happen with latest insiders https://code.visualstudio.com/insiders ?
