### ISSUE TITLE
vscode Completion API question

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/vscode#106090]
when CompletionItem contains `.`, the character after the first dot will let the completions disappear, I already set `CompletionItem.filterText`, and I don't know what have I missed

![e](https://user-images.githubusercontent.com/15936231/92207287-94be0e80-eebb-11ea-9f8d-1ccfbcb54992.gif)
![image](https://user-images.githubusercontent.com/15936231/92207488-dd75c780-eebb-11ea-91ab-5ff5c1e0f4c9.png)

EDIT: I also set the range to `new Range(position.line, at_index + 1, position.line, position.character);`, at_index is @ position, didn't work either

**Comment by jrieken** [comment]
hm... do you use `.` as a trigger characters? It might be that completions get re-triggered when typing that second `.`

**Comment by CGQAQ** [comment]
> hm... do you use `.` as a trigger characters? It might be that completions get re-triggered when typing that second `.`

no, I didn't, trigger chars are @ and /

**Comment by jrieken** [comment]
This seems to work for me using the provider below. Can you tweak my snippet so that it reproduces what you see?

![Sep-08-2020 09-06-49](https://user-images.githubusercontent.com/1794099/92444084-af8dcd00-f1b2-11ea-9de4-cf9946116c5c.gif)


```ts
	vscode.languages.registerCompletionItemProvider('fooLang', new class implements vscode.CompletionItemProvider {
		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext): vscode.ProviderResult<vscode.CompletionItem[] | vscode.CompletionList<vscode.CompletionItem>> {
			return [
				new vscode.CompletionItem('0.67.0'),
				new vscode.CompletionItem('0.61.0'),
				new vscode.CompletionItem('0.62.0'),
				new vscode.CompletionItem('0.63.0'),
				new vscode.CompletionItem('0.64.0'),
				new vscode.CompletionItem('0.65.0'),
			]
		}
	})
```

**Comment by CGQAQ** [comment]
![issue](https://user-images.githubusercontent.com/15936231/92445530-12995700-f1e7-11ea-8359-c76974d96ce0.gif)

Maybe it's vscode built-in ts completion plugin?

**Comment by CGQAQ** [comment]
And I removed all the other code, still happened. So I think it's definitely an issue with the vscode built-in ts/js plugin
![issue3](https://user-images.githubusercontent.com/15936231/92448439-28a91680-f1eb-11ea-991a-3dea788358a0.gif)

**Comment by jrieken** [comment]
Thanks for the extra info... The problem is that `.` separates words for JS and TS (and likely others) and that when typing the `6` in `0.6` a new word starts and for us that is a reason to cancel a completion session... Instead we should first check if there are still matching suggestions and only then cancel suggest.

**Comment by CGQAQ** [comment]
> Thanks for the extra info... The problem is that `.` separates words for JS and TS (and likely others) and that when typing the `6` in `0.6` a new word starts and for us that is a reason to cancel a completion session... Instead we should first check if there are still matching suggestions and only then cancel suggest.

@jrieken I found an interesting one, the `.` in `deno.land` will not cancel the completion session
![issue3](https://user-images.githubusercontent.com/15936231/92449530-ca7d3300-f1ec-11ea-8732-069e18030bfc.gif)

**Comment by jrieken** [comment]
It's not the dot that cancels but what you type afterwards and for us it matters if that's a letter or a number

**Comment by CGQAQ** [comment]
> It's not the dot that cancels but what you type afterwards and for us it matters if that's a letter or a number

Oh, I see. you mean only a number following the `.` will cancel the completion session, that makes sense

**Comment by mjbvz** [comment]
@CGQAQ Did you get a chance to test the fix?

**Comment by rzhao271** [comment]
Marking this as verified.

However, when I press backspace too many times (e.g. '0.61.0' to '0.') autosuggest turns off and then I have to trigger it again. @jrieken is this expected behaviour, or should I file a new issue?

**Comment by CGQAQ** [comment]
/verified

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
