### ISSUE TITLE
Extension Host terminates unexpectedly on fresh install

### ISSUE THREAD

**Issue by devaslooper** [microsoft/vscode#106048]
Version: 1.49.0-insider
Commit: 8c9b4015feb0297d99c8051c35e85d208ffe83e3
Date: 2020-09-03
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. Install the latest VSCode version
2. Install Python extension
2. Open existing demo folder with .py file

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Things tried out:**
1. Freshly installing previous versions of VS Code (tried past 2 versions)
2. Installed Insider Build, and tried out same procedure
3. Looked through similar issues, no solutions worked out.
4. Tried previously installed builds on another folder with python files.
5. Disabling system certificates.
6. Reinstalled python V 3.7

**Note:**
This was my first time installing VS Code, so I don't think the problem can be caused by any leftover files.
I couldn't another option for filling an issue other than Bug report, so sorry if this is not related.
I didn't install any other extensions other than the one for python. 

**Console Logs:**
1. These logs are even before the extensions start to load in.
![1 Annotation](https://user-images.githubusercontent.com/64781657/92130765-be772700-ee22-11ea-95aa-8baaba2e306f.jpg)

2. This is after the error pop-up is displayed saying, 'Extension Host terminated unexpectedly'
![2 Annotation](https://user-images.githubusercontent.com/64781657/92130922-ef575c00-ee22-11ea-8809-ec50e5d77af4.jpg)

Hope you all can help resolve this one

**Comment by connor4312** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No
> Yes

To be clear -- does it happen if you omit step 2? (If you don't install the Python extension)

**Comment by devaslooper** [comment]
No, it doesn't show the crash popup when the python extension is not installed.

**Comment by connor4312** [comment]
Okay, thanks. Please open an issue for the Python team.

\extPython
