### ISSUE TITLE
cannot add cursor by shortcut "Ctrl + Alt + UpArrow" or "Ctrl + Alt + DownArrow"

### ISSUE THREAD

**Issue by leodinas-hao** [microsoft/vscode#106089]
- VSCode Version: 1.48.2
- OS Version: Windows x64 10.0.19041

Steps to Reproduce:

1. open a editor
2. press the shortcut "Ctrl + Alt + UpArrow" or "Ctrl + Alt + DownArrow" to add

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
What does VS Code detect when you press the desired key combination? 

![keyboard-input](https://user-images.githubusercontent.com/5047891/80482640-da3e5e00-8954-11ea-9583-0f652b0595a8.gif)

**Comment by leodinas-hao** [comment]
Sorry, I found the cause. The recent update of Intel Graphics Command Center overrode the hotkeys of "ctrl + alt + up/down". After disabled it, vscode started working again.
