### ISSUE TITLE
Terminal: CTRL+L should clear scrollback just like the command "clear" in a shell does

### ISSUE THREAD

**Issue by ppanhoto78** [microsoft/vscode#106036]
- VSCode Version:1.48.2
- OS Version:Ubuntu 20.04/OpenSuSE Tumbleweed

Steps to Reproduce:

1.run `ls /usr/bin`
2.press CTRL+L -- the screen will be blank
3. scroll up  -- We can still see the the output of last command.
4. run `clear ; ls /etc`
5. scroll up - We just see the output of what came after clear.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
See https://superuser.com/a/819605/205226, ctrl+L in whatever shell you're using does not appear to be telling the terminal to clear its scrollback.

**Comment by ppanhoto78** [comment]
Just learned to make a chord and clear the backbuffer. Nevermind.

Happy coding!
