### ISSUE TITLE
Hover appears at a weird location

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#106010]
I am looking at the custom hover in the references view extension in web:

![recording (1)](https://user-images.githubusercontent.com/900690/92082244-8fca6380-edc4-11ea-91d0-0bbbaa54027e.gif)

It seems to me that when I go in and out (between editor and view) the hover appears at bad locations, not close to the mouse.

PS: I also wonder if the hover should be below the mouse cursor not above, at least the native hover on macOS is below.

**Comment by Tyriar** [comment]
The x position is defined by the custom tree view part.

@alexr00 do you think it should go below? All the terminal hovers are above and it makes the most sense especially if there are actions associated with the hover as they should be right near the cursor. If we decided to go below, this would mean where our custom hovers display becomes inconsistent. @bpasero is anything bothering you other than the OS shows `title` tooltips below normally?

**Comment by bpasero** [comment]
@Tyriar I think I am just used to seeing a hover below my mouse not above. I just checked, and macOS, Linux and Windows all seem to put the hover below the cursor not above. 

I think putting it above is maybe more common only for editors but I am not sure we should go against OS standards in other places.

**Comment by alexr00** [comment]
I think it is more important to be consistent with what people expect than with editor hovers here. Above or below doesn't bother me, but more uses will notice that the behavior is now different in the trees.

**Comment by alexr00** [comment]
For the position being off: I was using the mouse enter position, but its possible the mouse moves after that. Updated to account for the move.

**Comment by bpasero** [comment]
@alexr00 I see the bugs fixed for the hover, which is good. However can we have a follow up issue on the fact that our custom hover is different from native hovers in the following ways:
* the position is above while OS native experience seems to be below
* the hover still appears very fast for me compared to the native Chrome hover, at least twice as fast
* on Chrome at least, once I make the hover appear, moving the mouse to other elements with hover shows the hover almost instant, so I think they have some logic that would make the hover appear faster once you have it visible, this is likely an accessibility feature to make it easier to discover pieces of the UI

The reason why I am sensitive to this is that we should try to match the native look and feel as much as possible. To give another example: we are using hand cursor on clickable elements in the UI and we got users complaining that this is a pattern only seen in web UIs but not native UIs. I fear we might end up annoying more users that want an experience that is closer to what the OS provides. 

cc @misolori for UX and @Tyriar for workbench hover in general
