### ISSUE TITLE
Input data "jumps" around EOL character

### ISSUE THREAD

**Issue by malachib** [microsoft/vscode#106022]
- VSCode Version: 1.48.2
- OS Version: Windows 10 Pro 20H2 (And I believe Debian 10 also)

Steps to Reproduce:

1.  Open up a large C++ file ( > 1000 lines)
2.  Begin typing within a function definition

Does this issue occur when all extensions are disabled?: No

It seems that the EOL character lags behind what's being typed and shuffles its way forward.  I have taken an animated GIF of the issue:

![ezgif-4-1582198525fd](https://user-images.githubusercontent.com/1586399/92091759-0a27c300-ed86-11ea-975c-1cfdd6ef6a62.gif)

Disabling extensions does indeed inhibit the issue.  

I am not fully convinced this is a bug, but I was eaten alive and shut down by the "helpful" people on stackoverflow, so I am forced to inquire here

**Comment by alexdima** [comment]
> Disabling extensions does indeed inhibit the issue.

AFAIK the end of line symbol that you see there is not part of VS Code, so it must be contributed by some extension. You an disable all extension by pressing `F1` and then choosing `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)

**Comment by malachib** [comment]
In my original post:

"Does this issue occur when all extensions are disabled?: No"

I tried that and indeed the behavior is inhibited.  Probably it's part of `code-eol` extension

**Comment by alexdima** [comment]
Please report directly to the extension.
