### ISSUE TITLE
Preferred theme settings should be scoped to relative set

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#106063]
<img width="400" src="https://user-images.githubusercontent.com/35271042/92151941-c4dfb180-edd6-11ea-8d8b-e64710236bdd.png">

I would expect that only dark themes appear in the list for `workbench.preferredDarkColorTheme` and vice versa for the other theme lists. Especially since we split out the list in the color theme picker:

<img width="400" src="https://user-images.githubusercontent.com/35271042/92152133-0c663d80-edd7-11ea-945a-65b5b3f4cf68.png">

**Comment by aeschli** [comment]
What you see are the list of allowed themes, as defined by the configuration. By limiting it to only the light themes, functionality would be lost. Right now a user is free to choose a light theme when the OS scheme is dark.

The settings UI is generated out of the settings configuration which are done using JSON schema. Improving the UI is not easy.

**Comment by misolori** [comment]
I’d argue that if you want to have the same theme for dark and light then you don’t need to use this feature as that’s how it works by default.

**Comment by aeschli** [comment]
One could use a light theme when the OS is dark, and a dark theme when the OS is light. Ok, I'm completely making this up, but I just wonder if we really gain anything from restricting the themes.

**Comment by misolori** [comment]
For me it was more of "Why isn't VS Code smart enough to know that I only want the dark themes listed for dark preferences" and felt like a bug. Also, that list is hard to read through because the order feels random and not alphabetical (looks like defaults are near the top). We should just polish this experience.

**Comment by aeschli** [comment]
No plans to change the current behavior.
