### ISSUE TITLE
Environment: BACKUPS is weird

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#106021]
In an attempt to try to clean up `environment.ts` I noticed:

https://github.com/microsoft/vscode/blob/61e2ec4627f6c4f2b1113b1a7460e3938ca27cb8/src/vs/platform/environment/common/environment.ts#L20

I find this is at a weird location, especially because this file can be used in many contexts and many processes. This should move out imho, maybe on the level of workbench if only used there?

**Comment by bpasero** [comment]
Also, we do have `backupHome: URI` already in the `IEnvironmentService` interface.

**Comment by sandy081** [comment]
Cleaned up backup related properties in environment service

- removed `backupHome` from common env service and moved it into `INativeEnvironmentService` as it is only used on main (electron) side. Also changed its type to string (path)
- Promoted `backupWorkspaceHome: URI` to `IWorkbenchEnvironmentService`. This is the location under which back up is done for a given workspace.

**Comment by bpasero** [comment]
@sandy081 thanks!!
