### ISSUE TITLE
Mouse wheel first scroll is ignored in VSCode editor

### ISSUE THREAD

**Issue by botekp** [microsoft/vscode#106002]
Indepenently on system settings, when scrolling code up and down using mouse scroll wheel after a longer pause in user input, the first scroll rib move is being ignored by VSCode and text does not scroll anywhere.

This seems to be be associated with some kind of timeout that may be designed to prevent accidental mousewheel scolling - as when mouse is scrolled again within a 5-10 seconds interval from the first scroll that "unlocks" scrolling, mouse reacts properly and always scrolls at every wheel slightest move.

Tried all possible mouse settings available in VCCode - nothing this problem.

Can mouse be please made sensitive and react to every input action properly without any artificial accidental mouse wheel scroll protection as this is a really annoying feature and makes the editor unusable.

Kind regards.

**Comment by alexdima** [comment]
@botekp We react to all the `mousewheel` events coming in from Chromium / the OS. We have not implemented any such ignoring of mouse wheel events. What OS are you using?

VS Code is built with Electron, which is built with Chromium. Could you please try to open https://vscode-web-test-playground.azurewebsites.net/ in Chrome and see if you have this scroll problem there as well?

**Comment by botekp** [comment]
Hello Alex,

Thanks for a quick response. I tested the above https://vscode-web-test-playground.azurewebsites.net/ in Chrome and it yields the same result.

My system is Mint 19.3 x64 Cinnamon. 

I tested scrolling in a text viewer called KRViewer and it does not demonstrate this problem at all. So I assume this may be specific to VS Code.

Is there any other tests I can do?

Cheers

**Comment by alexdima** [comment]
@botekp Could you please also try https://vscode-web-test-playground.azurewebsites.net/ in Firefox?
