### ISSUE TITLE
ruby highlighting confused by a slash (/) or or quote (') in a here document

### ISSUE THREAD

**Issue by riepel** [microsoft/vscode#106146]
Issue Type: <b>Bug</b>

To replicate, open this ruby script:

[ruby-highlight.txt](https://github.com/microsoft/vscode/files/5177370/ruby-highlight.txt) (had to add <i>.txt</i> to get it upload)

Put the window into Ruby mode and observe that the highlighting goes haywire at the slash (/) on line 27 and doesn't recover until the slash on line 102. Further, delete the slash on line 27 - the highlighting changes, but goes wrong again at the quote (') on line 33 never to recover.

Both VScode and Textmate have this problem. Atom does it right, apparently by treating the contents of here documents as quoted text (which they are).

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
macos-modern-theme|dav|1.6.10

</details>

**Comment by weinand** [comment]
Please file issue against Ruby extension
