### ISSUE TITLE
Explorer sort order is not alphabetical

### ISSUE THREAD

**Issue by dandohotaru** [microsoft/vscode#106115]
Issue Type: <b>Bug</b>

As far as I can tell, there are some issues with the sort order in the Explorer panel, at least when folders do have a "." (dot) in their names.

As is (notice that Core.Domain[.*] folders are not in sequence)

![image](https://user-images.githubusercontent.com/1856429/92234505-77d10d80-eeb2-11ea-9278-ad8754f40223.png)

As expected:

![image](https://user-images.githubusercontent.com/1856429/92234578-9800cc80-eeb2-11ea-8d56-fda4007f10e7.png)

In terms of settings
  Settings > Features > Explorer > Sort Order: Default
the sort order is set to Default, so I would expect that files and folders to sort alphatically

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.14393

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by JackClarkeUottawa** [comment]
It is a weird result, but I dont think it's a bug. Based on [this](https://github.com/microsoft/vscode/issues/99955#issuecomment-643391532) explanation it seems that vscode **ignores file extensions** when sorting unless the names are the same. So what vs code is sorting by is
- Core
- Core
- Core.Domain
- Core.Queries
- Shared
- Shared 

Your file manager is sorting by the entire length of the name including the extension, which gives a different result

**Comment by dandohotaru** [comment]
that would have been probably correct if the sorted targets were files, 
but as a matter of fact those are folders, 
and should not be treated as having an extension :)
