### ISSUE TITLE
[ruby] shebang is not reconized

### ISSUE THREAD

**Issue by blairham** [Microsoft/vscode#10613]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

Steps to Reproduce:
1.  Add `#!/usr/bin/env ruby` as the first line to any file without an extension

**Comment by Spown** [comment]
what do you mean? syntax coloring? it's file extension based. you can choose synatx manually at any point
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2016-08/explorer_2016-08-17_18-41-55.png)
Code can not and should respond to ``#!/usr/bin/env``

**Comment by blairham** [comment]
actually it can and should respond to the shebang `#!/usr/bin/env ruby` just as discussed in this thread: https://github.com/Microsoft/vscode/issues/3806

it current responds to the shebang `#!/usr/bin/env bash` appropriately

![image](https://cloud.githubusercontent.com/assets/5043780/17745303/59f1a224-6479-11e6-8a25-04313392b5c9.png)

but not ruby
![image](https://cloud.githubusercontent.com/assets/5043780/17745309/6684a568-6479-11e6-8975-fc122361e240.png)

**Comment by roblourens** [comment]
Verified, but @aeschli - should this work immediately adding a new file, or adding a shebang to an existing file? It only fixes the highlighting when I open and close the file.

If I have a js file with no file extension, then open the file, and rename to add the .js extension, it detects that immediately.
