### ISSUE TITLE
Feature request: Better C# syntax colorizer

### ISSUE THREAD

**Issue by nfantone** [Microsoft/vscode#10619]
On latest Insiders (`1.5.0-55168276e4c0b6ec2404ac20af04eeed5f5b1000`), C# syntax  highlighting look _very_ bland.

<img width="823" alt="screen shot 2016-08-17 at 11 39 26 am" src="https://cloud.githubusercontent.com/assets/476069/17740664/d36e14c0-646f-11e6-93a3-9523e0ca963f.png">

As you can see, almost 70% of the text is just plain white, with only a few keyword being blue. Tried different themes as well, and all of them colorize the same bits leaving what was white-ish in the default theme intact.

Am I doing something wrong? Is there an extension of sorts for enhancing this? I am new to C# in general, so perhaps this is to be expected? Or are there plans to support better syntax highlighting in the future?

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#674
