### ISSUE TITLE
Diff editor not opened when file was opened previously

### ISSUE THREAD

**Issue by zawys** [microsoft/vscode#106130]
- VS Code Version: 1.49.0-insider, 8c9b4015feb0297d99c8051c35e85d208ffe83e3
- OS Version: Fedora 32, x64

### Steps to Reproduce

1. Open a workspace configured for Git version control.
2. Open an unignored file.
3. Edit it.
4. Open the *Source Control Explorer* (via activity bar).
   -> The edited file should appear in the list under *Changes*.
5. Click on the file in the list.
   -> The file editor is focused. Nothing else happens.

### Expected Results

The diff editor should open as in previous versions of Code.

### Remarks

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Maybe #106042. Are you using the latest Insiders?

**Comment by zawys** [comment]
Probably duplicate. Cannot reproduce this in latest Insiders.
