### ISSUE TITLE
net::ERR_PROXY_CONNECTION_FAILED

### ISSUE THREAD

**Issue by URDEY** [microsoft/vscode#106143]

**Comment by URDEY** [comment]
when check for VS updates net::ERR_PROXY_CONNECTION_FAILED it  problem  started from npm 
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/gatsby-cli failed, reason: getaddrinfo ENOTFOUND proxyhostname
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by aeschli** [comment]
Can you give reproducible steps (1... 2... 3...) that cause the issue? Where do you see this problem?
