### ISSUE TITLE
Recently opened list not showing in taskbar

### ISSUE THREAD

**Issue by Hamza141** [microsoft/vscode#106140]
- VSCode Version: 1.48.2
- OS Version: Windows 10 1803

Steps to Reproduce:
N/A

Does this issue occur when all extensions are disabled?: N/A

The "recently opened files and folders" list has disappeared from the VS Code taskbar pin. I only noticed this issue recently and have tried uninstalling and reinstalling vs code but to no avail. 

Pinned folders were still showing in that list but I decided to remove them to try and fix this issue but it didn't work and now I'm stuck like this.

![image](https://user-images.githubusercontent.com/14940503/92278831-08641980-eec4-11ea-928d-e7305da3f63d.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Hamza141** [comment]
The insider build seems to be working fine.
![image](https://user-images.githubusercontent.com/14940503/92469733-536f7c80-f1a3-11ea-905f-739c08598b67.png)

I feel like this might be an issue with windows explorer but I'm not sure.

**Comment by bpasero** [comment]
Yeah I don't think we can fix something here. I suggest you file a bug against Windows.

**Comment by Hamza141** [comment]
I was able to fix the issue by moving the old config folder (%APPDATA%\Code) and then reinstalling vscode. I'm using a mostly fresh config now, was able to get the important stuff synced back. Still not sure what caused this issue but let me know if you want to look at something from my old config.

![image](https://user-images.githubusercontent.com/14940503/92474262-89affa80-f1a9-11ea-90ba-b87dc06b246f.png)
