### ISSUE TITLE
Crashes at launch when process.env.APPDATA is not set.

### ISSUE THREAD

**Issue by jburman** [Microsoft/vscode#10616]
- VSCode Version:  1.4.0
- OS Version:  Windows 7 Prof. SP1 64-bit

![image](https://cloud.githubusercontent.com/assets/494060/17737810/b6100414-645c-11e6-84e4-32f65eabbdf4.png)

Steps to Reproduce:

1. Launch from user profile where APPDATA is missing

**Comment by joaomoreno** [comment]
@jburman Is there another variable that does the job that `APPDATA` would be doing?

**Comment by jburman** [comment]
@joaomoreno  I don't have a good suggestion for a replacement, and it looks like this just occurred due to a bungled profile update by our IT department. Once I found where the error was coming from I was able to resolve by setting the environment variable manually. I guess adding a check with a clear error message in case this happens to someone else would be helpful.

**Comment by joaomoreno** [comment]
Yes, we can check it, but there still needs to be a fallback. Is the `USERPROFILE` var set in your system?

**Comment by jburman** [comment]
Yes it is.

**Comment by joaomoreno** [comment]
And would it be safe to assume that `%USERPROFILE%\AppData\Roaming` exists on your machine?

**Comment by jburman** [comment]
Yes, it is there.

**Comment by joaomoreno** [comment]
OK so I'll make that fallback.

**Comment by bpasero** [comment]
@joaomoreno Verified, though the exact same issue happens if USERPROFILE is not defined.

**Comment by ezequias** [comment]
@bpasero @joaomoreno @jburman 
I am getting the same problem now (after installing projects extension)

Here is the extension: https://marketplace.visualstudio.com/items?itemName=bukas.projects

![image](https://user-images.githubusercontent.com/539561/29226338-0380c416-7ea8-11e7-9b69-6a87349cdad1.png)

**Comment by Mattgyver317** [comment]
Do a reinstall if this event occurred right after a Java update on your local PC. 
-> https://code.visualstudio.com/download
