### ISSUE TITLE
LSP: Go to definition reports two definitions when there is only one

### ISSUE THREAD

**Issue by digama0** [microsoft/vscode#106177]
- VSCode Version: 1.48.2
- OS Version: Ubuntu 19.10

I am working on a custom LSP server. When I ctrl-hover over a definition (which has only one target), the tooltip says "Click to show 2 definitions." instead of showing the definition target:

![lsp-definition-bug](https://user-images.githubusercontent.com/868588/92315846-a3cabc80-efa0-11ea-8fb2-361ea7758894.png)

Using Peek Definition shows that there is indeed only one target:

![lsp-definition-bug-2](https://user-images.githubusercontent.com/868588/92315902-513dd000-efa1-11ea-9060-bdc46b4bea69.png)

The relevant LSP traffic looks like this:
```json
<== {
  "jsonrpc": "2.0",
  "id": 4,
  "method": "textDocument/definition",
  "params": {
    "textDocument": {
      "uri": "file:///example/test.mm1"
    },
    "position": {
      "line": 4,
      "character": 4
    }
  }
}
<== {
  "jsonrpc": "2.0",
  "id": 5,
  "method": "textDocument/definition",
  "params": {
    "textDocument": {
      "uri": "file:///example/test.mm1"
    },
    "position": {
      "line": 4,
      "character": 4
    }
  }
}
==> {
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "range": {
      "end": {
        "character": 11,
        "line": 1
      },
      "start": {
        "character": 8,
        "line": 1
      }
    },
    "uri": "file:///example/test.mm1"
  }
}
==> {
  "jsonrpc": "2.0",
  "id": 5,
  "result": {
    "range": {
      "end": {
        "character": 11,
        "line": 1
      },
      "start": {
        "character": 8,
        "line": 1
      }
    },
    "uri": "file:///example/test.mm1"
  }
}
```
I don't know why the client makes the `textDocument/definition` request twice (and they are interleaved like this), but I believe the server's responses are correct. I also don't know whether the error is in vscode or [vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node).

**Comment by jrieken** [comment]
No clue what's happing here. Can you attach an extension that reproduces this without LSP usage, pure vscode.d.ts usage?

**Comment by dbaeumer** [comment]
@digama0 could it be that you have register for `textDocument/definition` twice?

**Comment by digama0** [comment]
@dbaeumer Aha, I think you are on to something. I didn't mention it in this report but I'm trying to figure out how to use the new `LocationLink[]` response type. I set `definition_provider: true` in the initialization response, and if `text_document.definition.link_support` is not set in the client capabilities (which it isn't) and `text_document.definition.dynamic_registration: true` is set (which it is), then I send a dynamic registration for `textDocument/definition`, with the hopes that this will turn on link support. It doesn't seem to help, but it's probably what causes the double response.

**Comment by digama0** [comment]
Confirmed that with the dynamic registration turned off it doesn't send double requests. But then how do I turn on `link_support`? Does vscode not support it, and if it does then why isn't it set in the client capabilities? To be clear, the message I get from vscode looks like this:

```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "method": "initialize",
  "params": {
    "capabilities": {
      "textDocument": {
        "definition": {
          "dynamicRegistration": true
        },
        "..."
      },
      "..."
    },
    "..."
  }
}
```

I have tried sending location links like this:
```json
<== {
  "jsonrpc": "2.0",
  "id": 4,
  "method": "textDocument/definition",
  "params": {
    "textDocument": {
      "uri": "file:///example/test.mm1"
    },
    "position": {
      "line": 4,
      "character": 4
    }
  }
}
==> {
  "jsonrpc": "2.0",
  "id": 4,
  "result": [
    {
      "originSelectionRange": {
        "end": {
          "character": 6,
          "line": 4
        },
        "start": {
          "character": 3,
          "line": 4
        }
      },
      "targetRange": {
        "end": {
          "character": 13,
          "line": 1
        },
        "start": {
          "character": 2,
          "line": 1
        }
      },
      "targetSelectionRange": {
        "end": {
          "character": 11,
          "line": 1
        },
        "start": {
          "character": 8,
          "line": 1
        }
      },
      "targetUri": "file:///example/test.mm1"
    }
  ]
}
```

However the behavior is much worse: ctrl clicking doesn't work at all, and F12 gives `Cannot read property 'startLineNumber' of undefined`. Issue #12353 describes a similar problem that seems to suggest that the JSON structure here is not correct, but from reading the LSP specification I can't tell how the `params` argument here is not a valid `LocationLink[]`.

**Comment by dbaeumer** [comment]
Which version of the LSP libraries are you using? The `linkSupport` is enabled here: https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/common/client.ts#L1664

**Comment by digama0** [comment]
While investigating this issue, I upgraded `"vscode-languageclient": "^4.2.0"` to `"vscode-languageclient": "^6.1.3"`. I don't have a dependency on `vscode-languageserver-node`, should I?

**Comment by digama0** [comment]
I confirmed it was an update issue (apparently the vscode build action doesn't run `npm update`, I must be spoiled from other languages...) Location links don't crash and burn now, but they stlll don't have the right underlining:

![lsp-definition-bug-3](https://user-images.githubusercontent.com/868588/92500482-0e9f1200-f1b2-11ea-9c96-1d913ab3f261.png)

In this screenshot, the server is saying that the `originSelectionRange` is the span of `foo/bar` on line 4, but as you can see vscode is only highlighting the `bar` part of the word. (Yes I know there are other ways to get vscode to guess the right span by setting word characters, here I'm specifically testing the `originSelectionRange` highlighting. In my application I can't set word characters because there are two nested languages and one of them has a more permissive identifier convention than the other.)

The mouseover is also very strange (the `targetRange` is only the `(def (foo/bar))` text on line 2), but that's probably another issue.

**Comment by dbaeumer** [comment]
The as been some additional problems with links due to some VS Code and LSP bugs. Can you try the latest next release which is `7.0.0-next.9`

**Comment by digama0** [comment]
I upgraded (I know the upgrade worked this time because it was a breaking change, but besides a changed import path nothing had to change), and the behavior is the same on both the incorrect span and the over-long hover text.

**Comment by dbaeumer** [comment]
@mjbvz can you please comment on the VS Code bahvior?

**Comment by mjbvz** [comment]
@digama0 Can you share an extension that causes this using just the VS Code apis along with steps to reproduce the problem?
