### ISSUE TITLE
Showing TODO items in Problems window

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#10612]
- VSCode Version: Code - Insiders 1.5.0-insider (55168276e4c0b6ec2404ac20af04eeed5f5b1000, 2016-08-17T06:04:29.075Z)
- OS Version: Darwin x64 15.6.0

Would be nice to be able to see all `@TODO` in 
![image](https://cloud.githubusercontent.com/assets/1723815/17735500/7d927542-6450-11e6-85be-240ea3553bad.png) (similar to errors and warnings)

**Comment by mrmlnc** [comment]
Maybe https://marketplace.visualstudio.com/items?itemName=minhthai.vscode-todo-parser?

**Comment by kjwatke** [comment]
This sounds like a great idea, I'd also like to see the todos highlighted in a different color, that makes it stand out from other comments. Currently, you can't tell the difference between a ``` //comment``` and a ```// TODO: do something``` without actually reading the comments.

**Comment by koutsenko** [comment]
Sample screenshot is here, taken from Eclipse IDE.
Please add it to VSCode also. Thanks
![2017-09-25 16 45 05](https://user-images.githubusercontent.com/529293/30812907-b14ffaa0-a214-11e7-80c5-51b6a5e424a3.png)

**Comment by mjbvz** [comment]
Closing as this can be provided by an extension. [This one](https://marketplace.visualstudio.com/items?itemName=minhthai.vscode-todo-parser) seems to already have this functionality
