### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by d00fensmertz** [microsoft/vscode#106144]
Issue Type: <b>Performance Issue</b>

When entering commands in the terminal, I recieve this error for almost any command I enter.
 bash: /c/Users/aidan/AppData/Local/Microsoft/WindowsApps/python: Permission denied

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    77	  5616	code main
    0	    67	  1224	   window (Issue Reporter)
    0	    72	  3524	   shared-process
    0	    25	  7632	   utility
    0	   124	 11452	   gpu-process
    0	    14	 20184	   electron-crash-reporter
    0	   164	 20440	   window (Welcome - Visual Studio Code)
    0	     5	 10188	     "C:\Program Files\Git\bin\bash.exe"
    0	    10	 13640	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	    59	 12508	     extensionHost
    0	     6	 16904	     console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.8.106424

</details>

**Comment by Tyriar** [comment]
Can you share your settings.json file? Also do you have anti-virus software that could be messing with it?
