### ISSUE TITLE
The Source Control view displays arrow signs for repos which don't even have any changes

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#106158]
- VSCode Version: **_1.48.2_**
- OS Version: **_Windows 10 Enterprise_**

Steps to Reproduce:

1. Open multiple repos in VSCode, for example I've a few dozens of repos opening in the same VSCode work space.
2. Observed that for those repos, in the version `1.48.2`, the Source Control view now displays an arrow sign at the most left for each of them, even for those don't have any changes! For example in the below screenshot, only **a few** repos actually have changes, but here we cannot easily tell will two they are which is extremely **inconvenient**.
![image](https://user-images.githubusercontent.com/19678455/92302951-a9d29480-efc4-11ea-918a-c2536772d33a.png)
3. When opening the same work space in `1.47.3`, it displays an arrow sign at the most left in each row **only** for repos which do have changes, but not for those which don't. This is very **convenient** to spot which repos have changes and which don't. It's so much **better**. The below screenshot shows clearly that 4 repos have changes.
![image](https://user-images.githubusercontent.com/19678455/92303231-f919c480-efc6-11ea-93aa-d4896aa2bd9f.png)

Please revert this behaviour in `1.48.2` to `1.47.3`, it'd be much more helpful. Thanks,

BTW, before `1.47.0`, as shown below, at least the visual effect for spotting changes looks even nicer, IMHO.
![image](https://user-images.githubusercontent.com/19678455/92303400-8b6e9800-efc8-11ea-946c-4679e20952c0.png)

**Comment by joaomoreno** [comment]
This is fixed in Insiders: you can show the Source Control Repositories view and control this visibility yourself again. It will be released on the next stable.

**Comment by cateyes99** [comment]
@joaomoreno I just downloaded `VSCode 1.49.0 Insiders`. Only see a new setting called `scm.repositories.visible` added as shown below, but not to control the arrow signs. So which new setting has been added to control the arrow signs?
![image](https://user-images.githubusercontent.com/19678455/92380761-ceae3f80-f15d-11ea-8dde-155d2ef0c219.png)

**Comment by joaomoreno** [comment]
Oh I see what you mean. The arrows were set to always show on repositories to help with consistency in understanding which rows are repositories. UX feedback drove us there. Sorry about that.

For that amount of repositories, I suggest you simply use the Source Control Repositories view.

**Comment by cateyes99** [comment]
I actually think that the new way _regarding displaying the arrows_ is **worse** in terms of UX 🙄 🤣 , comparing to the `1.47.3` way which does provide the convenience, and tidy view.
