### ISSUE TITLE
php

### ISSUE THREAD

**Issue by chriscp-cat** [microsoft/vscode#106171]
- VSCode Version:1.48.2 (user setup)
- OS Version:Windows_NT x64 10.0.18363

Steps to Reproduce:
This code will make PHP highlight the exception
``$this->sql = "INSERT INTO `" . $this->table . '`' . $dataStr . ' VALUES ' . $valueStr;``

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
It's not clear what your issue is, what is wrong? But there are other issues regarding sql highlighting inside PHP, and I am guessing yours is covered by one of those.

https://github.com/atom/language-php/issues?q=is%3Aissue+is%3Aopen+sql
