### ISSUE TITLE
Remove disabled breakpoints

### ISSUE THREAD

**Issue by kosciuk** [microsoft/vscode#106180]
Searched for words in title, nothing found.

On right click there are "Remove breakpoint" and "Remove All Breakpoints", I suggest : "Remove (only) disabled breakpoints"

Thanks

**Comment by isidorn** [comment]
We will not add this to the core. Closing this as an extension candidate, since an extension could use the vscode api to get all breakpoints check which are disabled and then use the `removeBreakpoints` api to only remove the disabled ones

**Comment by kosciuk** [comment]
Ok, I'll try to add this to my todo list. Thank you
