### ISSUE TITLE
Integrated terminal not working.

### ISSUE THREAD

**Issue by imhasib062** [microsoft/vscode#106181]
Like:
git bash, git cmd, msys64 integrated terminal even no third party terminal working in my machine with vs code.
just give me this message👇🏻
![Screenshot 2020-09-06 112812](https://user-images.githubusercontent.com/50325055/92318938-ec33ba00-f034-11ea-915c-f5176cf0b11d.jpg)
My vs code user setting is:👇🏻
{
    "code-runner.runInTerminal": true,
    "code-runner.saveFileBeforeRun": true,
    "C_Cpp.updateChannel": "Insiders",
    "githubPullRequests.queries": [
        {
            "label": "Waiting For My Review",
            "query": "is:open review-requested:${user}"
        },
        {
            "label": "Assigned To Me",
            "query": "is:open assignee:${user}"
        },
        {
            "label": "Created By Me",
            "query": "is:open author:${user}"
        },
        {
            "label": "Mentioned Me",
            "query": "is:open mentions:${user}"
        }
    ],
    "liveshare.guestApprovalRequired": true,
    "liveshare.joinDebugSessionOption":"Automatic",
    "json.schemas": [
        {
          "fileMatch": [
            "/receipts/*.json",
            "!/receipts/*.excluded.json"
          ],
          "url": "./receipts.schema.json"
        }
      ],
      //PowerShell-7
    //"terminal.integrated.shell.windows": "E:\\Program Files\\PowerShell\\7\\pwsh.exe",
    //GitBash
    //"terminal.integrated.shell.windows": "E:\\Program Files\\Git\\bin\\bash.exe",
    // Command Prompt
    //"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    // PowerShell
    //"terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "workbench.editor.highlightModifiedTabs": true,
    // Windows/Linux
    "key": "ctrl+f", "command": "-workbench.action.terminal.focusFindWidget",
    "when": "terminalFocus",
    "explorer.confirmDelete": false,
    "editor.renderControlCharacters": true,
    // Controls if the pressing tab inserts the best suggestion and if the tab cycles through other suggestions
    "editor.tabCompletion": "on",
      // Controls whether sorting favors words that appear close to the cursor
      "editor.suggest.localityBonus": true,

      // Controls how suggestions are pre-selected when showing the suggested list
      "editor.suggestSelection": "first",
  
      // Enable word-based suggestions
      "editor.wordBasedSuggestions": true,
  
      // Enable parameter hints
      "editor.parameterHints.enabled": true,
      // Controls whether suggestions should be accepted on commit characters. For example, in JavaScript, the semi-colon (`;`) can be a committed character that accepts a suggestion and types that character.
    "editor.acceptSuggestionOnCommitCharacter": true,

    // Controls if suggestions should be accepted on 'Enter' - in addition to 'Tab'. Helps to avoid ambiguity between inserting new lines or accepting suggestions. The value 'smart' means only accept a suggestion with entering when it makes a textual change
    "editor.acceptSuggestionOnEnter": "on",

    // Controls the delay in ms after which quick suggestions will show up.
    "editor.quickSuggestionsDelay": 10,

    // Controls if suggestions should automatically show up when typing trigger characters
    "editor.suggestOnTriggerCharacters": true,
     // Controls if quick suggestions should show up while typing
     "editor.quickSuggestions": {
      "other": true,
      "comments": true,
      "strings": true
  },
  "window.zoomLevel": 0,
  "workbench.colorTheme": "Visual Studio Dark",
  "java.configuration.runtimes": [
    {
      "name": "JavaSE-1.8",
      "path": "/path/to/jdk-8"
    },
    {
      "name": "JavaSE-11",
      "path": "/path/to/jdk-11"
    },
    {
      "name": "JavaSE-14",
      "path": "/path/to/jdk-14",
      "default": true
    }
  ],
  "files.exclude": {
    "**/.classpath": true,
    "**/.project": true,
    "**/.settings": true,
    "**/.factorypath": true
  },
  "git.autofetch": true,
  "vsintellicode.modify.editor.suggestSelection": "choseToUpdateConfiguration",
  "python.languageServer": "Microsoft",
  "python.pythonPath": "E:\\Program Files\\Python38\\python.exe",
  //New load Here:
  "terminal.integrated.shell.windows": "E:\\Program Files\\Git\\git-cmd.exe",
"terminal.integrated.shellArgs.windows": [
  "--command=usr/bin/bash.exe",
  "-l",
  "-i"
]
}
And my system environment path is:👇🏻
![Screenshot 2020-09-06 113617](https://user-images.githubusercontent.com/50325055/92318966-3cab1780-f035-11ea-83a8-60166b1f1970.jpg)
I don't know why this happens but I tried heart and soul for the fix but still, I'm failing with this.
&
my system info is:
![Screenshot 2020-09-06 114138](https://user-images.githubusercontent.com/50325055/92319035-0a4dea00-f036-11ea-9714-49539b800e5c.jpg)
&&
my vs code extensions are:
![Screenshot 2020-09-06 114304](https://user-images.githubusercontent.com/50325055/92319048-2782b880-f036-11ea-9e8f-2cb7ae19e116.jpg)

**Comment by Tyriar** [comment]
You've messed up the quotes in your command
