### ISSUE TITLE
[Nodejs debugging bug] When I hit a breakpoint vscode opens a new readonly version of the file, breakpoints not shown in gutter

### ISSUE THREAD

**Issue by RaniSharim** [Microsoft/vscode#10610]
- VSCode Version: 1.4.0 - it didn't happen in older versions.
- OS Version: windows 10

Whenever I hit a breakpoint, vscode halts on a new "tab" with a readonly version of the file with the full path instead of the local path, and sometimes doesn't display all the breakpoints I've set.

Does this happen to anyone else?

Example images:
![before_hitting_breakpoint](https://cloud.githubusercontent.com/assets/963221/17734403/add0491c-6484-11e6-9ea3-9445a2f9b3c5.png)
![after_hitting_breakpoint](https://cloud.githubusercontent.com/assets/963221/17734404/add15e2e-6484-11e6-959e-e1847a85fed4.png)

Steps to Reproduce:
Not sure - I tried it in a new project and couldn't reproduce.
In my project it's as simple as hitting a breakpoint on a function.

**Comment by mpartipilo** [comment]
+1
Happens to me too. I actually downgraded to 1.3.0 until the next release.

**Comment by weinand** [comment]
Could you please provide what OS you are using and reproducible steps. A project on github or a zip would be ideal.

**Comment by mpartipilo** [comment]
Windows 10, on a nodejs project.
Can't provide code, sorry.
Will try to reproduce on a clean or oss project and post steps tomorrow.

**Comment by weinand** [comment]
@mpartipilo just a single file project where you experience the problem would be very helpful. Thanks a lot!

**Comment by RaniSharim** [comment]
Also, setting breakpoints in this "new" file sometimes, when hitting restart, makes it just be stuck until you clear the breakpoint.

**Comment by RaniSharim** [comment]
Ok, I played with it a little. It seems to be an issue with the file itself - maybe attributes, maybe security, can't figure it out.

What I did:

This **did not** have a problem:
1. created a new project
2. copy&paste the **content** of one of the files which are having the problem.

This **did** have a problem:
1. new project
2. copy&paste the **file itself** from the old problematic project to the new project.

I'm thinking maybe it's an issue with git clone/pull?

This is the repository with the "bad" file : https://github.com/RaniSharim/testproject.git
the file is routes/officemanagement.js
I hope whatever is fucked up stays fucked up so you can check it.

Thanks.

**Comment by mpartipilo** [comment]
Still happening in 1.5.2 on Windows, Node version 4.4.4.

I also notice the added code at the start of the readonly buffer that @RaniSharim reports.

**Comment by RaniSharim** [comment]
Any word about this?

**Comment by mpartipilo** [comment]
@RaniSharim I will try your test repo and report if I can reproduce the problem.

**Comment by RaniSharim** [comment]
In file 
\src\vs\workbench\parts\debug\electron-browser\debugService.ts
Function openOrRevealSource

The parameter source.uri.toString() value is
"debug://internal/1000/c%3A%5CUsers%5Caharon%5CDocuments%5CVisual%20Studio%202013%5CProjects%5Cmrs%5Cmrs%5Clogic%5Cpriceoffers%5Cpriceoffers.js"

Where as the editor's fileInput.getResource().toString() is
"file:///c%3A/Users/aharon/Documents/Visual%20Studio%202013/Projects/mrs/mrs/logic/priceoffers/priceoffers.js"

Problem is the source uri but I have no idea where it is set/determined,

**Comment by RaniSharim** [comment]
Well, I've figured it is a problem with vscode-node-debug.
If you look at \src\vs\workbench\parts\debug\common\debugModel.ts
function getCallStackImpl line 145, you can see "source" is missing is the stack frame

**Comment by RaniSharim** [comment]
Anything? Please?

**Comment by goodlifeinc** [comment]
It happens to me for only one specific file in the whole project.
Tried loading the project from different directory, which didn't help.
The same file is opened as Read-Only when I hit a debug point inside it.

**Comment by weinand** [comment]
@RaniSharim the file officemanagement.js is the only file in the testproject that uses a "BOM" (Byte Order Mark). This can be seen in the status bar:

![2017-02-16_15-59-58](https://cloud.githubusercontent.com/assets/1898161/23026346/4546d6d2-f461-11e6-8d79-b1d9fbbf36ae.png)

This BOM confuses the code in the node debugger that tries to match a file loaded into node.js to a file in the workspace. As a result the match fails and VS Code falls back to showing the file loaded into node.js instead of showing the workspace file. Since the loaded file does not come from a filesystem it is opened in read-only mode.

BTW, you can easily see the origin of the editor content in the header (but only if the workbench is not in "tab" mode):

![2017-02-16_16-08-47](https://cloud.githubusercontent.com/assets/1898161/23026812/bb594430-f462-11e6-892b-1f31e4b382ee.png)

**Comment by mpartipilo** [comment]
This is great news!

**Comment by weinand** [comment]
@roblourens FYI, make sure to strip the BOM when reading utf-8 files that happen to use a BOM...

**Comment by aeschli** [comment]
Verified with https://github.com/RaniSharim/testproject.git that officemanagement is no longer opened as read-only file.
