### ISSUE TITLE
Everything is Blurry 

### ISSUE THREAD

**Issue by yenerorer** [microsoft/vscode#106174]
![Capture](https://user-images.githubusercontent.com/15785200/92313651-c7a8f500-efd6-11ea-9251-b9ba78c0feb5.PNG)
Issue Type: <b>Bug</b>

Everything on the screen is blurry!

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (7.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.14.0
flutter|Dar|3.14.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
beautify|Hoo|1.5.0
vscode-line-endings|jha|0.2.0
vscode-nuget-package-manager|jmr|1.1.6
vscode-scss|mrm|0.9.0
debugger-for-chrome|msj|4.12.10
vscode-scss-formatter|sib|2.0.2
quokka-vscode|Wal|1.0.317
local-history|xyz|1.8.1

</details>

**Comment by deepak1556** [comment]
Can you confirm if the issue persists with latest insiders https://code.visualstudio.com/insiders/ 

Also can you check if the following launch options fixes the issue

1) `code --disable-extensions`
2) `code --disable-gpu`
