### ISSUE TITLE
Execution spinner hung - Native notebooks

### ISSUE THREAD

**Issue by jilljac** [microsoft/vscode#106142]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. ran all cells, only first 3 cells show running state
2. spinner keeps spinning but timer is not increasing
3. restart kernel was not available. Happened again after interrupting kernel through command palette

<img width="1893" alt="Screen Shot 2020-09-04 at 1 53 25 PM" src="https://user-images.githubusercontent.com/60361194/92284255-83bece80-eeb6-11ea-8b7c-c373c2ca7820.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Issues like this should go to the python extension first, because it is in control of how the cell execution state appears.
