### ISSUE TITLE
Search causes WSL to die

### ISSUE THREAD

**Issue by ccarlsonpb** [microsoft/vscode#106139]
Issue Type: <b>Bug</b>

Not sure if this is a vscode issue or a WSL issue, but every couple of days, I'll do a search in vscode and every WSL process I have will terminate. All terminals I have open (unrelated to vscode) will be terminated, docker will crash, etc. I'm reporting this as a vscode issue because it only happens when I do a vscode search. I have not seen this issue caused by anything else, so I can only assume vscode is doing something strange under the hood. I don't know how to reproduce the issue - I can search fine 99% of the time, but searching seems to randomly trigger this, and it doesn't seem related to the specific search text.

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.20170
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2903)|
|Memory (System)|12.36GB (11.99GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
gitlens|eam|10.2.2
path-autocomplete|ion|1.15.0
vsc-python-indent|Kev|1.11.0
select-highlight-minimap|mde|0.0.8
python|ms-|2020.8.105369
psi-header|psi|1.13.1
vscode-yaml|red|0.10.1

</details>

**Comment by roblourens** [comment]
Sorry, I have no clue. Any idea @aeschli?

**Comment by ccarlsonpb** [comment]
@roblourens I don't know what qualifies as a "really large workspace". It's basically just a few python packages and some build scripts, though upon closer inspection there are _a lot_ of build artifacts; the directory is 2.4GB across ~100k files in ~13k folders. My search is only looking at *.py files, however, which would barely be in the hundreds. That being said, searching is virtually instantaneous for me, even with all of the junk. My machine has 16GB of RAM which I assume is sufficient. I have noticed that when I'm running docker, WSL tends to consume a ton of memory (~11GB at times) and sometimes not give it back until I manually flush the caches. I suppose it's possible that I am running out of memory when these crashes occur, but I haven't paid close enough attention.

**Comment by ccarlsonpb** [comment]
Update: the issue happened again, but this time I noticed some more details. When I pressed CTRL+SHIFT+F to search for a string, the query box became populated with an entire block of code that I happened to have selected, not what I was trying to search. Immediately after, I pasted in my actual query, and then everything crashed. I tried replicating this scenario and it did not cause a crash. It seems like the root cause is related to vscode being open for days prior.

**Comment by roblourens** [comment]
You could see if disabling the "search on type" setting helps - there have been some other reports of issues with search that seem to improve with this.

**Comment by aeschli** [comment]
You write that the WSL terminals terminate, so this shoulds like file i/o issue with WSL.
Are you searching on a /mnt/ mount? 

Would you mind filing an issue against https://github.com/microsoft/WSL ?

**Comment by ccarlsonpb** [comment]
@aeschli it is indeed a /mnt/ mount. I filed a separate issue here https://github.com/microsoft/WSL/issues/5939

**Comment by ccarlsonpb** [comment]
So I managed to have it crash under different circumstances. This time, I attempted to format my document (SHIFT + ALT + F) and it died, but additionally, it also failed to restart afterwards. One thing I noticed was that my CPU usage was maxed out after it crashed, with vscode being the main culprit. Docker also failed to restart, but once I killed docker, I was able to restart vscode, and resource consumption went back down.

![image](https://user-images.githubusercontent.com/32461199/94722492-60f0d000-0325-11eb-8393-c3e943f1f1d5.png)

**Comment by roblourens** [comment]
It sounds like this is being discussed in the upstream issue. I'm not sure what you are saying about Docker though, is it possible that your machine is just memory constrained?

**Comment by ccarlsonpb** [comment]
In this specific instance, memory consumption dropped when everything crashed, but CPU usage spiked due to vscode restarting. I assume it's rebuilding some kind of cache at that stage? Anyways, docker was also restarting and this maxed out my CPU and seemed to deadlock both processes. I killed docker which allowed vscode to finish, and then I was able to restart docker without issue.
