### ISSUE TITLE
Gopath in Extension Development Host

### ISSUE THREAD

**Issue by MattiasPernhult** [Microsoft/vscode#1061]
Sometimes when opening the Extension Development Host to debug custom extensions and the active file is a golang file it will give the following error:  **"Path must be a string. Received ..."**

The call stack looks like this:
![skarmavbild 2015-12-07 kl 10 07 35](https://cloud.githubusercontent.com/assets/7289303/11623039/601d84be-9cca-11e5-8281-97b8f3d27643.png)

As I mentioned this doesn't happens all the time.

**Comment by egamma** [comment]
From the call stack it looks like this is vscode-go initiated.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-go#147
