### ISSUE TITLE
Proxy popup makes whole VSCode to freeze - Not able to use VSCode 

### ISSUE THREAD

**Issue by saumyasuhagiya** [microsoft/vscode#106100]
- VSCode Version: Not able to find out because its unresponsive
- OS Version: Mac OS 10.15.6

Steps to Reproduce:

1. Connect to VPN on Mac 

2. Open VS Code 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

<img width="1040" alt="Screenshot 2020-09-04 at 2 23 42 PM" src="https://user-images.githubusercontent.com/2899428/92222749-18c4c600-eebd-11ea-939f-14082a3d62b5.png">

**Comment by weinand** [comment]
What happens if you do not start VPN and then start VS Code?

**Comment by saumyasuhagiya** [comment]
Hi @weinand, it works fine in non vm mode. I think it happens when it tries to update VSCode.
