### ISSUE TITLE
Replace Preview previews the replacement of multiple strings instead of just one

### ISSUE THREAD

**Issue by jgaehring** [microsoft/vscode#106160]
- VSCode Version:
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Create a line of code with a text string repeated twice
2. Search all files for the text string
3. Add a replacement string
4. Click on the file to preview the first replacement
5. The first _and second_ replacement are previewed, instead of just the first (see screenshot below)

![image](https://user-images.githubusercontent.com/5556545/92305857-04360b80-ef59-11ea-8ad3-7615a3baa7b7.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by AlexandroGonSan** [comment]
1. Isso não é um erro , a segunda string está realçada para indicar seleção .
2. Se isso resolve o seu problema , feche esse issue .

* Don't ask me to write in english , use Chrome .

**Comment by jgaehring** [comment]
Well, what seemed odd to me, and I don't know if this is a bug or not, but the second string is not only highlighted, but also the replace operation has been run on it. This seems wrong to me. When you actually do run "Replace", it is not changed, but it seems very intuitive.

Hope this is helpful, just did not seem like the expected behavior, but if it is, I'm happy to close this.

**Comment by sandy081** [comment]
This is expected. Preview shows all entries in the file and not specific to an entry and the action perform replace on selected entry.
