### ISSUE TITLE
Add warning when "undo" would leave current tab / file.  

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/vscode#106192]
**Feature Request:** Add a setting to warn when the *next* undo would take you out of the tab you're currently in.

**Currently** when you undo repeatedly, if your undo history spans multiple tabs, the act of undoing switches focus to another file or tab and keeps undoing there.  

**Use case**: Often, however, I just want to undo what I've done in the *current* tab, so I undo repeatedly -- but then I have to *redo* once the editor jumps over to the next tab / file.  

 **Meta**: The way Feature Requests work is a little opaque (#90091) so I'll just mention: if you support this FR, add your thumbs up on the first post.  If it gets to 20 votes in 60 days, it gets accepted.

**Comment by bpasero** [comment]
@ultraGentle 

> Currently when you undo repeatedly, if your undo history spans multiple tabs, the act of undoing switches focus to another file or tab and keeps undoing there.

How do you trigger that? Can you record a screen cast.

**Comment by ultraGentle** [comment]
@bpasero If I can catch it in action, I'll certainly record.  Might take a little while.

**Comment by bpasero** [comment]
Thanks
