### ISSUE TITLE
Allow contextually visible whitespace

### ISSUE THREAD

**Issue by Tarmean** [microsoft/vscode#106125]
I would love a Render Whitespace setting that only renders outliers as visible. Since vscode already does indentation detection a fairly intuitive implementation seems possible:

Use the local Insert Spaces setting. 

- if it is true, render visible tabs but invisible spaces
- if it is false, render  visible spaces but invisible tabs

This is inspired by vims listchars option: http://vimdoc.sourceforge.net/htmldoc/options.html#'listchars'

To give an example the following configuration is unobstrusive when spaces are used but makes tabs or trailing spaces visible:

    set listchars=tab:␉·,trail:␠,nbsp:⎵

![vim example](https://user-images.githubusercontent.com/11866759/92253259-9265af80-eecf-11ea-8ad4-725fbac4d3c2.png)

**Comment by hediet** [comment]
What setting names would you suggest? Another option in `editor.renderWhitespace`?
