### ISSUE TITLE
In configuration properties, make enum and enumDescriptions behave like an HTML select element

### ISSUE THREAD

**Issue by johnbillion** [microsoft/vscode#106133]
When an extension registers a configuration property as an enum, its representation on the Settings screen is unexpected and unusual. Here's my configuration:

```json
{
  "type": "string",
  "enum": [
    "",
    "7.0",
    "5.6"
  ],
  "enumDescriptions": [
    "None",
    "PHP 7.0+",
    "PHP 5.6+"
  ]
}
```

I was expecting this to result in a dropdown menu which shows the values from `enumDescription` as the user-visible labels, and uses the values from `enum` as the values stored in the settings when the option is selected.

Instead the values from `enum` are both shown to the user and stored in the settings, and the values from `enumDescriptions` are shown below the dropdown when the user hovers or focuses each element.

I would like for this configuration structure to work more like a `<select>` element in HTML, which allows for a user-visible label which is different from the value that gets set as the form value. For example, given the configuration above, I would expect to see a dropdown that you might represent in HTML as:

```html
<select>
  <option value="">None</option>
  <option value="7.0">PHP 7.0+</option>
  <option value="5.6">PHP 5.6+</option>
</select>

**Comment by roblourens** [comment]
The JSON representation is used by many users so the real stored value must be considered user-friendly surface area. The settings UI is just a projection of this. So we want to show the user the real value and also the enumDescription which is like a documentation string.
