### ISSUE TITLE
Thanks folks. I've been working with @sbatten and it seems that the changes for https://github.com/microsoft/vscode/issues/85164 are related, along with the conflicting view IDs between the two extensions.

### ISSUE THREAD

**Issue by Unorthodox-Creationz** [microsoft/vscode#106187]
Thanks folks. I've been working with @sbatten and it seems that the changes for https://github.com/microsoft/vscode/issues/85164 are related, along with the conflicting view IDs between the two extensions.

**I was able to reproduce the issue with the following:**

1. Uninstall both extensions
1. Install the Docker Explorer (third party) extension first
    1. It puts the Containers and Images view in the Explorer viewlet, not in the Docker viewlet
1. Install the Docker (first party) extension
    1. Note: the extensions didn't actually have to be _installed_ in this order, just _loaded_ in this order upon launching 1.42, but installing one and then the other guarantees the load order
1. The view-moving code that @sbatten added now thinks that the Images and Containers views (which share the same ID in both extensions) belong in the Explorer viewlet, which is why they do not show up in the Docker viewlet. I suspect for most people they do actually show up in the Explorer viewlet: 
![image](https://user-images.githubusercontent.com/36966225/74542493-b650ac00-4f11-11ea-8908-11c6a3f8fc8a.png)
1. Uninstalling the Docker Explorer extension does not quite fix the problem, because the view-moving code still thinks Images and Containers belong in the Explorer viewlet, due to the conflicting IDs. Here's what I see after uninstalling the Docker Explorer extension: 
![image](https://user-images.githubusercontent.com/36966225/74542577-e304c380-4f11-11ea-9a3a-c48274867300.png) 
![image](https://user-images.githubusercontent.com/36966225/74542622-f3b53980-4f11-11ea-92a3-cdfe4cc957a1.png)

**How to fix it**
1. Uninstall the Docker Explorer (third party) extension
1. In Settings, enable the experimental feature Workbench > View > Experimental: Allow Moving To New Container (setting ID `workbench.view.experimental.allowMovingToNewContainer`)
1. In the Explorer viewlet, right click the Images and Containers views and choose Move to Panel: 
![image](https://user-images.githubusercontent.com/36966225/74542872-6f16eb00-4f12-11ea-8217-212aa6e11b39.png)
1. They should now show in the center panel, same as where terminals and output windows usually show: 
![image](https://user-images.githubusercontent.com/36966225/74542948-8e157d00-4f12-11ea-82f3-59148cbfd3fc.png)
1. Right click them there, and choose Move to Sidebar. This should return them to their proper place in the Docker viewlet: 
![image](https://user-images.githubusercontent.com/36966225/74543027-abe2e200-4f12-11ea-8a5c-3f949b0d2cdc.png)
1. If desired, you can now disable the setting from step 2.

@irbisKo , @msssk , @jwtd , can you try the fix steps above and let us know if they work?

_Originally posted by @bwateratmsft in https://github.com/microsoft/vscode-docker/issues/1609#issuecomment-586331394_

**Comment by bwateratmsft** [comment]
I'm not sure why this issue was opened here. This is a copy-paste of a comment I made on a bug filed in the Docker extension. It has already long since been fixed both there and the related issue in VSCode fixed here.
