### ISSUE TITLE
Source Control icon is not showing .

### ISSUE THREAD

**Issue by rsrpa** [microsoft/vscode#106118]
Hi, i have updated lastest git version . 
As soon as i updated that, Source control git icon is not working. 
I want to solve this problem as soon as possible . 
![image](https://user-images.githubusercontent.com/48287086/92238858-15d0d200-eecb-11ea-8a19-47369bcc94d6.png)

**Comment by soccypowa** [comment]
Is it completely gone? What happens if you press Ctrl+Shift+G? Or right-click in the sidebar, "source control" is not choosable?

**Comment by rsrpa** [comment]
I found the solution . it's working well. 
Thank you so much .

**Comment by rsrpa** [comment]
great
