### ISSUE TITLE
Unsupported screen

### ISSUE THREAD

**Issue by dhrumil3006** [microsoft/vscode#106126]
Issue Type: <b>Bug</b>

i dont know ehat issue but always window show "unsupported".

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:14:14.576Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7200  @ 2.53GHz (2 x 2527)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.24GB (1.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
save-typing|akh|0.1.0
vscode-intelephense-client|bme|1.5.4
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|5.5.0
auto-save|mcr|1.0.3
mssql|ms-|1.9.0
material-icon-theme|PKi|4.2.0
format-html-in-php|rif|1.6.3
vscode-icons|vsc|10.2.0

</details>

**Comment by gjsjohnmurray** [comment]
I think this happens when one or more of the VS Code files has been changed. Maybe try reinstalling. And/or disable all your extensions to re-test.

**Comment by weinand** [comment]
Please provide some reproducible steps:
when does the window show "unsupported"?
a screenshot of the error would be helpful too.
