### ISSUE TITLE
Unfolds All Code on Save

### ISSUE THREAD

**Issue by nicholasimon** [microsoft/vscode#106166]
Issue Type: <b>Bug</b>

Not sure why this has happened however out of the blue Visual Studio Code is now unfolding all code every time the file is saved. I have tried uninstalling/reinstalling and removing extensions though nothing has worked. 

All code is unfolded every single time the file is saved and results in a lot of lost time.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (10.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
fold-unfold-all-icone|Fer|0.0.2
go|gol|0.16.2
mark-jump|spy|0.9.0

</details>

**Comment by aeschli** [comment]
For what language is that? Can you add a small code sample? Do you have format on save enabled?

**Comment by nicholasimon** [comment]
Hi the language is GO/GOLANG, it was working perfectly for months and then it started happening. Eventually I did a clean install of Windows 10 and it was fixed. However it is now happening again for some unknown reason.  

I don't change anything, install any new extensions or anything similar and out of the blue it just unfolds all on save. I do not have FORMAT ON SAVE enabled.

some code is belo

`func drawcredits() { // MARK: drawcredits
	altcloudson = true
	rl.DrawRectangle(0, 0, monw, monh, rl.Black)
	rl.DrawRectangle(0, 0, monw, monh, rl.Fade(creditscolor, creditsfade))
	if framecount%3 == 0 {
		for a := 0; a < 20; a++ {
			rl.DrawPixel(rInt(50, monw-50), rInt(50, monh-50), rl.Black)
			rl.DrawRectangle(rInt(50, monw-50), rInt(50, monh-50), 2, 2, rl.Black)
		}
	}

	if creditsfadeon {
		creditsfade -= 0.04
		if creditsfade <= 0.0 {
			randomcolors()
			creditscolor = randomcolorslice[0]
			creditsfadeon = false
		}
	} else {
		creditsfade += 0.04
		if creditsfade >= 1.0 {
			randomcolors()
			creditscolor = randomcolorslice[0]
			creditsfadeon = true
		}
	}

	rl.DrawText("these links all helped make this game possible:", 100, 150, 40, rl.White)

	rl.DrawText("raylib.com", 150, 250, 40, rl.White)
	rl.DrawText("golang.org", 150, 300, 40, rl.White)
	rl.DrawText("opengameart.org", 150, 350, 40, rl.White)
	rl.DrawText("itch.io", 150, 400, 40, rl.White)
	rl.DrawText("kenney.nl", 150, 450, 40, rl.White)
	rl.DrawText("planets - opengameart.org/content/20-planet-sprites", 150, 500, 40, rl.White)

}`

**Comment by aeschli** [comment]
I can reproduce.

From debugging I see that the go extension now also registers a folding range provider.
However that provider doesn't work well with incomplete code. It then returns no folding ranges, what results in all folded ranges to go way.
E.g. no ranges returned for that code:
```
package main
w
import (
	"fmt"
	"io"
	"net/http"

	"github.com/microsoft/vscode-remote-try-go/hello"
)

func handle(w http.ResponseWriter, r *http.Request) {
	io.WriteString(w, hello.Hello())
}
```
Can you file the issue against the go extension? https://github.com/golang/vscode-go
Thanks a lot!
