### ISSUE TITLE
Intellisense Fault - (window.open) funtion in HTML/JavaScript

### ISSUE THREAD

**Issue by TerminatorInAction** [microsoft/vscode#106155]
```
 <button id="pkc1" class="dlink" onclick=open("https://en.wikipedia.org/wiki/Titanic_(1997_film)","_blank","width=450,height=500,left=1000,top=200");><h2>Titanic [1997]</h2></button>
```
```
<button id="pkc2" class="dlink" onclick=open("https://www.facebook.com","_blank","width=450,height=500,left=1000,top=200");><h2>Kesari [2020]</h2></button>
```
These are the two button where I used javascript function to open this link in new custom size window.
The code I witten is working properly as I want .
BUT,
Problem Tab in VS code shows that it has some error as in screenshot.
If I will follow the instruction as VS code display then code will break custom function never will open , i.e value will not pass to the function.

Note : - According to AI, these errors were fixed when I used closing parenthesis just after opening parenthesis but the fact is that it breaks my custom function.

Thanks for this outstanding app, wish you will made VS code even better for us.

![Screenshot (409)](https://user-images.githubusercontent.com/59847834/92300385-08bdec80-ef78-11ea-883d-a41446a49863.png)

**Comment by aeschli** [comment]
`onclick=open("https://www.facebook.com","_blank","width=450,height=500,left=1000,top=200");><h2>Kesari [2020]</h2></button>` is not valid.

The HTML spec forbids double quote characters in unquotesd values:
https://www.w3.org/TR/2012/WD-html-markup-20120329/syntax.html#attr-value-unquoted

I suggest to put quotes around the value:

onclick='open("https://www.facebook.com","_blank","width=450,height=500,left=1000,top=200");'><h2>Kesari [2020]</h2></button>
