### ISSUE TITLE
Strange PowerShell PS1 prompt in Code OSS

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#106107]
Top is OSS (spawned from the integrated terminal of Insiders), bottom is Insiders:

![image](https://user-images.githubusercontent.com/22350/92231158-90d6c000-eeac-11ea-9c8e-c33d4a70d880.png)

Strange 🤔

**Comment by Tyriar** [comment]
@joaomoreno do you have a profile? However the prompt is getting set could be wrapped in `Convert-Path` https://stackoverflow.com/a/14654989/1156119

@TylerLeonhardt do you know what would cause the prompt to display like this?

**Comment by TylerLeonhardt** [comment]
I'd love to know what your environment variables are:

```pwsh
Get-Item env:
```

**Comment by joaomoreno** [comment]
I saved the env on the `localhost` shell to a `bad` file: `Get-Item env: > bad`.

Then, I diffed it with the env on the good shell: `Compare-Object (Get-Content bad) (Get-Item env:) -ExcludeDifferent`

It reported no changes whatsoever. Am I doing this right?

I'm reluctant in just providing my env here on GH.

**Comment by TylerLeonhardt** [comment]
Yeah if there is no change then it's not that.

Next question is what @Tyriar said. What is inside the file that is spit out from running:

```pwsh
PS > $PROFILE
PS > $PROFILE.AllUsersAllHosts
PS > $PROFILE.AllUsersCurrentHost
PS > $PROFILE.CurrentUserAllHosts
```

**Comment by joaomoreno** [comment]
Both look exactly the same:

```
PS C:\Users\jomo\Work\vscode> $PROFILE
C:\Users\jomo\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
PS C:\Users\jomo\Work\vscode> $PROFILE.AllUsersAllHosts
C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1
PS C:\Users\jomo\Work\vscode> $PROFILE.AllUsersCurrentHost
C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell_profile.ps1
PS C:\Users\jomo\Work\vscode> $PROFILE.CurrentUserAllHosts
C:\Users\jomo\Documents\WindowsPowerShell\profile.ps1
```

@Tyriar Can you repro this on a Windows machine?

**Comment by TylerLeonhardt** [comment]
Never seen this before either. Are you on an insider ring of Windows by chance?

**Comment by joaomoreno** [comment]
Nah...

![image](https://user-images.githubusercontent.com/22350/92704510-498c7b80-f353-11ea-83b5-4062678c8678.png)

Let's close it then, since it seems I'm the only one and it doesn't affect me in any way. 👍
