### ISSUE TITLE
error en el guardar 

### ISSUE THREAD

**Issue by fernandito16** [microsoft/vscode#106178]
porque cuando escribo codigo y utilizo spacio y tabulacion cuando lo guardo se elimina las tabulaciones y espacio  automaticamente

**Comment by ericmartinezr** [comment]
Issue title: "Error when saving"

Description: "When I write code and I use spaces and tabs and I save both spaces and tabs are deleted automatically"

**Comment by aeschli** [comment]
For what language is that? Can you give a small code sample and steps to reproduce?
