### ISSUE TITLE
Explorer ASCIIbetical sort order

### ISSUE THREAD

**Issue by vimtaai** [microsoft/vscode#106194]
**Feature request**: It would be nice to have the option to sort files in the Explorer pane in ASCIIbetical order as this is the order GitHub uses. The setting could be `"explorer.sortOrder": "asciibetical"` or `"explorer.sortOrder": "github"`.

[ASCIIbetical Order](https://en.wikipedia.org/wiki/ASCII#Character_order)

**Use case**: For better integration when developing for a GitHub repo it would be nice to have the option for the same file ordering.

**Possible solution**: It could use the `noIntlCompareFileNames` function in `src/vs/base/common/comparers.ts` with the `caseSensitive` option set to `true`.

https://github.com/microsoft/vscode/blob/master/src/vs/base/common/comparers.ts#L61

**Comment by gjsjohnmurray** [comment]
Related to #27759, for which PR #97272 is currently open.
