### ISSUE TITLE
Add option to minimize/hide the commented lines. Ain't there no need to display hundreds of green not required lines. Its annoying

### ISSUE THREAD

**Issue by Saba101** [microsoft/vscode#106112]
- VSCode Version: 1.48.2
- OS Version: Windows_NT x64 10.0.18363

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
Did you try using the `Fold All Block Comments` command?

**Comment by Saba101** [comment]
> Did you try using the `Fold All Block Comments` command?
Yes i tried.. doesn't really works.
