### ISSUE TITLE
VS github "Show fixes" too small to read

### ISSUE THREAD

**Issue by mjw99** [microsoft/vscode#106104]
Dear Support,

I have just been playing with Codespaces with a Java Maven project. I have found it very useful and interesting thus far, however, the "Show Fixes" (next to bulb, after hover in code) tips are often truncated at a few words, hence you have to apply them and then work out what they did. It would also be useful to have a complete enumeration of these "Show Fixes" in another pane, instead of hovering near code to see if there is actually a tip.

Thanks,

Mark

**Comment by mjbvz** [comment]
Can you share a screenshot of the problem

Also please fill in the issue template so we know what OS and VS Code version you are on. /needsMoreInfo

**Comment by mjw99** [comment]
Thanks, I am using Ubuntu 20.04 with FF 80.0.1
![codespaces_issue_mjw99](https://user-images.githubusercontent.com/1921009/92497532-5f822b00-f1f1-11ea-9a86-87279ce67e68.png)

**Comment by mjbvz** [comment]
Thanks. Which part is too small? The lightbulb itself?

**Comment by mjw99** [comment]
Thanks for looking at this Matt. In the above screenshot, it's specifically, the truncation of the tip box "Move 'HGPTwoElectronTerm'...". It's not clear where to move to and hovering over that box does not expand it.

**Comment by mjbvz** [comment]
This is with the Java extension right? Can you please steps to reproduce this (including example code as text)

**Comment by mjw99** [comment]
Yes; with the Java extension. Here are the steps to reproduce this:

0) Using Ubuntu 20.04.1 and Firefox 80.0.1 (64-bit) on x86_64
1) Go to https://github.com/mjw99/jquante landing page
2) Select "Open with Codespaces" from green code pulldown on right 
3) Select  mjw99-jquante-jf3f (this should be on the vs_testing branch)
4) From left panel, select "Java Projects"
5) Navigate to /src/main/java
6) Navigate to the name.mjw.jquante.math.qm.integral package
7) Open the HGPTwoElectronTerm class 
8) In the middle pane, hover on the lightbulb around line 24 and then click it

**Comment by mjbvz** [comment]
This is caused by the Java extension.

Here's the code action data that it returns to VS Code:

<img width="643" alt="Screen Shot 2020-09-28 at 3 34 29 PM" src="https://user-images.githubusercontent.com/12821956/94492901-2f023100-01a0-11eb-99c5-24683e6bfa09.png">

You can see that the `...` is included in the title.

Please try filing this against the Java extension instead

/extJava
