### ISSUE TITLE
nums

### ISSUE THREAD

**Issue by rohailahmad-code** [microsoft/vscode#106188]
![Screenshot (5)](https://user-images.githubusercontent.com/70832936/92322838-2610ba80-f04d-11ea-904b-f3a115582ada.png)
Issue Type: <b>Bug</b>

python: can't open file 'manage.py' : [Errno 2] No such file or directory

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core  CPU      E5800  @ 3.20GHz (2 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|4.00GB (1.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.8.106424

</details>

**Comment by Tyriar** [comment]
The explorer is showing that file doesn't exist? If this is a problem with the python extension please report to the vscode-python repo.
