### ISSUE TITLE
No means of providing a title for vscode.Hover

### ISSUE THREAD

**Issue by johnbillion** [microsoft/vscode#106170]
When an LSP provides intellisense for a variable, property, method, etc its hover information for those items regularly includes a title as well as a description. Example:

<img width="408" alt="" src="https://user-images.githubusercontent.com/208434/92312165-9fad9780-efbe-11ea-889d-24f23d9950e7.png">

It's not possible to recreate the same title styling using `vscode.Hover`. Adding multiple strings to a Hover just results in the following:

<img width="615" alt="" src="https://user-images.githubusercontent.com/208434/92312167-a0dec480-efbe-11ea-8382-cc1b6d470558.png">

Observe that the first string is not styled the same as the title in the hover for the property description.

It would be great if `vscode.Hover` could support a title string too.

**Comment by jrieken** [comment]
I don't understand what I am seeing there. The first screenshot doesn't show the Intellisense widget but also a hover.

> It's not possible to recreate the same title styling using vscode.Hover. Adding multiple strings to a Hover just results in the following:

The `vscode.Hover`-type supports markdown styling. Did you try that?

**Comment by johnbillion** [comment]
Yes I've tried markdown styling for the hover (using headings, code, etc) but it doesn't match that of what I believe to be a natively provided hover for a property.

I just tested this by launching VS Code without extensions enabled. When viewing a `.ts` file that references a typed property there is a hover available on the property which includes a title and a description. Here is a code sample to reproduce it:

```typescript

interface Foo {
  /**
   * The short description as plain text
   */
  bar: string;
}

const myFoo: Foo = {
    bar: 'Hello'
}

const myFooBar = myFoo.bar;
```

Hover over the `myFoo.bar` property and you'll be shown a title and description. Screenshot:

<img width="495" alt="" src="https://user-images.githubusercontent.com/208434/92380931-3a66bd00-f10a-11ea-882b-dfe70a44e97a.png">

It doesn't appear that it's possible for an extension using `vscode.Hover` to exactly replicate the styling of this title. I've tried using a code block and using a heading, and neither result in the same stying:

<img width="192" alt="" src="https://user-images.githubusercontent.com/208434/92381266-cd075c00-f10a-11ea-978d-c0df4194b985.png">

**Comment by jrieken** [comment]
Hm, so the go-to-definition hover uses a [code block](https://github.com/microsoft/vscode/blob/1c0ac37b1e189eecaa9c380a442534cb79c053be/src/vs/editor/contrib/gotoSymbol/link/goToDefinitionAtPosition.ts#L209) (not inline code). Can you try that?

**Comment by johnbillion** [comment]
Perfect!

<img width="197" alt="" src="https://user-images.githubusercontent.com/208434/92391279-a6522100-f11c-11ea-8209-92e1a088d277.png">

I'd like to submit a PR to the documentation for `vscode.Hover` to mention this. What do you think?

**Comment by jrieken** [comment]
That depends on the wording ;-) The code block isn't styled to look like a title it is just a coincidence that it in that sample, e.g this is how a different, valid, case looks:

<img width="505" alt="Screenshot 2020-09-07 at 16 03 02" src="https://user-images.githubusercontent.com/1794099/92395514-bde0d800-f123-11ea-8f42-9965b97ecbcd.png">

**Comment by johnbillion** [comment]
Cheers! Closing this off then.
