### ISSUE TITLE
Very hard to spot where object's members end and next local variable begins

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#10618]
`_rule` children stop before `beforePush` but this is very difficult to see unless one collapses to really check

![object-limit](https://cloud.githubusercontent.com/assets/5047891/17739929/0dd83876-6497-11e6-8397-e91549b9962c.gif)

**Comment by rozzzly** [comment]
Deeper indent, possibly a faint line like this

Collapsed:
>  fileA
> + folder1
> + folder2

Expanded:
>   fileA
> - folder1
>    |  fileA1
>    | + subdir1
>    | - subdir2
>    |    |  fileC
>    |    |  FileD
>    |  FileE
> + folder2

**Comment by isidorn** [comment]
We are now using the same indentation we use in the explorer. So 4px more. It should make things more obvious.

@rozzzly thanks for your suggestion but that is a seperate feature request. We are introducing icons to vscode in the August release and if you think your suggestion is the right way to go then please create a new feature request - thanks.
