### ISSUE TITLE
vscode can not use remote source map

### ISSUE THREAD

**Issue by dazhuaoyao** [microsoft/vscode#106182]
- VSCode Version: 
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0

- OS Version:
Mac

Steps to Reproduce:

1. follow the [Language Server Extension Guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide)
```
> git clone https://github.com/microsoft/vscode-extension-samples.git
> cd vscode-extension-samples/lsp-sample
> npm install
> npm run compile
> code .
```
2. then debug the lsp-sample extension as the doc describe, we can see the call stack:
<img width="1317" alt="图片" src="https://user-images.githubusercontent.com/29044630/92319037-d0391400-f046-11ea-91c9-7d004772fcfe.png">

I go to the _callActivateOptional as the above picture show, but this file is minified:

<img width="993" alt="图片" src="https://user-images.githubusercontent.com/29044630/92319097-ab916c00-f047-11ea-9f62-2baf62790eb3.png">
We can see this minified file have a souremap url: 
/# sourceMappingURL=https://ticino.blob.core.windows.net/sourcemaps/a0479759d6e9ea56afa657e454193f72aef85bd0/core/vs/workbench/services/extensions/node/extensionHostProcess.js.map

And it is available when I visit by browser, **but vscode cannot use this source map file ,  and still show me the minified file even though I enable `sourceMaps: true` option**

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
you can enable sourcemap loading by configurating the `resolveSourceMapLocations`, e.g. by removing the requirement that sourcemaps be in the workspace folder.

```
"resolveSourceMapLocations": [
	"!**/node_modules/**"
],
```

Note that it will take several seconds after starting the debugged instance of VS Code before sourcemaps are downloaded and available.
