### ISSUE TITLE
Browser Preview CSS 

### ISSUE THREAD

**Issue by leeo217** [microsoft/vscode#106161]
Issue Type: <b>Feature Request</b>

Please let me know how can i activate browser preview for css content within the project in VSCODE.
As my code doesn't run fully in browser only html code runs but css doesn't.

Thank you in advance. 
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

**Comment by AlexandroGonSan** [comment]
> As my code doesn't run fully in browser only html code runs but css doesn't.
1. Provavelmente esse não é o melhor pedido para resolver o seu problema .
2. Se no navegador o seu css não trabalha , resolva isso pois provavelmente você está criando algo para o navegador .

* Don't ask me to write in english , use Chrome .

**Comment by aeschli** [comment]
What kind of preview do you want to see?

**Comment by leeo217** [comment]
Never mind figured out the issue. 

Thank you anyways.
