### ISSUE TITLE
VS Code crashes when opening a 133 Mb json file without newlines

### ISSUE THREAD

**Issue by taatuut** [microsoft/vscode#106106]
Issue Type: <b>Bug</b>

Looks like https://github.com/microsoft/vscode/issues/102726 which is closed but issue still occurs.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.22GB free)|
|Process Argv|-psn_0_729266|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio-insiders-build|hed|0.7.302
mongodb-vscode|mon|0.1.1

</details>

**Comment by rebornix** [comment]
It's an known issue and a limitation in our current architecture.

**Comment by cynecx** [comment]
@rebornix If it’s a known issue where is it being tracked at since you have closed this issue tracker?
