### ISSUE TITLE
Retain collapsed state of SCM providers across window reloads

### ISSUE THREAD

**Issue by plwalsh** [microsoft/vscode#106196]
It would be great if the collapsed/expanded state of each SCM provider in the Source Control view would be retained across window reloads or window close-and-reopens. This functionality would better align with state retention across all other areas (like the file tree state in the Explorer view).

As a use case example, I have a repository that consists of several submodules. While I like to keep the submodule repositories visible at all times in the Source Control view for a high-level clean/dirty status, I don't necessarily need to see the file-level status inside each repo. So I like to keep those repos collapsed, while the main repo (parent) remains expanded at all times. As it currently stands, every time I reload or close the window, I need to reconfigure this setup when it opens back up, collapsing each repo one-by-one.

---

#### Current version information
```
Version: 1.49.0-insider (user setup)
Commit: e4256dd1a02339bb1d56647ecd9134bf38bc7c03
Date: 2020-09-04T18:49:12.955Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.16299
```

**Comment by gjsjohnmurray** [comment]
You didn't post your version information. If you are not already using Insiders maybe give that a try. If it's fixed there it will arrive in the next Stable, probably before the end of the coming week.

**Comment by plwalsh** [comment]
Sorry about that. OP updated with version info. I've been tracking the insider updates for quite some time now, ever since the updated Source Control view was introduced, and have yet to see it fixed. So I figured it was finally time to submit an issue in case no one had noticed it yet.

**Comment by gjsjohnmurray** [comment]
Related to #104629

**Comment by joaomoreno** [comment]
#102831
