### ISSUE TITLE
No windows or folders reopened on startup on Catalina

### ISSUE THREAD

**Issue by carlescufi** [microsoft/vscode#106191]
Issue Type: <b>Bug</b>

When closing the main VS Code window and then opening it again (without actually quitting the application), my folder and open windows are not reopened, and instead VS Code shows me the welcome window.

I have tried:

```
    "files.hotExit": "onExitAndWindowClose",                                       
    "window.restoreWindows": "all",                                                
    "window.reopenFolders": "all",  
```

without success.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz (8 x 1200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (1.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.8.106424
vim|vsc|1.16.0

</details>

**Comment by weinand** [comment]
There is no "main" window in VS Code. All windows are equal.
So closing a window and reopening it, is nothing special and does not trigger the restoring of windows and folders.

You must "exit" (aka "quit") VS Code and then relaunch in order to trigger restoring of windows and folders. 
(That's the reason why the hotExit setting "onExitAndWindowClose" uses the the term "exit").
