### ISSUE TITLE
Jump to next problem always works.

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#106138]
Currently when I press the default keyboard shortcut of F8 to jump to next problem, it only does so if I have initially opened the problems view, and jumped to the first problem. The an only then, will F8 begin jumping to other problems.

The desired behaviour would be, no matter what state the problems panel or editor windows are in, if there is a problem, F8 will jump to it.

**Comment by sandy081** [comment]
It works for me even if problems view is not opened. 

Can you please provide steps to repro?

**Comment by safield** [comment]
It seems like I have to close the current editor as well. Jump to first problem, close the editor window so no editor tabs are open, the hit F8. Nothing happens for me. If these steps do not reproduce it foryou, I will have to dig deeper.

**Comment by sandy081** [comment]
F8 is supported only when you have an editor opened.
