### ISSUE TITLE
VSCode cannot find my module Python

### ISSUE THREAD

**Issue by Shymaxtic** [microsoft/vscode#106165]
Issue Type: <b>Bug</b>

Is there any problem with finding Python module at recent updates?
My VSCode now cannot find any my Python module? It worked well few days ago.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (1.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
code-gnu-global|aus|0.2.2
Doxygen|bbe|1.0.0
bracket-pair-colorizer|Coe|1.0.61
xml|Dot|2.5.1
python|ms-|2020.8.106424
cpptools|ms-|0.29.0
autodocstring|njp|0.5.3
vscode-qt-for-python|sea|0.4.2
python|tht|0.2.3
vscode-icons|vsc|10.2.0
vscode-todo-highlight|way|1.0.4
licenser|ymo|1.5.0

(1 theme extensions excluded)

</details>

**Comment by AlexandroGonSan** [comment]
1. Esse é um problema simples .
2. Você não forneceu informações relevantes para que eu pudesse ajuda-lo , além da versão do sistema operacional .
3. Meu palpite é que você pode resolver isso nas configurações .
4. Isto é dependioso , mas verifique se você consegue rodar o python na linha de comando .
5. Lembre-se de voltar aqui , informar a solução , e fechar o issue quando resolver , isso ajuda na manutenção da comunidade .

* Don't ask me to write in english , use Chrome .

**Comment by Shymaxtic** [comment]
Hi all, thanks for your feedback.
It turns out that the problem comes from "Microsoft Python Language Server". I followed this thread and resolved the problem.
