### ISSUE TITLE
VSCode becomes too dim when Windows HDR is enabled

### ISSUE THREAD

**Issue by ErickXavier** [microsoft/vscode#106122]
- VSCode Version: 1.48.2
- OS Version: Windows 10

Steps to Reproduce:

1. Go to Window's Display Settings and enable "Play HDR games and apps"
2. Open VSCode

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Bot is correct, this is duplicate of issues above but original issue is #88491

Could you check if it's still reproducible for you in Insiders builds https://code.visualstudio.com/insiders/?

**Comment by WillerZ** [comment]
I also have this problem with VScode and I do not have it with insiders

**Comment by aeschli** [comment]
duplicate of  #88491
