### ISSUE TITLE
collectWorkspaceStats() can hang

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#106116]
If `token.count` happens to be equal to `MAX_FILES` here:
https://github.com/microsoft/vscode/blob/fe9d6d9f16166e400ba3d234eb8a8626d6011bc3/src/vs/platform/diagnostics/node/diagnosticsService.ts#L89

`pending` will be 0 and the loop after that will not loop at all and `done` will not be called on that branch of the traversal:
https://github.com/microsoft/vscode/blob/fe9d6d9f16166e400ba3d234eb8a8626d6011bc3/src/vs/platform/diagnostics/node/diagnosticsService.ts#L105

The fix might be to change the first check to use `>=`.

**Comment by RMacfarlane** [comment]
Nice catch, I will fix this in September

**Comment by sandy081** [comment]
Verified by code review
