### ISSUE TITLE
Debugging error path with space leaves path useless

### ISSUE THREAD

**Issue by nomadiccode** [microsoft/vscode#106121]
- VSCode Version: 1.48.2 Stable
- OS Version: 5.7.17-2-MANJARO

Steps to Reproduce:

1. Make an app for debugging whose path has a space in it i.e ( /home/user/path with space/ )
2. Debug the application (preferences don't matter)
3. Cause an error during debugging
4. The traceback path becomes useless

Does this issue occur when all extensions are disabled?: No, the Python extension is disabled, so I cannot debug the program

Here's an image of the problem

![problem](https://user-images.githubusercontent.com/64012987/92245277-b4bef380-eef6-11ea-9df2-f5267d182f26.png)

**Comment by weinand** [comment]
@NomadicCode what is the context of that screenshot? debug console or integrated terminal?

**Comment by NomadicCode** [comment]
![problem2](https://user-images.githubusercontent.com/64012987/92293471-62152400-ef56-11ea-9cdd-421eda96f14f.png)

**Comment by NomadicCode** [comment]
Im debugging the program with debugpy and when an exception occurs the path is split in half, making it useless

**Comment by weinand** [comment]
@isidorn who parses the stack trace in the exception peek UI?

**Comment by isidorn** [comment]
The link detector from [here](https://github.com/microsoft/vscode/blob/64b79581cbd3b50378eefcd076a8b3848b442b10/src/vs/workbench/contrib/debug/browser/linkDetector.ts#L36)

So this issue is bacialy "link detection does not work when path has whitespace". If I understand it correctly.

**Comment by weinand** [comment]
Yes, if the path is enclosed in quotes, we should not break the path at a blank.

Do we really need our own sets of patterns here or could we get them from some service?
I think these path patterns should be consistent across VS Code.

**Comment by isidorn** [comment]
Agree, this has already been discussed in mulitple issues. However the rest of vscode uses editor link detection, debug console is not an editor so we could not reuest. But yeah patterns we could ideally re-use.

**Comment by nomadiccode** [comment]
is there going to be any work on this? I find it harder to access the file that contains the error because of this

thanks in advance :)
