### ISSUE TITLE
Add setting to prevent override the "autoClosingPairs" section of a langage-configuration.json file.

### ISSUE THREAD

**Issue by rnewton5** [microsoft/vscode#106198]
The Rust language extension includes an "autoClosingPairs" entry for "<".

This makes writing less than conditionals a pain because the associated bracket, ">", is automatically appended to the end.

I've gone into the extension folder and have manually removed the line to prevent angle brackets from automatically closing. However, this solution is less than ideal. I'd like a setting entry to be able to override the autoClosingPairs list.

thanks

**Comment by rnewton5** [comment]
Hi @weinand , I wouldn't say that this issue is caused by an extension, I was simply using that as an example. Everything is working exactly as expected, there's just no way to override the auto closing brackets defined in the extension's language configuration file.

**Comment by weinand** [comment]
Most likely every language has "less than conditionals" and I've never experienced problems with auto closing for example in JS/TS or Java. For that reason I would like to understand the perspective of the Rust extension with regards to "autoClosingPairs" before we start to add another setting.
