### ISSUE TITLE
"Add cursor above/below" keyboard shortcuts not working

### ISSUE THREAD

**Issue by gulshan** [microsoft/vscode#106167]
Issue Type: <b>Bug</b>

- Open any file in editor.
- Press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>DownArrow</kbd> for "Add cursor below"
- Press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>UpArrow</kbd> for "Add cursor above"
- Nothing happens.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (11.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
gc-excelviewer|Gra|3.0.40
classic-asp-html|jtj|0.1.2
mssql|ms-|1.9.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0

</details>

**Comment by gulshan** [comment]
Found a solution in #106156
> Disabling the 'Intel Graphics Command Center Startup Task' during startup fixed the issue (IGCCTray.exe).

Still I think vscode team should have a look.

**Comment by rick3rt** [comment]
I am reporting the bug to Intel.

**Comment by alexdima** [comment]
There is nothing for us to look at. Some driver on the OS "steals" the keybinding so no application on that machine can receive it. There is nothing for us to do if that happens. That driver needs to stop doing that or be configured to stop doing that.
