### ISSUE TITLE
Cursor Regularly Dissapears

### ISSUE THREAD

**Issue by JeremyRubin** [microsoft/vscode#106253]
Issue Type: <b>Bug</b>

Hi! This bug comes up in a variety of different circumstances while using code -- e.g., working on C++, Solidity, Typescript, etc.

The cursor will stop showing up, and then I have to reload the window, and then it will only show briefly.

I've tried adjusting my render type and enabling/disabling extensions. With no extensions at all, the issue does not occur.

It is probably a negative interaction between different styling rules that the cursor gets mangled. One recommended fix would be somehow affixing important css rules to cursor so extensions can't override and make it invisible...

In the current setup I have below the cursor dissapears whenever the file is syntactically valid. When I have vim ext installed it just disappears altogether (syntax valid or not).

Not sure how to make a repro for this.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 5.4.0-42-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor (16 x 2615)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|31.37GB (1.60GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
plantuml|jeb|2.13.13
solidity|Jua|0.0.76
python|ms-|2020.8.106424
cpptools|ms-|0.30.0-insiders2
rust|rus|0.7.8
graphviz-interactive-preview|tin|0.0.9
solidity-visual-auditor|tin|0.0.29
vscode-ethover|tin|0.0.5
vscode-inline-bookmarks|tin|0.0.18
vscode-solidity-flattener|tin|0.0.9
slither-vscode|tra|0.0.7

</details>

**Comment by alexdima** [comment]
@JeremyRubin Normally using our API, extensions cannot change our CSS and mess with our rules. Some extensions go in and patch our css file on disk or use a known injection pattern to add additional CSS. We cannot support such VS Code instances, since with directly editing the CSS it is possible for everything to be broken in a million ways and we would never be able to reproduce.

So can you please try out our insiders without any extensions https://code.visualstudio.com/insiders/ ? Does the issue reproduce there?

**Comment by JeremyRubin** [comment]
Insiders seems to work like a charm, even with extensions installed. Will reopen an issue if it comes up again though.

Thanks so much for you help!
