### ISSUE TITLE
[theming][editor] support selection foreground color

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#10622]
- VSCode Version: Code - Insiders 1.5.0-insider (11ffcfcf69608c07e7db4b4c77856854d5083497, 2016-08-16T06:12:46.372Z)
- OS Version: Linux x64 4.4.0-34-generic, Ubuntu 16.04

It's difficult to read selected text when the theme is designed to change the foreground color:

![image](https://cloud.githubusercontent.com/assets/2193314/17744413/6a340d60-645c-11e6-96ee-2d7d6c653eee.png)

**Comment by aeschli** [comment]
selectionForeground would be very difficult implement given that in our editor selection and text are two different layers. @alexandrudima Alex, correct me if I lie.
Also [from what I read](https://github.com/deplorableword/textmate-solarized/issues/52), selectionForeground seems to be a customization, not even supported by TextMate. So I'd suggest to close this request as 'won't fix'.

**Comment by Tyriar** [comment]
This is one of a few issues that make themes converted from sublime text look bad (another example https://github.com/Microsoft/vscode/issues/3429). The majority of our themes are converted from sublime or atom themes so shouldn't we provide similar support to those editors?

**Comment by alexandrudima** [comment]
@aeschli is correct. The text and the selection are rendered as different layers. When the selection changes, the text is not repainted. This was implemented 5 years ago with performance in mind and without having `selectionForeground` in mind . Definitely a nice thing to have.

**Comment by aeschli** [comment]
Surely it would be ideal if we fully support all the various text mate theme properties, but there will always be differences and features we don't or can't support.
It's up to the author of a VSCode theme extension to not just import a theme but also to test and -if necessary- tune some of the colors or settings so it works seamless in VSCode. 

Closing won't fix given there's no plan on changing the current editor implementation in respect of keeping the selection layer separate from the text later.

**Comment by Tyriar** [comment]
Any reason this can't just be done using an `!important` rule on `.token`? Seems like an appropriate use of it.

**Comment by aeschli** [comment]
What if the selection starts in the middle of a token? 
![image](https://cloud.githubusercontent.com/assets/6461412/17784710/c2036488-657d-11e6-974d-abc1e9b80b29.png)
The token needs to be broken up. Also every token under a selection needs a class to be added and removed so it can be styled with the foreground color. 
We can keep this request open if you prefer.

**Comment by Tyriar** [comment]
Oh yeah, it's not native selection so `.token::selection` won't work. Nevermind let's close this, doesn't seem like it will get implemented.
