### ISSUE TITLE
Feature request: Reveal in explorer

### ISSUE THREAD

**Issue by jlbruno** [Microsoft/vscode#10627]
- VSCode Version: 1.4.0
- OS Version: Windows 7

When my user settings are set to have explorer.autoReveal = false, I can't find any way to reveal a file (either from the editor list or the tab) in the built in explorer. There is a "reveal in explorer" context menu option when right clicking on a file in the list of open editors, but it opens a windows explorer window. 

I'd like suggest changing the existing "reveal in explorer" option to have the same behavior as the "autoReveal"....selecting the file in the built in explorer window under the open editors. And perhaps renaming the existing "reveal in explorer" functionality to "open in explorer".

Thanks.

**Comment by bpasero** [comment]
F1 > "Show Active File In Explorer"
