### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by AbutalhaKothiwale53** [microsoft/vscode#106242]
Issue Type: <b>Bug</b>

I'm not able to open a new project and there is open project option available as I click on the file button it directly shows me to create a new file and not project 

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 6.3.9600

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.4
ng-template|Ang|0.1000.8
ajax-query|Bal|0.6.0
plsql|cas|0.0.5
angular2-snippets|dan|1.0.21
csv-editor|est|0.2.2
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
code-runner|for|0.11.0
sky-csv|Han|0.0.5
csharp|ms-|1.23.2
mssql|ms-|1.9.0
python|ms-|2020.8.106424
angular-console|nrw|13.0.0
LiveServer|rit|5.6.1
mongo-snippets-for-node-js|roe|1.3.5
vscode-java-debug|vsc|0.28.0
vscode-java-pack|vsc|0.10.0
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by weinand** [comment]
Please try to use the "Open Workspace" menu command and then select your project folder.
