### ISSUE TITLE
Can't use Ctrl+Alt+Arrow to duplicate cursor

### ISSUE THREAD

**Issue by schuelermine** [microsoft/vscode#106201]
Issue Type: <b>Bug</b>

Previously, using Ctrl + Alt + Up or Ctrl+Alt+Down would create a new cursor above the highest/below the lowest cursor at that cursors column. This no longer works.

VS Code version: Code - Insiders 1.49.0-insider (e4256dd1a02339bb1d56647ecd9134bf38bc7c03, 2020-09-04T18:49:12.955Z)
OS version: Windows_NT x64 10.0.20190

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.12GB free)|
|Process Argv|C:\Users\anselmschueler\AppData\Local\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json --crash-reporter-id ff84c704-1b73-4a28-a22f-d9c8b540b255|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.1.0
better-comments|aar|2.1.0
vscode-icontheme-nomo-dark|be5|1.3.6
gitlens|eam|10.2.2
haskell|has|1.1.0
discord-vscode|icr|4.0.0
language-haskell|jus|3.3.0
python|ms-|2020.8.106424
remote-wsl|ms-|0.44.5
powershell-preview|ms-|2020.7.0
fish-vscode|sky|0.2.1
vscode-icons|vsc|10.2.0

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
Which commands are bound to the desired key combination?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by PaulMejiaFeliz** [comment]
https://github.com/microsoft/vscode/issues/106089#issuecomment-687596374 This one could be helpful, it worked for me

**Comment by alexdima** [comment]
@schuelermine Can you please confirm?

**Comment by schuelermine** [comment]
THAT WAS IT! Thanks!
