### ISSUE TITLE
Fix Trusted Types violation (round #1)

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#106285]
This is part of the TrustedTypes effort (see https://github.com/microsoft/vscode/issues/103699) and a list of `innerHTML` usages which we avoid. To compile a list of violations

* run `yarn web --trusted-types`
* open http://localhost:8080/ in Edge or Chrome
* open console and check for "_[Report Only] This document requires 'TrustedHTML' assignment._"-messages

Also, there is `.vscode/searches/TrustedTypes.code-search` which finds all occurences of `innerHTML`. There are common sources of violation and therefore common fixes

* styling via `style.innerHTML` ➡️  use `textContent` instead (example https://github.com/microsoft/vscode/commit/c112f845f010a4b428a148d826e33dbb20d3f7fe)
* clear a node via `node.innerHTML = ''` ➡️  use `dom.ts#clearNode` or `node.innerText = ''`
* building dom nodes ➡️ use `dom.$` or `document.createElement` and friends
----

- [x] abstractTextMateService.js:250 @alexdima
- [x] abstractTree.js:1075 @joaomoreno
- [x] codiconStyles.js:17 @aeschli
- [x] compositePart.js:277 @jrieken
- [x] dirtydiffDecorator.js:1020 @joaomoreno
- [x] explorerView.js:628 @isidorn
- [x] listWidget.js:634 @joaomoreno
- [x] menubar.js:419 @sbatten
- [x] sash.js:35 @joaomoreno
- [x] statusbarColorProvider.js:74 @bpasero
- [x] statusbarPart.js:497 @bpasero
- [ ] viewLayer.js:394 @alexdima <-- will not happen, this is part of fine-tuned editor rendering, building dom nodes is not an option
- [x] watermark.js:105 @chrmarti
- [x] workbenchThemeService.js:560 @aeschli

**Comment by jrieken** [comment]
fyi @annkamsk

**Comment by alexdima** [comment]
The `viewLayer.js:394` is part of rendering the editor, this is very fine-tuned and changing the editor to build dom nodes instead of using raw html would make the editor a lot slower.

**Comment by jrieken** [comment]
> The strings in there are always properly escaped, so no injection is possible.

Yeah, I was expecting that and I think it's a good use case for a Trusted Types policy

**Comment by sbatten** [comment]
fixed for menubar

**Comment by jrieken** [comment]
Closing this, the continuation is tracked here: https://github.com/microsoft/vscode/issues/106395 and here https://github.com/microsoft/vscode/issues/106396
