### ISSUE TITLE
window.top undefined property "top"

### ISSUE THREAD

**Issue by Better-Boy** [microsoft/vscode#106259]
- VSCode Version: 1.48
- OS Version: Windows 10

Steps to Reproduce:

I have the following snippet of code that is loaded from a javascript file.

```function checkforParent(){
      var parents = [];
       
      var nextWindow = window.self;
      while(nextWindow.top !== nextWindow){
            nextWindow = nextWindow.opener || nextWindow.parent;
            parents.unshift(nextWindow);
       }
```
When I run the vscode webview it's giving the following error,

**Cannot read property "top" of undefined**

But if I do 

```function checkforParent(){
      var parents = [];
       
      var nextWindow = window.frames.top;
      while(nextWindow.top !== nextWindow){
            nextWindow = nextWindow.opener || nextWindow.parent;
            parents.unshift(nextWindow);
       }
```
everything works fine.

Is this the correct approach of changing to `window.frames.top`?

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
This question is unrelated to VS Code.
