### ISSUE TITLE
Vscode + github + windows = :(

### ISSUE THREAD

**Issue by jimmyff** [microsoft/vscode#106250]
I'm new to windows (I've come from OSX and may well be going back!) I'm trying to get vscode setup but I've had a nightmare trying to get it to work with github, I'm trying to use the flutter fetch dependencies command which fetches packages (private repos) from github. 

I've managed to find a temporary fix that allows me to fetch dependencies by following this solution:
https://github.com/microsoft/vscode/issues/42039#issuecomment-360278781

I'm sure this can't be the correct way to get VSCode to work with github private repos on Windows,
am I missing something really obvious?

I've updated open ssh:
```
Z:\dev\flutter\onescene\app>where ssh
C:\Windows\System32\OpenSSH\ssh.exe
C:\Program Files\OpenSSH\ssh.exe
```

**Comment by joaomoreno** [comment]
You're missing some very critical information:

- OS, VS Code version
- What's the command you're executing?
- What's the actual error you're seeing?

Screenshots and [screen recordings](https://gifcap.dev/) are also very helpful.
