### ISSUE TITLE
Vue file type disallows collapse of html tags in template section

### ISSUE THREAD

**Issue by MetanoiaRichi** [microsoft/vscode#106204]
- VSCode Version: 1.48.2
- OS Version: Windows 10

Steps to Reproduce:

1. Set file type to vue
2. Check to see that only the main template tag is collapseable. 

After the update I cant collapse the tags under the template in vue files.
The only collapseable part is the main template tag. Whereas the sub tags inside aren't collapseable.
There are also some times when If I open a vue file it will automatically collapse the template or the script section, or even both.
I had to switch the file type to vue-html to make the all tags collapseable again but making it like that will break the color stylings of the code. It will make the entire script tag color white which looks like a block of text not a code.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
Do you use am extension for vue?
Can you add a code sample that shows the issue?

**Comment by gabrielSBorges** [comment]
I think I have the same problem.

**Comment by gabrielSBorges** [comment]
I think I have the same problem. Only the "template" tag can be collapsed:
![image (1)](https://user-images.githubusercontent.com/32948255/92474281-f29b7080-f1b1-11ea-974e-19c1ca2cbce3.png)

**Comment by aeschli** [comment]
Folding ranges either come from extensions, or they are computed by indentation.
I believe the vue extension provides folding ranges, so if there are ranges missing, this is an issue of the vue extension.

Can you please file the issue against the vue extension? 

Also check https://github.com/vuejs/vetur/issues/2134
