### ISSUE TITLE
CSS Autosuggestion shows experimental properties first

### ISSUE THREAD

**Issue by aslamdoctor** [microsoft/vscode#106234]
- VSCode Version: 1.48.2
- OS Version: Pop OS 20.04

Steps to Reproduce:

1.Create any CSS file
2.And try typing "**text-align**", it will auto suggest "**text-align-last**" as first option, attached is the screenshot. Same issue with "**line-height**", it will auto suggest "**line-height-step**" as first suggestion. 
Same issue with "**font-size**". 

This can all be seen in attached screenshots.

These are all all experimental properties so should not be suggested as first. It would be much more productive if this worked as before. So typing "text-align" should give "text-align" as first suggestion.

Does this issue occur when all extensions are disabled?: Yes

![2020-09-07_18-40](https://user-images.githubusercontent.com/171670/92391252-f25f8e80-f139-11ea-9a68-5d34516e45df.png)
![2020-09-07_18-41](https://user-images.githubusercontent.com/171670/92391257-f390bb80-f139-11ea-901a-3538e84d174f.png)
![2020-09-07_18-41_1](https://user-images.githubusercontent.com/171670/92391260-f4295200-f139-11ea-802c-53d92f59ecad.png)

**Comment by aeschli** [comment]
This got fixed in the latest stable

**Comment by aslamdoctor** [comment]
Yes, thank you 👍
