### ISSUE TITLE
The implementation of SkipList seems to have useless level.

### ISSUE THREAD

**Issue by LeuisKen** [microsoft/vscode#106213]
File: https://github.com/microsoft/vscode/blob/master/src/vs/base/common/skipList.ts

Since the index of reference the paper starts from 1, and our implementation starts from 0, we could find that SkipList level forward[1] always equals to forward[0]. And it looks like we seem to waste some memory.

The following code could print the actual level in the SkipList:

```js
function logLevel(list, level) {
    let node = list._header;
    const res = [];
    while (node.forward[level]) {
        res.push(node.forward[level].key);
        node = node.forward[level];
    }
    console.log(res.toString());
}

function logLevels(list) {
    for (let i = 0; i <= list._level; i++) {
        console.log(`Level ${i}:`);
        logLevel(list, i);
    }
}
```

The test case I use is:

```js
let list = new SkipList((a, b) => a - b, 10);
list.set(1, true);
list.set(2, true);
list.set(3, true);
list.set(4, true);
list.set(5, true);
list.set(6, true);
list.set(7, true);
list.set(8, true);
list.set(9, true);
list.set(10, true);
list.set(11, true);
list.set(12, true);
```

Steps to Reproduce:

1. Running the test case and print SkipList using `logLevels`;
2. level 0 and level 1 are equal.

![image](https://user-images.githubusercontent.com/7701575/92356445-b7992e80-f118-11ea-9d91-daf721c1a3d4.png)

Expected:

![image](https://user-images.githubusercontent.com/7701575/92356537-e1525580-f118-11ea-806d-3f74a7eeef27.png)

I'd like to send a pull request to fix this problem if you want.

**Comment by jrieken** [comment]
> I'd like to send a pull request to fix this problem if you want.

👍
