### ISSUE TITLE
git: 'credential-stoee' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by Rhiyo** [microsoft/vscode#106207]
Hello, I'm using VS Code to try and push a commit to remote. However, the remote server requires a personal access token (It's a personal GitLab server). I've set a personal access token using GitLab workflow, I'm not sure if this is the right way to do things.

However, I get an error: 
```
git: 'credential-stoee' is not a git command. See 'git --help'. 
```
when trying to push in vs code. I'm not sure where the spelling mistake comes from, is it my git repository (it was originally cloned and managed with gitkraken on local0, vs code itself, the gitlab extension?

Im not even sure if this is related to the personal access token. as I get these errors after anyway:

```
remote: HTTP Basic: Access denied
remote: You must use a personal access token with 'read_repository' or 'write_repository' scope for Git over HTTP.
```
and the current personal access token only has read_user and api access.

**Comment by joaomoreno** [comment]
This is very likely a bad git configuration in your system. Can you check in `git config --global -e`? You'll find that string there.

**Comment by Rhiyo** [comment]
Thanks. the issue was in there, under [helper]. However I'm still unsure where I would need to put my personal access token within VS Code, if there is a place to put it.
