### ISSUE TITLE
python r+'\' is not working

### ISSUE THREAD

**Issue by liuyunsihai** [microsoft/vscode#106210]
- VSCode Version:1.48.2
- OS Version:Windows_NT ia32 10.0.17763

Steps to Reproduce:

1.create a python file
2.write code:path = r"\\"
3.save and run it

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
What is this meant to do and what does it do instead?

**Comment by liuyunsihai** [comment]
It should play a role in prohibiting escaping，but not
![image](https://user-images.githubusercontent.com/30039346/92565350-155e7f80-f2ad-11ea-8686-a4e5884055c8.png)
![image](https://user-images.githubusercontent.com/30039346/92565364-1abbca00-f2ad-11ea-99f8-2106b1b72543.png)
It's not working

**Comment by Tyriar** [comment]
You're using some extension to run it, you need to report it to the extension.
