### ISSUE TITLE
In-product release notes code blocks missing syntax highlighting

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#106261]
- VSCode Version: 1.49.0 Insiders
- OS Version: Windows 10, macOS

![image](https://user-images.githubusercontent.com/12818376/92419976-9985fb00-f125-11ea-846b-511a9d109b46.png)

Repros for TypeScript, JavaSctipt, and JSON code blocks in the release notes. 

Regular Markdown preview seems fine:

![image](https://user-images.githubusercontent.com/12818376/92420029-dc47d300-f125-11ea-957d-16351f24fb86.png)

**Comment by gregvanl** [comment]
Started with Insiders release https://github.com/Microsoft/vscode/commit/f66741dc2b4944e153719bb48bcaa9c565cc40f7
Insiders release https://github.com/Microsoft/vscode/commit/6384e3246884694cbc34eacc70281ada15e2c7f2 is good.

**Comment by gregvanl** [comment]
Also repros for Extension details which have code blocks in Markdown.

![image](https://user-images.githubusercontent.com/12818376/92504451-89b6f700-f1b7-11ea-8987-b982b94d3f21.png)

**Comment by RMacfarlane** [comment]
@alexdima caused by https://github.com/microsoft/vscode/commit/3994e92d88ea5e08548f3a29315e08fffec5191a

**Comment by mjbvz** [comment]
Hey @alexdima, I think 3994e92d88ea5e08548f3a29315e08fffec5191a caused this. 

Here's the problem:

- `tokenizeToString` returns tokens [wrapped in](https://github.com/microsoft/vscode/blob/94428f89bf25e3df92827c5bc677da8452aa7d12/src/vs/editor/common/modes/textToHtmlTokenizer.ts#L103) an `<div class="monaco-tokenized-source">`

- `generateTokensCSSForColorMap` used to generate generic css for the token classes. However it now generates css with the format `.monaco-editor .tokenclass`.

I can try adding an extra wrapper class around the output of `tokenizeToString` in this case but will need to review to make sure this didn't break anything else

**Comment by mjbvz** [comment]
The only reason code coloring in hovers still works is because they are under the editor dom node. If our markdown render is used for anything outside of the editor dom, code highlighting will not work

**Comment by mjbvz** [comment]
I suggest we revert the change unless it fixed some critical issue. That seems like the safest thing to do at this point

**Comment by mjbvz** [comment]
Pushed revert to main. Reopening for cherry-picked pr to 1.49: #106312
