### ISSUE TITLE
Extension Authors Call for August 2020

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#106264]
Here is the rough plan for our extension authors call for **August** 2020. The call will be held on **September 17th** @ **10am PT**.

The call will be focused on gathering feedback on a new work-in-progress proposal to improve the "what's new"/release notes/update experience for extensions (https://github.com/microsoft/vscode/issues/102139) and the new proposed APIs for supporting webviews within views (sidebar and panel) (https://github.com/microsoft/vscode/issues/46585). We will also highlight some recent and upcoming extension author APIs. So if you are interested in participating in those topics please join us!

### Agenda
- [_~10 mins_] Introductions — please introduce yourselves and your extension(s)
- [_~20 mins_] Introduce https://github.com/microsoft/vscode/issues/102139 and gather feedback
- [_~20 mins_] Introduce https://github.com/microsoft/vscode/issues/46585 and gather feedback
- [_~10 mins_] Highlight recent and upcoming features and APIs relevant to extension authors

### Participants
Since we want a small set of participants to facilitate richer and more effective communication, we are asking everyone who is interested in participating to fill out the sign up link below:

[Sign up to participate](https://www.surveymonkey.com/r/J5JLNHM)

Sign-ups will end on **Sept 15th**. After which, we will reach out and confirm the set of authors who will be participating in the call, and will update this post with the final list.

### Logistics
On **September 17th** @ **10am PT**, via a MS Teams call. After the call ends, we will post a link to the recorded video.

**Comment by RandomFractals** [comment]
I posted my comments & questions for the issues you plan to cover in this call.

What's new UX looks really good. Sidebars I do have some questions about.

Happy to see you guys still do it monthly.

Hopefully, I'll get invited for this call to ask more.

**Comment by eamodio** [comment]
Unfortunately because of conflicts with the VS Code Release Party call, we are going to move the Extension Authors call to Thursday, Sept 17th.

**Comment by RandomFractals** [comment]
@eamodio that's fine. just let us know who you picked for that call. I posted my comments where needed.

**Comment by mjbvz** [comment]
Closing since the call has taken place

**Comment by eamodio** [comment]
Thank you to everyone who participated in this call!

### Video
[![](https://img.youtube.com/vi/qkClv7gsq5w/hqdefault.jpg)](https://youtu.be/qkClv7gsq5w)

### Participants
- Gustavo Cassel ([Google Drive](https://marketplace.visualstudio.com/items?itemName=GustavoASC.google-drive-vscode))
- Jose Leon ([TMS WEB Core](https://marketplace.visualstudio.com/items?itemName=tmssoftware.tmswebcore))
- Prakash B ([Salesforce](https://marketplace.visualstudio.com/publishers/salesforce))
- Gordon Smith ([Observable JS](https://marketplace.visualstudio.com/items?itemName=GordonSmith.observable-js))
- Luis Campos ([Salesforce](https://marketplace.visualstudio.com/publishers/salesforce))
- Taras Novak ([Data Preview](https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-preview) and [more](https://marketplace.visualstudio.com/publishers/RandomFractalsInc))

### Topics
- Extensions What's new/update UI exploration #102139 — presented by @misolori 
- Webview Views #46585 — presented by @mjbvz 

### APIs Mentioned
#### Released
- Authentication APIs (consumer) #100993 [Docs](https://code.visualstudio.com/api/references/vscode-api#authentication)
- `in` operator for `package.json` `when` clauses #97544
- Terminal links API #91290 [Docs](https://code.visualstudio.com/api/references/vscode-api#TerminalLinkProvider%3CT%3E)
- Custom editors APIs #77131 [Docs](https://code.visualstudio.com/api/references/vscode-api#CustomEditorProvider%3CT%3E)
- ColorThemes API #32813 [Docs](https://code.visualstudio.com/api/references/vscode-api#ColorTheme)
- View-level progress - #92421 [Docs](https://code.visualstudio.com/api/references/vscode-api#ProgressOptions.location)
- [Codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html)
- View icons [Docs](https://code.visualstudio.com/api/references/contribution-points#contributes.views)

#### Coming Soon in 1.50
- Submenus #100172

#### Proposed
- Proposed Authentication APIs (producer) #88309
- TreeView markdown hovers & resolve #100741

### Related Topics
- Explore integration between extensions view and GitHub Sponsors #107482

Looking forward to next month!

P.S. Extension authors — join our community run [VS Code Developer Community Slack](https://aka.ms/vscode-dev-community) 😄
