### ISSUE TITLE
          How to manage watch viewlet by program?

### ISSUE THREAD

**Issue by Nina0408** [microsoft/vscode#106230]
Hi there,

how to manage watch expressions when debugging, do we have any doc about it?

I am developing a debugger and in watch viewlet by its default behavior, when start a new debug session, the previous watch expressions will be there also, and I can add the same name expression into watch viewlet, and the value of them will not changed anymore, they are in chaos.  

Can anyone share me some experiences on how to manage watch viewlet by program?

Thanks!

**Comment by weinand** [comment]
The Watches view is a pure VS Code feature. The debug adapter protocol (DAP) knows nothing about the Watches
view.

VS Code implements "Watches" as expressions (strings) and sends them to the debug adapter via a DAP "evaluate" request whenever the debug sessions stops.

Since Watches are just strings, they can be created at any time (even when no debugger is active) and they survive the debug session and needs to be deleted manually. In this respect Watches are very similar to Breakpoints.

There is no explicit API for manipulating watches but there is a command for removing watches: `debug.removeWatchExpression`.

**Comment by dodig-cel** [comment]
> The Watches view is a pure VS Code feature. The debug adapter protocol (DAP) knows nothing about the Watches
> 
> view.
> 
> 
> 
> VS Code implements "Watches" as expressions (strings) and sends them to the debug adapter via a DAP "evaluate" request (with `context: "watch"`) whenever the debug sessions is suspended.
> 
> 
> 
> Since Watches are just strings, they can be created at any time (even when no debugger is active) and they survive the debug session and need to be deleted manually by the user. In this respect Watches are very similar to Breakpoints.
> 
> 
> 
> Watches (as well as Breakpoints) are owned by the user, and VS Code or any debug extension should not remove them.
> 
> There is no explicit API for manipulating watches.

**Comment by Nina0408** [comment]
Thank you for your answering!!

For breakpoints, there is a command to remove all breakpoints by calling ```
vscode.commands.executeCommand(
            'workbench.debug.viewlet.action.removeAllBreakpoints'
        );
```
for all watch expressions, is there any commands as above to do it?

and for "evaluate" request, when the debug session is suspended, I can use "evaluate" request to set the value to watch expression, am I right?

Thanks!!

**Comment by Nina0408** [comment]
And I also found an issue: sometimes I add some new expressions to watch during debug session, it does not work, they are not displayed in watch viewlet. But after debug session ended, the watch expressions will be displayed. that's wired.

**Comment by weinand** [comment]
@Nina0408 you asked:

> for all watch expressions, is there any commands as above to do it?

no, there isn't. 

> and for "evaluate" request, when the debug session is suspended, I can use "evaluate" request to set the value to watch expression

No, "you" cannot run the "evaluate" request to set the value of a watch expression.
But VS Code will run the  "evaluate" request on the watch expression and will update the value in the watches view whenever the debug session is suspended.

> And I also found an issue

Please file a separate issues with reproducible steps

**Comment by Nina0408** [comment]
Thanks @weinand for your answering. it really helped a lot.
