### ISSUE TITLE
Problems View only showing active file although 'Show Active File Only' is unchecked.

### ISSUE THREAD

**Issue by martijnvanschie** [microsoft/vscode#106231]
- VSCode Version: 1.48.2
- OS Version: Version 2004 (OSBuild 19041.450)

Steps to Reproduce:

1. Open a project that contains at least one file with problems
2. Close all active files.
3. No problem is shown.
4. Open a file with 1 or more problems
5. Problems view shows list of problems.

Does this issue occur when all extensions are disabled?: 
Ran command `code --disable-extensions` to validate. Issue was not reproducible but then there are no problems found at all. Probably problems from other extensions are not globally scanned but should that then be implemented or at l;east be more informative?

No problems reported and `Show Active File Only` is disabled.
![image](https://user-images.githubusercontent.com/8370550/92384073-b8799280-f10f-11ea-8a44-d6ee992d8c54.png)

Problems are listed.
![image](https://user-images.githubusercontent.com/8370550/92384150-d3e49d80-f10f-11ea-9e56-67ad318252e7.png)

**Comment by sandy081** [comment]
> Probably problems from other extensions are not globally scanned but should that then be implemented or at l;east be more informative?

Yes, extensions are not generating problems for all files. If they are errors in more than one file then disabling the filter shall show all problems and enabling the filter shall show only for active file.

I do not think any action can be taken here.
