### ISSUE TITLE
Rerun Task didn't update task attribute

### ISSUE THREAD

**Issue by roycpp** [microsoft/vscode#106290]
- VSCode Version:1.48.2
- OS Version:Win7

attribute in "labeled task" not updated while rerun task

example:
`"tasks":[
    {
        label: "abc",
        ...
        "options": {
            "cwd": "${workspaceFolder}"
        }
    }
]`

Steps to Reproduce:

1. run compile task -> ok
2. make some update on "cwd" for example: "cwd": "${workspaceFolder}/dir_which_not_exist"
3. rerun task -> still ok (suppose this should fail since the path does not exist)
4. run compile task again -> fail (this is the expected behavior)

ps: only occur at the options of "labeled task" but not "tasks"
for example this is working well with the above step:

`"tasks":[
	{
		label: "abc",
		...
	}
],
	"options": {
		"cwd": "${workspaceFolder}"
	}`

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Rerun task uses the exact task that was previously run to be as fast as possible. It doesn't take any changes to the task into account.
