### ISSUE TITLE
Debounce code lens request based on average duration

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#106267]
Currently, the VS Code used the adaptive debouncing in the outline view and we found that this is very useful strategy to improve the performance. For example, we tried this in our Code Lens provider and it do help a lot for the performance.

So is it possible to provide an API or in whatever form to expose it and let the extension writer be able to use it?

**Comment by jrieken** [comment]
Do you have some more details for me? Most language features use the provider pattern, like DocumentSymbolProvider or CodeLensProvider, which means extension shouldn't be concerned with debouncing because part of the contract is that VS Code decides when to ask a provider for data. 

Can you elaborate how you have used that in your Code Lens provider?

**Comment by jdneo** [comment]
Sure, for example, in Java Test Runner, if the user is editing a very large test source file, usually it will take a while to resolve the the code lenses (send a request to Language Server and wait for the response). We found the adaptive debounce is very useful because:
- When the user is keep editing, the adaptive debounce can simply eliminated those cancelled request by checking the cancellation token.
- Since the debounce time is adaptive and calculated by its historical execution time, so it will be more suitable, and the language server can have more time to do some more important tasks(like completion), before the debounced request goes in.

**Comment by jrieken** [comment]
Hm, wouldn't it be better if VS Code also uses the debouncing for code lens requests? With that every extension would benefit from it without adopting anything

**Comment by jdneo** [comment]
Yes I think enabling adaptive debounce in code lens requests is exactly what we we want to have.

So... will it be an optional setting when register the code lens provider or it will just enabled inside vs code without exposing anything?

**Comment by jrieken** [comment]
Yeah, I'd say we will just enable it - just like we did it for outline. Today, code lens [statically debounces](https://github.com/microsoft/vscode/blob/c112f845f010a4b428a148d826e33dbb20d3f7fe/src/vs/editor/contrib/codelens/codelensController.ts#L156) at 250ms and we can use the same mechanism we use for outline, e.g keep a moving average per file and debounce by that (without lower/upper bounds)

**Comment by jdneo** [comment]
Thank you @jrieken !

**Comment by jrieken** [comment]
No problem - will be in next 1.50 insiders (end of this week), let me know if things work for you

**Comment by jdneo** [comment]
Hi @jrieken, 

I tested in insider today, below is the version info:

Version: 1.50.0-insider (user setup)
Commit: cca20eba8974b1d6b6a9b71bf4e60a29c8f26648
Date: 2020-09-12T01:04:21.398Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

It seems that the debounce is not working. What I did is force the provider to sleep for 3 sec (to make sure the moving average will be a large number), but I observed that the codelens provider still gets triggered very soon after editting. Below is a gif to illustrate that:

![demo](https://user-images.githubusercontent.com/6193897/93038384-68528100-f677-11ea-87dd-4675ec5d833c.gif)

**Comment by jrieken** [comment]
Sorry for that. I had missed the cases in which we schedule code lens requests directly. I pushed a change to make this less error prune. Should be working now but note that I have clamped things between 250ms (fastest) and 2500ms (slowest), so your 3sec sample won't get the full 3 second delay

**Comment by jdneo** [comment]
Thank you @jrieken! I'll try it tomorrow.

**Comment by jdneo** [comment]
@jrieken It's working now. If I force the execution to wait for a long time (> 2s), the code lens provider will also wait more to get triggered.

**Comment by jrieken** [comment]
@jdneo Thanks for the update

**Comment by jdneo** [comment]
Hi @jrieken, Do you think that it makes sense to apply this kind of mechanism to other APIs. For example, the callback for `onDidChangeTextDocument`?

**Comment by jrieken** [comment]
I depends - for providers debounce makes sense but I wouldn't generally do it for events, esp. not for `onDidChangeTextDocument`. Debouncing would have the potential for bogus behaviour, e.g. the document-value is already updated but the event isn't fire yet. I see the need to debounce event-listeners but for that I'd be in favour of making our [event-utils](https://github.com/microsoft/vscode/blob/e06678160f016e3063c687243a88fe13b5fb52aa/src/vs/base/common/event.ts#L20) re-usable (for instance as npm module or API extension)

**Comment by jdneo** [comment]
> for that I'd be in favour of making our event-utils re-usable (for instance as npm module or API extension)

Agree. It would be very helpful to have such npm module / API, and the extension authors can decide to use it or not by themselves according to their own use cases.
