### ISSUE TITLE
CoffeeScript go to definition support - not resolved, not caused by an extension!

### ISSUE THREAD

**Issue by sunyamare** [microsoft/vscode#106272]
I found that when working with .coffee files (CoffeeScript) in VSCode, the basic feature "go to definition" for imported functions does not work.

I checked existing issues and found this: https://github.com/microsoft/vscode/issues/75420
It is marked as caused-by-extension. That is not the case! I am using VSCode version 1.48.2 without extensions on MacOS version 10.15.6 and it is not working!

Please be more specific about what extension is supposedly causing this?

**Comment by gjsjohnmurray** [comment]
I could be wrong, but AFAIK there's no built-in CoffeeScript support. Extension Marketplace finds plenty of matches for "coffeescript".

**Comment by sunyamare** [comment]
Hi @gjsjohnmurray thanks for the fast response. That is correct, there is no built-in support for CS. However, the out-of-the-box syntax highlighting is "good enough". There are extensions on the marketplace that optimize that. However, I'd gladly trade the "go to definition" functionality for the slight improvement in syntax highlighting, if an extension really causes the go to definition not to work. Hope that makes sense.

So I'm basically just trying to find out which extension is supposed to break this functionality? The most common CS extension seems to be coffeescript-support. This one does not seem to break the functionality (as the functionality does not work without the extension either).

**Comment by sunyamare** [comment]
Based on the generic response of the bot above, I take it that no extension broke the "go to definition" functionality for .coffee files, but that it simply doesn't work with vscode (with or without any extensions), and CS support would need to be added manually with a custom extension. 
Hope this helps others reading this.

**Comment by mjbvz** [comment]
Yes,  @gjsjohnmurray is correct that VS Code does not have built-in coffee script support (besides basic syntax highlighting)
