### ISSUE TITLE
OneDrive does not work with git clone command

### ISSUE THREAD

**Issue by Joeclinton1** [microsoft/vscode#106287]
- VSCode Version: 1.48.2
- OS Version: Microsoft Windows 10 Home 10.0.18362 Build 18362

Steps to Reproduce:

1. Create folder within Onedrive
2. Use command git clone \<url of github repository\> \<File path to One drive folder\>
3. Receive the error: `fatal: Invalid path 'c:/Users/Joe/OneDrive': Invalid argument`

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
If you're able to do this outside VSCode but not within it then please post more information here.

But if you're not able to do it on your PC independently of VSCode then your problem isn't VSCode specific. Try an internet search for "git onedrive", and close this issue here.

**Comment by Joeclinton1** [comment]
Ok, it also doesn't work outside of vscode. Thank you.
