### ISSUE TITLE
Some unit tests doesn't work by following webpack guideline

### ISSUE THREAD

**Issue by ShenChen-Amazon** [microsoft/vscode#106269]
Issue Type: <b>Bug</b>

Hi I was trying to build some tests for my extension which use webpack to bundle. I was following this doc: https://code.visualstudio.com/api/working-with-extensions/bundling-extension.

However, when I write some unit test such as
```
const extensionId = 'vscode-samples.webpack-sample';
const extension = vscode.extensions.getExtension(extensionId);
if (extension) {
    await extension.activate();
    assert.ok(extension.isActive);
} else {
    assert.fail('Extension is not available');
}
```
The unit test failed with error: Error: Cannot find module '/Users/shench/vscode-extension-samples/webpack-sample/dist/extension'.

In package.json, the main is point to dist/extension as per recommended. The issue will be resolved if I change main point to out/extension (The complied output).

**Steps to reproduce:**
1. Download the webpack sample: https://github.com/microsoft/vscode-extension-samples/tree/master/webpack-sample.
2. Create test folder such as helloworld-test-sample: https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample. Add required dependencies in package.json, and install all dependencies.
3. replace the test with the code I provided above.
4. In .vscode/launch.json, update the testsPath: "--extensionTestsPath=${workspaceFolder}/out/test/suite/index"
5. start extension tests task

From my understanding, it seems some vscode api such as activate() will try to load from dist/extension ? Thus some famous extension such as [aws-toolkit](https://github.com/aws/aws-toolkit-vscode/blob/master/extensionMain.js#L20) and [docker extension](https://github.com/microsoft/vscode-docker/blob/master/main.js#L20) both use a high level entry point to solve this conflict. Please see the link of how they implement their entry file.

I am not sure if it's the best practice to follow ? Any suggestions would be appreciated :)

Thanks,
Shen

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:09:41.484Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 13, 10|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.5.0
vscode-pull-request-github|Git|0.19.0
vscode-codemetrics|kis|1.24.0
vscode-github|Kni|0.30.3
vscode-docker|ms-|1.5.0
vscode-typescript-tslint-plugin|ms-|1.2.3
code-spell-checker|str|1.9.0
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by ShenChen-Amazon** [comment]
Hi @jrieken ,

Could you please point me to the original issue ? Hard to find it :)

Thanks,
Shen

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/85779
