### ISSUE TITLE
AutoSave not consistently syncing changes to Markdown files saved to OneDrive

### ISSUE THREAD

**Issue by jx22** [Microsoft/vscode#10628]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

I discovered this issue when I opened a file on a second computer and the most recent changes, which were large and important, were not visible. They were still visible on my first computer, where I still had the file open in VSCode.

Note: After I disabled extensions (including vscode-icons and Spelling and Grammar Checker), autoSave seemed to be correctly. But for now I am still hesitant to trust VSCode to autoSave changes.

Steps to Reproduce:

1. Enable autoSave in Workspace settings. I use `"files.autoSave": "afterDelay", `and 
`"files.autoSaveDelay": 10,`
2. Create new and save with a .md extension to OneDrive
3. Edit file. File changes should be synced automatically to OneDrive given that autoSave is enabled. Open the file on onedrive.com to check if the edits have been synced.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
