### ISSUE TITLE
Open editors view: context keys are very generic

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#106246]
While going through some of the editor related context keys I noticed that the "Open Editors" view seems to define very generic keys that might confuse users, such as:
* `readonlyEditor`
* `dirtyEditor`

I feel these should make clear what they are, because they seem to reflect the state of the selected editor in the open editors view and not the active editor that is opened. I suggest to rename to better reflect their source if possible.

**Comment by isidorn** [comment]
This makes sense. I have renamed them to
* `readonlyEditorFocusedInOpenEditors`
* `dirtyEditorFocusedInOpenEditors`

They were never exposed in docs or api so it is fine to rename.

**Comment by bpasero** [comment]
Thanks!
