### ISSUE TITLE
Color scheme auto detect doesn't sync with the Windows scheme change made when VSCode was closed

### ISSUE THREAD

**Issue by synchronos-t** [microsoft/vscode#106229]
- VSCode Version: 1.48.2
- OS Version: Windows 10 (v2004)

Steps to reproduce (at least one way):

1. Use a workspace
2. Set Windows to dark mode (if not already)
3. Set workspace settings to `window.autoDetectColorScheme` on and `workbench.colorTheme` to some dark theme
4. Close VSCode and wait for at least 15 seconds
5. Set Windows to light mode
6. Open VSCode

After these steps, the VSCode doesn't seem to switch to light mode, but stays on dark mode. (For some reason, it does sync if I switch to the light mode right after closing VSCode. But not if I wait at least 15 seconds. This is perhaps related to the Chromium process shutdown?)

My expectation would be that the `window.autoDetectColorScheme` would always keep the VSCode theme in sync, regardless of whether the OS color scheme was changed while VSCode was open or when it was closed. At least I can't think of any use case where I would want the color scheme to match only if I changed my OS theme while VSCode was open, but not when it was closed, so my strong assumption is that this is indeed a bug and not as it was designed.

My workspace settings has also the `workbench.preferredDarkColorTheme` set, but not the `workbench.preferredLightColorTheme`, as I'm fine it using the default light theme, but I don't think it affects this. At least it shouldn't.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please check if it's reproducible in Insiders build https://code.visualstudio.com/insiders/ ?
Most likely fixed in scope of #105102
