### ISSUE TITLE
vscode manjaro any messaage popup  will crash the program

### ISSUE THREAD

**Issue by SarkarKurdish** [microsoft/vscode#106260]
i've been using manjaro for while any time vscode try to show a popup for example for saving a file vscode will crash, open external link will crash, try to delete a file will crash

i'm using latest version of vscode

my spec
Ram: 4gb
Cpu: core i5 4th gen
gpu: nividia gefore 820m

**Comment by IllusionMH** [comment]
Are you using snap? Probably duplicate of #100940
