### ISSUE TITLE
Build release?

### ISSUE THREAD

**Issue by dmitsuki** [Microsoft/vscode#1062]
Hi.

The editor did not have subword Navigation or scrolling with the keyboard. I added both of these however I can't actually figure out how to build a release build to use. How do I go about that?

**Comment by egamma** [comment]
Pls see: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

**Comment by dmitsuki** [comment]
Hi, 

Yes I know about that page, but isnt that just how to juild and debug? I have been doing that, but how do I build a stand alone release non debug biild?

**Comment by egamma** [comment]
Some of the gulp tasks are minimally documented here https://github.com/Microsoft/vscode/wiki/Code-Build-Process
