### ISSUE TITLE
Indent guides should use `guides` setting from tmTheme, not `invisibles`

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#10624]
- VSCode Version: Code - Insiders 1.5.0-insider (11ffcfcf69608c07e7db4b4c77856854d5083497, 2016-08-16T06:12:46.372Z)
- OS Version: Linux x64 4.4.0-34-generic, Ubuntu 16.04

In order to be consistent with Sublime Text.

**Comment by alexandrudima** [comment]
Nice catch!

**Comment by Tyriar** [comment]
Whitespace might also use guide, I'm not 100% sure.

**Comment by sandy081** [comment]
I am not sure if white space rendering uses guide setting.. I think there is a different setting `highlight.whitespace`.
