### ISSUE TITLE
Command suggestion "editor.action.collapseAll"

### ISSUE THREAD

**Issue by AzuStar** [microsoft/vscode#106284]
Actually surprised this simple feature no one requested before.
Command "editor.action.collapseAll"
Especially heavy files with like 2-3k lines, it is naturally hard to read/navigate.
Regions really help solve this, but if you want to collapse all regions (such as for loops, classes, practically any brackets, #region in c# and so on) you need to do this manually for the entire document, only then you can take a look at the structure and begin expanding things you need.

Screenshot of what I mean (just to be safe)
![image](https://user-images.githubusercontent.com/52426335/92477656-a53af580-f1e9-11ea-8ba2-1a8499ee3e13.png)

Some command to recursively collapse everything in selected document would be gr8!

**Comment by gjsjohnmurray** [comment]
Did you see the 'Fold All' command in the palette? It is `editor.foldAll` and has a keybinding by default. My little folding helper extension [The Folding Stuff](https://marketplace.visualstudio.com/items?itemName=georgejames.thefoldingstuff) adds this to the editor context menu along with several other fold/unfold commands.

**Comment by AzuStar** [comment]
OK, my bad, sorry for inconvenience :(
And to answer - no I didn't see the 'Fold All'
I naturally assumed since you can "collapse folders in explorer", it would be something like "collapse all code blocks".
