### ISSUE TITLE
Source control sync icon rotates wavy

### ISSUE THREAD

**Issue by massimo-cassandro** [microsoft/vscode#106275]
- VSCode Version: 1.48.2
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. pull/push any repository. See attached gif

![not centered icon](https://user-images.githubusercontent.com/1047169/92453308-65f7af00-f1bf-11ea-8626-705a8cacf993.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This is already fixed in `master`.
