### ISSUE TITLE
Windows Crash When Moving Terminal

### ISSUE THREAD

**Issue by grintaux** [microsoft/vscode#106252]
Issue Type: <b>Bug</b>

It keeps crashing while I'm moving terminal to another view location on VSCode.
It doesn't matter any process going on or which terminal I use ( like WSL or PowerShell ) or not running a terminal.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (3.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (113)</summary>

Extension|Author (truncated)|Version
---|---|---
30-seconds-of-code|30-|1.0.0
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
Bookmarks|ale|11.3.1
project-manager|ale|11.3.0
ng-template|Ang|0.1000.8
vscode-browser-preview|auc|0.6.7
vscode-database|baj|2.2.3
vscode-django|bat|0.20.0
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-node-readme|ben|3.0.2
vscode-tailwindcss|bra|0.4.3
phpserver|bra|3.0.1
simple-react-snippets|bur|1.2.3
vscode-standardjs-snippets|cap|0.8.15
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
disableligatures|Coe|0.0.8
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
vscode-npm-source|dku|1.0.0
python-extension-pack|don|1.6.0
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.5.0
vscode-firefox-debug|fir|2.9.1
auto-close-tag|for|0.5.8
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.4
github-extend-util|git|0.0.4
vscode-codeql|Git|1.3.2
vscode-pull-request-github|Git|0.19.0
sass-lint|gle|1.0.6
vscode-test-explorer|hbe|2.19.1
vue-snippets|hol|0.1.12
rest-client|hum|0.24.2
discord-vscode|icr|4.0.0
search-node-modules|jas|1.3.0
vscode-pigments|jas|2.0.0
react-vscode-extension-pack|jaw|0.4.0
svg|joc|1.3.9
vscode-gist|ken|3.0.3
kite|kit|0.122.0
node-module-intellisense|lei|1.5.0
MagicPython|mag|1.1.0
sass-extension-pack|mag|1.0.1
markdown-formatter|mer|0.8.8
vscode-language-babel|mgm|0.0.29
git-graph|mhu|1.25.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.17
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.5.0
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.8.106424
vscode-pylance|ms-|2020.9.0
remote-containers|ms-|0.134.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.2
vscode-github-issue-notebooks|ms-|0.0.50
cordova-tools|msj|1.9.5
debugger-for-chrome|msj|4.12.10
vscode-react-native|msj|0.17.0
vuejs-extension-pack|mub|1.2.1
jsflowchart|MUL|0.1.6
vscode-for-node-js-development-pack|nod|2.0.1
vetur|oct|0.27.2
indent-rainbow|ode|7.4.0
vscode-versionlens|pfl|1.0.8
material-icon-theme|PKi|4.2.0
polacode|pnp|0.3.4
seti-icons|qin|0.1.3
quicktype|qui|12.0.46
try-material-icon-theme|raf|3.9.0
fabric8-analytics|red|0.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|2.1.5
vscode-spotify|shy|3.1.0
html5-boilerplate|sid|1.0.3
vscode-fileutils|sle|3.0.1
snipsnap-vscode|sni|1.1.0
music-time|sof|2.0.16
swdc-vscode|sof|2.3.7
sass-indented|syl|1.8.11
ayu|tea|0.20.1
html-preview-vscode|tht|0.2.5
vscode-status-bar-format-toggle|tom|2.0.0
lorem-ipsum|Tyr|1.2.0
highlight-matching-tag|vin|0.9.9
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|10.2.0
nodejs-extension-pack|wad|0.1.9
quokka-vscode|Wal|1.0.317
jinja|who|0.0.8
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
file-size|zh9|0.1.3
material-theme|zhu|3.8.7
output-colorizer|IBM|0.1.2

(8 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you take a gif of the crash? https://gifcap.dev/
