### ISSUE TITLE
tmTheme bold fontStyle is not supported

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#10623]
- VSCode Version: Code - Insiders 1.5.0-insider (11ffcfcf69608c07e7db4b4c77856854d5083497, 2016-08-16T06:12:46.372Z)
- OS Version: Linux x64 4.4.0-34-generic, Ubuntu 16.04

Scopes with bold `fontStyle` do not appear bolded in vscode.

```xml
        <dict>
            <key>name</key>
            <string>Keyword</string>
            <key>scope</key>
            <string>keyword</string>
            <key>settings</key>
            <dict>
                <key>fontStyle</key>
                <string> bold</string>
                <key>foreground</key>
                <string>#d7503c</string>
            </dict>
        </dict>
```

**Comment by Tyriar** [comment]
@aeschli :tada: thanks :smile:

**Comment by dyu** [comment]
This bug reappeared in vscode 1.6
I'm on Ubuntu 14.04 x64

**Comment by dyu** [comment]
Opened #13470
The bug could be from electron
