### ISSUE TITLE
FileUserDataProvider unit test failures

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#106283]
```
1) FileUserDataProvider "after each" hook for "exists return false when file does not exist":
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

```

https://dev.azure.com/vscode/VSCode/_build/results?buildId=52258&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=08e986c2-058e-5f01-51da-ae4278e2d74e&l=13650

Somehow recently this test seems to fail, ever since we upated to Electron 9.3.0, but I do not see a correlation here that could be obvious.

**Comment by sandy081** [comment]
Looks like following change has caused this, I am using fileService to clean up the test folder now (before I was using node api directly). 

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/10746682/92495369-1df47e80-f1f7-11ea-812c-891288232bb2.png">

@bpasero Seems file service is taking time to clean up in windows. Do you suggest to move back to node api?

**Comment by bpasero** [comment]
@sandy081 

> Seems file service is taking time to clean up in windows

I am not sure I follow, the call should return when done. I think you are not using the `trash: true` feature so at least that will end up going through very comparable code like `rimraf`.

**Comment by sandy081** [comment]
> I am not sure I follow

Test has a post run task (after each hook) that deletes a folder. Before, I was using `pfs.rimraf(rootPath, pfs.RimRafMode.MOVE)` and I replaced that with `fileService.del(rootResource, {recursive: true})` call. 
Looking at the failure, fileService is taking more than 5s to complete.

will try `trash: true`

**Comment by bpasero** [comment]
@sandy081 sorry for the confusion, I was NOT suggesting to use `trash: true`. I don't think delete takes longer than 5s, rather I think there is some unhandled rejection within that is not bubbling up properly. Could it be a bug in the file system provider implementation? Isn't that yours?

**Comment by sandy081** [comment]
`trash: true` did not work - it complained that the provider does not support it.

So reverted the change to use node api directly.

**Comment by bpasero** [comment]
@sandy081 I found the issue: your user data provider is watching on the root folder here:

https://github.com/microsoft/vscode/blob/bb27a30efa01771b217b3844171b36fcf961bc2b/src/vs/workbench/services/userData/common/fileUserDataProvider.ts#L48

As such, on Windows you cannot delete a folder that is being watched. The fix is to first dispose that provider and then delete.

See my change in https://github.com/microsoft/vscode/commit/1d177e247c5dc16f772d0b78aaa6cbbe5944124b

**Comment by sandy081** [comment]
Great. Thanks for the fix/
