### ISSUE TITLE
Language extension: move cursor between parens, after function autocomplete

### ISSUE THREAD

**Issue by petar-dambovaliev** [microsoft/vscode#106281]
At the moment, when i select the function from autocomplete, the cursor is at the underscore position.
myFunc();`_`
and i want it to be
myFunc(`_`);

I have tried to do this in any imaginable way.
In the client middleware i have `resolveCompletionItem` method.
I do the following but nothing happens.

```
const editor = window.activeTextEditor;
const position = editor.selection.active;				
var newPosition = position.with(position.line, position.character + 5);
var newSelection = new Selection(newPosition, newPosition);
editor.selection = newSelection;
```

**Comment by jrieken** [comment]
Make the [`insertText`](https://github.com/microsoft/vscode/blob/ab4892d63b5949638353d1fc0b2164ea506c1cdf/src/vs/vscode.d.ts#L3845) be a `SnippetString` and use snippet syntax to define the final cursor position, e.g `myFoo($0)`
