### ISSUE TITLE
macOS: Integrated Terminal Defaults to Bash, Rather Than the User's Shell

### ISSUE THREAD

**Issue by cpsauer** [microsoft/vscode#106219]
Issue Type: <b>Bug</b>

If you use zsh on macOS (the default as of 10.15), the integrated terminal instead defaults to opening bash. The expected behavior would be opening the default shell that the user has selected with chsh -s, without needing to set "terminal.integrated.shell.osx" in preferences.

(chsh -s /bin/zsh is the Apple-suggested upgrade path from the default bash--a version now more than 12 years old)

Thank you VSCode team for an unbelievably great piece of software!

-CS

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

**Comment by Tyriar** [comment]
VS Code picks up the shell from `$SHELL` which is what chsh changes. note that you'll need to close all windows to reset VS Code's environment if you changed it while it was open though.

**Comment by Tyriar** [comment]
This is how we pull the default shell if you're interested:

https://github.com/microsoft/vscode/blob/0fbda8ef061b5e86904a3c4265c9f3ee0903b7fd/src/vs/workbench/contrib/terminal/node/terminal.ts#L34-L51

**Comment by cpsauer** [comment]
Sorry about that, @Tyriar. Thanks for replying so fast.

**As a heads -- and in case anyone else finds a similar issue:**
- Just closing VSCode doesn't do it. (Tried that well before bugging you :) )
- The root issue seems to be that macOS's various launchers keep passing the old environment variables on to VSCode until they're restarted.
  - So you can make the change, restart VSCode, and still have it open the old shell if you launch VSCode from Finder, the Dock, Spotlight...
  - Restarting the system or running `killall Dock ; killall Finder ; killall Spotlight; makes the right shell show up in the next launch from each of those places.
