### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by falnero** [microsoft/vscode#106238]
Issue Type: <b>Bug</b>

i cant see the problems in problem part ... and i dont know why ?!
please help me ... im gettin crazy

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:14:14.576Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.8.106424

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo a screenshot maybe? One way is to use Snipping Tool (part of Windows 10), copy to clipboard, then paste direct into GitHub reply.

**Comment by falnero** [comment]
normally when there is a problem it shows on problem part that which line has the problem but it doesn't work right now...after that i installed pycharm for django it happened
![Screenshot (31)](https://user-images.githubusercontent.com/70902181/92396557-70bc3080-f13a-11ea-868c-d5e0284312ff.png)

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/Microsoft/vscode-python/issues
Would you mind filing the issue there?
