### ISSUE TITLE
Context menu should dismiss hover

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#106268]
It is confusing to see both a hover and a context menu:

![image](https://user-images.githubusercontent.com/172399/92441649-dea23f80-f1ae-11ea-9dee-f691043b188d.png)

**Comment by alexr00** [comment]
Looks like @Tyriar has already fixed this generically for the hover service for September in https://github.com/microsoft/vscode/issues/106127

**Comment by Tyriar** [comment]
@alexr00 I'm surprised that would fix it? Does the native context menu trigger the intersection observer 😕

**Comment by alexr00** [comment]
@Tyriar I tried to repro it out of master and I couldn't. I wonder if this is platform specific. Have you removed `hideHover`? I didn't see it.

**Comment by Tyriar** [comment]
Yes `hideHover` is removed, you can add it back if you need it:

```ts
	hideHover(): void {
		if (!this._currentHoverOptions)
			return;
		}
		this._currentHoverOptions = undefined;	
		this._contextViewService.hideContextView();	
	}
```

https://github.com/microsoft/vscode/commit/a26e4fdd2018dea1c76a673e85e03c41f7000a64
