### ISSUE TITLE
[json] JSON language server not localized

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode#106220]
VSCode Version: VSCode 1.48.2

Steps to Reproduce:
1.Install VSCode
2.Install Language Extension Chinese(Simplified) and C++ extension
3.Open file “c_cpp_properties.json”
4. Delete the value or update value to an invalid one for property "cStandard"
5. Check the warning info in tooltip window

Expected:
Warning info in tooltip window

Actual:
Warning string “Value expected” and “Value is not accepted. Valid values" in file “c_cpp_properties.json” is not localized in tooltip window
(Repro on Windows, Linux and Mac)
![image](https://user-images.githubusercontent.com/37648162/92364022-01881180-f125-11ea-9a35-da919bd2ff57.png)

![image](https://user-images.githubusercontent.com/37648162/92364053-0e0c6a00-f125-11ea-8af6-588a20ad4e3f.png)

**Comment by PhoebeTf** [comment]
@weinand Sorry for mislead you when create this issue, this issue actually not related C++ Extension, as when we delete a value or update value to invalid one for VSCode property without C++ extension installed, issue still repro (Updated screenshot as below), could you help to double check this issue? Thanks.

Warning string “Value expected” in file “settings.json” is not localized in tooltip window
![valueEx](https://user-images.githubusercontent.com/37648162/92572646-493ea280-f2b7-11ea-9306-016404327c1d.PNG)

Warning string “Value is not accepted. Valid values" in file “settings.json” is not localized in tooltip window
![value_valids](https://user-images.githubusercontent.com/37648162/92572107-90786380-f2b6-11ea-84f3-81c1ec3ca678.png)

**Comment by v-ericawu** [comment]
"Trailing comma" in file “c_cpp_properties.json” is not localized:
![image](https://user-images.githubusercontent.com/78774400/130763667-47454356-8738-495c-97e4-e651dc10dcfb.png)
