### ISSUE TITLE
Cant open terninal and open local folder in the web based vs code

### ISSUE THREAD

**Issue by hasegetc** [microsoft/vscode#106205]
- VSCode Version: 1.48.2
- OS Version: win 10

Steps to Reproduce:

1. I build the vs code web version successful
2. yarn web, and my browser open localhost:8080
3. but I cant open a terminal, also I cant open a folder by the file->open folder command

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by hasegetc** [comment]
just like this:
![image](https://user-images.githubusercontent.com/5785979/92344655-a0971400-f0f9-11ea-908c-ad3e60374fa5.png)
![image](https://user-images.githubusercontent.com/5785979/92344672-aee53000-f0f9-11ea-94a8-964db0900a44.png)

**Comment by bpasero** [comment]
The web version of VSCode is work in progress and what you see is the expected behaviour.

**Comment by hasegetc** [comment]
could you point out the doc that describe the different  web version and the electron version?
