### ISSUE TITLE
Can't use shortcut "Add cursor above/below" [Windows]

### ISSUE THREAD

**Issue by KevinEsh** [microsoft/vscode#106256]
I can't use shortcut (Ctrl + Alt + Up/Down) to create mutiples cursors on a script. I've tried to assert functionality of the keys involved (All of them work with different shortcuts), to change my keyboard, reset shortcut config to default but none of these work. Here is a screenshot of shortcut configuration:
![image](https://user-images.githubusercontent.com/52937054/92414872-ce8d5000-f11b-11ea-9856-0ee67ddf0143.png)

- VSCode Version: 1.48.2
- OS Version: Windows 10

Steps to Reproduce:

1. Set my configuration
2. Try shortcut

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have Intel Graphics Application in tray or something like this?

If you got to Keyboard Shortcuts and select Record Keys and use any of this shortcuts do you see them in search field?
![image](https://user-images.githubusercontent.com/1312662/92417735-6b77d980-f16c-11ea-8d28-56f48c6cb60b.png)

**Comment by TedChenNZ** [comment]
When recording keys, when I try to press "ctrl + alt + uparrow" it only shows "ctrl + alt"
This occurs for all directions.

"ctrl + shift + uparrow" works, as does "ctrl + uparrow" and "alt + uparrow".

Windows 10.0.19042 Build 19042
Visual Studio Code 1.48.2

**Comment by alexdima** [comment]
@TedChenNZ This indicates that on your system you have a piece of software that "eats up" that keybinding. In the past, we have found that some Intel driver was doing this, but there may be more applications that would eat this keybinding. Unfortunately, there is nothing we can do on our side if we don't receive a keybinding from the OS.

**Comment by TedChenNZ** [comment]
While the Intel Graphics Command Center wasn't in the tray, it seemed to have somehow affected the keybind. Once I opened the app the keybind started working again.

I've now uninstalled Intel Graphics Command Center and everything seems to be working again. 

Thanks for pointing me in the right direction, @alexdima !
