### ISSUE TITLE
Visual Studio Code does not save files on a remote server

### ISSUE THREAD

**Issue by cawa-93** [Microsoft/vscode#10620]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:49:32.489Z)
- OS Version: Linux x64 4.4.0-34-generic

Steps to Reproduce:

1. Open in Nautilus remote server.
```
ftp://admin@91.225.136.204/www/example.com/
```
2. Open file in Visual Studio Code.
3. Change and Save file.

Details 
http://stackoverflow.com/questions/38993537/visual-studio-code-does-not-save-files-on-a-remote-server

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6854
