### ISSUE TITLE
cursor left in terminal

### ISSUE THREAD

**Issue by JaxVanYang** [microsoft/vscode#106271]
Issue Type: <b>Bug</b>

English description:
using powershell termial
1. input `git commit` without -m
2. input `i` to insert
3. input some commit info
4. after enter several word, you will see some cursors left in the terminal, and they can't be cleared by the command `cls` or `clear`
# Note: This bug won't be seen with English info, that is to say it will be only produced with Chinese commit info.

![image](https://user-images.githubusercontent.com/25650612/92456342-64e17480-f1f5-11ea-910f-09762aafeb65.png)

![image](https://user-images.githubusercontent.com/25650612/92448121-c05a3500-f1ea-11ea-956e-a58116093689.png)

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.0
todo-tree|Gru|0.0.178
Kotlin|mat|1.7.1
vscode-language-pack-zh-hans|MS-|1.48.3
python|ms-|2020.8.106424
cpptools|ms-|0.29.0
vscode-gradle|ric|3.4.3
LiveServer|rit|5.6.1
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by luboshanus** [comment]
I do experience the same problem. Cursor leaves traces in terminal. Not only for julia REPL.  Resizing terminal removes the traces. 

I have MacOS Catalina, VSCode Version: 1.49.1

![Screenshot 2020-09-25 at 12 59 39](https://user-images.githubusercontent.com/2473206/94278453-1d741b80-ff4b-11ea-9afc-2c69781120cc.png)

**Comment by JaxVanYang** [comment]
@luboshanus Thank for your reply, You can collect your machine data and create a new issue from mine. This issue was closed due to more information is needed, but I can't give more information. Hope you could help to fix this bug.
