### ISSUE TITLE
More flexible layout (split sidebars etc)

### ISSUE THREAD

**Issue by TheArcaneBrony** [microsoft/vscode#106254]
I am using VSCode on Linux for C# development, and being used to Visual Studio on windows, I'd like to be able to move panels freely, like you would on VS. An example of this would be to have the file tree on the left side, and the solution explorer on the right. Or for example the terminal being next to the output.
I realise that this might not currently be feasible, but if you can do it, please do, since it would be very useful, since now i have to switch between sidebar tabs constantly just to do my current workflow.

Thank you for taking some time to read my feature request!
- The Arcane Brony

**Comment by IllusionMH** [comment]
/duplicate

> for example the terminal being next to the output.

It is already implemented - you can drag views in panel or between panel and sidebar https://code.visualstudio.com/updates/v1_46#_flexible-layout

> An example of this would be to have the file tree on the left side, and the solution explorer on the right.

There is request for second sidebar #26777

**Comment by ig0rsky** [comment]
@TheArcaneBrony if you want grid like flexibility such as multiple panels or sidebars, then take a look at this: 
https://theia-ide.org/
