### ISSUE TITLE
Adding the shadow to the right-border of the line-numbering

### ISSUE THREAD

**Issue by hazho** [microsoft/vscode#106294]
Issue Type: <b>Feature Request or Style Modification</b>

many times the mouse selection causes un-desired actions like collapsing a class-block, thats is in a speed coding and selecting activities, in order to solve this issue we'll need a diffrence in the background color or a shadow in the right-border of the line numbering, this will solve other issue(horizontal scrol-bar) as well. as all of the backgrounds got same color and there is no such thing to distinguish them from each others.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 5.4.0-45-generic snap

**Comment by misolori** [comment]
@alexdima @bpasero thoughts on adding the scrolling shadow horizontally in the editor? Seems to make sense.

**Comment by bpasero** [comment]
Sorry, where exactly? Can you do a mockup?

**Comment by hazho** [comment]
![image](https://user-images.githubusercontent.com/20362375/98179993-01489e80-1f3b-11eb-9651-92dd5e8a45f0.png)
in between the line-numbers and the first column of the editing area, there is no differentiation to know where to click, if you click even 1mm left-side of the first litter of the line, it causes minimizing(-) of the block, if you can focus on the commented lines that has indentation, you'll see that there is a vertical line to indicate that this is the first column but the rest lines are not
