### ISSUE TITLE
Open folder and open file dialog freezes application.

### ISSUE THREAD

**Issue by dpronyaev** [microsoft/vscode#106279]
App freezes and does nothing when I click File - Open file or File - Open folder. After 10-20 secs file browser apeares. 
When iterating to the folders, freeze occured once again, every iteration.

- VSCode Version: 1.48.2 
- OS Version: Ubuntu 20.04.1

Steps to Reproduce:

1. Click File - Open folder (or Open file)
2. Watch the application freezed for about 10-20 seconds

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
@dpronyaev snap?

**Comment by dpronyaev** [comment]
> @dpronyaev snap?

Yes, it is. I've forgot to mention this.

deb works fine.

**Comment by deepak1556** [comment]
Are you using wayland ?

**Comment by dpronyaev** [comment]
No. "By default the Ubuntu 20.04
<https://linuxconfig.org/ubuntu-20-04-guide> desktop does not start Wayland
as it loads to Xorg display server instead".

вт, 8 сент. 2020 г., 18:11 Robo <notifications@github.com>:

**Comment by deepak1556** [comment]
There is a known issue with snap on wayland, thought it might be that https://github.com/microsoft/vscode/issues/99419. Can you confirm `$XDG_SESSION_TYPE` value ?

Weird I have been using snap on ubuntu 20.04 Xorg display and haven't seen this slowdown. What is the file manager you are using ?

**Comment by dpronyaev** [comment]
> $XDG_SESSION_TYPE

pdv@home:~$ echo $XDG_SESSION_TYPE
x11

**Comment by deepak1556** [comment]
I was not able to repro this yet, can you check if the issue persists with latest stable `1.49` ?

**Comment by dpronyaev** [comment]
> I was not able to repro this yet, can you check if the issue persists with latest stable `1.49` ?

1.49 installed via snap doesn't have described issue.

Thx you!

**Comment by deepak1556** [comment]
Thanks for confirming, closing this out.
