### ISSUE TITLE
Can't launch with preLaunchTask and execute vscode command

### ISSUE THREAD

**Issue by srfrnk** [microsoft/vscode#106276]
```
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```

Steps to Reproduce:

1. Use following `launch.json` and `tasks.json`
2. Start debugging
3. `build` task doesn't run
4. Comment: `"args": "${command:workbench.action.terminal.clear}",` line
5. `build` task runs but `command:workbench.action.terminal.clear` is not executed. (terminal is not cleaned)

Does this issue occur when all extensions are disabled?: Yes/No
**N/A** Can't debug Java w/o extension

```jsonc
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "java",
      "name": "Debug Current File",
      "request": "launch",
      "mainClass": "${file}"
    },
    {
      "type": "java",
      "name": "*********",
      "request": "launch",
      "mainClass": "*********",
      "projectName": "*********",
      "classPaths": ["*********", ""],
      "cwd": "${workspaceFolder}/*********",
      "preLaunchTask": "build",
      "args": "${command:workbench.action.terminal.clear}",
      "console": "integratedTerminal",
    }
  ]
}
```

```jsonc
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "build",
      "type": "shell",
      "command": [],
      "dependsOn": [
        "clear",
        "*********",
.
.
.
      ],
      "dependsOrder": "sequence"
    },
    {
      "label": "clear",
      "type": "shell",
      "command": [],
      "presentation": {
        "clear": true
      }
    },
.
.
.
  ]
}

```

**Comment by isidorn** [comment]
Yeah, my guess is that the command clears the terminal, and that the task is waiting for some terminal output to complete and thus it never completes and thus debugging does not start.
I think this is expected behavior. Though assigning also to @alexr00 so she can share her thoughts.

**Comment by alexr00** [comment]
Since `workbench.action.terminal.clear` doesn't return a string, variable resolution returns `null` and this line is hit: https://github.com/Microsoft/vscode/blob/2a9a512ee4e4cd57f21551533c662cc612b831c4/src/vs/workbench/contrib/debug/browser/debugService.ts#L415-L415 
Debug never reaches the prelaunch task because of this.

**Comment by isidorn** [comment]
Yeah good point.

**Comment by srfrnk** [comment]
This prevents using vscode commands for launching debug sessions.
Does that mean vscode doesn't support that anymore?
The documentation does not make it clear that such behaviour is acceptable: https://code.visualstudio.com/docs/editor/variables-reference#_command-variables
Further more this funcionality was described as solving https://github.com/microsoft/vscode/issues/11396 which it apparentaly doesn't. If this is the expected behaviour here maybe this other request should be reopened?

**Comment by alexr00** [comment]
If your command returns a string then it will work. It is required that the command return a string if you're going to use it in a command variable. The documentation does say that a string return value is needed, but perhaps the language isn't strong enough. I will update to make that clear.

**Comment by srfrnk** [comment]
Thanks. However besides documentation changes this means that https://github.com/microsoft/vscode/issues/11396 is not really satisfied as you cannot run 'vscommands' as 'tasks'. The command I'm trying to perform pre-debug is the `workbench.action.terminal.clear` command which is supposed to clean the integrated terminal to be able to have a clean debug log. This command is internal to vscode so I cannot change it's return value. That leaves this capability unattainable. Any workaround would be gladly accepted.
