### ISSUE TITLE
Show Opened Editors menuitem does not show its keyboard shortcut.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoft/vscode#106236]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

The ellipsis menu at the right of the editor tab well contains the following three items.

Show Opened Editors
Close All
Close Saved

The entries for Close All and Close Saved list the keyboard shortcut to the right. The entry for Show Opened Editors does not.

I just spend 20 minutes trying to work out what the command was for Show Opened Editors so I could create a shortcut for it before finding out that it has the default shortcut of CTRL+P but it just isn't shown.

The UI for creating a keyboard shortcut appears to have changed, I couldn't find the split JSON view that shows default and overridden keyboards shortcuts anywhere, which is one reason why a task that would have taken me 5 minutes before became a diversion I would have preferred to do without.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (0.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.9
path-intellisense|chr|2.2.0
xml|Dot|2.5.0
EditorConfig|Edi|0.15.1
LogFileHighlighter|emi|2.8.0
vscode-great-icons|emm|2.1.47
vscode-jasmine-test-adapter|hbe|1.6.2
vscode-test-explorer|hbe|2.19.1
classic-asp|ili|0.0.4
vscode-nuget-package-manager|jmr|1.1.6
csharp|ms-|1.22.0
debugger-for-chrome|msj|4.12.10
nativescript|Tel|0.11.0
subtle-brackets|raf|3.0.0
code-settings-sync|Sha|3.4.3
rewrap|stk|1.11.1
insert-special-symbol|swi|1.3.0
indent-one-space|use|0.2.6
html-css-class-completion|Zig|1.19.0

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Standard menu looks like this:

![image](https://user-images.githubusercontent.com/6726799/92395651-8ff79580-f11b-11ea-825b-db2f4a740d2f.png)

**Comment by IllusionMH** [comment]
@gjsjohnmurray it's about `...` menu, not context
![image](https://user-images.githubusercontent.com/1312662/92395823-a35f2c80-f12c-11ea-855f-f1eef9c35094.png)

@Neutrino-Sunset while it's not caused by extension it still functions as designed.
Show Opened Editors menu item uses `workbench.action.showEditorsInGroup` command which has separate keybinding from <kbd>Ctrl</kbd>+<kbd>P</kbd> (which is set for `workbench.action.quickOpen`).

**Comment by Neutrino-Sunset** [comment]
Got it. Thanks for that.

I notice the Show Opened Editors list has a close button for each entry, is there any way to assign a keyboard to that close button? Given the typically overlong file naming conventions used in Javascript I find the document tab headers to be not very useful for managing the open documents, if I could close unused ones from the Show Opened Editors list that would be a bit help.
