### ISSUE TITLE
Unable to install sfdx-diff plugin using Terminal

### ISSUE THREAD

**Issue by kushalbhalodia** [microsoft/vscode#106326]
Issue Type: <b>Bug</b>

Summary
When I tried installed sfdx-diff using command "sfdx plugins:install @salesforce/sfdx-diff" it throws an error "TypeError: Cannot read property 'dim' of undefined"

Steps To Reproduce:
Install VSCode
Install Salesforce Extension Pack from extensions.
From the VSCode Terminal, Type "sfdx plugins:install @salesforce/sfdx-diff"
Expected result
Plugin should have installed

Actual result
Error: TypeError: Cannot read property 'dim' of undefined

Additional information
![92566156-6795a580-f299-11ea-83ad-02d8944af2de](https://user-images.githubusercontent.com/3942456/92570669-ccec9500-f29f-11ea-89c6-4346bd1d2bc3.png)

VS Code Version:
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

SFDX CLI Version:
sfdx-cli/7.73.2-feef087df8 win32-x64 node-v12.18.3

OS and version:
Windows 10 version 2004

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
salesforce-vscode-slds|sal|1.2.1
salesforcedx-vscode|sal|49.8.0
salesforcedx-vscode-apex|sal|49.8.0
salesforcedx-vscode-apex-debugger|sal|49.8.0
salesforcedx-vscode-apex-replay-debugger|sal|49.8.0
salesforcedx-vscode-core|sal|49.8.0
salesforcedx-vscode-lightning|sal|49.8.0
salesforcedx-vscode-lwc|sal|49.8.0
salesforcedx-vscode-visualforce|sal|49.8.0

</details>

**Comment by Tyriar** [comment]
You'd have to ask sdfx either how to debug or why their program is throwing the error. If it just happens in VS Code's terminal it's likely related to its environment variables, it's still a bug in sfdx or the plugin install though.
