### ISSUE TITLE
XSLT Intellisense

### ISSUE THREAD

**Issue by Ajaja** [Microsoft/vscode#10632]
Is there some way to activate Intellisense for XSL/XSLT files?

**Comment by alexandrudima** [comment]
There is an XML plugin on the marketplace, not sure if that covers XSL or not.

https://marketplace.visualstudio.com/search?term=XSL&target=VSCode&sortBy=Relevance

**Comment by Ajaja** [comment]
I've tried XML Tools but it doesn's seem to cover XSL.
The IntelliSense with XSL works fine in Visual Studio 2015.  It would be great to have the feature in VS Code too.

**Comment by mjbvz** [comment]
Closing as extension-canidate
