### ISSUE TITLE
Extensions list no update when using different extensions directories

### ISSUE THREAD

**Issue by NormanV41** [microsoft/vscode#106366]
- VSCode Version: 1.49.0-insider
e790b931385d72cf5669fcefc51cdf65990efa5d
x64
- OS Version: Fedora release 32 x86_64

Steps to Reproduce:

1. Have two different extensions directories, in example extensions-A, and extensions-B.
2. Have two different workspaces, in example workspace-A, and workspace-B.
3. Open workspace-A with extensions-A from command line: `code-insiders --extensions-dir extensions-A workspace-A`.
4. repeat step 3 with workspace-B and extensions-B.
5. Check that in the vscode instance with workspace-B, the list of extensions show in the Extensions tab are the same of the workspace-A, when the expected behavior is to show the list of extensions available in workspace-B.

Does this issue occur when all extensions are disabled?: Yes

This is a small issue, but after doing the steps mentioned above, even though vscode renders the correct extensions in workspace-B, the list of extensions from the Extensions tab show the extensions found in extensions-A, instead of extensions-B.

**Comment by sandy081** [comment]
This is designed. After starting VS Code with a given extensions dir, other windows also use the same extensions dir. If you want other windows to use different extensions dir, you have to also point VS Code to a different user data dir.
