### ISSUE TITLE
Extension host debug warning message in console

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#106334]
* run `yarn web`
* observe the following warning:

```
 WARN Extension Host Debugging not available due to missing connection.
```

* we can remove the warning and create an issue to track anything that needs to be done there.

**Comment by isidorn** [comment]
Seems to be coming from [here](https://github.com/microsoft/vscode/blob/a443309bcf9d72921f01772120dbddd1cb5d7088/src/vs/workbench/contrib/debug/browser/extensionHostDebugService.ts#L38)

@weinand let me know what you would like us to do here.

**Comment by weinand** [comment]
I think @bpasero added the message.
We have to find out why this case is hit for "yarn web"...

**Comment by weinand** [comment]
Aha, and there is actually no debugger that would use the services provided by the `BrowserExtensionHostDebugService`..
So let's replace the warning with a comment: "extension host debugging not supported in serverless"
