### ISSUE TITLE
editor.detectIndentation not working properly

### ISSUE THREAD

**Issue by pprokopi** [microsoft/vscode#106397]
- VSCode Version:code --version 1.48.2
- OS Version: Fedora 32 x64

Steps to Reproduce:

1. Run code --disable-extensions 
2. Create a file with a separate editor that has tab indentation (personally used a .go file)
3. Set the following in user settings
    "editor.detectIndentation": false,
    "editor.insertSpaces": true,
    "editor.tabSize": 4,
4. Make sure the workspace has no settings
5. Check in the lower right corner if  indentation is tabs or spaces

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by rebornix** [comment]
```
    "editor.detectIndentation": false,
    "editor.insertSpaces": true,
    "editor.tabSize": 4,
```

with above setting, VS Code will not detect indentation/tab/space from the file, instead it will use settings `editor.insertSpaces` and `editor.tabSize` t for all future operations, like Tab, Format, Enter, etc. The status bar item is indicating what's the tab/space setting the editor will use, not if the current file is using tab or space/

**Comment by pprokopi** [comment]
In my case, it detects the indentation in the file, and it won't use the one I set. For example, if the file used tabs, then instead of spaces (with editor.intertSpaces=true), vscode will use tabs as well.
