### ISSUE TITLE
Revert for 8e5eed12991c8af7a599b3f68fb9ca723b953316

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#106379]
Hey @roblourens, looks like 8e5eed12991c8af7a599b3f68fb9ca723b953316 caused a layer check error: https://dev.azure.com/vscode/VSCode/_build/results?buildId=52539&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=3d94a178-cdfb-5c90-a971-5deeccbbe043&l=15

I've reverted it but please take a look when you have a chance

**Comment by roblourens** [comment]
Fixed, thanks
