### ISSUE TITLE
Cannot connect to the Extensions Marketplace

### ISSUE THREAD

**Issue by davidalmarinho** [microsoft/vscode#106369]
Hello, I am facing a problem with vscode.

![image](https://user-images.githubusercontent.com/53182041/92657314-82453a00-f2ec-11ea-99b8-e56652b46040.png)

My vscode can't connect to the Extensions Marketplace. It works just some times after restarting vscode a couple of times... Many times. 
I also can install extensions from command line:
![image](https://user-images.githubusercontent.com/53182041/92658139-f92f0280-f2ed-11ea-9b80-66198fcb769d.png)

And there it is
![image](https://user-images.githubusercontent.com/53182041/92658246-24b1ed00-f2ee-11ea-98f9-e52e91b25db1.png)

I also tried reinstalling vscode but the problem persists.
I hope that you fix this soon.

- VSCode Version: 1.48.2
- OS Version: Elementary OS 5.1.7 Hera

Steps to Reproduce:

1. Install vscode
2. Try install extensions using the vscode user's interface

Does this issue occur when all extensions are disabled?: 
Well, when I did it for the first (with the extensions disabled) and second (with the extensions already enabled) time, It worked, but after the problem appeared again.

**Comment by davidalmarinho** [comment]
Today I have updated to the newest version: 1.49, and the problem still persists.
Please help

**Comment by sandy081** [comment]
please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

Also see if there are any errors in network tab while making requests to marketplace

    - Help -> Toggle Developer Tools -> Console

**Comment by davidalmarinho** [comment]
> please share the logs from the following locations
> - Help -> Toggle Developer Tools -> Console
> - View -> Command Pallette... -> Toggle Shared Process -> Console
> - View -> Open View… -> Log (Shared)
> - View -> Open View… -> Log (Window)
> 
> Also see if there are any errors in network tab while making requests to marketplace
> 
> ```
> - Help -> Toggle Developer Tools -> Console
> ```

**- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -**
- [x] Help -> Toggle Developer Tools -> Console

![Captura de ecrã de 2020-09-15 18-37-52](https://user-images.githubusercontent.com/53182041/93245161-c91ab000-f782-11ea-9363-735a722b4cd7.png)
![Captura de ecrã de 2020-09-15 18-37-56](https://user-images.githubusercontent.com/53182041/93245171-cfa92780-f782-11ea-85b8-be8a6d57b8f2.png)

**- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -**

- [x] View -> Command Pallette... -> Toggle Shared Process -> Console

![Captura de ecrã de 2020-09-15 18-42-58](https://user-images.githubusercontent.com/53182041/93245522-5f4ed600-f783-11ea-9c1d-56b2ae1af74b.png)
![Captura de ecrã de 2020-09-15 18-43-11](https://user-images.githubusercontent.com/53182041/93245540-6249c680-f783-11ea-8cdb-85139737da19.png)
![Captura de ecrã de 2020-09-15 18-43-18](https://user-images.githubusercontent.com/53182041/93245549-637af380-f783-11ea-94dd-3fb89c5738a7.png)
![Captura de ecrã de 2020-09-15 18-43-20](https://user-images.githubusercontent.com/53182041/93245556-6544b700-f783-11ea-8f38-14b63fc2a31f.png)

**- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -**

- [ ] View -> Open View… -> Log (Shared)
- [ ] View -> Open View… -> Log (Window)
I have recorded a video, because I can't acess to the Open View... -> https://youtu.be/j_ja4NlXoEg

I hope that this stuff helps

**Comment by davidalmarinho** [comment]
I don't know how, but today I could open the Open view, Here it is:
- [x] View -> Open View… -> Log (Shared)
[2020-09-16 21:45:13.262] [sharedprocess] [info] main {"machineId":"63bbe65e041601d4601b44824f109d479a43853aa4a4f3560420bb63df7270b4","windowId":2}
[2020-09-16 21:45:53.323] [sharedprocess] [info] Starting to clean up unused language packs.

**- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -**

- [x] View -> Open View… -> Log (Window)
![Captura de ecrã de 2020-09-16 21-49-27](https://user-images.githubusercontent.com/53182041/93391045-829e8180-f866-11ea-95a9-67d87459eda0.png)

**Comment by sandy081** [comment]
I see in Dev tools > Console there is an error `ERR_CONNECTION_RESET`

Do you have any network proxy set up?

Can you please open the network tab there and check if there are any errors in requests to Marketplace?

**Comment by davidalmarinho** [comment]
- [x] Do you have any network proxy set up?
No
![Captura de ecrã de 2020-09-19 12-27-01](https://user-images.githubusercontent.com/53182041/93666167-d0d4a000-fa73-11ea-9bc1-52252c90d117.png)

- [x] Can you please open the network tab there and check if there are any errors in requests to Marketplace?
Yes, I think that is this what you need:
![Captura de ecrã de 2020-09-19 12-33-48](https://user-images.githubusercontent.com/53182041/93666239-64a66c00-fa74-11ea-9d98-c7256d1f754a.png)
![Captura de ecrã de 2020-09-19 12-33-50](https://user-images.githubusercontent.com/53182041/93666242-6c661080-fa74-11ea-8bec-b298a1500303.png)

P.S: I have updated the vscode to the 1.49.1 version.

**Comment by sandy081** [comment]
It seems `extensionsquery` requests are failing above. Can you please click on them and let us know what errors are they having?

**Comment by davidalmarinho** [comment]
> It seems `extensionsquery` requests are failing above. Can you please click on them and let us know what errors are they having?

I have found this
![Captura de ecrã de 2020-09-22 21-02-02](https://user-images.githubusercontent.com/53182041/93931802-30060f00-fd17-11ea-8302-b8e096d16c09.png)

**Comment by sandy081** [comment]
I do not see the error here, can you please open the network tab and click on the failing request to see the error?

**Comment by davidalmarinho** [comment]
> I do not see the error here, can you please open the network tab and click on the failing request to see the error?

I am not understanding a little of what you need, because, when I click in `extensionsquery`, a lot of things opens.
Is this what you need?
**- - - First extensionquery - - -**
![Captura de ecrã de 2020-09-23 19-50-54](https://user-images.githubusercontent.com/53182041/94056420-30191400-fdd6-11ea-9249-5a78197dbfe2.png)
![Captura de ecrã de 2020-09-23 19-50-57](https://user-images.githubusercontent.com/53182041/94056436-34453180-fdd6-11ea-8f8b-4533601e293d.png)
![Captura de ecrã de 2020-09-23 19-50-59](https://user-images.githubusercontent.com/53182041/94056444-360ef500-fdd6-11ea-94d8-c53e705ee9da.png)
![Captura de ecrã de 2020-09-23 19-51-03](https://user-images.githubusercontent.com/53182041/94056449-37d8b880-fdd6-11ea-9efa-89eb5e58ec06.png)
![Captura de ecrã de 2020-09-23 19-51-07](https://user-images.githubusercontent.com/53182041/94056460-3ad3a900-fdd6-11ea-9334-5ac265ff2e8a.png)
![Captura de ecrã de 2020-09-23 19-51-09](https://user-images.githubusercontent.com/53182041/94056467-3dce9980-fdd6-11ea-8739-2c811abbee0e.png)
![Captura de ecrã de 2020-09-23 19-51-12](https://user-images.githubusercontent.com/53182041/94056473-3effc680-fdd6-11ea-9a67-23f6b4a1d48a.png)
![Captura de ecrã de 2020-09-23 19-51-14](https://user-images.githubusercontent.com/53182041/94056476-4030f380-fdd6-11ea-9477-2bab90a623fa.png)

**- - - Second extensionquery - - -**
![Captura de ecrã de 2020-09-23 19-53-34](https://user-images.githubusercontent.com/53182041/94056700-8dad6080-fdd6-11ea-846d-bcd1f6409f57.png)
![Captura de ecrã de 2020-09-23 19-53-36](https://user-images.githubusercontent.com/53182041/94056707-8f772400-fdd6-11ea-93a4-f174bfa888eb.png)
![Captura de ecrã de 2020-09-23 19-53-37](https://user-images.githubusercontent.com/53182041/94056717-9140e780-fdd6-11ea-8bf9-67a12d4ce5a9.png)
![Captura de ecrã de 2020-09-23 19-53-40](https://user-images.githubusercontent.com/53182041/94056720-92721480-fdd6-11ea-9453-11c12c340fe8.png)
![Captura de ecrã de 2020-09-23 19-53-42](https://user-images.githubusercontent.com/53182041/94056725-94d46e80-fdd6-11ea-9318-cb46413466af.png)
![Captura de ecrã de 2020-09-23 19-53-45](https://user-images.githubusercontent.com/53182041/94056727-96059b80-fdd6-11ea-9b12-4d203f51b7bc.png)
![Captura de ecrã de 2020-09-23 19-53-47](https://user-images.githubusercontent.com/53182041/94056731-97cf5f00-fdd6-11ea-8dd6-ea805d2f5ac1.png)
**----**
![Captura de ecrã de 2020-09-23 20-04-00](https://user-images.githubusercontent.com/53182041/94057737-f517e000-fdd7-11ea-8749-8bcc41e7ded2.png)

**Comment by sandy081** [comment]
Confirmed that there is a network error ERR_CONNECTION_RESET. 

I see you do not have network proxy settings, but this error is related to proxy. Hence assigning to @chrmarti

**Comment by davidalmarinho** [comment]
Updated to the 1.49.2 version and the problema persists...

**Comment by oxk4r01** [comment]
Same here. Any fix for this?

**Comment by davidalmarinho** [comment]
> Same here with v1.50.0
> Any fix for this?

Not yet, but they are trying to fix it

**Comment by davidalmarinho** [comment]
@chrmarti I need tour help

**Comment by chrmarti** [comment]
Could you start VS Code with `--log-net-log=netlog.json`, retry the failing feature and then post the created netlog.json here?

**Comment by davidalmarinho** [comment]
> Could you start VS Code with `--log-net-log=netlog.json`, retry the failing feature and then post the created netlog.json here?

The problem still persists after ran that command.
Here it is the netlog.json file:

The git hub doesn't allow me to upload that file, so I put it in my MEGA drive.
key:
7sqtdJlfI8cVimND2HiVPg
https://mega.nz/folder/J04h3YiL

**Comment by deepak1556** [comment]
Thanks for the logs, this is kinda similar to https://github.com/microsoft/vscode/issues/108087 but there is subtle difference in the HTTP2_SESSION stack but then again not sure what is causing the reset.

```
t=7019 [st= 2]    HTTP2_SESSION_SEND_DATA
                  --> fin = true
                  --> size = 342
                  --> stream_id = 3
t=7019 [st= 2]    HTTP2_SESSION_UPDATE_SEND_WINDOW
                  --> delta = -342
                  --> window_size = 64035
t=7091 [st=74]    HTTP2_SESSION_CLOSE
                  --> description = "Error 101 reading from socket."
                  --> net_error = -101 (ERR_CONNECTION_RESET)
```

Couple of things to try,

1) Can you try pointing to one of the public DNS servers and see if the issue continues ?

2) Can you check if the issue happens with our exploration build https://az764295.vo.msecnd.net/exploration/53c0ab95bb770a8f3f869e81bb9da200708e6700/code-exploration-x64-1600879613.tar.gz that comes with newer chromium runtime.

3) Can you start code with `--disable-http2` flag and check if the issue continues.

**Comment by davidalmarinho** [comment]
> Thanks for the logs, this is kinda similar to #108087 but there is subtle difference in the HTTP2_SESSION stack but then again not sure what is causing the reset.
>
You are welcome.
All the cases that I have saw with this error, are all Linux Ubuntu based system. I don't know if this info could help.

> - [ ]  1. Can you try pointing to one of the public DNS servers and see if the issue continues?
> 
Sorry, I didn't understand what I have to do, may you explain me?
> - [X]   2. Can you check if the issue happens with our exploration build https://az764295.vo.msecnd.net/exploration/53c0ab95bb770a8f3f869e81bb9da200708e6700/code-exploration-x64-1600879613.tar.gz that comes with newer chromium runtime.
>
I have started with that version and a new error appear.
![Captura de ecrã de 2020-10-21 18-21-12](https://user-images.githubusercontent.com/53182041/96755425-9e97c480-13ca-11eb-82d5-31dfbf194a79.png)

>
- [X] 3. Can you start code with `--disable-http2` flag and check if the issue continues.
>
The issue still persists after I ran that command.
![Captura de ecrã de 2020-10-21 18-29-26](https://user-images.githubusercontent.com/53182041/96756113-81172a80-13cb-11eb-83f5-0fbc51113b4c.png)

**Comment by deepak1556** [comment]
> Sorry, I didn't understand what I have to do, may you explain me?

For example using google DNS https://developers.google.com/speed/public-dns `8.8.8.8 and 8.8.4.4`

>  have started with that version and a new error appear.

Can you get a netlog for the exploration builds

> All the cases that I have saw with this error, are all Linux Ubuntu based system

Yeah that is true

Can you also get me a tcpdump while taking the netlog following the steps in https://github.com/microsoft/vscode/issues/108087#issuecomment-705984162

**Comment by davidalmarinho** [comment]
> > Sorry, I didn't understand what I have to do, may you explain me?
> 
> - [X] For example using google DNS https://developers.google.com/speed/public-dns `8.8.8.8 and 8.8.4.4`
> 
Ok, I have started with it, following these steps: https://developers.google.com/speed/public-dns/docs/using 
It worked for the first, second and third time that I launch the vscode, but now it doesn't work no more.
> 
> - [X]  Can you get a netlog for the exploration builds
> 
Yes, it is inside NetLogs from exploration vscode version folder
Key: 
7sqtdJlfI8cVimND2HiVPg
https://mega.nz/folder/J04h3YiL

> > All the cases that I have saw with this error, are all Linux Ubuntu based system
> 
> Yeah that is true
> 
> Can you also get me a tcpdump while taking the netlog following the steps in [#108087 (comment)](https://github.com/microsoft/vscode/issues/108087#issuecomment-705984162)
>
Sure, it is also in the previous link.
And here it is tcpdump session:
1.wlp3s0 [Up, Running]
2.any (Pseudo-device that captures on all interfaces) [Up, Running]
3.lo [Up, Running, Loopback]
4.enp2s0 [Up]
5.nflog (Linux netfilter log (NFLOG) interface)
6.nfqueue (Linux netfilter queue (NFQUEUE) interface)
7.usbmon1 (USB bus number 1)
8.usbmon2 (USB bus number 2)
9.usbmon3 (USB bus number 3)

**Comment by davidalmarinho** [comment]
@deepak1556 @chrmarti @sandy081 Thank you for your help :D 
The error didn't happen again
Have a nice Sunday and have a good continuation
