### ISSUE TITLE
cpu overload after installing openjdk 11 

### ISSUE THREAD

**Issue by here-there** [microsoft/vscode#106360]
Issue Type: <b>Bug</b>

最新版安装openjdk 11以后，占用CPU资源爆炸式增长，vs code占用CPU长期持续超过70%，其中绝大多数是openjdk占用CPU资源增长，导致系统异常卡顿

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (4.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.3
asciidoctor-vscode|asc|2.8.3
vscode-instant-markdown|dba|1.4.5
xml|Dot|2.5.1
gitlens|eam|10.2.2
vscode-great-icons|emm|2.1.52
json-tools|eri|1.0.2
mdmath|goe|2.5.1
gc-excelviewer|Gra|3.0.40
vue-snippets|hol|0.1.12
beautify|Hoo|1.5.0
rest-client|hum|0.24.2
asciidoctor-vscode|joa|2.8.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.5.0
vscode-language-pack-zh-hans|MS-|1.48.3
csharp|ms-|1.23.2
python|ms-|2020.8.106424
remote-containers|ms-|0.134.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.29.0
debugger-for-chrome|msj|4.12.10
vsc-netease-music|non|0.0.39
vetur|oct|0.27.2
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.21.0
vscode-manifest-yaml|Piv|1.21.0
vscode-spring-boot|Piv|1.21.0
java|red|0.66.0
vscode-xml|red|0.13.0
LiveServer|rit|5.6.1
vscode-extjs|Sen|1.0.3
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-spring-boot-dashboard|vsc|0.1.10
vscode-spring-initializr|vsc|0.5.0

(3 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/8286863/92639081-e88e8480-f30d-11ea-8944-43f2c7a0554f.png)

**Comment by smallp** [comment]
translate:
After installing jdk11, the CPU usage of vs code is always 70%+. openjdk uses the most CPU.

我觉得你应该去java插件那里提issue，大概率不是vscode的问题，而是插件的问题。

**Comment by here-there** [comment]
Thanks for responsing,  smallp. Maybe it's caused by too many opened java folders added to workspace. The Maven executors especially consume cpu resources a lot.

**Comment by aeschli** [comment]
Please file this against the Java extension: https://github.com/redhat-developer/vscode-java
