### ISSUE TITLE
Extension Remote SSH: automatic upload files

### ISSUE THREAD

**Issue by wzm2256** [microsoft/vscode#106343]
I really appreciate the remote-ssh extension. However, I find it not practical in my situation, which is debuging a local file on a remote machine. I believe this is a common requirement for most machine learning researchers.

For example, I write a python file and I would like to debug it on a large server. I also wish to modify it a lot of times to increase its performance.  Meanwhile, **I need my file to STAY LOCAL**, so I don't have to download it everytime I feel necessary.

I understand the use of SSHFS and rsync, but that is much too complicated. It should be done with a click.

Currently, Pycharm is the only option, since it provide an easy-to-use automatic upload button. 
I hope VSCode can have a similar function like this.

![image](https://user-images.githubusercontent.com/24223188/92597905-9e3fe000-f2da-11ea-95ed-50ff1cf65950.png)

**Comment by roblourens** [comment]
Thanks for the feedback, but this doesn't really fit into how vscode remote works, and we don't plan to implement something like this.
