### ISSUE TITLE
TS server not starting

### ISSUE THREAD

**Issue by obedDecath** [microsoft/vscode#106320]
Issue Type: <b>Bug</b>

TS language server died 5 times and can't restart. 

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by obedDecath** [comment]
It worked after restarting vs code.
