### ISSUE TITLE
When editor.defaultFormatter not exist, the vscode will randomly choose another one without warning me

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/vscode#106376]
- VSCode Version: 1.48.2
- OS Version: Windows 20.04 (WIndows_NT x64 10.0.19041)

Steps to Reproduce:

1. set `editor.defaultFormatter` to a non exist value
2. turn on `editor.formatOnSave`

![issue 3](https://user-images.githubusercontent.com/15936231/92676975-44303080-f355-11ea-99e5-09bdf0371e17.gif)

I think `fomratOnSave` should behave like manually invoke `Format Document` command

**Comment by jrieken** [comment]
We have done that on purpose to not be annoying

**Comment by CGQAQ** [comment]
But you only need to choose once, what is annoying about?

**Comment by CGQAQ** [comment]
denoland/vscode_deno#193  I got an issue that he/she thinks that the plugin is hijacking the formatting functionality

**Comment by jrieken** [comment]
We actually do "show" the notification, but as a silent notification. Check out the dot on top of the bell icon.

**Comment by jrieken** [comment]
I'll give it some thought. I see how picking some formatter is confusing. There are two options: (1) we don't format when not being able to find the configured formatter or (2) we show the notification more prominent (and also don't format). The challenge is that in some scenarios we cannot show notifications, e.g when an extension invokes an API command to compute formatting edits. Also, showing a notification when formatting on focus out would be strange...

**Comment by jrieken** [comment]
Pushed a change so that no formatter is picked in the described scenario. No change wrt notifications
