### ISSUE TITLE
Ipynb git diffs broken

### ISSUE THREAD

**Issue by aaronsmith1234** [microsoft/vscode#106304]
Issue Type: <b>Bug</b>

If I try to do a diff between two ipynb's, it won't let me view the differences in VSCode. I think its trying to render the notebook.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
sas-syntax|77q|1.0.8
better-comments|aar|2.1.0
atlascode|atl|2.7.1
path-intellisense|chr|2.2.1
bracket-pair-colorizer-2|Coe|0.2.0
gitlens|eam|10.2.2
vsc-material-theme-icons|equ|1.2.0
todo-tree|Gru|0.0.178
r|Iku|1.4.4
vscode-edit-csv|jan|0.4.1
vsc-python-indent|Kev|1.11.0
git-graph|mhu|1.25.0
prettify-json|moh|0.0.3
vscode-azurestorage|ms-|0.9.0
mssql|ms-|1.9.0
python|ms-|2020.8.106424
vscode-pylance|ms-|2020.9.0
azure-account|ms-|0.9.2
powershell|ms-|2020.6.0
autodocstring|njp|0.5.3
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.10.1
vscode-iq-plugin|Son|0.7.4
vscodeintellicode|Vis|1.2.10

</details>

**Comment by rebornix** [comment]
@aaronsmith1234 do you run into this issue with extensions disabled?

**Comment by aaronsmith1234** [comment]
@rebornix nope I haven’t tried that yet; what extensions specifically to disable? Or just disable all? Assuming I can do that from command palette?

**Comment by rebornix** [comment]
@aaronsmith1234 you can run `code --disable-extensions` to disable all extensions and see you can still see the issue.

**Comment by aaronsmith1234** [comment]
Seems fixed without disabling even; I’m on v1.49.1 now
