### ISSUE TITLE
VS Code Not Configuring To Use Systems Proxy Pac

### ISSUE THREAD

**Issue by alwayserik** [microsoft/vscode#106311]
- VSCode Version: 1.48.2
- OS Version: Windows 10, 10.0.18363 Build 18363

Steps to Reproduce:

1. Have a proxy pac script configured in the proxy settings of windows 10. (Corporate requirement for internet connectivity)
2. Install latest version of VS code without any existing configuration files (Delete everything in AppData etc.)

Does this issue occur when all extensions are disabled?: Yes

![VSCodeDeveloperModeErrors](https://user-images.githubusercontent.com/22233206/92525752-3fdf0880-f1d9-11ea-878c-c8395cf4a6ce.PNG)

**Comment by alwayserik** [comment]
I work in a corporate office that uses a proxy pac on our windows systems.

My old work laptop (Initially Installed Version: 1.43.0 (user) x64 in February) has everything working.

My new laptop upon installing this (Version 1.48.2 (user) x64) encounters this issue. It wouldn't use the system proxy pac that was configured. To resolve this issue, I had to go and set my user environment variable _http_proxy_ and _https_proxy_. It's also interesting to note that if I later delete these environment variables, for some reason the application seems to keep the proxy settings.

I wasn't content with having VS code use hard-coded environment variables, so I uninstalled everything, removed all configuration files from appdata (to delete any previously kept proxies) and started over.

This time I first installed version 1.43.0 on my new laptop. Everything worked! Then I thought once I update, it will be working like on my old laptop right? No hardcoded environment variables required? Nope! Once I updated from 1.43.0 -> 1.48.2, I encountered the issue again... So currently it seems I have to set environment variables?

Can we fix this to be able to use the system proxy pac like it did in 1.43.0?

**Comment by chrmarti** [comment]
Could you start VS Code with --log-net-log=netlog.json, retry the failing operations and then post the created netlog.json here?

**Comment by alwayserik** [comment]
Here is the netlog. 
[netlog.zip](https://github.com/microsoft/vscode/files/5197270/netlog.zip)
I tried using the extensions marketplace and also tried to sync with my account. By the way, what is the default location that --log-net-log stores the file? I had to manually set a path to find it.

**Comment by chrmarti** [comment]
It fails to resolve the IP address of the server holding the PAC file. Can you try using 8.8.8.8 (Google Public DNS) as your DNS server?

**Comment by alwayserik** [comment]
@chrmarti I am happy to announce that it has started working. I was able to

**Comment by alwayserik** [comment]
As it stands, I'm not sure how I would modify the pac file to test using Google's public DNS. I will need to request info internally, or maybe you can provide an example

**Comment by chrmarti** [comment]
@alwayserik You would set the DNS in your OS' network configuration. E.g., the following post includes description and screenshots for Windows 10: https://www.windowscentral.com/how-change-your-pcs-dns-settings-windows-10
