### ISSUE TITLE
Notebooks do not update outputs or cell metadata

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#106387]
@rebornix, @jrieken the notebooks in code spaces do not update cells

- VSCode Version: Version: 1.49.0-insider Commit: b6d4fec3714ff897f72c1dab8cc02b7421a8f131 Date: 2020-09-01T05:49:16.366Z
- OS Version: Linux

Steps to Reproduce:

1. open a .NET Interactive notebook in code spaces
2. execute a cell
3. cell looks running and never stopping

![image](https://user-images.githubusercontent.com/375556/92692912-c9f3b200-f33c-11ea-8c2d-c90e8e210513.png)

In the dev tools I see this

![image](https://user-images.githubusercontent.com/375556/92693407-85b4e180-f33d-11ea-98c7-9f21e2045798.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
This is fixed (disabled) with https://github.com/microsoft/vscode/commit/f3023ca9c0a6a6c096d45a6c8571989f0a0b84e5 and should be in the latest build. Make sure to use insiders e790b931385d72cf5669fcefc51cdf65990efa5d

**Comment by colombod** [comment]
> This is fixed (disabled) with [f3023ca](https://github.com/microsoft/vscode/commit/f3023ca9c0a6a6c096d45a6c8571989f0a0b84e5) and should be in the latest build. Make sure to use insiders [e790b93](https://github.com/microsoft/vscode/commit/e790b931385d72cf5669fcefc51cdf65990efa5d)

it works perfectly on local machine, the issue i just reported manifests only in code spaces

**Comment by jrieken** [comment]
Ok, let's hope codespaces will update soon. Closing this because we don't plan a code change for this item
