### ISSUE TITLE
Folder doesn't show all available files

### ISSUE THREAD

**Issue by marcelhekking** [microsoft/vscode#106329]
- VSCode Version: July 2020 (version 1.48)
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. Open sidebar
2. Go to folder with error
3. Only 1 file is present while containing folder shows several

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Thanks for filling this issue. I can not reproduce. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
If yes can you please provide more precise steps so we reproduce this on our machines
