### ISSUE TITLE
vs code not showing accept incoming/current changes

### ISSUE THREAD

**Issue by sridharan99** [microsoft/vscode#106325]
- VSCode Version: vs 1.48.2 (downloaded from vs)
- OS Version: windows 10

Steps to Reproduce: 

1. did a git pull origin master
2. opened vs code from cmd with "code ." from root level git folder. 

![image](https://user-images.githubusercontent.com/17823318/92557879-e6cfad00-f28a-11ea-90e2-ca53817f418a.png)

I tried multiple solutions relating to this issue but none of them are fixing the issue. 

I referred this one https://github.com/eamodio/vscode-gitlens/issues/319 

I ensured that under userpreferences the diffEditor option is set true (toggled and checked)

I checked in output logs. nothing there. 

![image](https://user-images.githubusercontent.com/17823318/92557917-06ff6c00-f28b-11ea-8a09-e6fcf4573c15.png)

strangely, I'm not able see extensions from market place. it's just empty. 

![image](https://user-images.githubusercontent.com/17823318/92557996-2f876600-f28b-11ea-9d85-d7995dd07993.png)

I believe the complete installation is messed up in my machine. I uninstalled and installed the vs code twice. (did windows restart also :P)  Still the same issue. 

Please help fix this issue. The diff editor was helping me big time. 

Does this issue occur when all extensions are disabled?: No

**Comment by sbatten** [comment]
you say the issue goes away when extensions are disabled?

**Comment by sridharan99** [comment]
No. The extensions are not even loading in the market place. It's just empty when I move to the extensions section. As a result, I couldn't install any extensions.

**Comment by sbatten** [comment]
can you try running with a fresh user data dir? `code --user-data-dir <pathToNewEmptyDirectory> .`
