### ISSUE TITLE
Provide option to default to github provider git.api.getRemoteSources and potentially list org repos.

### ISSUE THREAD

**Issue by wangjaso** [microsoft/vscode#106316]
The repository picker feature https://github.com/microsoft/vscode/issues/102394 allows to pick github repos after selecting the GitHub provider. 
Asking for 
1. An option to default the provider to GitHub so that user can have one less click when creating a codespace. 
2. Currently it lists all repos where you are owner, is it possible to list repos of organizations you are in as well?

A side question is how does the api authenticate, is it with the stored git credentials in git extension? 

```
await commands.executeCommand('git.api.getRemoteSources', {
	providerLabel: (provider: RemoteSourceProvider) => `Test this for ${provider.name}`,
	urlLabel: `Test this for URL`,
        defaultProvider: 'Github'
});
```

@joaomoreno

Thanks,
Jason

**Comment by joaomoreno** [comment]
> An option to default the provider to GitHub so that user can have one less click when creating a codespace.

Sure, I can accept a PR here. But let's call it `providerName`. Note that multiple providers can have the same name, tho that is a hypothetical issue, so no worries.

> Currently it lists all repos where you are owner, is it possible to list repos of organizations you are in as well?

The code that gets the repositories lives in the GitHub core extension: https://github.com/microsoft/vscode/blob/4bb364cc8e4f936dae869d5d019f752ac675e010/extensions/github/src/remoteSourceProvider.ts#L29-L42. Maybe by querying for `ORG_NAME/` you'd get those repos? If so, we could add another option to the command `queryPrefix: string`.

Authentication is implemented via the GitHub Authentication core extension:https://github.com/microsoft/vscode/blob/8eb9cdaba94b6d23f87810c97fd81803726e1ecf/extensions/github-authentication/src/extension.ts#L25-L25
