### ISSUE TITLE
code folding stops at compiler directive in col 0

### ISSUE THREAD

**Issue by gforeman** [Microsoft/vscode#10631]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

when using `#region/#endregion`, folding stops if another compiler directive is in col 0.
```
#region Utility functions
    // code here
#if SOME_SWITCH
    // do something
#endif  //SOME_SWITCH
#endregion Utility functions
```

should show this:
```
#region Utility functions-
#endregion Utility functions
```

instead it shows this:
```
#region Utility functions
#if SOME_SWITCH
    // do something
#endif
#endregion Utility functions
```

indenting the `#if` produces the desired result.

**Comment by aeschli** [comment]
What you request is language-aware folding. We have #3422 for this.
The current folding strategy only looks at the indentation of a line to determine the folding regions.
