### ISSUE TITLE
Add a new settings for the debug toolbar location

### ISSUE THREAD

**Issue by Tazaf** [microsoft/vscode#106367]
Hi 👋 

The current two options for the debug toolbar location (docked or floating) have both their pros and cons, as discussed in [this (now closed) issue](https://github.com/microsoft/vscode/issues/101031), and none of them is completely satisfying (to me, anyways).

> The following is a copy/paste of my comment in the aforementionned issue

Wouldn't it be possible to add some kind of docked Debug Toolbar but located in a place that made it always available? Like above or below the Editor:

![example1](https://user-images.githubusercontent.com/7702322/90876047-4e888b80-e3a2-11ea-9051-8cb83db46b89.png)

This would take the best of both existing options: an always visible/accessible toolbar that do not get in the way of other UI elements (tabs or buttons).

Sure, this proposal would reduce the Editor space of some twenty-ish pixels, but I personnally wouldn't mind their loss considering the benefit it would provide.

(Plus, the added horizontal space could be used to add some useful shortcuts, like opening the debug console for the currently selected debug process)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by scottbeech** [comment]
I would prefer to use the docked option for the Debug Toolbar Location, but when I do so, the Debug Toolbar replaces the Launch Options. Perhaps a solution would be to locate the Debug Toolbar below the Launch Options when it is docked.

**Comment by EverlastEngineering** [comment]
I've written an extension that reveals the debug controls in the titlebar after being annoyed by this problem for years.

https://marketplace.visualstudio.com/items?itemName=EverlastEngineering.debug-in-titlebar

Hope it helps. Open any issues on it's github page and I'll address them.

**Comment by Tazaf** [comment]
> I've written an extension that reveals the debug controls in the titlebar after being annoyed by this problem for years.

Oh! That's interesting, i'll take a look 👍

**Comment by Tazaf** [comment]
I don't feel this issue is critical (by far), but it's still a little anoying ; I understand there must be more important issues to resolve, though 👍
