### ISSUE TITLE
hidden files dont show on mac

### ISSUE THREAD

**Issue by corey-c** [microsoft/vscode#106322]
Issue Type: <b>Bug</b>

When I hit the mac command(CMD + Shift + .) to show hidden files they don't show in the file browser.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.16.2
beautify|Hoo|1.5.0

</details>

**Comment by isidorn** [comment]
Hidden files always get shown in the File explorer for me on my mac. 
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by corey-c** [comment]
This was a none issue that a reinstall fixed
