### ISSUE TITLE
Anaconda commands on visual code remote terminal stopped working

### ISSUE THREAD

**Issue by ofiryaish** [microsoft/vscode#106317]
- VSCode Version: newest 
- OS Version: Windows 10

When I'm working not in visual code (linux terminal or powershell for example) everything is working fine. I succeed to run conda commands. For example, I succeed to ran `conda version` and other commands, and I manage to run `source activate my_env` or `conda activate my_env` to enter conda environment.   

When I worked with remote ssh on visual studio (using intel Devcloud if it says something) everything was also fine, and I managed to everything I done above in the terminal that is provided in by visual studio.

Today, I had some problem with my environments, so I deleted some and created new ones. As a result, thing stopped working only in visual code terminal. when I try to perform conda command I get `conda: command not found`, and when I try `source activate my_env` I get `bash: activate: No such file or directory`.

I saw that in general it got something with the PATH (I don't really understand how but I saw it), but here everything works fine when not using visual code. In addition, since I'm working on cloud, people suggestion to add something like this `export PATH=~/anaconda3/bin:$PATH` is not possible to me as I don't have this kind of location. Instead my environments are located on  `/home/user_name/.conda/envs`.
 
(side problem that I got is that when I tried to delete one of my environment, I saw that its directory in `/home/user_name/.conda/envs` is still there, and when I tried to delete it with rm -rf I get error `rm: cannot remove 'kerasenv/lib/python3.6/site-packages/~umpy/core': Permission denied`).

I broke my head to understand what is the problem.

**Comment by ofiryaish** [comment]
I will ask there, but I don't think it is caused by python extension. the occur only in the VS studio terminal.

**Comment by Tyriar** [comment]
@ofiryaish normally I believe the Python extension handles paths to conda and venv related things. I don't know much about this but these issues are normally user environment related which is why people suggested:

>  people suggestion to add something like this export PATH=~/anaconda3/bin:$PATH

**Comment by ofiryaish** [comment]
@Tyriar I didn't know that Python extension handles paths. About the second comment , I will normally agree with you, but  since the problem occurs only in the VScode terminal (in linux terminal and powershell of windows is works fine) I don't think that it is related to PATH problem (in a general manner). That is why I thought that the problem is with my VScode as it should have open a normal terminal (as linux terminal or powershell) that can run those commands (without any relation to python), but it doesn't. it doesn't recognize those commands (it was working fine).

**Comment by Tyriar** [comment]
@ofiryaish what environment are you using, you say Windows 10 but I see non-Windows paths?

**Comment by ofiryaish** [comment]
@Tyriar Maybe I wasn't clear. I'm using SSH remote connection from windows 10 VScode to a linux server. This is how my workspace looks like. Thank you for responding 👍 
![‏‏לכידה](https://user-images.githubusercontent.com/17110771/92616900-7430f280-f2c7-11ea-88c3-26d6e0cfdd5f.PNG)

**Comment by Tyriar** [comment]
@ofiryaish if you know where the paths get set up normally (.bashrc, .bash_profile?) it should us why they're not on the path for you.

**Comment by ofiryaish** [comment]
@Tyriar I didn't understand what you ask for. The path of bashrc and .bash_profile? 
They are located in /home/u30614 where u30614 is my cloud user.  Do you what me to upload them?

**Comment by Tyriar** [comment]
You were seeing this only in VS Code:

> conda: command not found

This means that conda is being added to the PATH somehow on your other terminals, you need to find where it's getting set in order to understand what's going on. Typically this is in your profile or rc script.

**Comment by ofiryaish** [comment]
I didn't find where it's getting set. I tried to read bashrc or .bash_profile to see if there is any connection to conda, and didn't find.

**Comment by Tyriar** [comment]
Closing this off as it seems like a generic python environment setup question.
