### ISSUE TITLE
Using editorTextFocus or textInputFocus in editor/title condition prevents editor context menu to open.

### ISSUE THREAD

**Issue by GorvGoyl** [microsoft/vscode#106357]
- VSCode Version: 1.48.2
- OS Version: Win10

This bug is related to VSCode extensions using Menu Contexts (editor/title) for Feature Contributions.

Steps to Reproduce:
1. in extension `package.json` file, use `textInputFocus` or `editorTextFocus` in `menus/editor/title` `when` clause. ex:
```
"menus": {
    "editor/title": [
        {
            "when": "textInputFocus && config.Redo",
            "command": "extension.redo",
            "group": "navigation@1"
          },
          {
            "when": "editorTextFocus && config.Toggle line comment",
            "command": "extension.commentLine",
            "group": "navigation@2"
          }
    ]
}
```
2. When editor is in focus, click on three dots menu (_more actions..._) to open menu but it instantly closes backs. hence, user is not able to see menu items.
See GIF: https://i.imgur.com/XD81kLn.gif

Expected behaviour: user should be able to open menu.

This is happening in my extension. link: https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar
I'm using `editorTextFocus` or `textInputFocus` to show menu icons only when editor is opened and hide the menu icons otherwise (for example when opening welcome page or built-in settings view). 

Does this issue occur when all extensions are disabled?: N.A

**Comment by sbatten** [comment]
@GorvGoyl can you verify if this reproduces when `window.titleBarStyle` is set to `native`

**Comment by GorvGoyl** [comment]
> @GorvGoyl can you verify if this reproduces when `window.titleBarStyle` is set to `native`

not reproducible on `native` but on `custom`

**Comment by sbatten** [comment]
@GorvGoyl after testing this in 1.50, I was unable to reproduce the issue. I see that opening the editor menu does move focus and therefore removes items from the toolbar, but the menu does not disappear. Can you verify?

**Comment by GorvGoyl** [comment]
I can see issue has been resolved. Thanks.
