### ISSUE TITLE
"cls" command only clears visible area of the integrated terminal

### ISSUE THREAD

**Issue by sajibsrs** [Microsoft/vscode#10636]
- VSCode Version: 1.4
- OS Version: Win 10 x64

Steps to Reproduce:

"cls" (clear screen command) only clears the visible are of the integrated terminal not everything from the beginning. If you scroll up you can still see previous executed commands.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/sourcelair/xterm.js/issues/106
