### ISSUE TITLE
Like 41295, make document scroll visible

### ISSUE THREAD

**Issue by mrmsbarnes** [microsoft/vscode#106370]
This scroll bar takes up no additional real estate when visible.  However, if you don't know where to look for it, if you aren't smart enough to hover over every pixel in the VS Code window, you end up loosing track of files under edit.  I hate clutter as much as as then next editor, but this little feature deserves to be visible when there are more tabs than space for them.  Please reconsider making this 'feature' visible when there are enough tabs to warrant its visibility.

**Comment by gjsjohnmurray** [comment]
Are you aware of `"workbench.editor.titleScrollbarSizing": "large"` to make that scroll bar easier to see and to grab?

#66000 asks for the visibility behaviour of all scrollbars to be configurable, and I intend to get back to the PR I opened for that.
