### ISSUE TITLE
Semantic token color sometimes render wrong, after change the text

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/vscode#106375]
- VSCode Version: 1.48.2 and older version
- OS Version: win10 1909 and older versions
- Language: Java with 'java extensions pack' enabled

Steps to Reproduce:

1. typing some java code(with java extensions pack enabled)
2. while you editing, **sometimes** semantic color rendering wrong like this:

![semantic color rendering wrong](https://github.com/JoeyRxy/tmp/blob/master/vscode%20issue%20report.png)

![semantic color rendering wrong](https://github.com/JoeyRxy/tmp/blob/master/vscode%20color%20rendering%20report.png)

Does this issue occur when all extensions are disabled?: No
But Semantic token color rendering needs matched language extensions ( I use java extensions)

**Comment by aeschli** [comment]
Can you file this against the Java extension? If you can figure out a steps with steps that would be great.
We need to find out if the Java extension reports the wrong positions or if the problem is with the editor.

**Comment by JoeyRxy** [comment]
I saw same issue in java extension's repo, and they think this is caused by the editor.

I think maybe the editor should auto render the color after editing, or can be triggered on some action, like 'save'.

**Comment by JoeyRxy** [comment]
> Can you file this against the Java extension? If you can figure out a steps with steps that would be great.
> We need to find out if the Java extension reports the wrong positions or if the problem is with the editor.

[java-extension-issue](https://github.com/redhat-developer/vscode-java/issues/1396)
