### ISSUE TITLE
about extentions group

### ISSUE THREAD

**Issue by shanliangdeYWJ** [microsoft/vscode#106315]
![image](https://user-images.githubusercontent.com/49124030/92530230-93e00080-f25e-11ea-9a2a-f517b86c3fe7.png)

There is no grouping content in the current sidebar about plug-ins. Just like git's grouping, I hope to create a new group in the plug-in, such as the Java component suite currently being developed by vscode. After I download it, he will download some other plug-in packages that can be opened by each workspace Suppose it is designed. Take JS, Java and CPP as examples, I can group a basic, CPP group, Java group, JS. In the file setting interface, there will be a check box to cooperate with the workspace function. In this way, each time you open the corresponding workspace or create a new workspace, you can quickly configure the default plug-in suite and some UI in the plug-in panel on the left GIT and other basic packages can be enabled by default,

I want to use idea as a project for each project, but that will make vscode lose flexibility. The biggest advantage of vscode is lightweight, plug-in customization and semi automation

If the above functions can be implemented in the workspace function, I hope that a document containing the workspace functions can be generated. How to set the contents similar to settings.json However, it is very troublesome to assign the previous configuration every time

**Comment by sandy081** [comment]
Not sure if I understand your requirement completely, if it is about having extensions enabled per workspace (project) you can do that using the action `Enable (Workspace)` available on each extension. If not, can you please explain the use case in more detail?
