### ISSUE TITLE
[js] ES6 template string can't include '/*'

### ISSUE THREAD

**Issue by builden** [Microsoft/vscode#1063]
such as: 
```js
const str = `bar/*`
```

**Comment by egamma** [comment]
Did you enable ES6 in the jsconfig.json?

**Comment by builden** [comment]
I have enabled ES6 in the jsconfig.json
![image](https://cloud.githubusercontent.com/assets/9499016/11623323/15a3154c-9d07-11e5-8c7e-5ef0fff3f669.png)
but show like this

**Comment by egamma** [comment]
Thanks for the clarification. This is a coloring issue.

**Comment by aeschli** [comment]
duplicate of #133.
Verified that this is fixed now (for December release)
