### ISSUE TITLE
[VSCode Extension/Testing]: Mocking of class methods via Sinon stubs are working fine while debugging but not while running tests from command line

### ISSUE THREAD

**Issue by vineetmimrot** [microsoft/vscode#106364]
- VSCode Version: 1.48
- OS Version: macOs Catalina 10.15.6

I am mocking methods of controlprovider class using Sinon stubs. It is working fine when I debug these tests in VSCode but while I run tests from the command line using 'npm run test', Sinon stub mocking doesn't happen. Anything I am missing?

Test file

    context('Should configure pipeline', function () {
        it('configure pipeline', async function () {
            this.timeout(0);
            await sleep(5000);
            await vscode.extensions.getExtension(extensionId).activate();
            let mockGetInput, mockShowQuickPick, mockShowInformationMessage;
            mockGetInput = sinon.stub(ControlProvider.prototype, 'showInputBox');
            mockGetInput.onFirstCall().resolves('text');

            mockShowQuickPick = sinon.stub(ControlProvider.prototype, 'showQuickPick');
            mockShowQuickPick
                .onFirstCall().resolves(data1)
                .onSecondCall().resolves(data2)

            mockShowInformationMessage = sinon.stub(ControlProvider.prototype, 'showInformationBox');
            mockShowInformationMessage.onFirstCall().resolves("Done");

            // This sleep is added because otherwise the tests run via cmd exits before running executeCommand. Unable to find root cause of this issue.
            await sleep(2000);
            await vscode.commands.executeCommand("configure-cicd-pipeline");

            sinon.assert.calledOnce(mockGetInput);
            sinon.assert.calledTwice(mockShowQuickPick);
            sinon.assert.calledOnce(mockShowInformationMessage);

        });

        after(() => {
            sinon.restore();
        });
    });

Launch debug configuration

        {
            "name": "Extension Tests",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "${workspaceRoot}/out/configure/test/test-fixtures/",
                "--extensionDevelopmentPath=${workspaceFolder}",
                "--extensionTestsPath=${workspaceFolder}/out/configure/test"
            ],
            "outFiles": [
                "${workspaceFolder}/out/configure/test/**/*.js"
            ]
        },
 
package.json

    "scripts": {
        "vscode:prepublish": "npm run compile",
        "compile": "tsc -p ./ && node copyStaticFiles.js",
        "watch": "node copyStaticFiles.js && tsc -watch -p ./",
        "pretest": "npm run compile",
        "test": "cp -r ./src/configure/test/test-fixtures/ ./out/configure/test/test-fixtures/ && node ./out/configure/test/runTest.js"
    },

Also Asked on: https://stackoverflow.com/questions/63818508

**Comment by weinand** [comment]
Thanks for asking on stackoverflow, because this is not a VS Code issue.

**Comment by vineetmimrot** [comment]
But how it is working in debug mode but not via command line? I am using scaffold test code generated by YO. This is very much related to VSCode internal configuration.

**Comment by weinand** [comment]
If it works in VS Code, but not outside, then the problem does not seem to be a VS Code problem, right?

**Comment by vineetmimrot** [comment]
But "npm test" command launches "node ./out/configure/test/runTest.js" script which is generated by YO generator during extension creation. runTest.js file internally calls vscode-test module, which further runs the tests.

**Comment by weinand** [comment]
Please file this issue against https://github.com/Microsoft/vscode-test

**Comment by vineetmimrot** [comment]
I have created the issue yesterday on [vscode-test](https://github.com/microsoft/vscode-test/issues/72) repo. But by looking at the history of the repository, there is not much activity in the last 3-4 months. This made me to create an issue here which is much more active and I though the developer team would be same for both.
