### ISSUE TITLE
Web playground: Enter stops working in editor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#106303]
Originally filed by @chrmarti 

Open https://vscode-web-test-playground.azurewebsites.net/
Open file, adding lines with Enter works
Cmd + , to open settings
Switch back to file, adding lines with Enter no longer works 🐛

Version: 1.48.0-insider
Commit: 7906d414c0af9e1e6cc4497559add84250d35d49
Date: 2020-08-04T09:42:03.624Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0

**Comment by roblourens** [comment]
This is because Firefox does not fire 'blur' when a focused element is removed from the DOM.  https://bugzilla.mozilla.org/show_bug.cgi?id=559561

So the editor does not fire `onDidBlurEditorText` and we will need to make sure we fire that manually when an editor is closed. Have we dealt with this already? @alexdima @bpasero

**Comment by alexdima** [comment]
@roblourens I just used the troubleshooting keybindings action and saw the following:

```
 INFO [KeybindingService]: / Received  keydown event - modifiers: [], code: Enter, keyCode: 13, key: Enter
 INFO [KeybindingService]: | Converted keydown event - modifiers: [], code: Enter, keyCode: 3 ('Enter')
 INFO [KeybindingService]: | Resolving [Enter]
 INFO [KeybindingService]: \ From 22 keybinding entries, matched settings.action.focusNextSetting, when: inSettingsSearch, source: built-in.
```

So the root cause is `inSettingsSearch` is `true`.

I have solved such issues by creating a child context: `IContextKeyService.createScoped` on the root dom node of the widget. Then, you could just "hard-code" that key to be true on the scoped context key service. You would then need to create a new instantiation service and be sure to use that one to construct any widgets that you use.

Otherwise, I'm not 100% sure what the editor should do here. Does the workbench inform you when the tab is hidden? Can you add a workaround there and unset `inSettingsSearch` there?

**Comment by roblourens** [comment]
Yeah, I am describing why `inSettingsSearch` is true. It's easy to hack around it here but it seems like we can no longer trust `onDidBlurEditorText` or even the 'blur' event anywhere. I don't understand why something so fundamental would be different in firefox. So we need to either audit every usage of it or just keep this in mind for weird FF bugs in the future.

**Comment by roblourens** [comment]
@rebornix you said you had seen this before, is there an issue anywhere or what investigation did you do?

**Comment by rebornix** [comment]
@roblourens I think we are investigating into the same thing https://github.com/microsoft/vscode/issues/83599#issuecomment-551355585

**Comment by roblourens** [comment]
Ok yeah that is exactly the same bug. The original actually still reproes because the `onHide` call happens when the editor still has DOM focus.

**Comment by roblourens** [comment]
Eh, I pushed another workaround. I also briefly looked at other usages of the blur event and `onDidBlurEditorText`. I don't see anything really dangerous but the same issue definitely shows up in other places. 

Example, 
- Start renaming a file in the explorer. 
- Close the sidebar
- Reopen the sidebar

In chrome/electron, the rename has been committed. In FF, the renamed row is still an input box.

If FF isn't high priority we can just fix these as they are noticed and come up. Otherwise we need to do something more aggressive like... ban blur, or add a helper that combines it with a mutation observer to patch the event, or just audit every usage and leave comments everywhere. I still feel like I'm missing something. https://bugzilla.mozilla.org/show_bug.cgi?id=559561. IE6 flashbacks. Also a codepen with a reduction https://codepen.io/roblourens/pen/bGpLjqv
