### ISSUE TITLE
No authentication provider 'microsoft' is currently registered

### ISSUE THREAD

**Issue by carlocardella** [microsoft/vscode#106321]
```
Version: 1.49.0-insider (user setup)
Commit: e4256dd1a02339bb1d56647ecd9134bf38bc7c03
Date: 2020-09-04T18:49:12.955Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

Steps to Reproduce:
- This is happening only on one machine (details above) with the latest Insiders
- The Stable version works fine, settings sync included
- The same Insiders version works fine on other machines

I see this: 

![image](https://user-images.githubusercontent.com/5784415/92544518-f0adcd80-f202-11ea-9632-9f910aa4e4bb.png)

Troubleshooting done so far:
- Started using `--disable-extensions`
- Started using `--log trace` hoping to find more details in the logs
- Completely removed Insiders
  - deleted `C:\Users\carloc\AppData\Local\Programs\Microsoft VS Code Insiders`
  - deleted `C:\Users\carloc\.vscode-insiders`
  - deleted `C:\Users\carloc\AppData\Roaming\Code - Insiders`
- Reinstalled Insiders using the latest x64 msi (downloaded today), no other extensions installed

The devtools console shows this: 

```
log.ts:197   ERR No authentication provider 'microsoft' is currently registered.: Error: No authentication provider 'microsoft' is currently registered.
    at E.getSessions (file:///C:/Users/carloc/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4407:7)
    at async e.getAccounts (file:///C:/Users/carloc/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6019:534)
    at async e.update (file:///C:/Users/carloc/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6019:334)
    at async e.initialize (file:///C:/Users/carloc/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6018:345)
    at async e.waitAndInitialize (file:///C:/Users/carloc/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6017:711)
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/carloc/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/semver-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/carloc/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/carloc/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/ExperimentationService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/carloc/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/TasApiFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/carloc/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/FilteredFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/carloc/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/BaseFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/carloc/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/AxiosHttpClient.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/carloc/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/ExperimentationServiceAutoPolling.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/carloc/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/ExperimentationServiceBase.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/carloc/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/MemoryKeyValueStorage.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/carloc/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/PollingService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/carloc/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/main.js.map: 
```

Seems clear the problem is with this specific installation/machine, but I've not been able to figure out what is wrong. 
Interestingly, this Insiders instance was working file last Friday, when I left the machine running untouched through the long weekend and this morning I found it as described.

What else can I try?

**Comment by carlocardella** [comment]
The SourceMap error does not bug me, I didn't even notice it before looking at the devtools console. 
What I care about is the missing authentication provider: with that error I simply cannot enable settings sync, not even using Github (which works fine to authenticate the RP Extension)

**Comment by RMacfarlane** [comment]
@carlocardella Can you copy-paste the logs from the output panel with "Microsoft Authentication" selected? This message is shown when trying to refresh the token repeatedly fails, so there is not valid authentication information available. Has anything changed about your network on the machine that shows this?

**Comment by carlocardella** [comment]
No networking changes that I am aware of, and the Stable release on this same machine works fine, the problem is only with Insiders. 

Here's the output from Insiders:

```
[Info  - 14:20:49.556] Refreshing token...
[Error  - 14:20:49.810] Refreshing token failed
[Error  - 14:20:49.810] Refreshing token failed
[Info  - 14:20:54.813] Refreshing token...
[Error  - 14:20:55.150] Refreshing token failed
[Error  - 14:20:55.150] Refreshing token failed
[Info  - 14:21:15.165] Refreshing token...
[Error  - 14:21:15.415] Refreshing token failed
[Error  - 14:21:15.415] Refreshing token failed
[Error  - 14:21:15.415] Token refresh failed after 3 attempts
[Info  - 14:21:15.416] Token expired or unavailable, trying refresh
[Info  - 14:21:15.416] Refreshing token...
[Error  - 14:21:15.765] Refreshing token failed
[Error  - 14:21:15.765] Refreshing token failed
[Info  - 14:21:15.767] Token expired or unavailable, trying refresh
[Info  - 14:21:15.767] Refreshing token...
[Error  - 14:21:16.148] Refreshing token failed
[Error  - 14:21:16.148] Refreshing token failed
[Info  - 14:21:21.107] Token expired or unavailable, trying refresh
[Info  - 14:21:21.107] Refreshing token...
[Error  - 14:21:21.359] Refreshing token failed
[Error  - 14:21:21.359] Refreshing token failed
[Info  - 14:51:15.422] Refreshing token...
[Error  - 14:51:15.693] Refreshing token failed
[Error  - 14:51:15.693] Refreshing token failed
```

This is from Stable on the same machine:

```
[Info  - 13:16:46.934] Refreshing token...
[Info  - 13:16:47.302] Token refresh success
[Info  - 13:16:47.305] Token available from cache, expires in 3598997 milliseconds
[Info  - 13:16:47.305] Token available from cache, expires in 3598997 milliseconds
[Info  - 14:16:16.289] Refreshing token...
[Info  - 14:16:16.571] Token refresh success
[Info  - 14:16:16.574] Token available from cache, expires in 3598997 milliseconds
[Info  - 14:16:16.574] Token available from cache, expires in 3598997 milliseconds
[Info  - 15:12:58.121] Token available from cache, expires in 197450 milliseconds
[Info  - 15:15:45.557] Refreshing token...
[Info  - 15:15:45.751] Token refresh success
[Info  - 15:15:45.754] Token available from cache, expires in 3598996 milliseconds
[Info  - 15:15:45.754] Token available from cache, expires in 3598996 milliseconds
```

**Comment by Cabemo** [comment]
I was having the same problem for github (i.e. No authentication provider 'github' is currently registered). I was installing the snap package. I removed it and installed the .deb package and works fine with both microsoft and github providers. Hope it helps.

**Comment by carlocardella** [comment]
Thanks, that's interesting to know, unfortunately my problem is on Windows and with a fresh install, no additional extensions, I just run the MSI and launch vscode insiders right after that, no third party extension can cause this as there is none installed

**Comment by carlocardella** [comment]
I investigated this further, I compared a working instance (Stable) and this broken one (Insiders): both issue a POST to `https://login.microsoftonline.com/organizations/oauth2/v2.0/token`, the broken request receives a 400 back with this description: 

`
{"error":"invalid_grant","error_description":"AADSTS700003: Device object was not found in the tenant 'f8cdef31-a31e-4b4a-93e4-5f571e91255a' directory.\r\nTrace ID: 6a98c866-d152-4b8c-9323-c267643a4d00\r\nCorrelation ID: 7783e740-4e79-4c3c-82c5-32224fdfd7bf\r\nTimestamp: 2020-09-17 01:38:41Z","error_codes":[700003],"timestamp":"2020-09-17 01:38:41Z","trace_id":"6a98c866-d152-4b8c-9323-c267643a4d00","correlation_id":"7783e740-4e79-4c3c-82c5-32224fdfd7bf","error_uri":"https://login.microsoftonline.com/error?code=700003","suberror":"device_authentication_failed"}
`

**Comment by carlocardella** [comment]
I spent some more time inspecting the http requests and responses on the working and bad instances and was finally able to track the problem down to the cached credentials in Windows Credential Manager. I have deleted the two items highlighted and after restarting vscode insiders sync was working again. 
I have no idea what happened to those cached credentials but at this point I don't really care to continue investigate (assuming it is even possible to find out more), I'm happy to be able to use Insiders again 😄 
I hope this helps someone else.

![image](https://user-images.githubusercontent.com/5784415/93545603-b389bf80-f915-11ea-96f3-3d7d8b9e4abc.png)

**Comment by RMacfarlane** [comment]
Thanks @carlocardella for the time investigating this!

I just pushed a change to automatically delete the stored credentials if we get a bad response back on refresh and show a notification about it.

**Comment by steelx** [comment]
Im facing this same issue on PopOs 20.04 ? How do I fix this

**Comment by rzhao271** [comment]
\closedWith 403a6895f401c397933ec5c4f7d89432a33509b6

**Comment by carlocardella** [comment]
I no longer have a repro to confirm the specific problem has gone, anyway I am on the latest insiders and everything is working fine

**Comment by PulsGarney** [comment]
On Mac, when I try to sync settings, which requires login first, I get this error: `Error while starting Settings Sync: No authentication provider 'github' is currently registered`. Which is quite similar to this one. expect @carlocardella seems already get the Github logged in.

Both of the auto-redirect and manually copy paste generated token did not work.
I've already checked Keychain access, seems like there is nothing related to vscode.
Any idea on how to solve this? please.

![image](https://user-images.githubusercontent.com/25129308/95478843-a617a080-09bc-11eb-84d9-3cc4ef2b6f22.png)

**Comment by RMacfarlane** [comment]
@PulsGarney This sounds like a different problem, so I have created a new issue to track it: https://github.com/microsoft/vscode/issues/108319

**Comment by PulsGarney** [comment]
> @PulsGarney This sounds like a different problem, so I have created a new issue to track it: #108319

Okay, Thank you
