### ISSUE TITLE
NotebookEditor debt/api issues

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#106336]
A couple of issues/questions come up when going through the notebook editor api

* There is `NotebookEditor#active` and there is `vscode.notebook.activeNotebookEditor`. We should nuke the former in favour of the latter. 
* There is `NotebookEditor#visible` which is highly questionable because the model should be that a non-visible editor is no editor. That's the model of text editors and we should follow the same model

**Comment by jrieken** [comment]
We should also move `activeNotebookEditor` to `vscode.window` because it is a window property

**Comment by rebornix** [comment]
> There is NotebookEditor#active and there is vscode.notebook.activeNotebookEditor. We should nuke the former in favour of the latter.

> That's the model of text editors and we should follow the same model

The reason we put `active` on `NotebookEditor` previously is we need an explicit way to identify an alive but non-visible notebook editors as notebook editors are retained and extensions can still talk to its webview.

Now that we separate `NotebookEditor` and `NotebookCommunication` so I'm wondering if we can archive the same thing with following API changes

* `NotebookEditor` no longer has `active` or `visible` properties
* `vscode.window.activeNotebookEditor` is the only active notebook editor in the workbench, it's undefined when the focused element is not a notebook editor
* `vscode.window.visibleNotebookEditors` are all visible notebook editors in the workbench
* `NotebookCommunication.onDidDispose: Event<void>` emits events when the comm object is disposed (happens only when the notebook editor is disposed in the UI).

@DonJayamanne can you help confirm this covers all the scenarios? I remember we added `active/visible` properties to help Python extension to handle kernel/renderer communications properly so want to confirm if the new proposal works 100%.

**Comment by DonJayamanne** [comment]
> NotebookEditor no longer has active or visible properties

We don't use the `active` & `visible` properties. Please feel free to remove them.
We rely on `activeNotebookEditor`. 

> Python extension to handle kernel/renderer communications properly so want to confirm if the new proposal works

Nope, we don't use that.
We rely on the webview being alive even if the notebook is put to the background (i.e. there is another active editor).
& I was using `onDidCloseNotebookDocument` to dispose any related objects (including the comms channel for IPyWidgets). Basically if the notebook has been closed, then we server all comms (dispose everything associated with that notebook).

> NotebookCommunication.onDidDispose

Thought I can see this being used by others extension authors.
I think we'll continue to use the event `onDidCloseNotebookDocument` at least for ipywidgets (as this encompasses everything).

Please note: We have not yet officially implemented IPyWidgets in the new VSC Notebook UI. However I have it working in a private branch with the current API (without the use of `active`, `visible`, etc). (will ping separately with issues related to that)

**Comment by rebornix** [comment]
@DonJayamanne thanks for the confirmation. I'll make the changes proposed above.
