### ISSUE TITLE
Views contribution point should support codicons

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#106348]
For example, I'd like to use a codicon for the icon here:

https://github.com/microsoft/vscode-pull-request-github/blob/ab61f7f2446995c21db6087cb41b0395795b1bc5/package.json#L361-L368

**Comment by sandy081** [comment]
Codicons are supported now in View Container and View icons. You can use the same format as in other icon contributions.

Eg: `"$(code)"`
