### ISSUE TITLE
After upgrade GO to 1.7 version, the Code just won't show intellisense for a variable

### ISSUE THREAD

**Issue by Dmdv** [Microsoft/vscode#10639]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. choose GOLANG environment
2. start coding, declare import, for example fmt
3. after typing fmt. and pressing space there is no dropdown hint about available methods, just "Panic"

**Comment by alexandrudima** [comment]
Moved to Microsoft/vscode-go#441
