### ISSUE TITLE
Problem with ż character ( option + z )

### ISSUE THREAD

**Issue by DanielMiara** [microsoft/vscode#106386]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Version: 1.48.2
2. Mac 10.15.6 ( Polish Pro  keyboard schame )

I can not tap ż ( option + z ) character from my keyboard but I can capital one Ż ( shift+ option + z ).

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
@DanielMiara option+z is bound by default to toggle word wrap. Can you please go to the keybindings editor (cmd+k cmd+s) and search for option+z and right click and choose Remove keybinding.

**Comment by DanielMiara** [comment]
Thank you very much. It helps me a lot 👍
