### ISSUE TITLE
Extension Error 

### ISSUE THREAD

**Issue by debby12345** [microsoft/vscode#106345]
I've been getting this error on vs code I've tried all possible solutions including vs code insiders still I am unable to see extensions install and uninstall extensions I am still getting the same errors as posted in #10634

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
May I know what error you are getting?

Can you also please provide steps to repro?
