### ISSUE TITLE
[Settings Sync] empty java.json (both local and remote) can't merge and prevents enabling sync

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode#106307]
- VSCode Version:  1.48.2
- OS Version:  Windows 10 2004 (19041.450)

Steps to Reproduce:

1.  Settings Sync:  Turn On
2.  Log in with GitHub
3.  dialog show conflict with settings.json, keybindings.json, java.json, extensions.json
4.  choose manually merge
5.  all can be merged fine except java.json
6.  clicking Accept Local or Accept Remote does nothing.
7.  Turn on Settings Sync button remains greyed out.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by burtonrodman** [comment]
btw, java.json is empty, but remote and local -- not sure why it's showing a conflict to begin with, but regardless it won't let you accept either file.

**Comment by sandy081** [comment]
May I know if `java.json` exists locally or remotely? If exists locally, can you please provide the content of that file?

**Comment by burtonrodman** [comment]
after starting the Turn On process again, java.json was not showing a conflict
