### ISSUE TITLE
Test: detect high contrast and detect OS color scheme

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#106389]
Refs: #105715

- [x] windows @deepak1556
- [x] macOS @JacksonKearl
- [x] linux @aeschli
- [x] anyOS (web) @bpasero

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23106389%0A%0A)

---

Test the settings `window.autoDetectColorScheme` and `window.autoDetectHighContrast`. They now work on MacOS and in the Web as well. 

On the web:  High contrast detection is enabled on the latest Edge by default. On Chrome it has to be enabled with `chrome://flags`, enable `Forced colors` . light dark mode is enabled on Chrome by default, on Edge it has to be enabled in the Edge settings.

When `window.autoDetectHighContrast` is enabled (default on), VS Code reacts to high contrast change in the OS. When detected, it uses the theme specified at `workbench.preferredHighContrastColorTheme`.

When `window.autoDetectColorScheme` is enabled (default off), VS Code reacts to dark/light mode change in the OS. When detected, it uses the theme specified at `workbench.preferredLightColorTheme` and `workbench.preferredDarkColorTheme`

- Test that VSCode detects the color scheme & hc changes
- Test that VSCode switches to the preferred theme
- Test that the `workbench.colorTheme` setting is changes to the new theme, but only in the user settings
- Test that changes to the autoDetect settings to the preferred theme settings are honored.
- Test that when toggling the the autoDetect settings back to off,  the theme that was used before is set again. (Note: the last used theme is not remembered across restarts of VSCode)
- Test that when starting VSCode, any color scheme OS changes that happend while VSCode was closed are detected
- Test that changing the current theme to a non preferred theme is honored and is only changed back to the preferred theme when there is an actual color scheme OS change detected.

**Comment by bpasero** [comment]
I saw some weird behaviour with restoring the previous configured theme. I was editing my settings (in the file) and removed all of them, including the `"window.autoDetectColorScheme": true` one. When I saved, my previous theme came back into the settings file. I wonder if we can be more clever and not do this if I change the settings file myself.

**Comment by aeschli** [comment]
Ubuntu 20.04 supports light/dark mode. Electron detects the scheme on startup, but has a bug that the update event is not working: https://github.com/electron/electron/issues/23861#issuecomment-650540860
So in VS Code, `"window.autoDetectColorScheme": true` works on Linux, but only on startup.
