### ISSUE TITLE
TypeScript + React - color issue with decorators

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10630]
- VSCode Version: Code - Insiders 1.5.0-insider (55168276e4c0b6ec2404ac20af04eeed5f5b1000, 2016-08-17T06:04:29.075Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

```ts
@dec<{}>()
class Test {
}
```

![image](https://cloud.githubusercontent.com/assets/1723815/17752511/35e51390-649a-11e6-999a-329b051a7a72.png)

**Comment by alexandrudima** [comment]
Moved to Microsoft/TypeScript-TmLanguage#247
