### ISSUE TITLE
What's the condition for DocumentLink target to be undefined?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#106308]
I would like to use api to get links from the document:

```ts
const links = await vscode.commands.executeCommand<DocumentLink[]>('vscode.executeLinkProvider', document.uri);
```

`DocumentLink` is guaranteed to have a `range: Range;`, but not the `target?: Uri;`. What are the cases when `target` is undefined, or am I using the wrong type?

**Comment by usernamehw** [comment]
https://github.com/microsoft/vscode/blob/62f1bf8c6bacd26dd7c3b8e2360d4728f2a26450/src/vs/vscode.d.ts#L4030-L4058

**Comment by jrieken** [comment]
Links without target must be resolved, see https://github.com/microsoft/vscode/blob/ab4892d63b5949638353d1fc0b2164ea506c1cdf/src/vs/vscode.d.ts#L4086. The command seems to not resolve them.
