### ISSUE TITLE
Emoji get inserted twice in OSX Firefox

### ISSUE THREAD

**Issue by belcherj** [microsoft/vscode#106392]
**monaco-editor version:** 0.X.Y
Latest

**Browser:**
Firefox 78.0.2 (64-bit)

**OS:**
macOS 10.5.6

**Playground code that reproduces the issue:**
  1. In Firefox on OSX goto https://vscode-web-test-playground.azurewebsites.net/
  2. From the edit menu, click Emoji & Symbols
  3. Select an emoji to insert
  4. Emoji gets inserted twice

Also reproducible at:
- https://microsoft.github.io/monaco-editor/
- https://microsoft.github.io/monaco-editor/playground.html

**Comment by belcherj** [comment]
Possible dupe: https://github.com/microsoft/monaco-editor/issues/1848

**Comment by belcherj** [comment]
Possible dupe: https://github.com/microsoft/vscode/issues/87199

**Comment by alexdima** [comment]
Probably the input is deduced incorrectly in the input event handler -- https://github.com/microsoft/vscode/blob/1fccb9e58c7b03f218ccab2124b0262b1d1bcb9a/src/vs/editor/browser/controller/textAreaInput.ts#L312-L338

**Comment by belcherj** [comment]
Found the issue: https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/editor/browser/controller/textAreaState.ts#L96

text.length will not return a valid length for some characters as a single character could have multiple UTF-16 units.

Working out the best way to calculate.

**Comment by dmsnell** [comment]
Not like I know my way around the code but I'm surprised there's not a string-length function in [vs/base/common/strings.ts](https://github.com/microsoft/vscode/blob/25ad7485b3aa2dea43ab945b4f6af94cf0537b09/src/vs/base/common/strings.ts).

Considering that this also affects accented characters it's probably not limited to surrogate pairs though. It could be an issue with counting grapheme clusters (or whatever segmentation is used in the app). `é` can be represented by two separate _code points_ in a sequence: `e` and `́`

You might double-check the theory @belcherj with that input too.

**Comment by belcherj** [comment]
I was wrong. Changing the length here does not fix the issue:

https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/editor/browser/controller/textAreaState.ts#L96

Adding isFirefox here does resolve the issue:

https://github.com/microsoft/vscode/blob/d52f31e78d1cae95d055e25c7bbc226d968934d5/src/vs/editor/browser/controller/textAreaInput.ts#L300

I want to understand why that is the case and do more testing then I'll create a PR.

**Comment by belcherj** [comment]
@alexdima PR ready for review: https://github.com/microsoft/vscode/pull/106873
