### ISSUE TITLE
notebook cell language is not updated

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#106359]
- VSCode Version: 1.49.0-insider, commit e790b931385d72cf5669fcefc51cdf65990efa5d
- OS Version: Win10 19041.450 (2004)

Steps to Reproduce:

1. Install the [.NET Interactive Notebook Extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode) to the latest insiders build.
2. Open a blank `.dib` file.
3. The first cell is C#.
4. Execute the code `ls`.
5. It fails as expected.
6. Change the cell language to `PowerShell`.
7. Re-execute the cell.
8. The cell's language is still reported as C# as confirmed by a breakpoint [here](https://github.com/dotnet/interactive/blob/8afa87f45f12e958a6447ad7fec291b7683b2301/src/dotnet-interactive-vscode/src/vscode/notebookProvider.ts#L124).

Does this issue occur when all extensions are disabled?: N/A

Issue first discovered in dotnet/interactive#764.

**Comment by rebornix** [comment]
Fixed via c53524a198ca46dd327d2559bcafa9296d6230e6

**Comment by connor4312** [comment]
I was not able to verify this -- the `.NET Interactive -- Create Blank Notebook` command resulted in an infinitely loading notebook on the latest insiders

!{](https://memes.peet.io/img/20-10-5c635353-3c51-4ee9-86fd-bd312b988ee9.png)

**Comment by rzhao271** [comment]
Adding `author-verification-requested` because I got the same result as @connor4312 and I'm not sure whether that means something regressed.

**Comment by rzhao271** [comment]
\closedWith c53524a198ca46dd327d2559bcafa9296d6230e6
