### ISSUE TITLE
EPIPE write failure while debugging after upgrading to 1.49

### ISSUE THREAD

**Issue by szul** [microsoft/vscode#106484]
- VSCode Version: 1.49
- OS Version: Pop OS 20.04 (Ubuntu)

Steps to Reproduce:

1. Upgrade to 1.49
2. Trying to debug

Does this issue occur when all extensions are disabled?: Yes

After upgrading to 1.49, both a Linux Pop OS machine and a Mac OSX machine on my team started having the following error: When attempting to launch the debugger, we would receive a failure to write EPIPE error. The error triggers in the `tslib` package. In our particular situation, it starts with an attempt to `createConnection()` with the TypeORM package (which uses `node-mssql` and `tedious`). Stepping into that breakpoint trigger the `tslib` failure and the EPIPE message.

Rolling back to VSCode 1.48 eliminated the problem.

**Comment by weinand** [comment]
What debugger are you using?

**Comment by szul** [comment]
The built-in debugger with Visual Studio Code. This occurs at project start-up when clicking the debug icon.

**Comment by weinand** [comment]
And the problem reproduces after disabling all extensions?

**Comment by szul** [comment]
@weinand Yes on both the Debian version and the Mac OSX version of Visual Studio Code 1.49. The only thing that fixed it was rolling back to 1.48 (which fixed it on both computers).

**Comment by weinand** [comment]
Does it make a difference if you:
- comment out the "preLaunchTask"?
- add `"debug.javascript.usePreview": false` as a user setting?

**Comment by szul** [comment]
@weinand I can give this a shot this weekend. Right now I need the downgraded version for work-related tasks, so I'll have to carve out some time to try it.

**Comment by nico93f** [comment]
> Does it make a difference if you:
> 
> * comment out the "preLaunchTask"?
> * add `"debug.javascript.usePreview": false` as a user setting?
> 
> (only one at a time, not both)

Same problem,

I dont have preLaunchTask and the `usePreview: false` didn't work

**Comment by connor4312** [comment]
Can you also try adding `nodeVersionHint: 10` to your launch.json?

**Comment by nico93f** [comment]
> Can you also try adding `nodeVersionHint: 10` to your launch.json?

`nodeVersionHint` is not recognized as a valid config key, you mean here?

![image](https://user-images.githubusercontent.com/14969854/92943510-3d72ed80-f429-11ea-8efe-7aa6975d1561.png)

**Comment by connor4312** [comment]
Yep, there

**Comment by nico93f** [comment]
Oh btw, it didn't work :stuck_out_tongue:

**Comment by connor4312** [comment]
Looks like the EPIPE my Next.js is coming from Node's [inspector internals](https://github.com/nodejs/node/blob/8d1d5f9cbdaf62f324368ece528b415d04dfb49e/lib/internal/inspector_async_hook.js#L25), triggered originally from [jest-worker](https://github.com/facebook/jest/blob/3150a81c412f50b58753884656f32b1d236f7b66/packages/jest-worker/src/workers/ChildProcessWorker.ts#L87). Continuing to investigate4.

**Comment by maximedupre** [comment]
I have the same problem, using Koa.js. Not using next.js or jest.

**Comment by maximedupre** [comment]
Actually `"debug.javascript.usePreview": false` does resolve the problem on my side.

**Comment by connor4312** [comment]
It should, since the old debugger doesn't know how to debug child processes (which is where the one repro case I have fails).

Are you able to collect a trace log @maximedupre?

**Comment by maximedupre** [comment]
@connor4312 Just sent the trace log to your email address

**Comment by connor4312** [comment]
I think I found the issue! Please try adding **"outputCapture": "std",** in your launch.json (may need to change `type` to `pwa-node` for it to be seen as valid).

This fixes the issue for me; let me know if it does the same for you.

**Comment by maximedupre** [comment]
Yep that fixes the issue! Didn't need to change to `"type": "pwa-node"`.

**Comment by connor4312** [comment]
Awesome, thank you for confirming. I will put in a fix for the recovery release.
