### ISSUE TITLE
error, display of Arabic word in csv file 

### ISSUE THREAD

**Issue by byhwdy** [microsoft/vscode#106443]
- VSCode Version:  1.49.0
- OS Version:  macos 10.15.6

Steps to Reproduce:
1. I have a line in sublime  as the below pic show
![sublime](https://raw.githubusercontent.com/byhwdy/images/master/WX20200911-101837%402x.png)

2. when i copy the line in sublime to vscode,  vscode show the line like the below pic show. The position of "," is wrong.
![vscode](https://raw.githubusercontent.com/byhwdy/images/master/WX20200911-101800%402x.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by byhwdy** [comment]
some example text:
a,b,الإسكندرية، مصر,91495380f7f5cc2b6ad1b99359616ffe

**Comment by alexdima** [comment]
Once an extension that adds CSV highlighting is installed (like [Rainbow CSV](https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv)), the rendering is the one that is expected:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/5047891/206868541-3a31d2f3-eb7b-4401-a5ca-8ccd3bdef244.png">
