### ISSUE TITLE
The subset of all search matches did not show

### ISSUE THREAD

**Issue by GitCodeview** [microsoft/vscode#106453]
- VSCode Version: 1.49.0 (user setup)
- OS Version: Window_NT x64 10.0.18363

Steps to Reproduce:

1. type search a keyword which exist in tons of files
2. search serveral time
3. at last, i can't get any results, it will show some at sometimes.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Please check whether any tips here help: https://github.com/microsoft/vscode/wiki/Search-Issues
