### ISSUE TITLE
Allow extensions to provide additional info for the bug report form

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode#106471]
Right now, when reporting an extension bug through, e.g., `Help - Report Issue`, the only info we get is from VS Code itself (platform, VS Code version, extension version, etc.) or from the user.

But for many extensions, it would be useful to also send additional details. For example, language extensions might include the version of the language server to help diagnose the issue.

So it would be nice to have an API similar to:

```ts
interface IssueDataProvider {
  provideData(): ProviderResult<Record<string, any>>;
}

namespace extensions {
  registerIssueDataProvider(provider: IssueDataProvider);
}
```

Or, really, any other way to add data to an issue.

**Comment by RMacfarlane** [comment]
This is a great feature request! There is already an issue for this: https://github.com/microsoft/vscode/issues/46726 Please continue the discussion there, thank you.
