### ISSUE TITLE
Extension LSP process forcefully terminated when VS Code is quit, on Windows

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#106433]
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

1. Implement an LSP server for VS Code
2. Handle LSP shutdown message
3. Run it on Windows
4. shutdown message is not received.

We're looking at an issue with the C/C++ Extension in which our native (LSP) process appears to be getting forcefully terminated when VS Code is quit.  This is only repro'ing on Windows.  On Linux and Max, we appear to be getting the chance to shut down gracefully.

Some background on our scenario is here: https://github.com/microsoft/vscode/issues/35196

We have 2 ways of detecting shutdown.  1. We handle the LSP "shutdown" message.  2. We interpret a failure to read from std::cin as an indication that we should shut down.  I can confirm that neither of these are occurring for us, on Windows.  I'm not sure when this behavior broke.  Our process is also terminated too quickly, not after the expected 5 second delay.

The result for us is that our DB is not closed gracefully, leading to needing to rebuild it in some cases.

I've tried specifying `detached: true` when constructing the LanguageClient.  That actually resulted in the expected behavior (detecting shutdown due to std::cin being closed.  I've never seen the "shutdown" message received), and everything shut down cleanly.  That would seem to suggest that, without this flag, VS Code is indeed trying to terminate our child process immediately on quit instead of allowing us to shut down gracefully.  It would be best if we could avoid having to use `detached`, as it could lead to other issues (lingering processes).

**Comment by dbaeumer** [comment]
This is actually the default Windows behavior. In Windows all child processes are terminated if the parent process is terminated. This is different under Linux and Mac. An extension host gets ~5 seconds to terminate (@alexdima can you fill in the correct number). After that the extension host gets forcefully terminated. If a server needs to survive this the only way to go is `detached: true`. This is why that property exists.

**Comment by dbaeumer** [comment]
I am in favor of closing the issue since there is nothing we can do against the Windows OS behavior.

**Comment by alexdima** [comment]
@dbaeumer That sounds right, `deactivate` gets called on an extension and then after at most 5 seconds the extension host process will exit. On windows, this will brutally kill all of the child processes of the extension host. The only way to have the child processes survive is to use `detached: true`, but then you need to be very careful not to leak any processes in case the extension host crashes. 

There is some exception to this, I'm not sure why, but when debugging an extension, the debugger kills the extension host process before the 5 seconds.

**Comment by Colengms** [comment]
@alexdima @dbaeumer To reiterate, the issue is that it does NOT wait 5 seconds before killing us on Windows.  It gives us no time to shut down gracefully.  I can easily repro, regardless of whether debugging is involved.  Please confirm that this does not immediately and obviously repro for you with a simple repro case.

**Comment by Colengms** [comment]
Also, could you clarify how an extension is notified of shutdown?  I see no reference to `deactivate` in [the API docs](https://code.visualstudio.com/api/references/vscode-api), VS Code APIs, or LanguageService APIs.  LSP defines [`shutdown` and `exit` messages](https://microsoft.github.io/language-server-protocol/specification#shutdown), but we don't appear to receive these from VS Code.

**Comment by sean-mcmanus** [comment]
@Colengms I see cpptools linger for around 5 seconds after closing VS Code.

**Comment by Colengms** [comment]
@sean-mcmanus I definitely do not, on Windows.  I see the process disappear within a second or so (it probably terminated more quickly than the task manager reflected it), and I repro the DB not getting closed.

**Comment by sean-mcmanus** [comment]
@dbaeumer But the LSP shutdown message is supposed to be sent to us, right? Colen said he was seeing that message not be sent, and that matches what I see with cpptools lingering due to not receiving any shutdown message.

**Comment by Colengms** [comment]
Aha.  Our exported `deactivate` in TS (not native LSP) gets called on shutdown.  So, I think I can solve this by adding our own communication with our native LSP process to ask it to shut down, and wait for that to complete.

However, to redirect, our native process was waiting for a shutdown LSP message that we don't seem to receive.  https://microsoft.github.io/language-server-protocol/specification#shutdown

Should we be receiving shutdown and exit LSP messages?

**Comment by Colengms** [comment]
Figured it out.  Our bug.  Closing.

**Comment by dbaeumer** [comment]
Just to clarify. Deactive can return a promise. The recommended way is to call stop on the LSP client in deactivate.
