### ISSUE TITLE
window.titleBarStyle=custom reports window as resizable

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#106464]
- VSCode Version: 1.49.0
- OS Version: Manjaro Linux 20.1

Steps to Reproduce:

Video demonstration: https://streamable.com/7n20m1
1. Set `window.titleBarStyle` to `custom`.
2. Open vscode 1.49.0 as the only window in a virtual desktop of i3wm-gaps 4.18.2.
3. Point cursor at the edge of the vscode window.
4. Observe window reported as resizeable by cursor icon change (not expected).
5. Open another window of any application.
6. Point cursor at the edge of the vscode window.
7. Observe window reported as resizeable by cursor icon change (not expected).
6. Point cursor at the edge of the window of a different application.
7. Observe window not reported as resizable by cursor not changing (as expected).

Does this issue occur when all extensions are disabled?: Yes

**Comment by avemilia** [comment]
Reproducible as of

```
Version: 1.52.0-insider
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:40:12.937Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.3-1-MANJARO
```

**Comment by deepak1556** [comment]
Unable to repro with VSCode `1.74`
