### ISSUE TITLE
window.titleBarStyle=native doesn't propagate clicks on fullsized window

### ISSUE THREAD

**Issue by avemilia** [microsoft/vscode#106463]
- VSCode Version: 1.49.0
- OS Version: Manjaro Linux 20.1

Steps to Reproduce:

Video demonstration: https://streamable.com/rc8yp5
1. Set `window.titleBarStyle` to `native`.
2. Open vscode 1.49.0 as the only window in a virtual desktop of i3wm-gaps 4.18.2.
3. Click on any titlebar entry.
4. Observe lack of dropdown menu (not expected).
5. Open another window of any application.
6. Click on any titlebar entry.
7. Observe dropdown menu (as expected).
8. Close another application window.
9. Click on any titlebar entry.
10. Observe dropdown menu (as expected).

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Does this happen with latest insiders https://code.visualstudio.com/insiders ?

**Comment by avemilia** [comment]
Not reproducible as of stable

```
Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:16:10.374Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.3-1-MANJARO
```

and insiders

```
Version: 1.52.0-insider
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:40:12.937Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.3-1-MANJARO
```
