### ISSUE TITLE
Revisit Proxy Auth Dialog

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#106489]
**Steps to see it in action:**
* `git clone https://github.com/microsoft/vscode-proxy-agent.git`
* `cd vscode-proxy-agent/tests/test-http-auth-proxy`
* `docker build -t test-http-auth-proxy .`
* `docker run -d -p 3128:3128 test-http-auth-proxy`
* `code --proxy-server=http://localhost:3128`
* (running out of sources: configure `extensionsGallery` in `product.json`)

![image](https://user-images.githubusercontent.com/900690/92928076-e5df7c80-f43e-11ea-893f-50ea3b39827b.png)

**Issues:**
* it shows 2 login dialogs instead of one
* it would be nice if credentials are remembered (e.g. use some auth service)
* it currently does not use our normal way of window opening via `bootstrap-window.js`
* it seems to fail when you start VSCode from a network drive (https://github.com/microsoft/vscode/issues/106468#issuecomment-692533307)
* it could get some UI polish to look more like our other (custom) dialogs
* it is not localized
* could this be a dialog triggered from within the workbench and not `electron-main`?
* can we add it to the smoke test to capture regressions earlier?
* check for more related issues: https://github.com/microsoft/vscode/labels/proxy

**Comment by deepak1556** [comment]
> could this be a dialog triggered from within the workbench and not electron-main?

Sadly no, it depends on the login event from the app module, so it has to rely on the main process and not workbench.

**Comment by bpasero** [comment]
@deepak1556 yeah that is fine, I was more wondering if we could open it from an existing window. E.g. via some IPC message to the currently active window. The only scenario where this may fail is if this dialog is needed even when no windows are opened (on macOS).

**Comment by deepak1556** [comment]
>  I was more wondering if we could open it from an existing window. E.g. via some IPC message to the currently active window

will this be an electron `BrowserWindow` opened from the currently active window or some other ui for dialogs ?

> The only scenario where this may fail is if this dialog is needed even when no windows are opened (on macOS).

Oh, which situation would this be ?

**Comment by bpasero** [comment]
> will this be an electron BrowserWindow opened from the currently active window or some other ui for dialogs ?

Yeah it could be a UI from within the window, it would not have to be a full browser window right? We have custom dialogs support inside VSCode so this could simplify things quite a bit, no?

> Oh, which situation would this be ?

Not sure. @joaomoreno from your point of view, would it be sufficient to open a custom dialog from within the workbench? Do you recall why you went with a separate window?

**Comment by joaomoreno** [comment]
It was easier to architect a separate window:

- No need for extra main -> renderer IPC channels
- It is modal. And it probably should stay modal. We had no such functionality at the time, not sure we have it now with web?
- It tackles the scenario that @bpasero explains: on macOS you can close all windows and Code is still running. The shared process can then trigger extension updates which trigger proxy auth. We can argue that this is rare and the whole operation could wait until a window opens.

**Comment by deepak1556** [comment]
> Yeah it could be a UI from within the window

In that case 💯 

> it would not have to be a full browser window right? We have custom dialogs support inside VSCode so this could simplify things quite a bit, no?

yup certainly there is no need to have a full browser window unless we are loading an external endpoint in a non-sandboxed process.
