### ISSUE TITLE
Allow createWebviewPanel in row above active column

### ISSUE THREAD

**Issue by rfrapp** [microsoft/vscode#106451]
I have an extension that I'm writing which uses a webview, and the most suitable format for this extension is a banner at the top of the editor. It would be great if we could specify to place the view above the current active column (basically do a "Split Up"). I see that it's possible to place the new view beside the active view, then the user can manually switch the orientation to stack vertically, but it'd be nice if this could be automated.

**Comment by mjbvz** [comment]
Closing this since it has not received much interest since it was opened

This is not also not possible to do with normal text editor today. More fine grained control over editor layout may fall under #15178
