### ISSUE TITLE
v1.49 creates debug.log automatically

### ISSUE THREAD

**Issue by bitfriend** [microsoft/vscode#106474]
- VSCode Version: 1.49
- OS Version: Windows 10 Enterprise - 1903

Steps to Reproduce:

1. Open react native/react js project with VS Code 1.49.
2. After project is loaded, debug.log is created automatically in root directory.

The debug.log file is created in almost source directories.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
Does this problem also occur with all extensions disabled?

**Comment by weinand** [comment]
Nevermind, this is a duplicate of #105191
