### ISSUE TITLE
unsigned .vscode-server asks firewall openings

### ISSUE THREAD

**Issue by ohhmm** [microsoft/vscode#106426]
\rootfs\home\serg\.vscode-server\bin\e790b931385d72cf5669fcefc51cdf65990efa5d\node
either sign or do not modify firewall settings 
![image](https://user-images.githubusercontent.com/190779/92805259-a161cb80-f3c1-11ea-9551-9bdb4e567b07.png)

**Comment by alexdima** [comment]
@ohhmm What steps are you doing that lead to this prompt being shown?

**Comment by ohhmm** [comment]
Hi Alrxandru,

It was updated.

Thanks,
Serg
