### ISSUE TITLE
TS Engine Always Dies

### ISSUE THREAD

**Issue by andkvo** [microsoft/vscode#106421]
Issue Type: <b>Bug</b>

It doesn't last very long before it dies.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.68GB free)|
|Process Argv|-psn_0_139298|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.5.0
vscode-sql-formatter|adp|1.4.4
Bookmarks|ale|11.3.1
vsc-material-theme|Equ|32.8.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.1.3
vscode-test-explorer|hbe|2.19.1
swagger-doc-viewer|mim|1.0.4
prettify-json|moh|0.0.3
vscode-docker|ms-|1.5.0
vetur|oct|0.26.1
openapi-designer|phi|0.3.0
vscode-yaml|red|0.9.1
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.6
vscode-jest-test-adapter|rtb|0.2.0
html5-boilerplate|sid|1.0.3

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
