### ISSUE TITLE
A recent update to the application caused the system to crash

### ISSUE THREAD

**Issue by Sicmatr1x** [microsoft/vscode#106446]
Issue Type: <b>Bug</b>

OS: Windows 10 professional x64
I just click the Manage button and click the install update button, than the screen is shown black out and computer has no response with both mouse click and keyboard.
Restart computer by PC case power button and the update is installed.

Blow info is noted when computer restarted.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600X Six-Core Processor            (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.26GB free)|
|Process Argv|--crash-reporter-id 0f8245d4-262e-42c9-8cad-a5fef6aa9f45|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
solidity|Jua|0.0.76
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by deepak1556** [comment]
Does it continue to happen with latest updates ?
