### ISSUE TITLE
Publish Linux ARM deb & rpm repositories

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#106473]
- [x] Deb
  - [x] Create working deb packages
  - [x] Publish to MS repos
  - [x] Migrate x64 repo over the new one
- [x] RPM
  - [x] Create working rpm packages - _Thanks, @psgreco_ 
  - [x] Publish to MS repos
- [ ] ~~Snap~~ 🔴
  - [ ] ~~Create working snap packages  _probably need ARM machines to build these_~~
  - [ ] ~~Publish to snap store~~

**Comment by m-roberts** [comment]
+1 for this!

**Comment by gizmotronic** [comment]
Any chance of publishing as a snap, as well?

**Comment by 0x011011110** [comment]
This would definitely be nice - something I noticed is that the debs currently install a vscode.list in /etc/apt/sources.list.d/ but it is limited to [arch=amd64] so it would be nice to have a sources.list that is correct

**Comment by joaomoreno** [comment]
@0x011011110 Yeah that's the biggest problem right now, we're looking into a good option right now.

**Comment by joaomoreno** [comment]
Snap packages are now created but they simply segfault:

```
joao@joao-ubuntu-rpi:~/Downloads$ gdb /snap/code-insiders/current/usr/share/code-insiders/code-insiders 
GNU gdb (Ubuntu 9.2-0ubuntu2) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /snap/code-insiders/current/usr/share/code-insiders/code-insiders...
(No debugging symbols found in /snap/code-insiders/current/usr/share/code-insiders/code-insiders)
(gdb) r
Starting program: /snap/code-insiders/x1/usr/share/code-insiders/code-insiders 

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000008 in ?? ()
```

```
joao@joao-ubuntu-rpi:~/Downloads$ uname -a
Linux joao-ubuntu-rpi 5.8.0-1007-raspi #10-Ubuntu SMP PREEMPT Thu Nov 5 17:52:40 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
joao@joao-ubuntu-rpi:~/Downloads$ file /snap/code-insiders/current/usr/share/code-insiders/code-insiders 
/snap/code-insiders/current/usr/share/code-insiders/code-insiders: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /snap/core/current/lib/ld-linux-aarch64.so.1, BuildID[sha1]=644557efd63781717386f34776877ca4e9fd0104, for GNU/Linux 3.7.0, stripped
```

**Comment by joaomoreno** [comment]
@flexiondotorg: As tweeted in https://twitter.com/joaomoreno/status/1329704593366847488:

> Hitting some issues. I thought that using `build-on: amd64` and `run-on: arm64` would get us there: https://github.com/microsoft/vscode/pull/111008/files#diff-74c4ea7e8a7229121137b67faf75b6808d948fbbd120adb7b0f763a52b975dedR9-R12 But the resulting snap still has an amd64 base system, so code segfaults.

> Aside from `snapcraft remote-build` it seems we can only get ARM snaps if we run it on ARM hardware, did I get that right?

---

Because of this snap ARM are currently blocked.

**Comment by joaomoreno** [comment]
We also need some help figuring out how to list RPM dependencies for ARM, since the current approach doesn't seem to work, when testing on CentOS 7 for Raspberry Pi 4 aarch64.

**Comment by joaomoreno** [comment]
Thanks to @psgreco, we now have working ARM RPM packages :fireworks: 

![Screenshot from 2020-11-25 11-09-00](https://user-images.githubusercontent.com/22350/100220187-e2707300-2f0e-11eb-9433-02a819d3dbbc.png)

**Comment by bpasero** [comment]
@joaomoreno let me know if you need any help
