### ISSUE TITLE
Multiple windows and system dialogs cause crash

### ISSUE THREAD

**Issue by Zenohate** [microsoft/vscode#106407]
- VSCode Version:
1.48.0
db40434f562994116e5b21c24015a2e40b2504e6
x64

- OS Version:
Fedora 32/Linux
- Desktop: Cinnamon
Version      : 4.6.6
Release      : 1.fc32

Steps to Reproduce:

1. Open a vscode window (eventually with a project)
2. Open a second window from the first window
3. Open the "open folder" dialog from the second window
4. Close the second window without closing the dialog
5. Any further interaction with the still open dialog is bogus, clicking the open button crashes the first window

Does this issue occur when all extensions are disabled?: Yes

Issue #81518 may be related

**Comment by deepak1556** [comment]
Does this happen with latest insiders https://code.visualstudio.com/insiders ?
