### ISSUE TITLE
Display current zoom level

### ISSUE THREAD

**Issue by ahdung** [Microsoft/vscode#10642]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Original title: How i know zoom level? ctrl+=/- | ctrl+mouseWheel

**Comment by alexandrudima** [comment]
fyi @bpasero

**Comment by ahdung** [comment]
Thanks for editing. and how to reset zoom level by ctrl+mousewheel?

**Comment by ahdung** [comment]
Thanks for editing. and how to reset zoom level by ctrl+mousewheel?

**Comment by ahdung** [comment]
Thanks for editing. and how to reset zoom level by ctrl+mousewheel?

**Comment by alexandrudima** [comment]
Sorry, there is currently no way except `F1 > Reload window`.

**Comment by blaylockbk** [comment]
Could show the zoom level for a short time when the zoom level is changed (similar to the chrome browser)

**Comment by mjbvz** [comment]
Duplicate of #12318
