### ISSUE TITLE
renamed file detected from git as (deleted and created)

### ISSUE THREAD

**Issue by urbanishimwe** [microsoft/vscode#106422]
- VSCode Version: 1.48.2-a0479759d6e9ea56afa657e454193f72aef85bd0
- OS Version: Linux 5.4.0-47-generic

Steps to Reproduce:

1. rename a file from a git repository by left-click on a file and do "rename"
2. write `git status` somewhere and click enter!
the file will be **tracked as deleted** and the renamed version will be **tracked as created!**

I am raising this a bug because if you rename the file manually(with `git mv` or `mv`), the file will be **tracked as renamed.**

Does this issue occur when all extensions are disabled?: Yes

**EDIT**
#93299 suggest

>  I think that it will be easier to do via Command Palette using "Git: Rename file" command

but I think it can a bit easier to make rename same as `mv`

**Comment by MoonE** [comment]
git should recognize the file as moved as soon as you add the old and new versions to the index by running `git add 'oldname' 'newname'`.

**Comment by urbanishimwe** [comment]
@MoonE how hard would it be to just make `VsCode renaming behaviors` same as `mv` or `git mv` as it is what so many people expect anyway?

**Comment by MoonE** [comment]
VSCode does the equivalent of a `mv` but git never shows files as moved unless they are added to its index. What you are asking is that VSCode automatically adds the change to the used version control system which isn't necessarily the desired behavior.

**Comment by urbanishimwe** [comment]
that makes sense. thanks for the clarification.. this should be close in a fever of #93299
