### ISSUE TITLE
title attribute lives on multiple explorer items for single item

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#106431]
The tooltip wouldn't disappear like that if it was only on one of them. I don't think the outer one needs it.

![recording](https://user-images.githubusercontent.com/2193314/92821201-a7cf5380-f37f-11ea-8be8-b8d4ada4d8b2.gif)

![image](https://user-images.githubusercontent.com/2193314/92821235-b1f15200-f37f-11ea-800c-844ef945c691.png)

**Comment by isidorn** [comment]
Seems like each resource label sets the title. And this might a resource label thing in general.
I am not sure who owns the resource label, but let's ping @jrieken first to get his thoughts
