### ISSUE TITLE
Renaming a file isn't being reflected in the tab if the file was opened before

### ISSUE THREAD

**Issue by yonifra** [microsoft/vscode#106458]
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T17:39:53.251Z (14 hrs ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/726718/92885442-6be9cc00-f41b-11ea-96de-30bac7becb3c.png)

1. Open a file (in my case it was a `tsx` ReactNative file
2. Rename the file by using the "Enter" key while the file is selected in the explorer window and input a new name (I changed the casing of the file)
3. The file gets updated in the Explorer view, and in the breadcrumbs, but the tab remains like it was before the renaming.

Does this issue occur when all extensions are disabled?: Yes

**Comment by yonifra** [comment]
I renamed the file from `searchBar.tsx` to `SearchBar.tsx` just to be clear.

**Comment by yonifra** [comment]
![image](https://user-images.githubusercontent.com/726718/92890712-0946ff00-f420-11ea-8483-618eb48bad2f.png)
In the search pane, it even shows two search results for the same file (before & after the rename). Might be a caching issue?

**Comment by bpasero** [comment]
@yonifra I tried to reproduce this just now and cannot. We did some recent fixes in this area but it should be fine in our latest released stable version. Can you distill exact steps maybe in a fresh folder?

**Comment by yonifra** [comment]
@bpasero I've recreated it again, but I couldn't recreate it when the other way around.
Meaning:
`camelCasing` to `PascalCasing` - Fails
`PascalCasing` to `camelCasing` - Works

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by yonifra** [comment]
@bpasero happened also after disabling extensions, so it's a VS Code issue, not extension related.
If you want, you can try replicating this issue with my own repo by cloning it (it's a public repo). I'm renaming a `tsx` React Native file, so it might be specific to that file extension?

**Comment by bpasero** [comment]
@yonifra ok can you distill steps starting from zero for me to reproduce on your repo? Best if you could try with a fresh user data dir to rule out any settings: `code --user-data-dir <empty dir>`

**Comment by yonifra** [comment]
Sure:

1. Clone https://github.com/yonifra/native-movies
2. Open it in VS Code
3. Go to the `components` folder
4. In the VS Code explorer tree, select, for example, `StyledText.tsx` file
5. Press "Enter" and rename to `styledText.tsx`
6. Notice that the tab with the filename remains to be `StyledText.tsx` and when searching for text within that file there are two search results, one for each file name.

**Comment by bpasero** [comment]
@yonifra I cannot reproduce:

![recording](https://user-images.githubusercontent.com/900690/92924180-cd6c6380-f438-11ea-9fce-e543d452109d.gif)

**Comment by yonifra** [comment]
![vscodebug](https://user-images.githubusercontent.com/726718/92924609-e9c0ce00-f441-11ea-8eb7-aa652165144d.gif)
This is very weird. are you sure you're on the same version as me? (the captured gif is without any extensions)
Maybe you have an extension that makes it work? ¯ \ _ (ツ) _ / ¯

**Comment by bpasero** [comment]
@yonifra my version:

```
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T17:39:53.251Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

I am running without any extensions and I think you indicated that you also tried that?

**Comment by yonifra** [comment]
Yes, I'm throwing ideas here, but maybe it's related to the font size / resolution of the monitor?

**Comment by bpasero** [comment]
@yonifra does it reproduce if:
* you do not have a second editor opened
* you configure `"typescript.updateImportsOnFileMove.enabled": "never"`

**Comment by yonifra** [comment]
Found the issue! It was Expo running in the background listening to changes and hot-reloading the React Native app. So it's not a VSC bug eventually.

**Comment by yonifra** [comment]
Thanks for your patience @bpasero and sorry for the hassle 👍
