### ISSUE TITLE
C# Arrow functions with string breaking color themes

### ISSUE THREAD

**Issue by mnsr** [Microsoft/vscode#10645]
VS Code: 1.4.0

This issue is similar to this one for TS: https://github.com/Microsoft/vscode/issues/3919

But in this case, it's happening in C# after using an arrow function AND the new string format syntax:

`protected string Name(string name) => $"My Name is {name}";`

![vscode-problem-csharp](https://cloud.githubusercontent.com/assets/4261458/17761004/fe29466c-6546-11e6-9108-5bf61b87b063.PNG)

if you remove the curly braces from the string, it's  fine:

`protected string Name(string name) => $"My Name is name";`

![vscode-problem-csharp-working](https://cloud.githubusercontent.com/assets/4261458/17761147/0c9ad02a-6548-11e6-9ca5-93bf3aced33e.PNG)

**Comment by alexandrudima** [comment]
Moved to Omnisharp/omnisharp-vscode#679
