### ISSUE TITLE
Vscode and Electron Chromium issue with blue lines Mac OS 10.15

### ISSUE THREAD

**Issue by nathanrpage97** [microsoft/vscode#106429]
- VSCode Version: 1.49.0
- OS Version: Mac OS Catalina 10.15.6

Steps to Reproduce:
This just occurred right after update to 1.49.0

1. Use VSCode on Mac OS Catalina

![image](https://user-images.githubusercontent.com/33010515/92819985-6a76c000-f397-11ea-96d5-7e59465800f5.png)

Does this issue occur when all extensions are disabled?: Yes

This seems to be a common bug that is plaguing Chromium. Currently the best way to resolve it is turning off Hardware Acceleration. How is this done in Vscode?
[Additional Reference](https://discussions.apple.com/thread/251248169)

**Comment by nathanrpage97** [comment]
Found how to do it. https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration.

**Comment by nathanrpage97** [comment]
Just to note for anyone else facing the issue: disabling gpu acceleration does work fully as a temporary fix.

**Comment by AustinShalit** [comment]
So not sure if this will help but... this only happens for me when viewing the landing page. Once I move to any other page, it behaves as expected.

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/3799260/95859670-f7ad8b80-0d2c-11eb-9489-3f25df389c99.png">

**Comment by deepak1556** [comment]
Upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1068170

**Comment by j0hnm4r5** [comment]
This issue just started happening to me on v1.50.1 (macOS 10.15.7).

Disabling GPU Acceleration via the Runtime Arguments JSON does not work.

![Screen Shot 2020-10-28 at 12 20 20 PM](https://user-images.githubusercontent.com/3644972/97465025-fdec5c00-1917-11eb-88dc-f64a0b6a4261.png)

**Comment by filipecabaco** [comment]
I uninstalled https://github.com/EmmanuelBeziat/vscode-great-icons and it fixed it

**Comment by LeBenLeBen** [comment]
@filipecabaco Thanks for the hint, for me it was Material icon theme.

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/112566749-ce456100-8d9c-11eb-91f0-3e7086455101.png)

**Comment by deepak1556** [comment]
Closing based on upstream comment https://bugs.chromium.org/p/chromium/issues/detail?id=1068170#c269
