### ISSUE TITLE
Task type "process" does not search PATH for the executable.

### ISSUE THREAD

**Issue by teo-tsirpanis** [microsoft/vscode#106423]
Issue Type: <b>Bug</b>

Consider this task:

``` json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "foo",
            "type": "process",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "command": "pwsh",
            "args": ["--help"]
        }
    ]
}
```

It used to work as expected (printing PowerShell's help), until version 1.49.0 where it fails with this error:

```
The terminal process failed to launch: Path to shell executable "C:\MyDirectory\pwsh" does not exist.
```

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (2.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
@teo-tsirpanis I'm still seeing this work correctly in 1.49. Can you open the developer tools (command Developer: Toggle Developer Tools) and in the developer tools console run `process.env.Path`. Does that path look correct to you? Does it include the path to pwsh?

**Comment by teo-tsirpanis** [comment]
Oh, PowerShell had been removed from PATH. It now works. Thank you.
