### ISSUE TITLE
[Request] Clipboard option to automatic replace backslashes with slashes and vice vera

### ISSUE THREAD

**Issue by TobiasSekan** [microsoft/vscode#106477]
Hello,

Sometime I ran into the problem that I have a file path with backslashes `\` but i need a path with slashes `/`

Example
Get: `\myFolder\myFile.php`
Need: `/myFolder/myFile.php`

So i think it would be nice when vscode has a clipboard option for this, like:

Option place: `Editor`
Option name: `Automatic replace (back-)slashes in Clipboard`
Possible Options:
* `Don't replace backslashes and slashes`
* `Replace all backslashes with slashes`
* `Replace all slashes with backslashes`
*  Maybe: `Filp slashes and backslashes`

What you think?
Thanks for the attention.

**Comment by IllusionMH** [comment]
Usual case for this is copying Relative path in VSCode and there is #56279 for this.
Does it solve your use case of there are other reasons to constantly change it.

TBH it looks more like action for selection (e.g. convert slashes selection), but not clipboard.

**Comment by TobiasSekan** [comment]
Hello,

https://marketplace.visualstudio.com/items?itemName=rssowl.copy-relative-path-posix
have solve the problem for the relative path, thanks

IMHO I think this should be a option or an action direct in vscode like:
* Copy Path (sub-menu)
  * Copy Path
  * Copy Relative Path
  * (Seperator)
  * Copy Path (Posix)
  * Copy Relative Path (Posix)
