### ISSUE TITLE
API: Add enablement to welcome view buttons

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#106487]
Below is a recording of a Control-R reload when no workspace is open and one non-builtin extension is contributing to to the Welcome view of Explorer.

![junk](https://user-images.githubusercontent.com/6726799/92923768-db69b680-f42f-11ea-8110-05c4e0187cd4.gif)

Observe how we start with Explorer's usual "NO FOLDER OPEN" view. Next my extension contributes its text and buttons. Finally the built-in git extension contributes text and a button. Since built-ins get higher priority the content from my extension jumps downward, perhaps while I'm reading it or trying to click one of its actions (link, button).

There's no progress indicator when the content is being fetched and assembled, and it's hard to know how long to wait before concluding that no other extensions are going to contribute.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Similarly on the Source Control view, it starts with a message saying "No source control providers registered" and stays this way long enough for me to worry that something is broken or missing. Eventually the contribution from the git extension arrives.

If a progress indicator isn't added, maybe at least the initial message could say something like "Please wait while we look for source control providers". Then if nothing contributes (e.g. the git extension has been disabled,) it could then display "No source control providers".

**Comment by joaomoreno** [comment]
This will be very hard to achieve. The problem here isn't actually the extension point, for which we could definitely add a progress indicator, but the activation of the git extension. That git section won't appear until the git extension is activated and all the potential repo locations have been probed... We simply can't add a progress indicator for that in the core unless we add some more API.

**Comment by joaomoreno** [comment]
> Similarly on the Source Control view, it starts with a message saying "No source control providers registered" and stays this way long enough for me to worry that something is broken or missing. Eventually the contribution from the git extension arrives.

On this, we could potentially add a `Git extension is activating...` message.

**Comment by gjsjohnmurray** [comment]
> On this, we could potentially add a `Git extension is activating...` message.

That might help.

**Comment by joaomoreno** [comment]
Closing this until we get actual user feedback that it's needed, sorry @gjsjohnmurray!
