### ISSUE TITLE
Add replaceWidgetVisible context to allow different keybindings for find vs. find-and-replace

### ISSUE THREAD

**Issue by krid** [microsoft/vscode#106445]
I frequently want to make use of cursor motion keys and copy-paste when interacting with the find-and-replace widget.  Conversely, when using find, I want almost any keystroke _except_ "find next" and "find previous" to immediately dismiss the widget and return me to editing mode.  I can currently have one or the other of these behaviors available; if there were separate contexts for `findWidgetVisible` and `replaceWidgetVisible` I could have everything my heart desires.

Example of proposed interaction with find-and-replace:
- Copy some text into the clipboard
- Open widget
- Paste text in `search` input
- Shift-backarrow to select part of the pasted text
- Tab to `replace` input
- Paste text
- backarrow to middle of text
- Type some stuff
- Start search-n-replace

See this bug in the Emacs keybindings extension for additional context: https://github.com/tuttieee/vscode-emacs-mcx/issues/360

**Comment by tuttieee** [comment]
Hi, I'm an author of the extension you referred to.
I think you can use `replaceInputFocussed` context for that purpose.
It's not published, but I found it from VSCode's source.

**Comment by rebornix** [comment]
Thanks @tuttieee !
