### ISSUE TITLE
market extensions issue

### ISSUE THREAD

**Issue by melik65** [microsoft/vscode#106485]
Issue Type: <b>Bug</b>

hi, I'm getting a marketplace issue. when I am want to go extensions marketplace I'am get a message is " we can not to connect marketpalce at this time, please try again later. "
 so my connection not problem but I can not install extensions.
can you help me? what can I do?

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz (2 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kieferrm** [comment]
@melik65 Do you still see the same issue?

**Comment by melik65** [comment]
@kieferrm yes sir

**Comment by joaomoreno** [comment]
Can you show me a screenshot of VS Code with the issue?

Are you inside a corporate network environment?

**Comment by melik65** [comment]
> Can you show me a screenshot of VS Code with the issue?
> 
> Are you inside a corporate network environment?

**Comment by melik65** [comment]
> > Can you show me a screenshot of VS Code with the issue?
> > Are you inside a corporate network environment?

![issue](https://user-images.githubusercontent.com/59912391/94682447-a3b6a600-032d-11eb-90c0-7f96bab19770.png)

**Comment by melik65** [comment]
I'm using normaly wifi connection

**Comment by hugodanielpereira** [comment]
I'm having the same issue after updating VS Code

**Comment by peaplesmart** [comment]
> I'm having the same issue after updating VS Code

**Comment by kmalaminstd** [comment]
I am also facing this issue.

**Comment by peaplesmart** [comment]
II found a solution to the problem I got about this, I restarted say on the
router and the problem was resolved. hope it helps ...

Pada tanggal Sab, 19 Des 2020 22.06, K.M. AL-AMIN <notifications@github.com>
menulis:

**Comment by joaomoreno** [comment]
@melik65 Is the issue still happening?

**Comment by melik65** [comment]
> Hey @joaomoreno, this issue might need further attention.
> 
> @melik65, you can help us out by closing this issue if the problem no longer exists, or adding more information.

I deleted and reinstalled windows. I solved that way

**Comment by melik65** [comment]
> Hey @joaomoreno, this issue might need further attention.
> 
> @melik65, you can help us out by closing this issue if the problem no longer exists, or adding more information.

I had to delete windows because of this error
