### ISSUE TITLE
minor issue on displaying the characters

### ISSUE THREAD

**Issue by landichokimpaolo** [microsoft/vscode#106454]
VSCode Version: 1.49.0
OS: Catalina 10.15.5 

**Steps to Reproduce:**
1. Create a CSS file
2. type the following:
ul li {
}

**Output:**
![Screen Shot 2020-09-11 at 2 53 32 PM](https://user-images.githubusercontent.com/25811639/92878426-ad3fa300-f43e-11ea-9dbe-2750fbafa4e4.png)

**Comment by rebornix** [comment]
@landichokimpaolo can you share what's the font you are using and also do you turn on Ligatures?

**Comment by rioj7** [comment]
I just upgraded to v1.49.3 and have this in all file types, it even happens in the Python OUTPUT pane (most recent call last).

If I disable all extensions it still happens.

Viewing the file in the hex editor does not show anything wrong.

I also tried in v1.50.0-insiders (2020-10-07) and there is does not happen.

**Comment by rioj7** [comment]
@landichokimpaolo Also look at #105672 and #106583 it has to do with `Render Whitespace` and using `Source Code Pro` and the new Electron engine used in v1.49.
