### ISSUE TITLE
Overall slow performance

### ISSUE THREAD

**Issue by Minkyu-Choi** [microsoft/vscode#106456]
Issue Type: <b>Performance Issue</b>

Especially, scrolling using mouse or keyboard is really laggy.
I've tested file under version control and not under version control. But they behaved almost same. 
Larger lines more laggy. Profile attached.

[CPU-20200911T161218.zip](https://github.com/microsoft/vscode/files/5207282/CPU-20200911T161218.zip)

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (9.62GB free)|
|Process Argv|--crash-reporter-id 515b2b29-a108-4178-9745-df82f9b97546 --crash-reporter-id 515b2b29-a108-4178-9745-df82f9b97546 --crash-reporter-id 515b2b29-a108-4178-9745-df82f9b97546|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   127	  9784	code main
    0	    86	  2568	   utility
    1	   100	  4160	   window (Issue Reporter)
    0	    79	  4804	   crashpad-handler
    0	    82	  8936	   utility
    0	   186	 14492	   window (● Untitled-1 - Visual Studio Code)
    0	   107	 18752	     extensionHost
    0	   105	 17812	   shared-process
    1	   141	 18180	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
amvim|aui|1.32.0
vscode-great-icons|emm|2.1.52
todo-tree|Gru|0.0.178
python|ms-|2020.8.108011
remote-wsl|ms-|0.44.5
trailing-spaces|sha|0.3.1
markdown-all-in-one|yzh|3.3.0

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
@Minkyu-Choi  From the CPU trace, I see that a lot of time is unaccounted and is spent in a section called "(program)", which is not helpful in pointing us to what is causing the slowness. Does this reproduce when you disable all extensions? (Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`).

Can you attempt to comment out your settings? Do you have a screen reader attached to the editor? Did you customize `editor.accessibilitySupport` ?

**Comment by Minkyu-Choi** [comment]
@alexdima I commented out my settings and reloaded window with extensions disabled. 
However, profile still showing most of the time consumed by (program). 
I'm not sure what the (program) is. How can I figure out?

**Comment by AndrewJRichardson** [comment]
Also seeing major slow down while scrolling with a keyboard since the new update.

**Comment by alexdima** [comment]
The CPU profile does not reveal anything. Also we did not change anything in the editor rendering in the past milestones. IIRC we have had some discussions about slowness around Electron 9, and that it might impact some older hardware.

I'm adding more people, maybe someone has an idea how to figure out what is the root cause.

**Comment by bpasero** [comment]
@Minkyu-Choi can you confirm that scrolling is fast with our previous `1.48.x` release: https://az764295.vo.msecnd.net/stable/a0479759d6e9ea56afa657e454193f72aef85bd0/VSCode-win32-x64-1.48.2.zip

**Comment by deepak1556** [comment]
`program` stacks indicate internal calls of v8. Since slowdown is happening inside v8 we need to look at some chrome traces for this. @Minkyu-Choi can you follow the steps to get the trace

1) Create trace.json somewhere on your disk with the following content:

```
{
 "result_file": "chrometrace.log",
 "trace_config": {
 "record_mode": "record-until-full",
 "included_categories": [
     "blink",
     "benchmark",
     "gpu",
     "cc",
     "toplevel",
     "viz",
     "v8",
     "disabled-by-default-v8.runtime",
     "disabled-by-default-v8.ic_stats",
     "disabled-by-default-v8.runtime_stats"
 ],
 "excluded_categories": ["*"]
 }
}
```

2) Start `code --trace-config-file <path-to>/trace.json`
3) Use the editor as normal and ensure the slowdown is seen
4) Quit the editor
5) Attach the generated chrometrace.log

**Comment by AndrewJRichardson** [comment]
Fresh install fiixed my slow scrolling 1.49 issue, guess something went wonky in the update.

**Comment by Minkyu-Choi** [comment]
> Fresh install fiixed my slow scrolling 1.49 issue, guess something went wonky in the update.

I had no luck with fresh install, even with insider version.

**Comment by Minkyu-Choi** [comment]
> `program` stacks indicate internal calls of v8. Since slowdown is happening inside v8 we need to look at some chrome traces for this. @Minkyu-Choi can you follow the steps to get the trace
> 
> 1. Create trace.json somewhere on your disk with the following content:
> 
> ```
> {
>  "result_file": "chrometrace.log",
>  "trace_config": {
>  "record_mode": "record-until-full",
>  "included_categories": [
>      "blink",
>      "benchmark",
>      "gpu",
>      "cc",
>      "toplevel",
>      "viz",
>      "v8",
>      "disabled-by-default-v8.runtime",
>      "disabled-by-default-v8.ic_stats",
>      "disabled-by-default-v8.runtime_stats"
>  ],
>  "excluded_categories": ["*"]
>  }
> }
> ```
> 
> 1. Start `code --trace-config-file <path-to>/trace.json`
> 2. Use the editor as normal and ensure the slowdown is seen
> 3. Quit the editor
> 4. Attach the generated chrometrace.log

I'll going to attach when I available company notebook

**Comment by Minkyu-Choi** [comment]
> @Minkyu-Choi can you confirm that scrolling is fast with our previous `1.48.x` release: https://az764295.vo.msecnd.net/stable/a0479759d6e9ea56afa657e454193f72aef85bd0/VSCode-win32-x64-1.48.2.zip

Yes, scrolling much better with 1.48.2 stable version

**Comment by Minkyu-Choi** [comment]
@bpasero 1.48.x version scrolls better than 1.49 version.

**Comment by Minkyu-Choi** [comment]
@deepak1556 chrometrace.log wasn't generated by using the command that you gave.

```
PS C:\Program Files\Microsoft VS Code> .\Code.exe --trace-config-file "C:\Program Files\Microsoft VS Code\trace.json"
PS C:\Program Files\Microsoft VS Code>
Warning: 'trace-config-file' is not in the list of known options, but still passed to Electron/Chromium.
[main 2020-09-15T01:59:24.373Z] update#setState idle
(node:17768) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:17768) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:16528) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:8020) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:8020) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[main 2020-09-15T01:59:54.378Z] update#setState checking for updates
[main 2020-09-15T01:59:55.388Z] update#setState idle
```

Anything wrong?

**Comment by deepak1556** [comment]
The config provided above will generate `chrometrace.log` file under the current directory where the executable is run, unless the application is run as elevated it can write the file under `Program Files`.  You can change the config with the path that is writable, for ex:

```
{
 "result_file": "C:\Users\<name>\AppData\Local\chrometrace.log",
 "trace_config": {
 "record_mode": "record-until-full",
 "included_categories": [
     "blink",
     "benchmark",
     "gpu",
     "cc",
     "toplevel",
     "viz",
     "v8",
     "disabled-by-default-v8.runtime",
     "disabled-by-default-v8.ic_stats",
     "disabled-by-default-v8.runtime_stats"
 ],
 "excluded_categories": ["*"]
 }
}
```

**Comment by Minkyu-Choi** [comment]
@deepak1556 I wasn't able to generate trace log. Maybe there's some restriction by company's security solution. 
Thank you for your suggestion.

**Comment by deepak1556** [comment]
Actually there is mistake with the flag, you need pass it like `--trace-config-file="C:\Program Files\Microsoft VS Code\trace.json"` . Also remove `"disabled-by-default-v8.ic_stats"` from the config, it currently crashes with it.

**Comment by Minkyu-Choi** [comment]
@deepak1556 Great, It works.

[chrometrace.001.zip](https://github.com/microsoft/vscode/files/5223246/chrometrace.001.zip)
[chrometrace.002.zip](https://github.com/microsoft/vscode/files/5223251/chrometrace.002.zip)
[chrometrace.003.zip](https://github.com/microsoft/vscode/files/5223257/chrometrace.003.zip)

I've changed file extension from number to zip due to github restriction. 
So, you should rename it to original one(e.g. chrometrace.001.zip to chrometrace.zip.001)
I've used 7zip.

**Comment by deepak1556** [comment]
Thanks! will get back further details from the trace tomorrow.

**Comment by Minkyu-Choi** [comment]
@deepak1556 any updates on this?

**Comment by deepak1556** [comment]
Sorry missed to respond, the recorded profile failed to load in `chrome://tracing` another bug of electron support of some tracing options. Can you record again with the following options

```
{
 "result_file": "C:\Users\<name>\AppData\Local\chrometrace.log",
 "trace_config": {
 "record_mode": "record-until-full",
 "included_categories": [
     "blink",
     "benchmark",
     "gpu",
     "cc",
     "toplevel",
     "viz",
     "v8",
     "disabled-by-default-v8.runtime"
 ],
 "excluded_categories": ["*"]
 }
}
```

One more can also provide the following trace,

* Download and install latest insiders https://code.visualstudio.com/insiders/
* Open `Windows Performance Recorder` from windows start menu
* Ensure `CPU usage` is checked under Resource Analysis
* Ensure Performance Scenario is `General` and Detail Level is `verbose`
* Click record
* Open the insiders and perform some scrolling that shows the slowdown
* Stop recording and save the profile
* Send the profile to Deepak.Mohan@microsoft.com since the trace will contain sensitive path informations

Also I am OOF till Monday, will check into this once I get to work. Thanks!

**Comment by Minkyu-Choi** [comment]
Trace file using new trace.json

[chrometrace.001.zip](https://github.com/microsoft/vscode/files/5243728/chrometrace.001.zip)
[chrometrace.002.zip](https://github.com/microsoft/vscode/files/5243733/chrometrace.002.zip)


I'll send WPR profile to your email. 
Thanks for your help.

**Comment by deepak1556** [comment]
@Minkyu-Choi thanks for the traces, I was able to narrow down some problematic areas, I will merge this issue to https://github.com/microsoft/vscode/issues/107016 for a broader conversation. Please follow that issue.
