### ISSUE TITLE
closing semicolon emmet expansion SCSS

### ISSUE THREAD

**Issue by kareljan** [Microsoft/vscode#1064]
When you expand an emmet expression in .SCSS files, a semicolon is not added at the end. I search everywhere, but I can not find this in settings. So I'm filing this as a bug.

**Comment by egamma** [comment]
Related to this issue https://github.com/sergeche/emmet-sublime/issues/70.

**Comment by egamma** [comment]
Since we do not really support sass, fixed by remapping the sass mode to the scss extension for emmet.

@aeschli renaming the sass mode to scss?

**Comment by kareljan** [comment]
Can I fix this myself somewhere in the current release, or do I have to wait for the following release?

**Comment by egamma** [comment]
The next update will be able by the end of this week. 

You can build from master and run the latest code. Refer to https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

**Comment by aeschli** [comment]
SASS is the name of the language. .sass and .scss are the two syntaxes. See http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syntax

**Comment by egamma** [comment]
@aeschli when verifying and Intellisense kicks in for the prefix, then use the 'Emmet: Expand abbreviation' command to use emmet to expand the prefix.
