### ISSUE TITLE
update August 2020 (version 1.49) and July 2020 (version 1.48) in Notebook UX not working

### ISSUE THREAD

**Issue by AbdelrahmanHamdy1996** [microsoft/vscode#106425]
Issue Type: <b>Feature Request</b>

the Notebook UX updates not working despite of i update to least version or not 

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:20:50.359Z)
OS version: Linux x64 5.4.0-47-generic

**Comment by rebornix** [comment]
Currently it's only supported in Insiders, https://code.visualstudio.com/insiders/

**Comment by AbdelrahmanHamdy1996** [comment]
Issue also exist vscode insider
