### ISSUE TITLE
Native Notebooks - Diffing behavior not consistent

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#106430]
Version: 1.49.0-insider (user setup)
Date: 2020-09-09T08:15:09.223Z
OS: Windows_NT x64 10.0.19041

## Steps to Reproduce:

1. Open any notebook where changes are being tracked
2. Insert a cell and track the diff (try multiple times)
 - Left side sometimes shows inserted empty and the right side shows the inserted cell (Picture A)
 - Left side sometimes does not show inserted empty and does cell by cell comparison instead (Picture B and C)

## Expected Behavior:
I would expect that whenever a cell is inserted and the difference is tracked, the left side has an inserted empty cell and leaves the relative position of all other cells below the same (Picture A). Otherwise every time a cell is inserted, all cells below will indicate a diff. 

### Picture A
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/19276747/92817139-1c53c380-f37b-11ea-9b5b-692228c25706.png)

### Picture B
![image](https://user-images.githubusercontent.com/19276747/92818794-f4fdf600-f37c-11ea-8478-2401596168cc.png)

### Picture C
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/19276747/92820577-f7614f80-f37e-11ea-9d7e-244f63977ba6.png)

**Comment by rebornix** [comment]
Nice catch @claudiaregio ! The diff algorithm running in the web worker are comparing the out-of-date documents, which lead to this inconsistency
