### ISSUE TITLE
Terminal picker's font / line-height has changed

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#106455]
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T17:39:53.251Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

---

1.48.2 (bot) vs 1.49 (top)

The old one is around same height as the panel names and more-or-less aligned with it. The new one looks larger than either panel names or the icons to its right.

![image](https://user-images.githubusercontent.com/4033249/92878330-95681f00-f43e-11ea-8e39-6ba35236f701.png)

**Comment by Tyriar** [comment]
Cc @cleidigh

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/103185
