### ISSUE TITLE
Release Notes tab not movable to the another vscode window

### ISSUE THREAD

**Issue by objque** [microsoft/vscode#106494]
- VSCode Version: 1.49.0
- Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
- Date: 2020-09-10T17:39:53.251Z (20 hrs ago)
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Open **Release Notes** tab and try to move release notes tab
![Screen Recording 2020-09-11 at 16 52 43](https://user-images.githubusercontent.com/7000585/92933946-90f83200-f44f-11ea-913e-051a6b5610fb.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Same root cause as #32818
