### ISSUE TITLE
VSCode 1.49.0 does not work when X-forwarded

### ISSUE THREAD

**Issue by aurelianito** [microsoft/vscode#106496]
- VSCode Version: 1.49.0
- OS Version: Lubuntu 20.04

```
$ code --version
1.49.0
e790b931385d72cf5669fcefc51cdf65990efa5d
x64
```

Steps to Reproduce:

1. Install vscode in lubuntu host (named b) using snap (version 1.49.0)
2. Connect to host b from another lubuntu host (a) via ssh forwarding X11 run `ssh -X user@b`
3. Run `code` in ssh session

Expected behavior (and what happens with version 1.48.2) is to open a new window in the (a) GUI with vscode

Actual behavior (with 1.49.0): shows a grey rectangle instead of the GUI. The title of the rectangle shows that it is vscode not rendering properly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aurelianito** [comment]
Seems related to https://github.com/electron/electron/issues/22775

Can be worked arround by setting env var `QT_X11_NO_MITSHM` to 1

**Comment by deepak1556** [comment]
Thanks for the report, this is already tracked under https://github.com/microsoft/vscode/issues/101069#issuecomment-662150152 . Closing as duplicate.
