### ISSUE TITLE
Window doesnt keep its size and location when closed and reopened

### ISSUE THREAD

**Issue by alexoconnell** [microsoft/vscode#106412]
Issue Type: <b>Bug</b>

Open VS Code
Resize the window and move the location
Close VS Code
reopen the application and it will open in its default location and size.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 4.15.0-117-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.83GB (0.83GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.2.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
vscode-jest-runner|fir|0.4.22
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
vsliveshare|ms-|1.0.2740
vetur|oct|0.27.2
LiveServer|rit|5.6.1
vscode-stylelint|sty|0.85.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by deepak1556** [comment]
Does this issue happen with latest stable `1.49.2` ?
