### ISSUE TITLE
Electron 9.x: macOS touchbar items disappear

### ISSUE THREAD

**Issue by e-tip** [microsoft/vscode#106495]
- VSCode Version: 1.49.0
- OS Version: Darwin x64 19.6.0

Hi all, until the last release i had my touchbar buttons and i use it when debugging my nodejs code.
With the today update instead, if i start the debug, and i'm on a js file, all the buttons disappears.
I've noticed that, when not in debugging mode, there's the emoticon button in the middle of the touchbar and the keyboard suggestion button is present.
Curiously if i select the settings tab ( or any other tab that are not js files, buttons are there correctly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Dog2puppy** [comment]
I've experienced this in Python files too.

**Comment by bpasero** [comment]
Can someone send a video how this looks like? This may be a Electron 9 regression.

**Comment by e-tip** [comment]
@bpasero i'll post a video tomorrow as soon as i arrive to my office, thanks

**Comment by bpasero** [comment]
One thing I do see on my MBP is a new icon in the touchbar which was not there before: emoji picker. I reported this as https://github.com/electron/electron/issues/25465

It may well be that the presence of this button makes the VSCode buttons drop.

To get more space on the touchbar I recommend to disable the option `Show Control Strip`

//cc @deepak1556 looks like the Electron 9 caused this.

**Comment by e-tip** [comment]
@bpasero here are the videos. i've noticed another difference between the versions on the buttons. Emoji picker and keyboard button on the right. 
[visual_studio_code.zip](https://github.com/microsoft/vscode/files/5223112/visual_studio_code.zip)

**Comment by e-tip** [comment]
@bpasero just to understand and get some extra knowledge on how high level software issue management works, is there a reason why my issue ( which has been opened before ) was marked as duplicate of an issue created later ? thanks if you would reply
