### ISSUE TITLE
Proxy auth dialog dissappear

### ISSUE THREAD

**Issue by shamarin** [microsoft/vscode#106452]
In version 1.49 x64 Windows 7 proxy auth dialog dissappear, so i cannot get access to internet.

**Comment by shamarin** [comment]
> 
> 
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Proxy Auth (#104726)](https://www.github.com/microsoft/vscode/issues/104726)

It's not the same, in 1.48 there was a bug with proxy that credentials couldn't be applied, but no auth popup window (dialog, modal window) is closing just after popup, so you can't even type auth credentials at all.

**Comment by shamarin** [comment]
The same issue https://github.com/microsoft/vscode/issues/106434

**Comment by deepak1556** [comment]
Sorry about this, lets track this under https://github.com/microsoft/vscode/issues/106434
