### ISSUE TITLE
error D:\vscode\node_modules\native-watchdog: Command failed.

### ISSUE THREAD

**Issue by z2184785** [microsoft/vscode#106467]
arning jsdom-no-contextify > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning mocha > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning mocha > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning mocha > jade > mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning mocha > to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
warning opn@6.0.0: The package has been renamed to `open`
warning sinon > formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
warning sinon > samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
warning sinon > formatio > samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam
warning webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > gulp-tsb@4.0.5" has incorrect peer dependency "typescript@^3.0.0".
[4/4] Building fresh packages...
[1/20] ⠄ keytar                                                                                                         [2/20] ⠄ native-is-elevated                                                                                             [3/20] ⠄ native-keymap                                                                                                  [4/20] ⠄ native-watchdog                                                                                                error D:\vscode\node_modules\native-watchdog: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\vscode\node_modules\native-watchdog
Output:
D:\vscode\node_modules\native-watchdog>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "node C:\Users\admin\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'D:\vscode\node_modules\native-watchdog\node C:\Users\admin\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)

**Comment by alexdima** [comment]
@z2184785 It looks like you have an installation problem. Maybe you did not install one of the required software https://github.com/Microsoft/vscode/wiki/How-to-Contribute#prerequisites
