### ISSUE TITLE
how to output the  error logs

### ISSUE THREAD

**Issue by WLswert** [Microsoft/vscode#10649]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

![image](https://cloud.githubusercontent.com/assets/12693684/17762472/86362e3e-6543-11e6-81f1-7c19c2b8fcad.png)
Hi, if I  want to see the error log  what can I do ?

**Comment by marvinhagemeister** [comment]
`Help -> Toggle Developer Tools`

**Comment by WLswert** [comment]
yes , I got it !
thank you !

**Comment by Hydrock** [comment]
My log:
