### ISSUE TITLE
Pass context of change to the formatter when formatting only modified lines

### ISSUE THREAD

**Issue by ilyakooo0** [microsoft/vscode#106478]
The latest (August 2020 version 1.49) update brought the option to only format modified lines on save: https://code.visualstudio.com/updates/v1_49#_only-format-modified-text.

This is a wonderful addition which helps minimize git diffs if the project wasn't formatted prior to a change.

However, some formatters use a pretty strict parser, which would not accept most lines out of context.

If I have a structure like this and I rename one of the fields the resulting changed lines passed to the formatter are not a valid structure in the language. A formatter, which uses strict parsing rules would fall over.
```diff
struct Foo {
  field1: Int
-  fild2: String
+  field2: String
}
```

Ormolu (https://github.com/tweag/ormolu) is an example of such a formatter -- it uses the parser that is actually used in the compiler. This means it is as strict as it can get.

It would be great to somehow detect enclosing language structures and pass them whole to the formatter.

# A proposed solution

An Idea might be to take the surrounding lines up until a line with only whitespace.

So a change like this:
```diff
struct Bar {
  otherField: Double
}

struct Foo {
  field1: Int
-  fild2: String
+  field2: String
}
```
 ... would pass the whole structure to the formatter, which is a valid language structure and a strict parser would be more likely to accept it:

```
struct Foo {
  field1: Int
  field2: String
}
```

**Comment by jrieken** [comment]
Not sure what you mean... Format modified doesn't send the diff-text but the "text as it is", e.g. the whole document, and the ranges that have been modified. It then asks the document _range_ formatter to format those ranges. See https://github.com/microsoft/vscode/blob/a45fa6ed50858306e5510742414887371d218a52/src/vs/vscode.d.ts#L3505

**Comment by ilyakooo0** [comment]
Oh, my mad

I am not familiar with the internals of VS Code and I assumed that it was not sending the whole document based on the errors from the formatter.

I think the extension I am using does not support ranges.

Thanks for the clarification, I will investigate.

---

For reference, I am using an extension I wrote myself, but I am not really familiar with the API: https://github.com/ilyakooo0/vs-code-ormolu

**Comment by jrieken** [comment]
> I am using an extension I wrote myself, but I am not really familiar with the API:

LOL - you should be familiar with it ;-) I see that the extension implements range formatter but I don't were the [passed range](https://github.com/ilyakooo0/vs-code-ormolu/blob/f01c8dba845510297c7c45c535793dbe7fa10e93/src/extension.ts#L12) is used. If you already have syntax tree based formatting it's pretty straight forward. Use the range to select the start and end node in the tree and format only those.

**Comment by jrieken** [comment]
Closing issue since this doesn't require code changes on our side.
