### ISSUE TITLE
Unable to run task containing docker-compose build

### ISSUE THREAD

**Issue by adamal** [microsoft/vscode#106492]
- VSCode Version: 
`code --version`
1.49.0
e790b931385d72cf5669fcefc51cdf65990efa5d
x64
- OS Version: MacOs 10.14.6

Steps to Reproduce:

1. Have `.vscode/tasks.json` containing a `docker-compose build` command.
2. Try to execute it.

--> 
```
docker.credentials.errors.InitializationError: docker-credential-desktop not installed or not available in PATH
[15603] Failed to execute script docker-compose
```

replacing `docker-compose build` with `echo $PATH` yields
```
/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
```

which is very different from what I get executing `echo $PATH` in a terminal (also vscode's built-in terminal)

Does this issue occur when all extensions are disabled?: 
Yes

**Comment by alexr00** [comment]
@adamal can you open the developer tools (command Developer: Toggle Developer Tools) and in the developer console run `process.env.path`? Does that path include docker's path?

**Comment by adamal** [comment]
`process.env.path` does include `usr/local/bin`. 
`which docker` gives `/usr/local/bin/docker` so yeah.

In case it's relevant: `docker-compose up` runs fine, if the image is already built.

**Comment by alexr00** [comment]
is `process.env.path` from the developer console the same as the result you get from your modified task with `echo $PATH`?

**Comment by adamal** [comment]
No, they were quite different.

**Comment by alexr00** [comment]
We do some work to try to make sure they are the same, so that's suspicious. How did you install VS Code? How did you launch it?
