### ISSUE TITLE
About mouse linkage

### ISSUE THREAD

**Issue by WULANREN8177** [microsoft/vscode#106437]
I have a logitech Master 3 mouse, which is a very easy-to-use office mouse. It can use logi option software to set various shortcut keys, but I use it to set vscode shortcut keys and find that they cannot be used, including the horizontal scrolling of the thumb wheel. , There are no switching tabs on the side buttons. So I am very disappointed.

**Comment by Sandstedt** [comment]
This problem has been up here before: #54024

And can confirm that (at least) the dedicated side scrolling wheel on my Logitech MX Master 3 doesn't not work in VS Code. It does work in Visual Studio 2019 though :)

**Comment by deepak1556** [comment]
Device input support comes from chromium, does the scroll work with chrome or edge ?

**Comment by WULANREN8177** [comment]
Horizontal scrolling in chrome and edge is available

**Comment by deepak1556** [comment]
Can you check if scrolling works with exploration builds https://az764295.vo.msecnd.net/exploration/3c1b4bacbef4ab788f72059f56ef53e9aa7923bc/VSCodeSetup-x64-1.52.0-exploration.exe

**Comment by Sandstedt** [comment]
@deepak1556 Sorry, but still doesn't work with the exploration build above. It works in Chromium browser. So must be something else.

The side-scroll does work in other overflow scenarios though, like the search input field in the Extension view.

Or no it doesn't. Not on a "cold start". Seems to be a bit sporadically. It start working after a while. Sometimes. So a really hard bug to find. It does seem to react directly when starting it, and while tabbing to it from another program. But within like 200ms it freezes again, and you can't scroll.

When it freezes in the main window, you cant scroll in the input fields in the sidebar either.

When it's frozen, I can use my laptops touchpad to sidescroll. So it's just related to the mouses horizontal scroll wheel.

**Comment by Sandstedt** [comment]
After some more digging, I found [this issue in electron](https://github.com/electron/electron/issues/20874), and specifically [this post](https://forum.vivaldi.net/topic/41537/logitech-smooth-scroll-extension-is-not-working-in-vivaldi/8). And apparently it's a Logitech Option problem.

So to temporarily fix it (if Logitech ever gets around to fix this), you can simple rename the VS Code .exe file to "chrome.exe", and it works.

**Comment by deepak1556** [comment]
Thanks for finding the relevant upstream issue, merging to https://github.com/microsoft/vscode/issues/56964
