### ISSUE TITLE
Update Go syntax

### ISSUE THREAD

**Issue by SteelPhase** [microsoft/vscode#106435]
[Better-go-syntax](https://github.com/jeff-hykin/better-go-syntax) has been updated. 

`extensions/go/syntaxes/go.tmLanguage.json` should be updated to reflect changes from upstream.

Can this just be done as a PR?

https://github.com/jeff-hykin/better-go-syntax/blob/master/export/generated.tmLanguage.json appears to be the location of updated version

**Comment by alexr00** [comment]
Thanks for pointing this out @SteelPhase I updated it a few weeks ago. Duplicate of https://github.com/microsoft/vscode/issues/106798
