### ISSUE TITLE
Add new notebook colors to documentation

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#106416]
Issue Type: <b>Bug</b>

`notebook.cellToolbarSeparator`
`notebook.symbolHighlightBackground`

are currently not listed in our theme color reference

VS Code version: Code - Insiders 1.49.0-insider (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-09T08:51:09.367Z)
OS version: Darwin x64 18.7.0

**Comment by roblourens** [comment]
I think @gregvanl generates this list somehow?

**Comment by RMacfarlane** [comment]
I don't think it's auto-generated, it's `api/references/theme-color.md` in the docs repo

**Comment by gregvanl** [comment]
There is a tool but I haven't used it. @mjbvz might know where it is and how to use it.

**Comment by misolori** [comment]
I didn't know about this, but [from the endgame template](https://github.com/microsoft/vscode/wiki/Endgame-Template):

> Run `scripts/test-documentation.sh|bat` and add file or fix issues if there are new colors that are not documented.

That's all I found regarding a tool.

**Comment by RMacfarlane** [comment]
yeah, I ran that to create these issues, but misread the directions as `add issues`. I just updated the docs https://github.com/microsoft/vscode-docs/commit/089b04ca69a4610a94ab96492780856060deb34d
