### ISSUE TITLE
Integrated terminal not working correctly with fish

### ISSUE THREAD

**Issue by probablykasper** [microsoft/vscode#106409]
Issue Type: <b>Bug</b>

I've got fish set as my login shell, but VS Code doesn't respect that and defaults `/bin/bash` bash instead. [The documentation](https://code.visualstudio.com/docs/editor/integrated-terminal#_changing-shell-for-tasks-and-debug) makes it seem like all I need to do is set `terminal.integrated.shell.osx` to `/usr/local/bin/fish`. Once I do that, it does run fish, but I get the following output when opening the integrated terminal:

```
source: Error encountered while sourcing file '/Users/kasper/.iterm2_shell_integration.bash':
source: No such file or directory
⏎                                                                               Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
```

That error and the huge spacing does not show up in the macOS Terminal or iTerm2.

If I then type `echo $SHELL`, it turns out $SHELL is set to `/bin/bash` even though it's running in `/usr/local/bin/fish`. In addition to that, my PATH is different from what it should be (it seems to have added the PATH from bash). I would assume these aren't the only things wrong.

The error above does go away if I set `terminal.integrated.env.osx` to `{ "SHELL": "/usr/local/bin/fish" }`, although the other issues persist.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|-psn_0_69649|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
stylus|Ala|0.0.4
svelte-intellisense|ard|0.7.1
markdown-preview-github-styles|bie|0.1.6
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
dart-code|Dar|3.14.1
flutter|Dar|3.14.1
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.13
vscode-pull-request-github|Git|0.19.0
sass-lint|gle|1.0.6
go|gol|0.16.2
beautify|Hoo|1.5.0
vscode-rust|kal|0.4.2
eml|lei|0.4.0
node-module-intellisense|lei|1.5.0
coffeelinter|lky|1.4.0
git-graph|mhu|1.25.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.17
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.5.0
python|ms-|2020.8.108011
debugger-for-chrome|msj|4.12.10
gradle-language|nac|0.2.3
color-highlight|nau|2.3.0
vetur|oct|0.27.2
vscode-versionlens|pfl|1.0.8
material-icon-theme|PKi|4.3.0
color-manager|roy|0.5.7
rust|rus|0.7.8
crates|ser|0.5.3
stylelint|shi|0.51.0
fish-vscode|sky|0.2.1
svelte-vscode|sve|101.13.0
sass-indented|syl|1.8.11
ayu|tea|0.20.1
vscodeintellicode|Vis|1.2.10
vscode-import-cost|wix|2.12.0
material-theme|zhu|3.8.7
vscode-open-in-github|ziy|1.3.6

(5 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you share you're settings.json file? Did you recently switch your shell and have you restarted since?

**Comment by jkjelsbak** [comment]
I was facing the same issue and realized that the Terminal.app was not set to the right shell.

Check in Terminal.app:

```
$ echo $SHELL
/bin/zsh
```
If the Terminal.app is not set to fish:

1. Ensure that /usr/local/bin/fish is in the /etc/shell file
   if not:
` echo “/usr/local/bin/fish” | sudo tee -a /etc/shells`

2. Make fish shell to default shell for Terminal
`chsh -s /usr/local/bin/fish`

3. Reboot

4. Back and check the Terminal.app is set correctly

Very best regards

Jens

**Comment by probablykasper** [comment]
@Tyriar Tried restarting and that did indeed fix it. Can't really see why restarting was needed for VS Code, but not Terminal or iTerm?

**Comment by Tyriar** [comment]
@probablykasper I think you probably had VS Code still running, the terminal's environment is based on VS Code's "main process" which only goes away when you cmd+q or restart.

**Comment by probablykasper** [comment]
@Tyriar I restarted VS Code multiple times to try to fix the issue
