### ISSUE TITLE
window.ShowInputBox returning undefined instead of empty string for Ok keypress

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode#10640]
- VSCode Version: 1.5.0-insider 
- OS Version: Mac OS X El Capitan

The window.ShowInputBox method was previously returning an empty string when the user hit OK, but in recent insider builds it now returns undefined for both Escape (cancel) and Enter (OK). This does not match the documented behavior and I cannot see a way to distinguish between user canceling or having default input chosen. This makes it very hard to write extensions that support default input values.

Note that the documentation states 

> The returned value will be undefined if the input box was canceled (e.g. pressing ESC). Otherwise the returned value will be the string typed by the user or an empty string if the user did not type anything but dismissed the input box with OK.

**Steps to Reproduce**:

The easiest repro is to install the [BowerVSCode](https://github.com/DonJayamanne/bowerVSCode) plugin from the marketplace, execute the "Bower" command from the F1 menu and choose the Init option. Then for the Name input hit Enter to use the default name

Expected:

- Workflow continues to the next step (Description) as the input box returns the empty string (and bower knows that this means use the default)

Actual:

- Workflow ends because when Enter is input, undefined is returned to the caller instead of the empty string. This is interpreted as cancellation per the API documentation

**Code Example**

1. Write an extension calling window.showInputBox - here is a
[BowerVSCode](https://github.com/DonJayamanne/bowerVSCode/blob/master/src/prompts/input.ts) example:

```
return window.showInputBox(this._options)
.then(result => {
	if (result === undefined) {
                // Hitting Enter gets to here, which is not expected
		throw new EscapeException();
	}

	if (result === '') {
                // Expected hitting Enter to mean code goes here
		result = 'my default value';
	}

	return result;
});
```

2. Execute the code to show the input box, and hit Enter. Notice that the result is undefined, when we would expect it to be ''.

**Comment by jrieken** [comment]
Thanks for the issue. The code around showInput and quickPick is a minefield where one 'fix' breaks another... Need to come up with tests that can press ESC and OK

**Comment by jrieken** [comment]
@bpasero Now that we have a command to close the quick picker can we also add one for accept? That would allow me to write tests against this

**Comment by bpasero** [comment]
@jrieken +1 for tests in this area. I added some more commands to play with:
* `workbench.action.closeQuickOpen` (we already had that)
* `workbench.action.acceptSelectedQuickOpenItem`
* `workbench.action.focusQuickOpen` (for people that want to quickly get back to the opened quick open input field in case it was not focussed)

**Comment by jrieken** [comment]
Reopening for writing tests

**Comment by jrieken** [comment]
habemus tests
