### ISSUE TITLE
any ext with activitybar list view stopped working after insider update v1.50.0

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#106499]
```
Version: 1.50.0-insider
Commit: bc38b0accb3c62180317c63dbe7323200977db0f
Date: 2020-09-11T12:26:02.664Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
```

Steps to Reproduce:

1. try with any of 
- https://github.com/alefragnani/vscode-project-manager
- https://github.com/Gruntfuggly/todo-tree
- https://github.com/usernamehw/vscode-snippets-view
- https://github.com/ctf0/vscode-file-shortcut
- https://github.com/zabel-xyz/local-history.git

2. error
```
Proposed API is only available when running out of dev or with the following command line switch: ...
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by akzaidi** [comment]
Seeing the same with the extension [`kortina.vscode-markdown-notes`](https://github.com/kortina/vscode-markdown-notes)

**Comment by alefragnani** [comment]
Also on my **Bookmarks** extension (https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks)

**Comment by alefragnani** [comment]
Interesting to see the [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension still works 🤔

**Comment by ctf0** [comment]
it seems issue is fixed
```
Version: 1.50.0-insider
Commit: cca20eba8974b1d6b6a9b71bf4e60a29c8f26648
Date: 2020-09-12T00:56:22.923Z
```

anyone else still having this ?

**Comment by joelday** [comment]
@ctf0 Looks like they just released with a revert.
