### ISSUE TITLE
Support AVIF encoded image previews

### ISSUE THREAD

**Issue by TimvdLippe** [microsoft/vscode#106415]
AVIF is a new image format that usually produces smaller images than other image compression formats (https://jakearchibald.com/2020/avif-has-landed/). VS Code allows me to show image previews for image formats such as JPG and PNG, but when I open an image that is encoded with AVIF it shows me the following error:

```
The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?
```

Opening it anyway shows binary output that is not human-readable.

Could you add support for AVIF image previews?

CC @jakearchibald

**Comment by mjbvz** [comment]
Note that this depends on Chromium 85+. Not something we can fix on the VS Code side besides picking up a new version of electron that includes that chromium version

**Comment by TimvdLippe** [comment]
It seems that that would happen when upgrading to Electron 10, which includes Chromium 85: https://www.electronjs.org/releases/stable?version=10

**Comment by TimvdLippe** [comment]
Am I correct to understand that #110759 should have resolved this issue?

**Comment by mjbvz** [comment]
Sample images for testing: https://github.com/link-u/avif-sample-images

**Comment by mjbvz** [comment]
Yes, thanks @TimvdLippe! Should be enabled in the next insiders build
