### ISSUE TITLE
Editor: formatOnSaveMode

### ISSUE THREAD

**Issue by lamboktulus1379** [microsoft/vscode#106450]
Issue Type: <b>Bug</b>

"editor.formatOnSaveMode": "modifications"

When I choose modifications mode, recently modifications not correctly formatted as file modifications mode.
The issue is in my css file, when add new line of style, and then I save, it formatted correctly,
But when I modified the existing style (the code before I installed Visual Studio Code Version 1.49.0), it not formatted.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|10.95GB (2.78GB free)|
|Process Argv|--crash-reporter-id a7e9480a-1d44-4dee-bccd-7a7258527883|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
php-intellisense|fel|2.3.14
beautify|Hoo|1.5.0
sftp|lix|1.12.9
vscode-docker|ms-|1.5.0
csharp|ms-|1.23.2
remote-wsl|ms-|0.44.5
js-debug-nightly|ms-|2020.9.1017
vsliveshare|ms-|1.0.2740
debugger-for-chrome|msj|4.12.10
debugger-for-edge|msj|1.0.15
vetur|oct|0.27.2

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by lamboktulus1379** [comment]
The issue is in my css file, when add new line of style, and then I save, it formatted correctly, 
But when I modified the existing style (the code before I installed Visual Studio Code Version 1.49.0), it not formatted.

**Comment by jrieken** [comment]
What formatter do you use for CSS? We don't ship one out of the box and I don't see one your extensions list

**Comment by lamboktulus1379** [comment]
Now, I found the issue, the issue cause by my the extensions...

I use  Beautify v1.5.0 for my CSS.

**Comment by jrieken** [comment]
Ok, then please forward this issue to the extension author. The formatter must support to format a range, e.g format selection, otherwise format modified doesn't work.
