### ISSUE TITLE
Source control view with dirty submodules does not respect .gitmodules config

### ISSUE THREAD

**Issue by Maldaris** [microsoft/vscode#106436]
- VSCode Version: 1.49
- OS Version: Windows 10.0.19041

Steps to Reproduce:

1. Create a project with one or more git submodules
2. add `ignore = dirty` to one or more submodule configuration entries.
3. Modify or add files to the submodule.

With large projects with multiple submodules, especially those where the development process may call for running builds on those submodules that their .gitignore doesn't cover, this makes it incredibly difficult to tell when/how many actual changes have been made to relevant submodules or the root repository.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
`ignore = dirty` only affects the parent repo. And for that VS Code seems to respect it correctly. But the repos, which happen to be submodules in that context, are indeed dirty. More details on https://stackoverflow.com/a/41598706

What would be your suggestion here?

**Comment by Maldaris** [comment]
For example: Given a `.gitmodules` file with the content:
```
[submodule "deps/zlib"]
	path = deps/zlib
	url = https://github.com/madler/zlib.git
	ignore = dirty
```

and the `deps/zlib` submodule properly initialized, but with files added/updated within the directory (ie from the build), the git integration should not display changes from that 

An example screenshot from the project which demonstrates the issue in practice: 
![image](https://user-images.githubusercontent.com/1953773/94706060-b7531400-030f-11eb-9c16-b3217373261b.png)

**Comment by joaomoreno** [comment]
Again `ignore = dirty` is only mean for the parent repo to ignore the fact that the submodule has dirty changes. I don't think it's a good idea to expand that into ignoring changes per repository.

**Comment by Maldaris** [comment]
Even just a flag for the submodule to not have its changes hidden would meet the need here. 

I guess I'm misinterpreting what you mean by ignoring changes per repository; it seems like case 2 in the SO link above covers, but I think what you're mentioning is in the context specifically of the nested submodule reporting changes itself?

```
Submodule has same commit checked out as recorded in parent project, working directory is dirty (has modified or untracked files). The parent project shows the submodule as having no changes (since ignore = dirty).
```
I guess I'm looking at the "parent" in this context being the editor having the root repository open, and not necessarily having the root _and its children_ open concurrently, and then aggregating those modified file counts/diffs.

**Comment by joaomoreno** [comment]
Does it help if you show the Source Control Repositories view (right click the `Source Control` view title and make that view visible) and just select the repository you're interested in?

**Comment by Maldaris** [comment]
![image](https://user-images.githubusercontent.com/1953773/95372512-a6734700-08a9-11eb-8d98-9f67318f32af.png)
So while it does filter file changes in the side panel, the badge on the actual source control button in the tray doesn't change in tandem.

This is starting to seem kind of minor at this point because viewing it in this mode does seem to deliver the broad strokes of what I'm looking for. It's just lacking the at-a-glance change count the badge provides. 

I'd be fine with closing this issue at this point.
