### ISSUE TITLE
Ability to hide some particular types of problems reported by an extension

### ISSUE THREAD

**Issue by SoniCoder** [microsoft/vscode#106459]
My extension (Erlang Linter Plugin) throws some problems because I'm doing something weird that it doesn't seems to like but actually compiles fine. Because of this all of my correct code shows a lot of red but I can't simply disable the extension because some types of problems are actually reported correctly. Please provide a feature to filter out certain kinds of problems.

Thanks

**Comment by sandy081** [comment]
Our general suggestion here is to let extension provide such feature for filtering problems so that they do not generate such problems to be performant. So please file the request against corresponding extension.
