### ISSUE TITLE
Doesn't work terminal

### ISSUE THREAD

**Issue by reagentJS** [microsoft/vscode#106424]
Issue Type: <b>Bug</b>

Hello.
After upgrade VSCode doesn't work terminal.
Also, why this soft was updating during I was working at the project?!

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.94GB (0.45GB free)|
|Process Argv|--crash-reporter-id a6453340-5a5c-4aac-a0ad-ff1a45aaadf4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-rename-tag|for|0.1.4
remote-wsl|ms-|0.44.5
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.9.0

(1 theme extensions excluded)

</details>

**Comment by Dogacel** [comment]
I think you mean WSL2. Yes I have troubles with WSL2 as well. It refuses connection to the host.

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal

**Comment by Dogacel** [comment]
The problem has been resolved after 15 minutes. I guess the vscode server didn't update on time but the IDE updated itself.

**Comment by reagentJS** [comment]
Thanks everyone, the problem has been resolved
