### ISSUE TITLE
Invalidate file marked "(deleted)" from code tree

### ISSUE THREAD

**Issue by urbanishimwe** [microsoft/vscode#106420]
I was going to raise this as **a bug** but I realized it may make sense that developers may have left this intentionally for some good reasons.

When a file is renamed(especially manually with git or in the shell), the open tab of that file will be kept open with the previous name and mark it as deleted. 
if you open the file with a new name, you will see some highlighted annoying errors saying **this thing is redeclared in this thing(block,...)**, which is caused by (maybe) VSCode treating open-in-another-tab delete file as a valid file in a code tree. my request is to change this behavior to something else

**why not just close the tab, if it is annoying?**
someone may want to keep that open for some reason(like a future reference), in case there is a plan to modify the new file

I suggest, to just invalidate that file **as a part of the code tree.**

**Comment by isidorn** [comment]
I believe this is designed behavior, however moving to @bpasero so he can decide whether to close this

**Comment by bpasero** [comment]
You can configure this via settings: `"workbench.editor.closeOnFileDelete": true`

**Comment by MCFrank16** [comment]
as @urbanishimwe mentioned

> someone may want to keep that open for some reason(like a future reference), in case there is a plan to modify the new file

I think it may not be a better idea to close the tab on delete.

the real issue is

> VSCode treating open-in-another-tab deleted file as a valid file in a code tree.

**Comment by bpasero** [comment]
@urbanishimwe what language was the file in and which extension did report the errors? It may well be that each extension has to deal with this individually.

**Comment by urbanishimwe** [comment]
@bpasero the language is Go and the extension might be gopls(language server) or some other tools configured automatically by VSCode.

**Comment by bpasero** [comment]
Ok then I suggest you report this to the Go extension.
