### ISSUE TITLE
Is it possible to update/refresh the CodeLens?

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#10648]
My plan is to display the results (as done [here](https://i-msdn.sec.s-msft.com/dynimg/IC814850.jpeg) in VS) of unittests against each method. Clicking the code lens would allow one to run (or re-run) that test making it necessary to update the code lens with the latest result.

As far as I can tell this isn't possible.

**Comment by jrieken** [comment]
We should add an optional event to the provider, ala `onDidChange` similar to have document providers allow [that](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1308).

**Comment by jrieken** [comment]
@DonJayamanne @eamodio @pflannery The first cut for this just landed and I'd like to collect feedback. Have a look at the changes or to code against the latest API do the following:

* open your extensions `package.json` file
* change the `engine.vscode` property to `*`
* run `npm run postinstall` (assuming you have the `vscode` module as dev-dependency)
* undo the engine-version change from step 2

**Comment by aeschli** [comment]
start verifying...

**Comment by DonJayamanne** [comment]
@Jakeii , @aeschli , thanks for the work guys. Missed this notification. Will look into this this weekend. 👍

**Comment by aeschli** [comment]
verified with a code sample. New API works.

**Comment by eamodio** [comment]
@jrieken sorry I haven't gotten a chance to look at this yet (been swamped) -- I will hopefully have some time this weekend.

**Comment by eamodio** [comment]
@jrieken looks great -- its now in the latest GitLens -- Thanks!
