### ISSUE TITLE
Could not read read Visual Code 1.49.0

### ISSUE THREAD

**Issue by phrakendark** [microsoft/vscode#106508]
Issue Type: <b>Bug</b>

today, when Update Visual these diferent errors appear: 11/09/2020

Could not read source map for file:///c:/gitForge/ForgeApp/node_modules/fecha/lib/fecha.umd.js: ENOENT: no such file or directory, open 'c:\gitForge\ForgeApp\node_modules\fecha\lib\fecha.umd.js.map'
Could not read source map for f....
Process exited with code 1
Uncaught Error: EPIPE: broken pipe, write

Itry to add these option but not working  this is a hell....i needdd your help

"resolveSourceMapLocations": [
    "${workspaceFolder}/**",
    "!**/node_modules/**"
]

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19631

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (6.38GB free)|
|Process Argv|--crash-reporter-id f69b2e01-6584-4b09-a494-0be960b176a5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.6.0
vscode-peacock|joh|3.8.0
vscode-azureappservice|ms-|0.18.0
remote-wsl|ms-|0.44.5
azure-account|ms-|0.9.3
docthis|oou|0.8.2
material-icon-theme|PKi|4.3.0
bunker|sld|1.1.6

(2 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
See here for the fix: https://github.com/microsoft/vscode/issues/106484#issuecomment-691202789

/duplicate

**Comment by phrakendark** [comment]
The error ocurrs whe this option was enabled in Settings Visual studio.

debug>Javascript:User preview Disable

**Comment by connor4312** [comment]
@phrakendark please let me know if the fix I linked _doesn't_ work. The "disable preview" option will go away in the next release.

**Comment by GrubbyHunter** [comment]
> The error ocurrs whe this option was enabled in Settings Visual studio.
> 
> debug>Javascript:User preview Disable
> 
> Please Close is Working for me!!

It's useful，thank you
