### ISSUE TITLE
Jupyter notebook files are not opening in version 1.49

### ISSUE THREAD

**Issue by hyderkh** [microsoft/vscode#106568]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Update to version 1.49
2. Open any .ipynb file OR
3. press Command+Shift+P and select Python: Create New Blank Jupyter Notebook

Does this issue occur when all extensions are disabled?: Yes
<img width="1181" alt="Screen Shot 2020-09-12 at 11 37 09 PM" src="https://user-images.githubusercontent.com/65697702/93009598-05ff6080-f551-11ea-8a11-ba19d658ac07.png">
<img width="1175" alt="Screen Shot 2020-09-12 at 11 37 40 PM" src="https://user-images.githubusercontent.com/65697702/93009604-0f88c880-f551-11ea-8d94-505312054d9f.png">

**Comment by kbalkcom** [comment]
I have the exact same problem.  Notebook file will open in Jupyter Notebook.  I don't have administrative privileges to install Insiders Build as suggested in other places.  Hope this is repaired soon!

**Comment by hyderkh** [comment]
I hope vscode team fixes it soon. unfortunately, I had to go back to the Jupyter lab again because of this issue.

**Comment by nilsholle** [comment]
Same problem here with Python 3.8.5 on Fedora 32.

**Comment by rebornix** [comment]
this should already be fixed now once you update the python extension.

**Comment by hyderkh** [comment]
Yes, now the notebooks are working fine. Thank you!
