### ISSUE TITLE
File -> Exit closes ALL instances of VS Code

### ISSUE THREAD

**Issue by timothyhoffmann** [microsoft/vscode#106501]
Issue Type: <b>Bug</b>

If I launch multiple instances of VS Code when I do File -> Exit in one of them all of the instances close themselves.  Please only exit the active instance.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (14.87GB free)|
|Process Argv|--crash-reporter-id e172f7a1-2d90-46a3-a2a7-faac0f71ec60|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp-to-typescript|adr|1.12.1
bracket-pair-colorizer-2|Coe|0.2.0
prettier-vscode|esb|5.6.0
debugger-for-chrome|msj|4.12.10
vs-asp-classic|wfe|0.0.4

</details>

**Comment by Tyriar** [comment]
This is by design, use Close Window/alt+f4 if you want to close one.

**Comment by timothyhoffmann** [comment]
Unlike other Windows applications separate instances of VS Code are apparently the same instance but with separate tabbed windows. e.g. If I'm in VS 2019 and click File -> Exit only that instance of VS 2019 exits and all other instances remain running.  If I'm running Outlook with multiple windows only the main Inbox has a File -> Exit, all the other windows just have a Close option. 
 It's just confusing to look at the Task Bar and see two instances of VS Code and two instances of VS 2019 but they behave very differently.
