### ISSUE TITLE
code --help hows wrong help for setting locale?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10655]
According to @dbaeumer to set a language on startup it is "`code --locale=<lang>`" but the help text proposes "`code --locale <lang>`".

I think our other commands follow the pattern of having the parameter followed with a whitespace so we should maybe be consistent here and change the locale command to take that into account.

I thought we would do the CLI parsing all in one place.

**Comment by dbaeumer** [comment]
Looked at the code and we use minimist now for args parsing. So it should be consistent.

**Comment by bpasero** [comment]
@Tyriar I cannot configure the locale though with space between.

**Comment by joaomoreno** [comment]
This code expects the equals `=` sign: https://github.com/Microsoft/vscode/blob/master/src/main.js#L46

**Comment by dbaeumer** [comment]
@joaomoreno thanks. Forgot about that part. So what should be the story. I can change the code to look for the next arg and use it unless it starts with a -

**Comment by bpasero** [comment]
@joaomoreno can we not make this work from minimist parsing?

**Comment by joaomoreno** [comment]
We should, yes. I can look at this.

**Comment by Tyriar** [comment]
@joaomoreno does https://github.com/Microsoft/vscode/commit/69df5034e46e98bfc8d5ae419a50556f3e9fc5d1 need to be reverted?

**Comment by joaomoreno** [comment]
It should although both options will works.

**Comment by Tyriar** [comment]
Done
