### ISSUE TITLE
The search tool's width is real-time change, It's shake and customer can not sometimes input correct word.

### ISSUE THREAD

**Issue by JimmyLonely** [Microsoft/vscode#10650]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.
Press hotkey "CTRL + F", Open search tool,
Search tool's width is: 411px
Screenshot:
![1](https://cloud.githubusercontent.com/assets/21092824/17763852/065e9c72-654e-11e6-82aa-a44d5c875a6b.PNG)

2.
Input 's',
Search tool's width is: 447px
Screehshot:
![2](https://cloud.githubusercontent.com/assets/21092824/17763861/18d23954-654e-11e6-925e-95480fbb6066.PNG)

3.
Input 'm',
Search tool's width is: 427px
Screenshot:
![3](https://cloud.githubusercontent.com/assets/21092824/17763869/2aefa3b0-654e-11e6-9e24-48270c6e82f7.PNG)

4.
Delete 'm',
Search tool's width is: 447px
Screenshot:
![4](https://cloud.githubusercontent.com/assets/21092824/17763872/3397b8e0-654e-11e6-9191-8985086e66fe.PNG)

Actual Result:
Search tool's width is real-time change, It's shake and customer can not sometimes input correct word.

Expect Result:
Search tool's width is fixed, customer can accurately locate char and input correct word

**Comment by ramamurthynagaraj** [comment]
Hi guys, submitted a PR for this issue. 
Fix increases the width of find widget for all locale.
Is that fine, do we have any other better approach?

**Comment by JimmyLonely** [comment]
Hi
Nagaraj,

 

Sorry,
I was busy with interview in Microsoft.SuZhou, yestoday.

About
this issue, I think your solution is fine, And I do not find a better solution
for it, now.

We
can change the issue state to ‘Resolved’ or ‘Close’, And I will continue focus
the issue in new build. 

 

Best
Regards,

Jimmy.LiDate: Fri, 19 Aug 2016 11:43:47 -0700

**Comment by JimmyLonely** [comment]
About this issue, I think your solution is fine, 
And I do not find a better solution for it, now.
We can change the issue state to ‘Resolved’ or ‘Close’, 
And I will continue focus the issue in new build.

**Comment by JimmyLonely** [comment]
It's the first time I use github.
Need I close the issue when we resolve it?

**Comment by ramamurthynagaraj** [comment]
Hi @JimmyLonely,
Usually one of the admins/core_committers of vscode will review & test whether the fix is fine or not. Only when it passes the review criteria, they will merge my pull request into the master branch and resolve/close the issue.
As a reporter of the issue, you don't have to do anything :)
