### ISSUE TITLE
Sidebar (treeview) don't focus selected file [1.49.0]

### ISSUE THREAD

**Issue by Daijobou** [microsoft/vscode#106584]
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Datum: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
Betriebssystem: Windows_NT x64 10.0.18363

When I click on a file in the sidebar, its not focus the current selected file. So its impossible to copy pre-selected text on-the-fly. You must first select the "tab".

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
I can not reproduce.

**Comment by Daijobou** [comment]
I have fresh installed vscode insider and its not working.

1. Open a folder with minimum two files in it
2. Select file1 in treeeview and select few lines
3. Select file2 in treeview, do nothing
4. Select file1 again and press STRG+C for copy selected text in file1

Result: The clipboard is empty because file1 was not focused.
If you want to copy the marked text you have to click on the tab before the file is focused.
