### ISSUE TITLE
terminal[git]: commit stopped working with optional args

### ISSUE THREAD

**Issue by AdrianSkar** [microsoft/vscode#106591]
- VSCode Version: 1.49.0
- OS Version: Windows_NT x64 10.0.19041

Steps to reproduce:

1. Have `.gitconfig` setup to use vscode to write git commit messages with the cursor in the first line (optional command line args):
`editor = code --wait -g $1:1` or
	`editor = \"C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe\" --wait -g $1:1`
2. Try to commit changes to a repo by using `git commit` command in the terminal

This worked properly before the last vscode update, whereas now  this error shows up in the terminal:
```
hint: Waiting for your editor to close the file... error: There was a problem with the editor '"C:\Users\USERNAME\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait -g $1:1'.
Please supply the message using either -m or -F option.
```

Everything works as expected without optional argument `-g $1:1` (the part that used to setup the cursor at line 1)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@AdrianSkar when you just invoke the editor directly, does that work? Type `C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe\" --wait -g $1:1` from the command line?

**Comment by AdrianSkar** [comment]
It shows a cursor allowing me to enter text as in terminal text editors like nano: 
![image](https://user-images.githubusercontent.com/12052430/98269575-2dd9d600-1f8e-11eb-9a83-377c189b4157.png)

**Comment by bpasero** [comment]
Sorry I do not understand why Code would not start?

**Comment by bpasero** [comment]
Ah, can you try just "code" instead of our exe directly?

**Comment by AdrianSkar** [comment]
The issue appeared when I tried to commit and only when specifying optional args but I'm not able to reproduce it right now so I guess further updates 'solved' this issue. 
Since I haven't seen anyone else with the same issue I guess this can be closed. 
@bpasero thank you for taking a look at this anyway.
