### ISSUE TITLE
Retrieve making nested copies of folder within folder

### ISSUE THREAD

**Issue by wescoturf** [microsoft/vscode#106515]
Issue Type: <b>Bug</b>

This issue started today. I don't see a cause. Nothing has changed. When I retrieve a folder from org, it pulls the folder into a into the css folder within the top folder I'm wanting to retrieve and update instead of just updating the files. I'm trying to retrieve theme files. It's adding another theme folder inside the css folder. Even if I try to just retrieve the styles.css, it makes a new top folder and puts it into the css folder. Then throws problems because of the nesting. I do not need an update. My coworker has the same setup and this is not happening to him.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.91GB free)|
|Process Argv|--file-uri file:///c%3A/Users/Robyn.Dombrowski/Documents/B2B%20Website/B2B.code-workspace --crash-reporter-id 50e5ef9b-0212-419a-88a2-8ad58c71b076|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.6.0
vscode-xml|red|0.13.0
salesforce-vscode-slds|sal|1.2.1
salesforcedx-vscode|sal|49.9.0
salesforcedx-vscode-apex|sal|49.9.0
salesforcedx-vscode-apex-debugger|sal|49.9.0
salesforcedx-vscode-apex-replay-debugger|sal|49.9.0
salesforcedx-vscode-core|sal|49.9.0
salesforcedx-vscode-lightning|sal|49.9.0
salesforcedx-vscode-lwc|sal|49.9.0
salesforcedx-vscode-visualforce|sal|49.9.0

</details>

**Comment by gjsjohnmurray** [comment]
The new version 1.49 was published on Thursday. Sounds like your Salesforce extensions have an issue.

/causedByExtension
