### ISSUE TITLE
Not sure if this is a bug or not

### ISSUE THREAD

**Issue by sweettyler** [microsoft/vscode#106530]
Issue Type: <b>Bug</b>

I think this is not a specific version related but I've observed the following for a very long time:

1) Open a file with vscode and place the cursor at where you want;
2) Hold the mouse left button first and then hold Alt key;
3) While holding the Alt key move the cursor right and down several characters;
4) You'll see a block is highlighted while the cursor is moving but the highlighting is off if the cursor stops moving and both the mouse button and Alt key is released. You'll see the selected block has a light gray background;
5) Then it seems I have to press the Alt key again to "activate" this block selection. And it seems the Alt key is the switch for "activating" or "de-activating" the block selection.

I have a few questions:
1) Anything wrong with my manupulation? or is there a better way to select a block?
2) Is "holding mouse left button first and then holding Alt ..." by design?
3) Is the "activate" and "de-activate" by design?
4) I tried to find the answer from the documents but found nothing.

Thank you.

VS Code version: Code - Insiders 1.50.0-insider (bc38b0accb3c62180317c63dbe7323200977db0f, 2020-09-11T12:27:36.137Z)
OS version: Linux x64 3.10.0-693.17.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (32 x 2100)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|187.41GB (82.21GB free)|
|Process Argv|--no-xshm --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.8.108011
cpptools|ms-|0.30.0-insiders4
material-icon-theme|PKi|4.3.0

</details>

**Comment by alexdima** [comment]
@sweettyler When using `"editor.multiCursorModifier": "ctrlCmd"`, the `alt` modifier becomes free and is used to create column selections:

So mouse click + drag will create regular selections, while mouse click + alt + drag will create column selections. Column selection is its own very popular feature, useful for editing tabular looking code:

![Kapture 2020-09-16 at 18 28 12](https://user-images.githubusercontent.com/5047891/93368530-65f64f80-f84e-11ea-88ed-5b05d8d6c4a2.gif)

**Comment by sweettyler** [comment]
@alexdima Thank you so much for the detailed answer and the video.

My last concern is how the "activate" and "deactivate" things? I mean after releasing both the alt key and the mouse button, pressing alt key again (and again) turn on and off the selection highlighting mode.

Sorry if I didn't speak my question clearly.

Regards.

**Comment by alexdima** [comment]
Yes, when `alt` is pressed the selection becomes a columnar selection, when `alt` is not pressed the selection becomes a regular selection, so `alt` functions like a toggle between the two modes.
