### ISSUE TITLE
Option to control how many repositories are visible in the Source Control section

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#106562]
Right now, we've got `scm.repositories.visible` to control how many repositories are visible in the _Source Control Repositories_ section. Would like an option to do that in _Source Control_ section as well. Although I've set `scm.repositories.visible: 1`, every time I open a file tracked in another repo, that repo emerges in the _Source Control_ section, like so:
![image](https://user-images.githubusercontent.com/28700378/93008184-7be0e780-f5a4-11ea-87ab-8543f7a5ad0c.png)

**Comment by gjsjohnmurray** [comment]
I think you can hide a repo you don't want to see. Look for a context menu to do this. IIRC there's an open issue with @joaomoreno to make those visibility states persist across reopening of a workspace.

**Comment by joaomoreno** [comment]
By selecting the repositories in the Source Control Repositories view, you control the number of visible repositories in the Source Control view.

**Comment by wenfangdu** [comment]
@joaomoreno How about a setting to control if all repositories should be selected or the just the first repo by default?

**Comment by joaomoreno** [comment]
Well, the idea here is to preserve visibility on reload, so a setting would be rather irrelevant.
