### ISSUE TITLE
Grey Window

### ISSUE THREAD

**Issue by pmqs** [microsoft/vscode#106556]
- VSCode Version: 1.49.0
- OS Version: Red Hat Enterprise Linux Server release 7.5 (Maipo)

Steps to Reproduce:

Launching vscode produces a completely grey window that looks like this.

![image](https://user-images.githubusercontent.com/2691108/93004425-b9128e80-f53e-11ea-9165-907ca78b5755.png)

I've tried uninstalling & reinstalling, but it makes no difference.

Also, installed code-insiders-1.50.0-1599872961.el7.x86_64 and still get the same grey screen

Does this issue occur when all extensions are disabled?: Yes

**Comment by pmqs** [comment]
Don't think https://github.com/microsoft/vscode/issues/94971 is the same issue.

**Comment by pmqs** [comment]
Should have mentioned, I didn't see this problem with 1.48

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/101069

please launch with `--no-xshm` as a temporary workaround.

**Comment by pmqs** [comment]
Thanks, workaround worked fine.
