### ISSUE TITLE
Unity opens new empty instances of VSCode when opening a script

### ISSUE THREAD

**Issue by originius** [microsoft/vscode#106514]
- VSCode Version: 1.49.0 (system setup)
- OS Version: Windows 10 (Windows_NT x64 10.0.19041)
- Unity Version: 2020.1.4f1

Steps to Reproduce:

1. Open a project in Unity which has C# scripts.
2. From the menu select: Asset > Open C# Project.
3. VSCode opens up but does not load the Unity project. So, open the project folder from VSCode manually.
4. In Unity, Project view, find a C# script file and doucle click on it.
5. It starts a new empty VSCode instance. What it should do is to activate the already open project's VSCode window and, and there open the C# script which was double clicked on.
 
- If I double click the C# file from File Explorer, it opens correctly in the already open VSCode project window.
- This is the only problem. Other Unity functionalities run correctly, like attaching a debugger.
- This issue was reported for different setups previously but the workarounds mentioned there do not work for me:

> [Unity keeps opening new instances of Microsoft Visual Studio code](https://github.com/microsoft/vscode/issues/76382)

> [Can't open a script on Unity](https://github.com/microsoft/vscode/issues/80884)

Does this issue occur when all extensions are disabled?: Yes

I also tried:
- Removing "JetBrains Rider Editor" package in Unity
- Looking for rogue VSCode instances in Task Manager and killing it
- Ending VSCode itself via Task Manager, and starting again
- Restarting Windows

**Comment by originius** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Cannot open unity script (#103172)](https://www.github.com/microsoft/vscode/issues/103172)
> * [Make Unity C# Better (#102550)](https://www.github.com/microsoft/vscode/issues/102550)
> * [Unity & Vscode Intellisense Not Working (#103141)](https://www.github.com/microsoft/vscode/issues/103141)
> * [codelens not working (#105257)](https://www.github.com/microsoft/vscode/issues/105257)

Yes, I know it was reported before. But it wasn't fixed, and it was closed.

**Comment by sbatten** [comment]
Can you verify this setting on your machine? window.openFilesInNewWindow

**Comment by originius** [comment]
> Can you verify this setting on your machine? window.openFilesInNewWindow

It is off.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by originius** [comment]
Ok, I tried Version: 1.50.0-insider (user setup). Nothing changed

Actually I realized that it is not even opening the C# project in the first place. It appeared to me as if it was opening it, but VSCode was actually just remembering the latest open files/folder. After I intentionally closed the folder in VScode, it stopped opening the project and now opening a new empty instance. Just like when I double click on a C# file. (correcting the issue description now)

**Comment by bpasero** [comment]
@originius it is hard to understand the issue without knowing what Unity does to open a file or folder in VSCode. If you can isolate the problem in VSCode by trying to reproduce from the command line (i.e. via `code <path>`) then I can look into it. Otherwise I suggest to follow up with Unity devs.

**Comment by originius** [comment]
I was also starting to suspect Unity. I will check on their side. Thanks.
