### ISSUE TITLE
can not open or install any extensions

### ISSUE THREAD

**Issue by ahmad-aboelnasr** [microsoft/vscode#106571]
Issue Type: <b>Bug</b>

I faced this problem directly after installing VS code editor. I can not install or even open any extension. I get an error message saying: "Unable to open 'Extension: Extension_Name': XHR failed."
I googled the problem and the solution I found did not work though, that is changing to google DNS.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (11.20GB free)|
|Process Argv|--crash-reporter-id c4a1f413-31c7-4673-8724-7b4502b33a6e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by ahmad-aboelnasr** [comment]
PLS tell anything except that the problem is with my network administrator. @sandy081

**Comment by sandy081** [comment]
please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
