### ISSUE TITLE
[tss plugin] What is configurePlugin actually do?

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/vscode#106567]
what is `configurePlugin(pluginId: string, configuration: ConfigurationField): void;` from `vscode.typescript-language-features` actually do?
like I asked in microsoft/vscode#106465

* https://github.com/CGQAQ/vscode_deno/blob/1d6de1df3d3e4205ce0f32e8bd03462c1cbfdf04/typescript-deno-plugin/src/plugin.ts#L611-L614
* [Push dts file into `getScriptFileNames` return value](https://github.com/CGQAQ/vscode_deno/blob/1d6de1df3d3e4205ce0f32e8bd03462c1cbfdf04/typescript-deno-plugin/src/plugin.ts#L207-L244)
* [`getProgram`? This one I don't know if use it in a right way](https://github.com/CGQAQ/vscode_deno/blob/1d6de1df3d3e4205ce0f32e8bd03462c1cbfdf04/typescript-deno-plugin/src/plugin.ts#L196-L205)

I've changed the flag, and tsserver.log show that it is worked, but the change still didn't apply at all

@mjbvz said in #106402 
> configurePlugin essentially just lets you post messages to a plugin from a vs code extension. Again the specifics depend on your use case but all the tools you need should be there to enable/disable the plugin's functionality based on some configuration

I tried do [this](https://github.com/CGQAQ/vscode_deno/blob/716c174e4a49bbf75ddd24cdbbf76573a1c11e9c/typescript-deno-plugin/src/plugin.ts#L591-L594), but didn't work

[code](https://github.com/CGQAQ/vscode_deno/blob/716c174e4a49bbf75ddd24cdbbf76573a1c11e9c/client/src/extension.ts#L170)
I also tried restart tsserver by run command `commands.executeCommand("typescript.restartTsServer");` and reload project by
`commands.executeCommand("typescript.reloadProjects");` after `configurePlugin`, didn't work either

**Comment by mjbvz** [comment]
What isn't work? If you have a minimal example I can take a look but I can't debug your complete extension/plugin.

As a reference, the tslint extension/plugin is using this api without issue:

- plugin: https://github.com/microsoft/typescript-tslint-plugin/blob/71de7a319d6a7ddde609bf542c16fcd7f109ce80/src/index.ts#L30

- extension: https://github.com/Microsoft/vscode-typescript-tslint-plugin//blob/501a71cde42eaa51006d2c4b73f3dcc444759209/src/index.ts#L55

**Comment by CGQAQ** [comment]
@mjbvz [this one](https://github.com/CGQAQ/vscode_deno/blob/1d6de1df3d3e4205ce0f32e8bd03462c1cbfdf04/typescript-deno-plugin/src/plugin.ts#L207-L244) doesn't work, you can see in the [tsserver.log](https://paste.ubuntu.com/p/jcMK7xYhKz/), the return value has changed, but types declared in the d.ts file didn't show up in IntelliSense

**Comment by mjbvz** [comment]
The server log shows that configure plugin is working then. Again `configurePlugin` just sends a json serializable object from VS Code to the extension. It does not have anything to do with d.ts loading. That's all up to your plugin

**Comment by CGQAQ** [comment]
> The server log shows that configure plugin is working (at least from the server's point of view).
> 
> Again `configurePlugin` just sends a json serializable object from VS Code to the extension. It does not have anything to do with d.ts loading. That's all up to your plugin

but this is back to the microsoft/TypeScript#40503 again, how to load it. I also tried restart tsserver by run command `commands.executeCommand("typescript.restartTsServer");` and reload project by
`commands.executeCommand("typescript.reloadProjects");` after configurePlugin, didn't work either. the return value of getScriptNames has changed! why tssever don't pick d.ts up?

**Comment by CGQAQ** [comment]
How the plugin tell tssever to change files in the project, I'm so confused

**Comment by mjbvz** [comment]
There is no api for that, your plugin needs to implement it.  I suggest you wait for someone on the TS team to reposed to https://github.com/microsoft/TypeScript/issues/40503

I'm closing this issue since there does not appear to be a bug. Please follow up in the TypeScript issue.

(also `typescript.restartTsServer` and `typescript.reloadProjects` are not apis for extension, they are commands a user can trigger  if they get into a bad state. Your extension/plugin should not need to use them)

**Comment by CGQAQ** [comment]
> There is no api for that, your plugin needs to implement it.
@mjbvz can you tell me which API should I use to implement it
