### ISSUE TITLE
Settings sync crashes on fedora 32

### ISSUE THREAD

**Issue by Stono** [microsoft/vscode#106588]
Hi, 
I've fresh installed vscode on Fedora 32 via snap and I'm attempting to sync my settings from my macbook.

When I click enable sync in the UI, vscode just shuts down.  I can't find any logs (please point me in the right direction of they are logged somewhere i'm missing!)

Thanks

**Comment by Stono** [comment]
Interestingly if i install vscode via the rpm, it's fine.  So this is a snap-install specific problem

**Comment by sandy081** [comment]
/duplicate

#100940
