### ISSUE TITLE
Multiline editing keyboard shortcuts not working

### ISSUE THREAD

**Issue by KJonesCAN** [microsoft/vscode#106529]
Issue Type: <b>Bug</b>

The multiline editing keyboard shortcuts CTRL+ALT+UP/DOWN is not working for me all of a sudden. I've tried uninstalling and reinstalling VS Code, but that hasn't helped.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (9.77GB free)|
|Process Argv|--crash-reporter-id 3c013fe6-b98b-44c2-99bd-6e8c87ac3cdb|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have Intel Graphics Command Center software? Most likely problem similar to #106256


Do you see these shortcuts if you follow steps in https://github.com/microsoft/vscode/issues/106256#issuecomment-688519096 or what new tool https://code.visualstudio.com/updates/v1_49#_improved-keybinding-diagnostics?

**Comment by KJonesCAN** [comment]
Hi Andrii,

I’ve traced the problem to the Nvidia Geforce Experience software that had it’s own key bindings. Once I disabled that the VS Code key bindings worked normally. Thanks for you help.


Kelly

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aeschli** [comment]
Thanks for reporting back. Closing the issue.
