### ISSUE TITLE
The breakpoints UI is really confusing

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#106559]
(i'm using vscode-cpptools over ssh to a linux box debugging with gdb)

For example:

- there's right-click menu items for "Enable/Disable All Breakpoints", but that seems to be different from whatever this button does:
![image](https://user-images.githubusercontent.com/1088194/93006326-a6349580-f50f-11ea-98a8-3c3debf4ccac.png) what's the difference between 'active' and 'enabled' ?
- there seem to be 3 different 'enable' / 'active' states:
  - the red circle, which can also be grey, or hollow. what do those even mean? it can also be white, for some reason.
  - the checkbox
  - the whole line can be greyed out, does this mean the code isn't loaded or the breakpoint is disabled, de-activated?
- shouldn't there be a right-click menu item in the breakpoint list to enable/disable a breakpoint. How about 'Activate All Breakpoints' ?
- if you click the 'Deactivate Breakpoints' button, then toggle the checkbox on one breakpoint (or add another breakpoint in the code), the whole lot seem to be re-activated, is this intentional? seems weird.

- if you click on a breakpoint in the breakpoints list) then the line is highlighted (and the circle turns white always, even if it was grey or hollow before, hiding the current state, why?). then if you use the cursor keys to move the selection to a different breakpoint, the original one stays selected (with its white circle), but hitting space toggles the checkbox of the other breakpoint. which one is supposed to be selected here? how many highlights do you need?
- there's a checkbox that can be toggled with the space bar, why no multi-select?

**Comment by isidorn** [comment]
THanks for the feedback however all of these are by design. We felt that makes the nicest experience.
We were inspired by chrome dev tools who also support this mechanism of enabling / disabling and deactivation on top.

The only things which we could support from the list is multi select, and for that I can leave this open as a feature request.
