### ISSUE TITLE
python create new blank jupyter notebook error

### ISSUE THREAD

**Issue by ycpss91255** [microsoft/vscode#106534]
- VSCode Version: 1.49
- OS Version: win10

Steps to Reproduce:

F1>Python: Create New Blenk Jupyter Notebook

無法開啟 'Untitled-3.ipynb': [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character。

![vscode python jupyter error](https://user-images.githubusercontent.com/54975526/92989819-b3e71c80-f509-11ea-8e7e-81383b824153.gif)

Does this issue occur when all extensions are disabled?: 
Requires dependent python

**Comment by harishmohan60** [comment]
I'm having the same problem
![image](https://user-images.githubusercontent.com/44602129/92990713-b01bc000-f532-11ea-8f2d-f3305db59c8d.png)

**Comment by harishmohan60** [comment]
Hi mate, 
I may have found a work around. Installed VS code- insiders and it works now. 
https://github.com/microsoft/vscode-python/issues/11865
![image](https://user-images.githubusercontent.com/44602129/92993715-f92a3f00-f547-11ea-9ee6-cc12e3ba4abf.png)

**Comment by Sricharan2402** [comment]
I'm having the same problem.
Additionally, the Jupyter Notebook editor is not loading - don't know if these two issues are related.

**Comment by Mithilsai** [comment]
Good day to you,
I am facing the same problem with creating or opening .ipnyb files(Jupyter). I tried these methods 
1. Reinstalling the Extension of Python.
2. Installing the VS code- insiders.

And the problem continues still now.
Kindly please resolve this issue as soon as possible.
Thank you in advance

**Comment by jasonhuayen91** [comment]
same here. I spent the whole day trying to solve this problem, but still got nowhere.

Unable to open 'Untitled-1.ipynb': [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character.

**Comment by guotree** [comment]
I have the same problem too

**Comment by guotree** [comment]
> same here. I spent the whole day trying to solve this problem, but still got nowhere.
> 
> Unable to open 'Untitled-1.ipynb': [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character.

you're not alone

**Comment by giri-v** [comment]
Looks like we've got a live one. Also no success trying to resolve...

**Comment by harishmohan60** [comment]
I managed to resolve this error by following these steps:
1.  Uninstall vscode completely - https://www.logicbig.com/how-to/visual-studio-code/remove-vs-code-completely.html (Restart the machine)
2. Install vscode Insiders user- https://code.visualstudio.com/insiders/
3. Install extensions - Python (Microsoft),  Remote-WSL
4. select base environment 
![image](https://user-images.githubusercontent.com/44602129/93003442-d6714800-f592-11ea-9dd1-1947957b7159.png)
5. Open a folder and create file and name it "whatever.ipynb" that should automatically ask to you install more dependencies follow through the errors and select the local kernel

This took me a whole day too, but its working now. Hopefully this works too. 
![image](https://user-images.githubusercontent.com/44602129/93003526-93fc3b00-f593-11ea-92cd-2ef9bafeb449.png)

**Comment by Mithilsai** [comment]
Good day to you,
My dear colearners, The method refered by Mr. _**harishmohan60**_ works perfectly.
I would like to thank him and every one else.
Thank you, Happy learning

**Comment by guotree** [comment]
> 5\. Open a folder and create file and name it "whatever.ipynb" that should automatically ask to you install more dependencies follow through the errors and select the local kernel

Followed every step of you, but it seems no work

**Comment by Rajwantmishra** [comment]
I download only insider (https://code.visualstudio.com/insiders/) and python extension, but now I have a different VS code (VS Insider ) that works.

**Comment by jasonhuayen91** [comment]
> > 5. Open a folder and create file and name it "whatever.ipynb" that should automatically ask to you install more dependencies follow through the errors and select the local kernel
> 
> Followed every step of you, but it seems no work

make sure delete code and .vscode, it works for me here. Good luck

**Comment by aayushadeshara333** [comment]
Followed each and every step, still not working

**Comment by BCusack** [comment]
Yep, Insider did the trick.

**Comment by cslongo** [comment]
same problem here since this morning: I would try to use the insider, but I believe this is not the end-solution
Might it be a conflict with the latest VS-Code Update 
![image](https://user-images.githubusercontent.com/25841945/93073579-68587e00-f683-11ea-947c-5a9ee9aa8637.png)

Extension version: 2020.8.108011
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Mithilsai** [comment]
Good day to you,
My dear co-learners, The method refered by Mr. _**harishmohan60**_ works perfectly for some time and after reloading the window for the other extensions. It failed again . Kindly suggest any suggestions.
Thank you, Happy learning

**Comment by jarix** [comment]
I'm having the same issue trying to create a new jupyter notebook.   
![image](https://user-images.githubusercontent.com/4304923/93108246-6c76a280-f667-11ea-9e48-b4cb55255fad.png)
Trying to open a notebook just hangs.  Same behavior with both VSCode 1.48.2 and 1.49.0

**Comment by santhoshr20** [comment]
Facing same issue
Unable to open 'Untitled-1.ipynb': [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character.

**Comment by santhoshr20** [comment]
> * VSCode Version: 1.49
> * OS Version: win10
> 
> Steps to Reproduce:
> 
> F1>Python: Create New Blenk Jupyter Notebook
> 
> 無法開啟 'Untitled-3.ipynb': [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character。
> 
> ![vscode python jupyter error](https://user-images.githubusercontent.com/54975526/92989819-b3e71c80-f509-11ea-8e7e-81383b824153.gif)
> 
> Does this issue occur when all extensions are disabled?:
> Requires dependent python

please fix this..ASAP

**Comment by joe-letourneau** [comment]
I too have this issue. Installing vscode insider is not an option for me, I develop in multiple languages, connected to multiple Salesforce orgs, and github repos.

I really need this fixed ASAP

**Comment by cslongo** [comment]
Hi all,

it seems that, in my case the problem has been resolved on its own.
![image](https://user-images.githubusercontent.com/25841945/93171260-081c1780-f729-11ea-86ae-2f0048ad7b35.png)

Try to open a folder with VS and run a python script (whatever): while running, VS has asked me to restart itself two times because "some extensions have been modified on the disk".

After the two applications restart, I could run a jupyter notebook inside of it: its a real interesting bug

![image](https://user-images.githubusercontent.com/25841945/93171559-9db7a700-f729-11ea-9cf4-a9dc129081c4.png)

**Comment by matozqui** [comment]
Same as cslongo. Create a sample.ipynb, open VSC - Insiders from raw several times. It took like three restarts of VSC - Insiders and finally kernel worked and Jupyter notebook shows results.

**Comment by hannurie** [comment]
Same as cslongo. It definitely works!!!

Thank you very much for your advice.

> Hi all,
> 
> it seems that, in my case, the problem has been resolved on its own.
> ![image](https://user-images.githubusercontent.com/25841945/93171260-081c1780-f729-11ea-86ae-2f0048ad7b35.png)
> 
> Try to open a folder with VS and run a python script (whatever): while running, VS has asked me to restart itself two times because "some extensions have been modified on the disk".
> 
> After the two applications restart, I could run a jupyter notebook inside of it: its a real interesting bug
> 
> ![image](https://user-images.githubusercontent.com/25841945/93171559-9db7a700-f729-11ea-9cf4-a9dc129081c4.png)

**Comment by aayushadeshara333** [comment]
I really worked, Thanks cslongo!

**Comment by aayushadeshara333** [comment]
It really worked, thanks cslongo!

**Comment by santhoshr20** [comment]
> Hi all,
> 
> it seems that, in my case, the problem has been resolved on its own.
> ![image](https://user-images.githubusercontent.com/25841945/93171260-081c1780-f729-11ea-86ae-2f0048ad7b35.png)
> 
> Try to open a folder with VS and run a python script (whatever): while running, VS has asked me to restart itself two times because "some extensions have been modified on the disk".
> 
> After the two applications restart, I could run a jupyter notebook inside of it: its a real interesting bug
> 
> ![image](https://user-images.githubusercontent.com/25841945/93171559-9db7a700-f729-11ea-9cf4-a9dc129081c4.png)

Tried ...but still facing the same issue

**Comment by cslongo** [comment]
> > Hi all,
> > it seems that, in my case, the problem has been resolved on its own.
> > ![image](https://user-images.githubusercontent.com/25841945/93171260-081c1780-f729-11ea-86ae-2f0048ad7b35.png)
> > Try to open a folder with VS and run a python script (whatever): while running, VS has asked me to restart itself two times because "some extensions have been modified on the disk".
> > After the two applications restart, I could run a jupyter notebook inside of it: its a real interesting bug
> > ![image](https://user-images.githubusercontent.com/25841945/93171559-9db7a700-f729-11ea-9cf4-a9dc129081c4.png)
> 
> Tried ...but still facing the same issue

Try to run a .py file and then the notebook. 
I'm using the default version of VS.

**Comment by santhoshr20** [comment]
After trying cslongo's , my problem  solved by itself, Now I can able to work with Jupyter notebook

> > > Hi all,
> > > it seems that, in my case, the problem has been resolved on its own.
> > > ![image](https://user-images.githubusercontent.com/25841945/93171260-081c1780-f729-11ea-86ae-2f0048ad7b35.png)
> > > Try to open a folder with VS and run a python script (whatever): while running, VS has asked me to restart itself two times because "some extensions have been modified on the disk".
> > > After the two applications restart, I could run a jupyter notebook inside of it: its a real interesting bug
> > > ![image](https://user-images.githubusercontent.com/25841945/93171559-9db7a700-f729-11ea-9cf4-a9dc129081c4.png)
> > 
> > 
> > Tried ...but still facing the same issue
> 
> Try to run a .py file and then the notebook.
> I'm using the default version of VS.

After trying cslongo's , my problem  solved by itself, Now I can able to work with Jupyter notebook
Thank You
