### ISSUE TITLE
VS Code doesn't load any jupyter notebook file

### ISSUE THREAD

**Issue by HenriqueAJNB** [microsoft/vscode#106526]
- VSCode Version: 1.49 x64
- OS Version: Ubuntu 20.04
- Python: 3.8.3
- conda 4.8.3 

![Peek 2020-09-11 22-04](https://user-images.githubusercontent.com/54143210/92983711-89e71900-f47b-11ea-9854-9c5d812de13a.gif)

Steps to Reproduce:

1. Open VS Code
2. Open any `.ipynb` file

Does this issue occur when all extensions are disabled?: Yes

**Comment by cost3rllo** [comment]
I'm having the same problem, it cannot open new jupyter notebook either. Always having error: "Unable to open 'Untitled-1.ipynb': [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character."

**Comment by pwlm** [comment]
I'm having the same error. The blue bar just runs forever.
win 10
Python 3.7.7

**Comment by offyoutrans** [comment]
Reproduced on my machine, it's rlly existing bug

**Comment by offyoutrans** [comment]
still the same after full jupyter reinstalling

**Comment by offyoutrans** [comment]
not sure if it is solution but i imported jupyter notebook and it contain appears (with different interface though)

**Comment by gabmartini** [comment]
Same here but with Fedora 32. 
Version of vscode: 1.49

**Comment by ParthChudasama** [comment]
Do we have a fix for this, facing the same issue. Tried both insiders build and v1.49
MacOS 10.15.6

**Comment by rebornix** [comment]
This is already fixed by the latest Python extension.
