### ISSUE TITLE
Unimplemented  console.clear()？

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode#10652]
- VSCode Version: 1.4
- OS Version:

Steps to Reproduce:

1. when I debug "runtimeExecutable": "${execPath}"
2. JS file inside the code like this ：console.clear();
3. Debug Console Panel is Unimplemented  console.clear()

**Comment by mrmlnc** [comment]
@weinand,

This is non-standard method. The `clear` method available in [Chrome DevTools](https://developers.google.com/web/tools/chrome-devtools/debug/console/console-reference#clear) and [Firefox Web API Console](https://developer.mozilla.org/en-US/docs/Web/API/Console).

**Comment by weinand** [comment]
@ydcoming what debugger are you using in VS Code?

VS Code's only builtin debugger is node-debug. Its Debug Console only supports node API.
Using Chrome DevTools API or Firefox Web API doesn't make any sense.

If you are using a different debugger, please create an issue in the corresponding repository.

**Comment by ydcoming** [comment]
what is the Clear Console action Shortcut key？

**Comment by weinand** [comment]
@ydcoming there is none.

@isidorn I've tried to assign a keyboard shortcut to "workbench.debug.panel.action.clearReplAction" but this doesn't work because the action's id is not known. Do you know what the problem is?

**Comment by ydcoming** [comment]
I made some modifications to the vscode .I would like to make a installer? for help!!!!

**Comment by weinand** [comment]
@ydcoming please create a new issue for your question since it has nothing to do with the problem discussed in this item.

**Comment by ydcoming** [comment]
ok 3ks

**Comment by isidorn** [comment]
As far as I see this is a dup of #10691
