### ISSUE TITLE
Drop down menu item selection jumping and flickering. Linux

### ISSUE THREAD

**Issue by s-bespalov** [microsoft/vscode#106592]
Drop down menu item selection jumping and flickering on mouse hover over menu items.
Recording:
[https://1drv.ms/u/s!AqkG7zvs1AtZxxi-cEpwQfCZy4gb](https://1drv.ms/u/s!AqkG7zvs1AtZxxi-cEpwQfCZy4gb)

VSCode Version: 
 - Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:20:50.359Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.7-200.fc32.x86_64

 - Version: 1.50.0-insider
Commit: cca20eba8974b1d6b6a9b71bf4e60a29c8f26648
Date: 2020-09-12T00:58:03.476Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.7-200.fc32.x86_64

OS Version: 
 - Operating System: Fedora 32
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.8.7-200.fc32.x86_64
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-8700 CPU @ 3.20GHz
Memory: 15.6 GiB of RAM

Steps to Reproduce:

1. Open VSCode
2. Hover mouse cursor over drop down menu

Does this issue occur when all extensions are disabled?: Yes

**Comment by kenguie** [comment]
Does this extend to the flickering i see when i scroll around in general? When I scroll anything up and down, i see the VS code screen flickering and it's pretty annoying.

**Comment by deepak1556** [comment]
@kenguie please open a new issue to help triage the issue you are facing, it is not the same as this issue. Thanks!

**Comment by deepak1556** [comment]
@s-bespalov can you check if the issue is present with our [exploration builds](https://az764295.vo.msecnd.net/exploration/b09dd7858771abf03f0abad6f5a5704839c13dd7/code-exploration-1.52.0-1604559462.el7.x86_64.rpm) that has newer runtime.
