### ISSUE TITLE
Latest version of VS Code breaks extensions

### ISSUE THREAD

**Issue by kufii** [microsoft/vscode#106504]
- VSCode Version: 1.49.0
- OS Version: macOS 10.15.6

with the latest release of vs code my extensions have broke. when trying to run them I get the error Error: Cannot find module 'vscode'. This even happens with a brand new extension generated with `yo code`

**Comment by Gizmodo** [comment]
I have got PlatformIO break.
[platformio.platformio-ide]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api platformio.platformio-ide

**Comment by kufii** [comment]
@alefragnani are you sure this is a duplicate? I'm not getting the same error and also not using the ActivityBar API
