### ISSUE TITLE
Extension API : platform identification

### ISSUE THREAD

**Issue by pmahend1** [microsoft/vscode#106525]
We can set different keybindings for different OS platforms in keybindings which take input as `isLinux` `isMac` `isWindows` `isWeb`  , the corresponding code lies in [vscode/src/vs/base/common/platform.ts](https://github.com/microsoft/vscode/blob/master/src/vs/base/common/platform.ts)

But doesnt seem to be exposed through vscode module.

```ts
import * as vscode from 'vscode'
```

How can I get OS platform at runtime within my extension?

**Comment by jrieken** [comment]
In the API, there is `vscode.env.uiKind` which wtll tell you if the UI is a web browser or the desktop app. Tho, I am not sure what you are trying to achieve. Do you want a context key value or an API value?

**Comment by pmahend1** [comment]
@jrieken That's way to different. I want to use platform.ts to get Operating System(OS). Because some of my extension code is platform dependent, say on Linux I want to call some other code.
I figured out I can use `node.process` for now,but I am still wondering the purpose of Platform.ts which has additional code and want to use that.It's not exposed though.

**Comment by jrieken** [comment]
> additional code and want to use that

What part of it do you want to use? Why is `node.process` not good for you?

**Comment by pmahend1** [comment]
For example `IsWeb`

**Comment by jrieken** [comment]
>  Because some of my extension code is platform dependent, say on Linux I want to call some other code.

You will not on run the web if your code is platform dependent, the UI might be. That's why I am confused here, e.g it seems that you will always run in a nodejs-context, not in a webworker context (see https://github.com/microsoft/vscode/issues/104436)

**Comment by pmahend1** [comment]
So what is `isWeb` in the platform.ts for?

**Comment by jrieken** [comment]
Internally we have code that does run in web or electron, but that's only UI not the extension host (process/worker)

**Comment by jrieken** [comment]
Closing as we have #104436 and `vscode.env.uiKind`

**Comment by pmahend1** [comment]
@jrieken in the keybindings documentation [`isWeb` is described](https://code.visualstudio.com/docs/getstarted/keybindings) as 

isWeb | True when accessing the editor from the Web

If its internal only when is it part of keybinding context ?  Since keybindings can take any of the platform.ts platform values it makes no sense to have Platform.ts linked to keybindings when. Why not just use `vscode.env.uiKind`?
