### ISSUE TITLE
Cannot Open a freshly downloaded copy of Vscode on Mac 10.15.6

### ISSUE THREAD

**Issue by thehigherlife** [microsoft/vscode#106557]
- VSCode Version: Aug 2020
- OS Version: 10.15.6

Steps to Reproduce:

1. Download new copy of vscode from web.
2.Try to open.
3. get this dialog:

The application “Visual Studio Code” can’t be opened.

Right click open does the same thing.  opening from command line gives this error:

open -a /Applications/Visual\ Studio\ Code.app 
LSOpenURLsWithRole() failed for the application /Applications/Visual Studio Code.app with error -10810.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deepak1556** [comment]
Unable to repro this issue, can you attach the application zip you downloaded. Also where did you download from ?

Did you try downloading again to avoid the issue of corrupted downloads ?

**Comment by thehigherlife** [comment]
I downloaded multiple times from this page.

https://code.visualstudio.com/docs/?dv=osx here is the actual dl link: https://az764295.vo.msecnd.net/stable/e790b931385d72cf5669fcefc51cdf65990efa5d/VSCode-darwin-stable.zip

sha of zip: shasum -a 256 VSCode-darwin-stable\(3\).zip 
6f75308c10ef92485e8deb20e212fde7fa404886268652fc91ebba929aab80ea  VSCode-darwin-stable(3).zip

sha of app:

shasum -a 256 Visual\ Studio\ Code.app/Contents/MacOS/Electron 
7f3d3ddf446acec3a142c9985288c78b1591260390a3294e2c2a4821229e6426  Visual Studio Code.app/Contents/MacOS/Electron

**Comment by deepak1556** [comment]
Thanks for the details, I am able to open the application from that link. 

`open -a ~/Downloads/Visual\ Studio\ Code.app/ --args --user-data-dir /tmp/vscode/`

Probably a corrupted state, might want to try restarting the system ?

**Comment by thehigherlife** [comment]
I have rebooted multiple times... Here is the error i get with your args

open -a /Applications/Visual\ Studio\ Code.app/ --args --user-data-dir /tmp/vscode/
LSOpenURLsWithRole() failed for the application /Applications/Visual Studio Code.app with error -10810.
