### ISSUE TITLE
Saturated and blurry colors/fonts in VSCode 1.49

### ISSUE THREAD

**Issue by sarbikbetal** [microsoft/vscode#106540]
- VSCode Version: 1.49.0-1599744551
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Just open anything in vscode

Does this issue occur when all extensions are disabled?: Yes

This new update of vscode seems to make every color very saturated and blurry, it includes the editor, the terminal, side bar, literally everything.

For your reference this is the comparison with vscode 1.48.2
| VSCode 1.48.2 | VSCode 1.49.0 |
| -- | -- |
| ![old vscode](https://user-images.githubusercontent.com/41508422/92992712-8a7ac080-f50a-11ea-8f67-d5a8db1adfbd.png) | ![new vscode](https://user-images.githubusercontent.com/41508422/92992716-8c448400-f50a-11ea-9126-d93c62603d9c.png) |

I had a similar issue while using VSCode insiders edition and that made me switch back to VSCode stable, but somehow the issue made it's way from insiders to the stable channel as well, and surprisingly this issue persists on the VSCode insiders version 1.50 as well.
This is kind of similar to #84154 but the last activity was 10 months back and this seems to be a fairly new issue.

**Comment by sarbikbetal** [comment]
After searching and tweaking here and there, I got a temporary fix by uncommenting this line on argv.json
```jsonc
{
    // argv.json  Command Pallete > Configure Runtime Arguments
    "disable-hardware-acceleration": true,
}
```
Though I don't understand if this is the right thing to do or what kind of performance impacts it might have.

**Comment by deepak1556** [comment]
Instead of disabling hw acceleration, does it help when you change `"disable-color-correct-rendering": false` instead ?

**Comment by sarbikbetal** [comment]
No `"disable-color-correct-rendering": false` doesn't make any difference.

**Comment by cooperfrench95** [comment]
I have the same issue, and neither changes to argv.json fixed it for me on Ubuntu 18.04.

**Comment by grigorig** [comment]
Same issue here. It's especially bad in the integrated terminal. It looks like a blur filter was applied to it.

![image](https://user-images.githubusercontent.com/1834351/94240639-d9b1ef80-ff13-11ea-8c2b-281cdbe7a4eb.png)

**Comment by sarbikbetal** [comment]
> Same issue here. It's especially bad in the integrated terminal. It looks like a blur filter was applied to it.
> 
> ![image](https://user-images.githubusercontent.com/1834351/94240639-d9b1ef80-ff13-11ea-8c2b-281cdbe7a4eb.png)
> 
> It doesn't look like it uses subpixel rendering either. I'm pretty sure it used to do that.

Yeah this happened for me as well and somehow resizing and maximising the window made the text look sharp. I guess it triggers a full re-render or something. But the colours remained over-saturated all the time.

**Comment by grigorig** [comment]
Running code with `--force-device-scale-factor=1` works around the problem, as seen in the other bug.

**Comment by sarbikbetal** [comment]
Thanks @grigorig, running code with `--force-device-scale-factor=1` seems to work, it removed the blurriness which I believe is referenced in your issue, but the colours are still not correct.

**Comment by daliborfilus** [comment]
I have the same issue - not in integrated terminal, but the whole vs code is "bigger" (I had to decrease font size since the update) and the fonts don't use subpixel antialias. I'm running on Linux with xmonad and I have Xft.dpi set to 115 (don't know if it makes a difference).

Running with `--force-device-scale-factor=1` fixes both issues - fonts have previous (smaller) size now and use subpixel antialias.

I suppose there isn't any way to set this in settings, because it's an Electron thing?

**Comment by deepak1556** [comment]
Closing as no further action can be taken in vscode.

**Comment by grigorig** [comment]
This may not be an issue in the VSCode code itself, but it's still an issue with the overall product. I don't think this issue should be closed. It's quite likely that someone else will open a new issue reporting the same problem.

**Comment by deepak1556** [comment]
Agreed, but unless there is an active upstream issue tracking this bug I don't see the value in keeping the issue open https://github.com/microsoft/vscode/wiki/Issue-Grooming#upstream-issue

**Comment by sarbikbetal** [comment]
Just a piece of update from my side that might help someone, so as identified correctly, it seems like a chromium issue because I tried opening up the same web page on Chrome and Firefox and there also **the colours were noticeably saturated** when viewed side by side, strangely enough when I tried to log in to my system via Ubuntu on **Wayland** the issue seems to have gone, so it seems specific to **Chromium on Xorg.**

**Comment by sarbikbetal** [comment]
Did some more research and found that forcing the `color-profile` to sRGB does the magic in Chrome here: [https://stackoverflow.com/a/51672977](https://stackoverflow.com/a/51672977) and guess what? Adding the same thing to `argv.json` fixes it even when hw acceleration is enabled, so this down here works: 
```jsonc
{
    // argv.json  ||  Command Palette > Configure Runtime Arguments

    // "disable-hardware-acceleration": true,
    "force-color-profile": "srgb"
}
```
