### ISSUE TITLE
Scroll very laggy

### ISSUE THREAD

**Issue by seravifer** [microsoft/vscode#106543]
Issue Type: <b>Performance Issue</b>

I open any file and when scrolling the CPU consumption increases by 20% and it is noticeable that the scroll works very very lagged.

With a clean install of VSCode.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4219)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.96GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   105	 15816	code main
    0	    92	  1236	   window (Issue Reporter)
    0	    71	  7020	   utility
    3	   253	 10848	   window (home.component.ts - room-manager - Visual Studio Code)
    1	   121	  4984	     extensionHost
    0	   293	  7988	       electron_node tsserver.js 
    0	    88	  1316	         electron_node typingsInstaller.js typesMap.js 
    0	   156	  9324	       electron_node tsserver.js 
    0	    74	 14284	       "C:\Users\Sergi\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Sergi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=4984
    3	   326	 17388	       electron_node tsserver.js 
    0	    15	  9304	     watcherService 
    0	    11	 16608	       console-window-host (Windows internal process)
    0	    25	 11292	   crashpad-handler
    0	    40	 12852	   utility
    0	    94	 13000	   shared-process
    0	   124	 17380	   gpu-process
```

</details>
Extensions: none

**Comment by alexdima** [comment]
@seravifer Could you please follow the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process and attach here a JavaScript CPU profile of the renderer while you are scrolling or noticing slowness?

**Comment by seravifer** [comment]
I don't know why but on my two computers where it happens now it works correctly.
