### ISSUE TITLE
Completions which use spaces are broken after updating from July to August version

### ISSUE THREAD

**Issue by kaba2** [microsoft/vscode#106573]
- VSCode Version: August 2020
- OS Version: Windows 10

Updating to August from July version breaks completions which use spaces.  When I start typing the first word, everything seems fine:

![image](https://user-images.githubusercontent.com/2399754/93011894-8058d080-f5a3-11ea-8a09-06c0c1e9c531.png)

However, when I get to the second word, the completion starts anew from the second word:

![image](https://user-images.githubusercontent.com/2399754/93011901-96ff2780-f5a3-11ea-91a6-f6c253aadd88.png)

Contrast this with how the completions work in July version:

![image](https://user-images.githubusercontent.com/2399754/93011908-b1d19c00-f5a3-11ea-800c-e92b4d0a01b8.png)

These completions are generated by the Latex Workshop extension. All other extensions are disabled. However, Workshop developers say that they have no control over the completions.

**Comment by jlelong** [comment]
I am a maintainer of LaTeX-Workshop. I confirm that the same version of the extension is used with vscode `1.49` and `1.48.2`.

The list of suggestions are `completionItem`s with undefined `filterText ` and `range` attributes. In both version, invoking `document.getWordRangeAtPosition(vscode.window.activeTextEditor.selection.active)` returns the current white space delimited word. 

Let me know if I can provide more information/context.

**Comment by jrieken** [comment]
likely due to https://github.com/microsoft/vscode/commit/37ebb445e250275cf794de93a37533f7c65f7616

> n both version, invoking document.getWordRangeAtPosition(vscode.window.activeTextEditor.selection.active) returns the current white space delimited word.

With the change mentioned above we will invoke completions again when entering the next word. Can you confirm that in both invocation the correct, full,  word is returned? I would be confused because the word definition that defines the range also defines that start of the new word. 

Also, with 1.48, what happens when you invoke IntelliSense manually (F1 > Trigger Suggest). Does the word start after the curly `{` or after the space?

**Comment by jrieken** [comment]
fyi @esbenk

**Comment by esbenk** [comment]
We are having a complete backend language server written in C#. We rely on LSP protocol. The protocol message flow have changed with the version 1.49 and now a new "textDocument/completion" message with a different position is sent after the "special" character. We rely on the LSP message and their position to provide completionItems.

btw we supports quoted identifier like "Sales Cr. Memo-Printed". This have work perfectly for the last 3 years.

It seems like you now do the filtering based on what is typed after the second message.

1.48 works also as expected with the manual invocation.

**Comment by jrieken** [comment]
> The protocol message flow have changed with the version 1.49 and now a new "textDocument/completion" message with a different position is sent after the "special" character.

Yes - see the bug fix mentioned above. I still think that was a valid fix

> 1.48 works also as expected with the manual invocation.

So, you say that manual invoking intellisene after the special character does the right thing?

**Comment by jrieken** [comment]
I have the provider below and things work for me. It is important to define a correct range because the default range goes for words (which by default are broken up at whitespaces)

```ts
vscode.languages.registerCompletionItemProvider('fooLang', new class implements vscode.CompletionItemProvider {
    provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext): vscode.ProviderResult<vscode.CompletionItem[] | vscode.CompletionList<vscode.CompletionItem>> {

        const startPos = document.lineAt(position).text.lastIndexOf('{', position.character);
        if (startPos < 0) {
            return;
        }
        const range = new vscode.Range(position.line, startPos + 1, position.line, position.character);
        return [{
            label: 'This is a suggestion',
            range
        }, {
            label: 'These suggestion have a range',
            range
        }, {
            label: 'because they span multiple words',
            range
        }]
    }
})
```

**Comment by esbenk** [comment]
I don't think that your definition of new words holds true for all different languages out there. At least not for ours. 

1.48 works with a manual "Trigger Suggest".

![wQHFRlXUoH](https://user-images.githubusercontent.com/24257835/93177471-26871080-f733-11ea-9b08-c5517453b622.gif)

**Comment by jrieken** [comment]
What range(s) for completion item are you returning then? Can you add a sample that is copy-pastable so that I can repo?

**Comment by esbenk** [comment]
What do mean by ranges for completion items? 

We are using the LanguageClient with our own backend language server. 

I can't provide a copy-pastable sample. I can provide you with a zipped folder structure your can open and try with.

**Comment by jrieken** [comment]
> What do mean by ranges for completion items?

I mean the [range of the completion item](https://github.com/microsoft/vscode/blob/e02afd19048014222134762f5b606e30eb9d95df/src/vs/vscode.d.ts#L3874), as it is shown in my snippet above. I believe in LSP land that's defined via the textEdit of a completion.

> I can't provide a copy-pastable sample. I can provide you with a zipped folder structure your can open and try with.

Whatever allows me to reproduce/debug this. Animated gifs don't.

**Comment by esbenk** [comment]
Install the AL Language extension from marketplace.
If you unzip the attached folder and open it with VsCode.
Open HelloWorld.al
Start typing `Crazy  meth` after the `c.` in line 8

Try with both 1.49 and 1.48

[IntellisenseTest.zip](https://github.com/microsoft/vscode/files/5223195/IntellisenseTest.zip)

We are not sending ranges back. We get this request over the LSP to our backend

```
{
  "jsonrpc": "2.0",
  "id": 13,
  "method": "textDocument/completion",
  "params": {
    "textDocument": {
      "uri": "file:///c%3A/Users/esbenk/Documents/AL/IntellisenseTest/HelloWorld.al"
    },
    "position": {
      "line": 7,
      "character": 10
    },
    "context": {
      "triggerKind": 1
    }
  }
}

```

and returns this back to the LanguageClient.

```
{
  "jsonrpc": "2.0",
  "id": 13,
  "result": [
    {
      "label": "\"Crazy method name\"",
      "kind": 2,
      "detail": "procedure \"Crazy method name\"()",
      "documentation": null,
      "sortText": "1006Crazy method name",
      "filterText": "\"Crazy method name\"",
      "insertText": null,
      "insertTextFormat": 1,
      "data": null,
      "range": {
        "start": null,
        "end": null
      },
      "textEdit": {
        "range": {
          "start": {
            "line": 7,
            "character": 10
          },
          "end": {
            "line": 7,
            "character": 10
          }
        },
        "newText": "\"Crazy method name\"();"
      },
      "tags": null
    },
    {
      "label": "\"Some-other-name\"",
      "kind": 2,
      "detail": "procedure \"Some-other-name\"()",
      "documentation": null,
      "sortText": "1006Some-other-name",
      "filterText": "\"Some-other-name\"",
      "insertText": null,
      "insertTextFormat": 1,
      "data": null,
      "range": {
        "start": null,
        "end": null
      },
      "textEdit": {
        "range": {
          "start": {
            "line": 7,
            "character": 10
          },
          "end": {
            "line": 7,
            "character": 10
          }
        },
        "newText": "\"Some-other-name\"();"
      },
      "tags": null
    },
    {
      "label": "Run",
      "kind": 2,
      "detail": "procedure Run(): Boolean",
      "documentation": null,
      "sortText": "1019Run",
      "filterText": "\"Run\"",
      "insertText": null,
      "insertTextFormat": 1,
      "data": null,
      "range": {
        "start": null,
        "end": null
      },
      "textEdit": {
        "range": {
          "start": {
            "line": 7,
            "character": 10
          },
          "end": {
            "line": 7,
            "character": 10
          }
        },
        "newText": "Run()"
      },
      "tags": null
    },
    {
      "label": "Test",
      "kind": 2,
      "detail": "procedure Test()",
      "documentation": null,
      "sortText": "1006Test",
      "filterText": "\"Test\"",
      "insertText": null,
      "insertTextFormat": 1,
      "data": null,
      "range": {
        "start": null,
        "end": null
      },
      "textEdit": {
        "range": {
          "start": {
            "line": 7,
            "character": 10
          },
          "end": {
            "line": 7,
            "character": 10
          }
        },
        "newText": "Test();"
      },
      "tags": null
    }
  ]
}

```

**Comment by jrieken** [comment]
Not sending back a range is the problem here and now just more visible but also present with 1.48. Do the following

* use 1.48
* in your sample, open `HelloWorld.al`
* on line 8 after `c.` type `crazy m`
* hit ESC to cancel quick suggestion (or disable quick suggestions via `editor.quickSuggestions`)
* manually trigger suggestion via `Ctrl+Space`
* :bug: no suggestion 

it seems that the completion provider is unaware of the anchor of the current completion, e.g the `.`-character of the `c` and therefore only works when triggered at the word following it


![Sep-15-2020 09-58-16](https://user-images.githubusercontent.com/1794099/93182533-13c40a00-f73a-11ea-8f1f-788f580be754.gif)

**Comment by jrieken** [comment]
I do acknowledge the issue but it I am unsure how to proceed. Yes, the fix for https://github.com/microsoft/vscode/issues/99504 does have a negative impact on your extension but in the end it just shows an existing bug in your extension more prominently.

**Comment by jlelong** [comment]
@jrieken thanks for your detailed explanations. It is now clear how we can fix this within the extension.

**Comment by esbenk** [comment]
IMO invoking completion at after `c.cr m n` should not give any results. The code is broken at that point. 

After the `.` we provide a list of valid CompletionItems based on the position. After the first special character + letter you send another textDocument/completion request from a new position where the syntax is now broken.

Can this changed behavior (the re-triggering) be made configurable. I know that our notion of identifier are a bit different than most languages but we are probably not alone. This has been working like this for many years now.

I have a hard time seeing how we can fix this on our end. We don't have the original invoked position anymore. Am I missing something?

**Comment by jrieken** [comment]
> IMO invoking completion at after c.cr m n should not give any results. The code is broken at that point.

Yeah - depending on the language that makes sense

> Can this changed behavior (the re-triggering) be made configurable. I know that our notion of identifier are a bit different than most languages but we are probably not alone. 

No, we cannot make this configurable as that would allow you suppress other providers from working. What I will be looking into is to skip those providers that already have results when re-triggering on entering a new word.

**Comment by jrieken** [comment]
To verify:

* open a TS file
* paste the snippet below
* on the last line type `b n` and make sure that you see the `bazz new` completion


```ts
interface Boo {
	bar: number,
	['bazz new']: null;
}

let a: Boo;
a.
``
