### ISSUE TITLE
Disable preview mode won't work and still doesn't open a new tab

### ISSUE THREAD

**Issue by destroyer22719** [microsoft/vscode#106594]
- VSCode Version:1.49
- OS Version:Microsoft Windows 10 Pro

Steps to Reproduce:

1.Click on a file
2.Still doesn't open a new tab

Does this issue occur when all extensions are disabled?: Yes

Guys I did some research and to open a new tab I had to disable preview mode. I did and it still doesn't work.

![settings json - ensemble-api - Visual Studio Code 2020-09-13 11-36-05](https://user-images.githubusercontent.com/65511595/93022205-f9612380-f5b5-11ea-9571-4722bb4f8db5.gif)

**Comment by gjsjohnmurray** [comment]
What setting did you change to disable preview mode?

Do you know that if you open a file from the Explorer by double click instead of single click it won't be in preview mode? 

Also, double click the preview mode tab (italic label) to make it persist.

**Comment by destroyer22719** [comment]
@gjsjohnmurray 
"workbench.editor.enablePreview": false
like you're supposed to 

This is a laptop and double clicking the touchpad doesn't work
also what's the preview mode tab?

**Comment by gjsjohnmurray** [comment]
You have set `workbench.editor.showTabs` to false. Therefore no tabs.

**Comment by destroyer22719** [comment]
@gjsjohnmurray Thank you so much! It was driving me insane! I didn't know I implemented these changes!

**Comment by gjsjohnmurray** [comment]
Glad to have helped. Please close your issue.
