### ISSUE TITLE
Light+ theme stopped working on Windows 10

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#10658]
- VSCode Version: 1.5.0.-Insider
- OS Version: Windows 10

Steps to Reproduce:

1. use Light+ theme
2. upgrade to latest

Observe:
![2016-08-18_10-09-35](https://cloud.githubusercontent.com/assets/1898161/17766534/e17ebd14-652b-11e6-8bca-9a90eac66eca.png)

**Comment by YuichiNukiyama** [comment]
On Windows 7, too.

**Comment by joaomoreno** [comment]
Should've been fixed in d71df3b99488725d510046b1d37c48aad6af73a8, which is already published for an update. @weinand Can you verify?

**Comment by weinand** [comment]
@joaomoreno works fine in the latest Insiders.
