### ISSUE TITLE
Cannot update extension: Cannot read property once of undefined

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#10654]
- VSCode Version: Code - Insiders 1.5.0-insider (9961aa2df1e1b3960acb2dd45349cb5f832be52d, 2016-08-18T06:08:27.918Z)
- OS Version: Windows_NT ia32 10.0.10586

* update an extension (I updated "Open in Github").

messageService.ts:119Cannot read property 'once' of undefined: TypeError: Cannot read property 'once' of undefined,    at c:\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:8:30449,    at new n.Class.derive._oncancel (c:\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:5:16066),    at Object.h [as download] (c:\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:8:30339),    at c:\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:9:6314,    at Object.m [as _notify] (c:\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:5:8882),    at Object.R.enter (c:\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:5:12460),    at n.Class.define._run (c:\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:5:14288),    at n.Class.define._completed (c:\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:5:13729),    at ClientRequest.<anonymous> (c:\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:8:30036),    at ClientRequest.g (events.js:273:16)

**Comment by alexandrudima** [comment]
Now I notice that the extension does not update.

**Comment by geirsagberg** [comment]
Same error when trying to install new extensions:

```messageService.ts:119Cannot read property 'once' of undefined: TypeError: Cannot read property 'once' of undefined,    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:8:30449,    at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:5:16066),    at Object.h [as download] (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:8:30339),    at c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:9:6314,    at Object.m [as _notify] (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:5:8882),    at Object.R.enter (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:5:12460),    at n.Class.define._run (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:5:14288),    at n.Class.define._completed (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:5:13729),    at ClientRequest.<anonymous> (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcessMain.js:8:30036),    at ClientRequest.g (events.js:273:16)```

**Comment by joaomoreno** [comment]
Fixed by 14a2d83

Firing new builds
