### ISSUE TITLE
Option 'Editor: Mouse Wheel Zoom' also reacts to Win/Super key

### ISSUE THREAD

**Issue by z0rgster** [microsoft/vscode#106581]
Issue Type: <b>Bug</b>

I am running VScode on Manjaro Linux. While trying to assign macros to my mouse wheel if a certain modifier is pressed, I noticed that the Ctrl+Scroll action in VScode is also triggered by Win/Super+Scroll. For many, this might be no issue but for me that means that everytime I do a Win+Scroll on VScode to switch desktops or tabs, the font size changes.
As a possible solution you could either just disbable the Win/Super key from being used for zooming or (and most users would probably favor that) you could add a selectable list of modifier keys that will trigger the zooming.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:20:50.359Z)
OS version: Linux x64 5.8.6-1-MANJARO

**Comment by techdev5521** [comment]
I've a similar issue, also on Manjaro (KDE) where VS Code will scroll when a modifier key like <kbd>Ctrl</kbd> and/or <kbd>Alt</kbd> are pressed. This makes VS Code unusable for me as I use a KWin's screen magnifier with xbindkeys to allow <kbd>Alt</kbd> + Scroll to zoom in and out but I lose my place in my document if the cursor is on VS Code.

No other applications also capture scrolling when a modifier key is pressed.
