### ISSUE TITLE
Format: Insert Space After Opening And Before Closing EMPTY Braces

### ISSUE THREAD

**Issue by diselop** [microsoft/vscode#106510]
Is it possible to do in the option "Format: Insert Space After Opening And Before Closing **Empty** Braces" so that when there are only empty brackets, then they would be {}, and if there are parameters, then spaces would be added { user } and {}

**Comment by mjbvz** [comment]
Isn't this already the default behavior? Here's the stands formatting:

```ts
console.log({});
console.log({ x });
```

You can control this with `javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces` (which seems to just to be a negation of the setting you are proposing)

**Comment by diselop** [comment]
But for classes and methods it works like this
```
class UserMedia { } 
```
Instead of 
```
class UserMedia {}
```

**Comment by mjbvz** [comment]
If you want more a specific formatting setting to control that, please [file a feature request upstream against TypeScript](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md).
