### ISSUE TITLE
Would it be possible to include the command 'run to cursor' in the run menu?

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#106590]
Issue Type: <b>Feature Request</b>

CC: @isidorn

When I am debugging a routine I make a lot of use of the 'run to cursor' command. It took me a while to discover that this command was implemented in VSCode. Certainly if it had appeared on the menu I would have discovered it more quickly.

If it is possible to make this command also appear in the run menu and with an associated shortcut key, I think it will help a lot in accessibility.

VS Code version: Code - Insiders 1.50.0-insider (cca20eba8974b1d6b6a9b71bf4e60a29c8f26648, 2020-09-12T00:58:03.476Z)
OS version: Linux x64 5.8.8-arch1-1

**Comment by isidorn** [comment]
@jvesouza thanks a lot for providing great feedback.
Yeah "Run To Cursor" is already present in the editor context menu while you are debugging. That is the main way how users discover this. Debug has a lot of commands, and if we were to put more in the Run menu soon it might get overcrowded.
Also the editor context menu is somehow "closer" to the cursor than the top main menu.

So your suggestion is to just make it more discoverable.
For now I would not change this to not make the Run menu too large, but am willing to consider it again in the future.

**Comment by jvesouza** [comment]
When I'm debugging and activating the run menu, some options like 'step over', 'step into' and etc are displayed in that menu. I don't know if these options are always present in the menu but they are only read by orca when they are enabled or if they only appear when the debugger is active. I figured that the 'run to cursor' option only appears when the debugger is active.
I understand the argument of not wanting to overload the run menu.
The lesson learned is that I need to use the context menu more often.

**Comment by isidorn** [comment]
Yeah they are always present, but Orca seems to be smart and only read them when they are enabled. We do not hide them to not break user's visual muscle memory.
So for now will not add the Run to Cursor action, but am open for changing it in the future.
