### ISSUE TITLE
[Codespaces] authenticating with GCM-Core doesn't work

### ISSUE THREAD

**Issue by bartekpacia** [microsoft/vscode#106522]
Authenticating with GitHub Credential Manager Core doesn't work when in a GH Codespace.

 A new browser tab opens up but it says "open the desktop app" but there's no a desktop tab because VS Code is running in another browser tab.

![Screenshot 2020-09-12 at 1 49 55 AM](https://user-images.githubusercontent.com/40357511/92981492-67b0c380-f49a-11ea-9eca-29022b43ff62.png)
![Screenshot 2020-09-12 at 1 50 06 AM](https://user-images.githubusercontent.com/40357511/92981495-68e1f080-f49a-11ea-9585-665c286c247f.png)
![Screenshot 2020-09-12 at 1 50 12 AM](https://user-images.githubusercontent.com/40357511/92981497-6a131d80-f49a-11ea-83af-010439c5822a.png)

**Comment by RMacfarlane** [comment]
The first part of this should be fixed, the 801 error is tracked by https://github.com/microsoft/vscode/issues/108304. Please let me know if you still see this. Thanks!
