### ISSUE TITLE
Custom Title Bar too small after latest update

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode#106528]
Issue Type: <b>Bug</b>

After updating to 1.49 I noticed that the title bar is a little bit squished now. 

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id 94ed4732-f758-4d73-bcc9-de56392deb7e --crash-reporter-id 94ed4732-f758-4d73-bcc9-de56392deb7e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
tasks|act|0.6.2
stylus|Ala|0.0.4
TabOut|alb|0.2.0
html-end-tag-labels|ant|0.3.0
color-info|bie|0.5.1
jsdoc-markdown-highlighting|bie|0.0.1
markdown-emoji|bie|0.0.9
markdown-mermaid|bie|1.8.1
markdown-shiki|bie|0.1.1
markdown-yaml-preamble|bie|0.0.4
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.2.0
postcss|css|1.0.9
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
ejs-vue|Dig|0.1.1
javascript-ejs-support|Dig|1.3.1
dotfiles-syntax-highlighting|dot|0.1.0
gitlens|eam|10.2.2
tsl-problem-matcher|eam|0.3.0
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.6.0
shell-format|fox|7.0.1
path-autocomplete|ion|1.15.0
markdown-extended|jeb|1.0.18
vscode-peacock|joh|3.8.0
vscode-remark|mrm|1.2.1
vscode-scss|mrm|0.9.0
csharp|ms-|1.23.2
python|ms-|2020.8.108011
vscode-pylance|ms-|2020.9.4
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
powershell|ms-|2020.6.0
vetur|oct|0.27.2
vscode-ts-config-plugin|oct|0.2.0
material-icon-theme|PKi|4.3.0
vscode-css-peek|pra|4.0.0
qub-xml-vscode|qub|1.2.8
vscode-yaml|red|0.10.1
rust|rus|0.7.8
jinjahtml|sam|0.15.0
vscode-wow-toc|sta|0.0.2
code-spell-checker|str|1.9.0
vscode-stylelint|sty|0.85.0
lua|sum|0.20.5
shellcheck|tim|0.10.1
shell-launcher|Tyr|0.4.1
sort-lines|Tyr|1.9.0
windows-terminal|Tyr|0.6.0
vscode-todo-highlight|way|1.0.4
material-theme|zhu|3.8.7

</details>

![package json — vscode-core — Visual Studio Code_2020-09-12_04-11-52](https://user-images.githubusercontent.com/75278/92984923-625d7400-f4ae-11ea-896e-956326081081.jpg)

**Comment by vainamov** [comment]
I'm not entirely sure if this could have the same reason but there is a similar issue on Windows right now. When VS Code is closed in maximized state and reopened again the title bar isn't stretched to the top of the screen but instead a white line is rendered.
![grafik](https://user-images.githubusercontent.com/11841072/93233398-4fcb8f00-f77b-11ea-8a55-287e5600c8ff.png)

Version: 1.50.0-insider (system setup)
Commit: e13875b77c89b95f20ccb5667e14ff164c198e57
Date: 2020-09-15T05:35:57.362Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by sbatten** [comment]
@vainamov this is likely a different issue. please file it separately

**Comment by sbatten** [comment]
@Stanzilla is this 100% repo?

**Comment by Stanzilla** [comment]
@sbatten yup

**Comment by sbatten** [comment]
@Stanzilla can you run with `--user-data-dir <some empty dir>` to try "fresh"

**Comment by Stanzilla** [comment]
@sbatten happens there as well

**Comment by Stanzilla** [comment]
pretty sure it's only happening on BigSur

**Comment by sbatten** [comment]
@Stanzilla thanks for the update. given the preview nature of Big Sur, I don't have a great way to verify what's going on right now. Is it the case that the expected title bar size is much larger in Big Sur than previous versions? Can you share a side by side of custom vs native titlebar in VS Code?

**Comment by deepak1556** [comment]
@sbatten seems like the titlebar height has increased in big sur, here are the measurements for native title bar height using accessibility inspector

**Catalina**

AXWindow pos - x=0, y=23
Content Area - x=0, y=45

Frame height - 22

**Big Sur**

AXWindow pos - x=1, y=25
Content Area - x=1, y=53

Frame Height - 28

**Comment by sbatten** [comment]
@bpasero I went to update the title bar part but it is now in electron-sandbox and thus cannot access os props except through the native host service which is async. the title bar part would need the os version synchronously. any suggestion?

**Comment by bpasero** [comment]
@sbatten if you must have a property sync, it needs to be added to the `IWorkbenchEnvironmentService` which is being created with some config properties from the main side. Example:

https://github.com/microsoft/vscode/blob/6bebcbb58d95e59ffde0e372888c5eea3995bf82/src/vs/workbench/services/environment/electron-sandbox/environmentService.ts#L21-L21

**Comment by sbatten** [comment]
@bpasero would need os version to adjust the title bar size as mac OS big sur is using a thicker title bar

**Comment by bpasero** [comment]
@sbatten if you can give me exactly the node.js call you need, I can add it. Looks like `os.version()` was only added in later node.js versions: https://nodejs.org/api/os.html#os_os_version

**Comment by sbatten** [comment]
Looks like release has the right info, https://nodejs.org/api/os.html#os_os_release

**Comment by bpasero** [comment]
@sbatten added `INativeWorkbenchEnvironmentService.os.release`

**Comment by sbatten** [comment]
@rebornix I believe can verify

**Comment by Stanzilla** [comment]
/verified

Thank you!
