### ISSUE TITLE
Out of memory starting vscode

### ISSUE THREAD

**Issue by mikedice** [microsoft/vscode#106597]
- VSCode Version: I don't know. It won't run. Cloned vscode repo on Sat, Sept 12 2020
- OS Version:
pi@raspberrypi:~/code/vscode $ node -v
v12.18.3
pi@raspberrypi:~/code/vscode $ npm -v
6.14.6
pi@raspberrypi:~/code/vscode $ uname -rmvo
5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
This is a raspberry pi 4 with 8GB of RAM

Steps to Reproduce:
1. Clone vscode repo
2. Run 'yarn'. It cranks away for a very long time.
3. Run scripts/code.sh. It emits the out of memory exception shown below. Note in the trace below I also output memory stats, at the time of the crash there is 4GB of free memory (out of 8GB)
pi@raspberrypi:~/code/vscode $ ./scripts/code.sh
yarn run v1.22.5
$ node build/lib/electron
Done in 1.45s.
yarn run v1.22.5
$ gulp compile --max_old_space_size=4095
[08:53:37] Node flags detected: --max_old_space_size=4095
[08:53:37] Respawned to PID: 21500

<--- Last few GCs --->

[21500:0x23aedb8]     1947 ms: Mark-sweep 24.3 (29.8) -> 24.3 (29.8) MB, 28.6 / 0.1 ms  (average mu = 0.836, current mu = 0.002) allocation failure GC in old space requested
[21500:0x23aedb8]     1976 ms: Mark-sweep 24.3 (29.8) -> 24.1 (26.5) MB, 29.0 / 0.0 ms  (average mu = 0.725, current mu = 0.002) last resort GC in old space requested
[21500:0x23aedb8]     2002 ms: Mark-sweep 24.1 (26.5) -> 24.0 (26.5) MB, 26.8 / 0.0 ms  (average mu = 0.583, current mu = 0.002) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x27ece8b5 <JSObject>
    0: builtin exit frame: compileFunction(this=0x34740335 <JSGlobal Object>,0x333e20c9 <JSArray[5]>,0x333e20b9 <JSArray[0]>,0x47640279 <undefined>,0x476403c1 <false>,0x47640279 <undefined>,0,0,0x50929f99 <String[#62]: /home/pi/code/vscode/node_modules/typescript/lib/typescript.js>,0xb02c008d <Very long string[8802315]>,0x34740335 <JSGlobal Object>)

    1: wrapSafe(aka wrapSafe) [0x58c85bd9] [inter...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Aborted
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
pi@raspberrypi:~/code/vscode $ free
              total        used        free      shared  buff/cache   available
Mem:        8064956      852016     4063516      315244     3149424     6599376
Swap:        102396        2816       99580

Does this issue occur when all extensions are disabled?: Yes

**Comment by mikedice** [comment]
By the way I just deleted every instance of max_old_space_size=4095 from ./package.json then reran ./scripts/code.sh. The app started and ran fine with that change.

**Comment by joaomoreno** [comment]
Good to know you're unblocked.
