### ISSUE TITLE
ipynb not connecting to kernal 

### ISSUE THREAD

**Issue by lorenzoyeung** [microsoft/vscode#106578]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

all my ipynb files are not opening. i am not the only one, there are many others on https://stackoverflow.com/questions/63856340/vs-code-cant-open-ipynb-file

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|19, 8, 5|
|Memory (System)|16.00GB (0.96GB free)|
|Process Argv|--crash-reporter-id 2a854eaa-c4eb-4102-8414-cf86d4ab147b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-database|baj|2.2.3
cc-nodejs|cc-|0.0.3
path-intellisense|chr|2.3.0
regex|chr|0.2.0
bracket-pair-colorizer|Coe|1.0.61
python-preview|don|0.0.4
githistory|don|0.6.9
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
tslint|eg2|1.0.44
auto-close-tag|for|0.5.8
pythonsnippets|frh|1.0.2
sass-lint|gle|1.0.6
ansible|haa|0.2.8
vscode-test-explorer|hbe|2.19.1
docker-linter|hen|0.5.0
vscode-heroku|iva|1.2.6
RelativePath|jak|1.4.0
vsc-python-indent|Kev|1.11.0
vscode-codemetrics|kis|1.24.0
vscode-mac-dictionary|koh|0.2.0
vscode-python-test-adapter|lit|0.5.0
gitignore|mic|1.0.1
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.9.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.8.108011
vscode-pylance|ms-|2020.9.4
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
autodocstring|njp|0.5.3
indent-rainbow|ode|7.4.0
heroku-command|pko|0.0.8
vscode-yaml|red|0.10.1
trailing-spaces|sha|0.3.1
code-spell-checker|str|1.9.0
ansible-autocomplete|tim|0.0.2
vscodeintellicode|Vis|1.2.10

</details>

**Comment by gjsjohnmurray** [comment]
Please look at #106547. Is yours a duplicate?

**Comment by rebornix** [comment]
closing as no more information is provided.
