### ISSUE TITLE
Arduino serial monitor not working

### ISSUE THREAD

**Issue by mannarsai** [microsoft/vscode#106536]
Issue Type: <b>Bug</b>

After upgrade of VSCode to 1.49.0 unable to open serial monitor in Arduino extension (vscode-arduino	vsc	0.3.2)

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

**Comment by iqapps** [comment]
Me too. Just updated, and bang, nothing works.

I just filled in a survey about what VSCode could do better - my answer was "stability, stability stability", and then this happen...

**Comment by iqapps** [comment]
Could we please have an easy downgrade to previous version button somewhere. These serial port problems is happening so often it has become an issue of timewaste to downgrade every time. We have a "install a previous release" menu item on each extension, but where is it on the VS code itself.

**Comment by iqapps** [comment]
I can confirm that downgrading to 1.48.2 restores expected functionallity.

**Comment by sbatten** [comment]
please see https://github.com/microsoft/vscode-arduino/issues/1097 for progress
