### ISSUE TITLE
Code file is being formatted after save contrary to settings

### ISSUE THREAD

**Issue by tzuriel-spearuav** [microsoft/vscode#106572]
[ as continue discussion within the cpp extension repository - https://github.com/microsoft/vscode-cpptools/issues/6107 ]

- VSCode Version: 1.49.0
- OS Version: Win10 (10.0.19041.450)

Steps to Reproduce:

1. Run vscode --disbale-extensions
2. Make sure settings are set as follows -
"editor.formatOnSave": false
"editor.formatOnType": false
3. Create a cpp or js file and save it
4. Notice formatting - file has been formatted after saving, contrary to settings

Does this issue occur when all extensions are disabled?: Yes

Before save-
```
(temp.js)
var   i =    0;
```

After save-
```
(temp.js)
var i = 0;
```

Also with cpp files:
`const char* Class::units = <<multiple spaces/tabs>> "km";`
becomes
`const char *Class::units = "km";`

**Comment by jrieken** [comment]
> Run vscode --disbale-extensions

Try `vscode --disable-extensions`

**Comment by tzuriel-spearuav** [comment]
typo, sorry. Indeed reproduces with disabled extensions

**Comment by jrieken** [comment]
It cannot be that your extensions are disabled. VS Codes does not ship with a formatter for CPP files and if CPP files are formatted then you do have extensions enabled (for builtin JS it's a different story as they cannot be disabled with that flag)

**Comment by tzuriel-spearuav** [comment]
You're right. The problem is specific to the cpp extension. When I disable all extensions - no problem appears. When only the cpp extension is enabled, a cpp file gets formatted, even though the formatOnSave flag is set to false.

As @sean-mcmanus noted in microsoft/vscode-cpptools/issues/6107, the log analysis extension seems to suggest a formatting message has been received from vscode

**Comment by jrieken** [comment]
> the log analysis extension seems to suggest a formatting message has been received from vscode

I don't think so. I am unable to reproduce with JS, e.g when disabling format on save, no format happens when saving. The code is also super trivial: 

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/codeEditor/browser/saveParticipants.ts#L242-L246

**Comment by jrieken** [comment]
Can you try the following:

* F1 > Log Level > Debug
* F1 > Show Logs > Extension Host
* Save a CPP file
* check for a message like this "[2020-09-14 09:40:43.739] [exthost] [debug] onWillSaveTextDocument-listener from extension 'jrieken.virtual2' finished after 44ms"

**Comment by tzuriel-spearuav** [comment]
He're the log -
```
[2020-09-14 10:45:04.666] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2020-09-14 10:45:04.666] [exthost] [error] undefined
[2020-09-14 10:45:08.730] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2020-09-14 10:45:08.730] [exthost] [error] undefined
[2020-09-14 10:45:49.270] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2020-09-14 10:45:49.270] [exthost] [error] undefined
[2020-09-14 10:46:25.807] [exthost] [debug] onWillSaveTextDocument-listener from extension 'ms-vscode.cpptools' finished after 1ms
```

**Comment by jrieken** [comment]
Ok, format on save should _not_ be implemented with an `onWillSaveTextDocument`-listener. Let's wait for @sean-mcmanus  to confirm that they don't do this

**Comment by sean-mcmanus** [comment]
1. We're not able to repro the bug. If we could get a repro, we could investigate/fix it probably.
2. Our TypeScript code at https://github.com/microsoft/vscode-cpptools/tree/master/Extension doesn't references onWillSaveTextDocument .
3. I mentioned filing a VS Code bug if the bug reproed with .js. Am I understand that it doesn't repro with .js files or it repros with .js files only when the C/C++ extension is enabled (which would be odd because we aren't supposed to process .js files).

**Comment by jrieken** [comment]
> Our TypeScript code at https://github.com/microsoft/vscode-cpptools/tree/master/Extension doesn't reference onWillSaveTextDocument .

Not a LSP expert but what is this: https://github.com/microsoft/vscode-cpptools/blob/f7165bae4f312cd18894a6f3c1308dfc80d8f460/Extension/src/LanguageServer/protocolFilter.ts#L81. Also the log message (https://github.com/microsoft/vscode/issues/106572#issuecomment-691883908) does mention the cpp extension

**Comment by sean-mcmanus** [comment]
Our cpptools LSP server implements willSaveWaitUntil, but not willSave. The willSave message never gets sent to us (so it seems like it might not even need to handled in that file). Our implementation of willSaveWaitUntil just sends back a null message and potentially triggers and IntelliSense update, but we don't do any formatting or send back any edits.

**Comment by jrieken** [comment]
> Our cpptools LSP server implements willSaveWaitUntil, but not willSave.

Thanks for clarifying @sean-mcmanus. On the vscode.d.ts side both are implemented via `onWillSaveTextDocument` that's why I was going after this.

We are still left with an issue that isn't reproducible, e.g with JS this doesn't reproduce and I would also be surprised if this is a general issue (unwanted formatting on save) since most user of VS Code do save

**Comment by tzuriel-spearuav** [comment]
Cannot reproduce after reinstall vscode
