### ISSUE TITLE
VS Code not able to create or load existing Jupyter Notebooks

### ISSUE THREAD

**Issue by amitmeel** [microsoft/vscode#106586]
after the latest update from vscode, now it is unable to load the jupyter notebooks. it is just showing loading kernel thats all. 

If i try to create a new notebook it is showing:: Unable to open 'Untitled-1.ipynb': [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1596)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.23GB free)|
|Process Argv|--crash-reporter-id 1d40455f-a09d-401b-963d-4f18052018c8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
gitlens|eam|10.2.2
python|ms-|2020.8.108011
unique-window-colors|stu|1.0.51
vscodeintellicode|Vis|1.2.10

</details>

**Comment by ducalpha** [comment]
I have the same error (VS Code 1.49.0 on Windows 10). The devtools shows the following:
```
notebookServiceImpl.ts:286 Cannot register renderer for ms-python.python since it did not have an entrypoint. This is now required: https://github.com/microsoft/vscode/issues/102644
```

**Comment by ShaleenAg** [comment]
Same here, the jupyter kernel loads but the notebook ui is blank
