### ISSUE TITLE
Integration test is failing on 1.49.0 with zip package on latest linux containers

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#106569]
Error is:

```
Server response: 

/dev/fd/3: No such file or directory

SIGSEGV
```

I'm using `ubuntu-18.04`.

I firsted noticed it in Vetur's CI: https://github.com/vuejs/vetur/runs/1107596361

I found this issue by @deepak1556: https://github.com/microsoft/vscode/issues/103060
I tried adding `--disable-gpu`, and there's no effect.

I have a minimal repro here: https://github.com/octref/vscode-149-linux-crash/runs/1107649209?check_suite_focus=true
(1.49.0, with `--disable-gpu`)

1.48.2 runs fine: https://github.com/octref/vscode-149-linux-crash/actions/runs/252075021

**Comment by deepak1556** [comment]
```
Server response: 

/dev/fd/3: No such file or directory
```

Thats just the crash reporter from chromium `breakpad` trying to send the crash dump to the server and failed, fixing that is tracked here https://github.com/microsoft/vscode/issues/103051, its not the source of issue. There is actually a crash `SIGSEGV` in that run. Can you launch with `--crash-reporter-directory <path>`, it will generate the dumps in that path, we can inspect further with it.

**Comment by octref** [comment]
https://github.com/octref/vscode-149-linux-crash/runs/1107690935?check_suite_focus=true

```
yarn run v1.22.5
warning package.json: No license field
warning vscode-test-sample@0.0.1: The engine "vscode" appears to be invalid.
$ node ./out/sample/test/runTest.js
Downloading VS Code 1.49.0 from https://update.code.visualstudio.com/1.49.0/linux-x64/stable
Downloaded VS Code 1.49.0 into .vscode-test/vscode-1.49.0
Found --crash-reporter-directory argument. Setting crashDumps directory to be '/home/runner/work/vscode-149-linux-crash/vscode-149-linux-crash/crash'

Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

[main 2020-09-13T06:14:31.876Z] update#setState idle

(node:2967) Electron: Loading non-context-aware native module in renderer: '/home/runner/work/vscode-149-linux-crash/vscode-149-linux-crash/sample/.vscode-test/vscode-1.49.0/VSCode-linux-x64/resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

[2906:0913/061433.509722:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.

(node:2967) Electron: Loading non-context-aware native module in renderer: '/home/runner/work/vscode-149-linux-crash/vscode-149-linux-crash/sample/.vscode-test/vscode-1.49.0/VSCode-linux-x64/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

Failed to generate minidump.
Failed to run tests
Exit code:   null
SIGILL
Done
```

**Comment by octref** [comment]
You can fork and play with it. I'm not running it locally.
https://github.com/octref/vscode-149-linux-crash/blob/master/.github/workflows/ci.yml
https://github.com/octref/vscode-149-linux-crash/blob/master/sample/test/runTest.ts

**Comment by bobbrow** [comment]
This blocks CI for the cpptools extension.  We have to do admin override for all PR's or disable tests.

**Comment by deepak1556** [comment]
Looked briefly at this, I couldn't get the crash dump from the workflow yet, will verify with a local container setup.

As a workaround install snap or deb version of vscode and point `vscodeExecutablePath` to it. Most likely the container is missing a dependency for the latest electron upgrade.

**Comment by Colengms** [comment]
@deepak1556 I'm trying to work around this by installing VS Code using snap:
```
sudo snap install --classic code
```
And passing the following path as `vscodeExecutablePath`: `/snap/bin/code`

However, this results in the following error from within runTests() :
```
$ tsc -p test.tsconfig.json && node ./out/test/unitTests/runTest.js
mkdir: cannot create directory ‘/run/user/1001’
: Permission denied
```

Can you advise?

**Comment by deepak1556** [comment]
@Colengms it would be a permission issue with the ci agent you are using, not sure I can be of much help with that.

**Comment by Colengms** [comment]
@deepak1556 We're using base vmImages from azure-pipelines, via GitHub.  The issue repros with `ubuntu-16.04`, `ubuntu-18-.04` and `ubuntu-20.04` images.

**Comment by mapoitras** [comment]
Did you ever resolve this issue?  I'm getting the same error trying to run a powershell command in azure devops.

mkdir: cannot create directory ‘/run/user/1001’: Permission denied

This is the script:
$XslPath = "$(Build.SourcesDirectory)/OWASP/OWASPToNUnit3.xslt"
$XmlInputPath = "$(Agent.TempDirectory)/dependency-scan-results/dependency-check-report.xml"
$XmlOutputPath = "$(Agent.BuildDirectory)/converted-dependency-check-report.xml"
$XslTransform = New-Object System.Xml.Xsl.XslCompiledTransform
$XslTransform.Load($XslPath)
$XslTransform.Transform($XmlInputPath, $XmlOutputPath)

**Comment by bobbrow** [comment]
We migrated our CI over to GitHub Actions and use this step to run our tests now:
```
      - name: Run unit tests
        uses: GabrielBB/xvfb-action@v1.4
        with:
          run: yarn run unitTests
          working-directory: Extension
```
This works on linux.

**Comment by aaronpowell** [comment]
I've just come across this as well (build ref: https://dev.azure.com/aaronpowell/VS%20Code%20Profile%20Switcher/_build/results?buildId=1012&view=logs&j=c9e7f81a-e301-5408-62aa-d2082bd3a1e5&t=27ccc203-455f-5175-cf9c-96632ceb65ba&l=41)

I'm assuming that Azure Pipelines is using a container of some flavour to run the agent, would there be some way that we can force the right snap to be loaded?

I'd prefer not to have to move to GitHub Actions if I don't have to (I'm too lazy to port my script!)

**Comment by yoyo930021** [comment]
https://github.com/microsoft/vscode/issues/106569#issuecomment-717450642
This solution is work for me.

https://github.com/vuejs/vetur/actions/runs/477706275

**Comment by deepak1556** [comment]
Closing, can reopen if issue persists with newer versions.
