### ISSUE TITLE
Notebook webview resources can not be loaded

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#106516]
Issue Type: <b>Bug</b>

Insiders now always open the notebook webview in iframe and it can't load resources 

```
GET vscode-webview-resource://4250cc26-9639-478b-b277-b6393c61fc34/file///Users/penlv/.vscode-insiders/extensions/ms-vscode.vscode-github-issue-notebooks-0.0.50/dist/renderer.js net::ERR_ABORTED 404 (Not Found)
```

I'm not able to reproduce this issue in OSS.

VS Code version: Code - Insiders 1.50.0-insider (bc38b0accb3c62180317c63dbe7323200977db0f, 2020-09-11T12:26:02.664Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.62GB free)|
|Process Argv|-psn_0_63487112 --enable-proposed-api ms-vscode.vscode-notebook-history --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|10%|
</details>

**Comment by mjbvz** [comment]
Didn't you switch notebooks to always use iframe based webviews a few iterations back?

**Comment by rebornix** [comment]
@mjbvz no we only tried that temporarily but then continued using electron webview for desktop (by using injected `IWebviewService`). Insiders from 3 days ago (the last 1.49-Insiders) works fine.

Added a few breakpoints and found that the service registration sequence is now wrong

* https://github.com/microsoft/vscode/blob/7e5937d684eb1dcbe5f199eaf81152411e1ef7e1/src/vs/workbench/contrib/webview/electron-browser/webview.contribution.ts#L12 is called first
* https://github.com/microsoft/vscode/blob/80b1a775d691612ce8334238d786a922d55e3544/src/vs/workbench/contrib/webview/browser/webview.contribution.ts#L33 is then called, which overrides the Electron webview service.

**Comment by mjbvz** [comment]
Thanks. This was caused by 80b1a775d691612ce8334238d786a922d55e3544. Not sure how this ever worked or why only notebooks seem effected at the moment but I'll look into a proper fix

**Comment by mjbvz** [comment]
Pushed potential fix but could not verify since I don't see the bug in OSS. Kicking off an official build now for testing

**Comment by mjbvz** [comment]
Confirmed that this is fixed for me in the latest insiders
