### ISSUE TITLE
Settings sync merge conflict list is too small

### ISSUE THREAD

**Issue by k-khr** [microsoft/vscode#106542]
Issue Type: <b>Bug</b>

![ conflict list is too small](https://user-images.githubusercontent.com/22492054/92994344-6af88d80-f534-11ea-8110-5cf8d6ab0549.png)

1. Narrow side bar
1. Select "Settings" and turn on settings sync
2. Select an account which was already synced with another vscode instance
3. Choose "Merge Manually" on "Merge or Replace" dialog

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

Extensions disabled

**Comment by sandy081** [comment]
@k-khr I cannot repro this. Are there any steps I am missing here?

**Comment by k-khr** [comment]
@sandy081 Can you make the sidebar as narrow as possible?

As the height of the highlighted element in devtools is too small, I cannot find which file to solve conflict.

![a](https://user-images.githubusercontent.com/22492054/93312830-a4860d00-f842-11ea-83a9-e0a26e68260f.png)

**Comment by sandy081** [comment]
So do you see the list completely when you make sidebar wider?

**Comment by k-khr** [comment]
I can see! Many thanks

**Comment by sandy081** [comment]
I cannot repro it even though I decreased the size of the side bar. Closing it. Please reopen it with steps to reproduce. 
Thanks.
