### ISSUE TITLE
Seeing progress from one viewlet showing up in other viewlet

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10653]
I wonder why the progress service gets disposed in compositePart.ts https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/compositePart.ts#L180 ?

**Comment by isidorn** [comment]
I would think it was there before we converting this code to work with composits.
From how I understand the progess service gets created on line 166 and thus needs to get dispoed later. Though why don't we use a centralized progress service like in debugViewlet.ts?

**Comment by bpasero** [comment]
@isidorn but the progress service is scoped per viewlet so that it can be used in each viewlet and is scoped to that viewlet (e.g. when you switch to another viewlet while one shows progress, we stop the progress).

I am lately seeing that progress from the git viewlet leaks into other viewlets and wanted to understand why this happens.

**Comment by bpasero** [comment]
I have updated the summary to reflect the issue I see. When I have a large repository like TypeScript, open the git viewlet, trigger a refresh and click on another viewlet, I see the progress from git in that other viewlet.

**Comment by isidorn** [comment]
Nice finding, I will investigate.
