### ISSUE TITLE
Repeated modal popups when stopping debugging

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#106576]
Issue Type: <b>Bug</b>

**repro**
1. In https://github.com/kieferrm/js-debug-sample
1. Add a breakpoint on the line `const mm = require('./micromatch');` in  `cluster.js`
1. Using a debug console, start debugging `cluster.js`
1. When the breakpoint is hit, try to stop debugging

**Bug**
This results in a sequence of 8 or so modal popups. You have to dismiss them one at a time

Here's the text from one of the errors

```
Error processing attach: Error: Could not get debug session delegate ID 14
    at t.DelegateLauncher.launch (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:40100)
    at t.Binder.captureLaunch (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:118764)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at t.Binder._launch (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:118327)
    at async Promise.all (index 11)
    at t.Binder._boot (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:73:117587)
    at t.default._onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js:15:2463780)
```

VS Code version: Code - Insiders 1.50.0-insider (cca20eba8974b1d6b6a9b71bf4e60a29c8f26648, 2020-09-12T00:56:22.923Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (10.14GB free)|
|Process Argv|--crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by connor4312** [comment]
I don't get this; can you enable trace: true and share the resulting log file?

**Comment by mjbvz** [comment]
Which log file?

**Comment by connor4312** [comment]
After adding `trace: true` to the launch.json, it'll print the location of the log file on disk to the Debug Console

**Comment by mjbvz** [comment]
Ok, I trued with the following config:

```
        {
            "name": "Launch Program",
            "program": "${workspaceFolder}/cluster.js",
            "request": "launch",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node",
            "trace": true
        }
```

But don't see the error. I still see the error when using the debug terminal. Is there a way to collect logs from there?

I also updated the instructions to make it clear you need a breakpoint on `const mm = require('./micromatch');` in `cluster.js`

**Comment by connor4312** [comment]
Interesting. I still didn't get this locally, but for logs there you can add that in the `debug.javascript.terminalOptions` user setting

**Comment by mjbvz** [comment]
Here's the log file (but it appears to be corrupted since I can't seem to uncompress it)

[vscode-debugadapter-5.json.gz](https://github.com/microsoft/vscode/files/5220142/vscode-debugadapter-5.json.gz)

**Comment by connor4312** [comment]
Thanks -- the key was hitting "disconnect" rather than ctrl+c in the terminal which is what I was doing. Should be a simple fix.
