### ISSUE TITLE
Feature: Print text documents to a printer

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode#106517]
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

I have no idea how to print a text file to a printer from Visual Studio Code. As far as I can tell, I don't think Visual Studio Code has this feature in yet. I even used the Command Palette just to make sure if I can launch a GUI for printing a text document from Visual Studio Code.

May I request for a feature to print text document to a printer from Visual Studio Code directly? I had to open Notepad.exe just to print a text copy.

**Comment by tommai78101** [comment]
It's a full on duplicate of #5953. Closing.

**Comment by PeterWone** [comment]
@tommai78101 VS Code is all about extensions. https://marketplace.visualstudio.com/items?itemName=pdconsec.vscode-print
