### ISSUE TITLE
Closing terminal ends with exit code 130

### ISSUE THREAD

**Issue by ZuBB** [microsoft/vscode#106555]
- VSCode Version: 1.49.0
- OS Version: mac os 10.15.5 (19F101)

Steps to Reproduce:

1. launch integrated terminal
2. press `Ctrl+C` shortcut in it
3. press `Ctrl+D` to log out

terminal tab will be closed but "The terminal process "/usr/local/bin/bash '-l'" terminated with exit code: 130." error message will appear

Does this issue occur when all extensions are disabled?: Yes

_Additional info_: I use bash v5.0.18 installed from brew as my default shell

----
<img width="528" alt="Screenshot 2020-09-12 at 22 35 20" src="https://user-images.githubusercontent.com/597016/93003812-853d6600-f54a-11ea-88c4-8b21fbe2e18b.png">

**Comment by Tyriar** [comment]
VS Code reports all non-zero exit codes from the shell, when you ctrl+d it exited with that code so we show it, I don't know how you can disable this on the shell side. You can suppress these exit code messages from VS Code though with `"terminal.integrated.showExitAlert": false`
