### ISSUE TITLE
Highlight similar text dpends on search settings

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode#106570]
Issue Type: <b>Bug</b>

When I double-click or otherwise highlight some text, similar text is marked throught the file. Which text exactly get marked dpends on the search settings that are active at the moment, but they are not displayed in any way for adjusting.

For example, create a new file with this text:
```
for
fork
For
```

Highlight the "for" on the first line - the other 2 "for"s are marked. Now press Ctrl-F and set either "Match case" or "Match whole word". Now close the search box and highlight the "for" again. Whetever settings were set in the search box are applied here as well, but there is no visibale indication of what they are or way to set them without opening the search box again.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.9.0-0.bpo.6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mews7748|
|OS|Linux x64 4.9.0-0.bpo.6-amd64|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 2258)|
|Memory (System)|15.54GB (3.63GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
material-icon-theme|PKi|4.3.0
gitlens|eam|10.2.2
todo-tree|Gru|0.0.178
me-vscode|ME-|0.0.9
git-graph|mhu|1.25.0
cpptools|ms-|0.30.0-insiders5
hexeditor|ms-|1.3.0

</details>

**Comment by ArturoDent** [comment]
I see the Find options on-screen for a short time but I think the time it stays on-screen needs to be extended.  If I want to mouse over there and change options it usually has disappeared before I get there.  It seems to be there for only two seconds.

Version: 1.52.0-insider (user setup)
Commit: caf01baa45b9816e2e1d8a2de22b40cf89459c03
Date: 2020-11-20T07:41:44.570Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20262

**Comment by RaulDurand** [comment]
> I see the Find options on-screen for a short time but I think the time it stays on-screen needs to be extended. If I want to mouse over there and change options it usually has disappeared before I get there. It seems to be there for only two seconds.

However the "find options" are not visible at all when you are just selecting some text and look for similar text.

**Comment by ArturoDent** [comment]
Yes, they are in the Insiders' Build - upper right corner.

**Comment by rzhao271** [comment]
@ArturoDent please file a new bug for that issue.
