### ISSUE TITLE
Cannot open .ipynb

### ISSUE THREAD

**Issue by jkrygel** [microsoft/vscode#106587]
I'm using the latest release of vscode and it's python extension, and can no longer open .ipynb files. There are no issues with the files themselves, I work on them in jupyter notebook now. 
VScode just continuously "loads" when I try to open one of these files, that's all I need to do to reproduce the problem.

**Comment by gjsjohnmurray** [comment]
Probably duplicate of #106534 and #106547

**Comment by rchiodo** [comment]
It is mentioned in #106547 but this issue is not the same as the URI problem.

Root cause seems to be a rendering issue.
See the discussion here:
https://github.com/microsoft/vscode-python/issues/13901

**Comment by rchiodo** [comment]
![maximize](https://user-images.githubusercontent.com/19672699/93117472-c54c3800-f673-11ea-8d4b-ffaad96e73b1.gif)

**Comment by rchiodo** [comment]
This may also require this setting here to be set:
```json
    "python.experiments.optInto": [
        "CustomEditorSupport - experiment"
    ],
```

**Comment by rchiodo** [comment]
That setting enables the usage of the custom editor API. This experiment was enabled by mistake on Friday 9/10.

**Comment by rebornix** [comment]
@rchiodo what's the recommended fix/workaround for this issue?

**Comment by rchiodo** [comment]
This should have resolved itself? Are you still seeing the issue?

**Comment by rebornix** [comment]
Closing as no update after two weeks.
