### ISSUE TITLE
VsCode doesn't prompt refresh when gradle files are changed

### ISSUE THREAD

**Issue by Karanjot-singh** [microsoft/vscode#106539]
- VSCode Version: 1.48.2
- OS Version: Linux x64 5.3.0-28-generic

Steps to Reproduce:

1. Modify the gradle files inside any Android App development project (I use flutter )
2. You may follow the tutorial to add a database from firebase. https://console.firebase.google.com/
2. Save the changes and no prompt to refresh appears

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
> Save the changes and no prompt to refresh appears

You expect VSCode to prompt? We do not prompt but simply take the changes unless the file is dirty.

**Comment by Karanjot-singh** [comment]
@bpasero Refer https://firebase.google.com/docs/flutter/setup. After making changes to the app and build level Gradle files, I always need to run ./gradlew in the android(app level) directory while using VS code to refresh the configuration. Some other editors / IDEs offer the functionality of a prompt which automatically runs the above script. Could be useful to others like me

**Comment by Karanjot-singh** [comment]
![image](https://user-images.githubusercontent.com/55680995/93216805-ce2d2e80-f785-11ea-827c-d166fa140de6.png)
