### ISSUE TITLE
Terminal Pane in panel changes order on upgrade from 1.48.* to 1.49

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#106579]
- VSCode Version: 1.49.0
- OS Version: macOS 10.14.6 (Also on another Windows 10 PC)

Steps to Reproduce:
1. Automatically upgraded from 1.48.* to 1.49.
2. The terminal pane is now between the "Problems" and "Output" where previously it was the last. This was not mentioned in the changelog and might not be intentional. (You can reorder of course, this is about the default)
<img width="421" alt="image" src="https://user-images.githubusercontent.com/24731903/93014609-0af8fa00-f5bb-11ea-8b37-a5fb3376c560.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
@sbatten could this have changed because I changed the view ID from `workbench.panel.terminal` to just `terminal` in aa6b2f163dad27d8e5d011ed36fb77e536a14e9d?

**Comment by sbatten** [comment]
Steps that could have happened to produce this:
1) Move terminal inside another container at some point
2) Move terminal back to panel (now a custom container, but no practical difference)
3) Update to get new view id which does not match the cached relocation of terminal

🐛 => the "new view id" is registered to the original terminal container which is in a different location.

The only catch here is that similar steps would have to have happened on 2 machines for this to be consistent unless @segevfiner uses settings sync

**Comment by segevfiner** [comment]
Not using settings sync. I don't remember ever moving anything in or out of the panel either on both PCs where this happened. But that's only from memory...

**Comment by sbatten** [comment]
Can you right click each of the tabs (e.g. problems) and check to see if any have an entry "Reset Location"

**Comment by segevfiner** [comment]
None of them seems to have such an entry:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/24731903/93113520-f6535980-f6c1-11ea-849f-9c1f308d83e7.png">

**Comment by sbatten** [comment]
@segevfiner can you also verify that running `code --user-data-dir <some temp folder path>` gives you terminal in the correct position?

**Comment by segevfiner** [comment]
It does.

**Comment by sbatten** [comment]
ok, this means the out of the box experience is working properly and it doesn't seem to be an issue with moved views. i don't have any additional guesses as to what could cause this from the upgrade

**Comment by tjx666** [comment]
It seems that I also encountered this issue before

**Comment by sbatten** [comment]
will re-open if we get reports in the future.
