### ISSUE TITLE
provideSignatureHelp doesn't seem to render anything despite being called and returning data

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10665]
- VSCode Version: 1.4
- OS Version: Windows 10

I'm trying to implement a signatureHelpProvider (which I believe is the thing that gives me parameter hints when I type `(` or `,` when calling a method/signature/etc.).

My code seems to be called; I see "running" in the console whenever I type a `(` but nothing ever appears in the editor! Here's my code:

```typescript
provideSignatureHelp(document: TextDocument, position: Position, token: CancellationToken): SignatureHelp {
	console.log("running...");
	return {
		activeParameter: 0,
		activeSignature: 0,
		signatures: [{
			label: "test",
			documentation: "test2",
			parameters: [
				{
					label: "test3",
					documentation: "test4",
				}
			]
		}]
	};
}
```

There are no errors shown anywhere, but also no popup. I've tried 1-based indexes for `activeParameter`/`activeSignature` but no difference.

Any ideas what might be causing this or how I could debug further?

**Comment by jrieken** [comment]
I'll investigate

**Comment by jrieken** [comment]
Ok, the problem is that we spec `vscode.SignatureHelp` as a `class` and the method above returns an object literal which fails the [`instanceof`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L615) check. It's an ongoing debate whether TypeScript should flag this as compile error or not  - both things are structurally equal but instanceof is nominal check.

When you return something like `new vscode.SignatureHelp` it will work

**Comment by DanTup** [comment]
Aha; gotcha! I will change it over and give it a whirl today. Thank you! 😄

**Comment by jrieken** [comment]
and for reference: https://github.com/Microsoft/TypeScript/issues/8168

**Comment by DanTup** [comment]
By the way, I've implemented most of my providers this way and they all seemed to work, I presume this is something specific to signatures that the others don't do?

**Comment by jrieken** [comment]
You might just be lucky ;-) Often we only check if something is an array but not the array types... Tho there are plans to accept both - class instances and look-alike literals

**Comment by DanTup** [comment]
Btw, in some sample code in the issue you linked, you warn on bad stuff:

```typescript
            } else {
                // warn about everything else
                console.warn('INVALID result from completion provider. expected CompletionItem-array or CompletionList but got:', value);
                return;
            }
```

But for this one, you don't. If easy to add, a warning might make it easier for understand what's happening.
