### ISSUE TITLE
Unable to authorize VSCODE

### ISSUE THREAD

**Issue by barshasony** [microsoft/vscode#106638]
Unable to Authorize Vscode for an Org ,All environment variables added and proxy settings is disabled
Getting below error :
Error: spawn powershell ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {   
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn powershell',
  path: 'powershell',
  spawnargs: [
    '-NoProfile',
    '-NonInteractive',
    '–ExecutionPolicy',
    'Bypass',
    '-EncodedCommand',
    'UwB0AGEAcgB0ACAAIgBgACIAaAB0AHQAcABzADoALwAvAHQAZQBzAHQALgBzAGEAbABlAHMAZgBvAHIAYwBlAC4AYwBvAG0ALwAvAHMAZQByAHYAaQBjAGUAcwAvAG8AYQB1AHQAaAAyAC8AYQB1AHQAaABvAHIAaQB6AGUAPwByAGUAcwBwAG8AbgBzAGUAXwB0AHkAcABlAD0AYwBvAGQAZQAmAGMAbABpAGUAbgB0AF8AaQBkAD0AUABsAGEAdABmAG8AcgBtAEMATABJACYAcgBlAGQAaQByAGUAYwB0AF8AdQByAGkAPQBoAHQAdABwACUAMwBBACUAMgBGACUAMgBGAGwAbwBjAGEAbABoAG8AcwB0ACUAMwBBADEANwAxADcAJQAyAEYATwBhAHUAdABoAFIAZQBkAGkAcgBlAGMAdAAmAHMAdABhAHQAZQA9ADAAMABhAGUAYwBmAGQANwA0ADEAYgA1ACYAcAByAG8AbQBwAHQAPQBsAG8AZwBpAG4AJgBzAGMAbwBwAGUAPQByAGUAZgByAGUAcwBoAF8AdABvAGsAZQBuACUAMgAwAGEAcABpACUAMgAwAHcAZQBiACYAYwBvAGQAZQBfAGMAaABhAGwAbABlAG4AZwBlAD0AaABtAE4ARgB4AEIARAB1AFIAVwB4AHYAeABxAFAASwBOAEQAWQAtAGMARwBIADkASwBuAGcAeQBxADcAVwBpAF8AbQBEADgAcQBCAFIAQgBzAEsAOABgACIAIgA='
  ]
}

**Comment by roblourens** [comment]
Please give more details about what you are trying to do and when this error shows up

**Comment by barshasony** [comment]
Hi,

I am getting this error when I am trying to Auhtorize an Org from Vscode.
Vscode version -1.49,Salesforce CLI version -7.74.1

Thanks,
Barsha Patro

**Comment by mJaiswal613** [comment]
I am also getting the same issue, please let me know if anyone has a solution for it. Any help would be highly appreciated.

**Comment by barshasony** [comment]
The issue got resolved after adding the path of powershell "C:\Windows\System32\WindowsPowerShell\v1.0 " to PATH Environment variable from Control Panel>Advanced>Environment Variable

**Comment by mJaiswal613** [comment]
Thank you barshasony it worked.

**Comment by barshasony** [comment]
👍Great
