### ISSUE TITLE
XHR failed

### ISSUE THREAD

**Issue by ahmed99dine** [microsoft/vscode#106600]
Issue Type: <b>Bug</b>

marketplace cannot connect

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.76GB free)|
|Process Argv|--crash-reporter-id aba25adf-f8c6-47fc-a44e-f1f5de68a00e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sandy081** [comment]
please share the logs and errors from the following locations
    - Help -> Toggle Developer Tools -> Console
    - Help -> Toggle Developer Tools -> Network
    - View -> Open View… -> Log (Window)
