### ISSUE TITLE
add breadcrumbs to peek view

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#106680]
Sometime I peek the references of a variable, and the peek view window only show little part content of the reference file,. If I want the understand the code context, I need jump to the file,. If there is a breadcrumb in the peek view, I can easily understand the context meaning of reference code.

![screenshot_2020-09-15_01-46-40](https://user-images.githubusercontent.com/41773861/93120031-544d6480-f6f5-11ea-9238-055e90f17172.png)

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Abreadcrumbs+label%3Afeature-request
