### ISSUE TITLE
Add ability to copy all call stacks

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#106696]
This was referred to in https://github.com/microsoft/vscode/issues/59959 , but I do not see another issue tracking it.

It would be useful to have the ability to copy the contents of all call stacks in the Call Stack pane.

We'd like to provide our users with guidance on how to attach a (native) debugger and report call stacks, when reporting issues with our extension.  Some issues are related to memory usage and CPU over-use.  In order to diagnose these, we'd like the user to provide a snapshot of all call stacks while the issue is occurring.  Currently, this would require them to separately click on each of our (potential >50) threads to copy stacks.  A UI feature to simply copy all call stacks would seem useful.

**Comment by isidorn** [comment]
@Colengms I think this makes sense, however it sounds very specific to your extension, at least for now nobody else asked for this.

Here's a potential solution for this:
1) Your extension contributes a command "Copy All Call Stacks"
2) The implementation of that command would simply call `debug.copyStackTrace` command
3) That command would handle specialy the case when it does not get any arguments, and in that case would copy all stack traces from all threads and from all sessions.

Some open questions, how would the stack traces get separated when they are written to clipboard?
Should the thread and session name also be copied?

**Comment by Colengms** [comment]
>at least for now nobody else asked for this.

@isidorn .  Technically, 1 other person has asked for it, in https://github.com/microsoft/vscode/issues/59959 .  :)  I don't think this is specific to our extension.  Our use case is one example, and it's not contrived.  I had actually asked our Debugger dev for this feature.  I was directed to make to the request here instead, as addressing it in in VS Code seems simple and generally useful.

**Comment by ruffsl** [comment]
Hello @isidorn , I'm another user needing to simply copy multiple call stacks as proposed in:

- https://github.com/microsoft/vscode/issues/59959

As that thread was quickly locked, and this thread isn't very discoverable (as there is not back-linking in closed threads), I'm guessing that why "nobody else asked for this", given the percentage of  users bother looking for a ticket to comment on and subscribe to, find the top search result for feature request was rejected, a then just giving up.

---

> The implementation of that command would simply call debug.copyStackTrace command

How do I invoke this `debug.copyStackTrace command` as a end user?
