### ISSUE TITLE
Debugger is terribly broken. My app crashes while running with or without debugger the new version

### ISSUE THREAD

**Issue by dpnishant** [microsoft/vscode#106618]
Issue Type: <b>Bug</b>

I'm not sure what exactly is the bug. But after the last update, my Node.js app is crashing on the VS Code "stable" build. Interestingly the same app runs fine when I start it manually from my terminal. And the same app runs fine with an old installation of the VS Code "insiders" build. I'm not sure supporting data should I attach except the version details and launch configuration. The default shell is the same as on my Terminal. The node PATH is the same. The same app used to work just fine before the upgrade. Is there a way to undo the update?

`.vscode/launch.json`
```js
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
  
  {
      "type": "node",
      "request": "launch",
      "name": "Launch App",
      "program": "${workspaceFolder}/index.js"
    },
]
}
```

VSCode "insider" installation is as follows:
```
Version: 1.41.0-insider
Commit: e15ff0097ceb84c4e28a67dac41c2d8dcd4cf027
Date: 2019-11-29T09:05:24.307Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

and my VS Code "stable" (the buggy one) installation is as follows:
```
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T17:39:53.251Z (3 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
```

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (8.74GB free)|
|Process Argv|--crash-reporter-id 6772b415-eae5-4552-89ad-868c04582b8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
python-docs|Muk|0.8.3
better-comments|aar|2.1.0
vscode-nsp|ada|1.0.1
marko-beautify|bus|2.0.0
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|2.1.8
javascript-ejs-support|Dig|1.3.1
createuniqueid|don|0.0.3
vscode-babel-coloring|dza|0.0.4
vscode-great-icons|emm|2.1.56
eppz-code|epp|1.2.52
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
php-debug|fel|1.13.0
code-runner|for|0.11.0
docker-explorer|for|0.1.7
py-paste-indent|hye|0.1.2
debugger-for-phantomjs|ira|0.1.1
vscode-format-context-menu|lac|1.0.4
pop-n-lock-theme-vscode|Lux|3.31.0
vscode-docker|ms-|1.5.0
vscode-devskim|MS-|0.4.187
python|ms-|2020.8.108011
debugger-for-chrome|msj|4.12.10
debugger-for-ios-web|msj|0.1.2
marko|pca|0.4.0
material-icon-theme|PKi|4.3.0
partial-diff|ryu|1.4.1
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.10
JavaScriptSnippets|xab|1.8.0

(12 theme extensions excluded)

</details>

**Comment by fy2462** [comment]
The same issue on Ubuntu, and output `No debugger available, can not send 'variables'` in debug console.

**Comment by danieler1981** [comment]
Still using v1.46 because debugger with auto-attach is not working anymore starting v1.47

`node --inspect-brk=0.0.0.0:34131 --require dotenv/config ./index.js
Debugger listening on ws://0.0.0.0:34131/55ed7864-7e6a-47fd-89db-64878cd0a920
For help, see: https://nodejs.org/en/docs/inspector`

Seems like "-brk" make VSCode wait forever.

**Comment by connor4312** [comment]
> Still using v1.46 because debugger with auto-attach is not working anymore starting v1.47
>
> node --inspect-brk=0.0.0.0:34131 --require dotenv/config ./index.js Debugger listening on ws://0.0.0.0:34131/55ed7864-7e6a-47fd-89db-64878cd0a920 For help, see: https://nodejs.org/en/docs/inspector

You no longer need any `--inspect` flag in the console. You can omit that and you should be good to go. See here for details: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_auto-attach-feature

> The same issue on Ubuntu, and output No debugger available, can not send 'variables' in debug console.

This is expected if you try to expand details on anything in the debug console after the session ends.

> But after the last update, my Node.js app is crashing on the VS Code "stable" build

Can you please share the error you're seeing in the terminal?

As a temporary workaround you can set `debug.javascript.usePreviewAutoAttach: false`, but this option will go away next month, so please share the error so I can fix it 🙂

**Comment by clarkestephen** [comment]
I have been getting the same issue on my vscode version 1.49.0. See [stackoverflow question with additional info](https://stackoverflow.com/questions/63851762/vscode-node-debugger-throws-uncaught-error-write-epipe)

<img width="629" alt="Screen Shot 2020-09-11 at 12 17 01 PM" src="https://user-images.githubusercontent.com/56166793/93111034-b4072980-f67b-11ea-884d-c4720ebe80aa.png">

vscode version 1.38.0 debugs the code without a problem.

**Comment by connor4312** [comment]
@clarkestephen thanks, see here for the fix! https://github.com/microsoft/vscode/issues/106484#issuecomment-691202789 This will be released in the upcoming recovery build this week.
