### ISSUE TITLE
Change Request Feature to Search Feature Requests in menu

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#10669]
As we move from UserVoice we decided on changing the menu item. 

The menu item will change from "Request Feature" to "Search Feature Requests"

This will point to a forward link, which will point to this query https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+sort%3Areactions-%2B1-desc 

From [vscode-distro product.json](https://github.com/Microsoft/vscode-distro/blob/master/quality/stable/product.json#L90), this is the forward link that needs to change.
 
https://go.microsoft.com/fwlink/?LinkID=533482

**Comment by waderyan** [comment]
@chrisdias can you update https://go.microsoft.com/fwlink/?LinkID=533482 to point to https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+sort%3Areactions-%2B1-desc?

**Comment by chrisdias** [comment]
@waderyan 

updated to: 

https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3Afeature-request 

the fwlink tool does not like the %2B1 in the sort parameter.  

if you want sorting we may need to use aka.ms

**Comment by waderyan** [comment]
We definitely want sorting. Let's use aka.ms

Can you update it again with the aka.ms below? 

https://aka.ms/popular-feature-requests

**Comment by chrisdias** [comment]
done
