### ISSUE TITLE
Cannot open jupyter notebook

### ISSUE THREAD

**Issue by Anar0729** [microsoft/vscode#106636]
Issue Type: <b>Bug</b>

Please check the latest update version of VS Code. It has same problem for many people that anyone couldn't solve it. 
https://github.com/microsoft/vscode/issues/106547

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.77GB free)|
|Process Argv|C:\DepthMap\DepthMap_20200914\DepthMap_20200914_MultiTask.ipynb --crash-reporter-id 6920e2a2-cc30-45ea-aa13-4ac3faed26ca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.8.108011
remote-wsl|ms-|0.44.5
cpptools|ms-|0.29.0

</details>

![image](https://user-images.githubusercontent.com/68235661/93063226-e54e1c80-f6b0-11ea-8e31-98b4cc2df576.png)

**Comment by gjsjohnmurray** [comment]
/duplicate

Please contribute to the existing issue instead of opening a new one.
