### ISSUE TITLE
[loc][issue][zh-CN] Local is translated to ‘JU’ incorrectly

### ISSUE THREAD

**Issue by yachen4ever** [microsoft/vscode#106676]
As I mentioned in 2 pull-requests I created in [vscode-loc](https://github.com/microsoft/vscode-loc/pull/185) and [vscode-translate](https://github.com/microsoft/vscode-translate/pull/2), the English word 'Local' has all been translated to 'ju' which is not a chinese word or character at all. The word 'local' can be translated to 2 words in chinese: '本地' and '局部'. The previous one should be used in circumstances like 'Local Environment' while the latter one used like 'Local Variable'. I correct those 3 positions separately.

This mis-translate leads to a confusing information on the addon page when using Remote Addon.
![Snipaste_2020-09-15_01-25-47](https://user-images.githubusercontent.com/9250987/93118260-975a0880-f6f2-11ea-90f1-4b6b780b4e6c.png)
Check out the screenshot above. Where the original english version says 'Local - Installed', the chinese version says 'JU - 已安装', which is quite confusing.

**Comment by danyeh** [comment]
Thank you @yachen4ever for your feedback and PR. Issue fixed as suggested in [1.49.2](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans)
