### ISSUE TITLE
Debug viewlet stays in "welcome" mode even after launch.json creation 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#106669]
Version: 1.50.0-insider
Commit: cca20eba8974b1d6b6a9b71bf4e60a29c8f26648
OS: Darwin x64 19.6.0

- create new folder aynwhere
- open folder in VS Code
- goto debug viewlet
- observe: debug viewlet is in "welcome" mode
- click link "To customize Run and Debug create a launch.json file" to create launch.json
- select a debug environment, create a launch config, and save editor

Observe:
debug viewlet is stuck in "welcome" mode

**Comment by isidorn** [comment]
I can not reproduce this. What are you doing differently than me?

1. VS Code insiders, open new empty folder 
2. Open debug viewlet, click link "To customize Run and Debug create a launch.json file" to create launch.json
3. Debug viewlet is no longer in Welcome mode

I also tried out of source and vscode stable and I can not reproduce.

If you still see this, do you get file events in that VS Code instance? For example make a change outside of VS Code to some file and see if VS Code is picking up the change.

![recording](https://user-images.githubusercontent.com/1926584/93308085-1853f580-f802-11ea-8057-979f6a405be3.gif)

**Comment by weinand** [comment]
I was seeing this:
![2020-09-16_09-59-31 (1)](https://user-images.githubusercontent.com/1898161/93310538-353df800-f805-11ea-97b9-7857d519674e.gif)

A launch.json exists but the debug viewlet shows the welcome view (even after a restart).

Disabling all extensions made the problem disappear.
After re-enabling all extensions the problem didn't come back...

Strange...
