### ISSUE TITLE
Separate color sceme scope for method declaration and method invocation.

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#106685]
I am working on a color scheme for vscode.

For coloring methods, I only have the option to color the declaration and invocations the same. It would be nice to be able to separate these.

I am currently testing my theme on Java...

```
public class Foo {
    public void bar() {
    }
}

// some other code somewhere
Foo foo = new Foo();
foo.bar();
```
In this example the scope "entity.name.function" applies for both the declaration (public void bar() ...) and the invocation (foo.bar()).

This should be broken out into two different scopes, so they could be colored differently.

**Comment by aeschli** [comment]
It's the TextMate grammar that creates these scopes. Each language has it's own grammar. You could file an issue against the Java TextMate grammar to come up with an additional scope. That said, TextMate grammars are kind of bound to a standard set of scopes and inventing new scopes doesn't make sense as no other theme will take advantage of it

**Comment by safield** [comment]
So where can I find a definition for a languages grammer?

**Comment by aeschli** [comment]
The one for Java we get from https://github.com/atom/language-java

**Comment by jwortmann** [comment]
You can already distinguish between function declarations and invocations in Java. Declarations use `meta.method.identifier.java entity.name.function`, while invocations use `meta.method-call.java entity.name.function` and `meta.function-call.java entity.name.function`.

**Comment by safield** [comment]
Little confused. You listed **entity.name.function** 4 separate times. Is there just a post formatting issue here?

**Comment by jwortmann** [comment]
I don't know what you're talking about. They all use different meta scopes.

![screenshot](https://user-images.githubusercontent.com/6579999/93387051-e629ae80-f868-11ea-987c-a981a52d53d1.png)

```json
{
      "scope": ["meta.method.identifier.java entity.name.function"],
      "settings": {
        "foreground": "#85a300"
      }
    },
    {
      "scope": ["meta.method-call.java entity.name.function"],
      "settings": {
        "foreground": "#d85896"
      }
    },
    {
      "scope": ["meta.function-call.java entity.name.function"],
      "settings": {
        "foreground": "#d89333"
      }
    },
```

**Comment by safield** [comment]
I am confused about the redudancy of the string _entity.name.function_. Why is it supplied in all of the scopes?

**Comment by safield** [comment]
The following definition does not result in red method/function calls.

		{
			"name": "Function declarations",
			"scope": [
				"entity.name.function", // remove this, because it applies to function declarations and references.
				"support.function",
				"support.constant.handlebars",
				"source.powershell variable.other.member",
				"entity.name.operator.custom-literal" // See https://en.cppreference.com/w/cpp/language/user_literal
			],
			"settings": {
				"foreground": "#7ad149"
			}
		},
        {
            "name": "Function Calls",
            "scope": [
                "meta.method-call.java entity.name.function",
                "meta.function-call.java entity.name.function"
            ],
            "settings": {
                "foreground": "#ff0000"
            }
        },

**Comment by jwortmann** [comment]
> I am confused about the redudancy of the string entity.name.function. Why is it supplied in all of the scopes?

Because you don't want to target *only* "uncolored" meta scopes, which often span bigger sections of code. Here for example, the meta scopes include the parentheses, which you probably want to color differently.

I tried the definitions you just posted and they *do* work for me.

**Comment by 0dinD** [comment]
@safield You can color declarations differently using the [semantic highlighting](https://github.com/redhat-developer/vscode-java/wiki/Semantic-Highlighting) feature introduced a couple of versions back. The Language Support for Java extension provides the `declaration` modifier since version 0.65.0.

Example:
```jsonc
// In the semantic highlighting rules...
"function:java": "#FF0000", // All Java methods are now red.
"function.declaration:java": "#00FF00" // All Java method declarations are now green.
```
