### ISSUE TITLE
Webview refreshes to previous state after clicking another open editor 

### ISSUE THREAD

**Issue by nsharma1989** [microsoft/vscode#106693]
- VSCode Version: 1.49
- OS Version: OS: Darwin x64 19.5.0

Steps to Reproduce:

1. Open a react webview perform state changes. 
2. Open settings preferences 
3. click back to the editor where webview is opened.
 Result- the webview refreshes back to the very first state of launching webview

Please note that my extension has the flag `retainContextWhenHidden : true` This problem wasn't there in previous versions

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
AFAIK This is intended behavior to preserve resources.

Have you checked docs for
https://code.visualstudio.com/api/extension-guides/webview#persistence and 
https://code.visualstudio.com/api/extension-guides/webview#retaincontextwhenhidden ?

Do this approaches solve your problem?

**Comment by nsharma1989** [comment]
Hi @IllusionMH , Yes as mentioned in the issue we have`retainContextWhenHidden : true`.
Looks like I have found something related. When I load my extension files using vscode-resource the persistence is working .
However , for eclipse-che compatibility I updated my extension to use `vscode-webview-resource` and now the persistence is not working and the webview is behaving like when's its launched for the first time everytime I switch to another opened editor.

**Comment by mjbvz** [comment]
I just confirmed that `haveretainContextWhenHidden` is working as expected for a simple case. I suspect there may be a bug in your extension.

Can you please share a minimal example extension that demonstrates the issue?

**Comment by nsharma1989** [comment]
Hi @mjbvz yes I noticed it is working when I use `vscode-resource` for loading the scripts but it refreshes when I am using `vscode-webview-resource`

**Comment by mjbvz** [comment]
The markdown preview uses modern webview resources (`vscode-webview-resource`). Please provide a minimal example extension

Also you shouldn't be hardcoding either of these url schemes directly in your code, use `asWebviewUri` instead

**Comment by nsharma1989** [comment]
Hi @mjbvz , yes it is not hardcoded  I am using 
```
const scriptUri2 = this._panel.webview.asWebviewUri(Uri.file(path.join(extensionPath, 'dist', 'bundle.js')));
    const styleUri = this._panel.webview.asWebviewUri(Uri.file(path.join(extensionPath, 'dist', 'styles.css'))); 
```
I will try to get a sample code to reproduce the issue.

**Comment by nsharma1989** [comment]
the extension code is based out of https://github.com/rebornix/vscode-webview-react/blob/master/ext-src/extension.ts

**Comment by mjbvz** [comment]
I confirmed `retainContextWhenHidden` works fine in that extension too:

```diff
diff --git a/ext-src/extension.ts b/ext-src/extension.ts
index 42f3371..a372031 100644
--- a/ext-src/extension.ts
+++ b/ext-src/extension.ts
@@ -46,7 +46,8 @@ class ReactPanel {
 			// And restric the webview to only loading content from our extension's `media` directory.
 			localResourceRoots: [
 				vscode.Uri.file(path.join(this._extensionPath, 'build'))
-			]
+			],
+			retainContextWhenHidden: true
 		});
 		
 		// Set the webview's initial html content 
diff --git a/src/App.tsx b/src/App.tsx
index c1bc27c..c9fa0e8 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -19,4 +19,7 @@ class App extends React.Component {
   }
 }
 
+let i = 0;
+setInterval(() => { console.log(i++) }, 1000);
+
 export default App;
```
