### ISSUE TITLE
the interface becomes blurred and indistinct。

### ISSUE THREAD

**Issue by WayKwin** [microsoft/vscode#106615]
- VSCode Version:1.49.0
- OS Version:Darwin x64 19.5.0

more  information:
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T17:39:53.251Z (3 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0

Steps to Reproduce:

1.  launch vscode
2. open any project

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/33773565/93036203-c714fc00-f671-11ea-92b0-1bdc016ee9b7.png)

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/106429 , please refer to the workaround in that issue.
