### ISSUE TITLE
CSS Emmet is slow

### ISSUE THREAD

**Issue by AlexJoo2003** [microsoft/vscode#106658]
- VSCode Version: 1.48.2
- OS Version: Ubuntu 20.2

Hello. I have noticed that VScode CSS Emmet shortcuts don't work if you type the abbreviations to fast. The issue is very similar to #50997, but there it was with html at the start of a new file, where my problem occurs every time if done quickly. 
When I type the abbreviation like `w` for `width:`, the popup doesn't appear for half a second and therefore the shortcut doesn't work in that period of time.

This problem only occurs when I use super short abbreviations like `w` for width, `h` for height, `c` for color, `m` for margin, etc. Then in order for shortcut to work I have to retype it, wait for a second and press tab. 

I would say that this issue didn't occur to me when I was using windows or in other languages like HTML or JavaScript, and when using bigger abbreviations like `bgc.` for background-color.

Steps to Reproduce:

1. Open a .css file in VSCode
2. Type `w` (or any other one letter abbreviations) and press tab very quickly

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment]
Closing this in favour of #83423, but I can reproduce this issue.

**Comment by rzhao271** [comment]
Actually, @AlexJoo2003 have you tried enabling the setting `Emmet: Trigger Expansion On Tab`?

It might be waiting for the dropdown every time.
