### ISSUE TITLE
text is duplicated in Terminal when typing fast rigth after opening the terminal

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#106642]
- VSCode Version: 1.49.0
- OS Version: Linux Fedora 31

Steps to Reproduce:

1. Open a terminal
2. Start typing fast

![duplicatedText](https://user-images.githubusercontent.com/1105127/93067120-16abf580-f67b-11ea-8983-0b79508c81ac.gif)

or

1. Programmatically createTerminal `let terminal = vscode.window.createTerminal()`
2. Programmatically show Terminal `terminal.show();`
3. Programmatically send Text to Terminal `terminal.sendText('some command');`

Does this issue occur when all extensions are disabled?: Yes

A first iteration can be to provide a way to wait programmatically that the Terminal is ready to receive text. it will cover the programmatic case.

**Comment by Tyriar** [comment]
Other terminals will do this too, this happens when your start up scripts are running, at that point the shell just echos the input out before your prompt is ready.

**Comment by apupier** [comment]
How to wait that the prompt is ready?

**Comment by Tyriar** [comment]
@apupier just wait a second? Bottom line is I don't believe we don't control this and therefore cannot suppress it.

**Comment by apupier** [comment]
An unconditional wait has higher drawbacks than the double print of the command.
for fast computer: it will slow down for no good reason
for slow computers: whatever time is provided it can be not enough. The bigger wait is added, the higher chance there is to be fine but there is the higher impact on all other users and a worse experience.

**Comment by Tyriar** [comment]
@apupier the time probably depends on what is in your `.bashrc` file, bash is doing this, not vscode.

**Comment by apupier** [comment]
> the time probably depends on what is in your `.bashrc` file,

another reason showing that we cannot use a random tiemout.

> bash is doing this, not vscode.

What VS Code can do to improve User Experience is to provide a method to know if the prompt is ready or provide a method returning a Promise of the Terminal only when the prompt is ready.

**Comment by Tyriar** [comment]
VS Code doesn't know that either though, the user could have a slow running nvm script that takes 3 seconds for example, we can only guess when it's ready as well.

You could consider launching the script in a different way, eg. a script that does something like:

```
bash -c ~/prelaunch.sh
bash
```

**Comment by apupier** [comment]
The idea of the feature is to show how to use VS Code to launch command in the VS Code Terminal.

By the way, I have no ~/prelaunch.sh file so the slowness is not related to that.

**Comment by Tyriar** [comment]
That was an example of how to fix your issue; If you put `some command` into `prelaunch.sh` you will avoid the echoed text.
