### ISSUE TITLE
Window crashes when I tried to close 20 tabs one at a time

### ISSUE THREAD

**Issue by manohar-kumar** [microsoft/vscode#106627]
Issue Type: <b>Bug</b>

*Create 30-40 tabs
* try closing them one by one 
* It shows window has crashes. Click to reopen and continue where you left off

VS Code version: Code - Insiders 1.50.0-insider (cca20eba8974b1d6b6a9b71bf4e60a29c8f26648, 2020-09-12T01:04:21.398Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.81GB free)|
|Process Argv|--crash-reporter-id f4f38c97-0116-4edb-a29d-3d609f15fa02|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.36.3
json-tools|eri|1.0.2
json-escaper|jos|1.1.0
vscode-sbt-scala|lig|0.2.4
escape-quotes|mil|1.10.0
prettify-json|moh|0.0.3
python|ms-|2020.8.108011
cpptools|ms-|0.29.0
auto-correct|syg|0.2.1
file-size|zh9|0.1.3

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
