### ISSUE TITLE
vs code very slow and doesn't response

### ISSUE THREAD

**Issue by mahassen-essalhi** [microsoft/vscode#106644]
Issue Type: <b>Bug</b>

Hi,

I have a big problem with vs code, it is very slow and often doesn't respond.
It is painful to work with.

Thank you in advance for your help. 

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.6.0
vscode-xml|red|0.13.0
salesforce-vscode-slds|sal|1.2.1
salesforcedx-vscode|sal|49.9.0
salesforcedx-vscode-apex|sal|49.9.0
salesforcedx-vscode-apex-debugger|sal|49.9.0
salesforcedx-vscode-apex-replay-debugger|sal|49.9.0
salesforcedx-vscode-core|sal|49.9.0
salesforcedx-vscode-lwc|sal|49.9.0
salesforcedx-vscode-visualforce|sal|49.9.0

</details>

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
