### ISSUE TITLE
Use "Add Folder" to add file causing unexpected behaviour

### ISSUE THREAD

**Issue by lexiaoau** [microsoft/vscode#106620]
- VSCode Version:1.48.2
- OS Version:Ubuntu 18.04

Steps to Reproduce:

1.Copy string "models/Book.ts"
2.Right click on "src" folder and select "New Folder"
3. Paste string in step 1 and enter.
4. A folder and file are created, but it can not be open in VS Code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
That is as designed. You have simply created a "New Folder" that is `models` and inside another folder `Book.ts`
What you want is a "New File". Once you click on that all will be fine
