### ISSUE TITLE
Add support for background tasks

### ISSUE THREAD

**Issue by hexler81** [Microsoft/vscode#10661]
- VSCode Version: 1.4
- OS Version: Windows 10 64-Bit

VC Code tasks are currently blocking. I.e., no other task can be executed until the currently running task has finished. There are situations, though, were it makes sense execute a task while another one is still running. Consider the following example:

I am writing a TeX document using VS Code. I have two tasks. One **build** task that runs pdflatex on my document in order to generate a pdf from my tex file. And a **show** task that opens my pdf in my pdf viewer (SumatraPDF in my case). SumatraPDF supports modifications to the currently shown pdf file while the viewer is still running. I.e., I could change my tex file and run my **build** task. SumatraPDF detects this and updates as soon as the new pdf is finished. However, as the **show** task is running until I close SumatraPDF, I cannot execute the **build** task. Being able to run **show** as a background task that does not block other tasks from being executed would solve this.

I also tried to workaround this by using grunt-exec but I was not able to find a configuration that solves my use case.

Best
Frank

P.S.: Thanks for this great and fast code editor! The more I use it, the more I can imagine that it has the potential to replace a lot of other editors that I am currently using for different tasks.

**Comment by dbaeumer** [comment]
Duplicates https://github.com/Microsoft/vscode/issues/981
