### ISSUE TITLE
Find widget covers results on first line

### ISSUE THREAD

**Issue by saborrie** [Microsoft/vscode#10662]
- VSCode Version: 1.4.0
- OS Version: Discovered on Ubuntu, suspect it is the same on all

Steps to Reproduce:
1. Turn off word wrap
2. Have a very long first line of file
3. Press Ctrl+f / Open find and replace in top right of window
4. Search for a term that exists in line 1

Observe that the term is hidden by the find-box, the window is not scrolled far enough to the right to show it

E.g. in this image I have searched for "mp3", you can see the start of the path in "Value" but the actual "mp3" itself is hidden because this is the first line in the file.

![image](https://cloud.githubusercontent.com/assets/4096734/17771514/49dff4c2-653b-11e6-85cc-e1806b984d7f.png)

**Comment by DeeHants** [comment]
Making it movable (drag handle on the edge?) should allow them to be seem, and also allows reading of the full first line.

**Comment by rebornix** [comment]
Let's track it in https://github.com/Microsoft/vscode/issues/5525 and solve it in May.
