### ISSUE TITLE
Add NotebookCell#index api

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#106637]
For https://github.com/microsoft/vscode/issues/105283 we have added operations to replace cells or modify output and metadata for cells. These operations target a cell by notebook-uri and cell index. To make this API easy to consume we should add `NotebookCell#index` - being the index of the cell in the array of cells.

**Comment by jrieken** [comment]
We should also consider to remove `NotebookCell#uri` since it is less important and just a shorthand for `NotebookCell#document#uri`

**Comment by isidorn** [comment]
How best to verify this?

**Comment by jrieken** [comment]
Try it against `vscode.proposed.d.ts`
