### ISSUE TITLE
Settings page keeps showing a (2) next to the user tab when using json mode

### ISSUE THREAD

**Issue by pingshunhuangalex** [microsoft/vscode#106605]
- VSCode Version: 1.50.0-insider
- OS Version: macOS Catalina 10.15.6

Steps to Reproduce:

1. Open setting page
2. Make sure to switch to json mode
3. Check the user tab

![image](https://user-images.githubusercontent.com/17170199/93030932-43a3dc80-f66a-11ea-9324-2b2b140290bd.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
That is the number of search results
