### ISSUE TITLE
Feature: In Screencast Mode, keep the current line fixed in the center, so it doesn't get obstructed by the Screencast Mode hotkey displays.

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode#106690]
This is a feature request.

Whenever you are editing a line in screencast mode, sometimes, you trigger hotkeys to initiate some action or command in Visual Studio Code. When this happens, the hotkeys are displayed and overlaid on top of the document editing portion of Visual Studio Code.

It is fine and dandy, but when you are constantly editing text in the area right behind where the hotkey overlays are usually displayed in, it blocks the view of the text editing part, and some viewers actually couldn't see clearly what was being typed out on the screen.

I would like to propose two methods, but I prefer the former, and hence this issue is about that.

1. Have the text editing line always be centered on the screen. That means, when you are scrolling up/down in the document, it's the document that scrolls down/up, while keeping the text cursor and the currently highlighted line fixed in the center of the screen. This mode should only be active when the screencast mode is enabled, and the producer of the livestream wants to have this enabled. But maybe it can be useful as a general feature.

2. Whenever the text editing line is detected to be near the bottom of the Visual Studio Code viewport and hotkeys are triggered, instead of displaying the hotkeys in the usual areas, display the hotkeys in the upper portion of the viewport, where it won't obstruct the text cursor and the edited text.

I don't know if No. 2 will work, considering that there are multiple screen resolutions to take into account, and whatnot, but I think that, by keeping the current line centered on the screen at all times when editing the document, it makes the screencast mode more obvious to the livestream viewers and the hotkey displays won't obstruct their viewing experiences.

When I say "current line" or "currently highlighted line", I am referring to the line where the text cursor is on at that point in time. For me, Visual Studio Code highlights or lightens up the current line where the text cursor is on, so I call it "currently highlighted line".

Thoughts?

**Comment by lszomoru** [comment]
Thank you very much for taking the time to write up the feature request and thinking about possible solutions. Overall, I feel that it would be quite confusing if the screencast overlay would jump around the screen depending on the position of the text that you are editing. Have you explored using the `screencastMode.verticalOffset` setting to place the screencast overlay at the top of the screen (ex: 80, 85)?

**Comment by tommai78101** [comment]
I'll try that. I wasn't aware of this option yet, and will let you know if it's acceptable to the viewers.

**Comment by lszomoru** [comment]
Spoke with @alexdima who owns the editor and option #1 seems like a valid feature request so labeling the issue accordingly.

**Comment by tommai78101** [comment]
@lszomoru By the way, thanks for the `screencastMode.verticalOffset` suggestion. I believed this might work, and it probably just needs some more tweaking to make sure it doesn't obstruct the user while editing text in the viewport.

**Comment by ArturoDent** [comment]
There is a way to get this to work now.  Try this setting:

      "editor.cursorSurroundingLines": 500,
 
Set that to some high enough number and the current line will stay centered.

**Comment by tommai78101** [comment]
@ArturoDent Oooh, this is nice!
