### ISSUE TITLE
[v1.49] Cannot authenticate proxies

### ISSUE THREAD

**Issue by matthewkwong2** [microsoft/vscode#106625]
First of all, why does the proxy dialogue breaks every time when there is a minor update release.

The proxy dialogue flashes and disappeared right after the VS Code is launched.

- VSCode Version: 1.49
- OS Version: Windows 10

Steps to Reproduce:
1. Install VS Code 1.49

**Comment by gjsjohnmurray** [comment]
/duplicate of #106434. Expect a recovery release soon. Meanwhile use Insiders if you can.
