### ISSUE TITLE
No Thing Download and no thig to run properly

### ISSUE THREAD

**Issue by dhruvbhaiji** [microsoft/vscode#106621]
Issue Type: <b>Bug</b>

please reset to default setting my vs code 

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.32GB free)|
|Process Argv|--crash-reporter-id 2c438424-ce95-40c8-8b1a-af5fc930821b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details>

**Comment by sbatten** [comment]
1. Open file explorer
2. Navigate to `%AppData%`
3. rename `Code` to `Code.bak`
4. Try relaunching code


`Code.bak` contains your old configuration. You can delete it if it is no longer required.
