### ISSUE TITLE
Unable to debug electron app / nodeVersionHint workaround no longer works

### ISSUE THREAD

**Issue by andyboyne** [microsoft/vscode#106634]
VSCode Version: 1.49.0
OS Version: Windows

https://github.com/microsoft/vscode/issues/102035
https://github.com/microsoft/vscode/issues/102099
https://github.com/microsoft/vscode-js-debug/issues/663

I upgraded to 1.49.0 and I am no longer able to start my application due to the debugger falling over. It falls over in the same way as described in the issues listed above.  It seems to be the same node version detection issue as before. I am launching an Electron 5 application and have node 14 on the path.

Previously, we could set nodeVersionHint: 10 to workaround this issue.  This no longer works.

**Comment by connor4312** [comment]
Does setting `debug.javascript.usePreviewAutoAttach: false` in your user settings fix this for you?

**Comment by andyboyne** [comment]
Hi,

 No it still fails. I tried this setting with and without the nodeVersionHint and it fails in both cases.

**Comment by connor4312** [comment]
Thanks for the issue. I'm not able to repro this, can you share a trace log so I can see exactly what's happening?

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by connor4312** [comment]
Thanks, fixed in https://github.com/microsoft/vscode-js-debug/commit/b5a01cfa174d7ba681c814122fbf1e0a687f20ba

**Comment by andyboyne** [comment]
Many thanks, much appreciated 👍
