### ISSUE TITLE
Geting Error 'Cannot read property'

### ISSUE THREAD

**Issue by prasoon-salesforce** [microsoft/vscode#106641]
Issue Type: <b>Bug</b>

Install Visual Studio Code > Create a New Project with Manifest > Authorize an Org > Right Click Package under Manifest > Choose 'SFDX: Retrive Source in Manifest from Org' and I am getting error continuously. Error is : 

Cannot read property 'record' of undefined. And debug is redirecting to the package which has been created by VS Code in the Step : ' Create a Project with Manifest'.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.82GB free)|
|Process Argv|--crash-reporter-id 91c08cea-dc7d-4e44-ae1e-1b4005d3cb69|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-soql-editor|all|0.3.3
vscode-eslint|dba|2.1.7
dx-code-companion|Moh|0.4.5
salesforce-vscode-slds|sal|1.2.0
salesforcedx-vscode|sal|49.7.0
salesforcedx-vscode-apex|sal|49.7.0
salesforcedx-vscode-apex-debugger|sal|49.7.0
salesforcedx-vscode-apex-replay-debugger|sal|49.7.0
salesforcedx-vscode-core|sal|49.7.0
salesforcedx-vscode-lightning|sal|49.7.0
salesforcedx-vscode-lwc|sal|49.7.0
salesforcedx-vscode-visualforce|sal|49.7.0

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension Please report this to the authors of the SFDX extension.
