### ISSUE TITLE
Code Navigation, Suggestions not working in VS Code

### ISSUE THREAD

**Issue by bala-suresh** [microsoft/vscode#106628]
Issue Type: <b>Bug</b>

Hi,  I am facing issue with Code Navigation on Visual Studio code. I am using TypeScript for React Native and i installed all required extensions support. but the code navigation, suggestions, and related stuff not working. Can i get any help on this. Thank you.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.15GB free)|
|Process Argv|--crash-reporter-id 05889dcf-b03a-47b6-b10f-58dce41c3844|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
es7-react-js-snippets|dsz|3.0.0
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.6.0
code-runner|for|0.11.0
beautify|Hoo|1.5.0
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
debugger-for-chrome|msj|4.12.10
vscode-react-native|msj|0.17.0
vetur|oct|0.27.3
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|2.1.5
vscode-status-bar-format-toggle|tom|2.0.0
code-navigation|vik|0.2.0
vscodeintellicode|Vis|1.2.10
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also, please share example code that demonstrates the issue

**Comment by thuann-vn** [comment]
Humm, I'm facing the same bug. The weird thing is it only happens on one project. Tried with other Project and it working okay.
