### ISSUE TITLE
Highlighting commit message produces weird symbols

### ISSUE THREAD

**Issue by mbs-zanas-stundys** [microsoft/vscode#106629]
- VSCode Version: 1.49.0
- OS Version: macOS Catalina 10.15.6 (19G2021)

Steps to Reproduce:

1. Enter a commit message
2. Highlight the entered text

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/41042117/93057065-fd547a80-f675-11ea-8b7b-9cb9ecf90020.png)

**Comment by rebornix** [comment]
@mbs-zanas-stundys I'm not able to reproduce this issue, can you confirm if you are still seeing this issue everytime?

**Comment by mbs-zanas-stundys** [comment]
Nope, I can't reproduce it anymore 👍  Closing the issue...
