### ISSUE TITLE
SSL Connection Errors when attempting to authenticate with Live Share

### ISSUE THREAD

**Issue by rigrassm** [microsoft/vscode#106689]
- VSCode Version: 1.49.0
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Click the Liveshare Extension
2. Click the "Sign in with Github" button
3. After authorizing access to Github, the browser redirects to `https://prod.liveshare.vsengsaas.visualstudio.com/auth/identity/github/?redirect=vscode://ms-vsliveshare.vsliveshare/signin` where you will recieve the error shown below.

```
Secure Connection Failed

An error occurred during a connection to prod.liveshare.vsengsaas.visualstudio.com. PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

Does this issue occur when all extensions are disabled?: N/A - The issue is part of the Live Share Extensions core functionality

This has been tested using multiple browsers (Firefox Developer Edition and Safari) and I have another colleague who is experiencing the exact same issue.

**Comment by RMacfarlane** [comment]
@olegoid Do you know who owns this url/where this issue should be transferred?

**Comment by matttrach** [comment]
This appears to have been resolved in https://github.com/MicrosoftDocs/live-share/issues/3833

**Comment by rigrassm** [comment]
Yup, looks to be fixed now. Gonna close this out now as it looks like this belonged in the live-share extension repo anyways.
