### ISSUE TITLE
Clicking string in debugger get stuck with "unexpected identifier" error

### ISSUE THREAD

**Issue by georgeedwards** [Microsoft/vscode#10666]
- VSCode Version: **1.4.0**
- OS Version: Windows 10 pro

Steps to Reproduce:

1. Debug an (in my case nodeJS) app and trigger a breakpoint
2. Click on a string value in Variables > Local, such that you can edit or select it's contents
3. Click away having not made any modification to the variables content
4. Get irritated by the unexpected identifier error that stops you doing anything else ...

[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/oPt1B.gif

**Comment by alexandrudima** [comment]
fyi @weinand

**Comment by weinand** [comment]
This problem occurs if the value of a string contains an escaped string delimiter (single or double quote) character:
```js
var a = "hello\"world";
var b = 'hello\'world';
var c = 'hello\"world';
``
