### ISSUE TITLE
cursor should follow the reference in peek view when set "editor.peekWidgetDefaultFocus": "editor"

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#106681]
```
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```
Steps to Reproduce:

1. set "editor.peekWidgetDefaultFocus": "editor"
2. right click and select `Go to references`
3. select another reference item
4. the cursor just disappear, but I think should move to the current reference

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by jrieken** [comment]
> select another reference item

And then? You didn't write what you expect to happen and what actually happens

**Comment by tjx666** [comment]
> > select another reference item
> 
> And then? You didn't write what you expect to happen and what actually happens


Sorry, I  have add the 4th step to reproduce.

**Comment by jrieken** [comment]
> the cursor just disappear, but I think should move to the current reference

No, it cannot do that automatically because then keyboard navigation in the tree would be broken. There is the `togglePeekWidgetFocus`-command (`cmd+k f2`) to toggle focus between the two sides.
