### ISSUE TITLE
Find full path for executables for `process` task on OSs other than Windows

### ISSUE THREAD

**Issue by shakir-timur** [microsoft/vscode#106661]
- VSCode Version: 1.49.0
- OS Version: Debian GNU/Linux 10 (x64 5.7.0-0.bpo.2-amd64)

Steps to Reproduce:

1. Install VSCode and C# Omnisharp extension.
2. Install dotnet SDK.
3. Create a console app project in any folder ("dotnet new console" command).
4. Open this folder in VSCode.
5. Wait for editor to download required components.
6. Select "Run - Start Debugging" or press F5. Agree to add required assets.
7.  Select "Run - Start Debugging" or press F5 again.

Does this issue occur when all extensions are disabled?: Yes

![Screenshot from 2020-09-14 16-58-12](https://user-images.githubusercontent.com/43072674/93097226-f8132200-f6ad-11ea-8508-87a38c91d687.png)

I've started to get this error some time ago. When I'm trying to run any task I get a message:
"The terminal process failed to launch: Path to shell executable "dotnet" is not a file of a symlink."

I tried uninstalling the editor and .Net SDK and installing it again. Also tried to replace the symlink "/usr/bin/dotnet" manually, but problem remains. 

This problem only appears when trying to run some tasks from menu/button/key. If I type the command manually it works Ok.

This is also mentioned here:
https://stackoverflow.com/questions/63088161/visual-studio-code-c-sharp-debugging-problem-the-terminal-process-failed-to-lau
The OP's workaround is to replace the command "dotnet" with "/usr/bin/dotnet" in "tasks.json" file (worked for me too).

**Comment by shakir-timur** [comment]
Today the problem disappeared after another clean install and removing all vscode and omnisharp config folders from user directory.

**Comment by alexr00** [comment]
If you run that same command in the integrated terminal (not using tasks) does it work?

**Comment by shakir-timur** [comment]
> If you run that same command in the integrated terminal (not using tasks) does it work?

Yes, it worked when typing command directly. Problem was only with commands / hotkeys

**Comment by alexr00** [comment]
How are you launching VS Code?
How did you install VS Code?
If you open the developer tools (command Developer: Toggle developer tools) and in the console run `process.env.Path` is the path to `dotnet` in there?

**Comment by shakir-timur** [comment]
Launching from gnome application menu.
Installed first with deb package from Microsoft website, following installations were updates via package manager (Synaptic).
`process.env.PATH` has the directory with `dotnet` symlink

**Comment by alexr00** [comment]
Ok, next time you see the problem, if you could check `process.env.Path` from the VS Code developer tools again that might provide a clue.

**Comment by shakir-timur** [comment]
> Ok, next time you see the problem, if you could check `process.env.Path` from the VS Code developer tools again that might provide a clue.

Actually last time problem was present, I forgot that I changed the command name as workaround suggests.

**Comment by shakir-timur** [comment]
I've made a virualbox image with a snapshot of bug, if needed. It's ~2,5 Gb compressed. 

https://drive.google.com/file/d/1Y0wFdgPwGqH_-WfbVAkRKzYg2uCSTS5o/

**Comment by isandburn** [comment]
I was getting this error as well and found this thread while researching issue... i realized that i opened VS Code (~/some/dir code .") in bash terminal from different directory than the project i was working in, as "dotnet new" had yet to create the project's directory; once i created to the dir/project, wrote a little code, and tried to build, i got the reported error... fast forward, i closed out of VS Code and reopened properly in the project's directory and everything built fine

**Comment by shakir-timur** [comment]
>  opened VS Code (~/some/dir code .") in bash terminal from different directory than the project i was working in

Indeed, this worked for me too. Yet if you launch VSC from application list, problem remains.

**Comment by caglardursun** [comment]
Count me in ! Do not close this bug ! The problem exists in my linux distro too :) I just faced it today.
`dotnet` command is fine, `which dotnet` executable file location is fine (which is in my path) 

The problem can be solve only editing task.json write the whole path of dotnet in my case `/usr/bin/dotnet`

tasks.json file should look like this : 
```javascript

{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "/usr/bin/dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/amazon_interview.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "/usr/bin/dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/amazon_interview.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "watch",
            "command": "/usr/bin/dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "${workspaceFolder}/amazon_interview.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}

```

**Comment by alexr00** [comment]
Next time you see the problem, if you could check process.env.Path from the VS Code developer tools again that might provide a clue.

**Comment by flabbyPatty** [comment]
In `tasks.json` replace `command:"dotnet",type:"process"` by `command:"dotnet",type:"shell"`

**Comment by jinyanghuang** [comment]
> In `tasks.json` replace `command:"dotnet",type:"process"` by `command:"dotnet",type:"shell"`

That did the trick. Thank you!

**Comment by caglardursun** [comment]
@alexr00 If you are talking about the developer console, it's undefined wrt. you wrote the last part `Path` 

It sould be `process.env.PATH` and looks fine 

"/home/caglar/.cargo/bin:/home/caglar/.cargo/bin:/home/caglar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/caglar/.dotnet/tools:/opt/bashtop:/opt/netcoredbg:/home/caglar/.local/bin:/home/caglar/.local/bin:/opt/qt/5.15.1/gcc_64/bin:/opt/anaconda3/bin:/home/caglar/.fzf/bin"

Here is the full env data
```javascript
{
BASE16_THEME: "onedark"
CHROME_DESKTOP: "code-url-handler.desktop"
COLORTERM: "truecolor"
COMPlus_PerfMapEnabled: "1"
DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1000/bus"
DEFAULTS_PATH: "/usr/share/gconf/ubuntu.default.path"
DESKTOP_SESSION: "custom"
DISPLAY: ":1"
EDITOR: "mvim"
GDMSESSION: "custom"
GIO_LAUNCHED_DESKTOP_FILE: "/usr/share/applications/code.desktop"
GIO_LAUNCHED_DESKTOP_FILE_PID: "15309"
GJS_DEBUG_OUTPUT: "stderr"
GJS_DEBUG_TOPICS: "JS ERROR;JS LOG"
GNOME_DESKTOP_SESSION_ID: "this-is-deprecated"
GNOME_SHELL_SESSION_MODE: "ubuntu"
GPG_AGENT_INFO: "/run/user/1000/gnupg/S.gpg-agent:0:1"
GTK_MODULES: "gail:atk-bridge"
HOME: "/home/caglar"
IM_CONFIG_PHASE: "1"
INVOCATION_ID: "31e483b298c94e7e95b46325625ddaf6"
JOURNAL_STREAM: "8:48792"
LANG: "en_US.UTF-8"
LC_ADDRESS: "tr_TR.UTF-8"
LC_IDENTIFICATION: "tr_TR.UTF-8"
LC_MEASUREMENT: "tr_TR.UTF-8"
LC_MONETARY: "tr_TR.UTF-8"
LC_NAME: "tr_TR.UTF-8"
LC_NUMERIC: "tr_TR.UTF-8"
LC_PAPER: "tr_TR.UTF-8"
LC_TELEPHONE: "tr_TR.UTF-8"
LC_TIME: "tr_TR.UTF-8"
LESS: "-R"
LESS_TERMCAP_mb: "[01;31m"
LESS_TERMCAP_md: "[01;31m"
LESS_TERMCAP_me: "[0m"
LESS_TERMCAP_se: "[0m"
LESS_TERMCAP_so: "[01;44;33m"
LESS_TERMCAP_ue: "[0m"
LESS_TERMCAP_us: "[01;32m"
LOGNAME: "caglar"
LSCOLORS: "Gxfxcxdxbxegedabagacad"
LS_COLORS: ""
MANAGERPID: "1763"
MANDATORY_PATH: "/usr/share/gconf/ubuntu.mandatory.path"
OLDPWD: "/home/caglar"
ORIGINAL_XDG_CURRENT_DESKTOP: "ubuntu:GNOME"
P9K_SSH: "0"
PAGER: "less"
PATH: "/home/caglar/.cargo/bin:/home/caglar/.cargo/bin:/home/caglar/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/caglar/.dotnet/tools:/opt/bashtop:/opt/netcoredbg:/home/caglar/.local/bin:/home/caglar/.local/bin:/opt/qt/5.15.1/gcc_64/bin:/opt/anaconda3/bin:/home/caglar/.fzf/bin"
PWD: "/home/caglar"
QT_ACCESSIBILITY: "1"
QT_IM_MODULE: "ibus"
SESSION_MANAGER: "local/g5-5587:@/tmp/.ICE-unix/2051,unix/g5-5587:/tmp/.ICE-unix/2051"
SHELL: "/bin/zsh"
SHLVL: "0"
SSH_AGENT_PID: "2009"
SSH_AUTH_SOCK: "/run/user/1000/keyring/ssh"
USER: "caglar"
USERNAME: "caglar"
VSCODE_IPC_HOOK: "/run/user/1000/vscode-12d119d3-1.53.2-main.sock"
VSCODE_NLS_CONFIG: "{"locale":"en-us","availableLanguages":{},"_languagePackSupport":true}"
VSCODE_NODE_CACHED_DATA_DIR: "/home/caglar/.config/Code/CachedData/622cb03f7e070a9670c94bae1a45d78d7181fbd4"
VSCODE_PID: "15309"
WINDOWPATH: "2"
XAUTHORITY: "/run/user/1000/gdm/Xauthority"
XDG_CONFIG_DIRS: "/etc/xdg/xdg-ubuntu:/etc/xdg"
XDG_CURRENT_DESKTOP: "Unity"
XDG_DATA_DIRS: "/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop"
XDG_MENU_PREFIX: "gnome-"
XDG_RUNTIME_DIR: "/run/user/1000"
XDG_SESSION_CLASS: "user"
XDG_SESSION_DESKTOP: "ubuntu"
XDG_SESSION_TYPE: "x11"
XMODIFIERS: "@im=ibus"
ZSH: "/home/caglar/.oh-my-zsh"
ZSH_TMUX_CONFIG: "/home/caglar/.tmux.conf"
ZSH_TMUX_TERM: "screen"
_: "/usr/share/code/code"
_ZSH_TMUX_FIXED_CONFIG: "/home/caglar/.oh-my-zsh/plugins/tmux/tmux.extra.conf"
}
```

**Comment by alexr00** [comment]
I agree, looks like your PATH is good.

What is the setting `terminal.integrated.inheritEnv` set to? If it's false, then your VS Code terminals won't get inherit that path.

**Comment by shakir-timur** [comment]
> What is the setting terminal.integrated.inheritEnv set to?
Set to true. Changing does not affect the error.

**Comment by alexr00** [comment]
@shakir-timur can you check process.env.PATH from the VS Code developer tools console and share the output from that?

**Comment by shakir-timur** [comment]
> @shakir-timur can you check process.env.PATH from the VS Code developer tools console 

"/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/timur/.dotnet/tools"

It's identical for both cases when it is working or not.

**Comment by alexr00** [comment]
That path should include your path to `dotnet` assuming it's installed in the usual location. Can you run `which dotnet` and share the output so I can make sure that you have `dotnet` in `/usr/bin/dotnet`?

Next, we should check if that `process.env.PATH` is making it to your task.
Add this task to your `tasks.json` file:
```json
		{
			"label": "Echo path",
			"command": "echo $PATH",
			"type": "shell"
		}
```
Run that task and share the output and we'll see if you have the right path for tasks.

**Comment by shakir-timur** [comment]
> Can you run which dotnet and share the output

/usr/bin/dotnet

Running echo task produced following:
```
Executing task: echo $PATH <
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/timur/.dotnet/tools
```

**Comment by alexr00** [comment]
I did some digging, and it looks like this is intentional right now. For `process` tasks on Windows, we find the full path of the executable. We don't do the same on linux.  Seems like we probably could find the executable though.

**Comment by jibbers42** [comment]
I get this error if I launch code from the terminal as `code .` (in my project root folder), but I don't get the error if I launch from Ubuntu Dock (20.04).

`process.env.PATH` when launched from dock:
```
"/home/jibbers42/bin:/home/jibbers42/.nvm/versions/node/v14.16.0/bin:/home/jibbers42/code/go/bin:/usr/local/go/bin:/home/jibbers42/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jibbers42/.dotnet/tools:/home/jibbers42/.dotnet/tools"
```
`process.env.PATH` when launched from terminal:
```
"/home/jibbers42/.nvm/versions/node/v14.16.0/bin:/home/jibbers42/code/go/bin:/usr/local/go/bin:/home/jibbers42/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jibbers42/.dotnet/tools"
```

The paths are different, but both have `/usr/bin`
```
==> which dotnet
/usr/bin/dotnet
```

**Comment by jibbers42** [comment]
> This feature request is now a candidate for our backlog. The community has 60 days to [upvote](https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request) the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).
> 
> Happy Coding!

I realize you have to be an influencer to have smaller quality of life issues considered these days (https://github.com/microsoft/vscode/issues/117847), but is this auto-close policy intended to apply to bugs as well?

**Comment by chevdor** [comment]
I confirm the issue and a workaround. On MacOS, if you open Vscode from the "last open" menu, commands work in the terminal but not from plugins.
If however, you cd into the folder and open vscode from there, everything works fine.

**Comment by mMarcos208** [comment]
> > In `tasks.json` replace `command:"dotnet",type:"process"` by `command:"dotnet",type:"shell"`
> 
> That did the trick. Thank you!

Thank you so much.
