### ISSUE TITLE
Webview content overlaps some other panel borders

### ISSUE THREAD

**Issue by n-gist** [microsoft/vscode#106612]
**Webview content overlaps other panel borders**

Hi! Just noticed this (red arrows).
There is 1px padding/margin noticeable also (green arrow).
It spoils the clarity a bit in some color themes. Does not happen on default theme.
Noticed when was using Git Graph extension, but its author pointed that it happens with other extensions: mhutchie/vscode-git-graph#380

- VSCode Version: 1.49.0 (user setup)
- OS Version: Windows 10

Steps to Reproduce:

1. Open some folder with git repository
2. Install Gist Theme color theme
2. Install Git Graph extension
3. Open Git Graph main window (button in status bar)
4. Open Output panel and sidebar (sidebar is on the right side on screenshots below)

Webview (Git Graph) tab:
![ov1](https://user-images.githubusercontent.com/58081918/93035579-2ddcea00-f65f-11ea-9a20-feb40fd6cd21.png)
File tab:
![ov2](https://user-images.githubusercontent.com/58081918/93035582-30d7da80-f65f-11ea-9a5a-c6c5f73c9e92.png)

**Comment by mjbvz** [comment]
Please file in the issue template

Also which color them are you using?

**Comment by n-gist** [comment]
Updated

**Comment by mjbvz** [comment]
Thanks
