### ISSUE TITLE
Cold Folding Not Working As It Should

### ISSUE THREAD

**Issue by Shubanshii** [microsoft/vscode#106654]
VSCode Version: 1.49.0
OS Version: Windows_NTx64 10.0.18362
Steps to Reproduce:

1. Go to text box of "Code Folding" section of the Interactive Playground.
2. Run Ctrl+K Ctrl+0

Nothing happens.  The Ctrl+Shift+[ and the inverse one work though.

**Comment by aeschli** [comment]
`Ctrl - K Ctrl + 0` works for me, but not `Ctrl + K Ctrl + 1`.

Not sure what's different in the playgorund, @chrmarti  ?
