### ISSUE TITLE
Filter debug parameters broken

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode#106632]
### System information
- VSCode Version: 1.49.0
- OS Version: Ubuntu 18.04

### Problem

I noticed that the filter debug parameters feature is broken in both the python and C++ debuggers.

#### Python script

```python
test = 2
test2 = "Hello"

print(test)
print(test2)
```

#### C++ script

```cpp
#include <iostream>
#include <stdio.h>

using namespace std;

int main()
{
    int n = 100;
    string s = "hello boss";
    cout << s;
    getchar();
    return 0;
}
```

### Expected behaviour

I expected the debug variable filter to work like was explained by @isidorn in [this issue](https://github.com/microsoft/vscode/issues/13201).

![66384609-58d6ac80-e9bf-11e9-9ad0-1bb4c194e31a](https://user-images.githubusercontent.com/17570430/93063638-d77ba580-f676-11ea-8646-ee28fe86f9be.gif)

### Actual behaviour

It, unfortunately, doesn't work in my version.

![problem](https://user-images.githubusercontent.com/17570430/93063060-01809800-f676-11ea-97c0-6bd2d3ffeb15.gif)
![python_problem](https://user-images.githubusercontent.com/17570430/93063065-02b1c500-f676-11ea-8edf-bf6b25011c64.gif)

### Steps to Reproduce:

1. Open the python or c++ example scripts.
2. Place a breakpoint somewhere in the example script.
2. Start a python or C++ debugging session.
3. Try to filter debug variables like was explained in [this issue](https://github.com/microsoft/vscode/issues/13201)

### Other debug questions

**Does this issue occur when all extensions are disabled?:** I can not test this since without the python or C++ extension I am not able to debug python code.

**Does this issue occur in the insiders version?:** Yes

**Version:** 1.50.0-insider
**Commit:** cca20eba8974b1d6b6a9b71bf4e60a29c8f26648
**Date:** 2020-09-14T05:09:13.216Z
**Electron:** 9.3.0
**Chrome:** 83.0.4103.122
**Node.js:** 12.14.1
**V8:** 8.3.110.13-electron.0
**OS:** Linux x64 5.4.26-050426-generic

**Comment by isidorn** [comment]
Thanks for filling this, however this works just fine for me.
Some questions
1. When you type the focus is in the variables view?
2. Do you maybe have a screen reader attached, can you reproduce if you set 	`"editor.accessibilitySupport": "off"` in your settings
3. Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by rickstaa** [comment]
@isidorn thanks a lot for looking into my problem. After your last comment I did some debugging and the feature is broken because I enabled the [VSCodeVim extension](https://github.com/VSCodeVim/Vim). It is related to the following [issue](https://github.com/VSCodeVim/Vim/issues/3997). Sorry for your troubles.

**Comment by isidorn** [comment]
Thanks
