### ISSUE TITLE
File links open as folders

### ISSUE THREAD

**Issue by SPAstef** [microsoft/vscode#106687]
Hello, since a couple days when I get a clickable link to a file (like the one in the picture), VScode opens the parent folder of the file in a new window, and not the file line in the same window as intended:
![image](https://user-images.githubusercontent.com/9153046/93123495-7d0b3500-f6c8-11ea-82f6-54f2efaf9432.png)

**Comment by isidorn** [comment]
Reproducable steps would be great here. Since with this there is nothing we can do. Though that looks like our temrinal thus forwarding to @Tyriar

**Comment by SPAstef** [comment]
Steps to reproduce:
- Open a C/C++ file which fails to compile due to some error
- Compile it through the integrated terminal
- CTRL+Click on the filename/line numbers that cause the error (like in the screenshot)
- A new window gets opened, instead of a new tab (or current tab) jumping at the right position in the file, like it used to do like a few days ago

**Comment by Tyriar** [comment]
What does it show when you hover the file? Also what folder does it open?

**Comment by SPAstef** [comment]
> What does it show when you hover the file? Also what folder does it open?

It shows the text "open this folder in a new window", and it opens the parent folder of the file itself.
It's like if the "engine" that handles this stuff ignores the last part of the file link/path and stops at the parent folder.
