### ISSUE TITLE
Html tag lang attribute rendering error

### ISSUE THREAD

**Issue by varxzy** [microsoft/vscode#106675]
Issue Type: <b>Bug</b>

Rendering error when adding lang attribute to html tag. Please see screenshot.

![image](https://user-images.githubusercontent.com/20296852/93117956-21ee3800-f6f2-11ea-9d79-528a00490742.png)

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.65GB free)|
|Process Argv|--crash-reporter-id bbf411d5-e056-4b03-89e2-20c0f421d254|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
vscode-language-pack-zh-hans|MS-|1.49.1
debugger-for-chrome|msj|4.12.10
vetur|oct|0.27.3
code-settings-sync|Sha|3.4.3
language-stylus|sys|1.11.0
open-in-browser|tec|2.0.0

</details>

**Comment by alexdima** [comment]
@varxzy That looks like something specific to the font you have configured. Perhaps it comes with ligatures? Can you please try changing the font or disabling `editor.fontLigatures` ?

**Comment by varxzy** [comment]
@alexdima As you said, I successfully solved this problem after setting `editor.fontLigatures` to true, thanks!

**Comment by alexdima** [comment]
Let's track in #106583
