### ISSUE TITLE
Add ability for extensions to show collapsible groups of files in the explorer

### ISSUE THREAD

**Issue by Merlin04** [microsoft/vscode#106608]
In some frameworks there are multiple files associated with one main file that are in the same directory (like `.razor` and `.razor.cs`). This feature would allow extensions to define collapsible groups that could show up in the explorer, making something like this:
![image](https://user-images.githubusercontent.com/11800751/93031647-6b9b2d80-f5e1-11ea-8c78-c8f9526d7e01.png)
Look something like this:
![image](https://user-images.githubusercontent.com/11800751/93031826-9a65d380-f5e2-11ea-8ee0-7bbc6d4f13f7.png)

Here's an example from JetBrains Rider:
![image](https://user-images.githubusercontent.com/11800751/93031935-69d26980-f5e3-11ea-9465-ff21184d7b01.png)

Currently the way to do this is to define a custom explorer view but then I have to make all of the code for file management (copy, paste, delete, rename, drag and drop to new folders, opening file in editor when clicked, etc).

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/6328
