### ISSUE TITLE
vscode hangs when inputting some words after opening user settings file from command palette

### ISSUE THREAD

**Issue by canfoderiskii** [Microsoft/vscode#10664]
- VSCode Version: 1.4
- OS Version: win 10 & win 7 (both has the same issue)

Steps to Reproduce: 

1. ctrl + shift + p, open command pallete
2. call "Preferences: Open User Settings", then editor will open 2 views, one is default settings, the other is user settings.
3. there are 2 scenes I know to trigger this issue: 
    - <scene 1> keep typing some random words inside user settings json file then the vscode will hangs eventually, and i cannot type or modify any character any more.
    - <scene 2> close all setting files, then open up a new old or new file, then keep typing some random words in it, the vscode will hangs eventually, and i cannot type or modify any character any more.

phenomenon:

1. When editor is hanging, i found that one of editor's process "Code.exe" occupies many CPU resources. If i kill that process, the editor will come back to life, and i can continue to type in characters, though vscode pop out these messages:
- Error from the extension host: channel closed
- Extension host terminated unexpectedly. Please reload the window to recover.
2. If i directly open settings.json to editor's view, vscode does not hang.

This issue seems have something with some extension, but i don't know which is. I installed many extensions, it'll be horrible if i enable/disable one by one and test. Is there any fast way to figure out what happed and who blocked the vscode?

**Comment by alexandrudima** [comment]
@canfoderiskii Can you do a `dir` where extensions are installed in `C:\Users\[username]\.vscode\extensions`.

You can try moving folders out of there and moving them back in to do impromptuu troubleshooting

**Comment by canfoderiskii** [comment]
@alexandrudima I have these extensions installed...

![t](https://cloud.githubusercontent.com/assets/10685920/17807753/1ef1243e-663f-11e6-8b4c-33e4889727ff.png)

**Comment by canfoderiskii** [comment]
@alexandrudima I found it, the extension "vscode-todo-parser" hangs the vscode.I'll report a issue to that extension

**Comment by dbaeumer** [comment]
@canfoderiskii I will close the issue since the issue has to be fixed in vscode-todo-parser. Have you opened and issue here: https://github.com/kantlove/vscode-todo-parser

**Comment by canfoderiskii** [comment]
@dbaeumer  okay
