### ISSUE TITLE
Font size for the side panel cannot be changed

### ISSUE THREAD

**Issue by KYSSelectron** [Microsoft/vscode#10660]
[Feature request]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:
1. Adjust font size of the code editor
2. See that in the lateral panel (files, search, ...) the code size is not the one specified above

It would be great to at least have consistency with the font size. Right now, while I am searching some variables along all my files, I have almost half of the display busy with the search results because font size is too big and I cannot make it smaller (or at least I haven't found a way to change it).

The code editor panel though is fantastic with the adjusted font size.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/519
