### ISSUE TITLE
seementic element 

### ISSUE THREAD

**Issue by Pritidesai557** [microsoft/vscode#106753]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Html Sementic Tags</title>
</head>

<body>
    <h3>Sementics Elements</h3>
    
    <details>
        <summary>  Make your Study easily with us</summary>
        <p>One of the best Data Science and web portal
            where you can learn good skills of programming.</p> 
    </details>
        
</body>

</html>

**Comment by aeschli** [comment]
Please add more details...
