### ISSUE TITLE
[themes] Diff highlighting breaks with Quiet Light theme

### ISSUE THREAD

**Issue by jspenguin2017** [microsoft/vscode#106707]
- VSCode Version: 1.49.0
- OS Version: Windows 10  2004

Steps to Reproduce:

1. Change VS Code to the built-in Quiet Light theme
2. Save the text below as `test.diff` and open it with VS Code

```diff
--- a.txt	2020-09-14 19:23:42.699158000 -0600
+++ b.txt	2020-09-14 19:23:41.501314200 -0600
@@ -1 +1 @@
-test
+hello world
```

3. Observe that with Quiet Light theme, syntax highlighting is not working: 
![image](https://user-images.githubusercontent.com/7283682/93154364-b2ac2000-f6c0-11ea-985b-69eb8a0abb74.png)

Does this issue occur when all extensions are disabled?: Yes

Tested with all extensions disabled, also with the insider build, still have this issue. Note that with other themes, the syntax highlighting is working. Looks like this is an issue with the Quiet Light theme. 
![image](https://user-images.githubusercontent.com/7283682/93154177-3c0f2280-f6c0-11ea-841b-33d293d268d3.png)

**Comment by alisonnoyes** [comment]
Going to try this issue for Grace Hopper OSD.

**Comment by aeschli** [comment]
Cool. You find the Quiet Light theme here: https://github.com/microsoft/vscode/blob/master/extensions/theme-quietlight/themes/quietlight-color-theme.json
I recommend to try out the changes in the settings first. See https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

**Comment by alisonnoyes** [comment]
It seems like the Quiet Light theme just didn't have any definition for what color the insertions/deletions/etc should be so by adding those the issue will be fixed.  Is there some sort of guideline for what these colors should be?

**Comment by aeschli** [comment]
Just can make a proposal and @misolori (our UX guy) can review.
