### ISSUE TITLE
"NPM SCRIPTS" update/refresh is not working

### ISSUE THREAD

**Issue by qwabra** [microsoft/vscode#106780]
# "NPM SCRIPTS" update/refresh is not working

- VSCode Version: 1.49.0 (windows)
- OS Version: Alpine (WSL1), windows 10

Does this issue occur when all extensions are disabled?: Yes/No

## Steps to Reproduce:

1.`code ./test` -> create `package.json`
```json
{
    "scripts": {
        "t1": "echo 't1'",
    }
}
```
2. edit `package.json`
```json
{
    "scripts": {
        "t1": "echo 't1'",
        "t2": "echo 't2'"
    }
}
```

## expected:

auto update scripts list in the left panel "NPM SCRIPTS" (or by click "refresh" button) 

![npm scripts bug](https://user-images.githubusercontent.com/5960180/93238036-8f00dc80-f789-11ea-9f51-8737bea11324.PNG)

**Comment by alexr00** [comment]
I'm not able to reproduce this problem. When I add a new script, the view updates automatically. Can you share your settings.json file?

**Comment by qwabra** [comment]
hmm, u right, `files.watcherExclude` is block it.
```json
{
    "files.watcherExclude": {
        "**/*": true
    }
}
```

**But**, even so i think "refresh" button should work !??

**Comment by qwabra** [comment]
![Снимок](https://user-images.githubusercontent.com/5960180/93443292-ecf00a00-f8d8-11ea-9d05-cf4fa4e3e492.PNG)

**Comment by alexr00** [comment]
The way it's written, the view actually shouldn't be updating. But I agree that this is extremely confusing and unexpected. The expectation is that when the refresh button is used, the view should update.
