### ISSUE TITLE
Blurry effect on interface

### ISSUE THREAD

**Issue by ahnaf00** [microsoft/vscode#106768]
Issue Type: <b>Bug</b>

Hello there
I started to use vs code a few days letter.Here when I start writing code  it becomes blurry from  all the side.It's very irritating.I want a solution

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.86GB free)|
|Process Argv|--crash-reporter-id 1ad61056-fa84-4348-a70e-c20839b12651|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please provide screenshot of the problem?
Is it reproducible if you close VS Code and start with `code --disable-gpu`?
