### ISSUE TITLE
[Codespaces] Make creation log sections easier to read

### ISSUE THREAD

**Issue by mchelen-gov** [microsoft/vscode#106777]
When viewing the creation log for a Codespace, each section (Initialize, Build, Configure, etc) is extremely small even when expanded. For a post creation step like `yarn install` the output is extremely long and difficult to navigate. 
![image](https://user-images.githubusercontent.com/63597655/93235481-9dc89e80-f74b-11ea-8d76-fb2c2b7ca802.png)

It's possible to redirect this output to a log file, but that requires an extra step is problematic when trying to debug the system itself.
The creation log sections should be larger & easier to read, maybe move them into Output console or similar?

**Comment by aeschli** [comment]
Please file this against https://github.com/MicrosoftDocs/vscodespaces

**Comment by mchelen-gov** [comment]
Duplicates https://github.com/MicrosoftDocs/vscodespaces/issues/481
