### ISSUE TITLE
Regex não funciona devidamente no replace

### ISSUE THREAD

**Issue by emanuelEstudo** [Microsoft/vscode#10675]
- VSCode Version: 1.4.0
- OS Version: windows 7 service pack 1

Steps to Reproduce:

a opção de usar $& no regex não funciona quando usada find

**Comment by alexandrudima** [comment]
Translation: "the option to use $ & the regex does not work when used find".

@emanuelEstudo Can you please provide an example regex that does not work for you? Do you use the global search or the editor find:

![image](https://cloud.githubusercontent.com/assets/5047891/17800412/4ab56406-65e3-11e6-8d26-d8a1755e2646.png)


OR


![image](https://cloud.githubusercontent.com/assets/5047891/17800414/52df0d3a-65e3-11e6-888d-fb404d38f85a.png)

**Comment by dbaeumer** [comment]
Closing. Haven't received any response in 14 days.
