### ISSUE TITLE
autopep8 Error Message (Errorno2)

### ISSUE THREAD

**Issue by NimiRock** [microsoft/vscode#106729]
- VSCode Version: version 1.49
- OS Version: Windows 10 Home x64

Steps to Reproduce:

1. Can't install autopep8
2. No such file or directory [Errno2], when using pip install -U autopep8 --user

Does this issue occur when all extensions are disabled?: Yes
![autopep8 Error Message](https://user-images.githubusercontent.com/68594149/93179721-be3e2c00-f73e-11ea-88ff-de7628004edb.jpg)

**Comment by aeschli** [comment]
Please file the issue against the extension:
https://marketplace.visualstudio.com/items?itemName=himanoa.Python-autopep8&ssr=false#review-details
