### ISSUE TITLE
My project's root directory got deleted during the execution of Python Debugging Session. 

### ISSUE THREAD

**Issue by codekoriko** [microsoft/vscode#106743]
It's the second time it happened. First time was a fresh project so as I didn't investigate further. I thought I messed up somehow. 

Second time I lost some datasets and got close to lose some code. I found the culprit so I hope it won't to me a third time.

Version: 1.48.2 (system setup)
Electron: 7.3.2
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Run a debugging session, that open a fresh python debug console terminal
2. Once debugging session terminate
3. Typing in python debug console terminal:
`rm some/sub/dir/in/my/project -rf`
4. Not pressing enter, so the command don't execute but sit there
5. Launch a new debugging session

VS code will then reuse the 'python debug console terminal' previously open, with my un-executed command still sitting there. 

It do its business as usually and inputting:
`"cd /home/my_username/my_project_root ; env /home/[...]"` 

resulting the command:
`rm some/sub/dir/in/my/project -rf cd /home/my_username/my_project_root ; env /home/[...]`

and Poof my whole project is gone ☠️ 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
We should clear any input before executing a command.

**Comment by psychonaute** [comment]
> We should clear any input before executing a command. 

I agree, I'm quite suprise it was not the case already. 

Waiting for the fix. There is the possibility of setting the debug console to be spawn in the debug output tab.

In ’.vscode/launch.json:’

’"console": "internalConsole"’

**Comment by weinand** [comment]
I'm now cancelling the input with Control-C. This should work on all platforms.

**Comment by psychonaute** [comment]
Perfect, thanks for your work

**Comment by alexr00** [comment]
The fix for this causes https://github.com/microsoft/vscode/issues/107969
Reverting for the release.

**Comment by nmoreaud** [comment]
Same thing happens with the C++/CMake extension when pressing F5.
