### ISSUE TITLE
MacOS Catalina Update: Service is disabled and cannot be executed

### ISSUE THREAD

**Issue by callmeberzerker** [microsoft/vscode#106742]
Issue Type: <b>Bug</b>

I can't figure out why automatic updates don't work on my catalina, and have to re-download the whole binary whenever there is a new release of vscode... I don't have this issue with any other macos app

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (1.19GB free)|
|Process Argv|--crash-reporter-id 53aea4e5-105c-4792-935d-8567b4e4efe0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-postgres|cko|1.1.11
gitlens|eam|10.2.2
prettier-vscode|esb|5.6.0
go|gol|0.16.2
vscode-styled-components|jpo|0.0.31
vscode-docker|ms-|1.5.0
svelte-vscode|sve|101.13.1
vscode-icons|vsc|10.2.0
markdown-all-in-one|yzh|3.3.0

(1 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
Possible duplicate issue, can you follow the steps at https://github.com/microsoft/vscode/issues/106258#issuecomment-689126228 and provide the required details. Thanks!

**Comment by callmeberzerker** [comment]
Just left a comment there, but it seems the bot closed it already?

**Comment by deepak1556** [comment]
Can you attach the log when launching with `code --verbose` and clicking update now action.

**Comment by callmeberzerker** [comment]
Hi @deepak1556 

Here you go :)

```
[79162:0917/181529.391591:INFO:CONSOLE(1705)] "%cTRACE color: #888 CommandService#executeCommand update.check", source: file:///Users/smarkovs/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1705)
[79162:0917/181529.391766:INFO:CONSOLE(1705)] "%cTRACE color: #888 telemetry/workbenchActionExecuted [object Object]", source: file:///Users/smarkovs/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (1705)
[main 2020-09-17T16:15:29.392Z] update#checkForUpdates, state =  idle
[main 2020-09-17T16:15:29.392Z] update#setState checking for updates
[main 2020-09-17T16:15:29.393Z] UpdateService error: The command is disabled and cannot be executed
[main 2020-09-17T16:15:29.393Z] update#setState idle
[79162:0917/181529.397747:INFO:CONSOLE(3066)] "The command is disabled and cannot be executed", source: file:///Users/smarkovs/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (3066)
[main 2020-09-17T16:15:29.602Z] menubarService#updateMenubar 1
[main 2020-09-17T16:15:51.618Z] update#checkForUpdates, state =  idle
[main 2020-09-17T16:15:51.618Z] update#setState checking for updates
[main 2020-09-17T16:15:51.620Z] UpdateService error: The command is disabled and cannot be executed
[main 2020-09-17T16:15:51.620Z] update#setState idle
```

**Comment by joaomoreno** [comment]
ping @deepak1556

**Comment by callmeberzerker** [comment]
This should be open - what more info can I provide than this? :)

**Comment by deepak1556** [comment]
Sorry missed this, related https://github.com/electron/electron/issues/7792 . The issue upstream was when update checker function was called in the middle of processing an update request. 

Can you find `ShipIt_stderr.log, ShipIt_stdout.log` on your system, you had previously mentioned that they are found https://github.com/microsoft/vscode/issues/106258#issuecomment-694035247 . Without the logs it would be hard to say what the issue is here.

Couple of options to try,

1) clear com.microsoft.VSCode.ShipIt/ folder if there is one and Reinstall vscode
2) Check if the issue persists with insiders release flavor https://code.visualstudio.com/insiders.
