### ISSUE TITLE
Typescript's language-defined auto-closing brackets incorrectly treat template strings like whitespace

### ISSUE THREAD

**Issue by thw0rted** [microsoft/vscode#106778]
- VSCode Version: 1.49
- OS Version: Windows 10 (2004)

Steps to Reproduce:

1. Open a Typescript file
2. Enter `window` on a new line
3. Place your cursor at the start of the line and start typing `atob(`
4. When you type the open paren, a close-paren is not inserted, resulting in `atob(|window` (where the pipe character is your cursor)
5. Repeat steps 2-3 using `"window"` in double quotes, or single quotes in place of `window`.
6. No close-paren is inserted, resulting in `atob(|"window"`.
7. Repeat steps 2-3 using `` `window` `` in place of `window`.
8. When you type the open paren, a close-paren is inserted, leaving you with `` atob(|)`window` `` 

Does this issue occur when all extensions are disabled?: Yes

**Comment by jeanp413** [comment]
I took a look at this and this is due to `` ` `` being included in the `autoCloseBefore` language configuration attribute
https://github.com/microsoft/vscode/blob/d19c4ec92c4270d1778ba91c694097cd839adc10/extensions/javascript/javascript-language-configuration.json#L28

not sure if that's the desired behavior but I'll make a PR removing the backtick from `autoCloseBefore`

**Comment by thw0rted** [comment]
I'm interested to [know why the fence was there before we knock it down](https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence) -- do you have any idea why backtick would have been on that list but not any other quote types?  It looks like the line was added by @JacksonKearl , maybe they have some feedback?

**Comment by JacksonKearl** [comment]
`autoCloseBefore` typically should be chars that cannot begin expressions, an exception was made for backtics because writing a brace here:
```
`myTemplate|`
```
should autoclose. I believe this to be a more common use case than what this PR is trying to address. 

Discussed at the time: https://github.com/microsoft/vscode/pull/52634#issuecomment-407313593

**Comment by thw0rted** [comment]
Ah, now I understand.  I think the ideal behavior might not be possible to implement with the mechanisms currently in place.  I would argue that we *don't* want auto-close for
* `` |`myTemplate` `` , when typing any bracket, because you are outside the template string
* `{` anywhere inside the template unless immediately preceded by a `$`
* `` `myTemplate|` ``, when typing `(` or `[`, because you are still in the literal part of the string

But we do want auto-close for
* `` `${myTemplate|` ``, when typing `(` or `[`, because you are writing a statement, not a literal

Am I right to guess that the engine doesn't keep/expose enough state context to differentiate these cases?

**Comment by jeanp413** [comment]
> 
> 
> `autoCloseBefore` typically should be chars that cannot begin expressions, an exception was made for backtics because writing a brace here:
> 
> ```
> `myTemplate|`
> ```
> 
> should autoclose. I believe this to be a more common use case than what this PR is trying to address.

Ah I see, I had a hunch it was there for a reason, I'll close my PR then.

**Comment by JacksonKearl** [comment]
> Am I right to guess that the engine doesn't keep/expose enough state context to differentiate these cases?

Yeah, no way to do that right now. I could in theory see an additional `onlyBefore` property added to the `autoClosingPairs` field, so for instance the JS config might become:
```
	"autoClosingPairs": [
		{ "onlyBefore": ";:.,=}])>` \n\t", "open": "{", "close": "}" },
		{ "onlyBefore": ";:.,=}])> \n\t", "open": "[", "close": "]" },
		{ "onlyBefore": ";:.,=}])> \n\t", "open": "(", "close": ")" },
		{ "onlyBefore": ";:.,=}])> \n\t", "open": "'", "close": "'", "notIn": ["string", "comment"] },
		{ "onlyBefore": ";:.,=}])> \n\t", "open": "\"", "close": "\"", "notIn": ["string"] },
		{ "onlyBefore": ";:.,=}])> \n\t", "open": "`", "close": "`", "notIn": ["string", "comment"] },
		{ "onlyBefore": ";:.,=}])> \n\t", "open": "/**", "close": " */", "notIn": ["string"] }
	],
```
But even that only solves some of the problems (and may introduce others). It also is also harder to explain and probably more likely to get wrong as a language extension.

**Comment by thw0rted** [comment]
Am I correct that a curly-brace should never auto-close inside a placeholder expression (`${ | }`) in a template string?  I don't think conditional blocks are valid there and I'm having trouble coming up with another reason to have a brace pair in that context.

**Comment by JacksonKearl** [comment]
@thw0rted hm.. 

```ts
const a = 'a'
const aorb = `${ {a: 'a', b: 'b'}[a] }
```

but I'm not sure how useful that is! Then again, not sure how useful not closing them out there is either. 

I'm going to go ahead and close this issue out as part of our annual housekeeping iteration as there isn't a strong use case for it to change, and it is known that the heuristic based approach we use will have some unhandled corner cases.

**Comment by thw0rted** [comment]
Sorry, I've lost context for this thread and I'm having to re-read and remind myself, trying to understand the resolution here.  Jean's PR would have removed the backtick from `autoCloseBefore`, but the PR was closed because the heuristics can't tell if you're inside a template string or not, and you are making the assertion that the case of typing an opening bracket with your cursor just before the closing backtick of a template string (where you'd want the bracket to auto-close) is more common than the case of typing an opening bracket immediately before the template string (where you would not).  Do I have that right?

I will give you that the case you describe is more common, however, I would counter that at least for me personally, when I expect to get a bracket inserted automatically, but the editor does not, I generally feel very mildly inconvenienced.  But when I am in the flow of typing, then I press a key, expecting one character, and the editor inserts two, that's a very disruptive feeling -- I mean, it bothered me enough to come here and write up this whole issue.  I figure I can't possibly be the only person who feels this way.

I've already asked if the editor could auto-close brackets only when in the context of a template string, or perhaps only immediately after a `$` character.  It would be ideal to auto-close `` `Hello $|` `` but not `` `Sample code: "if (X) |` ``.  Should that be its own issue?  If that's already been debated and it's too complex to implement, and we're stuck with trying to accommodate the more-frequently-used case (inside the string) rather avoiding than the more-disruptive case (unexpected character insert), can I at least change the default for myself?  I see that Jean's PR was editing config files inside the language plugin. From #38352 it looks like the answer is "not yet".  Is there anything else I can do to avoid this in the meantime?
