### ISSUE TITLE
Explore improvements to welcome pages

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#106715]
This meta issue is to track the various work items related to the welcome page. The main goal is to improve our welcome page for new and existing users while also providing meaningful updates relating to extensions and product updates.

## Issues
- [x] First run user onboarding #106717
- [x] Welcome page explorations https://github.com/microsoft/vscode/issues/63152
- [ ] What's new https://github.com/microsoft/vscode/issues/102139

**Comment by yangfansun** [comment]
we don't need welcome page!

**Comment by JacksonKearl** [comment]
Moved out of the milestone as the meta-nature means this just keeps getting pushed back. If there's any definitive closing condition for this issue we can re-add, otherwise maybe close it out?
