### ISSUE TITLE
Keyboard Shortcut When Expression (editorReadonly) doesn't work

### ISSUE THREAD

**Issue by EdsonRCJ** [microsoft/vscode#106762]
- VSCode Version: 1.49.0
- OS Version: Windows 10 ( Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Edit shortcut for Add Line Comment to : Ctrl + NumPad_Divide with When Expression ( editorTextFocus && !editorReadonly )
2.Edit shortcut for Remove Line Comment to : Ctrl + NumPad_Divide with When Expression ( editorTextFocus && editorRedonly)

VsCode doesn't remove the Line Comment... Just add more line comments.

Does this issue occur when all extensions are disabled?: Yesd
![Screenshot_1](https://user-images.githubusercontent.com/25020745/93212424-f7739d80-f738-11ea-84e5-014d57902a4c.png)
![Screenshot_2](https://user-images.githubusercontent.com/25020745/93212556-1d00a700-f739-11ea-8ffb-ad56b98f91f2.png)

**Comment by alexdima** [comment]
@EdsonRCJ Please follow the steps in the Basic Troubleshooting section here -- https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting

The output will indicate which keybinding rule matches when pressing the keybinding.

**Comment by EdsonRCJ** [comment]
> 
> 
> @EdsonRCJ Please follow the steps in the Basic Troubleshooting section here -- https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting
> 
> The output will indicate which keybinding rule matches when pressing the keybinding.

It matches the editor.action.addCommentLine 
This matches in every case ( commented or not )
`    {
        "key": "ctrl+numpad_divide",
        "command": "editor.action.addCommentLine",
        "when": "editorTextFocus && !editorReadonly"
    },`

This one never matches
`    {
        "key": "ctrl+numpad_divide",
        "command": "editor.action.removeCommentLine",
        "when": "editorTextFocus && editorReadonly"
    }`

**Comment by alexdima** [comment]
@EdsonRCJ Can you please comment out the contents of your `keybindings.json`? (`F1` > `Open Keyboard Shortcuts (JSON)`)
