### ISSUE TITLE
1.49 breaks typescript debugging (source map problem?)

### ISSUE THREAD

**Issue by lobsterkatie** [microsoft/vscode#106787]
Issue Type: <b>Bug</b>

After upgrading to 1.49, my debugger stopped being able to stop at breakpoints. In the breakpoint list they are all listed as `Unbound breakpoint`, and they are all skipped when I run the debugger. I suspect this is a source map problem, for a few reasons:

1. If instead of setting a breakpoint I insert a `debugger` statement, it does stop, but it stops in the transpiled JS file rather than the original TS file.
2. In the loaded scripts list, only the JS files are shown. Before, both the JS and the TS files would be shown.

By adding the debugger statement, I can see that the source maps are being inlined, but for some reason they're not being resolved into the original source.

Here is my `launch.json`:

```json
{
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}/packages/tracing",
      "name": "Debug tracing tests - only open file",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "args": [
        "--watch",
        "--runInBand",
        "--config",
        "${workspaceFolder}/packages/tracing/package.json",
        "--coverage",
        "false", // coverage messes up the source maps
        "${relativeFile}"
      ],
      "disableOptimisticBPs": true,
      "sourceMaps": true,
      "smartStep": true,
      "outFiles": ["${workspaceFolder}/packages/tracing/dist"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
    },
```

My `dist` folder contains both the transpiled JS files and the source maps, side by side, with appropriate `sourceMappingURL` values. (Also in there are the TS declaration files and their source maps.)

I'm attaching the log I got from adding `trace: true` to the above: [vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/5226713/vscode-debugadapter-0.json.gz)

The problem happens on both 1.49.0 and insiders (exact version details below), with and without extensions. Downgrading to 1.48 fixes it.

Please let me know if you need any more information.

.-------

Version, Extension, and System Information

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z), with extensions disabled

Also tried on Insiders version: Insider 1.50.0-insider (e13875b77c89b95f20ccb5667e14ff164c198e57, 2020-09-15T05:31:36.744Z), with no extensions installed.

OS version: Darwin x64 19.6.0
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|18, 16, 9|
|Memory (System)|32.00GB (1.82GB free)|
|Process Argv|--disable-extensions --crash-reporter-id b0279d3b-8393-4b25-b76f-67c5cd50b58e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by weinand** [comment]
@lobsterkatie your "outfiles" value is not a glob pattern. Please use something like `${workspaceFolder}/packages/tracing/dist/**/*.js`

**Comment by connor4312** [comment]
Indeed, that should fix your issue. A change was made this month to default to only resolving sourcemaps within the specified outFiles. This is the explanation behind that change: https://github.com/microsoft/vscode/issues/105859#issuecomment-685134778

**Comment by lobsterkatie** [comment]
Thanks for the quick reply!

Unfortunately, that change didn't fix it. 🙁

Here's another log file, from running 1.49 with extensions disabled:
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode/files/5229898/vscode-debugadapter-1.json.gz)

Same behavior as before - no stopping at breakpoints, debugger shows up in the transpiled file, only transpiled files showing up in the Loaded Scripts panel.

My new `launch.json` (identical to the above, save the change to `outFiles`):

```json
{
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}/packages/tracing",
      "name": "Debug @sentry/tracing tests - just open file",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "args": [
        "--watch",
        "--runInBand",
        "--config",
        "${workspaceFolder}/packages/tracing/package.json",
        "--coverage",
        "false", // coverage messes up the source maps
        "${relativeFile}"
      ],
      "protocol": "auto",
      "disableOptimisticBPs": true,
      "sourceMaps": true,
      "smartStep": true,
      "outFiles": ["${workspaceFolder}/packages/tracing/dist/**/*.js"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
    },
```

What else can I try?

**Comment by connor4312** [comment]
Ah, something I didn't notice -- are you transpiling TS files as part of your Jest run?

If so, you can specify that we should resolve maps there by adding `resolveSourceMapLocations: ["${workspaceFolder}/**"]`. You'll need to change the "type" to "pwa-node" for this to appear as valid.

**Comment by lobsterkatie** [comment]
Removing `outFiles` seems to have done it!

Thank you!

**Comment by ivansieder** [comment]
@connor4312 removing the outFiles seems to actually fix the breakpoint issue, but therefor it raises errors like "Could not read source map for file:///server/node_modules/@sentry/integrations/dist/transaction.js: ENOENT: no such file or directory, open '/server/node_modules/@sentry/integrations/dist/transaction.js.map'" inside the debug console. Is there a way to fix that, too?

**Comment by connor4312** [comment]
@ivansieder could you grab a trace log so I can see exactly what's happening?

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by ivansieder** [comment]
Wanted to try at home first (both workstations using Ubuntu 20.04 and VSCode 1.49.0). There it seems to work properly. Gonna try that again tomorrow at the office, maybe I'll find a reproducable difference. Thank you in the meantime!

**Comment by ivansieder** [comment]
@connor4312 re-installed VSCode and that now fixed it, thanks!
