### ISSUE TITLE
Codelens with padded with whitespace not showing

### ISSUE THREAD

**Issue by authuir** [microsoft/vscode#106718]
We found our codelens disappear in specific case in the latest version of VS Code(1.49.0) which won’t repro in previous version.
 
The root cause is the styling issue which results the third codelens squeezed to another line.

![image](https://user-images.githubusercontent.com/9346867/93162313-17aa5900-f747-11ea-8bee-3b45f24cdb81.png)

If the codelens starts or ends with an space will trigger this issue.

**Comment by jrieken** [comment]
> If the codelens starts or ends with an space will trigger this issue.

Workaround would then be to remove leading/trailing whitespace, right?

**Comment by jrieken** [comment]
This is a regression from updating to electron 9 (which bring a different layout enging). Running with `--disable-features=LayoutNG` doesn't allow me to reproduce this. fyi @deepak1556 @bpasero

**Comment by deepak1556** [comment]
@jrieken would it be possible to distill a minimal repro similar to https://github.com/microsoft/vscode/issues/88873#issuecomment-575924587 , makes it easier to report upstream.

**Comment by jrieken** [comment]
@authuir Are you the author of that extension? We have scheduled a fix for September and in the meantime the extension could push a change to trim the leading/trailing whitespace

**Comment by authuir** [comment]
> > If the codelens starts or ends with an space will trigger this issue.
> 
> Workaround would then be to remove leading/trailing whitespace, right?

Yeah, this is what we did

**Comment by authuir** [comment]
> @authuir Are you the author of that extension? We have scheduled a fix for September and in the meantime the extension could push a change to trim the leading/trailing whitespace

Yeah, I'm the author. Glad to hear that there will be an fix release!

**Comment by lifeart** [comment]
related: https://github.com/microsoft/vscode/issues/106876
