### ISSUE TITLE
If I switch workspace, focus moves to different VS Code instance

### ISSUE THREAD

**Issue by wivory** [microsoft/vscode#106727]
Issue Type: <b>Bug</b>

I have 2 VS code instances running, each using a different workspace.  If I switch the second instance to a third workspace, I'm immediately 'moved' to the other VS Code instance.  When I move back, I can see that the workspace has been changed, but it's not exactly helpful being forcibly moved to the other VS Code instance.  This worked fine prior to the most recent upgrade, though IIRC it did happen at one point in the past and I had to revert to an earlier version for a while.

Has the default value of some setting been changed?  It's incredibly annoying being moved between instances of VS Code, especially when they are in different linux virtual workspaces.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:20:50.359Z)
OS version: Linux x64 5.4.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 3588)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|62.43GB (45.55GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
cpputest-test-adapter|bne|0.1.6
yacc|car|1.3.1
gitlens|eam|10.2.2
go|gol|0.16.2
vscode-test-explorer|hbe|2.19.1
workspacesort|ici|1.5.9
plantuml|jeb|2.13.13
kite|kit|0.123.0
autoconf|mae|0.1.0
code-groovy|mar|0.1.2
python|ms-|2020.8.108011
vscode-pylance|ms-|2020.9.4
cpptools|ms-|1.0.0
vscode-groovy-lint|Nic|1.2.8
vscode-print|pdc|0.7.15
rf-intellisense|Tom|2.8.0
vscode-workspace-explorer|tom|1.5.0
yang-vscode|typ|2.0.3

</details>

**Comment by bpasero** [comment]
@wivory can you post exact steps how to reproduce from zero preferrably with a fresh user data dir `code --user-data-dir <empty dir>`

**Comment by wivory** [comment]
First, I have reverted from 1.49.0 to 1.48.2 and the problem has disappeared, so whatever is in my user data dir used to work just fine prior to the latest release.  So, for now at least, I can't see any use in using a fresh user data dir.

I'm running Ubuntu 20.04 with Cinnamon window manager.  I have 5 virtual workspaces in use (I'll call these Cinnamon-workspaces below for clarity).  To reproduce the problem:

- start 'code' in one Cinnamon-workspace; it starts and opens the last used code-workspace
- start 'code' in a second Cinnamon-workspace (it comes up not set to any workspace, as expected)
- select code-workspace 'B' in second code instance.  I'm immediately moved to the Cinnamon-workspace containing the first instance of 'code'.  If I move back to the Cinnamon-workspace containing the second instance of 'code', it has switched to the requested workspace.

In Code 1.48.2, when I select the code-workspace B in the second code instance, this instance of code opens the requested workspace, and I remain viewing this code instance in this Cinnamon-workspace, as you would expect.

**Comment by bpasero** [comment]
Ok, I am not sure about how "Cinnamon Window Manager" behaves, but since you indicate it used to work in 1.48 this maybe another Electron 9 update related regression. 

@deepak1556 I know I added the `app.focus({ steal: true})` to circumvent Electron's breaking change on macOS to not activate the app when it is in the background but I notice that I use it even on Linux and Windows. So my change in https://github.com/microsoft/vscode/commit/b9947f2a37923eb93ca56824e84003304ee6ac7d makes it conditional for mac only, please check.

**Comment by wivory** [comment]
Thanks - will this ship in next month's release?

**Comment by bpasero** [comment]
@wivory yes, but would be great if you could verify in our insider build tomorrow

**Comment by bpasero** [comment]
@wivory our insider build is out: https://code.visualstudio.com/insiders/

**Comment by wivory** [comment]
Thanks - that appears to be working as expected now, ie focus doesn't
switch back to original instance when I set the workspace in the second
instance.

**Comment by perlun** [comment]
Thanks for the fix @bpasero - I can confirm that vscode `1.50.1` (d2e414d9e4239a252d1ab117bd7067f125afd80a) indeed fixes my problem as well, as reported in #108174. Much appreciated. :clap: :bow:
