### ISSUE TITLE
update Go syntax

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#106798]
The last update was 8months ago. 
https://github.com/microsoft/vscode/blob/d54d7388946074b16f2093440edcd9ffcb9adeb3/extensions/go/syntaxes/go.tmLanguage.json#L7

Can we get it updated to pick up the fix for https://github.com/jeff-hykin/better-go-syntax/issues/3 ?

I think the up-to-date version is in https://github.com/jeff-hykin/better-go-syntax/blob/master/export/generated.tmLanguage.json

cc @jeff-hykin

**Comment by alexr00** [comment]
Thanks for catching this! Looks like the location of the grammar changed, so I updated our grammar-updating script and pulled in the change.
