### ISSUE TITLE
Interrupting a kernel vs Cancelling cell execution

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#106741]
With https://github.com/microsoft/vscode/issues/99203 we have removed cancellation tokens from the `execute`-functions and replaced them with `cancel`-function. This was done because jupyter kernels don't have the notion of canceling an execution but a notion of interrupting the kernel. Those are two different things and the current API is a compromise to fit both worlds. The compromise isn't happy:

1. for notebooks that support cancellation of execution things are now much more complex because the cancellation isn't automatically associated with an execution anymore. 
1. for jupyter kernels it doesn't make sense to implement `cancelAllCellsExecution` and `cancelCellExecution` because both are doing the same thing, sending an interrupt to the kernel.  

The API should be more explicit in support interrupting kernels. Proposal

```ts
export interface NotebookKernel {

  executeCell(document: NotebookDocument, cell: NotebookCell, token: CancellationToken): void;
  executeAllCells(document: NotebookDocument, token: CancellationToken): void;

  interruptExecution?(document: NotebookDocument): void;
}
```

A notebook kernel can optionally implement an interrupt-function which signals to us that it uses an interrupt model (e.g in the UI all stop buttons call interrupt). The execute-function do have cancellation tokens but the contract would be that they are null-token when using the interrupt model.

**Comment by jrieken** [comment]
fyi @DonJayamanne

**Comment by roblourens** [comment]
I like this proposal

**Comment by jrieken** [comment]
@roblourens I am leaving this to you. I looked into this but it seems that there is much work in the UI/model because today it's just cancel cell, not cancel a request. Also, unsure where to put the differentiation between interrupt and cancel, e.g hover over the stop button should show "interrupt kernel" or "cancel cell/notebook execution".

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/105847
