### ISSUE TITLE
Can't fold long <style> tag

### ISSUE THREAD

**Issue by zoulja** [Microsoft/vscode#10673]
![qunit](https://cloud.githubusercontent.com/assets/10187203/17784667/f49dbd0a-6585-11e6-9b02-c78aec1633a2.png)

- VSCode Version: 1.4.0
- OS Version: Win 7 x64

Steps to Reproduce:

1. Open HTML file with long `<style>` tag, try to fold it
2. It seems VS Code fails to detect tag's limits and doesn't even suggest fold icons on mouse over

By some reason I can't attach sample HTML file here, but it's simple wrapper for QUnit CSS from https://code.jquery.com/qunit/qunit-2.0.1.css (I directly inserted content of this CSS into the style tag)

In the same time such tag folding works fine in Notepad++

**Comment by aeschli** [comment]
The current folding strategy is based solely on the indentation of the line.
What you are asking for is language aware folding, where there is an understanding of opening and closing tags. We have #3422 for that.
