### ISSUE TITLE
Set "explorer / context" when key to reactjs only?

### ISSUE THREAD

**Issue by fulviocanducci** [microsoft/vscode#106794]
I create an "explorer / context" but, I want it to only appear when the project folder for a reactjs web how should I proceed in this configuration.

Actual:

```json
"menus": {
      "explorer/context": [
        {
          "command": "canducci.js.component",
          "group": "1_modification",
          "when": "explorerViewletFocus"
        },
```

that is, in the "when" key I put some configuration that limits it to appear only in a given project?

**Comment by sbatten** [comment]
Please see the list of existing when clauses here: https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

If one doesn't meet your need, you can calculate the context in your extension and use  
 `vscode.commands.executeCommand(‘setContext’, ‘inReactJsProject’, true)` to create your on context key

**Comment by fulviocanducci** [comment]
It does not solve

> If one doesn't meet your need, you can calculate the context in your extension and use
vscode.commands.executeCommand(‘setContext’, ‘inReactJsProject’, true) to create your on context key



- How do I know that the project uploaded by VS is ReactJs?

- Is there any command that I can run in the code to find out?

**Comment by sbatten** [comment]
it is not a core feature of VS Code to classify project types, that is best handled by extensions

**Comment by fulviocanducci** [comment]
> it is not a core feature of VS Code to classify project types, that is best handled by extensions


So there is nothing in Visual Studio Code to indicate that the project that was loaded is Javascript React?

@sbatten
