### ISSUE TITLE
Add compare/diff to ctrl-shift-p search menu

### ISSUE THREAD

**Issue by xPaw** [microsoft/vscode#106760]
Right now to compare two files, it is possible to right click in open editors, and do "select for compare", but this feels pretty hidden.

It would be good to have compare/diff available in ctrl-shift-p where you can select two tabs to compare between.

There is also no comparion options when right clicking a tab.

I had [this addon](https://github.com/fabiospampinato/vscode-diff) installed for diffing, but turns out VS Code can do it out of the box, it's just hidden.

**Comment by bpasero** [comment]
What is missing from here:

![image](https://user-images.githubusercontent.com/900690/93212967-93b29a00-f763-11ea-89f0-68ce3b899f54.png)

?

**Comment by xPaw** [comment]
Damn it, I only tried "diff" as that's the common term I always use (in git for example). Is it possible to have aliases in search?
