### ISSUE TITLE
Windows Setup: Add additional metadata to inno_updater.exe

### ISSUE THREAD

**Issue by stephannn** [microsoft/vscode#106721]
We use strict AppLocker Rules on Windows 10 and want to distribute VSC as user installer so that she or he can automatically install the updates. All exes are signed fine, except the inno_updater.exe which is responsible for the update installation. The publisher is missing the product name which means you have to allow all Microsoft products or use a maybe changing SHA hash.

Path      : %OSDRIVE%\USERS\user\APPDATA\LOCAL\PROGRAMS\MICROSOFT VS CODE\TOOLS\INNO_UPDATER.EXE
Publisher : O=MICROSOFT CORPORATION, L=REDMOND, S=WASHINGTON, C=US**\\**,0.0.0.0
Hash      : SHA256 0x19D1F34194DC2D13E0152C7ED32BDEF3B67620C19D4BB2C097D126319C979EBB
AppX      : False

The problem is the "\\" after C=US in the publisher field

![image](https://user-images.githubusercontent.com/38951729/93168009-34806580-f722-11ea-97b3-3daeb162906d.png)

Is it possible to signed the updater as well?
Thanks
Stephan

**Comment by joaomoreno** [comment]
The fix here would be to add those properties during the inno updater build: https://github.com/microsoft/inno-updater/
