### ISSUE TITLE
Show enumDescriptions in settings UI dropdowns

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#106737]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/9205389/93183965-fa23c200-f73b-11ea-8fe1-45f24f9fc543.png)

VS Code version: Code - Insiders 1.50.0-insider (cca20eba8974b1d6b6a9b71bf4e60a29c8f26648, 2020-09-12T00:56:22.923Z)
OS version: Darwin x64 19.4.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.01GB free)|
|Process Argv|-psn_0_31661616 --crash-reporter-id 7aad610c-0e6b-48aa-ba87-b704b1b543cf|
|Screen Reader|no|
|VM|22%|

|Item|Value|
|---|---|
|Remote|Dev Container: Alpine|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (0.86GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
This is the order that it's contributed in. Do you think that the settings UI should sort them alphabetically like they are in the suggest widget, or leave them in contribution order, in case that is important?

Looking through some enum settings, some seem to order the options in an intentional way, like with the default first, or the simpler options first. Some are random or are sorted. I think I am inclined to display them in contributed order to keep this an option (and we can sort the encodings manually), but I'm not sure, what do you think?

**Comment by bpasero** [comment]
It should be this order, same as the picker:

![image](https://user-images.githubusercontent.com/900690/93296754-28fb7000-f7f0-11ea-8e8e-dba2e0803f83.png)

The encodings are not sorted by name intentionally.

**Comment by roblourens** [comment]
Oh, got it. I've seen a few of these cases where it would make sense to display the enumDescription in the dropdown instead of the actual value. It doesn't make sense in general but it would be cool to provide an option for settings to opt into that, what do you think?

**Comment by bpasero** [comment]
Yeah I think it would make a lot of sense in this case 👍

**Comment by roblourens** [comment]
I think we should add an option to the schema contribution for this but I have no clue what to call it

**Comment by ryanclarke** [comment]
If the dropdown list will now display the enumDescriptions, should the description footer on the list show the value to be set? Should the collapsed dropdown control show the selected value or its enumDescription?

**Comment by ryanclarke** [comment]
I'll start working on this issue. Thanks for your help.

**Comment by roblourens** [comment]
Now this will show with the key in the description area in square brackets. But it would look much nicer to match the editor encoding picker, so I opened https://github.com/microsoft/vscode/issues/109255 for that.
