### ISSUE TITLE
 editor.selectionHighlightBackground in the default themes should be set to yellow or another color that jumps off the page

### ISSUE THREAD

**Issue by jd41** [microsoft/vscode#106748]
Issue Type: <b>Bug</b>

I decided yesterday to give VSCode a try, switching from kate.

When I select a piece of text (e.g. a variable name) in kate, other occurrences of that text are highlighted in a bright yellow colour. I can then quickly scroll through the file and find those other instances (variable, function call, etc.), which I find very useful.

VSCode has a similar feature, but in the default themes, the highlight color is barely distinguishable from the background (see screenshots, although it looks worse in a big code file with lots of syntax highlighting):
![screenshot_dark](https://user-images.githubusercontent.com/65656628/93203430-b9847280-f754-11ea-95a6-5fe285c4c975.png)
![screenshot_light](https://user-images.githubusercontent.com/65656628/93203438-bbe6cc80-f754-11ea-8810-34711736942f.png) This makes it impossible for me to scroll through the file and find instances quickly. Scrolling has advantages to clicking to "next result", as I feel I have better situational awareness of where in the code I currently am/what's the context.

I can't think of an argument in favour of the current set-up (in VSCode), and I think it's a big enough problem that I file it as a usability bug. Selecting a text is about the clearest signal a user can give that they are currently interested in that text, so the resulting highlighting should be more, not less, flashy and attention-catching than syntax highlighting etc. I don't think yellow is less stylish either, but if it was, any perceived stylishness should take a backseat to usability.

Including breaks and writing this issue, I started looking into and fixing this (for my system) about 4.5 hours ago, and I would have felt more warmly welcomed to VSCode if this color was more flashy from the start.

**For another newbie who finds this issue:** It can be solved by including e.g.

    "workbench.colorCustomizations": {
        "editor.selectionBackground": "#135564",
        "editor.selectionHighlightBackground": "#FFFF33"
    }

in config.json; my full config.json (at `/home/kubuntu/.config/Code/User/config.json`) is then

    {
        "terminal.integrated.inheritEnv": false,
        "workbench.colorTheme": "Default Light+",
        "workbench.colorCustomizations": {
            "editor.selectionBackground": "#135564",
            "editor.selectionHighlightBackground": "#FFFF33"
        }
    }

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:20:50.359Z)

**Comment by jd41** [comment]
Now that I am here: Is it possible to set the color of the foreground text in highlighed code to black, or another color that can always be distinguished from the background highlighting color?

**Comment by aeschli** [comment]
We currently have no plans to change the selection colors in the default themes. The current colors have been fine-tuned, and while not everyone might agree on the choice, changing it would cause other users to complain.

Luckily we allow users to tune the colors in the settings (as you have shown) or use one of many other themes available in the Marketplace.
