### ISSUE TITLE
Breakpoints and StopOnEntry Fail On Windows Only

### ISSUE THREAD

**Issue by ealexjordan** [Microsoft/vscode#10678]
- VSCode Version: 1.4.0
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

- OS Version:
Microsoft Windows 10 Enterprise 
Version 10.0.10586 Build 10586

Issue:
* Breakpoints and stoponentry do not work on our repo with VSCode 1.4.1 on Windows ( https://github.com/PowerShell/PowerShell). This was reported to us on https://github.com/PowerShell/PowerShell/issues/1831. 

* Breakpoints and stoponentry currently work on Ubuntu 16.04 with VSCode 1.4.1 and Ubuntu 14.04 with VSCode 1.2.1. Breakpoints and stoponentry DO currently work on the "dotnet new" default app on Windows. Breakpoints and stoponentry do not work on the same repo in Windows. 

* I've been playing with the VSCode 1.4.1 project.json file on Windows and was hoping to get some insight why or where this might be occurring on our repo. I can see no further settings or configurations that we could change to make breakpoints work. 

Our project.json file: 
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch",
            "type": "coreclr",
            "request": "launch",
            "justMyCode": false,
            "stopAtEntry": true,
            "program": "${workspaceRoot}/debug/powershell",
            "preLaunchTask": "build",
            "externalConsole": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "justMyCode": false,
            "processName": "powershell"
        }
    ]
}

Please let me know if there is further information I can provide, or if this issue does not belong here, it's been a long day ;)

**Comment by weinand** [comment]
The debug type 'coreclr' indicates that this issue is a problem of the C# debugger.

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#690
