### ISSUE TITLE
Cannot find  pwa-node on select enviroment

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/vscode#106703]
- VSCode Version: 1.49.0
- OS Version: Windows10 2004

![image](https://user-images.githubusercontent.com/15936231/93152407-474e6680-f731-11ea-919c-82ed767abce8.png)

![NLWuCchY0e](https://user-images.githubusercontent.com/15936231/93152731-07d44a00-f732-11ea-82ef-19c228b8f597.gif)

```typescript
resolveDebugConfiguration(_: WorkspaceFolder, config: DebugConfiguration): ProviderResult < DebugConfiguration > {
  // if launch.json is missing or empty
  if (!config.type && !config.request && !config.name) {
    const editor = window.activeTextEditor;
    const langid = editor?.document.languageId;
    if (editor && (
        langid === 'typescript' ||
        langid === 'javascript' ||
        langid === 'typescriptreact' ||
        langid === 'javascriptreact'
      )) {
      config.type = 'pwa-node';
      config.name = 'Launch';
      config.request = 'launch';
      config.program = '${file}';
      config.runtimeExecutable = 'deno';
      config.runtimeArgs = [
        "run",
        "--inspect-brk",
        "-A"
      ];
      config.attachSimplePort = 9229
    }
  }

  if (!config.program) {
    return window.showInformationMessage("Cannot find a program to debug").then(_ => {
      return undefined; // abort launch
    });
  }

  return config;
}
```

**Comment by connor4312** [comment]
@weinand I don't think this is me -- it looks like they're building a Deno debugger, from resolveDebugConfiguration they return a `pwa-node` type config but VS Code alerts that that doesn't exist. However they're able to debug with pwa-node inside a launch config.

**Comment by weinand** [comment]
@CGQAQ it is rather difficult to extract reproducible steps from your screen cast.
Could you please provide reproducible steps in written form. Thanks.

**Comment by CGQAQ** [comment]
> @weinand I don't think this is me -- it looks like they're building a Deno debugger, from resolveDebugConfiguration they return a `pwa-node` type config but VS Code alerts that that doesn't exist. However they're able to debug with pwa-node inside a launch config.

@weinand @connor4312 This is exactly what I want to ask

**Comment by connor4312** [comment]
Since you have code running, maybe the easiest way to let us diagnose this would be to push your code/a reproduction to a Github repo?

**Comment by CGQAQ** [comment]
> 
```typescript
resolveDebugConfiguration(_: WorkspaceFolder, config: DebugConfiguration): ProviderResult < DebugConfiguration > {
  // if launch.json is missing or empty
  if (!config.type && !config.request && !config.name) {
    const editor = window.activeTextEditor;
    const langid = editor?.document.languageId;
    if (editor && (
        langid === 'typescript' ||
        langid === 'javascript' ||
        langid === 'typescriptreact' ||
        langid === 'javascriptreact'
      )) {
      config.type = 'pwa-node';
      config.name = 'Launch';
      config.request = 'launch';
      config.program = '${file}';
      config.runtimeExecutable = 'deno';
      config.runtimeArgs = [
        "run",
        "--inspect-brk",
        "-A"
      ];
      config.attachSimplePort = 9229
    }
  }

  if (!config.program) {
    return window.showInformationMessage("Cannot find a program to debug").then(_ => {
      return undefined; // abort launch
    });
  }

  return config;
}
```

I think you just need that piece of code to reproduce the issue

**Comment by CGQAQ** [comment]
```typescript
    debug.registerDebugConfigurationProvider('deno', {
      resolveDebugConfiguration(_, config) {
        config.type = 'pwa-node';
        config.request= 'launch';
        return config;
      }
    })
```
![6adaGq9usC](https://user-images.githubusercontent.com/15936231/93243216-7a890800-f7ba-11ea-85c3-bf91431d2f3f.gif)
Add this piece of code to activate function is the minimal way to trigger this issue

**Comment by isidorn** [comment]
@CGQAQ please create a repository on GitHub which I can simply clone and reproduce this.
Or just fork https://github.com/microsoft/vscode-mock-debug and make some changes on top such that this is reproducable. Thanks

**Comment by CGQAQ** [comment]
@isidorn  https://github.com/CGQAQ/pwa-node-issue

**Comment by isidorn** [comment]
I followed your steps, however i get a different error

```
Activating extension 'undefined_publisher.pwa-node-issue' failed: Cannot find module '/Users/isidor/Development/pwa-node-issue/out/extension.js' Require stack: - /Users/isidor/Development/vscode/out/vs/loader.js - /Users/isidor/Development/vscode/out/bootstrap-amd.js - /Users/isidor/Development/vscode/out/bootstrap-fork.js.
```

**Comment by CGQAQ** [comment]
do you run `npm run watch` before run extension?

**Comment by CGQAQ** [comment]
@isidorn Fixed now, sorry

**Comment by isidorn** [comment]
Following your steps, this just works for me. Debugging starts. No breakpoint gets hit. Here's a gif.
I am on macOS with latest VS Code insiders.

![recording (1)](https://user-images.githubusercontent.com/1926584/93333083-16e6f500-f823-11ea-8edc-33adbb9c8993.gif)

**Comment by CGQAQ** [comment]
![Peek 2020-09-16 19-50](https://user-images.githubusercontent.com/15936231/93333568-13b92c80-f856-11ea-8f8b-122736be7647.gif)
I'm on 1.49.0 stable verison of vscode

**Comment by CGQAQ** [comment]
@isidorn  Please test it on stable version of vscode, I don't think most of the extension users will use insider version of vscode

**Comment by CGQAQ** [comment]
![image](https://user-images.githubusercontent.com/15936231/93420930-a7d0d580-f8e2-11ea-88f1-4d6e7046955d.png)
I'm facing another issue on vscode-insiders 1.50.0 @isidorn

**Comment by connor4312** [comment]
I'm guessing you got past the original issue -- what is the configuration you're calling startDebugging with when you get that error?

**Comment by CGQAQ** [comment]
> I'm guessing you got past the original issue -- what is the configuration you're calling startDebugging with when you get that error?

the repro is here

> @isidorn https://github.com/CGQAQ/pwa-node-issue
> 
> 1. Run the extension
> 2. open demo_workspace
> 3. open a.ts
> 4. press f5 and choose Deno

**Comment by connor4312** [comment]
You can fix that by including the workspace folder.

```diff
diff --git a/src/extension.ts b/src/extension.ts
index d6eca16..affbd86 100644
--- a/src/extension.ts
+++ b/src/extension.ts
@@ -6,7 +6,7 @@ import * as vscode from 'vscode';
 // your extension is activated the very first time the command is executed
 export function activate(context: vscode.ExtensionContext) {
 	vscode.debug.registerDebugConfigurationProvider('deno', {
-		resolveDebugConfiguration(_, config) {
+		resolveDebugConfiguration(workspaceFolder, config) {
       // "name": "Launch",
       // "type": "pwa-node",
       // "request": "launch",
@@ -18,6 +18,7 @@ export function activate(context: vscode.ExtensionContext) {
 		  config.type = 'pwa-node';
       config.request= 'launch';
       config.program = '${file}';
+      config.__workspaceFolder = workspaceFolder?.uri.fsPath;
 		  return config;
 		}
 	});
```

**Comment by CGQAQ** [comment]
@connor4312 But why I don't see anything about this in https://github.com/microsoft/vscode-mock-debug/blob/585b9344ef7bed6e5207daeb749b6e17c8a598b2/src/activateMockDebug.ts#L107

**Comment by connor4312** [comment]
You're looking at the mock debugger, which works to resolve the options it needs for it's _own_ debugging setup. This is not a minimal contract to which other debug extensions need to adhere. `js-debug` requires a folder context to do things like set the process' current working directory, which you can add by sending the `__workspaceFolder`.

**Comment by CGQAQ** [comment]
@connor4312 I need to set this internal like two underscores property, is this consider a bug? Or js-debug api' design problem? you can't get workspace folder directly in your js-debug code?
But anyway, thank you guys so much, I'll try it later, if it works, I'll close the issue

**Comment by connor4312** [comment]
> I need to set this internal like two underscores property by myself, is this consider a bug? Or js-debug api' design problem? 

The 'resolved config' isn't really considered an "API", much less stable, since building against it is vanishingly rare.

A more resilient option for you would be to return `undefined` from the config resolution process for deno, and then also call `vscode.debug.startDebugging` with the config you want. Basically, cancel the deno launch and while cancelling it incidentally start a `pwa-node` launch. Doing it this way will cause the configuration to go through the normal resolution process, as if it's in a launch.json, and keep you squarely in the realm of 'public APIs'.

**Comment by CGQAQ** [comment]
https://github.com/denoland/vscode_deno/blob/e57587d83d8a06b0b7487d4f541d795e5980683a/client/src/debug_config_provider.ts#L64
Resolved, thank you all!
