### ISSUE TITLE
node process occupation almost 100% cpu  issue on 1.49

### ISSUE THREAD

**Issue by leonkong** [microsoft/vscode#106720]
- VSCode Version: 1.49
- OS Version: macOS 10.14.6

Steps to Reproduce:
VSCode launch.json
"version": "0.2.0",
    "configurations": [
      {
          "type": "pwa-node", // or node
          "request": "launch",
          "name": "main",
          "runtimeExecutable": "nodemon",
          "restart": true,
          "env": {
              "NODE_ENV": "development",
              "IS_DEV": "1",
              "DEBUG": "nb:*",
          },
          "console": "internalConsole",
          "internalConsoleOptions": "openOnSessionStart",
          "program": "${workspaceFolder}/dist/bin/server.js",
          "outputCapture": "std",
      },

vscode debug custom config:
"debug.toolBarLocation": "docked",
"debug.openExplorerOnEnd": true,
 "debug.javascript.usePreview": false,
"debug.inlineValues": true,

My project is standard koa(nodejs) project with typescript, use tsconfig.json to compile ts files.

1. Run build task to compile all typescript files.
2. Press F5 to run debug session.
3. Occasionally，the fan in my mbp run with high-speed. I checked the system monitor, and found several node processes occupied almost 100% user cpu time (generally speaking 85+%)。
4. Then I close all vscode process, those node processes will not exit. I must kill them manually

on 1.48 or earlier versions，I encounter this problem uncommonly.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by filipac** [comment]
I get high CPU usage with Version: 1.50.0-insider  too

**Comment by connor4312** [comment]
What are those Node processes? What command line args are they started with?

**Comment by leonkong** [comment]
![image](https://user-images.githubusercontent.com/26429579/93339949-c8574c00-f85e-11ea-8a04-10f6baea3aa6.png)
![image](https://user-images.githubusercontent.com/26429579/93340607-9b576900-f85f-11ea-96de-f64905db499e.png)

**Comment by leonkong** [comment]
process like this:
node --inspect-brk=29834 dist/bin/server.js

**Comment by leonkong** [comment]
![image](https://user-images.githubusercontent.com/26429579/93342251-b4611980-f861-11ea-8c7c-bcf1e8d69c3d.png)
![image](https://user-images.githubusercontent.com/26429579/93342317-c93dad00-f861-11ea-9bcc-25bfaa0bf7c9.png)

**Comment by leonkong** [comment]
[nodemon] starting `node ./dist/bin/server.js`
[nodemon] forking
[nodemon] child pid: 27318
[nodemon] still waiting for 1 sub-process to finish...
Debugger listening on ws://127.0.0.1:60989/3b5d6065-cc2e-4d11-bd7a-e674fcf41932
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
2020-09-16T12:53:19.586Z  Server listening at host: 0.0.0.0, port: 9000

**Comment by connor4312** [comment]
If you're debugging a process, you should not spawn its children with --inspect-brk. We don't need them for debugging, and they will actually prevent VS Code from being able to attach to them.

There was a bug/behavior in older versions of Node.js where --inspect-brk would run a busy loop, eating 100% CPU, using --inspect-brk before a debugger is attached.

**Comment by leonkong** [comment]
I have checked all my config, I can't find where I use --inspect-brk param. It seems the '--inspect-brk=XXXX' created by vscode or some other mechanism？ Hope your comment.

**Comment by connor4312** [comment]
It's something in your program. How do you spawn the `dist/bin/server` processes? Are you able to share the contents of the `dist/bin/server.js",` file?

**Comment by leonkong** [comment]
maybe here "runtimeExecutable": "nodemon" in launch.json?

server.ts
import * as config from 'config';
import * as http from 'http';
import * as SocketIO from 'socket.io';
import socketIORedis = require('socket.io-redis');
import { app } from '../app';
import { getDebug } from '../lib/debug';
import { log } from '../lib/log';

const debug = getDebug(__filename);

const server = http.createServer(app.callback());

const io = SocketIO(server, {
  serveClient: false,
  path: '/rt',
  adapter: socketIORedis(config.get('redis.sockeio')),
});
io.adapter();
// realTime.init(io);

function getPort(): number {
  const envPort = process.env.PORT;
  if (envPort) {
    return parseInt(envPort, 10);
  }
  if (config.has('server.port')) {
    return config.get('server.port');
  }
  return 3000;
}

function getHost(): string {
  const envHost = process.env.HOST;
  if (envHost) {
    return envHost;
  }
  if (config.has('server.host')) {
    return config.get('server.host');
  }
  return '127.0.0.1';
}

const port = getPort();
const host = getHost();

server.listen(port, host, () => {
  debug('Server listening at host: %s, port: %d', host, port);
});

process.on('uncaughtException', (err) => {
  log.error('UNCAUGHT EXCEPTION ');
  log.error(`[Inside 'uncaughtException' event] ${err.stack || err.message}`);
});

export {
  server as default,
};

**Comment by leonkong** [comment]
server.js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = void 0;
const config = require("config");
const http = require("http");
const SocketIO = require("socket.io");
const socketIORedis = require("socket.io-redis");
const app_1 = require("../app");
const debug_1 = require("../lib/debug");
const log_1 = require("../lib/log");
const debug = debug_1.getDebug(__filename);
const server = http.createServer(app_1.app.callback());
exports.default = server;
const io = SocketIO(server, {
    serveClient: false,
    path: '/rt',
    adapter: socketIORedis(config.get('redis.sockeio')),
});
io.adapter();
function getPort() {
    const envPort = process.env.PORT;
    if (envPort) {
        return parseInt(envPort, 10);
    }
    if (config.has('server.port')) {
        return config.get('server.port');
    }
    return 3000;
}
function getHost() {
    const envHost = process.env.HOST;
    if (envHost) {
        return envHost;
    }
    if (config.has('server.host')) {
        return config.get('server.host');
    }
    return '127.0.0.1';
}
const port = getPort();
const host = getHost();
server.listen(port, host, () => {
    debug('Server listening at host: %s, port: %d', host, port);
});
process.on('uncaughtException', (err) => {
    log_1.log.error('UNCAUGHT EXCEPTION ');
    log_1.log.error(`[Inside 'uncaughtException' event] ${err.stack || err.message}`);
});
//# sourceMappingURL=server.js.map

**Comment by leonkong** [comment]
tsconfig.json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "sourceMap": true,

    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "removeComments": true,
    "preserveConstEnums": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,

    "experimentalDecorators": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": false,

    "alwaysStrict": true,
    "noEmitOnError": true,
    "newLine": "LF",

    "allowJs": false,
    "incremental": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": [
        "src/types/*"
      ]
    }
  },
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ],
  "include": [
    "src/**/*"
  ]
}

**Comment by leonkong** [comment]
nodemon.json
{
  "restartable": true,
  "ignore": [
    ".git",
    "node_modules/**/node_modules"
  ],
  "verbose": true,
  "execMap": {
    "js": "node",
    "mjs": "node --experimental-modules"
  },
  "events": {
    "restart": "osascript -e 'display notification \"App restarted due to:\n'$FILENAME'\" with title \"nodemon\"'"
  },
  "watch": [
    "dist",
    "config"
  ],
  "env": {
    "NODE_ENV": "development"
  },
  "ext": "js json mjs yml"
}

**Comment by connor4312** [comment]
I don't see anything suspicious in there. Is there any other time or way where you run server.js which could introduce these arguments?

**Comment by leonkong** [comment]
I have one way to run debug
1、VSCode menu command to run build task & watch ts files.
![image](https://user-images.githubusercontent.com/26429579/93419506-90dcb400-f8df-11ea-9275-8c71f9d1c7a9.png)
2、Press F5 to run "main" just like the launch.json I pasted before。
3、set breakpoint to debug.
