### ISSUE TITLE
Crash while Deleting file in workspace

### ISSUE THREAD

**Issue by kushkc12** [microsoft/vscode#106719]
Issue Type: <b>Bug</b>

i have observed that whenever i load multiple folder from disk in workspace ,which donot belong to same directory and while i delete one file visual studio crashes every time. ex: folder1 , folder2 in workspace when i deleted on of file in folder1 it crashes the program.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
