### ISSUE TITLE
add sign in natively to program

### ISSUE THREAD

**Issue by Philip-Getacademy** [microsoft/vscode#106749]
Issue Type: <b>Feature Request</b>

please add sign in function to visual studio code without browser. constantly have to sign back in even with sync on. tends to happen after closing colaboration sessions

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sandy081** [comment]
>  constantly have to sign back in even with sync on. tends to happen after closing colaboration sessions

Can you please elaborate what you mean by this? Are you seeing `Sign in to Sync Settings` action?

**Comment by Philip-Getacademy** [comment]
I read that I problems regarding login should be less frequent if sync settings is turned on, however, that doesnt help me at all. No setting or action reduces bugs regarding colaboration or action towards contacts. 
I have signed in, multiple times a day now, and are for the time being only using visual studio code because of live server. I would happily delete this application if such functionality found way into Visual Studio because of that.

Now, what I am saying is that it would be nice to have a native sign in for the visual studio code product so that you didnt get prompted to a browser for log in requests. Furthermore, if such a sign in exsisted none of the bugs regarding user/profile/colaboration would occur as you would be signed in natively and not through a "confirmation hash" or something from the microsoft browser session.

I hope that you are able to follow my train of thought, and perhaps understand the need and application of said functionality, as the current application version keeps giving me a whole lot of grief for the subject regarding login(s).
