### ISSUE TITLE
Please make Explorer view have a better design color pallete

### ISSUE THREAD

**Issue by ionuttamas** [microsoft/vscode#106700]
Issue Type: <b>Feature Request</b>

Currently, navigating/searching through files and folders in Explorer view is terrible: everything is a gray color (the file/folder names, the backgroud color, even the icons of the files have gray tint).
Very visually unpleasing. Please make it as Solution Explorer in Visual Studio.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

**Comment by isidorn** [comment]
Colors are customisable, please use a different theme, or just pick the colors you like via
workbench.colorCustomisations settings
