### ISSUE TITLE
扩展宿主意外终止

### ISSUE THREAD

**Issue by Wayne-007** [microsoft/vscode#106728]
Issue Type: <b>Bug</b>

打开编辑器就提示意外终止；

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.29GB free)|
|Process Argv|--crash-reporter-id 772cf195-148d-49d6-a3e0-7a55549cd6d1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
autopx2rem|ale|0.0.4
toolkit-vscode|ali|2020.8.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
auto-close-tag|for|0.5.8
auto-complete-tag|for|0.1.0
code-runner|for|0.11.0
vscode-lombok|Gab|1.0.1
vue-snippets|hol|0.1.12
beautify|Hoo|1.5.0
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.8.0
vscode-filesize|mkx|2.1.4
easy-less|mrc|1.6.3
vscode-language-pack-zh-hans|MS-|1.49.1
vetur|oct|0.27.3
material-icon-theme|PKi|4.3.0
java|red|0.66.0
vscode-yaml|red|0.10.1
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|2.1.5
easysass|spo|0.0.6
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-icons|vsc|10.2.0
ReactSnippets|xab|2.4.0

</details>

**Comment by qiulang** [comment]
Well I think he meant  _vscode program exits unexpectedly_

@Wayne-007 correct me if I was wrong.

**Comment by stdc105** [comment]
Extension host terminated unexpectedly.

**Comment by aeschli** [comment]
Does it reproduce with all extensions disabled?
Can you describe when this happens? What actions did you perform?

**Comment by Wayne-007** [comment]
I did nothing. I opened vscode and opened HTML file and reported this error. The solution was to go back to 1.48.2 and solve it!













At 2020-09-19 04:32:01, "Martin Aeschlimann" <notifications@github.com> wrote:

Does it reproduce with all extensions disabled?
Can you describe when this happens? What actions did you perform?

**Comment by Wayne-007** [comment]
There is no problem with Vscode, it is the live Server plug-in that has the problem, and the problem will be solved when we go back to version 1.48.2.
















At 2020-09-15 15:32:45, "qiulang" <notifications@github.com> wrote:

Well I think he meant vscode program exits unexpectedly

@Wayne-007 correct me if I was wrong.

**Comment by Wayne-007** [comment]
I used the latest version of macOS. When I opened the HTML file with Vscode, an error "extended host unexpectedly terminated" was reported. When I returned the 1.49 version to 1.48.2, the error did not appear, and the related plug-in was "Live Server". @vscode-triage-bot
