### ISSUE TITLE
Unexpected switch to High Contrast theme

### ISSUE THREAD

**Issue by stevage** [microsoft/vscode#106704]
Issue Type: <b>Bug</b>

Recently, I opened VS Code and, for no reason that I could tell, the High Contrast theme had been selected. The timing coincided with an automatic version update. I was able to set the theme back to my preferred Default Dark without harm.

(Reporting because [I was told to](https://twitter.com/BrigitMurtaugh/status/1305553495789985792))

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (1.68GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
vscode-apollo|apo|1.16.8
swagger-viewer|Arj|3.0.1
vs-org|Bob|0.1.3
ndjson-colorizer|bus|1.0.0
riot-tag|cri|0.1.7
vscode-eslint|dba|2.1.8
vscode-html2pug|dba|4.0.0
githistory|don|0.6.9
xml|Dot|2.5.1
gitlens|eam|10.2.2
json-tools|eri|1.0.2
prettier-vscode|esb|5.6.0
syntax-highlighter|evg|0.4.5
vscode-diff|fab|1.4.0
vscode-npm|fkn|3.3.0
url-encode|fle|1.1.0
code-runner|for|0.11.0
vscode-yarn|gam|1.7.1
gc-excelviewer|Gra|3.0.40
vscode-map-preview|jum|0.5.5
haml|kar|1.3.1
graphql-for-vscode|kum|1.15.3
bash-ide-vscode|mad|1.11.0
string-manipulation|mar|0.4.0
prettify-json|moh|0.0.3
python|ms-|2020.8.108011
sublime-keybindings|ms-|4.0.7
vsliveshare|ms-|1.0.2740
vetur|oct|0.27.3
word-counter|plu|0.0.1
ejs-language-support|Qas|0.0.1
ruby|reb|0.27.0
vscode-yaml|red|0.10.1
vue-vscode-snippets|sdr|2.1.5
mapbox-gl-js-snippets|shi|0.0.4
mdx|sil|0.1.0
language-stylus|sys|1.11.0
pdf|tom|1.1.0
org-mode|too|0.5.0
vscode-ruby|win|0.27.0

(5 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Since 1.49, the setting `window.autoDetectHighContrast` now also works on MacOS. It was always there, but just worked on Windows. It is on by default.
When a change to high contrast is detected, we switch to the theme defined in setting `workbench.preferredHighContrastColorTheme`.

**Comment by aeschli** [comment]
@stevage Did you had high contrast enabled on you OS?

**Comment by stevage** [comment]
Now that I look in Accessibility, I see the "Increase contrast" checkbox is ticked. I don't actually know what it does, I've never really noticed any effect in any other app.

I'd still say what happened here is a bug (or suboptimal design) though, because:

1. I had manually specified the theme I wanted (dark)
2. VS Code suddenly overrode my preference with a default assumption based on a system preference.

That guess would be fine (maybe? that high contrast theme is crazy high contrast and looks...well, not at all to my taste) if a user was installing VS Code and hadn't specified a theme yet. But not in this case.

**Comment by stevage** [comment]
(Oh, now I remember why I enabled that setting - it makes MacOS windows and controls so much easier to see, gives windows a hard black outline etc.)

**Comment by aeschli** [comment]
I agree that the high contrast theme is not for everyone. The Mac seems to support different levels of accessibility, and maybe it's not good that we use 'Increase contrast' alone is used to determine that we are in a high contrast mode. 
There's also a setting 'invert colors'. @bpasero Can we make also depend on that setting?

**Comment by bpasero** [comment]
@aeschli can you clarify? We currently use this code in `electron-main`:

https://github.com/microsoft/vscode/blob/b9947f2a37923eb93ca56824e84003304ee6ac7d/src/vs/code/electron-main/window.ts#L789-L789

**Comment by stevage** [comment]
Yeah, to expand on that: when this checkbox is enabled, MacOS itself only slightly bumps up the contrast. It highlights buttons and window edges a little bit more, but the overall effect is fairly subtle. If someone randomly switched this on on your computer, you probably wouldn't even notice.

VSCode interpreting that mode to enable SUPER HIGH CONTRAST MODE seems like a misinterpretation of what it means.

**Comment by individual11** [comment]
Same thing just happened to me after accidentally turning on high-contrast mode on OSX. When I switched it back, VSCode did *not* switch back to my normal theme and I had to switch it manually. Not the end of the world, but agree it's less than ideal.

**Comment by bpasero** [comment]
That does not sound like intended behaviour to me.

**Comment by aeschli** [comment]
@individual11 Did you restart VSCode in between? We only remember the last theme in memory.

**Comment by individual11** [comment]
@aeschli no, I had not restarted VSCode in between.

**Comment by aeschli** [comment]
I mark this issue (Unexpected switch to High Contrast theme) as dup of #107359.

@individual11 I just tested what you described, but don't see an issue. Would you mind filing a new issue with your steps?
My steps:
- in the user settings have `"workbench.colorTheme": "Kimbie Dark",`, also `window.autoDetectHighContrast` is on (as by default)
- in the Mac accessibility settings, enable 'Increase contrast'. 
    - VSCode switches to high contrast. User settings show `"workbench.colorTheme": "Default High Contrast",`
- in the Mac accessibility settings, disable 'Increase contrast'. 
   - VSCode switches back to Kimbie Dark. User settings contain: `"workbench.colorTheme": "Kimbie Dark",`
