### ISSUE TITLE
VS Code crashing on Ubuntu 16 with gpu error

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#106782]
- VSCode Version: 1.49 (stable)
- OS Version: Ubuntu 16

Steps to Reproduce:

1. Run VS code on the Azure Dev Ops machine (here's a recent build with this failure: https://dev.azure.com/ms/vscode-python/_build/results?buildId=109365&view=logs&j=1345b6c7-e7d6-523d-fef4-7a0223698f42&t=73b6dbed-1eb7-544e-0906-78814b410f0f)
2. We get this on startup: 
```[4909:0915/153741.574912:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.```

See this bug for more information:
https://github.com/microsoft/vscode-test/issues/73

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/106569
