### ISSUE TITLE
After VSCode runs for a period of time, the response become slower

### ISSUE THREAD

**Issue by colinsusie** [microsoft/vscode#106739]
Issue Type: <b>Performance Issue</b>

After VSCode runs for a period of time, the response become slower, and the scroll bar delayed a lot. I can only solve this problem by restarting VSCode

![slow](https://user-images.githubusercontent.com/11472347/93188317-6d94f600-f773-11ea-995f-6a59458ad48e.gif)

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.74GB free)|
|Process Argv|--crash-reporter-id e2e95338-f488-4d9b-8a4b-b9c79151c2d6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    5	   109	  3012	code main
    0	    26	  9808	   utility
    0	   232	  9840	   window (UIOperation.js - client-nav - Visual Studio Code)
    0	    11	 15372	     watcherService 
    0	    11	  9972	       console-window-host (Windows internal process)
    0	    33	 15836	     searchService
    0	    76	 17780	     extensionHost
    0	    29	  2884	       "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=17780
    0	    84	  5908	       electron_node tsserver.js 
    0	    43	  9192	         electron_node typingsInstaller.js typesMap.js 
    0	    76	 10408	       electron_node tsserver.js 
    4	    77	 10268	   shared-process
    1	    64	 11244	   window (Issue Reporter)
    0	   122	 14428	   gpu-process
    0	    14	 15868	   crashpad-handler
    0	   318	 17636	   window (FunPages.ts - client - Visual Studio Code)
    0	     6	  1292	     console-window-host (Windows internal process)
    0	     6	  4256	     C:\WINDOWS\System32\wsl.exe
    0	     5	 15356	       C:\WINDOWS\system32\lxss\wslhost.exe {0e5df17e-a77f-469a-a410-14a980dc529e} 488 496 500
    0	    13	  9828	         console-window-host (Windows internal process)
    0	    14	  5844	     watcherService 
    0	    11	  3332	       console-window-host (Windows internal process)
    0	    32	  6476	     searchService
    0	    79	 15096	     extensionHost
    0	    87	  9916	       electron_node tsserver.js 
    0	    30	 10244	       "C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=15096
    0	   149	 13192	       electron_node tsserver.js 
    0	    43	  1420	         electron_node typingsInstaller.js typesMap.js 
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (FunPages.ts - client - Visual Studio Code)
|  Window (UIOperation.js - client-nav - Visual Studio Code)
|    Folder (client-nav): 19702 files
|      File types: json(5761) meta(5159) js(2937) map(1956) jpg(1077)
|                  png(1064) prefab(569) mp3(126) plist(60) anim(18)
|      Conf files: project.json(2)
|    Folder (client): 19248 files
|      File types: json(6685) meta(4356) jpg(2534) png(2132) js(1119) map(649)
|                  mp3(254) prefab(247) ts(189) plist(14)
|      Conf files: settings.json(2) project.json(2) jsconfig.json(1)
|                  tsconfig.json(1);
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal-formatter|ale|2.4.0
xml|Dot|2.5.1
code-runner|for|0.11.0
python|ms-|2020.8.108011
vscode-pylance|ms-|2020.9.4
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
cpptools|ms-|1.0.0
debugger-for-chrome|msj|4.12.10
material-icon-theme|PKi|4.3.0
lua|sum|0.20.5
vscode-icons|vsc|10.2.0
omnipascal|Wos|0.18.0
markdown-all-in-one|yzh|3.3.0

(3 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
@colinsusie From the information you have attached, I cannot see any of the processes consuming a lot of CPU. Can you please try the steps explained in https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process to collect a CPU profile of the renderer process and attach it here?
