### ISSUE TITLE
PATH environment variable not consistent for Extension Host

### ISSUE THREAD

**Issue by giovdk21** [microsoft/vscode#106783]
- VSCode Version: 1.49.0 `e790b931385d72cf5669fcefc51cdf65990efa5d `
- OS Version: macOS Catalina `10.15.6 (19G2021)`

Steps to Reproduce:

1. Unfortunately it seems to be random

Description:

When running an extension locally (Extension Host) the result/value of `process.env.PATH` varies between it reflecting the PATH I have defined in my shell and just `/usr/bin:/bin:/usr/sbin:/sbin`

Basically most of the time the value of `process.env.PATH` corresponds to the results of typing `printenv PATH` in my terminal window (I use fish as my default shell) but sometimes it just returns `/usr/bin:/bin:/usr/sbin:/sbin`.

My extension uses `execFile` in order to run a command line tool that I have installed in a `bin` folder under my user home dir. however when `process.env.PATH` only return the "default" directories listed above, the command is not found (`ENOENT`).

While I appreciate there are several workarounds to this, it took me a while to figure out what was causing `execFile` to fail since the behaviour happens randomly and I would expect the value of `process.env.PATH` to be consistent.
Furthermore I never managed to reproduce this using the extension debugger (I ended up having to log the value of `process.env.PATH` to the extension output channel)

**Comment by Tyriar** [comment]
Is this randomness caused by whether you launch via the CLI or the dock? Note you'll need to close the app with cmd+Q in between checking as the environment won't refresh without fully exiting.

**Comment by giovdk21** [comment]
I almost always run it from the Dock and when I run it from command line it's usually from the VSCode terminal.

Another way the app is opened is when macOS launches it automatically after a reboot (e.g. if the OS freezes and you need to shut it down holding the power button).

I'll try to see if that is what's causing it, but I'm pretty sure it also happened a few times after running it from the Dock.

Thanks

**Comment by iFwu** [comment]
I can confirm this problem too.

**Comment by giovdk21** [comment]
I can confirm that this happens by just launching it from the Dock:

- launched VSCode the first time from the Dock and the PATH is wrong (`/usr/bin:/bin:/usr/sbin:/sbin`)
- reloaded window ("Developer: Reload Window")
- the PATH is now correct and `execFile` returns the PID instead of `ENOENT`
- closed VSCode (Cmd +Q)
- launched VSCode the second time from the Dock and now the PATH is still correct.

From what I remember using "Developer: Reload Window" does not always work either though (i.e. I'm sure I tried it before and the PATH was still "wrong" after doing it)

**Comment by tamuratak** [comment]
Related to #30847. And, the comment, https://github.com/microsoft/vscode/issues/30847#issuecomment-420399383, is helpful. 

You can find similar issues searching with the words `fish` and `PATH`.
