### ISSUE TITLE
Notebook metadata - undefined means false

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#106746]
When having an optional property  then `undefined` should have the same meaning as `false`, not `true`. There are a few metadata properties that violate this, e.g `NotebookCellMetadata#runnable`

**Comment by rebornix** [comment]
If this is a principle we follow, we may also want to change `editable` to `readonly`.

**Comment by jrieken** [comment]
this has become obsolete because all questionable metadata has been removed
