### ISSUE TITLE
[json] add quick fix for string to number conversion

### ISSUE THREAD

**Issue by PlanMan1717** [microsoft/vscode#106764]
A feature that would be very helpful to me in the quick drafting and validation of JSON docs to schemas would be the casting of types.

**What I find annoying:**

`"number_id": "5"` (`number_id` should be an `int`)

So I have to convert it to int myself.

What would be a huge time-saver is a quick fix that does this automatically.

Ex.

- (str -> int) `"5"` -> `5`
- (number -> int via. rounding) `53.44` -> `53`
- (single-element array -> str|int|number) `["44.1"]` -> `"44.1"`
- et cetera

Make this a quick fix please, so I can quickly run through the 'Problems' panel and instantly do this for all issues at once.

**Comment by nrayburn-tech** [comment]
Needing to convert single quotes to double quotes is something I find myself doing frequently.
