### ISSUE TITLE
Faulty popup help for comma inside an object in an array

### ISSUE THREAD

**Issue by MrAndersen1** [microsoft/vscode#106738]
Issue Type: <b>Bug</b>

```ts
interface test {
    id: number;
    propx?: number;
}
const testarr: test[] = [];
testarr.push({"id": 4})
```

Put the cursor after "id": 4 (still inside the object) and press comma. We then get a popup about Push when we shouldn't.

I posted a similar issue here
https://github.com/microsoft/vscode/issues/82825
a while ago, which was fixed.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-pdf|yza|1.4.4

(2 theme extensions excluded)

</details>

**Comment by MrAndersen1** [comment]
Some context: we have an array with large data structures in which we do something like this on:
```ts
someArr.push({
    ...
    propx: {
        ... 
        propy: [
              { "id": 4, },  // far down here we get popup help about the "someArr.push" above. When an array is involved like this we get the popup on the comma after the object too. See below.
        ]
    }
    ...
});

// Example with a nested array
interface test2 {
    id: number;
    propy?: string;
}
interface test {
    id: number;
    propx?: test2[];
}
const testarr: test[] = [];
testarr.push({"id": 4, propx: [{id: 4, }, ]}) // both commas give push-popup

```

**Comment by mjbvz** [comment]
I don't see this in VS Code insiders using TypeScript 4.0 (the default version):

![Sep-15-2020 11-31-54](https://user-images.githubusercontent.com/12821956/93250125-2d1f8300-f747-11ea-8d94-c1171be93269.gif)

Any extra steps to reproduce? Have you changed any settings?

**Comment by MrAndersen1** [comment]
I haven't tried insiders but it reproduces in playground too if that is any help. If it isn't then I could try insiders too, but that will have to wait until probably next week, sorry for the delay.

**Comment by MrAndersen1** [comment]
@mjbvz It does reproduce in insiders too, but only in a large open project. This time I did:
1. Open a larger project.
2. Add this code in some file:
```ts
interface test {
    id: number;
    propx?: number;
}
const testarr: test[] = [];
testarr.push({"id": 4})
``
3. Press comma twice in rapid succession after the 4 inside the object.

Sometimes it happens when erasing too, it's a bit finicky. It seems to happen when it has a lot of things to do, maybe it reproduces standalone in the playground because it has limited resources? Purely speculation on my part.

**Comment by mjbvz** [comment]
I tested this in the VS Code codebase but do not see this behavior using that example code. Can you share a specific project that demonstrates the problem?

**Comment by MrAndersen1** [comment]
Sorry no. I would if I could though.
Anyways if I'm the only one experiencing this issue and you cannot reproduce it then it's ok with me if we close it. It's not that big of an issue and if it bothers me again I could refactor the code it appears in :)

**Comment by mjbvz** [comment]
Ok, let me know if you find reliable steps to reproduce this so that we can take a look

**Comment by MrAndersen1** [comment]
@mjbvz out of curiosity did it reproduce for you in the playground link I posted up there?
[Playground Link](https://www.typescriptlang.org/play?ts=4.0.2#code/PTAEFEA8EMFsAcA2BTUB3AlgFwBamqAHbIDOWyAJvgE7XQCeAUBoedQGbQDGq5ZATKADejUGNAYKALiIBXWACNk1ANyjx8agHt49APwyy1FgHM1AX2atlnHqD5Zh6sZJmF5S1c9CadkA-akWPwA2gC6FoxcWoRkgWTQtDIO4aAAvKDhag6J1AB08LIkOAAUQgBEkuUyACwAND7a8JAyIUKuoPWg5g1h5gCUoCCgClq4oNGwsNAkoCYYAG6ohcUAtPA6svCMO1ZstrxBAMxO4hLScorKame+8NAB7ldeltGxjjm0-MnHqRlZjE++RWpQqVVqdQGQzAuAws0m03sWi0QA)
