### ISSUE TITLE
Too slow when saving file

### ISSUE THREAD

**Issue by khuccui2002** [microsoft/vscode#106713]
Issue Type: <b>Performance Issue</b>

Too slow when saving file

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (3.27GB free)|
|Process Argv|--crash-reporter-id 798549d8-8cb6-40e2-933c-7f056e69d0e8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   12	    98	   772	code main
    0	    82	   775	   gpu-process
    0	    33	   777	   utility
    0	   442	   778	   window (Settings — bh.kipi.vn)
    0	     0	   786	     /bin/zsh -l
    0	    33	  1267	       php artisan serve
    0	    49	  1271	         /usr/local/Cellar/php/7.4.7/bin/php -S 127.0.0.1:8000 /Users/mannguyen/Clients/GFC/ERP/GFC/bh.kipi/bh.kipi.vn/server.php
  100	   164	   794	     extensionHost
    0	    82	   809	       electron_node htmlServerMain.js 
    0	    33	   810	       electron_node server.js 
    0	    49	   812	       electron_node serverMain.js 
    0	   623	   901	       php /Users/mannguyen/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/felixfbecker/language-server/bin/php-language-server.php --tcp=127.0.0.1:49481 --memory-limit=4095M
    0	    33	   909	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=794
    0	   229	  1596	       electron_node intelephense.js 
    0	    49	   798	     watcherService
    0	    49	   826	     searchService
    0	    98	   799	   shared-process
    0	     0	  1877	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	  1875	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings — bh.kipi.vn)
|    Folder (bh.kipi.vn): 11686 files
|      File types: php(8391) phpt(269) md(227) json(186) xml(112) rst(76)
|                  stub(59) yml(52) dist(48) gitignore(46)
|      Conf files: makefile(4) launch.json(1) settings.json(1) package.json(1)
|      Launch Configs: php(2);
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
laravel-extra-intellisense|ami|0.3.2
atlascode|atl|2.7.1
laravel-blade-spacer|aus|2.1.2
vscode-intelephense-client|bme|1.5.4
laravel-goto-view|cod|1.3.3
vscode-eslint|dba|2.1.8
jquerysnippets|don|0.0.1
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
beautify|Hoo|1.5.0
regionfolder|map|1.0.12
identical-sublime-monokai-csharp-theme-colorizer|max|0.11.1
php-namespace-resolver|Meh|1.1.8
laravel-blade|one|1.24.0
laravel5-snippets|one|1.10.0
material-icon-theme|PKi|4.3.0
vscode-yaml|red|0.10.1
vscode-blade-formatter|shu|0.4.4
indenticator|Sir|0.6.0
laravel-goto-controller|ste|0.0.7
autoimport|ste|1.5.3
bootstrap4-vscode|the|6.1.0
highlight-matching-tag|vin|0.9.9
bootstrap-v4-snippets|Zac|1.1.3
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen if you launch with all extensions disabled? If it doesn't, I suggest you try to find out which one(s) to blame.

**Comment by khuccui2002** [comment]
> /needsMoreInfo does the problem also happen if you launch with all extensions disabled? If it doesn't, I suggest you try to find out which one(s) to blame.

Thank you for your suggestion, I tried to disabled all extensions and enabled 1 by 1 and I found **Laravel Extra Intellisense**
(https://marketplace.visualstudio.com/items?itemName=amiralizadeh9480.laravel-extra-intellisense) that made VS slow

**Comment by alexandis** [comment]
The 'stuck' time varies: sometimes it works more or less fast. Is there an easy way to figure out which extension could cause it? I am using the following ones (and I'd better keep using them, they help me around :) ):  Angular Language Service, ESLint, Prettier - Code formatter, TSLint, Visual Studio Intellicode. My colleague uses a bit different set of extensions and he as well has the same issue.
