### ISSUE TITLE
Tab Move Focus

### ISSUE THREAD

**Issue by MyLastAngel** [microsoft/vscode#106755]
Issue Type: <b>Bug</b>

Tab move focus in all  Ctrl+M  mode...

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.19GB free)|
|Process Argv|--file-uri file:///e%3A/%21PictureEditor%20JS/svg-picture-editor/PictureEditor.code-workspace --crash-reporter-id 9d0f2c30-bdce-4b2e-8e30-99f4de721c4a|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
electron-debug|kod|18.11.1
debugger-for-chrome|msj|4.12.10
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by aeschli** [comment]
Can you add more details what's not working?

**Comment by MyLastAngel** [comment]
I open any file with VSCode.  
"Tabs Move Focus" mode turned off (Ctrl+m) (no label) 
Click Tab, instead of adding 4 spaces changes the focus by UI VS Code (terminal, output, debug console, files, tabs...)

I press Ctrl+m  "Tabs Moves Focus" mode is enabled, but got same effect

**Comment by MyLastAngel** [comment]
"Ident Line" default key binding = Ctrl + ] (@aeschli - Is this ok?)
I change to Tab and all is ok...
