### ISSUE TITLE
Built-in typescript extension crashes quite often

### ISSUE THREAD

**Issue by walsehgal-discovery** [microsoft/vscode#106712]
Issue Type: <b>Bug</b>

When working with typescript code the built-in typescript extension crashed quite often. I have to disable and enable it in order to make it work. But now its crashing even more frequently.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
statistic|cai|0.6.3
xml|Dot|2.5.1
gitlens|eam|10.2.2
prettier-vscode|esb|5.5.0
go|gol|0.15.2
mssql|ms-|1.9.0
python|ms-|2020.6.91350

</details>

**Comment by mjbvz** [comment]
You are on an old VS Code build. Do you see this in VS Code 1.49 with extensions disabled?
