### ISSUE TITLE
Changed file case on a case sensitive file-system breaks VSCode

### ISSUE THREAD

**Issue by PepijnSenders** [microsoft/vscode#106774]
- VSCode Version: 1.49.0
- OS Version: 10.15.6 (19G2021)

Steps to Reproduce:

1. Create file with certain case
2. Change file case
3. VSCode loses it

<img width="444" alt="Screenshot 2020-09-15 at 11 00 47 AM" src="https://user-images.githubusercontent.com/2052659/93227953-f34c7d80-f742-11ea-9f61-dc5d816360d8.png">

Does this issue occur when all extensions are disabled?: No

**Comment by isidorn** [comment]
I believe this is a duplicate though forwarding first to @bpasero
