### ISSUE TITLE
Executing old build

### ISSUE THREAD

**Issue by kdecorso** [microsoft/vscode#106709]
Issue Type: <b>Bug</b>

I open VSCode and run my program; it works. I make a change and run the program; it runs the old build. The program will not run my updated code unless I close out VSCode and restart.

I have searched the internet for hours to solve this issue. I don't have a "Build" menu option, and I don't have an option to create a new project under "File". Any help will be much appreciated.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.16GB free)|
|Process Argv|--crash-reporter-id b24a0c0a-a0d4-469f-b59b-f7abcecedd1e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.0
cpptools|ms-|1.0.0

</details>

**Comment by aeschli** [comment]
What kind of project is it? C/C++?
You typically build from the command line, but it's also possible to set to a build task, It depends on your project.

**Comment by kdecorso** [comment]
Thanks for getting back to me so quickly. It’s a C++ project. I’ve followed YouTube walkthroughs on how to set up the program to run code. I honestly don’t know much terminology; I know my question is probably difficult to answer without more details

**Comment by aeschli** [comment]
Did you have a look at the tutorials at https://code.visualstudio.com/docs/languages/cpp ?
Also you can reach out for help on stackoverflow, e.g. https://stackoverflow.com/questions/30269449/how-do-i-set-up-visual-studio-code-to-compile-c-code

Issues related to the C++ extension have to go to https://github.com/microsoft/vscode-cpptools/issues. Note that in order to help we need detailed steps so we can reproduce the problem and find out if it is a bug.
