### ISSUE TITLE
Update 1.49 broke color profile selection

### ISSUE THREAD

**Issue by itkfm** [microsoft/vscode#106756]
- VSCode Version: 1.49
- OS Version: Ubuntu 20.04 amd64

Steps to Reproduce:

1. Get some pretty bad screen that you'll need a color profile for so it can at least display some contrast and somewhat saturated colors
1. Make sure that its color profile
1. Open VS Code 1.48 on a good screen
1. Close it
1. Update VS Code to 1.49
1. Re-open VS Code (still on the good screen)
1. Watch your eyes bleed because it will select the color profile of the bad screen

Does this issue occur when all extensions are disabled?: Yes

Does disabling the bad screen's color profile work-around that issue?: Yes

**Comment by bpasero** [comment]
Maybe related to the Electron 9 update.

**Comment by itkfm** [comment]
```sh
apt install code=1.48.2-1598353430
apt-mark hold code
```
^ went for this workaround for now

**Comment by deepak1556** [comment]
@itkfm can you check if this issue is present with our latest [exploration builds](https://az764295.vo.msecnd.net/exploration/b09dd7858771abf03f0abad6f5a5704839c13dd7/code-exploration_1.52.0-1604559376_amd64.deb)

**Comment by itkfm** [comment]
Unfortunately it’s still present.

![vsc](https://user-images.githubusercontent.com/53079668/98238355-8f864a00-1f66-11eb-804b-48f6427404e0.png)

(If you can't see the difference, it might be your screen. On my bad screen both sides of the screen look more or less the same. Most noticable difference: the purple in the right-hand instance “burns” way too bright.)

**Comment by deepak1556** [comment]
Yeah I don't see the difference in screenshot, can you try setting the color profile using `--force-color-profile <value>`. Available `<value>` options are `srgb`, `display-p3-d65`, `color-spin-gamma24`, `scrgb-linear`, `hdr10`

**Comment by itkfm** [comment]
> Warning: 'force-color-profile' is not in the list of known options, but still passed to Electron/Chromium.

But does the job :)
(Well, if this wouldn't require me to pass some --pretty-lengthy-parameter…)

**Comment by deepak1556** [comment]
which color profile worked ?

**Comment by itkfm** [comment]
All of them.

**Comment by deepak1556** [comment]
Thanks for confirming, you can set the color profile via `Runtime Arguments`

* Open the Command Palette.
* Run the Preferences: Configure Runtime Arguments command.
* Add "disable-hardware-acceleration": "srgb"
* Restart VS Code.

**Comment by itkfm** [comment]
```json
"disable-hardware-acceleration": "srgb"
```

Unfortunately, this does nothing but issue a warning (`Incorrect type. Expected "boolean".`).

Setting it to `true` makes VS Code choose some better color profile – I wonder whether this is the right thing to do, though.

**Comment by deepak1556** [comment]
Sorry its a typo, should be 

`"force-color-profile": "srgb"`

**Comment by itkfm** [comment]
ah, thanks :)

**Comment by itkfm** [comment]
`--force-color-profile <value>` appears to be broken. Seams to always produce the same result as putting `"force-color-profile": "srgb"` into `argv.json`.

Why?
Just tried those different profiles through `argv.json` and they all look very different, while with the `--f…` parameter they all look the same.
