### ISSUE TITLE
Unbound breakpoint

### ISSUE THREAD

**Issue by WymaRogerJarrett** [microsoft/vscode#106795]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I have been setting a breakpoint on some typescript code and launch the chrome debugger. Once chrome has loaded the breakpoint changes from solid red to grey open circle and message Unbound Breakpoint.

I have searched GitHub but there does not seem to be a fix for this issue.

VS Code version: Code - Insiders 1.50.0-insider (e13875b77c89b95f20ccb5667e14ff164c198e57, 2020-09-15T05:35:57.362Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (10.09GB free)|
|Process Argv|--crash-reporter-id 637413fa-86bb-4fbe-96b9-78eed6f63d04|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.6.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
debugger-for-chrome|msj|4.12.10
eno|Wsc|2.3.18

</details>

launch.json

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    {
        "name": "Launch Chrome - Cutting",
        "request": "launch",
        "type": "pwa-chrome",
        "url": "http://localhost/sweb/cuttingschedule",
        "webRoot": "C:/wamp/www/sweb/cuttingschedule",
        "sourceMaps": true,
        "trace": true
    },
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Listen for SWEB XDebug",
            "type": "php",
            "request": "launch",
            "pathMappings": {
                "/var/www/html": "${workspaceFolder}",
            },
            "port": 9001
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}

```

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/5227248/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment]
In the log file you included, the only three scripts the browser loaded were:

- https://code.jquery.com/jquery-3.3.1.min.js
- https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js
- https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js

It doesn't look like your own code is loaded in the browser. Therefore we cannot set the breakpoint and mark it with an empty circle.

**Comment by WymaRogerJarrett** [comment]
Issue Type: <b>Bug</b>

I have re-run again, trying to set a breakpoint in my typescript code.

I can see the code and set a breakpoint using chrome's internal debugger but can not do so from visual studio code.


VS Code version: Code - Insiders 1.50.0-insider (e13875b77c89b95f20ccb5667e14ff164c198e57, 2020-09-15T05:35:57.362Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.37GB free)|
|Process Argv|--crash-reporter-id 637413fa-86bb-4fbe-96b9-78eed6f63d04|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.6.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
composer|ika|0.7.1
debugger-for-chrome|msj|4.12.10
eno|Wsc|2.3.18


</details>

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/5229685/vscode-debugadapter-0.json.gz)
![2020-09-16 16_28_44-Window](https://user-images.githubusercontent.com/59033306/93292704-3ccbc400-f83a-11ea-8545-b35c7f8fb884.png)
![2020-09-16 16_22_30-Window](https://user-images.githubusercontent.com/59033306/93292835-97652000-f83a-11ea-85a8-28fecbd3e65a.png)

**Comment by connor4312** [comment]
I notice in your logs that you're opening a new window, 22 seconds into debugging. Are you trying to debug your the sources in there? You'll need update your urlFilter to include that if, so, which you can do by setting `urlFilter: '*'` in your launch.json.

**Comment by WymaRogerJarrett** [comment]
Adding 'urlFilter' solved the problem. Documentation about this option was not clear on this point. Nowhere that I could see did it say anything about what happens if multiple windows are opened. I have been used to the PHP debugger which does not use such an option. I had assumed wrongly that the javascript debugger worked in a similar manner. 

Thank you for pointing this out. Everything is now working.

**Comment by connor4312** [comment]
I think that defaulting the urlFilter is `'*'` is probably an okay default considering that we launched the debug browser fresh for the user. Thoughts @roblourens?

**Comment by roblourens** [comment]
Does that mean that it will auto attach to new tabs or windows?

**Comment by WymaRogerJarrett** [comment]
That was my expectation when I used the javascript debugger.

**Comment by roblourens** [comment]
I see it. Cool, it's probably fine. It could be annoying if someone is using the same browser for some other tabs that they don't want to debug, especially if those pages throw exceptions or something. But I would think that most likely they'd be using another browser/another chrome profile for that.

**Comment by roblourens** [comment]
It might make sense to actually name it "auto attach" or think about how it relates to node auto attach. Also as a launch config option vs user setting.

**Comment by connor4312** [comment]
Well, it's kind a matrix of both. As a user, the preference of whether or not to attach to other tabs in the debug target is a personal one. But for an app, I could know that I want to debug all of these specific urls. Which is additional configuration to conceptualize.

The exception case is annoying, but it will also be kind of apparent what happened in most cases. Probably...

I think a default of `*` is nice so people don't have to come to us when stuff doesn't work, as Wyma did. People whose process generally works but gives them a grain of sand in their shoe are more likely to seek an answer than people who try something, hit a brick wall, and give up.

I'll toggle it on Insiders and see if we get any complaints about it.

**Comment by lucashfreitas** [comment]
Same bug here: Start to happen on Version: 1.49.0

**Comment by connor4312** [comment]
If the [solution above](https://github.com/microsoft/vscode/issues/106795#issuecomment-693184830) doesn't work for you, you likely have a different issue and should open a bug here 🙂  https://github.com/microsoft/vscode-js-debug/issues
