### ISSUE TITLE
html.customData attribute snippets not worked if tag have uppercase

### ISSUE THREAD

**Issue by Kolobok12309** [microsoft/vscode#106731]
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
ОС: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Add to your file with custom data something like this
```json
{
  "version": 1.1,
  "tags": [
    {
      "name": "MyButton",
      "description": "My button. You should use it as in `<my-button type='alert'></mybutton>`.",
      "attributes": [
        {
          "name": "type",
          "description": "My button type",
          "values": [{ "name": "alert" }]
        }
      ],
      "references": [
        {
          "name": "Bootstrap buttons",
          "url": "https://getbootstrap.com/docs/4.0/components/buttons/"
        }
      ]
    }
  ]
}

```
2. Try write in `.html` files `<MyButton t`

Snippet for  attribute `type` don't working
If i rename tag to `my-button`, all normal

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode-html-languageservice/commit/2d7b17e532ab8b8f8dd64f1075c56caa00987545

**Comment by Kolobok12309** [comment]
Thanks for quick response 👍
