### ISSUE TITLE
Window Crashing when terminal panel toggled on welcome screen

### ISSUE THREAD

**Issue by Eazash** [microsoft/vscode#106724]
We have written the needed dat
Issue Type: <b>Bug</b>

Open a new vscode window
![image](https://user-images.githubusercontent.com/56728970/93172891-60a4e200-f734-11ea-9a72-01a74886ffa3.png)

Press <kbd>Ctrl</kbd> + <kbd>j</kbd>

I expected it to open the panel and start a new terminal at the home directory, instead i got this
![image](https://user-images.githubusercontent.com/56728970/93173907-e2493f80-f735-11ea-85ff-c74d3593f9b6.png)

Once i open a new terminal with <kbd>Ctrl</kbd>+<kbd>`</kbd> the issue seems to be gone, and the panel opens as expected with the shortcut

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.34GB free)|
|Process Argv|--crash-reporter-id 74be746f-3705-4a37-94a2-78106c099313|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
loopback-easy|Adi|0.7.0
vscode-flutter-helper|aks|0.2.5
flutter-snippets|ale|2.0.0
path-intellisense|chr|2.3.0
regex|chr|0.2.0
vue-peek|dar|1.0.2
dart-code|Dar|3.14.1
flutter|Dar|3.14.1
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
devdocs|dei|0.2.0
githistory|don|0.6.9
gitlens|eam|10.2.2
sass-lint|gle|1.0.6
nodejs-module-snippet|gun|0.0.2
ansible|haa|0.2.8
vue-snippets|hol|0.1.12
RelativePath|jak|1.4.0
search-node-modules|jas|1.3.0
flutter-tree|mar|1.0.0
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.9.0
python|ms-|2020.8.108011
remote-wsl|ms-|0.44.5
azure-account|ms-|0.9.3
debugger-for-chrome|msj|4.12.10
awesome-flutter-snippets|Nas|2.0.4
vetur|oct|0.27.3
nodejs-snippets|piy|0.0.2
synthwave-vscode|Rob|0.1.8
vue-vscode-snippets|sdr|2.1.5
loopback-json-schemas|seq|1.0.0
trailing-spaces|sha|0.3.1
html5-boilerplate|sid|1.0.3
guides|spy|0.9.3
nodejs-extension-pack|wad|0.1.9
material-theme|zhu|3.8.7

(4 theme extensions excluded)

</details>
a into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
The only hang I'm aware of in the panel is https://github.com/microsoft/vscode/issues/76548, which could happen if the terminal exits immediately in your case.

/duplicate

**Comment by Eazash** [comment]
The issue is not with closing but opening the panel. And i've found that the panel will crash anytime i try to open the panel on a window that hasn't opened a terminal yet.
It only happens in new windows.
