### ISSUE TITLE
Compose key does no work anymore

### ISSUE THREAD

**Issue by epeios-q37** [microsoft/vscode#106725]
Issue Type: <b>Bug</b>

- VSCode Version:
  - 1.49.0
  - Code - Insiders 1.50.0-insider (cca20eba8974b1d6b6a9b71bf4e60a29c8f26648, 2020-09-14T05:09:13.216Z)
- OS Version: Kubuntu 18.04; Linux 5.4.0-47-generic #51~18.04.1-Ubuntu SMP x86_64 GNU/Linux; <ins>French keyboard</ins>

Steps to Reproduce:

1. Launch *VSCode*
2. Select *File*/*New file*
3. Type the compose key
4. Type letter `o`
    - what should happen: nothing
    - what happens: `o` is displayed
5. Type letter `e`
    - what should happen: `œ` should be displayed
    - what happens: a separate `e` is displayed, resulting in `oe` instead of `œ` 

The compose key worked properly with previous version (<1.49.0) of *VSCode*. 

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 1604)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|15.52GB (4.13GB free)|
|Process Argv|--disable-extension --no-sandbox --crash-reporter-id b3298ee0-e97a-43fb-90ad-23cca65feaae|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by alexdima** [comment]
Starting with version 1.49, we have updated from Electron 7 to Electron 9, which brings a new Chromium version. Does this issue reproduce when typing in a text area in Chromium (like this comment input box here on github.com) ?

**Comment by epeios-q37** [comment]
Yes, indeed, *Chromium*/*Chrome* have the same issue. Can't say since which version, as I use both browsers very rarely.

**Comment by alexdima** [comment]
@epeios-q37 In this case, may I kindly ask that you please report this issue to Chromium at https://bugs.chromium.org/p/chromium/issues/list and link to the issue here. It would be very helpful if you would report it, as the Chromium developers could ask you specific questions about your setup in order to troubleshoot or reproduce the problem. I would also appreciate it if you could comment then here with a link to the issue you have created so we can better track this.

**Comment by epeios-q37** [comment]
Done: https://bugs.chromium.org/p/chromium/issues/detail?id=1129424

**Comment by alexdima** [comment]
Thank you!

**Comment by epeios-q37** [comment]
Issue fixed in version 1.56.1…
