### ISSUE TITLE
make it editable console

### ISSUE THREAD

**Issue by AbutalhaKothiwale53** [microsoft/vscode#106881]
Issue Type: <b>Feature Request</b>

I have a request for you,
can you make the output console writable/editable because it is not writable so I'm getting to trouble to write my python programs. Like if I have to give the user input for some python program, first I have to go to the terminal and then run the python file and then give the input. But using the output console I'd have to just run the program using the shortcut and then just give the input.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 6.3.9600

**Comment by isidorn** [comment]
I feel like this is designed behavior, though forwarding to @sandy081 who owns the output

**Comment by sandy081** [comment]
Output is meant to show information and logs. For interactive console use Debug Console or Terminal.
