### ISSUE TITLE
vscode extensions crashes on typescript tooltip over jquery methods

### ISSUE THREAD

**Issue by a-bentofreire** [microsoft/vscode#106834]
- VSCode Version: 1.49.0
- OS Version: Windows 10/Linux Mint 20
- @types/jquery@3.3.38

Steps to Reproduce:

1. Open a typescript file with jquery methods, such as: `$(document).ready(function () { });`
2. You will notice that the `ready` function is strikethrough.  
3. Place the mouse over the method: `ready`.

After this event the keyboard shortcuts stop working and well as many other operations.

**Comment by mjbvz** [comment]
Which extension is crashing? Can you share a screenshot of the problem?

**Comment by a-bentofreire** [comment]
I'm trying to make a proper diagnose but the extension host keeps crashing all the time even outside typescript files.
I have been using vscode for years without any problems, and the only update we did recently was on vscode, and the problem occurs in different machines.
![Screenshot from 2020-09-16 09-28-16](https://user-images.githubusercontent.com/7064913/93312452-23f1ed00-f7ff-11ea-828b-922f27b391be.png)

**Comment by a-bentofreire** [comment]
The host extension crash also occurs in other situations such as opening a file with it's git differences side-by-side.

**Comment by a-bentofreire** [comment]
I found out the problem, it's a conflict of [live-sass](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass) 3.0.0 and the latest version of vscode.
Unfortunately, this is a fundamental extension and I can't work with it disabled.
I will report the bug on the extension issue page and close this issue.
