### ISSUE TITLE
terminal issue

### ISSUE THREAD

**Issue by Nausheen95** [microsoft/vscode#106838]
> 

> @LuisBosquez  Type: <b>Bug</b>

The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 4294901760.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.67GB free)|
|Process Argv|D:\foldername\project name --crash-reporter-id a8572dfa-9f5e-44fd-bc28-68c5c237b122|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.6.0
powershell|ms-|2020.6.0
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

You may be able to fix it by whitelisting anti-virus https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

/duplicate https://github.com/Microsoft/vscode/issues/45693
