### ISSUE TITLE
I con't fold stylus in .vue file

### ISSUE THREAD

**Issue by a1245582339** [microsoft/vscode#106830]
Issue Type: <b>Bug</b>

Write stylus code in .vue file, every style block con't fold and expand. But the css, sass, scss and less can do. 

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (13.56GB free)|
|Process Argv|--crash-reporter-id fdce8d73-fbeb-4593-b20f-75bff2deb51d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.6.0
tt-miniapp|fis|0.0.2
code-runner|for|0.11.0
vscode-drawio|hed|0.7.2
svg|joc|1.3.9
vscode-styled-components|jpo|0.0.31
git-graph|mhu|1.26.0
snapcode|moy|1.1.0
vscode-language-pack-zh-hans|MS-|1.49.2
debugger-for-chrome|msj|4.12.10
vetur|oct|0.27.3
mdx|sil|0.1.0
language-stylus|sys|1.11.0
vscode-icons|vsc|10.2.0

</details>

**Comment by aeschli** [comment]
You need to file this against the vetur extension:https://github.com/vuejs/vetur

**Comment by a1245582339** [comment]
> You need to file this against the vetur extension:https://github.com/vuejs/vetur

I have open the vetur extension and it's working. 
When I launch the vscode, fold button can visiable one moment, but 1 second later, it would be disapper.
![image](https://user-images.githubusercontent.com/30924179/93323292-ffb9fe80-f846-11ea-88ec-d1e656ccba77.png)
![image](https://user-images.githubusercontent.com/30924179/93323340-0ea0b100-f847-11ea-8987-0538efe92f9c.png)

**Comment by aeschli** [comment]
Likely what you see is the indent based folding coming in first, nut then vetur comes in with folding ranges, but not css rule.
-> You need to file this against the vetur extension:https://github.com/vuejs/vetur
