### ISSUE TITLE
Configured debug type "pwa-node" is not supported, despite no pwa-node debug types

### ISSUE THREAD

**Issue by Twiggeh** [microsoft/vscode#106850]
- VSCode Version: Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:56:10.074Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
- OS Version: Linux x64 5.4.57-1-MANJARO

Steps to Reproduce:

1. Pressing f5

![image](https://user-images.githubusercontent.com/23149166/93329308-498def00-f81d-11ea-8ba2-a0d2edab67db.png)

Does this issue occur when all extensions are disabled?: Yes/No

Remote ssh machine, cannot disable all extensions

**Comment by isidorn** [comment]
Please try with latest vsode stable. 1.48.2 is an old version.

**Comment by Twiggeh** [comment]
Doesn't change with 1.49.0
```
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:20:50.359Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.57-1-MANJARO
```

**Comment by connor4312** [comment]
Did you somehow get js-debug disabled? (Search for `@id:ms-vscode.js-debug` in the extensions view)

**Comment by Twiggeh** [comment]
I disabled the nightly debugger in attempt to stop vs-code from auto-attaching, but I did not disable the "normal" javascript debugger

**Comment by connor4312** [comment]
Can you try running the command `Extensions: Enable All Extensions` and reload the window?

**Comment by Twiggeh** [comment]
Disabling `@id:ms-vscode.js-debug`, reloading, and then re-enabling it fixes the issue :D

**Comment by connor4312** [comment]
fyi @sandy081 -- sounds like a spooky issue somewhere. I've never seen this locally and unfortunately don't have repro steps.

**Comment by alfreddagenais** [comment]
I was having the issue. I update my `.vscode/settings.json` with the following configurations:

```json
{
  "debug.chrome.useV3": true,
  "debug.javascript.usePreview": false
}
```

And now all work for me

**Comment by connor4312** [comment]
@alfreddagenais the `usePreview` option is going away soon. Make sure to [file an issue](https://github.com/microsoft/vscode-js-debug/issues/new/choose) if something doesn't work.
