### ISSUE TITLE
Integrated terminal fails to launch

### ISSUE THREAD

**Issue by cdschreiber** [microsoft/vscode#106870]
Issue Type: <b>Bug</b>

Since the last update I'm getting the following error message when I run a task: "The terminal process failed to launch: Starting directory (cwd) "/Users/christoph/eod/~/eod" does not exist." It looks like the path parameter is passed twice.

VS Code version: Code - Insiders 1.50.0-insider (9e505675670d65138405321a60b0df4ddec28799, 2020-09-16T05:43:58.570Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.39GB free)|
|Process Argv|--crash-reporter-id e1ae89bb-bc15-4c0d-8be7-312a84233dd0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.0.0
vscode-icons|vsc|10.2.0

</details>

**Comment by scottpageindysoft** [comment]
Exact same issue after updating yesterday.

Version: 1.50.0-insider
Commit: d1f267742169584db010716d92addf50d4cd8139
Date: 2020-09-17T07:09:53.566Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

I've attempted set `cwd` in launch.json and tasks.json.
The task that fails runs `tsc`, which worked fine the day before updating.  That task is also a dependency task to another that runs npm scripts, which works fine.

**Comment by scottpageindysoft** [comment]
Notice the "~" in the path.  That does not show up anywhere else, for example when using ${workspaceFolder} in a launch configuration, the absolute path is correct.

**Comment by cdschreiber** [comment]
Fixed in 3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8
