### ISSUE TITLE
On click of any file automatically redirecting on that file when issue or warning in my project

### ISSUE THREAD

**Issue by hardik584** [microsoft/vscode#106863]
Open my flutter project  in vs code
Wait until analysis not done
After open any file, it will automatically redirect one by one warning error

**Comment by aeschli** [comment]
Sorry, I'm n ot sure what you mean by 'redirect one by one warning error'. Can you add a screenshot?

**Comment by hardik584** [comment]
![Screenshot (272)](https://user-images.githubusercontent.com/16501308/93451826-4a924f80-f8f5-11ea-8609-3e2e919d3a9f.png)
![Screenshot (271)](https://user-images.githubusercontent.com/16501308/93451855-51b95d80-f8f5-11ea-8afa-50c3d87112fa.png)
It's like when I open file for doing code at that time all warnings and info of problems part redirecting one by one in entire project file

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
