### ISSUE TITLE
Regex "search: \s(?=/), replace with: \n" not working 

### ISSUE THREAD

**Issue by maple1sha** [Microsoft/vscode#10684]
- VSCode Version: 1.3.1
- OS Version: Windows 10 14393

Steps to Reproduce:
1. Replace with regex not working as expected:
       "search: \s(?=/), replace with: \n"  is not working (this works on sublime text 2)

**Comment by bpasero** [comment]
@maple1sha in the editor or from the search view (global find & replace)?

**Comment by alexandrudima** [comment]
I believe this was fixed in the meantime
![regex](https://cloud.githubusercontent.com/assets/5047891/24913502/add800dc-1ed1-11e7-8da6-dcef1cc74b3b.gif)
