### ISSUE TITLE
Turning off autoattach doesn't turn of autoattaching

### ISSUE THREAD

**Issue by Twiggeh** [microsoft/vscode#106849]
- VSCode Version: Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:56:10.074Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
- OS Version: Linux x64 5.4.57-1-MANJARO

Steps to Reproduce:

1. Click "Auto Attach" to off
2. Doesn't do anything
![why](https://user-images.githubusercontent.com/23149166/93328754-6d046a00-f81c-11ea-8b3f-220efcf4a6d0.gif)

Does this issue occur when all extensions are disabled?: Yes/No

Working on remote machine through ssh so cannot remove all extensions

**Comment by connor4312** [comment]
You're debugging a program. We will _always_ attach to the program, regardless of the auto attach setting.
