### ISSUE TITLE
Select all when sidebar is clicked, selects line numbers

### ISSUE THREAD

**Issue by swarajgiri** [Microsoft/vscode#10688]
- VSCode Version: 1.4.0
- OS Version: 	Ubuntu 16.04.1

Steps to Reproduce:

1. Create/ open a file
1.  Press "ctrl + a" to select all
1. Now click on the sidebar
1.  Press "ctrl + a" to select all
1.  **It selects the line numbers** too
1. Copy pasting the above lines, produces this content.

`12345`
`1. Create/ open a file1.  Press "ctrl + a" to select all1. Now click on the sidebar1.  Press "ctrl + a" to select all1.  It selects the line numbers too`

[Screenshot](https://i.imgur.com/dyz0rZd.png)

**Comment by alexandrudima** [comment]
This has been fixed already. The fix is available on the Insiders channel and it will come in the Stable channel with the August release.

**Comment by swarajgiri** [comment]
Checked. It works on 
`Version 1.5.0-insider`
`Commit 3d9622208b2167921b6664e04fd1fbd51507a4a0`
`Date 2016-08-19T05:59:25.264Z`
