### ISSUE TITLE
Word separation doesn't select the $ in  PHP's variables

### ISSUE THREAD

**Issue by viaativaweb** [microsoft/vscode#106860]
The default setting should be:
```
    "[php]": {
        "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?", //no $
    },
```

**Comment by roblourens** [comment]
I think it's nicer for things like alt+arrow keys to work predictably across different file types, but this is there for users to configure with the configuration you suggest if they prefer something different.

**Comment by viaativaweb** [comment]
The problem is that no one working with PHP would not want to select the whole variable. Every single PHP developer needs to search on SO and copy and paste this setting every time they install vscode and it's just a pain the IDE doesn't just handle it right by default.
