### ISSUE TITLE
Remember open file custom identation

### ISSUE THREAD

**Issue by wesleyegberto** [microsoft/vscode#106816]
Would be nice to remember the identation changed manually for the current open files in the editor.

Sometimes a file is formatted in a different configuration and I don't want to change the format.
I use detect identation to keep the levels when adding new lines, but everytime I go to another file it resets.

**Comment by alexdima** [comment]
@wesleyegberto There exist three settings that control how indentation works. Did you attempt to configure them?
`editor.detectIndentation`, `editor.tabSize`, `editor.insertSpaces`. With language specific selectors, you could configure what the editor should do per language and not need to mess around with the settings manually.

**Comment by wesleyegberto** [comment]
I'm using thoses settings. The prettier and editorconfig extentions keep reseting them everytime I switch a file tab.

Thank you
