### ISSUE TITLE
Feature Request: Support inline code execution similar to jupyter notebooks / hydrogen

### ISSUE THREAD

**Issue by bigonazzi** [Microsoft/vscode#10680]
I'm looking for something similar to the [hydrogen package for atom](https://atom.io/packages/hydrogen), which allows you to execute parts of a script like a jupyter notebook does:

![68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f31333238353830382f31343539383737382f31636666316233322d303535342d313165362d383138312d3530343330376361366235362e676966](https://cloud.githubusercontent.com/assets/4755/17793617/8f2620a2-655d-11e6-84f4-f2eedc464279.gif)

**Comment by alexandrudima** [comment]
fyi @dbaeumer @bpasero @weinand

**Comment by weinand** [comment]
yes, to have support for this in the editor and/or debug console would be great.

/cc @isidorn

**Comment by egamma** [comment]
related https://github.com/Microsoft/vscode/issues/3220

**Comment by isidorn** [comment]
@bigonazzi is the produced output read only? Or can it be somehow modified?

**Comment by bigonazzi** [comment]
@isidorn hydrogen output is read only, with shortcuts to copy it to clipboard. Output cells above a certain length show scrollbars with the option to show full content.

**Comment by bigonazzi** [comment]
@isidorn hydrogen requires ipython and then connects to it via zmq. I believe all the output is html.

**Comment by egamma** [comment]
fyi @DonJayamanne @jrieken

**Comment by DonJayamanne** [comment]
@bigonazzi, some of the ground work has started for this in the [python](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) extension.
This will be available very soon, possibly this week (as soon as the next version of VS Code is released).

The initial release of the extension will display the results in a separate preview window, you can see some of the work here:
- [#303](https://github.com/DonJayamanne/pythonVSCode/issues/303)
- Screen [samples](https://github.com/DonJayamanne/pythonVSCodeDocs/blob/master/images/jupyter/examples.gif) and [more](https://github.com/DonJayamanne/pythonVSCodeDocs/tree/master/images/jupyter)

Inline display of results will start after the next release of VS Code.

**Comment by bigonazzi** [comment]
@DonJayamanne awesome! Can't wait to play with it! :)

**Comment by jrieken** [comment]
closing this as a dup of #3220
