### ISSUE TITLE
Broken "Ensure Prelaunch Dependencies" task

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#106877]
Can't use the Launch VS Code config because the prelaunch task is broken. `The terminal process failed to launch: Starting directory (cwd) "/Users/roblou/code/vscode/~/code/vscode" does not exist.`

@connor4312 @alexr00 any idea? I don't see what's determining the terminal cwd.

**Comment by connor4312** [comment]
I had an old Insiders on my macbook, it worked there and then failed after updating. Looking into, have a feeling it's tasks-related though as I haven't touched this in several weeks

**Comment by connor4312** [comment]
Seems to have been caused by 49ec999d80, I suspect by moving some of the path.normalize to path.relative. I don't have enough context to safely fix it myself.

**Comment by connor4312** [comment]
This also appears to affect debugging (linked issue)

**Comment by alexr00** [comment]
To support remote properly we should never be calling `path.normalize` like that, so I removed it. Looks like somewhere it's required though...

**Comment by alexr00** [comment]
Turned out to be unrelated to the `path.normalize`, and instead it was a missing parameter to the label service call.

**Comment by mastrauckas** [comment]
@alexr00 When will this be released?  My VSCode is completely broken.

**Comment by OoLunar** [comment]
This issue also affects Ubuntu 20.04.1 LTS. VSCode version: 1.50.0-insider \d1f267742169584db010716d92addf50d4cd8139
Guess this is a wakeup call to finally finish my documentation...

**Comment by payonel** [comment]
@OoLunar what documentation would that be, and how would it help us in this situation? just curious :)
also, I believe i have reported this issue in a duplicate ticket here: https://github.com/microsoft/vscode/issues/106958
I'll close my ticket myself when i can pull the updated build and retest

**Comment by OoLunar** [comment]
> @OoLunar what documentation would that be, and how would it help us in this situation? just curious :)

@payonel Oh it wouldn't help anyone here in the slightest. I've just been procrastinating creating docs for my project for months now... That's offtopic though 😅

**Comment by OoLunar** [comment]
It's fixed! Least, on the Debian ecosystem. Thank y'all for the quick fix!

**Comment by LoeDK** [comment]
Sadly, this just fixed one aspect of the bug for me.
Executing tasks now has the cwd set as `~/...` instead of `/home/user/...` leading to errors within scripts.
The behaviour used to be `/home/user...` .
The bug introduced `/home/user/~/...` .
The "bugfix" introduced `~/...` as default, which poses problems

System is Ubuntu 18.04

**Comment by LoeDK** [comment]
I opened a new ticket for this issue:
#106988 106988
