### ISSUE TITLE
Configuring an ES6 project using .d.ts files

### ISSUE THREAD

**Issue by builden** [Microsoft/vscode#1068]
if i want use node.d.ts, i must add node.d.ts to files property, but files not support glob pattern, i have to add all of project files to this property

other question: just use require('path') can support IntelliSense, use import don't support

**Comment by egamma** [comment]
The recommendation is to have the typings folder with the .d.ts files as a peer of the jsconfig.json.

See also https://github.com/Microsoft/vscode-samples

**Comment by builden** [comment]
the question is I have the typings folder and jsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "experimentalDecorators": true
  }
}
```

**Comment by egamma** [comment]
Did you try to put the typings folder in the same folder as the jsconfig.json. This is what I meant with 'peer' to jsconfig.json.

**Comment by builden** [comment]
my typings folder and jsconfig.json are in the project root dir

**Comment by egamma** [comment]
So it is the same layout as in the sample layout. Does the sample  https://github.com/Microsoft/vscode-samples work for you? If not what is the difference between your code and the sample?
Can you check whether this is related to #703

**Comment by builden** [comment]
the sample project  have the same problem
win8 + 64

**Comment by builden** [comment]
I just test the samples project
MAC OSX also has this problem

**Comment by egamma** [comment]
@builden cannot reproduce.

git clone the samples
npm install
replace the jsconfig.json with the one you have provided above

and I'm getting Intellisense.

![1068](https://cloud.githubusercontent.com/assets/172399/11655162/bd9d1352-9dab-11e5-9119-d02a9410f909.png)

**Comment by builden** [comment]
I already knew why i have this problem, because I had set global setting.json like this
![image](https://cloud.githubusercontent.com/assets/9499016/11655645/5038c2ea-9dea-11e5-9af3-e7ae77571361.png)

I just don't want to typings dir show at the files tree, and i did not set search.exclude property.

another question:  IntelliSense not support ES6 import, like this:
![image](https://cloud.githubusercontent.com/assets/9499016/11655780/69a80e92-9deb-11e5-9685-4b05d19582ba.png)

Thank you for your reply

**Comment by jrieken** [comment]
```
import path from 'path'
```

isn't well formed ES6 code. Those two options you have
1. `import * as path from 'path'` to import all
2. `import {join} from 'path'` to import only certain symbols

**Comment by builden** [comment]
Tks, those two options work well

but I have see many other open source use this style,
such as:
import React from 'react'

I never find import * as React from 'react'

**Comment by jrieken** [comment]
For sure a pattern that established before ES6 was finalised. Use this as reference: http://www.2ality.com/2014/09/es6-modules-final.html

**Comment by builden** [comment]
get it, tks for you reply
