### ISSUE TITLE
Typing into embedded editor moves focus into outer editor sometimes

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10686]
I am seeing this lately: I do a find references and quickly type into one of the results to edit and then the focus jumps out into the outer editor. After that I can move focus back and things are ok.

Takes a bit of tries to reproduce but happens frequently enough.

@jrieken @alexandrudima ideas?

**Comment by alexandrudima** [comment]
@bpasero Never saw that, but I rarely type inside an embedded editor. Any steps?

**Comment by bpasero** [comment]
@alexandrudima ![untitled](https://cloud.githubusercontent.com/assets/900690/17802060/299bc5e8-65ee-11e6-8939-fa40d6670174.gif)

**Comment by jrieken** [comment]
Yeah, I have seen that as well. No clue what's cause this...

**Comment by alexandrudima** [comment]
what the ...

**Comment by joaomoreno** [comment]
@bpasero Couldn't figure out how to repro this for verification.

**Comment by alexandrudima** [comment]
@joaomoreno 
* have two files A and B that reference each other (in TS use a function in A from B)
* open a single file B (!important)
* disable autosave
* find all references
* inside the find all references, type in A (!important)
* this should make it that A opens as a new tab in the background, which I think is what triggered the bug (a opening tab used to mess with the focus)

**Comment by joaomoreno** [comment]
Plus, have tabs enabled! 😉

Works!
