### ISSUE TITLE
make Column Selection on hotkey+LMB consistent

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#106804]
please make so when user presses the hotkey and then LMB, the selection would start from the location he pressed LMB on .

currently, the selection expands from existing, 1st placed cursor, and the workaround is to start 1-cursor selection and then press Ctrl+Shift . this is undesired behavior, and the action should not require the user to press the buttons in certain order . (MMB is not always comfortable, specifically with large amount of selections)

also i would like to change the Ctrl+Shift shortcut to Ctrl+Alt . (perfectly, the Keyboard Shortcuts settings should get all the functions that involve mouse, and a way to assign/input the mouse actions)
and the Column Selection should be integrated with the multi-selection . (perfectly, [ Ctrl+Shift/Alt+LMB >-> Column Selection, Shift+LMB >-> adjust the closest<b>/</b>last<b>/</b>1st Column or 1-cursor selection, Ctrl+Shift/Alt+LMB >-> add new Column Selection (multi-select) ] )

**Comment by alexdima** [comment]
Please configure `"editor.multiCursorModifier": "ctrlCmd"`.

Then, `alt` becomes free and you can use `alt` + mouse down and mouse drag to create column selections.

You can always also use the middle mouse button to create column selections.

**Comment by irvnriir** [comment]
@alexdima your comments doesn't address a single of the mentioned features . obviously i am already using `"editor.multiCursorModifier": "ctrlCmd"`

**Comment by alexdima** [comment]
For me, when I configure `"editor.multiCursorModifier": "ctrlCmd"` and then press <kbd>Alt</kbd> and press the left mouse button, the selection starts from the location where I pressed it:

![Kapture 2020-09-17 at 17 49 33](https://user-images.githubusercontent.com/5047891/93495472-70781e00-f90e-11ea-9b12-43cd4e077ab6.gif)

Having the ability to customize mouse bindings is tracked in #3130

**Comment by irvnriir** [comment]
@alexdima i reinstalled it and that worked, thank you . would still be good to make it work with multi-selection (Alt+Ctrl) .
