### ISSUE TITLE
about license

### ISSUE THREAD

**Issue by izaass** [microsoft/vscode#106817]
I work for a company, I want to make sure your visual studio code is free, and I need proof to prove it's correct, in case a copyright inspector comes to check, I can prove it surname

**Comment by aeschli** [comment]
You can find the license of the Visual Studio Code **product** here:
https://code.visualstudio.com/license

Visual Studio Code is based on OS source code available at https://github.com/Microsoft/vscode under the MIT license agreement at https://github.com/Microsoft/vscode/blob/master/LICENSE.txt. 

Additional license information can be found in our FAQ at https://code.visualstudio.com/docs/supporting/faq.
