### ISSUE TITLE
Show icon in Change language mode doesn't work anymore

### ISSUE THREAD

**Issue by zabel-xyz** [microsoft/vscode#106872]
- VSCode Version: 1.49
- OS Version: Windows 10

Steps to Reproduce:

1. Command: Change language mode
2. No icons are displayed, I use a custom icon theme.

In previous version 1.48 icon were displayed, this is no more the case. 
In fact, you must specified languageIds in order to work.
Specify fileExtensions only doesn't work anymore.

My custom icon theme:

  "fileExtensions": {
        "htm": "_f_html",
        "js": "_f_javascript",
        "ini": "_f_settings",
        "bat": "_f_shell",
        "sql": "_f_database",
       [...]
    },
    "languageIds": {
        "plsql": "_f_database"
    },
   "iconDefinitions": {
        "_f_database": {
            "iconPath": "./icons/png/database.png"
        },
        "_f_html": {
            "iconPath": "./icons/png/html.png"
        },
        "_f_javascript": {
            "iconPath": "./icons/png/javascript.png"
        },
        "_f_shell": {
            "iconPath": "./icons/png/shell.png"
        },
        "_f_settings": {
            "iconPath": "./icons/png/settings.png"
        },
       [...]
 }

![image](https://user-images.githubusercontent.com/16486407/93364819-4d376b00-f849-11ea-8408-4da27afe91f2.png)

Only plsql icon is displayed.

I test with other icon themes this is the same...

Does this issue occur when all extensions are disabled?: yes

**Comment by aeschli** [comment]
Which file icon theme is this?

**Comment by zabel-xyz** [comment]
It's a custom icon theme not published...
But I try with another extension with the same issue [Easy icon](https://github.com/JamesMaj/vscode-easy-icons)
=> No languageIds defined = No icon in "Change language mode" (Previousely it's work)

**Comment by aeschli** [comment]
Yes, there was a change as now we use the language associations. Before we picked a file extension and went with the icon of that extension. However that was not correct as users can redefine an file extension to a different language.
It is strongly recommended that file icon theme associate icons to languages. That way all file extensions for that language are automatically covered.

**Comment by aeschli** [comment]
Please file the issue against the theme that you are using,
