### ISSUE TITLE
Integrated terminal 'git log' initially shows top of scroll buffer

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#10685]
- VSCode Version: Code - Insiders 1.5.0-insider (55168276e4c0b6ec2404ac20af04eeed5f5b1000, 2016-08-17T06:04:29.075Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1. Exit any integrated terminal to start from a clean state
2. Open integrated terminal
3. ls -> primes scroll buffer with recognizable content
3. git log -> ok
4. exit git log
5. git log -> not ok, shows output of ls at top

**Comment by Tyriar** [comment]
I've been seeing this a bit recently as well, will look at for August.

**Comment by Tyriar** [comment]
Upstream issue https://github.com/sourcelair/xterm.js/issues/235
