### ISSUE TITLE
下划线能不能不要波浪的 换成简单点的 

### ISSUE THREAD

**Issue by jiangtong** [microsoft/vscode#106835]
Issue Type: <b>Feature Request</b>

页面太多波浪线感觉很乱

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.6.0

**Comment by AryanBeezadhur** [comment]
***Translated from Chinese to English, this reads:***

# Can the underline not be wavy but be replaced with a simple one?

Issue Type: **Feature Request**

Too many wavy lines on the page feel messy

VS Code version: Code 1.49.0 (e790b93, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.6.0

## My interpretation

I think that this user is referring to VS Code underlining code with wavy lines. They feel that it looks messy:

![image](https://user-images.githubusercontent.com/34424160/93325643-8357f900-f80f-11ea-8663-afdf446d070f.png)
