### ISSUE TITLE
[vscode-insiders] I can't use launch.json anymore 

### ISSUE THREAD

**Issue by herberthobregon** [microsoft/vscode#106874]
Code Insiders info:
```
Version: 1.50.0-insider
Commit: 9e505675670d65138405321a60b0df4ddec28799
Date: 2020-09-16T05:43:58.570Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

Steps to Reproduce:

I try to run program with `launch.json`
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "index.ts",
			"type": "node",
			"request": "launch",
			"program": "${workspaceFolder}/index.ts",
			"preLaunchTask": "tsc: build - tsconfig.json",
			"outFiles": ["${workspaceFolder}/dist/**/*.js"],
			"protocol": "inspector"
		}
	]
}
```

But when I run, the terminal show this error

```
The terminal process failed to launch: Starting directory (cwd) "/Users/herberth/Projects/backend/~/Projects/backend" does not exist.
```

### This is the main problem

`tasks.json`
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "typescript",
			"tsconfig": "tsconfig.json",
			"problemMatcher": [
				"$tsc"
			],
			"group": "build",
			"label": "tsc: build - tsconfig.json"
		}
	]
}
```

I don't know why it duplicates my file path.

This does not happen in previous versions of vs code insiders.
In `vscode-stable` and the prev. version of `vscode-insiders` works fine

_____ 
Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
There is no need for the "protocol" property, but I have no clue where the error message originates from.
There is no "terminal process" involved in the launch config you are using. And neither is there a preLaunchTask...

@connor4312 any idea?

**Comment by herberthobregon** [comment]
@weinand I update my issue, with `preLaunchTask` is the same

**Comment by connor4312** [comment]
Looks like the same as https://github.com/microsoft/vscode/issues/106877

/duplicate

**Comment by weinand** [comment]
does it make a difference if you add a "console": "integratedTerminal" to the lauch config?

**Comment by herberthobregon** [comment]
@weinand The same error keeps happening adding `"console": "integratedTerminal"` to `launch.json`

**Comment by connor4312** [comment]
Try removing or commenting out your `preLaunchTask` for the moment
