### ISSUE TITLE
Allow discovering where the webview is positioned

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#106825]
In webview views, I don't know where the webview is positioned. For the visualizer extension, by default it's placed in the sidebar, so I'm using the sidebar colors as the background on my graph. But then when it's moved into the panel, those backgrounds are mismatched and ugly. I don't see a way right now to figure out where the webview is positioned.

**Comment by connor4312** [comment]
In https://github.com/microsoft/vscode-js-profile-visualizer/commit/e40250f31aa0159dffe89a5a1e94ef53430bd195 I simplified some rendering so I no longer really need this (as long as the sidebar and panel aren't drastically different colors where the foreground would have contrast issues). But I can imagine it still be useful in those and other cases.

**Comment by mjbvz** [comment]
Closing this for now since it has not gotten additional feedback since it was opened
