### ISSUE TITLE
Feature request: Cell level VIM edit mode

### ISSUE THREAD

**Issue by wjsbgsnwss** [microsoft/vscode#106811]
With the current vim extension, one can append/delete/edit the cells as a whole, but when it goes into a cell, it is just normal edit mode. When you hit esc key, it will leave the cell and you can't edit the cell unless you hit the Enter key. 

It used to have plugin in Jupyter (not in VSCode) that allows VIM to edit the cell, using vim key-binding to edit the content of the cell.

**Comment by rebornix** [comment]
We already supports this with native notebook.
