### ISSUE TITLE
I can't debug anymore

### ISSUE THREAD

**Issue by GaoHengdong** [microsoft/vscode#106819]
- VSCode Version:1.49.0 
- OS Version:Windows_NT x64 10.0.18362

1.When debuging. There's nothing in variables ,watch and callstack. Button step over is disabled. I can't debug anymore.
2.This only happened on my ASUS computer recently. My another computer works fine.
3.I tried reinstalled. And deleting all the extensions. But still not work.
4.I tried newly download vscode insider without any extensions. But still not work. 

Please help me. Thank you.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@GaoHengdong what debugger are you using?

**Comment by GaoHengdong** [comment]
node.js

**Comment by weinand** [comment]
How does your launch config look like?

**Comment by GaoHengdong** [comment]
I click [run and debug], and choose node.js.
I didn't have a configuration.
It says No Configurations on the left top.

**Comment by weinand** [comment]
And you have a node.js program in the editor and you have set a breakpoint in that program?

E.g. something like this:

![2020-09-16_10-43-32 (1)](https://user-images.githubusercontent.com/1898161/93314084-9bc51500-f809-11ea-892c-f2fe0c63ae95.gif)

**Comment by GaoHengdong** [comment]
Yeah, I have. Like this.
![1](https://user-images.githubusercontent.com/30036217/93314741-c7152780-f83c-11ea-9079-a25276d930d5.gif)

**Comment by weinand** [comment]
Does restarting your ASUS computer helps?

**Comment by GaoHengdong** [comment]
I find the reason.
VS code and proxifier are not compatible.
It worked when I closed proxifier.
It's strange. Why that happened?

**Comment by weinand** [comment]
@connor4312 could the use of "proxifier" explain this problem?

**Comment by connor4312** [comment]
Yea. We had another issue where they had a firewall that was blocking attachment in the same way.

@GaoHengdong I recommend reaching out to Proxifier for support if you believe it's not working as designed.

**Comment by GaoHengdong** [comment]
Why not add tips？ It's  difficult to find the problem.

**Comment by connor4312** [comment]
Added some docs here https://github.com/microsoft/vscode-js-debug/blob/master/COMMON_PROBLEMS.md
