### ISSUE TITLE
There are some render issues after 1.49 updates

### ISSUE THREAD

**Issue by ziofat** [microsoft/vscode#106832]
- VSCode Version: 1.49.0
- OS Version: macOS Catalina 10.15.6

Steps to Reproduce:

1. Open a project with VSCode
2.

![1](https://user-images.githubusercontent.com/8521174/93304291-63d0c880-f82f-11ea-97e4-0bf00ad21886.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Can you disable hw acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration and check if the issue continues. Thanks!

**Comment by ziofat** [comment]
@deepak1556 The issue does not persist if turn off gpu acceleration.

**Comment by deepak1556** [comment]
Thanks for testing, I would suggest to run with hw acceleration disabled. GPU issues are sometimes fixed when we update the runtime. Can you check if our exploration build fixes this issue https://az764295.vo.msecnd.net/exploration/c8ed3d4a11938e833a77e11798c66723a7a4fff8/VSCode-darwin-exploration-x64.zip

**Comment by ziofat** [comment]
I cannot reproduce the issue with the exploration build.

**Comment by deepak1556** [comment]
It will be a while before we push the exploration build for stable release, please use the current stable with workaround until then. Thanks!

**Comment by ziofat** [comment]
OK, thanks. I can live with that.
