### ISSUE TITLE
Show whitespace in whitespace diff

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#106855]
Issue Type: <b>Feature Request</b>

Here's my use case: There are changes indicated in the VCS panel. I open a diff to inspect the changes. The diff view indicates zero changes:

![image](https://user-images.githubusercontent.com/1658949/93332045-82c85e00-f821-11ea-9395-55d756b6b58a.png)

I remember that whitespace diff is disabled and enable it.

![image](https://user-images.githubusercontent.com/1658949/93332109-9b387880-f821-11ea-9994-87dd8b0f91e5.png)

Now I can see that a lot of lines changed, but I still have no clue what the change was. The only way to actually _see_ it is to change `editor.renderWhitespace`. This is undesirable, because it has effects outside of the diff view. And adjusting the setting breaks the entire workflow, as the change is likely only temporarily relevant.

What I would love:

- Being able to toggle whitespace visibility in the diff view. Maybe toggle it automatically if whitespace diff indication is desired.
- Being able to set `editor.renderWhitespace` for the diff view separate from the main editor.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 4.19.104-microsoft-standard

**Comment by alexdima** [comment]
@oliversalzburg When the diff editor renders two text buffers that differ only in leading/trailing whitespace, the following button appears:

![image](https://user-images.githubusercontent.com/5047891/93359034-730d4180-f842-11ea-8d7a-acc4820118e6.png)

Does this button not appear for you?

**Comment by oliversalzburg** [comment]
Yes, I do see that button. However, as you mention, it only appears if there are no other changes in the diff.

Regardless, when I press it, that's where I'd get to my second screenshot. I can now see which lines have whitespace changes, but I can't see what the change were in details. Were tabs replaced with spaces? Spaces with tabs? Something more subtle?

When `editor.renderWhitespace` is configured to `"none"` (which is my current preference), then the change is not visible. That's why I felt it would help to show the whitespace indicators when also showing the whitespace differences.

**Comment by alexdima** [comment]
@oliversalzburg On a default theme, the whitespace is highlighted:

![image](https://user-images.githubusercontent.com/5047891/93383147-841a7a80-f863-11ea-9af0-777486445b52.png)

**Comment by oliversalzburg** [comment]
That's not the same as `editor.renderWhitespace`. In your screenshot, it's not clear if spaces or tabs are highlighted. It only highlights the *area* that was changed. It doesn't indicate the *characters* that were changed. 

The difference should be obvious by comparing your previous two screenshots. One has whitespace indicators, the other only highlights the changed area. I want both.

Is this difference still unclear or are you trying to suggest alternative solutions?

**Comment by alexdima** [comment]
Thank you, I think I'm finally understanding what you're asking for. I initially thought there is a problem with your theme and it does not render character-level diffs. (themes can define transparent colors and that might lead to the character level diff not being visible)

You would want that whitespace is rendered with dots/tabs even if `"editor.renderWhitespace": "none"` if the whitespace is part of a character level diff or a line level diff.
