### ISSUE TITLE
Code Helper Renderer Locks up with Find Command

### ISSUE THREAD

**Issue by jxramos** [microsoft/vscode#106806]
- VSCode Version:

```
Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T17:39:53.251Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
```
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Invoke global search from vscode: Cmd + Shift + F
This alone will trigger the Code Helper to lock up its CPU cycles to 99% and hangs the app for the most part.
![image](https://user-images.githubusercontent.com/13857038/93272387-379f4400-f76a-11ea-9d34-a21e3cd4f5c8.png)

Eventually the main thread prompts the user to close wait or reopen their window.
![image](https://user-images.githubusercontent.com/13857038/93275804-bf894c00-f772-11ea-95b7-6ddb7a577461.png)

Does this issue occur when all extensions are disabled?: Yes

This seems to be workspace specific issue. When I open another window for another directory the issue is not reproduced.

**Comment by roblourens** [comment]
This has been reported but I have not been able to reproduce it consistently. Disabling the "search on type" setting might help https://github.com/microsoft/vscode/issues/87254
