### ISSUE TITLE
Jupyter Notebook - kernel should start in cwd

### ISSUE THREAD

**Issue by pfarndt** [microsoft/vscode#106868]
Opening a (Julia) .ipynb on a **remote host** (via Remote-SSH) starts a (remote) julia kernel  as expected. The kernel process gets  a `--project=@.` (which is good), however, the working directory is set to my home directory on the remote host and not the directory of the ipynb. This way the kernel starts up with the wrong julia environment, which is very inconvenient and inconsistent to the behavior in jupyter lab.

**Comment by aeschli** [comment]
This issue needs to be filed against https://github.com/Microsoft/vscode-python/issues
Would you mind filing the issue there?
