### ISSUE TITLE
Predefined variables like ${file}  unavailable when using envFile in launch.json

### ISSUE THREAD

**Issue by mattgillard** [microsoft/vscode#106827]
Issue Type: <b>Bug</b>

I am using envFile in launch.json to create some source code file specific environment variables for use with Python.
Some variable substitutions work fine like, ${workspaceFolder}.
However any of the ${file} related predefined variables (mentioned [here](https://code.visualstudio.com/docs/editor/variables-reference))  just do not seem to work.
They **do** expand correctly when I test with a task.json.
They also seem to expand correctly when I test putting them into an "args" directive in launch.json. It just seems like "envFile" is the blocker.

launch.json example:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal",
      //"envFile": "\\Users\\matt\\dev\\test\\test.py.env" // works
      //"envFile": "${file}.env" // doesnt work
      //"envFile": "${workspaceFolder}/test.py.env" // works
      "envFile" : "${workspaceFolder}\\${fileBasename}.env" // doesnt work
    }
  ]
}
```
|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (0.65GB free)|
|Process Argv|--remote=wsl+Ubuntu --crash-reporter-id bd01a4c9-1b0b-4ecf-b3fa-7c25074d2420|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1991)|
|Memory (System)|12.37GB (5.98GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.13.0
cform|aws|0.0.24
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.6.0
auto-close-tag|for|0.5.8
vscode-journal-view|Gru|0.0.26
AzureFunctionsSnippets|hha|0.1.0
rainbow-csv|mec|1.7.1
compare-folders|mos|0.17.0
vscode-azurefunctions|ms-|0.24.0
vscode-azurestorage|ms-|0.10.0
vscode-cosmosdb|ms-|0.14.0
csharp|ms-|1.23.2
python|ms-|2020.8.109390
remote-wsl|ms-|0.44.5
azure-account|ms-|0.9.3
js-debug-nightly|ms-|2020.9.1517
powershell|ms-|2020.6.0
debugger-for-chrome|msj|4.12.10
vetur|oct|0.27.3
vscode-journal|paj|0.10.0
vscode-yaml|red|0.10.1
vscode-essentials-snippets|rob|2.0.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by mattgillard** [comment]
Apologies - not sure why the VSCode version is not recorded.

Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by weinand** [comment]
I cannot reproduce this:

![2020-09-16_11-46-33 (1)](https://user-images.githubusercontent.com/1898161/93321779-ded7b600-f812-11ea-8f04-0929fe4399fa.gif)

Are you running a remote setup "Windows/WSL2"?

**Comment by mattgillard** [comment]
Yes I am. But I tried it both in WSL2 and locally on Windows.  Let me try on a different machine (my mac) and get back to you. I literally spent hours on this today....
The only difference for me is that I am using Python.

**Comment by weinand** [comment]
If there is an issue, then it is because this is a remote setup with WSL2.

**Comment by mattgillard** [comment]
Ok - I can confirm node works fine (local Windows I tested). 
It appears its a Python only issue (presents itself in both WSL2 and local Windows environments).
Thanks for checking!

**Comment by mattgillard** [comment]
For those who find this in the future - there is a [bug](https://github.com/microsoft/vscode-python/issues/11915) already logged with the vscode-python extension on this which I had not seen until now.
