### ISSUE TITLE
javascript debugger doesn't work after upgrading to version 1.49.0

### ISSUE THREAD

**Issue by swilliams-a3digital** [microsoft/vscode#106891]
After upgrading to VS code debugging typescript compiled to javascript, running on node.js  no longer works.  I get an empty break point.  After disabling this setting: "debug.javascript.usePreview", everything works fine again:

"debug.javascript.usePreview": false

Something does not work correctly with the preview.  This should be disabled by default until it works.

- VSCode Version: 1.49.0
- OS Version: mac os Catalina 10.15.6

Steps to Reproduce:

1. compile node.js server code to a dist folder, attach debugger and try to debug.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
Please share a trace log using the following instructions:

>If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

/needsMoreInfo
