### ISSUE TITLE
Delete the settings of an extension when uninstall

### ISSUE THREAD

**Issue by pierretallotte** [microsoft/vscode#106852]
The settings of the extensions of a user are located in `~/.config/Code/User/settings.json`.
However, when an extension is uninstalled, this file continues to contain informations about the old extension.
Therefore, if the extension is installed again, the old settings are taken into account.

To avoid this issue, I think it can be interesting to delete the settings of an extension when it is uninstalled.

**Comment by sandy081** [comment]
/duplicate

Thanks for reporting but this issue is already reported before. You can find the issue in our open issues.

**Comment by pierretallotte** [comment]
@sandy081 I'm sorry but I'm not able to find the corresponding open issue. Maybe I'm not using the good keywords. Where can I find it?
Thanks.

**Comment by sandy081** [comment]
Sorry, I too can't find it. Will open this as feature request and if I find a duplicate I will tag it.
