### ISSUE TITLE
VS Code fails to start if current directory no longer exists

### ISSUE THREAD

**Issue by rmunn** [Microsoft/vscode#10689]
- VSCode Version: Version 1.4.0 (commit 6276dcb)
- OS Version: Ubuntu Linux 14.04

## Steps to Reproduce:

1. On Linux (or possibly on OS X), open two separate terminal windows.
2. In both windows, run `cd` with no arguments so you're in your home directory.
3. In the first terminal, run:
    * `mkdir foo`
    * `cd foo`
    * `echo "Hello" > file.txt`
4. In the second terminal, run:
    * `mkdir bar`
    * `cd bar`
    * `code ~/foo/file.txt`
5. VS Code starts up fine, and loads `~/foo/file.txt` without problems.
6. Exit VS Code.
7. In the first terminal, run `rmdir ~/bar`. This will succeed on Linux, because processes don't lock their current working directory while running. So having a terminal window open, `cd`'ed into `~/bar`, does not lock `~/bar` and it can therefore be removed by other terminals.
8. Now in the second terminal, run `code ~/foo/file.txt` again. VS Code will fail with the following error:

```plain
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
sh: 0: getcwd() failed: No such file or directory
path.js:1184
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1184:25)
    at Function.Module._resolveLookupPaths (module.js:263:17)
    at Function.Module._resolveFilename (module.js:330:31)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/share/code/resources/app/out/cli.js:5:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

## Notes

I believe this could also be reproduced on OS X, because I think the OS X file system works similarly to Linux, but I don't have access to a Mac to test it. I was able to verify that this does NOT occur on Windows, because on Windows you can't remove a directory while any Command Prompt windows are open in that directory, and so this bug reproduction fails on step 7 on a Windows machine.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2259

**Comment by rmunn** [comment]
I looked for duplicates before reporting, but missed that one. Sorry.
