### ISSUE TITLE
[Search] Allow to use "\t" as a replacement for a tabs or similar

### ISSUE THREAD

**Issue by TobiasSekan** [microsoft/vscode#106859]
Currently there is no easy way to find tabs in your program code. Find a amount of spaces is much easier.

![2020-09-16 14_17_43-●](https://user-images.githubusercontent.com/17874713/93335969-721ae680-f827-11ea-9be6-53acaae1f9e2.png)

Current workaround
1. Write one ore more tabs (or mix of text and tabs)
2. Mark it
3. Copy it to the clipboard
4. Click `ctrl+f` or paste into the search widget and click on search

**Comment by IllusionMH** [comment]
/question
You can use `\t` with RegExp search (third button in input with `.*` icon)
