### ISSUE TITLE
Change Language Mode drop-down should allow filtering by file extension

### ISSUE THREAD

**Issue by edmelly** [microsoft/vscode#106886]
In the [Change Language Mode drop-down](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file), it would be nice if we could filter by extension. e.g. at the moment for a `.jsx` file, typing `jsx` returns nothing. I have to start typing `javascriptreact`:

![select-language-type-vscode](https://user-images.githubusercontent.com/2462659/93381755-094c6200-f859-11ea-8f18-730f1c068685.png)

For TypeScript, `ts` gives you:

![select-language-type-vscode-ts](https://user-images.githubusercontent.com/2462659/93381956-503a5780-f859-11ea-90e9-f7a3503c5c44.png)

Which doesn't seem intuitive. I'd expected the same results, but taking the extension into account and ordering them:

```
TypeScript > TypeScript React > JSON with Comments > CSS (Styled Components
```

**Comment by bpasero** [comment]
I think this is an area where a PR could try to implement this and then we can test how it behaves.

**Comment by tomerstav** [comment]
I considered adding a hide ext. option after click but I think the current implementation is cleaner. Please let me know your thoughts. @bpasero @edmelly

**Comment by incakoala** [comment]
Hi there! I'm a part of Open Source Day and would love to contribute to this issue!

**Comment by incakoala** [comment]
@bpasero I was looking at @ tomerstav and looks like we haven't decided on whether or not we should display the extension names in the descriptions. If we DO want to display them it should be an easy fix (adding extensions in the description). Please me know how you want to go about this! thanks

<img width="730" alt="Screen Shot 2020-10-01 at 3 10 15 PM" src="https://user-images.githubusercontent.com/38148568/94868855-d5487380-03f8-11eb-80dd-38face83f3c2.png">

**Comment by tomerstav** [comment]
It's a trivial fix if we add the description. Would be more complicated to allow search without description. That's why I thought it was best to have that extra action in there.

**Comment by bpasero** [comment]
Is there still interest in working on this?

**Comment by bpasero** [comment]
**Verification:** in the language mode picker (from the status bar when a text editor is opened) you can type the name of any file extension (e.g. `jsx`) and it will show the language (e.g. `javascriptreact`) even when the pick item does not show that text.

**Comment by jrieken** [comment]
@bpasero I see this working but it also contains some unexpected results, like typing "js"  and find "html". Is that part of the strategy?

<img width="1289" alt="Screenshot 2021-01-26 at 15 32 38" src="https://user-images.githubusercontent.com/1794099/105858538-ba26f280-5feb-11eb-90aa-74eefd5659bc.png">

**Comment by bpasero** [comment]
@jrieken yeah the change was to make all extensions of any language be searchable even when the display label does not show it. And in this case you seem to be hitting `jsp` or `jshtm`.

However I wonder if we should make this smarter and only show the entry if you type the exact name of it?

**Comment by jrieken** [comment]
How about showing those strings (as details or description) but only when they have matched something. That would self-explain things

**Comment by bpasero** [comment]
Yeah that is a possibility but I wonder if https://github.com/microsoft/vscode/issues/106886#issuecomment-767637941 would help produce less unwanted results. I will take a look tomorrow to see if there is something to improve here.

The radical alternative is to simply show all extensions in each label but we felt that this would produce too long labels for the picker.
