### ISSUE TITLE
Selection Highlight issue when selected text is followed by '-' in long files

### ISSUE THREAD

**Issue by arnonshp** [microsoft/vscode#106840]
When using pointers in C/C++ code the text would usually look like this:

ptr->member

In long files (I started seeing it from line **13840**), when highlighting "ptr", matching strings in the file are not highlighted. However, when highlighting "ptr-" only then the matching strings are highlighted. Also, if ptr is mentioned earlier in the code and is not followed by '->', highlighting that string will not highlight the ptr occurrence which is followed by a "->" later in the code.

**Comment by alexr00** [comment]
Can you please provide a full example of the behavior you're seeing?

**Comment by arnonshp** [comment]
Here's an example: unitPtr is selected but its occurrences few lines below are not highlighted.

![Highlight_issue](https://user-images.githubusercontent.com/8546722/95015327-dd9cea80-0654-11eb-894c-3b10ceee20c6.jpg)

Here's what happens when I also select the hyphen after unitPtr:
![Highlight_issue_hyphen](https://user-images.githubusercontent.com/8546722/95015380-379db000-0655-11eb-96ca-99c456b9ab89.jpg)

This time, the next occurrences are highlighted,

I would expect that selecting only unitPtr will highlight all its occurrences whether they are followed by hyphen or not.

**Comment by alexr00** [comment]
Sorry, I wasn't clear enough, can you please proved a full example that I can **copy/paste**?

**Comment by arnonshp** [comment]
For that I need to share my workspace which I can't do.  You should try this with very long files and see if it reproduces.
