### ISSUE TITLE
Filter codicon is not visible

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#106829]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/10746682/93301565-ee4a0580-f7f8-11ea-8649-8c4317233e77.png">

**Comment by sandy081** [comment]
Also in problems view

**Comment by misolori** [comment]
Seems like the class is applied accordingly:

https://github.com/microsoft/vscode/blob/909760587f7e172cb63a7d62c8684362590ba274/src/vs/workbench/contrib/extensions/browser/extensionsViewlet.ts#L543

But the `-` in the class is being stripped out:

![image](https://user-images.githubusercontent.com/35271042/93353956-5ac10680-f7f1-11ea-8021-cd36defa70a9.png)

![image](https://user-images.githubusercontent.com/35271042/93353988-657b9b80-f7f1-11ea-83ea-809dbfedce79.png)

@eamodio did you say you saw something similar with subemenu actions? This feels like it's related to `SubmenuAction`.

**Comment by eamodio** [comment]
I don't think this is related to the fix that I made here: https://github.com/microsoft/vscode/commit/0eee546cc5c8d1dff9f12730777873a10bc47e72

**Comment by misolori** [comment]
Thanks @eamodio for fixing. Looks like this was caused via https://github.com/microsoft/vscode/commit/863acbab188c7248531fdc3c5f04783f315fcd68 (fyi @joaomoreno)

**Comment by joaomoreno** [comment]
Ooof should've seen that one coming. Thanks for the fix @eamodio. We really got to stop having multiple class names in a single string. https://github.com/microsoft/vscode/issues/103454#issuecomment-692053199
