### ISSUE TITLE
where is code display and/or console.log

### ISSUE THREAD

**Issue by destroyer9** [Microsoft/vscode#10687]
- VSCode Version: latest*
- OS Version: (is this including windows? if so im using windows 8 upgrade to 10)

@vscodeerrors  ok so i dont know if you havent noticed, but i cant seem to find the console.log or the viewing thing. please add that to the main screen as a button that you can click tht opens it up.

*latest on day that i posted this (8/18/2016)

**Comment by destroyer9** [comment]
i checked everywhere and i couldnt find a button for it if there is can you tell me where it is i got VS today

**Comment by alexandrudima** [comment]
@destroyer9 I am not sure what you mean? Do you run a task (`tasks.json`), do you launch a program to debug (`launch.json`), do you run a command inside the integrated terminal, do you want to see the developer console, in what area is your problem? (i.e. what do you do and what is missing)

**Comment by destroyer9** [comment]
well i look in where the vs code folders should be in file explorer and nothing i made is there and i typed `(console.log)'hello world'` and i should have seen hello world in the console. (and im using an unsaved file) and i dont know how to launch this dev console you're talking about so can you tell me how to do that (i got VS yesterday when i posted this)

**Comment by destroyer9** [comment]
oh and how do you add labels

**Comment by dbaeumer** [comment]
@destroyer9 can you please provide a git repository or a zip that shows the problem. If you create a JS file like
```js
console.log('Hello World');
```
and want to see the output running the code then please read the docs here how to do this: https://code.visualstudio.com/docs/editor/debugging

**Comment by dbaeumer** [comment]
Without the additional information we can't work on this issue. Please ping when the information is available and we will reopen the issue.
