### ISSUE TITLE
Programming help/documentation viewing from VSCode without switching to browser

### ISSUE THREAD

**Issue by hermolaou** [microsoft/vscode#106848]
Hi,
Here's a feature request. It would be nice if VBCode had a built-in mini-browser that could be used to view programming language help, documentation, to make queries to StackOverflow, MDN etc. and some search engine. Typically, when using VSCode, there's a need to have a browser open to look up all that stuff and so, to switch between VSCode and the browser all the time.

Thanks.

**Comment by aeschli** [comment]
I haven't tried it out, but https://marketplace.visualstudio.com/items?itemName=masonicboom.web-browser seems to offer that.
