### ISSUE TITLE
Add history to search window

### ISSUE THREAD

**Issue by catalinc404** [microsoft/vscode#106831]
Search window window should have some sort of dropdown to select previous searches.

**Comment by IllusionMH** [comment]
In VS Code you can use <kbd>ArrowUp</kbd>/<kbd>ArrowUp</kbd> (or <kbd>Alt</kbd>+<kbd>ArrowUp</kbd>/<kbd>ArrowUp</kbd> works for multiline fields) to access history in some fields (search panel, search widget etc.)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/23099
