### ISSUE TITLE
Apple Silicon Experimental Build Restart after Settings Change does not work.

### ISSUE THREAD

**Issue by jbotte** [microsoft/vscode#106887]
- VSCode Version: Version: 1.50.0-exploration
- OS Version:Mac OS Big Sur 11.0 Beta (20A5364e) Apple Silicon (Arm)

Version: 1.50.0-exploration
Commit: 02c157e4258b4fc59515cad3194cda3f17eaa505
Date: 2020-09-10T21:43:07.171Z
Electron: 11.0.0-beta.4
Chrome: 86.0.4234.0
Node.js: 12.18.3
V8: 8.6.373-electron.0
OS: Darwin arm64 20.1.0

Steps to Reproduce:

1. Go to settings -> Application -> Update 
2. Set Mode to None
3. Receive Popup saying "A setting has changed that requires a restart to take effect."
4. Click Restart
5. App does not restart.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
This should be fixed in latest releases.
