### ISSUE TITLE
Asterisks not working in console filter

### ISSUE THREAD

**Issue by pappy74** [microsoft/vscode#106880]
Issue Type: <b>Bug</b>

I printed two lines to the Debug Console:

print("****")
print("@@@@")

When entering text in the filter, only the at-signs work. There is no change to the console output when entering the asterisks. I thought perhaps this was a regex, but escaping the asterisks doesn't help.

Additionally, the first time I tried this, the app immediately beach-balled, but I can't reproduce that behavior.

More testing... "/\*/\*/\*" matches lines with paths, so "\*" is obviously a wildcard of some sort... perhaps just a glob? But "\\*" doesn't match it literally, so ¯\\\_(ツ)\_/¯.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2191B CPU @ 2.30GHz (36 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 7, 6|
|Memory (System)|128.00GB (67.73GB free)|
|Process Argv|--crash-reporter-id 40358437-6b26-43a0-96dc-9ccf8df23aa0|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
Yeah the issue is that * has a special "glob" meaning.
We do not support escaping it at the moment but makes sense that we do.
