### ISSUE TITLE
Build Task fails with missing start directory

### ISSUE THREAD

**Issue by bbradshaw** [microsoft/vscode#106883]
Issue Type: <b>Bug</b>

The most recent insiders update seems to have broken my project tasks.  The project has the following .code-workspace which lives in /Users/ben/Documents:
```
{
	"folders": [
		{
			"path": "yerba"
		}
	]
}
```
Attempting to run a build task (with no cwd manipulation) fails in Insiders (but not stable):
```
 Executing task in folder yerba: coffee -m --compile --output . . <

The terminal process failed to launch: Starting directory (cwd) "/Users/ben/Documents/yerba/~/Documents/yerba" does not exist.
```

VS Code version: Code - Insiders 1.50.0-insider (9e505675670d65138405321a60b0df4ddec28799, 2020-09-16T05:43:58.570Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (4.36GB free)|
|Process Argv|--crash-reporter-id e43d853a-7c37-4a86-90dc-a6f808cdaffd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
terraform|has|2.2.3
coffeelinter|lky|1.4.0
python|ms-|2020.8.109390
debugger-for-chrome|msj|4.12.10

</details>

**Comment by alexr00** [comment]
Looks like a dulicate of https://github.com/microsoft/vscode/issues/106877
