### ISSUE TITLE
VSC doesn't let me click in random rows - my windows updated today, can this cause this bug?

### ISSUE THREAD

**Issue by sarkanytibor** [microsoft/vscode#106882]
Issue Type: <b>Bug</b>

I inserted for example a predefined built-in snippet "form" and i can't click in the highlighted 3 rows.

- every extension is disabled (I reactivated 1 extension after final test, no extensiont were active and bug still remained)

- every custom json setting is removed

- I run it as administrator

- pc restarted

- if I restart VSC it works again and I can click them

- UNTIL I add another "form" using the built in snippet

Do you have ever seen something like this?

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.23GB free)|
|Process Argv|--crash-reporter-id 3dc3553f-51a8-40a9-a2de-a839d6028789|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
snippet-creator|rya|0.1.3

</details>

![bug](https://user-images.githubusercontent.com/63600657/93376566-16b61c00-f85a-11ea-8185-b5cfd4fd6845.jpg)

**Comment by sarkanytibor** [comment]
Update: seems reinstalling vsc solved the problem, when I installed again and activated "custom css and js loader" then vsc showed this error again, so I guess it was the extension which modified files which couldn't be reverted by only a disable

**Comment by jrieken** [comment]
/needsMoreInfo

Is this still an issue then? I have also trouble following your steps.
