### ISSUE TITLE
Unexpected behaviour when open from terminal

### ISSUE THREAD

**Issue by alexgv99** [microsoft/vscode#106884]
Issue Type: <b>Bug</b>

The last update brought an akward behaviour in Linux Mint. When I open a VSCode Window from a terminal, the Cinamon workspace is changed to the first one I opened a VSCode window before. It's not the expected behaviour and it changed from the previous version.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:20:50.359Z)
OS version: Linux x64 5.4.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3105)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.59GB (0.15GB free)|
|Process Argv|/home/alexgv/workspace/licenciamento-admin --no-sandbox --crash-reporter-id 944b9aeb-0598-44c1-94a2-873f6ad395d5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
read-only-indicator|ale|3.4.0
vscode-browser-preview|auc|0.6.7
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.36.3
mustache|daw|1.1.1
vscode-eslint|dba|2.1.8
eslint-disable-snippets|drK|1.2.0
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-great-icons|emm|2.1.56
react-native-react-redux|EQu|2.0.4
prettier-vscode|esb|5.6.0
vscode-firefox-debug|fir|2.9.1
todo-tree|Gru|0.0.178
vscode-peacock|joh|3.8.0
vscode-styled-components|jpo|0.0.31
regionfolder|map|1.0.12
sort-typescript-imports|mic|1.4.1
dotenv|mik|1.0.1
vscode-html-format|moh|0.0.4
graphql|mqu|0.1.2
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.6.0
vsliveshare|ms-|1.0.2740
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.10
material-icon-theme|PKi|4.3.0
typescript-hero|rbb|3.0.0
vscode-yaml|red|0.10.1
create-react-tsx-component|ric|1.4.3
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
move-ts|str|1.12.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|10.2.0
vscode-js-console-utils|wht|0.7.0
vscode-surround|yat|1.0.2
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by VxMxPx** [comment]
This is happening on Arch Linux, Gnome Shell too, and it's very frustrating. No matter in which way vscode is opened, either shortcut or terminal. It will always switch to the workspace from which initial window was opened. See a short gif for clarification:


![ezgif-4-b5c12fcd8bb3](https://user-images.githubusercontent.com/108407/93770253-3d8a9e80-fc1c-11ea-9a6d-f3dca81deb5b.gif)

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/106727

Can you check if this is fixed in latest insiders https://code.visualstudio.com/insiders/
