### ISSUE TITLE
Support syntax-highlight CompletionItem.detail when shown above the documentation

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#106862]
`CompletionItem` has a `detail` field that is documented as:

> A human-readable string with additional information about this item, like type or symbol information.

It's a `string` and is rendered above the documentation when the extra popup is open. However it doesn't get any syntax highlighting so it looks kinda bad:

![Screenshot 2020-09-16 at 14 06 34](https://user-images.githubusercontent.com/1078012/93341333-e2286d00-f825-11ea-9dee-6857ac0bcff6.png)

We can do syntax highlighting in the `documentation` field (as it's `string | MarkdownString`):

![Screenshot 2020-09-16 at 14 07 32](https://user-images.githubusercontent.com/1078012/93341407-fb311e00-f825-11ea-88f6-58e9fa805d14.png)

However if we put the signature there, then it will be duplicated because it's also in the `detail` (and if we remove from `detail` it won't ship in the collapsed completion list).

It would be nice to support highlighting this in some way (whether it's by extending the type, just always doing it, or having some way to suppress the `detail` from the extended popup so it can be inserted above the docs manually).

**Comment by jrieken** [comment]
I actually don't think that we want this. Today, details show inline with the item label or atop the documentation. We cannot render markdown as inline label which would mean no-details for markdown-style-details which then would make then just like documentation. So, the low hanging thing is to use the documentation property which does support markdown and then either leave out details or have some plain text in there.

**Comment by DanTup** [comment]
> So, the low hanging thing is to use the documentation property which does support markdown and then either leave out details or have some plain text in there.

The problem is that we can't hide the detail from the top of the documentation, and we want to show the same information in each - type information.

Now we have to choose between having plaintext type info in the in-line details, or having syntax-highlighting type information in the documentation - but we can't have both.

One suggestion above was:

> or having some way to suppress the detail from the extended popup so it can be inserted above the docs manually

Is that not possible?

**Comment by KamasamaK** [comment]
Looks like #34188

**Comment by jrieken** [comment]
True - but same reasoning applies.
