### ISSUE TITLE
Snippets are not cached and take too long to show up

### ISSUE THREAD

**Issue by adamreisnz** [microsoft/vscode#106928]
Issue Type: <b>Bug</b>

Since a few versions ago, snippets load very slowly, and don't appear to be cached. That means that when I am typing a snippet shortcut, I need to wait an excessive amount of time for the suggestions + snippets to show up, despite the setting set to 0ms delay.

For fast types/coders this is very frustrating, because we don't have time to wait for the snippets to load and show up every time we type them.

It's also strange, because I only have 3 or 4 snippets defined that I frequently use. It shouldn't be too complicated or memory intensive to cache those so they show up instantly when there's a code match.

I am running on a high end spec 2020 Macbook air, so computer performance should not be the cause of this issue.

This used to be much faster on an older version of VS Code.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz (8 x 1200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.3.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
file-icons|fil|1.0.25
gc-excelviewer|Gra|3.0.40
name-that-color|gui|0.1.2
json2csv|kha|0.0.1
l13-diff|L13|0.28.1
prettify-json|moh|0.0.3
vetur|oct|0.27.3
multi-command|ryu|1.4.0
vscode-fileutils|sle|3.0.1
control-snippets|svi|1.9.1
reopenclosedtab|uyi|1.1.0
highlight-matching-tag|vin|0.9.9
vscode-todo-highlight|way|1.0.4

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
