### ISSUE TITLE
breadcrumb and outline distinguish getter and setter

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#106935]
Now the VSCode recognize them as same name property:

![Snipaste_2020-09-17_18-52-43](https://user-images.githubusercontent.com/41773861/93461184-fe580700-f916-11ea-853c-848c0e138619.png)

**Comment by mjbvz** [comment]
@jrieken Should we add new entries to `SymbolKind`?

**Comment by mjbvz** [comment]
The other option is adding `(get)` and `(set)` to the symbol label. However we don't do this for any other typescript symbols today

**Comment by jrieken** [comment]
New `SymbolKind` means new icons. fyi @misolori For now, it might be the easiest to use the detail string for this information
