### ISSUE TITLE
wsl.exe as default terminal, crashes with exit code 1

### ISSUE THREAD

**Issue by delize** [microsoft/vscode#106910]
- VSCode Version: 
```
Version: 1.49.0 (system setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```
- OS Version: Windows 10.19041

Steps to Reproduce:

1.Set Windows Subsytem for Linux 2 as default 
2. Open up New Terminal Window, see crash details:
`The terminal process "C:\Windows\System32\wsl.exe" failed to launch (exit code: 1).`
```
The terminal process "C:\Windows\System32\wsl.exe" failed to launch (exit code: 1).
onDidChangeNotification @ breadcrumbsModel.ts:307
(anonymous) @ breadcrumbsModel.ts:307
fire @ event.ts:584
addNotification @ notifications.ts:169
notify @ notificationService.ts:69
_onProcessExit @ terminalInstance.ts:1032
async function (async)
_onProcessExit @ terminalInstance.ts:919
(anonymous) @ terminalInstance.ts:874
fire @ event.ts:584
_onExit @ terminalProcessManager.ts:280
(anonymous) @ terminalProcessManager.ts:169
fire @ event.ts:584
_kill @ terminalProcess.ts:156
async function (async)
_kill @ terminalProcess.ts:156
(anonymous) @ terminalProcess.ts:156
setTimeout (async)
_queueProcessExit @ terminalProcess.ts:156
(anonymous) @ terminalProcess.ts:156
EventEmitter2.fire @ C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\eventEmitter2.js:40
(anonymous) @ C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\terminal.js:86
emit @ events.js:223
Terminal.emit @ C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\terminal.js:148
(anonymous) @ C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:99
emit @ events.js:223
(anonymous) @ net.js:664
```
```
PS C:\Windows\System32> wsl -l --all --verbose
  NAME                   STATE           VERSION
* docker-desktop-data    Stopped         2
  Ubuntu                 Running         2
```

Does this issue occur when all extensions are disabled?: **Yes**

settings.json:
```
{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "window.zoomLevel": 0,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\wsl.exe",
    "terminal.integrated.automationShell.linux": ""
}
```

![image](https://user-images.githubusercontent.com/4028612/93416210-26356500-f85a-11ea-912e-99472bfcaf4d.png)
![image](https://user-images.githubusercontent.com/4028612/93416751-40237780-f85b-11ea-8665-ef586072f386.png)

I did search, but there are a massive amount of issues, and I don't see one specific to this, besides much older issues.

**Comment by delize** [comment]
Realized my issue when looking back through this. Because I installed Docker first when configuring my machine, it made that the default when running `wsl` standalone with no arguments resulting in the crashing terminal window.

Running `wsl --set-default Ubuntu` resolved this issue. 

Coincidentally, this seems like a minor oversight due to docker not dropping into a wsl compatible shell, and vscode/wsl not defaulting to an environment that has a compatible shell. 

Who or where should I go to reach out to on the wsl side for that?

**Comment by Tyriar** [comment]
You could follow this up with https://github.com/microsoft/WSL/issues

From VS Code's perspective, we assume WSL is set up correctly and just run wsl.exe.

**Comment by LeeRuns** [comment]
If you have a specific version of wsl which you want to have setup as the default THEN MAKE SURE TO DO THAT :)

Here is the way i ran it
1) get a list of different distros on your system
    ```
    PS C:\Users\Superman> wsl --list
    Windows Subsystem for Linux Distributions:
    Ubuntu (Default)
    Legacy
    docker-desktop-data
    docker-desktop
    Ubuntu-20.04
    ```
2) pick the one you want to use
    ```
    wsl --set-default Ubutnu-20.04
    ```

**Comment by Tyriar** [comment]
@LeeRuns are you running wsl through PS, as that behaves quite a bit differently to if you launched wsl directly as everything runs through a bunch of emulation (conpty) and PS may remove the sequences if it doesn't support them for example. If you run wsl directly as the default shell conpty runs in a special mode that skips the Windows console API emulation that is one of the things that could mess with this.

You can change the default shell in this dropdown:

![image](https://user-images.githubusercontent.com/2193314/97517414-61937b00-1952-11eb-8fb3-15d9d18f3f74.png)

I'd expect any WSL distro to work when launched as the default.
