### ISSUE TITLE
The behavior of "Escape + B" and "Escape + F" has changed

### ISSUE THREAD

**Issue by Dinduks** [microsoft/vscode#106908]
- VSCode Version: 1.49.0
- OS Version: Windows 10 latest update

Steps to Reproduce:

1. Open terminal
2. Type `word1_word2_word3`
3. Type Escape + B

What I expect to happen: the cursor moves to the second underscore (`word1_word2_▌word3`).

What happens: the cursor moves to the beginning of the line (`▌word1_word2_word3`).

Same behavior with "Escape + F" (F is for forward; B is for backward).

This behavior is inconsistent with pretty much all the terminals I've used, including VSCode's terminal from few days ago, and makes using the terminal clunky.

FWIW: the terminal doesn't respond to "Ctrl + f" anymore. Instead, it opens the search box, despite `keybindings.json` being configured not to (it has worked fine for months).

I don't know VSCode's codebase, but I'll be happy to take a look and submit a PR if somebody can give me some guidance.

Cheers.

Does this issue occur when all extensions are disabled?: Yes/No

I get `Ignoring option disable-extensions: not supported for code.` when trying to run code with `--disable-extensions`.

**Comment by thmzlt** [comment]
Updated to 1.49 and now can't use Ctrl+F to navigate the terminal command anymore. I can't change or delete the "Terminal: Focus Find" keybinding that is always assigned to Ctrl+F either.

**Comment by rzhao271** [comment]
@thmzlt that sounds like another issue. If that issue still persists for you on the latest Insiders, I recommend filing a new issue for it.

@Dinduks on Windows 10, pressing escape for me when following your steps on the latest Insiders just erases the whole line. I'm wondering whether the behaviour has changed for you again on the newest version?
