### ISSUE TITLE
Feature request: Show untitled file in language

### ISSUE THREAD

**Issue by rjrahul** [Microsoft/vscode#10699]
- VSCode Version: 1.4.0
- OS Version: OSX El Capitan

This is a feature request to view an untitled new file as a particular language. This would help view syntax format may be help while still being in an anonymous mode.

This is helpful in quick and dirty code that can be written tested and sent off to someone else.

**Comment by brodeuralexis** [comment]
On the bottom right, next to the smiley face, click on `Plain Text` to select your language

![ch-lang](https://cloud.githubusercontent.com/assets/11179144/17811703/e700ff06-65f1-11e6-96fd-39a5f68f3aad.PNG)

**Comment by rjrahul** [comment]
Thanks for pointing out. Please close the issue.
Regards,Rahul

Get Outlook for iOS




On Fri, Aug 19, 2016 at 7:18 PM +0530, "Alexis Brodeur" <notifications@github.com> wrote:












On the bottom right, next to the smiley face, click on Plain Text to select your language
