### ISSUE TITLE
settings sync reportet too many requests

### ISSUE THREAD

**Issue by LaggAt** [microsoft/vscode#106966]
Issue Type: <b>Bug</b>

I had two instances of VS code running when I came home, both are reporting:
"Settings sync is disabled because the current device is making too many requests. Please report an ussue  by providing the sync logs."

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (2.90GB free)|
|Process Argv|--crash-reporter-id b0bb833b-2a90-412c-8bf0-5b1c6f2ff78f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Home Assistant Dev|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2593)|
|Memory (System)|12.40GB (7.33GB free)|
|VM|0%|
</details><details><summary>Extensions (115)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|11.3.1
project-manager|ale|11.3.0
vscode-sqlite|ale|0.9.0
ng-template|Ang|0.1001.0
vscode-color|ans|0.4.5
All-Autocomplete|Ati|0.0.23
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
sqlformatter|bre|0.0.7
npm-intellisense|chr|1.3.1
codestream|Cod|8.3.7
gitignore|cod|0.6.0
macros|ctf|0.0.4
vscode-ssh|cwe|1.6.2
angular-schematics|cyr|4.3.0
ionic3-vs-ionView-snippets|dan|1.0.2
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.13
vscode-uppercasesql|epl|2.1.4
prettier-vscode|esb|5.6.0
pip-packages|etm|0.4.3
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
code-runner|for|0.11.0
vscode-mysql|for|0.4.0
auto-using|Fud|0.7.15
vscode-tfs|gen|2.0.0
vscode-pull-request-github|Git|0.20.0
gc-excelviewer|Gra|3.0.40
todo-tree|Gru|0.0.178
vscode-test-explorer|hbe|2.19.1
npm-dependency-links|her|1.1.0
vscode-settings-cycler|hoo|1.0.1
output-colorizer|IBM|0.1.2
easy-snippet|inu|0.6.2
customize-ui|ioc|0.1.48
monkey-patch|ioc|0.1.10
vscode-essentials|jab|1.5.0
search-editor-apply-changes|jak|0.1.1
vscode-edit-csv|jan|0.4.2
hungry-delete|jas|1.6.0
cordova-dev-essentials|jew|0.0.1
ionic2-vscode|jgw|1.0.0
vscode-text-pastry|jkj|1.2.0
sql-language-server|joe|0.12.0
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.8.0
solidity|Jua|0.0.76
chat|kar|0.35.0
vscode-home-assistant|kee|1.9.0
vscode-commitizen|Kni|0.9.3
vscode-format-context-menu|lac|1.0.4
aw-watcher-vscode|lin|0.4.1
vscode-python-test-adapter|lit|0.5.0
ionic-extension-pack|loi|0.2.2
vsls-whiteboard|los|0.0.11
metago|met|4.2.0
MetaJump|met|1.1.1
MetaWord|met|1.2.1
git-graph|mhu|1.26.0
vscode-checkpoints|mic|1.3.1
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
mssql|ms-|1.9.0
python|ms-|2020.8.109390
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
powershell|ms-|2020.6.0
vsliveshare|ms-|1.0.2740
vsliveshare-audio|ms-|0.1.91
team|ms-|1.161.0
cordova-tools|msj|1.9.5
debugger-for-chrome|msj|4.12.10
debugger-for-edge|msj|1.0.15
sqltools|mtx|0.23.0
gremlins|nho|0.23.1
vscode-json-editor|nic|0.2.3
angular-console|nrw|13.0.0
openhab|ope|0.7.0
material-icon-theme|PKi|4.3.0
rxjs-snippets|pko|0.0.2
polacode|pnp|0.3.4
vscode-xml|red|0.13.0
explorer-exclude-vscode-extension|Red|1.2.0
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|3.4.3
vscode-multiclip|sle|0.1.5
autoimport|ste|1.5.3
rewrap|stk|1.13.0
code-spell-checker|str|1.9.0
control-snippets|svi|1.9.1
poor-mans-t-sql-formatter-vscode|Tao|1.6.10
open-in-browser|tec|2.0.0
ionic2|Tha|3.0.2
pdf|tom|1.1.0
Angular2|UVB|0.4.1
vscodeintellicode|Vis|1.2.10
codetour|vsl|0.0.35
gistfs|vsl|0.1.8
vscode-wakatime|Wak|4.0.8
local-history|xyz|1.8.1
markdown-all-in-one|yzh|3.3.0
json|Zai|2.0.1

(2 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
This is expected and designed. Please restart and you can turn on Sync again .

Can you please provide us the Settings Sync log from Output view when this happened? If you restarted VS Code and lost the log when this issue occurred, you can find it in the logs folder on your disk (run the command `Open Logs Folder...`). This will show us the requests to diagnose.

**Comment by LaggAt** [comment]
I'll do when I get the message next time.

**Comment by sandy081** [comment]
Great, will close the issue until then. Please reopen it with required info.
