### ISSUE TITLE
Repos in asset unables

### ISSUE THREAD

**Issue by samuel-velazquez** [microsoft/vscode#106903]
Issue Type: <b>Feature Request</b>

Attribute only statement only main.. and framework so plug-in or template parameter: sync this boolean test if run so also tour changes feed last member.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.17134

**Comment by aeschli** [comment]
Sorry, I don't understand what you mean. Can you add more description and steps and maybe a screenshot?

**Comment by samuel-velazquez** [comment]
desing.. this above time and figth town-- andwer only process so remember attribute if sequense out-line

**Comment by aeschli** [comment]
Closing the issue due to lack of details provided. Please add complete steps and descriptions of what you see and what you expect.
