### ISSUE TITLE
viewColumn assignment won't open in rightmost position

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#106973]
- VSCode Version: 1.49.0
- OS Version: Windows 10

Steps to Reproduce:
1. Open two files in separate editors in VS Code
2. In extension development code, utilize the VS Code API to designate extension behavior to open a new editor (of type webViewPanel) in the specified viewColumn. 
3. Specify the viewColumn = 1+ (current number of editors open)

Expected: The new editor will open in a new, right-most column.

Actual: The new editor opens as a tab inside a new column, in between the two open editors.  

Does this issue occur when all extensions are disabled?: Yes/No

I am currently trying to use the VS Code API for extension development. The behavior I am trying to achieve is to open a new webViewPanel editor on the rightmost column on the screen. I have tried assigning the viewColumn of the new editor to all available options shown in the API, but the editor opens in between the currently opened editors. 

https://code.visualstudio.com/api/references/vscode-api#ViewColumn

**Comment by mjbvz** [comment]
Here's the call that eventually creates the editor in a specific group:

https://github.com/microsoft/vscode/blob/51dc3193d3f92c0d1854be9b1a462d0cedbd8a7e/src/vs/workbench/contrib/webviewPanel/browser/webviewWorkbenchService.ts#L194

And here's the extension host side that triggers that call in the main VS Code process:

https://github.com/microsoft/vscode/blob/23fe7a39de1cf6eff8044b8ea1ff30d692b98f6f/src/vs/workbench/api/common/extHostWebviewPanels.ts#L190

**Comment by mjbvz** [comment]
Another place to check internally: 
https://github.com/microsoft/vscode/blob/51dc3193d3f92c0d1854be9b1a462d0cedbd8a7e/src/vs/workbench/api/browser/mainThreadWebviewPanels.ts#L161

This is where the view column is actually calculated

**Comment by alyssajotice** [comment]
@jramsay and I found a workaround where we changed the "active" editor to the rightmost group right before opening our new editor window. We had the new editor set to open in viewColumn = beside, and this made the new editor open on the rightmost side of the screen. 

To change the active editor, I used the vscode command workbench.action.focusLastEditorGroup.
