### ISSUE TITLE
Remote: Disallow saving workspace locally

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#106990]
When saving a workspace it's possible to choose 'Show Local'. and save the workspace locally.

This will result in workspaces as seen in https://github.com/microsoft/vscode-remote-release/issues/3660#issuecomment-692787213 
which are not well supported.

The UI should only allow to save in the remote file system.

**Comment by soustruh** [comment]
Guys, sorry if I should have written this elsewhere, but this really collides with my workflow. I am used to opening the VSCode on my Windows machine via saved workspaces, which then connect me to remote SSH machine. Luckily my saved workspaces still work, but I cannot add more unless I manually edit the files.

Is there another preferred way that would solve my problem? I need to have a one-click way of opening VSCode (Windows machine) with remote SSH automatically connected and certain remote project folder automatically opened (probably in a workspace).

**Comment by w-** [comment]
i am also looking for the solution to this. I heavily use 
file -> save workspace -> "show local"

to save a remote workspace locally.

**Comment by jonnyijapan** [comment]
I used it a lot too. I reported this as a feature request here. https://github.com/microsoft/vscode/issues/109713
