### ISSUE TITLE
Auto attach interferes with code command

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#106920]
Running out of sources (with server bits)
The status bar has the auto attach control set to auto

- From the remote indicator, run `Remote: Test-Resolver: New Window`
- In the remote window, open the integrated terminal and run `code.sh test.txt` to open a file
   - the terminal reports that a port has been tunneled
   - the window shortly enters debug mode
  
![auto-attach](https://user-images.githubusercontent.com/6461412/93436525-32a5d600-f8cb-11ea-8948-bd495eab9604.gif)

**Comment by aeschli** [comment]
FYI @isidorn @weinand

**Comment by connor4312** [comment]
Thanks -- I've added some logic that should prevent this. Somewhat annoying since we seem to name the cli differently on different systems but it should work.
