### ISSUE TITLE
Inconsistent Commit All/Staged Location

### ISSUE THREAD

**Issue by VazMike** [microsoft/vscode#106998]
- VSCode Version: 1.49.1
- OS Version: Windows 10

Steps to Reproduce:

1. Follow context menu in a screenshot below

![image](https://user-images.githubusercontent.com/14861435/93587897-4167b800-f9b3-11ea-9a51-851cfc353943.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
What is the problem here?

**Comment by VazMike** [comment]
The order bugs me.
Amend section: `Commit All` `Commit Staged`.
Signed Off section: it is reversed.
I suggest swapping `Commit All (Signed Off)` `Commit Staged (Signed Off)`.

**Comment by joaomoreno** [comment]
Can you still repro this on the latest Insiders release?

![image](https://user-images.githubusercontent.com/22350/94682202-e58f1e80-0324-11eb-931f-15dd95417596.png)

**Comment by joaomoreno** [comment]
Yeah I can confirm this is fixed in `master`.
