### ISSUE TITLE
quick open should have prefill highlighted text

### ISSUE THREAD

**Issue by fredwangwang** [microsoft/vscode#106969]
Given I have some string highlighted in the editor (e.g. `sample.txt`)
When I click the keyboard shortcut to open the quick open menu,
I want to have the text `sample.txt` prefilled in the input field.

![Screen Shot 2020-09-17 at 4 44 01 PM](https://user-images.githubusercontent.com/21690857/93535938-38201200-f905-11ea-805e-9c8f76483322.png)

**Comment by fredwangwang** [comment]
Hi @bpasero ,could you review this again? I submitted this as a feature request, because currently quick open menu does not pre-fill the highlighted text, which is not convenient and is not consistent with the behavior of search:
![image](https://user-images.githubusercontent.com/21690857/93609043-96420900-f988-11ea-85c8-fe5fc902e0ef.png)
![image](https://user-images.githubusercontent.com/21690857/93609221-cbe6f200-f988-11ea-9c0a-d6bdb918bf12.png)

**Comment by bpasero** [comment]
Sorry I thought we had a solution for this in place already, but we do not. Here is how symbols do it:

https://github.com/microsoft/vscode/blob/696dca786ac73ca0779a65e18f4bdb613d66b26f/src/vs/workbench/contrib/search/browser/symbolsQuickAccess.ts#L51-L60

Related issues: https://github.com/microsoft/vscode/pull/41586, https://github.com/microsoft/vscode/issues/42297

There is probably an extension by now that can do it.
