### ISSUE TITLE
 Ctrl+Alt+Down or Ctrl+Alt+Up  stopped working

### ISSUE THREAD

**Issue by d4libor** [microsoft/vscode#106994]
Issue Type: <b>Bug</b>

multi line text -> Ctrl+Alt+Down or Ctrl+Alt+Up .
multi-cursor stopped working, no additional cursors are added

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (18.87GB free)|
|Process Argv|--crash-reporter-id a81d7504-12e9-4252-a115-dd9abd3db3b6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
asciidoctor-vscode|asc|2.8.3
bracket-pair-colorizer-2|Coe|0.2.0
githistory|don|0.6.9
xml|Dot|2.5.1
LogFileHighlighter|emi|2.9.0
auto-close-tag|for|0.5.8
plantuml|jeb|2.13.13
ecdc|mit|1.3.0
oracledevtools|Ora|19.3.2
material-icon-theme|PKi|4.3.0
vscode-xml|red|0.13.0
partial-diff|ryu|1.4.1

</details>

**Comment by alexdima** [comment]
There has been an update to an Intel Driver that adds ctrl+alt+up and ctrl+alt+down as hotkeys in Windows. This driver "steals" all such keybindings from all Windows applications. Please try to configure it and remove those keybindings.

**Comment by d4libor** [comment]
Any idea where can I disable this for intel driver?

**Comment by alexdima** [comment]
I am sorry, but I do not know. You can check if this is indeed the case on our side by looking if the keybinding reaches vs code. If vscode receives only "ctrl+alt+" and not "ctrl+alt+up" or so it means that someone is eating up the keybinding, as I said, most likely the Intel Graphics Driver:

![keyboard-input](https://user-images.githubusercontent.com/5047891/80482640-da3e5e00-8954-11ea-9583-0f652b0595a8.gif)

**Comment by d4libor** [comment]
you were right, the problem was caused by intel graphics driver. even though system hotkeys were disabled, it was causing problems. yet after mere enabling and disabling them, the problem in vs code was resolved.
thank you for support.

![image](https://user-images.githubusercontent.com/47737015/93888121-e05c1f00-fce7-11ea-9746-486b03bb29d1.png)

**Comment by Cerlancism** [comment]
There is probably a bug in their command centre as for me the hotkeys are already disabled. I can only get this key combination working after opening the command centre at least once after every system startup.
