### ISSUE TITLE
Do not expose end point detail in the error message that is displayed to user

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#106989]
![image](https://user-images.githubusercontent.com/3372902/93329120-02076300-f81d-11ea-812a-ac7950cedc53.png)

**Comment by sandy081** [comment]
Following notification is shown when there is an authentication failure

<img width="477" alt="image" src="https://user-images.githubusercontent.com/10746682/97962201-f19f4d80-1db4-11eb-96c9-8b7188b09999.png">

In all other failures, following notification is shown

<img width="468" alt="image" src="https://user-images.githubusercontent.com/10746682/97962095-c4eb3600-1db4-11eb-949b-19ad878bbb5b.png">

**Comment by sandy081** [comment]
@lszomoru can you please verify this/

**Comment by lszomoru** [comment]
Looks like there are still places in which this occurs (ex: seeing the endpoint while hitting an error turning off sync)
<img width="461" alt="image" src="https://user-images.githubusercontent.com/3372902/100760053-a4cd8780-33f1-11eb-86af-557f7f853b9c.png">
