### ISSUE TITLE
[Web] MR Workspace folders are getting resolved before file system providers are available

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#106934]
Workspace folders shall not be resolved until the corresponding FS providers are available. This is done for following reasons:

- Start up performance
- Prevent deadlock - workspace folder can be with custom scheme from an extension. This needs waiting on extension to be activated and extension cannot be activated until start up.

In Web, Validation (that involves resolving folders) of workspace folders in a MR workspace (untitled) is being kicked off during the start up thereby causing potential deadlock.

**Comment by sandy081** [comment]
Root cause:

In web MR Workspaces have `vscode-user-data` schema and they are not going through non blocking start up path like in Desktop.

**Comment by roblourens** [comment]
Any way to verify this besides code review?

**Comment by aeisenberg** [comment]
I have a problematic codespace that I originally found this issue in. If the fix above is already available in codespaces, then I can verify that I no longer have the problem.

**Comment by roblourens** [comment]
Thanks!

**Comment by aeisenberg** [comment]
All right. I've confirmed that this is now working for me in codespaces.
