### ISSUE TITLE
Contributed buttons not showing up on Notebook files

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#106911]
Version: 1.50.0-insider
Commit: 9e505675670d65138405321a60b0df4ddec28799
Date: 2020-09-16T05:43:58.570Z (22 hrs ago)
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

In the PowerShell extension, we contribute this button on Notebook editors:
![image](https://user-images.githubusercontent.com/2644648/93417589-60543600-f85d-11ea-868e-ce94ed7f7bde.png)

this has disappeared in today's insider build.

Here's the code in our [package.json](https://github.com/PowerShell/vscode-powershell/blob/master/package.json#L435-L437):

```json
    {
          "when": "resourceLangId == powershell && notebookEditorFocused",
          "command": "PowerShell.DisableNotebookMode",
          "group": "navigation@102"
    }
```

I checked the context and it looks fine. It has both of those:

![image](https://user-images.githubusercontent.com/2644648/93417660-81b52200-f85d-11ea-88bf-d256a2e8a222.png)

Did something change? Unfortunately, this hurts our customers a bit since we rely on that button to let the user exit the Notebook experience so I hope we can get this sorted.

**Comment by roblourens** [comment]
Sorry for the slow response. This seems to work for me today, can you verify?

**Comment by TylerLeonhardt** [comment]
It's back! Thanks!
