### ISSUE TITLE
Select Multiple Rows Issue

### ISSUE THREAD

**Issue by heping1108** [microsoft/vscode#106976]
Issue Type: <b>Bug</b>

I can't use Ctrl+Alt hotkey anymore nowtimes.
So I can't select multiple rows easy way.
Please fix it asap if it's possible.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (9.18GB free)|
|Process Argv|--crash-reporter-id 69ccbcda-e4f9-4118-9561-369886ac89c7|
|Screen Reader|no|
|VM|21%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ionic-snippets|fiv|2.2.2
vue-snippets|hol|0.1.12
remote-wsl|ms-|0.44.5
vetur|oct|0.27.3
laravel-blade|one|1.24.0

</details>

**Comment by alexdima** [comment]
@heping1108 There has been an update to an Intel Driver that adds ctrl+alt+up and ctrl+alt+down as hotkeys in Windows. This driver "steals" all such keybindings from all Windows applications. Please try to configure it and remove those keybindings.
