### ISSUE TITLE
C++ could not read tuple header file

### ISSUE THREAD

**Issue by AnneMayor** [microsoft/vscode#106931]
- VSCode Version: 1.49.0
- OS Version: macOS Catalina version. 10.15.6

Steps to Reproduce:

1. Include header file "tuple" in .cpp file.
2. Initialize tuple Object in main() function and run the source code.

Does this issue occur when all extensions are disabled?: Yes

<img width="1743" alt="Screen Shot 2020-09-17 at 7 39 05 PM" src="https://user-images.githubusercontent.com/15176192/93459948-7de8d480-f91d-11ea-8bb6-962235407d2d.png">

**Comment by aeschli** [comment]
You need to file this against the C++ extension: https://github.com/microsoft/vscode-cpptools/issues
