### ISSUE TITLE
File name not displayed in the tab

### ISSUE THREAD

**Issue by Didier68** [microsoft/vscode#106950]
- VSCode Version: 1.49.0
- OS Version: Windows_NT x64 10.0.18363 
Commit : e790b931385d72cf5669fcefc51cdf65990efa5d
Date : 2020-09-10T13:22:08.892Z
Electron : 9.2.1
Chrome : 83.0.4103.122
Node.js : 12.14.1
V8 : 8.3.110.13-electron.0

Steps to Reproduce: ???

Sometimes, the tab with the name of the file being edited is not always visible: only the file type is displayed (I don't know why)

To resolve this display problem, you must close the editor of the file, then reopen it.
This problem app ( it appeared with the last version)

![Image 2020 09 17 5](https://user-images.githubusercontent.com/49448202/93499020-c2bb3e00-f912-11ea-8dfd-7cd43e9c5c16.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Did you pin that tab? Look at its context menu.

**Comment by bpasero** [comment]
see https://github.com/microsoft/vscode/issues/98161#issuecomment-690104534

**Comment by Didier68** [comment]
I discovered the "pin" option yesterday and I thought it would just freeze its position in the list of tabs (much like a column in Excel). Later, by wanting to return to the file, it was impossible to find it.
Thanks for your help.
