### ISSUE TITLE
Speedup performance.

### ISSUE THREAD

**Issue by olegKusov** [microsoft/vscode#106962]
Hi, I tried to compare Sublime and Vscode and feel that Vscode is not enought smooth and speedy. When I click on something in vscode it reacts after maybe 100-300ms. I feel it. But in Sublime it reacts instantly (maybe 10-30 ms). Moreover, in settings, where a lot of list elements scroll feels very laggy. What do you think about it? Maybe its time to create trully native and light crossplatform code editor with needed for development features but simple and light? I really don't like jetBrains editors because there is too much features and UI is too overloaded and hope Microsoft can invest and create really speedy editor.

Smooth editor really matters, because it helps us to be calm and don't think about lags.

**Comment by aeschli** [comment]
In order for us to investigate and act, please be more specific and avoid mentioning multiple problems in the same issue (file one issue per problem)
You say clicking on something. Where is that? Can you give detailed steps?
Also, what is your OS and machine spec? Does it reproduce without extensions?

**Comment by olegKusov** [comment]
> In order for us to investigate and act, please be more specific and avoid mentioning multiple problems in the same issue (file one issue per problem)
> You say clicking on something. Where is that? Can you give detailed steps?
> Also, what is your OS and machine spec? Does it reproduce without extensions?

[https://youtu.be/faVXPcSeLt8](url)

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
