### ISSUE TITLE
when stashing, use commit message if populated

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode#106907]
Current Behavior:
I have staged changes and typed a commit message.
I choose Stash > Stash
I am prompted to enter a stash description

Desired Behavior:
If commit message is entered, automatically use it as the stash description instead of prompting.

**Comment by hp77-creator** [comment]
Is this issue available to work on?

**Comment by qu63V6hfk1** [comment]
[abm-my.pdf](https://github.com/microsoft/vscode/files/5251161/abm-my.pdf)

**Comment by jrieken** [comment]
![Dec-01-2020 14-00-28](https://user-images.githubusercontent.com/1794099/100744135-9ffed880-33dd-11eb-8634-ead56d7820d8.gif)

doesn't work for me

**Comment by joaomoreno** [comment]
Sorry for the hassle @jrieken, but we decided to go and put this behind a setting instead: `git.useCommitInputAsStashMessage`.

**Comment by jrieken** [comment]
A little overkill if you ask me. But it works

**Comment by joaomoreno** [comment]
I know... explanation is here: https://github.com/microsoft/vscode/pull/107074#pullrequestreview-492673513
