### ISSUE TITLE
Test coverage (nyc) for extension tests (vscode-test + mocha) stopped working in 1.49.0

### ISSUE THREAD

**Issue by EduardSergeev** [microsoft/vscode#106977]
- VSCode Version: 1.49.0 - Insiders
- OS Version: Ubuntu 16.04 - 20.04

Steps to Reproduce:

1. Get extension project which has TypeScript tests (the recommended [vscode-test + mocha](https://code.visualstudio.com/api/working-with-extensions/testing-extension)) 
2. Run the test calculating test coverage using [nyc](https://github.com/istanbuljs/nyc) (configured for [TypeScript](https://github.com/istanbuljs/istanbuljs/tree/master/packages/nyc-config-typescript) project)
3. This should work in VSCode 1.45.0 - 1.48.0 but starting from 1.49.0 (and in current Insiders) it produces 0% coverage:
    with [1.45.0](https://travis-ci.org/github/EduardSergeev/vscode-haskutil/builds/684873577#L293):
   ```
   =============================== Coverage summary ===============================
   Statements   : 96.93% ( 568/586 )
   Branches     : 79.1% ( 140/177 )
   Functions    : 96.06% ( 122/127 )
   Lines        : 96.93% ( 537/554 )
   ================================================================================
   ```
   with [1.49.0](https://travis-ci.org/github/EduardSergeev/vscode-haskutil/jobs/727893902#L282):
   ```
   =============================== Coverage summary ===============================
   Statements   : Unknown% ( 0/0 )
   Branches     : Unknown% ( 0/0 )
   Functions    : Unknown% ( 0/0 )
   Lines        : Unknown% ( 0/0 )
   ================================================================================
   ```

> Does this issue occur when all extensions are disabled?:

Yes. Well, `--disable-extensions` cannot be used here since we are testing extension (which depends on some other extensions) but during the test run only necessary extensions are installed.

**Comment by aeschli** [comment]
Can you provide a sample repo that shows the problem?

**Comment by EduardSergeev** [comment]
> Can you provide a sample repo that shows the problem?

Sure, no problem. I took Microsoft's [helloworld-test-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample) and just [added coverage](https://github.com/microsoft/vscode-extension-samples/compare/master...EduardSergeev:coverage-example).  
It works as expected with [1.48.0](https://github.com/microsoft/vscode-extension-samples/commit/d15711e13b2b6887c8d39742637c793737c96496):

```bash
  Extension Test Suite

Congratulations, your extension "helloworld-sample" is now active!

    ✓ Activate extension (90ms)

  1 passing (92ms)

Exit code:   0
Done


=============================== Coverage summary ===============================
Statements   : 100% ( 6/6 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 2/2 )
Lines        : 100% ( 6/6 )
================================================================================
```

but fails to produce any coverage results in [1.49.0](https://github.com/microsoft/vscode-extension-samples/commit/9329686a0d9136163b9e9d57a5423f43142715b2):

```bash
  Extension Test Suite

Congratulations, your extension "helloworld-sample" is now active!

    ✓ Activate extension (41ms)

  1 passing (45ms)

Exit code:   0
Done


=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
```

 or (same picture) in [Insiders](https://github.com/microsoft/vscode-extension-samples/commit/8bb8c50e99f55fc62eae82ea0c8efe4c3e6e59a7)

**Comment by EduardSergeev** [comment]
OK, the behaviour is actually depends on the platform we run the test on.  
I added [matrix build](https://github.com/EduardSergeev/vscode-extension-samples/compare/coverage-example...EduardSergeev:coverage-example--build) which runs it on all available OS's in [Github actions](https://github.com/EduardSergeev/vscode-extension-samples/runs/1136782901) and it seems that:
- on Ubuntu it behaves is described above: works on [1.48.0](https://github.com/EduardSergeev/vscode-extension-samples/runs/1136782877#step:5:100) and fails on [1.49.0](https://github.com/EduardSergeev/vscode-extension-samples/runs/1136782879#step:5:61) and above
- on Windows it [fails](https://github.com/EduardSergeev/vscode-extension-samples/runs/1136782885#step:5:45) on all versions
- on Mac it [works](https://github.com/EduardSergeev/vscode-extension-samples/runs/1136782901#step:5:68) on all versions

**Comment by EduardSergeev** [comment]
Does the issue still "needs more info"?

**Comment by pedroterzero** [comment]
> > Does this issue occur when all extensions are disabled?:
> 
> Yes. Well, `--disable-extensions` cannot be used here since we are testing extension (which depends on some other extensions) but during the test run only necessary extensions are installed.

To add to this, I have the same behavior with `--disable-extensions` enabled.
Also, running the tests from cli (in a docker container) yields the same results.

**Comment by pedroterzero** [comment]
An update on this. For some odd reason this seems to fix it for me:

I changed
```json
    "activationEvents": [
        "workspaceContains:**/*.yml"
    ],
```

to

```json
    "activationEvents": [
        "onStartupFinished"
    ],
```

That generally seems to fix things for me. I am not really sure why though, yet.

**Comment by pedroterzero** [comment]
> Sure, no problem. I took Microsoft's [helloworld-test-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample) and just [added coverage](https://github.com/microsoft/vscode-extension-samples/compare/master...EduardSergeev:coverage-example).

@EduardSergeev in your example, just adding this to `nyc:` in `package.json` seems to at least show the file in coverage for me (and I added `out` to excludes)
```json
		"all": true,
```

Output on 1.52.0:

```
  Extension Test Suite

Congratulations, your extension "helloworld-sample" is now active!

    ✓ Activate extension (61ms)

  1 passing (67ms)

Exit code:   0
Done


=============================== Coverage summary ===============================
Statements   : 0% ( 0/6 )
Branches     : 100% ( 0/0 )
Functions    : 0% ( 0/2 )
Lines        : 0% ( 0/6 )
================================================================================
```

I had the same problem with it not registering the coverage from the tests (statements/functions/lines). I don't know how to solve that in package.json. That seemed to have to do with nyc outputting its report too early (i.e. not waiting for the tests to finish). In the other repo I posted earlier it's solved pretty easily in code.

**Comment by EduardSergeev** [comment]
> adding this to `nyc:` in `package.json` seems to at least show the file in coverage for me (and I added `out/` to excludes)

That is not a proper coverage. The coverage should be:

```
   =============================== Coverage summary ===============================
   Statements   : 96.93% ( 568/586 )
   Branches     : 79.1% ( 140/177 )
   Functions    : 96.06% ( 122/127 )
   Lines        : 96.93% ( 537/554 )
   ================================================================================
```

It worked before `1.49.0` and as of today, I believe, it is still broken.

**Comment by pedroterzero** [comment]
Yeah., like I said before I got it working with something along the lines of that [repo I posted earlier.](https://github.com/microsoft/vscode/issues/106977#issuecomment-745621694) I'm not using `all` in that and it still works.

Why this particular one doesn't work is beyond me. Good luck, hope you get it figured out!
