### ISSUE TITLE
cant delete everything to restart

### ISSUE THREAD

**Issue by monica5555** [microsoft/vscode#106960]
Issue Type: <b>Bug</b>

Visual studio wont delete everything I uninstall and re install i needed to restart fully

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (10.45GB free)|
|Process Argv|--crash-reporter-id b9379448-7504-4bfb-a55f-bb9b757161b5|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by joaomoreno** [comment]
What specific things doesn't VS Code delete?
