### ISSUE TITLE
Allow pasting image or file directly into a markdown editor

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode#106955]
Vscode should allow pasting images (and creating links, optinally uploading and saving the image in the correct place). 

The Issue editor in Github, and gitlab, allows pasting an image file by pressing ctrl+v when editing in markdown. It works on comments as well. 

This is not currrently supported in vscode, when a screenshot or image file is on clipboard, it cannot be pasted directly in vscode. Also can't paste files. 

Steps to Reproduce:

1. Create new markdown file
2. Take a screenshot
3. Press ctrl+v to paste the image inside the markdown file

**Comment by IllusionMH** [comment]
It's not clear how it should be inserted? Base64 that will easily take couple of MBs to document and doesn't help to create separate file later; random name is same folder, why not in `img` or `media` folder.

I think that "how it should be inserted?" should be part of the proposal.

**Comment by phgmacedo** [comment]
@IllusionMH 
> It's not clear how it should be inserted? Base64 that will easily take couple of MBs to document and doesn't help to create separate file later; random name is same folder, why not in `img` or `media` folder.
> 
> I think that "how it should be inserted?" should be part of the proposal.

The images should be inserted as a separate file, and a reference to the file inserted in the document, [according to markdown syntax](https://www.markdownguide.org/basic-syntax#images), maybe into a `media` or `img` folder on the same folder as the file being edited. 

It would also be interesting to be able to upload it to a web service, maybe even github, since microsoft owns github.

**Comment by phgmacedo** [comment]
There is an extension that implements this capability, but thinking about it, this would also be very useful not just in markdown, but in html, and other languages as well. 

The [vscode clipboard API](https://code.visualstudio.com/api/references/vscode-api#Clipboard) seems to only support reading and writing text.

**Comment by ElecTreeFrying** [comment]
Hi, Maybe [this feature](https://github.com/ElecTreeFrying/auto-import-relative-path/blob/master/DEMO.md#markdown-support) could help you temporarily. 

This is from [Auto Import Relative Path](https://marketplace.visualstudio.com/items?itemName=ElecTreeFrying.auto-import) extension.

**Comment by ElecTreeFrying** [comment]
Hi, Maybe [this feature](https://github.com/ElecTreeFrying/auto-import-relative-path/blob/master/DEMO.md#markdown-support) from [Auto Import Relative Path](https://marketplace.visualstudio.com/items?itemName=ElecTreeFrying.auto-import) extension help you temporarily.

**Comment by phgmacedo** [comment]
> Hi, Maybe [this feature](https://github.com/ElecTreeFrying/auto-import-relative-path/blob/master/DEMO.md#markdown-support) from [Auto Import Relative Path](https://marketplace.visualstudio.com/items?itemName=ElecTreeFrying.auto-import) extension help you temporarily.

I did not know about that extension, it is a great extension, but it does not solve the main problem which is that I want to take a screenshot (which goes to clipboard), and then paste it in the markdown file. 

I would still have to manually save it and organize it inside the folder for the extension to work.

**Comment by mjbvz** [comment]
Marking as extension candidate but may require new extension APIs to support properly, specifically #30066

**Comment by mjbvz** [comment]
Closing this manually as an "extension candidate" since the bot didn't kick in

**Comment by AceTheWiz** [comment]
There is an [extension ](https://github.com/telesoho/vscode-markdown-paste-image.git) specifically for markdown which does this. 
It also requires (not sure why this is an issue for you)
- 'xclip' command be required (Linux)
- 'powershell' command be required (Win32)
- 'pbpaste' command be required (Mac)
