### ISSUE TITLE
turning "editor.accessibilitySupport" on disables all line wrap options without warning 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#106941]
Despite the fact that I had the "editor.wordWrap" setting turned on, I was not seeing word wrap occurring anywhere.

After enabling/disabling various settings through "bisecting", I found that the "editor.accessibilitySupport" disables word wrap without saying so.

I suggest to add this fact to the setting's description so that users can actually find this issue when they search for "wrap".
Even better would be if a warning would pop up... 

/cc @isidorn

**Comment by isidorn** [comment]
Related https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+word+wrap

**Comment by alexdima** [comment]
@weinand I'm sorry you ran into this. By default, when leaving `editor.accessibilitySupport` to auto (or not configuring it) and attaching a screen reader the following popup shows:

  ![image](https://user-images.githubusercontent.com/5047891/93573769-d65cb800-f997-11ea-8b11-994c780ed91a.png)

So the experience for people who use a screen reader is that they get informed into configuring `"editor.accessibilitySupport": "on"` and the popup lets them know that they won't have wrapping.

But I guess you maybe edited the setting directly, not by using a screen reader, in which case the setting description does not mention this limitation. I can improve the setting description, but I would not add yet another pop-up, as I expected people that use a screen reader to be "guided" into configuring that setting via our auto-detection mechanism.

**Comment by isidorn** [comment]
Makes sense to just improve the settings description. Additional popups would be too much.

**Comment by weinand** [comment]
yes, just adding the keyword "wrap" to the description will help to find the issue.
