### ISSUE TITLE
Lots of "Unable to open ..." errors on Mac

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#106905]
Issue Type: <b>Bug</b>

I've got a typescript project, and some of the errors show up with absolute and invalid paths for the files.  Clicking on the error then gives:
`> Unable to open 'ParentAndChildCodeLenses.ts': Unable to read file '/~/repos/vscode-azurearmtools/src/documents/templates/ParentAndChildCodeLenses.ts' (Error: Unable to resolve non-existing file '/~/repos/vscode-azurearmtools/src/documents/templates/ParentAndChildCodeLenses.ts').`

The path `"/~/"` is invalid.  Starting with `"~/"` would be valid.  (But some are relative, not absolute.)

If you need more specifics, I can try.

![image](https://user-images.githubusercontent.com/6913354/93410801-87efd200-f84e-11ea-8741-9abbc80b04a7.png)

Closing and reopening that file then showed multiple entries in the errors list:

![image](https://user-images.githubusercontent.com/6913354/93410863-b2418f80-f84e-11ea-8eda-96d44a4d806b.png)

VS Code version: Code - Insiders 1.50.0-insider (9e505675670d65138405321a60b0df4ddec28799, 2020-09-16T05:43:58.570Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 28a909e2-0b30-47b4-bfa3-dcb1734aca95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
vscode-dotnet-runtime|ms-|0.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by mjbvz** [comment]
Please share a project that demonstrates this problem

**Comment by StephenWeatherford** [comment]
REPRO (Mac):

1) git clone https://github.com/microsoft/vscode-azurearmtools.git
2) cd vscode-azurearmtools
3) npm i
4) open folder in vscode
5) SHIFT+CMD+B
!) Sometimes is shows no errors in the issues list (which is wrong, there are two errors).  When it does show the errors, they're formatted like this:

{
	"resource": "/~/repos/vscode-azurearmtools/src/documents/templates/Resource.ts",
	"owner": "typescript",
	"code": "2420",
	"severity": 8,
	"message": "Class 'Resource' incorrectly implements interface 'IResource'.",
	"source": "ts",
	"startLineNumber": 16,
	"startColumn": 14,
	"endLineNumber": 16,
	"endColumn": 14
}
{
	"resource": "/~/repos/vscode-azurearmtools/src/documents/templates/scopes/templateScopes.ts",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'Resource' is not assignable to parameter of type 'IResource'.",
	"source": "ts",
	"startLineNumber": 222,
	"startColumn": 32,
	"endLineNumber": 222,
	"endColumn": 32
}

Clicking on either one will give:
> Unable to open 'templateScopes.ts': Unable to read file '/~/repos/vscode-azurearmtools/src/documents/templates/scopes/templateScopes.ts' (Error: Unable to resolve non-existing file '/~/repos/vscode-azurearmtools/src/documents/templates/scopes/templateScopes.ts').

NOTE: I'm seeing somewhat inconsistent behavior.  For instance, if you open the build terminal and click on an error there, it goes to the correct file, and the bogus errors go away.  Then if you close the file, all the errors go away.

Also, if you press F5 after opening the folder instead of SHIFT+CMD+B, then debugging actually starts, but it should instead complain about the two errors.

**Comment by alexr00** [comment]
Looks like a duplicate of https://github.com/microsoft/vscode/issues/106877 or https://github.com/microsoft/vscode/issues/106988. @StephenWeatherford can you try updating and see if the issue is resolved?

**Comment by StephenWeatherford** [comment]
Updated, will see if I see it again.

**Comment by StephenWeatherford** [comment]
Haven't seen it for a while, closing.
