### ISSUE TITLE
Language Mode for HiveQL

### ISSUE THREAD

**Issue by vaibhavkbrahm** [microsoft/vscode#106919]
Please add HiveQL to the language mode for editing the Hive scripts. Currently I set the language to SQL but it show error for hive variables.

**Comment by aeschli** [comment]
Did you check the Marketplace for extensions? 
https://marketplace.visualstudio.com/items?itemName=josephtbradley.hive-sql adds syntax highlighting support.

If you are looking for richer support (code completions, validation) you might also want to file an issue against an sql extension to add support for HiveSQL.
