### ISSUE TITLE
Alert on launch

### ISSUE THREAD

**Issue by wasinwill** [microsoft/vscode#106938]
Issue Type: <b>Bug</b>

When opening VS Code Insiders since this morning's update, I'm getting this alert at every launch:

We did not find "node" on your path, so can not enable auto-attach in your environment
Source: JavaScript Debugger

The problem still occurs when all user-installed extensions are disabled.

![Screenshot 2020-09-17 072732](https://user-images.githubusercontent.com/44789688/93464666-873f5600-f8b7-11ea-8be5-0c41851fd23e.png)

VS Code version: Code - Insiders 1.50.0-insider (d1f267742169584db010716d92addf50d4cd8139, 2020-09-17T07:23:18.487Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (11.98GB free)|
|Process Argv|--crash-reporter-id 47798f4c-9d0b-4531-b0d9-c36278d01dbe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
auto-close-tag|for|0.5.8
todo-tree|Gru|0.0.178
color-manager|roy|0.5.7
highlight-matching-tag|vin|0.9.9

</details>

**Comment by sweettyler** [comment]
same here. didn't have such a issue yesterday.
=======================================================
Version: 1.50.0-insider
Commit: d1f267742169584db010716d92addf50d4cd8139
Date: 2020-09-17T07:03:46.695Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 3.10.0-693.17.1.el7.x86_64
=================================================

**Comment by agrimaldi74** [comment]
I clicked on the gear icon in the error message and followed the instructions to uninstall the JavaScript Debugger default extension and install the Nightly version, and the error is gone
![image](https://user-images.githubusercontent.com/42692661/93491863-78ce5a00-f90a-11ea-967e-c7ebc2ce45b1.png)

**Comment by connor4312** [comment]
Thanks for the reports, this duplicates https://github.com/microsoft/vscode/issues/106537

**Comment by sweettyler** [comment]
@connor4312  I am afraid this is not a duplicate of #106537. The reason is when I used the insider version of VScode built on yesterday I didn't have this issue. If it's a duplicate I would have saw the error message much earlier.

**Comment by sweettyler** [comment]
I just re-install the version "d1f267742169584db010716d92addf50d4cd8139" , and I have not this error message.

**Comment by connor4312** [comment]
Let's continue discussion in the linked issue. We can reopen this one if that issue ends up having a different root cause.
