### ISSUE TITLE
Debug Call Stack UI for multithreaded programs does not show `text` on hover because inline actions appear

### ISSUE THREAD

**Issue by suzmue** [microsoft/vscode#106957]
- VSCode Version: 1.49.0, 1.50.0-insider
- OS Version: macOS catalina 10.15.6

The debugging UI in the call stack for exceptions does not display all of the Stopped Event information when debugging multithreaded code. This was originally discovered and raised when developing the Go debugger in [#104475](https://github.com/microsoft/vscode/issues/104475) but is also reproducible in other languages when debugging multithreaded code.  

The spec for stopped events while debugging says that the text will be displayed in the UI, but this appears to only be the case in a single threaded program. The 'text' and 'description' fields in the stopped event appear to be ignored with multithreaded programs.

The description in the dap spec indicates these are both displayed in the UI:
```
    /**
     * The reason for the event.
     * For backward compatibility this string is shown in the UI if the 'description' attribute is missing (but it must not be translated).
     * Values: 'step', 'breakpoint', 'exception', 'pause', 'entry', 'goto', 'function breakpoint', 'data breakpoint', 'instruction breakpoint', etc.
     */
    reason: string;
    /**
     * The full reason for the event, e.g. 'Paused on exception'. This string is shown in the UI as is and must be translated.
     */
    description?: string;
    /**
     * Additional information. E.g. if reason is 'exception', text contains the exception name. This string is shown in the UI.
     */
    text?: string;

```

Steps to Reproduce:

1. Debug a multithreaded program and stop on an exception
2. Inspect call stack

Using the python extension as an example for debugging a single thread and a multithreaded program.

The stopped event for the exception in both programs is as follows:

```
           {
                 "pydevd_cmd_id": 157,
                 "seq": 30,
                 "type": "event",
                 "event": "stopped",
                 "body": {
                     "reason": "exception",
                     "description": "oops",
                     "threadId": 1,
                     "preserveFocusHint": false,
                     "text": "ValueError",
                     "allThreadsStopped": true
                 }
             }


```

A raised exception on a single thread appears like this:

![Screen Shot 2020-09-17 at 11 44 54 AM](https://user-images.githubusercontent.com/6634754/93496280-03986000-f8dd-11ea-9358-6a38e7e04b56.png)
Hover:
![Screen Shot 2020-09-17 at 11 45 26 AM](https://user-images.githubusercontent.com/6634754/93496285-05622380-f8dd-11ea-9083-1bd3742ed2c0.png)

While the multithreaded exception appears like this:

![Screen Shot 2020-09-17 at 11 43 03 AM](https://user-images.githubusercontent.com/6634754/93496190-eb284580-f8dc-11ea-9abe-11c31e4102d4.png)
Hover:
![Screen Shot 2020-09-17 at 11 43 33 AM](https://user-images.githubusercontent.com/6634754/93496200-efecf980-f8dc-11ea-9f11-d31a30ec67e9.png)

**Comment by polinasok** [comment]
@suzmue Thank you for narrowing down this issue to the multi-threaded scenario. I should have realized that's why the call stacks looked so different for go (always multi-threaded due to runtime implementation) and other languages I checked.

**Comment by isidorn** [comment]
Correct we do not show `text` because on hover we show the inline actions, so there is no good place to show this. I acklnowledge this bug. And am open for suggestions on how to show it.
However we should always respect the `description` and render it. I pushed a fix such that we are sure to always respect the `description`.

**Comment by polinasok** [comment]
Is the description supposed to replace "paused on <reason>" message? (On a related note, what documentation do you recommend to figure out how the various fields in each dap message are reflected in the vscode UI?)

It looks to me that the mouse-over appears under the line, not over it, so perhaps you can have both the hover text and the inline actions? There is already some kind of mouse-over  there that says "Thread" in addition to those inline actions.
![image](https://user-images.githubusercontent.com/51177946/93845831-17362480-fc57-11ea-805b-1e015f044a69.png)

**Comment by polinasok** [comment]
If showing text for multi-threaded programs, is not in scope for vscode, then is there a better place to file for this improvement.

Re: description. We verified and see that it is working. Thank you.
![image](https://user-images.githubusercontent.com/51177946/104503449-f3944280-5595-11eb-9cc4-1b5ec738232c.png)

Re: text. We would love to be able to provide additional details on stopped events. If 'text' is not possible for multi-threaded programs, is there a different hook that would allow us to replace mouse-over with the single world "Thread" ([image](https://user-images.githubusercontent.com/51177946/93845831-17362480-fc57-11ea-805b-1e015f044a69.png)) with something more useful? Thank you.
