### ISSUE TITLE
GitHub Always Asks for Creds

### ISSUE THREAD

**Issue by bentondavidl** [microsoft/vscode#106901]
Issue Type: <b>Bug</b>

When opening VSCode by right-clicking in a folder of a git repo and selecting `Open with Code`, I am always asked to re-enter my GitHub credentials. This does not happen when opening other folders with the context menu.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.91GB free)|
|Process Argv|C:\Users\David\Documents\GitHub\MileSplit-Scraper --crash-reporter-id 6e8178f8-5270-4325-a986-b961de473431|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.36.3
gc-excelviewer|Gra|3.0.40
rainbow-csv|mec|1.7.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.8.109390
vscode-pylance|ms-|2020.9.4
remote-wsl|ms-|0.44.5
autodocstring|njp|0.5.3
material-icon-theme|PKi|4.3.0
java|red|0.67.0
vscode-yaml|red|0.10.1
code-spell-checker|str|1.9.0
tabnine-vscode|Tab|3.0.0
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
jinja|who|0.0.8

</details>

**Comment by joaomoreno** [comment]
Can you show me a screenshot of that credential prompt window?

**Comment by bentondavidl** [comment]
The new version seems to have fixed the issue.
