### ISSUE TITLE
why my vscode displays in every desktop on mac?

### ISSUE THREAD

**Issue by fakeYanss** [microsoft/vscode#106923]
- VSCode Version: 1.48.2
- OS Version: macOS Catalina 10.15.6

Steps to Reproduce:

1. open vscode
2. open mission control
![image](https://user-images.githubusercontent.com/30440198/93438023-49662000-f8ff-11ea-9b56-31ee868f394e.png)
![image](https://user-images.githubusercontent.com/30440198/93438044-5256f180-f8ff-11ea-8672-5404bac013d9.png)

Does this issue occur when all extensions are disabled?: Yes

I don't know is it a new feature or a bug. And how to disable it?

**Comment by bpasero** [comment]
Unclear to me if Electron provides a way to control this or if this is a bug.

**Comment by fakeYanss** [comment]
I have not modified anything with my vscode. And I also try to uninstall and reinstall it with homebrew.

**Comment by deepak1556** [comment]
Unable to repro this with latest stable, can you check if this is still an issue ?
