### ISSUE TITLE
Can't click to highlight

### ISSUE THREAD

**Issue by theblackaccount** [microsoft/vscode#106949]
Issue Type: <b>Bug</b>

Click and drag over text, it doesn't highlight across lines.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.56GB free)|
|Process Argv|. --crash-reporter-id 96a82ffc-ede0-4c24-8ea2-fe2ec31011a7|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-highlight|fab|1.4.1
sass-lint|gle|1.0.6
vscode-scss-formatter|sib|2.0.2
sass-indented|syl|1.8.11

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen if you launch with all extensions disabled?
