### ISSUE TITLE
Pressing Enter in References window no longer works to navigate/activate highlighted item

### ISSUE THREAD

**Issue by ivanjonas** [microsoft/vscode#106984]
- VSCode Version: VS Codium 1.48.2
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Opened a .ts file with various symbols.
2. Triggered "Peek References" on a symbol.

Result:
✅ Up/down arrows work to highlight files/lines/occurrences.
✅ Pressing enter to expand/collapse a file works.
❌ Pressing enter to navigate to a line does not work.
✅ Double-clicking to navigate to a line does work.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

Latest released version is 1.49.1
Please check with latest version and all extensions disabled.
<kbd>Enter</kbd> navigates to other references without problem for me.

**Comment by ivanjonas** [comment]
I finally discovered... that it was a misconfigured keybinding. Entirely user error.
