### ISSUE TITLE
Cannot get intellisense to work in html for typescript interface

### ISSUE THREAD

**Issue by danAntoniuS** [microsoft/vscode#106970]
- VSCode Version: latest download 
- OS Version: Windows 10

Steps to Reproduce:

1. create an angular application
2. add a typescript interface say Course
3. in html view cannot get intellisense for {{course.decsription}} 
when type dot no property is suggested

**Comment by IllusionMH** [comment]
/needsMoreInfo
Do you have problems accessing this properties outside of HTML views?

If no problems outside of them, then this issue should be reported against extension that provide support for views

**Comment by danAntoniuS** [comment]
> /needsMoreInfo
> Do you have problems accessing this properties outside of HTML views?
> 
> If no problems outside of them, then this issue should be reported against extension that provide support for views

can you be more specific where / url where I can report?
I feel that you are closing issues w/o solving them
yes I have intellisense in ts files but not in html file
is this supported? does it come standard with VS Code or needs configuration?

**Comment by danAntoniuS** [comment]
what extension provides that support? could not find one

**Comment by danAntoniuS** [comment]
documentation does not offer information as it would not support it

**Comment by IllusionMH** [comment]
Guide is here https://code.visualstudio.com/docs/nodejs/angular-tutorial

Which has no mentions of HTML out of the box. In extensions list at you should see https://marketplace.visualstudio.com/items?itemName=Angular.ng-template that should provide this functionality.

**Comment by danAntoniuS** [comment]
Many thanks that worked
since is such a frequent scenario wold have helped if the page for VS Code installation would have this info
thanks again

**Comment by IllusionMH** [comment]
> would have helped if the page for VS Code installation would have this info

Docs are located in https://github.com/microsoft/vscode-docs/blob/master/docs/nodejs/angular-tutorial.md

I'm sure that PRs are welcome.
