### ISSUE TITLE
snippets are not displayed completely

### ISSUE THREAD

**Issue by EricDDK** [microsoft/vscode#106982]
- VSCode Version: 1.48.2
- OS Version: windows 10

Steps to Reproduce:

How to make the width of the box wider to show the whole
![image](https://user-images.githubusercontent.com/33505774/93558894-05335800-f9b1-11ea-9681-136368e94f84.png)
lua.code-snippets
![image](https://user-images.githubusercontent.com/33505774/93558794-d1f0c900-f9b0-11ea-9664-b1e6ef413cc7.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest+label%3Aux
