### ISSUE TITLE
why words isnt aligns

### ISSUE THREAD

**Issue by ywaby** [Microsoft/vscode#10696]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

```
‭0011 0111 0011 0001 0000 0000 0000 0000‬
‭0011 1111 0111 1111 1111 1110 1110 1101‬
```
up words is not aligns in vsc

**Comment by alexandrudima** [comment]
@ywaby They are aligned for me:

![image](https://cloud.githubusercontent.com/assets/5047891/17845995/2be6643e-6846-11e6-8a92-fadfca945510.png)

Perhaps you have customized your font to one which is not monospace?

**Comment by ywaby** [comment]
@alexandrudima 
![image](https://cloud.githubusercontent.com/assets/12198203/18052750/b73f2a46-6e2e-11e6-8b45-3e86ac23beb8.png)
my default set is 
```
"editor.fontFamily":` "Consolas, 'Courier New', monospace",
...
```
alter add setting.json, problem has solve . unknow reason.
```
{    "editor.fontFamily": "Consolas, 'Courier New', monospace"
}
```
![image](https://cloud.githubusercontent.com/assets/12198203/18053023/0d3b8f06-6e30-11e6-80e2-18ed89f3e4a1.png)

**Comment by alexandrudima** [comment]
That is most weird, but I'm happy it fixes the problem for your machine.
