### ISSUE TITLE
VSC loses opened files

### ISSUE THREAD

**Issue by Qualdan** [microsoft/vscode#106980]
Issue Type: <b>Bug</b>

Using with Unity. If I open VSC with "Open C# project" -command it reopens all previously opened files. But if I open VSC by activating a single script (from inside Unity), all previously opened files are not opened and every single one needs to be opened manually again.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.
