### ISSUE TITLE
远程服务器上文件下载

### ISSUE THREAD

**Issue by dreamenwalker** [microsoft/vscode#106995]
Issue Type: <b>Feature Request</b>

无法拖拽服务器上的文件下载到本地

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.15.0-99-generic
Remote OS version: Linux x64 4.15.0-117-generic
Remote OS version: Linux x64 4.15.0-99-generic
Remote OS version: Linux x64 4.15.0-117-generic

**Comment by erfanium** [comment]
Unable to drag and drop files on the server to download locally
