### ISSUE TITLE
Quick open changes order for matching elements

### ISSUE THREAD

**Issue by stephanjust** [Microsoft/vscode#10690]
- VSCode Version: 1.4.0
- OS Version: Windows 7 x64

This doesn't happen with all name-combinations, so I assume it depends on the algorithm (I could not reproduce this issue with aaa.ts and b.aaa.ts)

Steps to Reproduce:
1. Open a workspace containing the two files cell.editor.ts and editor.ts
2. Press CTRL+P and start typing: 'editorts' (without quotes and without a period)

Result:
While typing, editor.ts is the first result as long as you didn't type further than 'editor'. As soon as you add the 't' from the file ending, cell.editor.ts becomes the first entry in the list followed by editor.ts. Clicking on editor.ts while still typing 'editor' is not a workaround as my real folder contains more files with that naming schema.

Typing the full name, editor.ts (with the period), matches the correct file.

Expected result:
An entry should not change position when still completing its name without errors.

**Comment by bpasero** [comment]
This only happens when the files are in the "recently opened" category where we use a different scoring and sorting algorithm.
