### ISSUE TITLE
Allow disable (workspace) for conflicted extension

### ISSUE THREAD

**Issue by devel0** [microsoft/vscode#106951]
I have installed Platform.io and Arduino extensions and one (arduino) results confilcting with Platform.io

![image](https://user-images.githubusercontent.com/13405008/93504214-79222180-f919-11ea-89ee-fe3ffc9e3593.png)

however I need Arduino extension to work with other projects and would two extensions in the same vscode installation. In order to do that actually I go to extension, filter for the one conflicting, then disable in the workspace:

It would helpful if a **disable (workspace)** button could be added to that dialog as an alternative to uninstalling conflicting extension.

**Comment by gjsjohnmurray** [comment]
/causedByExtension that dialog comes from Platform.io (see bottom left corner)
