### ISSUE TITLE
Enable Pin Icon To Always Remain Visible

### ISSUE THREAD

**Issue by Sayvai** [microsoft/vscode#106956]
With the release of `1.50`, this provided a couple more much-needed configurations to pinned tabs, along with a new pin icon to represent a pinned tab. However, the pin icon itself is only temporarily visible.

As i develop away, i lose sight, or find it difficult to read as to which tabs are pinned again.

As a feature suggestion, I would like for the pin action icon to **always** remain visible. This way i can easily and quickly visually read from a user experience which tabs are pinned without much thought. 

See example below (credit to @ChristopherHaws for the [suggestion](https://github.com/microsoft/vscode/issues/98161#issuecomment-693185517) and providing image on issue #98161):

![image](https://user-images.githubusercontent.com/5934505/93296919-1a3b9b80-f7a5-11ea-8238-d74309eb8177.png)

Also, the same could apply on the folder / file explorer sidebar, where the pin icon would always remain visible to the left of the filenames.

Finally, an approach could be to make this a configurable option. Eg, `workbench.editor.alwaysShowTabPinIcon`.

**Comment by bpasero** [comment]
@Sayvai to clarify, you only ask for the pin icon to always be visible, similar to when the editor is dirty and shows the black dot right? This is not about showing the pin icon AND the close icon like VS does?

**Comment by Sayvai** [comment]
> @Sayvai to clarify, you only ask for the pin icon to always be visible, similar to when the editor is dirty and shows the black dot right? This is not about showing the pin icon AND the close icon like VS does?

@bpasero Correct. Similar to when the file is in a dirty state where the black (or white, if dark theme) persistently shows on the tab.

I suppose that raises another challenge, such as how would persisting dirty dot appear alongside a persisting pin icon? Next to each other? Or, vertically aligned next to each other (eg, top and bottom)?

**Comment by bpasero** [comment]
Yeah exactly, not clear to me.

**Comment by Sayvai** [comment]
> Yeah exactly, not clear to me. Could always let the dirty indicator win over the pin one.

Thinking about it, that would make sense. 👍
