### ISSUE TITLE
what is the Clear Console action Shortcut key？

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode#10691]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. what is the Clear Console action Shortcut key？
2.

**Comment by alexandrudima** [comment]
@ydcoming Do you mean the integrated terminal or the debug console?

**Comment by ydcoming** [comment]
the debug console panel

**Comment by isidorn** [comment]
@ydcoming  Currently there is no default shortcut key, we will add this action to be a global workbench action and then you will be able to assign a custom shortcut key as desired
