### ISSUE TITLE
vscode crushes when hover a class/ID

### ISSUE THREAD

**Issue by H2SO3** [microsoft/vscode#106985]
Issue Type: <b>Bug</b>

Hovering the cursor over an ID or class will display a tooltip for the "hover" feature, which will crash the extension and display the message "Extension host terminated unexpectedly".
Disabling the "hover" feature will prevent it from crashing, but at the cost of disabling features such as the color picker. X(

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (3.04GB free)|
|Process Argv|D:\htdocs\projects\bimi-ichizen.com\bimi-ichizen.com.code-workspace --crash-reporter-id 13a01e2a-7aaa-479c-bbe9-181b4fbede86|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
ACF-Snippet|ant|1.9.0
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
jquerysnippets|don|0.0.1
php-debug|fel|1.13.0
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
japanese-proofreading|ICS|0.2.3
sftp|lix|1.12.9
HTMLHint|mka|0.8.0
vscode-apache|mrm|1.2.0
vscode-language-pack-ja|MS-|1.49.1
indent-rainbow|ode|7.4.0
view-in-browser|qin|0.0.5
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
annotator|ryu|1.0.0
code-settings-sync|Sha|3.4.3
easysass|spo|0.0.6
wordpress-snippet|tun|1.1.5
vscode-convert-utils|vsc|1.0.2
local-history|xyz|1.8.1
searchwpdocs|yog|2.0.1

(3 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
Does this reproduce with extensions disabled?

**Comment by H2SO3** [comment]
The error message said that the "Live Sass Compiler" had crashed, but it seems that it was actually caused by "HTMLhint" (mkaufman.htmlhint). As a result of disabling this, the problem has been resolved. I owe you one.

**Comment by aeschli** [comment]
Thanks for letting me know!
