### ISSUE TITLE
Proxy not showing

### ISSUE THREAD

**Issue by Serpen** [microsoft/vscode#106943]
- VSCode Version: 1.49.0
- OS Version: Windows 10.0.19041.508

Steps to Reproduce:

The montly (3rd month in succession) proxy break is there.
This time the proxy authentication windows shows for less than a second and disappears without a chance to enter credentials.
After that a info tip with error 407 is showing.

Its really annoying to have proxy problems every month 👎 

The Changelog says nothing about a change in proxy settings

**Comment by Serpen** [comment]
> 
> 
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Proxy window stopped working (#104637)](https://www.github.com/microsoft/vscode/issues/104637)
> 
>     * [Can NOT Clear Proxy (#103693)](https://www.github.com/microsoft/vscode/issues/103693)
> 
>     * [Save Proxy Credentials (#32566)](https://www.github.com/microsoft/vscode/issues/32566)
> 
>     * [Proxy Auth (#104726)](https://www.github.com/microsoft/vscode/issues/104726)
> 
>     * [Save Proxy Authentication (#56439)](https://www.github.com/microsoft/vscode/issues/56439)

No, its none of those. Its something new. But I have gone through all of them to, (for me) they where fix with the next .1 release

**Comment by gjsjohnmurray** [comment]
Recovery release is nearly here. See #106671

**Comment by Serpen** [comment]
Fixed in Recovery Release, dup of #106434
