### ISSUE TITLE
VSCode should not download extensions that CAN'T work on the current platform

### ISSUE THREAD

**Issue by conioh** [microsoft/vscode#106971]
The Visual Studio Marketplace should specify supported platforms for VSCode extensions (it might be nice for Visual Studio too, but that's out of scope here) and VSCode should download and install extensions only if the platform on which VSCode is running is one of the supported platforms. You can have that information in the extensions manifest, or something specific to the Marketplace and not part of the manifest. I don't care how you implement the feature.

You might want to assume the "trivial" rules, i.e. the "supported" operator is a union of the identity operator (x86-32 is supported on x86-32, x86-64 is supported on x86-64, etc.) and the WoW support operator (x86-32 is supported on x86-64, x86-32 is supported on arm64, arm is supported on arm64). Or you might want to only use the identity operator. This question requires some thought and any choice should be documented.

Currently VSCode downloads and install unsupported extensions, and only then the extensions themselves find that out:

![image](https://user-images.githubusercontent.com/10606081/93537267-c1f6cc00-f953-11ea-8fb0-11a4b32ab6ae.png)

That's not good.

I emphasize that the issue is not whether the C++ extensions supports ARM64 or not (so #90233 is irrelevant). I couldn't care less for the purposes of this request. The issue is whether or not VSCode knows in advance, before downloading and installing, would a given extension run. Would _any_ given extension run.

That's what happens on any decent app store, like the iOS App Store, Google Play Store, etc.

![image](https://user-images.githubusercontent.com/10606081/93539453-8e1ea500-f959-11ea-876d-ddc03c8e710a.png)

![image](https://user-images.githubusercontent.com/10606081/93538314-827daf00-f956-11ea-8a9d-e34fb8e36a01.png)

Even a half-decent store like the Windows Store does that:

![image](https://user-images.githubusercontent.com/10606081/93539079-6c70ee00-f958-11ea-8238-1352813a4b01.png)

If you're unsure about how to do it I'm certain the Windows Store team would be happy to assist.

Again, [because people have already had a hard time understanding the request](https://github.com/microsoft/vscode/issues/33620#issuecomment-620583412): I'm not asking you to make this or that extension work on all platforms where VSCode runs. I'm asking you to tell me whether an extension would run or not before downloading. Just like any other distribution platform of that sore does, including one from your company.

**Comment by gjsjohnmurray** [comment]
Pinging @prashantvc for Marketplace element of this.

**Comment by sandy081** [comment]
/duplicate

#23251

**Comment by conioh** [comment]
@sandy081, Perhaps I'm missing something but I don't see how that's a duplicate.

#23251's title is "Support Platform Specific Extensions".
They're already supported.
That's not what I'm asking.

For example, the aforementioned C++ extension is supported (by none other than Microsoft itself) and actually works on multiple platforms.

In #23251 there's a long discussion about how extensions can and should get platform-specific components:
One suggestion: https://github.com/microsoft/vscode/issues/23251#issuecomment-406090410
Another option: https://github.com/microsoft/vscode/issues/23251#issuecomment-440224043 (made by you, actually)
A third one: https://github.com/microsoft/vscode/issues/23251#issuecomment-440745982 (pretty similar to what actually happens)
And so on.

But that's not what I'm talking about. I don't care about all of that. That's irrelevant.
I don't care about how extensions bring their dependencies.
I don't care if they do it themselves or they declare their platform-specific dependencies and VSCode gets them.
I don't even care if they bundle _all_ their platforms-specific content in a single gigantic extension and then use only the necessary parts.
That's not what this issue is about, in contrast with #23251.

However they do it, with whatever amount of assistance they get from VSCode, I want VSCode to NOT install extensions that can't run, extensions for which there is NO required platforms-specific content for the current platform.

That's a completely different issue.

Even after you changing the title from _Extension post-install hooks_ and your comment (https://github.com/microsoft/vscode/issues/23251#issuecomment-458075818) changing the agenda of #23251 it only deals with bringing the correct dependencies. It says nothing, and I emphasize - **COMPLETELY NOTHING** - about sparing users from downloading and installing incompatible extensions.

Then how is this a duplicate?

**Comment by sandy081** [comment]
I agree that #23251 talks about various issues and solutions due to the distraction of discussions but the intend of that issue is to support extensions that are supported per platform which is not supported now. This issue is exactly meant to do following

> However they do it, with whatever amount of assistance they get from VSCode, I want VSCode to NOT install extensions that can't run, extensions for which there is NO required platforms-specific content for the current platform.

**Comment by conioh** [comment]
> I agree that #23251 talks about various issues and solutions due to the distraction of discussions but the intend of that issue is to support extensions that are supported per platform which is not supported now. This issue is exactly meant to do following

The problem is not that #23251 talks about various different issues.
The problem is that it doesn't mention even once _this_ issue.

The fact that you claim that the "issue is exactly meant to do following" means nothing if it's not documented there, in writing. Let's say you quit your job at Microsoft tomorrow, how are the rest of the people assigned to #23251 supposed to know they have to deal with this problem?

**Comment by sandy081** [comment]
> The problem is that it doesn't mention even once this issue.

Here is the comment https://github.com/microsoft/vscode/issues/23251#issuecomment-458075818 that mentions about this.

> Let's say you quit your job at Microsoft tomorrow, how are the rest of the people assigned to #23251 supposed to know they have to deal with this problem?

Thanks for your concern but that's not an issue I suppose because we have multiple people knowing the context about it.
