### ISSUE TITLE
UX changes to install extension directly from Marketplace

### ISSUE THREAD

**Issue by hamenon** [Microsoft/vscode#10693]
CC: @waderyan @joaomoreno @seanmcbreen 

With the direct application URL handler changes coming in this next iteration we're working on changes to the Marketplace UX to allow direct installation of extension from Marketplace. We wanted to run a few options by you to get your thoughts as well, as there are a few factors to consider:

- The VS Code insiders build has a separate application handler so needs to be handled separately

- Older versions of the client won’t support the application handler hence copy command option still needs to be present

Following are two options we're considering:
Option 1:
![vscode install1](https://cloud.githubusercontent.com/assets/13758921/17803615/27e0aa08-6615-11e6-84c1-e26071499693.png)
Option 2:
![vs code install2](https://cloud.githubusercontent.com/assets/13758921/17803619/2e683738-6615-11e6-9f92-dc961f2368c2.png)

Current preference is toward option 1, the reasoning being:

- A majority of the users are generally on the latest build and hence that should be the most prominent CTA (Install button)
- We can also take a call to remove the helper message once enough users have moved to the latest version.

**Comment by joaomoreno** [comment]
Moved to #10340
