### ISSUE TITLE
Code CLI --clone command to clone a <url>

### ISSUE THREAD

**Issue by brunoborges** [microsoft/vscode#106917]
Add support for opening a remote Git repository from the command-line:

```sh
~$ code --clone https://github.com/microsoft/vscode.git
```

* Repository should be cloned into the current directory
* New window should be opened on the folder of the cloned repository (e.g. `~/vscode`)

Errors:

* If the current folder is already a repository, show an error message.

**Comment by manekinekko** [comment]
I like this feature. How about just `code https://github.com/microsoft/vscode.git`?

**Comment by brunoborges** [comment]
Reason for the `--clone` is because it leaves room for other options in the future. 

1. What if I want to open the Repo using GitHub Codespaces instead?
1. What if I want to open the repo just for read-only? Meaning: temporarily clone with `--depth 1` to a temporary folder and open on Code for navigation.

All of these are interesting options as well.

**Comment by joaomoreno** [comment]
This definitely feels like out of scope. I suggest to create an alias in bash which does this for you. Or even create a cli tool composing Code and git in such a way, if others are interested in such a feature.

**Comment by brunoborges** [comment]
@joaomoreno I think this is a shortsighted conclusion, considering the investment in Remote Development.

For similar reasons the CLI has:

```
  --folder-uri <uri>                Opens a window with given folder uri(s)
  --file-uri <uri>                  Opens a window with given file uri(s)
```

It wouldn't be hard to imagine the following either:

```
$ code --git-uri <uri>
```

**Comment by manekinekko** [comment]
@brunoborges here is a quick and dirty shell function that emulates the behaviour you are requesting:
```
code () {
        git clone --depth=1 $1
        code-insiders $(basename ${1%.*})
}
```
And then use it:
```
code https://github.com/microsoft/vscode.git
```
