### ISSUE TITLE
failure to find .ts source when debugging aka inconsitency with relative { .sources } path in sourcemaps

### ISSUE THREAD

**Issue by ilanc** [microsoft/vscode#106930]
Issue Type: <b>Bug</b>

When trying to resolve .ts source locations and the sourcemap has relative paths  e.g. `"sources":["../../../src/hello.ts"]` (which is the default format when you compile with `tsc`) then node fails to find the .ts. The error given is:
`Could not load source '/src/hello.ts': Unable to retrieve source content.`

It appears that node uses the HOME dir for relative paths - rather than the sourcemap directory. If you change to "./src" then you get: `Could not load source '/home/ilan/src/hello.ts': Unable to retrieve source content.`.

Steps to repro:

```sh
git clone https://github.com/spikedata/vscode-ts-debug.git
npm i
npm run build

# ts-node = works
node -r ts-node/register src/hello.ts

# ts-node --inspect-brk = kind of works = you get the weird .js names as .ts hack
node --inspect-brk -r ts-node/register src/hello.ts

# node = doesn't work = Could not load source '/src/hello.ts': Unable to retrieve source content.
node build/main/src/hello.js
```

To fix node you have to do this:

edit sourcemap
change "sources":["../../../src/hello.ts"] from relative to full path (or else a path relative to ~)
e.g. "sources":["/spike/prototype/vscode-ts-debug/src/hello.ts"]
now node build/main/src/hello.js works as expected, and thankfully so does ts-node

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:20:50.359Z)
OS version: Linux x64 5.4.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2923)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.39GB (0.56GB free)|
|Process Argv|/spike/v8/priv --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.6.0
vscode-statusbar-debugger|fab|2.0.6
vscode-mysql|for|0.4.0
gc-excelviewer|Gra|3.0.40
vscode-drawio|hed|0.7.2
rest-client|hum|0.24.2
json2csv|kha|0.0.1
git-graph|mhu|1.26.0
vscode-docker|ms-|1.6.0
python|ms-|2020.8.109390
vetur|oct|0.27.3
emoji|Per|0.0.3
vscode-sort-json|ric|1.18.0
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.13
stylelint|shi|0.51.0
code-spell-checker|str|1.9.0
language-stylus|sys|1.11.0
stylus-supremacy|thi|2.14.5
pdf|tom|1.1.0

</details>

**Comment by ilanc** [comment]
note: you can hack it into a state which works by using `mapRoot`:
```json
"compilerOptions": {
    "rootDir": ".",
    "mapRoot": "/",
```

**Comment by connor4312** [comment]
@ilanc thanks for the issue. Are you using auto attach? We got a similar issue here (see the comment for the resolution) https://github.com/microsoft/vscode/issues/106803

**Comment by ilanc** [comment]
Hi @connor4312 yup I'm using auto attach.

Btw a few related issues, which I would live your 2c on:
1. auto attach doesn't work for `ts-node`, but does for `node -r ts-node/register`
2. You can't set breakpoints in dependencies

The first one is not a biggie, I can easy setup an `alias` but the later is a real pain to deal with. I can only set breakpoints in built .js files, or singlestep into them from a breakpoint in the dependent module which Im debugging and then set breakpoints. Happy to setup a new issue to illustrate

**Comment by connor4312** [comment]
Where is `which ts-node`? I actually tried this out and discovered an issue on Linux with nvm...

**Comment by connor4312** [comment]
I pushed up some changes that should fix things on Linux. It'll be in the next nightly at 5PM, or if you're impatient you can install [this build](https://memes.peet.io/img/106930-js-debug-nightly.vsix) manually via the "Install from VSIX" command. Note that you'll need to auto attach twice to have the changes apply, as the first auto attach lazily updates the bootloader.

**Comment by ilanc** [comment]
Lekker thanks @connor4312! 

BTW I've just had a look at some of your associated projects and found a random thing I didn't know about before: `console.group` - useful for indenting. But I digress...

What do you think about the 2nd prob - i.e. how to get breakpoints in a dependency to fire whilst debugging a dependent. I'll put a demo together and link it here.

**Comment by ilanc** [comment]
Here you go @connor4312 

I've put together a demo repo: https://github.com/spikedata/vscode-ts-debug-monorepo - which is a trimmed down version of a real repo which unfortunately is private. The demo uses yarn workspaces and has 2 modules - `user` which depends on `lib`. The idea is to put a breakpoint in `lib` and then `debug` user.

I'm going to hold off submitting a new issue right now because I haven't been able to replicate the buggy behaviour which I see in my real repo - i.e. I don't hit breakpoints which I set in my dependencies when I debug a dependent app.

The demo repo is still useful in it's current state if you want to have a poke about though: it does exhibit some unexpected behaviour when debugging - i.e. vs code shows the built .js output instead of the .ts source when you hit the breakpoint. However it is actually hitting the breakpoint - whereas in my real repo I'm not hitting breakpoints in dependencies.

I've got a few theories (noted in the demo repo readme) which I will try later when time permits to see whether I can get the breakpoints to stop working in vscode.

**Comment by connor4312** [comment]
Thanks for the repo!

I think throwing ts-node in the mix is causing some issues. What's happening is that if you run `user/src/cli.ts` with ts-node, it gets compiled and that's all good. But the dependency is also being loaded through ts-node. Even though `lib/build/main/index.js` is a js file, it's still being recompiled with ts-node, and during this process ts-node _replaces_ the sourcemap pointing back to the original .ts file with a sourcemap pointing to the already-compiled .js file. js-debug is actually following the sourcemap correctly, it's just that the sourcemap goes to the wrong place.

What I would recommend here is not using ts-node and run the compiled files directly.

You can get a pretty good experience for this by using watch tasks and launch configs. For example, you can add a tasks.json containing

<details>

```
{
  "version": "2.0.0",
  "tasks": [
    // Compound task that runs the other:
    {
      "label": "Watch all",
      "dependsOn": ["tsc: watch - user/tsconfig.json", "tsc: watch - lib/tsconfig.json"]
    },

    // Watch tasks -- created with the `Task: Configure Task` command
    {
      "type": "typescript",
      "tsconfig": "lib/tsconfig.json",
      "option": "watch",
      "problemMatcher": [
        "$tsc-watch"
      ],
      "group": "build",
      "label": "tsc: watch - lib/tsconfig.json"
    },
    {
      "type": "typescript",
      "tsconfig": "user/tsconfig.json",
      "option": "watch",
      "problemMatcher": [
        "$tsc-watch"
      ],
      "group": "build",
      "label": "tsc: watch - user/tsconfig.json"
    },
  ]
}

```

</details>

And then a launch task that depends on them

```
{
  "type": "node",
  "request": "launch",
  "name": "Launch Program",
  "program": "${workspaceFolder}/user/build/main/cli.js",
  "skipFiles": ["<node_internals>/**"],
  "preLaunchTask": "Watch all"
}
```

With this, the watch tasks will get started the first time you run the "Launch Program" config, and continue running and incrementally compiling in the background. One benefit of this approach is that incremental compilation is nearly instant, and you don't get the second or two of delay that ts-node introduces for any moderately sized program.

Let me know how this works for you.

**Comment by ilanc** [comment]
cool - thanks for that description, it clears up what's going on with `ts-node`. I saw that [ts-node](https://github.com/TypeStrong/ts-node) has the ability to configure where your ts-config.json lives (i.e. `TS_NODE_PROJECT`) but this only works for a single project, which doesn't help when debugging multiple projects at a time like this. I had settled on `ts-node` because of lack of requirement to build, but the second delay is annoying (my repo contains a bunch of cli tools which get run a lot and the delay grates) and the inability to debug is a showstopper.

I had been meaning to play with auto-watch (after reading this: https://medium.com/@stigi/make-vs-code-typescript-even-more-5f20f3046109). I'll try out your suggestion once the nightly is deployed - right now the .js is still giving the `Could not load source..` error and the `rootDir/mapDir` trick doesn't work on monorepos - I get a full path in `sources` with the initial / missing :(

Shew ... it's becoming quite a challenge keeping up with the blog reading just to be able to debug my code. I have great hopes for https://romefrontend.dev/ ...

**Comment by connor4312** [comment]
> I'll try out your suggestion once the nightly is deployed - right now the .js is still giving the Could not load source.. error and the rootDir/mapDir trick doesn't work on monorepos - I get a full path in sources with the initial / missing :(

This was published yesterday. Are you still having issues using the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)? At the moment there's no way to enable trace logs on auto attach (something I need to fix) but if you use a launch.json entry you can grab logs using these instructions:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
>⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by ilanc** [comment]
Howdy,
I'm not having any luck with the insiders build. I have auto attach set to always, but I'm not hitting breakpoints at all in the dependent or in the dependency. see pic attached. I'll play with it some more - I literally am not even hitting a breakpoint in a standalone helloWorld.js?

**Comment by ilanc** [comment]
![2020-09-21T12:53:58](https://user-images.githubusercontent.com/1793957/93759243-204cd480-fc0a-11ea-82af-c3199a86915f.png)

**Comment by ilanc** [comment]
Hmm.. ok it works on a simple standlone hello.js. I'll try send you some logs

**Comment by ilanc** [comment]
So it doesn't attach when run from the vs code terminal. It does attach when you apply your launch.json and push `<F5>`. It's still buggy though:
- I push `<F5>` - it breaks on the 2nd line of code in cli.ts (i.e. console.log not the import statement)?
- I push `<F5>` again to continue - it runs the first console.log() and then i see 'Canceled' in the `Debug Console`
  - btw rt click > Copy All in the Debug Console prepends the `null`s in the output below - they're not visible in vscode 
```log
/home/ilan/.nvm/versions/node/v14.1.0/bin/node ./user/build/main/cli.js
Could not read source map for file:///spike/prototype/vscode-ts-debug-monorepo/lib/build/main/src/index.js: ENOENT: no such file or directory, open '/src/index.js.map'
null: {a: 0, b: 'less than 10'}
null: Canceled
```
![image](https://user-images.githubusercontent.com/1793957/93761150-96066f80-fc0d-11ea-91c5-1c84e349513f.png)
- I push `<F5>` again to restart - this time I click the arrow on the debug control thingy, this time it runs the full program withouth cancelling
```log
/home/ilan/.nvm/versions/node/v14.1.0/bin/node ./user/build/main/cli.js
Could not read source map for file:///spike/prototype/vscode-ts-debug-monorepo/lib/build/main/src/index.js: ENOENT: no such file or directory, open '/src/index.js.map'
null: {a: 0, b: 'less than 10'}
null: {a: 10, b: '10 or greater'}
```

**Comment by ilanc** [comment]
The `Could not read source map` is interesting - the paths are not correct there, let me check whether the `mapRoot` is causing that.

Currently:
- `/spike/prototype/vscode-ts-debug-monorepo/lib/build/main/src/index.js`
- has this:
```js
// ...
//# sourceMappingURL=/src/index.js.map
``

**Comment by ilanc** [comment]
Yes removing mapRoot did the trick (see [commit](https://github.com/spikedata/vscode-ts-debug-monorepo/commit/fc6ef3aa7c986c9da6423e8c643d0db85b8f9e01)).

I can now hit breakpoints in the dependency (`lib`) but only when using launch - not auto-attach.

There are a lot of weird things going on though - like:
- hitting a breakpoint on line 2 immediately on launch
- `Canceled` when pushing F5 to resume
- I seem to hit breakpoints out of order - i.e. if I have a breakpoint in `user/src/cli.ts:4` and in `lib/src/index.ts:7` then I'm expecting debugger to hit the breakpoint in the lib first, then the user, then the lib - that's the order which the code is being executed in.
- however what I get is: break in user twice, then break in lib twice

Let me conclude with a wishlist, next

**Comment by ilanc** [comment]
# Wish list

## debug

  - normal / standalone mode
    - I need to be able to run from the commandline not have to launch from vscode
    - In additional very often I won't be running the tools from the vs code terminal - just a normal unix bash terminal
    - I'd like to be able to add a flag (like `--inspect-brk`) if running from outside vscode, have the cli tool pause, and then fire up vscode (on the root folder of my project), attach the debugger, and set breakpoints in any lib 
 - auto attach mode
    - when running from vscode terminal I'd like all pre-defined breakpoints (in user and lib) to attach seemlessly when I stick breakpoints in .ts files (both in the package being debugged, and in any dependencies)
    - I only want to see .ts not the `build/**/.js` files
    - I'd like to be able to choose between `break on first line` (`--inspect-brk`) vs `run till first breakpoint or debugger` (i.e. `--inspect`) when auto attaching

## watch

- i'm happy to do my own scripts to `tsc watch` - i don't need the tasks
- for most of my code there are build order issues which make parallel builds break (e.g. attempting to build user and lib at the same time will cause the user build to break because lib/build is not available)

**Comment by connor4312** [comment]
> Yes removing mapRoot did the trick

Ah, yea. In most build setups the mapRoot should not be configured.

> There are a lot of weird things going on though 

I don't get these issues locally with auto attach in the repo. In the upcoming [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension) I've made the debug terminal options apply to auto attach, meaning you can grab trace logs now by adding

```
"debug.javascript.terminalOptions": {
  "trace": true
},
```

to your user options. Can you do so for your auto attach scenario? 🙂 


> normal / standalone mode ...

These wishlist items should all work via a launch config like

```
{
  "type": "pwa-node",
  "request": "attach",
  "name": "Attach to process",
  "port": 9229
}
```

**Comment by ilanc** [comment]
My mistake I didn't know you had to disable the old debugger extension and enable the nightly debugger extension (as per https://github.com/microsoft/vscode-js-debug/#nightly-extension). I thought simply running `vs code insiders` was sufficient.

With the nightly debugger extension enabled all the weird issues I reported have disappeared and the debugger in working as expected. I can run from an external terminal and attach in vs code, and I can auto-attach to processes run from the vs code terminal. I am hitting breakpoints (in the correct sequence, and in `user` and `lib`) and it's showing `.ts` source when I hit a break point not `build/**/*.js`.

Great stuff! Many thanks for your help.

I'll attach the trace here, in case it helps.
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/5260083/vscode-debugadapter-0.json.gz)

Some final questions:

- how does you release cadence tie in with vs code releases? do I need to manually enable the nightly debugger extension, when does this get built into the main vs code / vs code nightly?
- do you plan to support debugging via `ts-node`?
  - this can be a useful workflow when user and lib are under heavy development
  - though I get that there are a lot of moving parts and there's a workaround (namely to setup a better watch script)

**Comment by connor4312** [comment]
Awesome, thank you for the confirmation! I will close out this issue as 'fixed' then.

> how does you release cadence tie in with vs code releases? do I need to manually enable the nightly debugger extension, when does this get built into the main vs code / vs code nightly?

VS Code has monthly releases, and js-debug as a builtin extension updates as part of that. The nightly contains the additional changes made since the last stable release.

> do you plan to support debugging via ts-node? 

We do generally support ts-node. It looks like there's just a bad behavior in this scenario that we don't get around. However it looks like there's some flags like --ignore and --scope which you could use to get around it, haven't tried these out myself: https://github.com/TypeStrong/ts-node#cli-and-programmatic-options

**Comment by ilanc** [comment]
For anyone else who reads this thread here's a summary of current state (as of 2020-09-24, I imaging the code-insiders steps below will work in the next code release)

- summary
  - currently the best debugging workflow requires code-insiders, though with some extra `<f5>`ing and constantly switching `auto-attach` on/off you can get by in `code` (v 1.49.1)
  - in `code-insiders` you can use "auto attach: with flag||smart" so that vscode doesn't attach to every node that is spawned from the terminal (e.g. you don't want to attach to `code`, `yarn build`, etc...)
  - with the setup below `code-insiders` will auto-attach to your node script (when run from the code terminal) and run to the first breakpoint
  - it will attach breakpoints in libs correctly
  - in `code` (not `code-insiders`) auto attach only has 2 settings (on/off). In addition you have to run `node --inspect-brk`, `node --inspect` won't attach (but it will in `code-insiders`)

- how to setup debugger so that you can hit breakpoints in your .ts libs:
  - `code-insiders`:
    - enable [vs code debugger nightly extension](https://github.com/microsoft/vscode-js-debug/#nightly-extension) (prob not required from next code release)
    - launch.json = you must have a setting with `{ "type": "pwa-node", "request": "attach" }` and it must be active (see the [launch.json](https://github.com/spikedata/vscode-ts-debug-monorepo/blob/master/.vscode/launch.json) in the demo repo)
    - set auto attach=with flag, or perhaps smart (so that the debugger doesn't attach to all node processes spawned from the terminal)
    - you have to build your .ts to .js first and debug the .js (you can't use `ts-node`, `node -r register/ts-node`)
    - and you can only debug node
      - `node --inspect ./vscode-ts-debug-monorepo/user/build/main/src/cli.js`
      - will auto-attach and run to first breakpoint
      - can set breakpoints in libs
      - NOT
        - `ts-node`: --scope and --ignore don't work
        - `node -r register/ts-node`
  - `code`:
    - as above except to debug:
      - `node --inspect-brk /spike/prototype/vscode-ts-debug-monorepo/user/build/main/src/cli.js`
      - then hit-`<F5>` in vscode to attach, will stop at first line, then `<F5>` again to run to first breakpoint
      - can set breakpoints in libs
      - switch `autoattach=off` when not debugging to stop debugger attaching to all node's
