### ISSUE TITLE
Clipboard API doesn’t work on Codespaces (using Safari)

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#106997]
- VSCode Version: Codespaces
- OS Version: MacOS Catalina and iPadOS 13

Steps to Reproduce:

It seems the **Clipboard API** is not working, at least using **Safari**

1. Create an extension using the [Clipboard API](https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-clipboard) which as documented, should be used on Remote Development: `env.clipboard.writeText(editor.document.getText(editor.selection));`
2. Open Codespaces and install the extension (My `alefragnani.copy-word` extension does exactly that)
3. Use its command `Copy Word: Copy`, which will select the word where the cursor is located and should copy the selected text to clipboard 
4. Navigate to other location
5. Run `Paste` command (or use `Cmd V` shortcut)
6. Doesn’t work: instead of pasting the the newly selected/copied text, it pastes the previous clipboard content (not created using the extension)

* I tested on iPadOS 13 and MacOS Catalina and it fails.
* I tested on Edge (Chromium) and it works perfectly (I guess it should work on Chrome too)
* I didn’t test on Firefox (yet).

BTW, I tried to debug my extension on Codespaces **(on iPadOS)**, but it seems not possible/supported. I’m able to build the extension and hit the Debug button. The Debug toolbar appears but no `[development ]` window/tab appears. _Is there a way to debug VSCode extensions right from Codespaces?_. 

> As described below, debugging on Desktop (macOS Catalina) works just fine. Safari just _blocks_ the window, but you click the button and the `[development ]` window correctly appears.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alefragnani** [comment]
Updated the description and comments. Testing on Edge (Chromium) worked just fine.

**Comment by bpasero** [comment]
@alefragnani 

> BTW, I tried to debug my extension on Codespaces, but it seems not possible/supported. I’m able to build the extension and hit the Debug button. The Debug toolbar appears but no [development ] window/tab appears. Is there a way to debug VSCode extensions right from Codespaces?

Yes, it should open a new tab. Maybe it was blocked?

**Comment by alefragnani** [comment]
Hi @bpasero ,

Sorry about not updating the description properly. I tested debugging again later and indeed _it was blocked_ by Safari, but only on Desktop (macOS Catalina). On iPadOS, it doesn't display anything (neither a _blocked windows_ warning/icon), so I couldn't debug, yet.

I'll update the description. Thanks

**Comment by alefragnani** [comment]
@bpasero I think the **safari** label should remain, because the issue is happening using Safari, both on MacOS and iPadOS.

**Comment by rebornix** [comment]
It seems the Clipboard API is coming to Safari https://developer.apple.com/safari/technology-preview/release-notes/, we should reevaluate once it lands in Safari stable.

**Comment by rebornix** [comment]
I tested the improvements of `clipboard` api in the latest Safari Technology Preview but it doesn't solve this particular problem. The copy/paste request is coming from the extension host instead of user action, Safari will then block it.

**Comment by TylerLeonhardt** [comment]
verification steps:

* Open insiders.vscode.dev/github/microsoft/vscode on Safari (bonus points for it being on iPad but it doesn't matter)
* Install the GHPR extension
* Go to a random line in a file
* Run the `GitHub Issues: Copy GitHub Permalink` command

Your clipboard should contain the copied permalink now.

**Comment by alefragnani** [comment]
Hi @TylerLeonhardt ,

I’m glad to report that it is also working on iPadOS 15.2 and MacOS Big Sur 🚀 

I just tested my **Copy Word** extension (the reason why I opened this issue) and it is working perfectly.

Thank you!
