### ISSUE TITLE
Windows: .gitattributes and .gitignore should always show extension

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#10694]
@DarkNami says

> VSCode Version: 1.4.0
> OS Version: Win7 x64

> After installing Visual Code, I don't know which file is .gitattributes, and which file is .gitignore ...
> ![filename](https://cloud.githubusercontent.com/assets/5100919/17802988/133568a8-6626-11e6-964f-6e1111714bf6.png)

> although I added 'AlwaysShowExt' in filetype, but not working...
> ![regedit](https://cloud.githubusercontent.com/assets/5100919/17803025/43bf37c4-6626-11e6-875a-2772e4531a66.png)

**Comment by DarkNami** [comment]
If any user checked "Register Code as an editor supported file types", and Git config filename (.gitattributes, .gitconfig, .gitignore) is hidden. (File extensions of known file types are hidden)

You can create an empty string value here named "AlwaysShowExt" in subkey:
![2016-8-19 19-07-21](https://cloud.githubusercontent.com/assets/5100919/17808171/251dd710-6641-11e6-81f0-32330a2f66d9.png)

then you can see Git config filename again.
![2016-8-19 19-10-27](https://cloud.githubusercontent.com/assets/5100919/17808178/3143d2b0-6641-11e6-8c55-cb3482be5e60.png)

**Comment by joaomoreno** [comment]
Wait, so it's not fixed. It's only fixed in your machine because you added that registry key?

**Comment by DarkNami** [comment]
Windows 7 default hide extensions for known file types.

Before install VSCode, Windows don't know .gitattributes, .gitconfig and .gitignore.
So we can see the full filename.

After installed VSCode with "Register Code as an editor supported file types" option, 
Git config files become "known file types"  (registed by VSCode).
So Windows 7 hide extensions (.gitattributes) for known file types, the filename become empty in Windows Explorer.

This situation will happen on all linux hidden file (filename start with dot).
