### ISSUE TITLE
Tasks returned from `fetchTasks` do not contain `dependsOn` information

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#106946]
- VSCode Version: 1.49.0
- OS Version: Win10 10.0.19041

Steps to Reproduce:

1. Create a task that uses the `dependsOn` property to depend on another task
1. In extension code, call `vscode.tasks.fetchTasks()`

Expected:
Task returned would contain all information including `dependsOn`

Actual:
Task has name and definition, and a few other properties, but does not have `dependsOn`

Does this issue occur when all extensions are disabled?: N/A

**Comment by bwateratmsft** [comment]
@alexr00 FYI

**Comment by alexr00** [comment]
I thought that we already `dependsOn` in the API, but it looks like we don't.

**Comment by bwateratmsft** [comment]
Yeah, this is where there was a difference between the config API and the `fetchTasks` API. As part of our Docker build / run / debug process, we need to build up a task tree, in order to "find" the `docker-build` / `docker-run` tasks. Knowing information from those tasks allows us to save a significant amount of time and reduce the complexity of the `launch.json` and `tasks.json` files.

So far we've been using the config API which works fine in most cases, but when using workspaces instead of workspace folders, it starts to break down.

I have a [work item](https://github.com/microsoft/vscode-docker/issues/2289) to switch to mostly/entirely `resolveDebugConfigurationWithSubstitutedVariables()`; because this runs _after_ the tasks instead of before, it might eliminate the need for building the task tree. I haven't done enough investigation to be sure though.
