### ISSUE TITLE
After the upgrade is obvious Caton

### ISSUE THREAD

**Issue by OmidYi** [microsoft/vscode#106987]
Issue Type: <b>Performance Issue</b>

After upgrading to 1.49.1, and after installing pylance, the experience is obviously Caton. I can't judge whether it is caused by installing pylance or after upgrading.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (9.10GB free)|
|Process Argv|--crash-reporter-id 84fb50c7-edf3-4e68-b5e5-667f9da4f7ef|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    80	  4364	code main
    0	    27	  5324	   crashpad-handler
    0	    85	 12820	   window (undefined)
    0	    44	 14452	   utility
    3	    91	 15156	   shared-process
    0	   209	 15880	   window (serial_port.py - NetSerial_Client - Visual Studio Code)
    0	    74	  1800	     searchService
    0	     7	  5420	     console-window-host (Windows internal process)
    0	    15	 10284	     watcherService 
    0	    11	 16192	       console-window-host (Windows internal process)
    0	    88	 10760	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     7	 14360	     console-window-host (Windows internal process)
    0	   274	 18140	     extensionHost
    0	   208	  1836	       electron_node bundle.js 
    0	     4	  9776	       d:\CodeLibrary\NetSerial\NetSerial_Client\.venv\Scripts\python.exe c:\Users\Elin\.vscode\extensions\ms-python.python-2020.8.109390\pythonFiles\lib\python\debugpy\adapter
    0	    11	  7832	         console-window-host (Windows internal process)
    0	    15	 12692	         D:\������װ\python3.8.5\python.exe c:\Users\Elin\.vscode\extensions\ms-python.python-2020.8.109390\pythonFiles\lib\python\debugpy\adapter
    0	    89	 21396	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     4	 16288	       "D:\CodeLibrary\NetSerial\NetSerial_Client\.venv\Scripts\python.exe" c:\Users\Elin\.vscode\extensions\ms-python.python-2020.8.109390\pythonFiles\lib\python\debugpy\launcher 62037 -- d:\CodeLibrary\NetSerial\NetSerial_Client\start.py
    0	    15	 12728	         D:\������װ\python3.8.5\python.exe c:\Users\Elin\.vscode\extensions\ms-python.python-2020.8.109390\pythonFiles\lib\python\debugpy\launcher 62037 -- d:\CodeLibrary\NetSerial\NetSerial_Client\start.py
    0	     4	 21956	           D:\CodeLibrary\NetSerial\NetSerial_Client\.venv\Scripts\python.exe c:\Users\Elin\.vscode\extensions\ms-python.python-2020.8.109390\pythonFiles\lib\python\debugpy --connect 127.0.0.1:62036 --configure-qt auto --adapter-access-token 6ecd9f7d5662f5bbd4e7a7beced513edf269567d347929c69900450f018a34d1 d:\CodeLibrary\NetSerial\NetSerial_Client\start.py
    0	    43	  5272	             D:\������װ\python3.8.5\python.exe c:\Users\Elin\.vscode\extensions\ms-python.python-2020.8.109390\pythonFiles\lib\python\debugpy --connect 127.0.0.1:62036 --configure-qt auto --adapter-access-token 6ecd9f7d5662f5bbd4e7a7beced513edf269567d347929c69900450f018a34d1 d:\CodeLibrary\NetSerial\NetSerial_Client\start.py
    2	    88	 15968	   window (问题报告程序)
    1	   330	 16892	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (serial_port.py - NetSerial_Client - Visual Studio Code)
|    Folder (NetSerial_Client): 3586 files
|      File types: pyc(1415) py(1409) pyd(57) txt(45) exe(21) h(14) html(13)
|                  htm(13) dll(9) gif(9)
|      Conf files: launch.json(1) settings.json(1);
```

</details>
<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
GBKtoUTF8|buk|0.0.2
EnglishChineseDictionary|Cod|1.0.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.2
code-runner|for|0.11.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
git-graph|mhu|1.26.0
vscode-docker|ms-|1.6.0
vscode-language-pack-zh-hans|MS-|1.49.2
python|ms-|2020.8.109390
vscode-pylance|ms-|2020.9.5
remote-wsl|ms-|0.44.5
hexeditor|ms-|1.3.0
powershell|ms-|2020.6.0
vscodeintellicode|Vis|1.2.10
vim|vsc|1.16.0
better-align|wwm|1.1.6
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by aeschli** [comment]
What do you mean by `the experience is obviously Caton` ?
Is it a problem of the pylance extension? Can you file the issue there?
