### ISSUE TITLE
Adding lines are very slow

### ISSUE THREAD

**Issue by twepo** [microsoft/vscode#106925]
- VSCode Version: Vsiaul Studio Code - Insiders 1.50.0
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Type some lines
2. Using enter key to add multiple lines or backspace to remove multiple lines 

[video_and_cpu.zip](https://github.com/microsoft/vscode/files/5237340/video_and_cpu.zip)

Does this issue occur when all extensions are disabled?:  Yes

Extension : 0

I assume Windows update affect vscode performance.

**Comment by alexdima** [comment]
@twepo Does this slowness reproduce when closing all vs code instances and starting with `code --disable-renderer-accessibility` ?
