### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by GQ105501** [microsoft/vscode#106902]
Uncaught Error: EPIPE: broken pipe, write
Process exited with code 1

There is no problem with the CMD command line, but an error will be reported when sending a request in vs code debug mode

**Comment by GQ105501** [comment]
There is no problem with the CMD command line, but an error will be reported when sending a request in vs code debug mode

**Comment by aeschli** [comment]
Can you give more details how you get this error? Reproducible steps and screenshots would be helpful.
