### ISSUE TITLE
[UI] Weird color behavior with Extensions SideBar Foreground

### ISSUE THREAD

**Issue by psudo-dev** [microsoft/vscode#106963]
- VSCode Version: 1.49
- OS Version: Mac OS 10.13

Steps to Reproduce:

## Weird color behavior with Extensions SideBar
![2020-09-17 17 34 02](https://user-images.githubusercontent.com/51300850/93526306-a668d280-f90d-11ea-8827-9ae255bbe1eb.gif)

1. Select some extension: Extension bar in focus
- Selected:
  -  title/descrition: **YELLOW** comes from `list.activeSelectionForeground`
  - author: **RED** from `list.focusForeground`
- Non-selected:
  - title/descrition: **GREEN** `sideBar.foreground`
  - author: **LIGHT BLUE** `foreground`
2. Hover: Extension bar in focus
- Selected:
  - title/descrition: **YELLOW** comes from `list.activeSelectionForeground`
  - author: **RED** from `list.focusForeground`
- Non-selected:
  - title/descrition: **PINK** from `list.hoverForeground`
  - author: **LIGHT BLUE** `foreground`
3. Click outside Extension bar: Extension bar unfocused:
- Selected:
  -  title/descrition: **DARK BLUE** from `list.inactiveSelectionForeground`
  - author: **DARK BLUE** from `list.inactiveSelectionForeground`
- Non-selected:
  - title/descrition: **GREEN** `sideBar.foreground`
  - author: **LIGHT BLUE** `foreground`
4. Hover: Extension bar unfocused:
- Selected:
  -  title/descrition: **RED** from `list.focusForeground`
  - author: **DARK BLUE** from `list.inactiveSelectionForeground`
- Non-selected:
  - title/descrition: **PINK** from `list.hoverForeground`
  - author: **LIGHT BLUE** `foreground`

## Solution
- Author and Title/Description should always have the same color
  - `foreground` color shouldn't be used over `sideBar.foreground` or `list.hoverForeground`

#### Outcome:
1. Select some extension: Extension bar in focus
- Selected: `list.activeSelectionForeground`
- Non-selected: `sideBar.foreground`
2. Hover: Extension bar in focus
- Selected: `list.activeSelectionForeground`
- Non-selected: `list.hoverForeground`
3. Click outside Extension bar: Extension bar unfocused:
- Selected:  `list.inactiveSelectionForeground`
- Non-selected: `sideBar.foreground`
4. Hover: Extension bar unfocused:
- Selected: `list.focusForeground`
- Non-selected: `list.hoverForeground`

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
To verify:

Have following setting

```
"workbench.colorCustomizations": {
		"list.activeSelectionForeground": "#f0e10c",
		"list.focusForeground": "#ff0000"
	}
```

Select/Focus the extension in the view and make sure author, title, description are having same colour. Author colour will be a little less opaque than others.

**Comment by mjbvz** [comment]
Looks like there is still some inconsistency with `list.focusForeground`.

Using those settings, here is `list.activeSelectionForeground`:

![Screen Shot 2020-10-01 at 2 12 54 PM](https://user-images.githubusercontent.com/12821956/94864078-4df70200-03f0-11eb-98d7-d7c1cc90f7e1.png)


And here's `list.focusForeground`:

![Screen Shot 2020-10-01 at 2 12 58 PM](https://user-images.githubusercontent.com/12821956/94864098-551e1000-03f0-11eb-96cc-2254b7768595.png)


The publisher (`Matt`) and the icons (the gear and the download symbol) do not inherit the red color in this case

**Comment by sandy081** [comment]
Fixed it.
