### ISSUE TITLE
Auto attach should not work for `yarn` scripts

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#106991]
1. Run `npx vsce --version`, no auto attach
2. Run the same but with yarn `yarn vsce --version`, it auto attaches! 🐛

**Comment by connor4312** [comment]
Let's merge with https://github.com/microsoft/vscode/issues/106991

**Comment by connor4312** [comment]
Changed the default to exclude yarn. You can also add `!**/.yarn/**` to your auto attach smart patterns to exclude it.
