### ISSUE TITLE
Web: cannot drop VSIX into extensions view to install

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#106914]
I see a blue drop target but nothing happens.

**Comment by sandy081** [comment]
I do not think we support installing by VSIX (from local desktop) in Web.

I would disable it.

**Comment by bpasero** [comment]
It is possible to read the contents from a drop operation, e.g. we do allow to drag and drop to the explorer to upload.

**Comment by sandy081** [comment]
Yeah, it can be done if there is a server. Otherwise it will be disabled.

May I know how the data is transferred in explorer in Web?

**Comment by bpasero** [comment]
@sandy081 

https://github.com/microsoft/vscode/blob/93c96b63c0ad62ac9d9c1dc5a76763c2786f9300/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L995-L995

**Comment by sandy081** [comment]
Thanks. Seems not straight forward. Will take a look next milestone.
