### ISSUE TITLE
Intellisense Lightbulb does not appear when green squiggle clicked in C++ file

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/vscode#10695]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder with C++ files in it
2. With no c_cpp_properties.json file in .vscode directory ...
3. #include directives will be underlined with green squiggle
4. This link: 

http://code.visualstudio.com/docs/languages/cpp

says:

> To enable code completion and navigation, you will need to generate a c_cpp_properties.json file:
> 
> Hover over any green squiggle in a source file (e.g. a #include statement).
> Click the lightbulb that appears underneath the mouse cursor.
> Click Add include path to settings.

When I click the green squiggle no lightbulb appears.

**Comment by alexandrudima** [comment]
Moved to Microsoft/vscppsamples#159
