### ISSUE TITLE
The terminal process failed to launch Starting directory does not exist

### ISSUE THREAD

**Issue by payonel** [microsoft/vscode#106958]
Version: 1.50.0-insider
Commit: d1f267742169584db010716d92addf50d4cd8139
Date: 2020-09-17T07:03:46.695Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.1.0-050100-generic

and 

Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:20:50.359Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.1.0-050100-generic

Steps to Reproduce:

1. empty project, no extensions
2. add tasks.json with simple shell command, echo, to print hello
3. run task

The terminal for the task is never invoked, it fails:
```
> Executing task: make <

The terminal process failed to launch: Starting directory (cwd) "/home/payonel/code/sandbox/~/code/sandbox" does not exist.

Terminal will be reused by tasks, press any key to close it.
```

Please note the bad path, how it uses ~ inside the path

Does this issue occur when all extensions are disabled?: Yes

Notes:
1. This just started happening on a recent vscode insiders build. vscode 14.9 is working, the insiders build of 15.0 is not
2. This bug repros with integrated terminal, or any termainl option (custom or not). This error appears to occur before the terminal process is even invoked. It doesn't matter which terminal i use.
3. This effectively breaks running any task in vscode insiders. I am now having to use vscode release version

**Comment by ZNielsen** [comment]
I started having the same issue today. I around lunch from the 9/16 release. 9/16 was working, the 9/17 release is broken.

**Comment by ZNielsen** [comment]
This build was working:
```
Version: 1.50.0-insider
Commit: 9e505675670d65138405321a60b0df4ddec28799
Date: 2020-09-16T05:43:58.570Z (1 day ago)
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

Updated build, not working:
```
Version: 1.50.0-insider
Commit: d1f267742169584db010716d92addf50d4cd8139
Date: 2020-09-17T07:09:53.566Z (12 hrs ago)
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by payonel** [comment]
I wonder if these commits are related
9-16
https://github.com/microsoft/vscode/commit/7bf5773eb288fd71ae0d3aa256988949c95abcf8

9-17
https://github.com/microsoft/vscode/commit/3808cb3712e651cb96b4ccfe48c05d2fbd5f23cf

**Comment by payonel** [comment]
Oh, look at the comment on https://github.com/microsoft/vscode/commit/3808cb3712e651cb96b4ccfe48c05d2fbd5f23cf
this ticket might be a duplicate of https://github.com/microsoft/vscode/issues/106877

**Comment by payonel** [comment]
confirmed fixed in
```
Version: 1.50.0-insider
Commit: 3156f1fbfcbb7bdd5f7aa24b4cde71526d1980c8
Date: 2020-09-17T17:19:24.943Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.1.0-050100-generic
```

**Comment by mwangaben** [comment]
Same issue here with  

Version: 1.50.0-insider
Commit: 9e505675670d65138405321a60b0df4ddec28799
Date: 2020-09-16T05:43:58.570Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

**Comment by payonel** [comment]
@mwangaben strange, it should be working in that version (from my local tests). but test the latest update: 
```
Date: 2020-09-17T17:19:24.943Z
```

**Comment by mwangaben** [comment]
For my surprise after restart Vscode is now working as per usual
