### ISSUE TITLE
Add devcontainer "postStartCommand" support to Codespaces

### ISSUE THREAD

**Issue by mchelen-gov** [microsoft/vscode#106944]
Please add support in Codespaces for the devcontainer `postStartCommand` config property https://code.visualstudio.com/docs/remote/devcontainerjson-reference

**Comment by aeschli** [comment]
I believe this should be filed against Codespaces (https://github.com/MicrosoftDocs/vscodespaces), no?

**Comment by mchelen-gov** [comment]
@aeschli oh yup you're right, thanks! found https://github.com/MicrosoftDocs/vscodespaces/issues/403
it's kind of confusing what features belong to which project :sweat_smile:
