### ISSUE TITLE
Upgrade from deb_1.48.2-1598353430 to apt_1.49.0-1599744551 does not install dependency libgbm

### ISSUE THREAD

**Issue by Andrei-Paul** [microsoft/vscode#106936]
- VSCode Version: **1.48.2-1598353430 -> 1.49.0-1599744551**
- OS Version: **Ubuntu 20.04.1 LTS**

Steps to Reproduce:

0. libgbm-dev not installed
1. Download and install code_1.48.2-1598353430_amd64.deb --> VSCode works
2. Do apt update; apt-upgrade VSCode to 1.49.0-1599744551 --> VSCode fails with:
/usr/share/code/bin/../code: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
3. apt install libgbm-dev --> VSCode works

Expected:
upgrade checks for dependency and installs missing library

**Comment by Tyriar** [comment]
@deepak1556 new Electron 9 dep needs to be declared here?

https://github.com/microsoft/vscode/blob/master/resources/linux/rpm/dependencies.json

https://github.com/microsoft/vscode/blob/92a30ed2650c31839a453bb088be9a4e7935a393/resources/linux/debian/control.template#L4

**Comment by deepak1556** [comment]
I didn't know about this dependency configuration in the codebase, yes adding `libgbm1` should be sufficient. It is a new dependency for chromium 83 to use memory buffers in gpu code path.

**Comment by rebornix** [comment]
Tested this by upgrading from 1.48.2 to 1.50.1
