### ISSUE TITLE
"Activating extension 'ms-vsonline.vsonline' failed" when running extension tests with a custom --user-data-dir

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#106921]
I see this error anytime I run my extension's tests in the extension host:

> Activating extension 'ms-vsonline.vsonline' failed: ENOENT: no such file or directory, mkdir '/Users/danny/Dev/Dart-Code/.dart_code_test_data_dir/User/globalStorage/ms-vsonline.vsonline'.

![Screenshot 2020-09-17 at 08 52 51](https://user-images.githubusercontent.com/1078012/93437179-93311500-f8c3-11ea-867b-721cf92c9484.png)

I pass a custom `--user-data-dir` when running tests so that the tests aren't influenced by my own VS Code User Settings etc.

**Comment by jrieken** [comment]
Looks like a problem with ms-vsonline

**Comment by DanTup** [comment]
Oops sorry, I thought it was now a built-in extension but it's not. I'll re-raise over there. Thanks!
