### ISSUE TITLE
Separate Open Editors from Explorer (thus creating a Vertical Tab Bar)

### ISSUE THREAD

**Issue by mihaibrana** [microsoft/vscode#106927]
Root cause:
- There are often times when we debug a difficult issue and we have to open a lot of files.
- It often happens that file names are quite long, thus the tab bar space is quickly exhausted.

Already-explored solutions:
- Some editors have addressed this concern by enabling a vertical tab bar. 

Existing value:
- VS Code already has such a thing: the Open Editors area :). However, this area is tied into the Explorer, which forces it to be bundled with the project files explorer.

Proposed UI:
![image](https://user-images.githubusercontent.com/60734380/93439196-8cf46600-f8ce-11ea-9cea-8bad2f609316.png)

Perceived improvements:
- Vertical tab allowing more flexibility in working with large code bases.
- Improving use of horizontal screen space
- No conflict between explorer / open editors.
- Open Editors are closer to the Search / Version Control area, which /may/ create a better user experience when navigating search results / version history.
- Reduces the necessity to keep reorganizing tabs / pin tabs. In editors where vertical tab bars are enabled, I have personally perceived increased productivity due to the fact that I can build STABLE tab editor layout, which helps me a lot when debugging in multiple files (I confidently know where my entry point is and what the affected modules are).
- Vertical tab bar can be reused for other purposes

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we will probably not do this in the future since you can just drag and drop the open editors area anywher you want. Thanks

**Comment by mihaibrana** [comment]
@isidorn totally understandable given the amount of things you guys have to do :). I would just like to clarify that the feature request is not addressed in any way by the fact "you can just drag and drop the open editors area anywher you want", like your reply is phrased as :). But what you said is still valuable to me because I didn't know I could do that, so thanks! :D 

Actually you've given me the idea to rephrase the feature request as:

"Allow groups in the Explorer to be arranged in a second column as well"

You've opened me to the possibility that we could actually drag any of those groups to a second column.

There is even greater value there when we talk about Workspaces. A double-column Explorer could allow easier navigation of such code-bases, especially if in the future the folders of a Workspace could also be rearranged (but that's getting a bit ahead of myself).

Anyway, in case I would like to contribute to doing this (perhaps by means of Extending Code or as a locally built hack), could you tell me if you think that it is difficult to add a new column to the Explorer? If it's doable, would you be able to share some high level tips about the rendering flow of the Explorer?

**Comment by martin-braun** [comment]
This is not possible using the introduced side-panel which is a big plus.
