### ISSUE TITLE
File Language is not persisted when file is closed and reopened

### ISSUE THREAD

**Issue by luisrudge** [Microsoft/vscode#107]
![code](https://cloud.githubusercontent.com/assets/941075/11254833/1a063b96-8e2a-11e5-97a9-412e6b7a2499.gif)

**Comment by bpasero** [comment]
@luisrudge yes this is currently not supported.

**Comment by bpasero** [comment]
Actually this will work as long as the file is under the working files section. Once the file is not, closing it will also make the mode decision lost.

**Comment by bpasero** [comment]
Possible via https://github.com/Microsoft/vscode/issues/3612
