### ISSUE TITLE
Replace field for global search and replace does not scroll

### ISSUE THREAD

**Issue by septatrix** [microsoft/vscode#107004]
Issue Type: <b>Bug</b>

1. Select the Search tab and extend the Replace menu so you are in the familiar "Search & Replace" mode.
2. Insert a whole file with many lines in the search field -> The field gets a scrollbar and the layout is still reasonable
3. Now insert the whole file in the replace field -> It does not get a scroll bar and the layout is broken
4. Use tab to navigate to the bottom where the replacements are previewed (tabbing as scrolling does not work)
5 The file replacement section is also broken and only show a single line partially (but you can scroll to see other lines)

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:20:50.359Z)
OS version: Linux x64 5.4.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3499)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.68GB (0.12GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 37c60d0f-5ff0-40fc-af12-228ad2696997|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-wayland|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by roblourens** [comment]
#105421
