### ISSUE TITLE
Native title bar has no text under ChromeOS/crostini

### ISSUE THREAD

**Issue by hellige** [microsoft/vscode#107044]
- VSCode Version: 1.49.1 (also in insiders 1.50)
- OS Version: ChromeOS 85.0 / Debian 10

Steps to Reproduce:

1. Run vscode with native title bar style.
2. Observe that there is no title bar text.
3. Switch to custom title bar style: title bar text appears as expected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
Can you provide screenshots of the experiences so I can understand what is going on? I do not have a device to test this with.

**Comment by hellige** [comment]
Sure, attached!
![Screenshot 2020-10-02 at 3 39 50 PM](https://user-images.githubusercontent.com/14448/94968088-e6ab8180-04c5-11eb-94de-1e2bbefa9160.png)
![Screenshot 2020-10-02 at 3 38 58 PM](https://user-images.githubusercontent.com/14448/94968091-e6ab8180-04c5-11eb-9e1f-0259a7b45a51.png)

The black title-bar is the vscode "custom" style, looks fine. The grey title-bar is the vscode "native" style, notice the title text is completely missing from that one. The text still appears properly under the window in the alt-tab switcher.

**Comment by hellige** [comment]
Aha, I now see that this is a Chromium/ChromeOS bug: https://bugs.chromium.org/p/chromium/issues/detail?id=918314

Not sure if that means it should be closed here or what, I'll leave that to you! Sorry for the bad report!

**Comment by sbatten** [comment]
Since this is affecting all ChromeOS/Crostini apps, I will just close this as upstream.
