### ISSUE TITLE
Flutter hot reload

### ISSUE THREAD

**Issue by callmejm** [microsoft/vscode#107054]
Issue Type: <b>Bug</b>

flutter project wont trigger hot reload when save (control + s)

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (18.18GB free)|
|Process Argv|--crash-reporter-id d2fc37b6-d267-4c08-bb00-547c41dc90ea|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.14.1
flutter|Dar|3.14.1
emulate|Die|1.4.0
es7-react-js-snippets|dsz|3.0.0
prettier-vscode|esb|5.6.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1

</details>

**Comment by vuthanhlong94** [comment]
Dao yêu

**Comment by aeschli** [comment]
Can you file this against the flutter extension?
