### ISSUE TITLE
Weird behavior of the problemMatcher.

### ISSUE THREAD

**Issue by jhasse** [Microsoft/vscode#10701]
- VSCode Version: 1.4.0
- OS Version: Fedora Linux 24

Steps to Reproduce:

main.cpp:

``` cpp
int main() {
    error
}
```

.vscode/tasks.json:

``` json
{
    "version": "0.1.0",
    "command": "echo",
    "isShellCommand": true,
    "args": ["main.cpp:2:5: error: test\nfoo:1:2: error: test\nmain.cpp:3:0: warning: test"],
    "showOutput": "always",
    "problemMatcher": {
        "owner": "cpp",
        "fileLocation": ["relative", "${workspaceRoot}"],
        "pattern": {
            "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
            "file": 1,
            "line": 2,
            "column": 3,
            "severity": 4,
            "message": 5
        }
    }
}
```

The output is:

```
main.cpp:2:5: error: test
foo:106:7: error: test
main.cpp:3:0: warning: test
```

But the first error isn't shown for me. If I remove the second or the third line, it works. Is something wrong with my regexp?

**Comment by dbaeumer** [comment]
@jhasse the problem matcher looke great to me. I even verified it with https://regex101.com/

**Comment by dbaeumer** [comment]
OK. The problem is that the error parser currently collects errors per file in batches. So 
```
main.cpp:2:5: error: test
main.cpp:3:1: warning: test
foo:1:2: error: test
```
produces the correct result.

The reason being is that the task framework wants to report errors are early as possible. So when line foo... is parsed in your example errors for main.cpp are reported and then the internal state for the problem matcher is clear. When main.cpp shows up again only those errors are reported.

Is there a reason why your errors show up so intermixed ?

**Comment by jhasse** [comment]
Yes, it happens because of errors/warnings in header files. Minimal example:

foo.hpp
```cpp
#error second
```

main.cpp
```cpp
#error first
#include "foo.hpp"
#error third
```

GCC's output:
```
main.cpp:1:2: error: first
#error first
 ^
In file included from main.cpp:2:
./foo.hpp:1:2: error: second
#error second
 ^
main.cpp:3:2: error: third
#error third
 ^
3 errors generated.
```

**Comment by dbaeumer** [comment]
@jhasse Thanks.

Making it a bug.

**Comment by jhasse** [comment]
Thank you :)

**Comment by dbaeumer** [comment]
This got addressed a while ago. The errors are now collected de-dup in the problem collector and then send as soon as the error count changes for a resource.
