### ISSUE TITLE
Screen stays blank using code over Xwindow through ssh.

### ISSUE THREAD

**Issue by istnv** [microsoft/vscode#107085]
- VSCode Version: 1.49.0 and 1.49.1
- OS Version: Linux x64 5.4.0-47-generic

Steps to Reproduce:
I use ssh to another computer and code has been working fine until the new 1.49 releases. The screen is all white. The cursor changes and some menu components appear when moving the mouse over the window, but the rest of the screen stays white and unusable. I had to downgrade to 1.48.2 in order to submit this.

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 4000)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|31.21GB (24.37GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
vscode-npm-script|eg2|0.3.13
vscode-great-icons|emm|2.1.56
beautify|Hoo|1.5.0
search-node-modules|jas|1.3.0
auto-comment-blocks|kev|1.0.1
node-module-intellisense|lei|1.5.0
cpptools|ms-|1.0.0
debugger-for-chrome|msj|4.12.10
material-icon-theme|PKi|4.3.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/101069

Please try launching code with `--no-xshm` flag.

**Comment by istnv** [comment]
> /duplicate #101069
> 
> Please try launching code with `--no-xshm` flag.
That works for now, thanks.
BTW I did search other issues, first. :)
