### ISSUE TITLE
Can not use Preference Sync after changing Microsoft account

### ISSUE THREAD

**Issue by Destroyer-LDB** [microsoft/vscode#107093]
- VSCode Version: Stable 1.49.1 (user setup)
- OS Version: Windows 10 Education 1909

Steps to Reproduce:

1.Sign in to Preference Sync with a Microsoft account;
2.Delete the account and use another one;
3.Click on "Accounts" on the activity bar, and it says "Microsoft is currently unavailable".
![error](https://user-images.githubusercontent.com/60999555/93696156-c5eb3f80-fb47-11ea-9448-6601eedd3811.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Destroyer-LDB** [comment]
The problem didn't occur when I tested again on the Insiders Edition because I haven't used it.

**Comment by Destroyer-LDB** [comment]
I explored the issues above, and none of them matches with my problem.

**Comment by Destroyer-LDB** [comment]
Anyone here to help me? I used another PC to sign into Preference Sync with my new Microsoft account and it succeeded. But I think it is because I have never used VSCode on this computer.

**Comment by RMacfarlane** [comment]
This sounds like https://github.com/microsoft/vscode/issues/106321, this message appears when we're unable to refresh the stored credentials. I fixed a bug around this which has not yet shipped. In the mean time, can you try opening the windows credential manager, select "Windows Credentials", and delete "vscode-microsoft.login/account" to clear out the old data and sign in again?

**Comment by Destroyer-LDB** [comment]
@RMacfarlane Thank you! The Problem has been solved.
