### ISSUE TITLE
Deprecate list/tree keyboardSupport option

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#107011]
The `keyboardSupport` list/tree option exists in order for the widget to handle keyboard events itself. There should be no use for this in the workbench any more since keyboard events should be handled by the keybinding service, enabling custom keyboard shortcuts.

There are currently two usages:

- [`CommentsList`](https://github.com/microsoft/vscode/blob/59ef2e37e79a85f2eb1382eaad5dc842fa611f21/src/vs/workbench/contrib/comments/browser/commentsTreeViewer.ts#L185-L185) @rebornix 
- [`HelpPanel`](https://github.com/microsoft/vscode/blob/e29d25303c6ad7fd3045f96353df33d259f5619a/src/vs/workbench/contrib/remote/browser/remote.ts#L432-L432) @alexr00 

Could you review this flag in your use case and let me know why you would need it?

Thanks!

**Comment by alexdima** [comment]
This is my workaround for the `stopPropagation()` -- b89779ea91fe400070903b7ef8b3f3c32595f39b

**Comment by alexr00** [comment]
It isn't needed in the `HelpPanel`. Removed!

**Comment by joaomoreno** [comment]
Ping @rebornix

**Comment by rebornix** [comment]
It's no longer needed in comment list, thanks!
