### ISSUE TITLE
Allow ability to do Search In Files (cmd+shift+f command) the way as in Sublime Text

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#107019]
In Sublime Text, when you do cmd+shift+f global search, the window opens in the bottom of the editor like so:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/6391776/93608198-a4b11480-f9ca-11ea-804f-97e476dbcd9b.png">

Then when you start a search, the results get opened in separate tab like so:

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/6391776/93608312-c3afa680-f9ca-11ea-8b69-88ed709964e9.png">

You get to see both the matches and also surrounding text. Then you can press return on a line to open the file in the editor.

In VSCode the same searches are forced to be done in the sidebar:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/6391776/93608455-eb9f0a00-f9ca-11ea-8949-9a7a551a970e.png">

They lose context of surrounding files. You can press cmd+return to open the results in a separate file like so:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/6391776/93608553-0a050580-f9cb-11ea-83da-4760ebe032c3.png">

But you can't press `return` to open the file where the line is found in the editor. Plus if I press cmd+shift+f again, the focus goes here:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/6391776/93608654-2608a700-f9cb-11ea-9337-59e586663b4a.png">

And not here:

![CleanShot 2020-09-18 at 16 22 34@2x](https://user-images.githubusercontent.com/6391776/93608676-2d2fb500-f9cb-11ea-8939-d4911bcfc033.png)

Is it possible to achieve the Sublime global text search workflow in VSCode?

**Comment by nikitavoloboev** [comment]
Perhaps I should create an issue for `Add ability to press return in search results` to go to file of the result?

**Comment by nikitavoloboev** [comment]
I opened the issue here https://github.com/microsoft/vscode/issues/107025

**Comment by nikitavoloboev** [comment]
> You can drag search to panel which is by default at the bottom

I don't get how to do this.

<img width="255" alt="image" src="https://user-images.githubusercontent.com/6391776/93614126-0a54cf00-f9d2-11ea-8653-0a6014e096fd.png">

What should I drag?

**Comment by nikitavoloboev** [comment]
Also added this in settings:

`  "search.searchEditor.defaultNumberOfContextLines": 2,`

But still search shows no context:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/6391776/93614330-47b95c80-f9d2-11ea-889e-2e278c071b4a.png">


I reran the search again.

**Comment by nikitavoloboev** [comment]
> If you need to focus input while cursor is somewhere in Search editor - Esc will do that.

What do you mean by `input` here. Also `escape` for me does nothing. I use vim extension so escape will go from insert to normal mode but in normal mode, escape does nothing. Perhaps it's a clash?

**Comment by nikitavoloboev** [comment]
> so Ctrl+Click or double click (by default) on Search results line performs navigation.

cmd+click does nothing. so is ctrl+click on VS Code insiders. Perhaps vim extension is blocking it, I'll check.

**Comment by JacksonKearl** [comment]
> cmd+click does nothing. so is ctrl+click on VS Code insiders. Perhaps vim extension is blocking it, I'll check.

It's whatever "go to definition" is mapped to. Peek definition, open definition to side, etc, all also work.

> What do you mean by input here. Also escape for me does nothing. I use vim extension so escape will go from insert to normal mode but in normal mode, escape does nothing. Perhaps it's a clash?

You can try searching "Search Editor: Focus Input" in command palette to see what the keybinding is.

>But still search shows no context:

Only editors will show context, the sidebar will never show context

**Comment by nikitavoloboev** [comment]
Is it possible to map `return` in sidebar global search to do what cmd+return does?

**Comment by nikitavoloboev** [comment]
As there is no point in actually pressing `return` here: 

<img width="207" alt="image" src="https://user-images.githubusercontent.com/6391776/93615693-045fed80-f9d4-11ea-8bca-88d11f27b490.png">

Since the results get updated live as you type and you can cmd+down-arrow to go to them.

**Comment by nikitavoloboev** [comment]
I'd rather map `return` to directly open the search results in the file. 

Also would be nice to be able to map `down arrow` to do same as `cmd-down-arrow` in the sidebar search as I never use multi line to do global searches and want to just use down arrow to start going through results in sidebar.

**Comment by IllusionMH** [comment]
> What should I drag?

Open bottom panel (usually Terminal, Problems etc. are there)

Drag search icon from Action bar on the side to bottom panel tabs row, you should see vertical line where it will be placed.

Other were answered - context is only for editor that you already showed, keybindings are provided for default (Windows) config, so if you use Vim extension - you might need to redefine keybindings.

As for Enter  - responded in separate issue - you need to map to existing action whatever you want

**Comment by JacksonKearl** [comment]
As @IllusionMH has said, almost all keybindings can be configured in the editor, you can read here for more info: https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by nrayburn-tech** [comment]
I don't think this is exactly what you are looking for, but if you name a file with the extension `.code-search`, it gives you a search editor.
Here is a screenshot of an example.

<img width="1154" alt="Example" src="https://user-images.githubusercontent.com/52075362/93659134-c8468000-fa07-11ea-8190-db8dd43ebb47.png">

**Comment by JacksonKearl** [comment]
@nrayburn-tech You can also run the command "Open Search Editor" :)

**Comment by JacksonKearl** [comment]
Also, I don't believe there are any open requests in this issue, going to close as question.
