### ISSUE TITLE
Add project name in terminal tab

### ISSUE THREAD

**Issue by heng1025** [microsoft/vscode#107096]
sometimes，i open workspace that contains lots of project,i can't switch terminal easily.

<img width="1355" alt="terminal" src="https://user-images.githubusercontent.com/17466991/93705475-47df6680-fb50-11ea-8955-5531d78e575b.png">

**Comment by gjsjohnmurray** [comment]
Did you find the `Terminal: Rename` command in Command Palette?

**Comment by heng1025** [comment]
yeah, i got it, thanks.
