### ISSUE TITLE
A problem with termnal output

### ISSUE THREAD

**Issue by mgcolossus** [microsoft/vscode#107072]
Issue Type: <b>Bug</b>

Hi, there is a printscreen of terminal https://ibb.co/vQDygcS

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.76GB (1.49GB free)|
|Process Argv|--crash-reporter-id 514c27ba-bb51-4298-966b-0120823a2060|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
All-Autocomplete|Ati|0.0.23
htmltagwrap|bra|0.0.7
vscode-eslint|dba|2.1.8
ecsstractor-port|diz|0.0.3
xml|Dot|2.5.1
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.6.0
code-runner|for|0.11.0
beautify|Hoo|1.5.0
vscode-github|Kni|0.30.3
class-extractor|kvx|1.0.4
vscode-language-babel|mgm|0.0.29
vscode-checkpoints|mic|1.3.1
easy-less|mrc|1.6.3
vscode-autoprefixer|mrm|3.0.1
vscode-language-pack-ru|MS-|1.49.1
python|ms-|2020.8.109390
vsliveshare|ms-|1.0.2740
debugger-for-chrome|msj|4.12.10
JavaScriptSnippets|nat|0.2.0
LiveServer|rit|5.6.1
vscode-multiclip|sle|0.1.5
sass-indented|syl|1.8.11
vscode-todo-list|thi|1.0.4
vscode-svg-previewer|vit|0.6.0
vscode-icons|vsc|11.0.0
quokka-vscode|Wal|1.0.318
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.8.7

(2 theme extensions excluded)

</details>

**Comment by rzhao271** [comment]
@mgcolossus the screenshot expired. Can you describe what the issue was?

**Comment by mgcolossus** [comment]
> @mgcolossus the screenshot expired. Can you describe what the issue was?

The issue concerned a text wrapping in a console. I haven't seen that problem recently so I think it has been fixed.
