### ISSUE TITLE
'Checking for quick fixes' takes extremely long

### ISSUE THREAD

**Issue by rkanjani** [microsoft/vscode#107045]
Issue Type: <b>Performance Issue</b>

It takes an extremely long time for 'Checking for quick fixes' to resolve, even if the function I'm trying to import is in a sibling file. It didn't used to take this long but as of recently it takes forever.

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.01GB free)|
|Process Argv|-psn_0_1544569|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    8	    98	 81048	code main
    2	    66	 81083	   gpu-process
    0	    16	 81087	   utility
    0	    82	 81088	   window (chat-helpers.ts — Teamspace-Web)
    0	    33	 81283	     extensionHost
    0	    16	 81292	       electron_node tsserver.js 
    1	    33	 81293	       electron_node tsserver.js 
    0	    16	 81297	         electron_node typingsInstaller.js typesMap.js 
    0	    16	 81387	       electron_node eslintServer.js 
    0	    16	 81452	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=81283
    0	    16	 81289	     watcherService
   85	    66	 81282	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (message-container.tsx — teams-modular-packages)
|  Window (chat-helpers.ts — Teamspace-Web)
|    Folder (teams-modular-packages): more than 21833 files
|      File types: json(9361) tsx(3303) ts(2982) graphql(618) md(460)
|                  snap(404) png(333) scss(171) yml(54) jpg(28)
|      Conf files: package.json(324) tsconfig.json(324) launch.json(1)
|                  settings.json(1) webpack.config.js(1) tslint.json(1)
|      Launch Configs: node(10) chrome
|    Folder (Teamspace-Web): more than 22358 files
|      File types: ts(3570) js(3421) map(2729) html(1979) scss(531) json(443)
|                  png(397) svg(351) dll(178) h(116)
|      Conf files: package.json(25) tsconfig.json(4) gulp.js(3) launch.json(2)
|                  tslint.json(2) sln(2) csproj(2) grunt.js(2)
|                  settings.json(1) tasks.json(1) webpack.config.js(1)
|      Launch Configs: node(28) chrome(2);
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.8.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.6.0
graphql-for-vscode|kum|1.15.3
python|ms-|2020.8.109390
remote-containers|ms-|0.140.1
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.10
markdown-preview-enhanced|shd|0.5.13
alphabetical-sorter|ue|2.0.1
material-theme|zhu|3.8.7

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Which language is this for?

**Comment by constmoon** [comment]
Same issue here.
