### ISSUE TITLE
copying forwarded port in embedder side doesn't work

### ISSUE THREAD

**Issue by fara-nak** [microsoft/vscode#107036]
- VSCode Version: 1.49.0
- OS Version: any

Steps to Reproduce:

1. from [https://github.com/codespaces] create a codespace and connect to it
2. try forwarding a port (any port)
3. on the Ui side, right click and choose "Copy Address"

expected: you should see an address like `https://<guid>-<port>.apps.<subdomain>.codespaces.githubusercontent.com/`

actual: you will see `127.0.0.1:<port>`

Does this issue occur when all extensions are disabled?: No

**Comment by fara-nak** [comment]
FYI @alexr00

**Comment by alexr00** [comment]
I debugged and found that the embedder is returning the wrong value here.

**Comment by fara-nak** [comment]
shouldn't we follow same logic as [openPortInBrowserAction ](https://github.com/microsoft/vscode/blob/e29d25303c6ad7fd3045f96353df33d259f5619a/src/vs/workbench/contrib/remote/browser/tunnelView.ts#LC862:~:text=export%20const%20ID%20%3D%20'remote.tunnel.open'%3B,%7D)for copy as well?
