### ISSUE TITLE
Workbench services should be all in /common/ layer

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1070]
There are a few services from the workbench that don't live in common but in browser which makes them dangerous to use in the API, for instance `IQuickOpenService` service is in common, consequently is `pluginHostQuickOpen`. In effect it might mean we drag a lot of code into the ext host process and in the worst case we have css-dependencies et al in there too. So, I wonder why these services and types don't live in common?

* `vs/workbench/services/quickopen/browser/quickOpenService`
* `vs/workbench/browser/parts/statusbar/statusbar`

**Comment by jrieken** [comment]
Also these two

* vs/workbench/services/untitled/browser/untitledEditorService
* vs/workbench/browser/parts/editor/untitledEditorModel

**Comment by jrieken** [comment]
@alexandrudima fyu

**Comment by bpasero** [comment]
Yeah, its a consequence of never finishing our componentized build. Some service interfaces still point to types defined in browser land (e.g. editorInput) because eventually there is a dependency to DOM things like builder or HTMLElement.

**Comment by bpasero** [comment]
<img width="343" alt="screen shot 2015-12-22 at 09 42 47" src="https://cloud.githubusercontent.com/assets/900690/11951333/66e23e62-a890-11e5-9b88-433f81752555.png">
