### ISSUE TITLE
Ability to close VSCode when done executing commands

### ISSUE THREAD

**Issue by HenrikHolmIT** [microsoft/vscode#107006]
VSCode is launched from an external process with a set of commands that needs to be run. 
When all commands have been run it would be awesome if there was a way for extension code to terminate the main window and close the VSCode process.

This is part of a build pipeline but VSCode is required to perform the compilation of the source code. It would be nice if extension could close VSCode on compile completion instead of having to signal the process that started VSCode to now be alloved to kill process.

**Comment by aeschli** [comment]
I believe an extension can already do that with the close command, no? command id 'workbench.action.closeWindow'

**Comment by HenrikHolmIT** [comment]
Works. Thanks.
