### ISSUE TITLE
Intellisense frequently in a broken state requiring a restart

### ISSUE THREAD

**Issue by patrick-scully-ef** [microsoft/vscode#107041]
Issue Type: <b>Bug</b>

This occurs randomly while editing. Currently in F#, adding properties to records doesn't update to intellisense and code that builds and is completely valid is flagged by VSCode as a 'Problem' and marked red. This can be really time consuming when trying to learn something new, and annoying in a known language. It requires closing and reopening VSCode to fix. This can easily happen multiple times per day. Other have noted similar issues. At this point I would take a button I have to repeatedly hit to refresh/fix intellisense after I made code edits just to get this working.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (15.43GB free)|
|Process Argv|--crash-reporter-id 49624887-d790-466f-81c2-8a414f14f172|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
gitlens|eam|10.2.2
prettier-vscode|esb|5.6.0
code-runner|for|0.11.0
kotlin|fwc|0.2.18
vscode-pull-request-github|Git|0.20.0
Ionide-fsharp|Ion|4.17.0
drools|jim|1.2.0
vscode-peacock|joh|3.8.0
chat|kar|0.35.0
Kotlin|mat|1.7.1
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
remote-wsl|ms-|0.44.5
vsliveshare|ms-|1.0.2740
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.10
gradle-language|nac|0.2.3
java|red|0.67.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2

</details>

**Comment by aeschli** [comment]
Can you file this against the extension that you use for F# ?
