### ISSUE TITLE
Async import 'windows-process-tree' can load even more lazy

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107028]
I see that `await import('windows-process-tree')` is called very early here:

https://github.com/microsoft/vscode/blob/9b50b84c4cdcadfea05c05a5adfbf5cf24a3bfd5/src/vs/workbench/contrib/terminal/electron-browser/windowsShellHelper.ts#L56-L56

Even though only used in some method later. Can we please move it where it is being used only to ensure we do not block startup?

**Comment by Tyriar** [comment]
Sure this can move it further down. It will only save ~5ms on Windows and only if the terminal is restored on start up.
