### ISSUE TITLE
git Missing or invalid credentials.

### ISSUE THREAD

**Issue by sadig2** [microsoft/vscode#107024]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 1.46.1
2. Ubuntu 20.04 LTS

Does this issue occur when all extensions are disabled?: Yes
![trr](https://user-images.githubusercontent.com/20337465/93612182-3e36f100-f9e0-11ea-9205-919c6a8110cf.jpg)

Vs code terminal simply ignored my credentials of the repository. It would not push to the github. I spend half an hour trying different solutions to the problem. Terminal of ubuntu helped.

**Comment by joaomoreno** [comment]
Can you try again, after disabling git terminal auth via the `git.terminalAuthentication` setting? Thanks.

**Comment by anacsousa1** [comment]
Hi @joaomoreno , I am having the same trouble that @sadig2 described.
What do you mean by "disabling git terminal via git.terminalAuthentication setting"? How may I do that?

**Comment by joaomoreno** [comment]
Open VS Code settings, search for `git.terminalAuthentication` and you'll find a checkbox to disable that feature.
