### ISSUE TITLE
VSCode tries to run ifconfig or ip fallback and fails

### ISSUE THREAD

**Issue by VisualDevelopment** [microsoft/vscode#107022]
Issue Type: <b>Bug</b>

1. Use something like Gentoo Linux
2. Open VSCode in terminal
3. You get something like
```
[main 2020-09-18T14:19:57.521Z] [uncaught exception in main]: Unable to retrieve mac address (Error: Command failed: /sbin/ifconfig -a || /sbin/ip link
/bin/sh: /sbin/ifconfig: No such file or directory
/bin/sh: /sbin/ip: No such file or directory
```
Possible fix: Don't hardcode the path to these :^)

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 5.8.8-gentoo

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 2012)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.78GB (0.56GB free)|
|Process Argv|--crash-reporter-id efa12459-a531-4c84-8533-bc258558576f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
cpptools|ms-|1.0.0
vsliveshare|ms-|1.0.2740
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/blob/92a30ed2650c31839a453bb088be9a4e7935a393/src/vs/base/node/macAddress.ts#L11
