### ISSUE TITLE
Show operator information on mouse-over

### ISSUE THREAD

**Issue by j-steinbach** [microsoft/vscode#107046]
As a beginner developer, I often download foreign code to help me understand features. Often the more experienced developers use [operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators) I do not know. It would be very helpful if the IDE would show me a short definition of that operator when I hover my mouse over it, similar to how it tells me what a function does.

**Comment by aeschli** [comment]
For which programming language do you want this?

**Comment by j-steinbach** [comment]
I believe every programming language has symbols/operators that are confusing for beginners. 

For example it would be nice to know what these [symbols](https://github.com/tonsky/FiraCode/blob/master/extras/ligatures.png) mean. Also there is the modulo (%) operator and the [ternary operator (?:)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/conditional-operator). There is definitely confusion about those - in Programming 101 we had a big poster on the wall that explained them.

Ideally I have code like ```var x = condition ? 12 : (int?)null; ``` and when I hover over ? or : it shows me a tooltip like "is this condition true ? yes : no". Or a more simple example: What does ```x += y``` do? Hover: "x = x + y".

**Comment by aeschli** [comment]
Each language support in VSCode is implemented independently  and has different ownersWe need an issue per language, I can assign the issue to the correct component.
So I you can narrow your request to the language that is most important to you, then I can proceed.

**Comment by j-steinbach** [comment]
Ah, good to know. [TypeScript](https://www.typescriptlang.org/) would be nice have.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
