### ISSUE TITLE
version 1.49.1 having the pause button greyed out with custom debugger extension

### ISSUE THREAD

**Issue by Weichengfang** [microsoft/vscode#107053]
Hi,
I have just noticed that the latest version 1.49.1 started to show the debugger pause button is greyed out in our custom debugger extension, when debugging session started. 
![image](https://user-images.githubusercontent.com/11495662/93656835-ad5c2600-fa70-11ea-8b5b-beb9c1bad105.png)

It can be revived when there is breakpoint hit once. 

Thanks
Weicheng

**Comment by Weichengfang** [comment]
To  add more information, this is a remote debugging extension using networking connected session.

**Comment by isidorn** [comment]
Good catch, I have pushed a fix for this.

**Comment by Weichengfang** [comment]
Many thanks, Isidor. I can confirm this is fixed in insider build v1.50.

**Comment by isidorn** [comment]
Thanks. Adding verified label.
