### ISSUE TITLE
VSCode starts debug mode during yarn install and causes yarn install to fail

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#107000]
- VSCode Version: 1.50.0-insider
- OS Version: Ubuntu 2-.04

Steps to Reproduce:

1. Run `yarn` in an npm project
2. VSCode starts and stops debug mode multiple times
3. yarn install fails

![install fails](https://user-images.githubusercontent.com/23744935/93589536-3a3dab80-f9ad-11ea-94cf-2190ce9466bc.gif)

Does this issue occur when all extensions are disabled?: Yes

Installation works without problems when not installing with the VSCode Terminal

**Comment by connor4312** [comment]
Thanks for the issue, this should be fixed in the next Insiders build. Until that happens you can get around this by setting `debug.javascript.autoAttachFilter` to `disabled`.
