### ISSUE TITLE
'Select for compare' and 'Compare with selected' work between two workspace

### ISSUE THREAD

**Issue by tanxn5** [microsoft/vscode#107027]
'Select for compare' and 'Compare with selected' work between two workspace.

**Comment by IllusionMH** [comment]
Just drag file from one window to editor area of another window - it will be available in Open editors (as external file).
Then use select for compare or compare with selected on this editor in Opened edtors panel.

Sharing "Select for compare" file between different windows would result in unexpected comparisons.

**Comment by tanxn5** [comment]
> Just drag file from one window to editor area of another window - it will be available in Open editors (as external file).
> Then use select for compare or compare with selected on this editor in Opened edtors panel.
> 
> Sharing "Select for compare" file between different windows would result in unexpected comparisons.

OK. Thanks.
