### ISSUE TITLE
Don't auto-download disabled extensions

### ISSUE THREAD

**Issue by mhatvan** [microsoft/vscode#107030]
I have a couple of extensions that I keep disabled until I need them again for certain projects. 

It can be that they stay disabled for a large amount of time, still they auto-update and take the users' bandwidth, which might be limited.

In my opinion, they should stay on older versions and update only when they get enabled again.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/76879
