### ISSUE TITLE
Extension host types should have an 'adopt/lift' method

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#10703]
We see issues with TypeScript treating interfaces and classes equal and extension writer run it this... We should help and accept data that looks OK and convert it into instances of our classes, ala

```
class CompletionItem {
 static adopt(item:CompletionItem) {
  if(item instanceof CompletionItem) {
     return item;
   } else if(item) {
     return new CompletionItem(item.label, ... more data...)
  }
 }
}
```

Instead of instanceof-checks we should first adopt and then check.

**Comment by jrieken** [comment]
fyi @DanTup

**Comment by DanTup** [comment]
👍 

This is one of those things that once you know the issue, you'll probably figure it out if something doesn't work again in future; but the first time you hit it's very confusing. A fix like this would likely cut down on a bunch of confusion/frustration and [questions being raised about it](https://github.com/Microsoft/vscode/issues/10665)! :)
