### ISSUE TITLE
console.log(json) in visual studio code have problem

### ISSUE THREAD

**Issue by answord** [Microsoft/vscode#10704]
- VSCode Version: 1.4.0
- OS Version: Window7 Ultimate 64bit

Steps to Reproduce:
```
const http = require('http');
var util = require('util');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World\n');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});

console.log("aaa");
console.log({"aa": "bb"});
console.log("bbb");
```

Run this code in visual studio code, the progress will exit without any exception. But in cmd node app run normal.

**Comment by weinand** [comment]
@answord what version of node are you using?

**Comment by answord** [comment]
@weinand sorry, I forgot it. node-v4.2.5-x64. 
and I found this problem no longer appear in v4.5.0

**Comment by weinand** [comment]
@answord yes, there was a problem with olde node version. Probably you can reproduce this even outside of VS Code if you run your app with the `--debug` option.
