### ISSUE TITLE
editor.formatOnType

### ISSUE THREAD

**Issue by AbdelrahmanHamdy1996** [microsoft/vscode#107095]
Issue Type: <b>Bug</b>

when i type python code auto-format feature -  Format the line after typing not working. you can access in setting editor.formatOnType.
note: the other format feature working.
* editor.formatOnSave " working"
* editor.formatOnSave "working" 

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 5.4.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (1.64GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id e8cdb1fb-f439-4bff-9ff0-964f3ab2d516|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
arepl|alm|1.0.24
markdown-emoji|bie|0.0.9
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.36.3
python-preview|don|0.0.4
xml|Dot|2.5.1
prettier-vscode|esb|5.6.0
code-runner|for|0.11.0
vscode-pull-request-github|Git|0.20.0
beautify|Hoo|1.5.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.8.109390
vscode-pylance|ms-|2020.9.5
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
vscode-github-issue-notebooks|ms-|0.0.51
autodocstring|njp|0.5.3
vscode-xml|red|0.13.0
vscode-yaml|red|0.11.0
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
markdown-all-in-one|yzh|3.3.0
vscode-proto3|zxh|0.4.2

</details>

**Comment by jrieken** [comment]
Likely because the python extension doesn't support format on type
