### ISSUE TITLE
Find-Replace with RegEx puts characters in wrong capture group

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#107052]
- VSCode Version: 1.50.0-insider  2020-09-18  403a6895f
- OS Version: Win 8.1

Steps to Reproduce:

1.  Create a text file with the following content
```
    v-bind:propNameToolong=""
    :propDameGameplayer=""
    :prop-jame=""
```
2. Start a Regex Find replace with
```
Find: ((?:v-bind)?:)([a-zA-Z0-9]+)([A-Z][a-z0-9]+)
Replace: $1$2@$3
```
3. The goal is to place a `@` before the last capital word
4. The result is
```
    v-bind:propNameToolo@ng=""
    :propDameGameplay@er=""
    :pr@op-jame=""
```
5. It looks like capture group `$3` is always the last 2 characters. It should be the last Capital word.
6. In `:prop` are no capitals at all, why does it match?

If I test on [regex101](https://regex101.com/r/Id3jxN/2) it looks good and when tested in the console of Google Chrome the group `$3` is recognised correct.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ChadMcCaffery** [comment]
RegEx matches are affected by the "Match Case" (`Aa`) option, so you'll need to enable that.

**Comment by ArturoDent** [comment]
Exactly as @Chad said, I had already commented on your SO answer to the same effect.

**Comment by rioj7** [comment]
Then I must be programming with regex more then using the Find-Replace with regex.

This means that the `i` flag is on by default and the checkbox to signal that is `off` by default.

```
Match_Case == not Ignore_Case
```

I will place a post-it on my monitor near the Find-Replace box.
