### ISSUE TITLE
Upgrading to 1.49.1 through the built-in process breaks some features

### ISSUE THREAD

**Issue by cs-altshift** [microsoft/vscode#107029]
Issue Type: <b>Bug</b>

After having updated VSCode through the built-in update process, git-lfs was reported as missing from my path and .csproj files from unity where not opened correctly.

But if I download the 1.49.1 version directly from the website and replace the app in my /Applications folder, everything works as expected.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.45GB free)|
|Process Argv|-psn_0_573580 --crash-reporter-id 00349874-3afd-40e8-9b60-5ec182ab8100|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
eppz-code|epp|1.2.52
prettier-vscode|esb|5.6.0
csharpextensions|jch|1.3.1
jiracode|alt|0.0.1
unity-code-snippets|kle|1.3.0
csharp|ms-|1.23.0
unity-tools|Tob|1.2.12
unity-debug|Uni|2.7.5

</details>

**Comment by joaomoreno** [comment]
I'm glad to know you are unblocked now. Not sure what could've caused that temporary situation.

**Comment by cs-altshift** [comment]
Sure, I've found a workaround but it is reproductible every single time. So there is definitely something wrong with the built-in upgrade process, probably related to execution rights.
