### ISSUE TITLE
Rename symbole issue when they are inside destructuring 

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#107069]
When renaming a symbol, Vscode will modify the references in the destructuring incorrectly for my usercase.
And will stop the propagation of other lower symbols.
![af3tfgq23v2469beaf](https://user-images.githubusercontent.com/24865815/93670826-4a689000-fa6c-11ea-8c5a-c884d8dc04c5.gif)

Do we have a options to avoid this type of behavior ? 
and fully propagate symbole renaming ?

---
example if we have this
```js
var A = {a:true}

function foo(){
   const {a} = A;
   var otherstuff = !!a;
};
```

and if renaming symbole `a` to `_a`

target result 
```js
var A = {_a:true}

function foo(){
   const {_a} = A;
   var otherstuff = !!_a;
};
```

actual vscode do this

```js
var A = {_a:true}

function foo(){
   const {_a: a} = A;
   var otherstuff = !!a;
};
```

Maybe add a options to change this behavior ? or do we have one ?

**Comment by IllusionMH** [comment]
Yes, there are
`javascript.preferences.renameShorthandProperties` and `typescript.preferences.renameShorthandProperties`.

See details in https://github.com/microsoft/TypeScript/issues/29238#issuecomment-494866713

**Comment by djmisterjon** [comment]
than you so much friend
