### ISSUE TITLE
VS Code accessing disk too often

### ISSUE THREAD

**Issue by adam-becker** [microsoft/vscode#107047]
- VSCode Version: 1.47.2
- OS Version: Arch Linux 5.8.9-arch2-1

Steps to Reproduce:

1. Open VS Code
2. Run `$ sudo iotop -obtqqq | grep code`
3. Click in and out of VS Code, or just generally use it a while.
4. On my system, I periodically see VS Code using 99.99% of the disk, which then causes `jbd2` to use a lot of disk committing the transactions. The UI is unusable while this happens.

Does this issue occur when all extensions are disabled?: Yes/No

Yes.

[iotop.log](https://github.com/microsoft/vscode/files/5248414/iotop.log)

**Comment by rzhao271** [comment]
@adam-becker is this happening whenever you're opening a file/folder for the first time? Every time you open a file?

**Comment by adam-becker** [comment]
It happens when I have code just sitting idle with absolutely nothing open. I can open code with the "Open empty window" option and do nothing else.

**Comment by Tyriar** [comment]
Does that tool give you any information about what files are being accessed? This might be persisting Chromium's user data periodically or something.

**Comment by adam-becker** [comment]
> Does that tool give you any information about what files are being accessed? This might be persisting Chromium's user data periodically or something.

I think the best I could do there is run code with `strace` but that would generate a ton of noise. Still worth a try though.
