### ISSUE TITLE
VS Code hangs and couldn't even be terminated. Needed to reboot my machine

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#10707]
- VSCode Version: 1.5 insider
- OS Version:

No steps. Here is what I could capture: 

- I exited VS Code but two processes stayed around
`"C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe"`
`"C:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe" --reporter-url=https://ticinocrashreporter.azurewebsites.net/crash --application-name=VSCode --v=1`

- trying to kill one of them reported on the first one:
 ![capture](https://cloud.githubusercontent.com/assets/1931590/17808798/79666cb2-6612-11e6-9ba6-b461f120f8cf.png)

- starting code again didn't work since it tried to reuse these two process. The start simply hung.

**Comment by dbaeumer** [comment]
@bpasero FYI. I will add additional information if I see it again.

**Comment by bpasero** [comment]
And then you can reopen.
