### ISSUE TITLE
Latest update consumes the memory a lot

### ISSUE THREAD

**Issue by chamodSamajith** [microsoft/vscode#107094]
Update 1.49.1:
![image](https://user-images.githubusercontent.com/52029051/93700598-2b353580-fb34-11ea-80f8-580dd6cb3b0e.png)

- VSCode Version:1.49.1
- OS Version: windows 10
-Core i5 - 10 the Gen
-Ram -8Gb DDR 4
Steps to Reproduce:

1.just open a program on vs code

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
