### ISSUE TITLE
Types aren't recognized until I open them in another tab

### ISSUE THREAD

**Issue by limonte** [microsoft/vscode#107061]
- VSCode Version: 1.49.0
- OS Version: Win 10

### Steps to Reproduce:

1. clone https://github.com/sweetalert2/sweetalert2-parcel-demo
2. `yarn install`
3. open `app.ts`

### Current behavior

![image](https://user-images.githubusercontent.com/6059356/93664942-5576ec80-fa7b-11ea-964a-51e65f27f949.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/6059356/93665556-0e3f2a80-fa80-11ea-84f4-a6f9a0022eeb.png)

### The WEIRD part

As soon as I open `node_modules/sweetalert2/sweetalert2.d.ts` in another tab it works as expected:

![4wdtrUml6U](https://user-images.githubusercontent.com/6059356/93665612-4fcfd580-fa80-11ea-89c7-d873ea8e571b.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
What if you remove the `.js` in the import?

**Comment by limonte** [comment]
> 
> 
> What if you remove the `.js` in the import?

Same.

**Comment by limonte** [comment]
@mjbvz small detail to ad here (it might help): when I close `node_modules/sweetalert2/sweetalert2.d.ts` the unexpected behavior is starting again and `Swal` isn't recognized.

**Comment by limonte** [comment]
From https://github.com/sweetalert2/sweetalert2/issues/2056

> I think it may be caused by VSCode not loading the data tag file `sweetalert2.d.ts`, but Javascript also clearly stipulates that `Swal` is a class and a local file, which makes no sense.

**Comment by limonte** [comment]
From https://github.com/sweetalert2/sweetalert2/issues/2056#issuecomment-701328165

> Another proof that it's the VS Code issue is that in WebStorm all works as expected:
> 
> ![image](https://user-images.githubusercontent.com/6059356/94679092-33f1ec80-0328-11eb-9e88-d9cf9b826d13.png)

**Comment by limonte** [comment]
`tsconfig.json` was missing in that project:

```json
{
  "include": [
    "app.ts",
    "node_modules/sweetalert2/sweetalert2.d.ts"
  ]
}
```

https://github.com/sweetalert2/sweetalert2-parcel-demo/commit/ea7846d216fe2eb152e0b98df4dc059f200ba765
