### ISSUE TITLE
border-radius (css) type error

### ISSUE THREAD

**Issue by criiz8** [microsoft/vscode#107050]
Issue Type: <b>Bug</b>

When you see the border-radius (css) description, it says "radii" instead of "radio". Its minor but I think it should be fixed.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon 200GE with Radeon Vega Graphics      (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.95GB (1.74GB free)|
|Process Argv|C:\Users\crist\Downloads\yo\projects\walmart\index.html --crash-reporter-id e9929d08-bd7a-4749-8722-94662a4d431f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.6.0
LiveServer|rit|5.6.1
sonarlint-vscode|Son|1.17.0

</details>

**Comment by gjsjohnmurray** [comment]
The plural of "radius" IS "radii"

**Comment by criiz8** [comment]
Oh, i should learn more English. Sorry
