### ISSUE TITLE
Add ability to press return in search results

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#107025]
If I did a global search (cmd+shift+f), then pressed cmd+return to see the results in the file. I'd love to be able to press return when I am hovering some line to open the file where the line is. Currently I have to double click on the line (not keyboard friendly).

<img width="357" alt="image" src="https://user-images.githubusercontent.com/6391776/93613093-b0073e80-f9d0-11ea-8330-6b21fef1e323.png">

**Comment by IllusionMH** [comment]
Looks like you can already use existing `editor.action.goToDeclaration` with proper context `inSearchEditor` to achieve this

```json
{
    "key": "enter",
    "command": "editor.action.goToDeclaration",
    "when": "inSearchEditor"
}
```

**Comment by nikitavoloboev** [comment]
Amazing. Thx

**Comment by nikitavoloboev** [comment]
Now it also triggers when I am trying to do a search inside the file:

<img width="218" alt="image" src="https://user-images.githubusercontent.com/6391776/93617475-4ee26980-f9d6-11ea-821e-1f74165804c4.png">

Is it possible to make it work only when the search is done?

**Comment by nikitavoloboev** [comment]
I guess I have to extend the `when` clause to also consider only in the case of when `inFileSearch` is not open?

**Comment by IllusionMH** [comment]
Are you doing search inside of Search editor? 
Because I haven't problems with search widget in regular files.

Probably `"when": "inSearchEditor && editorTextFocus"` should do the trick.

@JacksonKearl do you know what `when` is best suited here? Docs don't even have `inSearchEditor`

**Comment by JacksonKearl** [comment]
`inSearchEditor && editorTextFocus` seems good to me. Good point about the missing docs, made a new issue to track.

**Comment by nikitavoloboev** [comment]
It worked, thanks all ❤️
