### ISSUE TITLE
Syntax highlight coloring occuring with non specified colors.

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#107035]
Operating System: Ubuntu 20.04
Visual Studio Code version: 1.49.0

I am working on a color theme, and I am observing some inexplicable editor background highlighting going on.

I have implemented a blank color theme extension. This extension has no colors defined for anything other than text forground and text background. It should be a two color theme.

But when I place the caret on any symbol name, there is a dark blue/green background highlight behind the declaration of that symbol, and a grey background drawn behind all references to that symbol.

![weird_highlighting](https://user-images.githubusercontent.com/12876404/93548926-e2ac2b00-f92d-11ea-972c-9f53a5f2ae4c.jpg)

The expected behaviour is that no coloring would be occuring unless that color is specified in my color theme.

This occurs in a Java source file, with the Java Extension by Redhat enabled.

**Comment by aeschli** [comment]
@safield what you see is the word highlight color that is set for all occurrences of the current symbol at the position. You need to change the following colors in your theme
		"editor.wordHighlightBackground": "#ff0000" // for normal occurrences
		"editor.wordHighlightStrongBackground": "#ff00ff" // for occurrences that are write accesses

That's in the `colors` section of your color theme. See https://code.visualstudio.com/api/extension-guides/color-theme#create-a-new-color-theme
