### ISSUE TITLE
A second instance of Code is already running as administrator

### ISSUE THREAD

**Issue by pmahend1** [microsoft/vscode#107014]
- VSCode Version: 1.49.0 and previous as well
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open command prompt as Admin
2. Open VSCode for a folder **foo** 
3. Go to any folder other than **foo** 
4. Right click on a file and select Open with VSCode 

![image](https://user-images.githubusercontent.com/21352870/93602630-e1f8b080-f990-11ea-856b-4e727369c577.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by pmahend1** [comment]
@bpasero @aechan what is this issue duplicate of? Sorry, I am finding hard time finding it.

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.

**Comment by pmahend1** [comment]
@bpasero Ok. The Bot did not put reference issue .
clicking label doesnt return anything. Could you please share the issue id or link?
