### ISSUE TITLE
Git actions doesn't auto reload git explorer section

### ISSUE THREAD

**Issue by induratized** [microsoft/vscode#107009]
Issue Type: <b>Bug</b>

Prior to update to 1.49 any git action like `git stash` used to auto reload/sync Git explorer section, but after update i have to manually click the reload icon for the changes to reflect in the git explorer section

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|-psn_0_5653860 --crash-reporter-id 1b654aa6-c989-4e2c-b14d-a372c2ec3eb5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
dart-code|Dar|3.14.1
vscode-eslint|dba|2.1.8
vscode-dash|dee|2.4.0
gitlens|eam|10.2.2
vscode-pull-request-github|Git|0.20.0
go|gol|0.16.2
python|ms-|2020.8.109390
cpptools|ms-|1.0.0
vsliveshare|ms-|1.0.2740
material-icon-theme|PKi|4.3.0
java|red|0.67.0
vscode-xml|red|0.13.0
vscode-yaml|red|0.10.1
code-settings-sync|Sha|3.4.3
vscode-checkstyle|she|1.3.3
sonarlint-vscode|Son|1.17.0
rewrap|stk|1.13.0
svelte-vscode|sve|101.14.0
vscode-lldb|vad|1.5.3
vscodeintellicode|Vis|1.2.10
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-webhint|web|1.5.8
material-theme|zhu|3.8.7

(9 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Nothing really changed in 1.49 regarding that, afaik. What's your git version? Does `Git: Show Git Output` show any details?

**Comment by SharakPL** [comment]
I've also noticed some weird behaviour related to explorer and git. Little different but probably related. Lately it stopped showing colors and badges if a folder has content changed in any way. Now most of the time you have to click on specific folder and reveal it's changed content to have badges and colors updated:

![git-explorer](https://user-images.githubusercontent.com/5007456/94416351-06b60a80-017f-11eb-8cb9-f9bf73079d83.gif)

Maybe Windows it's at fault here (2004 or one of later patches), because now I have to hit F5 on my desktop to reveal any new files there. In the past they were shown right away.

I'm using git 2.28.0.windows.1

**Comment by joaomoreno** [comment]
@SharakPL Please file a separate issue, since it's obviously not the same problem.

@induratized Let me know if you have more details.

**Comment by SharakPL** [comment]
@joaomoreno what makes you so sure it's not the same? It's all about updating git changes in explorer and it all started around the same time. I honestly think there's no point in creating another issue for this just to have it closed later   with follow-up back in this one. Please, confirm you want separate issue for this.

**Comment by joaomoreno** [comment]
The user says:

> after update i have to manually click the reload icon for the changes to reflect in the git explorer section

You show that the SCM viewlet already knows about the changes but you

> have to click on specific folder and reveal it's changed content to have badges and colors updated:

So yeah. It's a separate issue.

**Comment by induratized** [comment]
> Nothing really changed in 1.49 regarding that, afaik. What's your git version? Does `Git: Show Git Output` show any details?

git version - `2.21.0`

Yes , Git: Show Git Output does show outputs

I have updated VS to v1.49.3 and when I `git pull` from VS terminal it again didn't automatically update the git info in bottom left of the status bar, but after around 10-15 seconds it did sync fine. 

May be this is an issue of sync speed. Earlier it use to take no more than a couple seconds.

**Comment by joaomoreno** [comment]
We also didn't change the sync speed. Maybe you're just hitting the ugly debounce idle window. Does this reproduce 100% of the time, or just sometimes?

**Comment by induratized** [comment]
@joaomoreno right now it is 100% of the time. What info do you need to debug this? I just did a merge and there were merge conflict from terminal and it took 10+ seconds to show in the Git explorer

**Comment by joaomoreno** [comment]
I'd love to see how fast you get file events. Please go through the following steps:

1. Run `Git: Set Log Level...` and choose `Trace`
2. Run `Git: Show Git Output`
3. Outside of VS Code, touch a file in the repo.
4. Focus VS Code and wait until the SCM view refreshes
4. Paste the whole output here

**Comment by induratized** [comment]
> I'd love to see how fast you get file events. Please go through the following steps:
> 
> 1. Run `Git: Set Log Level...` and choose `Trace`
> 2. Run `Git: Show Git Output`
> 3. Outside of VS Code, touch a file in the repo.
> 4. Focus VS Code and wait until the SCM view refreshes
> 5. Paste the whole output here

Please find the desired output below
```
> git rev-parse <branch_name>
> git rev-parse --symbolic-full-name <branch_name>@{u}
> git rev-list --left-right <branch_name>...refs/remotes/origin/<branch_name>
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
```

in `v1.50.1` it works fine, Git explorer is now syncing as before and fast.  
VSCode version info below
```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

Thanks @joaomoreno . Let me know if you need more info
