### ISSUE TITLE
Extended `#region` support (outline, refactor region name)

### ISSUE THREAD

**Issue by TheGrimSilence** [microsoft/vscode#107084]
Currently regions, denoted by `//#region` &| `//region`, while supported are still lacking in "full support". This definition varies from dev to dev, but I think in more general terms we should be looking at at least "Rename Symbol" or `F2` support and `outline`/`breadcrumb` support. This would allow larger `region`ed code to be viewed within `outline`s. Allowing collapsibility just like the others (`method`, `class`, etc...) would also permit less scrolling.

## "Rename Symbol"

This one should really be determined by the existence of `#region <name>`. If the region header and footer both have the same name, then rename both from either the footer or header.

---

This should really just expand upon https://github.com/microsoft/vscode/issues/51364

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Afeature-request+label%3Aoutline
