### ISSUE TITLE
Terminal Should Retain Focus When Switching Out/In VSCode Window 

### ISSUE THREAD

**Issue by donCarlosOne** [microsoft/vscode#107066]
I'm not sure sure if this is a bug or a feature request.  In any event, I'll side with feature request.

When switching windows and views, in MacOS, and then returning to VSCode, the Editor panel always gets focus, regardless of where focus was before switching out of VSCode.  I often work in the Terminal panel when testing my server and browser code, and often find myself typing bash commands into my code, rather than the Terminal panel that I was in only moments before (and then I must carefully remove what I just typed).  I really think that VSCode should preserve the focus of the panel until the user explicitly changes it.

**Comment by rzhao271** [comment]
Hi @donCarlosOne, how are you switching your windows and views? Are you clicking the editor part of the window to switch back to VS Code?

I cannot reproduce this issue on Windows.

**Comment by Tyriar** [comment]
I cannot repro on mac either, you are probably after this setting:

```
"window.clickThroughInactive": false
```
