### ISSUE TITLE
'yarn add' starts debugging

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#107051]
Issue Type: <b>Bug</b>

**Repro**
1. In the VS Code repo
1. In the intergrated terminal, run `yarn add typescript@next`

**Bug**
The debugger launches

VS Code version: Code - Insiders 1.50.0-insider (403a6895f401c397933ec5c4f7d89432a33509b6, 2020-09-18T07:11:53.303Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.24GB free)|
|Process Argv|-psn_0_40187473 --crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|13%|
</details>

**Comment by connor4312** [comment]
Does it start as soon as you start yarn? If so, what's `which yarn`?

**Comment by mjbvz** [comment]
Yes debugging starts even for `yarn --version`. 

I'm on yarn `1.21.1`

**Comment by connor4312** [comment]
Okay. Adding `!**/yarn` to your `debug.javascript.autoAttachSmartPattern` should fix this. One more default to add.
