### ISSUE TITLE
Every click in a file opens a preview window in my web browser

### ISSUE THREAD

**Issue by chris1248** [microsoft/vscode#107042]
Issue Type: <b>Bug</b>

Every time I click in a file window in VS Code, it annoyingly opens up a new browser window and tries to display the damn markup.

Problem is, VSCode is doing this for every single file, not just *.md files. 

This is highly annoying and I have tried to turn it off with no success.

This has been happening ever since I updated to the latest version of visual studio code 1.48.2. i.e.
```
Version: 1.48.2 (system setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:14:14.576Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT ia32 10.0.19041
```

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:14:14.576Z)
OS version: Windows_NT ia32 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz (12 x 3458)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.98GB (21.29GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-instant-markdown|dba|1.4.5
xml|Dot|2.5.1
vscode-edit-csv|jan|0.4.2
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
python|ms-|2020.8.109390
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.0
sqltools|mtx|0.23.0
cmake|twx|0.0.17

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen if you reload with all extensions disabled?

**Comment by chris1248** [comment]
How do I disable all extensions? Oh nevermind I see now (one by one).
Ok, that did it: 

Found the offending extension: 'Instant Markdown version 1.4.5`

It's gonno! see ya later 'Instant Markdown'!!
