### ISSUE TITLE
VSCode crashes when launching from --verbose mode in WSL

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#107062]
Version: 1.50.0-insider (system setup)
Commit: cca20eba8974b1d6b6a9b71bf4e60a29c8f26648
Date: 2020-09-12T01:04:21.398Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

## Crashing
1. in WSL launch code-insiders --verbose (also happens with --no-extensions)
2. once code has launched, try clicking outside the window then back in
3. crash

## Working 
1. in WSL launch code-insiders
2. once code has launched, try clicking outside the window then back in
3. doesn't crash

I have https://github.com/boa-dev/boa open in the gif, sometimes it doesn't crash if i open no project so it could be an extension.

## non verbose
![nonVerbose](https://user-images.githubusercontent.com/936006/93666110-5b68cf80-fa73-11ea-9a19-01a0fbb3114d.gif)

Here VSCode is fine until i click out and back in again.

## verbose
![verbose](https://user-images.githubusercontent.com/936006/93666113-60c61a00-fa73-11ea-993c-fd90daf72128.gif)

## Logs
```
➜  workspace code-insiders --verbose
Invoking: /mnt/c/Program Files/Microsoft VS Code Insiders/Code - Insiders.exe resources/app/out/cli.js --verbose --remote=wsl+Ubuntu-20.04 in /mnt/c/Program Files/Microsoft VS Code Insiders
```

**Comment by aeschli** [comment]
I can't reproduce. Can you try to get more information about the crash? https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#windows

Does this also happens when you run from the Windows prompt:
`code-insiders --verbose --remote=wsl+Ubuntu-20.04`

**Comment by jasonwilliams** [comment]
> Does this also happens when you run from the Windows prompt:
> `code-insiders --verbose --remote=wsl+Ubuntu-20.04`

Yes i can reproduce it with and without the remote argument

> I can't reproduce. Can you try to get more information about the crash? https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#windows

I've got it running but it doesn't generate a .dmp file, code just hangs forever and i need to close the task in Task manager.

**Comment by jasonwilliams** [comment]
@aeschli  I've managed to get a dump of that none responding process but its a large file, so i can't attach it here

**Comment by aeschli** [comment]
@jasonwilliams Can you send me the dump file by mail or share it in the cloud?

**Comment by jasonwilliams** [comment]
Sent

**Comment by deepak1556** [comment]
@jasonwilliams can you also launch with `code-insiders --verbose --crash-reporter-directory <some-absolute-path>` and attach the generated minidump files from `<some-absolute-path>`

**Comment by jasonwilliams** [comment]
@deepak1556 doesn't look like that's supported

```
code-insiders --verbose --crash-reporter-directory /home/jasew
Ignoring option crash-reporter-directory: not supported for code-insiders.
```

```
~ code --verbose --crash-reporter-directory /home/jasew
Migrating .vscode-remote to .vscode-server...
Updating VS Code Server to version 58bb7b2331731bf72587010e943852e13e6fd3cf
Removing previous installation...
Installing VS Code Server for x64 (58bb7b2331731bf72587010e943852e13e6fd3cf)
Downloading: 100%
Unpacking: 100%
Unpacked 2341 files and folders to /home/jasew/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf.
Ignoring option crash-reporter-directory: not supported for code.
```

**Comment by jasonwilliams** [comment]
@aeschli was the dump useful?

**Comment by aeschli** [comment]
I didn't get anything useful out of it. Sending the dump to @deepak1556, he's more experienced.

**Comment by aeschli** [comment]
@jasonwilliams You mentione dyou can reproduce it when starting on the Windows side as well. 
Can you start from a  Windows command prompt:
`code-insiders --verbose --remote=wsl+Ubuntu-20.04 --crash-reporter-directory=c:\vscode-crashes`

**Comment by jasonwilliams** [comment]
@aeschli sorry i mis-read your earlier comment, i thought you meant does this also happen when you pass in the --remote argument. It only happens when launching from WSL, from windows it's fine

**Comment by jasonwilliams** [comment]
Further investigation:
VSCode v1.58.0-insider (system setup)
Rust Analyzer v0.2.637

I started to narrow this down to only-happening-on-rust-projects, then I looked at some extensions.
On further investigation it looks like the issue could be Rust Analyzer? I notice the crash happens once that kicks in. Not sure how its able to crash the whole of VSCode, ive not seen an extension do that but if you install that it should be reproducible.

https://user-images.githubusercontent.com/936006/122100929-a7328480-ce0b-11eb-8c2d-c8bf47ebb48c.mp4

Heads up to @matklad

**Comment by aeschli** [comment]
Please file this against the Rust Analyzer analyzer then. Very plausible that the freeze and core dump are caused by a native call in the extension.
How `--verbose` has an impact is unclear to be. VSCode will log more to the console, maybe the Rust Analyzer also does a lot of logging?

**Comment by matklad** [comment]
rust-analyzer vscode extension doesn't do any native calls. It more-or-less only calls into https://github.com/MIcrosoft/language-server-protocol/ to interact with a native binary via stdio-based IPC.
