### ISSUE TITLE
code ignores special character ~ when opening files

### ISSUE THREAD

**Issue by mladedav** [microsoft/vscode#107032]
- VSCode Version: 1.43.2 0ba0ca52957102ca3527cf479571617f0de6ed50 x64
- OS Version: Windows 10

Steps to Reproduce:

1. run `code ~/foobar`
2. observe that the file at $HOME/foobar does not exist but file at $(pwd)/~/foobar does

I tried WSL and it works as expected, well because bash does this. Powershell also does this expansion on several places but is also largely inconsistent. It may be argued that this should not be vs code's responsibility when it can't also know if people meant home directory or really a directory called `~` (although prefixing with `./` would solve this) so if this gets closed I would understand.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kieferrm** [comment]
Agreed. This is OS specific functionality, we can't "mess" with that.
