### ISSUE TITLE
Feature Request: Customisable Buttons

### ISSUE THREAD

**Issue by MeirionHughes** [Microsoft/vscode#10709]
Support adding custom buttons that execute a terminal command. 
Support custom button context options (states that need to be true to be enabled). 
Support downloading icons for said custom button from Noun Project.

**Comment by Tyriar** [comment]
The team is very sensitive to adding new Chrome to the UI. Currently you can't add buttons anywhere within VS Code and I believe that is an intentional design decision.

Coming soon to the terminal however is the ability to send text to a terminal, which will enable extensions to create custom commands, see https://github.com/Tyriar/vscode-terminal-api-example.

**Comment by MeirionHughes** [comment]
Not the chrome/electron menu; the left-side:  

![buttons](https://cloud.githubusercontent.com/assets/3584509/17903578/f6a061fc-6963-11e6-8381-fc7bd5b6ccf9.png)

That space is begging to be filled with user-buttons. I really do not want to have to type terminal commands I regularly use and almost every other UI out there allows at least some customization. 

For instance: I could have a button that releases my project; or another one that pushes documentation... but that doesn't matter, it empowers users to customize their UI experience. 

I think this has been closed prematurely if I'm honest.

**Comment by Tyriar** [comment]
@MeirionHughes this is the issue for allowing extensions to add buttons to that section of the UI (the activity bar) https://github.com/Microsoft/vscode/issues/8511

We prefer to defer functionality like this to extensions and #8511 combined with the terminal API (#9957). In the meantime I would recommend playing with [tasks](https://code.visualstudio.com/docs/editor/tasks) as a way to quickly launch custom tasks from the command palette (<kbd>F1</kbd>), you can also build custom commands in an extension and then attach it to a keybinding.

**Comment by MeirionHughes** [comment]
Why limit this to extensions though? 

I would think the above config example would make this easy for users to add their own without the need to jump through hoops. Its also applicable for both user and workplace setting files so you can have per-project button setups.  

* Its not hard to implement; 
   * icons from a icon-font might be easier? 
* It doesn't affect the UI layout, 
* It doesn't affect the default UI of normal users who choose not to use it, 
* It allows users to (easily) customize their UI experience 
  * how they want to use it, not how you want them to us it. 

I love vs-code, but right from the get-go I've wondered why there hasn't been an option to add user-configured buttons. Hopefully in the future you'll change your mind.

**Comment by Tyriar** [comment]
Why is the activity bar locked down?

- To keep the editor feeling "light-weight"
  - We don't want to clutter the UI
  - Opening the flood gates could have performance implications
- Keep the complexity of code down
- Extensions can't make much meaningful UI that would warrant allowing access to the buttons, it has been designed as a place to launch viewlets, not arbitrary commands

Why would this be extensions only if ever did allow it

- Configuring this via settings is not particularly discoverable
- Extensions allow devs to put together polished experiences
- Only extensions would be able to launch the sort of UI that the buttons are designed for
- Keep the complexity of code down

Also the sort of user interaction you're after is typically done within vscode currently via commands, keybindings and tasks which you can do already. Having said all this, I don't own this area but I believe I'm echoing the team's feelings fairly accurately.

I highly recommend looking into [tasks](https://code.visualstudio.com/docs/editor/tasks) as they allow you to do exactly what you want, just using a keybinding or the command pallete and not a physical button. The command palette (<kbd>F1</kbd>) is one of the most powerful features of vscode as you can pretty much call into everything the editor can do.

**Comment by MeirionHughes** [comment]
To be fair when #8511 is done I can make an extension to do exactly what I propose (read a config from .vscode and add activity buttons) anyway.

**Comment by AlanWalk** [comment]
I want to add a svn extension just like git, activityBar is better than terminal or command.

**Comment by marosca** [comment]
I want button in the activity bar!
