### ISSUE TITLE
Issue with VSCode extensions when behind SSL re-encryption proxy

### ISSUE THREAD

**Issue by Glober777** [Microsoft/vscode#10702]
Hi!

I'm observing issues working with VSCode extensions when behind a proxy that re-encrypts SSL traffic. Searching for an extension (i.e. using PowerShell as a keyword or anything else) doesn't return any results. Additionally, if I press the "Update" button for either of the existing extensions, an error message saying **unable to get local issuer certificate** pop up. I suspect that it is caused by the fact that the certificate that's used by the proxy to re-encrypt the traffic is not trusted by the crypto (OpenSSL?) that's being used by VSCode. If that's the case, there seem to be few ways to resolve it:
1. Add the URL that VSCode uses to download extensions from to the exclusion list on the proxy to avoid re-encryption. I couldn't find that URL in the documentation. Any idea where this can be obtained? Would be nice if that error message would include the URL as well.
2. Provide a mechanism that would allow adding self-signed (based on an approval) certificates to the trust store relied by VSCode. 

Here's the version details:
- Version 1.4.0
- Commit 6276dcb0ae497766056b4c09ea75be1d76a8b679
- Date 2016-08-04T16:45:31.680Z
- Shell 0.37.6
- Renderer 49.0.2623.75
- Node 5.10.0
- OS Version: Windows 10 Anniversary Edition

Thanks,
Glober777

**Comment by joaomoreno** [comment]
Have you tried setting the `http.proxyStrictSSL` setting to `false`?

**Comment by Glober777** [comment]
No, I haven't because that would mean reducing security, which is something I wanted to avoid. 

Actually, working with our firewall admins we were able to identify that if we exclude the following domains (from being re-encrypted) the issue goes away:
visualstudio.com
vsassets.io

I hope that would help others.

**Comment by joaomoreno** [comment]
Thank you.
