### ISSUE TITLE
A specific extension cannot be found

### ISSUE THREAD

**Issue by vojtechkral** [microsoft/vscode#107034]
Issue Type: <b>Bug</b>

I can't seem to be able to install the extension [File Browser](https://marketplace.visualstudio.com/items?itemName=bodil.file-browser) from VSCode.

When I enter the extension name or ID into the search field in VSCode, it will never be included in the list of results. Using `ext install bodil.file-browser` as instructed on the marketplace leads to the same result.

I had to download the VSIX and install from that - that does work, there seems to be no issue with using the extension. It does show up in my *installed extensions* list, but still won't show up in the online search.

All other extensions can be found just as normal as far as I can tell - I wasn't able to find any other extension where this would occur as well so far.

I have tried both in regular session as well as with extensions disabled, there's no difference.

VS Code version: VSCodium 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T19:42:46.044Z)
OS version: Linux x64 5.8.8-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 2292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|31.05GB (3.66GB free)|
|Process Argv|--unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by vojtechkral** [comment]
<img width="200" alt="vscode-filebrowser-bug" src="https://user-images.githubusercontent.com/424891/93623857-ac2ee880-f9df-11ea-9e46-c3fb8da4b9df.png">

**Comment by IllusionMH** [comment]
Strange, tried insiders (user install) and stable (zip) on Windows and it works as expected - single result
![image](https://user-images.githubusercontent.com/1312662/93632823-a5f83680-f9f6-11ea-8948-7960afbf9a20.png)

> VS Code version: VSCodium 1.49.0

Most likely problem is that VSCodium doesn't use marketplace and extension is not published where VSCodium is looking. I guess in that case you can as extension author to publish it to 2 places.

**Comment by sandy081** [comment]
Please file an issue against VSCodium.
