### ISSUE TITLE
JSON Language Feautures: A request has failed.

### ISSUE THREAD

**Issue by Salil03** [microsoft/vscode#107139]
We have written the needed data into your clip
Issue Type: <b>Bug</b>

Whenever I open vscode I get the following error:

![image](https://user-images.githubusercontent.com/32109637/93735379-5aae7580-fbfa-11ea-8d77-c4e83c346a0d.png)

This error has suddenly appeared since yesterday. I tried a full uninstall and reinstall but still couldn't resolve it. Also around this time, https://github.com/microsoft/vscode-cpptools/issues/6169 started appearing too.

Output windows shows:

```
[Error - 11:02:34 am] Connection to server is erroring. Shutting down server.
[Error - 11:02:34 am] Connection to server is erroring. Shutting down server.
[Error - 11:02:34 am] Connection to server is erroring. Shutting down server.

```
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.29GB free)|
|Process Argv|--crash-reporter-id 9375b8f1-36c1-4e77-b7e9-5242e30f159a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
acmx|mar|0.3.5

</details>

**Comment by aeschli** [comment]
Can you set `"json.trace.server": "messages",` and check if there's anything interesting in the Output > JSON Language Server log?

**Comment by Salil03** [comment]
I get this in the output window:

```
[Trace - 3:14:43 pm] Sending request 'initialize - (0)'.
[Error - 3:14:43 pm] Connection to server is erroring. Shutting down server.
[Error - 3:14:43 pm] Connection to server is erroring. Shutting down server.
[Trace - 3:14:43 pm] Sending request 'shutdown - (1)'.
[Error - 3:14:43 pm] Connection to server is erroring. Shutting down server.

```
Don't know if it is of much help.

**Comment by Salil03** [comment]
This issue went away on its own in 2 days. Idk why. I will keep this open for one more day if the issue resurfaces. Else, I will close it tomorrow.
