### ISSUE TITLE
VS Code does not update properly

### ISSUE THREAD

**Issue by Frzjck** [microsoft/vscode#107125]
Issue Type: <b>Bug</b>

Greetings,
VS seems to be updating properly to lastest (august 2020 1.49) version, but after reopening the program rollsback to March 2020 (version 1.44) for an unknown reason. 

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor              (12 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.24GB free)|
|Process Argv|--crash-reporter-id d57f1689-3537-4beb-8a11-6776a8628662|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1001.0
path-intellisense|chr|2.3.0
jshint|dba|0.10.21
vscode-eslint|dba|2.1.8
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.6.0
terminal|for|0.0.10
vscode-angular2-emmet|jak|2.0.3
vscode-JS-CSS-HTML-formatter|lon|0.2.3
Angular-BeastCode|Mik|10.0.3
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.0
vscode-typescript-tslint-plugin|ms-|1.2.3
angular2-inline|nat|0.0.17
material-icon-theme|PKi|4.3.0
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Is the issue fixed if you completely uninstall and reinstall VS Code?

**Comment by Frzjck** [comment]
Is there a way to reinstall it without loosing all extensions and configurations?

**Comment by joaomoreno** [comment]
Yes, uninstalling won't remove extensions or configurations.
