### ISSUE TITLE
Cannot Uninstall VSCode

### ISSUE THREAD

**Issue by snapzilla** [microsoft/vscode#107133]
Issue Type: <b>Bug</b>

Open Apps in Windows Settings
VDCode does not appear in the list of Apps

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (23.87GB free)|
|Process Argv|--crash-reporter-id a89cc710-71a3-4a63-8896-f6416a812290|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.0
vsc-material-theme|Equ|33.0.0
python|ms-|2020.8.109390
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.3.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Did you check in the Control Panel?

**Comment by snapzilla** [comment]
I did thanks and I found it under Microsoft Visual Studio Code.  I'd been
looking in the C's for Code and the V's for Visual.
