### ISSUE TITLE
InputProblem

### ISSUE THREAD

**Issue by rrushtw** [microsoft/vscode#107198]
Issue Type: <b>Bug</b>

My environment: Window10, Visual Studio Code version 1.49.1
I am facing a problem that continuously happen.
While inputing characters, it somehow duplicate the characters which I input.
For instance, I input 'A' and it response 'AA' to me especially inputing traditional Chinese.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (10.03GB free)|
|Process Argv|--crash-reporter-id 80d2b7ce-679c-4ca9-9ed3-241f59323774|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
csharp|ms-|1.23.2
mssql|ms-|1.9.0
sqltools|mtx|0.23.0

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen if you launch with all extensions disabled?

**Comment by rrushtw** [comment]
Dear Murray,
After I disable MSSQL extensions, vscode work well.
Sincerely,
Liu

John Murray <notifications@github.com> 於 2020年9月22日 週二 下午2:48寫道：

**Comment by rrushtw** [comment]
Dear Murray,
I found out that it only happens when I have MSSQL extensions and total
rows of my SQL code is over 1000 rows.

劉Sung <rrushtw@gmail.com> 於 2020年9月22日 週二 下午3:00寫道：

**Comment by gjsjohnmurray** [comment]
Please report this to the extension author.

**Comment by folivora-ice** [comment]
This problem can be reproduced when editor.letterSpacing: 1 is set

> Please report this to the extension author.
