### ISSUE TITLE
ParameterInformation isn't rendered when only contains a label

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10713]
- VSCode Version: 1.4
- OS Version: Windows 10

The docs for [`ParameterInformation`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#ParameterInformation) make it seem like `documentation` is optional (I hope so, Dart doesn't have any):

``` typescript
new ParameterInformation(label: string, documentation?: string): ParameterInformation
```

However if you don't provide any, the parameter info doesn't seem to be rendered:

``` typescript
let sigInfo = new SignatureInformation("SIG INFO");
sigInfo.parameters = [new ParameterInformation("PARAM INFO")];
```

![Missing parameter info](https://cloud.githubusercontent.com/assets/1078012/17814172/661545fc-6626-11e6-8b2d-a8ef1adc33a4.png)

``` typescript
let sigInfo = new SignatureInformation("SIG INFO");
sigInfo.parameters = [new ParameterInformation("PARAM INFO")];
sigInfo.parameters[0].documentation = "test";
```

![Included parameter info](https://cloud.githubusercontent.com/assets/1078012/17814175/69831390-6626-11e6-8be2-e0232e35a7a5.png)

**Comment by DanTup** [comment]
(Note: You also have to set `activeParameter` to `0` for it to render, but that was set in both cases).

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by DanTup** [comment]
@joaomoreno I understand you're trying to clean up, but this seems like a really silly bug (and hopefully simple to fix). I don't have any content for `documentation` so it seems like currently I can't have the param info rendered?

**Comment by joaomoreno** [comment]
Oh, I actually misunderstood this issue. Thanks for the ping @DanTup.

**Comment by ramya-rao-a** [comment]
@DanTup Is this still a problem?

In the Go extension, I dont pass the `documentation`, when creating the parameter either, and they get rendered just fine.

**Comment by DanTup** [comment]
Yep, works fine now. Looks very different now, so maybe it was fixed when it was tidied up :-)
