### ISSUE TITLE
Extension host terminates unexpectedly 1.49

### ISSUE THREAD

**Issue by mityaua** [microsoft/vscode#107158]
- VSCode Version: 1.49.0 and 1.49.1 too
- OS Version: Widows 10 (x64, 1909, 18363.1082)

Steps to Reproduce:

1. Update your version to 1.49 from 1.48
2. Open any html & css project. then turn on HTMLHint (https://github.com/Microsoft/vscode-htmlhint) and you got error **Extension host terminates unexpectedly** https://prnt.sc/ul44kk
Some people has this error without HTMLHint, after updating to 1.49 (about 200 people in my organization).

Does this issue occur when all extensions are disabled?: Yes/**No**

**Comment by aeschli** [comment]
Thanks for filing it against html-hint.
If your work-colleagues who also see that error can find out what other extension causes the problem that would be great.

**Comment by aeschli** [comment]
Also, please open the developer tools (Help > Toggle Developer Tools) and check the console for more information.

**Comment by mityaua** [comment]
> Also, please open the developer tools (Help > Toggle Developer Tools) and check the console for more information.

Extension Host
localProcessExtensionHost.ts:253 Debugger attached.
console.ts:137 [Extension Host] Looking for parseable documents...
log.ts:191  WARN UNRESPONSIVE extension host, 'Zignd.html-css-class-completion' took 80% of 1744.11ms, saved PROFILE here: 'C:\Users\mitya\AppData\Local\Temp\exthost-97923e.cpuprofile' Array(8)
console.ts:137 [Extension Host] Found all parseable documents.
console.ts:137 [Extension Host] Parsing documents and looking for CSS class definitions...
console.ts:137 [Extension Host] "live-sass-compiler" is now actived! Go and Debug :P 
console.ts:137 [Extension Host] Summary:
console.ts:137 [Extension Host]% 7 parseable documents found
console.ts:137 [Extension Host]% 482 CSS class definitions found
console.ts:137 [Extension Host]% 98 unique CSS class definitions found
console.ts:137 [Extension Host]% 0 failed attempts to parse. List of the documents:
console.ts:137 [Extension Host] 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/semver-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/ExperimentationService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/TasApiFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/FilteredFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/BaseFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/AxiosHttpClient.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/ExperimentationServiceAutoPolling.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/ExperimentationServiceBase.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/MemoryKeyValueStorage.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/PollingService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/main.js.map: 
console.ts:137 [Extension Host] [vscode-icons] v11.0.0 activated!
console.ts:137 [Extension Host] (node:7688) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:70
$logExtensionHostMessage @ extHostTunnelService.ts:43
_doInvokeHandler @ rpcProtocol.ts:372
_invokeHandler @ rpcProtocol.ts:372
_receiveRequest @ rpcProtocol.ts:253
_receiveOneMessage @ rpcProtocol.ts:185
(anonymous) @ rpcProtocol.ts:51
fire @ event.ts:584
fire @ ipc.net.ts:459
_receiveMessage @ ipc.net.ts:792
(anonymous) @ ipc.net.ts:647
fire @ event.ts:584
acceptChunk @ ipc.net.ts:216
(anonymous) @ ipc.net.ts:137
t @ ipc.net.ts:859
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
abstractExtensionService.ts:166 Extension host terminated unexpectedly. Code:  7  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:149
_onExtensionHostCrashed @ extensionService.ts:436
_onExtensionHostCrashOrExit @ abstractExtensionService.ts:149
(anonymous) @ abstractExtensionService.ts:111
fire @ event.ts:584
_onExtHostProcessExit @ localProcessExtensionHost.ts:480
(anonymous) @ localProcessExtensionHost.ts:241
emit @ events.js:223
ChildProcess._handle.onexit @ internal/child_process.js:272
log.ts:197   ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.github-authentication, vscode.css-language-features, vscode.emmet, vscode.html-language-features, vscode.debug-auto-launch, vscode.git, vscode.merge-conflict, vscode.search-result, kamikillerto.vscode-colorize, kisstkondoros.vscode-gutter-preview, PKief.material-icon-theme, pranaygp.vscode-css-peek, ritwickdey.LiveServer, vincaslt.highlight-matching-tag, vscode-icons-team.vscode-icons, zhuangtongfa.material-theme, Zignd.html-css-class-completion, ritwickdey.live-sass, vscode.configuration-editing, vscode.json-language-features, vscode.typescript-language-features, esbenp.prettier-vscode, vscode.github, vscode.extension-editing, ms-vscode.js-debug, vscode.npm, mkaufman.HTMLHint
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidChangeNotification @ notificationsAlerts.ts:36
(anonymous) @ breadcrumbsModel.ts:294
fire @ event.ts:584
addNotification @ notifications.ts:169
notify @ notificationService.ts:69
prompt @ notificationService.ts:149
_onExtensionHostCrashed @ extensionService.ts:436
_onExtensionHostCrashOrExit @ abstractExtensionService.ts:149
(anonymous) @ abstractExtensionService.ts:111
fire @ event.ts:584
_onExtHostProcessExit @ localProcessExtensionHost.ts:480
(anonymous) @ localProcessExtensionHost.ts:241
emit @ events.js:223
ChildProcess._handle.onexit @ internal/child_process.js:272
localProcessExtensionHost.ts:252 Extension Host
localProcessExtensionHost.ts:253 c:\Users\mitya\.vscode\extensions\ritwickdey.live-sass-3.0.0\node_modules\sasslib\sass.sync.js:61
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=(function(status,toThrow){throw toThrow});Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScr

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (c:\Users\mitya\.vscode\extensions\mkaufman.htmlhint-0.8.0\node_modules\vscode-jsonrpc\lib\messageReader.js:200:27)
    at Socket.<anonymous> (c:\Users\mitya\.vscode\extensions\mkaufman.htmlhint-0.8.0\node_modules\vscode-jsonrpc\lib\messageReader.js:185:19)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)

**Comment by mityaua** [comment]
And after restart app:

Extension Host
localProcessExtensionHost.ts:253 c:\Users\mitya\.vscode\extensions\ritwickdey.live-sass-3.0.0\node_modules\sasslib\sass.sync.js:61
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=(function(status,toThrow){throw toThrow});Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScr

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (c:\Users\mitya\.vscode\extensions\mkaufman.htmlhint-0.8.0\node_modules\vscode-jsonrpc\lib\messageReader.js:200:27)
    at Socket.<anonymous> (c:\Users\mitya\.vscode\extensions\mkaufman.htmlhint-0.8.0\node_modules\vscode-jsonrpc\lib\messageReader.js:185:19)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)

**Comment by LP5K** [comment]
![JR ) X(4SG(H__T51E{(OT0](https://user-images.githubusercontent.com/32986242/94216311-9fdfe980-ff11-11ea-8d5f-8ee488fa397f.png)

**Comment by mityaua** [comment]
1.49.2 - the same 

console.ts:137 [Extension Host] (node:16292) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:70
console.ts:137 [Extension Host] Looking for parseable documents...
abstractExtensionService.ts:166 Extension host terminated unexpectedly. Code:  7  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:149
log.ts:197   ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.github-authentication, vscode.emmet, vscode.html-language-features, mkaufman.HTMLHint, vscode.css-language-features, vscode.debug-auto-launch, vscode.git, vscode.merge-conflict, vscode.search-result, kamikillerto.vscode-colorize, kisstkondoros.vscode-gutter-preview, PKief.material-icon-theme, pranaygp.vscode-css-peek, ritwickdey.LiveServer, vincaslt.highlight-matching-tag, vscode-icons-team.vscode-icons, zhuangtongfa.material-theme, Zignd.html-css-class-completion, ritwickdey.live-sass
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidChangeNotification @ notificationsAlerts.ts:36
localProcessExtensionHost.ts:252 Extension Host
localProcessExtensionHost.ts:253 c:\Users\mitya\.vscode\extensions\ritwickdey.live-sass-3.0.0\node_modules\sasslib\sass.sync.js:61
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=(function(status,toThrow){throw toThrow});Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScr

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (c:\Users\mitya\.vscode\extensions\mkaufman.htmlhint-0.8.0\node_modules\vscode-jsonrpc\lib\messageReader.js:200:27)
    at Socket.<anonymous> (c:\Users\mitya\.vscode\extensions\mkaufman.htmlhint-0.8.0\node_modules\vscode-jsonrpc\lib\messageReader.js:185:19)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/semver-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/xterm.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/xterm-addon-unicode11.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/xterm-addon-search.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/windowsTerminal.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/terminal.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/eventEmitter2.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/windowsPtyAgent.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/utils.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/ExperimentationService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/TasApiFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/FilteredFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/BaseFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/AxiosHttpClient.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/ExperimentationServiceAutoPolling.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/ExperimentationServiceBase.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/MemoryKeyValueStorage.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/PollingService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/mitya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/main.js.map:

**Comment by aeschli** [comment]
@mityaua This needs to fixed in the html-hint extension. Please remove the extension until the issue is fixed: https://github.com/microsoft/vscode-htmlhint/issues/80
