### ISSUE TITLE
Zombie mouse highlight in Explorer

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoft/vscode#107180]
Issue Type: <b>Bug</b>

Click any node in the Explorer with the mouse.

Use the keyboard to select a different Explorer node.

The node previously clicked with the mouse is still highlighted as the selected node, but if you perform any operation with the keyboard e.g. F2 (rename), delete; it is actually the node selected with the keyboard that is the selected one.

![Focus0](https://user-images.githubusercontent.com/18445931/93812904-2b275980-fc4a-11ea-8411-68ca8e28e42c.jpg)

![Focus1](https://user-images.githubusercontent.com/18445931/93812910-2fec0d80-fc4a-11ea-89e2-8ce2ac53a676.jpg)

![Focus3](https://user-images.githubusercontent.com/18445931/93812926-34182b00-fc4a-11ea-937d-d0bf53ed8a42.jpg)

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.901.9
EditorConfig|Edi|0.15.1
LogFileHighlighter|emi|2.9.0
vscode-great-icons|emm|2.1.56
vscode-jasmine-test-adapter|hbe|1.7.0
vscode-test-explorer|hbe|2.19.1
classic-asp|ili|0.0.4
vscode-nuget-package-manager|jmr|1.1.6
csharp|ms-|1.22.0
debugger-for-chrome|msj|4.12.10
nativescript|Tel|0.11.0
subtle-brackets|raf|3.0.0
rewrap|stk|1.13.0
insert-special-symbol|swi|1.3.0
indent-one-space|use|0.2.6
html-css-class-completion|Zig|1.19.0

**Comment by isidorn** [comment]
This is how our tree works. We have focus and a selection. We will not change this. Closing as designed.

**Comment by Neutrino-Sunset** [comment]
Can you not provide any rationale to explain why such a nonsensical design is a good idea?

**Comment by Neutrino-Sunset** [comment]
Out of the focus and the selection which is which? Presumably the focus is the one you can move, same as any other control? But then what is the selection since that is the highlight that you can't actually do anything with. No keyboard shortcuts affect it, it literally does nothing yet is more promenent than the focused item.

**Comment by Neutrino-Sunset** [comment]
And how come clicking a file in the Explorer with the mouse both opens the file and 'selects' it (where 'selects' means gives it a really promenent highlight but doesn't actually do anything), but opening a file with the keyboard doesn't 'select' it?

How does that make sense?

How do I 'select' a file with the keyboard then? If for no other reason than opening a folder I never look in, 'select' a file in there and then close the folder again, which seems to be the only way to hide the additional 'selected' file node.

**Comment by Neutrino-Sunset** [comment]
My config shows `list.select` is bound to `Enter`.

So how come using the keyboard to focus a file in the Explorer and pressing Enter opens the file but leaves the selection highlight highlighting whichever file I last opened using the mouse? 

And you're saying it's supposed to be that way? I don't believe you.
