### ISSUE TITLE
Opening projects directories in the same way a file is open

### ISSUE THREAD

**Issue by senyai** [microsoft/vscode#107112]
Hello!

I'd like to suggest a feature. Often times I find myself having a full path to a file in the system buffer. To open this file in vscode, I press ＜Ctrl+P＞, ＜Ctrl+V＞, ＜Enter＞. That's very easy and pretty fast. Now I'd like to have a similar functionality but for project directories. Currently one has to press ＜Ctrl+K＞, ＜Ctrl+O＞ and find a way to paste the path in the system dialog which is often far from perfect. What I see as a way to go is to allow pasting directories in the ＜Ctrl+R＞ dialog, then opening directories will be as easy as opening a file. The ＜Ctrl+R＞ dialog already shows project directories, so pasting directories must be a good fit.

**Comment by sbatten** [comment]
`files.simpleDialog.enable`<= would this setting meet your request?

**Comment by senyai** [comment]
This is amazing! Very close. ＜Ctrl+K＞, ＜Ctrl+O＞, ＜Ctrl+A＞, ＜Ctrl+V＞, ＜Enter＞is just one shortcut too much in my opinion. I'd suggest selecting path by default and thus omitting ＜Ctrl+A＞, but I'm not sure this change would fit gui guidelines. Plus default ＜Ctrl+A＞would make ＜Arrow down＞select root on linux, which is undesirable. Maybe simpleDialog should check system buffer, and use it when there's existing path. @sbatten I can happily live with current simpleDialog, but if you see any acceptable solution, that reduces number of shortcuts, I'd really appreciate it. If it's too out of guidelines then closing the ticket is fine. Thank you very much.

**Comment by sbatten** [comment]
forwarding this to @alexr00 who owns this dialog for feedback

**Comment by alexr00** [comment]
@senyai your use case makes a lot of sense, maybe even for the system dialog too.
