### ISSUE TITLE
Hitting Enter key during IME composition on the find widget should not be handled by VSCode

### ISSUE THREAD

**Issue by tuttieee** [microsoft/vscode#107154]
- VSCode Version: 1.50.0-insider
- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

1. Add the following keybinding:
```
    {
      "key": "enter",
      "command": "closeFindWidget",
      "when": "editorFocus && findWidgetVisible"
    }
```
2. Open the find widget and input a text with IME, then hit Enter key to fix the IME input.
3. The find widget is closed and the text is inserted to the editor. This is because, Enter key, which was intended to confirm IME input, was handled by VSCode and triggers closeFindWidget command configured above though it should not have been.

![vscode-find-ime-example](https://user-images.githubusercontent.com/3135397/93757481-cec03c00-fc41-11ea-9998-7969fc46bcf7.gif)

Enter key is used by IME to confirm the input texts and should not be handled by VSCode during IME composition.
During text input in the editor areas, such IME handling can be done by extensions making use of `compositionStart` and `compositionEnd` events, like [VSCodeVim](https://github.com/VSCodeVim/Vim/blob/f18dde3ed9a46d2aae45774228ec92118d1f2471/extensionBase.ts#L377-L395) does. However, it's impossible outside the editor areas like on the find widget.
VSCode should handle such IME composition on the find widget (and other native UIs).

Does this issue occur when all extensions are disabled?: Yes

**Comment by tuttieee** [comment]
The suggested issue does not seem related

**Comment by rebornix** [comment]
Good point. Disallowing keybindings during composition makes most of the sense but I remember seeing issues complaining that some of the keyboard shortcuts not working in composition in some cases. Thus a new global context key `isComposing` will be added to give the choice to users.

**Comment by tuttieee** [comment]
Thank you, I confirmed it too.

In my case, I tested it with the keybinding that I have posted on the first comment and fixed to use `isComposing ` like this:
```
    {
      "key": "enter",
      "command": "closeFindWidget",
      "when": "editorFocus && findWidgetVisible && !isComposing"
    }
```

The problem still exists.

I used the lasted insider version.
```
Version: 1.51.0-insider
Commit: 2ee8b8c645ec8ab54304bacae7aa979c1d9c647a
Date: 2020-10-29T06:00:13.428Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

However, interestingly, the keybinding below that is included in the defaults prevents closing the find widget during IME composition expectedly.
```
{
  "key": "shift+escape",
  "command": "closeFindWidget",
  "when": "editorFocus && findWidgetVisible && !isComposing"
}
```

**Comment by rebornix** [comment]
@tuttieee may I ask what IME you are using? I tested with macOS Hiragana IME but it works

![iscomposing](https://user-images.githubusercontent.com/876920/98753909-4c6b1300-237a-11eb-8e0e-74cdf44336fb.gif)


also @isidorn the one you see is slightly different, it's macOS native accent picker (I don't really know the name) and when that quick pick shows up, the IME is not in composition mode, thus we can't really tell if the quick pick is visible or not. It's similar to the emoji quick pick which we don't support.

**Comment by isidorn** [comment]
@rebornix thanks for explaining. I was not aware it is a different thing...

**Comment by tuttieee** [comment]
@rebornix I'm sorry, I found I tested it with another old keybinding that didn't care about `isComposing` and it was successful deleting the wrong keybinding.
I confirmed it now works fine.
Thank you for your support 😄
