### ISSUE TITLE
Collapse Multiline Comments with Python

### ISSUE THREAD

**Issue by imjiangjun** [microsoft/vscode#107199]
Issue Type: <b>Feature Request</b>

Multiline comments both inside and outside the function can't be collapsed with Python. When there are hundreds of commented lines, it isn't convenient to view code. Even just fold those lines starting with '#' will make things better.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.13.0-39-generic

**Comment by aeschli** [comment]
This needs to be provided by the Python extension.
There's already an issue for it: https://github.com/microsoft/vscode-python/issues/1847
