### ISSUE TITLE
Replace button no longer aligned right, prevents repetitive replacement without moving mouse

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode#107195]
Issue Type: <b>Bug</b>

In previous versions:
1.  hit Ctrl+Shft+H - Search: Replace in Files
2.  type a search keyword
3.  hover mouse over the Replace button near the right edge of the tool window, after a find result.
4.  click the Replace button (this result disappears)
5.  the next result moves up with the Replace button in the same spot
6.  make repetitive replacements without moving the mouse.

In latest version:
the replace button is not aligned to the right edge, but the end of the result preview text (not exceeding the right edge).  so for short lines, the replace button is no longer consistently in the same spot for all search results, requiring you to move the mouse for each replacement.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19042

**Comment by roblourens** [comment]
It sounds like you want to set `"search.actionsPosition": "right"`
