### ISSUE TITLE
C++ Token/Scope Resolution is Incorrect

### ISSUE THREAD

**Issue by braxtons12** [microsoft/vscode#107172]
VSCode Version: Insiders 1.50.0
 OS Version: Windows 10 1903

Previously Reported this in #107043 , but was asked to split it up per language 

After updating from Insiders 1.49 to Insiders 1.50, token resolution is incorrect for c++ code, causing syntax highlighting to be incorrect.

For example, according the Editor Tokens and Scopes Inspector, member variables are being picked up as:

semantic token type: "member"
foreground: "entity.name.function.member, entity.name.function, support.function, support.constant.handlebars"

when they should be picked up as "variable.member", "property", or similar
and exception specifiers are being picked up as two different things, keywords or variable access specifiers, EG:

textmate scopes: "variable.other.object.access.cpp, meta.body.class.cpp, meta.block.class.cpp, source.cpp"
foreground: "variable"

When these should be picked up only as "keyword" or similar.

Example C++ code causing the problem:
https://pastebin.com/4AdtvMB6

Example images showing the Token Inspector:
![c++tokensexample](https://user-images.githubusercontent.com/28696801/93800592-70299c80-fc06-11ea-9c56-994401c526dd.PNG)
![c++tokensexample2](https://user-images.githubusercontent.com/28696801/93800596-71f36000-fc06-11ea-9d36-2e2a67e0c997.PNG)

I'm using:
vscode-clangd
cpp-tools
cmake tools

**Comment by alexr00** [comment]
Thanks for filing this issue. Since it's coming from our C++ grammar, I have opened an issue in the repo we get the C++ grammar from: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/504
