### ISSUE TITLE
Windows shutdown/restart during VSCode update uninstalls VSCode

### ISSUE THREAD

**Issue by naumazeredo** [microsoft/vscode#107188]
Issue Type: <b>Bug</b>

1. Close VSCode
2. Start reboot/shutdown while VSCode update window is open.
3. Windows will show it's waiting for VSCode update to finish in shutdown window.
4. After restart (or even if you try to cancel the shutdown), VSCode is inaccessible (VSCode folder is mostly emptied).

Related to this bug is: https://github.com/microsoft/vscode/issues/103537, which was closed automatically by a bot, but I can repro this issue consistently. I had to reinstall VSCode 4 times already.
Windows simply kills VSCode update, so it doesn't complete and just deletes old files. Probably can only be reproduced if a new VSCode version is available, since it shouldn't delete any file in case it doesn't need an update.

VS Code version: Code - Insiders 1.49.0-insider (00754e4babebc9ee5aa881234bc16366c4f32aa9, 2020-09-02T05:56:03.393Z)
OS version: Windows_NT x64 10.0.20215

**Comment by espresso3389** [comment]
When Windows restarts automatically (or manually) due to some reason, VSCode is closed by the OS but it attempts to invoke update during the OS shutdown process and it results in corruption of VSCode files.

I think VSCode should update it on launch rather than on close.

**Comment by joaomoreno** [comment]
#52855
