### ISSUE TITLE
Code Lens - Reference information for TypeScript

### ISSUE THREAD

**Issue by zplume** [Microsoft/vscode#10717]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.6

It would be amazing if vscode was able to provide the reference info functionality for TypeScript classes and methods that it provides for C#:
https://code.visualstudio.com/docs/editor/editingevolved#_reference-information

![image](https://cloud.githubusercontent.com/assets/2255088/17820875/cb5102a6-6646-11e6-83a9-b38f5e318e26.png)

Thanks!

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10500

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10502

**Comment by waderyan** [comment]
Reopening to track feature request.

**Comment by yahiko00** [comment]
Also, I'm wondering if it could be possible to display in TypeScript, on demand, the whole prototype chain of a given class in order to have in one glance all inherited properties without navigating through all ancestors of such a class. Maybe I should create a proposal...

**Comment by waderyan** [comment]
@yahiko00 yeah that would be great. The more detailed the proposal the more likely it could get picked up. If you think it applies to VS Code open it up as a new issue in VS Code's repo, otherwise open it in TypeScript. They're very responsive.

**Comment by waderyan** [comment]
@dbaeumer here is the feature request.

**Comment by kisstkondoros** [comment]
FYI: https://github.com/kisstkondoros/typelens

**Comment by mjbvz** [comment]
This is included in VSCode 1.9. Just add the setting: `"typescript.referencesCodeLens.enabled": true` to try it out
