### ISSUE TITLE
Pinned tabs overlap when folder names are visible

### ISSUE THREAD

**Issue by ChristopherHaws** [microsoft/vscode#107124]
- VSCode Version: 1.50.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Set your pin tab size to "normal": `"workbench.editor.pinnedTabSizing": "normal"`
2. Open an empty folder
3. Create 2 folders (in my example they are called `folder1` and `folder2`)
4. Create a file in each folder that are named the same (in my example they are called `file.txt`)
5. Open both files and pin one of them
6. Notice that the tabs overlap because the pinned tab is not taking the folder name into account
![image](https://user-images.githubusercontent.com/5934505/93722073-fb445d00-fb48-11ea-961b-e773fdeec87d.png)

Does this issue occur when all extensions are disabled?: Yes

/cc @bpasero

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/09a78db5ef427ab945a2773239ab9fd6a9ef5e1c

**Comment by ChristopherHaws** [comment]
@bpasero I do not believe that commit solves this problem. From what I can see that commit is changing the default to be "normal" which is not what this bug refers to.

**Comment by bpasero** [comment]
@ChristopherHaws yeah but it also fixes a bad logic here:

https://github.com/microsoft/vscode/commit/09a78db5ef427ab945a2773239ab9fd6a9ef5e1c#diff-40eb1f52e432c4163061705abdfb5d61R1059
