### ISSUE TITLE
Simple file dialog: doesn't match against entries on the first character typed

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#107168]
It would be great if the first character typed, would start matching against the list of entries

**Comment by eamodio** [comment]
This is actually another manifestation of https://github.com/microsoft/vscode/issues/107170

If the dialog opens to say `C:\Users\user\code\foo\bar\` and I delete it to `C:\Users\user\code\` then it won't match on the first char

**Comment by misolori** [comment]
Taking this off the milestone so it doesn't come up in verification
