### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by puranik3** [microsoft/vscode#107193]
Issue Type: <b>Bug</b>

I updated VSCode 2 days back. Since then there have been frequent crashes -once every hour or so, sometimes 2 - 3 continuous crashes). I feel there is something wrong here.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 6, 4|
|Memory (System)|16.00GB (1.41GB free)|
|Process Argv|--crash-reporter-id b564895a-af39-49fe-939a-950bb1bc6a06|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo are you using any extensions? If so, did you test with all extensions disabled?
