### ISSUE TITLE
Class function coloring fails if type sequelize.Model<{}, {}>; is used

### ISSUE THREAD

**Issue by mahald** [Microsoft/vscode#10714]
- VSCode Version: 1.4.0
- OS Version: Windows 10 Latest
- Language: TypeScript using nodejs

If a type such as `sequelize.Model<{}, {}>;` is used in a class the coloring after this type will fail.
Fore example here:

`

     import * as sequelize from "sequelize";

     export class Authenticate {

     protected userGroups: sequelize.Model<{}, {}>;
     protected users: sequelize.Model<{}, {}>;
     protected groups: sequelize.Model<{}, {}>;

     /**
       * Construct the class
       * 
       * @Class Authenticate
       */
      constructor() {
       this.initDb();
      } 

       /**
        * Initialize the DB Models
        */
     protected async initDb(): Promise<void> {
     ...
`

the coloring after `protected userGroups: sequelize.Model<{}, {}>;` is bugged.
Steps to Reproduce:

1. get typings for `sequelize` and dependencies (`validator `and `lodash`)
2. import * as sequelize from "sequelize";
3. create a Calss 
4. Within the Class define a variable with the type sequelize.Model<{}, {}>;
5. put some variable or functions after this definition
6. enjoy the wrong coloring of the class functions and variables ....

**Comment by alexandrudima** [comment]
@mahald This appears to be fixed on master, it will come out with the August release on the stable channel. You can get the fix now by installing the Insiders version.

1.4.0:
![image](https://cloud.githubusercontent.com/assets/5047891/17846738/70fb6a34-684a-11e6-8f8a-7bee4cf66c4b.png)

1.5.0/master/insiders:
![image](https://cloud.githubusercontent.com/assets/5047891/17846748/7f6f3a1e-684a-11e6-8024-3fc05af0b923.png)
