### ISSUE TITLE
[🔥Theme] semanticTokenColors does not work correctly

### ISSUE THREAD

**Issue by thisVioletHydra** [microsoft/vscode#107117]
> Version: 1.49.0 (system setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. setup theme : https://marketplace.visualstudio.com/items?itemName=Roman.ayu-next
2. open any free **project**, javascript, and try type `console.log('asdasd')`
3. see problem, `console.log` not have highlighting
![image](https://user-images.githubusercontent.com/11839238/93718975-4e89d000-fb88-11ea-95e7-0291c6047dc0.png)
4. Let's see the settings of the theme I'm using
![image](https://user-images.githubusercontent.com/11839238/93719191-94936380-fb89-11ea-9037-83a5d4bb9b5a.png)
5. Now I launch the project in the **debugger** and see that everything works, what am I doing wrong?
![image](https://user-images.githubusercontent.com/11839238/93719222-b5f44f80-fb89-11ea-8fbe-86682990589b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
You can see in the scope inspect tool that `console` did not get the `defaultLibrary` modifier. Can you do a goto definition on `console`?

**Comment by thisVioletHydra** [comment]
> defaultLibrary

![image](https://user-images.githubusercontent.com/11839238/93813750-3be0cb00-fc5c-11ea-8175-19026922fb2a.png)
this ??

**Comment by aeschli** [comment]
- put the cursor on `console` and invoke F12 (Goto Definition).
- in the editor or peek that show, what path does the d.ts file have that contains the declaration
![image](https://user-images.githubusercontent.com/6461412/93852554-812fe780-fcb2-11ea-9e85-d94e7cefae69.png)

**Comment by thisVioletHydra** [comment]
> * what path does the d.ts file have that contains the declaration

i have this:
![image](https://user-images.githubusercontent.com/11839238/93855487-42a12980-fcc0-11ea-9e59-bf59ea610d73.png)

and this: 
![image](https://user-images.githubusercontent.com/11839238/93855508-49c83780-fcc0-11ea-9312-71cf1c54a0b8.png)

**Comment by thisVioletHydra** [comment]
hmm... 
The most interesting thing is that when I check the `goto definition` in debugger, the library is connected there `lib.dom.d.ts`:
`C:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\lib.dom.d.ts`
![image](https://user-images.githubusercontent.com/11839238/93855893-edb1e300-fcc0-11ea-8ac1-9c20633705de.png)

**Comment by thisVioletHydra** [comment]
> * put the cursor on `console` and invoke F12 (Goto Definition).
> * in the editor or peek that show, what path does the d.ts file have that contains the declaration
>   ![image](https://user-images.githubusercontent.com/6461412/93852554-812fe780-fcb2-11ea-9e85-d94e7cefae69.png)

if i killed this file: `jsconfig.json`
semanticWork hm... 
![image](https://user-images.githubusercontent.com/11839238/94349632-10405500-004f-11eb-8dcd-abfac24c6f4c.png)

if you know, help me fix config: 
```json
{
  "title": "JSON schema for the TypeScript compiler's configuration file",
  "description": "config for VS CODE",
  "compilerOptions": {
    "lib": ["ESNext"],
    "noEmit": true,
    "rootDir": ".",
    "module": "ESNext",
    "target": "ESNext",
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"],
      "~~/*": ["./*"],
      "@@/*": ["./*"],
      "@root": ["."],
      "@access": ["./.access"],
      "@webpack": ["./webpack.config.js"],
      "@models": ["./src/models"],
      "@app": ["./src/app"]
    }
  },

 "compileOnSave": false,
 "include": ["**/*"],
 "exclude": ["node_modules/*", ".nuxt", "dist", "assets"],

  "eslint.enable": true,
  "files.exclude": {
    "node_modules": true,
    ".npm-offline-cache": true
  },
  "editor.formatOnSave": true,
  "[javascript]": {
    "editor.formatOnSave": true
  }
}
```

**Comment by thisVioletHydra** [comment]
`"lib": ["dom", "dom.iterable", "esnext"],`
I helped myself 🤔
