### ISSUE TITLE
When reopen code from WSL2, previous open tabs are not restored

### ISSUE THREAD

**Issue by swinder0161** [microsoft/vscode#107111]
- VSCode Version: 1.49.1 x64 58bb7b2331731bf72587010e943852e13e6fd3cf
- OS Version: Windows 2004 + WSL2 Ubuntu 20.04

Steps to Reproduce:

1. From WSL2, open code with some files -> $ code debug.log
2. Close code in windows
3. Open code again from WSL2 shell -> $ code
4. Code opens a fresh window with the welcome tab only and does not restore previously open files eg. debug.log in my case

Does this issue occur when all extensions are disabled?: Yes
Actually it is not possible to run code --disable-extensions when need to run in WSL remote environment

**Comment by swinder0161** [comment]
Hi @aeschli Please comment on feasibility of this usecase.

It is really important feature and this is restricting me to use code from within wsl2

**Comment by aeschli** [comment]
@bpasero Where does the restoring of editors happen?

**Comment by bpasero** [comment]
@aeschli they are part of workspace storage but it sounds as if code starts on an empty workspace and not the same WSL workspace when started again, which would explain why editors are not restoring?

**Comment by swinder0161** [comment]
@aeschli I have tried insider release 1.50.0 but still this problem is there
Which release is this feature going to be released?

**Comment by aeschli** [comment]
You are right, the empty workspace with file case was still not working.
Pushed a fix.

The original idea was to not restore empty remote workspaces, but I didn't realize that they can have editors open.
-> another special case removed

**Comment by swinder0161** [comment]
Thanks will download insider tomorrow again.

**Comment by swinder0161** [comment]
Still not working @aeschli 

Version: 1.50.0-insider (user setup)
Commit: **ddc98c3f620ab1d2ecad5942ebf4736060403d67**
Date: 2020-09-25T05:35:02.163Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by aeschli** [comment]
It works for me in ddc98c3f620ab1d2ecad5942ebf4736060403d67
My steps:
- open a Ubuntu shell: 
- `code-insiders .bashrc`, VSCode opens with `.bashrc` in an editor.
- close VSCode
- `code-insiders`. VSCode opens with `.bashrc` in an editor.

**Comment by swinder0161** [comment]
@aeschli Exactly same steps but it always opens with welcome tab

Some logs which I may provide to you to check this?

**Comment by swinder0161** [comment]
I got the problem, I had Custom CSS and JS Extenstion for Multiline Open Editors Tabs. Disable that and reload. This worked well.

Thanks for your help.

I was wondering, is it possible to have an option that when WSL session is open already, any file opened from windows using double click also goes to same VSCode windows instead of opening another VSCode local.

VSCode WSL remote session already has support for open local files.

Just want to avoid 2 VSCode windows open at teh same time.

**Comment by aeschli** [comment]
We support local files in the WSL window, but they come in through a remote uri (`vscode-local://) and only few extensions can handle them fully. So we rather not promote that...

For WSL we could convert them to `file://mnt/c/...` URIs but we currently don't have the hooks for that. 

For your use case, maybe drag and drop is useful?

**Comment by swinder0161** [comment]
Drag and drop is ok when we are already in WSL remote VS code windows.

What about reverse? if we have Local VS Code open, and I want to open WSL remote file, it will open new VSCode window.

I want to use single window open for VSCode can handle n=both,

**Comment by swinder0161** [comment]
Actually created a FR for this https://github.com/microsoft/vscode/issues/107529
You are the assignee for that too.
