### ISSUE TITLE
Latest Update fails

### ISSUE THREAD

**Issue by vchealy** [microsoft/vscode#107119]
Issue Type: <b>Bug</b>

Version: 1.50.0-insider (user setup)
Commit: cca20eba8974b1d6b6a9b71bf4e60a29c8f26648
Date: 2020-09-12T01:04:21.398Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

VS Code version: Code - Insiders 1.50.0-insider (cca20eba8974b1d6b6a9b71bf4e60a29c8f26648, 2020-09-12T01:04:21.398Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 2020M @ 2.40GHz (2 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.34GB free)|
|Process Argv|--crash-reporter-id 3262e7a8-d23d-4911-87e6-b52d57cd7309|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
code-runner|for|0.11.0
python|ms-|2020.8.109390
vscodeintellicode|Vis|1.2.10

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you provide more details on how it fails exactly?
