### ISSUE TITLE
Formatting failed: Unable to start child process

### ISSUE THREAD

**Issue by CodeNameHawk** [microsoft/vscode#107162]
Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:23:38.048Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT ia32 10.0.18363

Extensions:
Arduino v0.3.2
C/C++ v1.0.0
C++ Intellisense v0.2.2

Steps to Reproduce:

1. Edit Arduino ino file.
2.Press SHIFT+ALT+F format file.

Formatting failed:
"c:\Users\Marian\.vscode\extensions\ms-vscode.cpptools-1.0.0/bin/../LLVM/bin/clang-format.exe" -style="{ BasedOnStyle: LLVM, UseTab: Always, IndentWidth: 4, TabWidth: 4, BreakBeforeBraces: Allman, AllowShortIfStatementsOnASingleLine: false, IndentCaseLabels: false, ColumnLimit: 0, AccessModifierOffset: -4, NamespaceIndentation: All }" -fallback-style="LLVM" -sort-includes=1 -assume-filename="c:\Users\Marian\Documents\Arduino\Atmega2560_Franek\Ekarany.ino"
Unable to start child process!

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
Please file this against the cpp extension: https://github.com/microsoft/vscode-cpptools

**Comment by CodeNameHawk** [comment]
It looks like this is caused by the C++ extension. Please file it with the repository here. Make sure to check their issue reporting template and provide them relevant information such as the extension version you're using. See also our issue reporting guidelines for more information.
