### ISSUE TITLE
TS Server is too high cpu and memory

### ISSUE THREAD

**Issue by saQut** [microsoft/vscode#107155]
Issue Type: <b>Performance Issue</b>

Project: Working NodeJS project and self project no anything framework (ExpressJS and AngularJS vs.)
Linux 5.7.19-2-MANJARO x64 on KDE5
Note: Working big directory, there are too many files and directories
Dell Inspiron L5510 Nvidia-1gb 4gb-ddr4-ram ~5.20gb Swap memory (SSD disk)
Total disk : 128 SSD (on linux (this is working disk)), 500gb HDD (Windows)
Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz ((2 physical) 4 core)

While not writing and touching, status like this
CPU 100%
RAM 80% ~3.60gb/4gb
Swap 35%

ps aux result;
abdussa+    8935  163  3.7 1096164 147108 ?      Rl   13:25  59:41 /usr/lib/electron7/electron /usr/lib/code/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /home/abdussamed/.cache/typescript/3.9 --enableTelemetry --typesMapLocation /usr/lib/code/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation

I updated all components and libraries but it was not effective. 

VS Code version: Code - OSS 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T19:14:08.130Z)
OS version: Linux x64 5.7.19-2-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2298)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 5, 5|
|Memory (System)|3.75GB (0.13GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    73	  2926	code-oss main
    0	     4	  2928	   zygote
    0	    42	  2950	   gpu-process
    0	     8	  2966	   utility
    0	   192	  2974	   window (indent.js - Sihherainyme v3 - Code - OSS)
    0	     8	  3038	     watcherService
    0	    73	  8886	     extensionHost
    0	    62	  8900	       electron_node tsserver.js 
   38	   769	  8901	       electron_node tsserver.js 
   12	    46	  3000	   shared-process
    0	     0	  9486	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    2	   119	  9460	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (indent.js - Sihherainyme v3 - Code - OSS)
|    Folder (Sihherainyme v3): more than 20586 files
|      File types: html(14317) js(1821) webp(323) png(275) less(221) css(53)
|                  json(50) tsv(13) node_sesion(12) csv(11)
|      Conf files: launch.json(4) package.json(3) settings.json(1) makefile(1)
|                  gulp.js(1)
|      Launch Configs: node;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-js-profile-flame|ms-|0.0.8

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? Using VS Code insiders, follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Share the output of `code-insiders --status`
