### ISSUE TITLE
Search view: I ofter hit the dismiss button by accident

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#107163]
I often click on the search result view's dismiss button by accident. That forces me to search again.
- it's hard to see as it is so close to the text 
- and only shows up on hover
- it is at a different location every line
- it has the same color as the text

![image](https://user-images.githubusercontent.com/6461412/93782146-83e6fa00-fc2a-11ea-8a81-31f868fc4f8e.png)

Other views have it at the end. I suggest to put it there.

**Comment by nrayburn-tech** [comment]
Another issue created here, https://github.com/microsoft/vscode/issues/103398. Looks like there is a setting to align the buttons right, but not always show.

**Comment by roblourens** [comment]
Yeah you want `"search.actionsPosition": "right"`. Actually this is the second time this has come up in 24 hours hours. I'll try changing the default in October.
