### ISSUE TITLE
The cursor resets to the start of the line

### ISSUE THREAD

**Issue by Rahul-Krosuri-au6** [microsoft/vscode#107106]
- VSCode Version: August 2020 (1.49.1)
- OS Version: Windows 10

Info about this bug (or) error:

When I am writing my code it skips to the start of the line. It did not happen before and started happening after the update
 I have Auto save feature on and I thought that was the reason but when I saved manually the same thing repeats (it goes back to the start of the line). I did try restarting the vs code and even my system but none of them worked. Any help I can get will be greatly appreciated. Thank you

Does this issue occur when all extensions are disabled?: Yes

**Comment by saimehar31** [comment]
I would like to know does this error occurs when you write code in a specific programming language or for all languages?

**Comment by Rahul-Krosuri-au6** [comment]
It did while I was writing JavaScript code (React) as per other languages it didn't happen (other languages :- C, python)

**Comment by aeschli** [comment]
Do you have format on save enabled?

Any other settings that could cause this? The easiest unset all settings is with the Settings JSON editor.

**Comment by Rahul-Krosuri-au6** [comment]
Thank you @aeschli  it was formatting the document whenever it was getting autosaved, I had no idea how to revert this back and so I uninstalled and reinstalled vs code and its fine now
But can you please explain how to disable the format on save

**Comment by aeschli** [comment]
There's a setting "editor.formatOnSave"

**Comment by Rahul-Krosuri-au6** [comment]
thank you
