### ISSUE TITLE
Branches view

### ISSUE THREAD

**Issue by hraz-msft** [microsoft/vscode#107149]
It would be great to see a view of git branches that the user can easily manage them (rename, delete) in one place.
The existing commands for git are not very comfortable for bulk set of actions.

**Comment by joaomoreno** [comment]
Have you tried GitLens?

**Comment by hraz-msft** [comment]
Hi, Yes. It is nice extension. But I thought it would be nice to add this feature to the built-in git tool. I'm not using GitLens so often. The basic git tool that you have is enough for me (for creating brunshes, push, pull, see diffs and solve conflicts).

In my perspective, adding a small trash icon / edit icon in the right side for each line in the branches list (if it possible) would be very cool.

![image](https://user-images.githubusercontent.com/66222191/94120744-284e8380-fe59-11ea-926f-d201377faeb0.png)

**Comment by joaomoreno** [comment]
It's debatable. You get into that list since you intend to `check out`. So providing edit/delete options could be confusing to some users. I will close this as out of scope and keep the suggestion to use GitLens which provides outer loop git functionality.
