### ISSUE TITLE
"Go To Bracket" command under "Go" menu lists wrong keyboard shortcut

### ISSUE THREAD

**Issue by grandmasteri** [microsoft/vscode#107181]
- VSCode Version: 1.49.1
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

keyboard shortcut listed in the "Go" menu for "Go To Bracket" (⌘I) doesn't do anything. After searching online and confirmation by testing it seems the correct shortcut for this command is "⌘ + shift + \\" so that is what the menu should list as well.
1. Launch Visual Studio Code
2. Select the Go menu at the top left of the screen to view the incorrectly listed keyboard shortcut for the "Go To Bracket" command
![image](https://user-images.githubusercontent.com/31323121/93812936-2b523580-fc07-11ea-953e-5fc29de2874a.png)

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by kieferrm** [comment]
I think the issue here is that depending on your keyboard layout <kbd>Shift</kbd>+<kbd>\\</kbd> is the key cord to type <kbd>|</kbd>.

**Comment by grandmasteri** [comment]
You're right... I totally thought it was an I :-|
