### ISSUE TITLE
Settings sync - client side telemetry

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#107152]
When a setting sync failure occurs it would be great if we would validate that the failure occurred against one of the valid settings sync endpoints (insiders/stable). Along with the sync execution failure we should also emit the environment (insiders/stable) against which the failure occurred. 

Edit: Also add the resource uri

**Comment by sandy081** [comment]
@lszomoru Can you please elaborate what is required here from the client side?

**Comment by sandy081** [comment]
- Broken `ConnectionRefused` error into `RequestTimeout`, `RequestCanceled` and `RequestFailed` error codes. 
- Request url is passed to telemetry along with above error code

**Comment by sandy081** [comment]
Please verify it using code review.

**Comment by lszomoru** [comment]
LGTM! Thank you!

**Comment by lszomoru** [comment]
Verified changes by looking at the telemetry.
