### ISSUE TITLE
Different Profiles for different type of Development

### ISSUE THREAD

**Issue by aromalanil** [microsoft/vscode#107137]
## Description
It would be great if the VS code supports different profiles for a different type of development. Like I use VScode for Flutter, React and some backend development. I need a way to disable all my Flutter extensions when doing React and vice versa.

## Why
- Disable some conflicting snippets, shortcuts etc.
- Speed up loading time with fewer extensions.
- Increase convenience

## Example.
1. Flutter Mode
  - Flutter, Dart, Flutter Snippets extensions are the only extensions enabled.
  - Maybe a sperate Color Theme and Icon Theme.
2. React Mode
  - Javascript snippets, ESLint are the only extensions enabled

## Other Details
If anyone wishes for this feature, please mark your request by liking this issue.

**Comment by aeschli** [comment]
It's probably already possible to do that using different user-dir paths
