### ISSUE TITLE
Build broken on OS X

### ISSUE THREAD

**Issue by start** [Microsoft/vscode#1071]
Following the instructions in the [contribution guidelines](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source), I received the following error when I ran `gulp watch`:

```
$ gulp watch

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                  ^

Error: ENOENT: no such file or directory, open '/Users/dem/proj/vscode/node_modules/gulp-tsb/lib/typescript/lib.d.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at new DefaultLibScriptSnapshot (/Users/dem/proj/vscode/node_modules/gulp-tsb/lib/builder.js:354:32)
    at Object.createTypeScriptBuilder (/Users/dem/proj/vscode/node_modules/gulp-tsb/lib/builder.js:29:44)
    at Object.create (/Users/dem/proj/vscode/node_modules/gulp-tsb/lib/index.js:28:28)
    at createCompile (/Users/dem/proj/vscode/gulpfile.js:43:15)
    at compileTask (/Users/dem/proj/vscode/gulpfile.js:74:16)
    at Object.<anonymous> (/Users/dem/proj/vscode/gulpfile.js:100:47)
    at Module._compile (module.js:435:26)
```

I resolved the error by:

1.  Creating the `~/proj/vscode/node_modules/gulp-tsb/lib/typescript/`folder, which was missing:

    ```
    cd ~/proj/vscode/node_modules/gulp-tsb/lib/
    mkdir typescript
    ```

2. Copying `~/proj/vscode/out/vs/languages/typescript/common/lib/lib.d.ts` into that new `typescript` folder:

    ```
    cp ~/proj/vscode/out/vs/languages/typescript/common/lib/lib.d.ts ~/proj/vscode/node_modules/gulp-tsb/lib/typescript
    ```

**Additional information:**

- I didn't have mocha or gulp installed before trying to build Visual Studio Code
- This is on the master branch
- I'm able to duplicate this error every time I clone a new copy of the repository

If there is any other information you need, I'm happy to help!

**Comment by sergot** [comment]
The problem exists on other platforms too, probably due to https://github.com/jrieken/gulp-tsb/commit/e758da462e4ff2749db3b347e88252c119473a33

**Comment by sergot** [comment]
I see it fixed with https://github.com/Microsoft/vscode/commit/92cba7e9fe78c87fa10a4931657d86be66123c96 and https://github.com/Microsoft/vscode/commit/b71ce1948a88eeed6aa84d4eab46e16d49de0c0d

**Comment by egamma** [comment]
This should work now, we follow the same steps during development, pls reopen if it still doesn't work for with the latest code.
