### ISSUE TITLE
Git shows tag that are deleted

### ISSUE THREAD

**Issue by acohenOT** [microsoft/vscode#107118]
Issue Type: <b>Bug</b>

Create a tag in your Git repo. Sync changes with VS Code so it sees the new tags. Then delete the tag from Git repo and sync with the remote again. The tag still shows in VS Code.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.84GB free)|
|Process Argv|--folder-uri file:///e%3A/Product/9.0.2.x_branch/build --crash-reporter-id 9b0dc00a-cb8f-44be-998e-6068d165c4c3|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1001.0
doxdocgen|csc|0.7.2
vscode-pull-request-github|Git|0.20.0
better-cpp-syntax|jef|1.15.0
code-beautifier|mic|2.3.3
csharp|ms-|1.23.2
mssql|ms-|1.9.0
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.0
cpptools-extension-pack|ms-|1.0.0
powershell|ms-|2020.6.0
vsliveshare|ms-|1.0.2740
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.2823
debugger-for-chrome|msj|4.12.10
debugger-for-edge|msj|1.0.15
cmake|twx|0.0.17

(1 theme extensions excluded)

</details>

**Comment by acohenOT** [comment]
After `git pull`, VS Code shows tags but Visual Studio 2019 does not
![image](https://user-images.githubusercontent.com/34688558/93719314-a7894200-fb4f-11ea-927e-49292d016435.png)
![image](https://user-images.githubusercontent.com/34688558/93719321-b8d24e80-fb4f-11ea-94e5-33b001f7062c.png)

**Comment by joaomoreno** [comment]
What does `git tag` show?

**Comment by acohenOT** [comment]
Interesting. `git tag` does show the tags. The prune command did not delete the tags but deleting the tags manually using `git tag -d`  worked. Now the tags no longer show in Visual Studio Code. Thanks for your help. I guess this is functioning as designed. 

![image](https://user-images.githubusercontent.com/34688558/94148717-f9c6ad80-fe44-11ea-8eb0-2ba08a7e3d7d.png)
