### ISSUE TITLE
Moving custom editor results in a new WebView being loaded

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#107177]
- Version: 1.49.0
- Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
- Date: 2020-09-10T17:39:53.251Z
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Clone https://github.com/microsoft/vscode-extension-samples/tree/master/custom-editor-sample
2. Start debugging
3. Move the custom editor to a different editor column
4. The `resolveCustomEditor` gets invoked everytime the editor is moved around.

Unlike Custom WebViews, the context is not retained & it looks like the webview is destroyed & re-created anew when ever the custom editor is moved around.

For Python extension & possibly others, moving from WebViews this is a breaking change. As WebViews retain context & webview isn't destroyed when moving it around.

Does this issue occur when all extensions are disabled?: N/A

**Comment by mjbvz** [comment]
I just tested this in the custom editor sample but don't see this happening. 

If you still see this in the latest insiderbuilds, please share more specific steps to reproduce so I can investigate
