### ISSUE TITLE
Preview Notebook Editor does not support markdown

### ISSUE THREAD

**Issue by nemonominem** [microsoft/vscode#107192]
Issue Type: <b>Bug</b>

The Preview Notebook Editor (VSCode Insiders) does not support markdown cells correctly.

As simple markdown cell with 'Hello' display that correctly, but \<h1>Hello\</h1> won't work.
The \<li>\<ul>\<hn> etc basically don't work. Only plain text.

I am developing via SSH on a linux box.

Tx,
Gilles

VS Code version: Code - Insiders 1.50.0-insider (403a6895f401c397933ec5c4f7d89432a33509b6, 2020-09-18T05:31:09.978Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 3.10.0-1127.18.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.90GB free)|
|Process Argv|--crash-reporter-id ac2486d6-f967-48c8-99ef-c51a1f181949|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: pxlbig03|
|OS|Linux x64 3.10.0-1127.18.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (64 x 2100)|
|Memory (System)|503.60GB (12.29GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.6.7
remote-containers|ms-|0.141.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
vscode-remote-extensionpack|ms-|0.20.0
fast-open-html-in-browser|D1n|0.0.4
vscode-markdownlint|Dav|0.36.3
githistory|don|0.6.9
r|Iku|1.4.6
add-new-line-to-files|jdf|0.1.1
python|ms-|2020.8.109390
vscode-yaml|red|0.11.0
r-lsp|REd|0.1.11
vscodeintellicode|Vis|1.2.10

(2 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
Currently we don't allow plain text html in markdown rendering.
