### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by ChenAlmost** [microsoft/vscode#107196]
Issue Type: <b>Bug</b>

create a js file in create react app project 

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T17:39:53.251Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 4|
|Memory (System)|8.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 09d29ecc-fabc-4d09-a0e4-6fd3803405da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
gitlens|eam|10.2.2
prettier-vscode|esb|5.6.0
vscode-styled-components|jpo|0.0.31
LiveServer|rit|5.6.1
language-stylus|sys|1.11.0
vscode-mew|vsc|1.0.4
vscode-wakatime|Wak|4.0.8

</details>

**Comment by ChenAlmost** [comment]
slove the problem by change the version of typescript

**Comment by lakshmigandh** [comment]
@ChenAlmost Can you please let me know how ?
The auto complete is also gone now.

**Comment by ChenAlmost** [comment]
> @ChenAlmost Can you please let me know how ?
> The auto complete is also gone now.



> @ChenAlmost Can you please let me know how ?
> The auto complete is also gone now.

https://github.com/microsoft/vscode/issues/107331
