### ISSUE TITLE
I cannot change the zoom level with ⌘ + +/-

### ISSUE THREAD

**Issue by AndreaPi** [microsoft/vscode#107101]
Issue Type: <b>Bug</b>

When I press <kbd>⌘</kbd> + <kbd>+/-</kbd> in order to increase/decrease the zoom level of a Code window, I get the error message below:

![image](https://user-images.githubusercontent.com/8233615/93708387-05a92b80-fb36-11ea-86b8-ea4ca9ff1e81.png)

I click on <kbd>Open Settings</kbd> and from there I'm able to edit the `settings.json` file. This is an awkward workaround: it would be much more convenient if the keyboard shortcut actually worked as intended. I even went so far as to edit the permissions of `settings.json` so that everyone could write it (not a best practice...), but the keyboard shortcut still doesn't work:

```
(base) ...$ pwd
/Users/.../Library/Application Support/Code/User
(base) ...$ ls -al settings.json
-rw-rw-rw-  1 ...  staff  847 Sep 20 11:30 settings.json
```

BTW, **compliments** for the bug submission system! Being able to open a GitHub issue directly from Code GUI is kind of amazing. Maybe it's usual on modern applications, but this is the first time I saw it, so...good job! 👍

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.30GB free)|
|Process Argv|--crash-reporter-id df4f7917-f728-4290-9500-a3632318c3e7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.52
gc-excelviewer|Gra|3.0.40
vscode-insertdatestring|jsy|2.3.0
wordcounter|kir|2.3.0
vscode-docker|ms-|1.6.0
python|ms-|2020.8.109390
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
neuron-IPE|neu|1.0.4
printcode|nob|3.0.0

</details>

**Comment by aeschli** [comment]
There is very likely a syntax error in your settings file that needs to be fixed.

**Comment by AndreaPi** [comment]
@aeschli I cannot check if there's a syntax error because I don't know the syntax of the settings file. When I click on <kbd>Open Settings</kbd>, VS Code shows a valid `json` file (ofc I removed the personal information):


```json
 {
    "telemetry.enableTelemetry": false,
    "editor.minimap.enabled": true,
    "printcode.paperSize": "a4Land",
    "workbench.colorTheme": "Monokai",
    "window.zoomLevel": 1.7,
    "workbench.statusBar.visible": true,
    "python.pythonPath": "/anaconda3/envs/test_cognite/bin/python",   
    "sshfs.configs": [
        {
            "host": XXXX,
            "name": XXXX,
            "password": XXXX,
            "username": XXXX
        }
    ],
    "http.proxy": XXXX,
    "terminal.integrated.rendererType": "dom",
    "editor.multiCursorModifier": "alt",
    "diffEditor.ignoreTrimWhitespace": false,
    "spellright.language": [
        "en"
    ],
    "spellright.documentTypes": [
        "markdown",
        "latex",
        "plaintext"
    ]
}
```

**Comment by aeschli** [comment]
If it's valid JSON then all is good.

I tried your settings and I'm not able to reproduce it on my machine. Maybe an issue in the workspace settings?
(`.vscode/settings.json`)
