### ISSUE TITLE
Doble icon on dock

### ISSUE THREAD

**Issue by laradvance** [microsoft/vscode#107102]
Issue Type: <b>Bug</b>

Doble icon on dock. Sometimes happen

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 5.7.7-amd64-desktop

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8109U CPU @ 3.00GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (12.24GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 8d5152a7-802f-49ce-b87e-b7e3a435192b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|deepin|
|XDG_CURRENT_DESKTOP|Deepin|
|XDG_SESSION_DESKTOP|deepin|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
material-theme|zhu|3.8.7

</details>

**Comment by aeschli** [comment]
Please describe in more details what you see and what you expect.
