### ISSUE TITLE
User Voice Issues to Migrate

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#10715]
| User Voice Request | Status |
| --- | --- |
| 1. [Vim-style Keybindings](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752447-vim-style-keybindings) | [vscode/issues/3600](https://github.com/Microsoft/vscode/issues/3600) |
| 2. [PHP IntelliSense](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752606-php-intellisense) | [extensions exist](https://marketplace.visualstudio.com/search?term=php&target=VSCode&sortBy=Relevance) |
| 3. [Auto Indent, Code Format, and Beautify Source Code](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752552-auto-indent-code-format-beautify-source-code) | [vscode/issues/4039](https://github.com/Microsoft/vscode/issues/4039) |
| 4. [Unity Integration](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752702-unity-integration) | [extensions exist](https://marketplace.visualstudio.com/search?term=unity&target=VSCode&sortBy=Relevance) |
| 5. [Minimap](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752789-minimap) | [vscode/issues/4865](https://github.com/Microsoft/vscode/issues/4865) |
| 6. [Haskell](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756542-haskell) | [extensions exist](https://marketplace.visualstudio.com/search?term=haskell&target=VSCode&sortBy=Relevance) |
| 7. [Auto close / rename tags like in VS](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8243982-auto-close-rename-html-tags-like-visual-studio) | [extensions exist](https://marketplace.visualstudio.com/search?term=auto%20close&target=VSCode&sortBy=Relevance) |
| 8. [Add file icons in Tree View (Sidebar)](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7800105-add-file-icons-in-the-treeview-sidebar) | [vscode/issues/211](https://github.com/Microsoft/vscode/issues/211) |
| 9. [ActionScript 3 Support](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7757226-actionscript-3-support) | [extensions exist](https://marketplace.visualstudio.com/search?term=action%20script%203&target=VSCode&sortBy=Relevance) |
| 10. [Haxe Support](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756341-haxe-support) | [extensions exist](https://marketplace.visualstudio.com/search?term=haxe&target=VSCode&sortBy=Relevance) |
| 11. [Integrate with TFS](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752390-integrate-with-team-foundation-server) | [extensions exist](https://marketplace.visualstudio.com/search?term=tfs&target=VSCode&sortBy=Relevance) |
| 12. [Wider Python Support](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752336-wider-python-support) | [extensions exist](https://marketplace.visualstudio.com/search?term=python&target=VSCode&sortBy=Relevance) |
| 13. [Open Multiple Folders at once](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756986-open-multiple-folders-at-once) | [vscode/issues/394](https://github.com/Microsoft/vscode/issues/396) |
| 14. [Support the D programming language](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7763160-support-the-d-programming-language) | extension candidate |
| 15. [MeteorJS Support](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7755360-meteorjs-support) | [extensions exist](https://marketplace.visualstudio.com/search?term=meteor&target=VSCode&sortBy=Relevance) |
| 16. [FTP Editing](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752729-ftp-editing) | [extensions exist](https://marketplace.visualstudio.com/search?term=ftp&target=VSCode&sortBy=Relevance) |
| 17. [HTML editing within .js / .ts code (e.g. in es6 template strings)](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/9660111-html-editing-within-js-ts-code-e-g-in-es6-temp) | https://github.com/Microsoft/vscode/issues/130 https://github.com/Microsoft/vscode/issues/2000 |
| 18. [Support Rust](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7755504-support-rust) | [extensions exist](https://marketplace.visualstudio.com/search?term=rust&target=VSCode&sortBy=Relevance) |
| 19. [Path/folder IntelliSense](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7875195-path-folder-intellisense) | https://github.com/Microsoft/vscode/issues/17331 |
| 20. [Ruby on Rails - like html.erb, more ruby support](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7758042-ruby-on-rails-like-html-erb-more-ruby-support) | extension candidate |
| 21. [Split both vertical and horizontal](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7755933-split-both-vertical-and-horizontal) | [vscode/issues/5911](https://github.com/Microsoft/vscode/issues/5911) |
| 22. [Support for Mercurial](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752945-support-for-mercurial) | extension candidate |
| 23. [Visual Studio Code Portable](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7760061-visual-studio-code-portable) | [vscode/issues/12401](https://github.com/Microsoft/vscode/issues/12401) |
| 24. [Add ability to prettify code](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8893870-add-ability-to-prettify-code) | [extensions exist](https://marketplace.visualstudio.com/search?term=prettify&target=VSCode&sortBy=Relevance) |
| 25. [Auto save temporary files](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756146-auto-save-temporary-files) | [vscode/issues/101](https://github.com/Microsoft/vscode/issues/101) |
| 26. [Run / Preview HTML files](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7757253-run-preview-html-files) | [extensions exist](https://marketplace.visualstudio.com/search?term=html%20preview&target=VSCode&sortBy=Relevance) |
| 27. [Enable more Git commands](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756014-enable-more-git-commands) | [extensions exist](https://marketplace.visualstudio.com/search?term=git&target=VSCode&sortBy=Relevance) |
| 28. [Auto Imports in TypeScript](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/13344849-auto-imports-in-typescript) | [vscode/issues/2635](https://github.com/Microsoft/vscode/issues/2635) |
| 29. [Graphical Git Merging like in VS](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/9009613-graphical-git-merging-like-in-visual-studio) | [vscode/issues/5770](https://github.com/Microsoft/vscode/issues/5770) |
| 30. [Scala Support](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7755597-scala-support) | [extensions exist](https://marketplace.visualstudio.com/search?term=scala&target=VSCode&sortBy=Relevance) |
| 31. [Add Elixir Support](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7764939-add-elixir-support) | [extensions exist](https://marketplace.visualstudio.com/search?term=elixir&target=VSCode&sortBy=Relevance) |
| 32. [SVN Support](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756200-svn-support) | [extensions exist](https://marketplace.visualstudio.com/search?term=svn&target=VSCode&sortBy=Relevance) |
| 33. [Save all files with ctrl+shift+s like in VS](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/9715599-use-ctrl-shift-s-to-save-all-files-like-visual-st) | [vscode/issues/11433](https://github.com/Microsoft/vscode/issues/11433) |
| 34. [Better Bracket Highlighting](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/10584708-bracket-highlighting) | [vscode/issues/12402](https://github.com/Microsoft/vscode/issues/12402) |
| 35. [Support for ReactJS](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8669974-i-strongly-recomend-add-support-react-js-intellise) | [extensions exist](https://marketplace.visualstudio.com/search?term=react&target=VSCode&sortBy=Relevance) |
| 36. [Function List View](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7778991-function-list-view) | [vscode/issues/5605](https://github.com/Microsoft/vscode/issues/5605) |
| 37. [Aurelia Support and Integration](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8017794-add-aurelia-support-and-integration) | [extensions exist](https://marketplace.visualstudio.com/search?term=Aurelia&target=VSCode&sortBy=Relevance) |
| 38. [Drag 'n Drop Selections](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7763958-drag-n-drop-selections) | [vscode/issues/1046](https://github.com/Microsoft/vscode/issues/1046) |
| 39. [Lucee + CFScript (CFML) Support](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7921458-lucee-cfscript-cfml-support) | [extensions exist](https://marketplace.visualstudio.com/search?term=CFML&target=VSCode&sortBy=Relevance) |
| 40. [Integrated REST Client](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8473300-integrated-rest-client) | [extensions exist](https://marketplace.visualstudio.com/search?term=REST&target=VSCode&sortBy=Relevance) |
| 41. [Faster Start Time](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7755435-faster-start-time) | ongoing priority |
| 42. [Detachable Split View](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8279298-detachable-split-view) | [vscode/issues/367](https://github.com/Microsoft/vscode/issues/367) |
| 43. [Chrome OS Support](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7773537-chrome-os-support) | [vscode/issues/1031](https://github.com/Microsoft/vscode/issues/1031) |
| 44. [sass, css, and less Format Code](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7908831-sass-css-and-less-format-code) | [extensions exist](https://marketplace.visualstudio.com/search?term=css%20format&target=VSCode&sortBy=Relevance) |
| 45. [Remote Debugging](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7872216-remote-debugging) | [feature exists](https://code.visualstudio.com/docs/editor/debugging) |
| 46. [Julia Language Support](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7763118-julia-language-support) | [extensions exist](https://marketplace.visualstudio.com/search?term=julia&target=VSCode&sortBy=Relevance) |
| 47. [Add Language Support for Groovy](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752468-add-language-support-for-groovy) | extension candidate |
| 48. [Django](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756389-django) | extension candidate |
| 49. [Add Support for Dart](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7778799-add-support-for-dart) | [extensions exist](https://marketplace.visualstudio.com/search?term=dart&target=VSCode&sortBy=Relevance) |
| 50. [Live HTML, CSS Support](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8432782-live-html-css-for-web-developer) | [vscode/issues/12080](https://github.com/Microsoft/vscode/issues/12080) |

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@waderyan if you can include in your list:
51. [Autocomplete suggestion base on word completion](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8757571-autocomplete-suggestion-base-on-word-completion). I think it's similar with #7552.

**Comment by formulahendry** [comment]
For [Auto close / rename tags like in VS](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/8243982-auto-close-rename-html-tags-like-visual-studio), extensions exist: [Auto Close Tag ](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) and [Auto Rename Tag ](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag)

**Comment by misterhtmlcss** [comment]
Also [Run / Preview HTML files](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7757253-run-preview-html-files) has 2 really good extensions; I've tried both and I didn't complain, so I wouldn't spend time there either.

**Comment by waderyan** [comment]
Cool. Thank you for the feedback.

**Comment by jtlivio** [comment]
VSCode won't start on LINUX if you are using a Linux **xrdp** session (Debian based), can someone reproduce this?

**Comment by waderyan** [comment]
Hey @jtlivio thanks for your comment, however this isn't a great place. Please see these [guidelines](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md) and open a new issue.

**Comment by jtlivio** [comment]
@waderyan, I realize after post, Thanks.

**Comment by hassansw** [comment]
I request that can you include us of html snippets and css class completion in *.php file rather than changing file extensions every time like in sublime or atom

**Comment by waderyan** [comment]
@hassansw please open an issue to describe your request. Pease see these [guidelines](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md).

**Comment by ceyhunkerti** [comment]
30. says scala extension exists.

Thanks to author Iliya, but it just supports keyword highlighting and far from being used as scala extension. Supporting language like scala is a hard thing, since it has a complex type system compared to other languages. Even jetbrains has some issues on scala support. I don't now to whom we should ask for scala support, maybe we can team up.

**Comment by shanalikhan** [comment]
I would really like some extension that can make code to use windows bash libraries.

like i want code to compile the python code using ubuntu libraries that are installed in windows bash and debug the code using windows bash
So python developers that are using python in ubuntu can switch to Windows 10 easily and use windows bash.
@waderyan

**Comment by waderyan** [comment]
Closing as these have all been successfully migrated.
