### ISSUE TITLE
Caches of view containers, views and viewlets are not getting cleared

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#107109]
When I checked my view container, views and viewlet locations caches, I see there are lot of generated view containers which are redundant and not cleared. They are not getting cleared even after resetting all view locations 

- Move views, view containers around, say,
  - move view to another view container
  - move view to its own new view container

- Reset all view locations

Open dev tools console and run the VS Code command `Log Storage Database Contents`
Cached view container, views and viewlet locations are not cleared.

**Comment by connor4312** [comment]
I'm not sure exactly what to look for here. @sbatten are you able to verify this?

**Comment by rzhao271** [comment]
Removing verified label because not sure whether I verified the issue properly.
Before resetting the view locations, and after resetting the view locations, the size of the storage database stayed the same in both cases.

**Comment by sandy081** [comment]
To verify:

- Open VS Code using fresh user data dir and open VS Code repo
- Move time line view to sidebar, Move outline views to panel.
- Run `Developer: Log Storage Database Contents`
- Check following keys in global storage
  - `workbench.activity.pinnedViewlets2` - Generated container (id containing UUID) exists
  - `workbench.activity.pinnedPanels` - Generated container (id containing UUID) exists
  - `views.cachedViewContainerLocations` - Has two entries
  - `views.cachedViewPositions` - Has two entries
  - There are two storage keys for generated containers `workbench.views.service.sidebar.${uuid}.state.hidden`
- Run the command `Reset View Locations`
- Make sure above two views got reset to their original locations
- Check following keys in global storage
  - `workbench.activity.pinnedViewlets2` - Does not container generated containers
  - `workbench.activity.pinnedPanels` - Does not container generated containers
  - `views.cachedViewContainerLocations` - Has **NO** entires
  - `views.cachedViewPositions` - Has **NO** entires
  - There are **NO** storage keys for generated containers `workbench.views.service.sidebar.${uuid}.state.hidden`

**Comment by bpasero** [comment]
@sandy081 I cannot find `workbench.activity.pinnedPanels` after running the command, can you check your stepsß

**Comment by rzhao271** [comment]
It was `workbench.panel.pinnedPanels`
