### ISSUE TITLE
The extension host has terminated unexpectedly.

### ISSUE THREAD

**Issue by ryo1090** [microsoft/vscode#107131]
必要なデータが送信するには大きすぎたため、クリップボードに書き込みました。貼り付けてください。
I wrote it to the clipboard because the required data was too large to send. please paste.

**Comment by aeschli** [comment]
Please open the developer tools (Help > Toggle Developer Tools) and check the console for more information.

Also, please run with all extensions disabled and and see if the problem reproduces.
