### ISSUE TITLE
"Seed with nearest word" is always activated even when deactivated from settings.

### ISSUE THREAD

**Issue by bojomojo** [microsoft/vscode#107144]
- VSCode Version: 1.49.1
- OS Version: Mac OS Catalina

Steps to Reproduce:

1. Set "Seed With Nearest Word" to disabled
2. Double click on a function name in the code say "function1", run: "editor.action.moveSelectionToNextFindMatch" or "editor.action.nextSelectionMatchFindAction"
3. On the found part, move the cursor and click beside any other string say "string1", without choosing it (since the "Seed with nearest word" is disabled, I understand VSCode shall still be searching for "function1".
4. run: "editor.action.moveSelectionToNextFindMatch" or "editor.action.nextSelectionMatchFindAction"
Problem: VSCode will go to the next occurence of "string1" and not "function1"

Example:

```
Void function1( type arg1,
                           type string1 );
```

The first run of the command would return the next occurence of "function1". The second run would however return the next occurence of "string1". Eventhough it was not selected.

**Comment by aeschli** [comment]
`search.seedWithNearestWord` is an option from search (in files), which not apply to find/replace in the editor.

**Comment by bojomojo** [comment]
So find in editor forcefully replaces the selection?

**Comment by WEGFan** [comment]
It seems that vscode thinks you selected the word under the caret, even you actually not selecting it.

**Comment by roblourens** [comment]
The first command is explicitly based on selection. I am not sure how the second one works. But the setting is not relevant here. I think the command you want would be F3 (find next)
