### ISSUE TITLE
Format on save mode: modifications caused invalid formatting in JSON document

### ISSUE THREAD

**Issue by vivektiwary** [microsoft/vscode#107151]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

1. Paste any valid json with array of objects
2. Save it
3. Vscode will format `{ }` with `({ })`

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|-psn_0_6206955 --crash-reporter-id 6d76b1fb-143f-47b3-a162-06c182403bec|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.3
All-Autocomplete|Ati|0.0.23
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.8
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.6.0
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
go|gol|0.17.0
duplicateselection|kka|1.0.1
vscode-docker|ms-|1.6.0
python|ms-|2020.8.109390
cpptools|ms-|1.0.0
vscode-typescript-next|ms-|4.1.20200920
vscode-extension-auto-import|Nuc|1.4.3
vscode-boot-dev-pack|Piv|0.0.8
vscode-manifest-yaml|Piv|1.22.0
vscode-spring-boot|Piv|1.22.0
java|red|0.67.0
vscode-xml|red|0.13.0
vs-code-prettier-eslint|rve|0.3.2
jestRunIt|ves|0.4.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-spring-boot-dashboard|vsc|0.1.10
vscode-spring-initializr|vsc|0.5.0
vim|vsc|1.16.0
vscode-js-console-utils|wht|0.7.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by aeschli** [comment]
Does this reproduce with extensions disabled?

**Comment by vivektiwary** [comment]
Hi @aeschli, 
No it is not happening when i disable prettier. So it might be related to prettier.
