### ISSUE TITLE
Huge CPU usage when idle

### ISSUE THREAD

**Issue by estomagordo** [microsoft/vscode#107176]
We have written the needed data into your clipboard because it was too large t
Issue Type: <b>Bug</b>

1) Open VS Code

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.54GB free)|
|Process Argv|--crash-reporter-id 5e376644-1ef3-4ca6-b404-e27f5604a9b3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.9.0
vscode-database|baj|2.2.3
vscode-perl|cfg|1.18.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.8
githistory|don|0.6.9
gitlens|eam|10.2.2
json-tools|eri|1.0.2
git-project-manager|fel|1.7.1
chocolatey-vscode|gep|0.7.2
vscode-test-explorer|hbe|2.19.1
latex-workshop|Jam|8.13.2
vscode-python-test-adapter|lit|0.5.0
MagicPython|mag|1.1.0
code-coverage|mar|1.2.3
csharp|ms-|1.23.2
python|ms-|2020.8.109390
remote-wsl|ms-|0.44.5
powershell|ms-|2020.6.0
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.10
vscode-coconut|Qwe|0.0.1
vscode-zipexplorer|sle|0.3.1
vscode-icons|vsc|11.0.0
markdown-all-in-one|yzh|3.3.0

</details>
o send. Please paste.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen if you launch with all extensions disabled? If not, try to discover which extension is causing the issue, then report it to the extension author.
