### ISSUE TITLE
Language-specific user settings are not overwritten by language-independent workspace settings

### ISSUE THREAD

**Issue by dominic-simplan** [microsoft/vscode#107184]
- VSCode Version: 1.49.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. In the user settings, specify a default formatter for a specific language, e.g.
```
"[typescript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
},
```
2. In the workspace settings, specify a default formatter for all languages:
```
"editor.defaultFormatter": "esbenp.prettier-vscode"
```

Actual behaviour: Typescript files are formatted with "vscode.typescript-language-features".
Expected behaviour: Typescript files are formatted with "esbenp.prettier-vscode", as this is defined in the workspace settings which are shared by the team.

This probably applies to all settings which can be set depending on a language. If I explicitly set a language-independent option in the workspace settings, it should not be overwritten by a language-dependent setting from the user settings.

Not sure if this is a bug or if there are specific reasons it is implemented the way it currently is? 

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
It is expected and designed. Language settings are given more priority as they are specific to a language.

**Comment by dominic-simplan** [comment]
This means if I intend to share the workspace settings I should not use the "editor.defaultFormatter" option as it might get overridden by the language-specific user settings.
Might be worth to mention this in the documentation? Currently it only says that workspace settings override user settings.

**Comment by sandy081** [comment]
> Currently it only says that workspace settings override user settings.

Actually this is true, if you define the language key in workspace settings, this will override the same from user settings. I will update the documentation of language specific settings to make it clear - https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings
