### ISSUE TITLE
Markdown Heading Editor Folding Not Working

### ISSUE THREAD

**Issue by anishmittal2020** [microsoft/vscode#107130]
- VSCode Version:1.49.1
- OS Version:Ubuntu 20.04.1

Steps to Reproduce:

1. The markdown folding as illustrated in **[[folding] Add code folding for markdown based on heading level · Issue #3347 · microsoft/vscode](https://github.com/microsoft/vscode/issues/3347)**, doesn't work. I don't get the option to fold it

Does this issue occur when all extensions are disabled?:  Yes

**Comment by mjbvz** [comment]
![Sep-21-2020 09-54-46](https://user-images.githubusercontent.com/12821956/93797017-86c4f900-fbf0-11ea-91f9-1eea36f82da1.gif)


Please markdown code that demonstrates the problem

**Comment by anishmittal2020** [comment]
@mjbvz 

I opened the following markdown file after disabling all extensions

![image](https://user-images.githubusercontent.com/42092626/95373762-ba38a080-08dd-11eb-907b-48f07c20d68d.png)

# Observation

We can see that we don't get the `V` symbol for headings, so we are  unable to minimize it.


# Reference

Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:23:33.049Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic

**Comment by mjbvz** [comment]
Please share the text of that file

**Comment by anishmittal2020** [comment]
```markdown
---
title: 'Sewing'
subtitle:
author: 'Anish Mittal'
date: 'Wednesday, October 07, 2020 - 18:23'
keywords: ['']
ratings: ['']
reviews: ''
---

# Introduction

- [How to Sew by Hand - YouTube](https://www.youtube.com/watch?v=ZvzMMcKHVR4)
- [Hand sewing 2 Sewing on a button - YouTube](https://www.youtube.com/watch?v=MjmUaWkzF-I)
  - Excellent!
- [How to Sew a Zipper, TWO ways - YouTube](https://www.youtube.com/watch?v=oHDDhUzIXPY)
  - Nice! But for special use.

## Summary

-

# Bibliography

-

---
```

**Comment by mjbvz** [comment]
That example works fine for me:

<img width="450" alt="Screen Shot 2020-10-12 at 4 36 47 PM" src="https://user-images.githubusercontent.com/12821956/95799324-271ab480-0ca9-11eb-9957-7f252f1b7a17.png">

Did you disable the built-in `markdown language features` extension?

**Comment by mjbvz** [comment]
Or actually, either you've disabled the built-in extension or have changed the `"editor.foldingStrategy"` setting to be indentation based instead of smart

**Comment by kmatarese** [comment]
Interestingly I'm having a very similar problem using [Org Mode](https://vscode-org-mode.github.io/vscode-org-mode/) after just updating VSCode. It no longer recognizes the asterisks as the headings that should be folded, and will only fold lines that start with a dash like the OP showed [here](https://github.com/microsoft/vscode/issues/107130#issuecomment-705124717).

```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.0.0
```

**Comment by robgrace** [comment]
I struggled with this too for a while, even after checking the "Editor:Folding" setting, which was mysteriously off by default.  But it appears that *some* folding arrows only appear when you **mouse over** the gutter (like Markdown), but other arrows are persistent (like list-level folding).
