### ISSUE TITLE
First NumPad+Enter does not produce new line when switching from diff to normal editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10712]
I have this issue since a couple of months and only now realized how to reproduce. So I do not think it is related to the keybinding service context change we did:
- open a diff from the git viewlet and copy a line from the right hand side
- use quick open to jump back to another editor that is not a diff
- press Enter
  => you do not get a new line

**Comment by bpasero** [comment]
I updated the title, I think this only happens for me when I use the Enter on the numpad keyboard. I hope this is not some weirdness with my Mac keyboard and Mac OS, maybe you try to reproduce on Windows?

**Comment by alexandrudima** [comment]
hmm, I cannot reproduce:
![10712](https://cloud.githubusercontent.com/assets/5047891/17852995/6b85fa22-686a-11e6-9154-26735d7346bf.gif)

**Comment by bpasero** [comment]
@alexandrudima let's debug on my Mac tomorrow, might be very specific to the OS and keyboard.

**Comment by alexandrudima** [comment]
@bpasero Adding to November so we don't forget about this.

**Comment by bpasero** [comment]
I am fine closing this given the work we did in this area.
