### ISSUE TITLE
Editor breaks after CTRL-f

### ISSUE THREAD

**Issue by lairdrt** [microsoft/vscode#107135]
Issue Type: <b>Bug</b>

I am editing python code (not using python add-on), single pane, standard window layout. When I type CRTL-f to find an item on the page, I can type in the text to search for just fine. BUT, when I then use up/dn arrows to find text, and then go to edit text, the editor breaks and I can no longer use arrow keys, home key, end key, nor backspace key - the keys simply don't respond at all after this happens. Does not always occur, inconsistent. But when this does occur, I have to close the file, and then open the file again from the Explorer window and repeat process - this usually clears the error and the normal CTRL-f, find, edit sequence works. Very annoying, and slowing me down.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (10.50GB free)|
|Process Argv|--crash-reporter-id 32170359-0eeb-401e-bbde-b38577b747df|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sshfs|Kel|1.18.3
python|ms-|2020.8.109390

</details>

**Comment by alexdima** [comment]
@lairdt Can you please follow the steps at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting and see what is going on when these keybindings stop working for you? You can then share the log or portions of it here.

**Comment by lairdrt** [comment]
That's a lot of crap just to make the keyboard work again - this recently broke with one of the last updates…

**Comment by alexdima** [comment]
Please comment out your `keybindings.json`.
