### ISSUE TITLE
`editor.codeActionsOnSave` Occasionally Still Runs Even If Configuration is Empty

### ISSUE THREAD

**Issue by FloatingSunfish** [microsoft/vscode#107159]
- VSCode Version: 1.49.1
- OS Version: Windows 10 64-bit

**_Extensions installed:_**
1. [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks)
2. [Bracket Pair Colorizer 2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2)
3. [C#](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp)
4. [Clock in status bar](https://marketplace.visualstudio.com/items?itemName=Compulim.vscode-clock)
5. [Debugger for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug)
6. [EditorConfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)
7. [Go](https://marketplace.visualstudio.com/items?itemName=golang.Go)
8. [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack)
9. [Java Test Runner](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test)
10. [Language Support for Java(TM) by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java)
11. [Markdown All In One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)
12. [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)
13. [Maven for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven)
14. [NuGet Package Manager](https://marketplace.visualstudio.com/items?itemName=jmrog.vscode-nuget-package-manager)
15. [Project Manager for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency)
16. [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree)
17. [Visual Studio IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode)

**_Steps to Reproduce:_**

**_Language Used While Encountering the Issue:_** Golang 1.15.2

1. Add the following to your VS Code configuration file:

        "editor.codeActionsOnSave": {}

2. Make some changes to your project and save them. Occasionally, even when the setting has been configured to be empty, you get a message saying `Saving 'your_file.go': Getting code actions from "Go" (configure).`

Note that the issue happens intermittently and for seemingly no reason. Despite the setting being configured to empty, the feature is firing up occasionally upon saving.

The change that triggers the issue the most on my side is in Golang. Changing the package to anything and then saving triggers the issue (e.g. from `package main` to `package mainz`).

**_Sidenote 1:_** Configuring the settings to use `null` instead of `{}` also does not resolve the issue.

**_Sidenote 2:_** Adding language-specific configurations with either `null` or `{}` also does not resolve the issue:

    "[go]": {
        "editor.codeActionsOnSave": {}
    }

**_Sidenote 3:_** Completely removing the setting from the configurations file also does not resolve the issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by FloatingSunfish** [comment]
If there is a configuration to disable `editor.codeActionsOnSave`, please let me know so I can disable it as I have no use for this feature.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by FloatingSunfish** [comment]
@jrieken I have added all the details that I could find. I also updated the issue steps and details.
Although part of the issue's nature is its seeming randomness in occurrence. Thanks!

**Comment by jrieken** [comment]
> Saving 'your_file.extension': Getting code actions from "your_language" (configure).

A good start would be to name the language and extension

**Comment by FloatingSunfish** [comment]
@jrieken Added these details. Thanks!
Let me know if I missed anything else.

**Comment by jrieken** [comment]
There is only a single occurrence of that message and that's guarded behind [ch](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/codeEditor/browser/saveParticipants.ts#L283)[ecks](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/codeEditor/browser/saveParticipants.ts#L309) for the setting being set. If it says "occasionally" or "random" it means that there are no crisp repo steps and I suggest that you investigate into coming up with such steps first. E.g minimal steps, minimal set of extensions that one needs, minimal sources etc

**Comment by FloatingSunfish** [comment]
@jrieken Alright, I'll look more into that. Thanks!

**Comment by FloatingSunfish** [comment]
@jrieken From the two code links you provided, I see that there are checks to see if the configuration is either empty or present in the configuration file (please correct me if my interpretation is wrong).

What puzzles me is that even when I remove `editor.codeActionsOnSave` from my configuration file, the code says it should be returned as `undefined`. However, the feature is still firing up for some reason.

Oh, and I also added some repro notes for Golang. Although sadly they don't reproduce the issue too much. This issue is quite puzzling.
