### ISSUE TITLE
Error when try to update vscode gopls plugin

### ISSUE THREAD

**Issue by leosimoesp** [microsoft/vscode#107166]
[Info  - 12:55:52 PM] Connection to server got closed. Server will restart.
[Trace - 12:55:52.979 PM] Sending request 'initialize - (0)'.
Params: {"processId":38514,"clientInfo":{"name":"vscode","version":"1.49.1"},"rootPath":"/","rootUri":"file:///","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]}},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}},"contextSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true}},"window":{"workDoneProgress":true}},"initializationOptions":{},"trace":"off","workspaceFolders":[{"uri":"file:///","name":""}]}

panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 103 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	/home/leonardo/go/bin/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:58 +0x233
golang.org/x/tools/internal/lsp/debug.section(0xebd320, 0xc0002f8210, 0x0, 0xd90c72, 0x7, 0xc0002d4f28)
	/home/leonardo/go/bin/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:69 +0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xed0e40, 0xc000458f00, 0xebd320, 0xc0002f8210, 0x1, 0x0)
	/home/leonardo/go/bin/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:52 +0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc000434d20, 0xed0e40, 0xc000458f00, 0xc0002c0000, 0x0, 0x0, 0x0)
	/home/leonardo/go/bin/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/general.go:87 +0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc000434d20, 0xed0e40, 0xc000458f00, 0xc0002c0000, 0xc0002c0000, 0x0, 0x0)
	/home/leonardo/go/bin/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/server_gen.go:108 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xed0e40, 0xc000458f00, 0xee49c0, 0xc000434d20, 0xc0002bc240, 0xed1080, 0xc000458e80, 0x0, 0xebeb60, 0xc0002be000)
	/home/leonardo/go/bin/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/tsserver.go:235 +0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xed0e40, 0xc000458f00, 0xc0002bc240, 0xed1080, 0xc000458e80, 0xbc16b9, 0x1320a80)
	/home/leonardo/go/bin/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/protocol.go:63 +0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xed0e40, 0xc000458f00, 0xc0002bc240, 0xed1080, 0xc000458e80, 0x0, 0x0)
	/home/leonardo/go/bin/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/lsprpc/lsprpc.go:557 +0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xed0e40, 0xc000458f00, 0xc000454b00, 0xed1080, 0xc000458e80, 0x406305, 0xc00003c9b8)
	/home/leonardo/go/bin/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:35 +0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00003cf60, 0xc0004745a0, 0xc00045e160, 0xed0e40, 0xc000458f00, 0xc000454b00, 0xed1080, 0xc000458e80)
	/home/leonardo/go/bin/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/leonardo/go/bin/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:100 +0x173
[Error - 12:55:52 PM] Connection to server got closed. Server will not be restarted.

**Comment by subsr97** [comment]
I'm facing the same issue.
@leosimoesp Were you able to find the solution?

**Comment by subsr97** [comment]
https://github.com/golang/go/issues/41701
