### ISSUE TITLE
Rust Token/Scope Resolution Incorrect

### ISSUE THREAD

**Issue by braxtons12** [microsoft/vscode#107173]
VSCode Version: Insiders 1.50.0
OS Version: Windows 10 1903

Previously Reported this in #107043 , but was asked to split it up per language

After updating from Insiders 1.49 to Insiders 1.50, token resolution is incorrect for Rust code, causing syntax highlighting to be incorrect. It's not nearly as bad as the c++ issues in the mentioned issue, but still incorrect.

For example, according the Editor Tokens and Scopes Inspector procedural macros are being picked up as function attributes.

Example Rust code causing the problem:
https://pastebin.com/PTQ9GNqu

Example images showing the Token Inspector:
![rusttokensexample](https://user-images.githubusercontent.com/28696801/93801245-53419900-fc07-11ea-890b-c375c6e333ca.PNG)

I'm using:
rust-analyzer

**Comment by alexr00** [comment]
@braxtons12 I'm not familiar with Rust, but I went back to VS Code version 1.41.1 and I still see `meta.attribute.rust`. `entity.name.function.attribute.rust` looks like a more specific scope, and I wouldn't expect that to break anything.

![image](https://user-images.githubusercontent.com/38270282/94543603-8d83e980-024a-11eb-8653-f9b1e7beb2d2.png)
