### ISSUE TITLE
Web: terminal looks blurry (Safari)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107138]
Running `yarn web` and opening the integrated terminal it appears very blurry:

![image](https://user-images.githubusercontent.com/900690/93734816-1790da00-fbdb-11ea-8973-10a6c9db0335.png)

**Comment by rebornix** [comment]
I'm not able to reproduce this issue on Safari anymore.

**Comment by Tyriar** [comment]
@bpasero did you have zoomLevel set here as that's the main thing that complicates this.

**Comment by bpasero** [comment]
Yes, I am always zooming in.

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/2662

**Comment by usernamehw** [comment]
Duplicate of #97682 ?
