### ISSUE TITLE
Whitespaces are rendered incorrectly when changing font size

### ISSUE THREAD

**Issue by AriusX7** [microsoft/vscode#107122]
- VSCode Version: Version: 1.49.1
- OS Version: macOS Catalina 10.15.6

Steps to Reproduce:

1. Open Visual Code and set the font to Operator Mono Ssm or Dank Mono.
2. Enable "Render Whitespace".
3. Change the font size.

The whitespaces appear as weird characters.
![Screenshot 2020-09-21 at 00 54 21](https://user-images.githubusercontent.com/48966598/93720186-2066b900-fba5-11ea-9866-a98b0ef0f431.png)

If you decrease the font size to the original size, whitespaces are rendered normally. If you restart VSCode with a different font size and broken whitespace rendering, the rendering is fixed. However, it breaks again if you change font size.

I've tried a lot of fonts but could only reproduce this with Operator Mono Ssm and Dank Mono.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
Does this reproduce when quitting and then launching code with `--disable-features=LayoutNG` ?

**Comment by AriusX7** [comment]
I got the following error when running `code --disable-features=LayoutNG`:
`Warning: 'disable-features' is not in the list of known options, but still passed to Electron/Chromium.`

I'm not sure if that's what you meant so I tried running `open -a "Visual Studio Code" --args --disable-features=LayoutNG` as well, and I could reproduce the issue in the VSCode window that opened.

**Comment by AriusX7** [comment]
Closing as I am unable to reproduce this issue on version `1.53.0`.
