### ISSUE TITLE
`Import cost` extension flickering issue on `Auto save on`.

### ISSUE THREAD

**Issue by sahilrajput03** [microsoft/vscode#107115]
![import cost flickerting](https://user-images.githubusercontent.com/31458531/93718090-6a48a280-fb97-11ea-808d-c1b9928ae4b1.gif)
**NOTE: This happens only when I keep auto save on.**
INFO: I'm facing this issue with import cost extension, but as instructed in the `issue template`, **I tested with vscode insiders, and I don't face this issue**, so should i just shift to insiders' or is this gonna be solved in some days or next month?
 
Thanks in advance, you guys are amazing!! 
~ Sahil Rajput

**Comment by gjsjohnmurray** [comment]
Insiders gives you early access to what's likely to be in next Stable. Releases of Stable typically happen once a month, unless critical issues require a recovery release (e.g. 1.49.1)

/question
