### ISSUE TITLE
Double clicking commit message to select words changes the active pane to the Editor pane

### ISSUE THREAD

**Issue by vexx32** [microsoft/vscode#107114]
- VSCode Version: 1.49.1
- OS Version: Windows 10 2004

Steps to Reproduce:

1. Open any workspace with an active Git repository
1. Make changes to a file and save
1. Open the Source Control UI
1. Select the modified file to open the diff viewer (this will also work for already-staged files)
1. Enter a commit message (length doesn't matter, but at least a few words)
1. Try to select individual words by double clicking
1. Note that roughly 50-80% of the time the word will be selected, but the selection is faded, and the active cursor is now in the editor view displaying the diff instead; typing to attempt to overwrite the selected word instead makes changes to the file.

Note: this is _really_ annoying 😅 

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Woah I can repro, this does **not** look like a fun issue to fix. 😆

**Comment by vexx32** [comment]
Sorry, what more information was needed? I'd really like this fixed, this is super annoying to deal with 😅
