### ISSUE TITLE
Keyboard shortcut for Quick Open Recent reopens previous folder

### ISSUE THREAD

**Issue by gautams3** [microsoft/vscode#107197]
Issue Type: <b>Bug</b>

0. Open some folder in VSCode
1. Add a key binding for `workbench.action.quickOpenRecent`. I used Ctrl+Shift+8 to avoid collisions with other bindings
2. Press the key binding you just added
3. You see the quickOpenRecent window open up waiting for your input
4. Almost immediately, it disappears and VSCode reopens the previous open folder (same as File -> Open Recent -> 2nd most recent item)

If you clear the cache of recent items, you see the window from step 3 appear and disappear.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 5.4.0-45-generic snap

**Comment by chrmarti** [comment]
@bpasero This is opened with quicknav enabled.

**Comment by bpasero** [comment]
```json
{
	"key": "Ctrl+Shift+8",
	"command": "workbench.action.openRecent"
}
```
