### ISSUE TITLE
Source Control Views and more actions 3 dots icon touchy to click

### ISSUE THREAD

**Issue by albu77** [microsoft/vscode#107113]
Issue Type: <b>Bug</b>

Difficult sometimes to get the dropdown menu when  click on the 3 dots icon, like if the area was more or less disabled.
Same thing on my wife computer under windows10 and different screen dimensions

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|5.98GB (0.21GB free)|
|Process Argv|--file-uri file:///d%3A/electron/GestionSiteRestau/GestionSiteRestau.code-workspace --crash-reporter-id dd40267d-ef67-4c64-bd34-20e7d4f0cbbf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
vscode-custom-css|be5|3.0.10
css-compressor|bes|0.0.2
copy-without-formatting|bma|0.2.0
open-html-in-browser|cod|0.1.21
vscode-great-icons|emm|2.1.47
json-tools|eri|1.0.2
vscode-todo-plus|fab|4.17.1
vscode-firefox-debug|fir|2.9.0
vscode-mysql|for|0.4.0
todo-tree|Gru|0.0.177
beautify|Hoo|1.5.0
tasks-context|jsa|1.0.0
typings-autoinstaller|jvi|1.2.0
gitexplorer|mfe|1.0.1
gitignore|mic|1.0.1
vscode-language-pack-fr|MS-|1.46.5
debugger-for-chrome|msj|4.12.8
sqltools|mtx|0.23.0
live-server-preview|neg|0.1.4
git-file-history|pom|1.0.1
markdown-preview-enhanced|shd|0.5.12
html5-boilerplate|sid|1.0.3
addDocComments|ste|0.0.8
markdown-all-in-one|yzh|3.1.0
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen if you reload with all extensions disabled?

**Comment by albu77** [comment]
Yes same thing with reload without extensions

**Comment by joaomoreno** [comment]
Can you show us a screenshot showing the exact problem area?

**Comment by albu77** [comment]
![image](https://user-images.githubusercontent.com/624802/94292178-e3137a00-ff5c-11ea-8253-0dbe86d7976d.png)

It's not doing it always. When the problem is there We really need to click on some accurate area (the dots) besides when it works there is a normal area around the dots where the click is active. I can't find any relation with other gestures and on both machine... Really strange

**Comment by joaomoreno** [comment]
That area is exactly the same size as the area of the icons next to it. The area is 32x35 pixels, which is quite a lot. Can you show me a screen recording of the issue?
