### ISSUE TITLE
Feature Request: Customisation Bundles

### ISSUE THREAD

**Issue by MeirionHughes** [Microsoft/vscode#10710]
Support switching between preset customisations of
- extensions
- layout
- workspace settings
- custom buttons (#10709)

**why?** 
for one, it would allow all front-end developers to make an opinionated IDE for development of their platform.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
