### ISSUE TITLE
VS Code Fails Python Command due to Unactivated Conda Env in In Terminal

### ISSUE THREAD

**Issue by marcusobrien** [microsoft/vscode#107194]
- VSCode Version: 1.49.1 
- OS Version: Windows 10
- Python 3.6.12
- Conda 4.8.4

VS Code Extensions
- Anaconda Extension Pack : 1.0.1
- Python 2020.8.109390
- Profile Python with PyVmMonitor 0.0.3

Steps to Reproduce:

1. <Shift Control P> run the command
2. profile python module with PyVmMonitor 

The conda environment is being activated AFTER the command to run the python profiler ! I do not have an OS version of Python installed, only pythons installed in conda environments. I do this so that I can tell exactly where python, pip and conda and running etc. 

Microsoft Windows [Version 10.0.19041.508]
(c) 2020 Microsoft Corporation. All rights reserved.

D:\Projects19\repos\mine\finance\IntelStockScraper>python "f:/Program Files/Brainwy/PyVmMonitor 2.0.0/public_api/pyvmmonitor/__init__.py" --profile=lsprof d:/Projects19/repos/mine/finance/IntelStockScraper/StockMarketPrediction.py
'python' is not recognized as an internal or external command,
operable program or batch file.

D:\Projects19\repos\mine\finance\IntelStockScraper>C:\ProgramData\Anaconda3\Scripts\activate Py36Tf115CPU_GOLD

(Py36Tf115CPU_GOLD) D:\Projects19\repos\mine\finance\IntelStockScraper>
(Py36Tf115CPU_GOLD) D:\Projects19\repos\mine\finance\IntelStockScraper>
(Py36Tf115CPU_GOLD) D:\Projects19\repos\mine\finance\IntelStockScraper>python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

NOTE running from VS code (hitting F5) sometimes results in this erro - hitting F5 a few more times without closing/changing anything else will eventually work and run the python script 

import nump as np

Exception has occurred: ImportError

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.6 from "C:\Users\marcu\.conda\envs\Py36Tf115CPU_GOLD\python.exe"
  * The NumPy version is: "1.19.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: The specified module could not be found.
  File "D:\Projects19\repos\mine\finance\IntelStockScraper\blank.py", line 31, in <module>
    import numpy as np

Does this issue occur when all extensions are disabled?: Yes/No
It needs the python extension, so I didnt try this.

**Comment by rzhao271** [comment]
This sounds like a race condition, and it also sounds like it has to do with the Python extension. Can you try filing an issue at https://github.com/Microsoft/vscode-python?
