### ISSUE TITLE
Unrelated debugging extensions activated during debug sessions

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/vscode#107178]
Found discussing with @amyhartwig, @nalogan, and @chrisdias.

When debugging various project types, it appears that all extensions that support debugging are activated. This is not ideal in the presence of lots of extensions that might need to get activated at once. This might also affect activation events that extension authors keep track of.

#88849 might be related, as it relates to Microsoft-authored extensions that need to be switched to newer APIs.

If we can get someone from the engineering team to determine whether this is working as intended or a bug, that would be great.

**Comment by weinand** [comment]
VS Code debugging tries hard not to activate debug extension unnecessarily. But this requires that debug extensions use the correct activation events.

In order to investigate this issue we need additional information and reproducible steps:
- What debug extensions get activated unnecessarily?
- What are the steps that result in unnecessarily activation?

**Comment by DanielRosenwasser** [comment]
Looking at other chats, Naomi, explained it in the following way.

> The reason is VS Code needs to activate all debuggers to collect the configurationProviders dynamically registered via API for launch configuration generator, and calls the corresponding configurationProvider according to the debugging language.

https://github.com/microsoft/vscode-java-debug/issues/238

https://github.com/microsoft/vscode-python/issues/9557

Specifically, the one I'm interested in is the built-in TypeScript/JavaScript Language Features extension.

**Comment by weinand** [comment]
"configurationProviders" are only needed in the initial (and rare) case where no launch.json exists and "unspecific" F5 debugging is requested and multiple debug extensions re installed. After a launch.json has been created, "configurationProviders" are never requested again.
