### ISSUE TITLE
Terminal does not initialize (command not found: ...) 

### ISSUE THREAD

**Issue by tillkolter** [microsoft/vscode#107280]
- VSCode Version:
- OS Version: Mac OS Catalina 10.15.6

Steps to Reproduce:

1. Launch VS Code
2. Open Terminal

Does this issue occur when all extensions are disabled?: Yes

----

It seems that the terminal in VS Code does not load the path correctly. Very basic commands like sed, git, asf. are not found any more. The terminal is literally broken.

This happened overnight, no update was actively approved, but it might have uploaded in the background. Regular terminal (iTerm2) works.

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal

**Comment by tillkolter** [comment]
@Tyriar 

here is a screenshot 
![Screenshot 2020-09-24 at 15 50 19](https://user-images.githubusercontent.com/590062/94154388-1af7c000-fe7e-11ea-97ca-8911c99ab9cc.png)

**Comment by Tyriar** [comment]
Can you share your settings? I'm suspecting issues with maybe `terminal.integrated.shell.osx` or `terminal.integrated.inheritEnv`?
