### ISSUE TITLE
README.md does not take precendence when workbench.startupEditor=readme

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode#107253]
- VSCode Version: 1.49.1
- OS Version: Windows 10

Steps to Reproduce:

1. Set this on VSCode settings:

  ```jsonc
  {
    "workbench.startupEditor": "readme"
  }
  ```

2. Create a folder with an `README.md` and another `README test.txt`

3. Open the folder in VSCode (`code .`)

You'll notice that the file `README test.txt` was opened automatically, but the right file would be `README.md`.

Does this issue occur when all extensions are disabled?: Yes

It also occurs with VSCode Insiders current version.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/e6a3b8f98cd87d4023f70eabda3331344e5f78fa

**Comment by felipecrs** [comment]
Thanks, @bpasero for pointing out. I made a PR at https://github.com/microsoft/vscode/pull/107315/files.

**Comment by felipecrs** [comment]
Confirmed, it's working as expected in today's build.
