### ISSUE TITLE
Outline view element overflow

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#107284]
Description:

If the outline item detail is long, the item overflows. See below:

![image](https://user-images.githubusercontent.com/16353531/93990527-7dbc5f00-fd8b-11ea-9f43-447982a8e8c8.png)

- VSCode Version: 
  1.49.1
  58bb7b2331731bf72587010e943852e13e6fd3cf
  x64
- OS Version: MacOS Catalina

Steps to Reproduce:

- Have a long detail of an outline item

Does this issue occur when all extensions are disabled?: No

**Comment by Rachel-Hu** [comment]
Hi! I'm a part of Grace Hopper Open Source Day and would love to give it a try!
