### ISSUE TITLE
Text search is slow

### ISSUE THREAD

**Issue by zouhejing0000** [microsoft/vscode#107207]
When I perform a global search, CPU and memory will rise sharply. What's more troublesome is that the disk io started to get busy, causing the response speed of the entire computer to start to drop.

**Comment by roblourens** [comment]
See whether any tips on this page help https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
