### ISSUE TITLE
Automatically generated when the project is opened debug.log file

### ISSUE THREAD

**Issue by lubo3395** [microsoft/vscode#107206]
Issue Type: <b>Feature Request</b>

When I open my project with vscode, it will automatically generate one in the root directory debug.log Documents, which were not available before, have only recently appeared. I would like to ask why this is the case and how to set it to be removed. thank you.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen if you launch with all extensions disabled?
