### ISSUE TITLE
Intellisense stopped working weeks ago for TS

### ISSUE THREAD

**Issue by wmglasner** [microsoft/vscode#107255]
Issue Type: <b>Bug</b>

I have no idea how to reproduce this. I am using WSL 2.
Up until a few weeks ago, Intellisense was working fine in my angular project. 
Then it stopped working, specifically for typescript, I have no autocomplete settings, no hover information, no red squiggles, pretty much every feature advertised in Intellisense doesnt work.
I cloned the same repo on my mac and NPM installed, and it works fine.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (21.46GB free)|
|Process Argv|--crash-reporter-id 80c78536-012f-4ce7-b018-32ead928e80b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 3593)|
|Memory (System)|25.02GB (23.45GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.1
remote-wsl|ms-|0.44.5
debugger-for-chrome|msj|4.12.11
npm-intellisense|chr|1.3.1
githistory|don|0.6.9
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
git-project-manager|fel|1.7.1
vscode-docker|ms-|1.6.0

</details>

**Comment by Tomas-Tr** [comment]
copy paste the whole project to new folder and open it from there. it will work for another week or two again....

**Comment by mjbvz** [comment]
I can't reproduce this with a new angular project. Here's a new angular project running under WSL:

<img width="1583" alt="Screen Shot 2020-10-28 at 1 51 52 PM" src="https://user-images.githubusercontent.com/12821956/97495340-bddfa600-1924-11eb-9dcd-781f10d58d83.png">

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled) (besides wsl)? Can you provide steps to reproduce this?
