### ISSUE TITLE
Can't select folder in file explorer path when overflowing

### ISSUE THREAD

**Issue by infinitepr0** [microsoft/vscode#107263]
Issue Type: <b>Bug</b>

# To Reproduce
- Create a long, nested directory (for example `abc1/abc2/abc3/abc4/abc5`)
- Resize the Explorer pane so that the suffix of the path is replaced dots (making it something like `abc1/abc2/abc3/a...`)
- Try selecting any of the folder names (`abc1`/`abc2`/`abc3`)
- Now, resize the pane so that the entire path is visible.
- Try selecting the folders now.

# Expected results
In both cases, the folder should have got selected (underlined) on clicking.

# Actual Results
Folder doesn't get selected when there is overflow.

VS Code version: Code - Insiders 1.50.0-insider (cca20eba8974b1d6b6a9b71bf4e60a29c8f26648, 2020-09-14T05:09:13.216Z)
OS version: Linux x64 5.8.10-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2388)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|5.71GB (2.00GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 5a17676a-2717-46d9-af27-51bca0f20d11|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.17.0
cpptools|ms-|1.0.1
material-icon-theme|PKi|4.3.0
tabnine-vscode|Tab|3.0.2

(3 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
The issue here is what compact item design. When there are multiple folders with only one child we render them all together as one node. When the last node is not rendered we still mark it as focused which is the problem.

I acknowledge this issue, however no plans to tackle it right now -> backlog
