### ISSUE TITLE
Crash when click 'open folder'

### ISSUE THREAD

**Issue by ryanpatiency** [microsoft/vscode#107216]
- VSCode Version: 1.49.1
- OS Version: 5.8.10-arch1-1

Steps to Reproduce:

1. open vscode w/o extensions
2. click on 'open folder'

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you using snap package? 
Looks like duplicate of #100940 
Current workaround in https://github.com/microsoft/vscode/issues/100940#issuecomment-678711777

**Comment by ryanpatiency** [comment]
yes, solved. Thank you
