### ISSUE TITLE
[wsl] Support trash on remote

### ISSUE THREAD

**Issue by bermeom** [microsoft/vscode#107233]
Visual Studio Code with WSL deletes files/folders permanently (file/folder will not appear in Recycle Bin), which is not appropriate as you could accidentally delete important files. 

- VSCode Version: 1.49.0
- OS Version: Windows 10 

Steps to Reproduce:

1. Open whatever project in WSL  
2. Delete some file/folder
3. Now look for it

**Comment by isidorn** [comment]
The WSL file system provider does not support moving to trash, thus explorer by design does not show this command. Thus forwarding this to @aeschli for now

**Comment by bermeom** [comment]
Ok, but at least the files should be moved to the Recycle Bin of the Windows

**Comment by aeschli** [comment]
same issue: #108731

**Comment by aeschli** [comment]
Marking as duplicate of #108731

**Comment by SwastikBhattacharjee** [comment]
same issue: #108731
