### ISSUE TITLE
Need ability to pass commandline arguments to extension

### ISSUE THREAD

**Issue by HenrikHolmIT** [microsoft/vscode#107228]
I'd like a way to launch VSCode with commandline arguments and to have a way to my extension to access these value pairs.

**Comment by kieferrm** [comment]
Not the same but you can register a uri handler: https://code.visualstudio.com/api/references/vscode-api#window.registerUriHandler

**Comment by joaomoreno** [comment]
This is currently beyond our API scope.

**Comment by jrieken** [comment]
🤷 I don't own the feature...

**Comment by HenrikHolmIT** [comment]
This would be a nice feature indeed but we solved it by having the launcher process update the user profile settings.json file before launch and passing in parameters that way. Works but maybe not super elegant.
