### ISSUE TITLE
debug.log

### ISSUE THREAD

**Issue by devin-full-dev** [microsoft/vscode#107275]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by NoufalBhai** [comment]
debug.log file is automatically generated on each folder with the message on each save
`[0923/013438.097:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)`

**Comment by kieferrm** [comment]
\duplicate 105191
