### ISSUE TITLE
Smoke: Notebooks moves focus as it inserts/deletes a cell

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107219]
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Notebooks
           moves focus as it inserts/deletes a cell:
     Error: Timeout: get text content '.notebook-editor .monaco-list-row.focused .monaco-editor .view-lines' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)

**Comment by roblourens** [comment]
From 8e9beffcf5141874d64e4410d2166750cbf9c373

**Comment by bpasero** [comment]
Seems fine in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=89410&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=6ba55b26-6502-59ae-6c43-7e580fa53cb9&l=45
