### ISSUE TITLE
Debugging on multiple instances of web app

### ISSUE THREAD

**Issue by B45man** [microsoft/vscode#107221]
Modern web apps are usually run stateless with multiple instances. For example, if you're running in Kubernetes your app might have 1, 2, or even 10 instances running at once. My development environments (Visual Studio 2019 and Code) have no way to emulate this, leading to issues. 

For example: I have made a new feature that works great when I debug it locally. However, I have created a bug that means my feature is not stateless (it requires requests to hit the same instance of my web app every time), I will not notice this until I roll out my code to my dev/test/prod environments. 

I want Visual Studio Code to launch an ASP.Net web app with multiple instances when debugging, and routing my requests to a different instance every time to more accurately show what will happen when my code runs in an environment with multiple instances. Quickly brainstormed ways this can be accomplished: 

- make a Kubernetes deployment with multiple replicas, attach a debugger to every replica
- if Kubernetes is not available, use Docker containers to set up an nginx container automatically, and multiple docker containers with my app in it that the nginx container sends traffic to. Attach a debugger to every docker container.

**Comment by weinand** [comment]
Nothing in VS Code prevents this from already working OOTB like you suggested.

Running the classic Node.js "cluster" program starts _n_ independent node.js processes (all with an attached debugger):
```js
const cluster = require('cluster');
const http = require('http');
const numCPUs = require('os').cpus().length / 2;
const Net = require('net');

const PORT = 8000;

if (cluster.isMaster) {
	console.log(`Master ${process.pid} is running`);
	console.log(`Forking ${numCPUs} workers.`);
	console.log(`Node.js version ${process.version}`);

	// Fork workers.
	for (let i = 0; i < numCPUs; i++) {
		cluster.fork();
	}

	cluster.on('exit', (worker, code, signal) => {
		console.log(`worker ${worker.process.pid} died`);
	});
} else {
	// Workers can share any TCP connection
	// In this case it is an HTTP server

	http.createServer((req, res) => {
		res.writeHead(200);
		res.end('hello world\n');
	}).listen(PORT);

	console.log("listening on port: " + PORT);
	console.log(`Worker ${process.pid} started`);
}
```
If you hit the cluster web address with a web browser, some random node.js worker will get the request:

![2020-09-22_17-47-00 (1)](https://user-images.githubusercontent.com/1898161/93905954-de03c000-fcfb-11ea-8697-e6b56e3e9605.gif)

All 6 "test.js" nodes under the "cluster.js" node are independent processes which all have an independent debugger attached.

The only support that was added in the Node.js debug extension was to create new debug sessions for the child processes forked by the main program.

The same could be done for the C# extension. Please file a feature request against them.

Without that code you would have to attach debuggers to the worker processes manually or use a compound launch config that starts n debug sessions against n processes. The latter can be done already today.
