### ISSUE TITLE
Custom dialog: "Save Workspace As..." does not put proper name anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107279]
In web when I trigger File > Save Workspace As, I am seeing an empty picker, but I would expect an experience which is more like this:

![image](https://user-images.githubusercontent.com/900690/93975299-8c008000-fd77-11ea-9fd9-bf043227ff69.png)

**Comment by alexr00** [comment]
The current behavior is to have not placeholder for the filename+extension. Having no filename is consistent with what Windows does:
![image](https://user-images.githubusercontent.com/38270282/93985727-beb17500-fd85-11ea-936b-18d6096f178d.png)

@bpasero is your screen shot what you see on Mac when doing Save Workspace As in desktop?

**Comment by bpasero** [comment]
@alexr00 yeah it is macOS and I think the challenge here is that the custom file dialog does not provide any dropdown for the file extension to pick. I think I would prefer if the custom file dialog would then do what macOS does.

**Comment by alexr00** [comment]
Sounds good, I will update to add a placeholder filename+extension for save workspace as, which is not web specific.

**Comment by bpasero** [comment]
@alexr00 the code for that use is here:

https://github.com/microsoft/vscode/blob/e5d104b3a8aeb80400361713f735f5665a11d5f5/src/vs/workbench/services/workspaces/browser/abstractWorkspaceEditingService.ts#L51-L57

To clarify: you would not implement a one-off solution for the "Save Workspace As..." but pick on the existing `filters` property to do so? I guess one question is how that would conflict with the `defaultUri` property if that points to a file and not folder.

**Comment by alexr00** [comment]
I think I would change the last line of the method here:
https://github.com/Microsoft/vscode/blob/e5d104b3a8aeb80400361713f735f5665a11d5f5/src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts#L76-L88

Instead of just using the `defaultFilePath()`, is what you are seeing happen, I would give it an untitled filename and the appropriate extension.

**Comment by bpasero** [comment]
@alexr00 yeah works for me 👍
