### ISSUE TITLE
"Preserve case" replace option : add a key shortcut

### ISSUE THREAD

**Issue by Kapcash** [microsoft/vscode#107208]
I'm using the "**Preserve case**" option in the **Replace field** quite often.  
And it's the only option in the panel that does not have its own **keybinding shortcut** (or at least I can't find it to set it up).

Would you consider adding a shortcut entry for this toggle?

Thank you!

**Comment by roblourens** [comment]
You can add your own, but it would be nice to have a default. Any suggestions?

**Comment by Kapcash** [comment]
I couldn't find the shortcut from the key bindings UI, what's his name?

I noticed "_alt+cmd+**w**_" is for "match hole **w**ord", "_alt+cmd+**c**_" for "Match **c**ase"
so what about "_alt+cmd+**p**_" by default for "**P**reserve case"?

**Comment by roblourens** [comment]
Ah, you are right, I missed adding a Toggle action for this as well

**Comment by tvgirl90** [comment]
Hi, I'm part of Grace Hopper OSD and I will try to tackle this one!
