### ISSUE TITLE
Hover pop-up documentation pane is sometimes absurdly small

### ISSUE THREAD

**Issue by Ptival** [microsoft/vscode#107212]
- VSCode Version: 1.50.0-insider
- OS Version: Windows 10

Steps to Reproduce:
1. This happens to me when editing Unity C# files.
2. Just do a Ctrl-Space to get the hover popup, and scroll through the options.

![vscode](https://user-images.githubusercontent.com/478606/93865881-379dc780-fcc7-11ea-9e7b-044e2cd84c4f.gif)

Does this issue occur when all extensions are disabled?: This occurs when the only extension enabled is the C# extension (that allows such pop-ups to exist in the first place)

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest+label%3Aux

**Comment by Ptival** [comment]
@jrieken yeah I thought it could be a dupe but did not find it after a quick look. Could you add the `editor-hover` label to this issue, if appropriate, so that the next person at least finds this issue?
