### ISSUE TITLE
More intelligent IntelliSense

### ISSUE THREAD

**Issue by kenkopelson** [microsoft/vscode#107289]
I am constantly being annoyed by IntelliSense bringing up suggestions for things that I don't need suggestions for.  In general, it seems that the mechanism is not geared to editing code, changing code, adding to code, or modifying code.  It's only geared to a person adding new code.  If I put my cursor into a method's argument list, IntelliSense should see that I have already added method arguments, and not try to suggest anything to me.  The problem with it constantly making suggestions, and not detecting when I really could use assistance, is that it covers up the code with the suggestion box, and I can't see what I'm typing.  As it is, I have to type a few letters and then hit <escape> to get rid of the suggestion box.  Then I type a few more letters, etc.  In short, it's not very intelligent at all.

**Comment by jrieken** [comment]
> In short, it's not very intelligent at all.

Just like this issue. Please update with concrete steps/samples after reading this  https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
