### ISSUE TITLE
WSL terminal seems to trigger tunneling notifications

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#107227]
- set `"remote.WSL.debug": true`
- open a new WSL window using the Remote-WSL extension
- open the WSL log (`Rempte-WSL: Show Log)
- the log shows, along with two notifications that tunnels have been opened

It's strange that showing the log file seem to trigger the notifications.
Tunneling the remote server port is not very useful

![image](https://user-images.githubusercontent.com/6461412/93880272-80f91180-fcdd-11ea-96b1-31033056b11c.png)

**Comment by alexr00** [comment]
Two things can be done to improve this:
- Only turn on url finding when the remote has opted in to the forwarded ports view. This will exclude WSL, which is what we want.
- Wait to start the url finder until we are done connecting to the remote.

**Comment by aeschli** [comment]
@alexr00  It seems to me that the WSL terminal triggers the tunneling. Is that possible? The WSL terminal is not a real terminal, just a fancier output view using a PseudoTerminal as backend. That should not trigger anything.

**Comment by alexr00** [comment]
All terminals should trigger tunneling. One of the uses for PseudoTerminal is to just display the output from running a command. We don't know what that command would be, so we should treat all terminals as possible sources for port forwarding.
