### ISSUE TITLE
Source Control FR: Set repo icons to only show on hover

### ISSUE THREAD

**Issue by mikestopcontinues** [microsoft/vscode#107252]
I've been working with the SCM sidebar recently, in an attempt to push all my dev work into VSCode... But I find that the buttons on the repo row take up way too much visual real estate.

The easiest solution would be to show nothing except the number of changes (and perhaps the menu icon) by default, then on hover, to show the rest. This would retain the ease of those extra buttons without all the clutter. It would make it easier to keep the sidebar at a sane width as well.

If others have a different opinion about what to always show, it's possible to enable settings for each icon, to values: `alwaysShow`, `showOnHover`, and `neverShow`.

**Comment by joaomoreno** [comment]
#107145
