### ISSUE TITLE
GPU-related corrupted explorer side bar 

### ISSUE THREAD

**Issue by sdbruder** [microsoft/vscode#107224]
Issue Type: <b>Bug</b>

the workspace tab in the explorer side bar is visually corrupted, and only the workspace tab, everything else is ok.

An image of the corrupted side bar: https://slack-files.com/T02T7NB0A-F01AYD8BKM4-80b1100460

update: `code --disable-gpu` "fixes" the issue.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.91GB free)|
|Process Argv|--disable-gpu --crash-reporter-id 03870f14-3b9d-4b1c-aca6-a970a0033200|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.3.0
vscode-intelephense-client|bme|1.5.4
language-hugo-vscode|bud|1.2.0
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-clock|Com|0.0.1
xml|Dot|2.5.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|5.6.0
terraform|has|2.2.3
vscode-test-explorer|hbe|2.19.1
error-gutters|Igo|1.0.1
mysql-syntax|jak|1.3.1
inline-parameters|lia|0.2.1
rainbow-csv|mec|1.7.1
laravel-intellisense|moh|0.1.8
vscode-docker|ms-|1.6.0
python|ms-|2020.8.109390
remote-ssh-edit|ms-|0.55.0
vscode-remote-extensionpack|ms-|0.20.0
material-icon-theme|PKi|4.3.0
vscode-phpunit|rec|2.0.76
java|red|0.67.0
vscode-yaml|red|0.11.0
terraform-doc-snippets|run|0.4.0
vscode-workspace-switcher|sad|1.15.3
vscode-nginx|sha|0.6.0
tabnine-vscode|Tab|3.0.2
shellcheck|tim|0.10.1
quick-open-keep|tod|0.0.2
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-icons|vsc|11.0.0
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2
change-case|wma|1.0.0
cursor-align|yo1|1.0.4
material-theme|zhu|3.8.7

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Sounds like an electron issue since --disable-gpu fixes the issue. Forwarding to @deepak1556 
The link to the image is broken by the way, so please fix it @sdbruder

**Comment by sdbruder** [comment]
URL to image fixed.
