### ISSUE TITLE
Yarn command not working in terminal

### ISSUE THREAD

**Issue by abhishek1041** [microsoft/vscode#107288]
Whenever I try to run the yarn command in terminal, it always give me error of Unauthorized access through I'm using the system as administrator. Suggest a link which take me to Windows website. It would be better if relevant links can shared in errors of terminal to solve the issue.

- VSCode Version: 1.49.1
- OS Version: Windows 10 2004

Steps to Reproduce:

1. Create a react.js project or next.js project.
2. Run yarn dev or yarn add or any other command related yarn.

Does this issue occur when all extensions are disabled?: Not sure

**Comment by rzhao271** [comment]
@abhishek1041 I wonder if it's your project. This repo uses yarn too, and I can run yarn on it in the VS Code terminal on Windows 10 fine.

You can also paste the error message if it shows up on the latest Insiders, and that might make it easier to pinpoint the issue.
