### ISSUE TITLE
"Electron: Loading non-context-aware native module in renderer" Messages

### ISSUE THREAD

**Issue by m2web** [microsoft/vscode#107242]
- VSCode Version:
Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0

- OS Version:
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. I have VS Code set as my core editor for git via:
```
git config --global core.editor vscode
```
2. I have a PowerShell script that copies files, calls a git add and git commit.
2. After completing and saving the git commit message in VS Code, the following is displayed at the CLI:

```[main 2020-09-22T14:33:42.382Z]
update#setState idle
(node:25176) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:25176) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:17984) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[main 2020-09-22T14:34:12.385Z] update#setState checking for updates
[main 2020-09-22T14:34:12.763Z] update#setState idle
[master f86d509] Updates 9/22/2020 AM
```

Does this issue occur when all extensions are disabled?: Yes/No
N/A

**Comment by IllusionMH** [comment]
You need to use `--wait` flag if you need to wait for VS Code actually saving commit message
`git config --global core.editor "code --wait"` where `code` is `code.cmd` for your `bin` folder, and not `code.exe`

Most likely this should fix extra logs.

**Comment by m2web** [comment]
@IllusionMH, that was it. I wasn't sure as the errors just started showing up with the latest VS Code update. None the less, the deprecation messages are gone.
