### ISSUE TITLE
Don't automatically forward debug ports in auto attach

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#107243]
js-debug's auto attach "smart" mode causes a process to enter auto attach, without explicit flags. When entering debug mode, we let the OS choose a random free port (`0`) since we don't need any specific port.

I noticed when working in a remote container that this caused a bunch of ports to automatically be forwarded in the remote.

![](https://memes.peet.io/img/20-09-eb6ed6bb-f71a-49ae-8029-c3c4f7d54507.png)

Unfortunately this message is printed by Node and I cannot always stop it from printing.

Is there any way we could exclude the pattern `Debugger listening on ...` from automatic forwarding?

**Comment by alexr00** [comment]
@connor4312 we can exclude based on "Debugger listening on", but are there cases where Node may print that message and it isn't coming form j-debug's auto attach? Is there some other information about the terminal or state in VS Code I can use to exclude that link?

**Comment by connor4312** [comment]
It will also be printed if running something like `node --inspect` manually. But I would venture to guess that in those cases people will probably be subsequently attaching with vscode, so forwarding would not be necessary since js-debug is a workspace extension.

**Comment by connor4312** [comment]
Thanks!

**Comment by roblourens** [comment]
I can't repro this in stable, and I don't see the notification when I trigger port forwarding another way, what am I missing?

**Comment by alexr00** [comment]
The notification is new this iteration, so no repro in stable. To verify:

- run command Remote-Containers: Try a sample...
- Choose the node sample
- Make sure debug auto attach is on (command Debug: Toggle Auto Attach -> choose Smart)
- In the integrated terminal run `node server.js`
- Verify that you don't see the port forwarded notification.

**Comment by roblourens** [comment]
I don't see it, but do I expect to see it in this case?

![image](https://user-images.githubusercontent.com/323878/94949809-66b9f300-0496-11eb-858c-f8c37347ed1e.png)

**Comment by alexr00** [comment]
That case should forward the port.
