### ISSUE TITLE
SyntaxError on code that is not there

### ISSUE THREAD

**Issue by vchealy** [microsoft/vscode#107247]
Issue Type: <b>Bug</b>

Run a single .py file and an error marker appears at the end of the code.
Then an error stating the last line of the code:
   
                   ^
SyntaxError: unexpected EOF while parsing

There is no code after the last line, there is no spaces, tabs or anything.

VS Code version: Code - Insiders 1.50.0-insider (cca20eba8974b1d6b6a9b71bf4e60a29c8f26648, 2020-09-12T01:04:21.398Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 2020M @ 2.40GHz (2 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.72GB free)|
|Process Argv|--crash-reporter-id 3262e7a8-d23d-4911-87e6-b52d57cd7309|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
code-runner|for|0.11.0
python|ms-|2020.8.109390
vscodeintellicode|Vis|1.2.10

(1 theme extensions excluded)

</details>

**Comment by kieferrm** [comment]
\extPython
