### ISSUE TITLE
"Typescript language service died 5 times" error alert

### ISSUE THREAD

**Issue by glomotion** [microsoft/vscode#107272]
Issue Type: <b>Bug</b>

Open a TS file. 
The "typescript language service" error shows shortly afterwards

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 2|
|Memory (System)|16.00GB (0.77GB free)|
|Process Argv|--crash-reporter-id 2f473960-f7af-4b52-b713-abfdea2eac65|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1001.0
vscode-browser-preview|auc|0.6.7
es6-string-css|bas|0.1.0
npm-intellisense|chr|1.3.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-es-beautifier|dai|1.1.0
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
json-tools|eri|1.0.2
prettier-vscode|esb|5.6.0
JSDocTagComplete|Hoo|0.0.2
docthis|joe|0.7.1
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.8.0
litelement-web-components-extension-pack|jus|0.0.4
Polymer2Snippets|jus|2.0.1
chat|kar|0.35.0
prettify-json|moh|0.0.3
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2740
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
angular-console|nrw|13.0.0
fix-json|oli|0.1.2
material-icon-theme|PKi|4.3.0
csslint|ray|0.0.11
es6-mocha-snippets|spo|0.2.2
addDocComments|ste|0.0.8
rewrap|stk|1.13.0
code-spell-checker|str|1.9.0
es6-string-html|Tob|1.8.8
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by glomotion** [comment]
Oh nice! Nope... the insider vscode build runs fine! TY TY @mjbvz - ill just use this for the next little while! :)

**Comment by mjbvz** [comment]
It could also be one of the extensions you have installed. If that is the case, please file this against the extension instead
