### ISSUE TITLE
Please expose TRACK_DISPOSABLES to extensions

### ISSUE THREAD

**Issue by dcermak** [microsoft/vscode#107202]
vscode appears to have the ability for some simplistic tracking of disposables:
https://github.com/microsoft/vscode/blob/8c91bd827848f1710d055c39d80d04c59bb55463/src/vs/base/common/lifecycle.ts#L16

Would it be possible to expose this to developers of extensions, for example via an environment variable, so that it could be toggled in during development?

**Comment by jrieken** [comment]
fyi @mjbvz

**Comment by mjbvz** [comment]
This is not a fully implemented feature and has a lot of false positives. It will not do what you want and was only created to be used by VS Code devs (specifically, by me)
