### ISSUE TITLE
SnippetString does not escape commas in choices

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#107220]
`SnippetString.appendChoice` doesn't handle commas in choices correctly. Given the following code:

```ts
const editor = vs.window.activeTextEditor;
const snippet = new vs.SnippetString();
snippet.appendChoice(["One,Two", "Three,Four"], 1);
await editor.insertSnippet(snippet, new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)));
```

This is what shows in the editor:

![Screenshot 2020-09-22 at 12 07 28](https://user-images.githubusercontent.com/1078012/93875217-7da95a00-fccc-11ea-8735-c39c8133b993.png)

**Comment by jeanp413** [comment]
I'll take this
