### ISSUE TITLE
Multiple hovers showing (native and custom)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107277]
Steps to Reproduce:

1. have a JS or TS file with errors or warnings
2. find references
3. hover over the file name

![recording](https://user-images.githubusercontent.com/900690/93971209-eac1fb80-fd6f-11ea-9563-4af7445c58f3.gif)

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/commit/2116f17e96e6152b1f1827e3e4a82343ee776d60
