### ISSUE TITLE
It is recommended that the version control tool that comes with the software provides a richer interface, such as code submission records, code comparison and other functions

### ISSUE THREAD

**Issue by ldzqdrm** [microsoft/vscode#107296]
Because vs code has a lot of very useful plug-ins, so many developers have installed a lot of plug-ins, which causes the vs code to become more and more stuck, and the speed is getting slower and slower. Then I am thinking about the functions of vs code itself, To achieve the ultimate, can it allow users to install less plug-ins?

Here I want to talk about the version control tool of git. VS code does not have a very convenient and beautiful graphical interface. Many users have downloaded gitlends. It is good, but it seems redundant. After all, VS code comes with a version control tool, but it is not enough. It's easy to use, so the user downloads the plug-in, but the user cannot uninstall the version control tool that comes with the vs code, which leads to the user's vs code often has two version control tools.

Then I suggest that the version control tool that comes with the software provides a richer interface, such as code submission records, code comparison and other functions. This can refer to the design of ieda, so that users can install less git plugins and other plugins. Make the native function of vs code to the extreme and free users from redundant plug-ins.

**Comment by kieferrm** [comment]
@ldzqdrm thanks for your suggestion. We always try to find the right balance between what is core functionality and what comes in through extensions. For SCM in particular, we have no plans to massively extend the built-in functionality, but we do work with GitLens to provide a more natural integration between GitLens and the built-in SCM. This should reduce the impression of "redundancy".  You can follow along on our journey here: https://github.com/microsoft/vscode/wiki/Roadmap.

**Comment by kieferrm** [comment]
FYI @joaomoreno @eamodio

**Comment by ldzqdrm** [comment]
> @ldzqdrm thanks for your suggestion. We always try to find the right balance between what is core functionality and what comes in through extensions. For SCM in particular, we have no plans to massively extend the built-in functionality, but we do work with GitLens to provide a more natural integration between GitLens and the built-in SCM. This should reduce the impression of "redundancy". You can follow along on our journey here: https://github.com/microsoft/vscode/wiki/Roadmap.

Then I suggest that users install the git plug-in and embed the plug-in interface directly. In the native version control tool of vs code, this is more suitable as an expanded project and makes the software look more streamlined
![BJN8ACGZ0F{O%FO 3VXY4RJ](https://user-images.githubusercontent.com/22335503/94024053-85aaec00-fde9-11ea-9c2c-44d9713b7739.png)

**Comment by ldzqdrm** [comment]
@kieferrm
