### ISSUE TITLE
Settings sync de-authorized token problem

### ISSUE THREAD

**Issue by DanaMW** [microsoft/vscode#107287]
I changed my Microsoft user password after having applied an auth token to VS Code for settings syncing. Now I receive log errors as follows:
[2020-09-23 02:31:44.835] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-09-23 02:31:44.835] [userDataSync] [info] Auto Sync is enabled.
[2020-09-23 02:31:44.835] [userDataSync] [info] Auto Sync: Suspended until auth token is available.
On the menu it simply states: "Microsoft is currently unavailable". I guess it could be a bug also, but it seems since I have not yet found how to reset it, that it should move you to requesting a new auth token at that click. Or a sub menu to sign out of Microsoft. Since they are not available a sign out option would have fixed this for me. Hope I made this clear enough. Thank you for this fine work. 
![2020-09-23](https://user-images.githubusercontent.com/12940577/93996953-b5a1b300-fd47-11ea-853b-672a1969c41e.png)

**Comment by RMacfarlane** [comment]
Hey @DanaMW, this sounds like https://github.com/microsoft/vscode/issues/106321. We weren't removing cached credential information when it fails. This should be fixed in the next release, in the meantime can you try manually deleting the credential? If you're on windows, you can open the credential manager, select "Windows Credentials" and then delete "vscode-microsoft.login/account"

**Comment by DanaMW** [comment]
Thank you very much. I see they are similar issues and an update flows inbound now, if I may I will close this in favor of the previous #106321

**Comment by Curzey** [comment]
@RMacfarlane Do you know how to find and manually remove this file on mac? I have the exact same issue.

**Comment by RMacfarlane** [comment]
@Curzey Open "Keychain Access" and look for "vscode-microsoft.login" in the login keychain

**Comment by Curzey** [comment]
Thanks @RMacfarlane 🎉 - However I only have 'vscode-github.login'. Just for good sake; should it do the trick deleting this?
