### ISSUE TITLE
Outline: shift + tab needs to be pressed twice for focus to go to title actions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#107209]
1. Focus on outline view
2. Press `shift + tab` -> focus gets lost 🐛 
3. Press `shit + tab` again -> focus is on the Outline title actions

The first `shit + tab` should take the focus to the title actions like in all other views.

**Comment by jrieken** [comment]
it's because of https://github.com/microsoft/vscode/issues/55607... needs a better fix as it seems

**Comment by jeanp413** [comment]
I'll take a look at this
