### ISSUE TITLE
[Settings Sync] Feat Req: Do not focus output window on startup

### ISSUE THREAD

**Issue by jasonswearingen** [microsoft/vscode#107245]
### Feat Req:  
allow option to not force the ```output --> Code Settings Sync``` pane from being focused upon every vscode startup (maybe it is really "upon settings sync performing an action", but that occurs on startup)

Reason:  I don't need to be informed of a successful settings sync every startup.   I want to open VSCode and start working (example: using the builtin terminal window) but about 10-20 seconds after starting VSCode the bottom pane automatically switches to the  ```output --> Code Settings Sync``` view.  Disrupting my workflow.

**Comment by sandy081** [comment]
`Code Settings Sync` is this the name of the output view or just Settings Sync?

Can you please disable all extensions and repro it?

**Comment by jasonswearingen** [comment]
Thank you, you are right.  This seems to be a conflict with the ```Settings Sync``` extension and VSCode's built-in settings sync colliding.   When that happens the ```Settings Sync``` extension thinks there are changes at every startup and this is what is causing the output window focus.

Closing the issue, will repost on the settings sync extension
