### ISSUE TITLE
RenameProvider should be able to signal whether a location is valid for a rename

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10723]
Currently a RenameProvider can be instructed to make renames that are not valid, eg.:

```dart
import "dart:html";
```

Here, you can rename on the `import` which makes no sense. While it's possible for us to return no edits, it's weird to give the user a textbox pre-populated with `import`.

It would be better if a RenameProvider can be queried to see whether a rename is valid for a given location and Code can then avoid showing the rename box entirely.

**Comment by jrieken** [comment]
fyi @aeschli

**Comment by jrieken** [comment]
closing this as a duplicate of #7340
