### ISSUE TITLE
TS server crashes and restarts

### ISSUE THREAD

**Issue by CdricGmd** [microsoft/vscode#107249]
Issue Type: <b>Bug</b>

I work in a mono repo with 180+ npm packages using TypeScript. 
The mono repo is using rush, the package.json and tsconfig files reference some parent files.

Some features are consistently slow (autocomplete, reference search) and "JS/TS langugage feature" regularly restarts automatically.

VS Code version: Code - Insiders 1.50.0-insider (8c1015f5e1a7a686d19ec8a5f56a495332f16062, 2020-09-21T07:58:39.811Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (8.77GB free)|
|Process Argv|--crash-reporter-id 33ebab04-5cf1-4f65-9bc1-4ab14ad408d6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by CdricGmd** [comment]
Yes it still reproduces after restarting with all extensions disabled.

Le mar. 22 sept. 2020 à 19:04, Matt Bierner <notifications@github.com> a
écrit :

**Comment by mjbvz** [comment]
Can you share the project that causes this? 

Also, have you followed the guidance for [working with large TypeScript projects](https://code.visualstudio.com/docs/typescript/typescript-compiling#_working-with-large-projects)?
