### ISSUE TITLE
"Expand All" not expanding collapsed text

### ISSUE THREAD

**Issue by rh-jelabarre** [microsoft/vscode#107254]
In a file in the editor window, collapse a large number of sections in the document.  Then do a "select all", and "expand selection".  This should expand all the collapsed sections back put, but it doesn't change the edit window's collapsed sections at all.  No change occurs in the edit window.

Closing the file and re-opening it will not expand text back out.  Closing all copies of VSCodium and restarting it also will not reset the state back to default.   You have to manually expand them out individually.

**Comment by kieferrm** [comment]
What you are looking for is 

![image](https://user-images.githubusercontent.com/4674940/94022181-ab90ac00-fd69-11ea-873f-2be475e7570f.png)

Use <kbd>F1</kbd> to get to the command palette.

**Comment by kieferrm** [comment]
FYI @aeschli
