### ISSUE TITLE
TypeScript tooltips no longer show "undefined"

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#107203]
When hovering over types and functions recently, `undefined` is no longer shown in the types. This function `getWorkspaceFolder` (from the VS Code API) has a return type of `WorkspaceFolder | undefined` but the tooltip doesn't include `undefined`. This seems to the case for all tooltips, for local variables, functions, etc.:

<img width="792" alt="Screenshot 2020-09-22 at 09 07 02" src="https://user-images.githubusercontent.com/1078012/93857758-ff8c8980-fcb2-11ea-9ab4-3cd331014fc7.png">

If I hold down Cmd which adds a preview of the code (using the definition data), the `undefined` is shown:

<img width="624" alt="Screenshot 2020-09-22 at 09 06 24" src="https://user-images.githubusercontent.com/1078012/93857900-39f62680-fcb3-11ea-8452-0a3e0b5f1f65.png">

This makes fixing type issues a little annoying, as it's not always obvious if a value may be undefined or not.

I'm using TypeScript 4.0.2 according to the status bar.

**Comment by mjbvz** [comment]
Does your project have struct null checks enabled? `| undefined` will not show in non-strict projects

**Comment by DanTup** [comment]
@mjbvz Yep (via `strict`):

https://github.com/Dart-Code/Dart-Code/blob/e32b360706d4c3a76b7c0545b1eb9c267e6854bc/tsconfig.json#L12

It definitely used to show - I use this a lot, and it really caught me out that it disappeared.

**Comment by mjbvz** [comment]
Can you share steps to reproduce it in your codebase?

**Comment by DanTup** [comment]
```
cd /tmp
git clone https://github.com/Dart-Code/Dart-Code
cd Dart-Code
npm install
code .
```

Open `src/extension/commands/sdk.ts` and navigate to around line 156 (`const folder = vs.workspace.getWorkspaceFolder(uri);`) and hover over `getWorkspaceFolder`.

Based on another issue, I wonder if it may be related to this folder (`src/extension`) being excluded - but I'm certain this used to work. I need to exclude this folder from building because it's webpacked, and having two compiled copies of it is confusing for many reasons. This doesn't seem like it should break my language support in the editor (or if it must, there should be another way to prevent files being compiled to disk during a build).

**Comment by DanTup** [comment]
> I'm certain this used to work

Actually, it seems like I may have excluded the folder in tsconfig more recently than I remembered (when I webpack'd the debug adapter):

https://github.com/Dart-Code/Dart-Code/commit/27b76ae39a53dbe4aeb1b527d7cdffdebf916414#diff-e5e546dd2eb0351f813d63d1b39dbc48

So this might not have changed after all 🙈. Probably the fix is to have multiple tsconfigs?

**Comment by DanTup** [comment]
Turns out I'd already accidentally fixed this on my eslint-migration branch. I'd changed the base tsconfig to not exclude, and have a `tsconfig.build.json` that excludes and is used for builds. Sorry for the confusion (and misleading info!), I think this is all working-as-intended and has an obvious fix.

Thanks!
