### ISSUE TITLE
VSCODE does not stop on breakpoints in Node.js apps

### ISSUE THREAD

**Issue by jxmot** [microsoft/vscode#107251]
- VSCode Version: 1.49.1 (system setup)
- OS Version: Windows 10 Pro(2004)

Node info:
- version(s)  12.18.4,  12.16.1,  10.22.0,  **6.10.2(no longer supported!)** - all managed with NVM
- 64bit

Steps to Reproduce:

1. Create a node app
2. create a launch.json (Launch Program)
3. set a breakpoint
4. Run program

Files are in the attached `vscode_bug.zip`

Breakpoints are ignored, program runs. **This was working in previous versions of Code. I recently updated(big mistake apparently!) and now no version of node on my system will stop on breakpoints.**  

Does this issue occur when all extensions are disabled?: Yes/No **YES**
Does this issue occur with various node versions: **YES it does**

I've also noticed that vscode does not pass along a "debug" arg to node. It used to, and it was very clear in the output that Node was listing on a debug port. That message is no longer there.

**Can I download older versions or vscode? That seems to be the only fix. And I'll need it for working with 6.x.**

[vscode_bug.zip](https://github.com/microsoft/vscode/files/5263200/vscode_bug.zip)

**Comment by connor4312** [comment]
> That seems to be the only fix. And I'll need it for working with 6.x.

Recent versions of VS Code no longer support Node versions prior to 7, which use a different inspector protocol. You can set `debug.javascript.usePreview: false` to use the old debugger, but this option will by going away soon.

Upgrading off Node 6 is advisable in general, as since April 2019 it is end of life and no longer receives security updates.

> now no version of node on my system will stop on breakpoints.

To confirm -- it is expected that it doesn't work on Node 6, but should work on all the other versions you listed. If it doesn't, can you collect a trace log using the following instructions?

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.

**Comment by jxmot** [comment]
Node 6 is a requirement for me. There are some IoT boards I use and they're on 6 and not very likely to update as far as the bottom limit of VS Code. If "fix" for that is v1.20.1.

I will collect the trace data for you. But it might be a few days until I can get a chance.

Here's a doc describing the tests I ran with the various versions of VS Code and Node, hopefully it will be helpful:

https://github.com/jxmot/vscode-notes/blob/master/vscode-brkpt_bug.md

**Comment by connor4312** [comment]
Great doc, thanks! It's interesting that <v1.29 starts failing for you. We have an entirely new debugger as of v1.47. I will be interested to see the trace logs.

**Comment by jxmot** [comment]
No problem, believe it or not... I like writing docs!

I started on collecting the trace logs. And I'm beginning with v1.20.1. But I can't get the trace log working, I've googled and read through official docs, and cannot find anything on how to set it up. And I've also looked through the settings.

Could you please give me an example launch.json? Thanks!

**Comment by connor4312** [comment]
I would just grab the trace logs for 1.49. 1.29 is quite old and using a legacy debugger, so even if a bug is found there we're unlike to fix it. Let me know if `trace: true` doesn't work for 1.49. Your launch.json should look like

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "trace": true,
            "name": "Launch workspaceFolder",
            "program": "${workspaceFolder}/index.js"
        },
        {
            "type": "node",
            "request": "launch",
            "trace": true,
            "name": "Launch workspaceRoot",
            "program": "${workspaceRoot}\\index.js"
        }
    ]
}
```

With this, when you run a debug session you should get a line like this in your Debug Console view

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/2230985/94065791-6e93dc00-fda0-11ea-956b-48954eadab35.png">

**Comment by jxmot** [comment]
Thanks for the info! I'll switch over to 1.49 and retrieve the trace log. 

In version 1.49 none of the Node.js versions worked so I won't have a log saved for when it is working. I'll do my best to get this done over the weekend.

**Comment by jxmot** [comment]
Here are the trace logs. I ran against two versions of Node, 8.17.0 and 12.18.4. There is a `notes.txt` file describing which log is which. Thanks again for you help!
[tracelogs-20200927.zip](https://github.com/microsoft/vscode/files/5289393/tracelogs-20200927.zip)

**Comment by connor4312** [comment]
It looks like you have VS Code opened in `c:/Users/jim/Documents/WebExperiment/NodeJS/vscode_bug/index.js` but the file physically lives in `E:/Workspaces/Traveler/Documents/WebExperiment/NodeJS/vscode_bug/index.js`. It looks like you need to [run node with `--preserve-symlinks`](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks) for this.

**Comment by deepak-mali** [comment]
Same issue here with the following launch.json

`{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
			{
				"type": "node",
				"request": "attach",
				"name": "Attach",
				"port": 9229,
				"restart": true,
				"smartStep": true,
				"sourceMaps": true,
				"outFiles": [
						"${workspaceRoot}/dev-scripts/**/*.js"
				],
				"protocol": "inspector"
			}
	]
}`

**Comment by connor4312** [comment]
@deepak-mali please open a new issue using the template

**Comment by deepak-mali** [comment]
@connor4312 Aren't these same issues?

**Comment by connor4312** [comment]
It's very unlikely

**Comment by jxmot** [comment]
> It looks like you have VS Code opened in `c:/Users/jim/Documents/WebExperiment/NodeJS/vscode_bug/index.js` but the file physically lives in `E:/Workspaces/Traveler/Documents/WebExperiment/NodeJS/vscode_bug/index.js`. I'm thinking you need to [run node with `--preserve-symlinks`](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks). That should fix your Node 12 issue.

Thanks, I will look into using  `--preserve-symlinks`.  And I will try it from the _real_ folder and see what happens. I'll let you know the results.

In regards to older Node versions I simply may not have a choice in some cases. It will depend on the target I'm working on at the time. Not all can or should be updated.

**Comment by jxmot** [comment]
This problem does appear to have been caused by "open" vs "lives-in" path. When ran from the "lives-in" path breakpoints stop execution as expected. In this particular case Windows was configured to use a substitute folder location for "Documents".

I tried adding `"runtimeArgs": ["--preserve-symlinks"]` to launch.json but it had no effect.

**Comment by connor4312** [comment]
Glad to hear you found a workaround for your issue. Can you grab a trace log running with `--preserve-symlinks` so I can see why that wasn't working for you?

**Comment by jxmot** [comment]
Sure! Give me a day or two to get back to it.

**Comment by connor4312** [comment]
@JacksonKearl this morning also happened to hit a linked case where --preserve-symlinks in node didn't work. However I think we can be smarter in the debugger to avoid needing to require the flag, opened an investigation for next month: https://github.com/microsoft/vscode-js-debug/issues/776

**Comment by jxmot** [comment]
@connor4312 sorry about the delay, my plan is to get the logs to you very soon.

**Comment by connor4312** [comment]
Closing this as we've not heard anything recently. Feel free to ping me if you can collect logs.
