### ISSUE TITLE
Can't lauch "Extension Debug" since update 1.50

### ISSUE THREAD

**Issue by Raydir** [microsoft/vscode#107282]
Issue Type: <b>Bug</b>

Is it possible, that there is something wrong with the extension debug-host?

When I try to launch my Extension in Insider-Build  i get the following message:

The configured debug-type "pwa-node" is not supported
(translated from german).

Did I miss something?

VS Code version: Code - Insiders 1.50.0-insider (e6a742d2407c4a94c6540b49aa5f801468dbd1c8, 2020-09-22T18:23:14.500Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
xml|Dot|2.5.1
windows-explorer-context-menu|ele|2.0.0
gc-excelviewer|Gra|3.0.40
todo-tree|Gru|0.0.178
ilspy-vscode|ics|0.9.0
easy-icons|jam|0.3.1
prettify-json|moh|0.0.3
vscode-language-pack-de|MS-|1.49.1
cpptools|ms-|1.0.1
docthis|oou|0.8.2
opacciconbar|Opa|0.0.1
f-script|Opa|16.20.6
opacc-fscript-debug|Opa|16.20.1
snippets-view|use|0.2.7
cursorCharCode|zei|0.1.1

</details>

**Comment by connor4312** [comment]
If you enter `@id:ms-vscode.js-debug` in the "extension search", do you see the "JavaScript Debugger" extension? Did it get disabled at some point?

**Comment by Raydir** [comment]
@connor4312  I was disabled! 

Aw, thanx but how could that happen? Whatever, activating it did resolve the problem for me. Thank you!

**Comment by connor4312** [comment]
Good to hear! It's possible you hit an issue before and tried out the [nightly build](https://github.com/microsoft/vscode-js-debug/#nightly-extension) which requires disabling the built-in version (and perhaps never finished installing it or uninstalled it later)

**Comment by Raydir** [comment]
possible - I am gambling around with freatures a lot in the moment. Well thanx - "my users" will be happy to get the new version.
Regards
