### ISSUE TITLE
Unable to launch after install

### ISSUE THREAD

**Issue by macaranduba** [microsoft/vscode#107226]
- VSCode Version: 1.49.1
- OS Version: Windows 10 Enterprise, 64 Bits 
- NET. Framework Version: .NET Framework 4.7.1

Steps to Reproduce:

1. Install VSCode Insider, User, System or Zip version.
2. Error is presented as displayed in the image attached ("The window has crashed (reason: 'clean-exit')"). The error is always the same, no matter the version, since the first installation. Every new installation of a different version was preceded by the unistallation of the previous installed one. I'm behind a corporate environment and already tried with proxy setting flags (which i'm guessing are not being taking into account) and antivirus disabled. At home I don't have any problem with similar environment.

Does this issue occur when all extensions are disabled?: No. When any switch/flag (--disable-extensions, --verbose) is used for code command, no output is shown nor window is presented to the user.

![VSCodeFreshStart](https://user-images.githubusercontent.com/51032636/93879852-dff56100-fcb2-11ea-89f7-41d68b6199b1.png)

Thank for all the tips you can give!

**Comment by macaranduba** [comment]
Update: same result observed with VSCode Version: 1.40.1

**Comment by macaranduba** [comment]
Update: when I don't run the code command in the vscode home directory, I get the following result:
```
C:\Program Files>code
C:\Program Files>code -s
[main 2020-09-22T15:09:06.689Z] Error: connect ENOENT \\.\pipe\0b14439bfc5b011559f7c20e1c022056-1.49.1-shared-sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
```

**Comment by macaranduba** [comment]
Update: When I use the command-line switch --proxy-server="http=my_proxy_domain:80" the VSCode windows doesn't show up.

**Comment by macaranduba** [comment]
Hi, 
I found out that my organization blocks normal Windows 10 updates. Would this contribute for this problem I'm facing?
Any pointer for what could be originating this problem would be appreciated.

**Comment by macaranduba** [comment]
Update: also occurs in version
```
1.49.3
2af051012b66169dde0c4dfae3f5ef48f787ff69
x64
```

**Comment by macaranduba** [comment]
Would graphics card update help in this situation?

**Comment by deepak1556** [comment]
> When any switch/flag (--disable-extensions, --verbose) is used for code command, no output is shown nor window is presented to the user.

Rather than using code.cmd, for the user installation can you run the executable under the installed directory `C:\Users\<username>\AppData\Local\Programs\Microsoft Visual Studio Code\code.exe --enable-logging` and paste the output.

**Comment by macaranduba** [comment]
Sure. If I understood correctly, I didn't get any output at all when running:
```
C:\Users\myuser\AppData\Local\Programs\Microsoft VS Code>code.exe --enable-logging
C:\Users\myyser\AppData\Local\Programs\Microsoft VS Code>
```

**Comment by deepak1556** [comment]
Can you check for any running instances of code in task manager and kill them.

Also are you using powershell, if not can you try with it.

**Comment by macaranduba** [comment]
I think I don't have nay other VSCode instances running at the same time. 
Using PowerShell, i was unable to run code.exe, but using code 
![image](https://user-images.githubusercontent.com/51032636/95250217-29d06200-07f0-11eb-8da4-971efec31327.png)

**Comment by deepak1556** [comment]
> Using PowerShell, i was unable to run code.exe

What error was shown ?

Also looks like you are using an admin shell, can you try running under user shell.

**Comment by macaranduba** [comment]
Finally, I was able to run Code.exe, but no output nor VSCode window is launched. If I run it without the `--enable-logging` flag, VSCode window is presented like described in the first post of this thread.

I only have this user which has administrator rights. How can I try to run PowerSheel without admin rights?

```
PS C:\Users\my_user> "C:\Users\my_user\AppData\Local\Programs\Microsoft VS Code\Code.exe"
C:\Users\my_user\AppData\Local\Programs\Microsoft VS Code\Code.exe
PS C:\Users\my_user> 'C:\Users\my_user\AppData\Local\Programs\Microsoft VS Code\Code.exe'
C:\Users\my_user\AppData\Local\Programs\Microsoft VS Code\Code.exe
PS C:\Users\my_user> & 'C:\Users\my_user\AppData\Local\Programs\Microsoft VS Code\Code.exe'
PS C:\Users\my_user>
PS C:\Users\my_user> 0.525Z] update#setState idle
PS C:\Users\my_user> 2.202Z] [VS Code]: renderer process crashed (detail: clean-exit)
PS C:\Users\my_user>
PS C:\Users\my_user> & 'C:\Users\my_user\AppData\Local\Programs\Microsoft VS Code\Code.exe' --enable-logging
PS C:\Users\my_user>
```

Thanks for all your patience!

**Comment by deepak1556** [comment]
Can you try the following,

```
PS C:\Users\my_user> set ELECTRON_NO_ATTACH_CONSOLE=1
PS C:\Users\my_user> set ELECTRON_ENABLE_LOGGING=1
PS C:\Users\my_user> & 'C:\Users\my_user\AppData\Local\Programs\Microsoft VS Code\Code.exe' --v=1
```

this might open up a bunch of consoles, make sure to get the logs generated from all of them.

**Comment by macaranduba** [comment]
Sure.

Setting variables.
```
PS C:\Users\my_user> set ELECTRON_NO_ATTACH_CONSOLE=1
PS C:\Users\my_user> set ELECTRON_ENABLE_LOGGING=1
```
Checking variables.
```
PS C:\Users\my_user> Get-Variable

Name                           Value
----                           -----
ELECTRON_ENABLE_LOGGING=1
ELECTRON_NO_ATTACH_CONSOLE=1
```
Running with the --v=1 flag does not launch any console nor logs any output. When trying to run the same command without the that flag, I get the window attached to the first post of this thread.

```
PS C:\Users\my_user> & 'C:\Users\my_user\AppData\Local\Programs\Microsoft VS Code\Code.exe' --v=1
PS C:\Users\my_user>
PS C:\Users\my_user>
```

Thanks!

**Comment by macaranduba** [comment]
Running the same command but passing the . (current folder as folder to be opened by vscode), opens the window as in the original post of this thread, and gives more output:

```
PS C:\Users\my_user> & 'C:\Users\my_user\AppData\Local\Programs\Microsoft VS Code\Code.exe' . --v=1
PS C:\Users\my_user>
[main 2020-10-07T19:12:54.387Z] update#setState idle
[5068:1007/161255.178:ERROR:paint_controller.cc(646)] PaintController::FinishCycle() completed
[main 2020-10-07T19:12:55.316Z] [VS Code]: renderer process crashed (detail: clean-exit)
```

**Comment by deepak1556** [comment]
hmm weird, couple more checks.

* Can you download https://github.com/electron/electron/releases/download/v9.2.1/electron-v9.2.1-win32-x64.zip
* set ELECTRON_NO_ATTACH_CONSOLE=1
* set ELECTRON_ENABLE_LOGGING=1
* Extract and run it like `<extracted-folder>/electron.exe https://github.com --v=1`
* Do you see any window and logs ?


Also can you confirm if you are able to launch the editor from the file explorer instead of command line ?

**Comment by macaranduba** [comment]
Sorry @deepak1556, I'm starting to think that the problem is the Symantec antivirus program.

From the logs of that antivirus, I get the info that it took the action of terminate Code.exe atfer it attempt to read the following path:
`c:\Users\my_user\AppData\Local\Programs\Microsoft VS Code\resources\app\out` .
Weird because my user has admin privilegies, so I' guessing that while my helpdesk team doesn't reply we should freeze this thread (is there a way or should I close it?).

Meanwhile, when I run 
`<extracted-folder>electron.exe` 
from the command line, after setting the two above environment properties, the following window is realized:
![image](https://user-images.githubusercontent.com/51032636/95456793-42eb2700-0946-11eb-851a-6d25dad4b043.png)

Nothing happends if I run the same command but with the flags:
`<extracted-folder>/electron.exe https://github.com --v=1`

Thanks @deepak1556 !

**Comment by macaranduba** [comment]
Yep, Symantec log access to powersheel.exe is blocked and when I'm try to execute I also don't have enought user rights to do so. I found that it is possible to configure the settings.json to make VCode use CMD instead PowerShell, but I didn't found that configuration file on my system.
By the way, the PowerSheel I used before was an instance installed by myself.

**Comment by deepak1556** [comment]
> From the logs of that antivirus, I get the info that it took the action of terminate Code.exe after it attempt to read the following path:
c:\Users\my_user\AppData\Local\Programs\Microsoft VS Code\resources\app\out .
Weird because my user has admin privilegies, so I' guessing that while my helpdesk team doesn't reply we should freeze this thread (is there a way or should I close it?).

Nice find, in that case lets close this issue for now and if there is anything we need to look from the app perspective can reopen the issue.

>  I found that it is possible to configure the settings.json to make VCode use CMD instead PowerShell, but I didn't found that configuration file on my system.

You should be able to configure via settings from command palette, https://code.visualstudio.com/docs/editor/integrated-terminal#_windows . Does that not work ?

**Comment by macaranduba** [comment]
I guess that for accessing command palette I would be able to open VSCode's main window, right? I'm realizing also that any command-line parameters is being ignored or cannot be taking into account by code.exe. I'll be waiting for my HelpDesk support and get back here with the findings.
Thanks!
