### ISSUE TITLE
Window crashes when remote file becomes unavailable.

### ISSUE THREAD

**Issue by default-account-name** [microsoft/vscode#107244]
Issue Type: <b>Bug</b>

When editing a file located on a network share, if the network share becomes unavailable (i.e., the share goes offline), the window will crash.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 19.6.0

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
