### ISSUE TITLE
Able to open a file and focus on editor (like in old behaviour)

### ISSUE THREAD

**Issue by kahoot-karl** [microsoft/vscode#107232]
I'd like to be able to open a file using a keyboard shortcut from the filesExplorer that puts focus on the editor. I don't see this option here:

![image](https://user-images.githubusercontent.com/64776986/93888588-7ee88000-fce8-11ea-9829-13d10de8396f.png)

Thanks guys!

**Comment by kieferrm** [comment]
I think you look for 
![image](https://user-images.githubusercontent.com/4674940/94023992-b9dfc780-fd6b-11ea-8282-2393a88e0b2a.png)

**Comment by kahoot-karl** [comment]
Great, thanks
