### ISSUE TITLE
go back and go forward keybinding not work on mac

### ISSUE THREAD

**Issue by milter001** [microsoft/vscode#107229]
- VSCode Version:
1.49
- OS Version:
macOS
Steps to Reproduce:

1. move cursor to another place in the same file 
2. press ^ - 
3. not go back but sometimes it does work, very confusing

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by milter001** [comment]
i have forbidden all the plugins and not use any key change software, and also change the key binding to ctrl+/, the question still exists

**Comment by alexdima** [comment]
@milter001 Let's try to understand if this is a problem with the keybinding or with the action.

#### 1. Can you please try running the action directly from the Go menu. Does the action execute as you expect?
#### 2. Can you please try troubleshooting your keybindings. Simply follow the steps at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting to see which keybinding rule executes.

**Comment by milter001** [comment]
i have tried from the go menu, the action execute some like randomly。my keybinding logs are as below:
[2020-09-23 12:41:08.047] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2020-09-23 12:41:08.047] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2020-09-23 12:41:08.047] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched.
[2020-09-23 12:41:08.362] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: Minus, keyCode: 189, key: -
[2020-09-23 12:41:08.362] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: Minus, keyCode: 83 ('-')
[2020-09-23 12:41:08.362] [renderer1] [info] [KeybindingService]: | Resolving ctrl+[Minus]
[2020-09-23 12:41:08.362] [renderer1] [info] [KeybindingService]: \ From 1 keybinding entries, no when clauses matched the context.

**Comment by milter001** [comment]
i want to know if my understanding  is wrong.  i think  the go back and forward action meaning is go back or forward to last or next cursor location in the same file when i edit my code

**Comment by alexdima** [comment]
> i have tried from the go menu, the action execute some like randomly

That is the action implementation. If you have clear steps when the action does not work as expected, then please let us know.

> my keybinding logs are as below

You are pressing <kbd>ctrl</kbd>+<kbd>minus</kbd> but it looks like you have modified the default keybindings. By default, vscode ships with two keybindings bound to `ctrl+-` and it looks like only one remains on your system. Here is the default:

![image](https://user-images.githubusercontent.com/5047891/93986005-164fe080-fd86-11ea-97c5-07210260bb7a.png)

So it is my opinion that you  have edited your `keybindings.json` around this keybinding. Can you please open your `keybindings.json` and comment out your customizations?

**Comment by milter001** [comment]
> > i have tried from the go menu, the action execute some like randomly
> 
> That is the action implementation. If you have clear steps when the action does not work as expected, then please let us know.
> 
> > my keybinding logs are as below
> 
> You are pressing ctrl+minus but it looks like you have modified the default keybindings. By default, vscode ships with two keybindings bound to `ctrl+-` and it looks like only one remains on your system. Here is the default:
> 
> ![image](https://user-images.githubusercontent.com/5047891/93986005-164fe080-fd86-11ea-97c5-07210260bb7a.png)
> 
> So it is my opinion that you have edited your `keybindings.json` around this keybinding. Can you please open your `keybindings.json` and comment out your customizations?

yes,  but problem can not be solved by reset default keybinding

**Comment by alexdima** [comment]
@milter001 Your keybindings file must be a mess by now. You can see in the Source column in your screenshot that it all says "User". So it means you have a lot of keybindings targetting `ctrl+[Minus]` in your `keybindings.json` file. Please execute `F1 > Open Keyboard Shortcuts (JSON)` and remove all its contents or comment it out or something.

If you never edited that file directly, and only interacted with the visual keybindings UI, then what steps did you do that led to something you did not expect? Maybe there is a bug there, but we need reproducible steps.

**Comment by milter001** [comment]
first, i remove user keybindings, you can see from below :
![image](https://user-images.githubusercontent.com/16049564/94145839-b6505b80-fea5-11ea-9cf1-9cee6ecf5390.png)

now, my cursor is at 8th line. 

![image](https://user-images.githubusercontent.com/16049564/94146080-03343200-fea6-11ea-8328-a7cb406f197a.png)


now, i move it to 12 line.

![image](https://user-images.githubusercontent.com/16049564/94146127-11824e00-fea6-11ea-9196-7d94b8e0d9a7.png)

now, i press ^- , then the edior jump to  keyboard shortcuts window, which i opened recently.

![image](https://user-images.githubusercontent.com/16049564/94146262-455d7380-fea6-11ea-88ad-4b288f9dd270.png)

**Comment by alexdima** [comment]
@milter001 Please remove all keybindings from your `keybindings.json`. Please disable all extensions.
What does VS Code detect when you press the desired key combination? Here is a GIF about how to go to the `keybindings.json` file:

![keyboard-input](https://user-images.githubusercontent.com/5047891/80482640-da3e5e00-8954-11ea-9583-0f652b0595a8.gif)

**Comment by milter001** [comment]
i can not find define keybindings button when i open the json file. but i record my press key through recording, you can see below:
![image](https://user-images.githubusercontent.com/16049564/94148202-e5b49780-fea8-11ea-9fdf-f9126348710d.png)

**Comment by alexdima** [comment]
@milter001 :+1: From your latest screenshot, I see that `ctrl+-` is now bound from the Default source to two commands. This is great, it looks like all the custom keybindings were removed. 

Can you now please follow my initial steps. (Simply follow the steps at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting to see which keybinding rule executes). We will now see which command executes.

**Comment by milter001** [comment]
![image](https://user-images.githubusercontent.com/16049564/94394189-513f8300-018f-11eb-9515-0e6bbca11cab.png)

**Comment by alexdima** [comment]
@milter001 Your latest screenshot is incomplete. Can you please provide the entire log such that we can see which commands executes. I believe the very last line got clipped in the screenshot above.

**Comment by milter001** [comment]
[2020-09-29 09:31:09.137] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2020-09-29 15:59:19.281] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2020-09-29 15:59:19.281] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2020-09-29 15:59:19.282] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched.
[2020-09-29 15:59:19.624] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: Minus, keyCode: 189, key: -
[2020-09-29 15:59:19.624] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: Minus, keyCode: 83 ('-')
[2020-09-29 15:59:19.624] [renderer1] [info] [KeybindingService]: | Resolving ctrl+[Minus]
[2020-09-29 15:59:19.624] [renderer1] [info] [KeybindingService]: \ From 2 keybinding entries, matched workbench.action.navigateBack, when: no when condition, source: built-in.

**Comment by alexdima** [comment]
@milter001 Thank you. So it looks that everything is correct now:
> From 2 keybinding entries, matched workbench.action.navigateBack, when: no when condition, source: built-in.

So when you pressed `ctrl+[minus]` the action `workbench.action.navigateBack` is invoked correctly. So I believe your initial issue is resolved, and it appears it was caused by customizations done in `keybindings.json`. It is unclear how these changes in `keybindings.json` occurred and if this was a bug or just bad configuration.
