### ISSUE TITLE
"Git: Failed to execute git" on commit via UI - works on console

### ISSUE THREAD

**Issue by dominik-fielmann** [microsoft/vscode#107298]
Issue Type: <b>Bug</b>

In a npm project with husky precommit hooks I do the following in the VS Code UI:
- Stage 2 files
- Enter a commit message
- Press the checkmark to commit

The following error appears:

> Git: Failed to execute git

The git log shows the following output:

> git commit --quiet --allow-empty-message --file -
> git config --get-all user.name
> git config --get-all user.email

That's it, no error output whatsoever.

If I commit via the command line, everything works fine. Husky runs the precommit tasks and then the files are committed.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 5.4.0-48-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2999)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 2|
|Memory (System)|15.52GB (2.61GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 89f4fd38-e0fa-43cb-922e-d7a61be157c8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.6
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-css-modules|cli|0.2.3
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.6.0
shell-format|fox|7.0.1
lintlens|ghm|3.0.0
vscode-pull-request-github|Git|0.20.0
go|gol|0.17.0
vscode-test-explorer|hbe|2.19.1
vscode-test-explorer-liveshare|hbe|1.0.5
npm-dependency-links|her|1.1.0
vscode-npm-dependency|how|1.2.2
bash-ide-vscode|mad|1.11.0
vscode-scss|mrm|0.9.0
vscode-cosmosdb|ms-|0.15.0
vscode-docker|ms-|1.6.0
python|ms-|2020.8.109390
remote-wsl|ms-|0.44.5
azure-account|ms-|0.9.3
vsliveshare|ms-|1.0.2740
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-jest|Ort|3.2.0
vscode-versionlens|pfl|1.0.8
vscode-graphql|Pri|0.3.7
vscode-yaml|red|0.11.0
vscode-sort-package-json|uni|1.2.2
vscodeintellicode|Vis|1.2.10

</details>

**Comment by joaomoreno** [comment]
Strange. Can you show me the full output of `Git: Show Git Output` of such a session?
