### ISSUE TITLE
'Run' sidebar: Launching multiple sessions causes 'More' button to be hidden

### ISSUE THREAD

**Issue by amitbeck** [microsoft/vscode#107236]
![VSCode_Run_sidebar_UI_bug](https://user-images.githubusercontent.com/22454058/93896690-e6f39200-fcf9-11ea-893b-8a69f2466ea9.png)

- VSCode Version: 1.49.0
- OS Version: Fedora 31

Steps to Reproduce:

1. Launch a session
2. Use the 'More' button (`.actions-container > action-item:nth-child(8) > .monaco-dropdown > .dropdown-label > .action-label`) to launch another session

The 'More' button will now be hidden because of overflow caused by buttons added to the actions bar.

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by isidorn** [comment]
I acknlowedge this issue. But yeah there's not enough space there.
Suggestions on how to improve this are welcome

**Comment by amitbeck** [comment]
@isidorn Maybe make the buttons wrap at some break-point of minimum width?

**Comment by isidorn** [comment]
That would be a general pattern across the workbench which we currently do not do.
Though I think it makes sense but it should be consitent across views.
