### ISSUE TITLE
Delay so much when second time of clicking "Go to definition (F12)"

### ISSUE THREAD

**Issue by pizzacrystal** [microsoft/vscode#107281]
版本: 1.49.1 (system setup)
提交: 58bb7b2331731bf72587010e943852e13e6fd3cf
日期: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. move the cursor to a build-in function of python, then press "F12"
2. close the new tab for showing definition, then press "F12" again
3. tab shows immediately after step 1 but delay so much after step 2 as the screenshot below, 

![image](https://user-images.githubusercontent.com/11605580/93979491-faf9cb00-fdaf-11ea-9d14-a48ba7bd1ee8.png)

4. if hover on the function rather than pressing "F12", it shows "loading" for more than 1 minutes, as below figure shows,

![image](https://user-images.githubusercontent.com/11605580/93979837-693e8d80-fdb0-11ea-955f-98469a3d26e1.png)

Does this issue occur when all extensions are disabled?: No, because "Go to definition" is disabled when python extension is disabled.

**Comment by kieferrm** [comment]
\extPython
