### ISSUE TITLE
Workbench issue when no editors are open

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#107262]
Comment out all settings, restart vscode, close the welcome page, and I am missing the watermark/keybinding tips. And you can see an empty tab bar.

![image](https://user-images.githubusercontent.com/323878/93941655-857cf480-fcf4-11ea-90a0-da75fd175076.png)

If I open a file (settings.json) and close it, I get this:

![image](https://user-images.githubusercontent.com/323878/93941803-ce34ad80-fcf4-11ea-835d-6ba5a3641bb0.png)

**Comment by bpasero** [comment]
@roblourens I cannot reproduce, can you provide steps and let me know if this is insiders?

Also please check devtools for output.

**Comment by roblourens** [comment]
It was happening reliably yesterday but not today. There was nothing in devtools yesterday.
