### ISSUE TITLE
Commit Message is lost when closing VSCode

### ISSUE THREAD

**Issue by Nagarian** [microsoft/vscode#107295]
- VSCode Version: 1.49.1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Go to Source Control Panel
2. Type a commit message
3. Close VSCode
4. Reopen VSCode
5. Go to Source Control Panel, the typed commit message is lost !
![vscode-commit-message-bug](https://user-images.githubusercontent.com/3041932/94013465-65a80800-fdaa-11ea-9b68-8da3c8ddbdb9.gif)

Does this issue occur when all extensions are disabled?: Yes, I've tested it, the bug occurs event with extensions disabled

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/41232
