### ISSUE TITLE
Allow setting custom syntax to string template literal tags

### ISSUE THREAD

**Issue by pie6k** [microsoft/vscode#107248]
Let's say I've got custom template literal tag like

```ts
myCustomTag`
  <div>foo</div>
`
```

and I'd like to use HTML syntax highlighting for it. 

I can create custom extension for it to add proper rules to support it. But this sounds a bit like overkill and would only work for this specific tag name (`myCustomTag`) in example above.

Possible solution is to use https://marketplace.visualstudio.com/items?itemName=bierner.comment-tagged-templates extension that allows me to do

```ts
const cssString = foo<{elo: string}>/* css */`
    button {
        color: hotpink !important;
    }
`;
```

Which works, but syntax looks quite ugly and I have to repeat it on every tag.

Setting in `settings.json` could look something like

```json
    "language.javascript.template.associations": {
      "someTag": {
        "syntax": "html"
      }
    }
```

<img width="518" alt="CleanShot 2020-09-22 at 18 16 55@2x" src="https://user-images.githubusercontent.com/7311462/93909213-d219fd00-fcff-11ea-8161-0fd3c369f77d.png">

**Comment by mjbvz** [comment]
A custom extension could also enable for template string syntaxes besides comments
