### ISSUE TITLE
Hover: font size is larger than what I hover over

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107278]
The workbench typically defines a font size of `13px` but somehow the hover sets it to `14px` meaning that the hover text is always larger compared to the text.

https://github.com/microsoft/vscode/blob/c80b8a3318e6ea354061be254a69f148c2c500b2/src/vs/workbench/services/hover/browser/media/hover.css#L8-L8

Worth mentioning that the native hover on macOS seems to have an even smaller font size.

//cc @alexr00 @misolori

**Comment by misolori** [comment]
Agreed, the base font size should match our default (13px):

![image](https://user-images.githubusercontent.com/35271042/94074782-d0f3d900-fdae-11ea-9fce-a58bfb95b779.png)
