### ISSUE TITLE
Block sostitution with vim extension replaces text in a different location

### ISSUE THREAD

**Issue by fsoft72** [microsoft/vscode#107200]
- VSCode Version: 1.49.1
- OS Version: Kubuntu 20.04

Steps to Reproduce:

1. Copy a portion of source code
2. Paste the source code right below the original code
3. Select with SHIFT+cursors the just pasted portion of code
4. Try to replace some strings in the text using the ':s' command, this way:
    

> :<,>s/origText/newText/g

5. The text is replaced in the original code and not in the selected and pasted code

I have attached a small video showing what I mean. For the substitution part, please look at the bottom toolbar.

[2020-09-22 06-53-03.zip](https://github.com/microsoft/vscode/files/5259262/2020-09-22.06-53-03.zip)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by fsoft72** [comment]
what do you mean with "/extVim"   this behavior never happened in previous versions of VSCode

**Comment by gjsjohnmurray** [comment]
I suggest you report it to the vim extension repository.

**Comment by rebornix** [comment]
Please file this issue against the Vim extension, thanks!
