### ISSUE TITLE
Add option to remove tab close buttons

### ISSUE THREAD

**Issue by jez9999** [Microsoft/vscode#10739]
There should be a preference for removing tab close buttons (it just needs to apply the css style ".close-editor-action {display:none;}" to the interface) - tab close buttons make it too easy to accidentally close a tab, and you can use middle-click instead anyway.

**Comment by jez9999** [comment]
@bpasero @hashhar As this has now been implemented by you when will it get checked into the main codebase?

**Comment by bpasero** [comment]
@jez9999 @hashhar I am not seeing a PR yet?

**Comment by hashhar** [comment]
@bpasero @jez9999 I am only able to hide and show the close buttons but they don't refresh automatically. You would have to at least drag the tab to make the setting take effect.

I am unable to get it to repaint the window at my will.
I'll look into it again but right now I have campus placement sessions coming up so I'm a little too busy.

**Comment by jez9999** [comment]
@hashhar Your patch modifies the code where the tabs are created, but is there a way to apply a global stylesheet to the UI?  If so, you could just add or remove a CSS styling that hides all the tab close buttons.  That seems the most straightforward way to do it.

**Comment by bpasero** [comment]
@hashhar also keep in mind that you do not want to hide the dirty decorator which is drawn on top of the close action.

**Comment by hashhar** [comment]
Thanks for the input. I'll take it up again after the placements are over.

**Comment by jez9999** [comment]
@hashhar How long will the placements take?  This seems like a very small patch and I'd **really** like to get rid of those tab close buttons as soon as possible. :-)

**Comment by hashhar** [comment]
You are welcome to try and write a patch if you would like. I think it should be over by 28th of this month.

**Comment by jez9999** [comment]
@hashhar Bump!  Any chance of progressing on this issue now? :-)

**Comment by hashhar** [comment]
I am not able to figure out how tabs are drawn. I think I have a long week ahead of me of stepping through the entire codebase to learn how stuff works.

**Comment by jez9999** [comment]
@hashhar Did you get anywhere with this?  I just closed *another* tab accidentally!  Grrrr!

**Comment by bpasero** [comment]
Pushed this behind a new setting `workbench.editor.showTabCloseButton`. The dirty indicator when visible serves as action to save the file:

![editors](https://cloud.githubusercontent.com/assets/900690/19958065/4a75de68-a19c-11e6-9cad-6b8edb0f9133.gif)

**Comment by PunchyRascal** [comment]
I am sorry to maybe sound a little negative, but IMO the reason why people wanted to remove the close button is because they don't want to accidentally push any buttons while switching tabs, just being free to press anywhere on the tab, without worrying what will happen - at least I do. So to replace a close button with another button is a bit counter productive. Maybe add settings for it too?

**Comment by jez9999** [comment]
Exactly.

@bpasero While having the indicator save the document is at least a lot less destructive that closing it, I'm still disappointed you didn't just use my code.  The idea is that we want to be able to click the tab button with *no side effects* apart from selecting or moving the tab.  Your solution gives the side effect of saving.  I still suggest you back this out and implement my patch.

**Comment by bpasero** [comment]
@PunchyRascal thanks for your comment on this, I see the issue and pushed a fix for it.

**Comment by jez9999** [comment]
Nice.  No tab buttons, and a dirty indicator implemented through CSS.  Works great!
