### ISSUE TITLE
${value} is not working

### ISSUE THREAD

**Issue by iamsrijithsj** [microsoft/vscode#107369]
- VSCode Version:1.49.1
- OS Version:windows 10 pro

Steps to Reproduce:

1.let val5=prompt('enter a number');
let num=50;
let third="nothing";
if(val5>num){
  third='yes it is greater than ${num}';

}
else if(val5==num) {
//the element inside ${value} is not taking as  a element instead printing out as a string   
third= '${val5} is  equal to ${num}';
}
else {
  third='${val5} is less than ${num}';
}
document.getElementById('third').innerHTML=third;
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

You should be using back-single-quotes for the string.

**Comment by iamsrijithsj** [comment]
thanks a lot :)

**Comment by gjsjohnmurray** [comment]
Please close this issue.
