### ISSUE TITLE
Convert indentation to spaces for selection

### ISSUE THREAD

**Issue by pselle** [microsoft/vscode#107382]
A re-opening of:
- https://github.com/microsoft/vscode/issues/7415

I would like to be able to convert a section of a file from tabs to spaces, versus the whole file. This is particularly because sometimes ex. output tests require specific whitespace, and so I spend a lot of time manually changing the whitespace by hand, when I know the whole text block needs to be converted to spaces ... however, that doesn't need to happen for the whole file.

Thank you!

**Comment by mfox1** [comment]
I agree, this would be very useful.

**Comment by dlindhurst** [comment]
@pselle @mfox1 I just published the [TabSpacerSelect](https://marketplace.visualstudio.com/items?itemName=dlindhurst.tabspacerselect) extension that does this.
