### ISSUE TITLE
Question about sort menu items

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#10734]
- VSCode Version: 1.5.0-insider (3d9622208b2167921b6664e04fd1fbd51507a4a0)
- OS Version: Windows 10 Redstone 1

How are sorted the items in the menu? I would like to put item before or after `copy`, `copy path`, `rename` and `delete`.

### Case 1. `"group": "navigation"`

```json
"menus": {
  "explorer/context": [{
    "command": "duplicate.execute",
    "group": "navigation"
  }]
}
```

![image](https://cloud.githubusercontent.com/assets/7034281/17830045/7710f36c-66c9-11e6-94ef-0962454b480b.png)

### Case 2. `"group": "1_modification"`

> This group comes next and contains commands that modify your code.

```json
"menus": {
  "explorer/context": [{
    "command": "duplicate.execute",
    "group": "1_modification"
  }]
}
```

![image](https://cloud.githubusercontent.com/assets/7034281/17830055/9f6fbfd2-66c9-11e6-9b31-df046957634b.png)

### Case 3. `"group": "9_cutcopypaste"`

> The last default group with the basic editing commands.

```json
"menus": {
  "explorer/context": [{
    "command": "duplicate.execute",
    "group": "9_cutcopypaste"
  }]
}
```

![image](https://cloud.githubusercontent.com/assets/7034281/17830059/b9853fc8-66c9-11e6-9a58-ddd957367855.png)

Also in the documentation there is no information that there are groups except `navigation` (https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus).

**Comment by mrmlnc** [comment]
Oh, sorry, seems I didn't properly read this:

> You can add menu items to these groups or add new groups of menu items in between, below, or above. In this release, only the editor context menu allows this grouping control but it **will soon** be available for the editor title menu and the **explorer context** menu as well.

**Comment by jrieken** [comment]
Yeah - we are not yet fully done with the menu story. It's stretch for August and likely September when that lands
