### ISSUE TITLE
IntelliSense Should Maintain Multi-Line-Ness, Even if Not a List

### ISSUE THREAD

**Issue by SlurpTheo** [microsoft/vscode#107388]
- VSCode Version: 1.48.2 (user setup)
- OS Version: Windows_NT x64 10.0.18363

In a TypeScript file.
If my header has been formatted with multiple-lines of text, why not trust/show that (even if it doesn't look explicitly formatted like a list)?

Parameter `a` looks OK:
<br /> 
![image](https://user-images.githubusercontent.com/5269716/94207326-0111a980-fe8d-11ea-9599-96da551524f0.png)

However parameter `b` isn't what I was going/hoping for:
<br /> 
![image](https://user-images.githubusercontent.com/5269716/94207383-1c7cb480-fe8d-11ea-8412-9bcff3214e3a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is [standard markdown behavior](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22a%5Cnb%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Atrue%2C%22_view%22%3A%22html%22%7D%7D).

To create a new paragraph (i.e. a new line) you need to either have two new lines:

```md
one

two
```

Or you can end the first line with two spaces:

```md
one  
two
```

**Comment by mjbvz** [comment]
Also, the first case works because the new line defines a list since it starts with `*`
