### ISSUE TITLE
Debug hovers often stop working after debugging for a bit

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#107391]
This feels relatively recent, but I've been having a lot of issues with debug hovers not showing up over variables, etc. I don't have any reproducible steps, except for it seems to happen after debugging for a little while. And when it happens, the variables view will still show the contents of the variable I try to hover over.

**Comment by eamodio** [comment]
It might have to do with switching away from vscode while debugging and back. Since I just did that, and when I came back to vs code the hovers I was getting were GitLens rather than debug. And then when I stepped to the next line all hovers went away.

**Comment by isidorn** [comment]
@eamodio thanks Erich for reporitng this. This is probably related to this change https://github.com/microsoft/vscode/issues/84561
In short: when holding `alt` we hide the debug hover on purpose. Though it should come back when you are not holding the `alt` key.
Now that you know the motiviation behind the change it might be easier to find repro steps? Where you holding the `alt` key or was it unrelated to this?

**Comment by eamodio** [comment]
@isidorn it definitely is related to `alt`. It seems when I `alt+tab` out of vscode, vscode still thinks `alt` is down (or it just never gets the up) so it stops showing the debug hovers until I press `alt` again.

Also given that `alt` by itself (on Windows) focuses the menu bar it seems like that would be an issue (although I have the `alt` focusing the menu bar turned off)

**Comment by isidorn** [comment]
@eamodio I can also listen to some focus lost and restart it then. Hopefully that should fix it.
