### ISSUE TITLE
Webview copy/paste shortcuts broken in 1.50-insiders

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#107309]
Version: 1.50.0-insider
Commit: f943318042a3b9229049aea86cea04d0ff9c8210
Date: 2020-09-23T05:28:07.760Z (11 hrs ago)
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Download the vscode extension samples (https://github.com/microsoft/vscode-extension-samples.git) 
2. Modify the html in the cat coding webview sample to have a `<input>`
3. Run the cat coding webview
4. Type some text into the text area, select it, and try to ctrl+c / ctrl+v

Ctrl+c doesn't write to the clipboard, and ctrl+v has no effect.

This is causing https://github.com/microsoft/vscode-python/issues/14053 in the Python extension. I was on 1.48-insiders right before updating to repro this with our customer's setup, and this bug was not present in that build.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Do you see it in 1.49 as well?

**Comment by mjbvz** [comment]
Actually, pretty simple fix. I suspect it's in 1.49 too but not on web (and not with iframe based webviews on desktop)

**Comment by joyceerhl** [comment]
@mjbvz, do you know when this fix will become available in insiders? I see that this issue is tagged `released`, but we had another customer report the same issue 4 days ago: https://github.com/microsoft/vscode-python/issues/14095, and I still repro the problem locally. Thanks so much 😊

**Comment by mjbvz** [comment]
I just tested using 772aa0723f7f6b04b710bc3a92b7a904b60ef439 on Mac and Windows and it seems to be fine. Can you verify you are on that build and that copy/paste doesn't work in the sample extension specifically

**Comment by joyceerhl** [comment]
Ah yes it seems to work fine with the sample extension. Thanks Matt!
