### ISSUE TITLE
lineNumber variable doesn't work when used inside `window.title`

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#107370]
- VSCode Version: 1.50-insider
- OS Version: 11.0

Steps to Reproduce:

1. edit VSCode setting `"window.title": "${activeEditorShort}${separator}${lineNumber}",`
2. open some file and look at window and see:

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/6391776/94175130-877eb900-fe96-11ea-9f2a-8f09071aba68.png">

No line number gets shown in the window title.

I expect to see `settings.json - 37` in above screenshot as window title.

I saw `${lineNumber}` variable defined here https://code.visualstudio.com/docs/editor/variables-reference. Perhaps it's not possible to use it in this context. If not, can it be added?

Thank you.

**Comment by bpasero** [comment]
This is the list:

![image](https://user-images.githubusercontent.com/900690/97701894-68370500-1aae-11eb-9748-62923a124fed.png)
