### ISSUE TITLE
Debug hovers seem to no longer have a max height

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#107394]
![image](https://user-images.githubusercontent.com/641685/94210250-32de3c80-fe9c-11ea-8740-6e29ff7ecfac.png)

**Comment by isidorn** [comment]
@eamodio thanks for feedback, this was a delibarate design decision. There is a maximum it depends on the editor height.
I can reduce it a bit if you think it is too much

Here's the related issue https://github.com/microsoft/vscode/issues/106865

@eamodio let me know what you think

**Comment by eamodio** [comment]
@isidorn that issue says it should have a height max of up to 70%, but it seems to be much more than that -- even in that screenshot. I feel like 70% would be reasonable.

It seems like something else is going wrong too with the sizing -- in this screenshot, I expanded items in the hover and it just kept growing right off the bottom of the screen.

![image](https://user-images.githubusercontent.com/641685/94284282-24d1ff80-ff20-11ea-8fb6-b377a5d46631.png)

**Comment by isidorn** [comment]
I will reduce the max.

**Comment by isidorn** [comment]
Actually I was getting the editor layout height wrongly. Fixed that now and it should be better. Let me know how it works for you, thanks!

**Comment by eamodio** [comment]
Looks much better now -- thanks!
