### ISSUE TITLE
Improve default diff view w/ metadata changes

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#107385]
The current view when running the same notebook that has no code changes but has metadata/output change takes up quite amount of vertical real estate (related to https://github.com/microsoft/vscode/issues/105916):

![image](https://user-images.githubusercontent.com/35271042/94204622-6c9c4c80-fe76-11ea-949a-53aa5332ea62.png)

One idea about improving this is using an icon + coloring the text the same color as our modified indicator and collapsing it by default. This gives the user more real estate while still drawing attention to changes. I think we tried something similar before (bold + collapsed) but that didn't seem to provide enough of an indication. 

![Frame 38](https://user-images.githubusercontent.com/35271042/94204929-0f54cb00-fe77-11ea-8716-cfd40cd75508.png)

**Comment by claudiaregio** [comment]
Second this design, this looks great! 
- Still keeps the notebook feel 
- Not as code dense
- Less vertical space taken up 
- Bright color + icon makes it hard to miss the indicated changes

**Comment by IanMatthewHuff** [comment]
Looks great. One quick question, what is the "dot in square" icon? Confess that I don't quite get what that icon means and it almost looks like an actionable checkbox.

**Comment by misolori** [comment]
@IanMatthewHuff it's from our `diff` icons, they originated from GitHub's icon system:

[**Codicons**](https://microsoft.github.io/vscode-codicons/dist/codicon.html)
<img width="400" src="https://user-images.githubusercontent.com/35271042/94580589-f493a500-022e-11eb-9ccd-1db77f2ddb60.png">

[**GitHub Desktop**](https://desktop.github.com/)
<img width="400" src="https://user-images.githubusercontent.com/35271042/94580652-0412ee00-022f-11eb-91bd-a34c672fbd3c.png">

**Comment by misolori** [comment]
I think this isn't an issue anymore as when metadata changes occur we expand and highlight it:

<img width="774" alt="CleanShot 2021-10-05 at 07 35 45@2x" src="https://user-images.githubusercontent.com/35271042/136044402-ec782c8d-54e8-46e1-9d56-7d7fecc21e56.png">
