### ISSUE TITLE
Cursor and hover highlight ghosting on screen on dark themes

### ISSUE THREAD

**Issue by rodrigocaus** [microsoft/vscode#107319]
- VSCode Version: 1.50.1 (user setup)
- OS Version: Windows x64 10.0.19042
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0

Steps to Reproduce:

1. Open terminal
2. Press "space" and than move cursor back

Occurs in both Windows and WSL.
![vscode_glitch](https://user-images.githubusercontent.com/20566121/94055663-ace6c680-fdb3-11ea-9181-b29866eab94a.gif)
![vscode_glitch2](https://user-images.githubusercontent.com/20566121/94055671-afe1b700-fdb3-11ea-9686-0264cc7d4af6.gif)

Disable hardware acceleration does not solve.
Force color rendering to "srgb" does not solve.

Does this issue occur when all extensions are disabled?: No

**Comment by Tyriar** [comment]
For terminal cursor see #106981

@deepak1556 on menu ghosting

**Comment by rodrigocaus** [comment]
```terminal.integrated.rendererType``` is setted to ```dom``` and ```window.zoomLevel: 0``` does not solve. I haven't found any workaround to this so far.

**Comment by deepak1556** [comment]
@rodrigocaus can you confirm if this is still an issue with latest insiders https://code.visualstudio.com/insiders/ , thanks!

**Comment by rodrigocaus** [comment]
> @rodrigocaus can you confirm if this is still an issue with latest insiders https://code.visualstudio.com/insiders/ , thanks!

@deepak1556 I've installed insider's version 1.51.0 and both terminal and menu ghosting are still happening. I've tested on default _Dark+_ theme.

**Comment by deepak1556** [comment]
Can you also try https://github.com/microsoft/vscode/issues/106981#issuecomment-708606424 and add the results here.

**Comment by rodrigocaus** [comment]
> Can you also try [#106981 (comment)](https://github.com/microsoft/vscode/issues/106981#issuecomment-708606424) and add the results here.

 - With `code --disable-gpu` seems that the ghosting has stopped
 - With `code --disable-features=LayoutNG` the ghosting is still an issue
 - With exploration build 1.51.0 both terminal and menu ghosting are still happening

**Comment by deepak1556** [comment]
Thanks, considering the underlying issue is related to gpu I will merge to the other issue https://github.com/microsoft/vscode/issues/106981 to avoid duplicates. Please follow that issue for updates.
