### ISSUE TITLE
Bad UX when downgrading

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#107334]
If the last version of VSCode introduces an issue I'd like to have the ability to avoid using that version without having to micro manage my update settings
When downgrading versions the last update gets reinstalled instantly on launch, requiring the user to remember to change `update.mode` settings beforehand and remember to set it back to auto once another update is issued.

**Comment by joaomoreno** [comment]
Closing this as designed. We offer the ability to install old versions, but you must change the `update.mode` setting.
