### ISSUE TITLE
Ruby代码折叠功能异常

### ISSUE THREAD

**Issue by mymy3697166** [microsoft/vscode#107399]
在编写Ruby代码的时候，折叠起来的代码会因为删除代码而失效

**Comment by RandoNandoz** [comment]
I speak Chinese:

Title: Abnormal behavior when folding code in Ruby
Body: When writing Ruby code, folded code will be deleted.

**Comment by JW9506** [comment]
Translation: when you delete code in anywhere in a Ruby file, the folded code isn't respected and gets unfolded.

**Comment by kieferrm** [comment]
Thanks for the translation. We'd still need steps that would allow us to reproduce the problem. Also, are any ruby extensions at play here?
