### ISSUE TITLE
We hope to provide a unified way of feedback on plug-in problems or suggestions, so that user feedback can be convenient and direct feedback to plug-in developers

### ISSUE THREAD

**Issue by ldzqdrm** [microsoft/vscode#107300]
We hope to provide a unified way of feedback on plug-in problems or suggestions, so that user feedback can be easily and directly fed back to the plug-in developer, thus forming a virtuous circle, so that both users and plug-in developers can better

**Comment by kieferrm** [comment]
When you use `Help > Report Issue` you can specify whether your report is for an extension or VS Code itself.

![image](https://user-images.githubusercontent.com/4674940/94019543-c4e42900-fd66-11ea-93a4-a9998dea5ab0.png)

There is also the ability to provide reviews on the marketplace.

**Comment by kieferrm** [comment]
FYI @RMacfarlane
