### ISSUE TITLE
PowerShell on Mac OS X: error Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by DSotnikov** [Microsoft/vscode#10730]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Added PowerShell extension,
2. Created a simple file hello.ps1 with simple script: $i = 1,
3. Save the file,
4. Open folder containing the file,
5. Click Debug,
6. Accept default launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "PowerShell",
            "type": "PowerShell",
            "request": "launch",
            "program": "${file}",
            "args": [],
            "cwd": "${file}"
        }
    ]
}
```
7. Press F5.
8. Shows error "Debug adapter process has terminated unexpectedly"

**Comment by alexandrudima** [comment]
Moved to PowerShell/vscode-powershell#251
