### ISSUE TITLE
Feature Request: HAML Live Resolution after Enter

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#10733]
- VSCode Version: 1.4.0
- OS Version: Windows 10 64bit

Steps:
Type in ``.container#content`` in a HTML File and press Enter

Actual behaviour:
Nothing happens

Expected behaviour:
VSCode will replace this line(tab intended) with ```<div class="container" id="content">
[cursor here]
</div>```

That will be useful and I can type way more faster. It's more easier.

**Comment by mrmlnc** [comment]
This issue refers to Emmet. Unfortunately, now Emmet (in VS Code) doesn't support HAML syntax, however, that's a work in progress. See #9500.

**Comment by jens1o** [comment]
Thanks :smiley:
