### ISSUE TITLE
PowerShell on Mac OS X: Intellisense not working for cmdlets

### ISSUE THREAD

**Issue by DSotnikov** [Microsoft/vscode#10731]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Add PowerShell extension,
2. Open a PowerShell script, 
3. Type Get-P and press Ctrl-space - expected outcome is to see Get-Process - instead shows No Suggestions.

**Comment by alexandrudima** [comment]
Moved to PowerShell/vscode-powershell#250
