### ISSUE TITLE
Vscode panel bug

### ISSUE THREAD

**Issue by Blagoj5** [microsoft/vscode#107395]
- VSCode Version: 1.49.2
- OS Version: ubuntu 18.04

Steps to Reproduce:

1. When i open up vscode in the panel, PROBLEMS tab is missing
2. I tried uninstalling/purging vscode  (including it's config and extensions) nothing

![Screenshot from 2020-09-25 02-12-08](https://user-images.githubusercontent.com/50581470/94212671-16aac180-fed5-11ea-9091-10ccc5a85763.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by brendalf** [comment]
I wasn't able to reproduce this error.
What are the exactly steps you took when you say "When i open up vscode in the panel"?

**Comment by sandy081** [comment]
- Try the command `View: Reset View Locations` from the command pallette
- If does not work, try to start code on a different user data directory. You can do this from command line `code --user-data-dir <directory_path>`
