### ISSUE TITLE
Incorrect coloring of custom textarea elements (vscode-settings-textInputBackground) with Insiders 1.50.0

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#107332]
This is based on a user-reported issue with the C/C++ Extension: https://github.com/microsoft/vscode-cpptools/issues/6201

It looks like insiders 1.50 introduced an issue with custom html UI in our extension.  We are using the following to color textareas:

```
color: var(--vscode-settings-textInputForeground);
background: var(--vscode-settings-textInputBackground);
```

With 1.50.0, this results in a textarea background that matches the page background.

![image](https://user-images.githubusercontent.com/49173979/94091075-2ab6cc00-fdcc-11ea-8dcd-87c975ce23a8.png)

This is the expected behavior, and behavior prior to 1.50.0 :

![image](https://user-images.githubusercontent.com/49173979/94090985-ec211180-fdcb-11ea-99e9-6ae3cf70a261.png)

Version: 1.50.0-insider (user setup)
Commit: f943318042a3b9229049aea86cea04d0ff9c8210
Date: 2020-09-23T06:50:43.482Z
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by roblourens** [comment]
I was able to repro in yesterday's Insiders, but it works for me in today's, please verify. I was working with the settings editor theme colors but got it straightened out yesterday. Sorry!

![image](https://user-images.githubusercontent.com/323878/94153622-9c316180-fe42-11ea-9a6e-83d6a07a0710.png)


#106897
