### ISSUE TITLE
RBG/RGBA theme colors don't work for custom dialog boxes

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#107335]
![image](https://user-images.githubusercontent.com/641685/94094627-f6ec9e00-fded-11ea-99b2-1b6f0dbd5b0a.png)

On my theme that red text color should be `rgba(233, 217, 242, 0.82)`

Here is the cause -- we are assuming it is hex with the `fromHex` call.
https://github.com/microsoft/vscode/blob/e8572c022163b7db3e0424549bdb5ac32b7ebd4e/src/vs/base/browser/ui/dialog/dialog.ts#L302-L305

**Comment by mjbvz** [comment]
@eamodio Can you please add some steps to verify this? I tried:

```json
  "workbench.colorCustomizations": {
    "notifications.foreground": "rgba(233, 217, 242, 0.82)"
  }
```

But that doesn't seem to be recognized?

**Comment by eamodio** [comment]
You can verify using my theme https://marketplace.visualstudio.com/items?itemName=eamodio.amethyst-theme. The dialog text will not be red as shown above.
