### ISSUE TITLE
'Open Folder' button on the main window does not work

### ISSUE THREAD

**Issue by mjneuharth** [microsoft/vscode#107322]
Issue Type: <b>Bug</b>

1. Create a New Window
2. Attempt to 'Open Folder' and nothing happens.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|16, 8, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|-psn_0_2060791 --crash-reporter-id 12176607-765a-4528-98eb-263b6e006805|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (87)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
latex-preview|ajs|0.5.1
Bookmarks|ale|11.3.1
inf|bag|0.0.1
theme-verdandi|be5|2.0.1
figlet|can|0.0.1
vscode-opennewinstance|chr|0.0.7
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.36.3
ini-for-vscode|Dav|0.0.4
githistory|don|0.6.9
xml|Dot|2.5.1
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
vscode-great-icons|emm|2.1.56
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
git-project-manager|fel|1.7.1
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
gc-excelviewer|Gra|3.0.40
todo-tree|Gru|0.0.178
terraform|has|2.2.3
asciidecorator|hel|0.2.0
beautify|Hoo|1.5.0
reg|ion|1.0.1
kubernetes-snippets|ipe|0.1.9
mysql-syntax|jak|1.3.1
latex-workshop|Jam|8.13.2
autofilename|Jer|0.1.3
replace-curly-quotes|jin|1.1.0
vscode-kitchen|jir|0.5.0
banner-comments-plus|lun|0.3.1
rainbow-csv|mec|1.7.1
file-downloader|min|1.0.0
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|1.1.17
vscode-apache|mrm|1.2.0
azure-pipelines|ms-|1.174.2
vscode-azureappservice|ms-|0.19.0
vscode-azurefunctions|ms-|0.24.1
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
mssql|ms-|1.9.0
python|ms-|2020.9.111407
azure-account|ms-|0.9.3
azurecli|ms-|0.5.0
powershell|ms-|2020.6.0
vscode-open-iterm2|mus|0.0.4
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.3.0
polacode|pnp|0.3.4
quicktype|qui|12.0.46
java|red|0.67.0
vscode-yaml|red|0.11.0
vscode-statusbar-json-path|ric|1.4.4
kuskus-kusto-language-server|ros|1.0.1
sql-snippets|sad|0.0.4
jinjahtml|sam|0.15.0
elm|sbr|0.26.0
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.13
code-eol|soh|0.3.3
slack|soz|0.0.14
guides|spy|0.9.3
code-spell-checker|str|1.9.1
ayu|tea|0.20.1
latex-support|tor|3.2.0
shell-launcher|Tyr|0.4.1
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-icons|vsc|11.0.0
vscode-ansible|vsc|0.5.2
gitblame|wad|5.0.0
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
better-align|wwm|1.1.6
markdown-all-in-one|yzh|3.3.0
material-theme|zhu|3.8.7
html-css-class-completion|Zig|1.19.0

(4 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. I can not reproduce.
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
