### ISSUE TITLE
can't launch an Extension Development Host window with color theme development test

### ISSUE THREAD

**Issue by Mizobrook-kan** [microsoft/vscode#107396]
- VSCode Version: 1.49.1
- OS Version: windows 10

Steps to Reproduce:

1. following [this link](https://css-tricks.com/creating-a-vs-code-theme/) until theme test 

Does this issue occur when all extensions are disabled?: Yes/No

<------------------------- Detail --------------------------->
I issued a question on [stackoverflow](https://stackoverflow.com/questions/64046165/development-test-with-color-theme), but nobody answers under this question. Help me if someone can solve it.

**Comment by kieferrm** [comment]
@Mizobrook-kan what is the concrete issue you see when you press <kbd>F5</kbd>?  Any output in the `Debug Console`?
