### ISSUE TITLE
External applications are not opened as external windows in Ubuntu

### ISSUE THREAD

**Issue by aaad** [microsoft/vscode#107349]
Whenever VSCode opens another external application (browser, ...) in Ubuntu the application is running within vscode. This leads to bad tab handling and therefore to an unfamiliar workflow.

- VSCode Version: 1.49.1
- OS Version: Linux 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Open vscode in Ubuntu
2. Open a terminal in vscode
3. type: https://www.google.de and hit enter
4. Klick on the url while pressing ctrl -> firefox is opened
5. Press alt-tab
6. The opened firefox window is related to vscode

Same applies to "right click on a folder" in the explorer -> Open containing folder

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by NDOY3M4N** [comment]
I don't think this bug is related to 'vscode' but rather with 'ubuntu' because I have the same issue when using 'Sublime Text'. In 'sublime-text' when I'm using the 'live-server' package it launch Firefox as a Sublime Text window.

**Comment by deepak1556** [comment]
@aaad does the issue happen with latest stable ?

**Comment by aaad** [comment]
I can reproduce it with:

VSCode Version: 1.51.1
OS Version: Linux 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux (=Ubuntu 20.04.1 LTS)
