### ISSUE TITLE
Theme selector should not appear when installing an extension that contains a main

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#107320]
Repro:

1. Install C# extension

You will see this because it contributes themes:

![image](https://user-images.githubusercontent.com/2193314/94057468-81081880-fd94-11ea-9e9b-9ea09436779d.png)

I think this is confusing from a user's perspective as the main purpose of the C# extension is not themes. An easy way to separate this category of extensions seems to be whether the extension contains a `main`?

**Comment by sandy081** [comment]
If I remember, this was discussed before and the suggestion for the extension was to decouple them into separate extensions. Problem is that some theme extensions can contain `main` and not sure if there is a reliable way to segregate them.

**Comment by Tyriar** [comment]
Why not do it the other way and theme extensions that happen to have a main miss out on this feature? I think the reason C# contributes these themes is because they work specially with the grammar that the extension uses, so it doesn't make sense to use these themes unless you have the C# extension installed. I see PowerShell also still bundle the theme in the main extension.

**Comment by sandy081** [comment]
Not sure who gets the benefit or who does not. Some popular theme extensions has main code and not showing the theme picker might be more lose rather showing a picker for other extensions. One workaround would be that C# and Powershell can separate theme extensions and add them as a dependency.

@aeschli Since you have more insights about theme extensions, what do you recommend?

**Comment by aeschli** [comment]
I suggest that we tune the heuristic and check whether the extension makes language contributions:
Look for `"activationEvents"` that start with `onLanguage`.
Alternatively we add a new property to the theme contribution `proposeOnInstall: false` (true being the default)

**Comment by sandy081** [comment]
Checking for language contributions seems to be a smarter 👍
