### ISSUE TITLE
How to install extensions inside a WinRM/RS session?

### ISSUE THREAD

**Issue by rgl** [Microsoft/vscode#10736]
- VSCode Version: 1.4.0
- OS Version: Windows 2012 R2

I want to automate the installation of vscode inside a vagrant managed environment. Vagrant uses WinRM to execute commands inside the Windows VM. For some reason I cannot install extensions like I can do when running the same command at a normal Command Prompt.

Steps to Reproduce:
1. Install a Windows vagrant environment (you could use https://github.com/rgl/choco-0.9.10.3-not-working-with-vagrant/blob/master/Vagrantfile) or just setup WinRM on your machine.
2. try to install an extension with `winrs -r:localhost -u:vagrant -p:vagrant code --install-extension ms-vscode.PowerShell`.
3. and list the installed `winrs -r:localhost -u:vagrant -p:vagrant code --list-extensions`
4. realize that nothing was installed. in fact, `code` does not even produce any output.

Any idea on how to get this working?

**Comment by joaomoreno** [comment]
```
👎  [1] choco-0.9.10.3-not-working-with-vagrant master → vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'windows_10' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'windows_10' (v0) for provider: virtualbox
    default: Downloading: windows_10
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/joao/Desktop/choco-0.9.10.3-not-working-with-vagrant/windows_10
```

Can you give me more specific steps on how to use Vagrant?

**Comment by rgl** [comment]
The instructions are in a comment inside the linked Vagrantfile. You can also try it on your machine if you [setup WinRM](https://github.com/joefitzgerald/packer-windows/blob/master/answer_files/10/Autounattend.xml#L146) (you need to execute all commands that have WinRM in their name).

**Comment by joaomoreno** [comment]
OK maybe you can help out in debugging this. Do you get any output with `code --verbose`?

**Comment by rgl** [comment]
I don't get any output.

Oh, I completely forgot about this... but maybe this is related to a known [Electron issue](https://github.com/electron/electron/issues/683). Even doing the workaround (e.g. getting update.com from the squirrel for windows repository) it still does not work over WinRM.

**Comment by joaomoreno** [comment]
Closing as this doesn't seem to be a problem with Code itself but with the environment.
