### ISSUE TITLE
Keywords in statements following indexing of 2D matrix using variable across multiple lines are NOT highlighted

### ISSUE THREAD

**Issue by wsrfad** [microsoft/vscode#107346]
- VSCode Version: 1.49.0
- OS Version: Linux x64 3.13.0-71-generic

Steps to Reproduce:

1. Write the following code with vscode 
```
bool function1() {
    int mat[100][100];
    int x = 50;
    auto price = mat[x]
        [x];

    // Keywords in following statements are not highlighted
    auto tmp = 2;
    auto a = tmp;
    return true;

}

bool function2() {
    int mat[100];
    int x = 50;
    auto price = mat
        [x];        // Keyword in statements following are not highlighted
    auto tmp = 2;
    return true;
}
```

Does this issue occur when all extensions are disabled?: Keywords like auto / return are still not highlighted, while variable names are

**Comment by alexr00** [comment]
@wsrfad  what language are you using?

**Comment by wsrfad** [comment]
C++

**Comment by alexr00** [comment]
Since this issue comes from the C++ grammar I've moved the issue to that repo: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/507
