### ISSUE TITLE
I hope that Visual Studio IntelliCode can provide similar code hints for Java in idea

### ISSUE THREAD

**Issue by ldzqdrm** [microsoft/vscode#107303]
In the issue of this plugin GitHub, I posted feedback, but there was no response for a long time. Since you are all from Microsoft, I try to put this suggestion here. Please pay attention

I hope that Visual Studio IntelliCode can provide similar code prompting functions for Java in the idea, especially xx.for, xx.if, xx.null, xx.var、xx.switch and other functions, that is, the design for the trigger content of the variable suffix "." , This is very in line with user habits and very user-friendly. Please refer to, improve the performance of intelliCode, make it smarter and smarter, he also needs to learn from idea in the Java field

**Comment by kieferrm** [comment]
FYI @egamma

**Comment by kieferrm** [comment]
\extJava
