### ISSUE TITLE
Dropdown font seems to be smaller than before

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#107393]
![image](https://user-images.githubusercontent.com/641685/94209816-37562580-fe9b-11ea-84a4-a7495b02e58b.png)

**Comment by jeanp413** [comment]
related https://github.com/microsoft/vscode/issues/103185 and https://github.com/microsoft/vscode/pull/107266

**Comment by bpasero** [comment]
@eamodio we basically changed it back to how it was before updating Electron 9, you think there is an issue with that?

**Comment by eamodio** [comment]
I see a big difference between stable and insiders
![image](https://user-images.githubusercontent.com/641685/94371655-1291c600-00c6-11eb-993f-d29246d059d2.png)

The dropdown font is much smaller than before and much smaller than any of the other input fonts. The other input fonts are 13px, but the dropdown is 11px.

**Comment by bpasero** [comment]
@eamodio yes intentional, did you see https://github.com/microsoft/vscode/issues/107393#issuecomment-698718373 ?

**Comment by eamodio** [comment]
@bpasero Hrm, I see. I personally don't like that smaller font at all, as it seems really out of place since it doesn't match any other fonts. Also, at least on Windows, the dropdown text seems to low as well.

**Comment by bpasero** [comment]
@eamodio can you possibly compare with a previous version before Electron 9, e.g. `1.48` to see how it used to be for you?

**Comment by misolori** [comment]
After downloading previous versions, I'm wondering if it's always been 13px on Windows. Here's from our January release:

![image](https://user-images.githubusercontent.com/35271042/94448086-5f75ab00-015f-11eb-9d10-30e0768c163b.png)

I can change the css rule to only apply to Mac.

**Comment by bpasero** [comment]
@misolori thanks, ideally we can match whatever we had before on all platforms 👍

**Comment by misolori** [comment]
Double checked on Linux and it's also 13px, so will make the change to only apply to Mac.
