### ISSUE TITLE
Shortcut translation error

### ISSUE THREAD

**Issue by akaron79** [microsoft/vscode#107383]
Issue Type: <b>Bug</b>

Toggle line comment in a spanish keyboard layout on Mac should be shown as cmd+/ instead of cmd+& in the Edit menu (Editar->Alternar comentario de línea, in spanish).

I cannot believe I am the first person reporting this :S.

Thanks and regards.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|16.00GB (4.06GB free)|
|Process Argv|-psn_0_671908 --crash-reporter-id 8158e0da-6754-4d4b-b265-910e236fb4f7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
prettier-vscode|esb|5.7.1
vscode-placeholder-images|Jak|0.1.0
pretty-formatter|mbl|0.2.2
vscode-language-pack-es|MS-|1.49.1
java|red|0.67.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2

</details>

**Comment by alexdima** [comment]
Can you please open an editor and execute `F1 > Developer: Inspect Key Mappings` ?

**Comment by akaron79** [comment]
It is ok in the Keyboard shortcuts for macOS help page. The problem is within the Edit menu itself, running vscode.

You can check in this picture:

![EA9BA49D-A2B7-41F0-99B7-F1C4F3852B44](https://user-images.githubusercontent.com/26524080/94268104-f4e52500-ff3c-11ea-840c-c74f82708190.jpeg)

**Comment by alexdima** [comment]
Thanks Vicente, can you please open an editor and execute `F1 > Developer: Inspect Key Mappings` ? You can then save the output to a file and attach it here.

**Comment by akaron79** [comment]
Sure. I hope it helps:

[Layout_info.txt](https://github.com/microsoft/vscode/files/5284831/Layout_info.txt)


Thanks and regards
Vicente

**Comment by alexdima** [comment]
This appears to be a regression in Electron 4.0. I have created https://github.com/electron/electron/issues/26907 against Electron.

cc @bpasero @deepak1556

**Comment by deepak1556** [comment]
Closing as upstream fix has landed in our insiders.
