### ISSUE TITLE
Folder being replicated when Retrieve source from org

### ISSUE THREAD

**Issue by georgehmullins** [microsoft/vscode#107381]
When I right click on folder to retrieve source from org, the retrieved folder is being put into a subfolder of the one being refreshed.  Basically duplicating the file within the file.  I have the salesforce plugin installed and the problem just started today.  It was working fine for months.  Yesterday late I allowed the software to install an update.
I am on version 1.49.1
Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
/causedByExtension please report this to the extension author
