### ISSUE TITLE
typescriptServiceClient using up cpu on mac

### ISSUE THREAD

**Issue by vegetableman** [Microsoft/vscode#10735]
- VSCode Version:1.4.0
- OS Version: 10.11.1 (OS X El Capitan)

Steps to Reproduce:
1. Open up the editor (all third-party extensions are disabled).
2. And simply open files and navigate.

![screen shot 2016-08-20 at 2 02 07 pm](https://cloud.githubusercontent.com/assets/1330851/17830092/24020326-66df-11e6-81ce-f7cee9b9a349.png)

Closing the higher cpu using `Code Helper` process gives the following log:-

```
[Extension Host] Error: Service died.
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:236:46
    at Array.forEach (native)
    at TypeScriptServiceClient.serviceExited (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:235:37)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/typescriptServiceClient.js:176:31)
    at emitTwo (events.js:105:20)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

Haven't had the chance to debug the issue in depth. But `typescriptServiceClient` seems to be responsible for the cause. 

Hope this helps. Love VSCode.

**Comment by waderyan** [comment]
ping @dbaeumer

who would be best to talk to on the team about this?

**Comment by dbaeumer** [comment]
@waderyan I am pretty sure this is the tsserver and not the extension host which contains the typescriptServiceClient.

@vegetableman if you can reproduce this can you provide use with the command line of the `Code Helper` that is causing high CPU. That helps understand what the process is actual for.

**Comment by dbaeumer** [comment]
Some more comments: closing the extension host hard closes the tsserver. This is why you see Error: Service died. So the whole CPU eating has IMO nothing to do with the `typescriptServiceClient`. It is only a consequence of killing these progresses. 

As long as the tsserver has no high CPU usage or we can profile the extension host it is unclear if this is really TS related.

**Comment by waderyan** [comment]
@vegetableman this has fallen through the cracks. Are you still seeing this issue with the latest VS Code? Can you share your workspace if you are?

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this

@vegetableman Please let us know if you are still seeing this in VSCode 1.8.1 with TS 2.1.4+

Thanks.
