### ISSUE TITLE
Cannot use monaco editor on safari since 2.0.0

### ISSUE THREAD

**Issue by ljewalsh** [microsoft/vscode#107368]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open vscode-web in safari https://vscode-web-test-playground.azurewebsites.net/?enter=true
2. Page will not load

Does this issue occur when all extensions are disabled?: Yes/No

N/A only affects web

**Comment by mjbvz** [comment]
Works fine for me.

![Screen Shot 2020-09-24 at 9 59 39 AM](https://user-images.githubusercontent.com/12821956/94176302-bbcd8780-fe4c-11ea-9754-1b56b281b901.png)


Which safari version is this? Do you have any content blockers installed?

**Comment by ljewalsh** [comment]
https://whatismybrowser.com/w/MTYD9P5

We are using monaco-editor on our site and we get this error:

![image](https://user-images.githubusercontent.com/6325359/94176652-b138df80-fe98-11ea-81e2-3e153129ef1e.png)

Seems to be caused by a lookbehind in the regex. Reverting to 1.9.1 fixed this for us
