### ISSUE TITLE
Scrolling is extremely fast on Elan touchpad

### ISSUE THREAD

**Issue by 0x21106** [microsoft/vscode#107380]
- VSCode Version: 1.50.0-insider (user setup)
- OS Version: Windows 10 Pro version 2004 build 19041.508

When scrolling the code window with touchpad little bit, the thousands of line code scrolling to the end bottom or top one time

1. My laptop - Lenovo Idepad S145-15IWL i3-8145U version
2. Touchpad - Elan pointing device Driver version - 22.4.16.1 driver date: 5/23/2019

[https://im3.ezgif.com/tmp/ezgif-3-0ed3cbf26264.gif](url)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kieferrm** [comment]
@0x21106  you can use the `editor.mouseWheelScrollSensitivity` setting to slow scrolling down. For example, try `0.1`.

![image](https://user-images.githubusercontent.com/4674940/94325203-24525c80-ff52-11ea-8b75-36c2ae3e8d37.png)

**Comment by 0x21106** [comment]
> @0x21106 you can use the `editor.mouseWheelScrollSensitivity` setting to slow scrolling down. For example, try `0.1`.
> 
> ![image](https://user-images.githubusercontent.com/4674940/94325203-24525c80-ff52-11ea-8b75-36c2ae3e8d37.png)

Thanks brother :) my problem soved 👍  <3
