### ISSUE TITLE
My Terminal Console not working in Visual Studio Cord

### ISSUE THREAD

**Issue by samuelsaji** [microsoft/vscode#107371]
We have written the needed da
Issue Type: <b>Performance Issue</b>

 When I open my terminal console it is dissapearing with a pop up message as shown below
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 4294901760.

Kindly please answer to my problem

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    76	 12380	code main
    3	   185	  9272	   gpu-process
    1	    64	  9404	   window (Issue Reporter)
    0	    14	  9944	   electron-crash-reporter
    0	   169	 11784	   window (express_sample.js - web development - Visual Studio Code)
    0	    11	  5752	     watcherService 
    0	    11	 14112	       console-window-host (Windows internal process)
    0	    67	  9508	     extensionHost
    0	   140	  2492	       electron_node tsserver.js 
    0	    50	 11860	         electron_node typingsInstaller.js typesMap.js 
    0	     4	   504	           C:\WINDOWS\system32\cmd.exe /d /s /c "npm install --ignore-scripts types-registry@latest"
    0	     4	  5684	             C:\WINDOWS\system32\cmd.exe /c CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g
    2	    27	 10384	               "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g
    0	    11	  5892	             console-window-host (Windows internal process)
    0	    51	  8708	       electron_node tsserver.js 
    0	    34	 13840	     searchService
    0	    23	 13040	   utility
    0	    72	 13164	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (express_sample.js - web development - Visual Studio Code)
|    Folder (web development): 26 files
|      File types: js(16) html(4) json(2) css(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
save-typing|akh|0.1.0
LiveServer|rit|5.6.1

</details>
ta into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
Please follow https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch and create a new issue if you're still having problems.
