### ISSUE TITLE
The redo `CreateOperation` is not equal to the initial `CreateOperation`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#107379]
This took me a lot of time to understand and track down.

1. enable autosave (only reproduces with autosave on!)
2. do the following change in `bulkFileEdits.ts`:
![image](https://user-images.githubusercontent.com/5047891/94196944-5a8dce80-feb5-11ea-86d4-19c7d2f204f0.png)
3. have a ts file with the contents:
```ts
const myInterestingAndVeryLongedNameFunction = () => {

}

function myUtility() {
    return 5;
}
```
4. select the function entirely
5. do the quick fix "Move to a new file"
6. undo
7. redo
Observe that an exception is thrown. The exception is very hairy to understand, but the root cause is that a text buffer is created for `myUtility.ts`, but its content hash does not equal the content hash when the text buffer was disposed, so the undo-redo element is not rehydrated, so that's why there's an error. The root cause is that in the "redo" case the `CreateOperation` is not creating an empty file, but a file with contents. I can only speculate that this has to do with autosave. I suggest that the `DeleteOperation` has an optional reference to a `CreateOperation` and that it can return the exact same `CreateOperation` instance for the "redo" as the "do"...

![Kapture 2020-09-24 at 22 34 11](https://user-images.githubusercontent.com/5047891/94197501-2d8deb80-feb6-11ea-9718-4aaa527cb3db.gif)

**Comment by jrieken** [comment]
> The root cause is that in the "redo" case the CreateOperation is not creating an empty file, but a file with contents. I can only speculate that this has to do with autosave. I suggest that the DeleteOperation has an optional reference to a CreateOperation and

Makes sense. The `DeleteOperation` creates an undo operation which always restores the file contents. That IMO makes sense given that a delete could occur for any file. However, a delete which undoes a create shouldn't not do this.
