### ISSUE TITLE
"Push to" in source control now in a sub menu - annoying

### ISSUE THREAD

**Issue by MashaMSFT** [microsoft/vscode#107333]
Issue Type: <b>Bug</b>

In the new iteration of VS Code, the "..." menu in source contral has changed such that I now have to access a submenu to choose "Push to..". So now to achieve the same action, I have to click twice instead of once. It's not that big of a deal I suppose, but it is more annoying, and less conveneint. 

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (16.28GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.35.1
docs-article-templates|doc|0.2.9
docs-authoring-pack|doc|0.1.8
docs-images|doc|0.0.8
docs-linting|doc|0.0.3
docs-markdown|doc|0.2.71
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.49
docs-yaml|doc|0.2.5
powershell|ms-|2020.4.0
vscode-yaml|red|0.8.0
code-spell-checker|str|1.9.0

</details>

![image](https://user-images.githubusercontent.com/32783170/94094140-9b151b80-fdd3-11ea-977a-0709746c0739.png)

**Comment by joaomoreno** [comment]
> In the new iteration of VS Code, the "..." menu in source contral has changed such that I now have to access a submenu to choose "Push to..". So now to achieve the same action, I have to click twice instead of once. It's not that big of a deal I suppose, but it is more annoying, and less conveneint.

You can also reach that action via the F1 command palette and by assigning a custom keybinding.

Closing this as designed.

**Comment by MashaMSFT** [comment]
sure, i could work around this issue, but it doesn't change the fact that this change is annoying, making ppl do extra things to accomplish the same task is annoying, whenever i push to origin now, i sigh in annoyance. no, it's not a big deal, yes there is a workaround, but i think it should at least be noted that it's having this impact to ppl, and if a lot of ppl say the same thing, at least there'll be a record if it :)
