### ISSUE TITLE
js-debug cannot be used

### ISSUE THREAD

**Issue by 1758231591** [microsoft/vscode#107367]
Issue Type: <b>Bug</b>

"C:\Program Files\nodejs\node.exe" ".\Compiler tools\out\hello.js"
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'c:/Users/��ɭ��/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1277:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
Process exited with code 1

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.52GB free)|
|Process Argv|--crash-reporter-id bff26b53-40a0-44a6-b57f-1cc2f1bfb6a4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-javascript-snippet-pack|aka|0.1.6
project-manager|ale|11.3.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-svgviewer|css|2.0.0
vscode-mysql-client2|cwe|2.5.8
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.6.0
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.0
vscode-pull-request-github|Git|0.20.0
todo-tree|Gru|0.0.178
vscode-test-explorer|hbe|2.19.1
vscode-drawio|hed|0.7.2
canvas-snippets|hol|0.3.2
rest-client|hum|0.24.2
output-colorizer|IBM|0.1.2
search-node-modules|jas|1.3.0
webpack|jer|2.2.0
vscode-codemetrics|kis|1.24.0
vscode-gutter-preview|kis|0.26.2
node-module-intellisense|lei|1.5.0
vscode-language-babel|mgm|0.0.29
vscode-exec-node|mir|0.5.3
vscode-filesize|mkx|2.1.4
vscode-scss|mrm|0.9.0
vscode-azureappservice|ms-|0.19.0
vscode-docker|ms-|1.6.0
vscode-language-pack-zh-hans|MS-|1.49.2
mssql|ms-|1.9.0
azure-account|ms-|0.9.3
cpptools|ms-|1.0.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
indent-rainbow|ode|7.4.0
open-html-in-browser|pea|2.1.3
vscode-versionlens|pfl|1.0.8
tslint-vue|pro|1.5.6
quicktype|qui|12.0.46
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-javascript-booster|sbu|14.0.1
code-settings-sync|Sha|3.4.3
easysass|spo|0.0.6
code-spell-checker|str|1.9.1
move-ts|str|1.12.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
WebTemplateStudio-dev-nightly|WAS|0.4.2020202
vscode-import-cost|wix|2.12.0
better-align|wwm|1.1.6
html-css-class-completion|Zig|1.19.0

</details>

**Comment by connor4312** [comment]
This is fixed in the latest version of Node.js. There is also a workaround available, see https://github.com/microsoft/vscode-js-debug/issues/563#issuecomment-659592018

/duplicate
