### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by ChenAlmost** [microsoft/vscode#107331]
Issue Type: <b>Bug</b>

every time i open react app, this bug show up. even in insider version

VS Code version: Code - Insiders 1.50.0-insider (8c1015f5e1a7a686d19ec8a5f56a495332f16062, 2020-09-21T07:56:21.563Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 7, 5|
|Memory (System)|8.00GB (0.32GB free)|
|Process Argv|--crash-reporter-id 34fd20ab-6af7-4466-b842-51fdde942f33|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Please share steps plus example code that can reproduce this issue

/needsMoreInfo

**Comment by ChenAlmost** [comment]
![image](https://user-images.githubusercontent.com/31819795/94110438-38745c00-fe75-11ea-99b2-325054be0f5d.png)
it is a normal create-react-app. when I open the project and choose a .jsx file, the bug will show up :(

**Comment by ChenAlmost** [comment]
![image](https://user-images.githubusercontent.com/31819795/94110799-bfc1cf80-fe75-11ea-8151-7dbb7753f040.png)
this is the console log.

**Comment by mjbvz** [comment]
Have you configured VS Code to use a workspace version of TypeScript? You can check this by opening a javascript or typescript file and running `Select TypeScript` version in the command palette

**Comment by ChenAlmost** [comment]
> Have you configured VS Code to use a workspace version of TypeScript? You can check this by opening a javascript or typescript file and running `Select TypeScript` version in the command palette

wow, thx for reply. I solved the problem following your instruction! But I have a simple project does not have workspace typescript. I try to configure the tsdk(ts version is 3.8.2), and problem gone :) I guess the problem is caused by typescript version?
![image](https://user-images.githubusercontent.com/31819795/94219353-37950600-ff19-11ea-9710-23b101284af9.png)
![image](https://user-images.githubusercontent.com/31819795/94219327-25b36300-ff19-11ea-9662-c4876b5481fa.png)

**Comment by mjbvz** [comment]
What version of TypeScript was causing the issue?

**Comment by ChenAlmost** [comment]
> What version of TypeScript was causing the issue?

the default  typescript version(4.0.2 I remember but not for sure, sorry) of vscode 1.49.2
