### ISSUE TITLE
Repo Names should take precidence over branch names in SCM

### ISSUE THREAD

**Issue by kkolk** [microsoft/vscode#107302]
Currently in VSCode when working with relatively long branch names the branch name will take precedence over the reponame/folder name.

If you have multiple repos open this can make it very hard to see which repo you are selecting when working in the SCM.   For me this means that while I can comfortably have the sidebar at one width when working in the file explorer, in SCM manager I need a vastly wider view in order to have a working interface.

For example:
![Screen Shot 2020-09-23 at 9 49 33 AM](https://user-images.githubusercontent.com/6248447/94021575-29f94800-fd82-11ea-9fbb-c3f725bcc25c.png)

Could we get an option that allows the repo name/folder appear above the branch name instead of sliding behind it?

**Comment by joaomoreno** [comment]
We keep going back and forward on this. For every issue which argues the repository name should take precedence, there's another one arguing the opposite. In today's Insiders there's already a minimum width to the repository name, which definitely alleviates the problem. Please give that a try.
