### ISSUE TITLE
Block comments unfold when typing outside the region

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#107342]
- VSCode Version: 1.49.1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Type one or more block comments in a .js file
2. Fold any or all comments
3. Type anything outside the blocks and they will all unfold.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
I can't reproduce. Can you add a small code sample with steps? What do you type?
