### ISSUE TITLE
Rebinded backspace doesn't work

### ISSUE THREAD

**Issue by Kaltxi** [microsoft/vscode#107352]
- VSCode Version: 1.49.1
- OS Version: Arch Linux

Steps to Reproduce:

1. Using Xmodmap rebind backspace to right shift
2. Inside the editor right shift is not recognized as backspace, but rather as a shift (the only app that does so)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
Duplicate of #23991
