### ISSUE TITLE
Debug error with pwa-node: JavaScript displayed instead of TypeScript

### ISSUE THREAD

**Issue by TimMensch** [microsoft/vscode#107327]
Issue Type: <b>Bug</b>

With the config below, which was based on the config for Mocha Tests in Code 1.49.1, the source level debugging failed to work properly.

The problem is that, when it hits a breakpoint, it shows the compiled JavaScript instead of the original source file. This despite the fact that it _knows_ the exact path of the original source file; instead it shows a file that doesn't exist in the file system with an identical name and path to the one that I placed a breakpoint in. See the video for the demonstration.

Changing the configuration to `"type": "node"` fixes the problem, so there is a workaround. But I understand the pwa debugger is intended to replace the current debugger, so therefore this needs to be fixed, yes?

Mocha version 5.2.0
TypeScript version 2.5.3

`launch.json`
```cjson
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "args": [
        "-u", "bdd", "--watch", "--watchExtensions", "ts", "--timeout", "999999", "--colors",
        "${workspaceFolder}/packages/package/test/**/*.test.ts"
      ],
      "internalConsoleOptions": "openOnSessionStart",
      "name": "Mocha Tests",
      "env": {
        "NODE_ENV": "test"
      },
      "cwd": "${workspaceFolder}/packages/package",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "request": "launch",
      "skipFiles": ["<node_internals>/**"],
      "type": "pwa-node",
      "sourceMaps": true
    }
  ]
}
```

`tsconfig.json`
```cjson
{
  "compilerOptions": {
    "noEmit": true,
    "target": "es2017",
    "module": "commonjs",
    "lib": ["es2017", "dom"],
    "allowJs": false,
    "checkJs": false,
    "declaration": false,
    "sourceMap": false,
    "removeComments": false,
    "strict": true,
    "noStrictGenericChecks": true,
    "noImplicitReturns": true,
    "suppressImplicitAnyIndexErrors": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "types": ["node", "reflect-metadata", "mocha", "chai", "chai-subset", "chai-xml"],
    "inlineSourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true 
  },
  "exclude": [
    "node_modules",
    "public"
  ]
}
```

`packages/package/test/mocha.opts`
```
--require ../../node_modules/ts-node/register
--require ../common/test/setup.ts
--timeout 5000
--recursive
--exit
./**/*.test.ts
```

Video of repro: https://drive.google.com/file/d/1XsIAPl2QE0zv-h8Ytgphu4o0uBoaxK0Z/view?usp=sharing

VS Code version: Code - Insiders 1.50.0-insider (f943318042a3b9229049aea86cea04d0ff9c8210, 2020-09-23T06:50:43.482Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800XT 8-Core Processor             (16 x 3893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (2.78GB free)|
|Process Argv|--crash-reporter-id 1ea1d622-9637-463a-91c3-3a0788249eae|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.44.5

</details>

**Comment by connor4312** [comment]
In your tsconfig, you have

```
    "sourceMap": false,
```

We require sourcemaps enable to map the compiled locations back to their source locations. Please try adjusting that and let us know if the issue persists.

**Comment by TimMensch** [comment]
I tried that before I submitted the bug. It had no effect. Only changing to "type:node" fixed the issue. 

Note that it does work perfectly with "type: node". So therefore source maps must exist. The fact that it knew the source file name at all also implies source maps exist. You can even _see the source map in the video_, so there's that. 

I suspect the inline source maps option overrides the sourceMaps:no option.

**Comment by connor4312** [comment]
Ah, I see. Can you try adding a setting `resolveSourceMapLocations: null`?

**Comment by TimMensch** [comment]
Ahh, yes! That does fix it.

Should we _know_ that option exists? I found that option and tried to add a couple of different variety of paths to it, but it didn't occur to me to set  it to _null_.

**Comment by connor4312** [comment]
`null` disables the filter and lets sourcemaps be resolved everywhere.

In 1.49, `resolveSourceMapLocations` defaults to the `outFiles`, but outfiles in turn will try to default to the closest package.json up to the workspace root (to work more precisely in monorepos and avoid extra scanning for very large repos, refs https://github.com/microsoft/vscode-js-debug/issues/326).

So I think setting outFiles to something like

```
outFiles: ["packages/*/dist/**/*.js"]
```

is probably want you want to do if you want to be able to debug other packages in your monorepo.

Perhaps the optimization we made around guessing outfiles in this scenario is not a good approach. Small monorepos will be able to scan the whole workspace fine -- it's pretty fast, much faster now than it was when the linked issue was originally filed. And people using large monorepos where it is slow will probably be advanced enough to be able to figure out what they need to do -- or ask us.

**Comment by connor4312** [comment]
Looking through issues, this issue has been the only one about this. Therefore I think I'll leave the existing behavior; for your scenario I recommend configuring your outfile. You can also it to its (simple) default `['${workspaceFolder}/**/*.js', '!**/node_modules/**']` to include the whole workspace.

I also do want to get around to https://github.com/microsoft/vscode-js-debug/issues/260 next month which should help out in this scenario as well.
