### ISSUE TITLE
Commit Message in the "Source Control" message input box should retain after closing the VSCode

### ISSUE THREAD

**Issue by Soberia** [microsoft/vscode#107307]
Commit Message in the "Source Control" message input box should retain after closing the VSCode.
By this way, we can add changelog when developing in process

![image](https://user-images.githubusercontent.com/30440494/94028691-ec6bdd80-fdc8-11ea-8509-4ae53ef186e4.png)

**Comment by mjbvz** [comment]
Duplicate of #41232
