### ISSUE TITLE
Always conflicts for settings sync in Codespaces

### ISSUE THREAD

**Issue by heaths** [microsoft/vscode#107363]
Every time I open my repo in GitHub Codespaces, I'm told there are settings conflicts. When I viewed the diff, I see a couple of settings that were relocated but otherwise the same, except that one of them - an array - has been squashed into a single line. If I were to save the file in this state, desktop Code would eventually reformat that array and cause a conflict once again.

It would be great if you'd considered semantic diff or, if relying on existing diff tools, at least made sure that the settings JSON is formatted properly so I can accept the local changes (i.e. Codespaces, which may be confusing to some since it is remote to them) and not worry about desktop changes reformatting and causing a subsequent problem.

**Comment by sandy081** [comment]
It would be very helpful if you can provide the precise steps to reproduce the issue so that we can do better analysis of the problem and the solution

**Comment by heaths** [comment]
1. Open https://github.com/heaths/heaths.github.io in Codespaces
2. Wait a short bit while the container image is created, and VSCode renders
3. Observe a warning about settings being out of sync
4. Viewing the diff, observe that one setting was moved to the top, while another was "deformatted", i.e. the array is not formatted across multiple lines like it once was, though it is in the same spot. Every other JSON property is formatted correctly.

**Comment by sandy081** [comment]
I think this is happening because of the issue that Codepsace is using different settings sync service end point for initialisation and a different one for syncing. Hence you (and I am also) are seeing the conflict. We recently fixed this to make sure same end point is used always. You will get this when Codespaces are deployed with new builds.
