### ISSUE TITLE
Crashes when save File Snap Store version

### ISSUE THREAD

**Issue by nahbicris** [microsoft/vscode#107387]
- VSCode Version: 1.49
- OS Version: Manjaro Linux

Steps to Reproduce:

1.Install Visual Studio using Snap Store
2. Try to open or save a file
3. Crash

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by buzzra** [comment]
Confirm crash when using 'Save As' also.
Using Snap version 1.49 on Manjaro KDE

**Comment by kieferrm** [comment]
\duplicate #100940
