### ISSUE TITLE
high CPU load mount.ntfs process

### ISSUE THREAD

**Issue by j5ko** [microsoft/vscode#107350]
Ubunutu 20.04
VS code 1.49.1 (i also can reproduce with older versions)
when angular projects are located on a NTFS partition, VS code causes high CPU load after npm start is executed.
On a ext4 partition, there is no problem like this.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 5.4.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 3399)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.20GB (17.65GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 2e293dfd-961d-469d-99f4-9f03cb5956e1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.4
ng-template|Ang|0.1001.0
debugger-for-chrome|msj|4.12.11

</details>

**Comment by RandoNandoz** [comment]
NPM is I/O intensive.

NTFS on Linux uses the FUSE (file system in user space) driver, which is very CPU inefficient, and makes I/O slow. Does this occur with NPM on NTFS with the command line?

**Comment by j5ko** [comment]
i see, now i tried to compare the CPU load first starting npm start in terminal without vs code, than with vs code (to see if vs code is somehow responsible). Before it was no problem to reproduce, but now in both cases there was no big load. I'll check it later again!

**Comment by RandoNandoz** [comment]
Rule of thumb with working with stuff on Linux - use the Linux native file systems like ext4 or btrfs, instead of NTFS, or something non native. It will save you from a lot of headaches.

**Comment by rzhao271** [comment]
@j5ko any new results?

**Comment by j5ko** [comment]
Hi, could't reproduce it for a while but i moved code to ext4 partition now
