### ISSUE TITLE
Orca not detected at first launch

### ISSUE THREAD

**Issue by DataTriny** [microsoft/vscode#107317]
Issue Type: <b>Bug</b>

On Ubuntu 20.04, with Orca 3.36.2:
- Have Orca enabled,
- Install VS Code (official version from Microsoft),
- In a terminal, launch it with the `code` command.

Orca does not speak anything and the notification suggesting to enable screen reader optimized mode does not show.
I have been able to manually activate it on the settings because I can use my monitor/mouse, but otherwise it would have been impossible.

I can also say that the automated report below falsly detect that I am running Unity desktop, whereas I am effectively using GNOME.

Kind regards,
Arnold

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 5.4.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor (6 x 3058)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (10.82GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 9e2f3700-a03b-402d-9b1b-6ac9150836be|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by isidorn** [comment]
Please set the following setting:
`"editor.accessibilitySupport": "on"`
We have also documented it here https://code.visualstudio.com/docs/editor/accessibility#_linux

This is a known Chrome limitation which we have tracked in other open issues. 
Thus closing this as duplicate
