### ISSUE TITLE
Is there any way to have c# style guides suggesting proper styles? Newbie in c#. Will be very helpful!

### ISSUE THREAD

**Issue by idchlife** [Microsoft/vscode#10737]

**Comment by alexandrudima** [comment]
@idchlife Sorry, I don't understand the request. Can you please explain it more, perhaps with examples of what should happen?

**Comment by idchlife** [comment]
@alexandrudima sorry, I think this is mostly real issues repository. I was just thinking is there way to enable c# linter for VSCode and if there is actually any linter rules for c# out there. Did not find any useful info on this, so guessing that c# does not have coding style guides for linter out there.

**Comment by alexandrudima** [comment]
@idchlife Thanks, I didn't realize what you mean until I saw "linter" :). I moved the issue to OmniSharp/omnisharp-vscode#695
