### ISSUE TITLE
[theme] improve HC detection on MacOS

### ISSUE THREAD

**Issue by crunkilton** [microsoft/vscode#107359]
Issue Type: <b>Bug</b>

Actual results
1) Open VS Code and set theme to anything
2) Invert colors (cmd + option + control + 8)
3) VSCode changes the theme to "high contrast" (it can be changed back, but will revert to high contrast whenever colors are inverted again).

This started happening about a week or so ago. 

Expected results:
Inverting colors does not alter the theme in VS Code. 

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 12, 8|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 6cc1787e-c794-4061-b789-b89d2432cd77|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.3
jsonviewer|cci|1.2.2
macros|ged|1.2.1
kite|kit|0.123.0
MagicPython|mag|1.1.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.9.111407
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
sqltools|mtx|0.23.0
vscode-yaml|red|0.11.0

</details>

**Comment by aeschli** [comment]
Since the August release, VSCode automatically switches to a high contrast theme on the Mac if either `Invert color` or `Increase contrast` is set.
@crunkilton You can change that behavior by turning off setting `window.autoDetectHighContrast` or select a high contrast theme  of your choice by `workbench.preferredHighContrastTheme`.

Related issue https://github.com/microsoft/vscode/issues/106704.

@bpasero  IMO neither `Invert color` nor `Increase contrast` match the very powerful 'high contrast' mode that windows has. Switching to the the HC theme therefor seems to be too radical.
I suggest to either
- Only do so when both `Invert color` nor `Increase contrast`  are set
- Turn off `window.autoDetectHighContrast` on the Mac

**Comment by bpasero** [comment]
@aeschli yeah I am fine with both suggestions, my intent was to enable this capability but not necessarily to make it the default on macOS.

I feel like @isidorn should maybe give some 2 cents from the accessibility point of view.

**Comment by isidorn** [comment]
Yeah I like @aeschli suggestions.
Since this has been already done on Stable for a full milestone and only one user complained (as far as I know) I suggest to go with the lighter suggestion:
* Only do so when both Invert color nor Increase contrast are set

**Comment by bpasero** [comment]
@aeschli started in https://github.com/microsoft/vscode/tree/fix-107359 maybe you can continue. I see you are also depending on the `nativeTheme` in theme main service.

**Comment by bpasero** [comment]
Let's wait for more user feedback before making a decision here.

**Comment by jleedev** [comment]
A high contrast theme that doesn't invert the colors would be appropriate on macOS, fitting in with the system's interpretation of "add 1px borders to everything". As a mockup, the standard High Contrast theme could look like this when value inverted:

![Screen Shot 2021-03-19 at 11 08 37 AM](https://user-images.githubusercontent.com/23022/111802396-4f37c080-88a4-11eb-92cb-b033c9118310.png)

Note the white title bar in System Preferences, for example:

<img width="780" alt="Screen Shot 2021-03-19 at 11 08 06 AM" src="https://user-images.githubusercontent.com/23022/111802398-4fd05700-88a4-11eb-99c8-5de9b1572ef2.png">

Inverting the colors in response to macOS' high contrast setting looks sorely out of place. The system has a separate preference for light/dark appearance.

**Comment by aeschli** [comment]
@jleedev Yes, you are right. Unfortunately we don't have a light high contrast theme. We have/has issue https://github.com/microsoft/vscode/issues/100119 for that CC @misolori FYI

**Comment by aeschli** [comment]
We now have a light HC theme.

On the Mac, high contrast is set if one of the 'Invert colours' and `Increase contrast` settings in MacOS is set
