### ISSUE TITLE
After update code no longer has any context loading

### ISSUE THREAD

**Issue by aram535** [microsoft/vscode#107355]
After updating my system and pulling the latest version of code, I can no longer use Code.  All I get a blank gray window with the "Welcome - awm - Visual Studio Code" as the title.

Strange setup note: My linux servers are headless and therefore I am running X11 forwarding on SSH (XQuartz on a Catalina Macbook air).  I am running Code from a remotely started xterm (to make sure that the X11 is starting and connecting properly).

Last time I updated was about a month ago, the reason I updated is that GitHub Sync failed and so I figured something had been updated and that's the first step I tried.

Steps taken:
Started code with --disable-extensions, same result
Deleted the ~/.vscode dir, same result 
Deleted the ~/.config/Code dir, same result 
Started code with --verbose redirected to a log file ... resulting log file is attached. 

- VSCode Version:  1.49.1   58bb7b2331731bf72587010e943852e13e6fd3cf  x64
- OS Version: CentOS 8.2.2004

Steps to Reproduce:

1. Upgrade to this release
2. SSH to the linux server, with (-X) to enabel ForwardX11 
3. start xterm back to the MacBook 
4. start Code 
5. Window opens, title changes from "Visual Studio Code" to "Welcome - awm - Visual Studio Code" 
6. the rest of the window never loads, just a blank gray window content.
[code.log.gz](https://github.com/microsoft/vscode/files/5276182/code.log.gz)
 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/101069

Try launching with `--no-xshm`

**Comment by aram535** [comment]
@deepak1556 yes, with the --no-xshm it works, thanks for the workaround.
