### ISSUE TITLE
Javascript debugger should avoid program end before last step.

### ISSUE THREAD

**Issue by mikolertesx** [microsoft/vscode#107304]
Whenever you're using the Javascript built-in debugger, which uses Node, running the debugger inside will not cause the program to pause execution before it ends, and the debugger ends up being unable to peek at the variables.

Instead of having to add spaces at the end of the file just for debugging, there should be an option to set up the debugger to not close the program at the end.

**Comment by connor4312** [comment]
This could be done by having the debugger run something like `setInterval(() => {}, 10000)` to prevent the event loop from ending.

**Comment by mikolertesx** [comment]
If it's fixable, it would make my life a lot easier.
But I can understand if it's not a prioritity.
Thanks.
