### ISSUE TITLE
1.49.2 clicking cursor doesn't update with vscodevim controls

### ISSUE THREAD

**Issue by kalenpw** [microsoft/vscode#107403]
- VSCode Version: 1.49.2
- OS Version: Xubuntu 18.04 and macOS Catalina

Steps to Reproduce:

When you click somewhere in the code editor, it no longer updates your cursor position. So in other words if I am currently editing like 20, click on line 50 and then press `j` the cursor goes to line 21, instead of 51 as it previously did.

1. Use VSCodeVim Extension
2. Click somewhere in code editor
3. Use h/j/k/l to move cursor

Does this issue occur when all extensions are disabled?: Yes/No
No, if I disable all extensions if you click and then use arrow keys it works as expected

**Comment by JW9506** [comment]
I experienced this when they forced Vim 1.17.0 on me, downgrade your Vim to 1.16.0 manually, then your issue should be solved.

**Comment by alexdima** [comment]
Please report to the vim extension. fyi @rebornix
