### ISSUE TITLE
Scroll lag after update

### ISSUE THREAD

**Issue by PhoenixHe-msft** [microsoft/vscode#107416]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I'm editing a long markdown file (~1000 lines) and after upgrade to latest insider vscode the scroll lags.

VS Code version: Code - Insiders 1.50.0-insider (ddc98c3f620ab1d2ecad5942ebf4736060403d67, 2020-09-25T05:35:02.163Z)
OS version: Windows_NT x64 10.0.20223
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.27GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/htc/azure-rest-api-specs --crash-reporter-id 10698c5e-2fba-4f72-b5f5-3ee1a3408e40|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3599)|
|Memory (System)|7.77GB (5.56GB free)|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
vscode-peacock|joh|3.8.0
vscode-docker|ms-|1.6.0
remote-containers|ms-|0.141.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
vsonline|ms-|1.0.2823
debugger-for-edge|msj|1.0.15
vim|vsc|1.17.0
vscode-openapi|42C|3.6.0
Bookmarks|ale|11.3.1
swagger-viewer|Arj|3.0.1
LinkCheckMD|bla|0.3.1
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
docs-article-templates|doc|0.2.9
docs-authoring-pack|doc|0.1.8
docs-images|doc|0.0.9
docs-linting|doc|0.0.5
docs-markdown|doc|0.2.80
docs-metadata|doc|1.0.5
docs-preview|doc|0.3.55
docs-yaml|doc|0.2.5
githistory|don|0.6.10
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.1
vscode-pull-request-github|Git|0.20.0
vscode-peacock|joh|3.8.0
azure-pipelines|ms-|1.174.2
vscode-azurefunctions|ms-|0.24.1
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.9.111407
azure-account|ms-|0.9.3
cpptools|ms-|1.0.1
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2740
vsonline|ms-|1.0.2823
team|ms-|1.161.0
vscode-jest|Ort|3.2.0
vscode-versionlens|pfl|1.0.8
vscode-yaml|red|0.11.0
code-spell-checker|str|1.9.1
vscodeintellicode|Vis|1.2.10
vim|vsc|1.17.0

(2 theme extensions excluded)

</details>

**Comment by JW9506** [comment]
Can you reproduce it if you disable Vim?

**Comment by PhoenixHe-msft** [comment]
Yes, it still reproduces after vim disabled. I guess it's related to windows insider update, so I've sent a ticket to windows team.

**Comment by JW9506** [comment]
> Yes, it still reproduces after vim disabled. I guess it's related to windows insider update, so I've sent a ticket to windows team.

When people edit a huge file and face lag due when they navigate the file, it used to be related to the `Bracket Pair Colorizer` and `Vim` extension.

**Comment by PhoenixHe-msft** [comment]
That's not a huge file I suppose, and every file (even small ones) will lag on scroll.

**Comment by kieferrm** [comment]
Can you please check whether you see the same with disabled extension? https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled

**Comment by PhoenixHe-msft** [comment]
@kieferrm It doesn't work. Here is performance debug chart:

![image](https://user-images.githubusercontent.com/2346051/95557806-e8d28a80-0a47-11eb-80a7-0bcc0d356da4.png)

**Comment by PhoenixHe-msft** [comment]
Select one long frame 
![image](https://user-images.githubusercontent.com/2346051/95557916-0d2e6700-0a48-11eb-85c6-9b346bad45f4.png)

**Comment by jrieken** [comment]
We cannot work off screen shots, can you just attach the profile file

**Comment by PhoenixHe-msft** [comment]
@jrieken Attached. Thanks!
[Profile-20201009T182412.zip](https://github.com/microsoft/vscode/files/5354234/Profile-20201009T182412.zip)

**Comment by PhoenixHe-msft** [comment]
Hi @alexdima any update? I still experience scroll lags.

**Comment by enchant97** [comment]
I have found a temporary fix for scrolling lag that I have been experiencing (happened even with extensions disabled), I now run vscode from terminal with `code --disable-renderer-accessibility`. (I'm on Windows 10 with version 1.51)

**Comment by PhoenixHe-msft** [comment]
I've found the root cause: text cursor indicator. Disable the text cursor indicator in settings could solve this issue. Already tracked in windows feedback.
