### ISSUE TITLE
Extension names and descriptions incorrect in VSCode web

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#107460]
Extension names and descriptions are not correct on the extension list in VSCode web

Originally reported here: https://github.com/MicrosoftDocs/live-share/issues/3884

VSCode Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:24:04.104Z (1 wk ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

*Steps to Reproduce:*

1. Start a live share session
2. Join the session from web
3. Check the list of extensions

*Expected:*
Extensions listed with names and descriptions

*Actual:*
%displayName% and %description% are shown in place of the extension name and description

Does this issue occur when all extensions are disabled?: Yes/No: N/A - cannot control extensions in VSCode web

**Comment by sandy081** [comment]
I do not know how to follow above steps to repro. Can you please provide concrete steps?

Seems these are extensions installed by user, so, can you please open the folder where these extensions are installed check if they have `package.nls.json` files?

**Comment by IlyaBiryukov** [comment]
Repro:
1. Install Live Share extension in VSCode
2. Start Live Share session: Live Share viewlet -> Share (Read/Write)
3. That will create a URL and copy it to clipboard
4. Paste that URL in the browser
5. Do not open an app and instead click on "Join Live Share session from the browser" link.
6. VSCode in the web opens and joins the session
7. Check out the extensions viewlet

All extensions show %displayName% and %description%
Also the number of installed extensions (69) seems wrong.

**Comment by sandy081** [comment]
I can reproduce it and it seems VS Code in the web is a server-less version shown by the live share or (online.visualstudio.com). And it is not being created correctly. 

All these extensions those are shown are built in extensions but served as installed extensions. I think live share is using the `staticExtensions` API to contribute these extensions and I do not think this is correct. 

An embedder does not need to contribute built in extensions using `staticExtensions` API, instead it can just host them in the same location where workbench is served from. Please refer to our web playground application - http://vscode-web-test-playground.azurewebsites.net/?enter=true
