### ISSUE TITLE
Test: sudo-prompt and keytar moved into the main process

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107462]
Refs: 

- [x] macOS @sandy081 
- [x] linux @connor4312
- [x] windows @ornellaalt

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23107462%0A%0A)

---

**Test that:**
* you can save a file that needs elevated privileges (e.g. `/etc/hosts`) from the error notification that appears after trying to save normally
* you can use the GH PR extension (i.e. login and your credentials work)
* you do not see macOS keychain dialogs popping up repeatedly after confirming once with "Allow All"

**Comment by connor4312** [comment]
I was unable to fully test today as a result of https://github.com/microsoft/vscode-pull-request-github/issues/2168

**Comment by connor4312** [comment]
The PR extension only works with the nightly build on Insiders -- other verifies, make sure to use `github.vscode-pull-request-github-insiders` rather than the stable version.
