### ISSUE TITLE
Can't set keybinding in any pop widget, such as findWidget, command widget, quickfind widget, etc.

### ISSUE THREAD

**Issue by zy9306** [microsoft/vscode#107487]
- VSCode Version: 1.49.2
- OS Version: Windows_NT x64 10.0.19041

I use emacs keybinging in vscode, and install the https://marketplace.visualstudio.com/items?itemName=tuttieee.emacs-mcx. I can't set keybinding in any pop widget such as  findWidget, command widget, quickfind widget.

I set the ctrl+y in findWidget, but this not work. (ctrl+y should act as paste.I already unbinding the origin ctrl+y)

I also just set the ctrl+y to `paste` command, not the emacs-mcx't command, still not work.

![2020-09-26_10-40-39](https://user-images.githubusercontent.com/18747432/94328651-d9365900-ffe6-11ea-9a54-40ef3e449c67.png)
![2020-09-26_10-41-53](https://user-images.githubusercontent.com/18747432/94328654-e2272a80-ffe6-11ea-896e-6e1637f6fdcf.png)
![2020-09-26_10-43-30](https://user-images.githubusercontent.com/18747432/94328668-f66b2780-ffe6-11ea-9e84-11266b8432ee.png)
![2020-09-26_10-44-51](https://user-images.githubusercontent.com/18747432/94328672-fff48f80-ffe6-11ea-8a76-3801b4bfe0cf.png)

Does this issue occur when all extensions are disabled?: No

**Comment by alexdima** [comment]
@zy9306 It appears to me that the extension `tuttieee.emacs-mcx` [defines many keybindings](https://github.com/tuttieee/vscode-emacs-mcx/blob/ff20d6897dd2f37090f0bf70463073f84eb81c68/package.json#L107-L1511). Please ask for support about the keybindings defined by the extension at the extension itself.
