### ISSUE TITLE
webviewProtocolProvider.ts: deprecated require.toUrl() use

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107439]
The context is: https://github.com/microsoft/vscode/pull/107437 and the deprecation of `require.toUrl `

I noticed 2 uses of `require.toUrl` that ideally we can replace with `FileAccess.asFileUri` and `FileAccess.asBrowserUri`:

https://github.com/microsoft/vscode/blob/7506b2ba5ae3ee1052bff44d2f5129a61312b37b/src/vs/platform/webview/electron-main/webviewProtocolProvider.ts#L134-L138

I would have done it but wasn't exactly sure, my guess would be to use the `FileAccess.asFileUri` variant here since we are in `electron-main` context.

**Comment by mjbvz** [comment]
@bpasero Right now it looks like `FileAccess.asFileUri` returns a `file://` uri. Will it instead return a `vscode-file` uri as part of #107437?

**Comment by bpasero** [comment]
@mjbvz sorry, forgot to mention: currently on `master` I have just put stubs that do nothing, but in the `vscode-file` branch, you will:
* get a `file` scheme when using `asFileUri`
* get a `vscode-file` scheme when using `asBrowserUri`

As long as you are in node.js environments, it should be `asFileUri` unless you add this to a `electron-browser` renderer (e.g. DOM).
