### ISSUE TITLE
JSX HTML tags and their content's syntax highlighting are the same color

### ISSUE THREAD

**Issue by MichaelScoggins** [microsoft/vscode#107498]
i have spent a ~dozen hrs trying to get my syntax highlighting just right in my vscode while using javascript (and also react).

the last thing i cannot figure out is why my html tags are the same color as the html content. for example: 

`<this>and this is the same color as </this>`

i've tried using both language modes "javascriptreact" and "typescriptreact" but both seem identical in every respect. i have tried every single textmate scope and editor.semanticTokenColorCustomizations rule in the settings.json. nothing differentiates these two tokens.

it would help immensely while staring at JSX if these were differentiated, just as they are in regular .html files. 

if anyone could point me (or this issue) toward the right direction i would really appreciate it. i can provide any information needed.

by the way, VS Code is absolutely amazing, thanks for all the hard work!

**Comment by aeschli** [comment]
Can you add a small code sample?

**Comment by MichaelScoggins** [comment]
i actually figured it out. here was what i was looking for: 

`"editor.tokenColorCustomizations": {
    "[New Moon]": {
      "textMateRules": [
        // {
        //   "scope": "variable.other.readwrite.jsx",
        //   "settings": {
        //     "foreground": "#f2777a"
        //   }
        // },
        // {
        //   "scope": "variable.other.object.js.jsx",
        //   "settings": {
        //     "fontStyle": "italic bold underline"
        //   }
        // },
        {
          "scope": "variable.other.property.js",
          "settings": {
            "foreground": "#00e1ff"
          }
        },
        {
          "scope": "variable.other.object.property.js",
          "settings": {
            "foreground": "#00ffc8"
          }
        },`

with that general pattern continuing (sorry for the formatting, it's definitely formatted properly in the editor here... this is my first post). 

and the way i found the appropriate scopes was by "ctrl+shift+p" (command palette), and using Developer: Inspect Editor Tokens and Scopes and changing the top textmate scope in that section of the settings.json ... for example:

``` // textmate scopes	entity.name.tag.js.jsx
meta.tag.without-attributes.js.jsx
meta.block.js.jsx
meta.function.expression.js.jsx
meta.export.default.js.jsx
source.js.jsx
foreground	entity.name.tag
{ "foreground": "#6AB0F3" }
```

in my case it was `entity.name.tag` that needed to be scoped.

thank you so much for replying! 

here is the article that really made it clear what i had to do: https://medium.com/@steadylearner/how-to-enable-code-syntax-highlight-in-react-app-38463498fa6e
