### ISSUE TITLE
i was facing issue in visual studio code

### ISSUE THREAD

**Issue by johnwick1005** [microsoft/vscode#107468]
while i run a HTML & CSS in visual studio code it was showing Error like this...help me
![IMG_20200925_182321](https://user-images.githubusercontent.com/71536535/94297165-b1f97080-ff81-11ea-8db0-d0bd7495d607.jpg)

**Comment by johnwick1005** [comment]
> while i run a HTML & CSS in visual studio code it was showing Error like this...help me
> ![IMG_20200925_182321](https://user-images.githubusercontent.com/71536535/94297165-b1f97080-ff81-11ea-8db0-d0bd7495d607.jpg) please anyone help...

**Comment by isidorn** [comment]
Sounds like auto attach, forwarding to @connor4312

**Comment by connor4312** [comment]
Looks like you're trying to debug, but the thing you're trying to debug is not running. Please share more information about what you're trying to do.

/needsMoreInfo
