### ISSUE TITLE
VS code taking large memory even after disabling extensions

### ISSUE THREAD

**Issue by ManoharChaudhary** [microsoft/vscode#107417]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

Usually happens every day.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.65GB (6.81GB free)|
|Process Argv|--crash-reporter-id bcdd7cd3-4f9b-4a87-ade4-ee0d21597e65|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    82	  1660	code main
    0	    15	  4004	   crashpad-handler
    1	   225	  4716	   gpu-process
    0	    27	  8312	   utility
    0	   208	 17788	   window (ScheduleDialog.js - cm-flighting-widget - Visual Studio Code)
    0	    15	 17424	     watcherService 
    0	    10	 23196	       console-window-host (Windows internal process)
    0	    33	 19408	     searchService
    0	     6	 20664	     winpty-process
    0	     9	 10308	       console-window-host (Windows internal process)
    0	    66	 20200	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   106	 26020	     extensionHost
    0	   195	   956	       electron_node tsserver.js 
    0	    46	  4324	         electron_node typingsInstaller.js typesMap.js 
    0	    31	  3064	       "C:\Users\mchaudhari\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\mchaudhari\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=26020
    0	    47	  4644	       electron_node eslintServer.js 
    0	    28	  7200	       "C:\Users\mchaudhari\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\mchaudhari\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=26020
    0	    72	  9472	       electron_node tsserver.js 
    0	    55	 25840	       "C:\Users\mchaudhari\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\mchaudhari\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=26020
    0	    69	 21188	   window (Process Explorer)
    0	    70	 22168	   shared-process
    3	    63	 26488	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ScheduleDialog.js - cm-flighting-widget - Visual Studio Code)
|    Folder (cm-flighting-widget): 51 files
|      File types: js(21) scss(3) json(2) map(2) babelrc(1) gitignore(1)
|                  npmrc(1) prettierrc(1) yarnrc(1) html(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
react-pure-to-class-vscode|ang|1.1.8
simple-react-snippets|bur|1.2.3
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.3.1
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
