### ISSUE TITLE
Finding and replacing  text in selection cannot be automatically adaptive. 

### ISSUE THREAD

**Issue by ShoulderHe** [microsoft/vscode#107404]
Issue Type: <b>Bug</b>

Input the fowlowing text in the editor:
Line 1 : Hello, Man.
Line 2 : Hello, Woman.
Line 3 : Hello, World.

Do operations as fowllow:
1. Select the first line.
2. Open find pane, and enable 'Find in selection'.
3. Input text "Hello", the "Hello" in the first line is highlighted.
4. Select the second line in the text editor.
5. Focus the find pane again, the "Hello" in the second line cannot be highlighted automatically.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 6.1.7601

**Comment by rebornix** [comment]
This is expected as the "find in selection" is locked to previous selection (the first line). Currently we don't support modify the search area when cursor selection changes.

**Comment by ShoulderHe** [comment]
Automatically matching in the selection  is very useful, hope it will be approved.

**Comment by rebornix** [comment]
Let's track it in https://github.com/microsoft/vscode/issues/95356
