### ISSUE TITLE
Typescript language service died 5 times

### ISSUE THREAD

**Issue by AliSaberi** [microsoft/vscode#107428]
Hi. 
This errors happen in react projects !!!!
Even without no extension
Also the autocomplete was disappeared  !!

Os: Linux
version: 1.49.2

**Comment by AliSaberi** [comment]
Doesn't solve the problem !

**Comment by AliSaberi** [comment]
In create-react-app --template typescript, i don't get error !
but in normal project i get

**Comment by mjbvz** [comment]
Please fill in the issue template and provide steps to reproduce the issue

/needsMoreInfo

**Comment by mjbvz** [comment]
Also be sure to test in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)

**Comment by AliSaberi** [comment]
The problem is fixed. following action was done:
1. upgrade my OS from Ubuntu 18.04 to 20.04
2. reinstalling Vscode from snapcraft repository instead of APT
