### ISSUE TITLE
Simplify notebook cell output API

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107424]
The following changes to the current output API proposals are on the table. The focus is on simplifying and streamlining things (while still being equally powerful)

* Instead of three types for output, have a single type
* The effective output of a cell (`NotebookCell#output`) is many of these types (e.g NotebookCellOutput[])
* Each instance of `NotebookCellOutput` has a mime type, a value, and its metadata (iff applicable)
* Use a `plain/text` mime type for `CellStreamOutput`, respectively use an error mime type for `CellErrorOutput`

```ts
export class NotebookCellOutputItem {

	readonly mime: string;
	readonly value: unknown;
	readonly metadata?: Record<string, string | number | boolean>;

	constructor(mime: string, value: unknown, metadata?: Record<string, string | number | boolean>);
}

export class NotebookCellOutput {

	readonly outputs: NotebookCellOutputItem[];
	readonly metadata?: Record<string, string | number | boolean>;

	constructor(outputs: NotebookCellOutputItem[], metadata?: Record<string, string | number | boolean>);
}
```

Usage sample

```ts
// CURRENT proposed API
let output = [{
    outputKind: vscode.CellOutputKind.Rich,
    data: {
        'text/html': 'Hell<b>o</b>',
        'application/json': ['hello', 'json'],
        'image/png': '<base64>',
    },
    metadata: {
        custom: {
            'image/png': {
                'width': 640,
                'height': 480,
            }
        }
    }
}, {
    outputKind: vscode.CellOutputKind.Text,
    text: 'REPL text'
}]


// NEW proposal
let output = [
  new NotebookCellOutput([
    new vscode.NotebookCellOutputItem('text/html', 'Hell<b>o</b>'),
    new vscode.NotebookCellOutputItem('application/json', ['hello', 'json']),
    new vscode.NotebookCellOutputItem('image/png', '<base64>', { width: 640, height: 480 }),
  ], { display_id: 'xyz'} ),
  new NotebookCellOutput([
    new vscode.NotebookCellOutputItem('text/plain', 'REPL text'),
  ])
]
```

**Comment by jrieken** [comment]
partial implementation is here https://github.com/microsoft/vscode/pull/107426

**Comment by jrieken** [comment]
```ts
class NotebookCellOutputList {
  outputs: NotebookCellOutput[];
  metadata: Record<string, unknown>;
}

interface NotebookCell {
  output: NotebookCellOutputList[];
}
```

**Comment by jrieken** [comment]
Proposal and setting output is merged, but reading output is still the old API

**Comment by jrieken** [comment]
from https://github.com/microsoft/vscode/issues/107916#issuecomment-703687246

---

The need to extension to concat previous output bits with new output bits is bogus and wasteful, esp. since we will immediately remove what's already there. So, the idea of append or update output is something we should go after. I see two possibilities:

1. Have something similar to `vscode.OutputChannel` 
2. Allow a `NotebookCellOutput`-object to refer to an previous output-object to which is wants to be appended

The former approach is something well-known in API terms but we must be able to "spy" on the object so that we know when 'appendOutput' or such is called. The API concept for this to spec types as interface only and by offering a way to create an instance of said interface, e.g `createNotebookOutput`. This works well for long-lived objects but is likely cumbersome when the lifetime is short - as it is with notebook output. It is cumbersome because the extension owns the object and therefore must dispose it but the UI and API know/control when the object is of no more interest.

Therefore the second option might be better and simpler: An extension can keep hold of the last output and when creating a new object it would pass it along. It could look like so (building on the new output proposal https://github.com/microsoft/vscode/issues/107424)

```ts
export class NotebookCellOutput {

  readonly outputs: NotebookCellOutputItem[];
  readonly metadata?: Record<string, string | number | boolean>;

  constructor(
    outputs: NotebookCellOutputItem[], 
    metadata?: Record<string, string | number | boolean>, 
    appendTo?: NotebookCellOutput // previous output to which this is appended
  );
}
```

This makes it data-only objects which is generally simpler and preferred. What remains is how to signal to an extension that a complete new output is now active? The events we have for that might be enough tho

**Comment by DonJayamanne** [comment]
> What remains is how to signal to an extension that a complete new output is now active

At this stage, I can only see this being useful when output is cleared. I.e. output is empty.
Else as an extension, I'll continue to assume the output we have is the latest.

Though this does open the door for issues when user hits `undo` or the like (SCM revert), and this results in output changing, and we aren't in sync with those.

**Comment by jrieken** [comment]
> At this stage, I can only see this being useful & working (for python extension) when output is cleared.

I see two kinds:

1. Output is cleared (e.g by the user) and that's not a problem
1. Output is reset (e.g by another extension) and that's something you might wanna know. Tho, I am unsure about that

**Comment by brettfo** [comment]
I work on the [.NET Interactive Notebook extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode) for VS Code and we have some questions regarding the existing and proposed cell output functionality.

Our question seems to have been partially discussed above, but specifically, it's around the handling of STDOUT.  The suggestion is to treat cell stream output as `text/plain`​, but that will (and currently does) give the wrong output for regular STDOUT.  The issue is best expressed by example:

1. Jupyter Lab with a Python notebook with the following code:

   ``` python
   for i in range(5):
       print(i, end='')
   ```

   The output is the same as you'd get from a command line app:

   ```
   01234
   ```

   **A notebook opened with the Python VS Code extension also behaves this way.**

2. Jupyter Lab with a .NET Interactive notebook with the following code:

   ``` csharp
   for (int i = 0; i < 5; i++)
       Console.Write(i);
   ```

   The output is the same as you'd get from a command line app:
   ```
   01234
   ```

3. VS Code with a .NET Interactive notebook (i.e., the extension I work on) with the same code as (2) produces this output:

   ```
   0
   1
   2
   3
   4
   ```

The issue ultimately stems from each call to `Console.Write` getting wrapped in its own DOM element where from the user's perspective, these should really be together, probably replacing/updating an existing DOM element.

Have you had any discussions with the Python team around how to handle console/stream output?  I'm not sure what the solution looks like, but possibly it could fit into the existing and proposed models as a special mime type that corresponds to STDOUT and that VS Code does the special updating/replacing?  Something like `console/out`​?  Or perhaps it's a different API to append to the STDOUT display stream?  Given that this is a problem that every notebook kernel author will encounter, I'm hoping that there'll be a common approach to handling the display of this.

**Comment by jrieken** [comment]
@brettfo Can you validate you requirements against my thought: https://github.com/microsoft/vscode/issues/107424#issuecomment-703748207?

**Comment by brettfo** [comment]
@jrieken You mean the `NotebookCellOutput` contructor argument of `appendTo?`?  If I'm understanding the proposal, then our extension would track a specific `NotebookCellOutput` object that corresponds to STDOUT of cell 1 and another object for STDERR.  Then in our own code when we get a signal of STDOUT value received, we simply return a new `NotebookCellOutput` setting the `appendTo` value to the previous value, then tracking the new one for next time?  E.g.,

``` typescript
// pseudo-typescript
function onCellOutput(cell: NotebookCell, outputValue: SomeKindOfOutput) {
    if (isStdOut(outputValue)) {
        let stdOut = getStdOutForCell(cell); // still need to figure this out, possibly via cell metadata?
        let newStdOut = new NotebookCellOutput(ouputValue, metadata, appendTo: stdOut); // build on the previous one
        setStdOutForCell(cell, newStdOut); // track for next time
        return newStdOut;
    } else if (isStdErr(outputValue)) {
       // ...
    }
}
```

**Comment by jrieken** [comment]
Yes, along those lines. The final API shape might still change but the essence is that we allow you append to an existing output. Todays proposal uses the linking via the `appendTo` ctor-arg but I am also thinking of something event based

**Comment by DonJayamanne** [comment]
@jrieken Does this new API support concatenating output received from terminals.

For instance today we handle progress bars displayed in terminals.
We handle the command [Cursor Up](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#simple-cursor-positioning) when concatenating the stdout/stderr.

**Comment by jrieken** [comment]
We have done this. With the revised extension we are going to change how output items are delivered to the editor
