### ISSUE TITLE
editing not working

### ISSUE THREAD

**Issue by yarko** [microsoft/vscode#107455]
yesterday, it worked; today it doesn't.
Editing files is not working.

Vim plugin seems to be in place.   Can move cursor w/ cursor keys, but cannot find any way to edit / insert, delete charcters, etc.

Issue Type: <b>Bug</b>

vim extension (?) appears disabled - I can move cursor in a file via arrow keys - but cannot find a way to insert / edit file (worked yesterday).

VS Code version: Code - Insiders 1.50.0-insider (ddc98c3f620ab1d2ecad5942ebf4736060403d67, 2020-09-25T05:30:23.360Z)
OS version: Linux x64 5.4.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.26GB (0.35GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 2d601a7c-37e8-41d5-a777-e0dfedff81ef|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
hugofy|akm|0.1.1
markdown-toc|Ala|1.5.6
asciidoctor-vscode|asc|2.8.3
markdown-extension-pack|bat|0.6.0
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
language-hugo-vscode|bud|1.2.0
better-toml|bun|0.3.2
excel-to-markdown-table|csh|1.2.2
markdown-table-prettify|dar|2.5.0
vscode-markdownlint|Dav|0.36.3
vscode-rust-syntax|dun|0.0.32
mdmath|goe|2.5.1
go|gol|0.17.0
path-autocomplete|ion|1.15.0
asciidoctor-vscode|joa|2.8.0
edgedb|mag|0.1.5
markdown-shortcuts|mdi|0.12.0
rust-assist|moo|0.2.3
vscode-docker|ms-|1.6.0
python|ms-|2020.9.111407
cpptools|ms-|1.0.1
vsliveshare|ms-|1.0.2740
debugger-for-chrome|msj|4.12.11
rust|rus|0.7.8
markdown-preview-enhanced|shd|0.5.13
code-spell-checker|str|1.9.1
vscode-markdown-paste-image|tel|0.12.3
vim|vsc|1.17.0
gitblame|wad|5.0.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by yarko** [comment]
Removed .vscode directory in work space - apparently my attempts yesterday at configuring command-line debugging (per examples on https://code.visualstudio.com/docs/python/debugging)  affected editing (?).

Specifically, this was added to my json.launch:
```
{
  "name": "Python: Attach",
  "type": "python",
  "request": "attach",
  "connect": {
    "host": "localhost",
    "port": 5678
  }
}
```

I don't know if this should be considered a "bug" or not - I'll leave it to the discretion of maintainers to close this issue, or not.

**Comment by meginks** [comment]
I am having a similar issue with editing. I am not trying to use the Vim extension, but I do have it installed. When I try to insert a line or character, or delete a line or character, the cursor moves over the line and nothing is inserted or deleted. 

OS version: macOS Catalina 10.15.6 
VS Code version: 1.49.2

**Comment by meginks** [comment]
Update: I uninstalled the Vim extension, and can edit again.

**Comment by yarko** [comment]
Update:   I can only edit when first instantiating code-insiders;  after one file edit; I have to exit / enter again (so suspecting this is a Vim extension issue)

**Comment by yarko** [comment]
...strangely, I notice I can disable vim plugin (editing works) but I cannot disable nor uninstall any of a slew of markdown plugins (which undoubtedly were installed as part of go-hugo enabled installations)...   THAT is troubling...

**Comment by yarko** [comment]
I had been exclusively using code-insiders;  I just installed code (1.49) and Vim and "Markdown-all-in-one" and everything seems to be working fine here.

So - as for VScode issue:  not being able to disable any of the markdown extensions ... and their apparent interaction with blocking editing function:  this is the CORE issue, it would seem (w/o suggesting where the root of the problem is).

**Comment by rebornix** [comment]
I published a new version of Vim which fixes some of the editing problem mentioned above. @yarko are you still seeing editing issues with Vim extension disabled?

for the extension disablement issue, cc @sandy081

**Comment by sandy081** [comment]
Sorry there are bits and pieces here are there, can you please consolidate the issue about what is not working with extension disablement?

**Comment by yarko** [comment]
final comment:  on a current code-insiders on my laptop (also Ubuntu), I am not seeing this.  Installing code (not "-insiders"), I am not seeing this.   For now, I will assume it's either some interaction between particular versions of extensions, or (more likely - since I am not able to uninstall _any_ markdown related extension)  that something is corrupted in the copy of code-insiders (or settings) I have here.  Next step:  complete uninstall, clean, re-install (potentially of same mix of extensions?).  No time today, but will post when I've done that.

**Comment by yarko** [comment]
@rebornix - it does not appear changed (see above comment);
re: disablement / uninstall issue: apparently operator error:  I did not expand the message for disable/uninstall - I just did and saw the dependency in the message, and was thus able to uninstall a particular dependency.  Busy today, but will come back to "chase this dog" in days ahead...

**Comment by sandy081** [comment]
Waiting for info....

Closing this issue until the necessary info is provided.

Please reopen this after providing the info.

**Comment by yarko** [comment]
Sorry - I'd been using code (as opposed to code insiders), and today just upgraded insiders - this issue no longer shows up.
