### ISSUE TITLE
Memory run out when start vscode from gui (ubuntu 20.04)

### ISSUE THREAD

**Issue by dy51ex** [microsoft/vscode#107419]
- VSCode Version:
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:26:09.944Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic snap

- OS Version: Ubunto 20.04 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. install vscode via deb or snap
2. start from gui

Does this issue occur when 
all extensions are disabled?: No

When start vscode in gui, dbus-run-sessionand dbus-daemon starts cyclically run  until the memory runs out.
When run in console - all ok.
![processes](https://user-images.githubusercontent.com/7764872/94238692-66ab7780-ff19-11ea-93bf-8ec1c0bcf9d8.png)

**Comment by deepak1556** [comment]
What is the output of launching `code --verbose` from command line ?

> Does this issue occur when all extensions are disabled?: No

So when extensions are disabled the issue disappears ? Can you narrow down which extension is causing the issue ?

**Comment by dy51ex** [comment]
Extensions are probably enabled by default, the problem appears only if you run vscode from ubuntu GUI. If you run it from the command line, everything works fine with and without extensions. The problem appeared after a clean install of ubuntu.
The screenshots show that the number of tasks is constantly increasing, in 3 minutes 16GB of RAM ends.

![Снимок экрана от 2020-09-28 20-43-50](https://user-images.githubusercontent.com/7764872/94467615-dfd1f580-01cb-11eb-9ff8-93ba10bdf657.png)
![Снимок экрана от 2020-09-28 20-43-35](https://user-images.githubusercontent.com/7764872/94467619-e1032280-01cb-11eb-82e8-52ad68071514.png)
![Снимок экрана от 2020-09-28 20-42-33](https://user-images.githubusercontent.com/7764872/94467620-e19bb900-01cb-11eb-8477-2b9673c9af06.png)

**Comment by dy51ex** [comment]
Problems arise if run like this (or from the panel)

![Снимок экрана от 2020-09-28 20-42-51](https://user-images.githubusercontent.com/7764872/94468459-2116d500-01cd-11eb-98c2-80e34ef93821.png)

**Comment by deepak1556** [comment]
I am unable to repro with ubuntu 20.04 and snap installed code `1.49.2`.

Can you open `Help > Open Process explorer` from the app menu and paste the output when you see the high memory usage.

**Comment by BruneXX** [comment]
I've a similar issue with latest version of vs code at this point v1.49.2
I'm using Debian 9 (stretch) I've 16Gb of RAM and it's making swap, it's crazy!

**Comment by deepak1556** [comment]
@BruneXX does it continue to happen when you run with `--disable-extensions` ? Can you paste the output of process explorer following https://github.com/microsoft/vscode/issues/107419#issuecomment-700246912

**Comment by BruneXX** [comment]
Hi @deepak1556 I haven't tried with that option, I'll try and I'll let you know, thanks!
