### ISSUE TITLE
defaultWorkerFactory.ts: deprecated require.toUrl() use

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107440]
The context is: https://github.com/microsoft/vscode/pull/107437 and the deprecation of `require.toUrl `

I noticed 2 uses of `require.toUrl` that ideally we can replace with `FileAccess.asFileUri` and `FileAccess.asBrowserUri`:

https://github.com/microsoft/vscode/blob/08c92c9161a57cfe6f8e7badabbac6f96516737a/src/vs/base/worker/defaultWorkerFactory.ts#L22-L22

https://github.com/microsoft/vscode/blob/08c92c9161a57cfe6f8e7badabbac6f96516737a/src/vs/base/worker/defaultWorkerFactory.ts#L39-L39

I would have done it but wasn't exactly sure, my guess would be to use the `FileAccess.asBrowserUri` variant here since we are in `browser` context.

**Comment by alexdima** [comment]
I'm a bit concerned about changing this, as this piece of code runs in the standalone editor too. So before this piece of code would go directly to the loader (which could be `require.js` and not our loader) and get back a string.

With the proposed change to use `FileAccess.asBrowserUri`, this will now go through our `URI.parse` and I believe `URI.parse(str).toString()` is not guaranteed to be equal to `str`.

**Comment by bpasero** [comment]
@alexdima understood and that is also the reason why I wanted to ask you about it since I was not so sure.

When I test from the `vscode-file` branch it seems to me the worker is coming up properly, at least on macOS:

![image](https://user-images.githubusercontent.com/900690/94291879-7a2c0200-ff5c-11ea-977d-aa1c9d196996.png)

So it may well be that things continue to work, either with `file` or `vscode-file` protocol because we load the worker in a browser context always. 

I am fine leaving this use as is and maybe add a comment. I just wanted to bring this up to ensure this continues to work, even when we switch to the new base URL with `vscode-file://vscode-app/...` structure.

**Comment by bpasero** [comment]
I just added a comment explaining the use.
