### ISSUE TITLE
Support smart selection for markdown

### ISSUE THREAD

**Issue by mattbierner** [microsoft/vscode#107410]
Issue Type: <b>Feature Request</b>

**Request**
Support smart selection (expand/shrink selection) in markdown.

Example use cases:

1. Selecting inline elements such as inside matching backticks, `*`, or `**`

1. Selecting list elements.

1. Select block structures such as paragraphs, fenced code blocks, and block quotes

VS Code version: Code - Insiders 1.50.0-insider (f943318042a3b9229049aea86cea04d0ff9c8210, 2020-09-23T05:28:07.760Z)
OS version: Darwin x64 19.6.0

**Comment by mjbvz** [comment]
Currently does not seem easy for inline tokens since our markdown engine (markdown-it) does not generate correct column information: https://github.com/markdown-it/markdown-it/issues/125

**Comment by mjbvz** [comment]
To implement this:

1. In the markdown extension, create and register a `SelectionRangeProvider`: https://github.com/microsoft/vscode/blob/0579e831389c977e3f51981b8b59f524f510df89/src/vs/vscode.d.ts#L4352
1. Use the `MarkdownEngine` to parse the current file.
1. Transform the output of the file into selection ranges for the current cursor position

**Comment by mjbvz** [comment]
Some additional information we discussed today about this issue:

---

Here's a list of block level elements that should support smart selection:

- Fenced code blocks
- Block quotes
- Indented code blocks
- paragraphs
    
    Specifically paragraphs that are split into multiple lines:

    ```
    start of text
    continuing onto next line
    ```
- Lists
- [Front matter](https://github.com/ParkSB/markdown-it-front-matter)
- Inline html elements

Use your judgement on what selection ranges make sense and feel most natural. Test out the behavior in markdown from the  VS Code docs repo too

---

Once you have basic support, try adding adding smart select that spans multiple elements. For example, you can fold markdown based on headers. It would be cool if smart select also selected based on header level. As a simple example:

```md
# Top
Top text

## Sub

Paragraph 1 // Start cursor on this line

Paragraph 2

## Sub 2

Sub 2
```

Starting on `Paragraph 1`, I'd expect the additional selections to be (besides the default ones):

Start with the entire contents of the section

```md
Paragraph 1

Paragraph 2
```

Then expand the selection to include the header as well:

```md
## Sub

Paragraph 1 

Paragraph 2
```

Then select the the entire contents of the parent header:

```md
Top text

## Sub

Paragraph 1

Paragraph 2

## Sub 2

Sub 2
```

Then include the parent header in the selection too:

```md
# Top
Top text

## Sub

Paragraph 1

Paragraph 2

## Sub 2

Sub 2
```

**Comment by weinand** [comment]
@meganrogge I've changed the milestone from "Backlog" to "October" (to match the corresponding test item).

**Comment by JacksonKearl** [comment]
@meganrogge this can be closed, yes?
