### ISSUE TITLE
'vscode.executeHoverProvider' returns hovers with MarkdownString content that fail `instanceof` checks 

### ISSUE THREAD

**Issue by mattbierner** [microsoft/vscode#107414]
Issue Type: <b>Bug</b>

**Bug**
1. In an extension that uses `vscode.executeHoverProvider`

1. Make a hover request and then look at the results.

This extension demonstrates the issue. This line works around the problem (put a breakpoint here to test): https://github.com/mattbierner/vscode-docs-view/blob/ac3574abc229ca48cac396bccbeb9fa9668b3876/src/renderer.ts#L48

**Bug**
The returned hover object's content is a markdownString but it fails `instanceof vscode.MarkdownString`

VS Code version: Code - Insiders 1.50.0-insider (f943318042a3b9229049aea86cea04d0ff9c8210, 2020-09-23T05:28:07.760Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|40.00GB (5.95GB free)|
|Process Argv|-psn_0_5326100 --crash-reporter-id cefe23df-690f-4b1b-9ce9-e004d3be2745|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mattbierner** [comment]
Wow! Thanks for the quick fix Work Matt

**Comment by mjbvz** [comment]
Don't mention it, Other Matt!
