### ISSUE TITLE
Timed out waiting to get a heartbeat from kernel process

### ISSUE THREAD

**Issue by EvgNikulina** [microsoft/vscode#107494]
Issue Type: <b>Bug</b>

An error "Timed out waiting to get a heartbeat from kernel process." occurred around 3-4 days ago and i really don't understand why it's happened while writing the code in Jupiter Notebook

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.92GB free)|
|Process Argv|--crash-reporter-id 18963f43-9a35-4907-ad47-293169e7a087|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-markdownlint|Dav|0.36.3
gitlens|eam|10.2.2
vscode-pull-request-github|Git|0.20.0
latex-workshop|Jam|8.13.2
language-julia|jul|1.0.7
rainbow-csv|mec|1.7.1
vscode-language-pack-ru|MS-|1.49.1
python|ms-|2020.9.111407

</details>

**Comment by jkrygel** [comment]
I'm experiencing the same issue.
