### ISSUE TITLE
The git source control extension + the debugger extension keeps on crashing and get a modal that it crashed restart.

### ISSUE THREAD

**Issue by sujayvenaik** [microsoft/vscode#107402]
On extensive use, like files with around ~5k lines the source control extension crashes when resolving conflicts, discarding changes etc.

Also the debugger crashed too often. :cry:

Let me know if anything else needed from my end. 

---- System Info ----

CPUs | Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 2, 2, 3
Memory (System) | 16.00GB (5.34GB free)
Process Argv | --crash-reporter-id d6af9eb2-db5c-4f26-b706-c21ca4d90d64
Screen Reader | no
VM | 0%

**Comment by sujayvenaik** [comment]
![image](https://user-images.githubusercontent.com/11532114/94222997-7ec8ca00-ff0c-11ea-96e9-3c4b4aeb733b.png)


![image](https://user-images.githubusercontent.com/11532114/94223014-87210500-ff0c-11ea-9268-41996b3390a8.png)

**Comment by Diuda** [comment]
Facing a similar issue. Not even with a large file. My vscode debugger extension is crashing while just using the debugger itself. Especially when it has been restarted for several times

**Comment by kieferrm** [comment]
Pls file a separate issue for debugging.

**Comment by kieferrm** [comment]
@sujayvenaik can you pls provide the concrete steps, i.e. what does the SCM viewlet look like at the time, how to resolve conflicts, etc. Thanks!

**Comment by sujayvenaik** [comment]
@kieferrm @joaomoreno Can you tell me the exact questions you want information on? I can provide those.
Also if some profiling is needed for my system etc..

**Comment by joaomoreno** [comment]
Exact repro steps would be great. A screen recording as well. Detailed version information as well, as per our bug reporting template:

```
<!-- ⚠️⚠️ Do Not Delete This! bug_report_template ⚠️⚠️ -->
<!-- Please read our Rules of Conduct: https://opensource.microsoft.com/codeofconduct/ -->
<!-- Please search existing issues to avoid creating duplicates. -->
<!-- Also please test using the latest insiders build to make sure your issue has not already been fixed: https://code.visualstudio.com/insiders/ -->

<!-- Use Help > Report Issue to prefill these. -->
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

<!-- Launch with `code --disable-extensions` to check. -->
Does this issue occur when all extensions are disabled?: Yes/No
```
