### ISSUE TITLE
Sortable Keyboard Shortcuts

### ISSUE THREAD

**Issue by rohmanhm** [microsoft/vscode#107489]
My issue is a week ago I've customise my Keyboard shortcuts but now I forgot everything and when I want to memorise it again I couldn't recall the name of the shortcuts.

I want to have the ability to sort my Keyboard Shortcuts.
Maybe something like sort-by the latest update or name should do the job.

Thanks )))

**Comment by sandy081** [comment]
You can see the list of user modified keybindings using the search filter `@source:user` - I hope this works for you.
You can also open the file and see the list.

**Comment by rohmanhm** [comment]
Thanks @sandy081, It works!.
I didn't know vscode has that.
