### ISSUE TITLE
All using setting values inside tasks.json

### ISSUE THREAD

**Issue by killerall** [Microsoft/vscode#10740]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Hello,

I'm developing an extension to an own language.

To make the build I need different information that's in the "properties" of the extension.

However if I try to access by "{$ myextesion.myproperties}" I can't get the information.

Is there any way to do this?

I tried to build another way, using the command from contribution points.  The build worked, however I can't catch errors.
What I understood, only Tasks can send problemMatcher to User Interface, or I can do this from within a Command?

**Comment by dbaeumer** [comment]
@killerall can you provide and example what you want to achieve. Or a git repository I can clone that shows it. From your descriptions it is very hard to me to understand what you try to achieve.

**Comment by killerall** [comment]
@dbaeumer thanks for the reply
I don't have an git. Sorry.

Basically I would like to use all variables that i can use in lauch.json,
inside of tasks.json. Because I need different parameters of workspace going  to my compiler.

However, I did do by commands, notify the vscode of compilation errors.
With the following code:
```
// Values is string arrays with compile return.
var source = values [0];
var lineIndex = Number (values [1]) - 1;
var col = Number (values [2]);
var message = values [3];

var range = new vscode.Range (lineIndex 0, lineIndex, 10);
let diagnosis = new vscode.Diagnostic (range, message, vscode.DiagnosticSeverity.Error);
this.diagnosticCollection.set (vscode.Uri.file (source) [diagnosis]);

```
So,

It's only a suggestion for improvement to allow use of all workspace variables inside task.json

Sorry, my English is not good

Thanks a lot.

**Comment by dbaeumer** [comment]
Updated title.

**Comment by alexr00** [comment]
We now allow commands in in tasks.json 😊 https://code.visualstudio.com/docs/editor/variables-reference#_settings-command-variables-and-input-variables

**Comment by killerall** [comment]
Great!
I will be implementing soon.
Thank a lot!
