### ISSUE TITLE
Explore integration between extensions view and GitHub Sponsors

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#107482]
# Intro
This issue aims to explore what it could look like if we integrated GitHub Sponsors into the extensions view. Currently, extensions are not tied to a single user, so we'd need for a way for an extension to tell us what users they'd like to be added to the "sponsors" list. One idea is having a new entry in the `package.json` with a list of GitHub usernames that we could link to.

#  Design
We could remove the redundant information on the installed extensions (ratings + downloads) and add a ❤️ icon that signals to users that an extension can be sponsored by them. When opening the extension, we could have a special GitHub Sponsor button that links to the users being sponsored. One thing we need to consider is having multiple sponsors, do we introduce a new tab that has the list of sponsors? What other information would users want to know about before sponsorin?

![image](https://user-images.githubusercontent.com/35271042/94322810-624a8300-ff48-11ea-9b75-9c52ed5d77fa.png)

**Comment by misolori** [comment]
Here's another alternative where we show a "Sponsor" tag in the header and then what the tab could look like with additional sponsor data from the `funding.yml` file that is created:

![image](https://user-images.githubusercontent.com/35271042/94496567-97a1db80-01a9-11eb-952e-8605b986007c.png)

**Comment by RandomFractals** [comment]
please ship the second version with external links for other ways to sponsor.

**Comment by Borvik** [comment]
> We could remove the redundant information on the installed extensions (ratings + downloads)

I wouldn't call the ratings/downloads redundant.  When someone is searching for an extension and many show up, it is often easier to pick through the list by going straight to the more popular ones.  This is usually a first pass I run to help weed out junk extensions (though I understand the extension could just be _new_)  By removing it from the list, you now have an extra click and have to check each and every extension to see this information.

**Comment by misolori** [comment]
@Borvik I was referring to **installed** extensions. The ratings and downloads are useful when you are browsing extensions to install but not once you've installed it.

**Comment by RandomFractals** [comment]
I did not even catch that in those pics. I agree with @Borvik that it would be helpful to see # of installs and ratings in extensions list. perhaps as another line under ext. name and version in that list view item.

**Comment by misolori** [comment]
What's helpful about seeing the ratings/downloads for **installed** extensions?

**Comment by RandomFractals** [comment]
as @Borvik mentioned seeing the ratings and number of installs helps devs decide if that is the extension they want to check out, or read the docs, which would be 1 click away now.

**Comment by misolori** [comment]
I'm trying to understand, why would you want to check out an extension that is already installed? Isn't that something you look into before you install it?

**Comment by RandomFractals** [comment]
I would just keep it consistent for both installed and search view display extensions.

**Comment by RandomFractals** [comment]
also, does this mean you are finalizing that sponsor buttons UI & will you support other platforms besides github listed in funding.yml?

**Comment by Borvik** [comment]
I didn't realize it was just for _installed_ extensions, I'm ok with it not showing in that list.

Just checked and I'm not seeing it in the list when searching for extensions to install - and I'm not seeing it there - perhaps we need a different issue/request to get rating/installs added to the search list

**Comment by misolori** [comment]
@RandomFractals this issue is to explore the design of the layout so development hasn't started yet. Since this is specifically about GitHub Sponsors I think using the info from the `funding.yml` file makes the most sense, so whatever information a repo places in that file is what we will show (like external links).

@Borvik ratings and installs are still part of the extensions view:

<img width="400" src="https://user-images.githubusercontent.com/35271042/96160947-7f310100-0ecb-11eb-86c3-820088ee51ba.png">

**Comment by Borvik** [comment]
my bad - turns out it is a viewport thing - no worries then
![image](https://user-images.githubusercontent.com/1764750/96161227-ffb02b80-0ee4-11eb-956d-2600fd681cf2.png)
![image](https://user-images.githubusercontent.com/1764750/96161258-09d22a00-0ee5-11eb-81b8-b138d9fdbb8d.png)

**Comment by misolori** [comment]
@sandy081 is this a bug? I don't think we ever discussed hiding that from smaller viewports and I think having that info is extremely useful when browsing for extensions.

**Comment by RandomFractals** [comment]
>  I think using the info from the funding.yml file makes the most sense, so whatever information a repo places in that file is what we will show (like external links).

good to hear. I think the installs and ratings display as you have now looks good. Not sure if cramming new sponsor button there makes sense since you plan to add it in the ext. details view.

proceed as mocked up! :) can't wait to see it in the next release or two.

**Comment by sandy081** [comment]
> @sandy081 is this a bug? I don't think we ever discussed hiding that from smaller viewports and I think having that info is extremely useful when browsing for extensions.

Nopes, this is how it is from the time it is implemented by @joaomoreno 😉

**Comment by joaomoreno** [comment]
This is there since day 1. 😆

**Comment by RandomFractals** [comment]
can't you wrap it and show installs and ratings in the next line for smaller viewports like I suggested above?

**Comment by fabiospampinato** [comment]
This would be great to see, hopefully it will be moved back into an iteration plan.

Further more it would be awesome if vscode every once in a while were like: "Hey there, you used this extension about a 1 million times this month, would you like to give something back to the developers?"

**Comment by RandomFractals** [comment]
oh, I did not know this did not make the cut of your recent iteration plans.

I think it would be good if it was added back and released with what's new in extensions feature.

I also like @fabiospampinato suggestion. Maybe after 1000th activation of extension, vscode could show a separate sponsor dev view to prompt devs to support 3rd party vscode extensions. ;)

**Comment by isidorn** [comment]
Assigning to December so I start investigating the end to end experience for this.

**Comment by isidorn** [comment]
We have done the initial investigation and we are now working with the Marketplace team on the implementation.
Thus moving to February milestone when we will have more details. Thanks!

**Comment by sandy081** [comment]
Supporting sponsoring extensions from VS Code. An extension author can enable sponsoring by providing the `sponsor` URL in the extension's package.json and VS Code will allow users to sponsor to that extension using following UI. Clicking on `sponsor` button will take user to the sponsor link provided by the author.
![image](https://user-images.githubusercontent.com/10746682/170987533-db0ad37d-cbb5-406d-ba89-c19e26b5f61d.png)

**Comment by isidorn** [comment]
Here's the announcement https://github.com/microsoft/vscode-discussions/discussions/14
Try it out and let us know what you think in that discussion. Thanks!

**Comment by RandomFractals** [comment]
I really like new vscode discussions setup & hope it takes on.

Thank you guys for making it happen & this sponsors feature.
