### ISSUE TITLE
White Lines 

### ISSUE THREAD

**Issue by BisoyJan** [microsoft/vscode#107445]
![Screenshot 2020-09-25 213320](https://user-images.githubusercontent.com/55359040/94273270-c2581e00-ff76-11ea-9777-073867d6b91f.png)
this white lines i dont know what causing it. the other application doesn't have this kind of issue only visual studio code

**Comment by kieferrm** [comment]
Do you see the same issue when you start VS Code from the command line with the `--disable-gpu` option?

**Comment by BisoyJan** [comment]
thanks for replying back. I already solved the problem. I just need to
reinstall the VS Code
