### ISSUE TITLE
"Go Back" doesn't jump to the opened editor from content provider recently opened

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#107408]
In Java extension, we contributed a customized content provider to render the source for the binary class file. When the opened editor enable preview via `"workbench.editor.enablePreview": true`, `Go -> Back` doesn't jump to the last .class file opened by the customized content provider.

See the screencast below, we opened a Java file first, then go to the class file several times. Click "go back", it skipped the class file, but returned to the Java file directly.
![goBack](https://user-images.githubusercontent.com/14052197/94226588-9151fc00-ff2a-11ea-9e54-803a06517845.gif)

But if I turn off the editor preview, `go back` works well. It can jump to the last opened content provider editor.

**Comment by bpasero** [comment]
This is a consequence of the fact that the editor is being disposed once navigated away from. You can resolve this by registering a file system provider and not a content provider. You can register it readonly to get a similar experience.

**Comment by testforstephen** [comment]
> This is a consequence of the fact that the editor is being disposed once navigated away from.

Having that said, the previously opened disk file should have the same behavior. The truth is it only lost the content provider editors, but still can go back to the previous disk file. That's not consistent from the user's perspective, and it's a bug.

Also i believe this is not an extension specific issue, and implementing a file system provider is a little far to go.

**Comment by bpasero** [comment]
I am sorry, there is no plan to change this. We can never restore a disposed editor ever.
