### ISSUE TITLE
VSCode on DELL Precision5540 Performance

### ISSUE THREAD

**Issue by jack-chan-git** [microsoft/vscode#107427]
Issue Type: <b>Feature Request</b>

Hi,

I have two laptops, DELL Precision5540 and DELL XPS13.
Here ar ethe related hardwares:
         Precision5540                                  XPS13
CPU: i7-9850H@2.6G                                i5-8250U@1.6G
RAM: 32.00GB                                           8.00GB
HD:    SK hynix PC601 NVMe 512GB         Samsung PM691 NVMe 256GB

When I compile the same C code on the both machine, Precision takes about 4 minutes to complete while XSP13 only takes about 2 minutes.
I installed extactly the same version of VSCode and GNU compiler toolchain.

Would you please give some advices how to improve the performance on the Precision?

Thanks,
Kind regards,

Jack

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363

**Comment by JW9506** [comment]
Compiling codes isn't IDE related, can you reproduce the problem in just a terminal?

**Comment by jack-chan-git** [comment]
Hi,

Yes, the compile time is the same when I use PowerShell.
FYI.

Jack

**Comment by JW9506** [comment]
Then you just proved this issue is NOT VSCode related, this type of issues shouldn't be raised here... They will be mad.

**Comment by jack-chan-git** [comment]
Hi,

Agree, and sorry about that.
Then shall I cancel the ticket and where should I report this problem?
It is really annoying me. > <

Thank you.

Jack

**Comment by JW9506** [comment]
> Hi, Agree, and sorry about that. Then shall I cancel the ticket and where should I report this problem? It is really annoying me. 
Just be mindful of the software running in the background that can potentially eat away your PC resources. As a last resort, just reinstall the system so that if can test whether it is hardware related, if that's the case, just get a new pc. If you really want to ask this type of question on the internet you need to describe your situation in detail, otherwise people will just turn away.
