### ISSUE TITLE
Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\cli.js'

### ISSUE THREAD

**Issue by brajjan** [microsoft/vscode#107432]
- VSCode Version: 1.49.1
- OS Version: Windows 10 Education 1909 Build 18363.1082

Steps to Reproduce:

1. Tried to open a folder
2. VSCode turned blank (black screen) 

Does this issue occur when all extensions are disabled?: Yes

~ ❯ code --version
internal/modules/cjs/loader.js:847
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1103:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
~ ❯ code --disable-extensions
internal/modules/cjs/loader.js:847
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1103:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

~ ❯ Test-Path 'C:\Program Files\Microsoft VS Code\resources\app\out\cli.js'
False

Solution: Reinstall vscode

This has happened to me twice today, and before that ocationally

**Comment by isidorn** [comment]
I have no clue who owns this. Forwarding to @alexdima for the loader

**Comment by alexdima** [comment]
Looks like `C:\Program Files\Microsoft VS Code\resources\app\out\cli.js` is missing. That is before our AMD loader comes into the picture.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by gjsjohnmurray** [comment]
Maybe an antivirus product is interfering?

**Comment by joaomoreno** [comment]
@brajjan Have you tried reinstalling VS Code?

**Comment by buka102** [comment]
Hi I have same problem. VS Code is crashing on second day after reinstallation (3rd time), with message: 
"error: cannot find module 'c:\program Files\Microsoft vs code\resources\app\out\main"

> code --version produces:
Error: Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1103:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

I reinstalled VS code 3 times.

Version: 1.51.1 (system setup)
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Also have VS 2019 Professional installed.

**Comment by gjsjohnmurray** [comment]
Are you using an antivirus product? If so, which one? And did you check its log for any clues?
