### ISSUE TITLE
Remote Explorer shows multiple remote types on first load

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#107457]
Issue Type: <b>Bug</b>

1) Install the Remote-SSH and Codespaces extension
2) Reload
3) Open a new empty window
4) Open the Remote Explorer
-> Remote Explorer drop down shows "Codespaces" while both views are visible
5) Use the drop down in the Remote Explorer
-> You only see what you selected in the drop down

VS Code version: Code - Insiders 1.50.0-insider (ddc98c3f620ab1d2ecad5942ebf4736060403d67, 2020-09-25T05:30:51.469Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.3.0-1020-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_7628614 --crash-reporter-id d4b72415-0109-45b3-a1a7-967fdd12f0f4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.3.0-1020-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.61GB (3.81GB free)|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-track-build-errors|aes|0.0.2
git-branch|ale|1.6.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
tsl-problem-matcher|eam|0.3.0
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
graphviz-markdown-preview|gee|0.0.8
vscode-pull-request-github-insiders|Git|2020.9.34023
mdmath|goe|2.5.1
crazy|kie|0.0.2
svgpreview|kis|0.2.0
rainbow-csv|mec|1.7.1
theme-monokai-pro-vscode|mon|1.1.17
vscode-docker|ms-|1.6.0
python|ms-|2020.9.111407
remote-containers|ms-|0.141.0
remote-ssh-edit-nightly|ms-|2020.9.35460
remote-ssh-nightly|ms-|2020.9.35460
remote-wsl|ms-|0.44.5
azure-account|ms-|0.9.3
azurecli|ms-|0.5.0
js-debug-nightly|ms-|2020.9.2417
vscode-github-issue-notebooks|ms-|0.0.52
vscode-js-profile-flame|ms-|0.0.9
vscode-markdown-notebook|ms-|0.0.10
vsonline|ms-|1.0.2823
material-icon-theme|PKi|4.3.0
ruby|reb|0.27.0
vscode-xml|red|0.13.0
vscode-ruby|win|0.27.0

(4 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
@kieferrm I would expect that to have been fixed by https://github.com/microsoft/vscode/commit/2a77a2f7a5d596b2903ff91f4ebb23ceb3d3ce56, but you encountered this on a later build. I can't get the issue to repro, are there any additional steps?

**Comment by kieferrm** [comment]
@alexr00 unfortunately not.

**Comment by alexr00** [comment]
@kieferrm I've uninstalled, reinstalled, reloaded, and opened empty windows to no avail. In the bug it says you had a remote OS, but that isn't in the repro steps. Were you connected to a remote?
