### ISSUE TITLE
Duplicate Git repositories in Source Control

### ISSUE THREAD

**Issue by alexagranov7** [microsoft/vscode#107401]
Issue Type: <b>Bug</b>

Pretty much what is says in the title. Only I can't even close them anymore. It's causing havok on Git Push.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

**Comment by gjsjohnmurray** [comment]
Any reason for not updating to the latest Stable release?

If you still have the problem after doing that, please use the command to reload with all extensions disabled, then retest.
