### ISSUE TITLE
Wrong cursor position in Terminal

### ISSUE THREAD

**Issue by MiroJ** [microsoft/vscode#107453]
Issue Type: <b>Bug</b>

When I start VS Code and open Terminal with `Ctrl+~`, I see the cursor on the first line positioned over the `>` character of the current path. 

![image](https://user-images.githubusercontent.com/1686322/94286541-23560680-ff23-11ea-96c6-0258e0db4c69.png)

When I hit Enter on my keyboard, the cursor goes to the proper position - one after the `>` character.

![image](https://user-images.githubusercontent.com/1686322/94286622-3e287b00-ff23-11ea-893f-513357136d89.png)

This is only the first time I open the Terminal. If I close it with the garbage bin icon and reopen it again, the position is proper. I can also type and execute the command properly, regardless of the position.

![image](https://user-images.githubusercontent.com/1686322/94287025-cc046600-ff23-11ea-8c42-340442c88cda.png)

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (6.99GB free)|
|Process Argv|--crash-reporter-id 724bd6f8-c878-422c-a5ef-1e7f45e2565d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1001.0
xml|Dot|2.5.1
prettier-vscode|esb|5.7.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
trailing-spaces|sha|0.3.1

</details>

**Comment by rzhao271** [comment]
@MiroJ I can't reproduce this issue on the latest [Insiders](https://code.visualstudio.com/insiders/). Can you try again on there?

**Comment by MiroJ** [comment]
Visual Studio Code 1.51.0 has it fixed. I am closing the issue. Thanks!
