### ISSUE TITLE
Codespaces: Extension viewlet in perpetual refresh mode

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#107463]
Issue Type: <b>Bug</b>

1) Create a codespace from the VS Code repo
2) Let the codespace sit idle so that it suspends
3) Open a new empty VS Code Window
4) Open the remote explorer
5) Connect to the codespace created in step 1)
6) When the explorer shows content, open the extension viewlet
-> Codespaces section is empty and remains empty; progress bar never stops

![BjiJ25yhSM](https://user-images.githubusercontent.com/4674940/94295283-d9b2ef00-ff15-11ea-9066-3f92e9cb7330.gif)

VS Code version: Code - Insiders 1.50.0-insider (ddc98c3f620ab1d2ecad5942ebf4736060403d67, 2020-09-25T05:30:51.469Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.3.0-1020-azure
Remote OS version: Linux x64 5.4.0-1025-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|-psn_0_7628614 --crash-reporter-id d4b72415-0109-45b3-a1a7-967fdd12f0f4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.3.0-1020-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.61GB (3.80GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: kieferrm-microsoft-vscode-pxc3|
|OS|Linux x64 5.4.0-1025-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (2 x 2693)|
|Memory (System)|3.84GB (0.21GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|eam|0.3.0
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
theme-monokai-pro-vscode|mon|1.1.17
vscode-docker|ms-|1.6.0
remote-containers|ms-|0.141.0
remote-ssh-edit-nightly|ms-|2020.9.35460
remote-ssh-nightly|ms-|2020.9.35460
remote-wsl|ms-|0.44.5
azure-account|ms-|0.9.3
vscode-github-issue-notebooks|ms-|0.0.52
vsonline|ms-|1.0.2823
material-icon-theme|PKi|4.3.0
vscode-ruby|win|0.27.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vscode-pull-request-github-insiders|Git|2020.9.34023
rainbow-csv|mec|1.7.1
hexeditor|ms-|1.3.0
vscode-github-issue-notebooks|ms-|0.0.52
vscode-markdown-notebook|ms-|0.0.10
vscode-typescript-tslint-plugin|ms-|1.2.3

(4 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Can you please check if the remote server logs has any information?
