### ISSUE TITLE
Intellisense is all messed up even after disabling all extensions.

### ISSUE THREAD

**Issue by kpirvin** [microsoft/vscode#107488]
The inteliisense is all messed up and not showing possible switches.
It now gives me options for a lot of possible pre canned scripts like do until, ex class, ex splat, and it-pester. 
Is there a way to go back to the older intellisence or disable what has changed the autocomplete behavior

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
