### ISSUE TITLE
Dot and text overlap

### ISSUE THREAD

**Issue by SalehiAlireza** [microsoft/vscode#107493]
- VSCode Version: 1.49.1
- OS Version: win 10 x64 

Steps to Reproduce:

1. just copy below text and past in VsCode js page
```
    { 
    redirectAfter: 'انتظر لحظة...',
    }
```
and vs code showing you below image
http://s15.picofile.com/file/8409317618/Untitled.png

![image](https://user-images.githubusercontent.com/5047891/156350199-f53cdc4c-2ef2-42a3-bbc3-93795f5f9087.png)

Does this issue occur when all extensions are disabled?: i dont try it

**Comment by alexdima** [comment]
I can't reproduce this problem anymore in the latest VS Code version:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/5047891/156350517-79a02f29-a888-4c3a-b2d9-2ccc2ee7465e.png">
