### ISSUE TITLE
Search highlights wrong text in preview

### ISSUE THREAD

**Issue by jplackey** [microsoft/vscode#107459]
Issue Type: <b>Bug</b>

While using Search to find text across files, I ran into an issue in which the selected text/match displayed in the editor pane does not match the actual search expression.  In some cases, I was able to select a match from the left pane only to be taken to a location in the target file in the editor where no matching text was selected at all.

![image](https://user-images.githubusercontent.com/50848136/94291575-6ca55680-ff21-11ea-847a-27d38cb3ca44.png)

![image](https://user-images.githubusercontent.com/50848136/94291784-a8d8b700-ff21-11ea-89dc-9a78391b97b2.png)

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.14.47-64.38.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.69GB free)|
|Process Argv|--crash-reporter-id 98fc8c5a-1a40-4131-a076-36c401d139e2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: [redacted]|
|OS|Linux x64 [redacted|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz (8 x 2500)|
|Memory (System)|60.00GB (2.07GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
gitlens|eam|10.2.2
php-debug|fel|1.13.0
csharp|ms-|1.23.2
python|ms-|2020.9.111407
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
open-in-browser|tec|2.0.0

</details>

**Comment by roblourens** [comment]
Can you share the file with me?

Is it possible that it has CR-only newlines?

**Comment by jplackey** [comment]
The files are CR/LF terminated.  I have a set of files here, so let me try to find either one that doesn't need redacting or the smallest one possible to redact/send.  Will follow up.

**Comment by jplackey** [comment]
Some additional details: I went to redact some PII, and when I saved the file, the issue disappeared (for that file).  As such, I dug a little deeper.  I looked at the original file in Notepad++ with "show all characters" enabled.  The file is predominantly CR/LF line terminated, but there _are_ actually some instance of lines terminated only with CR.

Due to the size of the files in question and the volume of sensitive info within them, I can't send you those files as-is.  I could probably mock up a text file with a mix of CR and CR/LF line terminators to see if I can force the behavior if that would help.

**Comment by roblourens** [comment]
That makes sense, we normalize newlines when saving the file. No need to send the file, I am aware of this issue, but it's not easy to fix. What I don't understand is why people keep ending up with this. Any idea which editor/tool put these into your file?

**Comment by jplackey** [comment]
Thanks for confirming.  In my case, these files were logs produced by the GlobalProtect VPN client.
