### ISSUE TITLE
Java .properties files: Considers number sign (hash) as start of comment no matter where it occurs

### ISSUE THREAD

**Issue by Chealer** [microsoft/vscode#107481]
Issue Type: <b>Bug</b>

Open a Java .properties file (for example the application.properties of a Spring Boot application) which contains a hash character in the middle of the line (not as the first character), for example "spring.output.ansi.enabled=ALWAYS # Invalid comment"

Note that this ITS does not support .properties files.

This can be seen at line 28 in the following screenshot, where "Journaliser en couleur" is an invalid comment which should be on its own line:
![image](https://user-images.githubusercontent.com/486141/94321503-b318a680-ff5d-11ea-96af-a8dfcc1a7839.png)

As [explained on Wikipedia](https://en.wikipedia.org/wiki/.properties), comments in .properties files need to be on their own line.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.27GB free)|
|Process Argv|--crash-reporter-id f03105ec-6ab9-4f30-9a8e-fc1678d8a308|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-idea-keybindings|k--|0.2.41
vscode-xml|red|0.13.0

</details>

**Comment by Chealer** [comment]
I checked that this occurs even with the Java extension pack disabled, so I am guessing the Java extension is not the culprit. But if anyone is confident it is, feel free to move the issue.

**Comment by Chealer** [comment]
@vscode-triage-bot why is this ticket closed?

**Comment by mjbvz** [comment]
Proper support for java properties files should come from the Java extension

**Comment by Chealer** [comment]
@vscode-triage-bot , you closed this ticket without explanation on 2020-09-25. Thanks for reopening it; I cannot do that.
