### ISSUE TITLE
Extensions not loading

### ISSUE THREAD

**Issue by raulmvp** [microsoft/vscode#107499]
Issue Type: <b>Bug</b>

I turned up my pc to work today and any of my extensions seems to work, I've already tried to do it manually but it doesn't work.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 4|
|Memory (System)|8.00GB (0.80GB free)|
|Process Argv|--crash-reporter-id d8d0ba43-b41c-444f-a45d-3f16c1e5be77|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|11.3.1
laravel-extra-intellisense|ami|0.3.3
ng-template|Ang|0.1001.0
beautify-blade|api|1.0.1
laravel-blade-spacer|aus|2.1.2
git-easy|bib|1.11.0
vscode-intelephense-client|bme|1.5.4
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.3
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
EditorConfig|Edi|0.15.1
phpunit|ema|4.1.1
prettier-vscode|esb|5.7.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.8
shell-format|fox|7.0.1
todo-tree|Gru|0.0.178
vscode-test-explorer|hbe|2.19.1
php-cs-fixer|jun|0.1.156
vs-color-picker|lih|1.0.0
start-git-bash|McC|1.2.1
vscode-language-babel|mgm|0.0.29
dotenv|mik|1.0.1
laravel-intellisense|moh|0.1.8
mssql|ms-|1.9.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2740
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
laravel-blade|one|1.24.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.10.0
gitpatch|par|0.2.1
phpstorm-snippets|phi|1.1.1
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.27
laravel-goto-controller|ste|0.0.7
angular-template-formatter|str|0.1.2
vscode-icons|vsc|11.0.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
material-theme|zhu|3.9.0

(3 theme extensions excluded)

</details>

**Comment by JAugusto42** [comment]
@raulmvp Same here, loading only pre installed.

**Comment by sandy081** [comment]
What do you mean by not loading? You do not see them in the extensions view?
