### ISSUE TITLE
arduino port lose

### ISSUE THREAD

**Issue by LCKway** [microsoft/vscode#107492]
Issue Type: <b>Bug</b>

arduino port lose

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (11.27GB free)|
|Process Argv|D:\company\arduino\helloworld --crash-reporter-id 192b6b0a-9f21-4ca3-b139-342921db3e5c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
wenyan-lang|ant|0.11.4
code-gnu-global|aus|0.2.2
cortex-debug|mar|0.3.7
vscode-language-pack-zh-hans|MS-|1.49.2
cpptools|ms-|1.0.1
vscode-arduino|vsc|0.3.2

</details>

**Comment by rzhao271** [comment]
@LCKway can you provide some steps to help us reproduce the issue?
