### ISSUE TITLE
Rust file icon for file explorer

### ISSUE THREAD

**Issue by arnabanimesh** [microsoft/vscode#107413]
I use Rust on a daily basis. I want to have an icon for the Rust file type (.rs) visible in the file explorer.

**Comment by isidorn** [comment]
I believe this should be handled by an extension, but first forwarding to @aeschli since he owns the file icon theme I believe

**Comment by aeschli** [comment]
@arnabanimesh Which icon theme do you use?
The built-in Seti theme already has a Rust icon

![image](https://user-images.githubusercontent.com/6461412/94312793-de12f280-ff7d-11ea-8750-b30be6eaec89.png)

**Comment by arnabanimesh** [comment]
I meant the windows file explorer.
![Image](https://www.computerhope.com/jargon/e/explorer-win10.jpg)

**Comment by jhpratt** [comment]
Aren't those icons controlled by the operating system, not the editor?

**Comment by arnabanimesh** [comment]
> Aren't those icons controlled by the operating system, not the editor?

Editor has to implement the icon though. Then it comes to the user (and OS).
VS Code has its own icons for specific file types (like C, PHP). Currently, there are is no icon for the Rust source code.

**Comment by ryanhossain9797** [comment]
> Aren't those icons controlled by the operating system, not the editor?

I think it's upto the `default program` to assign the icon to a filetype.

**Comment by joaomoreno** [comment]
Sorry but I will close this since our current position is that we won't add endless icons to the product. @misolori

**Comment by Weasy666** [comment]
Hm...on which basis are you going to decide which icon gets added to the editor?  I can only speak for myself, but when i see a icon for a `C++` file or a `JavaScript` file, then i would also expect a icon for `Rust`, or any other halfway widespread language.

**Comment by misolori** [comment]
When we first developed these icons we looked at the top ~30 languages that were being used and that's how we decided. We haven't added any new icons since as each icon requires 3 different sets (mac, win, linux) across our various versions (oss, insiders, exploration, stable).

**Comment by Weasy666** [comment]
Thank you for the clarification. I can understand that this could end in a lot of work, so is it possible or would it be possible to add a way for set such icons with an extension? At least in my mind, this would be a fitting addition to current icon themes/extensions.

**Comment by misolori** [comment]
We did want to do that but unfortunately system file icons are created during runtime so they need to exist before the build starts. So there isn't a way for extensions to control this.

**Comment by Weasy666** [comment]
That is a shame! Thanks again, for taking the time.
