### ISSUE TITLE
 Git: Commit Staged (Amend)  with empty staging area asks to save dirty editors

### ISSUE THREAD

**Issue by alexanderkjeldaas** [microsoft/vscode#107452]
Issue Type: <b>Bug</b>

1. Keep the staging area empty (i.e. move all changes out of staging)
2. Edit a file
3. Do a "Commit Staged (Amend)"

You will now be asked to "save and commit all" (if I remember correctly).

Expected:

I will be asked to update the commit message only, possibly with some warning as this could be a out-of-the-ordinary operation.

Also, if the staging area is non-empty, only if any editor has changes that touches files that are in the staging area should I be asked to save files.

There might be reasons to always ask to save all files before a commit, and that makes the reported bug a specific corner-case you might not want to fix, but then I propose that there is a checkbox "never ask for this project" in this dialog box.

I don't feel like the dialog box asking me to save and commit is bringing any value, and never so for people that have workflows where a larger change is split up into smaller commits, so having a "clean file system" is not particularly normal (for example git stash is used when it's needed, not git commit).

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.83GB free)|
|Process Argv|-psn_0_200753 --crash-reporter-id 89d1d885-9ca1-4be1-a8ca-f10a7b891ab0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
Kotlin|mat|1.7.1
good-enough-scala-lsp|mrd|1.4.0
python|ms-|2020.9.111407
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
scala|sca|0.4.3
metals|sca|1.9.4
html-preview-vscode|tht|0.2.5
vim|vsc|1.17.0

</details>

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/104945
