### ISSUE TITLE
How can I implement format-on-save?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10741]
- VSCode Version: 1.4
- OS Version: Windows 10

I can't currently support format-on-type in Code because my formatting API can only do full documents. As a next-best-thing I wanted to add format-on-save. However, I'm struggling to find how I can get back to an `editor` in the `onDidSaveTextDocument` event in order to apply this (without looping through open editors, which doesn't seem very clean).

Even if I do go ahead and loop through active editors and find the correct one for my document, applying the editors doesn't seem easy - `executeCommand("vscode.executeFormatDocumentProvider")` returns an array of `TextEdit` but `editor.edit` provides an `editBuilder` that has `insert`/`delete`/`replaced` methods that don't take `TextEdits`. Although I could map them, it seems like I'm probably duplicated a lot of logic that already exists.

The ideal would be a format-on-save option within Code, or the ability to just call format on a document (and have it invoke the provider, apply the edits, return promise)!

```typescript
onDidSaveTextDocument(document: vs.TextDocument) {
	if (!util.isAnalyzable(document) || document.languageId != "dart")
		return;

	vs.commands.executeCommand("vscode.executeFormatDocumentProvider", document.uri)
		.then((resp: vs.TextEdit[]) => {
			// TODO: Get editor for this document
			// TODO: Convert TextEdits to something that can be passed to EditBuilder?
			// TODO: Then call document.save();
		});
}
```

**Comment by mrmlnc** [comment]
So, welcome to the hell :smiling_imp:

Refers to https://github.com/Microsoft/vscode/issues/3588 and https://github.com/Microsoft/vscode/issues/239

Now you can use this variant: https://github.com/mrmlnc/vscode-stylefmt/blob/master/extension.js

**Comment by DanTup** [comment]
Ugh :( Looks like it was nearly done in April! I'll add a comment to there and abort trying to do this manually. Thanks!
