### ISSUE TITLE
Opening multiple files from Windows Explorer context menu opens multiple windows

### ISSUE THREAD

**Issue by eyalsk** [Microsoft/vscode#10747]
On Windows `SendTo` is sometimes used to open multiple files but VSCode isn't listen there.

Is it possible to add it?

I looked briefly and didn't see this issue so there it is. :)

**Comment by joaomoreno** [comment]
Applications are not usually listed in that submenu, just _locations_.

The Windows setup allows you to add a context menu entry that will work for multiple files.

![Uploading image.png…]()

**Comment by eyalsk** [comment]
@joaomoreno The issue is it will create multiple instances of the editor instead of opening it up in a single instance, generally, when you select multiple files, you expect the files to be opened in the same instance.

**Comment by bpasero** [comment]
We fixed this.
