### ISSUE TITLE
After the update on 25th sept 2020(India)(windows 7) the shortcut and executable files etc are gone...like completely gone

### ISSUE THREAD

**Issue by avendeep** [microsoft/vscode#107411]

**Comment by gjsjohnmurray** [comment]
Any antivirus product that might be doing this?

**Comment by kieferrm** [comment]
@avendeep pls see above comment.

**Comment by avendeep** [comment]
> @avendeep pls see above comment.
I don't think so, back in 2018 similar kind of incident had happened.
[previous issue](https://github.com/Microsoft/vscode/issues/50544)
this happened specifically with the 25th Sept update..
Later I've download .exe file from the official site, surprisingly after the installation all the previous IDE setting & extensions were restored.
