### ISSUE TITLE
Ability to press `return` in Search Editor search to go to the file with searches

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#107447]
If I am doing a search in `Search Editor` page like this:

<img width="231" alt="image" src="https://user-images.githubusercontent.com/6391776/94275875-ca4c9980-ff47-11ea-9a91-f60c400ea4ad.png">

If I want to go on and focus on the file with searches and go up and down the file I have to press cmd+down-arrow.

It would be nice if I could just press return to bring focus to the file as the search view updates automatically already as user types so there is no use for pressing return (it does nothing when search is active).

Perhaps this is possible to bind already. I am not sure if there is a context of `Search Editor search view active`?

Thank you.

**Comment by JacksonKearl** [comment]
The current binding is:
```
{
  "key": "cmd+down",
  "command": "search.focus.nextInputBox",
  "when": "inSearchEditor && inputBoxFocus || inputBoxFocus && searchViewletVisible"
}
```

You could potentially add an additional one for enter in the search editor.

**Comment by JacksonKearl** [comment]
Were you able to get this behaviour working via the keybind?

**Comment by nikitavoloboev** [comment]
I did, thank you @JacksonKearl
