### ISSUE TITLE
Make task templates configurable

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#10742]
I started implementing a command to run tests, but the noticed there's a command in the command palette called "Run Test Task". It seems like it'd be a good idea to reuse this, since otherwise my "Run Dart tests" command appears even when there's not a Dart project open.

However, I'm struggling to find how I can actually fire this up. If I execute that command it says `No task runner configured` and when I click the option to configure it gives me a list of existing task runners. I figure I need to add a new item to this list that the uesr can select, which would then pre-fill their tasks.json with the correct things for executing tests.

However, I can't figure out how to contribute something to that list?

**Comment by DanTup** [comment]
Seems these might be hard-coded?

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/common/taskTemplates.ts

Are there plans to extend this? If not, what's the best way to handle this so that the end user doesn't need to configure things manually to run tests?

**Comment by dbaeumer** [comment]
Having ac contribution mechanism to the tasks.json templates is a fair request.

**Comment by DanTup** [comment]
Is there a good way to handle this in the meantime? I'm trying to avoid adding more commands while we can't restrict them to when our extension is activating, I'm worried about polluting the command list with Dart-specific things :-/

**Comment by dbaeumer** [comment]
No actually not.

**Comment by DanTup** [comment]
I haven't tried it yet, but does #8937 help with this now? Seems the settings API may allow us to write to `tasks.json`?

**Comment by dbaeumer** [comment]
@DanTup yes the settings API allows you to write the tasks.json. But asking extensions to do this might not be a good idea in general since it would require that all extensions are fair in terms of manipulating the tasks.json file..

**Comment by DanTup** [comment]
@dbaeumer I thought that was the reason for these changes? I'm currently using this for `launch.json` changes (see #15062 for an example); is it something that should generally be avoided?

**Comment by dbaeumer** [comment]
@DanTup I think it depends on. For the test running case I would say yes. What should extension do if two extensions want to execute something when the user requests running tests. We have on the next iteration plan an item to think about how to continue with the task framework and one idea is that extensions can participate in Build, Run Test, Clean, Rebuild All, without contributing a task.

**Comment by DanTup** [comment]
@dbaeumer 

> We have on the next iteration plan an item to think about how to continue with the task framework and one idea is that extensions can participate in Build, Run Test, Clean, Rebuild All, without contributing a task.

This sounds great! Is there an Issue about this I can subscribe to? Are you considering better support than just "run a process and show the output" for tests (such as a structured pane that allows click to jump to tests, etc.)? I know you don't want to turn into a fat IDE, but I think there's a lot that could be done to aid/encourage testing =)

**Comment by dbaeumer** [comment]
@DanTup: https://github.com/Microsoft/vscode/issues/15179. But it is work in progress right now

**Comment by DanTup** [comment]
@dbaeumer Thanks, I'll add some comments about things I'd like to see (though I suspect they're very similar to TypeScript).

**Comment by connorshea** [comment]
See also #9505

**Comment by meganrogge** [comment]
🙁 In the last 60 days, this feature request has received less than 20 community upvotes and we closed it. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
