### ISSUE TITLE
[safari] Screen cheese in settings editor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107449]
* open codespace in safari
* open settings editor
* 🧀 the gear icons is cropped
* 🧀 the menu is cropped

<img width="775" alt="Screenshot 2020-09-25 at 16 22 50" src="https://user-images.githubusercontent.com/1794099/94278772-865b9380-ff4b-11ea-9a3f-0cd28f7db994.png">

**Comment by roblourens** [comment]
Can you tell me what version is in codespaces right now? Might have been fixed in the past 2 days.

**Comment by jrieken** [comment]
`403a6895f401c397933ec5c4f7d89432a33509b6 `

<img width="1117" alt="Screenshot 2020-09-25 at 16 39 35" src="https://user-images.githubusercontent.com/1794099/94280455-b86df500-ff4d-11ea-94f6-532e2ff32ba8.png">

**Comment by roblourens** [comment]
The gear icon is fixed but the menu was apparently already an issue in stable

![Uploading image.png…]()

**Comment by roblourens** [comment]
@sbatten is there a way to move this on top of the table of contents, which has a z-index set, or should I try to move it to the right?

**Comment by jrieken** [comment]
doesn't reproduce anymore
