### ISSUE TITLE
system-wide installation and user-wide distribution

### ISSUE THREAD

**Issue by wenouyang** [microsoft/vscode#107479]
Hello, I was trying to install the Python extension, but I got the following message. What does that mean, and how to solve it? Thanks.

![image](https://user-images.githubusercontent.com/5430158/94316683-755e5280-ff4a-11ea-8e78-ea89cb1341b7.png)

**Comment by joaomoreno** [comment]
Open Control Panel. VS Code will appear twice. Simply uninstall one of them.
