### ISSUE TITLE
GitHub Authorization web page is referring to the no longer existing status bar item

### ISSUE THREAD

**Issue by yairEO** [microsoft/vscode#107495]
Same as #96350 (which the annoying bot closed).

## Browser 
![image](https://user-images.githubusercontent.com/845031/94336288-4a274200-ffe2-11ea-836e-05f5adcafadf.png)

## Code - Insiders
![image](https://user-images.githubusercontent.com/845031/94336271-11876880-ffe2-11ea-8db1-206e4e927145.png)

**Comment by kieferrm** [comment]
GH maintains this server for us. I forwarded the issue to them. Thanks for reporting!
