### ISSUE TITLE
Case change in a file name is not reflected in Copy Path

### ISSUE THREAD

**Issue by htwyford** [microsoft/vscode#107446]
Issue Type: <b>Bug</b>

STR:
1. Create a new file, e.g. `testfile.js`.
2. Right click the new file in the Explorer sidebar and change the case of the file name, e.g. to `testFile.js`.
3. Right click the file's tab and select Copy Path or Copy Relative Path.

Expected results:
`~/.../testFile.js` is copied to the clipboard.

Actual results:
`~/.../testfile.js` is copied to the clipboard.

Notes:
- Right clicking the renamed file in the Explorer sidebar and selecting Copy Path/Copy Relative Path copies the correct filename, e.g. `testFile.js`
- Non-case filename changes are reflected in Copy Path/Copy Relative Path. If you change `testfile.js` to `testFile.js` then to `testFile2.js` and then select Copy Path/Copy Relative Path from the file's tab, `~/.../testfile2.js` is copied to the clipboard.
- Closing the file's tab then reopening it does not fix the issue. Neither does closing the entire VS Code window. Neither does quitting VS Code (e.g. Cmd+Q on macOS).

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|32.00GB (5.51GB free)|
|Process Argv|-psn_0_25335848 --crash-reporter-id 734dc7e4-ac54-4b30-b45e-1f8fffc27504|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.7.1
vscode-firefox-debug|fir|2.9.1
restructuredtext|lex|129.0.0
prettify-json|moh|0.0.3
hg|mrc|1.7.1
python|ms-|2020.9.111407
cpptools|ms-|1.0.1
idl|myt|0.3.1
autotrim|Nat|1.0.6
fluent-syntax-highlighting|pau|0.0.1
rust|rus|0.7.8
vscode-todo-highlight|way|1.0.4
material-theme|zhu|3.8.7

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
@bpasero what is the famous bug where we do not handle casing correct in the workbench? I need to bookmark it

**Comment by bpasero** [comment]
This is unrelated to https://github.com/microsoft/vscode/issues/12448 if you mean it but the fix for https://github.com/microsoft/vscode/issues/12448 is the consequence of this. I will see if I can fix it.

**Comment by isidorn** [comment]
Thanks
