### ISSUE TITLE
Open in command prompt opens console with lowercase Drive Letter on Windows

### ISSUE THREAD

**Issue by johnzielke** [Microsoft/vscode#10743]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Press Ctrl + Shift + C
2. The new Command Prompt now has a cwd that starts with "**c**:\...." instead of "**C**:\" as when opening the command prompt from e.g. the explorer

This results in problems with webpack ( "There is another module with an equal name when case is ignored.") as the paths to the modules are inconsistent.

Although i don't use it, this issue seems to be the same with the integrated terminal.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/9448
