### ISSUE TITLE
Source Control Repository View

### ISSUE THREAD

**Issue by kh0m** [microsoft/vscode#107473]
Issue Type: <b>Feature Request</b>

In the Source Control Repositories View, under 'source control repositories', the branch name has higher priority than the repo name when the panel is collapsed to be of narrow width.

The use of that panel is to be able to toggle which repos' changes you see in the 'source control' portion..

When using long branch names then you cannot see at all which repo you are clicking on.. Can we put a min width on that so that we can see both the repo and the branch? and if only one then preferably the repo?

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 19.5.0

**Comment by gjsjohnmurray** [comment]
/duplicate see https://github.com/microsoft/vscode/issues/106406#issuecomment-692079449 which is already in Insiders so will arrive next month.
