### ISSUE TITLE
Function Definition jump not working

### ISSUE THREAD

**Issue by Shivani3094** [microsoft/vscode#107478]
Issue Type: <b>Bug</b>

Unable to navigate between functions. Function jump is not working.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (5.07GB free)|
|Process Argv|--crash-reporter-id 823082ff-f975-486e-95f9-dfa8021c0e59|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.9.111407
cpptools|ms-|1.0.1

</details>

**Comment by mjbvz** [comment]
Please provide steps to reproduce the issue

/needsMoreInfo

**Comment by mjbvz** [comment]
Closing as there is not enough information to investigate this
