### ISSUE TITLE
Opening another vscode window from the console of the second one produces CreateFile error

### ISSUE THREAD

**Issue by artaommahe** [microsoft/vscode#107496]
- VSCode Version: 1.49.2
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. open any folder in vscode
2. open any other folder in the new vscode window
3. open third folder from the terminal of the second window (e.g. `code ../smth`)
4. see an error in the terminal of the second vscode window

```
PS D:\projects\skyeng\skyeng-frontend\libs\shared\widgets> code ..\api\
[0926/115205.296:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
```

(though third window opens well)

Does this issue occur when all extensions are disabled?: Yes

Can be related somehow to this one already fixed https://github.com/microsoft/vscode/issues/105191

**Comment by gregvanl** [comment]
I see this as well for both Stable and Insiders

**Comment by rzhao271** [comment]
@artaommahe @gregvanl I can't reproduce this issue on the latest Insiders.

I'm wondering if it still shows up for either of you two after updating?

**Comment by artaommahe** [comment]
1.50.1 still have this error
```
PS D:\projects\skyeng\skyeng-frontend\libs\vimbox\blocks> code ..\layout\
[1105/230042.193:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
```

**Comment by Tyriar** [comment]
Passing to @deepak1556 as that looks like a Chromium log/source file.

**Comment by deepak1556** [comment]
Yeah this is a log from crashpad component, it can be ignored. Do you see the log when you run with `code.cmd` wrapper ?

**Comment by artaommahe** [comment]
what is `code.cmd wrapper`? regular vs code install, win10, running code with the command above (fisrt vs code instance is open via shortcut)

**Comment by ninmonkey** [comment]
I don't have insiders.I still get the error

    ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)

## to reproduce

![image](https://user-images.githubusercontent.com/3892031/98701681-2d9b5b00-233f-11eb-9ffb-c4356b7b3a56.png)

1. **right click a folder** -> open in VS Code (regular workspaces does not have an issue)
2. run these:

```powershell
$file = Get-ChildItem .. -File | select-Object -First 1
$file.Name
code $file

# or this
Get-ChildItem $filename | code -

# or this
$file = Get-ChildItem 'foo-bar' 
code $file

# or this
code './foo.json'
```

## Potentially related Extension

-  My shell is `pwsh` and I have the extension enabled `ms-vscode.powershell-preview@2020.9.0`

## version info

<details><summary>Environment (Click to Expand)</summary>

```powershell
🐒> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```


Environment Information
=====

Visual Studio Code
-----

| Name | Version |
| --- | --- |
| Operating System | Windows_NT x64 10.0.19041 |
| VSCode | 1.50.1|
| PowerShell Extension Version | 2020.9.0 |

PowerShell Information
-----

|Name|Value|
|---|---|
|PSVersion|7.0.3|
|PSEdition|Core|
|GitCommitId|7.0.3|
|OS|Microsoft Windows 10.0.19041|
|Platform|Win32NT|
|PSCompatibleVersions|1.0 2.0 3.0 4.0 5.0 5.1.10032.0 6.0.0 6.1.0 6.2.0 7.0.3|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|
|WSManStackVersion|3.0|
</details>


Visual Studio Code Extensions
-----

<details><summary>Visual Studio Code Extensions(Click to Expand)</summary>


|Extension|Author|Version|
|---|---|---|
|better-toml|bungcip|0.3.2|
|code-point|medo64|1.7.1|
|cpptools|ms-vscode|1.1.0|
|csharp|ms-dotnettools|1.23.5|
|debug|webfreak|0.25.0|
|font-switcher|evan-buss|3.1.0|
|githistory|donjayamanne|0.6.13|
|github-vscode-theme|GitHub|1.1.5|
|gitlens|eamodio|10.2.3|
|hexeditor|ms-vscode|1.3.0|
|markdown-all-in-one|yzhang|3.3.0|
|material-icon-theme|PKief|4.4.0|
|material-theme|zhuangtongfa|3.9.3|
|mssql|ms-mssql|1.9.0|
|mypy|matangover|0.1.4|
|nord-visual-studio-code|arcticicestudio|0.15.0|
|path-intellisense|christian-kohler|2.3.0|
|powershell-preview|ms-vscode|2020.9.0|
|prettier-vscode|esbenp|5.7.1|
|python|ms-python|2020.10.332292344|
|rainbow-csv|mechatroner|1.7.1|
|regexp-preview|LouisWT|0.1.5|
|remote-wsl|ms-vscode-remote|0.50.1|
|rust|rust-lang|0.7.8|
|tsl-problem-matcher|eamodio|0.3.1|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vsc-material-theme|Equinusocio|33.0.0|
|vsc-material-theme-icons|equinusocio|1.2.0|
|vscode-data-preview|RandomFractalsInc|2.2.0|
|vscode-duotone-dark|sallar|0.3.3|
|vscode-json-transform|octref|0.1.2|
|vscode-lldb|vadimcn|1.6.0|
|vscode-odata|stansw|0.1.0|
|vscode-powerquery|PowerQuery|0.1.5|
|vscode-pull-request-github|GitHub|0.21.0|
|vscode-pylance|ms-python|2020.11.0|
|vscode-theme-hydra|juanmnl|3.1.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vscode-xml|redhat|0.13.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|

**Comment by deepak1556** [comment]
I am unable to repro this with the steps outlined in latest stable with both system and user installed version.

**Comment by artaommahe** [comment]
@deepak1556 but it's still here. Recorded a video

https://i.imgur.com/nMgEJqJ.gif

```
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by deepak1556** [comment]
Thanks for the screenshot

I was able to repro it same as https://github.com/microsoft/vscode/issues/109782#issuecomment-720083009, the log is harmless, please ignore it. Is it affecting the behavior for you in anyway ?

**Comment by artaommahe** [comment]
nope, just strange error in console
