### ISSUE TITLE
Text editor adds spaces in front of quotes in html files

### ISSUE THREAD

**Issue by KPTousey** [microsoft/vscode#107441]
- VSCode Version:  1.49
- OS Version:  windows 8.1

Steps to Reproduce:

1.  create html using emmet
2.  create css
3. use beautify to format 
4. save
5. close vscode
6. reopen vscode
7. make edits in both html and css
9. reformat
10. save (starts adding spaces **before** quotes in multiple locations, most noticeably in id/class specifications)

Does this issue occur when all extensions are disabled?: Yes/No - - yes

**Comment by aeschli** [comment]
Can you add a sample code that shows that? Do you have format on save enabled?

Do you have an other formatter installed as well? I checked that beautify does not add spaced before `=`

**Comment by KPTousey** [comment]
Sorry, I do not have the VS Code editor installed any longer, and did not
take screenshots;  the automated spaces were added before the quotes ( " ),
and not the equal sign.
The HTML files that I was editing had to be opened in the brackets editor
in order to remove the spaces permanently; otherwise, they returned
whenever I saved changes.
Beautify was the only formatter that I had intentionally installed for that
purpose.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by aeschli** [comment]
Ah, then it's an issue with the Beautify extension. Please file the issue there.

**Comment by KPTousey** [comment]
Thanks Martin; issue was forwarded to the beautify team.
-Kevin Tousey


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
