### ISSUE TITLE
Extensions doesn't load in vscode when installed from snap on Ubuntu 20.04

### ISSUE THREAD

**Issue by arthurvaverko-kaltura** [microsoft/vscode#107490]
- VSCode Version: 1.49.2
- OS Version: Ubuntu 20.4

Steps to Reproduce:

1.install from apt 
2.open vscode and browse to extensions tab
3. extensions tab is not loaded and appears empty

I have read this https://github.com/microsoft/vscode/issues/98972
but i have no http_proxy or https_proxy env defined..

**Comment by arthurvaverko-kaltura** [comment]
also i just found that everything works well if I run vscode with sudo like this

sudo code --user-data-dir ~/

**Comment by arthurvaverko-kaltura** [comment]
now i see that also launching code from terminal is working by just typing code

**Comment by kieferrm** [comment]
@arthurvaverko-kaltura  how did you launch before? Using the GUI?

**Comment by arthurvaverko-kaltura** [comment]
> @arthurvaverko-kaltura how did you launch before? Using the GUI?

yup .. from the app launcher after apt installing it ..

**Comment by sandy081** [comment]
Please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by arthurvaverko-kaltura** [comment]
I cannot reproduce this anymore :\

**Comment by sandy081** [comment]
Closing this as user can't repro it anymore.
