### ISSUE TITLE
IntelliSense TypeScript show default values of optional arguments.

### ISSUE THREAD

**Issue by infacto** [microsoft/vscode#107579]
I ❤️ VS Code, IntelliSense and TypeScript. But I have a proposal to improve the info box. Currently a method is displayed like that (on mouse hover):
![demo](https://user-images.githubusercontent.com/60390085/94427075-d24a4a80-018e-11eb-84fb-d70b26b12964.png)

Is it possible to display the default values, not only the information of "optional". In this informations I guess `two` is like `three` just defined like `two?: string` and not `two = 'hello'`. For that I sometimes write the default value in the doc comment for that param. But this is redundant and inconsistent.

It should display the defined default value. Inline or better in a separate segment? Because more complex values may hard to read. 
Maybe in a list below that line. But I'm sure you have better ideas for that.

Also display the nullable return type of a method / function, if set. Like:

```ts
myMethod(): number | undefined {/*...*/}
```

Is currently displayed in as `myMethod(): number` only. In non-strict mode. In strict mode it works. But I also want to see it in non-strict mode. But maybe this should be splitted in another issue. This is issue is about display default values.

Maybe a TypeScript (not VS Code) issue?

**Comment by mjbvz** [comment]
Thanks. This is tracked upstream by https://github.com/microsoft/TypeScript/issues/16665
