### ISSUE TITLE
workon command giving not recognised 

### ISSUE THREAD

**Issue by jarvis-error** [microsoft/vscode#107515]
Issue Type: <b>Feature Request</b>

error : workon command not recognised as internal or external command

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363

**Comment by jarvis-error** [comment]
No only the workon command, and venv environment dissappears on clicking
python extension.so everytime I have to reload developer window. May I know
the issue

Thank you
Shreenidhi

**Comment by kieferrm** [comment]
\extPython
