### ISSUE TITLE
Test: code action resolve specification in LSP

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#107586]
Refs: https://github.com/microsoft/language-server-protocol/issues/787

- [x] anyOS @jrieken 
- [x] anyOS @aeschli 

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23107586%0A%0A)

---

Please review the specification part here https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_codeAction and here

**Comment by aeschli** [comment]
I fixed some typos in https://github.com/microsoft/language-server-protocol/pull/1100

**Comment by aeschli** [comment]
The following sentence could be improved:
` This is usally used to compute
the `edit` property of a code action to avoid its unnecessary computation during the `textDocument/codeAction` request.`

...avoid its unnecessary computation ...

It's not that it's **unnecessary** (not for the proposal that is selected) but to delay the computation if the computation is expensive

**Comment by dbaeumer** [comment]
Done. See https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_codeAction
