### ISSUE TITLE
shell tasks are run in non-login shell when shellArgs is "-l" vs. "--login"

### ISSUE THREAD

**Issue by cdwilson** [microsoft/vscode#107563]
- VSCode Version: 1.49.2
- OS Version: macOS Catalina 10.15.7 (19H2)

Steps to Reproduce:

Here's a `tasks.json` to use when reproducing this issue:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "Check if login shell",
			"command": "shopt -q login_shell && echo 'Login shell' || echo 'Not login shell'",
			"group": "build"
		}
	]
}
```

**Incorrect behavior:** The following `settings.json` incorrectly runs shell tasks in a non-login shell (it should be run in a login shell):

```
    "terminal.integrated.shell.osx": "/usr/local/bin/bash",
    "terminal.integrated.shellArgs.osx": [
        "-l"
    ],
```

Here's the output when running the task above:

```
> Executing task: shopt -q login_shell && echo 'Login shell' || echo 'Not login shell' <

Not login shell

Terminal will be reused by tasks, press any key to close it.
```

**Correct behavior:** Changing `-l` to `--login` causes shell tasks to be run in a login shell:

```
    "terminal.integrated.shell.osx": "/usr/local/bin/bash",
    "terminal.integrated.shellArgs.osx": [
        "--login"
    ],
```

Here's the output when running the same task above:

```
> Executing task: shopt -q login_shell && echo 'Login shell' || echo 'Not login shell' <

Login shell

Terminal will be reused by tasks, press any key to close it.
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
This does not reproduce with Linux. @Tyriar do you have a Mac you could try this on?

**Comment by Tyriar** [comment]
@alexr00 I can repro, I set the shell to `/bin/bash` as that exists on my machine but I see `-l` isn't being passed to the shell:

<img width="752" alt="Screen Shot 2020-11-05 at 8 00 39 AM" src="https://user-images.githubusercontent.com/2193314/98264720-0dcdf680-1f3d-11eb-99b2-e722b45369bb.png">

**Comment by alexr00** [comment]
@Tyriar thank you! This is interesting, tasks is deliberately removing it:

https://github.com/microsoft/vscode/blob/9dd69b3a2cc0eed8250d238eb5a1d3527c133cee/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1021-L1026

**Comment by alexr00** [comment]
Oh I see why we do that. Looks like the integrated terminal has that as a default on mac:

https://github.com/microsoft/vscode/blob/7210c7246ab3dd56492d5956ca4158a408e1f0b0/src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts#L50-L60

**Comment by Tyriar** [comment]
This may be to avoid double sourcing the profile script which can screw things up like shuffle `$PATH` around which is probably the reason for this. I see there isn't much info on the commit that changed it https://github.com/microsoft/vscode/commit/46c5c742e5b83c03a571c64aa69a01d7164fd5db, but that's probably the reason. It's a bit weird that `--login` behaves differently to `-l` as called out by the OP.

I'd recommend reading https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed if you haven't yet which details the ugly problem we face and why `-l` is the default on mac.

**Comment by alexr00** [comment]
I added a check to see if the `-l` was set in some settings. If it is, we keep it. This is consistent with how `shellArgs` work on other platforms.
