### ISSUE TITLE
Bring back unused variable highlight in JavaScript

### ISSUE THREAD

**Issue by saharso** [Microsoft/vscode#10755]
When I first started using vs code, There used to be a very useful green highlighting for variables that were declared, but not used throughout the code. This was very helpful with keeping my code clean and tidy. For some reason this feature was removed a few months ago. I can't see why. Please bring it back.

Sahar Soffer.

**Comment by alexandrudima** [comment]
fyi @dbaeumer

**Comment by dbaeumer** [comment]
@waderyan this is something the tsserver has to implement.
@saharso you can use a linter plugin (like eslint) to get that feature.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10503
