### ISSUE TITLE
Context menu doesn't work with a Touchscreen

### ISSUE THREAD

**Issue by MegMM** [microsoft/vscode#107516]
Recommended priority: Low to Medium priority. 
                                       More and more laptops and computer screens are becoming touchscreens

- VSCode Version: 1.49.2
- OS Version: Windows 10 (19041.508), patch 2004

Steps to Reproduce:
Hardware setup: HP Zbook Studio x360, flipped over like an easel (like an 'A')+ HP Touchscreen Pen. 
This is a Touchscreen laptop. My laptop is not set to Tablet Mode.

1. Open VS Code
2. Open a folder or workspace (doesn't matter which).
3. Choose a folder. 

Case 1 with pen:
`    `4. You can select a file or hover over the desired file in the Explorer side-window (sub-window?).  Doesn't seem to matter on the user-side.
`    `5. Push and hold pen over desired file.
Result: Nothing happens.

Case 2, with finger: 
`    `Repeat Steps 4 & 5 using a finger instead of the pen on the touchscreen. 
Result: Same, nothing happens.

Case 3, with mouse/touchpad:
`    `Repeat Step 4 & 5 with a mouse or the Touchpad instead of pen.
Result: Both work and bring up the context menu in the Explorer side-menu

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@bpasero should the context menu via touch just work? Asking because I think you have a touch machine?

**Comment by bpasero** [comment]
@isidorn I don't have a touch laptop, I got the same MacBookPro as you. I think Dirk or Alex might have a Surface with touch. There is a few issues with this label open already https://github.com/microsoft/vscode/labels/touch%2Fpointer but I think we never really officially announced that we do support touch at all.

**Comment by isidorn** [comment]
Thanks. Then let's treat this as a feature request and assign to backlog.

**Comment by bpasero** [comment]
//cc @sbatten

**Comment by MegMM** [comment]
a) Thanks for adding it as an rfe. I have the same issue on my SurfaceGo (touchscreen). Many laptops and even desktop screens are touchscreen-capable these days. In addition, due to arthritis, I often have a hard time using a mouse, so it's also an adaptability issue for me.
 
b) If an option to bring up the context-menu won't be done for a while, is there a keyboard shortcut? I can't find info on that.

**Comment by sbatten** [comment]
@MegMM `Shift+F10` is the default shortcut for opening context menus on focused elements.
