### ISSUE TITLE
Typoescript server crashing after installing current eslint in a sapper project

### ISSUE THREAD

**Issue by jhohlfeld** [microsoft/vscode#107512]
Issue Type: <b>Bug</b>

in a sapper project, after installing eslint, vscode keeps reporting typescript server crashes

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (1.18GB free)|
|Process Argv|--crash-reporter-id 1b657749-1c6c-4de5-b248-b1a37f87ee80|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
jsx|Twe|0.0.1
svelte-intellisense|ard|0.7.1
vscode-eslint|dba|2.1.8
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.1
flow-for-vscode|flo|1.5.0
csharp|ms-|1.23.2
svelte-autoimport|piv|1.0.4
java|red|0.67.0
svelte-vscode|sve|102.0.0
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2

</details>

**Comment by mjbvz** [comment]
Can you please a steps-by-step guide to reproduce this issue
