### ISSUE TITLE
Unformatted the HTML Code in React application while saving the application

### ISSUE THREAD

**Issue by MuhammadJeelan123** [microsoft/vscode#107546]
I am running a react application  using visual studio IDE .
In index.js , I have made simple code changes and trying to saving the file but while saving the index.js ,the code became unformatted  the html tags(which is alter the html tags) and throwing error in IDE which causes to error in browser

**Before Save**
```
function App() {
    return ( 
        <div className = "App" >
        <h1> Hello </h1> </div>
    );
}
```
export default App;

**While Try Save:**
```
function App() {
    return ( **<
        div className = "App" >
        <
        h1 > Hello < /h1> </div >**
    );
}

export default App;
```

**Comment by JW9506** [comment]
Configure `editor.defaultFormatter`.

**Comment by MuhammadJeelan123** [comment]
Thanks to everyone. Issue has been resolved
