### ISSUE TITLE
Rename Symbol only works in open files

### ISSUE THREAD

**Issue by fernandobelotto** [microsoft/vscode#107562]
- VSCode Version: 1.49.2
- OS Version: Windows_NT x64 10.0.19041

I think i found an bug in the behaviour of the Rename Symbol function in VSCode. When i tried to Rename Symbol in a functional component in a react project, only the ocurrencies with file open get changed. If the file is not open, the component ocurrencie dont get renamed. I made a simple video showing this behaviour

https://youtu.be/HrmmLQdCqvk

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Try adding a [jsconfig](https://code.visualstudio.com/docs/languages/jsconfig) to your workspace so that all JS files in it are treated as a single project
