### ISSUE TITLE
Extension API to provide a handler for updating imports on file move for other languages

### ISSUE THREAD

**Issue by mickdekkers** [microsoft/vscode#107500]
VS Code has a [feature](https://code.visualstudio.com/updates/v1_24#_update-import-paths-when-a-file-is-moved-or-renamed) that offers to update imports when a JavaScript or TypeScript file has been moved or renamed.
![ts-update-imports](https://user-images.githubusercontent.com/5085260/94340488-6d61e980-0002-11eb-8873-7be1703b8d0f.gif)

It would be great if this feature was available for more languages. I suggest opening this feature up to extensions so that any language extension can provide this functionality for their respective language.

**Comment by mjbvz** [comment]
The built-in JS/TS extension is not using any special apis, just the [standard `onDidRenameFiles` event](https://github.com/microsoft/vscode/blob/1fd7ee15d3a2c50547228b08cefc7c13a5a739d2/src/vs/vscode.d.ts#L10131)
