### ISSUE TITLE
Backspace problem in android browser

### ISSUE THREAD

**Issue by Deshdeepak1** [microsoft/vscode#107524]
- VSCode Version: 3.5.0
- OS Version:9

Steps to Reproduce:

1. Use vscode in android browser.
2. Press Backspace in editor.
 Backspace doesn't work.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by bpasero** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/107524 ?

**Comment by thatsed** [comment]
**Workaround**: in settings, set `keyboard.dispatch` to `keyCode`.

Events generated by the Android soft keyboard seem to have the correct `keyCode` attribute, while having some issues with the `code` attribute (which is the one VSCode uses by default). You can cross check with a working browser at https://keycode.info/

I suspect this is more an Android issue than a vscode one.
