### ISSUE TITLE
"Open file in editor" from terminal opens a new split, instead of changing focus to a different one

### ISSUE THREAD

**Issue by BRevzin** [microsoft/vscode#107509]
- VSCode Version: 1.49.2
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Have multiple "splits" (I think this is what VS Code calls them, like different files open at the same time. Basically different tabs)
2. Have some file `left.cpp` open on the left split and `right.cpp` open on the right split.
3. In the terminal, run `echo "left.cpp:4"` (some string that VS Code recognizes as a path to a file that it allows you to control-click to open file in editor)
4. With focus on `right.cpp`, ctrl-click on that link. 

The result is that we open a _new_ tab in the right split to refer to `left.cpp`. Even though `left.cpp` is already open and visible in the left split. 

This is mildly annoying, and would be much nicer if the editor first checked if `left.cpp` was visible in any of the splits -- and if it was, navigate in that split (regardless of which split currently has focus).

I wouldn't call this a _bug_ per se, since `left.cpp` does successfully get opened. More of a improvement request. 

Does this issue occur when all extensions are disabled?: When I tried to check this:

```
$ code --disable-extensions .
Ignoring option disable-extensions: not supported for code.
```

**Comment by Tyriar** [comment]
I think this is by design since you can open a file in multiple panes and the right one was focused.

**Comment by BRevzin** [comment]
> I think this is by design since you can open a file in multiple panes and the right one was focused.

Would it be possible to at least get a configuration option to get the different behavior? This may be by design but it is a design I find fairly annoying -- it is never the behavior I want and always results in momentary confusion.

**Comment by bpasero** [comment]
We have a setting.

**Comment by BRevzin** [comment]
> We have a setting.

Could you tell me what that setting is?
