### ISSUE TITLE
Move VC Actions to the left.

### ISSUE THREAD

**Issue by mrillusi0n** [microsoft/vscode#107589]
![image](https://user-images.githubusercontent.com/37063502/94439841-8adbb280-01be-11eb-8dd0-e3a787418550.png)
I'd have to move less of my mouse were the Stage, Discard, Next and Prev Change buttons closer to where I clicked to get those actions.

**Comment by bpasero** [comment]
Sounds like the actions in the embedded editor for dirty diff.

**Comment by joaomoreno** [comment]
Closing per https://github.com/microsoft/vscode/issues/98523
