### ISSUE TITLE
VSCODE at full screen - no way to exit without rebooting

### ISSUE THREAD

**Issue by dzittin** [microsoft/vscode#107549]
Issue Type: <b>Bug</b>

I don't know what I did to cause this, but VSCODE was in full screen with no way to reduce the window size or access the toolbar (win10). 
....later...I thought I would have to reboot, but opening "similar issues" got me out to a functioning win system so I am likely going to have to kill the VSCODE process and restart.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.46GB free)|
|Process Argv|--crash-reporter-id 1e631a67-5a9d-4e6c-9cde-ec8da5bb4b20|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.0
vsc-python-indent|Kev|1.11.0
python|ms-|2020.9.111407
sublime-keybindings|ms-|4.0.7

</details>

**Comment by gjsjohnmurray** [comment]
#107527 may be relevant

**Comment by rzhao271** [comment]
@dzittin did you press F11 (toggle fullscreen)? If so, does pressing F11 again bring you out of that mode?
