### ISSUE TITLE
Allow goToSymbol via copy pasted path

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#107547]
I am deeply sorry for creating a duplicate, but I don't feel like my feature request was well understood.
I think it should be reopened https://github.com/microsoft/vscode/issues/96651

The point is that it's not possible to copy/paste an otherwise working goToSymbol path. It must by typed in sequence.

![vscode-goToSymbol-1](https://user-images.githubusercontent.com/2313018/94370095-189b9d00-00ee-11eb-8f7f-3d09c0a0397d.gif)

![vscode-goToSymbol-2](https://user-images.githubusercontent.com/2313018/94370093-18030680-00ee-11eb-8fca-17829fca5ef7.gif)

**Comment by mjbvz** [comment]
@bpasero Steps to reproduce:

1. In the VS Code codebase, copy the text `codeaction@refactor` then paste it into the command palette
     - No results.
1. Type out the same
     - See results

**Comment by bpasero** [comment]
Yeah, I think this was never working, but fair request.

**Comment by bpasero** [comment]
Will not do this due to https://github.com/microsoft/vscode/issues/93845

**Comment by ackvf** [comment]
It's sad, but understandable.
