### ISSUE TITLE
Debugger should allow for a timeout when debugger inside container 

### ISSUE THREAD

**Issue by joao-p-marques** [microsoft/vscode#107587]
- VSCode Version: 1.49.2
- OS Version: Linux x64 5.4.0-7642-generic

Steps to Reproduce:

1. Setup a `launch` debugging _configuration_ or _compound_ where the `preLaunchTask` involves starting a Docker container in detached mode (like `docker compose up -d`)
2. Launch the debugging session
3. Observe the debugging session fail, not be launched or produce errors (like breakpoints not being mapped correctly)
4. Launch the session again and works normally.

This is probably happening because the debugging session is started before the containers spin up. 

It should be possible to define a task timeout so that we can wait for the containers to start.

Does this issue occur when all extensions are disabled?: No (Extensions are necessary to debug, like the Python one)

**Comment by weinand** [comment]
Some debuggers support to increase the connection timeout, e.g. node-debug.
Please try that (or if your debug extension doesn't support "timeout" file an issue against the extension).

**Comment by Yajo** [comment]
@joao-p-marques please reopen into https://github.com/microsoft/vscode-python
