### ISSUE TITLE
Orphaned tab groups after restarting or reloading

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#107554]
Issue Type: <b>Bug</b>

Some special tabs leave orphaned tab groups behind when restarting (or reloading) the application.

![Reload Bug](https://user-images.githubusercontent.com/484784/94372545-78288700-00b3-11eb-9674-a168c9f38d2d.gif)

After opening VSCode a noticing an empty tab group like this you have to invoke a command that moves tabs to get it back into a normal state.

The following tabs exhibit this behavior
* Default Settings JSON
* Default Keybard Shortcuts JSON
* Release Notes
* Extension pages

These do not
* Settings UI
* Keyboard Shortcuts UI
* Interactive Playground

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041

**Comment by bpasero** [comment]
This is "as designed", not all editors have opted in to restoring their content. If there is one particular editor you want to see restored, please file individual issues and then owners can triage this accordingly.

**Comment by akbyrd** [comment]
> If there is one particular editor you want to see restored

How about these guys?

> The following tabs exhibit this behavior
> * Default Settings JSON
> * Default Keybard Shortcuts JSON
> * Release Notes
> * Extension pagess

**Comment by bpasero** [comment]
As I said, please report as individual issues as they are different editors.
