### ISSUE TITLE
Test: Improved ESLint security flow

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#107584]
Refs: https://github.com/microsoft/vscode-eslint/issues/1012

- [x] anyOS @kieferrm 
- [x] anyOS @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23107584%0A%0A)

---

The flow of the ESLint execution confirmation dialog has been improved. Major changes are:

- no modal dialog on startup anymore
- An `Allow Everywhere` button.

To test please reset all former library decision you have made using the `ESLint: Reset Library Decisions` command. In addition you need to install the latest insider build from here: https://github.com/microsoft/vscode-eslint/releases/tag/2.1.9-insider

Please ensure that the following holds true:

- when opening a workspace folder that has not been approved or denied yet a red ESLINT status icon is shown with a blocked sign. No modal dialog is shown. In addition when opening a file that should be validated using ESLint the file will have an special error attached to its first word indicating that ESLint is missing an execution confirmation. Ensure that such an error is only shown for the active editor and only if that file would be validated using ESLint (please note that the error might show up on markdown files since ESLint can validate markdown).
- clicking on the status icon will open the modal dialog. Ensure that the description and the buttons make sense.
- test the various buttons and make sure that an appropriate button is shown. To reset a last made decision use the `ESLint: Reset Library Decisions` command
- if the execution is approved for a specific library (not Allow Everywhere) the ESLint status icon should only be visible when the active editor contains a document that is validated using ESLint.

**Comment by alexr00** [comment]
> when opening a workspace folder that has not been approved or denied yet a red ESLINT status icon is shown with a blocked sign. 

I do not see this icon:

![image](https://user-images.githubusercontent.com/38270282/94558462-2ffa9780-0260-11eb-8158-bd7295752de6.png)

**Comment by alexr00** [comment]
How is the Disable button different from the Cancel button?

![image](https://user-images.githubusercontent.com/38270282/94561045-c7151e80-0263-11eb-91bb-21f2f198d66a.png)

**Comment by dbaeumer** [comment]
Cancel cancel the dialog and leaves that state as it was before opening the dialog. So if you were in Allow cancel keeps you in allow. Like other dialogs as well.

**Comment by kieferrm** [comment]
Overall, this is a nice flow.
