### ISSUE TITLE
It looks like nothing happens when I press the "WSL: Install on Ubuntu-18.04" button on the extension golang.go

### ISSUE THREAD

**Issue by shimodatkh** [microsoft/vscode#107558]
procedure
1. Start Ubuntu 18.04 on WSL2
2. Connect with VS Code WSL extension
3. Click the "WSL: Install on Ubuntu-18.04" button on the extension golang.go

Expected result: The display changes to show success or failure or some result
Actual result: No change in display

**Comment by shimodatkh** [comment]
Sorry, just now I have translated.

**Comment by sandy081** [comment]
Do you see any errors any where else? Any prompts for eg?
Can you also open Output view in the bottom section and check for window and remote logs to see if there are any errors?

**Comment by shimodatkh** [comment]
Thank you for your reply

> Do you see any errors any where else? Any prompts for eg?
> Can you also open Output view in the bottom section and check for window and remote logs to see if there are any errors?

The error is not found on the VS Code GUI or in the logs under AppData / Roaming / Code.

The capture immediately after clicking the install button is below.
Nothing is displayed in the "Output view".

![SnapCrab_Extension Go - go  WSL Ubuntu-1804  - Visual Studio Code_2020-9-29_22-30-23_No-00](https://user-images.githubusercontent.com/11813560/94569442-af13be00-02a8-11eb-8299-07316a49a1be.png)

Is "remote logs" the logs under AppData / Roaming / Code? If so, it didn't contain the words error or golang.

```shell
$ pwd
/c/Users/me/AppData/Roaming/Code/logs/20200929T223251

$ ls -l
total 8
drwxr-xr-x 1 me 197121   0 Sep 29 22:32 exthost1
-rw-r--r-- 1 me 197121 202 Sep 29 22:33 main.log
drwxr-xr-x 1 me 197121   0 Sep 29 22:32 output_1_20200929T223252
-rw-r--r-- 1 me 197121   0 Sep 29 22:32 renderer1.log
-rw-r--r-- 1 me 197121 377 Sep 29 22:33 sharedprocess.log
-rw-r--r-- 1 me 197121 251 Sep 29 22:32 telemetry.log
-rw-r--r-- 1 me 197121 189 Sep 29 22:32 userDataSync.log

$ grep error * -rni

$ grep golang * -rni

$

```

The same is true for other extensions.
* mechatroner.rainbow-csv
* raynigon.nginx-formatter

version
* VSCode 1.49.2
* Windows 10 Home 2004 19041.508

**Comment by sandy081** [comment]
Logs will be available in Output view. Please open the dropdown and select `window` for window logs and `remote server` for remote logs. 

Please see if there are any errors there.

**Comment by shimodatkh** [comment]
I got it. I pressed the install button again and tried it, but neither window nor remote server logged anything.

window

![SnapCrab_Extension Go - go  WSL Ubuntu-1804  - Visual Studio Code_2020-9-29_23-25-38_No-00](https://user-images.githubusercontent.com/11813560/94572037-8a6d1580-02ab-11eb-8492-a35dcbca570d.png)

remote server

![SnapCrab_Extension Go - go  WSL Ubuntu-1804  - Visual Studio Code_2020-9-29_23-28-44_No-00](https://user-images.githubusercontent.com/11813560/94572075-922cba00-02ab-11eb-927d-4eaf90bba513.png)

**Comment by sandy081** [comment]
- Can you please enable log level to `trace` using the command `Developer: Set Log Level` and check the logs.
- Also check the logs in Developer tools console - Use command `Developer: Toggle Developer Tools`
