### ISSUE TITLE
Cannot click terminal selection using touch screen

### ISSUE THREAD

**Issue by happyme531** [microsoft/vscode#107542]
- VSCode Version:1.49.2
- OS Version:Windows 10.0.18363

Steps to Reproduce:

1.Create a terminal
2.Open the terminal selection menu
3.Touch the menu and find it not working

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment]
Works for me on the latest Insiders edition. 
Can you toggle screencast mode and then record a gif (e.g. with https://gifcap.dev/) showing the issue?
