### ISSUE TITLE
Python Interactive Window - environment selection disappeared

### ISSUE THREAD

**Issue by elvissey1984** [microsoft/vscode#107545]
- VSCode Version: 1.49.2
- OS Version: Windows 10 1909 (18363.1082)

Steps to Reproduce:

1. Open VS Code
2. Ctrl+Shift+P, and select "Create Python Interactive Window"
3. On the right pane, the environment selection bar flashes for one second and disappears

Does this issue occur when all extensions are disabled?: N/A - with extensions disabled I cannot create the interactive window

**Comment by rzhao271** [comment]
@elvissey1984 I tried to reproduce the issue. I don't see any environment selection bar. I just see a new editor open to the right that allows me to enter Python, though my VS Code says I have to install ipykernel for it to fully function.

My specs

Version: 1.51.0-insider (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-04T18:31:15.290Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Also, I wonder if this has more to do with the Python extension? You can try filing the same issue here https://github.com/microsoft/vscode-python
