### ISSUE TITLE
Vertical layout debug console (terminal) file path taking too much space

### ISSUE THREAD

**Issue by sebRomeo** [microsoft/vscode#107570]
- VSCode Version: 1.50.0
- OS Version: Linux Mint 20

Steps to Reproduce:

1. Launch debug mode with a script and put the layout vertical

Hi,
it's a bit frustrating that almost half of the vertical space in debug console is used to display the file name where the log originated. In addition, those informations are 100% inaccurate to me because it always point to the logger file and not the file where the error originated...

I'm working with a 1080p monitor, tried different zoom level and panel size but it's always the same problem as source location adapt to panel size.

See screen capture below:

![95859207-88508f80-0d5e-11eb-9dc7-5459e7422563](https://user-images.githubusercontent.com/17770809/96481103-6150fc80-123b-11eb-9d6d-b64561d49046.png)

**Comment by isidorn** [comment]
So you would like that there is a max width for the source location in the debug console.
I think this is a fair request which we might tackle in the future.

**Comment by isidorn** [comment]
This should be better now, thus closing
