### ISSUE TITLE
Please use XDG_RUNTIME_DIR for vscode-ipc sockets

### ISSUE THREAD

**Issue by alois31** [microsoft/vscode#107596]
- VSCode Version: 1.49.2
- OS Version: Linux x64 4.19.0-11-amd64

Steps to Reproduce:

1. not applicable

Does this issue occur when all extensions are disabled?: Not applicable, but may break extensions (see https://github.com/flathub/com.visualstudio.code-oss/issues/20 and https://github.com/flathub/com.visualstudio.code-oss/issues/20)

On non-Windows platforms, vscode currently uses ```os.tmpdir()``` indiscriminately when creating IPC sockets:
```javascript
export function generateRandomPipeName(): string {
	const randomSuffix = generateUuid();
	if (process.platform === 'win32') {
		return `\\\\.\\pipe\\vscode-ipc-${randomSuffix}-sock`;
	} else {
		// Mac/Unix: use socket file
		return join(tmpdir(), `vscode-ipc-${randomSuffix}.sock`);
	}
}
```

We should use ```XDG_RUNTIME_DIR``` if this is set, as the git extension already does:
```javascript
function getIPCHandlePath(id: string): string {
	if (process.platform === 'win32') {
		return `\\\\.\\pipe\\vscode-git-${id}-sock`;
	}

	if (process.env['XDG_RUNTIME_DIR']) {
		return path.join(process.env['XDG_RUNTIME_DIR'] as string, `vscode-git-${id}.sock`);
	}

	return path.join(os.tmpdir(), `vscode-git-${id}.sock`);
}
```

Rationale: citing from the XDG Base Directory Specification (https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables, emphasis mine):
> $XDG_RUNTIME_DIR defines the base directory relative to which user-specific non-essential runtime files and other file objects (**such as sockets**, named pipes, ...) should be stored.

**Comment by isidorn** [comment]
Based on blame I am forwarding this to @alexdima
