### ISSUE TITLE
Minor UI bug

### ISSUE THREAD

**Issue by capedghost** [microsoft/vscode#107502]
- VSCode Version: 1.49.1
- OS Version: Win10 2004 19041.508

Steps to Reproduce:

1. Turn off the Breadcrumbs of vscode.
2. Run some editor like extension, like Hex Editor.
3. There is a blank bar at the position of Breadcrumbs.
Like this:

With Breadcrumbs turned on:
![image](https://user-images.githubusercontent.com/44280081/94342016-be90ce00-0040-11eb-9cab-a12296804929.png)

After Breadcrumbs turned off:
![image](https://user-images.githubusercontent.com/44280081/94342050-ed0ea900-0040-11eb-9455-cf270e95c21b.png)
![image](https://user-images.githubusercontent.com/44280081/94342066-031c6980-0041-11eb-8aee-e2aa237bcfe2.png)

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
Does not reproduce for me. Can you try this with [VS Code Insiders](https://code.visualstudio.com/insiders/)?

**Comment by capedghost** [comment]
> Does not reproduce for me. Can you try this with [VS Code Insiders](https://code.visualstudio.com/insiders/)?

Oh, it's weird.
![S20200928160618](https://user-images.githubusercontent.com/44280081/94407728-64aa1880-01a6-11eb-9b3f-8098401aa75c.png)
![S20200928161532](https://user-images.githubusercontent.com/44280081/94407760-7390cb00-01a6-11eb-958a-7fce7557c177.png)
This is testing in virtual machine (Hyper-V). And all the screenshots in the issue is also in virtual machine.
*(Why the fonts getting bold?I haven't set it to bold)*
---
But, there is no problem in my real machine(is it called 'real machine'?)：
![S20200928161753](https://user-images.githubusercontent.com/44280081/94408951-14cc5100-01a8-11eb-87aa-4fb496f4cd3b.png)
