### ISSUE TITLE
Issue with slow

### ISSUE THREAD

**Issue by Niyask** [microsoft/vscode#107507]
Color code issue and color issue on the editor. Also,
![Capture](https://user-images.githubusercontent.com/5810367/94346898-68765780-004d-11eb-9fa3-e1e7ecfd0593.PNG)
 the code is very slow.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
