### ISSUE TITLE
Test: Smoke Tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107568]
- [x] Windows @dbaeumer
- [x] macOS @btholt
- [x] Linux @chrmarti
- [x] Web (Chromium, anyOS) @bpasero

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23107568%0A%0A)

---

**NOTE:** Desktop & Web tests MUST run with `--build` argument

**NOTE:** Desktop tests MUST run with `--stable-build` argument additionally

Documentation: https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md#run.

If the automated tests fail, create and issue for that and run the tests manually: https://github.com/microsoft/vscode/wiki/Smoke-Test

**Comment by chrmarti** [comment]
Also ran it on Mac to get early coverage. Saw #107688, everything else passed.

**Comment by bpasero** [comment]
@chrmarti thanks a lot!
