### ISSUE TITLE
plz add opencl support, thx!

### ISSUE THREAD

**Issue by hemmingway** [Microsoft/vscode#10757]
- VSCode Version:1.4.0
- OS Version:win 10

Steps to Reproduce:

1. plz add opencl support, thx!
2.

**Comment by aeschli** [comment]
@hemmingway Can you add some more specifics? Pointer to the OpenCL language spec? Is it about https://en.wikipedia.org/wiki/OpenCL? What would support for OpenCL mean?

**Comment by aeschli** [comment]
@hemmingway Need more information here. I'll close the issue for now, but will gladly reopen once I undertand the request
