### ISSUE TITLE
editor.hover [language] [mdn documentation

### ISSUE THREAD

**Issue by timoogo** [microsoft/vscode#107511]
Is it possible to add a feature to change the langugage of the hover of that ? [MDN documentation]
I'm asking that because it's redirecting us to the website already translated
<img width="491" alt="Capture d’écran 2020-09-26 à 20 40 04" src="https://user-images.githubusercontent.com/44207397/94347931-aae16980-0038-11eb-93af-b8e9b397d033.png">
thank you !

**Comment by aeschli** [comment]
It's the browser that does the redirect. Why not changing your primary language in the browser settings?

**Comment by timoogo** [comment]
It would be better that in visual studio, it changes (because, the rest of the app follow the langage rule

**Comment by imgustavo** [comment]
I want this option too! 😭
