### ISSUE TITLE
Control Exclude checkbox in search from extension

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#107588]
When executing search from extension api 2 checkboxes are not exposed:

- Preserve Case
- Use Exclude Settings and Ignore Files

```ts
vscode.commands.executeCommand('workbench.action.findInFiles', {
  query: regexStr,
  isRegex: true,
  triggerSearch: true,
});
```

![Screenshot (341)](https://user-images.githubusercontent.com/9638156/94437036-e6e60d00-01a5-11eb-931a-e76859e5aab5.png)

**Comment by Baibhab97** [comment]
Hi @roblourens , I would like to contribute. Can you guide me as to what exactly needs to be done?

**Comment by dhairyanadapara** [comment]
Hey @usernamehw , Can you please explain a little more about the issue?

**Comment by usernamehw** [comment]
@dhairyanadapara It's possible to trigger a search from extension by using this api:

```ts
vscode.commands.executeCommand('workbench.action.findInFiles', {
  query: 'example',
});
```

And it has good amount of options:

```ts
export interface IFindInFilesArgs {
	query?: string;
	replace?: string;
	triggerSearch?: boolean;
	filesToInclude?: string;
	filesToExclude?: string;
	isRegex?: boolean;
	isCaseSensitive?: boolean;
	matchWholeWord?: boolean;
}
```

But 2 of them are missing: 

1. `Preserve Case`
1. `Use Exclude Settings and Ignore Files`

**Comment by dhairyanadapara** [comment]
Thank @usernamehw, got the idea. I will raise a PR to fix the issue ASAP :)

**Comment by dhairyanadapara** [comment]
@usernamehw @roblourens  I have raised the [PR](https://github.com/microsoft/vscode/pull/107910). If you get time please review :)

**Comment by rotem-bar** [comment]
@roblourens genuinely didn't notice the existing PR, apologies @dhairyanadapara

**Comment by dhairyanadapara** [comment]
Thanks @roblourens :). No problem @rotem-bar.

**Comment by usernamehw** [comment]
It great now that it's possible to control it 👍 but why does it called `excludeSettingAndIgnoreFiles`? Would it possible to have the same name as in label:

```diff
- excludeSettingAndIgnoreFiles
+ useExcludeSettingsAndIgnoreFiles
```

**Comment by JacksonKearl** [comment]
Updated to `useExcludeSettingsAndIgnoreFiles` as per @usernamehw's suggestion and for consistency with search editor post #108750. Also added these to the keybindings intellisense registry.
