### ISSUE TITLE
CTRL to look for methods definitions not working properly

### ISSUE THREAD

**Issue by Lucas001** [Microsoft/vscode#10750]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:49:32.489Z)
- OS Version: Linux x64 4.2.0-42-generic

Steps to Reproduce:

1.Press CTRL
2.Click in any method definition that has more than one scopes

In my case, I have multiple Update methods in many different classes that are not inherited. When I press CTRL and see what is the definition of the method in a file ClassA.cpp, VS send me to ClassB.cpp Update definition. And they do not have the same scope.

**Comment by alexandrudima** [comment]
Moved to Microsoft/vscppsamples#160
