### ISSUE TITLE
Quick fix import not working

### ISSUE THREAD

**Issue by Alexzanderk** [microsoft/vscode#107572]
Issue Type: <b>Bug</b>

Nothing was changed only restarted the notebook. At the moment I have issue with quick fix import when you add some exported interface I don't have a quick-fix helper for adding interface import! 

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:09:08.021Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 8, 15|
|Memory (System)|8.00GB (0.22GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
gitstash|art|3.2.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
githistory|don|0.6.10
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.2
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.1
git-graph|mhu|1.26.0
vscode-docker|ms-|1.6.0
material-icon-theme|PKi|4.3.0
vscode-sass-format|sas|1.1.7
sass-indented|syl|1.8.11
vscodeintellicode|Vis|1.2.10
quokka-vscode|Wal|1.0.321
wallaby-vscode|Wal|1.0.244

(1 theme extensions excluded)

</details>

**Comment by Alexzanderk** [comment]
So it's real BUG I have added a mask in the tsconfig.json at the property include - and everything starts to work after I sometimes I removed and still works. I restart notebook - works!

**Comment by Alexzanderk** [comment]
it is not a solution because some exported classes don't catch by autocompleting and quick-fix

**Comment by mjbvz** [comment]
Please share steps to reproduce the problem.

/needsMoreInfo

**Comment by Alexzanderk** [comment]
@mjbvz Hi, here is the test repo for reproducing. https://github.com/Alexzanderk/vscode_contex_menu

**Comment by Alexzanderk** [comment]
![image](https://user-images.githubusercontent.com/16296369/94527588-e00bd880-023f-11eb-8da7-c80d0e3c94ba.png)
![image](https://user-images.githubusercontent.com/16296369/94527674-00d42e00-0240-11eb-880a-4dd0cc0f4512.png)
![image](https://user-images.githubusercontent.com/16296369/94527800-34af5380-0240-11eb-8dd0-350c0bdac9bd.png)
![image](https://user-images.githubusercontent.com/16296369/94527896-5ad4f380-0240-11eb-85eb-f13c88f0ab94.png)

**Comment by Alexzanderk** [comment]
@mjbvz any updates?

**Comment by mjbvz** [comment]
This is expect because you've defined separate projects: one for `test` that does not include `a` and one for `app` that does.
 
Either restructure your projects or use [project references](https://www.typescriptlang.org/docs/handbook/project-references.html)
