### ISSUE TITLE
Github signin fails and permanently breaks github functionality for private repos (Linux)

### ISSUE THREAD

**Issue by matt-codeslo** [microsoft/vscode#107510]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Do anything that triggers the browser-based github sign in. Sometimes this just fails, but you can replicate it by signing in to a github account that doesn't have access to the remote repository you want to use
2. Once the process fails or you sign in to a different account, you can no longer push or pull from any private repo. It does not matter what is in git.config. There does not seem to be any way to re-initialize the sign-in process.
3. This is the single worst feature of VS Code, which is otherwise an outstanding product.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by RMacfarlane** [comment]
Sorry I didn't respond to this months ago when I first read this, I was mad about this being called "the single worst feature of VS Code". You can sign out from an account using the accounts icon on the activity bar. Adding @joao to make sure the git extension listens for sign out and updates accordingly

**Comment by joaomoreno** [comment]
> 2\. There does not seem to be any way to re-initialize the sign-in process.

Have you tried `Sign Out`?
