### ISSUE TITLE
Please stop wasting my disk with multiples Android/Java stacks - Share one Docker image between IDEs

### ISSUE THREAD

**Issue by Joca63** [microsoft/vscode#107517]
For each IDE that is installed  on my machine I get another copy of Android stack, Visual Studio install one Android Stack, Android Studio install another Android Stack and so on for another ones each one with a different path. It would be wonderful if there is an official Google android SDK here on GitHub but Google keep the source locked inside they own git servers, would be great even a clone read-only here, Im thinking about put all the Android stack inside a Docker/VM image that would be shared for everyone, it can be even a shared image between Microsoft and Google , look at Eclipse Che project, there everything is a docker container.

**Comment by kieferrm** [comment]
Agreed

**Comment by kieferrm** [comment]
\extJava
