### ISSUE TITLE
The terminal process terminated with exit code: 3221225786

### ISSUE THREAD

**Issue by manolosolalinde** [microsoft/vscode#107501]
Issue Type: <b>Bug</b>

All of a sudden python terminal debugger stopped working. I'm getting an error with every shell.

Steps to reproduce:
1) Open any python file
2) Run debugger with F5

Error detail:

wsl: The terminal process "C:\WINDOWS\System32\wsl.exe" terminated with exit code: 3221225786.

powershell: The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" failed to launch (exit code: 3221225786).

All unnecesary extensions were disabled.

VS Code version: Code - Insiders 1.50.0-insider (ddc98c3f620ab1d2ecad5942ebf4736060403d67, 2020-09-25T05:35:02.163Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.92GB (2.10GB free)|
|Process Argv|--crash-reporter-id b3f75325-835d-42ed-8712-3cb202f9fd2a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
forward-slasher|for|0.1.0
python|ms-|2020.9.111407
rescuetime|Res|1.0.1
vscodeintellicode|Vis|1.2.10

</details>

**Comment by manolosolalinde** [comment]
I have been testing changes in my settings.json and also rebooting a few times. At a given time the debugger threw errors due to comments on my settings.json file, so I deleted them. By the third reboot the problem got solved. I have been trying to reproduce the error without success. My settings.json file is the same as it was initially (with comments) and now everything works. This is very confusing. Any idea of what could have been?

**Comment by manolosolalinde** [comment]
Error is back. Help!, this is very annoying. I am attaching a screenshot.

![vscode_error_f5_python](https://user-images.githubusercontent.com/34798311/94374728-41b33200-00dc-11eb-867a-67229148a4d3.jpg)

Please let me know how I can help.

**Comment by Tyriar** [comment]
Please follow https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch and let us know if you're still having issues.
