### ISSUE TITLE
introduce source.removeUnusedImport action as an opposite to source.addMissingImports

### ISSUE THREAD

**Issue by capaj** [microsoft/vscode#107535]
VScode already makes it seamless to work with imports-I almost never have to go and manually import anything. With one exception-removing them.
I would like to have a source action `source.removeUnusedImports` so that I can configure my `settings.json` like this:
```json
{
    "editor.codeActionsOnSave": [
        "source.removeUnusedImports"
    ]
}
```

Expected functionality would be that VScode would just run the source code action on save to remove all unused imports in my JS/TS file.

I know there is `source.organizeImports` already which removes unused imports, but I do not want that. In our codebase we prefer to keep order of imports in the order of addition.

**Comment by nrayburn-tech** [comment]
Similarly, I like to have the imports sorted.  I don't necessarily want the unused imports deleted though.

Maybe there should be a few different settings, or a different setting value.  Sorting, removing, or both.
