### ISSUE TITLE
VSCode UI becomes slow after a while used. Slow UI performance on TypeScript especially...

### ISSUE THREAD

**Issue by gencer** [microsoft/vscode#107560]
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.0-47-generic

Steps to Reproduce:

1. Open VSCode and connect to the WSL or SSH Remotes. Both will result same issue.
2. Work on TypeScript project for around ~30 min. and you will notice sluggish laggy selections and clicking. Also scrolling up/down is horrible.
3. Restarting Windows solves problem. Also two more things solves the problem. 
 a. If I open Task Manager and find `explorer.exe` and click on "Kill Process Tree" which result in terminating almost everything. This provides better VSCode next time I open it.
 b. When this slowness happens, close VSCode and run it from `cmd`. Wow. Everything is smooth, fast and <3.

1. Why my vscode instance becomes very slow after 30-40 minutes? Do I have to restart my windows every 30-40 minutes? :(
2. Why runing `code` from `cmd` makes vscode faster than normal launching?
3. I tried `"disable-hardware-acceleration": true,`. No luck. **But I haven't tried after system restart. Maybe something is cached. I will try now.**

Does this issue occur when all extensions are disabled?: **Yes**

See difference:

### This is when I work 1 hour and what VSCode becomes (launched from desktop):
[https://www.screencast.com/t/i7si0nBDJuo](https://www.screencast.com/t/i7si0nBDJuo)

### This is how it behaves when I launch from cmd:
[https://www.screencast.com/t/0s2rlgWGZmf](https://www.screencast.com/t/0s2rlgWGZmf)

Screencasts are 30fps. Please watch the cursor and scroll.

How can I solve this problem OR why is this happening?

One more note: I explicitly give selection and scroll screenshots in this issue. But also tab switching, file explorer is horrible after 30-40 mins. Either I have to restart my windows, kill `explorer.exe` tree or run from `cmd` to solve this.

Report Tool Output:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 1300X Quad-Core Processor           (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (26.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: example.com|
|OS|Linux x64 5.4.0-47-generic|
|CPUs|Common KVM processor (8 x 3311)|
|Memory (System)|16.60GB (7.16GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    90	  9788	code main
    0	    83	  1580	   window (Issue Reporter)
    1	    86	  1916	   shared-process
    3	    88	  3480	   gpu-process
    0	    25	 10288	   crashpad-handler
   30	   242	 12576	   window (● header.tsx - nienbo-com [SSH: example.com] - Visual Studio Code)
    0	     6	   216	     console-window-host (Windows internal process)
    0	     4	  7780	     C:\Windows\System32\cmd.exe /c (type "C:\Users\gence\AppData\Local\Temp\vscode-linux-multi-line-command-example.com-339626032.sh" | ssh -T -D 50345 -F "C:\Users\gence\.ssh\config_remote_ssh" example.com bash) & exit /b 0
    0	    10	 10428	       ssh  -T -D 50345 -F "C:\Users\gence\.ssh\config_remote_ssh" example.com bash
    0	   107	 10500	     extensionHost
    0	    38	 12756	   utility

Remote: SSH: example.com
CPU %	Mem MB	   PID	Process
    3	     0	2337183	remote agent
   11	     0	2337478	   extensionHost
    0	     0	2337490	   watcherService
    0	     0	2337518	   /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	2337519	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: some_server.com|    Folder (nienbo-com): 5710 files|      File types: cache(2402) jpg(244) scss(198) less(118) rb(103) png(79)
|                  svg(52) md(41) ttf(40) slim(39)
|      Conf files: package.json(3) project.json(1) settings.json(1)
|                  tsconfig.json(1);
```

</details>
<details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vsc-material-theme|Equ|33.0.0
output-colorizer|IBM|0.1.2
bats|jet|0.1.7
dotenv|mik|1.0.1
remote-ssh-edit-nightly|ms-|2020.9.35460
remote-ssh-nightly|ms-|2020.9.35460
vscode-remote-extensionpack|ms-|0.20.0
material-icon-theme|PKi|4.3.0
erb-types|rat|0.0.2
slim|sia|0.1.2
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2
vscode-ruby|win|0.27.0
auto-add-brackets|ali|0.11.0
react-pure-to-class-vscode|ang|1.1.8
i18n-ally|ant|2.3.19
vscode-gemfile|bun|0.4.0
better-toml|bun|0.3.2
ruby-debug|cas|0.3.5
solargraph|cas|0.21.1
gitignore|cod|0.6.0
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
vscode-projects-plus|fab|1.23.3
shell-format|fox|7.0.1
buildkite-ci-status|gen|1.3.0
vscode-buildkite-ci|gen|1.0.0
go|gol|0.17.0
css2react|got|1.0.1
vscode-git-tags|how|1.4.4
vscode-styled-components|jpo|0.0.31
vscode-colorize|kam|0.8.17
auto-comment-blocks|kev|1.0.1
bash-ide-vscode|mad|1.11.0
vscode-rufo|mbe|0.2.1
git-graph|mhu|1.26.0
vscode-scss|mrm|0.9.0
code-svgr|Nat|1.0.0
convert-css-in-js|pau|1.1.3
yard|pav|0.4.0
quicktype|qui|12.0.46
ruby|reb|0.27.0
vscode-yaml|red|0.11.0
gi|rub|0.2.11
slim|sia|0.1.2
vscode-nginx-format|tec|0.0.6
vscode-nginx|wil|0.7.2
vscode-ruby|win|0.27.0
markdown-all-in-one|yzh|3.3.0

(3 theme extensions excluded)

</details>

## Profiling the Renderer Process

[CPU-20200928T043307.zip](https://github.com/microsoft/vscode/files/5289463/CPU-20200928T043307.zip)

**Comment by gencer** [comment]
Hm.. It looks like I am runing `code` in `cmd` as administrator. Thats why it is fast. If I run via current user using cmd same again.

**Comment by jrieken** [comment]
Looks like a hit test issue. I believe @deepak1556 and @alexdima have seen this and know best what to do

<img width="724" alt="Screenshot 2020-09-28 at 16 22 29" src="https://user-images.githubusercontent.com/1794099/94444629-cff3ea80-01a6-11eb-9924-f6d888fc11e0.png">

**Comment by alexdima** [comment]
@gencer This might be #107016 or #106699

Could you please try killing all instances of vscode and running `code --disable-renderer-accessibility`. Is VS Code more responsive? How about if you kill all instances and run `code --disable-features=LayoutNG` ?

**Comment by gencer** [comment]
This didn't make any difference:

```
code --disable-features=LayoutNG
```

This **did**:

```
code --disable-renderer-accessibility
```

Much faster startup + No slowdown on selection + scroll at the moment. Let me try few hours more and If I see any problem I will update this issue...

**Comment by alexdima** [comment]
@deepak1556 Based on https://github.com/microsoft/vscode/issues/107560#issuecomment-700076650 , I think this is a dup of #107016 . I find it interesting that running as an admin also fixes the problem. I guess that a window running as an administrator does not receive these `WM_GETOBJECT` events or something...

**Comment by gencer** [comment]
@alexdima Thank you so much for the quick lookup and workaround. I ran the screen_reader_checker.exe on that issue and output is `0`:

```
PS C:\Users\gence\Desktop> ./screen_reader_checker.exe
0
```

For the administrator case, as you can see in my screencast slow one is run by normally by me and faster one is from `Windows PowerShell (Admin)`. Just to confirm, I tried almost 10-12 times and every time I did, Administrator-based run is faster than the current user.

**Comment by alexdima** [comment]
:+1: Thanks for the extra info. Let's continue tracking in #107016

**Comment by deepak1556** [comment]
> I guess that a window running as an administrator does not receive these WM_GETOBJECT events or something...

`Spy++` would be the way to find out the system messages a particular window is receiving. But for some reason it doesn't work with release build of electron, need to have electron launch via VS debugger.


I don't have much familiarity with accessibility code in chromium, but giving some windows tools a try based on https://chromium.googlesource.com/chromium/src/+/master/docs/accessibility/overview.md to see if we can spot any clues as to why this happens for certain users.
