### ISSUE TITLE
Debugger unexpectedly attaching when running git commit

### ISSUE THREAD

**Issue by neokamikai** [microsoft/vscode#107538]
Issue Type: <b>Bug</b>

# Steps to reproduce
* setup "git" to use vscode as commit message editor
* Open any git SCM project on vscode
* apply change to any files
* open the vs code terminal
* run "git add ."
* run "git commit", without the "-m" option to edit the commit message on vscode

You'll notice that the debugger is then attached, i can't see why it should be attached to anything in this step. Unless it's for precommit/postcommit checks, but in my project it's not configured.

Example output after the last step:
```
>git commit    
hint: Waiting for your editor to close the file... 
Debugger listening on ws://127.0.0.1:61422/aaf37dc0-1af3-415d-8885-477144476638
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
```

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3672)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (16.01GB free)|
|Process Argv|--crash-reporter-id 53b881b4-4919-404c-b600-1dff19995c44|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
language-maxscript|ate|1.10.3
vscode-intelephense-client|bme|1.5.4
simple-react-snippets|bur|1.2.3
emmet-jss|car|1.0.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vs-edit-hosts|con|0.0.1
vscode-eslint|dba|2.1.8
react-components|der|0.0.6
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
react-native-react-redux|EQu|2.0.4
vscode-open-in-npm|fab|1.0.4
php-debug|fel|1.13.0
php-pack|fel|1.0.2
duplicate|gee|1.0.1
gitlab-workflow|Git|3.3.0
vscode-graphql|Gra|0.3.10
todo-tree|Gru|0.0.178
vscode-react-typescript|inf|1.3.1
kubernetes-snippets|ipe|0.1.9
jenkinsfile-support|ivo|1.1.0
vscode-nuget-package-manager|jmr|1.1.6
react-native-snippet|jun|0.5.6
swift|Kas|0.2.0
graphql-for-vscode|kum|1.15.3
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.19.0
vscode-azurefunctions|ms-|0.24.1
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurestorage|ms-|0.10.0
vscode-azurevirtualmachines|ms-|0.2.0
vscode-cosmosdb|ms-|0.15.0
vscode-docker|ms-|1.6.0
vscode-dotnet-runtime|ms-|0.1.2
vscode-kubernetes-tools|ms-|1.2.1
mssql|ms-|1.9.0
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-ssh-explorer|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.3
azurecli|ms-|0.5.0
cmake-tools|ms-|1.4.2
vscode-node-azure-pack|ms-|0.0.11
azurerm-vscode-tools|msa|0.12.0
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|0.17.0
gradle-language|nac|0.2.3
color-highlight|nau|2.3.0
vscode-groovy-lint|Nic|1.2.8
docker-compose|p1c|0.3.5
material-icon-theme|PKi|4.3.0
qub-xml-vscode|qub|1.2.8
vscode-xml|red|0.13.0
vscode-yaml|red|0.11.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
rocketseatreactjs|roc|3.0.2
rocketseatreactnative|roc|3.0.1
nativeemmet|Sau|0.0.8
vscode-nginx|sha|0.6.0
vscode-scss-formatter|sib|2.0.2
hosts|tom|1.1.1
vscode-bemmet|vol|0.1.1
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
emmet-live|yse|1.0.0
editorconfig-vscode-snippet|zgu|0.2.0

</details>

**Comment by isidorn** [comment]
Sounds like auto attach, forwarding to @connor4312
