### ISSUE TITLE
when closing terminal, vscode freezes

### ISSUE THREAD

**Issue by katlimruiz** [microsoft/vscode#107557]
- VSCode Version: 1.49.2
- OS Version: win10

Steps to Reproduce:

1. debugged jest
2. closed Node Debug Window to go to previous terminal
3. The whole window freezes, and then win10 says: "Reopen, Wait or Close?"

Does this issue occur when all extensions are disabled?: Yes/No
Haven't tried it

**Comment by isidorn** [comment]
Can not repro. Do you have exact reproducable steps?
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by Hellek** [comment]
I have the same issue for a long time, a year maybe.
Usually it happens after hours of working with vscode. Chance to get an error higher if alot of programs opened in parallel (alot of memory used).
And it always happens when some process is runned, like vue-dev-server
