### ISSUE TITLE
Support customization of the panel

### ISSUE THREAD

**Issue by mikevaleriano** [Microsoft/vscode#10758]
Would it be possible to have the option to "extend" the integrated terminal to occupy the whole bottom of the vscode window while the sidebar is still visible? 

While working with it on 50% of the window the terminal gets too clunked and having to scroll a side bar is preferable to maximizing the window to see the terminal properly.

Current:
![image](https://cloud.githubusercontent.com/assets/6718750/17836823/98de472c-6775-11e6-820a-5da195d46011.png)

Goal (a really badly done mockup):
![image](https://cloud.githubusercontent.com/assets/6718750/17836830/bcaf92a0-6775-11e6-9eac-ce532ae47422.png)

Please forgive the broken English.

**Comment by isidorn** [comment]
We do not plans to tackle this in the next 12 months. Thus closing as no action is planned.
Also there are some new panela actions which might help ease the pain for this use case
