### ISSUE TITLE
Bad quick open pops up on any action clicked in editor toolbar

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#107543]
- VSCode Version: Codespaces
- OS Version: iPadOS 14

Steps to Reproduce:

1. Open any repo in Codespaces
2. Turn off `workbench.editor.showTabs`
3. Open any file
4. Use touch (not mouse) to click on any button at the top right corner (git, duplicate tab, close file, dropdown ellipsis)
5. If you click `duplicate tab` or `close tab` it fires the `Open Recent` command, showing the Command Palette (just like when you click on regular tabs when visible)
6. If you click `dropdown ellipsis` it just _blinks_ the dropdown items, and the same `Open Recent` command in the Command Palette

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Just to clarify: we currently do not fully support touch devices, so it may well be that the experience is buggy. Other related issues: https://github.com/microsoft/vscode/labels/ios

**Comment by alefragnani** [comment]
@bpasero no problem, I understand 👍 

I just wanna report the issue, because Codespaces could be a game changing for me, if iPadOS is fully supported.

Thank you

**Comment by bpasero** [comment]
I think this should be fixable, marking as help wanted if someone wants to chime in. The code that opens the command palette is probably doing something wrong:

https://github.com/microsoft/vscode/blob/b1c54c1483e2dfcf3101f233b3f8f28436127fba/src/vs/workbench/browser/parts/editor/noTabsTitleControl.ts#L91-L96

or

https://github.com/microsoft/vscode/blob/b1c54c1483e2dfcf3101f233b3f8f28436127fba/src/vs/workbench/browser/parts/editor/noTabsTitleControl.ts#L112-L117

**Comment by bpasero** [comment]
@rebornix looks like this is from the code you added:

https://github.com/microsoft/vscode/blob/b1c54c1483e2dfcf3101f233b3f8f28436127fba/src/vs/workbench/browser/parts/editor/noTabsTitleControl.ts#L112-L117

This is registered on the title container here:

https://github.com/microsoft/vscode/blob/b1c54c1483e2dfcf3101f233b3f8f28436127fba/src/vs/workbench/browser/parts/editor/noTabsTitleControl.ts#L76-L76

So it will open whenever you tap anywhere into the title area, including actions. 

My first idea was to register this listener simply on the same element as we do here:

https://github.com/microsoft/vscode/blob/b1c54c1483e2dfcf3101f233b3f8f28436127fba/src/vs/workbench/browser/parts/editor/noTabsTitleControl.ts#L48-L48

But that somehow was not working.

I attempted a fix via https://github.com/microsoft/vscode/pull/108736
