### ISSUE TITLE
GUI will become blur after every updating [Screenshot inside]

### ISSUE THREAD

**Issue by timeneverdie** [microsoft/vscode#107544]
![image](https://user-images.githubusercontent.com/15784314/94367427-5362fc80-0111-11eb-8d22-329bdc47f945.png)

- VSCode Version: **1.49.2 (user setup)**
- OS Version: **Windows_NT x64 10.0.19041**

Steps to Reproduce:

**Don't know how to reproduce it. But maybe it will show up every time after I update VSCode.**

Does this issue occur when all extensions are disabled?:

**Seem like only showing up once after updating. Reopen VSCode the issue has gone.**

**NOTICE:**

I am not sure but it seems like that this issue is related to AMD Chipset Software. 

Why I think so? Because after installing AMD Chipset Software, my **Anki** client has the same blur issue and hard to solve. 

I reinstall the Anki client and the issue was still there. Later I found a way: **disable hardware acceleration in Anki's setting option** and the issue is gone. But before I hadn't met this issue while hardware acceleration being checked on.

The GUI of Anki will remain the text which was showed in the GUI of AMD Chipset Software while installing it. 

I guess maybe some components or libraries affect all these three software: AMD Chipset Software, Anki and VSCode. The only thing I can confirm is that this issue is related to how Anki hardware acceleration works. Reboot PC is helpless so I think some settings has changed within the Windows OS to cause other software didn't work properly.

**Comment by deepak1556** [comment]
There isn't much vscode can do here, you can disable hw acceleration in vscode following https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
