### ISSUE TITLE
Visual studio adding spaces where not needed

### ISSUE THREAD

**Issue by marksteven** [microsoft/vscode#107505]
- VSCode Version:
- OS Version:

Steps to Reproduce:
Visual Studio code with no extensions turned on
1. add line to code (below)
 import { withAuthenticator } from “aws-amplify-react”;
2. Hit save and VSC automatically adds spaces between 
 import { withAuthenticator } from "aws - amplify - react"
causing it to break code even with all extensions off and rebooted.

Does this issue occur when all extensions are disabled?: Yes

Not sure if this is bug or setting somewhere but cannot find anything that would cause this so any help would be appreciated.

**Comment by mjbvz** [comment]
Your example code is using smart quotes (specific left quote and right quote characters) instead of the standard double quote character.

Formatting works fine for me using standard double quotes:

```ts
import { withAuthenticator } from "aws-amplify-react";
```

**Comment by marksteven** [comment]
HI mjbvz
thank you for that advice I was not aware VSC had this feature and that it was enabled.
Will find the setting and turn it off and I should be good to go.
again thanks could not find any reference to to his issue anywhere.
Mark
