### ISSUE TITLE
Add escape key (ESC) action for exiting fullscreen mode

### ISSUE THREAD

**Issue by nutpakorn-cat** [microsoft/vscode#107527]
## Pain Point
Due to VS Code provides only one way to exit fullscreen mode is that you have to press the entering fullscreen mode key again (F11 for Windows, control + command + F for macOS).

It is not a good user experience because if you accidentally press it and don't know which key is, 
you will get stuck in fullscreen mode, and can't exit the mode until you know which key is the entering fullscreen mode key.

## Feature Request
To improve this user experience, i want a feature that i can press ESC key to exit fullscreen mode instead of pressing the entering fullscreen mode key again.

Thank you

**Comment by rmunn** [comment]
The fullscreen key is discoverable by hitting F1 or Ctrl+Shift+P and typing "Full", but as evidenced by #107549 not everyone thinks of that, so it might be good to pop up a notification saying "You are in fullscreen mode. To exit full screen press (KEY). [ ] Never show again."

**Comment by bpasero** [comment]
@nutpakorn-cat I think your complaint about having to use the same keybinding is not valid, e.g. this keybinding config works to only exit fullscreen:

```json
{
	"key": "F3",
	"command": "workbench.action.toggleFullScreen",
	"when": "isFullscreen"
}
```

**Comment by bpasero** [comment]
Closing as this is a good solution that requires no new command.
