### ISSUE TITLE
Test/review references viewlet API

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107585]
Refs: https://github.com/microsoft/vscode/issues/106929

- [ ] anyOS @alexdima
- [x] anyOS @dbaeumer

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23107585%0A%0A)

---

The references viewlet has been reworked and now allows to show arbitrary contents via an extension API. 

* Make yourself familiar with the references viewlet API: https://github.com/microsoft/vscode-references-view/blob/a44cd9a6b08f9570572287f0fdbb2bd0b8ad035b/src/references-view.d.ts
* Create a new dummy extensions and extends the "Hello World" command so that it shows some content in the references viewlet

**Comment by dbaeumer** [comment]
@jrieken I am a little bit puzzled. How to I talk to the reference viewlet. The API list only interfaces. So how I get to the instance ?

**Comment by jrieken** [comment]
Like so 

```ts
const api = await vscode.extensions.getExtension<Api>('ms-vscode.references-view')?.activate();
if (!api) {
	return;
}
```

**Comment by dbaeumer** [comment]
Thanks!
