### ISSUE TITLE
Automatically add python virtual environments to .gitignore

### ISSUE THREAD

**Issue by rhymiz** [microsoft/vscode#107521]
**Feature:** Automatically add virtual environments to a project's `.gitignore` file so it doesn't accidentally get checked in. 
**Action trigger:** When a virtual env is added to your project's root directory.

This feature comes in handy in Codespaces where it looks like `pythonenvx.x` is automatically added to root.

**Comment by kieferrm** [comment]
\extPython

**Comment by kieferrm** [comment]
FYI @DonJayamanne
