### ISSUE TITLE
execInTerminal not found

### ISSUE THREAD

**Issue by suprateek13** [microsoft/vscode#107598]
Issue Type: <b>Bug</b>

I cannot see the terminate button to run the code.
As I try to run the code through my shortcut keys then everytime I am getting the error as mentioned in the Title bar.
![image](https://user-images.githubusercontent.com/71809075/94452107-cf6e4a80-01cc-11eb-98d6-4391312c11f7.png)

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:27:59.353Z)
OS version: Windows_NT ia32 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.67GB free)|
|Process Argv|--crash-reporter-id bd012653-b41e-4ab6-bff9-e9931d3cf477|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.9.111407

</details>

![image](https://user-images.githubusercontent.com/71809075/94457053-b0be8280-01d1-11eb-95f3-4303ee8d316d.png)

**Comment by kieferrm** [comment]
\extPython
