### ISSUE TITLE
Allow to resolve multiple similar problems.

### ISSUE THREAD

**Issue by Alex-0293** [microsoft/vscode#107591]
Allow to resolve more then one similar problem on the problem pane.
![изображение](https://user-images.githubusercontent.com/5895448/94440686-99b86a00-01aa-11eb-8efb-cfa0d8927a00.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo
What extension provides this errors? Does it have actions to fox problem in context menu for any of these problems?

ESLint extension provides action to fix all problems or all problems of given type, so it's up to extension to provide this functionality
![image](https://user-images.githubusercontent.com/1312662/94444263-d1291580-01ae-11eb-94cd-75e33968a396.png)

**Comment by Alex-0293** [comment]
I'm talking about Powershell extension. It doesn't have group action.
![изображение](https://user-images.githubusercontent.com/5895448/94808937-6875af00-03e1-11eb-8ece-3ce69634fc3f.png)

**Comment by sandy081** [comment]
Probably power shell extension can provide the same support as ES Lint?  It can contribute a quick fix action that says `Fix all Line has trailing whitespaces problems` ?

**Comment by Alex-0293** [comment]
Sounds good.

**Comment by sandy081** [comment]
Closing this since it can be handled by extension.
