### ISSUE TITLE
Add Uri parameter to moveFileToTrash command

### ISSUE THREAD

**Issue by xqzlgy2** [microsoft/vscode#107566]
Root Cause:
- Adding 'Delete' feature to context menu in `vscode-java-dependency` plugin, which is similar to file explorer's context menu like below
- Could not find a proper api which can make it have same behavior with file exploer

Already-explored Solutions:
- Use `moveFileToTrash` command, but could not pass an Uri to it, and it will automatically delete the file which is focused in file explorer
- Use `workspace.fs.delete` method, but could not show the same dialog like below. If use `showInformationMessage` instead, a lot of cases need to be dealt with, like text localization, warning for delete edited files etc.

Feature proposed:
- Add an Uri parameter to `moveFileToTrash` command
- Or show a dialog showing when calling `workspace.fs.delete`
- Or expose the dialog service to API level

Environment:
- OS: Windows 10
- VS Code version: 1.49.2

![image](https://user-images.githubusercontent.com/30518415/94396623-e1cc9200-0194-11eb-95ba-3b79b679e3c0.png)
![image](https://user-images.githubusercontent.com/30518415/94396339-4a673f00-0194-11eb-952c-cbb85b9a4e31.png)

**Comment by jrieken** [comment]
The `showInformationMessage` API support a flag to make a message modal. Did you try that?

**Comment by xqzlgy2** [comment]
> The `showInformationMessage` API support a flag to make a message modal. Did you try that?

I've tried and it looks better now. However, this dialog still have some difference compared with file explorer's deletion dialog, it will be good if I can directly call `moveFileToTrash` with an Uri in order to keep my feature corresponding to native one. Is there any reason not to exposure Uri parameter to plugin developers?

**Comment by Hikaruxy** [comment]
At the very least, @sleistner's [File Utils](https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils) extension can address this use-case in the interim.

**Comment by xqzlgy2** [comment]
It's great to see `vscode.open` and `vscode.diff` in custom trees have consistent behavior as built-in ones in VS Code 1.52! #110733

Benefited from this, our plugin have better UX when user open a file from Java Project Manager. microsoft/vscode-java-dependency#426

Since open has been added, could delete also be considered? In this case, other file operations may have more consistent experience too.

**Comment by jdneo** [comment]
+1 for this one. :)
