### ISSUE TITLE
incorrect coloring of c ++ comment block

### ISSUE THREAD

**Issue by duzeev** [microsoft/vscode#107565]
We have written the needed data into your clipboard because it was too large to send. Please paste.
incorrect coloring of c ++ comment block

```
#define TCP_NOTSENT_LOWAT	 25 /* Limit number of unsent bytes in

				       write queue.  */

#define TCP_CC_INFO		 26 /* Get Congestion Control

				       (optional) info.  */

#define TCP_SAVE_SYN		 27 /* Record SYN headers for new

				       connections.  */

#define TCP_SAVED_SYN		 28 /* Get SYN headers recorded for

				       connection.  */
```

Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:26:09.944Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic

**Comment by alexr00** [comment]
Moved to the repo that our C++ syntax highlighting grammar comes from: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/506
