### ISSUE TITLE
IntelliSense should remove already typed text

### ISSUE THREAD

**Issue by mac-pro** [Microsoft/vscode#10751]
Hi,

- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1. For example I have 2 phrases: _"Activity"_, _"ActivityBuilder"_.
2. Type _"Activity"_.
3. IntelliSense will propose: _"Activity"_, _"ActivityBuilder"_.

I think, if I already typed _"Activity"_, IntelliSense should remove that phrase, and only propose _"ActivityBuilder"_. So I can press Enter to grab that phrase.

Currently I have to press 2 keys, either:

- Down -> Enter.
- _B_ (to let IntelliSense remove the first phrase) -> Enter.

Thanks,

**Comment by jrieken** [comment]
Technically extension can already do that, but it seems like this could also be a user setting which always overrides the word-portion after the cursor.

@xfce0 With what language/extension do you see that?

**Comment by xfce0** [comment]
Thanks,

I checked my settings, but I think they're not related to this one.

The language is Java.

**Comment by jrieken** [comment]
closing as dup of #10266
