### ISSUE TITLE
Search files by name with current selection

### ISSUE THREAD

**Issue by tomer-simpo** [microsoft/vscode#107531]
**Feature description**
When clicking the shortcut cmd+p search files by name the current selection should be searched

**Comment by mifas** [comment]
Similar to this
https://github.com/microsoft/vscode/issues/80792

**Comment by roblourens** [comment]
Thanks for finding that @mifas

**Comment by tomer-simpo** [comment]
@roblourens Such a small yet important feature that frustrates many every day.   When migrating from Webstorm, where it was implemented many years ago, it makes searching for files very annoying 😔
