### ISSUE TITLE
opening and reading/writing .txt files with python on VS code

### ISSUE THREAD

**Issue by hugdp0** [microsoft/vscode#107593]
Issue Type: <b>Bug</b>

Description: there is a bug while opening .txt files in python where vscode tries to open it in the workspace general folder while the python file is in a folder/subfolder.
To reproduce it, it is very simple, when  you try to open a .txt file (by doing file = open("yourfile.txt", "r")) while in a folder/subfolder inside the workspace, it doesn't work because it tries to open the file from the workspace but not inside the folder/subfolder we are executing the python file in.
This can be checked by trying to write a .txt file because it will create it, not in the folder/subfolder, but in the workspace.
I don't know if it is just me doing it wrong but I don't think so because when executing the same python file with the python app, it opens the .txt file from the correct emplacement (inside the folder/subfolder where the python file is located).
Thanks for taking that into account and tell me if I am just being a noob and that I just forgot to do something or not.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041

**Comment by kieferrm** [comment]
\extPython
