### ISSUE TITLE
Remotes

### ISSUE THREAD

**Issue by SandPoot** [microsoft/vscode#107551]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Be on a repo, add a remote, see that no branches appear at all while trying to "Pull from" from added remote.

VS Code version: Code - Insiders 1.50.0-insider (ddc98c3f620ab1d2ecad5942ebf4736060403d67, 2020-09-25T05:35:02.163Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.94GB (12.00GB free)|
|Process Argv|--crash-reporter-id c78db87d-c84f-414e-8745-48f7f8311d05|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.36.3
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
byond-dm-language-support|gba|1.0.1
vscode-pull-request-github|Git|0.20.0
discord-vscode|icr|4.0.0
git-graph|mhu|1.26.0
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
mssql|ms-|1.9.0
python|ms-|2020.9.111407
notepadplusplus-keybindings|ms-|1.0.5
powershell-preview|ms-|2020.9.0
dm-langclient|pla|0.1.9
nunjucks|ron|0.3.0

</details>

**Comment by joaomoreno** [comment]
After adding a remote, you must first run Git Fetch.
