### ISSUE TITLE
Provide a command to open the folder or file for a specific output channel

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode#107571]
Right now, there is an `Open Log Output File` button in the `Output` panel, and the `Developer: Open Log File...` commands. But both of them work only for the default "log" channels, and not for output channels opened by extensions. Even though, apparently, those are, in fact, getting persisted in the log folder.

I would like for those commands to be extended to also open files (folders?) for extensions' output channels.

**Comment by sandy081** [comment]
Output channels, which are not logs, getting persisted in the folder is just an implementation/internal detail and it can happen that sometimes these can be stored in memory.
