### ISSUE TITLE
Tokenization for go files not working. 

### ISSUE THREAD

**Issue by shivam-tripathi** [microsoft/vscode#107508]
- VSCode Version: 1.49.2
- OS Version: Mac OS Catalina 10.15.5

Steps to Reproduce:

1. Open any `.go` file.
2. No syntax highlighting occurs. It's just plain text. 
3. Open `Developer: Inspect Editor Tokens and Scopes`
4. On hover it says `No grammar or semantic tokens available.`

Does this issue occur when all extensions are disabled?: Yes. 

I initially opened the issue at `https://github.com/golang/vscode-go`, but it turned out syntax highlighting is happening via vscode itself. 

#https://github.com/golang/vscode-go/issues/690

![Screenshot 2020-09-26 at 11 12 02 PM](https://user-images.githubusercontent.com/9463078/94346937-b8551e80-004d-11eb-8d80-2f4f3d2b1cbe.png)

**Comment by alexr00** [comment]
@shivam-tripathi can you try this in [VS Code Insiders](https://code.visualstudio.com/insiders/)?
If it still happens there, can you share a full copy/pastable example of code where this happens?

**Comment by shivam-tripathi** [comment]
@alexr00 It works as expected in VS Code Insiders.

**Comment by alexr00** [comment]
@shivam-tripathi thank you for testing it on insiders. This suggests one of two things:
- There was a bug and it is now fixed for the next release
- You have some setting or extension that is breaking this just for you on stable

Since I cannot repro the issue on stable, it is most likely the second one.

**Comment by victorhora** [comment]
I faced the same issue on both Vscode main and Vscode insiders. The problem seems to be an incompatibility/clash with the HCL AppScan CodeSweep extension. Disabling it seems to resolve the issue. Hopefully this help others until someone have the time to investigate the issue further :)
