### ISSUE TITLE
Emmet: Wrap lines with and using tag "a" locks or takes a long time

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#107592]
- VSCode Version: 1.50.0-insider  403a6895  2020-09-18T05:31:09
- OS Version: Windows8.1

Steps to Reproduce:

1. Create a html file with the following content
```
http://www.site.com/en-us/download/details.aspx?id=12345

http://www.site.com/download/details.aspx?id=12345

http://www.site.com/download/file.aspx?id=12345

http://www.site.com/download/foo.php?id=12345

http://www.site.com/download/foo.php
```

2. Select one of the URLs on a line (do not include the newline)

2. Execute command: `Emmet: Wrap Individual Lines with Abbreviation`

2. Use abbreviation: `a`

2. Press <kbd>Enter</kbd>

2. The first URL never finishes

2. The other URLs take a different amount of time from long to instant to create a result.

2. The URLs with the `?id=12345` are not recognised as a URL and the result does not fill in the `href` property. Only for the last URL the `href` property is filled with the URL

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment]
This should be fixed on the latest Insiders now. See https://github.com/microsoft/vscode/issues/54711
