### ISSUE TITLE
Debug hover is show on top of the item I wanted the hover for

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#107695]
Testing #107156

- I am debugging the tree view sample extension in our extension samples and when I hovered on following rootPath value in `vscode.workspace.rootPath`, the debug hover is shown covering the item completely

<img width="866" alt="image" src="https://user-images.githubusercontent.com/10746682/94561915-f4ae9780-0264-11eb-9800-cfad66492495.png">

<img width="314" alt="image" src="https://user-images.githubusercontent.com/10746682/94561835-dd6faa00-0264-11eb-9264-7ca4d725af11.png">

**Comment by isidorn** [comment]
The debug hover currently sets the preference to be placed above the location [here](https://github.com/microsoft/vscode/blob/1287f6b14a4c488549ed01f53af11e61b9d5ac73/src/vs/workbench/contrib/debug/browser/debugHover.ts#L325). It is up to the editor to choose the exact location, and in this particular case the editor decided to show the hover covering the item completely.

I am not sure if we can do anything regarding this.

fyi @alexdima for potential ideas

**Comment by alexdima** [comment]
@isidorn Maybe there is a missing `layoutContentWidget` call after changing the inside of the debug hover?

The positioning code will measure the widget and then cache its height. It looks like the editor positions the widget as if it would be only one line height high (i.e. without the wrapping seen in the picture)

**Comment by isidorn** [comment]
@alexdima good idea, but that does not seem to be the case looking at the code.
I always first set the content of the widget, and only then call the [`layoutContentWidget`](https://github.com/microsoft/vscode/blob/5ab1d926b623f10de864fff823a58cef1af7ec55/src/vs/workbench/contrib/debug/browser/debugHover.ts#L272)
However the widget word wraps, and in this particualr case it looks like the css breaks the widget in two lines. So I am not aware how many lines the widget will be, it is all handled by css.

**Comment by alexdima** [comment]
@isidorn How about this code path -- https://github.com/microsoft/vscode/blob/5ab1d926b623f10de864fff823a58cef1af7ec55/src/vs/workbench/contrib/debug/browser/debugHover.ts#L142 .. Shouldn't `layoutContentWidget` be called if there is a chance that the tree has expanded its height?

**Comment by isidorn** [comment]
@alexdima You are correct. 
I have pushed a change to tackle that code path. However I do not expect this to fix @sandy081 case since in his case the debug hover is not a tree, but a simple value (which is a different code path).
Though might fix it... @sandy081 let me know if you no longer see this

**Comment by sandy081** [comment]
Is this in today's insiders?

**Comment by isidorn** [comment]
@sandy081 no, will be tomorrow. I just pushed 1 hour ago :)

**Comment by isidorn** [comment]
Closing as I pushed an improvment for this and no further actoin is planned
