### ISSUE TITLE
Normal hover sticks even after releasing alt and moving cursor

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#107698]
Testing #107156

- Start debugging and hit a breakpoint
- Hover on any variable to get debug hover
- Press `alt` - you see normal hover
- release `alt` 🐛 normal hover sticks for a while and does not got off even after moving cursor.

**Comment by isidorn** [comment]
Yeah duplicate of https://github.com/microsoft/vscode/issues/107667
