### ISSUE TITLE
Provide extensions with a persistent logging channel

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode#107676]
Right now, there's the extension host log, but it can be non-trivial to filter only the records from a specific extension.

There are also output channels, but, apparently, these are not guaranteed to persist on disk:
https://github.com/microsoft/vscode/issues/107571#issuecomment-700599377

I would love to have a log channel specific to my extension, that would get persisted into files on disks.

**Comment by bryceitoc9** [comment]
The extension I work on instead writes to our own persistent log file with a command to open the file in the editor. It's a real shame that we can't tie our command to the "Open Log Output File" command in the output channel frame; would love to be able to use that whether or not we have to write to our own file.
