### ISSUE TITLE
After installing (without reload vscode), the extension is not reactivated when updateWorkspaceFolder api is called

### ISSUE THREAD

**Issue by giahuytn** [microsoft/vscode#107636]
- VSCode Version: 1.49.2
- OS Version: windo210

I am facing an issue, my extension is not reactivated when _updateWorkspaceFolder_ api is called after installing my extension. This issue does not happen if I reload vscode after installing it.
Refer to API doc:

> _If the first workspace folder is added, removed or changed, the currently executing extensions (including the one that called this method) will be terminated and restarted so that the (deprecated) rootPath property is updated to point to the first workspace folder._

It seems that the extension is terminated but not reactivated properly.
This issue also happens when saving a workspace folder. I also reproduce this on ESLint extension 

Steps to Reproduce:

1. Make sure ESLint extension is not installed
2. Open vscode and create a js file
3. Install ESLint extension. From output panel of log(ExtensionHost), ESLint is activated. ESLint log is added. But it is not displayed on result of command Developer:show running extension
4. Do command: Save Workspace As. **Observation**: ESLint extension is terminated, but not reactivated.

It seems that this issue has occurred in some recent builds (from 1.47). Could you have someone check this?

**Comment by bpasero** [comment]
Needs investigation if this is maybe a recent regression from the changes to support enabling extensions without window reload in remote.

**Comment by alexdima** [comment]
This is from 1.49.2, so it cannot be related to the recent changes. My best guess is we never supported this scenario.

**Comment by alexdima** [comment]
@giahuytn I cannot reproduce with your steps.

> 1. Make sure ESLint extension is not installed
> 2. Open vscode and create a js file
> 3. Install ESLint extension. From output panel of log(ExtensionHost), ESLint is activated. ESLint log is added. But it is not displayed on result of command Developer:show running extension
> 4. Do command: Save Workspace As. Observation: ESLint extension is terminated, but not reactivated.

* on step 3, the command `Developer: Show Running Extensions` shows ESLint
* on step 4, ESLint is shown again as activated.

**Comment by giahuytn** [comment]
@alexdima you need to delete ESLint Extension folder at %userprofile%/.vscode/extensions folder if having. It is the same situation with cases: first time install or upgrade extension

**Comment by alexdima** [comment]
@giahuytn I have ensured that the folder is deleted on disk. I cannot reproduce, I get the same behaviour as shown in the above gif.

**Comment by giahuytn** [comment]
@alexdima,
It seems that this only happens on window.
On step 3: the command Developer: Show Running Extensions shows ESLint, and ESLint Log panel appears
On step 4: ESLint log disappears and ESLint is not shown on Running Extension. It is not activated correctly.

![vscode_issue_2](https://user-images.githubusercontent.com/8381070/94777410-a973c080-03ed-11eb-973c-992bf53bd42e.gif)

**Comment by giahuytn** [comment]
hi @alexdima,
I also reproduce this issue on window with vscode 1.49.3. Do you reproduce it on your side?
Thanks,

**Comment by alexdima** [comment]
Simplified steps (only reproes on Windows):
- make sure eslint is not present in the `extensions` folder on disk
- open a JS file 
- run `F1 > Show Running Extensions`
- install ESLint
- ESLint activates but it does not show in the Running Extensions view
