### ISSUE TITLE
SSH environment variables not unset

### ISSUE THREAD

**Issue by theodoretliu** [microsoft/vscode#107630]
Issue Type: <b>Bug</b>

Hi, I've been using the Remote SSH plugin on my laptop and server to edit and debug my code. In my `~/.zshrc` file, I originally had an environment variable I declared `DB_URL`. However, I realized I didn't actually want that in my environment, so I removed the line from my `~/.zshrc` file and then exited all the SSH sessions from VS Code. However, every time I launch a new shell from VS Code on the server, I do `echo $DB_URL` and _still_ see the environment variable as set! What is going on? I tried SSHing directly from iTerm and the variable was unset as expected; this seems to imply that this is particular to how VS Code ssh's to the server and the vscode server that runs on the server.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 4.15.0-118-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|. --crash-reporter-id 8b74bfec-8b05-4ac4-aa67-eedbc993a4a6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: fortnite|
|OS|Linux x64 4.15.0-118-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (2 x 2199)|
|Memory (System)|3.85GB (2.42GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
vim|vsc|1.17.1
python|ms-|2020.9.111407

</details>

**Comment by roblourens** [comment]
You will have to kill the remote server, we launch one then keep attaching to it and it has the same environment.

Run the command "Kill VS Code Server on Host..."
