### ISSUE TITLE
Smoke test: Localization sometimes test fails under Windows (flaky)

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#107688]
Testing #107568

**Comment by dbaeumer** [comment]
It failes with

```
  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Localization
           starts with 'DE' locale and verifies title and viewlets text is in German:
     Error: Timeout: get text content '.monaco-workbench .part.sidebar > .title > .title-label > h2' after 20 seconds.
      at C:\Users\dirkb.EUROPE\Projects\mseng\VSCode\vscode\test\automation\out\code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\dirkb.EUROPE\Projects\mseng\VSCode\vscode\test\automation\out\code.js:9:58)

```

**Comment by dbaeumer** [comment]
The calls I do are

```
			await app.workbench.explorer.waitForOpenEditorsViewTitle(title => /geöffnete editoren/i.test(title));

			await app.workbench.search.openSearchViewlet();
			await app.workbench.search.waitForTitle(title => /suchen/i.test(title));
```

**Comment by dbaeumer** [comment]
I looked at the implementation and they basically end up if accessing `.monaco-workbench .part.sidebar > .title > .title-label > h2` which according to the dev tools exists:

<img width="777" alt="capture" src="https://user-images.githubusercontent.com/1931590/94559665-de530c80-0261-11eb-8752-00f49077335c.png">

@joaomoreno any hint / idea?

**Comment by chrmarti** [comment]
Same on Mac (not seen on Linux):
```
  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Localization
           starts with 'DE' locale and verifies title and viewlets text is in German:
     Error: Timeout: get text content '.monaco-workbench .part.sidebar > .title > .title-label > h2' after 20 seconds.
      at /Users/chrmarti/Development/repos/vscode/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/chrmarti/Development/repos/vscode/test/automation/out/code.js:9:58)
```

**Comment by dbaeumer** [comment]
Actually @joaomoreno help me to track this down. There seems to be something wrong with the workbench view switching. When that test fails you see

<img width="448" alt="capture" src="https://user-images.githubusercontent.com/1931590/94668568-7f000580-0310-11eb-9ae7-554dd04fe568.png">

Observe: the Search viewlet is active but the title shows Explorer.

**Comment by joaomoreno** [comment]
The smoke tests actually caught something!

![horn](https://media.giphy.com/media/H0mG4bN5BR8OBzPBJX/giphy.gif)

**Comment by isidorn** [comment]
Sound the horn of Gondor

**Comment by bpasero** [comment]
I just tried this with today's insider build on Windows (Parallels) but could not reproduce.

**Comment by joaomoreno** [comment]
Yeah @dbaeumer failed to mention this is flaky. Out of the multiple times we ran this while debugging, this repro'd about 50% of the times.

**Comment by bpasero** [comment]
Ok I let @sbatten decide if this is something for September then or not.

**Comment by sbatten** [comment]
reverted the change that causes this with this commit 228973889bc0e352f7cd11cc14755893f8d81864, will fix the separate issue next milestone with a different fix.

**Comment by sbatten** [comment]
brought back the reverted commit with better logic, hopefully there is no issue, but if this pops up again, try this commit as culprit https://github.com/microsoft/vscode/commit/c2337d8c5658ca5b0b0b0948131f0dc390604755
