### ISSUE TITLE
SCM commit message should have it's own whitespace color or be configurable not to highlight whitespace

### ISSUE THREAD

**Issue by hv-gerard** [microsoft/vscode#107689]
VSCode version: 1.49.2
Theme used: "Default Dark+" with some color customizations
Specific relevant settings:
```
"editor.renderWhitespace": "trailing",
"workbench.colorCustomizations": {
    "editorWhitespace.foreground": "#FF0000"
}
```

I've enabled the recently added "trailing" whitespace rendering option, and set the foreground colour to make any trailing whitespace stand out clearly. That works fine. I like the new configuration option, thanks!

Since changing the whitespace foreground colour, I have noticed that whitespace rendering is applied in the SCM commit message box when text is selected. For example:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/50950075/94556502-156ef100-0255-11eb-8967-3c889901f989.png">

As can be seen, some kind of rendering or overlay is being applied to spaces in the middle line, making it very difficult to read. I have confirmed by experiment that the "editorWhitespace.foreground" color is being used. When a less obtrusive color was used (as per the default, and a typical choice when _all_ whitespace is rendered), the impact was less noticeable.

I don't think that any whitespace rendering should be being applied in this box at all. If some users do desire it, I would expect them to want it at all times, not only for selected text.

I attempted to track down a location in the code where the rendering and associated color settings are applied for a SourceControlInputBox and thus be able to make a PR, however I don't have any knowledge of js/ts and it was taking me a lot longer than is reasonable.

**Comment by hv-gerard** [comment]
None of the duplicate suggestions apply. #104310 was the issue that added the "trailing" option mentioned in the description.

**Comment by joaomoreno** [comment]
Let's just disable render whitespace in the scm editor.

**Comment by rupran** [comment]
I think I found the right location for a fix and tested it locally already, would you mind if I sent a pull request?
