### ISSUE TITLE
Ignoring some C# warnings of OmniSharp

### ISSUE THREAD

**Issue by zsombornagy** [Microsoft/vscode#1076]
Hi!

I'm trying to ignore the "Unnecessary using directive." warning in my C# code (for Unity3D).
I've created an `omnisharp.json` file with this content:

```json
{
	"IgnoredCodeIssues": [
		"^Unnecessary using directive.$"
	]
}
```

Then I opened a C# file, and restarted OmniSharp (with the command palette within Code).
But it fails with this message:

```
System.FormatException: Unsupported JSON token 'StartArray' was found. Path 'IgnoredCodeIssues', line 2 position 24.
```

I'm using VS Code Version 0.10.3, on OS X 10.11.1.

Thanks!

**Comment by jrieken** [comment]
I don't believe that supported like that, but moving to OmniSharp for comment first.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#361
