### ISSUE TITLE
Ubuntu 20.04 VSCode "Unable to launch Chrome stable", auto-discovered "custom" and "dev" (Chromium)

### ISSUE THREAD

**Issue by gravityFlower** [microsoft/vscode#107608]
- VSCode Version:
```bash
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:26:09.944Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic snap
```
- OS Version:
```bash
$cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

- Relevant snap packages:

Name                     |Version                      |Rev   |Channel     		|Publisher	|Notes		
-------------------------|-----------------------------|------|---------------------|--------------|--------------
chromium                 |85.0.4183.121                |1320  |latest/stable    	|canonical✓	|-		
code                     |e5e9e69a                     |45    |latest/stable    	|vscode✓	|classic	
dotnet-sdk               |5.0.100-rc.1.20452.10        |100   |5.0/beta         	|dotnetcore✓	|classic	
snap-store               |3.36.0-80-g208fd61           |467   |latest/stable/…  	|canonical✓	|-		

- Snap version:
```bash
$snap --version
snap    2.46.1+20.04
snapd   2.46.1+20.04
series  16
ubuntu  20.04
kernel  5.4.0-48-generic
```

Steps to Reproduce:

1. Use Ubuntu 20.04, check if Chromium is installed (if not, install) _**Note: Chromium will be installed as Snap automatically**_

_**Note: Step 2 and 3 are probably unneccessary, since it seems that there is a problem with the path to the Chrom(e|ium) executable, but these are the steps which produced the current state**_

2. Install .Net Core 5 RC via snap (Don't use suggested snap alias, instead create symbolic link as described [here](https://github.com/dotnet/sdk/issues/10403#issuecomment-621463370))
3. Create new Blazor WebAssembly `dotnet new blazorwasm`

4. Start Visual Studio Code
5. Create Launch configuration
6. Run configuration

Expected behaviour:
- if Chrome is not found, check for Chromium (since it is aliased, this shouldn't be the problem) and launch the project with Chromium, probably with a warning about running a custom/dev version 
- as an alternative, provide a better error message, since i have no clue what should be done in this case

![Launch_failed](https://user-images.githubusercontent.com/12392087/94465033-911e5e80-01bf-11eb-8240-f5ca2fe24a95.png)

![launch_json](https://user-images.githubusercontent.com/12392087/94466346-967ca880-01c1-11eb-9401-3199acd10c44.png)

Does this issue occur when all extensions are disabled?: Yes/No
Not checked with all extensions disabled, but i uninstalled all extensions, uninstalled vscode, deleted the .vscode folder with all plugins, reinstalled the snap and only installed the C#-Extension(due to obvious reasons).

**Comment by kieferrm** [comment]
You are using a `balzorwasm` launch config. This launch config type is contributed by the C# extension. The C# extension is responsible for executing your launch config.

**Comment by kieferrm** [comment]
\extC#
