### ISSUE TITLE
Test Webiew View API finalization

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#107626]
Refs #46585

- [x] Mac @roblourens
- [x] Linux @sbatten 
- [x] Windows: @eamodio  

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23105764%0A%0A)

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23107626%0A%0A)

---

## Overview

The webview view API has now been finalized. In this plan item, try going through to test the api and the experience of writing an extension for it

- Start with the [webview view extension sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/webview-view-sample)

- Review the docs for the new apis in `vscode.d.ts`

- Look at webview view lifecycle (and showing and hiding view)

     - Does the dispose lifecycle make sense?
     - Are events for show/hide fired when you expect?

- Look at state management for the webview views

    - Make sure that webview state is persisted when: vscode is reloaded, a view is collapsed, a view is moved, a view is hidden.
    - Try using `retainContextWhenHidden`. When this is enabled, then switching so that the webview is no longer visible should preserve the iframe context itself.

**Comment by roblourens** [comment]
Are there going to be some docs about this on the website?
