### ISSUE TITLE
Setting sync is not working after removing extensions via command line

### ISSUE THREAD

**Issue by gokulkrishh** [microsoft/vscode#107632]
- VSCode Version: 1.49.2
- OS Version: 10.15.6 (osX)

Steps to Reproduce:

1. Sync your settings and quit the vscode editor.
2. Delete the extensions via `rm ~/.vscode/extensions` command in terminal. Re-open the vscode, extension, settings, etc are back to default and it is not syncing back to the last sync.

Does this issue occur when all extensions are disabled?: Yes/No - No

**Screenshot for vscode sync log after opening to sync back the deleted exts**:

<img width="1680" alt="Screenshot 2020-09-29 at 7 32 40 AM" src="https://user-images.githubusercontent.com/2944237/94504593-c6aa6280-0226-11eb-9b41-70612cd6f49a.png">

**Comment by sandy081** [comment]
In this case, your latest state of extensions (which is removing all installed extensions) is pushed to the server. You can see that from the log that extensions updated the data in remote.

May I know what are you expecting otherwise?

**Comment by gokulkrishh** [comment]
@sandy081 My expectation was, when I closed vscode editor and it can no longer sync the settings. When i opened it back it should have synced back extensions.

**Comment by sandy081** [comment]
No. After you open VS Code (after removing extensions from anywhere, same as changing a file that is being synced) VS Code sees that current state is changed and sync the state to the server. If the server has a different state (synced from a different machine), then VS Code does the merge. 

In short, changing the state is same as doing from the tool or outside the tool. It is same as turn off sync and uninstall extensions and turn on sync.

If you want to revert to a certain state, you can do it from Synced Data view - this is available with the command - `Settings Sync: Show Synced Data`
