### ISSUE TITLE
[scss] support cross file variable resulution

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/vscode#10762]
- VSCode Version: latest
- OS Version: 8.1

I reported this as `issue` , because I think this must be a default behavior in VSCode, please add this feature to the great VSCode.

Thank you !

**Comment by aeschli** [comment]
@MehdiDehghani Can give more details what is missing? What do you mean by 'hint'. It it for the .sass or the .scss Sass format?

**Comment by MehdiDehghani** [comment]
Sure, imagine you have `vars.scss` (contains some variables) and imported than in `main.scss` (as you know it's very common), there is no intellisense/autocompletion for `vars`'s variables.

Something like [this extension](https://github.com/konstantinkobs/brackets-SASShints) for brackets.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/6820

**Comment by mattez** [comment]
Very similar as this issue https://github.com/Microsoft/vscode/issues/6734
