### ISSUE TITLE
Minimum height of Open Editors group should respect the user's choice

### ISSUE THREAD

**Issue by mihaibrana** [microsoft/vscode#107679]
Hello :). This is both a feature request and, if I can dare, a small usability bug :)

Even if we increase the height of the _Open Editors_ **Explorer** group to accommodate more opened editors, when the editors are closed and then reopened, the area is again shrink'ed to a lower height. If we again open more editors, we then have to increase it via drag again.

Ideally, this should stay at the size it has been set, to prevent useless redraws when opening/closing editors AND to allow people who work with a lot of tabs to quickly be able to access them from a permanent location (the vertical tab bar is insufficient when opening many editors, thus, and opened editors is the "best hope" for a vertical tab bar in VS Code).

(hint ;) ) This could also be solved if the Opened Editors would get their own area, as I mentioned in
https://github.com/microsoft/vscode/issues/106927#

**Comment by isidorn** [comment]
Makes sense, however we do not have big plans on changing the open editors view at the moment. Thus assigning to backlog for now.

**Comment by martin-braun** [comment]
@isidorn I can see how this is low priority, but it's very annoying for me, because I decided to use it as vertical tab bar for better screen real estate. It's very frustrating for me right now.

**Comment by dshum1** [comment]
+1 to this feature request! I use the Open Editors section as a vertical tab bar too. It seems to automatically grow in height with the number of open files to a certain point, and then past that height (or number of files?), stops automatically expanding. I would love to be able to customize that max auto-expand height.

**Comment by wrinkledeth** [comment]
Same, this super annoying. Why can't the height be customized? I would prefer to be able to add extra vertical space instead of having it capped based on the number of open editors.
