### ISSUE TITLE
Error opening jupyter notebook

### ISSUE THREAD

**Issue by CristiDatas** [microsoft/vscode#107609]
Issue Type: <b>Bug</b>

Trying to open any jupyter notebook I get this message:

"Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed or enabled.
Reopen file with VS Code standard text editor". (when I click it runs ok).

I have check than I have the Microsoft Python extension (I have uninstalled and reinstall it) but the message is going on. S.O.S

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.72GB (2.56GB free)|
|Process Argv|C:\Users\crist\Documents\BOOTCAMP\GitPersonal\DataScience\week12\day1\exercises\regression_tensorflow.ipynb --crash-reporter-id 1d400811-efb2-4af4-9cf7-a2c56c2aa61c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.9.111407
geo-data-viewer|Ran|2.3.0
vscode-data-preview|Ran|2.2.0

</details>

**Comment by claudiaregio** [comment]
Seconding this error

![image](https://user-images.githubusercontent.com/19276747/94482063-92369800-018d-11eb-8e02-d48756ff9dbc.png)

**Comment by rebornix** [comment]
@DonJayamanne we renamed `onNotebookEditor` activation event to `onNotebook` as mentioned in https://github.com/microsoft/vscode/issues/93265#issuecomment-682034107, please update it otherwise users can't open the notebook with Python extension if it's not activated.

**Comment by CristiDatas** [comment]
I still get the error when opening Jupyter Notebook.
