### ISSUE TITLE
emmet Wrapping on individual lines not working

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode#107600]
Issue Type: <b>Bug</b>

See https://docs.emmet.io/actions/wrap-with-abbreviation/ "Wrapping individual lines"
Where this does work in atom it does not on VSCode. Selecting Wrap with abbriviation after selecting multple lines and typing for instance "ul>li*>a results in :
```
	<ul>
		<li>
			About
			News
			Prodducts
			Contact
		</li>
	</ul>
```

and not
```
<ul>
	<li>About</li>
	<li>News</li>
	<li>Prodducts</li>
	<li>Contact</li>
</ul>
```

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.88GB free)|
|Process Argv|--crash-reporter-id e1d6a1bb-9d8f-4f44-a55c-80319d53b841|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
php-debug|fel|1.13.0
php-pack|fel|1.0.2
beautify|Hoo|1.5.0
vscode-wordpress-hooks|joh|0.4.0
vscode-github|Kni|0.30.4
git-graph|mhu|1.26.0
mssql|ms-|1.9.0
vsliveshare|ms-|1.0.2740
php-docblocker|nei|2.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
lorem-ipsum|Tyr|1.2.0

</details>

**Comment by rzhao271** [comment]
@theking2 I just noticed that there's a command "Emmet: Wrap Individual Lines with Abbreviation". Selecting that command and typing in `ul>li*` worked for me.
I wonder if that's the command you meant to use instead?
