### ISSUE TITLE
Property resolveSourceMapLocations is not allowed

### ISSUE THREAD

**Issue by RevealedFrom** [microsoft/vscode#107637]
- VSCode Version: 1.49.1
- OS Version: Windows 10 Version 2004 Build 19041.508

Steps to Reproduce:

1. Node/Express project that was running fine for two years. No modifications made since last problem-free run.
2. Today, it hit the `Could not read source map ... ENOENT no such file or directory` problem as in #102042 of July.

Tried to add `resolveSourceMapLocations` but it was not allowed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
For `resolveSourceMapLocations` to show as allowed, you need to set the type to `pwa-node`. This will eventually no longer be needed, but is required at the moment while we still have the old debugger available for compatibility/fallback.

**Comment by pebanfield** [comment]
Ug guys. Love this free product, but verifying debug should be in the baseline test suite. It's not obvious where to find previous build version either...

**Comment by connor4312** [comment]
@pebanfield please file an issue using the template here: https://github.com/microsoft/vscode-js-debug/issues/new/choose

**Comment by RevealedFrom** [comment]
> For `resolveSourceMapLocations` to show as allowed, you need to set the type to `pwa-node`. This will eventually no longer be needed, but is required at the moment while we still have the old debugger available for compatibility/fallback.

Yes, if I run it using Node (Preview)…, ie type `pwa-node`, the error is not there. I don't have to set `resolveSourceMapLocations`.

**Comment by KevinNovak** [comment]
Will `resolveSourceMapLocations` eventually work with `"type": "node"`? It seems to be working even though the editor is complaining about it.

**Comment by connor4312** [comment]
Yes
