### ISSUE TITLE
Visualize change of values while debugging

### ISSUE THREAD

**Issue by MasterTim17** [microsoft/vscode#107614]
Hello,
im debugging an STM microcontroller via platformio. So there is a variable, watch, beripherals and register tab on the left. When i step through the code, it would be very nice to see which value changed and mark it red so i can see which changed. This would be very helpful in peripheral debugging

**Comment by isidorn** [comment]
This is already supported and works just fine for me with latest vscode insiders
In the gif you can see how the value changes are outlined in blue in VARIABLES view.

This color can also be customised via `debugView.valueChangedHighlight` color customisation. So either create a new theme or customise your current theme via `workbench.colorCustomizations` setting

![recording](https://user-images.githubusercontent.com/1926584/94544268-519d5400-024b-11eb-9172-e94775601869.gif)
