### ISSUE TITLE
renderLineHighlight doesn't work with remote files

### ISSUE THREAD

**Issue by dharrington** [microsoft/vscode#107601]
- VSCode Version: 1.49.1
- OS Version: Debian

Steps to Reproduce:

1. Use "editor.renderLineHighlight": "all"
2. Connect to a remote instance using the Remote - SSH plugin.
3. Use the Dark+ theme (or any other theme it seems)
4. Open a remote file.

Notice the editor does not show a box around the current line. Only the gutter changes, with a text color change.

5. Copy/paste the contents of the file into a new editor (with ctrl+n).

Notice a box is shown around the current line.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
@dharrington The setting `"editor.renderLineHighlight": "all"` works fine for me for any remote file that I try. What is much more likely, is that you are opening a file from a folder or a workspace where you have a `.vscode` settings folder and where perhaps there is also configured `editor.renderLineHighlight`, but with a different value:

**Comment by dharrington** [comment]
That's exactly right. I didn't realize folder settings were a thing, or that I had some. Thanks
