### ISSUE TITLE
字体显示模糊

### ISSUE THREAD

**Issue by GUJUNNIAN** [microsoft/vscode#107641]
- [ ] Issue Type: <b>Bug
![Uploading image.png…]()
![微信截图_20200929134547](https://user-images.githubusercontent.com/30283164/94517329-4867b380-025a-11eb-8262-3deec8a506a6.png)

</b>

打开编辑器过一会，字体就会出现模糊的现象

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.78GB free)|
|Process Argv|--crash-reporter-id 15822082-ba19-4786-bc92-eae33ab568ab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.10
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.49.2
debugger-for-chrome|msj|4.12.11
vscode-preview-server|yui|1.3.0

</details>

**Comment by Ycmelon** [comment]
Translation:
The font is blurred
After opening the editor for a while, the font will become blurry
