### ISSUE TITLE
Show the help text/tip in the bottom of debug hover to switch to normal hover

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#107697]
Testing #107156

Show the help text/tip in the bottom of debug hover to switch to normal hover

**Comment by isidorn** [comment]
This is a good idea.
For now opening this to PRs. If nobody is interested I can tackle this in the future
Code pointer https://github.com/microsoft/vscode/blob/1287f6b14a4c488549ed01f53af11e61b9d5ac73/src/vs/workbench/contrib/debug/browser/debugHover.ts#L66

If there is somebody interested please first ping us here so we can also involve some design @misolori

**Comment by sseelam2** [comment]
@isidorn Hi Isidor, I am interested!

**Comment by isidorn** [comment]
@sseelam2 ok, great. So the things to note is that the debug hover has 2 modes.
* First one is when a simple value is shown, for example when the user hovers over a string
* Second one when an object is shown, for example when the user hovers over `console` in javascript. This mode contains a tree which can be expanded

It seems like we would have to introduce a common `HTMLElement` that will be used in both these cases. 
This element would be placed after both the `complex-value` and the `.value` container.
Thing to note: layout of the other containers and the total height of the debug hover does not get broken.

Please note that there is no 100% chance that we accept this. I am still not sure who will this look in the end.

@misolori for potentially sketching something up if you find time.

**Comment by isidorn** [comment]
Went ahead with this. This is how it looks like

![Screenshot 2020-11-13 at 10 01 39](https://user-images.githubusercontent.com/1926584/99049599-561d9200-2597-11eb-9a1b-b31518f150d8.png)
