### ISSUE TITLE
Copying long string value from debug variables gives only abbreviated version

### ISSUE THREAD

**Issue by andig** [microsoft/vscode#107699]
Expected behaviour: the full value  is copied  instead of the abbreviated  version.

- VSCode Version: 1.49.2
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Inspect a loooooong string in the Debug->Variables view
<img width="557" alt="Screenshot 2020-09-29 at 15 37 22" src="https://user-images.githubusercontent.com/184815/94565822-f9297f00-0269-11eb-845f-3c6d77902246.png">

2. Copy the value and paste back into an editor
<img width="796" alt="Screenshot 2020-09-29 at 15 37 29" src="https://user-images.githubusercontent.com/184815/94565863-047caa80-026a-11eb-983e-17f96f5b47aa.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Right click -> copy value should give you the expected result

**Comment by andig** [comment]
Thank you for the feedback. After revisiting the issue my feeling is that this is not working as designed, at least not working as expected. IMHO the usual behaviour for controls showing abbreviated content is to switch to full content once activated (i.e. receiving focus or cursor positioned inside). That way, the usual copy/paste controls would still work. A second aspect is accessibility. It is imho unexpected to have to invoke a popup menu for doing something as simple as a copy operation.

I‘d kindly ask for review.

**Comment by isidorn** [comment]
Already discussed in previous issues. Please search our closed issues.
This is controlled by node and node can not provide a full result unless it's evaluated.

**Comment by andig** [comment]
Searching through [closed issues](https://github.com/microsoft/vscode/issues?page=2&q=is%3Aissue+label%3Adebug+is%3Aclosed+variable+copy) I have  found https://github.com/go-delve/delve/issues/1190, https://github.com/microsoft/vscode/issues/46288,https://github.com/microsoft/vscode/issues/24769 and https://github.com/microsoft/vscode-go/issues/868.

> This is controlled by node and node can not provide a full result unless it's evaluated.

It seems you're indicating this is controlled by  the language server, not by the view since it needs be evaluated?  In this case the  issue should be moved to the go  plugin?

**Comment by isidorn** [comment]
Correct. I was not aware that you are using the go plugin. Feel free to file an issue in their repository.
