### ISSUE TITLE
VSCode Executable file missed signature?

### ISSUE THREAD

**Issue by wbsdty331** [Microsoft/vscode#10763]
- VSCode Version:1.4.0
- OS Version:Windows 10

![qq 20160821215537](https://cloud.githubusercontent.com/assets/4280572/17837607/01c9044c-67ea-11e6-9df5-f10abbda42b2.png)

**Comment by joaomoreno** [comment]
Thanks for reporting.

**Comment by isidorn** [comment]
Verification steps?

**Comment by joaomoreno** [comment]
Right click `Code.exe` (or any DLL we ship with), hit Properties, it should have a Signature by Microsoft.
