### ISSUE TITLE
Test realtime performance view

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#107623]
Testing https://github.com/microsoft/vscode-js-debug/issues/755

- [x] anyOS @jrieken 
- [x] anyOS @sbatten

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23107623%0A%0A)

---

This iteration the [flamechart visualizer](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-js-profile-flame) now includes a "realtime performance" view which appears in the Debug view while running a JavaScript debugee (node.js, browser, or ext host).

![](https://memes.peet.io/img/20-09-d02f166b-3308-4d8d-b36f-e0d2c7d8fed4.png)

- The graph shows performance information for the active (currently selected) debug session
- The top left is the graph vertical scale
- The bottom times are the horizontal scale.
- The bottom indicates the color of each series, along with the current value. Hovering on the chart will show you the value at that point in time.
- Clicking on the series expands the "configurator" which lets you toggle series on and off (Node.js only support CPU and heap; browsers support more). When expanded, you can click on the graph to collapse the configurator.
- The gear in title opens a quickpick giving similar functionality as the configurator (this is also accessible via command)
- The split action toggles between showing all the series on one plot, versus having separate plots
- You can configuring easing, the poll interval, and the width of the graph (in milliseconds) data to retain

Verify that things work and the UI makes sense to you

**Comment by jrieken** [comment]
I don't get this to work/show.

**Comment by connor4312** [comment]
The bumped commit was reverted from the last Insiders, so you may need to use js-debug nightly or tomorrow's insiders.

**Comment by jrieken** [comment]
Filed a few polish items but I really like this 👏

**Comment by connor4312** [comment]
Thanks! :)
