### ISSUE TITLE
I cannot debug code on my chrome browser

### ISSUE THREAD

**Issue by DavidBenHorin** [microsoft/vscode#107666]
I have some js files that when I run them to debug, the browser gives me this error:

This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
![debug](https://user-images.githubusercontent.com/20887199/94539957-924a9c80-024e-11eb-81dd-99035e2acbcb.png)

**Comment by isidorn** [comment]
@DavidBenHorin reproducable steps please.

**Comment by connor4312** [comment]
This means that your web server (like a webpack dev server) is not listening, or it's not on localhost:8080. You can change the address in your launch.json.
