### ISSUE TITLE
Can't do multiple undo/redo (cmd + z) on iPadOS using Codespaces

### ISSUE THREAD

**Issue by VincentDondain** [microsoft/vscode#107616]
Version: 1.50.0-insider
Commit: 403a6895f401c397933ec5c4f7d89432a33509b6
Date: 2020-09-18T05:28:58.063Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15

Steps to Reproduce:

1. Open a Codespace / VSCode web on iPadOS
2. Type a bunch of text.
3. Try long pressing cmd + z to undo multiple changes. The command will only be ran once.

Note: this works fine on desktop VSCode.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
@rebornix Can you please try this out? I don't have access to an iPad with a keyboard.

**Comment by kieferrm** [comment]
@alexdima confirmed.

**Comment by rebornix** [comment]
I'm not seeing this issue in today's CS ppe (VS Code bits are from Oct 28 Insiders), @kieferrm are you still seeing it now?

**Comment by alexdima** [comment]
I also tried it just now and it works for me.
