### ISSUE TITLE
[theme] only restore the previous theme if the user has not changed the theme

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107673]
Testing #106389

* configure a HC default theme `Abyss`
* enter HC
* theme changes to Abyss
* manually change theme to Kimbie
* leave HC

=> 🐛 all my theme changes are lost

I think I would only restore the previous theme if the user has not changed the theme meanwhile?

**Comment by aeschli** [comment]
Fixed by the changes for https://code.visualstudio.com/updates/v1_89#_auto-detect-system-color-mode-improvements
