### ISSUE TITLE
Debug hover looks cut off

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#107696]
Testing #107156

<img width="794" alt="Screenshot 2020-09-29 at 15 07 08" src="https://user-images.githubusercontent.com/10746682/94562356-88806380-0265-11eb-9e09-8505e0f2bdde.png">

It looks cut off. It shall not span until the edge.

**Comment by isidorn** [comment]
Yeah it looks too wide for this case. Let me assign to September to investigate if we can do something about the width (to make it a funciton of the editor width)

**Comment by isidorn** [comment]
Did not find a nice way to cap the width. No change for now, might tackle it in the future.
