### ISSUE TITLE
ms-vscode.js-debug is slow to activate

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107680]
* get the `ms-vscode.js-debug` activated
* check F1 > Startup Performance
* 🐌 it takes 265ms to load the code for that extension

```
| ms-vscode.js-debug                         | false | 265       | 11            | 1   
```

**Comment by connor4312** [comment]
Thanks for the issue. js-debug has become a big bundle that hooks into quite a few things. We can probably split the "debug adapter" portion of the bundle so that only UI contributions get loaded until a debug session starts.

**Comment by connor4312** [comment]
In the linked commit I have removed our runtime dependency on TypeScript in favor of Acorn (which we were already using for beautification) which drops the bundle size from 3.6 -> 1.3MB and should significantly improve startup time.
