### ISSUE TITLE
Test settings editor a11y changes

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#107610]
Refs: #106897

- [x] macOS @sandy081
- [x] linux @jrieken
- [x] windows @dbaeumer

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23107610%0A%0A)

---

Please test the changes to the settings editor, which will be the default experience in this month's release. As a reminder, the motivation and a description of the changes are here #104318 (option A).

Some things to test

- Try navigating with a screen reader, and ensure that you hear basically the right info at the right time. For example, when a setting row is focused, you should hear the name and description. When you focus the control inside the row, you should _not_ hear the description/name a second time.
- When a setting row is focused, `enter` focuses the control inside the row (input box, dropdown, etc), and `tab` will tab through the fields of the focused row in order
- The focused row is the only one that is tabbable
- Clicking the control of a setting row makes the row itself selected, and the focused control can not get out of sync with the selected row
- `escape` returns focus from the setting control to the setting row, then to the table of contents, then to the search bar
- The row selection colors look ok in different themes, including custom themes
- The gear icon context menu button can be triggered by tabbing to it, or the "shift+f9" keybinding when the row is focused
- Switching into and out of search mode still has the right behavior
- When focus is in the setting control, keybindings go to the control and not to the list, for example pressing "down" when a dropdown is focused should always expand the dropdown/change dropdown selection, and not change the focused row of the settings list

**Comment by sandy081** [comment]
👏  Good job - works pretty well with Keyboard

**Comment by dbaeumer** [comment]
I agree with @sandy081. Nice work!
