### ISSUE TITLE
Changed files notifications + loading indicator absent on commit and push

### ISSUE THREAD

**Issue by saharso** [microsoft/vscode#107686]
Issue Type: <b>Bug</b>

As after the latest upgrade, I noticed that the blue circle with the number of changed files that is displayed on the git icon, is not updating after I push the changes.

You can see in the attached screenshot that the "changes" tab on the grey sidebar is empty, but the blue notification indicator still shows "4" files, although in reality there are none.

Also, there used to be a "loading" animation above the sidebar that indicate how long until the push was successfully submitted. This is no longer happening.

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|-psn_0_381021|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.52
vscode-eslint|dba|2.1.8
githistory|don|0.6.10
gitlens|eam|10.2.2
beautify|Hoo|1.5.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-jest|Ort|3.2.0
code-spell-checker|str|1.9.1
vscodeintellicode|Vis|1.2.10

</details>

![image](https://user-images.githubusercontent.com/19216444/94554234-751fc900-0262-11eb-9c31-f3f3a7764f88.png)

**Comment by joaomoreno** [comment]
@sbatten Did you touch something here lately?

**Comment by joaomoreno** [comment]
@saharso Can you reproduce reliably? On any repository?

**Comment by sbatten** [comment]
@joaomoreno nope, and this is 1.49.1 so I really don't know. 

@saharso can you right click `SOURCE CONTROL` and show all hidden views (if there are any) in case there is some context missing here?

**Comment by saharso** [comment]
Hi everyone,
I reported the bug.
It was resolved for me yesterday, when I upgraded to the latest version.

Thank you for your efforts,
Sahar Soffer
