### ISSUE TITLE
Stopped hitting breakpoints in TypeScript code

### ISSUE THREAD

**Issue by jdforsythe** [microsoft/vscode#107615]
As of version 1.49.1 (perhaps 1.49.0 - I skipped that update) the debugger seems to no longer follow the source map and show the breakpoints in the TypeScript code (using `ts-node`) but rather shows the breakpoints in compiled JavaScript code.

In a sample file (`index.ts`)

```ts
function testFn() {
  console.log('Something');
  console.log('Something else');
}

testFn();
```

If I put a breakpoint on the first `console.log` and run the debugger, it used to show a breakpoint on that same line in the same file and allow me to step through the code. Now it brings up a compiled JS file and puts the breakpoint there:

index.ts:

```js
function testFn() {
    console.log('Something');
    console.log('Something else');
}
testFn();
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiL1VzZXJzL2plcmVteWZvcnN5dGhlL2Rldi90ZW1wL3Rlc3QtdHMvc3JjL2luZGV4LnRzIiwic291cmNlcyI6WyIvVXNlcnMvamVyZW15Zm9yc3l0aGUvZGV2L3RlbXAvdGVzdC10cy9zcmMvaW5kZXgudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsU0FBUyxNQUFNO0lBQ2IsT0FBTyxDQUFDLEdBQUcsQ0FBQyxXQUFXLENBQUMsQ0FBQztJQUN6QixPQUFPLENBQUMsR0FBRyxDQUFDLGdCQUFnQixDQUFDLENBQUM7QUFDaEMsQ0FBQztBQUVELE1BQU0sRUFBRSxDQUFDIiwic291cmNlc0NvbnRlbnQiOlsiZnVuY3Rpb24gdGVzdEZuKCkge1xuICBjb25zb2xlLmxvZygnU29tZXRoaW5nJyk7XG4gIGNvbnNvbGUubG9nKCdTb21ldGhpbmcgZWxzZScpO1xufVxuXG50ZXN0Rm4oKTtcbiJdfQ==
```

Breakpoint setting/removal in the original TS file does not work. Existing breakpoints sometimes disappear and other times just say "unbounded". Clicking to set/remove breakpoints exhibits odd behavior:

![breakpoints-01](https://user-images.githubusercontent.com/286972/94478151-e4cd7f80-01a0-11eb-83e8-2c7544cf0630.gif)

Many (most?) times the breakpoints don't end up on the proper lines in the compiled code, and many times the code never stops executing.

![breakpoints-02](https://user-images.githubusercontent.com/286972/94478766-b7350600-01a1-11eb-8b4b-a03057b48446.gif)

In a particular app I was working on over the last week or so (when I noticed the issue), it won't hit any breakpoints. I did notice that if I set these breakpoints, for instance:

![Screen Shot 2020-09-28 at 3 49 43 PM](https://user-images.githubusercontent.com/286972/94479173-64a81980-01a2-11eb-8bb8-38a43e791876.png)

then I press play on the debugger, the line numbers get changed to:

![Screen Shot 2020-09-28 at 3 49 50 PM](https://user-images.githubusercontent.com/286972/94479203-6d005480-01a2-11eb-96ce-f37221000318.png)

If I try to add a breakpoint while it's running, I either get duplicate entries in the breakpoint list (and it still doesn't break on that line) or I get a line number + character combination, e.g. `46:13`

- VSCode Version: 1.49.2
- OS Version: macOS Catalina 10.5.5

Steps to Reproduce:

1. Expand the simple repro [tsdebugger.tar.gz](https://github.com/microsoft/vscode/files/5294561/tsdebugger.tar.gz)
2. `yarn install`
3. See the example GIFs above

Does this issue occur when all extensions are disabled?: Yes

**Comment by jdforsythe** [comment]
It does not match anything from the duplicate detection. Also, just to be clear about the expected behavior, it has always showed the breakpoints and allowed stepping through/over/into the code in the *original* typescript code. We have been using this exact configuration for well over a year across dozens of applications.

**Comment by connor4312** [comment]
Thanks for the issue and repro.

The issue is that you have `outFiles` configured to `".ts-node/**"`. In 1.49.0 we made a change to default the locations in which we resolve sourcemaps to the outFiles pattern. Previous, it was "all files excluding node_modules", but this caused confusion if someone actually _was_ debugging in their node_modules (e.g. npm-link'd modules) and hid issues setting breakpoint on a race condition.

So the solution for you is to change your `outFiles: ["${workspaceFolder}/src/**"]` -- or just remove the property, which is no longer necessary to configure in most cases.

**Comment by artyil** [comment]
Removing `outFiles` property resolved the issue for me, thanks a lot @connor4312 
Saved my day / week 👏 👍

**Comment by connor4312** [comment]
Glad it worked for you!

Going ahead and closing this issue as we've not heard back from the original poster in several weeks.

**Comment by jdforsythe** [comment]
Yep, tried this and it worked. Thanks @connor4312

**Comment by ChuckJonas** [comment]
If your hitting this issue and have no idea why, try removing and rebuilding your entire project.  I was running into it after doing a big refactor and reseting my "outFiles" solved it.
