### ISSUE TITLE
markdown messy code

### ISSUE THREAD

**Issue by JonDoe297-Rorschach** [microsoft/vscode#107648]
Write Chinese on the MD file,Open it in other text editor,then it will appear some messy code.   Try to copy and paste this in a MD file with vscode    --->  '| 排序算法 | 排序算法 |  排序算法  |
| -------- | -------- |  --------  |
| 排序算法 | 排序算法 |  排序算法  |'

**Comment by jrieken** [comment]
What is messy code?
