### ISSUE TITLE
Add build menu

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#107683]
This has always seemed like a weird oversight to me. Building code is one of the main things IDEs do, but the interface to start builds is hidden away in shortcuts (Ctrl-Shift-B), in the command palette (`Tasks: Run Build command`) and in obscure JSON files (`.vscode/tasks.json`). In contrast *running* code gets a full menu:

![image](https://user-images.githubusercontent.com/376842/94551633-8e6a4a80-024d-11eb-9059-b985c6754e9a.png)

It seems like it would help usability / discoverability to add a `Build` menu (or possibly `Tasks`?) just to the left of `Run` that contained similar things:

* Build default
* Build -> [submenu listing available build tasks]
* Add build configuration
* Edit build tasks

Something like that. I believe #20464 was requesting this (somewhat ambiguously), and build discoverability was mentioned as an issue [here](https://github.com/microsoft/vscode/issues/106717#issuecomment-694952168).

**Comment by alexr00** [comment]
Build and tasks related commands are actually in the terminal menu. To keep from having too many menus, we don't have a separate menu just for tasks. @misolori FYI. Happy to add a tasks menu if that is one of the outcomes of the first run discussions.

**Comment by Timmmm** [comment]
Oh, so they are. Well that is super confusing! I have literally never looked in the Terminal menu. Why would I think "I want to build this project... better go to the terminal menu!"? I think this just further highlights how confusing the run/build/task menu system is. If you look at the menu most items are related to tasks, not the terminal, and 4 of them are named `Run ...` but aren't in the `Run` menu!?

![image](https://user-images.githubusercontent.com/376842/94557591-aeead280-0256-11eb-8f99-cfb949a0e8a2.png)

Also the terminal is already accessible through the more logical place `View->Terminal`. I suggest renaming this menu to `Tasks` and maybe moving/removing the two terminal items. It probably needs a proper rethink by your UX guys.

**Comment by alexr00** [comment]
Further history: https://github.com/microsoft/vscode/issues/56836

@bpasero and @Tyriar FYI.
