### ISSUE TITLE
ESLint status bar item doesn't do anything after choosing "Disable"

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#107692]
Testing https://github.com/microsoft/vscode/issues/107584

I chose "Disable" here: 
![image](https://user-images.githubusercontent.com/38270282/94561177-f461cc80-0263-11eb-9f3d-366372193b3b.png)

I see that the status bar item is no longer red, which I am happy about.

However, since there is still a status bar item, I expect that I can click on it again and change my decision (see the same dialog from before). Clicking on the status bar item does nothing.

**Comment by dbaeumer** [comment]
Fair. Let me see what I can do.

**Comment by dbaeumer** [comment]
Fixed and updated https://github.com/microsoft/vscode-eslint/releases/tag/2.1.9-insider. Can you please verify :-)
