### ISSUE TITLE
Test notebook workspace edit API

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#107622]
Refs: #105283

- [x] anyOS @lszomoru
- [x] anyOS @alexr00

Complexity: 4

Authors: @jrieken @rebornix 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23107622%0A%0A)

---

We have made good progress with notebook editing API (including changes to the `d.ts` and also internal infrastructure). Now changes from UI or extensions will all land in the same code path `NotebookTextModel.applyEdits` so we want to test how robust the API and the implementation is.

_Interface_
```ts
export interface WorkspaceEdit {
  replaceNotebookMetadata(uri: Uri, value: NotebookDocumentMetadata): void;
  replaceNotebookCells(uri: Uri, start: number, end: number, cells: NotebookCellData[], metadata?: WorkspaceEditEntryMetadata): void;
  replaceNotebookCellOutput(uri: Uri, index: number, outputs: (NotebookCellOutput | CellOutput)[], metadata?: WorkspaceEditEntryMetadata): void;
  replaceNotebookCellMetadata(uri: Uri, index: number, cellMetadata: NotebookCellMetadata, metadata?: WorkspaceEditEntryMetadata): void;
}
```

To test this set of API:

* Install GH Issue Notebook extension
* Create `test.github-issues` notebook file
* Create an extension with proposed api (https://github.com/microsoft/vscode-extension-samples/tree/master/proposed-api-sample)
* Register commands which can apply workspace editors, for example

```ts
subscriptions.push(vscode.commands.registerCommand('github-issues.testLockCell', async () => {
	const editor = vscode.notebook.activeNotebookEditor;
	if (!editor) {
		return;
	}

	const selection = editor.selection;
	if (!selection) {
		return;
	}

	const workspaceEdit = new vscode.WorkspaceEdit();
	workspaceEdit.replaceNotebookCellMetadata(editor.document.uri, selection.index, {
		...selection.metadata,
		editable: false
	});

	await vscode.workspace.applyEdit(workspaceEdit);
}));

```
* and then run the command in a GitHub issue notebook file

Please test at least following scenarios 

* Insert/Delete/Replace cells
* Update cell outputs
* Update cell metadata
* Undo/Redo after workspace edits
* Performance (e.g., https://github.com/microsoft/vscode/issues/107613)

**Comment by alexr00** [comment]
I tested the following:
- Delete/Replace cells
- Update cell outputs
- Update cell metadata
- Undo/Redo after workspace edits
- Performance (e.g., #107613)

I used this API to replace and delete cells:
https://github.com/Microsoft/vscode/blob/4482c8794fa5e6b77ae08be69784352b8cde32ea/src/vs/vscode.proposed.d.ts#L1437-L1437

I could not find a way to delete cells.

**Comment by rebornix** [comment]
@alexr00 to insert a cell you can

```
workspaceEdit.replaceNotebookCells(editor.document.uri, 0, 0, [
{
  cellKind: vscode.CellKind.Code,
  language: 'github-issues',
  metadata: {},
  outputs: [],
  source: 'test'
}
]);
```
