### ISSUE TITLE
Pinned tabs - last pinned border is stale

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#107675]
Testing #107464

Repro steps:
* Set `tab.lastPinnedBorder` to a particular color
* Open three tabs in the editor with the following states:
  - file1 (pinned)
  - file2 (pinned)
  - file3 (not pinned)
* Last pinned border will be displayed on the right side of file2
* Focus file3, and pin it
  - Last pinned border will now show on the right side or file2 and file3
  - Focusing file2, will remove the last pinned border on the right side of file2
* Focus file3, and unpin it
  - Last pinned border will be removed from the right side of file3 but not shown on the right side of file2
  - Focusing file2, will display the last pinned border on the right side of file2

**Comment by bpasero** [comment]
Great catch, whenever pinned tabs change I was only updating the editor that changed, but not the others. Since the border can be on other pinned tabs, I am now going over all tabs to ensure the border is updated properly.
