### ISSUE TITLE
Debug sessions fail to start for some users after switching to DebugAdapterDescriptorFactory/out of process DA

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#107658]
In the last release of the Dart extension, I switched to using a `DebugAdapterDescriptorFactory` and running the debug adapter out-of-process rather than in-process.

Everything works fine for me (and I suspect, most users) but some users (@dominikheeb in https://github.com/Dart-Code/Dart-Code/issues/2782 ~and @moseskarunia in https://github.com/Dart-Code/Dart-Code/issues/2819~) have reported that debug sessions no longer start, with no clear obvious reason why.

In the logs written by the extension we see:

```
[8:17:14 AM] [General] [Info] Running debugger via node with /Users/***/.vscode/extensions/dart-code.dart-code-3.15.0-dev.3/out/dist/debug.js    flutter
```

This comes from this code at the bottom of the `DebugAdapterDescriptorFactory.createDebugAdapterDescriptor`:

```
const args = [this.extensionContext.asAbsolutePath(debugAdapterPath), debuggerName];
this.logger.info(`Running debugger via node with ${args.join("    ")}`);
return new DebugAdapterExecutable("node", args);
```

So it seems like the correct `DebugAdapterExecutable` is being created and returned to VS Code, but it's not clear why the debug session never starts. I can't reproduce it myself (I'm on macOS, the same as both users) and it's not clear how to get any more info from VS Code to debug this. Could anyone provide pointers on where to start (is there logging we can turn on? or somewhere that would be useful to breakpoint?).

**Comment by isidorn** [comment]
Since this is not reproducable, leaving this assigned to Andre so he can investigate more once he is back.

**Comment by DanTup** [comment]
I made a build of my extension that logged to a file in the temp folder immediately at start and @dominikheeb tested it, but it appears to have not created the file. This makes it seem like the debug adapter is definitely not starting (or, it's throwing while it does).

I'm not sure how to debug this further (since I can't reproduce it). An instructions that @dominikheeb could follow to try and understand where its failing would be appreciated. Thanks!

**Comment by weinand** [comment]
@DanTup in your initial comment you said:
> In the last release of the Dart extension, I switched to using a DebugAdapterDescriptorFactory and running the debug adapter out-of-process rather than in-process.

What do you mean by "running the DA in-process"?

You are now using a "DebugAdapterDescriptorFactory" and I was under the assumption that previously you had statically declared the path to your DA in the package.json, correct?

**Comment by DanTup** [comment]
> You are now using a "DebugAdapterDescriptorFactory" and I was under the assumption that previously you had statically declared the path to your DA in the package.json, correct?

Previously we started the DA server in-process in the extension host. This was done a long time go to work around another issue (it was suggested at https://github.com/microsoft/vscode/issues/45220#issuecomment-373384356).

We now use `DebugAdapterDescriptorFactory`, but for @dominikheeb it appears that the DA process is never started (it's not clear if it's not being attempted, or an error is occurring while it tries to run it - but running the script manually from node appears to run the process as expected).

So I think something may be going wrong between us returning from the `DebugAdapterDescriptorFactory` and the debug adapter process/script starting - though it's not clear how to debug that. It doesn't seem like there are any visible error messages, though the session also doesn't start.

**Comment by dominikheeb** [comment]
i also discovered another issue, which could be related to the issue.

When i open a Typescript Project in the bottom left is a spinner with the text 'Initializing JS/TS language features'.
This spinner never completes and i am also missing features in typescript files like intellisense.

**Comment by DanTup** [comment]
The other instance of this I had reported turned out to be unrelated, so @dominikheeb is the only instance of this I know of - perhaps he can confirm if this is still a problem. Based on the last comment above, it sounds like it might be node processes failing to start, though I'm not sure how to debug that.

**Comment by dominikheeb** [comment]
Hey
Thank you for still looking into the issue.
Since it really blocked efficient debugging and work on ts projects as well as on flutter projects, i reseted my macbook to factory state.

Reinstalling the whole system and all tools solved the issue.
Hopefully it will not come up again.

**Comment by DanTup** [comment]
I guess we should close this then as there's nothing to debug. Glad you managed to get it working, though shame it required such a drastic fix!

**Comment by weinand** [comment]
Thanks!
