### ISSUE TITLE
Unable to open file via context menu from other applications (Linux) 

### ISSUE THREAD

**Issue by albertsmus** [Microsoft/vscode#10761]
- VSCode Version:1.4
- OS Version:Ubuntu 16.04

Steps to Reproduce:
1. Using FireFtp installed on Mozilla. I can't open a local file which containing folder's name is in non latin characters.

**Comment by bpasero** [comment]
@albertsmus can you share some screenshots or video how this looks like?

**Comment by albertsmus** [comment]
![vscodevia fireftp](https://cloud.githubusercontent.com/assets/4593565/17848818/44eaef6e-685e-11e6-8faf-ebaa51fd2bcc.png)
![fireftplocalfile](https://cloud.githubusercontent.com/assets/4593565/17848819/44f3d00c-685e-11e6-9299-3328f277099d.png)
![vscode_localfile](https://cloud.githubusercontent.com/assets/4593565/17848820/44f5a012-685e-11e6-8a55-20f1c618e2ea.png)
The vscode_localFile is the screenshot for  file opened through the VsCode and selecting open folder and after the file. That's Ok
On fireFtpLocalFile file i show you the way how i open the file via mozilla's fireftp and finally the third file (vscodevia fireftp) is the screenshot from vs Code where you can see that there is an error to the path of file and so there are no contents in the file.

**Comment by bpasero** [comment]
@albertsmus so this issue is about the errors in the editor around the "include"?

**Comment by albertsmus** [comment]
No the isssue is when i try to open a file using the context menu (right click on a file and open with Visual Studio Code) i the file with no contents in. The same issue is when i use Fire ftp from mozilla and i try to open a local file. 
When i open the file via the open menu from visual studio code the file open's with it's contents in.

**Comment by bpasero** [comment]
@albertsmus using the context menu on the native Ubuntu file explorer you mean? Or is that another tool besides the Fire FTP?

**Comment by albertsmus** [comment]
Inside the native Ubuntu file explorer

**Comment by albertsmus** [comment]
But also from Fire Ftp

**Comment by bpasero** [comment]
@albertsmus can you try with a file in a folder that uses ASCII characters? from the screenshot it almost looks like an encoding issue with the folder name where Cars.php is in.

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by albertsmus** [comment]
Sorry for the delay. No the problem is the same with ascii characters also. Ihave to mention that 
![screenshot with 3 diff editors](https://cloud.githubusercontent.com/assets/4593565/18223409/9417ac3e-71bf-11e6-89ab-45560a695437.png)
Bluefish editor or sublime text 2 open the file as you see at the screenshot i post below.

**Comment by bpasero** [comment]
@albertsmus could you try if this is solved with our latest insider update, we pushed quite some changes:

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by albertsmus** [comment]
No it's not working again. I have to tell you also that as in the previous version now also ig i try to close the file that it seems that there is no code inside i get a warniong if i want to save the file or not. (i attach the screenshot)
![screen 2016-09-18 10-55-00](https://cloud.githubusercontent.com/assets/4593565/18614029/bc915e50-7d8e-11e6-9c9a-6f475423e416.png)
