### ISSUE TITLE
Clarify that presentation properties of code action should not change

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107653]
Testing #107586

> Clients signal this through the codeAction.resolveSupport capability which list all properties a client can resolve lazily

The sentence a little lax IMO because when resolving a code action it is usually showing in the UI and changing presentation properties, like title or kind, would be then be false.

**Comment by dbaeumer** [comment]
That is true for us but doesn't need to be the case for other clients (they might refresh the UI). This is why our client only flags the `edit` property. Do you suggest that we don't allow this at all?

**Comment by jrieken** [comment]
Yeah, I'd say it doesn't make sense to resolve a code action into something completely different

**Comment by dbaeumer** [comment]
OK. Will add a sentence.

**Comment by dbaeumer** [comment]
Added 

> It should also be noted that servers shouldn't alter existing attributes of a code action in a `codeAction/resolve` request.
