### ISSUE TITLE
Different markup usage

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107654]
Testing #107586

It seems that usually things like "Since version x.y.z" is printed italics but not for this instance

<img width="369" alt="Screenshot 2020-09-29 at 09 58 52" src="https://user-images.githubusercontent.com/1794099/94529760-6ae9d480-023a-11eb-972a-36968423e509.png">

**Comment by dbaeumer** [comment]
Good catch. Will fix it.

**Comment by dbaeumer** [comment]
Done.
