### ISSUE TITLE
marketplace disappear

### ISSUE THREAD

**Issue by NightOfTwelve** [Microsoft/vscode#10768]
- VSCode Version:1.4
- OS Version:win7 

Steps to Reproduce:

1. it doesn't display marketplace,but in my colleague computer,everything is ok.I don't know why.
![image](https://cloud.githubusercontent.com/assets/7830412/17841970/9a8b66c8-6850-11e6-96d1-3ebef40835c4.png)

**Comment by joaomoreno** [comment]
Are you behind a proxy? Look into the `http.proxy` and `http.proxyStrictSSL` settings.

**Comment by NightOfTwelve** [comment]
that's sloves my problem,thanks
