### ISSUE TITLE
Issues with Backspace in Codespaces on Android (Surface Duo)

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#107602]
Version: 1.50.0-insider
Commit: 403a6895f401c397933ec5c4f7d89432a33509b6
Date: 2020-09-18T05:28:58.063Z
Browser: Mozilla/5.0 (Linux; Android 10; Surface Duo) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36 EdgA/45.09.62.5078

Steps to Reproduce:

1. Open Codespaces in a browser on Android (for me, I used Surface Duo) 
2. type in the editor and hit `backspace` key

## In the editor pane

In the editor pane you expect it to delete the last character

Instead, _it does nothing_. Here the input:

![Screenshot_20200927-214627.png](https://user-images.githubusercontent.com/2644648/94455964-3e658800-0168-11eb-8bf0-ffdf9e30c4d4.png)

NOTE: This appears to be a Monaco bug as the samples on the Monaco website have the same problem.

## In the terminal

In the terminal you expect it to delete the last character on the prompt

I typed "asdf" and then backspace rather than doing nothing or deleting anything...

It adds an extra "asd" to my prompt (so I now have "asdfasd"). Then I hit backspace again... It adds "as" to my prompt (so I now have "asdfasdas")... Backspace again adds an "a" (so now "asdfasdasa".... Backspace again and this time it does nothing.... Backspace one more time and it actually starts working.

Here's the input next to codespaces:
![Screenshot_20200928-081010.png](https://user-images.githubusercontent.com/2644648/94456990-d3688100-0168-11eb-9eee-b64f548ec15a.png)

I've seen very similar behavior in Azure Cloud Shell in the Azure Mobile App so I have a feeling the terminal bug is in xterm.js.

Feel free to reach out if you want me to give something a try! 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
This is probably because you're using an on screen keyboard. It's probably a tricky problem for the terminal which is why https://github.com/xtermjs/xterm.js/issues/1101 hasn't been solved yet.

**Comment by TylerLeonhardt** [comment]
I believe it's tricky :/ one clarification, I also tried using a bluetooth keyboard and got the same result.

**Comment by rebornix** [comment]
Forgot that we already had an old issue in Monaco-editor https://github.com/microsoft/monaco-editor/issues/1538

**Comment by TylerLeonhardt** [comment]
UPDATE: I switched to GBoard from SwiftKey to see if that has any change (SwiftKey is the default installed keyboard because Microsoft :) ) and GBoard actually _WORKS_... both in the terminal and in the editor...

The only thing that didn't work in my minimal testing was backspace on an empty line did not delete the line.

**Comment by Pictor13** [comment]
Wow that's great to hear, that there maybe a temporary working solution with alternative keyboards.
However I wanted to add that for me, connecting a keyboard via USB, with an adapter, was working perfectly (since the virtual keyboard doesn't appear and, I guess, is not used at all).

**Comment by alexdima** [comment]
The editor should now work fine via 20f3ece2e09f86f6a81858cb6e627e1a7afd4422

**Comment by TylerLeonhardt** [comment]
@alexdima nice! When might I be able to give this a spin?

**Comment by alexdima** [comment]
@TylerLeonhardt With the next insiders or right now if you can run from master. I hope things will work with a real device, I have been using an Android emulator to implement this...

**Comment by TylerLeonhardt** [comment]
I no longer have this phone to try this out :(

**Comment by alexdima** [comment]
This could have also improved with https://github.com/microsoft/vscode/pull/124288
