### ISSUE TITLE
Debug hover doesn't come back

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107667]
Testing #107156

* debug an extension
* hover over an element, debug hover shows
* press `alt`, TS hover shows
* :bug: release `alt`, TS hover still shows

![Sep-29-2020 11-42-50](https://user-images.githubusercontent.com/1794099/94542324-f23e4480-0248-11eb-90d1-190903521bdb.gif)

**Comment by isidorn** [comment]
Thanks for feedback. Originaly `alt` would always toggle. however we got explicit feedback from Java team here https://github.com/microsoft/vscode/issues/84561#issuecomment-694743958
Which I agree with, when reading a long Javadoc you do not want to hold `alt` down all the time.

Anyways let's keep this open and if we get more feedback I would be open to change it back that `alt` aggressivly toggles, but for now will stick with the current behavior.
