### ISSUE TITLE
Wrong indentation of JS/TS - return of object with methods

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#10765]
- VSCode Version: insiders
- OS Version: window 10

Seems to be wrong indentation of JS/TS in case of return of object with methods:
![image](https://cloud.githubusercontent.com/assets/736697/17840407/21d8415e-6820-11e6-8873-912ff9d8df8b.png)
Should be (I believe):
![image](https://cloud.githubusercontent.com/assets/736697/17840408/421a5f06-6820-11e6-8ff8-c7467cf48379.png)

this is actually to inccorrect
![image](https://cloud.githubusercontent.com/assets/736697/17840698/5d892dce-6827-11e6-9bef-2a8bcfff533d.png)

**Comment by whitecolor** [comment]
This seem to be to incorrect indentation
![image](https://cloud.githubusercontent.com/assets/736697/17840475/062ba26e-6822-11e6-9f37-583b06571f8a.png)

it seems that it should be:
![image](https://cloud.githubusercontent.com/assets/736697/17840478/14f08e68-6822-11e6-8187-ec67c6a5cdef.png)

**Comment by waderyan** [comment]
Can you help me in recreating this? 

1. Paste some simple code that demonstrates the issue. I will open a new window and paste the code in. 
2. Describe the exact steps you took to see the issue (i.e. select entire code block, right click, select Format Code)

I will do the steps on my machine to confirm it is reproducible.

**Comment by whitecolor** [comment]
1) Well insert do this: `const functionWithParamsOnNextLine = (params) => { }`
2) Go with cursor before `(params)` and press enter
```js
const functionWithParamsOnNextLine = 
(params) => { }
```

It actually fixes indentation it after explicit formatting it with `Alt+Shift+F`, didn't know about it, but I would prefer automatic correct code formatting.

**Comment by whitecolor** [comment]
Actually editor option that I just became aware of `editor.formatOnType: true` solves this
