### ISSUE TITLE
ESLint status bar item shows even for files it doesn't apply to

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#107694]
Testing https://github.com/microsoft/vscode/issues/107584

I approved ESLint globally (allow everywhere).
![image](https://user-images.githubusercontent.com/38270282/94561854-e3fe2180-0264-11eb-953e-f8b6b2528de8.png)

Based on this, I expect the ESLint status bar item to only show on files that ESLint applies to:
> if the execution is approved the ESLint status icon should only be visible when the active editor contains a document that is validated using ESLint.

I have tried opening the following files, and the status bar item shows for all of them:
yarn.lock
ThirdPartyNotices.txt
delete.svg

**Comment by dbaeumer** [comment]
That is on purpose. The reason is that users are aware of the fact that they are in the `Allow everywhere` mode. Otherwise there is no indication that they trust something without being ask. I will make this clear in the test item.

**Comment by dbaeumer** [comment]
Update test item.
