### ISSUE TITLE
Web: high contrast and color scheme not detected on macOS

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107668]
Testing #106389

Works fine on Windows though.

**Comment by aeschli** [comment]
@bpasero Chrome and/or Edge? Does the `Forced Colors` setting work?

On Windows, only Edge has the autodetect behavior enabled where the HC mode triggers the experimental forced colors feature. OSX has no single 'high contrast' configuration setting, it will have to been seen what the browsers will end up doing. Maybe `Inverse colors` will be linked to `Forced colors`?

I would say that will be in the hands of the browsers, so I'd close the issue for now and we will continue to observe how the browsers evolve.

**Comment by bpasero** [comment]
This was Edge on macOS with Forced Colors enabled.

**Comment by aeschli** [comment]
Closing as this will be up to the browsers to define how they connect the OS scheme to the browser modes.
