### ISSUE TITLE
Titlebar screen cheese 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107647]
* make changes to a git tracked notebook
* open diff editor
* switch diff editor to text-diff mode
* 🧀 the title bar isn't pretty

<img width="1365" alt="Screenshot 2020-09-29 at 09 04 51" src="https://user-images.githubusercontent.com/1794099/94524441-e5aef180-0232-11eb-85a3-afbcf2d2d073.png">

**Comment by bpasero** [comment]
@jrieken did this get worse recently, e.g. compared to stable?

**Comment by jrieken** [comment]
idk - cannot use notebooks in stable

**Comment by bpasero** [comment]
@jrieken share your setting for `window.title`

**Comment by jrieken** [comment]
Not customised, the only thing that gets close is `"window.titleSeparator": " 🚴",`

**Comment by bpasero** [comment]
@jrieken weird, I get this:

Working Area:
![image](https://user-images.githubusercontent.com/900690/94539332-61199e80-0245-11eb-8aa8-247c740dcd9a.png)

Staged:
![image](https://user-images.githubusercontent.com/900690/94539372-6d9df700-0245-11eb-8136-3b9056404768.png)

**Comment by jrieken** [comment]
You aren't doing step 3 "switch diff editor to text-diff mode"

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/blob/20e9b0b78f3b6e3f58231d870812a51c77897024/src/vs/workbench/contrib/notebook/browser/diff/notebookDiffActions.ts#L46-L46

😱

**Comment by rebornix** [comment]
Interesting I was using the fallback used by text diff editor 

https://github.com/microsoft/vscode/blob/01f9355f655710c10c356ebae66b8070bbfa0566/src/vs/workbench/api/browser/mainThreadEditors.ts#L352

but maybe it's never used as git always provides a label.

**Comment by bpasero** [comment]
@rebornix yeah that label does not look too god, @jrieken unless you have objections I would change it to something like this:

https://github.com/microsoft/vscode/blob/db674322687bbfc592402e1bebdcf91f39b30c1a/src/vs/workbench/services/editor/browser/editorService.ts#L982-L982

**Comment by bpasero** [comment]
@rebornix we are down to just this case now:

https://github.com/microsoft/vscode/blob/6558e439b340e248061a7143573593aab1ed6bea/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L129-L129

Not sure this still applies, but such a label is never good imho, so I would not present it to the user.

**Comment by rebornix** [comment]
@bpasero thanks, they are for old workspaces which don't have `textDiffName` in memento yet. Once the release is out and most users update to it, we can remove the fallback.
