### ISSUE TITLE
Launching VSCode in Ubuntu in a 2nd desktop/workspace always assigns the new window to the first desktop

### ISSUE THREAD

**Issue by davidwendt** [microsoft/vscode#107607]
- VSCode Version: 1.49.2
- OS Version: Ubuntu 18.04

Steps to Reproduce:
(make sure no current instances of vscode are running)
1. From Ubuntu desktop click on the Activites button in the upper-left and select workspace 2
2. Open a terminal window and navigate to any appropriate directory.
3. Execute `code .` from this directory to launch vscode. The vscode window should appear as normal in the ubuntu desktop/workspace.
4. Click on the Activities button again to switch back to workspace 1
5. Open a terminal window and navigate to a different directory.
6. Execute `code .` from this directory and it will switch to the 2nd desktop/workspace and show the vscode window there.

This broke just recently though I don't know which version specifically introduced this failure.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/106727

This is fixed with latest insiders and will be fixed in the next stable release.
