### ISSUE TITLE
Pressing enter twice on Files Exclude or Files Associations setting should add new item

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#107746]
Testing #107610

- Navigate using down arrow until Files: Exclude settings is selected
- Press Enter - Patterns box is selected
- Press Enter again

🐛 nothing happens. 

Expected that new item is added, just like in drop down control - drop down is opened.

**Comment by roblourens** [comment]
I think we decided that empty patterns can't be added because that was probably a mistake. If I add one character, then press enter, the pattern is added
