### ISSUE TITLE
vscode file build: top menu doesn't seem to work

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#107730]
Testing #107466

Ubuntu

None of the entries on the top menu seem to work (Edit->Undo, for example)

Nothing logged to console

**Comment by bpasero** [comment]
@JacksonKearl I cannot really reproduce this issue, can you try again? Does it make a difference when you use native menu vs custom menu?

**Comment by JacksonKearl** [comment]
Can no longer reproduce. Might have been a VM thing.
