### ISSUE TITLE
Leaving and entering the gear action of a setting using tab and shift tab is not announcing the name of the setting

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#107743]
Testing #107610

- Tab until you reach the gear action of a setting
- Tab now - it goes to activity bar switcher (explorer) button for me
- Shift + Tab now 

Voice over announces following

<img width="637" alt="image" src="https://user-images.githubusercontent.com/10746682/94609250-c51c8100-029e-11eb-88f2-1e94b9f1280c.png">

<img width="655" alt="image" src="https://user-images.githubusercontent.com/10746682/94609187-b2a24780-029e-11eb-8afc-2e041767b9c6.png">

It does not announce on which setting this `More Actions...` button is for.

**Comment by roblourens** [comment]
I don't want to add the setting name to this just because it happens to be the last focusable element in the row. If the user presses escape to focus the row or does anything else then they will figure out where they are.
