### ISSUE TITLE
treeView description doesn't persist when layout is changed

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#107752]
Testing #107639

![recording (6)](https://user-images.githubusercontent.com/9721254/94617448-950db780-0277-11eb-960d-15da880fe3bf.gif)

**Comment by eamodio** [comment]
@sana-ajani can you still reproduce this on today's insiders? I think @sbatten made some changes to the views and I think it fixed this.

**Comment by sana-ajani** [comment]
Yeah, I still see this in the latest Insiders `(commit: 0ecb64a...)`.
