### ISSUE TITLE
Updated MacOS Exploration build

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#107757]
Issue Type: <b>Feature Request</b>

Is there an update for the MacOS Exploration build available? The Windows build is up to 1.50.0, with a recent date. MacOS is dated back in August.

VS Code version: Code - Exploration 1.49.0-exploration (16616bb90b4b083b9a4d22d7fcd35b565e42d4d6, 2020-08-14T06:30:44.371Z)
OS version: Darwin x64 19.6.0

**Comment by deepak1556** [comment]
New version has been released, please check. Thanks!
