### ISSUE TITLE
[decorators] Decoration types break each other

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#10774]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

Steps to Reproduce:

- Create an extension with the following code
```javascript
  let vscode = require('vscode');
  let window = vscode.window;

  let decorationTypeOne = window.createTextEditorDecorationType({
    isWholeLine: true, // not relevant, but present in the real-world scenario
  });
  let decorationTypeTwo = window.createTextEditorDecorationType({
    color: 'green'
  });

  let decorationWithContent = {
    range: new vscode.Range(0, 0, 0, 3),
    renderOptions: {after: {contentText: '+test'}}
  };

  let decorationWithColor = {range: new vscode.Range(0, 1, 0, 2)};

  window.activeTextEditor.setDecorations(decorationTypeOne, [decorationWithContent]);
  window.activeTextEditor.setDecorations(decorationTypeTwo, [decorationWithColor]);
```
- Open a text file with a single line `abc` in it.
- The result is a duplicated `contentText` inserted in a middle of the text.

<img width="188" alt="screen shot 2016-08-22 at 2 16 59 pm" src="https://cloud.githubusercontent.com/assets/979966/17843609/53ec5f38-6873-11e6-9433-cc2973558904.png">

Note if you remove `color: 'green'` from the second decoration type, then it works as expected:

<img width="122" alt="screen shot 2016-08-22 at 2 25 16 pm" src="https://cloud.githubusercontent.com/assets/979966/17843692/4ed1046c-6874-11e6-9db7-2dde0d57fe47.png">

Real-world scenario was reported [in wallaby.js repo](https://github.com/wallabyjs/public/issues/751#issuecomment-241301408) where decorations inserted by wallaby are broken when [Rainbow Brackets](https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets) extension is also used, which simply adds colours to certain ranges.

**Comment by aeschli** [comment]
I will investigate. 

As a workaround you can try to make the range of the decoration smaller.

**Comment by ArtemGovorov** [comment]
Thanks!

> As a workaround you can try to make the range of the decoration smaller.

This doesn't seem to help. I tried to reduce the wallaby decoration range down to 1 character, still the same. 

If it helps, here's how the generated HTML for the provided sample looks like:

![screen shot 2016-08-22 at 5 02 49 pm](https://cloud.githubusercontent.com/assets/979966/17846212/9843533c-688a-11e6-810b-11fc175e8c9e.png)

For some reason, an empty `token` is inserted in a middle of the line.
