### ISSUE TITLE
Upper bound on time configuration values

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107798]
Similar to the lower bound of 500ms you should consider an upper bound. Also, some nice time formatting, like "5.5hrs" instead of "xyz seconds"

<img width="1254" alt="Screenshot 2020-09-30 at 11 09 30" src="https://user-images.githubusercontent.com/1794099/94666252-883ba300-030d-11eb-9541-970ffb3aa245.png">
Testing #107623

**Comment by gjsjohnmurray** [comment]
Also just spotted the "Visaulizer" typo in that screenshot.
