### ISSUE TITLE
Unable to create empty git commit if there are any changed files

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#107753]
While testing https://github.com/microsoft/vscode/issues/105881 I noticed a case:

1. Change a file (but do not stage it)
1. Run `Git: Commit Empty`
1. Say that you're sure you want to create an empty commit
1. You're presented with this screen. There's no way to get past it and create an empty commit without stashing/discarding local changes 🐛 

![](https://memes.peet.io/img/20-09-8768b030-acde-4d0e-a408-964c8c04e95c.png)

**Comment by hunghw** [comment]
I would like to give this a try.

**Comment by luucamay** [comment]
Hello, I will try to solve this one

**Comment by luucamay** [comment]
We should be able to create an empty git commit with out stashing local changes?

**Comment by connor4312** [comment]
Yep, that's right. Creating an empty commit should not trigger the "no staged changes" dialog at all, since the user already said they want to create a commit with nothing in it.

**Comment by vivekmthr** [comment]
Hey! Even though hunghw has already issued a pull request I wanted to give it a try as well. To replicate, how exactly do you run git:commit empty, I'm currently not getting a dialog which asks if I'm sure I want to make an empty commit? I am only able to run git commit, at which point I see the dialog box mentioned above.

**Comment by connor4312** [comment]
Open the command palette (ctrl+shift+p, or F1) and type "commit empty"

![](https://memes.peet.io/img/20-10-80dae706-0096-4d29-a3e5-68906c357c34.png)
