### ISSUE TITLE
Errors in webview view sample webview script

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#107732]
Testing #107626

I know these are harmless but it would be good for a sample to show people how to set this up without errors

![image](https://user-images.githubusercontent.com/323878/94595421-ac30b300-023f-11eb-8942-c3eee82636b1.png)

**Comment by usernamehw** [comment]
Similar to https://github.com/microsoft/vscode-extension-samples/issues/342

Looks like no one is assigning issues in that repository.

**Comment by mjbvz** [comment]
Duplicate of #96221

**Comment by roblourens** [comment]
Thanks @usernamehw we will clean that up next month
