### ISSUE TITLE
Debug viewlet doesn't show configurations

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#107728]
- I opened the `webview-view-sample` folder for the first time (https://github.com/microsoft/vscode/issues/107626)
- It has a launch.json but the debug viewlet shows the experience for workspaces with no launch config

![image](https://user-images.githubusercontent.com/323878/94592235-be115680-023d-11eb-93f2-0ea1c5e65c34.png)

I see this error, dunno if related

![image](https://user-images.githubusercontent.com/323878/94592283-c5d0fb00-023d-11eb-9cce-8d7451550421.png)

**Comment by roblourens** [comment]
I could only debug through the command palette (`debug ` quick access)

**Comment by isidorn** [comment]
@roblourens thanks for filling this. However I could not reproduce. I tried openeing the webview-view-sample both from Insiders and from out of source and can not repro.

I pushed a fix looking at the error stack, thanks for that!
