### ISSUE TITLE
Unable to update via apt : mirror sync in progress ?

### ISSUE THREAD

**Issue by atmaniak** [microsoft/vscode#107793]
Since a few days i can't update vscode via apt update

- OS Version: Ubuntu 20.04

`E: Failed to fetch https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (201047 != 200914). Mirror sync in progress? [IP: 13.66.3.153 443]
   Hashes of expected file:
    - Filesize:200914 [weak]
    - SHA512:a91d388504b56c875620f73b618813be1c127d6bfe96406cc6e9a39fdf33f1dd2c8ecbda4a636f0c86bc18005e4f5d0683da0c02ba13c555cef8d11eb83412fe
    - SHA256:1d39334cb2779572dd17869a05d3ed3f1d57992cc9755a34a4d2622132b19f57
    - SHA1:d5224a98d6adfb4ab65d66aa803f9688a6503080 [weak]
    - MD5Sum:2fc601c3aa23f067ef305bfb7f7086e7 [weak]
   Release file created at: Mon, 28 Sep 2020 06:53:06 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by nichitapavel** [comment]
Same here, ubuntu version as @atmaniak, region Tenerife/Spain.

**Comment by bendeg** [comment]
Same issue here since this morning on 2 debian systems :  Debian GNU/Linux 9.13 (stretch), and the second one is a Debian buster

Réception de:8 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [201 kB]
Err:8 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages
  Writing more data than expected (201047 > 200914)
  Hashes of expected file:
   - Filesize:200914 [weak]
   - SHA512:a91d388504b56c875620f73b618813be1c127d6bfe96406cc6e9a39fdf33f1dd2c8ecbda4a636f0c86bc18005e4f5d0683da0c02ba13c555cef8d11eb83412fe
   - SHA256:1d39334cb2779572dd17869a05d3ed3f1d57992cc9755a34a4d2622132b19f57
   - SHA1:d5224a98d6adfb4ab65d66aa803f9688a6503080 [weak]
   - MD5Sum:2fc601c3aa23f067ef305bfb7f7086e7 [weak]
  Release file created at: Mon, 28 Sep 2020 06:53:06 +0000
142 ko réceptionnés en 0s (232 ko/s)                        
Lecture des listes de paquets... Fait
E: Impossible de récupérer http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  Writing more data than expected (201047 > 200914)
   Hashes of expected file:
    - Filesize:200914 [weak]
    - SHA512:a91d388504b56c875620f73b618813be1c127d6bfe96406cc6e9a39fdf33f1dd2c8ecbda4a636f0c86bc18005e4f5d0683da0c02ba13c555cef8d11eb83412fe
    - SHA256:1d39334cb2779572dd17869a05d3ed3f1d57992cc9755a34a4d2622132b19f57
    - SHA1:d5224a98d6adfb4ab65d66aa803f9688a6503080 [weak]
    - MD5Sum:2fc601c3aa23f067ef305bfb7f7086e7 [weak]
   Release file created at: Mon, 28 Sep 2020 06:53:06 +0000
E: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.

**Comment by mustafapc19** [comment]
Same ubuntu version 20.04, region: India

**Comment by haomingw** [comment]
same issue for Ubuntu 20.04. region: France

**Comment by Malanius** [comment]
Same on Ubuntu 20.04.1, region: Czech

**Comment by TomGrooves** [comment]
Same issue here. Elementary OS 5.1.7 (hera), region: Denmark

**Comment by TheZoker** [comment]
Duplicate of: https://github.com/microsoft/vscode/issues/107773

**Comment by minemax-ua** [comment]
The same issue. Debian Bullseye.

**Comment by kirafadhil** [comment]
same issue on eos 5.1.7 hera

**Comment by jozsefk9** [comment]
Same issue here. KUbuntu 20.04.1. Region: Serbia.
`E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (201420 != 200914). Mirror sync in progress?`

**Comment by minemax-ua** [comment]
Well, it looks like it's fixed now. :)

**Comment by KushalSM** [comment]
Yes for sure...
Same problem:
Zorin OS 15.3, India

**Comment by chrmarti** [comment]
This works for me (connecting from Switzerland).

@KushalSM Could you retry? This might take some time to reach all regions.

**Comment by chrmarti** [comment]
Checked with the repo team. This was fixed almost 5 hours ago. Anyone still seeing this, please let us know.

**Comment by kirafadhil** [comment]
> same issue on eos 5.1.7 hera
this fixed on this morning

**Comment by bendeg** [comment]
Restored (debian buster). Thanks !

**Comment by atmaniak** [comment]
Back to normal !

**Comment by KushalSM** [comment]
@chrmarti 

Hey its all fine now. Thx.
Cheers!!!

**Comment by issart** [comment]
Hello.
The same issue now.
```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

### Error:
```
Get:15 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [204 kB]
Err:15 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages
  File has unexpected size (203820 != 203585). Mirror sync in progress? [IP: 40.114.136.21 80]
  Hashes of expected file:
   - Filesize:203585 [weak]
   - SHA512:070b1469cbfcc74fbe83b5b8bd1af9707f9f0ad520d4bf161340532c8bec4fd31812cf9242a81fe54e805837495281bcece1edb925104ff817191e068970863c
   - SHA256:7e6635480cc4a9463de3167215ad504c8721bd43d9c40b4ad71b44f60380757d
   - SHA1:9baf9b98b78b41be5c361ba7825f016e1abd31d2 [weak]
   - MD5Sum:f509c48fcb219ac06f64fbec78be0dd5 [weak]
  Release file created at: Thu, 15 Oct 2020 18:21:44 +0000
Fetched 10,6 kB in 1s (8 524 B/s)
Reading package lists... Done
E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (203820 != 203585). Mirror sync in progress? [IP: 40.114.136.21 80]
   Hashes of expected file:
    - Filesize:203585 [weak]
    - SHA512:070b1469cbfcc74fbe83b5b8bd1af9707f9f0ad520d4bf161340532c8bec4fd31812cf9242a81fe54e805837495281bcece1edb925104ff817191e068970863c
    - SHA256:7e6635480cc4a9463de3167215ad504c8721bd43d9c40b4ad71b44f60380757d
    - SHA1:9baf9b98b78b41be5c361ba7825f016e1abd31d2 [weak]
    - MD5Sum:f509c48fcb219ac06f64fbec78be0dd5 [weak]
   Release file created at: Thu, 15 Oct 2020 18:21:44 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Fire-Dragon-DoL** [comment]
Same issue, Ubuntu 18.04.5 LTS:

```
E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (203820 != 203585). Mirror sync in progress? [IP: 13.93.152.112 80]
   Hashes of expected file:
    - Filesize:203585 [weak]
    - SHA512:070b1469cbfcc74fbe83b5b8bd1af9707f9f0ad520d4bf161340532c8bec4fd31812cf9242a81fe54e805837495281bcece1edb925104ff817191e068970863c
    - SHA256:7e6635480cc4a9463de3167215ad504c8721bd43d9c40b4ad71b44f60380757d
    - SHA1:9baf9b98b78b41be5c361ba7825f016e1abd31d2 [weak]
    - MD5Sum:f509c48fcb219ac06f64fbec78be0dd5 [weak]
   Release file created at: Thu, 15 Oct 2020 18:21:44 +0000

```

**Comment by mehulboricha** [comment]
Still having problems. Location: India

`Err:6 https://packages.microsoft.com/repos/vscode stable/main amd64 Packages
  File has unexpected size (203820 != 203585). Mirror sync in progress? [IP: 20.188.102.6 443]
  Hashes of expected file:
   - Filesize:203585 [weak]
   - SHA512:070b1469cbfcc74fbe83b5b8bd1af9707f9f0ad520d4bf161340532c8bec4fd31812cf9242a81fe54e805837495281bcece1edb925104ff817191e068970863c
   - SHA256:7e6635480cc4a9463de3167215ad504c8721bd43d9c40b4ad71b44f60380757d
   - SHA1:9baf9b98b78b41be5c361ba7825f016e1abd31d2 [weak]
   - MD5Sum:f509c48fcb219ac06f64fbec78be0dd5 [weak]
  Release file created at: Thu, 15 Oct 2020 18:21:44 +0000
Fetched 3,959 B in 1s (2,716 B/s)
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (203820 != 203585). Mirror sync in progress? [IP: 20.188.102.6 443]
   Hashes of expected file:
    - Filesize:203585 [weak]
    - SHA512:070b1469cbfcc74fbe83b5b8bd1af9707f9f0ad520d4bf161340532c8bec4fd31812cf9242a81fe54e805837495281bcece1edb925104ff817191e068970863c
    - SHA256:7e6635480cc4a9463de3167215ad504c8721bd43d9c40b4ad71b44f60380757d
    - SHA1:9baf9b98b78b41be5c361ba7825f016e1abd31d2 [weak]
    - MD5Sum:f509c48fcb219ac06f64fbec78be0dd5 [weak]
   Release file created at: Thu, 15 Oct 2020 18:21:44 +0000`

**Comment by w3mona** [comment]
I have the same issue in USA

Err:38 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (141364 != 141252). Mirror sync in progress? [IP: 40.74.238.15 443]
  Hashes of expected file:
   - Filesize:141252 [weak]
   - SHA512:dffbaf15f537ae643df110b279248993b2828e99352dff51a5df9648cf39531ffb7022ec2f0d9e553287c9889addcb5e734d9df95f749c456db04fd328a67ef4
   - SHA256:6757f7f09fb2a0491657aac899faa29bd67fe7b9dfd849844f7fafca9afcc33e
   - SHA1:37be76673db70e808db91294af54fddf476aae7f [weak]
   - MD5Sum:ecc0d5d8d9373eee7aeceda58d7be8f9 [weak]
  Release file created at: Tue, 13 Oct 2020 22:35:00 +0000
Get:39 https://cli-assets.heroku.com/apt ./ Packages [612 B]
Get:40 http://packages.cloud.google.com/apt cloud-sdk/main amd64 Packages [140 kB]
Get:42 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages [41.3 kB]
Get:43 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1387 kB]
Get:44 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages [226 kB]
Get:45 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [274 kB]
Get:46 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [160 kB]
Get:47 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [21.5 kB]
Get:48 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1075 kB]
Get:49 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages [71.9 kB]
Get:50 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [240 kB]
Get:51 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [12.6 kB]
Get:52 http://security.ubuntu.com/ubuntu bionic-security/multiverse Translation-en [2936 B]
Get:53 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main Translation-en [29.5 kB]
Fetched 8453 kB in 4s (2081 kB/s)
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (141364 != 141252). Mirror sync in progress? [IP: 40.74.238.15 443]
   Hashes of expected file:
    - Filesize:141252 [weak]
    - SHA512:dffbaf15f537ae643df110b279248993b2828e99352dff51a5df9648cf39531ffb7022ec2f0d9e553287c9889addcb5e734d9df95f749c456db04fd328a67ef4
    - SHA256:6757f7f09fb2a0491657aac899faa29bd67fe7b9dfd849844f7fafca9afcc33e
    - SHA1:37be76673db70e808db91294af54fddf476aae7f [weak]
    - MD5Sum:ecc0d5d8d9373eee7aeceda58d7be8f9 [weak]
   Release file created at: Tue, 13 Oct 2020 22:35:00 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error: The process 'sudo' failed with exit code 100

**Comment by DiaElectronics** [comment]
Just got the same issue:( Siberia, Russia.

**Comment by w3mona** [comment]
Works now

**Comment by chrmarti** [comment]
This was fixed around Friday 6:15am UTC. Let us know if you still see any issues. Thanks.

**Comment by mehulboricha** [comment]
> This was fixed around Friday 6:15am UTC. Let us know if you still see any issues. Thanks.

It's fixed now. Thanks 👍

**Comment by DanioPurdue** [comment]
same issue on ubuntu:20.04

**Comment by Tariqs** [comment]
This worked for me on Ubuntu 20.04. First, remove all the vscode related files in source.list.d and then update your packages.

```
sudo rm -rf /etc/apt/sources.list.d/vscode.list*
sudo apt-get update

```

I spent more than 6 hours searching for a solution and finally above mentioned solution worked.
Hope this helps.

**Comment by santiagopardal** [comment]
Same issue, Ubuntu 20.04 Argentina!
