### ISSUE TITLE
ESLint: Is it enabled or disabled?

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#107759]
Testing https://github.com/microsoft/vscode/issues/107584

I tried to get to the same dialog that I get through quick fix or the status bar item using the command palette. So, I chose `ESLint: Enable ESLint` in a workspace ESLint was not allowed to run in yet. I got:

![image](https://user-images.githubusercontent.com/4674940/94628850-f2a10480-0275-11eb-91b2-098036032b50.png)

The problem tells me that ESLint is disabled. The notification tells me it's enabled.

**Comment by dbaeumer** [comment]
This needs some rewording. You could always enable / disable ESLint using the setting `eslint.enable`. If set to false the extension will not start a server. This is for workspaces where ESLint shouldn't run at all. 

Currently no good idea about the wording :-(

**Comment by dbaeumer** [comment]
Here is what I did to fix this:

- removed the command since this can now be achieved using the extensions viewlet
- kept the setting but deprecated it.

**Comment by dbaeumer** [comment]
To verify: ensure that the `ESLint: Enable ESLint` and `ESLint: Disabled ESLint` commands are gone from the command palette.

**Comment by rzhao271** [comment]
Looks like they're still there.
Maybe the fix hasn't been released in the latest insiders yet?

![eslint-commands](https://user-images.githubusercontent.com/7199958/94860647-35381d80-03eb-11eb-8dcd-e2b3bec6bf16.PNG)

**Comment by dbaeumer** [comment]
This will come with a new version of the ESLint extension. Since this version will require VS Code 1.50.0 I need to wait to have a stable release before I can publish a new version of ESLint.
