### ISSUE TITLE
Check JS setting is not overridden by jsconfig.json

### ISSUE THREAD

**Issue by ValYouW** [microsoft/vscode#107718]
- VSCode Version: 1.49.2
- OS Version: Windows_NT x64 10.0.19041

In short: when setting `JavaScript › Implicit Project Config: Check JS` is enabled, type-checking is performed for files even if they are in the `exclude` setting of `jsconfig.json` - I'm pretty sure it wasn't always like that. Also in Settings there is a comment stating "Existing jsconfig.json or tsconfig.json files override this setting".

Steps to Reproduce:
1. In settings enable option `JavaScript › Implicit Project Config: Check JS`
2. create a `jsconfig.json` file looks like:
```js
{
	"compilerOptions": {
		"checkJs": true
	},
	"exclude": ["ignoreme.js"]
}
```

create file `ignoreme.js` like:
```js
parseInt(2);
```

Result: there is a `ts` error while this file should have been excluded.

**Comment by mjbvz** [comment]
This sounds correct.

The `exclude` excludes the file from any project (i.e. it is in an implicit project)

And any files in implicit projects use the `Implicit Project Config: Check JS` setting
