### ISSUE TITLE
Separate theme extensions and regular extensions

### ISSUE THREAD

**Issue by touhidrahman** [microsoft/vscode#107771]
In the installed extensions explorer, a subsection should be there to group the extensions those are purely for themes (and icons). That way user experience will improve while navigating lots of extensions which is normal for a typical vscode user.

**Comment by gjsjohnmurray** [comment]
You can already do this:

![image](https://user-images.githubusercontent.com/6726799/94650783-43a10f00-02ef-11eb-9159-34af21f04b9c.png)
