### ISSUE TITLE
Debugger tries to connect when running a npm script

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#107785]
In a CodeSpace on Github.

<img width="584" alt="capture" src="https://user-images.githubusercontent.com/1931590/94660701-5115c380-0306-11eb-8edf-fb187f51de83.png">

In addition I get a notification to forward a port.

**Comment by connor4312** [comment]
What is your auto attach setting?

Forwarding is covered by https://github.com/microsoft/vscode/issues/107243

**Comment by dbaeumer** [comment]
What do you mean by:

> What is your auto attach mode?

I simply cloned the repository into a GitHub code space and ran npm compile. This doesn't happen locally.

**Comment by anthowm** [comment]
I just generate a new react app yesterday all was working fine, today I get the update and all npm scripts I run open the debugger(it happen to other projects as well) . I got autoattach in preferences but this behaviour didnt happen to me before.

**Comment by connor4312** [comment]
Please share the version of VS Code you're running and the value of the `debug.javascript.autoAttachFilter` setting.

**Comment by anthowm** [comment]
v 1.49.2
![Screenshot 2020-10-01 at 17 58 08](https://user-images.githubusercontent.com/5764698/94833743-c6b98680-040f-11eb-9113-7b6752ee2f90.png)
Downgrade to v1.48.2 works as expected I noticed that there is a select for autoAttachFilter should I change smart to another value ?

**Comment by connor4312** [comment]
Ok, thanks. This will be fixed in the upcoming release (and is on [insiders](https://builds.code.visualstudio.com/builds/insider)). You're probably hitting https://github.com/microsoft/vscode/issues/106991
