### ISSUE TITLE
selecting a file to move in a scrolled explorer box shifts the selection to the previous file

### ISSUE THREAD

**Issue by davidfig** [Microsoft/vscode#10775]
- VSCode Version:
1.4.0 (1.4.0)
- OS Version:
Mac OS

Steps to Reproduce:

1. Open a directory with lots of files
2. Scroll down a bit in the explorer pane
3. hold click a file to start a move operation

The explorer window will scroll up by one file and you will be dragging the file above the one you wanted to select

**Comment by bpasero** [comment]
Ah this is because of the "opened editors" view pushing down due to the open.
