### ISSUE TITLE
Location called twice after setInput is called.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#107706]
Testing #107585

I recognized that `location` property is accessed twice in a row when calling `setInput`

**Comment by jrieken** [comment]
is that something bad?

**Comment by dbaeumer** [comment]
I noticed it and since I create a new instance I thought I report it.

**Comment by jrieken** [comment]
Ah, note the location-property on the input but the location-function on the navigation support?

**Comment by dbaeumer** [comment]
No, the location property on the input. My be it is my stupid implementation.

```
	public get location(): vscode.Location {
		const folder = vscode.workspace.workspaceFolders![0];
		return new vscode.Location(vscode.Uri.parse(`${folder.uri.toString()}/test.js`), new vscode.Position(1,1));
	}

```

**Comment by jrieken** [comment]
I could cache it but given this is a property (not a function) I think its ok to keep calling it. It is marked as `readonly` which should mean that we expect a constant value.

**Comment by dbaeumer** [comment]
Makes sense
