### ISSUE TITLE
Missing taskbar icon

### ISSUE THREAD

**Issue by sparkleface815** [microsoft/vscode#107754]
Issue Type: Performance Issue

I haven't opened vscode in about a few months and the taskbar icon is just a blank file icon

![image](https://user-images.githubusercontent.com/68936036/94624476-6558b280-026b-11eb-91dc-4765fade073d.png)

**Comment by joaomoreno** [comment]
This is an upstream Windows issue. Try something like https://www.howtogeek.com/232779/how-to-rebuild-a-broken-icon-cache-in-windows-10/
