### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by 928PJY** [Microsoft/vscode#10777]
in the extension [markdown](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/src/extension.ts) ,

	let d3 = vscode.commands.registerCommand('markdown.showSource', showSource);

no parameter was passed to the showSource , 
```ts
function showSource(mdUri: Uri) {
	if (!mdUri) {
		return vscode.commands.executeCommand('workbench.action.navigateBack');
	}

	const docUri = Uri.parse(mdUri.query);

	for (let editor of vscode.window.visibleTextEditors) {
		if (editor.document.uri.toString() === docUri.toString()) {
			return vscode.window.showTextDocument(editor.document, editor.viewColumn);
		}
	}

	return vscode.workspace.openTextDocument(docUri).then(doc => {
		return vscode.window.showTextDocument(doc);
	});
}
```
is it possible to execute the code after if{....}.
Any help will be appreciated!

**Comment by alexandrudima** [comment]
@928PJY Is it that you're writing an extension and want to invoke the `markdown.showSource` command?

**Comment by 928PJY** [comment]
Yes ,I am writing an preview extension just like markdown preview  , but not to invoke the markdown.showSource command . I just want to figure out the code. I think the code after if{..} won't be excute , is it?

**Comment by alexandrudima** [comment]
@kieferrm Can you help you further.

@kieferrm Please note it is possible for an extension to "export" public API -- it is the return value of the `activate()` function. It is also possible for an extension to "import" other's API via the `vscode.extensions` namespace.

**Comment by kieferrm** [comment]
@928PJY  Some context first: Assume a markdown preview is the user's active editor and the user wants to go to the markdown source. This can be done by toggling the preview using <kbd>Shift+Cmd+V</kbd> which issues the `markdown.showPreview` command. The user can also choose `Show Source` from the command palette or trigger `Show Source` in the preview editor's title bar. Those two cases issue the `markdown.showSource` command.

The `markdown.showSource` command is bound to the `showSource` function. The `markdown.showPreview` command is bound to the `showPreview` function. Depending on how the user triggers the command(s), the functions are called with or without the uri.  

The situation gets more complicated by the fact that  `vscode.window.activeTextEditor` returns `null` when the markdown preview is active, i.e. there is no way the code can determine that the preview is active. So, the code optimizes for the most common workflow which is toggling between markdown preview and markdown source and issues `workbench.action.navigateBack`. 

```ts

function showPreview(uri?: Uri, sideBySide: boolean = false) {

	let resource = uri;
	...
	if (!(resource instanceof Uri)) {
		if (!vscode.window.activeTextEditor) {
			// this is most likely toggling the preview
			return vscode.commands.executeCommand('markdown.showSource');
		}
		// nothing found that could be shown or toggled
		return;
	}
    ...
}

function showSource(mdUri: Uri) {
	if (!mdUri) {
		return vscode.commands.executeCommand('workbench.action.navigateBack');
	}
    ...
}
```

You should be able to execute `markdown.showSource` the following way:
```ts
vscode.commands.executeCommand('markdown.showSource', <your URI>);
```

**Comment by 928PJY** [comment]
Thank you so much ! it help me a lot!!
