### ISSUE TITLE
Improve working for empty view

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107796]
Testing #107623

<img width="347" alt="Screenshot 2020-09-30 at 11 06 21" src="https://user-images.githubusercontent.com/1794099/94665873-00559900-030d-11eb-8a46-4021308773de.png">

The working isn't good. Nuke the double dash and exclamation mark. How about: "This view will show realtime performance stats when an application is runnning"

**Comment by connor4312** [comment]
I think I will just have it say "No data available yet". The title says "realtime performance" and it's in the debug view which is otherwise mostly inactive without a running session, so restating that is redundant.
