### ISSUE TITLE
Boarder overlap in setting sync 'select service' UI

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#107737]
Issue Type: <b>Bug</b>

**Repro**
1. Using the standard dark+ theme
1. Trigger the 'select service' UI for setting sync

**bug**
This input has a blue boarder around it, however the two input options cut off this boarder on the sides:

<img width="1298" alt="Screen Shot 2020-09-29 at 12 01 53 PM" src="https://user-images.githubusercontent.com/12821956/94603853-afca3700-024b-11eb-979f-dca545bf531f.png">

VS Code version: Code - Insiders 1.50.0-insider (0580328b728a69768558cc8242067cae7b6a1c21, 2020-09-29T09:05:00.729Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.76GB free)|
|Process Argv|-psn_0_57833252 --crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|11%|
</details>

**Comment by chrmarti** [comment]
How do I trigger this UI?

**Comment by sandy081** [comment]
- Stop Settings Sync if it is On.
- Turn on Settings Sync and you will see this UI in the turn on flow.

This is available only in insiders

**Comment by Avivhdr** [comment]
I can't trigger it.
When I'm turning on setting sync, I get the _'select an account to sign in'_ UI, and not the _'select service'_.

I need to set it to 'stable' so I could sync my settings.
Can it be done in another way?

![image](https://user-images.githubusercontent.com/23265867/101983962-9ea39a80-3c7e-11eb-8922-2fd5ad63eeb1.png)

**Comment by TylerLeonhardt** [comment]
it looks like the UI for this has changed now so I'm going to close this

**Comment by TylerLeonhardt** [comment]
Actually, I was able to repro after signing in and clicking on the quick pick

**Comment by TylerLeonhardt** [comment]
test steps:

* turn off settings sync if it's on
* turn on settings sync
* you may need to log in to settings first
* click on the title of the quick pick

You should see the blue border around the entire quick pick
![image](https://user-images.githubusercontent.com/2644648/111337814-a125df80-8633-11eb-818e-10c0330d86ea.png)
