### ISSUE TITLE
Download fails with ERR_STREAM_PREMATURE_CLOSE starting in 1.49.0

### ISSUE THREAD

**Issue by lolodi** [microsoft/vscode#107741]
- VSCode Version: 1.49.0, 1.49.1, 1.49.2, 1.50.0-insider
- OS Version: All

Steps to Reproduce:

I work for Bridge to Kubernetes Microsoft extension. 
We used to be able to download our binaries without much trouble but starting with 1.49.0 we started seeing ERR_STREAM_PREMATURE_CLOSE happening in a relevant way, making it impossible for many of our users to use our extension.
We are unable to repro this locally but our telemetry indicates the failure happening only for 1.49 versions across all OSes while we never see this error on previous VSCode versions, where we still have a lot of activity.

1. Install https://marketplace.visualstudio.com/items?itemName=mindaro.mindaro
2. Wait for the extension to initialize and download binaries. During the download a Premature Close error is thrown.

Does this issue occur when all extensions are disabled?: Was not able to repro it locally, I am working out of telemetry.

**Comment by sandy081** [comment]
If I understand correctly, the extension downloads binaries during activation?

**Comment by pragyamehta** [comment]
Yes, that is correct. We use the file downloader here [https://github.com/microsoft/vscode-file-downloader-api](url) to download the binaries.

**Comment by alexdima** [comment]
VSCode `1.48.x` shipped with nodejs version `v12.8.1`.
VSCode `1.49.x` shipped with nodejs version `v12.14.1`.

I believe there is some piece of code (unclear to me which one) which does something with streams in a way that is OK for nodejs `v12.8.1` and not OK for nodejs `v12.14.1`.

Here is the nodejs changelog vor v12 -- https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md
Nothing stood out to me from `v12.8.1` to `v12.8.4`. The best is to report this directly against https://github.com/microsoft/vscode-file-downloader-api as that is not authored by the core VS Code maintainers.
