### ISSUE TITLE
"Unknown Configuration Setting" extends too far in workspace

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#107780]
- VSCode Version: 1.49.2, also 1.50.0-insider, 9de65ab77e587cf7ab5dd00ea301cd5431b0f397
- OS Version: Windows 10

Steps to Reproduce:

1. Save this file as ```bug.code-workspace``` and open it:
```
{
    "folders": [],
    "settings": {
        "python.analysis.autoImportCompletions": true,
        "unknown.setting": "",
        //"python.analysis.logLevel": "Error"
    },
    "tasks": {
        "version": "2.0.0",
        "tasks": []
    }
}
```

This is what you get:
![image](https://user-images.githubusercontent.com/12128514/94657249-7522d600-0301-11eb-9aab-72c1eb207d03.png)

The `"tasks"` entry is incorrectly dimmed out, although hints are correct:

![image](https://user-images.githubusercontent.com/12128514/94657335-997eb280-0301-11eb-9b73-b05ae6843588.png)

Commenting out `"unknown.setting"`, or commenting in `"python.analysis.logLevel"`, fixes the issue:

![image](https://user-images.githubusercontent.com/12128514/94657442-c03ce900-0301-11eb-81e5-11d66edab18c.png)

![image](https://user-images.githubusercontent.com/12128514/94657421-b7e4ae00-0301-11eb-80e2-b6833eb35fc5.png)

**Comment by jrieken** [comment]
Now I don't see any warning anymore. @sandy081 That's not expected, right?

<img width="577" alt="Screenshot 2020-10-29 at 12 40 49" src="https://user-images.githubusercontent.com/1794099/97563841-fabea200-19e3-11eb-908a-945f3c05a8f4.png">

**Comment by sandy081** [comment]
@jrieken We do not show warnings for unknown configurations instead we generate Hint markers thereby they will be dimmed. I see as expected.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/10746682/97564781-65241200-19e5-11eb-8366-feb93891d039.png">

Is there anything special with your set up? Can you also please try check running from sources?

**Comment by jrieken** [comment]
Do you need run in workspace mode is opening the file enough? I am doing the latter

**Comment by sandy081** [comment]
Ah that explains, you have to be in workspace mode and open the current workspace configuration file.
