### ISSUE TITLE
vscode-file:// windows cannot access HTTP URLs (CORS issue)

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#107722]
Testing #107466
Ubuntu 

![image](https://user-images.githubusercontent.com/8586769/94589672-6d4c2e80-023a-11eb-9971-755eb2b62d7c.png)

**Comment by bpasero** [comment]
//cc @mjbvz I wonder if the `webview` sets a CSP that blocks `vscode-file` possibly?

**Comment by bpasero** [comment]
@deepak1556 I might need your help here, it looks like XHR requests from the renderer will trigger this error and I wonder if we are missing a configuration property on the scheme here:

https://github.com/microsoft/vscode/blob/a3873d9570f9dd200310cb1fe13af7573821b1b6/src/main.js#L128-L128

The place where the error is triggered from is: 

https://github.com/microsoft/vscode/blob/66db1a705700afb764217016cef129b7a210e8db/src/vs/base/parts/request/browser/request.ts#L42-L42

**Comment by bpasero** [comment]
This probably requires new API: https://github.com/electron/electron/pull/24849

**Comment by bpasero** [comment]
This is actually a lot worse, I also see our request to settings sync failing:

```
Access to XMLHttpRequest at 'https://vscode-sync-insiders.trafficmanager.net/v1/manifest' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by bpasero** [comment]
After discussion with Deepak, we figured out that services we talk to need to be configured properly to have `Access-Control-Allow-Origin: vscode-file://vscode-app` as response header if CORS is enabled.

Refs: https://github.com/microsoft/vscode-internalbacklog/issues/1824
