### ISSUE TITLE
ESLint: Command palette entry for managing eslint execution

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#107762]
Testing https://github.com/microsoft/vscode/issues/107584

I'd like to be able to control eslint execution through the command palette. To me, this is more easily discoverable than going through Problems (either panel or editor).

**Comment by dbaeumer** [comment]
You can also click on the status.

**Comment by dbaeumer** [comment]
I added a command `ESLint: Manage Library Execution`
