### ISSUE TITLE
editor.semanticTokenColorCustomizations not working on PHP

### ISSUE THREAD

**Issue by arisdanang** [microsoft/vscode#107702]
when I modify file settings.json and add property editor.semanticTokenColorCustomizations and I customize it.
when I open my PHP project it doesn't works, but when I open my javascript project it works

**Comment by roblourens** [comment]
Please give an example of exactly what modifications you make and share the file you are looking at, and what should be happening.

**Comment by arisdanang** [comment]
[image: Screenshot (534).png]
[image: Screenshot (535).png]
[image: Screenshot (536).png]

Pada tanggal Sel, 29 Sep 2020 pukul 22.26 Rob Lourens <
notifications@github.com> menulis:

**Comment by roblourens** [comment]
The screenshots are missing, email doesn't work for them

**Comment by arisdanang** [comment]
sorry sir i dont know if img crack

Pada tanggal Rab, 30 Sep 2020 pukul 00.05 Rob Lourens <
notifications@github.com> menulis:

**Comment by roblourens** [comment]
You will just have to upload images through the website

**Comment by arisdanang** [comment]
[image: Screenshot (534).png]
[image: Screenshot (535).png]
[image: Screenshot (536).png]

Pada tanggal Rab, 30 Sep 2020 pukul 01.25 Rob Lourens <
notifications@github.com> menulis:

**Comment by roblourens** [comment]
It looks like you emailed them again, that won't work
