### ISSUE TITLE
treeView name and description both shorten when size of explorer changes

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#107751]
Testing #107639

When the explorer view is a smaller size, I think the description should be shortened, but personally, I think the name should remain and not be shortened.

![recording (5)](https://user-images.githubusercontent.com/9721254/94615946-97234680-0276-11eb-8349-cf1ce250a234.gif)

**Comment by eamodio** [comment]
Good call -- thanks for filing this!

**Comment by bpasero** [comment]
Verified with timeline view:

![image](https://user-images.githubusercontent.com/900690/94918122-341df380-04b2-11eb-9a54-121082373d64.png)
