### ISSUE TITLE
ESLint: Status bar item not updated

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#107764]
Testing https://github.com/microsoft/vscode/issues/107584

1) Reset all ESLint library decisions
2) Open a `.github-issues` notebook file
3) Press the eslint status bar item to get the dialog
4) Press `Allow`
-> status bar item does not update
5) Open a `.ts` file
-> status bar item correctly updates

**Comment by dbaeumer** [comment]
Fixed in ESLint repository.
