### ISSUE TITLE
I find it very confusing that tab on a focus row doesn't move you to the next row when at the end. It moves to the terminal panel

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#107795]
Testing #107610

- Focus a row
- tab through the elements
- after being on the tool action the next tab moves you to the terminal tab complete out of the settings editor.

**Comment by roblourens** [comment]
This is by design. Previously it worked this way and was impossible to tab out of the settings editor. Now it works more similarly to other editors as a tab target and doesn't keep your cursor forever.
