### ISSUE TITLE
SCM commit message box scrolls instead of wrapping

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#107769]
This is weird, sometimes overflowing text in the SCM scrolls horizontally, and sometimes it wraps. I think it's supposed to wrap. I can't repro it consistently but saw it a few times in Insiders and OSS.

![image](https://user-images.githubusercontent.com/323878/94644973-84713780-029f-11eb-9522-4d4c39b3a615.png)

cc @meganrogge I know you were working on this, I don't know whether your changes are in master or not yet

**Comment by joaomoreno** [comment]
Odd. Never saw it, let me know if you ever get to repro steps.
