### ISSUE TITLE
Please supply the ability to sort files by modified time asc/desc  in groups in source  control's Changes view when view as list

### ISSUE THREAD

**Issue by x-strong** [microsoft/vscode#107767]
﹀ **Changes**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ⑩
     | ﹀ **A quarter ago**
     |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file1.html
     | ﹀ **Half an hour ago**
     |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file2.ts
     |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file3.json
     | ﹀ **Two hours ago**
     |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file4.xml
     |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file5.md
     |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file6.properties
     |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file7.scss
     | ﹀ **One day ago**
     |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file8
     |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file9
     |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;file10

- When mouse is over the file, we can get the exactly modified time information from tooltip.
- We can make git operations on group, for example, stage group, stash group, or discard group, and so on.

**Comment by joaomoreno** [comment]
Modification time is something not present in our API nor in Git's model. This will be very hard to achieve.
