### ISSUE TITLE
Ubuntu repo maybe broken?

### ISSUE THREAD

**Issue by timfelle** [microsoft/vscode#107773]
- VSCode Version: 1.49.1
- OS Version: Ubuntu 20.04.1 LTS

Steps to Reproduce:

    $ sudo apt update  
    Get:6 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages [201 kB]
    Err:6 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages
    File has unexpected size (201047 != 200914). Mirror sync in progress? 
    Hashes of expected file:
      - Filesize:200914 [weak]  
      - SHA512:a91d388504b56c875620f73b618813be1c127d6bfe96406cc6e9a39fdf33f1dd2c8ecbda4a636f0c86bc18005e4f5d0683da0c02ba13c555cef8d11eb83412fe  
      - SHA256:1d39334cb2779572dd17869a05d3ed3f1d57992cc9755a34a4d2622132b19f57  
      - SHA1:d5224a98d6adfb4ab65d66aa803f9688a6503080 [weak]  
      - MD5Sum:2fc601c3aa23f067ef305bfb7f7086e7 [weak]  
     Release file created at: Mon, 28 Sep 2020 06:53:06 +0000
    Reading package lists... Done
    E: Failed to fetch http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (201047 != 200914). Mirror sync in progress? 
      Hashes of expected file:
       - Filesize:200914 [weak]
       - SHA512:a91d388504b56c875620f73b618813be1c127d6bfe96406cc6e9a39fdf33f1dd2c8ecbda4a636f0c86bc18005e4f5d0683da0c02ba13c555cef8d11eb83412fe
       - SHA256:1d39334cb2779572dd17869a05d3ed3f1d57992cc9755a34a4d2622132b19f57
       - SHA1:d5224a98d6adfb4ab65d66aa803f9688a6503080 [weak]
       - MD5Sum:2fc601c3aa23f067ef305bfb7f7086e7 [weak]
      Release file created at: Mon, 28 Sep 2020 06:53:06 +0000
    E: Some index files failed to download. They have been ignored, or old ones used instead.

Does this issue occur when all extensions are disabled?: Yes

Previous version of this problem:  #41094

**Comment by udaykapur** [comment]
Same issue here since the last 2 hours approximately - just did a clean install of Ubuntu 20.04.01 and installed VS code using the `.deb` file.
Region - Australia.

**Comment by machineska** [comment]
After 8 hour broken repo now Confirm fixed in Indonesia.

**Comment by bendeg** [comment]
Restored (Belgium, this morning, debian buster). Thanks !

**Comment by udaykapur** [comment]
Guess this can be closed as well, issue has now been fixed. Thanks
