### ISSUE TITLE
not able to see go live option

### ISSUE THREAD

**Issue by jashanxoo7** [microsoft/vscode#107786]
Issue Type: <b>Bug</b>

as i am using V.S but i am not able to see go live option to preview my work straight from V.S.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|8.00GB (0.51GB free)|
|Process Argv|-psn_0_13065333 --crash-reporter-id d4251f3a-cf1f-479f-8718-e712789c5915|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
indent-rainbow|ode|7.4.0

</details>

**Comment by IllusionMH** [comment]
I guess that you forgot to install [Live Server
](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extension

**Comment by jashanxoo7** [comment]
> I guess that you forgot to install [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extension

I've already but still it's not showing me that live option!

**Comment by IllusionMH** [comment]
Anyway it doesn't looks like issue with VS Code.
There are similar reports in extension repo https://github.com/ritwickdey/vscode-live-server/issues/960 and others
and issue should be tracked there
