### ISSUE TITLE
Terminal looks weird

### ISSUE THREAD

**Issue by hong-ggg** [microsoft/vscode#107720]
- VSCode Version:1.49
- OS Version: Win 10

Since i install vscode,my terminal can't type my letters with cursor. When i made terminal shows more lines,it can automatically correct the typesetting.

![擷取](https://user-images.githubusercontent.com/72063645/94587546-5696ed80-02b5-11eb-9dbd-92ee2dd4ca33.PNG)
![20200930_003756](https://user-images.githubusercontent.com/72063645/94587553-57c81a80-02b5-11eb-9bae-f017fecb7a24.gif)

Also,i try to search github issues to fine the answer,but most discuss about font.

**Comment by Tyriar** [comment]
Can you run `ver` in cmd to get the Windows build number?

**Comment by hong-ggg** [comment]
Ok,My computer hasn't been updated for too long.  The problem was solved after I updated.Thx!
