### ISSUE TITLE
Multiple language support in single file

### ISSUE THREAD

**Issue by aknEvrnky** [microsoft/vscode#107770]
I'm html web coder. I'm writing my html codes in to PHP file. I can change my language mode PHP to HTML form rigth bottom. But sometimes I'm using php codes in my file. Is there any multiple language support for single file ?

**Comment by aeschli** [comment]
Don't change the mode from PHP to HTML. Instead, install a PHP extension:
E.g. https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

File issues against the extensions if features are missing.
