### ISSUE TITLE
Split terminal weird linebreak

### ISSUE THREAD

**Issue by PedroLima92** [microsoft/vscode#107700]
- VSCode Version: 1.49.2
- OS Version: Ubuntu 18

Steps to Reproduce:

1. Split terminal;
2. Resize column until cwd info is bigger than the column space and line is broken;
3. If cwd addres is big enough, and you make the column small enough, linebreaking and rendering gets strange behaviour;
4. Go back to regular size and text will be left unfixed

Does this issue occur when all extensions are disabled?: Yes

Also it's text. I can select it, copy it...

![image](https://user-images.githubusercontent.com/44039025/94565649-dda97e80-023f-11eb-9501-13665e7093f2.png)

(I tried to follow the rules of conduct, and kept it short and simple... please let me know if I can fix anything in this bug report)

**Comment by rzhao271** [comment]
Closing in favour of #109479
