### ISSUE TITLE
Output Console Auto Scroll

### ISSUE THREAD

**Issue by vchealy** [microsoft/vscode#107735]
Issue Type: <b>Bug</b>

The Auto Scrolling is not scrolling up in the latest version when running code

VS Code version: Code - Insiders 1.50.0-insider (0580328b728a69768558cc8242067cae7b6a1c21, 2020-09-29T09:07:46.673Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 2020M @ 2.40GHz (2 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.33GB free)|
|Process Argv|--crash-reporter-id b30eb744-1140-4a31-8991-f0a0ac9836d0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.0
python|ms-|2020.10.111333-dev

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Works for me with latest vscode insiders. My steps
1. Open Git OUtput
2. Autoscroll is working

@vchealy what are you oding differently?

**Comment by vchealy** [comment]
I still have this issue, after the latest update has finally applied for VS Code.

**Comment by isidorn** [comment]
Do you mean the Debug Console or the Output view?
