### ISSUE TITLE
Mouse shortcuts

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#10778]
Extracted from Microsoft/vscode#10744

---

From @DarceyLloyd

**Mouse shortcuts**
Shortcuts are fine, however would love to get access to the mouse. Eg in phpstorm I use the side mouse buttons (forward and back) with ALT and CTRL combinations for an additional 6 very quick and easy shortcuts that don’t require you to let go of the mouse when coding.

Loving the editor by the way!

**Comment by Naereen** [comment]
That would be really useful!
