### ISSUE TITLE
vscode-file build: unable to auth with github

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#107734]
Testing #107466

0. using https://az764295.vo.msecnd.net/insider/d8f5cfff08b04367fceb9ccbcff332d03c99d0c2/code-insider-x64-1601360576.tar.gz on ubuntu 
1. Attempt to run a github issue notebook cell
2. go through sign in process   in browser
3. browser opens up old insiders (not vscode-file build that spanwned it), asks is extension can handle uri. Quit out.
4. get token from web ui and paste into vscode-file build.
5 "network error"

![image](https://user-images.githubusercontent.com/8586769/94601808-dd61b100-0248-11eb-8dcd-05cea3cba92e.png)

**Comment by bpasero** [comment]
@JacksonKearl this flow is probably not very realistic because you end up with 2 different instances of VSCode given the one is the system wide installed and the other only for testing. You still think there is a bug here?

**Comment by JacksonKearl** [comment]
Potentially... though I'd expect pasting the token to always work. @RMacfarlane would probably know best here.
