### ISSUE TITLE
Specify a different tsconfig.json for linting

### ISSUE THREAD

**Issue by dfee** [microsoft/vscode#107750]
I use a `tsconfig.eslint.json` for linting – this is picked up in my `.eslintrc.js`. However, VSCode complains because it's using `tsconfig.json` to validate my `*.test.ts` files, which is specifically excluded in `tsconfig.json` but included in `tsconfig.eslint.json`.

**Comment by dbaeumer** [comment]
@dfee what does that error look like. Is it a ESLint error or a TS error (the source is denoted in `[]` in the error)

**Comment by dfee** [comment]
@dbaeumer Well, I'm not getting any errors in my `*.test.ts` files because i have:
```
   "exclude": ["**/__tests__", "dist", "e2e", "node_modules"],
```
in my `tsconfig.json`.

If I were able to specify (and i'm using a monorepo – which consistently uses `tsonfig.eslint.json`), then i'd see the appropriate `ts` errors.

**Comment by dbaeumer** [comment]
This is then a TS problem and has nothing to do with ESLint. To my knowledge users can't control the tsconfig.json file used by the TS language server. @mjbvz is that correct?

**Comment by mjbvz** [comment]
Yes we always use files called `tsconfig.json`. Support for explicit tsconfig names is tracked by https://github.com/microsoft/TypeScript/issues/33094
