### ISSUE TITLE
ESLint: Problem should be recreated on "Reset"

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#107758]
Testing https://github.com/microsoft/vscode/issues/107584

1) Open a `.ts` file.
-> problem at first line
2) Allow eslint in your workspace
-> no problem
3) Reset all eslint library decision
-> no problem but I'd expect one

**Comment by dbaeumer** [comment]
Fixed.

@kieferrm I also update the insider release here https://github.com/microsoft/vscode-eslint/releases/tag/2.1.9-insider.2 in case you want to verify.
