### ISSUE TITLE
Navigation keybindings does not work after pressing escape inside Add Pattern input box

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#107744]
Testing #107610

- Navigate using down arrow until Files: Exclude settings is selected
- Press Enter
- Tab until Add Pattern button is selected
- Press Enter
- Press Escape

🐛 Cannot use Up and Down arrows now.

**Comment by roblourens** [comment]
I can't repro. It's possible that it was fixed, but also I've just seen some weird focus glitches when voiceover is enabled and it could have been that too
