### ISSUE TITLE
Pressing the refresh button results in the following error

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#107707]
Testing #107585

<img width="372" alt="capture" src="https://user-images.githubusercontent.com/1931590/94575872-0009bf00-0275-11eb-8e16-957b29f76910.png">

Not sure if this is a problem or a mistake on my end not implementing certain methods yet. But it should not result in an error notification.

**Comment by jrieken** [comment]
hm... is there more on the console?

**Comment by dbaeumer** [comment]
This is all

<img width="714" alt="capture" src="https://user-images.githubusercontent.com/1931590/94577259-a5716280-0276-11eb-9374-c538b42247c0.png">

**Comment by jrieken** [comment]
@dbaeumer can you share your extension with me?

**Comment by jrieken** [comment]
@dbaeumer doesn't reproduce in my sample....

**Comment by dbaeumer** [comment]
Here a minimal case to reproduce. Took me a little.

```
class Provider implements vscode.TreeDataProvider<string> {

	public getTreeItem(element: string): vscode.TreeItem {
		const result = new vscode.TreeItem(element, vscode.TreeItemCollapsibleState.Collapsed);
		return result;
	}

	getChildren(element?: string): vscode.ProviderResult<string[]> {
		if (element === undefined) {
			return ['1'];
		} else {
			return [`${element}.1`];
		}
	}
}

class Model implements SymbolTreeModel {
	public readonly empty: boolean = false;
	public readonly provider: Provider = new Provider();
	public readonly message: string = 'Hello Reference View';
}

class Input implements SymbolTreeInput {
	public readonly contextValue: string = 'contextValue';
	public readonly title: string = 'Hello Input';
	public get location(): vscode.Location {
		const folder = vscode.workspace.workspaceFolders![0];
		return new vscode.Location(vscode.Uri.parse(`${folder.uri.toString()}/test.js`), new vscode.Position(1,1));
	}
	with(position: vscode.Position): SymbolTreeInput {
		throw new Error('Method not implemented.');
	}
	resolve(): Promise<SymbolTreeModel> {
		return Promise.resolve(new Model());
	}
}
```

**Comment by jrieken** [comment]
```
with(position: vscode.Position): SymbolTreeInput {
	throw new Error('Method not implemented.');
}
```

Well, that's it. My expectation is that whole interface is being implemented

**Comment by dbaeumer** [comment]
I spent some additional time on this yesterday and here is a suggestion: rename the method from `with` to `refresh` or `reRun`. The `with` is very technical and from our other discussion the with is called when the user refreshes the view. The position is the tracked position form the editor. You could even be smart and allow undefined if the position didn't change (which BTW was the case in my example when I started testing this)

**Comment by jrieken** [comment]
We have been using `with` to derive new instances of otherwise immutable types, like `vscode.Uri.with(...)` or `vscode.Position.with(...)`. What's different here is (a) that you must implement this behaviour and (b)  `SymbolTreeInput#with` takes a position which isn't one of its properties. Maybe it should be changes to taking a location instead. That would complement `SymbolTreeInput#location` and maybe more obvious

**Comment by dbaeumer** [comment]
You convince me with the `with` argument. The location would help as well.

**Comment by jrieken** [comment]
It's not like this

```

	/**
	 * This function is called when re-running from history. The symbols tree has tracked
	 * the original location of this input and that is now passed to this input. The 
	 * implementation of this function should return a clone where the `location`-property
	 * uses the provided `location`
	 * 
	 * @param location The location at which the new input should be anchored.
	 * @returns A new input which location is anchored at the position.
	 */
	with(location: vscode.Location): SymbolTreeInput<T>;
```
