### ISSUE TITLE
Moving Lines/Blocks Using ALT+Up/Down Arrow Combo Locks Up VS Code

### ISSUE THREAD

**Issue by BitwiseGuy** [Microsoft/vscode#10772]
-VSCode Version: 1.4
-OS Version: 14905.rs_prerelease.160811-1739

Steps to Reproduce:

1. Move a line/block up/down the page multiple lines, say a quarter to half a screen's worth, with ALT+Up/Down Arrow and VS Code locks up.

Cut/Paste is fine, but trying to move location by too many lines with the ALT combo locks up the application and it must be shutdown via the Task Manager.

**Comment by alexandrudima** [comment]
@BitwiseGuy 

I could not reproduce. Perhaps this happens in a certain file and when moving certain lines?

![moving](https://cloud.githubusercontent.com/assets/5047891/17845882/7a38e89c-6845-11e6-9bbb-0f5c772deec7.gif)

**Comment by BitwiseGuy** [comment]
This appears to be related to an extension. I opened VS Code with extensions disabled and there was no problem. Now to narrow it down to which extension.

Thank you for the reply.
