### ISSUE TITLE
settings sync: "Microsoft is currently unavailable"

### ISSUE THREAD

**Issue by DustyPane** [microsoft/vscode#107724]
- VSCode Version: 1.49.2
- OS Version: Windows 10 (10.0.18363)

Steps to Reproduce:

1. launch VSCode
2. right-click the "accounts" icon in the activity bar
3. instead of an option to log into a Microsoft account a message is shown saying "Microsoft is currently unavailable". This is not a general issue since it works fine at the same time on another Windows 10 machine (running the same version of VSCode).

Notes:
- it takes roughly 2 min for the described error message to appear, which seems to indicate that VSCode is initially trying to "find Microsoft"
- the major difference between the one computer where it works and the other where it doesn't is the Windows 10 version; works on 1904 does not on 1809. Is 1904 required?

Does this issue occur when all extensions are disabled?: Yes

**Comment by DustyPane** [comment]
> * OS Version: Windows 10 (10.0.18363)
After upgrading to Windows 10 2004 I'm seeing the same behavior w/version 10.0.19041 (the same one that works on another laptop), so it does not appear to depend on the Windows version

**Comment by RMacfarlane** [comment]
This sounds like a duplicate of https://github.com/microsoft/vscode/issues/106321, which has been closed but not released yet. As a workaround, can you try removing the cached credentials from the Windows Credential Manager? https://github.com/microsoft/vscode/issues/106321#issuecomment-694599194

**Comment by DustyPane** [comment]
> This sounds like a duplicate of #106321, which has been closed but not released yet. As a workaround, can you try removing the cached credentials from the Windows Credential Manager?

Thank you that fixed the issue for me. Note that I only removed the vscode-**microsoft**.login/account entry from Credentials Manager, not the vscode-**github**.login/account entry for the my GitHub account which is working fine.
