### ISSUE TITLE
Should the API talk more about locations (uri, position, ranges)

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#107711]
Testing #107585

The API is currently very generic except the navigation API. Since that already talks about uri, positions and ranges would it make sense to have an API that is tailored towards matches in files. That might make it a lot easier for implementors.

**Comment by dbaeumer** [comment]
For example I have to provide a command right now to open an element in the tree.

**Comment by jrieken** [comment]
That's how it initially started but the challenge is that this is locations (like reference search results) and symbols (like call hierarchy). They don't have much in common at the end of the day and that's why the API turned out being so generic
