### ISSUE TITLE
.nvmrc is outdated?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107701]
We seem to be using this node version:

https://github.com/microsoft/vscode/blob/c8f9d00bb85129b415fd955bcb7d6f0b9c463506/build/azure-pipelines/darwin/product-build-darwin.yml#L24-L24

But the `.nvmrc` wants node 10, not clear to me why:

https://github.com/microsoft/vscode/blob/65579c1715799814ef454fdcc6a723f3579c20de/.nvmrc#L1-L1

**Comment by joaomoreno** [comment]
Yeah deleted this.
