### ISSUE TITLE
Autotrigger completions in snippet placeholders not working

### ISSUE THREAD

**Issue by tonycheang** [microsoft/vscode#107742]
- VSCode Version: 1.49.2
- OS Version: macOS 10.15.6

Hello, I'm from the team that builds the kite autocomplete extension. We've been trying to get autocompletion within snippet placeholders for alphanumeric characters, but have run into a snag. I suppose I would expect completion requesting behavior to be similar within a snippet as not within a snippet, i.e. alphanumeric characters trigger completion requests. However, that seems to not be the case (related? https://github.com/microsoft/vscode-go/issues/3007):

![noalphatriggers](https://user-images.githubusercontent.com/18232816/94597064-eef38a80-0241-11eb-89b7-7d65a372e6ad.gif)

One way we got this working is to specify alphanumerics as trigger characters. In the following gif, `'m'` and `'a'` have been included as trigger characters.

![matrigger](https://user-images.githubusercontent.com/18232816/94597250-30843580-0242-11eb-9d00-f539a91b449e.gif)

However this seems to have the side effect of disabling native completions when the kite plugin's `provideCompletions` returns `[]` as a `Promise<CompletionList>` (e.g. we make the request but our desktop process is not running). In the following gif, `'m'` and `'a'` have been included as trigger characters and our desktop process is not running:

![matriggerkitenotrunning](https://user-images.githubusercontent.com/18232816/94597765-d2a41d80-0242-11eb-9c19-cc9ac1519a23.gif)

If alphanumerics are not specified as trigger characters, this seems to not be an issue. The kite plugin also does not provide completions in the following gif and `'m'` and `'a'` are not specified as trigger characters.

![notriggerkitenotrunning](https://user-images.githubusercontent.com/18232816/94597969-2151b780-0243-11eb-86fd-718fc687b50e.gif)

This seems expected from https://github.com/microsoft/vscode/issues/11935#issuecomment-246778493 (`editor.quickSuggestions` is set to `true` for all of these examples). Our desired behavior is that alphanumeric characters trigger completions within placeholders but kite completions integrate with native completions as well. Is that possible? What would be the best way to go about enabling this?

Thanks!

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
When a snippet is active, IntelliSense as you type (aka quick suggestions) is disabled. That is because there is a conflict between the <kbd>Tab</kbd>-key which moves to the next placeholder but also accepts a completion. You wouldn't be able to type in a placeholder and then move to the next placeholder as you would accept a suggestion then. You have the following options

* change the default via the `editor.suggest.snippetsPreventQuickSuggestions`-setting
* in snippets trigger suggestions manually (via Ctrl+Space, Alt+ESC (macOS), or `ctrl/cmd+i`)

**Comment by tonycheang** [comment]
Thanks for the explanation. I don't normally use tab to select completions, so the ambiguity there slipped my mind--makes sense why the default requires the user to opt in.

Related note: should `snippetsPreventQuickSuggestions` disable completions within snippets entirely, regardless of extensions' trigger character set? It seems a bit surprising our plugin could override the setting's behavior by adding alphanumerics to that set.
