### ISSUE TITLE
website stuck on localhost

### ISSUE THREAD

**Issue by imrandogra** [microsoft/vscode#107727]
Issue Type: <b>Bug</b>

while opend directory in code for work on project  my localhost website not open and load atleast after few mints and when i uninstall it website work fine . 
experimented several time every time found visual studio code culptet. 
please advise some solution.
thanks
imran 

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:26:09.944Z)
OS version: Linux x64 5.4.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 3092)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|7.68GB (0.17GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id d62ab72b-5f37-4a78-a286-8f51a12d91a9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bracket-pair-colorizer|Coe|1.0.61
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
auto-rename-tag|for|0.1.4
todo-tree|Gru|0.0.178
color-the-tag-name|jzm|0.17.0
indent-to-bracket|LAK|1.2.2
git-graph|mhu|1.26.0
code-beautifier|mic|2.3.3
vscode-scss|mrm|0.9.0
debugger-for-chrome|msj|4.12.11
indent-rainbow|ode|7.4.0
vscode-css-peek|pra|4.0.0
format-html-in-php|rif|1.7.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
open-window-tab-context|tak|1.4.2
bootstrap4-vscode|the|6.1.0
errorlens|use|3.2.2
reopenclosedtab|uyi|1.1.0
highlight-matching-tag|vin|0.10.0
vscode-icons|vsc|11.0.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by poojamulik** [comment]
Can you reproduce on any other machines? Or a VM?

**Comment by imrandogra** [comment]
no diabled all ext now working on one by one to find out culpter

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
