### ISSUE TITLE
Search editor: review potential unsafe editor resource usage

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107776]
**Background:** the search editor overrides the editor open behaviour for certain files. It takes the `resource` of the editor here:

https://github.com/microsoft/vscode/blob/46ba25e11d30a9d7477e6c014f7fbcee679d54bc/src/vs/workbench/contrib/searchEditor/browser/searchEditor.contribution.ts#L78-L78

And then later uses that for `parseSavedSearchEditor` and as `backingUri`.

The `editor.resource` property for files is the canonical form of that URI and must not necessarily match with the form it had originally. Here is a good example:
* an extension triggers to open an editor `/FOO/BAR/file.txt`
* the editor opens and from now on `/FOO/BAR/file.txt` is the canonical form of that `URI`
* the user clicks on `/foo/bar/file.txt` in the explorer (assuming that `/foo/bar` is actually the casing on disk)
* at this point `editor.resource` will be `/FOO/BAR/file.txt` because that is still the canonical form

To circumvent this, `EditorResourceAccessor` utility was added with methods to get the original URI (`/foo/bar/file.txt`) as well as the canonical one (`/FOO/BAR/file.txt`).

This issue is to review that you understand the problem and your usage is safe. I am not entirely sure how the editor resource is later used so maybe you can clarify. Bottom line:
* canonical form is fine for any file access (e.g. via node.js) and should be used when checking for identity or comparing editors
* original form should be used e.g. when you show a label to the user

**Comment by JacksonKearl** [comment]
Pushed code to use original uri in display contexts, though I'm not sure it's possible to reach this state -- an extension can only open text documents, passing the uri of a `.code-search` to `vscode.window.showTextDocument(await vscode.workspace.openTextDocument(uri))` opens up the raw text version rather than going through the editor open overrides.
