### ISSUE TITLE
Go to Definition goes to first usage and not definition

### ISSUE THREAD

**Issue by kjeremy** [microsoft/vscode#107841]
Issue Type: <b>Bug</b>

If there is one definition and one usage of that definition then clicking on "Go to Definition" on the definition will go to the usage. If there are multiple usages then "Go to Definition" will instead bring up the references.

I can reproduce this in both typescript and rust.

For instance in the code below where `<|>` is the cursor where `F12` is hit:

```ts
function foo<|>() {}

function bar() {
    foo(); // <---- We go to foo here
}
```

In the following vscode will instead pull up the references window.

```ts
function foo<|>() {}

function bar() {
    foo();
    foo();
}
```

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (18.66GB free)|
|Process Argv|--folder-uri file:///c%3A/projects/test/rust-analyzer --crash-reporter-id 260ece62-6e09-4dc4-9ffb-35b2fbd68a17|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|0.7.2
dart-code|Dar|3.15.0
flutter|Dar|3.15.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
better-cpp-syntax|jef|1.15.0
pubspec-assist|jer|2.0.0
rust-analyzer|mat|0.4.0-dev
python|ms-|2020.9.112786
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.1
cpptools-extension-pack|ms-|1.0.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsonline|ms-|1.0.2823
material-icon-theme|PKi|4.3.0
show-offset|ram|0.0.4
ts-inline-types|sok|1.1.0
even-better-toml|tam|0.8.4
cmake|twx|0.0.17
vscode-lldb|vad|1.5.3
vscode-icons|vsc|11.0.0
markdown-all-in-one|yzh|3.3.0

(4 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
This can be configured via `editor.gotoLocation.alternativeDefinitionCommand`
