### ISSUE TITLE
Split icon for perf charts is strange

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#107837]
Testing #107623

I don't have a better icon in mind but I find the split icon doesn't quite fit the action. Instead of splitting the pane in 2, we are splitting existing charts into as many panes. Additionally, the inverse is to merge, which the icon does not reflect.

**Comment by connor4312** [comment]
cc @misolori -- maybe an icon similar to the split view, but with arrows facing outwards or inwards?

This is the current icon for reference:

![](https://memes.peet.io/img/20-09-fefbb8a4-2371-4b27-a5ff-22dafdf6d74c.png)

**Comment by misolori** [comment]
What about using the collapse/expand icons? The metaphor can still apply here as this toggles between 1 chart vs many:

![image](https://user-images.githubusercontent.com/35271042/94738765-be385180-0324-11eb-944d-5494835f9a01.png)

![image](https://user-images.githubusercontent.com/35271042/94738779-c2646f00-0324-11eb-9d8e-6e210bc181e6.png)

**Comment by connor4312** [comment]
Sounds good to me
