### ISSUE TITLE
net::ERR_CERT_AUTHORITY_INVALID when searching for extensions

### ISSUE THREAD

**Issue by rsokl** [microsoft/vscode#107896]
I hit https://github.com/microsoft/vscode/issues/106434 in 1.49.0 as did others. Upgrading to 1.49.1 fixed it. Today, VSCode updated to 1.49.2, which produced the exact same error as before

(**Note**: the `net::ERR_CERT_AUTHORITY_INVALID` only occurs when I check VSCode for updates. It does not occur when I simply check the extension marketplace. This is exactly the same behavior that manifested in `1.49.0`)

![image](https://user-images.githubusercontent.com/29104956/94834690-b5a45180-03de-11eb-8e5b-853b06b55a50.png)

Downgrading to 1.49.1 fixed it again.

- VSCode Version: 1.49.2
- OS Version: Windows 10

Steps to Reproduce:

1. Attempt to view extensions marketplace behind proxy

**Comment by shamarin** [comment]
Didn't found it, mine copy is working well, proxy also working well.

**Comment by deepak1556** [comment]
I see there is a `net::ERR_CERT_AUTHORITY_INVALID` notification, this would be a case of missing CA cert from your system certificate store.

Can you attach the log following these steps

* Clear any http(s)_proxy settings
* launch vscode with `code.cmd --log-net-log=<some-absolute-path>/netlog.json`
* Add the proxy settings
* Search for extensions
* Quit the application

Attach the generated `netlog.json`, thanks!

**Comment by rsokl** [comment]
To clarify, the `net::ERR_CERT_AUTHORITY_INVALID` actually only occurs when I click "check for updates". This also happened in `1.49.0`. It doesn't occur when I try to reach the marketplace.

Will include the logs

**Comment by rsokl** [comment]
@deepak1556 attached is the zipped netlog
[netlog.zip](https://github.com/microsoft/vscode/files/5313758/netlog.zip)

**Comment by deepak1556** [comment]
thanks for the log, the site used for viewing net log is currently down https://netlog-viewer.appspot.com/#import , will get back once its working.

**Comment by deepak1556** [comment]
Does running with `--ignore-certificate-errors` help ?

**Comment by rsokl** [comment]
Doing so changes the message to `No extensions found` and `server returned 403`

![image](https://user-images.githubusercontent.com/29104956/94844587-77159380-03ec-11eb-84fd-2c9468bc3d92.png)

**Comment by deepak1556** [comment]
Do you get a successful connection when you run `curl -v https://vadimcn.gallerycdn.vsassets.io/extensions/vadimcn/vscode-lldb/1.5.3/1591510551951/Microsoft.VisualStudio.Code.Manifest` ?

**Comment by rsokl** [comment]
Yes

**Comment by rsokl** [comment]
By the way it looks like #107907 reports the same issue. 

I think that my original title, ` 1.49.2 broke proxy authentication again` might be appropriate for this issue, since the `net::ERR_CERT_AUTHORITY_INVALID` was being raised due to the broken proxy authentication that was fixed by `1.49.1`.

**Comment by deepak1556** [comment]
Looking at the logs,

So the proxy is fetched from a PAC file at `http://llproxy.llan.ll.mit.edu/proxy.pac` and set to 

```
t=80 [st=0]  PROXY_CONFIG_CHANGED
             --> new_config =
                    Proxy server: llproxy.llan.ll.mit.edu:8080
                    Bypass list: 
                      502360-mitll
                      <local>
```

Now looking at a sample request related to extensions `https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery`

```
t=5067 [st=70]     -HTTP_STREAM_REQUEST
t=5067 [st=70]      URL_REQUEST_DELEGATE_SSL_CERTIFICATE_ERROR  [dt=1]
t=5068 [st=71]      CANCELLED
                    --> net_error = -202 (ERR_CERT_AUTHORITY_INVALID)
```


So all the requests are pretty much cancelled with the same error which is not surprising.


From the certificate verifier stack, 


```
t=5067 [st=1]   -CERT_VERIFY_PROC
                 --> cert_status = 4
                 --> is_issued_by_known_root = false
```


Couple of checks to verify,

1) Do you see any output when you run https://vscodeexperiments.azureedge.net/experiments/vscode-experiments.json on your system chrome browser ?

2) You said network access worked with `1.49.1`, can you run this version with following commandline argument `--user-data-dir=<some-absolute-writable-path>` and check if extension search work. The goal is to see if any cached network results are being used. And if it still works can you provide a netlog from this version.

**Comment by rsokl** [comment]
>Do you see any output when you run https://vscodeexperiments.azureedge.net/experiments/vscode-experiments.json on your system chrome browser ?

Yep! I do see output from my browser.

>with 1.49.1, can you run this version with following commandline argument --user-data-dir=<some-absolute-writable-path> and check if extension search work.

I ran using `1.49.1` having specified a distinct user-data directory, and the extension search worked as-expected. Attaching the netlog..
[netlog_2.zip](https://github.com/microsoft/vscode/files/5318173/netlog_2.zip)

**Comment by deepak1556** [comment]
Thanks for the logs, that helped narrow down the issue.

Lets call the server certificate from `netlog_1` as `cert_1.pem` and CA certificate as `issuer_1.pem` and `cert_2.pem`, `issuer_2.pem` for the other log. These are obtained from SOCKET step of the log


For netlog_2:

```
$ openssl verify issuer_2.pem 
issuer_2.pem: OK

$ openssl x509 -noout -ocsp_uri -in cert_2.pem 
http://ocsp.msocsp.com

$ openssl x509 -in issuer_2.pem -text -noout | grep 'Issuer:'
        Issuer: C=IE, O=Baltimore, OU=CyberTrust, CN=Baltimore CyberTrust Root
```


For netlog_1:

```
$ openssl verify issuer_1.pem 
issuer_1.pem: O = MIT Lincoln Laboratory, OU = ISD, L = Lexington, ST = MA, C = US, CN = McAfee Web Gateway
error 18 at 0 depth lookup:self signed certificate
OK

$ openssl x509 -noout -ocsp_uri -in cert_1.pem 
http://ocsp.mwginternal.com/ocsp/0/com.scur.engine.sslclientcontext.18182/2b85c3348706598c95e81da4576a7dfea1b3bb8a

$ openssl x509 -in cert_1.pem -text -noout | grep 'Issuer:'
        Issuer: O=MIT Lincoln Laboratory, OU=ISD, L=Lexington, ST=MA, C=US, CN=McAfee Web Gateway
```

**Comment by deepak1556** [comment]
As you can see, for the case where we get ssl error, the proxy server is retuning self-signed certificates. You will have to contact your network administrator on why this is the case, maybe the anti-virus blocks this paritcular version of the application. Unless these self-signed certificates are installed to your system cert store and trusted, the error will continue.


I am going to close this issue as there is nothing actionable from vscode side. Thanks!
