### ISSUE TITLE
Tab button goes to search instead of adding space

### ISSUE THREAD

**Issue by echountasis** [microsoft/vscode#107867]
Hi guys, I am in an editor of a .cs file and I have the in file search open, not the solution search. 

I am writing my code and I press Tab to move the line to the right but instead the cursor moves to the in file search box. 

Tha be haviour was not there before - it is like the search box has a tab index.

It would be really helpful if you could revert the behaviour as it was
![tabIssue](https://user-images.githubusercontent.com/14096267/94772427-e45c0100-03b9-11eb-9379-b3056ab4a95a.png)

**Comment by IllusionMH** [comment]
Looks like you've pressed <kbd>Ctrl</kbd>+<kbd>M</kbd> which changes <kbd>Tab</kbd>behavior to enable navigation across interface. See details here https://code.visualstudio.com/docs/editor/accessibility#_tab-trapping

Use <kbd>Ctrl</kbd>+<kbd>M</kbd> to exit this mode or remove shortcut.

**Comment by echountasis** [comment]
So true - sorry guys I did not notice that this is a feature. All good now :)
