### ISSUE TITLE
Ability to skip next instance of word highlighting when using CMD + D

### ISSUE THREAD

**Issue by Jeowulf** [microsoft/vscode#107826]
When using CMD + D to skip-to and highlight the next instance of the word a user has highlighted, it would be nice to be able to skip over an instance (for any of many reasons, but all of which boil down to not wanting the next instance of the word included in this multi-selection) by either adding in a third key to the press binding or using CMD + another hot key. When using this alternative during CMD + D highlighting, it would simply go to the next instance without highlighting. At this point, using the alt again would move on again without highlighting, or using the regular key binding would move on again, highlighting the next word (business as usual).

**Comment by alexdima** [comment]
`cmd+k cmd+d` does this.
