### ISSUE TITLE
PHP autoformat make lines after the '<?php' code indented by one tab

### ISSUE THREAD

**Issue by CarterSnich** [microsoft/vscode#107878]
If you please, I would like VS Code when I auto format it will indent every line after the '<?php' code. Like on the picture below:
![Annotation 2020-10-01 193656](https://user-images.githubusercontent.com/52433531/94804703-d8a22600-041d-11eb-9443-27665d8e5df6.png)

**Comment by roblourens** [comment]
Maybe a formatter setting supports this? We don't control the actual formatting though.

**Comment by CarterSnich** [comment]
> Maybe a formatter setting supports this? We don't control the actual formatting though.

How to do it?
