### ISSUE TITLE
Watermark missing on Windows

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#107893]
![image](https://user-images.githubusercontent.com/35271042/94832232-808a0600-03c2-11eb-8204-e25d282b865b.png)

When looking at the console log, it appears the URL for the file is not rendering correctly (missing the /):

`file:///C:/UsersmisolorippDataLocalProgramsMicrosoft%20VS%20Code%20Insidersresourcesppoutvsworkbench%0Browserparts%C3%ADitormedialetterpress-dark.svg`

Maybe related to this change https://github.com/Microsoft/vscode/commit/7f035b4be73a7ce9ceafb2128c066b717eafaf87

**Comment by bpasero** [comment]
Good catch.
