### ISSUE TITLE
Theme is not updated in web when opened  in two tabs on same browser

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#107854]
- Open test playground in two tabs on same browser
- Change theme on one tab
🐛  Theme is not changed on other

**Comment by bpasero** [comment]
@sandy081 I wonder, could we maybe get this to work given we typically sync global state across tabs? I imagine when settings sync kicks in, we must be writing to IndexDB for the new values and then we could maybe also trigger this change event somehow?

**Comment by sandy081** [comment]
Possible workaround I am thinking here is to poll IndexedDB and somehow detect there are updates to resources from other tab and trigger change events.

**Comment by bpasero** [comment]
Even though I am not a big fan of `window.localStorage`, it provides a `onstorage` event that can be used to detect when another window makes changes to the same shared storage: https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onstorage

In theory this could be used as a hint from the one window to another that IndexDB was written to and would prevent having to poll.

**Comment by sandy081** [comment]
Good idea I can use `localStorage` to know if there is a change to `IndexedDB` from other tabs.
