### ISSUE TITLE
File > Save As shows simple file dialog for settings.json but native one for other files

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107882]
Steps to Reproduce:

1. open global settings as `settings.json`
2. trigger File > Save As
3. 🐛 as custom file dialog appears

I would have expected the native one. Is this maybe because of the custom scheme we are using?

//cc @alexr00

**Comment by sandy081** [comment]
Yes, this is because of the custom scheme we are using for settings and user data. Why not show simple file dialog always when in local window?

**Comment by bpasero** [comment]
@sandy081 are you suggesting that we no longer show a native dialog to save files? I find that not to be a good idea given we try to be a native application as much as we can.

**Comment by alexr00** [comment]
Agree with @bpasero, we should be showing the native dialog here unless the setting to use the simple file dialog is set.

**Comment by sandy081** [comment]
Sorry, I meant to show native file dialog always in local window.

**Comment by bpasero** [comment]
Yes, native dialog always unless the file is remote or the user has the setting configured to use simple dialogs.
