### ISSUE TITLE
multiple workspace folders with multiple settings.json: opening terminal uses "wrong" or single ${workspaceFolder}

### ISSUE THREAD

**Issue by romkell** [microsoft/vscode#107874]
- VSCode Version:
- OS Version:

Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:26:09.944Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic snap

Steps to Reproduce:

General structure:
in folder home/user/lib_b/.vscode/settings.json
{
	"terminal.integrated.env.linux" : {
		"LIB_A_BASE" :   "/home/user/lib_a/",
		"LIB_B_BASE" : "${workspaceFolder}"
	

}
in folder home/user/lib_b/some/sub/folders/app/.vscode/settings.json
{
	"terminal.integrated.env.linux" : {
		"LIB_A_BASE" :   "~/other/version/of/lib_a/",
		"LIB_B_BASE" : "${workspaceFolder}/../../../../"
	}
}
The folder lib_b and lib_b/some/sub/folders/app are both added to the workspace
1. Open "Terminal/New Terminal
2. In dialog I get a selection of "lib_b" and "app" to open the terminal
3. Select lib_b
4. echo $LIB_B_BASE in the terminal
   expected: /home/user/lib_b  
   effective: /home/user/lib_b/some/folders/app

It seems to me as if the "home/user/lib_b/.vscode/settings.json" is being used (which I consider correct), but the ${workspaceFolder} is pointing to "home/user/lib_b/some/sub/folders/app"

If I open the terminal at "lib_b" should the ${workspaceFolder} not be set to that path?
I guess the lib_a  and LIB_A_BASE is completely irrelevant and could be omitted to reproduce.
But it is how the two settings.json look like.

Does this issue occur when all extensions are disabled?: Yes/No
Not tested

Regards

Roman

**Comment by Tyriar** [comment]
You might be hitting a security feature to not allow the use of workspace terminal settings without opting in, try run this command and allow and see if that fixes your issue:

![image](https://user-images.githubusercontent.com/2193314/98326265-abf5a700-1fa5-11eb-80d4-2bdbea256add.png)
