### ISSUE TITLE
Infinitely respawning tab

### ISSUE THREAD

**Issue by syprieur** [microsoft/vscode#107850]
Issue Type: <b>Bug</b>

1. Have VS Code as the default diff editor for Git.

2. From `Microsoft Visual Studio Enterprise 2019` Version 16.7.5, logged into DevOps, open a commit file diff through Team Explorer.

3. This opens the diff in VS Code, with a file path like: `C:\Users\<user>\AppData\Local\Temp\TFSTemp\vctmp20604_175639.RequestContext.29419ac2.cs`.

4. Close this new tab.
  **At this point everything has worked per expectations.**

5. Try re-opening the last closed tab (Control+Shift+T).
This open a tab with an "empty" diff view and an error message similar to:
```
'C:\Users\<user>\AppData\Local\Temp\TFSTemp\vctmp20604_938934.RequestContext.dadfa9c5.cs ↔ C:\Users\<user>\AppData\Local\Temp\TFSTemp\vctmp20604_753766.RequestContext.29419ac2.cs': Unable to read file 'c:\Users\<user>\AppData\Local\Temp\TFSTemp\vctmp20604_938934.RequestContext.dadfa9c5.cs' (Error: Unable to resolve non-existing file 'c:\Users\<user>\AppData\Local\Temp\TFSTemp\vctmp20604_938934.RequestContext.dadfa9c5.cs').
```
That makes sense and can be expected behavior, but:

6. **Bug**: whenever this "faulty" tab is closed (e.g.: Ctrl+W), it re-opens again. When closed at a "normal" pace, the tab reopens seemingly infinitely, but spamming Ctrl+W seems to make it go away.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.36GB free)|
|Process Argv|--crash-reporter-id 79a638a3-e5e1-4be8-850b-7112229342eb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.9.0
vscode-json|and|1.5.0
xml|Dot|2.5.1
go|gol|0.17.1
jsonnet|hep|0.1.0
kusto-syntax-highlighting|jos|1.0.1
csharp|ms-|1.23.2
remote-wsl|ms-|0.44.5
powershell|ms-|2020.6.0
vscode-zipexplorer|sle|0.3.1
vscode-bond|yiw|0.0.10
t4-support|zbe|0.5.0

</details>

**Comment by bpasero** [comment]
I cannot reproduce when I try locally to compare 2 files, close the editor, delete one or both files and then reopen closed editor. It opens whatever editor was there before.

Since I am not sure what VS does, can you try to reproduce just with VSCode and maybe attach a screenshot of how the diff view looks like in the error case?

**Comment by syprieur** [comment]
The issue seems to stem from re-opening a VS Code diff on 2 now **non-existing** files.

Visual Studio just creates 2 temporary files, asks the default git editor (in this case VS Code) to do a diff on them, and deletes these 2 files as soon as the diff is finished (i.e. editor closed in VS Code).

The issue can be reproduced by following similar steps, without any involvement from Visual Studio:
1. Create 2 files, and make VS Code perform a diff on them:
`echo "aa" > a.txt; echo "ab" > b.txt; code --diff .\a.txt .\b.txt`

2. Close this diff tab in VS Code: Ctrl+W

3. Delete the 2 files:
`rm .\a.txt .\b.txt`

4. Re-open the last closed editor in VS Code: Ctrl+Shift+T.
The "empty" diff will appear again, and when closing it (Ctrl+W), the tab will "re-appear" again.

![image](https://user-images.githubusercontent.com/43798336/94836642-0f4d5180-03c8-11eb-965e-8cfe75a180cd.png)
*Empty, "respawning" diff*

**Comment by bpasero** [comment]
I can reproduce and will push a fix, this was a bad endless loop.

**Comment by alexr00** [comment]
@bpasero I see as quick flicker when I try to reopen the closed tab after deleting the files. The flick was too fast to capture in a gif. Otherwise, works great.

**Comment by bpasero** [comment]
@alexr00 yeah, we still try to open the diff editor and the tab will appear first very quick but then we close the editor because the actual contents does not exist. We only know that after we have tried to resolve the file from disk.
