### ISSUE TITLE
Operators not working in the when clause with resourceFolder

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#107834]
Testing #107638

Using the [same example](https://github.com/microsoft/vscode/issues/107725), I changed the `when` clause to:

```json
{
    "command": "extension.helloWorld",
    "when": "resourceFolder != supportedFolders",
    "group": "navigation@1"
}
```

So that means that the command should only appear on everything that doesn't match the list in `supportedFolders`. And it does not appear to work as I am getting the command on every item.

**Comment by eamodio** [comment]
That `when` clause is saying anytime `resourceFolder` is set to anything other than "supportedFolders" it should show. Only the `in` operator supports the dynamic lookup
