### ISSUE TITLE
VS Code created a new file after installing extension from command line

### ISSUE THREAD

**Issue by laike9m** [microsoft/vscode#107870]
Steps to Reproduce:

1. `code --install-extension --force laike9m.cyberbrain`
2. And then VS Code would pop up new file named after the extension

![image](https://user-images.githubusercontent.com/2592205/94774930-acca6600-0373-11eb-946b-627b56ddbb55.png)

I'm not sure if that's the expected behavior, or I'm doing something wrong.

**Comment by bpasero** [comment]
Try with `code --install-extension laike9m.cyberbrain`

**Comment by laike9m** [comment]
Thanks for reply. My understanding is that `--force` force reinstall, and shouldn't change other behavior?

**Comment by bpasero** [comment]
@sandy081 do we support a `--force` to install extensions?

**Comment by sandy081** [comment]
Yes, for forcing to install latest version or older version.

**Comment by bpasero** [comment]
Then I think you should own this and check why your CLI is not being called.

**Comment by sandy081** [comment]
I do handle `force` argument but the extension to install shall be provided after `--install-extension` argument, otherwise there will not values/extensions to install. Hence it does not go to CLI

`code --install-extension laike9m.cyberbrain --force` is the right format.
