### ISSUE TITLE
Intellisense 

### ISSUE THREAD

**Issue by JerryDotseth** [microsoft/vscode#107880]
Issue Type: <b>Bug</b>

My intellisense feature stopped working - I turn on VS Code and Intellisense does not work. I disabled all extensions and it still doesnt work. 

Is there a way to turn intellisense off and on?

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (7.08GB free)|
|Process Argv|--crash-reporter-id 1ce2a321-8445-4221-b5ae-d5e7e7d240d5|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by JerryDotseth** [comment]
What more info do you want?

I turn on VSCode and it doesn’t work.

**Comment by JerryDotseth** [comment]
Why closed?

**Comment by jrieken** [comment]
I have just tried it - IntelliSense works over here. Since you have unwillingness in clarifying this issue it closed as invalid

**Comment by JerryDotseth** [comment]
I willing to clarify anything you want.

What info are you looking for?
