### ISSUE TITLE
Make it possible to expand empty selection into current word when Ctrl+C or Ctrl+X

### ISSUE THREAD

**Issue by jihu** [microsoft/vscode#107881]
I often have the need to copy a single word into the clipboard, often a variable name. A quick double click on the word, followed by Ctrl+C, does the trick. Except when the double click doesn't take. Then the default behavior is to copy the entire line instead. That feature can be disabled, but that still doesn't solve the problem because I just end up with the old clipboard content still in the clipboard, instead of the word that I intended to copy.

This problem is even more likely to happen when color coding of the text makes it more difficult to see quickly if a word is selected or not (for example, when searching for the variable name that you want to select and copy).

For me, it would be really useful it if was possible to configure a third behavior for this. And that is, if Ctr+C is pressed with an empty selection, then expand the selection to cover the word at the cursor position, and then let that selection get copied. The logic of deciding where that word starts and ends should be the same that is used for normal start/end of word logic, and the same logic that is applied when double clicking on a part of a text. So if I put the cursor in the middle of the word "myVariable", then that whole word should be copied when pressing Ctrl+C.

And, to be consistent, this configuration should also effect Ctrl+X, so that the word in question gets cut out and put into the clipboard.

**Comment by alexdima** [comment]
I acknowledge the feature request, but here is what I do:

A good keybinding to get used to is `cmd+d`. It will select the current word and then you can copy the current word using `cmd+d` and `cmd+c`. This is very convenient since on the qwerty keyboard layout, `d`, `c`, and `x` are placed very close to each other.

`cmd+d` is much more powerful than that, it can be used to select the next instance of the current word and do multi-cursor edits, etc. But even for the simple use-case of selecting the current word I find it quite useful.

**Comment by jihu** [comment]
> I acknowledge the feature request, but here is what I do:
> 
> A good keybinding to get used to is `cmd+d`. It will select the current word and then you can copy the current word using `cmd+c`. This is very convenient since on the qwerty keyboard layout, `d`, `c`, and `x` are placed very close to each other.
> 
> `cmd+d` is much more powerful than that, it can be used to select the next instance of the current word and do multi-cursor edits, etc. But even for the simple use-case of selecting the current word I find it quite useful.

I use Ctrl+D for deleting the current line (a feature I use heavily), and all other Ctrl+<Some letter near 'C'> shortcuts are also already in use.

Also, having to use two separate shortcuts every time I want to copy a word kind of defeats the propose :)
