### ISSUE TITLE
Web: opening notebook diff yields error

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#107872]
Steps to Reproduce:

1. web selfhost
2. make changes to our GH notebook
3. diff it

```
Unable to open 'api.github-issues (Working Tree)': Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:9777/static/out/vs/workbench/contrib/notebook/common/services/notebookSimpleWorker.js' failed to load..
```

**Comment by alexdima** [comment]
@rebornix I think you need to add the notebook worker to the build script [here](https://github.com/microsoft/vscode-distro/blob/43ce30bea7256f54f345b743dfb4101b2b8b0d3d/build/gulpfile.vscode.web.js#L69)

**Comment by rebornix** [comment]
Thanks for the pointers. Updated the build scripts.

**Comment by bpasero** [comment]
Verified for September.
