### ISSUE TITLE
Add commands "workbench.action.focus(.*)Group" that do not wrap

### ISSUE THREAD

**Issue by vkottler** [microsoft/vscode#107873]
Issue Type: <b>Bug</b>

1. Launch VSCode
2. Ctrl+N to open new editor
3. Execute command "View: Split Editor Right"
    1. We should now be focused on the right split, we came from the left.
4. Execute command "vew: Focus Right Editor Group"
    1. We are now focused back on the left split.

This is a bug. Right needs to be right, not left. Vice versa.

This makes it impossible to build any sane split-or-navigate logic (e.g. I want a command to "navigate" in a direction, split if there's no where to go, otherwise just focus).

VS Code version: VSCodium 1.49.2 (44f17daa51b1c87f666f9fc28047509297b8e692, 2020-09-25T10:30:41.945Z)
OS version: Windows_NT x64 10.0.20226

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (24.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-neovim|asv|0.0.63
vscode-eslint|dba|2.1.8
viml|dun|0.1.7

</details>

**Comment by vkottler** [comment]
For context, [here's](https://github.com/vkottler/dotfiles/blob/master/vim/vscode.vimrc#L23-L25) what I'm trying to get working.

The function [`winnr()`](https://neovim.io/doc/user/eval.html#winnr()) is correctly giving me a unique window identifier, so if this command wouldn't wrap I could get feature-parity with my primary editing environment.

If this were to come down to a preference thing and not be considered a bug, could a setting be considered to disable wrapping? Would you take a patch submission for that?

**Comment by vkottler** [comment]
Here's a demonstration of why this is a bug, at least to me:

[
![vscode_focus_bug](https://user-images.githubusercontent.com/15205052/94785872-1acb5900-0385-11eb-9b7d-f080d97d5504.gif)
](url)

I'm relying on the assumption that "focus <direction>" only changes the focus in that direction, which is does not. It would be useful if it did so that you can query the editor to see where you ended up and build conditional logic on it (what I'm trying to do, what's trivial to do in [neovim](https://neovim.io/) and [Vim](https://www.vim.org/)).

**Comment by vkottler** [comment]
Just re-tested with extensions disabled to make sure it's not related to specifically what I'm doing.

**Comment by bpasero** [comment]
I think it would break too many users if we changed the existing behaviour but I am fine introducing new commands that do this without wrapping if it helps the VIM case. I would probably not have them appear in the command palette though because seeing them twice may be a bit confusing.

The code that enforces the wrapping is this line:

https://github.com/microsoft/vscode/blob/7ae81709d205071d8105aedc4a9681b37f6dc49b/src/vs/workbench/browser/parts/editor/editorActions.ts#L272-L272

Up for grab if someone wants to add new commands for this.

**Comment by Agreon** [comment]
I will have a look at it

**Comment by bpasero** [comment]
**Verification:** bind keys to the new commands for navigating editor groups without wrap and verify they work. I.e. once you reached the right most group, triggering the command to focus the right group does not go to the first group.

**Command IDs:**
* `workbench.action.focusLeftGroupWithoutWrap`
* `workbench.action.focusRightGroupWithoutWrap`
* `workbench.action.focusAboveGroupWithoutWrap`
* `workbench.action.focusBelowGroupWithoutWrap`
