### ISSUE TITLE
"Insert line above" indents incorrectly when there is a blank line above

### ISSUE THREAD

**Issue by unode** [microsoft/vscode#107823]
### Note

This is a continuation of #28505 which has been closed/locked due to inactivity.

- VSCode Version: 1.45.0
- OS Version: Linux x64 5.7.16

#### Summary

When the line above the cursor is empty and contains no indentation, opening a new line with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd> results in an unindented line regardless of indentation in surrounding context.

#### Steps to Reproduce:

In the code below `^` marks the position of the cursor and `•` one 'space' for indentation:

Given:

```python
def func():
••••var1 = 1

••••^var2 = 2
```

when <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd> is hit, a new line is inserted above but the indentation is not kept.
The cursor is positioned at the start of the line as seen below:

```python
def func():
••••var1 = 1

^
••••var2 = 2
```

the expectation is that the indentation of the block above is kept:

```python
def func():
••••var1 = 1

••••^
••••var2 = 2
```

In contrast, given the following code:

```python
def func():
••••var1 = 1
••••^var2 = 2
```

when <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd> is hit, the new line is added with the correct expected indentation:

```python
def func():
••••var1 = 1
••••^
••••var2 = 2
```

Note as well that if the empty line in the first example **is indented**, opening a line above will also work as expected.

```python
def func():
••••var1 = 1
••••  # Notice indentation here
••••^var2 = 2
```

after <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd>, the following is seen:

```python
def func():
••••var1 = 1
••••
••••^
••••^var2 = 2
```

which matches the expected behaviour.

The only case where it misbehaves is when there is an empty line (without indentation) above the cursor. 

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by unode** [comment]
Tagging @rebornix as a possible reviewer after involvement in the original issue.

**Comment by rebornix** [comment]
Good point. This isn't a bug in how we implement `cmd+shift+enter`, instead it does what we ask it to do (though the behavior is not what we actually expect).

* when pressing `enter` on line 2, onEnterRule will be activated, and inherit the indentation
* when pressing `shift+enter` on line 4, we actually run `enter` on line 3, which has no indentation at all, thus the newly inserted line inherit empty indentation

It's a limitation of how we apply onEnterRules. One potential solution is if the line above the insertion point is empty, we go upwards and find the nearest non-empty line and then uses its indentation for inheritance.

**Comment by unode** [comment]
> It's a limitation of how we apply onEnterRules. One potential solution is if the line above the insertion point is empty, we go upwards and find the nearest non-empty line and then uses its indentation for inheritance

I'm :+: with the workaround, assuming "empty line" means blank spaces (space, tab, ...) are ignored.

**Comment by unode** [comment]
Tagging also @jackfranklin as author of the original #28505 issue.
Please tag also anyone that might have created duplicates or related issues.
