### ISSUE TITLE
Debug dropdown cropped

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#107890]
* create a codespace from an extension you are developing
* open in safari
* open debug viewlet
* 🧀  the top border is cropped

<img width="442" alt="Screenshot 2020-10-01 at 16 38 53" src="https://user-images.githubusercontent.com/1794099/94823894-ab954980-0404-11eb-8364-1d798734af7f.png">

**Comment by rebornix** [comment]
We didn't set `margin-bottom` on debug select and on Safari it falls back to `2px` for no reason (I don't understand as the user agent default is `0em`). I pushed a change to set `margin-bottom` explicitly on Safari, but @isidorn can decide if we want to make it so for all platforms.

**Comment by isidorn** [comment]
@rebornix thanks for pushing a fix, and let's leave this safari specific for now.
