### ISSUE TITLE
Modify standard default highlighting rules

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#10785]
It seems there is not currently ability to modify standard default highlighting rules or to create on top of it.

**Comment by sandy081** [comment]
@whitecolor Can you more specific and detail on what you are looking for?

**Comment by whitecolor** [comment]
Just to be able take standard color scheme(s) and modify it store on the user settings level and use them.

**Comment by sandy081** [comment]
@whitecolor Yes these are provided through theme extensions only not through user settings.
