### ISSUE TITLE
repo broken?

### ISSUE THREAD

**Issue by farhanpurdi** [microsoft/vscode#107813]
- VSCode Version: 1.49.2
- OS Version: Linux x64 5.8.0-kali2-amd64

E: Failed to fetch https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  File has unexpected size (201420 != 200914). Mirror sync in progress? [IP: 52.230.121.169 443]
   Hashes of expected file:
    - Filesize:200914 [weak]
    - SHA512:a91d388504b56c875620f73b618813be1c127d6bfe96406cc6e9a39fdf33f1dd2c8ecbda4a636f0c86bc18005e4f5d0683da0c02ba13c555cef8d11eb83412fe
    - SHA256:1d39334cb2779572dd17869a05d3ed3f1d57992cc9755a34a4d2622132b19f57
    - SHA1:d5224a98d6adfb4ab65d66aa803f9688a6503080 [weak]
    - MD5Sum:2fc601c3aa23f067ef305bfb7f7086e7 [weak]
   Release file created at: Mon, 28 Sep 2020 06:53:06 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by chrmarti** [comment]
@farhanpurdi That appears to be fixed, could you retry?

**Comment by chrmarti** [comment]
Continue tracking in #107793.
