### ISSUE TITLE
Updating the title of a webview view doesn't always update when in the panel

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#107824]
Testing #107626

When a webview view is in the panel (as its own entry), the updates to the title don't always take effect. I haven't yet figured out when this happens, but it seems to happen often after a window reload when the webview in the panel is focused and the title is updated automatically.

I've also seen the panel "tab" selected state stick as well (where it looks like that webview view panel is still selected) even when another panel tab is selected -- though I've only been able to reproduce this once or twice. But these two issues seem somewhat related.

**Comment by eamodio** [comment]
Since posting this, I've gotten this to happen with a normal view (that dynamically updates its title), so this seems like it isn't webview specific.

Here you can see that the GitLens File History isn't focused, but it still looks like it is -- and even when I switch to it, the tab title doesn't get updated with the filename as it should.

![image](https://user-images.githubusercontent.com/641685/94716455-e459f380-031c-11eb-811d-28ffce553d1b.png)

Again this only happens sometimes, and often right after a window reload

**Comment by sbatten** [comment]
@eamodio  can you try this tomorrow, I pushed a related fix but I couldn't explain this behavior with it yet

**Comment by eamodio** [comment]
@sbatten I can't reproduce this case anymore on today's insiders, but now the title of the tab won't get updated if the tab isn't visible. In this case, when the tab becomes inactive, I reset the tab title back to just `File History` and when active it is `File History • filename`, but now it just sticks at `File History • filename` even though it is getting reset.

**Comment by sbatten** [comment]
Yep I reverted the fix for that and will check in the correct fix next iteration.

**Comment by mjbvz** [comment]
@sbatten Just want to confirm you check in the correct fix. I don't see a linked commit

**Comment by sbatten** [comment]
just pushed https://github.com/microsoft/vscode/commit/c2337d8c5658ca5b0b0b0948131f0dc390604755
