### ISSUE TITLE
Look for alternative method of collapsing configurator

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#107835]
Testing #107623

Clicking the graph is not the most intuitive method of collapsing the configurator. I think searching for something more obvious would help. I view the expanded configuration as a legend, esp when in the panel.

**Comment by connor4312** [comment]
I used to have a little arrow/twistie, but that was awkward and I couldn't figure out a good place to put it. I'll think about it some more, open to suggestions as well
