### ISSUE TITLE
WebviewView.onDidChangeVisibility isn't firing properly

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#107827]
Testing #107626

Often when you move a webview view between the panel and sidebar or from a sidebar view into a new sidebar group, the `onDidChangeVisibility` only fires once, and when it fires the `visible` property is set to false. Even though the view is visible.

**Comment by mjbvz** [comment]
I believe the webview is mistakenly being recreated in this case: #107842

The `onDidChangeVisibility` you are seeing with `visible === false` is coming from the old view which is being disposed of see #105879 for that
