### ISSUE TITLE
Command L stopped working. Adds garabage text instead of selecting line.

### ISSUE THREAD

**Issue by rdbrown** [microsoft/vscode#107851]
Issue Type: <b>Bug</b>

Hit command L on MacOs. Doesn't select one line.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (7.48GB free)|
|Process Argv|-psn_0_548998 --crash-reporter-id 7758b878-7bd3-4274-92ba-38ed7913753f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.3.0
path-intellisense|chr|2.3.0
vscode-devtools-for-chrome|cod|0.0.7
git-diff-and-merge-tool|dav|1.0.4
vscode-eslint|dba|2.1.8
vscode-html-css|ecm|0.2.3
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
diff-tool|jin|0.0.1
lorem-whatever|job|1.0.2
color-highlight|nau|2.3.0
vscode-paste-and-indent|Rub|0.0.8

</details>

**Comment by usernamehw** [comment]
/causedByExtension https://marketplace.visualstudio.com/items?itemName=jobe451.lorem-whatever
