### ISSUE TITLE
Enable hiding of Home Indicator in Codespaces

### ISSUE THREAD

**Issue by 2percentsilk** [microsoft/vscode#107846]
Based on a [recently filed issue](https://github.com/MicrosoftDocs/vscodespaces/issues/813) on Codespaces. 

It'd be great to provide the option of hiding the "Go Home/back to GitHub" indicator at the top of the activity bar. This would be in line with the current behavior for other icons in the activity bar.
![HomeIndicator](https://user-images.githubusercontent.com/3174849/94742322-5e44a980-032a-11eb-8a4c-a7bf1070c09a.png)

**Comment by bpasero** [comment]
That is possible today, I am not sure what version of VSCode you are running with:

![image](https://user-images.githubusercontent.com/900690/94778091-d790da80-03c4-11eb-9996-0c1f476cee8e.png)

**Comment by 2percentsilk** [comment]
Weird! Sorry for the noise - it's working for me now!
