### ISSUE TITLE
Slow startup - spending too much time on start => app.isReady

### ISSUE THREAD

**Issue by xz348** [microsoft/vscode#107822]
I've searched for a solution but my case seems to be really rare: the application starts in about 10 seconds and the first part, start=>app.isReady, costs over 80% of the total time.

All extensions disabled. Application started with an empty workspace.

## System Info

* Code: 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a)
* OS: win32(10.0.19041)
* CPUs: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz(8 x 3600)
* Memory(System): 63.85 GB(56.89GB free)
* Memory(Process): 167.15 MB working set(140.75MB private, 0.29MB shared)
* VM(likelyhood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process          | Info                                                    |
| --------------------------------------------------------------- | -------- | ---------------- | ------------------------------------------------------- |
| start => app.isReady                                            | 8076     | [main]           | initial startup: true                                   |
| nls:start => nls:end                                            | 0        | [main]           | initial startup: true                                   |
| require(main.bundle.js)                                         | 48       | [main]           | initial startup: true                                   |
| app.isReady => window.loadUrl()                                 | 95       | [main]           | initial startup: true                                   |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 144      | [main->renderer] | NewWindow                                               |
| require(workbench.desktop.main.js)                              | 385      | [renderer]       | cached data: YES, node_modules took 67.74000000041269ms |
| require & init workspace storage                                | 4        | [renderer]       | -                                                       |
| init workspace service                                          | 24       | [renderer]       | -                                                       |
| register extensions & spawn extension host                      | 109      | [renderer]       | -                                                       |
| restore viewlet                                                 | 0        | [renderer]       | -                                                       |
| restore panel                                                   | 0        | [renderer]       | -                                                       |
| restore editors                                                 | 28       | [renderer]       | 1: PerfviewInput                                        |
| overall workbench load                                          | 142      | [renderer]       | -                                                       |
| workbench ready                                                 | 8880     | [main->renderer] | -                                                       |
| renderer ready                                                  | 571      | [renderer]       | -                                                       |
| extensions registered                                           | 9105     | [renderer]       | -                                                       |

## Extension Activation Stats

| Extension                           | Eager | Load Code | Call Activate | Finish Activate | Event                             | By                                  |
| ----------------------------------- | ----- | --------- | ------------- | --------------- | --------------------------------- | ----------------------------------- |
| vscode.debug-auto-launch            | true  | 3         | 1             | 3               | *                                 | vscode.debug-auto-launch            |
| vscode.emmet                        | true  | 16        | 1             | 2               | *                                 | vscode.emmet                        |
| vscode.git                          | true  | 10        | 1             | 46              | *                                 | vscode.github                       |
| vscode.github                       | true  | 3         | 0             | 0               | *                                 | vscode.github                       |
| vscode.merge-conflict               | true  | 3         | 1             | 3               | *                                 | vscode.merge-conflict               |
| vscode.search-result                | true  | 1         | 0             | 3               | *                                 | vscode.search-result                |
| vscode.configuration-editing        | false | 4         | 1             | 8               | onLanguage:jsonc                  | vscode.configuration-editing        |
| vscode.extension-editing            | false | 20        | 1             | 2               | onLanguage:markdown               | vscode.extension-editing            |
| vscode.github-authentication        | false | 4         | 0             | 20              | onAuthenticationRequest:github    | vscode.github-authentication        |
| vscode.json-language-features       | false | 21        | 6             | 8               | onLanguage:jsonc                  | vscode.json-language-features       |
| vscode.markdown-language-features   | false | 10        | 2             | 0               | onLanguage:markdown               | vscode.markdown-language-features   |
| vscode.microsoft-authentication     | false | 7         | 2             | 260             | onAuthenticationRequest:microsoft | vscode.microsoft-authentication     |
| vscode.typescript-language-features | false | 7         | 2             | 6               | onLanguage:jsonc                  | vscode.typescript-language-features |

## Raw Perf Marks

```
Name	Timestamp	Delta	Total
main:started	1601483505881	0	0
main:appReady	1601483513957	8076	8076
willLoadMainBundle	1601483513960	3	8079
didLoadMainBundle	1601483514008	48	8127
main:loadWindow	1601483514052	44	8171
renderer/started	1601483514190	138	8309
willShowPartsSplash	1601483514191	1	8310
didShowPartsSplash	1601483514192	1	8311
willLoadWorkbenchMain	1601483514196	4	8315
didLoadWorkbenchMain	1601483514581	385	8700
main/startup	1601483514581	0	8700
willInitWorkspaceService	1601483514587	6	8706
willInitWorkspaceStorage	1601483514597	10	8716
didInitWorkspaceStorage	1601483514601	4	8720
didInitWorkspaceService	1601483514611	10	8730
willStartWorkbench	1601483514619	8	8738
LifecyclePhase/Ready	1601483514620	1	8739
willRestoreEditors	1601483514733	113	8852
didRestoreEditors	1601483514761	28	8880
LifecyclePhase/Restored	1601483514761	0	8880
didStartWorkbench	1601483514761	0	8880
didRemovePartsSplash	1601483514761	0	8880
willLoadExtensions	1601483514877	116	8996
willHandleExtensionPoint/configurationDefaults	1601483514921	44	9040
didHandleExtensionPoint/configurationDefaults	1601483514927	6	9046
willHandleExtensionPoint/configuration	1601483514927	0	9046
didHandleExtensionPoint/configuration	1601483514941	14	9060
willHandleExtensionPoint/jsonValidation	1601483514941	0	9060
didHandleExtensionPoint/jsonValidation	1601483514942	1	9061
willHandleExtensionPoint/commands	1601483514942	0	9061
didHandleExtensionPoint/commands	1601483514943	1	9062
willHandleExtensionPoint/submenus	1601483514943	0	9062
didHandleExtensionPoint/submenus	1601483514943	0	9062
willHandleExtensionPoint/menus	1601483514943	0	9062
didHandleExtensionPoint/menus	1601483514946	3	9065
willHandleExtensionPoint/debuggers	1601483514946	0	9065
didHandleExtensionPoint/debuggers	1601483514949	3	9068
willHandleExtensionPoint/breakpoints	1601483514949	0	9068
didHandleExtensionPoint/breakpoints	1601483514949	0	9068
willHandleExtensionPoint/problemPatterns	1601483514949	0	9068
didHandleExtensionPoint/problemPatterns	1601483514950	1	9069
willHandleExtensionPoint/problemMatchers	1601483514950	0	9069
didHandleExtensionPoint/problemMatchers	1601483514950	0	9069
willHandleExtensionPoint/taskDefinitions	1601483514951	1	9070
didHandleExtensionPoint/taskDefinitions	1601483514951	0	9070
willHandleExtensionPoint/terminal	1601483514951	0	9070
didHandleExtensionPoint/terminal	1601483514951	0	9070
willHandleExtensionPoint/viewsWelcome	1601483514951	0	9070
didHandleExtensionPoint/viewsWelcome	1601483514951	0	9070
willHandleExtensionPoint/authentication	1601483514951	0	9070
didHandleExtensionPoint/authentication	1601483514951	0	9070
willHandleExtensionPoint/keybindings	1601483514951	0	9070
didHandleExtensionPoint/keybindings	1601483514957	6	9076
willHandleExtensionPoint/languages	1601483514957	0	9076
didHandleExtensionPoint/languages	1601483514962	5	9081
willHandleExtensionPoint/codeActions	1601483514962	0	9081
didHandleExtensionPoint/codeActions	1601483514962	0	9081
willHandleExtensionPoint/customEditors	1601483514962	0	9081
didHandleExtensionPoint/customEditors	1601483514963	1	9082
willHandleExtensionPoint/snippets	1601483514963	0	9082
didHandleExtensionPoint/snippets	1601483514963	0	9082
willHandleExtensionPoint/grammars	1601483514963	0	9082
didHandleExtensionPoint/grammars	1601483514972	9	9091
willHandleExtensionPoint/colors	1601483514972	0	9091
didHandleExtensionPoint/colors	1601483514972	0	9091
willHandleExtensionPoint/semanticTokenScopes	1601483514972	0	9091
didHandleExtensionPoint/semanticTokenScopes	1601483514972	0	9091
willHandleExtensionPoint/themes	1601483514972	0	9091
didHandleExtensionPoint/themes	1601483514973	1	9092
willHandleExtensionPoint/iconThemes	1601483514973	0	9092
didHandleExtensionPoint/iconThemes	1601483514973	0	9092
willHandleExtensionPoint/viewsContainers	1601483514973	0	9092
didHandleExtensionPoint/viewsContainers	1601483514976	3	9095
willHandleExtensionPoint/views	1601483514976	0	9095
didHandleExtensionPoint/views	1601483514979	3	9098
extensionHostReady	1601483514980	1	9099
didLoadExtensions	1601483514986	6	9105
LifecyclePhase/Eventually	1601483517269	2283	11388
```

**Comment by deepak1556** [comment]
Can you update to the latest stable `1.50.0` and if you still see the slowdown, can you take the following trace 

* Create trace.json somewhere on your disk with the following content:

```
{
 "result_file": "<some-absolute-writable-path>\chrometrace.log",
 "trace_config": {
 "record_mode": "record-until-full",
 "included_categories": [
     "blink",
     "browser",
     "io",
     "ipc",
     "content",
     "navigation",
     "renderer",
     "renderer_host",
     "latency",
     "benchmark",
     "gpu",
     "cc",
     "toplevel",
     "viz",
     "v8",
     "disabled-by-default-sequence_manager.debug",
    "disabled-by-default-renderer.scheduler"
 ],
 "excluded_categories": ["*"]
 }
}
```

* Start `code --trace-config-file="<absolute-path-to>\trace.json"`
* Verify that startup slowdown is seen
* Quit the editor

Attach the generated chrometrace.log

**Comment by xz348** [comment]
Thanks for your help! I actually resolved the problem by re-installing Windows 10... I believe this issue is not related to VS Code but the OS because I also noticed there're other programs experiencing such "deferred start-up" issues.
