### ISSUE TITLE
`RenameOperation` always saves before applying

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#107815]
See https://github.com/microsoft/vscode/issues/107739

We should discuss how we want to approach applying a rename operation to a dirty text buffer, because today moving a dirty text buffer results in a stack element being pushed to the undo/redo service, which is unexpected when the move is executed as part of a workspace edit rename operation.

**Comment by bpasero** [comment]
@alexdima 

> today moving a dirty text buffer results in a stack element being pushed to the undo/redo service

Did you find out what line triggers this when the move operation runs?

**Comment by jrieken** [comment]
I think we have seen it somewhere around here: https://github.com/microsoft/vscode/blob/fd4d8ddc1994c16583b12e12b38ba48283c2102e/src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts#L259

@alexdima one idea that I had is if we could pass along the undo-redo-group all to move operation so that the code above picks it up.

**Comment by bpasero** [comment]
Well, if the model was dirty I need to restore the contents after the move operation, so unless there is a way for me to do that without causing an undo-step, I am not sure what I can do to not loose unsaved data?

**Comment by jrieken** [comment]
Yep - that's the challenge

**Comment by alexdima** [comment]
@jrieken Even if we pass the undo-redo group, that isn't helpful, that just reduces the number of times undo needs to be executed (it is just a grouping thing)... The problem will remain that while undoing, the RedoOperation will move to the redo stack and while running there will be a new stack element pushed onto the undoredo and will delete the future. So effectively, an undo on `RedoOperation` undoes it and erases it from the redo stack.

**Comment by alexdima** [comment]
So the root thing here is that we need to have an implementation of `RenameOperation` which is independent of the undo-redo service... since it is not expected that undoing will call `pushElement` again.

**Comment by bpasero** [comment]
@alexdima I pushed my changes to ensure a text model get's created with the  contents of the file that was moved, thus we no longer update the model after it moved. Can you try to revert the changes you had to do for undo/redo to work properly and report back if that fixes the issue?

**Comment by alexdima** [comment]
@bpasero I've tried it, but it seems that some edits get lost in the move operation I believe... I am doing the steps of https://github.com/microsoft/vscode/issues/107739#issuecomment-701459336 and an undo and a redo. The text buffer edits get lost. I think the second move loses the file contents. I also see something off with the dirty indicator, so it might be related to the text buffer version ids ... it looks like the workbench believes the file is saved on disk with a different content than it actually is.

We can try debugging together or you can try the steps above, LMK.
