### ISSUE TITLE
slow performance

### ISSUE THREAD

**Issue by michelerenda2** [microsoft/vscode#107817]
Issue Type: <b>Performance Issue</b>

When i do a retrieve my pc doesn't work, it is almost stucked!

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.99GB free)|
|Process Argv|--crash-reporter-id b230da7f-9568-4538-ad09-df664f8867bc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    73	 22000	code main
    0	    82	 11656	   window (Issue Reporter)
    0	    38	 13356	   utility
    2	    89	 14764	   shared-process
    0	   245	 15060	   window (SFACommodity_ControllerTest.cls - devRebuild - Visual Studio Code)
   20	   151	  6912	     extensionHost
    0	     4	  2092	       C:\Windows\system32\cmd.exe /d /s /c "java -Dfile.encoding=UTF-8  -jar "c:\Users\mrend\.vscode\extensions\chuckjonas.apex-autocomplete-0.2.13\bin\tooling-force.jar" --action=serverStart --port=65000 --timeoutSec=1800"
    0	     7	 14056	         java  -Dfile.encoding=UTF-8  -jar "c:\Users\mrend\.vscode\extensions\chuckjonas.apex-autocomplete-0.2.13\bin\tooling-force.jar" --action=serverStart --port=65000 --timeoutSec=1800
    5	    35	 11676	           "C:\Program Files\Java\jdk-11.0.8\bin\java.exe" -Dfile.encoding=UTF-8 -jar c:\Users\mrend\.vscode\extensions\chuckjonas.apex-autocomplete-0.2.13\bin\tooling-force.jar --action=serverStart --port=65000 --timeoutSec=1800
    0	    10	 18280	         console-window-host (Windows internal process)
    0	    12	 14184	     watcherService 
    0	    11	 12152	       console-window-host (Windows internal process)
    0	    68	 15916	     searchService
    0	    25	 20156	   crashpad-handler
    0	   162	 20636	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (SFACommodity_ControllerTest.cls - devRebuild - Visual Studio Code)
|    Folder (devRebuild): 10014 files
|      File types: xml(2811) cls(2609) js(1358) cmp(589) ts(417) css(398)
|                  design(255) auradoc(227) svg(219) json(97)
|      Conf files: package.json(2) launch.json(1) settings.json(1)
|                  jsconfig.json(1) webpack.config.js(1)
|      Launch Configs: apex-replay;
```

</details>
<details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-snippets|aji|1.2.1
salesforce-soql-editor|all|0.3.4
vscode-salesforce|app|0.4.2
apex-autocomplete|chu|0.2.13
apex-debug|chu|1.0.3
salesforce-diff|chu|0.0.7
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
vscode-salesforce-toolkit|dro|1.2.2
prettier-vscode|esb|5.7.1
vscode-firefox-debug|fir|2.9.1
salesforce-code-snippets|Hel|1.1.0
sfdx-autoheader|Hug|0.7.1
salesforce-snippets|lco|0.4.0
dx-code-companion|Moh|0.4.7
notepadplusplus-keybindings|ms-|1.0.5
lwc-salesforce|Nik|2.0.0
sfdc-qcp-vscode-extension|pau|1.0.4
salesforce-code-snippets|pav|0.0.4
vscode-xml|red|0.13.0
schema-explorer|Roh|0.5.1
salesforce-vscode-slds|sal|1.2.1
salesforcedx-vscode|sal|49.11.0
salesforcedx-vscode-apex|sal|49.11.0
salesforcedx-vscode-apex-debugger|sal|49.11.0
salesforcedx-vscode-apex-replay-debugger|sal|49.11.0
salesforcedx-vscode-core|sal|49.11.0
salesforcedx-vscode-lightning|sal|49.11.0
salesforcedx-vscode-lwc|sal|49.11.0
salesforcedx-vscode-visualforce|sal|49.11.0
lightning-component-snippets|Ter|1.0.8
snippets-for-salesforce-devs|vic|2.0.1

</details>

**Comment by Tyriar** [comment]
Looks like the extension host is using 20% CPU (maybe one core?), this is likely related to one of your 32 extensions.
