### ISSUE TITLE
Disabling last item is not smooth

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#107829]
Testing #107623

I see that when you disable the last item in the graph, on the next tick, the first 2 items are re-enabled. The interaction feels choppy and almost like a bug. I would think it is not necessary to do this, allowing an empty graph should be okay. If we must show something, I think the interaction should instantly change state.

**Comment by connor4312** [comment]
Are you doing this through the quickpick or by clicking items inside the view?

**Comment by sbatten** [comment]
items in the view

**Comment by connor4312** [comment]
Hm, am I doing something differently than you? https://memes.peet.io/img/20-09-b89036d8-7ce7-4969-a571-cfaf124e0bb5.mp4

**Comment by sbatten** [comment]
![recording (2)](https://user-images.githubusercontent.com/6561887/94736650-6cda9300-0321-11eb-8601-30d824964ef2.gif)

**Comment by connor4312** [comment]
Ah, thanks, I actually fixed that in https://github.com/microsoft/vscode-js-profile-visualizer/commit/181d5317ce4443c8521efffd5c93571ed1d5aee9#diff-ed37fc08d14745b61a4bfafdeaec836e -- I thought before it was just causing some extra DOM stuff, but it looks like it also caused this bug.
