### ISSUE TITLE
Toogle Word Wrap

### ISSUE THREAD

**Issue by Subhash-subh1** [microsoft/vscode#107812]
Issue Type: <b>Feature Request</b>

When I click on Toogle Word Wrap option but that option not activate. please tell me how I activate that

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041

**Comment by alexdima** [comment]
@Subhash-subh1 I'm sorry, I don't understand what you mean. What do you click on?
