### ISSUE TITLE
Windows: Code should run as same user after updating

### ISSUE THREAD

**Issue by Timmmm** [Microsoft/vscode#10783]
- VSCode Version: 1.1.1
- OS Version: Windows 7, 64-bit

Steps to Reproduce:
1. Be on an annoying corporate network where the standard admin account doesn't work, but you have another "local admin" account that does.
2. Install VS Code using the local admin account.
3. Run it as a non-admin user.
4. Try to install an extension.
5. Observe the message "Visual Studio Code will be update after it restarts"
6. Click "Update Now"
7. VSC restarts but shows a dialog "You must be logged in as an administrator when installing this program."
8. Run VSC as the local admin account ("Run as different user"; not "Run as administrator").
9. Try to install the extension again
10. This time it works, but it only installed it for the local admin account, not for my standard account.
11. Run VSC as a non-admin user.
12. Extension is not installed.

**Comment by Timmmm** [comment]
I solved it in my case by manually copying the extension files from the admin account, i.e.:

    copy c:\Users\local-admin\.vscode\extensions\saviorisdead.RustyCode-0.17.0 c:\Users\me\.vscode\extensions\saviorisdead.RustyCode-0.17.0

Actually most of the files were there, and the only missing ones were `package.json`, `README.md`, `ROADMAP.md`, and `tslint.json`. I copied those and then it worked fine.

**Comment by Timmmm** [comment]
Actually, the "You must be logged in as an adminsitrator when installing this program" was about upgrading VSC from 1.1 to 1.4. Still weird that not all of the RustyCode extension was installed though.

**Comment by sandy081** [comment]
@joaomoreno this looks to me a dup of #534 if so, please close it. Otherwise a new issue for you :).

**Comment by joaomoreno** [comment]
Yeah, you seem to be mixing up installing extensions with updating Code.

What very likely happened was that Code was launched under the Admin user after updating, which is the bug.

You can now install extensions successfully right?

**Comment by Timmmm** [comment]
Ah yes it works now. I think I was confusing the VSC update with the extension installation, which wasn't working because VSC couldn't update. Sorry!

**Comment by joaomoreno** [comment]
I'll reopen and use this issue for its current title: `Windows: Code should run as same user after updating`

**Comment by joaomoreno** [comment]
Closing in favour of #1614
