### ISSUE TITLE
Horizontal Scrolling With Wheel Broken

### ISSUE THREAD

**Issue by A5hot** [microsoft/vscode#107848]
Issue Type: <b>Bug</b>

Scrolling with the secondary wheel on mx master 3, which is used for horizontal scrolling, will work for a moment, causing the page to scroll horizontally by an inch, then no longer work. Works intermittently but usually does not work.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.40GB free)|
|Process Argv|--crash-reporter-id b50f32c4-208f-4f58-b107-2edd291e141c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
python|ms-|2020.9.112786
jinjahtml|sam|0.15.0
jinja|who|0.0.8

</details>

**Comment by alexdima** [comment]
Let's track in #96986
