### ISSUE TITLE
Source control window loads endlessly

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vscode#107898]
- VSCode Version: 1.49.2
- OS Version: Windows_NT x64 10.0.18363

When i do changes in terminal, sometimes (once a week) the auto update of the source control windows gets broken. It loads endlessly. Refresh button does not help.

![grafik](https://user-images.githubusercontent.com/10581931/94836688-8eb44280-0413-11eb-91bc-b16778c4285b.png)
![grafik](https://user-images.githubusercontent.com/10581931/94836652-81975380-0413-11eb-8a2e-85c7854fea45.png)

This is sad because i need to restart vscode and loose all settings like open terminals and their environment settings.
Is there a way to reset the source contol autoupdate?

Steps to Reproduce:

1. Set git bash as terminal for VSCode
2. Do stuff in git bash (commit, rebase etc)

Does this issue occur when all extensions are disabled?: Unknown

**Comment by joaomoreno** [comment]
Can you reproduce the issue while having `Git: Show Git Output` open? Can you share the contents of that output?
