### ISSUE TITLE
Auto detect color scheme sets one theme for all open windows despite different preferred schemes set in workspaces

### ISSUE THREAD

**Issue by felixbinder** [microsoft/vscode#107855]
- VSCode Version: 1.49.2
- OS Version: macOS 10.15.7 (19H2)

Steps to Reproduce:

1. Open two different workspaces
2. Edit the corresponding workspace settings to with different themes for `workbench.preferredDarkColorTheme` and `workbench.preferredLightColorTheme` 
3. Enable `window.autoDetectColorScheme`
4. Switch to/from dark mode

Expected behavior: each window switches to the theme specified in the workspace settings. This is how it used to be before updating to the last version.

Actual behavior: both windows switch to a theme specified in one of the workspace settings (the one of the foregrounded window). The `workbench.colorTheme` for user is changed to the theme.

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
Related: https://github.com/microsoft/vscode/issues/105715
