### ISSUE TITLE
Debugger of Python's default setting failed

### ISSUE THREAD

**Issue by CosmoGao** [Microsoft/vscode#10786]
- VSCode Version:1.3.1
- OS Version:Windows 10 build 14393

Steps to Reproduce:

1. Install "Python" extension;
2. Create a .py file;
3. Press F5 to debug;
4. Application will auto-create a "launch.json" file;
5. line 9: "pythonPate": "${config.python.pythonPath}"
6. Fail to launch the Python Process, please vaildate the path "${config.python.pythonPath}"
7. I changed the setting.json, not work.
8. Update line 9 to "python", debugger will work.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/pythonVSCode#260
