### ISSUE TITLE
[Firefox] Select all doesn't work in input boxs

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#107847]
**Repro**
1. Open https://vscode-web-test-playground.azurewebsites.net/?enter=true in firefox
1. Open the find widget
1. Try using the standard select all keyboard shortcut (cmd+a on Mac) in the find widget 

**Bug**
Select all doesn't work

It works in the editor and in both Safari and Chrome

**Comment by rebornix** [comment]
No idea why `document.execCommand('selectAll')` doesn't work on Firefox.
