### ISSUE TITLE
Debug Console Shows wrong source for logpoint messages

### ISSUE THREAD

**Issue by KyleRAnderson** [microsoft/vscode#107860]
Issue Type: <b>Bug</b>

After debugging with the "Run Current File" configuration, the output from logpoints within that debug session showed up under the label of "Debug Unit Tests" (from the Python extension). This fixed itself when I switched to and from the debug sources.

1. Run Unit tests (in my case, I was using the Python extension) in Debug mode.
1. Run another launch configuration that has logpoints enabled in debug mode, while the debug console is not in focus.
1. Navigate to the debug console and verify that the correct console is showing the correct output.

I'm not sure if there is something specific to this having been unit tests running or not, or if it is possibly a problem with the Python extension.

Screenshot:
![image](https://user-images.githubusercontent.com/22606608/94758105-43922500-036a-11eb-84f0-84b69bbc334e.png)
In the above screenshot, the output that is being displayed was generated by the "Run Current File" launch configuration, but initially shows up under "Debug Unit Tests". This is the problem.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.13GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/home/kylek/repos/uwaterloo/se_212_george --crash-reporter-id 732ba2ab-8246-4b39-aa91-70d245f12e42|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|6.14GB (5.24GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.140.1
remote-wsl|ms-|0.44.5
slim|sia|0.1.2
vscode-ruby|win|0.27.0
rails|bun|0.16.7
vscode-gemfile|bun|0.4.0
solargraph|cas|0.21.1
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
todo-tree|Gru|0.0.178
vscode-rufo|jnb|0.0.1
vscode-docker|ms-|1.6.0
python|ms-|2020.9.112786
vscode-pylance|ms-|2020.9.7
ruby|reb|0.27.0
java|red|0.68.0
slim|sia|0.1.2
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-ruby|win|0.27.0

</details>

**Comment by isidorn** [comment]
This sounds like an issue in VS Code. However I can not reproduce it.
@KyleRAnderson is it possible to put some reopsitory on GitHub which I can clone and easily reproduce this?
Also can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by KyleRAnderson** [comment]
Hi @isidorn.

I have made a repository in which I can reproduce the bug consistently: https://github.com/KyleRAnderson/VSCode-bug-reproducible.

There are instructions in the repository's README with what you can do to get it to happen again.

Unfortunately I do not have time right now to reproduce it on VSCode insiders, though hopefully the steps above are enough.

Thanks!

**Comment by isidorn** [comment]
@KyleRAnderson thanks a lot for great steps. I have pushed a fix and VS Code insiders should have the fix tomorrow. So if you have time would be great if you doulbe check. Though I verified the fix fixes the issue here.

**Comment by KyleRAnderson** [comment]
Awesome, I'm really glad to hear that it's been fixed so quickly, I only found it yesterday. I'll try it out on VSCode insiders tomorrow, 
I should have time for that. Thank you @isidorn!

**Comment by isidorn** [comment]
Great, thanks!

**Comment by KyleRAnderson** [comment]
I tried this out on VSCode insiders again, I can confirm that it is functioning as expected now.

**Comment by isidorn** [comment]
Great, thanks for letting us know. Adding verified label.

**Comment by isidorn** [comment]
We had to revert the fix, thus reopening this.
@roblourens let me know if I missed a commit and if you also pushed a fix for this.

**Comment by KyleRAnderson** [comment]
/verified, see https://github.com/microsoft/vscode/issues/107860#issuecomment-702714610.

**Comment by isidorn** [comment]
Thanks a lot
