### ISSUE TITLE
Debug mode, the value of the variable error

### ISSUE THREAD

**Issue by whwnow** [Microsoft/vscode#1078]
Hi~
in the function b, the paramether id is a string 'id from middleware'. but vs code tell me it's a object and equal to the second parameter.

I think the pictures is more intuitive.  beg your pardon for my English. T T

https://c.hime.io/images/L0o.png

```javascript
'use strict';
const koa = require('koa');
const app = koa();
function* b(id, {
	age,
	name = 'name from b'
}) {
	console.log(id);
	return {
		id: id,
		name: name,
		age: age
	}
}
app.use(function* () {
	let {
		age: returnB
	} = yield* b('id from middleware', {
		age: 25
	});
	this.body = 'returnB(age):' + returnB;
});
app.listen(3001);

```

**Comment by isidorn** [comment]
In the call stack pane what is the focussed stack frame? The console always evaluates against the `top stack frame`, while the hover and the watch expression evaluate against the `focussed stack frame` - the one you choose.
I would guess that you have selected a different stack frame thus the difference in evaluation

**Comment by whwnow** [comment]
http://ww1.sinaimg.cn/large/0060lm7Tgw1eyt461wk05j317d0swq8m.jpg
Hi ,here is the call stack

**Comment by isidorn** [comment]
Keyword const is not highlighted because we use textmate grammers and I guess they do not highlight keyword 'const' atm.

@weinand It seems that the parameters `id` and `age` in this function get confused. Might you have an idea why this happens?

**Comment by whwnow** [comment]
Hi,  what more info do I need to provide? I'd like to do that, if  it's hlepful

**Comment by weinand** [comment]
This works fine in VS Code 1.3.0 and node 6.2.2:

![2016-07-06_16-16-39](https://cloud.githubusercontent.com/assets/1898161/16621021/174dfca6-4395-11e6-892f-b8199c586465.png)
