### ISSUE TITLE
After debug (of extension) file is not editable

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#10781]
- VSCode Version: insiders
- OS Version: windows 10

Steps to Reproduce:

I start debugging extension. After debug is stopped. I can not fully edit extensions code some commands (keys) like backspace don't work, can insert and add content, but can not remove it.

I have to do `Ctrl+P` and type file name and "activate" it - then edit mode fixes.

Not sure if it happens only while extensions debug.

**Comment by sandy081** [comment]
@whitecolor This issue does not happen to me. Can you please provide more information that will help us to reproduce it. say,

- Is there anything difference in your workspace/set up, any extensions as such
- I assume by debugging extension you mean launching the extension you are developing
- what do you mean by activate?

**Comment by whitecolor** [comment]
Well it stops to reproduce after insiders update, maybe it is gone for me too.

**Comment by sandy081** [comment]
Thank you, closing this.
