### ISSUE TITLE
Update webview view's urls to contain the extension id like normal webviews

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#107820]
Testing #107626

I was using the following in my `launch.json`:

```json
"debugWebviews": true,
"rendererDebugOptions": {
	"urlFilter": "*eamodio.gitlens*",
	"webRoot": "${workspaceFolder}/src/webviews/apps"
},
```

And was unable to get js-debug to debug my new webview view (although normal webviews worked fine). @connor4312 pointed out the `urlFilter` and when I removed that everything worked.

Looking at the urls attached, you can see the difference between a normal webview and the webview view:

![image](https://user-images.githubusercontent.com/641685/94713608-0c475800-0319-11eb-8388-b7769dc873b5.png)

We should probably add the extension id into the webview view's url, so that we can consistently only attach to the webviews we want.

**Comment by connor4312** [comment]
Thanks, I was just about to open this issue 🙂

**Comment by connor4312** [comment]
I hacked it in in the linked commit; not very familiar with this part of the code. Let me know if you think it's worth PRing @mjbvz

**Comment by connor4312** [comment]
I don't think so -- I pushed a tentative commit to a branch but didn't merge it
