### ISSUE TITLE
Debug: Open Link requires access to weird stuff

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#107839]
Using "Debug: Open Link" asks for access to System Events, any idea why?

![image](https://user-images.githubusercontent.com/323878/94729740-fb95e280-0316-11eb-830f-701b9c1db61a.png)

**Comment by connor4312** [comment]
Open Link is just a thin wrapper around vscode.debug.startDebugging. Have you debugged Chrome recently/before on that install? Maybe just launching Chrome requires that info?

**Comment by roblourens** [comment]
Oh, that's probably it. Haven't launched Chrome recently.
