### ISSUE TITLE
Zen mode stuck

### ISSUE THREAD

**Issue by journey-of-code** [microsoft/vscode#107868]
- VSCode Version: 1.49.2 (user setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Enter Zen mode
2. Restart computer
3. Open VSCode
4. Got this:
![image](https://user-images.githubusercontent.com/1939047/94773349-ddce8900-03bb-11eb-8e66-6ccaefa0a9db.png)
(The tab area is not maximized in the surrounding container)

Does this issue occur when all extensions are disabled?: Yes

Any newly opened VSCode windows don't show this behavior. The "main" window however is stuck with this Zen-mode-leftover. Switching to and from Zen mode changes nothing, but Zen mode works as intended.
If I remember correctly, the bug even persisted through the last update of VSCode. Restarting didn't help either. It is possible to resize the inner container like in Zen mode, but not to the extent to fill the entire inner area. What can I do to reset this? Should I look into anything before doing that?

**Comment by journey-of-code** [comment]
> 
> 
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Zen mode (#97773)](https://www.github.com/microsoft/vscode/issues/97773)
> 
>     * [Open Zen Mode thorough command line arguments (#103223)](https://www.github.com/microsoft/vscode/issues/103223)
> 
>     * [Zen Mode Settings (#45617)](https://www.github.com/microsoft/vscode/issues/45617)

Not related to any of the issues the bot suggested.

**Comment by isidorn** [comment]
`F1 > toggle centered layout` 
should fix the issue for you

Following your steps I can not get into the "broken" state you ended up in

**Comment by journey-of-code** [comment]
Thank you @isidorn - that fixed it for me. Feel stupid now. On the other hand there was no way for me to find out what to do as I didn't toggle it in the first place. I don't even have a shortcut defined for that. So I guess it was caused by a small bug. But I agree that this should be closed as it only happened once and cannot be reproduced.

**Comment by isidorn** [comment]
No need to feel stupid. There was an issue. The centered mode is a subset of zen mode which should be automatically toggled out of if zen mode is no longer active.
Let me know if you see it again and if you find repro steps. Thanks
