### ISSUE TITLE
Code folding does not collapse to terminating bracket

### ISSUE THREAD

**Issue by Orum** [microsoft/vscode#107811]
- VSCode Version:  1.49.1
- OS Version: Linux x64 5.8.6-1-MANJARO

Steps to Reproduce:

1. Create a source file in a bracketed language, e.g. C++.
2. Add a comment similar to that shown here: ![source](https://files.catbox.moe/znu2eh.webp)
3. Attempt to collapse the code block, and notice it doesn't collapse to the terminating scope.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
@Orum Are you using the C++ extension? If yes, this is issue https://github.com/microsoft/vscode-cpptools/issues/5523

If you do not have an extension that provides language aware folding, then VSCode falls back to indentation based folding.
