### ISSUE TITLE
resourceFolder of a folder is it's parent

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#107802]
Testing #107638

`resourceFolder` of a folder is it's parent. I find this slightly confusing.
I thought a resourceFolder of a folder resource is itself.

Maybe `resourceDirname` would be a better name to allign better with Node and then users might not be surprised
https://nodejs.org/api/path.html#path_path_dirname_path

Sorry for not providing this feedback earlier. Just my 2 cents

**Comment by eamodio** [comment]
Yeah, I am with you. It tripped me up at first as well. I will rename to `resourceDirname` as you suggest. Thanks!

**Comment by isidorn** [comment]
Great, thanks!
