### ISSUE TITLE
[explorer.sortOrder] Folders first.

### ISSUE THREAD

**Issue by infacto** [microsoft/vscode#107803]
The setting `explorer.sortOrder` should allow to sort folders first. Alphabetical order (natual sort), but folders first, then files. Like in Windows file explorer. I'm not sure if this behavior has changed in VS Code. So it's maybe a bug. I see that the root directoy of my workspace is ordered by folders first. But some subfolders not. ...

Demo (actual)

![image](https://user-images.githubusercontent.com/60390085/94671294-fe430880-0313-11eb-9413-7787ba04526c.png)

Demo (expected)
```text
src
|- app
|  |- > providers
|  |- app.component.html
|  |- app.component.scss
|  |- app.component.ts
|  |- main.ts
|- > assets
|- > pages
|- > theme
|- index.html
|- manifest.json
|- service.worker.js
```
(maybe not perfect sorted by alphabetic order, I'm just a human. ^^ But it should illustrate the expected behavior (folders first))

I tried all values for this settings. There is a `filesFirst` value. We should add a `foldersFirst` and / or set this behavior as `default`. Or just fix this bug, if this is a bug. ...
 
```text
Version: 1.49.2 (user setup)
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:29:41.983Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is your current value for `explorer.sortOrder`? Looks like `mixed` or `filesFirst`, because in other cases folders will be displayed first (works as expected on 1.49.2).
Please check that it's not overridden on folder/workspace level.

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by infacto** [comment]
This was weird. Now it works. Because I removed the entry `mixed` from the user settings.json. 😄 This is not trolling. Please believe me: I tested this multiple times. I edit the settings.json. And duplicate entries are highlighted in VS Code. I can swear that this was not set. This setting is maybe from my tests for this issue. This means it was not set before. But now, I'm not 100% anymore. The question is, who set this value? ^^ I wouldn't do this. ... I don't know. Maybe I'm getting senile.  
Maybe there is a bug. Hopefully not. For now, I cannot reproduce it. ... Sorry to bother you. ❤️
