### ISSUE TITLE
Sort Settings by Release Date

### ISSUE THREAD

**Issue by cmario92** [microsoft/vscode#107831]
As I user, I want the ability to sort the settings, by Release Date.

It is very hard to keep up with the Roadmap, commits and Release Notes(Insiders?) for every update we get(daily). Sorting the settings by the timestamp added, we will be able to figured out what was added, as well as what was not modified/tweaked for our projects in VSCode.

**Comment by roblourens** [comment]
We have discussed this, but we don't really think that the settings editor is the right place for this kind of info. Maybe we would have a more comprehensive "What's new" experience in vscode but not a one-off for the settings editor. If it helps, the release notes are only updated once a month, so you can just read them for each stable release at the end of the month to stay up to date :)
