### ISSUE TITLE
Relative Line Numbers: an option to have 0 as the current line number.

### ISSUE THREAD

**Issue by mrillusi0n** [microsoft/vscode#107869]
A setting that allows for displaying 0 as the current line number when relative numbering is on.

**Comment by ajaeshawn** [comment]
Out of curiosity, what is your use-case for relative line numbers? I've always wondered who that feature was useful for.

**Comment by mrillusi0n** [comment]
@ajaeshawn It's because I use the Vim extension. Say you're on line 132, and spot where you want to make the next change, see that it's on line 147. You'd probably use the mouse to reach it. But with Vim and relative numbering, 132 would be 0, and 147 would be 15, which would indicate that the line I'm interested in is 15 lines down, so I'd just do `15j` to reach there. You might wanna do more research on modal editing.
