### ISSUE TITLE
Markdown Preview not correct

### ISSUE THREAD

**Issue by jmtian** [Microsoft/vscode#10789]
- VSCode Version:1.4.0
- OS Version:win10

Steps to Reproduce:

1. open a markdown file, write ##sample
2. show preview, the preview is ##sample

**Comment by rcneves** [comment]
You should write "## sample" (with a space between "##" and "sample")

**Comment by jmtian** [comment]
But many other editors support this(without the space between).

在 2016年8月23日，00:22，rcneves <notifications@github.com> 写道：

You should write "## sample" (with a space between "##" and "sample")

**Comment by rcneves** [comment]
This don't :)
See "oficial syntax proposal" at: https://daringfireball.net/projects/markdown/syntax#header
It makes sense to separate "markup" from "information"

**Comment by sandy081** [comment]
Duplicates #8376

**Comment by jmtian** [comment]
ok, thanks for your patience !



tjm98@126.com
 
From: rcneves
Date: 2016-08-23 00:44
To: Microsoft/vscode
CC: kiddo; Author
Subject: Re: [Microsoft/vscode] Markdown Preview not correct (#10789)
This don't :)
See "oficial syntax proposal" at: https://daringfireball.net/projects/markdown/syntax#header
It makes sense to separate "markup" from "information"
