### ISSUE TITLE
terminal renderer description says webgl needs a reload

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#107858]
https://github.com/microsoft/vscode/issues/85970

![image](https://user-images.githubusercontent.com/8586769/94756109-72e56980-034b-11eb-90ff-f7788be8627d.png)

**Comment by rzhao271** [comment]
Note to self: change description, since webgl doesn't need a reload anymore.

**Comment by rzhao271** [comment]
Verifier: confirm that the description for `terminal.integrated.rendererType` when set to experimentalWebgl doesn't mention anything about it not being hot swappable.
