### ISSUE TITLE
Unbound breakpoint

### ISSUE THREAD

**Issue by amormicoder** [microsoft/vscode#107897]
- VSCode Version: 1.49.2
- OS Version: Windows 10

Steps to Reproduce:

1. Set a breakpoint at line in code.
2. Launch chrome to start a debuggind session.

As soon as the browser opens, the breakpoints show as "unbound breakpoint".

I've tried to uninstall and install vs code and the chrome extension, but still getting same behaviour.

Also i tried to install nightly extensions and set debug.javascript.usePreview: false, but couldn't fix it. 

Thanks in advance.

**Comment by plinionaves** [comment]
Same problem here

**Comment by connor4312** [comment]
@plinionaves please collect a trace log using the instructions above so I can help you out

**Comment by plinionaves** [comment]
@connor4312 I'm working on a private project, does this trace capture any sensitive information?

**Comment by plinionaves** [comment]
Hi @connor4312, I sent my log file in the email mentioned above, thanks in advance

**Comment by connor4312** [comment]
It doesn't look like your application is loading your "OrderStatusService.ts" anywhere. Where do you expect it to be coming from?

**Comment by plinionaves** [comment]
Really, I tried to debug directly through chrome too but I couldn't find it
It is inside a directory in my Vue project, running with the Webpack, I will try to restart the server

**Comment by connor4312** [comment]
Thanks for the info. Based on that, this is probably not a problem in the scope of VS Code; you may have more luck with StackOverflow and similar.

**Comment by yoyo930021** [comment]
I have a same problem in https://github.com/vuejs/vetur/pull/2301.
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode/files/5350767/vscode-debugadapter-1.json.gz)

PS. VSCode can get correct code position when `debugger` in code.

**Comment by connor4312** [comment]
Your sourcemaps or launch config are set incorrectly. You set a breakpoint in `/git/vetur/server/src/utils/prettier/index.ts`, but the sourcemap maps back to `/git/vetur/server/dist/server/src/utils/prettier/index.ts` (notice the `dist` in the path)

**Comment by yoyo930021** [comment]
> Your sourcemaps or launch config are set incorrectly. You set a breakpoint in `/git/vetur/server/src/utils/prettier/index.ts`, but the sourcemap maps back to `/git/vetur/server/dist/server/src/utils/prettier/index.ts`

Thanks, I think it's a sourcemap problem with esbuild.
I add a hack for it https://github.com/vuejs/vetur/pull/2301/commits/2dd9fa83678a1f40cf78d4f1a13756eef78bd1e2.

**Comment by connor4312** [comment]
Sounds good.

We've not had a followup from the original poster in 7 days, thus closing this issue.
