### ISSUE TITLE
Undo of replaceNotebookCellOutput doesn't do anything

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#107810]
Testing #107622

I have this workspace edit, where `i` increments each time the edit is run:
```
		const output: vscode.NotebookCellOutputItem[] = [
			new vscode.NotebookCellOutputItem('text/plain', 'this is output ' + i)
		];
		workspaceEdit.replaceNotebookCellOutput(editor.document.uri, selection.index, [
			new vscode.NotebookCellOutput(output)
		]);
```

I applied the edit several times and watched the output change ✔

Then I hit undo several times, expecting the output to change. It didn't change. 🐛

**Comment by rebornix** [comment]
We didn't wrap outputs inside Undo/Redo yet since we are going to change how execution works.

**Comment by rebornix** [comment]
It's now replaced by the new workspace edit api.
