### ISSUE TITLE
Feature Request: File Outline View for TypeScript

### ISSUE THREAD

**Issue by MartinHaeusler** [Microsoft/vscode#10788]
It would be very useful to have a structural outline of the currently opened TypeScript file in VScode.

For an example of what I mean, check out this screenshot of an outline from a Java file in Eclipse:

![outline](https://cloud.githubusercontent.com/assets/16356998/16942947/4c382adc-4d99-11e6-8703-a8a64a1ca62d.png)

It displays the names of all types on top-level, and folded within them are the names of all fields and methods, including their names as well as parameter and return types. Clicking on a member in the outline jumps to the declaration. The icons indicate if the method is public (green) or protected (yellow).

As somebody who used Eclipse extensively in the past, I find it very difficult to program without such a view.

**Comment by sandy081** [comment]
@MartinHaeusler There is a quick outline available when you type `ctrl+shift+o` which is a keyboard shortcut for the command `Go to Symbol...`

Guess this works for you.

**Comment by MartinHaeusler** [comment]
@sandy081 Thanks for the suggestion, that's already a good start. I would prefer a "permanent" view though, something that visually sticks around all the time, like a sidebar, and is always in sync with the current file in the editor.

In the `ctrl+shift+o` menu, there's also no folding (e.g. members of a class are shown as children of the class) and the types of the members (e.g. field types, method return types...) are unfortunately not displayed either...

As I said, this menu is a good start for me, but not quite what I would like to have.

**Comment by MartinHaeusler** [comment]
By the way, Visual Studio doesn't have that feature either. It needs third party plugins to achieve that, for example ReSharper for C#:

https://www.jetbrains.com/help/resharper/2016.2/Reference__Windows__File_Structure_Window.html

**Comment by MartinHaeusler** [comment]
One more detail: the eclipse outline allows to switch the display between alphabetic member sorting and "as occurs in file" sorting with a single UI button press - a very handy feature.

**Comment by sandy081** [comment]
@MartinHaeusler That's a good input. We already have a feature request for having a separate view for outline - #5605.

I would make this a dup of #5605. Please subscribe to that item and provide feedback there.

Thanks.

**Comment by MartinHaeusler** [comment]
Alright, thanks, I'll do that.
