### ISSUE TITLE
Debugger will not step into function calls for new files

### ISSUE THREAD

**Issue by zluther89** [microsoft/vscode#107859]
- VSCode Version: 1.49.2
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

Unsure of how to reproduce.

Does this issue occur when all extensions are disabled?: Yes

After setting a breakpoint on a function, the breakpoint will hit and stop, but then when I hit step into, it's like I hit continue. It executes the rest of the file, and exits the debugger. No output from the debugging console, and my launch.json is the standard one generated for node. (When I create one, I have repeated this step multiple times with and without a launch.json and the issue is the same)
```
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": ["<node_internals>/**"],
      "program": "${workspaceFolder}/new.js"
    }
  ]
}
```

If I write a "debugger;" into the function itself rather than using a breakpoint, it seems to kind of work. Though if the debugger encounter any console.log statements, it halts execution of the code and the debugger entirely.

After investigating further I have noticed this behavior only happens for new files. I can run old files just fine, but new files do not work correctly. Even if I create a new file in the an old folder alongside files which can be debugged correctly, the old files will debug fine, but the new one will exhibit this behavior.

[Screen Recording 2020-09-30 at 9.51.02 PM.zip](https://github.com/microsoft/vscode/files/5309069/Screen.Recording.2020-09-30.at.9.51.02.PM.zip)

**Comment by zluther89** [comment]
I am finding even weirder behavior as I continue to test. Here are two dummy functions that are the same exact function with different names. One can be debugged, but the other can't. 

[Screen Recording 2020-09-30 at 11.24.27 PM.zip](https://github.com/microsoft/vscode/files/5309312/Screen.Recording.2020-09-30.at.11.24.27.PM.zip)

**Comment by connor4312** [comment]
Fixed in the [next nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)

To verify, create a file like:

```
function double(x) {
  return x * 2;
}

double(2);
```

Set a breakpoint on `double(2)`; you should step into the function.

**Comment by zluther89** [comment]
@connor4312 

I'm getting the same behavior. I disabled Javascript Debugger, installed the nightly extension, and added
```"debug.javascript.usePreview": true ```
to my settings.json.

full settings.json is

```{
  "debug.javascript.usePreview": true,
  "window.titleBarStyle": "native",
  "workbench.colorCustomizations": {
    "terminal.background": "#1D2021",
    "terminal.foreground": "#A89984",
    "terminalCursor.background": "#A89984",
    "terminalCursor.foreground": "#A89984",
    "terminal.ansiBlack": "#1D2021",
    "terminal.ansiBlue": "#0D6678",
    "terminal.ansiBrightBlack": "#665C54",
    "terminal.ansiBrightBlue": "#0D6678",
    "terminal.ansiBrightCyan": "#8BA59B",
    "terminal.ansiBrightGreen": "#95C085",
    "terminal.ansiBrightMagenta": "#8F4673",
    "terminal.ansiBrightRed": "#FB543F",
    "terminal.ansiBrightWhite": "#FDF4C1",
    "terminal.ansiBrightYellow": "#FAC03B",
    "terminal.ansiCyan": "#8BA59B",
    "terminal.ansiGreen": "#95C085",
    "terminal.ansiMagenta": "#8F4673",
    // "terminal.ansiRed": "#FB543F",
    "terminal.ansiWhite": "#A89984",
    "terminal.ansiYellow": "#FAC03B"
  },
  "editor.semanticHighlighting.enabled": false,
  "editor.largeFileOptimizations": false,
  "files.maxMemoryForLargeFilesMB": 8000,
  "launch": {},
  "window.zoomLevel": 0,
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "workbench.colorTheme": "Community Material Theme Darker High Contrast",
  "editor.tokenColorCustomizations": {
    "[Material Theme Darker High Contrast]": {
      "comments": "#FAC03B"
    },
    "[Community Material Theme Darker High Contrast]": {
      "comments": "#FAC03B"
    }
  },
  "workbench.iconTheme": "vscode-icons",
  "workbench.editorAssociations": [],
  "editor.formatOnSave": false,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },  
  "[go]": {
    "editor.insertSpaces": false,
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
  }
}
```

**Comment by connor4312** [comment]
The nightly builds at 5PM PST each day, it's not released yet 🙂

**Comment by zluther89** [comment]
@connor4312 haha got it! thanks foe the patience 😄 
 👍

**Comment by zluther89** [comment]
@connor4312 Awesome, issues is fixed. Thanks for the update!
