### ISSUE TITLE
Debug toolbar placement

### ISSUE THREAD

**Issue by TheMisir** [microsoft/vscode#107825]
First of all I'm sorry for open ended issue / description.

I think placing debug toolbar on somewhere (eg: debug panel, status bar, or title bar) would be nice than placing over tab bar. Sometimes it's really frustration to move debug toolbar around to check which tab is open or checking code below toolbar (check #9315). I'm not good at UI design but I think current design have some flaws.

Here's some places that toolbar might be placed:

- Title / menu bar (titlebar currently has enough space for placing debug toolbar)
- Top of the debug panel on sidebar
- Status bar (which already has "debug" button)
- Placing inside tab bar instead of floating over it (like the buttons added by GitLens extension)
- Or, ...? Your thoughts

**Comment by isidorn** [comment]
Please use the following setting 	`"debug.toolBarLocation": "docked"`

**Comment by TheMisir** [comment]
Thanks, I haven't noticed 😅
