### ISSUE TITLE
Search not working for certain phrases

### ISSUE THREAD

**Issue by esimov** [microsoft/vscode#107947]
- VSCode Version: 1.49.2
- OS Version:Ubuntu 16.04

Steps to Reproduce:

1. There is a separate ticket mentioning the search issue https://github.com/microsoft/vscode/issues/85356, but in my case the search is working only on certain phrases like `for` as example, but if i'm trying to search in a Go codebase to `LittleEndian` in a compounded `binary.LittleEndian` phrase it does not find it, but it does find the `binary` word.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Can you share the repo so I can test?

**Comment by esimov** [comment]
Sure, here it is: https://github.com/esimov/pigo/.

Thank you.

**Comment by roblourens** [comment]
Works for me, what do you get?

![image](https://user-images.githubusercontent.com/323878/95002356-bcba9380-0587-11eb-8f80-1905b7575992.png)

**Comment by esimov** [comment]
Here is what I got:

![image](https://user-images.githubusercontent.com/883386/95015719-2786d000-0657-11eb-9f91-3207c2972689.png)

**Comment by roblourens** [comment]
That control searches a single file. What file are you looking in?

**Comment by esimov** [comment]
Yes, exactly i'm trying to search inside a single file, more specifically in the `pigo.go` file, because that's the file where it is included, but as you can see from the picture above the search result returns nothing.

**Comment by roblourens** [comment]
Well, you didn't say that before. Your screenshot shows that the "whole word" option is toggled on, so "Little" won't match "LittleEndian", you have to toggle off that middle button.

**Comment by esimov** [comment]
Sorry I missed that button. Thanks for the support.
