### ISSUE TITLE
"Go to definition" should not open a file in a new tab if it's already open in an existing tab

### ISSUE THREAD

**Issue by yay** [microsoft/vscode#107925]
Issue Type: <b>Feature</b>

IMO, "Go to definition" should not open a file in a new tab if it's already open in an existing tab.

For example, if I have a split view where a C++ header file is opened on the LHS and the corresponding source file on the RHS, when I go to definition, I'd like VS Code to jump to the definiton in the tab on the RHS, not create a new tab for the same file on the LHS.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (30.79GB free)|
|Process Argv|--crash-reporter-id 3e15ffe2-0055-499d-86f4-050413dd174e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|0.7.2
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.1
shader|sle|1.1.4
shader-toy|ste|0.10.12
cmake|twx|0.0.17
vscode-lldb|vad|1.5.3

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does the `workbench.editor.revealIfOpen` setting affect this?

**Comment by jrieken** [comment]
@yay please try the mentioned setting, it should be honoured

**Comment by yay** [comment]
Yep, that did the trick! Thanks guys!

**Comment by Love0ne** [comment]
I am free to use code as well.
