### ISSUE TITLE
Typescript wrapping disable issue

### ISSUE THREAD

**Issue by nitinbansal1989** [Microsoft/vscode#10792]
- VSCode Version: 1.4
- OS Version: Mac OS x 10.11

Typescript formating is wrapping the function statements event after the wrapping is disabled. Also ignoring wrapping for comments is not working. In version 1.3, this was working fine. Can you please check this. Also let me know if there is any user setting which has to be set. 

I have tried following settings:
"wrappingColumn" : 0 and -1

**Comment by waderyan** [comment]
@nitinbansal1989 thank you for opening this issue. Can you help me in recreating this? 

1. Paste some simple code that demonstrates the issue. I will open a new window and paste the code in. 
2. Describe the exact steps you took to see the issue (i.e. select entire code block, right click, select Format Code)
3. Paste a screenshot of what you see. 

I will do the steps on my machine to confirm it is reproducible.

**Comment by nitinbansal1989** [comment]
The issue has been resolved. It might be due to some extension. I uninstalled all formatting extension and then tried it.
Thanks for your help.
