### ISSUE TITLE
Remove extra whitespace from labels for unsaved tabs

### ISSUE THREAD

**Issue by bland328** [microsoft/vscode#107979]
# Feature suggestion
When VS Code generates a faux "filename" to appear in the tab of a new, unsaved file, I suggest that it would save screen space and eliminate some visual noise if all repeating whitespace characters were collapsed to single spaces.

# Example
A new tab is opened and a chunk of logged text with this first line is pasted in:
`error      13:47:38.285446-0500      cfprefsd      rejecting write of key(s) kFMFDStoredDataKey`

Currently, since the tab doesn't yet have a file name, VS Code labels it like this:
**error      13:47:38.285446-0500      cfprefsd      reje**

I'm suggesting that runs of whitespace _(tabs and spaces, at least)_ be collapsed to single spaces, making it instead like this:
**error 13:47:38.285446-0500 cfprefsd reje**

It's easier on the eye and takes less screen real estate without losing _(what I see as)_ actionable information. Thanks for considering!

**Comment by bpasero** [comment]
I think it makes sense to normalize multiple-whitespace to a single whitespace for the editor label. If someone wants to do this as a PR, go ahead. The label comes from here: 

https://github.com/microsoft/vscode/blob/50d9f05334aee7bbc416f675cceccd9a174de8c7/src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts#L91-L101

**Comment by bpasero** [comment]
**Verification:** open an untitled editor and type some words separated by more than one whitespace and verify only 1 whitespace appears in editor title.

**Comment by bland328** [comment]
And thank you!
