### ISSUE TITLE
Clone a BRANCH (other than master) from GitHub

### ISSUE THREAD

**Issue by kumueric** [microsoft/vscode#107974]
In VSC, if we open the Command Palette (Ctrl+Shift+P), we can easily clone the master branch of a remote repo.  What if we have a particular feature branch?  How can we specify it?

As a workaround, we can either use a terminal window (or the VSC integrated terminal) to cd over to the directory, and manually type:  git clone -b <named_branch> https://github.com/org/repo.git.  Then, we can Open Folder to it, and everything is fine.  But, it would be nice to be able to clone a BRANCH directly from within VSC.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/106664
