### ISSUE TITLE
Add ability to start typing in breadcrumb overview to go between entries

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#107955]
If I focus on breadcrumb with `cmd+shift+;`. I can then arrow key the element I want to jump too. I'd like to start typing the name I want to jump to and it will match (typical behavior on macOS inputs). So from here:

<img width="160" alt="image" src="https://user-images.githubusercontent.com/6391776/94901018-45f19d80-0496-11eb-9078-137dd92c98a8.png">

If I type in letter `d`, `default` will be in focus like this:

<img width="120" alt="image" src="https://user-images.githubusercontent.com/6391776/94901121-6c173d80-0496-11eb-84b5-2730189ab535.png">

**Comment by jrieken** [comment]
<img width="683" alt="Screenshot 2020-10-02 at 11 07 07" src="https://user-images.githubusercontent.com/1794099/94906815-6b36d980-049f-11eb-8df4-8e27ebc25be9.png">

You can do that - it's a normal list/tree so it should work as everywhere else in the editor,

**Comment by nikitavoloboev** [comment]
If I start typing characters inside this view:

<img width="169" alt="image" src="https://user-images.githubusercontent.com/6391776/94907089-eac4a880-049f-11eb-9ba7-84fc47178f7a.png">

Nothing happens. The keybindings get interpreted by vscode itself.

**Comment by jrieken** [comment]
🤷 works for me. Any settings on your side that disable this? Do you have something for `workbench.list.keyboardNavigation`

**Comment by nikitavoloboev** [comment]
Okay it's https://github.com/VSCodeVim/Vim that makes this not work. Without it, the search does work.

Do you know what the name of the context for when users are inside this breadcrumb view? I can try write a `when` clause thing perhaps to make it work even with the Vim extension.

**Comment by nikitavoloboev** [comment]
Asked it on VSCodeVim Slack channel, hopefully there is a solution to this.

<img width="897" alt="image" src="https://user-images.githubusercontent.com/6391776/94913865-4d22a680-04aa-11eb-98c2-3215d2ad8f55.png">

**Comment by nikitavoloboev** [comment]
Also if I am inside one of the breadcrumbs, is it possible to go back to focus on the top breadcrumbs?

So from here:

<img width="175" alt="image" src="https://user-images.githubusercontent.com/6391776/94915303-efdc2480-04ac-11eb-87f0-ecb0f7ce157d.png">

Go back to focus in here:

<img width="176" alt="image" src="https://user-images.githubusercontent.com/6391776/94915327-fcf91380-04ac-11eb-9045-9fdb3d06626a.png">

Escape will completely dismiss breadcrumb. And not sure if there is any hotkey available to go back down a level.

**Comment by jrieken** [comment]
closing this as answered, please file a separate feature request for https://github.com/microsoft/vscode/issues/107955#issuecomment-702661124
