### ISSUE TITLE
New windows inherit/merge environment from existing windows

### ISSUE THREAD

**Issue by AngryCochinoPup** [microsoft/vscode#107998]
Issue Type: <b>Bug</b>

1. Open two tabs in a terminal emulator
2. In tab 1: export TEST_VAR=1
3. In tab 2: export TEST_VAR=2
4. In tab 1: code --new-window .
5. In tab 2: code --new-window .
6. In Code window 2 terminal: echo $TEST_VAR
TEST_VAR has the value 1, not 2. This is *wrong*.
Using --sync off helps some, as tab 2 will get its own value for TEST_VAR, but it will still inherit any values in tab 1's environment that are not overwritten.
This is a disaster for my workflow, as I have different tabs with different environments set up to work on different programs.
Please tell me there is a way to turn this off completely.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:26:09.944Z)
OS version: Linux x64 3.10.0-1062.4.1.el7.x86_64

**Comment by bpasero** [comment]
Fixed as outlined in https://github.com/microsoft/vscode/issues/108804#issuecomment-731230574 for November.

**Comment by bpasero** [comment]
\closedWith 6f3fcd2ce0002ffd876b7b43bff42a912edddaae
