### ISSUE TITLE
vscode-json-languageserver crashes on start: Cannot find module '../out/jsonServerMain'

### ISSUE THREAD

**Issue by apexskier** [microsoft/vscode#107949]
- VSCode Version: n/a
- OS Version: macOS 10.15.6 (19G2021)

Steps to Reproduce:

1. `npx vscode-json-languageserver` (or run it locally, this is just the quickest repro)
2. See the following:
   ```
   Cannot find module '../out/jsonServerMain'
   Require stack:
   - /Users/cameronlittle/.npm/_npx/63688/lib/node_modules/vscode-json-languageserver/bin/vscode-json-languageserver
   ```

This doesn't happen on the previous release (`npx vscode-json-languageserver@1.2.3`)

**Comment by aeschli** [comment]
I pushed vscode-json-languageserver@1.3.1 with the fix

**Comment by apexskier** [comment]
Thanks! It's working now and this can be closed.
