### ISSUE TITLE
Settings UI dropdown list is not dismissed when setting editor is closed

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#107909]
Issue Type: <b>Bug</b>

* Open Settings Editor
* Open a drop down 
* CMD+W to close the editor
* The drop down will not go away

![settings-dropdown](https://user-images.githubusercontent.com/876920/94841940-8f2aea00-03cf-11eb-8e3f-adfb5da9bac9.gif)

VS Code version: Code - Insiders 1.50.0-insider (228973889bc0e352f7cd11cc14755893f8d81864, 2020-10-01T05:28:37.293Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.55GB free)|
|Process Argv|-psn_0_23889607 --enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|10%|
</details>

**Comment by rebornix** [comment]
Assigning to Sept first as it's a regression.

**Comment by roblourens** [comment]
Bad but not a regression

**Comment by roblourens** [comment]
Need to remove the dev flag in selectBoxCustom.ts and replace it with a hidden setting

**Comment by roblourens** [comment]
I don't really want to introduce config into that SelectBox world
