### ISSUE TITLE
external terminal closes instantly

### ISSUE THREAD

**Issue by saithebuilder** [microsoft/vscode#107960]
- VSCode Version:1.49.2
- OS Version:Ubuntu 20.04.1 LTS

External Terminal closes instantly in ubuntu but works properly in windows.

Steps to Reproduce:

1.create a new python file, create a launch.json file.
2.change "console": "integratedTerminal" to "console": "externalTerminal"
3.the terminal runs and closes instantly, with no way to check the output except by adding a  input = ()
in the python file.

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by isidorn** [comment]
Make sure to have 	`"debug.console.closeOnEnd": false` in your settings.
If you still see the issue then file against Python they might be doing something special from their extension

**Comment by saithebuilder** [comment]
the issue is still there. just tried it with a much older version of the python extension. looks like its an issue with the extension.
