### ISSUE TITLE
After executing jest  Unit Tests, debug console shows no output

### ISSUE THREAD

**Issue by shrikjoshi** [microsoft/vscode#107930]
Issue Type: <b>Bug</b>

After executing jestUnit Tests for react, debug console shows no output

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (19.09GB free)|
|Process Argv|--crash-reporter-id 4e585ff8-ba84-4ece-9ab1-0f504bc210fb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.8.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.8
githistory|don|0.6.10
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.1
graphql-for-vscode|kum|1.15.3
tdpcode|Mic|1.3.16
remote-containers|ms-|0.140.1
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.11
markdown-preview-enhanced|shd|0.5.13
teams-dyson|tea|0.0.2020081901
alphabetical-sorter|ue|2.0.1

</details>

**Comment by connor4312** [comment]
How are you executing the unit tests. If you're using a launch.json, can you share it?
