### ISSUE TITLE
Theme variables for notebook renderers

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#107985]
## Problem

In sharing renderers with Azure Notebooks, one issue that comes up is around color tokens. VS Code includes [over 400 color](https://github.com/connor4312/vscode-webview-tools/blob/master/src/pkg/colors.ts) tokens, which are made available in the renderer as, for example `var(--vscode-chart-red)`.

Azure Notebooks does the same, with a more limited set of color tokens

<details>

```js
["--theme-app-bg", NeutralColors.white],
["--theme-app-fg", NeutralColors.gray160],
["--theme-app-border", NeutralColors.white],
["--theme-primary-bg", NeutralColors.gray20],
["--theme-primary-bg-hover", NeutralColors.gray20],
["--theme-primary-bg-focus", NeutralColors.gray20],
["--theme-primary-fg", NeutralColors.gray160],
["--theme-primary-fg-hover", NeutralColors.gray160],
["--theme-primary-fg-focus", NeutralColors.gray160],
["--theme-secondary-bg", "var(--theme-primary-bg)"],
["--theme-secondary-bg-hover", "var(--theme-primary-bg-hover)"],
["--theme-secondary-bg-focus", "var(--theme-primary-bg-focus)"],
["--theme-secondary-fg", NeutralColors.gray180],
["--theme-secondary-fg-hover", NeutralColors.gray170],
["--theme-secondary-fg-focus", NeutralColors.gray160],
["--theme-primary-shadow-hover", "0px  0px 6px rgba(96, 94, 92, 0.25)"],
["--theme-primary-shadow-focus", "0px 0px 8px rgba(96, 94, 92, 0.5)"],
["--theme-title-bar-bg", "#2DFFFE"],
["--theme-menu-bg", NeutralColors.gray150],
["--theme-menu-bg-hover", NeutralColors.gray160],
["--theme-menu-bg-focus", NeutralColors.gray170],
["--theme-menu-shadow", "var(--theme-primary-shadow-hover)"],
["--theme-menu-fg", "var(--theme-app-fg)"],
["--theme-menu-fg-hover", "var(--theme-app-fg)"],
["--theme-menu-fg-focus", "var(--theme-app-fg)"],
["--theme-menu-checkmark", "#605e5"],
["--theme-menu-checkmark-hover", "var(--theme-menu-checkmark)"],
["--theme-menu-checkmark-focus", "var(--theme-menu-checkmark)"],
["--theme-menu-border", "none"],
["--theme-cell-bg", "var(--theme-app-bg)"],
["--theme-cell-shadow-hover", "var(--theme-primary-shadow-hover)"],
["--theme-cell-shadow-focus", "var(--theme-primary-shadow-focus)"],
["--theme-cell-hidden-input-fg", NeutralColors.gray130],
["--theme-md-fg", NeutralColors.black],
["--theme-cell-vertical-toolbar-button-bg", NeutralColors.gray30],
["--theme-cell-vertical-toolbar-button-bg-hover", NeutralColors.gray40],
["--theme-cell-vertical-toolbar-button-fg", NeutralColors.gray130],
["--theme-cell-vertical-toolbar-button-fg-hover", NeutralColors.gray130],
["--theme-cell-statebar-cell-focused-bg", SharedColors.cyanBlue10],
["--theme-cell-statebar-editor-focused-bg", "#659267"],
["--theme-cell-statebar-no-focus-hover-bg", NeutralColors.gray60],
["--theme-cell-execute-button-command-mode-bg", SharedColors.cyanBlue10],
["--theme-cell-execute-button-command-mode-bg-hover", SharedColors.cyanBlue20],
["--theme-cell-execute-button-command-mode-fg", NeutralColors.white],
["--theme-cell-execute-button-command-mode-fg-hover", NeutralColors.white],
["--theme-cell-execute-button-edit-mode-bg", SharedColors.green10],
["--theme-cell-execute-button-edit-mode-bg-hover", SharedColors.green20],
["--theme-cell-execute-button-edit-mode-fg", NeutralColors.white],
["--theme-cell-execute-button-edit-mode-fg-hover", NeutralColors.white],
["--theme-cell-execute-button-hover-bg", NeutralColors.gray40],
["--theme-cell-execute-button-hover-bg-hover", NeutralColors.gray50],
["--theme-cell-execute-button-hover-fg", SharedColors.cyanBlue10],
["--theme-cell-execute-button-hover-fg-hover", SharedColors.cyanBlue10],
["--theme-cell-cancel-button-rest-fg", SharedColors.cyanBlue10],
["--theme-cell-cancel-button-command-mode-bg", NeutralColors.gray50],
["--theme-cell-cancel-button-command-mode-bg-hover", NeutralColors.gray60],
["--theme-cell-cancel-button-command-mode-fg", SharedColors.cyanBlue10],
["--theme-cell-cancel-button-command-mode-fg-hover", SharedColors.cyanBlue20],
["--theme-cell-cancel-button-edit-mode-bg", NeutralColors.gray50],
["--theme-cell-cancel-button-edit-mode-bg-hover", NeutralColors.gray60],
["--theme-cell-cancel-button-edit-mode-fg", SharedColors.cyanBlue10],
["--theme-cell-cancel-button-edit-mode-fg-hover", SharedColors.cyanBlue20],
["--theme-cell-cancel-button-hover-bg", NeutralColors.gray40],
["--theme-cell-cancel-button-hover-bg-hover", NeutralColors.gray50],
["--theme-cell-cancel-button-hover-fg", SharedColors.cyanBlue10],
["--theme-cell-cancel-button-hover-fg-hover", SharedColors.cyanBlue10],
["--theme-cell-prompt-bg", "var(--theme-primary-bg)"],
["--theme-cell-prompt-bg-hover", NeutralColors.gray30],
["--theme-cell-prompt-bg-focus", NeutralColors.gray40],
["--theme-cell-prompt-fg", "var(--theme-app-fg)"],
["--theme-cell-prompt-fg-hover", "var(--theme-app-fg)"],
["--theme-cell-prompt-fg-focus", "var(--theme-app-fg)"],
["--theme-cell-prompt-border", "none"],
["--theme-cell-toolbar-bg", "var(--theme-primary-bg)"],
["--theme-cell-toolbar-bg-hover", NeutralColors.gray30],
["--theme-cell-toolbar-bg-focus", NeutralColors.gray40],
["--theme-cell-toolbar-fg", "var(--theme-app-fg)"],
["--theme-cell-toolbar-fg-hover", "var(--theme-app-fg)"],
["--theme-cell-toolbar-fg-focus", "var(--theme-app-fg)"],
["--theme-cell-menu-bg", NeutralColors.gray10],
["--theme-cell-menu-bg-hover", NeutralColors.gray30],
["--theme-cell-menu-bg-focus", NeutralColors.gray40],
["--theme-cell-menu-fg", "var(--theme-app-fg)"],
["--theme-cell-menu-fg-hover", "var(--theme-app-fg)"],
["--theme-cell-menu-fg-focus", "var(--theme-app-fg)"],
["--theme-cell-menu-linktext", "0px solid"],
["--theme-cell-menu-list-item-hover", NeutralColors.gray20],
["--theme-cell-menu-list-item-focus", "var(--theme-cell-menu-list-item-hover)"],
["--theme-cell-menu-list-icon-hover", SharedColors.cyanBlue10],
["--theme-cell-menu-list-icon-active", "var(--theme-cell-menu-list-icon-hover)"],
["--theme-cell-menu-list-icon-focus", "var(--theme-cell-menu-list-icon-hover)"],
["--theme-cell-menu-list-text-active", NeutralColors.gray160],
["--theme-cell-menu-list-text-focus", NeutralColors.gray160],
["--theme-cell-menu-overflow-expanded", NeutralColors.gray30],
["--theme-cell-menu-overflow-expanded-hover", NeutralColors.gray40],
["--theme-cell-menu-overflow-icon-expanded", NeutralColors.gray160],
["--theme-cell-input-bg", "white"],
["--theme-cell-input-fg", "var(--theme-app-fg)"],
["--theme-cell-output-bg", "var(--theme-app-bg)"],
["--theme-cell-output-bg-hover", "var(--theme-app-bg)"],
["--theme-cell-output-bg-focus", "var(--theme-app-bg)"],
["--theme-cell-output-fg", "var(--theme-app-fg)"],
["--theme-cell-creator-bg", "var(--theme-app-bg)"],
["--theme-cell-creator-bg-hover", NeutralColors.gray20],
["--theme-cell-creator-bg-focus", NeutralColors.gray30],
["--theme-cell-creator-fg", "var(--theme-app-fg)"],
["--theme-cell-creator-fg-hover", "var(--theme-app-fg)"],
["--theme-cell-creator-fg-focus", "var(--theme-app-fg)"],
["--theme-cell-vertical-divider", "var(--theme-cell-prompt-bg-focus)"],

["--theme-error-fg", "hsl(0, 100%, 95%)"],
["--theme-error-bg", "hsl(0, 100%, 30%)"],
["--theme-pager-bg", "#111"],

["--theme-focus-border-width", "1px"],
["--theme-focus-border-color", NeutralColors.gray160],

["--theme-cell-border-width", "0"],

["--theme-cell-input-border-width", "1px"],
["--theme-cell-input-border-color", NeutralColors.gray40],

["--theme-cell-input-active-border-width", "1px"],
["--theme-cell-input-active-border-color", "var(--theme-cell-input-border-color)"],
["--theme-cell-section-separtor-width", "1px"], // Separtor width between input and outputs

["--theme-commandbar-bg", NeutralColors.white],
["--theme-commandbar-border", NeutralColors.gray60],
["--theme-commandbar-divider", NeutralColors.gray50],

["--theme-statusbar-text", NeutralColors.white],
["--theme-statusbar-color-idle", NeutralColors.gray150],
["--theme-statusbar-color-connected", CommunicationColors.primary],
["--theme-statusbar-color-error", SharedColors.red20],

["--theme-errorbar-bg", NotebooksLightThemeColors.pink],
["--theme-errorbar-text", NeutralColors.black],
["--theme-errorbar-icon", NotebooksLightThemeColors.red],
["--theme-errorbar-border", "none"],
["--theme-dropdown-title-color", NeutralColors.gray160],

["--theme-messagebar-text", NeutralColors.gray160],
["--theme-messagebar-icon", NeutralColors.gray130],
["--theme-messagebar-bg", NeutralColors.gray20],
["--theme-messagebar-link", SharedColors.cyanBlue10],

["--theme-tooltip-border", "none"],
["--link-color", SharedColors.cyanBlue10],
["--link-color-hover", CommunicationColors.shade30],

["--block-quote-color", "#ddd"],
["--markdown-block-quote-bg", "#EFF0F1"],
["--markdown-block-quote-border", "none"],
["--theme-markdown-code-bg", "#EFF0F1"],
["--theme-markdown-code-border", "none"]
```

</details>

It's not practical for aznb to adopt every VS Code theme color in their notebooks, nor are all the aznb colors a strict subset of VS Code theme colors.

## Solution

We should share a subset of theme colors and expose them on the renderer webview. I propose we adopt the more generic names that aznb uses, `--theme-*`, and map VS Code theme colors to those.

First pass at what colors we'd want to share: (feel free to edit this issue/table)

| VS Code | Aznb | Final Name |
|-|-|-|
| **Typography** |-|-|
| `--vscode-font-family` | N/A (should add) | `--theme-font-family` |
| `--vscode-font-weight` | N/A (should add) | `--theme-font-weight` |
| `--vscode-font-size` | N/A (should add) | `--theme-font-size` |
| `--vscode-editor-font-family` | N/A (should add) | `--theme-code-font-family` |
| `--vscode-editor-font-weight` | N/A (should add) | `--theme-code-font-weight` |
| `--vscode-editor-font-size` | N/A (should add) | `--theme-code-font-size` |
| **Editor** |-|-|
| `--vscode-editor-background` | `--theme-app-bg` | `--theme-background` |
| `--vscode-editor-foreground` | `--theme-app-fg` | `--theme-foreground` |
| `--vscode-foreground` | `--theme-app-fg` | `--theme-ui-foreground` |
| `--vscode-editor-link-foreground` | `--link-color` | `--theme-link` |
| `--vscode-editor-link-active-foreground` | `--link-color-hover` | `--theme-link-active` |
| `--vscode-textBlockQuote-background` | `--markdown-block-quote-bg` | `--theme-quote-background` |
| `--vscode-textBlockQuote-border` | `--markdown-block-quote-border` | `--theme-quote-border` |
| `--vscode-textPreformat-foreground` | `--theme-app-fg` | `--theme-code-foreground` |
| `--vscode-scrollbarSlider-background` | N/A (use nothing) | theme-scrollbar-background', |
| `--vscode-scrollbarSlider-hoverBackground` | N/A (use nothing) | theme-scrollbar-hover-background |
| `--vscode-scrollbarSlider-activeBackground` | N/A (use nothing) | theme-scrollbar-active-background |
| **Buttons** |-|-|
| `--vscode-button-background` | `--theme-primary-bg` | `--theme-button-background` |
| `--vscode-button-hover-background` | `--theme-primary-bg-hover` | `--theme-button-hover-background` |
| `--vscode-button-foreground` | `--theme-primary-fg` | `--theme-button-foreground` |
| `--vscode-button-secondary-background` | `--theme-secondary-bg` | `--theme-button-secondary-background` |
| `--vscode-button-secondary-hover-background` | `--theme-secondary-bg-hover` | `--theme-button-secondary-hover-background` |
| `--vscode-button-secondary-foreground` | `--theme-secondary-fg` | `--theme-button-secondary-foreground` |
| N/A (use normal fg) | `--theme-primary-hover-fg` | `--theme-button-hover-foreground` |
| N/A (use normal fg) | `--theme-primary-focus-fg` | `--theme-button-focus-foreground` |
| N/A (use normal fg) | `--theme-secondary-hover-fg` | `--theme-button-secondary-hover-foreground` |
| N/A (use normal fg) | `--theme-secondary-focus-fg` | `--theme-button-secondary-focus-foreground` |
| N/A (use nothing) | `--theme-primary-shadow-hover` | `--theme-button-primary-hover-shadow` |
| N/A (use nothing) | `--theme-secondary-shadow-hover` | `--theme-button-secondary-hover-shadow` |
| **Inputs** |-|-|
| `--vscode-input-background` | `--theme-cell-input-bg` | `--theme-input-background` |
| `--vscode-input-foreground` | `--theme-cell-input-fg` | `--theme-input-foreground` |
| `--vscode-input-placeholder-foreground` | N/A (should add) | `--theme-input-placeholder-foreground` |
| `--vscode-input-border` | `--theme-cell-input-border-color` | `--theme-input-border-color` |
| 1px | `--theme-cell-input-border-width` | `--theme-input-border-width` |
| **Menus** |-|-|
| `--vscode-menu-background` | `--theme-menu-bg` | `--theme-menu-background` |
| `--vscode-menu-foreground` | `--theme-menu-fg` | `--theme-menu-foreground` |
| `--vscode-menu-selection-background` | `--theme-menu-bg-hover` | `--theme-menu-hover-background` |
| N/A (use selection bg) | `--theme-menu-bg-focus` | `--theme-menu-focus-background` |
| `--vscode-menu-selection-foreground` | `--theme-menu-fg-hover` | `--theme-menu-hover-foreground` |
| N/A (use selection fg) | `--theme-menu-fg-focus` | `--theme-menu-focus-foreground` |
| **Errors** |-|-|
| `--vscode-notification-error-background` | `--theme-error-bg` | `--theme-error-background` |
| `--vscode-notification-error-foreground` | `--theme-error-fg` | `--theme-error-foreground` |
| `--vscode-notification-warning-background` | N/A (should add) | `--theme-warning-background` |
| `--vscode-notification-warning-foreground` | N/A (should add) | `--theme-warning-foreground` |
| `--vscode-notification-info-background` | N/A (should add) | `--theme-info-background` |
| `--vscode-notification-info-foreground` | N/A (should add) | `--theme-info-foreground` |

cc @misolori @vijayupadya @kjcho-msft

**Comment by jrieken** [comment]
This seems to be missing a category of styles. There are buckets for errors, menus, input, and editors but nothing for "normal" background/foreground, like panel and then maybe list/tree

**Comment by connor4312** [comment]
From Slack:

>The other more radical solution is to tell aznb to consume our themes. I don't think this is too crazy, the only bit is that we would need to have the defaults/inheritance of VS Code theme colors be published in such a way that they could reliably apply vscode themes.

I plan to investigate the feasibility of this this week.

**Comment by connor4312** [comment]
We have decided to move forward on this. Other consumers of renderers should use the [theme-color-consumer](https://github.com/microsoft/vscode-theme-color-consumer) package, along with a VS Code theme (either built-in or from the marketplace) to create a compatible environment for running renderers.

For example, here's how you might load a VS Code theme in order to make the current document fully capable of styling code made to run in a VS Code webview:

```ts
import { ColorTheme, getWebviewProperties } from '@vscode/theme-color-consumer';

const myThemeJson = 'https://raw.githubusercontent.com/connor4312/codesong/master/package.json';

// Use .load() to load the json, passing in a fetcher function. Returns all
// themes defined in the package.json.
const themes = ColorTheme.load(myThemeJson, async url => {
  const res = fetch(url);
  return res.text();
});

// Get the webview colors. Information about the font to use is not included
// in themes and should be passed here as well:
const webviewProps = getWebviewProperties(themes[0], myFontData);

// This returns the 'style' property, as well as a class and data which should
// be applied to the body:
document.body.style = webviewProps.style;
document.body.classList.add(webviewProps.style);
Object.assign(document.body.dataset, webviewProps.dataset);
```
