### ISSUE TITLE
Tweak in Monokai Theme has made the code too greenish and eye paining

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode#107962]
- VSCode Version: 1.49.2
- OS Version: Windows 10

Steps to Reproduce:

1. I just wrote a code in python with Editor theme set to Monokai and this was the result !

![vscode_python](https://user-images.githubusercontent.com/54276661/94916804-f8445780-04cc-11eb-81d5-899fb0be9924.PNG)

**Its too much green! Previous settings were good!**

Does this issue occur when all extensions are disabled?: Yes

**Comment by lakshits11** [comment]
Can I get a update on the work please?

**Comment by misolori** [comment]
@lakshits11 are you using the Pylance extension? Because I without it I get this:

![image](https://user-images.githubusercontent.com/35271042/95115765-daf4d080-06fa-11eb-8750-455a4bd7e55f.png)

**Comment by lakshits11** [comment]
Oh, Yes!! So it was happening because of Pylance Extension! Thanks a lot!
