### ISSUE TITLE
console.log (JS) does not output to debug console, debug does not work either

### ISSUE THREAD

**Issue by danieltkach** [microsoft/vscode#107927]
- VSCode Version: 1.49.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Do a console.log("any string");
2. run the program

Does this issue occur when all extensions are disabled?: Yes

console.log does not output, and debugger does not work, breakpoints are completely ignored.
It all works find in the insiders version.

**Comment by isidorn** [comment]
If it is fine in insiders version than there is nothing for us to do since it is fixed.
However first assigning to @connor4312 as he might have some ideas.

@danieltkach also we would need exact reproducavle steps

**Comment by connor4312** [comment]
But yes if Insiders works fine (thank you for trying) then it's probably alright. The next release will ship next week.
