### ISSUE TITLE
[json] schema fileMatch fails after a second workspace folder is added

### ISSUE THREAD

**Issue by andreasulmer** [microsoft/vscode#107976]
Issue Type: <b>Bug</b>

In settings.json.schemas, fileMatch works as expected with a single folder in the workspace, and I get the expected schema validation error in problems view.
Once a second folder is added, fileMatch does not match any files anymore, no schema validation problems are shown.

### Short repro
1. set up a project with a single workspace folder, and a schema-invalid json file. In the workspace settings, configure a schema with a fileMatch pattern that includes the folder path. Make sure the problem view shows the invalid schema error.
2. Add a second workspace folder. Restart VSCode -> The schema validation error does not show anymore.

### More detailed example

Folder structure 

```
folderA/
  .vscode/
    filematch-issue.code-workspace
  samplesA/
   myfileA.json

folderB/ (empty)
```

schema is configured in workspace settings in `.vscode/filematch-issue.code-workspace`

### Situation 1
`filematch-issue.code-workspace` with only one folder (folderA)
```
{ "folders": [{
  "path": ".."
  }],
 "settings": {
  "json.schemas": [{
    "fileMatch": [
      "folderA/samplesA/*.json",
    ],
    "url": "http://my.domain.com/schema"
  }]
}}
```

✔ everything works as expected. json file in folderA/samplesA/ throws an expected validation error.

### Situation 2: After adding second folder `folderB`, but unchanged fileMatch

```
{ "folders": [{
    "path": ".."
  }, {
    "path": "..\\..\\folderB"
  }],
 "settings": {
  "json.schemas": [{
    "fileMatch": [
      "folderA/samplesA/*.json",
    ],
    "url": "http://my.domain.com/schema"
  }]
}}
```

❌ No more validation problems are shown, seems the fileMatch does not find any files anymore.

### Situation 3:
keep the second folder, and modify fileMatch from `folderA/samplesA/*.json` to `samplesA*.json`

-> the validation error shows again, i.e. fileMatch finds the file again.
This is especially weird.

It looks like adding a 2nd folder changes something on the internal file paths, in a way that the fileMatch does not find files anymore. 
From situation 3, where fileMatch works after removing the "root" part of a workspace folder, an assumption is that adding a second folder changes does something to that root part of the internal file paths, which could explain that fileMatch does not work as expected anymore.

----

* make sure to restart VSCode after changes to the workspace settings (these do not reliably update without a restart)
* I tried various different setups with different folder locations, different path patterns (absolute / relative), different fileMatch patterns, but the above issue is reliably reproducable
* I tried to collect more debug info by setting, "json.trace.server": "verbose" in the workspace settings, but I could not find any helpful output in any of the logs. Where do I see this output?

-----

VS Code version: Code - Insiders 1.50.0-insider (5052a7bc2ec35879b4ef5c835de78c9620bc1d9e, 2020-10-02T05:30:35.675Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (15.54GB free)|
|Process Argv|--crash-reporter-id 03e3eff6-56f6-46fe-a109-db8cc9b8a2fd|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by andreasulmer** [comment]
> check if it is already covered by an existing one, like:

Checked. Mentioned issues cover similar topics but do not describe the same problem.

**Comment by marcnee** [comment]
Hi @aeschli 
Unfortunately, I am not familiar with your planning process but I wanted to ask if this bug will be solved in the near future?

**Comment by aeschli** [comment]
Duplicate  of #147865
