### ISSUE TITLE
Canvas renderer of the integrated terminal is blurrier than other renderers

### ISSUE THREAD

**Issue by XsongyangX** [microsoft/vscode#107983]
The `canvas` renderer of the integrated terminal is not as clean sharp as the other renderers like `dom`. I've only found this problem on the integrated terminal.

- VSCode Version: 1.49.2 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Choose the renderer of the integrated terminal to be `canvas`
2. Open the integrated terminal, preferably Git Bash

Does this issue occur when all extensions are disabled?: Yes/No
![image](https://user-images.githubusercontent.com/10444460/94950478-b4dbf000-04b0-11eb-95b8-7f66219ce029.png)
![image](https://user-images.githubusercontent.com/10444460/94950519-c0c7b200-04b0-11eb-86ab-83d1698e8877.png)

**Comment by usernamehw** [comment]
If you use `window.zoomLevel` then this issue is a duplicate of #85154. Upstream issue https://github.com/xtermjs/xterm.js/issues/2662

**Comment by kbolino** [comment]
This happens without setting `window.zoomLevel`, in fact *setting* `window.zoomLevel` to -1 actually "fixes" it but then the text is too small.
