### ISSUE TITLE
Crash reporting opt-out is not honoured

### ISSUE THREAD

**Issue by justinsteven** [microsoft/vscode#107945]
- VSCode Version: 1.49.2
- OS Version: Debian Linux

When `enable-crash-reporter` is set to `false` in Runtime Arguments as per <https://code.visualstudio.com/docs/getstarted/telemetry#_disable-crash-reporting>, and/or when `--disable-crash-reporter` is set on the command-line, crash reports are still sent to Microsoft.

Steps to Reproduce:

1. Replace the `wget` binary with a canary that tells you when it's being invoked

```
% which wget
/usr/bin/wget

% sudo mv /usr/bin/wget /usr/bin/wget.old

% sudo vim /usr/bin/wget
[... SNIP ...]


% sudo chmod a+x /usr/bin/wget

% cat /usr/bin/wget
#!/bin/sh
echo "[!] Wget invoked as: $0 $@" >&2
exit 1

% wget foobar
[!] Wget invoked as: /usr/bin/wget foobar
```

2. Launch VSCode. Press `Ctrl+Shift+P`, do "Preferences: Configure Runtime Arguments", change `enable-crash-reporter` to `false` and exit VSCode. See https://code.visualstudio.com/docs/getstarted/telemetry#_disable-crash-reporting for more details.

3. Run `code --verbose --disable-extensions`

4. Press Ctrl-Shift-P and do "Toggle Developer Tools"

5. Go to the console and do `process.crash()`

6. Note the following in the terminal:

```
[!] Wget invoked as: /usr/bin/wget --header=Content-Type: application/json --header=App-Secret:  --header=Install-ID:  --post-file=/tmp/chromium-upload-0d3f9335c4e61c26 https://in.appcenter.ms/logs?api-version=1.0.0 --timeout=60 --tries=1 --quiet -O /dev/fd/3
Server response:
[1064:1002/140011.603931:WARNING:crash_handler_host_linux.cc(342)] Could not translate tid, attempt = 2 retry ...
[1064:1002/140011.704801:WARNING:crash_handler_host_linux.cc(366)] Could not translate tid - assuming crashing thread is thread group leader; syscall_supported=0
[1064:1002/140011.704967:ERROR:crash_handler_host_linux.cc(445)] Failed to write crash dump for pid 1115
Cannot upload crash dump: failed to open
[!] Wget invoked as: /usr/bin/wget --header=Content-Type: application/json --header=App-Secret:  --header=Install-ID:  --post-file=/tmp/chromium-upload-c6a95eb39fa5476d https://in.appcenter.ms/logs?api-version=1.0.0 --timeout=60 --tries=1 --quiet -O /dev/fd/3
Server response:
```

VSCode is attempting to use wget to upload the crash dumps to <https://in.appcenter.ms>

The same thing happens when `enable-crash-reporter` is set to `true` with `--disable-crash-reporter` set on the command-line.

7. Restore your modified `wget`

PR incoming.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I have not fully understood the issue yet but will check today if this is something we should fix for September.

**Comment by bpasero** [comment]
Talked with Deepak and we will tackle this in October, thanks a lot for finding this 👍

**Comment by m8ram** [comment]
FYI I can reproduce this on RHEL8 with `"enable-crash-reporter": false,` in `~/.vscode/argv.json`.

**Comment by deepak1556** [comment]
Should be fixed in latest insiders https://code.visualstudio.com/insiders/ , please verify. Thanks!
