### ISSUE TITLE
"Save as shell script" suggests *.bashrc instead of *.sh

### ISSUE THREAD

**Issue by LionOfJewdah** [microsoft/vscode#107943]
Issue Type: <b>Bug</b>

When I go to save a new file as a shell script using File > Save As, not having marked the syntax as shell script yet in the editor; it suggests I name it (filename).bashrc, instead of (filename).sh

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id 52447d5c-eb10-4f79-af5d-122dbf24b8fc|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
Sounds familiar.

**Comment by aeschli** [comment]
I can't reproduce with 1.49.2 and no extensions installed.
Do you have any shell related extensions installed?
