### ISSUE TITLE
filename_test.go appears before filename.go in the explorer

### ISSUE THREAD

**Issue by kylrth** [microsoft/vscode#107936]
Issue Type: <b>Bug</b>

For items in [lexicographic order](https://en.wikipedia.org/wiki/Lexicographic_order), an item that prefixes another item should be ranked before that longer item.

In VS Code, `alpha_test.go` gets displayed before `alpha.go`:

![Screenshot from 2020-10-01 17-25-46](https://user-images.githubusercontent.com/5044802/94872965-3d07ba00-040b-11eb-9728-70dee6bae81d.png)

Since we ignore the `.go` extension when sorting these file names, I think this ordering should be reversed.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:26:09.944Z)
OS version: Linux x64 5.4.3-050403-generic snap
Remote OS version: Linux x64 5.4.0-47-generic

**Comment by gjsjohnmurray** [comment]
Related to #27286 from @bpasero and PR #97272 from @leilapearson

**Comment by isidorn** [comment]
Yeah let's close as dup and we can continue the discussion in the PR

**Comment by leilapearson** [comment]
Also closely related to issue #99955 and PR #104528. These are both closed but they do explain why the code now behaves this way. The code no longer strips off the .go extension before comparing the names.
