### ISSUE TITLE
Extensions fail to load even after waiting for half an hour

### ISSUE THREAD

**Issue by odebroqueville** [microsoft/vscode#107907]
[Screenshot](https://i.imgur.com/d10iD9E.png)

- VSCode Version: 1.49.2
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. Open VS Code
2. Visit the Extensions tab

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rsokl** [comment]
This is the same problem as #107896

**Comment by sandy081** [comment]
- Did you see any error messages?
- Can you please check following and let us know if there are any errors
    - Help -> Toggle Developer Tools -> Console
    - Help -> Toggle Developer Tools -> Network - Check for extensions gallery requests
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by odebroqueville** [comment]
Yesterday, VSC wouldn't even connect to a GitHub server either, but today things are back to normal. The extensions are displaying properly again. If the issue re-occurs, I'll check the above for errors.
Right now I only see the following:
- in Log (Window): [2020-10-02 12:14:53.967] [renderer1] [error] No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
- in the Dev Tools Console: /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:284 [Extension Host] (node:1072) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by sandy081** [comment]
Closing this as it can't be repro.

Please reopen it if you see this again with required info
