### ISSUE TITLE
Feature: Ability to save regex Find/Replace patterns for future use 

### ISSUE THREAD

**Issue by disaac** [Microsoft/vscode#10791]
### Feature Request
- VSCode Version:
Version 1.4.0 (1.4.0)
- OS Version:
OS X El Capitan 10.11.6 (15G31)

Steps to Reproduce:

1. Open a text document in vscode with a fair amount of text. 
2. Launch the Find/Replace dialogue "Command + F" 
3. Click the regex icon to enter a regex pattern for the find and replace forms. 
4. Observe there is no means from that dialogue to save the regex pattern or reference previously used regex patterns. 

Expected Behavior: 
1. The Find/Replace dialogue would provide a means of saving regex patterns used for future use. Please see attached screen shots of the method BBEdit uses to accomplish this as an example of this feature. 
![screenshot_1315](https://cloud.githubusercontent.com/assets/15255373/17853055/539c3e3a-681f-11e6-8d74-efb1f0b77bb5.png)

**Comment by sandy081** [comment]
Duplicates #5865
