### ISSUE TITLE
Loss of settings on second window

### ISSUE THREAD

**Issue by infromthecold** [microsoft/vscode#107964]
- VSCode Version: Version: 1.49.2 (system setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. On Windows  Ctrl+K, then release the keys and press O (the letter O, not Zero).
2. This will open the active file tab in a new window/instance.
3. Press tab and enter some text with more tabs, the tabs will become spaces
4. When you return to the original window (instance) and reload the edited file it has spaces where you pressed tab

The new window appears to be ignoring the "settings": in the workspace file such as "editor.insertSpaces": false

Does this issue occur when all extensions are disabled?: Yes/No
Not tried

**Comment by bpasero** [comment]
> The new window appears to be ignoring the "settings": in the workspace file such as "editor.insertSpaces": false

Yes, because the new window is not inside that workspace. You need to configure globally.
