### ISSUE TITLE
again 'Extension host terminated unexpectedly.'

### ISSUE THREAD

**Issue by nilshendriks** [microsoft/vscode#107970]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

you can close this all you want but it's still an issue. happens all the time.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (5.18GB free)|
|Process Argv|--crash-reporter-id 1acf93cb-1c12-4acd-8421-ff1457d38657|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
project-manager|ale|11.3.0
gitflow-actions-sidebar|ard|0.5.2
vscode-intelephense-client|bme|1.5.4
gltf-vscode|ces|2.3.1
turbo-console-log|Cha|1.4.0
npm-intellisense|chr|1.3.1
html-entities|chr|1.1.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.8
vscode-quick-select|dba|0.2.9
vscode-dash|dee|2.4.0
chmod|dle|1.1.1
githistory|don|0.6.10
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.1
vscode-diff|fab|1.4.0
vscode-todo-plus|fab|4.18.0
vscode-firefox-debug|fir|2.9.1
auto-rename-tag|for|0.1.4
vscode-pull-request-github|Git|0.20.0
vscode-graphql|Gra|0.3.10
beautify|Hoo|1.5.0
rest-client|hum|0.24.2
vscode-placeholder-images|Jak|0.1.0
replace-curly-quotes|jin|1.1.0
vscode-styled-components|jpo|0.0.32
graphql-for-vscode|kum|1.15.3
vs-color-picker|lih|1.0.0
sftp|lix|1.12.9
vscode-smart-column-indenter|lmc|0.0.13
gitignore|mic|1.0.1
vscode-wrap-console-log|mid|1.7.2
ecdc|mit|1.3.0
HTMLHint|mka|0.8.0
prettify-json|moh|0.0.3
vscode-apache|mrm|1.2.0
vscode-csscomb|mrm|5.3.2
vscode-json-editor|nic|0.2.3
vetur|oct|0.28.0
indent-rainbow|ode|7.4.0
vscode-print|pdc|0.7.15
polacode|pnp|0.3.4
vscode-css-peek|pra|4.0.0
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.0.1
language-stylus|sys|1.11.0
ayu|tea|0.20.1
html-preview-vscode|tht|0.2.5
lorem-ipsum|Tyr|1.2.0
gitflow|vec|1.2.1
vscode-icons|vsc|11.0.0
change-case|wma|1.0.0
vsc-jsonsnippets|wmo|0.7.0
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.3.0
material-theme|zhu|3.9.0
html-css-class-completion|Zig|1.19.0

(6 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
