### ISSUE TITLE
finally fixed my terminal font issues

### ISSUE THREAD

**Issue by hems** [microsoft/vscode#107942]
After months and months having the issue with my font being cropped on the bottom of the terminal i managed to solve the issue by importing the font into https://www.glyphrstudio.com/online/ then export it as OTF.

This comment is related to https://github.com/microsoft/vscode/issues/35901 and the reason why i'm creating this separate "issue" is because that issue is `locked` and it seems there are a lot of people with the same problem, so perhaps this "tip" could be added to an FAQ of some sort.

Thanks a lot for your hard work on VSCode.

**Comment by Tyriar** [comment]
Thanks for the info! I added it to the locked issue to increase visibility. Since the canvas renderer will be removed in the future (https://github.com/microsoft/vscode/issues/106202) I don't think we should add this to the docs.

**Comment by hems** [comment]
> Thanks for the info! I added it to the locked issue to increase visibility. Since the canvas renderer will be removed in the future (#106202) I don't think we should add this to the docs.

i'm not 100% sure if that's related to the canvas renderer.. i remember trying the experimentalWebGL on OSX and Linux and it had exactly the same issue, at least with that font, and i assume, with other fonts too.

**Comment by hems** [comment]
![image](https://user-images.githubusercontent.com/27327/99245014-d0018580-27fa-11eb-8b55-e43e55c6b000.png)

That's my comment on the experimentalWebGL from the time i tried.. 

I just installed vs code on my fresh linux machine so i'm not sure which rendered i'm using now, how can i check which one is currently being used?

**Comment by veleek** [comment]
@hems - I gave this a shot bit it broke a bunch of the characters (could have been me using Glyphr Studio wrong) and it didn't appear to fix the other graphical problems I was having.
