### ISSUE TITLE
"editor.formatOnSaveMode": "modifications" not working as expected

### ISSUE THREAD

**Issue by thdoan** [microsoft/vscode#107940]
- VSCode Version: 1.49.2 (user setup)
- OS Version: Windows 10 64-bit (build 10.0.19041)

Steps to Reproduce:

1. Ensure settings.json has this:

```
    "editor.formatOnSaveMode": "modifications",
    "[javascript]": {
        "editor.formatOnPaste": true,
        "editor.formatOnSave": true
    }
```

2. Open the attached JS file in the zip: [test.zip](https://github.com/microsoft/vscode/files/5315337/test.zip)
3. Change line 3 to: `function component(){`

Since I modified line 3, I was expecting it to format line 3 to `function component() {` on save.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
What formatter extension are you using? Default or something like prettier?

**Comment by thdoan** [comment]
I don't have any formatters installed -- using default.

**Comment by jrieken** [comment]
Please try the follow: manually select the modified text in the editor and then execute "format selection"

**Comment by thdoan** [comment]
> Please try the follow: manually select the modified text in the editor and then execute "format selection"

This worked -- the selection was formatted correctly.

If I remove `"editor.formatOnSaveMode": "modifications"` and save, the code is also formatted correctly.

For your reference, here is my full settings.json:

```
{
    "breadcrumbs.enabled": true,
    "css.lint.ieHack": "warning",
    "editor.acceptSuggestionOnEnter": "off",
    "editor.autoClosingBrackets": "never",
    "editor.autoClosingQuotes": "never",
    "editor.codeLens": false,
    "editor.comments.insertSpace": false,
    "editor.dragAndDrop": false,
    "editor.find.autoFindInSelection": "multiline",
    "editor.find.cursorMoveOnType": false,
    "editor.formatOnSaveMode": "modifications",
    "editor.hover.enabled": false,
    "editor.minimap.enabled": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.renameOnType": true,
    "editor.renderLineHighlight": "gutter",
    "editor.snippetSuggestions": "top",
    "editor.unusualLineTerminators": "auto",
    "explorer.confirmDelete": false,
    "files.exclude": {
        "**/__pycache__": true,
        "**/.vscode": true
    },
    "files.restoreUndoStack": false,
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "git.enableSmartCommit": true,
    "html.format.wrapLineLength": 0,
    "javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
    "javascript.preferences.quoteStyle": "single",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": true,
    "python.pythonPath": "C:\\dev\\Miniconda3",
    "search.searchEditor.reusePriorSearchConfiguration": true,
    "sortLines.sortEntireFile": true,
    "task.problemMatchers.neverPrompt": {
        "shell": true
    },
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "terminal.integrated.fontSize": 12,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "workbench.colorCustomizations": {
        "editor.selectionBackground": "#135564",
        "editor.selectionHighlightBackground": "#135564"
    },
    "workbench.editor.highlightModifiedTabs": true,
    "workbench.enableExperiments": false,
    "[javascript]": {
        "editor.formatOnPaste": true,
        "editor.formatOnSave": true
    }
}
```

Is it possible one of the settings is the culprit?

**Comment by jrieken** [comment]
> This worked -- the selection was formatted correctly.

That's funny. Format modified does exactly that - it takes the modified (line) range and formats that, using the same mechanics as format selection

**Comment by thdoan** [comment]
> > This worked -- the selection was formatted correctly.
> 
> That's funny. Format modified does exactly that - it takes the modified (line) range and formats that, using the same mechanics as format selection

That's why I'm baffled. Can you see if you can replicate using my settings above and the test file?

**Comment by gjsjohnmurray** [comment]
Is the file in source control? Do you see the change indicator bar alongside the line you modified?

**Comment by thdoan** [comment]
The file is not in source control.

**Comment by gjsjohnmurray** [comment]
That's the reason then. See documentation for this feature at https://code.visualstudio.com/updates/v1_49#_only-format-modified-text

**Comment by thdoan** [comment]
@gjsjohnmurray ah that explains it -- thanks! I don't know the innerworkings of VS Code, but would it be possible to have this useful feature for files that are not in source control?

If not, then do you know if there's a way for me to automatically set `"editor.formatOnSaveMode": "file"` for files that are no source controlled?

**Comment by robrecord** [comment]
My file is source controlled and I have the same issue

**Comment by jrieken** [comment]
> Shall I open a new issue?

Yes - after having tried "format selection" on same range
