### ISSUE TITLE
Exclude files not respecting .gitignore negations

### ISSUE THREAD

**Issue by mossypig** [microsoft/vscode#107944]
- VSCode Version: 1.49.2
- OS Version: Centos 8 / Mac OS X

Steps to Reproduce:

1. Add a git ignore pattern for a folder. This will remove it from search and quick open (cmd + p)
```
cpp
```
2. Add a negation to allow some files to come through 
```
!cpp/*.cpp
!cpp/*.h
!cpp/Makefile
```

I noticed this on OSX and again on Linux. It seems that adding a folder to .gitignore adds it to the list of excluded files (search and quick open) but adding a negation to let some files through does not have an impact. The above example is me ignoring my cpp folder as to not include .o and runtime C++ files but keeping .cpp, .h and makefiles as they should be version controlled. However this has the affect of me not being ever to quick open or search C++ files. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment]
Yes, ripgrep diverges from git slightly here unfortunately. https://github.com/BurntSushi/ripgrep/issues/778

Changing `cpp` to `cpp/*` would work around it for you though
