### ISSUE TITLE
editor.action.moveLinesDownAction erroneously offsets the block to the right

### ISSUE THREAD

**Issue by Kasheftin** [microsoft/vscode#107915]
- VSCode Version: 1.49.1
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Select some lines;
2. Press ctrl+shift+down to swap selected lines with the next one (assuming you have ctrl+shift+down binded to editor.action.moveLinesDownAction);
3. The code shift to the right with every keypress while it's expected to move vertically only;

Does this issue occur when all extensions are disabled?: Yes

![moveLinesDownActionBug](https://user-images.githubusercontent.com/379267/94848321-85839f80-042c-11eb-8e52-1ee035975a77.gif)

**Comment by gjsjohnmurray** [comment]
Also #72849

**Comment by Kasheftin** [comment]
Since I got used sublime a lot, it seems the simplest solution for me would be setting "editor.autoIndent": "brackets" rule (restricting vs code autoIndent).
