### ISSUE TITLE
Cant edit code

### ISSUE THREAD

**Issue by mtho2014** [microsoft/vscode#107986]
When I open a file to edit the code I created, I cannot type any text in the code. A this bar replaces my curser and the only way for it to get out of that mode so I can make changes to my code is by quickly pushing a lot of keys on my keyboard. Same thing happens when I create a new file and copy and past a code from somewhere else. I included a screenshot that has a circle around the bar I was talking about. 

<img width="551" alt="Screen Shot 2020-10-02 at 11 14 56 AM" src="https://user-images.githubusercontent.com/71346322/94956289-c4533d00-04a0-11eb-8c5d-145bb883b56e.png">

**Comment by mtho2014** [comment]
Also, When I run the code, it wont let me input any data and says I can't edit in a read only editor. How do I get out of this read only editor mode?

<img width="1092" alt="Screen Shot 2020-10-02 at 11 21 20 AM" src="https://user-images.githubusercontent.com/71346322/94956732-860a4d80-04a1-11eb-8e63-b7dd89aaa150.png">

**Comment by ssw99** [comment]
Do you use vim extension?

**Comment by mtho2014** [comment]
yes, it's installed

**Comment by mtho2014** [comment]
I've also tried opening a new file and just writing a new code and it still isn't letting me type anything and showing that thick bar for the curser
<img width="357" alt="Screen Shot 2020-10-02 at 11 51 32 AM" src="https://user-images.githubusercontent.com/71346322/94959190-a0462a80-04a5-11eb-8d1c-651a232e7044.png">

**Comment by jrieken** [comment]
> Do you use vim extension?

Try without VIM?

**Comment by mtho2014** [comment]
That worked!! thank you!

**Comment by jrieken** [comment]
Ok, thanks for coming back
