### ISSUE TITLE
JavaScript files not recognised on MacOS 

### ISSUE THREAD

**Issue by FaresKi** [microsoft/vscode#107934]
- VSCode Version: 1.49.2
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Create folder
2. Create js files.

Result : 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/46092308/94870928-17010a80-0449-11eb-8dd3-101ae9e8ae99.png">
Extensions : 
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/46092308/94871090-7a8b3800-0449-11eb-9fb7-9ad5cde0bacf.png">
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/46092308/94871118-8bd44480-0449-11eb-96e2-95c14fa200bf.png">

Does this issue occur when all extensions are disabled?: Yes
Same result : 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/46092308/94871033-50d21100-0449-11eb-842d-0a27a9fe676c.png">

**Comment by mjbvz** [comment]
What is the issue?

**Comment by FaresKi** [comment]
Well the issue is that autocompletion and IntelliSense do not work, despite installing the extensions. I only got the syntax colors by changing themes. But if you check on your left, even the files don’t have the JS icons.

Le 2 oct. 2020 à 21:30, Matt Bierner <notifications@github.com<mailto:notifications@github.com>> a écrit :



What is the issue?

**Comment by nrayburn-tech** [comment]
You may have your file icons disabled.  You can change the theme by opening the command palette (`cmd + shift + p` on a mac) and then selecting the `File Icon Theme`.  From here, pick the theme you want to use.

This does not require any extensions to work properly, but additional themes can be installed.

As far as the autocompletion, more information is still needed for that.

**Comment by mjbvz** [comment]
@FaresKi Did you disable the built-in JavaScript and TypeScript language features extension? In the extensions view, search `@builtin` to check this

**Comment by FaresKi** [comment]
Ended up reinstalling VSCode and the extensions. Must’ve been a slight bug. We can close the issue.

Le 8 oct. 2020 à 08:40, Matt Bierner <notifications@github.com> a écrit :

﻿

@FaresKi<https://github.com/FaresKi> Did you disable the built-in JavaScript and TypeScript language features extension? In the extensions view, search @builtin to check this
