### ISSUE TITLE
Restore cursor position for readonly files

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#10794]
- VSCode Version: 1.4.0
- OS Version: Windows 10/64

### Steps to Reproduce:
1. Open two or more files in an editor group.
2. In one of the opened files scroll down a number of lines.
1. Press `CTRL+TAB` multiple times until the editor group revolves to the original file.

=> You will notice that the previous cursor position was lost and that the cursor has moved to the first column in the first line of the file.

### Suggested behaviour:
The cursor position for each opened file in the editor should be retained.

----
PS: I'd like to propose an option to have `CTRL+TAB` not only cycle through opened files within a _single_ editor group but through _all_ files in _all_ editor groups. This would reflect common Microsoft style guide and program behaviour and would increase daily VS Code usability.

**Comment by sandy081** [comment]
@SetTrend I see the cursor position is retained while doing `ctrl+tab`. May I know is there anything else we would be knowing about your set up, say extensions or custom configurations?

**Comment by SetTrend** [comment]
I dug into this issue more deeply and recognized that this problem is only true for read-only files.

Here you can see a screencast showing me trying to CTRL+TAB user settings:

![cursor position is not retained](https://cloud.githubusercontent.com/assets/9283914/17897152/7046e7a8-6953-11e6-805d-7bfae4af967f.gif)

**Comment by bpasero** [comment]
@SetTrend you can use the `workbench.action.showAllEditors` command to show editors across all groups and navigate to them. By default its keybinding is `Ctrl+K Ctrl+P` but that can be changed.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4314
