### ISSUE TITLE
Regex search in file results in ReDoS

### ISSUE THREAD

**Issue by effleurager** [microsoft/vscode#107902]
Regarding https://github.com/microsoft/vscode/issues/97238#issuecomment-631545925 , that looks to be mentioning a search in file, where we use the built-in JavaScript regex, so these two issues are AFAICT unrelated.

_Originally posted by @alexdima in https://github.com/microsoft/vscode/issues/97238#issuecomment-702157124_

**Comment by effleurager** [comment]
A regex search of a file with the following causes a hang:
```
smallest_valid_png = %w[89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 01 00 00 00 01 08 06 00 00 00 1f 15 c4 89 00 00 00 0a 49 44 41 54 78 9c 63 00 01 00 00 05 00 01 0d 0a 2d b4 00 00 00 00 49 45 4e 44 ae 42 60 82]
```
regex:
```
(?:smallest_valid_png = %w\[)(?:.*( ))*\]
```

**Comment by effleurager** [comment]
Affects the latest stable release and insider release.
<hr/>
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
<hr/>
Version: 1.50.0-insider
Commit: 228973889bc0e352f7cd11cc14755893f8d81864
Date: 2020-10-01T05:28:37.293Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by alexdima** [comment]
I tried the input at https://regex101.com/ and it appears the regex suffers from catastrophic backtracking:

![image](https://user-images.githubusercontent.com/5047891/94847430-ddb5a400-0422-11eb-9457-dc1c17a80ccf.png)

More info: http://www.regular-expressions.info/catastrophic.html

There are many such regular expressions and from what I could tell, `v8` or other JS engines don't care to hear about them and they recommend to simply avoid such regexes.
