### ISSUE TITLE
Stop auto collapsing the activity bar

### ISSUE THREAD

**Issue by zwhitchcox** [microsoft/vscode#107901]
Please, please please have a way to turn off auto-collapsing the activity bar. On every other computer, it works fine, but when I'm on my mac, it auto collapses whenever I go to the editor. I don't know if there's some setting I've set, but I've looked everywhere, but this is killing me inside. Every time I switch to the editor, the activity bar collapses automatically, and it only happens on mac.

**Comment by zwhitchcox** [comment]
I've tried deleting my settings, but it still disappears the activity bar

**Comment by zwhitchcox** [comment]
I also deleted every plugin and keyboard shortcut

**Comment by zwhitchcox** [comment]
I tried using app cleaner to delete every file related to vs code and reinstall, and it still does this

**Comment by isidorn** [comment]
We do not do this in vscode core.
I am 100% sure one of your extensions is doing this. Please disable them one by one to figure out which one

**Comment by zwhitchcox** [comment]
Oh. My. God. Thank you so much that was driving me fucking ballistic.
