### ISSUE TITLE
Associated icons not showing correctly in Finder

### ISSUE THREAD

**Issue by frizzyCat** [microsoft/vscode#107972]
- VSCode Version: 1.48.2
- OS Version: MacOS 10.15.6

Steps to Reproduce:
1. Set VSCode as default for opening a file (.cpp for example) on MacOS.

Does this issue occur when all extensions are disabled?: Yes

When choosing VSCode as default for opening certain files, the associated icon is blank with the VSCode icon on it, even though they are supposed to have different icons as seen here (https://github.com/microsoft/vscode/issues/4845#issuecomment-387570782).

<img width="118" alt="Screenshot 2020-10-02 at 15 09 17" src="https://user-images.githubusercontent.com/72204862/94926571-49e6e500-04c1-11eb-909b-8536246b305a.png"> 

I only tested some file types but I got the same result every time.
Other programs like Xcode don't have this issue.

**Comment by joaomoreno** [comment]
Can you zoom in on Finder? Do the works appear correct then?

**Comment by frizzyCat** [comment]
> Can you zoom in on Finder? Do the works appear correct then?

When using the bigger grid view, it shows the standard MacOS icons instead of the the ones seen in the linked comment. 

<img width="439" alt="Screenshot 2020-10-08 at 07 00 00" src="https://user-images.githubusercontent.com/72204862/95417076-6efdac80-0934-11eb-90d6-d1ec6dd24e80.png">

**Comment by joaomoreno** [comment]
Can you try to refresh the icon cache? https://gist.github.com/fabiofl/5873100

**Comment by frizzyCat** [comment]
I tried it but the bug still remains. 
I also experienced this behaviour on 3 different Macs und even under Mojave.

**Comment by joaomoreno** [comment]
I don't have a macOS machine any more, so I'm unable to repro, investigate or fix this. I wonder if someone wants to look at this? @misolori @bpasero @isidorn @jrieken @roblourens @mjbvz @sandy081

**Comment by bpasero** [comment]
Not having a lot of energy either, but we could set "help wanted" to get someone with energy look into it and investigate it?

**Comment by misolori** [comment]
I think this is the same as #107306

**Comment by misolori** [comment]
Do we have instructions for creating a build from OSS (not running from sources) to test this out if someone wanted to help?

**Comment by joaomoreno** [comment]
It's somewhat here: https://github.com/microsoft/vscode/wiki/How-to-Contribute#packaging

This does the trick:

```
yarn gulp vscode-darwin
```

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/107306
