### ISSUE TITLE
Add ability to go back one level in breadcrumb

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#107954]
If I am in code where the breadcrumb shows this:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/6391776/94900109-b8617e00-0494-11eb-87a6-707d0ec64a79.png">

I'd like to have a keybinding that when pressed will go back 1 level so I will be here:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/6391776/94900259-fb235600-0494-11eb-9651-adeed29f7da1.png">

Perhaps this is already possible? If not, please add it.

**Comment by jrieken** [comment]
Only a sequence of shortcuts is available: `Cmd+Shift+;` ⏭️ `ArrowLeft` ⏭️ `Space`

**Comment by nikitavoloboev** [comment]
`Cmd+Shift+` on mac will increase font size. What is the command name?

**Comment by jrieken** [comment]
> Cmd+Shift+ on mac will increase font size.

Not `Cmd+Shift+` but `Cmd+Shift+;`

**Comment by nikitavoloboev** [comment]
Yeah just realized it. Thanks. 😻
