### ISSUE TITLE
Indicate default values in settings.json

### ISSUE THREAD

**Issue by silesky** [microsoft/vscode#107988]
#### Doc / Feature Request 
My `settings.json` is the primary way I interact with settings, and I often want to change a value that I'm experimenting with back to a default -- but I don't remember which value that is.
> What's the default here?
![image](https://user-images.githubusercontent.com/5115498/94958368-071f1000-04b5-11eb-9698-f9202d68ca12.png)

In the Settings UI, there is a reset settings button -- but there is no equivalent functionality for the settings.json.

This can be ameliorated through one of the following:
- [doc] add the value to the setting documentation for all native settings, like some third party extensions [do](https://user-images.githubusercontent.com/5115498/94957949-4f89fe00-04b4-11eb-93f3-813f4b283d14.png).
- [feature] add a "reset settings"  to the quickFix (lightbulb) or some other way (potentially more complicated)

**Comment by roblourens** [comment]
I just comment it out when I want to put it back to the default, does that address this for you?

**Comment by silesky** [comment]
> I just comment it out when I want to put it back to the default, does that address this for you?

Not quite, I do that too, but I still need to look up the default.

That only helps for settings that are copied from elsewhere to your settings.json. Unfortunately, it doesn’t help when you are adding a setting by using autocomplete (ctrl+space) to discover the name — since autocomplete does not also fill in the default value.

**Comment by roblourens** [comment]
It looks like not all settings declare which value is the default in their schema
