### ISSUE TITLE
after updating Python 3.8 , Can't regoconize Python Interpreter(python.exe path doesn't work)

### ISSUE THREAD

**Issue by DeepakDk04** [microsoft/vscode#107967]
Issue Type: <b>Performance Issue</b>

after updating the python version, VS code doesn't regaconize the python.exe files. It always shows that select Python Interpreter, But after I'm choosing manually , It does not resolve

steps to reproduce:
1) Update Python locally On windows
2) Open python file in VS code
3)It prompts select interpreter ,
4)Choose python path
5)It prompts python does't installed download

note: My vs code is working file as long as I use previous python version. Issues occurs after the Python Update locally

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A4-4350B R4, 5 COMPUTE CORES 2C+3G      (2 x 2495)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.84GB (0.69GB free)|
|Process Argv|--crash-reporter-id 811391a9-6009-41c1-acaf-fc67784227a0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   104	 12152	code main
    1	   243	   776	   gpu-process
    0	    67	  3748	   shared-process
    0	    29	  7228	   utility
    0	   157	  8984	   window (PythonPractices - Visual Studio Code)
    0	     6	  3708	     console-window-host (Windows internal process)
    0	    11	  4204	     watcherService 
    0	    11	 10432	       console-window-host (Windows internal process)
    0	     4	  4760	     C:\WINDOWS\System32\cmd.exe
    0	    32	  8652	     searchService
    0	    97	  8996	     extensionHost
    0	    26	  1964	       electron_node serverMain.js 
    0	    72	 10812	   window (Issue Reporter)
    0	    14	 11624	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (PythonPractices - Visual Studio Code)
|    Folder (PythonPractices): 3 files
|      File types: py(2) txt(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.10.21
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
auto-rename-tag|for|0.1.4
vscode-pull-request-github|Git|0.20.0
beautify|Hoo|1.5.0
restructuredtext|lex|129.0.0
python|ms-|2020.9.112786
material-icon-theme|PKi|4.3.0
LiveServer|rit|5.6.1
preview-vscode|sea|2.1.0
jinja|who|0.0.8

</details>

**Comment by myfix16** [comment]
The same issue. It can't recognize python interpreter even if I designated the path.
![image](https://user-images.githubusercontent.com/61649477/94929110-3b1b2500-04f7-11eb-8b4b-2025640dbbe0.png)

**Comment by yezz123** [comment]
@DeepakDk04  And now with the last version is work or no?
Cause its the same issues for me and when i change to old version like the one of ` Microsoft visual studio` or `Anaconda 3` its work.

### 1. System info:

```
**_Operating System:_** Windows 10 Pro 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
**_Windows Version:_** 2004
**_Processor:_** Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 CPUs), ~2.3GHz
**_Memory:_** 16384MB RAM
```

**Comment by smartgamer1280** [comment]
I always add and the path and then on the next restart it always says that add interpreter in visual studio code
