### ISSUE TITLE
Markdown should handle GFM links with parenthesis/special chars in URL 

### ISSUE THREAD

**Issue by disaac** [Microsoft/vscode#10790]
- VSCode Version:
  Version 1.4.0 (1.4.0)
- OS Version:
  OSX El Capitan 10.11.6 (15G31)
  Steps to Reproduce:
1. Create or open a Markdown document in vscode with the .md extension. 
2. Open the vscode Markdown Preview window for live previewing.  ⇧⌘V
3. Add the following markdown formatted link and header text to the document. 

```
# This is a markdown formatting test
Here is a link 
[TestLink](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metrics:graph=~(metrics~(~(~'AWS*2fEC2~'CPUUtilization~'AutoScalingGroupName~'asg-prod-test)~(~'.~'NetworkIn~'.~'.~(yAxis~'right))~(~'.~'NetworkOut~'.~'.)~(~'AWS*2fLogs~'IncomingBytes~'LogGroupName~'TEST_Proxy)~(~'.~'IncomingLogEvents~'.~'.)~(~'AWS*2fEC2~'CPUUtilization~'AutoScalingGroupName~'asg-test-markdown-instance)~(~'.~'NetworkIn~'.~'.~(yAxis~'right))~(~'.~'NetworkOut~'.~'.)~(~'.~'CPUUtilization~'.~'asg-test-markdown-instance)~(~'.~'NetworkIn~'.~'.~(yAxis~'right))~(~'.~'NetworkOut~'.~'.)~(~'AWS*2fLogs~'IncomingBytes~'LogGroupName~'test-markdown-vpc-flow-logs)~(~'.~'IncomingLogEvents~'.~'.))~period~60~stat~'Average~start~'2016-08-17T04*3a00*3a00Z~end~'2016-08-17T07*3a01*3a59Z~yAxis~(left~null~right~null)~region~'us-east-1))

```
1. Observe the link is not formatted or displayed correctly. The complex assortment of characters specifically parenthesis and tilda seem to prevent the parser from properly recognizing the link. 
2. Perform the same the test using [BBEdit](http://www.barebones.com/products/bbedit/) and [Github Markdown Preview Package](https://github.com/gavinaiken/bbedit-scripts) 
3.  Observe the link is properly formatted in the preview window. 

**Please see attached screen shots for side by sides of preview examples** 
![vscode-markdown-preview-defect](https://cloud.githubusercontent.com/assets/15255373/17852545/be82b10a-681c-11e6-9b75-c0ed34de662e.png)
![bbedit-markdown-preview-plugin](https://cloud.githubusercontent.com/assets/15255373/17852551/c6299b08-681c-11e6-84b5-31ef45254d63.png)

**Comment by mjbvz** [comment]
The exact problem seems to be nested parens, as in a link destination like this `https://example.com/?key=a(b(c))`

According to the [commonmark spec](http://spec.commonmark.org/0.25/#links), this destination link is invalid (or at least will not be parsed properly):

> A link destination consists of either:

> a sequence of zero or more characters between an opening < and a closing > that contains no spaces, line breaks, or unescaped < or > characters, or

> a nonempty sequence of characters that does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses that is **not itself inside a balanced pair of unescaped parentheses.**


[Here's the line in markdown-it that handles nesting ](https://github.com/markdown-it/markdown-it/blob/master/lib/helpers/parse_link_destination.js#L62). So I believe that failure to parse the link is by design, at least with the markdown spec we target

One workaround is escaping parens in the link destination: `https://example.com/?key=a\(b\(c\)\)`

**Comment by disaac** [comment]
Interesting regarding the [commonmark spec](http://spec.commonmark.org/0.25/#links) I agree and can certainly use the workaround. In light of the specification being targeted I would say this issue could be closed or changed to a feature request for GFM support. 

It should be noted that Git Hub Flavored Markdown properly handles the nested parentheses. The [BBEdit Github Flavored Markdown parser](https://github.com/gavinaiken/bbedit-scripts) is using [redcarpet](https://github.com/vmg/redcarpet) which also does not require the escaped nested parentheses. 
 
As an example using the Github WYSIWYG editor for this post I highlighted the `https://example.com/?key=a(b(c))` and clicked the link icon and it also omitted the escape characters rendering as shown below:  
[Testlink](https://example.com/?key=a(b(c)))

**Comment by mjbvz** [comment]
After upgrading our markdown-it version, the example link is now handled correctly in the preview:

![screen shot 2017-09-05 at 3 41 21 pm](https://user-images.githubusercontent.com/12821956/30086598-be214686-9250-11e7-9bd8-fbae2b01f657.png)

Please try out the first 1.17 VSCode insiders build once those start up
