### ISSUE TITLE
Typescript died

### ISSUE THREAD

**Issue by angelod1as** [microsoft/vscode#107922]
Issue Type: <b>Bug</b>

Cloned [this repo](https://github.com/rocketseat-content/react-nextjs-typescript-structure) and opened vscode on the root folder.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|14, 13, 12|
|Memory (System)|8.00GB (0.46GB free)|
|Process Argv|. --crash-reporter-id 711ce1c2-56e1-4fe1-88fe-4a8d6537e7e2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-emoji|bie|0.0.9
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
todo-tree|Gru|0.0.178
path-autocomplete|ion|1.15.0
vscode-styled-components|jpo|0.0.31
dotenv|mik|1.0.1
vscode-docker|ms-|1.6.0
debugger-for-chrome|msj|4.12.11
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.3.0
polacode|pnp|0.3.4
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
vscode-wakatime|Wak|4.0.8
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Doesn't happen for me on the repo

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by angelod1as** [comment]
This happened at least three times before I posted the issue. Now it suddenly isn't happening anymore. I don't know why, I changed *nothing* from before, just closed and opened VSCode (as I did the other times)
