### ISSUE TITLE
Images are never reloaded

### ISSUE THREAD

**Issue by oflebbe** [Microsoft/vscode#10796]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. New Directory
2. run code .
3. Place an PNG file as picture.png in that directory
4. View It with VS Code (using explorer): File displays correctly
5.Delete the file with the  explorer
6. Place a different PNG File with the same name as picture.png in directory
7. View with explorer: The first image is displayed. (Expected the new image)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7951

**Comment by bpasero** [comment]
@oflebbe Code is not an image editor, if you need an image editor, I suggest you use an image editor 👍

**Comment by oflebbe** [comment]
#10577 is the duplicate. The #7951 may be related. Thanks for finding the dups. Haven't found  them.
