### ISSUE TITLE
Breakpoints don't show in the editor, debugger opens new windows

### ISSUE THREAD

**Issue by GWBasic** [microsoft/vscode#107912]
I'm having two very closely related issues. I suspect they are the same bug.

When I set a breakpoint, it doesn't show up in the editor. It does show up in the breakpoints pane.

When I hit the breakpoint, Visual Studio opens the same file in a new tab. This new tab shows the breakpoints and is read-only.

I certainly hope this isn't expected behavior! (It's very confusing, and goes against what every IDE I've ever used does.)

For context:
- I'm using Javascript
- This is a node.js project
- I don't know if I set up the project "wrong." I created a project folder via npm and then imported it into Visual Studio code

Also, if it's helpful:
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by isidorn** [comment]
Can you share a minimal repository which we can clone and reproduce this problem?
Can you reproduce this issue with vscode insdiers https://code.visualstudio.com/insiders/
