### ISSUE TITLE
Changes to terminal selection break plugins and WSL/OS mapping

### ISSUE THREAD

**Issue by aaronsteers** [microsoft/vscode#107906]
Issue Type: <b>Bug</b>

I am using windows (native) and often also use WSL as my terminal. However, when toggling between terminal defaults (WSL or Cmd/PS), this also appears to break other plugins which are configured on one or the other platform, or which leverage syntax specific to a certain platform.

Is this expected? I think there's a need to be able to specify which terminal my plugins and "vs code internals" use - and that should not be tied to what terminal I'm running my tests in. 

Am I missing some configuration option? Can you describe if this breakage is expected or if there's a way to eliminate/remap those dependencied upon my default terminal selection?

Thank you!

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.14.158-129.185.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (1.00GB free)|
|Process Argv|--crash-reporter-id 131c17f6-b8b6-4613-98c2-7fbbc2efbb1f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 34.214.119.36|
|OS|Linux x64 4.14.158-129.185.amzn2.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz (2 x 2899)|
|Memory (System)|3.67GB (0.49GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bracket-pair-colorizer-2|Coe|0.2.0
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.6.0
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
material-icon-theme|PKi|4.3.0
jinjahtml|sam|0.15.0
code-settings-sync|Sha|3.4.3
ayu|tea|0.20.1
vscode-icons|vsc|11.0.0
material-theme|zhu|3.9.0
quick-run-panel|dav|0.0.3
vscode-sqlfluff|dor|0.0.3
gitlens|eam|10.2.2
RunOnSave|eme|0.2.0
python|ms-|2020.9.112786
gradle-language|nac|0.2.3
vscode-yaml|red|0.11.1
vscode-gradle|ric|3.4.5

(11 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Can you elaborate on what you mean by breaking other plugins? I also notice you say Windows (native) but your issue report mentions a remote OS:

> Remote OS version: Linux x64 4.14.158-129.185.amzn2.x86_64

Are you using the WSL/SSH extension or is this another unrelated window?
