### ISSUE TITLE
Allow contributions to the search viewlet context menu

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode#107996]
**Feature:** Set breakpoints on all results of a text search

**Sample scenario:** I want to set a breakpoint on all the places that **sourceMap.url** is accessed. I can use the Text Search feature to find all those places. There are a lot of places where that code is used, so it's annoying to have to go through each one to set a breakpoint.
It'd be great if after searching for **sourceMap.url** I could tell VS Code to put a breakpoint in all the lines or places that the text search feature found.

This would allow us to to thing such as:
 * Search for all places that call fs.readFile, and set a breakpoint on all of them
 * Search for all constructors, and set a breakpoint on all of them
 * Assuming I can create a Regexp to find the first line of all methods, I could set a breakpoint that stops in the first line of each method for a particular class
 * Search for all places that use process.env and set a breakpoint on all of them
etc...

**Comment by connor4312** [comment]
This is a good idea for an extension I think.

**Comment by roblourens** [comment]
I actually want to leave it open to consider it. I can think of times that it would have been helpful to me. And the only way for an extension to do this would be to run its own search, which seems less useful, I want to preview the search results before blasting breakpoints all over. It could just be an unobtrusive context menu option in the search viewlet.

**Comment by roblourens** [comment]
Actually, we can support extensions implementing this with just a little effort

- Support multiselect in the search viewlet - https://github.com/microsoft/vscode/issues/47166
- Allow contributions to the search viewlet context menu, where the command gets some info about the selected search result

@digeff if you are interested in doing a PR, this would take some effort, but is probably doable

**Comment by roblourens** [comment]
Pulled this out of the build because it broke a (non-oss) test, and https://github.com/microsoft/vscode/pull/109049/files#r521207010

**Comment by roblourens** [comment]
> I'm looking at the proposed API that we have for search results and trying to decide whether it makes sense to use the same objects here. You could make a case either way. If we can make a case to design this api without necessarily tying it to search provider API, then we can do this without making it part of the whole search provider api problem.
>
> One difference between the UI results and the provider results is that providers return one Match per line, possibly with multiple ranges on the line. The UI object always has one object per actual match. Or you would want some additional info like the replacement value.

@jrieken wondering what your thoughts are and whether you are open to defining this API on its own, or whether we should wait for search provider API. I guess this situation is different than all other menus. Sorry for trying to sneak API in through the back door.

**Comment by jrieken** [comment]
Yeah, unsure if the future API will work here or not. If you wanna go fast and independent of that, than `vscode.Location` comes to my mind. It's an uri with a range or position and might work well enough for the search results - that also the data type reference search and friends use

**Comment by roblourens** [comment]
That's interesting, it would work for the specific scenario we have in mind.

So if we wanted to expand it in the future as a non-breaking change would we pass `(location: Location, someLargerObject: SearchMatch)`?

**Comment by jrieken** [comment]
With appending arguments we have seen trouble when extension call their own commands with extra argument. So, maybe better an object literal like `{ location: vscode.Location }` and then that literal can become a well-known interface in the future (with the restriction of having the location-property)

**Comment by roblourens** [comment]
@digeff just having a Location will be enough for your use-case, right? If so let's do this.

**Comment by digeff** [comment]
@roblourens I can implement a first iteration of the extension with the location.
Is it okay if I send both the "start" location and "end" location given that we have a range of text [User might want to set breakpoints at the start of the match or at the end]?

{ startLocation: vscode.Location, endLocation: vscode.Location }

Just to confirm, I'd be keeping the existing structure that a Folder has many File matches, and a File match has many individual Matches.

**Comment by roblourens** [comment]
Oh yeah, Folder and File contexts... We could say that the Folder and File levels just get a context with an array of locations? I'm not sure about that but it would get the job done.

**Comment by osortega** [comment]
This is already being tracked by https://github.com/microsoft/vscode/issues/228353
Closing this one

/duplicate

**Comment by starball5** [comment]
> already tracked by

a ticket that was created almost 4 years _after_ this one?
