### ISSUE TITLE
[Linux] VSCode does not follow system regulated font rendering settings

### ISSUE THREAD

**Issue by huypn12** [microsoft/vscode#107968]
OS: OpenSUSE Tumbleweed, updated 02 Okt, 2020
VSCode: 1.49.2

Suddenly with the last update of VSCode, I noticed that VSCode does not follow my system font rendering settings. Specifically speaking, somehow VSCode decides to disable font hinting (hint none) rather than using the system-wide regulated slight hinting. I capture the image from Konsole and VSCode to compare; if one zoom in, one can see that VSCode produce "blurrer font" than Konsole, which follows the system settings.

System font settings:
Antialiasing: true
Autohinting: false
Hinting: hintslight
RGB mode: rgb
LCD: lcddefault

![grafik](https://user-images.githubusercontent.com/2792821/94922365-5d428200-04ba-11eb-9b84-a0b2c7a58e0f.png)

**Comment by alexdima** [comment]
VS Code is built with Electron, which is built with Chromium. All font rendering in the editor area is delegated to Chromium. I believe this is an upstream issue with Chromium, can you please test how this font renders in Chromium?

**Comment by huypn12** [comment]
That is right. Chromium does not follow system font settings. It uses the system default font, but forces no hinting on rendering.
![image](https://user-images.githubusercontent.com/2792821/95112460-406bb000-0741-11eb-8af5-187998594258.png)

**Comment by alexdima** [comment]
Please create an issue or find an existing one at the Chromium project and link to it here -- https://bugs.chromium.org/p/chromium/issues/list

**Comment by huypn12** [comment]
I dont have other operating system here to test (to be sure it is not due to Suse's build system). Can someone with Ubuntu or Debian confirm this error?

**Comment by huypn12** [comment]
I dont have other operating system here to test (to be sure it is not due to Suse's build system). Can someone with Ubuntu or Debian confirm this error?

**Comment by VitVS** [comment]
> Can someone with Ubuntu or Debian confirm this error?
Yes, it looks very bad, developers, please return as it was in 1.48.2

VSCode 1.48.2
![1 48 2](https://user-images.githubusercontent.com/30373237/95197817-dc99c380-07e2-11eb-981f-2583777ccda3.png)

VSCode 1.49.3
![1 49 3](https://user-images.githubusercontent.com/30373237/95197830-e15e7780-07e2-11eb-93c3-f493112eaf63.png)

**Comment by deepak1556** [comment]
Can you check if the issue happens with our exploration builds

[Snap](https://az764295.vo.msecnd.net/exploration/53c0ab95bb770a8f3f869e81bb9da200708e6700/code-exploration-1600880002.snap)
[Deb](https://az764295.vo.msecnd.net/exploration/53c0ab95bb770a8f3f869e81bb9da200708e6700/code-exploration_1.50.0-1600879342_amd64.deb)
[Rpm](https://az764295.vo.msecnd.net/exploration/53c0ab95bb770a8f3f869e81bb9da200708e6700/code-exploration-1.50.0-1600879413.el7.x86_64.rpm)
[Unsigned Archive](https://az764295.vo.msecnd.net/exploration/53c0ab95bb770a8f3f869e81bb9da200708e6700/code-exploration-x64-1600879613.tar.gz)

**Comment by VitVS** [comment]
> Can you check if the issue happens with our exploration builds

I tried to install the deb package, unfortunately the problem persists. 
Maybe this will help you - I changed the environment variable in /etc/environment
FREETYPE_PROPERTIES="truetype:interpreter-version=35"

**Comment by deepak1556** [comment]
thanks for testing, can also confirm if this is an issue with chromium browser on your setup by loading https://vscode-web-test-playground.azurewebsites.net/?enter=true

**Comment by deepak1556** [comment]
Tested on Ubuntu 20.04 with following editor setting, unable to repro

```
{
    "editor.fontFamily": "'Arial', 'monospace'"
}
```

![Screenshot from 2020-10-08 16-09-49](https://user-images.githubusercontent.com/964386/95522887-27057680-0982-11eb-8cd0-337b2805c7fd.png)

**Comment by VitaliyVstyle** [comment]
> can also confirm if this is an issue with chromium browser on your setup by loading

I don't use the chromium browser, but I installed it temporarily, it looks like the problem is really in chromium

**chromium**
![chromium](https://user-images.githubusercontent.com/23429859/95523576-a7a29200-09d7-11eb-8f0e-8920813a4dc4.png)

**firefox**
![firefox](https://user-images.githubusercontent.com/23429859/95523601-b6894480-09d7-11eb-99e5-332145037b7d.png)

**Comment by VitVS** [comment]
> can also confirm if this is an issue with chromium browser on your setup by loading

I don't use the chromium browser, but I installed it temporarily, it looks like the problem is really in chromium

**chromium**
![chromium](https://user-images.githubusercontent.com/30373237/95524222-74f99900-09d9-11eb-9d1c-d861189c0644.png)

**firefox**
![firefox](https://user-images.githubusercontent.com/30373237/95524227-76c35c80-09d9-11eb-80cb-c34f984a28fb.png)

**Comment by VitVS** [comment]
> Tested on Ubuntu 20.04 with following editor setting, unable to repro

Compared to my VSCode 1.48.2 screenshot this is not the same

**Comment by deepak1556** [comment]
Can you file a bug in chromium https://bugs.chromium.org/p/chromium/issues/list and attach the bug link here. Thanks!

**Comment by VitVS** [comment]
As it turned out, this chromium bug is related to the scale factor of the device. I added the command line option --force-device-scale-factor=1 and now everything is fine.

![1 50 0](https://user-images.githubusercontent.com/30373237/95583731-3b5e7780-0a45-11eb-8b92-af6a931e298b.png)

![chromium](https://user-images.githubusercontent.com/30373237/95583735-3ef1fe80-0a45-11eb-9f6b-0a0383bb6cdd.png)

**Comment by deepak1556** [comment]
Nice find, merging this to https://github.com/microsoft/vscode/issues/108123
