### ISSUE TITLE
Snippets doesn't pass to next parameter

### ISSUE THREAD

**Issue by RicaBenhossi** [microsoft/vscode#107932]
`Issue` Type: <b>Bug</b>

In java for exemple, when I do fori it gives me the structure bellow, with parameters selected to I change. 

`for (int i = 0; i < alunos.length; i++) {
            
        }`

But I want to change the initial value of 'i' and that's the problem:  
If I press TAB, it indents the whole structure.
if I press enter, it breaks the line and took off var type.
If I press space it inserts a space in the int spot.

How can pass over the parameters to change only the info I want?

VS Code version: Code - Insiders 1.50.0-insider (228973889bc0e352f7cd11cc14755893f8d81864, 2020-10-01T05:29:38.355Z)
OS version: Linux x64 5.4.0-48-generic
Remote OS version: Linux x64 5.4.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2372)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|7.67GB (1.55GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id beb7cee1-d29d-4ea7-b7e1-fbc2ed9fcea7|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pantheon|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pantheon|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Java 12|
|OS|Linux x64 5.4.0-48-generic|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2372)|
|Memory (System)|7.67GB (1.55GB free)|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
delphi-keybindings|ale|9.2.0
project-manager|ale|11.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-firefox-debug|fir|2.9.1
remote-containers|ms-|0.144.0
remote-ssh-edit-nightly|ms-|2020.9.42660
remote-ssh-nightly|ms-|2020.9.42660
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.11
code-settings-sync|Sha|3.4.3
open-in-browser|tec|2.0.0
vscode-icons|vsc|11.0.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
Bookmarks|ale|11.3.1
project-manager|ale|11.3.0
read-only-indicator|ale|3.4.0
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.37.0
git-extension-pack|don|0.1.3
githistory|don|0.6.10
xml|Dot|2.5.1
gitlens|eam|10.2.2
todo-tree|Gru|0.0.181
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
resourcemonitor|mut|1.0.7
embrace|myc|1.0.0
java|red|0.68.0
vscode-community-server-connector|red|0.23.7
vscode-rsp-ui|red|0.23.4
vscode-xml|red|0.13.0
markdown-preview-enhanced|shd|0.5.13
snipsnap-vscode|sni|1.1.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-wakatime|Wak|4.0.8
change-case|wma|1.0.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Yeah, `tab` is the right key to go through snippet placeholders. Can you share the snippet here?

**Comment by RicaBenhossi** [comment]
This is it

"fori": {
		"prefix": "fori",
		"body": [
			"for (${1:int} ${2:i} = ${3:0}; ${2:i} < ${4:max}; ${2:i}++) {",
			"\t$0",
			"}"
		],
		"description": "Indexed for loop"
	}

It's is a snippet from RedHat Java Language. I've tried to copy it to user snippets and got the same result.

**Comment by jrieken** [comment]
![Oct-02-2020 12-31-03](https://user-images.githubusercontent.com/1794099/94914393-3df02880-04ab-11eb-8f75-409b5ede9f76.gif)

Working for me. Any custom keybinding configured? Esp for the `jumpToNextSnippetPlaceholder` command?

**Comment by RicaBenhossi** [comment]
This is it

"fori": {
		"prefix": "fori",
		"body": [
			"for (${1:int} ${2:i} = ${3:0}; ${2:i} < ${4:max}; ${2:i}++) {",
			"\t$0",
			"}"
		],
		"description": "Indexed for loop"
	}

It's is a snippet from RedHat Java Language. I've tried to copy it to user snippets and got the same result. The odd is that if I type something (like int which is the default) and hit `tab`, it goes to next parameter. If I hit `tab` again, it indent the code.

**Comment by RicaBenhossi** [comment]
> Any custom keybinding configured?
You found it... I had a /n very old custom keybinding on `tab` key. That was the conflict...

Thank you @jrieken for helping. And sorry about the silly question 😶
