### ISSUE TITLE
Terminal process "bin/bash" failed to launch

### ISSUE THREAD

**Issue by erythana** [microsoft/vscode#107990]
Issue Type: <b>Bug</b>

Hello,
i have troubles when debugging an extension. Whenever i debug the extension i get the error
"The terminal process "/bin/bash '-c', 'npm run watch'" failed to launch (exit code: 127)."
When i run "npm run watch" on my project directory i get "
[21:22:25] Starting compilation in watch mode...
[21:22:27] Found 0 errors. Watching for file changes.
"
I think this started with one of the two last VSCode Updates. I run Manjaro so i installed it manually extracting the package to
 "lrwxrwxrwx 1 root root 30 25. Jun 22:07 /usr/bin/code -> /usr/local/bin/VSCode/bin/code"

This is the error line from the Developer Console, but that seems to just be the notification:
"The terminal process "/bin/bash '-c', 'npm run watch'" failed to launch (exit code: 127).
onDidChangeNotification @ notificationsAlerts.ts:36
"

Appreciate any help as i don't know what causes this. It also seems that my changes in my extension don't get compiled into the debug session of VSCode (though it opens just fine and my extension is there as it used to be).

Thanks

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:23:33.049Z)
OS version: Linux x64 5.8.11-1-MANJARO

**Comment by erythana** [comment]
Just updated Code to 1.49.2, still the same issue _- sorry for not doing that before_

**Comment by erythana** [comment]
After running "code --log trace" it doesn't happen anymore?!

**Comment by connor4312** [comment]
Where do you have npm installed? Is it being pulled from `nvm` or set in your .bashrc file?

**Comment by erythana** [comment]
I just fixed it in that second. I've set it in the .bashrc file. Now i additionally added it to my X environment variables, described here: https://userbase.kde.org/Session_Environment_Variables, and it works (after a restart of X/Computer).
I really should get into Rubberduck-Debugging. I basically followed my own trail (even though i tried it for hours before).

Thank you for your help, though!

**Comment by connor4312** [comment]
no worries, I figured that may have been what was happening :)
