### ISSUE TITLE
Extension dev/debug: using vscode.workspace.findFiles

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#10793]
When I run extension in debug mode `vscode.workspace.rootPath` is undefined and so I can not test for example `vscode.workspace.findFiles`, it is possible do something about it?

**Comment by sandy081** [comment]
@whitecolor Can you try opening a folder in the extension that might set the workspace and try `vscode.workspace.findFiles`?

**Comment by whitecolor** [comment]
.Yes I think it is ok if I use excecuteCommand `openFolder` first. so probably can be closed
