### ISSUE TITLE
Error while installing the c/c++ extension in vscode

### ISSUE THREAD

**Issue by Vinayak-WEB-DEV** [microsoft/vscode#107956]
**I have just installed mingw and now I want a IntelliSense of c/c++ provided by microsoft on vscode**

First it starts installing some things and after sometime I am getting this error

`Error - 1:04:42 PM] Connection to server got closed. Server will not be restarted.`

_Is there any solution for this thing_

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
