### ISSUE TITLE
Extension host terminated unexpectedly  (memory allocation failure)

### ISSUE THREAD

**Issue by TD-er** [microsoft/vscode#107950]
- VSCode Version: 1.49.2
- OS Version: Windows 10 x64  10.0.19041

Steps to Reproduce:

No clear steps to reproduce. I do use PlatformIO constantly, which every now and then (quite often) just no longer responds and sometimes VScode is showing a notification telling me the extension host has stopped.

![image](https://user-images.githubusercontent.com/3751318/94446280-b5bb0c00-01a8-11eb-8896-5942d501fce4.png)

Does this issue occur when all extensions are disabled?: Yes/No
Not tested as I can't work in VScode without PlatformIO, but have disabled some of the other extensions, which doesn't seem to make a difference.

For completeness, these are the installed extensions:
![image](https://user-images.githubusercontent.com/3751318/94446375-d84d2500-01a8-11eb-95ca-08de999a23fc.png)

N.B. the logs suggest memory allocation issues, but that's probably some configured limit or some internal 32 bit limit as my system does have lots and lots of free memory right now. (currently only 13GB in use of the 96GB)

### Logs

Last logs in the "console tab" of the inspect window (after pressing "Open Developer Tools":

localProcessExtensionHost.ts:252:

```
<--- Last few GCs --->

[3360:0000031700000000]  3034793 ms: Scavenge 3797.4 (3965.5) -> 3791.5 (3966.5) MB, 4.8 / 0.0 ms  (average mu = 0.830, current mu = 0.671) allocation failure 
[3360:0000031700000000]  3034832 ms: Scavenge 3798.4 (3966.5) -> 3792.6 (3966.7) MB, 18.8 / 0.0 ms  (average mu = 0.830, current mu = 0.671) allocation failure 
[3360:0000031700000000]  3034875 ms: Scavenge 3799.0 (3966.7) -> 3793.5 (3966.7) MB, 24.0 / 0.0 ms  (average mu = 0.830, current mu = 0.671) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory
 1: 00007FF6C0686DAA VR_GetStringForHmdError+219210
 2: 00007FF6BFC143B6 node::Buffer::New+43430
 3: 00007FF6BFC14423 node::Buffer::New+43539
 4: 00007FF6BE71DFF8 v8::internal::Version::GetVersion+792
 5: 00007FF6BE71DFA1 v8::internal::Version::GetVersion+705
 6: 00007FF6BE8A9233 v8::Unlocker::~Unlocker+254403
 7: 00007FF6BE8D2351 v8::Unlocker::~Unlocker+422625
 8: 00007FF6BE8CF1F9 v8::Unlocker::~Unlocker+409993
 9: 00007FF6BE8A942C v8::Unlocker::~Unlocker+254908
10: 00007FF6BE8A6988 v8::Unlocker::~Unlocker+243992
11: 00007FF6BE8A49DD v8::Unlocker::~Unlocker+235885
12: 00007FF6BE8AFDA6 v8::Unlocker::~Unlocker+281910
13: 00007FF6BE8AFE8D v8::Unlocker::~Unlocker+282141
14: 00007FF6BE885212 v8::Unlocker::~Unlocker+106914
15: 00007FF6BEBA0AB9 v8::internal::TickSample::print+352969
16: 00007FF6BF0CAB9C v8_inspector::V8StackTraceId::ToString+2982396
17: 0000031700525C7E 
```

abstractExtensionService.ts:166

```
  ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.github-authentication, ms-vscode.cpptools, vscode.debug-auto-launch, vscode.emmet, vscode.git, vscode.merge-conflict, vscode.search-result, alefragnani.Bookmarks, Atishay-Jain.All-Autocomplete, CoenraadS.bracket-pair-colorizer-2, eamodio.gitlens, LaurentTreguier.uncrustify, nicollasr.vscode-streamdeck, vscode.github, platformio.platformio-ide, vscode.configuration-editing, vscode.extension-editing, vscode.json-language-features, ms-vscode.js-debug, vscode.npm, vscode.python, ms-python.python, vscode.grunt, vscode.gulp, vscode.jake, vscode.typescript-language-features
```

webviewElement.ts:152

```
[Embedded Page] WebSocket connection to 'ws://127.0.0.1:8010/wsrpc' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/semver-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/xterm.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/xterm-addon-unicode11.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/xterm-addon-search.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/windowsTerminal.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/terminal.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/eventEmitter2.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/windowsPtyAgent.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/utils.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/index.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/main.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/ExperimentationService.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/TasApiFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/FilteredFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/BaseFeatureProvider.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/AxiosHttpClient.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/ExperimentationServiceAutoPolling.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/ExperimentationServiceBase.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/MemoryKeyValueStorage.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/PollingService.js.map: 
29webviewElement.ts:152 [Embedded Page] WebSocket connection to 'ws://127.0.0.1:8010/wsrpc' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

**Comment by alexdima** [comment]
Thank you for the detailed report. From looking at the logs, I can confirm that the extension host crashes with an Out-Of-Memory error. I believe nodejs processes are normally limited to 4GB of memory, and the extension host crashes when it reaches that, even when using 64 bit VS Code. There are some flags to increase the memory limit, but I suggest that you please report to `platform.io`, since it appears that they have a memory leak in their extension. 

Here are the extensions that were executing when the extension host crashed:

- vscode.microsoft-authentication
- vscode.github-authentication
- ms-vscode.cpptools
- vscode.debug-auto-launch
- vscode.emmet
- vscode.git
- vscode.merge-conflict
- vscode.search-result
- alefragnani.Bookmarks
- Atishay-Jain.All-Autocomplete
- CoenraadS.bracket-pair-colorizer-2
- eamodio.gitlens
- LaurentTreguier.uncrustify
- nicollasr.vscode-streamdeck
- vscode.github
- platformio.platformio-ide
- vscode.configuration-editing
- vscode.extension-editing
- vscode.json-language-features
- ms-vscode.js-debug
- vscode.npm
- vscode.python
- ms-python.python
- vscode.grunt
- vscode.gulp
- vscode.jake
- vscode.typescript-language-features

You can attempt to disable of them unless you really really need them for a while and check if the crash still occurs. As it is right now, all of these extensions get loaded together in the extension host process and any one of the extensions can cause an Out-Of-Memory crash by simply allocating a lot or having memory leaks.

**Comment by RReverser** [comment]
I've started having this as well, and I already tried disabling any suspicious extensions, but nothing helps.

**Comment by RReverser** [comment]
Here's what I get in the memory profile, looks like vscode-oniguruma (built-in) is the only extension holding anything remotely large:
![image](https://user-images.githubusercontent.com/557590/99415779-11279180-28f0-11eb-810d-668a37e4e919.png)

**Comment by alexdima** [comment]
@RReverser It looks to me that you have created a memory snapshot of the renderer process. Is the renderer process or the extension host process crashing with OOM for you? Do you have reproducible steps?

**Comment by RReverser** [comment]
Hmm, I didn't realise DevTools / profiler were targeting only the renderer process by default. I'll try to target the extension host tomorrow.

For me, it reproducibly crashed the whole day ~30 sec after opening VSCode, so eventually I had to give up and try to do some work without extensions, but I wouldn't exactly call it "reproducible steps", no :(

**Comment by RReverser** [comment]
In general, between this and earlier issues with CMake extension crashing VSCode extension host a ~month ago, I really wish VSCode made extensions isolated from each other and not let them crash the whole process...

**Comment by RReverser** [comment]
Hmm how do I even target extensions host? It's not a Worker / target available from DevTools. This issue makes VSCode pretty much unusable :(

**Comment by RReverser** [comment]
Ughhh so in the end I had to disable all extensions (turns out, I've got lots of them over years) and then manually go through them one by one to re-enable.

In the end, turns out it was GitLens - the one I suspected the least...

While this should be now reported to GitLens as their own issue, I wonder if VSCode could make this process less painful. What do you think about the isolation idea above? If not, is there any way VSCode could detect which extension causes the crash and auto-disable it?

**Comment by RReverser** [comment]
Nevermind, I think it's still a general VSCode issue, it just takes longer to OOM now...

**Comment by RReverser** [comment]
Can you reopen this issue for tracking please?

**Comment by alexdima** [comment]
@RReverser I'm sorry I didn't get a chance to write it earlier (before your manual bisect). In our latest insiders, we have a new command `F1 > Help: Start Extension Bisect`. This will disable half of the installed extensions, then restart vscode and ask if the problem reproduces or not. Based on your answer, the problematic extension is narrowed down to either the half that was disabled or the half that was enabled. The process repeats until the problematic extension is singled out.

Regarding the current architecture, we currently load all extensions together in a single nodejs process. A nodejs OOM crash does not indicate which JS code path has been responsible for the most memory allocation, so we cannot detect that automatically from the crash stack trace and we cannot identify which extension is the culprit. Basically our runtime does not allow us to easily identify, in a shared context, which extension is causing an OOM crash.

Regarding having one nodejs process per extension, or grouping of extensions in processes. We already have a tracking item for having multiple extension hosts (https://github.com/microsoft/vscode/issues/75627) so I suggest we continue tracking there. Also, please keep in mind that would have other consequences. There are people who have tens of extensions installed and their laptops might suffer if we start 30 or 40 node processes for each extension independently. We would also duplicate the text buffers and other workspace state that is available in our API 30 or 40 times in memory. So while an extension host per extension might be feasible on powerful desktop machines, it is not a golden hammer to the problem of bugs in extensions.

**Comment by RReverser** [comment]
> I'm sorry I didn't get a chance to write it earlier (before your manual bisect). In our latest insiders, we have a new command F1 > Help: Start Extension Bisect. 

Oh wow, thanks for this. Although at this point, given that issue gets delayed when I disable extensions, I start suspecting that it's a cumulative effect and an actual OOM, rather than a single extension. I'll give it a try though.

> There are people who have tens of extensions installed and their laptops might suffer

Heh, that's me. Although, I imagined that rather than separate processes, we could use something more lightweight like Workers, but that still doesn't alleviate the memory concerns of course.

**Comment by TD-er** [comment]
For running out of memory performing a bisect on the running plugins is not the best way as simply disabling half of the extentions may simply appear to solve the issue.
For example if ext. A and B together cause this OOM, then disabling either one of them may appear to solve the issue.

In my case it appears intellisense along with PlatformIO do seem to cause OOM issues.
For me it helped to convert lots of .ino files in my project to .h/.cpp files.
However this lead to the next issue (not related to VScode), where all these extra .cpp files compiled into lots of .cpp.o files which made the linker command exceed the max command line length.

Isn't it possible to increase the max. memory size for the processes?
On my PC I do have enough memory, so limiting it to roughly 4 GByte is a bit silly, unless it is some 32 bit process of course.

**Comment by alexdima** [comment]
You have a good point. We do have a command line flag `--max-memory`, but that currently is only for the renderer processes. We do not use this value for the extension host process, so there is no way to indicate to v8 that it can consume more memory than it thinks by default. I've created https://github.com/microsoft/vscode/issues/110885 for this.
