### ISSUE TITLE
Feature: SSL Settings

### ISSUE THREAD

**Issue by pecigonzalo** [Microsoft/vscode#108]
My company uses a proxy with SSL inspection, i cant find a way to set allowed trusted certificates.

Cheers

**Comment by mwootendev** [comment]
+1

I'm having the same issue.
npm's .npmrc and Atom apm's .apmrc files allow you to set a "strict-ssl" value to false. While I realize this is unsecure, it seems to be the only way to use these tools through our proxy.

**Comment by simonech** [comment]
Indeed, I've the same problem. How can I specify strict-ssl?

**Comment by ywmail** [comment]
same problem here.

**Comment by maritz** [comment]
Starting Code with "NODE_TLS_REJECT_UNAUTHORIZED=0" seems to "fix" some issues and I actually get a list of extensions, but I still cannot install the extensions themselves. I get timeouts in the dev console after a while and that's it.

**Comment by simonech** [comment]
@maritz What do you mean by "Starting Code with"?
You put that into the settings?

**Comment by maritz** [comment]
__Disclmaimer__: This is not safe! (as is strict-ssl: false)

That's an environment variable. So in linux when starting vscode from command line you'd do this:

    NODE_TLS_REJECT_UNAUTHORIZED=0 ./Code

**Comment by joaomoreno** [comment]
Duplicate of #155

We will only support the `http.proxyStrictSSL`, not adding certificates to the trusted list.
