### ISSUE TITLE
automatically remember indentation settings

### ISSUE THREAD

**Issue by xrfang** [microsoft/vscode#108019]
Issue Type: <b>Feature Request</b>

I am editing Go source code, however I think this feature is related to vscode itself...

When I choose intentation use tab, size=4, it took effect immediately, but the setting is not remembered. When I open vscode again, it reverts indentation to 8-space.

I have checked preferece: workspace setting or user setting, didn't find a clue where to set this GLOBALLY.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:56:11.027Z)
OS version: Linux x64 5.4.0-47-generic

**Comment by alexdima** [comment]
Does this reproduce when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)

**Comment by xrfang** [comment]
@alexdima this problem persists even with extesions disabled.

**Comment by xrfang** [comment]
@alexdima a difference with your screenshot is that even with extensions disabled, they are still listed in the extensions panel, however all of them are grayed, except the language extesion.  I think the gray olor means they are indeed disabled, right?

**Comment by alexdima** [comment]
@xrfang Thanks for trying that out, sometimes extensions use vscode API to change the indentation settings. Other than through API, the indentation settings of VS Code are controlled by the following VS Code settings:
`editor.tabSize`, `editor.insertSpaces`, `editor.detectIndentation`. How did you configure these settings?

**Comment by xrfang** [comment]
@alexdima settings are:

**Comment by alexdima** [comment]
I see, you wish that the status bar persists the settings. That is not the intent of the status bar. The status bar is for "on-the-fly" changing of the settings. One of the reasons is that these settings can be quite complicated to do automatically, and we already have UI to change the settings: e.g.:

```
"editor.insertSpaces": false,
"[cpp]": { "editor.insertSpaces": true },
"[json]": { "editor.insertSpaces": true },
```

This is consistent with other entries in the status bar. Changing the encoding of a file does not configure the default VS Code encoding, changing the language mode of a file does not configure the default language mode, etc.

**Comment by xrfang** [comment]
@alexdima I would say it is probably a bug. Because I have done the following:

1) uncheck "editor.insertSpace", return to the edirot, open the file it still indent the code using tab width 8.

2) I then added the following into settings.json:

    "[go]": {
        "editor.insertSpaces": false,
        "editor.tabSize": 4,
        "editor.defaultFormatter": "golang.Go"
    },

Then return to the editor, open that file again, nothing changes.  Here is a portion of the source code:

`
LINE1:	tx.MustExec(`CREATE TRIGGER IF NOT EXISTS bomupd AFTER UPDATE ON "bom"
LINE2:        FOR EACH ROW BEGIN UPDATE "bom" SET updated=CURRENT_TIMESTAMP WHERE
LINE3:        id=OLD.id; END`)
`

The space at start of LINE1 is a TAB, I want its width to be 4, but it insist to be 8, the space at start of LINE2 and LINE3 are internal part of the multi-line string, which is irrelevant.

Note that according to gofmt, indentation in go source code is always TAB, what I want is vscode to use my preset tab width of 4.

Now, it is not the problem of save on-the-fly changes of the status bar.  But the settings I change in the Settings tab does not take effect!

**Comment by xrfang** [comment]
@alexdima  also, I suggest the setting **editor.insertSpace** should be clarified: does it mean insert space whenever user press TAB, or it **only** applies to start of line (indentation)?  Thanks
