### ISSUE TITLE
Custom editors: potentially unsafe file operation resource use

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108092]
Custom editors listen to file operations (move) here:

https://github.com/microsoft/vscode/blob/fec75ce9120a055009a0dbd33ff3a36e62d925be/src/vs/workbench/contrib/customEditor/browser/customEditors.ts#L80-L80

I have not fully checked how the `resource` property is used in `handleMovedFileInOpenedFileEditors` but feel it may hit path-casing issues on macOS and Windows if the path casing differs. For example, when you compare with `editor.resource` you always compare with the canonical form of the `URI` which may be different from the one of the file operation event.

We have `IURIIdentitiyService` for comparing with path casing in mind, or use the `IFileChangeEvent.contains` method which internally uses the `IURIIdentityService` too.

I recently changed to this form for my file event handler in file models. Instead of iterating over all file changes and getting the model for a `resource`, I now loop over my models and use the `contains` method:

https://github.com/microsoft/vscode/blob/7f4737616fc5b2d42a681ad09427ca1189c6cadd/src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts#L101-L114

**Comment by mjbvz** [comment]
I looked over the code and updated it to check against the canonical uri. I think everything is ok for how we are using the uris but let me know if you notice any bugs related to file cases
