### ISSUE TITLE
Doesn't syncing because of error in settings.json

### ISSUE THREAD

**Issue by FredUA** [microsoft/vscode#108033]
Issue Type: <b>Bug</b>

I have the next snippet in my json:
"csscomb.preset": {
        "remove-empty-rulesets": true,
        "always-semicolon": true,
        "color-case": "lower",
        "block-indent": "	",
        "eof-newline": true,
        // "quotes": "double",
        "sort-order-fallback": "abc",
        "sort-order": [
            ["$extend"],
            ["$include"],
            ["$variable"]
        ],
        "space-after-colon": " ",
        "space-before-combinator": " ",
        "space-after-combinator": " ",
        "space-between-declarations": "\n",
        "space-before-opening-brace": " ",
        "space-after-opening-brace": "\n",
        // "space-after-closing-brace": "",
        "space-after-selector-delimiter": "\n",
        "space-before-selector-delimiter": "",
        "space-before-closing-brace": "\n",
        // "strip-spaces": true,
        "tab-size": "2",
        "unitless-zero": true,
        // "vendor-prefix-align": true,
        "lines-between-rulesets": 1,
    },

In field "block-indent" I have tab sign there ("	"). But it says there is an issue and the system can not synchronize my preferences. How can I fix this? 

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:26:09.944Z)
OS version: Linux x64 5.4.0-48-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2689 0 @ 2.60GHz (16 x 1546)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (0.76GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id e94f603e-18c6-4c89-b618-3b9a34a4ed35|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
open-html-in-browser|cod|0.1.21
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.1
vscode-diff|fab|1.4.0
auto-rename-tag|for|0.1.4
todo-tree|Gru|0.0.181
path-autocomplete|ion|1.15.0
dotenv|mik|1.0.1
vscode-csscomb|mrm|5.3.2
vetur|oct|0.28.0
indent-rainbow|ode|7.4.0
require-cartridge-resolve|pik|1.8.1
material-icon-theme|PKi|4.3.0
synthwave-vscode|Rob|0.1.8
code-settings-sync|Sha|3.4.3
prophet|Sqr|1.3.28
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.9.1
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Do you see any problems (squiggles) when you open your settings.json file? 
It would be great if you can take a screenshot and provide it ?
