### ISSUE TITLE
PHP Intellisense parameter skip (Bug)

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#108049]
### **The bug because seperate word is repeated in seperateChar | And the problem solved when I rename seperate to separate for example**
![2](https://user-images.githubusercontent.com/17777237/95002311-c0273c80-05d2-11eb-8999-4d69dccdb469.gif)

- VSCode Version: 1.49.3
- OS Version: Windows 10 Pro version 2004 build 19041.265

Steps to Reproduce:

1. new laravel project with documented method
2. Intellisense parameter skip (Bug)

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
I don't know who owns this, is that controlled by us or the extension?

**Comment by jrieken** [comment]
<img width="556" alt="Screenshot 2020-10-06 at 09 20 58" src="https://user-images.githubusercontent.com/1794099/95170768-413e2980-07b5-11eb-837a-62970571641a.png">

**Comment by roblourens** [comment]
Which PHP extension are you using @pixieaka? Please file an issue on that extension's repo

**Comment by pixieaka** [comment]
@roblourens @jrieken Tracking in this issue https://github.com/bmewburn/vscode-intelephense/issues/455

**Comment by pixieaka** [comment]
@roblourens This is from vscode https://github.com/microsoft/vscode/issues/56337
