### ISSUE TITLE
Can't run npm in visual stuido integrated terminal (PATH problem)

### ISSUE THREAD

**Issue by kinwolfqc** [microsoft/vscode#108078]
Issue Type: <b>Bug</b>
I have a weird bug here.  If I open a project  by using windows explorer to browse to the project folder and selecting "Open in VSCode" on it, the path variable is missing entries!  In this case the path to nodejs and npm is nowhere to be seen.  

BUT

If I simply open vscode from the start menu, npm works fine in the terminal and indeed, the path variable contains all the paths it's supposed to contain.

Why would $env:PATH be different depending on how you open VSCode??? 

1. Select the folder where your code is, right click on it and select "Open in  vscode"
2. Open a terminal and run npm

Addiotional Info:  I haven't rebooted since installing nodejs on my computer, but every other software(like windows terminal) has the correct $env:PATH

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (11.63GB free)|
|Process Argv|D:\Users\kinwo\OneDrive\Documents\Code\Python\LearnSvelte\loan --crash-reporter-id dc1de7b0-70d5-457f-ae47-dba8d11c4448|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.3.0
atlascode|atl|2.8.2
django|big|1.0.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.37.1
vscode-eslint|dba|2.1.8
auto-rename-tag|for|0.1.4
go|gol|0.17.2
terraform|has|2.2.3
gitignore|mic|1.0.1
vscode-azureappservice|ms-|0.19.0
vscode-docker|ms-|1.6.0
python|ms-|2020.9.112786
vscode-pylance|ms-|2020.9.8
remote-wsl|ms-|0.44.5
azure-account|ms-|0.9.3
powershell|ms-|2020.6.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.3.0
vscode-yaml|red|0.11.1
svelte-vscode|sve|102.1.1
markdown-all-in-one|yzh|3.3.0

(1 theme extensions excluded)

</details>

**Comment by nougator** [comment]
It isn't vscode's fault, it's more like a windows bug.

**Comment by kinwolfqc** [comment]
> 
> 
> It isn't vscode's fault, it's more like a windows bug.

But the problem is only in vscode terminal...

**Comment by nougator** [comment]
Make sure vscode use the right terminal.

**Comment by kinwolfqc** [comment]
The right terminal?  Is there a wrong one? :-/  
Anyway, if this happens to anyone else, a reboot is what it took for vscode to see the path correctly.  Windows terminal, powershell 5.1, powershell 7 and cmd shells do not have this problem.  It only happeend with the pwsh terminal in vsCode.
