### ISSUE TITLE
Go to definition not showing 

### ISSUE THREAD

**Issue by DinkarSingh** [microsoft/vscode#108042]
Version: 1.49.2 (system setup)
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:29:41.983Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

I have installed vs code recently but I'm unable to use the Go to definition option on the right click on the function (JavaScript I'm using as language).

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
