### ISSUE TITLE
Completion Items closed unintentionally because of wordPattern

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#108012]
Version: 1.50.0-insider
Commit: 0ecb64a2c8945dd1193967019f0734af539ca9c3
Date: 2020-10-02T11:11:09.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:

1. Execute the following extension sample.
2. Open a file `t.abc`
3. Type `c`
4. Press `Ctrl-Space` to open completion items.
5. Press `o`. Then, completion items become closed. 
6. `console` should be matched,  and completion items should keep opened.

![Oct-03-2020 09-31-19](https://user-images.githubusercontent.com/10665499/94979014-62a3d900-055b-11eb-9783-f5823e91e992.gif)

Extension sample: https://github.com/tamuratak/vscode-extension-samples/tree/06eecff2e41966a29985320b731a6eae721ab3bd/completions-sample

src/extension.ts

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    const provider1 = vscode.languages.registerCompletionItemProvider({ scheme: 'file', language: 'abc' }, {
        provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {
            const consoleCompletion = new vscode.CompletionItem('console');
            // return all completion items as array
            return [
                consoleCompletion,
            ];
        }
    });
    context.subscriptions.push(provider1);
}

```

syntax.json
```json
{
	"wordPattern": "[^\\s`'\"~_!?|$#@%^&*\\-=+;:,.<>(){}[\\]\\\\\\/]{2,}"
}
```

package.json
```json
{
    "name": "completions-sample",
    "displayName": "Completion Item Provider Sample",
    "version": "0.0.2",
    "publisher": "vscode-samples",
    "repository": {
        "type": "git",
        "url": "https://github.com/Microsoft/vscode-extension-samples"
    },
    "bugs": {
        "url": "https://github.com/Microsoft/vscode-extension-samples/issues"
    },
    "contributes": {
        "languages": [
            {
                "id": "abc",
                "extensions": [
                    ".abc"
                ],
                "configuration": "./syntax.json"
            }
        ]
    },
    "engines": {
        "vscode": "^1.32.0"
    },
    "categories": [
        "Other"
    ],
    "activationEvents": [
        "*"
    ],
    "main": "./out/extension.js",
    "scripts": {
        "vscode:prepublish": "npm run compile",
        "compile": "tsc -p ./",
        "lint": "eslint . --ext .ts,.tsx",
        "watch": "tsc -watch -p ./"
    },
    "devDependencies": {
        "@types/node": "^12.12.0",
        "@typescript-eslint/eslint-plugin": "^3.0.2",
        "@typescript-eslint/parser": "^3.0.2",
        "eslint": "^7.1.0",
        "typescript": "^4.0.2",
        "@types/vscode": "^1.32.0"
    }
}

```

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
That's to be expected. You trigger new completions after the first `c` and the sample provider doesn't honour the leading word. The default is to then use the word definition (as provided) which seems to require that a word is at least 2 characters long.

**Comment by jlelong** [comment]
Yet, I do not understand why typing `n` (in the third position) after step 5 brings the completion list back with `console` and highlights `con`. I am a bit confused by 

> and the sample provider doesn't honour the leading word

Could you tell me more about that and how `wordPattern` interferes in this?
