### ISSUE TITLE
Progress bars

### ISSUE THREAD

**Issue by Joseph-I-Jess** [microsoft/vscode#108076]
Issue Type: <b>Feature Request</b>

I would like to request that extension installation have progress bars.  It would be great to have a progress bar on extension installation, even if just based on download sizes.

My slow internet connection speed  makes having progress bars critical for planning ahead.

Thank you  for the awesome editor :)!

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.17763

**Comment by sandy081** [comment]
/duplicate

#93713
