### ISSUE TITLE
Debug: potentially unsafe file events handling

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108091]
Debug is listening to file events:

https://github.com/microsoft/vscode/blob/235bae66cbe96bb3c67e3dc9572077147f8d1061/src/vs/workbench/contrib/debug/browser/debugService.ts#L988-L990

By comparing the `event.resource` with the breakpoints resource, you may potentially get into path-casing issues depending on how your resources are being created for breakpoints.

We have `IURIIdentityService` to compare with path-case in mind or `event.contains` which internally uses this. 

I recently changed to this form for my file event handler in file models. Instead of iterating over all file changes and getting the model for a `resource`, I now loop over my models and use the `contains` method:

https://github.com/microsoft/vscode/blob/7f4737616fc5b2d42a681ad09427ca1189c6cadd/src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts#L101-L114

**Comment by bpasero** [comment]
@isidorn I went ahead and took care of this via https://github.com/microsoft/vscode/commit/bb3aaa780099662751cf9b02be6fe02407af1b00#diff-f9eceda9194def39393e1ba1e19a319c

**Comment by isidorn** [comment]
Thanks Ben for looking into this and fixing it.
