### ISSUE TITLE
Custom prompt when asking to save before existing on macOS Big sur

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode#108099]
See screenshot, Big Sur dims the whole window when showing an alert and it looks like VSCode is locked up or frozen when everything is working fine.

Not sure if this is an Electron thing or not... but there you go

<img width="1549" alt="Screenshot 2020-10-05 at 4 46 52 PM" src="https://user-images.githubusercontent.com/9585787/95058638-5fab1300-072a-11eb-9939-2d2efbc7d45e.png">

**Comment by bpasero** [comment]
@deepak1556 maybe you know, is there a way to get the previous look back for dialogs or is this set in stone?

@jpike88 you are just concerned about the looks right, there is no functionality loss. If Apple decides that this is the way to go for dialogs, then maybe you should report this against Apple?

**Comment by jpike88** [comment]
Yes it's purely looks. I'll report to Apple too

**Comment by deepak1556** [comment]
It comes from the big sur design for NSAlert https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/ check the alerts section, we don't have control over it.

**Comment by joelday** [comment]
Pretty painful for any extensions that needed to display a lot of text in these.
