### ISSUE TITLE
Settings editor accessibility improvements summary

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#108006]
This is a summary of the work we did on settings editor accessibility, mostly compiled from the original issues https://github.com/microsoft/vscode/issues/104318, https://github.com/microsoft/vscode/issues/106897, https://github.com/microsoft/vscode/issues/97567, for easier reading.

Over the past couple iterations, we have been listening to feedback and exploring options for making the settings editor easier to use with a screen reader. Here are some of the issues we've heard:

- The only way to navigate the settings list is by tabbing. Arrow keys, page up/down, or screen reader browse mode don't work.
- The settings list is effectively an infinitely long tab sink. If you tab into it, it's very difficult to tab out of it.
- You can move from the category list into the settings list with no obvious way to get back to the category list.
- When navigating the settings list, you can tab from a setting in one category into a setting in another category with no announcement that you have changed categories.

We decided to address these with a change that makes navigating the settings editor becomes more like navigating a list. A setting row becomes focused, and the settings list can be navigated with the arrow keys. The user can navigate to a setting then tab or press enter to focus its control to edit it.

Some advantages to this approach: 

- The control in the focused row is the only tabbable element in the setting list. In other words, the setting list no longer will add hundreds of tab targets to the page.
- Setting category titles become focused as the user navigates through the list. They will be read by the screen reader so it is obvious that focus has moved from one category to another.
- This interaction model works similarly to all other lists in VS Code, so it should be familiar. The same keybindings for navigating other lists will work for this list.

Another improvement: you can press "escape" when focus is in the settings list to move focus back to the category list, and then press "escape" again to move focus back to the search bar. This solves the issue of having difficulty moving focus out of the settings editor, and emphasizes the hierarchical nature of these 3 main parts.

**Comment by adriatic** [comment]
Terrific addition, @roblourens - I was dreading the moment when some settings simply have to be changed to save my sanity. In particular, I like:

> Another improvement: you can press "escape" when focus is in the settings list to move focus back to the category list, and then press "escape" again to move focus back to the search bar. This solves the issue of having difficulty moving focus out of the settings editor, and emphasizes the hierarchical nature of these 3 main parts.
