### ISSUE TITLE
Typing ~ in terminal results in 4~

### ISSUE THREAD

**Issue by mnunezdm** [microsoft/vscode#108077]
Issue Type: <b>Bug</b>

Hello,

I have a keyboard with spanish layout.

When typing the ~ character (which in my case is Alt Gr + 4) in the terminal 4~ is printed. This only happens when I use the integrated terminal in vscode, and only with the ~, for example with the # which is Alt Gr + 3 does not happen

![error3](https://user-images.githubusercontent.com/10410852/95022286-9162a200-0676-11eb-96d9-d7250639d644.gif)
![error4](https://user-images.githubusercontent.com/10410852/95022288-91fb3880-0676-11eb-996d-afb8836131f2.gif)

For example these examples are using windows terminal & cmd

![noerror](https://user-images.githubusercontent.com/10410852/95022184-e9e56f80-0675-11eb-8e15-9bd18a34ba08.gif)

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.90GB free)|
|Process Argv|--crash-reporter-id f42cf393-2006-41d7-afa1-7a625b63925d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3695)|
|Memory (System)|5.80GB (2.86GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.6.0
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.11
material-icon-theme|PKi|4.3.0
material-theme|zhu|3.9.1
apex-pmd|chu|0.5.2
transformer|dak|1.9.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
json-tools|eri|1.0.2
prettier-vscode|esb|5.7.1
chat|kar|0.35.0
git-graph|mhu|1.26.0
vscode-autoprefixer|mrm|3.0.1
vsliveshare|ms-|1.0.2902
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-xml|red|0.13.0
salesforce-vscode-slds|sal|1.2.1
salesforcedx-vscode|sal|49.12.0
salesforcedx-vscode-apex|sal|49.12.0
salesforcedx-vscode-apex-debugger|sal|49.12.0
salesforcedx-vscode-apex-replay-debugger|sal|49.12.0
salesforcedx-vscode-core|sal|49.12.0
salesforcedx-vscode-lightning|sal|49.12.0
salesforcedx-vscode-lwc|sal|49.12.0
salesforcedx-vscode-visualforce|sal|49.12.0

</details>

**Comment by mnunezdm** [comment]
Apparently, when typing using the Ctrl + Alt + 4 correctly types the ~

Checking the [documentation](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-windows-keybindings). This is my configuration (i have omitted all the other mappings)

```json
{
	"layout": {
		"name": "0000040A",
		"id": "",
		"text": "Spanish"
	},
	"rawMapping": {
		"Digit4": {
			"vkey": "VK_4",
			"value": "4",
			"withShift": "$",
			"withAltGr": "~",
			"withShiftAltGr": ""
		},
	}
}
```

**Comment by Tyriar** [comment]
Can you try toggle escape sequence logging and see what is being sent when you press altgr+4 vs ctrl+alt+4?

https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by mnunezdm** [comment]
**When pressing AltGr + 4**

![image](https://user-images.githubusercontent.com/10410852/98233982-1126a980-1f60-11eb-94c9-622514c22fa8.png)

**When pressing Alt + Control + 4**

![image](https://user-images.githubusercontent.com/10410852/98234009-1edc2f00-1f60-11eb-8252-7d159c52ad69.png)

**Comment by mnunezdm** [comment]
I have just installed Hyper terminal, as it also runs on xterm and has the same issue, do you want me to create this issue in the xterm repository?

**Comment by Tyriar** [comment]
@mnunezdm thanks, the screenshots are very useful 👍

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? Let us know if not.
