### ISSUE TITLE
Killing the terminal in while in an infinite loop crashes vscode.

### ISSUE THREAD

**Issue by Misnad** [microsoft/vscode#108021]
Whenever I have a infinte loop (python3) and I run it. There is no way to stop it. Killing the terminal crashes VScode.
I tried in Ubuntu but no issue. Only the windows version has this problem (AFAIK).

- VSCode Version: 1.49.3
- OS Version: Windows 10, version 2004, os build 19041

Steps to Reproduce:

1. Create an infinite loop
2. Run the code. Then kill the terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
It's actually this one -> https://github.com/microsoft/vscode/issues/108317
