### ISSUE TITLE
"Reopen editor with" in editor title

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#108007]
I thought that action used to be in the editor title overflow menu? Was that not the case?

![image](https://user-images.githubusercontent.com/323878/94976554-3429ed80-04ca-11eb-9d18-55fec1aed00b.png)

It seems like it should be more discoverable. Was thinking this while resolving a merge conflict in a .md notebook which is sort of nonsense.

**Comment by mjbvz** [comment]
We moved it to the context menu on the tab instead. See #101463 for details of the discussion

**Comment by roblourens** [comment]
I don't know why I missed it there, that makes sense
