### ISSUE TITLE
Publish to GitHub fails (or doesn't go what would be expected) if there is already a git repo

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#108001]
Refs: #105025

#### Scenario 1
- Choose Publish to GitHub
- Pick private/public (I chose private)
- Choose the 1 file
- ✔️ Repo gets published and new file gets added in the first commit

#### Scenario 2
- Choose Publish to GitHub
- Pick private/public (I chose private)
- Don't choose the 1 file
- ❌ Repo gets published but the first commit is a `.gitignore` file  excluding the file I unchecked — this was completely unexpected to me, because it didn't suggest anywhere that this would happen and if I just didn't want to publish this file right now, I'd be really confused as to why it would never show up with changes anymore. IMO, `.gitignore` here is quite advanced and was unexpected

#### Scenario 3
- Choose Publish to GitHub
- Pick private/public (I chose private)
- Choose the 1 file
- ✔️ Repo gets published and new file gets added in the first commit

#### Scenario 4
- Choose Publish to GitHub
- Pick private/public (I chose private)
- Don't choose the 1 file
- ❌ Repo gets published but the first commit is a `.gitignore` file  excluding the file I unchecked — again unexpected

#### Scenario 5
- Choose Publish to GitHub
- Pick private/public (I chose private)
- ❌Choose the 1 file — why am I even seeing this file picker? There are no additional files (or uncommitted changes). Even if there were, I'm not sure I should even see those here as I think it should just publish the repo as-is
- ❌Repo gets published, but no commits or files get pushed, and no remote is added to the local repo. Nor do you get the notification at the end of the operation.

#### Scenario 6
- Choose Publish to GitHub
- Pick private/public (I chose private)
- ❌Don't choose the 1 file — again I don't even think you should get this prompt
- ❌ Repo and branch/commits get published but an additional commit gets added with a `.gitignore` file excluding the file I unchecked — again very unexpected, especially as this file is already committed

#### Scenario 7
- Choose Publish to GitHub
- Pick private/public (I chose private)
- ❌Choose both files — If this even should show up, I would expect that only the additional (uncommitted) file show up here and that it will just not stage/commit it
- ✔️ Repo and branch/commits get published, and additional file gets committed ✔️ (but the commit message is "first commit" ❌) 

#### Scenario 8
- Choose Publish to GitHub
- Pick private/public (I chose private)
- ❌Don't choose the additional file — again I don't even think you should get this prompt
- ✔️ Repo and branch/commits get published, and but an additional commit gets added with a `.gitignore` file excluding the file I unchecked and the commit message is "first commit" ❌

Overall, I don't think we should be mucking with `.gitignore` files (unless explicit to the user) and if a repository already exists, I think it should just be pushed as-is, and not attempt to do anything with uncommitted changes

**Comment by joaomoreno** [comment]
Fixed scenarios 2, 4

The others were all duplicates of https://github.com/microsoft/vscode/issues/99447, which is quite old 🤔

**Comment by rzhao271** [comment]
For scenario 2 nothing happens now, no published repo.
For scenario 4 an empty repo gets published, but I don't see the prompt for selecting a file show up.

**Comment by eamodio** [comment]
@rzhao271 Do the other scenarios now work? As #99447 is both old and closed -- so I'm not sure how they are related.

**Comment by rzhao271** [comment]
#99447 makes it so that for scenario 3 the file inclusion dialog doesn't pop up.

I'm unable to get the file inclusion dialog to pop up after the repository has already been initialized
