### ISSUE TITLE
Undo for selection

### ISSUE THREAD

**Issue by csicky** [microsoft/vscode#108098]
It would be very helpful to have a text portion selected, then press Ctrl+Z and have the undo work only for that selection while the rest remains as is.

Reason: it happened many times that I do some change, then go on and work, do a lot more other changes in other places of the file. If I undo to the point I want to get, I loose all other work applied over that point. What I do is either rewrite manually if easy, or go for an older version of the file and copy what I need back. Undo for selection would be so helpful. 

I know this requires very complex data for the undo system and is probably hard to do, but I think it would be very cool and helpful.

**Comment by csicky** [comment]
As an example, I think it would be something like the History Brush tool in Photoshop, but for code.

**Comment by miguelpagano** [comment]
From emacs [documentation](https://www.gnu.org/software/emacs/manual/html_node/emacs/Undo.html):

> When there is an active region, any use of undo performs selective undo: it undoes the most recent change within the region, instead of the entire buffer.

**Comment by csicky** [comment]
This is a bad way of deciding, I don't have time to make marketing for a
feature for your product.
