### ISSUE TITLE
`vsce package` defaults to using wrong package manager

### ISSUE THREAD

**Issue by ntilwalli** [microsoft/vscode#108044]
- VSCE Version: 1.81.0
- OS Version: MacOS 10.15.6

Steps to Reproduce:

1. At command-line run `yo code` and create the default hello world extension (choose npm as package manager, not yarn)
add a publisher property to package.json
2. Install any package in "dependencies" (i.e. `npm install --save html-to-hyperscript`)
3. Run `vsce package`
4. Notice how it uses yarn when I have told it to use npm.  It says...
```
Executing prepublish script 'yarn run vscode:prepublish'...
yarn run v1.22.5
```
In using the wrong package manager it also bundles the package improperly by skipping including dependencies from `node_modules`

The workaround is to always explicitly either use the `--yarn` or `--no-yarn` option when running `vsce package`.  When the package manager is included explicitly, the node_modules dependencies are properly included.

Does this issue occur when all extensions are disabled?: Not applicable, since this is an extensions issue.

**Comment by usernamehw** [comment]
You should probably file this issue at https://github.com/microsoft/vscode-vsce

**Comment by ntilwalli** [comment]
@usernamehw [done](https://github.com/microsoft/vscode-vsce/issues/496) thanks!
