### ISSUE TITLE
Format code keybinding prints a small tilde character in the editor

### ISSUE THREAD

**Issue by fayazara** [microsoft/vscode#108018]
- VSCode Version: 1.49.2
- OS Version: Mac OS Catalina 10.15.6

Steps to Reproduce:

1. Press Ctrl + Shift + F
2. Notice the ~ character getting printed on the editor (Attached a gif below)

Does this issue occur when all extensions are disabled?: Yes

Happens will extension files

## What I have tried so far

1. Tried completely deleting vscode from my mac and reinstalling and yet this happens.
2. Changing the keybinding to some other keys of "Format Document" - Same character is printed

The character is unusually smaller in font-size than other text in my files
![CleanShot 2020-10-03 at 10 10 44](https://user-images.githubusercontent.com/15716057/94983573-a699dc80-0561-11eb-911f-ffb75c3f7f1f.gif)

Anything I can try to debug this further?

**Comment by alexdima** [comment]
@fayazara 
What does VS Code detect when you press the desired key combination? 

![keyboard-input](https://user-images.githubusercontent.com/5047891/80482640-da3e5e00-8954-11ea-9583-0f652b0595a8.gif)

**Comment by fayazara** [comment]
@alexdima, when I pressed ctrl+alt+up, a new keybinding was added in the json file.

<img width="1013" alt="CleanShot 2020-10-09 at 10 11 17@2x" src="https://user-images.githubusercontent.com/15716057/95544125-e5bfa600-0a17-11eb-8c74-8f4bbcbf02f4.png">

**Comment by alexdima** [comment]
@fayazara I have a pre-recorded GIF since I answer so many times the same question. That is why in my gif I have "ctrl+alt+up". But could you please try to input the keybinding you are pressing? (Ctrl + Shift + F)
