### ISSUE TITLE
Empty configuration property should produce an error in package.json

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#108023]
`package.json` of extension repository

```js
"configuration": {
    "properties": {
        "": {
            "type": "boolean",
            "default": false,
            "description": "Wow"
        },
    }
}
```

**Comment by sandy081** [comment]
@aeschli May I know how can this be done through JSON schema?

**Comment by aeschli** [comment]
Yes, you can use `propertyNames` to enforce that property names follow a format: http://json-schema.org/understanding-json-schema/reference/object.html#property-names.

But I think it's also ok to make that check when we read the extension point.t

**Comment by sandy081** [comment]
Thanks @aeschli. 

Warning will be shown when property is empty.
Also gets validated while reading.
