### ISSUE TITLE
not showing the files

### ISSUE THREAD

**Issue by adhyan-jain** [microsoft/vscode#108064]
We have written the needed data into your cl
Issue Type: <b>Performance Issue</b>

When i am opening a folder from visual studio code then it is not showing my files even i have set VS code as default in the files which i want to open.
Also i have reinstalled it but then also the same problem is occuring.
I hope you will do something about the issue.
Thank You

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.85GB free)|
|Process Argv|--crash-reporter-id c8c6f256-a6e3-4902-9308-13bc35e96ec2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    72	  8280	code main
    0	    54	  2568	   window (Issue Reporter)
    0	   122	  4664	   window (Untitled-1 - Visual Studio Code)
    0	    47	  6152	     extensionHost
    0	    64	  4956	   shared-process
    0	     9	  7180	   crashpad-handler
    0	    20	 10512	   utility
    0	    68	 11136	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none
ipboard because it was too large to send. Please paste.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
