### ISSUE TITLE
Forced desktop switch on Windows when opening with a path argument

### ISSUE THREAD

**Issue by adamralph** [microsoft/vscode#108074]
Issue Type: <b>Bug</b>

1. Start a VS code instance and make sure it is the currently selected window.
2. Switch to another desktop
3. Open a command prompt
4. Execute the command: `code .`

## Expected

A new VS Code instance opens on the current desktop.

## Actual

A new VS Code instance opens on the desktop where the previously active VS Code instance is located, and the view is switched to that desktop.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (15.04GB free)|
|Process Argv|. --crash-reporter-id 5f24b731-69eb-4e15-bbf8-514921257f9f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|11.3.1
markdown-preview-github-styles|bie|0.1.6
path-intellisense|chr|2.3.0
vscode-markdownlint|Dav|0.37.1
xml|Dot|2.5.1
EditorConfig|Edi|0.15.1
auto-rename-tag|for|0.1.4
vscode-pull-request-github|Git|0.20.0
code-eol|jef|1.0.11
prettify-json|moh|0.0.3
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
powershell|ms-|2020.6.0
vsonline|ms-|1.0.2965
vscode-yaml|red|0.11.1
code-spell-checker|str|1.9.2
tabnine-vscode|Tab|3.0.2
sort-lines|Tyr|1.9.0
vscode-jumpy|wma|0.3.1

</details>

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by adamralph** [comment]
I can't reproduce it all any more. Although I my RTM installation has moved on to 1.50 in the meantime, so perhaps it contains a fix.
