### ISSUE TITLE
VSIX package generated by 'vsce package' failing to install

### ISSUE THREAD

**Issue by ntilwalli** [microsoft/vscode#108017]
This occurs in Insiders as well.

- VSCode Version: 1.49.3
- OS Version: MacOS 10.15.6

Steps to Reproduce:

1. At command-line run `yo code` like the extensions documentation states, name package `my-extension`, configure to use npm (not yarn), basic hello world extension gets created.
2. add a `publisher` property to `package.json`
3. At command-line run `vsce package`
4. At command-line run `code ./my-extension.vsix` to install the extension. See message: "The file is not displayed in the editor because it is either binary or uses and unsupported text encoding.  Do you want to open it anyway?"

Does this issue occur when all extensions are disabled?: Not applicable, this is an extension specific issue.

**Comment by gjsjohnmurray** [comment]
In step 4 you are telling VS Code to *open* the file.

There may be a CLI switch to install an extension, but I don't recall. 

Another way is to open VS Code, switch to Extension activity, then drag the VSIX from Finder onto the drop target on the left.

**Comment by usernamehw** [comment]
There is a cli flag to install an extension https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions

```
code --install-extension <ext>
```

Also, there is an extension that adds context menu for explorer: https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-install-vsix

**Comment by ntilwalli** [comment]
Argh... I was looking at the wrong docs site, It doesn't show that flag here: https://vscode-docs.readthedocs.io/en/stable/extensions/install-extension/

It does show the flag on the actual docs site here: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

Thanks!
