### ISSUE TITLE
Integrated terminal does not accept special characters like á, à, é, í, ú, ü, ã, etc.

### ISSUE THREAD

**Issue by ferox** [microsoft/vscode#108032]
- VSCode Version: 1.49.3
- OS Version: Fedora 32 with Plasma/KDE
- Shell: bash and zsh
- commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69

Steps to Reproduce:

1. Step into Terminal -> New Terminal -> select a project
2. Start typing those special characters: á, à, ã, ä, etc.

Does this issue occur when all extensions are disabled?: Yes

**Comment by werymanen** [comment]
It works for me on Arch Linux,
VSCode version: 
1.49.3
2af051012b66169dde0c4dfae3f5ef48f787ff69
x64
OS Version: Arch Linux with Gnome
Shell: zsh

Works with all extensions

**Comment by ferox** [comment]
> It works for me on Arch Linux,
> VSCode version:
> 1.49.3
> [2af0510](https://github.com/microsoft/vscode/commit/2af051012b66169dde0c4dfae3f5ef48f787ff69)
> x64
> OS Version: Arch Linux with Gnome
> Shell: zsh
> 
> Works with all extensions

Good for you!!

This bug is annoying me.

I had to switch to PHPStorm, there is no such bug in there.

**Comment by jefferson-teixeira** [comment]
It's not works for me
VSCode version: 1.49.3
OS Version: Fedora 33 with Gnome
Shell: Bash

**Comment by Josevaldos950** [comment]
It's not works for me
VSCode version: 1.49.3
OS Version: Fedora 33
Shell: Bash

**Comment by geraldosimiao** [comment]
For me, it's happening the same bug as described by @ferox 
None of the special characters áéíóúäëïöüâêîôû and all the others like this are accepted on the build-in terminal and the integrated one.

RPM for the VScode downloaded form the oficial website (//code.visualstudio.com/Download)
Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:56:11.027Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.13-200.fc32.x86_64
FEDORA 32 workstation

**Comment by ferox** [comment]
This is definitely a VS Code bug. Everything is working as expected with Yakuake and PHPStorm 2020.2 terminal. 

![vs-code-bug-special-characters](https://user-images.githubusercontent.com/7634766/95091513-efd26380-06fc-11eb-83c4-0a3f01871ae2.png)

**Comment by Lailah** [comment]
I'm using Fedora 33 KDE Spin. If I type characters that have a key of its own it works fine, but if I use a modifier it doesn't.  It either shows an unmodified character or something else completely.  I have two layouts, German QWERTZ and Spanish Spain.

**Comment by edivancarvalho** [comment]
Follow my print I'm using Fedora 31 Cinnamon

![VsCode](https://user-images.githubusercontent.com/28677284/95197298-c3c3ea80-07af-11eb-9996-b157a2da6110.png)

**Comment by ferox** [comment]
I'm digging it to find the bug.
So I just installed Atom with the x-terminal plugin (https://github.com/bus-stop/x-terminal). X-Terminal is a fork of atom-xterm. So this  annoying bug also occurs in Atom Text Editor.

Atom version: 1.51.0
Electron version: 5.0.13
Node version: v12.0.0
X-Terminal version: 10.0.1

![bug-character-atom-xterm](https://user-images.githubusercontent.com/7634766/95276681-44bbca00-0822-11eb-98b4-2a6b5391e00f.png)

**Comment by viniciusmattosrj** [comment]
For me, it's happening the same bug as described by @ferox 
None of the special characters áéíóúäëïöüâêîôû and all the others like this are accepted on the build-in terminal and the integrated one.

RPM for the VScode downloaded form the oficial website (//code.visualstudio.com/Download)
Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:56:11.027Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic
Linux Mint 20 Cinnamon

**Comment by edivancarvalho** [comment]
> It works for me on Fedora 31.
> VSCode Version: 1.49.2
> 
> ![VsCode](https://user-images.githubusercontent.com/28677284/95198806-33d37000-07b2-11eb-8477-999957d3456d.png)


![ele](https://user-images.githubusercontent.com/28677284/95320329-b8d08f00-086f-11eb-85c8-4a03f05cbf09.png)

![Electerm](https://electerm.html5beta.com/)

**Comment by geraldosimiao** [comment]
After some tests and research on a few VMs an baremetal too, we have this results (all with the most up-to-date versions)
VScode on F33KDE or F33workstation => bug
VScode on F31KDE => bug
VScode on F32workstation => bug
VScode on F31cinnamon or F33cinnamon => NO BUG!!!!!

We found that using [electerm](https://github.com/electerm/electerm) (a project that uses xterm too) the problem mimics the results above.

**Comment by ferox** [comment]
I can confirm that the bug also occurs in **Codium**

    **Codium Version: 1.49.1**
    OS Version: Fedora 32 with Cinnamon
    Shell: bash
    commit: 58bb7b2331731bf72587010e943852e13e6fd3cf

Steps to Reproduce:

    Step into Terminal -> New Terminal -> select a project
    Start typing those special characters: á, à, ã, ä, etc.

Does this issue occur when all extensions are disabled?: Yes

![photo_2020-10-07_08-47-11](https://user-images.githubusercontent.com/7634766/95326934-bb37e680-0879-11eb-993b-464fb0f15d6c.jpg)

**Comment by ferox** [comment]
> > It works for me on Fedora 31.
> > VSCode Version: 1.49.2
> > ![VsCode](https://user-images.githubusercontent.com/28677284/95198806-33d37000-07b2-11eb-8477-999957d3456d.png)
> 
> ![ele](https://user-images.githubusercontent.com/28677284/95320329-b8d08f00-086f-11eb-85c8-4a03f05cbf09.png)
> 
> ![Electerm](https://camo.githubusercontent.com/0bdc5441d33305db0fcd1fb672b945e251e921e1/68747470733a2f2f656c65637465726d2e68746d6c35626574612e636f6d2f)

Cinnamon right???

**Comment by edivancarvalho** [comment]
yes

**Comment by geraldosimiao** [comment]
It seems that on F32 Cinnamon the bug shows too on my setup, on VScode and on Electerm.

**Comment by werymanen** [comment]
> I'm digging it to find the bug.
> So I just installed Atom with the x-terminal plugin (https://github.com/bus-stop/x-terminal). X-Terminal is a fork of atom-xterm. So this annoying bug also occurs in Atom Text Editor.
> 
> Atom version: 1.51.0
> Electron version: 5.0.13
> Node version: v12.0.0
> X-Terminal version: 10.0.1
> 
> ![bug-character-atom-xterm](https://user-images.githubusercontent.com/7634766/95276681-44bbca00-0822-11eb-98b4-2a6b5391e00f.png)

hmm, does that mean that it's an Electron issue?

**Comment by ferox** [comment]
> > I'm digging it to find the bug.
> > So I just installed Atom with the x-terminal plugin (https://github.com/bus-stop/x-terminal). X-Terminal is a fork of atom-xterm. So this annoying bug also occurs in Atom Text Editor.
> > Atom version: 1.51.0
> > Electron version: 5.0.13
> > Node version: v12.0.0
> > X-Terminal version: 10.0.1
> > ![bug-character-atom-xterm](https://user-images.githubusercontent.com/7634766/95276681-44bbca00-0822-11eb-98b4-2a6b5391e00f.png)
> 
> hmm, does that mean that it's an Electron issue?

No, maybe in the xterm.js

**Comment by ferox** [comment]
It´s working on Windows

- VSCode Version: 1.50.0
- OS Version: Windows 10
- Shell: Powershell
- commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3

![aceita-caracteres-no-windows10](https://user-images.githubusercontent.com/7634766/95641711-2cde8300-0a7a-11eb-9066-106b0c0560ff.png)

**Comment by meganrogge** [comment]
related to [this](https://github.com/xtermjs/xterm.js/issues/2479)

**Comment by Lailah** [comment]
I still have the same problem on Linux  (Fedora 33 KDE).

**Comment by ferox** [comment]
> I still have the same problem on Linux (Fedora 33 KDE).

Yeah, same here!!!!

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-15T11:13:06.921Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.18-300.fc33.x86_64
