### ISSUE TITLE
Enable a way to cycle through diffs in multiple files

### ISSUE THREAD

**Issue by tiagomacarios** [microsoft/vscode#108013]
User scenario:
I work on large scale refactorings which usually involves doing modifications on hundreds if not thousands of files. I started using VS code and one feature I really miss if the ability to cycle through all the diffs I have open.
In codeflow for example you can enable F7/F8 to cycle through files:
![codeflow](https://user-images.githubusercontent.com/5450113/94979720-52e3b080-04d9-11eb-991b-9b84ee199c98.png)

This was already requested in #50434, which was closed as a dupe of another item, that was closed as a dupe of another item... by the end of the linked list I am not sure we are discussing the same issue anymore.

Would it be possible to track this feature separately?

**Comment by joaomoreno** [comment]
This already exists:

![image](https://user-images.githubusercontent.com/22350/95083576-025c9500-071d-11eb-9085-081648f64e72.png)
