### ISSUE TITLE
vsc ignores my .gitignore

### ISSUE THREAD

**Issue by YonLiud** [microsoft/vscode#108075]
- VSCode Version: 1.49.3 (System Setup)
- OS Version: Microsoft Windows 2004 Build 20226.1000

1) I added a file to the .gitignore, committed and pushed
2) I edit the file for my personal information I don't wish to update on git
3) it still stages automatically the file in the Source Control even tho I added the file to gitignore

Does this issue occur when all extensions are disabled?: Yes/No: Yes
![image](https://user-images.githubusercontent.com/45634836/95019198-ac301900-066c-11eb-90fc-46f93a1f9e89.png)

**Comment by YonLiud** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Add right click option to add file or folder to .gitignore/.gitkeep (#105450)](https://www.github.com/microsoft/vscode/issues/105450)
> * [SCM: Adding to .gitignore should put folder if folder is selected (#81724)](https://www.github.com/microsoft/vscode/issues/81724)

Done already, did not help!

**Comment by sohomdatta1** [comment]
If the file is already tracked (part of a commit in the repository) `git` ignores that entry in the `.gitignore` file ([per this](https://git-scm.com/docs/gitignore)). I had this problem recently but figured out that it was `git` and not vscode that was not acting the way I wanted.

**Comment by YonLiud** [comment]
Thanks! that was the issue, by your answer I found the answer to my issue!!

**WARNING**: First commit your current changes, or you will lose them.
To fix it:
```
git rm -r --cached .
git add .
git commit -m "fixed untracked files"
```
(original answer [here](https://stackoverflow.com/questions/11451535/gitignore-is-ignored-by-git))
