### ISSUE TITLE
Allow configuring --no-xshm via runtime arguments

### ISSUE THREAD

**Issue by ShamimIslam** [microsoft/vscode#108053]
- VSCode Version: 1.49.3-1601661990.el7.x86_64
- OS Version: Fedora release 31 (Thirty One)

Steps to Reproduce:

1. Install VSCode on one machine with NVidia card running Xorg
2. Login to another machine with intel video card running Xorg
3. SSH from intel video card machine to VSCode machine with X11 forwarding enabled
4. Launch "code --disable-gpu"
5. Remote VsCode window on intel video card machine is white on white
6. Launch "code --disable-gpu" on NVidia card machine
7. Local VsCode window on Nvidia card machine is properly colored.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/101069

Please use `--no-xshm` as a workaround, thanks!

**Comment by ShamimIslam** [comment]
Is there an argv.json entry for this?

**Comment by deepak1556** [comment]
No there isn't one. Opening the issue to see if we can add it, seems like a good candidate.

**Comment by deepak1556** [comment]
@bpasero what is the criteria for adding a chromium flag to argv setting, do you think `--no-xshm` makes the cut, it helps apps connecting over remote X server which was broken for some distros after electron 9 upgrade.

**Comment by ShamimIslam** [comment]
Amusingly enough, the startup shell script claims --no-xshm is not a valid
flag to boot.

**Comment by deepak1556** [comment]
You can ignore that warning, the flag will still be passed to the runtime. That check is to validate flags used by the app itself.

**Comment by ShamimIslam** [comment]
Understood. Just amusing that it complains. Is there a way to see what
flags the underlying electron wrapper accepts?

Thanks.

**Comment by deepak1556** [comment]
Most of https://peter.sh/experiments/chromium-command-line-switches/ which aren't chrome specific.

**Comment by bpasero** [comment]
I don't think we have any rule, the original intent was to not allow for everything to be put into `argv.json` but have a list of things we think make sense.

**Comment by deepak1556** [comment]
Don't have plans to address this anytime soon, PR welcome.
