### ISSUE TITLE
Terminal does not open to file location (in D drive)

### ISSUE THREAD

**Issue by Viljami0** [microsoft/vscode#108060]
Issue Type: <b>Bug</b>

The terminal never opens to my workspace file's folder, therefore I have to type in the terminal -> D: -> cd <folder1> -> cd <folder2>
which wastes time.
I hope this bug gets fixed in the next version of VSC!

VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4018)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.97GB (20.12GB free)|
|Process Argv|--crash-reporter-id edee0ece-cd45-40f1-806c-2e66cd1ee2a7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.9.112786
debugger-for-chrome|msj|4.12.11
java|red|0.68.0
python|tht|0.2.3

</details>

**Comment by meganrogge** [comment]
can you please provide a gif of this? I can't reproduce the issue. @Viljami0
