### ISSUE TITLE
Qt application debugging problem

### ISSUE THREAD

**Issue by andreiuspehov** [microsoft/vscode#108027]
When debugging the Qt application that is different Qt runtime version from PySide2 installed with python, its unable to launch the Qt application because debugging environment includes PySide2 path into beginning the PATH variable.

Run under debuger:
...
if __name__ == '__main__':
    os.system("C:\\Windows\\System32\\cmd.exe /c path")
...
console out:
PATH=C:\Python37\lib\site-packages\PySide2;C:\Python37\lib\site-packages\numpy\DLLs;...

Is it possibility to remove this path (C:\Python37\lib\site-packages\PySide2) from PATH env variable when debugging?

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18363

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.9.112786
cpptools|ms-|1.0.1

**Comment by jrieken** [comment]
I don't understand the issue here
