### ISSUE TITLE
How to tell if debugAdapter supports Exception breakpoints?

### ISSUE THREAD

**Issue by pieandcakes** [Microsoft/vscode#10809]
Looking at the debugProtocol.d.ts file and the Capabilities object, I don't see how to notify VSCode that the debugAdapter does not support Exception Breakpoints. 

What would be the proper way to do this or does there need to be a capability that is added in the InitializeResponse to support this?

Thanks
Pierson

**Comment by weinand** [comment]
@pieandcakes for enabling the exception breakpoint filters, you have to return the filters as the `exceptionBreakpointFilters ` Capability from the `InitializeRequest`:
https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L752

Here is an example from node-debug:
```ts
		// This debug adapter supports two exception breakpoint filters
		response.body.exceptionBreakpointFilters = [
			{
				label: localize('exceptions.all', "All Exceptions"),
				filter: 'all',
				default: false
			},
			{
				label: localize('exceptions.uncaught', "Uncaught Exceptions"),
				filter: 'uncaught',
				default: true
			}
		];

```
