### ISSUE TITLE
Add hint to find Show All Commands

### ISSUE THREAD

**Issue by trivalik** [microsoft/vscode#108089]
If you are new to VS Code it is hard to find the key for "Show All Commands". Any plugin is it using, but not refering about the pressing or name of this to get into it.

Maybe it would be helpful to show hint with information what to press in bar where document names for opened documents is shown. If space get rid this information can be removed, maybe also remove after first few presses of the key.

**Comment by misolori** [comment]
Going to combine this request with https://github.com/microsoft/vscode/issues/115641 since that is tackling this by adding a search bar to the top of app window
