### ISSUE TITLE
net::ERR_CERT_AUTHORITY_INVALID   

### ISSUE THREAD

**Issue by KaustubhJadhav** [microsoft/vscode#108061]
Issue Type: <b>Bug</b>

This error occurs while trying to check for updates and turning on setting sync please help !!!!

net::ERR_CERT_AUTHORITY_INVALID

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 6.1.7600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B940 @ 2.00GHz (2 x 1995)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.95GB (5.26GB free)|
|Process Argv|--disable-gpu --crash-reporter-id edeb3e46-e83a-4adb-987a-d0655af9237c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.0.1
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
Can you attach the log following these steps

* launch vscode with `code.cmd --log-net-log=<some-absolute-path>/netlog.json`
* Search for extensions or check for updates or try using settings sync
* Quit the application

Attach the generated netlog.json, thanks!

**Comment by xin053** [comment]
The same when check for updates (vscode 1.50.0)

[netlog.log](https://github.com/microsoft/vscode/files/5384483/netlog.log)
