### ISSUE TITLE
Remote Pair Programming Idea

### ISSUE THREAD

**Issue by drew-wallace** [Microsoft/vscode#10802]
After using this extension on Atom, I feel like it would be an awesome addition to VS code.

https://github.com/motepair/motepair

They use sockets that listen for major editor functions and the result is mimicked on the other users's editor.

I'm not sure if this functionality is doable for an extension given the currently exposed APIs, but having it as a core VS code feature would enable a richer user experience.

**Comment by sandy081** [comment]
@drew-wallace That's a good idea. If I remember, I have seen a video of a vscode extension that does something similar. But sadly, I am not able find that extension in our repo. So this is doable with the current APIs.

Since this is for an extension request. Please feel free to contribute to vscode extensions and you can always ask us questions if you have any.

Thanks.

**Comment by jldork** [comment]
Did this extension get created? How would I be able to track progress on extensions like this?

**Comment by drew-wallace** [comment]
@jldork I am almost done with a beta. I made a feature request (#11418 and was pointed to #10801) that would allow me to finish it. Here is the link to my repo: https://github.com/drew-wallace/vscode-motepair. If anyone wants to help me, it would be greatly appreciated.

**Comment by jldork** [comment]
@drew-wallace shot you an email (pulled from your git log)

**Comment by georgeedwards** [comment]
@drew-wallace Is that project no longer maintained?

**Comment by drew-wallace** [comment]
@georgeedwards Unfortunately yes. I ran into issues with document management (sync) and attempted to just send input between clients. I ran into an infinite loop because vscode couldn't determine remote input from local input. You can fork mine or take the mote-pair from Atom and compile the coffeescript to javascript and replace the atom API calls with vscode API calls. That's what I did to get started.
