### ISSUE TITLE
Remote explorer ends up in invalid state

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#108008]
1) install the Remote-SSH and the Codespaces extension
2) Open the remote explorer
3) Select SSH Targets
3) Grab the SSH Targets view and drag it onto the activity bar
-> the drop down still shows both entries but without any view
-> the dropped view only shows SSH Targets (as expected) and so there is no way to get to Codespaces anymore
4) Use the SSH Targets view and move it back into the Remote Explorer
-> two views, one of them a zombie

**Comment by alexr00** [comment]
Looks like somehow the remote explorer got enable for moving views again...
