### ISSUE TITLE
Feature for starting up a project by cloning the project directly from version control

### ISSUE THREAD

**Issue by S2606** [microsoft/vscode#108068]
So currently if I were to open a new project which is deployed in some version-controlled Source-Code Management(SCM) software like Github, first I would need to clone it to my local machine, followed by opening VSCode and then `File->Open`. How about if we could give an option wherein I could just provide an URL for the software which is present in some SCM and basically could do above two mentoined steps from just one place. This could help in easier starting up new projects.

**Comment by S2606** [comment]
Also would like to contribute towards this feature.

**Comment by joaomoreno** [comment]
That already exists for the built-in Git extension. The command is `Git: Clone`.
