### ISSUE TITLE
match html tags

### ISSUE THREAD

**Issue by FructuosoRobles** [Microsoft/vscode#10808]
- VSCode Version:
- OS Version:

It is a problem in big html files, match the tags, I really love VSCode...

**Comment by AnthonyMichaelc** [comment]
Are you trying to find the matching tag or are you saying that it is not auto completing the matching tag? And what version/os?

**Comment by FructuosoRobles** [comment]
1.4 I ment to see the matching tag.  Autocomplete is doing fine with the
Tab.

**Comment by AnthonyMichaelc** [comment]
From my experience it is a little tricky at first to see but to test if you put a div or p or any tag in a small space and then put the cursor before the tag and arrow over you will see it will highlight the inside of the start and ending tag. Would be nicer if they had a feature that underlined or bright color highlight but there is a slight highlight color at the moment. I hope that helps you a little.

**Comment by FructuosoRobles** [comment]
Thanks. I will check it.

Have a nice day.

**Comment by AnthonyMichaelc** [comment]
No problem, give feedback if it does not work.

You to.

**Comment by sandy081** [comment]
@AnthonyMichaelc Thanks for pitching in and helping out. 

@FructuosoRobles Please let us know if your issue is solved otherwise open the issue with what you are expecting

Thanks.
