### ISSUE TITLE
Bulk Edit: unsafe file events handling

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108090]
Bulk edit seems to install a file listener to check for conflicts in models:

https://github.com/microsoft/vscode/blob/0681925277df77878322d2ad789b746f462a08c9/src/vs/workbench/contrib/bulkEdit/browser/conflicts.ts#L58-L71

By using the `resource` property of the file event and then looking for a model, we potentially miss out on models that have a different canonical form compared to the file event. Since models can have any canonical form (depending on how the model was first opened), we need to either use `IURIIdentitiyService` for comparing, or use the `IFileChangeEvent.contains` method which internally uses the `IURIIdentityService` too.

I recently changed to this form for my file event handler in file models. Instead of iterating over all file changes and getting the model for a `resource`, I now loop over my models and use the `contains` method:

https://github.com/microsoft/vscode/blob/7f4737616fc5b2d42a681ad09427ca1189c6cadd/src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts#L101-L114

**Comment by jrieken** [comment]
> I recently changed to this form for my file event handler in file models. Instead of iterating over all file changes and getting the model for a resource, I now loop over my models and use the contains method:

O(n2) 😱

**Comment by bpasero** [comment]
@jrieken PR to adopt `TernaySearchTree` for file events in https://github.com/microsoft/vscode/pull/108096
