### ISSUE TITLE
Markdown preview always renders anchors as links

### ISSUE THREAD

**Issue by brunnerh** [microsoft/vscode#108166]
Issue Type: <b>Bug</b>

Contents of anchors without `href` should just render normally.

Example:

![image](https://user-images.githubusercontent.com/834235/95176919-cfb6a900-07bd-11eb-9148-4518ac1dcd3d.png)

As text:

```markdown
...

<a id="custom-anchor">This is an anchor</a>

...

[This is a link](#custom-anchor)
```

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.17134

**Comment by mjbvz** [comment]
The markdown preview uses Markdown-it, which also has this behavior: https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Ca%20id%3D%5C%22custom-anchor%5C%22%3EThis%20is%20an%20anchor%3C%2Fa%3E%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

Please file an issue against [Markdown-It](https://github.com/markdown-it/markdown-it) if you feel this is a problem

**Comment by brunnerh** [comment]
@mjbvz
It is not an issue with markdown-it, that only generates HTML, not CSS.
The presentation is part of the webview code. I can create a pull request to fix this.
