### ISSUE TITLE
Expose debug adapters to extensions

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#108138]
I request that the classes in the following files are exposed to extensions, or distributed as a separate NPM package:

- [`src/vs/workbench/contrib/debug/common/abstractDebugAdapter.ts`](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/debug/common/abstractDebugAdapter.ts)
  - `AbstractDebugAdapter`
- [`src/vs/workbench/contrib/debug/node/debugAdapter.ts`](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/debug/node/debugAdapter.ts)
  - `StreamDebugAdapter`
  - `NetworkDebugAdapter`
  - `SocketDebugAdapter`
  - `NamedPipeDebugAdapter`
  - `ExecutableDebugAdapter`

As an extension developer, when implementing a `DebugAdapterDescriptorFactory`, I have access to a number of descriptors I can return: `DebugAdapterExecutable`, `DebugAdapterServer`, and `DebugAdapterNamedPipeServer`. However, I do not have access to the actual debug adapter implementation that is instantiated, unless I write and instantiate my own adapter and return a `DebugAdapterInlineImplementation`. Thus, if I want to provide any variation on the base executable, server, or named pipe server debug adapter implementations, I am forced to reimplement the entire adapter.

This is very inconvenient, as I am working on a debugger extension for a Ruby debug adapter that has first-class support for DAP. The existing `ExecutableDebugAdapter` does 99% of what I need; all it's missing is a way to handle STDERR:

```typescript
class MyDebugAdapter extends ExecutableDebugAdapter {
    async startSession(): Promise<void> {
        await super.startSession()

        this.serverProcess.stderr!.on('data', data => /* do something useful */);
    }
}
```

**Comment by connor4312** [comment]
You may find https://github.com/microsoft/vscode-debugadapter-node useful.

**Comment by firelizzard18** [comment]
@connor4312 Nothing in that project fills the role of `ExecutableDebugAdapter`, so I would still have to reimplement most of its functionality. `ExecutableDebugAdapter` does *exactly* what I want, which is why I am asking for it to be exposed.

**Comment by connor4312** [comment]
I see.

We do not generally expose VS Code internals as modules. For instance, within the ExecutableDebugAdapter there is a significant amount of logic around normalizing and parsing contributions, which as a single extension you are unlikely to need.

However you should be able to easily implement what you need using the [ProtocolServer](https://github.com/microsoft/vscode-debugadapter-node/blob/3f8d7b0bb049278715ff76b2dec84d8a5e604441/adapter/src/protocol.ts#L81) on top of the child_process module in a few lines of code, e.g. creating an inline debug adapter from it:

```js
const child = spawn('my-debug-adapter-exec', { stdio: 'pipe' });

const server = new ProtocolServer();
server.start(child.stdout, child.stdin);
child.stderr.on('data', data => /* do something useful */);

return new DebugAdapterInlineImplementation(server);
```

**Comment by firelizzard18** [comment]
This does not work for me.

I have a debug adapter that can work via stdin/stdout or via a unix socket:

```typescript
class MyFactory implements DebugAdapterDescriptorFactory {
    async createDebugAdapterDescriptor(session: DebugSession) {
        if (session.configuration.request == 'attach') {
            return new DebugAdapterNamedPipeServer(session.configuration.socket);
        }

        const program = '...'
        const args = ['...', '--listen-on-unix-socket', '/tmp/byebug.socket']
        const dbg = spawn(program, args, {
            cwd: config.cwd,
            env: config.env,
            stdio: 'pipe',
        });

        let ready: (r: Boolean) => void;
        const setup = new Promise((ready) => {
            dbg.stdout.on('data', /* ... */);
            dbg.stderr.on('data', /* ... */);
            dbg.on('exit', /* ... */);
            dbg.on('error', /* ... */);
        });

        if (!await setup)
            return null;

        return new DebugAdapterNamedPipeServer('/tmp/byebug.socket');
    }
}
```

However, if I instruct my adapter to listen on stdin/stdout and use `ProtocolServer`:

```typescript
        const args = ['...', '--listen-on-unix-stdio']
        // ...

        const adapter = new ProtocolServer();
        adapter.start(dbg.stdout, dbg.stdin);
        return new DebugAdapterInlineImplementation(adapter);
```

Then it does not work. The debug session hangs, with only the restart and stop buttons enabled and the progress indicator cycling endlessly. I put a breakpoint on the return statement, and it does return.
