### ISSUE TITLE
Git gui icon disappeared vs code

### ISSUE THREAD

**Issue by Tolson321** [microsoft/vscode#108198]
- VSCode Version: 1.49.3
- OS Version: 10.15.7

Steps to Reproduce:

1. The cause of this is a button I accidentally pressed that removed it.  I don't remember what the button said exactly... 
The git gui icon is missing. I have tried creating a new repo + git init. Also, I have tried to enable and disable git from settings nothing has worked.no updates recently. any help with fixing this would be much appreciated!

I like using the git gui so would rather not switch back to the terminal for everything.

Thanks!
 link to  chat about it https://stackoverflow.com/questions/64230725/git-gui-icon-disappeared-vs-code

![SQ6ro](https://user-images.githubusercontent.com/57242391/95241880-6abe7b80-07dc-11eb-82f9-072ee08b5195.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tolson321** [comment]
It has not been covered in that issue

**Comment by misolori** [comment]
Can you right-clicking on the activity bar where the icons are and seeing if "Source Control" is checked?

![image](https://user-images.githubusercontent.com/35271042/95265290-c2adb000-07e5-11eb-84c0-c7714278d75b.png)

**Comment by vitoravale** [comment]
Same problem here:

<img width="267" alt="Screen Shot 2020-10-06 at 22 38 51" src="https://user-images.githubusercontent.com/4126824/95277677-bdbc2100-0824-11eb-9e46-5b82cf07870a.png">

About vscode infos:
Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:54:06.165Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by vitoravale** [comment]
@Tolson321 I've the same problem, in my case I dragged from activity bar to explorer, but the solution was quite simple

![Kapture 2020-10-06 at 22 48 44](https://user-images.githubusercontent.com/4126824/95278299-48e9e680-0826-11eb-8d75-7d065231b5df.gif)

**Comment by misolori** [comment]
You can also run `View: Reset View Locations` from the command palette to reset it if the view moved somewhere else.

**Comment by Tolson321** [comment]
Woohoo! Right-clicking was the ticket. Thanks for your help!

**Comment by misolori** [comment]
Glad that helped!

**Comment by Tolson321** [comment]
now the gui doesn't update my saved changes whether uncommitted or committed. 

![Screen Shot 2020-10-08 at 12 18 55 PM](https://user-images.githubusercontent.com/57242391/95486173-aeda8900-0960-11eb-9e37-d6ac08223f32.png)
 Any idea how I can fix this also??
