### ISSUE TITLE
Bug: code . activates other editor windows

### ISSUE THREAD

**Issue by perlun** [microsoft/vscode#108174]
- VSCode Version: 1.49.3 2af051012b66169dde0c4dfae3f5ef48f787ff69
- OS Version: Linux alladin 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

Steps to Reproduce:

1. Run `code .` from a terminal.
2. All active editor windows are moved on top of other windows, even others than the one I just opened. This is annoying and it seems like a regression. It worked properly in the last VSCode I used before the upgrade (Debian package 1.48.2-1598353430).

_Does this issue occur when all extensions are disabled?_: Yes

This is probably easier to explain with a few screenshots. The right-hand window is stacked below the terminal window before `code .` is invoked:

### Before launching

![image](https://user-images.githubusercontent.com/630613/95191056-e0284d00-07d8-11eb-987b-41e1b340ce21.png)

### After launching

![image](https://user-images.githubusercontent.com/630613/95191299-3d240300-07d9-11eb-8748-8a6ec1fadfa3.png)

**Comment by perlun** [comment]
Any ideas about this one @Tyriar? It's rather annoying since I tend to use the `code .` approach quite often, to open projects (or just make VS Code highlight the window for a particular project I have open).

**Comment by perlun** [comment]
Ping @Tyriar - this is still an issue, and unfortunately a bit annoying.

**Comment by Tyriar** [comment]
Strange, this doesn't happen for me on Windows or Ubuntu. Looping in @bpasero as it's related to window focus
