### ISSUE TITLE
Add icon for .svelte file

### ISSUE THREAD

**Issue by haohanyang** [microsoft/vscode#108112]
Icon for .svelte file is missing in the default icon set. It's better to add it.
<img width="234" alt="image" src="https://user-images.githubusercontent.com/37651510/95077057-74e16b00-0745-11eb-89df-c451c3b417c3.png">

Info:
Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
OS: macOS 10.15.7

**Comment by mocktarissa** [comment]
This is a Feature Request

**Comment by gjsjohnmurray** [comment]
VS Code uses seti-ui for its file icons so you'll need to make a request on that repo, https://github.com/jesseweed/seti-ui

If you do that, maybe link to it from here. Either way please close this issue.

**Comment by misolori** [comment]
Thanks @gjsjohnmurray, yes please file an issue in the [seti-ui theme](https://github.com/jesseweed/seti-ui) repo.
