### ISSUE TITLE
Save As - Doesn't work

### ISSUE THREAD

**Issue by AlessandroPerina** [microsoft/vscode#108178]
Issue Type: <b>Bug</b>

Open a file (ipynb)
Press Save As basically to create a copy
File explorer doesn't show up

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (19.47GB free)|
|Process Argv|--crash-reporter-id 8f7b0688-8ff4-4389-a4d0-47fc2265e74f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
beautify|Hoo|1.5.0
mssql|ms-|1.9.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.9.112786
geo-data-viewer|Ran|2.3.0
vscode-yaml|red|0.11.1
language-c3|rsa|0.2.0
c3-vscode|sha|0.2.4
vscode-icons|vsc|11.0.0

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
