### ISSUE TITLE
Linux yum repository signature broken

### ISSUE THREAD

**Issue by cesarizu** [microsoft/vscode#108135]
- VSCode Version: N/A
- OS Version: openSUSE tumbleweed

Steps to Reproduce:

1. Follow the guide at https://code.visualstudio.com/docs/setup/linux#_opensuse-and-slebased-distributions
2. Run `sudo zypper refresh` as the guide suggests (and needed to install the package)
3. The following message appears:

```
Signature verification failed for file 'repomd.xml' from repository 'Visual Studio Code'.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: This file was modified after it has been signed. This may have been a malicious change,
    so it might not be trustworthy anymore! You should not continue unless you know it's safe.
```

Does this issue occur when all extensions are disabled?: Yes/No
N/A

**Comment by darix** [comment]
could it be that this happens every time one of the non-stable builds gets updated in the repository?

**Comment by cesarizu** [comment]
This also happens to other microsoft repositories all the time like the one at https://packages.microsoft.com/opensuse/15/prod/

Besides the problem with the `repomd.xml` I also get errors with packages that fail signature checks.

The problems go away and reappear constantly.
