### ISSUE TITLE
Erro 5: Acesso negado na atualização de software

### ISSUE THREAD

**Issue by AndreOliveira00** [microsoft/vscode#108127]
Quando tenho aberto o VScode aparece me o seguinte erro:
" O instalador foi incapaz de criar o diretório C:\Users\André
Erro 5: Acesso negado"
O mesmo acontece quando tento fazer uma atualização de software do VScode na aba Help ->Check for Upgrades.
Estava com problemas na configuração do VScode anteriormente pois tinha "André" como diretório. Optei então por fazer a troca para "Andre". Friso que neste processo também troquei o nome nos registos.

Tentei realizar uma nova instalação por cima desta já instalada mas da mesma occore também erro.
Terei algum ficheiro corrompido ou simplemente tenho de trocar os diretórios?

Obrigado, cumprimentos,
André Oliveira.

**Comment by cajlonbatista** [comment]
Please change the language

**Comment by AndreOliveira00** [comment]
When I open VScode, the following error appears:
"The installer was unable to create the C: \ Users \ André directory
Error 5: Access is denied "
The same happens when I try to do a software update of VScode in the Help -> Check for Upgrades tab.
I had problems with the VScode configuration previously because I had "André" as a directory. So I chose to switch to "Andre". I emphasize that in this process I also changed the name in the records.

I tried to perform a new installation on top of this one already installed but the same error also occurs.
Will I have a corrupted file or do I just have to change directories?

Thank you, greetings,
André Oliveira.

> Quando tenho aberto o VScode aparece me o seguinte erro:
> " O instalador foi incapaz de criar o diretório C:\Users\André
> Erro 5: Acesso negado"
> O mesmo acontece quando tento fazer uma atualização de software do VScode na aba Help ->Check for Upgrades.
> Estava com problemas na configuração do VScode anteriormente pois tinha "André" como diretório. Optei então por fazer a troca para "Andre". Friso que neste processo também troquei o nome nos registos.
> 
> Tentei realizar uma nova instalação por cima desta já instalada mas da mesma occore também erro.
> Terei algum ficheiro corrompido ou simplemente tenho de trocar os diretórios?
> 
> Obrigado, cumprimentos,
> André Oliveira.
