### ISSUE TITLE
Multicursor modifier in Linux doesn't work properly

### ISSUE THREAD

**Issue by Vanuan** [microsoft/vscode#108109]
Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:40:55.768Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-48-generic

Steps to Reproduce:

1. Open a file
2. Press alt and drag the cursor - column is not selected
3. Go to setttings, change multi cursor modifier from alt to ctrlCmd
4. Press alt and drag the cursor - column is selected

Does this issue occur when all extensions are disabled?: Yes

**Comment by Vanuan** [comment]
It seems that multicursor modifier is inverted? And the ctrl+click doesn't work.

**Comment by alexdima** [comment]
@Vanuan on some linux distributions, alt+clicking is eaten up by the OS (to move windows or something like that). You can try configuring in your `settings.json` `"editor.multicurosrModifier": "ctrlCmd"` and then use ctrl+clicking to add multiple cursors.

**Comment by Vanuan** [comment]
@alexdima Well, alt-clicking works, but only when `"editor.multicurosrModifier"` is set to `"ctrlCmd"`. It's Ctrl+clicking that doesn't work. Very strange.

**Comment by alexdima** [comment]
@Vanuan Are you able to use the gesture of ctrl+click in other software on the same machine? Often ctrl+click is used in browser to open in a new tab so you could try a browser to test if it works perhaps..

**Comment by Vanuan** [comment]
@alexdima Yes, Ctrl+Click does work in other applications and in chrome. It also works in VSCode itself (in the terminal).

It appears that there's some issue with the editor window.

So, when it's set to "CtrlCmd", pressing the "Alt+Click" combination will trigger opening a file link in the Terminal and the block selection.
When it's set to nothing (Alt by default), The combination to open a file link will be "Ctrl+Click" and neither "Alt+Click" nor "Ctrl+Click" can be used for the block selection.

**Comment by Vanuan** [comment]
So the click link code does seem to work properly:

https://github.com/microsoft/vscode/blob/8c91bd827848f1710d055c39d80d04c59bb55463/src/vs/editor/contrib/gotoSymbol/link/clickLinkGesture.ts#L84-L94

What doesn't work is the actual dragging:

https://github.com/microsoft/vscode/blob/76bc88fd9d2e658c3ed3b46e3c47ab746a274d48/src/vs/editor/browser/view/viewController.ts#L105-L113

https://github.com/microsoft/vscode/blob/76bc88fd9d2e658c3ed3b46e3c47ab746a274d48/src/vs/editor/browser/view/viewController.ts#L137-L150

I'm confused. Should this option be set to `CtrlCmd` or `CtrlKey`?

**Comment by Vanuan** [comment]
Strange:

https://github.com/microsoft/vscode/blob/0e297b112830bd5be9cf51a848d9314c3887ec42/src/vs/editor/common/config/editorOptions.ts#L345-L349

**Comment by Vanuan** [comment]
Maybe this line `this.configuration.options.get(EditorOption.multiCursorModifier)` casts the string literal to the string type so that the error is not detected by the typescript compiler?

**Comment by Vanuan** [comment]
Ah, found. It gets converted in here: https://github.com/microsoft/vscode/blob/0e297b112830bd5be9cf51a848d9314c3887ec42/src/vs/editor/common/config/editorOptions.ts#L2483-L2488

**Comment by Vanuan** [comment]
Found the platform specific line:

https://github.com/microsoft/vscode/blob/76bc88fd9d2e658c3ed3b46e3c47ab746a274d48/src/vs/editor/browser/view/viewController.ts#L132

Is it a smoking gun?

**Comment by Vanuan** [comment]
Ah, it was turned off:

![image](https://user-images.githubusercontent.com/361985/95267447-f6b4bf80-083d-11eb-87e0-532d9d4db18a.png)

So the bug is that Alt+click selection still works even though the setting is off.

**Comment by Vanuan** [comment]
Ok. It seems I misunderstood how it is supposed to work.

So, first make sure that "Column selection" is set to "true". Otherwise the behavior of "alt+drag" is undefined.

Then, if "multicursorModifier" is set to "ctrlCmd", "alt+drag" does select the column.

When "multicursorModifier" is set to "alt" or unset, "ctrl+drag" enables the column selection.

Apparently, works as expected. It's that my expectation was wrong.
