### ISSUE TITLE
VSC freezes when a ps1 script is opened

### ISSUE THREAD

**Issue by robycambo** [microsoft/vscode#108106]
Issue Type: <b>Bug</b>

Open VSC and browse to open any ps1 script file: after a while the app will freeze

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.89GB (13.15GB free)|
|Process Argv|C:\Data\Software\Gmcs\GIT\06-DOCKER_RELEASES\ASSEMBLY --crash-reporter-id 48914a6a-f46b-4fb7-a592-f339028dce8f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.6.0
python|ms-|2020.9.112786
remote-wsl|ms-|0.44.5
cpptools|ms-|1.0.1
powershell|ms-|2020.6.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0

</details>

**Comment by robycambo** [comment]
Don't know if it is due to VSC or Powershell extension itself

**Comment by alexr00** [comment]
I see that you have a powershell extension installed. If you disable that extension do you still see the issue?
