### ISSUE TITLE
extension overrides keyboard shortcuts without warning

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#108142]
Issue Type: <b>Bug</b>

installing an extension (eg yzhang.markdown-all-in-one) can override default and custom keyboard shortcuts without telling you. uninstalling the offending extension doesn't revert those shortcuts resulting in a significant amount of frustration and downtime reverting to a working environment.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.10.0-1127.18.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (6.42GB free)|
|Process Argv|--crash-reporter-id 70645636-42ae-4864-b371-1810b42a2956|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.56.1:2222|
|OS|Linux x64 3.10.0-1127.18.2.el7.x86_64|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|3.70GB (2.07GB free)|
|VM|100%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp-to-typescript|adr|1.12.1
gitlens|eam|10.2.2
react-javascript-to-typescript-transform-vscode|moh|1.10.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
cmake-tools|ms-|1.4.2
pdf|tom|1.1.0

</details>

**Comment by alexdima** [comment]
@Spongman Please report against the extension. By design, extensions can override default keybindings (via the `keybindings` contribution point), but it will not override user defined keybindings.

**Comment by Spongman** [comment]
Right but my point is that an extension overrides built-in keybindings and then those keybindings are not reset when the extension is uninstalled.

**Comment by alexdima** [comment]
> and then those keybindings are not reset when the extension is uninstalled

This specific extension might be doing something bad such as editing your `keybindings.json`. But the contribution point `keybindings` that extensions can use will be removed when the extension is uninstalled. For example, you can try installing the Sublime keymap or the VS keymap extension. They will change the default keybindings and as soon as they are uninstalled or disabled, their customizations to the default keybindings are also removed.

**Comment by alexdima** [comment]
It looks like this extension is contributing a lot of keybindings -- https://github.com/yzhang-gh/vscode-markdown/blob/8b09452402e6b7200f65dc63a4c94343f8813393/package.json#L91-L213 -- As soon as you disable or uninstall it they will no longer be part of our system.

**Comment by Spongman** [comment]
> As soon as you disable or uninstall it they will no longer be part of our system.

i thought i had made it clear: this is not happening. i have uninstalled the extension, and my keybindings remain broken.

**Comment by alexdima** [comment]
> i have uninstalled the extension, and my keybindings remain broken.

Keybindings are customized from two sources:
- from extensions (like this one)
- from your **personal** `keybindings.json` on your machine

Please take a look at your `keybindings.json` file (`F1 > Open Keyboard Shortcuts (JSON)`), comment it out or review what you have in there.

**Comment by Spongman** [comment]
i'm sorry, i'm not able to do that now. i had to uninstall, pave & reinstall everything from scratch just to get back to a working config.
