### ISSUE TITLE
Creating a new pawdraw (custom editor) file with autoSave enabled continually asks to save the file

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#108143]
- VSCode Version: 1.49.3
- OS Version: Window 10

Steps to Reproduce:

1. Build and debug the custom-editor-sample
1. Turn on 'autoSave' with some short delay
1. Create new paw draw file
1. Draw on the surface
1. Save as dialog appears every time you draw

Does this issue occur when all extensions are disabled?: Yes

**Comment by greazer** [comment]
@mjbvz, it's not clear from this bug, but it's blocking our ability to release our custom editor solution in Python. Can it be prioritized higher? Thanks!

**Comment by mjbvz** [comment]
I don't see this behavior on MacOS with insiders. What do you mean by new? Is this with an untitled file?

**Comment by rchiodo** [comment]
Yes should be an untitled file.

**Comment by rchiodo** [comment]
![untitledsave](https://user-images.githubusercontent.com/19672699/95909146-d9f31d00-0d52-11eb-8623-6243e24d3098.gif)

**Comment by mjbvz** [comment]
Thanks. Please test this in the next VS Code insiders builds for the python extension and let me know if you still see the issue (it works for me using the custom editor sample)
