### ISSUE TITLE
The debug button does not get disabled on click, when process is running

### ISSUE THREAD

**Issue by saurabsa** [Microsoft/vscode#10813]
- VSCode Version: 1.4
- OS Version: Mac OSx

Steps to Reproduce:

1. Create a dotnet core project ad debug it using C# for Visual Studio Code (powered by OmniSharp).
2. The debug button does not get disabled on click when process is running and gets disabled only when it hits the breakpoints. 
So user might press debug button multiple times even before the first action completes.

**Comment by isidorn** [comment]
Can not repro with latest vscode insiders.
Clicking on the debug button it gets disabled immediatly for me. Do you see the issue with latest vscode insiders, and if yes can you attach a short video demonstrating the issue.
Just to avoid confussion which exact debug button are you refering to?

**Comment by isidorn** [comment]
Closing until more data is provided .
