### ISSUE TITLE
Allow users to change or define the default window size

### ISSUE THREAD

**Issue by kuworking** [microsoft/vscode#108179]
When using a 4K display and Windows 10, every new instance of vscode opens at a unusable small size, forcing a manual resize

Most of the times it wouldn't be necessary if this is a second or third window to just check some code, IF the default size was big enough

So it would be nice to allow in `settings` to define a standard size when opening the window, or something similar

**Comment by bpasero** [comment]
@kuworking did you try the window setting:

![image](https://user-images.githubusercontent.com/900690/95205818-30f27280-07e6-11eb-96c5-2e4cbfb9f3ee.png)

**Comment by kuworking** [comment]
Absolutely awesome, thanks!
