### ISSUE TITLE
String with curly braces breaks C# highlighting

### ISSUE THREAD

**Issue by kuulemart** [Microsoft/vscode#10816]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

When C# string contains curly braces then highlighting breaks down afterwards. Code example (see highlighting after first string in code):

namespace Test
{
    class Test
    {
        string Test1 = string.Format("{0}", 1);
        string Test2 = string.Format("{0}", 2);
    }
}

**Comment by sandy081** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#702
