### ISSUE TITLE
Vscode doesn't work with python 3.8(Last Version)

### ISSUE THREAD

**Issue by yezz123** [microsoft/vscode#108110]
When i try to work using python `3.8.6` And debug he give me Errors and when i change to other IDLE he work or if i work with an  other version like 
![Screenshot 2020-10-05 111450](https://user-images.githubusercontent.com/52716203/95067642-07f5b300-06fc-11eb-8cbf-70373d5f9672.png)
And the problems for them both like for the the `python.exe` inside this path:
`C:\Python38\`
`C:\Users\name\AppData\Local\Programs\Python\Python38-32`
![Screenshot 2020-10-05 111020](https://user-images.githubusercontent.com/52716203/95067220-62dada80-06fb-11eb-8d68-bb222b147fde.png)

**Comment by gjsjohnmurray** [comment]
See also #107967
