### ISSUE TITLE
Integrated Terminal leaves out the background color of output when the foreground is the same.

### ISSUE THREAD

**Issue by Jaykul** [Microsoft/vscode#10817]
- VSCode Version: 1.5.0-insider
- Commit 435df14a684df718c5ec523f9d674e63d1662c37
- Date 2016-08-22T08:10:56.602Z
- Shell 0.37.6
- Renderer 49.0.2623.75
- Node 5.10.0
- OS Version:  Windows 10 (10.0.14393.82)

If the foreground and background colors of the output are the same, instead of getting a space with the *specified* background color, I get the background color of the terminal showing through.

![terminal](https://cloud.githubusercontent.com/assets/192942/17880934/d328509e-68ce-11e6-94f2-3c4f07efbd14.jpg)

## Steps to Reproduce:

1. Open integrated terminal
2. Run a command that outputs matching foreground and background colors: 
```posh
Write-Host "HELLO" -Fore White -Back Green -NoNewline
Write-Host "PADDING" -Fore Green -Back Green -NoNewline
Write-Host "WORLD" -Fore White -Back Green
```

**Comment by Tyriar** [comment]
Not sure what's happening here as it works just fine in bash, I would suspect powershell is trying to be tricky?

![image](https://cloud.githubusercontent.com/assets/2193314/17900848/c12a77d6-6915-11e6-9d9e-8dd773530ff7.png)

@daviwil any ideas?

**Comment by daviwil** [comment]
Hmmm, not sure, maybe @lzybkr has an idea?

**Comment by Tyriar** [comment]
I don't totally understand how [winpty](https://github.com/rprichard/winpty) translates to/from ANSI escape sequences for Windows. It may be something to do with that?

**Comment by lzybkr** [comment]
It's not PowerShell, I see the same if I use:

```powershell
& {
[Console]::ForegroundColor = 'White'
[Console]::BackgroundColor = 'Green'
[Console]::Write('HELLO')
[Console]::ForegroundColor = 'Green'
[Console]::Write('PADDING')
[Console]::ForegroundColor = 'White'
[Console]::Write('WORLD')
}
```

**Comment by Tyriar** [comment]
I'm guessing it's winpty then, I've read somewhere that it uses screengrabs for some stuff. We're also on an older version of it. I'll close this off as it's purely an upstream issue.

**Comment by Tyriar** [comment]
Thanks for the help @lzybkr, @daviwil

**Comment by EmSyndio** [comment]
I'm on mac and I have the same issue...
