### ISSUE TITLE
Emmet Abbrevation for HTML5

### ISSUE THREAD

**Issue by getsetgopi** [microsoft/vscode#108119]
Current Emmet Abbrevation for HTML5 feature for html:5 & ! spits out HTML5 structure as below. However, the IE compatible meta tag (<meta http-equiv="X-UA-Compatible" content="IE=edge"/>) is missing.
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
```
*Should have IE compatible meta tag included as below*
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
```

**Comment by asiawin** [comment]
Internet Explorer is now unsupported and that tag is now unnecessary

**Comment by getsetgopi** [comment]
@aisawin. I completely agree with you. However, IE 11 is still not EOL and is still used as default browser by many users and supported by some organisation (Including mine).

**Comment by asiawin** [comment]
@getsetgopi My username is `@asiawin` not `@aisawin`. Btw I also agree with you because I also use IE to test my websites. So that tag may be necessary

**Comment by rzhao271** [comment]
\closedWith dc5a3da

**Comment by meganrogge** [comment]
should it delete the `html:5 & ` part? not sure if that's expected or not. @rzhao271 

![recording (9)](https://user-images.githubusercontent.com/29464607/105913078-31a35480-5fe1-11eb-81f5-8a2f4d62dcbd.gif)

**Comment by rzhao271** [comment]
@meganrogge I see what happened.
The original poster meant that `html:5` and `!` should produce the same expansion. So in your screencap, you verified that `!` expands correctly.
