### ISSUE TITLE
Folding - unpredictable behaviour

### ISSUE THREAD

**Issue by Fooeybar** [microsoft/vscode#108124]
Issue Type: <b>Bug</b>

Hiding or displaying code using the folding carets alongside the ruler has become unpredictable.

At any random time: 
   1) folding carets disappear from the vertical ruler
   2) code cannot be unfolded by adding text or clicking disappeared caret. Code behaves as if the folded section does not       exist
   3) unrelated code sections, or all folded code, unfolds itself

Restarting the editor has no visible effect.

Issue encountered while writing Javascript code.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (27.22GB free)|
|Process Argv|--crash-reporter-id e7e082e9-a3af-4323-9f90-8920e8cb8d21|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
mq4|ner|1.0.4
java|red|0.68.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2

</details>

**Comment by aeschli** [comment]
If you have small samples with reproducible steps, that would allow me to investigate...

**Comment by Fooeybar** [comment]
I am unsure the steps required to reproduce the bug at will however it
consistently occurs when using vscode. I will update if I can find a
reproducible sequence.

It has been occurring while writing JS/node, from an opened folder, with
one or multiple files open side by side. Restarting vscode has no effect
and the bug can be present from the initial loading of vscode.

**Comment by uloga** [comment]
Same here folding issues!

**Comment by aeschli** [comment]
Sorry, I need code samples that allow me to reproduce the problem...
