### ISSUE TITLE
iPadOS: with attached keyboard there is a keyboard toolbar appearing still

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108111]
Steps to Reproduce:

1. use web version on iOS (iPad)
2. attach a keyboard
3. install as PWA (this is proabably optional)

=> whenever you put the cursor into the editor, a small keyboard related toolbar appears at the bottom with e.g. buttons to make the on-screen keyboard appear or actions to undo/redo. I am not sure how much control we have but would be great to disable this if possible.

//cc @egamma

**Comment by alefragnani** [comment]
Hi,

This was the first thing I tried to solve when opened Codespaces for the first time 😬 

This toolbar can be disabled in **Settings**. Navigate to `General / Keyboards` and turn off `Shortcuts`

![8A72BB74-DFF8-4F70-9CA9-21645693FDD6](https://user-images.githubusercontent.com/3781424/95270641-509f9000-0812-11eb-861a-6dd1a924e12d.jpeg)

Hope this helps

**Comment by bpasero** [comment]
Oh wow, thanks for explaining! Would be cool if this could be somehow defined by the page itself.

**Comment by alefragnani** [comment]
You're welcome!

My primary idea for Codespaces is to be able to use my iPad for development so, every pixel counts.

I hope Zen Mode and Debugging (popup window) to be fixed soon, so I could develop my VSCode extensions as well 😁 

Thank you

**Comment by bpasero** [comment]
@alefragnani I tried what you said but I still see some horizontal space reserved below the Codespace window on my iPad, are you getting a full window of Codespace on iPad on your device?

Nice to hear you use iPad with Codespace, if you see issues with it, feel free to create new issues here or ping on existing ones, we plan on improving iPad support in the near term.

**Comment by alefragnani** [comment]
Yep, full screen (no toolbar below).

When I found this _solution_, some people said to turn off **Predictive** option too (those _suggestions_ iOS shows above the keyboard). In my case, wasn't necessary. Maybe you could try that one too.

I'm using an iPad (7th Gen - 10.2 in), with the Smart Keyboard. 

Hope this helps

**Comment by alefragnani** [comment]
@bpasero,

Two of the issues I created for Codespaces are planned for October release 🎉. (#107386 and #106997)

There is one on _Backlog_ (#107543), and Zen Mode is _still not planned_ (#106972), but I noticed changes after I reported (now it does not enter on Zen Mode anymore).

Thank you, and congratulations for the great work 👍

**Comment by bpasero** [comment]
@alefragnani thanks, I can confirm that I get a good fullscreen experience when I also disable "Predictive" option. 

Will check out the issues you linked.
