### ISSUE TITLE
Editor: links are kept longer than needed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108162]
Steps to Reproduce:

1. open a large JSON file (https://github.com/json-iterator/test-data/blob/master/large-file.json)
2. close the file
3. run a snapshot

=> 🐛 `links.activeLinksList` has thousands of entries still

https://github.com/microsoft/vscode/blob/7506b2ba5ae3ee1052bff44d2f5129a61312b37b/src/vs/editor/contrib/links/links.ts#L118-L118

![image](https://user-images.githubusercontent.com/900690/95165857-236cc680-07ad-11eb-8aaa-95e27393eae1.png)

**Comment by bpasero** [comment]
I see that about 40 MB of retained size is only attributed to the links contribution. Removing it, I am down to 60 MB for that file and I see no retainers anymore after closing the editor that are of large size.

**Comment by alexdima** [comment]
Nice catch!

**Comment by jrieken** [comment]
Well, this isn't really a leak because this only holds on the last element, it doesn't accumulate over time
