### ISSUE TITLE
VSCode continues to mix syntax colors

### ISSUE THREAD

**Issue by HerryYT** [microsoft/vscode#108125]
![Screenshot (90)](https://user-images.githubusercontent.com/34418030/95101714-c6ccc580-0732-11eb-9da7-0660c0b022ce.png)

![Screenshot (91)](https://user-images.githubusercontent.com/34418030/95101960-11e6d880-0733-11eb-996a-c1cf04e8784f.png)

(in the picture above there is an example of the bug)

Steps to Reproduce:

1. Install VSCode and open a project (not for spam but debug purposes) on my page called JSPrismarine
2. write / edit some code

Does this issue occur when all extensions are disabled?: Yes, i also clean installed VSCode but still occurs with latest update

**Comment by HerryYT** [comment]
Maybe related to #108177

**Comment by mjbvz** [comment]
Please always share the text of the code along with screenshots

**Comment by TheArmagan** [comment]
it generally happens when working with liveshare plugin

**Comment by mjbvz** [comment]
Closing as more info is needed from original poster
