### ISSUE TITLE
Cannot Collapse Codes After Switch Editor on Mac

### ISSUE THREAD

**Issue by mahdi-farnia** [microsoft/vscode#108132]
- VSCode Version: 1.49.3
- OS Version: Mac OS Catalina 10.16.7

Steps to Reproduce:

1. switch editor
2. collapsed codes cannot opened untill make changes like press Enter

Does this issue occur when all extensions are disabled?: Yes

Issue Type: <b>Bug</b>

i can't collapse codes after make it close it, it seems like opener arrows are disappeared

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.69GB free)|
|Process Argv|--crash-reporter-id 3abd098e-8913-45d9-9e68-58217d58edc2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.3.1
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-rename-tag|for|0.1.4
go|gol|0.17.2
dotenv|mik|1.0.1
python|ms-|2020.9.112786
cpptools|ms-|1.0.1
vsliveshare|ms-|1.0.2902
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.11
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|syl|1.8.12
vscode-icons|vsc|11.0.0
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by aeschli** [comment]
I'm not able to reproduce. With what language is that? Do you have a code sample where this shows?
