### ISSUE TITLE
PHP false-errors

### ISSUE THREAD

**Issue by CarterSnich** [microsoft/vscode#108153]
Issue Type: <b>Bug</b>

After updating, I get some errors on my PHP codes.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G (4 x 1797)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|10.95GB (6.62GB free)|
|Process Argv|--crash-reporter-id 4c1499bf-d270-4e07-8a17-d1a4550cae79|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-custom-css|be5|4.0.0
vscode-intelephense-client|bme|1.5.4
node-snippets|chr|1.2.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.37.1
vscode-npm-script|eg2|0.3.13
code-runner|for|0.11.0
electron-debug|kod|18.11.1
node-module-intellisense|lei|1.5.0
background-cover|man|2.2.4
python|ms-|2020.9.112786
vetur|oct|0.28.0
selectline-statusbar|tom|0.0.2
vscode-icons|vsc|11.0.0
material-theme|zhu|3.9.2
html-css-class-completion|Zig|1.19.0

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
This is most likely an extension issue. If not, please give more details
