### ISSUE TITLE
"Collapse All" does not show up in search results

### ISSUE THREAD

**Issue by aybiss** [microsoft/vscode#108161]
Issue Type: <b>Bug</b>

Where is it?

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (19.60GB free)|
|Process Argv|--crash-reporter-id 3deaf030-47b6-4d3e-8a79-dcdb566a36ea|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: W50567|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz (48 x 3001)|
|Memory (System)|127.90GB (117.67GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: W50567|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz (48 x 3001)|
|Memory (System)|127.90GB (117.67GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: W50567|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz (48 x 3001)|
|Memory (System)|127.90GB (117.67GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
Bookmarks|ale|11.3.1
svn-scm|joh|2.12.4

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

It's either in Tabs row when in Panel or near to title when in Actions Bar
![image](https://user-images.githubusercontent.com/1312662/95211761-a0239300-07f5-11eb-899c-f44213ea469f.png)

Please provide screenshot if it's missing for you.

**Comment by aybiss** [comment]
Full disclosure, I had not even seen that button. But I was looking for an option when right clicking on the tree items, like a normal tree.

**Comment by IllusionMH** [comment]
> right clicking on the tree items, like a normal tree.

I've checked other trees (Explorer, SCM tree (Git), NPM Scripts, Outline, GitHub Pull Request) - they have Toggle collapse button in title row (except Git), but none of them have Collapse All in context menu, so it's unclear why it was expected in context menu.

/cc @JacksonKearl
