### ISSUE TITLE
The phenomenon that keyboard input becomes impossible 

### ISSUE THREAD

**Issue by akkb** [microsoft/vscode#108156]
Issue Type: <b>Bug</b>

The phenomenon that keyboard input becomes impossible frequently occurs.
Line breaks and deletions cannot be made by pressing the enter key or backspace key.
Of course, I can't type.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (22.21GB free)|
|Process Argv|--crash-reporter-id 7a432767-109a-46f8-abce-36482b09ae88|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ja|MS-|1.49.1
LiveServer|rit|5.6.1
vim|vsc|1.17.1

</details>

**Comment by aiko-koba** [comment]
solition forthat issue.
To try restarting my laptop.

**Comment by JacksonKearl** [comment]
Can you tell if anything you do in the editor causes this to occur reliably? 

If not, does this happen in any other applications on your system?

**Comment by akkb** [comment]
Finally I solved that issue.
The issue is caused by  somethig extention perhaps.
So I deleted all extensions on my VSCode.
and then  I tried restarting your laptop.
