### ISSUE TITLE
Clicking on the edge of the SCM input box causes it to lose focus

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#108160]
I don't know why, but I often seem to click in a space in the input box that causes the focus to be lost.

![scm-input](https://user-images.githubusercontent.com/641685/95160361-5b084e00-076e-11eb-8279-830e0704e4bb.gif)

**Comment by joaomoreno** [comment]
I've added a click logger in devtools:

> e = window.addEventListener('click', e => console.log(e.target), true)

Which tells me it's `view-lines monaco-mouse-cursor-text` that's being hit. @alexdima shouldn't the editor take that as a focus intention? Here's what I found when debugging, notice all the `false` values:

![image](https://user-images.githubusercontent.com/22350/95210097-69487f80-07eb-11eb-864b-fba4d183fd8d.png)

When clicking right in the middle of the editor content area I get `targetIsContent` as `true`. But when hitting `view-lines`, everything is declared as false.
