### ISSUE TITLE
Duplicate entries in the terminal drop-down

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#108137]
Using codespaces PPE with insiders:

![image](https://user-images.githubusercontent.com/4674940/95111982-2906d580-06f5-11eb-860f-aa0d8f9be173.png)

**Comment by connor4312** [comment]
cc @sandy081 -- maybe disabled state for built-in extensions is not synced?

**Comment by sandy081** [comment]
It is synced, but Codespaces currently has an issue that it initialises with different Settings Sync Service. Could be because of that. So this shall be fixed with latest bits.
