### ISSUE TITLE
integrated terminal tab can`t move

### ISSUE THREAD

**Issue by moderationvirtue** [microsoft/vscode#108129]
Issue Type: <b>Bug</b>

* I can`t move integrated terminal tab when typescript build task error occures
* tasks.json
``` json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "option": "watch",
      "problemMatcher": ["$tsc-watch"],
      "group": "build",
      "label": "tsc:watch",
      "isBackground": true,
      "presentation": {
        "echo": true,
        "reveal": "silent",
        "focus": true,
        "panel": "shared",
        "showReuseMessage": true,
        "clear": true
      }
    }]
}
```

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (1.47GB free)|
|Process Argv|--crash-reporter-id b9573970-1468-49e9-b393-1c47a4f908d6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (82)</summary>

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
