### ISSUE TITLE
VScode ignores nested gitignore

### ISSUE THREAD

**Issue by DutchJelly** [microsoft/vscode#108172]
- VSCode Version: 
    ```
    1.49.3
    2af051012b66169dde0c4dfae3f5ef48f787ff69
    x64
    ```
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Add a nested .gitignore, relative to your .git folder.
2. (Maybe use WSL)
3. Try to .gitignore node modules, it will still show up as unstaged in the changes list.

Just to be clear: git totally works fine if I use it through any terminal like bash (wsl) or powershell. I can safely use `git add *` without staging my 3069 node modules. VSCode, for some reason, still wants me to stage them.

The `.gitignore` *does* work if I simply place it in the root of the vscode folder, but this is is not an option for the project I'm working on, because I have to seperate the `.gitignore`'s in the frontend and backend. I'd also like to see them both in my vscode, so I want to open vscode in the root folder of the entire project.

![image](https://user-images.githubusercontent.com/20456306/95184555-d0ecd380-07c7-11eb-96d2-a755dfa59ba0.png)

**Comment by joaomoreno** [comment]
Can you give me more specific steps? Eg (1) Init repo, (2) run `npm install bla`, (2) create `.gitignore` in _this_ folder, etc. I'd like to be able to reproduce locally.

**Comment by DutchJelly** [comment]
1) git init
2) make a folder `project`
3) go in the folder
4) make a vue project with vue-cli in a folder called 'frontend'
5) add a gitignore that contains node_modules/ to that 'frontend' folder with the vue project in it
6) open vscode at the root of the git repository
7) All node modules should be listed, even though there's a `.gitignore`

My command line's git was working fine. 

When I modify one file, my git status tells me:
```
modified:   project/frontend/pages/test.vue
```
However, my vscode also lists the node modules as changed:

![image](https://user-images.githubusercontent.com/20456306/95454818-3c23da80-096d-11eb-9b81-3ae5dc700594.png)

I hope this is reproducable now. I'm not very experienced with node, so that's why I just told you exactly what I did instead of the minimum example.

**Comment by joaomoreno** [comment]
From your screenshot, it appears `node_modules` is at the root of the git repository, not inside `frontend`. Did you by accident run `git init` inside the `frontend` folder?

**Comment by DutchJelly** [comment]
Oh I think one of my teammates ran `git init` in the root folder for tailwindcss. Thanks for your time, that was the issue.
