### ISSUE TITLE
Limited Memory Usage

### ISSUE THREAD

**Issue by SnowPrimate** [microsoft/vscode#108148]
In any project, vscode memory usage is limited to a very low amount. I believe that it is set to 512mb. I have checked that a Windows 10 Pro edition has physical memory usage limit to above 128GB and I have 32GB RAM installed. I would like to know if I should be having a better performance.
![image](https://user-images.githubusercontent.com/6299375/95147485-45d3f500-0757-11eb-86bf-9f70a293ced7.png)

**Comment by SnowPrimate** [comment]
@deepak1556 Hey deepak, any news on this? @JacksonKearl Issue hasn't been solved yet.

**Comment by deepak1556** [comment]
Can you provide the chrometrace.log following the below steps,

* Create trace.json somewhere on your disk with the following content:
```
{
 "result_file": "<some-absolute-writable-path>\chrometrace.log",
 "trace_config": {
 "record_mode": "record-until-full",
 "included_categories": [
     "blink",
     "browser",
     "io",
     "latency",
     "benchmark",
     "disabled-by-default-memory-infra"
 ],
 "excluded_categories": ["*"]
 }
}
```
* Start code --trace-config-file="\trace.json"
* Use vscode for a while as normal
* Quit the editor

**Comment by SnowPrimate** [comment]
Okay, so, I was unable to start code through git bash, ran it through cmd with the command >start --trace-config-file="\trace.json"
it did not create a chrometrace.log on the path I specified. Sorry for the delay.

**Comment by SnowPrimate** [comment]
@deepak1556 issue is still going on!

**Comment by deepak1556** [comment]
Sorry missed your last comment, there is an error in the command line passed `code --trace-config-file="\trace.json"` is incorrect, it should be `code --trace-config-file="<absolute-path-to>\trace.json"`

**Comment by SnowPrimate** [comment]
No problem! Here you go!
[chrometrace.log](https://github.com/microsoft/vscode/files/5895555/chrometrace.log)

**Comment by SnowPrimate** [comment]
@deepak1556 Hey there! Any idea on the solution?
