### ISSUE TITLE
VSCode Portable-Mode won't start (Windows Server 2012R2)

### ISSUE THREAD

**Issue by Marco-Leal** [microsoft/vscode#108191]
VSCode Version: 1.49.3 64bits
OS: Windows Server 2012R2

I installed the standard VSCode version to my work-machine. This worked but the installation folder is in the C: drive which doesn't keep newly installed programs after the session ends.

I then tried to install VSCode Portable-Mode to my U: drive which does save changes. To do this I followed the steps listed here: https://code.visualstudio.com/docs/editor/portable#_migrate-to-portable-mode

Afterwards I tried to start Code.exe (also as Administrator) but it simply doesn't do anything (nothing visible at least).

**Comment by joaomoreno** [comment]
> Afterwards I tried to start Code.exe (also as Administrator) but it simply doesn't do anything (nothing visible at least).

Can you try to launch it from a command prompt? `code --verbose`

**Comment by Marco-Leal** [comment]
When I run ./Code.exe --verbose on Git Bash I get this error:

socket: (10022) An invalid argument was supplied.

**Comment by joaomoreno** [comment]
Can you try from Command Prompt? Also, show me a screenshot of that error.

**Comment by Marco-Leal** [comment]
I tried it in cmd as well. It doesn't output anything to the console and also doesn't launch any application. You'll find screenshots of both attempts attached. The error code you see in Git Bash translates to what I wrote in my previous comment.

![code_verbose_cmd](https://user-images.githubusercontent.com/23037727/95460276-07b41c80-0975-11eb-92d2-4cbf1bab2677.PNG)
![code_verbose_gitbash](https://user-images.githubusercontent.com/23037727/95460285-0b47a380-0975-11eb-97d5-2e54b578ff8d.PNG)

**Comment by joaomoreno** [comment]
Does it work without portable mode?

**Comment by Marco-Leal** [comment]
As I said in my opening post, it did work when I installed the normal version to the C:\ drive. Is that what you meant?

I'm not sure which folder you're referring to when you say portable. I couldn't find any folder named portable on my U: drive. Do you mean the data folder that I created manually? or maybe the actual Desktop/VSCode folder where I unpacked the .zip file? Anyway, I tried renaming both but it didn't help. Same output as before both in cmd and in Git Bash.

**Comment by Marco-Leal** [comment]
Update: I copied the content of the folder where I installed the portable version (on U:) to where the normal version would have been installed (C:...\AppData\Local\Programs\Microsoft VS Code) and it works from there, both with and without the data folder. It doesn't seem therefore to have much to do with the content of the portable version, just with the location.

FYI: there doesn't seem to be any general restriction to installing portable software on this drive. I have installed the portable versions of Git-Bash, Sublime and Notepad++ and they all work fine there.

**Comment by joaomoreno** [comment]
> Portable mode is supported on the ZIP download for Windows, and the TAR.GZ download for Linux, as well as the regular Application download for macOS. See the Download page to find the correct .zip / .tar.gz file for your platform.
>
> Note: Do not attempt to configure portable mode on an installation from the Windows User or System installers. Portable mode is only supported on the Windows ZIP (.zip) archive. Note as well that the Windows ZIP archive does not support auto update.

https://code.visualstudio.com/docs/editor/portable

It seems you tried to create a portable mode from an installed VS Code. Please use the ZIP download instead.

**Comment by Marco-Leal** [comment]
Yes, I did try that at first because as you can see in the page I linked to, the documentation says it should be possible to migrate an installed VS Code to a portable one by following the instructions.

Regardless, I have in the meantime already tried to completely remove the installed VS Code (including deleting %UserFolder%\AppData\Roaming\Code  and %UserFolder%\.vscode) and then using the ZIP download only and manually creating the data folder. Still didn't work.

The only information I have is this socket (10022) error. Is that not relevant at all?

**Comment by joaomoreno** [comment]
> the documentation says it should be possible to migrate an installed VS Code to a portable one by following the instructions

No, the documentation explicitly says:

> Note: Do not attempt to configure portable mode on an installation from the Windows User or System installers. Portable mode is only supported on the Windows ZIP (.zip) archive. Note as well that the Windows ZIP archive does not support auto update.

---

Is there anything inside the `data` folder, after you attempted to execute VS Code?

**Comment by joaomoreno** [comment]
Just saw you are running Windows Server 2012 R2, which we do not officially support. That socket error could very well point to the OS limitation that prevents Electron from running in that platform.
