### ISSUE TITLE
Quick Fixes not showing

### ISSUE THREAD

**Issue by Srbaxter52** [microsoft/vscode#108121]
Issue Type: <b>Bug</b>

I am trying to deal with statement obsoletion by Microsoft. 
https://dynamicsuser.net/nav/b/demiliani/posts/dynamics-365-business-central-obsoleting-the-with-statement

In the documentation here, it shows that quick fixes have been added by Microsoft.  I don't know if I am doing something wrong, but I am not getting any options for quick fixes. The error shows up when I hover and I can peek, but quick fix doesn't show anything. I am not sure If I am missing something or not.  I have tried ctrl+. but it still tells me no actions found.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz (1 x 2195)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (13.81GB free)|
|Process Argv|--crash-reporter-id c6fa4467-e963-4342-87a6-d5de876f9009|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
advaniagit|adv|1.1.3
al|ms-|6.0.344420

</details>

**Comment by jrieken** [comment]
What language and extension do you use for that language?

**Comment by Srbaxter52** [comment]
I am using the AL extension that is provided by Microsoft for this.

Kind regards,

Sam Baxter
Developer
[cid:image001.jpg@01D69B07.0BC514F0]

Cost Control Software
12409 Old Meridian Street, Carmel, IN 46032
TEL 317-846-6025  CELL 317-525-2738
www.costcontrolsoftware.com<www.albrechtsolutions.com>

**Comment by jrieken** [comment]
Ok, then please file this issue against that extension. It's not part of the VS Code core bundle
