### ISSUE TITLE
GotoLine

### ISSUE THREAD

**Issue by stackerJobs** [Microsoft/vscode#10815]
- VSCode Version: 1.4.0
- OS Version:win10

I am writing a extension and I want to achieve the function 'gotoline' with a linenum  ,and I just found a command named "workbench.action.gotoline" but not a API , what should I do ,
Any help will be appreciated.

**Comment by sandy081** [comment]
@stackerJobs there is an API in vscode for extension writers to go to a line in the editor

``TextEditor.selection``

This will set the cursor (position/selection) at the required line

**Comment by stackerJobs** [comment]
It works !Thank you !
