### ISSUE TITLE
Snippets: move off iterating over file changes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108164]
With the introduction of ternary search tree to file events, I went ahead and deprecated the access to the raw `changes` array given that we have now a more efficient method in place (`contains`).

I noticed 2 usages in snippet land:

https://github.com/microsoft/vscode/blob/7f3b2e575c4a9f52639b0fa33c0d7afdfa2a8673/src/vs/platform/userDataSync/common/snippetsSync.ts#L55-L55

https://github.com/microsoft/vscode/blob/28cb90be8c65ed4fc54622297e2508e75684f138/src/vs/workbench/contrib/snippets/browser/snippetsService.ts#L119-L119

What is needed for you to use the `contains` method here? I think your requirement is to have `isEqualOrParent` for all file changes? Should the file changes event expose a method for that purpose? Currently it will only `isEqualOrParent` for the delete change type.

**Comment by jrieken** [comment]
Adding @sandy081  for `snippetsSync`

**Comment by sandy081** [comment]
I think the common use case is to check if any of the files (snippets) under snippets folder has changed. If the event can provide that info, I am fine with that.

**Comment by bpasero** [comment]
@sandy081 @jrieken in [`ben/file-changes-containsChildren`](https://github.com/microsoft/vscode/tree/ben/file-changes-containsChildren) I added a new method `containsChildren` which is almost identical to `contains` except that it will check for children of the provided resource, i.e. returns true if any resource is a child of the given one and included.

I am open for suggestions about names and behaviour, e.g. currently `containsChildren` will not return `true` if you pass in the resource that is part of the event, it has to be a child. So maybe in some cases you need to call both `contains` and `containsChildren` to get both.

**Comment by sandy081** [comment]
So `event.contains(resource) || event.containsChildren(resource)` === `isEqualOrParent(change, resource)`  ?

If so, it makes sense to me.

**Comment by bpasero** [comment]
@sandy081 yes exactly! I was not able to come up with an equivalent of `isEqualOrParent` for a single method...

**Comment by jrieken** [comment]
> I was not able to come up with an equivalent of isEqualOrParent for a single method...

For events, I like `affects`, e.g `e.affects(resource)` and then I know that have to do something

**Comment by bpasero** [comment]
I like that and pushed to `master`:
* `contains`: will match on the resource
* `affects`: will match on the resource or any child of that resource
