### ISSUE TITLE
Expose output from executable debug adapter

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#108145]
When I return a `DebugAdapterExecutable` from `DebugAdapterDescriptorFactory.createDebugAdapterDescriptor`, the debug adapter that VSCode creates (`ExecutableDebugAdapter`) spawns a child process, but does not expose stderr of that process in any way.

VSCode should provide a way for extensions to act on stderr of the process spawned by ExecutableDebugAdapter.

This is somewhat related to #98976.

**Comment by connor4312** [comment]
Did you run into an issue with the solution proposed in https://github.com/microsoft/vscode/issues/108138#issuecomment-703929096?

**Comment by firelizzard18** [comment]
The existence of `DebugAdapterExecutable` in `index.d.ts` implies that extensions should be able to use it. I think it is reasonable to expect to act on output from the executable spawned by returning a `DebugAdapterExecutable`, so I created an MR to enable that. The MR template indicated that every MR is required to have a corresponding issue, so I created one.

**Comment by weinand** [comment]
@firelizzard18 what is your use case for this request?
The contract between VS Code and DAs does not use stderr.
So your PR #108146 basically introduces a new private communication channel between an extension and a DA - but only for DAs available as executables.

**Comment by firelizzard18** [comment]
@weinand My use case is https://gitlab.com/firelizzard/vscode-byebug, specifically [`ByebugAdapterDescriptorFactory`](https://gitlab.com/firelizzard/vscode-byebug/-/blob/master/src/extension.ts#L103). `ExecutableDebugAdapter` is perfect for my purposes:

- I have a debug adapter (written in Ruby, for Ruby programs) that fully supports DAP, and thus the extension doesn't need to implement *anything* except startup.
- The DA supports stdin/stdout communications, which is ideal because I don't need to pollute user systems with unnecessary sockets.
- `ExecutableDebugAdapter` handles all of this, except failures.

The last point is especially problematic, because I don't have access to `ExecutableDebugAdapter` (and I'm not likely to get it: #108138) - all I can do is return a `DebugAdapterExecutable`.

If everything goes well, I return a `DebugAdapterExecutable` that launches `byebug-dap --wait --stdio <program> <args>` (or `bundle exec byebug-dap <...>`), and everything works perfectly. However, `DebugAdapterExecutable` does nothing to capture stderr. If the program argument is invalid, the debugger tracker will see `ENOENT` and a path, which is useful. But if `bundle` exists but it can't find `byebug-dap`, all I get is "exited with code 127", and zero information.

Beyond that, sometimes my extension has bugs (e.g. passing the wrong options) or the DA has bugs, and I want to show that error output *somewhere*. But `DebugAdapterExecutable` doesn't capture it at all.

I suppose a workable middleground would `DebugAdapterStdio`/`StdioDebugAdapter`, but I'd rather leave the child process handling to `ExecutableDebugAdapter`.

**Comment by weinand** [comment]
I think we have two options to proceed:
- the DA could send internal error messages as [`Output` events](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Output) with category "console". Those would appear in the debug console and are rendered differently from the debuggee's "stdout" or "stderr".
- VS Code could read stderr of a "ExecutableDebugAdapter" and send it to an "Output" log channel (either the "Extension" or a dedicated "Debug Adapter" log channel).

@isidorn @firelizzard18 what do you think?

**Comment by isidorn** [comment]
No preference. Option 1 sounds pretty straighforward and it could be tried our with no changes to VS Code.

**Comment by firelizzard18** [comment]
@weinand In either of those cases, would my extension be able to process and act on the output? It's been a while since I dug into it, but I'm unsure how your recommendations would allow my extension to capture the output. My primary interest is in converting [`ByebugAdapterDescriptorFactory.
createDebugAdapterDescriptor`](https://gitlab.com/firelizzard/vscode-byebug/-/blob/master/src/extension.ts#L121-211) in my extension into an implementation based on `ExecutableDebugAdapter`. Using `DebugAdapterNamedPipeServer` is an imperfect solution that allows me to reuse existing DA implementations while still reacting to failure modes. But it requires creating a Unix pipe, which I'd rather not do since the underlying DA supports STDIO-mode.

Showing the output to the user would be better than nothing, but I still want to be able to parse the output to provide the user with useful error messages such as, "Debugging failed because you are missing a essential dependency. Here's how to remediate the situation." Instead of "bundler: command not found: byebug-dap".

**Comment by DaanDeMeyer** [comment]
When using the vscode-clangd extension, I get all its stderr output in a separate output window 

![image](https://user-images.githubusercontent.com/9395011/102717029-f88c0c00-42df-11eb-968b-1e2a9fa3bd29.png)

I'd like to be able to provide the same from my debugger extension using a debug adapter.

**Comment by eliphatfs** [comment]
I just ran into similar situations. I would love the stderr exposure very much, as well as logging for internal errors such as executable file not exist due to environment/typos etc.

**Comment by Trass3r** [comment]
Ran into similar problems. The C++ debug adapter didn't start up cause of dependency issues. In the UI you only see the debug session shortly starting and stopping, nothing in the console or any of the output windows. See https://github.com/microsoft/vscode-cpptools/issues/9463.

**Comment by roblourens** [comment]
I don't think this makes sense in the context of DAP and DA's in general. I don't like adding something to the DA tracker which is linked to stderr from a particular process.

Something else that throws me is that processes might log stuff to stderr as a separate channel which isn't an error and isn't really intended for display- that makes me nervous to even log it all in vscode's logs because it could just end up as spam.

**Comment by eliphatfs** [comment]
Please reason more about your claims. Why doesn't it make sense? Moreover, "don't like" is basically invalid for excluding a feature. It is much better to make it an option as others may "like" it.

For the spamming, why not use a separate output channel in the logs tab, as someone suggested above. Developers of debug adapters and users will be both happy with it.
