### ISSUE TITLE
Functions incorrectly marked as unreferenced

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#108167]
Issue Type: <b>Bug</b>

Given this code:
```js
const fs = require("fs");

return foo()
  .then(bar);

function foo() {
  return new Promise((resolve) => {
    resolve();
  });
}

function bar() {
}
```

VS Code will mark the functions `foo` and `bar` as unused:

![image](https://user-images.githubusercontent.com/1658949/95179430-e7436100-07c0-11eb-88b4-398ef4ff7d4d.png)

Making apparently random code changes can partially resolve the situation or make it worse again.

Commenting out the `require` statement will result in both functions being detected as being used. Reverting the change also marks the functions as unused again.

Sometimes only `bar` is considered unused.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (42.09GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/static2 --remote=wsl+Ubuntu --crash-reporter-id f825acfe-92fa-4526-a38a-f8815cf9f7ea|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (42.51GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (42.51GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (42.51GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (42.51GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.8
javascript-ejs-support|Dig|1.3.1
xml|Dot|2.5.1
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.1
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
terraform|has|2.2.3
vscode-drawio|hed|1.0.0
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
code-beautifier|mic|2.3.3
vscode-puglint|mrm|2.3.0
vscode-docker|ms-|1.6.0
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
vscode-paste-image|mus|1.0.4
vscode-yaml|red|0.11.1
lit-plugin|run|1.2.1
language-pde|Tob|1.4.6
vscode-icons|vsc|11.0.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
That code is not valid JS; you can't have a top level return statement in a file

To see this error, [enable semantic checking](https://code.visualstudio.com/Docs/languages/javascript#_type-checking)
