### ISSUE TITLE
no such file or directory in C++

### ISSUE THREAD

**Issue by Programmer12138** [microsoft/vscode#108152]
Issue Type: <b>Feature Request</b>
I wrote include<Python.h> in my C++ code, and I'm sure track of this file is in the include path. Still, VScode shows '<Python.h> no such file or directory'. Could you please tell me how to solve this problem?
Best Wishes.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18363

**Comment by JacksonKearl** [comment]
\extC++
