### ISSUE TITLE
Poor setting search order for when searching for "color theme"

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#108163]
Issue Type: <b>Bug</b>

**Repro**
1. In the settings, search for `color theme`

**Bug**
The `Workbench: color theme` setting is 4th in the results, behind 3 much more advanced settings:

<img width="1308" alt="Screen Shot 2020-10-06 at 12 07 58 AM" src="https://user-images.githubusercontent.com/12821956/95169757-3c9f5400-0768-11eb-82ab-da45e3ff6d5b.png">

VS Code version: Code - Insiders 1.50.0-insider (66b696427273f5d4711cf37a48b57594074f4ee3, 2020-10-05T19:20:05.037Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|32.00GB (2.31GB free)|
|Process Argv|-psn_0_65986282 --crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|10%|
</details>

**Comment by roblourens** [comment]
These are all literal (local) matches which don't have any relevance sorting currently.
