### ISSUE TITLE
Problems listed in the debug console for excluded files

### ISSUE THREAD

**Issue by PaulSwarthout** [microsoft/vscode#108133]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Create a PHP file with a syntax error.
2. Save it.
3. Note the red highlighting of the file name and all the parent folders indicating the presence of a syntax error.
4. Open the Debug Console. Note the "Problems" heading. It shows how many problems exist in the red highlighted file.
5. Open VS Code settings. Exclude the file which has syntax errors.
6. Note that the file no longer appears in the folder list in the Explorer tab.
7. Return to the debug console. Note that the count of the problems remains the same.

Excluding files from the project should stop them from being parsed, and therefore no parent folder red highlighting and no display of the number of problems in the debug console.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.26GB free)|
|Process Argv|--crash-reporter-id 4a8c61d7-f6d3-495d-9576-c69834d93045|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14

</details>

**Comment by sandy081** [comment]
We always show the complete count of all problems generated by the extension. If you do not want problems not to be created for excluded files, please file an issue against the extension.
