### ISSUE TITLE
Many rg.exe processes are spawned

### ISSUE THREAD

**Issue by cveld** [microsoft/vscode#108101]
Issue Type: <b>Bug</b>

1. Clone https://github.com/Azure/azure-sdk-for-js
2. Switch between branches
3. Vscode spawns many rg.exe processes to scan the new TypeScript files

![image](https://user-images.githubusercontent.com/6196260/95061438-e5fc3080-06fb-11eb-807e-953955e548b1.png)

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (18.68GB free)|
|Process Argv|--crash-reporter-id 65a0e614-bdb1-4091-82f4-9edc2229188d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
terraform|4op|0.1.10
ng-template|Ang|0.1001.0
path-intellisense|chr|2.3.0
angular-schematics|cyr|4.3.0
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|2.1.8
angular-extension-pack|dog|9.3.0
githistory|don|0.6.11
EditorConfig|Edi|0.15.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.1
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
json2ts|Gre|0.0.6
angular2-switcher|inf|0.3.3
svelte-vscode|Jam|0.9.3
plantuml|jeb|2.13.13
docthis|joe|0.7.1
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.8.0
refactorix|kri|0.3.6
angular-extension-pack|loi|0.7.1
Angular2Tests|Mar|0.7.3
json-to-ts|Mar|1.7.5
xslt-action|mar|0.0.2
Angular-BeastCode|Mik|10.0.3
vscode-azurefunctions|ms-|0.24.1
vscode-azureterraform|ms-|0.3.1
vscode-docker|ms-|1.6.0
vscode-logicapps|ms-|0.2.52
csharp|ms-|1.23.2
dotnet-interactive-vscode|ms-|1.0.150105
vscode-dotnet-runtime|ms-|0.1.2
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.3
cpptools|ms-|1.0.1
js-debug-nightly|ms-|2020.9.2817
powershell|ms-|2020.6.0
typescript-javascript-grammar|ms-|0.0.53
vscode-github-issue-notebooks|ms-|0.0.52
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2902
azurerm-vscode-tools|msa|0.12.0
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
fast-code-review|nan|0.3.0
angular2-inline|nat|0.0.17
ng-fortytwo-vscode-extension|NG-|0.0.9
gremlins|nho|0.23.1
angular-console|nrw|14.0.0
arrr|obe|0.1.3
material-icon-theme|PKi|4.3.0
language-plantuml|qho|0.0.3
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
java|red|0.68.0
angular-follow-selector|san|1.2.0
markdown-preview-enhanced|shd|0.5.13
simontest|Sim|1.9.0
autoimport|ste|1.5.3
move-ts|str|1.12.0
vscode-xslt|szu|0.2.0
Angular2|UVB|0.4.1
vscodeintellicode|Vis|1.2.10
vscode-arduino|vsc|0.3.2
vscode-iot-device-cube|vsc|0.3.0
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-wakatime|Wak|4.0.8
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Does this happen if you start with `--disable-extensions`?

**Comment by cveld** [comment]
@roblourens Yes with extensions disabled the problem does not appear.

**Comment by roblourens** [comment]
From the command line you can get a hint from what it's looking for, in this case, .ts/.tsx files. You can get more hints with these steps to get logs for search


- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)
