### ISSUE TITLE
Mouse over a variable + ctrl key pressed output panel pops up

### ISSUE THREAD

**Issue by hiredtocode** [microsoft/vscode#108114]
- VSCode Version: 1.49.3 (system setup)
- OS Version:  Windows_NT x64 10.0.19041

Steps to Reproduce:

I've recorded my screen to explain this bug. Please view it at:  https://youtu.be/irbWUR09_2Y

and here's the code to help you reproduce this bug.
```
const questions = [
  {
    question: "What is 10 + 10?",
    options: ["8", "20", "28", "30"],
    answer: "20"
  },
  {
    question: "What is Athena's favoirt animal?",
    options: ["jellyfish", "penguins", "otters"],
    answer: "otters"
  },
]

let question_number = 0;
let correct = 0;

document.addEventListener( 'DOMContentLoaded', () => {
  load_question();
} );

function load_question () {
  document.querySelector( '#question' ).innerHTML = questions[question_number].question;
  const options = document.querySelector( '#options' );
  options.innerHTML = '';
  for ( const option of questions[question_number].options ) {
    options.innerHTML += `<button class="option">${ option }</button>`;
  }

  let answer = questions[question_number].answer;
  let counter = document.querySelector( '#correct' );
  let questionCount = questions.length

  document.querySelectorAll( '.option' ).forEach( option => {
    option.onclick = () => {
      if ( option.textContent === answer || question_number < questionCount) {
        question_number++;
        correct++;
        counter.innerHTML = `${correct} of ${question_number}`;
        load_question();

      } else if (option.textContent !== answer || questionCount < question_number) {
				question_number++;
				counter.innerHTML = `${correct} of ${question_number}`;
				load_question();
			} else {
				console.log('done');
			}
    }
  });
}
```
Please let me know if you need more information. Thanks.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mocktarissa** [comment]
The reason why this is happening is that your Output panel is on CSS peek. According to the CSS peek creator:

> 'This extension extends HTML and ejs code editing with Go To Definition and Go To Symbol in Workspace support for css/scss/less (classes and IDs) found in strings within the source code'

 So basically it not designed to work inside a Javascript file. You can create an issue in the [Css Peek Repo](https://github.com/pranaygp/vscode-css-peek/issues) and make a feature request so that it automatically ignores js files.

**Comment by hiredtocode** [comment]
@mocktarissa Super! I've tested by disabling CSS peek and you're correct. Thank you!
