### ISSUE TITLE
Git integration stopped working

### ISSUE THREAD

**Issue by bendelonlee** [microsoft/vscode#108139]
- VSCode Version: Version: 1.49.3

- OS Version:10.15.7 

Whether I open from VSCode or from the terminal, whether the project I've been working on or a text example project that's empty with a .git file, VSCode does not recognize that the project folder is a git directory. 

Git integration has been fine until now, and I can't imagine what I did that may have sparked the change, aside from upgrade the latest version of Catalina.

Have tried fully uninstalling and reinstalling VSCode.

Does this issue occur when all extensions are disabled?: Yes/No

Yes.

**Comment by joaomoreno** [comment]
Can you open `Developer: Toggle Developer Tools`. Any errors there?

How about `Git: Show Git Output`?

**Comment by bendelonlee** [comment]
After restarting my computer, the issue resolved itself. I have no idea why.
