### ISSUE TITLE
Tab button not working as expected

### ISSUE THREAD

**Issue by PrashantChaurasiya-WellSky** [microsoft/vscode#108183]
Issue Type: <b>Bug</b>

After recend updated of VS code, open any file say file.ts ( with .ts extension ),
and click on tab button. Tab is not working as expexted

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.75GB free)|
|Process Argv|--crash-reporter-id 75cd3f8b-4de0-4077-bceb-3cd1c0f31e33|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
add-reference|adr|1.0.2
csharp-to-typescript|adr|1.12.1
libman|adr|1.0.1
namespace|adr|1.1.2
terminal-commands|adr|1.0.5
user-secrets|adr|2.0.1
vscode-javascript-snippet-pack|aka|0.1.6
vscode-sqlite|ale|0.9.0
jest-snippets|and|1.8.0
simple-react-snippets|bur|1.2.3
gitignore|cod|0.6.0
netcore-extension-pack|dog|1.4.0
githistory|don|0.6.11
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
git-project-manager|fel|1.7.1
auto-close-tag|for|0.5.8
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.4
autofilename|Jer|0.1.3
Angular2|joh|9.1.2
csharpfixformat|Leo|0.0.84
vscode-azureappservice|ms-|0.19.0
vscode-azurefunctions|ms-|0.24.1
vscode-azurestorage|ms-|0.10.1
vscode-cosmosdb|ms-|0.15.0
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
azure-account|ms-|0.9.3
azurecli|ms-|0.5.0
debugger-for-chrome|msj|4.12.11
sqltools|mtx|0.23.0
vscode-jest|Ort|3.2.0
LiveServer|rit|5.6.1
autoimport|ste|1.5.3
nextflow-mean-stack-for-dotnet-developer-pack|tee|0.0.2
msbuild-project-tools|tin|0.3.8
html-validate-vscode|Tob|0.2.0
vscode-icons|vsc|11.0.0
vscode-proto3|zxh|0.4.2

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What does "Tab is not working as expexted" mean?

Most likely you've switches Tab mode. See https://github.com/microsoft/vscode/issues/107867#issuecomment-702030664

**Comment by mjbvz** [comment]
Closing as not actionable without more information
