### ISSUE TITLE
bug occur when filte extension

### ISSUE THREAD

**Issue by HOLL4ND** [microsoft/vscode#108154]
Issue Type: <b>Bug</b>

i want to filte the extension i had install but everytime i open the filter and select time as the restrictions, and then it just stuck. so i have to restart the vscode

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.14GB free)|
|Process Argv|F:\CS188Python\tutorial2018 --crash-reporter-id 50920c73-a5ca-4732-a590-28a7017706df|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.61
c-cpp-project-generator|dan|1.2.1
vscode-markdownlint|Dav|0.37.1
code-runner|for|0.11.0
latex-workshop|Jam|8.13.2
MagicPython|mag|1.1.0
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.49.2
csharp|ms-|1.23.2
python|ms-|2020.9.112786
vscode-pylance|ms-|2020.9.8
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
cpptools|ms-|1.0.1
material-icon-theme|PKi|4.3.0
latex-support|tor|3.2.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.10
clang-format|xav|1.9.0
material-theme|zhu|3.9.2

(1 theme extensions excluded)

</details>

**Comment by HOLL4ND** [comment]
![](https://github.com/HOLL4ND/Picture/blob/main/packet%20switching%2002example.gif?raw=true)

**Comment by HOLL4ND** [comment]
somtimes,the first time i open wouldn't trigger the problem but the second time,windows say it no longer responding.i uninstall the      
extension-- Chinese Language Pack ,but the problem still there

**Comment by sandy081** [comment]
I cannot reproduce this. Can you please try this by disabling all installed extensions?

If it is still reproducible - please follow these instruction and provide us the performance profile - https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process
