### ISSUE TITLE
Adds "SupportCancel" text after pasting from clipboard

### ISSUE THREAD

**Issue by PatrickGoettsch** [microsoft/vscode#108231]
Issue Type: <b>Bug</b>

When I copy text from web into a text document the string "SupportCancel" is added afterwards. This string is not part of the copied text.

VS Code version: Code - Insiders 1.50.0-insider (0c50e1db17168a738235bd7e5c02b9f05ea5df59, 2020-09-30T06:53:41.824Z)
OS version: Windows_NT x64 10.0.19041

**Comment by JacksonKearl** [comment]
Is this from a specific website? Some sites have javascript to override what gets put into your clipboard.

**Comment by PatrickGoettsch** [comment]
It happens, if I copy bibtex code from google schoolar to cite papers like this:
https://scholar.googleusercontent.com/scholar.bib?q=info:OWaAJ65530IJ:scholar.google.com/&output=citation&scisdr=CgUHYlz0EO30y3lECug:AAGBfm0AAAAAX4VBEuhDKFC1HxD51BMLuiniIp2UagQT&scisig=AAGBfm0AAAAAX4VBEv2DPH2RsaI3tCu-WVZl9IkZFDwa&scisf=4&ct=citation&cd=-1&hl=en+

**Comment by PatrickGoettsch** [comment]
And this is plain text from what I see

**Comment by JacksonKearl** [comment]
It's likely that this is happening on the google side. Does it happen if you copy text from this github issue, for instance?

**Comment by mjbvz** [comment]
Do you see this when pasting into other apps, specifically ones that only take plain text instead of formatted text?

**Comment by PatrickGoettsch** [comment]
I pasted the code from  google schoolar into notepad++ and there the text also shows up. When pasting code from somewhere else it does not happen. So, I think this is not a vscode issue. Thanks
