### ISSUE TITLE
Hover over Multi-lines variable in debug after version 1.45

### ISSUE THREAD

**Issue by CJL-93** [microsoft/vscode#108215]
In either verion 1.46 or 1.47, the hover behavior was changed.

In 1.45, multi-lines variables would display like this when hovered over
![Screenshot 2020-09-18 095549](https://user-images.githubusercontent.com/72475913/95269348-d7e30880-07fe-11eb-99d8-bb30176f9a0d.png)

In 1.47, multi-lines variables would display like this when hovered over
![Screenshot 2020-09-15 123550](https://user-images.githubusercontent.com/72475913/95269425-f77a3100-07fe-11eb-88e8-7990d64f6651.png)

When I copy from the hover popup, it brings the \n with it and I can't paste and use it, I have to parse out hte \n firrst.

Is there already or can there be a setting to turn this back to the way it was?

Thank you
Corey

**Comment by connor4312** [comment]
This was an intentional change in normalizing how values are escaped in 1.46. As an alternative way to do this, you can enter `copy(SQL)` in the Debug Console, which will copy the string without escaping.

**Comment by CJL-93** [comment]
I agree that it was intentional and works as intended, I was hoping if it could be made optional defaulting to the new way.. 

Also,  the workaround does not work
copy (SQL) 
undefined

**Comment by CJL-93** [comment]
![image](https://user-images.githubusercontent.com/72475913/95279482-7039b700-0818-11eb-82cb-159bcc26e24a.png)

**Comment by connor4312** [comment]
It returns undefined, but the value is copied to your clipboard

**Comment by vchirikov** [comment]
it doesn't work with C# 
```
copy(result)
error CS0103: The name 'copy' does not exist in the current context
```

**Comment by connor4312** [comment]
`copy` is implemented by the debugger, it's not a native feature of VS Code. C# (apparently) does not implement it. However you can also right click + "copy value" in the Variables view in the sidebar, which is a common functionality.
