### ISSUE TITLE
typing speed

### ISSUE THREAD

**Issue by varun172121** [microsoft/vscode#108227]
Issue Type: <b>Bug</b>

very slow typing 

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:56:11.027Z)
OS version: Linux x64 5.4.0-48-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD E-350 Processor (2 x 1292)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|5.42GB (0.85GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 08799189-b6ec-4d40-bb2f-184716d98a72|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details>

**Comment by gjsjohnmurray** [comment]
Does this also happen if you disable the extension you are using?

**Comment by varun172121** [comment]
Yes

**Comment by thiago-tanaka** [comment]
Do you use any clipboard manager? if so, try disabling it.

**Comment by varun172121** [comment]
i dont use any clipboard manager

**Comment by JacksonKearl** [comment]
Is this a new issue with a recent update to vscode?

**Comment by varun172121** [comment]
i recently installed vscode so it is already a updated one

**Comment by JacksonKearl** [comment]
Please see the steps [here](https://github.com/microsoft/vscode/wiki/Performance-Issues) on reporting performance issues, in particular sections on profiling.
