### ISSUE TITLE
Big Sur issues

### ISSUE THREAD

**Issue by PJBeck84** [microsoft/vscode#108212]
Issue Type: <b>Bug</b>

Big Sur running Python causes freezing and unpredictable behavior

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id c94350d9-cfea-40fb-95dd-9a2ed63aae31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
mips|kda|0.0.5
python|ms-|2020.9.114305
cpptools|ms-|1.0.1
powershell|ms-|2020.6.0
vscodeintellicode|Vis|1.2.10
vim|vsc|1.17.1

</details>

**Comment by JacksonKearl** [comment]
\extPython

**Comment by matinzd** [comment]
> It looks like this is caused by the Python extension. Please file it with the repository [here](https://github.com/microsoft/vscode-python). Make sure to check their issue reporting template and provide them relevant information such as the extension version you're using. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines for more information.
> 
> Happy Coding!

I checked with the latest macOS beta and disabled the python extension and the problem still exists.

```
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:00:00.397Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0
```
