### ISSUE TITLE
Show all the possible "change language mode" options without submenu to open

### ISSUE THREAD

**Issue by iamkarlson** [microsoft/vscode#108290]
Currently, I have to select "change language mode" first, and then pick up a language I need. 
![image](https://user-images.githubusercontent.com/4534374/95432339-d1fc3d00-094e-11eb-8b68-24fe17ef6165.png)
![image](https://user-images.githubusercontent.com/4534374/95432373-dc1e3b80-094e-11eb-9de5-824c8e17a97a.png)

It would be super nice if we would have all the possible languages in this menu without going to submenu. Like: 
Change language mode
Change language mode: JSON
Change language mode: JSON with comments
Change language mode: XML
Change language mode: Python.

**Comment by JacksonKearl** [comment]
We're not likely to put those all in the main menu as that would add quite a bit of noise to searching in the command palette. You could however use an extension which contributes a collection of these commands, or assign keybindings to your more frequently used versions.
