### ISSUE TITLE
Pseudoterminal output does not appear f emitted before open() event fires

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#108298]
Not sure what's happening here, but content written to an emitter for a pseudo terminal doesn't seem to show up outside of the `open` function:

```ts
const emitter = new vs.EventEmitter<string>();
const pseudoterminal: vs.Pseudoterminal = {
	close: () => { },
	onDidWrite: emitter.event,
	open: () => { emitter.fire("Hello world!\r\n"); },
};
const terminal = vs.window.createTerminal({ name: `Danny Test Terminal`, pty: pseudoterminal });
emitter.fire(`Test 1\r\n`);
terminal.show();
emitter.fire(`Test 2\r\n`);
setTimeout(() => emitter.fire(`Test 3\r\n`), 100);
```

I only see the first line in the terminal:

![Screenshot 2020-10-08 at 12 18 05](https://user-images.githubusercontent.com/1078012/95451884-5905e100-0960-11eb-83bf-093a7d8c15f4.png)

**Comment by DanTup** [comment]
Seems like this may be a delay in the terminal subscribing to the event. Unsure if this is a bug/unintended race, or by design (if intended, I think it should be documented against the API somewhere).

This works:

```ts
const emitter = new vs.EventEmitter<string>();
let terminal!: vs.Terminal;
const terminalCreation = new Promise((resolve) => {
	const pseudoterminal: vs.Pseudoterminal = {
		close: () => { },
		onDidWrite: emitter.event,
		open: () => { emitter.fire("Hello world!\r\n"); resolve(); },
	};
	terminal = vs.window.createTerminal({ name: `Danny Test Terminal`, pty: pseudoterminal });
	emitter.fire("this line breaks it\r\n");
});
await terminalCreation;
terminal.show();
setTimeout(() => emitter.fire("Test 3\r\n"), 0);
```

**Comment by Tyriar** [comment]
I think it's by design, `open` is the callback when everything is ready, you should only write after open is called.
