### ISSUE TITLE
TrustedTypes policy usage in viewLayer

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#108240]
Continues https://github.com/microsoft/vscode/issues/106285#issuecomment-689414623

I have done the following measurement with the file attached below (uses the standalone editor). tt_N is run N using trusted types, str_N is run N with what we have today. I have picked `_finishRenderingNewLines ` since that's where all changes are and `insertAdjacentHTML` which is receiving a trusted type

|  | `_finishRenderingNewLines` |  `insertAdjacentHTML`
|--|---|---|
| tt_1 | 20 | 17 |
| tt_2 | 16 | 12 |
| tt_3| **17** | **13** |
| str_1 | 17 | 16 |
| str_2 | 15 | 13 |
| str_3 | **16** | **15** |

[sample.txt](https://github.com/microsoft/vscode/files/5339669/sample.txt)
[profiles.zip](https://github.com/microsoft/vscode/files/5339670/profiles.zip)

The first run with trusted types seems have been an outlier but otherwise I don't see a difference between both.

**Comment by jrieken** [comment]
Changes that I have done

```diff
diff --git a/src/vs/editor/browser/view/viewLayer.ts b/src/vs/editor/browser/view/viewLayer.ts
index eec48240c9..5ab9784cd4 100644
--- a/src/vs/editor/browser/view/viewLayer.ts
+++ b/src/vs/editor/browser/view/viewLayer.ts
@@ -369,6 +369,8 @@ interface IRendererContext<T extends IVisibleLine> {
 
 class ViewLayerRenderer<T extends IVisibleLine> {
 
+	private static _ttPolicy = window.trustedTypes?.createPolicy('editorViewLayer', { createHTML: value => value });
+
 	readonly domNode: HTMLElement;
 	readonly host: IVisibleLinesHost<T>;
 	readonly viewportData: ViewportData;
@@ -505,6 +507,9 @@ class ViewLayerRenderer<T extends IVisibleLine> {
 	}
 
 	private _finishRenderingNewLines(ctx: IRendererContext<T>, domNodeIsEmpty: boolean, newLinesHTML: string, wasNew: boolean[]): void {
+		if (ViewLayerRenderer._ttPolicy) {
+			newLinesHTML = ViewLayerRenderer._ttPolicy.createHTML(newLinesHTML) as unknown as string; // explains the ugly casts -> https://github.com/microsoft/vscode/issues/106396#issuecomment-692625393
+		}
 		const lastChild = <HTMLElement>this.domNode.lastChild;
 		if (domNodeIsEmpty || !lastChild) {
 			this.domNode.innerHTML = newLinesHTML;
```

**Comment by alexdima** [comment]
:+1: Looks good, I tried with more heavy files.
