### ISSUE TITLE
Drag Explorer to bottom

### ISSUE THREAD

**Issue by Rober19** [microsoft/vscode#108252]
> I don't know if this request is duplicate, surely it is 

![image](https://user-images.githubusercontent.com/28882108/95339766-0a7e1700-087a-11eb-95bd-c6268b794d9c.png)

I would like to use explorer from the panel, same as search ( I'm using portrait monitor )

![image](https://user-images.githubusercontent.com/28882108/95339778-0f42cb00-087a-11eb-9d05-b12b7413fbdc.png)

> thanks ; )

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by Rober19** [comment]
please, reconsider this one to next updates/improvements

**Comment by rbatty19** [comment]
I saw this added today when I updated, thanks a lot

<img width="963" alt="image" src="https://user-images.githubusercontent.com/28882108/223730743-eee728fe-c356-4d4b-8a86-164af4ea6fbd.png">
