### ISSUE TITLE
How to run PHP code from Visual Studio Code (VSCode)?

### ISSUE THREAD

**Issue by AhmerAli** [Microsoft/vscode#10827]
I posted my question on [stackoverflow](http://stackoverflow.com/questions/39067908/how-to-run-php-code-from-visual-studio-code-vscode). Kindly help me.

**Comment by sandy081** [comment]
@AhmerAli Please post your question here - https://github.com/felixfbecker/vscode-php-debug

**Comment by AhmerAli** [comment]
Problem is resolved now. Thanks for your reply
