### ISSUE TITLE
Mac client doesn't support "search menu actions" keyboard shortcut

### ISSUE THREAD

**Issue by Heilemann** [microsoft/vscode#108253]
- VSCode Version:1.49.3
- OS Version: macOS Big Sur 11.0 Beta

Steps to Reproduce:

1. Shift + Command + / should open the Help menu and put the cursor in the search field
2. It doesn't do anything.

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
The keybinding does work on my machine (Mojave)... does this reproduce on other Electron apps in Big Sur?
