### ISSUE TITLE
Web: extensions on playground no longer work on Safari

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108285]
**Steps:**
* `yarn web`
* open in Safari

I believe this is related to how we load the web worker extension host. Errors:

```
Unrecognized Content-Security-Policy directive 'worker-src'.
SecurityError: The operation is insecure.
```

**Comment by alexdima** [comment]
There is nothing I could do to get this working in Safari. Basically, I could not get an `<iframe>` with a `null` origin to start up a web worker. Here are the combinations I tried on Safari:

| `<iframe>` sandbox | `<iframe>` src | `WebWorker` src | `origin` inside `<iframe>` | Worker runs |
|---|---|---|---|---|
| `allow-scripts` | `data:` | `data:` | `null` | No |
| `allow-scripts` | `data:` | `blob:` | `null` | No |
| `allow-scripts` | `blob:` | `data:` | `null` | No |
| `allow-scripts` | `blob:` | `blob:` | `null` | No |
| `allow-scripts allow-same-origin` | `data:` | `data:` | `null` | No |
| `allow-scripts allow-same-origin` | `data:` | `blob:` | `null` | No |
| `allow-scripts allow-same-origin` | `blob:` | `data:` | `null` | No |
| `allow-scripts allow-same-origin` | `blob:` | `blob:` | `http://localhost:8080 ` | Yes |

The only way I could get a `WebWorker` running in an `<iframe>` is if the `<iframe>` is sharing the origin with the original page. This beats the purpose of having an `<iframe>` to begin with, so I will do the following:
- disable `<iframe>` wrapping on Safari for now
- look into hosting an `<iframe>` src on a different domain, similar to webviews.

**Comment by alexdima** [comment]
fyi @mjbvz I will need some help from you to host the `<iframe>` src on a different domain, similar to webviews.

fyi @eamodio @JacksonKearl

**Comment by mjbvz** [comment]
@alexdima Sure! Let's set up a meeting to talk about the problem and what we do  today for webviews. After our Monday team meeting would work for me

**Comment by alexdima** [comment]
:+1: @mjbvz

**Comment by alexdima** [comment]
We now have `<iframe>` wrapping also on Safari thanks to using a different origin.
