### ISSUE TITLE
Terminal Integration Settings missing option from Bash

### ISSUE THREAD

**Issue by Mofunkles** [microsoft/vscode#108218]
Issue Type: <b>Feature Request</b>

In Git Bash if I customise my prompt to include a bold current folder-name using the attribute code '01' and then enable in the text options 'show bold as font' then the terminal window displays bolded text as expected.

This behaviour does not carry over to the Bash terminal in VS Code as it appears to be lacking this option.  VSCode does feature the neighbouring option to 'show bold as color', as terminal.integrated.drawBoldTextInBrightColors.

![image](https://user-images.githubusercontent.com/70051438/95279016-814eec00-0849-11eb-8670-17452b803b49.png)

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041

**Comment by Tyriar** [comment]
This seems to work for me?

![image](https://user-images.githubusercontent.com/2193314/98162503-52528700-1e96-11eb-9244-d003dd3c95bb.png)

**Comment by Mofunkles** [comment]
That will sure, but now customize your prompt so the '$' is bold or something like that, it shouldn't show up as bold in VSCode terminal despite working fine in the Git Bash terminal.

**Comment by Tyriar** [comment]
Seems to be working as expected?

![image](https://user-images.githubusercontent.com/2193314/98308212-653f8700-1f7c-11eb-86ed-d9ffdbf39bdb.png)

Running `PS1=\\[\\033[1m\\]$` to change the prompt temporarily.

**Comment by Mofunkles** [comment]
![noboldallowedsadface](https://user-images.githubusercontent.com/70051438/98317408-5b497280-1fd4-11eb-8029-131c2ea7b95a.png)

Here is my git-prompt.sh and it doesn't seem to work for me in VS Code.  Using your temporary command, like the previous echo command works, I'm not saying the terminal is incapable of producing bold text, I'm saying my configuration which uses bold is somewhere along the way being formatted otherwise in VS Code, as shown it works fine in the Git terminal.

**Comment by Tyriar** [comment]
Can you share your settings.json file?

Also could you try enable escape sequence logging? This will tell us what git bash is telling VS Code to write (including the char styles) https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by Mofunkles** [comment]
[settings.zip](https://github.com/microsoft/vscode/files/5499701/settings.zip)

There is the settings ZIP

> xterm.js: parsing data [?25l
> 
> [0;31;91msandbox[0;37;90m > [0m[0K
> [0K
> [0K
> [0K
> [0K
> [4A[11G[?25h

That is the only useful thing I could get the log to do regarding my prompt.  It does show a 0 and not a 01 for the 'sandbox >' - though I don't know if you wanted me to show something more specific from this log?

**Comment by Tyriar** [comment]
Yes it looks like vscode never gets the 1, instead it gets a 0. Does it help by change if you change it from `01` to just `1`? That's the normal way to do bold.

**Comment by Mofunkles** [comment]
Just tried 1 instead of 01, same issue persists.

Now, I'm new to this stuff so I wouldn't expect my 15 minutes of sleuthing to amount to much. But I decided to poke around VSCode repository to see if anything obvious stood out to me and I found the following...

https://github.com/microsoft/vscode/blob/35bad7021df1e9c4c64396256c8ef6fa9b58b370/src/vs/workbench/contrib/terminal/browser/media/terminal.css#L96

Something regarding the terminal, using the !important keyword that seems to be selecting .xterm-bold in what I interpret as if bold is ever disabled in the settings?

**Comment by Tyriar** [comment]
@Mofunkles I think that's actually from bit rot and doesn't do anything anymore. That's what used to be used instead of the current `terminal.integrated.fontWeight` and `terminal.integrated.fontWeightBold` settings for customizing how bold shows in the terminal.
