### ISSUE TITLE
node_modules folder does not appear in file explorer after yarn install

### ISSUE THREAD

**Issue by apaparazzi0329** [microsoft/vscode#108206]
- VSCode Version: 1.49.2
- OS Version: MacOS 10.15.5

Steps to Reproduce:

1. Delete an already existing node_modules folder from any project
2. Use `yarn install` to reinstall the node modules
3. The node_modules folder should still be missing from the vs code file explorer; however, it is still created and can be seen by other means such as Finder

Does this issue occur when all extensions are disabled?: Yes

**Comment by nrayburn-tech** [comment]
Just to make sure I understand correctly.
1. You delete the node_modules folder.  It is not visible in the finder or vscode now.  (Are you deleting node_modules from within the vscode explorer, or finder?)
2. You run yarn install.
3. You can see the node_modules folder in finder, but not in vscode.

Is that right?  If so, can you check your `files.exclude` setting?  This setting hides folders/files from the vscode explorer.

**Comment by apaparazzi0329** [comment]
Yes you are correct and I am deleting node_modules from within the vscode explorer. I will check my settings

**Comment by apaparazzi0329** [comment]
<img width="850" alt="Screen Shot 2020-10-07 at 10 37 50 AM" src="https://user-images.githubusercontent.com/26935099/95345821-2806ad00-0889-11eb-9b6e-976bb1eadbb7.png">

**Comment by nrayburn-tech** [comment]
It isn't listed, but seems to be excluded anyways.
Seems to be similar to this issue, https://github.com/microsoft/vscode/issues/23954.

Adding this seems to fix it, but excluding node_modules from the watcher may cause some performance issues.  (As explained in the setting.)
```json
	"files.exclude": {
		"**/node_modules/**": false
	},
	"files.watcherExclude": {
		"**/node_modules/**": false
	}
```

**Comment by apaparazzi0329** [comment]
Thanks for the help and solution. I do not think fixing this small issue personally is worth the potential performance issues so I will keep it as is.
