### ISSUE TITLE
.? Javascript Optional Chaining Syntax Highlighting

### ISSUE THREAD

**Issue by orvisevans** [microsoft/vscode#108283]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Create a new JS file.
2.  Use optional chaining. (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
3.  See improper coloring on the following line. ("const" on line 3 doesn't highlight in the following example)

example for optional chaining:
```javascript
const hello = { hello: 'world' };
const worldMaybe = hello?.world;
const worldForSure = hello.world;
```

Does this issue occur when all extensions are disabled?: Yes

I'm guessing optional chaining just hasn't been added yet as it's so new. I'm happy to do that and contribute to fixing this issue if anyone can point out where I can do that.

**Comment by mjbvz** [comment]
Works fine for me

<img width="791" alt="Screen Shot 2020-10-07 at 11 42 56 PM" src="https://user-images.githubusercontent.com/12821956/95419412-d6950700-08f6-11eb-87a5-1c9e5ff3bfd2.png">

Are you sure you've disabled all extensions and restarted VS Code after doing so?

**Comment by orvisevans** [comment]
I had disabled them, but not restarted. That did it.
Thanks!
