### ISSUE TITLE
Search in the search editor windows does not respect the modified sort field

### ISSUE THREAD

**Issue by bs** [microsoft/vscode#108286]
- VSCode Version: 1.50.0-insider
- OS Version: macOS Catalina

Steps to Reproduce:

In the same vein as  #103625, but with ```modified``` selected (works with countDescending).

1. Settings > "Search: Sort Order" > select "modified"
2. Ctrl+P "> Search editor" (open the search editor)
3. Search something, results appear sorted by path

Does this issue occur when all extensions are disabled?: Yes

/cc @JacksonKearl @damienmg <3

**Comment by vivekmthr** [comment]
Hey Jackson! Do you mind if I give this try? Any ideas for where to start?

**Comment by JacksonKearl** [comment]
Sure, [this PR](https://github.com/microsoft/vscode/pull/103627) is from a similar feature request, this is the relevant bit https://github.com/microsoft/vscode/pull/103627/files#diff-f5378e637262df545ce758b50746c208. 

I'd expect that PR to support modified times by default, but I'm guessing in this region of `searchMatchComparer` the `fileStat`s are not defined: https://github.com/microsoft/vscode/blob/528b473dba12e696213c747f3b710981cd32d30d/src/vs/workbench/contrib/search/common/searchModel.ts#L675-L680

In the search view we use this utility to define them: https://github.com/microsoft/vscode/blob/df6e65648906246624028776f9425050127784a7/src/vs/workbench/contrib/search/browser/searchView.ts#L1890-L1893

**Comment by vivekmthr** [comment]
Great! Thanks for your help. I'll look into it and let you know how I fare.

**Comment by vivekmthr** [comment]
My understanding so far is that the searchMatchComparer function essentially orders two files of the same type depending on the configuration that is chosen? 

However, whenever I put a breakpoint in the searchMatchComparer function, it doesn't break. How do I trigger the breakpoint in the searchMatchComparer function so I can check the values of fileStatA and B and check if the case "Modified" is actually getting reached? 

I thought that the above might be a good place to start but let me know if I'm off base and getting the wrong ideas.

Hope that it isn't too much trouble to answer and thanks for your help in advance : )

**Comment by JacksonKearl** [comment]
I'd expect the breakpoint to be hit - are you able to hit other breakpoints in the build?

**Comment by vivekmthr** [comment]
Yeah, I'm hitting other ones. Any specific break point I should try as a test?

**Comment by vivekmthr** [comment]
Also, the modified search in ctrl + shift + f search works properly, but the modified search prompted by the ctrl + shift + p doesn't. Could that be part of the problem?

**Comment by JacksonKearl** [comment]
> The breakpoints don't hit when I run control + shift + p

This is the command palette shortcut? Not clear to me what you're saying.

**Comment by vivekmthr** [comment]
Ctrl+P "> Search editor" (open the search editor) 
Search something, results appear sorted by path.

If you remove the arrow that comes up in the command palette short cut it defaults to "search files by name". If you search for a file from there it appears ordered by path even if you've chosen modified.

**Comment by AdityaKG-169** [comment]
I might be wrong, but I followed the exact same steps to reproduce the bug but it is working totally fine on my system.
The files are sorted on the basis of modified time.

**Comment by vivekmthr** [comment]
Exactly.

**Comment by jeanp413** [comment]
@vivekmthr are you still working on this? if not I can take a look at it

**Comment by JacksonKearl** [comment]
I can confirm that the sorting of results in the search editor does not respect the recent setting. To verify:
1. run a search
2. add a result in a new file
6. rerun.
4. result does not appear at top.

**Comment by vivekmthr** [comment]
jeanp413 go ahead! I wasn't able to reproduce the bug last time, but I'll try again in a bit with Jackson's suggestions to double check.

**Comment by bs** [comment]
<3
