### ISSUE TITLE
TypeError: Cannot read property 'className' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10820]
When switching "open editors" view from visible to hidden or vice versa.

@isidorn it looks like when the view changes, it does not get disposed and so old listeners are hanging around?

**Comment by isidorn** [comment]
No, the view gets properly disposed, however when reacting to icon changes we were acting on configuration changes before the whole explroer view would get constructed. Added a null guard to protect against that
fyi @aeschli

**Comment by bpasero** [comment]
I added that code btw.
