### ISSUE TITLE
spurious paste of copy data

### ISSUE THREAD

**Issue by moorjock** [microsoft/vscode#108293]
Ubuntu 18.04LTS user of vscode I experience spurious paste of previously copied data. Typically using (ctrl)-C to copy and (ctrl)-V to paste I sometimes (and not infrequently) find that the code clip has been pasted to random locations in same or another file.

Typical example shown in the code snippet below. I copied the function header "compute_inertia(..)" highlighted below into the header file only to later find that it had also been spuriously pasted into the comment section of another function in another file! (though in the same project). 
This is not an uncommon experience and it can be more damaging where the spurious paste breaks working code in a completely unrelated (but open file). I am typically working across multiple projects with many open file windows. This can be a real nuisance.
// pointCount   Number of vertex in pointVec
// rotVec       rotated pointVec  = Trans(pointVec) **_compute_Inertia(float* pointVec, int2 pntSz, int pointCount, int pSegSzX, float* WorkVec, int workSzX, float*dResVec, int* dAtomVec, FMat& Inertia)_**
// refMean      Mean of points in the reference cuArray

**Comment by JacksonKearl** [comment]
That's certainly odd - does this reproduce when all extensions are disabled? 
![image](https://user-images.githubusercontent.com/8586769/95501084-a2ecc800-095c-11eb-8119-8219d60e2843.png)
