### ISSUE TITLE
No IPv6 on packages.microsoft.com

### ISSUE THREAD

**Issue by kenyon** [microsoft/vscode#108265]
vscode is not installable on Linux from IPv6-only networks because packages.microsoft.com has no AAAA record:

```
% host -t aaaa packages.microsoft.com
packages.microsoft.com is an alias for apt-geofence-parent.trafficmanager.net.
apt-geofence-parent.trafficmanager.net is an alias for csd-apt-sus-d-3.southcentralus.cloudapp.azure.com.
```

Related: dotnet/core/issues/3016

**Comment by Tyriar** [comment]
This would go to the same team as for dotnet https://github.com/dotnet/core/issues/3016#issuecomment-536784919, since they're been informed already I'll close this out in the interest of issue grooming. If any other projects on packages.microsoft.com get it and we don't, let us know.
