### ISSUE TITLE
dotnet core is not found although it is added to my path

### ISSUE THREAD

**Issue by mover333** [microsoft/vscode#108275]
Issue Type: <b>Bug</b>

Whenever I open up a C# project in code I get the error:
```
The .NET Core SDK cannot be located. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.
```

dotnet core is installed on my path:
```
user@MBP ~> which dotnet                                                                                                                                             
/usr/local/bin/dotnet
user@MBP ~> dotnet --list-sdks                                                                                                                                       
3.1.402 [/usr/local/share/dotnet/sdk]
```

I have tried uninstalling both dotnet core and VSCode. I used dotnet core with C# in June with no issues, I do not think I have changed anything aside from VSCode updates. If I open code from my terminal I have no issues.

Maybe related:
Even once I fix the dotnet core issue, executing the default tasks debugging an Azure Function fails with the following error:

```
> Executing task: dotnet clean /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

execvp(3) failed.: No such file or directory
The terminal process "dotnet 'clean', '/property:GenerateFullPaths=true', '/consoleloggerparameters:NoSummary'" failed to launch (exit code: 1).
```

And the task is defined as:

```
{
      "label": "clean",
      "command": "dotnet",
      "args": [
        "clean",
        "/property:GenerateFullPaths=true",
        "/consoleloggerparameters:NoSummary"
      ],
      "type": "process",
      "problemMatcher": "$msCompile"
    }
```

If I change the type to "shell" it works. 

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|. --crash-reporter-id 5329a578-e85f-472c-b5d1-ea2a5e1d999b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
azurite|Azu|3.8.0
markdown-mermaid|bie|1.8.1
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.37.1
gitlens|eam|10.2.2
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.1
docomment|k--|0.1.18
git-graph|mhu|1.26.0
prettify-json|moh|0.0.3
vscode-azurefunctions|ms-|0.24.1
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
python|ms-|2020.9.114305
remote-containers|ms-|0.140.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.44.5
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.3
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-xml|red|0.13.0
vscode-yaml|red|0.11.1
rewrap|stk|1.13.0
code-spell-checker|str|1.9.2
python|tht|0.2.3
errorlens|use|3.2.3
azure-iot-edge|vsc|1.23.0
azure-iot-toolkit|vsc|2.16.4
azure-iot-tools|vsc|0.3.0
vscode-iot-device-cube|vsc|0.3.0
vscode-iot-workbench|vsc|0.16.0

(1 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
\extC#
