### ISSUE TITLE
Node.js preview doesn't kill the process when the debugging is stopped

### ISSUE THREAD

**Issue by agrawalsourav98** [microsoft/vscode#108289]
Issue Type: <b>Bug</b>

I am using the Node.js preview for debugging my application. It uses a npm script. I select the script from the provided options suring setup of Node.js preview debugger.

The debugging has no issues but when i stop the debugger, the program running is not killed. 

For instance, if i mounted my server on port 5000 previously, the port is still occuppied as the program is not killed. I have verified this through the netstat command.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:56:11.027Z)
OS version: Linux x64 5.4.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2107)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|11.54GB (5.29GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pantheon|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pantheon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
prettier-vscode|esb|5.7.1
python|ms-|2020.9.114305

</details>

**Comment by connor4312** [comment]
Thanks for the issue, this'll be fixed in the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Comment by aeschli** [comment]
I verified by creating a `Launch via NPM` launch config that starts a long running node script. Stopping the launch also killed the process. @connor4312 Please let me know if more is needed
