### ISSUE TITLE
Debugger does not work when running Node.js on an unsupported operating system

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [microsoft/vscode#108222]
I'm here because I spent over 6 hours trying to get any feedback from the debugging tools in vscode. 
even tried a fresh install of vscode, moved all config, extension and appdata folders

- I cloned these two examples: 
 - https://github.com/PKief/vscode-typescript-debugging
 - https://github.com/branflake2267/debugging-service-typescript
- Tried many examples, including any instructions on the typescript website.

I went trough many configuration settings for the launch.json, none worked.
No debugging method worked. The debugger just doesn't seem to launch.

If someone can give me some info on how to troubleshoot this I would be thankful.

I feel like this is the reason why many devs still use console.log

- VSCode Version: 1.49.2
- OS Version: Win7x64

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Please grab some logs

/jsDebugLogs

**Comment by hp8wvvvgnj6asjm7** [comment]
the debugger doesn't work on win7 x64 its utterly non-functioning - after 6 hours and countless examples, the variables box remains empty. Used breakpoints, tried typescript examples, node js examples, simplest possible, many configs, fresh vscode install. None worked. Please help.

I am using the portable builds of node and vscode, but had no issues with them before. Only the debugging never worked.
Every time I tried to use the debugger It never displayed anything and I thought it was too complicated, but now its clear that its a bug.

It seems like auto-attach doesn't work either.

I just tried to start the debugger on two different machines using this example: https://github.com/branflake2267/debugging-service-typescript
No success with it

**Comment by hp8wvvvgnj6asjm7** [comment]
I will collect some logs now, thank you.

**Comment by hp8wvvvgnj6asjm7** [comment]
[vscode-debugadapter-2.json.gz](https://github.com/microsoft/vscode/files/5338234/vscode-debugadapter-2.json.gz)

**Comment by connor4312** [comment]
Thanks for the logs. Do you have any antivirus or firewall running locally? We've seen issues where these sometimes block the debug connection.

**Comment by hp8wvvvgnj6asjm7** [comment]
i turned off my firewall.

**Comment by hp8wvvvgnj6asjm7** [comment]
I can see that it connects to localhost.
[10.07 04:22:59] Code.exe (2564) *64 - 127.0.0.1:52257 matching - rule : direct connection

**Comment by connor4312** [comment]
You want to make sure that the Node binary is able to connect back to the localhost server which VS Code sets up for it

**Comment by hp8wvvvgnj6asjm7** [comment]
How do we test this? I have all firewalls down.

**Comment by hp8wvvvgnj6asjm7** [comment]
When i was testing a simple js file, it said auto-attach failed. If that helps

**Comment by hp8wvvvgnj6asjm7** [comment]
```
node --inspect test
Debugger listening on ws://127.0.0.1:9229/912cb728-2afe-43e9-896a-8f58639fbdc5
For help, see: https://nodejs.org/en/docs/inspector
1
2
3
4
5
6
7
8
9
10

```

**Comment by hp8wvvvgnj6asjm7** [comment]
this is all i'm getting here: 
![wtf](https://user-images.githubusercontent.com/45887282/95287782-5ae37d80-0856-11eb-8bfb-f4d3a47da4ec.png)

**Comment by hp8wvvvgnj6asjm7** [comment]
If  I run a js file with auto attach on i get:

```
C:\Users\Auteroid\Desktop\debugging-service-typescript\dist\service>node service.js
Debugger listening on ws://127.0.0.1:52408/33033bc1-4378-41bb-8eae-17f1ca656b7b
For help, see: https://nodejs.org/en/docs/inspector
Error activating auto attach, please report to https://aka.ms/js-dbg-issue
```

**Comment by connor4312** [comment]
Here's a build with some additional logging:

1. Download [this build](https://memes.peet.io/img/108222-js-debug.vsix) and install it via the `Install from VSIX` command
1. Add `"console": "integratedTerminal"` to your launch.json config
1. Run and share the log information printed to your debug terminal

**Comment by hp8wvvvgnj6asjm7** [comment]
Terminal: 
````

 cmd /C "set "NODE_OPTION
S=--require c:/Users/Auteroid/.vscode/extensions/ms-vscode.js-debug-1.50.0/src/b
ootloader.bundle.js --inspect-publish-uid=http" && set "VSCODE_INSPECTOR_OPTIONS
={"inspectorIpc":"\\\\.\\pipe\\node-cdp.5724-2.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Users\\Auteroid\\Apps\\node\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\Auteroid\\AppData\\Local\\Temp\\node-debug-callback-49ec87ef44b3a1e7"}" && C:\Users\Auteroid\Apps\node\node.exe .\dist\launchers\launch_service.js "



```

**Comment by hp8wvvvgnj6asjm7** [comment]
```
C:\Users\Auteroid\Desktop\debugging-service-typescript> cmd /C "set "NODE_OPTION
S=--require c:/Users/Auteroid/.vscode/extensions/ms-vscode.js-debug-1.50.0/src/bootloader.bundle.js --inspect-publish-uid=http" && set "VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"\\\\.\\pipe\\node-cdp.5916-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Users\\Auteroid\\Apps\\node\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\Auteroid\\AppData\\Local\\Temp\\node-debug-callback-0a0e4a7b0172e1ff"}" && C:\Users\Auteroid\Apps\node\node.exe .\dist\launchers\launch_service.js "


```

**Comment by connor4312** [comment]
That output indicates js-debug v1.50.0 is running. The vsix I sent is 1.49.8 -- you may need to disable auto updating extensions if VS Code keeps string to update you

![](https://memes.peet.io/img/20-10-81670dc4-7a20-4d62-af24-e1eff9a4f4b0.png)

**Comment by hp8wvvvgnj6asjm7** [comment]
```

C:\Users\Auteroid\Desktop\debugging-service-typescript> cmd /C "set "NODE_OPTION
S=--require c:/Users/Auteroid/Apps/code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http" && set "VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"\\\\.\\pipe\\node-cdp.5636-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Users\\Auteroid\\Apps\\node\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\Auteroid\\AppData\\Local\\Temp\\node-debug-callback-e443d335b0e59bfe"}" && C:\Users\Auteroid\Apps\node\node.exe .\dist\launchers\launch_service.js "



```

**Comment by hp8wvvvgnj6asjm7** [comment]
![image](https://user-images.githubusercontent.com/45887282/95288790-c6c6e580-0858-11eb-8cfb-b5d41a2d581f.png)

**Comment by connor4312** [comment]
Can you go ahead and hit the "reload" button in the lower right to make sure the update takes?

**Comment by hp8wvvvgnj6asjm7** [comment]
```

C:\Users\Auteroid\Desktop\debugging-service-typescript> cmd /C "set "NODE_OPTIONS=--require c:/Users/Auteroid/.vscode/extensions/ms-vscode.js-debug-1.49.8/src/bootloader.bundle.js --inspect-publish-uid=http" && set "VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"\\\\.\\pipe\\node-cdp.5848-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Users\\Auteroid\\Apps\\node\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\Auteroid\\AppData\\Local\\Temp\\node-debug-callback-f63952c108b058bd"}" && C:\Users\Auteroid\Apps\node\node.exe .\dist\launchers\launch_service.js "
runtime.launch Bootloader imported {
  env: {
    inspectorIpc: '\\\\.\\pipe\\node-cdp.5848-1.sock',
    deferredMode: false,
    waitForDebugger: '',
    execPath: 'C:\\Users\\Auteroid\\Apps\\node\\node.exe',
    onlyEntrypoint: false,
    autoAttachMode: 'always',
    fileCallback: 'C:\\Users\\Auteroid\\AppData\\Local\\Temp\\node-debug-callback-f63952c108b058bd'
  },
  args: [
    'C:\\Users\\Auteroid\\Apps\\node\\node.exe',
    'C:\\Users\\Auteroid\\Desktop\\debugging-service-typescript\\dist\\launchers\\launch_service.js'
  ]
}
runtime Set debug mode { mode: 0 }
Node.js is only supported on Windows 8.1, Windows Server 2012 R2, or higher.
Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this
check, but Node.js might not execute correctly. Any issues encountered on
unsupported platforms will not be fixed.

```

**Comment by hp8wvvvgnj6asjm7** [comment]
i have set platform check to 1 already 
![Untitled-1](https://user-images.githubusercontent.com/45887282/95289141-93388b00-0859-11eb-85f3-7455aaecf0af.png)

**Comment by hp8wvvvgnj6asjm7** [comment]
It seems that this is the actual problem? But why does it ignore the platform check variable during debug? I can use node js without any problems otherwise.

**Comment by connor4312** [comment]
Ok, that explains it. The process we launch to talk back to VS Code is failing to launch, which we should report better.

This can be fixed by having the usages of `spawn` and `spawnSync` inherit that variable in here: https://github.com/microsoft/vscode-js-debug/blob/master/src/targets/node/bootloader.ts I would accept a PR for this.

**Comment by hp8wvvvgnj6asjm7** [comment]
thanks heaps!

**Comment by hp8wvvvgnj6asjm7** [comment]
`process.env.NODE_SKIP_PLATFORM_CHECK`?

**Comment by hp8wvvvgnj6asjm7** [comment]
@connor4312 
Is this worth a pull request? 
https://github.com/hp8wvvvgnj6asjm7/vscode-js-debug/pull/1/files

**Comment by connor4312** [comment]
\closedWith ba1b6a7b871b714dbe9fb1a450ca806d62e41264

**Comment by connor4312** [comment]
To verify this you need to:

1. Use Windows 7
1. Run Node 14
1. Set `NODE_SKIP_PLATFORM` check as a user/global environment variable
1. Verify you can debug

Or you can verify through code review
