### ISSUE TITLE
Unable to debug Typescript with auto-attach

### ISSUE THREAD

**Issue by AnthonyScottMoncrieff** [microsoft/vscode#108208]
- VSCode Version: 1.49.3
- OS Version: Windows 10 Professional

Steps to Reproduce:

1. Setup auto attach for typescript project
2. Set a breakpoint
3. See message: Could not load source %User Profile%\%Application Directory%': Unable to retrieve source content.

Does this issue occur when all extensions are disabled?: Yes

For the record, my application source is not in my user profile

I am using this tsconfig: 

{
    "compilerOptions": {
        "target": "ES2017",
        "lib": ["es6", "dom"],
        "types": ["reflect-metadata", "chai", "mocha", "typemoq", "node"],
        "module": "commonjs",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "sourceMap": true,
        "resolveJsonModule": true,
        "outDir": "lib/src/",
        "useDefineForClassFields": true
    }
}

**Comment by connor4312** [comment]
@AnthonyScottMoncrieff please confirm that you're using the nightly build suggested in https://github.com/microsoft/vscode/issues/106803#issuecomment-704575546

**Comment by AnthonyScottMoncrieff** [comment]
@connor4312 I have tried using the nightly build but that is even worse, I don't get any attachment at all

**Comment by AnthonyScottMoncrieff** [comment]
After some fiddling with the nightly build (including turning auto attach off and on again) I have managed to get it to attach, but I still get the above issue

**Comment by AnthonyScottMoncrieff** [comment]
I should clarify that this was working before the most recent update

**Comment by connor4312** [comment]
Please collect logs by add this to your settings:

```
"debug.javascript.terminalOptions": {
  "trace": true
},
```

The location of the log file will be written to the Debug Console

**Comment by AnthonyScottMoncrieff** [comment]
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/5337324/vscode-debugadapter-0.json.gz)

**Comment by AnthonyScottMoncrieff** [comment]
I should also mention that while VS Code is bound, none of the breakpoints in the typescript are

**Comment by AnthonyScottMoncrieff** [comment]
Interestingly, running this configuration seems to work just fine:

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node-terminal",
            "name": "Run Script: start",
            "request": "launch",
            "command": "npm run start",
            "cwd": "${workspaceFolder}"
        }
    ]
}

Despite the fact I'm running the same command from the terminal to get this issue

**Comment by connor4312** [comment]
We just released VS Code 1.50, can you update and check whether this happens there?

**Comment by AnthonyScottMoncrieff** [comment]
Hi Connor, that seems to have done it, many thanks

**Comment by connor4312** [comment]
Ok, thanks for confirming!

**Comment by danieler1981** [comment]
Similar issue for me with VSCode 1.50.0

> Could not load source '/DB.ts': Unable to retrieve source content.

- AutoAttach configuration: smart.
`NODE_PATH=../shared/ node --inspect=0.0.0.0:32415 ./index.js`

DB.ts is locate in "../shared" and I suspect VSCode is expecting to have it in ./ rather than ../shared.

**Comment by connor4312** [comment]
Please grab logs using the instruction above!

**Comment by danieler1981** [comment]
Thanks - done.
[vscode-debugadapter-13.json.gz](https://github.com/microsoft/vscode/files/5359401/vscode-debugadapter-13.json.gz)

**Comment by danieler1981** [comment]
@connor4312 is this file the right one you was looking for?

**Comment by connor4312** [comment]
Thanks @danieler1981  -- are you able to share (here or privately) the contents of `/Users/danieletassone/Desktop/repository/super-drafter-app/src/microservices/sharedmodule/library/DatabaseManager.js.map`?

**Comment by danieler1981** [comment]
@connor4312 just sent it. Thanks.
