### ISSUE TITLE
No Log (Telemetry) Output in Codespaces

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#108250]
From @devinvalenciano

Repro:

- Open a Codespace.
- Open Command Palette
- Developer: Set log level == Trace
- Open Output window
- Try to select Log (Telemetry)

This photo shows what the Output window looks like in Codespaces, with the Log (Telemetry) option missing:
![image](https://user-images.githubusercontent.com/1389808/95271487-dad7fc00-07f2-11eb-9b78-79962a07746b.png)

And this photo shows what the Output window looks like in VS Code desktop, with the Log (Telemetry) option present:
![image](https://user-images.githubusercontent.com/1389808/95270736-0eb22200-07f1-11eb-81be-6d7a11a3fa29.png)

**Comment by sandy081** [comment]
Not sure who owns telemetry, but I will look into it as I see couple of issues in logging telemetry. We are logging telemetry in multiple logs . Will consolidate the,.

**Comment by sbatten** [comment]
@sandy081 let's sync on this and include @RMacfarlane so that we do not break something and those with prior knowledge can be updated if changes are made.

**Comment by sandy081** [comment]
@sbatten, Sorry did not notice your comment and I prepared following improvements already and pushed.

- When telemetry is enabled and log level is trace, telemetry events are shown in single location - **Telemetry (Log)** output view. **Difference:** Previously telemetry events are getting logged in all logs (window, shared process, main, remote server) etc., in addition to the telemetry log. In Dev mode, no events are shown in telemetry log

- Enabled telemetry log channel in Web

CCing @jrieken as I see you share some history in logging telemetry events.

**Comment by sandy081** [comment]
To verify:

- Verify the steps in description
- Also verify running from sources as follow:
 - Add `"enableTelemetry": true` to `product.json`
 - Launch code from sources
 - Enable log level to trace
 - Open Output panel and open telemetry log and make sure telemetry events are recorded
