### ISSUE TITLE
[remote] Allow to open remote files through `vscode://vscode-remote/`

### ISSUE THREAD

**Issue by phknot** [microsoft/vscode#108257]
When clicking on link in the form of `vscode://vscode-remote/wsl+distro/path/to/file/in/open/workspace` my current VS Code window is closed, and the file is opened in another window.

Expected behaviour would be that the file opens in your already open VS Code instance that's connected to that remote. This is also how VS Code behaves when opening the same file via the command line: ` code --remote wsl+remote /path/to/file/in/open/workspace`.

Opening the links in your existing session would be great for opening stacktrace links from the browser and going directly to the code.

**Comment by aeschli** [comment]
Currently, URL starting with `vscode://vscode-remote/` can only open folders not files.

@dpatou Just pinged me with the same request

**Comment by aeschli** [comment]
For remote URIs we can't do a stat to find out if the URI is a file or a folder.
- When opening a `vscode:` uri we always treat it as folder unless it ends with `.code-workspace`, then it's a workspace
- On the command line, we have a heuristic:
  - it's a folder if it ends with a slash
  - it's a workspace if it ends with `.code-workspace`,
  - it's a file if the name contains a dot

@bpasero I think you originally added the `vscode` handler for remote URI. Should we use the same heuristic as for the command line (which also has it's weaknesses)? You might know if that can break existing usages.
Alternative is to add a query parameter `?fileURI=true`. If we add such a parameter we should also support it on the command line.

**Comment by bpasero** [comment]
@aeschli this code is used to support "Open in Desktop" from codespaces, so I am not sure we can do a change that risks breaking this flow. After all, repository names can possibly include ".".

**Comment by dpatou** [comment]
> Alternative is to add a query parameter ?fileURI=true. If we add such a parameter we should also support it on the command line.

This seems to be the most reliable, and kinda "fixes" the current caveats of the command line in file/workspace/folder detection.

@bpasero does the open in desktop feature of codespace supports opening a given file/line-in-file (I haven't been able to access codespace yet) ?

**Comment by aeschli** [comment]
With the pushed change, it is now possible to open remote files.

To indicate that a remote URL is a file, not a folder, the path needs to be followed by `:linenumber[:column].`

**Comment by aeschli** [comment]
To verify on WSL (or on any other remote)
- run the `Devloper: Open URL` command
-  `vscode://vscode-remote/wsl+distro/path/to/file:1:1` should open file

**Comment by dbaeumer** [comment]
Doesn't work for me. I am use the following URL

```
vscode://vscode-remote/wsl+Ubuntu-20.04/home/dirkb/tmp/package.json:1:1
```

And the file clearly exist on my file system

![cast](https://user-images.githubusercontent.com/1931590/116428240-0846ce80-a845-11eb-9173-d5bc6d70abf4.gif)

**Comment by aeschli** [comment]
Ok, my bad, but when using insiders, it's `vscode-insiders://vscode-remote/wsl+distro/path/to/file:1:1`

**Comment by chrisdias** [comment]
I tested the following and all seemed to work properly, opening the file (only) at the appropriate line/column. The last option opened the folder as expected.

* `vscode-insiders://vscode-remote/wsl+Ubuntu/home/chrisdias/src/myexpressapp/app.js:1:1`
* `vscode-insiders://vscode-remote/wsl+Ubuntu/home/chrisdias/src/myexpressapp/app.js:1:20`
* `vscode-insiders://vscode-remote/wsl+Ubuntu/home/chrisdias/src/myexpressapp/app.js:20:1`
* `vscode-insiders://vscode-remote/wsl+Ubuntu/home/chrisdias/src/myexpressapp`

If I provided the wrong path, a new unsaved file named `app.js` was opened.

* `vscode-insiders://vscode-remote/wsl+Ubuntu/home/BLAH/src/myexpressapp/app.js:20:1`

What I can't see, and don't know if its supported, is how to open the folder and the file at the same time, such that the `myexpressapp` workspace is opened, with `app.js` opened on a particular line/column.

**Comment by TylerLeonhardt** [comment]
Moving out to May and reopening so @chrisdias's comment doesn't get lost but @aeschli please do what you want with this issue.

**Comment by chrisdias** [comment]
to be clear - the files opened in the existing instance of Insiders.  opening the folder resulted in a reload of the current instance.

**Comment by aeschli** [comment]
Through the `vscode`/'vscode-insiders' protocol handler, we only support opening one resource a time. I believe that's how a protocol handler typically works. 
This feature request was just also allow opening a remote file, not only a remote folder.

@chrisdias Can you file a new feature request with your your use case?
