### ISSUE TITLE
"Open file" from Source Control panel on click

### ISSUE THREAD

**Issue by jpenna** [microsoft/vscode#108282]
When you click the file in the Source Control panel list, it defaults to "Open Changes".
There could also be a default "Open File" on `cmd/ctrl + click`
![image](https://user-images.githubusercontent.com/16005946/95407157-a21f4c00-08f2-11eb-93e7-520396f59c33.png)

**Comment by joaomoreno** [comment]
Unfortunately cmd/ctrl click is already taken: it's multiple selection.

There already is a single click action for opening the file directly:

![image](https://user-images.githubusercontent.com/22350/95596190-5cc36180-0a4d-11eb-9b8d-d6024e4d5192.png)

**Comment by jpenna** [comment]
It could be cmd+shift+click, ctrl+shift+click... I'm not being picky on a set of commands.

The shortcut would be nice because I use this tab a lot to move between the files I'm editing. We can click this icon, but being precise to click a small icon next to other icons isn't efficient enough.
Unfortunately there is no way to edit click shortcuts, so it would have to be built in.
