### ISSUE TITLE
VSCode freezes up briefly. may be caused by displaying dialog boxes

### ISSUE THREAD

**Issue by Raju-Maher** [microsoft/vscode#108259]
- VSCode Version:
Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:56:11.027Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic snap

- OS Version: Ubuntu 20.04.1 LTS

Steps to Reproduce:

1. change a file.
2. use the git functinality to revert that file change
3. see dialog that says vscode is not responding (click "wait")
4. few seconds later the expected dialog appears to ask if im sure.
5. if i choose select either option (cancel, discard file)... there is a few more seconds it is frozen before that action is performced

** i also experience something similar if i decide to delete a file
** i also experienced this when going to look for the vscode version (top-bar > help > about)

Does this issue occur when all extensions are disabled?: Yes

i have tried reinstalling vscode from the ubuntu store... this did not work.
i also tried removing folders found at `$HOME/.vscode` and `$HOME/.config/Code` in case it was something to do with my local configuration.

![image](https://user-images.githubusercontent.com/42640882/95357073-b568f200-08c7-11eb-8627-fe6185acdddf.png)

![image](https://user-images.githubusercontent.com/42640882/95357025-a3874f00-08c7-11eb-84b6-ca3a680f5695.png)

**Comment by Raju-Maher** [comment]
@deepak1556 to follow up on this issue. it seems something i did as described in the ticket seems to have fixed the issue after restarting the computer.

i dont know if you want to close the ticket now, but the issue is resolved for me and i didnt manage to identify what was causing the issue... that issue persistent between vscode updates. but unable to recreate issue now.

**Comment by deepak1556** [comment]
thanks for the update, we can close the issue for now and revisit if it happens again.
