### ISSUE TITLE
Show if a line is passing a character limit

### ISSUE THREAD

**Issue by novachief101** [microsoft/vscode#108238]
Is there any way in VSCode to show/highlight characters passing a character limit for a line such as 80 (possibly ignoring whitespace in the left side)? I sometimes use [Vim](https://www.vim.org), in Vim, there is a script for that. I have searched the VSCode Marketplace and have found nothing. It would be useful if a feature like this was pre-implemented in VSCode.

**Comment by JacksonKearl** [comment]
I think you want "Editor: Rulers" in settings:

![image](https://user-images.githubusercontent.com/8586769/95393670-d1f93000-08af-11eb-90f8-928ff7c94380.png)

**Comment by JacksonKearl** [comment]
If you specifically want highlighting, an extension could implement this via the text decorations API, here's a ref to get started: https://code.visualstudio.com/api/references/vscode-api#window.createTextEditorDecorationType. We're not likely to implement this in core as we already have the rulers.
