### ISSUE TITLE
Allow quick open to open multiple files

### ISSUE THREAD

**Issue by MarkKahn** [microsoft/vscode#108247]
Issue Type: <b>Feature Request</b>

Possibly by holding shift and using arrows.

My use case: I very commonly open both the source and the test file at the same time.  It'd be nice to just hit shift+down, enter

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 19.5.0

**Comment by alefragnani** [comment]
Hi @MarkKahn ,

You can use the `Right Arrow` key while using the `Quick Open` command. It will open the focused file in the background, keeping the `Quick Open` menu open.

It’s not the same as _multiple files_ but has a similar effect.

Hope this helps
