### ISSUE TITLE
Pinned tabs need more prominence

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#108211]
I know we have a new color token to separate the pinned tabs, but it doesn't feel like it gives enough prominence of the ones that are pinned. We also discussed this in standup and some felt the same about needing a stronger prominence. Below are some ideas.

## Always show the pin icon

This means we'd need a hybrid icon of pinned + dirty. This one is my favorite as it keeps the look cleaner.

![image](https://user-images.githubusercontent.com/35271042/95264481-3f3f8f00-07e4-11eb-8891-257d46360d8a.png)

## Add space for two icons

This follows closer to #106956 and VS by making space for two icons

![image](https://user-images.githubusercontent.com/35271042/95264991-25eb1280-07e5-11eb-9be0-8b5dcbae8a14.png)

## Stronger border

This was @kieferrm's idea about increasing the pinned tab border to 2px

![image](https://user-images.githubusercontent.com/35271042/95265061-487d2b80-07e5-11eb-8035-ead1517c5a64.png)

**Comment by bpasero** [comment]
I somewhat prefer the "always show the icon" approach and can give it a try once we have the icon for showing dirty and pinned.

**Comment by misolori** [comment]
Added the icon as `pinned-dirty` via https://github.com/microsoft/vscode/commit/4e8970bc0be936c58aaad8d7e1cd7510acd2fc27

**Comment by bpasero** [comment]
@misolori started a branch https://github.com/microsoft/vscode/tree/ben/sticky-tabs-always-visible to try this out, can you check if you think this is a good change?

Some open ends:
* the pin icon seems to move slightly when switching between dirty and not
* the new icon is not yet adopted in "open editors" view or when tabs are disabled
* should we also always show the icon in the "open editors" view?

![recording](https://user-images.githubusercontent.com/900690/95446857-30321b80-0961-11eb-9f86-e69360d40bc6.gif)

**Comment by misolori** [comment]
I can fix the jumpiness of the icon. This looks good, can this also be applied to the `shrink` state?

<img width="400" src="https://user-images.githubusercontent.com/35271042/95474436-f13c9f80-0939-11eb-94b5-899d01f0839d.png">

**Comment by bpasero** [comment]
I was not sure if it should apply for shrinked tabs too because you will loose a lot of space which otherwise can be used to show the file name?

**Comment by bpasero** [comment]
@misolori I also found Eric's idea of using a smaller icon interesting. When I look at VS icons in the tab well, they seem to be a lot smaller compared to others:

VS:
![image](https://user-images.githubusercontent.com/900690/95682062-90d08b00-0be3-11eb-8a9c-5ffb2ee55fe2.png)

VSCode:
![image](https://user-images.githubusercontent.com/900690/95682053-8615f600-0be3-11eb-91dd-87c8393e759c.png)

**Comment by misolori** [comment]
Made the icons a little shorter and fixed the jump in the icons:

![image](https://user-images.githubusercontent.com/35271042/95816999-51826700-0cd5-11eb-8b56-22eaa061c909.png)

**Comment by bpasero** [comment]
@misolori looks really good thanks!

**Comment by bpasero** [comment]
I pushed this and also adopted it for:
* open editors view
* when tabs are configured to shrink

![image](https://user-images.githubusercontent.com/900690/95832901-34807f00-0d3b-11eb-8f63-fd51142a236e.png)

@misolori it also appears when tabs are disabled:

![image](https://user-images.githubusercontent.com/900690/95832933-43ffc800-0d3b-11eb-9c2e-ae443a8c35a8.png)

One thing which is slightly irritating is that the dot disappears when hovering, though that is consistent imho:

![recording (8)](https://user-images.githubusercontent.com/900690/95833108-7b6e7480-0d3b-11eb-8e8d-2d874bf2eb5e.gif)
