### ISSUE TITLE
Show Installed Extensions empty if two extensions with the same name

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#1082]
This issue came  up with looking into changing an extension publisher (sean's spell checker).  If you change the publisher to the MS account (seanmcbreen -> ms-vscode), the user will end up with two extensions under .vscode\extensions which have the same name "Spell" but different publishers and versions.  
Extensions: Install Extensions shows that lower version installed with the Remove X available.  If you uninstall, the later version will show up here.
The issue is that Extensions: Show Installed Extensions shows nothing.  It should probably show both versions of the extension and the user can then clean up the lower version extension. 
From my testing, it appears that the later version extension is the one that is running.

**Comment by gregvanl** [comment]
To reproduce the issue, I installed Sean's spell checker (version 0.4.1) and then made a copy under a new ms-vscode folder and updated the version (0.4.2) and publisher in the package.json.

**Comment by gregvanl** [comment]
I was testing this on release version 0.10.3.  I haven't tried this with a nightly build.

**Comment by egamma** [comment]
This is by design. The market place identifies an extension by the pair publisher.extension name. We show the publisher in the list of extensions so you can distinguish the extension.

**Comment by gregvanl** [comment]
Sorry, I wasn't clearer about the issue.  The problem is that having two extensions with the same name but different publishers (such as would occur if someone takes ownership of an extension or moves to a shared publisher account such as ms-vscode) breaks the Extension: Show Installed Extensions dropdown.
![broken show installed](https://cloud.githubusercontent.com/assets/12818376/11663719/9c03dece-9d92-11e5-926a-6c01d1924499.png)

**Comment by gregvanl** [comment]
On further investigation, as long as the two extensions have different publishing metadata (as would happen if you republish with another account), the Show Installed Extensions behaves correctly.
