### ISSUE TITLE
Git changes are not revealed in explorer

### ISSUE THREAD

**Issue by SharakPL** [microsoft/vscode#108291]
- VSCode Version: 1..49.3
- OS Version: Windows 10

Lately (I think from 1.48) VSCode stopped showing colors and badges if a folder has content changed in any way, especially if there's quite a lot of changes, like 1000+. Now most of the time you have to click on specific folder and reveal it's changed content to have badges and colors updated:

![git-explorer](https://user-images.githubusercontent.com/5007456/94416351-06b60a80-017f-11eb-8cb9-f9bf73079d83.gif)

Another way is to open Source Control tab and reveal files there to update colors and badges in explorer, but still only folders containing files revealed in Source Control have colors updated in explorer. You have to scroll through all of them to update explorer completely:

![git-explorer2](https://user-images.githubusercontent.com/5007456/95431595-b3497680-094d-11eb-9a3a-f30ab2ca7501.gif)

Gifs show only untracked files but it happens with all states.
I have Ryzen 2700 (8 core) and 16 GB of RAM so slow hardware can't be the cause of this. It wasn't couple versions ago on the same hardware where all folders were updated almost instantly.
I'm using git 2.28.0.windows.1.

Steps to Reproduce:

1. Use any project with 1000+ files without git repository and open it in VSCode
2. Open terminal inside Code and run `git init`
3. Explorer marks only visible files as untracked and all closed folders look like nothing changed there.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/duplicate

Yielding to #108292 opened by OP

**Comment by SharakPL** [comment]
@gjsjohnmurray don't know why but I got 404 page on submiting this issue the first time. I didn't notice it was created anyway.

**Comment by saqifalpha** [comment]
Owowoqoqooaoaoaoaoaooaoaoaooaoaoaoaoaoaooaoaoaoaokasjsnswjkakamamakakak
