### ISSUE TITLE
bash for Ubuntu for Windows wouldn't open in the Terminal inside VSCode

### ISSUE THREAD

**Issue by akashdeep-singh** [Microsoft/vscode#10822]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14905

Steps to Reproduce:

1. Open VSCode on Windows
2. Open a command prompt inside VSCode using Ctrl+`
3. Type bash and hit enter

Error: 'bash' is not recognized as an internal or external command, operable program or batch file.

Bash is enabled on my system, and I use it for several things? I see no reason it shouldn't be able to operate from inside VSCode's command prompt because that command prompt gets all the environment variables from system's command prompt.

**Comment by mrmlnc** [comment]
Have you tried this instruction https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration?

**Comment by akashdeep-singh** [comment]
@mrmlnc While these instructions are helpful in changing VSCode's Terminal, they do not solve my particular issue.

On Windows, I can use bash by simply typing bash on a command prompt, and it gets me the bash shell.

VSCode essentially uses the same command prompt, but still the bash command wouldn't work as expected.

**Comment by Tyriar** [comment]
I believe cmd has this built in so that bash will install bash.exe or run it if it exists. There's nothing we can do about it in vscode as I understand it.
