### ISSUE TITLE
To be able to accept all current/incoming changes when solving merge conflicts in a file

### ISSUE THREAD

**Issue by khalyomede** [microsoft/vscode#108295]
When merging a branch, we can accept the current/incoming/both changes.

Sometimes, it happens I already know I need to accept all current (or incoming) changes. I would like to do it using a button on top of the conflicting file, to automatically allow all current changes (and discard the incoming) if I click on an "accept all current" changes.

To discuss if "accept all changes" (which would do an "accept both changes") button would be worth.

**Comment by chrmarti** [comment]
There are context menu actions in the SCM viewlet (https://github.com/microsoft/vscode/issues/53133). Does that address your request?

**Comment by khalyomede** [comment]
Absolutely! Thank you @chrmarti
