### ISSUE TITLE
Markdown Intellisense with multiple identical labels shows non-unique anchors

### ISSUE THREAD

**Issue by gmccullo** [microsoft/vscode#108233]
Issue Type: <b>Bug</b>

See screenshot. Each "item" should have a unique anchor value: "item", "item-1", "item-2" etc. Intellisense just shows the "item" multiple times. The table of contents was generated with an extension just to show how the links should be; it's not relevant to the issue.

![image](https://user-images.githubusercontent.com/26315643/95293453-bb34e800-0873-11eb-869d-16e8ffdfc8da.png)

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.08GB free)|
|Process Argv|--crash-reporter-id 8cee3e0c-4341-4a55-a1e5-058356aa15bb|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
VS Code's built-in markdown support does not provide IntelliSense so this must be coming from an extension

**Comment by gmccullo** [comment]
> VS Code's built-in markdown support does not provide IntelliSense so this must be coming from an extension

If I restart with all extensions disabled it's still a problem.

**Comment by mjbvz** [comment]
Try checking again. Your screenshot shows a code lens with is also not part of VS Code's builtin markdown support

**Comment by gmccullo** [comment]
Well, it's a little different, but still broken:

![image](https://user-images.githubusercontent.com/26315643/95421088-fcdd9580-093c-11eb-9029-73b1f7f4b423.png)

![image](https://user-images.githubusercontent.com/26315643/95421121-0cf57500-093d-11eb-80c6-5e0bf8f498e4.png)

**Comment by mjbvz** [comment]
That is the correct behavior. The document symbols show the text of headers, not their anchor values

**Comment by gmccullo** [comment]
For the dropdown navigator, I agree with you. Not for the markdown link intellisense. It means there's no way to make a link to item #2 or item #3. The link value should be the anchor value, not the label.

**Comment by mjbvz** [comment]
Those are [word based suggestions](https://stackoverflow.com/questions/50890967/disable-word-based-suggestion-in-visual-studio-code), not IntelliSense

Your bug was caused by an extension. File it an issue against that extension

**Comment by gmccullo** [comment]
OK. That's pretty confusing. Thanks.
