### ISSUE TITLE
all angular app slow

### ISSUE THREAD

**Issue by ahmed-aly-aly** [microsoft/vscode#108276]
We have written the neede
Issue Type: <b>Performance Issue</b>

whin open angular app vs code so slow
run command ng serve taka about 15 min to run

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (10.07GB free)|
|Process Argv|D:\ppt\html\cic\angular\cic-app --crash-reporter-id 13f2ba39-28b7-403c-b734-d3eaa4916739|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    78	 24040	code main
    1	   179	  8692	   gpu-process
    0	    82	 11608	   shared-process
    0	   193	 12284	   window (home.component.ts - cic-app - Visual Studio Code)
    0	    65	 13860	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     8	 11404	       C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" start"
    0	    30	  6860	         "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" start
    0	     8	  4380	           C:\WINDOWS\system32\cmd.exe /d /s /c ng serve --open --port 4300
    1	    52	  7060	             node   "D:\ppt\html\cic\angular\cic-app\node_modules\.bin\\..\@angular\cli\bin\ng" serve --open --port 4300
    0	     6	 18896	     console-window-host (Windows internal process)
    0	    14	 19156	     watcherService 
    0	    11	 10956	       console-window-host (Windows internal process)
    0	   182	 20260	     extensionHost
    0	    87	  8292	       electron_node server.js 
    0	    71	 13340	       "C:\Users\itd-ahmed\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\itd-ahmed\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=20260
    1	   172	 13872	       electron_node tsserver.js 
    0	    85	 16704	         electron_node typingsInstaller.js typesMap.js 
    0	    75	 15320	       electron_node dbaeumer.js server.js 
    0	    69	 15964	       electron_node eslintServer.js 
    1	   170	 16700	       "C:\Users\itd-ahmed\AppData\Local\Programs\Microsoft VS Code\Code.exe" c:\Users\itd-ahmed\.vscode\extensions\angular.ng-template-0.1001.0\server --logFile c:\Users\itd-ahmed\AppData\Roaming\Code\logs\20201008T000526\exthost1\Angular.ng-template\nglangsvc.log --logVerbosity terse --ngProbeLocations c:\Users\itd-ahmed\.vscode\extensions\angular.ng-template-0.1001.0\server,d:\ppt\html\cic\angular\cic-app --tsProbeLocations c:\Users\itd-ahmed\.vscode\extensions\angular.ng-template-0.1001.0,d:\ppt\html\cic\angular\cic-app --node-ipc --clientProcessId=20260
    0	    93	 18304	       "C:\Users\itd-ahmed\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\itd-ahmed\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=20260
    0	    70	 18672	       electron_node serverMain.js 
    0	   110	 19080	       electron_node tsserver.js 
    0	    73	 22216	     searchService
    0	    86	 19276	   window (Issue Reporter)
    0	    27	 25596	   crashpad-handler
    0	    42	 25940	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (home.component.ts - cic-app - Visual Studio Code)
|    Folder (cic-app): 85 files
|      File types: ts(23) jpg(9) json(8) svg(7) css(6) html(6) png(4) js(2)
|                  ico(2) browserslistrc(1)
|      Conf files: tsconfig.json(2) package.json(1) tslint.json(1);
```

</details>
<details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
vscode-angular2-files|ale|1.6.4
ng-template|Ang|0.1001.0
path-intellisense|chr|2.3.0
angular-schematics|cyr|4.5.0
vscode-simpler-icons|dav|1.6.5
jshint|dba|0.10.21
vscode-eslint|dba|2.1.8
angular-extension-pack|dog|9.3.0
githistory|don|0.6.11
jquerysnippets|don|0.0.1
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vscode-firefox-debug|fir|2.9.1
auto-rename-tag|for|0.1.4
beautify|Hoo|1.5.0
angular2-switcher|inf|0.3.3
docthis|joe|0.7.1
Angular2|joh|9.1.2
vscode-map-preview|jum|0.5.5
refactorix|kri|0.3.6
image-resizer|luk|0.1.0
json-to-ts|Mar|1.7.5
code-beautifier|mic|2.3.3
Angular-BeastCode|Mik|10.0.3
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
gremlins|nho|0.24.0
arrr|obe|0.1.3
quicktype|qui|12.0.46
csharp2ts|raf|0.0.24
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.4.3
autoimport|ste|1.5.3
code-spell-checker|str|1.9.2
move-ts|str|1.12.0
sass-indented|syl|1.8.12
sass-next|syl|0.0.1
bootstrap4-vscode|the|6.1.0
vscode-icons|vsc|11.0.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.3.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by JacksonKearl** [comment]
Does this reproduce when all extensions are disabled?

**Comment by mjbvz** [comment]
Closing this as without more information, it sounds like an angular issue instead of a VS Code issue (or potentially an issue with one of the angular extension)
