### ISSUE TITLE
[loc][Query][VSCode] More context for "tab"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#10829]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
\n\t\t\t\t\t\tArgument Properties:\n\t\t\t\t\t\t'to': String value providing where to move.\n\t\t\t\t\t\t'by': String value providing the unit for move. By tab or by group.\n\t\t\t\t\t\t'value': Number value providing how many positions or an absolute position to move.\n\t\t\t\t\t

File Name:
src\vs\workbench\browser\parts\editor\editorCommands.nls.resx

Resource ID:
".resx", 0; "editorCommand.activeEditorMove.arg.description"

Query:
Could you clarify the meaning of "tab" here?	
(es)

**Comment by bpasero** [comment]
@mkyjakova tab means a tab in the editor stack (it does NOT mean tab vs whitespace for an editor).
