### ISSUE TITLE
Regression in Insiders: Signature help no longer highlighting current arg in all cases

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#108216]
Issue Type: <b>Bug</b>

NOTES: 
a) It works in vscode 1.49.3 but not in 1.50.0-insider
b) It works in the concat case but not the resourceId case.
c) I'm using the default dark theme in code and insiders

REPRO:
1) Install "Azure Resource Manager Tools" extension (msazurermtools.azurerm-vscode-tools), version 0.12.0
(This is not a bug with the extension)
2) Create the following as a JSON file and open it:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "variables": {
        "v1": "[concat(1, 2, 3, 4)]",
        "v2": "[resourceId('Microsoft.Compute/virtualMachines/extensions', concat(parameters('vmName'),copyIndex(1),'/dscext'))]"
    }
}
```
3) Place the cursor somewhere inside the "'Microsoft.Compute/virtualMachines/extensions'" string 
4) press SHIFT+CMD+SPACE to bring up signature help
EXPECTED: The first arg ("[subscriptionId]") should be bolded to indicate it's the current argument
ACTUAL: It's not bolded

# Stable 1.49.3
![sighelp-code](https://user-images.githubusercontent.com/6913354/95271096-e4ad2f80-07f1-11eb-8684-28a0b1a03cbe.gif)
# Insiders 1.50.0-insider
![sighelp-insiders](https://user-images.githubusercontent.com/6913354/95271094-e37c0280-07f1-11eb-8842-3b665d3c8121.gif)
 
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|-psn_0_4490312 --crash-reporter-id 28a909e2-0b30-47b4-bfa3-dcb1734aca95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
todo-tree|Gru|0.0.183
vscode-azurefunctions|ms-|0.24.1
vscode-azurestorage|ms-|0.10.1
vscode-cosmosdb|ms-|0.15.0
vscode-docker|ms-|1.6.0
vscode-dotnet-runtime|ms-|0.1.2
python|ms-|2020.9.114305
vscode-ai|ms-|0.6.16
azure-account|ms-|0.9.3
vscode-typescript-tslint-plugin|ms-|1.2.3
azurerm-vscode-tools|msa|0.12.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by mjbvz** [comment]
This looks like a consequence of 536ea46187d013839c0f3dc04fee6ba945f90c1a (which fixed #106432)

I'll improve support on our side for this cases where the signature starts or ends with special characters (such as `(` or `)`).

@StephenWeatherford You may also want to switch over to use the index based parameter indexes. These should always be reliable since the externs itself calculates them
