### ISSUE TITLE
Ask for API to get debug console output

### ISSUE THREAD

**Issue by freedomhero** [microsoft/vscode#108235]
Hi, Teams! I want to write some end-to-end tests for my debugger extension, but the current vscode extension APIs seem to be not enough. What I need is to access the output log of debug console after using 'startDebugging' API to start a debug session. Could this be done with any existed api or would you consider to provide some? Thanks.

**Comment by connor4312** [comment]
You can use the [DebugSessionTracker](https://github.com/microsoft/vscode/blob/7a0705650fb71bec1845f9fc67d6065172b58260/src/vs/vscode.d.ts#L11233-L11261) for this and listen to [`output` events](https://microsoft.github.io/debug-adapter-protocol/specification#arrow_left-output-event).

**Comment by freedomhero** [comment]
Thanks, it works.
