### ISSUE TITLE
Snippets aren't trigged without a space before

### ISSUE THREAD

**Issue by nchanged** [Microsoft/vscode#10824]
- VSCode Version: Version 1.4.0 (1.4.0)
- OS Version: MacOS

I am not sure if it's intentional, but very annoying nonetheless.
I have a snippet "then" that creates this code:

````
 then(result => {
        
 })  
```
It works fine when i type " then", however this does not work:
`fn().then`

I get no suggestions!

Javascript/Typescript.

Thanks

**Comment by jrieken** [comment]
@nchanged Can you paste the snippet you are using (esp the prefix) and how do you trigger snippet completions, via TabCompletion, the 'Insert Snippet' command, or via IntelliSense?

**Comment by nchanged** [comment]
![then](https://cloud.githubusercontent.com/assets/1629088/17925564/1f1eb538-69f6-11e6-9ae1-659534247dbe.gif)

@jrieken If press ctrl+space it shows it, but not when i just press "tab" 
Of course, there is another issue (with typescript) if a function return a Promise, it has it's own "then" suggestion. Don't know how to override it

![then2](https://cloud.githubusercontent.com/assets/1629088/17925726/c5dab12e-69f6-11e6-8c26-0063cf130567.gif)

**Comment by jrieken** [comment]
@nchanged Did you enable tab completions? By default is off and you must have something like `"editor.tabCompletion": true`

**Comment by nchanged** [comment]
Yes, same thing...

**Comment by jrieken** [comment]
Thanks - I can repo. Seems to be related to the other content on the line... A simple `then` does it, `a().then` not

**Comment by ramya-rao-a** [comment]
In the latest insiders (dated 8/31), I can still repro this issue

**Comment by jrieken** [comment]
@ramya-rao-a Can you provide some detail? For me this works following these steps

* have a snippet for typescript as outlined [here](https://github.com/Microsoft/vscode/issues/10824#issuecomment-242007851)
* type `then`, dismiss suggest widget if showing, hit `tab` -> snippets expands
* type `a().then` or `foo foo then`, hit `tab` -> snippets expands

![sep-01-2016 11-05-17](https://cloud.githubusercontent.com/assets/1794099/18161910/43caccf2-7034-11e6-9283-84850f52b18f.gif)

**Comment by ramya-rao-a** [comment]
@jrieken I followed the exact same steps 
`a().then` doesn't show the snippet and neither does anything expand on `tab`
I tried both javascript and typescript

After tabbing, if I hit `backspace` to reach the `then`, then I see the option to use the snippet in the intellisense.

Maybe someone else can try?

**Comment by jrieken** [comment]
@ramya-rao-a Since this is an issue with many comments can you please spell out your exact steps

**Comment by ramya-rao-a** [comment]
@jrieken I am out on vacation at the moment, no access to a computer, so cannot provide screenshots etc.
Steps:
1. Added the same snippet 
2. Defined a function a() that does nothing
3. Hit tab after typing  a().then
4. No snippet is expanded, cursor moves ahead
5 Hit backspace until you reach the end of 'then', intellisense shows the option to expand snippet

I wont be in until Tuesday noon PST, so if anyone else is able to verify your fix, feel free to close the issue

**Comment by jrieken** [comment]
@ramya-rao-a Did you enable tab completion?

**Comment by ramya-rao-a** [comment]
@jrieken My bad, I missed that. Closing as verified
