### ISSUE TITLE
Inactive regions support shortcut key hiding and display functions 

### ISSUE THREAD

**Issue by jay-zhou-yan** [microsoft/vscode#108232]
Issue Type: <b>Feature Request</b>

In order to facilitate the reading of c/c++ code, it is required to support the hidden inactive area function through shortcut key commands, so as to hide invalid precompiled macro code blocks to facilitate code reading. I have seen this feature on SciTools Understand, which is very good for embedded development engineers. I strongly request that this feature be added later.

**By the way**, I have reported this request to the c/c++ plug-in, but they suggested that I want you to report this request, and the c/c++ plug-in thinks you can implement this feature. The link I report to c/c++ is as follows: https://github.com/microsoft/vscode-cpptools/issues/6258

I want to use VSCode as the main embedded environment, which will be an amazing feature.

Thank you.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041

**Comment by aeschli** [comment]
@colengms Extensions can fold by calling the `editor.fold` and `editor.unfold` commands. The commands take an argument object that lets you select the lines to fold:

`vscode.commands.executeCommand('editor.fold', { selectionLines: [0] })`

See https://code.visualstudio.com/api/references/commands for more arguments.

The C++ extension as the provider of the folding regions knows the lines to fold. If it's of any help I can add a `regions` arguments to the commands as well.

IMO the requests feature is better implemented by the C++ extension as the concept as I'm not aware of other language extensions that also have the inactive/hidden areas.
