### ISSUE TITLE
Unnatural dialog placement

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#108273]
* create a file
* discard it from git
* VS Code Web shows a dialog in the center of the window (this feels unnatural to me):

<img width="1231" alt="Screen Shot 2020-10-07 at 23 14 13" src="https://user-images.githubusercontent.com/5047891/95388602-d561db00-08f2-11eb-94d4-68b313d33be2.png">

---
VS Code Desktop shows a dialog near the top of the window:

<img width="923" alt="Screen Shot 2020-10-07 at 23 13 08" src="https://user-images.githubusercontent.com/5047891/95388516-aea3a480-08f2-11eb-96b5-a98e4e7bad4e.png">

**Comment by bpasero** [comment]
> VS Code Desktop shows a dialog near the top of the window

No, only on macOS, not on Windows/Linux.

**Comment by sbatten** [comment]
macOS changed where the dialogs show and shape so not sure if this is still relevant.
