### ISSUE TITLE
Completing function signatures in TypeScript breaks when writing JSX

### ISSUE THREAD

**Issue by lifeiscontent** [microsoft/vscode#108284]
Issue Type: <b>Bug</b>

The Option for VSCode to complete function signatures is very cool, but when writing JSX (tsx) it breaks.

e.g.

when Foo is not defined, it takes this:

```tsx
<Foo>
```
and turns it into

```tsx
<Foo(props)>
```

once it imports

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.50GB free)|
|Process Argv|. --crash-reporter-id d8a6bc35-5bf7-4028-9abf-4f8d3e3304cb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.6.7
vscode-database|baj|2.2.3
markdown-checkbox|bie|0.1.3
vscode-styled-jsx|bla|2.0.0
solargraph|cas|0.21.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-ruby-test-adapter|con|0.7.1
vscode-test-explorer-status-bar|con|1.1.2
vscode-eslint|dba|2.1.8
xml|Dot|2.5.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.1
auto-rename-tag|for|0.1.4
vscode-pull-request-github|Git|0.20.0
todo-tree|Gru|0.0.183
vscode-test-explorer|hbe|2.19.1
vscode-test-explorer-liveshare|hbe|1.0.5
vscode-peacock|joh|3.8.0
vscode-styled-components|jpo|0.0.32
chat|kar|0.35.0
vscode-github|Kni|0.30.4
graphql-for-vscode|kum|1.15.3
vscode-language-babel|mgm|0.0.30
ruby-rubocop|mis|0.8.4
HTMLHint|mka|0.10.0
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
vscode-postgresql|ms-|0.3.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2902
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.11
ruby|reb|0.27.0
vscode-jest-test-adapter|rtb|0.2.0
rust|rus|0.7.8
shellcheck|tim|0.11.0
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
codetour|vsl|0.0.35
gistfs|vsl|0.1.8
vscode-ruby|win|0.27.0
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by olajohn-ajiboye** [comment]
Hi! I would like to try this issue. Do you think it is beginner-friendly? Any ideas where to start? Danke!

**Comment by mjbvz** [comment]
Closing in favor of https://github.com/microsoft/TypeScript/issues/51758
