### ISSUE TITLE
Encryption service is not sandbox ready

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108230]
Because it is declared in `workbench.desktop.main.ts`. I tried really hard to make this easier for us with those comments but guess it just needs a bit of getting used to it:

https://github.com/microsoft/vscode/blob/dafce599a6f107f56ca1f414a6448b18bbcc9377/src/vs/workbench/workbench.desktop.main.ts#L88-L97

**Comment by RMacfarlane** [comment]
Thank you for catching this!
