### ISSUE TITLE
[php] Support embedded Javascript (and HTML)

### ISSUE THREAD

**Issue by Sirzechs** [Microsoft/vscode#10825]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. open a php file or create new one
2. type methods such as `console.log()` or `.prev()` `.next()`

![vscode-js-php](https://cloud.githubusercontent.com/assets/7927156/17887802/c69e5226-6930-11e6-9061-1ace44874020.png)

**Comment by aeschli** [comment]
Also related to #11081

**Comment by octref** [comment]
Verified to work. @Sirzechs  you can download [Insider](https://code.visualstudio.com/insiders) or wait for the Nov release.
