### ISSUE TITLE
vscode won't cleanup after itself

### ISSUE THREAD

**Issue by ivanjaros** [microsoft/vscode#108244]
As a, typical, windows program, when i uninstall vscode and install it later on agian, i get my old settings, even extensions, back on again. i think this is a massive privacy issue that should not be happening in 2020. it not ok to happen in a private computer but it is absolutely horribly wrong on shared computers whe one user's data can be exposed to another user after unmeasurable period of time.

**Comment by joaomoreno** [comment]
#66837
