### ISSUE TITLE
[css] CSS unknown property for "content-visibility"

### ISSUE THREAD

**Issue by vladmandic** [microsoft/vscode#108272]
CSS property `content-visibility` was added to Chrome 85 (and thus in Edge as well) <https://www.chromestatus.com/feature/4613920211861504>  
but is marked in VSCode as:

`Unknown property: 'content-visibility'`

Environment: VSCode Insiders (Date: 2020-10-07T01:00:44.765Z) on Windows 10 x64 Build 19042

**Comment by formikaio** [comment]
+1

**Comment by dtruffaut** [comment]
{
	"resource": "................/css/index.css",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "unknownProperties",
	"severity": 4,
	"message": "Unknown property: 'content-visibility'",
	"source": "css",
	..............
}

**Comment by aeschli** [comment]
Fixed in latest insiders
