### ISSUE TITLE
Unable to open vscode insiders Ubuntu 18.04

### ISSUE THREAD

**Issue by Devon7925** [microsoft/vscode#108225]
Happens both from gui and from terminal.
- VSCode Version: 1.50.0-insider snap build
- OS Version: Ubuntu 18.04
Log from verbose mode:
[11547:1006/220446.913448:ERROR:appcenter_api.cc(52)] expecting appcenter url prefix
libGL error: MESA-LOADER: failed to open r600 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open r600 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
[11547:1006/220446.962474:ERROR:gl_context_glx.cc(187)] Failed to create GL context with glXCreateNewContext.
[11547:1006/220446.962586:ERROR:gpu_info_collector.cc(76)] gl::init::CreateGLContext failed
[11547:1006/220446.962634:ERROR:gpu_info_collector.cc(208)] Could not create context for info collection.
[11547:1006/220446.962690:ERROR:gpu_init.cc(70)] gpu::CollectGraphicsInfo failed.
[11547:1006/220446.965508:WARNING:x11_util.cc(1520)] X error received: serial 205, error_code 161 (GLXBadContext), request_code 153, minor_code 6 (X_GLXIsDirect)
[11547:1006/220446.966336:WARNING:x11_util.cc(1520)] X error received: serial 204, error_code 2 (BadValue (integer parameter out of range for operation)), request_code 153, minor_code 24 (X_GLXCreateNewContext)
[11547:1006/220446.966466:ERROR:viz_main_impl.cc(152)] Exiting GPU process due to errors during initialization
[11553:1006/220446.970180:ERROR:appcenter_api.cc(52)] expecting appcenter url prefix
[11561:1006/220447.025359:ERROR:appcenter_api.cc(52)] expecting appcenter url prefix
[main 2020-10-07T04:04:47.039Z] Sending env to running instance...
[main 2020-10-07T04:04:47.056Z] [
  'Error: Image could not be created from /snap/code-insiders/542/usr/share/code-insiders/resources/app/resources/linux/code.png',
  '    at new r (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:536:712)',
  '    at u._createInstance (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:286:888)',
  '    at u.createInstance (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:286:309)',
  '    at t.openInBrowserWindow (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:608:417)',
  '    at t.doOpenEmpty (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:599:237)',
  '    at t.doOpen (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:598:640)',
  '    at t.open (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:594:341)',
  '    at g.startOpenWindow (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:555:658)',
  '    at g.start (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:554:499)',
  '    at Object.call (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:192:81)',
  '    at I.onPromise (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:183:929)',
  '    at I.onRawMessage (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:183:403)',
  '    at /snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:182:612',
  '    at l.fire (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:52:801)',
  '    at /snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:198:187',
  '    at l.fire (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:52:801)',
  '    at p.acceptChunk (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:196:752)',
  '    at /snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:196:104',
  '    at Socket.t (/snap/code-insiders/542/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:206:847)',
  '    at Socket.emit (events.js:223:5)',
  '    at addChunk (_stream_readable.js:309:12)',
  '    at readableAddChunk (_stream_readable.js:290:11)',
  '    at Socket.Readable.push (_stream_readable.js:224:10)',
  '    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)'
]
[main 2020-10-07T04:04:47.058Z] Lifecycle#kill()

Steps to Reproduce:

1. Try to open vs code
2. Notice it doesn't open

Does this issue occur when all extensions are disabled?: Yes

**Comment by Devon7925** [comment]
I did check, and its not a duplicate of that one or #107419

**Comment by deepak1556** [comment]
```
libGL error: MESA-LOADER: failed to open r600 (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open r600 (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
```

gpu process crash due to the above missing drivers. Can you check if the app starts if you use the archive version `.tar.gz` https://code.visualstudio.com/insiders/

**Comment by Devon7925** [comment]
Not sure what changed but it works now
