### ISSUE TITLE
Formatting issue in terminal

### ISSUE THREAD

**Issue by jrose529** [microsoft/vscode#108274]
**Repro Instructions:**
To reproduce bug, install the attached .vsix package. Open the command palette and execute "Bug: Open Kit Console". When the terminal opens, sometimes the text will have line breaks and other times it will appear fine. The file where the text is being read from has no breaks, and copy/pasting the text from the terminal will paste without breaks. If this bug doesn't occur on first instance, continue to kill and open new terminals.

**Description:**
The extension has the single command that opens a terminal via window.CreateTerminal(). This terminal is running a node shell to execute a .js script that reads a .txt file and prints to console. Using a python shell also produces the same bug.

**Notes**
VSCode Version: 1.49.3
This bug ONLY occurs on Windows(I'm running Windows 10), but runs fine on MacOS.
The expected path for node.js is "/usr/local/bin/node" on MacOS and "c:\\Program Files\\nodejs\\node.exe" on Windows.

[logBug-1.0.0.vsix.zip](https://github.com/microsoft/vscode/files/5343895/logBug-1.0.0.vsix.zip)

**Comment by jrose529** [comment]
@rzhao271 Hell

**Comment by jrose529** [comment]
@rzhao271 Hello, is there an update on this bug fix?

**Comment by Tyriar** [comment]
This is what happens:

![image](https://user-images.githubusercontent.com/2193314/104774016-c927be00-572a-11eb-8edd-3e2a7c4619af.png)

Looks like it's probably conpty wrapping at 80 columns on their side since we're not initializing it with the right dimensions.

**Comment by jrose529** [comment]
@Tyriar So I'm not seeing the bug anymore. I just wanted to confirm if this was addressed in an update?

**Comment by Tyriar** [comment]
Good to hear, I believe we did recently tweak how the initial dimensions of the terminal are set.

**Comment by jrose529** [comment]
@Tyriar Can you find out what VSCode version includes that fix?

**Comment by rzhao271** [comment]
Still repros for me

Version : 1.54.0-insider (user setup)
Commit : 59c31364c707ee962cc594389966801af4ce69bd
Date : 2021-02-25T07:44:40.955Z
Electron : 11.3.0
Chrome : 87.0.4280.141
Node.js : 12.18.3
V8 : 8.7.220.31-electron.0
OS : Windows_NT x64 10.0.19042

![still-there](https://user-images.githubusercontent.com/7199958/109203673-4f3b1980-7759-11eb-9a29-8fa0a622a568.PNG)

**Comment by jrose529** [comment]
In case it helps, the two environments where I'm not seeing it are below.

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by rzhao271** [comment]
Here's a case where the output still shows up with line breaks:

![logbug](https://user-images.githubusercontent.com/7199958/120868897-ed553180-c549-11eb-9c1f-0fc9f2956425.PNG)

I'm unable to reproduce https://github.com/microsoft/vscode/issues/108274#issuecomment-786132442, though.

**Comment by Tyriar** [comment]
@rzhao271 it's not clear exactly what's happening and what the repro is there, can you open another issue?

**Comment by rzhao271** [comment]
The repro is the same as https://github.com/microsoft/vscode/issues/108274#issue-716862632, but with a smaller terminal window width. I just tried again and couldn't reproduce the issue, though, so no action needed.
