### ISSUE TITLE
Opening large csv files is slow (compared to vim)

### ISSUE THREAD

**Issue by SujeathPareddy** [microsoft/vscode#108221]
I use code for medium-sized data analysis. Sometimes I have to open a csv file to inspect the header or other manual work. 

I find that code hangs a lot when opening large csv files. An example of such a csv is available for download [here](https://androzoo.uni.lu/static/lists/latest.csv.gz). I have a system with sufficient ram to hold the whole file in memory. When it finally opens, I can scroll and navigate just fine. Vim takes around 2-3 seconds to open, but code takes > 15 on my system.

My best guess is that code tries to read the whole file into a buffer or tries to parse it somehow. Maybe vim just reads the first N bytes or so.

OS: Mac OS Catalina
Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:54:06.165Z (4 days ago)

Extensions:
Python
Intellicode
Remote Server (ssh)
ESLint
TSLint
Hex Editor
Visual Studio Keymap
C/C++

The setting "editor.largeFileOptimizations" is true.

**Comment by rebornix** [comment]
> My best guess is that code tries to read the whole file into a buffer or tries to parse it somehow. Maybe vim just reads the first N bytes or so.


you are correct, currently we load the whole content into memory when opening a file and our text buffer infra relies on that.
