### ISSUE TITLE
Web: consider using beforeunload event sparsely

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#108228]
Using `unload` and `beforeunload` events is not recommended: https://developers.google.com/web/updates/2018/07/page-lifecycle-api#the-beforeunload-event
In order to detect last page interaction one can use `pagehide` and `visibilitychange` events instead: https://developers.google.com/web/updates/2018/07/page-lifecycle-api#advice-hidden
`beforeunload` event should be installed only when there is unsaved changes and removed when there are not

**Comment by bpasero** [comment]
@akosyakov I assume you are referring to our use for the web version of VSCode? Can you be more specific of where in code you think we are using it wrong and what the suggestion is?

**Comment by akosyakov** [comment]
Yes, it is about the web version. I was trying to integrate it in iframe and discover different issues among one of them was that if the iframe is removed programmatically then `beforeunload` event never happens. I was investigating then what was going on `on(Will)Shutdown` events which Code triggers on `beforeunload` and mainly 2 things are happening:
- some participant can veto the closing,
- or some state gets saved: https://github.com/microsoft/vscode/blob/18a6a88ee3b11384a5b7fb2e64ae0ecd29eee2d3/src/vs/workbench/browser/workbench.ts#L230

According to [the article mentioned above](https://developers.google.com/web/updates/2018/07/page-lifecycle-api#the-beforeunload-event) the second use case is valid. Although they recommend to install `beforeunload` only when there is really dirty state and remove afterwards to avoid breaking the page cache, not always as it now.

But for first use case using `beforeunload` is not recommended, instead they recommend to treat `hidden` as the end of user session and store state at this moment. I was suggesting to have another lifecycle event indicating for it and leave `onbeforeunload` responsible only for warning a user about unsaved changes. In use case with iframe it would let me first hide iframe to store state and then remove it. I can imagine also some issues with codespaces like: you leave the tab with codespace, work in another tab, in the meantime the codespace times out. When you close the codespace tab would it be able to store any remote state without the server?

**Comment by bpasero** [comment]
@akosyakov if I understand the articles correctly, `beforeunload` should:
* only be listened to when the page should prevent closing via the dialog
* not be listening if it is known that no prevention is needed

And then use the page lifecycle events to:
* listen to persist state as needed

Does that sound right?

We have to support a lot of browsers, not only Chrome/FF, so I am not sure if the page lifecycle events are supported consistently in all. With that, `beforeunload` seems to me the safer choice for now until all browsers are on par.

> I can imagine also some issues with codespaces like: you leave the tab with codespace, work in another tab, in the meantime > the codespace times out. When you close the codespace tab would it be able to store any remote state without the server?

Yes, for that reason any critical state is persisted periodically every couple of seconds. This includes dirty editors and all UI state. 

What we really would like to have is browser API to do a long-running operation when the browser page becomes hidden or closed, but for performance reasons, this is not really on the radar or there are some alternatives suggested like service workers.

**Comment by akosyakov** [comment]
> Does that sound right?

correct 

> Yes, for that reason any critical state is persisted periodically every couple of seconds. This includes dirty editors and all UI state.

👍 then it is indeed not a big issue

**Comment by bpasero** [comment]
I am currently not planning to change this until browser vendors fully deprecate `onBeforeUnload`.
