### ISSUE TITLE
Move tab to new window

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#108341]
So many times in the past few months, I've tried to drag a tab out of the window to create a new window and move it to that, or right-clicked a tab to find a "Open in new window" menu item. Can you add one? I don't know why I keep thinking/assuming it exists, but it doesn't, and it'd be great if it did.

**Comment by JacksonKearl** [comment]
This is basically [this](https://github.com/microsoft/vscode/issues/10121) (out most upvoted request ever).

The workaround is "Duplicate Workspace in New Window" 
![image](https://user-images.githubusercontent.com/8586769/95517617-2ebf1e00-0976-11eb-9b1a-188acdabaa7f.png)

Which will open the workspace in a new window, in which you can open the tab. there are also some extensions available that add a context menu item for this if you search "tab in new window" in the market place.

**Comment by sdegutis** [comment]
They're not quite the same issue. Moving the current tab to a new window is semantically different than reopening the workspace in a new window.

Often, opening a file will open it in the current workspace when it's intended to open it in a new window/workspace, so moving it out fixes that. This is just one example.

The extensions you mentioned, at least the most popular one I found, assume that the tab belongs to a file, but the tab may be an unsaved document that the user wants to move to a new window.

**Comment by JacksonKearl** [comment]
I see, does "File: Open Active File in New Window" do what you want?

**Comment by sdegutis** [comment]
With an unsaved file, it says "The active editor must contain an openable resource." That's the same as my third paragraph in the last thing.

**Comment by JacksonKearl** [comment]
passing to @bpasero for the issue of not being able to open an untitled file in a new window.

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.
