### ISSUE TITLE
keychain access keeping pop up，even  input password

### ISSUE THREAD

**Issue by Mark3K** [microsoft/vscode#108361]
Issue Type: <b>Bug</b>

keychain access dialog keeping pop up，even  after I input my password

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 5, 5|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv|. --crash-reporter-id 4256980a-8fa2-4711-b9aa-8dbc87a72bfc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-hie-server|ala|0.2.1
better-toml|bun|0.3.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.10
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
go|gol|0.17.2
haskell-linter|hoo|0.0.6
language-haskell|jus|3.3.0
rust-analyzer|mat|0.2.336
python|ms-|2020.9.114305
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
cpptools|ms-|1.0.1
vetur|oct|0.28.0
rust|rus|0.7.8
vscode-lldb|vad|1.5.3
vim|vsc|1.17.1
gitblame|wad|5.0.0
markdown-all-in-one|yzh|3.3.0
material-theme|zhu|3.9.3
vscode-proto3|zxh|0.4.2

(1 theme extensions excluded)

</details>

**Comment by jogo-** [comment]
Duplicate #108352
