### ISSUE TITLE
Unable to check for updates

### ISSUE THREAD

**Issue by Elijah-trillionz** [microsoft/vscode#108385]
Issue Type: <b>Bug</b>

When i try checking for updates, it always return net:ERR:aborted when there is a strong connection

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:33:57.013Z)
OS version: Windows_NT ia32 6.1.7600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T5550  @ 1.83GHz (2 x 1828)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|1.99GB (0.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.8.0
prettier-vscode|esb|5.5.0
material-icon-theme|PKi|4.3.0
LiveServer|rit|5.6.1

</details>

**Comment by joaomoreno** [comment]
Can you access `update.code.visualstudio.com` from a browser?

Do other features work?
