### ISSUE TITLE
Error while starting Settings Sync: No authentication provider 'github' is currently registered

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#108319]
On Mac, when I try to sync settings, which requires login first, I get this error: `Error while starting Settings Sync: No authentication provider 'github' is currently registered`. Which is quite similar to this one. expect @carlocardella seems already get the Github logged in.

Both of the auto-redirect and manually copy paste generated token did not work.
I've already checked Keychain access, seems like there is nothing related to vscode.
Any idea on how to solve this? please.

![image](https://user-images.githubusercontent.com/25129308/95478843-a617a080-09bc-11eb-84d9-3cc4ef2b6f22.png)

_Originally posted by @PulsGarney in https://github.com/microsoft/vscode/issue_comments/705649913_

**Comment by yusufdeepwork** [comment]
I have the same issue at Linux

**Comment by yusufdeepwork** [comment]
> I have the same issue at Linux

I have solved .I have created token via my github profile and I have copied its and pasted to vs code's token area

**Comment by renkun-ken** [comment]
Same here.

I also got 
<img width="527" alt="image" src="https://user-images.githubusercontent.com/4662568/95659624-d5f9ac00-0b54-11eb-959c-aa149a5dc551.png">

**Comment by swd543** [comment]
I have this issue on Clear Linux with Visual Studio Code stable.

**Comment by smartmark-pro** [comment]
I have the same issue at windows 10, but I tried a few more times, and it worked miraculously. maybe it was a problem with the previous link redirection

**Comment by owenthereal** [comment]
I have this issue on Fedora with 1.50.1

**Comment by jyeray** [comment]
I had the same issue with Ubuntu after install vscode via snap. Copy the token and remove the trailing white space at start and final from before use it worked for me.

**Comment by PulsGarney** [comment]
> Same here.
> 
> I also got
> <img alt="image" width="527" src="https://user-images.githubusercontent.com/4662568/95659624-d5f9ac00-0b54-11eb-959c-aa149a5dc551.png">

had never seen this before, could be another issue

**Comment by PulsGarney** [comment]
Somehow I manage to login with the latest release now, with the exact procedure I did before.
I think it is fixed on Mac now. 👍

**Comment by RMacfarlane** [comment]
Can others who are seeing this issue (specifically, "No authentication provider 'github' is currently registered", not the 801 error) try using the [insider's edition](https://code.visualstudio.com/insiders/) of VSCode? Do you see the problem there as well?

**Comment by tsgsz** [comment]
Me too

**Comment by danielfazlijevic** [comment]
> I had the same issue with Ubuntu after install vscode via snap. Copy the token and remove the trailing white space at start and final from before use it worked for me.

This worked for me.

**Comment by RMacfarlane** [comment]
I am tentatively closing this since it seems people have been able to sign in. The original problem in this issue is specifically the "No authentication provider 'github' is currently registered" error, I believe I have fixed it. The 801 error is tracked here: https://github.com/microsoft/vscode/issues/108304

**Comment by zhanglongqi** [comment]
I still have the same issue:

```
Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:16:10.374Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic
```

**Comment by amingilani** [comment]
Hello, experiencing the same issue on MacOS, even creating a custom token does not work.

**Comment by tbenst** [comment]
I see the same error on a fresh install of the latest `.deb`, version `1.51.1`, on Ubuntu 18.04. 

https://github.com/microsoft/vscode/issues/108304 can be fixed by:
```
rm -rf ~/.vscode ~/.vscode-server ~/.config/Code
```
