### ISSUE TITLE
I dont get typescript errors in the problems tab

### ISSUE THREAD

**Issue by melvsparks** [microsoft/vscode#108330]
Issue Type: <b>Bug</b>

1. Open the app
2. Wait a few seconds
3. The failure prompt shows up (typescript language service died 5 times)

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:08:02.231Z)
OS version: Windows_NT ia32 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (17.23GB free)|
|Process Argv|--crash-reporter-id 320c9dd0-a9ee-4550-8653-1596456dccb2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
es7-react-js-snippets|dsz|3.0.0
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.1
RelativePath|jak|1.4.0
kusto-syntax-highlighting|jos|1.0.1
sort-typescript-imports|mic|1.4.1
vscode-asa|ms-|0.7.0
csharp|ms-|1.23.2
azure-account|ms-|0.9.3
cpptools|ms-|1.0.1
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.0.1
ejs-language-support|Qas|0.0.1
project-snippets|reb|0.5.0
vscode-scope|yiw|0.0.21

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by melvsparks** [comment]
I was able to finally get this downloaded and tested. It looks like it works without even having to disable the extensions. Thanks
