### ISSUE TITLE
AbstractDebugAdapter.onMessage checks for existing eventCallback instead of messageCallback

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#108339]
I believe there's a typo in `AbstractDebugAdapter`:

https://github.com/microsoft/vscode/blob/6bebcbb58d95e59ffde0e372888c5eea3995bf82/src/vs/workbench/contrib/debug/common/abstractDebugAdapter.ts#L43-L48

I'm pretty sure that should be `if (this.messageCallback)`, not `if (this.eventCallback)`

**Comment by weinand** [comment]
Thanks for spotting this.
