### ISSUE TITLE
Ctrl+F does not work to bring up search on update to 1.50

### ISSUE THREAD

**Issue by roa-nyx** [microsoft/vscode#108344]
Issue Type: <b>Bug</b>

`Ctrl+F` in editor does not work to bring up search since update to 1.50

`Ctrl+Shift+F` still brings up search in all files.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (5.41GB free)|
|Process Argv|C:\_bunker\4klick\CM --crash-reporter-id 4f0cfeed-1899-4534-99dc-3679fb8c95af|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by roa-nyx** [comment]
I think the keybinding is still correct
![image](https://user-images.githubusercontent.com/8572438/95516484-4d7cdf00-098d-11eb-81f0-e529104135de.png)

**Comment by JacksonKearl** [comment]
Works for me... do you see anything logged to console? And does this reproduce with all extensions disabled?

**Comment by roa-nyx** [comment]
I had extensions disabled before

The Log (Window) has a bunch of lines:
```
[2020-10-08 17:38:53.711] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-10-08 17:38:53.736] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-10-08 17:39:20.728] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-10-08 17:39:20.728] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-10-08 17:39:25.729] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-10-08 17:39:25.729] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-10-08 17:39:30.731] [renderer1] [info] Setting search error: XHR timeout: 5000ms
[2020-10-08 17:39:30.732] [renderer1] [info] Setting search error: XHR timeout: 5000ms
```

Not sure if this is relevant. Is there another log I should check?

I just tried "recording keys" in the keybind editor, and pressing "Ctrl+F" shows just `"ctrl"`

I wonder if this is a problem with a keyboard layout or a program with conflicting keybind?

**Comment by roa-nyx** [comment]
I have verified Ctrl+F doesn't work for me in any app. This must be an issue on my end. Apologies.

**Comment by JacksonKearl** [comment]
No worries :)
