### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by bestGao** [microsoft/vscode#108353]
Issue Type: <b>Bug</b>

In windows 10 64bit operating system, it crashes almost every time I open vscode, any operation is unresponsive, and the pop-up window appears again after 30 seconds

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (8.21GB free)|
|Process Argv|--crash-reporter-id 9dec0f7a-2100-4c43-8f57-a52aa0672476|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.14.1
flutter|Dar|3.15.0
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
vscode-language-pack-zh-hans|MS-|1.49.2
vetur|oct|0.28.0
vscode-icons|vsc|11.0.0
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?
