### ISSUE TITLE
The TypeScript language service died 5 times right after it got started

### ISSUE THREAD

**Issue by VILLAN3LL3** [microsoft/vscode#108357]
Issue Type: <b>Bug</b>

Error occurs since latest VS Code Update right after starting VS Code and loading Angular 10 project.

Error message:

The TypeScript language service died 5 times right after it got started. The service will not be restarted.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (18.50GB free)|
|Process Argv|--crash-reporter-id 480134a1-c648-43c5-8a13-6caddf48fb79|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
html-snippets|abu|0.2.1
project-manager|ale|11.3.0
vscode-angular2-files|ale|1.6.4
ng-template|Ang|0.1001.0
ngx-translate-lookup|apk|1.3.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.37.1
jshint|dba|0.10.21
vscode-eslint|dba|2.1.10
git-extension-pack|don|0.1.3
githistory|don|0.6.11
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.1
vscode-firefox-debug|fir|2.9.1
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
angular-essentials|Gyd|0.1.3
javascript-essentials|Gyd|0.0.7
typescript-essentials|Gyd|0.2.2
web-design-essentials|Gyd|0.4.2
Angular2|joh|9.1.2
vscode-peacock|joh|3.8.0
css-snippets|joy|1.0.2
better-powershell-syntax-highlighting|jus|0.0.2
google-fonts|lio|0.0.1
vscode-azurestorage|ms-|0.10.1
vscode-docker|ms-|1.6.0
azure-account|ms-|0.9.3
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.1
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
color-highlight|nau|2.3.0
angular-console|nrw|14.0.0
vscode-css-peek|pra|4.0.0
typescript-hero|rbb|3.0.0
LiveServer|rit|5.6.1
ngx-translate-zombies|sev|0.0.1
generate-translation|thi|0.0.10
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
JavaScriptSnippets|xab|1.8.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by VILLAN3LL3** [comment]
I get the same issue when using the Angular IDE instead of VS Code

**Comment by thanoskrg** [comment]
I had the exact same problem after upgrading my VS Code to version 1.50.0 and I managed to fix it by doing the following:

1. Open `Command Palette`
2. Select `Extensions: Show Built-in Extensions`
3. Ensure that `TypeScript and JavaScript Language Features` & `TypeScript Language Basics` extensions are both **enabled**

Hope this fixes the problem for you too.

**Comment by VILLAN3LL3** [comment]
Today, without having changed anythigh, the issue does not occur anymore ¯\_(ツ)_/¯
