### ISSUE TITLE
Unknown Error on Sync settings

### ISSUE THREAD

**Issue by Hinaxnitro** [microsoft/vscode#108373]
Issue Type: <b>Bug</b>

System Language: Japanese
Press 'Sign in to Sync Settings' button in Account menu
Use 'Sign in with Microsoft'
Sign in with Microsoft account and Close the browser

VS Code version: Code - Insiders 1.51.0-insider (f5d3ba4d61146b78f0c75c82f3f85232d3409bc1, 2020-10-09T05:34:54.647Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (10.28GB free)|
|Process Argv|--crash-reporter-id ceb31a55-e545-4df7-96d4-a89f50abfc34|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-povray|jma|0.0.11
apex-lightbulbs|nch|1.2.0
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.10

</details>

**Comment by sandy081** [comment]
Can you please provide following logs from Output view ie., available in the section in the bottom

- Settings Sync
- Account
- Open developer tools (F1 > Toggle Developer Tools) and check if there are any errors in console?

**Comment by Hinaxnitro** [comment]
From developer tools console:
[-1602292854646.log](https://github.com/microsoft/vscode/files/5358220/-1602292854646.log)
From Log(Settings Sync) in output
[userDataSyncLog.txt](https://github.com/microsoft/vscode/files/5358222/userDataSyncLog.txt)

**Comment by sandy081** [comment]
Seems these logs are not while the error has occurred.

Can you please open above logs and capture them while issue is being reproduced?

**Comment by Hinaxnitro** [comment]
I tried to reproduce the issue today, but I couldn't reproduce it and I successfully signed in to my account multiple times.
