### ISSUE TITLE
Support Search/filtering on test panel

### ISSUE THREAD

**Issue by ahyerman** [microsoft/vscode#108334]
I'd love the ability to search for a specific test or filter tests from the test panel. When there's many tests in a project, it can be difficult to find the specific tests I'd like to run.

**Comment by JacksonKearl** [comment]
What extension are you using to populate the test view?

**Comment by ahyerman** [comment]
@JacksonKearl sorry for the delayed response. Using Python Extension for VS Code and Pytest

**Comment by JacksonKearl** [comment]
cc @connor4312

**Comment by connor4312** [comment]
\extPython

**Comment by ahyerman** [comment]
Duplicate of microsoft/vscode-python#14886
