### ISSUE TITLE
Verifying dialog won't close

### ISSUE THREAD

**Issue by newsonaut** [microsoft/vscode#108356]
Issue Type: <b>Bug</b>

When I update on macOS, I get two "Verifying Visual Studio Code" dialogs. One has a progress bar that works normally and goes away when it's done. The other does nothing and can't be dismissed. Restarting my computer seems to be the only way to get rid of it.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.63GB free)|
|Process Argv|-psn_0_5481786 --crash-reporter-id a5c549c0-3805-4102-8eba-f250c24238f6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
bracket-pair-colorizer-2|Coe|0.2.0
make-hidden|dev|3.0.3
prettier-vscode|esb|5.7.1
vscode-todo-plus|fab|4.18.0
LiveServer|rit|5.6.1
remove-empty-lines|use|0.0.6
highlight-matching-tag|vin|0.10.0
city-lights-icon-vsc|Yum|1.1.3

(2 theme extensions excluded)

</details>

<img width="512" alt="Screen Shot 2020-10-08 at 8 44 21 PM" src="https://user-images.githubusercontent.com/24844892/95541239-b7a27d80-09a7-11eb-9c84-c21eaef2dd18.png">

**Comment by deepak1556** [comment]
Can you provide a screen recording of the issue, you can use a older version from https://code.visualstudio.com/updates/v1_49 and update it. Thanks!

**Comment by newsonaut** [comment]
I tried this but was unable to reproduce the issue. I’ll wait for the next update and do a screen recording.

Mark

**Comment by newsonaut** [comment]
Looks like it was fixed in the latest update. Didn't see the issue this time.
