### ISSUE TITLE
opening Xcode project does not open the actual project, shows the content of the descriptor only

### ISSUE THREAD

**Issue by scaramushe** [microsoft/vscode#108303]
- VSCode Version:1.49.3
- OS Version:Darwin x64 19.5.0

Steps to Reproduce:
1. create a simple Xcode project
2. save it
3. open the resulting .xcodeproj in VSCode

What opens is the content of xcodeproj and not the actual code files that are described by them:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/72554978/95456405-f1f42680-0977-11eb-8355-a19b91a8bfbe.png">

Does this issue occur when all extensions are disabled?: Yes/No
YES

**Comment by JacksonKearl** [comment]
We don't natively support xcode's project format.. if you know where the files are on your disk, opening VS Code to that directory should allow you to work on them.
