### ISSUE TITLE
Odd "logo" string in Google marketplace results

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#108321]
- VSCode Version: n/a
- OS Version: n/a

Steps to Reproduce:

1. Google "VSCode Chrome Debugger"
2. See additional `logo` string in search result title

![image](https://user-images.githubusercontent.com/8599/95479861-16cca780-0940-11eb-8b9c-7c85ec8edcb4.png)

Works fine in Bing.

Weirdly, adding `"marketplace"` shows a result without the `logo`

![image](https://user-images.githubusercontent.com/8599/95480887-4203c680-0941-11eb-8e1e-17f68e355925.png)

**Comment by digitarald** [comment]
It seems like Google's search bot occasionally picks up the `h1` from the extension readme, so this is extension specific.

![image](https://user-images.githubusercontent.com/8599/95481904-67dd9b00-0942-11eb-98ad-4988b953db3a.png)

Maybe the page can be annotated more specifically. Since its sporadic and readme specific, this could maybe closed.

**Comment by fiveisprime** [comment]
Thanks, I'll report this out to the Marketplace team

// @prashantvc

**Comment by prashantvc** [comment]
Thanks for the report @digitarald 
We will take it up next sprint :)

**Comment by isidorn** [comment]
This works fine now, thus closing
