### ISSUE TITLE
Step into my code button for debugger

### ISSUE THREAD

**Issue by jahan01** [microsoft/vscode#108363]
This is a feature request for breakpoint debugging - to add a new butting for "Step in into my code" in addition to current existing "Step in". This is same as PyCharms (or) any Jetbrains IDE.

Initially opened a request at microsoft/vscode-python#13719 but was redirected here. This would help not to step into standard library/third party code. Some debuggers like python have settings like `justMyCode` but that will either turn off or on for the entire debug session. There are some places where I would want to step into other code, some places I would want to skip - this is pretty common uses in debugging I suppose.

Having a dedicated button to `step into workspace code` and support for it in DAP would be an welcome improvement in debugging experience, I believe

**Comment by connor4312** [comment]
@luabud you are actually able to contribute buttons to the debug toolbar, so that is possible. Maybe that would be a good start. Unsure if this is something we'd want to formalize.

**Comment by weinand** [comment]
Since the "Step in into my code" concept is neither known to VS Code's generic debugging UI nor the Debug Adapter Protocol, it can only be supported by specific extensions via the API mentioned by @connor4312.
