### ISSUE TITLE
watcherService process overloads CPU on a big project

### ISSUE THREAD

**Issue by victorpavlov** [microsoft/vscode#108387]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

After latest update I've noticed that watcherService process overlads CPU, it takes about 230% useage in activity monitor.
macOs Catalina 10.15.7

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.53GB free)|
|Process Argv|--crash-reporter-id 846d449c-e239-49e5-b97a-c2404e148570|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   12	    98	 76488	code main
    3	    66	 76491	   gpu-process
    0	    33	 76493	   utility
   12	    82	 76987	   shared-process
    0	     0	 77511	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   180	 77189	   window (section-header.component.html — pna)
    0	     0	 77190	     /bin/zsh -l
    0	   328	 77202	     extensionHost
    0	    16	 77409	       electron_node server.js 
    0	    66	 77411	       electron_node server.js 
    0	    16	 77463	       electron_node eslintServer.js 
    0	    66	 77472	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=77202
    0	   147	 77473	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Users/viktorpavlov/.vscode/extensions/angular.ng-template-0.1001.0/server --logFile /Users/viktorpavlov/Library/Application Support/Code/logs/20201009T145257/exthost5/Angular.ng-template/nglangsvc.log --logVerbosity terse --ngProbeLocations /Users/viktorpavlov/.vscode/extensions/angular.ng-template-0.1001.0/server,/Users/viktorpavlov/projects/pna --tsProbeLocations /Users/viktorpavlov/.vscode/extensions/angular.ng-template-0.1001.0,/Users/viktorpavlov/projects/pna --node-ipc --clientProcessId=77202
  228	  1343	 77208	     watcherService
    0	    33	 77425	     searchService
    0	    66	 77497	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (section-header.component.html — pna)
|    Folder (pna): more than 20314 files
|      File types: php(8294) yml(5329) js(690) twig(267) module(222) css(156)
|                  txt(116) inc(99) svg(94) install(82)
|      Conf files: package.json(2) launch.json(1)
|      Launch Configs: php(2);
```

</details>
<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.1001.0
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.37.1
mustache|daw|1.1.1
vscode-eslint|dba|2.1.10
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
tslint|eg2|1.0.44
prettier-vscode|esb|5.7.1
php-debug|fel|1.13.0
vscode-firefox-debug|fir|2.9.1
beautify|Hoo|1.5.0
docthis|joe|0.7.1
Angular2|joh|9.1.2
VS-code-drupal|mar|0.0.12
twig-language-2|mbl|0.9.2
vscode-autoprefixer|mrm|3.0.1
sublime-keybindings|ms-|4.0.7
debugger-for-chrome|msj|4.12.11
create-file-folder|rit|0.0.5
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.9.2
code-spell-checker-ukrainian|str|0.1.5
vscode-stylelint|sty|0.85.0
drupal-8-twig-snippets|tse|1.0.2
vscode-icons|vsc|11.0.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Merging into https://github.com/microsoft/vscode/issues/108441 please answer there for additional insights.
