### ISSUE TITLE
vscode opens two windows 

### ISSUE THREAD

**Issue by miguel-martinr** [microsoft/vscode#108354]
Issue Type: <b>Bug</b>

Everytime I    $code .   in a folder, the program opens two windows: one with the actual folder and  other with an OLD unsaved .css file that I don't know where it came from. It won't let me save this file to any path, only to close without saving it, but then when I   $code .  in a folder again it happens again 

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 5.4.0-49-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 1|
|Memory (System)|7.65GB (4.40GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 0586b674-50bc-40e4-a693-2f42f0dd5723|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by bpasero** [comment]
@miguel-martinr this should help:
* close all vscode
* delete the `Backups` folder from `~/.config/Code`
* restart

Note that deleting the backups folder deletes any dirty content you had, so maybe make a backup to make sure you are not loosing data.

**Comment by miguel-martinr** [comment]
this solved the problem perfectly, thanks a lot:)
