### ISSUE TITLE
Tab bar not scroll to current tab when pinned

### ISSUE THREAD

**Issue by troy351** [microsoft/vscode#108355]
- VSCode Version: 1.50.0
- OS Version: Win 10

Steps to Reproduce:

![record](https://user-images.githubusercontent.com/8372385/95539608-61722080-0a21-11eb-9002-f609b186c405.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Yes, intentional. You can change this by configuring `workbench.editor.pinnedTabSizing` to `shrink` or `compact`.

**Comment by cdoublev** [comment]
Thank you for the tip!

> **Workbench › Editor: Pinned Tab Sizing**
> 
> Controls the sizing of pinned editor tabs. Pinned tabs are sorted to the begining of all opened tabs and typically do not close until unpinned. This value is ignored when Workbench › Editor: Show Tabs is false.

Do you need a suggestion for an improved description of the behavior described by @killerkalamari and I in #108412 and #108370 (can't speak for @troy351)? Something like *Controls the sizing of pinned editor tabs. Any other value than `normal` prevents the pinned tabs from scrolling out of view. [...]*

Maybe you prefer to have a second setting, something like `pinnedTabAnchor`, that accepts `left` or `right`?

**Comment by bpasero** [comment]
Sorry I misunderstood this issue. I feel https://github.com/microsoft/vscode/issues/108561 fixes it!
