### ISSUE TITLE
Hope the terminal window arrangement can be more flexible

### ISSUE THREAD

**Issue by bao007fei** [microsoft/vscode#108399]
If the terminal windows can move like normal file tab, that'll be great. Sometimes I only want one quarter of the window .

![image](https://user-images.githubusercontent.com/24863266/95589217-05d28200-0a77-11eb-9320-7b1376eda699.png)

**Comment by alannt777** [comment]
You opened the same issue here: #108398

**Comment by bao007fei** [comment]
Accidental repetition
