### ISSUE TITLE
Writing login information to the keychain failed with error 'XXX' (Garbled code)

### ISSUE THREAD

**Issue by XuCpeng** [microsoft/vscode#108392]
- VSCode Version: 1.51.0-insider (user setup)
- Commit: f5d3ba4d61146b78f0c75c82f3f85232d3409bc1
- Date: 2020-10-09T05:34:54.647Z
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

**1. Turn on "Sign in to Sync Settings"**
**2. Sign in with Microsoft.** (Additional information that may be useful: Signed in `GitHub Pull Requests and Issues` extension with GitHub account)
**3. Successfully logged in to the external browser and ‘You are signed in now and can close this page.’**
**4. Go back to vscode and get the error message**

![](https://user-images.githubusercontent.com/19551139/95582788-b63b8880-0a6d-11eb-8604-859f02a2c484.png)

Does this issue occur when all extensions are disabled?: **YES**

**Comment by code004Accepted** [comment]
Also experiencing the same issue here.

>Version: 1.51.0-insider (system setup)
Commit: f5d3ba4d61146b78f0c75c82f3f85232d3409bc1
Date: 2020-10-09T05:34:54.647Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20231

Screenshot:
<img width="960" alt="Untitled2" src="https://user-images.githubusercontent.com/36566134/95681771-3f8cbf80-0c14-11eb-967e-77f8e7b82ae7.png">

**Comment by Taikamya** [comment]
> 
> 
> Also experiencing the same issue here.
> 
> > Version: 1.51.0-insider (system setup)
> > Commit: [f5d3ba4](https://github.com/microsoft/vscode/commit/f5d3ba4d61146b78f0c75c82f3f85232d3409bc1)
> > Date: 2020-10-09T05:34:54.647Z
> > Electron: 9.2.1
> > Chrome: 83.0.4103.122
> > Node.js: 12.14.1
> > V8: 8.3.110.13-electron.0
> > OS: Windows_NT x64 10.0.20231
> 
> Screenshot:
> <img alt="Untitled2" width="960" src="https://user-images.githubusercontent.com/36566134/95681771-3f8cbf80-0c14-11eb-967e-77f8e7b82ae7.png">
> 
> I've tried reinstalling the version before:
> 
> > Version: 1.50.0-insider (system setup)
> > Commit: [2289738](https://github.com/microsoft/vscode/commit/228973889bc0e352f7cd11cc14755893f8d81864)
> > Date: 2020-10-01T05:33:55.357Z
> > Electron: 9.2.1
> > Chrome: 83.0.4103.122
> > Node.js: 12.14.1
> > V8: 8.3.110.13-electron.0
> > OS: Windows_NT x64 10.0.20231
> 
> and no problems relating to this occured in that version.
> 
> Also, if the user was already logged in in previous versions before updating to 1.51.0-insider, he/she will see the popup in the screenshot above directly as they start the updated 1.51.0-insider.

Yeah, directly related to 1.51.0-insider. I updated today and it started happening to me too. Exact same issue as OP.

**Comment by joaomoreno** [comment]
Related:https://github.com/microsoft/vscode/issues/108362

**Comment by RMacfarlane** [comment]
For "The stub received bad data" errors, that's being tracked here: https://github.com/microsoft/vscode/issues/108411. I believe this is distinct from the original problem reported here, where the error message is garbled.

**Comment by code004Accepted** [comment]
Yes, it seems that #108411  and #108362 are same problems as this one.

I've updated to a newer version just now and the issue still exists.

>Version: 1.51.0-insider (system setup)
Commit: 605bc4ec1eaf8dc1acd89a0c3c5743926ed0dc09
Date: 2020-10-12T10:52:10.028Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20231

**Comment by XuCpeng** [comment]
This issue has been fixed in the new version, Sync Settings can Sigin with Microsoft account normally. 

- Version: 1.51.0-insider (user setup)
- Commit: bc20f53838c75c0ec473b2a1afa7423cc5bcf7ab
- Date: 2020-10-13T17:29:58.109Z
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.19041
