### ISSUE TITLE
Git: Support recursive git clone

### ISSUE THREAD

**Issue by Nabav** [microsoft/vscode#108381]
When we open the editor or in general from command pallette, there are 2 options to start: opening a folder and cloning a repository. It would be great to have the option to clone the repository **recursively**.

**Comment by joaomoreno** [comment]
> When we open the editor or in general from command pallette, there are 2 options to start: opening a folder and cloning a repository. It would be great to have the option to clone the repository recursively.

We can definitely provide a `Git: Clone Recursively` command. Though I wouldn't make it prominent in the explorer view.

**Comment by ThakurKarthik** [comment]
Hey @joaomoreno I want to give it a try, Do we want to add the command to the list when we click ctrl + shift + p (windows) ? I am new to this repo any pointers will be appreciated

Thanks !

**Comment by joaomoreno** [comment]
@ThakurKarthik Do a full text search for `git.clone` and follow the trail ;)

**Comment by Nabav** [comment]
> > When we open the editor or in general from command pallette, there are 2 options to start: opening a folder and cloning a repository. It would be great to have the option to clone the repository recursively.
> 
> We can definitely provide a `Git: Clone Recursively` command. Though I wouldn't make it prominent in the explorer view.

I think it is preferred to add the option in the same git clone command. The command already asks for the repository URL and destination folder. It can also ask for a recursive option with yes and no possible answers.

**Comment by joaomoreno** [comment]
> I think it is preferred to add the option in the same git clone command. The command already asks for the repository URL and destination folder. It can also ask for a recursive option with yes and no possible answers.

Yes it but also overcomplicates the flow of 99% of the use case for this command. I don't think it warrants annoying most people by adding an extra step to that dialog.

**Comment by Nabav** [comment]
> > I think it is preferred to add the option in the same git clone command. The command already asks for the repository URL and destination folder. It can also ask for a recursive option with yes and no possible answers.
> 
> Yes it but also overcomplicates the flow of 99% of the use case for this command. I don't think it warrants annoying most people by adding an extra step to that dialog.

The extra question about the recursive clone style could be asked just if there are submodules detected in .gitmodules. This will keep the conventional procedure unchanged.

**Comment by joaomoreno** [comment]
> The extra question about the recursive clone style could be asked just if there are submodules detected in .gitmodules.

The question is asked before the repository is even locally, so there's no way to check for that.
