### ISSUE TITLE
VScode's Git 'Discard Changes' option seems Too Danger

### ISSUE THREAD

**Issue by jehunseo** [microsoft/vscode#108348]
![image](https://user-images.githubusercontent.com/31786318/95521737-3aa5f100-0a05-11eb-89e2-0a0b1a4ad4ab.png)
I initialized some directory(my markdown documentation root folder) by my mistake, and i tried to un-initialized them,
In this process, i found a feature 'discard all changes'
I did not realized it means 'discard all files that not tracked.
and my files are all gone. I found it after that 'git clean -f -q' command has activated.
fortunately I could recover files, but clear -f command seems too danger.

how about use git clear -n to show what will be deleted first again or make some commit to recover them?
I want to make some chance for recovering them, not delete forever....

**Comment by gjsjohnmurray** [comment]
Did VS Code first ask for your permission with  message box containing CAPITALIZED WORDS?

**Comment by jehunseo** [comment]
I Changed the title. sorry for missing writing rules.
but I thought this ('discard all changes') feature seems to need adding re-confirming features. 
And -f option seems to danger, so I made that title using captial words.

**Comment by gjsjohnmurray** [comment]
I wasn't objecting to the issue title. Trying to check if you got the usual big warning message when you did this.

**Comment by jehunseo** [comment]
![image](https://user-images.githubusercontent.com/31786318/95563300-2e974f00-0a58-11eb-9bbb-7e98f797247d.png)
I saw a message 'you want to delete', and there were no messages 'all files will be gone forever'. so I first realized that files will deleted like 'move to paste bin'.

**Comment by gjsjohnmurray** [comment]
cc @joaomoreno

**Comment by joaomoreno** [comment]
For some reason that dialog lacked more uppercase.

**Comment by joaomoreno** [comment]
Verification: code review.
