### ISSUE TITLE
Allow git.path or some other directive to use Git from WSL while using VSCode on Windows without Remote WSL extension

### ISSUE THREAD

**Issue by umairkhan-dev** [microsoft/vscode#108371]
Issue Type: <b>Feature Request</b>

**Here is the scenario**:
I want to use Git installation from WSL while working on VSCode without Remote WSL extension. Currently VSCode has `git.path` setting which allows me to use Git setup from WSL.

**settings.json**
```
"git.path": "D:/Instructions/git-wsl-executable.bat"
```
**git-wsl-executable.bat**
```
@echo off
set v_params=%*
set v_params=%v_params:\=/%
set v_params=%v_params:c:=/c%
set v_params=%v_params:"=\"%
wsl.exe git %v_params%
```
As you can see that this is just a child's patch up to make it work. This may have lots of bugs, also this may produce errors in advanced cases.

Kindly provide some way to tell VSCode to use Git from WSL like.
```
/**
 * This setting tell VSCode the use current OS's Git installation or from some other source.
 * Applies to Windows installation of VSCode only.
 * Values may be
 * `os` -- (default) VSCode will try to find and use Git installation from current OS.
 * `wsl` -- VSCode will try to find and use Git installation from WSL. For this to work you need to set "git.path": "wsl.exe" -- to use default WSL distro, or "git.path": "wsl.exe -d <distribution>" to use specific WSL distro.
 * If you use `wsl`, VSCode will automatically convert file paths style to support targetted file paths between Windows and WSL.
"git.path-mode": "wsl",
"git.path": "wsl.exe",
```

**Back Story**
I extensively use WSL (Ubuntu 20.04) through out my day. I also need to perform ssh based tasks on multiple servers, some of which only allow access from specific IPs which I need to use as proxy through `ProxyCommand`. So it was very convenient for me to setup all my dependencies on WSL. On top of that my Git repos need ssh key based authentication, which Git on linux support somewhat natively through `ssh-agent`. As VSCode needs Git setup on windows side (I am not sure what will happen if in case of Remote WSL extension), which in turn requires me to load my keys in _Pageant_ and set an _Enviroment Variable_ `GIT_SSH` with path to _plink_ to allow Git on Windows to use ssh key based authentication. So its hell lot of setup. Also it requires to update Git settings in both WSL and Windows if needed.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

**Comment by joaomoreno** [comment]
> I want to use Git installation from WSL while working on VSCode without Remote WSL extension

We don't support this because it has terrible performance and has issues, since git would traverse the file system border. On the Windows side, we only support Git for Windows.

This is a possible solution for sharing SSH keys between both git installations: https://devblogs.microsoft.com/commandline/sharing-ssh-keys-between-windows-and-wsl-2/

**Comment by umairkhan-dev** [comment]
> We don't support this because it has terrible performance and has issues, since git would traverse the file system border. On the Windows side, we only support Git for Windows.

😢 😢 😞 Windows, WSL, WSL2-Linux-Kernel, VSCode, VSCode Remote WSL extension and even GitHub all have Microsoft at their back.
