### ISSUE TITLE
Add Link to #43347

### ISSUE THREAD

**Issue by guettli** [microsoft/vscode#108337]
For some strange reason I am not allowed to add a comment to this issue: 

https://github.com/microsoft/vscode/issues/43347

Could someone with more permission please do it.

Please link to this issue: https://github.com/microsoft/vscode-python/issues/14327

With this quote:

> Since the problem still exists, I created a corresponding issue in the vscode-python repo

Thank you.

**Comment by JacksonKearl** [comment]
Does the solution proposed in the issue (`"python.globalModuleInstallation": true`) not work for you? I don't think we need to revive a 2 year old barely populated thread for this.

**Comment by guettli** [comment]
The question for me is: Why should I do a work-around for so many years? It fails and it confuses new users.

**Comment by JacksonKearl** [comment]
I understand the frustration. I have added your content.
