### ISSUE TITLE
single file but 2 tabs with different path shown

### ISSUE THREAD

**Issue by Dandjinh** [microsoft/vscode#108306]
Issue Type: <b>Bug</b>

A single c file, open in resource manager shows the relative path.  While "go to definition" with any function a new tab pops showing the full path. Intellisense only works in short path tab but theme seems not working well and the full path tab has corrent theme color but intellisense doesn't work.

![2020-10-08 20-55-57屏幕截图](https://user-images.githubusercontent.com/23111507/95461584-fbe24d80-09a8-11eb-8bf4-29d170138859.png)

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:56:11.027Z)
OS version: Linux x64 5.4.0-49-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 3567)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.22GB (23.14GB free)|
|Process Argv|--no-sandbox --unity-launch /home/dandjinh/wheelchair/PRODUCT/master/application/ --crash-reporter-id 7471c379-7db6-4bce-9933-853c887cbb88|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.2.0
systemd-unit-file|coo|1.0.6
doxdocgen|csc|1.0.0
arm|dan|1.4.0
gitlens|eam|10.2.2
vscode-element-helper|Ele|0.5.6
go|gol|0.17.2
vscode-nuget-package-manager|jmr|1.1.6
intellij-idea-keybindings|k--|0.2.41
hex-fmt|ker|1.0.0
vscode-language-pack-zh-hans|MS-|1.49.2
csharp|ms-|1.23.2
python|ms-|2020.9.114305
cpptools|ms-|1.0.1
vetur|oct|0.28.0
devicetree|plo|0.1.1
vscode-icons|vsc|11.0.0
linkerscript|Zix|1.0.1

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you "Copy Path" from the context menu and compare the difference?

**Comment by Dandjinh** [comment]
> Can you "Copy Path" from the context menu and compare the difference?

Thanks and it's because I created a soft link to the project folder. It occurs when I start vscode with solf link folder but it works find in the original folder.

**Comment by Dandjinh** [comment]
the original project path: /media/a/b/c/d/e/f/prj and the soft link path: ~/d.
this situation happens when vscode ~/d/e/f/prj

**Comment by bpasero** [comment]
Yes, this is a situation that we currently cannot merge into 1 tab. If you use links, they will appear as 2 tabs.
