### ISSUE TITLE
Source Control file list is super hard to read

### ISSUE THREAD

**Issue by thujone** [microsoft/vscode#108358]
Issue Type: <b>Bug</b>

This feature is very confusing. It's very hard to tell what the files are and what are just folders. It was way better before. It concerns me, because I'm afraid it can be easy to delete / revert files, or miss adding them to a commit. I think this is an example of over-engineering. Please change it back to the way it was before!

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.19041

**Comment by JacksonKearl** [comment]
Are you referring to the tree versus list view? This can be toggled with the three lines at top the view.

![image](https://user-images.githubusercontent.com/8586769/95625825-0135ab80-0a2e-11eb-8f58-763f2f1bd79e.png)
![image](https://user-images.githubusercontent.com/8586769/95625837-05fa5f80-0a2e-11eb-8fbf-e014306472a4.png)
