### ISSUE TITLE
Settings Sync GitHub Authorization permissions request

### ISSUE THREAD

**Issue by fkromer** [microsoft/vscode#108305]
- VSCode Version: 1.49.3
- OS Version: Liunx x64 5.4.0-48-generic snap

Steps to Reproduce:

1. Enable Settings Sync
2. SignIn with GitHub

> Existing access
Full control of private repositories

Is it really necessary to request full control of private repositories. This seems to be quite "broad". Would it be possible to limit permissions request?

**Comment by sandy081** [comment]
I think the scopes needed for Settings Sync is just user, not sure why repos are needed. Hence assigning to @RMacfarlane

**Comment by RMacfarlane** [comment]
@fkromer Have you signed in using GitHub for other extensions? Since this is listed as "Existing access", I suspect that something else previously requested "repo" access. As @sandy081 says, settings sync itself should request only user information

**Comment by fkromer** [comment]
@RMacfarlane Mh, that's possible. I'll check my other integrations. Thanks! Luckily I don't use GitHub for production repos but private experimentation repos only :smile:

**Comment by fkromer** [comment]
I checked all my integrations for access on private repos. For these integrations I explicitly allow access to private GitHub repos. In the overview for VSCode integration there is a permissions request to private repos as well:

![github_for_vscode](https://user-images.githubusercontent.com/10199742/95762307-d22d6d00-0cad-11eb-8a76-7c55cdcc37f0.png)

The VSCode extension I'm currently using does require very little permissions:

![github_permissions_settings_sync](https://user-images.githubusercontent.com/10199742/95762661-4f58e200-0cae-11eb-91fe-8b1fe9163a74.png)

**Comment by fkromer** [comment]
Ah, seems like [GitHub for VSCode (vscode.github.com)](https://vscode.github.com/) is the integration I installed before where access to private repos makes sense. As soon as integration works I'll recognize what permissions are needed by VSCode Settings Sync. In general it's nice to know requirements before installation/integration :smirk:
