### ISSUE TITLE
Unknown Configuration Setting: tab.lastPinnedBorder

### ISSUE THREAD

**Issue by Sayvai** [microsoft/vscode#108372]
- VSCode Version: `1.50 - Stable`
- OS Version: `OSX Catalina 10.15.7`

It appears the new configuration option `tab.lastPinnedBorder` that is meant to be included with the latest `1.50` release is not actually available to set, with a tooltip warning appearing when hovering over the new configuration reading "_Unknown Configuration Setting_".

See annotated screenshot below:
![Screenshot 2020-10-09 at 10 44 13](https://user-images.githubusercontent.com/7581546/95569056-f3c3f580-0a1c-11eb-86a2-fe0f281a122c.png)

Steps to Reproduce:

1. Open the VS Code **Command Palette**
2. Search for and open **Preferences: Open Settings (JSON)**
3. Include the new configuration option `tab.lastPinnedBorder`, and save. (eg, `"tab.lastPinnedBorder": "#fffca6"`)

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by usernamehw** [comment]
It's a color. It should be inside `workbench.colorCustomizations` setting.

**Comment by Sayvai** [comment]
> It's a color. It should be inside `workbench.colorCustomizations` setting.

@usernamehw thanks, that did the trick!

Here's an example below for reference:
```
"workbench.colorCustomizations": {
    "tab.lastPinnedBorder": "#fffca6"
},
```

Will close the ticket.
