### ISSUE TITLE
Hope the terminal window can be more flexible

### ISSUE THREAD

**Issue by bao007fei** [microsoft/vscode#108398]
If the terminal windows can move like normal file tab, that'll be great. Sometimes I only want one quarter of the window .

![image](https://user-images.githubusercontent.com/24863266/95589045-c86df480-0a76-11eb-879c-21f7829207af.png)

**Comment by IllusionMH** [comment]
Terminal in editor tabs already discussed in #10546 (which is about tabs, but not sure if terminal in editor area is tracked there as well).

More info about terminal in editor tabs https://github.com/microsoft/vscode/issues/10546#issuecomment-685801194 and there is link to extension that allows to achieve it now.
