### ISSUE TITLE
VScode built-in terminal won't run when vscode itself is run on terminal using code .

### ISSUE THREAD

**Issue by cnemri** [microsoft/vscode#108369]
- VSCode Version: 1.49.3
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Go to linux terminal and run `code .`
2. Try to open vscode built-in terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by anniecruz13-dogs** [comment]
This is also broken for Windows 10
Version: 1.50.0 (user setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by JacksonKearl** [comment]
I haven't been able to reproduce this, tested on Windows (user) with Powershell and Command Prompt, and Ubuntu with bash... do you see anything logged to console when you try to open the terminal? (`Developer: Toggle Developer Tools` in the command palette)

**Comment by anniecruz13-dogs** [comment]
This came up on my work laptop. There were no errors and I could not enter
anything in the terminal window. This doesn't happen on my personal
computer. Are there any log files I can send you when I switch back to my
work computer?

**Comment by anniecruz13-dogs** [comment]
I could open terminal windows, but none of them would allow me to enter any
text in them.

**Comment by JacksonKearl** [comment]
> Are there any log files I can send you when I switch back to my
work computer?

We can start with the developer console I mentioned above.

**Comment by cnemri** [comment]
In the dev tools console I got the following : 
  ERR A system error occurred (EACCES: permission denied, open '/proc/1/environ'): Error: EACCES: permission denied, open '/proc/1/environ'

**Comment by JacksonKearl** [comment]
Looks like https://github.com/microsoft/vscode/issues/76542, can you try setting `"terminal.integrated.inheritEnv"` to true in settings?

**Comment by anniecruz13-dogs** [comment]
Which file does that go in? I saw the bug and tried that.

**Comment by cnemri** [comment]
> Looks like #76542, can you try setting `"terminal.integrated.inheritEnv"` to true in settings?

Thank you @JacksonKearl  this solved my problem (it is still not supported in windows though - I am on ubuntu).

**Comment by JacksonKearl** [comment]
@anniecruz13-dogs Open settings with `Ctrl + ,` then search for "terminal inheritenv" then check the box. Or add that line to "settings.json" by searching for "open settings.json" in the command palette.

**Comment by anniecruz13-dogs** [comment]
When I searched for  terminal inheritenv, it showed the box as already
checked.

I figured out what the problem was. If I comment out the lines below in
settings.json, close VS Code, open a Cmder window, then reopen VS Code, it
switched the terminal window to cmder and I can now use the terminal. I did
not manually enter these lines. Does VS Code look for what command windows
are open when you first install it to determine which command window to
default to? For the combination of Windows 10 and git bash, this may not be
a good plan. Either that, or just fix VS Code to work with git bash when VS
Code is running on a Windows 10 machine.

{

// "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    // "outputCapture": "std",
    // "window.zoomLevel": 1,
    // "terminal.integrated.shell.linux": ""
}

-Thanks

**Comment by JacksonKearl** [comment]
cc @Tyriar for the above

(He's out for the next few weeks but may be able to provide some more knowledge on this area when he returns)

**Comment by anniecruz13-dogs** [comment]
I see a lot of these messages in the Developer tools console - I don't know
if this is related though:
DevTools failed to load SourceMap: Could not load content for
file:///C:/Users/chq-anniec/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/main.js.map:

I did figure out this problem has to do with VS Code defaulting to a git
bash terminal type on my Windows 10 machine.

**Comment by Tyriar** [comment]
> When I searched for  terminal inheritenv, it showed the box as already checked.

You wouldn't see the environ error if this was the same issue.

> "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"

Perhaps this path doesn't exist? Create a new issue if you follow https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch and think it's a bug in vscode.

> DevTools failed to load SourceMap: Could not load content for

These are unrelated electron issues
