### ISSUE TITLE
VSCode uninstalled itself

### ISSUE THREAD

**Issue by nicolasparada** [microsoft/vscode#108382]
- VSCode Version: Version before 1.50.0
- OS Version: Windows 10 Pro 19041.508

Steps to Reproduce:

September update just got released, but the auto-update failed —most likely— and for the end-user looks like it just uninstalled itself.
Got this log at `C:\Users\nicolas\AppData\Local\Temp\vscode-inno-updater-1602213617.log`:
```
Oct 09 00:20:21.894 INFO Inno Updater v0.8.2
Oct 09 00:20:21.894 INFO Starting update, silent = true
Oct 09 00:20:21.930 INFO do_update: "C:\\Users\\nicolas\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe", _
Oct 09 00:20:21.930 INFO move_update: "C:\\Users\\nicolas\\AppData\\Local\\Programs\\Microsoft VS Code\\unins000.dat", _
Oct 09 00:20:21.930 INFO Reading directory: "C:\\Users\\nicolas\\AppData\\Local\\Programs\\Microsoft VS Code"
```
...
```
Oct 09 00:20:22.133 INFO Collected all directories and file handles
Oct 09 00:20:22.180 INFO All file handles marked for deletion
```

Does this issue occur when all extensions are disabled?: Dunno.

**Comment by joaomoreno** [comment]
So sorry about that. Unfortunately it's a well known issue: #47841

If it happens again, I suggest disabling Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
