### ISSUE TITLE
Global Search and Replace is failing

### ISSUE THREAD

**Issue by heavensloop** [microsoft/vscode#108312]
- VSCode Version: 1.49.3
- OS Version: macOs Mojave version 10.14.6

Steps to Reproduce:

1. Create a file and add the following text: ACTION_DELETE, ACTION_UPDATE, ACTION_EDIT
2. Use global "search and replace" to replace ACTION_UPDATE with ACTION_DELETE
3. ACTION_UPDATE changes to ACTION_EEIT

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by JacksonKearl** [comment]
Unable to reproduce.. is this the correct repro steps? \gitPlease
![recording (7)](https://user-images.githubusercontent.com/8586769/95499003-81d6a800-0959-11eb-8a7d-39b3df9491ab.gif)

**Comment by JacksonKearl** [comment]
\gifPlease
