### ISSUE TITLE
Menu activity bar entry is never active

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#108314]
See attached screen capture. The explorer entry shows active, the menu entry doesn't even though the menu is showing. IMO the menu entry should get the "active" treatments, e.g be stronger and have the highlight, while the menu shows

<img width="573" alt="Screenshot 2020-10-08 at 16 26 20" src="https://user-images.githubusercontent.com/1794099/95472198-07228280-0983-11eb-8546-b71d057167fa.png">

**Comment by misolori** [comment]
Isn't this the same behavior in native apps as well?

![image](https://user-images.githubusercontent.com/35271042/95600560-31b61f00-0a07-11eb-9061-630d3809d93e.png)

![image](https://user-images.githubusercontent.com/35271042/95600584-3bd81d80-0a07-11eb-8973-990b79714129.png)

**Comment by sbatten** [comment]
Yes, the menu is a not equivalent to a View Container Icon. Opening the menu does not hide the explorer view container so you would not want to make its icon "inactive."

**Comment by jrieken** [comment]
> Isn't this the same behavior in native apps as well?

Not sure what direction you are arguing for. The screen shot does show how the anchor of a menu is highlighted so I take it as a "yes, good idea"

**Comment by misolori** [comment]
@jrieken sorry, I was referring to how selection in the explorer and menu were common in other apps, but I also think I misread your original comment so you ignore my original comment 😄 

It's worth noting that our account + settings gear menu behave the same way. Although those do not get the active color on the icon (which should all be consistent):

![image](https://user-images.githubusercontent.com/35271042/96154764-05e1e000-0ec4-11eb-9ad6-2ddcf9b74647.png)

**Comment by jrieken** [comment]
> It's worth noting that our account + settings gear menu behave the same way.

Indeed and it's funny that I am not soo confused by that. Maybe it's the awkward placement of the menu (https://github.com/microsoft/vscode/issues/108307), the position of its anchor, the color, or all things combined...

**Comment by sbatten** [comment]
position updated in separate issue, I don't think the menu should highlight but I wonder if there is some separation needed between the hamburger and the view container icons

**Comment by sbatten** [comment]
@jrieken let me know if the new positioning has improved this. will reopen if needed
