### ISSUE TITLE
After 1.50, Code Helper (Renderer) takes +100% CPU 

### ISSUE THREAD

**Issue by n808** [microsoft/vscode#108376]
Issue Type: <b>Bug</b>

Visual Code was auto-upgraded to 1.50 and now the "Code Helper (Renderer)" process takes up 100-150% of the CPU. Edited: the issue persists for around 20 minutes (real time) after every time Code starts, and occurs even if all extensions have been disabled. 

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 8, 7|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 086104be-0946-4fb6-9470-e155c7f5584e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
git-graph|mhu|1.26.0
cpptools|ms-|1.0.1
trailing-spaces|sha|0.3.1
vscode-lldb|vad|1.5.3

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does this also happen with all extensions disabled?

**Comment by n808** [comment]
Hmm, it seems after about 20 minutes, the problem has gone away. If it re-occurs I will check each extension that I have separately, to see if one of them is the problem. I have attached a screenshot showing that one of the Code Helpers have used a large amount of CPU time. 

<img width="847" alt="Screenshot 2020-10-09 at 13 13 32" src="https://user-images.githubusercontent.com/664311/95576826-650da380-0a31-11eb-8532-ea28f381a346.png">

**Comment by n808** [comment]
The issue re-occurs on every restart of Code, and with all extensions disabled. 
<img width="947" alt="Screenshot 2020-10-09 at 13 24 44" src="https://user-images.githubusercontent.com/664311/95577650-dd289900-0a32-11eb-9e21-11f93099c937.png">

**Comment by n808** [comment]
Note1: It is possible that this was also happening before 1.50
Note2: I also notice that when Code Helper (Renderer) stops consuming CPU, color formatting stops updating properly, along with IntelliSense issue 'squiggles'. This may or may not be related, or the observation may not be correct. However, I know I was struggling with broken/stuck color formatting and Intellisense issues for a few weeks prior to 1.50.

**Comment by hDmtP** [comment]
Accurate

**Comment by rebornix** [comment]
Can you open Process Explorer from VS Code UI and share the screenshot?

**Comment by n808** [comment]
Here you, the 15-thread watcherService' appears to be the culprit:
<img width="802" alt="Screenshot 2020-10-09 at 19 14 14" src="https://user-images.githubusercontent.com/664311/95612998-876ce480-0a64-11eb-9586-a4fb3511829d.png">

**Comment by n808** [comment]
Here you go, 'watcherService' seems to be problematic...

<img width="802" alt="Screenshot 2020-10-09 at 19 14 14" src="https://user-images.githubusercontent.com/664311/95613586-7a9cc080-0a65-11eb-96a4-6231e968bda3.png">

**Comment by bpasero** [comment]
Merging into https://github.com/microsoft/vscode/issues/108441 please answer there for additional insights.
