### ISSUE TITLE
Regression from 1.49.3 to 1.50.0: Quick Watch window moves away from mouse, making further interactions impossible

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#108333]
Issue Type: <b>Bug</b>

1) 
git clone https://github.com/microsoft/vscode-azurearmtools.git
cd vscode-azurearmtools
git checkout saw/vscodebug-quickwatch
npm i
npm run build
2) open folder in vs code 
3) open file vscode-azurearmtools/test/dependsOn.completions.test.ts
4) Put a breakpoint on line 41 (assertEx.deepEqual)
5) Position approximately line 32 at the top of the editor window
6) F5
7) On the breakpoint, hover over the "completions" variable
8) when the quick watch window comes up, click on the first array element to expand it ("[0]")
!) the window moves when it shows the expanded array element, and the window is no longer underneath the mouse
9) Try to expand anything else in the window
!) It's impossible, because any move of the mouse will close the window

In 1.43.9, the quick watch window did not move, so you could expand any additional elements in the window as much as you wanted.

## 1.43.9 stable
![bug-quick-watch stable](https://user-images.githubusercontent.com/6913354/95501748-a2086600-095d-11eb-8beb-e6dfc9f86a05.gif)

## 1.50.0 stable and insider
![bug-quick-watch insiders](https://user-images.githubusercontent.com/6913354/95501737-9e74df00-095d-11eb-9e76-f01af367906e.gif)

VS Code version: Code - Insiders 1.50.0-insider (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T00:58:35.624Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 6, 6|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_5477689 --crash-reporter-id 28a909e2-0b30-47b4-bfa3-dcb1734aca95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
todo-tree|Gru|0.0.183
vscode-azurefunctions|ms-|0.24.1
vscode-azurestorage|ms-|0.10.1
vscode-cosmosdb|ms-|0.15.0
vscode-docker|ms-|1.6.0
vscode-dotnet-runtime|ms-|0.1.2
python|ms-|2020.9.114305
vscode-ai|ms-|0.6.16
azure-account|ms-|0.9.3
vscode-typescript-tslint-plugin|ms-|1.2.3
azurerm-vscode-tools|msa|0.12.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by isidorn** [comment]
@StephenWeatherford thanks for good steps. Yes I introduced this issue since I have redone how we render the debug hover.
Assiging to October to fix this milestone.

**Comment by isidorn** [comment]
Thanks a lot for steps, however closing in favor of https://github.com/microsoft/vscode/issues/109226
Since that one has a recommendation for the fix
