### ISSUE TITLE
playground misses code highlights after reload

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#108378]
* open playground, see embedded code editors with highlights
* reload window
* embedded code editors have no more highlights

I guess the problem is that the welcome page doesn't wait for extensions to be registered. Before that, no language is known and everything is plaintext.

**Comment by chrmarti** [comment]
@jrieken Do you have a code pointer on how to wait for the extensions to be registered?

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/blob/03912754be58651eb8e73a833a66da0fab731338/src/vs/workbench/services/extensions/common/extensions.ts#L199
