### ISSUE TITLE
Settings Sync SignIn with GitHub fails: Error code 801

### ISSUE THREAD

**Issue by fkromer** [microsoft/vscode#108304]
- VSCode Version: 1.49.3
- OS Version: Liunx x64 5.4.0-48-generic snap

Steps to Reproduce:

1. Enable settings sync like described here: https://code.visualstudio.com/docs/editor/settings-sync
2. SignIn with GitHub

![vscode_sync_github_login_fail](https://user-images.githubusercontent.com/10199742/95457853-b9e9e500-0971-11eb-8a08-6be3d0f8ae86.png)

**Comment by zhanglongqi** [comment]
I still have the same issue.

```
Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:16:10.374Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic
```

**Comment by fkromer** [comment]
As workaround there is still https://marketplace.visualstudio.com/itemdetails?itemName=Shan.code-settings-sync by the way.

**Comment by schulzalbrecht** [comment]
how can I simply disable the pop-up asking me to sign in to github?

**Comment by RMacfarlane** [comment]
@schulzalbrecht What does the pop-up say, is it from an extension?

**Comment by schulzalbrecht** [comment]
@RMacfarlane it's from the GitLens extensions. It says: "GitLens would like to connect to GitHub to provide a rich integration with pull requests, issues, avatars, and more. If you choose to connect, you will be prompted to authenticate with GitHub.". When pressing the button "Connect to GitHub", the browser opens and I get the error in the picture above.

**Comment by nervocalm** [comment]
Still same problem with settings sync.

Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by 4c74356b41** [comment]
just hit this issue (was using the setting sync extensión). any ideas?

**Comment by John-Muriu** [comment]
> As workaround there is still https://marketplace.visualstudio.com/itemdetails?itemName=Shan.code-settings-sync by the way.

this worked for me,
 thank you

**Comment by jvanattedev** [comment]
> > As workaround there is still https://marketplace.visualstudio.com/itemdetails?itemName=Shan.code-settings-sync by the way.
> 
> this worked for me,
> thank you

installing another extension is not a real solution; this stuff should work

**Comment by soredake** [comment]
https://github.com/microsoft/vscode-pull-request-github/issues/1221#issuecomment-790411607

**Comment by TylerLeonhardt** [comment]
It's been a week and I haven't heard anything... Going to close this but please don't hesitate to reach out.

**Comment by TylerLeonhardt** [comment]
I'm gonna call this a dupe of the GHPR one just because of the huge amount of upvotes over there.
