### ISSUE TITLE
cannot see folders view

### ISSUE THREAD

**Issue by javeranga** [microsoft/vscode#108318]
Issue Type: <b>Bug</b>

Hi,

Please help me with visual studio code, because I connot see the folders view, when I try to open from de explorer menu its blocked or disabled, I don't know what happend because it suddenly change and folders view dissapeared.

Thnaks for your help

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.60GB free)|
|Process Argv|--crash-reporter-id d61b57f8-86fe-43f6-be59-c70d57fbd01f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by gjsjohnmurray** [comment]
Try the `View: Reset View Locations` from the Command Palette.

If that doesn't fix it, try the command that reloads with all extensions disabled.
