### ISSUE TITLE
Safari: Copy/Paste support

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#108349]
Considering we have made good progress with Web support and Safari evolves a lot during the last few years, here we do another assessment of Copy/Paste availability

## Limitations

When VS Code runs in Safari (or any other browser), we leave default copy/cut/paste keybindings blank, majorly because we want to avoid security warning or inconsistent experience. For example, to implement `paste`, we need to either run  `document.execCommand('paste')`, or reading from `navigator.clipboard.readText()`, both require proper security permission, meaning you might see below prompt:

<details>
<img src="https://user-images.githubusercontent.com/876920/96023485-5ba48280-0e07-11eb-8510-0f3b99ebfb31.gif" alt="paste-contextmenu" style="max-width:100%;">
</details>

Sometimes Safari thinks the paste attempt is triggered by the user, so it will not show the prompt but we should not game with the system and try to avoid the prompt by tricks. Thus we leave it blank, and let the browser do the job.

We don't have  a unified command/keybinding for copy/cut/paste for all components (editor, terminal, custom editor, notebook, etc) like what we do in desktop, for the same reason.

The behaviors you should see in Safari:

* `cmd+c/v` on editor, terminal and any other native input elements (find widget, quick input) in main thread UI or webview, it works seamlessly
* `cmd+c/v` or custom keybindings on custom components works seamlessly (tree view, notebook cell), as they don't involve real copy/paste.
* custom keybindings or actions from context menu to copy/cut/paste on editor or terminal, you might see security prompt.

## Check list

- Editor
    - ✅ `cmd+c/v` on text
    - ✅ `cmd+c/v` inside find widget
    - ⚠️  customized keybindings will trigger additional confirmation on paste
- Terminal
    - ✅ `cmd+c/v` on text
    - ✅ `cmd+c/v` inside find widget
    - ⚠️  customized keybindings will trigger additional confirmation on paste
- File Explorer
    - ✅ `cmd+c/v` on file entry
    - ✅ customized keybindings
- Notebook
    - ✅ `cmd+c/v` on text and cells
    - ✅ `cmd+c/v` in dynamic outputs (in webview)
    - ✅ `cmd+c` in static outputs
    - ✅ customized keybindings on notebook cells work
   - ⚠️  we don't support customizing keybindings for copy text output or outputs inside webview
- Custom Editor / Webview
    - ✅ `cmd+c/v`
    - ✅ We don't have any command for copy/cut/paste for webview/iframe, so all keyboard events go directly into the webview/iframe
- MISC
  - ✅ Commands triggered from the UI and using the internal clipboard service readText API
    ```
     debug.copyEvaluatePath
     debug.copyStackTrace
     debug.copyValue
     keybindings.editor.copyCommandKeybindingEntry
     problems.action.copyMessage
     problems.action.copyRelatedInformationMessage
     search.action.copyAll
     workbench.extensions.action.copyExtension
     workbench.extensions.action.copyExtension
     ```
- 🔴  Clipboard API. The Clipboard API exposed to the extension host will not work. `navigator.clipboard` is only working when it's used in an action triggered  by user (e.g., click, keyboard shortcut).

**Comment by rebornix** [comment]
Once https://github.com/microsoft/vscode/issues/108285 is resolved, we can report issues to Codespace if the issue doesn't reproduce in our OSS.

**Comment by rebornix** [comment]
> * Safari
>   * macOS
>     * cmd+v opens the context menu (with one action Paste) on CodeSpace

No longer reproducible.

**Comment by rebornix** [comment]
A summary of changes pushed into master and current status:

* 📌 `cmd+v` keybindings are no longer bound to `paste` in editor, terminal, or notebook if the focus is on output elements.
* Clipboard API is not working (as tracked in https://github.com/microsoft/vscode/issues/106997) due to security. We can't workaround it by a dummy `textarea` and `document.execCommand('copy')`. The latest Safari Technology Preview has improvements for `clipboard.writeText` but it doesn't fix the problem.

**Comment by alexdima** [comment]
fyi @egamma
