### ISSUE TITLE
UX meeting agenda 23 August 2016

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#10834]
- Icons
- Horizontal layout UX
- Debug UX #10437 #9740 #1931 
- Close button for horizontal panel #9638

@Microsoft/vscode - let me know if you want to join the meeting and I will send you the invite.

**Comment by bgashler1** [comment]
# Notes

### Explorer Icons
The team feels that monochrome looks better than color icons.  Being a cross-platform app, having color icons for folders tend to mismatch some platforms.  For example, orange—the color we were proposing for the folder icons and that is consistent with Visual Studio—is not the color macOS uses for folders in Finder.
Action item: monochromize the folder icons in the Explorer as well as any other area we use the orange folder icons.

### Horizontal panels.
We finalized the design.  We will put a toggle for switching between vertical and horizontal layouts in the Open Editors area.  We will leave the split action in the active editor.  We will also add View menu items for "Vertical" and "Horizontal" editor layouts (to account for people who have Open Editors disabled or who tend to discover commands that way.

### POSTPONED
All other items in the agenda will be discussed later.
