### ISSUE TITLE
Can't use Pallete

### ISSUE THREAD

**Issue by jihyeon316** [microsoft/vscode#108347]
- VSCode Version:1.50.0(user setup)
- OS Version: WIndows7

Steps to Reproduce:

1. When I open Palette and click one of things and then nothing show up
And it said Command 'C/C++: Edit Configurations (UI)' resulted in an error (command 'C_Cpp.ConfigurationEditUI' not found)
Everything showed up like this.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
I suggest you launch with all extensions disabled and confirm that you no longer have the problem. Then work out which of your extensions is faulty. Then report it to the author.
