### ISSUE TITLE
Editor walkthrough content is parsed many times

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#108310]
The editor walkthrough content is mostly static markdown which we parse

1. once when we render it as html (see [this](https://github.com/microsoft/vscode/blob/ffd533aaa9973c4dd579e5c9d42319f367b287ad/src/vs/workbench/contrib/welcome/walkThrough/browser/walkThroughPart.ts#L305)),
1. another time when we create references for the embedded editor widgets [here](https://github.com/microsoft/vscode/blob/ffd533aaa9973c4dd579e5c9d42319f367b287ad/src/vs/workbench/contrib/welcome/walkThrough/browser/walkThroughInput.ts#L111), and
1. ~N^2 times (_N_ is the number of code blocks) when providing content for a cell in the [content provider](https://github.com/microsoft/vscode/blob/ffd533aaa9973c4dd579e5c9d42319f367b287ad/src/vs/workbench/contrib/welcome/walkThrough/common/walkThroughContentProvider.ts#L73)

For statically known contents that's too much. I would suggest to do the following

* author the page in html since that's how we want it to be
* parse it once via `innerHTML` - just like the welcome page content
* use some query-selector-math to extract code blocks which then will be replaced with embedded editors

**Comment by JacksonKearl** [comment]
Not sure how you're getting `N^2` times there... isn't it just `N`? We provide cell content once per cell, and that requires one parse.

**Comment by jrieken** [comment]
True. I was only looking at the `renderer.code` function that gets called

**Comment by rebornix** [comment]
I guess WalkThrough will be a notebook later on?

**Comment by JacksonKearl** [comment]
Maybe.. there's a lot of UI to notebooks that we don't necessarily want in the getting started so I'm not sure. Maybe in a "lite" notebook UI?

**Comment by jrieken** [comment]
verified in source
