### ISSUE TITLE
Not full docs/params descriptions in tooltip helper

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#10830]
- VSCode Version: insiders
- OS Version: window 10

```js
import * as vscode from 'vscode'
```
See not full docs/params descriptions in tooltip helper:
![image](https://cloud.githubusercontent.com/assets/736697/17889980/6b2d5bdc-694c-11e6-9718-7e8561de19c1.png)
and no way to extend the tooltip.

**Comment by sandy081** [comment]
@whitecolor It is showing the complete doc. May i know what is not being shown here?

**Comment by whitecolor** [comment]
@sandy081 

the description is incomplete and comes off in the mid-sentence, and only one param (`command` is present)

Here is from vscode.d.ts:
![image](https://cloud.githubusercontent.com/assets/736697/17924001/22e4ce78-6a00-11e6-9695-6f3213effdd6.png)

**Comment by sandy081** [comment]
@whitecolor In the first screen shot you are at the position of first argument, hence hover is only showing the documentation for first argument. You can also see that first parameter is highlighted. Description of the method there is not prominent, hence minimal text is shown.

You can see the complete description when you hover on the method name or do ctrl+space at the end of the method name.

IMO this makes sense. Please let me know if this helps.

Thanks

**Comment by whitecolor** [comment]
Ah ok, thanks)
