### ISSUE TITLE
Bind a key to search for a string

### ISSUE THREAD

**Issue by verslyfr** [microsoft/vscode#108383]
Issue Type: <b>Feature Request</b>

I have established a template variable for which I would like to be able to search for instances with a key binding. The pattern is #\{.*?\} so the pattern is #{anything at all}. I have looked for search commands which would allow me to create the key binding, but do not seem to find any.

I suspect there might already be a way to do this, but none of my searches have turned up anything useful. 

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:57:01.595Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by JacksonKearl** [comment]
You can use the `args` property of the search command to do this:
```json
// search editor
  {
    "key": "alt+g alt+q",
    "command": "search.action.openNewEditor",
    "args": {
      "query": "hello"
    }
  }
// search view
  {
    "key": "alt+g alt+h",
    "command": "workbench.action.findInFiles",
    "args": {
      "query": "hello"
    }
  }
```

**Comment by ArturoDent** [comment]
It isn't clear from the question but I believe this can't be done for the find in a file command `actions.find` - it doesn't appear to take args.

**Comment by JacksonKearl** [comment]
@ArturoDent yes the in-editor find doesn't support args. I will reopen this as being specific to in-editor find.
