### ISSUE TITLE
Vertical selection

### ISSUE THREAD

**Issue by sushmitkumarpatil** [Microsoft/vscode#10837]
Add support for Vertical selection by holding `Alt` key like Visual Studio.

**Comment by sandy081** [comment]
@sushmitkumarpatil Can you please be more elaborate about your request? More context/details about Vertical selection? Is it in editor or where?

**Comment by sushmitkumarpatil** [comment]
In editor we should be able to select the text vertically, like in below image.  
![verticle selection](https://cloud.githubusercontent.com/assets/2450835/17922232/9b81f176-69fb-11e6-8610-7454aad9b1f8.png)

**Comment by sandy081** [comment]
@sushmitkumarpatil You can use `ctrl+d` keyboard short cut to do this.

**Comment by sushmitkumarpatil** [comment]
@sandy081  It is possible only if the same text is there in all lines. In below image there are some strings in which i want keep only last part(98777*), `ctrl+d` will help me to select same text(not selected REF-2015 ), but I want to select any text in column. 
 
![image](https://cloud.githubusercontent.com/assets/2450835/17922927/2bf6f4c4-69ff-11e6-814d-f37c3b967de7.png)

**Comment by sandy081** [comment]
@sushmitkumarpatil Ok, I am reopening this.

**Comment by smuuf** [comment]
On Windows you should be able (at least for me it works) to use `SHIFT+ALT+<MOUSE_CLICK&DRAG>` to create block selection.

Although I would ***really*** love to have it available through pressing the middle mouse button, as in *SublimeText*, instead of this finger-breaking key-mouse combo.

**Comment by alexandrudima** [comment]
Please see https://code.visualstudio.com/docs/editor/editingevolved#_column-box-text-selection

**Comment by kestelle** [comment]
I want this.

**Comment by Jijjy** [comment]
Three things i'd really like from this:
 - default to alt-drag (not alt-shift-drag), as in Visual Studio, Notepad++ and other editors
 - selection to be from where the user starts and stops dragging, not starting where the the caret is
 - ability to select past the end of line (as in Visual Studio, Notepad++)

A related nice-to-have would be Atom's Ctrl+Click to add a caret anywhere (where lines don't have to be sequential)

**Comment by alexandrudima** [comment]
@Jijjy we have an issue somewhere to track mouse configuration (make the gestures configurable). ctrl-click is under alt-click in vscode.

**Comment by Jijjy** [comment]
@alexandrudima Sorry, I wasn't aware VS Code supported multiple carets. I understand I may be able to configure this in future, but from a UX perspective it would feel more natural to me to place multiple carets with Alt+Shift+Click and vertical selection as Alt+Drag, and not the other way around.

**Comment by alexandrudima** [comment]
I agree, it was not my decision to have ctrl+click go to definition and alt+click add cursor, which leaves column selection to shift+alt+click.
