### ISSUE TITLE
Not able to open vs code on macos Catalina

### ISSUE THREAD

**Issue by mjmanav4** [microsoft/vscode#108394]
1. i have  updated macos to Catalina
2. i have installed vscode from here https://code.visualstudio.com/docs/?dv=osx
3. now i am getting this issue. `The application “Visual Studio Code 3” can’t be opened.`
4. also in system preference i am not getting any option to open the editor
 
<img width="471" alt="Screenshot 2020-10-09 at 6 16 00 PM" src="https://user-images.githubusercontent.com/9611624/95584781-de21f080-0a5b-11eb-92f2-d875965fd09f.png">
<img width="662" alt="Screenshot 2020-10-09 at 6 19 14 PM" src="https://user-images.githubusercontent.com/9611624/95584856-fb56bf00-0a5b-11eb-9c9d-e7a5758f8879.png">

**Comment by mjmanav4** [comment]
![Uploading Screenshot 2020-10-09 at 6.16.00 PM.png…]()

**Comment by deepak1556** [comment]
Can you paste the output of `spctl --verbose --assess --type execute --v <path-to>/Visual\ Studio\ Code.app/` ?

**Comment by ChickenWangSY** [comment]
I got the same error. 
```
$ spctl --verbose --assess --type execute --v /Applications/Visual\ Studio\ Code.app
/Applications/Visual Studio Code.app: accepted
source=Notarized Developer ID
override=security disabled
origin=Developer ID Application: Microsoft Corporation (UBF8T346G9)
```

is there any advice to solve this question?
