### ISSUE TITLE
Python Interactive is blank.

### ISSUE THREAD

**Issue by k-wht1023** [microsoft/vscode#108360]
Issue Type: <b>Bug</b>

Python Interactive is blank.
When I Run Cell in pyhon script, then Python Interactive is open.
But there is not any results in Python Interactive.
And I try again to put 'Run Cell', then the message'executing cell' is shown.
But never finish and show result.

By the way, I try to open jupyter notebook, the same situation happen.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|12.37GB (10.64GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.50.0
python|ms-|2020.9.114305

</details>

**Comment by alannt777** [comment]
This repository does not contain Python language features. Please submit this issue at [microsoft/vscode-python](https://github.com/microsoft/vscode-python)

**Comment by k-wht1023** [comment]
I submit again here.
https://github.com/microsoft/vscode-python/issues/14342#issue-718003957

**Comment by alannt777** [comment]
@k-wht1023 Please close this issue as well
