### ISSUE TITLE
Menu is anchored at a funny position

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#108307]
* open codespace
* select the main menu button in the left
* 😕 the menu isn't anchored at the item I have clicked on...

<img width="1321" alt="Screenshot 2020-10-08 at 15 01 34" src="https://user-images.githubusercontent.com/1794099/95462013-3c28d800-0977-11eb-94b3-1281bc7cdc27.png">

**Comment by sbatten** [comment]
IIRC I made this decision intentionally to allow for the maximum amount of vertical space for the expected submenus since we cannot draw outside the viewport. The submenus are smart enough to shift up if needed but I actually felt the gap left by anchoring on the hamburger icon also looked worse.

**Comment by jrieken** [comment]
> The submenus are smart enough to shift up if needed but I actually felt the gap left by anchoring on the hamburger icon also looked worse.

**Comment by jrieken** [comment]
I don't get it. They do scroll. So you way you rather position the menu somewhere else than having the scrollbar?

<img width="1199" alt="Screenshot 2020-10-08 at 16 09 34" src="https://user-images.githubusercontent.com/1794099/95470126-b27e0800-0980-11eb-97d4-bd3d93a674ce.png">

**Comment by misolori** [comment]
+1 for anchoring the menu right next to the menu item as it's consistent with where we show all other menus. I always thought this was an annoying bug.

**Comment by bpasero** [comment]
Also +1 for 👍
