### ISSUE TITLE
vscode remove php close tag on save

### ISSUE THREAD

**Issue by yuber83** [microsoft/vscode#108336]
Issue Type: <b>Bug</b>

simply, create a php file open and close tag, and in the moment of vscode save the file, it removes the php close tag .
vscode removes this. 
?>

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 4.19.0-10-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 2579)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 1|
|Memory (System)|7.67GB (1.08GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 2ce6b1f3-1302-4832-ab36-cdd7e04d584a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|awesome|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|awesome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.15.0
flutter|Dar|3.15.0
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.8
auto-rename-tag|for|0.1.4
todo-tree|Gru|0.0.183
pubspec-assist|jer|2.2.1
dart-import|lua|0.3.0
vetur|oct|0.28.0
laravel-blade|one|1.24.0
laravel5-snippets|one|1.10.0
vscode-yaml|red|0.11.1
vue-vscode-snippets|sdr|2.1.5
vim|vsc|1.17.1
material-theme|zhu|3.9.3

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by yuber83** [comment]
I disabled all extensions and the problem goes.
The PHP extension Intelephense 1.5.4 is causing the problem.
Sorry for the inconvenience
