### ISSUE TITLE
Ctrl+C doesn't clear the line in integrated cmd.exe

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#10835]
- VSCode Version: 1.4.0
- OS Version: Windows

Steps to Reproduce:

1. Open a Terminal
2. Type something, then press Ctrl+C

Expected result: you get a new empty line as you would in a standalone `cmd.exe` window.
Actual: nothing happens.

Note: it seems Ctrl+C works as expected for interrupting a process.

**Comment by Tyriar** [comment]
Duplicate #9347
