### ISSUE TITLE
Add setting to disable automatic port fowarding.

### ISSUE THREAD

**Issue by JeremyGrieshop** [microsoft/vscode#108346]
- VSCode Version: 1.50.0
- OS Version: MacOS 10.15.6

Steps to Reproduce:

1. Launch VSCode and use File->New Window to create a separate Code instance window.
2. In one window, open a Remote Connection to a docker container (not sure if this is required, but it's what I've always done in the past)
3. In Code window that isn't attached to a remote connection, run a task that needs to bind to a port, say 3000.
4. Code in the other window (Remote Connection) pops up a message saying "localhost:3000 from the remote has been forwarded to localhost:3000 locally.".  

Since the window with the Remote Connection is not running anything on port 3000, this of course will cause the connections to fail.

Does this issue occur when all extensions are disabled?: Yes/No

I need the Remote Connections extension to demonstrate the error and don't know if it's VS Code or Remote Connections, but it has worked fine for years until the September 2020 update.

**Comment by alexr00** [comment]
@JeremyGrieshop I tried to repro with your exact steps, but I don't see the issue.

Do you have any terminals running in your remote window? We added a new feature that finds urls in the terminal in remote windows and forwards ports automatically. If you have a terminal running in your remote window, is there a url in there with port 3000?

**Comment by JeremyGrieshop** [comment]
Ah!  I think you've helped me understand things now.  So, in my container, I have nginx running, which logs its requests out to the terminal.  When I hit my "npm start" on port 3000 from my other window, it loads my app, which causes an API request to my docker container.  Then nginx logs that request with a message containing the "referral" url, which contains the ":3000" url, triggering that port forward feature that you have mentioned:

`172.18.0.1 - - [09/Oct/2020:09:16:38 +0000] "POST /afw HTTP/1.1" 200 935134 "http://localhost:3000/afw_app" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"`

Is there a way to disable that feature?

**Comment by alexr00** [comment]
@JeremyGrieshop there is currently no way to disable the feature, but your setup clearly needs such a setting. I will add such a setting.

**Comment by alexr00** [comment]
@JeremyGrieshop I have added the setting `remote.autoForwardPorts`. To get your setup working again soon, you can try the [insiders build](https://code.visualstudio.com/insiders/) (installs side by side with stable). The next insiders build (available when the "unrelease" label is removed from this issue), will have the setting.

**Comment by JeremyGrieshop** [comment]
Amazing, thank you so much for the quick turnaround!  I'm looking forward to trying out the Insiders Build when it's there.

**Comment by pablocar80** [comment]
Would it be possible to fix the feature so that it works, instead of having to turn it off? In this case, forward the port 3000 only if the remote container is listening on port 3000.

**Comment by JeremyGrieshop** [comment]
/verified 

It works correctly when I set the `remote.autoForwardPorts` setting to `false`.  Thanks!

**Comment by alexr00** [comment]
Thank you for verifying!

**Comment by pablocar80** [comment]
@alexr00 this isn't working for me on the latest version:

This is my version with the feature, running on MacOS:

![image](https://user-images.githubusercontent.com/36197603/98379232-ae3f1c00-200c-11eb-8758-3d9c8f6eea2c.png)

I have set it to false:

![image](https://user-images.githubusercontent.com/36197603/98379296-bb5c0b00-200c-11eb-9196-aba1ee54d93b.png)

Then I still get this message and the port gets automatically added:

![image](https://user-images.githubusercontent.com/36197603/98379392-db8bca00-200c-11eb-977b-d51ded4458e3.png)

![image](https://user-images.githubusercontent.com/36197603/98379414-e34b6e80-200c-11eb-9e02-a16b4e04d640.png)

**Comment by alexr00** [comment]
Which settings are you setting `remote.autoForwardPorts` in?

**Comment by pablocar80** [comment]
@alexr00 on my devcontainer.json in the folder .devcontainer

looks like this:

```json
// For format details, see https://aka.ms/vscode-remote/devcontainer.json or this file's README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.117.1/containers/javascript-node-12-postgres
// If you want to run as a non-root user in the container, see .devcontainer/docker-compose.yml.
{
  "name": "xxxxxxxxx",
  "dockerComposeFile": "docker-compose.yml",
  "service": "web",
  "workspaceFolder": "/workspace",
  "settings": {
    "remote.autoForwardPorts": false,
```

**Comment by pablocar80** [comment]
seems to be solved by rebuilding the container
