### ISSUE TITLE
[scss] autocomplete for @directives

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#10836]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.6 

Steps to Reproduce:
1. type `@inc` or `inc`
2. there is no autocomplete for `@include`, just `:increment`

There should be snippets or autocompletes for `include`, `extend` `mixin` and other Sass directives.

**Comment by tsi** [comment]
Do you know of any plugin that will fill the gap for the meantime?

**Comment by aeschli** [comment]
You can add a user snippet for that. See File > Preferences > User Snippet

**Comment by nmsmith22389** [comment]
I couldn't find one either so I just made a SCSS snippets extension that is a port of the Sublime Text one. I haven't published it to the marketplace yet but I can email it to you if you'd like!

**Comment by 5ulo** [comment]
@nmsmith22389 please upload your SCSS snippets to your git or somewhere else.. dropbox etc :) Thanks

**Comment by octref** [comment]
Tracking in #41929.
