### ISSUE TITLE
Debugger is not displaying correctly a decimal property value

### ISSUE THREAD

**Issue by mayconbeserra** [Microsoft/vscode#10838]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6
- .NET core version: 1.0.0-preview2-003121

Steps to Reproduce:

1. Create a class with a decimal property
2. Create a test and set any value to the decimal property
3. Put a breakpoint after changing the decimal property
4. Debug
5. Inspect the decimal property value from the class

As you can see in the screenshot, the debugger is not working correctly. It's is showing an invalid number.

The issue is only related to the debugger since the value is being correctly set.

![vscodeerror](https://cloud.githubusercontent.com/assets/911493/17892153/259207be-6940-11e6-9c30-306c011b2dd9.png)

**Comment by weinand** [comment]
The .NET debugger is not part of VS Code but a separate extension. Moving issue.

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#703
