### ISSUE TITLE
VSCode has extreme lag on any version past 1.35.1

### ISSUE THREAD

**Issue by isuggestchlorox** [microsoft/vscode#108340]
- VSCode Version: 1.50.0
- OS Version: 10.0.19041 Build 19041

Steps to Reproduce:

1. Freshly install vscode.
2. Lags on scroll or any action.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
