### ISSUE TITLE
Allow to select entries of the explorer by typing the start of the name

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#10839]
When looking up the files tree I can use pageup, pagedown
![image](https://cloud.githubusercontent.com/assets/736697/17892223/8febeeae-6959-11e6-826c-78bda76e1210.png)

It would be great to be able to navigate using leters so if I type it would jump to the next folder that matches the patter, many IDEs (like for example `webstorm`) provide this feature.

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/10026
