### ISSUE TITLE
IntelliSense for Xamarin project is extremely slow

### ISSUE THREAD

**Issue by sideez** [microsoft/vscode#108309]
Issue Type: <b>Performance Issue</b>

IntelliSense is extremely slow when working with C# files in a Xamarin project.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|13, 7, 5|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 753a1f37-4dc0-4a07-9eae-075f06b99246|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	    82	 12223	code main
    3	    66	 12234	   gpu-process
    0	    33	 12237	   utility
    0	   229	 12238	   window (ContactActivity.cs — Xamarin-AM7)
    0	   131	 12271	     extensionHost
    0	     0	 12281	       node /Users/fali/.vscode/extensions/mtxr.sqltools-0.23.0/dist/languageserver.js --node-ipc --clientProcessId=12271
    0	   606	 12336	       mono --assembly-loader=strict /Users/fali/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/OmniSharp.exe -s /Users/fali/dev/iAware/_git/Xamarin-AM7/AM7Client.sln --hostPID 12271 DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information --plugin /Users/fali/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.razor/OmniSharpPlugin/Microsoft.AspNetCore.Razor.OmniSharpPlugin.dll FileOptions:SystemExcludeSearchPatterns:0=**/.git FileOptions:SystemExcludeSearchPatterns:1=**/.svn FileOptions:SystemExcludeSearchPatterns:2=**/.hg FileOptions:SystemExcludeSearchPatterns:3=**/CVS FileOptions:SystemExcludeSearchPatterns:4=**/.DS_Store formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
    0	    49	 12273	     watcherService
    0	     0	 12580	     /bin/zsh -l
    2	    82	 12274	   shared-process
    0	     0	 22178	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    3	    82	 22173	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ContactActivity.cs — Xamarin-AM7)
|    Folder (Xamarin-AM7): more than 20334 files
|      File types: png(5612) flat(4324) xml(2796) class(1293) java(1031)
|                  cs(678) dll(648) txt(429) axml(231) stamp(187)
|      Conf files: csproj(1) sln(1);
```

</details>
<details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.9.0
vscode-multimarkdown|and|0.1.1
dart-code|Dar|3.15.0
flutter|Dar|3.15.0
vscode-markdownlint|Dav|0.37.1
vscode-eslint|dba|2.1.8
githistory|don|0.6.11
xml|Dot|2.5.1
gitlens|eam|10.2.2
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
code-runner|for|0.11.0
vscode-mysql|for|0.4.0
vscode-pull-request-github|Git|0.20.0
go|gol|0.17.2
rest-client|hum|0.24.3
emoji-code|idl|0.10.0
svelte-vscode|Jam|0.9.3
vscode-nuget-package-manager|jmr|1.1.6
vscode-csproj|luc|0.7.0
Angular-BeastCode|Mik|10.0.3
azure-pipelines|ms-|1.174.2
vscode-apimanagement|ms-|0.1.6
vscode-azureappservice|ms-|0.19.0
vscode-azurefunctions|ms-|0.24.1
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurestorage|ms-|0.10.1
vscode-azurevirtualmachines|ms-|0.2.0
vscode-cosmosdb|ms-|0.15.0
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
vscode-dotnet-runtime|ms-|0.1.2
mssql|ms-|1.9.0
python|ms-|2020.9.114305
azure-account|ms-|0.9.3
azurecli|ms-|0.5.0
cpptools|ms-|1.0.1
vscode-node-azure-pack|ms-|0.0.11
vscode-typescript-tslint-plugin|ms-|1.2.3
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.2902
team|ms-|1.161.1
azurerm-vscode-tools|msa|0.12.0
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.0.1
sqltools|mtx|0.23.0
vetur|oct|0.28.0
java|red|0.68.0
vscode-yaml|red|0.11.1
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.10
azure-iot-toolkit|vsc|2.16.4
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-icons|vsc|11.0.0
markdown-all-in-one|yzh|3.3.0
material-theme|zhu|3.9.3

(1 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
\extC#
