### ISSUE TITLE
vscode-github.login cannot allow

### ISSUE THREAD

**Issue by RomeoChen** [microsoft/vscode#108374]
System: MacOS
version: 1.50
vscode-github.com  password is not correct
i've tried thousands of times, but not works

**Comment by SachinShekhar** [comment]
This is a known issue: https://github.com/microsoft/vscode/issues/107480

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/108342#issuecomment-706340396, please check that comment for background.
