### ISSUE TITLE
Unexpected status bar context menu

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#108308]
See attached screen capture, the groups is confusing and I often select the wrong item because the primary/top item is hide status bar, not hide for the entry. Context menus for the activity bar get this right

😕 

<img width="372" alt="Screenshot 2020-10-08 at 15 13 15" src="https://user-images.githubusercontent.com/1794099/95463256-d9384080-0978-11eb-8108-a7f3434388ed.png">

😄 

<img width="332" alt="Screenshot 2020-10-08 at 15 14 33" src="https://user-images.githubusercontent.com/1794099/95463478-13094700-0979-11eb-8ef2-cbbd33b51fe4.png">

**Comment by bpasero** [comment]
This is actually intentional with the rationale that it makes hiding an entry from the status bar fast because you do not have to move your mouse all the way up. 

//cc @misolori

**Comment by misolori** [comment]
I think one of the things that really bother me is how the context menu starts from your cursor and downwards in the status bar, so you actually end up having to move your cursor all the way down:

![image](https://user-images.githubusercontent.com/35271042/95814510-6fe56400-0ccf-11eb-8b80-305a211ef690.png)

We should make all of these consistent, panels + views also behave the same as the activity bar:

![image](https://user-images.githubusercontent.com/35271042/95814585-93101380-0ccf-11eb-8708-d887cbf773a0.png)

![image](https://user-images.githubusercontent.com/35271042/95814663-bdfa6780-0ccf-11eb-8c80-3ff8116a1a9e.png)

**Comment by bpasero** [comment]
@misolori the status bar is typically to the bottom of the screen since the window is likely maximized and then the menu opens to the top:

![image](https://user-images.githubusercontent.com/900690/95823066-48bd7f80-0d2d-11eb-9c14-eaec29113b84.png)

The rationale was that in order to hide the entry you right click, you should not move the mouse all the way up. As such the "Hide" entry appears first.

Should we change it? Doesn't this break  muscle memory and people will start to hide the status bar always?

**Comment by bpasero** [comment]
A very similar thing we do is to put most recent folders/workspaces to the bottom of the dock context menu:

![image](https://user-images.githubusercontent.com/900690/95969274-c86f4b00-0e0e-11eb-89fc-9f8eab5a85df.png)

**Comment by misolori** [comment]
Ah, ok so I think what I've always seen is a bug on mac where the menu does not start at the bottom, so for me I've always had to scroll a lot: 

<img width="450" src="https://user-images.githubusercontent.com/35271042/96157717-82c28900-0ec7-11eb-8673-71ce1a06b5a3.png">

<img width="300" src="https://user-images.githubusercontent.com/35271042/96157816-a4bc0b80-0ec7-11eb-8bbd-91eb9f3983fc.png">

If we're able to get the menu to work consistently then I think having the "hide this" menu option as the first thing makes sense. But I'm also fine making all menus the same.

**Comment by bpasero** [comment]
I will call my veto here on changing it as UX owner of the experience. Especially in codespaces for example, I see tons of entries and having a fast way to hide exactly the one you right click is crucial to me:

![image](https://user-images.githubusercontent.com/900690/96217893-dc888900-0f83-11eb-9a3e-5695223840d7.png)

**Comment by bpasero** [comment]
@misolori the fact that the menu scrolls is actually a bug we never figured out how to resolve in electron. See https://github.com/microsoft/vscode/issues/40262
