### ISSUE TITLE
Typescript compiler broken on Ubuntu 20

### ISSUE THREAD

**Issue by ecanas44** [microsoft/vscode#108320]
Working on my react/typescript project when suddenly it stopped recongnizing JSX on returns. The project still runs, only vs marks a lot errors.

**Comment by IkeyBenz** [comment]
Having the same issue (with parsing JSX of typescript/react files) after updating.

**Comment by balazsorban44** [comment]
I can confirm, I had the same issue today.

VSCode -> About
```
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:01:33.073Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic snap
```
Using `Ubuntu 20.04.1 LTS 64bit`

@IkeyBenz the `files.associations` fix saved me, although I still don't understand why it worked without it until now.

**Comment by ecanas44** [comment]
Thanks! This worked for me too.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by balazsorban44** [comment]
@mjbvz Installed VS Code insiders clean, opened the same file in both VS Code and VS Code Insiders.

with `--disable-extensions`, it appears to be working in both!
