### ISSUE TITLE
error while processing request ' _request ' (exception exception ) 

### ISSUE THREAD

**Issue by thibault1907** [Microsoft/vscode#1083]
This is the error that comes up when i try to launch my first program. What does this mean? Any solutions? is this well coded? are there many mistakes? please help me. i am just learning to code :)

username = raw_input("username?")
age = raw_input("age?")
if age == [1,17]:
	print "you are too young"
else:
	print "welcome", username "we are happy to have you here"

time.sleep(3)

while true: 
	import random 
	print "welcome: " + username "This is a dice game. So get ready!"
	time.sleep(3)
	print "press enter to roll the dice."
	input()
	number=random.randint(1,6)
	if number == 1:
		print "[--------------]"
		print "[              ]"
		print "[      o       ]"
		print "[              ]"
		print "[--------------]"
		print "you threw 1!"
	if numer == 2:
		print "[--------------]"
		print "[              ]"
		print "[   o      o   ]"
		print "[              ]"
		print "[--------------]"
		print "you threw 2!"
	if number == 3:
		print "[--------------]
		print "[   o     o     ]"
		print "[                 ]"
		print "[      o         ]"
		print "[--------------]"
		print "you threw 3"
	if number == 4:
		print "[--------------]"
		print "[   o       o   ]"
		print "[                 ]"
		print "[   o       o   ]"
		print "[-------------]"
		print "you threw 4!"
	if number == 5:
		print "[--------------]"
		print "[   o       o  ]"
		print "[       o      ]"
		print "[   o       o  ]"
		print "[--------------]"
		print "you threw 5!"
	if number == 6:
		print "[--------------]"
		print "[   o      o   ]"
		print "[   o      o   ]"
		print "[   o      o   ]"
		print "[--------------]"
		print "you threw 6!"

**Comment by thibault1907** [comment]
oh the little drawings are suposed to form dices :)

**Comment by thibault1907** [comment]
and i see copy pasting is not a great idea :)

**Comment by egamma** [comment]
>This is the error that comes up when i try to launch my first program. 

You are using Visual Studio Code and are creating a launch configuration?

**Comment by thibault1907** [comment]
As i said i am new to this so why isnt this possible? Please give me more information so i can learn how to propely run my programs. Thank you for your reply

Date: Mon, 7 Dec 2015 13:23:18 -0800

**Comment by egamma** [comment]
This repository is for tracking Visual Studio Code issues/bugs etc, this is the wrong place for asking such questions.
