### ISSUE TITLE
Open Webview Developer Tools not working

### ISSUE THREAD

**Issue by Better-Boy** [microsoft/vscode#108395]
Version: 1.50.0 (user setup)
Date: 2020-10-07T06:10:52
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
OS version: Windows_NTx64 10.0.19041

Steps to Reproduce:

1. Create a sample extension.
2. Click on "Run" -> Start Debugging
3. Press "ctrl + shift + p"
4. Open Webview Developer Tools

Previous versions a debug windows used to open, after updating it's not opening

**Comment by mjbvz** [comment]
Is a webview visible?

**Comment by mjbvz** [comment]
Closing this a we need more information to investigate.

This command will only work if a webview exists (and is visible)
