### ISSUE TITLE
ERR: Enable all workspace extensions

### ISSUE THREAD

**Issue by uzprocode** [microsoft/vscode#108486]
Issue Type: <b>Bug</b>

1. Disable all installed extensions in the workspace
2. Enable all extensions for this workspace
3. err:  Because the GitHub Authentication extension in the workspace provides authentication providers, it cannot be disabled

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 18.7.0

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/107290
