### ISSUE TITLE
Search and Replace (Multiple files, large files) corrupts file(s) - 4 line offset replacement

### ISSUE THREAD

**Issue by rubin55** [microsoft/vscode#108467]
Issue Type: <b>Bug</b>

I have done a find and replace on a set of XML files (less than 100 files, a LaunchBox Data directory actually). The string replacement was:

     search: D:\
    replace: G:\

No options selected (no match case, no match whole word, no regular expressions). Expected correct string replacement, got (random? not all?) lines like this:

    <Platform>WiG:\ws</Platform>
    <Publisher>Electronic Arts</Publisher>
    <Rating />
    <ReleaseDate>1999-10-29T23:00:00+02:00</ReleaseDate>
    <RootFolder>D:\Galaxy\Ultima 9</RootFolder>

Notice in the above that `G:\` appears 4 lines higher, at the same character position - it did not replace the `D:\`. This seems to be consistent behaviour throughout the file. See this mangled file (just do a search for `G:` or `D:`) here: 
[example.zip](https://github.com/microsoft/vscode/files/5360003/example.zip)

I am not sure how you guys view this, but I consider this highly critical.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (20.79GB free)|
|Process Argv|C:\Users\rubin\AppData\Local\Programs\LaunchBox\Data|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.7.0
mustache|daw|1.1.1
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.1
vscode-firefox-debug|fir|2.9.1
vscode-lombok|Gab|1.0.1
go|gol|0.17.2
zopeneditor|IBM|1.0.4
reg|ion|1.0.1
hoogle-vscode|jca|0.0.7
language-haskell|jus|3.3.0
bash-ide-vscode|mad|1.11.0
rainbow-csv|mec|1.7.1
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.9.114305
remote-wsl|ms-|0.50.0
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.1
hexeditor|ms-|1.3.0
powershell|ms-|2020.6.0
sqltools|mtx|0.23.0
ruby|reb|0.27.0
java|red|0.68.0
vscode-xml|red|0.13.0
vscode-yaml|red|0.11.1
rust|rus|0.7.8
haskero|Van|1.3.1
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-ruby|win|0.27.0
vscode-extension-for-zowe|Zow|1.9.0

(2 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Is it possible that the original file has CR-only newlines? That is unusual but can cause exactly this issue. They get normalized away when the file is saved in vscode so they don't show up in the file you shared with me. 

If that is not the problem, is this consistently reproducible?

**Comment by rubin55** [comment]
It is possible that the original file only had CR newlines; I can't check because I did the replacement already (and had to fix the resulting file you've seen by hand).
The file was auto generated by LaunchBox (a games collection front-end). I would opine that any change to a file not expressed in the search/replace (i.e., "get normalized away") is a bug - search/replace has no business changing anything but what you requested in the search/replace in the first place, right?

**Comment by roblourens** [comment]
The newlines aren't changed by search/replace, they are normalized by the editor itself whenever a save happens, since CR-only newlines are not really valid. But certain tools insert them so this issue shows up from time to time.

Sorry for the trouble, we need to handle this better but it's difficult, tracking in https://github.com/microsoft/vscode/issues/48063
