### ISSUE TITLE
Interface doesn't work!!

### ISSUE THREAD

**Issue by yezz123** [microsoft/vscode#108474]
I'm a user of visual studio code on linux that my configuration :
```
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.11-1-MANJARO
Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
Ram : 8GiB
```
And i install it using [snapcraft](https://snapcraft.io/install/code/manjaro) following those commands :
```
$ sudo pacman -S snapd
$ sudo systemctl enable --now snapd.socket
$ sudo ln -s /var/lib/snapd/snap /snap
$ sudo snap install code --classic
```
And when i install it and going to download extensions and start working i go to the menu to create a workspace or open a folder nothing work the VScode exit and the same for all file categorie. 
Please check this issue !
<p align="center"> <img src="https://media.giphy.com/media/CWMhYu8WqaV5lDR2PD/giphy.gif">

**Comment by joaomoreno** [comment]
#100940
