### ISSUE TITLE
Markdown preview flashes when live editing the contents

### ISSUE THREAD

**Issue by peterjuras** [microsoft/vscode#108494]
- VSCode Version: 1.50.0
- OS Version: Windows 10 (2004 19041)

The markdown preview is flickering images (badges) when typing. This has already been reported a couple of times (#19475 #56378) but these issues have been closed therefore I wanted to open a new one.

Steps to Reproduce:

1. Add some badges to a markdown file
2. Open the file in preview
3. Start typing

You can see the issue happening here: https://streamable.com/3fzl6i

Does this issue occur when all extensions are disabled?: Markdown preview is not displayed in WSL with --disable-extensions

**Workaround:**
Simply commenting out images while writing works, but it would be more convenient if images are more aggressively cached between refreshes.

**Comment by mjbvz** [comment]
Can you please share the markdown source the causes this

**Comment by peterjuras** [comment]
Thanks for the reply, you can use the following markdown (or in this case html) content to reproduce it:

```md
<p align="center">
  <a href="https://codecov.io/gh/coat-dev/coat">
    <img src="https://codecov.io/gh/coat-dev/coat/branch/main/graph/badge.svg">
  </a>
  <a href="https://github.com/coat-dev/coat/actions">
    <img src="https://github.com/coat-dev/coat/workflows/@coat/cli/badge.svg?branch=main&event=push">
  </a>
  <a href="https://github.com/coat-dev/coat/actions">
    <img src="https://img.shields.io/npm/l/@coat/cli">
  </a>
</p>

Typing and typing and typing
```

**Comment by peterjuras** [comment]
It appears that the issue has been solved, I don't see any flashing in the newest version.
