### ISSUE TITLE
Treat words with hyphens as one word in Autocomplete

### ISSUE THREAD

**Issue by al3x1337** [microsoft/vscode#108420]
![dash autocomplete](https://user-images.githubusercontent.com/44815197/95623663-b161df00-0a43-11eb-8f04-13e7f65db335.png)
A picture is worth a thousand words so here's the difference between Notepad++ autocomplete including a word with a hyphen versus VS Code separating it before the hyphen.

I've already removed hyphen's from "editor.wordSeparators" but it does not change the behavior. Unsure whether it is a bug (not feature haha) of editor.wordSeparators or if that is not the intended sure of that setting but either way this would be a nice feature to have.

**Comment by jrieken** [comment]
This depends on the language you are typing in and what word definition this language uses.
