### ISSUE TITLE
Can't run/configure tasks after disabling "TypeScript and JavaScript Language Features" 

### ISSUE THREAD

**Issue by fbernhart** [microsoft/vscode#108499]
I just switched from PyCharm to VS Code today, so I'm really new and not 100% sure if this is a bug or if I'm just wrong on this one. But:

By disabling the built-in "TypeScript and JavaScript Language Features" (v1.0.0) I'm not able to configure tasks anymore. Clicking on "Tasks: Configure Task" will show "Select a task to configure" with a blue progress bar running forever.

If "TypeScript and JavaScript Language Features"  is enabled, everything works again as expected,

Is this intended? Is TypeScripts/JavaScript needed to run tasks? Sorry if this is a dumb question - I'm new to VS Code.

Here is a GIF to show what's happening.

![test](https://user-images.githubusercontent.com/70264417/95691947-669ebd80-0c23-11eb-9481-bb724b68ebc7.gif)

The same issue appears for "Tasks: Run Task"

Maybe this is related to #75498 ?

- VSCode Version: 1.50.0 (Portable x64 version, if that's important)
- OS Version: Windows 10, v. 2004

Steps to Reproduce:

1. Disable "TypeScript and JavaScript Language Features"  (v1.0.0)
2. Type "Tasks: Configure Task" in the VS Code Terminal

Does this issue occur when all extensions are disabled?:  Yes

**Comment by alexr00** [comment]
@fbernhart I tried to repro using your steps, but I didn't see the issue.

You should be able to disable the built-in Typescript extension and still use Tasks.

It looks to me like you have some extension installed that is very slow to provide tasks. Try disabling all the extension you installed (the built-in ones don't need to be disabled). You can also try setting the setting `task.autoDetect` to `false` to test this. You might not want to leave that setting as `false` though, since it means that extensions that provide tasks won't be able to do so.

**Comment by fbernhart** [comment]
Hi @alexr00 

thanks for having a look at this. I can definitely say, that it's not caused by an external extension. It still happened by running VS Code with the --disable-extensions flag. It's definitely caused by the built-ins.

I did some more testing and it seems like it wasn't just the "TypeScript and JavaScript Language Features" extension.  I was able to track it down to disabling 3 built-ins on a new, fresh installation.

Steps to reproduce:
- Go to https://code.visualstudio.com/download and download the VS Code portable Version 64-bit. (I haven't tested other versions, but maybe it will also appear in the 32-bit, user or system installation versions).

- Extract the VSCode-win32-x64-1.50.0.zip folder.

- Create an empty "data" folder inside of the "VSCode-win32-x64-1.50.0" folder. (Like described here: https://code.visualstudio.com/docs/editor/portable)

- Start Code.exe

- Go to Explorer, click on "Open Folder" (as tasks won't work without a folder opened) and choose any empty folder on your PC.

- Go to Extensions. Click on "Filter Extensions" --> "Built-in".

- Now disable the following 3 extensions: "TypeScript and JavaScript Language Features" (v1.0.0), "Less Language Basics" (v.1.0.0) and "SCSS Language Basics" (v.1.0.0).

- Close VS Code and start it again by clicking on Code.exe

- Press the "F1" key on your keyboard. Type "configure" and click on the "Tasks: Configure Tasks" option.

- Now it should be loading endlessly.

![test](https://user-images.githubusercontent.com/70264417/95743435-114dc500-0c92-11eb-88de-53e3ebd8b11d.gif)



I did the above like 3 times and was able to reproduce it every time. Hopefully you can also reproduce it! If you need any further information, let me know.
