### ISSUE TITLE
Keep the file browser in the same directory when deleting a file or subdirectory

### ISSUE THREAD

**Issue by Pomax** [microsoft/vscode#108463]
Currently, deleting a file in the file browser sidebar will cause the file browser to immediately jump to whatever the currently open file is, instead of staying in the same directory, making it _really_ hard to do some basic file management. 

Instead, the file browser should just move focus to whichever dir owns the file/dir that got deleted:

```
┬ root
│ ├ some dir  <─ highlight this...
│ │  ├ some file
┆ ┆  └ some other file <─ ...when deleting this
```

And then don't change the file browser location until the user explicitly focuses on an open file again (e.g _not_ on scroll, as scrolling does not imply working on a file in the slightest; it's a consultation at best, which might in fact guide which other files need deleting).

**Comment by isidorn** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/71315

**Comment by Pomax** [comment]
@isidorn that sounds like it's related, but also rather different given the initial description?
