### ISSUE TITLE
shortcut to "go back" navigation feature

### ISSUE THREAD

**Issue by gilbertomartinimadeira** [microsoft/vscode#108468]
Hi guys
I'm a linux user, and C# coder for over a decade, I absolutely love VSCODE, but this one thing that I can do in VS Community 2019 (on windows) by pressing CTRL + - (the minus button) doesn't work here in vscode on linux and I miss it so much! is there a chance to add this feature? 

Thanks !

**Comment by JacksonKearl** [comment]
You can use the keybindings editor to bind "Go Back" to ctrl+minus. It's available in the command palette at `Preferences: Open Keyboard Shortcuts`

![image](https://user-images.githubusercontent.com/8586769/95779616-371d9e80-0c7f-11eb-9405-250a338c4ecb.png)
