### ISSUE TITLE
cannot read property onDidStop of null

### ISSUE THREAD

**Issue by maxcli** [Microsoft/vscode#10848]
- VSCode Version: 1.4.0
- OS Version: win 10 ver 1601

 I see error :   cannot read property onDidStop of null

Steps to Reproduce:

1.  debugging powershell, 
2.

**Comment by sandy081** [comment]
I wonder it could be related to the power shell extension on VS Code. I would suggest to check with the extension - https://github.com/PowerShell/vscode-powershell

Please reopen the issue if not so. Sorry for not being very helpful here.

**Comment by maxcli** [comment]
i upgraded to 0.7.1 today. It actually makes it worse :-)
The program hangs when I hit F5

**Comment by sandy081** [comment]
This issue was moved to PowerShell/vscode-powershell#265

**Comment by sandy081** [comment]
@maxcli I moved this issue to Powershell repository
