### ISSUE TITLE
VScode doesn't respond after closing a terminal window

### ISSUE THREAD

**Issue by islam36** [microsoft/vscode#108402]
Issue Type: <b>Bug</b>

every time i use the terminal in vscode to run my node application and then when i close it, vscode shows me a window saying it's not responding. Looking forward to correct this issue.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (1.33GB free)|
|Process Argv|--crash-reporter-id a41fb235-99cf-4a4e-be1a-731ecd38b218|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
LiveServer|rit|5.6.1
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by 2000Slash** [comment]
I also experienced this. It appears that if you try to close the terminal while a process is running that is currently writing to the console, vscode hangs and crashes. You can easily test this with a simple powershell script: This will crash it: `while($true) {"Test"}` This will not crash it: `while($true) {}`

I tested this on Windows 10.0.18363 with version 1.50.1 https://github.com/microsoft/vscode/commit/d2e414d9e4239a252d1ab117bd7067f125afd80a and insiders https://github.com/microsoft/vscode/commit/fce8fc82ca
