### ISSUE TITLE
Cannot read property settings of undefined in themeService

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#10843]
Get latest, start vscode out of source, notice exception in console.
`themeDocument` is `undefined` [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/themes/electron-browser/themeService.ts#L626)

![screen shot 2016-08-23 at 16 12 42](https://cloud.githubusercontent.com/assets/1926584/17895180/8a7d609a-694c-11e6-9d11-975d0e456459.png)

**Comment by aeschli** [comment]
fixed by 886e308f7e699350db880dd7485d94be997470a0
