### ISSUE TITLE
ctrl + tab not working in mac

### ISSUE THREAD

**Issue by hariharan-palanichamy** [microsoft/vscode#108433]
Issue Type: <b>Bug</b>

ctrl + tab not working properly in mac

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 19.6.0

**Comment by JacksonKearl** [comment]
I'm unable to reproduce this... do you possibly have a different application handling that event?
