### ISSUE TITLE
TypeScript 'died 5 times' and then stopped error message

### ISSUE THREAD

**Issue by Peach-24** [microsoft/vscode#108449]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Random error message saying "TypeScript and JavaScript Language Features died 5 times and then stopped."

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.54GB free)|
|Process Argv|. --crash-reporter-id da560fdd-91da-40d1-beea-91050bd986de|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.10
javascript-ejs-support|Dig|1.3.1
vscode-toggle-column-selection|eri|1.0.6
prettier-vscode|esb|5.7.1
auto-close-tag|for|0.5.8
stylelint-plus|hex|0.52.10
beautify|Hoo|1.5.0
debugger-for-chrome|msj|4.12.11
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.3.0
LiveServer|rit|5.6.1
best-dark-themes-pack|the|1.0.2
vscode-icons|vsc|11.0.0
material-theme|zhu|3.9.3

(9 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
