### ISSUE TITLE
Add a setting to prevent explorer to open last opened file when getting visible

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#10845]
- VSCode Version: 1.5.0 - insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

This behavior would be normal? In certain moments it can become annoying.

It can happen in other situations my was as follows.

Steps to Reproduce:
1. Open a folder other folders and files inside.
2. Click on a file that does not get the Preview Editor.
3. Open User Setting.Deixe the mouse cursor on the "Default Setting".
4. Hide the Explorer (sidebar). Stay on the "Default Setting".
5. Now click to redisplay the Explorer (sidebar).
6. The same file back to the guide mentioned in number 2.

Another situation:
1. Open a folder other folders and files inside.
2. Click on a file that does not get the Preview Editor.
3. Open User Setting.Deixe the mouse cursor on the "Default Setting".
4. Choose another file to visualiar (either in the Preview Editor mode or not).
5. Hide the Explorer (sidebar).
6. Close the item guide 4.
7. Now click to redisplay the Explorer (sidebar).
8. The same file back to the guide mentioned in number 4.

Being in the second group of guides (ie keeping the pointer mouse before in "settings.json") the problem does not happen. In the first group created guides (which comes standard).

I think this should not happen. The same could keep a color on the last file that was seen (or a different color tone that exists), as at present, but without reopening it.

Or have a specific configuration for that not to happen?

**Comment by bpasero** [comment]
Yes, we do restore the last opened file once you make the explorer visible. This helps in cases where you jump from one viewlet back to the explorer to bring you back in context. I am closing this "as designed".

**Comment by Tekbr** [comment]
I believe that an option to be able to disable this behavior is not in the plans. I am sure?

**Comment by bpasero** [comment]
Let's reopen to consider this as feature request.

**Comment by Tekbr** [comment]
@bpasero Thank you.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
