### ISSUE TITLE
[Theme] gitDecoration.stageAddedResourceForeground or gitDecoration.stageModifiedResourceForeground?

### ISSUE THREAD

**Issue by psudo-dev** [microsoft/vscode#108434]
- VSCode Version: 1.50
- OS Version: Mac OS 10.13.6

Steps to Reproduce:

1. 
2.

Does this issue occur when all extensions are disabled?: Yes/No

In this new [release](https://code.visualstudio.com/updates/v1_50#_new-theme-colors) it says that there are 2 new Git Decorations but according to `vscode://schemas/color-theme`, `gitDecoration.stageAddedResourceForeground` is not allowed and when you use `Developer: Generate Color Theme from Current Settings` it shows `gitDecoration.stageDeletedResourceForeground` just like in the update documentation but instead of `gitDecoration.stageAddedResourceForeground`, it shows `gitDecoration.stageModifiedResourceForeground` - which is recognized by the schema. 

In the [API reference for Theme Color](https://code.visualstudio.com/api/references/theme-color) it does say `gitDecoration.stageAddedResourceForeground` but not `gitDecoration.stageModifiedResourceForeground`. When you stage an untracked resource it shows the usual `gitDecoration.addedResourceForeground` color. 

So was it supposed to be `gitDecoration.stageModifiedResourceForeground` instead? Or maybe all three of them?

**Comment by psudo-dev** [comment]
From what I've seen, when a theme doesn't have these new git decorators, VSCode adopts some default colors and they don't match anything from what the theme already has.

A suggestion for the `default` behavior I think should be:
stageDeletedResourceForegroung: deletedResourceForegroung with 75% opacity
stageModifiedResourceForeground: modifiedResourceForeground with 75% opacity
stageAddedResourceForeground: addedResourceForeground with 75% opacity

It will use the same colors the user is already familiar with but it will be a bit darker, so the user knows it has been staged.

**Comment by aeschli** [comment]
Assigning to @joaomoreno to fix/update the doc...

On the second comment, it's currently not possible for extensions to define a default that derives from a different color.

**Comment by psudo-dev** [comment]
Oh, I meant for VSCode to assign a 75% opacity from those git decorators when the theme doesn't assign a value.

**Comment by joaomoreno** [comment]
Great catch. Fixed the docs.
