### ISSUE TITLE
Editor Find doesn't support args passed via keybinding

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#108459]
Ref #108383

Find in files and search editors allow passing args from the keybinding or extension triggering to configure the query, flags, etc. This could be helpful for the in-editor find too.

**Comment by andrew-maust** [comment]
Hello, is this available to work on? If so, I am possibly interested in working on it. Could someone elaborate a bit more on what exactly is being looked for with this feature request?

**Comment by ArturoDent** [comment]
@andrew-maust If you look at the `workbench.action.findInFiles` command for example you can create a keybinding like so:

 ```
 {
    "key": "ctrl+shift+f",
    "command": "workbench.action.findInFiles",
    "args": {

      // "query": "Company(\\w+)",
      // "replace": "boy $1 swell",
      // "triggerSearch": true,
      // "isRegex": true,
      // "filesToExclude": "",
      // "filesToInclude": "",
      // "matchWholeWord": false,
      // "isCaseSensitive": false
    }
  },
```

So that command can take the indicated arguments - which are also surfaced through intellisense.  Thus if you have a frequently used search, you can create a binding for it with all those args and options.  Likewise for the `search.action.openNewEditor` command with slightly different args keys.

But you cannot do that for the `actions.find` command for find within the current file, it will not take any arguments.  As for the argument names, @JacksonKearl may have an opinion but I would suggest using the `findInFiles` names for consistency sake.

**Comment by orange4glace** [comment]
@andrew-maust Oh, I'm very sorry Andrew! I didn't realize that you've also started work with this issue. My apologies.
Although I think you can have your own PR, or please give some opinions for my one since I have no sure for my one whether it's a good way or not.

**Comment by ArturoDent** [comment]
Also, there should be the arg option:

      // "inSelection": true       // need this too for find in file command args

**Comment by orange4glace** [comment]
> Also, there should be the arg option:
> 
> ```
>   // "inSelection": Boolean       // or similar name, need this too for find in file command args
> ```

@andrew-maust If you don't mind, could you make a PR including this feature with your version? I'm just going to close my one ;)

**Comment by andrew-maust** [comment]
Sorry for the late response but please don't apologize, I realized after my comment I didn't make it very clear that I was actually working on it. You go ahead and submit the PR as I wasn't very close at all to finishing it. My apologies

**Comment by orange4glace** [comment]
@andrew-maust Nonono.. Don't apologize either! Anyway, thanks for saying that.

**Comment by EtienneDS** [comment]
Hey, just wondering if this functionality was added to the code yet.
I see this PR was made and closed, but then reopened and checks are not fully completed.

For the moment, I assume there is no way to pass arguments to a file search (actions.find) from inside a VSCode extension? For example when opening a find for a specific regex inside a particular editor selection. This can be circumvented by using findInFiles with a regex query and including only the current file, but not when wanting to find only in a particular selection.

**Comment by Stassy** [comment]
Hi, any extra news after 6 month on editor.action.startFindReplaceAction and action.find ?

**Comment by rebornix** [comment]
Thanks @orange4glace for the contribution, all kudos to you.

I updated the branch and have it merged so you should be able to use it with tomorrow's Insiders. The first set of args supported are:

```
export interface IFindStartArguments {
	searchString?: string;
	replaceString?: string;
	isRegex?: boolean;
	matchWholeWord?: boolean;
	isCaseSensitive?: boolean;
	preserveCase?: boolean;
	findInSelection?: boolean;
}
```

**Comment by ArturoDent** [comment]
Are the user-facing args that would be used in a keybinding consistent with those in the `findInFiles` command?  I believe the search editor command (`search.action.openEditor`) also uses these args:

```
export interface IFindInFilesArgs {
	query?: string;
	replace?: string;
	preserveCase?: boolean;
	triggerSearch?: boolean;
	// filesToInclude?: string;
	// filesToExclude?: string;
	isRegex?: boolean;
	isCaseSensitive?: boolean;
	matchWholeWord?: boolean;
	// useExcludeSettingsAndIgnoreFiles?: boolean;
	// onlyOpenEditors?: boolean;
}
```

from https://github.com/microsoft/vscode/blob/4ed0329e9c5e12e2c7c59697facc96020b0768ab/src/vs/workbench/contrib/search/browser/searchActions.ts

**Comment by rebornix** [comment]
We currently only include ones which work in the find widget, for example, we don't support `	// filesToInclude?: string;
	// filesToExclude?: string;`

**Comment by ArturoDent** [comment]
Yes, that is why I commented those args out above.  I was just checking that the nomenclature is consistent across these commands.  For example, using `query`, `replace`, `isRegex`, etc.   It seems unfortunate to support `searchString` rather than `query` used in other similar commands.
