### ISSUE TITLE
Native Notebooks - Add Code Cell 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#108464]
- VSCode Version: 1.51.0 Insider

Steps to Reproduce:

1. Opened Python notebook
2. Ran all cells 
3. Click add code cell
4. Plain text cell is added, not python code cell

![Add Code Plain Text](https://user-images.githubusercontent.com/19276747/95662896-1c1c2480-0aef-11eb-9faa-9a781d9189ad.gif)

**Comment by claudiaregio** [comment]
Closing as this is no longer happening

**Comment by claudiaregio** [comment]
Reopening as I figured out the pattern. This only happens if the previous cell is a markdown cell. 

![Add Code Broken](https://user-images.githubusercontent.com/19276747/99338774-b9c6ea00-2839-11eb-819b-66796c4f8c39.gif)

**Comment by rebornix** [comment]
@DonJayamanne we had discussions about this before and we might need some way to indicate what's the preferred language to use when creating new code cells.

**Comment by DonJayamanne** [comment]
@rebornix 
I think providing an API asking from the extension for the preferred language is a better way.
**Here are some scenarios we need to consider:**
* Most kernels in Jupyter only support a single language
	* Thus when using such kernels, the default language of the cell is same as the kernel langauge
* Some kernels support multiple languages
	* In such cases, the language will be determined by the user
	* We don't know the languages a kernel supports out of the box

**Suggestion**
* For new cells use the language of the previous code cell
	* I.e. walk backwards from current cell, & look for the first code cell
* If there are no code cells
	* Then optionally provide an extensibility point for extension to provide the default language
	* E.g. at a property on NotebookMetadata for the default cell language.

**Comment by rebornix** [comment]
@DonJayamanne agree on the suggestions. I pushed a change to find nearest code cell and use its language. 

> Then optionally provide an extensibility point for extension to provide the default language

I'll think about the API together with kernel language support.

**Comment by misolori** [comment]
@claudiaregio are you still seeing this? Was testing this today and didn't reproduce so I think it's fixed @rebornix?

**Comment by claudiaregio** [comment]
No I am no longer seeing this! looks fixed! :)
