### ISSUE TITLE
activeTextEditor edit event get stuck and then do everything at once

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#108488]
- VSCode Version: 
![image](https://user-images.githubusercontent.com/55927613/95681651-03883900-0bd9-11eb-899b-1953966e9bf2.png)

- OS Version:
Windows 10

Steps to Reproduce:

 - 1. Create a Webview. 

 - 2. Add a OnDidChangeViewState event to the Webview Panel. Use this event to save a reference to the activeTextEditor you were before switching focus from or to the Webview Panel. 
Example: Open an empty editor and call your webview. Check that whenever you change focus to or from the webview the OnDidChangeViewState is called. Use this event to set save the active text editor you were before focusing on the Webview. In the debug console, check that you have a reference to the previous editor. Now click on the webview and make sure that this.activeTextEditor still has a reference to that editor. And make sure that the extension always know what is the active text editor after focusing on the webview.

 - 3. Create an action on your webview to post a message to vscode to call this.activeTextEditor.edit(callback) method.

 - 4. On the edit callback get the position the user were in the editor and insert text there, using
`
this.activeTextEditor.edit((editBuilder) => {
    editBuilder.insert(position, 'your text');
});
`

 - 5. From the webview keep posting messages to call the method that has `this.activeTextEditor.edit(callback)`. You can use a button to do this. Notice that nothing happens for a few seconds, but then 'your text' appears multiple times on the editor (because you kept calling the method). After this weird behavior, continue calling the action and notice that now as soon as you call the action the text is added to that editor right away. And the error is gone.

OBS: when you start calling the this.activeTextEditor.edit() make sure it still has the reference to the editor it was opened before you changed focus to your webview. Also, when you start posting messages to the main thread don't change focus to the editor, keep focusing on the webview. 

OBS: it was working fine on v1.47 and 1.48. On 1.49 I don't know. I noticed this behavior on 1.50.

OBS: if you can't reproduce lets have a chat so I can show it to you.

**Comment by mjbvz** [comment]
Please share the code for sample extension that demonstrates this issue

**Comment by AllanOricil** [comment]
didChangeViewState is called everytime the webview panel changes it state, for instance everytime I click on a different editor tab. Then I save the activeTextEditor reference to use later. Also, I only change the activeTextEditor if the file opened is the type I wanted, which is '.cls', because I don't want the activeTextEditor to be the webview tab again when I click on the webview again.

````javascript
this.didChangeViewState = () => {
      const editor = vscode.window.activeTextEditor;
      const fileNameTokens = editor.document.fileName.split(/\/|\\/);
      const fileName = fileNameTokens.pop();
      if(fileName.includes('.cls'))
        this.activeTextEditor = editor;
    };
````

````javascript
this.panel.onDidChangeViewState(
        (state) => this.didChangeViewState(state),
        undefined,
        context.subscriptions
      );
````

Then in the Webview there is a button that post a message to the main thread to call the method below. This method is adding a text sent from the Webview into the editor that I was focusing before changing to the webview again. It works, but after a few clicks on the button, and it adds like 3/4 times the same text. After this weird behavior it works as soon as I click in the button. 

````javascript
addToApex: (soql) => {
        if(this.activeTextEditor && this.activeTextEditor.selection.isEmpty) {
          const position = this.activeTextEditor.selection.active;
          this.activeTextEditor.edit((editBuilder) => {
            soql = soql.replace(/\n/g, ' ');
            soql = soql.replace(/ +(?= )/g, ' ');
            editBuilder.insert(position, `[${soql}]`);
          });
        }
      },
````

**Comment by mjbvz** [comment]
Please share a complete, self contained extension example that shows the problem. It can build on the [webview sample](https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample)

**Comment by AllanOricil** [comment]
@mjbvz I implemented the same code in the sample and there it works without any problems. I don't really know yet what is the problem. But here is the sample with the logic that doesn't work on my extension

https://github.com/AllanOricil/webviewsample

**Comment by AllanOricil** [comment]
@mjbvz I think that error happened because I was with some breakpoint somewhere. Now It is working as expected. Thank you anyway.
