### ISSUE TITLE
[File Hierarchy] Old selection not removed upon new selection

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#10847]
- VSCode Version: 1.4.0
- OS Version: Windows 10

I am not sure what caused this, but once in awhile I have multiple items selected, even though one of the items is not selected. Somehow it isn't clearing the old selection when a new selection is selected.

Here is an example:

![multiple-select](https://cloud.githubusercontent.com/assets/1571806/17899874/76a02cda-6922-11e6-9be8-6e298b7ab4a9.PNG)

**Comment by bpasero** [comment]
Standard tree behaviour, I guess the one is the select, the other is the focus.

**Comment by joaomoreno** [comment]
This happens due to the [`FileController`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L545) treating folders differently from files, regarding focus and selection.

**Comment by bpasero** [comment]
I hate that old controller...

**Comment by sandy081** [comment]
@bpasero Any steps to verify this?

**Comment by bpasero** [comment]
Yeah make sure you cannot select 2 folders at the same time :)

**Comment by TheColorRed** [comment]
No, there really isn't any steps to take. It just seemed to randomly happen.
