### ISSUE TITLE
Actually override instead of reset preference when default value for an otherwise overwritten preference is entered

### ISSUE THREAD

**Issue by WorldSEnder** [microsoft/vscode#108475]
### Expected behaviour:

1. Change a setting in the (user) settings, for example toggle *on* "Format On Save".
2. Open workspace settings UI, and also toggle *on* "Format On Save"
3. Toggle *off* "Format On Save" in the workspace settings
4. "Format On Save" should now be considered *off* in this workspace

### Observed behaviour

4. "Format On Save" is still *on*, because the workspace-specific setting was *reset*, and the configuration set in the user settings is used instead.

There seems to be no way to, from within the settings browser, override, in a workspace, a setting with a value the user settings, with the default value for that setting. Attempting to do so will *unset* the setting instead, hence falling back to the configured user setting. Unsetting a setting can (and imo should) be done with "Reset setting" which currently does the same thing as entering the default value.

The responsible lines of code seem to be

https://github.com/microsoft/vscode/blob/3b99352509cb2bf0cfc65fc567cea100e4a8a279/src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts#L838-L840

The setting value should probably only be reset here if no other/lower priority override exists.

**Comment by roblourens** [comment]
Tracked in https://github.com/microsoft/vscode/issues/58038
