### ISSUE TITLE
Pinned tabs still scroll off

### ISSUE THREAD

**Issue by killerkalamari** [microsoft/vscode#108412]
- VSCode Version: Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:01:33.073Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
- OS Version: Ubuntu 18.04 LTS, Linux x64 4.15.0-117-generic

Steps to Reproduce:

1. Open enough files so that it would require scrolling to see them all.
2. Right-click a tab, then left-click "Pin".
3. Observe that tab moves to left side and shows a pin icon.
4. Use mouse scroll wheel on the tab bar to scroll the tabs.
5. Expected behavior: Pinned tab remains visible on the left side. Actual behavior: Pinned tab scrolls off the screen just like a normal tab would.

Basis for expected behavior:
https://code.visualstudio.com/updates/v1_46#_pin-tabs
"Pinned tabs have a number of useful features to help mark files that are important to you: ... They do not scroll out of view if you have many tabs opened."

Does this issue occur when all extensions are disabled?: Yes

**Comment by seekingtheoptimal** [comment]
Guys this issue is still there with latest VS Code update for me, and all the related/duplicate issues are Closed, yet pinned tabs still scroll out of view. Can this be reopened or should I create a new one?
