### ISSUE TITLE
Workspace doesn't preserve selected source control repositories

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#108495]
- VSCode Version: 1.51.0-insider f5d3ba4d61146b78f0c75c82f3f85232d3409bc1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. open a workspace that contains multiple git repositories
2. in the "Source control repositories" view, select only a subset of them
3. restart VSCode

Expected: the same subset of git repos is selected
Actual: all git repos are selected again

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
#104629
