### ISSUE TITLE
settings synchronization. Unable to close normally

### ISSUE THREAD

**Issue by LuoZhiW** [microsoft/vscode#108440]
Issue Type: <b>Bug</b>

When I turn on settings synchronization. Unable to close normally

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.55GB free)|
|Process Argv|--crash-reporter-id 893c0b8c-63a9-420f-b2a3-abc819e8b7ea|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.50.2
python|ms-|2020.9.114305
vetur|oct|0.28.0

</details>

**Comment by roblourens** [comment]
Please explain what you mean by "unable to close normally"
