### ISSUE TITLE
Prompts appearing for "visual studio code wants to use your confidential information stored in vscode.github.login"

### ISSUE THREAD

**Issue by laurameckley-wk** [microsoft/vscode#108419]
- VSCode Version: 1.50.0
- OS Version: MacOS 10.14.6

Steps to Reproduce:

1. Open VSCode
2. Repeated prompts for password access appear around every 30 seconds, despite hitting "Deny"
There are two separate prompts:
`visual studio code wants to use your confidential information stored in vscode.github.login in your keychain`
`visual studio code wants to use your confidential information stored in VS Code Account in your keychain`

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
@RMacfarlane I know we have https://github.com/microsoft/vscode/issues/108342 specifying the happy path for "Always Allow", not sure if we're tracking issues when "Deny"ing anywhere?

**Comment by RMacfarlane** [comment]
I think https://github.com/microsoft/vscode/issues/108342 also covers that the prompt is shown again when hitting "Deny", so I'll go ahead and close this as a duplicate. Thanks!

**Comment by youngjae99** [comment]
I have a same problem... plz anybody help me

**Comment by christophergaughan** [comment]
I'm having the same problem Mac OS Catalina v 10.15.7

**Comment by BenGedi** [comment]
I'm having the same problem Mac OS Catalina v 10.15.7

**Comment by gane5hvarma** [comment]
I'm having the same problem Mac OS Catalina V10.15.1

**Comment by chuckthepiranha** [comment]
I am having this problem as well. It won't go away no matter what I do.

**Comment by chuckthepiranha** [comment]
Even when I enter the password

**Comment by danielbettech** [comment]
I have the same problem. I enter my password and won't go away.

**Comment by chuckthepiranha** [comment]
Hey I finally got it to go away. I had to enter password and press always allow and then repeat the process like 8 times and then it finally went away.

**Comment by Nirrleybo** [comment]
Same here. Choosing "Deny" 20394948 times won't make it go away

**Comment by amer1616** [comment]
i have the same annoying popup!! any solution!

**Comment by yumindeckard** [comment]
I don't even know what my confidential information is.

**Comment by connietran-dev** [comment]
Is there an explanation for what the confidential information and keychain are?

**Comment by alessiochiffi** [comment]
Same problem here. It used to work fine, might be github?

**Comment by m4rt1n82** [comment]
same!

**Comment by alessiochiffi** [comment]
Solved removing the login GitHub keychain as suggested here https://github.com/microsoft/vscode/issues/108342

**Comment by PawanBhandarkar** [comment]
I have the same issue on macOS Catalina 10.15.6

**Comment by MuhamadRFauzi** [comment]
I have the same issue on macOA Catalina 10.15.6

**Comment by vinod827** [comment]
same issues guys

**Comment by kockok** [comment]
too annoying! I need to frequently click 'Deny' and exit the prompt!! Temporarily switched to Atom as a remedy. Please fix this soon!!!

**Comment by rachelfranklin1** [comment]
same issue on MacOS Catalina 10.15.6. Fixed by clicking "Always allow"!

**Comment by kpose** [comment]
this is too disturbing, any workaround yet?

**Comment by PawanBhandarkar** [comment]
> Solved deleting the login GitHub keychain `vscode-github.login` as suggested here #108342
This worked for me.

**Comment by gatmeister** [comment]
It's on Catalina 10.15.5 as well. Deleting the vscode-github.login via Keychain Access fixed it for me

**Comment by RMacfarlane** [comment]
Please see https://github.com/microsoft/vscode/issues/108342 to track this.

There was an architectural change so that a different VSCode process than before is now accessing the keychain, a nice write up on this is here: https://github.com/microsoft/vscode/issues/108342#issuecomment-706340396. VSCode is requesting access specifically to a credential it wrote in the keychain. Choosing "Deny" or "Allow" on the prompt does not persist the choice, it only handles that particular access request. Because we were polling on the keychain, choosing one of those options would cause the prompt to reappear repeatedly.

We have made a fix to remove polling (https://github.com/microsoft/vscode/commit/4c0811c9c2b58251fbb09ecc77a739e023759df9) which will be shipped as part of a recovery build this week. You can try out the changes by using our [insider's version](https://code.visualstudio.com/insiders/). As others have said, removing the credential from the keychain should also stop the prompts. Choosing "Always Allow" so that VSCode has persistent access to its credential should also work.

**Comment by boutell** [comment]
"Always Allow" doesn't make this go away, but like others I found it went away after I entered my password about eight times.

**Comment by Yedzinovich** [comment]
I have the same problem. Why does this ticket was closed if there is no valid solution?

**Comment by krishnaindani** [comment]
I am also having same issue on mac. Prompting many times.

**Comment by amer1616** [comment]
Solved deleting the login GitHub keychain access vscode-github.login as On 16 Oct 2020 4:22 am, Krishna Indani <notifications@github.com> wrote:
I am also having same issue on mac. Prompting many times.

**Comment by jcarlos78** [comment]
Same problem after updating vscode in mac.

**Comment by RMacfarlane** [comment]
Please see https://github.com/microsoft/vscode/issues/108342#issuecomment-706340396 for an explanation of this issue.

Choosing the "Always Allow" option for each credential should stop the repeated prompts, or as others have said, you can delete the credential from the keychain or credential manager.
