### ISSUE TITLE
Label is not read by screen readers in trees rendered by TreeDataProvider when the item has a description

### ISSUE THREAD

**Issue by Neurrone** [microsoft/vscode#108480]
/CC: @isidorn 

Issue Type: <b>Bug</b>

1. Install the [markdown notes extension](https://github.com/kortina/vscode-markdown-notes)
2. Open a new workspace and create 2 .md files, one with a link to the other.
3. Focus on the backlinks view, which this extension provides.

*Expected*:

When using the extension with NVDA and in the backlinks view, the file name + number of references are read.

*Actual*:

Only the number of references are read.

*Additional information*:

I did some preliminary investigation after [filing this issue on the extension's repo](https://github.com/kortina/vscode-markdown-notes/issues/67). I am now suspecting that this is actually a bug in Vs Code.

Looking at the BacklinksTreeDataProvider.ts in the extension's source code, it sets the label of the tree item as the file name, and the description is the number of references found to that file which looks perfectly correct. Hence, I'm suspecting that Vs Code itself is not rendering the tree correctly to ensure that screen reader users can hear both the label and description when set. Right now, only the description set on the tree item is heard.

I couldn't figure out how to inspect the element in the backlinks view to see what the DOM looked like to see what is actually wrong.
 My suspicion is that the aria-label set on the tree item is not combining both pieces of information.

**Comment by isidorn** [comment]
@alexr00 I am not sure how visible the desciription is, if it is visible then it sounds like the default aria-albel should also contain the description. If not then the extension should provide an aria-label which is now part of our API.

Anyways let me know if you would like me to help here.

**Comment by Neurrone** [comment]
The extension specified 2 parameters, label and description. Both show up visually.

So the bug is that the aria-label only shows the description, not both like it does visually, causing information to be lost.

**Comment by alexr00** [comment]
@joaomoreno I'm not seeing the aria label I set in the tree view get used by the tree. I set the aria label here:

https://github.com/microsoft/vscode/blob/0e43c7a495541bb2388d7004ba94c275cc44d442/src/vs/workbench/contrib/views/browser/treeView.ts#L397-L397

So for a tree element without a tooltip but with a label and description, I expect both the label and description to be read. However, it seems like the aria label set there is being ignored. You can repro this by hovering hover a file element in the references tree view. Am I using the accessibility provider incorrectly?

**Comment by isidorn** [comment]
@alexr00 it looks like you are using label provider correctly.
If you have a good case for debugging I would just check the caller of that method, and make sure you get called and it gets propagated all the way up. Since there are a lot of tree wrappers and I might have missed some cases to just propage the result of the `getAriaLabel`

**Comment by joaomoreno** [comment]
@alexr00 Let me know if you want to go on a debug Teams session.

**Comment by alexr00** [comment]
I'm not able to repro this issue now. I will leave this issue in the January Milestone so it gets tested.

The logic behind what the aria labels:
1. Use accessibility information that was set by the extension if it exists.
2. If not (1), then use the `tooltip` if it is a string.
3. If not (1) and (2), Use the label + the description.

**Comment by isidorn** [comment]
@Neurrone let us know if you still see this with VS Code insiders

**Comment by JacksonKearl** [comment]
Still seeing this issue, voiceover says only the description element and in the DOM I can see that the aria label haas been set to only contain the description element. 

![image](https://user-images.githubusercontent.com/8586769/106078394-30992280-60c8-11eb-92a2-a05f8d7c0362.png)

**Comment by alexr00** [comment]
I still can't repro this. I tested with the "Reference: Callers Of" view. @JacksonKearl what view is that? Is it possible that the view you're using sets a tooltip or accessibility information on the tree items? The "Reference: Callers Of" view sets neither and so gets the default behavior that is specified in this issue (<label> <description>).

**Comment by JacksonKearl** [comment]
Confirmed the correct behavior in [tree view sample extension](https://github.com/microsoft/vscode-extension-samples/tree/master/tree-view-sample). The markdown notes extension is explicitly setting the tree item's tooltip to only the description, which causes the aria label to also be only the description. Followed up with them in the original issue.
