### ISSUE TITLE
`relativeFileDirname` gives empty string when the Dirname equals to current working directory

### ISSUE THREAD

**Issue by escape0707** [microsoft/vscode#108437]
- VSCode Version:
- OS Version:
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. I use C++ extension and configured `tasks.json` to use task to get my source code compiled.
The part of the `tasks.json` relatives to this issue is basically like this:
```json
      "command": "clang++",
      "args": [
        "-g",
        "${relativeFile}",
        "-o",
        "${relativeFileDirname}/${fileBasenameNoExtension}.exe"
      ]
```
2. VSCode now synthesizes this command as `clang++ -g tmp.cpp -o /tmp.exe`,
rather than previously in VSCode version 1.49.3, `clang++ -g tmp.cpp -o ./tmp.exe`.
3. The compiler will get `permission denied` for trying to write to root folder, of course.

Should  `relativeFileDirname` still be `.` under such cases or not?

Currently I reverted to 1.49.3.

**Comment by alexr00** [comment]
To verify:
- Open a folder with some files in VS Code
- Add the following task:
```json
		{
			"label": "test variable",
			"command": "echo ${relativeFileDirname}/${fileBasenameNoExtension}",
			"type": "shell",
			"problemMatcher": []
		}
```
- Open a file in from your folder **that is at the top level of your folder, not in a subfolder**
- Run the task
- Verify that the task outputs `./<your file name>` and not `/<your file name>`
