### ISSUE TITLE
VS Code running Pester test gives odd results

### ISSUE THREAD

**Issue by maxcli** [Microsoft/vscode#10849]
•VSCode Version: 1.4.0

•OS Version: win 10 ver 1601

In  VS Code, this assert fails. The same assert works fine in Powershell ISE.
it "**Verify functionxx mock was called one time" {
Assert-MockCalled functionxx -Exactly 1

Steps to Reproduce:
1. debugging powershell pester test , 
2.

**Comment by sandy081** [comment]
I wonder it could be related to the power shell extension on VS Code. I would suggest to check with the extension - https://github.com/PowerShell/vscode-powershell
