### ISSUE TITLE
python not recognized properly after updating to 3.9

### ISSUE THREAD

**Issue by AliMejbar** [microsoft/vscode#108490]
after updating python to 3.9 I can't jump to functions definition , get outline and code structure.
Python Version : 3.9
Extensions installed : Python Extension by Microsoft.
Thank's in advance.

**Comment by joyceerhl** [comment]
Hi @AliMejbar, I'm a developer on the Python extension by Microsoft. We'd appreciate it if you could file this issue directly with us: https://github.com/microsoft/vscode-python.

When you file an issue with us, please also give us information on which Python language server you are using (Pylance, Microsoft, or Jedi) so we can better assist you! You can check this by looking at the `python.languageServer` value in your user settings.json file.

Thanks very much!

**Comment by AliMejbar** [comment]
> Hi @AliMejbar, I'm a developer on the Python extension by Microsoft. We'd appreciate it if you could file this issue directly with us: https://github.com/microsoft/vscode-python.
> 
> When you file an issue with us, please also give us information on which Python language server you are using (Pylance, Microsoft, or Jedi) so we can better assist you! You can check this by looking at the `python.languageServer` value in your user settings.json file.
> 
> Thanks very much!

hi thank's for your help , reinstalling the python extension worked , Thank you.
