### ISSUE TITLE
[folding] Add option to collapse/hide stdout lines in file w/ language support

### ISSUE THREAD

**Issue by blaney83** [microsoft/vscode#108416]
Stdout statements (py: `print`, js: `console.log`, java: `System.out...`, etc.) have a time and place and can be helpful when used with log levels to write clean, self-documenting code. However, when developing they can sometimes lead to unnecessary scrolling or other obfuscation of the code itself.

A feature where you can collapse/hide these stdout statements in the same way you can collapse code blocks/doc comments would be extremely helpful/useful in certain scenarios, e.g. working without an additional monitor. Don't know how this might look from a UI perspective in the line number UI- but something similar to the code block collapser/debug marker but for stdout. Perhaps even utilizing the file search field (CTRL+F) as a "Hide lines starting with..." + existing Case/Regex/MagicMarker controls could be one approach.

Not sure if this is a usecase for others or I am just working on a particularly verbose file at the moment.

**Comment by blaney83** [comment]
Don't want to distract from the initial proposal, but building on the idea of using the file search UI, a general "Hide lines" function would suffice with regex support, allowing the use of comments + a "magic marker" to differentiate lines which are used debugging/analysis vs. application logic.

Disclaimer: the project which gave me this idea is a personal project which has lots of benchmarking + data gathering spread throughout the code. This might not be helpful for your typical "production-ready" project.

**Comment by aeschli** [comment]
Just to note, many languages support folding markers e.g. `//#region` in JavaScript/TypeScript.
Would that help you.

https://github.com/microsoft/vscode/issues/104667 is a similar request than yours.
