### ISSUE TITLE
Add extension integration tests support for packaged .vsix file.

### ISSUE THREAD

**Issue by freedomhero** [microsoft/vscode#108435]
I'm trying to write some integration tests for an extension. From the [document](https://code.visualstudio.com/api/working-with-extensions/testing-extension) I learned that it's possible to start the tests by using the project's root path as the `extensionDevelopmentPath` parameter, like the code in the demo:

```
import * as path from 'path';

import { runTests } from 'vscode-test';

async function main() {
  try {
    // The folder containing the Extension Manifest package.json
    // Passed to `--extensionDevelopmentPath`
    const extensionDevelopmentPath = path.resolve(__dirname, '../../../');

    // The path to the extension test runner script
    // Passed to --extensionTestsPath
    const extensionTestsPath = path.resolve(__dirname, './suite/index');

    // Download VS Code, unzip it and run the integration test
    await runTests({ extensionDevelopmentPath, extensionTestsPath });
  } catch (err) {
    console.error(err);
    console.error('Failed to run tests');
    process.exit(1);
  }
}

main();
```

But my question is that how can I start the tests for an extension packaged as .vsix file. Because it may be different after the webpack process, and I want to make sure it does not break. Any idea is welcome.

**Comment by xhliu** [comment]
We have seen issue after webpack obfuscation, which causes extension to malfunction after packaging into `vsix`.
