### ISSUE TITLE
Adding default Close Side Bar Keybinding

### ISSUE THREAD

**Issue by nEuDy** [microsoft/vscode#108461]
Adding a Close Side Bar Keybinding for closing the Side Bar, would be very helpful. It's possbile, to open the Side Bars by shortcuts, but not to close by default.

In my opinion, following options is very helpful:

CommandID: workbench.action.closeSidebar
Default Keybinding: "Ctrl + w"
Default "When": "sideBarFocus && sideBarVisible"

**Comment by ArturoDent** [comment]
You can create your own keybinding:

```
  {
    "key": "ctrl+w",
    "command": "workbench.action.closeSidebar",
    "when": "sideBarFocus && sideBarVisible"
  },
```

Is there some reason this isn't what you want?

**Comment by JacksonKearl** [comment]
There should actually be a `toggle sidebar` command available by default: 
```
{
  "key": "cmd+b",
  "command": "workbench.action.toggleSidebarVisibility"
}
```
