### ISSUE TITLE
Cannot find a way to change color and boldness of VSC app text

### ISSUE THREAD

**Issue by David263** [microsoft/vscode#108455]
- VSCode Version:1.50.0
- OS Version:Windows 10 Home

Steps to Reproduce:

1.Run VSC 
2.Select Menu > Help > Interactive Playground.
3. Observe that the text near the top of the screen is in two shades of gray against a gray background. I need text to be in black boldface against a white or gray background to see it clearly, so that VSC is usable for me.
4. Search through the Menu > Preferences > Settings and observe that there seems to be no way to change the appearance of text in the VSC app, only in the editor text panes.

Does this issue occur when all extensions are disabled?: Yes, exactly the same.

**Comment by JacksonKearl** [comment]
Hey @David263, have you tried changing the theme (F1 => `Preferences: Color Theme`)? This changes the text colors in the entire app, not just editors. 

Light+:
![image](https://user-images.githubusercontent.com/8586769/95779355-beb6dd80-0c7e-11eb-969f-649e26cc8d59.png)

Dark+:
![image](https://user-images.githubusercontent.com/8586769/95779417-e312ba00-0c7e-11eb-895d-69851df87f07.png)

High Contrast:
![image](https://user-images.githubusercontent.com/8586769/95779431-ead25e80-0c7e-11eb-9903-b3af5ff049c7.png)

That being said, I agree that the headings on that page are quite thin. cc @misolori for design ideas.

**Comment by misolori** [comment]
We don't have any settings that control the boldness of the UI. Also, the heading weights are also determined by the system font and in the last couple of releases on macOS the default font has been made lighter. I think when we work on updating the UI for the welcome page we should update all of the headings because they are the same there as well.

**Comment by David263** [comment]
Yes, I tried all the themes. None work well for me. Since VSC has other problems for me, not just this one, I'll keep on looking for a good editor. I found 010 Editor, which is low in bugs and high in reliability, but the developer wants to focus on editing structured binary data rather than programming text. I've also evaluated about 14 other editors, but haven't found a great one yet.

**Comment by JacksonKearl** [comment]
@David263 is the main problem the weight of the text?
