### ISSUE TITLE
Cannot sign in to sync settings

### ISSUE THREAD

**Issue by zendu** [microsoft/vscode#108411]
Issue Type: <b>Bug</b>

Shows error in Microsoft Account extension. This prevents from signing in to sync settings.

Writing login information to the keychain failed with error 'The stub received bad data. '.

VS Code version: Code - Insiders 1.51.0-insider (f5d3ba4d61146b78f0c75c82f3f85232d3409bc1, 2020-10-09T05:34:54.647Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.29GB free)|
|Process Argv|--crash-reporter-id 0b98f0c7-3ae6-4e62-8a44-ee3c183c3704|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
ng-template|Ang|0.1001.0
vscode-eslint|dba|2.1.10
githistory|don|0.6.11
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
gc-excelviewer|Gra|3.0.40
beautify|Hoo|1.5.0
vscode-edit-csv|jan|0.4.2
rainbow-csv|mec|1.7.1
csharp|ms-|1.23.2
vscode-dotnet-runtime|ms-|0.1.2
vscode-edge-devtools|ms-|1.0.9
sarif-viewer|MS-|3.0.1
remote-wsl|ms-|0.50.0
azure-account|ms-|0.9.3
azurecli|ms-|0.5.0
powershell-preview|ms-|2020.9.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2902
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
azurerm-vscode-tools|msa|0.13.0
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
vscode-data-preview|Ran|2.2.0

</details>

**Comment by IllusionMH** [comment]
Error looks a bit different but maybe related to #108362

/cc @RMacfarlane

**Comment by keeganwitt** [comment]
Here's the output from Microsoft Authentication, but it's not much more detail.

This happens every time the program is launched on the Insider build on Windows, but doesn't happen on the stable build on Windows or on either build on MacOS.

```
[Info  - 17:54:09.997] Logging in...
[Info  - 17:54:13.298] Exchanging login code for token
[Info  - 17:54:13.625] Exchanging login code for token success
[Info  - 17:54:13.626] Login successful
[Info  - 17:54:13.626] Token available from cache, expires in 3599000 milliseconds
[Info  - 17:54:13.629] Token available from cache, expires in 3598997 milliseconds
[Info  - 17:54:13.629] Token available from cache, expires in 3598997 milliseconds
[Info  - 17:54:13.630] Token available from cache, expires in 3598996 milliseconds
[Error  - 17:54:13.634] Setting token failed: Error: The stub received bad data.

[Info  - 17:54:38.103] No stored keychain data, clearing local data
```

**Comment by JustinGrote** [comment]
Version: 1.51.0-insider (user setup)
Commit: 605bc4ec1eaf8dc1acd89a0c3c5743926ed0dc09
Date: 2020-10-12T10:52:10.028Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

As of this version, I still see the error but it seems to continue and settings sync to Microsoft works for me again.

**Comment by zendu** [comment]
Error message has changed to "Writing login information to the keychain failed with error 'The stub received bad data. '." on today's update.

Version: 1.51.0-insider (user setup)
Commit: 605bc4ec1eaf8dc1acd89a0c3c5743926ed0dc09
Date: 2020-10-12T10:52:10.028Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by JustinGrote** [comment]
Thanks @RMacfarlane! Will verify when the next insiders comes out and report back.

**Comment by aeschli** [comment]
Verified that setting up syncing with a Microsoft account works on Windows and Ubuntu.
@RMacfarlane Please add verification steps if more is needed
