### ISSUE TITLE
Native windows titlebar keyboard shortcuts are broken

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#108469]
Issue Type: <b>Bug</b>

With window.titleBarStyle configured to native

1. Press alt to select the menubar
2. Press F for file

The file menu is not opened. 

In fact, none of the shortcuts work anymore. 

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.21GB free)|
|Process Argv|--crash-reporter-id d5ea691a-3712-4101-aae4-25ab7111fae5 --crash-reporter-id d5ea691a-3712-4101-aae4-25ab7111fae5 --crash-reporter-id d5ea691a-3712-4101-aae4-25ab7111fae5|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ArturoDent** [comment]
And you have `Enable Menu Bar Mnemonics` enabled?

**Comment by sbatten** [comment]
@deepak1556 Since the native menus are not default on Windows, I have forgotten if this used to work, but it seems in the latest versions, electron will show she registered mnemonics but after the menubar is focused, pressing any will not have any effect.

**Comment by deepak1556** [comment]
Yeah it was never explicitly supported https://github.com/electron/electron/issues/10637

Using `Alt+mnemonic key` will work currently. Closing as there is nothing actionable from our end.

**Comment by phgmacedo** [comment]
@deepak1556 Alt+mnemonic key is not working. That's why I opened the issue.

**Comment by deepak1556** [comment]
I am unable to repro the issue

[mnemonic.webm.zip](https://github.com/microsoft/vscode/files/5381179/mnemonic.webm.zip)

**Comment by phgmacedo** [comment]
@deepak1556 You're reproing wrong. 

How I expected to work:

1. press and release alt
2. Press the mnemonic key

**Comment by phgmacedo** [comment]
@deepak1556 Comparison with other editors (this behavior is consistent with other software that uses the menubar): 


![4qP6JmDUpj](https://user-images.githubusercontent.com/2473545/96062196-77da0b00-0e6b-11eb-92e4-40b235431a69.gif)

**Comment by deepak1556** [comment]
Thanks for clarifying https://github.com/microsoft/vscode/issues/108469#issuecomment-708822254 , I can open a new issue in electron since vscode doesn't draw the native menubar.

**Comment by rzhao271** [comment]
The issue still occurs on the latest Insiders using the native titlebar.
The current best workarounds are to use the custom titlebar, or to press the alt and mnemonic keys at the same time.
