### ISSUE TITLE
 Initializing JS/TS language features spinning constantly #103740 still happening

### ISSUE THREAD

**Issue by David263** [microsoft/vscode#108454]
- VSCode Version:1.50.0
- OS Version:Windows 10 Home

Steps to Reproduce:

1.Install VSC or update to version 1.50.0
2.Open some Help pages.
3.Click on the tab for an existing file ("Interactive Playground").
Observe that the purple status bar has a spinner "Initializing JS/TS..." at the left. It never stops spinning.

Does this issue occur when all extensions are disabled?: Yes!
See #103740.

**Comment by ell1e** [comment]
I recently saw this too, and only got it to stop by disabling `TypeScript and JavaScript Language Features` (the "rich" plugin) entirely. Not that I care, since I don't use TS/JS much anyway. But obviously, that shouldn't be required to not make it do that

**Comment by David263** [comment]
I don't have such a Typescript plugin. My VSC contains Insert Unicode, PHP interphense, Restore Editors, and Save All only.

**Comment by ell1e** [comment]
Click "Extensions" > "Filter Extensions..." (the left-most icon on the top of the extensions search window) > "Built-in" to see it, it doesn't normally show in the regular list

**Comment by David263** [comment]
There are a lot of these. What is the exact name, please?

**Comment by ell1e** [comment]
As I already wrote above it is named: `TypeScript and JavaScript Language Features`

The list is alphabetical, so with a bit of scrolling you should hopefully find it

**Comment by David263** [comment]
Oh, I disabled "TypeScript Language Basics" before I saw the screenshot. My bad. I've corrected it. For future reference, it is in the Extensions > Features section, as shown clearly in the screenshot. Thanks.

**Comment by mjbvz** [comment]
Closing this as:

- It only effects the interactive playground
- The interactive playground is not much used

**Comment by ell1e** [comment]
@mjbvz is the playground to be removed then? Otherwise this decision would seem pretty inconsistent

**Comment by mjbvz** [comment]
Actually this effects other in-memory resources too so reopening. To verify:

- Use the Fs provider extension sample
- Open

**Comment by David263** [comment]
This strange bug thread is one reason I've decided not to use VSC as my code editor. I don't want to use an editor, no matter how otherwise functional, that can't fix its own bugs in an intelligent and timely way.

**Comment by mjbvz** [comment]
Somedays you just can't win at open source :)

**Comment by David263** [comment]
mjbvz,. I think that is true. Only when there are good bug fixers and good documentation writers and good designers and good coders in the active community does Open Source really shine. Otherwise, I've evaluated 14 code editors and discovered that those that are sold by a single developer for money are freest of bugs and the best documented. In may cases, they are also the most functional products.

**Comment by David263** [comment]
It may be of interest to those who have been following my search for a code editor to know that I've given up my search as fruitless and plan to write my own. It will be lightweight, easily extendible, and work with all OSs because it will be an Ajax/JavaScript/PHP/Bootstrap self-hosted website. It will welcome an Open Source community for extensions and suggestions only, and I will fix any bugs and document it myself.
