### ISSUE TITLE
C++20

### ISSUE THREAD

**Issue by IgaMeddie** [microsoft/vscode#108481]
Issue Type: <b>Feature Request</b>

Please enable C++20 for microsoft build tools as a default version of C++. 

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

**Comment by alannt777** [comment]
This repository does not contain C++ language features for VS Code. Please file an issue in [this repository](https://github.com/microsoft/vscode-cpptools)

**Comment by JacksonKearl** [comment]
\extC++
