### ISSUE TITLE
Release Notes is smooth-scrolling

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#108471]
Issue Type: <b>Bug</b>

The Release Notes page is smooth scrolling, but I have disabled smooth scrolling for accessibility purposes.

With this bug in place, it is next to impossible for me to use this page. Please make it respect the smooth scrolling setting.

Btw, the same goes for the issue reporter when the window is smaller than its contents.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (25.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
overtype|ada|0.2.0
Bookmarks|ale|11.3.1
color-info|bie|0.5.1
mustache|daw|1.1.1
vscode-eslint|dba|2.1.10
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.15.1
vscode-great-icons|emm|2.1.57
file-icons|fil|1.0.26
duplicate|gee|1.0.1
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.6.0
remote-wsl|ms-|0.50.0
vscode-sort-json|ric|1.18.1
code-settings-sync|Sha|3.4.3
vscode-svg-previewer|vit|0.6.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
@deepak1556 This should previously have been fixed in https://github.com/microsoft/vscode/pull/65422. Are you aware of any recent electron updates around smooth scrolling?

**Comment by deepak1556** [comment]
@mjbvz the PR you are referring to had its change reverted here https://github.com/microsoft/vscode/issues/76665 , so unless the user passes the flag there wouldn't be any effect.

@thany does it help when you launch the app with `--disable-smooth-scrolling`

**Comment by thany** [comment]
Could it be that this issue is fixed? I'm not seeing this on 1.50.1 anymore. Although I'm on a different pc now. Both are Windows 10 though, but I think the accessibility settings are slightly different.
