### ISSUE TITLE
Please include files from the project in the list of recently opened files.

### ISSUE THREAD

**Issue by huye** [microsoft/vscode#108432]
Issue Type: <b>Feature Request</b>

When there are many files in a project, it can be difficult to find the previously closed files again. 
Please add at least one configuration option for setting.

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:56:11.027Z)
OS version: Linux x64 5.4.50-amd64-desktop

**Comment by huye** [comment]
In particular, switching back and forth between directories can be a pain to open a file.

**Comment by isidorn** [comment]
Forwarding to @sbatten as I believe he owns the recently opened list. Sorry if I am mistaken.

**Comment by sbatten** [comment]
Ctrl+P shows recently touched files within the project already

**Comment by huye** [comment]
Thanks a lot.
But why not put them together with open history?
