### ISSUE TITLE
git submodules missing from vscode when specified as "url=http" without spaces, works as "url = http"

### ISSUE THREAD

**Issue by jeske** [microsoft/vscode#108417]
Steps to Reproduce:

1. create a git repository with a submodule
2. edit `.gitmodules` and remove the spaces from the url spec, so instead of `url = http://...`, it looks like `url=http://...`
3. check in the new .gitmodules spec (without spaces in the URL)
4. **restart VSCode**: WITNESS: the submodule is missing from VSCode git support
5. WITNESS:  it works fine in git, gitkraken, github client, every other git client
6. edit '.gitmodules' to put the spaces back in the URL spec, check it in...
7. WITNESS: the submodule reappears in vscode git

Does this issue occur when all extensions are disabled?: Yes

## example .gitmodules specs

This breaks vscode git, but works fine in git command line 

```
[submodule "Build/Assets"]
	path = Build/Assets
	url=https://github.com/VisualStoryCreator/VSC-Assets-Dev
```

This works fine

```
[submodule "Build/Assets"]
	path = Build/Assets
	url = https://github.com/VisualStoryCreator/VSC-Assets-Dev
```

## vscode version info

> Version: 1.50.0 (system setup)
> Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
> Date: 2020-10-07T06:08:02.231Z
> Electron: 9.2.1
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT ia32 10.0.18362

**Comment by joaomoreno** [comment]
Fixed by 47116a8
