### ISSUE TITLE
ShellExecution issue with env variables.

### ISSUE THREAD

**Issue by brianignacio5** [microsoft/vscode#108445]
- VSCode Version: 1.50.0
- OS Version: macOS Catalina 10.15.5 and Windows 10

The code of an extension can affect other extension. For example PlatformIO modifies the `process.env`. In our extension we are trying to use a modified copy of `process.env` where we expand PATH with some additional paths. If PlatformIO is enabled, the env update doesn't work. If it is disabled, the env is updated without any issues.

Steps to Reproduce:

```
const newEnv = Object.assign({}, process.env);
newEnv.PATH = extendedPath;
const shellExec = new vscode.ShellExecution(`echo $Path`, { env: newEnv });
const newTask: vscode.Task = new vscode.Task(taskDefinition, scope, taskName, source, shellExec, problemMatchers);
```

1. Use the taskProvider API with the previously given code with PlatformIO extension activated.

Does this issue occur when all extensions are disabled?: No

**Comment by alexr00** [comment]
@brianignacio5 I'm not sure I understand the problem. Are you saying that the `newEnv` doesn't always get used for the task?

**Comment by brianignacio5** [comment]
Basically `newEnv.PATH` is not visible in the output of `shellExec` and remains with `process.env` (not updated).

**Comment by alexr00** [comment]
I was not able to reproduce the issue. I made a task like this:
```
	const newEnv: { [key: string]: string } = <{ [key: string]: string }>Object.assign({}, process.env);
	newEnv.path = process.env.path + ';c:\\users\\alexr00\\TEST';
	const task = new Task(kind, folder, taskName, 'testTask', new ShellExecution('echo %path%', { cwd: cwd, env: newEnv }), matcher);
```
And when it ran, I could see that my additional path had been added:
```
> Executing task: echo %path% <

C:\Python27\;C:\Python27\Scripts; <lots more path> C:\Users\alros\AppData\Local\Programs\Microsoft 
VS Code Insiders\bin;c:\users\alexr00\TEST

Terminal will be reused by tasks, press any key to close it.
```
