### ISSUE TITLE
alt + e mapping doesn't work when text-focused

### ISSUE THREAD

**Issue by MoxHe** [microsoft/vscode#108478]
```
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:00:00.397Z (3 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
I'm trying to toggle the side bar by pressing alt + e
So I have this in keybindings.json
```
  {
    "key": "alt+e",
    "command": "workbench.action.toggleSidebarVisibility"
  },
```
It doesn't work when my cursor is on text-focused. Instead it types ```´```
Other key bindings like ```alt+w``` works as expected.  
I'm using Mac US keyboard layout. 

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by alexdima** [comment]
Let's track in #41024
