### ISSUE TITLE
Almost every section in the Interactive playground does not work

### ISSUE THREAD

**Issue by pepijndevos** [microsoft/vscode#108457]
Issue Type: <b>Bug</b>

This is the first thing a new user like me will try, and my experience goes as follows:

# Multi-cursor editing

I reloaded the editor and ran into #108378, worked fine after a fresh start

# IntelliSense

No error underline is shown. I do get some suggestions, but I'm not sure if they are the right ones.

# Line Actions

The first action switches Gnome workspace, and does not work. It's also nearly impossible to press, but that's more of a feature request I guess.  I'd also like to just... select and copy whole lines, but this is not covered.

# Rename Refactoring

Pressing F2 does absolutely nothing. This seems to be issue #105154

# Errors and Warning

Again, no errors or warnings are shown. Pressing F8 does nothing. Might be #106655

# JavaScript Type Checking

Not clear what to do. Changing the line to `// @ts-check` does not report any errors.

# Conclusion

Well, lets just say my first impression of this editor is not great.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 5.8.13-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 3981)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.41GB (3.45GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id ca1c52af-04c8-4797-8555-f4c7a474e5c1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.9.114305
cpptools|ms-|1.0.1
rust|rus|0.7.8
vscode-arduino|vsc|0.3.2

</details>

**Comment by chrmarti** [comment]
Thanks for the summary. Tracking issues:

- Multi-cursor editing: #108378
- IntelliSense: #83025
- Line Actions: #18902
- Rename: #105154
- Errors and Warnings: Also #83025
- JavaScript Type Checking: Also #83025 (?)
- General: #109149

**Comment by chrmarti** [comment]
Errors and Warnings still needs an edit to trigger the errors. We'll continue tracking that with #83025.

Closing as the situation has improved.
