### ISSUE TITLE
problem with python in arrow marking of the return (the ->)

### ISSUE THREAD

**Issue by 1kamma** [microsoft/vscode#108483]
- VSCode Version: 1.49.3
- OS Version:10.0.0.19042

Steps to Reproduce:

Does this issue occur when all extensions are disabled?: **Yes**/No
when I write a function in python, and put arrow to mark that the function returns value (the ->), the arrow is destroying the syntax highlight and the linter (the part that checks if the keywords have been typed correctly)
![image](https://user-images.githubusercontent.com/44523436/95677229-c9b13580-0bcc-11eb-8929-bf0e60ccf422.png)

![image](https://user-images.githubusercontent.com/44523436/95677262-f1a09900-0bcc-11eb-90b5-a761a5819d1d.png)

**Comment by alannt777** [comment]
I can't seem to find any squiggly lines that indicate a syntax error and this repository does not contain the Python language features. Please file a _valid_ issue in [this repo](https://github.com/microsoft/vscode-python)
