### ISSUE TITLE
[css] support `contain` property in css

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#10840]
- VSCode Version: 1.40
- OS Version: 10.11.6 (15G31)

The css [`contain` property](https://drafts.csswg.org/css-containment/) is not properly recognized in VScode. Should be
`contain: none | strict | content | [ size || layout || style || paint ]`

**Comment by aeschli** [comment]
As the contain property is still only a draft, we'd rather wait with adding it.

**Comment by equinusocio** [comment]
I think this can be implemented now..
https://www.w3.org/TR/css-contain-1/
