### ISSUE TITLE
Accounts sync menu registers unintended clicks

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode#108421]
Issue Type: <b>Bug</b>

![lwSzeE54jz](https://user-images.githubusercontent.com/2473545/95626789-5505bc00-0a51-11eb-8a53-731c8e568a67.gif)

Repro: 
1. Click and hold the "accounts" menu button in the region like shown in repro gif
2. Release mouse button 

The option "Turn on Settings sync" is clicked without intention, because the menu position is broken. 

Just clicking a menu, without moving the mouse, should not trigger a context menu option. 

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.71GB free)|
|Process Argv|--crash-reporter-id d5ea691a-3712-4101-aae4-25ab7111fae5|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by phgmacedo** [comment]
Another very annoying problem is that since the menu is triggered with right-click as well, doing a right click will also activate the first option, and will prevent the user from selecting any other option like "Hide".

**Comment by sbatten** [comment]
@RMacfarlane we should position it just like the global activity icon

**Comment by sbatten** [comment]
fixed in separate cleanup
