### ISSUE TITLE
终端上的字变白了

### ISSUE THREAD

**Issue by sdsdsdsd0000** [microsoft/vscode#108458]
Issue Type: <b>Feature Request</b>

A long string of words on my terminal has become white. It used to be blue. How to restore it
This is what it looks like now：
![{~VV5YX3KUBDDH`)9R NKLL](https://user-images.githubusercontent.com/72660994/95660374-f0825400-0b59-11eb-93dd-e7989a4af186.png)
This is what it used to be：
![tuer](https://user-images.githubusercontent.com/72660994/95660387-11e34000-0b5a-11eb-8f20-26f0b5d1493d.png)

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
This looks like it's a problem with whatever extension is launching "Java Process Console".
