### ISSUE TITLE
Show Activity Bar on Mouse Hover

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#108492]
Currently we can hide the activity bar and use a key binding to toogle it. But I would like to be able to use the mouse to show the activity bar when I move it to the left or right side of the screen.  The same way we can do with the Taskbar on Windows, or the side and bottom menus on ubuntu and mac os respectivelly.

**Comment by thunder-coding** [comment]
@vscodebot This is not a duplicate issue...

I think the feature requested by AllanOricil is very much needed by all of us.

**Comment by thunder-coding** [comment]
Hey, anyone from the VS Code team. I have a question.

Can I still create a PR to complete this feature request inspite of closing of this issue?

**Comment by AllanOricil** [comment]
> Hey, anyone from the VS Code team. I have a question.
> 
> Can I still create a PR to complete this feature request inspite of closing of this issue?

I think people did not like the idea. That is ok if you leave it closed.
