### ISSUE TITLE
Settings Sync osx and windows

### ISSUE THREAD

**Issue by VasuInukollu** [microsoft/vscode#108489]
Issue Type: <b>Bug</b>

Settings sync is attempting to write to keychain (possibly, osx feature) on windows. I had setup Code to Sync settings between my Windows Desktop and OSX laptop.

VS Code version: Code - Insiders 1.51.0-insider (f5d3ba4d61146b78f0c75c82f3f85232d3409bc1, 2020-10-09T05:34:54.647Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (2.59GB free)|
|Process Argv|--crash-reporter-id 9d87ec80-aa09-4bab-b1b1-5ba3b7443c05|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1001.0
vscode-eslint|dba|2.1.10
docs-markdown|doc|0.2.81
xml|Dot|2.5.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
vs-code-http-server-and-html-preview|Fli|2.2.2
Angular-BeastCode|Mik|10.0.3
csharp|ms-|1.23.2
mssql|ms-|1.9.0
remote-wsl|ms-|0.50.0
azure-account|ms-|0.9.3
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2902
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.0.1
vscode-yaml|red|0.11.1
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0

</details>

**Comment by RMacfarlane** [comment]
@VasuInukollu I assume you mean you see an error about writing to the keychain, can you please paste the error text? Although the error text says "keychain", it writes to the Windows Credential Manager on windows

**Comment by VasuInukollu** [comment]
The new build seems to have resolved the problem.
