### ISSUE TITLE
Preserve per-window environment variables between workspace changes

### ISSUE THREAD

**Issue by vkk-steigend** [microsoft/vscode#108571]
- VSCode Version: 1.44.2
- Local OS Version: Ubuntu 18.04.4 LTS
- Remote OS Version: Debian Buster (10.3)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open a terminal in host machine
2. Start an ssh-agent by `eval $(ssh-agent -s)`
3. Add a key (key1) using `ssh-add ~/.ssh/id_ed25519_key1`
4. Open VS Code from the same terminal `code .`
5. Run `ssh-add -l` in VS Code terminal (shows the identity of key1) (:+1: )
6. Open folder in Remote Container
7. Run `ssh-add -l` in VS Code terminal (shows the identity of key1) (:+1: )
6. Open another terminal in host machine
7. Start a new ssh-agent by `eval $(ssh-agent -s)`
8. Add a key (key2) using `ssh-add ~/.ssh/id_ed25519_key2`
9. Open VS Code from the same terminal `code .`
10. Run `ssh-add -l` in VS Code terminal (shows the identity of key2) (:+1: )
11. Open folder in Remote Container
12. Run `ssh-add -l` in VS Code terminal (shows the identity of key1) (:-1: )

VS Code somehow only forwards the first ssh-agent to remote container eventhough it has the correct ssh-agent forwarded locally. Am I missing any configuration? Can this be fixed with any settings in devcontainer.json?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by bpasero** [comment]
Slightly related: https://github.com/microsoft/vscode/issues/15452

**Comment by bpasero** [comment]
Logic is here and I hope it does not break anything. Idea is that we preserve the windows `userEnv` if it was started from a CLI and the new config is not:

https://github.com/microsoft/vscode/commit/ff1887be3e07b5d16760376106d6234cad5356a6#diff-ce055d098d503f8b3309d514fd97e4a84da4515e21ee102618bbb2097087ab2bR687-R689
