### ISSUE TITLE
Prettier auto-save failed

### ISSUE THREAD

**Issue by ayako02** [microsoft/vscode#108520]
Issue Type: <b>Bug</b>

The prettier auto save mode is turned on but unable to fix code format on save after the latest vscode update. 
1. With eslint installed.
2. type a incorrect code format
3. ctrl + s to save

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id 0155e6db-d9e7-47bc-9b22-e030fc37a878|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.10
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
auto-rename-tag|for|0.1.5
markdown-preview-enhanced|shd|0.5.13
doki-theme|unt|6.0.0
markdown-all-in-one|yzh|3.3.0

(6 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Does information from the linked duplicate help?

**Comment by ayako02** [comment]
> Does information from the linked duplicate help?

It helpes!
