### ISSUE TITLE
vscode shows README.md from marketplace instead of installed vsix if extension version is same

### ISSUE THREAD

**Issue by pkruk2** [microsoft/vscode#108584]
- VSCode Version: 1.50.0
- OS Version: Windows 10

Steps to Reproduce:

1. Have extension on marketplace with version x.y.z
2. Create local vsix file with same x.y.z version but different README.md content
3. Install local vsix file (Extensions>Install from VSIX...)
4. Show extension Details in vscode (which shows README.md)

Expected: README.md from installed vsix is displayed
Actual: README.md from marketplace is displayed

This only happens when both local and marketplace extensions have the same version, e.g. 1.2.3
If local version is different, for example 1.2.4, the README.md from local version is displayed.
But when working on extension and installing local builds you may have the same version. Would be nice if simply the actually installed README.md was shown. It is confusing.
Also in case a beta/testing version is sent to user (by mail/outside of marketplace), you need to make sure the version is different than version on marketplace, otherwise vscode will display wrong README.

**Comment by sandy081** [comment]
To verify, 
- install an extension and open the extensions folder.
- Updated read me and make sure local read me is shown unless there is a latest version in Marketplace.
