### ISSUE TITLE
VSCode segmentation fault on CentOS8 non-4k pagesize aarch64(arm64)

### ISSUE THREAD

**Issue by itas109** [microsoft/vscode#108509]
- VSCode Version: September 2020 (version 1.50)
- OS Version: CentOS 8.2 aarch64 pagesize 64k

Steps to Reproduce:

```
download code-stable-arm64-1602050866.tar.gz
tar zxvf code-stable-arm64-1602050866.tar.gz
cd VSCode-linux-arm64
./code 
segmentation fault
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by itas109** [comment]
I think it is linux kernel's PAGESIZE problem ( chromium ).

PAGESIZE = 64k on cetos 8 aarch64
but,
PAGESIZE = 4K on other linux(such debian aarch64)
PAGESIZE = 4K on centos 8 x86_64

```
$ getconf PAGESIZE
65535
```

**Comment by itas109** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Segmentation Fault on current dev channel insider Windows build when using WSL 2 (#104708)](https://www.github.com/microsoft/vscode/issues/104708)

not the same problem

**Comment by deepak1556** [comment]
Can you repro the crash when you run https://github.com/electron/electron/releases/download/v10.1.5/electron-v10.1.5-linux-arm64.zip , in that case this should be reported to https://github.com/electron/electron/issues

**Comment by itas109** [comment]
electron v10.1.5 has the same problem.
I had reported to https://github.com/electron/electron/issues/25387

**Comment by deepak1556** [comment]
Thanks!
