### ISSUE TITLE
Cursor in terminal prevents reading words correctly.

### ISSUE THREAD

**Issue by Jalalx** [Microsoft/vscode#10858]
VS Code is just amazing! It's fast and easy. The only problem I found is that cursor there, If you call it a "Problem"! It's a bit annoying :confounded: 

I couldn't move it using mouse or keyboard arrows. I think it should be placed at end of line, because in the begining, it might prevent reading some words correctly. :confused: 

- VSCode Version: 1.4
- OS Version: Windows 10 x64bit

Steps to Reproduce:

1. Open Terminal
2. Git clone
3. You can see it there!

![VS Code Terminal Editor Cursor](https://cloud.githubusercontent.com/assets/1018975/17907523/94ae90e4-6991-11e6-81c1-fa8e1f2eba17.jpg)

If you think it's too trivial to work on it, I will fix it. :smiley:

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
