### ISSUE TITLE
"Editor: Accept Suggestion On Enter" should default to Off

### ISSUE THREAD

**Issue by ell1e** [microsoft/vscode#108536]
"Editor: Accept Suggestion On Enter" should default to Off in a new install of VS Code. At worst, in languages like Python, Lua, and others with no terminating character, it is almost impossible that return -> accept suggestion won't strongly interfere with legitimate typing. At best, it still messes with typing when inserting line breaks e.g. into a lengthier `if` condition in C when the user didn't intend to interact with the auto suggestion popup. And the default behavior shouldn't be to have the potential to completely mess up what I am typing when I am just writing down a regular code line minding my own business. Therefore, unless the user opts in to this, I think this is just a bad default value for this setting.

A good workaround to make people realize how to use the popup might be to instead add an additional small annotation "Press Tab to accept suggestion" inside the pop up below the listed suggestions, instead of double-hogging a vital key like "Return" by default. (Assuming that beginner friendliness was the misguided motivation for this default)

- VSCode Version: 1.50.0
- OS Version: Fedora 32 x64

Steps to Reproduce:

1. Type any code
2. Notice how when inserting line breaks not following an obvious statement end (like `;` in C/C++) the auto suggestion popup likes to mess with what you're typing even when you didn't interact with it at all. While it is possible to avoid this when paying extra attention, how well this works depends on the language and it's definitely not a great initial experience for someone freshly coming to VS Code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Sorry, but we aren't fixing defaults for such highly visible and frequently used features. Changing the default for your setup is easy and with settings sync you have this behaviour everywhere

**Comment by ell1e** [comment]
@jrieken why not? While I can understand you don't do so lightly, given how highly disruptive this default is (and nonsensical for languages without a line terminator) I suggest to at least have some discussion about whether it really makes sense for the large majority of users. If you're worried about alienating existing users, surely there is a way that existing installations could be grandfathered to keep the old default via some settings revision marker.
