### ISSUE TITLE
Highlight the parts automatically in the Outline Sidebar as you click through code

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#108570]
Highlight the parts automatically in the Outline Sidebar as you click through code.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/6391776/95832092-24b46b00-0d3a-11eb-8c06-7dd263928fee.png">

As in image above. Since I clicked on `render` in the code. It should highlight `render` in the sidebar Outline view. Otherwise the Outline view is not as useful.

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/96002284-87595400-0e6b-11eb-8cc7-e01fe929b94e.png)

There is a "Follow cursor" setting in the `...` menu

**Comment by nikitavoloboev** [comment]
Very cool. Thanks.
