### ISSUE TITLE
Reduce host service dependencies

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108522]
Steps to Reproduce:

1. run `yarn web`
2. => 🐛 workbench does not open

From: https://github.com/microsoft/vscode/commit/03912754be58651eb8e73a833a66da0fab731338

Workaround: https://github.com/microsoft/vscode/commit/57ea89683c760fc9929eca67867bbd5d52652e4f

**Comment by sandy081** [comment]
@bpasero I think `IWorkbenchExtensionEnablementService` depending on `IHostService` is logically correct. But, in web `IHostService` is depending on other workbench services like `IEditorService` -> `IEditorGroupsService` -> `IThemeService -> ...` and causing cycle. Not having consistent base services in desktop and web is causing confusion and debt and it might add up as we evolve. I think fixing in `IWorkbenchExtensionEnablementService` is just a patch.

To unblock for now, I removed the dependency on `IHostService` and used `ReloadWindowAction`. 

Assigning back to you for fixing this in `IHostService`.
