### ISSUE TITLE
make it easy vscode its wasting my time so when i learn something

### ISSUE THREAD

**Issue by loverofmicrosoft** [microsoft/vscode#108585]
Issue Type: <b>Feature Request</b>

can you please make it easy when i install c/c++ but my programme not working it said there is gcc or clang problem i don't understand can you please set automatic install all things for programmers because we waste time to fix problem to downloading and set path not only c in python , java etc please fix it i want to download vscode and just start coding and my programme run please make it simple vscode is complicated only those people use who is developer or well know about it but what about those who just starting coding but they don't know about it please make it easy because i waste lot's of time please

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 17.7.0

**Comment by bamurtaugh** [comment]
Hey @loverofmicrosoft, thanks for the feedback. I think we have a couple of tools that could really help in this situation.

Have you had a chance to take a look at our [Java or Python coding packs](https://code.visualstudio.com/learntocode)? The Coding Pack for Java includes VS Code, the Java Development Kit (JDK), and essential Java extensions. The Coding Pack can be used as a clean installation, or to update or repair an existing development environment. The Coding Pack for Python sets up VS Code, your Python environment and libraries, and other really helpful extensions for starting out, like LiveShare.

As another alternative, we have the [Remote - Containers extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers), which also greatly reduces the need to set up any downloads or dependencies. You could choose from a list of preconfigured dev containers, such as a Python 3 or C++ dev container, and all of the runtimes and libraries will already be set up for you - you don't have to download anything on your local machine besides Docker. We have a [getting started tutorial here](https://code.visualstudio.com/docs/remote/containers-tutorial).

Does it sound like any of these solutions might help?

**Comment by bamurtaugh** [comment]
Hey @loverofmicrosoft, following up here - did it sound like any of the above might help?

**Comment by bamurtaugh** [comment]
Closing for now with the guidance above in mind - please feel free to let us know if you have any other questions or feedback, and I'd be happy to reopen or discuss further. Thank you!
