### ISSUE TITLE
Terminal flickers when clicking on paths to open them

### ISSUE THREAD

**Issue by svillar** [microsoft/vscode#108599]
Issue Type: <b>Bug</b>

Preconditions:
* Terminal should show a clickable path. One example could be the output generated by `git status`

Steps to reproduce:
1.  Alt+Click on the path to open it

Actual behaviour:
The terminal starts flicking like mad just after clicking on the url.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 5.8.0-2-amd64

**Comment by Tyriar** [comment]
Are you able to capture this flicking like mad via https://gifcap.dev/?

**Comment by svillar** [comment]
That service didn't work, I guess it's because of wayland. Anyway I recorded a video with my camera and uploaded a reduced resolution version which showcases the issue.
![output2](https://user-images.githubusercontent.com/1826122/98351563-27466f80-201d-11eb-92a0-c9140326be93.gif)

**Comment by Tyriar** [comment]
Strange, this looks like it might be related to the GPU. Can you close all windows and try launch with `code --disable-gpu` and see if it still happens?

**Comment by svillar** [comment]
> Strange, this looks like it might be related to the GPU. Can you close all windows and try launch with `code --disable-gpu` and see if it still happens?

yeah same outcome
