### ISSUE TITLE
(arm64) Install error - ./code

### ISSUE THREAD

**Issue by codebankco** [microsoft/vscode#108526]
I'm having issues installing vscode on my arm64 build of linux on a rpi4.  I get the error: 
`./code: cannot execute binary file: Exec format error`
Here are the steps to reproduce:
`download code-stable-arm64-1602050866.tar.gz`

`tar zxvf code-stable-arm64-1602050866.tar.gz`

`cd VSCode-linux-arm64`

`./code `
Error is ./code: cannot execute binary file: Exec format error

Thanks!

**Comment by codebankco** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [VSCode segmentation fault on CentOS8 non-4k pagesize aarch64(arm64) (#108509)](https://www.github.com/microsoft/vscode/issues/108509)

Different issue.

**Comment by joaomoreno** [comment]
What does `file code` return? What about `uname -a`?
