### ISSUE TITLE
Open project

### ISSUE THREAD

**Issue by nico123321** [microsoft/vscode#108568]
Issue Type: <b>Feature Request</b>

How i open my project on cmd? the codes in terminal not work for me

**Comment by engrmamun66** [comment]
Open cmd in your project location.
then type **code .**

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
