### ISSUE TITLE
[FileSearch(Ctrl+P)] The searched files are from the system root dir instead of the relative WS path (please read the description)

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode#108535]
- VSCode Version: 1.51.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open a multi-root workspace
2. Do a quick file search (Ctrl+P)

a) As seen in the first screenshot, the matching file results are all of the path froom the system root
That is, they are from `D:\Playground\Nodejs\something\package.json` instead of `Nodejs\something\package.json`

![image](https://user-images.githubusercontent.com/15051871/95762063-d4ea8b00-0cca-11eb-96bf-f39a224ad4b3.png)

b) As seen in this second screenshot, because of the above reason, the opened file is not opened and highlighted in the "Explorer" tree

![image](https://user-images.githubusercontent.com/15051871/95762219-08c5b080-0ccb-11eb-9584-aadd2bc071e3.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Do you know whether this is a new issue, did it work before? 

Does it happen in a window with only a folder open?

Can you share your workspace config? (from `Open Workspace Configuration File`)

**Comment by roblourens** [comment]
Oh, I can repro this

**Comment by stagefright5** [comment]
> Do you know whether this is a new issue, did it work before?

It is new in the version mentioned above

> Does it happen in a window with only a folder open?

No

Also, the relative path-ed files will start appearing in the quick open search panel if once that file is opened from the vs code in-built file explorer.

**Comment by roblourens** [comment]
It seems like there is an issue with the drive letter case here, from search we end up with a URI with a lowercase drive letter, and from the explorer, we get one with an uppercase drive letter. What changed here? @isidorn @bpasero

**Comment by isidorn** [comment]
@roblourens the only change we did this milestone in the explorer which I think is not related to this is that we now use the `URIIdentityService` to compare URI's for equality. Instead of the previous `uri.toString()` comparison.

**Comment by bpasero** [comment]
Nothing I can recall, but agree that ideally search uses the same URI structure as the workspace roots.

**Comment by roblourens** [comment]
For URIs from the explorer which work correctly, `resource.toString()` shows a lowercased drive letter, but `resource.path` has an uppercase drive letter. `getWorkspaceFolder` apparently wants an uppercased drive letter.

**Comment by roblourens** [comment]
Well, if the workspace folder that we are told to search in has an uppercased drive letter then I guess I just need to make sure the results match that.

**Comment by roblourens** [comment]
Here's what I see in 1.49 where this works

- The folder query for search has a path with an uppercased drive letter
- The search result is returned with a lowercase drive letter
  - Internally the search service uses fsPath at some point, which normalizes drive letters to lowercase, and recreates the result URI from that and the relative path of the result
- Apparently we are still able to look up the workspace folder with this mismatch

In 1.51 where it's broken

- The casings going into and coming out of search are exactly the same
- But now we are not able to look up the workspace folder

I can probably get rid of the mismatch in search, but all I'm doing is `uri.fsPath` then `URI.file` from that fsPath, and I end up with an incompatible URI, and that's weird to me, is that wrong or is that expected now? @jrieken 

I'm also looking at some changes in the TernarySearchTree and trying to bisect this.

**Comment by jrieken** [comment]
> but all I'm doing is uri.fsPath then URI.file from that fsPath, and I end up with an incompatible URI, and that's weird to me, is that wrong or is that expected now?

That is unhappy but expected since the casing doesn't actually matter. Internally we have [`originalFSPath`](https://github.com/microsoft/vscode/blob/6e022766d135689a6a5f92a4f3d9ebf97b238dd0/src/vs/base/common/resources.ts#L16) which you might wanna use. Tho, using originalFSPath should _not_ be the new thing, then it is better to use the uri identity service. 

I did push a follow-up change (https://github.com/microsoft/vscode/commit/70a8fc5b231c90629a9b2d917f017b4913821f1f) to fix a similar issue in the extension host and maybe the a similar change is required in the main side (`Workspace`) or (maybe better) the use of the uri ident service

**Comment by bpasero** [comment]
@jrieken shouldn't we use the file service information in the extension host to compare workspace folder URIs? in theory an extension could register a FSP that is case-sensitive and open that as folder in a multi root setup, no?

**Comment by jrieken** [comment]
Yeah, likely. My change only removed the generally untidiness from the search tree into same concrete locations. It didn't attempt to clean up

**Comment by roblourens** [comment]
So should the search service just run all URIs through `asCanonicalUri`?

**Comment by isidorn** [comment]
@roblourens fyi we are reverting the `TernarySearchTree` behavior for vscode stable 
PR here https://github.com/microsoft/vscode/pull/110247

**Comment by stagefright5** [comment]
@roblourens @isidorn Do you think the issue #110367 has anything to do with this?

**Comment by roblourens** [comment]
Yes. This issue is now fixed in Insiders too.

**Comment by roblourens** [comment]
Verification steps

- Use vscode on windows
- Open a multiroot workspace
- Open quickopen
- You should see relative paths, not absolute paths
