### ISSUE TITLE
IndexDB file system provider needs a good test suite

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108566]
Our IndexDB based file system provider is very important for web but currently seems to  lack a good test suite. I suggest to look at `src/vs/platform/files/test/electron-browser/diskFileService.test.ts` and see if some of the tests can run against IndexDB to make sure we have good coverage.

**Comment by JacksonKearl** [comment]
Looked into this a bit, as far as I can tell we don't have any serverless tests at all yet, is this correct?

**Comment by bpasero** [comment]
@JacksonKearl not sure I understand, we run our unit tests in both [electron](https://github.com/microsoft/vscode/blob/87847325a66f098621f6650a16d665c9cd07f15a/test/unit/electron/index.js#L6-L6) and [browsers](https://github.com/microsoft/vscode/blob/41b661eb3d135b14d7f66d6342b64ca3bcdee36d/test/unit/browser/index.js#L1-L1), so you should get good coverage if you simply write unit tests. I do not think you need any server for these tests.

**Comment by JacksonKearl** [comment]
Oh I see. I was looking at the API tests, which I think only run on serverfull browser and desktop.
