### ISSUE TITLE
Git view pick repo with a dropdown control 

### ISSUE THREAD

**Issue by LucaGabi** [microsoft/vscode#108519]
Pick repo with a dropdown (preferable editable) control in git view instead of enumerating top-bottom.

**Comment by joaomoreno** [comment]
Can you elaborate?

**Comment by LucaGabi** [comment]
Yes.

Current:

![image](https://user-images.githubusercontent.com/37976898/96030185-59244600-0e64-11eb-9906-98fd42a2eeca.png)

Request is: provide a filterable drop-down to choose   between repos.

Also a better UX I'd consider keeping the commit message box fixed at the top, currently I think it scrolls out with files.

**Comment by joaomoreno** [comment]
Can you right click the `SOURCE CONTROL` title and display the `Source Control Repositories` view? Does that help?

**Comment by LucaGabi** [comment]
Yes, can be an option. I'd still think that keeping the commit message box fixed at the top (now it scrolls with the file changes) it's a good idea.

**Comment by joaomoreno** [comment]
Sorry, that was a forced design decision to allow showing multiple SCM repos in a single view. Hope you get a better workflow now!
