### ISSUE TITLE
Built-in Markdown preview is often fluttering

### ISSUE THREAD

**Issue by dull-bird** [microsoft/vscode#108582]
- VSCode Version: 1.5.1-insider
- OS Version: Windows 10 2004

I found that the scrolling in VSC built-in Markdown preview is often fluttering if I set:
-  "markdown.preview.scrollEditorWithPreview": true
-  "markdown.preview.scrollPreviewWithEditor": true 

If I only set the **first one** to be true, which means that the editor is "listening" to the preview, then the scrolling is fluent.
The problem is more obvious if I also set
- "editor.smoothScrolling": true 

To reproduce this, you can use a long markdown file, and adjust the flags in setting.

Here is my screen shot with both “scrollEditorWithPreview” and "scrollPreviewWithEditor" being ture:

![2](https://user-images.githubusercontent.com/8479707/95850596-ab416a80-0d83-11eb-9aab-96f7b9926511.gif)

We can find some fluttering in the preview.

And here is my screen shot with only “scrollEditorWithPreview” being ture:
![1](https://user-images.githubusercontent.com/8479707/95851055-4d615280-0d84-11eb-95c5-5874fa4f2b22.gif)

This is much more fluent.

In both screen shots, I simply scroll up or down the mouse in *one direction* and I try to make the comparison fair.

I guess this problem is due to the mutual influence of both the editor and the preview, thus maybe it can be solved if VSC can disable one of the flag based on the position of the cursor.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
Can you share the markdown source that shows this issue?

**Comment by dull-bird** [comment]
You can use any long .md file.

Here is my example:  
https://raw.githubusercontent.com/mxstbr/markdown-test-file/master/TEST.md

**Comment by mjbvz** [comment]
Seems to have been mostly resolved by #111094

If you still see this, please share a file and steps to reproduce the issue

**Comment by heartacker** [comment]
Is any body notice that if the markdown file have pics. the vscode page-screen will shake when typing
![vscode_markdown](https://user-images.githubusercontent.com/1876302/107028827-0c84c200-67e9-11eb-85b0-721959e4a015.gif)

**Comment by isaacdchan** [comment]
> Is any body notice that if the markdown file have pics. the vscode page-screen will shake when typing
> ![vscode_markdown](https://user-images.githubusercontent.com/1876302/107028827-0c84c200-67e9-11eb-85b0-721959e4a015.gif)

I have shaking though my markdown doesn't have pictures. It only happens when I am typing at the bottom of the file though (which I normally am).
