### ISSUE TITLE
Provide official AppImage builds for Linux

### ISSUE THREAD

**Issue by probonopd** [microsoft/vscode#10857]
Please provide Visual Studio Code in the [AppImage](http://appimage.org) format for Linux. This would allow users to
- Test Visual Studio Code without having to install it
- Use Visual Studio Code on machines where they have no root rights
- Run Visual Studio Code on Linux distributions for which no native package is provided

AppImage is a bundling format for Linux that lets users download one single file, set the executable bit and run the application (here: Visual Studio Code). Unlike [other](https://github.com/Microsoft/vscode/issues/7112) [options](https://github.com/Microsoft/vscode/issues/5458), AppImage is entirely distribution-agnostic and no special runtime infrastructure is needed on the target system(s). This means that the user can run the application on almost any recent Linux distribution.

It is easy to convert the official deb builds to AppImages using [this script](https://github.com/probonopd/AppImages/blob/master/recipes/vscode/Recipe).

**Comment by joaomoreno** [comment]
cc @Microsoft/vscode 

@probonopd This is incredibly cool. I've just watched your [presentation on Youtube](https://www.youtube.com/watch?v=mVVP77jC8Fc) and everything resonated with me. I admire the work you're doing there, keep it up!

@Tyriar Given the huge friction we're seeing with auto-updates on the deb and rpm packages and the crazy benefits this would give us in terms of packaging and incremental updates, I'd be willing to push towards making AppImage our default and recommended distribution method for VS Code alongside a preventive ZIP archive. After a proper investigation of course.

**Comment by probonopd** [comment]
Thanks @joaomoreno for your kind words; your [PowerShell](https://github.com/PowerShell/PowerShell) colleagues are currently also [reviewing](https://github.com/PowerShell/PowerShell/pull/2027) it.

**Comment by probonopd** [comment]
By the way, I don't know how applicable this is here, but [electron-builder](https://github.com/electron-userland/electron-builder) has support for building AppImages for Electron applications too.

**Comment by probonopd** [comment]
Here are some example AppImages of Electron-based apps that you can download and try:
* https://bintray.com/probono/AppImages/Atom/_latestVersion#files
* https://bintray.com/probono/AppImages/Brackets/_latestVersion#files
I could upload one of Visual Studio Code but am uncertain whether the license permits it.

**Comment by joaomoreno** [comment]
Go ahead, we are MIT.

**Comment by probonopd** [comment]
Here is my experimental Visual Studio Code AppImage generated by the script above on Travis CI ([build log](https://travis-ci.org/probonopd/AppImages/builds/154680774)):

https://bintray.com/probono/AppImages/Code#files

To download and run, simply:

```
VSCODE="Code-1.4.0-x86_64.AppImage"
wget -c "https://bintray.com/probono/AppImages/download_file?file_path=$VSCODE" -O "$VSCODE"
chmod a+x "$VSCODE"
./"$VSCODE"
```

Since the AppImage packaging runs on Travis CI this can be integrated into CI workflows easily. There still some minor glitches that could be easily resolved, e.g., the name is "Code" rather than "Visual Studio Code", desktop integration (optional installtion into the start menu) is not there yet, etc. and it is expected that some fine-tuning might still be needed, ideally with the help from the upstream team.

Known to run on
* Chromixium-1.5-amd64.iso
* debian-live-8.0.0-amd64-xfce-desktop+nonfree.iso
* debian-live-8.4.0-amd64-gnome-desktop.iso
* CentOS-7.0-1406-x86_64-GnomeLive.iso
* CentOS-7-x86_64-LiveGNOME-1511.iso
* elementary_OS_0.3_freya_amd64.iso
* Fedora-Live-Workstation-x86_64-22-3.iso
* Fedora-Live-Workstation-x86_64-23-10.iso
* kali-linux-2016.1-amd64.iso
* kubuntu-14.04.4-desktop-amd64.iso
* kubuntu-15.04-desktop-amd64.iso
* kubuntu-16.04-desktop-amd64.iso
* neon-useredition-20160609-0826-amd64.iso
* SL-72-x86_64-2016-02-03-LiveDVDgnome.iso
* ubuntu-14.04.1-desktop-amd64.iso
* ubuntu-16.04-desktop-amd64.iso
* ubuntu-gnome-16.04-desktop-amd64.iso
* ubuntu-mate-16.04-desktop-amd64.iso
* xubuntu-16.04-desktop-amd64.iso

Does not run on very outdated distributions (to make this work, vscode would need to be compiled on an older build system):
* CentOS-6.7-x86_64-LiveCD.iso
* ubuntu-12.04.5-desktop-amd64.iso
* ubuntu-12.10-desktop-amd64.iso

**Comment by joaomoreno** [comment]
It just works, so cool! Thanks for the sample. We will definitely consider this.

**Comment by probonopd** [comment]
Renamed and added desktop integration (optional installation into the start menu). Download links updated above.

**Comment by probonopd** [comment]
@joaomoreno are the binaries at https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable generated by a Travis CI run, and if so, where is the respective code? I could try to hook in there and send a PR which also builds an AppImage using the binaries generated anyway for the deb.

**Comment by joaomoreno** [comment]
@probonopd They are generated from our internal build. Building and distributing VS Code is not open source, so you'll have to leave picking this up to us for now.

**Comment by GitRASQ** [comment]
Arch Linux user here. There doesn't appear to be a package for my system. Collecting dependencies and compiling is a pain, I'd love to have an appimage. The one linked above seems to no longer exist.

**Comment by Tyriar** [comment]
@GitRASQ the community has an AUR package which we recommend. https://aur.archlinux.org/packages/visual-studio-code/

**Comment by fusion809** [comment]
I have provided a code-oss Debian package (https://github.com/fusion809/code-oss/releases/tag/debian1.6.1) and built an AppImage from it.

**Comment by probonopd** [comment]
@fusion809 thanks for your effort but please be aware that only Microsoft can build an official AppImage with the official branding as far as I understand.

**Comment by fusion809** [comment]
Official branding? What's meant by that. I built an OSS build of code-oss using, the build system that VSCode's official developers put in place.

**Comment by Tyriar** [comment]
I don't think [this line](https://github.com/fusion809/code-oss/blob/559d106a875a4851a02616ecbb0a989c82fb110d/product_json.patch#L8) for example is allowed since the "Visual Studio" branding can only be used in official builds by Microsoft. That's the main reason for the whole "Code (OSS)" vs "VS Code" thing. Same story with the logo.

**Comment by fusion809** [comment]
I just use the code-oss as a place to upload the Debian package, it's does not contain the sources used to build the Debian package.

**Comment by Tyriar** [comment]
"code-oss" is fine, it's branding it as Visual Studio and using the logo that could potentially be an issue.

**Comment by Tyriar** [comment]
Some more info on the topic from one of our PMs https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005

**Comment by fusion809** [comment]
Well if that's the only problems with my code-oss Debian package I've rebuilt it without any of the MIT license-breakers. Then I build an AppImage and it's working fine. So @probonopd I suspect all is good now and you can provide my AppImage at Bintray.

**Comment by probonopd** [comment]
@Tyriar any chance you would provide an official AppImage?

**Comment by Tyriar** [comment]
We'll be getting signed apt/yum repos soon, polishing that experience is the priority on this front for now.

**Comment by probonopd** [comment]
Would you consider merging a PR if I sent one that would generate an AppImage for each continuous build on Travis CI?

**Comment by Tyriar** [comment]
Not just yet, as mentioned before apt and yum repos are just on the horizon which is the focus for now. I'd prefer to wait before embracing one of the newer package types as adding support for another one will increase our maintenance burden.

**Comment by Moilleadoir** [comment]
Is that horizon any closer after a month?

**Comment by Tyriar** [comment]
@Moilleadoir It was actually completed a week or so ago, check out https://github.com/Microsoft/vscode/issues/229#issuecomment-280943455 and https://github.com/Microsoft/vscode/issues/2973#issuecomment-280575841

**Comment by probonopd** [comment]
@Tyriar is the subject of this ticket still being considered? [PowerShell](https://github.com/PowerShell/PowerShell/) just has started to generate  an AppImage for each continuous build on Travis CI.

**Comment by Moilleadoir** [comment]
@Tyriar Thank you. Read somewhere on code.visualstudio.com that it wasn’t supported…of course, I can’t find it now.

**Comment by Tyriar** [comment]
@probonopd yes. We want to see how the repositories do right now though.

@Moilleadoir yeah it's being included in the upcoming release notes, the documentation will need to be updated before the release.

**Comment by karai17** [comment]
Any further advancements on this issue? I'd love to see AppImages for more of the tools I use.

**Comment by stavpup** [comment]
A snap is here, but still no Appimage. 
http://news.softpedia.com/news/you-can-now-install-microsoft-s-visual-studio-code-ide-as-a-snap-on-ubuntu-linux-515882.shtml

**Comment by probonopd** [comment]
Happy to support this project in making an official AppImage. Microsoft is already using AppImage for PowerShell btw.

**Comment by Serkan-devel** [comment]
Any updates on an official appimage?

**Comment by Tyriar** [comment]
We don't plan on supporting AppImage any time soon. We are investing some effort into snap packages though. See https://github.com/Microsoft/vscode/issues/5458 for updates on that.

**Comment by probonopd** [comment]
@vscodebot owners: Please reconsider!

> We look at the number of votes the issue has received

Please look closely:

![stars](https://user-images.githubusercontent.com/2480569/34298773-b398df98-e71f-11e7-9d9c-058ddd6a14a4.png)

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages. __Microsoft provides PowerShell as an AppImage, too.__

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by Tyriar** [comment]
@probonopd our team is quite small and I simply cannot manage more than what we are currently doing. I'll reopen as this could happen eventually, but realistically it's not going to be considered for another 12-24 months.

**Comment by gengjiawen** [comment]
With AppImage we can do auto updater like macOS and Windows. Update VS Code for linux now is very cumbersome, even with the PM like apt.

**Comment by ghisvail** [comment]
> Update VS Code for linux now is very cumbersome, even with the PM like apt.

Do you mean typing `apt update && apt upgrade` is that difficult? Come on.

It's no secret Microsoft is collaborating with Canonical to provide VSCode for all distros via snap packages. I suppose support for AppImage or Flatpak will be up to their respective communities at this point.

**Comment by gengjiawen** [comment]
If you want to use apt, you have to execute [lots of script](https://code.visualstudio.com/docs/setup/linux) before `sudo apt-get install code`. When you update you ubuntu to higher version. Guess what to be execute again ?

**Comment by ghisvail** [comment]
> If you want to use apt, you have to execute lots of script before `sudo apt-get install code`.

The link shows multiple *alternatives*, each of them are far from being "lots of script". In fact, installing the `.deb` via your graphical package manager (the recommended option btw) is enough and 1-click away. 

I'd argue this process is actually simpler than AppImage which needs an additional `chmod a+x` step. Don't get me wrong, I get the value of AppImage, snaps and flatpak (I use the latter personally). However, I don't believe spinning the narrative around the amount of "scripting" required for integration with native package manager is gonna get you much sympathy.

**Comment by gengjiawen** [comment]
We clearly have different understanding on easy and time.

**Comment by Tyriar** [comment]
@gengjiawen FYI this is what I use to update Insiders daily at the moment which is fairly convenient:

```
alias up='sudo apt update && sudo apt install code-insiders'
```

In the morning on a weekday or when I see the update available badge in the gear menu: ctrl+\`, `up` and put in password

**Comment by RoyiAvital** [comment]
I would be great to have VS Code in AppImage format.
They have some potential use cases which are not covered by FlatPak & Snap.

Think of working on VS Code from USB on any system with the same configuration and set of extensions (Just utilize the `.home` and `.configure` features of AppImage).

**Comment by Serkan-devel** [comment]
Has someone commented? Why did I get a notification for this thread?

**Comment by thenktor** [comment]
Slackware user here: I'd like to have an AppImage, too. AppImages just work without hassle.

**Comment by rzr** [comment]
Maybe not related by docker images could help eventually too
specially if debian is able to rebuild and distribute deb package:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898259

**Comment by probonopd** [comment]
What would be needed for the team to reconsider providing an official AppImage build?

![vscode](https://user-images.githubusercontent.com/2480569/50373989-c2c3c800-05de-11e9-9c79-1b94a3c7bb69.png)

In the meantime, you can easily make your own using this recipe like this on a Debian/Ubuntu system:

```
wget -c "https://github.com/AppImage/pkg2appimage/raw/master/pkg2appimage"
bash -ex pkg2appimage VSCode
```

(Debian/Ubuntu system is needed for the conversion from deb to AppImage because the tooling uses apt and dpkg, but the resulting AppImage should be able to run on other systems, too.)

Here is the recipe:
https://github.com/AppImage/pkg2appimage/blob/master/recipes/VSCode.yml

**Comment by leandrw** [comment]
> What would be needed for the team to reconsider providing an official AppImage build? @Tyriar
> 
> ![vscode](https://user-images.githubusercontent.com/2480569/50373989-c2c3c800-05de-11e9-9c79-1b94a3c7bb69.png)
> 
> In the meantime, you can easily make your own using this recipe like this on a Debian/Ubuntu system:
> 
> ```
> wget -c "https://github.com/AppImage/pkg2appimage/raw/master/pkg2appimage"
> bash -ex pkg2appimage VSCode
> ```
> (Debian/Ubuntu system is needed for the conversion from deb to AppImage because the tooling uses apt and dpkg, but the resulting AppImage should be able to run on other systems, too.)
> 
> Here is the recipe:
> https://github.com/AppImage/pkg2appimage/blob/master/recipes/VSCode.yml

I tried this recipe in KDE Neon with **code-insiders_1.33.0-1553235446_amd64.deb** package and got this output:
```
eval: line 108: unexpected EOF while looking for matching ``'
```

**Comment by probonopd** [comment]
The following works for me on `xubuntu-18.04-desktop-amd64.iso`:

```
wget https://raw.githubusercontent.com/AppImage/pkg2appimage/master/pkg2appimage
bash -ex ./pkg2appimage VSCode
```

What do you mean by

> with code-insiders_1.33.0-1553235446_amd64.deb

? 

The recipe currently gets 1.32.3-1552606978.

**Comment by leandrw** [comment]
> The following works for me on `xubuntu-18.04-desktop-amd64.iso`:
> 
> ```
> wget https://raw.githubusercontent.com/AppImage/pkg2appimage/master/pkg2appimage
> bash -ex ./pkg2appimage VSCode
> ```
> What do you mean by
> 
> > with code-insiders_1.33.0-1553235446_amd64.deb
> 
> ?
> 
> The recipe currently gets 1.32.3-1552606978.

I didn't get it.
The script does not convert debian package to appImage?
I'm running it against Code Insiders build.

**Comment by probonopd** [comment]
`pkg2appimage` uses https://github.com/AppImage/pkg2appimage/blob/master/recipes/VSCode.yml to produce a VSCode AppImage, It downloads the application from https://github.com/AppImage/pkg2appimage/blob/e42f51314b02364497ac65286068c7f71d7779ea/recipes/VSCode.yml#L19.

**Comment by leandrw** [comment]
> `pkg2appimage` uses https://github.com/AppImage/pkg2appimage/blob/master/recipes/VSCode.yml to produce a VSCode AppImage, It downloads the application from https://github.com/AppImage/pkg2appimage/blob/e42f51314b02364497ac65286068c7f71d7779ea/recipes/VSCode.yml#L19.

I think I get it. This script targets to stable build, not insiders.

**Comment by probonopd** [comment]
Yes, but you can make a variation of it that downloads and uses the insiders build.

**Comment by ergonomicus** [comment]
@probonopd Any idea why Git doesn't work in AppImage? I have tried setting a path, but no luck.

**Comment by probonopd** [comment]
Please define "does not work". Do you get an error message?

**Comment by ergonomicus** [comment]
Well, that's on my work computer, but I think the error message was something like "Git is not installed on your system". I have tried '/usr/bin/git', just 'git' and what not, but I get the same error message.

**Comment by probonopd** [comment]
Is git installed on your system?

**Comment by ergonomicus** [comment]
Yes, working all the time in it. And 'which git' gives me '/usr/bin/git'.

**Comment by chadalen** [comment]
What is the state of this ticket?

I would also like to see an official build for AppImage.

The reasons for this is because...
Flatpak: Terminal doesn't work (due to sandboxing)
Snap: Startup is painfully slow
AppImage just works and doesn't have either one of these problems..

**Comment by Tyriar** [comment]
> What is the state of this ticket?

No plans to support officially.

> Snap: Startup is painfully slow

I believe this issue was fixed a while ago after we reported it to the snapcraft team https://github.com/Microsoft/vscode/issues/61613#issuecomment-448930788

**Comment by chadalen** [comment]
@Tyriar I will try using the snap when I can actually install snaps again... I always use snaps as last resort because I always have so many problems with them. I just opened up an issue for snapd because I can't even install any snaps.

[https://bugs.launchpad.net/snapd/+bug/1826662](https://bugs.launchpad.net/snapd/+bug/1826662)

Reason I use AppImage is because I use several linux distros. I use Fedora (rpm based) for work and Ubuntu (deb based) for my home computer. I just had to install vscode using a debian package because snap wasn't working for me. Then on my fedora system I had to install using an rpm because Flatpak (terminal doesn't work in vscode) and snapd had issues for me.. Would be nice if I can just take that one file and run vscode without looking for a deb or rpm which defeats the purpose of these universal formats that we should be moving to. I feel like if a big company like Microsoft moved away from deb/rpm we can make Linux much better.

I really hope you can reconsider.

**Comment by Tyriar** [comment]
@chadalen thanks for reporting that, it worked fine for me on Ubuntu 19.04 when I tried last week.

> Is there any downsides of doing this?

If everyone had their way we would be distributing tarball, deb, rpm, snap, flatpak, appimage and AUR packages. The cost of implementing and supporting all of them is too high.

Right now there are community-based options for appimage, flatpak and AUR if you really want to use them over what we provide. Seems fairly simple to use https://github.com/AppImage/pkg2appimage/blob/master/recipes/VSCode.yml and you can see from the source that it's derived from our deb package.

**Comment by chadalen** [comment]
@Tyriar Ok I see your point. Thanks for your response.

**Comment by mick33** [comment]
i love appimage, simple and easy transfert with parameters

**Comment by probonopd** [comment]
Just for information if you are looking for an AppImage, the VSCodium project is providing binary releases of VS Code without MS branding/telemetry/licensing, including AppImages:
https://github.com/VSCodium/vscodium/releases

**Comment by Tyriar** [comment]
In the interest of transparency I'm closing this issue as out of scope as we do not plan on implementing this in the foreseeable future and keeping the issue open gives the wrong impression that we may. The primary reasons for closing is that the cost to maintain and support yet another distribution mechanism is too high for too little payoff. You can read more on our [issue triaging](https://github.com/microsoft/vscode/wiki/Issues-Triaging) wiki page on why we close issues.

**Comment by mightyiam** [comment]
I'm happy with the snap on Ubuntu.

**Comment by godalming123** [comment]
I suggest if we want an app image support we switch to vscodium as they have an official release for appimegs https://github.com/VSCodium/vscodium/releases/tag/1.59.0

**Comment by sean-gray** [comment]
I agree 100%. We run Fedora SilverBLue and it would be a lifesaver. and @Tyriar appimages can replace deb and rpm builds.

**Comment by kdm6389** [comment]
appimegs are good
