### ISSUE TITLE
Add command-line option for updating.

### ISSUE THREAD

**Issue by Jaykul** [Microsoft/vscode#10852]
Now that the insider's are getting _nightly_ new builds, we need a way to trigger the download and install **before** opening the editor, so we don't have to open it, and then wait for it to fetch the update, and then restart again... every morning.

Ideally, a command-line option, or just a separate helper script, which could take care of fetching and starting the update install. Then we could (optionally) create a shortcut that would check for and install any updates _before_ starting the editor.

**Comment by DanTup** [comment]
If delaying the startup is a concern, if new builds are generally consistent, you could possibly make an assumption about whether there's an update based on the date of current build and current date?

That would allow fast startup when you're (probably) already on the latest version, avoid the restart when you're (probably) not on the latest version, and if you get it wrong the penalty is minor (delayed startup now and then, or restart if an extra build was pushed).

**Comment by joaomoreno** [comment]
Feel free to write such a script on your machine.

The URL to figure out whether there is an update to download is:

```
https://vscode-update.azurewebsites.net/api/update/darwin/insider/VERSION
```

Where `VERSION` is your current Code commit hash version, which you can find out with the following command:

```bash
node -p 'require("/Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Resources/app/product.json").commit'
```

The URL will return 200 with a JSON object describing where to download the update, or 204 when there is no update available.

Updating is just unzipping and replacing the app in disk.
