### ISSUE TITLE
No settings Found

### ISSUE THREAD

**Issue by atyuwen** [microsoft/vscode#108523]
Issue Type: <b>Bug</b>

1. Select any extension.
2. In context menu, click "Extension Settings".
3. The setting page shows no items. 

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (17.00GB free)|
|Process Argv|--crash-reporter-id abc23c44-bd1b-44a3-9c87-2ebe1dd17a8e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.0
messiahsl|aty|1.8.0
python|ms-|2020.9.114305
cpptools|ms-|1.0.1
code-spell-checker|str|1.9.2
sleeping-forest-ue4|suv|0.6.14
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by atyuwen** [comment]
From the extension's detail page, we can see many settings here.
![image](https://user-images.githubusercontent.com/1708081/95735874-03ab3600-0cb8-11eb-8b1f-17f381e710d3.png)

But the setting page only shows: No settings found.
![image](https://user-images.githubusercontent.com/1708081/95735836-f3935680-0cb7-11eb-82bd-bd341434b732.png)

**Comment by roblourens** [comment]
Can you try with the Insiders build? I think we just fixed something related to this, and it works for me. https://code.visualstudio.com/insiders

**Comment by atyuwen** [comment]
I tried insider build and the bug is gone. Thanks.
