### ISSUE TITLE
vscode hang when update exts and reload win, and also hang when check exts update（vscode>1.48）

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#108502]
Issue Type: <b>Bug</b>

1. check exts update, hang
2. update exts,and than reload win, vscode will hang and show dialog

hang was occured when vscode version >1.48, please fix it. 
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.67GB (1.84GB free)|
|Process Argv|--crash-reporter-id dda9faca-e42e-4975-a2ba-c96c78991221|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joaomoreno** [comment]
> vscode will hang and show dialog

Can you show me a screenshot of that?

**Comment by heartacker** [comment]
> > vscode will hang and show dialog
> 
> Can you show me a screenshot of that?

as same as
![](https://user-images.githubusercontent.com/1876302/90842725-90a9d100-e392-11ea-9509-64b1d8a37584.png)
https://user-images.githubusercontent.com/1876302/90842725-90a9d100-e392-11ea-9509-64b1d8a37584.png


https://github.com/microsoft/vscode/issues/105118

**Comment by heartacker** [comment]
when I update some exts
and than reload window of vscode
than vscode will must hang

![image](https://user-images.githubusercontent.com/1876302/95751846-be93fd80-0cd1-11eb-9c6f-a90bbf890fc2.png)

![image](https://user-images.githubusercontent.com/1876302/95751970-e97e5180-0cd1-11eb-80c4-ce190f5cdd97.png)

VSCODE>1.48

**Comment by sandy081** [comment]
Can you please follow these instructions and share the performance profile - https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process
