### ISSUE TITLE
Feature: Ctrl+Click on file paths to open file

### ISSUE THREAD

**Issue by Svish** [microsoft/vscode#108527]
VS Code currently has a _very_ helpful feature where it allows you to Ctrl+Click on any web links anywhere (as far as I can see), whether that is in a markdown file, a java comment, or a typescript variable value. It would be _very_ helpful if this feature was extended to also cover file paths!

E.g. the following file (a [.betterer.results](https://github.com/phenomnomnominal/betterer) file), contains file paths to files currently containing typescript errors, and it would be _very_ helpful if I could just Ctrl+Click on a one of those paths to navigate to it.

![image](https://user-images.githubusercontent.com/142162/95749242-938eb700-0c9b-11eb-9337-2e07702669dc.png)

The highlighting could be a combination of an "is this a valid file path"-regular expression and if it is, check if the file exists (either absolutely, if it's an absolute path, or relative to the file or the project root). If all good, underline and allow Ctrl+Click, the same as for web links.

**Comment by Svish** [comment]
The google link was added manually by me, just to check that the Follow link did indeed work within a random string like this as well.

I did try to search for similar issues, but either they do not exist, or I just wasn't able to see them because of all the issues related to Ctrl+Clicking on stuff in terminal windows. My feature request is about paths in editor windows.

**Comment by mjbvz** [comment]
We leave this up to extensions to implement per language

**Comment by Svish** [comment]
@mjbvz But the Ctrl+Click for hyperlinks is built-in, isn't it? Why can't you expand that already existing feature to cover file-paths too?

Extensions could be great to make the feature more sofisticated or whatever, but this shouldn't be a per language extension thing, it should be a simple core built-in feature that should Just Work™ work everywhere. You _already have_ the feature for the built-in terminal in VS Code even. It's super useful there, and would be just as useful in the editor, whether it be file-paths in a log file, or a config file, or a setup thing, or a string referring to a file somewhere, or whatever.

**Comment by mjbvz** [comment]
Hyperlinks are well known and have a standard format. File paths do not. Consider:

- Path styles (windows, unix, ...)
- False positives
- Relative paths

It's a bug/feature farm. Per language extensions are better (if you want, you could write an extension that enables paths for all languages too, but it'd be up to you to maintain that)
