### ISSUE TITLE
Ability To Permanently Change App Icon

### ISSUE THREAD

**Issue by timkofu** [microsoft/vscode#108583]
There are some nice icons on the [vscode-icons](https://github.com/dhanishgajjar/vscode-icons) project (for the app itself as seen in Applications and when running), but every updated sets it back to the original vscode icon. Would it be possible to have a way to permanently set it?

**Comment by timkofu** [comment]
@vscodebot It's not a dup as far as I can tell.

**Comment by misolori** [comment]
@joaomoreno @deepak1556 is this even possible with our builds?

**Comment by joaomoreno** [comment]
No, not possible nor supported... Sorry!

**Comment by timkofu** [comment]
Well alright. It’s a great editor and we like it, hence the wanting to customize it to make it our own (the Vim icon is my favorite). Maybe in the future?
