### ISSUE TITLE
Arguments for Powershell in integrated terminal not working as expected

### ISSUE THREAD

**Issue by guillermoarb** [microsoft/vscode#108562]
![image](https://user-images.githubusercontent.com/8877521/95813797-539cf380-0cde-11eb-9442-663323f6987a.png)

When using feature to start PowerShell with arguments (**terminal.integrated.shellArgs.windows** ), the terminal closes.  Argument "-noexit" need to be part of the arguments send as part of the command.

Steps to Reproduce:

1. Set configuration

```
    "terminal.integrated.shell.windows": "C:\\windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.shellArgs.windows": ["dir"],
```

Then this will launch the terminal but it is going to close.  If terminal.integrated.shellArgs.windows option is deleted then the powershell will start as normal.

2.- Workaround, add the option -noexit to force PowerShell to remain open.

```
    "terminal.integrated.shell.windows": "C:\\windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.shellArgs.windows": ["-noexit", "dir"],
```

This may be not an issue but it was not expected by me.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is working as expected, `shellArgs` is an advanced level feature that allows the user finer control, hardcoding `-noexit` when the shell is detected as powershell or something would be frail and take away control from the user.
