### ISSUE TITLE
Window has moved off the screen

### ISSUE THREAD

**Issue by PetrSrom** [microsoft/vscode#108524]
- VSCode Version: 1.50.0
- OS Version: Windows 7

If i click on the icon "Visual Studio Code" on Windows taskbar - window VSC is moved out of screen (behind left side). 
The window cannot be seen.

**Comment by bpasero** [comment]
This sounds like a bug of the Windows OS window manager to me that it allows to move windows offscreen, I suggest to report this against windoofs.

**Comment by PetrSrom** [comment]
Ok, thanks for comment.
