### ISSUE TITLE
VS Code Insiders install got corrupted after an update attempt

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#108542]
- VSCode Version: 1.51.0-insiders. October 9th version updating to October 12.
- OS Version: Windows 10 (19041)

Steps to Reproduce:

1. I just did the update. Nothing unusual.
2. Run code-insiders
```
#
# Fatal error in , line 0
# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
#
#
#
#FailureMessage Object: 0000007BF11BF350
```

Does this issue occur when all extensions are disabled?: Yes

I'm going to uninstall/resintall to fix it.

**Comment by joaomoreno** [comment]
And this error prevents code from launching altogether? @jrieken Are these the snapshots we do?

**Comment by sean-mcmanus** [comment]
Yes, code - insiders failed to launch, and just output those error lines. Uninstall/reinstall fixed the issue.

**Comment by jrieken** [comment]
No, we don't create snapshots, only cached data files. Snapshots usually come with v8/electron for things like `Math`, `Regex` etc

**Comment by joaomoreno** [comment]
Then I'm guessing it was just an update gone wrong, too common I'm afraid. I suggest to Windows background updates for now. Set `update.enableWindowsBackgroundUpdates` to `false`.
