### ISSUE TITLE
Extended glob patter for findFiles

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#10851]
It seems that `vscod.workspace.findFiles` doesn't support extended patterns such as:

`**/+(gulpfile.js|package.json)` or `'**/@(node_modules|jspm_packages|bower_components)/**'`

http://www.linuxjournal.com/content/bash-extended-globbing

it is quite limiting.

**Comment by whitecolor** [comment]
Or another proposal is to add ability for mult-pattern so it would be possible to pass array of simple patterns.

BTW `findFIles` works quite slowly is it because it checks all the nested folders and tests all files against exclude pattern?

**Comment by bpasero** [comment]
Unlikely given that we now depend on RipGrep glob handling, but I let @roblourens decide

**Comment by roblourens** [comment]
I opened this issue to allow passing an array of patterns: https://github.com/Microsoft/vscode/issues/38545. I much prefer that over supporting extended glob syntax.
