### ISSUE TITLE
Extensions with a onDebugDynamicConfigurations are eagerly activated at startup in v1.50

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#108578]
In 1.50, any extension that has `onDebugDynamicConfigurations` in its activation events is immediately activated when ~~opening any project~~ loading VS Code. This did not happen in v1.49.

```
[2020-10-13 10:37:47.815] [exthost] [info] ExtensionService#_doActivateExtension Dart-Code.dart-code {"startup":false,"extensionId":{"value":"Dart-Code.dart-code","_lower":"dart-code.dart-code"},"activationEvent":"onDebugDynamicConfigurations"}
```

There's some discussion around this in https://github.com/microsoft/vscode/issues/96297 / https://github.com/microsoft/vscode/issues/88230 and my understanding is that they should not be activated so early. This leads to other issues such as language extensions spawning their language servers for every project (whether they should is another issue - but there's no guidance from VS Code on how they should handle this, especially without knowing [why they were activated](https://github.com/microsoft/vscode/issues/44711)).

**Comment by weinand** [comment]
@isidorn IIRC, we have discussed the approach for avoiding early activation in #96297.

**Comment by isidorn** [comment]
@DanTup correct but we are activating only the type that is needed I assume.
Does this happen all the time, or only when a user has used a dynamic configuration from Dart and reloads the window?

If that is the case, we need to get dynamic configs on startup to be able to select the proper one.

**Comment by DanTup** [comment]
@isidorn it's worse than that - the extensions are activated unconditionally at startup of VS Code. If you install the Dart extension, click File -> Close Folder, then **Reload Window** you'll see Dart is immediately activated without doing anything (or even having any workspace folder open).

**Comment by isidorn** [comment]
Assigning to October to investigate more

**Comment by isidorn** [comment]
@DanTup thanks a lot for reporting this and sorry about the breakage.
I have pushed a fix for this, so please try it out with vscode insiders from tomorrow and let us know how it goes. Thanks a lot!

**Comment by DanTup** [comment]
Thanks, will do!

**Comment by DanTup** [comment]
@isidorn fix looks good to me, thanks!

**Comment by isidorn** [comment]
Great, thanks for letting us know. Adding verified label.
