### ISSUE TITLE
Pinned tab doesnt scroll to focus

### ISSUE THREAD

**Issue by rhizene** [microsoft/vscode#108561]
Issue Type: <b>Bug</b>

scenario:  many tabs, pinned tab scrolled far left
if  alt + 1 was pressed
or navigated from last tab using ctrl + page down
pinned tab  doesn't focus

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 4.15.0-118-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.54GB (1.37GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 0b6f0557-baa6-44d3-a0c7-6108ef4bc2b1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
githistory|don|0.6.12
csv-editor|est|0.2.2
beautify|Hoo|1.5.0
loreminem-ipsum|may|0.0.1
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.22.0
vscode-manifest-yaml|Piv|1.22.0
vscode-spring-boot|Piv|1.22.0
java|red|0.68.0
vscode-yaml|red|0.11.1
vscode-coverage-gutters|rya|2.6.0
lorem-ipsum|Tyr|1.2.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-spring-boot-dashboard|vsc|0.1.10
vscode-spring-initializr|vsc|0.5.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Yes, I may have broken this last milestone.

**Comment by bpasero** [comment]
Excellent catch 👍

**Comment by rhizene** [comment]
this one of my favorite hotkeys, thanks!
