### ISSUE TITLE
File is not active in tab when opened from search results

### ISSUE THREAD

**Issue by ajithks44** [microsoft/vscode#108579]
Issue Type: <b>Bug</b>

I am using the latest update. When I select a file from the search results, the same is not active in tabs. Also it' svery difficult to navigate between tabs when there are pinned tabs as well..

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18362

**Comment by roblourens** [comment]
Are you saying that when you click the search result, the file does not open in the editor?
