### ISSUE TITLE
How can I add user defined buttons in debug toolbox that support assembly level debugging with source?

### ISSUE THREAD

**Issue by freedomhero** [microsoft/vscode#108564]
I've developed a debugger extension in vscode for some compiled language. Now I'm trying to add a new feature that could let the user dive into the assembly code during debugging. For example, one can debug step by step in the source code, meanwhile he could also chose to run instruction by instruction in the assembly codes. How can I implement something like that? How can I add some user defined buttons for that purpose in debug toolbox?

**Comment by isidorn** [comment]
You can contribute a command to the `debug/toolbar` menu.
More details here https://code.visualstudio.com/api/references/contribution-points#contributes.menus
