### ISSUE TITLE
Angular language features and intellisense stopped working

### ISSUE THREAD

**Issue by Tomas-Tr** [microsoft/vscode#108581]
Issue Type: <b>Bug</b>

The typescript intellisense  feature and go to definition gets slow after week of usage. Workaround is copy whole project to new folder

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.15GB free)|
|Process Argv|--crash-reporter-id dc5ed1fc-aea0-44d4-8600-f461e9565eac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1001.0
gitstash|art|3.3.0
vscode-eslint|dba|2.1.10
githistory|don|0.6.12
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
gc-excelviewer|Gra|3.0.40
csharp|ms-|1.23.3
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
angular-console|nrw|14.0.1
pwabuilder-extension|PWA|0.0.3
java|red|0.68.0
code-settings-sync|Sha|3.4.3
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2

</details>

**Comment by mjbvz** [comment]
If you are seeing angular specific issues, please start by filing them against your angular extension
