### ISSUE TITLE
Terminal running very slow on Big Sur

### ISSUE THREAD

**Issue by paulfsheridan** [microsoft/vscode#108544]
- VSCode Version: 1.50.0
- OS Version: Big Sur 11.0 Beta

Steps to Reproduce:

1. Open integrated terminal, `cd` into a directory

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by yay** [comment]
Same issue here. VS Code 1.50.1 (no extensions), Big Sur Beta 10.
VS Code is unresponsive initially when the terminal is first opened and one starts typing. Then the typed letters show up twice as in the screenshot:
![screenshot](https://user-images.githubusercontent.com/1799756/96289218-8b58b380-0fdc-11eb-9a8d-4ff26b26c0d2.jpg)
Built-in terminal can get temporarily unresponsive randomly later on as well.

**Comment by paulfsheridan** [comment]
@yay I think the latest Big Sur patch _may_ have fixed this.

**Comment by yay** [comment]
I’m using macOS 11.0.1 beta and the issue is still there.
