### ISSUE TITLE
VSCODE with ext PowerShell 0.7.0 - Throws errors and fails...

### ISSUE THREAD

**Issue by EM1L** [Microsoft/vscode#10854]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

On Windows 7 workstation with latest SP etc.

1. Download VSCODE and do a fresh install; 
   1.1 This also happens for me as a result of an upgrade of the PowerShell extension to Version 0.7.0; Basically I have tried this on two different workstations;
2. Install the **[vscode.PowerShell](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell) Version 0.7.0**
3. Open PowerShell file and you should observe the errors reported in the UI:

>**Error  Could not start language service: undefined**

>**Error  Couldn't start client PowerShell Editor Services**
 

Please note I have also tried uninstalling both VSCODE and the extension multiple times and cleaned %AppData% etc. without any success.

I was successfully running VSCODE with previous version of PowerShell extension 6.x.x and the error condition occurred after upgrade to PowerShell 0.7.0

**HELP:** Meanwhile any tips how to obtain and run the older PowerShell extension will be greatly appreciated as I have lost my PowerShell DEV environment as VSCODE was my editor of choice :)

**Comment by rjwiii** [comment]
I am having the same issue. See screenshot.
![vscode-error](https://cloud.githubusercontent.com/assets/4544754/17907552/7479a3fa-694a-11e6-8294-8750acf76a95.PNG)

**Comment by rjwiii** [comment]
Fix on the way ...

https://github.com/PowerShell/vscode-powershell/issues/254

rjwiii

**Comment by EM1L** [comment]
Thanks for the link rjwii :+1: 
Looks like we are going to get a fix very soon :)
