### ISSUE TITLE
Unable to locate package code-insiders

### ISSUE THREAD

**Issue by doodlewhale** [microsoft/vscode#108501]
- OS Version: Kali Linux

Steps to Reproduce:

1. Add vscode stable main to sources.list.d as per instructions here https://code.visualstudio.com/docs/setup/linux
2. sudo apt-get install code-insiders
3. Error: Unable to locate package code-insiders

**Comment by Tyriar** [comment]
Did you run `sudo apt-get update` beforehand? I don't think there are any known problems at the moment with the apt repo.
