### ISSUE TITLE
Unable to click the links under "Start" on the Welcome screen.

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vscode#108577]
Issue Type: <b>Bug</b>

1. Launch Visual Studio Code - Insiders.
2. Make sure the Welcome screen is open.
3. Click on one of the links under "Start".

This happens under Linux and Windows.

Here's a screenshot showing the links in question:

![Screenshot from 2020-10-13 05-44-50](https://user-images.githubusercontent.com/1977106/95845155-d3937f80-0d17-11eb-843c-64e1dec93141.png)

VS Code version: Code - Insiders 1.51.0-insider (605bc4ec1eaf8dc1acd89a0c3c5743926ed0dc09, 2020-10-12T10:50:18.940Z)
OS version: Linux x64 5.8.14-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2757)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.51GB (7.20GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 5ae4f025-c7cc-49c2-ba42-78795be3d05a|
|Screen Reader|no|
|VM|67%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.3.0
ng-template|Ang|0.1001.0
cmake-format|che|0.6.11
gitignore|cod|0.6.0
doxdocgen|csc|1.0.1
dart-code|Dar|3.15.0
flutter|Dar|3.15.0
vscode-eslint|dba|2.1.10
git-extension-pack|don|0.1.3
githistory|don|0.6.12
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.1
cpp-class-creator|Fle|0.17.0
vscode-pull-request-github|Git|0.20.1
vscode-guid|hea|1.4.20
better-cpp-syntax|jef|1.15.0
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.8.0
csharp|ms-|1.23.3
remote-containers|ms-|0.145.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.0
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.1
cpptools-extension-pack|ms-|1.0.0
powershell-preview|ms-|2020.9.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.2902
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3007
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
angular-console|nrw|14.0.1
material-icon-theme|PKi|4.3.0
java|red|0.68.0
vscode-xml|red|0.13.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-icons|vsc|11.0.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
@jrieken and @JacksonKearl for the most recent changes.

**Comment by JacksonKearl** [comment]
@jrieken victim #1 of https://github.com/microsoft/vscode/pull/108332 😆

Though I have no clue why it'd be stripping `href`s from `a` tags... it seems like we explicitly allow them.

**Comment by JacksonKearl** [comment]
...wut...
![image](https://user-images.githubusercontent.com/8586769/96029706-e25d5d80-0e0f-11eb-9bdd-dde3df020b94.png)

**Comment by jrieken** [comment]
Thanks for fixing
