### ISSUE TITLE
setting.json "Can Not edit in read-only editor"

### ISSUE THREAD

**Issue by Gnnhnk** [microsoft/vscode#108594]
Issue Type: <b>Feature Request</b>

the default setting.json occurs problems, unable to settle with notification "Can Not edit in read-only editor",  how to solve this?

![](https://ftp.bmp.ovh/imgs/2020/10/0b6cc9992741f323.png)

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Gnnhnk** [comment]
Something changed the default \0\setting.json file with errors, but i can't reinstate it by hand.

**Comment by gjsjohnmurray** [comment]
How did you open the file that your screenshot shows?

Does its tab label read `defaultsettings.json` ?

I'm guessing the problem doesn't occur if you run the command to reload with all extensions disabled, right?

**Comment by Gnnhnk** [comment]
> How did you open the file that your screenshot shows?
> 
> Does its tab label read `defaultsettings.json` ?
> 
> I'm guessing the problem doesn't occur if you run the command to reload with all extensions disabled, right?

It's strange. The tab shows `setting.json` and the problems panel indicates the path `\0`.

I can't find the real path that `\0` refers for editing `setting.json` by using other editor.

**Comment by Gnnhnk** [comment]
![](https://ftp.bmp.ovh/imgs/2020/10/1b73cfdbb9100b7c.png)

**Comment by gjsjohnmurray** [comment]
> How did you open the file that your screenshot shows?

@Gnnhnk I didn't see an answer to this question.

**Comment by roblourens** [comment]
Yes please try what @gjsjohnmurray says, and if that doesn't work, can you tell me what the content that got added to that file says? You might also just try reinstalling vscode.
