### ISSUE TITLE
Add a setting to configure the size of the area the breakpoints are added

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#108528]
Currently there is too much space in the area we add breakpoints. Is it really necessary?

![image](https://user-images.githubusercontent.com/55927613/95749192-1eb77f00-0c93-11eb-859d-eef3ff494d55.png)

I could fit two breakpoints there haha

![image](https://user-images.githubusercontent.com/55927613/95749273-3bec4d80-0c93-11eb-99d4-284a349d9281.png)

I did not find a way to configure it.

**Comment by isidorn** [comment]
This is just the size of the editor glyph margin. There can be other things there not only breakpoints (for example quick fixes).
This is designed behavior of the editor thus closing.
