### ISSUE TITLE
LocalHost connection error

### ISSUE THREAD

**Issue by paulkckho** [microsoft/vscode#108553]
This error continue to display. No solutions found. 
![Screenshot 2020-10-12 184626](https://user-images.githubusercontent.com/72099759/95802724-7ec21b80-0cbb-11eb-9348-880aa31c3f89.png)

**Comment by chrmarti** [comment]
This issue misses any context to assess it, but it very much looks like it has nothing to do with VS Code. Please explain.

**Comment by paulkckho** [comment]
This error has everything to do with VS Code. This program cannot access LocalHost 8080. This program need to be updated to access browser.

**Comment by chrmarti** [comment]
The screenshot is showing a browser unable to access localhost:8080. That is all I see.
