### ISSUE TITLE
ansible-playbook not executable error via VSCode debug console on WSL2 (Ubuntu 20.04.1) in virtualenv

### ISSUE THREAD

**Issue by EthanBannister** [microsoft/vscode#108556]
- VSCode Version:  1.50.0
- OS Version: Windows 10 Pro 2004 Build 19041.508

Steps to Reproduce:

1. Install and set up Ubuntu 20.04.1 on WSL2
2. Connect to WSL instance in VSCode
3. Create a Python 3 virtual environment
4. Enter newly created Python Virtual Environment
5. Install (via pip) ansible-runner
6. Create new test script using ansible_runner.run:

Example:
def ansibleRunnerManipulate(playbook_path, hostIP, ansible_user, ansible_user_pass, curTime, extvars):
    defaultvars = { 'ansible_become_pass': ansible_user_pass,'ansible_user': ansible_user, 'ansible_ssh_password': ansible_user_pass, 'ansible_password': ansible_user_pass, 'curTime': curTime }
    defaultvars.update(extvars)
    r = ansible_runner.run(playbook=playbook_path, inventory=hostIP, extravars=defaultvars)
    return r.rc

7. Create a test playbook (something simple that echoes "hello world" or something.  Use the path for this playbook in the previous step.
8. Open another generic terminal to you WSL2 Ubuntu instance and attempt to execute the same Ansible script

I have tested things out on the insiders build of VSCode and I get the same results.

Does this issue occur when all extensions are disabled?: Yes

This issue occurs only with WSL.  If I use SSH to connect to another Ubuntu VM that is set up exactly the same way as my WSL2 Ubuntu instance, it works just fine with all the same extensions applied.  Also, if I log directly into my WSL2 Ubuntu instance via the Windows Terminal application, enter into my virtual environment, then run my script, it also works fine.  Thus, I have narrowed it down to it being something specifically with VSCode and it's relationship with WSL.

**Comment by connor4312** [comment]
What's the precise error you get?

**Comment by EthanBannister** [comment]
The exact error is just stdout in the integrated terminal:

![image](https://user-images.githubusercontent.com/9910708/95923418-7c2af900-0d83-11eb-88ff-054a12ce627f.png)

To keep things short, the script that I am writing creates a clone of a VM on XenServer, then attempts to make changes on the clone using Ansible.  Since Ansible relies on SSH to manipulate the files, I put in a loop that checks for SSH connectivity every 5 seconds (after waiting an initial 30 seconds for the VM to start).  This may be why you see 'The command was not found or was not executable: ansible-playbook.' repeat over and over in the screenshot.

When I attempt to execute the exact same script, but this time within the Ubuntu terminal (WSL2), it works with no problems:

![image](https://user-images.githubusercontent.com/9910708/95924068-d5475c80-0d84-11eb-9f12-84a87f8541f6.png)


When inside the virtual environment, if look at the anisble-playbook executable permissions, it appears that all of them are set as  executable globally:

![image](https://user-images.githubusercontent.com/9910708/95925297-6fa89f80-0d87-11eb-88ba-843476714504.png)

**Comment by alexr00** [comment]
@EthanBannister a few questions:
- Are you entering 
![image](https://user-images.githubusercontent.com/38270282/95962861-3748a600-0e07-11eb-8e7d-0acffbccd7cf.png)
into the VS Code integrated terminal yourself, or do you run something from some extension and it starts the terminal?
- Can you share any VS Code integrated terminal settings you have (user settings, workspace settings, remote settings)?

**Comment by EthanBannister** [comment]
This is automatically entered when I start the debug process (generally, by pressing F5).  Since I have automatically set my default interpreter to be python in the venv, it automatically enters the venv and executes the script (which is actually really nice to see).
![image](https://user-images.githubusercontent.com/9910708/96057714-9504de80-0e57-11eb-8b5a-2c65d7d3c93a.png)

My launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "xennu.py",
            "console": "integratedTerminal",
        }
    ]
}
```

My settings.py:
```
{
    "python.pythonPath": "venv/bin/python"
}
```

The script is called 'xennu.py', and I have it in the launch.json because I want it to execute that script when I attempt to debug.  Any libraries/modules which I have created are pulled in from headers in that script and used later on.

**Comment by alexr00** [comment]
@EthanBannister can you share your VS Code settings too? I'm wondering if there are any terminal settings that are causing this.

**Comment by EthanBannister** [comment]
I see now, sorry about that.  Here is my global config:

```
{
    "workbench.startupEditor": "newUntitledFile",
    "remote.SSH.remotePlatform": {
        "LINBOX": "linux",
        "REDACTED": "linux",
        "REDACTED": "linux"
    },
    "files.autoSave": "afterDelay",
    "kite.showWelcomeNotificationOnStartup": false,
    "kite.showGoBetaNotification": false,
    "workbench.colorTheme": "Monokai Dimmed",
    "sync.gist": "0652fec2a0eefb5a9f9cd369c3042c22",
    "workbench.iconTheme": "material-icon-theme",
    "git.autofetch": true,
    "editor.accessibilitySupport": "off",
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.languageServer": "Pylance"
}
```

I disabled all of my extensions, with the exception of some that are needed for WSL and Python support.  However, even with all my extensions enabled, the same issue occurs.

**Comment by alexr00** [comment]
@isidorn, how does debug create terminals?

**Comment by isidorn** [comment]
External terminal we launch using this code
https://github.com/microsoft/vscode/blob/3e8c2e036d429c2bc8662da2e009a8088fd2af96/src/vs/workbench/contrib/debug/node/terminals.ts#L15

Though @weinand would know more, thus forwarding to him

**Comment by weinand** [comment]
Since the launch.json from above uses `"console": "integratedTerminal"`, not an "external terminal" but an "integrated terminal" is used.

The integrated terminal is launched using this code:
https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostDebugService.ts#L74-L116

**Comment by weinand** [comment]
@EthanBannister are you saying that the executable command "ansible-playbook" is not found on the PATH when you (indirectly) launch it through a launch config (F5), whereas it is found if launched manually from an integrated terminal?

**Comment by EthanBannister** [comment]
@weinand Yes.  However, to clear things up with regards to the integrated terminal, if I were to manually launch the script using any terminal, integrated or external, I would always ensure that I manually enter into my virtual environment first (i.e. via `source venv/bin/activate`).  When I see "(venv)" prepended in front of my prompt, I am good to go.

With VSCode, I never see this prompt under any circumstance.  In cases where I connect to a remote SSH host which has the script and virtual environment, it works with no issues anyway.  I am assuming that if VSCode is told to use the virtual environments Python interpreter, then it will automatically execute the script by silently entering this silo first, then executing and debugging the code it as it normally would.

**Comment by EthanBannister** [comment]
Unfortunately, I no longer have access to the code that I had been experiencing this issue with, so I would no longer be of any help without recreating the scenario from scratch.

This issue was mostly intended to let development know about it so that hopefully they can improve the product.  It was not a complete blocker for me since I was able to connect to a remote Linux host and work from there with no issues.

As mentioned previously, the issue appears to be either related to WSL/WSL2 and how VSCode interacts with it.  Perhaps someone from the development team can set up WSL2 on their host, create a Python virtual environment, install ansible-runner, then create a small script that uses it and attempt to run it in the VSCode terminal.

All this being said, I will close this issue now that the developers at Microsoft are at least aware of it.
