### ISSUE TITLE
Sign-in to setting sync error

### ISSUE THREAD

**Issue by deepan-py** [microsoft/vscode#108513]
When trying to sync settings in VS-Code with Microsoft it throws error saying **Writing login information to the keychain failed with error 'The stub received bad data. '.**

![Screenshot 2020-10-12 123048](https://user-images.githubusercontent.com/60477808/95715179-06d9fe00-0c87-11eb-9f1b-e4a183cedfbb.png)

**Comment by deepan2509** [comment]
related to #108411
