### ISSUE TITLE
html block comment problem in php file

### ISSUE THREAD

**Issue by sorabh86** [Microsoft/vscode#10855]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. create an php file
2. type some html and try to comment using ctrl+/ <- single line,
 alt+shift+a <- block level (this is better to be default shortcut of ctrl+shift+/ used for all famous text editor so i had changed)
3. you will see html comment are not working there, without <?php ?> syntax getting php comments in html

**Comment by sorabh86** [comment]
I didn't tested but i am sure same problem will be detected on asp files.

**Comment by sandy081** [comment]
duplicate #10797
