### ISSUE TITLE
Crashes when opening whatever folder or checking for updates

### ISSUE THREAD

**Issue by step135** [microsoft/vscode#108531]
- VSCode Version: latest from snap today
- OS Version: Fedora 32

Steps to Reproduce:

1. click on option open folder or Help -> Check for updates

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by JacksonKearl** [comment]
Is this the latest insiders or stable version?

**Comment by step135** [comment]
As I wrote, it is the actual version on snap.

**Comment by JacksonKearl** [comment]
duplicate of https://github.com/microsoft/vscode/issues/100940
