### ISSUE TITLE
ERR: View resolver already registered for <viewId>

### ISSUE THREAD

**Issue by bcanzanella** [microsoft/vscode#108555]
VSCode Version:
Version: 1.50.0 (user setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. My fork has the changes to reproduce this. https://github.com/microsoft/vscode-extension-samples/compare/master...bcanzanella:already-registered-issue?expand=1 it's just a couple of package.json changes (and an svg [meow!?])

2. There's some combination of loading/reloading the extension and adding a folder to the workspace which creates `ERR View resolver already registered for calicoColors.colorsView`. I can consistently get it to happen with CodeStream by ensuring I don't have a workspace open, adding a folder to the workspace, and clicking the icon in the activity bar to open the webview. That doesn't seem to work 100% of the time with the calico cat example, but after a couple of times it seems to happen.

It doesn't appear to affect the sample's webview except for the error in the console, but when this happens with CodeStream our webview is dead (see attached).

My first guess is perhaps the `registerWebviewViewProvider` is somehow not disposing correctly? (even though it's in the context.subscriptions array...)

![image](https://user-images.githubusercontent.com/834948/95804905-087ce380-0cd2-11eb-8362-d8f6568e5ab6.png)
![image](https://user-images.githubusercontent.com/834948/95805036-6d383e00-0cd2-11eb-81d1-cdfc8a284fc9.png)

Does this issue occur when all extensions are disabled?: N/A

**Comment by mjbvz** [comment]
The new behavior should now be:

1. Starting with a single folder
1. Webview created
1. User adds folder to create a workspace
1. Extension host restarts.
1. This should restart the extension and also clear the old webview view
1. We should then try re-resolve the new webview view with the new extension host
