### ISSUE TITLE
language server debugging breaks when using extensionDependencies

### ISSUE THREAD

**Issue by badsyntax** [microsoft/vscode#108597]
- VSCode Version: 1.50.0
- OS Version: Macos Catalina

Description of problem:

My extension relies on another extension, so I set `extensionDependencies` in my `package.json` but doing so appears to break the node server debugging of my lsp server.

Steps to Reproduce:

This issue can easily be reproduced using the lsp-sample here: https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample

1. `git clone https://github.com/microsoft/vscode-extension-samples`
2. `cd vscode-extension-samples/lsp-sample`
3. Follow the instructions in the README to setup the extension
4. Place a [breakpoint here](https://github.com/microsoft/vscode-extension-samples/blob/9b8701dceac5fab83345356743170bca609c87f9/lsp-sample/server/src/server.ts#L139) and run the "Client + Server" launch config.
5. Type the letter 's' or 't'
6. The breakpoint should be hit
7. Add the following to `package.json`:
```json
"extensionDependencies": [
  "ms-vscode.node-debug2"
]
```
8. Run the "Client + Server" launch config.
9. Type the letter 's' or 't'
10. Notice the breakpoint is not hit. The breakpoints are disabled with a tooltip "Breakpoint ignored because generated code not found (source map problem?)"

Does this issue occur when all extensions are disabled?: I can't disable all extensions as my extension depends on other extensions.

**Comment by connor4312** [comment]
I cannot reproduce this, can you share logs?

/jsDebugLogs
