### ISSUE TITLE
docker.exe and visualstudio isnt connecting to the containers or anything else.

### ISSUE THREAD

**Issue by Justpro77** [microsoft/vscode#108543]
Containers- Failed to connect. Is doclker installed - yes its installed
Images - same problem
Registers - same problem
Networks option  - same problem
Volumes- same problem
Contexts- same problem

everything is installed and nothing is running , fix it 

Also docker,exe is not able to be uninstalled

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Docker extension. Please file a new issue for it: https://github.com/microsoft/vscode-docker/issues
