### ISSUE TITLE
Very Urgent

### ISSUE THREAD

**Issue by 07-Bash** [microsoft/vscode#108557]
Issue Type: <b>Feature Request</b>

please add auto brackettt feature in input means after user write  input it auto compltes to input""()""    i want these brackett sign pls!!!!!!!!!!!pls!!!!!!!

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:08:02.231Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by alannt777** [comment]
Enable auto bracket feature using UI Settings:

![image](https://user-images.githubusercontent.com/67918878/95810182-06487280-0d2e-11eb-8458-770526b12674.png)

Enable auto bracket feature using JSON Settings:

```json
"editor.autoClosingBrackets": "always"
```
