### ISSUE TITLE
Integrated terminal very slow 

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode#108590]
Issue Type: <b>Bug</b>

Just after the most recent update, the Integrated terminal is extremely slow to display any text, either entering commands or displaying the stdout of commands.  
Many times typing a complete command at the prompt will show up a s-i-n-g-l-e - c-h-a-r-a-c-t-e-r - a-t - a - t-i-m-e   over several seconds *after* you finished typing.

It does not matter which Shell I use (PowerShell, CMD, WSL bash, Git Bash).  Although, the bash shells **seem** to perform a little better.

All of these Shells perform normally on my computer, it is only when running in the Intergrated Terminal in VSCode.

Also, connecting to a remote computer with ssh, the stdout is also very slow.  Again, no problems using in any Shell outside of VSCode.

Is there some setting and can change back?

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.05GB free)|
|Process Argv|--crash-reporter-id f652528b-5678-4b12-9ca0-3de6b1e1135f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
macros|ged|1.2.1
graphviz-markdown-preview|gee|0.0.8
sftp|lix|1.12.9
marp-vscode|mar|0.15.1
python|ms-|2020.9.114305
rust|rus|0.7.8

</details>

**Comment by clayms** [comment]
changing the following settings helped.  Not sure why an update would make the Integrated Terminal nearly unusable.

```
    "terminal.integrated.allowChords": false,
    "terminal.integrated.drawBoldTextInBrightColors": false,
    "terminal.integrated.experimentalLinkProvider": false,
    "terminal.integrated.rendererType": "auto"

```

**Comment by dr-gino** [comment]
Using the Docker extension to view logs (around a 8000 lines) of a container would make not just the terminal but the entire VSCode editor laggy.
Setting `"terminal.integrated.rendererType"` from `"dom"` to `"auto"` did the trick. I had never touched that setting before.

Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z (3 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by Tyriar** [comment]
@clayms could you try out `"terminal.integrated.rendererType": "experimentalWebgl"`? If you could capture a performance profile through the devtools performance tab (help > toggle dev tools) and upload it that would let us know if the main thread is being blocked and by what.

**Comment by testworksau** [comment]
Hi @meganrogge, @Tyriar 👋 

Is this issue closed because it is fixed? Or do you still need more info?

FWIW I have the same issue, which is only present when `terminal.integrated.rendererType` is set to `dom`. I don't believe I have changed that setting before.

Here's the performance profile from my machine.

```
Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

[Profile-20201111T132351.zip](https://github.com/microsoft/vscode/files/5521337/Profile-20201111T132351.zip)

**Comment by Tyriar** [comment]
@testworksau the profile's interesting, not sure what could cause this apart from a Chromium issue (cc @deepak1556):

![image](https://user-images.githubusercontent.com/2193314/98830792-a8bc4a00-23ef-11eb-89f2-618b9838b3a5.png)

It looks different to the OP's issue, typically slow rendering like this in the terminal on Windows is due to this issue https://github.com/microsoft/vscode/issues/76548

**Comment by jamilraichouni** [comment]
> changing the following settings helped. Not sure why an update would make the Integrated Terminal nearly unusable.
> 
> ```
>     "terminal.integrated.allowChords": false,
>     "terminal.integrated.drawBoldTextInBrightColors": false,
>     "terminal.integrated.experimentalLinkProvider": false,
>     "terminal.integrated.rendererType": "auto"
> ```

That solved the same issue I had.
Thanks!

**Comment by johngrant** [comment]
I'm having this issue also. Let me know if I can add diagnostic data to this issue or another.

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

**Comment by Fortidude** [comment]
Terminal still very slow and it likes to freeze for 1-2 seconds when just typing.

**Comment by TheCaffeineDev** [comment]
I am also facing the same issue. Integrated terminal freezes for 1-2 seconds while typing.

**Comment by deepak1556** [comment]
@Fortidude @TheCaffeineDev what is your operating system and version ?

**Comment by TheCaffeineDev** [comment]
@deepak1556 I am using Mac OS Big Sur. Vs code version is: 1.51.1

**Comment by deepak1556** [comment]
Thanks, please subscribe to https://github.com/microsoft/vscode/issues/105446 for issues with terminal on Big sur.

**Comment by gpgabrielpaiva** [comment]
> Terminal still very slow and it likes to freeze for 1-2 seconds when just typing.

Same here.

Windows 10

**Comment by mkotsollaris** [comment]
For my setup (macos + big sur), this command fixed the problem:

🔺 `codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`

In case you don't have `xcrun`, you can install it via:

`xcode-select --install`

and then make sure to run the 🔺  command!

**Comment by TheCaffeineDev** [comment]
I also fixed mine by using the same commands as your @mkotsollaris . Not sure about windows though.

**Comment by testworksau** [comment]
@deepak1556 do you have any commentary on this? Do you need me to raise a new bug?

https://github.com/microsoft/vscode/issues/108590#issuecomment-725489014

**Comment by deepak1556** [comment]
@testworksau does running with `--disable-renderer-accessibility` fix the issue ?

**Comment by testworksau** [comment]
> @testworksau does running with `--disable-renderer-accessibility` fix the issue ?

@deepak1556 setting `terminal.integrated.rendererType` to anything other than `dom` fixed the issue for me. 

Do you want me to try `--disable-renderer-accessibility` with `terminal.integrated.rendererType` set to `dom`?

**Comment by deepak1556** [comment]
yes please try the flag with dom renderer for the terminal. Also can you take a performance profile in this setup ?

**Comment by pfisterer** [comment]
@deepak1556 For me, this notably improves terminal response time on Big Sur.

**Comment by MacKentoch** [comment]
So what is this issue from?

A lot of possible fixes but this is messy.

**Comment by pietroastolfi** [comment]
> --disable-renderer-accessibility

This worked for me as well. But still this is just a trick to avoid the problem, not a real solution.

**Comment by ogdenstudios** [comment]
Hey folks, I'm experiencing an issue I believe to be the same thing. 

Here's my VS code info: 

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0
```

And my machine info: 

![Screen Shot 2020-12-23 at 6 59 01 PM](https://user-images.githubusercontent.com/29899554/103050232-18763680-4551-11eb-84eb-6382f47e2ecd.png)

thanks for all your work!
