### ISSUE TITLE
Make active/clickable tooltip typing elements

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#10865]
![image](https://cloud.githubusercontent.com/assets/736697/17914179/5d8f0d82-69b9-11e6-9ffd-1345af54e8bd.png)
It would be cool if one could click on `vscode.DecorationRenderOptions` (that is on the screenshot) and see the description of this type/interface.

**Comment by sandy081** [comment]
@whitecolor you can do that by hovering on that. You can either do simple hover or ctrl + hover (which shows more info)

**Comment by whitecolor** [comment]
![image](https://cloud.githubusercontent.com/assets/736697/17923718/f032f0be-69fe-11e6-8d06-a1b492cc5349.png)


Hm, for example in this case I can not hover (+ctrl or not) on `GetResponse` and what it is.

**Comment by whitecolor** [comment]
Another simple example:
![image](https://cloud.githubusercontent.com/assets/736697/17929674/6e6e8dbe-6a1b-11e6-81a1-43766720be20.png)
It is not possible to see what are `CreateCommandParams` and it is very unconvincing.

@sandy081 please, reopen if you consider it is a problem

**Comment by whitecolor** [comment]
@sandy081 
I still would like to draw your attention on this. Because **typings can be quite complex** and I'm sure tooltip needs to be more functional while displaying helper information about such types.

![image](https://cloud.githubusercontent.com/assets/736697/18033039/7d425f8c-6d31-11e6-8638-e49566d95c79.png)


Click on this tooltip in any place causes next overloaded definition to show, and all. So this **tooltip is not very functional**. I think it could be made more functional. So that One could **click though the elements in the tooltip** and see the descriptions about of **inner types** inside this tooltip, without need to navigate though definitions sorce coude.

**Comment by jrieken** [comment]
@whitecolor What you are seeing there is signature help which API-wise is something different from a tooltip (HoverProvider vs SignatureInfoProvider). With the former you can in theory already do this (depends on each language extensions) the latter you cannot and it will require breaking API changes which we are not eager to make any time soon.

**Comment by whitecolor** [comment]
@jrieken 
Ok I just wanted to draw attention on this problem, you know better is possible and what is not)

**Comment by whitecolor** [comment]
> With the former you can in theory already do this (depends on each language extensions).

I'm taking about typescript. On this picture:

![image](https://cloud.githubusercontent.com/assets/736697/18311419/95e2ddac-751d-11e6-81fa-e6cedd436dfc.png)

How can I know what is "AsyncDriver" for example?

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
