### ISSUE TITLE
Constantly nagging about updates

### ISSUE THREAD

**Issue by jordanrh1** [microsoft/vscode#108615]
Issue Type: <b>Bug</b>

I open Code because I have work to do. Stop nagging me about updates. Just do it silently in the background.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
What do the nags look like? Could they be coming from your extensions?
