### ISSUE TITLE
codespaces: Unable to change color theme

### ISSUE THREAD

**Issue by Kreyren** [microsoft/vscode#108695]
NOTICE: Codespaces 'report a bug' lead me here

![image](https://user-images.githubusercontent.com/11302521/96059252-b7b1ea00-0e8d-11eb-8426-db8207825d1a.png)

- VSCode Version: codespaces
- OS Version: Mostly linux

Steps to Reproduce:

1. Open any codepsaces
2. Try to change color scheme

Does this issue occur when all extensions are disabled?: Yes/No

Seems that i am getting 404 each time i try to change the color scheme

![image](https://user-images.githubusercontent.com/11302521/96059358-0a8ba180-0e8e-11eb-90c5-75df46fe14b4.png)

**Comment by aeschli** [comment]
Sorry, can you file this against https://github.com/github/codespaces ?
