### ISSUE TITLE
wrappingIndent with cjk characters 

### ISSUE THREAD

**Issue by nonanonno** [Microsoft/vscode#10862]
- VSCode Version: 1.5.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1.  set following parameters to setting.json
   
   "editor.wrappingIndent":  "same"
   "editor.wrappingColumn": 10
2.  input tabs or 2 (or more) spaces and some cjk characters like this
   
   あああああああああああああああ

![screenshot from 2016-08-24 07-58-46](https://cloud.githubusercontent.com/assets/10045065/17912842/4cee9c8c-69d1-11e6-9882-aeed598e6f15.png)

**Comment by alexandrudima** [comment]
I think this got fixed in the meantime:

![kapture 2017-05-30 at 12 12 41](https://cloud.githubusercontent.com/assets/5047891/26578733/644c2c8c-4531-11e7-8112-757c817cc12f.gif)

**Comment by Tyriar** [comment]
@alexandrudima I can't seem to get `editor.wordWrapColumn` working? With the settings:

```js
"editor.wordWrapColumn": 5,
"editor.wordWrap": "wordWrapColumn",
```

I see this:

<img width="1100" alt="screen shot 2017-06-01 at 3 23 58 pm" src="https://cloud.githubusercontent.com/assets/2193314/26703414/6854577e-46de-11e7-9290-661c5609b1cb.png">

**Comment by Tyriar** [comment]
@alexandrudima interestingly it works fine in the one of the other windows:

<img width="954" alt="screen shot 2017-06-01 at 3 32 55 pm" src="https://cloud.githubusercontent.com/assets/2193314/26703675/ae4e97b6-46df-11e7-8943-187992695610.png">

**Comment by alexandrudima** [comment]
@Tyriar This works consistently for me even for untitled files. Is it possible the folder you've opened where the setting does not work has `editor.wordWrap` overwritten by a workspace setting ?

**Comment by Tyriar** [comment]
@alexandrudima doh https://github.com/Microsoft/vscode-docs/blob/31807155896a51f85cfec0e0779dba84d6a19753/.vscode/settings.json#L3
