### ISSUE TITLE
Microsoft Visual Code could not hightlight CSS syntax if the <style> open tag and </style> end tag in same line

### ISSUE THREAD

**Issue by asdf913** [microsoft/vscode#108642]
- VSCode Version: 1.5.0 (system setup)
- OS Version:6.1.7601 (Result of **ver** command)

The file ends with *_vue_* file extensions.
![20201014_1239](https://user-images.githubusercontent.com/2301325/95944272-6caabf00-0e1a-11eb-8538-8096ade51836.gif)

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
Can you please provide a copy/pastable example? Does this reproduce if you disabled all installed extensions?

**Comment by asdf913** [comment]
> Can you please provide a copy/pastable example? Does this reproduce if you disabled all installed extensions?

After I disable [vuejs/vetur: Vue tooling for VS Code.](https://github.com/vuejs/vetur) extension, the syntax of *vue* file is not highlighted.
