### ISSUE TITLE
Latest Insiders Build breaks LaTeX workshop

### ISSUE THREAD

**Issue by noahgaertner** [microsoft/vscode#108671]
- VSCode Version:1.51.0-insider (latest)
- OS Version: Windows 10 for EDU 2004, Feature Experience Pack 120.2212.31.0

Steps to Reproduce:

1. Install Latex Workshop, all dependencies
2. Attempt to compile LaTeX file through the sidebar menu (with something in it obviously) or by editing and saving it
3. Does not compile, even though it will in the current build of normal VS Code and did just prior to the latest update (from last night or this morning afaik) to the insiders build.

Does this issue occur when all extensions are disabled?: Yes/No
N/A
In LaTeX Workshop git issues here: https://github.com/James-Yu/LaTeX-Workshop/issues/2328#issue-721632591

**Comment by chrmarti** [comment]
Thanks for filing the issue with the extension too. Please follow up with their questions first.

**Comment by noahgaertner** [comment]
Fixed by vscode update sometime yesterday
