### ISSUE TITLE
Change the MacOS authentication dialogue image in the 1.50 release notes

### ISSUE THREAD

**Issue by mikehdt** [microsoft/vscode#108692]
- VSCode Version: 1.50
- OS Version: 10.15.7

Steps to Reproduce:

1. Upgrade to VS Code 1.50 and read the release notes

Does this issue occur when all extensions are disabled?: Yes

A simple one, but I would recommend doing _something_ with that "VSCode wants to use your keychain..." image in the 1.50 release notes. When I first saw it, because it's at 1:1 and has no other indications that it's an image -- and coupled with an _actual_ version of the dialogue opening at the same time, I got confused and clicked on it. Silly thing I know, but it might be worth considering to put some kind of watermark or crop the image in some way for "critical" OS dialogue screenshots so that they aren't at least initially mistaken for _real_ system dialogues.

**Comment by RMacfarlane** [comment]
Hey @mikehdt, this is certainly a reasonable request. Sorry I've slept on it, now that we are about to release 1.51, I don't plan to do this
