### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by brianagude** [microsoft/vscode#108686]
Issue Type: <b>Bug</b>

got an error saying typescript crashed 6 times...?

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz (8 x 1200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|. --crash-reporter-id 68696815-f8ec-4eb7-b9eb-c09d07b51f4c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.10
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
auto-close-tag|for|0.5.9
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.5
vscode-liquid-snippets|kil|2.0.1
auto-save|mcr|1.0.3
atom-keybindings|ms-|3.0.9
vsliveshare|ms-|1.0.2902
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
language-liquid|nei|0.1.1
ruby|reb|0.27.0
html5-boilerplate|sid|1.1.1
shopify-liquid|sis|2.3.0
open-in-browser|tec|2.0.0
liquid-snippet-include-detection|tsh|0.11.0
vscode-ruby|win|0.27.0
px-2rem|zan|1.2.8

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
