### ISSUE TITLE
command list.select doesn't move focus to the editor in source control

### ISSUE THREAD

**Issue by robertmoura** [microsoft/vscode#108641]
- VSCode Version: 1.50.0
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Focus on the source control list
2. Press space on a file to open it without moving focus (command: "list.selectAndPreserveFocus")
3. Press cmd+down to move focus to the editor (command: "list.select")
4. The focus remains in the source control panel

Note: "list.select" works if the file you select isn't already visible

Does this issue occur when all extensions are disabled?: Yes

**Comment by robertmoura** [comment]
Found the command: "explorer.openAndPassFocus" which solved the issue.

**Comment by robertmoura** [comment]
I found "explorer.openAndPassFocus" to solve this issue in the file explorer but I couldn't find a way to do this in Source Control.

**Comment by robertmoura** [comment]
I found "explorer.openAndPassFocus" to solve this issue in the file explorer but I couldn't find a way to do this in Source Control.

**Comment by isidorn** [comment]
I believe this is as designed. However @joaomoreno would know more, thus forwarding to him
