### ISSUE TITLE
When connecting with Remote-SSH and using "Download" of the file, the file name field becomes blank

### ISSUE THREAD

**Issue by mikuta0407** [microsoft/vscode#108699]
- VSCode Version:  1.50.1
- OS Version: Client: Windows10 2004 (19041.508), Server: Ubuntu18.04.5

Steps to Reproduce:

1. Connect to the server using Remote-SSH
2. In Explorer on the side menu, right-click the file and select "Download".
3. The file name in the server is not retained, and you need to enter a new file name in the save dialog.

Does this issue occur when all extensions are disabled?: Yes/No
Yes (Remote-SSH is enabled because this bug is due to Remote-SSH. No other extensions are installed.)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/83433
