### ISSUE TITLE
UI should make it clear if the DA does not support breakpoint conditions or logpoints

### ISSUE THREAD

**Issue by polinasok** [microsoft/vscode#108632]
The UI allows us to click-set a breakpoint and then do "Edit Breakpoint" and set Expression, Hit Count or Log Message at any point before or during a debug session. However, not all debug adapters support these features. As soon as the debug adapter runs and `supportsXXX` capabilities are received on initialization, it should be clear if these will actually be supported. 

Before the debug session starts, I can hover over the breakpoint and see its details.
![image](https://user-images.githubusercontent.com/51177946/95934554-feb4b800-0d85-11eb-9a2a-50cbd72d70ed.png)

Once debug session starts, breakpoint gets an exclamation point in the middle of it. At first, I thought that meant that the breakpoint was special - i.e. had conditions, but now I am realizing that it means the breakpoint has a problem. If I stop on entry and hover over the breakpoint or if I hover over it while the program is running, I do see "Breakpoints of this type are not supported by the debugger". I can no longer see all of the conditions on hover that I could see before the session started. The error message does not make it clear which of the features are not supported. That would be quite helpful as the debuggers might support different subsets.

![image](https://user-images.githubusercontent.com/51177946/95934901-cc578a80-0d86-11eb-85e9-96bf7d775f0d.png)

If the debug session hits the breakpoint, then none of the hovers are available anymore for any breakpoint,  hit or not. At first I thought this was the only available behavior (see first version of this bug), not realizing that I could get more info if hovering in other conditions. It would be great if the same available information was displayed no matter when you hover over a breakpoint.
![image](https://user-images.githubusercontent.com/51177946/95935006-117bbc80-0d87-11eb-8307-580dedc52547.png)

It would also be great if the unsupported options could be disabled in the UI as unavailable while the debug adapter is running.

**Comment by isidorn** [comment]
What you are saying makes sense, however before a user starts debugging there is no debug adapter so we can not disalow setting log points function breakpoint etc even if they will not be supported - we do not know.

Yes we could disable some functionality while the debug adapter is running. For that I have decided to leave this issue open and assing to the backlog so we potentially tackle this in the future.

**Comment by polinasok** [comment]
To clarify my original request: I am not asking for any modification before the DA runs. I understand that it is impossible and tried to make that clear in the first paragraph of my original post. 

I do think that it is important to make this clear after the DA runs. Disabling functionality for new breakpoints is the the last suggestion I made and would be a cherry on top. Please do take a look at my thoughts in the middle of my original report. Depending on where you are in the program, you might or might not get a hover error message "Breakpoints of this type are not supported by the debugger", but even when you do (not always), it doesn't list any of the details. Is it the hit count that is not supported? The expression? Both? There is no way to tell.

**Comment by isidorn** [comment]
Agree. We should improve this.

**Comment by connor4312** [comment]
> I can no longer see all of the conditions on hover that I could see before the session started... If the debug session hits the breakpoint, then none of the hovers are available anymore for any breakpoint, hit or not.

I will fix this this

> It would also be great if the unsupported options could be disabled in the UI as unavailable while the debug adapter is running.

I don't want to do this, since the fact that one debug type is running does not mean that the user doesn't want other debuggers to be run as well.
