### ISSUE TITLE
Intellisense not working Python

### ISSUE THREAD

**Issue by Sm1dty** [microsoft/vscode#108645]
Issue Type: <b>Bug</b>

My Intellisense stopped working in workspace for python files. Restarted vsCode and machine multiple times and still wont work. 

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.88GB free)|
|Process Argv|--crash-reporter-id e4e982b3-c13f-4abb-93fa-a334c9484593|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
html-snippets|abu|0.2.1
vscode-mysql|for|0.4.0
gc-excelviewer|Gra|3.0.40
ocaml|hac|0.6.43
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.9.114305
remote-wsl|ms-|0.50.0
cpptools|ms-|1.0.1
reasonml-wsl|rai|1.0.39
java|red|0.68.0
vscode-yaml|red|0.11.1
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2

(2 theme extensions excluded)

</details>

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
