### ISSUE TITLE
WSL launching 1.50 - "Window has crashed"

### ISSUE THREAD

**Issue by michaeljackson-rgare** [microsoft/vscode#108608]
- VSCode Version: 1.50
- OS Version: Windows 10 Enterprise 1909 - 18363.1016

Steps to Reproduce:

1.  Install zip file
2.  Launch from WSL with ~/MY_WINDOWS/vscode-2020/bin/code -n ~/MY_SERVER/projectName
3.  Observe VSCode launches
4.  Open any file in project
5.  Observe VSCode crashes, and a Windows popup "Window has crashed"

Does this issue occur when all extensions are disabled?: Yes/No
Yes.  I installed VSCode insiders (1.51 preview), which had no extensions installed.  Same issue.

This issues started immediately after upgrading to 1.50 yesterday.  I resolved the issue by rolling back to 1.49.  I had to reinstall the VSCode Remote extension, but it appears to have fixed the issue.

**Comment by aeschli** [comment]
Does this oalso happen when opening a Windows folder and files? Or only with Remote WSL windows?

https://github.com/microsoft/vscode/wiki/Native-Crash-Issues has more information on how you can collect crash information that you can share it with us

**Comment by michaeljackson-rgare** [comment]
Unfortunately I'm under a deadline and can't break my environment again to test the Remote plugin.  If you can leave this open for a bit I should have some time in 2 weeks.  Thanks.

**Comment by aeschli** [comment]
Closing the issue. I'm happy to reopen if more information is available.
