### ISSUE TITLE
Blocklist for intellisense suggestions

### ISSUE THREAD

**Issue by jonrimmer** [microsoft/vscode#108653]
The Storybook project has recently started exporting hook functions from its `@storybook/addons` modules that shadow the names of the core hook functions exported by `React` project.

The result of this is that VSCode intellisense often suggests importing these hook functions instead of the ones from React, which is almost never what you want:

![image](https://user-images.githubusercontent.com/183786/95963659-dd90ad80-0dff-11eb-81b6-d9bf483e8eff.png)

This is a real nightmare when coding, as often you'll end up importing the wrong one without even noticing, resulting in a error when you run the app.

It would be good if VSCode could provide a mechanism to block particular suggestions, based on their name and source.

**Comment by mjbvz** [comment]
The IntelliSense feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md) with an example of where this would be useful
