### ISSUE TITLE
General Lagginess on Manjaro KDE

### ISSUE THREAD

**Issue by Kayomn** [microsoft/vscode#108612]
Persistent lagginess throughout the whole UI, however the biggest bug bear has to be the mouse event handler, which can take over half a second on the initial scroll event, creating a choppy UI that feels incredibly slow.

This may be an issue with Electron itself, as the slowness seems to be originating from the event loop API.

This issue exists in the insiders build, however scrolling lagginess less-noticeable by default as smooth scrolling is disabled.

- VSCode Version: 1.50
- OS Version: Manjaro Linux x86_64
  * Kernel: 5.4.67-1-MANJARO
  * DE: Plasma 5.19.5 
  * WM: KWin 
  * CPU: Intel i5-7200U (4) @ 3.100GHz 
  * GPU: NVIDIA GeForce 940MX 
  * GPU: Intel HD Graphics 620

Steps to Reproduce:
1. Attempt to scroll up and down in a text document while on Manjaro KDE.

Does this issue occur when all extensions are disabled?: Yes

Developer Tools Profile JSON:
[Profile-20201013T172349.txt](https://github.com/microsoft/vscode/files/5372844/Profile-20201013T172349.txt)

**Comment by deepak1556** [comment]
how is the scroll performance when you run with `--disable-gpu` ?

**Comment by Kayomn** [comment]
Yeah, tho it seems to be slightly less so. Most mouse events seem to be around the 30ms mark according to the profiler.

Attached is the profiler results with `--disable-gpu`
[Profile-20201014T215230.txt](https://github.com/microsoft/vscode/files/5380824/Profile-20201014T215230.txt)

**Comment by Kayomn** [comment]
This issue has since been resolved by a system update.

I'll chalk it down to Nvidia's drivers not playing well with something inside Electron.
