### ISSUE TITLE
using keyboard shortcut to copy selected text in large file is not working

### ISSUE THREAD

**Issue by LambdaAlpha** [microsoft/vscode#108658]
Issue Type: <b>Bug</b>

open a large file

select some text

ctrl + c to copy

expected:

selected text is copied

actual:

selected text is not copied

ps:

using context menu to copy selected text in large file is working.

ctrl + c to copy selected text in small file is working.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:01:33.073Z)
OS version: Linux x64 5.4.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3959)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (0.51GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 5e3ad1b5-8b44-4b8c-96be-62ec7aff55c4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.37.1
gitlens|eam|10.2.2
vscode-powertools|ego|0.61.0
vscode-highlight|fab|1.4.1
code-runner|for|0.11.1
vscode-pull-request-github|Git|0.20.1
path-autocomplete|ion|1.15.0
vscode-insertdatestring|jsy|2.3.0
language-haskell|jus|3.3.0
intellij-idea-keybindings|k--|0.2.41
Kotlin|mat|1.7.1
vscoq|max|0.3.2
git-graph|mhu|1.26.0
vscode-filesize|mkx|2.1.4
vscode-language-pack-zh-hans|MS-|1.50.2
hexeditor|ms-|1.3.0
color-highlight|nau|2.3.0
unicode-latex|oij|1.1.2
text-power-tools|qcz|1.16.0
highlight-words|rsb|0.1.4
partial-diff|ryu|1.4.1
dumb-copy-paste|she|1.0.1
vscode-fileutils|sle|3.0.1
vscode-json-stable-stringify|Tra|1.2.0
org-mode|vsc|1.0.0
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by rebornix** [comment]
@LambdaAlpha can you run "Toggle Keyboard Shortcut Troubleshooting" from Command Palate and then try `ctrl+c` again, then share the log from outputs channel?

**Comment by LambdaAlpha** [comment]
[keyboard-shortcut.log](https://github.com/microsoft/vscode/files/5478844/keyboard-shortcut.log)
@rebornix

**Comment by rebornix** [comment]
From the log, `ctrl+c` is hijacked by extension `shepelevstas.dumb-copy-paste`.

```
[2020-11-03 09:28:40.476] [renderer1] [info] [KeybindingService]: \ From 12 keybinding entries, matched dumb.copy, when: editorTextFocus, source: built-in extension shepelevstas.dumb-copy-paste.

```
