### ISSUE TITLE
Create and manage collections of extensions

### ISSUE THREAD

**Issue by nauben** [microsoft/vscode#108655]
I couldn't find an existing issue for this, but probably I just overlooked:

As working with many extension-packages simultaneously can get confusing fast and there may occur compatibility issues between specific extensions, it could prove to be very useful to save an environment/collection/set of extensions. When selected, the included extensions automatically turn active, all others inactive. 

As I am just a beginner at programming, comments on this from veterans are deeply welcomed.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/105342
