### ISSUE TITLE
Format on Save does not work Js and Jsx after updating to 1.50

### ISSUE THREAD

**Issue by nelsonx73** [microsoft/vscode#108601]
Hello,
After applied the update 1.50 the "Format on Save" stopped to work properly.
Can you please help?

Thank you!

**Comment by nelsonx73** [comment]
I found a similar post about this error.:  no format on paste/save on v 1.50.0 #108365.   Applying the solution solved the error.

RanSatious commented 4 days ago
got the same issue
resolved by adding "editor.defaultFormatter": "esbenp.prettier-vscode" to settings.json

**Comment by xieyezi** [comment]
@nelsonx73 
nice! thank you!
