### ISSUE TITLE
Offer to open workspace in root even when telemetry has been disabled

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#108669]
Issue Type: <b>Bug</b>

1. Create a folder containing a single workspace file XYZ.code-workspace
2. Use VS Code to open the folder.

If `"telemetry.enableTelemetry": false` then you **won't** get the expected notification:

![image](https://user-images.githubusercontent.com/6726799/96019219-236f6500-0e44-11eb-820d-3c91b5879fc8.png)

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
Yes, intentional because we need a service that scans root files to be enabled and this one is tied to telemetry. But leaving open as feature request to support.

**Comment by bpasero** [comment]
**Verification:** https://github.com/microsoft/vscode/issues/108669#issue-721615354
