### ISSUE TITLE
Cannot import methods from classes 

### ISSUE THREAD

**Issue by kunal3210** [microsoft/vscode#108644]
Issue Type: <b>Bug</b>

In python when i use the following import statement

### from kivy.properties import NumericProperty, BooleanProperty

It gives me an error as

No name 'NumericProperty' in module 'kivy.properties'
No name 'BooleanProperty' in module 'kivy.properties'

This this is just the case for VScode, because when checked in Pycharm the code works fine.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18362

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
