### ISSUE TITLE
Debugging Electron app from VSCode with using a graphics tablet causes input issues.

### ISSUE THREAD

**Issue by Flairieve** [microsoft/vscode#108630]
Issue Type: <b>Bug</b>

I was told to report this issue here from the Electron github even though this probably has nothing to do with vscode.
When trying to debug my Electron app, my Electron app has input issues with my graphics tablet though only when debugging it. When I build and launch there is no issues with the inputs on my Electron app.
https://github.com/electron/electron/issues/25850

Snippet of launch configuration on the Electron app:
```
{
        "name": "Debug Main Process",
        "type": "node",
        "request": "launch",
        "cwd": "${workspaceRoot}",
        "runtimeExecutable": "${workspaceRoot}/src/node_modules/.bin/electron",
        "windows": {
          "runtimeExecutable": "${workspaceRoot}/src/node_modules/.bin/electron.cmd"
        },
        "program": "${workspaceRoot}/src/electron.js",
        "protocol": "inspector",
        "outputCapture": "std"
      },
      {
        "name": "Debug Renderer Process",
        "type": "pwa-chrome",
        "request": "launch",
        "sourceMaps": false,
        "runtimeExecutable": "${workspaceRoot}/src/node_modules/.bin/electron",
        "windows": {
          "runtimeExecutable": "${workspaceRoot}/src/node_modules/.bin/electron.cmd"
        },
        "runtimeArgs": [
          "${workspaceRoot}/src/electron.js",
          "--remote-debugging-port=9222"
        ],
        "webRoot": "${workspaceRoot}"
      }
```
The code having problems on the Electron app:
```
document.addEventListener('mouseup', function() {
console.log('mouseup')
})

document.addEventListener('mousedown', function() {
console.log('mousedown')
})
```

Expected results:
I should be able to detect mouse up and mouse down when using a graphics tablet on my Electron app.

Actual results:
Randomly the mouse up and mouse down events are called when trying to use my graphics tablet while debugging the Electron app. Though it works completely on a built Electron app.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3199)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.24GB free)|
|Process Argv|--crash-reporter-id 42982bb0-7699-43a6-83a9-a4ec4dcf2308|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-checkbox|bie|0.1.3
better-toml|bun|0.3.2
vscode-firefox-debug|fir|2.9.1
auto-using|Fud|0.7.15
discord-vscode|icr|4.0.0
vscode-json5|mrm|1.0.0
csharp|ms-|1.23.3
vsliveshare|ms-|1.0.2902
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
lua|sum|0.21.2
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Thanks for the report. Does this happen if you run the electron process directly without going through the debugger? i.e. if you manually run `./src/node_modules/.bin/electron src/electron.js`

**Comment by Flairieve** [comment]
I manually ran the command into powershell on VSCode and the same issue occurs.

**Comment by connor4312** [comment]
Okay, thanks for the info. I think this is pretty decisive evidence that the issue is not related to VS Code; I'd recommend following back up with the Electron follks with that information.
