### ISSUE TITLE
Right Click #ffffff hex colors or square brings up color pallet in PHP and HTML files

### ISSUE THREAD

**Issue by soljohnston777** [microsoft/vscode#108687]
Right Click #ffffff hex colors or a square that brings up color pallet (like in the inspector in web browsers) in .PHP, .JS, and .HTML files.  

I know this automatically happens in CSS files, but sometimes I like to do everything in only a PHP, Javascript, or html files when testing things.

**Comment by roblourens** [comment]
You are asking for this feature in html and php files as a feature request right?

**Comment by soljohnston777** [comment]
Yes
