### ISSUE TITLE
Command + Tab - is not showing last active window

### ISSUE THREAD

**Issue by vijayakumarbathini** [microsoft/vscode#108650]
When using command + Tab option in Mac - VS code is opening with different workspace than last visited workspace

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open VSCode instances with multipile workspaces 
2.Use command + Tab to switch between pages

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
Is `Command-Tab` a macOS global keyboard shortcut?
