### ISSUE TITLE
Find in selected text

### ISSUE THREAD

**Issue by erf** [microsoft/vscode#108617]
I would like to select some text, then do a Find in that selected text.

**Comment by rebornix** [comment]
Please provide more information of VS Code version, OS, and also extensions you are using.

**Comment by erf** [comment]
Visual Studo Code Version: 1.50.0

OS: macOS

Extensions:
Dart-Code.dart-code
Dart-Code.flutter
dbaeumer.vscode-eslint
denoland.vscode-deno
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
esbenp.prettier-vscode
Kasik96.swift
ms-azuretools.vscode-docker
PKief.material-icon-theme
vknabel.vscode-apple-swift-format
vscodevim.vim

**Comment by erf** [comment]
It seem there already is an option for this `Auto Find In Selection`. Thanks for a great editor!
