### ISSUE TITLE
Support for Xtext-issue-style links (line number & column) for links inside the terminal

### ISSUE THREAD

**Issue by MaximilianKoestler** [microsoft/vscode#108659]
## Feature Description
Implement support for opening links from the command line that appear as e.g.
```
src/main.mydsl line : 30 column : 4
```
Currently, when clicking the link in the terminal, vscode jumps to the file but not to the line and column.

It should be possible to implement this rather trivially by extending the regex in [`terminalValidatedLocalLinkProvider.ts`](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/terminal/browser/links/terminalValidatedLocalLinkProvider.ts#L36-L43).

## Motivation
[Xtext](https://www.eclipse.org/Xtext/index.html) is a framework to build DSL processors. Because you can build a language server for your DSL around it, I assume that using it together with vscode is not uncommon.

When using Xtext-based tools on the integrated terminal command line in vscode, it will format *issues* (errors and warnings) as such (Windows example):
```
ERROR:Something has gone wrong. (file:/C:/SomeDir/src/main.mydsl line : 30 column : 4)
```
The code that formats the issues in such a way can be found here: https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext/src/org/eclipse/xtext/validation/Issue.java#L245

It would be really great if vscode would support detecting these kinds of line and column numbers to jump directly to the issue.

If this this feature fits the scope of vscode, I would be happy to provide a PR.

**Comment by Tyriar** [comment]
I don't think this is popular enough to make it into the core, you can now implement an extension that adds links to the terminal though. Check out the terminal link provider API for more info.

**Comment by MaximilianKoestler** [comment]
@Tyriar Thanks for pointing me at the terminal link provider API. With that, building an extension that does what I want was in fact very easy.

If anyone else stumbles over this issue while searching for a solution, you can try [Xtext Links](https://marketplace.visualstudio.com/items?itemName=MaximilianKoestler.xtext-links) on the Marketplace.
