### ISSUE TITLE
TSX Support Not Working For Some .tsx Files

### ISSUE THREAD

**Issue by georgezlei** [microsoft/vscode#108624]
After updating VSCode, All JSX tags in .tsx files are all displayed as errors in my editor. Meanwhile, Webpack can still work without error.

An example of the errors, `<div>` is recognised as an error and the error message reads `cannot find name 'div'. ts(2304)`. It seems that the parser interprets `<...>` as type casting instead of JSX tag even though the files name ends with .tsx.

All such error messages will disappear if I change the file name extension to `.jsx`.

I updated both August 2020 update and September 2020 update together. The error may occur from August 2020 update.

### Steps to reproduce:

1. Open an empty folder
2. Run command `npx create-react-app my-app --template typescript`
3. Open file `my-app/src/App.tsx`. The file should look good.
4. Create another file under `src` folder and name it as `App1.tsx`.
5. Copy everything in `App.tsx` into `App1.tsx`. You should see the error messages. (A mystery here is that the error messages won't show if you use command line `cp App.tsx App1.tsx`.)

**Comment by mjbvz** [comment]
Works fine for me. Please fill in the issue template to provide more info

/needsMoreInfo

**Comment by georgezlei** [comment]
The issue is no longer reproducible after resetting the ESLint extension.
