### ISSUE TITLE
Search feature when using workspace is searching folders that should be ignored

### ISSUE THREAD

**Issue by Oscar-21** [microsoft/vscode#108606]
![image](https://user-images.githubusercontent.com/21151259/95872713-1d429100-0d3d-11eb-9a09-2ba451cbb87b.png)

Steps to Reproduce:

1. In a workspace with multiple projects search any string
2. Results are being returned from .git folder and .gitignore file
3. Search.exclude is set in workspace/User/and individual projects like so:
![image](https://user-images.githubusercontent.com/21151259/95875581-2a14b400-0d40-11eb-9e2d-9eedc879a1ed.png)

This only happens when I am searching while using a workspace. If I open any of the projects on their own I do not have this issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Please check these tips https://github.com/microsoft/vscode/wiki/Search-Issues#search-including-too-many-results
