### ISSUE TITLE
List extensions in a file in user folder

### ISSUE THREAD

**Issue by giggio** [Microsoft/vscode#10860]
I want to maintain all my configuration in a git repo, and this includes my extensions. It already stores my keybindings, settings and snippets, as they are in files in a user folder, which I commit to git. But VSCode does not list the extensions in any file in this folder.
I want you to list them in a file, and use this file to restore the extensions when VS Code opens. This way I can always control what is going on with my environment.
I already do this for other editors, like Vim, and environments like Bash and Powershell.

Migrated from UserVoice: https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/15319209-list-extensions-in-a-file-in-user-folder

**Comment by joaomoreno** [comment]
Might wanna give this extension a try:

https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by giggio** [comment]
@joaomoreno No, that does not help at all. I don't want some cryptic extension saving my info. I want to have dot files config persisted and versioned using Git, and available to others using Github. And I don't want to depend on the extension to define what and how I save my info.
I have this with other text editors, why not with VS Code? This is a **common pattern** on the Linux community.
See an example here for VSCode:
https://github.com/giggio/vscodefiles
See here for Vim:
https://github.com/giggio/vimfiles
No an editor, but still, for powershell:
https://github.com/giggio/poshfiles

**Comment by giggio** [comment]
Also, please discuss before closing issues, it is not polity at all. This is **not** good open source etiquette.

**Comment by joaomoreno** [comment]
Baking this specific feature into the product is simply [not in our 12 month plan](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#ongoing-issue-management), thus I closed the issue.

We can still discuss it, even after closing it; people can still vote on it and comment on it if they feel passionate enough about it as you.

Still, the fact remains: this can be achieved with a few extensions already in the marketplace. They're not even cryptic at all, they are open source just as VS Code. Have you given them a try? What are they lacking?

**Comment by giggio** [comment]
Ok, I did not know about how you handle issues, but be aware that closing issues signals you are not going to work on them, not that they are not in your 12 month plan. It is unusual.

One scenario that I use often is to use git submodules in my dot files, you can see that on my Posh files, and on my Vim files. I cannot gather other peoples work on other git repos using an extension.
Also, I am not in control with what I want to save, the extension creator is. A simple edit on my .gitignore and something is in or out.
And an extension does not version the code the way I would, it uses some gist to manage it, in a format that is appropriate to itself, not people. It is hard to other people to look at it, clone, etc. There is a whole culture around dot files and taking (forking) from other people's dot files, and contributing back. You can't do that with that extension.
I could go on and on, we are talking about git freedom versus a closed extension.
Why not just gather all the user info a single directory and let them choose how they want to roam this info. If it is an extension, fine, but what if it is not? This has always been the Linux mindset, and I feel it is not being respected here.

**Comment by joaomoreno** [comment]
It just doesn't sound _Linuxy_ to build this into Code itself, when it could be done on the outside. Each tool for its task.

You could maintain that list yourself in such a `~/.extensions` file, just like you'd do with any other tool:

```
rebornix.Ruby
vscodevim.vim
donjayamanne.python
```

And you could restore them with:

```bash
cat ~/.extensions | sed 's/^/--install-extension=/' | xargs code
```

You could even alias `code` to always running that command before it executes `code` itself.

**Comment by giggio** [comment]
I don't need VSCode to do anything for me but to keep the user info in only one place. Extensions are user specific artifacts, as are keybindings, snippets and settings, which currently are stored together. But, for whatever reason, extensions go to `$HOME/.vscode/extensions`, while all the rest goes somewhere else.
Why not just keep every artifact under `$HOME/.vscode`?
This way, I could manage the whole thing in one repo. VSCode is the only tools making me do it with two repos.

**Comment by joaomoreno** [comment]
You'll wanna follow #3884 for that.
