### ISSUE TITLE
Regression: `vscode.tasks.executeTask` does not work if Node package is in a subfolder

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#108610]
Opened based on https://github.com/microsoft/vscode-docker/issues/2393.

- VSCode Version: 1.51.0-insider, commit 605bc4ec
- OS Version: Win10 10.0.19042.508

Steps to Reproduce:

1. Install the latest Docker extension [nightly build](https://github.com/microsoft/vscode-docker/issues/1408), or at least 1.7.0
1. Create a Node express app in a subfolder and open the parent folder in VSCode
1. Add Dockerfiles to workspace, Node.js, etc.
1. Right click the Dockerfile in the subfolder and click "Build Image"

Expected:
The `docker-build` task in .vscode/tasks.json executes

Actual:
Nothing happens, but I see this error if I'm debugging the Docker extension in the outer VSCode window:
```
rejected promise not handled within 1 second: TypeError: Cannot destructure property 'name' of '(intermediate value)' as it is null.
 extensionHostProcess.js
stack trace: TypeError: Cannot destructure property 'name' of '(intermediate value)' as it is null.
	at Object.findPreferredPM (c:\Users\bwater\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\npm\dist\npmMain.js:14:49429)
	at async v (c:\Users\bwater\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\npm\dist\npmMain.js:1:12156)
	at async A (c:\Users\bwater\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\npm\dist\npmMain.js:1:14173)
	at async E (c:\Users\bwater\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\npm\dist\npmMain.js:1:13606)
	at async c:\Users\bwater\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\npm\dist\npmMain.js:1:12604
	at async y (c:\Users\bwater\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\npm\dist\npmMain.js:1:12310)
 extensionHostProcess.js
```

I think this is a regression due to https://github.com/microsoft/vscode/commit/f8c0e3b612733b1f78d354556e8767a85f50ab87. When I change the setting `npm.packageManager` to `npm`, the issue goes away. I can then change it back to `auto` and it stays gone. However, if I restart VSCode with `auto` the issue returns.

My guess is that `which-pm` is returning null because it does not find anything in the root workspace folder (the express app is in a subfolder), and then [this](https://github.com/microsoft/vscode/blob/f8c0e3b612733b1f78d354556e8767a85f50ab87/extensions/npm/src/preferred-pm.ts#L68) line fails to destructure.

**Comment by bwateratmsft** [comment]
@alexr00 @shivangg FYI

**Comment by bwateratmsft** [comment]
Possibly related issue: the "NPM Scripts" window just has a loading bar forever:
![image](https://user-images.githubusercontent.com/36966225/95883569-17eb4380-0d49-11eb-812c-056a391913c1.png)

**Comment by alexr00** [comment]
Already fixed with https://github.com/microsoft/vscode/commit/5742413347d0543b4f2164aa78e205c6d271d5a0

**Comment by bwateratmsft** [comment]
Can confirm this is now working in today's Insiders build. Thank you @alexr00!
