### ISSUE TITLE
vscode freezen

### ISSUE THREAD

**Issue by ycj** [microsoft/vscode#108696]
Issue Type: <b>Bug</b>

vscode is installed in the host windows 10 pc.   It is freezed when i login from guest machine by remote desktop,  It also keep the same state when i logout from guest pc.   It return to normal state after I restart vscode.

                                                                                                                                                                               Thanks.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (11.04GB free)|
|Process Argv|--crash-reporter-id 30670e9d-165b-4916-b579-797c5456f706|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
leek-fund|gis|1.6.4
gitignore|mic|1.0.1
vscode-docker|ms-|1.6.0
vscode-language-pack-zh-hans|MS-|1.50.2
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.9.114305
vscode-pylance|ms-|2020.10.1
remote-containers|ms-|0.145.0
remote-ssh|ms-|0.55.0
remote-wsl|ms-|0.50.0
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.1
vetur|oct|0.28.0
erlang|pgo|0.6.5
vscode-yaml|red|0.11.1
cmake|twx|0.0.17

</details>

**Comment by chrmarti** [comment]
Could you attach a screenshot of the frozen VS Code window?

**Comment by deepak1556** [comment]
Can you check if the issue happens with our [exploration builds](https://az764295.vo.msecnd.net/exploration/3c1b4bacbef4ab788f72059f56ef53e9aa7923bc/VSCodeSetup-x64-1.52.0-exploration.exe)
