### ISSUE TITLE
Typescript "Cannot redeclare block scope variable" problem

### ISSUE THREAD

**Issue by akylc** [microsoft/vscode#108633]
Issue Type: <b>Bug</b>

In the same folder, two ts files with different names have two constants or variables with the same name, and vscode will prompt "Cannot redeclare block range variables". This problem has always existed, if it was originally designed to be like this , I hope to add an option, because the environment where ts is used is not necessarily a module environment, it may be an independent single file ts.

Hope to fix this problem

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/14279
