### ISSUE TITLE
Open VS code on SSH session

### ISSUE THREAD

**Issue by Jawell** [microsoft/vscode#108678]
- VSCode Version: 1.49.3
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1) Connect to KVM by ssh
2) code -n PATH
3) Connect to KVM by VNC

I have KVM on my machine (by virt-install). I need to connect by SSH to my KVM and I need to open VS Code using `code -n PATH` (where PATH - my path to project). When I disconnected SSH and connected to KVM by VNC I don't have opened VS code window with project.

Does this issue occur when all extensions are disabled?: Yes

`code --verbose`
[59204:1014/222659.810981:ERROR:browser_main_loop.cc(1473)] Unable to open X display.
/dev/fd/3: No such file or directory
Server response

**Comment by chrmarti** [comment]
Maybe `DISPLAY` is not set?
