### ISSUE TITLE
Appearance settings should be specific to each window

### ISSUE THREAD

**Issue by Wintaru** [microsoft/vscode#108661]
Increasing/decreasing the zoom affects all VS Code windows in Debian Stretch. If I want two windows (say one in a 4K monitor and another in a 1080 monitor) I can't increase the zoom in one while decreasing the zoom in another.

**Comment by bpasero** [comment]
You can configure a zoom in the workspace settings per window as a workaround. The standard keybindings for zooming will apply on user settings though, impacting all windows.
