### ISSUE TITLE
cnnnot input chinese and diplay in integrated terminal

### ISSUE THREAD

**Issue by notadalao** [microsoft/vscode#108651]
Issue Type: <b>Bug</b>

#include <stdio.h>
#include <cstdlib>
#include <cstring>
int main()
{
	char str[100];
	scanf("%s", str);
	printf("正文shi*%s*", str);
	return 0;
}

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.79GB free)|
|Process Argv|--crash-reporter-id 07a380a4-b411-43e1-a9d5-1e93a7104b0a|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.1
vscode-language-pack-zh-hans|MS-|1.50.2
cpptools|ms-|1.1.0-insiders
material-theme|zhu|3.9.3

(1 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
