### ISSUE TITLE
 ctrl+enter shortcut key is not working for git commit

### ISSUE THREAD

**Issue by g5becks** [microsoft/vscode#108674]
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:01:33.073Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-7642-generic

Steps to Reproduce:

press ctrl + shift + g to commit
enter a commit message
press ctrl + enter

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by joaomoreno** [comment]
1. Press <kbd>F1</kbd>, then `Preferences: Open Keyboard Shortcuts`
2. Search for `Ctrl+Enter`

You have some other command assigned to that keybinding which is executing when you press Ctrl Enter. Find it!

**Comment by g5becks** [comment]
I removed all the other keyboard shortcuts that would conflict before submitting this issue.

In doing so, I may have actually removed the keybinding for the correct command by mistake. Right now it is mapped to scm.acceptInput, Is that the correct command?

**Comment by joaomoreno** [comment]
You can right click the command in that UI and choose `Reset Keybinding`.
