### ISSUE TITLE
 1.50.1 Update fail

### ISSUE THREAD

**Issue by lr00429** [microsoft/vscode#108697]
Issue Type: <b>Bug</b>

When updating VS Code to  1.50.1 on Surface Pro X running Windows build 20231.1000, The update fails and deletes code.exe requiring new install

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:10:09.126Z)
OS version: Windows_NT arm64 10.0.20231

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Microsoft SQ1 @ 3.0 GHz (8 x 1670)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.47GB (9.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
vscode-html-css|ecm|0.2.3
python|ms-|2020.8.109390
salesforce-vscode-slds|sal|1.3.0
salesforcedx-vscode|sal|50.1.0
salesforcedx-vscode-apex|sal|50.1.0
salesforcedx-vscode-apex-debugger|sal|50.1.0
salesforcedx-vscode-apex-replay-debugger|sal|50.1.0
salesforcedx-vscode-core|sal|50.1.0
salesforcedx-vscode-lightning|sal|50.1.0
salesforcedx-vscode-lwc|sal|50.1.0
salesforcedx-vscode-visualforce|sal|50.1.0
html-preview-vscode|tht|0.2.5

</details>

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by lr00429** [comment]
I have tired disabling it and the update failed again. I have since downloaded the new updated setup file rather then trying to update again. However here are the errors that I get trying to update.
[vscode-inno-updater-1602892025.log](https://github.com/microsoft/vscode/files/5394723/vscode-inno-updater-1602892025.log)
![Screenshot 2020-10-16 194940](https://user-images.githubusercontent.com/62064675/96323118-d6c58e80-0fe9-11eb-92cf-a1eae1bc20a5.png)

**Comment by joaomoreno** [comment]
This error dialog shows that the setting wasn't properly set. Please make sure it is properly set and restart your machine to be sure. This dialog won't appear at all if windows background updates are disabled.
