### ISSUE TITLE
package.json dependency completion: npm command not used on windows

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#108605]
For  package.json dependency completion and hivers we either use the npm command or make a HTTP access.
On Windows, the npm command no longer is used.

To verify, hover over `@types/react-select`
```
"devDependencies": {
    "@types/react-select": "^2.0.15"
}
```
- the npm command will show `3.0.22`
- `api.npms.io` will show 1.2.6 due to a bug in api.npms.io (reported as https://github.com/npms-io/npms/issues/42#issuecomment-707136902)

**Comment by vaindil** [comment]
It would be very helpful if this were an option because of the aforementioned bug with the npms API. This hover functionality is currently completely useless because of that bug, so the option to force it to use the npm command would be very helpful.

**Comment by waynebloss** [comment]
I'm getting this problem on Linux (Manjaro).

The latest version of [react-admin](https://www.npmjs.com/package/react-admin) is `3.10.1` as of today. VS Code is showing me `3.8.5`

![image](https://user-images.githubusercontent.com/623736/99462525-daf30d80-2901-11eb-849c-433db73a4d4b.png)

**Comment by csvn** [comment]
There is a commit that closed this issue, but I am curious if this was included in the recent release of VSCode. I still have the issue as well.

**Comment by aeschli** [comment]
@waynebloss As explained earlier, we use the  `npm` command if we find it on the PATH, or use https://npms.io/.
https://npms.io/ still has the issue open about their index not up-to-date: https://github.com/npms-io/npms/issues/42#issuecomment-707136902

` 3.8.5` is what https://npms.io/ returns. So you want to check whether npm is installed and on the path of the shell that was used to run VSCode (you can also check that with the integrated terminal)

**Comment by Knagis** [comment]
In my case I have `npm` in path and still I get wrong versions.

![image](https://user-images.githubusercontent.com/8700285/99714039-bf2c6a80-2aad-11eb-97ed-090218472ade.png)

any suggestions how to check why vscode might not be able to find npm?

```
Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z (1 mo ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20175
```

**Comment by aeschli** [comment]
The issue that npm was not used on WIndows got fixed (this issue is closed). I just verified that it works for me on Windows and Linux.

Can you open the integrated terminal and run `npm view webpack version` ?

**Comment by Knagis** [comment]
![image](https://user-images.githubusercontent.com/8700285/99794765-58ea2b00-2b33-11eb-9e91-a9bdcd71dc48.png)

**Comment by Knagis** [comment]
The issue was rather simple 🤦‍♂️ 

Needed to update VSCode... 1.51.1 now shows it correctly.

Sorry about this, usually VSCode nags me about the update, this time I might have closed the notification without noticing it. Explicit Help -> Install Update and now it shows correct version.
