### ISSUE TITLE
Applying app udpates overwhelm my workstation

### ISSUE THREAD

**Issue by wagnerone** [microsoft/vscode#108663]
Issue Type: <b>Bug</b>

I use a modern workstation (8 core, SSD, etc.). Each time I update the VSC application (daily at least as I'm on the Insiders track), my workstation is brought to its knees for a couple of minutes.

I basically have to start a VSC app update and walk away for a while because my laptop becomes overwhelmed and unusable. It's kind of impressive actually how bad it gets. The CPU goes to max and the fans go haywire.

It seems the app update process triggers trustd and trustd goes bonkers for those couple of minutes each update.

I'm a bit compulsive about updating my apps and update many applications daily. I've not witnessed this situation with anything except VSC.

VS Code version: Code - Insiders 1.51.0-insider (bc20f53838c75c0ec473b2a1afa7423cc5bcf7ab, 2020-10-13T17:28:21.414Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (0.61GB free)|
|Process Argv|-psn_0_20472709 --crash-reporter-id 212a1510-41cd-4257-9265-09b65bc1f6a6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-quick-select|dba|0.2.9
githistory|don|0.6.12
xml|Dot|2.5.1
gitlens|eam|10.2.2
vscode-great-icons|emm|2.1.57
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
terraform-autocomplete|erd|0.0.8
auto-close-tag|for|0.5.9
vscode-pull-request-github|Git|0.20.1
todo-tree|Gru|0.0.183
terraform|has|2.2.3
mysql-syntax|jak|1.3.1
vscode-peacock|joh|3.8.0
bash-ide-vscode|mad|1.11.0
rainbow-csv|mec|1.7.1
vscode-apache|mrm|1.2.0
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.6.0
python|ms-|2020.9.114305
remote-containers|ms-|0.145.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.0
vscode-remote-extensionpack|ms-|0.20.0
vsliveshare|ms-|1.0.2902
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.3.0
vscode-xml|red|0.13.0
vscode-yaml|red|0.11.1
partial-diff|ryu|1.4.1
code-spell-checker|str|1.9.2
vscode-terminal-here|Tyr|0.2.4
vscode-jumpy|wma|0.3.1
json|Zai|2.0.1
propertylist|zho|0.0.2
material-theme|zhu|3.9.3

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
I would reach out to trustd and ask them what's happening. Other than that, I suggest to file an issue to Electron, since the entire update process on macOS is run by Electron itself.

Can you share some details on what processes exactly go berserk? Maybe a screen recording along with a process monitor sorted by CPU percentage?
