### ISSUE TITLE
Find box should close on after creating selections

### ISSUE THREAD

**Issue by erf** [microsoft/vscode#108616]
I would like the Find box to close after i press `Option+Enter` or `Shift+CMD+L` to create selections of the matched text.

**Comment by rebornix** [comment]
Please provide more information of VS Code version, OS, and also extensions you are using.

**Comment by erf** [comment]
Visual Studo Code Version: 1.50.0

OS: macOS

Extensions:
Dart-Code.dart-code
Dart-Code.flutter
dbaeumer.vscode-eslint
denoland.vscode-deno
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
esbenp.prettier-vscode
Kasik96.swift
ms-azuretools.vscode-docker
PKief.material-icon-theme
vknabel.vscode-apple-swift-format
vscodevim.vim
