### ISSUE TITLE
Syntax highlighting error for Perl

### ISSUE THREAD

**Issue by donsequitur** [microsoft/vscode#108609]
Issue Type: <b>Bug</b>

```
    for my $comp_site_config (@comp_sites_configs) {
        my ($cmp_j_id, $cmp_abbrev, $cmp_url) = split /\|/, $comp_site_config;
        my ($cmp_journal_id) = $c->db->selectrow_array(qq(SELECT journal_id FROM Journal WHERE j_id = ?),undef, $cmp_j_id + 0);
        push @cmp_sites, {abbrev => $cmp_abbrev, journal_id => $cmp_journal_id};
    }
```

![image](https://user-images.githubusercontent.com/9997705/95882100-4bc56980-0d47-11eb-94e1-da3e9318b72b.png)

syntax highlighting breaks at the closing slash of the regex in the first argument of the split.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3999)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (0.43GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+CentOS8/opt/ejp/docker --remote=wsl+CentOS8 --crash-reporter-id ab624221-dd85-4727-8c1e-19b2307c1e21|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS8|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3998)|
|Memory (System)|12.44GB (3.33GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS8|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3998)|
|Memory (System)|12.44GB (3.33GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
mojolicious|kra|1.9.0
remote-containers|ms-|0.145.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.0

</details>

**Comment by donsequitur** [comment]
Hi,

This is not caused by the Mojolicious extension.  The auto-diagnostic info may indicate the syntax from that extension was active, but I have subsequently tested with that extension disabled and the normal Perl syntax enabled for the file and the problem is still present.

**Comment by donsequitur** [comment]
Hello,

Here is an example in a fresh file with extension disabled.

![image](https://user-images.githubusercontent.com/9997705/95885011-c643b880-0d4a-11eb-883a-6676fb289fbc.png)

**Comment by gjsjohnmurray** [comment]
@donsequitur sorry for my false assumption.

@aeschli is the built-in perl support your domain? Please reopen, and redirect if not your responsibility.

**Comment by alexr00** [comment]
Duplicate of the this upstream bug: https://github.com/textmate/perl.tmbundle/issues/28
