### ISSUE TITLE
Maximized panel brings artifacts from editor along with it

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#108629]
![recording (9)](https://user-images.githubusercontent.com/8586769/95927732-70840600-0d74-11eb-864e-2997f243e2d5.gif)

**Comment by JacksonKearl** [comment]
@rzhao271 I believe you were working in this area otherwise cc @bpasero

**Comment by bpasero** [comment]
Looks bad, moving to October. Not sure if this is a regression?

**Comment by rebornix** [comment]
@JacksonKearl proved to be actively self hosting the native notebook, good catches.

**Comment by JacksonKearl** [comment]
Easy to selfhost when it's so helpful!
