### ISSUE TITLE
Extension `Configuration Editing` cannot format  `main.c`

### ISSUE THREAD

**Issue by SmartElec** [microsoft/vscode#108638]
- VSCode Version: 1.50.0
- OS Version:Win10 2004

Steps to Reproduce:

1.format c file with key `shift+alt+f`
2.tips Extension `Configuration Editing` cannot format  `main.c`
3.but another PC can format it

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Did you maybe change the language mode of the file? What is the programming language shown in the statusbar (lower right)? I would expect it to show `C`:
![image](https://user-images.githubusercontent.com/9205389/95954079-0ebaaf00-0dfb-11eb-8a2c-8430c78bedf1.png)

**Comment by SmartElec** [comment]
`Ln714,Col 6 Space:4 UTF-8 LF C Linux`

**Comment by jrieken** [comment]
Looks like you have configured the `Configuration Editing` extension as default formatter. Check the `editor.defaultFormatter` setting and unset its value

**Comment by SmartElec** [comment]
thanks,my `editor.defaultFormatter` is config with others
