### ISSUE TITLE
Cannot pick tabs vs spaces in notebook

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#108675]
No a "choose intentation type" entry in status bar when editing in a notebook. I have a notebook with tab indentation but it seems theres some global spaces setting that overrides it... even pasting a literal tab charachter inserts spaces :/ 

![recording (10)](https://user-images.githubusercontent.com/8586769/96029154-1c7a2f80-0e0f-11eb-8c34-1a2137f092b2.gif)

**Comment by alexr00** [comment]
False alarm. The status bar entry just moved so much that I didn't see it right away.

**Comment by alexr00** [comment]
Actually, looks like the status bar is really slow to update. I saw it update eventually, but I'm not sure what caused it to finally show the correct thing.

![Recording 2024-02-20 at 16 46 43](https://github.com/microsoft/vscode/assets/38270282/d7b7e4ec-cfae-4c51-a7e0-3181ed774b89)
