### ISSUE TITLE
Context menu actions are always executed twice when clicked on Firefox

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#108621]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Run VS Code web in Firefox
2. Install https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks (from vsix)
3. Create a GitHub issue notebook
4. Insert a code cell, type in some content
5. Right click on the cell container, click "Copy Notebook Cell" from the context menu
6. Right click on the cell container, click "Paste Notebook Cell" from the context menu
7. It inserts two new cells into the document

After some debugging, I found that every action in the context menu is always executed twice, and only in Firefox.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sbatten** [comment]
curious if this reproduces in all menus?

**Comment by bpasero** [comment]
@sbatten it is easy to reproduce and fix seems trivial: https://github.com/microsoft/vscode/pull/109374
