### ISSUE TITLE
Settings sync: before shutdown cannot be async in web

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108647]
A reminder that in `browser` long running shutdown handlers will not work:

https://github.com/microsoft/vscode/blob/d014eb12807b7ab06662c78698052b8686555ab2/src/vs/workbench/services/userDataSync/browser/userDataSyncWorkbenchService.ts#L286-L298

I suggest to move this into a `electron-sandbox` namespace to be clear.

**Comment by sandy081** [comment]
I cannot move just this to `electron-sandbox`, instead I will add web check and add a note that it works only in desktop.
