### ISSUE TITLE
HELP. "The terminal process failed to launch Exit code -1" - VSCODE

### ISSUE THREAD

**Issue by MaximoPedernera** [microsoft/vscode#108628]
When running my project in C ++ (I clarify that the program does not jump any error
 code) but when I want to run it does nothing and in the terminal it says the following:
 
Starting build...
Build finished with error.
The terminal process failed to launch (exit code: -1).

I've been looking all over the internet for the "Exit code: -1" and nowhere does it appear, not on GitHub. Hope someone can help me. Thank you

- VSCode Version: 1.50.0
- OS Version: Windows 10.0.18
![image](https://user-images.githubusercontent.com/72838868/95926662-31b17880-0d93-11eb-81cf-0712899e8cf6.png)

**Comment by meganrogge** [comment]
@MaximoPedernera  please report that issue [here ](https://github.com/microsoft/vscode-cpptools)

**Comment by Tyriar** [comment]
You may also have issues with your task if it's saying it exited immediately.
