### ISSUE TITLE
Improve window.withProgress in status bar to use a static spin icon

### ISSUE THREAD

**Issue by badsyntax** [microsoft/vscode#108657]
- VSCode Version: 1.50.0
- OS Version: MacOS Catalina

Steps to Reproduce:

1. `git clone https://github.com/microsoft/vscode-extension-samples`
2. `cd vscode-extension-samples/progress-sample`
3. `npm install`
4. `code src/extension.ts`
5. change `location: ProgressLocation.Notification` to `location: ProgressLocation.Window`
6. Run the "Launch Extension" launch config
7. Run the extension command `extension.startTask`
8. Note the spinner icon in the statusbar gets reset for every progress

A lot of extensions use the progress API for showing download progress of large binaries, but every time the progress is updated the spinner icon gets reset and this looks pretty bad. 

I expect the spinner icon to not update whenever i call `progress.report()`

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This is a consequence of using codicons inside the text for reporting progress, thus every time the text changes, the icon will start again from its initial state. We have this issue in other places too.

The status bar already makes sure to not update the text if it does not change:

https://github.com/microsoft/vscode/blob/18a6a88ee3b11384a5b7fb2e64ae0ecd29eee2d3/src/vs/workbench/browser/parts/statusbar/statusbarPart.ts#L753-L761

Moving to @jrieken as original author of this progress location.

**Comment by bpasero** [comment]
I think this can be done on the level of the status bar by putting the spin icon into a separate label independent from the progress message.

**Comment by badsyntax** [comment]
Thanks for the fix! I will verify once a new insiders is released.

**Comment by badsyntax** [comment]
Looks good to me!

/verified
