### ISSUE TITLE
Blockchain Platform Tutorial A5.25 does not link

### ISSUE THREAD

**Issue by winf3** [microsoft/vscode#108683]
Hi, I followed the Blockchain Platform Tutorial and everything worked so far.
In Step A5.25 I got an Linker Error:

Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "-m" hinzufügen.
  addon.cc
  x509.cc
  win_delay_load_hook.cc
LINK : fatal error LNK1104: Datei "C:\OpenSSL-Win64\lib\libeay32.lib" kann nicht geöffnet werden. [C:\Users\winre\OneDrive\Dokumente\Blockchain20
20\IBM\Get-started-Example\VSCode-Tutorial\node_modules\fabric-shim\node_modules\@ampretia\x509\build\x509.vcxproj]

Question:
How to install libeay32.lib ?

CPUs | Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 15.87GB (2.58GB free)
Process Argv | --crash-reporter-id 8113c175-09dc-4e4f-b141-b4b84f103b3b
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
go | gol | 0.17.2
ibmcloud-account | IBM | 1.0.3
ibm-blockchain-platform | IBM | 1.0.37
remote-wsl | ms- | 0.50.0
javascript-test-runner | osh | 1.2.1

End of debug log:
warn VSCode-Tutorial@0.0.1 No repository field.
3567 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
3568 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
3569 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
3569 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
3569 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
3569 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
3570 verbose stack Error: @ampretia/x509@0.4.7 install: `node-gyp rebuild`
3570 verbose stack Exit status 1
3570 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
3570 verbose stack     at EventEmitter.emit (events.js:310:20)
3570 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
3570 verbose stack     at ChildProcess.emit (events.js:310:20)
3570 verbose stack     at maybeClose (internal/child_process.js:1021:16)
3570 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
3571 verbose pkgid @ampretia/x509@0.4.7
3572 verbose cwd C:\Users\winre\OneDrive\Dokumente\Blockchain2020\IBM\Get-started-Example\VSCode-Tutorial\Demo-Application
3573 verbose Windows_NT 10.0.19041
3574 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
3575 verbose node v12.16.2
3576 verbose npm  v6.14.4
3577 error code ELIFECYCLE
3578 error errno 1
3579 error @ampretia/x509@0.4.7 install: `node-gyp rebuild`
3579 error Exit status 1
3580 error Failed at the @ampretia/x509@0.4.7 install script.
3580 error This is probably not a problem with npm. There is likely additional logging output above.
3581 verbose exit [ 1, true ]

**Comment by chrmarti** [comment]
This appears to be provided for the Blockchain Platform, please open an issue for them: https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues
