### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Mexicanking1** [microsoft/vscode#108698]
Issue Type: <b>Bug</b>

when I run my code it gives me a web page I did but when I update the visual studio code and run it again, it gives me a different layout of my webpages.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.06GB free)|
|Process Argv|--crash-reporter-id 558ee1e8-a5de-4776-b534-5d892ae12b64|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
docs-images|doc|0.0.9
vscode-firefox-debug|fir|2.9.1
live-html-previewer|hdg|0.3.0
cpptools|ms-|1.0.1
LiveServer|rit|5.6.1

</details>

**Comment by chrmarti** [comment]
Could you attach a screenshot of the problem?
