### ISSUE TITLE
Error when clicking ports status bar item

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#108740]
![image](https://user-images.githubusercontent.com/22350/96134999-b4554780-0efb-11eb-803e-97196c08edb1.png)

**Comment by alexr00** [comment]
Should be fixed by https://github.com/microsoft/vscode/commit/d18f310cfe483fb26014a40b0d5ea3943c9fd448
You shouldn't see anything port forwarding related stuff in WSL. That is caused by Codespaces: https://github.com/github/codespaces/issues/1573
