### ISSUE TITLE
Quoting of "args" value in launch.json is incorrect

### ISSUE THREAD

**Issue by amazingmo** [microsoft/vscode#108775]
- VSCode Version: 1.49.2
- OS Version: Ubuntu 14.04 

Hello @weinand , @int19h ,

I have an issue escaping an argument to a Python module that I want to run.  I would like to achieve:

> python -m behave --tags="not @wip"

Here is the beginning of my .vscode/launch.json:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(py) Finished Behave Tests",
            "type": "python",
            "request": "launch",
            "module": "behave",
            "cwd": "${workspaceFolder}/BehaviouralTests/features",
            "args": [".", "--tags=\"not @wip\""],
            "env":{
                "EXEDIR":"${workspaceFolder}/bin",
                "WORKSPACE":"${workspaceFolder}"
            },
            "preLaunchTask": "Copy to bin"
        },
```

It seems that the space character between the not and the '@' character causes the whole thing to be quoted, such that I get:

> /usr/bin/env /usr/local/bin/python3 /home/me/.vscode-server/extensions/ms-python.python-2020.9.111407/pythonFiles/lib/python/debugpy/launcher 45119 -- -m behave . "--tags=\"not @wip\""

I have tried all manner of escaping the space and the double quotes such that the result is still valid JSON, but none give me the desired:

> --tags="not @wip"

----

Note that I am using the Remote-SSH extension, version 0.55.0. My desktop is Windows 10.  The Server end is Ubuntu 14.04.  The version of Python is 3.6.3 (in /usr/local/bin, but I don't think that's important.)

EDIT: I forgot to mention that the shell is Bash.

**Comment by weinand** [comment]
Have you tried this:
```
"args": [".", "--tags", "not @wip"],
```

**Comment by int19h** [comment]
Getting the whole thing quoted is what I'd expect in this case. But the quoting process should also escape existing quotes and/or spaces to be correct. 

If the above workaround doesn't work, another option would be to use `"console": "internalConsole"` in launch.json, at least if your app doesn't require interactive input. With that setting, the debugger won't try to use the shell in your terminal to spawn the debuggee, and so there are no quoting/escaping issues.

**Comment by amazingmo** [comment]
Hi @weinand and @int19h,

Thanks for your suggestion, and I did try as you suggested:
```
"args": [".", "--tags", "not @wip"],
```
but it produces `.../launcher 35264 -- -m behave . --tags "not @wip"` which has the result of skipping all of the tests.
I believe that the '=' character is required and that there may be no space between the end of `--tags` and the `="not @wip"`.

I understand that this does not follow the usual convention.

Thanks for your suggestion @int19h  but it doesn't seem to have addressed the issue.  I set a breakpoint on a test that should have been hit but it wasn't.

**Comment by amazingmo** [comment]
Hi @weinand 
This ticket still has the "needs more info" tag.  Can you please let me know specifically what you need?
I thought you wanted me to try your suggested input. I did.  It's not clear to me what else you need.

Thank you, and Merry Christmas.

**Comment by weinand** [comment]
@amazingmo I'll look into this in January. Enjoy the holidays.

**Comment by eternalphane** [comment]
@amazingmo you may try this:
```json
["." "--tags=\"not", "@wip\""]
```

**Comment by roblourens** [comment]
This should be fixed now in latest Insiders. Write your args with no escapes and vscode should escape it properly for your shell.
