### ISSUE TITLE
Mouse scroll action taking to bottom of page

### ISSUE THREAD

**Issue by pankaj2433** [microsoft/vscode#108780]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Sometimes when I start to scroll the screen runs to the last section of the code(i.e bottom of the page).

It's happening a lot of times.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 4.15.0-121-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3821)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (0.54GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id d67c7c96-46c3-49f6-b2d5-9524ba6bc782|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
vscode-intelephense-client|bme|1.5.4
githistory|don|0.6.12
gitlens|eam|10.2.2
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.1
code-runner|for|0.11.1
debugger-for-chrome|msj|4.12.11
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.3.0
vscode-css-peek|pra|4.0.0
synthwave-vscode|Rob|0.1.8
code-settings-sync|Sha|3.4.3
ayu|tea|0.20.1
highlight-matching-tag|vin|0.10.0
vscode-icons|vsc|11.0.0
material-theme|zhu|3.9.3

(5 theme extensions excluded)

</details>

**Comment by pankaj2433** [comment]
No it's not covered.

**Comment by chrmarti** [comment]
How do you scroll? With the mouse wheel, scrollbar or keyboard?

**Comment by pankaj2433** [comment]
Mouse wheel

**Comment by alexdima** [comment]
Let's track in #28795
