### ISSUE TITLE
How to recover file after losing it due to disk full

### ISSUE THREAD

**Issue by labeeba** [microsoft/vscode#108770]
I faced the same issue reported in https://github.com/microsoft/vscode/issues/34915
and my file is now empty. Is there any way to recover the file? Please help, I've lost days of work. I'm on a Windows OS.

**Comment by bpasero** [comment]
There is no recovery option sorry. The best choice to make sure data is not lost in these cases is imho to use a SCM repository (even locally) and to frequently check in the data.
