### ISSUE TITLE
Cannot close tab opened by piping to `code -`

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [microsoft/vscode#108752]
Issue Type: <b>Bug</b>

This issue occurred while I was running VSCode locally on my Mac and connecting to a remote Linux development system.

1. Pipe some input from a terminal to VSCode via `code -`, for example: `ls |code -`
2. VSCode will open the input in a new editor with a name like `code-stdin-xxx.txt`.
3. Accidentally run the "Save" command (e.g. Cmd+S) in the editor.
4. VSCode reports the error: "Failed to save 'code-stdin-rkm.txt': The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes."
5. Close the error (do not click either "Compare" or "Overwrite").
6. Notice that the "unsaved" dot now appears on the editor's tab title.
7. Try to close the editor with the input.
8. Notice that nothing happens—the editor remains open and cannot be closed.

Opening and closing other editors created by piping to `code -` seem to work just fine—this only seems to be an issue if you try to save an editor that was piped from `code -`.

Also, in step 5 if you choose "Overwrite" instead of dismissing the notification, the bug does not occur—the file is saved, the "unsaved" dot is removed from the tab title, and the editor can be closed. The bug only seems to occur if you leave the editor unsaved.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.0-1024-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|-psn_0_684199 --crash-reporter-id 064a4e57-4ceb-4e96-985c-c7562897d65d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: aws-dev|
|OS|Linux x64 5.4.0-1024-aws|
|CPUs|AMD EPYC 7571 (8 x 2199)|
|Memory (System)|31.10GB (15.93GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.6.0
remote-containers|ms-|0.145.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.0
vscode-remote-extensionpack|ms-|0.20.0
pestfile|xor|0.0.2
npm-intellisense|chr|1.3.1
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
html-preview-vscode|geo|0.2.5
vscode-pull-request-github|Git|0.20.1
vscode-emacs-friendly|lfs|0.9.0
git-graph|mhu|1.26.0
trailing-spaces|sha|0.3.1
vscode-taskexplorer|spm|1.27.0
rewrap|stk|1.13.0

</details>

**Comment by bpasero** [comment]
I cannot reproduce, I can close the file after confirming to close it without saving, are you closing it any different?

**Comment by joshua-berry-ntnx** [comment]
I tried to reproduce it again just now and largely failed (step 4 in my original report didn't happen).

However, after some more experimentation, it seems there is one condition missing from my original report, which is the temporary file holding stdin has to have been changed outside of the editor (e.g. by appending more output to it). For example, I can reproduce it consistently using a command like `ping localhost |code -`, which appends to the file every second.

In my particular case, this probably happened consistently yesterday because I was piping very large log output (e.g. `docker-compose logs foo |code -`) into VSCode and trying to clean it up for readability—unknowingly, before the logs had finished loading. The thing that clued me in on re-reading this morning was the actual error—I should have paid a little more attention to "The content of the file is newer.", sorry for missing this detail at first. :)

Here is a revised list of steps to reproduce (changes <ins>marked</ins>):

1. Pipe some <ins>continuous</ins> input from a terminal to VSCode via `code -`, for example: `ping localhost |code -`. <ins>Leave the command running in the terminal.</ins>
2. VSCode will open the input in a new editor with a name like `code-stdin-xxx.txt`.
3. <ins>Make a change to the contents of the editor.</ins>
4. Accidentally run the "Save" command (e.g. Cmd+S) in the editor.
5. VSCode reports the error: "Failed to save 'code-stdin-rkm.txt': The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes."
6. Close the error (do not click either "Compare" or "Overwrite").
7. Notice that the "unsaved" dot now appears on the editor's tab title.
8. Try to close the editor with the input.
9. Notice that nothing happens—the editor remains open and cannot be closed.

Also, now that I think of it, there is one non-default setting I have which might be relevant/affect the behavior above, which is:

```
"files.autoSave": "onFocusChange"
```

Hope this helps and thanks for looking into this!

**Comment by bpasero** [comment]
@joshua-berry-ntnx very good finding, thanks for the detailed steps I can reproduce 👍

**Comment by joshua-berry-ntnx** [comment]
No problem, thank you for fixing it! 😄
