### ISSUE TITLE
Allow to give commands different alias(display name) for different menus

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#108719]
Sometimes, the extension author may want to make a command has different display name according to where the command is shown. For example:

A command to run the current active file
- It can displayed as `Run current file` in the Command Palette.
- It can also be simply displayed as `Run` in the editor context menu.

Currently, we have to register two different commands to display different names for the same functionality.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Amenus

**Comment by jdneo** [comment]
Hi @jrieken,

I tried to search for it but did not find duplicated one. 😂

**Comment by jrieken** [comment]
hehe - this one: https://github.com/microsoft/vscode/issues/34048

**Comment by jdneo** [comment]
Ah, I should search for `command title`. (was trying to search with `command name`, `command alias`...🙈)
