### ISSUE TITLE
Syntax highlighting breaks without any reason. (Javascript)

### ISSUE THREAD

**Issue by ebastuart** [Microsoft/vscode#10878]
- VSCode Version: 1.4.0
- OS Version: Windows 10 64bit, latest updates

the highlighting breaks without any reason. there are no errors and the code is valid, but the code remains white (no highlighting)  down to the end of the file. 

![image](https://cloud.githubusercontent.com/assets/5196882/17923865/6ff90dc4-69e6-11e6-83e6-ee5cb5891069.png)

**Comment by wallverb** [comment]
Maybe related to this https://github.com/Microsoft/vscode/issues/9937

**Comment by alexandrudima** [comment]
@ebastuart Is it possible to share the file with us so we can track down the problem and check if it is an issue with the grammar

**Comment by alallier** [comment]
I've seen this happen in many different occurrences, mainly in longer files. Could this be a file length issue?

**Comment by alexandrudima** [comment]
@alallier When you notice this, please create an issue and attach the file or a similar file that reproduces the issue.

**Comment by ebastuart** [comment]
@alallier it is a nesting issue ... if you have to much code nested in each other it will break the highlighting.

**Comment by alallier** [comment]
@alexandrudima The files I am working on contain sensitive data, so I can't attach them to an issue. I've been meaning to work up a dummy file I can attach to show the problem I am running into.

@ebastuart it doesn't seem to be a nesting problem for me

**Comment by jdalton** [comment]
If you're looking for a large file which stops highlighting you can check out:
https://raw.githubusercontent.com/lodash/lodash/4.16.4/lodash.js

**Comment by alexandrudima** [comment]
@jdalton we regularly update our JavaScript TM language (we take it from https://github.com/Microsoft/TypeScript-TmLanguage). With the latest version we have in master (insiders build stream) lodash appears to be colored fine.

**Comment by djlooney** [comment]
Not sure if you are still in the market for a nonsensitive file. Here is an un-minified js resource loaded by twitch.tv which has issues for me starting at line 4825. The lodash file from earlier in the thread has no issues for me.

https://gist.githubusercontent.com/djlooney/4ec6a2a55f778d11bd95eb9bbc87fe28/raw/6c7cc59860114382420eec82d55a7bd630f94133/sample.js

**Comment by mjbvz** [comment]
Closing as fixed

@ebastuart Please let us know if you still see this issue in VSCode 1.8.1+. If you do, please provide some sample code so we can investigate.

Thanks

**Comment by djlooney** [comment]
I am still having issues with some of my large files on 1.8.1. Attached is a js file which has no syntax highlighting after line 4823, and an attached screenshot of what I see.

https://gist.githubusercontent.com/djlooney/4ec6a2a55f778d11bd95eb9bbc87fe28/raw/6c7cc59860114382420eec82d55a7bd630f94133/sample.js

http://imgur.com/a/B2A4U

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#403
