### ISSUE TITLE
Python: Hovering Mouse Over Decorated Functions Shows Decorator As Function Name

### ISSUE THREAD

**Issue by rohansekhri** [microsoft/vscode#108707]
Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Since all extensions were disabled, this looks more like an editor issue than a Python extension issue

Steps to Reproduce:

1. Write a decorated function in Python as shown 
2. Hover the mouse over the decorated method

![setup_github](https://user-images.githubusercontent.com/46380417/96074929-eb821500-0e77-11eb-8f9d-a593b1f430d0.gif)

Does this issue occur when all extensions are disabled?: Yes

The docString is correct, but the method name is always _check_client

**Comment by aeschli** [comment]
The hover must come from a Python extension as out of the box, VSCode has no rich Python support.

Would you mind filing the issue against https://github.com/Microsoft/vscode-python/issues? (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)
