### ISSUE TITLE
iPadOS: view header actions not touchable

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108735]
I noticed that the view header actions cannot be touched easily because they seem to disappear once focus moves out of the tree within. Example:
* add a watch expression in debug view
* select it
* try to touch on any of the watch expressions view header items

=> 🐛 they disappear

**Comment by isidorn** [comment]
This is better since my change to render the header actions on focus. So the title actions are now actually nicely usable on the iPad. Thus closing this.
