### ISSUE TITLE
Screen cheese in notebooks

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#108764]
I was close the bottom of the window. Several items were collapsed. I added a new H3 markdown cell and then a code cell. I ran the code cell right away:

![image](https://user-images.githubusercontent.com/4674940/96204852-2e94c480-0f1a-11eb-9173-62fa842ee17e.png)

**Comment by rebornix** [comment]
This particular issue was already fixed and follow up item is extracted to https://github.com/microsoft/vscode/issues/117623 .
