### ISSUE TITLE
XHR errors when running _workbench.downloadresource command

### ISSUE THREAD

**Issue by daniv-msft** [microsoft/vscode#108760]
Hello,

Our extension is using the VS Code command `_workbench.downloadresource` to download binaries. We can see from our telemetry that some of our users are getting errors with this command: `XHR failed` and `XHR timeout: undefinedms`.

From our investigation, these XHR issues are likely due to network issues or to timeouts. However, the existing errors don't provide much details to help us understand more.

Looking at VS Code's codebase, we can see that more details should be included in the `XHR failed` error, but as of today we don't get any (for none of our users).

Are you aware of reasons for XHR issues with this command? Would you have any recommendations on how to get more details about these errors?

- VSCode Version: 1.50.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce: seen in telemetry for a part of our users, not reproducing when using the command directly.

Does this issue occur when all extensions are disabled?: Cannot be tested because we don't have access to the failing users' machines.

**Comment by sandy081** [comment]
I am just using underlying request service to returning the error I receive from request.

https://github.com/microsoft/vscode/blob/df29df80c583c1e9a1c674428cc317e1275296d6/src/vs/platform/download/common/downloadService.ts#L22-L36

Assigning to @deepak1556 to help how to get more info here.

**Comment by deepak1556** [comment]
@daniv-msft can you get the network log by asking users to launch code with `--log-net-log=<some-absolute-path>/netlog.json` and perform the failing request action.

**Comment by daniv-msft** [comment]
@deepak1556 Thanks for your reply. I cannot ask directly most users to do this (as we mostly see this indirectly through telemetry), but we have one user who contacted us about this issue recently! I just asked the user to provide these logs, and will let you know once I have them.

**Comment by daniv-msft** [comment]
The user never replied, unfortunately. Since November, we moved to another third-party downloading API to help with this.
Thanks to everyone who had a look into this! I'm closing this issue.
