### ISSUE TITLE
don't have any symbol info for lua?

### ISSUE THREAD

**Issue by 1050676515** [Microsoft/vscode#10871]
- OS Version:Win7

Steps to Reproduce:

1. can't find symbol info for lua-file

**Comment by sandy081** [comment]
@1050676515 By symbol info you mean Symbols out line (Go to Symbol... or ctrl+shift+o command). If not may I know what exactly it is.

Thanks

**Comment by 1050676515** [comment]
It is solved.I installed lua-for-vscode plugin.Thank you for reply
