### ISSUE TITLE
Debug Console: Filter dialog visibility should be customizable

### ISSUE THREAD

**Issue by benPesso** [microsoft/vscode#108723]
As can be seen in the screenshot, the field is huge and takes up too much space, forcing the `Output` and `Terminal` windows into a secondary window. It is also always visible, whether you need it or not.

The dialog should be hidden by default, and only made visible on demand (or configuration, for those that want it "always on"). It should also display as a floating modal dialog. This will align its behavior and style to that of the `Edit -> Find` dialog. 

This will also make the panel less ugly; what with the slim and rounded drop-down menu, and the square and ugly input field. 😄

_**P.S.**
As mentioned in #108759, this should probably be applied to all panels in that have a filter widget. Not only the Debug Console._

### Current
<img width="849" alt="Screenshot" src="https://user-images.githubusercontent.com/921173/96103157-025c5200-0ee0-11eb-8a0e-38d273d3cb5d.png">

### Proposed
<img width="849" alt="Screenshot" src="https://user-images.githubusercontent.com/921173/96105358-9deec200-0ee2-11eb-9226-6b93ba67f74a.png">

**Comment by ArturoDent** [comment]
Related: https://github.com/microsoft/vscode/issues/93584 although unclear there what change(s) is being considered.

**Comment by isidorn** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/108759 
When we do that issue we will also take this into account. Thanks

**Comment by benPesso** [comment]
@isidorn I think it might be faster to implement the change I suggested, than to re-write the whole panel to be reusable, so maybe it would be good to keep this one open and separate?... As "phase 1" or something.
