### ISSUE TITLE
apt-get update broken

### ISSUE THREAD

**Issue by rittneje** [microsoft/vscode#108766]
Not sure if this is the right place to report this, but `apt-get update` is broken. It was working fine a few days ago.

```
$ sudo apt-get update
...
Err:8 http://packages.microsoft.com/repos/vscode stable/main amd64 Packages
  Writing more data than expected (1401820 > 1400699)
Fetched 3,959 B in 1s (2,904 B/s)   
...
```

**Comment by MitaiGit** [comment]
`
Не удалось получить http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages.bz2  Файл имеет неожиданный размер (203820 != 203585). Возможно, выполняется синхронизация зеркала? [IP: 104.214.230.139 80]
`

**Comment by iridakos** [comment]
I had the same problem and it seems to have been resolved. The `sudo apt-get update` commands completes successfully.

**Comment by rittneje** [comment]
It is working for me now as well.
