### ISSUE TITLE
Windows Integrated Bash Shell -- long startup

### ISSUE THREAD

**Issue by kylelib** [microsoft/vscode#108737]
Issue Type: <b>Bug</b>

For several releases now I've had issues with the integrated Bash shell not taking input for several minutes after starting up Visual Studio Code. On VS Code startup the integrated shell opens as expected, but the bash shell prompt is scrolled out of view. When I enter commands to the integrated bash shell no keyboard input is accepted for quite some time (several seconds to minutes). The interesting thing is, after I receive the latest VS Code automated update the integrated bash terminal startups up and is responsive to keyboard input almost immediately. After a few VS Code sessions the startup time degrades.

Steps to reproduce: 
1. Set Visual Studio Code terminal.integrated.shell.windows to "C:\\Program Files\\Git\\bin\\bash.exe".
2. Close Visual Studio Code
3. Open VIsual Studio Code
4. Notice that the shell appears as expected, but the prompt is scrolled out of view, and it will not accept keyboard input.
NOTE: This behavior may not start happening until subsequent VS Code sessions have been started, So it may require closing and reopening Visual Studio code a few times.

Also NOTE: My home drive is set to a network drive rather than a local drive. However this does not seem to affect the Bash shell when I open it outside Visual Studio.

Here are my related settings:
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "window.zoomLevel": 0,
  "editor.tabSize": 2,
  "editor.detectIndentation": false,
  "terminal.integrated.automationShell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode"
}

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.88GB (10.88GB free)|
|Process Argv|--folder-uri file:///c%3A/LHIProjects/LHI.MedNet/LHI.MedNet.WebApp.WebAppUI --crash-reporter-id d686cce1-ea51-49b5-840f-9df594d815b6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
ng-template|Ang|0.1001.0
bracket-pair-colorizer-2|Coe|0.2.0
prettier-vscode|esb|5.7.1
vscode-tfs|gen|2.0.0
mssql|ms-|1.9.0
vscode-icons|vsc|11.0.0

</details>

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by kylelib** [comment]
I'm not sure I understand what your telling me to do. The ConPTY references you pointed me to are from two years ago. The problems I'm having only started recently within the past 2 or 3 months. Honestly, I think the problem might be with the ConPTY implementation in Visual Studio because if I turn off _Terminal > Integration: **Windows Enable Conpty**_ the problem I reported seems to go away. 

Here's is my settings JSON for that configuration Item:
`"terminal.integrated.windowsEnableConpty": false`

At the moment I feel like the problem is with ConPTY, not WinPTY.

**Comment by kylelib** [comment]
I'm just noticing that the setting `"terminal.integrated.windowsEnableConpty"` has a caveat in the comments saying: "requires Windows 10 build number 18309+). My client is quite a bit behind on Win10 versions. I'm currently at Version 10.0.17763 Build 17763.

I guess I'll be waiting until my client is caught up.
