### ISSUE TITLE
Settings Sync: There is no way to specify git.defaultCloneDirectory on various platforms Windows, Mac or Linux

### ISSUE THREAD

**Issue by asphub** [microsoft/vscode#108714]
Issue Type: <b>Bug</b>

`git.defaultCloneDirectory` conflicts on mac and windows sync, 
Please add an option to add multiple paths for Windows / Mac or Linux

Also If there is an option to **OVERRIDE the settings from DEVICE to DEVICE like what the User Settings & Workspace Settings do** will be more helpful.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (4.83GB free)|
|Process Argv|--crash-reporter-id 58d34ec8-d61b-42a3-a6f0-c972cd87ddfc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgo|ajh|0.1.0
ng-template|Ang|0.1001.0
vscode-svgviewer|css|2.0.0
gitlens|eam|10.2.2
minify|Hoo|0.4.3
vscode-typescript-tslint-plugin|ms-|1.2.3
material-icon-theme|PKi|4.3.0
vscode-scss-formatter|sib|2.0.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by joaomoreno** [comment]
Fixed it. Until then, you can add `git.defaultCloneDirectory` to the `settingsSync.ignoredSettings` setting.

**Comment by jrieken** [comment]
Verified in source
