### ISSUE TITLE
Improve smart select for batch files (between quotes)

### ISSUE THREAD

**Issue by freMea** [microsoft/vscode#108763]
VS Code version | OS
------------------ | ----
1.50.1  | Win 10 x64 pro (french) 18363.1082

## Steps to reproduce

Currently, when I use `editor.action.smartSelect.expand` in a .bat file and when the cursor is in a quoted scope, it selects the word then the line. It’s not consistent with other language.

## Expectations

Add a step to select inner and outer quoted text.

## Example

Each line would be a step using the `editor.action.smartSelect.expand` command, where `[]` represents the cursor/selection:

```bat
"%SYSTEMROOT%\system32\fsutil.exe" dirty query "%Syst[]emDrive%" >NUL 2>&1
```
```bat
"%SYSTEMROOT%\system32\fsutil.exe" dirty query "%[System]Drive%" >NUL 2>&1
```
```bat
"%SYSTEMROOT%\system32\fsutil.exe" dirty query "%[SystemDrive]%" >NUL 2>&1
```
Currently at this step, it directly jump to line selection. So here are the steps to add for an expected behavior.
```bat
"%SYSTEMROOT%\system32\fsutil.exe" dirty query "[%SystemDrive%]" >NUL 2>&1
```
```bat
"%SYSTEMROOT%\system32\fsutil.exe" dirty query ["%SystemDrive%"] >NUL 2>&1
```
These are optional.
```bat
["%SYSTEMROOT%\system32\fsutil.exe" dirty query "%SystemDrive%"] >NUL 2>&1
```
```bat
["%SYSTEMROOT%\system32\fsutil.exe" dirty query "%SystemDrive%" >NUL 2>&1]
```

**Comment by aeschli** [comment]
Language extensions can provide a language aware selection providers, but out-of-the box, we don't do that for batch files.
Instead, a default selection provider is used that uses the current word, brackets and lines. 

We don't plan to add a batch-file specific selection provider. This would be something an extension should provide. 

But maybe strings could also be part of the default selection provider. That would cover `"[%SystemDrive%]"` and `["%SystemDrive%"]`. You could file an issue for that. (FYI @jrieken)

However `["%SYSTEMROOT%\system32\fsutil.exe" dirty query "%SystemDrive%"]` can only be done by a language aware selection provider that has to come from an extension.
