### ISSUE TITLE
references.preferredLocation setting stopped working

### ISSUE THREAD

**Issue by Andikki** [microsoft/vscode#108726]
Issue Type: <b>Bug</b>

I have the following user setting:
```json
"references.preferredLocation": "view"
```
With this when I click on CodeLens references counter above a method or class I should see references open in a "References" panel on the side. But they open in a peek view instead, as if the setting's value was `"peek"`.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.25GB free)|
|Process Argv|--folder-uri file:///<...> --crash-reporter-id ad1c424d-a6f5-4fb1-9d42-fb370ca87718|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
code-beautifier|mic|2.3.3
csharp|ms-|1.23.3
mssql|ms-|1.9.0
remote-wsl|ms-|0.50.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11

</details>

**Comment by jrieken** [comment]
Ops - looks like that got lost during a last big refactoring...

**Comment by jrieken** [comment]
\closedWith 4be0a2b9d571b9f9707ab2d7cf35c5012bfc12cc
