### ISSUE TITLE
Visual Code Studio not working after an update

### ISSUE THREAD

**Issue by fcbarnard** [microsoft/vscode#108703]
- VSCode Version: 2020 v 1.5
- OS Version: Catalina 10.15.7

Steps to Reproduce:

1. I am just running normal queries. If statements that should not execute executes when I look at code execution. 
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
> 1. I am just running normal queries. If statements that should not execute executes when I look at code execution.

Please explain. Maybe paste screenshots. 

/needsMoreInfo
