### ISSUE TITLE
Avoid "Go to file..." finding deleted files

### ISSUE THREAD

**Issue by erf** [microsoft/vscode#108716]
When i pressed `CMD+p` and searced for a file now, a couple of deleted files popped up and when i pressed on it i got an error message as they were deleted. I think it is unnessesary to list deleted files, so maybe this command could check if these files are deleted and don't show them, or update the index at start, or something like that. Thanks!

Visual Studo Code Version: 1.50.1

OS: macOS

Extensions:
Dart-Code.dart-code
Dart-Code.flutter
dbaeumer.vscode-eslint
denoland.vscode-deno
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
esbenp.prettier-vscode
Kasik96.swift
ms-azuretools.vscode-docker
PKief.material-icon-theme
vknabel.vscode-apple-swift-format
vscodevim.vim

**Comment by bpasero** [comment]
The history of recently opened files is updated based on file events and will remove entries when they get deleted. But if VSCode is not running and files are deleted, the history is potentially stale. 

I have no plans to change this.
