### ISSUE TITLE
Source control tab shows duplicate repos while Live Sharing

### ISSUE THREAD

**Issue by nschmeller** [microsoft/vscode#108756]
Issue Type: <b>Bug</b>

1. Start Live Share session (2 other users joining with read/write in this case)
2. Follow one participant and have them edit on a different branch in a git repo (in this case, I was on master and they were on a separate branch)
3. Every time they make an edit, a new duplicate repo appears in the Source Control tab. See screenshot below (after several edits):

<img width="252" alt="image" src="https://user-images.githubusercontent.com/26189705/96161952-eeb3ea00-0ee5-11eb-8d84-168d5cab7771.png">

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|8.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id 5bf3bb8f-57b1-4dda-9c7c-de15247d23d0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
react-pure-to-class-vscode|ang|1.1.8
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.37.1
vscode-eslint|dba|2.1.10
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
json-tools|eri|1.0.2
prettier-vscode|esb|5.7.1
ocaml|hac|0.6.43
git-graph|mhu|1.26.0
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.3
python|ms-|2020.9.114305
remote-containers|ms-|0.145.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.0
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.0.1
vsliveshare|ms-|1.0.2902
debugger-for-chrome|msj|4.12.11
ocaml-tuareg-master|muc|1.0.3
abracadabra|nic|4.8.0
java|red|0.69.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-todo-highlight|way|1.0.4

</details>

**Comment by fabiogiolito** [comment]
I have this same issue. Anyone know what's causing it?

**Comment by nschmeller** [comment]
I linked to this issue at the Live Share repo, we'll see what happens!

[https://github.com/MicrosoftDocs/live-share/issues/3922](url) #
