### ISSUE TITLE
Dropdown with search history

### ISSUE THREAD

**Issue by sergey-beloglazov** [microsoft/vscode#108728]
Functionality with browsing search history with alt+up/down works fine. It was mentioned in this issue:
https://github.com/microsoft/vscode/issues/5508
But it's not obvious and takes too much time to browse history one-by-one.
I think, a select with a drop-down list, as it is in Notepad++ and any other program, such as Word or Execl is better!
Thank you!

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/23099
