### ISSUE TITLE
VS Code delete the indentation of empty lines when formatting the code

### ISSUE THREAD

**Issue by brunoprietog** [microsoft/vscode#108709]
Hello!
I have the following issue. When formatting some code with indented blank lines, VS Code takes away the spaces. This is very annoying when reading it with a screen reader (in my case NVDA), because if there is a line with 4 indented spaces, then a blank line and then another line with 4 spaces, NVDA notifies a change of indentation in that blank line, and then again announces a change of indentation, informing that it was returned to the 4 spaces of before, being that in reality there has not been any change, theoretically. At first glance you don't notice this, but with NVDA it is especially annoying in my opinion.

You can try using NVDA, with the indentation announcement with tones enabled. NVDA menu -> Preferences -> Settings... -> Document Formatting -> Line indentation reporting: Tones.

This is how VS Code formats it:

```python
testing=True
if testing:
    print('First print before a blank line')

    print('Second print after a blank line')
```

And this would be much more pleasing to the ear, with fewer distractions:

```python
testing=True
if testing:
    print('First print before a blank line')
    
    print('Second print after a blank line')
```

Even if I try to write it this way, the moment I format the code, all my effort to keep the lines that way is immediately lost.

Other people have also requested this feature although for other reasons, also very valid and that I agree, see [here](https://github.com/OmniSharp/omnisharp-vscode/issues/1980).

I would be very grateful if you could enable an option to disable the removal of indentation on empty lines when formating.

**Comment by brunoprietog** [comment]
@isidorn

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
