### ISSUE TITLE
Change the font of the debugger panels

### ISSUE THREAD

**Issue by ijoel92** [microsoft/vscode#108761]
Hello everyone,

I have searched and found similar features that have been provided but not quite as I think they would work.

I would like to have a format similar to PyCharm, where the variables have a more readable font to see the variable's data. There are are settings to change the "Debugger Console" but they don't affect the rest of the panels (Variables, Watch or Call Stack).

Here's an image of how PyCharm displays it:

![image](https://user-images.githubusercontent.com/44055815/96195430-a7107b00-0f44-11eb-9993-6c72bdf4ebd5.png)

This, alongside the "View as Array" feature, would make my experience of working with data much more enjoyable!

Let me know if there is anything I can provide

**Comment by isidorn** [comment]
Pytho extension can contribute commands to the variables context menu. One of those would be View As Array which could open a custom web view

**Comment by ijoel92** [comment]
How does the python extension affect the font selection on the debugger panels?

**Comment by isidorn** [comment]
The view as array feature you mentioned.
The font is a duplicate of make font customisable across workbench - you can search for that issue and upvote it.

**Comment by ijoel92** [comment]
Can't find that issue. Is it still open? Can you point me to it?
