### ISSUE TITLE
TypeScript detects types differently when hovering vs CMD+hovering

### ISSUE THREAD

**Issue by christian-bromann** [microsoft/vscode#108786]
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (2 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. git clone git@github.com:webdriverio/webdriverio.git
1. cd webdriverio
1. git checkout cb-rewrite-wdio-utils
1. npm install
1. npm run setup-full
1. open packages/wdio-utils/tests/initialisePlugin.test.ts

You will see that TypeScript is in a weird space not being able to detect namespaces and types properly, e.g. hovering over a function returns different types than pressing command and hover:

![ts](https://user-images.githubusercontent.com/731337/96244285-25513980-0fa6-11eb-8868-92b30a7bf287.gif)

This makes working with TypeScript very frustrating as things pass locally and fail in CI. You have to check out the whole repo again to reproduce the issue but if you run tests twice, everything passes magically again. This makes it a very unreliable experience.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Normal hover shows the detected type signature. Cmd+hover shows a preview of the actual source code.

If the hover shows `any`, it's likely because our IntelliSense cannot understand the typing. What is the type of `Service` if you hover over it?
