### ISSUE TITLE
Rename symbol (F2) does not work anymore

### ISSUE THREAD

**Issue by eddy147** [microsoft/vscode#108713]
- VSCode Version: 1.50.1, commit d2e414
- OS Version: Linux x64 5.4.0-51-generic snap
- Node.js: 12.14.1

Steps to Reproduce:

1. Open vscode with code
2. Set cursor on variable name or function name
3. click F2
Expected: you can edit the name of the symbol to be renamed
Actual: nothing happens, so can not rename the symbol.

Notes: 
- this used to always work, maybe because I updated to the latest version?
- in the tree explorer I can rename a file or directory, but not variables/functions in code.
- I use Intelephense extension. But same issue appears after uninstalling all extensions, also tried with Code Insiders.
- Checked the developers tool bar, there were no errors shown when I pressed F2. Actuall nothing was shown as if the F2 is not binded to an action.

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Could be https://github.com/microsoft/vscode/issues/108679. Which Linux distro and version are you using?

**Comment by eddy147** [comment]
@chrmarti I am using 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by alexdima** [comment]
@eddy147 Can you please follow the steps at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting

It would be interesting to see what the log output for pressing `F2` is.

**Comment by eddy147** [comment]
Hi @alexdima
see attachment, hopefully it is useful.
Let me know if I can do something else.

Thx for your help.

 [
[f2.log](https://github.com/microsoft/vscode/files/5383593/f2.log)
](url)

**Comment by alexdima** [comment]
@eddy147

This is the relevant section:
```
[2020-10-15 11:00:06.349] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: F2, keyCode: 113, key: F2
[2020-10-15 11:00:06.349] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: F2, keyCode: 60 ('F2')
[2020-10-15 11:00:06.350] [renderer1] [info] [KeybindingService]: | Resolving [F2]
[2020-10-15 11:00:06.350] [renderer1] [info] [KeybindingService]: \ From 5 keybinding entries, no when clauses matched the context.
```

So it looks like on your machine there are 5 keybinding entries that are bound to <kbd>F2</kbd>, but none of them matched the current context. This is very interesting, for example on mac we only ship with one keybinding that targets <kbd>F2</kbd>:
```
{ "key": "f2",                    "command": "editor.action.rename",
                                     "when": "editorHasRenameProvider && editorTextFocus && !editorReadonly" },
```

So I wonder if you have perhaps installed extensions that customize keybindings or if you have written custom rules in your personal `keybindings.json` ?

**Comment by eddy147** [comment]
Thank you so far.

This was my ~/.config/Code/User/keybindings.json
```
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "f2",
        "command": "-renameFile",
        "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
    },
    {
        "key": "f2",
        "command": "-remote.tunnel.label",
        "when": "tunnelViewFocus && tunnelType == 'Forwarded'"
    },
    {
        "key": "f2",
        "command": "-debug.setVariable",
        "when": "variablesFocused"
    },
    {
        "key": "f2",
        "command": "-debug.renameWatchExpression",
        "when": "watchExpressionsFocused"
    }
]
```
I removed them, having now:


I did not add these myself.

After removing them and adding what I think is the default:


```
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "f2",
        "command": "editor.action.rename",
        "when": "editorHasRenameProvider && editorTextFocus && !editorReadonly"
    },
    {
        "key": "f2",
        "command": "-renameFile",
        "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
    }
]
```
Did not help, I am getting the same error as in the log you showed me earlier.
Also removing this keybindings.json file did not help either.

Is there a way to remove everything (cache/settings) and start totally clean?

**Comment by eddy147** [comment]
After upgrading to 20.04, and reinstalling vscode, F2  works again.
No clue what caused the problem though.

**Comment by alexdima** [comment]
Thanks for investigating. Clearing out your `keybindings.json` should fix things for you. I also don't know what might have caused these keybindings rules to show up in your `keybindings.json`. Normally, they show up when the keybindings editor UI is used and rich click > remove keybindings is invoked.

**Comment by eddy147** [comment]
Thank you for your efforts and such a great editor.
