### ISSUE TITLE
Badge on Remote Explorer makes icon harder to recognize

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#108798]
Please see the screenshot below:

![image](https://user-images.githubusercontent.com/172399/96261221-6eae8280-0fc0-11eb-848e-94a248143deb.png)

Given the rich information that can be shown in the status bar I wonder whether the badge is still needed

![image](https://user-images.githubusercontent.com/172399/96261317-969de600-0fc0-11eb-866b-46d5e14f8016.png)

**Comment by misolori** [comment]
The badge on the activity bar icon makes it more discoverable and matches the pattern for debug, though it can feel heavy handed. I do personally prefer the status bar item if we had to chose one though.

**Comment by egamma** [comment]
@misolori 

>The badge on the activity bar icon makes it more discoverable and matches the pattern for debug, though it can feel heavy handed.

Makes sense. 

However, in contrast to the debug icon the remote explorer icon is not badge friendly. The 'ports available badge' covers the 'remote decoration' of the icon. Without the remote decoration visible, the remote explorer icon is not easy to spot.

**Comment by alexr00** [comment]
@misolori could we flip the remote explorer icon? Badges in the activity bar are an expected and normal occurrence, so it seems like all icons in the activity bar should be badge friendly.

I am open to removing the badge, but it is consistent with how debug works.

**Comment by misolori** [comment]
I think if we move the remote decoration to the left it'll look odd and introduce inconsistencies with our other icons:

![image](https://user-images.githubusercontent.com/35271042/96793916-1c030b00-13b2-11eb-8f70-9d4c11372f71.png)

![image](https://user-images.githubusercontent.com/35271042/96793936-22918280-13b2-11eb-9b8a-1e8bbe65deda.png)

![image](https://user-images.githubusercontent.com/35271042/96793965-30df9e80-13b2-11eb-9028-3641ac2b249b.png)

**Comment by alexr00** [comment]
In that case, I'll remove the badge.
