### ISSUE TITLE
Issue with $TM_SELECTED_TEXT custom snippet

### ISSUE THREAD

**Issue by Damix48** [microsoft/vscode#108784]
When I select a word there and try to use the snippet there are 3 type of issue (in the same file and workspace):

1. Sometime there is not any suggestion for the snippet: ![issue1](https://user-images.githubusercontent.com/23702345/96237999-3f871980-0f9e-11eb-8bd1-ae8db614416a.gif)
2. Sometime the snippet not insert `$TM_SELECTED_TEXT`: ![issue2](https://user-images.githubusercontent.com/23702345/96238642-01d6c080-0f9f-11eb-979d-45245cbc3d79.gif)
3. Sometime the snippet delete 2 char of the text after and not insert `$TM_SELECTED_TEXT`: ![issue3](https://user-images.githubusercontent.com/23702345/96238358-ad334580-0f9e-11eb-848e-6e32af937ad9.gif)

This is my custom snippet:
```
"custom": {
    "prefix": "eng",
    "body": "<span xml:lang=\"en\">$TM_SELECTED_TEXT</span>",
    "scope": "html"
  }
```

- VSCode Version: 1.50.1 d2e414d9e4239a252d1ab117bd7067f125afd80a 2020-10-13T15:06:15.712Z
- OS Version: Windows_NT x64 10.0.19041 and Linux distros

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Does it work if you select the word, then open Command Palette (F1), then choose `Insert Snippet` and pick your snippet?

**Comment by Damix48** [comment]
Yes, seems to work.

**Comment by gjsjohnmurray** [comment]
So maybe set a keyboard shortcut for `editor.action.showSnippets` and use that when you have selected the word you want your snippet to wrap.

**Comment by Damix48** [comment]
Yes maybe, but it should work I think.
The issue 3 still even if I not select any word and change the custom snippet to this:
```
"custom": {
    "prefix": "eng",
    "body": "<span xml:lang=\"en\">${TM_SELECTED_TEXT:$1}</span>",
    "scope": "html"
  },
```
![issue4](https://user-images.githubusercontent.com/23702345/96242168-70b61880-0fa3-11eb-90df-a54e91cf284c.gif)

**Comment by jrieken** [comment]
File 1 issue per problem. Not 1 issue for 3 problems. Then include the full sample text and the complete steps you are trying

**Comment by Damix48** [comment]
[Repo](https://github.com/Damix48/vscode-issue) this repository contains the file personaggi.html where I have the problems and the `main.code-snippets`.

Steps to reproduce:
1. Clone the repo (https://github.com/Damix48/vscode-issue)
2. Open `personaggi.html`
3. Select random word
4. With some words the snippet `eng` (name: `span inglese`) works fine.
5. With other random words the snippet has one of the 3 problems (I don't recognize any pattern)

**Comment by ArturoDent** [comment]
In the meantime you could use (in keybindings.json)

```
  {
    "key": "alt+i",                                                 // whatever keybinding you want
    "command": "editor.action.insertSnippet",
    "args": {    
      "snippet": "<span xml:lang=\"en\">$TM_SELECTED_TEXT</span>",
    },
    "when": "editorTextFocus && editorHasSelection && editorLangId == html",
    "name": "wrap with span and lang=en attribute"
  },
```

this does seem to always work.

**Comment by Damix48** [comment]
> File 1 issue per problem. Not 1 issue for 3 problems. Then include the full sample text and the complete steps you are trying

Open 3 issues for the 3 problem:
1. #108892
2. #108893
3. #108894
