### ISSUE TITLE
Adopt UriIdentityService in WorkspaceService

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#108793]
The `WorkspaceService` manages the workspace and the workspace folders.

These folders are read from the config file or added from user input. To do that correctly, so that all URI are canonical, the UriIdentityServiceshould be used when the folders URIs are parsed.

The following utilities need the UriIdentityService as parameter:

- [toWorkspaceFolders](https://github.com/microsoft/vscode/blob/0ea68382da8946c59f57ed1990639d1d0f57f2e5/src/vs/platform/workspace/common/workspace.ts#L235),
- [rewriteWorkspaceFileForNewLocation](https://github.com/microsoft/vscode/blob/0ea68382da8946c59f57ed1990639d1d0f57f2e5/src/vs/platform/workspaces/common/workspaces.ts#L258)
- [getStoredWorkspaceFolder](https://github.com/microsoft/vscode/blob/0ea68382da8946c59f57ed1990639d1d0f57f2e5/src/vs/platform/workspaces/common/workspaces.ts#L215)

-> WorkspaceService/ConfigurationService needs the UriIdentityService

**Comment by bpasero** [comment]
@sandy081 QQ: I recently did a quick scan of where we still use the generic `isEqual` which does not take casing into account and was wondering if we now missed a few places, specificially:
* [`configurationService#contains`](https://github.com/microsoft/vscode/blob/bdb0ef4d48978773cb1173a6141985d337324274/src/vs/workbench/services/configuration/browser/configurationService.ts#L267-L269) which is I think used when adding folders to the workspace
* [`extHostWorkspace`](https://github.com/microsoft/vscode/blob/d49955575e50106fa99aade64f70e1011250dbb8/src/vs/workbench/api/common/extHostWorkspace.ts#L40-L54) has a few direct uses of `isEqual` too which also seem to be used in the context of adding folders to the workspace

I did not look closely enough if a change was needed or not.

**Comment by sandy081** [comment]
Thanks for the pointers. I think they are needed and adopted these places to use proper extUri.
