### ISSUE TITLE
Folders Doesn't link properly

### ISSUE THREAD

**Issue by NashatHelmi** [microsoft/vscode#108781]
Issue Type: <b>Bug</b>

When i link to any folder on my system the vscode shows it as .lnk file
and when i try to open it, it opens as text file

Steps to Reproduce:
1. Go to any folder
2. Make a shortcut to it
3. Paste the shortcut in the Workspace Folder

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.02GB free)|
|Process Argv|D:\Projects\My-React-Projects\blog-template --crash-reporter-id f550dffe-dea0-44ae-8e0e-48bf795eef20|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
See #35085 which also offers an alternative way of doing what you want without using Windows shortcut (.lnk) files.

**Comment by NashatHelmi** [comment]
> See #35085 which also offers an alternative way of doing what you want without using Windows shortcut (.lnk) files.

Thanks, it worked!

it would be better for vscode to support *.lnk folders like windows explorer rather than having to symlink it manually,
or having windows explorer itself to symlink rather than having .lnk file pointing to it
as they both work kinda the same way.
