### ISSUE TITLE
Opens much slower + g++ default build task issue

### ISSUE THREAD

**Issue by devils2ndself** [microsoft/vscode#108717]
Issue Type: <b>Performance Issue</b>

with one of the recent updates (like 1-2 days ago) vs code started to take much more time to open even the simplest projects, now gotta wait for quite some time for it to pop up

also, idk why, but i started having an issue with default build task using mingw's g++. earlier I used to set the task.json file by changing "${file}" in "args" to "*.cpp" so instead of one file it would compile all of them, now it doesn't work for some reason, getting errors saying that everything in the other files is undefined (meaning it only compiles 1 file). works from command line tho (if using "g++ - g *.cpp -o out"), so it's definitely not a compiler issue

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.65GB free)|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by devils2ndself** [comment]
figured out the task.json g++ issue. with the new update task.json file started using ""type": "cppbuild" instead of "type": "shell", like it used to.  changing the "type" to "shell" manually fixes the issue and the build process works perfectly. a minor inconvenience, but at least works, so not that big of a deal. although would be great not having to manually change task.json everytime :)

**Comment by Sonny-Klotz** [comment]
I had the same problem (same vscode and windows versions) and it worked after I changed "cppbuild" to "shell". Thanks a lot.
