### ISSUE TITLE
Opening a URL from the bash terminal freezes both the terminal and code.exe itself

### ISSUE THREAD

**Issue by JansthcirlU** [microsoft/vscode#108734]
- VSCode Version: 1.50.1
- OS Version: Windows 10 Pro version 1903

Steps to Reproduce:

1. Open Visual Studio Code
2. Open a new integrated terminal
3. Type any command that contains a URL, such as `echo https://duckduckgo.com`
4. Alt + Click the URL and confirm that code may open it

*Expected behaviour*: The webpage opens in my default browser and I can return to the terminal to continue working
*Actual behaviour*: The webpage opens but random characters appear in my terminal and it completely freezes, sometimes code also crashes and has to be reopened.

I demonstrate the bug in [this video](https://youtu.be/-vUcK-Ndytk). I used [`carnac`](http://carnackeys.com/) to visualize my keystrokes, but since I'm using AZERTY (Belgian keyboard layout), some keystrokes appear differently. However, it is still clear that the terminal does not process my text input for some time after opening a webpage. The same bug also occurs when I try to open a URL from Powershell.

Does this issue occur when all extensions are disabled?: **Yes** / ~No~

**Comment by JansthcirlU** [comment]
This issue still persists after uninstalling and reinstalling Visual Studio Code. This bug is especially annoying for web development since I'm used to Alt + Clicking the localhost address to view my pages. I know that I can just open the localhost address once and then refresh when needed, but that still does not justify such a critical bug in the terminal.

**Comment by Tyriar** [comment]
You might be hitting weird perf problems because of https://github.com/microsoft/vscode/issues/101136?

Could you take a performance profile via devtools (help > toggle dev tools) and upload it? That should show what is blocking the main thread.

**Comment by JansthcirlU** [comment]
@Tyriar I've tried to attach the corresponding `json` file but github wouldn't let me upload it. It's also a pretty big chunk of text to paste in my comment. Could I possibly send it to you in some other way?

**Comment by Tyriar** [comment]
Does it work when you zip it? I don't normally see problems with profile uploads. If you still have problems my microsoft.com email alias is daimms.

**Comment by JansthcirlU** [comment]
It worked! Here's the [Zipped Performance Profile](https://github.com/microsoft/vscode/files/5487098/Profile-20201103T150249.zip) archive.

**Comment by Tyriar** [comment]
Hmm, not much happening in the profile so I wouldn't expect a lock up to happen 🤔:

![image](https://user-images.githubusercontent.com/2193314/98152755-0f3ce780-1e87-11eb-9fac-72c197c5ebeb.png)

Could you try [enable escape sequence logging](https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging) to see if maybe your shell is causing the delay? That should show us that the text does indeed get send to the shell, and what it responds with and when.

**Comment by JansthcirlU** [comment]
[New performance profile](https://github.com/microsoft/vscode/files/5492867/Profile-20201105T090934.zip) after toggling escape sequence logging.

**Comment by Tyriar** [comment]
Oh sorry I didn't explain good enough, the logging will show up in the console which doesn't come through in the profile. I'm interested in how vscode and the shell reacts to your typing, what would be perfect would be a [gif ](https://gifcap.dev/)with screencast mode and the console showing up at the same time, something like this:

![recording (13)](https://user-images.githubusercontent.com/2193314/98307321-5eb01000-1f7a-11eb-83a7-9ef3e0b61816.gif)
