### ISSUE TITLE
File has unexpected size (141364 != 141252). Mirror sync in progress? [IP: 40.117.131.251 443]   Hashes of expected file: 

### ISSUE THREAD

**Issue by w3mona** [microsoft/vscode#108769]
Github actions fail to when the command "sudo apt-get update" is running. The error is:

Err:36 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (141364 != 141252). Mirror sync in progress? [IP: 40.117.131.251 443]
  Hashes of expected file:
   - Filesize:141252 [weak]
   - SHA512:dffbaf15f537ae643df110b279248993b2828e99352dff51a5df9648cf39531ffb7022ec2f0d9e553287c9889addcb5e734d9df95f749c456db04fd328a67ef4
   - SHA256:6757f7f09fb2a0491657aac899faa29bd67fe7b9dfd849844f7fafca9afcc33e
   - SHA1:37be76673db70e808db91294af54fddf476aae7f [weak]
   - MD5Sum:ecc0d5d8d9373eee7aeceda58d7be8f9 [weak]
  Release file created at: Tue, 13 Oct 2020 22:35:00 +0000
Hit:37 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic InRelease
Get:38 http://packages.cloud.google.com/apt cloud-sdk/main amd64 Packages [140 kB]
Get:39 https://cli-assets.heroku.com/apt ./ Packages [612 B]
Get:40 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages [41.3 kB]
Get:41 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1387 kB]
Get:43 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages [226 kB]
Get:44 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [274 kB]
Get:45 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [160 kB]
Get:46 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [21.5 kB]
Get:47 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1075 kB]
Get:48 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [240 kB]
Get:49 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [12.6 kB]
Get:50 http://security.ubuntu.com/ubuntu bionic-security/multiverse Translation-en [2936 B]
Get:51 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages [71.9 kB]
Get:52 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main Translation-en [29.5 kB]
Err:53 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  InRelease
  Cannot initiate the connection to download.opensuse.org:80 (2001:67c:2178:8::13). - connect (101: Network is unreachable) Could not connect to download.opensuse.org:80 (195.135.221.134), connection timed out
Fetched 8453 kB in 30s (278 kB/s)
Reading package lists...
W: Failed to fetch http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/InRelease  Cannot initiate the connection to download.opensuse.org:80 (2001:67c:2178:8::13). - connect (101: Network is unreachable) Could not connect to download.opensuse.org:80 (195.135.221.134), connection timed out
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (141364 != 141252). Mirror sync in progress? [IP: 40.117.131.251 443]
   Hashes of expected file:
    - Filesize:141252 [weak]
    - SHA512:dffbaf15f537ae643df110b279248993b2828e99352dff51a5df9648cf39531ffb7022ec2f0d9e553287c9889addcb5e734d9df95f749c456db04fd328a67ef4
    - SHA256:6757f7f09fb2a0491657aac899faa29bd67fe7b9dfd849844f7fafca9afcc33e
    - SHA1:37be76673db70e808db91294af54fddf476aae7f [weak]
    - MD5Sum:ecc0d5d8d9373eee7aeceda58d7be8f9 [weak]
   Release file created at: Tue, 13 Oct 2020 22:35:00 +0000
W: Some index files failed to download. They have been ignored, or old ones used instead.
Error: The process 'sudo' failed with exit code 100

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Can you still reproduce? This seems to work fine for me.

**Comment by dagood** [comment]
This was an outage in packages.microsoft.com's Ubuntu 18.04 and Ubuntu 20.04 repositories, we see these over on .NET Core as well and got the packages.microsoft.com team to resolve it: https://github.com/dotnet/core/issues/5373.
