### ISSUE TITLE
Overwrite files after upload completed

### ISSUE THREAD

**Issue by RazaGR** [microsoft/vscode#108730]
When I save a document, it takes a few seconds to update on the remote server. While my file is being updated, on my frontend (`http://myfile.php `) I get different kinds of errors, like 404 or php warnings or errors related to missing file data.

Is it possible to first update the file on a temp location and then replace the original file once the file has fully uploaded on the server?

For example, if I have had a file `/var/www/myfile.php`, and when I click save, it should first create a file `/tmp/myfile.php` and once the upload is complete, it moves from `/tmp/myfile.php` to `/var/www/myfile.php`

**Comment by gjsjohnmurray** [comment]
#98063 seems related
