### ISSUE TITLE
Makefile syntax highlighting partially breaks when a # is in a string

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode#108749]
- VSCode Version: 1.50.1
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Open a Makefile
2. Type in the following
```make
define config-gen =
	( echo '# Note: When a variable is set multiple times in this file' ;\
	  echo '#       it is the *first* setting that sticks!' ;\
  )
endef
```

Does this issue occur when all extensions are disabled?: Yes

The second echo statement is colored to look like a comment. You can see it is even broken in the GitHub syntax. I am no expert at textmake language files, but https://github.com/microsoft/vscode/blob/master/extensions/make/syntaxes/make.tmLanguage.json#L41 seems to tell me that a comment beginning with a # doesn't look behind itself to see if it is in a string.

**Comment by tristan957** [comment]
If the # sign was not in quotes I would most definitely expect the rest of the line to be commented. Some other language example that treat this properly:

```python
print("# hello world")
```
```shell
echo "# hello world"
```

**Comment by alexr00** [comment]
Thanks for filing the issue! We get our syntax highlighting grammar from another repo, so I've moved the issue over there: https://github.com/fadeevab/make.tmbundle/issues/9

**Comment by tristan957** [comment]
Thanks @alexr00
