### ISSUE TITLE
Markdown syntax highlighting issue

### ISSUE THREAD

**Issue by iranvir** [microsoft/vscode#108744]
- VSCode Version: 15.0.1 (User setup)
- OS Version: Windows 10.0.19041

Steps to Reproduce:

1. Create a markdown file.

2. Insert the following:
```
<br>
# This heading is not highlighted properly
```

3. The heading highlight doesn't work unless I introduce another newline between them:
```
<br>

# This is a heading is highlighted properly
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
```
<br>
# This heading is not highlighted properly
```

Do you know of any app that previews it as header? It looks like the header needs a newline before (or nothing at the start of the file) to be valid. At least the built-in preview in vscode and GFM work that way.

**Comment by mjbvz** [comment]
Closing this matches the markdown spec as far as I can tell: https://spec.commonmark.org/0.29/#html-blocks
