### ISSUE TITLE
Run code runs the code in non-writable output window

### ISSUE THREAD

**Issue by sanjmishra** [microsoft/vscode#108791]
When Running code using the Run code (Ctrl+Alt+N) it always runs in output window which is non-writable. Consequently if the program expects an input then it cannot be done. There are three ways to solve it:
1. Enable the output window to receive the input for the program (Make it writable just for the input of the program). This would make it easy for the user to have the same interface irrespective of the program.
2. Detect that the program expects an input and disable the Run Code command and its triangle icon on the right top and force the person to use the terminal to execute the command for the program to run, and
3. Detect that the program expects an input and run it in the terminal instead of the output window.

I know the alternative is to run the program from the terminal. But most often one will use the Run Code and get stuck. Then force kill the run. Then move to terminal.

**Comment by TryerGit** [comment]
Have you tried running it under linux ? In my experience, in linux, run/debug sessions happen in the integrated terminal that can very well accept user input. Under windows, it shows either in external cmd console or else in debug console. The latter, indeed, does not accept user input. However, on my windows machine, I installed WSL and run "code ." from within WSL. This effectively means that even on the window machine, it runs as if it is under linux. This allows it to run in the terminal windows that is integrated.

If I understand correctly, one cannot run from a windows platform in the integrated terminal.

**Comment by connor4312** [comment]
Debuggers have the ability to launch their programs in VS Code's integrated terminal, rather than purely in the REPL. If the debugger for the language you're using doesn't have this capability, please open an issue on that debugger extension.
