### ISSUE TITLE
vs code git errors with asian character.

### ISSUE THREAD

**Issue by manuzcom** [microsoft/vscode#108706]
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:00:00.397Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

if root path has asian character git shows error like this.
<img width="1415" alt="screenshot_18" src="https://user-images.githubusercontent.com/1845799/96074484-c3c89680-0ee3-11eb-9513-8758cb863b3e.png">

Does this issue occur when all extensions are disabled?: Yes
<img width="466" alt="screenshot_19" src="https://user-images.githubusercontent.com/1845799/96074907-d1325080-0ee4-11eb-9aed-a769fcf579a0.png">

**Comment by manuzcom** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [网络连接已中断  (#108700)](https://www.github.com/microsoft/vscode/issues/108700)

this is not a duplicate of that issue.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/88798
