### ISSUE TITLE
Code folding not working properly when code indentation is not as expected.

### ISSUE THREAD

**Issue by umairkhan-dev** [microsoft/vscode#108718]
Issue Type: <b>Bug</b>

Consider the following code.

```
<?php
$a = 10;
if (true)
    switch ($a) {
        case 10:
            echo '$a is 5';
            break;

        case 15:
            echo '
<h1>Code folding of SWITCH and current CASE not working. May be due to indentation.</h1>
';

        case 20:
            echo <<<HERE
<h1>Code folding of SWITCH and current CASE not working. May be due to indentation.</h1>
HERE;
            break;

        default:
            # code...
            break;
    } else {
    # code...
}
```

Try folding `switch`, `case 15:` or `case 20:`. Also see bmewburn/vscode-intelephense#1454

![VSCode Code Folding](https://user-images.githubusercontent.com/16460954/96097700-b662da80-0eea-11eb-890e-841e2da5ae1f.gif)

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (3.96GB free)|
|Process Argv|--crash-reporter-id a1ca6bf5-7e7a-4d10-9ace-479aaf22cc58|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-mysql-client2|cwe|2.5.9
whitespace-plus|dav|0.0.5
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.7.1
php-debug|fel|1.13.0
auto-complete-tag|for|0.1.0
shell-format|fox|7.0.1
vscode-pull-request-github|Git|0.20.1
gc-excelviewer|Gra|3.0.40
minify|Hoo|0.4.3
code-eol|jef|1.0.11
intellij-idea-keybindings|k--|0.2.41
sftp|lix|1.12.9
git-graph|mhu|1.26.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
php-docblocker|nei|2.1.0
gremlins|nho|0.24.0
es6-css-minify|olb|3.3.2
phpstorm-snippets|phi|1.1.1
vscode-php-getters-setters|php|1.2.3
git-file-history|pom|1.0.1
vscode-css-peek|pra|4.0.0
phpdoc-comment-vscode-plugin|rex|1.3.0
code-spell-checker|str|1.9.2
vscode-icons|vsc|11.0.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by umairkhan-dev** [comment]
Thanks @vscodebot. But it seems that its not duplicate.

**Comment by aeschli** [comment]
For most languages the folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

However, language extensions can provide language aware folding providers. Please check out PHP extensions. From a quick glance in the marketplace it seem [PHP intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client) offers that in the premium edition.
