### ISSUE TITLE
Web: never unbind Cmd/Ctrl+W or other keybindings in browser

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108788]
I feel we are a bit too aggressive to unbind `Cmd+W` (or `Ctrl+W` on Windows) from the browser if we think we cannot override the browser behaviour. I would remove this logic and always keep it bound. From my testing I sometimes see a PWA app close from `Cmd+W` unless I have `Cmd+W` explicitly configured in my keybindings. After all we cannot know for sure if we can use these keybindings or not, so it is always just a guess that we do.

To give some more recent examples, the detection of native fullscreen had to be added to allow users to use `Cmd+W` because we would aggressively unbind it.

Same goes for `Cmd+T` and `Cmd+N`.

**Comment by rebornix** [comment]
Now that we have `window.confirmBeforeQuit`, I think it makes sense to have `cmd+w` bind as the dialog shows up before `cmd+w` takes effect so it's clear to users why their keybindings don't work as advertised (in keybindings editor).

**Comment by borekb** [comment]
Slightly OT, and mostly out of curiosity, but is VSCode team somehow in touch with Chromium / Firefox devs about the possibility to remap `Cmd-W` and other similar shortcuts? It seems important for online IDEs (I've closed Codespaces like 150 times already 😄) and VSCode team is in a unique position to influence this (large, reputable project, plus MS devs are working on Chromium).
