### ISSUE TITLE
Debug and problems filter should be consistent

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#108759]
Ideally it would be great if these could be the same component, similar to the find widget, so that others can re-use it (like in Output). I think they both should take up 100% of the leftover space while not forcing the tabs to hide. Problems currently has this issue but is also responsive while debug filter is not.

## Debug console
![image](https://user-images.githubusercontent.com/35271042/96190829-b61d0c00-0ef7-11eb-8666-d6e8b4102e02.png)

## Problems
![image](https://user-images.githubusercontent.com/35271042/96190369-ffb92700-0ef6-11eb-99e0-80e164403611.png)

**Comment by gjsjohnmurray** [comment]
Related #108723, #93584

**Comment by benPesso** [comment]
I've proposed a more [elegant solution](https://github.com/microsoft/vscode/issues/108723), though I agree; it would make more sense if both panels used the same component under the hood.

**Comment by isidorn** [comment]
I think this proposal makes sense. We tried to initially do it with just one compoenent but there was less code reuse than I expected.
Though we should still only have one...

**Comment by benPesso** [comment]
@isidorn @roblourens Just wondering if there's any roadmap for this issue to be resolved?

**Comment by roblourens** [comment]
We do better here now, they are a shared component and they both have the behavior of shifting down below the tabs when the panel gets narrow. One thing missing

> should take up 100% of the leftover space while not forcing the tabs to hide.

I think this is hard to do with the way the layout works, the tabs assume that the right section won't shrink, and the behavior here is a little funky sometimes. But I think it's better now and ok as-is.
