### ISSUE TITLE
"editor.quickSuggestions" should be true by default for Markdown

### ISSUE THREAD

**Issue by phuctv95** [microsoft/vscode#108777]
When I open a _Markdown_ file, **it's better if when I type some characters, vscode suggests the _word_ and just press tab to use the suggestion**. Of course this can be done by setting "editor.quickSuggestions" to true like following, but I think it should be default value for markdown file.

```json
"[markdown]": {
    "editor.quickSuggestions": true
}
```

Default behavior now: ctrl + space to show the suggestions.

**Comment by gjsjohnmurray** [comment]
Based on https://github.com/microsoft/vscode/issues/108536#issuecomment-708996559 I think it's unlikely that the default will be changed.

**Comment by mjbvz** [comment]
While writing text instead of code, word based suggestions are usually more of a distraction than helpful. We let you enable them if you prefer but `off` is a better default for markdown

**Comment by ell1e** [comment]
@mjbvz maybe the actual problem is that suggestions are too easy to accidentally activate by default, and therefore more disruptive than they should be? if that was addressed, it might be less distracting to enable them in more places
