### ISSUE TITLE
"debug.node.autoAttach" showing Unknown Configuration Setting

### ISSUE THREAD

**Issue by ateeqrehmani** [microsoft/vscode#108790]
VSCode Version: 1.50.1 (system setup)
OS Version: Windows_NT x64 10.0.18362 (Windows 10)
![119469970_1575678082591960_5655906693726152435_o](https://user-images.githubusercontent.com/50024356/96257214-66ac0e00-0fd3-11eb-88e0-3413955299ab.jpg)

Auto attach debug functionality was working fine till last night.
now it is not working and showing "Unknown Configuration Setting" in setting.json file

**Comment by connor4312** [comment]
See the [latest release notes](https://code.visualstudio.com/updates/v1_50#_javascript-debugging)

**Comment by ateeqrehmani** [comment]
@connor4312 debugger is listening but not attaching to the process as per latest documentation. please see screen shot.

PS: I am running nestjs project with following command
nest start --debug --watch

![119469970_1575678082591960_5655906693726152435_o](https://user-images.githubusercontent.com/50024356/96295559-66c60100-1007-11eb-9232-0a4d7fcb5e97.jpg)

**Comment by connor4312** [comment]
Did you reload/restart the terminal after setting that, and do you see the Auto Attach badge in the status bar?

Also, you do not need the `--debug` flag with auto attach set to `always`

**Comment by ateeqrehmani** [comment]
@connor4312 After restarting the system now debugger is attaching but facing another problem
"Could not load source '....': Unable to retrieve source content."
I had solved this problem in older version by adding below in in setting.json but now this is also deprecated.
"debug.javascript.usePreviewAutoAttach": false,

**Comment by ateeqrehmani** [comment]
@connor4312  i have added "trace": true in launch.json file and reproduced the same issue, but unfortunately unable to find debug log file.
can you please tell me the exact name or location.

**Comment by connor4312** [comment]
Ah, sorry, for auto attach you want to add this to your user settings:

```
"debug.javascript.terminalOptions": {
  "trace": true
},
```

**Comment by ateeqrehmani** [comment]
@connor4312 i have uploaded log file
https://microsoft.github.io/vscode-pwa-analyzer/index.html

**Comment by ateeqrehmani** [comment]
[Uploading vscode-debugadapter-0.json.gz…]()

**Comment by connor4312** [comment]
That link doesn't work

**Comment by ateeqrehmani** [comment]
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode/files/5437612/vscode-debugadapter-1.json.gz)
@connor4312 check this one

**Comment by connor4312** [comment]
In the log you sent, it doesn't look like you hit the case where

> "Could not load source '....': Unable to retrieve source content."

However, looking through the logs I notice what's probably causing it -- the sourcemaps for your code have source URLS like `"../../../../../src/components/ethereum/abi/DeployerAbi.ts"`, so that resolves to `"C:/src/components/ethereum/abi/DeployerAbi.ts"` which I assume is not the correct path.

Are you compiling with tsc? If so please share your tsconfig.json and I can point you in the right direction as for what you need to tweak.

**Comment by ateeqrehmani** [comment]
@connor4312 

here is my tsconfig.json

{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "resolveJsonModule": true
  },
  "exclude": ["node_modules", "dist"]
}

**Comment by connor4312** [comment]
Try removing `baseUrl`
