### ISSUE TITLE
Terminal assuming wrong time format

### ISSUE THREAD

**Issue by zeMinimalist** [microsoft/vscode#108705]
Issue Type: <b>Bug</b>

My system settings are set to display the 24/h time format. When I open the actual terminal (outside of VS Code) and I run "npm run dev", it displays the time format on the upper right as 20:35:17 (correct). But when I run that same command in VS Code's terminal window, it shows 8:35:17 PM (incorrect). Can you please inherit the system settings? Or is there some way that I can change my region settings in VS Code?

Otherwise, I'm extremely impressed as I just switched over from Sublime Text 3.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 6f9857a9-c97d-48dc-b154-c0b5dba358cf|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
You could try changing the value of `terminal.integrated.detectLocale` to see if that fixes it. If that's not the problem, you would need to diff the contents of the `env` command in each terminal and figure out which one is influencing the program.

**Comment by zeMinimalist** [comment]
I tried changing this value in VS Code from Auto to Off to On, and it doesn’t seem to be effecting this timestamp.

I don’t understand what you want me to do regarding diffing contents. But if it helps, here is a screenshot from Terminal:


And here is a screenshot from there terminal window inside VS Code:


The timestamp on the upper right is what I’m referring to. One is in the 24-h time format, and the other is stuck in the 12-h format with “AM” and “PM”. This is after running the same command in the same folder. The only difference seems to be the app that I’m using (Terminal vs VS Code).

Simon Hartigan

**Comment by Tyriar** [comment]
@zeMinimalist By diffing I mean run `env` in each of the terminals and identify which environment variables are different, I think that's the only thing that could influence the node module to print something differently there.

**Comment by zeMinimalist** [comment]
You're right, that's the problem. The Terminal window shows: "LANG=en_GB.UTF-8" and the VS Code shows: "LANG=en_US.UTF-8"

**Comment by Tyriar** [comment]
That environment variable is influenced by `terminal.integrated.detectLocale` so I'd recommend setting that to `"terminal.integrated.detectLocale": "off"`, though I wouldn't expect it to do anything here. My guess outside of that is that `$LANG` is being set by one of your launch scripts, check `~/.bashrc`, `~/.zshrc`, `~/.bash_profile`, etc. for `export LANG=...`. Closing this out as it seems to be an environment setup issue.
