### ISSUE TITLE
JavaScript function is not listed in "ctrl+shift+o"

### ISSUE THREAD

**Issue by qlqllu** [Microsoft/vscode#10877]
- VSCode Version:1.4.0
- OS Version: Windows10

Steps to Reproduce:

1.  Create a JS file with this content:
```
function f1(){};

var obj = f1({
    p1: function(){}
});

```
2.  Open this JS file and type "ctrl+shift+o", notice that the `p1` function is not listed in the symbols list.
3. However, `p1` can be listed in this file 
```
function f1(){};

var obj;
obj = f1({
    p1: function(){}
});

```

Please notice that the only difference is the place to declare the `obj` variable.

**Comment by sandy081** [comment]
@qlqllu I do not see p1 listed in any of the scenarios and I think it wont be listed as it is a member of an anonymous object

**Comment by qlqllu** [comment]
p1 is listed in sublime.

**Comment by sandy081** [comment]
@qlqllu Ok that's interesting. I will redirect this to our js language server team and see if they can build such symbols too.

**Comment by qlqllu** [comment]
Thanks!

**Comment by waderyan** [comment]
Thank you for opening this issue @qlqllu. Moving to JavaScript language service team.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10558
