### ISSUE TITLE
Quick way to navigate to a folder in the explorer (left side)

### ISSUE THREAD

**Issue by mw-senthil** [microsoft/vscode#108747]
Say a key combo:  Cntrl+alt+G (go to folder)
Brings a window start typing the path foo/bar/bar2/...
As the user types goes to a folder

This would allow the user to navigate to a folder quickly especially in large projects

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
