### ISSUE TITLE
console.log is not Display in debugger 

### ISSUE THREAD

**Issue by guogaigai** [Microsoft/vscode#10870]
- VSCode Version:1.3.1
- OS Version: ubuntu 12.04

Steps to Reproduce:

1. I Installed the Debugger for chrome extension 
2. I try to add console.log in chromeDebug.js and the vscode-chrome-debug-core/out/chrome/chromeDebugAdapter.js and other files in the same directory 
3. When i press F5 to debug webapp on chrome debugger , i can not see the console.log info i added  in the Debug Console. 

Does there is any special of the debugger to show console.log ? How can i see the logs in the debugger 

I am looking forward to your reply ,thank you very much ~

**Comment by guogaigai** [comment]
@weinand  Can you answer my question ? thanks

**Comment by weinand** [comment]
The chrome debugger is a separate extension and not part of VS Code. I'll will move this issue to the correct repository.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-chrome-debug#214
