### ISSUE TITLE
menubarControl.ts tracks window focus even if hidden or not showing

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#108712]
Steps to Reproduce:

1. use web and have the menubar hidden
2. open dev tools, put a breakpoint into `menubarControl.ts#onDidChangeWindowFocus`
3. click into page

=> 🐛 breakpoint is hit

I would neither expect the menu to do any work when not enabled nor when not visible.

**Comment by bpasero** [comment]
I still see that this code is hit even though the menu is hidden in web:

https://github.com/microsoft/vscode/blob/0baf6bb9cca978e6f3527b96331e27573b0dfb24/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L205-L205

**Comment by bpasero** [comment]
@sbatten I still don't understand why the menu needs to be updated when not opened. Can we not run this code when the user clicks on the "File" menu lazily?

**Comment by sbatten** [comment]
this code is shared with the native menu bar which cannot calculate information lazily. for simplicity the 2 models are kept as similar as possible. this is now only happening when the menu is visible and the user switches workspaces/windows
