### ISSUE TITLE
Re-run last launch command with state

### ISSUE THREAD

**Issue by TimKingtonFC** [microsoft/vscode#108799]
I would like to have a re-run last launch command like Eclipse's.  Similar to the re-run task command: https://github.com/microsoft/vscode/issues/25310

When I'm running tests, the launch.json entry uses my current context - open file and line.  In the typical flow, I run a test, see that it fails, make a code change, and want to run the test again.  Right now I have to navigate back to the test and run from there.  If there was a re-run task command I could iterate while staying in the code I'm working on.

**Comment by weinand** [comment]
This feature request makes a lot of sense. Since all "debug launches" go through a single piece of code it should be possible to remember everything needed to provide a generic "re-run"/"re-debug"

**Comment by isidorn** [comment]
Agree it makes sense. Let's assign to Backlog and potentially add this in the future.

**Comment by weinand** [comment]
@TimKingtonFC please check out this extension: https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer
It provides "re-run" and a "re-debug" commands.

**Comment by isidorn** [comment]
Oh even better. This can be handled from the extension side.

**Comment by weinand** [comment]
But only for running tests supported by the extension. So it is not a generic solution.

**Comment by isidorn** [comment]
Yeah, but I think there could be an extension that genericly solves this.
