### ISSUE TITLE
Source control text box scroll issue after switcing panels

### ISSUE THREAD

**Issue by jacobweber** [microsoft/vscode#108823]
Issue Type: <b>Bug</b>

Go to the Source Control tab, click the comment text field, and type some text that wraps to multiple lines. Then hide the side bar, and show it again. The scroll position of the text field will be messed up.

![source_control_scroll 2020-10-16 11_07_33](https://user-images.githubusercontent.com/542988/96293553-cee0fc80-0f9f-11eb-957c-4488d5e633c8.gif)

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|--crash-reporter-id ee98133f-4180-44b0-86f2-150582a5f918|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.3.0
ng-template|Ang|0.1001.0
vscode-intelephense-client|bme|1.5.4
npm-intellisense|chr|1.3.1
mustache|daw|1.1.1
vscode-eslint|dba|2.1.10
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
vscode-powertools|ego|0.61.0
php-debug|fel|1.13.0
vscode-favorites|how|1.8.3
svn-scm|joh|2.12.4
vscode-apache|mrm|1.2.0
python|ms-|2020.9.114305
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
hexeditor|ms-|1.3.0
debugger-for-chrome|msj|4.12.11
java|red|0.69.0
vscode-yaml|red|0.11.1
slack|soz|0.0.14
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-maven|vsc|0.24.2
sync-rsync|vsc|0.36.0
jinja|who|0.0.8

</details>

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/108067
