### ISSUE TITLE
Can't format selection using ESLint

### ISSUE THREAD

**Issue by Tsimopak** [microsoft/vscode#108808]
- VSCode Version: 1.50.1
- OS Version: Windows 

Steps to Reproduce:

I found out that if I write in my `settings.json` that:

```json
  "eslint.format.enable": true,
  "[javascriptreact]": {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint",
  }
```
Then I can format the whole page using `ALT + SHIFT + F` with ESLint ( or right click -> Format Document ).

I can also see once I right click -> `Format Selection With....` then I can see ESLint as an option.

But if I select a line and press right click, then `Format Selection With...` I can't find the Eslint option. ( or as a shortcut `CTRL+K` )

So how can I format selection with ESLint?

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> I can also see once I right click -> Format Selection With.... then I can see ESLint as an option.

Without a selection you shouldn't see 'Format Selection With' Are you sure that this wasn't "Format Document With..."?

@dbaeumer Does ESLint contribute a range formatter?

**Comment by dbaeumer** [comment]
@jrieken  No, ESLint doesn't contribute a range formatter since they have no API to do this.

**Comment by jrieken** [comment]
Ok. Thanks for clarifying @dbaeumer
