### ISSUE TITLE
Terminal process failed to identify the path of shell exicution

### ISSUE THREAD

**Issue by Tejaswini-code** [microsoft/vscode#108845]
Issue Type: <b>Bug</b>

When I run the program, I take the essue that "The terminal process failed to launch: Path to shell executable "C:\Windows\system32\cmd.exeC:\MinGW\binC:\MinGW\bin" does not exist." 
I resquested please help me how to solve this problem.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (1.33GB free)|
|Process Argv|--crash-reporter-id 16f5496c-e031-44f6-b435-ee278e460e41|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
c-cpp-compile-run|dan|1.0.11
code-runner|for|0.11.1
cpptools|ms-|1.1.0-insiders2

</details>

**Comment by Tyriar** [comment]
Looks like you have set `terminal.integrated.shell.windows` incorrectly in your settings file. Additionally, you may be running under compatibility mode which will break the terminal https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch#_the-terminal-exited-with-code-1-on-windows-10
