### ISSUE TITLE
[Jupyter notebook]: change the default output color for numbers

### ISSUE THREAD

**Issue by mxgc** [microsoft/vscode#108837]
Provide an option to change the output color for numbers. On dark background, the default deep blue color is hardly legible. 

![A80D7D65-E5A3-47B2-8241-4EF828308288](https://user-images.githubusercontent.com/62173553/96320070-25f9c800-0fc6-11eb-97ca-d1c42954edd8.png)

**Comment by mxgc** [comment]
In addition, the tool `Developer: Inspect Editor Tokens and Scopes` is not available in Jupyter notebooks.

**Comment by rebornix** [comment]
Please file against Python extension.
