### ISSUE TITLE
Zoom Reset (CMD + 0) dosn't work on wireless Mac Magic Keyboard

### ISSUE THREAD

**Issue by humphd** [microsoft/vscode#108813]
- VSCode Version: 1.51.0 (master)
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. On a Mac using a wireless Magic Keyboard (i.e., no numpad), zoom the view size using `CMD+ +` 
2. Try to reset the zoom to normal using `CMD + 0`

Instead of resetting the zoom, the side panel is focused instead

Does this issue occur when all extensions are disabled?: Yes

I have a Mac wireless Magic Keyboard with no numpad, like this one:

![MLA22LL](https://user-images.githubusercontent.com/427398/96287175-8598a900-0faf-11eb-96a8-e88bc710a4c6.jpg)

In browsers (Chrome, Firefox, etc) using `CMD+ +` will zoom in, `CMD + -` will zoom out, and `CMD + 0` will reset the zoom level to normal.

In VSCode, this doesn't work.  I did some research, and it looks like the keybinding for zoom reset is `CMD + NUMPAD_0`:

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/electron-sandbox/desktop.contribution.ts#L34

The binding for `CMD + KEY_0` is set here in the FocusSideBarAction:

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/sidebar/sidebarPart.ts#L317

Because there is no number pad on these keyboards, users expect `CMD + 0` to reset, but this is impossible.

Could we rebind the Zoom Reset action to `CMD + KEY_0`?  It's more commonly known than the sidebar focus in my opinion.

**Comment by alexdima** [comment]
This is not a keybinding dispatching problem, but rather a problem with our default keybindings, where we have opted to follow browser zoom keybindings for zooming in or zooming out, but not for resetting the zoom.
