### ISSUE TITLE
Terminal often stuck

### ISSUE THREAD

**Issue by wutz** [microsoft/vscode#108811]
When i use terminal to enter some thing, it often gets stuck for a short time. At the same time the process window use 100% cpu.

![image](https://user-images.githubusercontent.com/9458625/96280039-0d130600-100a-11eb-9d79-3ea04a2b3115.png)

![image](https://user-images.githubusercontent.com/9458625/96280275-5a8f7300-100a-11eb-84c6-11e860d2a81a.png)

**Comment by mrasong** [comment]
same issue in macOS big sur Beta 10.

**Comment by Tyriar** [comment]
Thanks for the report, can you use devtools (via Help menu) to save and upload a profile (in the performance tab) so I can check it out?

**Comment by mrasong** [comment]
> Thanks for the report, can you use devtools (via Help menu) to save and upload a profile (in the performance tab) so I can check it out?


here's the profile.

[Profile-20201029T233523.json.zip](https://github.com/microsoft/vscode/files/5459533/Profile-20201029T233523.json.zip)
