### ISSUE TITLE
Unselecting selection among multi-selection and pressing DEL delete latest unselected item

### ISSUE THREAD

**Issue by yann-papouin** [microsoft/vscode#108885]
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open a project/workspace with multiple files
2. Select a range of files using SHIFT modifier
3. Use CTRL modifier to unselect one file from current selection
4. Press DEL to delete selection
5. A confirmation to delete will prompt about deleting the latest unselected file
6. Finally the unselected file is deleted

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Yeah this is as designed. We always execute explorer commands on focused items, not on selected. Selection is respected only if focus belongs to it.
I see how in some cases this is not intuitive. However for now we would not change this.

**Comment by eamodio** [comment]
This imo is really bad and I was bitten by it by deleting the exact thing I wished to NOT delete. The `del` shortcut should go with the selection (if there is any) over the focused item.

**Comment by isidorn** [comment]
@eamodio but then do you argue that all commands in the explorer should just go with the selection, or only the delete one?
Does this hold when triggering via keyboard, context menu, command palette or always?

**Comment by mystiquewolf** [comment]
Why would someone select files without intention to act on them?

**Comment by github0013** [comment]
I have been having this issue, and I am hoping this gets fixed soon.

https://i.gyazo.com/51178dd63daef7bb9fa451c521ce8795.mp4

1. shift + DOWN to select files
2. control (or command) + CLICK to deselect a file
3. control (or command) + DELETE to delete the files

*don't click anywhere else between 2 and 3

**Comment by psychopatt** [comment]
I was just bitten by this and had to dig up the victim from the trash, so I took the time to understand what had happened and figured out this behaviour. Now I realize it already had happened when copy/pasting files, whithout me investigating since it was less problematic. 

> @eamodio but then do you argue that all commands in the explorer should just go with the selection, or only the delete one? Does this hold when triggering via keyboard, context menu, command palette or always?

So I don't know if there's any other command than these, but I think selection should be used over focus when present, since as @mystiquewolf perfectly worded it:

> Why would someone select files without intention to act on them?
