### ISSUE TITLE
Custom snippet $TM_SELECTED_TEXT not show suggestion

### ISSUE THREAD

**Issue by Damix48** [microsoft/vscode#108892]
Custom snippet:
```
"span inglese": {
    "prefix": "eng",
    "body": "<span xml:lang=\"en\">${TM_SELECTED_TEXT:$1}</span>",
    "scope": "html"
},
```

Sometime there is not any suggestion for the snippet:
![issue1](https://user-images.githubusercontent.com/23702345/96237999-3f871980-0f9e-11eb-8bd1-ae8db614416a.gif)

Steps to reproduce:
1. Clone the repo (https://github.com/Damix48/vscode-issue) that contains `personaggi.html` and `main.code-snippets`
2. Open `personaggi.html`
3. Select **random** word
4. With some words the snippet `eng` (name: `span inglese`) works fine.
5. With other **random** words not show the suggestion for the snippet

System:

- VSCode Version: 1.50.1 d2e414d9e4239a252d1ab117bd7067f125afd80a 2020-10-13T15:06:15.712Z
- OS Version: Windows_NT x64 10.0.19041 and Linux distros

Does this issue occur when all extensions are disabled?: Yes

Problem 1 of #108784

**Comment by jrieken** [comment]
Seems to be a problem with find words at lines longer than 1000 characters

**Comment by jrieken** [comment]
This is very good find btw. Thanks!

**Comment by jrieken** [comment]
To verify:

* have a line with words which in total is longer than 1000 characters
* at the start of the line select a word and type `e`
* make sure to see any suggestions
