### ISSUE TITLE
Setting sync does not recognize github account for the github pull requests extension

### ISSUE THREAD

**Issue by webczat** [microsoft/vscode#108849]
Hi,
I believe settings sync and github pull requests and issues extension use the same github account (assuming someone syncs using github instead of microsoft account). Normally if I first set up github pull requests then I don't have to re signin to turn on settings sync, probably it works both ways.

However, the extension does not seem to cooperate with settings sync when installing new vscode and first populating local settings. Here is how to reproduce:
* Install vscode-insiders, inside of it install github pull requests extension, and sign into github for both pull requests and settings sync.
* Wait for extensions and settings to be synced
* Remove vscode configuration and start vscode again
* Turn on settings sync choosing to sign in with github
* After completing the signin, observe that the github pull requests and issues extension does not automatically sign you in to the same account, instead you seem to get a sign in request and have to do this again

I would expect that, in case of github-based syncing, the extension recognizes the fact you are already signed into github and does not require further input.

**Comment by RMacfarlane** [comment]
This is unfortunately as designed - when you sign into GitHub, you request a token with certain permissions. In this case, the GitHub Pull Requests and Issues extension requires additional permissions that settings sync does not, so the same token can't be reused.

**Comment by webczat** [comment]
but then if you re-request the token, then it is used for both settings sync and gh pull requests and issues? I believe that still makes for a bit confusing user experience, not the fact you have to relogin but the fact it's not quite clear what is going on...

**Comment by webczat** [comment]
actually can I request this is made somehow more clear that the extension needs more permissions from github and has to rerequest the token? Do I assume correctly that if the gh issues and pull requests extension was installed first it would not require I relogin?
Not even sure what happens in the reverse case where I first turn on settings sync, then enable gh pull requests and issues, but there are no previously synced settings for it.
