### ISSUE TITLE
Custom Editors should have ability to use normal diff view

### ISSUE THREAD

**Issue by kkukshtel** [microsoft/vscode#108836]
Right now, Custom Editors are used anytime in Code where the file is being referenced. This means that a diff for a file that uses a custom editor looks something like this:

![image](https://user-images.githubusercontent.com/7715279/96310891-46318300-0fd6-11eb-8ba6-a85f4331890c.png)

It would be great if there was a way in the custom editor to be able to toggle between the webview or a standard file view when viewing the diff on a file that uses a custom editor.

**Comment by mjbvz** [comment]
Closing due to lack of additional feedback over the past year
