### ISSUE TITLE
Safari: editor/notebook web worker is not included in content security policy

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#108833]
Steps to Reproduce:

1. Open Codespace in Safari
2. Install GitHub Issue Notebook, create a notebook, stage it, make more modifications
3. In SCM viewlet, click the entry from pending changes

Instead of opening a diff editor, we throw an error `The operation is insecure` due to 
```
Refused to load https://rebornix-microsoft-vscode-github-issue-notebooks-jm29.ppe.github.dev/workbench-page/web-standalone/insider-a522f37/out/vs/base/worker/workerMain.js#notebookEditorWorkerService because it appears in neither the child-src directive nor the default-src directive of the Content Security Policy.
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
It applies to editor worker too so it's not notebook specific 


```
Refused to load https://rebornix-microsoft-vscode-github-issue-notebooks-jm29.ppe.github.dev/workbench-page/web-standalone/insider-a522f37/out/vs/workbench/services/extensions/worker/extensionHostWorkerMain.js#WorkerExtensionHost because it appears in neither the child-src directive nor the default-src directive of the Content Security Policy.
```

**Comment by alexdima** [comment]
Hmm this works fine for me:

![image](https://user-images.githubusercontent.com/5047891/96562747-6789bc00-12c1-11eb-82ef-3a3e723607f9.png)

**Comment by alexdima** [comment]
This works on latest.
