### ISSUE TITLE
Wavy text scroll on scaled display settings

### ISSUE THREAD

**Issue by zakutin** [microsoft/vscode#108805]
I'm not sure if this was already covered in issues here. I'm experiencing a wavy effect by text scrolling with precision touchpad when 125% or 150% display scaling is enabled in Windows. This not happens in Jupyter Notebook files -- it made of moving blocks with code, rather the moving text itself. 

- VSCode Version: 1.50.1
- OS Version: Windows 10 x64 2004

Steps to Reproduce:

1. Set 125% or 150% in Windows display settings
2. Open any code or text in VS Code
3. Scroll with touchpad
4. See wavy text

Does this issue occur when all extensions are disabled?: Yes

![ezgif-7-929fc3fe9d44](https://user-images.githubusercontent.com/53969222/96272961-1337c100-0fcf-11eb-8806-02ec160e3a59.gif)

**Comment by zakutin** [comment]
The same effect happens also on normal 100% display scaling, but with zoomed vscode appearance (Ctrl+plus).

**Comment by zakutin** [comment]
Looks like this happens on all platforms...

**Comment by alexdima** [comment]
This is due to how Chromium implements `window.zoomLevel` and zoom levels for Windows.

We render rectangles at integer coordinates that perfectly touch each-other, but Chromium's implementation of zooming introduce rounding errors and create such artefacts.

**Comment by zakutin** [comment]
@alexdima, I went through your comments, thanks for explanation, it is good idea to use `editor.mouseWheelZoom` as it increases font size instead of ui.
