### ISSUE TITLE
Snippet replace-range incorrect

### ISSUE THREAD

**Issue by Damix48** [microsoft/vscode#108894]
Custom snippet:
```
"span inglese": {
    "prefix": "eng",
    "body": "<span xml:lang=\"en\">${TM_SELECTED_TEXT:$1}</span>",
    "scope": "html"
},
```

Sometime the snippet delete 2 char of the text after and not insert `$TM_SELECTED_TEXT`:
![issue3](https://user-images.githubusercontent.com/23702345/96238358-ad334580-0f9e-11eb-848e-6e32af937ad9.gif)
Not seletect text:
![issue4](https://user-images.githubusercontent.com/23702345/96242168-70b61880-0fa3-11eb-90df-a54e91cf284c.gif)

Steps to reproduce:
1. Clone the repo (https://github.com/Damix48/vscode-issue) that contains `personaggi.html` and `main.code-snippets`
2. Open `personaggi.html`
3. Select **random** word
4. With some words the snippet `eng` (name: `span inglese`) works fine.
5. With other **random** words the snippet not insert the selected text and delete 2 char
6. If no word is selected sometimes the snippet delete 2 char

System:

- VSCode Version: 1.50.1 d2e414d9e4239a252d1ab117bd7067f125afd80a 2020-10-13T15:06:15.712Z
- OS Version: Windows_NT x64 10.0.19041 and Linux distros

Does this issue occur when all extensions are disabled?: Yes

Problem 3 of #108784

**Comment by jrieken** [comment]
Sorry, fuzzy steps don't work. What word/character is deleted? Can you be precise with exact steps, actual and expected outcome?

**Comment by Damix48** [comment]
Steps to reproduce:
1. Clone the repo (https://github.com/Damix48/vscode-issue) that contains `personaggi.html` and `main.code-snippets`
2. Open `personaggi.html`
3. Select `gran` at _Ln 140 col 596-600_
4. Type `eng` to use the custom snippet

Actual result:
From
```
[...] gran parte di [...]
```
to
```
[...] <span xml:lang="en"></span>arte di [...]
```
Not insert `gran` and delete ` p` (space and 'p')
![issue3](https://user-images.githubusercontent.com/23702345/96238358-ad334580-0f9e-11eb-848e-6e32af937ad9.gif)

Expected result:
From
```
[...] gran parte di [...]
```
to
```
[...] <span xml:lang="en">gran</span> parte di [...]
```
