### ISSUE TITLE
Find window text and icons becomes blurry sometimes

### ISSUE THREAD

**Issue by KevinNovak** [microsoft/vscode#108864]
Find window text:
![image](https://user-images.githubusercontent.com/11231402/96347417-b0e2cd00-106f-11eb-90ac-acaa52591795.png)

Notice all the text in the find window is blurry, including the icons. The open file/name above it is still clear.

- VSCode Version: 1.50.1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

I don't know the exact steps but here is what I think led to this:

1. Highlighted some text in a file
2. Typed "Ctrl + F" to open the find window for that text
3. Text was blurry

Immediately after this happened I repeated it a second time and it didn't show up blurry.

Does this issue occur when all extensions are disabled?: Yes/No
No, could not reproduce a second time.

**Comment by rebornix** [comment]
@KevinNovak can you try running vscode with gpu disabled `code --disable-gpu` and see if it helps?

**Comment by KevinNovak** [comment]
@rebornix it hasn't happened for me since, but I'll set this up as my default and post here if it happens again.

**Comment by rebornix** [comment]
sure, I'll close it for now.
