### ISSUE TITLE
 I want to use $ref in configurationDefaults in package.json.

### ISSUE THREAD

**Issue by wraith13** [microsoft/vscode#108875]
I'm making extensions.
I want to use $ref in configurationDefaults in package.json, like this:

```json
        "configurationDefaults":
        {
            "[typescript]": { "$ref": "./language-configuration/typescript.json" },
            "[cpp]": { "$ref": "./language-configuration/cpp.json" },
            "[ignore]": { "$ref": "./language-configuration/ignore.json" }
        }
```

I can't cover many languages, so I need the cooperation of many people, but if this is not possible, conflicts will occur frequently when receiving a pull request with default settings for each language.

**Comment by aeschli** [comment]
duplicate of https://github.com/microsoft/vscode/issues/81782
