### ISSUE TITLE
Why vscode inserts 4 spaces even after I tell it not to

### ISSUE THREAD

**Issue by TheVeryDarkness** [microsoft/vscode#108876]
Issue Type: <b>Bug</b>

I've set Detect-Indentation to false, Insert-Spaces to false, and tab-size to 1, but every time I tab a tab in markdown, vscode inserts 4 spaces.
I've noticed that vscode inserts tab when I tab a tab in .cpp files.
Is it a feature for markdown?

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.90GB (1.85GB free)|
|Process Argv|--crash-reporter-id 506201bc-1fce-46fa-bbf1-77e7d184cab1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
code-gnu-global|aus|0.2.2
autolispext|Aut|1.3.0
masm|blt|0.0.4
gltf-vscode|ces|2.3.1
doxdocgen|csc|1.0.1
docs-markdown|doc|0.2.81
vscode-firefox-debug|fir|2.9.1
go|gol|0.17.2
better-cpp-syntax|jef|1.15.0
vscode-language-pack-zh-hans|MS-|1.50.2
python|ms-|2020.9.114305
remote-containers|ms-|0.145.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.1
cmake-tools|ms-|1.4.2
cpptools|ms-|1.1.0-insiders2
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3014
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3007
tcl|ras|0.1.0
java|red|0.69.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled?

**Comment by mjbvz** [comment]
Also please share example markdown that demonstrates the problem

**Comment by TheVeryDarkness** [comment]
> Does the problem also happen if you launch with all extensions disabled?

Wow, vscode insert exact one tab this time. But I wonder how I can get to know which extension does that.
And thank you all.

**Comment by localjo** [comment]
Do you have an `.editorconfig` file in your project or workspace? The settings in that file could be overriding your VS Code settings.

**Comment by mjbvz** [comment]
Closing this as we steps to be able to reproduce and investigate this
