### ISSUE TITLE
Safari: minimap shadow renders improperly

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#108822]
* Open Web/Codespace in Safari
* Turn on minimap
* Make the window size relatively small (for example, half width of the screen)
* The shadow element is rendered weirdly (as a dark gray rectangle)

<img width="993" alt="image" src="https://user-images.githubusercontent.com/876920/96293136-229f1600-0f9f-11eb-853e-62eb35aa0322.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
I have investigated this and it appears it is a Safari bug:

https://jsfiddle.net/kvgsqfz1/

FF:
![image](https://user-images.githubusercontent.com/5047891/97443048-d0f57480-192a-11eb-92b3-6be4b20a3174.png)

Chrome:
![image](https://user-images.githubusercontent.com/5047891/97443100-e36fae00-192a-11eb-9acf-b0882a22441f.png)


Safari:
![image](https://user-images.githubusercontent.com/5047891/97443072-d81c8280-192a-11eb-8f41-a89ce3720e36.png)
