### ISSUE TITLE
The drive or UNC share you selected does not exist or is not accessible

### ISSUE THREAD

**Issue by lystormenvoy** [microsoft/vscode#108802]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.After I move the folder which the VSCode installed in it (e.g. I install in D:\VSCde, then move to E:\VSCode). When I launch VSCode. It will show a messagebox with 'The drive or UNC share you selected does not exist or is not accessible...'.
2.After I close the messagebox, it will show again sometimes.
3. And I don't know how to find what cause this

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Moving the installation folder of VS Code is not supported. You should uninstall and reinstall VS Code in the desired path, instead.
