### ISSUE TITLE
onDidChangeActiveTextEditor fired twice when closing the editor

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#108868]
When using tab switching, for instance (<kbd>Ctrl</kbd>+<kbd>Tab</kbd>) - event is only fired 1 time as expected.

But for closing editor tab (<kbd>Ctrl</kbd>+<kbd>W</kbd>) it is fired 2 times:

1. The editor is undefined
1. The editor is the next tab (editor)

Both documents are text (not images or anything).

---

Version: 1.51.0-insider (user setup)
Commit: 89c002ab02f87102d91efc83c191ef1174756c6a
OS: Windows_NT x64 10.0.18363

**Comment by jrieken** [comment]
Yeah, but we have decided not to fix this. An editor can always be undefined so it doesn't really matter if its undefined for a split seconds or not.  The underlying cause is the mechanics of the workbench
