### ISSUE TITLE
when I split windows to two or more mindless,  and want close one, the vscode show that whether to save the file to close, no matter what I chose, the file will close in all whidows. so my question is how to close one splited windows without any effect to other windows, like vi -O?

### ISSUE THREAD

**Issue by crazyluffy** [Microsoft/vscode#10883]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
We fixed this already for August.

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: 
http://code.visualstudio.com/Download#insiders

**Comment by crazyluffy** [comment]
thanks,i'll try it.
