### ISSUE TITLE
VSCode for Android tablets

### ISSUE THREAD

**Issue by reob-info** [microsoft/vscode#108891]
I would like to suggest and request that VSCode be released for Android tablets.

I like a lot this app and miss it at Android tablets that I use to applications development.

I have used VSCode at Linux but I am migrating to Android and would like to continue using VSCode on Android if it was available.

Thank you for your very valuable work on VSCode, I hope that I can continue having this app as my main development tool.

Best regards,
Fernando Lima

**Comment by hDmtP** [comment]
@reob-info have a look at this => https://marketplace.visualstudio.com/items?itemName=adelphes.android-dev-ext

**Comment by joaomoreno** [comment]
We've made Linux ARM builds available. It's a step closer, but publishing an APK is out of our scope, sorry.
