### ISSUE TITLE
SCM "Open Changes" not opened as a preview if "Open Diff On Click" is false

### ISSUE THREAD

**Issue by hemlok** [microsoft/vscode#108856]
Opening files when "Open Diff On Click" is false by clicking "Open Changes" in the SCM list causes them to be kept open, and doesn't respect the other settings for "enable preview", however when "Open Diff On Click" is true, clicking the file does properly open the diff as a preview.

- VSCode Version: 1.50.1
- OS Version: 10.15.7 (19H2)

Steps to Reproduce:

1. Set `Git > Open Diff On Click` to `false`
2. Change a file, open SCM, and click the "Open Changes" icon next to the changed file.
3. The diff will not be opened as a preview, even if `Workbench > Editor: Enable Preview` and `Workbench > Editor: Enable Preview from Quick Open` are set to `true`

Does this issue occur when all extensions are disabled?: Yes

**Comment by gorogoroumaru** [comment]
Can I take this issue?

**Comment by YounesN** [comment]
I assumed that we only need to respect `Workbench > Editor: Enable Preview`. `Quick Open` is a specific functionality and shouldn't affect this issue. @joaomoreno, please let me know if that's not the case and I will update the PR.

**Comment by joaomoreno** [comment]
Sorry I misunderstood the issue. This is working as designed since when opening files via actions this is considered to be a user explicit action and files aren't open in preview in that case.

The same applies for the Open File action, when "Open Diff On Click" is true.

**Comment by hemlok** [comment]
Hey @joaomoreno, thanks for thinking about the ticket, and I can understand that product rationalisation!

However, as an end user that behaviour you're describing is really not transparent, I would really value if that behaviour was selectable via a setting. e.g. "Explicit actions open in preview: boolean".  

Secondly, would there be any easy ways for me to enable my desired behaviour locally?

**Comment by joaomoreno** [comment]
Unfortunately there is no current workaround... 😢
