### ISSUE TITLE
Safari: multi root workspace does not load

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#108820]
Steps to Reproduce:

1. Run web from local bits `./resources/server/web.sh`
2. In the web UI, Menu -> File -> Open Workspace ..., open a workspace file
3. After reload, the UI is blank, however it opens fine in Edge

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
Turns out the some resources are loaded extremely slow, for example `blob:http://localhost:9888/2258f8e9-acfe-48a1-b6fc-6beefd680af6` but not sure what are those.

**Comment by rebornix** [comment]
remove important as I'm not seeing this issue in Codespace.

**Comment by bpasero** [comment]
I see no loading, no errors. This must be a Safari bug, does not reproduce in other browsers, wth.

**Comment by bpasero** [comment]
I can no longer reproduce.
