### ISSUE TITLE
GIT EXTENSION ENABLED

### ISSUE THREAD

**Issue by gillesarmand225** [microsoft/vscode#108831]
I have this message "No source control providers registered" with git already installed on the computer and the extension enabled. Worked perfectily till today.

**Comment by usernamehw** [comment]
Have you tried different solutions from this: https://stackoverflow.com/questions/46609255/git-missing-in-vs-code-no-source-control-providers ?

**Comment by joaomoreno** [comment]
What output is in `Git: Show Git Output`?

**Comment by gillesarmand225** [comment]
> What output is in `Git: Show Git Output`?

Hi. An error. The commande is not found

**Comment by gillesarmand225** [comment]
> Have you tried different solutions from this: https://stackoverflow.com/questions/46609255/git-missing-in-vs-code-no-source-control-providers ?

Hi. I tried all of them but nothing. It's worked perfectly till for days ago. I've changed nothing in my configuration. 
It's intriguing.

**Comment by joaomoreno** [comment]
Can you reinstall VS Code?
