### ISSUE TITLE
Use "import type" syntax for TypeScript

### ISSUE THREAD

**Issue by cyberalien** [microsoft/vscode#108884]
As of version 3.8, TypeScript supports `import type` syntax for imports.

When using it in VSCode, all automatically imported types default to `import { Whatever }`, even if other imports in the same file use `import type { Whatever }`.

Is it possible to add option to use `import type` syntax for type imports that are automatically added by VSCode?

**Comment by mjbvz** [comment]
Already discussed under https://github.com/microsoft/TypeScript/issues/36038

`import type` only needs to be used in specific cases where you want to ensure the import will not result in a real import. It is better handled by explicitly marking the import instead of automatically doing so

**Comment by cyberalien** [comment]
Thank you for linking that discussion. Following it I found a solution: https://github.com/microsoft/TypeScript/pull/36412#issuecomment-707221008
