### ISSUE TITLE
i cant launch terminal on win 7

### ISSUE THREAD

**Issue by mrtineu** [microsoft/vscode#108816]
Issue Type: <b>Bug</b>

The terminal process "C:\Windows\system32\cmd.exe" failed to launch (exit code: 259).

VS Code version: Code - Insiders 1.51.0-insider (89c002ab02f87102d91efc83c191ef1174756c6a, 2020-10-15T23:17:08.035Z)
OS version: Windows_NT x64 6.1.7601

Extensions: none

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
