### ISSUE TITLE
Tabs not same width with Duospace font

### ISSUE THREAD

**Issue by crystalfp** [microsoft/vscode#108858]
Issue Type: <b>Bug</b>

Open a new file using the duospace font "iA Writer Duospace" (in which m and M are 150% of the other characters). this font is retrievable from [GitHub](https://github.com/iaolo/iA-Fonts/tree/master/iA%20Writer%20Duospace).

Using tabs after a word containing "m" gives the following word not aligned with one of the tab stops
![image](https://user-images.githubusercontent.com/865866/96338024-a0d8e680-108b-11eb-9358-f43c71c7f221.png)
Seems the tabs are strictly equivalent to 4 spaces. I think the tab stops should be every 4 spaces and a tab moves from one tabstop to the next. The problem is similar to issue #108755.

Why I use this font? Because for markdown texts gives a more readable rendering without visual problems, except this one.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (16.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
spellright|ban|3.0.52
github-markdown-preview|bie|0.0.2
markdown-footnotes|bie|0.0.7
markdown-yaml-preamble|bie|0.0.4
vscode-toggle-quotes|Bri|0.3.3
refactorix|chr|0.3.7
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.10
vscode-pandoc|Dou|0.0.8
eslint-disable-snippets|drK|1.2.0
gitlens|eam|10.2.2
vscode-great-icons|emm|2.1.57
vscode-todo-plus|fab|4.18.0
auto-close-tag|for|0.5.9
sass-lint|gle|1.0.6
todo-tree|Gru|0.0.183
code-eol|jef|1.0.11
tag-rename|kri|0.2.1
stack-tabs|kyl|0.0.2
git-graph|mhu|1.26.0
prettify-json|moh|0.0.3
tab-cycle|mpo|1.0.1
notepadplusplus-keybindings|ms-|1.0.5
leaper|Onl|0.6.0
vscode-jscpd|pau|0.3.4
bib|phr|0.3.0
git-file-history|pom|1.0.1
typescript-hero|rbb|3.0.0
vscode-javascript-booster|sbu|14.0.1
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.13
unique-window-colors|stu|1.0.51
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.10
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.3.0

(2 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
This appears to be a special case of #108755 where all characters are monospace, except for `m`. Let's track in #108755
