### ISSUE TITLE
Safari/iPadOS: Settings Editor drop down mispositioned

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#108827]
Steps to Reproduce:

1. Open Web/Codespace on iPadOS
2. Open Settings Editor
3. Search `font-family`, click the gear icon
4. Dropdown menu mispositioned

![IMG_9B8119A09088-1](https://user-images.githubusercontent.com/876920/96297100-36e61180-0fa5-11eb-8aa1-75a01c8240c3.jpeg)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Works fine on desktop Safari, and I don't have an iOS device

**Comment by isidorn** [comment]
This works just fine for me with latest on iPad. Thus closing,
If somebody still see this let me know and I can reopen
