### ISSUE TITLE
VS Code has been moved or deleted after update 1.50

### ISSUE THREAD

**Issue by BrownCoatJustice** [microsoft/vscode#108843]
Hello, I opened this issue because yesterday right after I closed VS Code it updated and every time it updates there is always some error in opening VS Code, after the update my VS Code wasn't available in my PC, this is what it said. 

![image](https://user-images.githubusercontent.com/70653261/96326469-79aff400-104e-11eb-8e13-d2fc6b5149c4.png)

My VS Code has been moved or deleted, this happens every update,  **I tried reinstalling this and it worked fine but this update lets say VERSION: 1.50 has made my VS Code the same way it was 'MOVED OR DELETED'**

- VSCode Version: 1.50
- OS Version: Microsoft Windows [Version 10.0.19041.572] Pro

Steps to Reproduce:

1. I tried installing and reinstalling
2. I searched for VS Code in my PC, but couldn't

Does this issue occur when all extensions are disabled?: _Doesn't relate to the issue._

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
