### ISSUE TITLE
Setting Variable in UI that fails will attempt to set bad value again if user clicks elsewhere

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#10881]
_From @rkeithhill on August 21, 2016 21:50_

I'm in the middle of implementing this cool feature for the PowerShell extension.  I could be doing something wrong but what I notice is if I try to set a value to a variable that is readonly, I get the error message in the UI as expected.  But when I try to click somewhere else to dismiss the error UI, VSCode sends the setVariableRequest again, so we wind up in a bit of a vicious loop.

I can understand why you'd want to apply the value when use clicks away but perhaps you shouldn't do that if A) the last attempt was an error and B) the current value has not changed from the value used during the previous failed attempt. 

However, in the case of a readonly/constant variable, no amount of futzing with the value will. I see that pressing `Esc` helps in this case but things get out of sync a bit until I step again in the debugger:

![vscode-debug-issue1](https://cloud.githubusercontent.com/assets/5177512/17839970/84ca99fc-67b6-11e6-8c80-5dcf62b214b0.gif)

You can see the extensions says no - you can't set an int to `42a` and you get an error message to that effect. So I press `Esc` and things look good.  The value goes back to 42 until I close and re-open the `Autos` container.

_Copied from original issue: Microsoft/vscode-debugadapter-node#55_

**Comment by rkeithhill** [comment]
Cool.  Thanks for fixing this!  @daviwil

**Comment by rebornix** [comment]
Not sure if I'm reproducing this issue correctly but seems this one consists of two different issues

1. `pressing Esc helps in this case but things get out of sync a bit until I step again in the debugger`
2. `But when I try to click somewhere else to dismiss the error UI, VSCode sends the setVariableRequest again, so we wind up in a bit of a vicious loop`

The 1st one is already fixed and now it works perfectly but I'm still seeing the second issue. My way of testing is adding below code to my ruby debugger extension

```
protected setVariableRequest(response: DebugProtocol.SetVariableResponse, args: DebugProtocol.SetVariableArguments): void {
    response.success = false;
    response.body = {
        value: ""
    };
    response.message = "Error!";

    this.sendResponse(response);
}
```

Above code does nothing but tell Debug Host that we are setting the variable wrong but once I click somewhere else, Debug Host invokes this method again.

@isidorn did I miss something here? As the ruby debugger I'm using doesn't support `setVariableRequest` so I didn't implement this feature within my extension so maybe I'm doing this wrongly.

**Comment by isidorn** [comment]
@rebornix the fact that we send the setVariable request when the input gets closed is not unexpected, it was just that with the combination of 1st it was causing a pain.
This way it is fine. Thanks for finding this though
