### ISSUE TITLE
Extension Issues

### ISSUE THREAD

**Issue by DennisKnie** [microsoft/vscode#108870]
We have written the needed data into your clipboard because it was too large to send. Please paste. 
After running the latest update for VSC none of the extensions work. Prior my code would give suggestions on code and would show the color when typing and color in code. Now neither will work. I have uninstalled and reinstalled the extensions but it still will not work.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo specifically have you followed the steps to discover which of your extensions is causing the problem?
