### ISSUE TITLE
Cannot switch to C++11 configurations

### ISSUE THREAD

**Issue by hungrymeow** [microsoft/vscode#108869]
Issue Type: <b>Bug</b>

On settings menu -> Extensions -> C/C++ -> Default: Cpp Standard, although changing my settings from default to c++11, it still gives me errors and warnings as if i were not using c++11 configurations. 
For example: 
using "auto" keyword gives a warning: " warning: range-based for loop is a C++11 extension [-Wc++11-extensions] "
or using lambda expressions gives an error at the comma just before '[' symbol: " error: expected expression "back_inserter(vecVals2),[divisor](int x){return (x%2)==0;}); "

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.86GB free)|
|Process Argv|--crash-reporter-id a5de4c69-7f7a-4a04-83d4-51f9a9892daf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
code-runner|for|0.11.1
vscode-clang|mit|0.2.3
cpptools|ms-|1.0.1
vsliveshare|ms-|1.0.3014
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0

</details>

**Comment by roblourens** [comment]
Please file this issue on the repo for the vscode-cpptools extension:

https://github.com/microsoft/vscode-cpptools/issues

Thanks!
