### ISSUE TITLE
Quick fix icon is broken?

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#108888]
![image](https://user-images.githubusercontent.com/22350/96365870-05577c80-1144-11eb-9c51-1caa4bdad41f.png)

Two problems:

1. It has no contrast and is being displayed over text
2. The mouse cursor over it should be `pointer`

@jrieken Is this you? 😕

**Comment by misolori** [comment]
We've always had this problem, the bottom part of the icon has no fill hence why the text shows through. The only alternative is to show this in the gutter when the first column of the row has text, but I'm not sure if that is technically possible.

**Comment by joaomoreno** [comment]
Could we add a white trace outline to the icon, making it popup in messy locations?

**Comment by misolori** [comment]
Unfortunately strokes don't work on icons:

![image](https://user-images.githubusercontent.com/35271042/96468577-1efad180-11e1-11eb-8eed-940c2f6db81d.png)

We could try to add the same editor bg color with a slight opacity to account for this:

![image](https://user-images.githubusercontent.com/35271042/96469782-73eb1780-11e2-11eb-868c-095e643c545e.png)

**Comment by joaomoreno** [comment]
Oh man, that looks good.
