### ISSUE TITLE
Peek Definition not working for Angular.JS 1.5.8

### ISSUE THREAD

**Issue by vimarshc** [Microsoft/vscode#10882]
- VSCode Version: 1.4.0 (1.4.0)
- OS Version: 10.11.3 (15D21) [OSX El Capitan]

Following are the steps that I've found on various blogs to install Intellisense for Angular.js
1. Create jsconfig.json in the root of the project
2. Install typings via npm 
3. Run `typings install dt~angular --global `                               

I am using a service in my controller, I have used DI to use the service in my controller. 
For example my service is "myService" and the function defined inside the service is "sendRequest". '

Now, the behaviour explained below happens in the controller: 
1. When I hover over the "myService" variable, a hovering message saying "(parameter) myService:any". 

2. When I hover over the "myService" variable while I'm pressing Command, the hovering message displays only one line of the definition of the service. 

3. Now, when I click on "myService" while I'm pressing Command, it takes me to the DI injected variable inside the controller file. When I repeat the action over the variable in the DI array, it doesn't take me anywhere. 

4. When I hover over method "sendRequest" while I'm pressing Command it displays "any" in the hovering message and nothing else.

**Comment by waderyan** [comment]
@vimarshc apologize for the delay here. This issue fell through my issue tracker. 

* Are you still seeing the issue in VSC 1.5? 
* Can you share a short code sample that I can copy and paste? 
* Do you have a different version of TSC then what came bundled (if you don't know the answer is no)?

**Comment by waderyan** [comment]
Closing until more info is provided.

**Comment by gurusinga** [comment]
I'm having the same issue. I'm writing a simple app by using Angular 1.5.10 and ES6.

![screen shot 2016-12-30 at 14 34 06](https://cloud.githubusercontent.com/assets/1540089/21565865/17a37c06-ce9d-11e6-9e09-b4f0e4393b02.png)

**Comment by waderyan** [comment]
@gurusinga can you share your workspace so we can recreate this on our end?
