### ISSUE TITLE
can't open source control "..." menu right after commit

### ISSUE THREAD

**Issue by mbest** [microsoft/vscode#108825]
Issue Type: <b>Bug</b>

From the source control panel, right after I commit by pressing ctrl-enter, I try to open the "..." menu to push the changes, but the menu won't open (it used to work). Instead I have to move the mouse out of the source control panel and back in to get the menu open. 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.42GB free)|
|Process Argv|--crash-reporter-id 35e41115-2557-4b0b-9ebe-75e001ccac44|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-jest|Ort|3.2.0
rewrap|stk|1.13.0
code-spell-checker|str|1.9.2

</details>

**Comment by joaomoreno** [comment]
What an odd issue.

Can you enable `Developer: Toggle Screencast Mode` and

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?
