### ISSUE TITLE
Provide dedicated keyboard shortcuts for changing active stack frame

### ISSUE THREAD

**Issue by penagos** [microsoft/vscode#108844]
It seems the only way today to change the current stack frame using keyboard shortcuts is to bind the `workbench.debug.action.focusCallStackView` command to a key, and then to use the arrow keys/enter to move up and down the stack. Could we get dedicated keyboard shortcuts for moving up and down a frame to use 1 key instead of 3 to change a stack frame?

**Comment by isidorn** [comment]
This is a fair feature request. What commands would you expect "Focus Stack Frame Above", "Focus Stack Frame Below"?
If more users request this I would be open for a PR that adds this.

**Comment by penagos** [comment]
Yes; those sound like reasonable command names. They're also inline with the nomenclature used for focusing the call stack window, i.e. `workbench.debug.action.focusCallStackView`.
