### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Abhinav7867** [microsoft/vscode#108897]
Kindly add and plugins and and live supported editing on vscode to change the html txt and css
Request 
regards

**Comment by bmeschesi** [comment]
Hi @Abhinav7867 ! I don't know if I understand you question, but if you are looking for some plugin to help you in your site development with live reload, try to use this plugin:

Live Server
ritwickdey.liveserver

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/12080 but to be honest, this functionality is best provided by extensions (like ritwickdey.liveserver)
