### ISSUE TITLE
Problems panel

### ISSUE THREAD

**Issue by Armanarmanarman** [microsoft/vscode#108896]
Issue Type: <b>Feature Request</b>

Problems pannel shows correctly the line where is problem located, but it shows "СЌС‚Рѕ РѕР±СЉСЏРІР»РµРЅРёРµ РЅРµ СЃРѕРґРµСЂР¶РёС‚ РєР»Р°СЃСЃ С…СЂР°РЅРµРЅРёСЏ РёР»Рё СЃРїРµС†РёС„РёРєР°С‚РѕСЂ "" something like this. How to solve this issue?

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.3.9600

**Comment by sandy081** [comment]
I would recommend to first file an issue against the extension that is generating this problems for initial investigation.
