### ISSUE TITLE
Customize links discovery/handling in Debug Console

### ISSUE THREAD

**Issue by fabioz** [microsoft/vscode#108853]
I see that from 1.49 onwards there's an API which allows for customization of links through `registerTerminalLinkProvider`, yet, using that API doesn't seem to have any effect on the `Debug Console`, so, this is a feature request to add the same support for the `Debug Console`.

To give some background on my use case, I'd like users to be able to open in a browser the results of a test-run by `Ctrl+Click` (both in the Debug Console and at the Terminal) -- the terminal seems to be customizable already, but links on the Debug Console seem to always open a new editor (and I couldn't find a way to customize it).

-- It's printed by the related test framework as the contents below (and all of those should be opened in a browser):

```
Output:  X:\vscode-robot\local_test\output.xml
Log:     X:\vscode-robot\local_test\log.html
Report:  X:\vscode-robot\local_test\report.html
```

**Comment by isidorn** [comment]
Correct, this is currently not possible. However it is a fair feature request.
For now assigning this to backlog and we might be open to a PR in the future that tackles this.

**Comment by DanTup** [comment]
I have a need for something similar too. The debug output from our process contains hyperlinks that open an external tool, but in the case where you've configured the extension to render this in embedded window, I'd like to be able to handle that link click myself and run it through the code that sets this up.

Either being able to handle all links, or being able to inject some sort of special command-link from the debug adapter would work for me (although I'm not sure how the latter would fit into DAP).
