### ISSUE TITLE
Backwards red underline errors for TypeScript

### ISSUE THREAD

**Issue by ryancwalsh** [microsoft/vscode#108872]
Issue Type: <b>Bug</b>

It seems that people trying to write TypeScript in VSC face this dilemma of choosing between:

1. VSC shows an error (red underline), but the code works, or:
1. If we follow the VSC error tooltip's suggestion, it will "resolve" the error in the editor, but then the code won't run.

See also: https://github.com/microsoft/TypeScript/issues/11235#issuecomment-706751405

![image](https://user-images.githubusercontent.com/2086493/96354020-adffd080-109f-11eb-865e-82995bc5a726.png)

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.9.0
vscode-intelephense-client|bme|1.5.4
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.10
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-language-babel|mgm|0.0.30
dotenv|mik|1.0.1
python|ms-|2020.9.114305
remote-wsl|ms-|0.50.1
sqltools|mtx|0.23.0
react-proptypes-intellisense|OfH|1.0.3
vscode-versionlens|pfl|1.0.8
prisma|Pri|2.9.0
phpdoc-comment-vscode-plugin|rex|1.3.0
vscode-status-bar-format-toggle|tom|2.0.0
vscode-import-cost|wix|2.12.0

</details>

**Comment by mjbvz** [comment]
As you noted, this is a TypeScript issue. Please follow up on the TypeScript repo
