### ISSUE TITLE
statusbar.background can't reset as default color at new window

### ISSUE THREAD

**Issue by Whosydd** [microsoft/vscode#108877]
Issue Type: <b>Bug</b>

when i open a new window, statusbar.background is purple and i can't change it. but after i open a folder,it's ok and i can change it. i don't know why...

ps: i try to reset my computer to check it, but win10 and mac all have this problem 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

![issue](https://user-images.githubusercontent.com/22630678/96357531-a25bea80-112f-11eb-9622-1a4fba7e7af1.png)

Extensions: none

**Comment by gjsjohnmurray** [comment]
Customize `statusbar.noFolderBackground`

See https://code.visualstudio.com/api/references/theme-color#status-bar-colors

**Comment by Whosydd** [comment]
> Customize `statusbar.noFolderBackground`
> 
> See https://code.visualstudio.com/api/references/theme-color#status-bar-colors

@gjsjohnmurray 
i got it, thanks~
