### ISSUE TITLE
Custom snippet $TM_SELECTED_TEXT not insert selected text

### ISSUE THREAD

**Issue by Damix48** [microsoft/vscode#108893]
Custom snippet:
```
"span inglese": {
    "prefix": "eng",
    "body": "<span xml:lang=\"en\">${TM_SELECTED_TEXT:$1}</span>",
    "scope": "html"
},
```

Sometime the snippet not insert `$TM_SELECTED_TEXT`:
![issue2](https://user-images.githubusercontent.com/23702345/96238642-01d6c080-0f9f-11eb-979d-45245cbc3d79.gif)

Steps to reproduce:
1. Clone the repo (https://github.com/Damix48/vscode-issue) that contains `personaggi.html` and `main.code-snippets`
2. Open `personaggi.html`
3. Select **random** word
4. With some words the snippet `eng` (name: `span inglese`) works fine.
5. With other **random** words the snippet not insert the selected text

System:

- VSCode Version: 1.50.1 d2e414d9e4239a252d1ab117bd7067f125afd80a 2020-10-13T15:06:15.712Z
- OS Version: Windows_NT x64 10.0.19041 and Linux distros

Does this issue occur when all extensions are disabled?: Yes

Problem 2 of #108784

**Comment by ArturoDent** [comment]
Yes, even this simplified snippet

```
 "span inglese": {
    "prefix": "eng",
    "body": "howdy ${TM_SELECTED_TEXT:$1} howdy",
    "scope": "html"
},
```

doesn't work in any html file.  But does work on the same text string in js or txt file for example (once the html scope id removed of course).

**Comment by Damix48** [comment]
So the problem could be only with HTML file

**Comment by jrieken** [comment]
Happens when re-triggering completions due to incomplete results. With that a cancel event is send which makes the overtyping capturer drop its internal state
