### ISSUE TITLE
[Request] Option to enforce adding public modifier even though it's the default one in TypeScript

### ISSUE THREAD

**Issue by whpac** [microsoft/vscode#108889]
I'm used to typing `public` modifier everywhere, even if it's the default one in TypeScript. But when auto-implementing interface with VS Code Ctrl+. menu all the functions get inserted without a modifier. This results in an inconsistent code (since I'm too lazy to alter all the functions).

Thus, I would like to see an option "TypeScript > Format: Enforce `public` modifier" (`insert`, `preserve`, `remove`) that would keep my code consistent - the setting could be taken into account when auto-implementing an interface and by the auto-formatter.

**Comment by mjbvz** [comment]
Enforcing style conventions like this are the job of a linter. ESLint may already even have a rule to enforce this
