### ISSUE TITLE
Safari/iPadOS: no UI affordance when hover on sash

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#108828]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open Web/Codespace on iPadOS
2. Connect external mouse/trackpad
3. Mouse over sash, there is no UI affordance

In desktop, we change the pointer style but there is no such thing on iPadOS. We may want to change the sash style.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
can be a sub set of https://github.com/microsoft/vscode/issues/108832

**Comment by bpasero** [comment]
I think this is solved with the new sash feedback color @rebornix ?

**Comment by isidorn** [comment]
Let's close as dup of https://github.com/microsoft/vscode/issues/120937
Even though that one is newer, it is already assigned to current milestone to look into
