### ISSUE TITLE
Debug Console - Autocomplete overwriting my entry

### ISSUE THREAD

**Issue by Mwatchorn26** [microsoft/vscode#108810]
Issue Type: <b>Bug</b>

Autocomplete in Debug Console shouldn't override something I have written (when I hit ENTER). For example I type "x='oranges'" and press ENTER, but autocomplete saw "x=" and suggested my previous value "x='pears'" once I start typing "x='o" it should no longer propose 'pears'. 
I typed x='oranges' ENTER, and got x='pears'... very frustrating!!!
I have to type  "x='oranges'" ESC, ENTER

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.71GB free)|
|Process Argv|--crash-reporter-id 04f030f2-738a-4d83-82b6-580ce30bb314|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.9.114305

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/108439
