### ISSUE TITLE
Safari/iOS: Settings Editor dropdown menu is unresponsive

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#108824]
- VSCode Version:
- OS Version:

Steps to Reproduce:

* Open Codespace on iPadOS
* Open Settings Editor
* Click the gear icon of a setting row
* Click the menu items from the drop down, nothing happens

![IMG_EFECE835AAE9-1](https://user-images.githubusercontent.com/876920/96295419-b1f9f880-0fa2-11eb-91f0-bdf93746e4a8.jpeg)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
This one is `touch` specific as mouse clicking works.

**Comment by isidorn** [comment]
I can still repro this. Assigning to @roblourens 
@roblourens do you have some mouse click listener? Can you simply add your element to the [Gesture](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/touch.ts#L67) and then listen on click events?

**Comment by roblourens** [comment]
Does this work with other context menus? I don't know what is special about this one.

**Comment by isidorn** [comment]
@roblourens yeah, other context menus across the workbench work just fine.

**Comment by roblourens** [comment]
Can you comment out this line and see if it works?

https://github.com/microsoft/vscode/blob/606bf316c73dcb83413077e2226010c25164bd73/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L663

**Comment by isidorn** [comment]
@roblourens if I comment that line out everything works just fine!

**Comment by roblourens** [comment]
@sbatten what is that option for?

**Comment by sbatten** [comment]
@roblourens it shadow doms the menu as a child of the button (dropdown in this case) to preserve focus. this is necessary to prevent the action bars from disappearing when focus is actually given to the html-based menus

**Comment by roblourens** [comment]
Why doesn't every menu get that option?

@isidorn do you see this on other menus that use that option, the notebook cell toolbar and viewpane header?

**Comment by sbatten** [comment]
it was added much later and can cause bugs because of the shadow dom isolation so we only adopted where focus changing had an obvious negative effect

**Comment by isidorn** [comment]
@roblourens seems to work fine for the viewpane header. Notebooks I currently do not have setup on my iPad.

**Comment by roblourens** [comment]
I don't have an ipad to investigate, if someone wants to debug it, you could poke at it with devtools. Or, I could unset that option when running on ipad.

**Comment by isidorn** [comment]
@roblourens for now I suggest to unset that option when running on an iPad.
You can use this check https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/browser.ts#L118

If we notice that other menus suffer from the same problem we can move that check to the menus land

**Comment by roblourens** [comment]
Works for me, done.
