### ISSUE TITLE
highlight jsconfig.json as invalid when tsconfig.json is present

### ISSUE THREAD

**Issue by webdeb** [microsoft/vscode#108801]
### Basically same issure as described here: https://github.com/Microsoft/vscode/issues/41890

VSCode About output

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (2 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

## Problem description

jsconfig.json 
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "./src/*"
      ]
    }
  },
  "include": [
    "src/**/*",
    "pages/**/*"
  ]
}
```

tsconfig.json

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "baseUrl": "./",
    "paths": {
      "~/*": [
        "./src/*"
      ]
    },
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    ".next",
    ".ci",
    ".smoke",
    ".vscode",
    "node_modules"
  ]
}

```

## Expectation

Auto-import & Go-to Definition should follow the "~/Module" to "<projectRoot>/src/Module"

## Actual behaviour

After adding tsconfig.json and reloading vscode, auto-import & Go to definition is not working anymore

**Comment by mjbvz** [comment]
Please share a small example project that demonstrates the issue (the configs are not enough to reproduce this)

**Comment by webdeb** [comment]
@mjbvz ok, this is really basic but its actually enough to demonstrate that Go to definition is not working when both tsconfig and jsconfig are present.
https://github.com/webdeb/vscode-resolve-bug

**Comment by webdeb** [comment]
Hmm.. seems like I can use tsconfig.json without jsconfig.json at all, If I include js files into tsconfig.json since `allowJs: true`. Interesting. 

```
...
compilerOptions: {
   ...
  "allowJs": true
},
"include": [
  "**/*.ts",
  "**/*.js",
]
```

I'll check it out the next days, how it will perform only with `tsconfig.json` in a 95% js project.

**Comment by webdeb** [comment]
> I was having the same issue, but when I was unable to reproduce in [a small project I created](https://github.com/jedmao/vscode-paths-broken), I looked closer and realized that in my actual project, I have a sub-package with the following section in `tsconfig.json`:
> 
> ```json
> {
>   "include": ["src"]
> }
> ```
> 
> What I realized is that the files in `src` resolve just fine, but the files in `server` do not, as they were not included. Once I added `server` to the `include` list, it fixed the problem.
> 
> Hope that helps!
> 
> _Note: my project is a Lerna monorepo with a ton of packages in it. The fundamental difference between all the other packages and the one I was having problems with was this new inclusion of a `server` folder._

Yeah, thank you for your input. I started using TS for server too, although my server folder is inside src also.

**Comment by webdeb** [comment]
Oh, yes! Now I am pretty sure that it is the expected behaviour: https://code.visualstudio.com/docs/languages/jsconfig

It says that jsconfig.json IS tsconfig.json with `allowJs: true`, so I guess the presence of tsconfig.json makes vscode ignore the jsconfig.json. 

---
Can we somehow highlight the jsconfig.json with a note that "tsconfig.json negligates jsconfig.json"? is it even correct english? :)

**Comment by jedmao** [comment]
> Can we somehow highlight the jsconfig.json with a note that "tsconfig.json negligates jsconfig.json"? is it even correct english? :)

`tsconfig.json` trumps `jsconfig.json`

**Comment by webdeb** [comment]
Closing this in favour of #108841
