### ISSUE TITLE
[scss] Normalise SCSS attributes with CSS/LESS/SASS

### ISSUE THREAD

**Issue by roydukkey** [microsoft/vscode#108840]
Removing the `"entity.other.attribute-name.attribute.scss"` scope, from Line 89 of the following snippet, will bring SCSS attributes inline with CSS, LESS, SASS (as provided by [Atom](https://github.com/atom/language-sass/blob/master/grammars/sass.cson))

https://github.com/microsoft/vscode/blob/ae5ecf9e17a4fc18219c8f8a3ede09112c3a3627/extensions/theme-defaults/themes/dark_vs.json#L80-L95

Here is a screenshot of the current state of the Dark theme.

![Current](https://user-images.githubusercontent.com/1509616/96322991-3bccb480-0fe9-11eb-8637-d1e4958a4bf7.png)

**Note:** The attribute strings (`"button"`, `"reset"`, and `"submit"`) are not properly scoped. This is an issue at atom/language-sass#257

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (8.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.10
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
vscode-language-rust|miq|0.14.0
csharp|ms-|1.23.3
theme-chimera|roy|0.4.0
rust|rus|0.7.8
code-spell-checker|str|1.9.2

(1 theme extensions excluded)

</details>

**Comment by misolori** [comment]
@aeschli I think this needs verification steps, I'm not exactly sure what I should be referencing. Below, sass `type` isn't highlighted like the others and in scss the attributes (button, reset, submit) are also not highlighted like the rest.

![image](https://user-images.githubusercontent.com/35271042/97615619-c8f40e00-19d8-11eb-8404-e2c0dd521903.png)

**Comment by roydukkey** [comment]
@misolori I wonder if you're using a different grammar than myself for SASS. I'm comparing it to this grammar: https://github.com/atom/language-sass/blob/f52ab12f7f9346cc2568129d8c4419bd3d506b47/grammars/sass.cson

Using this for SASS because the SCSS/LESS/CSS grammars officially used in vscode is sourced from the same repo.

https://github.com/microsoft/vscode/blob/40cf6489c9b0a908ea2e7af5e34b04a14a59b322/extensions/scss/syntaxes/scss.tmLanguage.json#L7
https://github.com/microsoft/vscode/blob/40cf6489c9b0a908ea2e7af5e34b04a14a59b322/extensions/less/syntaxes/less.tmLanguage.json#L7
https://github.com/microsoft/vscode/blob/40cf6489c9b0a908ea2e7af5e34b04a14a59b322/extensions/css/syntaxes/css.tmLanguage.json#L7

Also, as stated in my original post, the arrow pointing to `"reset"` in the `.scss` file is due to another issue.

> Note: The attribute strings ("button", "reset", and "submit") are not properly scoped. This is an issue at atom/language-sass#257

**Comment by aeschli** [comment]
@misolori You got it right, the screenshots show that scss now renders `type` in the same color as in css and less. We don't ship a grammar for sass so no worries there. Yes, it looks like we have also a difference with coloring the string literal. Feel free to file an issue and I can investigate if we can fix that (also depends on the grammar)
