### ISSUE TITLE
Where to get help with contributing to VSCode itself?

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#108899]
I've been working on a couple of VSCode bugs, but as an outsider it isn't clear how to get help with contributing. The only resources I've found are the [How to contribute](https://github.com/microsoft/vscode/wiki/How-to-Contribute) page, which is very useful but static (i.e. you can't ask questions), and the [vscode Gitter channel](https://gitter.im/Microsoft/vscode) which seems to be people occasionally asking questions but nobody really answering them (I guess the VSCode team aren't present?).

Is there some way to get help with actually contributing to VSCode? It's an annoyingly difficult thing to search for so I might have missed something. Or maybe you deliberately don't have something like this because of the inevitable influx of user questions? The sort of questions I'd want answered are:

1. How do I request a review for my pull request?
2. What exactly is `IResourceEditorInput` and how does it differ from `IEditorInput`?

**Comment by nrayburn-tech** [comment]
I have made some PRs, but mostly they were smaller items that didn't require any feedback.  If I ran into a question like you have for the difference between `IResourceEditorInput` and `IEditorInput` I would look around in the code.  If it wasn't simple, I would move on to something else.
Being able to find assistance with these type of questions would be great.

If you are working on a specific issue, I would think that the assigned person would be able to provide some help if you ask.  Outside of that, I wouldn't know where to ask.

**Comment by ArturoDent** [comment]
I would file issues on the separate bugs.  And then say you are working on a PR.  You can ask questions to whomever is assigned the issue from the vscode team.

Sometimes they can tell you where to start or that there is a coming change to that part of the code that would make your PR irrelevant so it is best to file the issue first.

**Comment by alexdima** [comment]
I think all of us are very active in issues, so if you have specific questions when working on a PR, you can ask on the issue you're working on.

@bpasero might be able to answer this specific question about `IResourceEditorInput` vs `IEditorInput`.

**Comment by bpasero** [comment]
To answer here:
* `IResourceEditorInput`: is the lightweight, untyped variant of editor inputs that only require a `resource: URI`
* `IEditorInput`: is the instantiated editor input that we need in few cases where just a `resource: URI` is not enough

I think it would be better to ask questions in specific issues that have the "help wanted" label.
