### ISSUE TITLE
Safari/iPadOS: tree view title requires multiple clicks to expand/collapse the tree view

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#108829]
Steps to Reproduce:

1. Open Web/Codespace on iPadOS
2. Connect external mouse/trackpad
3. Open Remote Explorer, mouse click on the tree view title, often you need multiple clicks to toggle the state of the tree view

In desktop, we change the pointer style but there is no such thing on iPadOS. We may want to change the sash style.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
Mouse clicking and touch behaves the same.

**Comment by chrmarti** [comment]
@rebornix Not sure I (as the inbox tracker) should distribute the iOS issues to the team. Assigning to you for now.

**Comment by rebornix** [comment]
Discussed this with @isidorn it makes sense otherwise you can easily click on actions on the title bar.
