### ISSUE TITLE
Arrow keys || Backspace key does not work randomly (rare)

### ISSUE THREAD

**Issue by mfaheemakhtar** [microsoft/vscode#108861]
Issue Type: <b>Bug</b>

After the recent update(s), rarely, the arrow keys OR the backspace key stops working. This has happened around 3 times in the last week. 2x in office and 1x just now on my machine. I don't know how to reproduce it. Automatically, gets fixed if I change the cursor position by clicking somewhere else.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (8.02GB free)|
|Process Argv|[redacted] --crash-reporter-id 992e8aa5-f144-4f45-83a7-45b0c7e43aad|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.37.1
vscode-eslint|dba|2.1.10
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
graphql-for-vscode|kum|1.15.3
rainbow-csv|mec|1.7.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.6.0
LiveServer|rit|5.6.1
sort-lines|Tyr|1.9.0
material-theme|zhu|3.9.3

(2 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
Please let me know if you manage to find any steps. Otherwise, perhaps you have some customizations in `keybindings.json` or perhaps some of these extensions "steal" some of the keybindings in certain conditions?

**Comment by mfaheemakhtar** [comment]
I have not installed any extensions recently. So probably VSCode or extensions compatibility. Have not faced this issue again yet.

**Comment by mfaheemakhtar** [comment]
@alexdima , just faced the issue again. And I have more details.

I typed `p-` and the autocomplete showed me some suggestions, such as `p-0`. I hit the `Enter` key and instead of autocompleting the suggestion. It inserted a new line and then the bug occurs. Backspace, Arrow keys, Delete key stopped working. I was able to use the characters keys.

I had to re-open the file to fix the issue.

**Comment by alexdima** [comment]
@mfaheemakhtar are you using some special input method? Or are you using the standard US keyboard layout?

**Comment by mfaheemakhtar** [comment]
I am using the standard US keyboard layout. I will update this thread when it happens again, probably with more details.

**Comment by blakeNaccarato** [comment]
I'm having this issue as well, on two separate Windows 10 machines. It happens to at least to the Home/End keys as well, and possibly others. I will pay more attention next time it happens and provide more info then.

If I recall correctly, if I click out of the editor (say, focus the terminal), and back again, key functions return to normal. Here is a link to a [gist containing my keybindings.json](https://gist.github.com/blakeNaccarato/44dcd272559c074d2a6c5f1a48dff6c4), for what it's worth.

This seems to be a regression related to [#24107](https://github.com/microsoft/vscode/issues/24107)?

**Comment by alexdima** [comment]
@blakeNaccarato #24107 is unrelated, that one is about linux which uses a different keyboard dispatching mechanism (based on scan codes and not on key codes). When you see this again, can you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command Developer: Toggle Keyboard Shortcuts Troubleshooting
  * This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* You can then press your desired keybinding and check what keyboard shortcut VS Code detects and what command is invoked.
