### ISSUE TITLE
DebugConfigurationProvider only calls resolveDebugConfiguration

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/vscode#108835]
Issue Type: <b>Bug</b>

Occurs in Insiders, not release.

We are trying to convert our DebugConfigurationProvider to only use `resolveDebugConfigurationWithSubstitutedVariables`.
However, in the scenario with no launch.json, it calls `provideDebugConfigurations`, then after a user selects a configuration. It only seems to call `resolveDebugConfiguration`. 

I think it should also be calling `resolveDebugConfigurationWithSubstitutedVariables`

Actual:
![image](https://user-images.githubusercontent.com/3953714/96306889-70267d80-0fb5-11eb-87f7-59a76d9132fd.png)
Then nothing.

Expected:
![image](https://user-images.githubusercontent.com/3953714/96306889-70267d80-0fb5-11eb-87f7-59a76d9132fd.png)
![image](https://user-images.githubusercontent.com/3953714/96307432-76692980-0fb6-11eb-8073-7f8776f6b3c0.png)

Bug Version:
VS Code version: Code - Insiders 1.51.0-insider (89c002ab02f87102d91efc83c191ef1174756c6a, 2020-10-15T23:17:08.035Z)
OS version: Windows_NT x64 10.0.19041

Working Release Version:
```
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (45.49GB free)|
|Process Argv|--crash-reporter-id b203f981-bd1f-4c33-9e1e-fd8717861426|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.3
cpptools|ms-|1.1.0-insiders2

</details>

**Comment by isidorn** [comment]
I have just tried this with latest VS Code insiders and it works just fine for me.
Here are my steps:
1. Have a `hello.js` file. Do not have a `launch.json`
2. Press `F5` -> notice how the `resolveDebugConfigurationWithSubstitutedVariables` gets called on provider side

Also the whole milestone I was on vacation, so it is very strange that this would work for stable and not for insiders.

@WardenGnaw is it possible that you somehow change mock debug so we can clone and be able to reproduce this issue on our side?

**Comment by WardenGnaw** [comment]
I just realized that this is my error. I forgot we rely on returning null instead of empty configuration `{}` to prompt the provider.

I hope you had a wonderful vacation!

**Comment by isidorn** [comment]
Glad you found the issue.
Yeah vacation was great, thanks :)
