### ISSUE TITLE
Restore all windows on launch

### ISSUE THREAD

**Issue by matejkramny** [Microsoft/vscode#10885]
- VSCode Version: 1.4.0
- OS Version: macos 10.12

Steps to Reproduce:

1. Open two windows, load a project into them
2. Quit vs code
3. Re-open vs code, only one window opens.

VSCode only remembers one workspace. It should remember all open windows and restore them on launch.

**Comment by sandy081** [comment]
I do not think re-opening all windows is a good idea and it might not be liking to many users. It makes sense to open the recently closed workspace on open.

I will close this for now.. But we can wait to see if there are more users looking for this feature and come back to it.

Thanks.

**Comment by matejkramny** [comment]
Ok no worries. If I made a PR with this, and it'd be an off-by-default option in settings, would this be useful to the project?

**Comment by matejkramny** [comment]
btw, if you have "multiple window tabs" when you quit VSCode, it restores them as multiple windows ;)

**Comment by erhhung** [comment]
I work on multiple projects in multiple windows all the time, and having been used to this behavior in Sublime, I have come to expect it in VSCode, but am disappointed that, at the very least, there's no option to enable it. I understand not everyone will like it, so it should clearly be a user preference.

**Comment by erhhung** [comment]
OK, I just discovered that **this feature now exists, but it isn't the default setting** (another strike against the "restore to the exact same state as I had" philosophy).

Just set the `window.reopenFolders` preference to `all`.

**Comment by matejkramny** [comment]
you're a hero. Thank you

**Comment by vvo** [comment]
It's now "window.restoreWindows": "none|one|all|folders",

![image](https://user-images.githubusercontent.com/123822/30349741-41970596-9814-11e7-8485-2c16bf4f525d.png)
