### ISSUE TITLE
Unexpected output value in terminal using pre/post-increment & pre/post-decrement.

### ISSUE THREAD

**Issue by WilliamYangjaya** [microsoft/vscode#108882]
- VSCode Version: 1.50.1
- OS Version: Windows 10 Version 1909

List of extensions:
- Atom One Dark Theme v2.2.2
- C/C++ v1.1.0-insiders2
- Code Runner v0.11.1
- Kubernetes v1.2.1
- Live Share v1.0.3014
- Noctis v10.39.0
- Python v2020.9.114305
- SQLTools v0.23.0
- SQLTools MySQL/MariaDB v0.2.0
- swift-sfdc v0.0.21
- vscode-icons v11.0.0
- YAML v0.11.1

Steps to Reproduce:
1. Run the codes of the main program.
2. Unexpected output value in terminal using pre/post-increment & pre/post-decrement.

Does this issue occur when all extensions are disabled?: No

![Report Issue](https://user-images.githubusercontent.com/45089786/96358983-7c3a4880-1137-11eb-894a-6cd2efcb7332.PNG)

**Comment by gjsjohnmurray** [comment]
What part of the output is unexpected?

**Comment by WilliamYangjaya** [comment]
I think the output should be as follows
// postincrement
// output value of a
5
5
6

// preincrement
// output value of b
5
6
6

// postdecrement
// output value of c
5
5
4

// predecrement
// output value of d
5
4
4

<!-----------------!>

What I actually saw.
// postincrement
// output value of a
16
16
17

// preincrement
// output value of b
0
1
1

// postdecrement
// output value of c
14948048
14948048
14948047

// predecrement
// output value of d
5
4
4

**Comment by WilliamYangjaya** [comment]
> What part of the output is unexpected?

I think the output should be as follows
// postincrement
// output value of a
5
5
6

// preincrement
// output value of b
5
6
6

// postdecrement
// output value of c
5
5
4

// predecrement
// output value of d
5
4
4

=============

What I actually saw.
// postincrement
// output value of a
16
16
17

// preincrement
// output value of b
0
1
1

// postdecrement
// output value of c
14948048
14948048
14948047

// predecrement
// output value of d
5
4
4

**Comment by WilliamYangjaya** [comment]
> What part of the output is unexpected?

I think the output should be as follows
// postincrement
// output value of a
5
5
6

// preincrement
// output value of b
5
6
6

// postdecrement
// output value of c
5
5
4

// predecrement
// output value of d
5
4
4

=============

What I actually saw.
// postincrement
// output value of a
16
16
17

// preincrement
// output value of b
0
1
1

// postdecrement
// output value of c
14948048
14948048
14948047

// predecrement
// output value of d
5
4
4

**Comment by gjsjohnmurray** [comment]
You are only setting an initial value for d

/question - for example [here](https://stackoverflow.com/questions/35877190/how-to-initialize-multiple-variables-in-c-to-the-same-value/35877212)
