### ISSUE TITLE
Visual Studio Code is not responding

### ISSUE THREAD

**Issue by masternikhilgupta** [microsoft/vscode#108917]
Issue Type: <b>Performance Issue</b>

when i am writing or running a code in visual studio code, it shows window is not responding. i have uninstall the Visual studio code & reinstall it, but the problem has not been solved yet. I am getting rid of these. Kindly solve my issues as soon as possible. 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.96GB free)|
|Process Argv|--crash-reporter-id 7337cfd9-dcfe-4427-80f2-f34206178bed|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    71	 11220	code main
    0	    83	   760	   shared-process
    2	    81	  6748	   window (Issue Reporter)
    1	   179	  6804	   gpu-process
    0	    25	  7036	   crashpad-handler
    0	    38	 10676	   utility
    0	   156	 10844	   window (Settings - VS CODE - Visual Studio Code)
    0	    11	  2964	     watcherService 
    0	    10	  8912	       console-window-host (Windows internal process)
    0	   160	  6728	     extensionHost
    0	   222	  6256	       C:\Users\LENOVO\AppData\Local\Programs\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar c:\Users\LENOVO\.vscode\extensions\redhat.java-0.69.0\server\plugins\org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar -configuration c:\Users\LENOVO\AppData\Roaming\Code\User\globalStorage\redhat.java\0.69.0\config_win -data c:\Users\LENOVO\AppData\Roaming\Code\User\workspaceStorage\f18dbdb5bb167a6dd24fd73882f65890\redhat.java\jdt_ws
    0	    10	  6424	         console-window-host (Windows internal process)
    0	    68	  9788	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - VS CODE - Visual Studio Code)
|    Folder (VS CODE): 11 files
|      File types: java(5) class(4) cpp(1) exe(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.7.1
code-runner|for|0.11.1
python|ms-|2020.9.114305
cpptools|ms-|1.1.0-insiders2
java|red|0.69.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2

</details>
 # # #

**Comment by chrmarti** [comment]
What programming language are you using? Does this happen when you disable all extensions (`F1` > `Developer: Reload with Extensions Disabled`)?

**Comment by chinmya1975** [comment]
Hey There,
If you want to execute a code you need the required extension of that language ex- .py for python make sure these are not disabled

**Comment by masternikhilgupta** [comment]
> Hey There,
> If you want to execute a code you need the required extension of that language ex- .py for python make sure these are not disabled

Hey... I know this & i was not disable this extensions.

**Comment by chrmarti** [comment]
@masternikhilgupta Can you provide more information, which programming language are you using when this happens? Does it still occur when disabling all extensions? It sounds like the renderer might use up the CPU, can you check again with `code --status` and if so follow https://github.com/Microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process to get a profile? (More info: https://github.com/Microsoft/vscode/wiki/Performance-Issues)
