### ISSUE TITLE
ctrl+c

### ISSUE THREAD

**Issue by Nours2806** [microsoft/vscode#108997]
Issue Type: <b>Bug</b>

bonjour,
la touche CTRL+c ne marche plus pour faire une copie, à la place il me fait la commande "insert" 
pouvez-vous m'aider ?
merci d'avance

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4335)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.63GB free)|
|Process Argv|--crash-reporter-id ef9e909c-60a5-402d-800a-3b327c51d344|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.4.0
vscode-sqlite|ale|0.9.0
alignment|ann|0.3.0
color-info|bie|0.5.1
vscode-intelephense-client|bme|1.5.4
bdjavasyntax|Dav|1.3.9
vscode-generate-getter-setter|DSK|0.5.0
vscode-npm-script|eg2|0.3.13
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-rename-tag|for|0.1.5
vscode-test-explorer|hbe|2.19.1
beautify|Hoo|1.5.0
icon-fonts|idl|2.3.2
composer|ika|0.7.1
RelativePath|jak|1.4.0
vscode-peacock|joh|3.8.0
node-module-intellisense|lei|1.5.0
php-namespace-resolver|Meh|1.1.8
vscode-autoprefixer|mrm|3.0.1
vscode-language-pack-fr|MS-|1.50.2
mssql|ms-|1.9.0
cpptools|ms-|1.0.1
debugger-for-chrome|msj|4.12.11
sqltools|mtx|0.23.0
color-highlight|nau|2.3.0
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|4.3.0
vscode-phpunit|rec|2.0.76
phpdoc-comment-vscode-plugin|rex|1.3.0
LiveServer|rit|5.6.1
vscode-paste-and-indent|Rub|0.0.8
vscode-scss-formatter|sib|2.0.2
sass-indented|syl|1.8.12
vim|vsc|1.17.1
twig|wha|1.0.2

</details>

**Comment by hediet** [comment]
It would be very helpful if you could submit your bug reports in English!

Can you check your keybindings? Is Ctrl+C still bound to copy? Does Ctrl+C work outside of VS Code as expected?

**Comment by myfonj** [comment]
(Obligatory questions about whether it happens solely in VSC, extensions disabled /clean profile and if there is no clash visible in Keyboard shortcuts)
(Machine translations + "you should probably better use English next time".)

---

Traductions automatiques. Vous devriez probablement mieux [utiliser l'anglais](https://github.com/microsoft/vscode/wiki/How-to-Contribute#discussion-etiquette) la prochaine fois.

Cela se produit-il uniquement dans VSC?
Cela se produit-il lorsque toutes les extensions sont désactivées ( `code --disable-extensions`) ou dans un profil propre (`code --extensions-dir "C:\tmp-exts" --user-data-dir "C:\tmp-profile"`)?

<details><summary>Vérifiez ces préférences:</summary>

![image](https://user-images.githubusercontent.com/1761395/96567595-41671a80-12c7-11eb-8313-5e39c753f1b1.png)

![image](https://user-images.githubusercontent.com/1761395/96567917-a589de80-12c7-11eb-8534-a3577f98c41d.png)

</details>

**Comment by Nours2806** [comment]
yes, this only happens in VSC
yes this happens when extentions are disabled

**Comment by myfonj** [comment]
And `"ctrl+c"` in search input filed of _"Keyboard Shortcuts"_ pane shows … ? Ideally entered via "Record Keys" to see what keystrokes exactly VSC "sees".

**Comment by connor4312** [comment]
Please check out https://github.com/microsoft/vscode/wiki/Keybinding-Issues and let us know if you still have issues / can collect more information
