### ISSUE TITLE
Menus unreadable when Windows is in high contrast mode

### ISSUE THREAD

**Issue by djohns505** [Microsoft/vscode#10898]
Code is not aware of the OS setting. Enable high contrast mode in Windows (not the Code theme) and all of the menus are white text on a white background

<img width="533" alt="code high contrast" src="https://cloud.githubusercontent.com/assets/587960/17936641/779d8224-69ed-11e6-9ea9-364ac582f3d1.PNG">

**Comment by bpasero** [comment]
Menu is rendered by Chrome, so this is an upstream issue.

**Comment by djohns505** [comment]
Closing as a duplicate of #9878
