### ISSUE TITLE
cpuprofile files generated by vscode for extension performance won't load on Mac

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#108965]
I'm not blocked, so not high pri, but this is the second time I had to go to a win32 machine to debug a performance scenario because the files won't load on a Mac.  For example, try the one in https://github.com/microsoft/vscode-azurearmtools/issues/1051

I always get this:
> Can’t load file. Supported file extensions: `.cpuprofile`.

(and yes, I did rename to .cpuprofile)

**Comment by connor4312** [comment]
I'm unable to reproduce this. After renaming the file I'm able to open it in Chrome on both OSX and Windows, as well as in VS Code's built-in profile visualizer tools.

/needsMoreInfo

**Comment by StephenWeatherford** [comment]
Here's the zip with the renamed file:
[msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.zip](https://github.com/microsoft/vscode/files/5425422/msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.zip)

Using dev tools to open on Mac in vscode Version: 1.50.1 Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a Date: 2020-10-13T14:53:05.704Z Electron: 9.2.1 Chrome: 83.0.4103.122 Node.js: 12.14.1 V8: 8.3.110.13-electron.0 OS: Darwin x64 19.6.0:
![cpuprofile](https://user-images.githubusercontent.com/6913354/96924377-6d210680-1467-11eb-8b4f-d2a766efd775.gif)

**Comment by StephenWeatherford** [comment]
![image](https://user-images.githubusercontent.com/6913354/96925325-d5241c80-1468-11eb-9dee-65e279685414.png)

**Comment by StephenWeatherford** [comment]
Okay, so apparently my Mac is hiding some file extensions like .txt but not others (like .zip).  Had no idea it would do that.  Thanks.
