### ISSUE TITLE
notebook integration for markdown <code> cells

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode#108922]
#### Use case
Native Notebook experience in VS Code is great, and it is natural for rendering tutorials. But currently Notebook is per file extension, and I cannot have a notebook supporting multiple "languages", which is common in tutorials.

For example, I want to write a tutorial containing snippets for both **python** code and **powershell** commands. PowerShell extension recognizes file extension `.ps1` (it's reusing the ext according to [this blog](https://devblogs.microsoft.com/powershell/public-preview-of-notebook-mode-in-the-powershell-preview-extension-for-visual-studio-code/#how-is-notebook-mode-different-than-jupyter-notebooks-jupyter-lab)) and Python extension recognizes `.ipynb`. 

#### feature request 
As most of tutorials are written in Markdown, an approach can be, integrate Notebook support with Markdown rendering. For example, tutorials can be written in below way:

#### tutorial.md
<pre>
# A Sample Tutorial
* Step 1. Run below commands to configure prerequisites.

```powershell
some powershell commands...
```

* Step 2. Run below Python code and observe the output
```python
sample python code snippet
```

</pre>

#### expected behavior
If Notebook extensions are installed, corresponding "code" cells (powershell and python) are automatically rendered in the Notebook way, that users can run it.

**Comment by rebornix** [comment]
You would like https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-markdown-notebook from @roblourens
