### ISSUE TITLE
Kernel Picker displayed when running cells before preferred kernel is auto selected

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#108950]
With the Python extension:
* Assume you open a notebook
* Assume python extension is slow to return the list of kernels (hence slow to return the preferred kernel to VS Code).
* Next, click on the `Run` cell icon.
* VS Code now displays the kernel picker

It seems there's a race condition:
* When `Run` is clicked, VS Code doesn't yet have the preferred kernel from extension
* VSCode then calls extension to get the list of kernels & displays the kernel picker

**Suggestion**
* When user clicks `Run`, wait for first call to extension to complete before checking if extension provides a preferred kernel.

@rebornix /cc

**Comment by RMacfarlane** [comment]
Not sure if I did this correctly, but I used https://github.com/microsoft/vscode-github-issue-notebooks as a starting place and made these changes:

added delay to provide kernals
```
		vscode.notebook.registerNotebookKernelProvider({
			viewType: 'github-issues',
		}, {
			provideKernels: () => {
				return new Promise((resolve, _) => {
					setTimeout(() => {
						resolve([this]);
					}, 4000);
				});
			}
		});
```

set the `isPreferred` flag to true for the kernel

If I start debugging and immediately click run on cell in `github-issues` notebook, I still see a quickpick pop up that eventually resolves to have the "GitHub Issues Kernel" as the only option

**Comment by rebornix** [comment]
My previous fix doesn't guard the case where the first round of kernel fetching doesn't finish so you will always see a quick pick if you click the run button before the kernels are resolved. The right fix should be 

* The run button should wait for the kernel fetching, but not showing the quick pick
* Once the kernel fetching is done
  * If there is a preferred kernel, use that kernel to run the code
  * If there is only one kernel, use that kernel to run
  * If there are multiple non-preferred kernel, we show the quick pick (we can discuss if this behavior is the best)

**Comment by connor4312** [comment]
The bug is fixed, but for this:

> If there are multiple non-preferred kernel, we show the quick pick (we can discuss if this behavior is the best)

I tried returning multiple kernels that had `isPreferred = false`, but no quickpick was shown
