### ISSUE TITLE
Feature Request : Highlight a single line and execute just 1 line at a time in integrated terminal 

### ISSUE THREAD

**Issue by abhishekanand** [Microsoft/vscode#10894]
- VSCode Version: NA
- OS Version: NA

Steps to Reproduce: NA

When editing CLI or PowerShell and executing commands, either we cut-n-paste 1 line at a time or have VSC execute all commands. Is there a way to highlight a single line and execute just 1 line at a time?

**Comment by Tyriar** [comment]
Currently all characters are sent as if they were typed, meaning that the lines are evaluated one at a time unless there is a block or line continuation. So I think this is working as expected? There was recently the inverse issue created where PS lines were being evaluated 1 line at a time and not as a block.
