### ISSUE TITLE
Method to report dead extensions

### ISSUE THREAD

**Issue by dashesy** [microsoft/vscode#108949]
Please provide a way to flag dead extensions. 
You can see the [reviews](https://marketplace.visualstudio.com/items?itemName=kriegalex.vscode-cudacpp) but no way to report and extension to be removed.

**Comment by prashantvc** [comment]
We cannot remove an extension just because publisher did not update it or committed any code.
Leaving low rating and review is an effective way to deal with these extensions and get publisher's attention
