### ISSUE TITLE
Intellij idea key-binding  function do not work when press any pre-defined key-binding plan

### ISSUE THREAD

**Issue by mebest100** [microsoft/vscode#108921]
- VSCode Version: 1.50.1
- OS Version: win7 x86 64

Steps to Reproduce:

1.  install Intellij idea key-binding plugins in vscode and edit java code into vscode
2.  Intellij idea key-binding  function do not work at all, it takes no effect when press any key-binding plan defined by the plugins.

Does this issue occur when all extensions are disabled?: Yes/No: No., it do not connected with disable other extensions

**Comment by chrmarti** [comment]
There are several extensions for this which one do you have installed?

**Comment by mebest100** [comment]
Hi, Pls check the installed  extesion link:
https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings

**Comment by chrmarti** [comment]
Make sure the extension is enabled and no other keymap extensions are installed. (Check in the Extension viewlet.)

**Comment by mebest100** [comment]
Sure, Hv enabled this extension and no other keymap extensions installed.

**Comment by chrmarti** [comment]
What does the keybindings editor show for 'copy line down'? I have (on Mac):
![image](https://user-images.githubusercontent.com/9205389/96886051-8172fc80-1483-11eb-8224-3ff44501920e.png)

**Comment by mebest100** [comment]
Sorry,  I don't care  'copy line down', what I can concern is IDEA style keybindings. such as 'ctrl + shift + enter' , 'alt + enter' , all of this does not work

**Comment by chrmarti** [comment]
What does the keybindings editor show for the commands you are interested in?

**Comment by mebest100** [comment]
Nothing happened, no any expected effects occur
