### ISSUE TITLE
VSCode Changes looping between two differently-cased filenames (one of which is deleted)

### ISSUE THREAD

**Issue by nathanielastudillo** [microsoft/vscode#108956]
Issue Type: <b>Bug</b>

VSCode inside WSL:Ubuntu switches between two differently-cased versions of a file indefinitely within the changes tab.

Steps To Reproduce: 

1. Start with 2 files, one named Jenkinsfile and one named JenkinsFile
2. Initialize repo with both files (Jenkinsfile, JenkinsFile)
3. Delete file (JenkinsFile)
4. Commit change
5. Edit file (Jenkinsfile)
6. Discard Changes (Jenkinsfile) 

After that, every time changes are discarded on Jenkinsfile, it becomes JenkinsFile. When changes are discarded on JenkinsFile, it becomes Jenkinsfile. There's something wonky going on with the way VSCode handles case-insensitive files. It seems to think a file that's been deleted (JenkinsFile) is still present AND is the same as the file that is actually present (Jenkinsfile).

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (7.68GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/mnt/c/Users/natha/Documents/change.click/change.click|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2601)|
|Memory (System)|15.90GB (7.68GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2601)|
|Memory (System)|15.90GB (7.68GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.1
jenkinsfile-support|sec|0.1.0
vscode-nginx|sha|0.6.0
vscode-djaneiro|the|1.4.2
code-groovy|mar|0.1.2
vscode-docker|ms-|1.7.0
python|ms-|2020.9.114305
vetur|oct|0.28.0
vue-vscode-snippets|sdr|2.1.5

</details>

**Comment by joaomoreno** [comment]
> After that, every time changes are discarded on Jenkinsfile, it becomes JenkinsFile.

Can you show me that?

What is the actual file name in disk?
