### ISSUE TITLE
extension activating

### ISSUE THREAD

**Issue by Jaswant9829** [microsoft/vscode#108989]
- [ ] 
![activating](https://user-images.githubusercontent.com/73154682/96542738-5a200200-12c0-11eb-80a4-4d8b80bd6f69.PNG)
Issue Type: <b>Performance Issue</b>

when i run any extenion there pop a error activating extenstion

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.1.7600

<details>
<summary>Process Info</summary>

```

```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
shell|bbe|0.3.0
live-code-runner|lab|4.5.0
cpptools|ms-|1.0.1

</details>

**Comment by gjsjohnmurray** [comment]
That is a normal notification, but it shouldn't remain indefinitely. I suggest you try disabling each of your extensions in turn and restarting VS Code each time to find out which one is causing the problem.
