### ISSUE TITLE
"scm.providerCountBadge" not working

### ISSUE THREAD

**Issue by danielt117** [microsoft/vscode#108957]
- VSCode Version: 1.50.1
- OS Version: Ubuntu 20.04

The "scm.providerCountBadge" setting no longer works (none of the 3 option).
If i remember correctly, this is responsible for the number on the right. But even if i set it to "hidden", it's still visible.
Currently it acts like it's always on "visible".

![Screenshot from 2020-10-19 11-34-11](https://user-images.githubusercontent.com/42888821/96513886-219e0b00-1263-11eb-82fb-b72145cca73a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
The `scm.providerCountBadge` only affects the repositories in the Source Control view, not the Source Control Repositories view. This is because we'd like all actions to be aligned in the Source Control Repositories view and this would break alignment. The setting description also makes this clear:

> These headers only appear when there is more than one provider.

**Comment by susiwen8** [comment]
@joaomoreno 
`scm.providerCountBadge` doesn't work in `Source Control view` either.

https://user-images.githubusercontent.com/20318608/106373486-ec9e6a00-63b4-11eb-9ddc-dfb25f344c4a.mp4

And I have tested the PR I have made, it only affect `Source Control view`

**Comment by susiwen8** [comment]
@joaomoreno Hi could you relook this issue?

**Comment by joaomoreno** [comment]
@susiwen8 This is about the count badge on Source Control Provider headers, not Source Control Resource Groups. To see the providers in the Source Control view, please enable `scm.alwaysShowRepositories`, or open more than one repository.

**Comment by susiwen8** [comment]
> @susiwen8 This is about the count badge on Source Control Provider headers, not Source Control Resource Groups. To see the providers in the Source Control view, please enable `scm.alwaysShowRepositories`, or open more than one repository.

Got it,  thanks
