### ISSUE TITLE
Unable to select intermediate folder when condensed path is not fully shown

### ISSUE THREAD

**Issue by kevinresol** [microsoft/vscode#108962]
Issue Type: <b>Bug</b>

In the following two screenshots my cursor (not captured in the shot) is over the "physics" folder.

When the condensed path is not fully shown, the "physics" folder does not show hovered effect and clicking it does not bring me to that folder. Instead it just expands/collapses the entire condensed path.
<img width="202" alt="Screenshot 2020-10-20 at 10 40 06 AM" src="https://user-images.githubusercontent.com/1103788/96533738-fe09ad80-12c0-11eb-8b3a-c23d12af2aad.png">

Below is when the condensed path is fully shown, and works as expected.
<img width="245" alt="Screenshot 2020-10-20 at 10 39 56 AM" src="https://user-images.githubusercontent.com/1103788/96533742-ffd37100-12c0-11eb-8e6a-4d1d370957a2.png">

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (3.69GB free)|
|Process Argv|-psn_0_57358 --crash-reporter-id 3ea1f3a8-e276-4541-a0db-69c48306144f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
cmake-format|che|0.6.11
regex|chr|0.2.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-chinese-translation|Com|0.0.1
vscode-eslint|dba|2.1.13
javadebugger|don|0.1.5
xml|Dot|2.5.1
gitlens|eam|10.2.2
permute-lines|ear|1.1.0
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.7.1
php-intellisense|fel|2.3.14
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.9
reasonml|fre|1.0.38
ocaml|hac|0.6.43
vscode-test-explorer|hbe|2.19.1
tasks-chooser|jer|0.3.0
electron-debug|kod|18.11.1
kha|kod|20.4.0
kha-extension-pack|kod|20.2.2
krafix|kod|18.7.1
krom|kod|20.1.0
krom-debug|kod|20.6.0
beancount|Len|0.5.6
restructuredtext|lex|129.0.0
lix|lix|1.3.0
vscode-smart-column-indenter|lmc|0.0.13
vscode-fluent|mac|0.0.4
git-graph|mhu|1.26.0
azure-pipelines|ms-|1.177.0
vscode-docker|ms-|1.7.0
vscode-kubernetes-tools|ms-|1.2.1
mssql|ms-|1.9.0
python|ms-|2020.9.114305
azure-account|ms-|0.9.3
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.1
mono-debug|ms-|0.16.2
node-debug2|ms-|1.42.5
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.1.0
vshaxe|nad|2.21.4
lime-vscode-extension|ope|1.4.0
java|red|0.69.0
vscode-yaml|red|0.11.1
vscode-hexdump|sle|1.8.1
html-preview-vscode|tht|0.2.5
cmake|twx|0.0.17
vscode-bnf|Val|0.0.1
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
vscode-icons|vsc|11.0.0
haxe-checkstyle|vsh|1.6.1
codedox|wig|1.3.1
change-case|wma|1.0.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by isidorn** [comment]
I acknowledge this issue.
We are open to a PR that fixes this

Code poitner
https://github.com/microsoft/vscode/blob/49d9c8c79b6fd9aaeeb5e869e37d93cfd0e7b703/src/vs/base/browser/ui/iconLabel/iconLabel.ts#L198

**Comment by jeanp413** [comment]
This looks like a chromium issue. It works fine in vscode web with chromium v86

**Comment by isidorn** [comment]
@jeanp413 thanks for letting us know. So should be fixed when we update to Electron 11.
Removing help wanted label.
