### ISSUE TITLE
Allow to Drag and drop files from explorer into working file to produce a URL link

### ISSUE THREAD

**Issue by owennicol** [Microsoft/vscode#10895]
- VSCode Version: 1.4.0
- OS Version: OSX El Capitan

Would like the ability to drag a file from the integrated explorer and have it create the relevant link in my html/js file - in the same way that Visual Studio Professional does

**Comment by Morgy93** [comment]
![b3d75292-3c4a-4af6-98d4-15aa0c720b4b](https://cloud.githubusercontent.com/assets/7961978/25818915/772589e0-342c-11e7-9e41-9a5252b5f204.gif)

Thanks to @geektrainer for showing off this neat feature.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by aeschli** [comment]
duplicate of #34647
