### ISSUE TITLE
Error not shown when a typing error happens inside of quotes 

### ISSUE THREAD

**Issue by nitti87** [microsoft/vscode#108926]
Issue Type: <b>Bug</b>

When I type `document.querySelectorAll("[data-location='top left'")`, it doesn't tell me that I forgot the `]`

It may be a feature request so forgive me for that 

VS Code version: Code - Insiders 1.51.0-insider (89c002ab02f87102d91efc83c191ef1174756c6a, 2020-10-15T23:17:08.035Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (9.63GB free)|
|Process Argv|--crash-reporter-id 3fb8ec7d-1b2f-4bfc-8e8b-7f5c45261437|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.50.1
material-icon-theme|PKi|4.3.0
tabnine-vscode|Tab|3.0.3
vscodeintellicode|Vis|1.2.10

(1 theme extensions excluded)

</details>

**Comment by chinmya1975** [comment]
hey there,
this can be rectified by enabling any  linter  in settings command...Linters will keep check on small mistakes
