### ISSUE TITLE
VSCode cannot code navigate some libraries. 

### ISSUE THREAD

**Issue by jaepil-choi** [microsoft/vscode#108934]
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Try to code navigate 

```python
from requests.packages.urllib3.util.retry import Retry
```

2. See that it is only accessible to .pyi, not the source code .py itself. 

Does this issue occur when all extensions are disabled?: Probably yes. Extension doesn't seem to be an issue here. 

The only way to access the source file is by going into the `site-packages/` directory and directly opening the file. 
In my case, `~/Anaconda3/envs/webscraping37/lib/site-packages/urllib3/util/retry.py`

My thoughts are that this happens because of how the backward compatibility code is written in `requests` module. 

When you go to `~/Anaconda3/envs/webscraping37/lib/site-packages/requests/util/packages.py`, it looks like the below. 

```python
import sys

# This code exists for backwards compatibility reasons.
# I don't like it either. Just look the other way. :)

for package in ('urllib3', 'idna', 'chardet'):
    locals()[package] = __import__(package)
    # This traversal is apparently necessary such that the identities are
    # preserved (requests.packages.urllib3.* is urllib3.*)
    for mod in list(sys.modules):
        if mod == package or mod.startswith(package + '.'):
            sys.modules['requests.packages.' + mod] = sys.modules[mod]

# Kinda cool, though, right?
```

Would it be possible for VSCode to find out the real source of the imported libraries? 
I think it should at least tell the user that the library is importable but not reachable in code navigation.

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
