### ISSUE TITLE
Broken Gif for new extension

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/vscode#108911]
I just published a new extension and noticed that the gif file was broken in the extension details view.

![image](https://user-images.githubusercontent.com/211268/96399631-ab76a700-1183-11eb-8f38-e2b04c4e6d25.png)

From the debugging tool, it looks like the generated link to the gif file is incorrect. It references files in the master branch. However, now for new repositories github uses main as default branch name (See https://github.com/github/renaming). so the correct link should be https://github.com/sunliangqin/VSCodeQuickJump/raw/main/assets/demo.gif
![image](https://user-images.githubusercontent.com/211268/96399679-cf39ed00-1183-11eb-979c-3d3fef57bda5.png)

**Comment by sunliangqin** [comment]
The gif file is also broken in the visual studio marketplace website.
![image](https://user-images.githubusercontent.com/211268/96400342-4fad1d80-1185-11eb-8b4c-8e5e2dde4267.png)

**Comment by sandy081** [comment]
@prashantvc FYI

**Comment by prashantvc** [comment]
Marketplace does not resolve URLs, we use only absolute paths.
`vsce` generates path for links in the README file, you can use `--githubBranch` to override the branch name.

see https://github.com/microsoft/vscode-vsce/issues/504#issuecomment-711875147

**Comment by sunliangqin** [comment]
Good to know. Thanks. Is it possible for the tool to auto detect the branch name or show an error if the branch/generated link doesn't exist?

**Comment by fiveisprime** [comment]
This is being tracked here: https://github.com/microsoft/vscode-vsce/issues/534
