### ISSUE TITLE
 "View: Reset Zoom" does not work when zooming on images

### ISSUE THREAD

**Issue by sanehab** [microsoft/vscode#108900]
- VSCode Version: 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a) x64
- OS Version: OS X 10.15.6

Steps to Reproduce:

1. Open an image
2. Zoom in
2. Open commands menu (command + shift + p)
3. Search for "View: Reset Zoom", click on it. But nothing happens and the zoom level stays as it is

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
That command is the the window's zoom level. The image preview commands are labeled `Image Preview`:

<img width="505" alt="Screen Shot 2020-10-18 at 1 59 07 PM" src="https://user-images.githubusercontent.com/12821956/96385648-1a370e80-114a-11eb-99ed-a18db76a3b6b.png">

There is currently not a `Reset zoom` command for images (prs welcome)
