### ISSUE TITLE
vscode can not update ,help

### ISSUE THREAD

**Issue by laterz** [microsoft/vscode#108959]
- VSCode Version:1.50.1
- OS Version:win7

Steps to Reproduce:

1.when i click the button 'Help->Check for Updates' ,always show error: 

net::ERR_CERT_AUTHORITY_INVALID
source:Update Service

2.in fact，this occurs since 1.49.1 . so i download the new vscodeUserSetup.exe to reinstall vscode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
> ERR_CERT_AUTHORITY_INVALID

Are you in an enterprise network?

**Comment by laterz** [comment]
> 
> 
> > ERR_CERT_AUTHORITY_INVALID
> 
> Are you in an enterprise network?

no , home network .anything else is normal, also the Extensions search / install.

**Comment by joaomoreno** [comment]
@deepak1556 Some help

**Comment by laterz** [comment]
> 
> 
> Oops missed this, Can you attach the log following these steps
> 
>     * launch vscode with `code.cmd --log-net-log=<some-absolute-path>/netlog.json`
> 
>     * check for updates under the gear icon
> 
>     * Quit the application
> 
> 
> Attach the generated netlog.json, thanks!

- [ ] 

- [ ] 

> ### **_`[](url)`_**

**Comment by laterz** [comment]
> 
> 
> Oops missed this, Can you attach the log following these steps
> 
>     * launch vscode with `code.cmd --log-net-log=<some-absolute-path>/netlog.json`
> 
>     * check for updates under the gear icon
> 
>     * Quit the application
> 
> 
> Attach the generated netlog.json, thanks!

[Uploading netlog.json…]()

**Comment by laterz** [comment]
> 
> 
> Oops missed this, Can you attach the log following these steps
> 
>     * launch vscode with `code.cmd --log-net-log=<some-absolute-path>/netlog.json`
> 
>     * check for updates under the gear icon
> 
>     * Quit the application
> 
> 
> Attach the generated netlog.json, thanks!

[netlog.zip](https://github.com/microsoft/vscode/files/5469306/netlog.zip)
