### ISSUE TITLE
UI flicker on Save, with some fun side effects

### ISSUE THREAD

**Issue by brandonmp** [Microsoft/vscode#10897]
this was discussed a little in [https://github.com/Microsoft/vscode/issues/7322] but it was closed b/c of non-response  ( @bpasero )

[Here's a screencast](https://youtu.be/3lnbWsz4KeU) of the buggy behavior

[Here's a diff't screencast](https://youtu.be/FTzFv1GyTPo) of similar actions in the same file that don't reproduce the bug

- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. clone [this repo](https://github.com/davezuko/react-redux-starter-kit) (no need to `npm install`). bug happens in my project and others as well (all `JavaScript/Node` projects), but using this repo makes replication easier.
2. open the folder in `VS Code`
3. open `.babelrc` in a tab
4. open `package.json` in another tab
5. delete a line from the `dependencies` prop in `package.json`
6. `ctrl+s` (or whatever on a mac)

**you should observe some flickering in a number of places in the UI**

7. close `package.json` tab, confirm `save` in the ensuing dialogue

**the tab should close, but the text of `package.json` should paste-over the text in your other open file, ie, `babelrc`**

This behavior also happens often when editing VS Code `settings` JSONs. 

**my settings**: 

```
$ code --list-extensions
EditorConfig.EditorConfig
Nuuf.theme-hackershaze
Shan.code-settings-sync
TsumiNa.Seti-theme
Tyriar.lorem-ipsum
alefragnani.Bookmarks
bcmarinacci.theme-material
bernardodsanderson.theme-material-neutral
bialikover.theme-seti
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
chrmarti.regex
codezombiech.gitignore
cssho.vscode-svgviewer
dbaeumer.vscode-eslint
donjayamanne.githistory
dzannotti.vscode-babel-coloring
flowtype.flow-for-vscode
gerane.Theme-AnarchistEighties
gerane.Theme-Batman
gerane.Theme-FocusLight
gerane.Theme-Sunburst
gerane.Theme-Zenburn
gerane.Theme-sublimexoria
joelday.docthis
lonefy.vscode-JS-CSS-HTML-formatter
ms-vscode.Theme-MaterialKit
msjsdiag.debugger-for-chrome
nemesv.copy-file-name
robertohuertasm.vscode-icons
seanmcbreen.MDTools
slevesque.vscode-multiclip
tnaseem.theme-seti
xabikos.JavaScriptSnippets
xabikos.ReactSnippets
zhuangtongfa.Material-theme

```

```
// these are 'user settings', 'workplace settings' file is empty
{
    "files.associations": {
        "*.js": "javascriptreact"
    },
    "editor.acceptSuggestionOnEnter": false,
    "editor.mouseWheelZoom": true,
    "editor.cursorStyle": "block",
    "editor.fontLigatures": true,
    "editor.renderIndentGuides": true,
    "editor.fontFamily": "'Fira Code',monospace, 'Droid Sans Fallback'",
    "editor.fontSize": 20,

}

```

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by brandonmp** [comment]
Thanks @bpasero - `disable-extensions` solves the problem, so ostensibly this is an extension issue. 

Should have checked that before posting! Will try and track down which extension is crazy & follow-up as you suggested.
