### ISSUE TITLE
Safari: tab linear gradient rendering is not working

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#108996]
![image](https://user-images.githubusercontent.com/5047891/96563201-f5fe3d80-12c1-11eb-9bae-fc8d0b0058d9.png)

**Comment by bpasero** [comment]
Up for grab, this may just be Safari not supporting our `linear-gradient` properly:

https://github.com/microsoft/vscode/blob/d1578555f7247b8070df0ba625d046859a163f04/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L1633-L1727

**Comment by alexdima** [comment]
possibly related, the shadow of the editor minimap is also not rendering well -- https://github.com/microsoft/vscode/issues/108822

**Comment by bpasero** [comment]
Since I cannot figure out why this happens and it looks very bad, I pushed a change to disable `linear-gradient` in tabs on Safari.

**Comment by bpasero** [comment]
I am not planning to bring it back, closing.
