### ISSUE TITLE
Allow extension developers to specify a validator regex(or even an async validator function) for the extension options

### ISSUE THREAD

**Issue by sktguha** [microsoft/vscode#108937]
So it would be good if there was an option to specify a regex in the contributes.configuration options. 
For example in my extension I am taking an absolute path to a file. So would be good if I can specify a regex for that in the contributes.configuration option. Even better would be if the extension can specify a validator function (maybe that returns a promise also ?) that will get called on extension configuration change and will give back some result and message, if the configuration is valid or not

**Comment by chrmarti** [comment]
For `"type": "string"` you can provide a regex with the `"pattern"` property.

**Comment by sktguha** [comment]
Ok thank you for the information. How about the second one, i.e specifying a validator function ? For ex I can check if the file actually exists or not and also maybe an option can be added of file type ? Where user can pick a file using a file picker in the settings UI itself ?

**Comment by sandy081** [comment]
> Even better would be if the extension can specify a validator function (maybe that returns a promise also ?) that will get called on extension configuration change and will give back some result and message, if the configuration is valid or not

What is the use case here?

**Comment by sktguha** [comment]
I can check if the file actually exists or not, once the user has entered the absolute path to the file and show appropriate message. Alternatively, maybe the extension can register something like "onPreferencesChanged" event, which can called, when there (extension only ? ) is change in setting.json

**Comment by sandy081** [comment]
There is an API already you can use to listen to configuration changes - Look for `onDidChangeConfiguration` event here - https://code.visualstudio.com/api/references/vscode-api

**Comment by sktguha** [comment]
Oh ok. Thank you. will check that
