### ISSUE TITLE
Trust Notebook Content and readonly notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#108946]
Creating an issue to capture what was discussed last week with VS Code:
Python extension would like the following capabilities:
* Hide output when notebook is not trusted (based on some metadata)
* Trusting a ntoebook (updating this metadata) should not mark the notebook as dirty
* Disable saving/editing notebooks when a notebook is not trusted
	* This is required, because of todays implementation of trusted notebooks in python extension)
	* Today if a user attempts to save an untrusted notebook, Python extension would have to handle this and swallow this method call (i.e. noop).

@rebornix /cc

**Comment by rebornix** [comment]
Added a new property `NotebookDocumentMetadata#trusted` to control if insecure outputs can be rendered (html, javascript, svg, etc). We will only render secure ones if `trusted: false`. The Jupyter extension can run command `vscode.commands.executeCommand('notebook.trust', vscode.window.activeNotebookEditor.document.uri);` to turn the notebook to trust mode without making the document dirty.

Note that neither the property or the command is finalized. We can discuss what should the core do and what belongs to the notebook provider once we have better understanding of trusted workspace and trusted code execution.

**Comment by mjbvz** [comment]
I opened a few UX issues with the current implementation but looks like python is waiting for trusted workspaces:

https://github.com/microsoft/vscode-jupyter/issues/4088
https://github.com/microsoft/vscode-jupyter/issues/4089
