### ISSUE TITLE
Cannot disable file auto save

### ISSUE THREAD

**Issue by thiemeljiri** [microsoft/vscode#108932]
I cannot disable file auto save.

**I cannot uncheck "Auto Save" under "File" menu.** I disabled it in User settings but this option is still checked in file menu.   

Restarting VS Code has no effect. I tried running VS Code without extensions and it behaves exactly the same. So it's very likely not related to any extension.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by thiemeljiri** [comment]
Hi @bpasero, I've just tried and it behaves exactly the same. In VS Code Insiders I couldn't untick the "auto save" under file menu. This time it was fresh installation I did from the link you provided. I didn't have VS Code Insiders installed before. This is really annoying and should should be investigated from your side. Thanks.

**Comment by bpasero** [comment]
@thiemeljiri what OS is this?

**Comment by thiemeljiri** [comment]
@bpasero Windows 10 Enterprise 64bit

**Comment by bpasero** [comment]
Does it reproduce when you configure `"window.titleBarStyle": "native"`

**Comment by thiemeljiri** [comment]
@bpasero Yes. And now I can see that clicking on "Auto Save" under "File" menu actually does some changes in settings.json - "files.autoSave" chnages its value between "off" and "afterDelay". But the tick remains and even when it's set to "off" the files are still save automatically.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by thiemeljiri** [comment]
As I mentioned in the original comment, I have already tried that. And as for VSC Insiders - I have no extensions there.

As for `"window.titleBarStyle": "native"`, I've tried that only in VSC Insiders with no effect.

**Comment by bpasero** [comment]
I cannot explain this, unless maybe your settings file is not valid. Does it show errors when you open it as JSON file?

**Comment by thiemeljiri** [comment]
No, it doesn't. It is valid. And it happens even if it's completely empty.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by thiemeljiri** [comment]
Hi @bpasero.

Ok, I've found out what was the issue. And it was very puzzling to me. I tried both scenarios on the same project. And now I've found out that there is also a `.vscode` folder with `settings.json` in this project which I haven't seen there before.

I don't have any experience with this king of settings, but I don't like the current behavior. Settings in this file is forced to the editor and you cannot change it unless you modify this file. But it seems to me a bit puzzling.

I'd expect probably some of these scenarios as a user:

1.  When project editor settings file is present, the options it overrides should be either disabled and/or somehow marked as overridden by project editor settings file.
2. When project editor settings file is present and the user tries to change the options it overrides in the UI, these changes are reflected in the project editor settings file, or both, in project and user settings file. Currently only user settings file is modified leaving the user puzzled why it's not working.

Please, let UX designer or other responsible people in your team know about this. Encountering something like this for the first time is *extremely* frustrating.

Thanks!

BR,
thiemeljiri

**Comment by bpasero** [comment]
@thiemeljiri great catch, we should be able to handle that case better.

**Comment by bpasero** [comment]
Opening up for a PR, the code that needs to be looked at is:

https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/workbench/services/filesConfiguration/common/filesConfigurationService.ts#L186-L201

**Comment by jeanp413** [comment]
I'll take a look at this

**Comment by jeanp413** [comment]
I'll take a look at this

**Comment by bpasero** [comment]
**Verification:** verify auto save can be turned on and off via File > Auto Save toggle in main menu. Verify this also works if `files.autoSave` is configured as workspace setting and then is updated inside the workspace.
