### ISSUE TITLE
A keybinding when-clause for if the cursor is on a followable link

### ISSUE THREAD

**Issue by bs** [microsoft/vscode#108948]
I'd like to bind, for example, cmd-enter to go-to-definition, but have it conditional on having the cursor on a link that has a definition to goto.

I've searched docs and issues and don't see a way to get this (known) context?

**Comment by jrieken** [comment]
> but have it conditional on having the cursor on a link that has a definition to goto.

We don't know that a word is a goto definition target. It would mean that we need to execute go-to-def as the cursor moves around which IMO is too expensive to become real.

**Comment by bs** [comment]
Is there a no method, similar to a language server, that would register which components are links ahead of time?￼
