### ISSUE TITLE
[Webview View] Can't drag view into Webview View to split

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#108953]
1. Install any extension that contributes WV
1. Drag WV to the Activity Bar so that this View takes the entire SideBar
1. Try to drag any View into it

**Comment by sandy081** [comment]
I am not able to drag a view onto webview.

**Comment by mjbvz** [comment]
Any idea what you are doing differently?

![Dec-04-2020 11-58-08](https://user-images.githubusercontent.com/12821956/101209085-0840fa80-3628-11eb-95e7-eac16ce5a821.gif)

**Comment by usernamehw** [comment]
@mjbvz WV should take the entire View Container Sidebar/Panel (not being split with other view)

**Comment by mjbvz** [comment]
I've fixed dragging into a webview that's one section of the panel. Let's keep tracking the issue with dragging into a full panel webview with #144122. The commit fixed some—but not all cases—of that
