### ISSUE TITLE
Literal not found under cursor

### ISSUE THREAD

**Issue by wysisoft** [microsoft/vscode#108910]
this happened while pasting a line to a typescript file.

![image](https://user-images.githubusercontent.com/15177964/96399182-f811b080-118a-11eb-8a50-f02c55dbada7.png)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform, and whether it still occurs if you run with all extensions disabled. Based on the message text, this looks like an extension problem.
