### ISSUE TITLE
Starting a Web service in termianl with VsCode sometimes slows access

### ISSUE THREAD

**Issue by ayuayue** [microsoft/vscode#108961]
- VSCode Version: 1.50.1
- OS Version: win10

Steps to Reproduce:

1. terminal run a web service
2. brower open service 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I don't think I have enough to go on here, whatever you run in the terminal shouldn't be throttled or anything, it's just a regular process just like other terminals.
