### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by Ankit0203** [microsoft/vscode#108936]
While minimize vs code and then  run any command in terminal in written over path

**Comment by yume-chan** [comment]
Please use the [issue template](https://github.com/microsoft/vscode/issues/new?template=bug_report.md) to include your operating system and vs code versions.

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
