### ISSUE TITLE
VSCode closes every time I try to open a link

### ISSUE THREAD

**Issue by RepleDEV** [microsoft/vscode#108916]
- VSCode Version: 1.50.1 (Snap)
- OS Version: Arch Linux x86_64 5.8.14-arch1-1 KDE Plasma DE

Steps to Reproduce:
1. Create a comment containing a link
2. Click on the link
3. VSCode should suddenly close

This also occurs when trying to turn on settings sync.
**EDIT**:  
Other places this issue occurs (that I know of):
Deleting a file
Signing in through the vscode-spotify extension

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
@joaomoreno Is our snap supported on Arch?

**Comment by joaomoreno** [comment]
#100940
