### ISSUE TITLE
Unable to resolve workspace folder 

### ISSUE THREAD

**Issue by oxk4r01** [microsoft/vscode#108924]
- VSCode Version: 1.50.1
- OS Version: Windows 10 pro

Steps to Reproduce:

1. Save some workspace to OneDrive.
2. Try to open it in other computer.
3. Files wont open and a message in sidebar saying 'unable to resolve workspace folder'.
4. I won't get the error if I open that workspace in the original computer.
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by valbrea** [comment]
Similar problem as mine.
When using version 1.50.1, I saved my workspace from WSL to Windows Desktop.
It can't be opened in windows and said 'unable to resolve wrkspace folder'.
I can only open it from bash.
Never encountered before, and the previously saved workspace can still be opened in Windows.

I open '.code-workspace' file in notepad
Old file writes:

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

I can not reproduce it.
If you can repro, can you please create a repository on GitHub which I can simply clone and reproduce this issue? Thanks
