### ISSUE TITLE
Syntax Coloring Is Missing

### ISSUE THREAD

**Issue by Shashank-Prasanna** [microsoft/vscode#108901]
- VSCode Version: 1.50
- OS Version: macOS 1.15
 I have been coding with vscode for about a month now, and just recently I discovered that the syntax coloring is gone! I don't know why or how, it is just gone! Here is a picture:
![code](https://user-images.githubusercontent.com/57506946/96376263-d2b18200-114b-11eb-833a-e0be604619f4.png)
Most of the text is all white! This happened just before I upgraded to 1.50, thinking that it would fix the issue. It didn't. 
Thanks in advance for any help :)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
What language mode is your editor in (check the status bar)?

**Comment by hosseinzamaninasab** [comment]
Just look at issue #111, it may helps you.

**Comment by Shashank-Prasanna** [comment]
No, it doesnt help. The issue seemed to be outdated software, but I'm already running 1.50. Also, yes I checked the language bar and it is on Javascript. I tried with all of my extensions disabled and it is still all white. However, I did just change the color of my cursor. Maybe that??

**Comment by aeschli** [comment]
@Shashank-Prasanna Can you paste or link to the sample code to reproduce?

**Comment by Shashank-Prasanna** [comment]
Ok. I am using Dark (Visual Studio Default), and it reproduces with other themes as well. It happens with other code as well. Let me put some that doesn't work:
`push();`
 `translate(this.body.position.x, this.body.position.y);`
 `ellipseMode(CENTER); `
`ellipse(0, 0, this.radius);`
In the case above, push, translate, ellipseMode, and ellipse are all white, including others.

**Comment by aeschli** [comment]
The  Dark (Visual Studio Default) is a very simple theme and does not color function or variable references.
Try the Dark+ theme and you will see colors for the example above:
![image](https://user-images.githubusercontent.com/6461412/97117404-dcb32200-1703-11eb-8a55-682f3af8a40d.png)

**Comment by Shashank-Prasanna** [comment]
Oh... whoops. Yeah, that fixed it. I should probably look into the problem more before making a GitHub issue. Thanks for all your help everyone!
