### ISSUE TITLE
Problem with terminal

### ISSUE THREAD

**Issue by Mateushen19** [microsoft/vscode#108943]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
![tela](https://user-images.githubusercontent.com/51799470/96480783-11f5d680-1211-11eb-9956-4f43a59044cc.png)

2. Terminal can't open

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
How are you opening the terminal? Which VS Code version are you running?

**Comment by Tyriar** [comment]
I suggest reporting to whatever maven extension is launching the terminal, it might be on their side, especially if you don't see this with regular terminals.
