### ISSUE TITLE
Allow extensions to determine if a position is within a fold

### ISSUE THREAD

**Issue by robsonpeixoto** [microsoft/vscode#108960]
This issue(https://github.com/VSCodeVim/Vim/issues/1004) very annoying but need it(https://github.com/microsoft/vscode/issues/22276).

Is the right time to discuss about it again?

Thanks

**Comment by aeschli** [comment]
We have #81498 for the API request. The issue also explain why we hesitate to make that API available.

We're happy to help the VIM extension. Any chance we can improve the `cursorDown` command with additional parameters so it does what VIM needs?
