### ISSUE TITLE
Use older designs of VSCode in newer versions

### ISSUE THREAD

**Issue by dragonDScript** [microsoft/vscode#108906]
Duplicate of another issue, but with another focus.

Ok. So I've just tried an older version of VSCode (october 2018) and I really like the old design. But October 2018 is too old and works a lot different from recent versions.
My suggestion would be to create editor's icons/animations like icon packs.
I know that this carries a lot of problems, but also gives the editor a new fresh look and flexibility. Thank you.

**Comment by misolori** [comment]
Please upvote https://github.com/microsoft/vscode/issues/92791 to be able to use custom icons in the editor

**Comment by dragonDScript** [comment]
Sure. Thank you
