### ISSUE TITLE
[VCQ][DevDiv_VSO][VSCode][Placeholder meaning check]

### ISSUE THREAD

**Issue by danyeh** [microsoft/vscode#108986]
<table style="border-collapse:collapse;width:631pt;" width=841>
<tbody>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>MS PM</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border-top:none;border-right:0.5pt solid windowtext;border-bottom:0.5pt solid windowtext;border-left:0.5pt solid windowtext;border:1px solid #d4d4d4;border-left:none;width:527pt;" width=703></td>
 </tr>
<tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>MOR PM</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border-top:none;border-right:0.5pt solid windowtext;border-bottom:0.5pt solid windowtext;border-left:0.5pt solid windowtext;border:1px solid #d4d4d4;border-left:none;width:527pt;" width=703>Jan Baltus (Moravia IT)</td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>String Resource ID</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border-top:none;border-right:0.5pt solid windowtext;border-bottom:0.5pt solid windowtext;border-left:0.5pt solid windowtext;border:1px solid #d4d4d4;border-left:none;width:527pt;" width=703>0; &quot;src/vs/workbench/services/themes/common/themeConfiguration.preferredLightColorTheme&quot;</td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=80><strong>Source String</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703>Specifies the preferred color theme for light OS appearance when `#{0}#` is enabled.</td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>Subtenant</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703>VSCode</td>
 </tr>
<tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>Source Control Link</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703></td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>Filename</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703>vscode-workbench\vs_workbench_services_themes.xlf</td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=40><strong>Question</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703>What will &quot;#{0}#&quot; be replaced with?

0; &quot;src/vs/workbench/services/themes/common/themeConfiguration.preferredLightColorTheme&quot;
0; &quot;src/vs/workbench/services/themes/common/themeConfiguration.preferredHCColorTheme&quot;
0; &quot;extensions/ms-vscode.js-debug//src/ui/disableSourceMapUI.disableSourceMapUi.msg&quot;</td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>Additional details</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703></td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#ffc000;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=60><strong>Core Team Response</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703></td>
 </tr></tbody>
 </table>

**Comment by aeschli** [comment]
It'a settings id. It's important that it's surrounded by `` `# `` and `` #` ``

**Comment by isidorn** [comment]
Adding verified based on code review
