### ISSUE TITLE
Pasting Large Amounts of Text to Terminal Doesn't Work

### ISSUE THREAD

**Issue by philkloose** [Microsoft/vscode#10892]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

I find that when I'm copy/pasting a chunk of text from an editor window that the paste command stops working when I reach some arbitrary, variably large size.  Usually a few thousand characters of text will trigger the bug.

Steps to Reproduce:
1. Open VS Code and an integrated terminal (in my case, PowerShell, but the same issue exists in cmd.exe)
2. Create a large block of text.  I don't believe the format of the text matters at all
3. Paste the text in the terminal below and it will fail to paste when your text selection gets large enough.  I can typically trigger the issue after a few thousand characters.

I know that the text is in the clipboard because I can paste it outside to Notepad as well as to another editor tab inside of VSCode.  The issue only exists when pasting to the terminal.

**Comment by Tyriar** [comment]
No plans to fix, the PowerShell extension should probably give a better experience for running PS in the terminal now https://github.com/PowerShell/vscode-powershell
