### ISSUE TITLE
preLaunchTasks not working for multi-root workspaces

### ISSUE THREAD

**Issue by KorbinianK** [microsoft/vscode#108928]
- VSCode Version: 1.50.1
- OS Version: MacOS Catalina 10.15.6

**Steps to Reproduce:**

1. Clone https://github.com/KorbinianK/task-issue/ (very very basic TypeScript setup)
2. Open the workspace through the file
3. Try debugging it with F5
4. The preLaunchTask cannot be found

Does this issue occur when all extensions are disabled?: Yes

**Comment:**
The goal is to debug a typescript project, for that I have to run a preLaunchTask and compile it. This works fine when opening a project folder directly, but the tasks cannot be found when using a multi-root workspace structure.

Search results and documentation on [Workspace Tasks](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_tasks) did not yield any results or help.

Some things I've tried:
- ` "preLaunchTask": "test-task"`
- ` "preLaunchTask": ":test-task"`
- ` "preLaunchTask": "${workspaceRoot}/test-task"`
- ` "preLaunchTask": "${workspaceRoot}/test-task"`

**Comment by isidorn** [comment]
You basically need to use workspace tasks I belive. More details here
https://github.com/microsoft/vscode/issues/36966
Though leaving this up to @alexr00 as she might have more details

**Comment by alexr00** [comment]
@isidorn is correct, we don't currently support using a folder task in a workspace.

**Comment by KorbinianK** [comment]
@alexr00 so there is no way to do this then, as workspace tasks do not support typescript, only `"shell"` and `"process" `?
Is this a planned feature I can track somewhere? It seems to me a rather important feature for any bigger typescript project.  Every other issue I found through the one linked above and is related, has been simply closed.

**Comment by alexr00** [comment]
This one is actually exactly what you're looking for: https://github.com/microsoft/vscode/issues/93149
