### ISSUE TITLE
[Feature Request] Add "search in directory" to the project explorer context menu

### ISSUE THREAD

**Issue by Wayofthesin** [microsoft/vscode#108944]
I very often search for something in sub-directories of my workspace. It is inefficient to copy directory path every time I need to search somewhere else. It would be massively useful to extend the project explorer context menu with "Search in directory" option. It should bring the user to the "Search in files" tab with extra filter being the directory selected.

The extra filter should be separate from the existing filters. Thanks to that we avoid messing up with existing search filters.

**Comment by gjsjohnmurray** [comment]
![image](https://user-images.githubusercontent.com/6726799/96508897-2b1f7700-1253-11eb-8ca7-2de167e7829b.png)

If that isn't what you need please give more details.
