### ISSUE TITLE
Zoom bug with window reload

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#108920]
1. Open VS Code
2. Zoom in
2. Close VS Code
3. Open VS Code
4. Zoom out
5. `Reload Window`

🐛 Window is zoomed in

**Comment by bpasero** [comment]
Wasn't able to repro :|

**Comment by joaomoreno** [comment]
Time to whip out everyone's favorite recorder:

![recording (7)](https://user-images.githubusercontent.com/22350/96465749-9a807100-1229-11eb-8399-830241d9c39d.gif)

**Comment by joaomoreno** [comment]
I can even repro on Linux, out of sources.

**Comment by joaomoreno** [comment]
Maybe https://github.com/microsoft/vscode/commit/c7fe3b41ae4c22de8b84a95076b8fe43aa259635

**Comment by joaomoreno** [comment]
I tried debugging but I got lost with all the places zoom comes into play. 😢

**Comment by joaomoreno** [comment]
Also https://github.com/microsoft/vscode/commit/836fbb1b5db08306d3e90933b4996e4570a59e04 cc @deepak1556

**Comment by bpasero** [comment]
Those commits seem relevant, marking "help wanted" if someone has ideas.

**Comment by bpasero** [comment]
Will fix this when I land https://github.com/microsoft/vscode/pull/104779. I added this check for `0`:

https://github.com/microsoft/vscode/blob/7f035b4be73a7ce9ceafb2128c066b717eafaf87/src/bootstrap-window.js#L51-L51

To reduce required sync IPC calls on startup and that is the issue here. Should be fine once we do this from the main side.

**Comment by joaomoreno** [comment]
Since https://github.com/microsoft/vscode/pull/104779 is merged, can we get this fix in?

**Comment by bpasero** [comment]
No, it is https://github.com/microsoft/vscode/pull/114020 that is not merged yet. It is blocked by our `vscode-file` protocol work.

**Comment by bpasero** [comment]
I am now always using `webFrame` to set the zoom level early on, even if it is `0`.
