### ISSUE TITLE
Auto Build Marlin - command not found: platformio

### ISSUE THREAD

**Issue by slwise** [microsoft/vscode#108903]
I am new to compiling my own firmware. I am now trying to build Marlin 2.0.7.2 for the SKR Mini E3 V1.2 using the custom configuration supplied by the Marlin GitHub. I have used VSCode to compile Marlin versions 2.0.7 and 2.0.7.1 for the same board. Both compiled beautifully using the Auto Build Marlin and the Platformio plugins. I am doing the same thing as before but now I keep receiving this error:

platformio run -e STM32F103RC_btt_512K ; echo "done" >/var/folders/08/p81zkj6x7l7gq17dsxv4pxrh0000gn/T/ipc
stevewise@Steves-MacBook-Pro Marlin-2.0.x % platformio run -e STM32F103RC_btt_512K ; echo "done" >/var/folders/08/p81zkj6x7l7gq17dsxv4pxrh0000gn/T/ipc
zsh: command not found: platformio
stevewise@Steves-MacBook-Pro Marlin-2.0.x % 

I have uninstalled everything and reinstalled several times with no success. I was able to get a successful build by going into project tasks in Platformio and doing the build from there. I apologize in advance if I am doing something stupid but I can't figure out what is wrong. I have searched the internet but with no success. Thanks for your help.

**Comment by Raspa888** [comment]
Same problem! 
echo "done" >/var/folders/kh/9r2ycv7921lgg6q7t7twmsym0000gn/T/ipc
zsh: command not found: platformio

**Comment by slwise** [comment]
I have also noticed this error when doing the update in PlatformIO. 

Updating platformio/contrib-pysite            2.38.201019 @ ~2.38.0              [Incompatible 2.39.201019]

I removed the folder ".platformio/penv" and then updated again but with the same error. Not sure if this helps.

**Comment by etiennepelletier3** [comment]
I just got the same message! There must be a problem with the new update of platform.io...

**Comment by Raspa888** [comment]
Anyway I can build and upload. Sometimes is not uploading fine but repeating the process it works. 
You have to go to the left vertical menu and click on the Platformio icon, then choose the file, in may case is env:melzi_optimized, @slwise in your case should be env:STM32F103RC_btt_512K. Click it and you will see below it build, upload and more options. 
I hope this will help!

**Comment by slwise** [comment]
> Anyway I can build and upload. Sometimes is not uploading fine but repeating the process it works.
> You have to go to the left vertical menu and click on the Platformio icon, then choose the file, in may case is env:melzi_optimized, @slwise in your case should be env:STM32F103RC_btt_512K. Click it and you will see below it build, upload and more options.
> I hope this will help!

**Comment by Tyriar** [comment]
This seems like a question for the platformio extension/team https://github.com/platformio/platformio-vscode-ide/issues
