### ISSUE TITLE
New Auto Attach options do not work with tsc-watch and inspect-brk flag

### ISSUE THREAD

**Issue by PizzaPartyInc** [microsoft/vscode#108925]
- VSCode Version: 1.50.1
- OS Version: Windows 10 Enterprise Version 1803

Steps to Reproduce:

1. Have a script that uses tsc-watch (version ^4.2.3) to launch a project in debug mode, e.g.
```
"start:debug": "tsc-watch --onSuccess \"node -r dotenv/config --inspect-brk dist/index.js\"",
```
2. Have launch.json contents:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to Node Server",
      "port": 9229,
      "restart": true
    }
  ]
}
```
3. Set Auto Attach option to any of available new options: Always/Smart/With Flag Only/Disabled
3. run the `start:debug`
4. Process waits for attach to be done manually
![image](https://user-images.githubusercontent.com/37663061/96427247-fb4a8200-1206-11eb-875b-f386a9bb7bf9.png)

Does this issue occur when all extensions are disabled?: Yes

Clarifications: When Auto Attach was implemented with On/Off options - this was working, process would start, debugger would attach automatically, no explicit configuration changes were needed.

I can still debug using other ways, e.g. using Node.js (preview) or attaching and un-attaching debugger manually, but would really like to make such scripts work like they used to (just launch a script - debuger attaches, Ctrl+C will stop the process and un-attach the debugger)

Thank you! :)

**Comment by connor4312** [comment]
Try running without [--inspect-brk] ([see reason](https://github.com/microsoft/vscode-js-debug/blob/master/COMMON_PROBLEMS.md#my-app-doesnt-start-run-and-i-use---inspect-brk-to-load-it)). Let me know if you still have issues at that point 🙂 

Tagging with needs-more-info to auto close after 7d.

**Comment by PizzaPartyInc** [comment]
Thanks for the reference! 

Unfortunately, removing the `--inspect-brk` does not work. Tried following script variations with all Auto Attach options:

```
"start:debug": "tsc-watch --onSuccess \"node -r dotenv/config dist/index.js\"",
```

```
"start:debug": "tsc-watch --onSuccess \"node -r dotenv/config --inspect dist/index.js\"",
```

The app starts normally, but debugger is not attached.

**Comment by PizzaPartyInc** [comment]
Ok, managed to make it work with `--inspect` and "Auto Attach: With Flag". The issue was that after enabling Auto Attach - it is now required to restart the terminal (or VScode). This is a one-time action and once auto attach is enabled - this will no longer be required. VScode gives you a warning, but it's easy to miss:
![image](https://user-images.githubusercontent.com/37663061/96542907-d2c89380-12ab-11eb-8087-f2af6e36defc.png)

Anyway, I think this is now resolved. Thank you! :)
