### ISSUE TITLE
Kerberos Authentication with SSH

### ISSUE THREAD

**Issue by blueostrich18** [microsoft/vscode#108945]
I'd like to be able to SSH to a server with Kerberos(gssapi) authentication. Searching github and the internet this is something that many in the enterprise/corporate environments would appreciate. Not sure why https://github.com/microsoft/vscode-remote-release/issues/250 was closed. A valid reason was not given. At the very least make a modification so the plink workaround works again.

**Comment by roblourens** [comment]
It is just not practical for us to do this. I don't know what the comment about plink is referring to, if someone can give me more details I can try to give support for that.

**Comment by blueostrich18** [comment]
The plink work around is posted [here](https://github.com/microsoft/vscode-remote-release/issues/250#issuecomment-506063523)

**Comment by roblourens** [comment]
Do you know why it broke? What options are not supported?
