### ISSUE TITLE
Problem to copy content of a opened file

### ISSUE THREAD

**Issue by victorschinaider** [Microsoft/vscode#10891]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1. In "Open Editors", open two different files with some content
2. Choose one of the two files to open in editor
3. When it's open, click and open the other file, and press "Ctrl + a" and, after that, try to copy by pressing "Ctrl + c"
4. Open the first file again, and try to paste the content. The clipboard contains content before the "new copy".

![image](https://cloud.githubusercontent.com/assets/16581931/17931474/069751a0-69e2-11e6-963a-1632d2ab3c5a.png)

Ps.: Observe when you press "Ctrl + a", the "lines numbers" are selected too.

**Comment by mrmlnc** [comment]
Yes, sometimes noticed the same behavior. But couldn't find any patterns of occurrence of the problem.

**Comment by sandy081** [comment]
@victorschinaider Can you please make it clear on 

> Step 4: Open the first file again, and try to paste the content. The clipboard contains content before the "new copy".

Or Is it that the first files contains the copied content before paste?

**Comment by victorschinaider** [comment]
@sandy081 Ok, the 4th step needs reformulation.

   4. Now, try to paste the copied content in anywhere. You'll see, based on pasted content, that the clipboard memory region do not suffered any changes by the last "Crtl + C" action.

**Comment by sandy081** [comment]
Thanks for confirmation

**Comment by alexandrudima** [comment]
This has already been fixed on master. @victorschinaider the fix will come out with the August stable release or you can get it already now using the Insiders channel.
