### ISSUE TITLE
Search not looking for files in paths starting with a dot (.)

### ISSUE THREAD

**Issue by ameltzerMSFT** [microsoft/vscode#108955]
Issue Type: <b>Bug</b>

When I have a file contained in a directory starting with a dot, search is not finding it. This means I often times need to fall back to using findstr in a terminal window to find the text I am looking for.

Search result:
![image](https://user-images.githubusercontent.com/26661268/96510379-48802100-1212-11eb-841c-6347b60384ef.png)

Findstr result:

![image](https://user-images.githubusercontent.com/26661268/96510466-68afe000-1212-11eb-9b01-9c7c66dc6b0b.png)

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz (12 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.70GB (18.96GB free)|
|Process Argv|. --crash-reporter-id 696441d4-7d45-4750-a6e7-db250750c74a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
xml|Dot|2.5.1
gitlens|eam|10.2.2
php-cs-fixer|hig|1.1.4
vscode-JS-CSS-HTML-formatter|lon|0.2.3
render-crlf|med|1.5.15
devinsights|Mic|2020.10.15-1
vscode-nmake-tools|Mic|3.0.200420008
prettify-json|moh|0.0.3
vscode-azureappservice|ms-|0.19.0
vscode-azurefunctions|ms-|0.24.1
csharp|ms-|1.23.4
vscode-dotnet-runtime|ms-|0.1.2
mssql|ms-|1.9.0
remote-wsl|ms-|0.50.1
azure-account|ms-|0.9.3
azurecli|ms-|0.5.0
cpptools|ms-|1.0.1
powershell|ms-|2020.6.0
azurerm-vscode-tools|msa|0.13.0
trailing-spaces|sha|0.3.1
vscode-icons|vsc|11.0.0

</details>

**Comment by roblourens** [comment]
Please check whether any of the tips here help: https://github.com/microsoft/vscode/wiki/Search-Issues

It's likely that folder is excluded by your .gitignore or exclude settings

**Comment by ameltzerMSFT** [comment]
@roblourens I wasn't aware of this setting! What a strange default. In any event, I think this was the root cause.
