### ISSUE TITLE
I Run VS Code as root so i can enable the glow effect of color theme Synthwave '84 in Linux Ubuntu

### ISSUE THREAD

**Issue by whizzkkid** [microsoft/vscode#108905]
- VSCode Version: Latest
- OS Version: Linux

Steps to Reproduce:

1. Install the theme "Synthwave '84"
2.And follow the steps to enable the Glow effect

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Not sure what you're asking exactly, but if it's because you need to run it as root that's because the Synthwave theme patches VS Code itself, which we wouldn't recommend doing and can't support the client if you do.

**Comment by whizzkkid** [comment]
> Not sure what you're asking exactly, but if it's because you need to run it as root that's because the Synthwave theme patches VS Code itself, which we wouldn't recommend doing and can't support the client if you do.

hi there, 
             actually I  tried to enable glow effect of that theme and also in their guide they also said enabling glow effect might 
make VS Code buggy, they stated that "VS code doesn't natively support text effects and as a result, the glow is experimental. It's likely to be buggy " and when I activated the glow effect the bug appeared whenever i start my editor it use to give me error message. then i install extension fix VScode checksum which fix that issue.

**Comment by Tyriar** [comment]
Ok, just note that you're changing the source of the client though, and then removing our protections which detect the source has changed. Not recommended as the extensions might cause random issues since they're patching the source which changes every month.
