### ISSUE TITLE
extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by Jaswant9829** [microsoft/vscode#108988]
> 

> [Issue](url) Type: <b>Feature Request</b>

extension host terminated unexpectedly.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.1.7600

1.

- [ ] 
![Capture](https://user-images.githubusercontent.com/73154682/96542359-8b4c0280-12bf-11eb-93d5-40acb9c6c1bb.PNG)

**Comment by gjsjohnmurray** [comment]
I guess this is related to #108989
