### ISSUE TITLE
Output args from task with g++ compiler doesn't work

### ISSUE THREAD

**Issue by YohanVienne** [microsoft/vscode#108931]
- VSCode Version: 1.50.1
- OS Version: Win10 2004
- G++ version: 4.8.3

-o argument on task to compile with g++ a *.cpp file doesn't work, I have tried to add a "build" folder for output, but the compiler only output a exe in same folder of origin
 
Steps to Reproduce:

1. a simple helloworld.cpp:

`#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}`

2.Configure a task with output path:
`> {

    "version": "2.0.0",

	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++.exe build abc",
			"command": "C:\\winBuilds\\bin\\g++.exe",
			"args": [
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\build\\${fileBasenameNoExtension}.exe"
			],
			"options": {
				"cwd": "C:\\winBuilds\\bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: C:\\winBuilds\\bin\\g++.exe"
		}
	]
}`

3. Output of the exe is always at same path or name of original source

Does this issue occur when all extensions are disabled?: Yes

Any idea of the problem ?

**Comment by sweihub** [comment]
I have the same issue with Remote-SSH mode, the args dose not work at all, I use /usr/bin/echo to ouput the comnand line, any prompt solution will be apprecated.

tasks.json

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "Joy Build",
			"command": "/usr/bin/echo",
			"args": [
				"-I./",
				"-I/opt/gcc-8.4.0/include/c++/8.4.0",
				"-I/opt/gcc-8.4.0/include/c++/8.4.0/x86_64-pc-linux-gnu -I/usr/include/python3.6m -flto -ggdb -fno-omit-frame-pointer -Wextra -Wall -fpic -DCACHE_LINE=64 -std=c++20",
				"-c",
				"${file}",
				"-o",
				"${fileDirname}/${fileBasenameNoExtension}.o",			
			],
			"options": {
				"cwd": "/opt/llvm-10.0.0/bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: /opt/llvm-10.0.0/bin/clang++"
		}
	]
}
```

Output indicates the args dose not work at all.

```
> Executing task: Joy Build <

Starting build...
-g /mnt/nas01/home/awei/joy/.vscode/tasks.json -o /mnt/nas01/home/awei/joy/tasks

Build finished successfully.
Terminal will be reused by tasks, press any key to close it.

```

**Comment by sweihub** [comment]
Quick solution/workaround

Remove the `“type”: "cppbuild"` property will work, my /usr/bin/echo output seems working

```
> Executing task: /usr/bin/echo -I./ -I/opt/gcc-8.4.0/include/c++/8.4.0 -I/opt/gcc-8.4.0/include/c++/8.4.0/x86_64-pc-linux-gnu -I/usr/include/python3.6m -flto -ggdb -fno-omit-frame-pointer -Wextra -Wall -fpic -DCACHE_LINE=64 -std=c++20 -c /mnt/nas01/home/awei/joy/perfhelp/source/engine/create_app.cpp -o /mnt/nas01/home/awei/joy/perfhelp/source/engine/create_app.o <

-I./ -I/opt/gcc-8.4.0/include/c++/8.4.0 -I/opt/gcc-8.4.0/include/c++/8.4.0/x86_64-pc-linux-gnu -I/usr/include/python3.6m -flto -ggdb -fno-omit-frame-pointer -Wextra -Wall -fpic -DCACHE_LINE=64 -std=c++20 -c /mnt/nas01/home/awei/joy/perfhelp/source/engine/create_app.cpp -o /mnt/nas01/home/awei/joy/perfhelp/source/engine/create_app.o

Terminal will be reused by tasks, press any key to close it.

```
