### ISSUE TITLE
extension cache issue

### ISSUE THREAD

**Issue by slavik-lvovsky** [microsoft/vscode#108933]
- VSCode Version: 1.50.0
- OS Version: Windows 10

Steps to Reproduce in vscode:

1. git clone the test extension repository: https://github.com/slavik-lvovsky/vscode-ext-bug.git
2. run **npm i** in the cloned folder.
3. run the cloned extension using the provided "Extension" launch configuration.
4. **npm i -g generator-code@1.1.0**
5. run the extension "Test Code Gen" command
6. **npm i -g generator-code@1.3.3**
7. run the extension "Test Code Gen" command

The same scenario works without issues when you run the provided "Node" launch configuration. 

It fails with exception because it tries to find a module that does not exists anymore.
I my opinion some vscode cache mechanism still holds map of all previously loaded modules and is not updated when these modules has changed/removed.
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Please ask on StackOverflow on how to remove a loaded module and its dependencies from the runtime: https://github.com/slavik-lvovsky/vscode-ext-bug/blob/82795a0987b44a351d5e2427e25aa4917dc5f547/env.js#L7

**Comment by slavik-lvovsky** [comment]
I asked the question in StackOverflow but I still think it is a bug. No one answers on it.
You can easily reproduce it using the simple extension I created.
