### ISSUE TITLE
Screen freeze when trying to move any folder or file to trash

### ISSUE THREAD

**Issue by Chaostheorie** [microsoft/vscode#108904]
- VSCode Version: 1.50.1 x64
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. Move any file or folder to trash with vscode

Does this issue occur when all extensions are disabled?: Yes

As mentioned in #43508. This is *still* a problem for apparently *nix systems. This occurs not when removing directly

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/101920
