### ISSUE TITLE
[TS] Wrong debugger hover value

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10899]
- VSCode Version: Code - Insiders 1.5.0-insider (c4f365235906cd689e55376e44cc106003ac06b3, 2016-08-24T06:04:42.373Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

Code:
```ts
import * as lodash from 'lodash'

let keys = lodash.keys({a:1,b:2})
console.log(keys)
debugger

```
Notice that hovering `keys` from `let keys` doesn't show values of `keys` but rather definition of `lodash.keys`

![zvc9sxcsfp](https://cloud.githubusercontent.com/assets/1723815/17937651/d281d3e0-69f0-11e6-975b-9aef00ecbdb1.gif)

**Comment by isidorn** [comment]
There were some improvments in the debug hover that should take care of this issue. Can you please try again and let me know if you still see it.
You can try on Monday with the insiders release - thanks!
