### ISSUE TITLE
License - clarify the "Data" section

### ISSUE THREAD

**Issue by mattdsteele** [Microsoft/vscode#109]
On the website's [license page](https://code.visualstudio.com/License), I'm interested in this section:

>  DATA. The software may collect information about you and your use of the software, and send that to Microsoft. Microsoft may use this information to provide services and improve our products and services. **For this pre-release version, users cannot opt out of data collection. There may also be some features in the software that enable you to collect data from users of your applications.** If you use these features to enable data collection in your applications, you must comply with applicable law, including providing appropriate notices to users of your applications. You can learn more about data collection and use in the help documentation and the privacy statement at http://go.microsoft.com/fwlink/?LinkID=528096&clcid=0x409. Your use of the software operates as your consent to these practices. 

**Emphasis** mine. My employer has concerns about this section. We'd love to have VS Code as an option - are there plans to revise this section after Code has a public release? Or perhaps a clearer description of what data is being collected and sent from users?

**Comment by egamma** [comment]
At this pre-release stage, it’s especially important that we understand how our users are interacting with the product and where they are experiencing problems so we can make it better!  For GA, we intend to provide a settings option for opting out of usage data collection, but in the meantime, you can manually disable usage data collection by following the instructions in our [FAQ](https://code.visualstudio.com/Docs/supporting/FAQ#_how-to-disable-telemetry-reporting).
