### ISSUE TITLE
Wrong coloring of else statement for ifdef in Makefile

### ISSUE THREAD

**Issue by foreignmeloman** [microsoft/vscode#109008]
Issue Type: <b>Bug</b>

In this Makefile sample "else" statement gets a wrong color:

```
a := 1
target:
ifdef a
	echo a
else
	echo b
endif
```

Screenshot:
![image](https://user-images.githubusercontent.com/11769352/96580534-797f5500-12e9-11eb-983d-f1acf2d1a0cf.png)

VS Code version: Code - Insiders 1.51.0-insider (13b3c937dc5e3816c79bdd2cdf2cdf6f9c727b75, 2020-10-20T06:07:53.466Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (4.73GB free)|
|Process Argv|--crash-reporter-id b24ee7a9-a4c3-4313-b1c0-661cd65ffc34|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexr00** [comment]
Copied to owning repo: https://github.com/fadeevab/make.tmbundle/issues/10
