### ISSUE TITLE
Search fields follow macOS "Add period with double-space" setting which is unexpected

### ISSUE THREAD

**Issue by pdfowler** [microsoft/vscode#109047]
- VSCode Version: 1.50.0
- OS Version: macOS 10.15.6

#### Steps to Reproduce:

1. Open _System Preferences --> Keyboard --> Text_ and enable "Add period with double-space"
1. In VSCode, open the project search sidebar panel (⇧-⌘-F)
1. Type a normal character (eg: "x"), followed by two spaces

**Result**: The search field reads: `"x."`
**Expected**: The search field reads: `"x  "`

##### Notes:
* This behavior is also observed on `files to include` and `files to exclude` fields, and I suspect elsewhere as well.
* The three other settings adjacent to "add period with double space" ("Correct spelling automatically", "Capitalize words automatically" and "Touch Bar typing suggestions") are ignored as I would expect.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by roblourens** [comment]
I've been searching around, and I can't find a way for us to disable this for native web text inputs.

**Comment by pdfowler** [comment]
Thanks for looking. I'd expect the behavior to fall under the purview of the html input `autocorrect` attribute but my testing shows otherwise. Guess I'll take it up with the black hole that is "Apple Product Feedback"
