### ISSUE TITLE
[TS] Value not shown on first hover

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#10904]
- VSCode Version: Code - Insiders 1.5.0-insider (c4f365235906cd689e55376e44cc106003ac06b3, 2016-08-24T06:04:42.373Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

```ts
let obj = {a:1,b:2}

let test = ()=>{
    console.log(obj)
    debugger
}
test()
```

When hovering `obj` for the first time - value is not being show.
When moving out and hovering again - the value will be shown

![irxuqyl05t](https://cloud.githubusercontent.com/assets/1723815/17941833/fc31733c-6a02-11e6-8498-9260525e3c77.gif)

**Comment by isidorn** [comment]
@wallverb thanks for the great bug descriptions!
