### ISSUE TITLE
Ability to mark all test case as skip and vice-versa

### ISSUE THREAD

**Issue by YashMonetate** [microsoft/vscode#109007]
Issue Type: <b>Feature Request</b>

Hi Team,
First of all, thanks for this wonderfull VS code environment. I love it's feature and working with it.

I am writing to place a request by which we could be able to skip all the test case in one go. 
Use case: In webdriverio, we can define many test case in one describe block. User should be able to skip/unskip all test case by any short-cut key. I know that we can write `describe.skip` but i have a need to run one test case only and others should not run i.e. if we have 100 test in one describe block, i have a need to run 1 test only and other 99 should be skipped. So to achieve this, we have to skip those 99 test manually that is a cumbersome task.

Advantage: while fixing automation script, if there is only one test case that need to be run/debug, then we got to put skip keyword manually to all other test case. Imaging doing this where we have 100 test case in one describe block.

Other possibilities: There could be nested describe blocks. But again we are concerned here for test case that starts with 'it' block. So no matter where 'it' block appears it would be marked as skil/unskip if fall under selected describe block.

```
describe("Bug", () => {
    it("", () => {
    });
    it("second", () => {
    });
    it("", () => {
    });
    it("", () => {
    });
    it("", () => {
    });
    it("", () => {
    });
    it("", () => {
    });
});
```

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

**Comment by weinand** [comment]
In mocha it is possible to use `.only()` to run only a single test from a test suite.
Did you try this?

**Comment by weinand** [comment]
Since the requested functionality depends heavily on the used testing framework, I do not see us implementing this feature in VS Code generically.

**Comment by YashMonetate** [comment]
@weinand Thanks for highlighting. I placed this request keeping in mind that VS code is able to format my code by shift+ctrl+f irrespective of which language/framework is used as obviously each language/framework has different way of writing a function or class etc. so i thought it is possible to identify a test irrespective of used framework.

**Comment by weinand** [comment]
VS Code delegates all language specific functionality (e.g. formatting) to (mostly third-party) extensions.
Your feature request would fall into that category too.

Please check out this extension: https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer
Maybe it supports already what you are asking for.
