### ISSUE TITLE
File Upload still works when "explorer.enableDragAndDrop" is false

### ISSUE THREAD

**Issue by mklechan** [microsoft/vscode#109057]
- VSCode Version: 1.49.3
- OS Version: Mac OS

Steps to Reproduce:

1. In settings set "explorer.enableDragAndDrop" to false
2. Drag file from Mac File Explorer to Editor Window
3. Note the file can now be edited and saved to remote or local machine

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
That setting only affects drag and drop from within the explorer.
I understand the setting name might be confusing.
And that it might also disable drag and drop from desktop to vscode.

However for now leaving this open to get more user feedback.

**Comment by mklechan** [comment]
Hi @isidorn , thanks.  Is there a setting to disable file upload and download from the Desktop to VSCode?
If not could you point me to the module that handles this? That way i can understand if  i could do this myself.

**Comment by isidorn** [comment]
No, there is no setting for this.
Here's the code that handles this https://github.com/microsoft/vscode/blob/9eaeb4db68efee5b9650fc1cc63f9128f80437a6/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L816

I think the change should be simple, I am not sure if it would cause user backlash. So a clean PR is probably welcome.

fyi @bpasero since he originaly introduced the `enableDragAndDrop` setting

**Comment by bpasero** [comment]
The original intent of `enableDragAndDrop` setting was really to prevent accident changes in the explorer when you drag-and-move in the explorer. It has nothing to do with uploading from the desktop. I would not change anything here.

**Comment by isidorn** [comment]
Makes sense. 
Then the only thing we could do is improve the setting description.

**Comment by isidorn** [comment]
As discussed I have only pushed a clarification of the setting.
No further changes are planned thus closing this.

**Comment by mklechan** [comment]
@isidorn I was able to stop file uploads by setting MAX_FILE_UPLOAD_SIZE to 0
with `enableDragAndDrop` set to false I can stop uploads to both the Editor and the Explorer.

But I can still download files from VSCode to my Mac by dragging and dropping.  Is there a better place in the code to stop this?
I was looking at: https://github.com/microsoft/vscode/blob/776541c380657f8e1bf9f4acc459a33d84f755bd/src/vs/platform/download/common/downloadService.ts#L22
But that doesnt seem to work

Thanks

**Comment by isidorn** [comment]
@mklechan we do not have plans to change this at the moment, so even if you create a PR, we would probably not merge this in.
As for the code pointer, here is where the drop is handled 
https://github.com/microsoft/vscode/blob/7536644522b156e7f24d638dd4faf31477456a40/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L986
