### ISSUE TITLE
Git branch detection when refreshing network folder

### ISSUE THREAD

**Issue by jzombie** [microsoft/vscode#109016]
When refreshing the source tree filesystem directory on a networked location (in my case SSHFS), I think the current git branch should reflect if it was changed outside of VSCode when pulling latest directory tree updates.

i.e. If I'm on develop, and I switch to master using CLI, even though the code inside of VSCode renders what's in the master branch, it will still be labeled as develop in this label, which is a bit confusing.

I realize that I can change branches directly in VSCode, but I'm not working 100% within it at all times, either.

![vscode-feature-request](https://user-images.githubusercontent.com/1139657/96595666-ebd84100-12b9-11eb-8639-5e37519a4c0d.png)

**Comment by joaomoreno** [comment]
If you go into the SCM view and hit refresh there, it will refresh the SCM state. The fact that this isn't working automatically is very likely due to the fact that you're missing file events on that file system.
