### ISSUE TITLE
Using nodemon / webpack --watch, Command for terminating a named task in postDebugTask

### ISSUE THREAD

**Issue by grbd** [microsoft/vscode#109091]
Hi,
So I've been trying to use nodemon and webpack --watch both together at the same time
I've had some success at this, but what I'd like to request
is if there's a command for killing a specific launched task from a postDebugTask

So as an example:

launch.json section
```
    {
      "name": "Server Debug - Nodemon",
      "runtimeExecutable": "yarn",
      "runtimeArgs": ["nodemon"],
      "restart": true,
      "program": "${workspaceFolder}/src/index.ts",
      "cwd": "${workspaceFolder}",
      "args": [],
      "request": "launch",
      "type": "pwa-node",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "outFiles": [
        "${workspaceFolder}/build/**/*.js"
      ],
      "sourceMaps": true,
      "preLaunchTask": "build:dev:watch",
      "postDebugTask": "postdebugKill"
    },
```

tasks.json section
```
    {
      "label": "build:dev:watch",
      "type": "npm",
      "script": "build:dev:watch",
      "group": "build",
      "isBackground": true,
      "problemMatcher": {
        "pattern": {
          "regexp": "^ERROR in",
        },
        "background": {
          "activeOnStart": true,
          "beginsPattern": "\\Compilation  starting…",
          "endsPattern": "\\[webpack-cli\\] watching files for updates...",
        }
      }
    },
    {
      "label": "postdebugKill",
      "type": "process",
      "command":[
          "${command:workbench.action.tasks.terminate}",
          "${command:workbench.action.acceptSelectedQuickOpenItem}",
      ],
    },
```

package.json section
```
  "scripts": {
    "build:dev:watch": "NODE_ENV=development webpack --watch",
  },
```

This mostly works, but keeps the webpack task open after debugging stops
Ideally I'd like to know if there's a specific command for killing the "build:dev:watch" named task within the "postdebugKill" task
I tried the workbench terminate commands above as suggested in the stackoverflow but this didn't seem to work anyway

There's some related issues I found but didn't give me any clues to do this

  * https://github.com/microsoft/vscode/issues/6209
  * https://github.com/microsoft/vscode/issues/65288
  * https://github.com/microsoft/vscode/issues/24779
  * https://stackoverflow.com/questions/54480792/terminate-another-task-from-within-a-postdebugtask-vs-code

**Comment by grbd** [comment]
Just to add for anyone else looking at doing something similar
I've found using the Task Explorer extention to be a big help, although the above would still be useful

  * https://github.com/spmeesseman/vscode-taskexplorer

**Comment by isidorn** [comment]
Let's keep this open for the community to answer.
