### ISSUE TITLE
Debugging Diagnostics

### ISSUE THREAD

**Issue by OOBELOCAL** [microsoft/vscode#109065]
Issue Type: <b>Bug</b>

- Publishing to Github.
- Trying Profiling.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.37.1
xml|Dot|2.5.1
vscode-firefox-debug|fir|2.9.1
cloudcode|goo|1.6.1
file-downloader|min|1.0.5
mindaro|min|1.0.120201007
vscode-docker|ms-|1.7.0
vscode-aks-tools|ms-|0.0.7
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.9.114305
remote-containers|ms-|0.145.1
remote-wsl|ms-|0.50.1
azure-account|ms-|0.9.3
powershell|ms-|2020.6.0
vscode-yaml|red|0.11.1

</details>

**Comment by weinand** [comment]
Please provide details for what you are asking for.
