### ISSUE TITLE
It always says add   path to interpreter

### ISSUE THREAD

**Issue by smartgamer1280** [microsoft/vscode#109080]
Issue Type: <b>Bug</b>

It doesnt work help me =>>I always add and the path and then on the next restart it always says that add interpreter in visual studio code

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.95GB free)|
|Process Argv|--crash-reporter-id fdd4a875-b1eb-4ab4-a52d-f449a98f48bf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.3
code-runner|for|0.11.1
python|ms-|2020.9.114305
vscode-pylance|ms-|2020.10.1

</details>

**Comment by Tyriar** [comment]
This is an extension issue, you should report it to whatever extension uses the interpreter that it's complaining about.

**Comment by smartgamer1280** [comment]
> This is an extension issue, you should report it to whatever extension uses the interpreter that it's complaining about.

Thanks bro I have reported lets see what happens
