### ISSUE TITLE
Unable to intall plugin

### ISSUE THREAD

**Issue by ankur-manocha** [microsoft/vscode#109059]
Run below command in terminal:
ensure you have -salesforce extension pack installed already

PS C:\Users\A.Manocha\VSCode-GIT\BAUDEV\BAUDEV> sfdx plugins:install @salesforce/sfdx-diff
    Error: tunneling socket could not be established, cause=write EPROTO 21008:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

    Code: ECONNRESET

**Comment by sandy081** [comment]
Seems sdfx command is from salesforce, please file issue against salesforce.
