### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by sharmayogesh123** [microsoft/vscode#109033]
Issue Type: <b>Bug</b>

net::ERR_PROXY_CONNECTION_FAILED

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.79GB free)|
|Process Argv|--crash-reporter-id 2d03cebe-0d89-41f5-a21f-162fc3076f63|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
go-to-method|tri|0.2.0
current-file-path|Yos|2.0.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/34385
