### ISSUE TITLE
ERROR:browser_main_loop.cc(217)

### ISSUE THREAD

**Issue by mong87suk** [Microsoft/vscode#10905]
- VSCode Version: 1.5.0
- OS Version: Raspbian GNU/Linux 8.0 (jessie)

Steps to Reproduce:

1. I installed  VS code on raspberry pi

2. When I tried run it. so following error happened.

3.  I've tried this way : [Linux SUID Sandbox Development](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md)

Run following line.
pi@KERNEL_BZ:/usr/lib/chromium-browser $ ls
chrome-sandbox
pi@KERNEL_BZ:sudo mkdir /usr/local/sbin/chrome-devel-sandbox
pi@KERNEL_BZ:cp chrome-sandbox /usr/local/sbin/chrome-devel-sandbox
pi@KERNEL_BZ:sudo chown root:root /usr/local/sbin/chrome-devel-sandox
pi@KERNEL_BZ:shdo chmod 4775 /usr/local/sbin/chrome-devel-sandbox

Put this line in may ~/.bashrc
export CHMOE_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox

I've tried to fix but I couldn't fix this error.
Please review my error and fix it.

Thanks,
Felinus Jeong

pi@KERNEL_BZ:~/Development/vscode/scripts $ ./code.sh 
[2396:0825/023731:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.

**Comment by joaomoreno** [comment]
If Code runs in ARM, great, but we're not actively supporting it.

**Comment by mong87suk** [comment]
Hello, @joaomoreno 
Thank you for your support.
I really want to fix it. 
Could you give me some hint to fix it?

Best regards,
Felinus Jeong

**Comment by joaomoreno** [comment]
You might want to follow #10923
