### ISSUE TITLE
URL: Allow `file://` URLs in hovers to escape to the OS

### ISSUE THREAD

**Issue by zacps** [microsoft/vscode#109039]
Currently markdown hovers or completion popups can contain clickable links. [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) has recently started resolving links in documentation to point at their hosted documentation. However, the program which generates documentation for Rust can also create local documentation files (html).

We want the user to be able to chose whether these links resolve to hosted documentation or local documentation. Unfortunately, when a hover contains a `file://` URL it is intercepted by vs code and not opened in a browser.

A simple way to resolve this would be to add handling for a specific scheme, for example `extfile://`, which rewrites to `file://` and defers to the OS.

**Comment by zacps** [comment]
I've described a possible workaround using command URLs [here](https://github.com/rust-analyzer/rust-analyzer/issues/6332#issuecomment-714900956)

**Comment by joaomoreno** [comment]
I'm not sure I completely understand the feature request.

What do you want to happen exactly, when the user clicks the link?

**Comment by zacps** [comment]
I want the `file` URL to be opened in whatever application the system has bound for that URL. In the case of an HTML file this is *likely* a browser.
