### ISSUE TITLE
MarkdownString.appendText doesn't escape quote

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#109040]
```ts
provideHover(document, position, token) {
    const markdown = new MarkdownString(undefined, true);
    markdown.isTrusted = true;
    markdown.appendText('> Text');
    return new vscode.Hover(markdown);
}
```
Expected: Rendered text `> Text`
Actual: Rendered a block quote `Text` with a lot of padding.

**Comment by jppm99** [comment]
I believe that is the [expected behaviour](https://www.markdownguide.org/basic-syntax/#blockquotes-1).

**Comment by usernamehw** [comment]
@jppm99 appendText function is to add text `as-is`. Not as markdown.

**Comment by jppm99** [comment]
True, my bad.

**Comment by amaust** [comment]
Hello, I believe I may have a fix. Would you mind giving me a little more information on how to reproduce the bug? @usernamehw

**Comment by usernamehw** [comment]
Create a hover provider in extension:

```ts
vscode.languages.registerHoverProvider(
    { scheme: 'file' },
    {
        provideHover(document, position, token) {
            const markdown = new MarkdownString(undefined, true);
            markdown.isTrusted = true;
            markdown.appendText('> Text');
            return new vscode.Hover(markdown);
        },
    },
);
```

**Comment by amaust** [comment]
Alright thanks @usernamehw, Ill give that a shot and if it works ill submit the PR

**Comment by amaust** [comment]
Hi @jrieken, I thought I had a fix to the problem but what I assumed would work doesnt seem to be the case and I was wondering if you wouldn't mind guiding me in the right direction/tell me if there is something that I am missing.

I feel like the issue most likely lies in the htmlContent.ts file located in the vs base common files and more specifically I thought that adding `>` to the regex expression would correct the issue but that doenst seem to be the case. Do you have any advice you can give me/
`	appendText(value: string): MarkdownString {
		// escape markdown syntax tokens: http://daringfireball.net/projects/markdown/syntax#backslash
		this._value += (this._supportThemeIcons ? escapeCodicons(value) : value)
			.replace(/[\\`*_{}[\]()#+\-.!]/g, '\\$&')
			.replace(/\n/g, '\n\n');

		return this;
	}`

**Comment by jrieken** [comment]
Sorry for the late investigation but it turns out that this isn't bug after all. Lines starting `>` are quotations and that's correctly rendered. 

> Actual: Rendered a block quote Text with a lot of padding.

What might be missing is the nicer style as GH does it. However, having other angle brackets inside text works as designed.

<img width="374" alt="Screenshot 2020-11-03 at 10 56 10" src="https://user-images.githubusercontent.com/1794099/97971515-76916380-1dc3-11eb-8988-11af45f0fc7a.png">

**Comment by usernamehw** [comment]
@jrieken I don't understand this function then

```ts
const markdown = new MarkdownString(undefined, true);
markdown.appendMarkdown('**bold** `code` *italic*\n\n');// ✅
markdown.appendText('**NOT bold** `NOT code` *NOT italic*\n');// ✅
markdown.appendMarkdown('> quote\n\n');// ✅
markdown.appendText('> should NOT be a quote');// ❌
return new vscode.Hover(markdown);
```

**Comment by jrieken** [comment]
You are so right 🤦 Sorry, I was confused.
