### ISSUE TITLE
scripts/code.sh broken since 1.50.0

### ISSUE THREAD

**Issue by dcermak** [microsoft/vscode#109005]
- VSCode Version: 1.49 and 1.50
- OS Version: opensuse Tumbleweed

Steps to Reproduce:

1. clone the vscode git repository, checkout any of the `1.49.*` tags
2. run `./scripts/code.sh` and verify that it works
3. check out either `1.50.0` or `1.50.1`
4. run `./scripts/code.sh`, which fails for me with:
```ShellSession
$ ./scripts/code.sh
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/home/dan/packages/github.com/microsoft/vscode/build/lib/preLaunch.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
Note that the file `/home/dan/packages/github.com/microsoft/vscode/build/lib/preLaunch.js` does not exist, only its typescript source exists. So maybe a compilation step is missing there?

Does this issue occur when all extensions are disabled?: irrelevant

**Comment by dcermak** [comment]
Indeed, running `yarn install` and `yarn run compile` before `./scripts/code.sh` fixes the issue for me.

**Comment by weinand** [comment]
Yes, you need to build before trying to run VS Code.
For details see: https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites
