### ISSUE TITLE
Workspace settings not taking precedence over user settings

### ISSUE THREAD

**Issue by svillar** [microsoft/vscode#109020]
I have formatOnSave enabled in my user settings but disabled in a particular workspace. However everytime I save a file the file is formatted anyway. What's worst, the "modifications" option is enabled in user settings but the formatting is applied to the whole file.

**Comment by roblourens** [comment]
> but disabled in a particular workspace

Can you check that the setting is actually disabled in your workspace settings.json? It needs to be configured like that to override the user settings.json
