### ISSUE TITLE
Codespaces - Private Repos and Codespaces: Enable Submodule Cloning

### ISSUE THREAD

**Issue by Coda-Coda** [microsoft/vscode#109050]
- VSCode Version: GitHub Codespaces
- OS Version: n/a

Steps to Reproduce:

1. Open a private repo in Codespaces with submodules that are private repositories, with `Codespaces: Enable Submodule Cloning` enabled.
2. Note that the submodules did not clone successfully.
3. Try `git submodule update --init --recursive`.
4. Note the error: `remote: Repository not found.`

Possibly related to:
https://github.com/microsoft/vscode/issues/101147
and
https://github.community/t/how-to-checkout-recursively/136734

Does this issue occur when all extensions are disabled?: I think so (codespaces)

**Comment by Coda-Coda** [comment]
_Workaround_: install a separate version of git, `git submodule update --init --recursive` will then prompt you for your password. This is not ideal.

**Comment by joaomoreno** [comment]
Closing per https://github.community/t/how-to-checkout-recursively/136734/5:

>  That setting in VS Code is only supported in Visual Studio Codespaces and is not currently implemented for GitHub Codespaces.

**Comment by Coda-Coda** [comment]
@joaomoreno Thanks, I see that thread has been updated with useful information. Please consider adding submodule cloning of private repos to the backlog too, if it is not already on there.

Thanks for the awesome work being done on Codespaces!
