### ISSUE TITLE
Alt+shift+f doesn't work

### ISSUE THREAD

**Issue by lpintes** [microsoft/vscode#109072]
Issue Type: <b>Bug</b>

I tested this using Golang and Elm extensions. When i press the alt+shift+f keyboard shortcut, the folliwing nonsense appears on status line:

```
Info: Extension 'PKief.material-icon-theme' is configured as formatter but not available. Select a different default formatter to continue.
```

VS Code version: Code - Insiders 1.51.0-insider (13b3c937dc5e3816c79bdd2cdf2cdf6f9c727b75, 2020-10-20T06:07:53.466Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.58GB (3.27GB free)|
|Process Argv|. --crash-reporter-id 3229a6ba-f91c-4af0-945c-d57b1e4677fb|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
EditorConfig|Edi|0.15.1
elm-ls-vscode|elm|1.5.2
go|gol|0.17.2
rest-client|hum|0.24.3
goto-next-previous-member|mis|0.0.5
python|ms-|2020.9.114305
remote-containers|ms-|0.145.1
remote-wsl|ms-|0.51.0
debugger-for-chrome|msj|4.12.11

</details>

**Comment by gjsjohnmurray** [comment]
Does this only appear on the status line? Don't you also get a notification appearing in the lower right corner?

**Comment by IllusionMH** [comment]
/needsMoreInfo

> Extension 'PKief.material-icon-theme' is configured as formatter

This looks really wrong. Do you have `"editor.defaultFormatter"` somewhere in you user or workspace configurations?

**Comment by lpintes** [comment]
Hi robot or who you are.

I used an issue reporter from the help menu. If you think there is 
missing something, please fix the report issue feature.


Dňa 21. 10. 2020 o 16:00 VS Code Issue Triage Bot napísal(a):

**Comment by lpintes** [comment]
I am not sure, I am a screen reader user.

I tried to find the way to copy the message exactly and command line 
immediately came to mind.


Dňa 21. 10. 2020 o 15:23 John Murray napísal(a):

**Comment by lpintes** [comment]
Hello I think there is no such setting. I never tried to set this manually.


Also I looked into the settings editor and the editor default formatter 
is null.

**Comment by IllusionMH** [comment]
> Hi robot or who you are.

Bot was triggered by me as follow up to questions about `"editor.defaultFormatter"` configuration.

---

I was able to reproduce this error (shown as notification) only with `"editor.defaultFormatter": "123"` in my configuration.
> Extension '123' is configured as formatter but not available. Select a different default formatter to continue.

Settings UI will show `null` in case when you have language specific setting, so it's better to check in `settigngs.json`.

Could you please check if you have `editor.defaultFormatter` or `PKief.material-icon-theme` when you open JSON file using `>Preferences: Open Settings (JSON)` for user settings and `>Preferences: Open Workspace Settings (JSON)` for workspace specific settings?

**Comment by lpintes** [comment]
Hello,

Indeed in my settings.json I have the line:

"editor.defaultFormatter": "PKief.material-icon-theme",
Interesting, I am sure I never modified settings.json manually.
So this can be closed. After fixing settings.json alt+shift+f seems to 
work again.
