### ISSUE TITLE
Colorization of large cpp/h files fails after so many lines

### ISSUE THREAD

**Issue by rchiodo** [Microsoft/vscode#10901]
- VSCode Version: 1.4.0
- OS Version: Windows 10 RS1

Steps to Reproduce:

1.  Open file C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h
2.  Colorization stops at about line 612 for me

![image](https://cloud.githubusercontent.com/assets/19672699/17938187/c22b4a92-69d9-11e6-927f-f5b030fc71c7.png)

**Comment by sandy081** [comment]
This issue was moved to Microsoft/vscppsamples#167

**Comment by rchiodo** [comment]
Not sure why this was moved? Colorization is handled by vscode's textmate bundles as far as I know.

**Comment by angrah** [comment]
This is an example of json coloring:
`
{
	"a": {
		"b": {
			"c": {
				"d": {
					"e": {
						"f": {
							"g": {
								"h": {
									"i": {
										"j": {
											"k": {
												"l": {
													"m": {
														"n": {
															"o": {
																"p": "test"
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
`
Line "p" and every line below it is not colored.
