### ISSUE TITLE
Latest version of VSCode Insiders crashed on macOS Catalina

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode#109066]
- VSCode Version: 1.50.0 and 1.51.0
- OS Version: 10.15.7

Steps to Reproduce:

1. Download that latest from the site.
2. Drag and drop on Applications folder under the second disk (HDD), .i.e, `/Volumes/Second_HDD/Users/gusbe/Applications/`;
3. Open VSCode.
4. Install Python.
5. Close VSCode.
6. Open VSCode.
7. It crashed. 

I reverted to 1.50.0, but it also crashed. 

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by deepak1556** [comment]
> 4. Install Python.

Does this step refer to installing python extension ? Does the crash happen when you skip this step ?

Can you share the log when running `code --verbose`
