### ISSUE TITLE
[bot] Show dev message even for closed issues

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#109087]
There's a text telling people to ask dev questions in slack channel. But the issue is often closed before label is added and there is no bot message in that case: https://github.com/microsoft/vscode/issues/109031

It happens https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aclosed+label%3A*dev-question

**Comment by JacksonKearl** [comment]
It's an explicit decision to not comment if the issue was closed then the label was added, as we try to add a more specific comment ourselves if we close it manually. In the link you give Joh gave more info than the slack would give.

**Comment by usernamehw** [comment]
Ok.

**Comment by usernamehw** [comment]
@JacksonKearl maybe the link to slack should also be present in README file? 

https://github.com/microsoft/vscode#feedback

**Comment by JacksonKearl** [comment]
Added some more info to the readme liking to the wiki's feedback section

**Comment by usernamehw** [comment]
I didn't know there's a wiki with feedback channels. I think that commit now referencing the same page.

You probably meant https://github.com/microsoft/vscode/wiki/Feedback-Channels

**Comment by JacksonKearl** [comment]
Oops my bad :) thanks
