### ISSUE TITLE
WordPart navigation in Rename popup input instead navigates in editor

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#109021]
Version: 1.50.0 (user setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

This is not a regression in latest version, it has always worked this way.

Steps to Reproduce:

1. add this key binding to `keybindings.json`
```

{ "key": "alt+left",              "command": "-workbench.action.navigateBack"     },
{ "key": "alt+right",             "command": "-workbench.action.navigateForward"  },

{ "key": "shift+alt+left",        "command": "-editor.action.smartSelect.shrink", },
{ "key": "shift+alt+right",       "command": "-editor.action.smartSelect.grow",   },

{ "key": "alt+left",              "command": "cursorWordPartStartLeft",           },
{ "key": "shift+alt+left",        "command": "cursorWordPartStartLeftSelect",     },
{ "key": "alt+right",             "command": "cursorWordPartRight",               },
{ "key": "shift+alt+right",       "command": "cursorWordPartRightSelect",         },

```

2. click on a variable name and invoke F2 Rename popup input
3. this will select text under popup <kbd>alt</kbd><kbd>←</kbd>, <kbd>alt</kbd><kbd>→</kbd>, <kbd>alt</kbd><kbd>shift</kbd><kbd>←</kbd>, <kbd>alt</kbd><kbd>shift</kbd><kbd>→</kbd>
4. this works as expected <kbd>←</kbd>, <kbd>→</kbd>, <kbd>shift</kbd><kbd>←</kbd>, <kbd>shift</kbd><kbd>→</kbd>
5. this works as expected <kbd>ctrl</kbd><kbd>←</kbd>, <kbd>ctrl</kbd><kbd>→</kbd>, <kbd>ctrl</kbd><kbd>shift</kbd><kbd>←</kbd>, <kbd>ctrl</kbd><kbd>shift</kbd><kbd>→</kbd>

In step 2), instead of manipulating with cursor in the Rename popup, original text in the editor will get highlighted at word part stops.

Verify that the keybinding actually works with normal text:
![vscode-cursorWordPart2](https://user-images.githubusercontent.com/2313018/96602667-8a34c880-12f3-11eb-8d09-85d8b5a8f8e7.gif)

Keybinding will not work as expected with popup Rename input, notice WordPart highlights in editor.
![vscode-cursorWordPart1](https://user-images.githubusercontent.com/2313018/96602657-87d26e80-12f3-11eb-8707-bf17f4d71fbf.gif)
Other key combinations work as expected.
![vscode-cursorWordPart3](https://user-images.githubusercontent.com/2313018/96602679-8d2fb900-12f3-11eb-9cd5-368ef0e2707a.gif)

I have removed `"when": "textInputFocus"` on last moment for simplicity as the effect is, to my surprise, the same.

```
// default keybinding for inspiration
{ "key": "ctrl+left", "command": "cursorWordLeft",          "when": "textInputFocus" }
{ "key": "alt+left",  "command": "cursorWordPartStartLeft", "when": "textInputFocus" }
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
The root problem is with the keybindings. You must use `"when": "textInputFocus"`, otherwise they will always execute in the last active editor, even if it is not focused. So the solution is:
```
{ "key": "alt+left",              "command": "-workbench.action.navigateBack",    "when": "textInputFocus" },
{ "key": "alt+right",             "command": "-workbench.action.navigateForward", "when": "textInputFocus" },

{ "key": "shift+alt+left",        "command": "-editor.action.smartSelect.shrink", "when": "textInputFocus" },
{ "key": "shift+alt+right",       "command": "-editor.action.smartSelect.grow",   "when": "textInputFocus" },

{ "key": "alt+left",              "command": "cursorWordPartStartLeft",           "when": "textInputFocus" },
{ "key": "shift+alt+left",        "command": "cursorWordPartStartLeftSelect",     "when": "textInputFocus" },
{ "key": "alt+right",             "command": "cursorWordPartRight",               "when": "textInputFocus" },
{ "key": "shift+alt+right",       "command": "cursorWordPartRightSelect",         "when": "textInputFocus" },
```

**Comment by ackvf** [comment]
@alexdima Oh yeah, I know. I only removed it here, because the line was too long for the github code snippet.
It doesn't work with it.

> I have removed `"when": "textInputFocus"` on last moment for simplicity as the effect is, to my surprise, the same.
