### ISSUE TITLE
SSH Terminal

### ISSUE THREAD

**Issue by itsunaev** [microsoft/vscode#109089]
Issue Type: <b>Bug</b>

SSH to remote never opens in terminal window (status is "Starting..." permanently)

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.3.9600
Remote OS version: Linux arm 4.13.15-sunxi

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (3.99GB free)|
|Process Argv|--crash-reporter-id 4e5f8b9a-8144-4ca0-afb5-b7c804b5b4ae|
|Screen Reader|no|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: 10.134.10.132|
|OS|Linux arm 4.13.15-sunxi|
|CPUs|ARMv7 Processor rev 5 (v7l) (4 x 1200)|
|Memory (System)|0.48GB (0.13GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0

</details>

**Comment by itsunaev** [comment]
JFYI verified on August release it is working.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/2313

**Comment by AmericanY** [comment]
@Tyriar i do have the same issue. i followed up the link which you mentioned but i couldn't figure out any solution for it?

**Comment by Tyriar** [comment]
There is no solution, it's an open bug

**Comment by AmericanY** [comment]
@Tyriar after trying vscode recent update. the issue fixed but the remote terminal is completely slow and connection keep drop.
