### ISSUE TITLE
Not Getting html suggestions

### ISSUE THREAD

**Issue by dheerajsingh2016d** [microsoft/vscode#109090]
Issue Type: <b>Feature Request</b>

i have enabled a html css extension but not getting suggestions in visual studio code  even after restarting, what should i do?

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:57:08.739Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by aeschli** [comment]
VSCode ships with HTML support out of the box.
Create a HTML file, enter `<` and do code complete (Ctrl + Space) to see suggestions for tags.

Please add a code sample and describe what you see and what you expect.
Also note that issues against other extension must go directly against the repo of these extension
