### ISSUE TITLE
VS Code extension activates twice when launched in debug mode

### ISSUE THREAD

**Issue by kittaakos** [microsoft/vscode#109014]
Hi there, I can see that my VS Code extensions' `activate` function is called twice when I launch them in debug mode from VS Code. I was sure there is a bug in my code, so I ended up cloning, building and running the [`fsprovider-sample`](https://github.com/microsoft/vscode-extension-samples/tree/master/fsprovider-sample). When I activate the MemFS extension with the `MemFS: Setup Workspace` command, I can see this is the debug console.

```
MemFS says "Hello"
 extension.js
MemFS says "Hello"
 extension.js
```

Is this the expected behavior? I am using `1.50.1`. Thank you!

- VSCode Version: `1.50.1`
- OS Version: macOS 10.15.6 (19G2021)

Steps to reproduce:
```
rm -rf ./tmp-vscode-extension-samples \
&& git clone --depth 1 https://github.com/microsoft/vscode-extension-samples.git ./tmp-vscode-extension-samples \
&& cd tmp-vscode-extension-samples/fsprovider-sample \
&& npm i \
&& code .
```
 - Launch your extension in debug mode with <kbd>F5</kbd>,
 - <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> > `MemFS: Setup Workspace`,
 - Check the _Debug Console_, `MemFS says "Hello"` is there twice.
 - (You can also put a breakpoint in the `activate` method and see that you will hit it twice.)

Does this issue occur when all extensions are disabled?: Yes/No

----
(I have [cross-posted](https://gitter.im/Microsoft/vscode?at=5f8ee315c990bb1c391da2a4) the same question on VS Code Gitter.)

**Comment by weinand** [comment]
I cannot reproduce this issue with the "hello world" extension, so this issue is not a general issue of VS Code.

I suspect that the "MemFS: Setup Workspace" action reloads the extension host which will result in a second activation.

If my assuption is correct, you should see a call to the "deactivate" function of your extension before the second "activate" occurs.

**Comment by kittaakos** [comment]
> If my assuption is correct, you should see a call to the "deactivate" function of your extension before the second "activate" occurs.

Thank you for your reply, I am going to try this and update this thread.

**Comment by kittaakos** [comment]
> I cannot reproduce this issue with the "hello world" extension

I can confirm.

> "MemFS: Setup Workspace" action restarts the extension host process (where your extension is running). This will result in another activation of your extension (after properly deactivating the first).

This seems to be an incorrect assumption. I can clearly see, the MemFS extension module is loaded and `activate` called twice, `deactivate` is not called. Have you had the chance to try with the `fsprovider-sample`?

I am going to check if this is a file-system provider-specific issue or not. My extension also has an `onFileSystem:scheme` activation event. Just guessing, though.

**Comment by jrieken** [comment]
That's because you go through `MemFS: Setup Workspace`. That will restart the extension host and re-activate all extensions that have been active. The deactivate call cannot be to debugged afaik because we don't wait for, a console.log-statement should work tho.

**Comment by kittaakos** [comment]
Thank you!

> That will restart the extension host and re-activate all extensions that have been active.

I should have read the docs: 
https://github.com/microsoft/vscode/blob/6c8c6008ef9d86e46b086a00f273b1fee5bd8c51/src/vs/vscode.d.ts#L9867-L9869

> a console.log-statement should work tho.

It does not.
