### ISSUE TITLE
Colorization fails at 9 nested JavaScript functions

### ISSUE THREAD

**Issue by davidcapatch** [Microsoft/vscode#10908]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Open a blank .js file
2. Create 9 nested functions following this format
```
var foo1 = function() {
    var foo2 = function() {
        ...
    }
};
```
3. Colorization stops a 9th function

Issue does not occur using this function format:
function foo1() {};

See screenshot
![screen shot 2016-08-24 at 2 25 48 pm](https://cloud.githubusercontent.com/assets/18700676/17942894/4bcf4a82-6a07-11e6-8009-888b4ee4ee30.png)

**Comment by waderyan** [comment]
@alexandrudima we've seen this before right? I can't find the issue now but I remember seeing something similar. There was a constant we set for when we would stop colorizing. Can you remember this issue? Maybe it was someone else on the team.

**Comment by alexandrudima** [comment]
@waderyan yes, we have similar issues. I opt not to collapse them until we find the root cause in each of them.

**Comment by alexandrudima** [comment]
From debugging, each nested level increases the rule stack by 4 elements. Rule stack length at the end of each line:

```javascript
/*01 -  5 */var foo1 = function() {
/*02 -  9 */    var foo2 = function() {
/*03 - 13 */        var foo3 = function() {
/*04 - 17 */            var foo4 = function() {
/*05 - 21 */                var foo5 = function() {
/*06 - 25 */                    var foo6 = function() {
/*07 - 29 */                        var foo7 = function() {
/*08 - 33 */                            var foo8 = function() {
/*09 - 37 */                                var foo9 = function() {
/*10 - 41 */                                    var foo10 = function() {
/*11 - 45 */                                        var foo11 = function() {
/*12 - 41 */                                        };
/*13 - 37 */                                    };
/*14 - 33 */                                };
/*15 - 29 */                            };
/*16 - 25 */                        };
/*17 - 21 */                    };
/*18 - 17 */                };
/*19 - 13 */            };
/*20 -  9 */        };
/*21 -  5 */    };
/*22 -  1 */};
/*23 -  1 */
```

**Comment by alexandrudima** [comment]
Let's track in #9937
