### ISSUE TITLE
Allow horizontal scrolling WITH word wrapping enabled!

### ISSUE THREAD

**Issue by Servail** [microsoft/vscode#109051]
When working with files with deep intendations, it's very useful if scope/block is placed near the left side of viewport, which is kind of standard behaviour without word wrapping (if even it smart-autoscrolls horizontally to indentation level of selected line...). Word wrapping is also very useful feature, but as soon you enable it, you're sticked to the first column and forced to watch all the indentations and actually work in a small portion of viewport. Why it didn't allow to scroll to the real last column or whatever, while still wrapping to viewport? Isn't word wrapping virtual?
I thought editor.wordWrap = bounded with editor.wordWrapColumn = 1000 will enable this kind of behaviour. But they're not! What's the point in "bounded" then? Just to fit some guide while outsizing viewport? Bruh. 
Maybe I do something wrong or can't find the right extension (and I've searched a lot)?

**Comment by alexdima** [comment]
@Servail I don't understand what you want. A clarification of what we have:
- `editor.wordWrap: off`: no wrapping
- `editor.wordWrap: on`: wrapping at `viewportColumn` (value depends on the width of your editor)
- `editor.wordWrap: wordWrapColumn`: wrapping at the setting `editor.wordWrapColumn` (value configured in settings)
- `editor.wordWrap: bounded`: wrapping at `min(viewportColumn, editor.wordWrapColumn)`.

What kind of behavior are you looking for and can you please provide an example of an application that has it?

**Comment by Servail** [comment]
@alexdima I want wordWrap: on, but alongside with horizontal scrollbar like with wordWrap: off. So when I scroll that scrollbar, first column hides behind the left side of viewport (as with wordWrap: off) and wrapped words dynamically unwrap (like when outsizing editor width with wordWrap:on) to original single line (which length+scrollBeyondLastColumn defines the size of available "virtual" scrolling area). Basically it's dynamic word wrapping based on "virtual" horizontal viewport position. Same as wordWrap: off, but with *elapsed* line endings wrapped around, ideally to min(wrappingIndent, viewportLeftColumn). Sadly, I don't remember any app with this feature (maybe VSCode will be the first?).
P.S.: I quoted "virtual" because I thought the entire wordwrap feature was virtual (or maybe better word - visual) in the first place. Now I doubt, and think that issue originates in electron itself (as there's no horizontal scroll API for extensions), so maybe it's possible to implement vice-versa.
P.S.S.: If it's still not enough... just open VSCode, move window closer to the left side of your display, enable wordwrap and put some long line of text. Now expand the editor a bit by dragging right edge of VSCode window, and then move window to the left outside your display by the same amount. Repeat until text unwrap into a single line (most part of it will be hidden behind the screen, and you'll be able to see only the ending). That's the wrap-scroll feature that I... propose now, I guess? Leaving you with wide, wide window... :----)
