### ISSUE TITLE
Extensions Marketplace not loading

### ISSUE THREAD

**Issue by LargAnk** [microsoft/vscode#109011]
When I try to view the languages to install them, it just says "We cannot connect to the Extensions Marketplace at this time, please try again later." I want to install C++ and Python, but cannot do so because of this bug. When I install them from the Visual Studio Code website, it still shows this message. Please help.
![Capture](https://user-images.githubusercontent.com/66485719/96588713-fb538c00-12b1-11eb-9ea6-64f48768c3c7.PNG)

**Comment by LargAnk** [comment]
![Capture](https://user-images.githubusercontent.com/66485719/96589833-4a4df100-12b3-11eb-97d6-77f208ccc0ff.PNG)

**Comment by sandy081** [comment]
Can you please click on those failed requests and let us know what failures are they?

**Comment by LargAnk** [comment]
(failed) net::ERR_PROXY_CONNECTION_FAILED

**Comment by chrmarti** [comment]
Could you start VS Code with `--log-net-log=netlog.json`, retry the failing feature and then post the created netlog.json here?

**Comment by LargAnk** [comment]
what do you mean by "start vscode with"?

**Comment by chrmarti** [comment]
Close all VS Code windows and on the command line run: `code --log-net-log=netlog.json`.

**Comment by chrmarti** [comment]
@LargAnk The netlog.json should be in the folder you started VS Code from.

**Comment by LargAnk** [comment]
![Capture](https://user-images.githubusercontent.com/66485719/97874767-80459900-1ce7-11eb-9c4b-859afb9b4ee8.PNG)
i opened my c++ folder and ran the command, is this what you are looking for?

**Comment by chrmarti** [comment]
@LargAnk There should be a `netlog.json` file in the folder you started `code --log-net-log=netlog.json` from (the terminal, not VS Code).

**Comment by LargAnk** [comment]
so i do not have vscode open, i open cmd.exe or command prompt, i type code --log-net-log=netlog.json and press enter. it opens vscode. i do not have a vscode folder open. where would it be? or did i use the wrong terminal?
?

**Comment by chrmarti** [comment]
Once the window opens, try searching for extensions to trigger the error. After that check in the terminal you launch from for the netlog.json.

**Comment by LargAnk** [comment]
![Capture](https://user-images.githubusercontent.com/66485719/98013464-64fe8a80-1dc8-11eb-8250-c2053583f52b.PNG)
i don't see it. i also checked in the folder, but i did not find anything. i activated the error.

**Comment by LargAnk** [comment]
should i be looking somewhere else?
