### ISSUE TITLE
highlight the line jumped to

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#109006]
Some time when I use `Ctrl + left click` to jump to variable definition, VSCode will locate to the definition on active editor. For now, the cursor will locate to it's definition position, but I can't find the twinkling cursor quickly. If highlight the line jumped to, It would be helpful.

What's more, this should also be applied to many  other situations which jumping cursor such as go to line(Ctrl + G).

One thing must be pointed is that this highlight should not be keep, it should be keep only short time just like an animation.

**Comment by myfonj** [comment]
Remarks:
- How about setting sufficiently contrasting background for "current line" to locate it more easily [1] in general?
- "Go To Definition" already "blinks" target token (not line), you can set more prominent colour of its highlight [2]

Relevant `settings.json` entries examples:

```JavaScript
"editor.renderLineHighlight": "all", // [1] emphasize current line and line number
"workbench.colorCustomizations": {
	// "[Default Dark+]": {
		// ...
		"editor.lineHighlightBackground": "#0009", // [1] current line slightly darker
		"editor.symbolHighlightBackground": "#f009", // [2] reddish flash of token after "go to definition" 
		"editor.symbolHighlightBorder": "#f02",  // [2] ditto
	// }
```
