### ISSUE TITLE
file explorer mouse/keyboard handling

### ISSUE THREAD

**Issue by hhi** [Microsoft/vscode#10902]
Within the File Explorer, 
when using mouse button, it would be nice to extend with following functionality:
- single click (replaces the file with the clicked one in current tab)
-- double click (opens file but now as an extra tab)
using the keyboard 
- default behavior of enter key is now to rename a file (should be configurable in settings) 
- it would be nice to be able to open the selected file in a current tab with a configurable key config (like command - enter) op to be opened in new tab (by shift-command-enter likewise)

**Comment by sandy081** [comment]
@hhi

I think you would have following setting `workbench.editor.enablePreview` disabled or false. Please enable it and try. I think you will see the requested behavior on single click.
