### ISSUE TITLE
[BUG]: Compiler ARGS not taken over/considered when running build with g++ on Win10

### ISSUE THREAD

**Issue by hasenradball** [microsoft/vscode#109081]
- VSCode Version: 150.1
- OS Version: Win 10.0.18363

Steps to Reproduce:

1. create the "hello world" example from Documentation 
2. change the compiler "args" in tasks.json like an other output name, or change the args to be able to compile multiple files
3. run Task
4. the changes in "args" are not considered!

Hint:
on MAC it works fine on Win10 it does not work!

`
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: g++.exe build active file",
			"command": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\g++.exe",
			"args": ["-g", "${workspaceFolder}\\*.cpp", "-o", "${fileDirname}\\${fileBasenameNoExtension}.exe"],
			"options": {
				"cwd": "${workspaceFolder}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: \"C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\g++.exe\""
		}
	]
}
`

Does this issue occur when all extensions are disabled?:
actually not possible to test

**Comment by hasenradball** [comment]
When using the command on the terminal everything works fine

**Comment by alexr00** [comment]
The task type `cppbuild` comes from an extension. Please file this issue with the extension that provides that task.

**Comment by hasenradball** [comment]
See https://github.com/microsoft/vscode-cpptools/issues/6366
