### ISSUE TITLE
Documentation added as MarkdownString to CompletionItemProvider is not displayed

### ISSUE THREAD

**Issue by ldrahnik** [microsoft/vscode#109031]
- VSCode Version: 1.50.1
- OS Version: Windows_NT x64 10.0.18.363

Steps to Reproduce:

1. register **registerCompletionItemProvider** and return **item.documentation** initialized with **new vscode.MarkdownString('\<p\>Something.\</p>');**
2. and when is completion triggered i see nothing (screen below)

![image](https://user-images.githubusercontent.com/3233644/96618127-d3414880-1304-11eb-9ad0-e463ae2c845c.png)

Does this issue occur when all extensions are disabled? Yes

**Comment by jrieken** [comment]
That's because of the `<p>` tags - those aren't allowed in the `MarkdownString`

**Comment by ldrahnik** [comment]
Thank you for your response. Can you send me where in documentation i can find all allowed syntax? Especially i am focused on how i can do a paragraphs (https://www.markdownguide.org/basic-syntax/#paragraphs-1).

**Comment by jrieken** [comment]
No tags allowed, only markdown syntax

**Comment by ldrahnik** [comment]
I know its a question and it should be somewhere else? Stackoverflow/ Slack? Can you send me Slack link please? Bot probably did not added SLack link to this issue because has been added label after issue was closed.

Question: What would you recommend me to parse HTML to Markdown syntaxe (and what a Markdown syntax is used in Visual Studio Code, Markdown supports a a lot and what everything is here supported?)

Thank you!

Lukas

**Comment by usernamehw** [comment]
Link to slack: https://aka.ms/vscode-dev-community
