### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by AdamAtri** [microsoft/vscode#109024]
Issue Type: <b>Bug</b>

Got a pop up indicating that the typescript service died 5 times

VS Code version: Code 1.49.3 (2af051012b66169dde0c4dfae3f5ef48f787ff69, 2020-10-02T17:54:06.165Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 7|
|Memory (System)|16.00GB (1.11GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.2
vsliveshare|ms-|1.0.3014
debugger-for-chrome|msj|4.12.11
nativescript|Tel|0.11.0
vetur|oct|0.28.0
twig|wha|1.0.2

</details>

**Comment by mjbvz** [comment]
When this happens, there should be a `report issue` button in the notification. This should generate an issue that includes relevant diagnostic information. Do you see this link
