### ISSUE TITLE
Update service shows notifications after resuming laptop

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109063]
<img width="1090" alt="Screenshot 2020-10-21 at 08 48 16" src="https://user-images.githubusercontent.com/1794099/96683258-34573380-137a-11eb-9717-19714e1069f8.png">

Open my laptop this morning and all VS Code windows show this notification...

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/109097
