### ISSUE TITLE
vscode cannot infer typescript type properly

### ISSUE THREAD

**Issue by fredyang** [microsoft/vscode#109029]
- VSCode Version: 1.50.1
- OS Version: Linux x64 5.4.0-51-generic snap 
- typescript version 4.02

Steps to Reproduce:

1. run the type following code in tyepscript playground

https://www.typescriptlang.org/play?ts=4.0.2#code/LAKAZgrgdgxgLgSwPZQARwKYGc4AoGYC2WAXKlBIQEYYBOA2gLoCUqA3qKqgDYZyoEMhANydUAdwAWCXrnxFUAXgFEsAOizSweZqwCEi5dAAmGMAigZjrDiFBiuD1DBRYkvNdyQBzeUOaiIFwAvqChdiCYOLj0AIwANKgAzIkATCzCQA

![image](https://user-images.githubusercontent.com/669555/96616070-1df49d80-12d0-11eb-91e8-6ab6889976f1.png)

typescript playground can infer the item to be a number type

2. do the same thing in vscode

![image](https://user-images.githubusercontent.com/669555/96616378-7deb4400-12d0-11eb-9593-55317d00bf92.png)

vscode cannot infer type.

**exepct vscode can also infer the type as typescript playground does.**

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The playground enables `noImplicitAny` (and a bunch of other flags) by default. `tsc` (and therefore VS Code) does not. Add a tsconfig that matches that from the playground, and the behavior is the same
