### ISSUE TITLE
When running more then one VS Code instance 'CTRL +' should increase the font size only on a active/focused instance

### ISSUE THREAD

**Issue by zeljkoantich** [microsoft/vscode#109086]
Currently when you run 'CTRL +'  to increase the font size, it affects all open VS Code instances.
It would be nice if it would affect only the instance that are active/focused.

**Comment by gjsjohnmurray** [comment]
See #83848 for when this was previously a candidate but didn't receive enough votes.

**Comment by zeljkoantich** [comment]
> See #83848 for when this was previously a candidate but didn't receive enough votes.

Thanks @gjsjohnmurray, but how can I vote for https://github.com/microsoft/vscode/issues/83848 if it's locked and conversation is limited to collaborators.

**Comment by Tyriar** [comment]
@zeljkoantich it was opened for many months and didn't get enough votes to warrant us looking at it (vs the other 5k issues), see the process here: https://github.com/microsoft/vscode/wiki/Issues-Triaging

**Comment by zeljkoantich** [comment]
@Tyriar gotcha, thanks.
