### ISSUE TITLE
Change List for git 

### ISSUE THREAD

**Issue by LiloD** [Microsoft/vscode#10907]
Hi, is there any plan to let user create different change lists for changed files for git
I find this feature is quite useful in intellij

**Comment by joaomoreno** [comment]
Can you elaborate on what those are?

**Comment by LiloD** [comment]
Right now the git in Code is like
CHANGES
 - file1
 - file2
 - file3
 - ...
All change files are under same group 'CHANGES'

I hope user can define different changes list which means user can create different groups
Something like

User Story 1
 - file1
 - file2

User Story 2
 - file3
 - file4
 - ...

Further more, user can take actions(stage, clean, push) on selected group
For example only clean changed files for User Story 1, etc.

**Comment by joaomoreno** [comment]
This will likely not happen, since we try to be as close to the git flow as possible, in which there is simply a single staging area.
