### ISSUE TITLE
Closing file open in 2 places opens "save" dialog

### ISSUE THREAD

**Issue by jkjustjoshing** [Microsoft/vscode#10909]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Open a project in VS Code
2. Split the editor so 2 files can be viewed side by side
3. Open the same file twice and arrange so both are visible
4. Make an edit to the file (either one - the changes should sync between the two views)
5. Try closing one of the instances of the file

**Desired behavior:** The file will close with no prompt, since there is another instance of the file still being edited
**Current behavior:** The file will prompt you to save. Not only that, if you click "Don't Save", the file will revert to the version on disk, and any work done on the file will disappear from the instance still open.

**Comment by bpasero** [comment]
We fixed this already for August.

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
