### ISSUE TITLE
Send `vscode.workspace.onDidCreateFiles` events for folders

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#109088]
It does fire for folder on move and delete.  According to @bpasero the reason lies here: https://github.com/microsoft/vscode/blob/60d96d72a560f0f02d67ef9d438a8a7ed534ec4a/src/vs/workbench/contrib/files/browser/fileActions.ts#L897-L897

The code goes directly to the file service.

Since we correctly report move and delete for folders I think we should report create as well.

**Comment by dbaeumer** [comment]
Some background: I want to adopt this in LSP but specing that this only works for move and delete of folders sounds a little silly. So I want to make sure that there is either a very compelling reason or there is some ack. that we will fix it in the future.

**Comment by bpasero** [comment]
We currently have no related method such as `ITextFileService#create` for folders that the explorer could use here:

https://github.com/microsoft/vscode/blob/60d96d72a560f0f02d67ef9d438a8a7ed534ec4a/src/vs/workbench/contrib/files/browser/fileActions.ts#L897-L897

If we support this, I guess one question in terms of API breakage is wether it is fine to let `onWillCreateFiles` and `onDidCreateFiles` emit events for folders too while they currently only emit for files.

**Comment by jrieken** [comment]
> I guess one question in terms of API breakage is wether it is fine to let onWillCreateFiles and onDidCreateFiles emit events for folders too while they currently only emit for files.

I don't consider that breakage, it's a bug fix esp. given that move and delete already fire events for both

**Comment by bpasero** [comment]
**Verification:** write an extension that registers to `onWillCreateFiles` and `onDidCreateFiles` and verify you see both events when you right click into the explorer and create a new folder.

**Comment by dbaeumer** [comment]
Thanks for fixing!
