### ISSUE TITLE
My code vanished.

### ISSUE THREAD

**Issue by ParkerOP** [microsoft/vscode#109032]
Issue Type: <b>Bug</b>

I tried to host my Giveaway discord bot on Heroku but failed so I closed vs code and turned off the pc.When I came back,my all saved codes vanished.Only those codes remained that were there in starting.What I edited in them and all new files that I made were not there.If you think that I tried to host before editing,ur wrong.I edited,saved and even tried my bot using `npm run start` and after that tried to host but failed,ok no problem.My problem is why my code vanished after I reopened my folder in vs code after turning on my pc.😢
I worked hard on it.I want to get my work back!!!

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.55GB free)|
|Process Argv|--crash-reporter-id b68e25f4-0780-487c-9d7d-db0810905acd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
code-runner|for|0.11.1
vsliveshare|ms-|1.0.3014
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.11
commandlist|yam|1.0.3

</details>

**Comment by bpasero** [comment]
Sorry to hear that but from the description I cannot tell what was going wrong. You seemed to have saved the files and not left them dirty, is that true?

**Comment by ParkerOP** [comment]
Yes,I saved all the files.Sorry for the late response.

**Comment by bpasero** [comment]
Is this a special file system, maybe connected to a remote or all local?

**Comment by ParkerOP** [comment]
Nothing special. But I done hardwork on it!! It was the code of a discord
giveaway bot. I didn't host it as I said I tried on Heroku but failed so I
closed the pc.

**Comment by bpasero** [comment]
Sorry, but I see no actionable item for me here.
