### ISSUE TITLE
VS Code cannot resolve the path of tsconfig.json monorepo React - Nest project

### ISSUE THREAD

**Issue by montacerdk** [microsoft/vscode#109075]
- VSCode Version: 1.50
- OS Version: Ubuntu 18

Steps to Reproduce:

1. Create a mono repository project that contains two projects (React.js and Nest.js) using Create React App and Nest CLI. this what the path looks like : 

- **Mono repo** : 

![Screenshot from 2020-10-21 10-50-34](https://user-images.githubusercontent.com/26897940/96704310-d9c6d300-138b-11eb-9feb-a917ea16d489.png)

- **React Project** :

![Screenshot from 2020-10-21 10-50-53](https://user-images.githubusercontent.com/26897940/96704504-15619d00-138c-11eb-9a01-ee96c26a22b7.png)

- **Nest Project** : 

![Screenshot from 2020-10-21 10-51-22](https://user-images.githubusercontent.com/26897940/96704657-404bf100-138c-11eb-8570-1f5e19ff7435.png)

2. When opening a file, it seems that VSCode cannot resolve the path of the tsconfig.json file in the nest project.

![Screenshot from 2020-10-21 10-52-03](https://user-images.githubusercontent.com/26897940/96705007-a59fe200-138c-11eb-94a8-7ff5350548a7.png)

Any solutions to this ?

**Comment by mjbvz** [comment]
Please share a minimal example project that demonstrates the issue

**Comment by montacerdk** [comment]
I've just created a git repository that demonstrates the issue.

[HERE](https://github.com/montacerdk/react-nest-mono)

**Comment by mjbvz** [comment]
Thanks. Looks like these errors are actually coming from eslint instead of VS Code (see `eslint` in the error message.)

Please start by filing this issue against the eslint extension
