### ISSUE TITLE
C++ highlighting broken on class template specializations, but only with specific formatting 

### ISSUE THREAD

**Issue by evanacox** [microsoft/vscode#109098]
With C++, `class`/`struct` template declarations break syntax highlighting with template specialization **only** when there's not an opening brace on the end of the line, and the template is on the same line as `struct`/`class`. Does't change when 
the C++ extension is enabled/disabled, it's broken on both. 

- VSCode Version: 1.50.1
- OS Version: Linux x64 5.8.15-201.fc32.x86_64

Steps to Reproduce:

1. Open up a C++ file in VSCode
2. Paste in the following:
```cpp
template <class T> struct example;

// highlighting works perfectly fine here
template <> struct example<unsigned> {};

// this also works perfectly fine
template <>
struct example<int> 
{};

// highlighting breaks at <>, doesn't matter if there is anything in it or not. 
// doesn't matter if the specialization is partial, full, CV-qualified, or anything else. 
template <> struct example<long> 
{};
```

At least on my machine, that text produces the following in a brand new Insiders installation: 
![Screenshot from 2020-10-21 11-21-32](https://user-images.githubusercontent.com/44881821/96741263-9bcbae00-138f-11eb-83aa-4e005f534c65.png)

Does this issue occur when all extensions are disabled?: **Yes**/No (Also reproduces on the Insiders build)

**Comment by alexr00** [comment]
Since we get our c++ syntax highlighting grammar from another repo, I have moved the issue to https://github.com/jeff-hykin/cpp-textmate-grammar/issues/512
