### ISSUE TITLE
Debug font settings

### ISSUE THREAD

**Issue by pjuangph** [microsoft/vscode#109045]
- VSCode Version: 1.50.1
- OS Version: Windows 10

I noticed there's a change to the font coloring in the debug settings. How am I supposed to read this? This happens because I have 8 threads so each thread highlights the same line when it fails. Highlights overlap and then it's impossible to read anything.
I'm using python with code. Is anyone else seeing the same issue? 
![image](https://user-images.githubusercontent.com/9328717/96650843-8f007900-1301-11eb-83dd-f09d37243507.png)

**Comment by isidorn** [comment]
Oh my. Yeah the idea was to show a stronger color when there are multiple threads on the same line. But this case shows the problem. Let me assign to this milestone so I change this

**Comment by isidorn** [comment]
I have pushed a fix for this you can try it in vscode insiders and let us know if it works.

Easy verification steps:
1. Have a simple `hello.js` file and put a breakpoint on that line
`console.log('hello there')`
2. Have the following launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/hello.js"
        },
        {
            "type": "node",
            "request": "launch",
            
            "name": "Launch Program2",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/hello.js"
        }
    ]
}
```
3. Launch both configurations and verify that the yellow color does not change shades of yellow even when mulitiple programs stop on the same line
