### ISSUE TITLE
Webview views do not persist view actions on hover

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#109030]
All other views show the view actions when the entire view is hovered. But on webview views, the view actions go away when the webview is hovered.

![Kapture 2020-10-20 at 09 42 49](https://user-images.githubusercontent.com/35271042/96618120-60f74680-12b9-11eb-97ae-800d1f3b8e36.gif)

**Comment by nabeelkausari** [comment]
Any update on this issue? @mjbvz please consider prioritising it

**Comment by mjbvz** [comment]
Fixed by #185864
