### ISSUE TITLE
"The Request Timed Out" update service notification on every new window when on bad internet

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#109097]
I don't think we should be loud about network failures if the user didn't explicitly ask for an update. Especially not on every new window.

![image](https://user-images.githubusercontent.com/8586769/96740765-fe17b500-1375-11eb-955d-958b75f92de1.png)

**Comment by joaomoreno** [comment]
Also:

![image](https://user-images.githubusercontent.com/22350/96887904-54274e00-1485-11eb-9a9d-51f75b3a2e92.png)
