### ISSUE TITLE
Provide Button to Show Additional Detail When Extension Install or Update Fails

### ISSUE THREAD

**Issue by starionjames** [microsoft/vscode#109023]
Issue Type: <b>Feature Request</b>

When an extension update or install fails, an error message toast appears stating the update/install has failed.

The toast includes a button for "Download Manually"

Add to this toast message a button or link that will open a new editor window with additional error information.

The additional information should include: 

A formatted and human readable text window containing the error information.

If possible, when the error is due to exceeded resource limits when downloading the extension, the error could indicate that the extension download server is overloaded and to try again in a few minutes.

Perhaps some metric should be kept regarding how often resource limits are  exceeded when new updates become available, which is a likely scenario when a popular extension reports via the GUI that an update is available.

This is now the second time in about 1 month that I have seen this issue.  The specific extension I was attempting to update is: the C# extension from OmniSharp.

This is the only error I have ever encountered in VS code since I began using it in late 2016.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
I think its a fair request to see the error. Best is to show the error message in the prompt.

**Comment by sandy081** [comment]
Added link to show logs when extension install fails due to unknown reason

<img width="560" alt="image" src="https://user-images.githubusercontent.com/10746682/98243357-1db1fe80-1f6e-11eb-8834-ae12d69771ff.png">

**Comment by sandy081** [comment]
To verify

- Browse for an extension and disconnect from internet
- Install the extension and make sure you get above prompt
