### ISSUE TITLE
Consider to rename resourceIdentityService

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109015]
While looking into lifting services we declare in `src/vs/platform` to `src/vs/workbench` because they are only used there, I came across `resourceIdentityService` (which I moved to `workbench` btw: https://github.com/microsoft/vscode/commit/c57b7cd3d65a5f1404ec5bdd1d17252f65b9cf21). 

Since we already have a `IURIIdentityService` (probably came in later), I suggest to rename this service to better reflect it's purpose if possible.

Looking at the implementation it seems to produce a hash of the resource, so maybe `IResourceHashService` or `IURIHashService`?

**Comment by sandy081** [comment]
Removed this service and inline it in main as it is not needed anywhere at present.
