### ISSUE TITLE
Easier switch between shells

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#109037]
Make it easy to switch between shells for the terminal. I frequently use all three options (cmd, powershell, and wsl) at the same time, but the only way to open them is first to "Select Default shell" and then open a new terminal. This is tedious and time consuming.

(I actually think of this more of a product defect than a request, but alas.)

**Comment by Qubisc** [comment]
You could always set a keyboard shortcut for it. 
Look under Preferences->Keyboard Shortcuts->Terminal: Switch Active Terminal.

**Comment by runxel** [comment]
> 
> 
> You could always set a keyboard shortcut for it.
> Look under Preferences->Keyboard Shortcuts->Terminal: Switch Active Terminal.

Uhm, sorry @retfloww? This has nothing to do with the act of _switching between tabs_ or therelike.
Looks like the terms are overloaded. If I talked about switching it means there is no way to open _a new_ terminal shell, but _with another shell_. (CMD is opened, but I need a WSL shell)
You instead can only open another shell of the same kind, which is okay, but not really what I need.

**Comment by retfloww** [comment]
Oh I now undertand what do you mean. Alright, sorry for misunderstanding you.

**Comment by runxel** [comment]
> 
> 
> Oh I now undertand what do you mean. Alright, sorry for misunderstanding you.

No problem. I realized too late that the term "switching" is actually used differently even in VSCode 🤦‍♂️

**Comment by Rvvlf** [comment]
Try this extension. https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher.

**Comment by runxel** [comment]
> 
> 
> Try this extension. [marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher](https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher).

Thanks for this tip, @Rvvlf! I've tried it and it seems good enough. I still would prefer to be this a built in feature, tho. There is already everything there, the devs would just need to improve in the usability.
(I'd propose a new setting, where you either can have the current behaviour when pressing that "+" i.e. launching a new terminal with the _same_ shell as currently, or being _asked_ which shell to start)

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/issues/45444 is the issue tracking essentially merging in shell launcher's functionality.

/duplicate
