### ISSUE TITLE
The focused repository and the bottom repo are not in sync

### ISSUE THREAD

**Issue by danielt117** [microsoft/vscode#109028]
- VSCode Version: 1.50.1
- OS Version: Ubuntu 20.04

Actual behavior:
If i have multiple repositories, and i change the focused repo to another, the selected git repository on the bottom stays on the first repo. And only changes if i commit in other repo, but not when i select it in the upper menu (scm). Currently it's misleading, and sometimes i sync a repo that i don't want.

Expected behavior:
In the previous versions it worked like: If i selected a repository in the scm, the bottom repo was always the same as the focused one.

Note: I'm using the "old" scm view that was reintroduced in 1.49

![1](https://user-images.githubusercontent.com/42888821/96615877-25cd3580-1302-11eb-98cc-817c8ba3b957.jpg)
![Screenshot from 2020-10-19 11-37-34](https://user-images.githubusercontent.com/42888821/96615887-28c82600-1302-11eb-9905-54efd4917491.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
The status bar will only follow the open file, not the visible repositories. If you open a file within that other repo, it will appear in the status bar.
