### ISSUE TITLE
[PHP] Debug Console doesn't execute some php commands

### ISSUE THREAD

**Issue by albertgaya** [microsoft/vscode#109013]
Requirements:
- Laravel Project
- Xdebug
- VSCode

Note: It's working before V1.50.1 update.

I'm implementing a Test Driven Development approach. 

Steps:
1. Create Test case and write random code
2. Assign a breakpoint 
3. Run Debugger
4. Run Test (Execution will stop to breakpoint)
5. Open "Debug Console" and type simple PHP script 

```
echo "Hello World";
```

Expected: "Hello World"
Actual: "error evaluating code"

[Updates]

Attribute not recognized
![Screenshot](https://user-images.githubusercontent.com/4438423/96601892-072c6600-1325-11eb-8097-985e85e9203e.PNG)

Attribute being assign. (Tried also just putting below code)
```
$model->memberPrivacy
if ($model->memberPrivacy->members_visibility != -1) {
...
```
![Screenshot_2](https://user-images.githubusercontent.com/4438423/96602376-891c8f00-1325-11eb-92d3-e25ec803d4e2.PNG)

**Comment by albertgaya** [comment]
@weinand i disabled all the extension except "PHP Debug" but still issue occur

**Comment by weinand** [comment]
Your problem is an issue of the PHP extension. Please file it against that extension.
