### ISSUE TITLE
Completions ignores sortText

### ISSUE THREAD

**Issue by boaz-codota** [microsoft/vscode#109067]
- VSCode Version: master
- OS Version: ---

Building [TabNine](https://github.com/codota/tabnine-vscode) we encountered a bug in completions, where `sortText` is ignored if any `CompletionItem` does not contain `sortText` attribute. This causes the IDE to totally ignore the `sortText` in the ordering, forcing the sort algorithm to fallback to `label` only.

Steps to Reproduce:

1. Use suggestions from a source that provide `sortText` (such TabNine) & a source that does not provide `sortText` (such the built in lsp).
2. Completions suggestions's ordering will be based on the `label` and not on the `sortText`.

I traced the bug to this line: 
https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/suggest.ts#L274
The problem is that it is checked that `sortText` is present on both `CompletionItem`s, breaking the sort functionality if any single item does not implement `sortText`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by boaz-codota** [comment]
@jrieken I'll be more than happy to create a PR if it'll be merged

**Comment by jrieken** [comment]
If it's a good PR it'll be merged. Tho, I wonder if there was a specific reason for why things are they way they are. I could have also sworn that I have fixed this already... Needs a short trip down memory lane before making this change 🤔

**Comment by boaz-codota** [comment]
Cool, let me know if you want me to provide a fix. Will ping every day. Thanks!

**Comment by jrieken** [comment]
Found the issue: https://github.com/microsoft/vscode/issues/66109. So, this is actually fixed but in a sneaky way, e.g by always filling in the sortText-property (b4ead4e). Leaves the question what you are actually seeing? Do you have some simple steps to reproduce this?

**Comment by boaz-codota** [comment]
This is an example:
![image](https://user-images.githubusercontent.com/69103343/96744896-2fbc6a80-13ce-11eb-9fa8-014f83ff86d0.png)

We give our suggestions `sortText` of zeros (1st suggestions gets "0", 2nd "00" etc.; I also tried other characters combinations, none seem to change something) but our suggestions still only shown after some of the results coming from the lsp (not all of them, only those with the same `Range` of matching characters).

You can install TabNine and test it yourself.
This is where the `sortText` is set: https://github.com/codota/tabnine-vscode/blob/master/src/provideCompletionItems.ts#L95

**Comment by jrieken** [comment]
Check this out: https://github.com/microsoft/vscode/blob/cb1dce0ef30d48c4259eb7d0a923926b3e6e16af/src/vs/vscode.d.ts#L3855-L3863

Basically, what is says (tries to say) is that once a prefix exists (`ht` in your sample) the match quality of that prefix and a suggestion overrules all sortText.

**Comment by jrieken** [comment]
Unsure if you use `filterText`. With that property you can provide a string that matched against said prefix. Assuming in your sample you set it to `html` then ranking should be different. Also: you can hit `cmd+/` to toggle explain mode - the details part of the suggest widget will then show some debug info, like so: 
<img width="685" alt="Screenshot 2020-10-21 at 18 01 04" src="https://user-images.githubusercontent.com/1794099/96746369-65118a00-13c7-11eb-9f3b-9c99b7f9f6e4.png">

**Comment by boaz-codota** [comment]
Thanks! That seem to make things much better. But I'm still confused about other ordering as such:
![image](https://user-images.githubusercontent.com/69103343/96834019-f7f30880-1449-11eb-93e4-0848445981dc.png)

**Comment by jrieken** [comment]
Hard to say. What does the explain widget say?

**Comment by boaz-codota** [comment]
`cmd`+`/` didn't trigger it. Do I need some special version of vscode for it?

**Comment by jrieken** [comment]
I think you need to trigger it first on an item with details, like `realPath` or so and then go up
