### ISSUE TITLE
Make problems filter apply in the editor view

### ISSUE THREAD

**Issue by gdlx** [microsoft/vscode#109003]
I wish I could quickly & temporarily disable the wavy problem markers to improve code readability when actually working on fixing the problem.

This becomes an obvious need when the problem applies on a whole method (eg. Too long/complex, ...):
![image](https://user-images.githubusercontent.com/1533042/96567918-a589de80-12c7-11eb-94c5-ca1f7af33510.png)

I think the best way would be to make the problems panel filter being applied in the editor view:
![image](https://user-images.githubusercontent.com/1533042/96568827-a4a57c80-12c8-11eb-937f-30625c319184.png)

Note my request is not about disabling linting nor changing the problem display style, it's just about a quick toggle like the problems filter, but applied in the editor.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/90180
