### ISSUE TITLE
Displacement of syntax and language-server highlighting

### ISSUE THREAD

**Issue by achimnol** [microsoft/vscode#109069]
- VSCode Version: 1.50.1
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. This does not happen always, but suddenly, opening [this file](https://github.com/lablup/backend.ai-manager/blob/master/src/ai/backend/gateway/etcd.py) results in a displacement of syntax highlights and language-server highlights.
![image](https://user-images.githubusercontent.com/555156/96692535-195be200-13c1-11eb-92ec-5d491997a599.png)

I'm using the remote development extension (0.20.0) with SSH (0.55.0), where the Python extension (2020.9.114305) and pylance extension (2020.10.1) is installed and activated remotely.

This issue had persisted even I close the file and reopen, but disappeared when I completely restarted VSCode.

Does this issue occur when all extensions are disabled?: Yes/No -> This issue looks related to the extensions or handling of extensions.

**Comment by aeschli** [comment]
@achimnol This might be a semantic highlighting issue. To confirm, can you set the cursor in a one of the wrongly colored areas and invoke the `Developer: Inspect Editor Tokens and Scopes`) command? A screenshot of the result would be helpful.

**Comment by achimnol** [comment]
Thanks for quick reply.
Unfortunately this happens randomly and I don't know how to exactly reproduce it, though it is not entirely that rare.
I will try to gather more debug log if I encounter this again.

**Comment by aeschli** [comment]
Closing the issue but I'm happy to reopen when we have more information.
