### ISSUE TITLE
Keystrokes are delayed

### ISSUE THREAD

**Issue by mishranurag** [microsoft/vscode#109046]
Issue Type: <b>Bug</b>

Sometimes keystrokes don't do anything.  I need to wait for the effect of keystrokes. It especially happens with latex documents.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.55GB (3.98GB free)|
|Process Argv|--crash-reporter-id 4588d334-c3ca-49e1-8dd9-d4cd459b2053|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.52
githistory|don|0.6.12
vscode-pandoc|Dou|0.0.8
gitlens|eam|10.2.2
compareit|in4|0.0.2
latex-workshop|Jam|8.13.2
rainbow-csv|mec|1.7.1
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.9.114305
vscode-yaml|red|0.11.1

</details>

**Comment by tamuratak** [comment]
Uninstall the extension `Spell Right`.

See https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#known-incompatible-extensions

**Comment by djmisterjon** [comment]
ya typescript consume a lot of memory !(Intelisence) sometime i reach 3go ram !!!
![image](https://user-images.githubusercontent.com/24865815/96662021-7309d100-131b-11eb-86cc-4bfabd423bc0.png)
When is too big, just close and restart vscode.
note: 
more you open window, more is can be laggy.
More you have [node_module] for is laggy.
Also extensions, but in my case i dont have a lot.

**Comment by mishranurag** [comment]
Removing that extension definitely helped. Thanks a lot.

**Comment by alexdima** [comment]
Thank you for following up. Please create an issue directly against the extension.
