### ISSUE TITLE
facing slow file saving problem

### ISSUE THREAD

**Issue by hope0986** [microsoft/vscode#109073]
Issue Type: <b>Bug</b>

facing slow file saving problem

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (6.65GB free)|
|Process Argv|--crash-reporter-id 2ef01fdf-c564-4d12-89bd-0591c5e047b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Untabify|ili|0.0.2
duplicateselection|kka|1.0.1
material-icon-theme|PKi|4.3.0
sonarlint-vscode|Son|1.17.0

</details>

**Comment by isidorn** [comment]
Here's how to report a performance issue https://github.com/microsoft/vscode-wiki/blob/master/Performance-Issues.md
For now closing this as it does not have any details needed
