### ISSUE TITLE
Problems with 1.50.1 on Windows 10 19041

### ISSUE THREAD

**Issue by Skatterbrainz** [microsoft/vscode#109038]
- VSCode Version: 1.50.1
- OS Version: 10.0.19041 (Windows 10 x64 Enterprise)

Steps to Reproduce:

1. Launch via shortcut or CLI
2. Wait 1-2 minutes for UI to render
3. Theme is disabled

Does this issue occur when all extensions are disabled?:  Somewhat

The theme is restored, but it still takes 1-2 minutes to reach ready for editing.

I've tried disabling individual extensions, but the UI is running so slow.  I will try uninstall and reinstall of the app and extensions as well.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by Skatterbrainz** [comment]
Sorry for the slow reply - it's been a busy week.  The issue resolved itself after a reboot. I'm still not sure what caused it, but it hasn't occurred since.  Thank you!
