### ISSUE TITLE
command + click 崩溃了

### ISSUE THREAD

**Issue by 947612227** [microsoft/vscode#109042]
按下转到定义的快捷键之后，vscode崩溃了
![image](https://user-images.githubusercontent.com/39144531/96538925-55f9e180-12cc-11eb-956f-ce9f13267ad9.png)

**Comment by deepak1556** [comment]
1) Can you launch with `code --crash-reporter-directory /tmp/vscode-crash`
2) Perform the steps for crash
3) Attach the crash dumps here or you can send them to Deepak.Mohan@microsoft.com
