### ISSUE TITLE
Format On Save (modifications) formats entire file when resolving merge conflicts

### ISSUE THREAD

**Issue by emptyVoid** [microsoft/vscode#109022]
- Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.19041

Steps to Reproduce:
1. Edit GIT merge conflict.
2. Save the file.

**Comment by jrieken** [comment]
what file-type? what formatter extension?

**Comment by emptyVoid** [comment]
C++ files: .cpp/.hpp/.h
ms-vscode.cpptools I guess? (is it exposed somewhere?)

**Comment by jrieken** [comment]
@joaomoreno It seems that `getOriginalResource` is returning an empty string when having a conflict? This can also be seen by the lack of dirty diff decorators. Is that intended and should I adjust my logic accordingly?

**Comment by joaomoreno** [comment]
It is expected: original resource only exists if the file is not in the Merge group.

**Comment by jrieken** [comment]
Makes sense but I would have expected that `getOriginalResource` returns `undefined` in that case, not an empty document.

**Comment by jrieken** [comment]
I can add a check for the original being empty (`""`) but that will break the case in which a file has been added since I cannot differentiate between new files and conflicting files
