### ISSUE TITLE
Explorer has Download command in context menu

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#109077]
![image](https://user-images.githubusercontent.com/22350/96705250-527e5d00-1395-11eb-870c-1cb03fb64253.png)

**Comment by bpasero** [comment]
I did not change that, we always show "Download" for remotes:

![image](https://user-images.githubusercontent.com/900690/96706031-552d8200-1396-11eb-9756-4fa573324651.png)

**Comment by joaomoreno** [comment]
Oh sorry, this was WSL, my bad 🙈
