### ISSUE TITLE
Jupyter notebooks only show JSON view

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#109181]
Issue Type: <b>Bug</b>

opened a Jupyter notebook which I've run successfully many times before, as recently as October 12th... got a JSON view with no syntax highlighting & ability to execute the embedded Python

(also occurs with all extensions disabled)

running Python 3.7.8 from Visual Studio install (same behavior with 3.7.6 from Conda), Python extension v 2020.9.114305
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (6.91GB free)|
|Process Argv|--file-uri file:///c%3A/src/CCPA.code-workspace --crash-reporter-id 75dbaf1b-c97f-4cbe-92b0-b4ac9d69a742|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by rebornix** [comment]
Please file issue against the Python extension.
