### ISSUE TITLE
After last update today VSCODE broken. "Extension host terminated unexpectedly."

### ISSUE THREAD

**Issue by masihjahangiri** [microsoft/vscode#109116]
Issue Type: <b>Bug</b>

We get this error:
Extension host terminated unexpectedly.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.97GB free)|
|Process Argv|--crash-reporter-id 8a77c77e-d4b0-4827-8cd0-fd99fa121fd4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
amphtml-validator|amp|1.1.0
vscode-styled-jsx-languageserver|And|1.0.1
vscode-apollo|apo|1.17.0
vscode-styled-jsx|bla|2.0.0
vscode-tailwindcss|bra|0.4.3
path-intellisense|chr|2.3.0
vscode-css-modules|cli|0.2.3
vscode-markdownlint|Dav|0.37.1
vscode-eslint|dba|2.1.13
xml|Dot|2.5.1
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.7.1
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
vscode-styled-components|jpo|1.2.0
graphql-for-vscode|kum|1.15.3
dotenv|mik|1.0.1
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.7.0
remote-wsl|ms-|0.50.1
vsliveshare|ms-|1.0.3014
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
polacode|pnp|0.3.4
vscode-yaml|red|0.11.1
markdown-preview-enhanced|shd|0.5.13
code-spell-checker|str|1.9.2
vscode-stylelint|sty|0.85.0
markdown-all-in-one|yzh|3.3.0

(1 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
Does the extension host crash when disabling all extensions? Press F1 and then choose Developer: Reload Window with Extensions Disabled

/needsMoreInfo

**Comment by masihjahangiri** [comment]
I completely uninstall VSCODE and install it again to solve issue and now it works correctly, If the issue returned again I'll send you more info about it here. Thanks you.
