### ISSUE TITLE
Show search history list

### ISSUE THREAD

**Issue by nguyenhuynhan** [microsoft/vscode#109148]
Issue Type: <b>Feature Request</b>

There're lot of cases I need to switch between recently keywords. So it's very nice if Visual Studio Code support this feature.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.6.0

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/23099
