### ISSUE TITLE
Debug toolbar: allow to position anywhere

### ISSUE THREAD

**Issue by diver2** [microsoft/vscode#109192]
Many people already complained. But you still haven't listened.
Please allow us to move the debug toolbar wherever we want, or provide more options.
I know of "debug.toolBarLocation": "docked" - and it is only visible in the debug tab, but if I'm on the project tree, it doesn't work. Currently the places where we can put the bar are annoying. Everyone is annoyed. There have been tweets with enormous following. Listen to the people.
Please listen to the people.
Best regards,

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by israelpgjm** [comment]
> This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by EverlastEngineering** [comment]
If this helps, I've written an extension to reveal the debug controls in the titlebar.

https://marketplace.visualstudio.com/items?itemName=EverlastEngineering.debug-in-titlebar

**Comment by Scrandre** [comment]
Why force a user to obstruct the view with the toolbar allowed to float only in the most obtrusive places when there are tons of empty spots on the screen?
The good candidate is the title bar, you moved the main menu there - great idea, good job! Why not do the same with the debug toolbar?
Another good candidate is the footer, it's also pretty empty. Or the leftmost icon bar?
Any location is better than the current position.
