### ISSUE TITLE
Terminal Doesn't work on Windows 10

### ISSUE THREAD

**Issue by Shaaman331** [microsoft/vscode#109120]
- VSCode Version: 1.50.1
- OS Version:

![winver](https://user-images.githubusercontent.com/50487748/96801826-ecb6c300-13de-11eb-9bca-ace9bd1f3c44.png)

Steps to Reproduce:

1. Install Visual Studio code stable version on Windows 10
2.  Try Open Terminal

<details>

![image](https://user-images.githubusercontent.com/50487748/96802271-e6751680-13df-11eb-84c2-c536aee880c2.png)

</details>

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
