### ISSUE TITLE
Keybinding issues in codespaces

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109169]
* maybe safari ?
* type in editor
* open find-widget
* hit ESC to close it
* :bug: it stays

Enable trace logging and see that the ESC has been dispatched correctly to the close-command 🤯 

<img width="1383" alt="Screenshot 2020-10-22 at 16 25 12" src="https://user-images.githubusercontent.com/1794099/96886825-40c7b300-1484-11eb-99a3-2bae9df8d304.png">

**Comment by jrieken** [comment]
I see the same with rename, hitting Enter in the input field doesn't do anything. Debugging shows that the context keys are bogous... Tho, not sure why...

<img width="816" alt="Screenshot 2020-10-22 at 16 56 35" src="https://user-images.githubusercontent.com/1794099/96890370-de70b180-1487-11eb-87a6-5fcc8eb92bad.png">

**Comment by jrieken** [comment]
Steps:

* open codespaces using safari
* type something into the SCM box
* focus into another window 
* focus back the codespaces window
* open explorer, open a file
* open in editor search
* hit `ESC`
* 🐛 widget doesn't close, debugger shows that the SCM find widget still thinks its active

**Comment by alexdima** [comment]
@jrieken I can no longer reproduce. I think this was related to https://github.com/microsoft/vscode/issues/112621 where the SCM viewlet would take the editor off-dom while the textarea was focused, which would cause browsers to behave weirdly. Can you please also try to reproduce again using latest?

**Comment by jrieken** [comment]
wasn't able to repro anymore
