### ISSUE TITLE
Debug Console doesn't respect user settings.

### ISSUE THREAD

**Issue by AmericanY** [microsoft/vscode#109111]
Issue Type: <b>Bug</b>

Python debug console doesn't use integrated shell args provided before. but outside debug console all is works fine.

My Settings:

```
{
    "terminal.integrated.shellArgs.windows": [
        "-ExecutionPolicy",
        "Bypass",
        "-NoLogo"
    ],
    "workbench.startupEditor": "none",
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "editor.formatOnType": true,
    "code-runner.clearPreviousOutput": true,
    "code-runner.runInTerminal": true,
    "code-runner.saveFileBeforeRun": true,
    "code-runner.showExecutionMessage": false,
    "workbench.panel.defaultLocation": "right",
    "terminal.integrated.copyOnSelection": true,
    "python.terminal.activateEnvInCurrentTerminal": true,
    "python.languageServer": "Microsoft",
    "python.pythonPath": "C:/Users/AmericaN/Desktop/Lab/MyEnv/Scripts/python.exe",
    "code-runner.executorMap": {
        "python": "$pythonPath -u $fullFileName"
    },
    "code-runner.ignoreSelection": true,
    "remote.SSH.remotePlatform": {
        "My": "linux",
    },
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
}
```

![image](https://user-images.githubusercontent.com/27644047/96783481-cf3d2580-13ed-11eb-8d5b-661ceeb16c9b.png)

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.84GB free)|
|Process Argv|--crash-reporter-id b6c0830d-6a13-4115-8888-7dc0b49df85d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.1
gc-excelviewer|Gra|3.0.40
python|ms-|2020.9.114305
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0

</details>

**Comment by AmericanY** [comment]
@weinand @connor4312 any update from your kind side?

**Comment by connor4312** [comment]
@weinand do you recall why this is commented out? 

https://github.com/microsoft/vscode/blob/63e42d414bf0867ba57a7c8f843744933087d911/src/vs/workbench/api/node/extHostDebugService.ts#L91

It looks like it's been that was since it was initially written, so my blame trail turned up empty

**Comment by weinand** [comment]
@connor4312 IIRC either "shellArgs" or "_getDefaultShellArgs()" was not available at that time

**Comment by AmericanY** [comment]
@weinand how to pull that fix?
