### ISSUE TITLE
vscode API - editors TextEditor.edit can control undo/redo stack

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109131]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=91409&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=3298c3b5-1605-5171-4fdb-795e858fded6&l=281

```
1) vscode API - editors TextEditor.edit can control undo/redo stack 1:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: 'hello world!' == 'Hello world!'
      + expected - actual

      -hello world!
      +Hello world!
      
      at extensions\vscode-api-tests\src\singlefolder-tests\editor.test.ts:155:12
      at processTicksAndRejections (internal/process/task_queues.js:94:5)

```

**Comment by alexdima** [comment]
I have tried locally to reproduce, but the test passes fine.

The test is making two consecutive edits to a file and then is executing undo. The test asserts that undo undoes both edits in one go, but in this test failure it looks like only the second edit was undone. So it appears that an undo stop was inserted in between the two edits.

Undo stops get inserted for really many reasons, for example when the cursor moves, when typing, when saving the file, etc. I did a quick look through all references, but nothing stood out to me.
