### ISSUE TITLE
Strange CompletionItemKind icons

### ISSUE THREAD

**Issue by JeremyJeanson** [microsoft/vscode#109154]
Issue Type: <b>Bug</b>

Since this week (since the 19 october) I have strange icons when I use code completion.

vscode use wrong icons for wrong CompletionItemKind.

ex: I see "Interface" icon when I should have "Module"
ex: I see "Module" icon when I should have "Property"

VS Code version: Code - Insiders 1.51.0-insider (9f7a586124ca121bba906b44eb8356691617957e, 2020-10-22T00:49:16.002Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (7.67GB free)|
|Process Argv|--crash-reporter-id ba82d897-f64b-40f3-a2f0-2f6677fb30b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
language-gettext|mro|0.2.0
vscode-kubernetes-tools|ms-|1.2.1
remote-wsl|ms-|0.51.0
azure-account|ms-|0.9.3
powershell-preview|ms-|2020.9.0
vscode-yaml|red|0.11.1
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0

</details>

**Comment by jrieken** [comment]
@misolori Do you recall any changes in that area?

**Comment by JeremyJeanson** [comment]
I forgot to say that this problem appends only when I am debugging the extension.

When I use the extension installed from the vscode marketplace, it work fine.

**Comment by misolori** [comment]
Haven’t made any changes. 

@JeremyJeanson can you post a screenshot?

**Comment by JeremyJeanson** [comment]
Yes, with TS code and JS ;)

**First exemple**

![node-completion](https://user-images.githubusercontent.com/17407758/96882685-d9a7ff80-147f-11eb-836d-46cb7d837ffe.png)

TS code used :
```typescript
return {
    data: data,
    label: definition.label,
    insertText: insertText,
    insertTextFormat: InsertTextFormat.Snippet,
    kind: CompletionItemKind.Module,
};
```

JS generated
```javascript
return {
    data: data,
    label: definition.label,
    insertText: insertText,
    insertTextFormat: vscode_languageserver_1.InsertTextFormat.Snippet,
    kind: 8 /* Module */,
};
```

**Second exemple**

![attribut-completion](https://user-images.githubusercontent.com/17407758/96882699-dc0a5980-147f-11eb-9d37-a1cca6fd5e60.png)

TS code used :
```typescript
return {
    data: data,
    label: definition.label,
    insertText:
        // Check if a snippet is avaiable
        definition.insertText
            ? definition.insertText
            : `${definition.label}="$1"`,
    insertTextFormat: InsertTextFormat.Snippet,
    kind: CompletionItemKind.Property,
};
```

JS generated
```javascript
return {
    data: data,
    label: definition.label,
    insertText: 
    // Check if a snippet is avaiable
    definition.insertText
        ? definition.insertText
        : `${definition.label}="$1"`,
    insertTextFormat: vscode_languageserver_1.InsertTextFormat.Snippet,
    kind: 9 /* Property */,
};
```

The code of this extension is available here: [fitbit-sdk-extension](https://github.com/JeremyJeanson/fitbit-sdk-extension)

**Comment by misolori** [comment]
FWIW: I'm seeing the completion kinds align in a dummy extension:

<img width="600" src="https://user-images.githubusercontent.com/35271042/96901834-9bdbb480-1448-11eb-906a-4a80f5f14921.png">

**Comment by JeremyJeanson** [comment]
@misolori Thak you. I didn't known this extension.

I found the same list via bing.

It is why I found the problem really strange when I run tests this week. I think it was fine last week, in debug.

**Comment by JeremyJeanson** [comment]
@misolori This morning, I had the same problem.

I cleaned all mes local out folders, and vs test folders.... Tada! It work fine since.

I don't understand why. The Javasript generated was fine. I cant' reproduce this error now. I think this isssue should be closed.

**Comment by jrieken** [comment]
ok. thanks for following up
