### ISSUE TITLE
Copying Files is Optimized for the Wrong Use Case (Very, Very Rarely Does Anyone Want "Foo (Copy).js")

### ISSUE THREAD

**Issue by machineghost** [microsoft/vscode#109105]
When you copy/paste a file in VS Code, it creates a copy named "Foo (Copy).js" ... and that's it.   I believe this would be the optimal behavior if the average user wanted to create files called "Foo (Copy).js".

However, I would submit that most developers *don't* want to create such files: when I copy "Foo.js", it's overwhelmingly more likely that I really want to create "Bar.js" or "FooBar.js", _not_ "Foo (Copy).js".

If the above claim is true (and you likely have access to way more insight into this than I do), then a different flow would be more optimal.  Instead of simply creating a new file called "Foo (Copy).js" when I paste, it would be more optimal if:

1. It created a file called "Foo (Copy).js" (as before)
2. It immediately began a rename operation on that file, and:
3. _(optional)_ It removed the " (Copy)"; this would make the rename invalid, but that's ok because ...
4. Stop here!  Leave the file mid-rename.

If I'm trying to create "Bar.js", you've now saved me the effort of having to right-click on the file and rename it ... which again (I would submit) is what happens 95%+ of the time after someone pastes a file.

And in the unlikely scenario that I truly did want "Foo (Copy).js", all this change adds to my workflow is that I have to hit ESC right after the paste, to cancel the rename and get back my "(Copy)" file.

**Comment by mjbvz** [comment]
Try changing the `explorer.incrementalNaming` setting to `"smart"`. This results in files call `Foo1`, `Foo2`, ...

**Comment by machineghost** [comment]
Please re-open this ticket, that does not address the issue.

Again, no one wants a file named `Foo1`.  They want a file named `Foo`, or `FooBar`.  Putting the user "mid-rename" solves this ... or rather, it optimizes for that use case ...

... but again, look at your metrics!  Are people really keeping files called "Foo (Copy).js" or "Foo 1.js"?  Or are they (95+% of the time) renaming them to "FooBar.js" or "Bar.js"?

**Comment by machineghost** [comment]
I don't think it's crucial, I just think it's a missed opportunity to make the editor better (and not a hard on either; all of the functionality to make it happen already exists).
