### ISSUE TITLE
Blurry upscaling on 4k display Win10

### ISSUE THREAD

**Issue by belst** [microsoft/vscode#109157]
- VSCode Version: 1.51.0-insider (user setup)
- Commit: 6c8c6008ef9d86e46b086a00f273b1fee5bd8c51
- Date: 2020-10-21T05:39:35.557Z
- Electron: 9.3.2
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS Version: Windows 10 Pro N Version 2004 Build 19041.572

Steps to Reproduce:

1. Launch Vscode
2. Drag it to higher dpi screen

Does this issue occur when all extensions are disabled?: Yes

comparison between telegram desktop and vscode:
![Telegram_2020-10-22_14-01-13](https://user-images.githubusercontent.com/1449312/96869828-516e2e00-1470-11eb-8e61-c05c9cbb21e1.png)

**Comment by deepak1556** [comment]
How does this compare to stable `1.50.1` ?

**Comment by belst** [comment]
It works with those 2 version I tested just not the insider version:

```
Version: 1.51.0-exploration (user setup)
Commit: 1dfc92ea9b990fad440fcf12ce46cb85897861ce
Date: 2020-10-22T06:39:15.893Z
Electron: 11.0.0-beta.12
Chrome: 87.0.4280.11
Node.js: 12.18.3
V8: 8.7.220-electron.0
OS: Windows_NT x64 10.0.19041
```

```
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by deepak1556** [comment]
Can you try launching with `--force-device-scale-factor=1`

**Comment by belst** [comment]
still blurry

**Comment by deepak1556** [comment]
There was a change in runtime for frameless windows in the insiders. Can you check with changing the title bar to native.

**Comment by belst** [comment]
Still not working :/

**Comment by deepak1556** [comment]
I believe you tried with `"window.titleBarStyle": "native"` ? Can you share your settings.json ?

Also instead of dragging from a low dpi monitor, what happens when you launch vscode in the hidpi display ?

**Comment by belst** [comment]
sure, config:

```json
{
    "git.path": "E:\\Program Files\\Git\\cmd\\git.exe",
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "gitlens.historyExplorer.enabled": true,
    "git.autofetch": true,
    "debug.allowBreakpointsEverywhere": true,
    "C_Cpp.updateChannel": "Insiders",
    "cmake.configureOnOpen": true,
    "remote.SSH.remotePlatform": {
        "192.168.178.22": "linux",
        "192.168.10.80": "linux"
    },
    "python.defaultInterpreterPath": "C:\\Program Files\\Python36\\python.exe",
    "python.insidersChannel": "off",
    "python.dataScience.widgetScriptSources": [ "jsdelivr.com", "unpkg.com"],
    "python.dataScience.themeMatplotlibPlots": true,
    "python.dataScience.askForKernelRestart": false,
    "window.zoomLevel": 0,
    "window.titleBarStyle": "native"
}
```

**Comment by deepak1556** [comment]
Exploration branch and master track each other closely, the only difference with the current insider is the frameless window fix https://github.com/electron/electron/pull/25940 which shouldn't affect native titlebar. Its weird that the issue persists in both the modes.

/cc @bpasero do you have the setup to confirm this issue ?


> Also instead of dragging from a low dpi monitor, what happens when you launch vscode in the hidpi display ?

@belst can you confirm this.

**Comment by belst** [comment]
> Also instead of dragging from a low dpi monitor, what happens when you launch vscode in the hidpi display ?

this doesn't change anything. looks the same

**Comment by bpasero** [comment]
I don't have a 4k display, only 2k. Should I still test something?

**Comment by deepak1556** [comment]
Ah in that case no need to test, thanks!

**Comment by sbatten** [comment]
I have set up 2 screens with 1080p and 4k resolution. Attempting to reproduce this, I see no noticeable difference between stable and insiders 
![image](https://user-images.githubusercontent.com/6561887/97054536-cce7e200-1539-11eb-8b9b-8bd6191914c6.png)

**Comment by deepak1556** [comment]
Its hard to debug further without a repro, can reopen if there is a reliable repro. Thanks!
