### ISSUE TITLE
API for work with '/// reference path="..' files

### ISSUE THREAD

**Issue by ldrahnik** [microsoft/vscode#109152]
Helllo,

i am sorry. I have a dev question. It is not a bug report. But it is a issue. If i should put this question somewhere else. Tell me please.

Exists API for work with /// references? (for example ```/// <reference path="Utilities.js")``` I write a extension and i would like to know list of files added by user on the top of each file. Is here any option list these files? And everything about this ecosystem is there more to know. Prefer links even links to code.

If not. Is it planned? Or is planned still use this syntax? I please eventually for feature request links if exist or whatever about future and these references.

Thank you!

Lukas

**Comment by mjbvz** [comment]
There is no API for this and we don't have plans to add one to VS Code.

If you want to parse a TypeScript file to find all `/// <reference` comments, you can use TypeScript as a library and [run its parser](https://medium.com/allenhwkim/how-to-parse-typescript-from-source-643387971f4e)

If you want to change TypeScript's behavior based on `/// <reference` comments, take a look at [TypeScript language service plugins](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin)
