### ISSUE TITLE
Have a setting option to close "(Working Tree)" tab when pressing "Open File"

### ISSUE THREAD

**Issue by Norfeldt** [microsoft/vscode#109113]
Have a setting option to close "**(Working Tree)**" tab when pressing "**Open File**" 

so it will be more like a "**Switch To File**" instead of "**Open File**".

**Comment by joaomoreno** [comment]
Closing this as designed because:

- There is currently no workbench support for this, so it's impossible to achieve as an extension
- There is already preview tab mode which alleviates this problem

**Comment by Norfeldt** [comment]
@joaomoreno is it possible to only have _**preview tab mode**_ enabled for the _**version control sidebar**_ and not for the _**file explorer sidebar**_?

**Comment by joaomoreno** [comment]
@Norfeldt I don't think that's currently possible, no.
