### ISSUE TITLE
Please Reopen the *Feature Request* (Not Question): 109105

### ISSUE THREAD

**Issue by machineghost** [microsoft/vscode#109107]
The issue https://github.com/microsoft/vscode/issues/109105 got closed incorrectly.  I know that comments on closed issues are often ignored, so I'm filing this to draw attention (apologies if closed tickets do get read, and this is unnecessary).

**Comment by mjbvz** [comment]
@machineghost Don't do this. If you disagree, post a follow up question

**Comment by machineghost** [comment]
Sorry, I did ... but as I said on *many* repos maintainers just don't pay attention to closed issue comments, so I was trying to walk the line between respectfully requesting a re-examination and being an annoying whiner who keeps creating tickets :-)

Again, apologies for being the latter.

**Comment by mjbvz** [comment]
At least give maintains time if that's your goal. It was < 10 minutes between you posting a follow up question and opening a duplicate issue

**Comment by machineghost** [comment]
Absolutely, will do next time, and again apologies.
