### ISSUE TITLE
Stop miss-clicks on actions in the view header from collapsing the view

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#109128]
Miss-clicks (specifically in views in the panel -- e.g. terminal, problems) on the actions in the view header causing the view to collapse is really driving me nuts 😄 

Can we add more room/padding around the action area that wouldn't collapse the view? This is especially problematic for me with the terminal view -- because if you click and miss the terminal dropdown on either the right or left, 💥 the terminal is collapsed.

Additionally I find this extra problematic for the panel, because I often just click "somewhere" in the terminal to give it focus, and sometimes I inadvertently hit the header.

Here is my panel

![image](https://user-images.githubusercontent.com/641685/96822559-5b544a80-13f8-11eb-9865-68ffe39a8f8d.png)

**Comment by sbatten** [comment]
not sure how this differs from the experience in the side bar that has been the same for so long, would like to figure out what exactly is causing new issues so we can address them specifically.

**Comment by eamodio** [comment]
I think the big issue is that the sidebar views generally don't have inputs or dropdowns -- and the inputs/dropdown have gaps and spacing around them that when clicked cause collapsing.

I think we should just stop the container for the "action bar" from propagating click events to cause the header to collapse -- because if you are anywhere in the action bar you are certainly not trying to collapse things.

Additionally, I would add a 5px (or so) buffer to the left of the action bar (basically expand the action bar and give it a left padding) so that it also won't collapse, since you are so close to an action.
