### ISSUE TITLE
Fedore 32 Snap crashes when doing almost anything - saving, closing a tab, going to a menu option

### ISSUE THREAD

**Issue by tromlet** [microsoft/vscode#109182]
- VSCode Version: d2e414d9
- OS Version: Fedora 32

Steps to Reproduce:

1. Open VS Code
2. Old windows to files/folders should open
3. Try to save anything or close any tab, or try to go to Help > About -- instant crash.

Does this issue occur when all extensions are disabled?: Yes/No

 Not sure how to do this with the snap...

**Comment by connor4312** [comment]
Please share a crash report: https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

/needsMoreInfo
