### ISSUE TITLE
Suggest box: documentation box does not preserve size

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#109160]
1. Increase the size of the suggest documentation box 
2. Notice how the size of the suggest documentation is not preserved when I open another suggest item

I would expect the suggest documentation size to be the `Min(size to show full content, user set size)`

**Comment by jrieken** [comment]
What I am planning to do is to remember the size per suggest session, but not permanently. I think documentation changes too much between items, files, and languages to have value is persisting longer. @isidorn Let me know if you disagree

**Comment by isidorn** [comment]
I agree the value should not be peristed forever.
Depends on what is the defintiion of the suggest session?
I guess until user closes the suggest box or accepts an item... I think that makes sense, alternative would be until user moves to another file (which your widget is proably unaware of) or just until he closes VS Code (so you simply keep it in memory).

**Comment by jrieken** [comment]
> I guess until user closes the suggest box or accepts an item... 

Yeah, that's what I had in mind

/cc @misolori
