### ISSUE TITLE
Tabs move with marquee effect to the left [Regression]

### ISSUE THREAD

**Issue by fritzfr** [microsoft/vscode#109156]
I had this reported previously [here](https://github.com/microsoft/vscode/issues/104367), it disappeared but seems to be back now.

- VSCode Version: 1.50.1
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Have VSCode split into 2 editors (left + right)
2. Have a couple of Tabs open on the right half so that the tab list at the top is longer than the available space at the top
3. Click on the right most tab (or any tab that is NOT 100% visible with its width), it will start to move with a marquee effect slowly to the left until the start

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by fritzfr** [comment]
@bpasero I have a hard time reproducing it with the production build, it's not occuring after a restart. I get the feeling it might have to do with an extension, will report back.

**Comment by bpasero** [comment]
Ok thanks.
