### ISSUE TITLE
Terminal passthrough commands/keyboard shortcuts

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#109188]
When running Remote-WSL/Remote-SSH/Codespaces from a winows box to a Linux box we get unavoidably conflicts for keyboard shortcuts. To mitigate we use `terminal.integrated.commandsToSkipShell`, however without research there is no way for a user to know that this controls the behavior. We should explore how to teach the users about the setting (and maybe rethinking the setting to easily allow for `everything goes to the workbench` and `everything goes to the terminal`.)

**Comment by Tyriar** [comment]
Do you have some examples of the conflicts you hit?

**Comment by Tyriar** [comment]
We had a chat about this and landed on a pretty good idea:

- Add a new setting that would change the default value of commandsToSkipShell to []
- Intercept the first ctrl+<key> keybinding in the terminal the user uses and ask them if they wanted it to be sent to the shell
- If they do, set the new setting to true, and set commandsToSkipShell to a very small subset of the commands, maybe just toggle terminal (ctrl+`) and focus editor group 1 (ctrl+1)

**Comment by Tyriar** [comment]
@meganrogge I think this is done in https://github.com/microsoft/vscode/pull/110987 (tested in https://github.com/microsoft/vscode/issues/111330), please reopen if something isn't covered.
