### ISSUE TITLE
Terraform autoformatting stops working when in settings.json editor.formatOnSaveMode is set to a value

### ISSUE THREAD

**Issue by miniGweek** [microsoft/vscode#109109]
- VSCode Version: 1.50.1
- OS Version: Windows 10 x64 Pro

Steps to Reproduce:

1. Install HashiCorp Terraform extension.
2. Enable auto format on save for Terraform by adding the following entry in settings.json
`"[terraform]": {
        "editor.formatOnSave": true
    }`
3. Also ensure that the following terraform language server settings are there
`"terraform.languageServer": {
        "external": true,
        "args": [
            "serve"
        ],
        "maxNumberOfProblems": 100
    }`
4. Create a terraform file, keep it simple ...  A simple terraform like this gets formatted on save

```
provider "azurerm" {
  version = ">= 2.28.0"
                features {}
}

terraform {
             required_version = ">= 0.13.3"
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}
```
5. Enable VS code settings to save on every modification , edit settings.json like
```
editor.formatOnSaveMode : "modifications"
```
6. Now Terraform files do not autoformat on save
7. Remove the line editor.formatOnSaveMode from settings.json
8. Terraform autoformatting works again.

Does this issue occur when all extensions are disabled?: Yes/No
N/A Not applicable.

**Comment by jrieken** [comment]
Does the formatter support formatting a selection? You can check that by selecting some text and then locate "Format Selection" in the context menu

**Comment by miniGweek** [comment]
> Does the formatter support formatting a selection? You can check that by selecting some text and then locate "Format Selection" in the context menu

Hi mate,
I also posted this in reddit https://www.reddit.com/r/Terraform/comments/jfkqnh/vs_code_terraform_autoformat_on_save_breaks_if/

The reply by https://www.reddit.com/user/shouperman/ , solved it. I tried changing the value to `"editor.formatOnSaveMode": "file"` . Now autoformatting is working again. Weird huh ?

Regarding your question, No I don't see a **Format Selection* menu when I select the text and right click...

**Comment by jrieken** [comment]
Ok. Thanks for clarifying. Format modified only works if the underlying extension provides a range formatter, not just a document formatter
