### ISSUE TITLE
Go to References does not work on staged files

### ISSUE THREAD

**Issue by ChromeQ** [microsoft/vscode#109144]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Make a file change and stage it in git
2. Right click and choose Go to References on a member of the staged file

Does this issue occur when all extensions are disabled?: Yes

![Peek 2020-10-21 15-48](https://user-images.githubusercontent.com/625203/96845147-171a8600-149c-11eb-94e1-8751a1a20384.gif)

**Comment by joaomoreno** [comment]
That's because it is literally a different document. That document you're seeing only exists virtually, since it can be different from what's on disk. TypeScript doesn't know about it since it only knows about literal files on disk.
