### ISSUE TITLE
Support keyboard shortcut for selecting the launch target

### ISSUE THREAD

**Issue by saveriomiroddi** [microsoft/vscode#109155]
When working a project with multiple launch configurations, sometimes I need to switch between launch configurations.

VSC currently allows configuring keyboard shortcuts for plenty of events, however, it doesn't have (or at least, I couldn't find it - I've searched for `configuration`, `target`, etc.) one for focusing on the launch configuration dropbox.

The request is to add a keyboard shortcut for focusing on the launch configurations dropdown, or something similar, as long as it allows to select a launch configuration via keyboard.

**Comment by saveriomiroddi** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Howto configure serverReadyAction debugwithchrome point to a specific config  (#77843)](https://www.github.com/microsoft/vscode/issues/77843)

I've checked that issue, and they're different, however, I speculate (I don't know the platform) that this issue depends on solving the referenced one.

**Comment by isidorn** [comment]
You can use the "F1 > select and start debugging" command.
However there is no command "Select launch configuration", which would just select it and not start debugging.
I think this is a fair feature request which we currently do not have on the plan but might add in the future

**Comment by saveriomiroddi** [comment]
> You can use the "F1 > select and start debugging" command.
> However there is no command "Select launch configuration", which would just select it and not start debugging.
> I think this is a fair feature request which we currently do not have on the plan but might add in the future

Thanks. That does it well enough! Considering that:

- it's a bindable action,
- it switches the launch configuration,
- switching configuration is something I may do a few times per session, but certainly not every $short_time_interval,

I'm perfectly fine with this solution, so I'd close the issue.

Thanks, and death to (mechanical) mice!

**Comment by isidorn** [comment]
Yeah let's close it. 
Long live non mechanical mice.
