### ISSUE TITLE
Keybinding not working for terminal.focusNextPane or .focusPreviousPane

### ISSUE THREAD

**Issue by metasean** [microsoft/vscode#109195]
**base version**
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**insiders version**
Version: 1.51.0-insider
Commit: 9f7a586124ca121bba906b44eb8356691617957e
Date: 2020-10-22T00:46:08.325Z
Electron: 9.3.2
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Steps to Reproduce:**

Note: I tried a few different variations, including the defaults, none of which worked.  The following only uses two of the variations I tried, one for `focusNextPane` and the other for `focusPreviousPane`.

1. Add the following to `keybindings.json` (user):
```
    {
        "key": "alt+cmd+right",
        "command": "-workbench.action.nextEditor",
        "when": ""
    },
    {
        "key": "alt+cmd+right",
        "command": "-workbench.action.terminal.focusNextPane",
        "when": "terminalFocus && terminalProcessSupported"
    },
    {
        "key": "alt+cmd+right",
        "command": "workbench.action.terminal.focusNextPane",
        "when": "terminalFocus"
    },
    {
        "key": "alt+cmd+left",
        "command": "-workbench.action.previousEditor",
        "when": ""
    },
    {
        "key": "alt+cmd+left",
        "command": "workbench.action.terminal.focusPreviousPane",
        "when": ""
    }
```
2. Open the TERMINAL view (I used `^\``)
3. Open several new terminal panes (e.g. `⌃⇧\`` 2-4 times)
4. Ensure one of the terminals is in focus (e.g. click in the terminal pane)
5. Use the `alt+cmd+right` and `alt+cmd+left` to try and navigate between terminal panes.  
**Expected:** _should_ navigate between terminal panes
**Actual:** does nothing

**Does this issue occur when all extensions are disabled?:**
- Yes
- Also happens in a brand new freshly downloaded version of the "Insiders" version with _only_ the modifications listed above in the "Steps to Reproduce:" section.

**Comment by alexr00** [comment]
@metasean if you run the commands from the command palette do the commands work?

**Comment by metasean** [comment]
@alexr00 - No.  Neither `Terminal: Focus Next Pane` nor `Terminal: Focus Previous Pane` work in either my primary VS Code or the VS Code - Insiders edition.

**Comment by alexr00** [comment]
In that case, the issue appears to be with those commands, not with the keybindings themselves.

**Comment by Tyriar** [comment]
You actually want the `focusNext` and `focusPrevious` commands, the pane ones are referring to side-by-side _split_ panes.
