### ISSUE TITLE
Unable to type characters when they are set a shortcut key

### ISSUE THREAD

**Issue by NightFury5535** [microsoft/vscode#109165]
Issue Type: <b>Bug</b>

installed extension: Turbo console log
Settings -> keyboard shortcut -> search turbo console -> I changed the default key bindings to Z+X,Z+C,Z+V,Z+B.
After that I can't able to type 'Z' in the editor window. It is looking only for the next key combinations.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (5.13GB free)|
|Process Argv|--crash-reporter-id 8a96f376-a54c-450c-a17e-e8075f5ad7e3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
ng-template|Ang|0.1001.0
angulardoc-vscode|Ang|6.1.3
turbo-console-log|Cha|1.4.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|4.5.0
split-html-attributes|dan|1.0.10
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.2
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.1
auto-close-tag|for|0.5.9
NgRxSnippets|har|9.1.0
beautify|Hoo|1.5.0
angular-file-changer|joh|0.0.4
Angular2|joh|9.1.2
Angular-BeastCode|Mik|10.0.3
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-next|ms-|4.1.20201021
debugger-for-chrome|msj|4.12.11
angular-console|nrw|14.0.1
angular-component-extension|oni|0.0.14
material-icon-theme|PKi|4.3.0
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
autoimport|ste|1.5.3
tabnine-vscode|Tab|3.0.3
bootstrap4-vscode|the|6.1.0
errorlens|use|3.2.3
highlight-matching-tag|vin|0.10.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.9.3

(4 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
To remove the bad keybindings, you can open your `keybindings.json` via `F1 > Open Keyboard Shortcuts (JSON)` and delete them from there.

**Comment by NightFury5535** [comment]
Hi Alex,
I was allowed to set only the alphabets for the shortcuts. If keep like this please refer the below image. I was unable to type the fist letter of the shortcut. In my case 'Z'.
![image](https://user-images.githubusercontent.com/58245775/96962429-61dfe080-1524-11eb-986b-8b45a2fca0d0.png)

**Comment by alexdima** [comment]
@NightFury5535 VS Code allows powerful customizations. In this case, you have customized VS Code and instructed it via a custom keybinding that you want <kbd>Z</kbd> to not type the letter `z`, but that you want it to enter a chord. Please remove your keybinding if that is not your intent.
