### ISSUE TITLE
Emmet combine "Wrap Individual Lines with Abbreviation" and "Wrap with Abbreviation" commands

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#109191]
From #54711, users such as @emilime, @contentfree, and @Yensan expressed that it is confusing how VS Code has both "Wrap Individual Lines with Abbreviation" and "Wrap with Abbreviation" commands.

Therefore, my plan is to merge the two commands into a single "Wrap with Abbreviation" command. I noticed that other editors do that anyway. In fact, I'm not even sure why VS Code requires two commands if there's the option to use the Emmet `*` operator.

**If you don't like the idea of merging these two commands into one, give this issue a thumbs down and/or comment why.
Otherwise, it is going to be part of the November or December milestone†**.

†Depending on how well the VS Code migration to the latest Emmet (v2.1.5 at this time of writing) is going.

Edit: The new "Wrap with Abbreviation" command will work in a similar way to the current "Wrap Individual Lines with Abbreviation" command, but with several bugfixes (see https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3Aemmet-revamp+).

**Comment by Tyriar** [comment]
The emmet website itself also exposes it as a single command fyi https://docs.emmet.io/actions/wrap-with-abbreviation/

**Comment by jeanp413** [comment]
Created a PR #116603 fixing this
