### ISSUE TITLE
List and info box missing in Playground

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#109149]
Issue Type: <b>Bug</b>

Current:
![image](https://user-images.githubusercontent.com/9205389/96853348-866f8600-145a-11eb-80bc-e8dde95d644e.png)

Previous (1.50):
![image](https://user-images.githubusercontent.com/9205389/96853501-b880e800-145a-11eb-9000-5cd77d324e73.png)

VS Code version: Code - Insiders 1.51.0-insider (9f7a586124ca121bba906b44eb8356691617957e, 2020-10-22T00:46:08.325Z)
OS version: Darwin x64 19.6.0

**Comment by chrmarti** [comment]
Other sections have the same issues.

**Comment by jrieken** [comment]
@chrmarti What is "info box"?

**Comment by chrmarti** [comment]
@jrieken The last box in the second screenshot
