### ISSUE TITLE
Terminal issuse

### ISSUE THREAD

**Issue by wedderburn95** [microsoft/vscode#109198]
Issue Type: <b>Bug</b>

I am unable to use the terminal. When I click on the new terminal it's blank nothing happens. I was able to use it yesturday with no problems. What should I do?

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.71GB (2.53GB free)|
|Process Argv|--crash-reporter-id 242d1c42-8278-4630-a92b-26a51b190829|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.50.1
ruby|reb|0.27.0
vscode-ruby|win|0.27.0

</details>

**Comment by Tyriar** [comment]
Please follow https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch to try diagnose and provide some more information on the issue.
