### ISSUE TITLE
Intelisence stopped working

### ISSUE THREAD

**Issue by HarelM** [microsoft/vscode#109186]
Issue Type: <b>Bug</b>

I'm pressing ctrl+space on a windows machine with a c# solution, in a file to get intellicense and it doesn't work.
It used to work before the upgrade I think. much like many other things that stopped working after the last update (September 2020).
I have decided to bail on using VS code although I need to develop on both a windows machine and a mac. I should probably bail on .net as well as nothing seems to be working as expected... just a horrible user experience lately...

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.30GB free)|
|Process Argv|--folder-uri file:///d%3A/Github/IsraelHikingMap/Site --crash-reporter-id 06829eee-fb6c-491a-8e5c-5c1389ded2d4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dotnet-test-explorer|for|0.7.4
vscode-pull-request-github|Git|0.20.1
vscode-docker|ms-|1.7.0
csharp|ms-|1.23.4
remote-wsl|ms-|0.50.1
powershell|ms-|2020.6.0

</details>

**Comment by mjbvz** [comment]
VS Code does not provide built-in c# support. Please file this against the c# extension 

/extC#
