### ISSUE TITLE
Disable Keychain access prompt?

### ISSUE THREAD

**Issue by jsumners** [microsoft/vscode#109162]
What setting in VSCode needs to be toggled to prevent it from asking for Keychain access? There is no reason for VSCode to access my Keychain.

![image](https://user-images.githubusercontent.com/321201/96875979-da23a480-1445-11eb-8fa2-33a186eba2b7.png)

**Comment by RMacfarlane** [comment]
Please see https://github.com/microsoft/vscode/issues/108342#issuecomment-706340396 for an explanation of why this is happening. At some point in a previous version of VS Code, you likely logged into an extension that stored something into the keychain. You can delete "VS Code Account" from the keychain if you don't want to be prompted again.
