### ISSUE TITLE
Introduce a built-in theme for proton color blind people

### ISSUE THREAD

**Issue by Huayra-J** [microsoft/vscode#109132]
Issue Type: <b>Feature Request</b>

Please consider 8% of the population who have colour blindness, thanks!

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
We always try to consider all our users. We always try to respect the color contrast required for items to be visiually distinguishable for all users.
Do you maybe have exact examples of where we are not using colors correctly? That would help us a lot for improving in this area, otherwise this issue is too general and we can not create any actionable items from it.

Thanks

**Comment by Huayra-J** [comment]
Thanks for your reply! There are many built-in colour themes which is great, however there is no colour theme for Proton colour blind people. It would be great to have a colour theme for at least proton colour blind people as this is the most common colour blindness (as a very popular settings in games). Thanks again for the support.

**Comment by isidorn** [comment]
Ok, thank you for clarifying. So let me rename this issue.
I will add a help wanted as we would like to see an extension theme that introduces theme for this. If that extension proves to be very good we will consider to add it to VS Code.

**Comment by PedroFonsecaDEV** [comment]
@Huayra-J 
Could you please provide us:
1) A screenshot using the theme you would like to be improved with the colours that need to be replaced circled? 
Thanks.

**Comment by tamuratak** [comment]
>  proton color blind

`proton` seems to be a typo, although I am not an expert. See https://en.wikipedia.org/wiki/Color_blindness#Classification

**Comment by PedroFonsecaDEV** [comment]
Guys I worked on a theme for color blindness developers. 

https://marketplace.visualstudio.com/items?itemName=PedroFonsecaDEV.dark-plus-colorblind&ssr=false

**Comment by isidorn** [comment]
@PedroFonsecaDEV great, thanks for working on this!
Would be great if @Huayra-J tries it out and if it works for him we can close this one.
