### ISSUE TITLE
Clicking code action in "F8" popup doesn't refresh code fix actions/close dialog = possibility of duplicate actions

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#10912]
- VSCode Version: 1.4
- OS Version: Windows 10

I've implemented a code fix provider but hit a bit of a snag. Assume the following code:

```dart
myFunc() {
  myFun(); // <-- Typo
}
```

I get a code fix here that says "change `myFun()` to `myFunc()`" and provides an edit which inserts a `c` at the correct position.

If I click the lightbulb and apply it, everything is fine; the change is applied, the menu closes.

However, if I hit `F8` and click the link in the popup:

![Code action](https://cloud.githubusercontent.com/assets/1078012/17945949/fc2471d8-6a3d-11e6-9b03-2b1f97230121.png)

The edit is applied (I'm doing this via `workspace.applyEdit()` in a command) but the link remains on the screen. This means you can click it a second time and it inserts a second `c` (and a third...).

Now, I could keep track of this by mutating the source edit object and refusing to apply it a second time; but it seems to me that Code should do something here; either re-request code-fixes for this location or close the popup when it's applied?

(It's possible it already should do something like this and I've implemented something incorrectly; but I've been struggling to find it, and I can't find any good examples of others that have already implemented this properly to step through).

**Comment by DanTup** [comment]
Related: If I hit F8 to open this window, then type some changes in the editor, then clicking the link applies a stale code fix, which means nothing matches up.

Note: My language service can only provide fixes for a single point (not a range), so there's a chance that's the cause of this (eg. I always have to take the start of the Range code gives me and drop the rest), though I'm not sure?

**Comment by jrieken** [comment]
It's by design that the widget doesn't update when the markers change. We figured it's too noisy otherwise. Also what should really happen? Close? Jump to next/prev marker? However those decisions were made *before* we added the quick fixes to the widget. I see how those should reconcile when the document changes.

**Comment by DanTup** [comment]
@jrieken Am I right in thinking I can test this in Insiders from tomorrow?

**Comment by jrieken** [comment]
yep. we now listen to marker updates. If the F8 windows still shows at a marker we reconcile the quick fixes, else we hide quick fixes. Also the border changes. Like so:

![aug-26-2016 15-26-23](https://cloud.githubusercontent.com/assets/1794099/18006760/7c55e058-6ba1-11e6-8bb7-10ba2076c5ed.gif)

**Comment by jrieken** [comment]
So, it is important to update the diagnostics (since that is driving quick fixes). My sample code goes like this 

```
    const diag = vscode.languages.createDiagnosticCollection();

    vscode.commands.registerCommand('extension.sayHello', function (range) {
        // console.log(range, arguments);
        diag.forEach((uri, all) => {
            let rest = all.filter(d => !d.range.isEqual(range));
            diag.set(uri, rest);
        })
    });

    vscode.workspace.onDidChangeTextDocument(e => {
        if (e.document.languageId === 'abc') {
            
            const d: vscode.Diagnostic[] = [];
            const text = e.document.getText();
            let idx: number;
            while ((idx = text.indexOf('abc', idx)) >= 0) {
                let range = e.document.getWordRangeAtPosition(e.document.positionAt(idx));
                if (range) {
                    let len = d.push(new vscode.Diagnostic(range, 'I am an error diagnostic'));
                    d[len - 1].code = 42;
                }

                idx += 3;
            }

            diag.set(e.document.uri, d);
        }
    });

    vscode.languages.registerCodeActionsProvider('abc', {
        provideCodeActions(doc, range, ctx) {
            const result: vscode.Command[] = [];
            ctx.diagnostics.some(d => {
                if (d.code === 42) {
                    result.push({
                        title: 'Remove this error...',
                        command: 'extension.sayHello',
                        arguments: [d.range]
                    })
                    return true;
                }
            });
            return result;
        }
    })

```

**Comment by DanTup** [comment]
Excellent, thanks! Our document edits will automatically trigger re-calculation of diagnostics so they'll be updated as new ones arrive/we're told to clear them.

I'll give it a test tomorrow and ensure it's all working together. Thanks again! :+1:  :smile:

**Comment by DanTup** [comment]
@jrieken After playing with this, I think still having the diagnostic text hang around even though it's been fixed (the squiggle gone and gone from problems list) is a bit confusing; it looks like a bug that the error wasn't cleared (it references a misspelled call that doesn't exist anymore).

![Code fix](https://cloud.githubusercontent.com/assets/1078012/18052011/e0216eea-6def-11e6-870e-3b93ccbed9dc.gif)

I'm not sure it would be all that bad hiding the popup if the diagnostic gets removed?

**Comment by DanTup** [comment]
@jrieken Sorta-related, if the diagnostic gets replaced (eg. the text changes because you edit the document) it also doesn't update, so you end up with an incorrectly-worded diagnostic in the popup.

See here, I edit the doc so that `mai` is `mi` and the diagnostic in the problems window updates, but not the popup.

![Code fix update](https://cloud.githubusercontent.com/assets/1078012/18052295/6c316d12-6df1-11e6-834b-cdb80f166652.gif)

btw, the lightbulb/`Ctrl+.` feature and this popup seem to be almost entirely the same (except the popup shows the diagnostic text); seems a bit strange to have two features that are so similar?

**Comment by DanTup** [comment]
@jrieken Sorry for all the comments! Also noticed that when you have this popup open, any keypress seems to remove focus from the editor, so it's impossible to edit the document (first keypress works, further keypresses do not)!

**Comment by aeschli** [comment]
Verified that the errors go away in the F8 widget when apply a quick fix.

@DanTup I suggest you file all follow-up items as separate issues.

**Comment by DanTup** [comment]
I've raised new issues; I'll try to avoid tagging related things on to the end in future and just create new cases. Btw, this functionality is awesome when working; thanks! :+1:
