### ISSUE TITLE
No Application Launcher entry of Visual Studio Code in Kubuntu if installed via Snap

### ISSUE THREAD

**Issue by tamulis** [microsoft/vscode#109118]
- VSCode Version: Snapcraft: latest/stable | d2e414d9 | 14 October 2020
- OS Version: Kubuntu 20.04

The only way to launch VS Code when installed as Snap is through command line.

Steps to Reproduce:

1. Install vscode via snap (command line or through Discover app).
2. No shortcut is created in Application Launcher.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@tamulis  Other snap applications work fine?
