### ISSUE TITLE
TS file not save

### ISSUE THREAD

**Issue by KinjalDodiyaTechifysolutions** [microsoft/vscode#109153]
Saving 'Type.js': Running 'TypeScript and JavaScript Language Features' Formatter (configure).

**Comment by KinjalDodiyaTechifysolutions** [comment]
Issue Type: <b>Bug</b>

Saving 'ProductDetailsEdit.js': Running 'TypeScript and JavaScript Language Features' Formatter (configure).

Extension version: 1.3.1
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470T CPU @ 2.90GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|19.44GB (5.25GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id b9d4618b-de96-4f8a-9f07-2eeb4e3e6996|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|Lubuntu|
|XDG_CURRENT_DESKTOP|LXQt|
|XDG_SESSION_DESKTOP|Lubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by mjbvz** [comment]
Please provide steps to reproduce.

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
