### ISSUE TITLE
Emmet preview leaves in backslashes until enter pressed for wrap to abbrev

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#109177]
Version: 1.51.0-insider
Commit: 076245b1ce18bc0c262bb287b3fcad1575d756ae
Date: 2020-10-14T19:02:31.672Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36 Edg/86.0.622.48

Steps to Reproduce:

1. Type `test$` into the editor and select those characters
2. Run command 'Emmet: Wrap with Abbreviation' OR 'Emmet: Wrap Individual Lines with Abbreviation'
3. Type `span`
4. The preview text shows `<span>test\$</span>`, but after enter is pressed, it shows the *correct* wrapping `<span>test$</span>`.

Expected behaviour:
The preview text shows `<span>test$</span>` even before enter is pressed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by 3sne** [comment]
Looks like the escape on `$` originates from [`vscode-emmet-helper`](https://github.com/microsoft/vscode-emmet-helper) module code-base. Not sure how to approach the fix.

https://github.com/microsoft/vscode/blob/1e0df6a4aca46c351bbf38faf58e77e8342d220a/extensions/emmet/src/abbreviationActions.ts#L682-L685

**Comment by rzhao271** [comment]
@3sne yep, I think that's because VS Code uses its own snippets too, though.
The fix probably involves a similar replace call as you linked in `abbreviationActions.ts` there.

**Comment by rzhao271** [comment]
Verifier:

1. Type `test$` into an html file and select those characters
2. Run command 'Emmet: Wrap with Abbreviation' OR 'Emmet: Wrap Individual Lines with Abbreviation'
3. Type `span`
4. Verify the preview text shows `<span>test$</span>` and after enter is pressed, verify it still shows `<span>test$</span>`.
