### ISSUE TITLE
Right align "Dismiss" X button in search result entry list

### ISSUE THREAD

**Issue by sleutho** [microsoft/vscode#109179]
Could we right align the Dismiss "X" of individual lines in the search? I often search for things and start dismissing items in that list that are not of interest. However, the X is always in another place, which makes this difficult. If it were right aligned, I could always click in the same place to dismiss items.
I think it was right aligned a few years ago but somehow got removed.

Thanks for considering this.
Regards

**Comment by roblourens** [comment]
You want to set `"search.actionsPosition": "right"`. I am considering making this the default
