### ISSUE TITLE
Codelens should pick up `editor.gotoLocation.multipleReferences` setting

### ISSUE THREAD

**Issue by steadicat** [microsoft/vscode#109194]
- VSCode Version:  1.50.1
- OS Version: Mac OS 10.15.6

Steps to Reproduce:

1. Set `"editor.gotoLocation.multipleReferences": "goto"` in your preferences
2. Click on a reference codelens
3. Observe that a “peek” keyhole opens up, instead of going to the first result and opening the list of references in the sidebar, as it used to be

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
I don't think we ever did this. You can choose between peek and stable view but not navigation. @steadicat What makes you think this "stopped" working?

**Comment by steadicat** [comment]
I'm pretty sure it worked. I used to rely on that pretty heavily. I can't prove it though. :(
