### ISSUE TITLE
TypeScript import suggestions suggests third party modules before modules in current project

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/vscode#109173]
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20241

Steps to Reproduce:

1. Use a value that could be imported
2. See VScode suggestions

See screenshot: 

![image](https://user-images.githubusercontent.com/172594/96898525-b84b1180-1487-11eb-8333-be27a715e4e2.png)

`Entities/User` is part of the current project. `aws-sdk` is not. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mikemaccana** [comment]
Hi @vscodebot this isn't a dupe of that issue.

**Comment by mikemaccana** [comment]
Hi Bot! It looks like I can't talk to you (mentioning 'at vscodebot' is someone else) but this isn't a dupe of that issue.

**Comment by mjbvz** [comment]
Can you please share a minimal project that demonstrates this issue
