### ISSUE TITLE
Getting prort forwarding dialog when running my tests

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#109143]
I have browser test written using playwright. Since lately I get a popup now about port 8080 being forwarded when running these test. It doesn't necessarily make sense to forward this port in this scenario.

<img width="350" alt="capture" src="https://user-images.githubusercontent.com/1931590/96844414-c54c0e80-144f-11eb-8f8c-67232cb7b839.png">

**Comment by alexr00** [comment]
We can't tell the difference between this port that shouldn't be forwarded and ports that should be forwarded. Would a setting to exclude 8080 help? There is also a setting to disable the feature entirely. Alternatively, you can use the gear icon in the notification to "never show again", which will still forward the port but you won't see the notification.

**Comment by dbaeumer** [comment]
Thanks for the explanation. Will use the gear icon.
