### ISSUE TITLE
Add ability to hide outputs in Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#109104]
Request for ability to hide output from notebooks.

Currently in the Python implementation of Notebooks, we have output that are hidden.

* Today these are neither displayed in our old Python Notebooks nor in Jupyter
* As far as I can tell, most of these outputs end up as Rich Displays, containing an object with a single key. However no real data for display purposes.
* The outputs are not displayed, however they are persisted on disck (i.e. they are part of the ipynb content).

Adding an issue for what was discussed (forgot to add this issue last week).
@rebornix /cc

**Comment by RMacfarlane** [comment]
@rebornix What's a good way to verify this change?

**Comment by DonJayamanne** [comment]
@DonJayamanne to provide logic for hiding empty ipywidget output.

**Comment by DonJayamanne** [comment]
@rebornix Unfortunately the logic for rendering a widget is in the widget manager.
Here's the sample code:
```python 
import nglview
view = nglview.show_pdbid("3pqr")
view
```

When we run this we get two outputs with almost identical data, but with different model_ids, see below:
```
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "d2fc10942d3e4a0d93f055c7f85bdf5d",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": ""
     },
     "metadata": {
      "transient": {}
     },
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "bfc1da481100435990053406e1c8348f",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": "NGLWidget()"
     },
     "metadata": {
      "transient": {}
     },
     "output_type": "display_data"
    }
   ],
```

Unfortunately, only the widget manager knows which one needs to be hidden.
Basically we query the widget manager to see if it has any views to be rendered for the provided model_id. If there isn't any view associated with the model_id, then we don't render it.

With the renderer architecture, the only way to determine whether a cell needs to be rendered or not can only be provided by the renderer.

Finally, the renderer doesn't render the output immediately.
Just because the renderer was asked to render an output for model_id = xyz doesn't mean it will render the output immediately. This is all asynchronous.

**Comment by rebornix** [comment]
@DonJayamanne I guess we can have a workaround for this by doing:

* When we see a two mimetype output (pretty common in Jupyter), one is custom mimtype, which will be rendered in the webview, another one is `text/plain`, which will be rendered by VS Code itself. If the custom mimetype rendered in the webview has height of zero and the `text/plain` mimetype is empty string, we then not preserve any whitespace in the output container and will also hide the mimetype switcher.
  * We can even limit this behavior to `application/vnd.jupyter.widget-view+json`/`text/plain` mimetype bundle only

**Comment by DonJayamanne** [comment]
Sure, but my concern is if there are two legitimate outputs then VSCode might end up removing the padding.
Because VS Code code will probably run before the renderer code (renderer code is async & needs to wait for the data to come through from kernel into the widget manager). 
Hence possible that VS Code will assume the output is empty (0 height) & remove the padding & after that the widget manager renders the output.

**Comment by rebornix** [comment]
> Hence possible that VS Code will assume the output is empty (0 height) & remove the padding & after that the widget manager renders the output.

When this happens, we will automatically bring back the padding, it has a listener to the content height change. Does this fix the problem?

**Comment by amunger** [comment]
I think this was fixed along with https://github.com/microsoft/vscode/issues/214886, though that never got verified.
Empty outputs should be combined into a single output
