### ISSUE TITLE
Shortcuts don't work properly while using Python Notebook

### ISSUE THREAD

**Issue by ellizonn** [microsoft/vscode#109172]
Issue Type: <b>Bug</b>

Dear developers, unfortunately when I'm working on some Python Notebooks ("file.ipynb") I have troubles using all shortcuts. From cmd+O to open files, ctrl+tab to switch notebooks, shift+cmd+P to command palette, and many others. Sometimes the shortcut works, but really few times. Usually I try several times the shortcut and nothing happen.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 3|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 3cd63675-bb48-4f5c-8fb6-ebf2ed913c56|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
theme-monokai-pro-vscode|mon|1.1.17
python|ms-|2020.9.114305
cpptools|ms-|1.1.0-insiders2
java|red|0.69.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.25.0
vscode-maven|vsc|0.25.0

</details>

**Comment by ellizonn** [comment]
> /extPython

Sorry? I don't get it, what do you mean?

**Comment by rebornix** [comment]
@ellizonn I was calling our `bot` to label this issue as "caused-by-extension". This is an issue with the Python extension which provides notebook experience for now, please file against them. Thanks!

**Comment by ellizonn** [comment]
> @ellizonn I was calling our `bot` to label this issue as "caused-by-extension". This is an issue with the Python extension which provides notebook experience for now, please file against them. Thanks!

Thanks to you!
