### ISSUE TITLE
Can't run some tasks in web UI

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#109122]
- Launch local web ui with server (`./resources/server/web.sh`)
- Open the vscode folder
- Run an npm or gulp task
- Get a "not implemented" error

![image](https://user-images.githubusercontent.com/323878/96807520-a3a94380-13cb-11eb-8ebf-66b299d6f748.png)

Shouldn't this stuff be running in the workspace extension host? I have working terminals and can build there. A "shell" type task works.

**Comment by alexr00** [comment]
Yes, this should be using the workspace extension host. Fixed by 0eda23e1122b9d6b863be9962d4d9f020276220d
