### ISSUE TITLE
could support open command terminal in new window!

### ISSUE THREAD

**Issue by Georege** [microsoft/vscode#109126]
command running terminal in zhe default window is so small, so open command runing in new windows is need！

**Comment by Tyriar** [comment]
Looks like you're after https://github.com/microsoft/vscode/issues/10121

Note that there is a button/command to maximize the terminal as a workaround:

![image](https://user-images.githubusercontent.com/2193314/97746769-23a86b00-1aa8-11eb-81ca-385514dc4219.png)
