### ISSUE TITLE
Allow terminal launch path to be set via integrated terminal API

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#10917]

**Comment by guogaigai** [comment]
thanks for your reply firstly ,  then when will this API release ? @Tyriar

**Comment by Tyriar** [comment]
@guogaigai v1.5.0 is the plan

**Comment by guogaigai** [comment]
ok ,thank you very much@Tyriar

**Comment by daviwil** [comment]
Looks like there's been a commit to enable this but I only see the terminal's path being added as a parameter.  Could you also add a parameter for arguments to send to the terminal app?  I know it may not work in Windows but it'd be helpful to not have to use hacks for all 3 platforms :)

**Comment by Tyriar** [comment]
That's coming as well, good eye though :smiley:

**Comment by daviwil** [comment]
Perfect!  Any chance the arguments will also work on Windows?  I remember you telling me that there was a bug in the library you're using for terminal support

**Comment by Tyriar** [comment]
@daviwil #8429 I marked it as upstream/help wanted, the problem likely lies in https://github.com/chjj/pty.js/issues/137, either a coding error or the version of winpty it uses it too old.

**Comment by daviwil** [comment]
Yep,  I was going to use the batch file approach as discussed in #8429 if the arguments still didn't work.  Any chance we could temporarily fork one (or both) of your dependencies to fix the problem in the short term until the project maintainers get to it?

**Comment by Tyriar** [comment]
It's already forked to https://github.com/Tyriar/pty.js in order to fix some cross-platform build issues. The project is mostly unmaintained now though so I have doubts of being able to upstream any fixes.

**Comment by daviwil** [comment]
One of these days I might get a few moments to help get it fixed then.  Depends on how painful it is for me to launch PowerShell using a batch file that has to be updated for each execution :)

**Comment by Tyriar** [comment]
Reopening to add shellArgs

**Comment by Tyriar** [comment]
Reopening to add path/shellargs usage example to https://github.com/Microsoft/vscode-extension-samples

**Comment by Tyriar** [comment]
An example using the new API is up on the sample repository https://github.com/Microsoft/vscode-extension-samples/commit/94cd47f3c16d8a9b4fbef2ec2ef48abdaa92635d

**Comment by daviwil** [comment]
Awesome, thanks a lot!
