### ISSUE TITLE
yarn web error Error: connect ECONNREFUSED 0.0.0.0:443

### ISSUE THREAD

**Issue by pre1ude** [microsoft/vscode#109123]
I can't run yarn web to see the vscode running in the browser, with error: connect ECONNREFUSED 0.0.0.0:443

Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:01:33.073Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic snap

Steps to Reproduce:

1. clone the vscode repository and in the master branch
2. yarn
3. yarn compile-web
4. yarn web

Does this issue occur when all extensions are disabled?: Yes

```sh
> yarn web
yarn run v1.22.5
$ node resources/web/code-web.js
Web UI available at           http://localhost:8080
Secondary server available at http://localhost:8081
internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 443,
  attempts: 5
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by pre1ude** [comment]
It's my network problem, when downloading the "vscode-playground" thing

**Comment by huigs** [comment]
@pre1ude I met the same issue when yarn web, could you help to inform em how did you solve it ? thx a lot
