### ISSUE TITLE
Quick file find, or jump to file in explorer by typing filename

### ISSUE THREAD

**Issue by dougrosenfeld** [Microsoft/vscode#10910]
- VSCode Version:
- OS Version:

We are literally working with thousands of files. Currently the user is limited to a mouse scrolling through a large folder structure to find the file and manually selecting the file.

We kindly request that finding files in the Explorer be easier. The Windows Explorer is a parallel example.

For example, provide a box where you can start typing in the file name and the Explorer is limited to showing files that match. Please support wild cards.

For example, allow typing in the Explorer to jump to a file.

**Comment by sandy081** [comment]
Duplicates #10026
