### ISSUE TITLE
Cancel GitHub sign in

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#109101]
Issue Type: <b>Bug</b>

1. Start sign in process to GitHub
2. Close resulting browser window

There is no current gesture to cancel the sign in flow, there should be a way to remove the "Signing in to github.com"  status bar item, perhaps by clicking this and then dismissing the quick pick

VS Code version: Code - Insiders 1.51.0-insider (6c8c6008ef9d86e46b086a00f273b1fee5bd8c51, 2020-10-21T05:33:56.950Z)
OS version: Darwin x64 18.7.0

**Comment by rzhao271** [comment]
Just to double-check:
If I close the browser window, then click on the status bar item, then dismiss the quick pick, the sign-in process is cancelled. Is that the new flow?
I notice on the stable version that after dismissing the quick pick, the status bar item remains.

**Comment by RMacfarlane** [comment]
Yes, thanks for checking, that's correct! The status bar item should be removed
