### ISSUE TITLE
TypeScript extension not working

### ISSUE THREAD

**Issue by victor-cui-discovery** [microsoft/vscode#109103]
Issue Type: <b>Bug</b>

Typescript extension doesn't seem to be working. No longer see auto-completion o r going to a function definition by clicking on the function.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|32.00GB (3.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
go|gol|0.17.2
plantuml|jeb|2.13.14
vscode-docker|ms-|1.6.0
vim|vsc|1.17.1
vscode-proto3|zxh|0.5.2

</details>

**Comment by mjbvz** [comment]
Also you are on an old VS code version, have you tried with 1.50+?
