### ISSUE TITLE
SCSS Attribute Selector Syntax Highlighting Broken

### ISSUE THREAD

**Issue by alan-pie** [microsoft/vscode#109247]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

For code like this
```
.position-metadata li[data-type="team"] {
  background-image: image-url("team-icon.svg");
}
```

The text 'team' should be highlighted as a string but is not.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|66, 53, 27|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|. --crash-reporter-id 3f419053-17d7-4526-9fc2-e9eddee9554a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.8.4
vscode-intelephense-client|bme|1.5.4
vscode-markdownlint|Dav|0.37.1
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
vscode-rufo|mbe|0.2.1
vscode-docker|ms-|1.7.0
vetur|oct|0.28.0
vscode-jest|Ort|3.2.0
ruby|reb|0.27.0
vscode-yaml|red|0.11.1
vscode-sort-json|ric|1.18.1
vscode-ruby|win|0.27.0

</details>

<img width="444" alt="Screen Shot 2020-10-23 at 9 04 12 AM" src="https://user-images.githubusercontent.com/65185890/97026859-cd1eb800-150e-11eb-8af6-5db00898911c.png">

**Comment by alexr00** [comment]
Copied to the repository where our SCSS syntax highlighting grammar comes from: https://github.com/atom/language-sass/issues/280
