### ISSUE TITLE
html文件编辑代码提示不完善

### ISSUE THREAD

**Issue by DreamElapse** [Microsoft/vscode#10926]
- VSCode Version: 1.4.0

Steps to Reproduce:

1. 在thml文件内，用内嵌式css的情况下，css样式无代码提示并且用tab快捷键生成的css样式通常不是常用的和通用的样式

**Comment by sandy081** [comment]
@DreamElapse Can you please provide Summary and description of the issue and steps to reproduce in English.

Thanks.

**Comment by dbaeumer** [comment]
Closing. Haven't received any response. @DreamElapse please ping if the issue is still reproducible with steps that demo the problematic behavior.
