### ISSUE TITLE
Cursor disappears briefly before starting blinking animation.

### ISSUE THREAD

**Issue by JoeWinger** [Microsoft/vscode#10922]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1. Change the "editor.cursorBlinking" setting to either "smooth," "phase," or "expand."
2. Move cursor either with mouse or arrow keys.

The cursor briefly vanishes (as if it's starting the "blink" animation,) then immediately starts the defined animation.

**Comment by alexandrudima** [comment]
Relevant animations in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/viewCursors/viewCursors.css#L59 

PR welcome

**Comment by alexandrudima** [comment]
Just merged in the PR from @sprinkle131313 . Thank you @sprinkle131313  !
