### ISSUE TITLE
Terminal crash with code 1

### ISSUE THREAD

**Issue by Kran001** [Microsoft/vscode#10920]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
@Kran001 Can you please provide the steps needed to reproduce this crash?

**Comment by Kran001** [comment]
Im just click Focus new terminal, and my VS code give me error with code 1.
I have been doing it with admin privileges, and none. Results was equals.

2016-08-25 13:39 GMT+03:00 Sandeep Somavarapu <notifications@github.com>:

**Comment by sandy081** [comment]
@Kran001 Can you let us know if you have any special terminal settings?

**Comment by Kran001** [comment]
At begin, i have not special terminal settings, this error have been. I
restart my PC, and reinstall code editor, but don't be better. I change
terminal settings to Git-Bash terminal, VS Code have not reacting.
I have special settings just snippets.

2016-08-25 16:42 GMT+03:00 Sandeep Somavarapu <notifications@github.com>:

**Comment by Kran001** [comment]
Please, try to fix that. i very like this editor, and i want to use him
everyday, and when i was on linux i have been doing it. I can't to do this
now.

2016-08-25 23:09 GMT+03:00 Александр Кран <fedorandsanya@gmail.com>:

**Comment by sandy081** [comment]
@Tyriar Are you aware of any such terminal crashes?

**Comment by Tyriar** [comment]
This is common when the path is incorrect to your shell. Make sure the path to git bash is correct, there are some instructions here to help https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration
