### ISSUE TITLE
How to determine if a Terminal created using new API has been closed by the user?

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#10925]
- VSCode Version: Insider Build

I'm using the [code sample](https://github.com/Tyriar/vscode-terminal-api-example) put together by @Tyriar 

Steps to Reproduce:

1. Run the above sample  
2. Create a terminal using the new API  
3. Send text to this new terminal  
4. Close the new terminal using the icon on the top right of the terminal panel  
(NOTE: Terminal has now been disposed, but extension is not aware of this) 
5. Next try to send text to previously created terminal (_**that no longer exists**_)  
A new terminal window is opened.  

Is it possible for the extension to be notified of the fact that the terminal has been closed? 
Either via: 
  + A callback (method or event) 
  + Or extension needs to be able to query this

**Comment by Tyriar** [comment]
@jrieken what's the common/recommended way of communicating this sort of event via the API?

**Comment by jrieken** [comment]
We do this with the global events ala `window.onDidCloseTerminal` like this [active editor event](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3321). 

@Tyriar On question regarding `hide` vs `dispose`. Are they the same? So when hiding a terminal its like killing it? Iff so we should revisit the API around that and remove either hide or dispose.

**Comment by Tyriar** [comment]
@jrieken I should flesh this out in the jsdoc if it wasn't clear, but hide will close the panel if that terminal is currently active, dispose kills the terminal but keeps the panel up.

**Comment by jrieken** [comment]
> Close the new terminal using the icon on the top right of the terminal panel
(NOTE: Terminal has now been disposed, but extension is not aware of this)

@Tyriar I am a little confused because of that. I assume that is the same as calling `hide` where `ctrl+c` is like `dispose`

**Comment by Tyriar** [comment]
The `workbench.action.terminal.kill` command (bin icon) will kill the terminal instance, currently the API only goes one way so an API terminal does not know that a terminal has been disposed via the command. I'll look into making an `window.onDidCloseTerminal` similar to https://github.com/Microsoft/vscode/blob/1f412b5a1e52c661eb60f203fbdc43507430d5df/src/vs/vscode.d.ts#L3321

**Comment by DonJayamanne** [comment]
@Tyriar , will the proposed ```window.onDidCloseTerminal``` be available in the next version (1.5) of VS Code or is this something that would probably be added in a subsequent build? 
If it is planned for a later version, then I can work around this without having to wait for it.

**Comment by Tyriar** [comment]
@DonJayamanne looking at this for 1.6

**Comment by DonJayamanne** [comment]
@Tyriar , thanks

**Comment by daviwil** [comment]
Awesome, nice work!

**Comment by Tyriar** [comment]
This will land in tomorrow's insiders. Note that currently the event will only fire for terminals created with the API. This can be easily be changed in a backwards compatible way to include all terminals if an `window.onDidOpenTerminal` is added.

It should fire when terminals are closed both through the API and through user interaction (command, button).

**Comment by jrieken** [comment]
@Tyriar What is the definition of close? kill/dispose or not visible anymore?

**Comment by Tyriar** [comment]
@jrieken kill/dispose,  I'd prefer to name this `onDidDisoseTerminal` to be consistent.

**Comment by jrieken** [comment]
👎 We already have this and it is also about disposing 

```ts
		/**
		 * An event that is emitted when a [text document](#TextDocument) is disposed.
		 */
		export const onDidCloseTextDocument: Event<TextDocument>;
```

**Comment by Tyriar** [comment]
So just improve the jsdoc that it's about disposing, not hiding?

**Comment by Tyriar** [comment]
Also `onDidCloseTextDocument` is a little different isn't it? Dispose on that could indicate deleting the file.

**Comment by Tyriar** [comment]
Changed close to dispose in the jsdoc, reopen if there's anything else you think should change.

**Comment by jrieken** [comment]
lgtm
