### ISSUE TITLE
launch.json preLaunchTask fails linking, but build task is ok

### ISSUE THREAD

**Issue by rikerfi** [microsoft/vscode#109291]
Issue Type: <b>Bug</b>

Run build task produces executable just fine. However, when starting debugging build  preLaunchTask fails. It seem to be problem with linking. Might be that -lm parameter is not handled well in case of pre-launch. This is indicated with similar result if leaving -lm parameter out of build i.e. making build task fail.

If commenting out the preLaunchTask from launch.json then run debug and run without debugging are successful.

Here is output, where the first is build task (successful) and the second is launch (fail preLaunchTask).

```
> Executing task: C/C++: gcc build active file <
Starting build...
Build finished successfully.
Terminal will be reused by tasks, press any key to close it.

> Executing task: C/C++: gcc build active file <
Starting build...
Build finished with error:
/usr/bin/ld: /tmp/ccGpbaep.o: in function `BusyWork':/tryouts/thtest.c:27: undefined reference to `sin'
/usr/bin/ld: /tryouts/thtest.c:27: undefined reference to `tan'
/usr/bin/ld: /tmp/ccGpbaep.o: in function `main': /tryouts/thtest.c:47: undefined reference to `pthread_create'
/usr/bin/ld: /tryouts/thtest.c:57: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
terminal process failed to launch (exit code: -1).
Terminal will be reused by tasks, press any key to close it.
```
tasks.json
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cppbuild",
			"label": "C/C++: gcc build active file",
			"command": "/usr/bin/gcc",
			"args": [
				"-pthread", // use threads in target
				"-g", // generate debug
				"${file}",
				"-o", // output
				"${fileDirname}/${fileBasenameNoExtension}",
				"-lm" // link libm (math)
			],
			"options": {
				"cwd": "/usr/bin"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler: /usr/bin/gcc"
		}
	]
}
```
launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "gcc - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: gcc build active file", // comment out and all is fine, if build-task is done prior.
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}
```
Used c-file thtest.c
```
/*****************************************************************************
* FILE: join.c
* DESCRIPTION:
*   This example demonstrates how to "wait" for thread completions by using
*   the Pthread join routine.  Threads are explicitly created in a joinable
*   state for portability reasons. Use of the pthread_exit status argument is 
*   also shown. Compare to detached.c
* AUTHOR: 8/98 Blaise Barney
* LAST REVISED:  01/30/09
******************************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <pthread.h>

#define NUM_THREADS	4

void *BusyWork(void *t)
{
   int i;
   long tid;
   double result=0.0;
   tid = (long)t;
   printf("Thread %ld starting...\n",tid);
   for (i=0; i<1000000; i++)
   {
      result = result + sin(i) * tan(i);
   }
   printf("Thread %ld done. Result = %e\n",tid, result);
   pthread_exit((void*) t);
}

int main (int argc, char *argv[])
{
   pthread_t thread[NUM_THREADS];
   pthread_attr_t attr;
   int rc;
   long t;
   void *status;

   /* Initialize and set thread detached attribute */
   pthread_attr_init(&attr);
   pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);

   for(t=0; t<NUM_THREADS; t++) {
      printf("Main: creating thread %ld\n", t);
      rc = pthread_create(&thread[t], &attr, BusyWork, (void *)t); 
      if (rc) {
         printf("ERROR; return code from pthread_create() is %d\n", rc);
         exit(-1);
         }
      }

   /* Free attribute and wait for the other threads */
   pthread_attr_destroy(&attr);
   for(t=0; t<NUM_THREADS; t++) {
      rc = pthread_join(thread[t], &status);
      if (rc) {
         printf("ERROR; return code from pthread_join() is %d\n", rc);
         exit(-1);
         }
      printf("Main: completed join with thread %ld having a status of %ld\n",t,(long)status);
      }
 
printf("Main: program completed. Exiting.\n");
pthread_exit(NULL);
}

```

```
$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
```
Using C/C++ Extension Pack for VS Code

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.4.0-51-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 3900)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|23.33GB (2.46GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 29db6a5c-8721-448a-868e-41acf354dad1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
xml|Dot|2.5.1
gitlens|eam|10.2.2
LogFileHighlighter|emi|2.9.0
prettier-vscode|esb|5.7.1
findfile|Has|0.0.4
Angular2|joh|9.1.2
intellij-idea-keybindings|k--|0.2.41
vscode-docker|ms-|1.7.0
mssql|ms-|1.9.0
python|ms-|2020.9.114305
cpptools|ms-|1.1.0-insiders3
java|red|0.69.0
vscode-xml|red|0.13.0
bash-beautify|sha|0.1.1
markdown-preview-enhanced|shd|0.5.13
sonarlint-vscode|Son|1.18.0
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.25.0
vscode-maven|vsc|0.25.0
vscode-ansible|vsc|0.5.2
bootstrap-v4-snippets|Zac|1.1.3

(1 theme extensions excluded)

</details>

**Comment by sean-mcmanus** [comment]
It sounds like you hitting bug https://github.com/microsoft/vscode-cpptools/issues/6375 -- the fix is pending for our next release, and the workaround is to change your tasks.json "label" and make the corresponding change in the launch.json preLaunchTask.

For future reference, it's usually better to post C/C++ related issued to https://github.com/microsoft/vscode-cpptools/issues , unless you know it's a VS Code specific issue.
