### ISSUE TITLE
Ability to forward a range of ports to container

### ISSUE THREAD

**Issue by peredwardsson** [microsoft/vscode#109215]
I'm working with robotics using the ROS ecosystem. In it, you can create services that act as functions that can be called to by other parts of the system. The services are assigned a predetermined IP and a random available port somewhere above 30000. This makes developing in a container frustrating, since I have to manually forward the port of the day into the container. EXPOSE-ing the port in the Dockerfile doesn't help, nor does using `"runArgs": ["--expose=30000-65535"]` in the devcontainer.json. 

I would like to be able to add such a range of ports to the forwardPorts field of devcontainer.json, such that I could use 
`"forwardPorts": [30000-65535]`
or
`"forwardPorts": [30000:]` (for "30000 onward")
or maybe even
`"forwardPorts": [*]` (for "all ports")

To the best of my abilities, this doesn't seem doable at the moment. Happy to answer questions should they pop up.

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/3898
