### ISSUE TITLE
Git login GUI in more actions tab

### ISSUE THREAD

**Issue by jugaldb** [microsoft/vscode#109204]
Currently there is a git login system in the terminal, it would be great to have one in the git panel under more actions as well where it opens a dialog box tab inside VScode

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the git login system in the terminal you are referring to?

**Comment by jugaldb** [comment]
Hi @joaomoreno, currently 
![image](https://user-images.githubusercontent.com/55304795/96973174-2bf72800-1535-11eb-8e7f-b2dc24146326.png) 
this is supported in VScode while pushing to remote repositories, something similar is available in terminal as well, what I am saying is let user configure these setting in VScode startup/installation itself, like adding remote user credentials or something like that if a user is interested in doing that, I dont have my credentials stored in git installed in my machine, I would love to have that inside the VScode as a gui instead of using terminal or the screenshot I have attached, hope that makes sense

**Comment by joaomoreno** [comment]
What VS Code version do you have installed? VS Code now has automatic GitHub authentication.

**Comment by jugaldb** [comment]
![image](https://user-images.githubusercontent.com/55304795/97025786-2968f280-1576-11eb-9454-dca5978d9a39.png)
This is my current version and if I click on check for updates it shows..
![image](https://user-images.githubusercontent.com/55304795/97025902-50272900-1576-11eb-92a8-f047c5c7b166.png)

**Comment by joaomoreno** [comment]
When is that dialog prompt appearing? Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by jugaldb** [comment]
Hi @joaomoreno , I just found the setting which you were talking about, thanks, closing the issue.
