### ISSUE TITLE
Delete or rename file from the editor

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#109287]
It would be great to be allowed to delete/rename/... a file from a right click inside the editor and on the editor tab.
For now these items:
![Window_000283](https://user-images.githubusercontent.com/9438102/97078799-e860f480-15ee-11eb-89a1-221c315981c5.png)

Are only available from a right click in the explorer view.

**Comment by gjsjohnmurray** [comment]
Related #90104 #100591

**Comment by isidorn** [comment]
There are duplicates of these and an extension can also handle this.
