### ISSUE TITLE
Option to create a template out of our customized launch.json in vscode?

### ISSUE THREAD

**Issue by ldarshan1991** [microsoft/vscode#109234]
For my project, I have customized my `launch.json` file.

It would be nice to save my own customized launch configuration as a template? Just like `C++ (GDB/LLDB)` template So that I can re-use it easily every time I open a new folder(project).

I don't want to add it under global launch configuration. Adding it there would start showing up my launch configurations even for other kind of projects where this launch configuration is inappropriate.

I wanted to have the same behavior that is achieved for `C++ (GDB/LLDB)` template.
An option - `Save your configuration as template` and it should show up in the below list as one other option.

![image](https://user-images.githubusercontent.com/28981482/96998378-fe1fdc80-1550-11eb-83f8-dbefd6995777.png)

**Comment by ldarshan1991** [comment]
@weinand Can I have a response on this, please?

**Comment by weinand** [comment]
The QuickPick UI from above does not show launch configurations but debuggers. So it would not be the correct place to show your template.

Most likely you want to have your template show up in the "Add Configuration" QuickPick:

<img width="823" alt="2020-10-27_17-31-47" src="https://user-images.githubusercontent.com/1898161/97332183-713f9080-187a-11eb-8eb3-d440447165cd.png">

Is this a correct assumption?

**Comment by ldarshan1991** [comment]
@weinand yeah, you right.

**Comment by ldarshan1991** [comment]
Thanks @weinand for suggesting.
If I understood your suggestion properly, you are asking me to write a new plugin/extension for achieve this. Am I right?
If so, rather than having a whole new plugin wouldn't it be cleaner to support this in the VSCode core feature? Just like `settings.json` exposing `package.json		`

**Comment by weinand** [comment]
Yes, you can just use the snippet support of VS Code: https://code.visualstudio.com/docs/editor/userdefinedsnippets
