### ISSUE TITLE
vs code ctrl+n not save in currently opened directory

### ISSUE THREAD

**Issue by voteskip** [microsoft/vscode#109279]
- VSCode Version:
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
- OS Version:
edition - windows 10 pro for workstations
version - 2004
build - 19041.572

Steps to Reproduce:
0. try edit any outside file with this editor. close it.
1. open any another directory
2. do ctrl+n
3. try save with ctrl+s
4. get something like a previous/foreign path
5. suffer

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by voteskip** [comment]
Currently, i can reproduce this bug with "desktop" path. but seems like it happens occasionally.

1.0.  ![image](https://user-images.githubusercontent.com/67455967/97187412-5f5be000-17dd-11eb-9d5d-f48e1a378bae.png)
OR
1.1.  ![image](https://user-images.githubusercontent.com/67455967/97187606-916d4200-17dd-11eb-963a-68d5e3656464.png)

2. ![image](https://user-images.githubusercontent.com/67455967/97187700-ab0e8980-17dd-11eb-9511-917e6873fe72.png)
3. ![image](https://user-images.githubusercontent.com/67455967/97187776-c1b4e080-17dd-11eb-9d71-6135ca2af734.png)
4. ![image](https://user-images.githubusercontent.com/67455967/97188171-2cfeb280-17de-11eb-81ec-a0d83c79cec8.png)

trying` file>open folder`. and create/save actions looks fine. at least now.

thanks for what you do guys, keep it going.

**Comment by bpasero** [comment]
I think we just remember the last used path. Can you suggest what you would expect

**Comment by voteskip** [comment]
More context relative behavior i guess.
Its not well comfortable, say i want open folder and start doing my things.
basic operations like CRUD files, right?
and what i get, last used path, when i'm working with current path/project?
I found it not conveniently, and need clarify that thing. 
maybe that buttons on top bar, and their hotkeys not for me ;)

**Comment by bpasero** [comment]
@voteskip I followed your steps and I do not see a problem:

![recording](https://user-images.githubusercontent.com/900690/97264612-9229c680-1825-11eb-9329-3fb0c1ad7f47.gif)

**Steps:**
* open a folder
* open a file not inside that folder
* open another folder
* open a new file
* save it
* => the folder that is opened is suggested

**Comment by voteskip** [comment]
nope.
![result](https://user-images.githubusercontent.com/67455967/97278662-0475c780-1875-11eb-9fe4-2d9a2f9efa98.gif)

- open vs code
- create file
- try to save
- get unrelated path for saving

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by voteskip** [comment]
nah, i choose IDE. thanks for nothing.
