### ISSUE TITLE
Проблема в кодировке

### ISSUE THREAD

**Issue by NicolayGolovnev** [microsoft/vscode#109298]
Issue Type: <b>Bug</b>

Обнаружил проблему после уcтановки последнего обновления. При обнаружении ошибки в коде, подсказка в виде всплывающего окна, где должен быть написан текст, нарушена кодировка для русского языка.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (4.50GB free)|
|Process Argv|--crash-reporter-id c59a25c1-2cde-4e73-8be9-acefc2763afc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
asm-code-lens|maz|1.5.8
vscode-clang|mit|0.2.3
vscode-language-pack-ru|MS-|1.50.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.9.114305
cpptools|ms-|1.1.0-insiders3
vscode-yaml|red|0.11.1

</details>

**Comment by zealcrew** [comment]
> Issue Type: Bug
> 
> Обнаружил проблему после уcтановки последнего обновления. При обнаружении ошибки в коде, подсказка в виде всплывающего окна, где должен быть написан текст, нарушена кодировка для русского языка.
> 

Got a problem after installing the latest update. If some error is detected in the source code then russian text in a pop-up window are wrong encoded.

![1](https://user-images.githubusercontent.com/73593477/97438618-13707e80-1936-11eb-9a66-1b892cc3cb43.jpg)
