### ISSUE TITLE
Terminal text invisible

### ISSUE THREAD

**Issue by shujathkhan** [microsoft/vscode#109232]
Issue Type: <b>Bug</b>

My terminal's text becomes invisible after 2 or 3 hours of usage. 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.81GB (10.63GB free)|
|Process Argv|--crash-reporter-id 123e2acc-ce7e-4d91-95f6-7fdc14f39330|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|7.2.0
npm-intellisense|chr|1.3.1
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
make-hidden|dev|3.0.3
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
vscode-peacock|joh|3.8.0
template-string-converter|meg|0.2.3
git-graph|mhu|1.26.0
vscode-js-profile-flame|ms-|0.0.13
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.1
debugger-for-chrome|msj|4.12.11
vscode-scss-formatter|sib|2.0.2
vscode-multiclip|sle|0.1.5
tabnine-vscode|Tab|3.0.3
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0

(2 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
You might be seeing https://github.com/Microsoft/vscode/issues/69665? I haven't seen any other reports of it just all of a sudden becoming visible after 2-3 hours without having the computer sleep.

**Comment by shujathkhan** [comment]
Facing similar issues to #69665 , hence closing as a duplicate.
