### ISSUE TITLE
Terminal: remember layout between restarts

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109244]
Now that we support to restore terminals after connecting back to a remote, I think the terminal layout should also be preserved.

I would have expected that the terminal already stores the layout into the view memento, but it does not seem to be the case. I am not sure why?

//cc @alexdima

**Comment by Tyriar** [comment]
Currently when remotes reconnect terminals the split terminals get flattened into their own terminals. This is mainly an issue of how we want to persist that knowledge across sessions and make sure the remote agent stores it (eg. splitIndex: number may be enough). Note also that split terminals are naturally smaller so they have non-standard dimensions, not sure we need to do anything special to handle dimensions differently as resize events are recorded.

Ideally there may need to be some logic/checks to ensure split terminals get adopted together so they cannot be split up. This will probably involve the introduction of the terminal tab idea on the server.

**Comment by GitMensch** [comment]
Is this issue only related to the remote terminal or also to the way hidden terminals are processed (a terminal created by openssh with `reveal:always` has a correct size (full-width of the terminal view) while `reveal:never` seems to be 80 columns only)?

**Comment by roblourens** [comment]
Not exactly sure what your scenario is, but I don't think this will be related.
