### ISSUE TITLE
SCM: Should use Ctrl-UpArrow instead of just UpArrow?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#109275]
Issue Type: <b>Bug</b>

I've been using the scm commit history in insiders for the past few days. Here's some general feedback on the UX:

### Unexpectedly navigating through history
I'll often hit up or down arrow to go to the next or previous line, and instead end up navigating through the history. 

Could we require holding down ctrl or some other key to navigate history? I don't know why but I hit this a lot more in the commit history than I ever do in the search input boxes. Maybe this should be discussed at the UX sync?

### Lost commit message
I've lost my commit messages a few times (possibly #109121). This is quite frustrating when you have written a long commit message, and it's something I think we need to fix this iteration

VS Code version: Code - Insiders 1.51.0-insider (7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9, 2020-10-23T07:32:22.213Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.95GB free)|
|Process Argv|-psn_0_2732699 --crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|18%|
</details>

**Comment by joaomoreno** [comment]
### Unexpectedly navigating through history

Yeah, but you can always go back to it right? I wonder if this is warranted. I guess it just happens more because commit messages are often multiline, as opposed to search. The problem with Ctrl is the discoverability. Plus, we'd need to align all other history input boxes to also use Ctrl.

### Lost commit message

That's https://github.com/microsoft/vscode/issues/109443

**Comment by meganrogge** [comment]
Related to #109437, which has now been addressed so that instead of up and down arrows, the options to navigate the history are:

1. use alt + arrows
2. use up and down arrows, but be on the first line, first character or last line, last character, respectively
