### ISSUE TITLE
Launch configurations opening user settings should respect remote connection

### ISSUE THREAD

**Issue by ldarshan1991** [microsoft/vscode#109228]
- VSCode Version: 1.50.1
- OS Version: Windows 10

Steps to Reproduce:

1. Have VSCode running on Windows machine.
2. Install Remote Development extension and establish a remote connection to a linux machine.
3. Have your launch configuration inside the remote-connection settings.json - `/users/<username>/.vscode-server/data/Machine/settings.json`
4. Now open a folder from VSCode which has the code and come to **Run** section. You will see all the configuration settings present as part of remote-connection settings.json.
![image](https://user-images.githubusercontent.com/28981482/96995717-3ffa5400-154c-11eb-82c2-3f954eb9a2ed.png)

5. Press the "settings wheel" present at the top.
![image](https://user-images.githubusercontent.com/28981482/96995805-67512100-154c-11eb-8af4-1361dec08609.png)

6. Notice the settings.json file that opens is the User Settings once - `/C:/Users/<username>/AppData/Roaming/Code/User/settings.json`
and not the remote-connection settings.json from where launch configuration is actually read from.

Does this issue occur when all extensions are disabled?: No

**Comment by isidorn** [comment]
@sandy081 I am simply using `preferencesService.openGlobalSettings`
[Code pointer](https://github.com/microsoft/vscode/blob/0124f68884254b067fc0118bd866b46200029e41/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L897)

Should the `preferenceService` respect the remote connection when opening global settings?

**Comment by sandy081** [comment]
> Should the preferenceService respect the remote connection when opening global settings?

I do not think so, that would prevent opening regular user settings at all in remote window. Instead you can use following api if you want to open remote settings

https://github.com/microsoft/vscode/blob/0b1cd268f1a2753ba02ab1a0754f7d4a0528b7b3/src/vs/workbench/services/preferences/common/preferences.ts#L210
