### ISSUE TITLE
VsCode internal git module doesn't recognize sub-modules

### ISSUE THREAD

**Issue by mike-onehub** [microsoft/vscode#109258]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Have a repo with a submodule activated in it.
Edit two files, one in repo and one in submodule.
Attempt to stage both files for one commit.
Only repo file is able to commit, submodule file is left unstaged.
Going to command line and cd into submodule to commit and push accomplishes intended task.

Expected result:
VsCode performs first commit and 'automagically' changes paths into submodule to perform same action again for remaining changes. Same approach for pushes.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.75GB free)|
|Process Argv|--crash-reporter-id 1c2980dc-3089-4820-8655-25af7d98e4c1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (69)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-clock|Com|0.0.1
better-comments|aar|2.1.0
vscode-color-pick|ada|0.6.2
Bookmarks|ale|11.4.0
project-manager|ale|11.3.1
read-only-indicator|ale|3.4.0
aws-toolkit-vscode|ama|1.15.0
vscode-database|baj|2.2.3
vscode-django|bat|0.20.0
git-easy|bib|1.11.0
path-intellisense|chr|2.3.0
regex|chr|0.2.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.37.1
lua-debug|dev|1.1.1
githistory|don|0.6.12
python-extension-pack|don|1.6.0
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
vscode-great-icons|emm|2.1.57
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
vscode-toggle-column-selection|eri|1.0.6
prettier-vscode|esb|5.7.1
vscode-pull-request-github|Git|0.20.1
code-sync|gol|2.7.3
activitusbar|Gru|0.0.36
todo-tree|Gru|0.0.183
ansible|haa|0.2.8
terraform|has|2.2.3
beautify|Hoo|1.5.0
vscode-peacock|joh|3.8.0
MagicPython|mag|1.1.0
aws-cli-configure|mar|0.3.0
markdown-shortcuts|mdi|0.12.0
ecdc|mit|1.3.0
perl-debug|mor|0.6.3
vscode-docker|ms-|1.7.0
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.9.114305
remote-containers|ms-|0.145.1
remote-wsl|ms-|0.50.1
atom-keybindings|ms-|3.0.9
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.3.0
aws-actions|Ple|1.0.0
puppet-vscode|pup|0.28.0
ruby|reb|0.27.0
vscode-yaml|red|0.11.1
perl|ric|2.1.0
lua-indent|rin|0.0.1
LiveServer|rit|5.6.1
ActiveFileInStatusBar|Ros|1.0.3
wow-bundle|Sep|1.3.0
trailing-spaces|sha|0.3.1
guides|spy|0.9.3
code-spell-checker|str|1.9.2
python|tht|0.2.3
ansible-autocomplete|tim|0.0.2
shellcheck|tim|0.12.1
vscode-lua|tri|0.12.4
terminal-tabs|Tyr|0.2.0
vscodeintellicode|Vis|1.2.10
vscode-glide|vit|1.0.2
sync-rsync|vsc|0.36.0
vscode-icons|vsc|11.0.0
jinja|who|0.0.8
vscode-ruby|win|0.27.0
markdown-all-in-one|yzh|3.3.0

(8 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
> Edit two files, one in repo and one in submodule.
> Attempt to stage both files for one commit.

Git doesn't support this. Each file is in a separate repository, despite one repo being a submodule of another.

You're going to have to create two separate commits. First, the submodule changes. Then the outer one.
