### ISSUE TITLE
Test: confirmation prompt when closing tab/window

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109283]
Refs: 

- [x] web @meganrogge (Edge/Chrome)
- [x] web @alexr00 (Firefox)
- [x] web @JacksonKearl (Safari)

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23109283%0A%0A)

---

A new setting `window.confirmBeforeClose` for web allows to prevent a close of the window/tab by accident. This setting is only enabled for web and will be enabled as `keyboardOnly` unless you run in a PWA app. A choice of `always` and `never` is provided as well to tweak this.

**Testing:**
* verify the setting makes sense to you 
* verify the setting is `keyboardOnly` in normal web but `never` if you install as PWA app (needs a reload of PWA app once installed)
* test the various settings
  * `keyboardOnly`: you see a confirmation dialog when you use keybinding to close the tab (`CtrlCmd+W` or any other assigned key if it has a modifier such as `Ctrl`, `Cmd`, etc.) but not when you e.g. use the mouse to close the tab from the X button.
  * `always`: you always get a confirmation dialog, even when you close with the X button and mouse
  * `never`: you never get the confirmation dialog, even when using keyboard to close
* quickly make changes and try to close the tab, you should still see a confirmation dialog even if you configure `never` because we only run backups after a certain timeout and warn for real data loss
* even when configured as `always` or `keyboardOnly`, you will not see a confirmation dialog if you reload the window via keybindings (`CtrlCmd+R`) or when you switch folders (via `File > Open Recent`)

**Comment by alexr00** [comment]
> even when configured as always or keyboardOnly, you will not see a confirmation dialog if you reload the window via keybindings (CtrlCmd+R) or when you switch folders (via File > Open Recent)

I actually do still see the confirmation when doing File -> Open Recent

**Comment by alexr00** [comment]
I couldn't get PWA to work in Firefox (got PWA enabled for Firefox, but wasn't able to open web as PWA). Otherwise looks good!

**Comment by bpasero** [comment]
@alexr00 I think you found a bug in my implementation when you set `window.confirmBeforeClose: always` you would always see a confirmation even when you do File > Open Recent. I opened https://github.com/microsoft/vscode/issues/109487 and pushed a fix, but it will take until tomorrow to land.

**Comment by meganrogge** [comment]
@bpasero works well overall. I still see the dialogue when I reload the window via keybindings with `window.confirmBeforeClose: always or keyboardOnly` in Chrome and Edge

**Comment by JacksonKearl** [comment]
On a ppe codespace in macOS, when configured as `always` reloading via a keybinding or changing workspace will trigger the warning, but at at `keyboardOnly` it does not.

Version: 1.51.0-insider
Commit: 16f4a29aa0ac05d3cba222b1f347b7404626c680
Date: 2020-10-26T05:37:52.074Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15

**Comment by bpasero** [comment]
@meganrogge @JacksonKearl yes, this sounds like the fix I pushed only yesterday, would be great if you can re-check that scenario from a PPE Codespace that has todays insider build 👍
