### ISSUE TITLE
VSCode Smoke Tests: localization - "before all" hook for "starts with 'DE' locale and verifies title and viewlets text is in German":

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109211]
```
VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Localization
           "before all" hook for "starts with 'DE' locale and verifies title and viewlets text is in German":
     Error: Timeout: click 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-list-row[data-extension-id="ms-ceintl.vscode-language-pack-de"] .extension-list-item li[class='action-item'] .extension-action.install' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=91585&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=6ba55b26-6502-59ae-6c43-7e580fa53cb9&l=111

**Comment by dbaeumer** [comment]
Looks like it failed to install the German LP. Actually I have no idea what to do when this happens since I can't recover from this. So IMO it is OK to let the test fail. 

@bpasero any other suggestion? Or do we mark something like this as `yellow` failed?

**Comment by bpasero** [comment]
We mark it as "yellow" failed just to be able to file issues during the milestone. But if the test failed because of some network outage on the build machine and not because of the test itself, feel free to close.

**Comment by dbaeumer** [comment]
Ran it locally and the localization test passes. Closing the issue

<img width="587" alt="capture" src="https://user-images.githubusercontent.com/1931590/97162317-563c2600-177f-11eb-81a9-66a0a8f39660.png">
