### ISSUE TITLE
Can't select multiple lines in VSCode web

### ISSUE THREAD

**Issue by VincentDondain** [microsoft/vscode#109243]
Version: 1.51.0-insider
Commit: f4e5221ca7414d39a4d509a2825fd89143531148
Date: 2020-10-21T20:55:44.266Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15

Steps to Reproduce:

1. Open VSCode web (Codespaces) on iPadOS
2. Try selecting multiple lines of codes either with fingers or magic trackpad.

cc @bpasero @rebornix

**Comment by VincentDondain** [comment]
Actually, it seems to sometimes work with the magic trackpad but never with fingers.

**Comment by rebornix** [comment]
Now that `pointer`, `mouse` and `finger` are all different event types, we need to rethink what's the expected behaviors with fingers (currently it only set cursor and scroll the viewport, but does not allow selection)

**Comment by TylerLeonhardt** [comment]
This is quite stale and should work now. We had several other issues that have been resolved with newer iPadOS updates.
