### ISSUE TITLE
MSSQL language syntax out of date

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode#109251]
https://github.com/microsoft/vscode/blob/master/extensions/sql/syntaxes/sql.tmLanguage.json

There's been updates made to the plist from https://github.com/microsoft/vscode-mssql/blob/main/syntaxes/SQL.plist but it looks like the syntax here hasn't been updated. How often does this happen? 

@alexr00

**Comment by alexr00** [comment]
I update the grammars roughly once per month unless some lets me know about something particularly egregious. I'll probably update next week!

**Comment by alexr00** [comment]
It looks like we are already at commit 61ae0eb21ac53883a23e09913a5ae77a59126ff9, which appears to be the most recent commit https://github.com/microsoft/vscode-mssql/commits/main/syntaxes/SQL.plist

**Comment by Charles-Gagnon** [comment]
@alexr00 Looks like something isn't going right with the conversion process then - in that commit we have the following : 

```
		<dict>
			<key>match</key>
			<string>(?i)\b(ascii|char|charindex|concat|difference|format|left|len|lower|ltrim|nchar|nodes|patindex|quotename|replace|replicate|reverse|right|rtrim|soundex|space|str|string_agg|string_escape|string_split|stuff|substring|translate|trim|unicode|upper)\b</string>
			<key>name</key>
			<string>support.function.string.sql</string>
		</dict>
```

https://github.com/microsoft/vscode-mssql/commit/61ae0eb21ac53883a23e09913a5ae77a59126ff9#diff-77fe01e5ece1baf6fab2accf8a6c81a998ef5c219e50b225fb6dcaa62efa81bdR396

But if we diff that with the matching entry in https://github.com/microsoft/vscode/blob/master/extensions/sql/syntaxes/sql.tmLanguage.json

```
		{
			"match": "(?i)\\b(ascii|char|charindex|concat|difference|format|left|len|lower|ltrim|nchar|patindex|quotename|replace|replicate|reverse|rtrim|soundex|space|str|string_agg|string_escape|string_split|stuff|substring|translate|trim|unicode|upper)\\b",
			"name": "support.function.string.sql"
		},
```

I see that it's missing some of the values, for example `right`

**Comment by alexr00** [comment]
@Charles-Gagnon thank you for your diligence. It seems that microsoft/vscode-mssql changed the name of their default branch, and out language updating scripts are not very smart and just hardcode the branch. I have updated the script with the correct branch name and updated the grammar!

**Comment by Charles-Gagnon** [comment]
Awesome, thank you!
