### ISSUE TITLE
Remove whitespaces (replace them with dashes or underscores) when text is pasted into the Create git branch input

### ISSUE THREAD

**Issue by dKab** [microsoft/vscode#109223]
I often name branches using the title of the Jira ticket that I'm going to work on, and I think many developers do that too, whether they use Jira or other project tracking software. The problem is, of course, that whitespaces are not allowed in the name of a git branch. So I have to either type out the name by hand, which is slow and error-prone, or paste the text from a clipboard and replace whitespaces with "-" or "_". It would be great if the replacement happened automatically.

**Comment by joaomoreno** [comment]
> It would be great if the replacement happened automatically.

Have you tried it? It already happens automatically.
