### ISSUE TITLE
References view: clicking refresh seems to run previous search from history

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109293]
Steps to Reproduce:

0. (I am using web, not sure if relevant)
1. find references 
2. find references again on a different symbol
3. click the refresh button

=> 🐛  previous references are shown

![recording](https://user-images.githubusercontent.com/900690/97081193-02a3ce00-1601-11eb-8f82-9e6434511a50.gif)

**Comment by jrieken** [comment]
It's actually the first history entry. Surprised that this was caught only now
