### ISSUE TITLE
Debug hover moves while expanding/collapsing

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109226]
* see attached screen capture
* open a debug hover above cursor
* expand it to become too large
* :bug: it now renders below

![Oct-23-2020 12-10-03](https://user-images.githubusercontent.com/1794099/96992826-b2f2d300-152a-11eb-87ff-d3d059d96ad9.gif)

@isidorn For suggest I have a similar problem and I added `IContentWIdget#afterRender` which is invoked with the position preference at which the editor has placed the widget. I'd recommend to keep that position locked as the hover shows

**Comment by isidorn** [comment]
@jrieken thanks for the issue and for the suggestion on how to fix.
I have tried it out with keeping the position preference stable and now it seems to behave good for me.

**Comment by jrieken** [comment]
verified but found this: https://github.com/microsoft/vscode/issues/109653. Unsure if it's a regression.
