### ISSUE TITLE
Jump to definition with F12

### ISSUE THREAD

**Issue by JUAN2011315** [Microsoft/vscode#10921]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1. Por favor incluyan la opción de IR A LA DEFINICIÓN CON F12, en mi caso con el lenguaje PHP.

**Comment by sandy081** [comment]
@JUAN2011315 Can you please provide proper and detailed summary and description of the issue and steps to reproduce?

Thanks

**Comment by dbaeumer** [comment]
Closing. Haven't received any response. @JUAN2011315 please ping if the issue is still reproducible with steps that demo the problematic behavior.
