### ISSUE TITLE
[Live Share Web] Workspace label on startup before the workspace is resolved shows '/'

### ISSUE THREAD

**Issue by jramsay** [microsoft/vscode#109253]
When a guest first attempts to join the Live Share session on Web, and they haven’t yet logged in, they see the following `/` workspace entry. Is there a way to suppress this, or rename it, until we load the workspace folders? It appears before our Live Share Web extension’s activate() gets called so I don’t think this is something we’re explicitly enabling.

![image](https://user-images.githubusercontent.com/8161247/97034275-81254080-1519-11eb-882e-c3f0999b264a.png)

- VSCode Version: 1.51.0-insider (also tested on 1.49.3)
- OS Version: Windows 10 Enterprise 64-bit OS, x64 

This is a VS Code in browser issue

Steps to Reproduce:

1. Start a Live Share session on VS Code desktop
2. Join using the Live Share Web link in a browser
![image](https://user-images.githubusercontent.com/8161247/97034572-fabd2e80-1519-11eb-950a-da95167a66a9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jramsay** [comment]
@isidorn: creating an issue to continue the conversation here. thanks!

**Comment by isidorn** [comment]
@jramsay thanks for creating the issue. Do you register a [label formatter](https://github.com/microsoft/vscode/blob/3ec9473a4598104f141aab997564376d637e1fd8/src/vs/vscode.proposed.d.ts#L292)? If yes, have you tried to pass the [`stripPathStartingSeparator`](https://github.com/microsoft/vscode/blob/3ec9473a4598104f141aab997564376d637e1fd8/src/vs/vscode.proposed.d.ts#L287)?

If you do not use the formatter can you explain how to you get your URI's displayed correctly?

**Comment by jramsay** [comment]
@isidorn: I checked the code and there wasn't a label formatter. I added one and could see it had an impact in formatting the filenames but didn't appear to help with the workspace ('/') name in the Explorer. That said,  I checked to see how URIs were getting displayed. For Live Share Web (Browser) we have a WorkspaceProvider that extends vscode's FileSystemProvider. It provides the files for the workspace. Then we follow up with a call to vscode.workspace.updateWorkspaceFolders() to update the workspace names.

I was able to add the following call right in our extension activate():

const workspaceFolders = vscode.workspace.workspaceFolders;
    if (workspaceFolders && workspaceFolders.length > 0) {
        vscode.workspace.updateWorkspaceFolders(0, workspaceFolders.length, {
            uri: workspaceFolders[0].uri,
            name: ' '
        });
    }

This replaces the '/' in the Explorer with 'Untitled (Workspace)' and a loading icon which is actually what we want in this scenario. It gives the user the opportunity to sign in and then we can update the workspace with the shared files.

![image](https://user-images.githubusercontent.com/8161247/97489127-62111f00-191c-11eb-91a6-143d2b86af74.png)

The one item remaining is we'd like to be able to update the UNTITLED (WORKSPACE) caption with: VISUAL STUDIO LIVE SHARE (WORKSPACE). @bpasero was suggesting this could be done by first opening a workspace with that name ("Visual Studio Live Share.code-workspace"). I tested that out though and haven't yet been successful doing this in our Browser extension. I'm going to close this issue and I'll open another to get help on that one. Thanks!

**Comment by isidorn** [comment]
Glad you could find something that works.

Did you maybe try using the [`workspaceSuffix`](https://github.com/microsoft/vscode/blob/1b30218687941e718b38c337e901d4898a8e2b70/src/vs/vscode.proposed.d.ts#L285) that should allow you to add any suffix to your workspaces. For example VISUAL STUDIO LIVE SHARE?
It would not give you exactly what you want but might help.
