### ISSUE TITLE
Unable to resolve filesystem provider with relative file path...

### ISSUE THREAD

**Issue by nakiya** [microsoft/vscode#109209]
I have calva installed in VSCode.

I am Just trying to do a REPL jack-in using `ctrl+alt+c ctrl+alt+j`. (This has worked many times in the past.)

Then I get this error: `Unable to resolve filesystem provider with relative file path 'd:\work\projects\formula/.calva/output-window/.clj-kondo'` (`d:\work\projects\formula` is my project folder, I don't see a .calva folder created there though.)

I tried restarting VSCode/machine, moving project location, creating new fresh project, etc and nothing works.

What is wrong and what can I do? I'm not sure if this is a VSCode issue or something related to Calva.

----

Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by aturok** [comment]
@nakiya  It seems to be a Calva issue - I just ran into this and rolling Calva back to 2.0.126 makes jack in work again. On 2.0.127 it doesn't jack in (doesn't event show the message as on 2.0.129)
