### ISSUE TITLE
Improve description of explorer.openEditors.visible setting

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#109250]
> 
> 
> Found it. "explorer.openEditors.visible": 1 solved the problem.

You may want to set that larger than 1. Default value is 9.

Helptext for the section doesn't state that a value of zero disables the panel entirely. It probably ought to.

![image](https://user-images.githubusercontent.com/6726799/97031038-93be6a80-1557-11eb-87a7-ceab92398fb5.png)

_Originally posted by @gjsjohnmurray in https://github.com/microsoft/vscode/issues/108264#issuecomment-715454861_

**Comment by isidorn** [comment]
Yeah, makes perfect sense. Pushed a commit that tackles this. Thanks!
