### ISSUE TITLE
Very often suggest widget larger than it should be

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#109239]
I am on latest insiders.
Every 15 minutes I get the suggest widget to be larger than it should be. Here's one picture example.
Sorry for no clear repro steps: let me know if you need them and I can try to find exact ones.

![Screenshot 2020-10-23 at 16 15 18](https://user-images.githubusercontent.com/1926584/97015118-784d6280-154b-11eb-9bc1-fb1a3206bfef.png)

**Comment by jrieken** [comment]
already fixed via 5c013722f1a7a75de409712ef2acb039d8039555
