### ISSUE TITLE
Support detail text in settings editor dropdown

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#109255]
In https://github.com/microsoft/vscode/issues/106737 we added support for showing an enum value "label" instead of the only the key. The key shows up in square brackets in the description area. But it would be nicer to show this in the same way that it looks in the editor's encoding picker: 

![image](https://user-images.githubusercontent.com/323878/96287159-5cb7ea00-0f96-11eb-83b4-95494f0d7a01.png)

So we should add support for the same sort of left-aligned detail text without losing the right-aligned detail text (that is used for "Default")

**Comment by maldahleh** [comment]
@roblourens I'd be interested in trying this out if it's available, do you have any pointers on where to start?

**Comment by roblourens** [comment]
Great! Check out the file `selectBoxCustom.ts`. You can see where it creates the elements for the text and decoratorRight. We just need an option to add something similar, left aligned and styled in gray. You could call it `detail` or something like that. Then `settingsTree.ts` needs to make use of this new option when enumItemLabels are set.
