### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by parided** [microsoft/vscode#109230]
I download and install Vscode VSCodeSetup-ia32-1.50.1.exe.
When I run it, the vscode window stays completely black and nothing is visible. in order to close the window, I have to press the  ctrl + f4 sequence key.

- VSCode Version:ia32-1.50.1
- OS Version:Windows 7

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by javaxiu** [comment]
is that cause by Electron 6 (or later version) is not supported to run on windows 7 ?  see also https://github.com/electron/electron/issues/22118

**Comment by parided** [comment]
Perfect thanks. Microsoft then has to change the wording on the supported version being downloaded from windows 7,8,10, in windows 8, 10. At this point it means that I switch to atom or eclipse. Goodbye microsoft.
