### ISSUE TITLE
Sourcing environment with multiple VS Code window

### ISSUE THREAD

**Issue by yannickowow** [microsoft/vscode#109238]
#88718 duplicate ? I don't think it is the same behavior but still

- VSCode Version: 1.50.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code from exe
2. Open new VS Code from sourced environment (ex: minGW)
3. Open a folder with new VS Code window (with minGW environment)

Expected: First window does not have sourced env., second one has minGW env.
Result: None of them have minGW env.

Does this issue occur when all extensions are disabled?: Yes

Hi, 
My hypothesis is that the first opened process will source next windows. I don't think that it is a #88718 duplicate because env. is not added from an extension, but from a shell.
When I open a new folder, I expect my current window to have the same environment before close/reopen step to refresh current folder. 

Thanks in advance.

**Comment by Tyriar** [comment]
I think you're after https://github.com/microsoft/vscode/issues/15452?

When you open VS Code, the environment is inherited from whatever you launched from. After that, all other windows will share the original environment. So you need to close all windows to refresh it currently.

**Comment by yannickowow** [comment]
Hi, 
Yes it looks like something similar. I agree to your first point, when I open a new window from a terminal, it'll inherit all the environment.
My suggestion was, from this window, if I decide to do "Open Folder", this window should have the same environment as before. I don't know it if was raised on #15452.

**Comment by Tyriar** [comment]
I wouldn't expect it act as it does not but only not in certain circumstances like the open folder command. But anyway I think https://github.com/microsoft/vscode/issues/15452 covers to change anything around the fact that currently all windows share the same environment.

**Comment by bpasero** [comment]
Should be fixed now based on https://github.com/microsoft/vscode/issues/108804#issuecomment-731230574

**Comment by bpasero** [comment]
\closedWith 6f3fcd2ce0002ffd876b7b43bff42a912edddaae
