### ISSUE TITLE
Can't use Git Windows when project is opened in remote WSL

### ISSUE THREAD

**Issue by ymoreau** [microsoft/vscode#109242]
- VSCode Version: 1.50.1
- OS Version: Linux x64 4.4.0-18362-Microsoft (WSL1 on Windows 10)

1. Open a remote project in VisualStudioCode
2. Try git commands in GitBash or actions in GitGui
3. Enjoy the error message: `Rename from 'C:/workspace/myproject/.git/index.lock' to 'C:/workspace/myproject/.git/index' failed. Should I try again?`

I saw other issues related to this, all closed without any working workaround (#901, #987, #90186).

I tried to deactivate everything about git, it makes no difference. GitLens is deactivated. I have `git.enabled: false`, `git.autorefresh: false` and `git.autofetch: false`.

Interesting point though: the git commands are working inside the WSL console, and not in the GitWindows console.

I had the same problem with my previous setup (older versions of Windows, WSL-Ubuntu, VSCode and GitWindows), so this is not specific to the versions I am using right now.

Does this issue occur when all extensions are disabled?: Yes (except for Remote-WSL)

**Comment by joaomoreno** [comment]
If your repository is in Windows, please use Git for Windows.

If your repository is in WSL, please use Git inside WSL.

**Comment by ymoreau** [comment]
How is this related? Well everything works fine as long as VS Code is not executing so it is obviously the cause of the issues.
Even with git fully disabled in VS Code it is still locking the git index somehow, and no other command or tool is doing this.

The repository is in Windows btw, but I compile it in the WSL console, and the filesystem is in windows anyway.

**Comment by joaomoreno** [comment]
> The repository is in Windows btw, but I compile it in the WSL console, and the filesystem is in windows anyway.

Got it. This is an unsupported scenario. I highly recommend using Git for Windows, if your files are in Window since (1) much better performance and (2) no FS errors like the above.

**Comment by ymoreau** [comment]
I do use Git for Windows, it's Git for Windows that is not working when VS Code is running remote on the windows workspace.

I don't have the issue if I open the workspace normally (not in remote). And I don't have the issue if VS Code is running for another project.

So, somehow, opening the workspace using remote will lock the git index even if all git settings are disabled in VS Code.
