### ISSUE TITLE
External terminal not logging Electron logs

### ISSUE THREAD

**Issue by laggingreflex** [microsoft/vscode#109216]
Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

---

**Steps to Reproduce:**

1. Create a [sample Electron project](https://www.electronjs.org/docs/tutorial/quick-start#create-the-main-script-file).

    In the main process log to console a sample text line
    ```
    const { app, BrowserWindow } = require('electron')
    ...
    console.log('SAMPLE TEXT LINE')
    ```
2. Open VSCode
3. Launch external terminal <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>C</kbd>
4. Run the electron app

    ```
    electron .
    ```

**Expected:**

It should log

```
electron .
SAMPLE TEXT LINE
```

**Actual:**

Nothing is logged
```
electron .
```

---

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
It looks like the environment is probably getting inherited from VS Code which could cause this as it's also an Electron app. We could try sanitizing the env:

https://github.com/microsoft/vscode/blob/cf4b5a703f581944f308b9a6f1e8b386059caef1/src/vs/base/common/processes.ts#L104

Here:

https://github.com/microsoft/vscode/blob/cf4b5a703f581944f308b9a6f1e8b386059caef1/src/vs/workbench/contrib/externalTerminal/node/externalTerminalService.ts#L101-L102

**Comment by keremgocen** [comment]
up for grabs I assume?

**Comment by Tyriar** [comment]
@keremgocen yep

**Comment by patlehmann1** [comment]
I'm willing to open a PR for this, would just need some background as I am completely green to this project. Would anyone be available to walk me through some things?

**Comment by Tyriar** [comment]
@patlehmann1 the basic changes needed are outlined here (note there are 2 places where spawn is called under Windows):

https://github.com/microsoft/vscode/issues/109216#issuecomment-719730398

Contributing docs are here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Comment by rolimans** [comment]
Is this issue being take care of? I'm looking to start contributing and thought I may help

**Comment by patlehmann1** [comment]
@rolimans, it looks like @jaykayitare has a pull request open that will close this issue.

**Comment by meganrogge** [comment]
fixed by https://github.com/microsoft/vscode/commit/2b81396e0a118ed739a313328892fea747732e8e
