### ISSUE TITLE
UI items are incorrect order when applying the language pack

### ISSUE THREAD

**Issue by bicstone** [microsoft/vscode#109286]
- VSCode Version: 1.50.1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. install [Japanese Language Pack](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-ja).

~~Git sub menu~~ UI items are incorrect order when applying the language pack.
~~Menu~~ UI items are sorted in ASC item name of after translation order.

Case:

| ja | en | 
| --- | --- |
| **Stash** (一時退避) <br> **Stash (Include Untracked)** (一時退避(未追跡ファイルを含む)) <br> **Drop Stash** (一時退避を削除する) <br> **Apply Stash** (一時退避内容を適用) <br> **Pop Stash** (一時退避内容を適用して削除) <br> **Apply Latest Stash** (最新の一時退避内容を適用) <br> **Pop Latest Stash** (最新の一時退避を適用して削除) | **Apply Latest Stash** <br> **Apply Stash** <br> **Drop Stash** <br> **Pop Latest Stash** <br> **Pop Stash** <br> **Stash** <br> **Stash (Include Untracked)**  |
| <img src="https://user-images.githubusercontent.com/47806818/97078078-3f34f100-1624-11eb-908f-9b781397d5d5.png" width="300"> | <img src="https://user-images.githubusercontent.com/47806818/97078083-49ef8600-1624-11eb-9728-f445da146b56.png" width="300"> |

Does this issue occur when all extensions are disabled?: Yes (only Japanese Language Pack)

**Comment by bicstone** [comment]
Changes button UI, too...

| ja | en |
| --- | --- |
| **Stash All Changes**(Stash All Changes) <br> **Stage All Changes**(すべての変更をステージ) <br> **Discard All Changes**(すべての変更を廃棄) | **Stash All Changes** <br> **Discard All Changes** <br> **Stage All Changes** | 
| <img src="https://user-images.githubusercontent.com/47806818/97080177-7ca17a80-1634-11eb-9883-4207e34e3992.png" width="300"> | <img src="https://user-images.githubusercontent.com/47806818/97080236-db66f400-1634-11eb-926d-41a80fd6a506.png" width="300"> |

| ja | en |
| --- | --- |
| **Open File** <br> **Discard Changes** <br> **Stage Changes** |  **Open File**(ファイルを開く) <br> **Stage Changes**(変更をステージ) <br> **Discard Changes**(変更を廃棄) |
| <img src="https://user-images.githubusercontent.com/47806818/97080191-9ba00c80-1634-11eb-8efc-43606825a0c4.png" width="300"> | <img src="https://user-images.githubusercontent.com/47806818/97080192-9cd13980-1634-11eb-8e47-b5a75abc9339.png" width="300"> |

**Comment by joaomoreno** [comment]
I believe this was a purposeful menu API decision.

**Comment by jrieken** [comment]
> I believe this was a purposeful menu API decision.

Nope. See I believe this was a purposeful menu API decision.

**Comment by bicstone** [comment]
>Nope. See https://code.visualstudio.com/api/references/contribution-points#Sorting-inside-groups

Thanks!
I want to try doing this.

**Comment by joaomoreno** [comment]
@jrieken I know I can manually sort these, but there are two problems I see:

1. It's an exhaustive process to sort and maintain proper sorting for each menu, as time goes by.
2. This would only fix one menu at the time. I can fix the git menus, but what about the others? While the user first submitted the issue about the Git menus, they then rewrote the issue to be about general UI menus.

Notice the user is talking about menus in general, so this applies to the default sort. If we don't want to change the default sort order, we should just close this issue.

**Comment by bicstone** [comment]
@joaomoreno I get it, Thanks!
If name of translation is changed, UI order would be unexpectedly changed.
As far as I'm concerned, It would be better to change the default so that UI items are inserted in the order they exist in the object.

**Comment by bicstone** [comment]
/verified

It works!

![スクリーンショット 2020-10-30 093820](https://user-images.githubusercontent.com/47806818/97647088-b212f180-1a94-11eb-829a-44baae6b87a7.png)
![スクリーンショット 2020-10-30 093926](https://user-images.githubusercontent.com/47806818/97647091-b3dcb500-1a94-11eb-8d67-45664ddc457c.png)

VS Code version: Code - Insiders 1.51.0-insider (2ee8b8c645ec8ab54304bacae7aa979c1d9c647a, 2020-10-29T06:01:21.160Z)
OS version: Windows_NT x64 10.0.19041
