### ISSUE TITLE
Crash in VScode latest for ubuntu 20.10

### ISSUE THREAD

**Issue by bird-in-hat** [microsoft/vscode#109245]
- VSCode Version: 1.50.1-1602600906
- OS Version: ubuntu 20.10

Steps to Reproduce:

1. Upgrade to ubuntu 20.10
2. Launch vscode

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
Please provide more information using the following guide:

/needsMoreInfo

**Comment by bird-in-hat** [comment]
Sorry. Seems like it new ubuntu 20.10 or hardware problem, not vscode.

**Comment by gwolf2u** [comment]
> Sorry. Seems like it new ubuntu 20.10 or hardware problem, not vscode.

@bird-in-hat 
fixed it?
having same issue

**Comment by bird-in-hat** [comment]
@gwolf2u 
No :( Tried everything, even downgrade to 20.04. But now it appears even in 20.04. Gonna sell laptop.
