### ISSUE TITLE
"Could not fetch remote environment" on WSL2 Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by h1tech** [microsoft/vscode#109297]
- VSCode Version: 1.50.1
- OS Version: Windows 10 2004 19041.572

While trying to use VSCode on WSL Ubuntu, i am getting the error from the title, i searched through all same issues and still didn't found the solution to this problem.

Have anyone found the solution to the similar/same problem?

**Comment by Tyriar** [comment]
Hmm, we actually just changed the code around this dramatically so I'd say wait for 1.51.0 to see if it's fixed (or try insiders) and let us know if it's not.

FYI @roblourens

**Comment by h1tech** [comment]
> 
> 
> Hmm, we actually just changed the code around this dramatically so I'd say wait for 1.51.0 to see if it's fixed (or try insiders) and let us know if it's not.
> 
> FYI @roblourens
Thank you for the explanation, will be waiting for an update!
