### ISSUE TITLE
Cannot mass-copy messages from the Problems window

### ISSUE THREAD

**Issue by chriskush** [microsoft/vscode#109263]
Issue Type: <b>Bug</b>

In the **Problems** pane, right-clicking provides options to **Copy** or **Copy Message**, but **Select All** is not available.

Pressing `CTRL+A` appears to work - everything gets highlighted - but pressing `CTRL+C` only copies a single entry.

It would be nice if, as with search results, one could treat the contents of the **Problems** Window as data, so one could, for example, generate a report for their team of all the warnings they have to fix, etc.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (7.23GB free)|
|Process Argv|--crash-reporter-id 5021c1ca-a526-46e0-ac29-364923fa1827|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.37.1
xml|Dot|2.5.1
vscode-html-css|ecm|0.2.3
scad|efb|1.0.1
vscode-edit-csv|jan|0.4.2
jenkins-pipeline-linter-connector|jan|1.2.0
zenuml|MrC|0.5.4
vscode-docker|ms-|1.7.0
csharp|ms-|1.23.4
python|ms-|2020.9.114305
remote-containers|ms-|0.145.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.1
cpptools|ms-|1.0.1
powershell|ms-|2020.6.0
vscode-groovy-lint|Nic|1.2.9
rewrap|stk|1.13.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/105657
