### ISSUE TITLE
Live share in windows 7

### ISSUE THREAD

**Issue by Pratyush3** [microsoft/vscode#109296]
Issue Type: <b>Feature Request</b>

I am not able to start live share on my laptop that has windows 7. I can't understand what's the problem. Please let me know about this.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.1.7601

**Comment by connor4312** [comment]
Please open an issue on https://github.com/MicrosoftDocs/live-share
