### ISSUE TITLE
VS Code does not work with Samsung Easy Setting Box

### ISSUE THREAD

**Issue by cool-html5** [microsoft/vscode#109288]
Issue Type: <b>Bug</b>

Download Samsung's easy setting box application from https://displaysolutions.samsung.com/support/resources/product-support/easy+setting+box

Install and test with VS Code, you will notice that it does not work with VS Code. It works fine with e.g. Visual Studio and most other applications.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (20.43GB free)|
|Process Argv|--crash-reporter-id f0ce765f-4741-4fb3-9de0-f292eb8ae462|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
prettier-vscode|esb|5.7.1
vscode-test-explorer|hbe|2.19.1
json-escaper|jos|1.1.0
vscode-docker|ms-|1.7.0
csharp|ms-|1.23.4
remote-wsl|ms-|0.50.1
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.3046
debugger-for-chrome|msj|4.12.11
vscode-jest-test-adapter|rtb|0.2.0
stylelint|shi|0.51.0

</details>

**Comment by deepak1556** [comment]
I haven't used this, does it work with chrome or edge ?

**Comment by cool-html5** [comment]
_Easy Setting Box SW enables users to partition the screen into various layouts of multiple sections so as to multi-task._

So that is what this sw does, similar to windows key + right/left, it let's you position any application to a specific part of the screen. It seems to work with almost any application (as you drag the screen and press CTRL, there will be an area in the top center of the screen that lets you decide where to place that particular application). For some reason the area in the top will not activate when I am dragging the VS code application. It works fine with Chrome and Edge.

**Comment by cool-html5** [comment]
![image](https://user-images.githubusercontent.com/20070567/97223814-f3777880-17d8-11eb-986e-fde5af766859.png)

**Comment by deepak1556** [comment]
Can you check if this is an issue with latest insiders https://code.visualstudio.com/insiders/ , we had some fixes go in for the frameless windows which I think might fix your issue.

**Comment by cool-html5** [comment]
Sorry, it did not solve the problem. I installed the insider build but it did not solve the issue.

**Comment by deepak1556** [comment]
Can you provide a screen recording of the issue, thanks!

A temporary workaround would be to use the setting `"window.titleBarStyle": "native"`

**Comment by cool-html5** [comment]
![image](https://user-images.githubusercontent.com/20070567/97228246-4e13d300-17df-11eb-9cd9-499addd2712c.png)

**Comment by cool-html5** [comment]
Yes, this helped, now it works! Thanks a lot.
