### ISSUE TITLE
Error when trying to search on a single file - ENOENT rg.exe

### ISSUE THREAD

**Issue by nikonso** [microsoft/vscode#109246]
Issue Type: <b>Bug</b>

When I try to search I get the following error
![image](https://user-images.githubusercontent.com/16099035/97026329-26a7d680-1551-11eb-9e76-c396db6635ed.png)

Console output below
`[IPC Library: Search] Error: spawn c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe ENOENT

at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)     
at onErrorNT (internal/child_process.js:456:16)    
 at processTicksAndRejections (internal/process/task_queues.js:81:21) 
t.log @ console.ts:70
(anonymous) @ ipc.cp.ts:185
fire @ event.ts:535
n @ event.ts:322
emit @ events.js:223
emit @ internal/child_process.js:876
processTicksAndRejections @ internal/process/task_queues.js:82`

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|32.00GB (15.02GB free)|
|Process Argv|--crash-reporter-id 7a378df6-2271-42ee-a955-7f5d46d0b3c7|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
xml|Dot|2.5.1
beautify|Hoo|1.5.0
rest-client|hum|0.24.3
sftp|lix|1.12.9
rainbow-csv|mec|1.7.1
csharp|ms-|1.23.4
vscode-dotnet-runtime|ms-|0.1.2
mssql|ms-|1.9.0
powershell|ms-|2020.6.0
azurerm-vscode-tools|msa|0.13.0
material-icon-theme|PKi|4.3.0
open-in-browser|tec|2.0.0
gitblame|wad|6.0.0

(1 theme extensions excluded)

</details>

**Comment by nikonso** [comment]
Also, I checket that the file is there..

![image](https://user-images.githubusercontent.com/16099035/97027013-104e4a80-1552-11eb-8333-38e4df258b5f.png)

And I'm running code as an admin so in theory it shouldn't be permissions related.

**Comment by nikonso** [comment]
One more thing, If I remove the part in blue from the filter the error no longer occurs
![image](https://user-images.githubusercontent.com/16099035/97027363-85ba1b00-1552-11eb-97ac-9fb6ef0080a4.png)

**Comment by roblourens** [comment]
Searching with a single file path is not supported, this is https://github.com/microsoft/vscode/issues/20530

**Comment by nikonso** [comment]
In reality it is, if I use a relative path instead of an absolute one it works, so I don't think that this is the same issue as the other one.

Relative path: It works and I can use the niceties of the search widget
Absolute path: throws the error above.

Given that I would say that this an actual and different bug, as my request does not have anything to do with the linked issue.

**Comment by roblourens** [comment]
A relative path will work because it will be treated as a glob pattern that matches one file. An absolute path will be treated as a folder and throw this error. Sorry for the bad experience here but it needs some work and I consider it under the linked issue.
