### ISSUE TITLE
Slow startup when extensions View is visible

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#109261]
Issue Type: <b>Performance Issue</b>

When starting/restarting vscode if the active View is Extensions View the entire editor is frozen for ~10 seconds and, sometimes, crashes the window.

[CPU-20201023T221617.zip](https://github.com/microsoft/vscode/files/5431454/CPU-20201023T221617.zip)

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
/duplicate

#109516
