### ISSUE TITLE
Provide LSP Samples for folder level validation

### ISSUE THREAD

**Issue by ShenChen-Amazon** [microsoft/vscode#109268]
Hi,
Actually i've asked same question at stackOverflow: https://stackoverflow.com/questions/64433585/how-to-use-vscode-extension-to-verify-folder-structure, but seems it's ignored somehow.

 I am building a LSP Vscode extension. One of the feature I want to achieve is to detect whether there's a folder named as 'foo'  under developer's opened workspace. If that folder exist, I also want to check whether there is a file 'bar.json' under that folder. If folder doesn't exist, the extension should keep silent. But if the folder exist, it will run validations against that folder and see the folder structure is as expected.

I am not sure if it's supported feature in vscode. I've seen vscode has feature that when I move module A to a different path, vscode will automatically ask me if i want to update the import path on B module which depend on A module. However, it's hard for me to find out folder structure level validations in vscode docs and samples. Thus would like to know if there's any instruction or samples I could follow. Would really appreciate if anyone could give me any hints on how to implement this feature.

Thanks,
Shen

**Comment by dbaeumer** [comment]
Actually this has nothing to do with LSP in terms of activation. You might wan to look at the following two VS Code API concepts:

- https://code.visualstudio.com/api/references/activation-events#workspaceContains
- file events: https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts#L9920
