### ISSUE TITLE
CustomTextEditorProvider has no retainContextWhenHidden

### ISSUE THREAD

**Issue by quantrpeter** [microsoft/vscode#109205]
Hi
   CustomTextEditorProvider has no retainContextWhenHidden, how can we make a useful custom editor if it reload everything when lost-and-regain focus? How people resolve it?
Thanks
Peter

**Comment by mjbvz** [comment]
`registerCustomEditorProvider` takes a set of webviewOptions that can set `retainContextWhenHidden`: https://github.com/microsoft/vscode/blob/f3e58fbdd06169cd1d8de3ba81c763867e9808d9/src/vs/vscode.d.ts#L8475

**Comment by quantrpeter** [comment]
it takes webviewoption, not webviewpaneloption.

取得 Android 版 Outlook<https://aka.ms/ghei36>

________________________________

**Comment by mjbvz** [comment]
The types say otherwise

**Comment by quantrpeter** [comment]
thank you my hero
