### ISSUE TITLE
Deprecated tag support for TypeScript not working over SSH

### ISSUE THREAD

**Issue by praneshr** [microsoft/vscode#109218]
- VSCode Version: 1.50.1
- OS Version: macOS Catalina v10.15.2
- Typescript version: v3.9.5

Steps to Reproduce:

1. SSH into a remote machine using vscode remote extension.
2. Create two files `.ts` file. One with a exported class with one deprecated method. Another importing the class and initializing the class.
3. Try calling the deprecated method in the second file. No strikethrough will be added.

![image](https://user-images.githubusercontent.com/10805204/96975561-3b2ba500-1538-11eb-9854-807b5639bd31.png)

On hovering over the method, shows it as deprecated.

![image](https://user-images.githubusercontent.com/10805204/96975616-4f6fa200-1538-11eb-8ab8-fd9a97ce885e.png)

Also, will adding `@deprecated` in the typings(`*.d.ts`) will also work? I couldn't find info about this in the release notes.

Does this issue occur when all extensions are disabled?: Cannot test this as vscode remote extension is required to SSH.

**Comment by IllusionMH** [comment]
/needsMoreInfo

What version of TS is used on remote host and  what is configuration of `"typescript.tsdk"`?

**Comment by praneshr** [comment]
I'm using typescript@3.9.5 in my remote and `typescript.tsdk` points to the `lib` of typescript@3.9.5

**Comment by IllusionMH** [comment]
/question

Deprecated tag only supported starting from 4.0 https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#deprecated-support

You should either update TS in project or change setting to use built-in TS version.
