### ISSUE TITLE
Web: allow to download folders with files

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109284]
Refs: https://github.com/microsoft/vscode/issues/83579

- [x] web @aeschli (Edge)
- [x] web @meganrogge (Chrome)

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23109284%0A%0A)

---

**Note**: this ONLY works in Chrome + Edge browsers!

**Test:**
* you see a `Download...` action when you right click on folders in the file explorer
* clicking it allows you to download the folder with all children to a location on disk
* you see progress in the status bar for long running ops
* you can cancel the download once you click on the progress and into the notification "Cancel" button
* verify the contents you downloaded match the structure in the file explorer and file contents

**Comment by JacksonKearl** [comment]
@meganrogge you can close the issue out if you're the last to test it.
