### ISSUE TITLE
Descriptions of "unusual line terminators" setting options when hovering mouse over them are mixed up.

### ISSUE THREAD

**Issue by Nekto222** [microsoft/vscode#109260]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open settings
2. Go to "unusual line terminators" and hover mouse over different options to see that they are mixed up.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/49713360/97045712-e9f2d400-157e-11eb-9631-894c697e4d21.png)
![image](https://user-images.githubusercontent.com/49713360/97045748-fbd47700-157e-11eb-904d-21fe3c580d6f.png)
![image](https://user-images.githubusercontent.com/49713360/97045769-068f0c00-157f-11eb-93ed-5547f5c436ed.png)

**Comment by roblourens** [comment]
@mjbvz 64b2a7b0bd4e593e20c1fb02002910909afda4a6 :)
