### ISSUE TITLE
"Restart typescript server" missing once again

### ISSUE THREAD

**Issue by stoplion** [microsoft/vscode#109262]
"Restart typescript server" command is missing.

I see this issue:
https://github.com/microsoft/vscode/issues/25382

_It was closed as a dupe of this one:_

https://github.com/microsoft/vscode/issues/22335
_That was closed by a bot_

[and this closed one](https://github.com/Microsoft/vscode/issues/67892)

and so on.. but this still happens

I had the "restart typescript server" last month. Now it's gone.

VSCODE Version: 1.50.1

This works ok on VSCode Insiders

**Comment by mjbvz** [comment]
/needsMoreInfo

Also, are you in a js/ts file when running this command?
