### ISSUE TITLE
visual code 2020

### ISSUE THREAD

**Issue by 0too** [microsoft/vscode#109292]
- VSCode Version:1.50.1
- OS Version:10 home

Steps to Reproduce:
I'm trying to run a program in the c ++ language in visual code, with the extension RUN CODE. And I get a "cout" error
and "cin" indeterminate.Language c works perfectly but c++ does not work.

I don't know why it doesn't work, but I remember that one day I was coding and I accidentally clicked on a line of code and another file opened with hundreds of lines and I think I deleted something from there.

-----------------------------------------------------------------------------------------------------------------------------------
#include <iostream>
using namespace std;
int main()
{
    int a;
    cout << "Dati un number:"<<endl;
    cin<<a<<endl;
    cout<<a;
    return 0;
}
-----------------------------------------------------
TASK JSON
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "g++",
            "args": [
                "-g",
                "main.cpp"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
----------------------------------------------------------------
This is the error:
РёРґРµРЅС‚РёС„РёРєР°С‚РѕСЂ "cout" РЅРµ РѕРїСЂРµРґРµР»РµРЅ
{
	"resource": "/d:/Visual Studio/dace/main.cpp",
	"owner": "C/C++",
	"code": "20",
	"severity": 8,
	"message": "РёРґРµРЅС‚РёС„РёРєР°С‚РѕСЂ \"cout\" РЅРµ РѕРїСЂРµРґРµР»РµРЅ",
	"source": "C/C++",
	"startLineNumber": 8,
	"startColumn": 5,
	"endLineNumber": 8,
	"endColumn": 9
}

РёРґРµРЅС‚РёС„РёРєР°С‚РѕСЂ "cin" РЅРµ РѕРїСЂРµРґРµР»РµРЅ
{
	"resource": "/d:/Visual Studio/dace/main.cpp",
	"owner": "C/C++",
	"code": "20",
	"severity": 8,
	"message": "РёРґРµРЅС‚РёС„РёРєР°С‚РѕСЂ \"cin\" РЅРµ РѕРїСЂРµРґРµР»РµРЅ",
	"source": "C/C++",
	"startLineNumber": 9,
	"startColumn": 5,
	"endLineNumber": 9,
	"endColumn": 8
}
-----------------------------------------------------------------------------------------------------------------
In terminal mesage
Windows PowerShell
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Попробуйте новую кроссплатформенную оболочку PowerShell (https://aka.ms/pscore6)

PS D:\Visual Studio\dace> cd "d:\Visual Studio\dace\" ; if ($?) { g++ main.cpp -o main } ; if ($?) { .\main }
In file included from c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\ostream:681:0,
                 from c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\iostream:39,
                 from main.cpp:1:
c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\bits\ostream.tcc:106:5: error: expected unqualified-id before '<<' token
     <<" "operator<<(int __n)
     ^~
c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\bits\ostream.tcc:106:5: error: expected initializer before '<<' token
PS D:\Visual Studio\dace> 
--------------------------------------------------------------------------------------------------------

I tried to download Visual code to another computer I installed the C ++ extensions MICROSOFT and RUN CODE
in the settings I chose
the section
RUN IN TERMINAL:
WHETHER TO RUN CODE IN INTEGRATED
I checked the option and everything went but the computer I work on does not work.

Thanks for help
please contact me by email: rucu.oktavian@mail.ru

**Comment by 0too** [comment]
Thanks for help

**Comment by 0too** [comment]
I wrote everything in English

**Comment by 0too** [comment]
please help my

**Comment by 0too** [comment]
I spent days solving the problem and I didn't succeed

**Comment by rikerfi** [comment]
Hi,
just one comment about the first line of source
Instead of 
**#include**
it should be
**#include <iostream>**

Cheers.

**Comment by 0too** [comment]
there is no difference

**Comment by 0too** [comment]
#include
it should be
#include

**Comment by 0too** [comment]
I wrote the code quickly, but in visual code everything is correct, here is a program that used to work.
#include <iostream>

using namespace std;

int main()
{
    int v1, v2, v3;
    int max, min;

    cout << "Dati virsta pentru v1 = ";
    cin >> v1;
    cout << "Dati virsta pentru v2 = ";
    cin >> v2;
    cout << "Dati virsta pentru v3 = ";
    cin >> v3;

    if (v1 > v2)
    {
        max = v1;
    }
    else if (v2 > v3)
    {
        max = v2;
    }
    else
    {
        max = v3;
    }

    if (v1 < v2)
    {
        min = v1;
    }
    else if (v2 < v3)
    {
        min = v2;
    }
    else
    {
        min = v3;
    }

    cout << "\n";
    cout << "Cea mai mare virsta este : " << max << endl;
    cout << "Cea mai mica virsta este : " << min;

    return 0;
}

**Comment by 0too** [comment]
I forgot in the first line is
#include <iostream>

**Comment by 0too** [comment]
<iostream>

**Comment by 0too** [comment]
iostream
