### ISSUE TITLE
Unable to get intelesens for C# on a multi folder structure 

### ISSUE THREAD

**Issue by afoliaco** [Microsoft/vscode#10929]
- VSCode Version: 1.4
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create the following folder structure 
SampleCode/src/Project1
SampleCode/src/Project2
2. Run dotnet new and dotnet restore to create the applications  and the new application restore all the correct dependencies. 
3. Create sample class in Project2 and add the Project2 reference on  Projec1 project.json. 

Note: I create this repo for duplication https://github.com/afoliaco/InventoryServices, also you can see question on StackOverflow http://stackoverflow.com/questions/39124742/vscode-multiples-projects-reference

**Comment by sandy081** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#713
