### ISSUE TITLE
Scrolling away from rename dialog leaves editor unfocused

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#109266]
Repro:

1. F2 on a symbol
2. Scroll away
3. Scroll back

![recording](https://user-images.githubusercontent.com/2193314/97054262-577c1180-1539-11eb-8d67-9bd6d22efe41.gif)

Escape doesn't return focus, only ctrl+z seems to. `document.activeElement` is `body` in this state.

**Comment by jrieken** [comment]
The fun part is that the editor is sending a blur-event (`onDidBlurEditorWidget`) and because of that the rename widget doesn't give back focus to the editor (since it assumes that the something else has been focused)

**Comment by jrieken** [comment]
/cc @alexdima since I don't believe the editor blur is intentional. To debug/trace apply this

```diff
diff --git a/src/vs/editor/contrib/rename/renameInputField.ts b/src/vs/editor/contrib/rename/renameInputField.ts
index 2be443c8c55..c6ed1ac9512 100644
--- a/src/vs/editor/contrib/rename/renameInputField.ts
+++ b/src/vs/editor/contrib/rename/renameInputField.ts
@@ -144,6 +144,7 @@ export class RenameInputField implements IContentWidget {
        }
 
        cancelInput(focusEditor: boolean): void {
+               console.trace(focusEditor);
                if (this._currentCancelInput) {
                        this._currentCancelInput(focusEditor);
                }
```

**Comment by jrieken** [comment]
Turns out the newly added `IContentWIdget#afterRender` is helpful here.
