### ISSUE TITLE
backspace shows two characters as deleted with git bash

### ISSUE THREAD

**Issue by binyamin** [microsoft/vscode#109248]
- VSCode Version: 1.51.0-insiders
- OS Version: Windows 10 (2004)

Steps to Reproduce:
1. Set the default terminal to git bash
2. type `echo hi` in the terminal
3. press backspace once. (only `echo<space>` will be shown)
4. Press enter. (`h` will be printed).

Does this issue occur when all extensions are disabled?: Yes

**Comment by markgoho** [comment]
https://www.loom.com/share/237257c3a1be42968b144d76d11919c2

**Comment by espenja** [comment]
This is happening for me too with cmder set as terminal. It even deletes the λ character in the cmder prompt which isn't supposed to be removable.

Version: 1.51.0-insider (user setup)
Commit: b72c840ba04850dcd56be0f3ad843ee92067c8c6
Date: 2020-10-23T05:36:43.869Z
Electron: 9.3.2
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Tyriar** [comment]
You can enable escape sequence logging, this will tell us whether it's an issue with VS Code or whether your shell/program is telling VS Code to delete those 2 characters: https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging

**Comment by binyamin** [comment]
I typed `gh`, and hit backspace. Here's the log.

```log
LogService.ts:76 xterm.js: sending data "g" [103]
LogService.ts:76 xterm.js: parsing data g
LogService.ts:76 xterm.js: sending data "h" [104]
LogService.ts:76 xterm.js: parsing data h
LogService.ts:76 xterm.js: sending data "" [127]
LogService.ts:76 xterm.js: parsing data 
LogService.ts:76 xterm.js: parsing data [K
```

**Comment by Tyriar** [comment]
@binyamin if you copy and paste the � chars in the devtools console and run `'�'.charCodeAt(0)` what does it come out as? GitHub might be sanitizing the characters.

**Comment by binyamin** [comment]
8,8,27

**Comment by Tyriar** [comment]
What these sequences that we receive from the program do:

- `8`: Move cursor to left 1 cell
- `8`: Move cursor to left 1 cell
- `\x1b[K`: Erase all cells to the right of the cursor (inclusive)

So it seems like this is an issue with either git bash itself or conpty (what launches the process and emulates unix ptys), you could try reproduce in Windows Terminal and report there if it happens there too, but there's unfortunately nothing we can do on our end here.

**Comment by binyamin** [comment]
@Tyriar it doesn't happen in windows terminal. Where does that leave this? conpty?

**Comment by Tyriar** [comment]
That's my guess, WT is on a newer version of conpty as it's built with it whereas we use the one bundled with Windows, perhaps that's the issue? Or Git Bash treats WT differently to VS Code?

**Comment by binyamin** [comment]
It's working for me today (latest update?)
@markgoho @espenja Is it working for you?

**Comment by espenja** [comment]
> It's working for me today (latest update?)
> @markgoho @espenja Is it working for you?

@binyamin 
I can't reproduce this anymore either. Tested with Cmder, Git Bash and WSL.

Version: 1.51.0-insider (user setup)
Commit: 2d8bbc6976748c4b0c5e84be541674b89b9d91e4
Date: 2020-10-30T06:57:39.786Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by markgoho** [comment]
@binyamin no more backspace bug for me, yay!
