### ISSUE TITLE
"Starting..." label on remote terminals doesn't show up until the remote is already connected

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#109259]
When a remote terminal is started, we expect to set a "Starting..." title for the terminal when launched before the remote is connected. But, we delay this until after a call to the remote agent finishes, so that title only appears for a brief moment.

I think this is a regression from months ago. https://github.com/microsoft/vscode/blob/c131e8bd6d0a03a9115785e7158697efeb69fd4e/src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts#L153 it looks like it would be fine to not wait for userHome/os before starting the terminal, but I won't change it now.

**Comment by Tyriar** [comment]
Yes this is probably safe to change back:

https://github.com/microsoft/vscode/commit/8046b7306628158f2421285f81e2b2eb751e87c6
