### ISSUE TITLE
Intellisense suggestion gets ellipsized

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#109384]
- VSCode Version: 1.51
- OS Version: Linux

The first suggestion of Intellisense is ellipsized.

Because of this, I can't differentiate the first one from the second one.

I'm flagging it as a bug because in previous versions, the first suggestions was not uselessly ellipsized.

**VS Code 1.51**

![Capture du 2020-10-26 15-38-30](https://user-images.githubusercontent.com/15984272/97187241-8ea12b80-17a2-11eb-8bea-fbd5dd2b561d.png)

**VS Code 1.25** (arbitrarily old version)

![Capture du 2020-10-26 15-44-58](https://user-images.githubusercontent.com/15984272/97187236-8cd76800-17a2-11eb-85b6-8ae826bc2a0b.png)

Steps to Reproduce:

1. Open a Typescript editor. Any language will do, this is for illustration.
2. Try Intellisense anywhere with a "long" type (gets ellipsisized even when full definition is 50 characters long)
Here is an example if you want.
```ts
type PositionSolver = (a: PositionSolver, b: PositionSolver) => void
let a : 
```

![Capture du 2020-10-26 15-38-30 (copie)](https://user-images.githubusercontent.com/15984272/97188516-dffdea80-17a3-11eb-9a53-0254c09b38cd.png)

Of course in this case `Position` still appears after `alias` but
- it only works for suggestions less than ~18 charactersl ong
- I expect all suggestions to appear in a row, not the first one on the right and the other ones on the left

Does this issue occur when all extensions are disabled?: Yes

Old (good)
```
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
```

New (bad)
```
Version: 1.51.0-insider
Commit: 89c002ab02f87102d91efc83c191ef1174756c6a
Date: 2020-10-16T05:12:37.273Z (1 wk ago)
Electron: 9.3.2
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-120-generic
```

Thank you

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest

**Comment by jrieken** [comment]
YSK that you press Ctrl+Space to get the details to show in the extra details panel

**Comment by sguillia** [comment]
Aaaah pressing `Ctrl+Space` toggles the **details** permanently and for all editors... Great, this acts like a setting, issue solved
