### ISSUE TITLE
Test suggest status bar

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109396]
Refs: 

- [x] anyOS @digitarald
- [x] anyOS @sana-ajani

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23109396%0A%0A)

---

The suggest widget has now an optional status bar. Test that

* the status bar can be toggled via `editor.suggest.statusBar.visible`
* the status bar shows a hint to toggle details 
* the status bar shows Insert and Replace gestures if applicable, e.g trigger suggest inside `console`
* the status bar behaves correctly when having `editor.suggest.insertMode` configured (per user and per language)

**Comment by sana-ajani** [comment]
Nice! Tested the `editor.suggest.insertMode` with JS/TS and HTML files and the status bar behaves correctly.

**Comment by digitarald** [comment]
Love it as onboarding to more users to the advanced replace/details features.

- [x] the status bar can be toggled via editor.suggest.statusBar.visible
- [x] the status bar shows a hint to toggle details
- [x] the status bar shows Insert and Replace gestures if applicable, e.g trigger suggest inside console
- [x] the status bar behaves correctly when having editor.suggest.insertMode configured (per user and per language)

**Comment by jrieken** [comment]
Thanks. Let's discuss for next release to turn it on by default
