### ISSUE TITLE
Middle-clicking on a notification sometimes pastes the contents of the clipboard

### ISSUE THREAD

**Issue by contribucious** [microsoft/vscode#109322]
- VSCode Version: **1.50.1** _(Stable)_ / **1.51.0-insider** _(Insiders in its latest version, with the same problem)_
- OS Version: Linux Mint 19.3 (Cinnamon D.E.) [Linux x64 5.4.0-52-generic]

- Does this issue occur when all extensions are disabled?: Yes
&nbsp;

## Steps to reproduce

1. First, make sure you have some text in your clipboard.
2. Now, open a file in VSCode.
3. Wait for a notification or arrange for a notification to appear (at the bottom right).
4. Middle-click on it (at any position) — i.e. click on the mouse wheel.

## Expected result

The notification closes.

## Actual result

The notification closes.

:arrow_right: But ... sometimes (seemingly randomly), in addition to that, the contents of the clipboard are pasted into the currently open file _(normal and desired behavior under Linux in normal times but not in this case)_.

:arrow_right_hook: In the case of two consecutive notifications for example, one may not have this problem and when the next one is closed in the same way, the problem will arise(*).

(*) _(At least here, technically speaking, this can probably be explained by the fact that once the last notification is closed, it is the file in the editor that receives the focus. But in all cases, with the same action on the various notifications, the same result is expected IMHO.)_
&nbsp;

___
Thanks in advance! :thumbsup:

**Comment by bpasero** [comment]
I cannot explain why this happens, since we cancel the event and stop propagation, but up for help if someone wants to try it out:

https://github.com/microsoft/vscode/blob/ef169aecd7912897d5fd716243bf672109dca3b8/src/vs/workbench/browser/parts/notifications/notificationsViewer.ts#L309-L315

**Comment by contribucious** [comment]
Thank you @jeanp413 (and @bpasero). It was fast! :v:

As soon as the fix is available in the Insiders version, I will test it and keep you informed. :thumbsup:

**Comment by contribucious** [comment]
I can confirm that the problem is fixed in the latest **VS Code Insiders** release. :thumbsup:

:arrow_right_hook: Problem **not** reproducible using `code-insiders` (version https://github.com/microsoft/vscode/commit/e5c0007ce0e9a3816679cba674d03376c03726e3) and reproducible using `code`.
&nbsp;

Thanks again @jeanp413 (and @bpasero). :wink:
