### ISSUE TITLE
View action bar hides on submenu

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#109305]
Related to: https://github.com/microsoft/vscode/issues/92029

While the original #92029 issue is fixed, this is another case.

1. Add a submenu as a command in a view's title
1. Click on the submenu and it will hide the action bar

**Comment by sbatten** [comment]
> Add a submenu as a command in a view's title

can you elaborate on the steps here or provide some min repro code?

**Comment by eamodio** [comment]
If you install the latest GitLens 11 RC2, it has this issue

![hide](https://user-images.githubusercontent.com/641685/97234860-1180b100-17b8-11eb-8f4d-264ecf92ebc4.gif)
