### ISSUE TITLE
CodeLens not working

### ISSUE THREAD

**Issue by marxus562** [microsoft/vscode#109351]
Pretty much the codeLens won't appear on any of my scripts dispite restarting, redownloading, reseting setting, and anything I saw on online blogs. I'm pretty sure it stopped working after I downloaded one of the most recent updates and assusmed it just didn't download correctly but I still can't get it to show up. I don't know how to re-create it because it kinda just happened on it's own.

**Comment by marxus562** [comment]
> I forgot to mention that it not just my codeLens, but pretty much all basic information about my code is gone. Like if i have an incorrect line of code or a variable that isn't used, none of the error or warning lines pop up to tell me anything.

**Comment by mjbvz** [comment]
Please fill in the issue template. Also what code lens is this?

/needsMoreInfo
