### ISSUE TITLE
Laggy.

### ISSUE THREAD

**Issue by JimmyBenHur** [microsoft/vscode#109335]
Issue Type: <b>Performance Issue</b>

It occures a few minutes after starting VSCode. The screen starts lagging very much and it gets unusable, so I have to restart it.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.8.0-25-generic

**Comment by gjsjohnmurray** [comment]
Please review https://github.com/microsoft/vscode/wiki/Performance-Issues and add information here.
