### ISSUE TITLE
Active text editor doesn't provide symbol information in javascript

### ISSUE THREAD

**Issue by NaveenDA** [microsoft/vscode#109319]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open the editor and press CMD+P
2. Now type @
<img width="785" alt="Screenshot 2020-10-25 at 2 29 58 PM" src="https://user-images.githubusercontent.com/20555082/97102814-97c0c880-16ce-11eb-9f12-57282b586f7e.png">

Note: It was worked before. A few days before I uninstalled some least used extension. That may be cause issue 

Does this issue occur when all extensions are disabled?: Yes

**Comment by NaveenDA** [comment]
After reinstalling the vscode it works, so closing this issue

**Comment by neohunter** [comment]
after reinstalling.... thats like... non sense, so each issue we have thats the solution?

I've the same issue on my mac, and the same is happening on installation on linux.
