### ISSUE TITLE
Takes around 20 seconds to open everytime

### ISSUE THREAD

**Issue by devils2ndself** [microsoft/vscode#109337]
Issue Type: <b>Performance Issue</b>

Since I beleive last week or so VS Code started taking a lot of time to open regardless of how I do so (from file explorer -> right click, by a shortcut or even cmd). I read a bit about common issues but never found a similar to mine online. Here is the startup performance info:
<details>
## System Info

* Code: 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a)
* OS: win32(10.0.19041)
* CPUs: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz(12 x 2208)
* Memory(System): 15.85 GB(6.90GB free)
* Memory(Process): 171.25 MB working set(148.91MB private, 0.95MB shared)
* VM(likelyhood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                            | Duration | Process          | Info                                                     |
| --------------------------------------------------------------- | -------- | ---------------- | -------------------------------------------------------- |
| start => app.isReady                                            | 16228    | [main]           | initial startup: true                                    |
| nls:start => nls:end                                            | 0        | [main]           | initial startup: true                                    |
| require(main.bundle.js)                                         | 73       | [main]           | initial startup: true                                    |
| app.isReady => window.loadUrl()                                 | 199      | [main]           | initial startup: true                                    |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 312      | [main->renderer] | NewWindow                                                |
| require(workbench.desktop.main.js)                              | 772      | [renderer]       | cached data: YES, node_modules took 181.59000005107373ms |
| require & init workspace storage                                | 32       | [renderer]       | -                                                        |
| init workspace service                                          | 57       | [renderer]       | -                                                        |
| register extensions & spawn extension host                      | 252      | [renderer]       | -                                                        |
| restore viewlet                                                 | 21       | [renderer]       | workbench.view.explorer                                  |
| restore panel                                                   | 0        | [renderer]       | -                                                        |
| restore editors                                                 | 574      | [renderer]       | 1: workbench.editors.files.fileEditorInput               |
| overall workbench load                                          | 801      | [renderer]       | -                                                        |
| workbench ready                                                 | 18403    | [main->renderer] | -                                                        |
| renderer ready                                                  | 1674     | [renderer]       | -                                                        |
| extensions registered                                           | 18254    | [renderer]       | -                                                        |

## Extension Activation Stats

| Extension                           | Eager | Load Code | Call Activate | Finish Activate | Event                             | By                                  |
| ----------------------------------- | ----- | --------- | ------------- | --------------- | --------------------------------- | ----------------------------------- |
| vscode.debug-auto-launch            | true  | 6         | 0             | 5               | *                                 | vscode.debug-auto-launch            |
| vscode.emmet                        | true  | 13        | 1             | 4               | *                                 | vscode.emmet                        |
| vscode.git                          | true  | 23        | 2             | 2               | *                                 | vscode.github                       |
| vscode.github                       | true  | 11        | 0             | 0               | *                                 | vscode.github                       |
| vscode.merge-conflict               | true  | 8         | 1             | 1               | *                                 | vscode.merge-conflict               |
| vscode.search-result                | true  | 5         | 0             | 1               | *                                 | vscode.search-result                |
| vscode.configuration-editing        | false | 10        | 0             | 18              | onLanguage:jsonc                  | vscode.configuration-editing        |
| vscode.extension-editing            | false | 10        | 0             | 3               | onLanguage:markdown               | vscode.extension-editing            |
| vscode.github-authentication        | false | 10        | 1             | 6               | onAuthenticationRequest:github    | vscode.github-authentication        |
| vscode.json-language-features       | false | 41        | 10            | 8               | onLanguage:jsonc                  | vscode.json-language-features       |
| vscode.markdown-language-features   | false | 25        | 3             | 0               | onLanguage:markdown               | vscode.markdown-language-features   |
| vscode.microsoft-authentication     | false | 13        | 2             | 80              | onAuthenticationRequest:microsoft | vscode.microsoft-authentication     |
| ms-vscode.js-debug                  | false | 163       | 6             | 18              | onDebugDynamicConfigurations      | ms-vscode.js-debug                  |
| vscode.typescript-language-features | false | 16        | 3             | 6               | onLanguage:jsonc                  | vscode.typescript-language-features |

## Raw Perf Marks

```
Name	Timestamp	Delta	Total
main:started	1603667481896	0	0
main:appReady	1603667498124	16228	16228
willLoadMainBundle	1603667498171	47	16275
didLoadMainBundle	1603667498244	73	16348
main:loadWindow	1603667498323	79	16427
renderer/started	1603667498625	302	16729
willShowPartsSplash	1603667498626	1	16730
didShowPartsSplash	1603667498628	2	16732
willLoadWorkbenchMain	1603667498635	7	16739
didLoadWorkbenchMain	1603667499407	772	17511
main/startup	1603667499407	0	17511
willInitWorkspaceService	1603667499439	32	17543
willInitWorkspaceStorage	1603667499446	7	17550
didInitWorkspaceStorage	1603667499478	32	17582
didInitWorkspaceService	1603667499496	18	17600
willStartWorkbench	1603667499498	2	17602
LifecyclePhase/Ready	1603667499500	2	17604
willRestoreEditors	1603667499725	225	17829
willRestoreViewlet	1603667499774	49	17878
didRestoreViewlet	1603667499795	21	17899
willResolveExplorer	1603667499819	24	17923
willLoadExtensions	1603667499898	79	18002
didResolveExplorer	1603667499936	38	18040
willHandleExtensionPoint/configurationDefaults	1603667499979	43	18083
didHandleExtensionPoint/configurationDefaults	1603667499988	9	18092
willHandleExtensionPoint/configuration	1603667499988	0	18092
didHandleExtensionPoint/configuration	1603667500029	41	18133
willHandleExtensionPoint/jsonValidation	1603667500029	0	18133
didHandleExtensionPoint/jsonValidation	1603667500030	1	18134
willHandleExtensionPoint/commands	1603667500030	0	18134
didHandleExtensionPoint/commands	1603667500033	3	18137
willHandleExtensionPoint/submenus	1603667500033	0	18137
didHandleExtensionPoint/submenus	1603667500034	1	18138
willHandleExtensionPoint/menus	1603667500034	0	18138
didHandleExtensionPoint/menus	1603667500039	5	18143
willHandleExtensionPoint/debuggers	1603667500039	0	18143
didHandleExtensionPoint/debuggers	1603667500047	8	18151
willHandleExtensionPoint/breakpoints	1603667500047	0	18151
didHandleExtensionPoint/breakpoints	1603667500047	0	18151
willHandleExtensionPoint/notebookProvider	1603667500047	0	18151
didHandleExtensionPoint/notebookProvider	1603667500047	0	18151
willHandleExtensionPoint/notebookOutputRenderer	1603667500047	0	18151
didHandleExtensionPoint/notebookOutputRenderer	1603667500048	1	18152
willHandleExtensionPoint/problemPatterns	1603667500048	0	18152
didHandleExtensionPoint/problemPatterns	1603667500050	2	18154
willHandleExtensionPoint/problemMatchers	1603667500050	0	18154
didHandleExtensionPoint/problemMatchers	1603667500051	1	18155
willHandleExtensionPoint/taskDefinitions	1603667500051	0	18155
didHandleExtensionPoint/taskDefinitions	1603667500051	0	18155
willHandleExtensionPoint/terminal	1603667500051	0	18155
didHandleExtensionPoint/terminal	1603667500051	0	18155
willHandleExtensionPoint/viewsWelcome	1603667500051	0	18155
didHandleExtensionPoint/viewsWelcome	1603667500051	0	18155
willHandleExtensionPoint/authentication	1603667500051	0	18155
didHandleExtensionPoint/authentication	1603667500051	0	18155
willHandleExtensionPoint/keybindings	1603667500051	0	18155
didHandleExtensionPoint/keybindings	1603667500072	21	18176
willHandleExtensionPoint/languages	1603667500072	0	18176
didHandleExtensionPoint/languages	1603667500084	12	18188
willHandleExtensionPoint/codeActions	1603667500084	0	18188
didHandleExtensionPoint/codeActions	1603667500084	0	18188
willHandleExtensionPoint/customEditors	1603667500084	0	18188
didHandleExtensionPoint/customEditors	1603667500085	1	18189
willHandleExtensionPoint/snippets	1603667500085	0	18189
didHandleExtensionPoint/snippets	1603667500085	0	18189
willHandleExtensionPoint/grammars	1603667500085	0	18189
didHandleExtensionPoint/grammars	1603667500088	3	18192
willHandleExtensionPoint/colors	1603667500088	0	18192
didHandleExtensionPoint/colors	1603667500089	1	18193
willHandleExtensionPoint/semanticTokenTypes	1603667500089	0	18193
didHandleExtensionPoint/semanticTokenTypes	1603667500089	0	18193
willHandleExtensionPoint/semanticTokenModifiers	1603667500089	0	18193
didHandleExtensionPoint/semanticTokenModifiers	1603667500089	0	18193
willHandleExtensionPoint/semanticTokenScopes	1603667500089	0	18193
didHandleExtensionPoint/semanticTokenScopes	1603667500090	1	18194
willHandleExtensionPoint/themes	1603667500090	0	18194
didHandleExtensionPoint/themes	1603667500092	2	18196
willHandleExtensionPoint/iconThemes	1603667500092	0	18196
didHandleExtensionPoint/iconThemes	1603667500092	0	18196
willHandleExtensionPoint/viewsContainers	1603667500092	0	18196
didHandleExtensionPoint/viewsContainers	1603667500097	5	18201
willHandleExtensionPoint/views	1603667500097	0	18201
didHandleExtensionPoint/views	1603667500128	31	18232
extensionHostReady	1603667500130	2	18234
didLoadExtensions	1603667500150	20	18254
didRestoreEditors	1603667500299	149	18403
LifecyclePhase/Restored	1603667500299	0	18403
didStartWorkbench	1603667500299	0	18403
didRemovePartsSplash	1603667500299	0	18403
LifecyclePhase/Eventually	1603667502806	2507	20910
```

</details>
It says it takes around 16 seconds for app.IsReady. Never found such issue on the web

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.96GB free)|
|Process Argv|D:\#Projects\#Programming\C++\fstream --crash-reporter-id ebb68724-2c57-4da4-a930-2cb80705c5c8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    78	  3676	code main
    0	   169	  2244	   window (Startup Performance - fstream - Visual Studio Code)
    0	    12	 18984	     watcherService 
    0	    11	  2148	       console-window-host (Windows internal process)
    0	   108	 20236	     extensionHost
    0	    67	 24908	       "C:\Users\magic\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\magic\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=20236
    0	    87	  7780	   shared-process
    0	    27	 17872	   crashpad-handler
    1	   112	 20620	   gpu-process
    0	    38	 25584	   utility
    0	    82	 26380	   window (Issue Reporter)
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
vscode-npm-script|eg2|0.3.13
python|ms-|2020.9.114305
cpptools|ms-|1.1.0-insiders2
debugger-for-chrome|msj|4.12.11

(1 theme extensions excluded)

</details>

**Comment by devils2ndself** [comment]
oh yeah also, there is 1 thread about app.IsReady issue, but the guy just reinstalled windows, which is not how I want to solve it tbh. Also, not a single other app on my pc lags or starts up slowly apart from vs code so I doubt there is something wrong about my system.

**Comment by connor4312** [comment]
Please provide more information using these instructions: https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly

/needsMoreInfo

**Comment by devils2ndself** [comment]
[prof-a0b3.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/5440488/prof-a0b3.extHost.cpuprofile.txt)
[prof-a0b3.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/5440490/prof-a0b3.main.cpuprofile.txt)
[prof-a0b3.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/5440493/prof-a0b3.renderer.cpuprofile.txt)

**Comment by bpasero** [comment]
Smells like https://github.com/microsoft/vscode/issues/56644 or https://github.com/microsoft/vscode/issues/22087 to me

![image](https://user-images.githubusercontent.com/900690/97264961-1da35780-1826-11eb-8496-e37fe7a7cf7f.png)
