### ISSUE TITLE
Auto-completing React Native tags

### ISSUE THREAD

**Issue by sercanov** [Microsoft/vscode#10935]
- VSCode Version: 1.4.0
- OS Version: OS X Yosemite

I've already opened an issue in vscode-react-native repo but I think it's related to vscode itself.

Microsoft/vscode-react-native#247

When I need to insert a component or any tag, I have to write both opening and closing tags. Auto completion on these could be great to have.

Similar behavior is available on React with double TAB.

Example behavior on ; https://atom.io/packages/react

Thanks

**Comment by jrieken** [comment]
The completion framework allows you to do that. @aeschli is this something the html-language should do? be configured to do?

**Comment by rod-stuchi** [comment]
That would be great!
[Demo videos **atom-react**](https://orktes.github.io/atom-react/)

**Comment by lshaf** [comment]
will be really helpful

**Comment by mjbvz** [comment]
Closing as duplicate of #34307
