### ISSUE TITLE
Unable to select a folder using window.openFileDialog with a remote File System (using local workspace)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#109345]
- Version: 1.51.0-insider
- Commit: 7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9
- Date: 2020-10-23T07:32:22.213Z
- Electron: 9.3.2
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Darwin x64 19.6.0

**Steps to Reproduce:**

1. Create an extension and register a remote file system
2. Use the command `window.showOpenDialog` with `defaultUri` pointing to a directory on the remote file system.
3. VS Code will now select the remote file system folder picker (as expected).
4. Selecting a folder from the list results in the display of the message `The path does not exist.`.

VS Code seems to convert the remote path to a local path & perform some local FS operations on the path (to determine its validity, things fall over as the file doesn't exist, hence we get the incorrect message).

**Expected behavior**
- VS Code will return the selected remote folder.
- Looking at the code, 

**Note:**
* Not using any of the Remote extensions for VSCode
* I am on the local machine
* I have a local workspace folder opened
* I have registered a remote file system,

See below screenshot:
<img width="424" alt="Screen Shot 2020-10-25 at 21 19 33" src="https://user-images.githubusercontent.com/1948812/97133731-31589c00-1708-11eb-9093-32db985bbf1e.png">

Screenshots of the stack trace (hope this helps)

<img width="1004" alt="Screen Shot 2020-10-25 at 21 24 39" src="https://user-images.githubusercontent.com/1948812/97133926-c22f7780-1708-11eb-977e-e56c64aef936.png">
<img width="995" alt="Screen Shot 2020-10-25 at 21 25 21" src="https://user-images.githubusercontent.com/1948812/97133928-c52a6800-1708-11eb-97a1-c4487a271461.png">

Does this issue occur when all extensions are disabled?: No

**Comment by DonJayamanne** [comment]
Checked the existing issues, and they do not apply

**Comment by alexr00** [comment]
What is your `defaultUri`? I'm wondering if it has the correct scheme.

**Comment by DonJayamanne** [comment]
Default uri is `localhost888:/` and this is correct and that's why the folders are listed in the drop-down (ie it is display remote folders).

**Comment by alexr00** [comment]
Is it possible your files system provider is implemented incorrectly? It should be called as part of that call stack.

**Comment by DonJayamanne** [comment]
> Is it possible your files system provider

To my knowledge this is implemented correctly.
Agreed it should be cashed, but not, and that's why I posted that stack.

**Comment by alexr00** [comment]
Can you share the exact way you call `window.showOpenDialog`? You must also specify the [`availableFileSystems`](https://github.com/Microsoft/vscode/blob/b90805e1748f63b938b8295017452cbb048c26d1/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L159-L159) for the file picker to understand what to do. `availableFileSystems` is just an array of uri schemes.

**Comment by DonJayamanne** [comment]
Here's the code
```typescript
        const remoteFolders = await window.showOpenDialog({
            canSelectFiles: false,
            canSelectFolders: true,
            canSelectMany: false,
            defaultUri: fileSystem.rootFolder,
            openLabel: 'Folder to create notebook',
            title: `Select folder on Remote Server (${server.label})`
        });
```

FYI - I am an extension author, hence do not have access to internal VSCode API. `availableFileSystem` is not in the exposed API (https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts).

**Comment by alexr00** [comment]
That makes sense. Do you have a repo I could clone to try it out? I think I see the problem, but it would be good to confirm.

**Comment by DonJayamanne** [comment]
Thats good news, unfortunately the code is private, hence nothing I can share.
Should be easy to repro though (whipping up using a sample fs provider).

**Comment by DonJayamanne** [comment]
@alexr00 Do u still need some information (asking because of the current label `needs more info`)
Thanks

**Comment by alexr00** [comment]
@DonJayamanne no further info needed, thank you!

**Comment by rebornix** [comment]
@DonJayamanne does the fix work for you?

**Comment by rzhao271** [comment]
@alexr00 @DonJayamanne's steps don't look too hard but I'm wondering if you know what "register a remote file system" refers to? Is that part of the VS Code API, or does that mean setting up a remote file system on the side?

**Comment by JacksonKearl** [comment]
Using the below sample code (`npm i` => `f5` => `memFS: Open memFS`) I'm still seeing the "path does not exist error". 
[fsprovider-sample.zip](https://github.com/microsoft/vscode/files/5484876/fsprovider-sample.zip)

**Comment by DonJayamanne** [comment]
> does the fix work for you?

Will check, I didn't see a new insider build. Will double check

**Comment by alexr00** [comment]
Since this isn't a regression (it never worked), moving the fix to November.
To verify, use sample project here: https://github.com/microsoft/vscode/issues/109345#issuecomment-721451698
1. npm i
2. F5
3. Run the command  memFS: Open memFS
4. Verify that you can navigate into folders in the file dialog. (the sample doesn't actually open any files, just shows the dialog).

**Comment by DonJayamanne** [comment]
**Tested and confirm it does not work.**

Version: 1.52.0-insider
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:39:23.276Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by alexr00** [comment]
@DonJayamanne thanks for trying to verify! Are you still seeing the exact same bad behavior? With the [sample project](https://github.com/microsoft/vscode/issues/109345#issuecomment-721451698) I can no longer repro the issue.

**Comment by DonJayamanne** [comment]
Odd, I can still repro this. However using the VSCode extensions examples I can no longer repro this.
Will have to check why its not working in my extension.
Lets assume this is closed for now, I'll need to debug my extension separately.

**Comment by alexr00** [comment]
Thanks @DonJayamanne. Feel free to ping again if you discover that the issue is still present.
