### ISSUE TITLE
wiew

### ISSUE THREAD

**Issue by abtemir** [microsoft/vscode#109309]
Issue Type: <b>Bug</b>

I have a problem with terminal. The folder path doesn't appear in the drop-down window and doesn't appear  'copyright microsoft corporation. All rights reserved.' when I click on the 'new terminal'. 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.0.6001

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T6670  @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|5.84GB (2.94GB free)|
|Process Argv|--crash-reporter-id 476ae144-b533-408e-ab7c-55a3228e1b23|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
