### ISSUE TITLE
Option to emit forward slashes for workspaceFolder and fileDirname variables on windows

### ISSUE THREAD

**Issue by yousefwalid** [microsoft/vscode#109300]
I'm using Git Bash on windows, vscode emits `workspaceFolder` and `fileDirname` with back slashes which are ignored in Git Bash, this creates an issue with paths.
Should there be an option to change backward slashes to forward slashes?
To my understanding, forward slashes work in all environments, why is it not the default?

I also tried adding the feature myself but I need some guidance as I haven't contributed to any big open source projects before.

Edit:

When creating C++ build and debug tasks, vscode generates two files: `launch.json` and `task.json`, these two files contain information about the program directory, the path of the executable to be generated.
Both can be noticed in this code snippet:
```js
  "configurations": [
    {
      "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
      "cwd": "${workspaceFolder}",
      // ... more properties
    }
  ]
```

The `${fileDirname}` and `${workspaceFolder}` parameters emitted by vscode generated the file directory path with backward slashes on windows, eg: `D:\examplefolder\subfolder`.
This works well on cmd but doesn't work with Git Bash, because Git Bash required backslashes to be escaped.

However, both cmd and Git Bash accept forward slashes as path separators, the option requested is a vscode settings option to make these variables generate forward slashes instead of backward slashes on windows

**Comment by joaomoreno** [comment]
> vscode emits `workspaceFolder` and `fileDirname`

What do you mean by _emits_?

**Comment by yousefwalid** [comment]
> > vscode emits `workspaceFolder` and `fileDirname`
> 
> What do you mean by _emits_? What feature is this?

Sorry, post updated with more info.

**Comment by alexr00** [comment]
If we solve https://github.com/microsoft/vscode/issues/38381 then we should make the solution solve this too. Marking as duplicate.
