### ISSUE TITLE
[Windows] Cannot create new vscode windows when running as administrator

### ISSUE THREAD

**Issue by Riglerr** [Microsoft/vscode#10936]
- VSCode Version: 1.4.0
- OS Version: Windows 8.1 server Enterprise editin

Steps to Reproduce:

1. Run VSCode as administrator
2. Right click icon in the taskbar and select 'New Window'
Result : No new window is created

The 'New Window' task works as expected when not running as administrator

**Comment by joaomoreno** [comment]
#1614
