### ISSUE TITLE
Poor fps when dragging scrollbar

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [microsoft/vscode#109386]
Issue Type: <b>Performance Issue</b>

To start with, I'm sorry if this is already reported, but I could not find it.

When dragging the scrollbar (on side) or by click-dragging in the outline (mini map?) of the code, and scrolling, the fps drops to close to 1. It seems fine the first one second, but gets very bad after that, jumping around due to frame rate. The issue seems to be present even when I choose "Plain Text" mode, but less severe.

I'm on a pretty decent computer with m.2 disk, 32GB 2667MHz ram, decent cpu (see below) and gpu (rtx 2080), I have 3 monitors of 2560x1440, the vs code instance running on only one of them. I have also tried with turning off two of the displays, and the same results apply, so the number of screens does not seem to affect this issue.

I can't see any difference if I close all other windows applications, close all terminals, close side panel, all other tabs etc. All seems to behave the same way.

If I make the vertical size of the window smaller, the stuttering becomes less noticeably, but I have to get it to about 12 lines of visible code for it to be "ok". If I click `ctrl`+`+`, increasing the font size, so I get only 12 lines of code on screen, but with a large window, the results are the same as if I shrunk vertical size of the window down, so it does seem to be affected by the number of visible characters on screen in some form.

If I aggressively scroll with the mouse wheel the same stuttering happens. 

Inspecting the process explorer, and windows Task Manager, it does seem to be CPU bound on one thread. The particular process which is spiking is the "window (myTypescript.ts - project-name - Visual Studio Code)

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz (20 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (18.53GB free)|
|Process Argv|--folder-uri file:///c%3A/gh/project-name|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    85	 23596	code main
    0	    79	  8640	   window (Issue Reporter)
    0	   243	  9560	   window (myTypescript.ts - project-name - Visual Studio Code)
    0	     6	  2560	     console-window-host (Windows internal process)
    0	    15	 16940	     watcherService 
    0	    11	 21884	       console-window-host (Windows internal process)
    0	    69	 20548	     searchService
    0	    66	 21928	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   104	 24004	     extensionHost
    0	   294	 19524	       electron_node tsserver.js 
    0	    81	 19176	         electron_node typingsInstaller.js typesMap.js 
    0	   106	 22636	       electron_node tsserver.js 
    0	    67	 24928	       "C:\Users\myUser\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\myUser\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=24004
    0	    25	 18640	   crashpad-handler
    0	    39	 24448	   utility
    0	    93	 24504	   shared-process
    1	    94	 24652	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (myTypescript.ts - project-name - Visual Studio Code)
|    Folder (project-name): 531 files
|      File types: ts(171) js(108) map(93) html(47) yml(21) json(11) md(3)
|                  css(2) png(2) pem(2)
|      Conf files: github-actions(3) package.json(2) launch.json(1)
|                  tsconfig.json(1) webpack.config.js(1)
|      Launch Configs: node(5);
```

</details>
Extensions: none

**Comment by connor4312** [comment]
Please grab some information using the "profiling the render process" section: https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

/needsMoreInfo

**Comment by connor4312** [comment]
Ok, if you experience this again please collect a log using those instructions so we can look into it. Thanks!
