### ISSUE TITLE
Apple Silicon: Opening some installed plugin's Extension page causes a Window crash

### ISSUE THREAD

**Issue by tarasis** [microsoft/vscode#109301]
- VSCode Version: 1.51.0-exploration
Commit: 3f89956ad6bbce2e86827215d9c332f09889eb01
Date: 2020-10-21T09:43:52.775Z
Electron: 11.0.0-beta.12
Chrome: 87.0.4280.11
Node.js: 12.18.3
V8: 8.7.220-electron.0
OS: Darwin arm64 20.1.0
- OS Version: Big Sur 11.0 Beta (20A5395g)

Steps to Reproduce:

1. Go to extensions.
2. Click on an installed extension
3. Error dialog appears:

```
The window has crashed

We are sorry for the inconvenience! You can reopen the window to continue where you left off.
```

So far this is consistent with Auto Tag Rename 0.1.5, ESLint 2.1.13, HTML CSS Support 0.2.3, Markdown Notes 0.0.20, Material Icon Theme 4.3.0, Tokyo Night 0.6.6, Bracket Pair Colorizer 2 0.2.0 (plugin disabled as it crashes extension host), Code Runner 0.11.1

Extensions that are okay: Gitlens 10.2.2, JavaScript (ES6) code snippets 1.8.0, HTML Snippets 0.2.1, IntelliSense for CSS class names in HTML 1.19.0,  Live Server 5.6.1, Visual Studio IntelliCode 1.2.10, XML Tools 2.5.1

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by sandy081** [comment]
Assigning to @deepak1556 as this is happening on exploration build/

**Comment by deepak1556** [comment]
This could very well be https://github.com/microsoft/vscode/issues/106770#issuecomment-719877989 , but to confirm can you provide the crash dump following https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

**Comment by tarasis** [comment]
Apologies for the delay. Forgot and some life issues. Here is the request dmp file. Still happens with the new VSCode Exploration release 

Version: 1.52.0-exploration
Commit: a4117a13ce760000c84b4af6e9898f29daba0d31
Date: 2020-11-10T19:13:55.206Z
Electron: 11.0.0-beta.20
Chrome: 87.0.4280.40
Node.js: 12.18.3
V8: 8.7.220.10-electron.0
OS: Darwin arm64 20.1.0

[Code-exploration-crash.zip](https://github.com/microsoft/vscode/files/5533801/Code-exploration-crash.zip)

**Comment by deepak1556** [comment]
Thanks for the logs, yup its the same crash as https://github.com/microsoft/vscode/issues/106770#issuecomment-719877989, please follow that issue for updates.
