### ISSUE TITLE
Failed to delete using the Trash

### ISSUE THREAD

**Issue by cabbagehao** [microsoft/vscode#109344]
Issue Type: <b>Bug</b>

ubuntu16.04.  I can't move the file to Trash, why?

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 4.4.0-142-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|31.34GB (12.51GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 8577b2ec-0afd-4c28-9fec-643754b117cc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
al-code-outline|and|2.0.18
code-gnu-global|aus|0.2.2
gitlens|eam|10.2.2
vue|jcb|0.1.5
vscode-elm-jump|joe|0.0.1
cmake-tools-helper|mad|0.2.1
vscode-fileheader|mik|0.0.2
vscode-clang|mit|0.2.3
vscode-docker|ms-|1.7.0
python|ms-|2020.9.114305
remote-containers|ms-|0.145.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.1
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.4.2
cpptools|ms-|1.1.0-insiders3
vetur|oct|0.28.0
code-settings-sync|Sha|3.4.3
cmake|twx|0.0.17
gitblame|wad|6.0.0
crs-al-language-extension|wal|1.2.5
c-cpp-snippets|wlh|0.1.0

</details>

**Comment by cabbagehao** [comment]
![image](https://user-images.githubusercontent.com/8425720/97133032-9c938400-1783-11eb-8c47-cca1d891f3c5.png)

**Comment by cabbagehao** [comment]
And when I accidentally clicked "Delete Permanently", the editor doesn't keep the file open (an in-memory copy) as sublime does.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/101920
