### ISSUE TITLE
[Suggestion]: About the user-define color theme.

### ISSUE THREAD

**Issue by shines77** [Microsoft/vscode#10938]
- VSCode Version: 1.4.0
- OS Version: Win7 sp1

I have a suggestion:

Why we can not choose another color theme? Not only the dark black style like now, especial when you preview the markdown file. The user experience is too bad on default dark black theme.

**Comment by sandy081** [comment]
@shines77 I am not sure if you are aware that you can

- Select a theme from an existing installed themes. 

![screen shot 2016-08-25 at 12 22 46 pm](https://cloud.githubusercontent.com/assets/10746682/17965822/d01becb6-6abe-11e6-9c17-1ef94df14c97.png)
![screen shot 2016-08-25 at 12 23 02 pm](https://cloud.githubusercontent.com/assets/10746682/17965821/d018e606-6abe-11e6-8a1a-f2289ecb4cc3.png)

- Install a new theme from the extensions market

![screen shot 2016-08-25 at 12 23 43 pm](https://cloud.githubusercontent.com/assets/10746682/17965825/d59cef14-6abe-11e6-87e2-4d12a72905bb.png)

**Comment by shines77** [comment]
@sandy081 
Thanks, I got it.
