### ISSUE TITLE
VS code is too slow

### ISSUE THREAD

**Issue by Stehos** [microsoft/vscode#109369]
Issue Type: <b>Performance Issue</b>

Hi there, this performance issue is taking few days, maybe weeks. Nothing was changed in my computer but doing anything is quite impossible. Everything is taking a lot of time, many lags during regular typing in the code etc.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (4.94GB free)|
|Process Argv|C:\wamp64\www\weyou --crash-reporter-id 76e13a4a-0344-44e0-884e-513f1537eb32|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    82	 20252	code main
    0	    14	  3408	   utility
   11	    47	 22900	   shared-process
    0	   964	 25116	   window (MmyController.php - weyou - Visual Studio Code)
    0	    18	  3228	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    15	 51332	       "C:\wamp64\bin\php\php7.4.0\php.exe" artisan serve --host=weyou.sro --port=80
    0	     3	 34844	         cmd.exe /c ""C:\wamp64\bin\php\php7.4.0\php.exe" -S weyou.sro:80 "C:\wamp64\www\weyou\server.php""
    0	    20	 47084	           "C:\wamp64\bin\php\php7.4.0\php.exe"  -S weyou.sro:80 "C:\wamp64\www\weyou\server.php"
    0	    18	 14060	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 22024	     console-window-host (Windows internal process)
    0	   108	 25132	     extensionHost
    0	    21	  5048	       electron_node vueServerMain.js 
    0	    26	  5288	       electron_node tsserver.js 
    0	    12	 24304	         electron_node typingsInstaller.js typesMap.js 
    0	    98	  8844	       electron_node intelephense.js 
    0	     9	 15372	       electron_node dbaeumer.js server.js 
    0	     9	 17404	       c:\Users\sthos\.vscode\extensions\ms-python.python-2020.9.114305\languageServer.0.5.59\Microsoft.Python.LanguageServer.exe
    0	     2	 14676	         console-window-host (Windows internal process)
    0	    19	 17572	       php.exe c:\Users\sthos\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:56672 --memory-limit=4095M
    0	     5	 20496	         console-window-host (Windows internal process)
    0	    15	 23472	       electron_node serverMain.js 
    0	    11	 25804	       "C:\Users\sthos\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\sthos\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=25132
    0	    12	 25932	       electron_node htmlServerMain.js 
    0	    22	 26176	       electron_node index.js 
    0	    19	 26744	       "C:\Users\sthos\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\sthos\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=25132
    0	    16	 27288	       electron_node tsserver.js 
    0	    15	 28628	       electron_node server.js 
    0	    20	 37772	       "C:\Users\sthos\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\sthos\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=25132
    0	     5	 25152	     console-window-host (Windows internal process)
    0	     9	 25368	     watcherService 
    0	     4	 27760	       console-window-host (Windows internal process)
    0	    27	 46724	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    33	 47648	     searchService
    0	     6	 48420	     console-window-host (Windows internal process)
    0	   318	 25296	   gpu-process
    0	     8	 26284	   crashpad-handler
    0	   164	 52808	   window (SettingsTableSeeder.php - voyager - Visual Studio Code)
    0	    11	 10136	     watcherService 
    0	     5	 50928	       console-window-host (Windows internal process)
    0	    35	 52560	     extensionHost
    0	    20	  3620	       electron_node serverMain.js 
    0	    20	  8016	       electron_node htmlServerMain.js 
    0	    23	 15832	       electron_node intelephense.js 
    0	    20	 22716	       electron_node server.js 
    0	    20	 30112	       electron_node server.js 
    0	    12	 47376	       php.exe c:\Users\sthos\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\bin\php-language-server.php --tcp=127.0.0.1:63661 --memory-limit=4095M
    0	     5	 37876	         console-window-host (Windows internal process)
    0	    20	 53068	       electron_node index.js 
    0	    64	 53224	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (SettingsTableSeeder.php - voyager - Visual Studio Code)
|  Window (MmyController.php - weyou - Visual Studio Code)
|    Folder (voyager): 1663 files
|      File types: php(895) js(416) md(45) jpg(31) png(26) css(16) gif(12)
|                  json(10) svg(9) woff(9)
|      Conf files: github-actions(5) package.json(1)
|    Folder (weyou): 13471 files
|      File types: php(8352) js(889) json(726) md(333) css(182) xml(96)
|                  jpg(93) stub(83) yml(75) gitignore(57)
|      Conf files: package.json(5) makefile(3) webpack.config.js(1) gulp.js(1);
```

</details>
<details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
laravel-blade-vscode|ami|2.0.3
tailwind-docs|aus|1.4.0
vscode-intelephense-client|bme|1.5.4
vscode-tailwindcss|bra|0.4.3
phpserver|bra|3.0.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
laravel-goto-view|cod|1.3.3
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
vscode-autohotkey-plus|cwe|2.5.9
vs-phpclassgen|dam|0.1.1
vscode-markdownlint|Dav|0.37.2
jshint|dba|0.10.21
githistory|don|0.6.12
jquerysnippets|don|0.0.1
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-rename-tag|for|0.1.5
day-night-theme-switcher|fre|0.1.2
html-slim-scss-css-class-completion|gen|1.7.7
gc-excelviewer|Gra|3.0.40
vue-snippets|hol|0.1.12
beautify|Hoo|1.5.0
smarty|imp|0.3.0
vue|jcb|0.1.5
Angular2|joh|9.1.2
latte|Kas|0.7.0
node-module-intellisense|lei|1.5.0
code-beautifier|mic|2.3.3
Angular-BeastCode|Mik|10.0.3
vscode-less|mrm|0.6.3
vscode-docker|ms-|1.7.0
python|ms-|2020.9.114305
powershell|ms-|2020.6.0
color-highlight|nau|2.3.0
php-docblocker|nei|2.1.0
vetur|oct|0.28.0
laravel-blade|one|1.24.0
laravel5-snippets|one|1.10.0
vscode-css-peek|pra|4.0.0
typescript-hero|rbb|3.0.0
java|red|0.69.0
prettier-now|rem|1.4.9
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.27
code-settings-sync|Sha|3.4.3
vscode-tailwindcss|sid|0.1.0
html5-boilerplate|sid|1.1.1
vscode-autohotkey|sle|0.2.2
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.25.0
vscode-maven|vsc|0.25.0
vscode-icons|vsc|11.0.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.3.0

(2 theme extensions excluded)

</details>

**Comment by Sleitnick** [comment]
I have been experiencing the same issue recently. It used to be silky-smooth, but now it lags a lot when I scroll or type. According to the performance recording I grabbed, I'm getting around 10 FPS, and it looks like the Layout Shift task is taking the longest.

<details><summary>Performance Screenshot</summary>
![performance](https://user-images.githubusercontent.com/5747014/97182995-9e554b80-1773-11eb-9872-e73342cfa113.jpg)
[/Image]
</details>

High level specs: VSCode v1.50.1; Windows 10 (version 2004); i7-8700k; 16GB RAM; GTX 1070 GPU

**Comment by connor4312** [comment]
Please collect performance information using the following instructions: https://github.com/microsoft/vscode/wiki/Performance-Issues

/needsMoreInfo
