### ISSUE TITLE
Custom emmet lorem text doesnt work.

### ISSUE THREAD

**Issue by mmsaffari** [microsoft/vscode#109381]
Issue Type: <b>Bug</b>

According to [the docs](https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets)
Use this in the `settings.json`
```json
    "emmet.extensionsPath": "C:\\Workspace\\EditorExtensions\\emmet",
```
now create a file named `snippets.json` inside that folder containign this:
```json
{
  "html": {
    "snippets": {
      "ran": "{ Wrap plain text in curly braces }",
      "falorem": "{لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.}"
    }
  }
}
```
The expected behavior is that `falorm` snippet produces the Farsi text indicated in the `snippets.json` file, but it does not.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960X CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.63GB free)|
|Process Argv|--crash-reporter-id f3322d03-c449-47fc-8b1b-7036f7706254|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.9.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.13
xml|Dot|2.5.1
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
code-runner|for|0.11.1
toml-formatter|ice|0.0.3
cargo-toml-snippets|kev|0.1.1
vscode-docker|ms-|1.7.0
csharp|ms-|1.23.4
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.9.114305
remote-wsl|ms-|0.50.1
cpptools|ms-|1.0.1
powershell|ms-|2020.6.0
debugger-for-chrome|msj|4.12.11
vetur|oct|0.28.0
vscode-yaml-sort|Pas|2.7.1
vscode-yaml|red|0.11.1
rust|rus|0.7.8
crates|ser|0.5.3
html-preview-vscode|tht|0.2.5
vue-docs|tit|1.0.2
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0

</details>

**Comment by meganrogge** [comment]
![recording (13)](https://user-images.githubusercontent.com/29464607/97466111-f8831780-18ff-11eb-990d-f8d25182e550.gif)
@mmsaffari please check that your path is correct because your snippets.json works for me.

**Comment by mmsaffari** [comment]
For `snippets.json` to work, the value of the `emmet.extensionsPath` setting should be written in a WSL-like format and the DOS/Windows path style won't work. Perhaps because I have WSL2 installed?  
This is the correct way of pointing emmet to the folder where `snippets.json` resides:
```json
{
  
  "emmet.extensionsPath": "/C:/Workspace/EditorExtensions/emmet",
  
}
```
