### ISSUE TITLE
about html icon

### ISSUE THREAD

**Issue by Nikhil-5654** [microsoft/vscode#109341]
Issue Type: <b>Feature Request</b>

i have created html file with .html extension  after i created i am getting windows icon on file instead of  "< >" this icon and for js files "js " icon visible  and automatic emmets are not working. Atelast tell me solution to  resolve problem my self.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.1.7601

**Comment by aeschli** [comment]
Does this reproduce with extensions disabled?
Dis you make any settings changes, e.g. associate `.html` to another language?

**Comment by Nikhil-5654** [comment]
No  i haven't changed anything.
After updating to new version i am noticing all these changes

**Comment by aeschli** [comment]
Can you add a screenshot?

**Comment by Nikhil-5654** [comment]
![20201029_140712.jpg](https://user-images.githubusercontent.com/59393250/97544870-36f7ff80-19f0-11eb-9b52-27d1b938f274.jpg)

**Comment by Nikhil-5654** [comment]
U can see on above picture

**Comment by aeschli** [comment]
When you open the html file, what does the language indicator say? Is it HTML ?

**Comment by Nikhil-5654** [comment]
Yes it  dispalys in html language only 
But file icon  is in windows and Emmets also not working

**Comment by aeschli** [comment]
The language indicator in the status bar... 
![image](https://user-images.githubusercontent.com/6461412/97552134-2a65ae00-19d4-11eb-87f9-044c527c6a13.png)

**Comment by Nikhil-5654** [comment]
![20201029_154607.jpg](https://user-images.githubusercontent.com/59393250/97555255-e5567180-19fd-11eb-8f5d-b6e8970782a6.jpg)

**Comment by aeschli** [comment]
That's the problem: The HTML file is associated with `Batch`.
Click on `Batch`, and select `Configure File Association for .html` and choose HTML.

**Comment by Nikhil-5654** [comment]
Tq

**Comment by Nikhil-5654** [comment]
Its resolved
