### ISSUE TITLE
Debug stepping through code briefly shows a green line highlight 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#109385]
When trying extension debugging in a remote scenario (CS), I noticed that on stepping through the code every line is briefly shown in green before turning yellow. This results in flashing:

![2020-10-26_15-56-03 (1)](https://user-images.githubusercontent.com/1898161/97189485-efc9fe80-17a4-11eb-8ff7-16c27f68b552.gif)

If you open the animated gif from above in macOS Preview application (which shows the individual frames), you can see that there are some unexpected transitions, e.g. yellow (37) -> none (38) -> green (39) -> yellow (40):

<img width="1214" alt="2020-10-26_16-13-22" src="https://user-images.githubusercontent.com/1898161/97190693-54d22400-17a6-11eb-9368-7b331520ade1.png">

**Comment by isidorn** [comment]
Interesting, is this something new that was not happening before?
Can you reproduce in a non remote scenario?

**Comment by weinand** [comment]
I don't think that this is a new issue. But I first noticed it in a remote (that is slow) setup.

**Comment by isidorn** [comment]
It is probably caused by the way how we fetch first the top stack frame and then the rest of the call stack. And we try to preserve the rest of the call stack intact to reduce flickering in CALL STACK view.
