### ISSUE TITLE
Integrated terminal: Random laggy experience

### ISSUE THREAD

**Issue by imWildCat** [microsoft/vscode#109323]
- VSCode Version and OS Version:

```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0 - macOS 11.0 Beta (20A5395g)
```

Steps to Reproduce:

I don't think it can be reproduced easily on other machines.

1. Open VSCode
2. Type anything in the integrated terminal
3. The lagging happens very frequently, about once per 10 ~ 30 seconds.

I can also see this if I open Developer Tools for profiling:
![dev_tools](https://user-images.githubusercontent.com/2396817/97105774-8987a200-16f8-11eb-8c23-7446ff9b8f1b.png)

(I can upload this profiling log if needed)

Does this issue occur when all extensions are disabled?: Yes (I can always repro without any extension)

**Comment by Mokto** [comment]
Thanks for the info @imWildCat.

Got the same issue and only when I run it through `code ...`

**Comment by imWildCat** [comment]
Yeah, the Big Sur on my laptop was a fresh installation.

And it seems that I launched VSCode via command line as well.

**Comment by imWildCat** [comment]
Yeah, the Big Sur on my laptop was a fresh installation.

And it seems that I launched VSCode via command line as well.

**Comment by Tyriar** [comment]
Yes could you please attach the profile?

**Comment by Tyriar** [comment]
Looking at the profile it seems like maybe it's a bug in Node.js with Big Sur that some async process launches are happening synchronously or something?

![image](https://user-images.githubusercontent.com/2193314/97595012-80c8f180-19c0-11eb-8214-3abaf9efcee9.png)

@deepak1556 have you seen this happen elsewhere where `exec` ends up blocking the main thread for > 1s?
