### ISSUE TITLE
Provide an Insert Snippet command ID

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#109315]
Could you please provide a command ID for the _Insert Snippet_ command please so we can trigger it via a keybind?

**Comment by usernamehw** [comment]
Do you want to insert a snippet with keybinding https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets or to open a dialog?

**Comment by inwardmovement** [comment]
I want to open the quick pick triggered by the _Insert Snippet_ command palette command:

![image](https://user-images.githubusercontent.com/9438102/97101447-bd81a980-169d-11eb-9b4c-3cdbe292e2c7.png)

![image](https://user-images.githubusercontent.com/9438102/97101424-97f4a000-169d-11eb-82f2-402ce63e77f7.png)

**Comment by usernamehw** [comment]
You can do that without specifying an argument:

```js
{
	"key": "ctrl+shift+9",
	"command": "editor.action.insertSnippet"
}
```

**Comment by inwardmovement** [comment]
Awesome thank you, I didn't find this command anywhere.
