### ISSUE TITLE
Error while accessing CSS file...

### ISSUE THREAD

**Issue by RavePlnt** [microsoft/vscode#109399]
Issue Type: <b>Performance Issue</b>

Keep getting this error the last couple weeks/month: 
"Error while accessing CSS file. Use command palette 'Scan linked CSS file' to try again."

That command doesn't do anything and I get this error every time I open Visual Studio Code. I think this started after a recent update. Also click that lightning bolt icon to scan and same thing.

Please advise.

Thanks

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (5.34GB free)|
|Process Argv|--crash-reporter-id e07627e2-821c-4904-b236-621a4e42378b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    53	 27628	code main
    0	   213	 27716	   window (index.html - raveplants - Visual Studio Code)
    0	   159	 24992	     extensionHost
    0	    70	  2672	       "C:\Users\Dale.RAVES\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Dale.RAVES\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=24992
    0	    14	 26984	       "C:\Users\Dale.RAVES\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Dale.RAVES\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=24992
    0	    19	 29220	       electron_node serverMain.js 
    0	     5	 26020	     watcherService 
    0	     1	 27944	       console-window-host (Windows internal process)
    2	    39	 28604	   shared-process
    0	     4	 29180	   crashpad-handler
    0	   167	 29296	   gpu-process
    0	    15	 29408	   utility
    1	    60	101188	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - raveplants - Visual Studio Code)
|    Folder (raveplants): 11526 files
|      File types: jpg(6636) html(2600) png(704) htm(208) css(162) gif(160)
|                  md(134) js(124) JPG(92) txt(24)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
auto-rename-tag|for|0.1.5
vscode-edge-devtools|ms-|1.1.1
LiveServer|rit|5.6.1
ayu|tea|0.20.1
open-in-browser|tec|2.0.0
lorem-ipsum|Tyr|1.2.0
html-snippets|wge|0.1.5
html-css-class-completion|Zig|1.19.0

(10 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
This error comes from the `aessoft-class-autocomplete` extension. Can you file an issue there?
https://github.com/AESSoft/vscode-class-autocomplete-for-html/issues

**Comment by RavePlnt** [comment]
Ok, but how do I fix this error?

**Comment by aeschli** [comment]
The authors of the `aessoft-class-autocomplete` can hopefully tell you.
But you can always uninstall the extension...

**Comment by RavePlnt** [comment]
Thank you
