### ISSUE TITLE
--extensions-dir '[Your Path]' have a bug.

### ISSUE THREAD

**Issue by TheSmileCat** [microsoft/vscode#109308]
Issue Type: <b>Bug</b>

I used this bat code to launch the Visual Studio Code and finded a bug.
------------------------------------------------
@echo off
"%cd%\VSCode\Code - Insiders.exe" --extensions-dir ‘.\VSCode\plugins’
------------------------------------------------
Such as you move the VSCode to a root of disk, and run this bat. A directory will be created and it named '. (It's a single mark and a dot).  I can't to delete and open the directory.
Using the DiskGenius, I can see this:

I:\\'.\VSCode\plugin\\'

The last directory named ' (a single mark) and "I" is my USBdisk.

VS Code version: Code - Insiders 1.51.0-insider (7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9, 2020-10-23T07:36:26.010Z)
OS version: Windows_NT ia32 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.24GB free)|
|Process Argv|--extensions-dir .\VSCode\plugins --crash-reporter-id d256dd06-8d84-4fb7-bd44-0237bc558342|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.1.0
c-cpp-compile-run|dan|1.0.12
vscode-pull-request-github|Git|0.20.1
vscode-gnu-global|jay|0.3.3
better-cpp-syntax|jef|1.15.0
vscode-language-pack-zh-hans|MS-|1.51.0
remote-containers|ms-|0.146.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.51.0
cmake-tools|ms-|1.4.2
cpptools|ms-|1.1.0-insiders3
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3046
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3073
cmake|twx|0.0.17

(1 theme extensions excluded)

</details>

**Comment by TheSmileCat** [comment]
string launchCommand = Command.Replace(" ", "").Length > 0 ? Command : Config[0];
            if (launchCommand.Length > 0) launchCommand += " ";
            if (!Command.Contains("--extensions-dir")) launchCommand += "--extensions-dir \'" + Config[2] + "\'";
            Process = System.Diagnostics.Process.Start(Config[1], launchCommand);
In this code, if I used \" it will missing the first double mark. result is VSCode crashed, so I changed to using single mark.

I'm sorry to I have a bad English and I'm a 1 Year  student of University in China.

**Comment by joaomoreno** [comment]
```
@echo off
"%cd%\VSCode\Code - Insiders.exe" --extensions-dir ‘.\VSCode\plugins’
```

The problem is you used the `‘` character in `‘.\VSCode\plugins’` instead of the correct `'` as in `.\VSCode\plugins`.

This is an issue with Command Prompt, not VS Code.
