### ISSUE TITLE
Regarding debug and run

### ISSUE THREAD

**Issue by adityajmadi** [microsoft/vscode#109331]
Issue Type: <b>Bug</b>

When I degub my C program, it says task.json file is not launched and when I run my C program it says acess is denied

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.66GB free)|
|Process Argv|--crash-reporter-id 79bd7fa1-acaa-4cb8-95b4-206604fc9525|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.1
cpptools|ms-|1.1.0-insiders3

</details>

**Comment by weinand** [comment]
Please provide reproducible steps with screenshots of the errors you are seeing.
