### ISSUE TITLE
account login

### ISSUE THREAD

**Issue by SHIVAMSINGH4** [microsoft/vscode#109347]
Issue Type: <b>Bug</b>

My login option is not showing in the visual studio code .

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.56GB free)|
|Process Argv|--crash-reporter-id edc0ee9d-01f1-4683-b26e-ca6176a103ac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
python|ms-|2020.9.114305
team|ms-|1.161.1
sqltools|mtx|0.23.0

</details>

**Comment by RMacfarlane** [comment]
What are you trying to log into, an extension, or settings sync? What do you see under the accounts icon?

**Comment by SHIVAMSINGH4** [comment]
I am trying to login in my GitHub account through vscode ,but I am already
logged in on same day .
Your reply comes after a couple of days so I can't wait any longer .

so can you just tell me that why my account icon is not showing up on
screen ?

**Comment by RMacfarlane** [comment]
Do you mean that this icon isn't visible to you?
<img width="64" alt="Screen Shot 2020-11-03 at 9 00 00 AM" src="https://user-images.githubusercontent.com/3672607/98016581-037ff100-1db3-11eb-8e29-4564ae24b8f5.png">

**Comment by SHIVAMSINGH4** [comment]
Yes that icon

**Comment by SHIVAMSINGH4** [comment]
And can we talk through any other medium like WhatsApp .if yes so please
send me your number.

**Comment by RMacfarlane** [comment]
Does right clicking the activity bar show an option to "Show Accounts"?
<img width="234" alt="Screen Shot 2020-11-03 at 9 02 29 AM" src="https://user-images.githubusercontent.com/3672607/98017057-9456cc80-1db3-11eb-9cec-49bff8fb2b8d.png">

**Comment by SHIVAMSINGH4** [comment]
No

**Comment by RMacfarlane** [comment]
Do you remember if you're previously hidden that icon? Can you please share a screenshot of your activity bar?

**Comment by SHIVAMSINGH4** [comment]
please see attachment

**Comment by RMacfarlane** [comment]
Attachments made through email don't seem to show up on GitHub, please add it through the GitHub website.

**Comment by SHIVAMSINGH4** [comment]
![2020-11-04_10-06-18](https://user-images.githubusercontent.com/71896732/98200295-52648c80-1f53-11eb-8477-c4b467c79b37.png)

**Comment by RMacfarlane** [comment]
If you run `code --user-data-dir <some folder name>` from the command line, does the icon appear?
