### ISSUE TITLE
Test resizable suggest widget

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109394]
Refs: https://github.com/microsoft/vscode/issues/29126

- [x] anyOS @isidorn
- [x] anyOS @dbaeumer

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23109394%0A%0A)

---

The suggest widget is now resizable - that applies to the list of suggestions and the details panel. Test that

* the list of suggestions is resizable
* the details panel is resizable
* there is good minimal sizes 
* the details panels doesn't steel space from the list
* the list remembers a custom size
* the list goes to "ideal" size when double clicking its resize sashes
  * the ideal height of the list is defined via `editor.suggest.maxVisibleSuggestions`
  * the ideal width is defined by the items
* the details panels only remembers a custom size for the current sessions (comment here if you disagree https://github.com/microsoft/vscode/issues/109360)
* when resizing the list or window the details re-position themselves with this priority: left, right, below
* the list preferrers to be shown below the cursor but shows above if there isn't enough space
* the details align to top of the list unless they are too high in which case they align with the bottom of the list

**Comment by isidorn** [comment]
Great work, I really like these changes.

**Comment by dbaeumer** [comment]
Agree with @isidorn. None of my issue are critical (the are mostly corner cases) except may be https://github.com/microsoft/vscode/issues/109447
