### ISSUE TITLE
Test syncing extension's global state

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#109388]
Testing https://github.com/microsoft/vscode/issues/95209

- [x] anyOS @RMacfarlane
- [x] anyOS @sbatten

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23109388%0A%0A)

---

Extensions can now contribute global state keys those can be synchronised using proposed [syncedKeys](https://github.com/microsoft/vscode/blob/9b4f91b/src/vs/vscode.proposed.d.ts#L2191) API

https://github.com/microsoft/vscode/blob/9b4f91b31cf2f8a7fafc1bbdcacf98505b84c0eb/src/vs/vscode.proposed.d.ts#L2184-L2194

- Write and publish a test extension that saves and syncs some global state using above API.
  - Make sure you add `"enableProposedApi": true` flag to extension's package.json.
  - use `--noVerify` flag while publishing the extension.

Following sample, shows a welcome notification for the first time and remembers that. From thereafter it mentions that welcome was shown already.

```ts
import * as vscode from 'vscode';

const welcomeMessageShownStateKey = 'sandy081.999-test-sync-state.welcomeMessageShwon';
export function activate(context: vscode.ExtensionContext) {
	context.syncedGlobalState.syncedKeys = [welcomeMessageShownStateKey];
	if (context.syncedGlobalState.get(welcomeMessageShownStateKey)) {
		vscode.window.showInformationMessage('Activated: Welcome was shown already');
	} else {
		vscode.window.showInformationMessage('Activated: Welcome to my extension');
		context.syncedGlobalState.update(welcomeMessageShownStateKey, true);
	}
}

export function deactivate() {}
```

**Note:** Extension state sync works only with published extensions.

- Test that extension state is synced across
  - Start insiders using the flag `--enable-proposed-api <above-extension-id>`
  - Install above extension (if you used above sample, then you shall see welcome notification)
  - Turn on settings sync
  - On other machine (or use another user data dir and extensions dir on same machine) start insiders with `--enable-proposed-api  <above-extension-id>`
  - Turn on settings sync and make sure above extension is installed and the extension state is synced.
  - For example, if you used above sample, then you shall see a notification saying welcome was shown already.
  - You can also check for synced extension state by 
    - Open Synced Data view using command `Settings Sync: Show Synced Data`
    - Open the latest synced extensions.json entry and make sure extension state is synced to server.

<img width="1577" alt="image" src="https://user-images.githubusercontent.com/10746682/97200652-c82d6300-17b1-11eb-9fe4-e4c1f6e4b69b.png">

- Test that you can add or remove keys to sync by updating the `syncedKeys` value and make sure state is synced accordingly.
- Test that explicitly setting the `syncedKeys` to empty array will clear the synced state on server.
- Test that only state from latest extension version is synced. It means when remote and local extensions are in different versions
  - If local version is older than remote version, then state is not synced
  - If local version is newer than remote version, then remote state is replaced with local.
  - If local and remote are on same versions, then state is merged and synced.
- Validate the documentation and naming terminology of the API

**Comment by sbatten** [comment]
@sandy081 things just don't seem to be working as expected at all. I've created an extension that has commands for pushing new state, clearing state, and checking the sync'd state, but nothing is working as expected. 

Here is the extension code with a README explaining usage: https://github.com/sbatten/vscode-sync-test-sample. PTAL and let us know if we are doing something wrong.

**Comment by sandy081** [comment]
@sbatten Can you please check following in both machines?

- Open Synced Data view using command Settings Sync: Show Synced Data
- Open the latest synced extensions.json entry and make sure extension state is synced to server.

Also open Settings Sync log and check if Sync is happening, especially, check if extensions are being pushed or pulled.

**Comment by RMacfarlane** [comment]
I'm also seeing this problem with my own test extension, and SteVen and I looked at his sample together on a call. We verified that other data was correctly being synced, i.e. settings like the theme were correctly applied between windows. When looking at the synced data, it seemed like the incoming changes from the remote were always being deleted on the local machine

**Comment by sandy081** [comment]
This is happening because the extension is not published. Extension state is not synced when extension is not available in the Marketplace - Please file an issue for it. I verified this by publishing your sample using extension id `sandy081.999-test-sync-state` and it works as expected.
