### ISSUE TITLE
Creating Lists on HTML gone wrong 

### ISSUE THREAD

**Issue by Nze007** [microsoft/vscode#109321]
We have writteI want to create a unodered list on my index page. Whenever I type `<li>` and intend to create an `<a href>`, my `</ul>` will change automatically to `</a>`. This is frustrating and delaying my work cos whenever i intend to manually correct it, auto correct will start deleting every elements I intend to corect. 
![2020-10-25](https://user-images.githubusercontent.com/70347981/97103722-8a262700-166b-11eb-986b-6c1836228fe6.png)
n the needed data into your clipboard because it was too large to send. Please paste.

**Comment by aeschli** [comment]
Sorry, I'm not able to repoduce.
- type `<ul>`: this will complete to `<ul></ul>`
- type `<a href

Do you have any extensions enabled?

**Comment by Nze007** [comment]
Whenever I type <li> <a href, my <ul></ul> changes to <a>. I don't have any new extensions enabled. Its been working perfectly fine until now.

**Comment by aeschli** [comment]
Sorry, not for me:
![image](https://user-images.githubusercontent.com/6461412/97179418-184bfb80-1799-11eb-8311-5733404b297c.png)
