### ISSUE TITLE
The detail of a suggest does not remember its height

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#109360]
Version: 1.51.0-insider
Commit: 7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9
Date: 2020-10-23T07:32:22.213Z
Electron: 9.3.2
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:

1. Resize the height of the detail of a suggest.
2. Close it and reopen it with `Ctrl-Space`
3. The height is not restored.

Does this issue occur when all extensions are disabled?: Yes

![Oct-26-2020 18-40-05](https://user-images.githubusercontent.com/10665499/97157270-388cb200-17bb-11eb-915f-6efc735dbf95.gif)

**Comment by jrieken** [comment]
That's on purpose and needs to be discussed. The motivation is that details vary a lot between items and that there is little value in keeping the size for too long. E.g it might be annoying to see a totally wrong size for details at a later suggest session.  Reading details is something short lived in our model and therefore its size isn't restored

**Comment by jrieken** [comment]
Closing this
