### ISSUE TITLE
Add file search ablility for "Explorer" pane

### ISSUE THREAD

**Issue by sdhongjun** [microsoft/vscode#109316]
If an opend project have many files I want to search a file in "Explorer" pane directly. Could you add this ablility to be next version release.

**Comment by kanlukasz** [comment]
Not perfect yet, but it's better than nothing:
https://github.com/microsoft/vscode/issues/10026

...or maybe you can use `ctrl` + `p` ?

**Comment by isidorn** [comment]
Use the search panel, Ctrl + p, or install an extension that does it.
Closing as designed.
