### ISSUE TITLE
全局搜索的问题

### ISSUE THREAD

**Issue by KringZhang** [microsoft/vscode#109352]
Issue Type: <b>Bug</b>

主编辑器区域没打开文件A，全局搜索A中的关键字时，文件A不会出现在搜索结果中（搜索结果不全）；当主编辑器区域打开了该文件A之后，再全局搜索该文件里的关键字，则可以搜到该文件。

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.05GB free)|
|Process Argv|--crash-reporter-id 12c2b1a9-2183-4cdc-aff6-630ae88b0c36|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
flutter-snippets|ale|2.0.0
dart-code|Dar|3.15.1
flutter|Dar|3.15.1
vscode-eslint|dba|2.1.13
anes|gam|0.0.2
vscode-language-pack-zh-hans|MS-|1.50.2
awesome-flutter-snippets|Nas|2.0.4
vetur|oct|0.28.0
java|red|0.69.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.25.0
vscode-maven|vsc|0.25.0

</details>

**Comment by HaoboGu** [comment]
Translation:

Global search's problem'

If file A is not opened in main editing area, and when doing global search on keywords in A, file A will not appear in the searching result(incomplete searching result). After file A is opened in main editing area, then to do global search on previous keywords, file A can be retrieved this time.

**Comment by yume-chan** [comment]
Same as #109371 and #102884

From https://github.com/microsoft/vscode/issues/102884#issuecomment-661457673

> Can you tell me whether there are any errors in the dev tools console (Help > Toggle Developer Tools)

**Comment by KringZhang** [comment]
No,there is no error in the dev tools console.I think it is very easy to find this problem:open a project and then search a keyword in the global search area,and you will find the search results are not complete.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 下午5:12
收件人:&nbsp;"microsoft/vscode"<vscode@noreply.github.com&gt;;
抄送:&nbsp;"星夜无语"<746822492@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vscode] 全局搜索的问题 (#109352)





 
Same as #109371 and #102884
 
From #102884 (comment)
  
Can you tell me whether there are any errors in the dev tools console (Help &gt; Toggle Developer Tools)

**Comment by HermanZzz** [comment]
> No,there is no error in the dev tools console.I think it is very easy to find this problem:open a project and then search a keyword in the global search area,and you will find the search results are not complete.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "microsoft/vscode" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月3日(星期二) 下午5:12 收件人:&nbsp;"microsoft/vscode"<vscode@noreply.github.com&gt;; 抄送:&nbsp;"星夜无语"<746822492@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [microsoft/vscode] 全局搜索的问题 (#109352) Same as #109371 and #102884 From #102884 (comment) Can you tell me whether there are any errors in the dev tools console (Help &gt; Toggle Developer Tools) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Same problem.

**Comment by roblourens** [comment]
Please check whether any of the tips here help: https://github.com/microsoft/vscode/wiki/Search-Issues

**Comment by KringZhang** [comment]
> Please check whether any of the tips here help: https://github.com/microsoft/vscode/wiki/Search-Issues
No,this problem has not been resolved yet.
