### ISSUE TITLE
When work with Sogou pinyin Chinese input method, the inputed Chinese word will repeat.

### ISSUE THREAD

**Issue by Ruikuan** [Microsoft/vscode#10937]
- VSCode Version: Code - Insiders 1.5.0-insider (2f2d6502638fa108f8ddbcc5831b38a35d5a1c11, 2016-08-25T06:09:29.461Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Download [Sogou pinyin Chinese input method](http://pinyin.sogou.com/). It's a very popular Chinese input method, almost top 1, so I think maybe this issue will puzzle many people.
![download](https://github.com/Ruikuan/Img/raw/master/inputinstall.png)

2. Install the input method, then use it to input any Chinese word, you can see the word will be repeated in the Editor.  
![inputing](https://github.com/Ruikuan/Img/raw/master/input1.png)
![inputed](https://github.com/Ruikuan/Img/raw/master/input2.png)

**Comment by fantacytyx** [comment]
[ QQ pinyin](http://cdn.qq.ime.sogou.com/0db3cec5686d0d317d0f9e3dcff8e081/57bf1595/QQPinyin_Setup_5.3.3208.400.exe)  have the same problem.

**Comment by alexandrudima** [comment]
@Ruikuan @fantacytyx Can you please try today's insiders version, where we made a fix in this area for mac dead key handling (input was doubled), I believe that fix might fix this issue too.

![image](https://cloud.githubusercontent.com/assets/5047891/18002113/540670ec-6b86-11e6-9875-5d61ce86e725.png)

**Comment by alexandrudima** [comment]
The relevant commit is 26f5824005d31dffebd1235dc997088f7ee76754

**Comment by fantacytyx** [comment]
@alexandrudima This issue has been fixed. But I find a new problem that the charset of the input is difficult to undo by using keyboard Ctrl+z.

**Comment by alexandrudima** [comment]
@fantacytyx Thank you for confirming. Indeed, let's track the undo problem in #9675

**Comment by Ruikuan** [comment]
@alexandrudima fixed. Thank you.

**Comment by alexandrudima** [comment]
@Ruikuan @fantacytyx I have started some time ago a Wiki page where we collect different manual tests for different input methods. Please notice how the tests are written "for dummies" with all the needed steps spelled out.

https://github.com/Microsoft/vscode/wiki/IME-Test

Is it possible that maybe you comment in here such a test for the Sogou pinyin Chinese input method such that in the future when we make changes in this area we can also test this input method? [There is already a test for Microsoft Pinyin, maybe we can add one for Sogou too)

**Comment by Ruikuan** [comment]
- Add the Sogou pinyin Chinese input method  
   - Download Sogou pinyin Chinese input method from [this link](http://pinyin.sogou.com/)
     ![download link](https://github.com/Ruikuan/Img/raw/master/inputinstall.png)
   - Install Sogou pinyin Chinese input method
      - Double click downloaded install exe  
        ![install exe](https://github.com/Ruikuan/Img/raw/master/install_exe.png)  
      - Click YES if UAC dialog show  
        ![accept uac](https://github.com/Ruikuan/Img/raw/master/accept_uac.png)
      - Click Install immediately in the install UI  
        ![install immediately](https://github.com/Ruikuan/Img/raw/master/clickinstall.png)
      - Wait for the process complete, UNCHECK the "install the Sogou browser"  
        ![uncheck sogou browser](https://github.com/Ruikuan/Img/raw/master/uncheck.png)  
      - Uncheck all options, click finish  
        ![uncheck all options](https://github.com/Ruikuan/Img/raw/master/uncheck2.png)
      - Sogou pinyin Chinese input method install successfully
- Focus VS Code and switch OS input method to Chinese and choose Chinese mode and make sure the input method's name is Sogou Pinyin:  
   ![sogou pinyin](https://github.com/Ruikuan/Img/raw/master/input_status.png)
- Type ni press Space and then hao and press Space. They should be typed in immediately. Here is how Word looks like doing this:  
   ![input to word](https://github.com/Ruikuan/Img/raw/master/word_input.gif)
- Type nihao press Space. It should result into 你好  


Hope this can be helpful.

**Comment by alexandrudima** [comment]
@Ruikuan Thank you very much! :heart: I have added this as a test to the wiki!

https://github.com/Microsoft/vscode/wiki/IME-Test#windows-sogou-pinyin-chinese-input-method
