### ISSUE TITLE
Gulp auto detect with gulpfile.mjs

### ISSUE THREAD

**Issue by jens-t** [microsoft/vscode#109326]
Gulp auto detect doesn't work with gulpfile.mjs

- VSCode Version: 1.50.1
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Create gulpfile.mjs in project root
2. Define Tasks
3. task -> show all tasks

Does this issue occur when all extensions are disabled?: Yes

**Comment by jens-t** [comment]
@alexr00 I think that's more a compatibility bug with the current node lts version, than it is a feature request. Maybe this could also be seen as part of the larger problem of supporting the mjs extension for all kind of js configuration files.

**Comment by alexr00** [comment]
We also specifically only look for these files:

https://github.com/microsoft/vscode/blob/fe35d8c97a4f79b2efc6df4f6e0baeb49be0deb3/extensions/gulp/src/main.ts#L149-L153

so there it is a feature request there too.
