### ISSUE TITLE
Blazor WASM Application fails to launch on VSCode Insiders

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#109395]
- VS Code version: Code - Insiders 1.51.0-insider (16f4a29aa0ac05d3cba222b1f347b7404626c680, 2020-10-26T05:32:45.135Z)
- OS version: Darwin x64 19.6.0

Issue Type: <b>Bug</b>

When attempting to start a stock simple Blazor WASM application, an error is displayed, indicating the project cannot start: 

![image](https://user-images.githubusercontent.com/13488/97199563-84713400-1786-11eb-9dd9-232065af8b13.png)

I have the latest version of the C# extension, and also attempted to run with all other extensions disabled. Same problem

This problem ONLY occurs on VSCode - Insiders. Launching the same Blazor application using the release version of VSCode works as expected.

Reported in the C# extension repo, but reporting here, as it seems to only affect VSCode-Insiders:
https://github.com/OmniSharp/omnisharp-vscode/issues/4131

Contents of launch.json, generated from "generate assets from build and debug" command:
```
{
   // Use IntelliSense to find out which attributes exist for C# debugging
   // Use hover for the description of the existing attributes
   // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
   "version": "0.2.0",
   "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}"
        }
    ]
}
``` 
## Steps to Reproduce ##

Create new Blazor WASM application - dotnet new blazorwasm -o BlazorWasmTest
Open project in VS Code Insiders
Click Run

## Expected Behavior ##
Project Runs and launches browser

## Actual Behavior ##
Error message displayed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.15GB free)|
|Process Argv|--crash-reporter-id 9d6f571a-d31e-40c5-baf0-0b1f495508d5|
|Screen Reader|no|
|VM|18%|
</details>

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
VS Code has no built-in debugger for a "blazorwasm" debug type?
What debug extension defines the "blazorwasm" debug type?

**Comment by jtsom** [comment]
> VS Code has no built-in debugger for a "blazorwasm" debug type?
> What debug extension defines the "blazorwasm" debug type?

The C# extension. As I mentioned above the same extension works when using the release version of VS Code. Using the same extension version in Insiders presents the above error message.
