### ISSUE TITLE
[c#] wrong colorization for unsafe code pointer

### ISSUE THREAD

**Issue by jonnyguo1988** [Microsoft/vscode#1093]
![pointer](https://cloud.githubusercontent.com/assets/14086700/11649742/220b860a-9dbd-11e5-8e6d-bedd2c3a98f6.png)

hi
please see the attachment, I'm writing unsafe code in c#, but the color for the parameters of pointers is wired, I think this should be a bug.

Thank you

**Comment by aeschli** [comment]
Same problem with Atom (languages-csharp 0.11.0)
![image](https://cloud.githubusercontent.com/assets/6461412/11651856/421d3ea8-9d94-11e5-8836-0dc91a5717ce.png)

**Comment by aeschli** [comment]
This issue was moved to atom/language-csharp#46

**Comment by aeschli** [comment]
Now tracked in https://github.com/OmniSharp/omnisharp-vscode/issues/101
