### ISSUE TITLE
 Error: Could not connect to debug target at http://localhost:port: Promise was canceled

### ISSUE THREAD

**Issue by alvinhui** [microsoft/vscode#109346]
**Describe the bug**

**To Reproduce**

https://code.visualstudio.com/api/get-started/your-first-extension#debugging-the-extension

- clone this repository: https://github.com/microsoft/vscode-extension-samples
-  `code ./helloworld`
- Then, inside the editor, press F5. This will compile and run the extension in a new Extension Development Host window.
- error:
    ![image](https://user-images.githubusercontent.com/4392234/97133995-b6829600-1786-11eb-8328-397c884f37d9.png)

**Log File**

[vscode-debugadapter-2.json.gz](https://github.com/microsoft/vscode-js-debug/files/5436815/vscode-debugadapter-2.json.gz)
[vscode-debugadapter-3.json.gz](https://github.com/microsoft/vscode-js-debug/files/5436816/vscode-debugadapter-3.json.gz)

**VS Code Version:** 

Version: 1.51.0-insider
Commit: 7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9
Date: 2020-10-23T07:32:22.213Z
Electron: 9.3.2
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by connor4312** [comment]
@alvinhui do you have any antivirus or firewall running locally? We've seen some issues in the past where that was blocking the debug connection.

**Comment by El-Chiang** [comment]
Did you solve the problem? I had the same issue

**Comment by rasputtim** [comment]
I also have the same problem after upgrading to version 1.52.0
