### ISSUE TITLE
View action bar hides on problems filter context menu

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#109304]
Related to: https://github.com/microsoft/vscode/issues/92029

While the original #92029 issue is fixed, this is another case.

Filter context menu in the Problems view

![image](https://user-images.githubusercontent.com/641685/97087565-13e8dc80-15f9-11eb-9c70-e02d8f5a56d4.png)

**Comment by sandy081** [comment]
Sorry that I do not understand the issue, can you please explain in detail. Are there any steps to repro?

**Comment by eamodio** [comment]
Move the problems panel out of its own container and into another one (so it behaves like a normal view) and then click on the filter icon to show the menu -- the view header will hide because focus moves to the menu

**Comment by sandy081** [comment]
Do you mean as follows:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/10746682/97186434-93191480-17a1-11eb-927a-d180a28c75b8.png">

**Comment by eamodio** [comment]
Exactly, but you need to use our custom menus (sorry forgot about that detail)

**Comment by sandy081** [comment]
Sorry to ask what setting is it to use custom menus and is it available in Mac?

**Comment by eamodio** [comment]
Its `"window.titleBarStyle": "custom"`, but I don't think its available on the mac.

**Comment by sbatten** [comment]
@sandy081 the problems view filter dropdown should adopt the shadow dom'd child menu where the custom menu is rendered as a child of the filter button. I tested this with the simple change above and did not see issues, but we slowly adopt this as needed since there can be unforeseen issues with styling. please test on web to verify.
