### ISSUE TITLE
registerWebviewViewProvider: no way to enable scripts

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#109398]
- VSCode Version: 1.50.1
- OS Version: macOS

Steps to Reproduce:

I'm providing a WebView for the sidebar. 
That is working.
However I found no way to allow script execution, i.e. to pass ```enableScripts: true```.

Not sure if this is a bug or a feature request, but I would have expected that it is possible to enable scripts to allow rich UI in the side bar.

**Comment by usernamehw** [comment]
The extension sample has it:

https://github.com/microsoft/vscode-extension-samples/blob/5dfcb7253834f664cf534ab9bdcd78e116e75e28/webview-view-sample/src/extension.ts#L40

**Comment by maziac** [comment]
Ok,
thanks.
