### ISSUE TITLE
All windows not worked and shown anymore

### ISSUE THREAD

**Issue by klee29** [microsoft/vscode#109330]
- VSCode Version: 1.50.1
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. Re-installed several times, but it still doesn't show any window and function.
2. Even I have tried to check preference or update and so on, it doesn't show any behavior. I only can see this screen. I attached my window screenshots below: 
<img width="1027" alt="Screen Shot 2020-10-25 at 10 33 53 AM" src="https://user-images.githubusercontent.com/31781090/97110082-9632d880-16ad-11eb-8e82-77c8da765ba8.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
