### ISSUE TITLE
Test: new proxy authentication dialog

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109377]
Refs: https://github.com/microsoft/vscode/issues/106489

- [x] macOS @chrmarti 
- [x] linux @deepak1556
- [x] windows @joaomoreno

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23109377%0A%0A)

---

VSCode supports to login with proxy credentials when network access is needed. The old proxy dialog always appeared as separate window, lacking a lot of the styling and translation support we have inside a window.

Since we typically do not run from an environment that needs proxy authentication, Christoph has a nice way of testing this locally via docker.

**Setup**
* Make sure `docker` command is installed on your OS or install docker if not yet done
* `git clone https://github.com/microsoft/vscode-proxy-agent.git`
* `cd vscode-proxy-agent/tests/test-http-auth-proxy`
* `docker build -t test-http-auth-proxy .`
* `docker run -d -p 3128:3128 test-http-auth-proxy`
* `code-insiders --proxy-server=http://localhost:3128`
* ✅  you should see our old login dialog appear. 

**Testing**
* configure `window.enableExperimentalProxyLoginDialog: true` to enable the new flow after a restart
* if you don't see a login dialog right on startup, trigger a search for extensions in the marketplace from extensions viewlet
* verify you only ever see 1 dialog even with multiple windows
* verify you can use `foo` as username and `bar` as password to trigger extensions search properly
* type in wrong username/password and select "Remember credentials" and verify after restart the dialog still appears with the wrong username/password prefilled and you can provide the correct credentials
* verify the same but this time providing correct credentials, you should not get asked for credentials after restart
* verify that you are getting asked for credentials again, even if they are persisted once you change the required username/password from the docker image

**Note:** credentials are stored in the OS credential store (using `keytar`). As such, you can delete the credential by looking for an `vscode.proxy-credentials` entry.

**Comment by JacksonKearl** [comment]
Temporarily removing joao to make test plan item assigner happy

**Comment by joaomoreno** [comment]
Ben, the absolute master of test plan item steps. 👑
