### ISSUE TITLE
Opening a file not in any active workspaces causes the Source Control Repository to be opened

### ISSUE THREAD

**Issue by dave-juicelabs** [microsoft/vscode#109332]
- VSCode Version: 1.51.0-insider Commit 7a3bdf4ee
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

Folders:
- "Empty Folder"
- "Another Folder"
    - .git
    - "Some file"

1. Open "Empty Folder" with vscode
2. Open "Some file" from "Another Folder" in the window with "Empty Folder" workspace
3. The repository for "Another Folder" will be opened.

Does this issue occur when all extensions are disabled?: Yes

This is more of a question about the proper action to perform when opening a file outside of the workspace. Should vscode open the repository that file is part of when it is outside all active workspaces in that code window?

**Comment by joaomoreno** [comment]
You can control this behavior with the `git.autoRepositoryDetection` setting.
