### ISSUE TITLE
Introduce a developer command to reset user data in web

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#109378]
Introduce a developer command to reset user data in web

**Comment by sandy081** [comment]
To verify -

- Open web playground - https://vscode-web-test-playground.azurewebsites.net
- Update some user state
  - Change theme
  - Move/Hide views or view containers
  - Update keybindings
  - Install some extensions (web)
- Run the command `Developer: Reset User Data`
- Make sure window is reloaded with initial state (

**Comment by rzhao271** [comment]
- Changed from a dark to a light theme but that was not reset
- Layout _was_ reset, which is good
- Keybinding wasn't reset, I changed "Add Cursor Above" to Ctrl+E
- I'm not sure how to filter installable extensions by whether it's for web. Every extension I tried could not be installed

**Comment by sandy081** [comment]
This is because, settings sync is on by default on playground and it is initialising on reset.

Please disable settings sync for testing. You can do that using query parameter `settingsSync=false`. You can find web extensions using `@web` filter.

Updated steps

To verify -

- Open web playground with **settings sync disabled** - https://vscode-web-test-playground.azurewebsites.net/?enter=true&settingsSync=false
- Update some user state
  - Change theme
  - Move/Hide views or view containers
  - Update keybindings
  - Install some extensions (web) - Use `@web` filter in extensions view to find some web extensions.
- Run the command `Developer: Reset User Data`
- Make sure window is reloaded with initial state (
