### ISSUE TITLE
VSCode-Insiders can't debug anymore 

### ISSUE THREAD

**Issue by fab1o** [microsoft/vscode#109392]
**Version: 1.51.0-insider**
`Commit: 16f4a29aa0ac05d3cba222b1f347b7404626c680`

MacOS 10.14.6

Since one of the latest versions of VSCode-Insiders, I can't debug anymore. I get this error:

```sh
auto run test
zsh: command not found: auto
```

The last time I was able to debug was a couple of months ago, so I can't pin point precisely what update caused this issue.

I go to the `package.json` file, and click on debug (above scripts) and choose the script to debug. It used to run the application and debug just fine. Now the application doesn't run, and I get the error above.

**Comment by connor4312** [comment]
/duplicate https://github.com/microsoft/vscode-js-debug/issues/808
