### ISSUE TITLE
Comment on CSS file

### ISSUE THREAD

**Issue by Shoban-Chiddarth** [microsoft/vscode#109334]
Issue Type: <b>Bug</b>

Select some part of code in .css file and press CTRL+/
It will comment
Select randomly (without particular line starting and ending)
And press
It will comment out the whole line including other lines you select, but we particularly want to comment out a specific part in a line. But we are not able to do that if we select that particular part

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (3.75GB free)|
|Process Argv|--crash-reporter-id a07bb4c3-1052-4dc1-aa04-793782e9dca3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
prettier-vscode|esb|5.7.1
beautify|Hoo|1.5.0
vscode-docker|ms-|1.7.0
python|ms-|2020.9.114305
vsliveshare|ms-|1.0.3046
debugger-for-chrome|msj|4.12.11
LiveServer|rit|5.6.1

</details>

**Comment by aeschli** [comment]
`Ctrl +/` is called `Toggle Line Comment`
Try `Toggle Block Comment` to comment a range only.
