### ISSUE TITLE
The width of the detail of a suggest can be inconsistent

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#109362]
Version: 1.51.0-insider
Commit: 7a3bdf4ee9588755d447aa1c3b5db4a123fc11a9
Date: 2020-10-23T07:32:22.213Z
Electron: 9.3.2
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:

1. Make the width of the detail of a suggest much larger.
2. Resize the window keeping the detail opened.
3. The detail flips.
5. Then, make the width of the detail much smaller.
6. Resize the window again. 
7. The detail flips even when not necessary.

Does this issue occur when all extensions are disabled?: Yes

![Oct-26-2020 19-06-14](https://user-images.githubusercontent.com/10665499/97159581-7212ec80-17be-11eb-907c-5322115149cd.gif)

**Comment by jrieken** [comment]
Yeah. It should only flip (be left aligned) when running out of space but there is still enough space...

**Comment by aeschli** [comment]
Now, when making the width smaller, the details only move to the left if there's no more space.
When making the space larger, the details go back on the right side. I assume that's still the intended behavior.
