### ISSUE TITLE
curly quotes

### ISSUE THREAD

**Issue by joseporto** [microsoft/vscode#109366]
Issue Type: <b>Bug</b>

`Use curly quotes “”, not straight quotes ""` keeps showing in the problems pane, even when I haven't set any particular setting or linting rule. How can I find the source of this problem?

No particular step that I can think of. Anytime I open a file, I will get random suggestions to use curly quotes instead of straight.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (7.58GB free)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.4.0
ng-template|Ang|0.1001.0
markdown-mermaid|bie|1.8.1
markdown-preview-github-styles|bie|0.1.6
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
postcss|css|1.0.9
vscode-markdownlint|Dav|0.37.2
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.1
gitlab-workflow|Git|3.5.0
todo-tree|Gru|0.0.186
beautify|Hoo|1.5.0
svelte-vscode|Jam|0.9.3
replace-curly-quotes|jin|1.1.0
VS-code-drupal|mar|0.0.12
git-graph|mhu|1.26.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.17
vscode-docker|ms-|1.7.0
python|ms-|2020.9.114305
vscode-pylance|ms-|2020.10.2
cmake-tools|ms-|1.4.2
cpptools|ms-|1.1.0-insiders
vscode-js-profile-flame|ms-|0.0.13
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
vetur|oct|0.28.0
origamid-next|ori|2.0.0
vscode-jest|Ort|3.2.0
vscode-proselint|Pat|0.0.3
material-icon-theme|PKi|4.3.0
vscode-text-tables|Rom|0.1.5
vscode-coverage-gutters|rya|2.6.0
vscode-stylelint|sty|0.85.0
sass-indented|syl|1.8.12
nativescript|Tel|0.11.0
vscode-iterm2-theme-sync|tus|0.1.3
lorem-ipsum|Tyr|1.2.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
vscode-wakatime|Wak|4.0.9

(4 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
These diagnostics should be coming from one of the extensions installed. Enable log level to `trace` using command `Developer: Set Log Level`. Repro the issue and you can see in the extension host logs which extension is creating these diagnostics. Extension host log can be found using `F1 > View: Open View > Log (Extension Host)`
