### ISSUE TITLE
No option such as 'Don't Auto-indent' is available

### ISSUE THREAD

**Issue by sohrabsaran** [microsoft/vscode#109382]
Please note: there is a bug #32746 that seems very similar, but I cannot reopen it.

- VSCode Version: 1.50.1
- OS Version: Linux sohrab-HP-Notebook 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
(base)

Steps to Reproduce:

1. Disable all extensions
2. Open https://github.com/sohrabsaran/tfjs-examples/blob/master/iris/data.js in vs code
3. In the bottom right-hand corner, there is an option like Spaces:2 for the Tabs to spaces mode.
4. No matter what option of the 3 available options I choose, I can't stop auto-indent.  
The three options that I see and have tried are:
 'Indent Using Spaces' - I actually need an option ('Do not Auto-Indent')
'Indent Using Tabs' - converts spaces to tabs on save, which is not what I need
'Detect Indentation from Content' - it converts the following line to 2 spaces indent from original of 4 spaces:
    ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'];

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by connor4312** [comment]
You can control this via the `editor.autoIndent` setting.

/duplicate https://github.com/microsoft/vscode/issues/5446

**Comment by rebornix** [comment]
> 'Indent Using Spaces' - I actually need an option ('Do not Auto-Indent')
'Indent Using Tabs' - converts spaces to tabs on save, which is not what I need
'Detect Indentation from Content' - it converts the following line to 2 spaces indent from original of 4 spaces:
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'];

@sohrabsaran our auto indent doesn't covert spaces or tabs on save, it is usually triggered by format on save, please check if you have any extension doing that.
