### ISSUE TITLE
Terminal search is not working as expected

### ISSUE THREAD

**Issue by genesis-algorithms** [microsoft/vscode#109325]
- VSCode Version: 1.50
- OS Version: macOS Catalina/Version 10.15.6

Steps to Reproduce:

1. `Cmd + f` > Insert text for search > Iterate forward with `Enter` or backwards with `Shift + Enter`

Does this issue occur when all extensions are disabled?: Yes

The problem is searching with `Cmd + f` in the terminal is not working as it does in the editor and it wasn't like that before. It fails to find the searched string if it's not in the range of the current "window". It seems like it's failing to search through the whole buffer to me.

I'll try to explain what I mean with screenshots.

Here, for example, the branch that I'm looking for is visible and it has no problem finding it:
<img width="1440" alt="Screen Shot 2020-10-25 at 14 47 58" src="https://user-images.githubusercontent.com/5767281/97106240-6f869900-16d1-11eb-9986-ebe903109269.png">

But if I scroll up or down a bit and the string that I'm looking for is not visible anymore it starts to fail, even highlighting something completely unrelated:
<img width="1440" alt="Screen Shot 2020-10-25 at 14 48 32" src="https://user-images.githubusercontent.com/5767281/97106305-d1470300-16d1-11eb-8d25-c7e8e0300f11.png">

Sorry if this is a duplicate, I've looked into the open issues but couldn't see any related to this.

**Comment by Tyriar** [comment]
I can't seem to reproduce this with a similar buffer. Could you check if there are errors in the devtools console (Help > toggle dev tools) and if you can come up with a minimal repro case that I could easily try repro on my end?

**Comment by genesis-algorithms** [comment]
Not sure if I should open this issue again... 😅 Hope you see my response. I'm still not able to search in the terminal.

The console errors I'm getting are those:
<img width="1080" alt="Screen Shot 2020-12-10 at 20 19 39" src="https://user-images.githubusercontent.com/5767281/101806675-515fe580-3b25-11eb-9fd8-0d9db24c9f91.png">
They appeared consistently on every window reload.

As for the reproduction case I'm not really sure... I know that It used to work before but I'm not sure how it stopped or how to reproduce that really. 😞 

If I have to open reopen the issue I will because it's an annoying bug and I've tried everything I could to make it stop (uninstalling, searching through the internet, etc.)

**Comment by Tyriar** [comment]
Nothing in the console looks off. I suspect what the issue is here is that you have git's pager open in all of them, the terminal search will not search through that, it searches through the "scrollback" which is what you can view when you use the mouse to scroll the scrollbar. To search git's pager type `/searchterm`.
