### ISSUE TITLE
Watch window cut off with horizontal scrollbar enabled

### ISSUE THREAD

**Issue by RomanKornev** [microsoft/vscode#109307]
When debugging, watch window is cut off by ~30 pixels when using a horizontal scrollbar.
The scrollbar is also not touching the edge and hanging ~30px to the left.

How it should be:
![image](https://user-images.githubusercontent.com/5807561/97088593-99d94780-163a-11eb-8bd0-283079067715.png)
How it is:
![image](https://user-images.githubusercontent.com/5807561/97088597-9e056500-163a-11eb-8cf3-34e84d0823cf.png)
Notice the vertical scrollbar position. Also notice the horizontal scrollbar - it's scrolled all the way to the left, but there is still some space missing.

- VSCode Version: 1.50.1
- OS Version: Win 10 x64 2004 + WSL2 + macOS Catalina

Steps to Reproduce:
Not the only way, happens randomly every time:
1. `"workbench.list.horizontalScrolling": true,`
2. Debug
3. Display a big list in the watch window
4. Right click -> Add Expression
5. Watch window is now cut off, horizontal scrollbar is not in the correct position.
GIF:
![2020-10-24 20 54 37](https://user-images.githubusercontent.com/5807561/97088878-8b8c2b00-163c-11eb-9ed4-8de7144931e5.gif)

Issue was not present in the recent versions of VSCode.

Does this issue occur when all extensions are disabled?: Only 1 language extension for debugging enabled. How do I debug with no extensions?

**Comment by isidorn** [comment]
Looks like a Tree issue which I think @joaomoreno is aware off and already has a duplicate for?
Assign back to me if I am mistaken, thanks!

**Comment by joaomoreno** [comment]
@isidorn We have to implement the same as in the explorer: https://github.com/microsoft/vscode/commit/5a5c5eca9960c8e2e5bfb98f55d70094d954d7dd#diff-7aedf2ce39d5f3c6edca567c1e25b828a9b8fc0eaa9d47b12be7093eb9747c23R312-R327

That is: temporarily disable horizontal scrolling when the rename widget is open. Let me know if you need help.

**Comment by isidorn** [comment]
@joaomoreno seems like you already did this. Code pointer https://github.com/microsoft/vscode/blob/4fc2aacf5a7b7fd72ef7f69ccea447e6aee5c0e8/src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts#L138

Commit https://github.com/microsoft/vscode/commit/5a5c5eca9960c8e2e5bfb98f55d70094d954d7dd

Ugly part is that every tree has to do this... So there is a lot of duplication.

**Comment by joaomoreno** [comment]
> @joaomoreno seems like you already did this. Code pointer

Strange, then it must've broken since.

> Ugly part is that every tree has to do this... So there is a lot of duplication.

Not a lot. Only tree which (1) support horizontal scrolling and (2) have input boxes in them. There is no way to get this done at the widget level, otherwise I would've done it.

**Comment by joaomoreno** [comment]
@isidorn Can you review and verify? I guess this was always happening with `New Watch Expression`, only working with `Rename Watch Expression`.

**Comment by isidorn** [comment]
@joaomoreno yeah, fix looks clean. Should have caught it myself, since new watch expression do not have a name set yet.
Thanks a lot for fixing it!

**Comment by isidorn** [comment]
I have verified that the fix seems to really fix the issue, thus adding verified label
