### ISSUE TITLE
Revisit explicit use of ConfigurationTarget.USER when updating config

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109373]
See https://github.com/microsoft/vscode/pull/109278#issuecomment-715889584. 

We have many places that enforce to update settings in `ConfigurationTarget.USER` which is a no-op if the setting is configured on a workspace level. `ConfigurationService.updateValue` derives the target appropriately if the target is not passed. So please double check your usage of this method and do not pass `ConfigurationTarget.USER` target if your intention is to change the effective value.

- [x] src/vs/workbench/browser/actions/layoutActions.ts @bpasero 
- [x] src/vs/workbench/browser/actions/windowActions.ts @bpasero 
- [x] src/vs/workbench/browser/parts/editor/editorCommands.ts @alexdima 
- [x] src/vs/workbench/browser/parts/editor/editorStatus.ts @alexdima 
- [x] src/vs/workbench/contrib/codeEditor/browser/accessibility/accessibility.ts @alexdima 
- [x] src/vs/workbench/contrib/codeEditor/browser/diffEditorHelper.ts @alexdima 
- [x] src/vs/workbench/contrib/codeEditor/browser/toggleColumnSelection.ts @alexdima 
- [x] src/vs/workbench/contrib/codeEditor/browser/toggleMinimap.ts @alexdima 
- [x] src/vs/workbench/contrib/codeEditor/browser/toggleMultiCursorModifier.ts @alexdima 
- [x] src/vs/workbench/contrib/codeEditor/browser/toggleRenderControlCharacter.ts @alexdima 
- [x] src/vs/workbench/contrib/codeEditor/browser/toggleRenderWhitespace.ts @alexdima 
- [x] src/vs/workbench/contrib/extensions/browser/extensionRecommendationNotificationService.ts @sandy081 
- [x] src/vs/workbench/contrib/files/browser/fileActions.ts @isidorn 
- [x] src/vs/workbench/contrib/files/browser/views/explorerViewer.ts @isidorn 
- [x] src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts @alexr00 
- [x] src/vs/workbench/contrib/terminal/browser/terminalInstance.ts @Tyriar 
- [x] src/vs/workbench/contrib/terminal/browser/terminalService.ts @Tyriar 
- [x] src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts @chrmarti 
- [x] src/vs/workbench/services/themes/common/themeConfiguration.ts @aeschli

**Comment by sandy081** [comment]
This shall be team task to update the usage accordingly. I will go through the references and add a check list here.

**Comment by bpasero** [comment]
Yup agree, thanks!

**Comment by Tyriar** [comment]
I think both terminal usages are fine, they're about the default renderer and shells, changing the workspace value isn't appropriate imo.
