### ISSUE TITLE
Node 12 version doesn't seem to work

### ISSUE THREAD

**Issue by dzid26** [microsoft/vscode#109312]
[Wiki ](https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites)says Node 12 is required, but when I run `yarn`, I am getting Node version error:
```
Please use node >=8 and <11.
```
![image](https://user-images.githubusercontent.com/841061/97098224-cdbf6780-1650-11eb-8454-7bff2b39bf87.png)

I downgraded my Node to 10.x and `yarn` worked.

**Comment by connor4312** [comment]
Make sure you're on the latest commit from the vscode repo, and installed after updating with a clean working directory (`git clean -dfx`)
