### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#109333]
Issue Type: <b>Feature Request</b>

Terminal not working

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.1.7600

**Comment by Tyriar** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
