### ISSUE TITLE
Automating the downloads with help from repeatable links

### ISSUE THREAD

**Issue by mwpowellhtx** [microsoft/vscode#109329]
Hello,

I'd like to automate our downloads of Code if at all possible. I see that as two prongs, first identifying the target platform and packaging, and second depending on a repeatable link.

Some links appear to forward to a front facing current version only ,i.e. [https://aka.ms/win32-x64-user-stable](https://aka.ms/win32-x64-user-stable) for the Windows x64 user installer. Whereas other links refer to a single instance only, i.e. [https://go.microsoft.com/fwlink/?Linkid=852157](https://go.microsoft.com/fwlink/?Linkid=852157) for the _Windows x64 system installer_.

Assuming there are direct, version specific download links, that would be great. Then we can simply wget the bits we want/need in a more automated manner. Is there a way for you to contain the installers by version, an archive perhaps, I am unaware of apart from the main downloads?

Thank you...

**Comment by joaomoreno** [comment]
Here's how to do it:

```
https://update.code.visualstudio.com/latest/{platform}/{quality}
```

Examples:

- https://update.code.visualstudio.com/latest/win32-x64-user/insider
- https://update.code.visualstudio.com/latest/win32-x64-user/stable

**Comment by mwpowellhtx** [comment]
@joaomoreno How about for other _platforms_, _qualities_? Windows? 32-bit? arm? arm64? Linux? macOS? Would you mind enumerating these so the pattern is plain to see? Thank you...

**Comment by mwpowellhtx** [comment]
@joaomoreno Oh, and for which versions? Other than `.../latest/...` for instance, right...

**Comment by joaomoreno** [comment]
Platforms:

```
darwin
linux-arm64
linux-armhf
linux-deb-arm64
linux-deb-armhf
linux-deb-x64
linux-rpm-arm64
linux-rpm-armhf
linux-rpm-x64
linux-snap-x64
linux-x64
win32
win32-archive
win32-arm64
win32-arm64-archive
win32-arm64-user
win32-user
win32-x64
win32-x64-archive
win32-x64-user
```

Instead of `latest` you can also use `VERSION`, eg:

- https://update.code.visualstudio.com/1.51.0-insider/win32-x64-user/insider
- https://update.code.visualstudio.com/1.50.0/win32-x64-user/stable

**Comment by mwpowellhtx** [comment]
@joaomoreno Much appreciated for the clarification. Thanks.
