### ISSUE TITLE
suggestions about preview image file type

### ISSUE THREAD

**Issue by xyyjk** [Microsoft/vscode#10931]
1. there is something important information is lost when preview images file. etc: width&height, file size.

2. file tree on the sidebar doesn't support arrow key in keyboard, like up(down) arrow key to active current file easy.

![](http://i.niupic.com/images/2016/08/25/kHshHm.png)

**Comment by sandy081** [comment]
@xyyjk This might be a good candidate for extension. Feel free to contribute. Thanks.
