### ISSUE TITLE
Preview Editor setting not always applied in Source Control panel

### ISSUE THREAD

**Issue by appetite-j** [microsoft/vscode#109393]
Issue Type: <b>Bug</b>

I have the setting `workbench.editor.enablePreview` enabled. In the "Source Control" panel I would expect all of the following actions to open a preview editor:
* 1 - Open comparison by clicking a file
* 2 - Open file by clicking the "open file" icon to the right of a file

With the setting `git.openDiffOnClick` unchecked:
* 3 - Open file by clicking a file
* 4 - Open comparison by clicking the "open changes" icon to the right of a file

What actually happens is that only case 1 opens in a preview editor, cases 2, 3, and 4 do not.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 20.1.0
Remote OS version: Linux x64 4.19.76-linuxkit

**Comment by appetite-j** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [SCM "Open Changes" not opened as a preview if "Open Diff On Click" is false (#108856)](https://www.github.com/microsoft/vscode/issues/108856)

This is similar, but it highlights an inconsistency.

**Comment by dmartin** [comment]
With the November 2020 release, seems like cases 1, 3, and 4 open in preview editors as expected, though case 2 still does not.

**Comment by joaomoreno** [comment]
Closing this issue. Case 2 is purposeful: clicking an action is an explicit user action so the editor shouldn't be in preview.
