### ISSUE TITLE
Use separate data folders when running as admin to prevent permission issues

### ISSUE THREAD

**Issue by jaanus** [microsoft/vscode#109370]
Issue Type: <b>Bug</b>

How to reproduce:
1. Install VS Code on a fresh installation of Catalina
2. Turn on settings sync

Expected: settings are synced

Observed: settings are not synced and there is this error in the sync log.

```
[2020-10-26 14:29:22.058] [userDataSync] [info] Auto Sync: Triggered by Activity
[2020-10-26 14:29:22.101] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2020-10-26 14:29:22.102] [userDataSync] [info] Keybindings: No changes found during synchronizing keybindings.
[2020-10-26 14:29:22.103] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2020-10-26 14:29:22.105] [userDataSync] [error] Error: Unable to write file '/Users/jaanus/Library/Application Support/Code/User/sync/globalState/preview/globalState.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/jaanus/Library/Application Support/Code/User/sync/globalState/preview/globalState.json')
    at writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:284:225)
    at async e.doGenerateSyncResourcePreview (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:449:37)
[2020-10-26 14:29:22.105] [userDataSync] [error] globalState: Unable to write file '/Users/jaanus/Library/Application Support/Code/User/sync/globalState/preview/globalState.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/jaanus/Library/Application Support/Code/User/sync/globalState/preview/globalState.json')
[2020-10-26 14:29:22.123] [userDataSync] [info] Extensions: No changes found during synchronizing extensions.
[2020-10-26 14:29:22.123] [userDataSync] [info] Sync done. Took 23ms
```

Note: This is bizarre because it happens only one of my several machines. On other machines, the sync works as expected. This is an iMac with a fresh install of Catalina and VS Code. To my knowledge, I have not tweaked any permissions or other system settings beyond the basic install.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (4.82GB free)|
|Process Argv|-psn_0_49164 --crash-reporter-id e2ed31e6-f3da-4702-9d0d-f7d691ceb234|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.7.0

</details>

**Comment by jaanus** [comment]
When investigating more, I found that the indicated file and folder were indeed owned by the `root` user. This may have happened because I at some point ran `code` with `sudo` to edit a privileged file. I did not expect this to interfere with settings sync.

When I manually changed owner of the file and folder to correct user, it now works as expected.

<img width="940" alt="Screenshot 2020-10-26 at 14 35 07" src="https://user-images.githubusercontent.com/184253/97173002-8a701080-1798-11eb-91b0-fcbd833faa1a.png">

**Comment by sandy081** [comment]
> This may have happened because I at some point ran code with sudo to edit a privileged file. I did not expect this to interfere with settings sync.

Delegating it to @bpasero as Settings Sync uses underlying file service to write files

**Comment by bpasero** [comment]
> When investigating more, I found that the indicated file and folder were indeed owned by the root user. This may have 
> happened because I at some point ran code with sudo to edit a privileged file. I did not expect this to interfere with settings sync.

Please do not run Code as super user. You can fix this by changing the permissions again or start with a fresh user data directory.

VSCode itself cannot fix permission problems, do you think there is still a bug with VSCode?

**Comment by jaanus** [comment]
I don’t expect VSCode to fix permission problems after the fact. I do expect VSCode to behave more robustly in these circumstances and not create files with incorrect permissions in my `Library` folder in the first place, making it harder for me as a user to shoot myself in the foot.

I can think of at least two changes that would make the behavior more robust.

1) Running `sudo code` is the root cause of settings files with incorrect permissions. There is currently no warning or guidance to user when running `sudo code`. Maybe Code should refuse to run as super user, or provide some warning. I see how it could break other things besides settings sync.

2) In settings sync, I would expect Code to not write any files with incorrect permissions into my `Library` folder when it is running as superuser, and thus preventing settings sync from working correctly when running next sessions as my regular user. (This could mean several things in practice - just not executing settings sync, setting the correct permissions during execution, etc.)

**Comment by bpasero** [comment]
> Running sudo code is the root cause of settings files with incorrect permissions. There is currently no warning or guidance to user when running sudo code. Maybe Code should refuse to run as super user, or provide some warning. I see how it could break other things besides settings sync.

We show a notification, subtle though:

![image](https://user-images.githubusercontent.com/900690/97266593-0154ea00-1829-11eb-978c-21009ebb6f13.png)

I don't think refusing to start is an option.

> In settings sync, I would expect Code to not write any files with incorrect permissions into my Library folder when it is running as superuser, and thus preventing settings sync from working correctly when running next sessions as my regular user. (This could mean several things in practice - just not executing settings sync, setting the correct permissions during execution, etc.)

One thing we could do is to detect that a user is running as admin and then use a totally separate directory for user data and extensions. This would make sure that the folders we use for persisting any state are not getting written to with permissions that cause these issues. 

The downside of this approach is that anyone expecting today's behaviour would suddenly see a fresh instance of VSCode starting where previously it had the same settings.

**Comment by bpasero** [comment]
I would argue this is covered by https://github.com/microsoft/vscode/issues/6560
