### ISSUE TITLE
Bad typing performance when Problems tab updates on every keypress

### ISSUE THREAD

**Issue by RomanKornev** [microsoft/vscode#109406]
Seems that some extensions update the Problems tab on every keypress which causes severe typing performance drop, e.g. https://github.com/Dart-Code/Dart-Code/issues/2902 @DanTup
Dart file:
![2020-10-24 01 03 59](https://user-images.githubusercontent.com/5807561/97058192-c8511700-1595-11eb-92ce-5eb43533f85b.gif)
Any other file:
![2020-10-24 01 04 53](https://user-images.githubusercontent.com/5807561/97058208-ce46f800-1595-11eb-95a4-4ee0feb92b07.gif)
No other extensions, except Dart-Code are enabled.
- VSCode Version: 1.50.1
- OS Version: Win10 x64 2004

Steps to Reproduce:

1. Install https://github.com/Dart-Code/Dart-Code
2. Open Problems tab
3. Make a new `.dart` file
4. Start typing
5. Notice extremely bad typing performance
6. Switch off Problems to Output
7. Performance increased significantly

Does this issue occur when all extensions are disabled?: Only Dart extension is enabled

**Comment by sandy081** [comment]
I wrote a sample extension that updates diagnostics on every change and I do not see issues with typing performance.

Can you please profile your instance and provide us the info - Please follow this link to profile - https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

It might also be helpful to report the issue against dart extension to see if there are any changes/improvements.

**Comment by DanTup** [comment]
This was raised in the Dart-Code repo, but since it only occurs when the Problems view is visible and the typing also stutters, I don't think it's related to the CPU usage of the Dart extension (which is in the extension host) but rather the rendering of the Problems view.

The language server is shared by multiple clients, so I'd prefer not to add delays/throttling into its updates for them all for the performance characteristics of one specific component of one specific client (at least not without LSP having some general guidance about this).

**Comment by RomanKornev** [comment]
Here's some CPU profiles:
[Laggy with Problems tab shown](https://github.com/microsoft/vscode/files/5462149/CPU-20201030T032341.cpuprofile.txt)
[Smooth with Problems tab hidden](https://github.com/microsoft/vscode/files/5462148/CPU-20201030T032511.cpuprofile.txt)

**Comment by RomanKornev** [comment]
@sandy081 Any progress on this issue? I provided the CPU profiles.

**Comment by sandy081** [comment]
Sorry, no progress yet, will look into this soon.

**Comment by sandy081** [comment]
Before

<img width="536" alt="image" src="https://user-images.githubusercontent.com/10746682/100498394-2b6c3580-3162-11eb-9a19-be9854b0a3dc.png">

<img width="442" alt="image" src="https://user-images.githubusercontent.com/10746682/100498437-8867eb80-3162-11eb-85dd-e7fd95a06066.png">

After Fix

<img width="538" alt="image" src="https://user-images.githubusercontent.com/10746682/100498402-345d0700-3162-11eb-8b6d-fd55cd678c98.png">

<img width="428" alt="image" src="https://user-images.githubusercontent.com/10746682/100498404-39ba5180-3162-11eb-98bb-c40bfc11a982.png">

Debounced rendering by `64 ms`
