### ISSUE TITLE
Test: js-debug diagnostic tool

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#109420]
Refs https://github.com/microsoft/vscode-js-debug/issues/260

- [ ] anyOS @misolori
- [x] anyOS @fiveisprime

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23109420%0A%0A)

---

In js-debug this month we added a diagnostic tool with the goal of helping developers troubleshoot their own breakpoint issues via the `Create Diagnostic Information` command while a debug session is running. (Currently we don't prompt for this, but we will.)

For this you should try to create some broken builds/launch configs 🙂 Things that I can suggest (this is not a todo list)

- Set a breakpoint in a file that isn't loaded by your application
- Compile typescript code and try to debug it without `sourceMap: true` in your tsconfig
- Set `sourceRoot` in your tsconfig to some invalid location
- With sourcemaps, specify an incorrect/non-existent `outFiles` location
- If debugging in the browser, set a webRoot in the wrong place

...or anything else you can think of :) The diagnostic tool has heuristics that are designed to provide actionable feedback -- or, at least, actions that can be googled -- in the event of a bad build setup. Let me know if you run into a case where this is not the case.

**Comment by fiveisprime** [comment]
Works great in Windows, but I was unable to open the diagnostics when using WSL (#109507)

**Comment by misolori** [comment]
This is really cool. I especially like that when I debugged a gatsby app that it detected the component and then where it compiled to and pointed to it in runtime:

![image](https://user-images.githubusercontent.com/35271042/97359891-b653ca80-185a-11eb-8cd3-e6b0ccab87e1.png)

Two large bits of feedback:
- The tool is quite text heavy, which means I have to slow down and ready the text to figure out what it's telling me. Would be interesting to see if we could play around with the text hierarchy to increase the scanability of the page.
- I really wish there was a way to get this info FROM the tool. For example, when I have an unverified breakpoint, there is nothing in the tool that tells me why it didn't hit it. This is where you want the diagnostics so some type of indicator either near the breakpoint in the editor or debug view.
