### ISSUE TITLE
Empty entry in SCM commit history

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109442]
Testing #109428

Not entirely sure how I got there, but I have an empty entry in my SCM history. This happened early during testing. I did make a commit which I then undid. Maybe that's how the empty entry happened

![Oct-27-2020 09-10-28](https://user-images.githubusercontent.com/1794099/97273993-4e8a8900-1834-11eb-9d05-25f37202d667.gif)

**Comment by joaomoreno** [comment]
This is https://github.com/microsoft/vscode/issues/109443
