### ISSUE TITLE
Loosing what I have typed in SCM input box

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109443]
Testing #109428

* use ArrowUp to select an entry from SCM
* select and overtype the text
* select ArrowUp and the the previous input
* select ArrowDown 
* 😢 what you have typed is gone

![Oct-27-2020 09-13-54](https://user-images.githubusercontent.com/1794099/97274354-d53f6600-1834-11eb-938c-75f9761bcd43.gif)

**Comment by jvesouza** [comment]
This is confirmed and I can reproduce using the following steps:

* Press ctrl+shift+g.
* Type "this is a test", without the quotations.
* Press DownArrow.
* Press UpArrow.

The text "this is a test" disappears. Perhaps in my case it has something to do with the fact that I am using the orca screen reader.

**Comment by joaomoreno** [comment]
@meganrogge This is the issue we just talked about.
