### ISSUE TITLE
Suggest widget: ideal resizing not wide enough

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#109461]
#109394

1. Open any TS file in the VS Code repo, type `areK` trigger suggest widget
2. Have the size like in picture 1. Double click on the sash to get the ideal size
3. The widget gets too narrow - some of the items are horizontally cut off. The widget should be more wide in this case (picture 2)

Explorer when double clicking on the sash tries to always respect the widest element.
Apart from that it has a min width it can go to.

![Screenshot 2020-10-27 at 11 38 53](https://user-images.githubusercontent.com/1926584/97290690-2f4a2680-1849-11eb-9279-1b8c2f011781.png)
![Screenshot 2020-10-27 at 11 40 09](https://user-images.githubusercontent.com/1926584/97290693-3113ea00-1849-11eb-96a9-f5092c68555f.png)

**Comment by jrieken** [comment]
Todays logic uses the average length of the labels. This might be skewed given that we have short labels for keywords like `let`, `for` etc

**Comment by jrieken** [comment]
I don't really know how wide elements are because they aren't rendered yet - this considers all completions. However, I have a change that will take 85th percentile of label lens (instead of average length). That works better from my testing
