### ISSUE TITLE
Screen flickering when resizing details panel

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#109448]
Testing #109394

See screen cast

![cast](https://user-images.githubusercontent.com/1931590/97277601-f6a25100-1838-11eb-84ce-50c7282ac481.gif)

**Comment by jrieken** [comment]
hm... looks like max height is unhappy...

**Comment by isidorn** [comment]
I get a similar experience so will not file a new bug.
Just for me the details view jumps a bit up - does not go fully crazy

![recording](https://user-images.githubusercontent.com/1926584/97295176-3f650480-184f-11eb-9ee1-53b3f443ce55.gif)
