### ISSUE TITLE
Enable "Remote.SSH: Remote Server Listen On Socket" by default

### ISSUE THREAD

**Issue by buzh** [microsoft/vscode#109475]
By default (at least on Linux and macOS), VSCode opens a TCP port listening to localhost: for connections. This means that for multi-user systems, user A can connect to and control the session of user B. This is obviously a major security and privacy issue.

There is a documented workaround here: https://code.visualstudio.com/docs/remote/troubleshooting#_improving-security-on-multiuser-servers

However, this requires that each user configures the software individually. In large multi-user infrastructures such as HPC, this does not scale. We as administrators will have a hard time hunting down the users who have not configured their vscode installation securely, and it is difficult to prevent mishaps, misunderstandings and so-on.

I therefore ask that you either make "listen on socket" the default, and/or provide a mechanism for system administrators to globally enforce the setting (e.g. if /etc/vscode.conf has "listenonsocket=true" then vscode always uses sockets instead of tcp ports)

Best regards,
Buzh

**Comment by roblourens** [comment]
We are aware of this issue and are working on a better solution that will address some of the shortcomings of that setting and will be able to work by default. Sorry that there is no public discussion that I can link you to, but please know that we are working on it.
