### ISSUE TITLE
Loosing SCM history when entering "workspace mode"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109450]
Testing #109428

* open a simple folder
* use SCM and have some history
* add another folder so that the workbench is now in workspace mode
* make another change for the initial folders
* 🐛 the SCM history is gone

**Comment by joaomoreno** [comment]
I wonder if we should just store this data in global storage then, since we always scope it to the SCM repo, in the storage key. What do you think @meganrogge?

**Comment by JacksonKearl** [comment]
Seems like there's still some oddness here. If I open a folder, make some commits, then run add folder to workspace, I loose the history that I created in the single folder case. Perhaps `e.reason === WillSaveStateReason.SHUTDOWN` is not true in the add folder to workspace case, as it's a reload?

**Comment by meganrogge** [comment]
> Seems like there's still some oddness here. If I open a folder, make some commits, then run add folder to workspace, I lose the history that I created in the single folder case. Perhaps `e.reason === WillSaveStateReason.SHUTDOWN` is not true in the add folder to workspace case, as it's a reload?

Yes exactly. [This ](https://github.com/microsoft/vscode/commit/2ee8b8c645ec8ab54304bacae7aa979c1d9c647a) fixes that
