### ISSUE TITLE
Enforced restart does not terminate running debug session

### ISSUE THREAD

**Issue by neilyoung** [microsoft/vscode#109468]
- VSCode Version: 1.50.1
- OS Version:  Darwin x64 19.6.0

Steps to Reproduce:
Noticed it while having a Rust debug session open, but I suppose it applies to other languages too. I was using an app, which establishes a Webserver at a given port, so I noticed, that the port was still allocated after having returned from enforce restart.

1. Start a debug session
2. Manipulate an extension, which enforces a Restart

Does this issue occur when all extensions are disabled?: No

**Comment by weinand** [comment]
Are the following steps a correct description of the problem your are seeing?
- start debugging a Rust application that establishes a Webserver at a given port
- open the Webserver address in a browser and verify that it works
- press F1 and find the "Developer: Reload Window" action and execute it
- reload the browser and notice that it still works

**Comment by neilyoung** [comment]
@weinand Sorry, I realized that I didn't really start a VSCode debug session, but did run my app via `cargo run` from a terminal window within VSCode. Those apps are apparently not terminated on restart. I guess you can silently close this "non-issue". Sorry for the hassle.

**Comment by weinand** [comment]
no problem.
