### ISSUE TITLE
VS Code does not understand ANSI escape sequences

### ISSUE THREAD

**Issue by Nowhk** [microsoft/vscode#109483]
- VSCode Version: 1.50.1
- OS Version: Windows 10 Professional (64 Bit), version 2004

Steps to Reproduce:

1. run an application that output ANSI char in the terminal. in my case C++, with a fprintf such as `fprintf(outputFile, "\x1B[%dm", levelColors[level]);`

When I watch the terminal, I can't see the color as they should be, but lots of char messes:

![image](https://user-images.githubusercontent.com/19835752/97310764-e489d800-1863-11eb-8361-d19bb94364d4.png)

**Comment by Tyriar** [comment]
What shell are you using and do you have `terminal.integrated.windowsEnableConpty` set?

**Comment by Nowhk** [comment]
@Tyriar here's my settings:

```
{
  "workbench.sideBar.location": "right",
  "terminal.integrated.shell.windows": "C:/msys64/usr/bin/bash.exe",
  "terminal.integrated.shellArgs.windows": [
    "-i"
  ],
  "terminal.integrated.env.windows": {
    "MSYSTEM": "MINGW64",
    "PATH": "/mingw64/bin:/usr/local/bin:/usr/bin:/bin:${env:windir}/System32:${env:windir}:${env:PATH}"
  },
  "terminal.integrated.cwd": "c:\\repos\\",
  "extensions.ignoreRecommendations": false,
  "files.autoSave": "off",
  "diffEditor.ignoreTrimWhitespace": false
}
```

**Comment by Tyriar** [comment]
This is related to the fact that you're using msys64/mintty which I don't think has great support for conpty, the relatively new component from the Windows terminal team which does support these sequences. Nothing we can do on our side here.

**Comment by Nowhk** [comment]
@Tyriar till build 2004 on windows, I was able to do this placing ` -mconsole` on build and changing buffer using `std::setvbuf(outputFile, nullptr, _IOFBF, BUFSIZ);`.

Why now this is not possible anymore? Can you explain me?

**Comment by Tyriar** [comment]
@Nowhk I'm not sure what that means? This issue's about ansi support breaking in mintty?

**Comment by polyclash** [comment]
@Tyriar @Nowhk 
Support for ANSI it's n̲o̲t̲ e̲n̲a̲b̲l̲e̲d̲ by default on Windows 10 console host,
unless the specific software you're using enables ANSI processing by calling the `SetConsoleMode` API with the `ENABLE_VIRTUAL_TERMINAL_PROCESSING (0x0400)` flag, you won't see colors or get ANSI processing for that application.
Or you can enable it globally with the regkey `HKEY_CURRENT_USER\Console\VirtualTerminalLevel ` with value key `"VirtualTerminalLevel"=dword:00000001`.
https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#example

**Comment by warasilapm** [comment]
For what it's worth, I switched my git for Windows install back to just use cmd instead of wintty and it resolves this issue.

**Comment by Tyriar** [comment]
This report is really old and likely related to the old version of Windows. Newer versions of Windows 10 and 11 both use conpty which improves many cases where this can happen, but it could still happen regardless (eg. if something escapes them). We'll be bundling conpty so it's not tied to the version of Windows soon, see https://github.com/microsoft/vscode/issues/224488
