### ISSUE TITLE
Suggest widget details size should be remembered until end of suggest session

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#109462]
Testing #109394

1. Open suggest widget, open the details 
2. Resize the details view so it is very large
3. Cmd + space to hide the details view. But the suggest is still visible
4. Cmd + space to show the details again. The details does not preserve the size from step 3

I believe the size of the details view should be preserved until suggest widget gets closed.

**Comment by jrieken** [comment]
Today it's implemented to drop it's custom size when hidden. Unsure what best?

**Comment by isidorn** [comment]
I think closing suggest widget is the clear signal which we should use for all of these things (until when to remember something). That way it will be more consistent and easier for users to understand.
