### ISSUE TITLE
New snippet variable: UUID_V4 (generate a random UUID)

### ISSUE THREAD

**Issue by hi2u** [microsoft/vscode#109438]
Vscode snippets support [a bunch of auto-generated variables](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables) - e.g. variables related to filepaths, timestamps etc.

Could you please add a new variable called something like `UUID_V4`  that will auto-generate a version 4 UUID? (random)

e.g. When executing the snippet, the `${UUID_V4}` placeholder would be replaced with a value like: `e83961ec-f06d-4539-b7ba-a08175ceac3c`

**Comment by waldo1001** [comment]
@vscode-triage-bot , that's a wrap!  Now put it on the backlog, and in the software :D

**Comment by nrayburn-tech** [comment]
@jrieken could the generateUuid function be used with a `RANDOM_UUID` snippet variable?
https://github.com/microsoft/vscode/blob/ebb316a2881f131069b2eef901a84a94ca2fba8a/src/vs/base/common/uuid.ts#L30

I don't know how different the uuid and uuid_v4 are, or if that matters here.

I can submit a PR if that function works, or if you have any input on how to go about this.

**Comment by jrieken** [comment]
@nrayburn-tech Yeah, that function should be OK to be used

**Comment by jrieken** [comment]
To _verify_ make sure that you can have a snippet like this: `Hello $UUID`
