### ISSUE TITLE
Timeline 

### ISSUE THREAD

**Issue by sjPUB** [microsoft/vscode#109431]
Issue Type: <b>Bug</b>

Timeline doesn't appear in my Wiindows installation.
I'm a beginner, trying to use VS Code. This is the first item on the Tips & Tricks video! 
So not a good start.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.83GB free)|
|Process Argv|--crash-reporter-id b2165682-1166-4ae9-bd06-d9bcbeea6521|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
open-html-in-browser|cod|0.1.21
debugger-for-chrome|msj|4.12.11
LiveServer|rit|5.6.1

</details>

**Comment by eamodio** [comment]
The Timeline view will only show when a there is a Git repository open -- if you don't see anything in the Source Control side bar then this is expected behavior.
