### ISSUE TITLE
The completion widget should always be alligned with the cursor especially if there is enough horizontal space

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#109481]
Testing #109394

<img width="1108" alt="capture" src="https://user-images.githubusercontent.com/1931590/97309609-8ad4de00-1862-11eb-8323-892904cc8dab.png">

I would prefer the widget shrinks instead of positions left of the cursor.

**Comment by jrieken** [comment]
I don't see where your cursor is and how wide your window is. But "yes" with the widget is always anchored at the cursor position unless too wide. That applies to custom or default widget - imagine the case in which you type at the end of the line

**Comment by dbaeumer** [comment]
The cursor was here `Err<|>or`. I see the end of the line argument. However in my case I would have preferred the widget gets smaller than pushed to the left.

This being said it is a corner case. No one will hopefully make the widget so big :-)
