### ISSUE TITLE
Unable to use breakpoints when debugging a serverless node typescript application when debug.javascript.usePreview is enabled

### ISSUE THREAD

**Issue by tylerjgarland** [microsoft/vscode#109408]
- VSCode Version: 1.50.1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:
**launch.json is configured as below.**

```{
            "type": "node",
            "request": "launch",
            "name": "Debug Serverless API",
            "program": "${workspaceFolder}/node_modules/serverless/bin/serverless",
            "args": [
                "offline",
                "--stage",
                "dev"
            ],
            "env": {
                ...
            },
            "outFiles": [
                "${workspaceFolder}/.webpack/service/functions/**/*.js"
            ]
        }
```

When `debug.javascript.usePreview` is set to true, breakpoints do not trigger. A work around is to use `debugger;` in each file you want to debug. You can then set breakpoints normally. If I set `.usePreview` to false, I can remove all `debugger;` commands and use breakpoints as normal. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by tylerjgarland** [comment]
I turned on tracing but the file is pretty massive so please point me to relevant data if you need.

**Comment by connor4312** [comment]
Also, first thing I would try to removing `outFiles` from your launch config

**Comment by tylerjgarland** [comment]
@connor4312 , that was the trick. Thanks.
