### ISSUE TITLE
Smart select on second level of list selects a newline instead of another list item  

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#109489]
Testing #109417

Smart select on second level of list ("level_1") selects a newline at the end of the line instead of the next  list item on level:

![2020-10-27_15-24-58 (1)](https://user-images.githubusercontent.com/1898161/97315146-b4910380-1868-11eb-8cc0-1216017cb79b.gif)

**Comment by rebornix** [comment]
I am running into similar issues with lists

![expand](https://user-images.githubusercontent.com/876920/97330758-dde46c00-1835-11eb-98c1-5f7946724b6b.gif)

As you see from above, expanding the second item on the list, expands from cursor -> word -> line -> block, however expanding the third item, expands from cursor -> word -> line -> line + line break -> block.
