### ISSUE TITLE
winpty-agent.exe is different for each VSCode version

### ISSUE THREAD

**Issue by lucamanga** [microsoft/vscode#109465]
The problem is that we have a Group Policy to restrict the access to executables.
The policy permits the user to execute all executables in "C:\Program Files".
The problem is that Visual Studio Code tries to run an executable from this strange path:
 
   "\\?\C:\Program Files\Microsoft VS Code\...."

we must write new hash file of winpyh-agent.exe that is submitted on each VSCode version.

Could you remove that initial "\\?\"  ?

- VSCode Version: 1.50.1 (but affects earlier versions, too)
- OS Version: Windows 10

Steps to Reproduce:

1. Open Terminal
2. An error popus: "The terminal process failed to launch: A native exception occurred during launch (Error launching WinPTY agent: winpty-agent CreateProcess failed: cmdline='"\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\node-pty\build\Release\winpty-agent.exe"

Does this issue occur when all extensions are disabled?: Yes

**Comment by lucamanga** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [TS Server fatal error:  Debug Failure. (#106004)](https://www.github.com/microsoft/vscode/issues/106004)
> 
>     * [TS Server fatal error:  Debug Failure. (#108025)](https://www.github.com/microsoft/vscode/issues/108025)
> 
>     * [TS Server fatal error:  Debug Failure. (#107065)](https://www.github.com/microsoft/vscode/issues/107065)
> 
>     * [TS Server fatal error:  Maximum call stack size exceeded (#105605)](https://www.github.com/microsoft/vscode/issues/105605)

None of these. It is not an error, it is a Group Policy of our organization that limits the run of executables from strange paths.
The temporary fix is to insert the **hash code** of the Winpty-agent.exe, but this is not too comfortable (we should update it at EVERY vscode release)

**Comment by Tyriar** [comment]
Sorry that's a legacy feature and we're not changing how it ships at this point. If you're on Windows 1903+ the recommendation is to move off this anyway as the default for `terminal.integrated.windowsEnableConpty` is `true`.
