### ISSUE TITLE
Indentation error

### ISSUE THREAD

**Issue by Architk25** [microsoft/vscode#109488]
1. My vscode is glitching out on some kind of indent error, My default is set to tabs with size of 4 - but it's indenting in spaces.

2. Also, I can't edit the indents - it just adds in a new indent in if I press backspace and remove one, please  help me if any specific extension/setting is glitching vscode.

Thanks in advance.

**Comment by thsubaku9** [comment]
I think I kind of understand what you're going through, I followed these 3 steps to get my tab properly working:

1. File -> Preferences -> Settings -> Set tab size as the amount of spaces a tab is equivalent to

2. Detect Indentation may be on leading to overwrite of default tab size

3. Insert Spaces may be on (allows you to move your cursor to positions in between the tab)

Might help you if it was the same problem as mine

**Comment by Architk25** [comment]
Well, I already have it switched off and it is still not that error, the
error is that whenever I indent, It just glitches out, I cannot backspace
or tab at all - I'm using Atom now.

 - Regards,
 Archit Kumar
 MYP - 1

**Comment by Architk25** [comment]
Ummmm...
I don't know how, but the glitch is finished!
It must have been something temporary - Welp!
This issue is now **Closed**
