### ISSUE TITLE
Support smart select in character markup

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#109498]
Testing #109417

Character markup like `**bold**` or images and links `[Duck Duck Go](https://duckduckgo.com)` are not smart selectable.
The selection always jumps to words and then lines.

![2020-10-27_16-21-38 (1)](https://user-images.githubusercontent.com/1898161/97322912-8dd6cb00-1870-11eb-8fbb-ce16c0304741.gif)

It would be useful if the selection can expand to the `**bold**` and full links.

**Comment by rebornix** [comment]
I would expect this behavior as well.
