### ISSUE TITLE
Scope proxy credentials to proxy host and port

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#109497]
Testing #109377

Running two proxy servers on localhost with different ports and different credentials I'm presented with the credentials dialog every time I switch proxies even though I chose to remember the credentials.

A PAC file (proxy config) can configure more than one proxy and use different ones depending on the host that needs to be accessed.

**Comment by bpasero** [comment]
Nice catch.

**Comment by bpasero** [comment]
Initially I had the idea to simply store a JSON into the credentials manager that has entries per proxy, but then I realised that `keytar` exposes an API to us that allows to store credentials for a specific `account`:

https://github.com/microsoft/vscode/blob/5ede377c03c7960411d93d9ea61efc1efc82acb2/src/vs/platform/native/common/native.ts#L149-L150

@RMacfarlane to confirm that this is OK to be different per proxy server. I quickly checked in macOS keychain and I see one entry per service+account in the list.

To get a unique `account` name I produce a hash over some of the properties of `AuthInfo`, but not all:

https://github.com/microsoft/vscode/blob/e113cbf2970eb09070fb49a5a6705cacafb0a753/src/vs/code/electron-main/auth2.ts#L120-L120

@deepak1556 to confirm that this is OK to differentiate different proxy servers.

**Comment by deepak1556** [comment]
yup `scheme, host and port` are sufficient to differentiate the servers.

**Comment by bpasero** [comment]
**Verification:** on macOS follow https://github.com/microsoft/vscode/issues/106489#issue-699287308 and check that the credentials persisted into keychain use a number as "Account" in the "*.proxy-credentials" credential.
