### ISSUE TITLE
Test: electron 11 exploration builds

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#109425]
Refs: https://github.com/microsoft/vscode/issues/106489

- [x] macOS @sandy081
- [x] linux @weinand
- [x] windows @alexr00

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23109425%0A%0A)

---

We plan to promote Electron 11 in the next milestone for Insiders. Download the latest released Code Exploration build from [here](https://builds.code.visualstudio.com/builds/exploration)

**Verify:**
1) our smoke tests pass when run against this build (in case of an error, compare with insiders to see if it is Electron related or not)

2) Compare `Developer: startup performance` numbers with insiders, if there is a slowdown open an issue with the report.

3) Some exploratory testing covering some native pieces of the application
  * **macOS:**
      * Native Tabs (enable via settings: `window.nativeTabs: true`)
         - Verify opening tabs isn't slow
      * Simple Fullscreen (enable via settings: `window.nativeFullScreen: false`)
         - Verify going fullscreen isn't slow
      * window is focused when starting from command line
         - open code exploration
         - open a terminal outside
         - type code-exploration
         - make sure the window is put to foreground
      * Verifying extension debugging works fine
      * Verify automatic update works fine.

  * **windows:**
      * touch device, verify onscreen keyboard doesn't pop up when clicking inside vscode while external keyboard is attached
      * verify maximize and restore operations work as expected when task bar is auto-hidden for custom titlebar
      * verify minimizing and restoring the window doesn't reset to minimum width
      * Verifying extension debugging works fine
      * Verify titlebar is not clipped off when exit fullscreen
          - Maximize VS Code window
          - Press F11 or Ctrl+K Z twice to enter/exit full screen.
          - Verify titlebar is not cropped
      * Verify there is no rendering lag with custom titlebar
      * Verify opening multiple windows doesn't stop rendering the oldest windows
      * verify scroll performance on 4k monitors

  * **linux:**
      * Verify opening multiple windows doesn't stop rendering the oldest windows
      * Verify extension debugging works fine
      * Verify application launches successfully
         - Snap
         - Deb
         - RPM
     
4) check out the `electron-11.x.y` branch locally and verify you can run out of sources, set a breakpoint and debug using chrome devtools

**Comment by alexr00** [comment]
I was not able to verify "verify scroll performance on 4k monitors" since I don't have one. Otherwise, it looks good!

**Comment by weinand** [comment]
Since I do not have a native linux system, I'm testing this on Parallels with Ubuntu 20.

Launching "VS Code Exploration" results in this screen cheese:

<img width="1215" alt="2020-10-27_17-55-04" src="https://user-images.githubusercontent.com/1898161/97335810-8d453100-187e-11eb-9ba2-6e5822c83ad7.png">

Launching "VS Code Exploration"  with the "--disable-gpu" command line flag makes it work.

**Comment by deepak1556** [comment]
@weinand are you on parallels 16 ? That would be an upstream issue https://github.com/electron/electron/issues/26061, the only workaround now is to use `--disable-gpu`

**Comment by weinand** [comment]
@deepak1556 yes, I'm on Parallels 16.1.0

**Comment by weinand** [comment]
BTW, scrolling speed on my 5k monitor on **macOS** is great. I don't see any problems.

**Comment by weinand** [comment]
Startup performance on **linux** seems to be slightly faster than Insiders.

**Comment by deepak1556** [comment]
Nice data, thanks for testing everyone!

**Comment by weinand** [comment]
Fun fact: the automatic smoketest runs without issues despite the fact that the "VS Code Exploration" build produces screen cheese (https://github.com/electron/electron/issues/26061) because I did not pass the "--disable-gpu" flag.

**Comment by weinand** [comment]
On Fedora (on Parallels 16.1) "VS Code Exploration" runs fine without the "--disable-gpu" flag.
