### ISSUE TITLE
Extensions are not showing/have very few downloads and no ratings

### ISSUE THREAD

**Issue by DirkdenHoedt** [microsoft/vscode#109416]
- VSCode Version: 
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-15T10:42:48.064Z
Electron: 9.3.2
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
- OS Version:
Linux x64 5.9.1-arch1-1

Steps to Reproduce:

1. Open VS Code
2. Check the Extensions tab

Does this issue occur when all extensions are disabled?: Yes

Since some time, extensions have a lot less downloads then they have on the marketplace website. Also, a lot of extensions are not visible, see screenshot below.
![image](https://user-images.githubusercontent.com/23523283/97229608-ec506a80-17d8-11eb-8607-766425cd35b0.png)
![image](https://user-images.githubusercontent.com/23523283/97229975-700a5700-17d9-11eb-9f74-de6dcd4a7575.png)

I can't find any information regarding this problem on the internet anywhere.
I have even completely reinstalled VS Code and deleted all of my user settings files in the ~/.config folder. What am I missing here or is this a bug?

**Comment by tamuratak** [comment]
Duplicate of #109365 and #107997. See https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Comment by DirkdenHoedt** [comment]
Sorry I did research but did not find this. Thank you.
