### ISSUE TITLE
Suggest widget details widget sometimes too large

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#109458]
Refs: #109394

Trigger inteli-sense anywhere in VS Code. Navigate to the AbortController, trigger details view. The details view always looks a bit too high.
Details view should never be larger than the full content height.

![Screenshot 2020-10-27 at 11 33 24](https://user-images.githubusercontent.com/1926584/97290042-4dfbed80-1848-11eb-986c-ee0bddafb9f2.png)

**Comment by jrieken** [comment]
Yeah, today it's just guess work and not really measuring...
