### ISSUE TITLE
Double clicking resize handle makes widget too small and doesn't resize details pane

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#109474]
Testing #109394

![cast](https://user-images.githubusercontent.com/1931590/97299341-1d6e8080-1855-11eb-8811-b229edc4c6bf.gif)

See the `...` behind a completion item.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/109461
