### ISSUE TITLE
Allow extra default paths for searches

### ISSUE THREAD

**Issue by niccolomineo** [microsoft/vscode#109472]
I wasn't able to find out whether this can be done already or somehow worked around.

I would like to propose the possibility to add extra default paths for searches, other than the workspace / project path.

My aim is to be able to search in the virtualenv, which pyenv decouples from the workspace / project (by default all pyenv's virtualenvs are found in `~/.pyenv/`).

**Comment by roblourens** [comment]
When you say "search" you are talking about text/file search right? You can search in another folder by entering its path, but I don't want to confuse the concept of a workspace by adding extra folders to it that show up in searches but aren't part of the workspace.
