### ISSUE TITLE
Shortcut improvements

### ISSUE THREAD

**Issue by matejkramny** [Microsoft/vscode#10949]
Is it possible to define shortcuts like:

- `cmd+k cmd+u` (convert selection to uppercase)
- `cmd+k cmd+l` (convert selection to lowercase)
- `cmd+l` when selected multiple lines, create a cursor at the end of each line
- `ctrl+cmd+up(arrow)` move selection up/down

What would be the best way to implement these, and if you don't mind I can make a PR for this?

**Comment by sandy081** [comment]
@matejkramny You can write an extension for all of them using our API and Commands. Please refer here 

https://code.visualstudio.com/docs/extensions/overview

https://code.visualstudio.com/docs/extensionAPI/overview

**Comment by mrmlnc** [comment]
For lowercase and uppercase transformation you can use https://marketplace.visualstudio.com/items?itemName=florianloch.text-transform

**Comment by matejkramny** [comment]
Thanks! I'll have a look and write an extension.

I found the `Microsoft/vscode-sublime-keybindings` package but it doesn't cover these bindings.
