### ISSUE TITLE
Smart select needs extra expand steps to reach top header

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#109493]
Testing #109417

![2020-10-27_15-39-16 (1)](https://user-images.githubusercontent.com/1898161/97317020-ad6af500-186a-11eb-86f9-d4353cd26762.gif)

Please note: the screen cast doesn't show the additional two expand steps necessary to fully expand to the header

**Comment by rebornix** [comment]
+1 on this, I personally would like to skip the intermediate step (selecting all content under header).

**Comment by jrieken** [comment]
I have pushed `smart-select-trivia` (https://github.com/microsoft/vscode/compare/joh/smart-select-trivia) which has an option to disable the automagic expansion of leading/trailing whitespace.

**Comment by jrieken** [comment]
also related/duplicate issue https://github.com/microsoft/vscode/issues/67339

**Comment by meganrogge** [comment]
Steps to verify the [fix](https://github.com/microsoft/vscode/compare/joh/smart-select-trivia):

Use the above [code ](https://github.com/microsoft/vscode/issues/109493#issue-730516087) or similar that requires extra expand steps to reach the top header.

Uncheck `editor.smartSelect.selectLeadingAndTrailingWhitespace` in settings. Verify that it now doesn't require the extra expand steps.

**Comment by weinand** [comment]
Indeed, after setting `editor.smartSelect.selectLeadingAndTrailingWhitespace` to false, no extra expands steps are necessary.
