### ISSUE TITLE
Invalid file resource . c++

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#10942]
- VSCode Version:1.5.0-insiders
- OS Version:10.12

Steps to Reproduce:

1.  open a c file.
2. press f12 and then meet this error.
![vscode-error](http://o8z0dg641.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-08-25%20%E4%B8%8B%E5%8D%887.19.06.png)

**Comment by sandy081** [comment]
This issue was moved to Microsoft/vscppsamples#170
