### ISSUE TITLE
Crash in node-oniguruma when tokenizing this malformed string with the JS grammar

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#10945]
```
let badStr = [9,109,46,115,101,116,40,110,117,108,108,44,32,39,233,55356,102,102,111,111,39,41,59,10].map(code => String.fromCharCode(code)).join("");
```

**Comment by alexandrudima** [comment]
PR submitted: atom/node-oniguruma#57

**Comment by alexandrudima** [comment]
Does not look like they will accept the PR in time for the August code freeze.

**Comment by alexandrudima** [comment]
The PR to oniguruma got accepted, we adopted latest oniguruma, plus I did some work in edf62453dce23780817eb28a98828cc4bdbd431d to prevent edits from producing invalid UTF16

**Comment by alexandrudima** [comment]
Related #12329
