### ISSUE TITLE
Test: Copy/Paste in Web

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#109422]
Refs https://github.com/microsoft/vscode/issues/108349

- [x] macOS @kieferrm Safari
- [x] Win @devinvalenciano /Linux, any browser 
- [x] Linux @bpasero

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23109422%0A%0A)

---

We improved the Copy/Paste experience on Web this iteration to appeal to the security restrictions of Clipboard API. Those security restrictions vary a lot on different platforms so we need to get them well tested.

Please open VS Code in Web and test at least following scenarios:

* `cmd/ctrl+c` / `cmd/ctrl+v` in the monaco editor
  * type in the find widget, then `cmd/ctrl+c/x` from the it and then `cmd/ctrl+v` in the editor, and vise versa
* `cmd/ctrl+c` from somewhere else and the `cmd/ctrl+v` in the terminal
  * `cmd/ctrl+f` in the terminal, type in the find widget and then select all text then cut, lastly, `cmd+v` in the terminal
* open a GitHub issue notebook file, run a query, get more than one result 
  * `cmd/ctrl+c` from the rich output 
  * click the icon on the left of the outputs container, switch to `text/markdown` renderer, select some text from the rendered output and perform `cmd+c`
  * test `cmd+v`
* open the extension page, select some text and then `cmd+c` and then test `cmd+v` pastes the right content

Please note that Context Menu -> Paste might lead to issues on some platforms due to limitations listed in https://github.com/microsoft/vscode/issues/108349#issuecomment-708728384 . Other than that, you should get a seamless `cmd+c/v` experience in vs code components.

**Comment by bpasero** [comment]
@rebornix I tested on Linux inside a CS and it seems to large work fine. But the integrated terminal does not accpet my `Ctrl+V` when I paste into the prompt. I see this appear:

`^V^V`

Does it work for you?

**Comment by rebornix** [comment]
@bpasero I pushed a change to fix this yesterday, CS doesn't pick this up yet.

**Comment by devinvalenciano** [comment]
Everything works great on Windows (new Edge), except the terminal paste issue Ben mentions (pic below). Copy from terminal and paste to editor works, though.
![image](https://user-images.githubusercontent.com/1389808/97486262-70f5d280-1918-11eb-83ab-9e44ada9de4e.png)

**Comment by JacksonKearl** [comment]
removed the runner emoji which caaused the testplan item to become invalid

**Comment by rebornix** [comment]
@devinvalenciano can you share the commit of VS Code used in your CS? I verified that it's already working locally in Web.

**Comment by devinvalenciano** [comment]
Version: 1.51.0-insider
Commit: 16f4a29aa0ac05d3cba222b1f347b7404626c680
Date: 2020-10-26T05:37:52.074Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Edg/86.0.622.51

This was the commit info from my test this morning.  I opened a new Codespace on a different repo now, and I got the same build.

**Comment by rebornix** [comment]
Thanks @devinvalenciano it's one build behind so the fix is not in yet.
