### ISSUE TITLE
Test: Smoke Test

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#109426]
- [x] Windows @stevencl
- [x] macOS @egamma
- [x] Linux @mjbvz
- [x] web @isidorn 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23109426%0A%0A)

---

**NOTE:** Desktop & Web tests MUST run with `--build` argument

**NOTE:** Desktop tests MUST run with `--stable-build` argument additionally

Documentation: https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md#run.

If the automated tests fail, create and issue for that and run the tests manually: https://github.com/microsoft/vscode/wiki/Smoke-Test

**Comment by isidorn** [comment]
Web looks good

![Screenshot 2020-10-27 at 11 28 27](https://user-images.githubusercontent.com/1926584/97289517-949d1800-1847-11eb-981a-ecaf962ec3a8.png)

**Comment by egamma** [comment]
macOS looks good

![image](https://user-images.githubusercontent.com/172399/97311593-cffa0f80-1864-11eb-9ed4-fd1c8cf8e364.png)

**Comment by stevencl** [comment]
One reported failure on Windows:

![image](https://user-images.githubusercontent.com/1704059/97340903-45bda580-187c-11eb-95f3-616ed2f64571.png)

**Comment by mjbvz** [comment]
Linux (Ubuntu) passed for me
