### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by H-bit90** [microsoft/vscode#109490]
Issue Type: <b>Bug</b>

Intead of giving me a regular terminal it gives me an intagreated terminal, please help.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.27GB free)|
|Process Argv|--crash-reporter-id 5ea1b28a-73fa-4d1e-92ee-c18861e42326|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.1.0-insiders3

</details>

**Comment by Tyriar** [comment]
Shortcut to external terminal is ctrl+shift+c, integrated is ctrl+`

**Comment by H-bit90** [comment]
Thank you.
