### ISSUE TITLE
Down arrow closes suggest in SCM input

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#109494]
I use the suggest widget in the SCM view to add my issues number. When I hit down arrow, it now closes the suggest widget.

![recording (25)](https://user-images.githubusercontent.com/38270282/97317298-f1f69080-186a-11eb-93f5-b99cbb5ba2de.gif)

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/109145
