### ISSUE TITLE
preserve  debug target on reload

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode#109455]
Now on window reload the run/debug target would com back to the first one. I want it to remember last used one.

**Comment by isidorn** [comment]
I can not reproduce.
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
If yes, can you please share a minimal repository on GitHub that I can clone and reproduce this issue? Thanks

**Comment by xgdgsc** [comment]
I'm using a centos 7.6 container with vscode remote.

**Comment by xgdgsc** [comment]
Still reproduceable for me.
