### ISSUE TITLE
Extension sets

### ISSUE THREAD

**Issue by alexkreidler** [microsoft/vscode#109430]
Currently, "Workspace recommended extensions" and "Extension Packs" allow for installing sets of extensions in one action.

However, if one wants to disable or re-enable those extensions, they have to do it one-by-one.

It would be great to have Extension Sets, where a user can edit a map of IDs/names, and optional descriptions, for sets of extensions, with the actual set of extensions each contains. This could be represented in a user or workspace JSON config file.

Then, users should be able to enable/disable all extensions in a set at once.

Additionally, both "Workspace recommended extensions" and "Extension Packs" should automatically contribute Extension sets with the names: `workspaceRecommended` (or similar), of course scoped to the workspace, and `<extension-pack-id>` where <extension-pack-id> is the ID of the VSCode extension that provides the extension pack, which would be scoped globally, just like extensions.

This feature would enable better ease-of-use for managing many many extensions, and likely improve performance because users would only use the minimal set of extensions needed for the task at hand.

Any feedback would be appreciated.

**Comment by gjsjohnmurray** [comment]
Provided your chosen extension pack uses the `extensionPack` object to define its member extensions, disabling the pack will disable all the members. The same goes for enabling.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/105342
