### ISSUE TITLE
remote ssh explorer did not show host in included ssh config

### ISSUE THREAD

**Issue by secmask** [microsoft/vscode#109432]
- VSCode Version: 1.49.3
- OS Version: MacOS 10.15

Steps to Reproduce:

1. in .ssh/config define include `Include config.d/*`
2. in config.d/myconf define list of host

Actual: SSH Explorer can only show host define in .ssh/config file itself
Expect: can also list host define in `config.d`

Does this issue occur when all extensions are disabled?: No

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2446
