### ISSUE TITLE
Efficient tab switching workflow

### ISSUE THREAD

**Issue by matejkramny** [Microsoft/vscode#10948]
I came to Code from TextMate and Sublime world. In those editors, you use CMD+[1-9] to switch between open tabs.

How do you efficiently switch between tabs in Code? It seems a little counter intuitive (for me) for cmd+2 to open a split screen.

Please note i am not criticising how it is in VSCode. I get that most users of Code have maybe larger screens and switch between split screens often. However different users work differently, so I am curious about the reasons behind this approach and also see if there's any way I can configure the editor to open tabs using cmd+num shortcuts.

Thanks!

**Comment by bpasero** [comment]
@matejkramny you can configure keybindings to get this behaviour:

`{ "key": "cmd+1",                "command": "workbench.action.openEditorAtIndex1" }`

**Comment by matejkramny** [comment]
oh awesome! You're a lifesaver :)
