### ISSUE TITLE
Suggest widget: allow resize to be multi directional

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#109463]
Testing #109394

Currently I can only resize horizontally if I grab the sash on the right.
I can only resize vertically if I grab the sash on the bottom.

Why not allow me to resize however I want whenever I grab any of those 2 sashes?
I think the experience than would be smoother and will make the vertical resize more discovarable, as I belive the sash on the right is easier to find.

**Comment by jrieken** [comment]
@isidorn You can grab the corner and resize both height and width at the same time

**Comment by isidorn** [comment]
Ok. Just a bit hard to find that. Though makes sense. Especially since our grid view behaves just like that.

Feel free to close as designed if you want.

**Comment by jrieken** [comment]
Closing this since I have related issue to make the sash areas larger. With that it should be easier to grab them.

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/109447
