### ISSUE TITLE
"One or more dirty editors could not be saved to the back up location."

### ISSUE THREAD

**Issue by jansensan** [microsoft/vscode#109404]
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:
1. Open Terminal
2. Run `code /Users/<username>/.ssh/authorized_keys`
3. I dont know, quit VSCode?

Does this issue occur when all extensions are disabled?: **Yes**

**Current Behavior:**
VSCode endlessly throws this error as I try to quit:

> One or more dirty editors could not be saved to the back up location.

I do not care for the changes in this file. I tell it don't save, and VSCode always tries to reopen it when I start VSCode. It always blocks quitting because unsaved changes in that file. I want to discard those changes, I don't care for them, I don't want VSCode to open that file anymore.

**Expected Behavior:**
When I discard the changes and close the file, VSCode should not try to reopen it. I have not asked for that action, leave the file be.

**Comment by jansensan** [comment]
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/1410355/97309251-269d2480-1838-11eb-9d4f-c4d3c92deab8.png">

This is pretty much all the additional information I can provide unless you ask for specific details. The file keeps reopening every time I open VSCode, and I do not want that.

When I try to close it, I get the modal above, from which I choose "Don't Save". Once I choose that option, that should be the end of that file trying to reopen, but if I close VSCode and reopen it, the same thing happens again and again.

I might simply delete the whole application and reinstall it.

**Comment by bpasero** [comment]
@jansensan maybe this is a permission problem, did you run Code as `sudo` before?

You can manually fix this by closing all VSCode instances and delete `~/Library/Application Support/code/Backups`. This will delete any unsaved changes you have though!

**Comment by jansensan** [comment]
@bpasero Yes that did the trick!

re: `sudo`, maybe? I am setting up a new computer, jumping from the old one to the new to ensure access to a website host has access to keys. Maybe I opened I did that locally instead of the remote location.

I'd say this issue is resolved.
