### ISSUE TITLE
Terminal running in background

### ISSUE THREAD

**Issue by Sitri08** [microsoft/vscode#109413]
Issue Type: <b>Bug</b>

When using Ctrl+F5 to run a file, it will not close unless the code exits or it is ended with Shift+F5/status bar stop button. However, when overriding the currently running code with another Ctrl+F5 command, the first one will not instantly abort, but rather keep running as a background process. This will only end with repeated presses of Shift+F5/status bar stop button. 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.88GB (10.82GB free)|
|Process Argv|--crash-reporter-id adea8e88-167f-4aeb-b05d-a29d6ad7349e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
arm|dan|1.4.0
vscode-html-css|ecm|0.2.3
csharp|ms-|1.23.4
python|ms-|2020.9.114305
cpptools|ms-|1.0.1
veriloghdl|msh|1.3.5

</details>

**Comment by connor4312** [comment]
What language/debugger are you using? This is probably an issue for them

**Comment by Sitri08** [comment]
This happens in Python, I think the details for that are in the original post.

**Comment by connor4312** [comment]
Thanks, please file an issue for them

\extPython
