### ISSUE TITLE
Show current debug line in overview ruler

### ISSUE THREAD

**Issue by rickstaa** [microsoft/vscode#109456]
I think it would be beneficial to show the current line the debugger is on in the overview ruler (For example, using an orange colour). Currently, when `debug.showBreakpointsInOverviewRuler` is enabled, it only shows the debug breakpoints. 

*Current behavoir*
![image](https://user-images.githubusercontent.com/17570430/97287758-3f600700-1845-11eb-8458-a7ce029b12c6.png)

*Requested behaviour*

![image](https://user-images.githubusercontent.com/17570430/97288816-acc06780-1846-11eb-995b-86877ccd60c9.png)

**Comment by isidorn** [comment]
Yeah, not a bad idea.
Let's do the change start of next milestone so we have a full milestone to get feedback on this. Thus assigning to November.

**Comment by isidorn** [comment]
I have pushed a change to tackle this. You can try it out with vscode insiders in 7 days and let me know how it goes.

**Comment by rickstaa** [comment]
@isidorn Amazing thanks a lot! I will test it out in 7 days.

**Comment by rickstaa** [comment]
@isidorn It works and looks amzing! Very minimalistic. Thanks a lot for implementing this.

**Comment by isidorn** [comment]
Great, thanks for trying it out and for letting us know. Adding verified label.
