### ISSUE TITLE
Widget doesn't adapt to new editor size - missing details pane

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#109473]
Testing #109394

![cast](https://user-images.githubusercontent.com/1931590/97298896-66720500-1854-11eb-9de4-60dffb4814dc.gif)

**Comment by dbaeumer** [comment]
After maximizing VS Code I see this

<img width="1803" alt="capture" src="https://user-images.githubusercontent.com/1931590/97299070-ab963700-1854-11eb-81b6-150b06a7f510.png">

**Comment by jrieken** [comment]
Not super pretty but when running out space the details widget should show atop the list... This is what I see when running from master

<img width="693" alt="Screenshot 2020-10-28 at 12 37 33" src="https://user-images.githubusercontent.com/1794099/97431301-5de40200-191a-11eb-89c3-7efde3493b42.png">

**Comment by dbaeumer** [comment]
That would work for me.

**Comment by jrieken** [comment]
Alright. Closing and waiting for verification 🎲

**Comment by dbaeumer** [comment]
Verified from source.
