### ISSUE TITLE
Suggest widget: details sash should be on the left side if details is rendered on the left

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#109464]
Testing #109394

1. Have the suggest widget quite wide that there is no space for the details to be rendered on the right
2. Trigger details -> it is rendered on the left
3. The details view still uses the right resize sash. It should use the left sash

![recording (1)](https://user-images.githubusercontent.com/1926584/97296449-fada6880-1850-11eb-80d2-70cd53afd269.gif)

**Comment by jrieken** [comment]
Valid point. I didn't do this (yet?) because I wanna make the widget freely moveable

**Comment by jrieken** [comment]
Adding bug for verification
