### ISSUE TITLE
Last run task does not on the top of the task list when config tasks in workspace.

### ISSUE THREAD

**Issue by zuoxiaofeng** [microsoft/vscode#109454]
Issue Type: <b>Feature Request</b>

When put tasks in folder's .vscode, at the top of task list is last run task.
But when put tasks in workspace config file, the task list is fixed and do not show last run task in the top of the list.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 3.10.0-1127.13.1.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.13.1.el7.x86_64

**Comment by roblourens** [comment]
Where is the "last run task" supposed to show up?

![image](https://user-images.githubusercontent.com/323878/144292400-cb49014b-7bf8-4fa6-a7e7-6ede0f9669c8.png)

**Comment by alexr00** [comment]
1. Open a workspace with a .code-workspace file.
2. Add a tasks section to the workspace file with at least one task in it.
3. Run the command "Run Task". Run your new workspace file task.
4. Run the command "Run Task".
5.  You should see a "recently used" section at the top of the task picker:
![image](https://user-images.githubusercontent.com/38270282/144386250-60573272-1b75-44d4-9bb3-7a46664c3611.png)

> Note: Make sure you don't have the task history set to zero (`task.quickOpen.history`).

**Comment by weinand** [comment]
This works fine now.
