### ISSUE TITLE
Can we have an API to figure out the list of files Visual Studio Code is watching?

### ISSUE THREAD

**Issue by kartikeyshetty** [microsoft/vscode#109452]
I have a large codebase opened in Visual Studio Code ( about 60k files ). I get the "Unable to watch for file changes ... " whenever i do. To get rid of the message, i have the files.watcherExclude setting set up, leaving only about 1000 files on watch. My watcher limit is the typical 8192 files. But with these settings on, the "Unable to watch..." pops up. I suspect my files.watcherExclude pattern. 

Is there an API to see the list of files Visual Studio Code is watching ?If not can we get one. I can improve my watcherExclude pattern if i can see which files are still being watched.

**Comment by GitMensch** [comment]
Come on botty, that's 15 votes and a list of that is definitely available "internally", it's just about dumping these per request to the output pane...

**Comment by GitMensch** [comment]
A (possibly not portable) workaround for Linux was posted by @jhanschoo in https://github.com/microsoft/vscode/issues/45295#issuecomment-449713658. It is a shell script that tries to query that information. from the handles open on process-level.
