### ISSUE TITLE
Vertical resize stops without indication why

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#109471]
Testing #109394

Screen cast

![cast](https://user-images.githubusercontent.com/1931590/97298515-cf0cb200-1853-11eb-93ab-a3679d42a1ff.gif)

It is unclear to me why I can't make the widget longer.

**Comment by jrieken** [comment]
> It is unclear to me why I can't make the widget longer.

It stops when no more suggestions can be rendered. That's to prevent empty space below the suggestions

**Comment by dbaeumer** [comment]
OK Thanks. Makes sense

**Comment by jrieken** [comment]
Check - closing in that case
