### ISSUE TITLE
Reuse integrated terminal when running debug target

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#10940]
When running the debug target in the integrated terminal, every debug session results in a new terminal instance. Managing these terminals is a pain.

Please reuse the terminals based on their title.

Ideally, the terminal API should have a way to find out whether the terminal is "busy" (a process is already running). In this case you would not reuse the terminal but create a new terminal (and append a number to the title). If necessary please file an API request for this.

**Comment by isidorn** [comment]
Assigning to September, if we decide to ship the integrated terminal support this milestone then I will assign this to August

**Comment by weinand** [comment]
@isidorn the September milestone is ok. We will ship this feature behind a (non documented) launch config flag in August and we will test it next week.
