### ISSUE TITLE
Windows defender popup when extension debugging

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#109484]
Testing #109425

I started extension debugging the a sample extension and the Windows defender pop up showed. Not sure if this is expected or not.

**Comment by deepak1556** [comment]
Did you test with archive version of the build or user/system installed version ?

**Comment by alexr00** [comment]
System installed.

**Comment by deepak1556** [comment]
@alexr00 do you see this with latest insiders ?

**Comment by alexr00** [comment]
Yes, I'm still seeing the Windows defender popup. Tested with the latest insiders and with the latest exploration. Both were system installed.

**Comment by rzhao271** [comment]
I'm unable to reproduce the issue with my old sample extension at https://github.com/rzhao271/uri-format-setest on v1.52.1 or 1.53.0-insider.

Does the Windows Defender popup still occur for you with that extension?
Also, when it did pop up in the past, did the popup mention which files were flagged?

**Comment by alexr00** [comment]
Seems to be fixed now. I no longer see the defender pop up when extension debugging.

**Comment by deepak1556** [comment]
Thanks for confirming!
