### ISSUE TITLE
incompatible sync service for 1.50.1

### ISSUE THREAD

**Issue by rudotriton** [microsoft/vscode#109470]
I'm using settings sync to have the same settings between the stable and the insiders builds of vsc, however, the latest stable build throws an error when I want to enable sync.

<p align="left" >
    <img width="450" alt="error message
" src ="https://user-images.githubusercontent.com/14181026/97297339-8e646700-185a-11eb-9540-1d9c87e09898.png">
</p>

```
Settings sync cannot be turned on because the current version (1.50.1, d2e414d9e4239a252d1ab117bd7067f125afd80a) is not compatible with the sync service. Please update before turning on sync.
```

I uninstalled and reinstalled both versions: stable and insiders and the problem still occurs. Also, insiders doesn't seem to have the [Settings Sync: Select Service...](https://code.visualstudio.com/docs/editor/settings-sync#_syncing-stable-versus-insiders) command anymore, the service selection is only available when turning on sync.

- VSCode Version: 1.50.1
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. Launch vscode-stable
2. Try to go through the "Turn on Settings Sync..." flow

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Yeah this is expected because your insiders is now incompatible with your stable version. You can sync with stable again when stable is updated to 1.51

**Comment by carlocardella** [comment]
Is it because I have Insiders use the Stable sync channel (and that breaks Stable with some incompatible format)?

**Comment by sandy081** [comment]
Yes. Recently we added a new feature - Sync extensions global state https://github.com/microsoft/vscode/issues/95209. This changes the format of extensions data. This feature is already available in insiders and not in stable yet. Hence you got into incompatible state.

This will get fixed automatically when we release stable and you update to it/

**Comment by 454de6e** [comment]
Is there an ETA for the update?

**Comment by sandy081** [comment]
Mostly by end of this week.
