### ISSUE TITLE
Search in subdirectory can not be combined with file filtering

### ISSUE THREAD

**Issue by AndreyDodonov-EH** [microsoft/vscode#109476]
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open a desired folder with vs code
2. Perform a search in the subdirectory AND file filtering with a wildcard.

**DOESN'T WORK**
![image](https://user-images.githubusercontent.com/44361144/97301265-d7ff8280-1857-11eb-9d55-60b583abdd37.png)

**WORKS**
![image](https://user-images.githubusercontent.com/44361144/97301310-e8176200-1857-11eb-802b-90ba56976b9c.png) 

**ALSO WORKS**
![image](https://user-images.githubusercontent.com/44361144/97301568-3593cf00-1858-11eb-9ee1-9daa3416c134.png)

**Comment by roblourens** [comment]
You need to use `**/*.h` to search subfolders. `*.h` only matches files but when it is by itself, we expand it to `*.h`.
