### ISSUE TITLE
Chrome renderer is causing 100% cpu on mac

### ISSUE THREAD

**Issue by idanhaviv** [microsoft/vscode#109457]
Issue Type: <b>Performance Issue</b>

Issue happens on startup on a mac book pro.

causing process spec: 

37757  98.4  1.0  8833956 169092   ??  R    12:20PM   8:54.44 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) --inspect-port=0 /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork --type=extensionHost

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id ea905aca-7013-4dd0-bd25-b1aa07baf998|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    98	 36132	code main
    0	    82	 36135	   gpu-process
    0	    33	 36137	   utility
    0	   246	 36138	   window (rooms.service.ts — server)
    0	     0	 36495	     /bin/zsh -l
    0	   131	 36507	     extensionHost
    0	    98	 37068	       electron_node tsserver.js 
    0	   229	 37071	       electron_node tsserver.js 
    0	    33	 38394	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=36507
    0	    33	 36997	     watcherService
    0	    33	 37050	     searchService
    0	   262	 36139	   window (App.tsx — web)
    0	     0	 36509	     /bin/zsh -l
    0	   131	 36550	     extensionHost
    0	    98	 37102	       electron_node tsserver.js 
    0	   180	 37103	       electron_node tsserver.js 
    0	    33	 38024	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=36550
    0	    33	 37006	     watcherService
    0	    33	 37058	     searchService
    0	    98	 36494	   shared-process
    0	     0	 38693	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   295	 37523	   window (questions.js — meet10-admin)
    0	     0	 37743	     /bin/zsh -l
    0	    49	 38551	       node /usr/local/Cellar/yarn/1.22.5/libexec/bin/yarn.js start
    0	    33	 38552	         npm
    0	    33	 38553	           /Users/idanhaviv/.nvm/versions/node/v12.18.3/bin/node /Users/idanhaviv/Developer/meet10/meet10-admin/node_modules/.bin/nodemon --watch ./**/*.js --ignore node_nodules/* --exec node ./bin/www
    0	    66	 38627	             /Users/idanhaviv/.nvm/versions/node/v12.18.3/bin/node ./bin/www
   99	   164	 37757	     extensionHost
    0	    98	 38026	       electron_node tsserver.js 
    0	   180	 38027	       electron_node tsserver.js 
    0	    33	 37934	     watcherService
    0	    33	 38016	     searchService
    1	    66	 38686	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (questions.js — meet10-admin)
|  Window (App.tsx — web)
|  Window (rooms.service.ts — server)
|    Folder (meet10-admin): 43 files
|      File types: js(22) json(3) dockerignore(1) env(1) gitignore(1) yml(1)
|                  png(1) html(1)
|      Conf files: package.json(1)
|    Folder (server): 135 files
|      File types: js(35) map(33) ts(33) json(3) yml(2) env(1) gitignore(1)
|                  md(1) sh(1) lock(1)
|      Conf files: launch.json(1) package.json(1) tsconfig.json(1)
|      Launch Configs: node(2)
|    Folder (web): 343 files
|      File types: tsx(138) svg(86) ts(21) otf(10) json(7) js(5) map(5) png(4)
|                  txt(3) css(3)
|      Conf files: settings.json(1) package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.4.0
quitcontrol-vscode|art|3.1.3
folder-source-actions|bie|0.2.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.2
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
vscode-graphql|Gra|0.3.10
vscode-react-typescript|inf|1.3.1
vscode-edit-csv|jan|0.4.2
vscode-styled-components|jpo|1.2.0
vscode-format-context-menu|lac|1.0.4
expand-region|let|0.1.4
camelcasenavigation|map|1.1.3
mssql|ms-|1.9.0
python|ms-|2020.9.114305
vsliveshare|ms-|1.0.3046
vscode-react-native|msj|1.1.0
copy-json-path|nid|0.1.0
code-settings-sync|Sha|3.4.3
js-jsx-snippets|sky|10.1.0
vscode-fileutils|sle|3.3.3
copy-with-imports|str|0.1.7
vscodeintellicode|Vis|1.2.10
gitblame|wad|6.0.0
vscode-todo-highlight|way|1.0.4
vscode-js-console-utils|wht|0.7.0
material-theme|zhu|3.9.3

(1 theme extensions excluded)

</details>

**Comment by alexr00** [comment]
Please see the wiki page on reporting a performance issue: https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by maapteh** [comment]
On a new fresh macbook pro the code renderer consumes 700% cpu on 8 core machine. Only have VSC installed and happens during boottime when VSC is not even on. Also i havent even installed any workspace nor extension. Im happy to provide all debug info as well.
