### ISSUE TITLE
Menu has issues with very long labels

### ISSUE THREAD

**Issue by boyvinall** [Microsoft/vscode#10941]
- VSCode Version: 1.4.0
- OS Version: Windows 7

Steps to Reproduce:
1. open a folder with a really long path
2. File / Open Recent

Currently the ellipsis is right at the end of the path, which makes it difficult to know which path you're opening if you have several long paths in the list.  Ideally, the ellipsis should reduce folder names in the middle of the path. See https://blog.codinghorror.com/shortening-long-file-paths/ for inspiration.

**Comment by boyvinall** [comment]
![image](https://cloud.githubusercontent.com/assets/1652176/17963850/57509e44-6aaf-11e6-9053-658920643907.png)

**Comment by bpasero** [comment]
We are not doing anything special but rely on the Electron menu here.

**Comment by boyvinall** [comment]
Hi @bpasero, I raised this on electron as you can see, but it seems they think this is a VSCode issue.

**Comment by bpasero** [comment]
I disagree with their assessment and added a comment.

**Comment by boyvinall** [comment]
Thanks

**Comment by bpasero** [comment]
@sbatten for the custom menu we might want to throw in a `max-width` possibly to avoid large paths exploding the menu.
