### ISSUE TITLE
Gulp task to build directly a tar.gz or zip archive for linux version

### ISSUE THREAD

**Issue by snakebyte85** [microsoft/vscode#109570]
I need to repackage vs-code with some custom extension

I followed the instructions in order to build vs-code from source and repackage it

The problem is that for windows version I can package it in a zip, but the same type of build is misising for the linux version.

There are gulp tasks for create a .deb or .rpm package, but there aren't for .zip or .tar.gz. But I see that vs-code is distributed in tar.gz archives

What am I missing?

**Comment by joaomoreno** [comment]
Just use command line: `zip` or `tar`.
