### ISSUE TITLE
The detail of a suggest is not scrollable when it should be.

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#109577]
Version: 1.51.0-insider
Commit: bb16786cff3d231facbdcee90741ac25fcffd3ac
Date: 2020-10-28T05:53:18.953Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:

1. Make the height of window of VS Code small.
1. Open a TypeScript file.
1. Type `vscode.languages.`, then open suggests and details with `Ctrl-Space`.
2. The detail of a suggest `vscode.languages.match` is not scrollable despite it should be.

![Oct-28-2020 19-13-21](https://user-images.githubusercontent.com/10665499/97423273-53ddf580-1952-11eb-8eab-2a39fd94ad1f.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Thanks. This is fixed on master. I don't recall the commit tho...

**Comment by jrieken** [comment]
<img width="1193" alt="Screenshot 2020-10-28 at 12 13 28" src="https://user-images.githubusercontent.com/1794099/97428927-fed0be00-1916-11eb-9082-2e2ed4c50b07.png">
