### ISSUE TITLE
RE: #109518

### ISSUE THREAD

**Issue by shalevv123** [microsoft/vscode#109579]
- VSCode Version: 1.50.1
- OS Version: 1909

Steps to Reproduce:
1. install vscode on a drive
2. remove the drive from your PC
3. try to install vscode on a new drive

Does this issue occur when all extensions are disabled?: Yes

![vscode bug](https://user-images.githubusercontent.com/73291739/97424792-e57d4100-1919-11eb-8970-6ca656edafac.png)

i keep on getting this error message when trying to install vscode on my new drive, please help i really need it for school

i cant uninstall VSCode becuas i dont have the old drive in my possesion. what can i do?

**Comment by joaomoreno** [comment]
Let's continue the discussion on that other issue.
