### ISSUE TITLE
Terminal always show uppercase letters when using caps lock to switch input source

### ISSUE THREAD

**Issue by jasonxia23** [microsoft/vscode#109565]
- VSCode Version: 1.50.1
- OS Version: 10.15.7

Steps to Reproduce:

1. Set system input source to shuangpin, before which add shuangpin as an input source.
![image](https://user-images.githubusercontent.com/15098719/97403011-97bf0380-192e-11eb-90a8-5c2f551a17cb.png)
2. Lock caps lock, with caps lock unlock, you will input Chinese character, which is an expected behavior.
3. Input something in the integrated terminal, I can only input upper case letters. But when I input something in editor or some other application, I can input lower case letters.

Does this issue occur when all extensions are disabled?: Yes.

Actually I think it might be the problem of xterm.js. Xterm.js might decide the letters by cap lock. This is not as expected with shuangpin mode.

**Comment by Tyriar** [comment]
This looks like an upstream issue in https://github.com/xtermjs/xterm.js

**Comment by jasonxia23** [comment]
Thanks for replying. Opened an issue for xterm.js. https://github.com/xtermjs/xterm.js/issues/3155
