### ISSUE TITLE
Unclear what merging logic is for extension global state

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#109535]
Testing #109388

Since syncing of extension global state is async of updating the state, it is unclear what merging will happen if 2 clients are working with the same extension state at the same time.

If PC1 sets the value of some state, the following must happen in order to understand the data flow:
1. PC1 syncs with service
2. PC2 syncs with service
3. PC2 uses state
4. PC2 updates state
5. PC2 syncs with service

Alternatively, it is unclear what should happen here:

1. PC1 sets state
2. PC2 gets state (it is not in sync with PC1)
3. PC2 sets state based on outdated info
4. PC1 syncs state
5. PC2 syncs state (should server state be from PC2 or PC1)

**Comment by sandy081** [comment]
In case of merge, remote always wins. So in your scenario, the machine (PC1 or PC2) that goes into merge state gets the remote state. This is very hypothetical and theoretical given that Settings Sync is per user and not across users. So its very rare that sync gets into this state. In such a case, as mentioned, we always take from remote. This is also true while syncing core global state.
