### ISSUE TITLE
Integrated terminal does not work if opened from command line

### ISSUE THREAD

**Issue by cfitz25** [microsoft/vscode#109563]
- VSCode Version: 1.50.1
- OS Version: Manjaro, KDE Plasma: 5.19.5, Kernel: 5.8.16

Steps to Reproduce:

1. Running `code` in the bash terminal in manjaro
2.  Select "New Terminal"

Does this issue occur when all extensions are disabled?: Yes

The new terminal that is opened is blank and its label is also blank. If i open it from the application object it starts up fine however even though it should also be being launched with terminal behind the scenes

**Comment by Tyriar** [comment]
Could you provide:

- A screenshot of the blank terminal (including the panel title bar)
- Your settings.json file

**Comment by cfitz25** [comment]
Here they are, sorry i had to compress the settings as it wasnt allowed to be uploaded.
[settings.tar.gz](https://github.com/microsoft/vscode/files/5462294/settings.tar.gz)
![vscode-terminal](https://user-images.githubusercontent.com/412214/97647635-7bda6f80-1a9e-11eb-99e3-6dd6b347fef1.png)

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/76542

Remove the `terminal.integrated.inheritEnv` setting to fix this.
