### ISSUE TITLE
Need HTML Matching Keystroke

### ISSUE THREAD

**Issue by KvChaos** [Microsoft/vscode#10953]
- VSCode Version: 1.4
- OS Version: Windows 10

In HTML editor, need a keyboard mapping that allows you to jump to the matching tag.  I am aware that if you place the cursor on a tag, the matching tag is highlighted; but in a div that may sufficiently long as to not be visible on the screen, it would be useful to quickly jump to the matching tag.

It would also be extremely useful to have a keyboard mapping that selects the entire current block.  e.g., Ctrl+B within a div selects the entire div.  This facilitates quickly re-arranging elements within a document without visually hunting for the beginning/ending tags of an element.  

Thank you for this great editor and providing it as free & open source!

**Comment by sandy081** [comment]
Duplicates #8446
