### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by p8queiroz** [microsoft/vscode#109589]
Issue Type: <b>Bug</b>

I downloaded the latest version of visual code VSCodeUserSetup-x64-1.50.1.exe to my machine and the terminal opens but it only show white screen and do not allow me to type anything.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.75GB free)|
|Process Argv|--crash-reporter-id 3c5e2478-c45f-42c3-8b66-7b527cb7090b|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by usernamehw** [comment]
Possible duplicate of #105431
