### ISSUE TITLE
locks up mac. Reboot required

### ISSUE THREAD

**Issue by FrankOwen** [microsoft/vscode#109560]
Issue Type: <b>Bug</b>

When editing go code, mac will eventually become unresponsive, fans will spin at highest speed. mouse pointer spinner of death is presented, and force reboot seems to be the only way out of it. Suspect gopls is the culprit, but can't be sure.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|22, 7, 2|
|Memory (System)|16.00GB (5.68GB free)|
|Process Argv|-psn_0_86037 --crash-reporter-id 6a4f9d94-c5d8-41ab-8eb9-4b23eb3c5c02|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.12.0
swagger-viewer|Arj|3.0.1
gitlens|eam|10.2.2
go|gol|0.18.0
yaml-plus-json|hil|1.4.1
vscode-favorites|how|1.8.3
git-graph|mhu|1.26.0
binary-viewer|mom|0.0.1
vscode-docker|ms-|1.7.0
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.9.114305
hexeditor|ms-|1.3.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-yaml|red|0.11.1
code-settings-sync|Sha|3.4.3
vscode-hexdump|sle|1.8.1
vscode-dicom|smi|1.4.0
python|tht|0.2.3
json2yaml|tux|0.2.0

</details>

**Comment by alexr00** [comment]
Does this happen if you disable all installed extensions?
