### ISSUE TITLE
DeprecationWarning: Buffer() when installing extension from CLI

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#109515]
Testing #109427

- Install [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) from CLI

`code-insiders --install-extension esbenp.prettier-vscode`

- Get deprecation warning:

```
Installing extensions...
Installing extension 'esbenp.prettier-vscode' v5.7.1...
(node:25996) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'esbenp.prettier-vscode' v5.7.1 was successfully installed.
```

- Launched Insiders, saw Prettier extension was successfully installed despite warning

![image](https://user-images.githubusercontent.com/25310137/97338565-c5c51a80-183e-11eb-9194-5c6b8102da7d.png)

![image](https://user-images.githubusercontent.com/25310137/97338894-22283a00-183f-11eb-8ab4-5b56fd5501ed.png)

- Tried with another extension, got same warning

![image](https://user-images.githubusercontent.com/25310137/97339191-83e8a400-183f-11eb-83eb-eab58b5df38c.png)

Version: 1.51.0-insider (user setup)
Commit: e5c0007ce0e9a3816679cba674d03376c03726e3
Date: 2020-10-27T05:37:14.199Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by bamurtaugh** [comment]
Same warning when install multiple extensions at once:

![image](https://user-images.githubusercontent.com/25310137/97344489-0d02d980-1846-11eb-868f-17561a539685.png)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/82524
