### ISSUE TITLE
Extension global state syncing - syncing objects

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#109543]
Testing #109388

I have an extension with these commands:
```
	context.subscriptions.push(vscode.commands.registerCommand('extension.addRamacfarTest', _ => {
		context.syncedGlobalState.syncedKeys = ['ramacfar-test'];
	}));

	context.subscriptions.push(vscode.commands.registerCommand('extension.setRamacfarTest', async _ => {
		context.syncedGlobalState.update('ramacfar-test', { test: true });
	}));
```

When modifying and syncing this key, the synced data view shows it only as an empty object, instead of as `{ test: true }`:
<img width="604" alt="Screen Shot 2020-10-27 at 3 29 14 PM" src="https://user-images.githubusercontent.com/3672607/97369493-48170400-186a-11eb-99cd-ccf52e370c08.png">

**Comment by sandy081** [comment]
Good catch
