### ISSUE TITLE
Long hang after reloading window with extension view open

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#109516]
Noticed this while testing. 

- Open the extensions view
- Reload window
- When the window is reloading, there is a point when it stops responding for several seconds

Similar to https://github.com/microsoft/vscode/issues/54041?

![image](https://user-images.githubusercontent.com/323878/97339178-80edb380-183f-11eb-9180-ea3efcfbfdc3.png)

[Profile-20201027T103103.json.txt.zip](https://github.com/microsoft/vscode/files/5447004/Profile-20201027T103103.json.txt.zip)

**Comment by sandy081** [comment]
It seems following methods are called repetitively

https://github.com/microsoft/vscode/blob/e8d3a7b8dc7064c4743ef70cb9ef38c5fca558bc/src/vs/workbench/contrib/extensions/browser/extensionsActions.ts#L2986

https://github.com/microsoft/vscode/blob/e8d3a7b8dc7064c4743ef70cb9ef38c5fca558bc/src/vs/workbench/contrib/extensions/browser/extensionsActions.ts#L3044

<img width="599" alt="image" src="https://user-images.githubusercontent.com/10746682/97452531-20d93900-1935-11eb-8813-93195e39e16b.png">

@roblourens Can you please keep a counter in above methods and let me know how many times this method is being called.

Fact is that these actions are secondary actions and not needed to be created as they are not visible.

**Comment by roblourens** [comment]
Can you not reproduce it?

**Comment by roblourens** [comment]
I saw `getExtensionsToEnable` get called 405 times when reloading the window with the extensions view open. Seems like a lot. I have 135 extensions installed 🤭

**Comment by sandy081** [comment]
These actions have listeners to update enablement whenever extensions are changed. Hence these are getting called so many times. And, I do not know why workbench asks for these actions even if they are not required to be shown. 

Since these are secondary actions these listeners are not needed. Fixed by not having these listeners if actions are not primary.
