### ISSUE TITLE
Search in File, Refrence Error after Hibernate

### ISSUE THREAD

**Issue by mtahirishere** [microsoft/vscode#109574]
Issue Type: <b>Bug</b>

Hi,

After Search In Project, We have references to found points on left panel  with files. these reference does not work after you wake up from hibernation and these references start pointing to a random line number rather than the actual line where text is found. I have got this issue multiple time.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.31GB free)|
|Process Argv|--crash-reporter-id 285f6464-03a5-4351-8f40-2dd28f182f1e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
sftp|lix|1.12.9
prettify-json|moh|0.0.3
mssql|ms-|1.9.0
foxpro|new|1.4.10
vscode-jsp|pth|0.0.3
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-pack|vsc|0.10.0
vscode-maven|vsc|0.25.0
ReactSnippets|xab|2.4.0

</details>

**Comment by mtahirishere** [comment]
Reproducing Step:

Search some text in Search Panel(Ctrl+Shift+F) on Left.
you Got Some References to where that Code is. 
Click on those References, they will take you to line number where that search matched.

Hibernate the System.

Wake Up System

Click on those References in left Panel.
They will take you to some other lines Not where the Searched Text is.

I can Make Video if this is not helpful

**Comment by jrieken** [comment]
I video won't help to reproduce but it might illustrate things. With those steps (search, hibernate, resume, click) I cannot reproduce and it also doesn't appear logical that file location change during hibernation

**Comment by mtahirishere** [comment]
> I cannot reproduce and it also doesn't appear logical that file location change during hibernation

Sorry For misunderstanding,  
File doesn't change location. Reference Does

![image](https://user-images.githubusercontent.com/73585089/97431848-cfcd4300-193c-11eb-880a-653e1cd8d6bc.png)
For Example as in the given Picture i got two results, First was pointing to line 1984.

after  Hibernation cycle it will start pointing to some other line like 2565.

I will also post video this weekend.

**Comment by jrieken** [comment]
Forwarding to Rob since this seems to be file search, not reference search

**Comment by roblourens** [comment]
Would appreciate a video. When you open the file, we run the search again and that's the only thing that would cause the lien numbers for those results to change.
