### ISSUE TITLE
dotnet new command  not returning to terminal

### ISSUE THREAD

**Issue by arun-siv** [microsoft/vscode#109587]
when i run dotnet new console from vscode terminal , its stuck for a long time and returns after a delayed time . There is some bug in the dotnet new command when used  in vscode terminal

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
