### ISSUE TITLE
Remember selected language mode for files

### ISSUE THREAD

**Issue by sanen** [microsoft/vscode#109552]
Issue Type: <b>Feature Request</b>

Translated by @jshinonome:

I had a file that is in the format of key-value which should use "Properties" language. When I reopen the file, I have to select "Properties" again in "change Language Mode". I want a feature that I can set default language rather than indicate from filename(.config).

我有一个  .config 文件内部是key-value格式，我想默认这种为properties模式。可惜没有找到。只能每次通过重新选择打开语言来设置。比较繁琐

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

**Comment by jshinonome** [comment]
Translation:
I had a file that is in the format of key-value which should use "Properties" language. When I reopen the file, I have to select "Properties" again in "change Language Mode". I want a feature that I can set default language rather than indicate from filename(.config).

**Comment by bpasero** [comment]
This sounds like an extension provides the language mode and extension can declare the mode for a file extension. I suggest to follow up with the extension.

**Comment by sanen** [comment]
yeah. I agree with you . thanks your reback.







--

Thanks & Best Regards,
Sanen_Zhang（张科华）
微信：Sanen-zhang
腾讯：1418227374
手机：15021879141
邮箱：zhangkehuait@163.com




















At 2020-10-28 18:05:13, "Benjamin Pasero" <notifications@github.com> wrote:

This sounds like an extension provides the language mode and extension can declare the mode for a file extension. I suggest to follow up with the extension.
