### ISSUE TITLE
Link to documentation in diagnostic info

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#109528]
Testing #109420

It would be great if we could point users to documentation on parts where things didn't load correctly so users can further investigate or learn how to do it. Otherwise it can feel similar to the "there was an error" messages without much guidance.

![image](https://user-images.githubusercontent.com/35271042/97353233-03cb3a00-1851-11eb-8c92-7a820d49367e.png)

**Comment by connor4312** [comment]
I'm not sure there's really documentation for this scenario, it's more a very basic concept of "how to load files". However I updated it with some additional context-dependent hints.

Node:

![](https://memes.peet.io/img/20-10-3d3d5052-c9d3-4716-8891-217629f3784f.png)

Browsers:

![](https://memes.peet.io/img/20-10-c96ebf3b-3696-420d-9d33-d09893654345.png)

**Comment by misolori** [comment]
That's perfect, even that bit is much more useful. Thanks!
