### ISSUE TITLE
problem on loop in c programme

### ISSUE THREAD

**Issue by ap1809** [microsoft/vscode#109555]
#include <stdio.h>

int main(){
    int n;
    printf("Enter the value of n\n");
    scanf("%d", &n);

    for(int i=n; i>0; i--){
        printf("%d\n", i);
    }
    return 0;
}

When i run the above code , The loop becomes infinite. I can''t  get my desired result.

**Comment by Spriithy** [comment]
Hi @ap1809 ! This place is not a code help site. Please check out https://stackoverflow.com/ and ask your question there !
