### ISSUE TITLE
Type ahead can leave dimmed characters around if resizing during input

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#109584]
On resize it should probably undo all predictions to be safe as cursor positions can change?

![recording (9)](https://user-images.githubusercontent.com/2193314/97433713-2d30a800-18db-11eb-97b5-740105b7d32e.gif)

Version: 1.51.0-insider (user setup)
Commit: bb16786cff3d231facbdcee90741ac25fcffd3ac
Date: 2020-10-28T05:57:23.779Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by rzhao271** [comment]
Not familiar enough with the terminal keybindings to get the sidebar to hide while holding down the s key in the terminal, if that's what's happening.

**Comment by Tyriar** [comment]
Repro is using the mouse to resize the sidebar/panel while holding s with focus in the terminal
