### ISSUE TITLE
Cmd+P doesn't work when another quick pick is open

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#10957]
- press `cmd+shift+P` and see the command palette
- realise you wanted to open a file and press `cmd+P`
- 🐛 instead of opening the file picker the selection in command palette changes

**Comment by bpasero** [comment]
@jrieken this is due to the following keybinding rule that you can unset:

`{ "key": "cmd+p", "command": "workbench.action.quickOpenNavigateNext", "when": "inQuickOpen" }`

The idea being that you can press Cmd+P repeatedly to jump to the next item in quick open after opening it.

Thinking about it, maybe this keybinding should look for a context "inFileQuickOpen" instead of working so generaly.

**Comment by jrieken** [comment]
often one context key isn't enough 🙏

**Comment by hun1ahpu** [comment]
Would like to work on this one but the solution of allowing it only InFileQuickOpen looks a little bit weird.
For example what will happen to quickOpenNavigatePrevious?
If we block quickOpenNavigatePrevious when InFileQuickOpen looks inconsistent as we are going to allow quickOpenNavigateNext when InFileQuickOpen.
At the same time if we allow quickOpenNavigatePrevious when InFileQuickOpen we will end up with the opposite problem that the when InFileQuickOpen ctrl+shift+p will not open Command Palette.

@bpasero, @jrieken  what do you think?

**Comment by bpasero** [comment]
Better fix is to keep the behaviour but make the keybinding only work when "Find in Files" (Cmd+P) is active. I will make a change next release to add contexts based on which quick open is visible.

**Comment by bpasero** [comment]
Workaround in `keybindings.json`:

```json
{ "key": "cmd+p", "command": "-workbench.action.quickOpenNavigateNext", "when": "inQuickOpen" },
{ "key": "cmd+shift+p", "command": "-workbench.action.quickOpenNavigatePrevious", "when": "inQuickOpen" }
```

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/issues/28462
