### ISSUE TITLE
OutputChannels show up as active editor

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#10956]
* Have code like below and open an output channel. 
* The output channel appears as an editor which is surfacing an implementation detail and not the intent

```
    vscode.window.onDidChangeActiveTextEditor(editor => { 
        if (editor) {
            console.log(editor.document.uri.toString());
        }
    });
```

**Comment by jrieken** [comment]
@alexandrudima @isidorn fyi

**Comment by alexandrudima** [comment]
We just changed today that the debug repl is a text editor available to extensions

**Comment by alexandrudima** [comment]
The thought process is: if you use & like vim for example, why not type in the debug repl in vim mode too...

**Comment by jrieken** [comment]
Would make it less work... It might just be a little surprising for folks working with the active editor?

**Comment by jrieken** [comment]
we won't change this behaviour
