### ISSUE TITLE
Web download: downloaded file has different new line delimiter

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#109506]
Testing #109284

Edge/Linux

- Open the web playground on `microsoft/vscode`
- Download `resources/win32/bin`
- Check out `code.cmd`. The downloaded version uses `\n` as line delimiter.
- Compare with  `code.cmd` from a locally cloned vscode repo: `\r\n` is used.

**Comment by bpasero** [comment]
@aeschli I would think that git maybe does this conversion based on your git config? Can you download the file from the GitHub repo and compare?

**Comment by aeschli** [comment]
We have a `.gitattribute` file in the root of vscode that says `*.cmd eol=crlf`.
The bug is that the github fs provider is not following that. That can also be seen in the status bar when opening `code.cmd` in the web UI.

**Comment by aeschli** [comment]
Created https://github.com/microsoft/vscode-github-browser/issues/27
