### ISSUE TITLE
Ability to select which nodes to autoexpand on follow in Code Outline

### ISSUE THREAD

**Issue by regs01** [microsoft/vscode#109545]
There is an option outline.showVariables" which allows to hide variables. But what if not to hide, but just not to follow variables. I.e. do not expand Functions and Methods.

There was an extension before and it had an option "symbolOutline.expandNodes".
https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline

So you could select which nodes to auto expand. By default variables were out of list.
```
  "symbolOutline.expandNodes": [
    "Module",
    "Class",
    "Interface",
    "Namespace",
    "Object",
    "Package",
    "Struct"
  ],
```

So, something like this.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Afeature-request+label%3Aoutline
