### ISSUE TITLE
Markdown Notebook breaks interactive playground

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109595]
* install `ms-vscode.vscode-markdown-notebook`
* make markdown notebook default editor for md-files
* F1 > Interactive Playground
* 💥 you see an error but no playground

```
Unable to open 'Interactive Playground': No file system provider found for resource 'walkThrough:/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/contrib/welcome/walkThrough/browser/editor/vs_code_editor_walkthrough.md?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2FwalkThrough%2Fbrowser%2Feditor%2Fvs_code_editor_walkthrough%22%7D'.
```

**Comment by jrieken** [comment]
So, this happens

* the markdown-notebook is the default editor for md-files
* the input for the playground uses an uri with `md` in its path, e.g `vs_code_editor_walkthrough.md`
* in consequence the notebook editor redirects the open request to the extension
* the extension tries to read the uri as file which fails

These should not happen but I am unsure where problems start... Should the workbench never allow to overwrite certain input-types? Should notebooks hardcode the walk-through schemes? Should the playground use a "random" uri that doesn't get accidentally interpreted as language X? 🤷 

<img width="1173" alt="Screenshot 2020-10-28 at 14 41 53" src="https://user-images.githubusercontent.com/1794099/97443934-e323e280-192b-11eb-9767-0ad1c9167ba2.png">

**Comment by mjbvz** [comment]
For custom editors, we have the capability to only enable a custom editor for specific file schemes (or potentially disable it for a specific file scheme). This is not exposed to extensions at the moment.

One thought is that we could try to make the playground another editor override and give it priority over any other registered overrides (such as those for notebooks or custom editors)

**Comment by jrieken** [comment]
I was thinking to add a flag to editor inputs that says "I cannot be replaced". The `WalkThroughInput` input would set this (and I guess also others) and the workbench would simply not invoke the overwrite logic then

**Comment by JacksonKearl** [comment]
Makes sense to me. We've seen issues like this in the past with extension editors being overridden.

**Comment by jrieken** [comment]
Turns out that there is the `override` option which allows to opt-out of editor override when open an input. I think that should be enough for the interactive playground and others
