### ISSUE TITLE
Intellisense not working in django 

### ISSUE THREAD

**Issue by naman4662** [microsoft/vscode#109559]
Issue Type: <b>Bug</b>

It gets stuck at loading stage 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (13.67GB free)|
|Process Argv|--crash-reporter-id fd7c125c-811a-4bcc-95eb-b2ac7bda1744|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.2
python|ms-|2020.9.114305
remote-wsl|ms-|0.50.1
django-intellisense|sha|0.0.2

</details>

**Comment by aeschli** [comment]
Please file it against the extension that provides the intellisense: https://gitlab.com/shamanu4/django-intellisense/-/issues

Don't forget to add a small sample code to reproduce the problem.
