### ISSUE TITLE
Terminal typeahead produces wrong color when latency is high

### ISSUE THREAD

**Issue by dtinth** [microsoft/vscode#109562]
Version: 1.51.0-insider
Commit: 16f4a29aa0ac05d3cba222b1f347b7404626c680
Date: 2020-10-26T05:37:52.074Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

VS Code version: Code - Insiders 1.51.0-insider (e5c0007ce0e9a3816679cba674d03376c03726e3, 2020-10-27T05:32:19.703Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.0-1028-aws

Steps to Reproduce:

1. SSH into a server in other side of the world to replicate the network condition. (e.g. fly to Thailand and SSH into a server in the US)
2. Use [Oh My Fish](https://github.com/oh-my-fish/oh-my-fish) in the Terminal.
3. Type some command, such as `git pull origin master`.
4. Note how some characters get the wrong color (in image below, the letter `g` in `origin` gets wrong color).

![20201028T062052862Z](https://user-images.githubusercontent.com/193136/97400228-52e0a000-1921-11eb-9bcd-fc595efb0c63.gif)

I confirm that I can replicate this on:

- Vanilla VS Code Insiders with `ssh` command.
- VS Code Insiders over Remote - SSH
- GitHub Codespaces

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Thanks for the issue, we're working on improving behavior in https://github.com/microsoft/vscode-internalbacklog/issues/1551

/duplicate
