### ISSUE TITLE
Debugging variable popup misbehaves when expanding if it is near the top of the screen.

### ISSUE THREAD

**Issue by HubKing** [microsoft/vscode#109547]
When the debugging variable popup is near the top of the screen, expanding the first item moves the popup to a new location. At this point, it is impossible to expand the second entry, because it gets closed when trying to do so. I think this screen recording explains all.

![28-October](https://user-images.githubusercontent.com/10900489/97376626-32085280-1901-11eb-9d6b-383e9570e48e.gif)

- VSCode Version: 1.50.1
- OS Version: Windows 10 (2019 Fall)

Steps to Reproduce:
1. Use the following code.

```
        static void Main(string[] args)
        {
            var l = new Dictionary<int, string>();
            for(var i=0; i<10; i++)
            {
                l.Add(i, $"Value of {i}");
            }
            var a = l.Count;
        }
```

2. Scroll down the code a little bit so that ` static void Main(string[] args)` will the first visible line.
3. Break and the dictionary and place the mouse over `l`.
4. Try to expand the first entry in the variable popup.

Does this issue occur when all extensions are disabled?: No, but that is because without the C# extension, debugging will not work. I posted this issue to [the C# extension project](https://github.com/OmniSharp/omnisharp-vscode/issues/4157) first, but they said it looked like a VS Code's issue.

**Comment by isidorn** [comment]
This is fixed in latest insiders and dup of https://github.com/microsoft/vscode/issues/109226
