### ISSUE TITLE
Type ahead: don't predict when the first character on the line is :

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#109541]
Some programs like `git log`/`less` use the normal buffer, we should prevent predictions for this case where the line is not wrapped, starts with `: ` and the cursor is on the second column (1 based).
![recording (8)](https://user-images.githubusercontent.com/2193314/97368658-a3e08d80-1868-11eb-9e4b-94e2467a85e2.gif)

**Comment by rzhao271** [comment]
Not sure what the expected output is here.
If I run git log, and then try typing or holding down `a`, nothing happens.
I have local echo set to 0

**Comment by connor4312** [comment]
That's expected -- you should not get predictions in git log
