### ISSUE TITLE
The drive or UNC share you selected does not exist or is not accessible. Please select another.

### ISSUE THREAD

**Issue by shalevv123** [microsoft/vscode#109518]
- VSCode Version: 1.50.1
- OS Version: 1909

Steps to Reproduce:
![vscode bug](https://user-images.githubusercontent.com/73291739/97340717-cdabab80-188c-11eb-9d73-25eb28e4f8e1.png)

1. install vscode on a drive
2. remove the drive from your PC
3. try to install vscode on a new drive

Does this issue occur when all extensions are disabled?: Yes

i keep on getting this error message when trying to install vscode on my new drive, please help i really need it for school

**Comment by joaomoreno** [comment]
Yeah our Setup program doesn't deal with this very well. I suggest you uninstall VS Code altogether and reinstall it on the new drive.

**Comment by shalevv123** [comment]
i cant uninstall vscode becaus i threw away the old drive

**Comment by joaomoreno** [comment]
What happens if you go to the Control Panel, and choose to uninstall VS Code? Can you show me that error?

**Comment by shalevv123** [comment]
i cant even uninstall it, i dont even have the program, it was installed on my old E drive, it is now in the garbage, and i have a D drive, 
![errorcode](https://user-images.githubusercontent.com/73291739/97442502-98f22f80-1932-11eb-94ca-81f9c9a86d1a.png)

**Comment by joaomoreno** [comment]
You can manually remove Code from the Control Panel by deleting the following entire registry key:

```
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1
```

**Comment by shalevv123** [comment]
where do i find that registry key? i wrote the line on the file explorer but i cant seem to find it 
im not that good with windows and operating systems

**Comment by shalevv123** [comment]
i think i found it but it doesnt apear to be anything called 771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1
![Uploading uninstall.png…]()

**Comment by shalevv123** [comment]
i think i found it but it doesnt apear to be anything called 771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1
![uninstall](https://user-images.githubusercontent.com/73291739/97449942-de1a5f80-193a-11eb-827a-f52d787b0419.png)

**Comment by joaomoreno** [comment]
How about `{D628A17A-9713-46BF-8D57-E671B46A741E}_is1`?

**Comment by shalevv123** [comment]
sadly no

**Comment by joaomoreno** [comment]
Can you run a Search over that top `Uninstall` key, look for `Visual Studio Code`

**Comment by shalevv123** [comment]
i cant find any of them, they both dont lead to anywhere

**Comment by shalevv123** [comment]
if i knew it would do it like thati would have uninstalled vscode before i threw the drive, i dont know why this is happening

**Comment by joaomoreno** [comment]
OK then just do a full search for `Visual Studio Code` or `VS Code` in your entire registry, you'll soon find the key.

**Comment by shalevv123** [comment]
ive searched threw the entire registry and i couldnt find visual studio code anywhere

**Comment by jorgeguberte** [comment]
> You can manually remove Code from the Control Panel by deleting the following entire registry key:
> 
> ```
> Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1
> ```

My vscode was installed on a drive that died. Deleting that registry entry worked for me. Thank you!

**Comment by fredriksvahn** [comment]
> You can manually remove Code from the Control Panel by deleting the following entire registry key:
> 
> ```
> Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1
> ```

Just had this problem, your solution did the trick. Thanks!
