### ISSUE TITLE
No syntax highlight at some points in js files

### ISSUE THREAD

**Issue by Orodan** [Microsoft/vscode#10950]
- VSCode Version: 1.4.0
- OS Version: OS X Yosemite 10.10.5

Hi,

using VSCode to write some javascript, sometimes it ends up with no syntax highlight at some points in the file.

Here is an example of what I'm talking about :

<img width="842" alt="capture d ecran 2016-08-25 a 14 15 05" src="https://cloud.githubusercontent.com/assets/7422824/17968669/5c307636-6ace-11e6-8c4e-a013b64f1570.png">

The code is correctly formated and functional, and it actually have a correct highlight on other editors like atom for example). I'm using the dark+ theme and I've already tried to install some other themes and adding highlight snippets to see if they made a difference but the problem was still here.

Hope you can help

**Comment by devlo** [comment]
I have the same problem after updating from version 1.0 to 1.4. All worked without problems in 1.0.

**Comment by dooso** [comment]
I have the same problem in my typescript files.. and i found it just occur in 1.4 , and now  i use back to v1.3.

**Comment by sandy081** [comment]
Duplicates #9937
