### ISSUE TITLE
Run custom command in editor.codeActionsOnSave

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode#109500]
So, I could do something like:

```json
"[shellscript]": {
    "editor.defaultFormatter": "foxundermoon.shell-format",
    "editor.codeActionsOnSave": {
      "command": "argbash -i ${relativeFile}"
    }
  },
```

PS: I'm talking about a shell command, not a VSCode command.

I can think of 3 approaches:

1. Support calling VSCode commands (so we can call a task)
2. Support calling tasks (so we can set a task which run that command)
3. Support calling commands

I think the first is the best one since it would extend to many possibilities.

**Comment by mjbvz** [comment]
This like a good candidate for an extension that converts tasks/commands into source actions.

If that proves popular, we could look into integrating it into VS Code

**Comment by felipecrs** [comment]
@mjbvz I was able to successfully create an extension that converts a task to a source Code Action, and I was able to make it run with codeActionsOnSave. However, there is an issue:

The formatOnSave runs before the task finishes, I believe that's because the source action calls the task through `workbench.action.tasks.runTask` and therefore, it does not wait for its execution before moving ahead.

Is there a way to run a task through `workbench.action.tasks.runTask` and wait for its execution to finish?

**Comment by felipecrs** [comment]
I was able to successfully create an extension to transform tasks into source code actions, and therefore be able to use them in `codeActionsOnSave`.

However, there is a challenge:

The command which the task runs changes the document contents, therefore it triggers a VS Code error:

![dhBDM1eRSZ](https://user-images.githubusercontent.com/29582865/98747718-d923ca00-2396-11eb-8497-f35b17d22bb4.gif)

Is there a way to work around this?

**Comment by mjbvz** [comment]
Looks like your task writes to disk before the file is written. Try delaying your task until the save has completed

**Comment by felipecrs** [comment]
But in fact, I need the formatter (`formatOnSave`) to actually run after the task. =/
