### ISSUE TITLE
Searching icon stuck

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#109554]
- VSCode Version: 1.50.1
- OS Version: Windows 10

Steps to Reproduce:

1. Global Search
2. Finish Search
3. Searching icon never disappears

It's  not reproducible every time, but it did happen quite frequently.
![image](https://user-images.githubusercontent.com/28700378/97386083-08a1f380-190e-11eb-8d21-3d3ab615b5c4.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/109371#issuecomment-721871660 would appreciate the same details I'm asking for in that issue
