### ISSUE TITLE
Webviews prevent close confirmation dialog from appearing

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#109521]
Testing #109283

In a codespace, open a markdown preview or gitlens welcome editor or some sort of webview. Press Cmd+W. Tab closes without warning.

**Comment by mjbvz** [comment]
This sounds like #82592

We definitely need some browser help here for the keyboard event dispatch but maybe we could try adding `onBeforeUnload` handler in the webview itself to prevent this?

**Comment by bpasero** [comment]
@mjbvz I somewhat doubt that a `iframe` can prevent the outer document from unloading, but have not tested it. Ideally our [`ModifierKeyEmitter`](https://github.com/microsoft/vscode/blob/1a130d2c17a42161b9437a0d5c7ed3ac2cdc1968/src/vs/base/browser/dom.ts#L1427-L1427) that I am using would detect keybindings pressed even when focus is inside the `iframe`. I am not sure how to achieve thats, so assigning you as well for suggestions.

**Comment by mjbvz** [comment]
I confirmed that we can use `beforeunload` inside iframes (although I need to fully confirm that this works for cross origin iframes. I've only tested this using VS Code run on localhost and iframes hosted on 127.0.0.1):

```ts
window.addEventListener('beforeunload', () => false);
```

The main limitation is that this code must be synchronous. The webview cannot call back to VS Code to check if it should veto the unload or not. 

@bpasero Do you recommend that webviews listen to keypresses to prevent `cmd+w`?

**Comment by bpasero** [comment]
I would probably prefer a solution where `webview` would not trap keybindings (https://github.com/microsoft/vscode/issues/82592 ?) and let them bubble to my handler.

**Comment by mjbvz** [comment]
Unfortunately it's the iframe itself that traps these keypresses. We need to handle this inside the webview

**Comment by mjbvz** [comment]
I pushed a change that seems to prevent window closing when focused in a basic webview. Give it a try and let me know if you notice any issues  (it doesn't seem to work in Firefox in my testing)

**Comment by bpasero** [comment]
I was not able to get a confirmation dialog in Chrome at least. I opened a markdown preview, but maybe this needs an insider build?

Btw I would expect this to be looking at the `window.confirmBeforeClose` setting from the user if possible.

**Comment by mjbvz** [comment]
Yes since this touches the JavaScript hosted inside the webview, you'll need to wait until that is pushed to our CDN with the next insiders (I run a server that hosts this code locally for testing purposes) 

Good point about `window.confirmBeforeClose`. I'll synchronize that setting over to the webview so that we can observe it
