### ISSUE TITLE
"W" key not working

### ISSUE THREAD

**Issue by JeremyJason** [microsoft/vscode#109575]
Issue Type: <b>Bug</b>

I cannot type "W" into the editor . I don't know what the issue is , please can you help me out ?

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.81GB free)|
|Process Argv|--crash-reporter-id cb0e71d4-0b5c-4c64-b074-f88db70af300|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexdima** [comment]
@JeremyJason Please go to your `keybindings.json` file (`F1 > Preferences: Open Keyboard Shortcuts (JSON)`) and remove the entry which uses `"key": "w"` or simply comment out everything.
