### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by click44** [microsoft/vscode#109514]
Issue Type: <b>Bug</b>

Every time I launch vscode I get "The TypeScript language service died 5 times right after it got started. The service will not be restarted."

Everything worked fine yesterday. I don't think vscode or typescript has updated in the last couple of days. I've restared vscode multiple times and I restarted my computer. 

Any help here would be appreciated. vscode is really helpful if I don't get the typescript features. 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id ad666562-6867-40ec-bc92-9441dad4da7b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.15.1
vscode-install-vsix|fab|1.4.0
beautify|Hoo|1.5.0
vscode-typescript-next|ms-|4.1.20201026
vscode-typescript-tslint-plugin|ms-|1.2.3
angular-console|nrw|14.0.1

</details>

**Comment by click44** [comment]
It appears to be the tslint extension causing the issue. TypeScript language service seems to start fine when that is disabled.

**Comment by click44** [comment]
<img width="1058" alt="Screen Shot 2020-10-27 at 11 39 28 AM" src="https://user-images.githubusercontent.com/7707029/97340484-7506ef00-1849-11eb-8eb3-9c61dedd8ec0.png">

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
