### ISSUE TITLE
Should diagnostics page match the vs code branding?

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#109529]
Testing #109420

Wondering if the overall page design should match our VS Code branding, similar to our website? Otherwise it could feel like this is from a third party extension and can create confusion.

![image](https://user-images.githubusercontent.com/35271042/97353687-9370e880-1851-11eb-8fc5-4ed0ece735bc.png)

**Comment by connor4312** [comment]
We now show in a webview panel and use the user's VS Code theme, e.g.

![](https://memes.peet.io/img/20-10-9df65757-85e7-46c1-994d-80e32a98c882.png)
