### ISSUE TITLE
.deb package 1.50.1 cannot install from unsigned repo

### ISSUE THREAD

**Issue by TheDiveO** [microsoft/vscode#109567]
- VSCode Version: 1.50.1-1602600906
- OS Version: Ubuntu 20.04.01 LTS

Steps to Reproduce:

1. download .deb package from https://code.visualstudio.com/docs/?dv=linux64_deb
2. try to install
3. error message: cannot install from unsigned repo

Does this issue occur when all extensions are disabled?: (Yes) N/A

**Comment by Tyriar** [comment]
If you downloaded the deb package from the website, you're not installed from a repo at all. Instructions to install the deb file as well as hooking up the actual repo are available at https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions

**Comment by TheDiveO** [comment]
Sorry, but you are mincing words; I wrote that when trying to install the downloaded .deb file, an error message appears which reads "cannot install from unsigned repo". Before 1.50.1 I installed on several machines on a regular basis using the method of downloading the .deb and then installing it (e.g. via the discover wrapper on Kubuntu systems). So something clearly has changed, if you would benso kind as to acknowledge.

**Comment by Tyriar** [comment]
Thanks for teaching me a new word I guess, but I read what you said and responded _trying to help_ with a very reasonable answer given what you wrote, you didn't even tell me how you're installing it or where the error came from.

If you're just installing a package via `dpkg` as mentioned in the page I linked, no repo signed or unsigned is involved on our end. If you're downloading from the website as you say, it's an unsigned deb _package_ as is the norm with deb packages. Perhaps you're being solipsistic and Discover is somehow using a repo? Regardless, you still haven't given me enough info to help much, just got angry at me for some reason.

**Comment by TheDiveO** [comment]
Glad that you're learning at least sometimes a new word, it opens the mind. I've given you exactly the information that is available to me, if you need more, ask specifically for **what** you need, not that you want more. I already told you that I'm installing the downloaded package via Kubuntu's discover UI ... if you please to read your own documentation you link to, then UI installation tools are specifically mentioned, as is installation of downloaded debs at the very beginning. Also, if you please to actually digest then you would notice that I also wrote that before there never was a signing issue reported. So something has changed, if not for the package itself, then another source could be a change in dpkg. However, I'm not aware of such changes, afaik.

**Comment by TheDiveO** [comment]
I'm working with testers, support personnel and devs all the time. Their professional stance is not to deny my bugs with it cannot be but instead like, oh, I don't yet understand why you are getting this weird error message, it shouldn't be involveld at all. Let's drill down, please can you tell be A, B, ... I would have expected the same quality here, but then something learned for this project.

**Comment by Tyriar** [comment]
What is clear to me is that nothing on our end is to blame, **no signing was ever used or was ever required to install the deb package**. The problem is you your end and unfortunately you will need to figure it out.

Note also that I'm not support, I'm an engineer on the team who has been out for a month and I'm trying to get through 450 other notifications in a reasonable speed so that I can actually get back to improving the product. I may sound terse and close issues when you may think I should not, but that's only because I must do this efficiently. I also went and tested our package installation despite my better judgement and it worked just fine, the problem is on your end.

**Comment by eddieferrer** [comment]
@TheDiveO I was seeing the same issue when opening the .deb file with KDE Discover. The package updates fine when using the terminal instead of the Discover UI via the command `sudo apt install ./code_1.50.1-1602600906_amd64.deb`
