### ISSUE TITLE
VSCode does not remember last launched configuration after Reload window

### ISSUE THREAD

**Issue by dslijepcevic** [microsoft/vscode#109568]
Issue Type: <b>Bug</b>

It seems that after Reload window VSCode sets the active launch configuration to the first one available in `launch.json` instead of restoring the last one that was used.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by dslijepcevic** [comment]
@isidorn Yes, I can reproduce it with 1.51.0-insider, however, it seems to happen only within a Docker container or WSL and works properly with a local project.

**Comment by isidorn** [comment]
Do you have a launch confiugration in your workspace `launch.json` or in your user settings file?

**Comment by dslijepcevic** [comment]
I tried only with `.vscode/launch.json`.
