### ISSUE TITLE
Shortcut to highlight lines are inconsistent on macOS

### ISSUE THREAD

**Issue by u84six** [microsoft/vscode#109533]
- VSCode Version: Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
- OS Version: 10.15.7

Steps to Reproduce:

1. Place cursor on line with text before the first character and ensure there's next on line above
2. Hold shift and hit the up arrow key
Bug: it doesn't highlight the current line. It skips the current line and highlights the line above it.
Fix: Highlight the current line and then go to the line above.

This action is inconsistent with holding shift and hitting the down arrow. When you place the cursor on the line and hit the down arrow, it selects the current line and then goes to the next line. This is how I think It should work going up. The only way to make this work is if you put the cursor at the end of the line, it will select the current line when you hit the up arrow. But this way is so inconsistent and doesn't select the text the right way. It should really just select the whole line no matter which direction you're going (up or down). I just want to put the cursor before the first character of a line and be able to select each line as I go up or down (like most older text editors).

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment]
Can you list some other programs work the way you proposed?

Holding <kbd>Shift</kbd> and pressing arrow keys always select between "where the cursor was when shift key was first pressed" and "the latest cursor position", which is consistent with holding <kbd>Shift</kbd> and moving cursor with mouse.

**Comment by alexdima** [comment]
AFAIK our behavior is consistent with other code editors.
