### ISSUE TITLE
terminal.integrated.typeaheadStyle could have more friendly values

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#109590]
Some of the possible values right now aren't useful imo like invert, bold, maybe italic too as the predictions will end up looking quite different to what will replace it. I suggest we change it to: 'normal' | 'dim' | 'underline' and colors. This also hides internal details like the style codes from the user.

**Comment by Tyriar** [comment]
@connor4312 do you think it's worth keeping bold and inverted in there too? They look pretty clunky and probably won't ever see use?

**Comment by connor4312** [comment]
I could imagine vision impaired users may prefer the visible inverted style over the more subtle dim/underline options. Making them available is cheap enough imo.
