### ISSUE TITLE
Untitled file with whitespace causes placeholder title to shrink

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#109525]
Issue Type: <b>Bug</b>

Found while testing https://github.com/microsoft/vscode/issues/107979

1. Open an untitled editor and paste 
`error      13:47:38.285446-0500      cfprefsd      rejecting write of key(s) kFMFDStoredDataKey`

 into it, the tab title reads "error 13:47:38.285446-0500 cf"
2. Place cursor after "error" and enter a bunch of spaces. The tab title shrinks, with enough spaces, eventually just becoming "error"

I expected the tab title to be stable as whitespace was added

VS Code version: Code - Insiders 1.51.0-insider (e5c0007ce0e9a3816679cba674d03376c03726e3, 2020-10-27T05:32:19.703Z)
OS version: Darwin x64 18.7.0

**Comment by bpasero** [comment]
I will not fix this for any line length, but have changed our logic to consider the first 400 characters for the title that has a maximum of 40 chars.
