### ISSUE TITLE
Possible concern if user installs alpha version of extension

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#109536]
Testing #109388

For those who might sideload an extension version alpha, if the alpha version syncs state but is then uninstalled, all clients will no longer be able to sync unless I misunderstand the logic for version conflicts.

**Comment by sandy081** [comment]
Good point.

When extension is uninstalled, then it is removed in the cloud. So it gets uninstalled in all other clients. If it is installed again then it gets synced in all other clients. 

If alpha/beta version of an extension is installed on a client then state is not synced in all other clients as they might have older versions which is expected. If the extension gets downgraded to the normal version then state gets synced across as now all clients are on same version.

**Comment by sbatten** [comment]
> If the extension gets downgraded to the normal version then state gets synced across as now all clients are on same version.

How does this work exactly? For my own understanding

**Comment by sandy081** [comment]
>  I install and alpha version on a single device. Now syncing does not work because the alpha version has the highest version and its the only one

Yes, if you have higher version on just one system, state is not synced everywhere. 

>  I decide I want to go back to stable after some testing so I uninstall the extension and reinstall from the marketplace. 

After you reinstall the extension from Marketplace, all clients will have same extension version and state gets synced everywhere.

> This flow will probably delete all my state, yes and the other devices will not recover it because remote wins?

I do not think sync will delete the state on other machines. If a machine has older version of extension, state will not be synced (it does not delete the state). When you install the stable version on the machine where you had alpha version, it will push the current state (remember locally the machine has state from previous extension) to the cloud and all other clients sync it.

Sorry if I am not clear, but happy to chat and explain it directly.
