### ISSUE TITLE
Syntax coloring issue with flow polymorphic types

### ISSUE THREAD

**Issue by minedeljkovic** [Microsoft/vscode#10958]
- VSCode Version: 1.4.0
- OS Version:  Ubuntu 14.04 LTS

Steps to Reproduce:

1. Create .js file with [flow](https://flowtype.org/) type not using polymorphic types (coloring is ok)
2. Introduce polymorphic type (coloring is broken below the line where polymorphic type is used)

![vscode-flow-coloring](https://cloud.githubusercontent.com/assets/1811622/17973615/6d2b9082-6ae3-11e6-8e28-9a2d10c451eb.png)

**Comment by sandy081** [comment]
This issue was moved to flowtype/flow-for-vscode#29
