### ISSUE TITLE
Add ability to change fs provider capabilities dynamically

### ISSUE THREAD

**Issue by setaskin** [microsoft/vscode#109527]
Currently when editor is open we cannot change the state of it. ( read only to read write vice versa ).  Live Share extension has a way to change the access level of current user in session. However the access level change doesn’t take effect on open editors immediately. If host gives accidental read-write access to a guest, there is no way to revert this access immediately for open editors. So we need a new api to toggling editor read-only state globally.

**Comment by alexdima** [comment]
@setaskin I'm not entirely aware of this. What API are you currently using to make the editors read-only?

**Comment by daytonellwanger** [comment]
@alexdima we register a read-only file system provider, and when we want to switch it to read-write, we unregister the read-only provider and register an equivalent read-write provider (vice versa for the reverse direction). However, any open editors don't reflect the change (which probably makes sense - the resources are technically different; I'm guessing VS Code doesn't know that we're registering an equivalent file system provider but for the read-onlyness). I think we may need a new API for updating the read-onlyness of the file system provider without unregistering the old one and registering a new one.

**Comment by alexdima** [comment]
@jrieken I think the API request here is to be able to change the `isReadonly` option for a file system provider and that open files should reflect this.

**Comment by jrieken** [comment]
I do think it is fishy that editor don't update/change when the filesystem provider goes (and returns). Adding @bpasero what the semantics are supposed to be. I think unregistering a file system provider is similar to cases where files are deleted on disk, when a new provider for the same scheme return the editor should probably update. 

For readonly-ness we also have https://github.com/microsoft/vscode/issues/73122 which is about readonly-ness on the level of a file

**Comment by bpasero** [comment]
Extracted https://github.com/microsoft/vscode/issues/110854 for me. The reminder seems to be an API request to do this without disposing the registration.

**Comment by bpasero** [comment]
Pushed a change to update an editor's readonlyness whenever file providers either change capabilities or dispose and come back with different capabilities. This impacts both normal editors and diff editors:

![recording](https://user-images.githubusercontent.com/900690/99645727-db99ba00-2a4f-11eb-807d-962e58bd6f81.gif)

A consequence is that even when the file is dirty you cannot type in it anymore (as you can see from the recording).

**Comment by daytonellwanger** [comment]
Thanks @bpasero ! Working now!

**Comment by jrieken** [comment]
Alright, closing this issue now as the current API shape doesn't easily allow for changing capabilities
