### ISSUE TITLE
Creating a new tsx file that uses decorators always gives an error in VSCode

### ISSUE THREAD

**Issue by ptallett** [microsoft/vscode#109599]
- VSCode Version: 1.50.1
- OS Version: Windows 10 1903 (18362.1139)

Steps to Reproduce:

1. Enable experimental decorators in your tsconfig
2. Restart VSCode
3. Note that any existing classes using decorators show no errors
4. Create a new class file that uses decorators

Expected result
    No errors

Actual result
   Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.ts(1219)

Restarting VSCode cures the issue
Note this is especially annoying using mobx with React as nearly every class has decorators

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Can you share an example project that demonstrates this issue

**Comment by RobinGiel** [comment]
Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.ts.

I'm having the same warning after the update, relaunched vs code a few times but still getting the same errors everywhere in my project. The experimentalDecorators is set to true

**Comment by ptallett** [comment]
This doesn't seem to repro with all the latest stuff. Sorry for bothering you.
