### ISSUE TITLE
terminal.integrated.typeaheadThreshold naming

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#109585]
Type ahead was always just a quick codename/internal name for the feature. I think we should name this `terminal.integrated.latencyMitigationThreshold`.

**Comment by connor4312** [comment]
`latencyMitigationStyle` or `latencyMitigationCharacterStyle` reads awkwardly to me. "Latency mitigation" sounds like a process, where something like "typeahead" sounds like concrete feature. Maybe keep the typeahead name and change the setting to `typeaheadLatencyThreshold`?

**Comment by Tyriar** [comment]
Actually local echo is the typical name for this features like this, how about that? `localEchoLatencyThreshold`? Would make it more discoverable as it's a somewhat common term.
