### ISSUE TITLE
new function 

### ISSUE THREAD

**Issue by chanmaoooo** [microsoft/vscode#109510]
The 'deleteWordLeft' command cannot delete letters on right side of the cursor. We want new function which can delete the whole word. 

(We submit this issue formally. Sorry.)

**Comment by alexdima** [comment]
To verify, please look for a "Delete Word" action that you can bind to a keybinding if you wish to. The action will delete the current word under the cursor (both to the left and to the right of the cursor) and will delete any trailing whitespace.

**Comment by chanmaoooo** [comment]
I've checked. I could find the "Delete Word" action and bind a keybinding to it. The function works properly. Thank you!
