### ISSUE TITLE
Run option

### ISSUE THREAD

**Issue by chiru-20** [microsoft/vscode#109522]
Issue Type: <b>Bug</b>

Hi there. first when clicked on the run option at top-right corner it wolud run the code in terminal. now when I click it .. it runs the code in "output" window and not terminal ..
So how do I do the same..??

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (10.67GB free)|
|Process Argv|--crash-reporter-id 3ccbd510-3dc5-4712-9b1d-00cb54157377|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
All-Autocomplete|Ati|0.0.23
macros|ctf|0.0.4
gitlens|eam|10.2.2
code-runner|for|0.11.1
shell-format|fox|7.0.1
gc-excelviewer|Gra|3.0.40
todo-tree|Gru|0.0.186
vscode-settings-cycler|hoo|1.0.1
customize-ui|ioc|0.1.49
monkey-patch|ioc|0.1.11
vscode-text-pastry|jkj|1.2.0
chat|kar|0.35.0
vsls-whiteboard|los|0.0.11
git-graph|mhu|1.26.0
python|ms-|2020.9.114305
powershell|ms-|2020.6.0
sublime-keybindings|ms-|4.0.7
gremlins|nho|0.25.0
env-cmd-file-syntax|Nix|0.2.2
autodocstring|njp|0.5.3
explorer-exclude-vscode-extension|Red|1.2.0
code-settings-sync|Sha|3.4.3
rewrap|stk|1.13.0
vscode-icons|vsc|11.0.0

</details>

**Comment by weinand** [comment]
Your description is not actionable.
What debugger are you using?
What do you mean by "the run option at top-right corner"?
Please provide reproducible steps and screenshots.
