### ISSUE TITLE
Home button closes without warning

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#109520]
Testing #109283 on playground.

When using `"window.confirmBeforeClose": "always"`, clicking the home button 
![image](https://user-images.githubusercontent.com/8586769/97345985-0bd2ac00-1848-11eb-8e1a-6b9bf49e1718.png)
will exit without warning. This is potentially unexpected as it's not clear that "home" in a CS means go back to github and lose all your state.

**Comment by bpasero** [comment]
I am not able to reproduce, tried today. In the console I see this `log.ts:191  WARN Unload veto: window.confirmBeforeClose=always`

Can you try again? What OS/Browser is this?

**Comment by JacksonKearl** [comment]
Unable to test rn due to https://github.com/microsoft/vscode-internalbacklog/issues/1581

**Comment by bpasero** [comment]
@JacksonKearl you can always open the settings editor as file to change settings, no?

Second icon in editor toolbar:

![image](https://user-images.githubusercontent.com/900690/97453596-2f742000-1936-11eb-898a-d04e0b85ba63.png)

**Comment by JacksonKearl** [comment]
No :( button throws the same error, command pallete entry throws a new one. 
![image](https://user-images.githubusercontent.com/8586769/97453768-49404380-18f3-11eb-9f28-ccdc82154e05.png)

**Comment by bpasero** [comment]
Ok strange, my Codespace seems fine, maybe try with a new one?

**Comment by JacksonKearl** [comment]
Nope, brand new codespace has the same errors. I cant open any files either.

**Comment by JacksonKearl** [comment]
Filed https://github.com/github/codespaces/issues/1637
