### ISSUE TITLE
Upgrade to 1.46.1

### ISSUE THREAD

**Issue by reuvygroovy** [microsoft/vscode#109558]
- VSCode Version: 1.50.1
- OS Version: Windows 10

Steps to Reproduce:
I lately find myself either:

(a) unable to open VSCode
![image](https://user-images.githubusercontent.com/1325158/97396007-df259f80-18ee-11eb-9e41-996b35949570.png)

I see in Task Manager there are a bunch of Code.exe processes open:
![image](https://user-images.githubusercontent.com/1325158/97396051-f6fd2380-18ee-11eb-96dd-37168ba113b0.png)

And also a bunch of installer files running:
![image](https://user-images.githubusercontent.com/1325158/97395992-d634ce00-18ee-11eb-9b3c-d306f89e0290.png)

(b) Sometimes VSCode opens without the Folder View, and when I open Help -> Check for updates it seems like there is an update, but when I go to the site to manually download it I am using the latest version.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by joaomoreno** [comment]
Can you completely remove VS Code and reinstall it?

**Comment by reuvygroovy** [comment]
I will try and let you know

**Comment by joaomoreno** [comment]
OK let me know.

**Comment by reuvygroovy** [comment]
Didn't help. Arrived this morning and again:
![image](https://user-images.githubusercontent.com/1325158/97795993-c16d7880-1c15-11eb-8659-0b3d6ca16508.png)

Despite that I had already manually installed: VSCodeSetup-x64-1.50.1.exe

**Comment by joaomoreno** [comment]
Did you completely uninstall VS Code?

**Comment by reuvygroovy** [comment]
yes'r

**Comment by joaomoreno** [comment]
So, did you install the latest version?

**Comment by reuvygroovy** [comment]
I'll repeat the story:
1. I uninstalled the software
2. Reinstalled version 1.50.1
3. I don't do anything
4. A day or two later VSCode downgrades to version 1.46 and let's me know I have an update

**Comment by joaomoreno** [comment]
> A day or two later VSCode downgrades to version 1.46 and let's me know I have an update

VS Code won't just downgrade for any reason. I suspect you have two installations of VS Code in your system. Uninstall VS Code again and do a full system search for VS Code (Code.exe for example). I bet you'll find something.

**Comment by reuvygroovy** [comment]
After uninstalling.
![image](https://user-images.githubusercontent.com/1325158/98115865-23e1a580-1eb0-11eb-81f8-cbfb3758d9da.png)

Trying again to install..

**Comment by reuvygroovy** [comment]
thanks
