### ISSUE TITLE
Enabling context display for search result forgets scope of search

### ISSUE THREAD

**Issue by codefox42** [microsoft/vscode#109556]
### System information

> Version: 1.50.1 (system setup)
> Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
> Date: 2020-10-13T15:06:15.712Z
> Electron: 9.2.1
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT x64 10.0.18363

* All extensions disabled

### Reproducible steps

1. Open Search
2. Enter text to search for (that will match multiple files)
3. Click _Open in editor_ to open the result in a new editor window
4. Click the _Context_ icon located at the top right of the editor window to disable the display of context lines (which was enabled for me by default, when I remember correctly)
5. Close this editor window
6. Remove some of the files in the list of search results
7. Click _Open in editor_ to open the result in a new editor window once again (this time it displays only lines from the files that were not removed from the search results and without context)
8. Click on the _Context_ icon located at the top right of the editor windows to enable the display of context lines

### Expected result

Lines with context from the partial search result (i.e. no lines from files that have been removed from the search result in step 6).

### Current behavior

When reenabling the display of context lines, the editor windows forgets about the partial search result it was created from and displays lines (with context) from all files with matches.

**Comment by JacksonKearl** [comment]
Yes, enabling context starts a brand new search.
