### ISSUE TITLE
Opening a multi-step quickpick when focus starts in the terminal dismisses when moving to the 2nd step

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#109538]
In GitLens, I have many multi-step quickpicks, and recently (today?) navigating from the first step to the second fails -- the second step flashes up for a brief second and disappears. While if focus starts from the editor or another view everything works fine.

Steps:

1. Focus the terminal
1. Open the command palette and choose _GitLens: Git Commands_ (or _GitLens: Git Command Palette_ if you are on the RC)
1. Pick the _switch_ step
1. :bug: You should see a list of branches to switch to, but instead the quickpick is just dismissed

If you follow the same steps with the focus outside the terminal all is well.

**Comment by roblourens** [comment]
Can repro, only in windows, only when the problems view is in the terminal pane.

**Comment by roblourens** [comment]
Thanks @eamodio, good catch.
