### ISSUE TITLE
The default height of details of suggests is too small

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#109564]
Version: 1.51.0-insider
Commit: e5c0007ce0e9a3816679cba674d03376c03726e3
Date: 2020-10-27T05:32:19.703Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0
Steps to Reproduce:

1. Open suggests and details with `Ctrl+Space`.
2. The height of details is too small compared to VS Code 1.50.

VS Code 1.50.1

![スクリーンショット 2020-10-28 15 38 42](https://user-images.githubusercontent.com/10665499/97401462-34d06b00-1934-11eb-8ba4-f87e7690c650.png)

VS Code 1.51.0-insider

![スクリーンショット 2020-10-28 15 39 12](https://user-images.githubusercontent.com/10665499/97401503-474aa480-1934-11eb-8c84-3b289dd6de8c.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
That got fixed yesterday when fixing https://github.com/microsoft/vscode/issues/109458. Instead of a guesstimate the size is now the actual size

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest
