### ISSUE TITLE
Failed to install an extension with EPERM exception (operation not permitted, write)

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#1095]
This seems to happen on Windows only using Commit 942e9b and could be reproduced on multiple machines. 

- wanted to install tslint
- checked whether it was already installed ant tslint didn't show up
- selecting tslint from `install extension`
-> EENOPERM exception

**Comment by egamma** [comment]
Please change the file back to zip :smile: 

![eg2tslint](https://cloud.githubusercontent.com/assets/172399/11650457/947df012-9d89-11e5-8aff-7a0a1d73b396.gif)

**Comment by joaomoreno** [comment]
This is fixed.
