### ISSUE TITLE
freeze report

### ISSUE THREAD

**Issue by shazaib491** [microsoft/vscode#109524]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.vs code latest version  is hanging in ubuntu 20.0 lts 
2.its hang whole system how to fix that issue

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
Please see https://github.com/microsoft/vscode/wiki/Performance-Issues for how to report a performance issue.

**Comment by shazaib491** [comment]
thankyou for the help mem @alexr00
