### ISSUE TITLE
Menus: tweak position with custom menus in activity bar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109603]
I know we had a recent change in this area which I think was good, but I still think the position of the custom menu over the hamburger action icon or the gear icon could be improved.

Here is today:

![image](https://user-images.githubusercontent.com/900690/97453002-9e04ae00-1935-11eb-8c0b-30bbf7eec81e.png)

![image](https://user-images.githubusercontent.com/900690/97453019-a2c96200-1935-11eb-82ce-d087b75aea52.png)

The current location makes it look almost like a right-click context menu that is anchored to my mouse, but not the icon.

Compare with e.g. Teams:

![image](https://user-images.githubusercontent.com/900690/97453134-bc6aa980-1935-11eb-97a7-8610f686321d.png)

![image](https://user-images.githubusercontent.com/900690/97453154-c096c700-1935-11eb-9711-84b0e78b8465.png)

I think the truth is somewhere in between: more anchored to the action icon (not above or below) and maybe aligned to the activitybar width?

//cc @misolori

**Comment by misolori** [comment]
Agreed, having both menus (web menu and gear menu) should be anchored to the right of the activity bar and then vertically relative. So web menu anchored to the top and gear menu to the bottom.

**Comment by bpasero** [comment]
I like that 👍

**Comment by sbatten** [comment]
hmm the position you screenshot is a bug, on Windows Edge, where I tested, it appears as suggested by @misolori , will fix

**Comment by misolori** [comment]
It could also be that the Codesapce header (in PPE) is forcing the menu down

**Comment by sbatten** [comment]
it was broken in desktop anyway so fix there my help both

**Comment by bpasero** [comment]
Thanks for the prompt fix 👍

**Comment by bpasero** [comment]
@sbatten oh I just realized we seem to be having the same issue for accounts menu:

![image](https://user-images.githubusercontent.com/900690/97535804-7efd2f00-19bc-11eb-9dc3-b3d998897ea3.png)

Can we look into that too?

**Comment by sbatten** [comment]
@bpasero this actually is expected because by default the accounts menu is not as large so it tries to flow down. when that fails, the menu flows up. the account icon doesn't know the size of the menu beforehand and the menu layout logic doesn't currently align to anything but the top of the anchor. 

with that, let's keep this verified and open a separate issue to improve the context view layout logic in general

**Comment by bpasero** [comment]
Seems back:

![image](https://user-images.githubusercontent.com/900690/99223033-067fd600-27e4-11eb-8f55-5b1e6a52a119.png)

**Comment by sbatten** [comment]
The broken case was macOS web. Verifier should be sure to test this case.
