### ISSUE TITLE
Code removes newline at the end of .json files

### ISSUE THREAD

**Issue by moi90** [microsoft/vscode#109649]
- VSCode Version: 1.50.1
- OS Version: Ubuntu 18.04.5 LTS

Steps to Reproduce:

1. Start without extensions: `code --disable-extensions`
2. Open JSON file. Add newlines at the end of the file.
3. "Format Document".

The newlines are gone.

Does this issue occur when all extensions are disabled?: Yes.

Settings:
```json
{
"files.trimFinalNewlines": false,
}
```

**Comment by aeschli** [comment]
The JSON formatter removes all 'unnecessary' new lines.

The request to preserve new lines is https://github.com/microsoft/vscode/issues/23260
