### ISSUE TITLE
image ne se charge pas

### ISSUE THREAD

**Issue by benissez** [microsoft/vscode#109659]
Issue Type: <b>Feature Request</b>

dans mon code html si s'introduit une image elle ne s'affiche pas

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042

**Comment by aeschli** [comment]
Sorry, can you provide a sample code and the steps?

**Comment by benissez** [comment]
<img src=""Bureau\REVISION WEB\IMG_20180916_082547.jpg""> when i execute the image isn't upload but if i execute the same code with notepad++ image upload correctly

**Comment by benissez** [comment]
it's with visual studio code that i have this problem

**Comment by aeschli** [comment]
Sorry, I don't understand. You have the following content in a `.html` file
` <img src=""Bureau\REVISION WEB\IMG_20180916_082547.jpg"">`

What do you mean by `execute the image` ?

**Comment by benissez** [comment]
I don't know how to explain .with visual studio code when I try to introduce image it's impossible I don't know why?

**Comment by aeschli** [comment]
Sorry I'm guessing here:
- remove the extra quotes and use forward slash `<img src="Bureau/REVISION WEB/IMG_20180916_082547.jpg">
- make sure there is an image `Bureau/REVISION WEB/IMG_20180916_082547.jpg` relative to the html file. You can do this e.g. with drag and drop in the file explorer.

That's not really a VSCode issue, just HTML. If there anything VSCode should have done, please let us know.
I'm closing for now, happy to reopen with more information.
