### ISSUE TITLE
VSCode is too slow on all actions related to SCM

### ISSUE THREAD

**Issue by Elichkoto** [microsoft/vscode#109652]
Issue Type: <b>Performance Issue</b>

It seems that VSCode has significant degradation in performance, while it's trying to show up the changes in Source Control tab. Changed files are shown after some delay, checking the changes takes a lot of time and staging the changed files seems too slow than previously.
I'd disabled all of my extensions, but the result is still the same.
I suspect that it comes with the latest update of the VSCode.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (2.42GB free)|
|Process Argv|--crash-reporter-id 2984cfc6-fa2b-40ff-8cdd-87a1ca7828e6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
code-runner|for|0.11.1
beautify|Hoo|1.5.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-icons|vsc|11.0.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Is this a new issue? When did it start happening?

Does running `git status` in a command prompt give the same slowness?

**Comment by Elichkoto** [comment]
No, ```git status``` shows the modified files immediately.
You can check the behaviour here:
![SlowVSCode](https://user-images.githubusercontent.com/9268396/97581628-7842dc00-19fd-11eb-8021-5a5412957cfc.gif)

**Comment by joaomoreno** [comment]
What git version do you have installed? Have you tried to update git itself?

**Comment by alexdrl** [comment]
I have the same issue with VS Code on Windows, updated git to 2.29.1 with no luck.

**Comment by Elichkoto** [comment]
I've updated to ```2.29.1.windows.1```, but still issue is reproducible.

**Comment by joaomoreno** [comment]
Unfortunately, just like in  #34898, we never really did find the root cause of this.

Any additional interesting information will help here:

- Does this reproduce in other repositories?
- Does this reproduce in older VS Code releases?
- Does this reproduce in Insiders as well?

Etc.

**Comment by Elichkoto** [comment]
> Unfortunately, just like in #34898, we never really did find the root cause of this.
> 
> Any additional interesting information will help here:
> 
> * Does this reproduce in other repositories?
> * Does this reproduce in older VS Code releases?
> * Does this reproduce in Insiders as well?
> 
> Etc.

**Comment by alexdrl** [comment]
I have Gitlens, C# and powershell only installed, I will test on Insiders...

**Comment by Elichkoto** [comment]
> Unfortunately, just like in #34898, we never really did find the root cause of this.
> 
> Any additional interesting information will help here:
> 
> * Does this reproduce in other repositories?
> * Does this reproduce in older VS Code releases?
> * Does this reproduce in Insiders as well?
> 
> Etc.

It doesn't seems to be related with some repo, it happens everywhere. 
As far as I understood, a lot of my colleagues have the same issue with the latest update.
We're all using v1.50.1, we've disabled all extensions, checking CPU and RAM usage, while using VSCode, but it doesn't show any major spikes.
It seems it's all related to git actions.
I'll try with Insiders as well.
Let me know, if I can help with something. :))

**Comment by Elichkoto** [comment]
Reproducible on Insiders.

Version: 1.51.0-insider (user setup)
Commit: 2d8bbc6976748c4b0c5e84be541674b89b9d91e4
Date: 2020-10-30T06:57:39.786Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by alexdrl** [comment]
I have all these commands running on each refresh of the SCM window 
![image](https://user-images.githubusercontent.com/26382633/97861286-c7418780-1d03-11eb-88d4-f1559d997baf.png)

**Comment by joaomoreno** [comment]
What if you disable all extensions? `code-insiders --disable-extensions`?

**Comment by jmlag** [comment]
@joaomoreno
> What if you disable all extensions? `code-insiders --disable-extensions`?

The issue is still present for me.

**Comment by Elichkoto** [comment]
Guys, sorry for the stupid question, but is it possible to be related somekind with the version of Chrome?

**Comment by dgow** [comment]
had the same problem with big .asset files (Unity). Adding `Assets/_Game/Fonts/*.assets binary` in `.gitattributes` helped

**Comment by edwin-hendriks** [comment]
It simply seems to be related to too many commands being run in combi with a version upgrade of git itself. 

Suppose git itself was upgraded to a version with more functionality but each command takes much more time. Normally when only using git from the command line, this does not matter that much because one git command took 0.01s to complete and now it takes 0.5s (50 times longer). In my case even 1s

However, when using git from VS code, VS code itself uses a rather extensive number of git command for each action it starts to build op. E.g. on my (not so performant but okay) machine using a stopwatch and after turning of any extension and VS Code git setting that could slow things down:

- Pressing CTRL+S: 7 git commands in 10 seconds
- Commiting a change: 17 git commands in 8 seconds
- Sync to master: 19 git commands in 22 seconds

I've tested and each individual command of these in total 33 commands do take exact that same amount of time if you would perform them directly from the command line. 

Now we cannot ask the awesome VS code team to change git. And also not the rather embarrassing machine and network infra I am forced to work with. But I could ask to take a look at reducing the total number of git commands needed to make git work fast enough from VS code (which I love by the way). Or at least give the user the choice to use this bare-bone-least-possible-git-commands option.

**Comment by MartialSeron** [comment]
I have the same problem since I upgraded git to version 2.29.2.windows.3

No problem  with CLI

**Comment by matt-deboer** [comment]
I'm was seeing the same slowdown, and my git version (on ubuntu 20.04) is 2.25.1.
IIRC, somewhat recently GitLens was more tightly integrated with the source control view, and the slowdown for me seems to be correlated to that timeframe.

FWIW, I just disabled the GitLens extension, and immediately saw the performance restored. I suppose I could selectively re-enable it when I need those features...

**Comment by brianpham93** [comment]
Got same issue as well, especially when open workspace with multiple projects. No extension enabled

CPUs | Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 7, 6, 6
Memory (System) | 16.00GB (0.13GB free)
Process Argv | --crash-reporter-id 0f16b330-04e2-4b8d-8eaa-5a18a3f3eabd
Screen Reader | no
VM | 0%

```

CPU %	Mem MB	   PID	Process
    8	   115	  4228	code main
   11	    82	  4231	   gpu-process
    0	    16	  4233	   utility
   29	   410	  4234	   window (amex-service.js — KrisPayBackend (Workspace))
    0	     0	  4252	     /usr/local/bin/fish -l
  117	   541	  4261	     extensionHost
    0	    49	  4376	       electron_node tsserver.js 
    6	   360	  4377	       electron_node tsserver.js 
    0	    33	  4387	         electron_node typingsInstaller.js typesMap.js 
   63	    49	 47757	           npm
    0	    66	  4863	       electron_node server.js 
    0	    49	  5035	       electron_node eslintServer.js 
    0	    33	  5423	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=4261
    0	    16	  5424	       electron_node languageServer.js 
    1	    66	 33584	       /Users/brian/.config/nvm/10.14.1/bin/node /Users/brian/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.8.1/out/worker/bundle.js {}
    0	    33	 33594	         /Users/brian/krispay/non-biz/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod --bind_ip 127.0.0.1 --port 60121 --storageEngine ephemeralForTest --dbpath /var/folders/5_/m382_63n65562k6d9slsgqw40000gn/T/mongo-mem-33584ynY27G8y9HxP --noauth
    0	    16	 33595	         /Users/brian/.config/nvm/10.14.1/bin/node /Users/brian/krispay/non-biz/node_modules/mongodb-memory-server-core/scripts/mongo_killer.js 33584 33594
    1	    82	 46332	       /Users/brian/.config/nvm/10.14.1/bin/node /Users/brian/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.8.1/out/worker/bundle.js {}
    0	    33	 46334	         /Users/brian/krispay/non-biz/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod --bind_ip 127.0.0.1 --port 60221 --storageEngine ephemeralForTest --dbpath /var/folders/5_/m382_63n65562k6d9slsgqw40000gn/T/mongo-mem-463320oiFSsZp3ZVI --noauth
    0	    16	 46335	         /Users/brian/.config/nvm/10.14.1/bin/node /Users/brian/krispay/non-biz/node_modules/mongodb-memory-server-core/scripts/mongo_killer.js 46332 46334
    0	    33	 46404	       electron_node bundle.js 
    0	    33	  4274	     searchService
    0	    16	  5258	     watcherService
    0	     0	 38544	     /usr/local/bin/fish -l
   95	    98	  4247	   shared-process
    0	     0	 47760	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    5	    66	 47756	   window (Issue Reporter)
```

**Comment by brianpham93** [comment]
I got the same issue when open workspace with multiple folders. No extension enabled

CPUs | Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 7, 6, 6
Memory (System) | 16.00GB (0.13GB free)
Process Argv | --crash-reporter-id 0f16b330-04e2-4b8d-8eaa-5a18a3f3eabd
Screen Reader | no
VM | 0%

```
CPU %	Mem MB	   PID	Process
    8	   115	  4228	code main
   11	    82	  4231	   gpu-process
    0	    16	  4233	   utility
   29	   410	  4234	   window (amex-service.js — prjNameBackend (Workspace))
    0	     0	  4252	     /usr/local/bin/fish -l
  117	   541	  4261	     extensionHost
    0	    49	  4376	       electron_node tsserver.js 
    6	   360	  4377	       electron_node tsserver.js 
    0	    33	  4387	         electron_node typingsInstaller.js typesMap.js 
   63	    49	 47757	           npm
    0	    66	  4863	       electron_node server.js 
    0	    49	  5035	       electron_node eslintServer.js 
    0	    33	  5423	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=4261
    0	    16	  5424	       electron_node languageServer.js 
    1	    66	 33584	       /Users/brian/.config/nvm/10.14.1/bin/node /Users/brian/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.8.1/out/worker/bundle.js {}
    0	    33	 33594	         /Users/brian/prjName/subPrjName/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod --bind_ip 127.0.0.1 --port 60121 --storageEngine ephemeralForTest --dbpath /var/folders/5_/m382_63n65562k6d9slsgqw40000gn/T/mongo-mem-33584ynY27G8y9HxP --noauth
    0	    16	 33595	         /Users/brian/.config/nvm/10.14.1/bin/node /Users/brian/prjName/subPrjName/node_modules/mongodb-memory-server-core/scripts/mongo_killer.js 33584 33594
    1	    82	 46332	       /Users/brian/.config/nvm/10.14.1/bin/node /Users/brian/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.8.1/out/worker/bundle.js {}
    0	    33	 46334	         /Users/brian/prjName/subPrjName/node_modules/.cache/mongodb-memory-server/mongodb-binaries/4.0.14/mongod --bind_ip 127.0.0.1 --port 60221 --storageEngine ephemeralForTest --dbpath /var/folders/5_/m382_63n65562k6d9slsgqw40000gn/T/mongo-mem-463320oiFSsZp3ZVI --noauth
    0	    16	 46335	         /Users/brian/.config/nvm/10.14.1/bin/node /Users/brian/prjName/subPrjName/node_modules/mongodb-memory-server-core/scripts/mongo_killer.js 46332 46334
    0	    33	 46404	       electron_node bundle.js 
    0	    33	  4274	     searchService
    0	    16	  5258	     watcherService
    0	     0	 38544	     /usr/local/bin/fish -l
   95	    98	  4247	   shared-process
    0	     0	 47760	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    5	    66	 47756	   window (Issue Reporter)
```
