### ISSUE TITLE
Git commit template not updating

### ISSUE THREAD

**Issue by pp5311006** [microsoft/vscode#109660]
- VSCode Version: 1.50.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:
1. use vscode remote ssh extension to connect to a linux machine
2. git config --global --edit to set a template 
3. git config --global --edit to change a template
4. git commit message in vscode source control is not updated

Does this issue occur when all extensions are disabled?: N/A

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by pp5311006** [comment]
Unfortunately the environment I am currently using is for work, I am not able to make a screen recoding.

This is what the VS Code source control looks like when I update my global git commit message template using the command:
`git config --global --edit`
![image](https://user-images.githubusercontent.com/12990920/97650162-0ff30980-1a94-11eb-8a6c-486b5e45e030.png)

I feel like vscode has a cached commit message template which is not updating when I change the global git commit message template.

**Comment by joaomoreno** [comment]
The commit template auto updating feature only works if the template file is inside the repo, since we listen for file events there. If the template file is elsewhere, VS Code won't react to its changes at all: you have to manually hit the Git Refresh command.

**Comment by pp5311006** [comment]
@joaomoreno Since the first time I used git config --global to set the template file and VS Code had successfully picked up the content in that file, I was wonder if there is anyway I could clear the cached template and re-config the commit template. Also Git refresh command did not make any difference. Perhaps there is a location on my Windows machine (where VS Code is installed) that contains the cached template?
