### ISSUE TITLE
find and replace bad

### ISSUE THREAD

**Issue by Hardcore-fs** [microsoft/vscode#109623]
Issue Type: <b>Bug</b>

Let's say we have hte following code:

},
        "3": {
          "x": 637.82196,
          "y": 27.5510254,
          "z": 909.427734
        },

find "},"
replace" },
          "pause": 0,
          "speed": 650.0
        },"

the find & replace is NOT continuing the search from the END of the replacement text

and so it creates a loop.

it should do the insert then continue AFTER the replaced text.. not the stat.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 17.7.0

**Comment by rebornix** [comment]
@Hardcore-fs could you please format your snippet (for example, wrap them inside a code block ```) to help troubleshoot?

**Comment by Hardcore-fs** [comment]
The default initial  content to be  processed.


`},
"3": {
"x": 637.82196,
"y": 27.5510254,
"z": 909.427734
},'

What we want to find:
'
},
'
what we want to replace it with:

' },
"pause": 0,
"speed": 650.0
},`



so we should end up with: 

`},
"3": {
"x": 637.82196,
"y": 27.5510254,
"z": 909.427734
},
"pause": 0,
"speed": 650.0
},`


YES !!!  , i know the above is "miss-nested, that is becasue there is a second operation after this to make the complete expression , nested correctly, but that is not relevant to this bug.

Specifically becasue you are adding in a string that contains part of the search string, it triggers a loop.

The search should continue AFTER the inserted text.

**Comment by rebornix** [comment]
I'm not able to reproduce this issue, after doing the replacement, the search result count is then 3 and I can navigate between them.

**Comment by Hardcore-fs** [comment]
Nope sorry.....
if you get the find and replace up , enter the text as shown
and then replace each occurrence one at a time, you get:

`{
                
                        "x": 511.066132,
                        "y": 38.21089,
                        "z": 627.5774
                     },
                    "pause": 0,
                    "speed": 650.0
                 },
                    "pause": 0,
                    "speed": 650.0
                 },
                    "pause": 0,
                    "speed": 650.0
                 },
                    "pause": 0,
                    "speed": 650.0
                 },
                    "pause": 0,
                    "speed": 650.0
                 },
                    "pause": 0,
                    "speed": 650.0
                },`


just followed my own post, but if you  do a full replace "replace all" then it functions.

**Comment by rebornix** [comment]
Isn't this what should happen? After the first replacement, the document is changed and search re-triggers. The behavior aligns with other editors (e.g., Sublime, Atom).

**Comment by Hardcore-fs** [comment]
er no.......
after the search, the search should restart AFTER the replacement not on the previous to last 
LAST character of the replacement.

you can see after the replacement it DOES NOT move the cursor back to the start of the file.

it leaves the cursor in the WRONG place after the replace......... hence the replace is incorrect
