### ISSUE TITLE
Remote SSH extension locks up low memory servers

### ISSUE THREAD

**Issue by spacehen** [microsoft/vscode#109677]
- VSCode Version: 1.50
- OS Version: Linux

Steps to Reproduce:

1. Start SSH server on constricted remote host with less than 600MB of memory (Google f1-micro instance)
2. Use the SSH extension by Microsoft to connect to host.
3. Observe hosts CPU usage
4. Remote host will hang after a couple of connections, server reset required.

Does this issue occur when all extensions are disabled?: No

See: https://medium.com/good-robot/use-visual-studio-code-remote-ssh-sftp-without-crashing-your-server-a1dc2ef0936d

**Comment by roblourens** [comment]
Unfortunately it needs more memory than that. Probably 1GB minimum
