### ISSUE TITLE
characters not align

### ISSUE THREAD

**Issue by MagicJack** [microsoft/vscode#109645]
- VSCode Version: 1.50.1
- OS Version: Windoes 10 Professional, Build 19041.vb_release.191206-1406

Steps to Reproduce:

1. It always there.
2. This issue is same as #84119

My settings.json:
```
{
    "editor.renderWhitespace": "all",
    "files.trimTrailingWhitespace": true,
    "python.defaultInterpreterPath": "C:\\progs\\Python38\\python.exe",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "editor.fontSize": 16,
    "window.zoomLevel": 0,
    "editor.fontFamily": "Consolas, 'Microsoft Yahei Mono', 'Courier New', monospace",
    "editor.find.addExtraSpaceOnTop": false,
    "editor.fontLigatures": null
}

```

Sympton:
1. If the '細明體' is in front of them, the outlooking is aligned correctly.
<img width="447" alt="character alignment trouble" src="https://user-images.githubusercontent.com/8586084/97535124-16cb3f00-19f6-11eb-9e17-2c01d4390c19.png">

2. For font 'Consolas' and 'Microsoft YaHei Mono', no matter what order are them, the outlooking of one 'Chinese' character is a little bit narrow than two 'English' characters. 
<img width="447" alt="character alignment trouble2" src="https://user-images.githubusercontent.com/8586084/97535430-99ec9500-19f6-11eb-81ef-7234e9df5894.png">

3. 'Microsoft YaHei Mono' or 'Consolas' was used to have an aligned text view of mix English and Chinese (no matter zh-tw or zh-cn) for other IDE or cmd.exe console.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@MagicJack I believe you want to use a font which renders wide characters as 2x the width of latin characters. VS Code respects the glyph widths as defined by the font you have configured, so I believe 'Microsoft YaHei Mono' or 'Consolas' do not have the wide characters have twice the width of latin characters. You need to install and try different fonts until you find one which defines the widths you desire. An example that I know of is [Inconsolata](https://fonts.google.com/specimen/Inconsolata), but there are other fonts like that for sure.

**Comment by MagicJack** [comment]
No, It's not the case.
1. 'Microsoft YaHei Mono' embedded 'Consolas' in it, and 'Microsoft YaHei Mono' was modified from 'Microsoft YaHei' which is a monospaced font. But the 'English' part of 'Microsoft YaHei' just little bit ugly, so someone replace it with 'Consolas'.
2. It was widely known before Win10 was born. And we used to use it in IDE's, text editor and even in windows command console. It just work perfectly.

You said
>> VS Code respects the glyph widths as defined by the font you have configured
I believe that true.
I'm just wondering why it works on other text editor, IDE... but VScode don't?

Aren't there some other settings or situations that make it won't work in VScode?
Thanks.

**Comment by alexdima** [comment]
It is possible that other code editors use a different font rendering stack than VS Code. VS Code is built with Electron, which is built with Chromium. For the VS Code editor we delegate all text layout and rendering to Chromium. This allows us to support complex scripts, such as Arabic, Tamil, Hebrew, and partially support complex layout situations like RTL or bi-di. In order for all of that to work, we do not make any assumptions about the width of characters, we delegate rendering to Chromium, which uses the kerning rules defined by the font.

**Comment by MagicJack** [comment]
Understood.
I've try 'Noto Sans Mono CJK TC Regular', it's aligned again.
So, it's about 'Microsoft YaHei Mono' or 'Consolas' themselves.
Thanks, anyway.
