### ISSUE TITLE
Live Share failure to install

### ISSUE THREAD

**Issue by Paullouis5168** [microsoft/vscode#109657]
Issue Type: <b>Bug</b>

Live Share keeps refreshing / crashing when installing. The extension was working fine for 10 mins and it started having issues, tried uninstalling and reinstalling vs studio code and the extension multiple times
![ezgif-4-49965af1a8e8](https://user-images.githubusercontent.com/66101837/97552953-d2e53380-1a0f-11eb-89da-a73ea0748e78.gif)

.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (10.88GB free)|
|Process Argv|--crash-reporter-id 2e44ea1b-5542-4c72-be29-bb9ad52a6c8c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.10.332292344

</details>

![ezgif-4-49965af1a8e8](https://user-images.githubusercontent.com/66101837/97553093-fdcf8780-1a0f-11eb-822f-6bfba267a21e.gif)

**Comment by sandy081** [comment]
Please file issue against the live share extension for initial investigation.
