### ISSUE TITLE
Saving (repeatedly) with syntax errors causes code to be deleted and/or broken

### ISSUE THREAD

**Issue by bbugh** [microsoft/vscode#109621]
I am re-reporting the issue from #109530 with additional info because I think there was a miscommunication about the severity of this issue and it was closed before I could provide more info. I cannot imagine that this very destructive and unexpected behavior is intended. 

When `tsconfig` `allowUnreachableCode` is `false` (the default) and `"editor.codeActionsOnSave": { "source.fixAll": true }` is set, VSCode will delete code in an unpredictable way as a result of syntax errors because of error code 7027. On the other hand, it does not delete other "unused code" errors like 6196 (the `interface Nothing` in the example).

![Screen-Recording-2020-10-28-at-3-2](https://user-images.githubusercontent.com/438465/97493837-89271b00-1933-11eb-901a-e3ad5ee20355.gif)

Additionally, it will continue to delete other parts of the code every time it is saved, as shown in the example gif. In a real world case, we have a `utilities.ts` file, and any time we save with a relevant syntax error, it will delete the next function on every repeated save, until the file is empty. 

Additionally, it only partially deletes code where the to-be-deleted code has comments, which introduces additional syntax errors caused by VSCode, as shown by the `// return\n}` fragment in the example gif.

Accidental syntax errors are a common part of programming, and I don't think that VSCode deleting and breaking valid code as a result of a common mistake is good behavior for a code editor! It is not uncommon for us to save a file with an accidental syntax issue and not realize that code was deleted until we're trying to track down webpack errors. 

I do not remember this ever happening until the last few weeks. I am not sure what changed to cause it. We have minimal changes to our configuration except for the VSCode updates and upgrading TypeScript to 4.0.3.

- VSCode Version: 1.50.1
- OS Version: 10.14.6
- TypeScript: 4.0.3

Steps to Reproduce:

1. Create a file with this code:
  ```typescript
  export function anyFunc () => {
    // The return statement here with this syntax error triggers error 7027
    // which causes everything after it to be DELETED on save
    return
  }

  export const will_be_removed_on_first_save = () =>
    // return
  }

  export const will_be_removed_on_next_save = () => {
    return
  }

  interface Nothing {}
  ```
1. Save the file, and observe that the first `export const` is partially deleted, leaving `// return` and `}`
1. Save again and observe that the second `export const` is removed, leaving the previous partially deleted fragment intact, which creates a new syntax error
1. Save again and observe that the 6196 "unused code" error on `Nothing` is not automatically removed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I [already explained](https://github.com/microsoft/vscode/issues/109530#issuecomment-717553135) how this behavior is not enabled by default (and can be easily disabled) and how, if your code is not syntactically valid, we can't make an guarantees that anything will work

**Comment by bbugh** [comment]
I am not concerned about the setting value, I am reporting that the behavior of the "all inclusive" settings is breaking things in a really bad way. I'm very confused how you are suggesting that this is acceptable behavior for a code editor. The demo video shows how much of a drastic breaking change it is to code.

**Comment by bbugh** [comment]
Additionally, it is only deleting code partially, leaving some "unused code" behind. This behavior is internally inconsistent.

**Comment by mjbvz** [comment]
Your code is already broken. We make a best effort attempt to work with invalid code but will not get this right all the time.

If you don't like this happening on save, disable the setting
