### ISSUE TITLE
Bot should not lock author-verification-requested issues until after the iteration

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#109699]
Noticed on this issue https://github.com/microsoft/vscode/issues/98504#issuecomment-712616116 that the github bot locked the issue just 4 days after author verification was requested. Should probably keep these open until the end of the iteration (or just extend the time until a lock happens)

**Comment by JacksonKearl** [comment]
Looking at the logs I think I might have just totally disabled the locker... investigating 🙃 https://github.com/microsoft/vscode/runs/1495852851?check_suite_focus=true

**Comment by RMacfarlane** [comment]
@JacksonKearl Is there any way to verify this besides just code review? Seems like a reasonable change to wait to lock it until "verified" has been applied for author-verification-requested changes. From the logs you linked, it looks like some issues are still getting locked, do you still think it's been disabled?

**Comment by JacksonKearl** [comment]
I fixed the locker but as of right now there aren't any old author-verification-requested's for this to take effect on... I could enable it in a dummy repo with a shorter timeout perhaps?

**Comment by JacksonKearl** [comment]
https://github.com/JacksonKearl/testissues/issues/17727 looks like theres still something up here, moving out to next iteration.

**Comment by JacksonKearl** [comment]
Silly mistake, should be fixed now. (Linked issue and sibiling in same repo can verify)  https://github.com/microsoft/vscode-github-triage-actions/commit/010d576383f608c8d6ced51c051d8765e1912b13

For actual verification I can manually trigger the locker on the test issues repo, which uses a 1 minute cutoff.
