### ISSUE TITLE
holoviews / ipywidgets / Panel not supported in notebooks preview and extension versions

### ISSUE THREAD

**Issue by nemonominem** [microsoft/vscode#109624]
In VSCode, notebooks (either via preview version or python extension) do not support the essential holoviews / ipywidgets / panel visualizations.
That's very limiting as holoviews/hvplot/panel are quickly becoming the best visualisation and dashboarding libraries on Python.

Message: No renderer could be found for MIME type: application/vnd.holoviews_load.v0+json

In all 3 examples below nothing is displayed in the notebook.

Example 1:  Works in Python extension Notebook, not native VSCode Notebook (preview)
-----------
```
import numpy as np
import pandas as pd

index = pd.date_range('1/1/2000', periods=1000)
df = pd.DataFrame(np.random.randn(1000, 4), index=index, columns=list('ABCD')).cumsum()
df.head()

# This works
df.plot();

# This fails:
# No renderer could be found for MIME type: application/vnd.holoviews_load.v0+json
import hvplot.pandas 
df.hvplot()
```

Example 2: Works neither in Native or Extension
-----------
```
import numpy as np
import scipy.stats as st
import holoviews as hv
import panel as pn

pn.extension('mathjax')
hv.extension('bokeh')

# create a title for the dashboard
title = '### Gaussian Dashboard'

# create some text describing the dashboard
desc  = 'An example of a simple interactive HoloViz Panel dashboard.'

from panel import widgets

# Controls
mu_slider    = pn.widgets.FloatSlider(name="µ", start=-5,  end=5, step=0.1, value=0)
sigma_slider = pn.widgets.FloatSlider(name="σ", start=0.1, end=5, step=0.1, value=1)

# Graph
@pn.interact(mu=mu_slider, sigma=sigma_slider)  #<- argument translation
def dograph1a(mu, sigma):
    x  = np.linspace(-10, 10, 200)
    y  = st.norm.pdf(x, loc=mu, scale=sigma)

    return hv.Curve(data=(x, y), kdims=["x"], vdims=["f(x ; µ, σ)"])

# Dashboard
dash1a = pn.Row(pn.Column(title + " #1",
                         desc,
                         dograph1a[0]), # <- Controls
               dograph1a[1])            # <- Widgets

dash1a
```

Example 3: Works in Extension, not Native
------------
```
import ipywidgets as ipw
from ipywidgets import interact, interactive, fixed, interact_manual

def f(x):
    return x

interact(f, x=10);
```

Example 4: Works neither in Native or Extension
------------
```
import ipyvolume as ipv

x, y, z, u, v = ipv.examples.klein_bottle(draw=False)
fig           = ipv.figure()
m             = ipv.plot_mesh(x, y, z, wireframe=False)
ipv.squarelim()
```

**Comment by rebornix** [comment]
/extPython

The rendering of outputs are managed by the Python extension as well so please file issue against them. thanks!

**Comment by nemonominem** [comment]
As stated above, this affects also the native (preview) notebook. 
Is the native notebook using the Python extension to manage the display? If not this issue should be reopened.

**Comment by smackesey** [comment]
This seems relevant: https://code.visualstudio.com/api/extension-guides/notebook#output-renderer

Looks like an extension is needed specifically for VSCode's new notebook API. The extension needs to declare a `notebookOutputRenderer` for `application/vnd.holoviews_load.v0+json` that implements the required interface.
