### ISSUE TITLE
TS Server fatal error:  Cannot read property 'charCount' of undefined

### ISSUE THREAD

**Issue by erikras** [microsoft/vscode#109662]
Issue Type: <b>Bug</b>

Also, either VS Code or Prettier mangles my code.

<img width="900" alt="Screen Shot 2020-10-29 at 12 28 34" src="https://user-images.githubusercontent.com/4396759/97562841-92bb8c00-19e2-11eb-9e36-8f784fa6bf3b.png">

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.0-51-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.83GB free)|
|Process Argv|--crash-reporter-id 5cf06e07-9eb1-4f9a-81c1-130e8a865044|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev|
|OS|Linux x64 5.4.0-51-generic|
|CPUs|Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (4 x 2693)|
|Memory (System)|7.78GB (3.53GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
remote-containers|ms-|0.145.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
debugger-for-chrome|msj|4.12.11
mdx|sil|0.1.0
vscode-icons|vsc|11.0.0
vim|vsc|1.17.1
material-theme|zhu|3.9.3
package-json-upgrade|cod|1.2.2
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
vscode-pull-request-github|Git|0.20.1
vscode-graphql|Gra|0.3.10
vscode-elixir|mjm|1.1.0
react-javascript-to-typescript-transform-vscode|moh|1.10.0
vscode-jest|Ort|3.2.0
gitblame|wad|6.0.0
glean|wix|5.0.1
vscode-import-cost|wix|2.12.0

(2 theme extensions excluded)

</details>

**Comment by erikras** [comment]
Thanks, @vscode-triage-bot, but I examined those before posting, and they all seemed pretty vacuous.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
