### ISSUE TITLE
Sync debug and editor hover fade out times

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#109627]
Looking at #107921, the debug hover now fades in and fades out according to the Editor Hover Delay setting. However, the editor hover fades in, but does not fade out according to that setting.

Therefore, there is still a difference between the two settings.
I'm not sure if they should be synchronized, so I labelled this as a feature request for now.

CC @isidorn

**Comment by isidorn** [comment]
Let's see what the users think of this for the debug hover.
After talking earlier with @alexdima I thought the editor respects the hover delay also for hiding the hover.

**Comment by isidorn** [comment]
I have actually fine tuned the debug hover. I do not think they should respect the editor hover since the debug hover is much more heavy, and imho should come more slower (since it obscures a large part of the sceen sometimes).
Closing this as no action planned here
