### ISSUE TITLE
Copy/Cut broken on safari on iPadOS

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#109635]
Testing #109422.

<kbd>Cmd+C</kbd> and <kbd>Cmd+X</kbd> are broken on safari on iPadOS in the Monaco editor and the terminal. It seems to me that this is related to the detection of the selection. When having a selection, the iPad toolbar does not show the copy action not do the key bindings work.

However, sometimes I can make it show up: Copy text from the omnibar, then paste into the editor using the key bindings or the iPad toolbar. In most cases the selection you make right after causes the copy action to be enabled.

**Comment by rebornix** [comment]
@kieferrm my guess is you are selecting text through trackpad, right? I didn't reproduce this with selection through arrow keys, but if I use trackpad to select text, even though we do see the selection, it's actually an iOS native selection other than our virtual selection, then the Copy/Cut doesn't work as the editor is not even selected. It's a more severe problem with how selections are being handled now.

I'm not seeing this issue with https://microsoft.github.io/monaco-editor/ so might not be a regression from our side recently. Will dig into a bit more why that happens.

**Comment by rebornix** [comment]
> However, sometimes I can make it show up

With a second try I can't reproduce the issue anymore and reloading the window and tried the third time and ran into it again. When this happens, clicking into the editor doesn't put focus into the editor text.

![ezgif-6-239d332a8ec3](https://user-images.githubusercontent.com/876920/97609925-7bc06e00-19d1-11eb-92a5-4afcac5254a0.gif)

*update*

my 100% reproduce steps are 

* use finger to change cursor position in the editor, should see the blinking cursor
* then use trackpad to select text, no blinking cursor anymore

**Comment by rebornix** [comment]
Previously with iOS/iPadOS 13, `pointer` events work seamlessly with `mouse` events as at that moment, trackpad or external mouse are treated the same as pointer device (Apple Pencil). Now with iOS/iPadOS 14, trackpad and mouse are now treated as real mouse.

Our current logic on iOS:

* listen to `pointerdown` and `pointermove` events for trackpad, mouse and pencil, to mimic clicking and selecting
* listen to `touchStart/End` for finger actions, to mimic clicking and scrolling

However there is potentially an iOS 14 bug with `pointermove` event that as long as you use finger to tab on the editor, trackpad will only emit `mousemove` events other than `pointermove` event. Verified that tabing into Monaco editor also breaks the `pointermove` listener on the terminal (`xterm` DOM). Though I'm not able to reproduce this issue with a simple DIV element.

Considering that webkit doesn't fully support `pointer` events as advertised and how trackpad/mouse are handled now in latest iOS, we should do following refactoring to archive an identical desktop like experience 

* listen to `mouse` events like what we do on desktop, it will handle trackpad/mouse clicking and text selection.
* listen to `touchStart/End` as before for fingers.
* listen to `pointer` events and filter out `pointerType === 'mouse'`, this code path is specifically for Apple Pencil. Need to think about what's the right behavior for the pencil as now you can write text directly with the pencil.

**Comment by isidorn** [comment]
With the fix for https://github.com/microsoft/vscode/issues/122653 this now works great for me.
I can select using touch, mouse, keyboard and copy/cut always work for me.

@kieferrm if you can try it out and let me know if you find some scenario where this is still not working. Thanks a lot!
