### ISSUE TITLE
Format on save for TypeScript files sometimes indents JSDoc comments incorrectly

### ISSUE THREAD

**Issue by craxal** [microsoft/vscode#109622]
- VSCode Version: 1.50.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a TypeScript file with a class and several methods.
2. Create a JSDoc comment for one of the methods.
3. Make sure that auto format on save is enabled for TypeScript files.
4. Save the file.

Does this issue occur when all extensions are disabled?
Not sure, but reloading VS Code seems to rectify the issue.

![AutoFormatBug](https://user-images.githubusercontent.com/3473026/97499301-e23e8100-192a-11eb-93fe-0bd1e9ad77fb.gif)

**Comment by mjbvz** [comment]
Can you confirm this happens with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If it does, please share some example code (as text) that demonstrates the issue

**Comment by craxal** [comment]
It's difficult to reproduce. I've only seen this happen twice, and it only happens on occasion even with extensions enabled. If I have some time, I can try to reproduce with extensions disabled.

**Comment by craxal** [comment]
OK, it just happened again. I restarted Code then disabled all extensions. The JSDoc comments are still indented incorrectly.

**Comment by mjbvz** [comment]
Were extensions disabled when the formatting issue first happened?

**Comment by craxal** [comment]
I had extensions installed and active when it first started. I restarted Code then disabled extensions from the ... menu. I then corrected the indentation manually and saved. The indentation was automatically modified incorrectly again.

**Comment by mjbvz** [comment]
You need to restart VS Code after disabling extension. You can use the `Developer: reload with extensions disabled` command to do this too
