### ISSUE TITLE
windows crashed

### ISSUE THREAD

**Issue by JChavezNI** [microsoft/vscode#109637]
Issue Type: <b>Bug</b>

my windows crash when im open another windows

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.77GB (1.44GB free)|
|Process Argv|--crash-reporter-id d708fe3d-e39c-4ad0-8fcd-7b33fcf1600b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|0.2.3
vscode-JS-CSS-HTML-formatter|lon|0.2.3
remote-wsl|ms-|0.50.1
material-icon-theme|PKi|4.3.0
tsimporter|pmn|2.0.1
JavaScriptSnippets|xab|1.8.0

</details>

see image: https://ibb.co/m48bVDJ

**Comment by alexr00** [comment]
Can you provide the information [detailed in the wiki for crashes](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues)?

**Comment by JChavezNI** [comment]
> Can you provide the information [detailed in the wiki for crashes](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues)?

I don't know what happens, the application gets all blurry, it only happens with the vscode, with the VS2019 it works correctly, when I debug a code or when I open a window over it the app gets blurry.

I have deactivated all the extensions and re-installed the app and the problem persists. 
you can see this image as example: 
[https://drive.google.com/file/d/1LXEMMg2FJbxUwLhOR00_0D5oHO2GHZG7/view?usp=sharing](url)

**Comment by JChavezNI** [comment]
.
