### ISSUE TITLE
Syntax highlighting in HTML is wrong when @page rule contains more than one nested rule

### ISSUE THREAD

**Issue by NicHub** [microsoft/vscode#109651]
- VSCode Version: Version: 1.50.1
- OS Version: macOS 10.14.6, Ubuntu 18

It seems that HTML syntax highlighting is wrong when the CSS styles contain an `@page` rule with more than one nested rule. This doesn’t depend on the OS or on the theme used. Disabling VSCode extensions has no effect.

Steps to Reproduce:

1. Create a file with the content below. Syntax highlighting should be wrong. (See 1st image below.)
2. Comment or suppress line 7. Syntax highlighting should be OK. (See 2nd image below.)

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>SYNTAX HIGHLIGHTING BUG</title>
  <style>
    @page {
      @left-middle { content: none; }
      @left-top { content: none; }
    }
  </style>
</head>
<body>

  <!-- I SHOULD BE GREEN -->
  <div class="container">
    <p id="p1">Lorem</p>
    <p>
      Effect is the same without extensions
      <code>code --disable-extensions .</code>
    </p>
  </div>

</body>
</html>
```

Does this issue occur when all extensions are disabled?: Yes/No
Yes

![syntax_highlighting_bug_001](https://user-images.githubusercontent.com/6534134/97541942-42cecc00-19c6-11eb-96d6-f886c7acd702.jpg)

![syntax_highlighting_bug_002](https://user-images.githubusercontent.com/6534134/97541949-43676280-19c6-11eb-9900-49c733ecd61b.jpg)

**Comment by alexr00** [comment]
This looks like an issue with the CSS grammar we use since the same issue happens when you use the following in CSS:
```css
@page {
	@left-middle { content: none; }
	@left-top { content: none; }
}
```
We get our CSS grammar from https://github.com/octref/language-css, however that repo doesn't support filing issues. @octref, FYI you have this issue.

**Comment by alexr00** [comment]
Closing as the issue is upstream.
