### ISSUE TITLE
Suggest stays small when using arrow left/right

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109658]
* trigger suggest in front on an identifier
* use arrow right to narrow down
* use arrow left to widen
* 🐛 the widget stays small

![Oct-29-2020 11-24-00](https://user-images.githubusercontent.com/1794099/97556210-7109d700-19d9-11eb-8e47-bdefc4f6aaa7.gif)

**Comment by meganrogge** [comment]
doesn't work yet probably because it's unreleased at this point
