### ISSUE TITLE
xterm.css is out of date

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#109636]
@kena0ki spotted in https://github.com/xtermjs/xterm.js/issues/3058#issuecomment-718026122 that https://github.com/microsoft/vscode/issues/104876 was caused because xterm.css was out of date.

Compare

https://github.com/microsoft/vscode/blob/2ee8b8c645ec8ab54304bacae7aa979c1d9c647a/src/vs/workbench/contrib/terminal/browser/media/xterm.css#L64-L80

To

https://github.com/xtermjs/xterm.js/blob/d95a633f164409f413e61f8537f9be90dd011099/css/xterm.css#L61-L77

We should remove the workaround in https://github.com/microsoft/vscode/issues/104876 and re-sync xterm.css.

**Comment by mjbvz** [comment]
Verified that the original problem with the space no longer happens and based on linked PR
