### ISSUE TITLE
Intellisense incorrectly highlighting auto variable in C++

### ISSUE THREAD

**Issue by ardunster** [microsoft/vscode#109695]
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic snap

Steps to Reproduce:

1. Use `auto [var1, var2] = (some object that returns var1, var2);` syntax
2. Intellisense incorrectly highlights functioning code.

In the project I'm working on, we have this bit of code using `auto` to generate two variables from a returned object:
```
auto [attr, l] = UnitParser(remainder).parse();
model.push_back(new Unit(attr));
if (remainder.length() - l <= 0)
	return;
onestring new_rem = remainder.substr(l, remainder.length());
remainder = new_rem;
```

The code compiles and runs fine, however Intellisense gives me 3 errors on the first line and highlights with red squiggles:
`expected an identifierC/C++(40)`
`identifier "attr" is undefinedC/C++(20)`
`identifier "l" is undefinedC/C++(20)`

If I use only one variable, with the `[]` removed, Intellisense correctly interprets it as an automatically typed variable (but of course the code doesn't work otherwise, because I need both variables).

Per [cppreference.com's example code](https://en.cppreference.com/w/cpp/language/auto), this is valid syntax for `auto`.

**Comment by alexr00** [comment]
I can't repro this, is it possible that it's coming from the C++ extension you have installed?

**Comment by ardunster** [comment]
I disabled all extensions, then enabled only `ms-vscode.cpptools` v1.0.1 and still get the same highlighting and error.  Is this not the right place for an error with that extension? 

I am starting to think I need to reinstall VSCode with apt instead of snap, though.... had other issues related to the snap install. When I have time to have it down for a bit while I reinstall and reconfigure I'll try that and see if it changes anything.

**Comment by alexr00** [comment]
Since you need to enable the C++ extension to repro the issue, you should file the issue in the repo for that extension. You can find the repo for most extensions by opening the extensions description page in VS Code. There should be a link for a repository.
