### ISSUE TITLE
"Initializing JS/TS language features" fails to initialize

### ISSUE THREAD

**Issue by jspurlin** [microsoft/vscode#109682]
Issue Type: <b>Bug</b>

"Initializing JS/TS language features" fails to initialize and has been happening consistently over the past few days. Over the past few weeks the intellisense functionality as stopped responding frequently.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|63.90GB (40.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.2
prettier-vscode|esb|5.7.1
vscode-edge-devtools|ms-|1.0.8
team|ms-|1.161.1
code-spell-checker|str|1.9.0

</details>

**Comment by mjbvz** [comment]
Closing this as it is an old VS Code version. If you are seeing this in VS Code 1.50+ with extensions disabled, please let us know
