### ISSUE TITLE
[CodeSpace] Error message: Failed to connect to relay

### ISSUE THREAD

**Issue by avdev4j** [microsoft/vscode#109602]
I am a part of the beta testing phase of GitHub Codespace and I'm not able to start a Codespace session due to an error "Failed to connect to relay".

- VSCode Version: GitHub CodeSpace
- OS Version: macOs Catalina 10.15.7
- Browser: Chrome 86.0.4240.111 and Safari 14.0 (15610.1.28.1.9, 15610)
- Tested with two different internet providers

Steps to Reproduce:

1. Go to one of my repository
2. Create a new codeSpace
3. When the codeSpace is available the error message appear in the right corner
![Capture d’écran 2020-10-28 à 14 12 42](https://user-images.githubusercontent.com/37835668/97451562-25e9b880-1934-11eb-86f0-2ccb75dc8d29.png)
4. Finally, no action, editing code is possible.

I have tested it on 3 different repositories, delete and recreate those, with private mode on.

Does this issue occur when all extensions are disabled?: Yes/No
N/A

**Comment by bpasero** [comment]
@avdev4j could you please report the issue here: https://github.com/MicrosoftDocs/vscodespaces/issues

**Comment by avdev4j** [comment]
Finally, it's working now. I will report the bug but with no reasons the error disappear.
