### ISSUE TITLE
The default file extension, default file language mode

### ISSUE THREAD

**Issue by b5414** [microsoft/vscode#109688]
### Introduction

Hello, I couldn't find in the settings how to choose the default syntax. I didn't have similar problems in _npp_ - a smaller ide

When **I want to put the code** (for example from _stackoverflow_) **and do not want to format the entire document**, I should - create a new file, but this file will be created in txt format(in the program for developers), and if you hit `ctrl+s`, the file will pick up the first line as a title(in more cases | but I found: `workbench.editor.untitled.labelFormat`, and I'm sure you need to change the _default param_ to the "name" instead), and then you will need to type\select the extension for this file... fyi: hit `ctrl+s` in [npp](https://imgur.com/0H7L3pk) and I can working with it without saving.. 

i.e. this is a big time waste, instead of me just doing:
1. 2 clicks \ `Ctrl+N`
2. `Ctrl+V`
3. \> Format
4. `Ctrl+A` + `Ctrl+C`
5. `Ctrl+W` > Don't save

ps I know about `editor.formatOnPaste`, and the situation is taken as an example 

### Describe the feature you'd like.

I need option (`editor.defaultSyntax` or `editor.defaultExtension`, selector) for the default extension, because I can't format a (code in) file (that I haven't saved anywhere), because the formatter doesn't know its extension. [And\Or] Saving a file & Choosing a file format every time is too time-consuming.

Same for the left folder tree (`explorer.applyDefaultExtension`), my idea for it - are: If the user did not specify an extension, select the default one from `editor.defaultExtension`

**Comment by usernamehw** [comment]
`files.defaultLanguage` ?

**Comment by b5414** [comment]
xd, @usernamehw 👍

I was looking for: `[selector] \ syntax \ extension`, but it's not too late to update_it \ expand_tags 🙂

btw, it does not cancel the 2 point - about the folder tree 🙃

**Comment by alexr00** [comment]
You can also select the language mode for an unsaved file with the command "Change Language mode".

@isidorn for 

> Same for the left folder tree (explorer.applyDefaultExtension), my idea for it - are: If the user did not specify an extension, select the default one from editor.defaultExtension

**Comment by isidorn** [comment]
`files.defaultLanguage` is the way to go here
We will not add anything apart from this. Thus closing

**Comment by b5414** [comment]
@isidorn re-read again please, `files.defaultLanguage` is not a solution for the folder tree
