### ISSUE TITLE
The position of details widget of suggests is not correct sometimes

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#109650]
Version: 1.51.0-insider
Commit: 2ee8b8c645ec8ab54304bacae7aa979c1d9c647a
Date: 2020-10-29T06:00:13.428Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:

2. Open a TypeScript file.
3. Type `vscode.languages.`, and open suggests and details with `Ctrl-Space`
4. The position of a suggest details`vscode.languages.match` is not correct.

The same thing happens for `vscode.commands`. The active cursor must be above the middle of the screen.

Does this issue occur when all extensions are disabled?: Yes

![スクリーンショット 2020-10-29 17 02 11](https://user-images.githubusercontent.com/10665499/97541557-b42f6e80-1a08-11eb-98d0-2b9405fd801a.png)

![スクリーンショット 2020-10-29 17 02 36](https://user-images.githubusercontent.com/10665499/97541582-babde600-1a08-11eb-8f71-f2868c6f7f05.png)

**Comment by jrieken** [comment]
I can reproduce. Thanks.
