### ISSUE TITLE
Proxy auth dialog shown on hidden window

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#109667]
Testing #109377

Using Mac native tabs (in cases this matters). I launched from the command line and 2 windows were restored with the second native tab being on top. The proxy dialog was shown on the first window.

Version: 1.51.0-insider
Commit: 2ee8b8c645ec8ab54304bacae7aa979c1d9c647a
Date: 2020-10-29T06:00:13.428Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by chrmarti** [comment]
After entering the wrong credentials on the first window, the dialog showed up the second (hidden) window. 🤔

**Comment by bpasero** [comment]
Awesome finding! Yeah, I thought it would be clever to show the dialog in the window that does the network request but now changed that to be the focused window, same as what the old authentication code was doing.
