### ISSUE TITLE
Feature request: Working sets

### ISSUE THREAD

**Issue by Pszek** [Microsoft/vscode#10962]
Sometimes I happen to work on really trashy repository from which I cannot remove anything. Having some functionality for setting working sets (selecting files and folders which we then have visible in file tree) would be really nice.

**Comment by sandy081** [comment]
Duplicates #9498

**Comment by georgemarrows** [comment]
The OP's request doesn't sound like a dup of #9498 - it's two different uses of working sets. in 9498 it's about a working set of tabs. Here it's about filtering down the list of files you see in the folder view, presumably regardless of whether or not they're open in tabs.

Me, I'm looking for 9498, so I'll move along!
