### ISSUE TITLE
System Sound on Windows dialog boxes lags for the first dialog window

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode#109647]
- VSCode Version: 1.49.1
- OS Version: Win 2004

Keywords for search: sound lagging, audio lagging, slow sound

## Steps to Reproduce

0. Make sure Windows is configured to play sounds for opened dialog boxes (this is the default behavior and can be adjusted via `control mmsys.cpl,,2`)
1. Reload your VS Code Window (Developer: Reload Window)
2. Trigger any dialog window (e.g.: Help: About)
3. The first time the relevant sound has to be played, it takes about 1 second until the sound can be heard.
4. If you trigger the dialog window again, sound plays immediately now.

While this is some kind of cache/performance issue only, it is a small but annoying bug in a power user's workflow because until the sound plays, I am already five steps later and the sound is no longer relevant. I suppose that sounds are loaded lazily somewhere by VS Code/Electron. Usually, my machine has a low CPU, so this is not the source of the problem ...

**Does this issue occur when all extensions are disabled?:** Yes

**Comment by rzhao271** [comment]
I'm unable to reproduce the issue on v1.52.1. Does this issue still occur for you there?
