### ISSUE TITLE
Minor Improvement (A New Variable) For the "window.title" Setting: ${rootParent}

### ISSUE THREAD

**Issue by machineghost** [microsoft/vscode#109676]
Currently the `window.title` setting provides a whole bunch of variables for configuring your window title, which is awesome!  However, I've found that they fall short for a common use case I have: `client` and `server` folders.

Let's say I have two web projects, and each project has a client and server, so I organize them as:

    ~/projects/Foo/client
    ~/projects/Foo/server
    ~/projects/Bar/client
    ~/projects/Bar/server

I then open each one (as needed) in their own separate VS Code, so my "workspace folder" is either "client" or "server".

The problem is, if I use a `window.title` of `${folderName}`, I see "client" or "server" (but I don't know the project name).  If I instead use a `window.title` of `${folderPath}`, I get "~/projects/Foo/client", which would be great ... except that in my taskbar the window title gets truncated, so all I see is `~/projects/Foo`: I don't see the folder name.

What I *really* want to see is `Foo/client` or `Bar/server`, but this is currently impossible.  Adding one simple variable of `${folderParent}`, which resolves to the name of the *parent* of the workspace folder, would solve this.

With such a variable I could have a `window.title` of `${folderParent}/${folderName}`, which would allow me to see `Foo/client` or `Bar/server`, and easily distinguish my different open editors.

**Comment by bpasero** [comment]
@machineghost why not open all the folders into a multi root workspace into one window? Alternatively you could create a workspace file for each folder and give it a distinct name.

**Comment by machineghost** [comment]
>why not open all the folders into a multi root workspace into one window

I wasn't real knowledgeable about workspaces, but I read [this](https://code.visualstudio.com/docs/editor/multi-root-workspaces) and they sound great.

My concern is that when I used one editor before, all of my projects' files were in scope, so a `CTRL + E foo` would be slower. I often had a `foo.js` or `fooBar.js` in another project, and while this might seem trivial, over time going from:

  `CTRL + E foo ENTER`

to:

  `CTRL + E foo` look, think, maybe press `DOWN` once or twice, then `ENTER`

really adds up!  The hassle of having to start up multiple editors (on a machine I rarely restart) is worth it to avoid that.

>Alternatively you could create a workspace file for each folder and give it a distinct name.

I hadn't thought of that , but just now I went and did "Save Workspace As..." for each editor to name them, then changed my window title to `${rootName}`, and now I can see each one easily/separately in my system tray. Thanks!

I'll close the ticket, but for the record **IF** this bug is easy to solve, I'd vote for it to be re-opened, simply because a variable would solve this problem without require workspace files/knowledge.
