### ISSUE TITLE
Unable to install extension 'ms-vscode-remote.remote-wsl' as it is not compatible with VS Code '1.50.1'.

### ISSUE THREAD

**Issue by TannerBragg** [microsoft/vscode#109678]
- VSCode Version: 1.50.1  (Latest at time of issue creation)
- OS Version: 2004 19041.508
- WSL2

Steps to Reproduce:

1.  Running behind firewall in disconnected environment.
2.  Download Remote WSL vsix file  (https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)
3.  Install Remote WSL from extension file.
4.  Receive "Unable to install extension 'ms-vscode-remote.remote-wsl' as it is not compatible with VS Code '1.50.1'." error.

Note:  I receive the same error with the remote container extension, but the remote ssh extension installs successfully.  Maybe an issue with WSL2?

Does this issue occur when all extensions are disabled?: N/A

**Comment by aeschli** [comment]
Yes, Remote-WSL 0.51.x requirer VSCode 1.51 (Insiders)
Use Remote-WSL version 0.50.1 for stable (https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-wsl/0.50.1/vspackage)
