### ISSUE TITLE
[Live Share in Browser] workspace is always displayed as: UNTITLED (WORKSPACE)

### ISSUE THREAD

**Issue by jramsay** [microsoft/vscode#109619]
- VSCode Version: 1.51.0-insider (also tested on 1.49.3)
- OS Version: Windows 10 Enterprise 64-bit OS, x64

Steps to Reproduce:

1. Start a Live Share session on VS Code desktop
2. Join using the Live Share Web link in a browser

Does this issue occur when all extensions are disabled?: No

![image](https://user-images.githubusercontent.com/8161247/97509338-42d7b900-193f-11eb-95f6-b7e174a106e3.png)

@bpasero:  creating an issue to continue the conversation here. You had mentioned the following on the previous thread:

"Untitled workspaces in VSCode are there whenever e.g. a folder is added to the current workspace until you save it to some location. You could probably prevent the untitled workspace altogether if you created and then opened a code-workspace file first."

For Live Share Web (Browser) we have a WorkspaceProvider that extends vscode's FileSystemProvider. It provides the files for the workspace. Then we currently follow up with a call to vscode.workspace.updateWorkspaceFolders() to update the workspace names. This is different from our Live Share Desktop implementation which first creates a '.code-workspace' file "Visual Studio Live Share.code-workspace"  in the local temp directory. We then follow up with a call to:

 vscode.commands.executeCommand('vscode.openFolder', workspaceFileUri, false);

This causes a reload and opens the workspace file which has the correct name: Visual Studio Live Share (WORKSPACE)

I've tried some tests with our browser extension and figured I could use our  "vsls" scheme file system provider to return an empty workspace in this scenario when it gets a request for "Visual Studio Live Share.code-workspace". I had breakpoints in our Workspace FileSystemProviders' stat() and readFile(). Then tried to execute the 'vscode.openFolder' command using a '.code-workspace' uri with the vsls scheme. I'm not seeing it make requests for this file to our FileSystemProvider though. 

Questions: Is this the approach you were suggesting? Is there another way I should be attempting to open the '.code-workspace' file from our Live Share Browser extension?

**Comment by bpasero** [comment]
@jramsay I was able to reproduce a problem locally when I tried to open a workspace that was provided from a file system that an extension registers: https://github.com/microsoft/vscode/commit/f07cc1ef2df4bda394ff2f1c35cdb61a1b741d00

Can you try your flow again after you consumed this change and report back how it goes?

**Comment by bpasero** [comment]
Thanks! Closing optimistically.

**Comment by bpasero** [comment]
\closedWith f07cc1e

**Comment by rebornix** [comment]
Maybe Live Share Web doesn't pick up this yet, I'm still seeing it. How can we verify this locally? @bpasero ?

**Comment by bpasero** [comment]
There is no way.

**Comment by jramsay** [comment]
@bpasero : unfortunately still doesn't work. I can see that code path you mentioned getting hit when the Live Share url is first loaded. At this point though our extension hasn't even had the opportunity to register a FileSystemProvider (that happens on activate).  
![image](https://user-images.githubusercontent.com/8161247/98049723-20351c80-1de5-11eb-8fab-99fc11c0f56a.png)

I never see this get hit again. Even when I call the following after registering the file system provider:
   const uri = vscode.Uri.parse('vsls:Visual Studio Live Share.code-workspace');
   await vscode.commands.executeCommand('vscode.openFolder', uri, false);

The 'openFolder' command appears to do nothing and I'm not seeing any errors in devtools. Even if it did work would openFolder cause a reload in the browser? If so that likely won't work for us as our anonymous login flow requires interaction on reload. 

Currently we use the following to update the workspace folder names:

vscode.workspace.updateWorkspaceFolders

Would it be possible to get support to simply update the actual vscode.workspace.name? (it is read-only)

**Comment by bpasero** [comment]
@jramsay at this point I need to ask you for a minimal hello world extension that exhibits the problem. Please start with `yo code` and add the minimal code for me to reproduce. Thanks.

**Comment by bpasero** [comment]
**Steps:**
* `git clone https://github.com/microsoft/vscode-web-playground.git`
* `yarn`
* `yarn watch`
* cd into `vscode` sources (assuming you have checked it out and `yarn && yarn watch`
* `yarn compile-web`
* `yarn web --extension <path to vscode-web-playground folder>`

This will open a browser instance of VSCode running the `vscode-web-playground`. You can make changes there and see them live after reload.
