### ISSUE TITLE
Error from chokidar. EBUSY: resource busy or locked, lstat. (C:\ hiberfil.sys, pagefile.sys, swapfile.sys, etc.)

### ISSUE THREAD

**Issue by infacto** [microsoft/vscode#109611]
Since a few days, I get a weird error about sys-files from the roor directory of the `c:\` drive.
I'm on an Angular multi-app repo and just call `ng serve --project="whatever"`. 
The build and serve works. But at the bottom of the log, I get these errors:

```text
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
```

```text
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
```

Why related to `C:\`? And why `C:\node_modules`? 😄 My project is here: `C:\projects\...`. There is no `node_modules` folder in `C:\`. Is this related to VS Code? Or serve dev server? Any guesses?

**Version**

```text
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
> I'm on an Angular multi-app repo and just call `ng serve --project="whatever"`.
> The build and serve works. But at the bottom of the log, I get these errors:

This seems to be an issue with `ng serve`. Please report to the angular project.
