### ISSUE TITLE
Untitled file: suggest box constantly shows "Loading..."

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#109675]
1. Cmd + N to open untitled file
2. Trigger suggest box via cmd + space
3. Suggest box constantly shows "Loading...". It does not go away

Compare to stable and see how Stable nicely shows "No Suggestions"

![Screenshot 2020-10-29 at 16 31 01](https://user-images.githubusercontent.com/1926584/97595750-4bde8e00-1a04-11eb-8676-6ea2ccdfc61d.png)

**Comment by jrieken** [comment]
I don't see that... @isidorn Are you sure that you don't have a dead extension host or a bogous extension that never returns completions?

<img width="383" alt="Screenshot 2020-10-29 at 16 44 42" src="https://user-images.githubusercontent.com/1794099/97597376-0de26980-1a06-11eb-89d5-85ade2e6a465.png">

**Comment by isidorn** [comment]
After I removed some extensions I can no longer reproduce this.
I appologize for the noise.
