### ISSUE TITLE
auto import issue 

### ISSUE THREAD

**Issue by RajanKrishnan** [microsoft/vscode#109618]
Issue Type: <b>Bug</b>

Ctrl+. shows the object and also has auto import but the path is wrong 

import { Post } from "../entities/Post";    ---> correct path
import { Post } from "src/entities/Post"; ---> wrong autoimport path

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.69GB free)|
|Process Argv|--crash-reporter-id 232b256b-5942-4c50-a433-6c9b088f0270|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.13
prettier-vscode|esb|5.7.1
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|1.7.0
remote-wsl|ms-|0.50.1
typescript-javascript-grammar|ms-|0.0.53
vs-keybindings|ms-|0.2.0
vscode-typescript-next|ms-|4.1.20201027
java|red|0.69.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.25.0
vscode-maven|vsc|0.25.0
vim|vsc|1.17.1

</details>

**Comment by mjbvz** [comment]
Please share a complete example project to reproduce this issue

**Comment by RajanKrishnan** [comment]
In a zip file will do ??

**Comment by mjbvz** [comment]
A minimal GitHub repo would be better but zip works

**Comment by RajanKrishnan** [comment]
sent you the Github .. access to collabarate see if you got the notification and are able to access the code

**Comment by mjbvz** [comment]
Please share steps on how to reproduce the bug in that repo

**Comment by RajanKrishnan** [comment]
[image: image.png]

just go to this file (posts.ts) and comment the import like in screen shot
and then go to "Post" object and perform ctrl.

**Comment by mjbvz** [comment]
Try setting `"typescript.preferences.importModuleSpecifier": "relative"` or changing your project configuration. The current import style is expected for `commonjs`
