### ISSUE TITLE
Slow file handling on remote

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#109691]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.51.0-insider (2ee8b8c645ec8ab54304bacae7aa979c1d9c647a, 2020-10-29T06:00:13.428Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.3.0-1020-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (1.68GB free)|
|Process Argv|-psn_0_3105526 --crash-reporter-id d4b72415-0109-45b3-a1a7-967fdd12f0f4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.3.0-1020-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.61GB (1.63GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|eam|0.3.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
theme-monokai-pro-vscode|mon|1.1.17
vscode-docker|ms-|1.7.0
remote-containers|ms-|0.147.0
remote-ssh-edit-nightly|ms-|2020.10.29700
remote-ssh-nightly|ms-|2020.10.29700
remote-wsl|ms-|0.51.1
azure-account|ms-|0.9.3
vscode-github-issue-notebooks|ms-|0.0.57
vsonline|ms-|1.0.3073
material-icon-theme|PKi|4.3.0
vscode-ruby|win|0.27.0
gitlens|eam|10.2.2
vscode-pull-request-github-insiders|Git|2020.10.40117
rainbow-csv|mec|1.7.1
vscode-typescript-tslint-plugin|ms-|1.2.3

(4 theme extensions excluded)

</details>

Over the course of the last couple of weeks I realized that working with files on SSH remotes gets slower and slower. I use decent-sized `csv` files with around 20,000 lines. The following operations in the file explorer have becomes massively slower, some of them now taking 5-10s even with all workspace extensions on my ssh box being disabled:
- File copy using Cmd+C -> Cmd+V
- Rename a file
- Permanently delete a file

I see in the status bar that in all of those cases participants are running which seem to account for pretty much all the time I wait.

Here is an example with all workspace extensions disabled:
![qfrCnimSsx](https://user-images.githubusercontent.com/4674940/97616789-3eaca980-19da-11eb-9932-52f7d734d3f8.gif)

**Comment by bpasero** [comment]
I just verified that the copy + delete operations are really just send to the remote and implemented there, there is no IO overhead, i.e. no contents send over.

The participants are likely accounting for most of the time here. Any file operation from the explorer will trigger save participants and that means the remote will be asked to run them which can take time. 

@kieferrm can you check if it reproduces once you selectively disable extensions?

**Comment by kieferrm** [comment]
The above screen recording was made with while all workspace extensions where disabled with the exception of the built-in ones.

**Comment by isidorn** [comment]
Sorry for the slow response, this issue somehow fell throught the cracks.
@kieferrm do you still see this with latest?
