### ISSUE TITLE
Locaolization bug:zh-cn: Preference: files.trimTrailingWhitespace

### ISSUE THREAD

**Issue by wbpluto** [microsoft/vscode#109687]
Issue Type: <b>Bug</b>

files.trimTrailingWhitespace

The Simplified Chinese translation of this setting should be "在行末" other than "在文末"

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.20246
![image](https://user-images.githubusercontent.com/5191513/97608674-9cc6a480-1a4d-11eb-88af-1389d4727709.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (4.60GB free)|
|Process Argv|--crash-reporter-id 61f3155d-cfdf-4529-b9a0-f08835cab1f6|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by danyeh** [comment]
Fixed in [language pack 1.51.2](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans).
Fixed in [file](https://github.com/microsoft/vscode-loc/blob/master/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json#L4636)
