### ISSUE TITLE
Open Folder in File Explorer not working

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#109612]
Issue Type: <b>Bug</b>

* Open an empty workspace
* Go to File Explorer and then click Open Folder
* Nothing happens

`cmd+r` and then choose a folder works fine.

VS Code version: Code - Insiders 1.51.0-insider (bb16786cff3d231facbdcee90741ac25fcffd3ac, 2020-10-28T05:53:18.953Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.36GB free)|
|Process Argv|-psn_0_5260548 --enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|14%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.2
tsl-problem-matcher|eam|0.3.1
vscode-pull-request-github-insiders|Git|2020.10.34021
vscode-fluent-icons|mig|0.0.1
theme-monokai-pro-vscode|mon|1.1.17
vscode-docker|ms-|1.7.0
vscode-language-pack-zh-hans|MS-|1.51.0
dotnet-interactive-vscode|ms-|1.0.152203
vscode-dotnet-runtime|ms-|0.1.2
python|ms-|2020.9.114305
remote-containers|ms-|0.147.0
remote-ssh-edit-nightly|ms-|2020.10.29700
remote-ssh-nightly|ms-|2020.10.29700
hexeditor|ms-|1.3.0
js-debug-nightly|ms-|2020.10.2617
powershell-preview|ms-|2020.9.0
vscode-github-issue-notebooks|ms-|0.0.56
vscode-markdown-notebook|ms-|0.0.13
vscode-notebook-history|ms-|0.0.1
vsliveshare|ms-|1.1.0-dev
vsonline|ms-|1.0.3073
debugger-for-chrome|msj|4.12.11
toggle|reb|0.0.1
java|red|0.69.0
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
rust|rus|0.7.8
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.6.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.25.0
vscode-maven|vsc|0.25.0
notebook-editing|vsc|1.0.0

(5 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@rebornix you dont see a dialog opening doing this?

![recording](https://user-images.githubusercontent.com/900690/97475529-a832a680-194d-11eb-836c-4921cce9fd56.gif)

**Comment by rebornix** [comment]
right, I'm not seeing the native dialog showing up and I'm only seeing this error

```
  ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

**Comment by bpasero** [comment]
I have no ideas why this happens. Did you try from a fresh user data dir? Do you see any output with `--verbose`?

**Comment by deepak1556** [comment]
@rebornix did you open code from command line ? or via finder , dock ?

**Comment by rebornix** [comment]
I can't reproduce this issue any more, which is really weird. Now I only see long lag sometimes when clicking the open folder button, which made me think that probably it's just being slow. Not sure why though. Closing it for now.

**Comment by deepak1556** [comment]
@rebornix next time you see this issue, would be good to check how you launched the app. The error from https://github.com/microsoft/vscode/issues/109612#issuecomment-718135486 definitely sounds like a side effect of https://github.com/microsoft/vscode/issues/102975

**Comment by dbogatov** [comment]
I have same problem.
macOS 10.15.7 (19H2)

**Comment by dbogatov** [comment]
Workaround so far is to "add folder to workspace".
