### ISSUE TITLE
Option to Context Menu

### ISSUE THREAD

**Issue by cbolivar82** [Microsoft/vscode#10968]
- VSCode Version: 1.4.0
- OS Version: Windows 10

it is a improvement that would have VS Code. "In the menu context on windows explorer file we should have the option "Open with
![dmeo fw](https://cloud.githubusercontent.com/assets/7227181/17978901/2834cec0-6ac6-11e6-8f55-0d1caf599a45.png)
 VS Code" like has other editor...

Thanks!

**Comment by joaomoreno** [comment]
During VS Code's installation you are given that option.

![image](https://cloud.githubusercontent.com/assets/22350/18044300/80ddaf42-6dcd-11e6-8401-6b2319d55c41.png)

**Comment by cbolivar82** [comment]
Hi @joaomoreno thank you for your response!, but I mean when you need "Open folder" from the context menu (right click). You can see this example like "Atom" has this option:
![image](https://cloud.githubusercontent.com/assets/7227181/18056633/ab87cb44-6dda-11e6-8a76-3c0baa30f117.png)

That is my point, We don't have available this option in the context menu.

Thanks!
@

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/18056855/ed4955e2-6e0d-11e6-922c-b7344ae0b5af.png)

![image](https://cloud.githubusercontent.com/assets/22350/18056865/fe7e218a-6e0d-11e6-94e5-a9a737cc4b1f.png)
