### ISSUE TITLE
プログラムが実行されない

### ISSUE THREAD

**Issue by Muretengu** [microsoft/vscode#109633]
Issue Type: <b>Performance Issue</b>

「1.＃初めてのプログラム 2.print("ExcelをPythonで使用する。")」と入力した後、実行の「ディバッグ無で実行」をする。左縦帯の下から２番目に青色の➀が出てきて、クイックすると、Gogle Chrome (localhost)に飛び、「localhostで接続を拒否されました」とのメッセージが出てきて先に進めません。対応処置方法をお教え下さい。

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.57GB free)|
|Process Argv|--crash-reporter-id dd364e8a-feff-4413-8d24-cbca816b86ec|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    76	 16312	code main
    0	   148	  2084	   window (#初めてのプログラム.py - 製作プログラム - Visual Studio Code)
    0	    30	 11992	     searchService
    0	     8	 13744	     console-window-host (Windows internal process)
    0	    11	 14568	     watcherService 
    0	     6	  7280	       console-window-host (Windows internal process)
    0	    88	 15092	     extensionHost
    0	    87	  7676	       electron_node ms-vscode.js 
    0	    21	  3696	         window (undefined)
    0	    25	  5408	         utility
    0	    48	 14220	         window (undefined)
    0	     9	 15116	         crashpad-handler
    0	    86	 17884	         gpu-process
    0	    24	 11068	       C:\Users\murak\AppData\Local\Programs\Python\Python39\python.exe c:\Users\murak\.vscode\extensions\ms-python.python-2020.10.332292344\pythonFiles\pyvsc-run-isolated.py c:\Users\murak\.vscode\extensions\ms-python.python-2020.10.332292344\pythonFiles\completion.py
    0	    19	  2536	         C:\Users\murak\AppData\Local\Programs\Python\Python39\python.exe c:\Users\murak\.vscode\extensions\ms-python.python-2020.10.332292344\pythonFiles\lib\python\jedi\inference\compiled\subprocess\__main__.py c:\Users\murak\.vscode\extensions\ms-python.python-2020.10.332292344\pythonFiles\lib\python 3.9.0
    0	     6	  3048	           console-window-host (Windows internal process)
    0	     6	 18040	         console-window-host (Windows internal process)
    0	    36	 15376	     "C:\Users\murak\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\murak\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork" ms-vscode.pwa-chrome "{\"common.vscodemachineid\":\"04ac482c080064bd2a64629894864d7c7608ba53c5bb2b50d4d0c0801f04628c\",\"common.vscodesessionid\":\"036d3f34-dcb5-4fba-909b-c5a0ffc463671603929002147\"}" AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
    0	    61	 17424	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   254	  8340	   gpu-process
    0	    25	  8672	   utility
    0	    66	 11544	   shared-process
    0	    16	 16576	   crashpad-handler
    0	    62	 16964	   window (問題のレポーター)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (#初めてのプログラム.py - 製作プログラム - Visual Studio Code)
|    Folder (製作プログラム): 4 files
|      File types: json(1) log(1) py(1)
|      Conf files: launch.json(1)
|      Launch Configs: pwa-chrome;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ja|MS-|1.50.2
python|ms-|2020.10.332292344

</details>
必要なデータが送信するには大きすぎたため、クリップボードに書き込みました。貼り付けてください。

**Comment by yume-chan** [comment]
Translation:

> ## Program doesn't run
> 
> Input the following code:
>
> ```python
> # My first program
> print("Using Python on Excel")
> ```
>
> Invoke "Run Without Debugging" from "Run" menu
>
> A blue 1 appears at the second from bottom icon
> 
> When I click it, Google Chrome opens at `localhost`, with a "localhost refused to connect" message.
>
> I can't continue from here, please tell me how to fix it.
