### ISSUE TITLE
Custom menu: consider to align accounts menu like gear and home menu

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109681]
Extracted from https://github.com/microsoft/vscode/issues/109603 I think the accounts menu should appear like gear and home menu do, aligned to the right of the activity bar but at the same location as the icon:

![image](https://user-images.githubusercontent.com/900690/97603249-83e9cf00-1a0c-11eb-8ff2-32f5e6854b11.png)

**Comment by bpasero** [comment]
This is back:

![image](https://user-images.githubusercontent.com/900690/99222967-e94b0780-27e3-11eb-975e-30d1d81e0b1d.png)

**Comment by sbatten** [comment]
This would have the same cause as the other issue. It is fixed in tomorrows build. Broken case is macOS Web.
