### ISSUE TITLE
WebView not scaled correctly when zooming vscode

### ISSUE THREAD

**Issue by yaSebastian** [Microsoft/vscode#10965]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1. Zoom the UI
2. Open any WebView (e.g. Extensions Details or Preview of a Markdown File)

The opened WebView is sized for a zoom, but not scaled, staying at 100%, leaving empty space in it's container.
When Zooming with the WebView being open, it is sized and scaled correctly.

**Comment by jrieken** [comment]
dup of #5745
