### ISSUE TITLE
registerWebviewViewProvider: Can't call it a 2nd time

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#109625]
VSCode Version: 1.50.1
OS Version: macOS

Steps to Reproduce:

I'm providing a WebView for the sidebar.
That is working. At least once.
But when I start the extension a 2nd time, calling registerWebviewViewProvider the resolveWebviewView method is not called anymore. And thus the extension hangs.

Here is my package.json:
~~~
		"views": {
			"debug": [
				{
					"type": "webview",
					"id": "dezog.memoryregisterview",
					"name": "Memory Dump",
					"when":"inDebugMode && config.dezog.memoryregisterview.location=='sidebar'"
				}
			]
~~~

And here is the code I use for registering (have stripped it down so that it doesn't do anything anymore, however resolveWebviewView is called only after the first registering, not after the 2nd one).
~~~
public async asyncInit(): Promise<void> {
		return new Promise<void>(resolve => {
			class wvp implements vscode.WebviewViewProvider {
				resolveWebviewView(webviewView: vscode.WebviewView, context: vscode.WebviewViewResolveContext, token: vscode.CancellationToken): Thenable<void>|void {
					resolve();
				}
			};
			const provider=new wvp();
			vscode.window.registerWebviewViewProvider('dezog.memoryregisterview', provider, {webviewOptions: {retainContextWhenHidden: true}});
}
~~~

Is there maybe a way to unregister? So that after a session (the extension is a debug adapter) I can unregister and on the next session register again.

**Comment by mjbvz** [comment]
What do you mean by ` I start the extension a 2nd time`?

Can you share steps to reproduce (along side example extension code)?

**Comment by maziac** [comment]
What I meant was:
The extension is a debug adapter for assembly code.
When I first start the debug adapter then the extension is started and I can register the web view.
Now when I close the debug session I would like to unregister the web view.
Then, on the next debug session, I would like to register it once again.

If this is the wrong approach please advise how to do it / i.e. how to use the API in the right way.

**Comment by mjbvz** [comment]
In all likelihood, you don't need to unregister it at all

If you do feel you need to for some reason, `registerWebviewViewProvider` returns a disposable. Dispose of it to unregister

**Comment by maziac** [comment]
I've tried that already. This has no effect. I.e. it is not unregistering, or, at least, registering afterwards does not lead to a call to resolveWebviewView.
