### ISSUE TITLE
execSync('code --version').toString() returns node.js version instead of vs code version

### ISSUE THREAD

**Issue by akhilravuri1** [microsoft/vscode#109672]
- VSCode Version: 1.50.1
- OS Version: Windows_NT x64

Steps to Reproduce:

1. Create a new project
2.  Add the below code in the function active()

```
   const execSync = require('child_process').execSync;
  var codeOut = execSync('code --version').toString();
  console.log(`codeOut = ${codeOut}`);
```

3. Click F5 or Start Debugging.
4. Check the debug console.

It should print vs code version but it prints node.js version.
OUTPUT in DEBUG CONSOLE:-
```
codeOut = v12.14.1
```

I have created a sample program in node.js and executed it and the output is correct. It prints the vscode version.
```
C:\WORK_VsCode>node vscodeversion.js
codeOut = 1.50.1
d2e414d9e4239a252d1ab117bd7067f125afd80a
x64
```
![image](https://user-images.githubusercontent.com/32290825/97585960-b3560700-1a1f-11eb-9ddc-5a409a2e8b48.png)

Does this issue occur when all extensions are disabled?: Yes

Thanks,
Akhil

**Comment by deepak1556** [comment]
That would be because `ELECTRON_RUN_AS_NODE` env being leaked into the launched process from debugger. You can set the following environment config to workaround

```
"environment": [
    {"name": "ELECTRON_RUN_AS_NODE", "value": ""}
],
```

**Comment by akhilravuri1** [comment]
Hi @deepak1556 

Thanks for the prompt response.

I see a debug label that means only when the user installs the extension then the output will be correct?

I try to get the node version to find the electron version.
Like this:-
```
      try {
        var codeOut = execSync('code --version').toString();
        console.log(`codeOut = ${codeOut}`);
        vscodeVer = parseFloat(codeOut.split('\n')[0]);
        console.log(`vscodeVer = ${vscodeVer}`);
        if(!isNaN(vscodeVer)) {
          if (vscodeVer >= 1.49) {
              electron_version = "9.2.1";
          }
          else if (vscodeVer >= 1.47) {
              electron_version = "7.3.2";
          }
          else if (vscodeVer >= 1.46) {
              electron_version = "7.3.1";
          }
          else if (vscodeVer >= 1.45) {
              electron_version = "7.2.4";
          }
          else {// vscode version older than 1.45 not supported
              electron_version = "7.1.11"; // old binary, not getting updated.
          }
          console.log("Detected VSCode version", vscodeVer,
                  ", will use Electron version ", electron_version);
        }
```
Is there any other way to find the electron version on which vs code is build(from the code---function active(){})? 

Thanks,
Akhil

**Comment by deepak1556** [comment]
you can get that info from `process.versions`

**Comment by akhilravuri1** [comment]
But process.versions only works in developer tools right.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @deepak1556 

Sorry!! 
Able to retrieve the electron version in extension.s file using process.versions.electron

Thanks,
Akhil

**Comment by connor4312** [comment]
I'm unable to reproduce this. When launching debugged programs we do unset ELECTRON_RUN_AS_NODE

![](https://memes.peet.io/img/20-11-6d1fc755-5291-4105-86d5-1d560dc25623.png)

Can you share a small sample repo that contains the code and launch config you're using?
