### ISSUE TITLE
Problem resolving conflicts with YAML files.

### ISSUE THREAD

**Issue by mlezcano1985** [microsoft/vscode#109605]
Hi. I have some problem try to resolve git conflicts with vscode and YAML files.
<img width="618" alt="yaml_merge" src="https://user-images.githubusercontent.com/13625487/97453846-e3fd4a00-1914-11eb-88f9-90628cea2e5c.png">
.

**Comment by joaomoreno** [comment]
https://dev.to/zellwk/resolving-git-conflicts-38h0
