### ISSUE TITLE
Empty entries in SCM histroy

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#109629]
The actual history here was test->rest->[add folder to workspace]->test11->test22, but paging through after a reload I'm getting just test22->[empty]->rest. Its not clear why there are missing entries or why there's an empty entry.

![recording (15)](https://user-images.githubusercontent.com/8586769/97507292-1a00f500-193a-11eb-8eb7-0f741d857c7b.gif)

**Comment by JacksonKearl** [comment]
This line may be the cause
https://github.com/microsoft/vscode/commit/bb3bb1375cf6be37d13769087c97317b61021dcb#diff-0040e0ad33ad9fad03ce48fa1b94486305a362fc2d6ed0401aa1bc270369ff77R97

**Comment by meganrogge** [comment]
@JacksonKearl the storage key is scoped per repo, so I don't think the global storage is this issue. I think the issue is that the history is only getting saved on reload. It should also be saved when a folder is added. Thanks for catching this.
