### ISSUE TITLE
December Test Plan

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#1096]
The test plan for the December iteration plan #917.

### Debug - long text wraps in repl
- [x] win @alexandrudima 
- [x] mac @jrieken
- [ ] linux @SofianHn  

Verify that long text now nicely wraps across multiple lines in the debug repl both for evaluation requests and for output text.

### Debug - breakpoint state
- [ ] win @alexandrudima 
- [x] mac @jrieken
- [x] linux @aeschli 

We have changed breakpoints states and now show it differently in the UI. Verify:
* new UI properly and intuitivly reflects if breakpoints are enabled, disabled, verified or deactivated. 
* breakpoints get hit / not hit depending on their enablement state

### Debug - extension debugging
- [ ] win @dbaeumer 
- [ ] mac @SofianHn 
- [x] linux @aeschli 

Extension debugging is now using a new strategy to attach the debugger to the extension
* verify you can debug your extension as before
* verify you can restart debugging from the debugger side and the debugger reconnects properly
* verify you can change folders or refresh on the extension development side and the debugger reconnects
* verify closing the extension development side stops debugging
* verify stopping the session from the debugger closes the extension development window

### Update - channel from settings
- [ ] win @alexandrudima 
- [x] mac @joaomoreno 

Verify you can change the update channel from settings.

### View - persisted zoom settings
- [ ] win @dbaeumer 
- [x] mac | linux @weinand 

Verify you can change and persist the zoom factor for windows. 
* negative and positive values work
* the zoom actions are still working as before but do not persist
* the change is live

### Quick open - Path and Fuzzy matching
- [x] win @aeschli 
- [ ] mac | linux @isidorn 

Unless you include a path character in your query or enabled fuzzy matching, quick open for files should work as before:
* results are sorted properly with most relevant ones to the top
* editor history always comes first on top of matching file results
* if you narrow down a search, subsequent matching is fast and does not go to the disk (verify with a larger workspace)

Verify the new support to match on paths if included in search
* using the native path separator in the search enables matching on (workspace relative) paths for both editor history results and file matching
* more relevant results are still sorted to the top
* results are highlighted properly also in their path segment

Verify the new support for fuzzy file matching
* find and enable the new setting to enable fuzzy matching for quick open. this will only enable fuzzy matching for file search, it should not have any impact to other quick open providers, nor the editor history search
* verify results from file searches match on the entire (workspace relative) path of the file without having to use the native path separator
* verify matching happens in substrings of the path, not requiring the characters to be in sequence (e.g. "fr" would match "**f**oo_ba**r**")
* more relevant results are sorted to the top

### Extensions info in status bar #1123
- [ ] win @bpasero 
- [ ] mac @egamma 
- [ ] linux @SofianHn  

Verify that the extensions status shows up in the status bar if you have extension errors. Verify clicking on the status bar shows all the error / warning messages to the user and that you can uninstall the extension via action in message.

**Comment by egamma** [comment]
### Emmet support in JSX and TSX files
- [ ] win

In both .tsx and jsx files the following snippet 
``` html
.foo>input[name="bob"]+label[for="bob"]
```

Should expand to
```html
<div className="foo">\n\t<input type="text" name="bob"/>\n\t<label htmlFor="bob"></label>\n</div>
```

**Comment by jrieken** [comment]
## ES6 by default

 Make sure that ES6 is supported without the need to configure something. That that
* JS code inside html supports ES6, like `let`, `const`, and `class C {}`
* Have no jsconfig file and make sure ES6 is supported
* create a new jsconfig.json and make sure the default is ES6 for the target property

**Comment by dbaeumer** [comment]
## Language Server

[ ] win | mac | linux

The language client / server libraries now support the complete set of language features available in the extension host. Implement a sample language server with more features by taking https://github.com/Microsoft/vscode-languageserver-node-example as a starting point. Focus on the new support for CodeActions, CodeLens, Formatting and rename.

**Comment by egamma** [comment]
## vscode-tslint

- [ ] win | mac | linux

- added support for configFile options (known limitations in /Microsoft/vscode-tslint#16
- schema support for the tslint.json configuration file

**Comment by alexandrudima** [comment]
## line/page scrolling
## select current line
## numpad keys
## find widget improvements
 - Ctrl+H, Ctrl+F, Ctrl+ArrowDown
 - Alt+C, Alt+W, Alt+R
## extension deactivate()
## keybindings with kb layout labels, Ctrl+K Ctrl+K

**Comment by joaomoreno** [comment]
### Suggest widget #1006 #1079
- [ ] win
- [ ] mac
- [ ] linux

The Suggest widget underwent quite some heavy rework behind the scenes. Make sure everything still works as before.

### Scoped git services #718
- [ ] win
- [ ] mac
- [ ] linux

You should now be able to open a folder inside a git repo and still have the git features enabled.

**Comment by aeschli** [comment]
## ES6 JavaScript grammar

- [ ] 

 We're using a modifed TypeScript grammar for JavaScript tokenization
* Have a look at some JavaScript files, including ES6, make sure they look fine
* Test the default light and dark theme as well as some contributed themes

**Comment by bpasero** [comment]
@egamma can you send me an up to date version of ts-lint? the one I can install via extensions does not seem to have any of the features on the test plan.

**Comment by egamma** [comment]
@bpasero voila

- .gif -> .vsix
- `code tslint.vsix`

![tslint-0 5 4](https://cloud.githubusercontent.com/assets/172399/11783145/ce1d9304-a275-11e5-8735-d0c4d9dd22a0.gif)

**Comment by jrieken** [comment]
closed in favour of the wiki
