### ISSUE TITLE
Pinned Tabs: offer a mode where unpin icon is hidden

### ISSUE THREAD

**Issue by lymimt** [microsoft/vscode#109639]
I'd like to pin multiple files in my workspace (like `todo.md`, `note.md`, etc.).

If I switch to compact mode, it's hard to distinguish between different files with the same icon.

Shrink mode is good but the unpin button is too easy to accidentally click, I hope there is a way to hide that button.

**Comment by gjsjohnmurray** [comment]
@bpasero could unpinning be added to the undo stack? And pinning too, for symmetry?

**Comment by bpasero** [comment]
@gjsjohnmurray oh I am not very convinced about that to be honest because the change is very subtle and you can easily configure keybindings to toggle the pinned state. I would leave the undo/redo stack for file or edit operations.
