### ISSUE TITLE
Feature request: Mercurial support

### ISSUE THREAD

**Issue by Pszek** [Microsoft/vscode#10961]
I really love default git support for VS Code. I would love to have Mercurial support as well (togglable, non-default).

Really love your product - good job,!

**Comment by sandy081** [comment]
Duplicates #205

**Comment by mrcrowl** [comment]
@Pszek there is now an extension available for Mercurial in VS Code 
https://marketplace.visualstudio.com/items?itemName=mrcrowl.hg

Or just search **hg** from the extensions sidebar.
