### ISSUE TITLE
if i save the file allignement keeps changing

### ISSUE THREAD

**Issue by shivani-14** [microsoft/vscode#109692]
Issue Type: <b>Bug</b>

if i save the alignement keeps changing

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including extensions being used, what language and how to reproduce it (screenshots can be pasted into the textfield here). Have you configured a code formatter?
