### ISSUE TITLE
Suggest box pops up again after explicitly dismissing it and pressin arrows

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#109664]
From Accessibility Gitter channel @Menelion

Hi everyone! After updating VS Code Insiders yesterday it's extremely hard to work since something has changed in the autocomplete algorithm. Now when autocomplete is triggered and I either accept it with Enter or dismiss it with Escape, and then left arrow to review by character what was actually inserted (sometimes it's useful), autocomplete pops up again and prevents me from doing anything, horizontal arrows just don't help. If I press Escape, then try to left arrow to the method again, it pops up for the third time, and it loops. So, for example, the method is called myMethod(), and it was auto-suggested. I'm on the ) char, I left arrow to the ( char, so far so good. then, if I left arrow once more to the d of myMethod, autocomplete pops up again preventing me from navigating. 

Correction: autocomplete now pops up when I just navigate by line past the line that has something that can be suggested. Before it popped up only when I typed characters. could the previous behavior be returned back somehow? Thanks.

From @isidorn
Gist seems to be that the suggest box pops up automatically after being manually dismissed which is unexpected.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Abug+label%3Asuggest+label%3Aux
