### ISSUE TITLE
菜单栏右侧出现不明斜线

### ISSUE THREAD

**Issue by XLearner** [microsoft/vscode#109641]
右上角的功能按钮 “Toggle File Blame Annotations” 出现一条很长的斜线。

![image](https://user-images.githubusercontent.com/26158725/97529083-1f1d7d00-19ea-11eb-975b-fe4f54faabeb.png)

**Comment by XLearner** [comment]
In the top-right corner of my VSCode page, there is a long slash exsiting on the button of "Toggle File Blame Annotations". You can see it in the image I submit. I have no idea of this problem.

![image](https://user-images.githubusercontent.com/26158725/97529559-25602900-19eb-11eb-9b12-b17afd6d25c9.png)

**Comment by alexr00** [comment]
This is coming from the gitlens extension.

**Comment by XLearner** [comment]
I got it. Thanks!
