### ISSUE TITLE
File save time stamp is not correct

### ISSUE THREAD

**Issue by JustinWebDev** [microsoft/vscode#109663]
Issue Type: <b>Bug</b>

I've been editing a PS1 file in VSC for a few days, explicitly Saving several times.  The file date and time never change.  I think the time is from creation.

This is a terrible bug.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1270 v5 @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (27.16GB free)|
|Process Argv|--crash-reporter-id 551da91a-f5ca-43e8-8d21-1a4416d83aab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
VBScript|lug|0.0.2
csharp|ms-|1.23.4
powershell|ms-|2020.6.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Just saved file and Modified time is updated accordingly.
![image](https://user-images.githubusercontent.com/1312662/97582092-074ff400-19fe-11eb-8eb1-b4998298d03d.png)

If it reproducible on any file or some specific? What date/time do you see in file properties for modified and accessed time?
Is it actual file or link/junction?

**Comment by JustinWebDev** [comment]
As far as I can tell, it is only in a particular folder.  I copied my file (it had a strange hour that didn't match anything!), open, save, and it had the current time.  Waited a minute, repeated the open/save, and now it is stuck at the first save time.  Copied in another PS1 from a diff folder and it reproduced.

TXT files in this same folder do not show this problem.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by JustinWebDev** [comment]
Same result with using `code --disable-extensions`.

**Comment by bpasero** [comment]
@JustinWebDev so any other file type shows a modification timestamp that is correct, only PowerShell does not?

**Comment by JustinWebDev** [comment]
TXT shows the correct time.

Here is a pic of the file props.
![image](https://user-images.githubusercontent.com/40804543/97918525-e0563280-1d1b-11eb-859e-2789d706dda2.png)

**Comment by bpasero** [comment]
I cannot explain this, nor do I think that VSCode can do something about this. I suggest to report to Windows.
