### ISSUE TITLE
Alt button conflict (toggle menu-bar & multi-select)

### ISSUE THREAD

**Issue by Motassem-MK** [Microsoft/vscode#10964]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Hi, I'm using Code on windows and there is a little annoying conflict with the "Alt" button when im on full screen, you see Alt is the button used for multi-selection and also for toggling the menu bar, means the menu bar keeps appearing every time i try to multi-select, which causes the code to scroll down a line or two in a very annoying way

I guess a good solution would be giving us the option to assign another button for toggling the menu bar instead of Alt.

thank you.

**Comment by sandy081** [comment]
@Motassem-MK You can also configure different key combination for multi-selection?

**Comment by Motassem-MK** [comment]
well yes, changing the key combination for multi-selection would work too, maybe to Ctrl like some other editors..
but I also couldn't figure out how to do this, as I didn't find it in the huge JSON file of shortcuts.

**Comment by sandy081** [comment]
@Motassem-MK Here are some selection actions key bindings.. you can pick the one you are using and can change the key binding

```
{ "key": "shift+alt+cmd+down",    "command": "cursorColumnSelectDown",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+cmd+left",    "command": "cursorColumnSelectLeft",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+cmd+pagedown", "command": "cursorColumnSelectPageDown",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+cmd+pageup",  "command": "cursorColumnSelectPageUp",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+cmd+right",   "command": "cursorColumnSelectRight",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+cmd+up",      "command": "cursorColumnSelectUp",
```

**Comment by Motassem-MK** [comment]
thank you but the one I want is not a combination, its just the "alt" and i couldn't find it to change it with Ctrl

**Comment by sandy081** [comment]
I do not think there is a key board configuration for menu. I also think it's in built from under-lying electron and wonder we cannot change it.

**Comment by Motassem-MK** [comment]
so you're saying its impossible to use "Ctrl" instead of "Alt" for multi-selection because "Alt" triggers something else at the same time?
