### ISSUE TITLE
Have a setting to disable inline details for suggestions

### ISSUE THREAD

**Issue by adamvictorclever** [microsoft/vscode#109690]
Apologies, I'm not sure if this makes more sense as a VS Code issue or a TypeScript one, but I'm starting here since it impacts the editor UI.

VS Code provides great support for autocompletion for string unions, but it falls a little short for very long strings.

With the example code
```
type Option = "aVeryVeryLongNameThatTakesUpSpace" | "alsoAVeryLongNameThatAlsoDoesThat";

function f(o: Option) {}
```

When I type `f("")` and ask for autocompletion, this is what I see
<img width="462" alt="Screen Shot 2020-10-29 at 11 07 52 AM" src="https://user-images.githubusercontent.com/39533986/97614301-0192e800-19d7-11eb-8522-459bc06c3462.png">

Notice that while the second option is completely readable, the selected option gets cut off. If I select the second option, then the first option is readable but the second one is cut off. This is especially frustrating because the info that takes up the extra space is completely redundant! It's the exact same name as the string itself.

I'm not sure if there are some cases where that extra info is helpful, but could it be special cased to not display if it's the exact same as the original string?

**Comment by mjbvz** [comment]
@jrieken The information that TS returns is correct, but it repetitive since the type and the suggestion are the same. Leaving it up to you on if this is a problem and how we might fix it

**Comment by jrieken** [comment]
I share the pain. What I have in mind is to add a setting that allows to disable "inline details". E.g on select the label would not change and you need the details widget to see more

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/97852032-29fd4800-1d31-11eb-9697-88ab499f6c4a.png)

I think there is another issue. I always have details show in popup (<kbd>Ctrl</kbd> + <kbd>Space</kbd>, `toggleSuggestionDetails`).

![image](https://user-images.githubusercontent.com/1330321/97851874-ea366080-1d30-11eb-8892-60f11054d653.png)

But for these completion items non of inline info and detail popup are visible.

<details>
<summary>
Version Info
</summary>

```
Version: 1.51.0-insider (user setup)
Commit: 49696e87c64f478f97909a91d41ff2913df9bf71
Date: 2020-10-31T00:22:00.097Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763
```

</details>

---

I also don't think an option is required. The suggestion list should either not display duplicate information, or resize itself to not clip important information.

**Comment by jrieken** [comment]
@yume-chan It is the designed and correct behaviour to show details-string in the details-widget (along with documentation iff existent). Also, when the details-widget shows we don't show the details-string another time with the label. This issue is about not having an option to never show the details-string with the label

**Comment by yume-chan** [comment]
> It is the designed and correct behaviour to show details-string in the details-widget (along with documentation iff existent). Also, when the details-widget shows we don't show the details-string another time with the label.

@jrieken In my second screenshot there is **neither** details-widget **nor** inline label.

**Comment by jrieken** [comment]
The setting for next insiders is `editor.suggest.showInlineDetails`

**Comment by RMacfarlane** [comment]
@jrieken I'm having trouble reproducing the original behavior, when are inline details shown? Even if I clear out all of my settings, when I trigger suggest on the code above, I don't see it:
<img width="498" alt="Screen Shot 2020-12-02 at 5 14 08 PM" src="https://user-images.githubusercontent.com/3672607/100951252-0c073c80-34c3-11eb-9ec9-d54e82d76d5b.png">

**Comment by jrieken** [comment]
The original behaviour depends on the TS version but you might have noticed that many symbols show details when being selected - given the dedicated details widget doesn't show

**Comment by yume-chan** [comment]
@RMacfarlane See my [comment](https://github.com/microsoft/vscode/issues/109690#issuecomment-720355872), press <kbd>Ctrl</kbd> + <kbd>Space</kbd> to make the inline detail appear, otherwise it's completely hidden.
