### ISSUE TITLE
Suggest widget shows up randomly

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#109634]
- Cursor up or down a line, landing at the end of a word
- The suggest widget appears

![Oct-28-2020 18-42-54](https://user-images.githubusercontent.com/323878/97515052-6bff4600-194d-11eb-99bd-70e2d9b23f41.gif)

This reproes totally consistently for me, but I was editing for a while today without noticing it, so I don't know whether I did something else to make it happen

**Comment by jrieken** [comment]
Likely caused by being able to arrow key left/right when completions show.

**Comment by jrieken** [comment]
Steps: 

* have the two lines below
* trigger suggest at end of line 1
* repeatedly press arrow right and see how widget reappears at word ends

```
console.log
console.log
```

**Comment by jrieken** [comment]
Thanks @roblourens 👏
