### ISSUE TITLE
japanese IME doubles input

### ISSUE THREAD

**Issue by andrearicci** [microsoft/vscode#109604]
Issue Type: <b>Bug</b>

I'm working on a html file. Whenever I try to input some japanese text with the system IME, if I choose one of the drop-down options it's ok, but if I just click to accept my input then it's duobled、Eg I write はりねずみ, but when I muose-click to accept it, on screen it appears はりねずみはりねずみ.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (20.34GB free)|
|Process Argv|--crash-reporter-id 9cec1758-4ca3-4415-aa0a-81060dbdf87b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
vscode-markdownlint|Dav|0.37.2
snippet|dev|1.0.1
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.1
ftp-simple|hum|0.7.5
vscode-edit-csv|jan|0.4.2
svg|joc|1.4.0
nim|kos|0.6.6
vs-color-picker|lih|1.0.0
rainbow-csv|mec|1.7.1
code-beautifier|mic|2.3.3
remote-wsl|ms-|0.50.1
cpptools|ms-|1.0.1
LiveServer|rit|5.6.1
tabnine-vscode|Tab|3.1.5
jinja|who|0.0.8

</details>

**Comment by rebornix** [comment]
I'm not able to reproduce this issue, what I tried

* open a HTML file
* type `konnichiwa`
* click in the editor to accept

@andrearicci could you please share a screen recording (also run "Toggle Screen Cast mode" first) to help me troubleshoot?

**Comment by andrearicci** [comment]
@rebornix hi, here's the screen capture with 3 samples:

- first I input my text and then click in the IME list, and that's ok
- second after typing I click Enter, and that's ok too
- lastly I type then I click with the mouse in the document, outside the IME list, and that action doubles my input.

[https://youtu.be/hBiLhkYU6rs](https://youtu.be/hBiLhkYU6rs)
I have not idea of what "Toggle Screen Cast mode" is. Sorry.

**Comment by andrearicci** [comment]
ok, not happening any more
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
