### ISSUE TITLE
The ANSI 'hidden' color code does not seem to be supported in the terminal

### ISSUE THREAD

**Issue by kretschmannj** [microsoft/vscode#109615]
Issue Type: <b>Bug</b>

It doesn't appear that the 'hidden' ANSI escape is supported in the VSCode terminal.  Specifically, I'm running some JS code (NodeJS) and doing a console.log command using the 'hidden' color code sequence but the text is displaying in the default font/color rather than being hidden.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.2.0
uniform-dark-theme|sae|1.5.0

(3 theme extensions excluded)

</details>

**Comment by Tyriar** [comment]
It's definitely supported:

![image](https://user-images.githubusercontent.com/2193314/97508371-aca29380-193c-11eb-8276-f9e5f4c53139.png)

You're probably hitting an issue with invisible attribute support in either conpty or the shell you're using since you're on Windows. It looks like Windows Terminal also supports it (running wsl) which uses a newer version of conpty, so it will either come to VS Code over time as Windows gets updated or it might not get fixed if your shell is the one manipulating the sequence.

**Comment by kretschmannj** [comment]
> It's definitely supported:
> 
> ![image](https://user-images.githubusercontent.com/2193314/97508371-aca29380-193c-11eb-8276-f9e5f4c53139.png)
> 
> You're probably hitting an issue with invisible attribute support in either conpty or the shell you're using since you're on Windows. It looks like Windows Terminal also supports it (running wsl) which uses a newer version of conpty, so it will either come to VS Code over time as Windows gets updated or it might not get fixed if your shell is the one manipulating the sequence.

@Tyriar Thanks.  I'm on Windows 10 and my VSCode terminal is set to 'cmd'.  In the 'shell' dropdown I only have 3 choices ...
![image](https://user-images.githubusercontent.com/63016258/97588052-5293e380-19b9-11eb-8481-2e6b4e2b310b.png)
Maybe I need to switch to a different shell in order for the 'hidden' char code to work?

**Comment by Tyriar** [comment]
@kretschmannj if cmd is your main shell I'd recommend using shell launcher here https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher

I can say from experience after delaying so long it was worth learning a little bit of PowerShell to replace the little bit of cmd I needed as PowerShell continued to get updates today.
