### ISSUE TITLE
Smoke test: changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109644]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=92259&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=6ba55b26-6502-59ae-6c43-7e580fa53cb9&l=78

```
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Preferences
           changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it:
     Error: Timeout: get element '.keybindings-list-container .monaco-list-row.keybinding-item.focused.selected' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)

```

Since it seems to be searching the keybindings editor, I feel this is a keybindings editor problem.

**Comment by sandy081** [comment]
Cant repro it locally. I also do not find any reasons for random-ness. 

Running one more build to make sure if it is really really random.

**Comment by sandy081** [comment]
@joaomoreno This works well with OSS and Insiders build locally. Can we get more info from the build like screenshots to see where it get stuck?

**Comment by joaomoreno** [comment]
@sandy081  Sorry that code is filled with spiderwebs, I am way past the maintenance phase of that.

I've moved all my git smoketest tests to integration tests and never looked back: they are **always** green. I suggest you try to do the same.

**Comment by bpasero** [comment]
Green build, verified.
