### ISSUE TITLE
Bash syntax highlighting breaks after in-line pipe to while-read loop

### ISSUE THREAD

**Issue by aiguy110** [microsoft/vscode#109685]
Issue Type: <b>Bug</b>

Piping input to a `while read` loop inside `$()` breaks syntax highlighting on all lines that follow:
![image](https://user-images.githubusercontent.com/7716397/97606180-debc0000-19e5-11eb-86a6-b99d8e605508.png)
Possibly related issue #106078 indicates this is actually a problem with the grammar VSCode pulls from [here](https://github.com/atom/language-shellscript), but that grammar is not being updated. Posting issue here for tracking purposes. 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (4.47GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/mnt/c/Users/josiah.hunsinger/Projects/proactive-monitoring --remote=wsl+Ubuntu-20.04 --crash-reporter-id c6df1426-188f-4141-b2fc-3af101810a2d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|12.34GB (11.60GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.1
gitlens|eam|10.2.2
python|ms-|2020.10.332292344

</details>

**Comment by alexr00** [comment]
Can you provide a copy/pastable example/

**Comment by aiguy110** [comment]
```
A="Assigning to a variable. Looks nice :D"

THINGS=$(while true; do echo "foo"; done)
B="Still looks nice :)"

MORE_THINGS=$(while read THING; do echo "$THING"; done < <(cat /some/file))
C="So pretty..."

SAME_THINGS=$(cat /some/file | while read THING; do echo "$THING"; done)
X="Oh no... D:"
Y="Syntax highlighting is broken for the rest of the lines in the file"
```

**Comment by alexr00** [comment]
Thanks! As you noted, we get our grammar for shell script syntax highlighting from https://github.com/atom/language-shellscript, but they aren't supporting the grammar anymore. I'll keep this bug around in case we update where we get our grammar from.

**Comment by alexr00** [comment]
Linking and closing in favor of #77675, which tracks considering a new shellscript grammar.
