### ISSUE TITLE
Predictions sticking around in pwsh/ssh

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#109616]
Repro:

1. Connect to SSH windows box (or simulate a slower connection to a windows shell)
2. Open a terminal
3. Hold a key, it's relatively easy to get sticky predictions

![recording (11)](https://user-images.githubusercontent.com/2193314/97486524-c8943e00-1918-11eb-8501-a3d8d7c1dd77.gif)

I know support for Windows isn't the priority, but this is likely also a bug in anything that reprints the line, like oh-my-zsh. It's possible this is already fixed with today's changes.

Version: 1.51.0-insider (user setup)
Commit: bb16786cff3d231facbdcee90741ac25fcffd3ac
Date: 2020-10-28T05:57:23.779Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by connor4312** [comment]
This should be fixed with the coloring improvements; there's a known (uncommon) race that causes this.

/duplicate
