### ISSUE TITLE
${fileDirname} does not resolve correctly

### ISSUE THREAD

**Issue by advikkabra** [microsoft/vscode#109785]
- VSCode Version:Version: 1.50.1 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open a folder with a subfolder containing a C++ file
2. Build the file.

Expected behaviour:
An exe file is formed in the subfolder

Actual behaviour:
An exe file is formed in the workspace root folder

I have isolated the bug in the ${fileDirname} variable, which resolves to the ${workspaceFolder} instead.

Folder structure:
![image](https://user-images.githubusercontent.com/64316822/97778686-d824b880-1b9e-11eb-869f-3a5e946873b4.png)

Tasks.json:
![image](https://user-images.githubusercontent.com/64316822/97778697-f4c0f080-1b9e-11eb-8f8d-fdc2a293f313.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
`${fileDirname}` resolves to the folder of the currently open file. Did you open you example.cpp file first? 

Can you paste this task into your tasks.json, open your example.cpp file, then run this task? What is the output?
```json
        {
            "label": "echo filedirname",
            "type": "shell",
            "command": "echo ${fileDirname}",
            "problemMatcher": []
        }
```

**Comment by advikkabra** [comment]
The output of the echo command is accurate, yet in the other task it still makes the executable outside the subfolder.
![image](https://user-images.githubusercontent.com/64316822/97962296-da735680-1dda-11eb-9a9a-e77427aec7ca.png)

**Comment by alexr00** [comment]
In that case, I think the C++ extension (which provides this task) is resolving `fileDirname` themselves and this is a bug with their resolution of `fileDirname`.

**Comment by advikkabra** [comment]
Thank you for the reply. I will open an issue in the C/C++ extension's GitHub.

**Comment by sean-mcmanus** [comment]
This is bug microsoft/vscode-cpptools#6386 with the C/C++ extension -- we're looking at shipping a patch update tomorrow.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.2
