### ISSUE TITLE
Add menu bar font size modification option

### ISSUE THREAD

**Issue by wannianhong** [microsoft/vscode#109719]
<img width="315" alt="font" src="https://user-images.githubusercontent.com/59216544/97659185-51da7a80-1aa9-11eb-94a3-aeb080967632.PNG">
Add menu bar font size modification option（Change **File Edit Selection** ...)font size

**Comment by sbatten** [comment]
This menubar is controlled by electron which is controlled by your OS scaling. For control of the menu itself, you might try `window.titleBarStyle` `custom`
