### ISSUE TITLE
Visual indication of upload progress when drag&dropping into remote host

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#109743]
When doing a drag & drop of a file into VS Code that is connected to a remote ssh host, there is no visual indication of the file-upload progress. If one tries to use a large file directly in some way (e.g. to untar a tar.gz file) it won't work, since the upload is not complete.

It would be nice with a visual indicator of the upload. Possibly in the file tree view, maybe a small, blue horizontal bar under the filename that gets filled up?

**Comment by isidorn** [comment]
There are already issues about progress in exlporer for long running operatoins.
Closing this as duplicate. You can find them by searching for issues marked with label file-explorer and feature-request

**Comment by thernstig** [comment]
@isidorn I did a search before submitting this. I also tried to search for your suggestion: https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3Afile-explorer+label%3Afeature-request

What am I missing?

**Comment by isidorn** [comment]
Here it is https://github.com/microsoft/vscode/issues/73996
