### ISSUE TITLE
"Find with Selection" no longer works with an empty selection

### ISSUE THREAD

**Issue by adzenith** [microsoft/vscode#109756]
- VSCode Version:
Version: 1.51.0-insider
Commit: 2d8bbc6976748c4b0c5e84be541674b89b9d91e4
Date: 2020-10-30T05:55:22.238Z (13 hrs ago)
- OS Version:
macOS Catalina 10.15.4 (19E287)

Steps to Reproduce:

1. Put the insertion point in the middle of a word
2. Run "Find with selection" (either via keybinding or in the cmd+p menu)

Expected result (and how it's worked since as long as I've used VS Code): the find buffer is filled with the word containing the current insertion point when the selection is empty
Result as of I think yesterday: nothing happens

I use "Find with selection" about a million times a day (slight exaggeration, but only slight 😄) and I immediately noticed this change in behavior. For what it's worth, I used Sublime Text before VS Code and its "Find with selection" also works with an empty selection, so I have about a decade's worth of muscle memory here.

Does this issue occur when all extensions are disabled?
Presumably so, but:
```
$ code-insiders --disable-extensions
Ignoring option disable-extensions: not supported for code-insiders.
```

**Comment by rebornix** [comment]
Thank you sir, good catch ❤️

**Comment by adzenith** [comment]
Thank you!! Such a fast fix :)
