### ISSUE TITLE
Semantic Highlighting can't be disabled

### ISSUE THREAD

**Issue by Mofunkles** [microsoft/vscode#109775]
- VSCode Version: 1.50.1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1.  Find the Sematic Highlighting option in settings.
2.  Set it to false.  It will remain enabled.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Mofunkles** [comment]
Found that this is actually possibly to disable by setting it to... true! the settings still says it is 'enabled' but it is definitely then disabled from looking at the editor.

**Comment by aeschli** [comment]
I can't reproduce the issue. All works fine for for me. `true` enables semantic highlighting, `false` disables it.
To find out if semantic highlighting is there, set the cursor on an identifier and run `Developer: Inspect Editor Tokens and Scopes`.
If you see the semantic color section then semantic coloring is on.
![image](https://user-images.githubusercontent.com/6461412/97867682-9155d080-1d0e-11eb-8c07-57355f5d467a.png)

**Comment by Mofunkles** [comment]
Whoops, yeah dev inspector shows it is working! I guess I was misinterpreting what it was doing so had it backwards in my head whether it was working or not!
