### ISSUE TITLE
Git: Support `Git: Push Tags` command

### ISSUE THREAD

**Issue by aalfiann** [microsoft/vscode#109799]
- VSCode Version: 1.50.1
- OS Version: Ubuntu 18 Bionic Beaver

Steps to Reproduce:

1. Commit
2. Git Create Tag
3. Git Push (Follow Tags)

My code successful push to github, but no tags and releases file created in github.

Does this issue occur when all extensions are disabled?: Yes/No
YES (except GIT extension)

**Comment by joaomoreno** [comment]
Can you show me the full output of `Git: Show Git Output`, as soon as that command is executed?

**Comment by aalfiann** [comment]
Here is the screenshot of the Git Output

**Commit**  
![](https://cdn.imgproxify.com/img/3400fd611717c63257884c105d941fe84128541e7efd4448278d6319abe28565.png)

**Create Tags**  
![](https://cdn.imgproxify.com/img/3400fd611717c63257884c105d941fe8b52ab45a0a637044777cc20b0f5ff291.png)  

**Push (Follow Tags)**  
![](https://cdn.imgproxify.com/img/3400fd611717c63257884c105d941fe81fce12d13f226d16fa4686af2342ed23.png)  


You can check my github there is no tags and releases file created at here >> https://github.com/aalfiann/fastify-fullstack-skeleton

**Comment by aalfiann** [comment]
Mirror image:
- Commit : https://i.imgur.com/KcvejSH.png
- Create Tags: https://i.imgur.com/UAhw9Ya.png
- Push (Follow Tags): https://i.imgur.com/01kmPTU.png

**Comment by joaomoreno** [comment]
What git version do you have installed?

**Comment by aalfiann** [comment]
Git 2.17.1

Is that too old?

**Comment by joaomoreno** [comment]
Does it fix it if you upgrade git? https://git-scm.com/

**Comment by aalfiann** [comment]
I've already update to Git 2.29.2 but still not work.

**Comment by joaomoreno** [comment]
If you run `git push --tags`, does that push that tags?

**Comment by aalfiann** [comment]
![](https://cdn.imgproxify.com/img/3400fd611717c63257884c105d941fe88c917bd3dab2c22491255a7389f43ee0.png)

yes it will works. i already know it.
but my issue is about this feature, I like to using this command shortcut, and actualy in vscode version 1.49 still working.
![](https://cdn.imgproxify.com/img/3400fd611717c63257884c105d941fe86d13a42b455c320429be5bb55f20ee4d.png)

**Comment by joaomoreno** [comment]
Yeah... so `--follow-tags` isn't the same as `--tags`, so we might need a `Git: Push Tags` command.
