### ISSUE TITLE
Windows explorer icons should be updated with the icons for the current VS Code file icon theme

### ISSUE THREAD

**Issue by akhilesh-balaji** [microsoft/vscode#109742]
I have new icons for the VS Code file explorer, the material icon theme as seen [here](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme).

However, the icons of files in my windows explorer are different, and some file types are not supported. It would be nice to have the new icons of VS Code file explorer in my windows explorer as well. Like it is currently, these icons could simply be overlayed on the existing document icon:
![image](https://user-images.githubusercontent.com/69246693/97720501-5a08d900-1aee-11eb-95cb-cad8679aa442.png)

Here's a rough mockup of what the file icon might look like with the material icon theme in use:
![icons](https://user-images.githubusercontent.com/69246693/97721823-eff13380-1aef-11eb-8402-a380299afde9.png)

For any other icon theme, the icons in the middle of the "document" white icon would simply be replaced with the new ones.

**Comment by misolori** [comment]
Unfortunately this is not possible as these icons need to be part of the build process to be compiled.
