### ISSUE TITLE
Regex Replace not working for look-behind expression matching a newline

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode#109791]
- VSCode Version: 1.50.1
- OS Version: Win 2004
- Does this issue occur when all extensions are disabled?: Yes

## Steps to Reproduce

1. Open a new tab.
2. Fill it with the following contents:
   ```
   1
   2 3
   4 5
   ```
3. Open the Replace dialog and set the following parameters:
   - Find: `(?<=\n)\d`
     * Regex: true
     * Only entire words: false
     * Case sensitive: false
   - Replace: `0`
4. Press the Replace button.

### Expected behavior
Whenever the Replace button is clicked, `2` respectively `4` from the file is replaced with `0`.

### Actual behavior
`2` and `4` are found correctly, however, no replacement is performed.

Still, note that the following things work as expected:
- Use Replace All instead.
- Replace works with `(?<= )\d` (no newline in look-behind expression) to replace `3` and `5`.
- Replace works with `\n\d` (no look-behind expression) to replace `2` and `4`.

**Comment by rebornix** [comment]
Lookbehinds will come once v8 implements them and there is nothing we can do from our end.

**Comment by ArturoDent** [comment]
Umm, vscode does support lookbehinds - see https://github.com/Microsoft/vscode/issues/68004

**Comment by LinqLover** [comment]
Reopen?
