### ISSUE TITLE
Update editor mode while changing buffer

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1097]
Have a file without ending but this first line

```
#!/usr/bin/env node
```

it should be associated to JavaScript.

**Comment by jrieken** [comment]
@bpasero This is still the old world, no clue that's the API are?

**Comment by jrieken** [comment]
This relates to #703 which must also know this during FS eventing phase.

**Comment by bpasero** [comment]
Cannot reproduce:

![image](https://cloud.githubusercontent.com/assets/900690/11651791/b728141c-9d93-11e5-99b2-424137d4bcc3.png)

**Comment by bpasero** [comment]
The thing that does not work (yet) is updating the editor live or during the session. So currently you need a reload or pick the mode from the mode picker.

**Comment by jrieken** [comment]
yeah, that's what I saw

**Comment by bpasero** [comment]
ok, fair (known) issue

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
