### ISSUE TITLE
TypeScript compile errors stop being reported when multiple Index files are open

### ISSUE THREAD

**Issue by bdoss** [Microsoft/vscode#10975]
- VSCode Version: 1.4
- VSCode Insiders Version: 1.5
- TypeScript Versions: 1.8.10, 2.0
- OS Version: Windows 10

Steps to Reproduce:

Open multiple tabs named Index.ts(x). Compile errors and intellisense only appear to function properly in the first tab opened. Only appears to impact files named Index.ts/Index.tsx from what I am able to reproduce reliably.

Source: https://github.com/bdoss/tsserver-bug

![bug steps](https://dl.dropboxusercontent.com/s/0pe2rgt52wnw4qu/tsserver-bug-steps.gif)

**Comment by waderyan** [comment]
@bdoss thank you for opening this issue and for creating the easy to understand gif! I am going to migrate this to the TypeScript language service repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10559
