### ISSUE TITLE
EDITING PROBLEM. :(

### ISSUE THREAD

**Issue by Github2256** [microsoft/vscode#109759]
Issue Type: <b>Bug</b>

HELLO :( am unable to delete a single letter from my code i don't know why but please if you see this,
would you mind fixing this problem.
:(((

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.25GB free)|
|Process Argv|--crash-reporter-id df82bdea-5997-4cbf-afe5-4bb5b07b5774|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.12
python|ms-|2020.10.332292344
debugger-for-chrome|msj|4.12.11
vim|vsc|1.17.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Especially without vim.

Also do you see any read-only modifiers on files? Do you have any custom keybindings that involve delete key?

**Comment by Github2256** [comment]
actually it is fixed now.
am just wondering, since am new at coding in Github can it allow me to see what i coded in vscode like see the game am making or do i need something else.
any help is appreciated :)
