### ISSUE TITLE
Running `code .` on WSL will try to download an outdated version of VSC

### ISSUE THREAD

**Issue by Newbie012** [microsoft/vscode#109737]
- VSCode Version: 1.50.1
- OS Version: Windows 10 [Version 10.0.19041.572]

Steps to Reproduce:

Video - https://www.loom.com/share/fa3419a315e84bc2b307db4feb47ad7f

1. Open VSC
2. Download Remote - WSL (v0.50.1)
3. Go to WSL terminal
4. Type `code .`
5. Get the following message:

```
Updating VS Code Server to version 2af051012b66169dde0c4dfae3f5ef48f787ff69
Removing previous installation...
Installing VS Code Server for x64 (2af051012b66169dde0c4dfae3f5ef48f787ff69)
Downloading: 100%
Unpacking: 100%
Unpacked 2341 files and folders to /home/eliya/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69.
```
6. See release notes of August 2020 update (v1.49 - previous version) and "Disconnected from WSL":
![image](https://user-images.githubusercontent.com/10504365/97705727-37aa9780-1abd-11eb-9ab2-a6ea4099a67d.png)
![image](https://user-images.githubusercontent.com/10504365/97705743-3d07e200-1abd-11eb-9e17-a354677ccad3.png)
![image](https://user-images.githubusercontent.com/10504365/97705761-42fdc300-1abd-11eb-9db4-30cc2da4e9a5.png)
![image](https://user-images.githubusercontent.com/10504365/97705835-5e68ce00-1abd-11eb-8619-535d417ce959.png)

If I try to downgrade the Remote -WSL extension, it will work. If I try to open a folder not by `code .` it will work as well.

Does this issue occur when all extensions are disabled?: No (and the irony is that I need the `Remote - WSL` extension installed.

**Comment by Newbie012** [comment]
I can confirm that none of the vscodebot suggestions are similar.

**Comment by Newbie012** [comment]
In case you want to see a full reproduction - 
https://www.loom.com/share/feae4011711f4772b4c5a69b148ef7ab

**Comment by aeschli** [comment]
In the WSL shell, can you do a `which code`? That will point into the VSCode Windows install that is on the WSL PATH which normally is inherited from the Windows PATH. The server version that is downloaded will match the version of that install.
Is that install still in use and up-to-date?
Maybe you ended up having two VScode installations on your machine (user and global). I suggest to uninstall them both, install only one and check the PATH.

**Comment by Newbie012** [comment]
You're correct. I had two installations of VS Code. Once I removed one of the folders, `which code` has pointed to the other installation path. Thanks!
