### ISSUE TITLE
Explorer not focused if no sections expanded

### ISSUE THREAD

**Issue by SaschaCowley** [microsoft/vscode#109700]
- VSCode Version: 1.50.1 (system setup)
- OS Version: Windows 10x64 Version 10.0.19042.572

Steps to Reproduce:

1. Collapse all the sections in the explorer sidebar.
2.Focus another area of VS Code, such as the editor.
3. Try using Ctrl+Shift+E to focus the explorer.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
@isidorn I pulled the changes and tried this and when I use the above steps, I don't see it focusing. Please let me know if I'm doing something wrong.
![recording (21)](https://user-images.githubusercontent.com/29464607/97741679-59e1ec80-1aa0-11eb-9496-1949b365143a.gif)

**Comment by isidorn** [comment]
@meganrogge thanks a lot for trying it out.
I just tried also with newest VS Code insdiers and out of source and for me it works just fine.
Do you still see this not working with latest vscode insdiers

@SaschaCowley did you also get a chance to try this out?

**Comment by rzhao271** [comment]
I didn't even know this shortcut was a thing.
It works in the latest Insiders, thanks!

**Comment by isidorn** [comment]
@rzhao271 thanks for verifying!
