### ISSUE TITLE
Not Getting Auto Information

### ISSUE THREAD

**Issue by ShlokJaiswal1** [microsoft/vscode#109777]
When I go to type something it dosen't completes itself automatically nor does it shows the options of what we can write .
Like I press P or any other letter it is not showing me the drop-down list of options
and I have to write everything myself. so, what's the use Visual Studio then I can go to any other editor too but I like Visual Studio Please Fix This Problem of Mine.

**Comment by Splatterxl** [comment]
```
CTRL+SPACE
```
opens intellisense
