### ISSUE TITLE
The extension manager should display to which marketplace it connects 

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#109773]
The extension manager should display to which marketplace it connects.

Otherwise, countless users will continue to complain about the manager's download counter and other things since some Linux distributions have begun to use `open-vsx.org` as their VS Code package's primary marketplace. 

See #107997.

**Comment by sandy081** [comment]
VS Code officially supports only VS Code Marketplace - https://marketplace.visualstudio.com/vscode and there is not support to switch or use different Marketplaces. Archlinux is repackaging VS Code with custom marketplace, so I would recommend to ask Archlinux to add this support.
