### ISSUE TITLE
New branch not visible

### ISSUE THREAD

**Issue by DattatreyaDash** [microsoft/vscode#109797]
Issue Type: <b>Feature Request</b>

Once the code is checked out from Git repository having 2-3 branches and then suppose a new branch is added directly in Git repository, the newly created branch is not visible under VS Code branch change option (bottom left side corner). The branch is not visible even after synchronization with the master branch.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
Does the branch appear after closing and opening VS Code?
