### ISSUE TITLE
100% CPU Usage - Code Helper (renderer)

### ISSUE THREAD

**Issue by TimSchumann** [microsoft/vscode#109746]
Issue Type: <b>Bug</b>

https://github.com/microsoft/vscode/issues/87509

Pretty much exactly this issue. Wasn't even using VS code it was just sitting in the background doing nothing after a fresh install.

I was browsing in firefox, and had 1Password open, and Dropbox in the background. That's about it for applications as this system is less than a week from a clean OS install.

Only thing I can think of that I did recently to change anything on the system, was I plugged in the charging adapter.

Let me know if you need any further info from me.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (6.90GB free)|
|Process Argv|--crash-reporter-id aba55653-22c6-4bf7-8b56-ebd436138b52|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by TimGr** [comment]
Hi, I can confirm this. I also have up to 170% CPU usage. And VS Code is only open and running in the background.

**Three things I could already determine:**
- The problem does not occur if you open a new VS Code window and no folder is open
- It occurs in a large project/folder, even with Git disabled
- The problem can also be reproduced with the Insider version


---

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	    98	  2209	code main
    0	    49	  2212	   gpu-process
    0	    25	  2214	   utility
    0	   246	  2215	   window (cms-app)
    0	    74	  2234	     extensionHost
    0	    25	  2240	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=2234
    0	    49	  2244	       electron_node tsserver.js 
    0	   106	  2245	       electron_node tsserver.js 
    0	    25	  2246	         electron_node typingsInstaller.js typesMap.js 
  162	  1343	  2235	     watcherService
    0	    98	  2239	   shared-process
    0	     0	  2267	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    57	  2265	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (cms-app)
|    Folder (cms-app): more than 20570 files
|      File types: js(9511) html(3467) png(1253) php(744) json(649) md(452)
|                  css(276) docx(235) _word2013(169) txt(161)
|      Conf files: package.json(5) grunt.js(1) gulp.js(1) webpack.config.js(1);
```

</details>
Extensions: none

**Comment by jrieken** [comment]
@bpasero for the watcher service
