### ISSUE TITLE
Bad Auto-Format on EJS

### ISSUE THREAD

**Issue by elad-m** [microsoft/vscode#109796]
I was writing the following lines on a .ejs file:
```
<script>
    const mapToken = '<%-process.env.MAPBOX_TOKEN%>';
    const campground = <%-JSON.stringify(campground) %>;
</script>
```

The '<%-...' on the third line would become '<% -...' whenever I was saving, i.e. white-space is added between the '%' and the '-', resulting in bad ejs syntax. This would not happen in other lines such as this for example:
`<%- include('../partials/navbar')%>`

nor does it happen in the second line in the code at the beginning. 

In addition, it also marks said third line with red-squigly line below the '<' and '>' (I think it is below it) no matter if with or without the white space.

I should clarify that the code that I cited at the beginning works fine.

Good luck and have a nice day!

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.83GB free)|
|Process Argv|--crash-reporter-id a176b953-e9f9-4a02-9f22-906d1529b58a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
code-spell-checker|str|1.9.2

(1 theme extensions excluded)

</details>

**Comment by yume-chan** [comment]
Sadly Code never supported ejs nor know how to format it.

**Comment by aeschli** [comment]
Yes, sorry, you need to look out for a EJS extension that is aware of EJS tags.
