### ISSUE TITLE
The header of the details widget of suggests is not word-wrapped sometimes

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#109717]
Version: 1.51.0-insider
Commit: 2ee8b8c645ec8ab54304bacae7aa979c1d9c647a
Date: 2020-10-29T06:00:13.428Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Open a TypeScript file.
2. Type `vscode.window.` and open suggests and details with `Ctrl-Space`
3. The header of the details widget of a suggest 
`vscode.window.onDidChangeActiveTerminal` is not word-wrapped.
4. If we want to see the whole header, we have to make the detail ridiculously wider.

Does this issue occur when all extensions are disabled?: Yes

<img width="2536" alt="スクリーンショット 2020-10-30 12 53 19" src="https://user-images.githubusercontent.com/10665499/97658239-2f4b6000-1aaf-11eb-9d7b-840855f88a04.png">

Still not enough wide.

<img width="2536" alt="スクリーンショット 2020-10-30 12 53 42" src="https://user-images.githubusercontent.com/10665499/97658249-383c3180-1aaf-11eb-86bf-c1c20d03ce61.png">

**Comment by jrieken** [comment]
That's on purpose. You can read more here: https://github.com/microsoft/vscode/issues/99370#issuecomment-717238060. In short, we auto wrap unless the extension provided multiples lines for the details in which case we don't auto wrap so that we don't interfere with its "ascii art". Tho, we might wanna extend that to says "contains new lines and leading whitespace"

**Comment by jrieken** [comment]
Done. The details/header will now "break to fit lines" unless the extension provided new lines followed by intentation.

**Comment by MartinGC94** [comment]
I think this change broke the fix for the problem I mentioned here: https://github.com/microsoft/vscode/issues/29126#issuecomment-714782628 where linebreaks from the extension aren't shown like they should.
