### ISSUE TITLE
The cursor lags when typing/selecting/deleted text quickly if the editor.cursorSmoothCaretAnimation option is set to true

### ISSUE THREAD

**Issue by anay-p** [microsoft/vscode#109787]
Issue Type: <b>Performance Issue</b>

The cursor lags consistently about 3 to 4 characters behind or in front of the text depending on what action is being carried out. There are also sometimes spikes of lag where it can be upto 7 to 8 characters. Have a look:

![cursor issue](https://user-images.githubusercontent.com/59292344/97778917-a280cf00-1ba0-11eb-96d1-adcd9c2b65b5.gif)

Ideally, there should not be any lag at all.

I recently started using VS Code so this issue has been there from the beginning. I have found that I had set the  editor.smoothScrolling setting to true, which when set to false, reduces the lag to 1-1.5 characters, which is the same amount of lag experienced when all extensions are globally disabled and all global (and local) settings except editor.cursorSmoothCaretAnimation are commented out. Have a look:

![cursor issue 2](https://user-images.githubusercontent.com/59292344/97779253-d826b780-1ba2-11eb-8f86-00475cc72459.gif)

This lag is present consistently, regardless of whether I just started VS Code or whether it has been running for a while.

Steps to Reproduce:
1. Open VS Code
2. Set both editor.cursorSmoothCaretAnimation and editor.smoothScrolling to true. The lag is present.
3. Now set the editor.smoothScrolling to false. The lag reduces but isn't gone.

I wrote a question and provided my own answer regarding the same on Github. Here's a [link](https://stackoverflow.com/a/64621268/14224870) to that.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.95GB (1.95GB free)|
|Process Argv|--crash-reporter-id f6cfc040-744d-4db3-9a0b-1ae8b5953df6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    68	  9572	code main
    0	   142	   216	   window (test.py - e-Shopping Sim - Visual Studio Code)
    0	    13	  6316	     watcherService 
    0	     6	  6220	       console-window-host (Windows internal process)
    0	    85	 16940	     extensionHost
    0	    36	  2296	       c:\Users\Anayp\.vscode\extensions\ms-python.python-2020.10.332292344\languageServer.0.5.59\Microsoft.Python.LanguageServer.exe
    0	     5	 15532	         console-window-host (Windows internal process)
    0	    75	 11100	       "C:\Users\Anayp\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Anayp\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=16940
    0	   148	   820	   gpu-process
    0	    80	  3448	   window (Issue Reporter)
    0	    57	  5612	   shared-process
    0	    27	 11424	   utility
    0	    14	 11608	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (test.py - e-Shopping Sim - Visual Studio Code)
|    Folder (e-Shopping Sim): 22 files
|      File types: png(10) py(3) sql(3) pyc(3)
|      Conf files:;
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|11.4.0
vsc-material-theme|Equ|33.0.0
code-runner|for|0.11.1
intellij-idea-keybindings|k--|0.2.41
vsc-python-indent|Kev|1.12.0
kite|kit|0.133.0
python|ms-|2020.10.332292344
remote-wsl|ms-|0.50.1
autodocstring|njp|0.5.3
material-icon-theme|PKi|4.3.0
vscode-paste-and-indent|Rub|0.0.8
errorlens|use|3.2.3
vscodeintellicode|Vis|1.2.10

</details>

**Comment by AlexDev2020** [comment]
Is there any progress on this task? A little annoying this lag.

**Comment by huantianad** [comment]
I'm still getting this issue, for me it may be an issue with wayland since it seems to work fine with xwayland.

**Comment by alexdima** [comment]
After receiving more feedback (see #168857), I've pushed a change where there will be 3 possible values for `cursorSmoothCaretAnimation`. You can now use `explicit` to have it that the cursor animates only when it is set via mouse or via arrow keys, etc. and not when typing / deleting.
