### ISSUE TITLE
Support allowlisting of snippets from extensions

### ISSUE THREAD

**Issue by dantman** [microsoft/vscode#109705]
There are a decent collection of snippet extensions that have a variety of useful snippets. However these extensions also often contain many snippets you will never use.

As a result if an extension contains 120 snippets but you only need 30 of them, your intellisense is full of 90 snippets you'll never ever need. Sometimes multiple extensions will also offer the same thing (e.g. there's a "react" snippets extensions that overlaps with both a "react hooks" snippets extension and general js/ts snippet extensions) meaning the snippet you want isn't always the only thing that shows up when you fully type it out.

This is also a bigger issue because in some contexts (eg. an object literal in TS where you want to list/expand properties) the context seems to be a little ambiguous to vscode and as a result you get a large selection of your snippets mixed in with TS interface properties.

I think a good solution to these issues would be to make it possible to explicitly allowlist/whitelist the snippets provided by snippet extensions. By default all snippets for an extension can be made available. But if the user has provided a allowlist for an extension in their settings, then non-allowlist snippets from that extension should not show up in intellisense.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Afeature-request+label%3Asnippets
