### ISSUE TITLE
natvis does not support enum class template argument types

### ISSUE THREAD

**Issue by JessyDLHatch** [microsoft/vscode#109784]
Issue Type: <b>Bug</b>

Debugger does not display custom natvis visualizer when any of the template type arguments is an enum class. This does not happen in Visual Studio, but does in VSCode.

Given the following basic example code:

```
enum class bar_enum {};

template <bar_enum E = bar_enum{0}>
class foo
{
  public:
	int value{5};
};
```

accompanied by the following natvis
```
<?xml version="1.0" encoding="utf-8"?> 
<AutoVisualizer xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010">
  <Type Name="foo&lt;*&gt;">
    <DisplayString>{{ size=0 }}</DisplayString>
    <Expand>
    </Expand>
  </Type>
</AutoVisualizer>
```

You'll notice this works in Visual Studio, but not in VSCode.

Expected:
Debugger would use the natvis correctly and display the string. Note that any other template arg type does work, the moment an enum class is added is when it breaks.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

**Comment by weinand** [comment]
Please note that VS and VS Code are independent products.

What debugger extension are you using?

**Comment by JessyDLHatch** [comment]
> What debugger extension are you using?

`gdb`, forgot to mention this was on WSL2. I'd try on `lldb`, but on MacOS natvis refuses to work altogether, though I saw some reports about that already from last year.

> Please note that VS and VS Code are independent products.

I'm aware, just showing discrepancy in expected behavior vs actual, showing that the example does respect the expected rules of the natvis format.

**Comment by weinand** [comment]
natvis support must come from the debugger extension.
