### ISSUE TITLE
linter toggle

### ISSUE THREAD

**Issue by dl90** [microsoft/vscode#109792]
Hi, I'd like to suggest a linter toggle for vscode.

```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

npm packages -global:

- eslint@7.12.1
- standard@14.3.4

extensions:

```
Name: ESLint
Id: dbaeumer.vscode-eslint
Version: 2.1.13
```
```
Name: StandardJS - JavaScript Standard Style
Id: chenxsan.vscode-standardjs
Version: 1.3.0
```

I have standardjs installed globally and use it as my go to linter but it conflicts when I work on projects with ESlint.

<img width="776" alt="Screen Shot 2020-11-01 at 9 37 21 AM" src="https://user-images.githubusercontent.com/48544754/97810188-f3d3a180-1c26-11eb-9c11-046862369c97.png">

Currently, the way I get around this is by specifying "eslint.format.enable", "standard.enable", in settings.json.
It would be nice if there's a visual toggle for switching between different linters you have installed on the status bar.

<img width="605" alt="Screen Shot 2020-11-01 at 9 39 29 AM" src="https://user-images.githubusercontent.com/48544754/97810191-f8985580-1c26-11eb-9b37-7bbffc3a468a.png">

**Comment by sandy081** [comment]
You can disable one of the extensions from extensions view.
