### ISSUE TITLE
grid-template-area not working

### ISSUE THREAD

**Issue by omar442** [microsoft/vscode#109772]
Issue Type: <b>Bug</b>

I've been using the function grid-template area and i have no problem but Itry to use again but it won't show what i was expecting instead it shows all piled up

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (1.17GB free)|
|Process Argv|--crash-reporter-id 12e61cb4-7594-4cae-9fc7-88d746bf0b92|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-babel-coloring|dza|0.0.4
python|ms-|2020.10.332292344
printcode|nob|3.0.0
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by joaomoreno** [comment]
>  function grid-template area

What do you mean by this? Can you share a screenshot of this feature?
