### ISSUE TITLE
VS Code setup removes js files association  with Windows Scripting Host (WSH)

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/vscode#109793]
https://github.com/microsoft/vscode-cpptools/issues/6340#issuecomment-714919398

Thank you

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by DBJDBJ** [comment]
yes that is also reported by me .. the same issue

**Comment by joaomoreno** [comment]
Same reply as https://github.com/microsoft/vscode/issues/108847#issuecomment-711432346
