### ISSUE TITLE
Word wrap for variables in Watch view

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode#109707]
Sometimes the value of the variables is too long and it doesn't fit on the Watch view. It'd be nice to have a word wrap option so it can be shown on multiple lines. An horizontal scroll bar would also be useful.

![image](https://user-images.githubusercontent.com/14098140/97642604-d7571f80-1a02-11eb-8968-6fd616f67e36.png)

**Comment by isidorn** [comment]
We will not do this.
You can drag and drop the WATCH view to the horizontal panel for more space.

**Comment by qlub53** [comment]
> We will not do this.
> You can drag and drop the WATCH view to the horizontal panel for more space.

This sucks. Horizontal dragging makes very little sense.
The WATCH view ought to show complete variables without users having to worry about space on screen. Text wrapping is and is the only way to go. I totally don't understand the denial of this feature.

**Comment by weinand** [comment]
I don't agree: by dragging the Watches view into another area it will gain a lot of horizontal space as you can see on this screenshot:
 
<img width="2560" alt="2021-07-11_20-35-32" src="https://user-images.githubusercontent.com/1898161/125206495-e972a880-e287-11eb-896a-9b10bdb8d011.png">

If you don't like that approach, please feel free to submit a Pull Request implementing what you are looking for.

**Comment by xoelop** [comment]
What if it's a long string that doesn't fit the screen, even horizontally? The only viable way to watch it if it's being changed iteratively is by printing it in each step of a loop with the debug console. That's too cumbersome

**Comment by profPlum** [comment]
> I don't agree: by dragging the Watches view into another area it will gain a lot of horizontal space as you can see on this screenshot:

@xoelop is right though, this is the first time I've used watches and I've already got a long expression with an even longer regex string value. There is literally no way for me to view the output with watches.

Why don't you just make existing word wrap option apply globally (i.e. including watched expressions)? It's like the most basic text editor/viewer feature.

**Comment by maribox** [comment]
It also would be amazing to be able to view variables that include line breaks as a string with multiple lines instead of with escaped characters.

**Comment by mjec** [comment]
For folks like me who landed here from search, it looks like this is now on the backlog in #177733

**Comment by Qlub53** [comment]
> For folks like me who landed here from search, it looks like this is now on the backlog in #177733

🎉🎉🎉! That's right!
Finally 1⃣️ less weakness compared to JetBrains products!
