### ISSUE TITLE
VS Code scroll lags on macos

### ISSUE THREAD

**Issue by olegKusov** [microsoft/vscode#109795]
- VSCode Version: 1.50.1
- OS Version: 14.15.7

Steps to Reproduce:
1. open vs code
2. scroll file

I created video example (vs code scroll vs nova panic editor (https://nova.app))
https://youtu.be/-U3auTvDKN0
P.S. I don't have installed extensions and used clean vs code installation.

**Comment by alexdima** [comment]
I'm sorry, I'm not noticing anything wrong in the video. Do you perhaps have configured `"editor.smoothScrolling": true` or other scrolling related settings?

**Comment by olegKusov** [comment]
> I'm sorry, I'm not noticing anything wrong in the video. Do you perhaps have configured `"editor.smoothScrolling": true` or other scrolling related settings?

video can't really show all lags. in real life there are more. It's not lags its like microfreeze scrolling. And I really don't understand why you don't see difference. Even on my video you can see it.

**Comment by alexdima** [comment]
@olegKusov I watched the video again a couple of times and there is nothing obvious to me, sorry about that. But I'm happy to try to troubleshoot this. Could you try to create a CPU profile of the renderer? We could try to see if there's something standing out. Steps here -- https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by sonnykt** [comment]
I also get the same issue. VS Code has recently become laggy when scrolling, regardless of `editor.smoothScrolling`, even when all extensions are disabled and just a small text file is opened.

My VS Code version
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (2 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0 (Catalina 10.15.7)
```

CPU Profile
[CPU-20201127T133350.cpuprofile.zip](https://github.com/microsoft/vscode/files/5605686/CPU-20201127T133350.cpuprofile.zip)

**Comment by alexdima** [comment]
@sonnykt Thank you for the CPU profile, but there is nothing there that stands out, everything looks normal.

@deepak1556 Do you have more ideas on how to investigate this mouse wheel slow-down on macOS ?

**Comment by sonnykt** [comment]
@alexdima I made a side by side comparison video between VSCode and Sublime Text
https://www.dropbox.com/s/a4bgg1851zxwy74/vscode-sublime-scroll.mp4?dl=0

**Comment by olegKusov** [comment]
> @alexdima I made a side by side comparison video between VSCode and Sublime Text
> https://www.dropbox.com/s/a4bgg1851zxwy74/vscode-sublime-scroll.mp4?dl=0
> 
> I have tried to downgraded VS Code but no luck, even with versions from last year. It may be a compatibility issue of Google Chrome with the latest macOS update (Catalina 10.15.7 released in September). I've just noticed that scrolling on Chrome (Chrome is not my browser though) is also laggy the same way with VS Code.
> 
> **Update**: I reckon that it's the issue with hardware acceleration. When I turn off hardware acceleration, scrolling in Chrome becomes as smooth as expected. Running VSCode with the flag `--disable-gpu` also results in the same effect.

you helped me! thanks

**Comment by olegKusov** [comment]
> @olegKusov I watched the video again a couple of times and there is nothing obvious to me, sorry about that. But I'm happy to try to troubleshoot this. Could you try to create a CPU profile of the renderer? We could try to see if there's something standing out. Steps here -- https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

thank you for helping
