### ISSUE TITLE
Change the encoding file when i open.

### ISSUE THREAD

**Issue by embc89** [Microsoft/vscode#10971]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
@embc89 Can you please give more details about the issue

**Comment by embc89** [comment]
I open an ASP file with ANSI enconding. When i open the file with Visual Code, it changed to UTF-8 format.

**Comment by bpasero** [comment]
@embc89 you can set the encoding either as a setting or from the status bar.
