### ISSUE TITLE
Import from other project to test.component.spec.ts is underlined with red (Angular)

### ISSUE THREAD

**Issue by AnttiTanskanen** [microsoft/vscode#109721]
Issue Type: <b>Bug</b>

1) Create Angular project and another angular project. 
2) Create a reusable service (fe. TestService) to the second Angular project.
3) Add service exports to index.ts file in second Angular project
4) In the first angular project create test.component and test.component.spec.ts test file.
5) create shortcut to the second Angular project in tsconfic.spec.json like the following: "paths": {
      "@app-shared": [
        "projects/second-project"
      ],
      "@app-shared/models": [
        "projects/second-project/models"
      ],
    },
6) In first project's test file try to import { TestService } from '@app-shared';
7) '@app-shared' part is underlined with red but the tests passes. 

Other info:
In component '@app-shared' part is not underlined. It is underlined only in tests.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (7.02GB free)|
|Process Argv|. --crash-reporter-id ddcc5801-386c-4fcd-a2f8-eb6434cce563|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1001.0
gitlens|eam|10.2.2
Angular-BeastCode|Mik|10.0.3
python|ms-|2020.10.332292344
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.3071
JasmineSnippets|xab|1.0.1

</details>

**Comment by mjbvz** [comment]
Can you please share a small sample project that demonstrates the issue?

**Comment by AnttiTanskanen** [comment]
> 
> 
> Can you please share a small sample project that demonstrates the issue?

Sorry, I don't currently have time for that.

**Comment by mjbvz** [comment]
Closing this then as we can't investigate this without simple steps to reproduce
