### ISSUE TITLE
output window encoding error.

### ISSUE THREAD

**Issue by xWulitou** [Microsoft/vscode#10973]
- VSCode Version:1.4
- OS Version:windows 10

Steps to Reproduce:

1. use vscode tasks.json like below:
{
-----------------------------------------------------------
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "cmd",
    "isShellCommand": true,
    "args": ["/c"],
    "tasks": [
        {
            "taskName": "build",
            "args": ["dotnet","build"],
            "isBuildCommand": true,
            "showOutput": "always",
            "problemMatcher": "$msCompile",
            "suppressTaskName": false
        }
    ]
}
------------------------------------------------------------
and launch.json like this:
---------------------------------------------------------
{
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/netcoreapp1.0/DotnetCoreApp.dll",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "externalConsole": false
        }
-----------------------------------------------------------
2. then begin to debug. and output window like this :

'build' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

-----------------------------------------------------------
by the way ,I found the document of tasks.json is not detailed, can u explain to me that how to run several tasks before debug or running .For example, before I run a program ,that I need to tsc the ts code,gulp and build the c# code ,finally running the program.could someone know how to do it.  
![image](https://cloud.githubusercontent.com/assets/9709973/17985455/7598e1ec-6b48-11e6-9b78-f4677c5b5688.png)

**Comment by dbaeumer** [comment]
Dups #3550
