### ISSUE TITLE
Readonly editor hover appears weird for first line

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109776]
![image](https://user-images.githubusercontent.com/900690/97773187-0a59fa00-1b4e-11eb-9e45-3e3e71ecfa1a.png)

(I ran the https://github.com/microsoft/vscode-extension-samples/tree/master/fsprovider-sample for testing this)

**Comment by isidorn** [comment]
This comes from the editor, forwarding to @alexdima
