### ISSUE TITLE
Provision to get a `pickString` dynamically populated in a VSCode task

### ISSUE THREAD

**Issue by ldarshan1991** [microsoft/vscode#109789]
Currently, the task `pickString` is statically populated. ie we need to pre-define the list while writing the task.
However, there are cases, wherein we would like to populate that list dynamically. For example that list should be a list of files in a folder. That list should be populated by the output of `ls` command.

**Comment by ArturoDent** [comment]
This can be done with a `comand` variable in a pickString input to a task.  See the example at https://code.visualstudio.com/docs/editor/variables-reference#_input-variables.  You would need an extension that contributes a command that returns the data you want.  Getting the files in a folder should be pretty easy.

**Comment by ArturoDent** [comment]
I have posted an example extension and task at https://stackoverflow.com/a/64637337/836330

**Comment by alexr00** [comment]
Thanks @ArturoDent, that is the recommend wat to do this.

**Comment by runxel** [comment]
I'm sorry but this not a solution!
Surely this needs to be done natively. You can't expect users to write their own extensions for this trivial stuff!
And this is not something which would be a rarely used feature. I'm not sure what kind of work y'all doing but I need this daily, i.e. calling a external command on a specific module folder in my workspace.

**Comment by ldarshan1991** [comment]
@alexr00 May be this is the way currently. But asking every user of VSCode to write an extension to achieve this not at all great solution. By this you are telling every user of VSCode should become a typescript programmer as well.
I am a C developer and I want to use VSCode for my workflow and if you are asking me to learn typescript or some other language to write my own extension, this doesn't looks to be a good marketing for the product.

I expect some native way to achieve this. I request you to reopen this issue and revaluate the better design to achieve this.

**Comment by juarezr** [comment]
Currently VSCode tasks doesn't have this functionality built-in.

### Alternative Solution

You can install the [augustocdias.tasks-shell-input](https://marketplace.visualstudio.com/items?itemName=augustocdias.tasks-shell-input) and configure an input variable with type `command` calling this extension for populating the pick list.

Follow the following steps:

1. Install the extension with:
   1. Search in the Extensions Sidebar (`Ctrl+Shift+X`) for `augustocdias.tasks-shell-input` and install or
   2. Launch VS Code Quick Open (Ctrl+P), paste the following command, and press enter:
     - `ext install augustocdias.tasks-shell-input`
2. Configure your `task.json` with:
   1. A task with the command you want to execute
   2. Add to the task `args` configuration entry one or more references to input variables like `${input:my_variable}`.
   3. Configure an entry in the `inputs` section with:
      - `id`: use the same variable name defined in task `args` like `my_variable` for `${input:my_variable}`
      - `type`: `command`
      - `command`: `shellCommand.execute`
      - `args`: add an config with the properties: `command`, `cwd`, `env`
3. See the example `task.json` file bellow.

### Example

Example `task.json` file using `augustocdias.tasks-shell-input` extension:

``` json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Dynamically Populated Task",
            "type": "shell",
            "command": "echo",
            "args": [
                "'${input:my_dynamic_input_variable}'"
            ],
            "problemMatcher": []
        }
    ],
    "inputs": [
        {
            "id": "my_dynamic_input_variable",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "command": "ls -1 *.*",
                "cwd": "${workspaceFolder}",
                "env": {
                    "WORKSPACE": "${workspaceFolder[0]}",
                    "FILE": "${file}",
                    "PROJECT": "${workspaceFolderBasename}"
                }
            },
        }
    ]
}

```
