### ISSUE TITLE
Unwanted HTML tag highlight since recent updates

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#109783]
Since a recent update (sorry I didn't keep track of when precisely it started) HTML tags are highlighted (a dark red background color is displayed) when I click on them, except on self-closing tags. The highlight disappears when I press escape, then reappears if I click anywhere else in the tag name. It does it with every default color themes. I tweaked `workbench.colorCustomizations` and `editor.tokenColorCustomizations` and disabled all extensions but it's still there and I cannot find from where it comes. There's no relevant information in the Problems panel nor in the Inspect Tokens/Scopes. The color does not appear in the developer tools inspector.

Steps to Reproduce:

1. Click in a non-self-closing HTML tag name.

![bug](https://user-images.githubusercontent.com/9438102/97777613-c4af2880-1b71-11eb-9044-3b7a0a2e96f4.gif)
![Window 000285](https://user-images.githubusercontent.com/9438102/97777662-09d35a80-1b72-11eb-812e-75ebf5c4bb14.png)

---

Does this issue occur when all extensions are disabled?: **Yes**

```
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by aeschli** [comment]
I suspect it's the `wordHighlightBackground`. Try this:
```
	"workbench.colorCustomizations": {
		"editor.wordHighlightBackground": "#ff0000"
	}
```

**Comment by inwardmovement** [comment]
> I suspect it's the `wordHighlightBackground`. Try this:
> 
> ```
> 	"workbench.colorCustomizations": {
> 		"editor.wordHighlightBackground": "#ff0000"
> 	}
> ```

I tried and this setting has no impact

**Comment by aeschli** [comment]
Does it reproduce with all extension disabled?

**Comment by inwardmovement** [comment]
> Does it reproduce with all extension disabled?

Yes it does

**Comment by aeschli** [comment]
Do you have renameOnType enabled? (`"editor.renameOnType": true`).

That adds a color: `editor.onTypeRenameBackground`

**Comment by inwardmovement** [comment]
> Do you have renameOnType enabled? (`"editor.renameOnType": true`).
> 
> That adds a color: `editor.onTypeRenameBackground`

Hooray you found where it comes from! I set it to `#ffffff00` to make it transparent. Thanks!
