### ISSUE TITLE
Using search feature causes crashing frequently

### ISSUE THREAD

**Issue by egucciar** [Microsoft/vscode#10972]
- VSCode Version: 1.4.0
- OS Version: Windows 7

Steps to Reproduce:
1.  Search for something using Find ALL or file selection with CTRL + P
2. Observe frequent crashes as of last update

**Comment by bpasero** [comment]
We do some active changes in this area, wondering if our insiders release makes this experience any better for you?

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by sandy081** [comment]
@egucciar Very sorry to hear that VS Code is crashing. In order to know the root cause for it would you let us know

- How big is the project?
- Do you have a special setup?
- When this happens would you be able to run a CPU profile from the developer tools (help > toggle developer tools) to see where we spend so much time?

Also, did this not happen with the previous release?

**Comment by egucciar** [comment]
Hi all,

I'm sorry to get back to you so late. I was using insiders version which seemed to work better. But now it's crashing again pretty frequently, and not just with search.

1. It is a webpack / nodejs project thats 348 MB in size including node_modules. Not including the node modules, its 1,162 files and 121 folder.

2. I do not have admin rights to my machine, I usually run VSCode with elevated privileges. My only setting besides the default is to save when the window loses focus.

3. Do you want me to run the dev tools while I work to profile VS code as it runs? also i just tried doing that, and the dev console is not opening.

![image](https://cloud.githubusercontent.com/assets/2848185/18494572/e5b75896-79e4-11e6-9556-bd58016a5a19.png)

It did not happen as much in previous releases. I would get crashing maybe once a day. Now it's almost so frequent that I have to consider trying atom (I really dont want to, though)

**Comment by chrmarti** [comment]
Not sure if this is related, but we had to revert our optimization of using 'dir' for the stable release. The insiders builds were using that for a while, maybe that had improved things for you.

**Comment by chrmarti** [comment]
#11037 reported the problem coming back after we reverted that change too. There the problem seems to be some interaction between our file traversal and anti-malware software.

**Comment by egucciar** [comment]
Yes, I have not gotten the chance to code but the other members on my team are reporting that now the insiders version, instead of crashing, stops responding / slows down to a crawl occasionally when interacting with the file system (via search etc)

**Comment by chrmarti** [comment]
@egucciar Is everyone seeing this using Windows 7? Is there a particular process using a lot of CPU time when this occurs? Also on the latest insider builds?

**Comment by chrmarti** [comment]
Is this still an issue?
