### ISSUE TITLE
Can't connect to extensions marketplace

### ISSUE THREAD

**Issue by mrmehi** [microsoft/vscode#109747]
We have written the needed data into
Issue Type: <b>Bug</b>

I've been trying to solve this issue for over a week but yet it's not been fixed (I tried to in other editors they just work fine). Please help me. 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.30GB free)|
|Process Argv|--crash-reporter-id c9c3d6e5-e13a-43e1-8333-c60faab4a77a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.8
es7-react-js-snippets|dsz|3.0.0
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.1
auto-rename-tag|for|0.1.4
python|ms-|2020.9.111407
cpptools|ms-|1.0.1
vsliveshare|ms-|1.0.2740
material-icon-theme|PKi|4.3.0
LiveServer|rit|5.6.1
highlight-matching-tag|vin|0.10.0
vscode-icons|vsc|11.0.0
JavaScriptSnippets|xab|1.8.0

(3 theme extensions excluded)

</details>
 your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please follow the advice from @sandy081 at https://github.com/microsoft/vscode/issues/108456#issuecomment-718770642 and post your results.
