### ISSUE TITLE
Allow filter in quick navigation (Ctrl-Q)

### ISSUE THREAD

**Issue by LucaGabi** [microsoft/vscode#109774]
Now: Ctrl-Q shows quick navigation and no fast jump to some item
Request:  show quick navigation and allow typing letters to jump to an item

![image](https://user-images.githubusercontent.com/37976898/97772285-5c9b1b00-1b4e-11eb-90e7-68c3d8e8dad0.png)

**Comment by chrmarti** [comment]
Have you tried using using `F1` > `View: Open View`?

**Comment by LucaGabi** [comment]
> Have you tried using using `F1` > `View: Open View`?

Thanks! I assigned Ctrl-Q to this command and it dose exactly what I wanted.

I think this can be closed.
