### ISSUE TITLE
Extension API: Fully open preview/half opened file

### ISSUE THREAD

**Issue by fakusb** [microsoft/vscode#109749]
I have an extension and would like to "fully" open an editor that is already open, but only in preview mode (italic file name). So I would like to change the state of an `TextEditor` that is already open as if it was opened with the `preview=false` option in `TextDocumentShowOptions`.

I would also like to check if the current editor is in preview mode or "fully" opened from the API.

(The use case is the [extension for the proof assistant coq](https://github.com/coq-community/vscoq): Source files are processed interactively in the editor and involve "augmenting" each command in the file with the current proof state. Those operations can be quire resource intensive and it would be a shame if the user accidently closes the file (while a lot of 'compilation' work was done in the background that augments the document) because he only opened the file in preview mode).

I know that I probably can disable preview mode all together, but that would only be a workaround, as the preview mode can be handy.

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/60276#issuecomment-524764009 points to a command you may be able to run in order to meet your first need.

**Comment by fakusb** [comment]
Great, as far as I understand, and as far as I can test, this command indeed does what I intended:
`await vscode.commands.executeCommand("workbench.action.keepEditor",editor.document.uri);`
