### ISSUE TITLE
Intellisense results should be LRU sorted

### ISSUE THREAD

**Issue by svillar** [microsoft/vscode#109729]
Issue Type: <b>Feature Request</b>

The autocompletion (intellisense) results would be more useful if  LRU sorted because most of the times developers use the same subset of methods for a given class.

I'm looking for something like what [company-statistics](https://github.com/company-mode/company-statistics) does for emacs.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.8.0-3-amd64

**Comment by jrieken** [comment]
Did try the `editor.suggestSelection` setting?

**Comment by svillar** [comment]
Ah I see. Results are alphabetically sorted but the most recent one is highlighted and becomes the selected one when clicking on enter. I think it's more or less what I was looking for. Thanks!
