### ISSUE TITLE
[regression] Files served by readonly filesystem show double '(read-only)' suffix in titlebar again

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#109733]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/6726799/97700657-1e492180-1aa4-11eb-9396-547a7ccb0680.png)

Previously logged as #79240 and fixed in #79241.

Repro steps are as given in previous issue.

Regression apparently occurred in https://github.com/microsoft/vscode/commit/12cf39dea3c87137d4bc1b96c16c4e0a19bd5122

I will submit a PR.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
Thanks, seems to reproduce in stable already. Open for grab.

**Comment by gjsjohnmurray** [comment]
> 
> 
> Thanks, seems to reproduce in stable already. Open for grab.

@bpasero PR incoming shortly from me.
