### ISSUE TITLE
Some extensions not showing 

### ISSUE THREAD

**Issue by stevedekorte** [microsoft/vscode#109708]
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (2 wks ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

Not sure how to reproduce this issue, but here's what I'm seeing: 
I have the Node debugger installed, as you can see from the right side of the top entry here:

<img width="690" alt="Screen Shot 2020-10-29 at 4 44 47 PM" src="https://user-images.githubusercontent.com/138/97643958-3a968100-1a06-11eb-9f99-af78d6d0e2f7.png">

but it doesn't show up in the installed extensions:

<img width="690" alt="Screen Shot 2020-10-29 at 4 44 32 PM" src="https://user-images.githubusercontent.com/138/97643943-32d6dc80-1a06-11eb-9221-04b8450a7df4.png">

The Node debugger extension also doesn't seem to work, though it was earlier. Not sure what changed.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
Node debugger is a built in extension and hence it is not shown in installed. You can see it in built in extensions view.
