### ISSUE TITLE
API: file watching doesn't report file deletions caused by directory deletion

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode#109754]
In the [Go language server](https://golang.org/s/gopls), we register a file watcher with a `GlobPattern` of `"**/*.{go,mod,sum}"`. I would expect that this file watcher would report deletions of files caused by the deletion of a directory, but this doesn't seem to be the case.

For example, if the workspace contains a directory `foo` with the file `foo.go`, deleting `foo` either in the terminal (`rm -rf foo`) or in the VS Code UI does not result in any change notifications for `foo/foo.go`. The only way I was able to get notifications was when I registered a watcher with the `GlobPattern` of `"**"`, but we'd prefer to avoid registering for notifications for all files in the workspace.

Is this expected behavior or have we made some mistake here?

VSCode Version:

1.51.0-insider
2ee8b8c645ec8ab54304bacae7aa979c1d9c647a
x64

OS Version: Mac OS Catalina 10.15.7

**Comment by bpasero** [comment]
> Is this expected behavior or have we made some mistake here?

Expected. On some platforms or for performance reasons we may decide to fold the delete event into a single one for the folder. Since you can subscribe to a pattern that includes folders as well, the workaround is to register for the folder and then check if the events match your files as children.

**Comment by stamblerre** [comment]
> Expected. On some platforms or for performance reasons we may decide to fold the delete event into a single one for the folder. Since you can subscribe to a pattern that includes folders as well, the workaround is to register for the folder and then check if the events match your files as children.

I still find this a bit surprising. Doesn't that mean that the only valid GlobPattern is `**` (since directories can have any name or extension)?

I might expect the file watcher to report directory deletions instead of per-file deletions when a directory was deleted, but I saw no notifications at all with a `GlobPattern` of `"**/*.{go,mod,sum}"`, even though matching files were deleted when the directory was deleted.
