### ISSUE TITLE
Multiple snippet transforms

### ISSUE THREAD

**Issue by reggi** [microsoft/vscode#109766]
There has been this request once before but I do not believe the solution applies.

I'd love to transform `helloWorld` to `HELLO_WORLD`.

I have a couple of different snippet transforms:

```
helloWorld
${1/(^\w)/${1:/upcase}/} // upcase first letter (HelloWorld)
${1/(^\w)/${1:/downcase}/} // downcase first letter (helloWorld)
${1/([A-Z])/_${1:/downcase}/g} // snake -> underscore (hello_world)
${1/(.*)/${1:/upcase}/} // all caps (HELLOWORLD)
```

Here I'd want to use both the last two. `${${1/([A-Z])/_${1:/downcase}/g}/(.*)/${1:/upcase}/}` But this is not currently supported.

**Comment by ArturoDent** [comment]
This works, unless I am missing exactly how you are using it:

      "body": "${1/(.*)([A-Z].*)/${1:/upcase}_${2:/upcase}/}",

The idea being to split your text `helloWorld` into 2 capture groups.  Upcase them both and separate with an underscrore.

**Comment by jrieken** [comment]
Thanks @ArturoDent
