### ISSUE TITLE
wrong color

### ISSUE THREAD

**Issue by zwkno1** [microsoft/vscode#109798]
- VSCode Version:
1.50.1
'd2e414d9e4239a252d1ab117bd7067f125afd80a'
x64
- OS Version: 
macos catalina 10.15.7

Steps to Reproduce:

1.create a file a.h with c++ code:
`
template<int N, char ...chs>
struct formater_generator : formater_generator<N-1, '{', '}', chs... > {};
 `
2. the color after "'{'" was wrong.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
@zwkno1 thanks for reporting this. I have copied the bug to https://github.com/jeff-hykin/cpp-textmate-grammar/issues/516, which is where we get our C++ syntax highlighting grammar from.
