### ISSUE TITLE
Toggle visibility of Editor Groups

### ISSUE THREAD

**Issue by zain-ak** [microsoft/vscode#109771]
I was thinking of being able to toggle the visibility of editor groups so that space can be freed up when you're focusing on windows in one group. This would be done in two ways: 

1.) A minimize-maximize button next to the split editor and additional options buttons on the right of every editor <img width="45" alt="Screen Shot 2020-10-30 at 22 17 59" src="https://user-images.githubusercontent.com/14963706/97769009-c808cc80-1afd-11eb-8338-4df3e1d0a548.png">

2.) Shortcut keys that could toggle visibility on and off, focusing on specific editor groups using the initial shortcut as the start of a chord, and then perhaps entering the _nth_ number on the keyboard to refer to the specific editor group in sequence.

When the editor group is minimized, it could be stacked on the left like a pinned tab in chrome, perhaps in the next editor on its right or in a **dedicated space** (I think this is preferable), with a maximize icon and icon denoting which editor group it is. An example: if you have 4 editor groups open and you minimize the 2nd & 3rd, where would you stack them? In this case a dedicated between the sidebar and first editor group denoting its number in the sequence of overall editor groups. 

_Of course, you don't want this little space to take up too much space, so you could have an additional options button with a dropdown after a certain number of editor groups are closed._

P.S This is my first feature request, and I'm interested in attempting to implement it myself. Please let me know whether this is a feasible thing to pursue, or if I should perhaps look to build it as an extension.

**Comment by stagefright5** [comment]
I can think of few features that can be included in this:

1. Ability to add a single editor tab to the group (using context menu, for example)
2. Ability to select the editor tab/s and add selected tabs to a group
3. Restore the minimized editor tab group into the current open/focused editor group
4. Restore the minimized editor tab group into a new editor group (to right, left, down or up)

Please feel free to modify or add your suggestions

**Comment by brianblakely** [comment]
I'd like to pile on top of this request:

Peek a minimized editor group. Peek triggers could be the following:
* Hovering over its minimized representation. 
* Long-holding (mousedown/pointerdown) its minimized representation.
* Holding or toggling a key shortcut.

The use-case is for referencing code/text related to one's current work, without permanently occupying a lot of screen space. I think of the minimized editor group as a "sidekick" to the non-minimized groups.

**Comment by jcole099** [comment]
I made an AutoHotKey (AHK) script that opens and closes a second editor group with a single hotkey. The hotkey I'm using is Numpad0. Leaving this here incase anyone wants a quick solution to a similar issue that I have experienced. Here is the code:

;first keypress: splits tab #2 in group 1
;second keypress: closes group 2
;requirement is that the tab to be split is in the second position of editor group 1

toggle:=1		;set variable
Numpad0::
toggle := !toggle	;invert variable
If (!toggle) {
	send, ^1   ;select group 1
	send, !2	;select tab 2
	send, ^\	;split tab 2
	send, ^1	;select group 1
	send, !1	;select tab 1
}
else 
{
	send, ^2	;select group 2
	send, ^{F4}	;close window
}
Return

**Comment by kingpatrickj** [comment]
This feature only allows for working within one group while all the rest are minimized. It's still missing the functionality of hiding only one group while other groups are left open. For example, I might be working in two files and need a third for reference. Being able to toggle the visibility of ONLY the reference group would mean I can still work in both working groups at the same time.

**Comment by profxavr** [comment]
I am also desperately hoping this feature gets added. My editor groupings are usually quite meaningful to me, and once I have a specific set of tabs open, I don't necessarily want to part with them. I think the current best solution is opening a new window, but that FEELS messier than just having, essentially, vscodes own internal windowing with groups.
