### ISSUE TITLE
Provide a way for a CompletionItem to have both a color and documentation

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#109794]
Currently in order for a color to be shown in a completino item, the color has to be the _only_ thing in the documentation (or it has to be the label)

https://github.com/microsoft/vscode/blob/5264ab94a337ea8acae51c550aefe1f0b578f656/src/vs/editor/contrib/suggest/suggestWidgetRenderer.ts#L33-L49

This forces me to use the 'detail' for documentation, which looks awkward

![](https://memes.peet.io/img/20-10-0299c46b-9ec4-43b0-a24b-17e80f111489.png)

It would be very useful if documentation could be provided in addition to the color. Perhaps allow the color to be specified on either the first or last line (or in the `detail` property). Using the first or last line would not be breaking in the current behavior.

**Comment by jrieken** [comment]
Hm... We could also allow details to be used as color

**Comment by jrieken** [comment]
@connor4312 please verify

**Comment by mjbvz** [comment]
@jrieken Looks good! FYI I pushed a minor fix to allow upper case hex characters: ff66544ada8e87a5ec75271b0d606c0c1b425afc
