### ISSUE TITLE
Can't save workspace locally when using remote extension

### ISSUE THREAD

**Issue by jonnyijapan** [microsoft/vscode#109713]
Issue Type: <b>Feature Request</b>

Can't save workspace locally when using remote extension, and connected remotely.
The feature used is "File>Save Workspace as..."

This used to work, but it doesn't seem to work anymore. All that shows up is directories remotely.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 4.18.0-193.6.3.el8_2.x86_64

**Comment by buzhangjiuzhou** [comment]
I also heavily rely on this feature, can you add it back?

**Comment by aeschli** [comment]
The workaround is to store the workspace on remote and opening it from the local side either from the recent menu or by using the command line:
`code --remote ssh+remotetaddr /home/you/workspacefile.code-workspace`

**Comment by buzhangjiuzhou** [comment]
> The workaround is to store the workspace on remote and opening it from the local side either from the recent menu or by using the command line:
> `code --remote ssh+remotetaddr /home/you/workspacefile.code-workspace`

But it is not convenient to do so as I have to memory or store this command somewhere, also it helps to some extent, VScode save locally is better.

**Comment by vince-zeng** [comment]
Is the workaround is the only way for this issue? I don't understand why not allow the remote folder to local workspace.

**Comment by Aetherbase** [comment]
@aeschli  I feel it is senseless that we have to disable the entire feature because of a minor issue. Many projects of mine and my clients and people around here too were reliant on the feature because of convenience. Maybe enable the feature and warn the users for the encoding issue and provide a workaround for it instead of disallowing local workspace saving. This is like instead of fixing the hinge you are removing the entire door. pretty senseless imo.

**Comment by aeschli** [comment]
I added it back.

**Comment by buzhangjiuzhou** [comment]
> I added it back.

Thanks so much!

**Comment by paulguise** [comment]
I am using v 1.51.1 and the Show Local option is not available for saving workspaces. Was this disabled again?

**Comment by rlegrand** [comment]
It looks like "show local" is available when adding a folder, but not when saving the workspace.

**Comment by timaelliott** [comment]
Please add "show local" back this was an absolutely idiotic change to remove it.

**Comment by scubanarc** [comment]
> Please add "show local" back this was an absolutely idiotic change to remove it.

+1

Saving a workspace locally is a critical feature to making it work. I've been editing my workspace files by hand since this feature was removed.

VSCode 1.51.1 with Remote - SSH v0.61.0 does not appear to have the option to me.

**Comment by paulguise** [comment]
I've been editing manually as well. Some workspaces have local and remote files but most have only remote files, so saving those to the server (where it defaults to saving) isn't doable.

**Comment by jonnyijapan** [comment]
I assume this has already been fixed but is somehow waiting for a release. Does anyone know when that could be?
