### ISSUE TITLE
Extension count in not working properly

### ISSUE THREAD

**Issue by indahud** [microsoft/vscode#109725]
- VSCode Version: 1.49.1
- OS Version: Linux x64 5.8.16-2-MANJARO

Steps to Reproduce:

1. Go to any extension of your choice
2. Install count is less than marketplace count.

Does this issue occur when all extensions are disabled?: Yes

**Comment by tamuratak** [comment]
Duplicate of #109365 and #107997. See https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178
