### ISSUE TITLE
Selection in the debug console "leaks" into the code editor

### ISSUE THREAD

**Issue by delmyers** [Microsoft/vscode#10976]
- VSCode Version: 1.4
- OS Version: OSX El Capitan 10.11.5

Steps to Reproduce:
1. Open a code file
2. Do something that will cause output into the debug console
3. Select some text in the debug console
4. Use Shift+Up to select multiple lines

Observe: the selection "leaks" into the code editor (see attached)

![screen shot 2016-08-25 at 2 04 26 pm](https://cloud.githubusercontent.com/assets/242340/17986054/ae80b992-6acd-11e6-9563-41de57f7916c.png)

**Comment by delmyers** [comment]
Also, it seems that it is only possible to copy what is currently visible in the debug console.

**Comment by isidorn** [comment]
Only copying what is currently visible is dup of https://github.com/Microsoft/vscode/issues/2163

**Comment by isidorn** [comment]
Actually the selection leak would also be fixed by the proper implementation of #2163
Thus closing as duplicate
