### ISSUE TITLE
Option to skip update notification for a specific version of an extension (that I know has some bug)

### ISSUE THREAD

**Issue by geekley** [microsoft/vscode#109715]
**The problem**
So I found out that the C# extension has a bug in version 1.23.3+ that causes it to mark errors incorrectly in my project. Naturally, I chose the `Install Another Version...` option for that extension, to keep it in version 1.23.2 until this bug is eventually fixed. The thing is, the update notification is still there (I have extension update set to manual) always telling me to update to the version 1.23.4, which I know still has the bug. There's a feature I've seen in other programs (Android Studio, Unity) which allows to skip an update version. It would be good to have it in here too, so I can ignore one extension while still getting updates normally for other extensions.

**The solution**
The "install another version" option would be greatly improved if I could also have these options on the extension context menu:
`Skip update to this version`: Disables update notification for that extension version. When a version more recent than the skipped version ever becomes available, you get the update notification again, and then you can either skip again or install it.
`Skip all updates`: Disables update notifications for this extension until you decide otherwise.
`Allow updates`: Back to normal behavior.

Or, if you want a flexible implementation:
`Restrict updates to version ...` > (text field input pre-filled with `>` followed by the latest version currently available)
This skips update notifications for versions specified in pattern. For example:
- `>1.23.4`: skip any version until >= 1.23.5 is available
- `>1.23`: skip any version until >= 1.24.0 or >= 2.0.0 is available
- `>1`: skip any version until >= 2.0.0 is available
- `>`: skips all updates
- `1.23.2`: accept no updates >= 1.23.3
- `1.23`: accept only patch updates (skip >= 1.24.0 or >= 2.0.0, but allow 1.23.3, 1.23.4, etc)
- `1`: accept only minor and patch updates (skip >= 2.0.0, but allow 1.x.x)
- ` `: accept any updates

This could be in settings.json, so you could have it as a workspace or user setting.

**Comment by sandy081** [comment]
/duplicate

Please add your use case and more details in the other request.
