### ISSUE TITLE
VCS sync error bad handling

### ISSUE THREAD

**Issue by peach-lasagna** [microsoft/vscode#109769]
- VSCode Version: 1.50.1
- OS Version: Windows 10( +wsl Ubuntu) 

Steps to Reproduce:
1. clone repo
2. commit changes to local repo
3. try to sync changes with remote , clicked on this circle
![изображение](https://user-images.githubusercontent.com/59787538/97764606-3c546780-1b20-11eb-9732-5bbdca1acb38.png)
4. vscode VCS  is frozen ,and circle was spinning, but vscode continued work 

Solution :
5. I tryed to do this from terminal, and git answer me: "Permission denied, login to git:
do in terminal ```git config --global user.name ``` and ... ".

I would like to have a error catching system better than now.

Does this issue occur when all extensions are disabled?: No

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the Terminal message?

**Comment by peach-lasagna** [comment]
sorry, i close terminal 3 days ago

**Comment by joaomoreno** [comment]
Is it working now?

**Comment by peach-lasagna** [comment]
yes, because i login to git (from terminal).

**Comment by peach-lasagna** [comment]
But , i want have a better  error handling.
