### ISSUE TITLE
How to know User selected extension via command or just by shortcut

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#10974]
Hi,
My extension "code-settings-sync" has shortcut for command to upload / download the settings.
It deletes the extensions also, When user use shortcut for any command to download the settings rather than command palatte, I dont have any way to know because i want to set a confirmation when user use shortcut instead of command palatte.

This check or feature will be nice to have.

**Comment by jrieken** [comment]
The indirection of `command_id ` to `function` and UI-guesture to `command_id` is on purpose and don't plan to indicate what gesture triggered a command. Also note that with `executeCommand` and redefined keybindings your command can be triggered from anywhere in any condition. 

*Today* you can workaround this by having separate command and bind them accordingly, in the *future* we will allow to define static arguments in keybinding.json. With that you can travel a bit of custom information but must can be customised.
