### ISSUE TITLE
"Restart to Update" does not restart on macOS 11.0.1 (Big Sur)

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#109728]
VS Code Insider and Stable on macOS 11.0.1 (Big Sur):

The "Restart to Update" does not restart VS Code on macOS 11.0.1 (Big Sur).
But the update works fine: after a manual start VS Code is updated.

**Comment by deepak1556** [comment]
Upstream fix https://github.com/electron/electron/pull/25864, should be fixed in our exploration builds, needs to be backported to `9-x-y`

**Comment by joaomoreno** [comment]
@deepak1556 It would be ideal if we could backport this and include it for November so Big Sur stable users don't hit this issue the next few updates. Would a backport be possible?

**Comment by deepak1556** [comment]
For Electron versions < 11 , squirrel is downloaded as a prebuilt binary from https://github.com/electron/electron-frameworks which hasn't bumped versions in a long time.

For electron 11 and higher squirrel is built from source, which made it easier to pick up fixes. So backporting a fix to Electron 9 at this late stage in release is difficult.

**Comment by joaomoreno** [comment]
**Discussion from Zürich standup**

On Big Sur, the action is still to be called `Restart to Update`. When clicking it, a modal dialog should come up explaining this is broken in Big Sur, with a link to the issue, and an action to Quit VS Code.

**Comment by deepak1556** [comment]
@joaomoreno will this change be included only for release/1.52 branch ? Since master is already on Electron 11

**Comment by joaomoreno** [comment]
I will include the modal dialog *only* on the release branch, and keep this issue open.

**Comment by joaomoreno** [comment]
PR: https://github.com/microsoft/vscode/pull/112008

**Comment by joaomoreno** [comment]
Moving this to December.

**Comment by weinand** [comment]
Automatic restart works fine now.

**Comment by atharva789** [comment]
> The "Restart to Upd

doesn't work at least on macos Big Sur version 11.2.1 for me can't find any fixes 
keeps telling me to restart my vscode and tells me when I press to quit to restart that theere is some problem with macos Big Sur 
![Screenshot 2021-02-26 at 23 27 46](https://user-images.githubusercontent.com/62479753/109337061-41d17c80-788a-11eb-94ed-5624ab746d8c.jpg)

**Comment by deepak1556** [comment]
@atharva789 which version of vscode are you seeing this issue with ?

**Comment by atharva789** [comment]
> @atharva789 which version of vscode are you seeing this issue with ?

version 1.53 is what the release notes of the update is pointing me at 
I'm on Version: 1.52.1

**Comment by deepak1556** [comment]
Yes moving from `1.52` => `1.53` will have this issue where you need to manually restart. Once you update to `1.53` for the next updates the application will be restarted automatically.

**Comment by atharva789** [comment]
I tried it doesn't work

**Comment by deepak1556** [comment]
Did you try updating from `1.53.0` => `1.53.1` ? Please share a screencast about the problem which also shows the initial version you are on and the new version you are updating to.

**Comment by atharva789** [comment]
> Did you try updating from `1.53.0` => `1.53.1` ? Please share a screencast about the problem which also shows the initial version you are on and the new version you are updating to.

how do I mannually restart? I've already tried opening the app from finder, double-clicking on the app icon to open it, force-quitting and restarting it

**Comment by deepak1556** [comment]
what is the output of `code --verbose` ?
