### ISSUE TITLE
unable to login with corporate microsoft account

### ISSUE THREAD

**Issue by kumardeni** [microsoft/vscode#109735]
Issue Type: <b>Bug</b>

I can login to https://marketplace.visualstudio.com/ with my corporate email id/account. But when i try to sign in in VS code to get extensions...it gives the below error message in browser after taking the corporate email id/account

Error Details:
An error occurred while signing in:
Unable to login.

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:29:41.983Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.20GB free)|
|Process Argv|--crash-reporter-id f219e213-9e4f-4790-a391-27512bac465b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-extension-sa|SAP|0.1.1
sap-ux-fiori-tools-extension-pack|SAP|1.0.7-pre-20200713164906-cf52a75db.0

</details>

**Comment by RMacfarlane** [comment]
@kumardeni Can you try this again and open the output panel, select "Microsoft Authentication", and copy the log from there?

**Comment by kumardeni** [comment]
@RMacfarlane Please find the same...

1. When in corporate network:
a. during authentication.
******
[Info  - 10:02:19.444] Logging in...
[Info  - 10:02:39.735] Exchanging login code for token
[Error  - 10:02:40.711] Exchanging login code for token failed
[Error  - 10:02:40.712] Unable to login.
******

b. when I use 'check for updates' option, below is the log.
******
[2020-10-31 15:59:27.229] [main] [info] update#setState checking for updates
[2020-10-31 15:59:27.890] [main] [error] Error: net::ERR_TUNNEL_CONNECTION_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6395)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
[2020-10-31 15:59:27.890] [main] [info] update#setState idle
******

2. When not in corporate network:
a. during authentication.
******
[Info  - 10:06:31.419] Logging in...
[Info  - 10:06:36.424] Exchanging login code for token
[Error  - 10:06:36.456] request to https://login.microsoftonline.com/organizations/oauth2/v2.0/token failed, reason: getaddrinfo ENOTFOUND proxy.wdf.sap.corp
******

b. when I use 'check for updates' option, below is the log.
******
[2020-10-31 16:09:48.631] [main] [info] update#setState checking for updates
[2020-10-31 16:09:48.650] [main] [error] Error: net::ERR_PROXY_CONNECTION_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6395)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
[2020-10-31 16:09:48.650] [main] [info] update#setState idle
******

**Comment by kumardeni** [comment]
@RMacfarlane - Also I can't search for any extensions...I get the message "We cannot connect to the extensions marketplace at this time, please try again later."

**Comment by RMacfarlane** [comment]
@kumardeni This looks like a network problem, has anything changed about your network recently? Did this work in previous versions of VS Code? Please see https://code.visualstudio.com/docs/setup/network

**Comment by kumardeni** [comment]
@RMacfarlane - Lets park the login issue for a moment, even a basic check for update option is not working.

I have checked from my end and also with the network team, the corporate firewall is not blocking anything related to Microsoft. In the laptop i'm using it is first time installation.

Also, I would like to mention that for my colleagues who are in the same office network, it works perfectly fine.
For them, it gets connected to extension market place and the update option works just fine.

> [2020-11-10 18:04:00.082] [main] [info] update#setState checking for updates
> [2020-11-10 18:04:00.942] [main] [error] Error: net::ERR_TUNNEL_CONNECTION_FAILED
>     at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6395)
>     at SimpleURLLoaderWrapper.emit (events.js:223:5)
> [2020-11-10 18:04:00.942] [main] [info] update#setState idle

So can we check if there are any application specific setting which I'm missing or can you please let me know to which server a call gets made when I click on 'Check for Update' option, so I can trace by pinging to the server incorporate environment with the help of my network team.

**Comment by kumardeni** [comment]
@RMacfarlane another thing...when I open https://marketplace.visualstudio.com/ , search for a extension and click on install option, it opens up my VS Code in PC and I get a error "XHR failed"

Log of Window from Output.

> [2020-11-06 10:08:30.864] [renderer1] [error] XHR failed: Error: XHR failed
>     at XMLHttpRequest.r.onerror (file:///C:/Users/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:465:45)
> [2020-11-09 13:51:43.258] [renderer1] [info] Setting search error: XHR failed
> [2020-11-09 13:51:43.258] [renderer1] [info] Setting search error: XHR failed
> [2020-11-09 13:51:44.134] [renderer1] [info] Setting search error: XHR failed
> [2020-11-09 13:51:44.390] [renderer1] [info] Setting search error: XHR failed
> [2020-11-09 13:51:45.454] [renderer1] [info] Setting search error: XHR failed
> [2020-11-09 13:51:45.706] [renderer1] [info] Setting search error: XHR failed
> [2020-11-10 13:54:16.851] [renderer1] [error] XHR failed: Error: XHR failed
>     at XMLHttpRequest.r.onerror (file:///C:/Users/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:465:45)

**Comment by chrmarti** [comment]
@kumardeni Are you behind a network proxy?

**Comment by kumardeni** [comment]
@chrmarti yes, in a office network(VPN). In my windows laptop "Automatically Detect Settings" is ON.

**Comment by kumardeni** [comment]
@chrmarti - is there any way to find out the root cause ?

**Comment by chrmarti** [comment]
The log above shows `getaddrinfo ENOTFOUND proxy.wdf.sap.corp`. Could this be a general networking problem on your machine independent of VS Code?

**Comment by kumardeni** [comment]
There are two types of error, the one you are referring to is the second case.
1. When in corporate network
Error: net::ERR_TUNNEL_CONNECTION_FAILED
2. When not in corporate network
Error: net::ERR_PROXY_CONNECTION_FAILED

**Comment by chrmarti** [comment]
Could you start VS Code with `--log-net-log=netlog.json`, retry the failing feature and then post the created netlog.json here?

It would make sense to collect this for both cases.

**Comment by kumardeni** [comment]
@chrmarti    When in Corporate Network, 
CMD Log

> C:\Users\i334776\AppData\Local\Programs\Microsoft VS Code>Code.exe --log-net-log=netlog.json

> C:\Users\i334776\AppData\Local\Programs\Microsoft VS Code>
> [main 2020-11-24T10:05:30.921Z] update#setState idle
> (node:3116) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\i334776\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
> (node:3116) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\i334776\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
> (node:16152) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\i334776\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
> [main 2020-11-24T10:05:43.222Z] update#setState checking for updates
> [main 2020-11-24T10:05:43.961Z] Error: net::ERR_TUNNEL_CONNECTION_FAILED
>     at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6395)
>     at SimpleURLLoaderWrapper.emit (events.js:223:5)
> [main 2020-11-24T10:05:43.963Z] update#setState idle
> [main 2020-11-24T10:06:00.937Z] update#setState checking for updates
> [main 2020-11-24T10:06:01.762Z] Error: net::ERR_TUNNEL_CONNECTION_FAILED
>     at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6395)
>     at SimpleURLLoaderWrapper.emit (events.js:223:5)
> [main 2020-11-24T10:06:01.765Z] update#setState idle
> [main 2020-11-24T11:06:01.045Z] update#setState checking for updates
> [main 2020-11-24T11:39:25.783Z] Error: net::ERR_TUNNEL_CONNECTION_FAILED
>     at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6395)
>     at SimpleURLLoaderWrapper.emit (events.js:223:5)
> [main 2020-11-24T11:39:25.785Z] update#setState idle

attaching netlog.json in a zip
[netlog_CN.zip](https://github.com/microsoft/vscode/files/5589573/netlog_CN.zip)

**Comment by kumardeni** [comment]
@chrmarti When not in corporate network
CMD Log

> C:\Users\i334776\AppData\Local\Programs\Microsoft VS Code>Code.exe --log-net-log=netlog.json
> 
> C:\Users\i334776\AppData\Local\Programs\Microsoft VS Code>
> [main 2020-11-24T11:44:57.920Z] update#setState idle
> (node:38472) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\i334776\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
> (node:5720) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\i334776\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
> (node:38472) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\i334776\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
> [main 2020-11-24T11:45:20.253Z] update#setState checking for updates
> [main 2020-11-24T11:45:20.304Z] Error: net::ERR_PROXY_CONNECTION_FAILED
>     at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6395)
>     at SimpleURLLoaderWrapper.emit (events.js:223:5)
> [main 2020-11-24T11:45:20.310Z] update#setState idle
> [main 2020-11-24T11:45:27.975Z] update#setState checking for updates
> [main 2020-11-24T11:45:27.995Z] Error: net::ERR_PROXY_CONNECTION_FAILED
>     at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6395)
>     at SimpleURLLoaderWrapper.emit (events.js:223:5)
> [main 2020-11-24T11:45:27.996Z] update#setState idle

attaching netlog.json in a zip
[netlog_ocn.zip](https://github.com/microsoft/vscode/files/5589609/netlog_ocn.zip)

**Comment by chrmarti** [comment]
@deepak1556 Could you take a look at the logs? It looks like this might be a problem with the network or the network configuration, there is no indication of a bug on our or Electron's side from what I see.

**Comment by kumardeni** [comment]
@chrmarti - Meanwhile can I know the destination hostname or IP address, which gets invoked by VS Code client upon clicking on 'Check for Update' option, So I can try to ping directly from my laptop. This way I can be sure that there is something blocking in the network.

**Comment by chrmarti** [comment]
@kumardeni Try https://update.code.visualstudio.com/api/update/win32-x64-user/stable/latest in Chrome. It should show a small JSON document.
