### ISSUE TITLE
JavaScript code highlighting doesn't work

### ISSUE THREAD

**Issue by frolov-alexey** [Microsoft/vscode#10978]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Highlighting breaks in the file which has lots of nested if / functions with 37 spaces in the left
![image 3](https://cloud.githubusercontent.com/assets/6369486/17987844/40b6d07c-6ad7-11e6-96d2-942cbe87eb25.png)

**Comment by sandy081** [comment]
This might be related to #10878.

**Comment by alexandrudima** [comment]
@frolov-alexey Can you please provide a full example in textual form so we can check if this is an issue with the grammar?

**Comment by frolov-alexey** [comment]
@alexandrudima I don't have rights for that. But I can say that it doesn't have any jslint warnings/errors, and it is highlighted properly in Atom editor.

**Comment by alexandrudima** [comment]
Ok, that is not a problem. We have already some good cases for this in #9937

**Comment by frolov-alexey** [comment]
@alexandrudima OK, looks like I'll have to remove VS Code and use another editor.

**Comment by alexandrudima** [comment]
@frolov-alexey I'm sorry you feel that way. I have simply closed this issue as a duplicate of another issue that was created before this one. Tomorrow's insiders build will contain the fix for #9937 and if you want to help us out you can try the insiders build to see if the file you cannot share with us gets colored.

**Comment by frolov-alexey** [comment]
@alexandrudima alright, sounds good. I'll let you know if that update fix the issue. Thanks.

**Comment by BenjaVR** [comment]
@alexandrudima for me it is fixed with the insiders build!

**Comment by frolov-alexey** [comment]
Yes, this was fixed in latest version (1.5.1). Thanks for hard work!
