### ISSUE TITLE
Emmet doesn't remove snippets if user moves snippet file to another directory

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#109706]
Version: 1.51.0-insider (user setup)
Commit: 2ee8b8c645ec8ab54304bacae7aa979c1d9c647a
Date: 2020-10-29T06:01:21.160Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Have a working Emmet snippets setup
2. Move snippet file to another directory within VS Code but don't change or refresh settings.json
3. The snippets still work

Found while testing #108812

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rzhao271** [comment]
Closing as out of scope.
Anyone who wants this implemented can either comment on this issue, or open a new feature request for this.

**Comment by roblourens** [comment]
Hey @rzhao271, when you close an issue as out of scope, you can remove it from the milestone so it doesn't show up in our verification query
