### ISSUE TITLE
Some extensions cannot be found

### ISSUE THREAD

**Issue by Catoverflow** [microsoft/vscode#109745]
- VSCode Version: `1.50.1`
- OS Version: `5.9.2-arch1-1`

Steps to Reproduce:

1. Open VSCode
2. Search for extensions with explicit name like `mshr-h.VerilogHDL`
    Or use command: `ext install mshr-h.VerilogHDL`
3. Says "No extensions found"
![image](https://user-images.githubusercontent.com/55503205/97723905-4158ed00-1b07-11eb-92af-781d85691270.png)

Does this issue occur when all extensions are disabled?: Yes

Other extensions such as `ftsamoyed.theme-pink-cat-boo` won't appear too, though can be downloaded from extension market online and installed via .vsix files. **While some other extensions can still be found** in search bar like `dbaeumer.vscode-eslint`.
![image](https://user-images.githubusercontent.com/55503205/97725166-d14b6680-1b08-11eb-87fb-b166b2a9fecf.png)

This reoccured after reinstalling the system and vscode. I believe this to be due to some weird configurations or network errors instead of an internal bug, but reinstalling didn't work nor searching the Internet helped. No relavant Q&A was found in forums and thus I've to raise this issue. Any suggestion?

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/107034

**Comment by tamuratak** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Comment by Catoverflow** [comment]
A handy wordaround is to manually edit `/usr/share/code/products.config`,
and change
~~~~
"serviceUrl": "https://open-vsx.org/vscode/gallery",
"itemUrl": "https://open-vsx.org/vscode/item"
~~~~json
to
~~~~
"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
"cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
"itemUrl": "https://marketplace.visualstudio.com/items"
~~~~json
