### ISSUE TITLE
Getting artefacts on mouse move over window

### ISSUE THREAD

**Issue by yonghie** [microsoft/vscode#109763]
![JJUK7Bjji3Y](https://user-images.githubusercontent.com/56758452/97757997-9b0ce780-1b06-11eb-9ae1-1cdc2aa0d258.jpg)

- VSCode Version: 1.50.1
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:
There is many variations how it shows up
1. minimise window
2. lose focus by clicking on desktop
3. on desktop make selection under window

1. alt-tab window

1. lose focus by click on desktop
2. move mouse over window

these all work randomly
sometimes shows and sometimes no but using vscode is imposible

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/103673

You can disable hw acceleration for a temporary workaround https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
