### ISSUE TITLE
[html] hovers in embedded JavaScript should look like in TypeScript

### ISSUE THREAD

**Issue by wgxh** [microsoft/vscode#109800]
# Screenshot:
## in JS:
![image](https://user-images.githubusercontent.com/68545007/97795330-e1199680-1c3f-11eb-9b24-cae2cf1f0f9e.png)
## in HTML:
![image](https://user-images.githubusercontent.com/68545007/97795333-e545b400-1c3f-11eb-8da0-b654957bd8b9.png)

I hope to make the hover prompt in HTML and JS consistent, Thanks!

**Comment by amaust** [comment]
Hello! I would be interested in working on this issue. I was wondering if anyone would mind leading me in the right direction. Im thinking that since the feature is already there for typescript files I wouldnt have to re write the feature. Im just not quite sure where to look. Thanks!

**Comment by aeschli** [comment]
@amaust You find the code for hovers in embedded JavaScript here: https://github.com/microsoft/vscode/blob/1c0d05691547300f8e9ffd69704eadc1e3c2e0f5/extensions/html-language-features/server/src/modes/javascriptMode.ts#L140

The code for hover in TypeScript/JavaScript is here: https://github.com/microsoft/vscode/blob/1c0d05691547300f8e9ffd69704eadc1e3c2e0f5/extensions/typescript-language-features/src/languageFeatures/hover.ts#L32

The first one uese the TypeScript service, and the second one the TypeScript server. The object representing the QuickInfo is not the same but kind of similar.

**Comment by amaust** [comment]
Awesome thank you for that, could you also tell me where the HTML hover functions are? @aeschli

**Comment by aeschli** [comment]
Not sure what you mean by the 'HTML hover' functions. The first link is for the HTML hover, specifically when in JavaScript embedded in HTML. Check the code in that folder for css and htmnl element hovers.

**Comment by amaust** [comment]
Ah I see now, my apologies for the confusion.

**Comment by chenjigeng** [comment]
@aeschli I fixed it by doing this. But I think this maybe has a better way to do it?
![image](https://user-images.githubusercontent.com/14784326/99883580-669ece00-2c63-11eb-8a5a-6bf14b637953.png)

**Comment by AbduAmeen** [comment]
I also tried the solution, and it worked.

**Comment by aeschli** [comment]
Thanks @chenjigeng !
