### ISSUE TITLE
php.executablePath from settings.json ignored on macOS (BigSur beta)

### ISSUE THREAD

**Issue by bkg2018** [microsoft/vscode#109858]
Issue Type: <b>Bug</b>

Tested on BigSur beta 11.0.1 (not sure this is specific to macOS version)

Context:
- install php 7.4 under `/usr/local/opt/php` link with homebrew (BigSur installs version 7.3)
- adjust PATH in startup scripts and check order is 7.4 first:
    `> where php`
        `/usr/local/opt/php/bin/php`
        `/usr/bin/php`
    `> php -v`
        `PHP 7.4.12 (cli) (built: Oct 29 2020 18:37:21) ( NTS )` etc
- launch vscode (1.50.1)
- Cmd+ opens settings.json
- enter php 7.4 path : `"php.executablePath": "/usr/local/opt/php/bin/php"`
- set a launch.json to run a php script

Problem:
- Start debug -> launches macOS php 7.3 from `/usr/bin` instead of the 7.4 from settings.

Possible fix:
- can be fixed by specifying runtimeExecutable in launch.json configurations: `"runtimeExecutable": "/usr/local/opt/php/bin/php"`

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 20.1.0

<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.3.1
vscode-markdownlint|Dav|0.37.2
vscode-eslint|dba|2.1.13
xml|Dot|2.5.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
AWK|lug|0.0.2
asm-code-lens|maz|1.5.8
dezog|maz|1.5.4
z80-instruction-set|maz|1.0.1
z80-macroasm|mbo|0.6.1
theme-monokai-pro-vscode|mon|1.1.17
vscode-docker|ms-|1.7.0
mssql|ms-|1.9.0
remote-containers|ms-|0.145.1
cpptools|ms-|1.0.1
debugger-for-chrome|msj|4.12.11
synthwave-vscode|Rob|0.1.8
awk-language-client|TGV|0.1.0
vscode-icons|vsc|11.0.0
markdown-all-in-one|yzh|3.3.0

(3 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
That setting is used for vscode's built-in PHP support. The debug extension does not read it, so I think this is by design. But you can file an issue on the debug extension if you think it should work differently.
