### ISSUE TITLE
shortcut in Japanese keyboard

### ISSUE THREAD

**Issue by agektmr** [Microsoft/vscode#10986]
- VSCode Version: 1.4.0
- OS Version: Mac OS X 10.11.6
- Apple wireless Japanese keyboard
- Karabiner 10.21.0
    - "Use Japanese Keyboard as US Keyboard" turned on.
    - Some other assignments are on but I think they are not related.

Steps to Reproduce:
When I press "CMD+]" it splits the window where indent is expected.
I'm using Karabiner to match the behavior with US keyboard but it doesn't seem to work as expected. Replacing it with US keyboard worked as expected.

I don't see similar oddities when using Atom or SublimeText. I imagine VSCode is reading native keypress events?

#6020 seems to be related.

cc: @aioutecism

**Comment by sandy081** [comment]
Yes it is related. Marking it as dup of #6020
