### ISSUE TITLE
Unwanted: const { response } = require("express");

### ISSUE THREAD

**Issue by lborgman** [microsoft/vscode#109873]
Issue Type: <b>Bug</b>

I have no idea how to reproduce this, but here is some info:

- The line in the title (after "unwanted") was added automatically.
- I had just added a new function where I have a parameter called "response" when this happened. 
- The file is just a pure ES6 file. 
- I do not use any framework that could decode "require" (if Firebase can't do that, it is the only framework I use).

It confused me quite a bit since I had some network trouble at the same time.

I am sure I have seen something similar before (but I did not have time to report it then).

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU N4200 @ 1.10GHz (4 x 1094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.84GB (0.31GB free)|
|Process Argv|--crash-reporter-id 2db228e7-570f-43a0-b1bf-75f2af041a44|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.3
cursor-charcode|but|0.9.2
firecode|ChF|1.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.2
vscode-sort|hen|0.2.5
beautify|Hoo|1.5.0
svg|joc|1.4.1
powershell|ms-|2020.6.0
material-icon-theme|PKi|4.4.0
partial-diff|ryu|1.4.1
vim|vsc|1.17.1
json|Zai|2.0.1

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so, please try putting together more specific steps to reproduce this issue

**Comment by lborgman** [comment]
@mjbvz
Hi Matt, this is of course an intermittent problem. There is no way to provide more specific info than what you already have got from me. So please continue from that. It should be possible to spot the code inserting this and from where it is called.

I think I have told before that I sometimes see problems related to race conditions. I see this in two places:

1) Code completion while simultaneously typing. They get mixed.
2) In the same context screen update shows a log of space that will collapse later when doing something else.

I am on a rather slow laptop with not to much memory when doing this. If you want to reproduce the problem when you must stay many hours on such a pc, I guess... (The laptop works surprisingly well even though it is cheap. I thought I would put together a faster desktop, but the components are just lying there. I really do not need them.)

**Comment by mjbvz** [comment]
Did you test in insiders with extensions disabled?

This looks like a normal [auto import](https://code.visualstudio.com/docs/languages/javascript#_auto-imports). It means you are accepting a suggestion that is for an auto import. Without steps to reproduce though, I can't investigate why this import might being picked up in the first place

**Comment by lborgman** [comment]
Thanks, yes, I guess it was auto import. (I have disabled it now.)

Auto import looks like a nice feature, but I have no need for it on the client side. Maybe sometimes on the NodeJs side.

However the implementation could be a bit more cautious. I think I got into this because of some unfortunate things working together:

1) I am since long a vi/emacs user. This means I expect things to just work. I normally do not look much on the screen. That would take a bit longer time.

2) The screen update sometimes does not work when auto-suggestions are shown. (I will try to take a screenshort next time it happens.) 

3) The auto import suggestions are added in another part of the file. This together with bad screen update make it easier to miss that the import statement was added.

I suggest adding a confirmation step before adding the import statement (or any other thing that happens in another part of the file).

**Comment by mjbvz** [comment]
Glad you were able to find the cause

This feature has been enabled for a long time for a whole lot of users without causing problems, so I don't want to add extra steps that would slow coding down.

Let me know if you find a case where auto imports are doing the wrong thing
