### ISSUE TITLE
Execute command via launch arguments.

### ISSUE THREAD

**Issue by Megabyteceer** [microsoft/vscode#109816]
Its will be great to have launch argument like ,"**vscode -command command.id.to.execute,command_arg**" which will pass one or more commands to existing vscode instance as it happens when new file open request sent. It will allow simple way to integrate vscode with any external tools.

**Comment by ArturoDent** [comment]
Similar and maybe what you are looking for:  https://github.com/microsoft/vscode/issues/109789

**Comment by Megabyteceer** [comment]
> Similar and maybe what you are looking for: #109789

If i got it correct, there is about send commands from vscode to external tools.
I am speaking about send commands from external tools to vscode.
