### ISSUE TITLE
autopep8 doesn't work in VS code with wsl2

### ISSUE THREAD

**Issue by hhchi13** [microsoft/vscode#109828]
Issue Type: <b>Bug</b>

1: open vs code in wsl2
2: open a python file. (choose conda as the intepreter)
3: enter: a=1
4: save. 

expected: a = 1
actual: a=1

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|30.96GB (22.76GB free)|
|Process Argv|--crash-reporter-id 36cfa6d8-1acf-4713-a43d-cac28acd1a02|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|1.0.24
code-gnu-global|aus|0.2.2
spellright|ban|3.0.52
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
gitlens|eam|10.2.2
vscode-test-explorer|hbe|2.19.1
vscode-drawio|hed|1.0.3
helium-icon-theme|hel|1.0.0
latex-workshop|Jam|8.13.2
kite|kit|0.133.0
vscode-leetcode|Lee|0.17.0
vscode-python-test-adapter|lit|0.6.2
theme-monokai-pro-vscode|mon|1.1.17
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.10.332292344
vscode-pylance|ms-|2020.10.3
remote-wsl|ms-|0.50.1
cpptools|ms-|1.0.1
debugger-for-chrome|msj|4.12.11
autodocstring|njp|0.5.3
java|red|0.69.0
vscode-yaml|red|0.12.0
swdc-vscode|sof|2.3.15
latex-utilities|tec|0.3.7
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.25.0
vscode-maven|vsc|0.25.0
vscode-icons|vsc|11.0.0
vscode-wakatime|Wak|4.0.9
debug-leetcode|wan|0.2.2
markdown-all-in-one|yzh|3.3.0

(5 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/Microsoft/vscode-python/issues
Would you mind filing the issue there? (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)

**Comment by hhchi13** [comment]
> This issue needs to be filed against
> https://github.com/Microsoft/vscode-python/issues
> Would you mind filing the issue there? (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)

I just filed the issue there. Here is the link: 
https://github.com/microsoft/vscode-python/issues/14634#issue-737241384
