### ISSUE TITLE
When i input chinese, some problems occured that i can't resolve.

### ISSUE THREAD

**Issue by powerdoom** [microsoft/vscode#109809]
Issue Type: <b>Bug</b>

When I input chinese, some problems occured. The first letter of Chinese PinYin will become English letter, and replace the Chinese word before it. That something strange is like this: 
If I want to input two sentences " 今天天气很不错，我想去钓鱼!"
When I finished the first sentence - "今天天气很不错", I tried to input the sencond one, it'll become some odd format like - "w我想去钓鱼". And the comma before the word will be disappered. All the two resulted is "j今天天气很不错w我想去钓鱼!". This problem confused a long time, so I need some help.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (21.43GB free)|
|Process Argv|--crash-reporter-id 6c2c15f2-a8ee-463b-80c6-89747fe59960|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
path-intellisense|chr|2.3.0
regex|chr|0.2.0
bracket-pair-colorizer|Coe|1.0.61
doxdocgen|csc|1.1.0
vscode-markdownlint|Dav|0.37.2
jshint|dba|0.10.21
vscode-eslint|dba|2.1.13
python-extension-pack|don|1.6.0
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
vscode-firefox-debug|fir|2.9.1
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
vscode-pull-request-github|Git|0.20.1
vscode-emacs|hir|0.1.1
vue-snippets|hol|0.1.12
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.15.0
MagicPython|mag|1.1.0
vscode-docker|ms-|1.7.0
csharp|ms-|1.23.4
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.10.332292344
remote-containers|ms-|0.145.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.1
cmake-tools|ms-|1.4.2
cpptools|ms-|1.0.1
cpptools-extension-pack|ms-|1.0.0
vscode-typescript-next|ms-|4.1.20201031
vsliveshare|ms-|1.0.3071
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3073
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.1.0
vetur|oct|0.28.0
material-icon-theme|PKi|4.4.0
java|red|0.69.0
vscode-yaml|red|0.12.0
guides|spy|0.9.3
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.25.0
vscode-maven|vsc|0.25.0
vscode-spring-initializr|vsc|0.5.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by yume-chan** [comment]
Which IME do you use?
