### ISSUE TITLE
Issue resolving env vars in remote server-hosted terminals

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#109863]
- Connect a mac->windows SSH remote
- Open terminal
- See this popup

![image](https://user-images.githubusercontent.com/323878/97915316-243e3d00-1d06-11eb-9a98-856c6cd7d83a.png)

So `findExecutable` fails here because it checks ".PATH" on the environment when this is actually "Path" on windows. `process.env` has special behavior where it resolves property accesses in a case-insensitive way on Windows. We changed many accesses from using `process.env` to a constructed environment object, and need the same behavior there.

**Comment by rzhao271** [comment]
@roblourens is this a mac-specific issue or are there steps to repro/verify on Windows?

**Comment by roblourens** [comment]
Can't be verified on windows. Thanks @JacksonKearl
