### ISSUE TITLE
vscode git changes not showing in explorer view when working through symbolic links.

### ISSUE THREAD

**Issue by NOD507** [microsoft/vscode#109865]
Today i found this issue and started looking for answers here. 

I am on:

VC Code: 1.50.1
Windows 10.0.19041.572

If I open my repository througth a symbolic link, the explorer view in vs code wont show Diff Decorations (M, U, D) but it will show them ok on the Source Control view. 

If I open the full path everything works fine.

It would be great if this could be resolved as we as users can manage shorter paths this way.

It is the same issue as 
_Originally posted by @marvila in https://github.com/microsoft/vscode/issues/28432#issuecomment-495638246_

"I found the same issue a few weeks ago and only now I could investigate it further and found something that might be the culprit, at least on my system. 

It seems to have something to do with symbolic links.

VC Code: 1.34.0
Linux: Ubuntu 18.04

A few weeks ago, I moved my files from one disk to another and created a symbolic link (ln -s) with the same name as before, but pointing, obviously, to the new location.

It was around that time that I noticed the change in behavior. I thought it was due to an extension I installed, but removing it didn't solve the problem.

So today, I don't know why, I tried to open the file through the full path, not the symbolic link _et voilà_, everything worked as expected, that is, i could see the coloring on the side of the changed files and auto sync at the GIT SCM view after saving.

I also noticed that opening through the full path, not the symbolic link, made vscode open the folder as if it was opening a new folder since the previously opened files were all closed.

**So it looks like the issue is with vscode not being able to work through symbolic links.**

_As a workaround: always open folders through their full path / mount point, never through symbolic links._

But I'd really appreciate if it was possible to use symbolic links as it would make my folder path much shorther."

_Originally posted by @marvila in https://github.com/microsoft/vscode/issues/28432#issuecomment-495638246_

**Comment by joaomoreno** [comment]
#5970
