### ISSUE TITLE
Not able to copy/paste in Search/Find inputbox

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#109892]
- Copy some text
- Open Search view
- Try to paste in Search input

🐛 Does not paste

Also does not work in Find input

```
Version: 1.51.0-insider
Commit: fce8fc82cacf0b4e2a18c633b6c6f3058702a5c9
Date: 2020-11-02T19:41:03.269Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by yume-chan** [comment]
See #109874, looks like it also happens to stable version

**Comment by rebornix** [comment]
@sandy081 what's the log you see when you run "Toggle Keyboard Shortcut Troubleshooting"?

**Comment by roblourens** [comment]
Works for me

**Comment by sandy081** [comment]
Sorry for the false alarm. It works for me now. 

I will run the command next time I see it.

**Comment by roblourens** [comment]
It's possible that you got a context key stuck at some value and that caused a different command to run. Have seen bugs like that before.
