### ISSUE TITLE
Initializing TS/JS shows forever

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109847]
* open a TS file, have TS active 
* close all files
* run the restart tsserver command
* :bug: the loading notification doesn't stop unless I open another TS/JS file

<img width="1356" alt="Screenshot 2020-11-02 at 14 23 55" src="https://user-images.githubusercontent.com/1794099/97872932-22c94080-1d17-11eb-89ed-9e027d8225f3.png">

**Comment by mjbvz** [comment]
With #117813, you should no longer be able to run `Restart TS Server` when no JS/TS files are open

However I think you might be able to hit this if the server crashes and restarts while no JS/TS file is open

**Comment by adjenks** [comment]
This appears to be an issue for me when accessing a network drive that is a little bit slow.
This also appears to be the cause of the linked issue above: https://github.com/SchoofsKelvin/vscode-sshfs/issues/248

**Comment by mjbvz** [comment]
Closing due to lack of additional reports of  the problem It should be difficult to get into this state now (and opening a JS/TS file fixes it)
