### ISSUE TITLE
super + e opens VS Code on Linux Deepin 

### ISSUE THREAD

**Issue by Miguel-Bento-Github** [microsoft/vscode#109807]
This issue still occurs.

After installing VS Code when I press super + e, instead of opening the file explorer it opens a new VS Code window.

> Sorry I don't really understand what you're saying, can you explain in more detail?

In Linux Deepin, when you install the VS Code, it overwrites the default file manager, so the shortcut SUPER + e (WIN + e for Windows) used to open the file manager opens the VS Code.

_Originally posted by @filippfarias in https://github.com/microsoft/vscode/issues/69790#issuecomment-475873105_

**Comment by Miguel-Bento-Github** [comment]
The solution is to change the order of apps
open 
`code /usr/share/applications/mimeinfo.cache` 
find
`inode/directory`
assign `code.desktop;dde-file-manager.desktop;` to it

**Comment by BackMountainDevil** [comment]
> The solution is to change the order of apps
> open
> `code /usr/share/applications/mimeinfo.cache`
> find
> `inode/directory`
> assign `code.desktop;dde-file-manager.desktop;` to it
When I open that, it is there  
`inode/directory=code.desktop;dde-file-manager.desktop;`
Then I try delete that line\one of both. In the end, the solution is delete 'code.desktop'. Just save this `inode/directory=dde-file-manager.desktop;`
