### ISSUE TITLE
Feature request: Option to disable auto creation of the ".vscode" folder

### ISSUE THREAD

**Issue by 8bitslime** [Microsoft/vscode#10987]
I know I'm not alone when I say I use VS Code as just a text editor and not an IDE, yet the editor still forces that annoying .vscode folder into any directory you open the program in. I don't need it to save project or workplace settings. I just want a good looking text editor without any residue of where it's been used. I'm getting tired of deleting the folder every single time. Please add an option to disable it.

**Comment by bpasero** [comment]
@8bitslime what files are in that folder and what contents?

**Comment by 8bitslime** [comment]
@bpasero It doesn't seem to be making the folder anymore. I remember it had only a .db file in it. I figured it was for storing workplace settings in a specific folder, but it seems to be gone, so problem solved? All I know is it was a hidden folder named ."vscode" and I couldn't find anything else about it online. I guess I'll come back to this thread if it shows up again with a more detailed description of it. Thanks for your time.

**Comment by bpasero** [comment]
@8bitslime we heard that the C++ extension was creating this file all the time, maybe they updated and fixed it?

**Comment by 8bitslime** [comment]
@bpasero It looks like the extension managed to uninstall itself; I'll take that as problem solved. Thanks. (but you may want to tell the guys working on the extension that the file should be opt-out)
