### ISSUE TITLE
输出控制待显示乱码

### ISSUE THREAD

**Issue by txm123-bye** [microsoft/vscode#109879]
Issue Type: <b>Feature Request</b>

见标题

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

**Comment by yume-chan** [comment]
Translation:

> # Output console text garbled
>
> See the title

**Comment by yume-chan** [comment]
Can you attach a scrrenshot showing your problem?

能发张截图吗？
