### ISSUE TITLE
VS code stuck infinitely 

### ISSUE THREAD

**Issue by MahmoudYounes** [microsoft/vscode#109811]
Hi all, I have a project where I mess around with some stuff. I copy pasted a token that is about 9500+ chars and now vscode is stuck forever. it prompts me to either reopen, keep waiting, or close.. none of those choices would unstuck vscode, and the UI thread is frozen so I can't actually execute any command to clear workspace cache to undo my changes. I am willing to give any debug trace info just point out where I can find it.

update:
I tried to start vscode without any extensions enabled:
code --disable-extensions

and still getting the same issue. the file that has the changes just freezes all vscode threads and there is no way I can close it from inside vscode

**Comment by alexr00** [comment]
What language mode(c++, perl, html, etc.) is the editor your pasting into set to? Can you share the token you pasted?

**Comment by MahmoudYounes** [comment]
C#. I can't share the token unfortunately!
