### ISSUE TITLE
(SSH) Automatic port forwarding

### ISSUE THREAD

**Issue by Fighter19** [microsoft/vscode#109819]
- VSCode Version: 1.50.1
- OS Version: Ubuntu 18.04

I'm not sure if this is intended behaviour or not, as I can see this being abused,
as the port-forwarding happens without user interaction.

When looking through the staged changes of an HTML file
while being connected to a remote PC via SSH, Visual Studio
automatically detected the URL and setup port-forwarding.

Steps to Reproduce:

1. Stage changes on an html file for example ```<form action="http://localhost:62345/hi" method="POST">```
2. Go into Terminal and type ```git diff --cached```
3. Watch Visual Studio automatically forward the port 62345 from the Remote to the Local PC.

**Comment by alexr00** [comment]
@Fighter19 this feature can be disabled with `"remote.autoForwardPorts": false`
