### ISSUE TITLE
Wrong Path Separator

### ISSUE THREAD

**Issue by shaonianruntu** [microsoft/vscode#109895]
Issue Type: <b>Performance Issue</b>

I am used to using the remote development function of vscode under Windows to connect to my Linux server for development. But when I drag files or folders under the PROJECT window in the sidebar to the remote TERMINAL, it always use the Windows path separator style, that is '\\' instead of '/', which makes me very confused. I think this maybe a functional defect or bug.

Following image shows the drag-and-drop effects of folders and files during testing:

![folder drag effect](https://user-images.githubusercontent.com/16336682/97961751-d5b89d80-1dee-11eb-85ec-f45f7d093b02.png)

![file drag effect](https://user-images.githubusercontent.com/16336682/97961652-aefa6700-1dee-11eb-97e4-d7aed99c76f1.png)

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.15.0-20-generic
Remote OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.60GB free)|
|Process Argv|--crash-reporter-id a3c9809e-fa4f-46f0-9d5e-187bbea6a34f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: titan|
|OS|Linux x64 4.15.0-20-generic|
|CPUs|Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz (20 x 3954)|
|Memory (System)|125.82GB (0.75GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 1080amax|
|OS|Linux x64 4.15.0-20-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 1202)|
|Memory (System)|125.79GB (117.13GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   142	  8636	code main
    0	    39	  1232	   utility
    0	    45	  3224	   utility
    0	    24	  9400	   crashpad-handler
    0	    90	 11168	   window (Issue Reporter)
    0	   367	 14808	   gpu-process
    0	    91	 15148	   shared-process
    0	   214	 16452	   window (option.py - project [SSH: 1080amax] - Visual Studio Code)
    0	     4	  4524	     C:\WINDOWS\System32\cmd.exe /c (type "C:\Users\fangn\AppData\Local\Temp\vscode-linux-multi-line-command-1080amax-932529594.sh" | ssh -T -D 64033 1080amax bash) & exit /b 0
    0	     8	  6440	       ssh  -T -D 64033 1080amax bash
    0	     6	 15000	     console-window-host (Windows internal process)
    0	    89	 20664	     extensionHost
    0	   239	 19548	   window (test_bisenetv2.py - project [SSH: titan] - Visual Studio Code)
    0	     4	  6580	     C:\WINDOWS\System32\cmd.exe /c (type "C:\Users\fangn\AppData\Local\Temp\vscode-linux-multi-line-command-titan-549401407.sh" | ssh -T -D 63251 titan bash) & exit /b 0
    0	     9	 17660	       ssh  -T -D 63251 titan bash
    0	     6	 16576	     console-window-host (Windows internal process)
    0	    92	 20400	     extensionHost

Remote: SSH: titan
CPU %	Mem MB	   PID	Process
    1	     0	 11314	remote agent
    0	     0	 11409	   extensionHost
    0	     0	 11447	     /bin/bash
    0	     0	 11640	     /home/fangnan/anaconda3/bin/python /home/fangnan/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py /home/fangnan/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/completion.py
    0	     0	 21661	       /home/fangnan/anaconda3/bin/python /home/fangnan/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python/jedi/inference/compiled/subprocess/__main__.py /home/fangnan/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python 3.8.3
    0	     0	 22222	       /home/fangnan/anaconda3/bin/python /home/fangnan/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python/jedi/inference/compiled/subprocess/__main__.py /home/fangnan/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python 3.8.3
    0	     0	 11919	     /bin/bash
    0	     0	 12024	     /home/fangnan/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node /home/fangnan/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=11409
    0	     0	 21259	     /home/fangnan/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node /home/fangnan/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=11409
    0	     0	 21712	     /bin/bash
    0	     0	 21764	     /bin/bash
    0	     0	 21803	     /bin/bash
    0	     0	 21835	     /bin/bash
    0	     0	 21919	     /bin/bash
    0	     0	 11422	   watcherService
    0	     0	 22408	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 22409	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Remote: SSH: 1080amax
CPU %	Mem MB	   PID	Process
    0	     0	 18523	remote agent
    0	     0	 18793	   extensionHost
    0	     0	 18820	     /bin/bash
    0	     0	 19835	     /home/fangnan/anaconda3/bin/python /home/fangnan/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py /home/fangnan/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/completion.py
    0	     0	 20305	       /home/fangnan/anaconda3/bin/python /home/fangnan/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python/jedi/inference/compiled/subprocess/__main__.py /home/fangnan/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python 3.8.3
    0	     0	 18874	   watcherService
    0	     0	 26926	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 26927	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: titan|    Folder (project): more than 56866 files|      File types: png(14369) jpg(254) py(102) pth(98) pyc(45) txt(13) 0(11)
|                  md(9) gitignore(5) xml(4)
|      Conf files: settings.json(1)
|  Remote: SSH: 1080amax|    Folder (project): more than 24200 files|      File types: jpg(17853) ckpt(705) py(690) pyc(126) png(64) 0(40) txt(37)
|                  md(12) sh(2) gif(2)
|      Conf files:;
```

</details>
<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer|Coe|1.0.61
remote-containers|ms-|0.145.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.1
vscode-remote-extensionpack|ms-|0.20.0
svg-preview|Sim|2.8.3
open-in-browser|tec|2.0.0
markdown-preview-github-styles|bie|0.1.6
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.1
todo-tree|Gru|0.0.186
kite|kit|0.134.0
rainbow-csv|mec|1.7.1
vscode-filesize|mkx|2.1.4
python|ms-|2020.10.332292344
cpptools|ms-|1.0.1
korofileheader|OBK|4.7.8
indent-rainbow|ode|7.4.0
svg-preview|Sim|2.8.3
vscode-wakatime|Wak|4.0.9
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by IllusionMH** [comment]
May be related to the fact that on Windows it's always copied in Windows style #56279

**Comment by Tyriar** [comment]
Looks like the path is being prepared based on the local path, not the remote path:

https://github.com/microsoft/vscode/blob/265a2f6424dfbd3a9788652c7d376a7991d049a3/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L600

**Comment by shaonianruntu** [comment]
> Looks like the path is being prepared based on the local path, not the remote path:
> 
> https://github.com/microsoft/vscode/blob/265a2f6424dfbd3a9788652c7d376a7991d049a3/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L600

It seems to be the case. 
This seems to be a setting that does not meet the requirements of the WSL develop environment. I hope that it can support the use of the corresponding path separator in the remote development environment in future versions.
