### ISSUE TITLE
Storage: remove IStorageKeysSyncRegistryService in favour of StorageTargets

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109896]
The `IStorageKeysSyncRegistryService` is a workaround for not having this information persisted inside `IStorageService`.

In `ben/storage-target` I pushed new API from `IStorageService` to tackle this:
* new `store2` method with new `StorageTarget`
* new `keys` method to get all keys for scope and target
* new `onDidChangeTarget` event whenever targets change for a scope

**Comment by bpasero** [comment]
Happened 👍

**Comment by bpasero** [comment]
@sandy081 I still noticed `IStorageKeysSyncRegistryService` exists, maybe it can be removed?

**Comment by sandy081** [comment]
It was used for syncing extensions state - removed it and introduced new service for syncing extensions state.
