### ISSUE TITLE
webRoot displays as "Property not allowed" in launch.json

### ISSUE THREAD

**Issue by alanosman** [microsoft/vscode#109810]
- VSCode Version: 1.50.1
- OS Version: Windows 10, build 19041.572

Steps to Reproduce:

1.  Added a configuration for Node.Js
2. Add line "webroot": ${workspaceFolder/app",
3. A squiggly appears under webRoot stating that it is not allowed

![image](https://user-images.githubusercontent.com/2914981/97805440-25973900-1c24-11eb-9ef3-2d75123f2d11.png)

Does this issue occur when all extensions are disabled?: Yes and also in the Insiders Version.

I was working on a nodeJS server project and trying to debug it.
My F9 debugger stops were not being picked up when I ran the code within Visual Code.  I did a web search and docs that state I should have webRoot as a variable.

When I add webRoot, the parameter works and I can stop code execution on F9 debug points.  Without it, the only way I can stop my code execution is to put a debugger; statement in line with the code.

**Comment by connor4312** [comment]
`webRoot` is only relevant when running chrome configurations. Please collect logs and I can take a look at what you're facing.

/jsDebugLogs
