### ISSUE TITLE
Make extentions similar to node modules .

### ISSUE THREAD

**Issue by WaelRabah** [microsoft/vscode#109805]
What I mean is that you should make it that when you open a new project in vs code , no extentions would be installed.
and then you can add extentions in the same way that you would do with node modules . 
I think this would reduce vscode's memory usage .
an example of this : 
I work on multiple projects and sometimes I use react , vue , python , .. and if I want to work on a python project then I only need the python extentions but instead all my other extentions are enabled consuming resources .
I think this is a useful feature for people like me who work with multiple languages and frameworks.

**Comment by yume-chan** [comment]
Yet another proporsal for extension group:

#105342 #108655
