### ISSUE TITLE
Only enable local echo in windows with a remote authority

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#109864]

**Comment by connor4312** [comment]
There are some benefits of not doing this:

- we can get latency telemetry from local terminals 
- typeahead works if running ssh directly in the terminal without explicitly being connected to a remote; there are quite a few users (as I've seen through debug issues) who do work remotely but without a remote extension

**Comment by Tyriar** [comment]
> typeahead works if running ssh directly in the terminal

Good point, latency is measured by a data response not actual latency to the program so this should work. My main interest though is dropping the on data, before data and csi listeners unless the feature is on as they can run hot which means a lot of callbacks that fire but don't do anything useful.

Some ideas:

- Don't listen to csi unless the feature is truly turned on
- Listen for when the program changes to `ssh` and at that point allow support outside of remote terminals, there's some code for this internally but it doesn't currently persists both process name and title in the same spot https://github.com/microsoft/vscode/blob/6acc9ff1eeb155b66d0a1548c2eba395846b0802/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1433-L1439

**Comment by Tyriar** [comment]
Here are more useful links for proc name:

https://github.com/microsoft/vscode/blob/6acc9ff1eeb155b66d0a1548c2eba395846b0802/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L914

I think ssh would get recognized as the shell for windows:

https://github.com/microsoft/vscode/blob/6acc9ff1eeb155b66d0a1548c2eba395846b0802/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L926

**Comment by connor4312** [comment]
I gave a shot at profiling this to get a baseline using a script that echo'd 64K CSI-wrapped characters

```
const chalk = require('chalk');
const strlen = 32;
const size = 1024 * 64;
const str = chalk.red('x\n').repeat(strlen);

for (let i = 0; i < size / strlen; i++) {
  process.stdout.write(str);
}
```

While taking a profile of this, the TerminalTypeAheadAddon didn't show up at all. This makes it hard for me to measure the impact of optimizations we make here, but I agree that unregistering the CSI listener while predictions aren't pending sounds like a good idea.

However because there appears to be an already-minimal overhead I think that may be sufficient to alleviate throughput concerns.

**Comment by Tyriar** [comment]
@connor4312 sounds good, would be good enough to not register the CSI listener 👍

**Comment by roblourens** [comment]
Verified by code review, I think
