### ISSUE TITLE
To be able to toggle windows

### ISSUE THREAD

**Issue by EpicPb** [microsoft/vscode#109885]
It would be nice to be able to open and close editors easily. Closing a group to allow a bigger view of the other groups only to re-open that same file you've closed is a hassle. It would be an amazing feature to quickly toggle groups instead of closing them.

**Comment by yume-chan** [comment]
> It would be nice to be able to open and close editors easily.

Do you mean you want to be able to hide and show editor groups... (#27203, #86641, #102088)

> Closing a group to allow a bigger view of the other groups only to re-open that same file you've closed is a hassle. 

Or merge two groups together?

**Comment by yume-chan** [comment]
If you mean the former, there is [another request](https://github.com/microsoft/vscode/issues/109771) which is currently open and you can up vote to make it happen
