### ISSUE TITLE
Suggest Widget: will not close on escape

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#109821]
Steps to Reproduce:

1.  Open a javascript file
2.  Input this code:

   const str = 'Test test1 test2'
   str.  // <= intellisense pops up string info

<kbd>Esc</kbd> will not close the suggestion widget.  <kbd>Shift</kbd>+<kbd>Esc</kbd> does close it.

Occurs in javascript files in Insider's Build - I have not seen it in my other languages (limited to css, html and json files) or Stable in any language.

Does this issue occur when all extensions are disabled?: Yes

Version: 1.51.0-insider (user setup)
Commit: 49696e87c64f478f97909a91d41ff2913df9bf71
Date: 2020-10-31T00:22:00.097Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20246

**Comment by jrieken** [comment]
This works for me. Please retry without extensions enabled. Select 'Extensions View > ... > Disable all Installed Extensions' and try again. Thanks. 

<img width="577" alt="screen shot 2018-05-09 at 08 45 10" src="https://user-images.githubusercontent.com/1794099/39799711-82d97e00-5365-11e8-8bd8-6b6fc3500370.png">

**Comment by ArturoDent** [comment]
Arg, sorry for the noise.  I had a keybinding I was testing some time back that was conflicting:

    {
      "key": "escape",
      "command": "editor.action.triggerParameterHints",
      "when": "editorHasSignatureHelpProvider && editorTextFocus"
    },

Disabled it and all is fine.  Sorry.

**Comment by jrieken** [comment]
You can add `!suggestWidgetVisible` to that when-clause and things should be working for you
