### ISSUE TITLE
Proposal: rewrite part of the module with WebAssembly for better performance.

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode#109824]
Currently, vscode has too much feedback about performance.

All issue pointed out that "it is too slow"

Page scrolling stuck, Unbearable type/suggestion delay, and more

As more functions to be added, it continues to bloat and will only get slower

Is there any official plan to improve performance?

Can some modules be rewritten via WebAssembly to improve performance? (It is browser compatible)

I believe many people are looking forward to this.

 Thanks vscode team.

**Comment by mjbvz** [comment]
We are always investigating how to improving performance. Super generic issue like this though are not helpful

If there's some part of the code that's slow, try profiling and then exploring how to make it faster (WebAssembly is not a magic bullet and could even make something slower if used poorly)
