### ISSUE TITLE
Conflict resolution title labels left side as "(in file)" even when a FileSystemProvider is being used

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#109844]
https://github.com/microsoft/vscode/blob/441698a621d78aa7305bd7aa84537096f1b0cf57/src/vs/workbench/contrib/files/browser/editors/textFileSaveErrorHandler.ts#L251

Can we have it display the value of `resource.scheme` instead of the fixed text "file"? When a FSP isn't involved this will still report "file".

Version: 1.51.0-insider (user setup)
Commit: 49696e87c64f478f97909a91d41ff2913df9bf71
Date: 2020-10-31T00:22:00.097Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
Sure, PR welcome.

**Comment by bpasero** [comment]
Actually closing as designed, I find "file" is true even for contributed file systems and has nothing to do with the file being local or not.
