### ISSUE TITLE
Add autocompleteAfter for bracket closing

### ISSUE THREAD

**Issue by chengyuhui** [microsoft/vscode#109838]
In rust, programmers generally write a lot of generics, i.e. `Arc<Mutex<Vec<T>>>`, so they made the choice to automatically close `<` with `>`. 
However, this quickly become annoying when writing algorithms with a lot of comparisons, as `x <` would become `x <>` (rust-lang/vscode-rust#798).
I wonder if we could have a `autocompleteAfter`, so that the bracket only closes when there is no space before, as people usually write `if x < 1` and `Result<T` (note the space before `<`).

**Comment by alexdima** [comment]
We have this situation in many languages. If there is ambiguity and the meaning of a token like `<` depends on the context, we recommend that the language simply does not define an auto closing pair for `<` and `>`. In our built-in language configuration for Rust, we do not define `<` and `>` as auto-closing pairs (see [here](https://github.com/AE1020/vscode/blob/a3658a2feedc94e12c52a8a9a0e91034faa13d10/extensions/rust/language-configuration.json#L11-L16)).

It looks like the `vscode-rust` extension decides to overwrite our defined language configuration and adds `<` and `>` as auto-closing pairs [here](https://github.com/rust-lang/vscode-rust/blob/c957ad5ff0eee266e9b2506ad3367fcef1f17cab/language-configuration.json#L16). So basically, this is an issue with the `vscode-rust` extension and you should open an issue with them to discuss it. Our recommendation is to remove `<` and `>` as auto-closing pairs if their meaning depends on context.
