### ISSUE TITLE
Attempted to update project that is not loaded

### ISSUE THREAD

**Issue by kiranraj20** [microsoft/vscode#109881]
Issue Type: <b>Bug</b>

Attempted to update project that is not loaded 
how much i try it wont work 
please help me
i am new to this.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.82GB free)|
|Process Argv|C:/Users/uset/platformer -g C:\Users\uset\platformer\Assets\scripts\player.cs:1:0 --crash-reporter-id 304e2ce9-a4fe-4795-8728-37aa142f7746|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.4

</details>

**Comment by yume-chan** [comment]
Can you describe what did you do in detail and what did it show? Better with screenshots.
