### ISSUE TITLE
Running/debugging extension tests does not work anymore

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#109853]
Version: 1.51.0-insider
Commit: 49696e87c64f478f97909a91d41ff2913df9bf71
Date: 2020-10-31T00:11:14.623Z

Tested on Ubuntu and Window

- create a new extension with `yo code`
- open the extension in VScode, 
- set a breakpoint in `src/test/suite/extension.test.ts`
- go to the debug viewlet, Run `Extension Tests`
- other window opens but immediately closes
Breakpoint not reached, no output to debug console
Sometimes the debug session is not terminated (debug toolbar stays present)

**Comment by weinand** [comment]
I cannot reproduce the issue on Window or linux.
@connor can you?

**Comment by connor4312** [comment]
Have you enabled the web worker extension host? If so you're probably running into https://github.com/microsoft/vscode/issues/104004

**Comment by aeschli** [comment]
Yes, I had the web worker ext host on. So sorry for that, I didn't realize that.

Duplicate of #104004
