### ISSUE TITLE
Delete file(s) permanently from context menu.

### ISSUE THREAD

**Issue by vuoriliikaluoma** [microsoft/vscode#109831]
I'd like Code to allow you to permanently delete files from the context menu the same way it works in Windows:
1. Right click a file to open the context menu.
2. Hold the <kbd>Shift</kbd> key.
3. Click the Delete option in the context menu.

This will give you the confirmation box to permanently delete the file(s). 

_I know I can just <kbd>Shift</kbd>+<kbd>Delete</kbd> the selected files._

**Comment by isidorn** [comment]
In VS Code it is Hold the `Alt` key.
Alt for alternative, and since that is more friendly for all platforms.

**Comment by kenny1983** [comment]
@isidorn Are you sure about that? `Alt+Delete` does nothing for me, and `Shift+Delete` gives me this: https://i.stack.imgur.com/q5338.png
