### ISSUE TITLE
please don't format exist code

### ISSUE THREAD

**Issue by leo1515416043** [microsoft/vscode#109843]
when format a file, please don't format exist code. I don't set default formatter, the file is in source control
![image](https://user-images.githubusercontent.com/48787027/97867462-e282b600-1d48-11eb-824d-53f87afb3296.png)

I tried this settings, but it not work
```
    "editor.formatOnSave": true,
    "editor.formatOnSaveMode": "modifications",
```

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, language mode of the file, and what extensions you have. Also, does the problem occur if you run with all extensions disabled?

**Comment by leo1515416043** [comment]
In my case,  below image is the answer.

![image](https://user-images.githubusercontent.com/48787027/97870884-92a6ed80-1d4e-11eb-8286-4d2e1c0fb587.png)
