### ISSUE TITLE
Locally, but exported, constants hurt minification (a little)

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109899]
Came across the const below and its siblings: https://github.com/microsoft/vscode/blob/2d7aacfa927dde260b6602f5fd45ff14d99c76d6/src/vs/workbench/browser/parts/notifications/notificationsCommands.ts#L21 

These are super long variable names which are exported but only used locally (inside the declaring file). This hurts minification because the export prevents its name from being shortened. 

<img width="482" alt="Screenshot 2020-11-03 at 10 37 19" src="https://user-images.githubusercontent.com/1794099/97969806-db978a00-1dc0-11eb-8ceb-c1312ed8c319.png">

**Comment by bpasero** [comment]
That would be a nice ESLint rule to have.
