### ISSUE TITLE
Cannot save as root: unable to find pkexec

### ISSUE THREAD

**Issue by Narice** [microsoft/vscode#109808]
- VSCode Version: 
```
1.50.1
d2e414d9e4239a252d1ab117bd7067f125afd80a
x64
```
- OS Version: NixOS 21.03pre249162.1dc37370c48 (Okapi)

Steps to Reproduce:

1. Modify a file owned by root
2. Try saving the file
3. Click on `Retry as Sudo...`
4. Error pops up: `Failed to save '...': Unable to find pkexec or kdesudo.`

Does this issue occur when all extensions are disabled?: Yes

The very strange thing is that I can use `pkexec code --file-write /path/to/source /path/to/target` and it works fine.

**Comment by bpasero** [comment]
This does not sound like a Linux distro we officially support. 

/duplicate https://github.com/jorangreef/sudo-prompt/issues/113
