### ISSUE TITLE
Serviço de Typescript interrompido

### ISSUE THREAD

**Issue by Crocetti** [microsoft/vscode#109848]
Nós escrevemos os dados necessários em sua área de transferência porque era muito grande para ser enviado. Por favor, Cole.
Issue Type: <b>Bug</b>

Inicialização do VSCode, inesperadamente emite mensagem de erro.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.94GB (1.53GB free)|
|Process Argv|--crash-reporter-id 55a6872b-489e-4def-8546-187e598790b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
html-snippets|abu|0.2.1
vscode-angular2-files|ale|1.6.4
ng-template|Ang|0.1001.0
angulardoc-vscode|Ang|6.1.3
blamer-vs|bea|0.5.2
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-svgviewer|css|2.0.0
angular-schematics|cyr|4.5.0
vscode-simpler-icons|dav|1.6.5
mustache|daw|1.1.1
vscode-eslint|dba|2.1.13
angular-extension-pack|dog|9.3.0
githistory|don|0.6.12
xml|Dot|2.5.1
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.1
vscode-firefox-debug|fir|2.9.1
vscode-jest-runner|fir|0.4.29
crypto-tools|fof|0.0.2
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
json2ts|Gre|0.0.6
rest-client|hum|0.24.3
angular2-switcher|inf|0.3.3
plantuml|jeb|2.13.14
plantuml|jke|1.8.1
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
svn-scm|joh|2.12.4
refactorix|kri|0.3.6
angular-extension-pack|loi|0.9.0
b64toJSON|luk|0.0.7
json-to-ts|Mar|1.7.5
Angular-BeastCode|Mik|10.0.3
vscode-language-pack-pt-BR|MS-|1.50.2
remote-wsl|ms-|0.50.1
powershell|ms-|2020.6.0
typescript-javascript-grammar|ms-|0.0.53
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
uuid-generator|net|0.0.4
ng-fortytwo-vscode-extension|NG-|0.0.9
angular-console|nrw|14.0.1
arrr|obe|0.1.3
material-icon-theme|PKi|4.4.0
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
karma-problem-matcher|rct|1.0.1
html5-boilerplate|sid|1.1.1
simontest|Sim|1.9.5
autoimport|ste|1.5.3
move-ts|str|1.12.0
html-preview-vscode|tht|0.2.5
pdf|tom|1.1.0
Angular2|UVB|0.4.1
vscode-todo-highlight|way|1.0.4
omnipascal|Wos|0.18.0
JavaScriptSnippets|xab|1.8.0
primengsnippets|yig|1.0.5

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
