### ISSUE TITLE
make my computer too laggy

### ISSUE THREAD

**Issue by zhumu3** [microsoft/vscode#109884]
Issue Type: <b>Bug</b>

new version vscode make my computer too laggy

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.66GB (0.67GB free)|
|Process Argv|--crash-reporter-id 5121c41a-c71b-4528-8de7-6ed7b4038e2f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by zhumu3** [comment]
i found **rg.exe** makes cpu so high,so i close file-prefrecenses-settings-search:follow symlinks.
this can fix this problem

**Comment by roblourens** [comment]
It can be slow in a workspace with many symlinks. Sounds like you found the right setting.
