### ISSUE TITLE
Color decorators not showing.

### ISSUE THREAD

**Issue by oxk4r01** [microsoft/vscode#109852]
- VSCode Version: 1.50.1
- OS Version: Windows 10 pro

Color decorators are only showed sometimes. After some lines they disappear:

![image](https://user-images.githubusercontent.com/1032224/97894126-6f6e4500-1d32-11eb-9604-ffe93b401485.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@aeschli is there log for us to check if LS is returning all color infos?

**Comment by oxk4r01** [comment]
And how can I get a log of this?

**Comment by aeschli** [comment]
yes, set `"json.trace.server": "verbose"` in the settings and check the 'JSON Language Server' output view.

**Comment by oxk4r01** [comment]
Ok, here is it:
`
[VSCode_log.txt](https://github.com/microsoft/vscode/files/5480503/VSCode_log.txt)
`

**Comment by oxk4r01** [comment]
Ok, here is it:

[VSCode_log.zip](https://github.com/microsoft/vscode/files/5480523/VSCode_log.zip)

**Comment by aeschli** [comment]
There should be a message `textDocument/documentColor`. Did you open the document with the color decorators?
Can you share the file?

Note that we have a maximum of color decorators that are transmitted. It is 5000 by default and can be configured by the setting `json.maxItemsComputed`.

**Comment by oxk4r01** [comment]
> There should be a message textDocument/documentColor. Did you open the document with the color decorators?
Can you share the file?

Can you elaborate, please? I'm not understanding what you exactly mean. Isn't that in the log I uploaded?
Color decorators are active all the time, I supose, but squares aren't rendered:

![image](https://user-images.githubusercontent.com/1032224/98090945-06e3ad00-1e85-11eb-9ef8-25ded176707a.png)

![image](https://user-images.githubusercontent.com/1032224/98090997-13680580-1e85-11eb-9def-263e4161ba52.png)

I changed  "json.maxItemsComputed": to 15000 but nothing happened.

**Comment by aeschli** [comment]
Ah, now I see. For the color decorators to show, the JSON schema that is associate with the document needs to specify that the property is a color.

E.g. that what the schema for color-theme.json specifies:

```json
{ 
	"settings": {
		"type": "object",
		"properties": {
			"foreground": {
				"type": "string",
				"description": "Foreground color for the token.",
				"format: "color-hex",
				"default": "#ff0000"
			}
		}
	}
}
```

**Comment by aeschli** [comment]
Closing as designed.
