### ISSUE TITLE
[Feature request] Provide shortcut keys and context menu action to clear the output windows

### ISSUE THREAD

**Issue by letientai299** [Microsoft/vscode#10989]
I want to trigger the __Clear output__ button without click into it.
There's should be a __Clear__ menu when right click into the Output window.

**Comment by sandy081** [comment]
Reason is that we do not want to have duplicate. I am closing this and wait to see if we get more requests for this.

Thanks

**Comment by letientai299** [comment]
I understand that the new context menu would be duplicate with the current button. But IMHO, right click anywhere in the Console or Output window, and press a character to trigger the *Clear* action is far easier to click into the button in top right corner.

How do you think?

**Comment by sandy081** [comment]
Instead of introducing one more UI action, I would think of introducing a new command for clearing console which can configured through a key board binding.

**Comment by isidorn** [comment]
I have added the clear output global workbench action, clear debug console was added last week and should be available in the insders vscode
