### ISSUE TITLE
Extension host crashes

### ISSUE THREAD

**Issue by QuentinHsu** [microsoft/vscode#109822]
- VSCode Version:
> Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
- OS Version: 
> Windows_NT x64 10.0.19042

Steps to Reproduce:

I can't reproduce it in a systematic way. This problem has been encountered in at least four recent updates, both in Git and SVN: VS Code suddenly shows a loss of version control for projects that have version tracking. Revert to an initial state without version tracking, which is obviously not desirable. Only reboot VS Code to restore the desired state. As shown.

![image](https://user-images.githubusercontent.com/21162238/97823866-38c60980-1cf5-11eb-8029-8a2bfcec0be9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
When in that state, what's the **full** output of `Git: Show Git Output`?

**Comment by QuentinHsu** [comment]
> When in that state, what's the **full** output of `Git: Show Git Output`?

I'm sorry, I'm not sure I understand what you're trying to say.

**Comment by joaomoreno** [comment]
Press <kbd>F1</kbd> and type `Git: Show Git Output`. A log view will appear, copy the entire contents and paste them here.

**Comment by QuentinHsu** [comment]
> Press F1 and type `Git: Show Git Output`. A log view will appear, copy the entire contents and paste them here.

I followed your prompts and got the following information:

> Looking for git in: C:\Program Files\Git\cmd\git.exe
Using git 2.29.0.windows.1 from C:\Program Files\Git\cmd\git.exe

But what I'm seeing is not just in Git, SVN is having the same problem in VS Code as well. So I think it's probably a problem with VS Code.
The version information for SVN is as follows:

> svn, version 1.14.0 (r1876290)
   compiled May 27 2020, 15:46:48 on x86/x86_64-microsoft-windows6.2.9200

**Comment by joaomoreno** [comment]
Are you sure you opened the correct folder with VS Code?

**Comment by QuentinHsu** [comment]
> 您确定使用VS Code打开了正确的文件夹吗？

Sure, it's all my business projects at the company.

**Comment by joaomoreno** [comment]
I mean: did you open a folder in VS Code?

**Comment by QuentinHsu** [comment]
> I mean: did you open a folder in VS Code?

Yes, and is the folder where the project is located.

In most cases, it will show the version control situation properly. However, in a few cases, it will display abnormally, as shown in the picture I posted at the beginning.

**Comment by joaomoreno** [comment]
OK when it happens again, open `Developer: Toggle Developer Tools` and see if you have any errors in the console.

**Comment by QuentinHsu** [comment]
> OK when it happens again, open `Developer: Toggle Developer Tools` and see if you have any errors in the console.

Ok.

**Comment by QuentinHsu** [comment]
When editing a project that uses SVN version management, the problem recurs as described before, and I open the console with the following error:

![image](https://user-images.githubusercontent.com/21162238/100065488-cddc9e00-2e6e-11eb-9e2b-2ec39098984d.png)

**Comment by alexdima** [comment]
@QuentinHsu All extensions share a single extension host process. When the extension host process crashes, all extensions go down until the extension host is restarted (or the window is reloaded). Unfortunately, any one of the extensions you have running (listed in the screenshot above) could be the reason of the crash.

In our latest insiders version, we have a command `F1 > Help: Start Extension Bisect` which will disable half of the extensions, asks you if the crash still reproduces or not, then narrows things down to either one half or the other, based on your answers.

But I can tell you from a quick look at your list that we have seen a higher than usual crash rate for extension hosts where `softwaredotcom.swdc-vscode` is running.
