### ISSUE TITLE
Cmd+O proposes wrong folder

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1098]
* be on mac
* git cmd+o
* > it open with the folder that you have opened last (like, `~/dev/vscode`) which is never a good choice because why would I open the folder which I opened last again? Instead it should open the folder from which I have opened the last folder (the parent of the current folder, `~/dev/`)

**Comment by bpasero** [comment]
Yeah I messed with this during the sprint...

**Comment by bpasero** [comment]
There is no right or wrong here btw, I am sure we can find users that don't like the behavior after my change.
