### ISSUE TITLE
node does not run from built in terminal

### ISSUE THREAD

**Issue by csakis** [Microsoft/vscode#10981]
- VSCode Version: 1.4.0
- OS Version: windows 10 1607

Steps to Reproduce:
**Node works:**
1. Open VS Code by double clicking on its icon.
2. Open terminal (ctrl-`).
3. Write node -v in terminal.
4. Everything works fine

**Node does not work:**
1. Open VS Code by right-clickin on a Folder and Opan in VSCode
2. Open terminal (ctrl-`).
3. Write node -v in terminal.
4. Node will not work.

**Comment by Tyriar** [comment]
What does it say when node doesn't work? If it says it can't find node then can you check your `echo %PATH%` to make sure it's on the path?

**Comment by csakis** [comment]
Node is in the path. If I open a command line and wrrite node -v, I get the
proper response. Furthermore, if I open VSCode normally just by duble
clicking on its icon and opening a terminal inside VSCode the node -v
command works.
However is I open VSCode by right clicking on a folder and telling it to
open in VSCODE, the terminal inside VSCode does not see node.

**Comment by Tyriar** [comment]
Please tell me the exact message, "node will not work" and "vscode does not see node" is very ambiguous.
