### ISSUE TITLE
snippet suggestion does not appear when use specific prefixes

### ISSUE THREAD

**Issue by almaceleste** [microsoft/vscode#109871]
Issue Type: <b>Bug</b>

1. add to the `~/.config/Code/User/snippets/r.json` file:
```json
     "assignment operator": {
        "prefix": ["<-", "="],
        "body": [
			"<- "
		],
        "description": "assignment operator"
    },
    "magrittr pipe": {
        "prefix": ["%>%", ">"],
		"body": [
			"%>%",
			"\t$0"
		],
        "description": "magrittr pipe"
    }
```
2. open .r file and type `<`, `=` or `>` - snippet suggestion does not appear, but if press `Ctrl`+`Space` it is in the dropdown list.
3. type `-` or `%` and snippet suggestion appears automatically, without `Ctrl`+`Space`.

note: strange, that for `javascript.json` prefix `<` works, but `>` does not.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.4.0-52-lowlatency

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.57GB (1.65GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 0bfd8309-f876-4390-99c3-dddd9b122049|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.6.7
unique-lines|bib|1.0.0
file-properties-viewer|bru|0.5.0
npm-intellisense|chr|1.3.1
regex|chr|0.2.0
vscode-translate|chu|0.1.5
vscode-quick-select|dba|0.2.9
apt-source-list-syntax|dei|0.1.5
gitlens|eam|10.2.2
vscode-npm-script|eg2|0.3.13
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
code-runner|for|0.11.1
shell-format|fox|7.0.1
seito-openfile|Fr4|1.8.7
vscode-pull-request-github|Git|0.20.1
shortcuts|giz|0.0.1
name-that-color|gui|0.1.2
rest-client|hum|0.24.3
r|Iku|1.5.2
reg|ion|1.0.1
AWK|lug|0.0.2
python|ms-|2020.10.332292344
cpptools|ms-|1.0.1
powershell|ms-|2020.6.0
vscode-github-issue-notebooks|ms-|0.0.57
debugger-for-chrome|msj|4.12.11
reload|nat|0.0.6
linesinfostatusbar|pet|0.0.3
vscode-css-peek|pra|4.0.0
bracketeer|pus|1.3.1
vscode-data-preview|Ran|2.2.0
r-lsp|REd|0.1.11
LiveServer|rit|5.6.1
color-manager|roy|0.6.1
csspreview|san|1.0.4
trailing-spaces|sha|0.3.1
vscode-scheme|sjh|0.4.0
code-spell-checker|str|1.9.2
code-spell-checker-russian|str|0.2.8
code-spell-checker-spanish|str|1.0.6
open-in-new-instance|syd|1.2.1
open-window-tab-context|tak|1.4.2
pdf|tom|1.1.0
autocomplate-shell|tru|0.1.1
vscodeintellicode|Vis|1.2.10
open-in-external-app|YuT|0.2.1

</details>

**Comment by jrieken** [comment]
Yes - quick suggestions (suggestions as you type) only appear when typing at word ends not when typing arbitrary characters. This is done to prevent unwanted showings of the suggest widget

**Comment by almaceleste** [comment]
as-designed?! really?!!
javascript file (just pressed `<`, not pressed `ctrl`+`space`):
![image](https://user-images.githubusercontent.com/36765595/98016709-5dae9f80-1e0f-11eb-9fb2-5d235bf51ca9.png)
r file (just pressed `<`):
![image](https://user-images.githubusercontent.com/36765595/98017106-d7df2400-1e0f-11eb-8351-8a4c0173a970.png)
r file (pressed `ctrl`+`space`):
![image](https://user-images.githubusercontent.com/36765595/98017195-f8a77980-1e0f-11eb-9845-baaf24eb428d.png)
are these different behaviors really intended from by design?!! why?!!

**Comment by jrieken** [comment]
>  why?!!

because `<` is a trigger character for JS

**Comment by almaceleste** [comment]
> because `<` is a trigger character for JS

trigger to what?
I can create snippets for trigger characters only?
if so, where can I see the entire list of trigger symbols?
