### ISSUE TITLE
Access Denied Issue

### ISSUE THREAD

**Issue by Santosh-Goyal** [microsoft/vscode#109827]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

Codes are not running.
It keep saying that  "We can't open this file , Access is denied" , whenever i try to run my C++ code

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (3.59GB free)|
|Process Argv|--crash-reporter-id 1f0ca0e8-747e-4e7d-8a7e-cb17b96328e9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    78	  2032	code main
    0	   157	  4908	   window (Sample1.cpp - Visual Studio Code)
    0	    85	  9256	     extensionHost
    0	    23	  1996	       c:\Users\santo\.vscode\extensions\ms-vscode.cpptools-1.1.0-insiders3\bin\cpptools.exe
    0	    42	   612	         "c:\Users\santo\.vscode\extensions\ms-vscode.cpptools-1.1.0-insiders3/bin/cpptools-srv.exe" 1996 0
    0	    11	  1772	         console-window-host (Windows internal process)
    0	   126	  5056	   gpu-process
    0	    14	  6268	   crashpad-handler
    0	    25	  6716	   utility
    0	    65	  8816	   window (Issue Reporter)
    0	    67	 10548	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.1
cpptools|ms-|1.1.0-insiders3

</details>

**Comment by Santosh-Goyal** [comment]
![image](https://user-images.githubusercontent.com/73796571/97833864-65315400-1cfc-11eb-9489-a3b3f38df68b.png)

**Comment by Santosh-Goyal** [comment]
I just send the screen shot of the problem i am facing on my comment box

**Comment by dishantrathi** [comment]
@Santosh-Goyal Try executing again with Admin Mode

**Comment by Santosh-Goyal** [comment]
And how can i use the admin mode?
Can you please tell me the procedure or steps.

**Comment by dishantrathi** [comment]
Run VS Code as Admin!

**Comment by Santosh-Goyal** [comment]
After running the VS Code as admin then also i am getting the same issue.
That the access is denied.
