### ISSUE TITLE
My intellisense for c# is not working

### ISSUE THREAD

**Issue by NewLobster3798** [microsoft/vscode#109893]
Issue Type: <b>Bug</b>

intellisence for c# is not working even though i download many extensions followed the steps written that page and downloaded  that something sdk file 
still not working

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.87GB free)|
|Process Argv|C:/Users/roshani patel/Desktop/unity projects/learning unity -g C:\Users\roshani patel\Desktop\unity projects\learning unity\Assets\player.cs:1:0 --crash-reporter-id 53584be4-4df9-46b5-aa7a-19f270e9785a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.4
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0

</details>

**Comment by yume-chan** [comment]
I see you have installed the C# extension, and since it's not working, maybe it's better to report an issue there.

From https://github.com/OmniSharp/omnisharp-vscode/issues/new

> 1. Open Visual Studio Code
> 2. Bring up the command palette (press <kbd>F1</kbd>)
> 3. Type `CSharp: Report an issue`

Please include details of what you have done and what error message (if any) it shows.
