### ISSUE TITLE
Removing last Explorer section except Folders also removed the Folders section header

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoft/vscode#109804]
Issue Type: <b>Bug</b>

Removing the last Explorer section except Folders also removes the header of the Folder section in a manner that appears to leave a graphical artifact.

There's no obvious reason why removing the last optional Explorer section should remove the Folders (non-optional Explorer section) header at all.

![ExplorerBug1](https://user-images.githubusercontent.com/18445931/97801928-fbe80d00-1c37-11eb-95e3-98ed55d8e080.png)
![ExplorerBug2](https://user-images.githubusercontent.com/18445931/97801931-fee2fd80-1c37-11eb-8104-09a3325b680c.png)
![ExplorerBug3](https://user-images.githubusercontent.com/18445931/97801934-02768480-1c38-11eb-940c-ec05535e4600.png)

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
rtf|ale|2.2.0
ng-template|Ang|0.1001.0
EditorConfig|Edi|0.15.1
vscode-great-icons|emm|2.1.57
vscode-jasmine-test-adapter|hbe|1.7.0
vscode-test-explorer|hbe|2.19.1
classic-asp|ili|0.0.4
vscode-nuget-package-manager|jmr|1.1.6
vscode-docker|ms-|1.7.0
csharp|ms-|1.23.2
debugger-for-chrome|msj|4.12.11
rewrap|stk|1.13.0
indent-one-space|use|0.2.6
html-css-class-completion|Zig|1.19.0

</details>

**Comment by yume-chan** [comment]
If there is only one viewlet in a pane, the viewlet's title and actions will merge with pane's title.

Your sidebar is just to narrow to display the title.

![image](https://user-images.githubusercontent.com/1330321/97822874-331af480-1cf2-11eb-9503-43bb705fcb20.png)

Maybe this can be somehow improved...

**Comment by isidorn** [comment]
We have no plans to change this.
We actually like that when you have one view they get merged to save on vertical space. I personally always use it like that
