### ISSUE TITLE
When 2 extensions contribute the same submenus it is duplicated instead of merged

### ISSUE THREAD

**Issue by devinea** [microsoft/vscode#109818]
- VSCode Version: 1.50.1
- OS Version: macos 10.15.7

Steps to Reproduce:

1. Create 2 extensions that contribute the same submenu with different sub menu items. 
See extension 1 

https://github.com/devinea/code_submenus/blob/main/code1/package.json#L22-L45

and extension 2

https://github.com/devinea/code_submenus/blob/main/code2/package.json#L24-L46

2. When both extensions are installed the `Tools` menu appears 2 times and the content from 2 the extensions is shown in both. 
<img width="430" alt="Screenshot 2020-11-01 at 21 25 56" src="https://user-images.githubusercontent.com/10102054/97815994-016e4300-1c8a-11eb-87ea-b020a565f6fb.png">
<img width="491" alt="Screenshot 2020-11-01 at 21 25 50" src="https://user-images.githubusercontent.com/10102054/97815997-0501ca00-1c8a-11eb-9d16-e5550c09d479.png">

I would like for multiple of my extensions (part of a suite) to contribute to the same `Tools` menu and the sub menu items from each extension shown within.
If I remove the following from the config of 1 of the 2 extensions the desired UX is achieved when both are installed.
```
      "explorer/context": [
        {
          "label": "Tools",
          "submenu": "tools",
          "group": "1_modification@1"
        }
      ],
```
<img width="407" alt="Screenshot 2020-11-01 at 21 56 33" src="https://user-images.githubusercontent.com/10102054/97816439-329c4280-1c8d-11eb-8f80-b22f77befb61.png">

But when launching the extension with `explorer/context` removed without the other installed the menu item does not appear. This is particularly annoying when developing and launching for debugging.

Does this issue occur when all extensions are disabled?: No

**Comment by devinea** [comment]
Hi @joaomoreno, 
Thanks for taking a look at this issue. I see you've added a commit https://github.com/microsoft/vscode/commit/98262ef05017cc79ab33be09a2de921c4141ada4 .
If I read this right it would prevent the second extension activating if the  same submenu id is used?

This will prevent extensions adding items to the same submenu which I think is really useful.
Would you consider allowing it and merging the menu duplicate entry instead of blocking it?

**Comment by joaomoreno** [comment]
It won't prevent any extension from being activated. It will simply not register that second submenu. The first submenu registration wins. All menu items contributed to that submenu (from both extensions) will be merged into the submenu. Can I ask you to verify once the Insiders build is out tomorrow?

**Comment by devinea** [comment]
Thanks. Sounds good @joaomoreno. I'll try it tomorrow.

**Comment by devinea** [comment]
Hi @joaomoreno 
I retested with 
```
Version: 1.51.0-insider
Commit: fce8fc82cacf0b4e2a18c633b6c6f3058702a5c9
Date: 2020-11-02T19:41:03.269Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
And still see the same behaviour

<img width="539" alt="Screenshot 2020-11-03 at 11 02 26" src="https://user-images.githubusercontent.com/10102054/97977535-40a0af00-1dc4-11eb-91d5-674e423d4a1e.png">
<img width="582" alt="Screenshot 2020-11-03 at 11 02 15" src="https://user-images.githubusercontent.com/10102054/97977545-45656300-1dc4-11eb-8eab-d2629b2e13cd.png">

**Comment by joaomoreno** [comment]
Are you absolutely sure both menus have the exact same ID?

**Comment by joaomoreno** [comment]
OK never mind, something was indeed missing, thanks for checking! Do you mind verifying again on the next insiders? Thanks a bunch! 🙏

**Comment by devinea** [comment]
Thanks for checking @joaomoreno 
Here is the samples I am using https://github.com/devinea/code_submenus/ 
Attached is a zip of the 2 vsix files. 
[example_extensions.zip](https://github.com/microsoft/vscode/files/5487807/example_extensions.zip)

I'll test again tomorrow. Thanks.

**Comment by devinea** [comment]
@joaomoreno 
I've retested with 
```
Version: 1.51.0-insider
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-04T18:28:58.019Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```


and still see duplicate menus
![Screenshot 2020-11-05 at 15 37 41](https://user-images.githubusercontent.com/10102054/98262190-38d83a80-1f7d-11eb-997d-68afa9a2d69e.png)

Thanks

**Comment by gjsjohnmurray** [comment]
@devinea Insiders is currently tracking the upcoming 1.51 release, so I think you'll need to wait until endgame has completed and Insiders About dialog starts reporting as 1.52. Maybe as soon as tomorrow.

**Comment by joaomoreno** [comment]
Yeah I forgot that we're currently locking down Insiders for the release... Thanks @gjsjohnmurray!

And thanks again @devinea, love the passion!

**Comment by devinea** [comment]
🎉  Confirmed working with 
```
Version: 1.52.0-insider
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:39:23.276Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
![Screenshot 2020-11-06 at 10 31 15](https://user-images.githubusercontent.com/10102054/98356265-39bfa980-201b-11eb-8499-834ab30be760.png)


Many thanks @joaomoreno

**Comment by devinea** [comment]
`/verified`

**Comment by joaomoreno** [comment]
Awesome, thanks a bunch! @devinea
