### ISSUE TITLE
[themes] theme names are all not localized

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode#109840]
- VSCode Version: 1.50.1

Steps to Reproduce:
1. Install VScode and Language Extension Chinese(Simplified)
2. Set the Display Language to "zh-cn" and restart VScode
3. Input "theme" in command palette and observe the theme name

Expected:
Theme name are all localized

Actual:
Theme name are all not localized
(Repro on Windows, Linux and Mac)
![image](https://user-images.githubusercontent.com/37648162/97855537-d6412d80-1d35-11eb-88c8-48da6c8e0da7.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
The labels of the themes now can be translated. It will be up to the translation team to decide how and whether to use a translated name.
Note: the settings id will remain the same as to not break any users with existing settings.
