### ISSUE TITLE
Auto collapse node_modules if no file within it is opened

### ISSUE THREAD

**Issue by WangHansen** [microsoft/vscode#109820]
Currently, if I try to look into some of the sources code of the libraries by `go to implementation`, the explorer will open the file location: 
<img width="278" alt="截屏2020-11-01 下午5 45 23" src="https://user-images.githubusercontent.com/15679461/97817368-07542c00-1c6a-11eb-9b95-70a1249d32e0.png">

After I closed the window, the explorer remain this way. So if I want to see my src files, I have to scroll through the infinitely long list of `node_modules` to manually collapse it so that I can see my own files.

It would be really nice if `node_modules` folder can automatically collapse if no file within it is open. 
If that is hard to detect, an easier way is to always collapse the folder in explorer when a file window is close.

**Comment by yume-chan** [comment]
My solution is hide "node_modules" in explorer (`files.exclude`) and use [Search node_modules extension](https://marketplace.visualstudio.com/items?itemName=jasonnutter.search-node-modules) if I need to manully open a file there.
