### ISSUE TITLE
mistake in vsc document

### ISSUE THREAD

**Issue by hayoung123** [microsoft/vscode#109845]
- VSCode Version: ---
- OS Version: ---
there is a mistake video in Logpoints  
there's a video of fibonacci algorithm. but it's wrong.
https://code.visualstudio.com/docs/editor/debugging

Steps to Reproduce:

1.  revise the documents like this code
```
function fibonacci(n) {
  if (n < 2) return n;
  const result = fibonacci(n - 1) + fibonacci(n - 2) 
  return result;
}
```

Does this issue occur when all extensions are disabled?: No

**Comment by weinand** [comment]
@hayoung123 thanks for spotting this.
