### ISSUE TITLE
Static noise after wake from sleep/suspend [with temp solution] 

### ISSUE THREAD

**Issue by smac89** [microsoft/vscode#109856]
- VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
- OS version: Linux x64 5.8.14-arch1-1

Steps to Reproduce:

1. Restart vscode, and make sure the minimap to the right is visible
3. Sleep the machine
4. Wake after 1 minute or so, and notice the minimap to the right is covered in static

Does this issue occur when all extensions are disabled?: Yes/No
**Yes**

---

#### Before disabling all extensions:
![ArcoLinux_2020-11-02_11-11-44](https://user-images.githubusercontent.com/8305511/97900640-d8ee5380-1d32-11eb-9d22-3368b0de5830.png)

#### After disabling all extensions:
![ArcoLinux_2020-11-02_11-38-35](https://user-images.githubusercontent.com/8305511/97900679-ea376000-1d32-11eb-9ab3-a7f6ccfc02e2.png)

---

### Temporary Solution

After browsing a [few](https://github.com/microsoft/vscode/issues/68346) [issues](https://github.com/microsoft/vscode/issues/58167) related to this one, I found [one](https://github.com/microsoft/vscode/issues/69665) that was still open, which provides a [workaround for this issue](https://github.com/microsoft/vscode/issues/69665#issuecomment-716758361).

So after I disabled hardware rendering: `"disable-hardware-acceleration": true,`, and restarted vscode, I don't experience this problem anymore.

**Comment by deepak1556** [comment]
Can you check if the issue happens with our [exploration builds](https://az764295.vo.msecnd.net/exploration/b09dd7858771abf03f0abad6f5a5704839c13dd7/code-exploration-x64-1604559647.tar.gz) that comes with newer runtime.

**Comment by smac89** [comment]
I'm sorry to report that even this one was worse.

#### Before sleeping:
![ArcoLinux_2020-11-06_12-21-01](https://user-images.githubusercontent.com/8305511/98401404-86c46f80-205d-11eb-9ba1-8f3db46083fe.png)

#### After sleeping:
![ArcoLinux_2020-11-06_12-24-21](https://user-images.githubusercontent.com/8305511/98401437-9643b880-205d-11eb-950a-bd748aefe03c.png)

#### After moving the window to see if the display is restored:
![ArcoLinux_2020-11-06_12-19-28](https://user-images.githubusercontent.com/8305511/98401507-b5dae100-205d-11eb-978c-f1715f5673c9.png)

As you can see, this version really doesn't help. In fact, it renders the IDE unusable after waking from sleep.

**Comment by deepak1556** [comment]
> So after I disabled hardware rendering: "disable-hardware-acceleration": true,, and restarted vscode, I don't experience this problem anymore.

Does it help with the exploration version as well ?

**Comment by smac89** [comment]
> Does it help with the exploration version as well ?

Yup. Enabling that option definitely seems to fix the problem, as it does on the regular versions

**Comment by deepak1556** [comment]
Thanks for confirming, this would be a gpu issue that should fixed in the runtime. For now you can use the workaround, closing as its outside the scope of vscode.
