### ISSUE TITLE
Code is Not Running

### ISSUE THREAD

**Issue by Santosh-Goyal** [microsoft/vscode#109817]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

[Running] cd "c:\Users\santo\OneDrive\Documents\C++\" && g++ Sample1.cpp -o Sample1 && "c:\Users\santo\OneDrive\Documents\C++\"Sample1
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: cannot open output file Sample1.exe: Permission denied
collect2.exe: error: ld returned 1 exit status

[Done] exited with code=1 in 0.432 seconds

Above one is the o/p i get for every run.
Can you please guide me.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (3.87GB free)|
|Process Argv|--crash-reporter-id 1f0ca0e8-747e-4e7d-8a7e-cb17b96328e9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.1
cpptools|ms-|1.1.0-insiders3

</details>

**Comment by Santosh-Goyal** [comment]
Please help me guys

**Comment by Hitesh-Patil-creator** [comment]
Try running as admin

**Comment by Santosh-Goyal** [comment]
After Running the app as an administrator then also i am facing the
same problem.
That the access is denied.

**Comment by Tyriar** [comment]
What shell are you using? And does this work when you run it in Windows Terminal?

**Comment by Santosh-Goyal** [comment]
Now I get the problem and solve it. Thank you for your kind concern.


Sent from Mail for Windows 10
