### ISSUE TITLE
Unable to search content in un-opened file of the project

### ISSUE THREAD

**Issue by HermanZzz** [microsoft/vscode#109886]
- VSCode Version: 1.49.2
- OS Version: macOS 10.15.6

Steps to Reproduce:

1. I can only search for things about the opened file of the project and the search is infinitely loading.
<img width="722" alt="1" src="https://user-images.githubusercontent.com/8086434/97173352-611ca800-17cb-11eb-8f5a-a468d0392bdd.png">

2. Unable to find text in an un-opened file.
![1](https://user-images.githubusercontent.com/8086434/97955104-56bc6880-1de0-11eb-901a-4d3b95c41ea8.png)

3. Search works fine when I  launch with `code --disable-extensions`. But not for even I disable all the extensions manually.
<img width="487" alt="3" src="https://user-images.githubusercontent.com/8086434/97173555-b9ec4080-17cb-11eb-9814-88a0cd5fc63a.png">

reproduce gif: 
![](https://user-images.githubusercontent.com/8086434/97252389-cd87bd80-1844-11eb-9232-748d7957875b.gif)

Does this issue occur when all extensions are disabled?: No

**Comment by yume-chan** [comment]
Please don't open another issue for the same problem.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/109371
