### ISSUE TITLE
Does not close on stopping KDE/Plasma activity

### ISSUE THREAD

**Issue by MagicMuscleMan** [microsoft/vscode#109825]
KDE/Plasma has a concept named activities, which are some sort of extended and persistent virtual desktops. Activity handling uses (AFAIK) X session save/restore mechanisms to stop a set of applications in one activity (virtual desktop) and start the programs (restoring state) only when needed again saving a lot of RAM with little reduction of comfort.

Current behavior:
When stopping an activity which includes vscode, the activity is closed and all applications are closed with the exception of vscode. It's not visible any more but its processes still exist and still consume 300 MB memory.

Expected behavior:
When stopping an activity vscode should stop, too.

Current workaround:
You can restart the activity again, close vscode manually and close the activity again. But then vscode does not get startet the next time you start the activity automatically, so you have to manually start vscode, too, kind of defeating the purpose of the activity in the first place.

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/97395
