### ISSUE TITLE
editor.action.goToDeclaration not working

### ISSUE THREAD

**Issue by mcakircali** [microsoft/vscode#109803]
- VSCode Version: 1.50.1
- OS Version: Windows 10 x64 10.0.19042
- Extension: ms-vscode.cpptools (Version: 1.0.1)

## Steps to Reproduce:

1. Set the setting: 
"editor.gotoLocation.alternativeDefinitionCommand": "editor.action.goToDeclaration"
2. Create two files; header and source as given in example program below.
3. Locate the definition in the source file and press F12 (Go To Definition Hotkey).

## Expected behavior:

The cursor should jump to the declaration in the header file.

## Example program

**headerfile.h**
```
struct Basic {
    Basic(); // this is declaration
};
```

**source file**

```
#include <iostream>
#include "headerfile.h"
Basic::Basic()
{
    std::cout << "This is definition." << std::endl;
}

int main()
{
    Basic test;
}
```

**Comment by jrieken** [comment]
Missing: what language? what extension? concrete code sample to repro

**Comment by mcakircali** [comment]
> Missing: what language? what extension? concrete code sample to repro

Please find the additional information in the description.

**Comment by jrieken** [comment]
Thanks for the update. Please file this issue against the Cpp extension as they are computing those results
