### ISSUE TITLE
no quick fix for available for 'unused imports'

### ISSUE THREAD

**Issue by zillionare** [microsoft/vscode#109876]
- VSCode Version: 1.50.1
- OS Version:Windows_NT x64 10.0.19042 working on WSL ubuntu

Steps to Reproduce:

the code is something like
`import datetime
import logging
from typing import TYPE_CHECKING, Iterable, List, Optional, Union
`

the linter is flake8 (with pylint the issue still exists), and it already reports unused imports, but no quick fix suggestion

![图片](https://user-images.githubusercontent.com/7206696/97944498-cff79380-1dbf-11eb-81dc-90f4bcaf7729.png)

the only extensions I installed are pylance and python

Expected:

vscode can auto remove unused imports

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
> It looks like this is caused by the Python extension. Please file it with the repository here. Make sure to check their issue reporting template and provide them relevant information such as the extension version you're using. See also our issue reporting guidelines for more information.
> 
> Happy Coding!
