### ISSUE TITLE
Too much bash.exe

### ISSUE THREAD

**Issue by Its-Just-Nans** [microsoft/vscode#109982]
- VSCode Version:  **1.50.1**
- OS Version: **Windows 10 - 1909** & **Windows 10 Family - 2004**

Steps to Reproduce:

1. Just open 32 bash.exe in terminal
2. Try open a new bash.exe in terminal
3. You will see that error
![image](https://user-images.githubusercontent.com/56606507/98169535-bd2ead00-1eec-11eb-994e-6cdf36ccf909.png)

Maybe the number 32 is the limit for my computer, maybe the limit changes depending on the computer (but I checked on another computer and it's the same).

I did'nt check on other terminal like powerShell and all others possible terminals.

Its is not a big error but maybe if visualCode can just say "Too much terminal", it would be cool !

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by rzhao271** [comment]
This might be specific to git bash. Cannot reproduce on WSL.
