### ISSUE TITLE
Search by file name needs full path

### ISSUE THREAD

**Issue by evs-xsarus** [microsoft/vscode#109900]
When searching for a file, it's needed to give no path or the full path. But even in the first situation, the file isn't always found.

![2020-10-30_hard_to_find_file](https://user-images.githubusercontent.com/44158071/97970356-b2c3c480-1dc1-11eb-9c81-2a54185e647d.gif)

**Expected behavior**
When searching on the filename only, have the results start with at least all files with that name. When including part of the path, do a partial match.

- VSCode Version: 1.50.1
- OS Version: Ubuntu Unity 20.04.1

**Steps to Reproduce:**

Create a file 'vendor/activeants/magento2-logistics/Model/Servicepoints.php' and search for:

* 'Servicepoints.php'
* 'activeants/magento2-logistics/Model/Servicepoints.php'

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Please check these tips: https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results

Is your vendor folder in your .gitignore or an exclude setting?

**Comment by evs-xsarus** [comment]
The vendor folder is included. As you can see in the animation, I do find the file, but only with a full path or only the filename.

**Comment by roblourens** [comment]
When you type the full path, we will match even if the file is excluded, which makes me think that is the issue, so please double-check.

**Comment by evs-xsarus** [comment]
When searching with CTRL+SHIFT+F, I always turn of "Use Exclude Settings and Ignore Files". Have done it in settings now too.

![image](https://user-images.githubusercontent.com/44158071/98337636-37545400-2009-11eb-8e97-402af6fbaf4a.png)

This indeed seems to work. Might be usefull to add the same icon to the file search panel. E.g.:

![image](https://user-images.githubusercontent.com/44158071/98338034-ceb9a700-2009-11eb-931a-c534b2a36127.png)

**Comment by roblourens** [comment]
👍 there is an open issue for that possibility
