### ISSUE TITLE
window problem

### ISSUE THREAD

**Issue by madipta** [microsoft/vscode#109941]
Issue Type: <b>Bug</b>

missing close, minimize, maximize button 
cannot move window 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.8.0-7625-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3180)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|11.58GB (7.64GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 7073186a-b7ed-42bd-854e-b27a6f4a8681|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.12
prettier-vscode|esb|5.7.1
vscode-jest-runner|fir|0.4.29
Angular-BeastCode|Mik|10.0.3
vscode-docker|ms-|1.7.0
vscode-typescript-tslint-plugin|ms-|1.2.3
angular-console|nrw|14.0.1
material-icon-theme|PKi|4.4.0

</details>

**Comment by madipta** [comment]
the buttons appears after i changed Title Bar Style to "custom", it's okay now but the native is much nicer look

**Comment by sbatten** [comment]
@madipta can you provide full screen shot of the native title bar so I can understand your environment.
