### ISSUE TITLE
Test: multi line debug repl input

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#10996]
Test for #8115
Complexity: 2

- [x] win **@octref**
- [x] mac **@kieferrm**
- [x] Linux **@rebornix**

Debug repl input now expands / shrinks as the input grows up to a limit. Verify:
* Typing / pasting large strings into the debug repl input makes the input expand
* Shift + enter expands the input
* Input shrinks intuitivly
* Once entered the expression is properly displayed in the debug repl

**Comment by rebornix** [comment]
The only valid issue I found right now is #11245. But I'm still unclear about the shrinking feature, I've put about 10k lines of string into the input box but seems no shrinking happens, let me know if I'm doing wrong or it's an issue indeed.

**Comment by octref** [comment]
I'm able to repro #11245 in Win 10. Other than that it works fine.
