### ISSUE TITLE
lagging while scrolling and typing

### ISSUE THREAD

**Issue by devexus** [microsoft/vscode#109922]
Issue Type: <b>Performance Issue</b>

When I restart laptop and run VS Code, everything is fine. I don't have any lags, but after an hour it starts lagging. I disabled all extensions and it still has lags. I runned vs code with "disable GPU" option and it also doesn't help. I was looking for any solutions, but I cannot find any. Can someone help me? 

Any other application works perfect. 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.52GB free)|
|Process Argv|--crash-reporter-id abd5d41e-7ee8-4349-8e2f-a6e72da3722a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    93	 12344	code main
    0	    79	  6808	   gpu-process
    0	    24	  7660	   crashpad-handler
    0	    38	 14320	   utility
    1	    62	 30548	   shared-process
    2	    85	 32088	   window (Issue Reporter)
    0	   310	 33564	   window (_reset.scss - cip-react - Visual Studio Code)
    0	   113	 18076	     extensionHost
    0	   116	 11320	       electron_node tsserver.js 
    0	   291	 11684	       electron_node tsserver.js 
    0	    85	 16612	         electron_node typingsInstaller.js typesMap.js 
    0	    72	 19048	       "D:\Programs\Microsoft VS Code\Code.exe" "d:\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=18076
    0	    70	 30676	       "D:\Programs\Microsoft VS Code\Code.exe" "d:\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=18076
    0	    12	 25140	     watcherService 
    0	    11	 17108	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (_reset.scss - cip-react - Visual Studio Code)
|    Folder (cip-react): 1156 files
|      File types: tsx(462) scss(234) ts(106) js(37) html(19) css(12) svg(11)
|                  json(9) hbs(4) png(4)
|      Conf files: launch.json(1) settings.json(1) gulp.js(1) package.json(1)
|                  tsconfig.json(1) webpack.config.js(1)
|      Launch Configs: chrome(2);
```

</details>
Extensions: none

**Comment by deepak1556** [comment]
Does launching with `--disable-renderer-accessibility` help ?

**Comment by devexus** [comment]
@deepak1556 
Yep, right now everything is fine.

**Comment by deepak1556** [comment]
thanks for confirming, merging to https://github.com/microsoft/vscode/issues/107016
