### ISSUE TITLE
Search: missing a match in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109944]
Steps to Reproduce:

1. search for `_workbench.diff|_workbench.open|_workbench.openWith`
2. enable all search options (case, word, regex)

=> 🐛 notice how it only shows 2 results in `apiCommands.ts` when there are 3

Probably related that `_workbench.open` is a substring of `_workbench.openWith`

**Comment by bpasero** [comment]
I also think that the preview should highlight the longest match:

![image](https://user-images.githubusercontent.com/900690/98074712-3be30600-1e6b-11eb-8503-3005a03db46a.png)

**Comment by roblourens** [comment]
This is just regexes. The `open` clause in the `|` matches before it gets to the `openWith` clause. If you reorder it, you should get the result you expect. I can't really do anything.
