### ISSUE TITLE
Search editor crashes (OOM) when matching a very long line (e.g. minified JSON)

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#109902]
- VSCode Version: 1.50.1
- OS Version: macOS 10.14.6 (18G6032)

Steps to Reproduce:

1. Extract this file into a VS Code workspace [workbench.web.api.js.map.zip](https://github.com/microsoft/vscode/files/5480398/workbench.web.api.js.map.zip)
2. Open a search editor and search for "// TODO".
3. The VS Code window will crash prompting to reload.

<details><summary>Stack Trace</summary>

```
(anonymous) (searchEditorSerialization.ts:41)
l (searchEditorSerialization.ts:35)
(anonymous) (searchEditorSerialization.ts:65)
(anonymous) (searchEditorSerialization.ts:65)
(anonymous) (searchEditorSerialization.ts:234)
(anonymous) (searchEditorSerialization.ts:234)
t.serializeSearchResultForEditor (searchEditorSerialization.ts:233)
doRunSearch (searchEditor.ts:524)
await in doRunSearch (async)
(anonymous) (searchEditor.ts:427)
(anonymous) (async.ts:260)
Promise.then (async)
trigger (async.ts:254)
triggerSearch (searchEditor.ts:426)
(anonymous) (searchEditor.ts:132)
fire (event.ts:587)
submitSearch (searchWidget.ts:631)
onSearchInputChanged (searchWidget.ts:510)
(anonymous) (searchWidget.ts:326)
fire (event.ts:587)
onValueChange (inputBox.ts:508)
(anonymous) (inputBox.ts:210)
```

</details>

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Not a new issue, but I'm going to close an old bug in favor of this because of your nice repro example.
