### ISSUE TITLE
Editor pin actions should not appear if tabs are disabled

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#109973]
![image](https://user-images.githubusercontent.com/22350/98141483-f5bb9000-1ec6-11eb-8cf2-06d729fd1665.png)

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/100211 for context

**Comment by joaomoreno** [comment]
@bpasero Oh it's because of open editors... which I also don't have!
