### ISSUE TITLE
Terminal environment variable indicator does not show up in Codespaces

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#109963]
Even when `"terminal.integrated.environmentChangesIndicator": "on", no indicator seems to show inside a Codespace, the actual feature of environment variables being added to terminals looks like it works fine though.

**Comment by joaomoreno** [comment]
@Tyriar I also see this in WSL.

**Comment by Tyriar** [comment]
@meganrogge has been looking into this in https://github.com/microsoft/vscode/issues/105177
