### ISSUE TITLE
Test: suggestions in debug repl

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#10997]
test for #8114:
complexity: 3

- [x] any OS - **@alexandrudima**
- [x] any OS - **@stevencl**

As per feature request #8114, debug repl now supports suggestions. Start a node debug session and verify:
* When typing in the debug repl input you get inteli-sense suggestions which make sense
* Upon accepting a suggestion the text in the repl input is properly replaced
* Be creative and use the multi line repl input to try to break the suggestions

**Comment by dbaeumer** [comment]
Closing item since it is tested.
