### ISSUE TITLE
Replace debugWithChrome with launchConfig in serverReadyAction

### ISSUE THREAD

**Issue by llgcode** [microsoft/vscode#109931]
Hi,
It would be more flexible to have this option **launchConfig**  rather than **debugWithChrome** in serverReadyAction and pass the url in argument to the other launch config. See the sample below

```json
       {
       ....
         "serverReadyAction": {
                "pattern": "(https://.+/\\w+)",
                "action": "launchConfig",
                "uriFormat": "%s",
                "name": "Attach to Client"
            }
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Client",
            "port": 9222,
            "disableNetworkCache": true,
            "pathMapping": {
                "/sources/": "${workspaceFolder}/",
                "webapps/": "${workspaceFolder}/webdev/webapps/"
            }
        },
```

thanks

**Comment by connor4312** [comment]
I think this is sensible -- it's common to have additional tweaks per application -- and easy to implement, so I have done so. @weinand let me know if you have any concerns/tweaks in my implementation.

**Comment by llgcode** [comment]
You mean you implemented it, with a new attribute startDebugging: "configName"?
How can we use it?
How do we retrieve the url from second launch config?

**Comment by connor4312** [comment]
Yes, the serverReadyAction looks like

```
"serverReadyAction": {
	"action": "startDebugging",
	"pattern": "listening on port ([0-9]+)",
	"name": "Debug with Chrome"
}
```

In this implementation I have not passed the URL through. We don't really have an easy way to do that in the extension API right now, though we could manually read the launch.json's and find the right action. Though if you're running an existing configuration, my logic was that that URL is probably already (or even required) in it.

**Comment by llgcode** [comment]
You're right the problem with my logic is that we could not launch independently a configuration if it depends on an url parameter...
I guess we could use something like this in the configuration :
${command:extension.getServerReadyCapture}
or something in the input variable: 
https://code.visualstudio.com/docs/editor/variables-reference#_input-variables
${input:serverReadyCapture}
If you think of a solution to get url parameter with a command or an input I will be interested.
I 'll try it in the next update of vscode.
Thanks @connor4312.
