### ISSUE TITLE
The extension totally not working with projects created with "dotnet new angular"

### ISSUE THREAD

**Issue by slishnevsky** [microsoft/vscode#109924]
Angular code debugging should be straight forward according to the documentation for "Debugger for Chrome" VSCode extension.

However I cannot make it work.

I created a simple default app using `dotnet new angular -o Homepage`, which is an Web API + Angular ASP.NET Core project.

I installed the extension and configured launch.json to trigger the debug:

    "configurations": [
    {
       "name": "Launch Chrome",
       "request": "launch",
       "type": "chrome",
       "url": "http://localhost:5001",
       "webRoot": "${workspaceFolder}"
    },
    {
        "name": "Attach to Chrome",
        "port": 9222,
        "request": "attach",
        "type": "chrome",
        "webRoot": "${workspaceFolder}"
    }

When executed with `dotnet run` command, browser opens and runs the application on port 5001.

Then in VSCode I selected Debug, then selected "Launch Chrome" option and clicked the debug button (the green arrow button), a new browser window opened, but breakpoints that I set in the angular app which is ClientApp don't get hit in VSCode.

Also I tried to use the "attach" option for debugging, previously I added "chrome.exe --remote-debugging-port=9222" for Chrome shortcut. Ran the app as before, then selected "Attach to Chrome" option for debugging and clicked the debug button. This also didn't work, no breakpoints get hit.

What am I doing wrong or what's the trick here, why isn't it working? 
It is exactly as the documentation for "Debugger for Chrome" extension instructs to do.

Thanks.

**Comment by connor4312** [comment]
Bot seems to be having issues -- 

Please collect trace logs using the following instructions:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by slishnevsky** [comment]
Hi connor4321.
I addded `"trace": true to your launch.json`
Here is the output in Debug console.
I dont know if there is a debug file.
What I get in Debug console is this:

![image](https://user-images.githubusercontent.com/2932739/98137073-955d2c00-1e8f-11eb-8bc6-5da713528d37.png)

**Comment by connor4312** [comment]
Your launch.json should now have an object like

```
{
   "name": "Launch Chrome",
   "request": "launch",
   "type": "chrome",
   "url": "http://localhost:5001",
   "webRoot": "${workspaceFolder}",
   "trace": true, // <- added this
},
```

With this, there will be a log file path printed at the top of your Debug Console (you may need to scroll up from what I see in your screenshot)

**Comment by slishnevsky** [comment]
Yes, my launch.json is exactly like this.
Ok, the file is like this c:\Users\Username\AppData\Roaming\Code\logs\20201104T114453\exthost1\ms-vscode.js-debug\vscode-debugadapter-0.json.gz
But I cannot upload it here, I get a message "Somthing went really wrong, and we cannot process that file".
I could upload it to " https://microsoft.github.io/vscode-pwa-analyzer/index.html", it whows bunch of info.
I dont know how to read it, I can email it to you.
Is that ok?
It doesnt upload here.

**Comment by connor4312** [comment]
Thanks for the logs. It looks like you want to set `"webRoot": "${workspaceFolder}/ClientApp",`

(next month the debugger is shipping with a tool to self-serve fixes for these kinds of issues :) )

**Comment by slishnevsky** [comment]
Thank you, you are right. That was that issue. Sometimes it is difficult to find out to where this should point.
Thank you, works now.

**Comment by connor4312** [comment]
Good to hear, let us know if you run into any more issues

**Comment by slishnevsky** [comment]
Perfect resolution, thank you, Connor!
