### ISSUE TITLE
editor hover Cannot display Chinese correctly

### ISSUE THREAD

**Issue by welod** [microsoft/vscode#109975]
- VSCode Version: 1.50.1
- OS Version: Mint 20

Steps to Reproduce:

1.  see pic
locale = zh_CN.UTF-8

![image](https://user-images.githubusercontent.com/31583951/98151012-7e0f5480-1f0a-11eb-99a2-195bfeb42e68.png)

Does this issue occur when all extensions are disabled?: No
if disable C++ extension, then no hover.

**Comment by isidorn** [comment]
I see a lot of editor-hover issues assigned to @tyriar thus forwarding this to him

**Comment by Tyriar** [comment]
Passing to @alexdima as it seems to be related to the hover on the editor side, using CJK in the hover service works fine:

![image](https://user-images.githubusercontent.com/2193314/98306609-062c4300-1f79-11eb-887c-1141474b2ed9.png)

**Comment by alexdima** [comment]
This is a hover computed by the C++ language. Please report to the C++ extension.
