### ISSUE TITLE
Intellisense shows only one suggestion

### ISSUE THREAD

**Issue by nitti87** [microsoft/vscode#109906]
Issue Type: <b>Bug</b>

I'm coding in js, css and html and intellisense shows only one suggestion

VS Code version: Code - Insiders 1.51.0-insider (fce8fc82cacf0b4e2a18c633b6c6f3058702a5c9, 2020-11-02T19:45:32.796Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.56GB free)|
|Process Argv|--crash-reporter-id cd7405a1-4997-42c2-abbd-a29c4b00bc6b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|4.4.0
vscode-counter|uct|2.2.0

(1 theme extensions excluded)

</details>

**Comment by mhlozek** [comment]
Same here +1
There are more suggestions when listing with keyboard arrows but only one line is visible in suggestion tooltip.

**Comment by jrieken** [comment]
Did resize the widget by any chance? Can resize it to become larger again?

**Comment by mhlozek** [comment]
Wow, I did not know it can be resized by drag n drop. 
So yes - resizing it solved my problem. Thank you.

**Comment by jrieken** [comment]
Resizing is a new upcoming feature. What wonder and I am nervous about is how you got into that state. Do you recall anything?

**Comment by nitti87** [comment]
I'm not able to resize the widget. 
I'm disabled and therefore use a virtual keyboard and a mouse button utility called [Softype](https://www.orin.com/access/softype/). Because of this software I find it impossible to resize the widget.

**Comment by jrieken** [comment]
Planning to make the following changes for October

1. Add a command to reset a custom widget size, e.g 'F1 > Reset Suggest Widget Size'
1. Don't persist changes when they differ little from the current size. 

The second point addresses my only possible explanation for why this is happening: e.g when resizing the width while a single suggestion shows using the corner-sash the height can change a little as well. You should ignore some degree of little to prevent this

**Comment by isidorn** [comment]
Great for 2. That was my suspicion as well how this was happening.

**Comment by jrieken** [comment]
For 2. it's actually easier: I have logic to that knows what sash have fired. When horizontal sashes fire the height gets persisted, when vertical sash fire the width gets persisted. Now, when dragging from a corner both (horizontal and vertical) sash fire no matter if they have changed. However, I will stick to make "ignore little change" plan as that cover both cases.

**Comment by jrieken** [comment]
To verify:

#### Part 1

* resize the suggest widget
* F1 > Reset Suggest Widget Size (requires an editor)
* trigger suggest notice how the default size is used


#### Part 2

* resize suggest widget to your favourite size
* in TS trigger suggest `console.timeLog|`
* drag the corner and change the width
* trigger suggest somewhere else (with enough suggestions) and make sure your size is used
