### ISSUE TITLE
Bottom of window is clipped when do right snap

### ISSUE THREAD

**Issue by notuntoward** [microsoft/vscode#109921]
On Windows 10, when I snap VSC to the right (Windows+RightArrow), the bottom title bar is truncated, as show in the screenshot.

### Versions

Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

![image](https://user-images.githubusercontent.com/3851891/98012891-78046100-1dae-11eb-85f1-798d08611d80.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please check if it's still reproducible in Insiders build https://code.visualstudio.com/insiders/ ?

What is your screens resolution and system scaling (in display properties)?
Do you have specific settings for task bar (changed location or autohide)?
What value do you have for `window.zoomLevel` if changed?

**Comment by notuntoward** [comment]
The problem goes away on the insiders build.

* this is on a Surface Book 2, so the screen is: 3240 x 2160
* yes, I have autohide on, but otherwise, the taskbar has default settings
* zoomlevel = 100%

**Comment by IllusionMH** [comment]
> The problem goes away on the insiders build.

Could you please clos this issue then? This should be in next stable release then (initially planed for this week)

**Comment by notuntoward** [comment]
Closed b/c fixed in next release.
