### ISSUE TITLE
[Bug] Keybindings.json command is not surrouned by double quotes when auto-complete

### ISSUE THREAD

**Issue by letientai299** [Microsoft/vscode#10990]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04 

Steps to Reproduce:

1. Open `keybindings.json` via Preferences: Open Keyboard Shortcuts.
2. Move the end of the file, and add new key block by type:
```
{
  "key": "ctrl+e",
   "command": <cursor>
}
```

3. Now type `cur`, it would show completion for cursorBottom, cursorBottomSelect, etc... 
4. Press `<tab>`.  Expect to see `"cursorBottom"`. But saw `cursorBottom` without double quotes.

Also notice that if at step 4 we start with `"cur` then no completion will be show up.

**Comment by sandy081** [comment]
@letientai299 Thanks for filing the issue but I am not reproducing this from my side. I am on latest insiders. 

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: 
http://code.visualstudio.com/Download#insiders
