### ISSUE TITLE
VsCode freezes for a few seconds after deleting a file/directory

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [microsoft/vscode#109913]
- VSCode Version: 1.50.1
- OS Version: Fedora 33, Ubuntu 20.04 both with KDE

Abount window:

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.16-300.fc33.x86_64

Steps to Reproduce:

1. Open a c# project
2. Delete a file/folder from the project explorer

Does this issue occur when all extensions are disabled?: Yes

Older instances of the same problem are reported and then closed the version I'm using is much newer than those, but still exhibiting the problem. Please don't close this as a duplicate of an old and already closed one.

This is not a memory/cpu/hdd issue. The machine is 10th gen core i7, 16gig, nvme. Most of the ram is empty at the time of last check.

**Comment by JuanEL0** [comment]
I have the same issue but in macos.

- VSCode Version: Versión: 1.50.1
- OS Version: macOS 10.15.7 (Catalina)

Complete version info:

Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (3 weeks ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

To me, this issue happens in every project that I open, when I try to remove a file/folder, VSCode freezes for a while.

**Comment by eamodio** [comment]
I've seen it happen occasionally on Windows as well

**Comment by nuochong** [comment]
me to

**Comment by nooblyf** [comment]
it's so frustrating, happened to me 5 times today itself, i'm using ubuntu

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/101920
fyi @deepak1556

**Comment by AlirezaHaghshenas** [comment]
I see that setting an Env variable will probably fix this. Thanks for pointing out.

Is there a plan to make vscode independent of this variable (like packaging the value inside vscode, or any other solution?)

Or at least, update the installation docs for linux to instruct people to do this?
