### ISSUE TITLE
Last relaese opens with empty window in Xwindow envirenment

### ISSUE THREAD

**Issue by EmTee70** [microsoft/vscode#109903]
- VSCode Version: code_1.50.1-1602600906_amd64.deb
- OS Version: Ubuntu 18.04.5 LTS

Steps to Reproduce: 

1. Installing with dpkg -i  code_1.50.1-1602600906_amd64.deb 
2. opening via ssh -XC other_user@localhost 
3. code   opens an empty window 
4. --disable-gpu does not help!
5. when reverting to code_1.47.2-1594837870_amd64.deb everything works as before
6. when retrying code_1.50.1-1602600906_amd64.deb same behavior.

Does this issue occur when all extensions are disabled?: Yes/No
Yes!

In my main account **without XWindows redirect** everything works as expected.

**Comment by eamodio** [comment]
Can you try launching code with --no-xshm flag?

**Comment by EmTee70** [comment]
code --no-xshm
**Is working! What is the meaning of this flag?**
Getting:
Warning: 'xshm' is not in the list of known options, but still passed to Electron/Chromium.

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/101069

You can refer https://github.com/microsoft/vscode/issues/101069#issuecomment-662150152 for what the flag is and why it is now needed. Thanks!
