### ISSUE TITLE
typescript language server repeatedly crashes after updating yarn2 PnP monorepo dependencies

### ISSUE THREAD

**Issue by xenoterracide** [microsoft/vscode#109907]
Issue Type: <b>Bug</b>

typescript language server repeatedly crashes after updating yarn2 PnP monorepo dependencies.

It doesn't always happen, but pretty certain all you need to do is do a `yarn workspace myworkspace add somedep` or remove one... this probably only occurs in a yarn2 PnP environment.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 9, 7|
|Memory (System)|16.00GB (0.75GB free)|
|Process Argv|--crash-reporter-id 90bc7667-773a-49db-8edc-133c9bb723b3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-imports|ama|6.2.2
vscode-zipfs|arc|2.2.2
language-hugo-vscode|bud|1.2.0
better-toml|bun|0.3.2
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.13
javascript-ejs-support|Dig|1.3.1
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.1
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|1.7.0
vscode-kubernetes-tools|ms-|1.2.1
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
gradle-language|nac|0.2.3
env-cmd-file-syntax|Nix|0.2.2
vscode-jest|Ort|3.2.0
vscode-versionlens|pfl|1.0.8
vscode-xml|red|0.13.0
vscode-yaml|red|0.12.0
vscodeintellicode|Vis|1.2.10
faster-new|wen|1.0.9

</details>

**Comment by mjbvz** [comment]
Please provide steps to reproduce the issue

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
