### ISSUE TITLE
window reload after file explorer click on large files

### ISSUE THREAD

**Issue by gabriel-modex** [microsoft/vscode#109952]
especially when working remote with remoteSSH plugin, whenever I click a large file in file explorer. it tries to open it in editor. should be a question if I really want to open that file

**Comment by eamodio** [comment]
Not sure what the issue is here -- is the window reloading or something else?

**Comment by gabriel-modex** [comment]
yes, sometimes the dialog to reopen the window comes up.
I see that there is a warning beforer openening binary/large files

I'll get back when I reproduce. Maybe is only over slow connections/
Thank you

![image](https://user-images.githubusercontent.com/67112759/98218139-141b9d00-1f54-11eb-93de-37e363fb9bde.png)

It remains in this state state 
![image](https://user-images.githubusercontent.com/67112759/98215933-14666900-1f51-11eb-9091-d65c82553fef.png)

**Comment by isidorn** [comment]
This is not coming from the explorer, forwarding to @roblourens for SSH

**Comment by gabriel-modex** [comment]
yes, remote ssh only. sry, on local it detects file type, as above screenshot
on remote I get this for the same file. every time.

could I provide anything else in order to reproduce? the file size is in this case is  ~300MB

![image](https://user-images.githubusercontent.com/67112759/98224215-e4709300-1f5b-11eb-943f-30f5cf7480f0.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1087
