### ISSUE TITLE
Compiler #includes errors using CustomConfigurationProvider for custom compilers

### ISSUE THREAD

**Issue by denis-shienkov** [microsoft/vscode#109958]
- VSCode Version: 1.51
- OS Version: Windows 10

We are create an own extension to support the [QBS build system](https://github.com/denis-shienkov/vscode-qbs). 
(it is something like your [cmake-tools extension](https://github.com/microsoft/vscode-cmake-tools)).

We are use the custom `cpt.CustomConfigurationProvider` class to provide the intelli sense features. 
When we are use the generic compilers (such as GCC, MinGW, MSVC, Clang), then the our extension
finds the includes from the compiler, e.g. such as `#include <iostream>`. 

But, when we are use the other compilers (e.g. IAR EW, KEIL, SDCC), then the extension report an erros,
that the includes did not found:

`[04.11.2020, 16:33:03] Unable to resolve configuration with compilerPath: "C:/Program Files (x86)/IAR Systems/Embedded Workbench 8.4/arm/bin/iccarm.exe"`

And we open any project's source file, e.g. `main.cpp`, then we got the following errors:

` #include errors detected based on information provided by the configurationProvider setting. Squiggles are disabled for this translation unit (E:\git\ng\git\123\qbs-git\tests\helloworld-minimal\main.cpp).`
`cannot open source file "iostream"`

![main.cpp](https://user-images.githubusercontent.com/8415796/98119455-af156800-1ebd-11eb-900a-c973104f548f.png)

But, it is strange, because in our `cpt.CustomConfigurationProvider` implementation we return the required 
`cpt.SourceFileConfiguration` (including the paths to the compiler includes):

* https://github.com/denis-shienkov/vscode-qbs/blob/master/src/qbscpp.ts#L58

The extension required the configuration for the `main.cpp` file:

![main.cpp uri](https://user-images.githubusercontent.com/8415796/98119997-7033e200-1ebe-11eb-9ca1-99dc5ed28ca4.png)

And the configuration content is the following:

![configuration content](https://user-images.githubusercontent.com/8415796/98120201-b6894100-1ebe-11eb-9077-f20cdb3a539d.png)

As you can see, we provide a paths to the compiler includes, and the `iostream` file exists in the
filesystem on the path `c:\Program Files (x86)\IAR Systems\Embedded Workbench 8.4\arm\inc\cpp\iostream`.

Besides, the passed `FOO` define successfully highlighted in the `main.cpp` sources.

**Comment by dbaeumer** [comment]
@denis-shienkov this looks like a problem of the CPP extension.
