### ISSUE TITLE
Reset "Don't show again"

### ISSUE THREAD

**Issue by Peepijeep** [microsoft/vscode#109912]
Hello,

I Visual Studio Code, I accidentally clicked on "Dont show again", when there was a prompt. Can I reset/undo that setting somewhere without deleting Visual Studio Code and all other user files?

A simple command or a simple button to do that is all we want :(

**Comment by Peepijeep** [comment]
Thanks VS-Code-Bot, but nope, this is a total different case. Thats why we are human and you a only a bot :D

**Comment by gjsjohnmurray** [comment]
See #24815 which was recently closed by @bpasero as out-of-scope.

**Comment by bpasero** [comment]
Not possible unless you delete the workspace or global state. To get it you can run "F1 > Log Storage Contents" and check devtools.
