### ISSUE TITLE
Easily navigate to your most recently changed settings

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#109974]
**Easily navigate to your most recently changed setting(s)**
- search for a setting
- interact with the setting (require that the value has changed?)
- close the settings page
- re-open the settings page
- see the setting you interacted with
   Case 1. on the most commonly used page
   Case 2. where you scrolled in your last search results

Existing behavior:

Navigating with the scroll/sidebar
- scroll and use the sidebar outline to navigate to a setting
- close the settings page
- re-open the settings page
- see the setting you most recently navigated to

Navigating with search
- search for a settings page
- close the settings page
- re-open the settings page
- see the Commonly Used page

**Ideas to accomplish this:**

Case 1: re-purpose Commonly Used settings page to include most recently changed settings
   - questions:
      - do we include settings changed via a command? 
      - do we include settings changed by an extension?
      - sort the page by most frequently changed or by most recently changed?

Case 2: save search input (configurable setting)

Questions to research:
Do users frequently change particular setting(s)?
Are users likely to toggle a setting multiple times?
Do new users find the Commonly Used settings page helpful?

**Comment by ThaJay** [comment]
Post a link to the backlog then!
