### ISSUE TITLE
Quick input reset scroll position

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#109969]
* use latest from master
* f1 > insert snippet
* scroll down to an extension snippet and hide it (press 👁️ icon)
* :bug: the scroll position resets

This is happening when reassigning the items (since the press changed the label) here: https://github.com/microsoft/vscode/blob/92314d61a55f466c125fa9d1f9fe8da633a82423/src/vs/workbench/contrib/snippets/browser/insertSnippet.ts#L213

**Comment by chrmarti** [comment]
Fixing this might be non-trivial because you set new objects and there is no way for the picker to tell if you intend this to be a new set of choices that require the scroll position to be reset or if this is a refinement of the existing choices that require the scroll position to stay the same.

**Comment by jrieken** [comment]
I could give you the same object again, e.g I would modify them them in-place and set the same array again

**Comment by chrmarti** [comment]
Two simpler options:
- Add read-writable `scrollTop` to the QuickPick object. You read it, update the items and set the old value again.
- Or: Add `splice()` to the QuickPick object and document that as preserving the scroll position by default.

If we were to add this to the API one day, I would prefer the second option.

**Comment by TylerLeonhardt** [comment]
I don't think the `splice()` would help in this case because @jrieken doesn't want to remove the item, he wants to _change_ the item.

> Add read-writable scrollTop to the QuickPick object. You read it, update the items and set the old value again.

This would work, though I'm not sure how to control scroll... any pointers on that?

With that being said, I almost feel like @jrieken wants a way to say "Hey I modified the objects in some way, please refresh them".

This can be done by turning [this code](https://github.com/microsoft/vscode/blob/156fed280ac000e9d61014b16da93ea8baefdb36/src/vs/workbench/contrib/snippets/browser/insertSnippet.ts#L210-L214) into:
```ts
                picker.onDidTriggerItemButton(ctx => {
			const isEnabled = snippetService.isEnabled(ctx.item.snippet);
			snippetService.updateEnablement(ctx.item.snippet, !isEnabled);

			if (!isEnabled) {
				ctx.item.description = undefined;
				ctx.item.buttons = [{
					iconClass: Codicon.eyeClosed.classNames,
					tooltip: nls.localize('disableSnippet', 'Hide from IntelliSense')
				}];
			} else {
				ctx.item.description = nls.localize('isDisabled', "(hidden from IntelliSense)");
				ctx.item.buttons = [{
					iconClass: Codicon.eye.classNames,
					tooltip: nls.localize('enable.snippet', 'Show in IntelliSense')
				}];
			}

			picker.itemActivation = 0;
			picker.itemsUpdated = true;
			picker.update();
		});
```

The if/else just sets the buttons and description based on the new state. The real magic is the last 3 lines that basically force update how the items are rendered. This gives the desired effect of clicking on an 👁️ and having it change right in front of you.

```ts
picker.itemActivation = 0;
picker.itemsUpdated = true;
picker.update();
```

None of these are public atm, but I could see a possible `refreshItems()` function that does exactly those 3 lines.

Thoughts?

**Comment by chrmarti** [comment]
The assumption so far was that items would not change and that we need to read their properties only once when they are set on the picker object. That has kept the API simple. The `scrollTop` and `splice()` (replace the changed items) suggestions are preserving this assumption.

If we wanted to support mutable items, we would need an extension-supplied event. That would in my view mix two distinct approaches in the same API.

`splice()` might be a bit easier to use, but now that I think about this some more I think `scrollTop` will cover more cases and might be the preferable solution. (E.g., imagine changing the sort order and wanting control the scroll position or similar changes affecting all items.)

**Comment by TylerLeonhardt** [comment]
@chrmarti and I talked about this... one of my fundamental misunderstandings was that a `.splice()` would only remove things from a list when really the idea is that we'd pass a `Map` into `.splice()` that would map "nodes to be replaced" to "nodes to replace them with".

The assumption being that this API would not scroll to top as you are just replacing nodes in the list. If you want the 'scroll to top' behavior, you can set `.items`.

What do you think? Something like this:

```ts
export interface QuickPick<T extends QuickPickItem> extends QuickInput {
    // ...

    splice(replacementMap: Map<T, T>): void;

   // ...
```

**Comment by TylerLeonhardt** [comment]
after talking to @jrieken, he suggested we use an `id` property instead that we can use to do the comparison on whether or not the list has changed. The logic would be... if the list maintains the same order as before (using the `id`s to determine this) we will maintain the cursor position.

What do you think @chrmarti ?

**Comment by chrmarti** [comment]
@TylerLeonhardt Sounds good. I suggest to briefly look into the implementation before committing to it. We currently maintain object identity in the API, e.g., when the extension sets some items, it will get the same objects back as the active and selected item(s). When introducing ids, you would probably expect the new object to replace the old object with the same id in all of the API. Probably not a big task, but something to consider.

**Comment by TylerLeonhardt** [comment]
> When introducing ids, you would probably expect the new object to replace the old object with the same id in all of the API. Probably not a big task, but something to consider.

This a good point... I guess the question is... how far should we go with this?

If you have 2 items with the same id should it:
* throw an error (explicit but potentially hugely breaking)
* overwrite the first one, with the last one (makes it so the quick pick still work but potentially breaking if the user has 2 items with the same id today)
* Only use the id (or a new property) for focus purposes and allow 2 items with the same id

I think the "focus algorithm" could simply be... "verify the order of the ids hasn't changed at all" which means something along these lines:
```ts
	private shouldKeepFocus(items: Array<T | IQuickPickSeparator>): boolean {
		// short circuit if their lengths are different
		if (items.length !== this._items.length) {
			return false;
		} else {
			return this._items.every((item, i) => {
				const otherItem = items[i];

				// verify separators are the same
				if (otherItem.type === 'separator'
					&& item.type === 'separator'
					&& otherItem.label === item.label
				) {
					return true;
				}

				// verify items have the same id (and that that id is not undefined)
				if (otherItem.type !== 'separator'
					&& item.type !== 'separator'
					&& otherItem.id === item.id
					&& otherItem.id
				) {
					return true;
				}

				return false;
			});
		}
	}

**Comment by chrmarti** [comment]
Even without duplicate ids in the same items array, ids raise some questions, e.g.:
- Set some `items` with unique ids and focus one of them.
- Reading `activeItems` will give you the same object you set on `items`.
- Update `items` with new objects, but the same ids (same order to keep things simple).
- Does reading `activeItems` now give you the new object or the old object? (I'd expect the new object. If you agree, this just needs to be considered when implementing.)

If `items` is set to an array with duplicate ids, maybe a warning could be logged and all ids could be ignored to keep things simple and non-breaking?

**Comment by TylerLeonhardt** [comment]
> * Set some items with unique ids and focus one of them.
> * Reading activeItems will give you the same object you set on items.

do you think you can point me to where `activeItems` gets set after I set `items`? I was trying to narrow it down but none of the references to `activeItems` really stood out.

> Does reading activeItems now give you the new object or the old object? (I'd expect the new object. If you agree, this just needs to be considered when implementing.)

Yes I would also expect the new object. Good point.

> If items is set to an array with duplicate ids, maybe a warning could be logged and all ids could be ignored to keep things simple and non-breaking?

Yes I like this.

**Comment by chrmarti** [comment]
This one picks up changes from the UI: https://github.com/microsoft/vscode/blob/main/src/vs/base/parts/quickinput/browser/quickInput.ts#L807

We trigger this initially by setting the focus items on the list: https://github.com/microsoft/vscode/blob/main/src/vs/base/parts/quickinput/browser/quickInput.ts#L956

**Comment by TylerLeonhardt** [comment]
Ah... so what I was doing is setting:

`ItemActivation` to `NONE`
https://github.com/microsoft/vscode/blob/e003fd9a5d8a17965d307f3fc1955671d3336bdc/src/vs/base/parts/quickinput/browser/quickInput.ts#L1019-L1019

but what this does is makes it so that when you reset `.items` `.activeItems` becomes and empty array.

This is the easiest solution for this issue... however... it may not be ideal.

If we want to _keep_ activeItems to the last selection that gets trickier because when the items in the list widget get set, it appears to clear the focused state... we get around this by using `ItemActivation.FIRST` which triggers the first item in the quick pick to be focused...however that is a problem because even if we are able to focus on the "previously focused index", that's still going to cause the cursor to jump to that item which is what we see in this issue.

To truly fix this, that would mean we need some way to say "yes, focus on the last item that was focused (already happens today I think) but reset the scroll position back to what it was before.

**Comment by karrtikr** [comment]
We have a related use case in the Python extension where the scroll focus is lost when adding items dynamically to end of quickpick list #131457

**Comment by TylerLeonhardt** [comment]
related https://github.com/microsoft/vscode/issues/76193

**Comment by chrmarti** [comment]
One way to avoid introducing ids would be to have separate functions for inserting, replacing and removing items:
- `.insertItems(index, additionalItems)`
- `.replaceItems(index, replacementItems)`
- `.removeItems(index, count)`

**Comment by TylerLeonhardt** [comment]
@jrieken proposed something different... a
```
stableItems: boolean
```
Property on quickpick. This is similar to `ignoreFocusOut: boolean` and it would specifically handle the behavior of what to do with the scroll position.

**Comment by TylerLeonhardt** [comment]
I have a PR out that adds a `resetScrollPosition: boolean`: https://github.com/microsoft/vscode/pull/132013

**Comment by TylerLeonhardt** [comment]
verification: original issue has good steps.
