### ISSUE TITLE
OSS - Unable to open 'Settings': Cannot read property 'minimapWidth' of undefined.

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#109920]
Issue Type: <b>Bug</b>

This is happening with OSS built from today's master, as soon as I try to open Settings (Ctrl+,)

VS Code version: Code - OSS Dev 1.52.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.18363

**Comment by eamodio** [comment]
I can't reproduce this on master -- maybe it was fixed? or did you have a bad setting?

**Comment by gjsjohnmurray** [comment]
Turns out this is a dup of #100873, and since that was logged by me too I ought to have recognized the symptom and know how to fix it (delete the `out` folder and then re-run `yarn`). I still wish the build scripts could deal with this though.
