### ISSUE TITLE
Only partial syntax highlighting in switch case structure in C

### ISSUE THREAD

**Issue by DagBjorndal** [microsoft/vscode#109929]
Issue Type: <b>Bug</b>
Several of the "case" statements and the "default" statement are white, and not colored. Other switch case statements in the program code seems fine with correct color. Hence, I don't know how to reproduce this phenomenon. 

Screen shot: 
![2020-11-03-181937_1294x917_scrot](https://user-images.githubusercontent.com/47723512/98020111-da874c80-1e02-11eb-805d-fbefcde217fc.png)

VS Code version: Code - Insiders 1.51.0-insider (fce8fc82cacf0b4e2a18c633b6c6f3058702a5c9, 2020-11-02T21:50:11.273Z)
OS version: Linux arm64 5.4.73-v8+

|Memory (System)|7.63GB (4.34GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 9c19745a-358a-4c4e-b069-006f89f11979|
Extension|Author (truncated)|Version
cpptools|ms-|1.1.0-insiders3
bash-debug|rog|0.3.9

**Comment by alexr00** [comment]
Can you share the code that this happens with in a copy/pastable form?

**Comment by DagBjorndal** [comment]
Sorry; I am now on VSCode v1.52, and not checking out the same commit of my code produces the error. Was it fixed possibly?

![2020-11-06-163433_1398x965_scrot](https://user-images.githubusercontent.com/47723512/98384901-a738fd80-204e-11eb-9f3c-912e99f045ea.png)
