### ISSUE TITLE
Long string input cut off in debug repl

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#10992]
Refs: #10982

Steps to Reproduce:

1.  Open debug console
2. Paste the following string into the repl input 
`a77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0ba77e9c0b77e9c0b77e9c0b77e9c0b77e9c0bEND`
3. Notice how the END is cut off, it should be visible
4. This worked yesterday (before pr #10982)

I also noticed that `s` should be `line` [here]( https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/replViewer.ts#L128)

**Comment by roblourens** [comment]
Oops, thanks for catching that. I'll see if I can add a unit test for this tomorrow.

**Comment by isidorn** [comment]
Unit tests would be lovely! Any suggestions on how to improve the coverage of the debug land is really appreciated.
