### ISSUE TITLE
Multiple-cursors are not visible on first column

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#10993]
- VSCode Version: 1.5.0-insider  2f2d65
- OS Version: Windows 10

Steps to Reproduce:

1. select multiple lines using multiple cursors, or break a multi-line selection into multiple cursors.
2. press HOME to move all cursors to first column
3. Only the first cursor shows up, that too partly covered by the gutter.

Additional details:

Theme: Dark+
```json
{
  "editor.cursorBlinking": "phase",
  "editor.fontFamily": "Consolas, 'Courier New', monospace",
  "editor.fontSize": 14,
  "window.zoomLevel": -1
}

**Comment by alexandrudima** [comment]
@kumarharsh This is caused by `window.zoomLevel`. My personal recommendation is to not use that. Please see #9634. You can also upvote #10605
