### ISSUE TITLE
Snippet can not auto trigger in markdown file

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode#109946]
Snippet can not auto trigger in markdown file

**Comment by bonaluo** [comment]
when i code a java file ,snippet for java will show in suggestions automatically, it will not when i write a markdown file, i have to use shortcuts to trigger it.

**Comment by gjsjohnmurray** [comment]
I think this is as designed. The built-in Markdown Language Features extension doesn't register a CompletionItemProvider, so there are no trigger characters when editing a file that is using the 'markdown' language mode. Markdown snippets come from the built-in Markdown Language Basics extension. To access them you need to use the generic trigger, which on Windows is <kbd>Ctrl</kbd>+<kbd>Space</kbd>

**Comment by gjsjohnmurray** [comment]
You could also [enable tab completion](https://code.visualstudio.com/docs/editor/userdefinedsnippets) with `"editor.tabCompletion": "on"`

**Comment by ArturoDent** [comment]
Read this in another issue.  For markdown to get snippets showing in suggestions you have to do this in your settings.json:

```
  "[markdown]": {
    "editor.quickSuggestions": {
      "other": true,                          // <= this is the important one
      // "comments": false,
      // "strings": true
    }
 }
```

**Comment by bonaluo** [comment]
@ArturoDent Thanks for your help.
