### ISSUE TITLE
Multiple markdown display

### ISSUE THREAD

**Issue by Sigmarus** [microsoft/vscode#109935]
Currently, we can display only one markdown preview in a unique tab, but what if we want to see markdown previews from multiple files at the same time ?
It would be nice if we could display the markdown text and preview versions on one tab and let the user choose either he wants to display the text version, or the preview version, or both, so we can have each file displayed as wanted.

**Comment by yume-chan** [comment]
Actually you can (except displaying both), <kbd>F1</kbd>, `View: Reopen Editor With...`, `Markdown Preview (Experimental)`

Oh I think I found a bug here...

**Comment by mjbvz** [comment]
Closing since this sounds like a fit for the markdown preview custom editor 

Also see the documentation about the markdown preview and locking it to a single file: https://code.visualstudio.com/Docs/languages/markdown#_dynamic-previews-and-preview-locking
