### ISSUE TITLE
Add ${} or template literal escaping for User Snippets.

### ISSUE THREAD

**Issue by BreadcrumbIsTaken** [microsoft/vscode#109915]
Hi, I am making a snippet so I can easily and quickly program a file for JavaScript. My JavaScript code includes template literals. But, you use `$` and `${}` for tabbing to easily and quickly editing code. I would like to have the template literals for my code. When I use the snippet, it takes away the `$` and the `{}`. If there is a way to escape it or cheat it to make it not take away the template literals. Thanks!

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you post example where you have problems with ${}? Have you tried to use `\` or `\\` before characters in `${}`

**Comment by IllusionMH** [comment]
This snippet body should work with snippet placeholders `${1:start}` inside of template literal placeholders `\\${...}` (note `\\` to escape `$`)
```
"`\\${${1:start}} - \\${${2:end}}`"
```
