### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by p4lad1n030** [microsoft/vscode#109925]
- Issue Type: `Bug`
- Extension Name: `debugger-for-chrome`
- Extension Version: `4.12.11`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.50.0`

Entao o meu vs code ta dando erro ao executar um projeto html no chrome e eu nao sei como resolver estou aprendendo programaçao qualquer ajuda sera bem vinda obrigado!
ERRO:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8740,
		"activateCallTime": 0,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "msjsdiag.debugger-for-chrome",
				"_lower": "msjsdiag.debugger-for-chrome"
			},
			"activationEvent": "onDebugResolve:chrome"
		}
	},
	"runtimeErrors": []
}
```

**Comment by connor4312** [comment]
Can you share the exact error message you're seeing?

/needsMoreInfo
