### ISSUE TITLE
editor.detectIndentation:false not working properly

### ISSUE THREAD

**Issue by pprokopi** [microsoft/vscode#109979]
VSCode Version:code --version 1.48.2
    OS Version: Fedora 32 x64

Steps to Reproduce:

    Run code --disable-extensions
    Create a file with a separate editor that has tab indentation (personally used a .go file)
    Set the following in user settings
    "editor.detectIndentation": false,
    "editor.insertSpaces": true,
    "editor.tabSize": 4,
    Make sure the workspace has no settings
    Check in the lower right corner if indentation is tabs or spaces

What I expected:
VS code ignores the already used indentation in the file and uses spaces for future indentation.

What happened:
VS code detected the indentation of the file and kept using tabs instead of spaces for indentation.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by rebornix** [comment]
@pprokopi can you check if you have workspace setting which sets the indentation settings? Also a screen recording / gif can help troubleshoot.

**Comment by pprokopi** [comment]
![out](https://user-images.githubusercontent.com/55585744/98188659-1c57e600-1f1c-11eb-879a-dad76880f631.gif)

**Comment by pprokopi** [comment]
I have tested .c .go .py and files without an extension and noticed that it only happens in .go files.
As you can see, settings.json is empty except for the 3 settings mentioned above, there are no workspace settings and extensions are disabled

**Comment by adegeo** [comment]
This also doesn't seem to be working for me. VSCode is showing Spaces: 2 at the bottom but it indents with 4 spaces.

![image](https://user-images.githubusercontent.com/67293991/98304257-80a69400-1f74-11eb-95f4-13af13e4f194.png)

![image](https://user-images.githubusercontent.com/67293991/98304315-9fa52600-1f74-11eb-9205-b7407ea2e0c9.png)

**Comment by pprokopi** [comment]
> UPDATE
> Sigh.. yet again it's the https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack extension screwing things up.

In my case extensions are disabled, and Docs Authoring Pack is not installed
