### ISSUE TITLE
invoke peek commands using command palette (not keybindings)

### ISSUE THREAD

**Issue by blueray453** [microsoft/vscode#109953]
I need to invoke the following using command palette (not keybindings).

```
peek definition
peek implementation
peek declaration
peek reference
peek type definition
```
To give some context, I can not remember all these keybindings. So, It will be great to have one keybinding to invoke them all. So, I am trying to [use](https://github.com/microsoft/vscode/issues/92769#issuecomment-641512657):
```
 {
     "key": "ctrl+b",
     "command": "workbench.action.quickOpen",
     "args": "Peek"
 }
```
But it seems like `Peek` does not yield relevant commands in the command pallet.

**Comment by eamodio** [comment]
If you use the following it will work. (need to enter command mode by using `>`)
```
 {
     "key": "ctrl+b",
     "command": "workbench.action.quickOpen",
     "args": "> Peek"
 }
```
