### ISSUE TITLE
Adopt StorageTarget

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#109967]
If you own a call to `IStorageService#store`, please adopt `IStorageService#store2` where a new argument is required:
* `StorageTarget.USER`: sync it across machines
* `StorageTarget.MACHINE`: do NOT sync it

As a rule of thumb, `StorageTarget.USER` should be used in almost all cases unless the state is very specific to the machine (e.g. file paths are used, or window dimensions and sizes).

**Note:** even though we do not sync workspace UI state yet, it would still be good to adopt this new method so that we are ready in the future.

Here is a list of areas:
**StorageService**
* `workbenchThemeService` @aeschli 
* `productIconThemeData` @aeschli 
* `fileIconThemeData` @aeschli 
* `remoteExplorerService` @alexr00 
* `authenticationService` @RMacfarlane 
* `mainThreadAuthentication` @RMacfarlane 
* `runAutomaticTasks` @alexr00 
* `abstractTaskService` @alexr00 
* `scmService` @meganrogge (history related)
* `experimentService` @sbatten 

**Memento (look for `legacygetMemento`)**
* `experimentService` @sbatten 
* `webviewPane` @mjbvz 
* `searchEditorInput` @JacksonKearl 
* `notebookServiceImpl` @rebornix 
* `notebookEditorWidget` @rebornix 
* `contributedCustomEditors` @mjbvz 

Fyi I will go over a few not mentioned here that are straight forward to adopt.

**Comment by alexr00** [comment]
@bpasero how does this interact with `StorageScope.WORKSPACE`?

**Comment by bpasero** [comment]
@alexr00 I tried to explain this above:

> Note: even though we do not sync workspace UI state yet, it would still be good to adopt this new method so that we are ready in the future.

Today we don't sync workspace UI state, but we may in the future. Only put `StorageTarget.USER` for `StorageScope.WORKSPACE` if the data does not contain machine specific things (like file paths).

**Comment by alexr00** [comment]
I should have read more carefully, thank you.

**Comment by bpasero** [comment]
Thanks for a lot of changes already. I forgot to list the references to memento object that also needs adoption. The new list is:

**StorageService**
* `workbenchThemeService` @aeschli 
* `productIconThemeData` @aeschli 
* `fileIconThemeData` @aeschli 
* `remoteExplorerService` @alexr00 
* `authenticationService` @RMacfarlane 
* `mainThreadAuthentication` @RMacfarlane 
* `runAutomaticTasks` @alexr00 
* `abstractTaskService` @alexr00 
* `scmService` @meganrogge (history related)
* `experimentService` @sbatten 

**Memento (look for `legacygetMemento`) **
* `experimentService` @sbatten 
* `webviewPane` @mjbvz 
* `searchEditorInput` @JacksonKearl 
* `notebookServiceImpl` @rebornix 
* `notebookEditorWidget` @rebornix 
* `contributedCustomEditors` @mjbvz

**Comment by bpasero** [comment]
Thanks, only a few left. Ping @rebornix & @RMacfarlane

**Comment by bpasero** [comment]
Down to only these:

![image](https://user-images.githubusercontent.com/900690/99042051-582e2380-258c-11eb-98e9-af0734f3707c.png)

**Comment by rebornix** [comment]
@bpasero I added ScopeTarget in notebook world, the legacygetMemto can be removed now.
