### ISSUE TITLE
Disconnect icon in debug toolbar 

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#10998]
I think the icon is really bad, I liked the strong red icon for stopping to debug and now you have to really search for the action when doing extension development:

![image](https://cloud.githubusercontent.com/assets/900690/17997890/a89dedde-6b71-11e6-8e77-a137b0fd2226.png)

**Comment by isidorn** [comment]
ping @joaomoreno 
related issue: https://github.com/Microsoft/vscode/issues/9740

**Comment by weinand** [comment]
Consider to show the plug on top of a red square. With this the icon is always strong and red but in case of disconnect, it conveys the slightly different semantics.

**Comment by isidorn** [comment]
Sounds good to me that the red should be the dominant color. @bgashler1 can you please update the icon?

**Comment by bgashler1** [comment]
@isidorn we're working on a revision for this right now with red being the dominant color.  It will be a red plug that's struck through.  I will post it as soon as it's ready.

We also will have an icon for "Connect" back to the debugger, in case that's desired.  We tried the red square with a plug in it, and it didn't look quite right.

FYI: @chryw

**Comment by bgashler1** [comment]
Here are the new icons
One for disconnect and one for connect (in case that is needed, similar to how we have stop and run)

[Disconnect_icons.zip](https://github.com/Microsoft/vscode/files/446110/Disconnect_icons.zip)

**Comment by isidorn** [comment]
I like that the new icon is red which makes it a bit clearer. However the visuals are still completly different than the previous red squire so this might be surprising to some users. In the end this icon works for me. @weinand @bpasero please add opinions

![screen shot 2016-08-31 at 11 44 07](https://cloud.githubusercontent.com/assets/1926584/18123900/464c2c7e-6f70-11e6-9b30-7396e3fd76aa.png)

![screen shot 2016-08-31 at 11 44 17](https://cloud.githubusercontent.com/assets/1926584/18123908/4afc0b0e-6f70-11e6-8c6e-3f496898f4e8.png)

**Comment by weinand** [comment]
The new icon doesn't look quite right. It is not bold enough.
We will not use this for VS Code v1.5.

**Comment by isidorn** [comment]
Since @bgashler1 is not replying and @weinand is not approving of the icon for august we will go back to the red square for the disconnect. 
Thus assigning this to @bgashler1 and September to address @weinand concerns regarding the the icon

**Comment by chryw** [comment]
@isidorn 
@bgashler1 is on vacation. He stopped by my desk and suggested this approach before he left. What do you think?
![image](https://cloud.githubusercontent.com/assets/7075677/18178135/ff909b4a-7031-11e6-80dd-d474824323fe.png)

![image](https://cloud.githubusercontent.com/assets/7075677/18178122/f1521c0c-7031-11e6-94ce-761d5c216b0e.png)

**Comment by weinand** [comment]
@chryw great, I like that!

**Comment by isidorn** [comment]
@chryw Works for me also, can you please attach those icons so I can incorporate them into vscode. I would just make sure that the square is exactly the same size as our current stop icon
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/media/stop.svg#L1

**Comment by chryw** [comment]
@isidorn I don't think it's possible to make the plug still visible in such a small square like the current stop icon. I attached exactly the same size as you see in the mockup.
![image](https://cloud.githubusercontent.com/assets/7075677/18212692/61a7da2e-70f9-11e6-914b-7afda0be88cf.png)

[DetachConnection_VSCodeVersion.zip](https://github.com/Microsoft/vscode/files/452612/DetachConnection_VSCodeVersion.zip)

**Comment by isidorn** [comment]
@chryw thanks for the icons. I tried putting them in vsocde and icons have a border which is out of style with our stop icon. This is especailly visible in the dark theme. Is there some special reason for this border? 
I removed the border and pushed the updated icons to master. Try it out and let me know what you think

**Comment by bgashler1** [comment]
@chryw thanks for your help while I was away.

@isidorn you made the right call in removing the border.  In Visual Studio, it's standard to have this border (but it's programmatically adjusted to be the same as the background color of the thing it's sitting on).  We have no need to do that in VS Code, and I remove them whenever I see them.
