### ISSUE TITLE
Unable to split bundles in Notebook Renderers

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#109932]
- Version: 1.51.0-insider
- OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Try the sample renderer https://github.com/microsoft/vscode-notebook-renderer-starter
2. It does not work

We get an error `Error loading preloads: Cannot read property 'src' of null`
Looks like we are no longer emitting a script tag for the preloads.

@rebornix @connor4312 /cc

Does this issue occur when all extensions are disabled?: N/A

**Comment by connor4312** [comment]
There's now a `scriptUrl` global you can use instead of `document.currentScript.src`

**Comment by connor4312** [comment]
See https://github.com/microsoft/vscode-generator-code/commit/ea8867d5481f38ef6123f293226ecc871f5939cc for an example

**Comment by connor4312** [comment]
Fyi @vijayupadya @kjcho-msft this is new contract
