### ISSUE TITLE
Code Helper (Renderer) CPU drain - just one repo/folder, extensions disabled, git disabled

### ISSUE THREAD

**Issue by krinhorn** [microsoft/vscode#109981]
Issue Type: <b>Performance Issue</b>

This only happens with a particular repo/folder on my computer. It still happens with all installed extensions disabled and with git disabled from the user settings.

All I have to do is open the workspace and the CPU starts going up immediately until my fans are going. It only stops when I close the workspace.

Opening other git-controlled folders seems fine, as is running VS Code with no windows open or making a single file or folder and opening it in VS Code.

I followed these instructions to narrow down the problem: https://github.com/microsoft/vscode/wiki/Performance-Issues

[Here is a link to the CPU profile collected](https://www.dropbox.com/s/mch1zh53hfzexka/CPU-20201104T161409.cpuprofile?dl=0) according to the instructions above.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--disable-extensions --crash-reporter-id c85288e9-112f-4db7-9988-df1c28170765|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    98	 36290	code main
    0	    49	 36300	   gpu-process
    0	    16	 36302	   utility
    0	    82	 36325	   shared-process
    0	     0	 36796	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   246	 36718	   window (Settings — cypress (Workspace))
    0	    98	 36723	     extensionHost
    0	    33	 36760	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=36723
  168	   197	 36724	     watcherService
    0	    66	 36794	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings — cypress (Workspace))
|    Folder (cypress): 9978 files
|      File types: hs(2160) sql(1746) elm(834) md(773) tf(589) nix(297)
|                  js(191) dhall(180) yaml(139) sh(101)
|      Conf files: tsconfig.json(1) settings.json(1) package.json(1);
```

</details>
Extensions disabled

**Comment by bpasero** [comment]
@krinhorn can you open the vscode process explorer from help and see which process spins high?

**Comment by krinhorn** [comment]
@bpasero Thanks for the guidance! Looks like `watcherService`?
![image](https://user-images.githubusercontent.com/31359690/98262125-3eb92600-1f53-11eb-9eef-b196f0dcb7c2.png)

**Comment by krinhorn** [comment]
oh, thank you! :D

**Comment by krinhorn** [comment]
@bpasero How large is "large"? This is the folder in question...
![image](https://user-images.githubusercontent.com/31359690/98263550-fa2e8a00-1f54-11eb-93db-212cf04451a8.png)
