### ISSUE TITLE
Keyboard navigation to "Don't Save" will not discard the file.

### ISSUE THREAD

**Issue by kuppalli** [microsoft/vscode#109943]
Issue Type: <b>Bug</b>

1. Create a new file.
2. enter some random text into the file
3. try to close the file by clicking 'x' on the file tab.
4. A popup appears saying "Do you want to save the changes you made to <something> ?
5. Try to focus on 'Don't Save' button using keyboard.
6. once focused hit  'enter' key from keyboard.

<img width="1373" alt="2020-11-03_21-55-35" src="https://user-images.githubusercontent.com/1990686/98064037-61e2b900-1e1f-11eb-8919-e9aa56f4610e.png">

issue:
instead of discarding the file it prompts to save the file.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.67GB free)|
|Process Argv|--crash-reporter-id d8eb55e6-b34f-4500-a8e1-1fee56f1d8b6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.3
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.1
auto-rename-tag|for|0.1.5
vscode-language-babel|mgm|0.0.30
vscode-mjml|mjm|1.0.1
remote-containers|ms-|0.145.1
debugger-for-chrome|msj|4.12.11
material-icon-theme|PKi|4.4.0
sonarlint-vscode|Son|1.18.0
vscodeintellicode|Vis|1.2.10
material-theme|zhu|3.9.3

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Sorry but we are not here to explain operating system behaviour. Please ask over at Apple support for help.
