### ISSUE TITLE
fileSystemWatcher ignore folder level changes/create/delete

### ISSUE THREAD

**Issue by ShenChen-Amazon** [microsoft/vscode#109994]
- VSCode Version: 1.50.1
- OS Version: MacOS

Hi,

I am building an extension with fileSystemWatcher feature.

From the api doc: https://code.visualstudio.com/api/references/vscode-api#FileSystemWatcher. The `onDidCreate` and `onDidDelete` event should be fired when file/folder changed. However, the a fileSystemWatcher only fires when file created / deleted, but not working when folder created and deleted.

Steps to Reproduce:
1. download the helloworld-sample, install dependencies.
2. In extension.ts activate function,  create a fileSystemWatcher by using code such as 
```
const watcher = vscode.workspace.createFileSystemWatcher("**/foo/**/*.*");
    watcher.onDidChange(() => {
        void vscode.window.showWarningMessage('something changed');
    });

    watcher.onDidCreate(() => {
        void vscode.window.showWarningMessage('something created');
    });

    watcher.onDidDelete(() => {
        void vscode.window.showWarningMessage('something deleted');
    });
```
3. use debug tab to run extension. And use command + shift + P to open command drop box, choose `hello world `, and see the Hello World be printed at the right bottom corner.

4. Open an empty folder and create a folder named as `foo` under opened folder.

5. Create a test.json under `foo` folder, will see `something created` at the right bottom corner.

6. Create a folder named as `bar` under `foo`, but there' nothing logged out.

7. Create a file named as `test.json` under `bar` folder, will see `something created` at the right bottom corner.

8. Delete the entire `bar` folder, even the `test.json` is deleted along with the bar folder, nothing will be logged out.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by eamodio** [comment]
I believe the issue is your pattern of `*.*` in `const watcher = vscode.workspace.createFileSystemWatcher("**/foo/**/*.*");`. That will limit to files. If you just remove that I think you will get what you need.
