### ISSUE TITLE
`question` How auto-updates working with electron

### ISSUE THREAD

**Issue by havenchyk** [Microsoft/vscode#1099]
Hi, it's a question about build process. I can't find in sources the correct place where auto-update implemented. Do you use Squirrel for it? 

Sorry if it's not a good place to ask.

**Comment by egamma** [comment]
We use squirrel for the mac auto update and Inno on Windows (see http://blogs.msdn.com/b/vscode/archive/2015/09/11/updated-windows-installer-for-vs-code.aspx)

**Comment by havenchyk** [comment]
@egamma thanks!

**Comment by havenchyk** [comment]
@egamma maybe you can also share the link to information, how code's team prepare builds for windows and mac? Are you using windows to make build for windows and mac for mac build? Maybe there is already blog post? otherwise it would be cool topic for the new article in the blog :)

**Comment by egamma** [comment]
There is no blog post yet and I have no link I can share yet, but I agree that this would be a good topic for an engineering blog post. Is your background that you would be interested in building electron apps in general or is it VS Code specific?

**Comment by havenchyk** [comment]
@egamma both. I'm trying to build electron app as my pet project, but I use VSCode to do it and since in the VSCode has been done great job to build and deliver this type of application, it's very interesting for me(and I believe for many other developers) to understand, how to set up this build process, I didn't find enough information in the electron's docs.

**Comment by egamma** [comment]
@havenchyk makes sense, thanks.

**Comment by havenchyk** [comment]
Hey @egamma, is there any news?

**Comment by egamma** [comment]
Sorry no news, except that we will change the auto update support in January so that different versions (alpha, beta, stable) can be installed side-by-side.

**Comment by afreeland** [comment]
Any information yet? I think that vscode has done a great job with this functionality and would be really interested to read about the thought process and implementation =)
