### ISSUE TITLE
[linked editing] finalize LinkedEditingRangeProvider

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#109923]
The OnTypeRenameProvider allows the editor to apply a rename to a symbol automatically to other ranges as well.

The feature can be seen in action in HTML, where modifications to an open tag is automatically applied to the close tag (and vice versa). (Requires settings: `"editor.renameOnType": true`)

```ts
	/**
	 * The 'on type' rename provider interface defines the contract between extensions and
	 * the 'on type' rename feature.
	 */
	export interface OnTypeRenameProvider {
		/**
		 * For a given position in a document, returns the range of the symbol at the position and all ranges
		 * that have the same content and can be renamed together. Optionally a result specific word pattern can be returned as well
		 * that describes valid contents. A rename to one of the ranges can be applied to all other ranges if the new content
		 * matches the word pattern.
		 * If no result-specific word pattern is provided, the word pattern defined when registering the provider is used.
		 *
		 * @param document The document in which the provider was invoked.
		 * @param position The position at which the provider was invoked.
		 * @param token A cancellation token.
		 * @return A list of ranges that can be renamed together. The ranges must have
		 * identical length and contain identical text content. The ranges cannot overlap. Optionally a word pattern
		 * that overrides the word pattern defined when registering the provider can be provided.
		 */
		provideOnTypeRenameRanges(document: TextDocument, position: Position, token: CancellationToken): ProviderResult<{ ranges: Range[]; wordPattern?: RegExp; }>;
	}

	namespace languages {
		/**
		 * Register a 'on type' rename provider.
		 *
		 * Multiple providers can be registered for a language. In that case providers are sorted
		 * by their [score](#languages.match) and the best-matching provider that has a result is used. Failure
		 * of the selected provider will cause a failure of the whole operation.
		 *
		 * @param selector A selector that defines the documents this provider is applicable to.
		 * @param provider An 'on type' rename provider.
		 * @param wordPattern A word pattern to describes valid contents of renamed ranges.
		 * @return A [disposable](#Disposable) that unregisters this provider when being disposed.
		 */
		export function registerOnTypeRenameProvider(selector: DocumentSelector, provider: OnTypeRenameProvider, wordPattern?: RegExp): Disposable;
	}
```

**Comment by jrieken** [comment]
* pattern per result only
* result as object with ctor
* what about multi cursor?

**Comment by aeschli** [comment]
Adopted feedback: New state:
```
	/**
	 * The 'on type' rename provider interface defines the contract between extensions and
	 * the 'on type' rename feature.
	 */
	export interface OnTypeRenameProvider {
		/**
		 * For a given position in a document, returns the range of the symbol at the position and all ranges
		 * that have the same content and can be renamed together. Optionally a word pattern can be returned
		 * to describe valid contents. A rename to one of the ranges can be applied to all other ranges if the new content
		 * is valid.
		 * If no result-specific word pattern is provided, the word pattern from the language configuration is used.
		 *
		 * @param document The document in which the provider was invoked.
		 * @param position The position at which the provider was invoked.
		 * @param token A cancellation token.
		 * @return A list of ranges that can be renamed together
		 */
		provideOnTypeRenameRanges(document: TextDocument, position: Position, token: CancellationToken): ProviderResult<OnTypeRenameRanges>;
	}

	namespace languages {
		/**
		 * Register a 'on type' rename provider.
		 *
		 * Multiple providers can be registered for a language. In that case providers are sorted
		 * by their [score](#languages.match) and the best-matching provider that has a result is used. Failure
		 * of the selected provider will cause a failure of the whole operation.
		 *
		 * @param selector A selector that defines the documents this provider is applicable to.
		 * @param provider An 'on type' rename provider.
		 * @return A [disposable](#Disposable) that unregisters this provider when being disposed.
		 */
		export function registerOnTypeRenameProvider(selector: DocumentSelector, provider: OnTypeRenameProvider): Disposable;
	}

	/**
	 * Represents a list of ranges that can be renamed together along with a word pattern to describe valid range contents.
	 */
	export class OnTypeRenameRanges {
		constructor(ranges: Range[], wordPattern?: RegExp);

		/**
		 * A list of ranges that can be renamed together. The ranges must have
		 * identical length and contain identical text content. The ranges cannot overlap.
		 */
		readonly ranges: Range[];

		/**
		 * An optional word pattern that describes valid contents for the given ranges.
		 * If no pattern is provided, the language configuration's word pattern will be used.
		 */
		readonly wordPattern?: RegExp;
	}
```

**Comment by jrieken** [comment]
/Naming nit/ - In the past we haven't been super consistent but when the function is called `provideOnTypeRenameRanges` (which I like) than the provider should be called `OnTypeRenameRangeProvider` = today is misses `Range` tho it is rename ranges that it provides

**Comment by gjsjohnmurray** [comment]
@jrieken why `Range` and not `Ranges`?

**Comment by jrieken** [comment]
Actually unsure but that's the majority of cases. I'd say the logic is that a provider can provide a thing and then there is call to provide many - and in some case a call to resolve one.

**Comment by aeschli** [comment]
Makes sense. I made the rename to OnTypeRenameRangeProvider

**Comment by aeschli** [comment]
We discussed that the `Rename` in `OnTypeRenameRangeProvider` is misleading. The feature is not so much about renaming a symbol, but more making concurrent edits. 
We stared brainstorming on better names:
 - OnTypeLinkedEditing (by @dbaeumer)

**Comment by jrieken** [comment]
`LinkedEditingRangeProvider`, `providedLinkedEditingRanges(): LinkedEditingRange[]`

**Comment by IllusionMH** [comment]
`...LinkedEditing...` looks great and intuitive if looked from this perspective. Maybe `...SyncedEditing...` or `...SyncEditing...` as alternative, however I'm not sure if "sync" variation were used for initial HTML implementation and was discarded later.

**Comment by dbaeumer** [comment]
What I liked about `onTypeLinkedEditing` is the fact that it indicates (like `onTypeFormatting`) that this request is send with high frequency. However this being said the same is true for completion :-). So I am fine going with @jrieken proposals. 

@aeschli when do you plan to do the renaming. Then I will catchup with LSP

**Comment by jrieken** [comment]
> What I liked about onTypeLinkedEditing is the fact that it indicates (like onTypeFormatting) that this request is send with high frequency.

In fact they are both different. OnType-formatting happens rarely and only when typing trigger characters - which you have listed beforehand. Linked editing happens on cursor move and should actually not happen when typing within a returned linked range. I'd say the frequency of linked editing ranges is similar to mark occurrences

**Comment by aeschli** [comment]
Moved to public vscode.d.ts.

To verify, please create a small extension, install it like a regular extension and verify it works (no more proposedAPI checks)

**Comment by johnsoncodehk** [comment]
I found this registerOnTypeRenameProvider is work to `html-language-features` in VSCode v0.15.1, but it not working when I try to following `html-language-features` to added `client.registerProposedFeatures()` and `"enableProposedApi": true`. 

It should be work? or use proposed API in non Insiders VSCode is built-in package's privilege?

**Comment by aeschli** [comment]
Yes, built-in extensions are allowed to use proposed API also in stable.

But the new API is now public in 1.52: `languages.registerLinkedEditingRangeProvider`

**Comment by johnsoncodehk** [comment]
@aeschli can't wait for it! :) can turn `editor.linkedEditing` default on? otherwise 99% of users will miss it.

**Comment by Ares9323** [comment]
> registerLinkedEditingRangeProvider

Can you please explain how to use this setting?
I have version 1.52.1 and settings.json says "Unknown Configuration Settings"
I have read the documentation for both "editor.renameOnType" and "editor.linkedEditing" but it looks like there's nothing there.

I'd like to have an example of the syntax of this setting too, I tried several but none of them matched.

An extension I use to beautify files only supports html, js and css and I managed to make it work with "blade" and "php" files as they were .html with this setting:
`"beautify.language": {"html": ["htm","html","php","blade",]},`
Do I have to do something similar or do I just need to type the extension in a particular way?

Thanks in advance, have a nice day
