### ISSUE TITLE
unprotected node binary

### ISSUE THREAD

**Issue by ohhmm** [microsoft/vscode#109983]
Issue Type: <b>Bug</b>

the node is in app data and unsigned which causes various vulnerabilities

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 3990X 64-Core Processor  (64 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (14.81GB free)|
|Process Argv|--crash-reporter-id e54c389b-114c-4176-98d3-43554e7607f5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|AMD Ryzen Threadripper 3990X 64-Core Processor  (64 x 3600)|
|Memory (System)|31.88GB (14.82GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.50.1
cmake-tools|ms-|1.4.2
cpptools|ms-|1.1.0-insiders3

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/190779/98171165-f28cc800-1ef7-11eb-9bd5-abec56fbd5ad.png)

**Comment by weinand** [comment]
Please provide reproducible steps.
