### ISSUE TITLE
There is no formatter for 'json' files installed. when a big json file opened 53.8 MB

### ISSUE THREAD

**Issue by jliu666** [microsoft/vscode#109995]
- VSCode Version:
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362
Just open a big json,use Alt Shift F to format.

**Comment by aeschli** [comment]
@jrieken I think most language services are disabled for large files, correct?

**Comment by jrieken** [comment]
Yes, files larger than a certain limit (I recall 50MB but might be wrong) never make it to extension host

**Comment by aeschli** [comment]
Closing. Behavior is as expected and necessary for performance reasons.
