### ISSUE TITLE
Support to skip over non-letter characters in a file search

### ISSUE THREAD

**Issue by bbugh** [microsoft/vscode#109910]
- VSCode Version: 1.50.1
- OS Version: Mac 10.14.6 

Steps to Reproduce:

1. Quick File Open
2. Enter a bunch of letters that do fuzzy match a file, but then add in the wrong special character
3. Observe that the high-match fuzzy item is removed because of the special character

Does this issue occur when all extensions are disabled?: Yes

---

I looked through many other issues for this request and went through relevant-looking issues in #27317, apologies if it's a dupe.

It would be fantastic if the fuzzy quick open matcher could also ignore/lower the weight of special character differences used in filenames. Working in multiple languages every day, it's easy to forget who is using `PascalCase`, `snake_case` or `kebab-case` for filenames. Typing any `_` or `-` does not match the other and removes any word matches. 

This happens to me multiple times a day where I've entered the correct general letter pattern but have a space or a dash that doesn't match completely, and despite the file I'm looking for having the strongest fuzzy match, it's entirely eliminated from the list.

Thanks for consideration!

---
**Example 1**

Oops
<img width="133" alt="Pasted_Image_11_3_20__6_31_AM" src="https://user-images.githubusercontent.com/438465/97985700-3c619b00-1d9e-11eb-984c-94a9c59d6d6a.png">

Oops
<img width="166" alt="image" src="https://user-images.githubusercontent.com/438465/97985745-4daaa780-1d9e-11eb-94fb-9b4f1b211b30.png">

⭐️
<img width="174" alt="image" src="https://user-images.githubusercontent.com/438465/97986118-daedfc00-1d9e-11eb-8383-5c25d1308891.png">

---
**Example 2**

<img width="175" alt="image" src="https://user-images.githubusercontent.com/438465/97987009-340a5f80-1da0-11eb-8f7c-6d094336813e.png">

Oops
<img width="156" alt="image" src="https://user-images.githubusercontent.com/438465/97987041-3ff62180-1da0-11eb-9bde-0e061e502a8c.png">

Oops
<img width="129" alt="image" src="https://user-images.githubusercontent.com/438465/97986493-65366000-1d9f-11eb-86b3-820d61e0d6bd.png">

⭐️
<img width="189" alt="image" src="https://user-images.githubusercontent.com/438465/97986514-6f585e80-1d9f-11eb-948b-e8c3f56b865c.png">

**Comment by bpasero** [comment]
@bbugh to clarify, you want the fuzzy matcher in quick open to ignore `-` or `_`?

**Comment by bbugh** [comment]
@bpasero that does seem like one option, though I think that would produce suboptimal matches. I think a more optimal matcher would be to weight exact matches of special characters, but change the fuzzer so it doesn't completely eliminate non-matching special characters.

To compare, in a levenshtein distance, `project-vue`, `project_vue`, and `project vue` are equally close and would all have selected `Project.vue` as the strongest match. Whereas with the fuzzer, 2 of 3 of those strong matches are removed entirely from the list. `project.vue` would be a closer distance. (Not saying it needs to do levenshtein, just an example).

It could also consider `['-', '_', '/', '.', ' ']` and maybe other common filename characters having the same values, though I'm not sure that would work as well because I don't think it would select effectively for camel/Pascal case.

**Comment by bpasero** [comment]
This will need support from search (RipGrep) and is unlikely to happen I guess because this has the potential of returning a lot more results than expected. 

Moving to @roblourens for comment, but feel free to close as designed.

**Comment by bbugh** [comment]
Thanks for the reply. I'm not sure what ripgrep's involvement is since I'm referring to file name search (Cmd+P), not file content search. Sorry if that wasn't clear. 

I was not able to find an entry point for `quickOpen` where fuzzy file pattern comparison happens. Could you point me to in the code where the quick pick query is compared to the file name list? I see all the fuzzy stuff but wasn't able to parse the abstractions to find the origin source of `query <-fuzzy-> filename`. 

You're probably right since you obviously know more about the internal operations than I do, but this causes me enough stress that I'd like to take a shot at it.

**Comment by bpasero** [comment]
Yes, we use RipGrep library for file name search too.

**Comment by roblourens** [comment]
@bpasero ripgrep is not analyzing the search query or doing fuzzy matching, that is all us

**Comment by bpasero** [comment]
@roblourens ah ok I was not aware of that. Do you say that RipGrep does not have support to match on file names? Only on textual content?

**Comment by roblourens** [comment]
I mean it's just how file search works, rg returns all files then we do the fully filtering
