### ISSUE TITLE
Middle click paste doesn't work on Linux

### ISSUE THREAD

**Issue by dflock** [Microsoft/vscode#110]
On linux, whenever you select some text, this text is automatically placed onto a separate X11 clipboard called PRIMARY. This can then be pasted anywhere by middle clicking.

This works (pretty much) everywhere - including other electron apps like Atom - but doesn't work in Visual Studio Code, sadly.

VSCode Version:

Version 0.10.1
Commit df352367df2efcfa9d602d471e4e2f42140a0f05
Date 2015-11-17T15:21:23.766Z
Shell 0.34.1
Renderer 45.0.2454.85
Node 4.1.1

Linux Version:

Ubuntu 13.10

**Comment by aniljava** [comment]
Same problem in:

Version 0.10.1
Commit df352367df2efcfa9d602d471e4e2f42140a0f05
Date 2015-11-17T15:21:23.766Z
Shell 0.34.1
Renderer 45.0.2454.85
Node 4.1.1

Ubuntu 15.04

**Comment by pavlos256** [comment]
Please make it optional. Middle-click can happen by accident when scrolling.

**Comment by dflock** [comment]
It's not optional in any other linux software that I know of?

**Comment by alexandrudima** [comment]
Just to be sure I do the right thing:

The change should be: "middle click should be bound to paste in Linux" (i.e. what Ctrl-V does)

**Comment by dflock** [comment]
Nope.

Linux, via XWindows, has multiple clipboards. One called CLIPBOARD is used for Windows style ctrl+c, ctrl-v copy & paste. One called PRIMARY is used to do middle click paste. This works like this:

- You select some text somewhere. This selection is automatically copied to the PRIMARY clipboard, live, as you're selecting it. This just happens without the user doing anything, other than selecting text.
- When you middle click somewhere, the contents of the PRIMARY clipboard are inserted at the cursor.

You just have to implement/support the second step.

Like I said, [Atom](http://atom.io), which is also based on electron and is open source - supports this correctly; so I might be possible to look at their implementation?

**Comment by zevero** [comment]
:thumbsup:
Middle click already works for pasting the filename to create a new file...

**Comment by honzahana** [comment]
Version 0.10.8 still not works (Ubuntu 14.04). Hope VSC has faster support team then Skype (bugs 2 years not fixed).

**Comment by jcward** [comment]
Yes, it's not the same as paste -- the dual clipboard thing is often irritating, but at least standard on Linux. I use it all the time.

I'd assume it's a high-level X-windows function. Something high-level in the code must be blocking it for the editor portions of the window. Because it works to middle-click paste into this pop-up text input:

![image](https://cloud.githubusercontent.com/assets/2192439/13821413/28500fca-eb67-11e5-969a-eacd49808e2c.png)

And it works in the find/replace pop-up dialogs:

![image](https://cloud.githubusercontent.com/assets/2192439/13821456/6b5ae902-eb67-11e5-9d6e-9029b1443f94.png)

**Comment by lianghu** [comment]
It's still not working in the Feb release.

**Comment by alexandrudima** [comment]
With the March release, it will be under a setting called `"editor.selectionClipboard"`, which is off by default until we better understand the perf implications of writing to the clipboard on every selection change.

**Comment by zevero** [comment]
It is working great!
Thank you!

**Comment by Tyriar** [comment]
@alexandrudima I've had it turned on for a while now and haven't had any issues. I don't use it often, I've probably used it around 4-5 times spread out across that time. Do you think it's safe to turn on by default?

**Comment by alexandrudima** [comment]
:+1:
