### ISSUE TITLE
Cannot open notebook of type 'PowerShellNotebookModeOption'.

### ISSUE THREAD

**Issue by itzjustalan** [microsoft/vscode#110016]
- VSCode Version: 1.46.0
- OS Version: Windows 2004

Steps to Reproduce: 

1. open any .ps1 file
2.

Does this issue occur when all extensions are disabled?: Yes/No yes

**Comment by rebornix** [comment]
We don't currently support native notebook in VS Code stable.

**Comment by itzjustalan** [comment]
nvm guys just did an update and it loads up fine
