### ISSUE TITLE
Only show show recently opened folders if they exist

### ISSUE THREAD

**Issue by Matt-Gleich** [microsoft/vscode#110029]
When I bring up the recently opened section and search for a folder it shows deleted or moved folders. It would be great for cleanliness if the deleted files/folders wouldn't be shown.

**Comment by sbatten** [comment]
this would involve having the history service check each entry for existence and destroying it. not only is this expensive itself with a lot of entries, some may be transient and we cannot know if the item is deleted or only present sometimes. for this reason, we only check the status when the user tries to open the file/folder.

**Comment by sbatten** [comment]
sorry @Matt-Gleich, but if you are not aware, when you try to open a deleted file, it will ask to be removed from the list so you can manually clean up
