### ISSUE TITLE
Terminal does not work out of the box

### ISSUE THREAD

**Issue by IntelligentFunction** [microsoft/vscode#110022]
Issue Type: <b>Bug</b>

Hi, I've just installed visual studio code on Linux Mint, and the Terminal does not work, no prompt just a blinking cursor unable to type any characters at all. 

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 4.15.0-122-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4026)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 2, 2|
|Memory (System)|31.29GB (16.56GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id fe537777-9223-4cc2-af4f-90d2f3297c89|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.6
django|big|1.0.2
vscode-postgres|cko|1.1.14
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.3
vscode-html-css|ecm|0.2.3
file-icons|fil|1.0.27
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.1
beautify|Hoo|1.5.0
python|ms-|2020.10.332292344
cpptools|ms-|1.0.1
node-debug2|ms-|1.42.5
sqltools|mtx|0.23.0
deepdark-material|Nim|3.2.1
material-icon-theme|PKi|4.4.0
code-clip-ring|Sir|0.4.0
emacs-mcx|tut|0.23.5
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0

(8 theme extensions excluded)

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Tyriar** [comment]
Can you try get a trace log? This will give details on how the terminal launched exactly: https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
