### ISSUE TITLE
TypeScript Code quoted with `  not folded properly 

### ISSUE THREAD

**Issue by ap00rv** [microsoft/vscode#110097]
VSCode Version: 1.50.1
OS Version: macOS mojave 10.14.6

Steps to Reproduce:

1. Write a variable in TypeScript that is quoted with `  and spans multiple lines. 

Example :
```
const a = `32
sdsdsd
sdsds`;

```
2. Fold it and observe that end ` and semicolon is not shown. 

![Screen Shot 2020-11-06 at 9 49 29 AM](https://user-images.githubusercontent.com/10767622/98398513-f1ea5380-2015-11eb-8206-ea191a01f0a9.png)

❗  This bug is similar to #109854 , which is now closed. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by sumanbk92** [comment]
I'm interested in fixing this bug. Could you please let me know where to start / help me identify where to look into ?

Many Thanks,
Suman

**Comment by ap00rv** [comment]
hi @sumanbk92 , I am not a VSCode core developer but you can look at the commit which fixed #109854 to get some clues.

**Comment by sumanbk92** [comment]
Raised a PR for this issue - https://github.com/microsoft/vscode/pull/110108

**Comment by mjbvz** [comment]
Fixed by #110108
