### ISSUE TITLE
Out-of-memory on large size terminal output

### ISSUE THREAD

**Issue by OneMoreSecond** [microsoft/vscode#110004]
Issue Type: <b>Bug</b>

**Reproduction steps**
1. (Maybe optional) connect to a remote server via SSH
2. In the integrated terminal, run a program which will write a lot of things to stdout
3. The editor window dies with a pop-out box saying 'OOM'.

**Proposed solution**
Add a new option for controlling memory used by the terminal, and discard old content in the terminal.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.14393
Remote OS version: Linux x64 5.4.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.01GB free)|
|Process Argv|--crash-reporter-id e562f803-0647-49e2-8b05-490928911d2f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: TTS-GPU-1|
|OS|Linux x64 5.4.0-45-generic|
|CPUs|Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz (32 x 800)|
|Memory (System)|62.57GB (1.87GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-idl|kur|0.1.2
vscode-docker|ms-|1.7.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
unique-lines|bib|1.0.0
vscode-terminals|fab|1.12.9
kite|kit|0.134.0
bash-ide-vscode|mad|1.11.0
rainbow-csv|mec|1.7.1
vscode-docker|ms-|1.7.0
python|ms-|2020.10.332292344
vscode-pylance|ms-|2020.11.0
python-docs|Muk|0.8.3

</details>

**Comment by Tyriar** [comment]
I'd expect this to be fixed with https://github.com/microsoft/vscode/issues/74620

/duplicate
