### ISSUE TITLE
VSCode with WSL - Debug mode of C won't show printf commands unless using /n

### ISSUE THREAD

**Issue by shirans7** [microsoft/vscode#110054]
- VSCode Version: 1.50.1
- OS Version: Windows 10 (build 2004) with WSL enabled

When debugging a C language code with gdb there is no output showing if using the following print command:
printf("%d", i);
but using the same command with /n printf("%d\n", i) makes the output showed in the terminal.

I have created this sample code to show the differences:

![image](https://user-images.githubusercontent.com/74029967/98315498-fb0cfd80-1fe0-11eb-80d2-516818681595.png)
![image](https://user-images.githubusercontent.com/74029967/98315568-268fe800-1fe1-11eb-856f-84eac54f550a.png)

Adding my launch.json file:

![image](https://user-images.githubusercontent.com/74029967/98315680-6bb41a00-1fe1-11eb-8d9f-fc0038c3da0e.png)

Any idea how can I fix it?

**Comment by weinand** [comment]
pls see https://stackoverflow.com/questions/1716296/why-does-printf-not-flush-after-the-call-unless-a-newline-is-in-the-format-strin
