### ISSUE TITLE
Suggestions status bar settings key wrong in 1.51.0 release notes

### ISSUE THREAD

**Issue by lobsterkatie** [microsoft/vscode#110089]
Issue Type: <b>Bug</b>

In the "Status bar for suggestions" section of the release notes, it says the settings key for enabling it is `editor.suggestStatusBar.enable`, but that key doesn't exist in settings. Instead, it appears to be `editor.suggest.showStatusBar`.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 6|
|Memory (System)|32.00GB (0.39GB free)|
|Process Argv|-psn_0_8439820 --crash-reporter-id b0279d3b-8393-4b25-b76f-67c5cd50b58e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.37.2
vscode-eslint|dba|2.1.13
nunjucks-vscode-extensionpack|dou|0.0.1
gitlens|eam|10.2.3
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.1
vscode-firefox-debug|fir|2.9.1
shell-format|fox|7.0.1
vscode-pull-request-github|Git|0.21.0
docthis|joe|0.7.1
rust-analyzer|mat|0.2.368
dotenv|mik|1.0.1
python|ms-|2020.10.332292344
vscode-pylance|ms-|2020.11.0
sublime-keybindings|ms-|4.0.7
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
indent-rainbow|ode|7.4.0
subtle-brackets|raf|3.0.0
vscode-gitweblinks|red|1.8.1
rust|rus|0.7.8
crates|ser|0.5.3
code-settings-sync|Sha|3.4.3
mdx|sil|0.1.0
ascii-plist|spe|1.0.3
rewrap|stk|1.13.0
vscodeintellicode|Vis|1.2.10
vscode-mdx-preview|xyc|0.3.0
vscode-open-in-github|ziy|1.3.6

(6 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate
Fixed via https://github.com/microsoft/vscode-docs/issues/4113
