### ISSUE TITLE
Sync issue: Some extensions are automatically uninstalled as soon as they are installed.

### ISSUE THREAD

**Issue by Teassassin** [microsoft/vscode#110017]
Issue Type: <b>Bug</b>

Unable to install some extension.
Some extensions are automatically uninstalled as soon as they are installed.
When I turn off Sync, everything is back to OK.
有些扩展安装后会立即被自动卸载掉，关掉同步后就好了。

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.95GB free)|
|Process Argv|--crash-reporter-id f9c63df5-c7c2-42bb-bda0-2cee39ff5bf3|
|Screen Reader|no|
|VM|50%|
</details>

**Comment by sandy081** [comment]
Are you able to repro it consistently? If so please follow following steps:

- Open Settings Sync Log in Output view in the bottom section
- Try to reproduce the issue and provide us the logs.
