### ISSUE TITLE
Fails renaming folders and files

### ISSUE THREAD

**Issue by andrei811** [microsoft/vscode#110064]
- VSCode Version: 1.50.1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Use Visual Studio Code for a while
2. Try to rename a folder

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can not reproduce. Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

Do you use wsl?

**Comment by andrei811** [comment]
After about an hour of use (while all was working just fine), when I try to rename a folder it says:

`Error: Unable to move <folder_name> into <opened_folder> (Error: EBUSY: resource busy or locked, rename <folder_name_path> -> <open_folder_path> `

I was able to reproduce it even in Visual Studio Code Insiders, and I'm not using wsl.

**Comment by isidorn** [comment]
Well the error says what is going on. The item is busy - thus it is used by some other process.
Shutdown all other processes and this will not happen.
Closing as this is designed behavior

**Comment by andrei811** [comment]
No, isn't used in any other process, that's the problem. And it happened many times for me.

**Comment by isidorn** [comment]
fyi @deepak1556 for electron ideas.
