### ISSUE TITLE
TS Server fatal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by higrw123** [microsoft/vscode#110053]
❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.2.0-dev.20201105

**Steps to reproduce crash**
1. {
    "imports": {        
        "immutablejs": "https://esm.sh/immutable@4.0.0-rc.12"
    }
}
2. import { Map } from "immutablejs";
3. crash

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
RangeError: Maximum call stack size exceeded
    at parse (<anonymous>)
    at new URL (internal/url.js:319:5)
    at Function.create (/home/grw/.vscode/extensions/denoland.vscode-deno-2.3.2/node_modules/typescript-deno-plugin/out/core/hash_meta.js:76:43)
    at CacheModule.resolveModule

**Comment by mjbvz** [comment]
Caused by the deno extension (see callstack)
