### ISSUE TITLE
pwa-node debugger launch type with runtimeVersion and nvm causes PATH to be reset

### ISSUE THREAD

**Issue by jamie-pate** [microsoft/vscode#110049]
- VSCode Version: 
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.0-7625-generic

- OS Version: 
Distributor ID: Pop
Description:    Pop!_OS 20.10
Release:        20.10
Codename:       groovy

Steps to Reproduce:

1. Add a launch config that uses `pwa-node`, `runtimeVersion` in an environment that uses `nvm`

`node` works fine and `pwa-node` works fine when `runtimeVersion` is not set.

e.g. 

```JSON
{
            //"type": "node",
            "type": "pwa-node",
            "request": "launch",
            "name": "NodeJS run file",
            "runtimeVersion": "12.13.1",
            "program": "${file}",
            "cwd": "${workspaceFolder}/pkg/angular",
            //"skipFiles": ["<node_internals>/**"],
            "console": "integratedTerminal",
            "resolveSourceMapLocations": [
                "${workspaceFolder}/**",
                "!**/node_modules/**",
                "!**/.yarn/**"
            ],
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "fos_allow_foreign_node":"yes",
            },
            "outFiles": [
                "${workspaceRoot}/Gruntfile.js",
                "${workspaceRoot}/grunt_tasks/**/*.js",
                "${workspaceRoot}/pkg/**/*.js"
            ],
            "args": [
                "watch",
            ]
        },
```

2. Run your node application

```JavaScript
console.log('PATH=',process.env.PATH);
process.exit(1);
```

PATH no longer contains useful locations such as `/usr/bin`

```
Process exited with code 1
PATH= /home/jpate/.nvm/versions/node/v12.13.1/bin
```

Does this issue occur when all extensions are disabled?: Yes

To workaround this issue you can set PATH in the "env" section manually, but it sucks :D

**Comment by connor4312** [comment]
It sounds like you're hitting https://github.com/microsoft/vscode/issues/106537

/duplicate

**Comment by jamie-pate** [comment]
Cool, the original issue has _none_ of the keywords I was looking for so hopefully this dup helps steer ppl towards *Revisit hardcoded timeout for resolving shell environment blocking first window* :D
