### ISSUE TITLE
Allow to register a language for an output channel

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#11005]
I have taken the idea from this extension https://github.com/formulahendry/vscode-code-runner and created a language + grammar to highlight the output of my extension:

```
  "contributes": {
    ...
    "languages": [
      {
        "id": "wallaby-output",
        "mimetypes": [
          "text/x-code-output"
        ]
      }
    ],
    "grammars": [
      {
        "language": "wallaby-output",
        "scopeName": "wallaby.output",
        "path": "./wallaby-output.tmLanguage"
      }
    ]
  },
```

![screen shot 2016-08-26 at 6 31 37 pm](https://cloud.githubusercontent.com/assets/979966/17999152/5feb3a20-6bbb-11e6-8e69-9dc2e5633170.png)

It seems to work ok, but because of using the `text/x-code-output` mime type, the languages and its grammar gets applied to all output channels, not just mine. So not only my extension and other extensions using the same trick may clash with other output channels and each other, also some built-in features seem to stop working in all output channels - for example the file absolute paths detection stops creating links for the paths.

I'm wondering if it's possible to somehow constraint a language to work only within a specific output channel? If not, would it be possible to add such feature?

**Comment by ArtemGovorov** [comment]
From the API perspective, it'd be nice if the
```
export function createOutputChannel(name: string): OutputChannel;
```
function also accepted a `languageId: string`, or perhaps ai instance of `DocumentSelector`, but this may be an overkill for this specific purpose.

**Comment by jrieken** [comment]
Cool, idea. I'd go with `languageId` or an `Uri` when creating a channel.

**Comment by ArtemGovorov** [comment]
BTW, apart from being able to colorize an output channel, [here's another scenario](https://github.com/Microsoft/vscode/issues/586#issuecomment-248184108) that the feature implementation enables - implementing and registering any custom link providers for an output channel (we're using it for test links on the screenshot above).

**Comment by ArtemGovorov** [comment]
In v1.7 mimetypes were removed, so the [workaround doesn't work anymore](https://github.com/Microsoft/vscode/issues/13502) and currently custom output highlighting is broken in our extension, and few other extensions using the same trick, such as:
- https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner (https://github.com/IBM-Bluemix/vscode-log-output-colorizer/blob/master/package.json#L40)
- https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer&cm_mc_uid=85884614434214761902558&cm_mc_sid_50200000=1476190255 (https://github.com/formulahendry/vscode-code-runner/blob/master/package.json#L162)

**Comment by jrieken** [comment]
hm... @isidorn can you comment?

**Comment by isidorn** [comment]
I will comment here https://github.com/Microsoft/vscode/issues/13502 since @ArtemGovorov already created that issue

**Comment by jroesch** [comment]
Is anyone actively working on this issue? I think I understand how to make the change for this, and would be willingly to give it a shot sometime later this week.

**Comment by ArtemGovorov** [comment]
@jroesch Did you have a chance to look into this one? 

@jrieken I see more and more extension using `text/x-code-output` mime type and simply breaking each other because of this. For example an output channel highlighting supplied by one extension is breaking highlighting from other extension (even though they are highlighting completely different independent output channels).

**Comment by jrieken** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by seanpoulter** [comment]
@jrieken, would t be considered if I submitted a PR?

**Comment by xhliu** [comment]
Any fix coming? Seems a very useful feature.

**Comment by freedomhero** [comment]
Any update for this feature request?

**Comment by zhfnjust** [comment]
we need this feature
