### ISSUE TITLE
File > Save As, does not work!

### ISSUE THREAD

**Issue by entozoon** [microsoft/vscode#110071]
- VSCode Version: October 2020 (version 1.51)
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. Open an existing or new file
2. File > Save As

Does nothing. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by entozoon** [comment]
It does occur in insiders.
The issue is seemingly intermittent - having exited the program and relaunched 4 or 5 times, it works again

**Comment by isidorn** [comment]
@entozoon Do you have a regular editor open or a custom editor? What are you trying to save?
Anyways forwarding to @bpasero

**Comment by entozoon** [comment]
Even just a brand new file. I've tried it with and without extensions, makes no difference.
It really want to give more info but there were no errors in problems or anything I could see, and like I said it resolves itself for a few days.
I wonder if it's a possibility that the problem lies with macOS? The file save dialog not initialising

**Comment by bpasero** [comment]
> I wonder if it's a possibility that the problem lies with macOS? The file save dialog not initialising

Yeah I would bet.
