### ISSUE TITLE
Keybindings for inputBoxes

### ISSUE THREAD

**Issue by strikerlulu** [microsoft/vscode#110057]
It's not possible to create keybindings(for editing) in inputBoxes other than the textEditor ?
I saw there is one for terminal like 
```
workbench.action.terminal.sendSequence
```
But how do we add unix like keybindings for the textInputBoxes ?
```
{
  "key": "ctrl+w",
  "command": "deleteWordLeft",
  "when": "inputFocus && !textInputFocus"
 },
 {
  "key": "ctrl+h",
  "command": "deleteLeft",
  "when": "inputFocus && !textInputFocus"
 },
```
Instead of deleting text in the editor i need it to be delete in the focused inputBox(like quickOpen,renameBox,etc...)

**Comment by alexdima** [comment]
Those inputs use simple HTML `<input>`s elements, and those do not support these commands.

**Comment by jrieken** [comment]
Unassigning myself since there is a separate issue for rename already
