### ISSUE TITLE
Breakpoints not hit in activate() method of extension when debugging

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#110013]
I raised this in the past (https://github.com/microsoft/vscode/issues/74525) and it turned out to be `outFiles` being set incorrectly, but I'm seeing it again today and I'm sure they're correct, and I can also repro using a `yo code` created extension.

- Create an extension with `yo code`
- Change activation events to `*`
- Add the following code in the activate method:
  ```
	console.log("Test!");
	setImmediate(() => {
		console.log("Test!");
	});
	setTimeout(() => {
		console.log("Test!");
	}, 50);
  ```
- Add breakpoints to all `console.log` lines
- Press `F5` to run

The first/only breakpoint to be hit is the one in the timeout:

<img width="676" alt="Screenshot 2020-11-05 at 11 30 51" src="https://user-images.githubusercontent.com/1078012/98235913-68c21680-1f5a-11eb-956b-d28ca622434c.png">

**Comment by connor4312** [comment]
This should be fixed already in VS Code Insiders and on the [nightly release](https://github.com/microsoft/vscode-js-debug#nightly-extension). If it repros there, can you grab logs?

/jsDebugLogs

**Comment by DanTup** [comment]
Yep, you're right - sorry for the noise!

**Comment by connor4312** [comment]
no worries, duplicate reports are better than unreported issues :)
