### ISSUE TITLE
Error Regex parser  INVALID SCAPE

### ISSUE THREAD

**Issue by matheuscamarques** [microsoft/vscode#110085]
` ("@@(\/?[a-zA-Z\\u00C0-\\u00FF záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ !@#$%¨&*()_+]+\"))`

I tested this regex in N validators and they all accept, except in vc code

Testei esse regex em N validadores e todos aceitam , execeto no vc code

**Comment by IllusionMH** [comment]
Reduced case is just `\"`

In your case you don't need to escape double quotes so current workaround is to remove escape for second `"`
`("@@(\/?[a-zA-Z\\u00C0-\\u00FF záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ !@#$%¨&*()_+]+\"))`

**Comment by IllusionMH** [comment]
On more detailed look this is correct error that comes from V8. VS Code uses Unicode flag for all regex searches which makes unnecessary escapes invalid.
You can try `/\"/u` in browser DevTools or check https://regex101.com/r/tq17Cr/1/

Looks like this one works as expected.

**Comment by matheuscamarques** [comment]
Obrigado , problema solucionado com as sugestões acima!
