### ISSUE TITLE
On web-based Codespaces, git.enableCommitSigning should be ignored

### ISSUE THREAD

**Issue by ItalyPaleAle** [microsoft/vscode#110041]
- VSCode Version: GitHub Codespaces
- OS Version: Browser (Edge 86 on macOS)

**Describe the bug**
My VS Code settings include `"git.enableCommitSigning": true` to enable signing commits with a GPG key. These settings are synchronized to Codespaces too.

Because of that, making a commit in Codespaces on the browser fails every time, as browser-based apps can't access the GPG socket. In the git output view, the error message is:

```
> git commit --quiet --allow-empty-message --file - -S
error: gpg failed to sign the data
```

**To Reproduce**
1. Use browser-based Codespaces
2. Enable `git.enableCommitSigning`
3. Try to make a Git commit
4. Commits always fail

**Expected behavior**
Because it's not possible for a browser-based app to communicate with a GPG agent, `git.enableCommitSigning` should be ignored when using Codespaces in the browser.

**Comment by joaomoreno** [comment]
Actually, I don't think this is right. I expect to still be able to sign in Codespaces. Please file an issue to Codespaces itself.
