### ISSUE TITLE
VSCode freezing

### ISSUE THREAD

**Issue by utkarsh0124** [microsoft/vscode#110063]
[Issue]( @url
![VSCode  freezed](https://user-images.githubusercontent.com/52751458/98335484-0d138e00-202b-11eb-96d1-f1a6f38ddd55.png)
) Type: <b>Bug</b>

Visual Studio is constantly freezing after few minutes of use. I don't know if it's the extension or not. It is showing 'The Window is no longer Responsive' message.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.25GB free)|
|Process Argv|--crash-reporter-id dc9dcb0b-d5fb-4494-9070-df0cecbf3b87|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.1
python|ms-|2020.10.332292344
cpptools|ms-|1.1.0

</details>

**Comment by eamodio** [comment]
Can you disable all extensions and see if you still experience the issue? And if not, I would suggest re-enabling them one by one to determine the culprit

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
