### ISSUE TITLE
Unknown configuration parameter for suggestStatusBar

### ISSUE THREAD

**Issue by Torvaldi** [microsoft/vscode#110081]
- VSCode Version: 1.51.0
- OS Version: Manjaro Linux Nibia (20.2)

Steps to Reproduce:

1. Add the configuration "editor.suggestStatusBar.enable" in the settings.json file of vscode

Does this issue occur when all extensions are disabled?: Yes

I saw the new "suggestStatusBar" parameter in the release notes file, but it is not recognized by VSCode : 
![image](https://user-images.githubusercontent.com/7703951/98367971-d3e11b00-2036-11eb-8b14-240f1196c7b6.png)

**Comment by lowpolysnow** [comment]
Probably the release notes are wrong.
I found a setting item.
`"editor.suggest.showStatusBar"`
values : `true` or `false`(default)

**Comment by Torvaldi** [comment]
> Probably the release notes are wrong.
> I found a setting item.
> `"editor.suggest.showStatusBar"`
> values : `true` or `false`(default)

You are right, It works now!

**Comment by jrieken** [comment]
Sorry, release notes had a bug...
