### ISSUE TITLE
Installation issue in Windows 7

### ISSUE THREAD

**Issue by jaswant100** [Microsoft/vscode#11000]
- VSCode Version:
- OS Version:
  ![error](https://cloud.githubusercontent.com/assets/4330430/17998357/872168dc-6b91-11e6-8afb-9db2a6b03dfb.png)

Steps to Reproduce:
1. https://code.visualstudio.com/Docs/?dv=win
2. running VSCodeSetup-stable
3. Iam using windows 7 service pack 1

**Comment by jaswant100** [comment]
VSCode Version:1.4
OS :windows 7

**Comment by joaomoreno** [comment]
Does it always happen? Even after restarting? Even after fully uninstalling?

**Comment by jaswant100** [comment]
iam installing it first time, it occur when i try to install VSCodeSetup-stable.exe, error comes even  after restarting windows.

**Comment by joaomoreno** [comment]
Didn't have more users filling this issue, so closing it.
