### ISSUE TITLE
Integrated terminal inserting ^[[D character hundreds of times.

### ISSUE THREAD

**Issue by Ranguna** [microsoft/vscode#110082]
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-15T10:42:48.064Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.3-arch1-1
**Terminal Emulator: Termite** <-- I haven't tested with another emulator, but maybe the problem is with this one specifically.

Steps to Reproduce:

1. Open the integrated console.
2. Run a script that echos a link (tested with file and http links) and sleeps for a few seconds.
3. Press the link before the script finishes.
3. Lots of ^[[D (left press) characters start poping up.

Here's an example script, I managed to reproduce this issue by pressing the link before the script completes the `sleep` command.
```sh
#!/bin/sh

echo "https://github.com/microsoft/vscode/issues/110082"
sleep 5
```

Does this issue occur when all extensions are disabled: Yes.

If there were no recent changed to vscode (+/- one month) related with the integrated terminal (such as this old issue  #19766), then I will close this since it's possibly a problem on my machine. 
Here's a screenshot:
![image](https://user-images.githubusercontent.com/5003755/98367999-7ba61b00-202e-11eb-84dd-6b16a72374c6.png)

**Comment by Tzlz** [comment]
，，，，

Luis Pais <notifications@github.com> 于 2020年11月6日周五 下午8:53写道：

**Comment by Ranguna** [comment]
I found a way to always reproduce this, even with extension disabled. Apparently it happens when I click a link (file or http link, I haven't tested with other types) that appears in the integrated terminal while a script is running.

Here's an example script:
```sh
#|/bin/sh

echo "https://github.com/microsoft/vscode/issues/110082"
sleep 5
```

If I run this script from the integrated terminal and press that link before the `sleep` command finished, I get a few `^[[D`s in the terminal:
![image](https://user-images.githubusercontent.com/5003755/98531884-dd59c580-2278-11eb-90a0-f8d599ffc4c7.png)

I'll update the original description with this info.
