### ISSUE TITLE
Breadcrumbs: cannot click twistie to expand

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#110012]
Works using keyboard but not mouse. I think when I explicitly click on the twistie we should expand and not open.

![recording (3)](https://user-images.githubusercontent.com/900690/98235349-f8b78e80-1f61-11eb-8910-d6094e9b6b7c.gif)

**Comment by jrieken** [comment]
Works for me. @bpasero is that insiders or from master?

**Comment by bpasero** [comment]
@jrieken yeah was running out of sources from `master`

**Comment by jrieken** [comment]
@joaomoreno I do recall you having demoed some twisty changes. Do it be causing this?

**Comment by jrieken** [comment]
I cannot reproduce. @bpasero can you?

**Comment by joaomoreno** [comment]
I can repro, this might be me! Investigating...

**Comment by bpasero** [comment]
Looks like it needs only 1 element to reproduce:

![Kapture 2020-11-09 at 11 09 38](https://user-images.githubusercontent.com/900690/98528089-1d6e7780-227c-11eb-88c9-78652cf69ef7.gif)
