### ISSUE TITLE
Unable to find Microsoft Edge on Ubuntu

### ISSUE THREAD

**Issue by MakiWolf** [microsoft/vscode#110099]
- VSCode Version: 1.51.0
- OS Version: Ubuntu 20.10

Steps to Reproduce:

![grafik](https://user-images.githubusercontent.com/73300633/98400034-aa8ab400-2063-11eb-94e5-db44569eaa78.png)
![grafik](https://user-images.githubusercontent.com/73300633/98399995-96df4d80-2063-11eb-8036-eaec1192d7e8.png)

Can't find the new Developer preview from Microsoft Edge (Version 88.0.685.3) on Ubuntu 20.10
VS Code (Web) does work, because it will be opened in Firefox

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by eamodio** [comment]
That `launch.json` config is setup to launch the stable version of Edge.  You can change it using the `runtimeExecutable` option: 
https://github.com/microsoft/vscode-js-debug/blob/master/OPTIONS.md#runtimeexecutable-3
