### ISSUE TITLE
Typescript module augmentation works only while file its live in remains open

### ISSUE THREAD

**Issue by carljohnesan** [microsoft/vscode#110027]
- VSCode Version: 1.50.1
- OS Version: osx 10.13.6

Steps to Reproduce:

1. install `fs-extra` and `@types/fs-extra`
2. create "src/tests" directory
3. create "src/tests/foo.ts" with contents:
```ts
declare module 'fs-extra' {
  var __foo__: string
}
```
and don't close tab with this file
4. create "src/tests/test.ts" file with contents:
```ts
import { __foo__ } from 'fs-extra'
```
You'll see it works.
4. Close "foo.ts" tab, You'll see now `import { __foo__ } from 'fs-extra'` gives following error:
"Module '"../../node_modules/@types/fs-extra"' has no exported member '__foo__'."

Does this issue occur when all extensions are disabled? Yes

![2020-11-05 16 37 34](https://user-images.githubusercontent.com/47556468/98258331-6925d600-1f89-11eb-9ea8-dcfdbabd673e.gif)

**Comment by mjbvz** [comment]
Please share your `tsconfig` too

**Comment by carljohnesan** [comment]
It's actually empty - `{}`

**Comment by carljohnesan** [comment]
Also this bug only occurs with `tests` or `__tests__` directories, creating module augmentations in other directories just overwrites node module declaration

**Comment by carljohnesan** [comment]
Initially I wanted to create declarations for mock modules for tests written in typescript. Could you advice me something while bug not solved? Maybe I don't understand something about type declarations.

**Comment by mjbvz** [comment]
What if you create a valid `tsconfig`?

**Comment by carljohnesan** [comment]
It's valid. I asked you an advice

**Comment by carljohnesan** [comment]
Does reproduction works for you?

**Comment by mjbvz** [comment]
This is very likely a configuration issue with your project. Please share a small example project

**Comment by carljohnesan** [comment]
Solved, I removed "\_\_tests\_\_" from "exclude"
