### ISSUE TITLE
Use Sogou appear two Chinese characters

### ISSUE THREAD

**Issue by minjunlan** [Microsoft/vscode#11002]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
![image](https://cloud.githubusercontent.com/assets/7425981/17998604/df52fac8-6ba7-11e6-9213-54a22ede3376.png)

2. press space key

3. 
![image](https://cloud.githubusercontent.com/assets/7425981/17998678/348f1c56-6ba8-11e6-8e29-b58d3fdf9c36.png)

4. Repeated Chinese characters

**Comment by alexandrudima** [comment]
@minjunlan  What precise version are you on? Can you please share a screenshot of the Help > About?

Here is an example of what I mean:
![image](https://cloud.githubusercontent.com/assets/5047891/18009861/4abbc424-6bae-11e6-8c76-26af7230d678.png)

**Comment by alexandrudima** [comment]
Dup of #10937
