### ISSUE TITLE
Support git-cmd.exe as git bash shell type in Windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#110098]
Context: https://github.com/microsoft/vscode-docs/pull/4066

Repro:

On windows create a keybinding with a `when` clause of `terminalShellType == 'gitbash'` and make sure it works when you set git bash as the default shell using the instructions added in https://github.com/microsoft/vscode-docs/pull/4066

**Comment by karlhorky** [comment]
Thanks @Tyriar ! Am I correct in my assumption that this will show up in the January 2021 stable release (probably in Feb / Mar 2021)?

**Comment by Tyriar** [comment]
@karlhorky yes this won't work until early the stable release that goes out in early Feb. Note that all this really does though is allows you to create git bash-specific keybindings using `"when": "terminalShellType == 'gitbash'"`
