### ISSUE TITLE
Data breakpoints are not showing up in Breakpoints view

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#110077]
VS Code 1.51 (Stable)

- git clone Mock Debug
- F5
- start debugging
- in the Variables view expand the "global" scope
- select "global_i"  and from the context menu and run "Break When Value Changes"

Observe:
No data breakpoint shows up in the Breakpoints view

**Comment by isidorn** [comment]
Good catch. I have pushed a fix for this.
If you would like feel free to add a candidate label, though this was broken for a couple of stable releases.
