### ISSUE TITLE
Add more spacing in SCM trees between indent guides and icons

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode#110092]
- VSCode Version: 1.51
- OS Version: Windows 10 (19.09?)

![image](https://user-images.githubusercontent.com/11936772/98388824-d59be600-2018-11eb-9ee1-0774631150b1.png)

Steps to Reproduce:

1. Open a git repo
2. Make changes
3. Set `"workbench.tree.renderIndentGuides": "always"` in settings.json
4. Notice how lines overlap or are close to overlapping with icons

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Yeah unfortunately we're closing this as designed. The real indentation to follow is the text indentation. The current default of 8px means that the indent guide might collide with icons. There are a few workarounds: increase indentation via setting and disable icons. Sorry about that!

**Comment by tristan957** [comment]
Thanks @joaomoreno
