### ISSUE TITLE
We did not find `node` on your PATH, so we cannot enable auto-attach in your environment

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#110075]
- VSCode Version: 1.52.0-insider 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b x64

- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Open VSCode
2. It shows an error message `We did not find `node` on your PATH, so we cannot enable auto-attach in your environment`

![node](https://user-images.githubusercontent.com/23744935/98361377-b65a8400-202b-11eb-84a4-e1df67af87ff.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
If you do not want to use auto attach, you can remove "debug.javascript.autoAttachFilter" from your user settings (or use the command `Debug: Toggle Auto Attach`).

If you want to use auto attach, make sure Node.js is installed and in your PATH so that VS Code can find it.
