### ISSUE TITLE
Highlighting the current selection in multiple editors

### ISSUE THREAD

**Issue by mindrones** [microsoft/vscode#110032]
I recently switched from Atom and I'm finding it difficult not being able to highlight occurrencies in multiple editors/tabs.

In Atom I can do this with https://atom.io/packages/highlight-selected:

<img width="1378" alt="Screenshot 2020-11-05 at 17 03 21" src="https://user-images.githubusercontent.com/1309648/98273051-bbff8d80-1f89-11eb-801c-2bd297187f83.png">

In Code, with the setting `Selection Highlight` enabled, it works only in the current tab, forcing you to look for occurrences in other tabs visually, which isn't ideal:

<img width="441" alt="Screenshot 2020-11-05 at 17 40 58" src="https://user-images.githubusercontent.com/1309648/98276597-18fd4280-1f8e-11eb-8c14-f0a45809f641.png">

<img width="1021" alt="Screenshot 2020-11-05 at 17 15 49" src="https://user-images.githubusercontent.com/1309648/98273979-ca9a7480-1f8a-11eb-9d69-9091ea2554b9.png">

If we had a selection in other tabs before selecting something in the current tab, it actually keeps the selection in the previous tab highlighted, making visual searching even more difficult if we hadn't previously selected the same text:

<img width="1017" alt="Screenshot 2020-11-05 at 17 16 02" src="https://user-images.githubusercontent.com/1309648/98273863-ab034c00-1f8a-11eb-9eeb-3b26108226c2.png">

I tried a multitude of Code addons, with no luck; [`highlight-selections-vscode`](https://github.com/cliffordfajardo/highlight-selections-vscode#multi-tab-support) seemed promising but it's glitchy

<img width="777" alt="Screenshot 2020-11-05 at 17 06 47" src="https://user-images.githubusercontent.com/1309648/98272788-62975e80-1f89-11eb-9285-fe630f73da1b.png">

I might just have filed this issue in the `highlight-selections-vscode` repo but I think this is such a fundamental feature that it should be available natively in Code to make sure it gets properly maintained.

Would it be possible to implement this internally?

Thanks!

**Comment by ArturoDent** [comment]
This was recently asked and closed: see https://github.com/microsoft/vscode/issues/104659
