### ISSUE TITLE
99

### ISSUE THREAD

**Issue by weiyi-li00** [microsoft/vscode#110084]
Issue Type: <b>Bug</b>

這是測試

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
canvas-snippets|hol|0.3.2
vue-snippets|hol|0.1.12
beautify|Hoo|1.5.0
git-graph|mhu|1.27.0
vsliveshare|ms-|1.0.3121
indent-rainbow|ode|7.4.0
git-file-history|pom|1.0.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
snippet|vsc|0.8.1
snippet|ysf|0.2.0

</details>

**Comment by rzhao271** [comment]
Closing because OP is just testing how filing issues works.
Translation: "this is a test".
