### ISSUE TITLE
Remove 'insiders builds are becoming daily builds' message on startup

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11004]
1. Download an insiders vscode on a fresh machine
2. Notice the message on startup 'insiders builds are becoming daily builds'
3. This message is stale and this should be communicated on our web site, no need to spam the user

**Comment by waderyan** [comment]
What do you think about this [change](https://github.com/Microsoft/vscode/pull/13028)?

"Insider builds and releases everyday!"

**Comment by isidorn** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/13028
