### ISSUE TITLE
Fails to detach from Command Prompt

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#110030]
- VSCode Version: 1.50.1
- OS Version: Windows 10

Steps to Reproduce:

1. Launch Command Prompt.
2. Call `code`.
3. Call `exit`.

Instead of exiting the Command Prompt, the Command Prompt stalls indefinitely. It waits for VSCode to terminate, which is not the expected behavior. Especially as the terminal does receive commands while VSCode is running.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
If you are using `code` script then you have to set `ELECTRON_NO_ATTACH_CONSOLE` environment variable to avoid the prompt. Instead you can use the `code.cmd` wrapper.
