### ISSUE TITLE
Integrated terminal hangs whole window if big strings are printed in one go

### ISSUE THREAD

**Issue by jalaj-k** [microsoft/vscode#110070]
- VSCode Version:
```
$ code --version
1.50.1
d2e414d9e4239a252d1ab117bd7067f125afd80a
x64
```
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Open integrated terminal
2. Give it a command to print a long enough string.
3. It will hang midway.

Does this issue occur when all extensions are disabled?: Yes

So, I have a program which I wanted to test and so I made it print out some data to the terminal. Apparantly, it was 40kB worth of base64 encoded data. But the task never got completed because vscode window hanged midway. I tried it several times ( Even with extensions disabled and closing _all_ other background apps). The same thing works just fine in a normal terminal.

**Screenshots**

With Extensions:
![Screenshot from 2020-11-06 16-07-56](https://user-images.githubusercontent.com/67556827/98358002-0fd2ab00-204c-11eb-95e5-8356333382f4.png)

Extensions disabled:
![Screenshot from 2020-11-06 16-13-23](https://user-images.githubusercontent.com/67556827/98358284-748e0580-204c-11eb-850b-44631627aec4.png)

Ok, I understand that its a rare use case but I don't think it was supposed to go this way.

**Comment by Tyriar** [comment]
/duplicate https://github.com/xtermjs/xterm.js/issues/1515 https://github.com/microsoft/vscode/issues/108317
