### ISSUE TITLE
More Intelligent IntelliSense

### ISSUE THREAD

**Issue by kenkopelson** [microsoft/vscode#110008]
I would like IntelliSense to be more geared to editing existing code, in addition to adding new code.  Right now, it is only geared to adding new code.  Here is an example of what I mean:

1) Let's say we have a method defined with 3 parameters.  Let's also say that I have an existing method call of that same method, with 3 values corresponding to those 3 parameters.  Let's say I erase the middle (2nd) parameter so that the code looks like this:
       someFunction(345,<cursor is here>,"test");
With the cursor at the position indicated, at the spot where the 2nd parameter should go, I would like to see the IntelliSense show the following:    Parameter: String name

If all parameters are present in the method call, then no IntelliSense help would be shown.

2) Basically, IntelliSense should not show any help box unless there is no code at all in the spot where the cursor is, or the code that is there is different from what is already there.  When I say there is no code there at all, I mean that the statement is incomplete to the right of the cursor.

**Comment by jrieken** [comment]
Ok, lets start with the language you are using and the extension that is providing the smarts. A real code snippet would help be helpful
