### ISSUE TITLE
What should I do to put menubar in titlebarPart instead of activitybarPart?

### ISSUE THREAD

**Issue by DengJianShen** [microsoft/vscode#110056]
- VSCode Version: 1.50.1

vscode/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts
vscode/src/vs/workbench/browser/parts/activitybar/activitybarPart.ts

What should I do to put menubar in titlebarPart instead of activitybarPart?

**Comment by sbatten** [comment]
```
"window.menuBarVisibility": "default"
```
