### ISSUE TITLE
Use case-insensitive to filter files in search panel in windows plataform

### ISSUE THREAD

**Issue by felipekmr** [microsoft/vscode#110019]
The Windows platform use case-insensitive system files, then it would be better to filter the files regardless of whether the files are in upper or lower case in search panel.
 
Maybe the best solution will be include the 'Match case' option in 'files to include' field. Seems more simplest for me and a platform indenpendent solution.

![image](https://user-images.githubusercontent.com/936313/98248797-301f3e80-1f54-11eb-9140-4b1b4cca9615.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/10633
