### ISSUE TITLE
Intellisense window is compressed into an unreadable state on fresh install of VSCode..

### ISSUE THREAD

**Issue by drwebman** [microsoft/vscode#110078]
- VSCode Version: 1.51.0
- OS Version: Darwin x64 19.4.0

Steps to Reproduce:

1. Install VSCode
2. Type some code, observe Intellisense

Does this issue occur when all extensions are disabled?: Yes
<img width="607" alt="Screenshot 2020-11-06 at 11 59 41" src="https://user-images.githubusercontent.com/6297784/98365891-ff5e0880-202a-11eb-8dd8-8ae19edac395.png">

**Comment by jrieken** [comment]
Do you have this setting configured: `editor.suggestFontSize`? Can you select "F1 > Reset Suggest Widget Size" and try again?

**Comment by prayjourney** [comment]
> Do you have this setting configured: `editor.suggestFontSize`? Can you select "F1 > Reset Suggest Widget Size" and try again?

Thanks, Sloved!

**Comment by jrieken** [comment]
@prayjourney one more question. Do you have any suggestion font settings configured? Please check for `editor.suggestFontSize` or `editor.suggestLineHeight`

**Comment by prayjourney** [comment]
> @prayjourney one more question. Do you have any suggestion font settings configured? Please check for `editor.suggestFontSize` or `editor.suggestLineHeight`

now I use default configuration, I tried `"editor.suggestLineHeight": 20`  and it was normal too. Using the default is pretty good.

**Comment by prayjourney** [comment]
> @prayjourney one more question. Do you have any suggestion font settings configured? Please check for `editor.suggestFontSize` or `editor.suggestLineHeight`

@jrieken now I use default configuration, I tried `"editor.suggestLineHeight": 20` and it was normal too. Using the default is pretty good.

**Comment by jrieken** [comment]
Ok. Thanks for clarifying. I keep wondering how this could have happened since the minimum height of the suggest widget is line line - so 20px in your case and it should never be smaller than that

**Comment by prayjourney** [comment]
@jrieken okay, You may know more clearly by looking at the picture😅😅😅
![2020-11-16_171059](https://user-images.githubusercontent.com/15311937/99234262-461fdf80-282f-11eb-8c9a-7e35401bc992.png)

**Comment by jrieken** [comment]
Yeah, that's not good... Let me push a change that sets a lower bound on the suggest widget line height

**Comment by jrieken** [comment]
Closing - the suggest line height is now clamp between 8 and 1000, similar to the editor line height
