### ISSUE TITLE
Add option to hide git commit box

### ISSUE THREAD

**Issue by Yuuki77** [microsoft/vscode#110088]
I want an option not to show the git commit box.

I want this feature because when I use `workbench.scm.focus`, it focus the commit box not changes files.
it.
or is there a shortcut to focus changes files? 🤔 

![image](https://user-images.githubusercontent.com/18569016/98385408-49c6a000-2092-11eb-89af-477534b9f4a7.png)

**Comment by preetamm** [comment]
Heyy I am a first-time contributor, I would love to work on this.

**Comment by joaomoreno** [comment]
The setting is `git.showCommitInput`

**Comment by Yuuki77** [comment]
Thanks This is exactly what I was looking for 😄
