### ISSUE TITLE
Breakpoints not hit in NodeJS project on MacOS

### ISSUE THREAD

**Issue by maartenjanson** [microsoft/vscode#110043]
Problem: Breakpoints are not hit, the same project works on Win 10. 
The NodeJS code does run and outputs in the internal console
even though I have trace:true I see no trace files being generated

System:
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

launch.json{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/app.js",
            "console": "integratedTerminal",
            "trace": true
        }
    ]
}

console output:
sh-3.2#  /usr/bin/env 'NODE_OPTIONS=--require /tmp/vscode-js-debug-bootloader.js' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.13531-5.sock","deferredMode":false,"waitForDebugger":"","execPath":"/usr/local/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/tmp/node-debug-callback-b5a71c8b7561782b"}' /usr/local/bin/node ./app.js 
Debugger listening on ws://127.0.0.1:60512/78d6b0f1-1a97-4bf2-b019-f84c3bf38c09
For help see https://nodejs.org/en/docs/inspector

**Comment by connor4312** [comment]
/jsDebugLogs

Note that the path is will printed to the Debug Console view, **not** the terminal

**Comment by maartenjanson** [comment]
Thank you for your help, please find attached the latest log file.
[vscode-debugadapter-5.json.gz](https://github.com/microsoft/vscode/files/5503147/vscode-debugadapter-5.json.gz)

**Comment by connor4312** [comment]
Thanks for the logs. It looks like you're on an end-of-life version of Node.js. Can you try updating to a more recent version (14 is the latest stable version) and seeing if that fixes the issue for you?

**Comment by Spottus** [comment]
i have the same issue , Thank you for your help
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/5512234/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment]
You have a different issue.

It looks like everything is fine in your setup, but Node.js doesn't bind the breakpoints where you set them. Make sure they're set on statements / locations that can be paused upon.

**Comment by maartenjanson** [comment]
Many Thanks Conor, updating Node.js seems to have done the trick!
