### ISSUE TITLE
Add API to disambiguate "deactivate()" function in extension.ts

### ISSUE THREAD

**Issue by bchuecos** [microsoft/vscode#110034]
We have an extension for VS Code and need to delete the current workspace file upon deactivation of the extension, but only in cases where the VS Code instance is being closed by the user, as doing so during a user-triggered or extension-triggered reload can mess up VS Code's workspace management logic. It would be really helpful if we had a way to disambiguate what's triggering the deactivate() function in extension.ts, like say, a reload vs the instance being closed.

**Comment by alexdima** [comment]
I think it would be best to create an issue about the workspace management logic bug you are hitting.

IMHO working around a bug is not a good reason for adding API.

Also IMHO deleting workspace files on deactivation sounds very very fishy, so maybe there's something else missing there, like an "in-memory" workspace file.

fyi @bpasero

**Comment by bchuecos** [comment]
@alexdima there's a bit more than just the workspace bug. We need to be able to delete the workspace only in cases where the extension is being deactivated due to the VS Code instance closing. This is because the expected behavior is that the workspace should not be reopened when the user closes their instance and opens it again, but it should be reopened if there is a user-triggered or extension-triggered reload. We can only do this if we know the reason for deactivation.
