### ISSUE TITLE
Program language is reset to English after update

### ISSUE THREAD

**Issue by pvsNiceDo** [microsoft/vscode#110080]
Issue Type: <b>Bug</b>

After updating the program, the interface language is reset to English (although it was Russian).

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

**Comment by esmultivac** [comment]
Same here. My language was Spanish and was reset to English after update.

**Comment by dbaeumer** [comment]
I tried to reproduce this with German but wasn't able to do so.

@esmultivac @pvsNiceDo are you able to switch th UI back to the original language or are you stuck with English now?

**Comment by esmultivac** [comment]
I'm back to Spanish and the new update (1.5.1.1) didn't revert to English again.

**Comment by dbaeumer** [comment]
@esmultivac thanks for letting me know.

**Comment by dbaeumer** [comment]
Might be related to https://github.com/microsoft/vscode/issues/75241

**Comment by pvsNiceDo** [comment]
I'm back ti Russian too.
