### ISSUE TITLE
Some extensions are disabled on WSL Remote and can't be enabled.

### ISSUE THREAD

**Issue by nparoski** [microsoft/vscode#110140]
Issue Type: <b>Bug</b>

I've installed Ruby and VSCode Ruby extension on my local (windows) vscode, but when i run VSCode on remote VSCode Ruby extension is "Enabled locally and disabled on WSL" even though i haven't disabled it.
On the othe hand Ruby extension is running fine and i didn't need to enable it anywhere.
Also this happens when i install Rails extension, Rails extension is enabled on Remote but Slim is disabled.

I've tried uninstalling extensions locally and on remote and installing again on Remote but the end result is the same.
Also i tried uninstalling them on Remote and localy and then installing on Remote but still same result.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.26GB free)|
|Process Argv|. --crash-reporter-id 9f62f1a9-5c3c-4c3c-b417-c6b93a6d45cd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|12.37GB (9.66GB free)|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
es7-react-js-snippets|dsz|3.0.0
yarn-lock-syntax|mar|0.1.3
remote-wsl|ms-|0.50.1
material-icon-theme|PKi|4.4.0
slim|sia|0.1.2
vsc-php-snippets|vsc|0.0.30
vscode-ruby|win|0.27.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.9.3
vscode-mjml|att|1.6.0
vagrant|bbe|0.5.0
markdown-preview-github-styles|bie|0.1.6
vscode-intelephense-client|bme|1.5.4
rails|bun|0.16.7
vscode-gemfile|bun|0.4.0
gitlens|eam|10.2.3
prettier-vscode|esb|5.7.1
php-debug|fel|1.13.0
php-pack|fel|1.0.2
todo-tree|Gru|0.0.186
git-graph|mhu|1.27.0
python|ms-|2020.10.332292344
ruby|reb|0.27.0
LiveServer|rit|5.6.1
todotasks|san|0.5.0
slim|sia|0.1.2
vscode-ruby|win|0.27.0

</details>

**Comment by sandy081** [comment]
When an extension is installed both locally and remotely, we enable this extension only on one side and disable it to run on other side. The decision of on which side to run is taken using `extensionKind` property defined by the extension. Please check following docs for more info

https://code.visualstudio.com/docs/remote/wsl#_can-i-force-an-extension-to-run-locally-remotely-
https://code.visualstudio.com/api/references/vscode-api
