### ISSUE TITLE
Settings filter is reset automatically

### ISSUE THREAD

**Issue by yzhang-gh** [microsoft/vscode#110139]
- VSCode Version: 1.51.0 (user setup)
- OS Version: Windows 10

Steps to Reproduce:

![settings](https://user-images.githubusercontent.com/7588612/98440801-cced0200-2135-11eb-8fea-7398ff789aa0.gif)

1. Type something in the input box
2. Click on an item in the sidebar
3. See settings filtered
4. Wait for a while (don't need to do anything), and see the filter results being reset

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Fixed in https://github.com/microsoft/vscode/issues/109860
