### ISSUE TITLE
VSCode freezing on Integrated Terminal close

### ISSUE THREAD

**Issue by MiguelMachado-dev** [microsoft/vscode#110110]
- VSCode Version: 1.51.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open integrated terminal
2. Run project `npm run dev`
3. When I stop the script and close the integrated terminal, vscode freezes and popup a dialog asking to reopen, wait or close

I noticed this after getting a 4K monitor, I don't know if this is related.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
What terminal are you using: powershell, cmd, something else?

**Comment by MiguelMachado-dev** [comment]
> What terminal are you using: powershell, cmd, something else? 

powershell 7
