### ISSUE TITLE
New update is not working

### ISSUE THREAD

**Issue by Shoban-Chiddarth** [microsoft/vscode#110180]
Issue Type: <b>Bug</b>

Hover/Bring the cursor to the text(instead of erasing it and typing it again)(new update) in .css file is not working

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (3.52GB free)|
|Process Argv|--crash-reporter-id a07bb4c3-1052-4dc1-aa04-793782e9dca3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
stories|ben|2.20.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.13
prettier-vscode|esb|5.7.1
auto-rename-tag|for|0.1.5
beautify|Hoo|1.5.0
google-search|kam|0.0.1
vscode-docker|ms-|1.7.0
python|ms-|2020.10.332292344
vsliveshare|ms-|1.0.3121
debugger-for-chrome|msj|4.12.11
LiveServer|rit|5.6.1
vscode-todo-highlight|way|1.0.4

</details>

**Comment by aeschli** [comment]
Can you provide more detailed steps with screenshots or a screen-cast?

**Comment by Shoban-Chiddarth** [comment]
Here is the [recording](https://www.loom.com/share/ee0435ed01204f29b76f1e0bffa74d56)
I read that I can change the properties if I just hover my mouse or cursor. But I had to erase and again type.

**Comment by Shoban-Chiddarth** [comment]
[Another Recording on the same issue](https://www.loom.com/share/781978be7f374a4796d7698c41ae34a9)

**Comment by aeschli** [comment]
![](https://code.visualstudio.com/assets/updates/1_51/suggest-left.gif)

I think you misunderstood the feature. This is about when code completion is open (Ctrl +Space) you can move the cursor to the left and will see additional proposals.
