### ISSUE TITLE
add an item “add to extension recommend to workspace” to extension menu

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#110121]
hi， in order to add an recommend extension to workspace，we recommend that adding an item “add to extension recommend to workspace” to extension menu，thanks
![image](https://user-images.githubusercontent.com/1876302/98430795-43b0dd80-20eb-11eb-9fc9-3d02453e35af.png)

**Comment by sandy081** [comment]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/10746682/98553606-13f70680-22a0-11eb-8ac9-fa46562508be.png">

**Comment by sandy081** [comment]
/duplicate 

https://github.com/microsoft/vscode/issues/68702
