### ISSUE TITLE
Enable findregex in settings.json

### ISSUE THREAD

**Issue by erf** [microsoft/vscode#110134]
I would like an option in `settings.json` to enable `findregex: true`.

This can now be toggled in keymaps ( `alt+cmd+r` to toggle `toggleFindRegex` ), but i would like it as an option in settings so  i don't have to toggle it, but can save it in my "dotfiles" project.

**Comment by roblourens** [comment]
Once you have turned it on in a workspace, that should be remembered. But I don't want to add an option to always have it turned on.
