### ISSUE TITLE
Support committing the selected completion item with keys like `(`

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#11016]
In Visual Studio, pressing an open paren `(` will commit the selected item in the completion list.

eg.:

```dart
funcA() {
}

funcB() {
  func
}
```

With the cursor after the `c` on the last line and the completion list having `funcA` selected, pressing `ENTER` will complete the item. However pressing `(` will not, it will just result in `func(`.

It would be really nice if when you register a completion item provider you can provide characters that will also commit the selection (I think it should complete and then still insert the character after the completion).

(Edit: maybe it should be a Code user-option, not a language-specific thing?)

**Comment by DanTup** [comment]
There are a couple of mentions of things that might be related (like https://github.com/Microsoft/vscode/issues/6237) but if this is already supported, I can't figure out where I'm supposed to configure it?

**Comment by jrieken** [comment]
Your extension can do that by defining a keybinding. Take our TypeScript extension as a sample: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/package.json#L204

```
"key": ".",
"command": "^acceptSelectedSuggestion",
"when": "editorTextFocus && suggestWidgetVisible && editorLangId == 'typescript' && suggestionSupportsAcceptOnKey"
```

Note the `^` in front of the command id, which mean *insert character AND run command*

**Comment by DanTup** [comment]
@jrieken Great! Though I don't seem to be able to get it to work; I've got this:

```
"keybindings": [
			{
				"key": "(",
				"command": "^acceptSelectedSuggestion",
				"when": "editorTextFocus && suggestWidgetVisible && editorLangId == 'dart' && suggestionSupportsAcceptOnKey"
			},
			{
				"command": "dart.organizeDirectives",
				"key": "ctrl+alt+o",
				"mac": "cmd+alt+o",
				"when": "editorLangId == dart"
			}
		],
```

Unlike your example, we have two keybindings, so this is an array instead of a single object. My guess is that it's related to `suggestionSupportsAcceptOnKey` but I can't see whether I need to do something to say I support this, I can't find anything about this in the docs :(

I've got `prin` and the completion window open (and `print` selected) when I type `(` and I just end up with `prin(`.

(I'm using 1.4 stable if that matters)

**Comment by DanTup** [comment]
@jrieken Same in insiders, this doesn't seem to work (see above comment). I presume the issue is `suggestionSupportsAcceptOnKey` but I can't find anything on it in the docs, nor by searching GitHub :(
