### ISSUE TITLE
After Control Tab from one Jupyter notebook to a second  Can't Control Tab again

### ISSUE THREAD

**Issue by tmozun** [microsoft/vscode#110157]
- VSCode Version: 1.51.0
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. Open two Jupyter notebooks that contain multiple cells.
2. Click in a cell in one of the notebooks.
3. Control + Tab to the next notebook. BUT DON'T CLICK ANYWHERE. 
4. Release Control and Tab keys.
5. Try Control + Tab again to navigate back to the first notebook. It doesn't work.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
We now moved the notebook editor impl into the core, you would not see this issue anymore.
