### ISSUE TITLE
Hearing a bell sound while moving editor to another editor window

### ISSUE THREAD

**Issue by rvadaga** [microsoft/vscode#110124]
- VSCode Version: 1.51.0
- OS Version: macOS Catalina 10.15.7

As mentioned in the title, I hear a bell sound whenever I move editor between editor groups (by using keyboard shortcuts). I've seen people complain about this elsewhere, and the threads are either locked here on GitHub, or no one seems to have an answer [see [issue #46149](https://github.com/microsoft/vscode/issues/46149), comment right below this [SO answer](https://stackoverflow.com/a/44018640/3187043)].

Steps to Reproduce:

1. Open a VS Code window, and set appearance to 2 columns 
2. Open multiple files in each editor group.
3. Select any editor within an editor group, move editor to pre/next editor group using ctd-cmd-left/ctrl-cmd-right.

Does this issue occur when all extensions are disabled? - Yes

**Comment by bpasero** [comment]
I don't think VSCode can change something to prevent this bell from happening, could be some other app or could be electron. Leaving it to @deepak1556 if he maybe heard about this, otherwise will close in 7 days.
