### ISSUE TITLE
Settings editor: commonly used configuration not strict

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#110129]
Notice how `files.autoSave` is configured to be a commonly used setting, but `files.autoSaveDelay` also appears:

![image](https://user-images.githubusercontent.com/900690/98434489-80231000-20d0-11eb-94d4-7788c5aff6cc.png)

Since I am about to add `workbench.editor.enablePreview`, I noticed that `workbench.editor.enablePreviewFromQuickopen` was also appearing.

**Comment by JacksonKearl** [comment]
cc @RyanCavanaugh Settings Editor Total Landscaping?

 ([reference](https://twitter.com/SeaRyanC/status/1325593701343621120))
