### ISSUE TITLE
It should be possible to lookup global symbols without openning an editor

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/vscode#11014]

**Comment by sandy081** [comment]
@akosyakov There is a command to see all symbols without opening any editor - `Show All Symbols`

**Comment by akosyakov** [comment]
@sandy081 it does not show anything with a closed editor.

**Comment by sandy081** [comment]
@akosyakov Yes you are right.

**Comment by jrieken** [comment]
That's a matter of [activation events](https://code.visualstudio.com/docs/extensionAPI/activation-events). By default extension register when one of their files opens but can activate also eager or on commend execution. @akosyakov Please file a request against the extension you are excepting this to work with

**Comment by akosyakov** [comment]
@jrieken if i would like to file for typescript extension, should it be filed against this repo?

**Comment by jrieken** [comment]
In theory yes, but the TypeScript server is written in such a way that it *always* needs to know at least one file. Already today we depend on [tricks](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/workspaceSymbolProvider.ts#L35)... So, in this specific case it's sort of an upstream issue in the TypeScript lang

**Comment by akosyakov** [comment]
@jrieken just not really smooth UX, when you first have to look for a typescript file, would be nice if you can just type a symbol name
