### ISSUE TITLE
[Feature Request] source control: unbold repositories that don't have changes

### ISSUE THREAD

**Issue by dorsany** [microsoft/vscode#110142]
I think that it will be much more convenient for the end user the get a list of repositories under the **source control**  made `unbold` as default, and repositories with changes will be made `bold`.

This will ease the end user to find repositories with changes much more quickly and the style of the repositories will be more informative.

![image](https://user-images.githubusercontent.com/36127093/98444047-22b2b180-2118-11eb-9fed-25f7f7f62a80.png)

**Comment by joaomoreno** [comment]
We won't change the rendering of the repositories. But since you have so many, right click the Source Control view and show the Source Control Repositories view. Then select one. This view will make your life better.
