### ISSUE TITLE
Local echo is making remote Vim hard to use

### ISSUE THREAD

**Issue by XsongyangX** [microsoft/vscode#110109]
The recently release local feature is nice to use on ssh terminals. But when editing files on the remote server with Vim, the cursor flickers around and seeing the edit of the text in real time becomes difficult. It would be nice if the local echoing is disabled when doing Vim and things similar to it.

Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Connect to a remote ssh server with a slight latency (ping=100ms)
2. Launch the file editor Vim on an existing file.
3. Try to type and edit the file

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
@connor4312 do we not switch off local echo when the alt buffer is active currently? I don't see `Terminal.buffer.onBufferChange` getting used so that's probably the easy fix here.

**Comment by connor4312** [comment]
We do, but on Windows/through powershell Vim doesn't seem to use the alternate buffer. Maybe there's another heuristic we can use to detect it though

**Comment by Tyriar** [comment]
Maybe using `ITerminalService.onInstanceTitleChanged` and disable it for vim/tmux/vi/etc. as a workaround? More specifically we'd want process title since the title also would include renaming the terminal, but there isn't an event for this currently.

**Comment by connor4312** [comment]
It looks like that doesn't work on git bash or through running `bash` in an existing powershell instance, because the terminal title change doesn't fire there. But it works on vim installed in windows via choco, so it's an improvement. I'll add it.
