### ISSUE TITLE
executeCompletionItemProvider command can't get resolve result when set itemResolveCount

### ISSUE THREAD

**Issue by yoyo930021** [microsoft/vscode#110182]
- VSCode Version: 1.51.0
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Execute command `vscode.executeCompletionItemProvider`
2. have result from `completion`, but no any result from `completion/resolve`

Does this issue occur when all extensions are disabled?: Yes

I'm a extension developer.
I try to add e2e test for `completion/resolve` in LSP.
But I've noticed only get original completion data when set `itemResolveCount`.
I'm willing to issue a PR if it's confirmed to be a problem.

**Comment by yoyo930021** [comment]
Hi @jrieken 
When I add e2e test in LSP, I will use built-in command to get some info.
Example: https://github.com/vuejs/vetur/blob/2e0f8db398b7364afbfd7bbf7eb572dd202b3732/test/completionHelper.ts#L28.

But I can't get `completion/resolve` result in VSCode now.
Although it has an `itemResolveCount ` argument, but It doesn't return result after resolve.

The VSCode is only wait for `itemResolveCount`.
https://github.com/microsoft/vscode/blob/6b7eabb7f2e31e3ee1d02bdc3ebaffccd3d19402/src/vs/editor/contrib/suggest/suggest.ts#L364

**Comment by jrieken** [comment]
If the call to `resolve` doesn't return it's likely due to your extension. We have a passing test for this case here: https://github.com/microsoft/vscode/blob/b381a3a679528a6d78a2087d7a8879dc73dd672e/src/vs/workbench/test/browser/api/extHostApiCommands.test.ts#L696

**Comment by yoyo930021** [comment]
> If the call to `resolve` doesn't return it's likely due to your extension. We have a passing test for this case here:
> 
> https://github.com/microsoft/vscode/blob/b381a3a679528a6d78a2087d7a8879dc73dd672e/src/vs/workbench/test/browser/api/extHostApiCommands.test.ts#L696

You talk is only about `completion`.
I want to get `completion/resolve`.
In VSCode, I think it is `resolveCompletionItem` function.
https://github.com/microsoft/vscode/blob/b381a3a679528a6d78a2087d7a8879dc73dd672e/src/vs/workbench/test/browser/api/extHostApiCommands.test.ts#L666

**Comment by jrieken** [comment]
No, that's what the last parameter is for. There is no command to resolve items but an argument that says how many items should be resolved when asking for completions

**Comment by yoyo930021** [comment]
> No, that's what the last parameter is for. There is no command to resolve items but an argument that says how many items should be resolved when asking for completions

I expect that can get completions result after `resolved`.
If not, Do you want to add a command for this?

**Comment by jrieken** [comment]
> I expect that can get completions result after resolved

Yes. That's how it works and that's what the unit test asserts

**Comment by yoyo930021** [comment]
> > I expect that can get completions result after resolved
> 
> Yes. That's how it works and that's what the unit test asserts

No, This test is only we can get data from `provideCompletionItems` function.
but I want to get data from `resolveCompletionItem` function.

**Comment by jrieken** [comment]
> but I want to get data from resolveCompletionItem function.

The `resolveCompletionItem` returns a `CompletionItem`, so does `provideCompletionItems` (as array or list). When providing the argument to resolve items then the `resolveCompletionItem`-function is called and its result is part of the overall result. That's how you get the data.

**Comment by yoyo930021** [comment]
Sorry, my english is not well.
I found out later that it was because `vscode-languageclient` will convert `TextEdit` to another object.
So I can't see directly it.
Thanks for help.
