### ISSUE TITLE
Line height of suggestion details pane is too small when font size is large.

### ISSUE THREAD

**Issue by g-plane** [microsoft/vscode#110172]
- VSCode Version: 1.51.0
- OS Version: Arch Linux (kernel 5.9.6)

Line height of suggestion details pane is too small when font size is large. If font size is medium or small, this looks OK.

When font size is "15":

![图片](https://user-images.githubusercontent.com/17216317/98461632-ae940e80-21e8-11eb-9834-0911bee0d310.png)

When font size is "19":

![图片](https://user-images.githubusercontent.com/17216317/98461638-c4a1cf00-21e8-11eb-91ba-8fc869b87eed.png)

VS Code 1.50.0 doesn't has this problem.

Steps to Reproduce:

1. Set the "font size" to a large value, e.g. "19".
2. Edit a file which supports suggestion, then type something which will trigger the suggestion details pane.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
@g-plane What font are you using?

**Comment by jrieken** [comment]
I can reproduce with `editor.fontSize` being 19 or above. Is that what you are doing? This isn't with having the suggest font size configured, right?

**Comment by g-plane** [comment]
> What font are you using?

I'm using Jetbrains Mono.

> This isn't with having the suggest font size configured, right?

Yes. I don't configure that.
