### ISSUE TITLE
File name contains spaces or. Cannot compile problem

### ISSUE THREAD

**Issue by gaoqiang-3416** [microsoft/vscode#110133]
Use gcc to write a C language program. If the program name is 01.hello.c, it can’t run, but if it’s 01hello.c
, it can run normally.
![image](https://user-images.githubusercontent.com/55910045/98436974-f730c680-2119-11eb-8b64-88ec4692442e.png)

**Comment by eamodio** [comment]
This doesn't seem like an issue with VS Code.
