### ISSUE TITLE
Version 1.51.0 broke my extension: johtela.vscode-litscript-highlighting

### ISSUE THREAD

**Issue by johtela** [microsoft/vscode#110105]
- VSCode Version: 1.51.0
- OS Version: Windows 10 (reproduced with 2004 Home Edition and 1909 Professional)

Steps to Reproduce:

1. Install [LitScript Syntax Highlighting](https://marketplace.visualstudio.com/items?itemName=johtela.vscode-litscript-highlighting) extension with VSCode 1.50.1 -> Markdown is highlighted in JSDoc comments
2. Update to 1.51.0 -> Markdown syntax no longer highlighted in JSDoc comments

Does this issue occur when all extensions are disabled?: N/A

My extension is very simple; basically a fork of [JSDoc Markdown Highlighting](https://marketplace.visualstudio.com/items?itemName=bierner.jsdoc-markdown-highlighting). It contains no code, only configuration. It injects Markdown scopes to JSDoc comment blocks. My extension does this for TS, CSS, Less, and Scss file formats.

I have no way of investigating what has changed in version 1.51.0 that broke my extension. Only thing I can do is to try to change some settings in language file or package.json and check if that has fixed the issue. Oddly enough JSDoc Markdown Highlighting still works. It has almost identical configuration. But I can't figure out what is the culprit that breaks LiTScript Syntax Highlighting. Any clues are welcome.

**Comment by mjbvz** [comment]
We don't have resources to investigate why your extension isn't working for you.

As you noted, the JSDoc markdown extension works fine in 1.51/1.52, so I suggest you investigate your extension. If there something VS Code is doing is unexpected, then open a more specific issue that states what doesn't work and provides steps to reproduce the problem
