### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by capellac** [microsoft/vscode#110132]
Issue Type: <b>Bug</b>

Whenever I click something even if I click space, it hot reloads which I do not want something like this. I would like to hot reload my code when I click to ctrl+s

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.45GB free)|
|Process Argv|--crash-reporter-id 83b89c12-ac4b-4c67-a5f6-684bc3a4449f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.0
dart-code|Dar|3.16.0
flutter|Dar|3.16.0
todo-tree|Gru|0.0.186
pubspec-assist|jer|2.2.1
awesome-flutter-snippets|Nas|2.0.4
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.4.0
vim|vsc|1.17.1

</details>

**Comment by eamodio** [comment]
I'm not sure of your setup, but I would check into your auto-save settings.
