### ISSUE TITLE
vscode 1.51 Release Notes: Incorrect setting in Release Notes

### ISSUE THREAD

**Issue by sventec** [microsoft/vscode#110113]
- VSCode Version: 1.51.0
- OS Version: Windows_NT x64 10.0.19041

In the [v1.51 Release Notes](https://code.visualstudio.com/updates/v1_51), specifically the [Status bar for suggestions](https://code.visualstudio.com/updates/v1_51#_status-bar-for-suggestions) section:

The release notes mention the `editor.suggestStatusBar.enable` setting. However, on v1.51.0, that settings does not actually exist.

This setting, as far as I can tell, is actually `editor.suggest.showStatusBar`.

My apologies if this is not the right place to put this issue, I just did not know where to report an error in the Release Notes.

Does this issue occur when all extensions are disabled?: N/A

**Comment by rzhao271** [comment]
I think you can report that here https://github.com/microsoft/vscode-docs
