### ISSUE TITLE
Cannot install Terraform Extension from Hashicorp

### ISSUE THREAD

**Issue by mro-kgarayev** [microsoft/vscode#110161]
Issue Type: <b>Bug</b>

Tried to install Terraform extension from Hashicorp company via VS code extensions tab. But it's returned an error that Failed to intall hashicorp.terraform. Downloaded manually and tried to install in manually and it's also not helped
.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|16.00GB (5.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.1.0

</details>

**Comment by mro-kgarayev** [comment]
Issue during installation terraform.hashicorp extension

**Comment by gjsjohnmurray** [comment]
Why are you running such an old version of VS Code?

**Comment by sandy081** [comment]
Please try with latest version of VS Code and provide us following logs if you are still seeing the issue:

- Help -> Toggle Developer Tools -> Console
- View -> Command Pallette... -> Toggle Shared Process -> Console
- View -> Open View… -> Log (Shared)
- View -> Open View… -> Log (Window)

**Comment by mro-kgarayev** [comment]
> Why are you running such an old version of VS Code?

Hi, it's due to company software portal included this version and no it's not allowed for us to update it manually. On latest version it's working as well. Thanks.
