### ISSUE TITLE
Simple code causes the ui no-response

### ISSUE THREAD

**Issue by Necromonster** [microsoft/vscode#110111]
Version: 1.52.0-insider (user setup)
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:43:01.017Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/74076340/98416382-fa11b580-204c-11eb-8ff9-6033168faaaa.png)

2.`console.log('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'.repeat(5000))`

3.I also tested on Linux a different version on VS code it also responded this

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment]
/assign @Tyriar 

Looks like this issue is reproducible if
```
node -e "console.log('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'.repeat(5000))"
```
executed in `cmd` or `powershell` but has no problems with git-bash.
