### ISSUE TITLE
Change the number of words displayed in 'suggestions'

### ISSUE THREAD

**Issue by Chikapro** [microsoft/vscode#110175]
There are too many suggested words displayed when coding, and the number of suggested words can't be changed now. I hope I can change the suggested words to arbitrarily number.

**Comment by ArturoDent** [comment]
You can drag the lower border of the suggestions box up to reduce the number of suggestions shown.

**Comment by jrieken** [comment]
@Chikapro Is this with latest stable (1.51)? Did you try what @ArturoDent suggested?

**Comment by Chikapro** [comment]
@ArturoDent @jrieken Yes I tried and it works now, thanks very much!
