### ISSUE TITLE
Issues with the Find box

### ISSUE THREAD

**Issue by kpachar** [Microsoft/vscode#11013]
- VSCode Version:1.4.0
- OS Version:Windows 10

Steps:
First of all, thank you for this good editor. It's nice and I enjoy using it.
The Find box has some minor issues:
Suppose you want to search for a certain phrase and make some modifications near that phrase.
Eg: Consider this text:
```
x = process("cat");
y = process("mouse")
... ...
z = process("dog");
...
```

Say you want to change it to this:

```
x = process($("cat").getId());
y = process($("mouse").getId());
... ...
z = process($("dog").getId());
...
```

(for whatever reason),

You'd hit Ctrl+F and type in "process" in the Find box. 
Problem 1) Once it highlights the first occurrence of the word 'process', the Escape key does not close that Find box. I have to visually locate the highlighted word, and take my mouse to click near that word and position my cursor there.
Continuing with the example, I reach `x = process("cat");` and position my cursor after the opening curve bracket `(` and type in `$(` and then move to the `"` following `cat` and type in `).getId()` to change it to `x = process($("cat").getId());`. 
Then, to avoid typing in `).getId()` again, I select the word `).getId()` that I just typed, copy it and then I want to continue my search for `process`.
Problem 2) There's no way to continue my previous search now. Hitting Ctrl+F while this is selected automatically overwrites my Find box's contents `process` with `).getId()`. There should be a switch to disable this behavior.
Problem 3) The Next Match and Previous Match arrows on the Find box don't work. Clicking them doesn't do anything. There aren't any keyboard shortcuts on them either.
Problem 4) The find box shows a misleading "No Results" in red background even when it actually finds some results and highlights them.

**Comment by sandy081** [comment]
@kpachar Thanks for using VS Code and reporting this issue.

>> Problem 1) Once it highlights the first occurrence of the word 'process', the Escape key does not close that Find box. I have to visually locate the highlighted word, and take my mouse to click near that word and position my cursor there.

<kbd>esc</kbd> closes the Find box for me. Can you please check that in your keyboard shortcuts settings, `closeFindWidget` is bound to `escape`.

>> Problem 2) Then, to avoid typing in ).getId() again, I select the word ).getId() that I just typed, copy it and then I want to continue my search for process.
There's no way to continue my previous search now. Hitting Ctrl+F while this is selected automatically overwrites my Find box's contents process with ).getId(). There should be a switch to disable this behavior.

>> Problem 3) The Next Match and Previous Match arrows on the Find box don't work. Clicking them doesn't do anything. There aren't any keyboard shortcuts on them either.

<kbd>ctrl</kbd>+<kbd>f</kbd> action always starts finding the text selected. You can use <kbd>ctrl</kbd>+<kbd>F3</kbd> (`editor.action.nextSelectionMatchFindAction`) and <kbd>shift</kbd>+<kbd>ctrl</kbd>+<kbd>F3</kbd> (`editor.action.previousSelectionMatchFindAction`) for finding next or previous find matches.

>> Problem 4) The find box shows a misleading "No Results" in red background even when it actually finds some results and highlights them.

Can you please provide a proper example with steps where you are seeing this behavior.

Thanks.

**Comment by sandy081** [comment]
Closing this since there is no feedback on this issue. Please reopen it with required information
