### ISSUE TITLE
Support persisting splits in reconnected terminals across window reloads

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#110107]
Currently when remotes reconnect terminals the split terminals get flattened into their own terminals. This is mainly an issue of how we want to persist that knowledge across sessions and make sure the remote agent stores it (eg. `splitIndex: number` may be enough). Note also that split terminals are naturally smaller so they have non-standard dimensions, not sure we need to do anything special to handle dimensions differently as resize events are recorded.

Ideally there may need to be some logic/checks to ensure split terminals get adopted together so they cannot be split up. This will probably involve the introduction of the terminal tab idea on the server.

**Comment by bpasero** [comment]
Isn't this https://github.com/microsoft/vscode/issues/109244 ?
