### ISSUE TITLE
Enhance settings title generation to allow other case conventions

### ISSUE THREAD

**Issue by mark-wiemer** [microsoft/vscode#110163]
I'm authoring an extension, and I'd like to set the name of one of my settings to "Enable IntelliSense". However, the only options available to me are "Enable Intellisense" (with a small `s`) and "Enable Intelli Sense". Neither of these look right to me. Allowing camelCase, kebab-case, TRAIN_CASE, PascalCase, or [other case conventions](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Examples_of_multiple-word_identifier_formats) would enable extension authors to create more informative settings names.

**Comment by roblourens** [comment]
Covered by https://github.com/microsoft/vscode/issues/70589
