### ISSUE TITLE
Support for creating, loading, saving, and closing multi folder projects with side bar

### ISSUE THREAD

**Issue by Shadowblitz16** [microsoft/vscode#110117]
I come from visual studio 2019 and I find it very hard to create a new project in vs code.
I was wondering if we can have support for creating, loading, saving, and closing multi and single folder projects with side bar?
I was thinking a create project button in the explorer tab as well as the ability to load and remove workspaces
![image](https://user-images.githubusercontent.com/2453707/98423650-2c6ae500-2044-11eb-9e40-0ec7b7e6c8a3.png)

**Comment by isidorn** [comment]
There are already commands like F1 > Workspace Add Folder To Workspace and others
Please try using that

![Screenshot 2020-11-09 at 09 30 09](https://user-images.githubusercontent.com/1926584/98517426-2f491e00-226e-11eb-9e6c-18d7a81d2822.png)

We will not have buttons for each of those in the explorer side bar, thus closing as designed
