### ISSUE TITLE
Git extension does not gray out ignored files on Ubuntu20.04

### ISSUE THREAD

**Issue by vule24** [microsoft/vscode#110104]
Issue Type: <b>Bug</b>

1. Access to repo on Ubuntu20.04 by remote ssh extension 
2. Create `.gitignore` file and fill the proper ignored filenames.

When I access to Ubuntu18.04 remote desktop, git extension do gray out those ignored files

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 5.4.0-52-generic
Remote OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.78GB free)|
|Process Argv|--crash-reporter-id bbf63062-278d-4213-a7c6-f90b1fed7248|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: lab-hn|
|OS|Linux x64 5.4.0-52-generic (ubuntu18.04)| 
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 4948)|
|Memory (System)|31.29GB (16.74GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sg|
|OS|Linux x64 5.4.0-52-generic(ubuntu20.04)|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 800)|
|Memory (System)|31.30GB (18.34GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Is `git` on the PATH?

**Comment by joaomoreno** [comment]
Does it work if you reload the window?

**Comment by vule24** [comment]
> Is `git` on the PATH?

@chrmarti Are you mentioning PATH on Window? I use git on remote server, git still work well on terminal, no git installed on my desktop client. I tested on Ubuntu client as well but this problem still happens. I have found that not only ignoring files but autoloading as well. It seem like Ubuntu20.04 error, I guess.
I have created an ubuntu18.04 container on this ubuntu20.04 server and surprisingly no above issue occurs.

> Does it work if you reload the window?

@joaomoreno Unfortunately no, I have tried it many times.

**Comment by chrmarti** [comment]
@vule24 Try adding `"userEnvProbe": "loginInteractiveShell"` to the devcontainer.json. (If `git` gets on the PATH only through your shell's startup scripts, you need that.)

**Comment by vule24** [comment]
@chrmarti  I have tested on a local Ubuntu20.04 desktop and the same symptom happens. 
Thanks for your solution. However instead of using a temporary solution, I hope to have the same experiment on Ubuntu18.04.
It would be extremely great if it's fixed in the next realease.
I truly appreciate that :D

**Comment by joaomoreno** [comment]
Can you share screenshots of the file explorer and the SCM view?
