### ISSUE TITLE
Cosistent markdown rendering of http code blocks

### ISSUE THREAD

**Issue by rvinzent** [microsoft/vscode#110116]
Hi, I am writing some API documentation, and I realized the `http` highlighted code blocks are pretty useful for making it look nice. However I am unable to get the syntax highlighting to render consistently. Code blocks pasted with extra backslash because I couldn't figure out how to escape it properly

For example, these code blocks render the JSON as different colors, and the only difference appears to be the existence of a comment
``` 
```http
POST /api/v1/labware-type/ HTTP/1.1

{
    "name": "96-Well Plate",
    "description": "A standard 96-Well plate for general use.",
    "rows": 8,
    "columns": 12,
    "default_designation": "Plasticware", // this must exist as an available LabwareDesignation
    "default_barcode_prefix": "PG"
}
``
```
<img width="958" alt="Screen Shot 2020-11-06 at 3 00 20 PM" src="https://user-images.githubusercontent.com/34038882/98422563-d8aacc80-2040-11eb-9fdc-da3dc6c535ce.png">

```
```http
POST /api/v1/labware-type/ HTTP/1.1

{
    "name": "Tube",
    "description": "A standard micro-centrifuge tube for general use.",
    "rows": 1,
    "columns": 1,
    "default_designation": "Plasticware",
    "default_barcode_prefix": "TU"
}
``
```

<img width="428" alt="Screen Shot 2020-11-06 at 2 49 29 PM" src="https://user-images.githubusercontent.com/34038882/98422061-9af97400-203f-11eb-9714-a25d1a8853f9.png">

Other times, comments don't highlight properly, and as far as I can tell, the markdown is the same format. Removing the `-->` doesn't seem to help, and also this `-->` arbitrarily seems to either render as green or white, and I have no idea what causes that. 
```
```http
POST /api/v1/labware/IB1235/aliquots/ HTTP/1.1

{
    "row": 1,
    "column": 1,
    "sample": {
        "name": "NIPS Specimen",
        "sample_type": "Blood"
    }
}
-->
{
    "id": 2385289,
    "row": 1,
    "column": 1,
    "position": "A1",  // letter number format for position names
    "status": "Available",
    "sample": {
        "id": 743793,
        "name": "NIPS Specimen",
        "sample_type": "Blood",
        "components": [],
        ...
    }
}
``
```
<img width="644" alt="Screen Shot 2020-11-06 at 2 57 18 PM" src="https://user-images.githubusercontent.com/34038882/98422408-689c4680-2040-11eb-96bf-043859b2c2ac.png">

I cannot find documentation _anywhere_ on how to properly use this HTTP syntax highlighting and sometimes it appears the same format renders inconsistently.

**Comment by mjbvz** [comment]
I don't think VS Code includes built-in http highlighting. Is this from an extension?

/needsMoreInfo

**Comment by rvinzent** [comment]
HI @mjbvz , I don't have any markdown extensions installed, so I assume this is coming from somewhere in vanilla VSCode. Maybe the syntax highlighting in markdown code blocks is delegated to a third-party?

**Comment by mjbvz** [comment]
Do you have an http extension installed? Markdown files use the default highlighter for whatever language is in the code block and, to my knowledge, VS Code does not include support for http highlighting.

**Comment by rvinzent** [comment]
> Do you have an http extension installed?

No I don't believe so. Here is my list of installed extensions, nothing that I would think supports syntax highlighting in markdown code blocks.

```
adpyke.vscode-sql-formatter-1.4.4                   
bungcip.better-toml-0.3.2                           
dbaeumer.vscode-eslint-2.1.13                       
eamodio.gitlens-10.2.2                              
eamodio.gitlens-10.2.3                              
editorconfig.editorconfig-0.15.1                    msjsdiag.debugger-for-chrome-4.12.11
mathiasfrohlich.kotlin-1.7.1                        ofhumanbondage.react-proptypes-intellisense-1.0.3
ms-azuretools.vscode-docker-1.7.0                   rbbit.typescript-hero-3.0.0
ms-python.python-2020.10.332292344                  redhat.vscode-yaml-0.11.1
ms-python.vscode-pylance-2020.10.2                  redhat.vscode-yaml-0.12.0
ms-python.vscode-pylance-2020.10.3                  vscodevim.vim-1.17.1
ms-python.vscode-pylance-2020.11.0
ms-vscode-remote.remote-containers-0.145.1
ms-vscode-remote.remote-ssh-0.55.0
ms-vscode-remote.remote-ssh-edit-0.55.0
ms-vscode-remote.remote-wsl-0.50.1
```

**Comment by mjbvz** [comment]
This doesn't repo for me with extensions disabled so this must be one of your extensions. If you find which one contributes the grammar, please file the issue against
