### ISSUE TITLE
[semantic highlighting] improve fallback scope for macro

### ISSUE THREAD

**Issue by georgewfraser** [microsoft/vscode#110150]
- VSCode Version: 1.51.0
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. Run an extension that uses semantic coloring mark a token as "macro"
2. Observe that no fallback scope is being applied:

<img width="484" alt="Screen Shot 2020-11-07 at 10 47 49 AM" src="https://user-images.githubusercontent.com/1369240/98449245-cedba480-20e6-11eb-93ca-dd1e4db7da90.png">

Does this issue occur when all extensions are disabled?: Yes/No

Not applicable, this bug can only occur when an extension is using macro syntax coloring.

**Comment by georgewfraser** [comment]
The fallback scope for "macro" is described in https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-scope-map

**Comment by aeschli** [comment]
`entity.name.other.preprocessor.macro` is defined as the fallback scope, but non of the built-in theme define any color for it.

Is there a better scope to use?

@Colengms Any suggestions?

**Comment by Colengms** [comment]
@aeschli The TextMate scope for `macro` used in the original C/C++ semantic colorization feature was: `entity.name.function.preprocessor`, which we still use as a fallback.

https://code.visualstudio.com/docs/cpp/colorization-cpp

It was mentioned here, when discussing adding scopes to plus themes: https://github.com/microsoft/vscode/issues/80783

The C/C++ extension currently uses the same semantic token for both function macros and non-function macros.

**Comment by georgewfraser** [comment]
@aeschli If `entity.name.other.preprocessor.macro` is the fallback scope, why doesn't it show up in the tooltip? Perhaps that is a separate bug?

**Comment by aeschli** [comment]
@georgewfraser The tooltip wants to show how the style at the current position was determined. For semantic highlighting it would show the theming rule if it had matched one. As current theme doesn't have theming rules to neither the token type (`macro`) nor the fallback scope(s), no such information is shown

**Comment by aeschli** [comment]
I pushed a fix to change the `macro` fallback scope to `entity.name.function.preprocessor`

**Comment by aeschli** [comment]
To verify open the https://github.com/microsoft/vscode-extension-samples/tree/master/semantic-tokens-sample, add `macro` as a supported token. Use the 'Inspect token and scopes' command to verify that it is colored with the color associated with the `entity.name.function.preprocessor` scope
