### ISSUE TITLE
Files are no longer detected as being part of the workspace (breaking auto reveal in sidebar)

### ISSUE THREAD

**Issue by jhammersholt** [microsoft/vscode#110146]
When i select a file VSC no longer reveals it in the sidebar even though i have set VSC to automatically do that, furthermore when searching in files some files are listed as part of the workspace and other are not EVEN though they reside inside the same folder

- VSCode Version: 1.51
- OS Version: Win 10 19042.572

Steps to Reproduce:

1. Use the editor
2. Search

or

1. Click on files in editor with auto reveal on

Does this issue occur when all extensions are disabled?: Yes

I 'solved' all issues by rolling back to version 1.50

**Comment by eamodio** [comment]
I can't reproduce this. Is there anything special about the folder/workspace you are opening?

**Comment by rosczja** [comment]
I have the exact same problem. I tried it with a fresh install of Code on Windows and with just one workspace. Still does not auto reveal any files.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/110188
fyi @jrieken seems like more people are hitting this, so good thing we do a recovery. Though we should decide what to do for insiders.
