### ISSUE TITLE
Cannot find extension in VSCode

### ISSUE THREAD

**Issue by torn4dom4n** [microsoft/vscode#110126]
VSCode version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-15T10:42:48.064Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.18-1-MANJARO

Steps to Reproduce:

1. Open VSCode
2. Select Extensions: Marketplace
3. Search `latex language support`

![Screenshot_20201019_134139](https://user-images.githubusercontent.com/5488440/96445935-fab6e900-1210-11eb-8003-c49ffddb277a.png)

I copy this issue from my github repo [vscode-LaTeX-support/issues/10](https://github.com/AREA44/vscode-LaTeX-support/issues/10). The issue happen in Germany and France.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by tamuratak** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Comment by torn4dom4n** [comment]
> Duplicate of [#107997 (comment)](https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178)

Thanks.
