### ISSUE TITLE
Remote label doesn't show up in Recently Opened correctly

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#110153]
This has been reported but I just noticed that I can repro it. See the first entry

![image](https://user-images.githubusercontent.com/323878/98449913-c2f2e100-20ec-11eb-8f8e-9f6dffdd28b6.png)

How can I debug it?

**Comment by isidorn** [comment]
I would guess this is timing related. Anyways best is to put a breakpoint [here](https://github.com/microsoft/vscode/blob/59a1893d6d66171437f3608d2e938efa616f421e/src/vs/workbench/services/label/common/labelService.ts#L185). That is the method for computing the workspace label
In case that does not get hit than @sbatten would know more how the Recently Opened list is computing Workspace labels

**Comment by roblourens** [comment]
That isn't called, it seems like it was calculated once then cached. Guessing that if I remove it from the list and open it again, it will show the right label.

**Comment by isidorn** [comment]
As for caching @sbatten would know best when and how that is done for the recently opened list.

**Comment by sbatten** [comment]
Yes, if we have a cached label and the workspace/folder is not currently opened, we just use the label as cached.

**Comment by roblourens** [comment]
I see it whether the folder is open or not. Here it is open

![image](https://user-images.githubusercontent.com/323878/101420694-937bf380-38a7-11eb-94c5-ec15ee9886f2.png)

**Comment by isidorn** [comment]
Assigning to @sbatten so you can first investigate from the recently opened list and then forward to me

**Comment by sbatten** [comment]
@roblourens sorry I misunderstood a step in the code, it appears we will always use the cached label

**Comment by sbatten** [comment]
This was fixed by a general caching mechanism implemented to solve something similar for tunnels.
