### ISSUE TITLE
Option to use gtk themes on linux?

### ISSUE THREAD

**Issue by Shadowblitz16** [microsoft/vscode#110123]
Can we get a plug-in for translating linux user's current gtk theme to vscode?

**Comment by aeschli** [comment]
You could write such an extension to generate a theme from a gtk theme.

VSCode themes consist of many colors, so you probably have to come up with some solution how to define these colors based on the GTK colors.

See https://code.visualstudio.com/api/extension-guides/color-theme  for more information on how to write a color theme.
