### ISSUE TITLE
TaskProcessEndEvent.exitCode is undefined on task termination

### ISSUE THREAD

**Issue by dsanders11** [microsoft/vscode#110185]
Issue Type: <b>Bug</b>

If an executing task is terminated, the `exitCode` on `TaskProcessEndEvent` will be `undefined`, even though the Typescript definitions don't list `undefined` as a possibility.

The underlying `TaskEvent` which is used to trigger the `TaskProcessEndEvent` *does* list `undefined` as a possible value, but this is overriden. It was changed in [this commit](https://github.com/microsoft/vscode/commit/fdc710af64c74335e330b5cd98a5f60d5b188caa#diff-12843c7cf67035bfd990a30f426d90f44108acfa9ea3daa5f6c715023a360f28R404).

@mjbvz, is this intended behavior? I would expect `TaskProcessEndEvent.exitCode` to list `undefined` as a possible value since it is possible.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

**Comment by alexr00** [comment]
This seems to be an oversight in our API. @jrieken or @mjbvz, this value can be undefined, which is consistent with how the integrated terminal works too:

https://github.com/microsoft/vscode/blob/875c2ced66174e98d5a732e9b51110181dd52b33/src/vs/vscode.d.ts#L6421-L6424

Simply adding ` | undefined` to the existing API could break some extension authors. Is there a good way to fix this?

**Comment by jrieken** [comment]
I would add the breaking type annotation since this isn't a behavioural change but only one types definition

**Comment by mjbvz** [comment]
Adding `| undefined` seems ok since that's already the runtime behavior. The other option would be to initialize `exitCode` to zero

**Comment by dsanders11** [comment]
@mjbvz, I think it's useful to know that the task was terminated rather than naturally finished, so initializing it to zero would lose that information.
