### ISSUE TITLE
Auto Complile on Save for TypeScript

### ISSUE THREAD

**Issue by ras90it** [microsoft/vscode#110196]
Issue Type: <b>Feature Request</b>

Auto Complile on Save for TypeScript

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

**Comment by thunder-coding** [comment]
The TypeScript Compiler already has this functionality.

First make sure you have TypeScript Compiler installed via npm.
Then run `tsc --watch` in a new terminal

Then the TypeScript Compiler will detect for file changes and compile your code again whenever it finds any change

**Comment by mjbvz** [comment]
As @thunder-coding noted, we use [tasks](https://code.visualstudio.com/Docs/editor/tasks) for this
