### ISSUE TITLE
Cannot rename class reference used within the class itself (JavaScript)

### ISSUE THREAD

**Issue by mikehaas763** [Microsoft/vscode#11015]
- VSCode Version: 1.4.0
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce:

1. Create an ES6 class in JavaScript (not sure if issue is in TypeScript or not).
2. Reference that class in a method of the class.
3. Try rename using the reference symbol.
4. An info message appears "You cannot rename this element."

```javascript
class Foo {
  do() {
    return Foo;
  }
}
```

**Comment by waderyan** [comment]
This works in 1.6-Insiders.
