### ISSUE TITLE
The terminal does not start in user mode, but starts in administrator mode.

### ISSUE THREAD

**Issue by agvozdezkiy** [microsoft/vscode#110191]
- VSCode Version: 5.51.0
- OS Version: Windows 10 build 19041.572

Steps to Reproduce:

1. Press ctrl-`.
2. Gives error: notificationsAlerts.ts:40 The terminal process failed to launch: A native exception occurred during launch (Cannot launch conpty).

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by agvozdezkiy** [comment]
Also updating works only in administrator mode.

**Comment by meganrogge** [comment]
@agvozdezkiy This seems like an issue with ConPTY. Please report it to https://github.com/Microsoft/console (the team who owns ConPTY) or this repo (if you think it's an integration issue). You can opt out of conpty by adding this setting:

"terminal.integrated.windowsEnableConpty": false

**Comment by agvozdezkiy** [comment]
No. Maybe, you did not understand me. I can run the windows terminal every time when I want. And PHPstorm runs cmd.exe  without problems. But VS Code can't do it in my_user mode.

**Comment by meganrogge** [comment]
@agvozdezkiy have you tried setting "terminal.integrated.windowsEnableConpty": false? I ask bc that has helped in cases such as #88008

**Comment by agvozdezkiy** [comment]
I get this:
The terminal process failed to launch: A native exception occurred during launch (Error launching WinPTY agent: winpty-agent CreateProcess failed: cmdline='"\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\node-pty\build\Release\winpty-agent.exe" \\.\pipe\winpty-control-14240-1-1d6b651cf83ead3-d9f4e6d04bf20b70b14cd7dcd79f8e1a 0 1 261 15' err=0x4ec).

**Comment by Tyriar** [comment]
This is likely related to an anti-virus blocking the library we use to launch the process. If you do have anti-virus software you can try allow the files by following these instructions: https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch#_error-connectnamedpipe-failed-windows-error-232

If that doesn't work then chances are you're seeing this upstream issue: https://github.com/microsoft/terminal/issues/6862
