### ISSUE TITLE
editor.showUnused: Access modifiers declared in the class still highlighted as unused

### ISSUE THREAD

**Issue by rinshankolayil** [microsoft/vscode#110137]
I have enabled **editor.showUnused** with following codes in the usersettings
`{
    "editor.showUnused": true,
    "workbench.colorCustomizations": {
        "editorUnnecessaryCode.border": "#a10906",
        "editorUnnecessaryCode.foreground": "#a10906",
    }
}`

1. I have declared a access modifier (private,protected or public) as **private $db** and assigned some value in the **constructor**.
2. But in the visual studio code IDE, i can still view the error border line which indicating the variable as unused variable.

![Capture](https://user-images.githubusercontent.com/40558052/98439929-584e9f00-2106-11eb-81b3-d8537957d74b.JPG)

**Comment by mjbvz** [comment]
Please file this against your PHP extension
