### ISSUE TITLE
VS-Code marks all the code wrong but only in one document and not in the other one 

### ISSUE THREAD

**Issue by Zererat** [microsoft/vscode#110144]
![Screenshot (34)](https://user-images.githubusercontent.com/69715864/98446658-4e856580-211f-11eb-8dd4-f208ce3ad12c.png)
Hey guys. I switched from Intellij Ultimate to VS Code and I found the following problem. React is properly installed and node runs fine. All the other files (I've imported from IntelliJ) run fine 2. After creating this new file (on the right sight) this error appeared. Any suggestions how I can fix this? 
Thx for help

**Comment by mjbvz** [comment]
/needsMoreInfo

Please share a small example project and steps to reproduce this issue
