### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by a11smiles** [microsoft/vscode#110145]
Issue Type: <b>Bug</b>

In the October 2020 release, intellisense stops working when the file system changes (e.g. a new file is created, files are moved in the project, etc.).  I have to close Code and reopen it for intellisense to kick back in.

Additionally, when I add a new file, intellisense doesn't "run" on the new file. If I want intellisense running on the new file, I, again, have to close Code and reopen it.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.12GB free)|
|Process Argv|. --crash-reporter-id 503ddb96-1884-479b-8fd7-373a318dcb50|
|Screen Reader|no|
|VM|22%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
ascii-tree-generator|apr|1.2.4
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
gitlens|eam|10.2.3
prettier-vscode|esb|5.7.1
vscode-todo-plus|fab|4.18.0
dotnet-test-explorer|for|0.7.4
github-actions|for|0.0.1
terraform|has|2.2.3
vscode-guid|hea|1.4.20
wordcounter|kir|2.3.0
git-graph|mhu|1.27.0
azure-pipelines|ms-|1.177.0
vscode-azureappservice|ms-|0.19.0
vscode-azurefunctions|ms-|1.0.0
vscode-cosmosdb|ms-|0.15.0
vscode-docker|ms-|1.7.0
csharp|ms-|1.23.5
vscode-dotnet-runtime|ms-|0.2.0
mssql|ms-|1.9.0
python|ms-|2020.10.332292344
azure-account|ms-|0.9.3
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
azurerm-vscode-tools|msa|0.13.0
vscode-coverage-gutters|rya|2.6.0
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|sib|2.0.2
code-spell-checker|str|1.9.2
vscode-icons|vsc|11.0.0

</details>

**Comment by a11smiles** [comment]
For additional info on environment, I'm writing a .NET Core app (Azure Fn) in C#.

**Comment by luuap** [comment]
Faced this issue as well. I'm working on an Angular app, which uses Typescript language features.

When I copied a file on the same directory, it could not resolve the aliased paths on the new file, while the old file was fine. Restarting did not seem to fix it, so I just rolled back to the previous version.

**Comment by tonymatute** [comment]
> For additional info on environment, I'm writing a .NET Core app (Azure Fn) in C#.



> Issue Type: Bug
> 
> In the October 2020 release, intellisense stops working when the file system changes (e.g. a new file is created, files are moved in the project, etc.). I have to close Code and reopen it for intellisense to kick back in.
> 
> Additionally, when I add a new file, intellisense doesn't "run" on the new file. If I want intellisense running on the new file, I, again, have to close Code and reopen it.
> 
> VS Code version: Code 1.51.0 ([fcac248](https://github.com/microsoft/vscode/commit/fcac248b077b55bae4ba5bab613fd6e9156c2f0c), 2020-11-05T18:14:40.758Z)
> OS version: Darwin x64 18.7.0
> 
> System Info
> Extensions (33)

Hey Joshua!,
Did you get this issue resolved? I am having the same problem and I can't find anything to resolve it

**Comment by heggi** [comment]
I have had a same issue.
Updating extension c# to 1.23.6-beta (from github) resolves it.
