### ISSUE TITLE
Issue with Integrated Terminal

### ISSUE THREAD

**Issue by Jaimish00** [microsoft/vscode#110176]
![temp 3](https://user-images.githubusercontent.com/48212176/98463777-e5b3f100-21e3-11eb-8d81-66d5d8019b98.jpg)
Unexpectedly my Terminal got like this. I am not understanding what is the issue. Also, I am not able to change the font of the terminal

**Comment by meganrogge** [comment]
@Jaimish00 Does this occur when you have disabled all extensions?

**Comment by meganrogge** [comment]
@Jaimish00 Also, can you run ver in cmd to get the Windows build number?

**Comment by trumbitta** [comment]
@Jaimish00 this happended to me once because I had two different machines synchronize their vscode settings and the older one also had an older sync settings format. Before understanding what was going to happen, I chose to override the newer settings with the older one and all hell broke loose.

**Comment by Jaimish00** [comment]
Hey guys, i just removed my font family of the terminal, which was Fira Mono Nerd font and the terminal was again back to its normal condition.
I think it was because of that only. Thanks for the suggestions!
