### ISSUE TITLE
VS Code 请使用严格的等宽字体。（Please use a strict monospace font for VS Code.）

### ISSUE THREAD

**Issue by WuZhengqiang666** [microsoft/vscode#110143]
VS Code 请使用严格的等宽字体。
中文字符及标点的宽度严格对应两个英文字符或者数字。
VS Code现在的字体看起来很糟糕！我无法排版，无法对齐。具体内容请看图。
感谢，Thanks♪(･ω･)ﾉ
——————————————————————————————————————————
This is Google Translate, there may be grammatical errors, please forgive me.
Please use a strict monospace font for VS Code.
The width of Chinese characters and punctuation corresponds strictly to two English characters or numbers.
The fonts in VS Code now look terrible! I can’t typeset or align. Please see the picture for details.
Thanks♪(･ω･)ﾉ

![VS Code](https://user-images.githubusercontent.com/49598775/98445375-72ae6a00-2152-11eb-9a09-9710e2358f30.jpg)

![Visual Studio Community 2019](https://user-images.githubusercontent.com/49598775/98445383-8528a380-2152-11eb-92c7-37b4465a6695.jpg)

![Word](https://user-images.githubusercontent.com/49598775/98445397-91acfc00-2152-11eb-8cf1-29272575b6f6.jpg)

**Comment by alexdima** [comment]
VS Code respects the glyph width settings defined by the font family.

Please configure `editor.fontFamily` to a font that defines wide characters to be the width of two latin characters. e.g. [Inconsolata](https://fonts.google.com/specimen/Inconsolata).

**Comment by jerviscui** [comment]
@WuZhengqiang666 换楼上说的这个字体，可以等宽
