### ISSUE TITLE
[themes] Editor tokens and scopes are different on different OS

### ISSUE THREAD

**Issue by Jimmydalecleveland** [microsoft/vscode#110118]
- VSCode Version: 1.51.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open VSCode from windows
2. Open VSCode from WSL2 Ubuntu
3. Observe that the colors of some themes are different
4. Open command palette and select "Developer: Inspect Editor Tokens and Scopes"
5. Observe that in each VSCode instance the tokens have different names for different properties, such as javascript imports and object keys.

Does this issue occur when all extensions are disabled?: Yes or N/A because this is an extension so I can't disable them all.

I'm assuming this occurs in regular Ubuntu as well, but can't say for sure.

Example from Windows:
![image](https://user-images.githubusercontent.com/3894120/98426472-31389480-2056-11eb-8b8e-ef6893903e23.png)

Example from WSL2 Ubuntu:
![image](https://user-images.githubusercontent.com/3894120/98426490-4b727280-2056-11eb-8561-ea0af4e1ba5d.png)

**Comment by aeschli** [comment]
You can see that the first editor is associated to `javascriptreact`, but the second one to `javascript`.
Please check if if you have changed the file-extension to language association in the settings.

**Comment by Jimmydalecleveland** [comment]
Good eye, I totally missed that. I changed the file to `javascriptreact` and VS Code says in the bottom right corner that the file is now "Javascript React", but inspecting the tokens still shows it as `javascript` and closing the file and re-opening it shows it changed back to "Babel Javascript".

**Comment by Jimmydalecleveland** [comment]
I've changed the Windows version to be `javascript` and the syntax highlighting hasn't changed. I also shrunk the window to hopefully make the information more clear by showing the language in the bottom right.
![image](https://user-images.githubusercontent.com/3894120/98615720-81169600-22b8-11eb-89d6-5410e819f674.png)

Then I set the file associations in the WSL Ubuntu editor to make sure the file is set to `javascriptreact`
![image](https://user-images.githubusercontent.com/3894120/98615669-6c3a0280-22b8-11eb-8bab-289953d88f10.png)

So this is them reversed and still having the same issue.

**Comment by Jimmydalecleveland** [comment]
I've noticed that when disabling all extensions, more values show up and the "textmate scopes" are different, if that helps at all
Windows:
![image](https://user-images.githubusercontent.com/3894120/98616074-42351000-22b9-11eb-966d-bc12501cbef6.png)


WSL Ubuntu
![image](https://user-images.githubusercontent.com/3894120/98616074-42351000-22b9-11eb-966d-bc12501cbef6.png)

**Comment by Jimmydalecleveland** [comment]
Sorry, meant to edit that last one not delete it.

I've noticed that, when disabling all extensions, I get more information while inspecting scopes and the "textmate scopes" are different if that helps at all.

Windows:
![image](https://user-images.githubusercontent.com/3894120/98616183-7d374380-22b9-11eb-9d83-5eca43f59f4d.png)

WSL Ubuntu:
![image](https://user-images.githubusercontent.com/3894120/98616194-845e5180-22b9-11eb-9046-a4e63bb5ad59.png)

**Comment by Jimmydalecleveland** [comment]
I think I might have wasted your time. I restarted with all extensions disabled and got the syntax to swap and show the same values when inspecting scopes. I'm in the process of flipping extensions on to see which might be the culprit, but I don't want to take anymore of your time.

Sorry about that, and thank you for pointing me in the right direction!

**Comment by aeschli** [comment]
No worries. Be assured that there's no OS specific code for the tokenization.
