### ISSUE TITLE
OSX: Can't undo on any text input box

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11011]
Find widget, search viewlet, git viewlet, extensions viewlet, etc...

It seems that the editor is getting the Undo command. When all editors are closed I get this message:

![image](https://cloud.githubusercontent.com/assets/22350/18002217/c82dccae-6b86-11e6-8e44-46f123da71b3.png)

**Comment by alexandrudima** [comment]
@joaomoreno If you remove the Undo entry from the mac menu, does it work?

https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/menus.ts#L486
https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/menus.ts#L507
```
			undo = this.createDevToolsAwareMenuItem(nls.localize({ key: 'miUndo', comment: ['&& denotes a mnemonic'] }, "&&Undo"), 'undo', (devTools) => devTools.undo());
```

**Comment by joaomoreno** [comment]
Negative, still doesn't work. But, with that change, I no longer receive the console warning when no editors are open.

**Comment by alexandrudima** [comment]
Does undo work in native elements of the electron sample app?

**Comment by bpasero** [comment]
@alexandrudima @joaomoreno this is a known issue that was reported already before. 

We do some magic with Cut, Copy, Paste where we send the command to the browser if no editor is focussed. I think we should do the same for Undo/Redo if possible.

See https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/clipboard/browser/clipboard.ts#L28

**Comment by joaomoreno** [comment]
Duplicate of #8439
