### ISSUE TITLE
Support multiple screen feature

### ISSUE THREAD

**Issue by MPi3D** [microsoft/vscode#110152]
Hello, I am using Visual Studio Code and I have multiple screens. So I wonder if it is possible to use it on multiple screens not by creating multiples instances but by splitting one instance into multiples windows.
For example, detach the file explorer on a new window or detach the debug console.
With this splitting feature, everyone would be able to custom his own disposition of every component. For example, you would be able to put your code on a full vertical screen and put the debug console and the file explorer on another screen. You can see an example below split into 3 different screens:

![Screens](https://user-images.githubusercontent.com/26822551/98449162-8f867580-2131-11eb-82ac-07214c5e970e.png)

If you have some questions please let me know.

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/wiki/Roadmap#workbench
