### ISSUE TITLE
Cursor jumps line

### ISSUE THREAD

**Issue by nermineslimane** [microsoft/vscode#110173]
Issue Type: <b>Bug</b>

My cursor jumps to the next line while i'm writing , if i stop for 2 seconds , i'll find my cursor somewhere else . i tried disabling all extensions and restarting Vscode , i tried updating it , nothing seems to work

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.44GB (5.43GB free)|
|Process Argv|--crash-reporter-id f17b5eb2-bd87-4410-a039-319e9fb2be0a|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|3.0.0
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.1

</details>

**Comment by avrahamwn** [comment]
I have the same issue. any help?

**Comment by nermineslimane** [comment]
I deactivated all the plugins and updated my vscode . and it worked so i
assume that the problem was that one of the plugins has a bug.

Nermine SLIMANE

Software engineer student


p:(+216)29376602

a: Rades, Tunisia

e:slimane.nermine@esprit.tn

  <https://www.facebook.com/nermine.slimane>
<https://www.instagram.com/nermine.slimane/?hl=en>
<https://www.linkedin.com/in/nermine-slimane-810114159/>

**Comment by alexdima** [comment]
@nermineslimane If you track down which extension is to blame, please report an issue directly against the extension.
