### ISSUE TITLE
search previous (shift+enter) not working in markdown (.md) files only

### ISSUE THREAD

**Issue by j9108c** [microsoft/vscode#110127]
1. open a markdown (.md) file with duplicate text in it.
2. press ctrl+f to search. type a duplicate word.
3. press shift+enter to search previous.

expected: jump to search previous result.
actual: nothing happens.

from the few ive checked, this only happens in markdown (.md) files or files that have been associated as markdown.

**Comment by roblourens** [comment]
Please run the command "Toggle Keyboard Shortcuts Troubleshooting", try again, and share the log output

**Comment by j9108c** [comment]
thanks, that helped me find the issue. it was an extension Markdown Preview Enhanced which replaced the shift+enter keybinding. i'll close the issue.
