### ISSUE TITLE
gitignore glob "something*.txt" does not grey out "something.txt" in the file browser

### ISSUE THREAD

**Issue by joshua-maros** [microsoft/vscode#110187]
Issue Type: <b>Bug</b>

- Create a git repository in the current folder
- Add the line "something*.txt" to .gitignore
- Create files "something.txt", "something1.txt", "something asdfasdf.txt"
- All of these files are ignored by git, but only the last two are greyed-out in the file browser to indicate that they are ignored.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 2521)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.65GB (1.53GB free)|
|Process Argv|--crash-reporter-id 0f8823ef-98eb-422d-acde-0c09b31728bc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ron|a5h|0.6.0
glsl-canvas|cir|0.2.11
exac-syntax|cod|1.0.1
nodespeak-language-support|cod|0.0.2
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.16.0
flutter|Dar|3.16.0
gitlens|eam|10.2.3
vscode-open-in-application|fab|1.0.5
chuck|for|0.2.1
godot-tools|gee|1.1.2
r|Iku|1.5.2
latex-workshop|Jam|8.13.2
mips|kda|0.0.5
Lua|key|0.0.9
vscode-lua-format|Koi|1.3.6
reflow-markdown|mar|2.1.0
rainbow-csv|mec|1.7.1
python|ms-|2020.10.332292344
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
cpptools|ms-|1.1.0
hexeditor|ms-|1.3.0
mono-debug|ms-|0.16.2
gradle-language|nac|0.2.3
exa-syntax-highlighting|piz|1.2.0
material-icon-theme|PKi|4.4.0
vscode-unitymeta|PTD|0.0.7
java|red|0.70.0
rust|rus|0.7.8
crates|ser|0.5.3
shader|sle|1.1.4
vscode-hexdump|sle|1.8.1
language-pde|Tob|1.4.6
vscode-lldb|vad|1.6.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-maven|vsc|0.25.0
vim|vsc|1.17.1
pestfile|xor|0.0.2

(3 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
I can't reproduce:

![image](https://user-images.githubusercontent.com/22350/98530325-0b420880-227f-11eb-8d65-9bf766643642.png)

If you restart VS Code are the changes picked up?

**Comment by joshua-maros** [comment]
Yeah, it looks like the problem has gone away. My apologies, I thought I had tried restarting before.
