### ISSUE TITLE
Keybinding "ctrl alt -" works on alternate hits 

### ISSUE THREAD

**Issue by magdumnikhil** [microsoft/vscode#110138]
Issue Type: <b>Bug</b>

I have the following user-defined keybinding

```
{
  "key": "ctrl+alt+oem_minus",
  "command": "workbench.action.navigateBack"
}
```

When this combination is pressed continuously (Holding ctrl+alt and just press - again and again) to go back multiple locations, the action happens on alternate hits, and on other alternate hits, it prints the '-' character instead.

This does not happen when the keybinding is changed to

```
{
  "key": "ctrl+alt+numpad_subtract",
  "command": "workbench.action.navigateBack"
}
```

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.62GB free)|
|Process Argv|--crash-reporter-id cbf5af01-9ac6-414e-a2a5-d597132ecd40|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.19.65.95|
|OS|Linux x64 5.4.0-52-generic|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4071)|
|Memory (System)|62.68GB (4.22GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|11.3.1
arm|dan|1.4.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.51.1
vcast-lang|Pat|0.2.0
linkerscript|Zix|1.0.1
asciidoctor-vscode|asc|2.8.4
atlascode|atl|2.8.3
codealignment-vscode|cpm|2.0.19
doxdocgen|csc|1.1.0
gitlens|eam|10.2.3
plantuml|jeb|2.13.14
python|ms-|2020.10.332292344
vscode-pylance|ms-|2020.11.0
cpptools|ms-|1.1.0
hexeditor|ms-|1.3.0
vscode-yaml|red|0.12.0
tmlanguage|Tog|0.9.0
pdf|tom|1.1.0

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
@magdumnikhil `Ctrl+Alt+` is used on many keyboard layouts as a substitute for `AltGr+`. What keyboard layout are you using?

**Comment by magdumnikhil** [comment]
I'm using "English (India) QWERTY" layout.
Observed that when using "US QWERTY" layout, the mentioned issue does not reproduce

**Comment by alexdima** [comment]
@magdumnikhil I can reproduce, but I cannot explain it. We call `e.preventDefault()` on the `keydown` event, which should prevent any input. So AFAICT we are doing the corrent thing.

VS Code is built with Electron, which is built with Chromium. I have created a separate test page at https://jsfiddle.net/zfpLywxe/ and I can also reproduce in Chrome, but **not in Firefox**. I suggest that you please create an issue directly against Chromium at https://bugs.chromium.org/p/chromium/issues/list and link to the issue here.
