### ISSUE TITLE
Unable to Debug Typescript: The terminal process "C:\WINDOWS\System32\wsl.exe -e npm run build" failed to launch

### ISSUE THREAD

**Issue by harindaka** [microsoft/vscode#110164]
I receive the following error when trying to debug my typescript project

```
The terminal process "C:\WINDOWS\System32\wsl.exe -e npm run build" failed to launch (exit code: 1).
```

VSCode Version: 
Version: 1.51.0 (system setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

OS Version: Windows 10

Steps to Reproduce:

1. Create a Typescript (Node) project with the following configuration
2. Click the run button to start debugging

.vscode/launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Debug",
            "program": "${workspaceFolder}\\src\\app.ts",
            "preLaunchTask": "npm: build",
            "sourceMaps": true,
            "smartStep": true,
            "internalConsoleOptions": "openOnSessionStart",
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ]
        }
    ]
}
```
.vscode/settings.json
```
{
    "typescript.tsdk": "node_modules\\typescript\\lib"
}
```

package.json

```
{
    "name": "ts-sample",
    "version": "1.0.0",
    "description": "",
    "main": "dist/src/app.js",
    "scripts": {
      "start": "node dist/src/app.js",
      "prestart": "npm run build",
      "build": "tsc",
      "test": "echo \"Error: no test specified\" && exit 1"    
    },
    "repository": {
      "type": "git",
      "url": ""
    },
    "author": "",
    "license": "ISC",
    "bugs": {
      "url": ""
    },
    "homepage": "",
    "devDependencies": {
      "@types/express": "^4.17.1",
      "@typescript-eslint/eslint-plugin": "^4.4.0",
      "@typescript-eslint/parser": "^4.4.0",
      "eslint": "^7.11.0",
      "remove": "^0.1.5",
      "tslint": "^6.1.3",
      "typescript": "^4.0.5"
    },
    "dependencies": {
      "express": "^4.17.1",
      "inversify": "^5.0.1",
      "json-merge-patch": "^1.0.1",
      "reflect-metadata": "^0.1.13"    
    }
  }
```

tsconfig.json

```
{
  "compilerOptions": {      
    "esModuleInterop": true,            
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./src",
    "target": "es2017",
    "moduleResolution": "node",
    "module": "commonjs",
    "lib": ["es2017", "dom"],
    "types": ["reflect-metadata"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "resolveJsonModule": true
  },
  "lib": ["es2017"],
  "include": [
    "./src/**/*.ts",
    "./**/config*.json"
  ],
  "exclude": [ 
    "./dist/**/*",     
    "./node_modules"
  ]
}
```

All the npm related commands in the package.json such as `npm build`, `npm start` etc. work fine from the wsl bash prompt

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@harindaka are you debugging your project in WSL?
Via VS Code's "Remote Development" and "Remote - WSL" extensions?

**Comment by harindaka** [comment]
@weinand No. I do run commands like `npm start` via WSL prompt, which work correctly, but didn't setup any remote debugging to my knowledge. Looks to me like vscode is trying to run the project outside my "working WSL context" when running it via the vscode debug option.

**Comment by harindaka** [comment]
I've used nvm to set the path to my node sdk. Could this be the reason why vscode seems to have issues running npm commands?

**Comment by weinand** [comment]
@harindaka does debugging work if you comment out the "preLaunchTask" property in your launch config?

**Comment by harindaka** [comment]
@weinand yes it does work though I need to do a manual `npm run build` beforehand if the js isn't already generated by `tsc`

**Comment by weinand** [comment]
@harindaka thanks for the info.
That means that this is not a debug issue but a task issue.

**Comment by superhuai** [comment]
```bash
The terminal process "C:\Windows\System32\wsl.exe -e npm run dev:test" terminated with exit code: 1.
```

I also have this problem

**Comment by alexr00** [comment]
@harindaka do you have a tasks.json file?

**Comment by harindaka** [comment]
@alexr00 No I don't have a tasks.json file. How do I create one?

**Comment by alexr00** [comment]
You don't need to create a tasks.json, I was just looking for more information that might help to figure out what's going on. Do you use nvm?

**Comment by superhuai** [comment]
```js
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "dev:test",
			"path": "src/main/js/",
			"problemMatcher": [],
			"label": "npm: dev:test - src/main/js",
			"detail": "cross-env PORT=8080",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"runOptions": {
        "runOn": "folderOpen"
      }
		}
	]
}
```

**Comment by harindaka** [comment]
@alexr00 Yes I use nvm

**Comment by alexr00** [comment]
@harindaka can you share your user settings.json ?

**Comment by bali-ibrahim** [comment]
I am having the same issue as in If I set the default shell to git-bash my script works but if wsl2 it does not.

**Comment by harindaka** [comment]
@alexr00 see below

%APPDATA%\Code\User\settings.json
```
{
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",
    "window.zoomLevel": 0,
    "editor.largeFileOptimizations": false,
    "typescript.updateImportsOnFileMove.enabled": "always"
}
```

**Comment by alexr00** [comment]
@harindaka I think the problem is that nvm adds something into your shell start up scripts. Tasks runs a non-login, non-interactive shell, so your .bashrc and profile files wont be run. 

Can you try creating a tasks.json (command Configure Task and then select any of the tasks there to create the file) and adding this task:
```
		{
			"type": "shell",
			"problemMatcher": [],
			"command":"echo $PATH",
			"label": "echo the path"
		}
```
Does the output of that task include the path to npm?

**Comment by superhuai** [comment]
> Executing task: echo $PATH <

$PATH

**Comment by harindaka** [comment]
@alexr00 ok my tasks.json is 

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"problemMatcher": [],
			"command":"echo $PATH",
			"label": "echo the path"
		}
	]
}
```

Output:
```
> Executing task: echo $PATH <

$PATH

Terminal will be reused by tasks, press any key to close it.
```

That does not seem right :(

**Comment by alexr00** [comment]
Ah sorry @harindaka, looks like there are some interesting properties of wsl that mean that you must use your _Windows_ path. Can you try this task?
```
                {
			"type": "shell",
			"problemMatcher": [],
			"command":"echo %path%",
			"label": "echo the path"
		}
```
Can you also try these tasks?
```
                {
			"type": "shell",
			"problemMatcher": [],
			"command":"which npm",
			"label": "which npm"
		},
                {
			"type": "shell",
			"problemMatcher": [],
			"command":"which nvm",
			"label": "which nvm"
		}
```

**Comment by harindaka** [comment]
@alexr00 please see output below

Output for: "echo the path"
```
> Executing task: echo %path% <

%path%

Terminal will be reused by tasks, press any key to close it.
```

Output for: "which npm"
```
> Executing task: which npm <

/mnt/c/Program Files/nodejs/npm

Terminal will be reused by tasks, press any key to close it.
```

Output for: "which nvm"
```
> Executing task: which nvm <

The terminal process "C:\WINDOWS\System32\wsl.exe -e which nvm" failed to launch (exit code: 1).

Terminal will be reused by tasks, press any key to close it.
```

**Comment by alexr00** [comment]
@harindaka this is suspicious to me:

> Output for: "which npm"
```
> Executing task: which npm <
/mnt/c/Program Files/nodejs/npm
Terminal will be reused by tasks, press any key to close it.
```

I would expect `which npm` to return the path to npm installed in your linux distro. You say you use nvm. Is this nvm for Windows or do you use it in your linux distro? 

At this point, I'm not sure we will figure out what's going on other than there is something about your setup which doesn't work (which is something we've seen with nvm + tasks before). To get things working for you, I'd recommend you change your setup to one of the following:

1. If you don't need to use wsl as your shell for tasks, change the setting `terminal.integrated.automationShell.windows` to cmd or powershell.
2. Or, if you do need to use wsl, try using the [Remote WSL extension](https://code.visualstudio.com/docs/remote/wsl#_getting-started). That is the well supported way to use wsl with VS Code.

Will one of those options work for you?

**Comment by harindaka** [comment]
@alexr00 Thank you. Using the Remote WSL extension worked! Typing `code .` from WSL bash as mentioned in the article did not work. However clicking the green icon on the bottom left and opening the folder that way did work. Hope this helps others.
