### ISSUE TITLE
Intellisense not working in Jupyter notebook

### ISSUE THREAD

**Issue by alone-sHaDoW** [microsoft/vscode#110237]
- VSCode Version: 1.51.0
- OS Version: Windows 10

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/67627458/98563699-7e746a80-22d1-11eb-84b7-d36cb166ce41.png)

2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kieferrm** [comment]
\extPython
