### ISSUE TITLE
Test: contribute actions to folders in the explorer

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11025]
- [ ] any OS **@alexandrudima**

In #10433 we introduced a new context key `explorerResourceIsFolder`  that extension writers can use to contribute actions to folders in the explorer
* Write an extension and verify you can add a functional action to a folder in the explorer

**Comment by alexandrudima** [comment]
Verified by adding the following to typescript's package.json:

```
		"menus": {
			"explorer/context": [
				{
					"when": "explorerResourceIsFolder",
					"command": "typescript.reloadProjects"
				}
			]
		}
```

And the command only shows on folder context menu entries.
