### ISSUE TITLE
CLI help: consider to separate --file-uri and --folder-uri

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#110206]
I find these two in the wrong spot:

![image](https://user-images.githubusercontent.com/900690/98516096-569eeb80-226c-11eb-80b4-18bb6a985825.png)

I think for a user it is not easy to understand what `--file-uri` or `--folder-uri` does and when it should be used. My understanding is that the use case is for remote scenarios only. As such I suggest to make this a separate section in the help output which specifically talks about remotes and maybe gives an example how such a remote URI would look like?

**Comment by aeschli** [comment]
Given that `--help` does not document all parameters, only the important ones, I'm in favor of removing both `--file-uri` or `--folder-uri`.

For remote we now have the friendlier syntax `--remote wsl /home/me/that` , but given that this is only available when remote extensions are installed, I think this should not be part of the default `--help` but of the remote extensions documentation.

**Comment by aeschli** [comment]
@bpasero Ok for you?

**Comment by aeschli** [comment]
I pushed the change, but if you disagree I'm happy to work on it.

**Comment by bpasero** [comment]
@aeschli yeah I feel this is the right change, thanks 👍
