### ISSUE TITLE
Context key lost focus in explorer

### ISSUE THREAD

**Issue by tanftw** [microsoft/vscode#110208]
- VSCode Version: 1.51.0, 1.52.0 - insiders
- OS Version: Windows 10, 20H1

Steps to Reproduce:

1. Navigate to any file, folder in Explorer by keyboard.
2. Press Context key, and select any item via keyboard, for example, Rename.

-> VSCode is lost focus to selected item and context menu is renaming other file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/109870
