### ISSUE TITLE
Automatic update fails

### ISSUE THREAD

**Issue by sdbip** [Microsoft/vscode#11028]
- VSCode Version: 1.3.1
- OS Version: Mac OS X El Capitan 10.11.6 
- Note: I'm logged on as a "standard" user and need to logon as administrator to install

1. I received the notification for a new version (1.4.0)
2. Quit and restarted VS Code
3. …still running the same version.
4. There was never any dialog asking for my password nor the administrator password

Had to download the app from the web and manually replace the old version.

**Comment by Alirezanet** [comment]
i had same problem before

**Comment by joaomoreno** [comment]
#3520
