### ISSUE TITLE
Dirty file dialog has Cancel button in the middle

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#110227]
![image](https://user-images.githubusercontent.com/22350/98550197-17888e80-229c-11eb-83d9-c5f38cff7734.png)

**Comment by bpasero** [comment]
Looks like this is standard ubuntu behaviour:

![image](https://user-images.githubusercontent.com/900690/98553267-be225e80-229f-11eb-970f-ee7d86e7247c.png)
