### ISSUE TITLE
[css] MDN references link not showing up for some CSS properties

### ISSUE THREAD

**Issue by mikelei8291** [microsoft/vscode#110279]
- VSCode Version: 1.51.0
- OS Version: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. Hover the cursor on top of some CSS properties. For example, [`justify-content`](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content), [`align-content`](https://developer.mozilla.org/en-US/docs/Web/CSS/align-content), and more.
2. No MDN references link shows up:

![Image](https://user-images.githubusercontent.com/9620335/98621320-e68d7580-22fe-11eb-9d99-340c4f4566d4.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by thenomadicmann** [comment]
I'm also seeing this issue still. The correct justify-content options are not being displayed: https://www.dropbox.com/s/hb0hvpq3ra5i4jv/oo04fm6d.png?raw=1

**Comment by mikelei8291** [comment]
Looks like this got fixed already.
