### ISSUE TITLE
The native notebook UI doesn't allow user to click links on the last line of a markdown cell

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode#110274]
Version: 1.52.0-insider (user setup)
Commit: 24b28f57be22fe3029cb17a1dd72d8d9c2d6468b
Date: 2020-11-06T05:43:01.017Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a new Notebook
2. Add a markdown cell
3. have a link `[here](https://www.bing.com/)` on the last line of the markdown

Result:
Can't click the link because the + Code and + Markdown buttons are on the way.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by rebornix** [comment]
The in-between cell toolbar is too tall and covers part of the markdown preview, introduced by https://github.com/microsoft/vscode/commit/b0c6e84bee616b266a979a95019513c3992e87d3 

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/876920/98855901-a0750680-2411-11eb-9b69-a423a2bd4c0d.png">

**Comment by roblourens** [comment]
We can have a div that you can click through using `pointer-events: none`, but it can't react on hover and also be clicked through. So I think we will have to do some weird stuff with JS implementing a hover in order to have both.

**Comment by rebornix** [comment]
right, we might need to customize `hover`

**Comment by misolori** [comment]
Reduced the height of the add cell toolbar since the hover trigger isn't required anymore (now that #111063 is fixed) so it won't overlap on first line links:

![image](https://user-images.githubusercontent.com/35271042/102550061-09cfe100-4072-11eb-9081-e311ae427985.png)

![image](https://user-images.githubusercontent.com/35271042/102550094-16543980-4072-11eb-808b-ce2731a80491.png)

**Comment by misolori** [comment]
This also fixes an issue where you previously couldn't delete multiple cells because the add new cell toolbar was in the way (@kieferrm brought this up). Now you can click to your heart's content:

https://user-images.githubusercontent.com/35271042/102550645-02f59e00-4073-11eb-9e0b-f2efb9c0aec7.mp4

**Comment by roblourens** [comment]
Yesss this is so much better than the other potential fix

**Comment by roblourens** [comment]
Procrastinating fixing this paid off
