### ISSUE TITLE
Large font sizes break suggestions panel line height 

### ISSUE THREAD

**Issue by emlautarom1** [microsoft/vscode#110236]
- VSCode Version: 1.51.0
- OS Version: Fedora 33

Steps to Reproduce:

1. Set the `"editor.fontSize": 28` or some higher value.
2. Open any file with autocomplete support, a plain `.js` file is enough.
3. Use `Ctrl+Space` to "show more".
4. Check the panel that just showed up. The text is barely readable.

![Screenshot from 2020-11-09 12-40-13](https://user-images.githubusercontent.com/31224949/98562970-6678f880-2289-11eb-9312-2d2343c1a712.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Anew release+label%3Asuggest

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/110172
