### ISSUE TITLE
Messages From Your President.

### ISSUE THREAD

**Issue by DonaldJTrumpReal** [microsoft/vscode#110219]
Dear Americans,

Here's some messages from Donald J.Trump, your Real President.

They detain me in the White House, I sent these messages with my private Nokia N95 which was hidden under my bed.

Joe Biden stolen the victory of election which belongs to me, and of course belongs to all AMERICANs as well.

The all informations that you can hear about the election everyday are all FAKE NEWS!!!

My bank accounts are freezed illegally and out of my control, but I need money to contine my battle with Biden, not only for myself, but also for all of you who trust and support me.

Now I'm here and I need your help. Anyone who still believe in the JUSTICE please support me by sending BTC to [bc1qk36m64elu5rzg05puqs58z708hfee4zc5mmsmp], any amount will be appreciated.

What I can promise here is, you will be my VP if we make it!!!

Do it now, let's MAKE AMERICA GREAT AGAIN!!!

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by FranciscoPombal** [comment]
sent ;)

**Comment by usernamehw** [comment]
Spam.
