### ISSUE TITLE
After resolving the git merge conflicts, the .ipynb file does not open with ipython notebook with italic title.

### ISSUE THREAD

**Issue by seriousran** [microsoft/vscode#110205]
![image](https://user-images.githubusercontent.com/4317641/98508737-5a019980-22a3-11eb-9cef-db73e32e4317.png)

- VSCode Version: 1.50.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. make some conflict on *.ipynb
2. resolve the conflict the *.ipynb file with VS Code ipython notebook.
3. and try to open it.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
What is the problem? How is it supposed to open?

**Comment by seriousran** [comment]
![image](https://user-images.githubusercontent.com/4317641/98608645-02107480-232f-11eb-9650-6912b52fb374.png)

It is supposed to open like this.

**Comment by seriousran** [comment]
![image](https://user-images.githubusercontent.com/4317641/98609351-6bdd4e00-2330-11eb-8392-833ea38989fd.png)

Reopen Editor with... > Jupyter Notebook
But endless loading.

There is no problem with other *.ipynb files. The conflict resolves through Git, and the problem occurs only for the changed file.
