### ISSUE TITLE
Screen flickering

### ISSUE THREAD

**Issue by stevengogogo** [microsoft/vscode#110220]
Issue Type: <b>Bug</b>

The screen flicking when using dark theme

![截圖 2020-11-09 下午7.57.33](https://i.imgur.com/JFDjrLI.jpg)

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 70b991c7-7b94-4289-950a-8b720d0b9979|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.1
latex-workshop|Jam|8.13.2
python|ms-|2020.10.332292344
cpptools|ms-|1.1.0
markdown-preview-enhanced|shd|0.5.13
vscodeintellicode|Vis|1.2.10

(1 theme extensions excluded)

</details>

**Comment by stevengogogo** [comment]
<img width="509" alt="截圖 2020-11-11 下午9 51 28" src="https://user-images.githubusercontent.com/29009898/98819668-1b690c00-2468-11eb-9768-04eef017fc78.png">

I tried the older version. Then everything works fine.

**Comment by deepak1556** [comment]
Is this still an issue with latest stable `1.74` ?

**Comment by stevengogogo** [comment]
> Is this still an issue with latest stable `1.74` ?

It works fine with `1.74` now.
