### ISSUE TITLE
Request Features : Multi Selection

### ISSUE THREAD

**Issue by mbougarne** [Microsoft/vscode#11029]
Hello :smile: 

I don't know if this is requested before or not, but I hope to think about adding this feature with the next version.

- Multi selection 

Thank You.

**Comment by sandy081** [comment]
@mbougarne We already support multi selection in our editor. Refer to our documentation for [Multiple Selections](https://code.visualstudio.com/docs/editor/editingevolved#_multiple-selections)

If you are looking for more, please add more details to your requirement.

Thanks
