### ISSUE TITLE
Terminal lags while scrollling when printing long line

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#110212]
- VSCode Version: stable and from sources

Steps to Reproduce:

1. Open terminal and run a program that prints a really long line. For example `console.log([...Array(4000).keys()].join(','));`
2. Hover the mouse over the text in the terminal and start scrolling up and down
3. :bug: observe the terminal lags while scrolling

**Comment by meganrogge** [comment]
@jeanp413 I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
![recording (29)](https://user-images.githubusercontent.com/29464607/98570476-5866b000-2268-11eb-8ef0-3fda5a3e2655.gif)

**Comment by jeanp413** [comment]
@meganrogge it's an issue in the terminal not in the debug console

**Comment by meganrogge** [comment]
@jeanp413 I see. Could you pls send a gif of this? https://gifcap.dev/

**Comment by jeanp413** [comment]
Sure, notice int the gif  I'm scrolling up
![terminal_lag](https://user-images.githubusercontent.com/25115070/98573404-d5a01e00-2284-11eb-9efa-bf1fbc1cf1ef.gif)

**Comment by meganrogge** [comment]
@jeanp413 I verified that your PR fixes this bug 👍 , but will await @Tyriar 's approval of the changes.
