### ISSUE TITLE
Cannot connect to Extensions market place

### ISSUE THREAD

**Issue by ziggy6792** [microsoft/vscode#110289]
- VSCode Version: 1.51.0 
- OS Version:  Catalina 10.15.5

## My Setup

Mac osx : `Catalina 10.15.5`

VS code
```
Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:14:40.758Z (4 days ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0
```

## Steps to reproduce

I cannot connect to Extensions market place using vscode, here is the [error message][1]

If I open developer tools (`F1 > Toggle Developer Tools`) and inspect the [request to marketplace][2] it says `net::ERR_ACCESS_DENIED`

But I can copy out that request as curl (`right click -> copy and curl`) and it works fine from my terminal

```
curl 'https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery' \
  -H 'X-Market-User-Id: f8427084-f361-48f0-b662-fabf315667cf' \
  -H 'Accept: application/json;api-version=3.0-preview.1' \
  -H 'Referer: ' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.51.0 Chrome/83.0.4103.122 Electron/9.3.3 Safari/537.36' \
  -H 'X-Market-Client-Id: VSCode 1.51.0' \
  -H 'Content-Type: application/json' \
  --data-binary '{"filters":[{"criteria":[{"filterType":8,"value":"Microsoft.VisualStudio.Code"},{"filterType":10,"value":"py"},{"filterType":12,"value":"4096"}],"pageNumber":1,"pageSize":50,"sortBy":0,"sortOrder":0}],"assetTypes":[],"flags":946}' \
  --compressed
```

Also if I open (`F1 > Toggle Developer Tools`) and go to the console tab and try to do any other fetch e.g
`await fetch("https://randomuser.me/api/")` then I get [the same error][3] (so it looks like my vscode is having a problem connecting to the internet in general)

### Things that didn't work:

 - Restart Mac
 - Completely remove vscode :
   https://stackoverflow.com/questions/42603103/how-to-completely-uninstall-vscode-on-mac#:~:text=Just%20drag%20VS%20Code%20from,click%20on%20the%20Remove%20button.
 - Change DNS: https://github.com/microsoft/vscode/issues/79604

### Workaround:
Using the VScode insider build works fine, I can search and install extensions no problem (https://code.visualstudio.com/insiders/)

Any help greatly appreciated.

Thanks

  [1]: https://i.stack.imgur.com/8fcBX.png
  [2]: https://i.stack.imgur.com/Lwesj.jpg
  [3]: https://i.stack.imgur.com/L4fKW.jpg

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Can you provide network log from vscode by launching the app from command line with `code --log-net-log=<some-absolute-path>/netlog.json` , perform the failing network requests.

**Comment by ziggy6792** [comment]
> Can you provide network log from vscode by launching the app from command line with `code --log-net-log=<some-absolute-path>/netlog.json` , perform the failing network requests.

[netlog.json.zip](https://github.com/microsoft/vscode/files/5577181/netlog.json.zip)

Thanks :)

**Comment by ziggy6792** [comment]
Hey any update on this?

Thanks

**Comment by deepak1556** [comment]
Sorry missed the comments, is this still an issue with stable builds ?

Based on the netlog it would seem the application network access might be blocked by some antivirus or firewall on your system, please check for it. Closing as not actionable from the app side.

```
t=771 [st=0]     +TCP_CONNECT_ATTEMPT  [dt=0]
                  --> address = "13.107.5.93:443"
t=771 [st=0]     -TCP_CONNECT_ATTEMPT
                  --> os_error = 1
t=771 [st=0]   -TCP_CONNECT
                --> net_error = -10 (ERR_ACCESS_DENIED)
```
