### ISSUE TITLE
Multiple selections: disable context detection

### ISSUE THREAD

**Issue by Instagit** [Microsoft/vscode#11027]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 14.04

Steps to reproduce:

Example code:

``` JavaScript
<script>
var testVar1 = "<CURSOR>";
var testVar2 = <CURSOR>;
</script>
```
1. Set language to JavaScript.
2. Place two cursors at `<CURSOR>`
3. Enter something like `\"sometext\"`
4. You end up with

``` JavaScript
<script>
var testVar1 = "\"sometext\";
var testVar2 = \"sometext\";
</script>
```

This may not be the best example, but it shows that typing with multiple cursors has the potential to not do what the user expects (the entered text being the same at all cursor locations) and break things. I think other editors work around this by disabling the context detection when there are multiple cursors.

**Comment by alexandrudima** [comment]
:+1: This has been fixed in the March stable release. All cursors now do the same thing when typing.
