### ISSUE TITLE
"Pinning" a dynamic launch configuration removes comments from launch.json 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#110295]
"Pinning" a dynamic launch configuration(by clicking on the gear icon in the QuickPick) removes comments from launch.json:

![2020-11-10_10-30-17 (1)](https://user-images.githubusercontent.com/1898161/98655500-d77ae780-233f-11eb-84c4-6ad990f3b522.gif)

Adding regular launch configurations via the "Add Configuration..." button does not remove comments:

![2020-11-10_10-32-37 (1)](https://user-images.githubusercontent.com/1898161/98655735-1b6dec80-2340-11eb-9473-c539a377cf2d.gif)

**Comment by isidorn** [comment]
This is a known limitation, dup of https://github.com/microsoft/vscode/issues/99305
There is no api for this in the configuraiton service, thus assigning to backlog.

**Comment by weinand** [comment]
IMO this issue and #99305 are just duplicates of #29453.
You don't have to keep this open and put on backlog.

**Comment by isidorn** [comment]
Ok, closing as duplicate
fyi @sandy081
