### ISSUE TITLE
Change "checkout to" to "switch to"

### ISSUE THREAD

**Issue by kimhmadsen** [microsoft/vscode#110221]
I would suggest replacing the "checkout to..." text in the source control menu to "switch to..."
![image](https://user-images.githubusercontent.com/122740/98521533-d9777480-2273-11eb-9fc4-602da5c06a30.png)

I think this would be more clear what the use cases for this is and it would be inline with
the "switch" command introduced in Git v2.23.

**Comment by joaomoreno** [comment]
I don't think this is a good idea. `git switch` is pretty much unknown by everyone. The confusion arising out of this won't pay off the alignment with git.
