### ISSUE TITLE
Adopt TernarySearchTree#forUris2

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#110241]
This is a follow up from https://github.com/microsoft/vscode/issues/110188

I noticed how recently https://github.com/microsoft/vscode/commit/70a8fc5b231c90629a9b2d917f017b4913821f1f was pushed to create a `TernarySearchTree.forUris<vscode.WorkspaceFolder>(!isLinux)` and https://github.com/microsoft/vscode/pull/110224/files will push a similar change on the main side.

Imho the `TernarySearchTree` somehow needs to respect the capabilities of the registered file system provider for the scheme and should not hardcode via `isLinux` because some workspace folders might come in from contributed file system providers. 

Maybe `IURIIdentityService` should have a method to create a `TernarySearchTree` that knows how to deal with path casing?

**Comment by jrieken** [comment]
> Maybe IURIIdentityService should have a method to create a TernarySearchTree that knows how to deal with path casing?

Unsure about that. IMO we should have something similar to the `ResourceMap` which abstracts away the uri identity service by allowing to pass a `toKey`-function.

**Comment by jrieken** [comment]
- [ ] src/vs/base/common/resources.ts @bpasero 
- [ ] src/vs/platform/files/common/fileService.ts  @bpasero 
- [ ] src/vs/platform/files/common/files.ts  @bpasero 
- [ ] src/vs/platform/workspace/common/workspace.ts @sandy081 
- [ ] src/vs/workbench/api/common/extHostWorkspace.ts @sandy081 
- [ ] src/vs/workbench/contrib/search/common/searchModel.ts @roblourens 
- [ ] src/vs/workbench/services/decorations/browser/decorationsService.ts @jrieken 
- [ ] src/vs/workbench/services/extensions/electron-browser/extensionHostProfiler.ts @jrieken

**Comment by jrieken** [comment]
FYI - I have pushed 3bf2afd which deprecates the `forUris` and adds `forUris2`. The latter must be called with a function that answers the question whether a scheme is case-sensitive for paths or not.

**Comment by jrieken** [comment]
fyi @sandy081 - on the extension host side you can use the `IExtHostFileSystemInfo` to query for the casing capabilities of a scheme

**Comment by jrieken** [comment]
fyi **all** - I have added `IExtUri#ignorePathCasing` which knows whether path casing matters for a scheme or not

**Comment by bpasero** [comment]
@sandy081 assigned you for `vs/base/common/ResourceGlobMatcher` which seems to only be used by markers. I found another one (https://github.com/microsoft/vscode/blob/9382e6375fb1cf026730e0d37056cb3b4ec4e38c/src/vs/workbench/common/resources.ts#L123-L123) which seems to be used by my editor history. Not sure why we have two.

**Comment by sandy081** [comment]
Adopted.

I do not know why there are two `ResourceGlobMatcher`s but moved the one the markers is using into markers contrib.

**Comment by jrieken** [comment]
Thanks everyone
