### ISSUE TITLE
Test: Configuration and environment service cleanup

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11023]
- [x] win **@isidorn**
- [x] os x **@weinand**
- [x] Linux **@joaomoreno**

In order to work on extension API for configuration management, quite some debt in `configuration` land and `environment` handling (cli) was removed and lots of code refactored. We should make sure that we did not introduce regressions while doing so in the areas touched:
* All our command line arguments passed to VS Code work as before and work for either no instance running or an existing instance running
* You can install extensions from the command line
* User settings are being picked up and apply live throughout the UI
* Workspace settings are being picked up and apply live throughout the UI
* Debug an extension and verify the extension settings it defines are picked up properly within the extension

**Comment by isidorn** [comment]
> Debug an extension and verify the extension settings are picked up properly within the extension

@bpasero You mean the workspace and user settings inside the window where the extension is launched? Or what extension settings are you refering to?

**Comment by bpasero** [comment]
@isidorn settings defined by the extension itself.
