### ISSUE TITLE
code-workspace files not working

### ISSUE THREAD

**Issue by BrianThorChristensen** [microsoft/vscode#110230]
VS Code version: Code 1.51.0
OS version: Windows 10 Enterprise 20H2

When I open VSCode through a code-workspace file, it seems like VSCode is unable to find the .vscode folder or at least some files in it. The settings are not read and it is unable to find any configurations in launch.json.

If I open VSCode in a new window and open the same folder it works.

I have downgraded to 1.50.1. On this version workspace files work as expected.

**Comment by sandy081** [comment]
Can you please try opening the folder containing `.vscode` folder directly and let us know if it works? 
Also, can you please let us know how your `.code-workspace` looks like?

**Comment by BrianThorChristensen** [comment]
Thanks for getting back to me.
I am not sure what you mean by opening the folder directly. I have tried to open VSCode and then open the project folder and that works just fine. BTW It is a singe folder workspace.
We only have problems when I open the project using a code-workspace file. We have reproduced the problem on all our workstations and all our projects.

Our code-workspace file is currently placed in a subfolder but I have tried to move it to the root and use absolute filepaths but none of that helped. It looks like this:
{
	"folders": [
		{
			"path": ".."
		}
	],
	"settings": {
		"git.ignoreMissingGitWarning": false,
		"team.showWelcomeMessage": false,
		"tfvc.proxy": "https://camp365.visualstudio.com/",
		"tfvc.restrictWorkspace": true,
		"todo-tree.general.tags": [
			"TODO",
			"FIXME",
			"UPGRADE",
			"APP"
		]
	}
}

**Comment by sandy081** [comment]
So can you please confirm that you are able to open the above `code-workspace` file and see the folder in the file explorer view and navigating files and opening files work. Only that workspace folder (.vscode) settings and launches are not applied ?

And all your work stations are on Windows and it works as expected in previous version (`1.50`) ?

I do not remember I did any changes in this area last milestone, @isidorn By any chance is this a dup of https://github.com/microsoft/vscode/issues/110188

**Comment by isidorn** [comment]
@sandy081 might be. That change touches various areas. I think the best would be if the user tries to reproduce with an insiders from tomorrow which should hopefully have a fix for it. Or to try it in a couple of days when we release our stable recovery release.

**Comment by BrianThorChristensen** [comment]
Yes, the workspace opens and contains all the files and folders including .vscode.
All files and folders also open and shows the correct content.
In fact the tasks.json file seems to work.
We all use Windows workstations and they all work as expected on version 1.50.1.

**Comment by isidorn** [comment]
@BrianThorChristensen can you reproduce with https://code.visualstudio.com/insiders/
