### ISSUE TITLE
the function of keyboard shortcuts Ctrl+F5 is not same as the menu run -> Ctrl+F5 

### ISSUE THREAD

**Issue by kinglionsz** [microsoft/vscode#110283]
Issue Type: <b>Bug</b>

open a python file, use keyboard shortcuts Ctrl+F5, it will dispaly cmake/GCC list menu.

<img width="632" alt="屏幕截图 2020-11-10 142443" src="https://user-images.githubusercontent.com/51827261/98636199-56cce300-2361-11eb-91f3-c60c7fd292ea.png">

the following is ok.

<img width="493" alt="屏幕截图 2020-11-10 142613" src="https://user-images.githubusercontent.com/51827261/98636195-55031f80-2361-11eb-8a43-1f21633ed0fd.png">

pls check the issues. tks.

VS Code version: Code - Insiders 1.52.0-insider (24b28f57be22fe3029cb17a1dd72d8d9c2d6468b, 2020-11-06T05:43:01.017Z)
OS version: Windows_NT x64 10.0.20251
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz (4 x 2128)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.72GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+ubuntu/mnt/e/CodeSources/learn/Python/Python376/Python%E7%BC%96%E7%A8%8B%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E5%AE%9E%E8%B7%B5 --remote=wsl+ubuntu --crash-reporter-id 3d6cc155-76f5-4808-bc32-87cd8cc8aaca|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz (4 x 2127)|
|Memory (System)|3.77GB (2.14GB free)|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
pythonsnippets|frh|1.0.2
vscode-csharp-snippets|jor|0.5.0
vscode-language-pack-zh-hans|MS-|1.51.2
remote-wsl|ms-|0.51.1
material-icon-theme|PKi|4.4.0
python-extended-snippets|tus|0.0.1
jinja|who|0.0.8
add-reference|adr|1.0.2
Bookmarks|ale|11.4.0
code-gnu-global|aus|0.2.2
vscode-django|bat|1.0.0
cmake-format|che|0.6.11
npm-intellisense|chr|1.3.1
vscode-markdownlint|Dav|0.37.2
py-pack|dav|1.2.0
python-preview|don|0.0.4
githistory|don|0.6.13
python-extension-pack|don|1.6.0
gitlens|eam|10.2.3
vscode-npm-script|eg2|0.3.13
eppz-code|epp|1.2.52
vscode-nupkg|eri|1.0.1
vs-sharper|ese|0.2.0
git-project-manager|fel|1.7.1
code-runner|for|0.11.1
vscode-test-explorer|hbe|2.19.3
githd|hui|2.2.4
format-python-docstrings|ian|1.2.1
python-coding-conventions|igr|0.0.4
csharp-winform-designer|iro|1.1.1
csharpextensions|jch|1.3.1
nuget-reverse-package-search|jes|0.1.68
nbpreviewer|jit|1.2.2
vscode-nuget-package-manager|jmr|1.1.6
vsc-python-indent|Kev|1.12.0
csharpfixformat|Leo|0.0.84
vscode-python-test-adapter|lit|0.6.2
MagicPython|mag|1.1.0
dotnet-core-commands|mat|1.0.6
git-graph|mhu|1.27.0
vscode-language-pack-zh-hans|MS-|1.51.2
csharp|ms-|1.23.5
python|ms-|2020.10.332292344
vscode-pylance|ms-|2020.11.0
cmake-tools|ms-|1.5.1
cpptools|ms-|1.1.0
python-docs|Muk|0.8.3
autodocstring|njp|0.5.3
quicktype|qui|12.0.46
bash-debug|rog|0.3.9
trailing-spaces|sha|0.3.1
code-spell-checker|str|1.9.2
python-editing-terminal|ted|1.0.5
cmake|twx|0.0.17
snippet-creator|vin|1.1.0
vscodeintellicode|Vis|1.2.10
gitblame|wad|6.0.0
jinja|who|0.0.8
markdown-all-in-one|yzh|3.3.0

(5 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
It's possible to have multiple commands bound to the same keyboard shortcut, with different conditions for them to activate. You can manage your keyboard shortcuts through the command "Open Keyboard Shortcuts"
