### ISSUE TITLE
Using "Show Local" file system option produces a nonexistent path

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode#110264]
- VSCode Version: Code - Insiders 1.52.0-insider (24b28f5, 2020-11-06T05:39:23.276Z)
- OS Version: Darwin x64 19.6.0
- Remote OS version: Linux x64 5.4.0-1031-azure

Steps to Reproduce:
Via a VS Code extension running in remote SSH.
1. Use `vscode.window.showOpenDialog` to get a file or folder path from the local machine using "Show Local" 
2. Reference that path from the remote machine and it does not exist

While behavior is expected since that local path doesn't exist on the remote machine, I think there should be some way of handling it in the API because it complicates scenarios that worked fine in VS Code running locally.

Does this issue occur when all extensions are disabled?: N/A

**Comment by alexr00** [comment]
I think when extensions use `vscode.window.showOpenDialog` we should simple not offer "Show Local".
