### ISSUE TITLE
Error exception C0000006

### ISSUE THREAD

**Issue by alfredomusumeci** [microsoft/vscode#110228]
Hello,
I am experiencing this very strange problem when trying to install Visual Studio Code on Windows: I get this exception error right when launching the installation file. I can't go any further.
I had VSCode in the past already and I have then uninstalled it. May these two things be connected?

**Comment by joaomoreno** [comment]
Can you share a screenshot?

**Comment by alfredomusumeci** [comment]
![Screenshoot](https://user-images.githubusercontent.com/61691516/98667055-cdf47e00-2345-11eb-9bed-ab386308b04e.PNG)
This is it. 
The installation doesn't even start, this is the first message I get.

**Comment by joaomoreno** [comment]
Can you provide details on your system? OS, version, etc.

**Comment by joaomoreno** [comment]
Related: https://stackoverflow.com/questions/1317886/external-exception-c0000006

**Comment by alfredomusumeci** [comment]
![info](https://user-images.githubusercontent.com/61691516/98705646-d6fd4380-2375-11eb-90a9-ab81fd23822d.PNG)
Here the details on my system.
As I said, it was working before, then after I uninstalled it seems impossible to install it again because of this problem, the installation does not even begin.
However, the zip file containing the app, with no installation needed, that works perfectly fine.

**Comment by joaomoreno** [comment]
>However, the zip file containing the app, with no installation needed, that works perfectly fine.

Glad this is an acceptable solution for you!
