### ISSUE TITLE
typescript crash

### ISSUE THREAD

**Issue by vairakkumar-vairaperumal** [microsoft/vscode#110239]
Issue Type: <b>Bug</b>

I am running vscode from WSL and I get this error. Don't know how to reproduce it

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (2.83GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/mnt/c/Users/username/projectfolder --remote=wsl+Ubuntu --crash-reporter-id 67c16343-c493-4df5-98a1-9549166dc60a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2807)|
|Memory (System)|12.37GB (0.55GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2807)|
|Memory (System)|12.37GB (0.55GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2807)|
|Memory (System)|12.37GB (0.55GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.12.0
openssl-configuration-file|gee|0.0.1
intellij-idea-keybindings|k--|0.2.41
vscode-docker|ms-|1.7.0
remote-containers|ms-|0.145.1
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
remote-wsl|ms-|0.50.1
vscode-remote-extensionpack|ms-|0.20.0
HCL|who|0.0.5
vscode-mysql|for|0.4.0
go|gol|0.18.1

</details>

**Comment by mjbvz** [comment]
We can't investigate this without steps to reproduce the problem

/needsMoreInfo
