### ISSUE TITLE
Debug console scrolling glitches

### ISSUE THREAD

**Issue by TheMisir** [microsoft/vscode#110210]
Issue Type: <b>Bug</b>

Scrolling on debug console sometimes glitches like that:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/29130291/98524479-b4452f00-2290-11eb-9da0-39c402c91f23.gif)
[video](https://drive.google.com/file/d/1gJvK4NuiLzfpRExgL-DEQHmNHnn9u5DY/view?usp=sharing)

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.17GB free)|
|Process Argv|--crash-reporter-id c9812d6c-a933-4353-8de0-3d4cf0b1717f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
dart-code|Dar|3.16.0
flutter|Dar|3.16.0
gitlens|eam|10.2.3
vscode-pull-request-github|Git|0.21.0
go|gol|0.18.1
vscode-github|Kni|0.30.4
vscode-docker|ms-|1.7.0
vscode-kubernetes-tools|ms-|1.2.1
remote-containers|ms-|0.148.0
remote-wsl|ms-|0.51.1
vscode-yaml|red|0.12.0
rust|rus|0.7.8

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/107704
