### ISSUE TITLE
Test: New actions to move tabs within a group

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11020]
- [x] any OS **gregvanl**

As per feature request #10291, we added new actions to move tabs in a group left or right.
* Verify this works as expected and you can assign keybindings to these actions
* The command IDs are `workbench.action.moveEditorLeftInGroup` and `workbench.action.moveEditorRightInGroup`

**Comment by gregvanl** [comment]
Note: default key bindings for these actions are set to Ctrl+Shift+PageUp and +PageDown on Windows.
