### ISSUE TITLE
Implement output.reverseAttributes for emmet snippets

### ISSUE THREAD

**Issue by webdog** [microsoft/vscode#110251]
Hello!

Could you please allow for the output.ReverseAttributes to be defined as a user preference setting?

This was implemented to [allow user-defined positioning of attributes](https://github.com/emmetio/expand-abbreviation/issues/16) and was implemented in the current emmet repo [here](https://github.com/emmetio/emmet/blob/6ca3780097d7abd5c59ef3768f4a50023c467548/src/config.ts#L301)

**Why is this important?**

With Bootstrap, all of the generated code samples implement class attributes at the beginning of a tag. For example, a generated [navbar sample from their site](https://getbootstrap.com/docs/4.0/components/navbar/) (As a note, this is how I've generally seen and used bootstrap classes implemented inside a tag), might have a section that looks like this:

```html
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Current</a>
            <a class="dropdown-item" href="#">Next Week</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
```

to add a new anchor with the same syntax, I would want to use the follow emmet syntax: 
`a.dropdown-item[href=#]{Next Month}`
However, the preview generated, and the implementation do not give me the style that I prefer:
![image](https://user-images.githubusercontent.com/960210/98579078-bf459280-2283-11eb-912c-5f1670153829.png)
```html
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Current</a>
            <a class="dropdown-item" href="#">Next Week</a>
            <a href="#" class="dropdown-item">Next Month</a>
            <a class="dropdown-item" href="#">Something else here</a>
</div>
```

Now, I **could** implement a snippet for this specific anchor override, but now if I want to use this style across the codebase with all of my tags that utilize bootstrap, I now have to create a snippets.json file that grows exponentially to cover every use-case.

Since `output.reverseAttributes` solves this behavior, I figured I could do add this override in my code workspace settings, such as

```json
	"settings": {
		"emmet.preferences": {
			"output.reverseAttributes": true
		}
	}
```

But this did not work. `snippets.json` also does not have a supported object for preferences based on [emmet documentation](https://docs.emmet.io/customization/snippets/). I think this might also open a bigger question of "How can VSCode support any arbitrary snippet preference? (There are many from where this specific attribute was implemented) There doesn't seem to be a method to implement this behavior via the regular [preferences.json](https://docs.emmet.io/customization/preferences/) so if I want this behavior today, it seems I would need to fork emmet and vscode, and implement my own custom implementation to enable this feature toggle.

**Comment by rzhao271** [comment]
@webdog thanks for the write-up. I wasn't aware of when output.reverseAttributes would come in handy.

What I do know though, is that VS Code is currently using an older version of Emmet. Once it moves on to the newer version (the one you see at emmetio/emmet), it should be much simpler to get that preference implemented.

I'll keep this issue open in the meantime.

**Comment by webdog** [comment]
@rzhao271 Sounds great! Thanks for the quick response, looking forward to the newer version of Emmet being implemented! 😸

**Comment by jeanp413** [comment]
Created a PR #116088 fixing this
