### ISSUE TITLE
Clicking on tree item twistie now triggers tree item command

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#110257]
Clicking on a tree item's twistie never used to trigger the tree item's command, which imo is highly desirable. This has changed in a recent insiders.

![image](https://user-images.githubusercontent.com/641685/98587679-78ae6300-2298-11eb-825c-44c48b2cc8b7.png)

**Comment by alexr00** [comment]
I don't know what could have happened here, but it appears to be fixed already when running out of source. Maybe @joaomoreno had some tree changes.
