### ISSUE TITLE
Sync disabled because of too many changes

### ISSUE THREAD

**Issue by JCKodel** [microsoft/vscode#110259]
Issue Type: <b>Bug</b>

I'm just experience some settings editing settings.json and saving...

I would not mind a bouncing delay of 15, 30 seconds (immediate while closing the IDE)

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.41GB free)|
|Process Argv|--crash-reporter-id d7bd9aff-64c3-4a22-9a47-8de4cb7b8fe5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
tt-processor|ais|0.8.0
Bookmarks|ale|11.4.0
separators|ale|1.0.2
amphtml-validator|amp|1.1.0
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.16.0
flutter|Dar|3.16.0
gitlens|eam|10.2.3
vscode-google-translate|fun|1.4.9
todo-tree|Gru|0.0.186
output-colorizer|IBM|0.1.2
customize-ui|ioc|0.1.49
monkey-patch|ioc|0.1.11
pubspec-assist|jer|2.2.1
svg|joc|1.4.1
bracket-peek|jom|1.3.0
vscode-gutter-preview|kis|0.26.2
dart-import|lua|0.3.1
regionfolder|map|1.0.12
sqltools|mtx|0.23.0
sqltools-driver-sqlite|mtx|0.2.0
awesome-flutter-snippets|Nas|2.0.4
vscode-xml|red|0.13.0
multi-command|ryu|1.4.0
swdc-vscode|sof|2.3.18
comment-divider|sta|0.2.2
code-spell-checker|str|1.9.3
unique-window-colors|stu|1.0.51
sort-lines|Tyr|1.9.0
errorlens|use|3.2.3
vscode-icons|vsc|11.0.0
t4-support|zbe|0.5.0

</details>

**Comment by sandy081** [comment]
This is expected and designed. Please restart and you can turn on Sync again .

Can you please provide us the Settings Sync log from Output view when this happened? If you restarted VS Code and lost the log when this issue occurred, you can find it in the logs folder on your disk (run the command Open Logs Folder...). This will show us the requests to diagnose.
