### ISSUE TITLE
Pass telemetry enablement to extensions

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#110267]
Right now extensions use the configuration to determine if they should send telemetry; however, the cli flag is not passed to the extension host.

```ts
export namespace env {
  export const enableTelemetry: boolean;

  export const onDidChangeEnableTelemetry: Event<boolean>;
}
```

**Comment by jrieken** [comment]
* for the name maybe something like `isTelemetryEnabled` and `onDidChangeTelemetryEnabled`

**Comment by jrieken** [comment]
Let's keep this open to track the API finalization under the same issue

**Comment by sbatten** [comment]
To verify:
1. Use the following extension code to verify the api OR
2. Install this VSIX for that extension (rename zip to vsix)
[telemetry-api-extension-0.0.1.zip](https://github.com/microsoft/vscode/files/6193291/telemetry-api-extension-0.0.1.zip)

3. Once using the test extension, toggle the `telemetry.enableTelemetry` setting and watch for notifications of the change by the extension. It also has a command to check the current state (Check Telemetry Enablement).
4. Launch code with --disable-telemetry. Verify that checking the state always shows disabled and changing the setting has no effect.
