### ISSUE TITLE
Problems view should show file finder rather than error notification on missing files

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#110256]
![image](https://user-images.githubusercontent.com/641685/98587241-de4e1f80-2297-11eb-90c9-ac3e6ffae4a2.png)

It would be nice if the problems panel would open the quick open picker (like the terminal does with terminal links) to search for missing files rather than the error notification. Or at least offer a button on the error notification to try to find the file, as the _Create File_ button doesn't feel very useful.

**Comment by sandy081** [comment]
This notification is coming from text file service - hence delegating to @bpasero. It would be nice if the underlying service provides this support.

**Comment by bpasero** [comment]
I am not sure opening quick pick directly is a good idea, but the error notification could offer another button to "Open File" via quick pick.

**Comment by eamodio** [comment]
I would suggest that the `Create File` button be replaced with an `Open File` button -- since it doesn't make sense to me to want to create a file from a "problem" -- typically the issue is path mapping in the problem matcher

**Comment by bpasero** [comment]
The original intent of this button was when you follow a link from the editor for a file that does not exist it would allow to quickly create it:

![image](https://user-images.githubusercontent.com/900690/98658109-f29b2680-2342-11eb-8246-77a9e1aef3c2.png)

E.g.:
* open a html file
* write a link
* ctrl click it even if it does not exist
* quickly have the file created

Btw any client that opens an editor is free to implement their own behaviour via `ignoreError`
