### ISSUE TITLE
Most of icons are broken (displayed like squares)

### ISSUE THREAD

**Issue by nycshisan** [microsoft/vscode#110288]
- VSCode Version: 1.51.0
- OS Version: Win10 version:1903

Steps to Reproduce:

1. Just install the editor and open. See the screenshot

![image](https://user-images.githubusercontent.com/16484740/98643200-ff833e80-2371-11eb-8aec-55925ed9c01a.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by nycshisan** [comment]
FYI, when launching the editor by the right-click menu of a file, icons come back, but some of them are still broken. See the screenshot below:

![image](https://user-images.githubusercontent.com/16484740/98643985-28f09a00-2373-11eb-9715-f1f926ea367e.png)


However, under this case, if doing "open the folder" in the screen, the icons are broken again just like the first screenshot.

**Comment by aeschli** [comment]
Can you open the dev tools and inspect one of the broken images?

![image](https://user-images.githubusercontent.com/6461412/98679070-be822e80-235f-11eb-828a-c942a51a6fc8.png)

**Comment by nycshisan** [comment]
![image](https://user-images.githubusercontent.com/16484740/98683048-f319d880-23a7-11eb-9fe2-50672c9661e0.png)

Do you mean this?

**Comment by misolori** [comment]
This looks like the bundled files (codicons and seti) failed to load, and the same as https://github.com/microsoft/vscode/issues/85872

I've can't repro on Windows using the same version of VS Code.

**Comment by nycshisan** [comment]
The problem is fixed by reinstall the font in #85872. Thanks for your reply!
