### ISSUE TITLE
Redraw issues in the terminal

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#110242]
Version: 1.51.0-insider
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-04T18:30:27.659Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15

1) Create a codespace using the web UI
2) In the terminal of the codespace run `git config --list`

-> 
![image](https://user-images.githubusercontent.com/4674940/98571048-f8243e00-2268-11eb-8174-ff145e600605.png)

The amount of whitespace on the top reflects the number of lines that were displayed in the terminal before.

Note: Redraw fixes the problem:

![image](https://user-images.githubusercontent.com/4674940/98570504-5f8dbe00-2268-11eb-93c2-ae4a937ae18f.png)

**Comment by connor4312** [comment]
Potentially related: https://github.com/microsoft/vscode/issues/110232

**Comment by Tyriar** [comment]
It does look similar to #110232.

I can't repro though:

![image](https://user-images.githubusercontent.com/2193314/98607463-10628000-229e-11eb-949d-81a1924eec6b.png)

When piping into `| less` I see this which is expected:

![image](https://user-images.githubusercontent.com/2193314/98607563-4b64b380-229e-11eb-9f42-62e9aff8e003.png)

Pressing up or resizing will show that it's the end of the file:

![image](https://user-images.githubusercontent.com/2193314/98607587-5cadc000-229e-11eb-8098-8bbce0908059.png)

@kieferrm do you have a value set for `core.pager` in your `.gitconfig`?

**Comment by Tyriar** [comment]
Still can't reproduce
