### ISSUE TITLE
Intellisense only shows one option.

### ISSUE THREAD

**Issue by tonymatute** [microsoft/vscode#110231]
Issue Type: <b>Bug</b>

I am using VSCode for angular and everything was working fine. I updated VS Code to the new Version
Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

and now I am experiencing an odd behavior with intellisence. It is only showing me ONE/the last one I used  option and I can't figure the way to resolve this issue. I experiment with different editor settings in my Settings.json file but nothing seems to work 

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.9.0
ng-template|Ang|0.1001.1
bracket-pair-colorizer-2|Coe|0.2.0
prettier-vscode|esb|5.7.1
Angular2|joh|9.1.2
csharpextensions|kre|1.3.6
csharpfixformat|Leo|0.0.84
mongodb-vscode|mon|0.2.1
csharp|ms-|1.23.5
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
vscode-nuget-gallery|pat|0.0.22
material-icon-theme|PKi|4.4.0
vscode-icons|vsc|11.0.0
es7-react-js-snippets|woo|2.3.8
html-css-class-completion|Zig|1.19.0

</details>

**Comment by jrieken** [comment]
Did you by any chance resize the widget while it was showing a single suggestion? Can you try "F1 > Reset Suggest Widget Size" and check if the widget size is back to normal?

**Comment by tonymatute** [comment]
Great!

That fix the problem!!

 

Thanks,

Tony

**Comment by jrieken** [comment]
I'd still be interested in how you go into this state... Any ideas/memories?

**Comment by tonymatute** [comment]
Weird to say I have no recollection on how I got the widget into that state however I will put some , not all my bitcoins in the October release I recently downloaded, in which VS Code has fixed a problem with resizable suggestions ! 

I am not sure if this fix caused my widget window size to be very small.

 

Thanks for your input fixing this annoying issue in my VS Code!!

 

Tony

**Comment by jrieken** [comment]
Alright. Closing this issue then
