### ISSUE TITLE
Option in context menu overlapped with title bar not working

### ISSUE THREAD

**Issue by huntdream** [microsoft/vscode#110282]
- VSCode Version: 1.51.0
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Right click to open a context menu, make sure at least one option in the menu is overlapped with title bar
2. Move cursor over the overlapped area, it doesn't trigger hover effect and will not trigger event if you click 

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/7903755/98629949-fcc62080-2354-11eb-87c9-b2af954cf059.png)

**Comment by sbatten** [comment]
for reference, the original fix for this was here: https://github.com/microsoft/vscode/pull/58467 which was regressed by the Shadow DOM feature of the context view
