### ISSUE TITLE
Remote Launch from SSH don't work on 1.51

### ISSUE THREAD

**Issue by bobaoapae** [microsoft/vscode#110253]
- VSCode Version:1.51
- OS Version: Windows 10 20h2

Version 1.51 Remote Start: [https://prnt.sc/vg9tm2](https://prnt.sc/vg9tm2) (10 minutes waiting)
Version 1.50.1 Remote Start: [https://prnt.sc/vg9wpp](https://prnt.sc/vg9wpp) (work as expected)

Launch.json: https://prnt.sc/vg9vuw

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Need more details, but please file an issue on the repo for the debug extension that you are using. You can also check developer tools (Help > Toggle Developer Tools) for possible errors.

**Comment by bobaoapae** [comment]
This only happen on version 1.51, downgrade to 1.50.1 fix this issue

**Comment by bobaoapae** [comment]
Developer Tools Log: 

ERR Cannot read property 'scheme' of null: TypeError: Cannot read property 'scheme' of null
    at Object.transformIncoming (c:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\uriTransformer.js:4:76)
    at t.URITransformer.transformIncoming (C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:244:220)
    at I._createTerminalProcess (C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:781:351)
    at I.call (C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:780:328)
    at x.onPromise (C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:266:142)
    at x.onRawMessage (C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:265:615)
    at C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:264:877
    at l.fire (C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:48:801)
    at v.fire (C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:281:381)
    at t.PersistentProtocol._receiveMessage (C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:286:451)
    at C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:283:489
    at l.fire (C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:48:801)
    at f.acceptChunk (C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:278:851)
    at C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:278:203
    at Socket.t (C:\Users\Administrador\.vscode-server\bin\fcac248b077b55bae4ba5bab613fd6e9156c2f0c\out\vs\server\remoteExtensionHostAgent.js:288:226)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)

**Comment by roblourens** [comment]
Does a normal terminal work? Does that error only show up when you click the button to start debugging?

**Comment by bobaoapae** [comment]
Normal terminal works, even the build task work, only remote start hangs forever, don't show any error

**Comment by roblourens** [comment]
Does setting `"terminal.integrated.serverSpawn": false` fix it?

**Comment by roblourens** [comment]
@alexdima seems that we have `args.shellLaunchConfig.cwd` as null, when we only check for `undefined`

**Comment by roblourens** [comment]
I can repro this just with `vscode.window.createTerminal({ cwd: null, name: 'extension terminal' });` in a remote extension

**Comment by roblourens** [comment]
Can you share your launch config too @bobaoapae?

**Comment by bobaoapae** [comment]
> Can you share your launch config too @bobaoapae?

`{
    // Use IntelliSense to find out which attributes exist for C# debugging
    // Use hover for the description of the existing attributes
    // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Center Service",
            "type": "coreclr",
            "preLaunchTask": "build",
            "request": "launch",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/Center.Service/bin/Debug/netcoreapp3.1/win10-x64/Center.Service.dll",
            "args": [],
            "cwd": "${workspaceFolder}/Center.Service/bin/Debug/netcoreapp3.1/win10-x64/",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "integratedTerminal",
            "stopAtEntry": false,
            "allowFastEvaluate": true
        },
        {
            "name": "Fight Service",
            "type": "coreclr",
            "preLaunchTask": "build",
            "request": "launch",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/Fighting.Service/bin/Debug/netcoreapp3.1/win10-x64/Fighting.Service.dll",
            "args": [],
            "cwd": "${workspaceFolder}/Fighting.Service/bin/Debug/netcoreapp3.1/win10-x64/",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "integratedTerminal",
            "stopAtEntry": false,
            "allowFastEvaluate": true
        },
        {
            "name": "Flash Service",
            "type": "coreclr",
            "preLaunchTask": "build",
            "request": "launch",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/Flash.Service/bin/Debug/netcoreapp3.1/win10-x64/Flash.Service.dll",
            "args": [],
            "cwd": "${workspaceFolder}/Flash.Service/bin/Debug/netcoreapp3.1/win10-x64/",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "integratedTerminal",
            "stopAtEntry": false,
            "allowFastEvaluate": true
        },
        {
            "name": "Game Service",
            "type": "coreclr",
            "preLaunchTask": "build",
            "request": "launch",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/Game.Service/bin/Debug/netcoreapp3.1/win10-x64/Game.Service.dll",
            "args": [],
            "cwd": "${workspaceFolder}/Game.Service/bin/Debug/netcoreapp3.1/win10-x64/",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "integratedTerminal",
            "stopAtEntry": false,
            "allowFastEvaluate": true
        }
    ],
    "compounds": [
        {
            "name": "Debug All",
            "configurations": [
                "Center Service",
                "Fight Service",
                "Flash Service",
                "Game Service"
            ]
        }
    ]
}`

**Comment by bobaoapae** [comment]
> Does setting `"terminal.integrated.serverSpawn": false` fix it?

I need try, i cant update vscode to test right now, when i finish coding i will try this

**Comment by alexdima** [comment]
> seems that we have `args.shellLaunchConfig.cwd` as null, when we only check for `undefined`

I see. This means that https://github.com/microsoft/vscode/blob/02f6319ca1f24d80bba309b91e5d64b4ddebb718/src/vs/workbench/contrib/terminal/common/terminal.ts#L204 is incorrect and it should be `cwd?: string | URI | null`

**Comment by bobaoapae** [comment]
> Does setting `"terminal.integrated.serverSpawn": false` fix it?

Yes, with this config i don't have issues on start debug

**Comment by roblourens** [comment]
If you don't have the right strict option set for your extension, you can always do that. We often don't validate arguments from extension api in code.

**Comment by alexdima** [comment]
@roblourens :+1: Thanks for the fix!

**Comment by Spongman** [comment]
/verified

i was seeing this in 1.5.1, but not in

> Version: 1.52.0-insider (user setup)
> Commit: a36c68b9ec3d6a0aca9799d7a10be741a6658a51
> Date: 2020-11-19T05:37:52.577Z
> Electron: 9.3.3
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT x64 10.0.19041

**Comment by meganrogge** [comment]
> /verified

per the above, adding z-author-verified label
