### ISSUE TITLE
vscode arm64 .deb adds entry to /ete/apt/sources.list.d Forlder that is only for amd64 architecture?

### ISSUE THREAD

**Issue by mannkeithc** [microsoft/vscode#110229]
- VSCode Version: code_1.51.0-1604600189_arm64
- OS Version: Chrome OS 86.0.4240.183 / Debian Buster 10 Container 

Steps to Reproduce:
I have a Lenovo Duet Chromebook with a MediaTek Helio P60T Octa-Core ARM processor. The latest release of vscode for arm64 installs and runs OK in a Debian Buster container, but it adds a vscode.list file to the /etc/apt/sources.list.d folder that is amd64 architecture specific (see step 1). If I edit this to be arm64 architecture specific (see step 2), and then run command $ sudo apt update, I receive a warning message (see step 3). Running "sudo apt update && upgrade" would ordinarily ensure vscode remains up to date on an amd64 platform, but fails on an arm64 platform, because the current vscode repository only supports X86 processors. This means I need to manually download and install each new vscode software update for arm64 processors. Please would you add the arm64 architecture to your vscode linux software repository.
1. more /etc/apt/sources.list.d/vscode.list
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
2.
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=arm64] http://packages.microsoft.com/repos/vscode stable main
3. Warning message from running $ sudo apt update comand:
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://packages.microsoft.com/repos/vscode stable InRelease' doesn't support architecture 'arm64'

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by Tyriar** [comment]
Code pointer:

https://github.com/microsoft/vscode/blob/1256b16ee19605cc1eb4d3f14ebd7180758dcf11/resources/linux/debian/postinst.template#L26-L78

**Comment by joaomoreno** [comment]
Part of https://github.com/microsoft/vscode/issues/106473

**Comment by lesar** [comment]
A little question.  

if I let vscode.list be:  
deb [arch=arm64] http://packages.microsoft.com/repos/vscode stable main  

on rpi4 using ubuntu 20.04 64 desktop  

waiting some time it will stop to give error unsupported arch?  

best regards,
Leonardo
