### ISSUE TITLE
Unable to load extensions view

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#110244]
- VSCode Version: 1.52.0-insiders
- OS Version: Mac

On the latest insiders, clicking on the extensions shows me this error. I've tried reloading the window and reconnecting to my wifi but still seeing it. Not seeing this issue in 1.51.0 in stable. 

![image](https://user-images.githubusercontent.com/9721254/98571783-e2237700-2282-11eb-9efe-c0aa36d6a253.png)

**Comment by joaomoreno** [comment]
@sana-ajani Does it reproduce if you restart your machine?

**Comment by sana-ajani** [comment]
Restarting my machine fixed this!
