### ISSUE TITLE
Files don't appear when browsing in remote SSH

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode#110265]
- VSCode Version: Code - Insiders 1.52.0-insider (24b28f5, 2020-11-06T05:39:23.276Z)
- OS Version: Darwin x64 19.6.0
- Remote OS version: Linux x64 5.4.0-1031-azure

Steps to Reproduce:
Via a VS Code extension running in remote SSH.

1. Use `vscode.window.showOpenDialog` to browse for files on the remote machine with the following options:
```ts
            {
                canSelectFiles: true,
                canSelectFolders: false,
                canSelectMany: true,
                defaultUri: Uri,
                filters: {
                    "All files": ['*']
                },
                openLabel: "Upload"
            }
```
2. No files appear - only folders

Does this issue occur when all extensions are disabled?: N/A

**Comment by alexr00** [comment]
Thanks @wwlorey !
