### ISSUE TITLE
Local Echo breaks docker exec printout

### ISSUE THREAD

**Issue by joshk0** [microsoft/vscode#110232]
Issue Type: <b>Bug</b>

1. Create a WSL2 setup using Ubuntu 20.04 as the client OS and Docker Desktop 2.5.0 in WSL2 mode. (Unsure if this is required but this is my setup)
2. Load your vscode inside your WSL2 guest, then start a terminal session.
3. Run a docker image: `docker run --rm -it node:14.15.0-alpine sh`
4. Try something like `ls /`, you would get this:

![image](https://user-images.githubusercontent.com/5368926/98557549-5ace0780-2272-11eb-9038-728279f5ce12.png)

5. Go to settings.json and turn off local echo: `"terminal.integrated.localEchoLatencyThreshold": -1`
6. In my case the terminal refreshes immediately and I can now see the correct contents of the terminal:

![image](https://user-images.githubusercontent.com/5368926/98557557-5dc8f800-2272-11eb-8392-62f7bfad2315.png)

Note: I tried with `docker run --rm -it alpine sh` and could not reproduce this bug, but the fact that local echo seems to be a proximate cause seems worth investigating.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (4.62GB free)|
|Process Argv|--crash-reporter-id 6a21a6e0-2ac5-446e-88c1-ad7f0b95572d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|Memory (System)|3.84GB (1.42GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.7.0
remote-containers|ms-|0.148.0
remote-wsl|ms-|0.51.1
debugger-for-edge|msj|1.0.15
sql-bigquery|shi|1.4.0
vim|vsc|1.17.1
vscode-npm-script|eg2|0.3.13
go|gol|0.18.1
terraform|has|2.2.3
vscode-docker|ms-|1.7.0
python|ms-|2020.10.332292344
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.3121
vetur|oct|0.29.1
java|red|0.70.0
vscode-xml|red|0.13.0
vscode-yaml|red|0.12.0
trailing-spaces|sha|0.3.1
vscode-scss-formatter|sib|2.0.2
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.25.0

</details>

**Comment by meganrogge** [comment]
@joshk0 I just tried to reproduce this and could not. I ran the exact command you mentioned above and didn't change "terminal.integrated.localEchoLatencyThreshold", so it was set to 30. 
![result](https://user-images.githubusercontent.com/29464607/98571291-420d2400-2269-11eb-9b09-5e7cde80e9f6.PNG)

**Comment by joshk0** [comment]
Hey Megan, I agree that WSL could be at fault, but I am curious about what is special about the local echo feature that allows things to work if I turn it off.

Also, I should note that everything works fine in cmd.exe or Windows Terminal with both docker images, and the fact that turning off local echo _immediately_ restores the invisible values without needing to run the command again (e.g. they were there all along, but the terminal itself was not displaying them for one reason or another)

All of this makes me very suspicious of the changes in the vscode terminal!

What shell were you using when you ran docker, and what is the output of the following command for you? Here's what I have:

```
$ printenv | grep TERM
COLORTERM=truecolor
TERM_PROGRAM_VERSION=1.51.0
TERM=xterm-256color
TERM_PROGRAM=vscode
```

**Comment by meganrogge** [comment]
Hey Josh, yes you raise a good and interesting question.

I am using bash and the output of that for me is 
`TERM=xterm`

**Comment by joshk0** [comment]
OK, I tried to screencap what I'm seeing and it's truly weird. I wanted to show the contents of the terminal returning when I disabled local echo, but instead I found that as soon as I opened settings.json in a pane, they came back right away!

My guess is that the bug will happen or not base on whether local echo triggers, so based on the threshold it may happen some times and not others. No clue as to why opening settings.json (without changing the setting) fixes things though.

[Video](https://imgur.com/a/Zq3rl2D)

**Comment by meganrogge** [comment]
@joshk0 do you see any errors in the developer console?

**Comment by connor4312** [comment]
Thanks for the issue. This looks like an issue with the renderer; resizing the terminal at all/toggling the sidebar (forcing a redraw) causes the text to be displayed correctly.

Unlike Megan, I'm able to reproduce it both with and without `"terminal.integrated.rendererType": "experimentalWebgl"`, but only with the specific command and only when running it in a remote WSL2 instance (not through `wsl` directly on the windows side)/

**Comment by connor4312** [comment]
Log running the command in wsl2/ubuntu where the problem happens:

```
predict: "\u001b[2ml\u001b[22m"
VM371:1 predict: "\u001b[2ms\u001b[22m"
VM372:1 predict: "\u001b[2m \u001b[22m"
VM373:1 predict: "\u001b[2m/\u001b[22m"
VM374:1 before: "ls /"
VM375:1 after: "ls /"
VM376:1 predict: "\r\n"
VM377:1 before: "\r\n\u001b[1;34mbin\u001b[m    \u001b[1;34mdev\u001b[m    \u001b[1;34metc\u001b[m    \u001b[1;34mhome\u001b[m   \u001b[1;34mlib\u001b[m    \u001b[1;34mmedia\u001b[m  \u001b[1;34mmnt\u001b[m    \u001b[1;34mopt\u001b[m    \u001b[1;34mproc\u001b[m   \u001b[1;34mroot\u001b[m   \u001b[1;34mrun\u001b[m    \u001b[1;34msbin\u001b[m   \u001b[1;34msrv\u001b[m    \u001b[1;34msys\u001b[m    \u001b[1;34mtmp\u001b[m    \u001b[1;34musr\u001b[m    \u001b[1;34mvar\u001b[m\r\n/ # \u001b[6n"
VM378:1 after: "\u001b[?25l\u001b[1;34mbin\u001b[m    \u001b[1;34mdev\u001b[m    \u001b[1;34metc\u001b[m    \u001b[1;34mhome\u001b[m   \u001b[1;34mlib\u001b[m    \u001b[1;34mmedia\u001b[m  \u001b[1;34mmnt\u001b[m    \u001b[1;34mopt\u001b[m    \u001b[1;34mproc\u001b[m   \u001b[1;34mroot\u001b[m   \u001b[1;34mrun\u001b[m    \u001b[1;34msbin\u001b[m   \u001b[1;34msrv\u001b[m    \u001b[1;34msys\u001b[m    \u001b[1;34mtmp\u001b[m    \u001b[1;34musr\u001b[m    \u001b[1;34mvar\u001b[m\r\n/ # \u001b[6n\u001b[?25h"
```

Log running it through powershell:

```
predict: "\u001b[2ml\u001b[22m"
VM219:1 predict: "\u001b[2ms\u001b[22m"
VM220:1 predict: "\u001b[2m \u001b[22m"
VM221:1 predict: "\u001b[2m/\u001b[22m"
VM222:1 before: "l"
VM223:1 after: "\u001b[?25l\u001b[9;5Hl\u001b[9;9H\u001b[?25h"
VM224:1 before: "s /"
VM225:1 after: "\u001b[?25l\u001b[9;6Hs\u001b[9;7H \u001b[9;8H/\u001b[9;9H\u001b[?25h"
VM226:1 predict: "\r\n"
VM227:1 before: "\r\n"
VM228:1 after: ""
VM229:1 before: "\u001b[1m\u001b[94mbin\u001b[m    \u001b[1m\u001b[94mdev\u001b[m    \u001b[1m\u001b[94metc\u001b[m    \u001b[1m\u001b[94mhome\u001b[m   \u001b[1m\u001b[94mlib\u001b[m    \u001b[1m\u001b[94mmedia\u001b[m  \u001b[1m\u001b[94mmnt\u001b[m    \u001b[1m\u001b[94mopt\u001b[m    \u001b[1m\u001b[94mproc\u001b[m   \u001b[1m\u001b[94mroot\u001b[m   \u001b[1m\u001b[94mrun\u001b[m    \u001b[1m\u001b[94msbin\u001b[m   \u001b[1m\u001b[94msrv\u001b[m    \u001b[1m\u001b[94msys\u001b[m    \u001b[1m\u001b[94mtmp\u001b[m    \u001b[1m\u001b[94musr\u001b[m    \u001b[1m\u001b[94mvar\u001b[m\r\n/ # \u001b[111X"
VM230:1 after: "\u001b[1m\u001b[94mbin\u001b[m    \u001b[1m\u001b[94mdev\u001b[m    \u001b[1m\u001b[94metc\u001b[m    \u001b[1m\u001b[94mhome\u001b[m   \u001b[1m\u001b[94mlib\u001b[m    \u001b[1m\u001b[94mmedia\u001b[m  \u001b[1m\u001b[94mmnt\u001b[m    \u001b[1m\u001b[94mopt\u001b[m    \u001b[1m\
```

**Comment by jpriebe** [comment]
I'm seeing this on Mac (Catalina, 10.15.7) as well.  

I'm shelled into a kubernetes container on AKS, and when I issue commands like "ls", I see one of three things:
- the expected output
- no output at all
- a blank line

Resizing the VSCode window (and hence the terminal) causes the missing text to appear.  I just started noticing it today; it's possible that the reason I just noticed it today was because I restarted VSCode for the first time in a week or two.

Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:14:40.758Z (4 days ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by joshk0** [comment]
@jpriebe 
If you disable local echo using `"terminal.integrated.localEchoLatencyThreshold": -1` does the condition go away?

**Comment by jpriebe** [comment]
@joshk0 - yes it did go away.  Interestingly, the behavior changes as soon as I save settings.json, even with an open terminal with an open shell to a remote kubernetes container.  That's a pretty impressive level of dynamic configuration.

**Comment by markedwards** [comment]
I also see this issue on OS X, and it seems to have gone away with `"terminal.integrated.localEchoLatencyThreshold": -1`

**Comment by backbone87** [comment]
Can confirm the behavior described here.
Setup: Win 10 - WSL 2/Ubuntu - Docker Desktop
When running a container (`docker run --rm -it node:14-alpine /bin/sh`) the outputs of commands are not visible most of the time.
Starting a fresh VSCode instance, running the container, then the output of the first command **is visible**. After that, the outputs are only visible after the terminal is redrawn (scroll/resize).
Tried all renderers.
Setting `"terminal.integrated.localEchoLatencyThreshold": -1` makes everything work as expected immediately.

**Comment by jarrodldavis** [comment]
I'm having the same issue running Ruby's REPL, `irb`, in a GitHub Codespace. None of the terminal renderer options (including `experimentalWebgl`) alleviate the issue, but turning Local Echo off (`terminal.integrated.localEchoLatencyThreshold` set to `-1`) fixes the problem.

**Comment by andrewspode** [comment]
I'm having this problem as well. I am doing "docker-compose exec container-name sh". Oddly, all my other containers are fine - this is only happening when I've started working with alpine which uses sh instead of bash.

If I do this from the WSL terminal built into Windows 10 - there are no rendering issues, so only happening from within VS Code.

I can also confirm that adding "terminal.integrated.localEchoLatencyThreshold": -1 fixes things, although I'm unsure on what impact this has on anything else.

**Comment by akosyakov** [comment]
I can reproduce it in Gitpod and Codespaces by running `docker run --rm -it alpine:latest`.

**Comment by dosfx** [comment]
I can reproduce the issue on Windows using vscode-remote connected to centos running on aws. I'm running `docker run --rm -it nginx:stable-alpine sh`, so more alpine.

Both setting the threshold to -1 or enabling experimentalWebgl fixes the issue.

**Comment by ghuntley** [comment]
Confirming reproducibility.

**Comment by Tyriar** [comment]
Since this appears to be a rendering problem that doesn't happen in webgl I'll close this off. Please do open another issue if you still see the issue with more info as I worry this one has become stale.
