### ISSUE TITLE
php_opcache.dll

### ISSUE THREAD

**Issue by VladDVN** [microsoft/vscode#110293]
php.ini is configured. It conteins the full path to the dll: zend_extension=C:\xampp\php\ext\php_opcache.dll

The projects are working in all browsers. But in VSC this error always occurs:

Warning: Failed loading Zend extension 'opcache' (tried: C:\xampp\php\ext\opcache (The specified module could not be found.), C:\xampp\php\ext\php_opcache.dll (The specified module could not be found.)) in Unknown on line 0

**Comment by roblourens** [comment]
This sounds like an issue with a PHP extension or with your app, I don't think vscode is doing this.
