### ISSUE TITLE
VScode suddenly crashes after sleep and wake up

### ISSUE THREAD

**Issue by shujathkhan** [microsoft/vscode#110209]
Issue Type: <b>Bug</b>

Keep using VSCode for a few hours, lock system and leave it for a while, then unlock system, VScode has been autoclosed/crashed.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.81GB (13.83GB free)|
|Process Argv|--crash-reporter-id 123e2acc-ce7e-4d91-95f6-7fdc14f39330|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|7.2.0
npm-intellisense|chr|1.3.1
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
make-hidden|dev|3.0.3
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.3
vscode-npm-script|eg2|0.3.13
vscode-peacock|joh|3.8.0
template-string-converter|meg|0.2.7
git-graph|mhu|1.27.0
vscode-js-profile-flame|ms-|0.0.13
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.1
debugger-for-chrome|msj|4.12.11
vscode-scss-formatter|sib|2.0.2
vscode-multiclip|sle|0.1.5
tabnine-vscode|Tab|3.1.5
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0

(2 theme extensions excluded)

</details>

**Comment by rzhao271** [comment]
Does this issue still occur for you on the latest Insiders version of VS Code (v1.53.0)?
If so, can you attach a crash dump? https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
