### ISSUE TITLE
close newly created file(s) in a branch once git checkout to another branch

### ISSUE THREAD

**Issue by walidbarakat** [microsoft/vscode#110261]
i noticed that if i'm working on a branch and that work resulted in creating new files in the project, i still need to close these files after i'm done with that branch and checked out in addition i need to refresh the directory view to see the current branch related directory, i remember when i'm working with Eclipse i didn't need that. and such handling can be a small add to the productivity i think.

**Comment by joaomoreno** [comment]
You can use the `workbench.editor.closeOnFileDelete` setting for this.
