### ISSUE TITLE
Webview keypress dispatch sometimes stops working

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#110276]
I found something more interesting:

* Open a text editor, keep pressing ctrl+`, the terminal keeps toggling
* Open markdown preview, keep pressing ctrl+`, the terminal toggles for a few times and then nothing happens anymore

This happens even without the experiment settings. I also toggled the keyboard shortcut troubleshooting and when ctrl+` went dead, the keybinding service doesn't get any keyboard events as well.

_Originally posted by @rebornix in https://github.com/microsoft/vscode/issues/109702#issuecomment-719062237_

**Comment by David-Else** [comment]
As this is a serious accessability issue and does not involve any experimental settings, why not add to the November milestone rather than backlog? Thanks.

**Comment by mjbvz** [comment]
I tried creating a minimal electron repo (https://github.com/electron/electron/issues/26309) but it can be fixed by changing `.focus()` to `.contentWindow.focus()`. However since VS Code is already using `.contentWindow.focus()` the repo must not be complete 

Also this is fixed by using iframe based webviews: `webview.experimental.useIframes`

**Comment by David-Else** [comment]
@mjbvz I just installed Code 1.52 and can't find any `webview.experimental.useIframes`. It says Unknown Configuration Setting in settings.json

**Comment by jace4511** [comment]
> I found something more interesting:
> 
> * Open a text editor, keep pressing ctrl+`, the terminal keeps toggling
> * Open markdown preview, keep pressing ctrl+`, the terminal toggles for a few times and then nothing happens anymore
> 
> This happens even without the experiment settings. I also toggled the keyboard shortcut troubleshooting and when ctrl+` went dead, the keybinding service doesn't get any keyboard events as well.
> 
> _Originally posted by @rebornix in [#109702 (comment)](https://github.com/microsoft/vscode/issues/109702#issuecomment-719062237)_

**Comment by mjbvz** [comment]
I'm closing this since I cannot reproduce using iframe based webview, which are now enabled by default for all webviews except those that enable search. We should be converting those over to use iframes too shortly
