### ISSUE TITLE
"Create a launch.json" is blocked by unrelated extensions downloading SDKs

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#110386]
When I clicked "Create a launch.json" file here in my Dart project, it caused the C# extension to activate, which then started downloading SDK components. This seems to have blocked the creation of the launch.json for the entire duration.

![blocked](https://user-images.githubusercontent.com/1078012/98810223-c94bca80-2416-11eb-9d63-63c030d8f721.png)

I'm not sure what a good fix would be (the C# extension not blocking completing its activation for downloads, VS Code only waiting a short period for activation to complete when fetching the dynamic debug configurations?), but it feels awkward to be blocked for several minutes by an extension that is completely unrelated to the current workspace.

**Comment by isidorn** [comment]
@DanTup I agree with you that this is not the best experience.
1. We have to activate C# because we need to get their debug configurations for the launch.json creation
2. C# should idally handle this differently - they should have a soft and a "hard" activation. Ideally they shuold be able to provide a launch configuration without installing OmniSharp.

Can you also file this issue in the C# repository please so we start the discussion going there? Thanks

**Comment by DanTup** [comment]
> C# should idally handle this differently - they should have a soft and a "hard" activation. Ideally they shuold be able to provide a launch configuration without installing OmniSharp.

I know I keep saying this, but this is where I think VS Code should really give some guidance. Dart also does expensive work (spawns a language server) unconditionally at activation. It's hard for language extensions to know whether they can assume if they're activated they're really needed or not. In the past, it seemed like VS Code would only ever activate when it was *really* needed, but over time, it seems like VS Code needs to activate them more frequently for things like metadata. I think if there's an expectation that extensions should behave differently, there should be some better guidance from VS Code around this?

**Comment by isidorn** [comment]
Yes, that makes sense.

**Comment by isidorn** [comment]
@jrieken do we have some extension guidance for when extensions should activate? I think last comment that @DanTup made is correct and maybe we should have a more fine-tuned guidance for activation

**Comment by roblourens** [comment]
I agree that this is an issue with the C# extension, but I think https://github.com/microsoft/vscode/issues/88617 covers this
