### ISSUE TITLE
The infamous chromium blue noise bug on MacOS reached vscode

### ISSUE THREAD

**Issue by trumbitta** [microsoft/vscode#110379]
The infamous chromium blue noise bug on MacOS reached vscode with one the latest releases. I'm guessing via Electron.

https://bugs.chromium.org/p/chromium/issues/detail?id=1068170

This is so disappointing.

Any way of disabling "Out of Process rasterisation" via some flag for vscode like I had to do for Chrome?

**Comment by trumbitta** [comment]
For now, launching code from the terminal like this `code --disable-gpu` seems to work while we wait for some better solution.

**Comment by trumbitta** [comment]
Update: as dreaded, launching vscode with `--disable-gpu` results in a sensible loss of performance while typing and now my liver hurts 😭

**Comment by deepak1556** [comment]
You can try starting with `--disable-oop-rasterization`

/duplicate https://github.com/microsoft/vscode/issues/106429
