### ISSUE TITLE
Close Debug on Session End

### ISSUE THREAD

**Issue by ssoher** [microsoft/vscode#110349]
We have the settings `debug.openDebug` to customize when the debug view opens. But we have no option to customize what happens to this view when debug session is finished. I want a settings like `debug.closeDebug` with an option like `closeOnSessionEnd`. We have this for console but not for the actual debug view, resulting in bad user experience if the developer uses vscode with sidebar hidden.

**Comment by isidorn** [comment]
I agree we have no clean way to do this. We only have the following setting
`"debug.openExplorerOnEnd": true`
Which would just open the Explorer once debugging is stopped.
Idealy we would have a more general setting that would allow either to open explorer or to close the sidebar. Thus leaving this open as a feature request for now. Thanks

**Comment by ssoher** [comment]
@isidorn 1) Does this mean it's not going to be implemented ever? 2) Is there an event in the extension API on debug session end that I can listen to and close the panel in an extension myself?

**Comment by isidorn** [comment]
1) not going to be implemented in the near future
2) yeah there is, great idea. Check out this event https://github.com/microsoft/vscode/blob/653e409f480282a3f6fd53b88972d6fc989367d9/src/vs/vscode.d.ts#L11797

**Comment by ssoher** [comment]
released here if anyone is interested
https://marketplace.visualstudio.com/items?itemName=sarper.close-sidebar-on-debug-session-end

**Comment by isidorn** [comment]
Thanks for creating an extension for this!
