### ISSUE TITLE
Copying, then cutting pastes the cut line, not the copied text

### ISSUE THREAD

**Issue by Destaq** [microsoft/vscode#110348]
- VSCode Version: 1.51.0
- OS Version: macOS Catalina 10.15.6

Steps to Reproduce:

1. Copy some text with `cmd-c`
2. Delete a line with `cmd-x`
3. Try pasting your text with `cmd-v` - you paste the deleted line

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by EthanRutherford** [comment]
That's.. how cut works.
