### ISSUE TITLE
Allow separation of activity bar

### ISSUE THREAD

**Issue by stephenjfox** [microsoft/vscode#110335]
I would like to see VS Code support creating two opposite instances of the activity bar, preferably by dragging a single activity/extension icon from one side to any of the four cardinal positions of VS Code (top, left, bottom/tray, right).

* Currently, I can only pin the activity bar to the left or right side (or hide it all together)
* But what if I want to see my LiveShare details on the left side of the editor, and the file explorer on the right?
  * This is just one of many possibilities

The second instance of the activity bar would support housing multiple extension buttons, at the drag and drop or settings configuration of the user.

**Comment by misolori** [comment]
Please upvote https://github.com/microsoft/vscode/issues/26777 as this will allow you to do that. Closing as duplicate.
