### ISSUE TITLE
Ctrl+Click does not properly unselect file in explorer/tree view

### ISSUE THREAD

**Issue by jkpubsrc** [microsoft/vscode#110301]
VSCode Version: 1.50.1

Steps to Reproduce:

1. In the explorer/tree view mark multiple files. E.g.: Click on one file in a directory, hold shift and scroll down and click on another file. Then let go of shift again. (The classic way of selecting multiple files.)
2. Hold Ctrl and click on any of the marked files. (The classic way of unselecting a file from a multi-file selection.)
3. Now delete the file via pressing the delete-button on the keyboard.

Result encountered:
- Not the selected files are gone, but the unselected file.

Result expected:
- The selected files should be gone now, not the unselected file.

I'm not running the very latest version, so please try to reproduce this in a more recent version.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/108885
