### ISSUE TITLE
Tip to convert to ES6 module gives error

### ISSUE THREAD

**Issue by lborgman** [microsoft/vscode#110358]
Issue Type: <b>Bug</b>

VS code suggested I could convert a require statement to ES6 import in a Node.js app. I let VS code do that and then got an error when running the app:

> &gt; node myapp.js
import { platform } from "os";
^^^^^^
SyntaxError: Cannot use import statement outside a module

>node -v
v12.18.4

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU N4200 @ 1.10GHz (4 x 1094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.84GB (0.70GB free)|
|Process Argv|--crash-reporter-id 2db228e7-570f-43a0-b1bf-75f2af041a44|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.3
cursor-charcode|but|0.9.2
firecode|ChF|1.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|10.2.3
vscode-sort|hen|0.2.5
beautify|Hoo|1.5.0
svg|joc|1.4.1
powershell|ms-|2020.6.0
material-icon-theme|PKi|4.4.0
partial-diff|ryu|1.4.1
vim|vsc|1.17.1
json|Zai|2.0.2

</details>

**Comment by mjbvz** [comment]
You can't use import statements in an environment that doesn't support them (such as node 12). VS Code shows this suggestion because it doesn't know what your target environment and many users are in environments where imports are preferable to requires. Try setting up a jsconfig if you want to configure this
