### ISSUE TITLE
Creating launch config opens extensions tab when it should show additional launch snippets

### ISSUE THREAD

**Issue by fabioz** [microsoft/vscode#110334]
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363

When creating a new launch configuration in the workspace if there are no previous launch items, VSCode shows only a truncated list of items initially with a `More...` entry, and when selecting `More...` it ends up bringing up the window to install extensions (which doesn't seem to make sense for me in this context) instead of showing the other launch configurations to launch (this seems to happen only if the `launch` section is still not at the workspace file or related launch.json).

Below is a list with the images for the current process for a new launch configuration in the workspace (where in this case there's no `launch` entry yet):

![im1](https://user-images.githubusercontent.com/117621/98711681-128f1200-2364-11eb-8a5c-e64428139cea.png)
![im2](https://user-images.githubusercontent.com/117621/98711697-1753c600-2364-11eb-8480-cb1112213f42.png)

Result of selecting `More...`:

![im3](https://user-images.githubusercontent.com/117621/98711707-191d8980-2364-11eb-8e94-af6f12539182.png)

If I pre-create the launch section in the workspace file with:

```
	"launch": {
		"version": "0.2.0",
		"configurations": [
			
			
		]
	}
```

it does seem to do the right thing (which is opening the workspace settings file and providing a list of suggestions and is what I expected it to do in the first place).

![image](https://user-images.githubusercontent.com/117621/98711854-4d914580-2364-11eb-80fa-2b21ffaff606.png)

In fact, I believe it should always do this... is there any reason for that truncated list of launch configurations to appear in the first place? Is that customizable?

**Comment by weinand** [comment]
@fabioz this works as designed:
- if there is no launch.json (neither as a file nor as an embedded workspace setting), VS Code presents the list of "debugging environments" that are able to provide a **complete launch.json** (= a full set of launch configuration). This is not a truncated list of launch configurations! It is the list of all installed debuggers. The "More.." action lets you find and install even more debuggers. The idea is to let users decide what debugger to use for a project.
- if there is already a launch.json (empty or more likely: not empty), it does not make sense to "flood" it with a set of launch configuration for a single debugger. So here VS Code does not ask users for selecting a debugger. Instead it presents a list of single debug configurations (contributed by the installed debuggers).

@isidorn please chime in if my explanation is incorrect.

**Comment by fabioz** [comment]
Humm, in this case, I have 3 other installed extensions which also have debuggers -- with configuration snippets (and for which the completions snippets appear afterwards) but they don't appear here (i.e.: Python/Robocorp Code/Robot Framework Language Server), so, it doesn't seem to be the list of all installed debuggers (which is why I'm a bit confused by the suggestion to install other extensions with `More...`):

![image](https://user-images.githubusercontent.com/117621/98748931-75e76700-2399-11eb-8c8b-52cf81de37b1.png)

Still, if that's not the trimmed list, maybe extensions with debuggers need some additional configuration to appear there? If that's the case, can you point me to some docs which explains how to do that so that it'd appear in that list? (Until now I thought all an extension needed was having a debugger with a configuration snippet for all UI-related settings, but this doesn't appear to be the case here... is this a feature or a bug?)

**Comment by weinand** [comment]
Only debuggers with a `initialConfigurations` contribution are listed in the QuickPick menu. If a debugger does not provide "initial configurations" then it is not helpful for population the launch.json. The Python debugger is an example for this.

Please see paragraph starting with  "The initialConfigurations define the initial content..." in the [Debugger Extension documentation](https://code.visualstudio.com/api/extension-guides/debugger-extension#anatomy-of-the-package.json-of-a-debugger-extension).

**Comment by fabioz** [comment]
Well, it seems that's a feature and not a bug then ;)

I think it may be a tad confusing having a different behavior if the launch is empty vs not being empty (i.e.: why can't I pick that initial configuration if there's one launch already and why can't I get one of the other snippets if there's still no launch), but then again, the extensions I expected to use didn't provide such a configuration, so, this probably added even more to my confusion.

i.e.: I expected the behavior to be always the same -- maybe having the `initialConfiguration` options always brought up from the `Add Config` and having `More...` always present the other configuration snippets instead of showing extensions to install?

Anyways, feel free to close this if you don't plan to change how this works (I'll check to make sure the extensions I'm interested in actually do provide the `initialConfiguration`).

Thank you for taking the time to explain how it works.

**Comment by weinand** [comment]
@fabioz thanks for providing valuable feedback - the fact that you were confused about the contents of the QuickPick is already an indication that there is room for improvement.

@isidorn I suggest that we leave this issue open and start a discussion for how to improve the experience.

**Comment by isidorn** [comment]
@weinand just to confirm that your explanaition from above is indeed how we behave. And yes we can leave this open. Thanks
