### ISSUE TITLE
There is no feedback if failed to click to goToDefinition

### ISSUE THREAD

**Issue by ayqy** [microsoft/vscode#110393]
- VSCode Version: 1.51
- OS Version: OSX 10.15.5 (19F101)

Steps to Reproduce:

1.`import some from 'moduledoesnotexist';`
2.CMD + Click to goToDefinition
3.Failed to go, and **there's no feedback message** (`No definition found for 'moduledoesnotexist'` like commands or context menu)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ayqy** [comment]
Dig one step deeper, #23978 seems to be the original reason.

**Comment by jrieken** [comment]
Please attach the file/project in which this reproduces

**Comment by ayqy** [comment]
file `demo.js`:

```
import a from 'thisModuleDoesNotExist';
```

Right click `'thisModuleDoesNotExist'` or execute `go to definition` command and go to definition:

![image](https://user-images.githubusercontent.com/12402989/98909642-10ac8680-24fd-11eb-8e76-e87901e5659b.png)

Keyboard shortcut `CMD + Click` to go to deinfition:

![image](https://user-images.githubusercontent.com/12402989/98909860-58cba900-24fd-11eb-8f0d-31ddf83c1ec2.png)

Expect a definition not found tip here.

**Comment by jrieken** [comment]
> Keyboard shortcut CMD + Click to go to deinfition:

 The cmd+click gesture check if there is a definition before making a word a link. I don't see an underline and link color when hovering over the word while holding cmd. That means there is nothing to navigate to and therefore there is no message about a missing definition. Do you see a link being rendered?

**Comment by ayqy** [comment]
> Expect a definition not found tip here.

IMO, link navigation should be separated from cmd+click gesture, the problem is a kind of gesture conflict, no link navigation (so as to keep silent) may not affect no definition found message.

**Comment by ayqy** [comment]
1. cmd+click a link, then do not go to definition, just open URL
2. cmd+click a module, then just go to definition, do not try to open URL
3. cmd+click a existing module, then open one target file or peek definitions
4. cmd+click a non-existing module, then show module not found message (*which is silent now*)

**Comment by jrieken** [comment]
> cmd+click a non-existing module reference, then show module not found message (which is silent now)

That's where I disagree and why I am closing this. The cmd+click gesture is only valid for links and the link will show when cmd+hovering over a _valid_ target.

**Comment by ayqy** [comment]
> The cmd+click gesture is only valid for links

It's not true (from user's view), because go to definition shortcut seems to be cmd+click in a long time, and the kind of gesture conflict exists all the time.

**Comment by mjbvz** [comment]
Go to definition is bound to `f12`. It shows an alert if no definition is found

cmd+click is a convenience for quickly navigating through code with the mouse. In this case, the lack of a link being rendered is the feedback that no definition has been found

**Comment by ayqy** [comment]
@mjbvz Thanks for your explanation, I know 'as-designed' now.

My consideration is whether no definition found should be a bit more explicitly (than lack of a link rendered now)? especially in certain cases:

- A 3rd DefinitionProvider extension: failure message may be important for users. (BTW, custom failure message may be a feature request.)
- Modified Go to definition keyboard shortcut(eg. Sublime Text keymap ctrl+click on Mac): some users told us they can not go to anywhere use cmd+click, we have to ask them 'Right click and select go to definition, then can you go to there?' to rule out modified shortcut.

I agree with the interesting convenience, but I notice *the missing feedback message*, and an explicit feedback for goToDefinition result is essential from my point of view, because click is a stronger action than hover, users maybe expect a stronger feedback.
