### ISSUE TITLE
freeze randomly

### ISSUE THREAD

**Issue by Caligulaa** [microsoft/vscode#110337]
Issue Type: <b>Bug</b>

oracle vm running ubuntu 18.04

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:16:10.374Z)
OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor (6 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|12.19GB (4.75GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 8f52aa54-cdbd-4087-b6d4-4cb14a8c84bf|
|Screen Reader|no|
|VM|50%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.13
es7-react-js-snippets|dsz|3.0.0
prettier-vscode|esb|5.7.1
mithril-emmet|Fal|0.7.6
python|ms-|2020.10.332292344
material-icon-theme|PKi|4.4.0
LiveServer|rit|5.6.1
vscode-import-cost|wix|2.12.0

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by Caligulaa** [comment]
disabled 3d acceleration in my VM settings, seems like it solved it!
