### ISSUE TITLE
Command to show excluded files

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#110315]
A command to temporarily show excluded files. A sort of toggle switch for `files.exclude`.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by usernamehw** [comment]
This extension might help: https://marketplace.visualstudio.com/items?itemName=eamodio.toggle-excluded-files

**Comment by isidorn** [comment]
Great! So please use that extension. Thus closing this
