### ISSUE TITLE
Add hotkey for `Toggle Search Details`

### ISSUE THREAD

**Issue by nikitavoloboev** [microsoft/vscode#110326]
When user is in search view like here:

![image](https://user-images.githubusercontent.com/6391776/98705932-8807dc00-237e-11eb-86d4-86502bd84c4f.png)

I'd love to be able to activate `Toggle Search Details ` from a hotkey. This action:

![CleanShot 2020-11-10 at 18 00 14](https://user-images.githubusercontent.com/6391776/98706012-9d7d0600-237e-11eb-8942-4dab012a92b5.png)

Currently it's only available to be activated with mouse only I believe. I searched in keybindings & docs. Please add such an action. Thank you.

**Comment by usernamehw** [comment]
`workbench.action.search.toggleQueryDetails`

![Screenshot (376)](https://user-images.githubusercontent.com/9638156/98707801-80056780-2391-11eb-9b38-893b03149fa8.png)

**Comment by roblourens** [comment]
That's it, thanks @usernamehw!
