### ISSUE TITLE
Add color of tab label

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#110310]
![Screenshot (375)](https://user-images.githubusercontent.com/9638156/98674648-2b022b00-236a-11eb-9be0-211c42ea2f27.png)

Right now it's at `0.7` opacity of the tab color. If the tab color has a lot of contrast (`#000000` on `#ffffff`) the difference is too small. On the other hand, when contrast is already bad, then the label is barely readable.

Adding a new color might be a solution.

**Comment by misolori** [comment]
We intentionally do this in several areas so that we don't have to define a new color token. For this label, we'd need to update everywhere where it's being used (open editors, scm, debug, etc.)
