### ISSUE TITLE
Git: stash all changes in sidebar has no effect

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode#110390]
Issue Type: <b>Bug</b>

1. Have a bunch of changes
2. Click the icon for stash all changes
3. Enter stash message
4. nothing happens

![ezgif-6-3a999e679625](https://user-images.githubusercontent.com/17641229/98813644-cf48a800-2424-11eb-963c-e886b6aea17a.gif)

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (15.74GB free)|
|Process Argv|--crash-reporter-id 334f021d-210d-4760-a7f9-f7e771ce0905|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.3
toggle-excluded-files|eam|1.7.0
EditorConfig|Edi|0.15.1
RunOnSave|eme|0.2.0
json-tools|eri|1.0.2
prettier-vscode|esb|5.7.1
vscode-pull-request-github|Git|0.21.0
vscode-test-explorer|hbe|2.19.3
rest-client|hum|0.24.4
template-string-converter|meg|0.2.7
compare-folders|mos|0.18.0
vscode-docker|ms-|1.7.0
vscode-language-pack-de|MS-|1.51.2
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.2
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.3
hexeditor|ms-|1.3.0
vscode-js-profile-flame|ms-|0.0.13
vsonline|ms-|1.0.3075
hide-gitignored|npx|1.1.0
vscode-jest|Ort|3.2.0
typescript-mono-repo-import-helper|q|0.0.6
project-snippets|reb|0.5.0
java|red|0.70.0
vscode-sort-json|ric|1.18.1
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.25.0
vscode-icons|vsc|11.0.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by joaomoreno** [comment]
I believe this is GitLens.

**Comment by AlCalzone** [comment]
Update: it does seem to work if the number of changes is small (a handful of files). The 215 files above seem to be to much.

**Comment by eamodio** [comment]
@AlCalzone Yeah, this is from GitLens. Would you mind opening an issue on that repo. I'm pretty sure I am hitting some command line file limit, but there should probably be a warning when that happens.

**Comment by AlCalzone** [comment]
✔
