### ISSUE TITLE
VSCode Git doesn't see files moved into subdirectory

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#11039]
- VSCode Version: 1.4.0
- OS Version: Windows 10 Anniversary Update
- Git Version: `git version 2.8.1.windows.1`

Steps to Reproduce:

1. Clone a Git repository (https://github.com/SocketCluster/sc-sample-inventory)
2. Move everyting from root folder into subfolder
3. VSCode doesn't show / commit changes

![image](https://cloud.githubusercontent.com/assets/466713/18023772/8d3fc99c-6bba-11e6-9347-fc4985d093c9.png)

This resulted in me "losing" tons of files in my project. I had to go to the Git command line to "see" the modified files and commit them. @joaomoreno @bpasero 

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by joaomoreno** [comment]
The screenshot shows that you have opened `inventory-app`, not `sc-sample-inventory`. It also shows a bunch of files that are not in that repository (`docker-compose.yml` for example).

Also into which subfolder should I move everything?

**Comment by pcgeek86** [comment]
@joaomoreno Yes, the `inventory-app` is a private fork of `sc-sample-inventory`. That is why you see a slight discrepancy between the screenshot and the repro steps. We don't allow access to the private fork.

We moved everything into a subfolder named `frontend`, though in theory, the name of the subfolder should be irrelevant.

**Comment by joaomoreno** [comment]
The thing is: I can't reproduce it. I also doubt you can reproduce it in another repository.

Without those original bits, it's hard for me to know what kind of setup your repository has and let you know what the problem is.

**Comment by pcgeek86** [comment]
@joaomoreno We literally just forked the repository and cloned it locally. Thanks for trying to reproduce it. Let me see if I can repro using our private fork again, and I'll reopen with more specific steps.
