### ISSUE TITLE
Running dotnet test on WSL1 debian10 sometimes turns off echo

### ISSUE THREAD

**Issue by gxtaillon** [microsoft/vscode#110364]
Issue Type: <b>Bug</b>

Run dotnet test from the vscode terminal (16.7.0)
Type in anything after it finishes
**Sometimes**
Text will not appear

Typing in `stty echo` fixes it and inputs appear again.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (17.97GB free)|
|Process Argv|--file-uri vscode-remote://wsl%2Bdebian/home/gtaillon/AribaIntegrations/Cae.Digital.AribaSoapGateway.code-workspace|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|Memory (System)|31.88GB (17.97GB free)|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by gxtaillon** [comment]
![image](https://user-images.githubusercontent.com/567119/98761619-d9769200-23a3-11eb-9c11-f0b6a22543f2.png)

**Comment by connor4312** [comment]
Does this reproduce if you set `"terminal.integrated.localEchoLatencyThreshold": -1`?
