### ISSUE TITLE
Git: Investigate using `vscode.open` and `vscode.diff` as commands in scm

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#110397]
Currently SCM has a custom mechanism for opening resources: SCM providers provide a command for each resource (git provides `git.openResource`) and it does some magic behind the scenes to be sure that command gets passed the right Resource when invoked. But this custom approach can never align with all the UI gestures and settings related to editor opening actions (preview, to side, etc).

We should investigate whether its feasible for git to simply provide `vscode.open` and `vscode.diff` as the Resource opening commands. That way the core can gives us all the preview, open to side, features. 

Related:

- https://github.com/microsoft/vscode/issues/85636#issuecomment-725947147
- https://github.com/microsoft/vscode/issues/109393

**Comment by bpasero** [comment]
I landed my changes, if an extension is using `vscode.open` or `vscode.diff` for `TreeItem`, we pass over the context of the list.

To adopt this in SCM, we need something similar like this code right before we invoke the command of a SCM tree item:

https://github.com/microsoft/vscode/blob/630e706ad2de99e255a18bf77f72d569e9fc0e49/src/vs/workbench/contrib/views/browser/treeView.ts#L468-L475

**Comment by joaomoreno** [comment]
Thanks @bpasero, looks awesome!

**Comment by joaomoreno** [comment]
@bpasero Check it out:

https://github.com/microsoft/vscode/commit/ed4d86eba279cda7b6aa8e60e687ba2added0b88#diff-a29d112f7e1fecae5536543510588375d7283d06e96a4cf64325e8b600f30356R1940-R1941

It is mostly working with some very weird behavior, on which I will need your help next week:

![image](https://user-images.githubusercontent.com/22350/99094278-e5e13180-25d3-11eb-967b-c6982d5250a6.png)

**Comment by joaomoreno** [comment]
cc @eamodio
