### ISSUE TITLE
Incorrect locale 'en-US' used everywhere (Electron issue?)

### ISSUE THREAD

**Issue by koxu1996** [microsoft/vscode#110322]
- VSCode Version: 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a) x64
- OS Version: ArchLinux x64 5.9.6

Today I upgraded _electron_ from _9.3.3-1_ to _9.3.4-1_ and many extensions stopped working in _VSCode_, due to incorrect locale, eg. Python:
![image](https://user-images.githubusercontent.com/6506780/98695907-74a34380-2373-11eb-82d4-5addf7a928ee.png)
![image](https://user-images.githubusercontent.com/6506780/98695923-7b31bb00-2373-11eb-8687-d30f6c9743ce.png)

Probably it's related to https://github.com/electron/electron/issues/23272, but I want to let you know.

**Comment by wooque** [comment]
Same issue here, this message pops in integrated terminal, though it seems it didn't break anything in my setup.

**Comment by stakaz** [comment]
Same here. For me it breaks lualatex compilation with LaTeX-Workshop extension.

**Comment by wooque** [comment]
This PR is backported to 9.3.4, could be the culprit https://github.com/electron/electron/pull/26185

**Comment by tamuratak** [comment]
The VS Code package on Arch Linux is a custom build. The current version of Electron of the official build is `9.3.3`.  You should report this issue to Arch Linux.

- https://github.com/microsoft/vscode/blob/a856e60a0cfcc9609f46855062162e8aa4b69c08/.yarnrc#L2
- https://github.com/archlinux/svntogit-community/tree/packages/code/trunk

**Comment by starquake** [comment]
Arch Linux splits Electron from VS Code and always has the most recent version available from upstream. It looks like something broke in 9.3.4: https://github.com/electron/electron/issues/26443

So I guess we should wait for an update with a fix.

**Comment by lights0123** [comment]
I opened that issue in electron's issue tracker after experiencing this exact problem in VS Code, so yes, that is the problem.

**Comment by jorgelaranjo** [comment]
Great, meanwhile the latest Jupyter extension is not compatible with VS Code 1.45 and 1.51 has the LOCALE problems.

**Comment by telmotrooper** [comment]
For anyone having this issue on Arch Linux, downgrade package `electron9` from `9.3.4` to `9.3.3`.

```
curl -O https://archive.archlinux.org/packages/e/electron9/electron9-9.3.3-1-x86_64.pkg.tar.zst
sudo pacman -U electron9-9.3.3-1-x86_64.pkg.tar.zst
```
You'll probably want to add `electron9*` to `IgnorePkg` in `/etc/pacman.conf`, so the next time you update your packages you won't accidentally update this one as well. When a fix has been deploy you can remove this setting...

**Comment by endorsystems** [comment]
@telmotrooper This works. Thanks!

**Comment by ejose19** [comment]
@telmotrooper Thanks, be sure to also download the signature (https://archive.archlinux.org/packages/e/electron9/electron9-9.3.3-1-x86_64.pkg.tar.zst.sig) along the package and check ```pacman.conf``` so that ```LocalFileSigLevel = Required```(or unset and ```SigLevel = Required```), as you probably don't want to install unsigned packages.

**Comment by lights0123** [comment]
You can also just do `sudo pacman -U /var/cache/pacman/pkg/electron9-9.3.3-1-x86_64.pkg.tar.zst`, as you probably have it still cached.

**Comment by stuartpb** [comment]
Just adding, for anyone looking for a low-hanging-fruit workaround, `LC_ALL=en_US.UTF-8 code --lang=en_US.UTF-8 --set-lang=en_US.UTF-8` (ie. all of the `LC_ALL` environment variable, old `--lang` option that the blamed PR said didn't work, and `--set-lang` option that the PR appears to implement instead) still results in the `en-US` locale issue appearing in the first terminal you see.

**Comment by lights0123** [comment]
Yep, because the Electron source code reads the locale passed from the command line, but then immediately overrides it:

https://github.com/electron/electron/blob/ef674025b5e17845e48a4d55721ea1a5583c4d04/shell/browser/electron_browser_main_parts.cc#L385-L387

**Comment by lights0123** [comment]
The fix [has been merged upstream](https://github.com/electron/electron/pull/26508): the next release will include the fix.

**Comment by deepak1556** [comment]
Closing this as vscode master is on `9.3.3` and the upstream issue was first observed in `9.3.4`

**Comment by wleoncio** [comment]
> Just adding, for anyone looking for a low-hanging-fruit workaround, `LC_ALL=en_US.UTF-8 code --lang=en_US.UTF-8 --set-lang=en_US.UTF-8` (ie. all of the `LC_ALL` environment variable, old `--lang` option that the blamed PR said didn't work, and `--set-lang` option that the PR appears to implement instead) still results in the `en-US` locale issue appearing in the first terminal you see.

Is it possible to have VSC run a script or even a 1-liner before opening an intergrated terminal? I've seen similar issues back from 2016 which were solved by adding `export LC_ALL=[whatever]` to the shell configuration file (e.g. `.bashrc`), but I tried that and it didn't work.
