### ISSUE TITLE
terminal text showing not good at first load

### ISSUE THREAD

**Issue by zareshahi** [microsoft/vscode#110302]
Hello 
recently my terminal dont show text spaces currectly and insert space between charachters 
![image](https://user-images.githubusercontent.com/7747315/98662113-8e855c00-235c-11eb-92e3-cdd9d020f99f.png)
but after resize panel its been ok!

**Comment by zareshahi** [comment]
it's fixed for me by change terminal font family in vscode settings 
but in older versions its worked currectly

**Comment by Tyriar** [comment]
Can you share your settings.json file when it wasn't working correctly? Also can you provide OS information?
