### ISSUE TITLE
[Problems Panel] No problems are listed even though the count is shown and no filters are applied (Screenshot)

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode#110394]
- VSCode Version: 1.52.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Write code with syntax errors
2. open "Problems" panel

In this screenshot, there are no filters are enabled and problem count is shown to be 19
![image](https://user-images.githubusercontent.com/15051871/98818735-f7023500-2451-11eb-81d6-57f7d2357885.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by stagefright5** [comment]
The duplicate tagged by the VS code is not actually a duplicate as that issue applies a filter and that is related to notebook editor

**Comment by sandy081** [comment]
/duplicate

ttps://github.com/microsoft/vscode/issues/110410.
