### ISSUE TITLE
Any way to support untitled notebooks?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#110343]
I'd like to support creating untitled notebooks for ephemeral "scratchpad" style use. Is there any way this can be done? I've tried `openNotebookDocument` with an `untitled` scheme URI but it threw a "no filesystem provider registered for scheme. error.

```ts
vscode.notebook.openNotebookDocument(
				vscode.Uri.joinPath(vscode.Uri.parse('untitled:').with({ path: vscode.workspace.workspaceFolders?.[0].uri.path }), 'scratch.hdnb'),
				'handydandy-notebook');
```

**Comment by JacksonKearl** [comment]
i remember we used to have `File -> New Untitled File` show a notebook provider quick pick, but that was too invasive. What if we perhaps had a `File -> New Untitled Notebook` that showed the quick pick?

**Comment by rebornix** [comment]
This can be done currently by running commands

```
{
		"key": "cmd+i",
		"command": "workbench.action.files.newUntitledFile",
		"args": {
			"viewType": "github-issues"
		}
	},
```

**Comment by JacksonKearl** [comment]
fabulous
