### ISSUE TITLE
Don't display autocomplete code snippets when typing comments.

### ISSUE THREAD

**Issue by louisl** [microsoft/vscode#110325]
Minor annoyance, I comment code a lot especially PHP. I find quite often that I end up autocompleting the first code snippet result instead of a new line when hitting 'return' when creating multi-line comments. Apologies if this is already a setting but I didn't see it.

**Comment by jrieken** [comment]
I assume with "code snippet" you mean any suggestion, not necessarily a snippet suggestion, right? Anyways, for suggestion as you type (aka quick suggestions) there this setting: `editor.quickSuggestions` and you can configure them to be off inside comments, like so: `"editor.quickSuggestions":{"comments": false},`
