### ISSUE TITLE
Also After Adding JSON schema you told ... color pickers are not appearing ...

### ISSUE THREAD

**Issue by star-warrior** [microsoft/vscode#110380]
![Capture](https://user-images.githubusercontent.com/69752445/98798288-babfdc00-2433-11eb-8b56-4cb09ed7be3f.PNG)

I was having issue of color picker disappearing in JSON files ... i read your solution in the same issue ... i followed it , but didnt work ...

## I am sending you my `settings.json` ... i followed your steps 
![Capture1](https://user-images.githubusercontent.com/69752445/98798757-40438c00-2434-11eb-9205-83a07b7e76ba.PNG)

## this is the `theme.json` file 
![Capture2](https://user-images.githubusercontent.com/69752445/98798815-4a658a80-2434-11eb-8e64-e3a7dec7f96f.PNG)

plz help me

Steps to Reproduce:

1. Just copy the json.schema in your settings.json 
2. Check a json file with hex colors ... 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
- It's `"format": "color-hex"`
- If you want me to paste the `json.schema` in my settings.json please add the text, not the screenshot
- The format of `json.schema` looks wrong. See here how to associate a file with a schema: https://code.visualstudio.com/docs/languages/json#_mapping-to-a-schema-defined-in-settings
- how is the screenshot for theme.json related to the schema above?

**Comment by JayMehtaJBM** [comment]
Ok ... I'll send you the text ... Actually I am trying to create my custom
theme .. so I first edited dark_plus.json file .. which had color pickers
... But when I opened drqcula.json it didn't had color picker ... So I
asked in Google and read a issue which was 2 years old .. I tried to
replicate that but didn't work ... So I made a new issue ... Thanks for
replying ...
