### ISSUE TITLE
strange shapes rendered in vscode, mainly integrated terminal

### ISSUE THREAD

**Issue by luboi75** [microsoft/vscode#110378]
- VSCode Version: 1.50.1
- OS Version: Linux manjaro 5.8.18-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020 x86_64 GNU/Linux

Steps to Reproduce:

1. start vscode
2. start integrated terminal 
3. type enter several times
4. integrated terminal is unreadable, lines broken, blue triangle rendered in top left corner of the terminal, parts of text of the line rendered using color identical to background color

Does this issue occur when all extensions are disabled?: Yes
sligthly less prominent, text in terminal still broken, does not render strange triangles

**Comment by luboi75** [comment]
![image](https://user-images.githubusercontent.com/10387971/98794946-f04fcf80-2409-11eb-9c9b-b32ef55cdb23.png)
![image](https://user-images.githubusercontent.com/10387971/98794984-f9d93780-2409-11eb-971f-53ce0a694f63.png)
these are screenshots of incorrectly rendered terminal window

**Comment by meganrogge** [comment]
Thanks for the issue. I'm not able to reproduce it. Can you please attach a gif with all extensions disabled?

**Comment by meganrogge** [comment]
Looks like a problem with Chromium GPU acceleration in <canvas>, you can try updating your graphics driver and if that doesn't work you can move to the DOM-based renderer with this setting:
`"terminal.integrated.rendererType": "dom"`
/label integrated-terminal *question

**Comment by luboi75** [comment]
thank you.
I used suggested setting change (since environment I use vscode in is virtual machine)
it fixed the worst part ...
