### ISSUE TITLE
Can't use default commit message when merge conflicts

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode#110316]
Issue Type: <b>Bug</b>

When doing a `git merge <branch>`, if there are merge conflicts, the merge is paused until the conflicts are resolved. In VSCode, any conflicting files appear in the source control as conflicted. After I resolve them and stage them, I want to finish the merge. If I commit from the command line (`git commit`) I am presented with a default commit message (something like "Merge branch X into branch Y"). However, if I finish the merge commit from VSCode (by clicking the commit button), I am prompted for a commit message with an epmty box.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.9.0-0.bpo.6-amd64
Remote OS version: Linux x64 5.9.3-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.44GB free)|
|Process Argv|--crash-reporter-id 6949b6e9-d952-4b8f-a136-284374926c80|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mews7748|
|OS|Linux x64 4.9.0-0.bpo.6-amd64|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4026)|
|Memory (System)|15.54GB (0.56GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 127.0.0.1|
|OS|Linux x64 5.9.3-arch1-1|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (1 x 1895)|
|Memory (System)|1.94GB (1.04GB free)|
|VM|100%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
remote-ssh|ms-|0.55.0
remote-ssh-edit|ms-|0.55.0
material-icon-theme|PKi|4.4.0
gitlens|eam|10.2.3
todo-tree|Gru|0.0.187
me-vscode|ME-|0.0.9
git-graph|mhu|1.27.0
python|ms-|2020.10.332292344
cpptools|ms-|1.1.1
hexeditor|ms-|1.3.0

</details>

**Comment by joaomoreno** [comment]
This is already implemented. When the merge conflict happens, the input box should show Git's default message:

![recording (9)](https://user-images.githubusercontent.com/22350/98693936-3016a880-2371-11eb-95d3-71829daae779.gif)

**Comment by BMBurstein** [comment]
@joaomoreno This is not what I am seeing. How did you record it? I will record it to show you.

**Comment by joaomoreno** [comment]
You can use [gifcap](https://gifcap.dev/)?

**Comment by BMBurstein** [comment]
I don't know what I did before to cause this, but I am unable to reproduce it again. Thank you anyway!
