### ISSUE TITLE
workbench.files.action.showActiveFileInExplorer broken

### ISSUE THREAD

**Issue by PFight** [microsoft/vscode#110346]
- VSCode Version: 1.51.0
- OS Version: Windows 8.1

Steps to Reproduce:

1. Disable auto reveal current file in file explorer
2. Open some file
3. Scroll file explorer to make it not visible
4. Execute command workbench.files.action.showActiveFileInExplorer (via keybinding or directly over command panel)
5. File not revealed in file explorer, but focused in Open editors panel instead

Command broken after some of the last updates. Similar to #41097

Does this issue occur when all extensions are disabled?: Yes

**Comment by rajivsubra1981** [comment]
Can confirm the same issue being faced after the latest update.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/110188
We will ship a fix as part of the recovery release.
