### ISSUE TITLE
Notebook Kernel preload order is not retained

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#110338]
- VSCode Version: 1.52-insiders
- OS Version: Windows 10

Using this api 
```typescript
export interface NotebookKernel {
        preloads?: Uri[];
    }
```

Our preload list has more than one item. The order of these two items seems to be reversed from the order in the list.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
Preloads load in parallel; whichever gets executed first is a race on the network/browser side of things.

**Comment by DonJayamanne** [comment]
Can we change it to load in sync (or use `defer` or the like).
I don't think that'll hurt perf, as preloads for kernels only apply to the current kernel in question.
Thus if an extension author has 100 preloads, it slows down the `resolveNotebook` method & not any other extension author.

**Comment by connor4312** [comment]
Fixed in the linked commit. The scripts will be downloaded in parallel, but execution is serialized.
