### ISSUE TITLE
Validate dynamic configurations only on launch

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#110318]
Refs https://github.com/microsoft/vscode/issues/110009

**Comment by weinand** [comment]
I think early activation on startup is a bug, so this issue asks for a fix not for a feature.

**Comment by isidorn** [comment]
Makes sense, I have changed the labels.

**Comment by isidorn** [comment]
I have a pushed a change that tackles this. Now we will only activate extension once you start debugging. Please try it out and let me know how it works for you.

Missing piece unrelated to this change: it can happen that for whatever reason a dynamic configuration is no longer valid. In that case we show a bit of an ugly error message "Configuartion NAME not found in launch.json" once you start debugging.
We should improve that error wording.
Scenario when it happens: have a js file open, choose "Run Current File"  js-debug configuration. Open some non JS file. Hit F5 -> you get the error

fyi @connor4312
