### ISSUE TITLE
Insider version terminal broke after recent update

### ISSUE THREAD

**Issue by egucciar** [Microsoft/vscode#11034]
- VSCode Version: see picture (insider version)
- OS Version: Windows 7

![image](https://cloud.githubusercontent.com/assets/2848185/18015001/989b254c-6b93-11e6-8ac9-dcfaa4502687.png)

Steps to Reproduce:

1. Open Terminal
2. Observe it is not working :(

Downloaded and installed insider version this morning and it was pretty great, but a few hours later, the terminal stopped working!

**Comment by egucciar** [comment]
seems like this was an issue with not running the VSInsiders with elevated rights and/or the VSInsiders not being start up the right way. working now

**Comment by Tyriar** [comment]
@egucciar strange, you shouldn't have needed to launch with elevated rights. I just updated on my Windows 10 machine and it all went smoothly. If you have any more issues please reopen and paste in the contents of the develop tools log (Help > Toggle Developer Tools) and also any terminal-related settings in your `settings.json`.
