### ISSUE TITLE
getLangEnvVariable fallback to en_US.UTF-8 too early without checking locale -a

### ISSUE THREAD

**Issue by soiamsoNG** [microsoft/vscode#110366]
- VSCode Version: 1.51.0 fcac248b077b55bae4ba5bab613fd6e9156c2f0c
- OS Version: Linux x64 5.8.18-300.fc33.x86_64

Steps to Reproduce:

1. use terminal in container with default LANG=POSIX setting
2. getLangEnvVariable fallback to en_US.UTF-8 without checking **locale -a** and incorrect set LANG
in my case **locale -a** just support below 3.  it actually have utf-8 locale in this system.

C
C.UTF-8
POSIX

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by meganrogge** [comment]
@soiamsoNG what do you have `terminal.integrated.detectLocale` set to?

**Comment by jorgelaranjo** [comment]
This is a fresh new bug and widespread https://www.reddit.com/r/vscode/comments/jsdwvl/issues_with_internal_terminal_locale/
