### ISSUE TITLE
"Command not found loop"

### ISSUE THREAD

**Issue by Imadeddine503** [microsoft/vscode#110387]
Whenever I start launch Git Bash (same if I start a bash terminal on VSCode) on my computer, it prints without stopping "bash: $'\377\376#': command not found" as shown in the picture. Is there any solution to this?
![image](https://user-images.githubusercontent.com/74302751/98811676-82af9d80-2421-11eb-970c-b782854a00b1.png)

**Comment by joaomoreno** [comment]
How is this related to VS Code? Seems like a bug in git.
