### ISSUE TITLE
cannot set a font included '+' in a name

### ISSUE THREAD

**Issue by usagi** [Microsoft/vscode#11033]
- VSCode Version: 1.4.0 6276dcb0ae497766056b4c09ea75be1d76a8b679
- OS Version: Microsoft Windows 10 Pro

Steps to Reproduce:
1. install a font include '+' in a name; for example, I tried ["Rounded Mgen+ 1mn medium"](http://jikasei.me/font/rounded-mgenplus/) ( Japanese ).
2. run the VSCode and open the `settings.json`
3. set the font; for example, to set `"editor.fontFamily": "Rounded Mgen+ 1mn medium"`.
4. save the `settings.json` and repro( the font will be not applied ).

**Comment by alexandrudima** [comment]
@usagi Would it work if you were to enclose in a second pair of quotes:

`"editor.fontFamily": "'Rounded Mgen+ 1mn medium'"`

Does the font work for you in Chrome:
http://codepen.io/anon/pen/ryxRXx

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
