### ISSUE TITLE
Code lens rendering issues are back

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#110354]
![image](https://user-images.githubusercontent.com/641685/98741565-e206a280-237a-11eb-8e15-a22430c1cb1e.png)

Switching away from the file and back again fixed it.

And did we change the font or font-size (or something) about the code lens? They look different to me.

**Comment by misolori** [comment]
I think this is a duplicate of https://github.com/microsoft/vscode/issues/110332
