### ISSUE TITLE
Typescript language features: No error output if typescript language server fails at startup

### ISSUE THREAD

**Issue by tsmaeder** [microsoft/vscode#110313]
I've had a case where tsserver fails at startup. Since ChildServerProcess in serverProcess.electron.ts never reads from stderr of the child process it forks, it's impossible to find out why the start-up fails. Logging does not help, since the logging is set up after the failure. 
stderr of language servers should be mirrored to the output of the typescript extension.

**Comment by tsmaeder** [comment]
V 1.49.3.

**Comment by mjbvz** [comment]
Please provide steps to reproduce the issue

**Comment by tsmaeder** [comment]
Provoke any condition that makes tsserver fail upon startup (in my case, I was running the typescript extension in a nexe-compiled plugin host in Eclipse Che, which crashes immediately, but I doubt that you'll want to do that ;-)). 

The problem lies here: https://github.com/microsoft/vscode/blob/64d126cafbac5e94519f635602e03a20b1f28db1/extensions/typescript-language-features/src/tsServer/serverProcess.electron.ts#L140

The code creates a child process with stdin, stdout and stderr piped to the parent process, Stdin and stdout are read/written to, but stderr is never referenced and therefore silently ignored. Note that _process.on('error', ...) does not get invoked when the process writes to stderr.

**Comment by mjbvz** [comment]
Would you like to submit a PR?
