### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by 4c74356b41** [Microsoft/vscode#11030]
- VSCode Version: 1.4.0 (says no updates available)
- OS Version: w10, 1511 10586.545

Its not a bug report, but could you implement a feature to set default language? I'm using powershell 90% of the time and the fact that I have to manually switch to powershell when editing any files is disturbing.

**Comment by mrmlnc** [comment]
Good idea to create the extension, but the current API does not allow you to change the language of document.

**Comment by mrmlnc** [comment]
You try use this extension https://github.com/brpaz/vscode-file-templates-ext?

**Comment by sandy081** [comment]
@4c74356b41 Please use the [Power Shell language extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell) for editing. If it does not works, please file an issue against the Power Shell extension repository. Thanks.

**Comment by 4c74356b41** [comment]
How does that help?
