### ISSUE TITLE
Two characters, seperated by Unicode U+200C (ZERO_WIDTH_NON_JOINER) are displayed as ligature (but shouldn't)

### ISSUE THREAD

**Issue by DrPepperBianco** [microsoft/vscode#110320]
Issue Type: <b>Bug</b>

The unicode point U+200C (ZERO_WIDTH_NON_JOINER) can be inserted between to characters to prevent ligatures.
That normally works everywhere else. But it doesn't work in Visual Studio Code.

I created a code file to see the effect of ligatures on certain code snippets. I put the non-ligatures in comments directly after it. In Visual Studio Code the characters spereated by the ZERO_WIDTH_NON_JOINER are still shown as ligature (which is wrong).

In settings.json I added the line » "editor.fontLigatures": true, « to activate ligatures.

Example (to test it, needs ligature font, like Fira Code):

<code>
<pre style="font-family: 'Fira Code', 'JetBrains Mono'">
public class Ligature_Test
{
    // 💡 Note: Unicode-Character U+200C (ZERO_WIDTH_NON_JOINER)
    //          prevents ligatures in comments.
    public static void Main(string[] args)
    {
        double a = 2.0, b = 3.0;

        if(a < b) { }   // <
        if(a > b) { }   // >
        if(a <= b) { }  // <‌=
        if(a >= b) { }  // >­=
        if(a == b) { }  // =­= 
        if(a != b) { }  // !­=

        // Lambda          =­>
        Action action = () => Console.WriteLine("Hello World");

        // Additionals:
        // && instead of &­‌&
        // || instead of |­‌‌|
        // ?? instead of ?‌?
        // ?. instead of ?‌.
        // // instead of /­/
        // /* and */ instead of /‌* and *‌/
    }
}

</pre>
</code>
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.79GB free)|
|Process Argv|. --crash-reporter-id e3469c50-d15f-4f29-9626-b8681f1602ec|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
delphi-pack|ale|2.0.0
numbered-bookmarks|ale|7.2.0
pascal|ale|9.2.0
pascal-formatter|ale|2.4.0
slncode|big|0.2.1
xml|Dot|2.5.1
gitlens|eam|10.2.3
vscode-solution-explorer|fer|0.3.11
r|Iku|1.5.2
shortcut-menu-bar|jer|1.5.0
vscode-icon-theme|jtl|1.6.6
sln-support|log|0.0.1
xslt-action|mar|0.0.2
csharp|ms-|1.23.5
remote-wsl|ms-|0.50.1
powershell|ms-|2020.6.0
vsliveshare|ms-|1.0.3121
team|ms-|1.161.1
vscode-xml|red|0.13.0
pdf|tom|1.1.0
omnipascal|Wos|0.18.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.3.0
vscode-proto3|zxh|0.5.2

(3 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
@DrPepperBianco VS Code is built with Electron, which is built with Chromium. The editor delegates font rendering to Chromium. I could reproduce the same behavior in Chrome (which is also based on Chromium) using a test page -- https://jsfiddle.net/afjwdhLv/ --. I also get the same rendering in Firefox, so I believe this is an intentional behaviour. If you don't agree, then please feel free to report against Chromium directly at https://bugs.chromium.org/p/chromium/issues/list

```
<div style="font-family: 'Fira Code'; font-feature-settings: 'liga', 'calt';">
   <div>&nbsp;&lt;=&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;&zwnj;=</div>
</div>
```

#### Chrome
![image](https://user-images.githubusercontent.com/5047891/98944324-274ce080-24f1-11eb-8f10-26c2bc1375e7.png)

#### Firefox
![image](https://user-images.githubusercontent.com/5047891/98944343-2d42c180-24f1-11eb-8873-893f26bb3031.png)
