### ISSUE TITLE
October 2020 Recovery Endgame

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#110347]
- [x] Create a milestone `<Month> <Year> Recovery` **@jacksonkearl**
- [x] Bump the version number **@jacksonkearl**
- [x] [🔖candidate issues](https://github.com/microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22October+2020+Recovery%22+label%3Acandidate+)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `master` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `master`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **@jacksonkearl**
- [x] Issues are verified on `stable` build and the `verified` label is added **@jacksonkearl**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **@jacksonkearl**
- [ ] Update the release notes and include a link to a query for the fixed issues **@ornellaalt**
- [x] [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test) stable bits  (⚠️ MUST run with `--stable-build` argument ⚠️ )
  - [x] Windows - **@bpasero**
  - [x] OS X - **@isidorn**
  - [x] Linux - **@RMacfarlane**
- [ ] Sanity check of installable bits
  - [ ] Windows 32 bit **@roblourens**
    - [ ] signed installer 32-bit
    - [ ] signed user installer 32-bit
    - [ ] zip 32-bit
  - [x] Windows 64 bit **@JacksonKearl**
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
  - [x] Windows ARM64 **@sbatten**
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
  - [x] OS X - **@JacksonKearl**
  - [x] Linux
    - [x] deb package 64-bit **RMacfarlane**
    - [x] rpm package 64-bit **RMacfarlane**
    - [x] archives **RMacfarlane**
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`) **RMacfarlane**
  - [x] Server ([instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
    - [x] Linux **RMacfarlane**
    - [x] macOS **@JacksonKearl**
    - [x] Windows **@roblourens** 
- [x] Publish website **@ornellaalt**
- [x] Publish stable build **@jacksonkearl**
- [x] Create an official release **@jacksonkearl**
  - [x] Create a tag: `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)

**Comment by gjsjohnmurray** [comment]
candidate issues link in the issue description seems to be faulty.

**Comment by JacksonKearl** [comment]
Fixed, thanks
