### ISSUE TITLE
Debugger stopped working

### ISSUE THREAD

**Issue by stoplion** [microsoft/vscode#110345]
- VSCode Version: insiders
- OS Version: 10.15.7

Steps to Reproduce:

Created a `launch.json`

Added Node `chrome` type debugger

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:5005",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```

Ran the debugger. VSCode opens up a browser and when I add a debugger (in VSCode, not writting debugger). When I run a React app, and it reaches the debugger line — VSCode pauses write where the debugger line is. It works correctly.

That was yesterday.

Nothing has changed.

Today the debugger is NOT working. VSCode does open the browser when I press the debugger button. But when it does not stop when it hits the debugger line.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@stoplion problem solved?
