### ISSUE TITLE
Add a command to create a repository on GitHub

### ISSUE THREAD

**Issue by inwardmovement** [microsoft/vscode#110381]
As there is a command to `Git: Clone`, it would be great to have a command to `Git: Create` that would leverage [GitHub CLI `gh repo create`](https://cli.github.com/manual/gh_repo_create)

**Comment by joaomoreno** [comment]
The command is `Publish to Github`.

**Comment by inwardmovement** [comment]
It does not leverage the whole [GitHub CLI `gh repo create`](https://cli.github.com/manual/gh_repo_create) prompts (template, etc.)
