### ISSUE TITLE
launch.json not detected / can't debug ASP.NET core app

### ISSUE THREAD

**Issue by benedikt-mayer** [microsoft/vscode#110312]
- VSCode Version: Version: 1.52.0-insider (user setup)
Commit: 65f805d98e798b979901b74d4c8810c05455b792
Date: 2020-11-10T08:05:00.147Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
- OS Version: OS: Windows_NT x64 10.0.19041 running WSL2

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/42207135/98677304-1f5c3780-235d-11eb-9cc7-e5f8e2d0c361.png)

1. Clone a minimal project such as https://github.com/cloudfoundry-samples/dotnet-core-hello-world
2. The C# extension does a restore and fetches the necessary files.
3. A basic launch.json is created automatically.
4. The debugger still prompts to create a launch.json file.

Does this issue occur when all extensions are disabled?: Yes, only the C# extension is enabled.

The same does not happen with an older version of vs code:
Version: 1.51.0 (system setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/110304
Pushed fix 2 hours ago
Thanks for letting us know
