### ISSUE TITLE
have semi-transparent popups (e.g. for autocomplete) when using CTRL key

### ISSUE THREAD

**Issue by geerligs** [microsoft/vscode#110385]
With Visual Studio Intellisense, I can hold down the CTRL key and popups become semi-transparent so I can see the code behind them.  Is there a way to get this same behavior with Visual Studio Code! Thanks!

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aeditor-hover
