### ISSUE TITLE
Ctrl + Left and Ctrl + Shift + Left do no match

### ISSUE THREAD

**Issue by duzenko** [microsoft/vscode#110303]
- VSCode Version: 1.50.1
- OS Version: Win10

Steps to Reproduce:

1. In a .ts file. have a line of code
```
		ctx.lineWidth = element.strokeWidth ?? 1;
```
2. Put cursor at the start of `strokeWidth`
3. Press Ctrl + Left. Cursor goes to the end of `element`
4. Go back to the start of `strokeWidth` and press Ctrl + Shift + Left
5. Cursor goes to the start of `element`

This is frustrating and counter-intuitive.

**Comment by alexdima** [comment]
@duzenko Can you please try to disable all extensions and comment out your `keybindings.json`?

**Comment by duzenko** [comment]
Yes, it's one of the extensions
