### ISSUE TITLE
Commit characters don't work when inside parens (TypeScript)

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#110382]
I'm not sure if this is deliberate and there's a reason for it (I couldn't find any issues that seem related), but I noticed than when pressing commit characters, the selected completion item is not selected if you're inside another function call.

![Nov-11-2020 10-43-26](https://user-images.githubusercontent.com/1078012/98802285-014d1080-240b-11eb-82b3-6e4e06a1db64.gif)

Here I typed `a(` and the `(` committed the call to `aaaaaaa`. However when I then did the same thing for the argument (again, pressing `a(`) it did not commit the completion, and instead just left `a(` instead of `aaaaaaa(`.

**Comment by jrieken** [comment]
Looks like no commit characters are defined here...

<img width="656" alt="Screenshot 2020-11-11 at 12 17 15" src="https://user-images.githubusercontent.com/1794099/98805477-e634cd80-2417-11eb-8f9f-92f093a60e58.png">

**Comment by DanTup** [comment]
I don't know if it's the same cause, but there are other places where they don't work either, for example:

Works here:

<img width="383" alt="Screenshot 2020-11-11 at 16 31 20" src="https://user-images.githubusercontent.com/1078012/98837912-76383e80-243b-11eb-9d45-755610189851.png">

But calling the same function at the top level, it does not:

<img width="457" alt="Screenshot 2020-11-11 at 16 31 37" src="https://user-images.githubusercontent.com/1078012/98837944-7f291000-243b-11eb-8ef8-7c031510f2aa.png">

**Comment by mjbvz** [comment]
Unfortunately we can't reliably compute commit characters on the VS Code extension side. This needs to come from the TypeScript server. Support for commit characters there is tracked by https://github.com/microsoft/TypeScript/issues/27623
