### ISSUE TITLE
High Memory utilization

### ISSUE THREAD

**Issue by nayakrpgcom** [microsoft/vscode#110305]
Issue Type: <b>Bug</b>

Open Angular project as a workspace

In terminal execute "ng serve".
Memory utilization will increase.

This problem was not there with 1.50.1

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
