### ISSUE TITLE
Add parenthesis after auto-completing methods if parenthesis NOT exists already

### ISSUE THREAD

**Issue by adurmus** [microsoft/vscode#110383]
It is annoying and time consuming when coding in angular template that a method name  needs to be changed It automatically adds parenthesis '()' without checking whether parenthesis already there.

Example:
`(click)="oldMethod()"`  while changing method name to `newMethod()` intellisense  helps you pick the method instead of typing all characters. However, you end up with duplicated parenthesis  like `(click)="newMethod()()"`  and you would click there to remove duplicated parenthesis.

**Comment by mjbvz** [comment]
This sounds like it's coming from your angular extension
