### ISSUE TITLE
Toggle Search Details in Search changes height for Search Results

### ISSUE THREAD

**Issue by torrao** [microsoft/vscode#110324]
Issue Type: <b>Bug</b>

- Search for a term
- Toggle Search Details
- Search results height become shorter

After toggling the search details a few times, the search results disappear.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 19.6.0

![screenCapture](https://user-images.githubusercontent.com/2873718/98702278-188bef80-2372-11eb-9da8-e91cd61e0140.gif)

**Comment by roblourens** [comment]
That's weird and I can't repro. Do you see any errors in the devtools (Help > Toggle Developer Tools)
